! Public Export umbrella for the MAPL.enums layer.
! All enum entities carry the MAPL_ prefix, so Export = Internal.
! This is what mapl/MAPL.F90 imports from.
module mapl_Enums_export
   use mapl_Enums_internal
   implicit none(type, external)
   private

   ! ConservationType
   public :: MAPL_CONSERVE_NONE, MAPL_CONSERVE_MASS
   public :: MAPL_CONSERVE_ENERGY, MAPL_CONSERVE_MOMENTUM
   public :: MAPL_ConservationType

   ! NormalizationType
   public :: MAPL_NORMALIZE_NONE, MAPL_NORMALIZE_DELP, MAPL_NORMALIZE_DZ
   public :: MAPL_NormalizationType

   ! QuantityType
   public :: MAPL_QUANTITY_UNKNOWN, MAPL_QUANTITY_MIXING_RATIO
   public :: MAPL_QUANTITY_CONCENTRATION, MAPL_QUANTITY_TEMPERATURE
   public :: MAPL_QUANTITY_PRESSURE, MAPL_QUANTITY_EXTENSIVE
   public :: MAPL_BASIS_NONE, MAPL_BASIS_WET_MASS, MAPL_BASIS_DRY_MASS, MAPL_BASIS_VOLUME

   ! VectorBasisKind
   public :: MAPL_VECTOR_BASIS_KIND_INVALID, MAPL_VECTOR_BASIS_KIND_GRID
   public :: MAPL_VECTOR_BASIS_KIND_NS, MAPL_VectorBasisKind

   ! ValidationMode
   public :: MAPL_VALIDATION_MODE_PERMISSIVE, MAPL_VALIDATION_MODE_STRICT
   public :: MAPL_ValidationMode

   ! VerificationStatus
   public :: MAPL_VERIFICATION_STATUS_UNVERIFIED, MAPL_VERIFICATION_STATUS_VERIFIED
   public :: MAPL_VERIFICATION_STATUS_CF_COMPLIANT, MAPL_VerificationStatus

   ! GenericPhases
   public :: MAPL_GENERIC_INIT_PHASE_SEQUENCE, MAPL_GENERIC_INIT_SET_CLOCK
   public :: MAPL_GENERIC_INIT_GEOM_A, MAPL_GENERIC_INIT_GEOM_B
   public :: MAPL_GENERIC_INIT_ADVERTISE, MAPL_GENERIC_INIT_MODIFY_ADVERTISED
   public :: MAPL_GENERIC_INIT_REALIZE, MAPL_GENERIC_INIT_READ_RESTART
   public :: MAPL_GENERIC_INIT_USER, MAPL_GENERIC_RUN_OFFSET
   public :: MAPL_GENERIC_RUN_CLOCK_ADVANCE, MAPL_GENERIC_RUN_USER
   public :: MAPL_GENERIC_FINALIZE_USER

   ! CouplerPhases
   public :: MAPL_GENERIC_COUPLER_INITIALIZE, MAPL_GENERIC_COUPLER_UPDATE
   public :: MAPL_GENERIC_COUPLER_INVALIDATE, MAPL_GENERIC_COUPLER_CLOCK_ADVANCE

   ! StateItemAllocation
   public :: MAPL_STATEITEM_ALLOCATION_INVALID, MAPL_STATEITEM_ALLOCATION_CREATED
   public :: MAPL_STATEITEM_ALLOCATION_INACTIVE, MAPL_STATEITEM_ALLOCATION_ACTIVE
   public :: MAPL_STATEITEM_ALLOCATION_CONNECTED, MAPL_STATEITEM_ALLOCATION_ALLOCATED

   ! FieldBundleType_Flag
   public :: MAPL_FIELDBUNDLETYPE_BASIC, MAPL_FIELDBUNDLETYPE_VECTOR
   public :: MAPL_FIELDBUNDLETYPE_BRACKET, MAPL_FIELDBUNDLETYPE_VECTORBRACKET
   public :: MAPL_FIELDBUNDLETYPE_SERVICE, MAPL_FIELDBUNDLETYPE_SERVICE_AGGREGATE
   public :: MAPL_FIELDBUNDLETYPE_SERVICE_SEPARATE, MAPL_FIELDBUNDLETYPE_INVALID

end module mapl_Enums_export
