ActualPtStateItemSpecMap – MAPL
ActualPtStateItemSpecMap Interface
5 statements
Source File
public interface ActualPtStateItemSpecMap
Calls
Module Procedures
private function map_new_map_empty() result(m)
Arguments
None
Return Value type(ActualPtStateItemSpecMap)
private function map_new_map_copy(x) result(m)
Arguments
Type Intent Optional Attributes Name
type(ActualPtStateItemSpecMap), intent(in) :: x
Return Value type(ActualPtStateItemSpecMap)
private function map_new_map_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(ActualPtStateItemSpecPair), intent(in) :: il(:)
Return Value type(ActualPtStateItemSpecMap)
Call graph
actualptstateitemspecmap calls map_new_map_copy, map_new_map_empty, map_new_map_initializer_list
map_new_map_initializer_list calls insert
map_insert_pair calls insert