apply_to_children – MAPL
apply_to_children Interface
3 statements
Source File
private interface apply_to_children
Calls
Called by
Module Procedures
private subroutine apply_to_children_custom(this, oper, rc)
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
procedure(I_child_op) :: oper
integer, intent(out), optional :: rc
Call graph
apply_to_children calls apply_to_children_custom
apply_to_children_custom calls get_outer_meta, get_gridcomp, mapl_return, mapl_verify, omap_begin, omap_iter_next
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
omap_begin calls omap_k_begin
omap_iter_next calls omap_k_iter_next
get_error_message calls at, insert
get_outer_meta_from_outer_gc calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_throw_exception calls initialize
initialize_advertise calls apply_to_children
initialize_geom calls apply_to_children
initialize calls initialize_advertise, initialize_geom