are_convertible – MAPL
are_convertible Interface
4 statements
Source File
public interface are_convertible
Calls
Called by
Module Procedures
private function are_convertible_udunit(unit1, unit2, rc) result(convertible)
Arguments
Type Intent Optional Attributes Name
type(UDUnit), intent(in) :: unit1
type(UDUnit), intent(in) :: unit2
integer, intent(out), optional :: rc
Return Value logical
private function are_convertible_str(from, to, rc) result(convertible)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: from
character(len=*), intent(in) :: to
integer, intent(out), optional :: rc
Return Value logical
Call graph
are_convertible calls are_convertible_str, are_convertible_udunit
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_are_convertible, ut_get_status, get_cptr, success
can_connect_units calls are_convertible
construct_converter calls are_convertible
test_are_convertible calls are_convertible
test_are_not_convertible calls are_convertible
converter calls construct_converter
can_connect_to calls can_connect_units, can_connect_to
connect_to calls can_connect_to, connect_to
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to
test_connect_unique_mirror calls can_connect_to
test_mirror_bracket_size calls can_connect_to