are_equal – MAPL
are_equal Interface
13 statements
Source File
public interface are_equal
Calls
Called by
Module Procedures
private function equals_i4_scalar(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(in) :: u
integer(kind=ESMF_KIND_I4), intent(in) :: v
Return Value logical
private function equals_i8_scalar(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I8), intent(in) :: u
integer(kind=ESMF_KIND_I8), intent(in) :: v
Return Value logical
private function equals_r4_scalar(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: u
real(kind=ESMF_KIND_R4), intent(in) :: v
Return Value logical
private function equals_r8_scalar(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: u
real(kind=ESMF_KIND_R8), intent(in) :: v
Return Value logical
private function equals_l_scalar(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: u
logical, intent(in) :: v
Return Value logical
private function equals_string(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(in), allocatable :: u
character(len=*), intent(in) :: v
Return Value logical
private function equals_i4_array(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(in), allocatable :: u(:)
integer(kind=ESMF_KIND_I4), intent(in) :: v(:)
Return Value logical
private function equals_i8_array(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I8), intent(in), allocatable :: u(:)
integer(kind=ESMF_KIND_I8), intent(in) :: v(:)
Return Value logical
private function equals_r4_array(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in), allocatable :: u(:)
real(kind=ESMF_KIND_R4), intent(in) :: v(:)
Return Value logical
private function equals_r8_array(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in), allocatable :: u(:)
real(kind=ESMF_KIND_R8), intent(in) :: v(:)
Return Value logical
private function equals_l_array(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
logical, intent(in), allocatable :: u(:)
logical, intent(in) :: v(:)
Return Value logical
Call graph
are_equal calls equals_i4_array, equals_i4_scalar, equals_i8_array, equals_i8_scalar, equals_l_array, equals_l_scalar, equals_r4_array, equals_r4_scalar, equals_r8_array, equals_r8_scalar, equals_string
get_value_i4 calls are_equal
get_value_i4seq calls are_equal
get_value_i8 calls are_equal
get_value_i8seq calls are_equal
get_value_logical calls are_equal
get_value_logical_seq calls are_equal
get_value_r4 calls are_equal
get_value_r4seq calls are_equal
get_value_r8 calls are_equal
get_value_r8seq calls are_equal
get_value_string calls are_equal
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string