check – MAPL
check Interface
4 statements
Source File
public interface check
Calls
Called by
Module Procedures
public function check_actual(r, actual_pt, expected_name) result(check)
Arguments
Type Intent Optional Attributes Name
type(HierarchicalRegistry), intent(in) :: r
type(ActualConnectionPt), intent(in) :: actual_pt
character(len=*), intent(in) :: expected_name
Return Value logical
public function check_virtual(r, virtual_pt, expected_names) result(check)
Arguments
Type Intent Optional Attributes Name
type(HierarchicalRegistry), intent(in) :: r
type(VirtualConnectionPt), intent(in) :: virtual_pt
character(len=*), intent(in) :: expected_names(:)
Return Value logical
Call graph
check calls check_actual, check_virtual
check_actual calls assert_that, assertequal, get_item_spec, true
check_virtual calls check_actual, assert_that, of, get_actual_pts, true
get_actual_pts calls at
get_item_spec calls at, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_export_to_export_connection calls check
test_get_item_spec_found calls check
test_get_item_spec_multi calls check
test_internal_to_export_connection calls check
test_sibling_activation calls check