ConnectionVector – MAPL
ConnectionVector Interface
7 statements
Source File
public interface ConnectionVector
Calls
Module Procedures
private function vector_new_vector_empty() result(v)
Arguments
None
Return Value type(ConnectionVector)
private function vector_new_vector_fill_size_kind(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer(kind=GFTL_SIZE_KIND), intent(in) :: n
class(Connection), intent(in), optional :: value
Return Value type(ConnectionVector)
private function vector_new_vector_fill_default(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
class(Connection), intent(in), optional :: value
Return Value type(ConnectionVector)
private function vector_new_vector_range(first, last) result(v)
Arguments
Type Intent Optional Attributes Name
type(ConnectionVectorIterator), intent(in) :: first
type(ConnectionVectorIterator), intent(in) :: last
Return Value type(ConnectionVector)
private function vector_new_vector_copy(x) result(v)
Arguments
Type Intent Optional Attributes Name
type(ConnectionVector) :: x
Return Value type(ConnectionVector)
Call graph
connectionvector calls vector_new_vector_copy, vector_new_vector_empty, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_range
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_range calls of, vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve