ConvertUnitsAction – MAPL
ConvertUnitsAction Interface
4 statements
Source File
public interface ConvertUnitsAction
Calls
Module Procedures
public function new_converter(f_in, src_units, f_out, dst_units) result(action)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: f_in
character(len=*), intent(in) :: src_units
type(ESMF_Field), intent(in) :: f_out
character(len=*), intent(in) :: dst_units
Return Value type(ConvertUnitsAction)
public function new_converter2(src_units, dst_units) result(action)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: src_units
character(len=*), intent(in) :: dst_units
Return Value type(ConvertUnitsAction)
Call graph
convertunitsaction calls new_converter, new_converter2
new_converter calls get_converter
get_converter calls is_free