create_grid_comp – MAPL
create_grid_comp Interface
3 statements
Source File
public interface create_grid_comp
Calls
Called by
Module Procedures
private recursive function create_grid_comp_primary(name, set_services, config, clock, unusable, petlist, rc) result(gridcomp)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
class(AbstractUserSetServices), intent(in) :: set_services
type(ESMF_HConfig), intent(in) :: config
type(ESMF_Clock), intent(in) :: clock
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: petlist(:)
integer, intent(out), optional :: rc
Return Value type(ESMF_GridComp)
Call graph
create_grid_comp calls create_grid_comp_primary
create_grid_comp_primary calls ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic
get_outer_meta calls get_outer_meta_from_outer_gc
setservices_ calls setservices_, add_child
attach_outer_meta calls mapl_return, mapl_assert, mapl_usercompsetinternalstate
init_meta calls mapl_return, mapl_verify, get_logger, get_name
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_is_generic calls mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoSet
add_child_by_name calls create_grid_comp, add_child_by_name, add_child
make_driver calls create_grid_comp
setup calls create_grid_comp, add_child
test_is_generic calls create_grid_comp
test_mapl_invalid_name calls create_grid_comp, add_child
mapl_run_driver calls make_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
test_wasfinal calls setup
test_wasinit calls setup
test_wasrun_1 calls setup
test_wasrun_extra calls setup
run_geos calls mapl_run_driver
geos calls run_geos