DistributedMeter – MAPL
DistributedMeter Interface
3 statements
Source File
public interface DistributedMeter
Calls
Module Procedures
private function new_DistributedMeter(gauge) result(distributed_meter)
Arguments
Type Intent Optional Attributes Name
class(AbstractGauge), intent(in) :: gauge
Return Value type(DistributedMeter)
Call graph
distributedmeter calls new_distributedmeter
new_distributedmeter calls initialize
initialize calls mpi_op_create, mpi_type_commit, make_mpi_type