DynamicMask – MAPL
DynamicMask Interface
5 statements
Source File
public interface DynamicMask
Calls
Module Procedures
private function new_DynamicMask_r4(mask_type, src_mask_value, dst_mask_value, handleAllElements, rc) result(mask)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mask_type
real(kind=ESMF_KIND_R4) :: src_mask_value
real(kind=ESMF_KIND_R4), intent(in), optional :: dst_mask_value
logical, optional :: handleAllElements
integer, intent(out), optional :: rc
Return Value type(DynamicMask)
private function new_DynamicMask_r8(mask_type, src_mask_value, dst_mask_value, handleAllElements, rc) result(mask)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mask_type
real(kind=ESMF_KIND_R8), intent(in), optional :: src_mask_value
real(kind=ESMF_KIND_R8), intent(in), optional :: dst_mask_value
logical, optional :: handleAllElements
integer, intent(out), optional :: rc
Return Value type(DynamicMask)
private function new_DynamicMask_r4r8(spec, rc) result(mask)
Arguments
Type Intent Optional Attributes Name
type(DynamicMaskSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(DynamicMask)
Call graph
dynamicmask calls new_dynamicmask_r4, new_dynamicmask_r4r8, new_dynamicmask_r8
new_dynamicmask_r4 calls mapl_return, mapl_verify
new_dynamicmask_r4r8 calls ESMF_DynamicMaskSetR4R8R4V, ESMF_DynamicMaskSetR8R8R8V, get_mask_routine_r4, get_mask_routine_r8, mapl_return, mapl_verify
new_dynamicmask_r8 calls mapl_return, mapl_verify
get_mask_routine_r4 calls mapl_return, mapl_assert
get_mask_routine_r8 calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize