ESMFL_BundleAddState – MAPL
ESMFL_BundleAddState Interface
3 statements
Source File
public interface ESMFL_BundleAddState
Calls
Called by
Module Procedures
private recursive subroutine BundleAddState_(BUNDLE, STATE, rc, GRID, VALIDATE)
The recursive subrountine BundleAddState_ adds contents of State to Bundle. Extracts fields from an ESMF State and adds them to a ESMF Bundle. In essesence, it serializes an ESMF state in a flat Bundle. The BUNDLE must have been created prior to calling this routine.
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
type(ESMF_State), intent(inout) :: STATE
integer, optional :: rc
type(ESMF_Grid), intent(in), optional :: GRID
logical, intent(in), optional :: VALIDATE
Call graph
esmfl_bundleaddstate calls bundleaddstate_
bundleaddstate_ calls bundleaddstate_, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldbundleget, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_assert, mapl_fieldbundleadd, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_cfiocreatefromstate calls esmfl_bundleaddstate
mapl_cfioreadstate calls esmfl_bundleaddstate
mapl_cfiowritestate calls esmfl_bundleaddstate
mapl_simplebundlecreatefromstate calls esmfl_bundleaddstate
esmf_iocreate calls mapl_cfiocreatefromstate
esmf_ioread calls mapl_cfioreadstate
esmf_iowrite calls mapl_cfiowritestate
mapl_cfiocreate calls mapl_cfiocreatefromstate
mapl_cfioread calls mapl_cfioreadstate
mapl_cfiowrite calls mapl_cfiowritestate
mapl_simplebundlecreate calls mapl_simplebundlecreatefromstate
initialize_ calls mapl_cfioread
mapl_simplebundleread calls mapl_cfioread, mapl_simplebundlecreate
mapl_simplebundlewrite1 calls mapl_cfiocreate, mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiocreate, mapl_cfiowrite
test_main calls mapl_cfioread, esmf_iocreate, esmf_ioread, esmf_iowrite
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main