ESMFL_HALO – MAPL
ESMFL_HALO Interface
3 statements
Source File
public interface ESMFL_HALO
Calls
Called by
Module Procedures
private subroutine ESMFL_HALO_R4_2D(GRID, INPUT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: GRID
real, intent(inout) :: INPUT(:,:)
integer, intent(out), optional :: RC
Call graph
esmfl_halo calls esmfl_halo_r4_2d
esmfl_halo_r4_2d calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, halo, mapl_assert, mapl_commssendrecv, get_factory, mapl_distgridget, mapl_getimsjms, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commssendrecv calls mapl_commssendrecv_i4_0, mapl_commssendrecv_r4_0, mapl_commssendrecv_r4_1, mapl_commssendrecv_r4_2, mapl_commssendrecv_r8_1, mapl_commssendrecv_r8_2
get_factory calls mapl_return, mapl_verify, get_factory
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridget calls ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_getimsjms, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_locstreamtransformg2t calls esmfl_halo
mapl_locstreamtransform calls mapl_locstreamtransformg2t, mapl_locstreamtransformfield
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run calls regridtransform, regridtransformt2g, regridtransformt2g2g