FieldSet – MAPL
FieldSet Interface
4 statements
Source File
public interface FieldSet
Called by
Module Procedures
private subroutine FieldSet_r4(field, constant_val, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
real(kind=ESMF_KIND_r4), intent(in) :: constant_val
integer, intent(out), optional :: rc
private subroutine FieldSet_r8(field, constant_val, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
real(kind=ESMF_KIND_r8), intent(in) :: constant_val
integer, intent(out), optional :: rc
Call graph
mapl_stateeval calls fieldset
setup_field calls fieldset
test_accumulate_mean_r4 calls fieldset
test_accumulate_r4 calls fieldset
test_accumulate calls fieldset
test_calculate_mean_r4 calls fieldset
test_clear calls fieldset, clear
test_invalidate calls fieldset
test_update calls fieldset
evaluate_derived_field calls mapl_stateeval
setup_bundle calls setup_field
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval