FieldBundleSet – MAPL
FieldBundleSet Interface
3 statements
Source File
public interface FieldBundleSet
Called by
Module Procedures
private subroutine bundle_set(fieldBundle, unusable, geom, fieldBundleType, typekind, interpolation_weights, ungridded_dims, num_levels, vert_staggerloc, units, standard_name, long_name, is_active, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: fieldBundle
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Geom), intent(in), optional :: geom
type(FieldBundleType_Flag), intent(in), optional :: fieldBundleType
type(ESMF_TypeKind_Flag), intent(in), optional :: typekind
real(kind=ESMF_KIND_R4), intent(in), optional :: interpolation_weights(:)
type(UngriddedDims), intent(in), optional :: ungridded_dims
integer, intent(in), optional :: num_levels
type(VerticalStaggerLoc), intent(in), optional :: vert_staggerloc
character(len=*), intent(in), optional :: units
character(len=*), intent(in), optional :: standard_name
character(len=*), intent(in), optional :: long_name
logical, intent(in), optional :: is_active
integer, intent(out), optional :: rc
Call graph
setup_bundle calls fieldbundleset
test_interp_constant calls fieldbundleset
test_interp_midway calls fieldbundleset
test_mapl_undef calls fieldbundleset
test_propagate_geom calls fieldbundleset
test_propagate_interp_weights calls fieldbundleset
test_change_geom calls update_bundle, setup_bundle
test_change_typekind calls update_bundle, setup_bundle
test_change_units calls update_bundle, setup_bundle
test_change_weights calls update_bundle, setup_bundle
test_change_weights_with_ungridded calls update_bundle, setup_bundle
test_create_fields calls update_bundle, setup_bundle
test_create_fields_with_ungridded calls update_bundle, setup_bundle
test_same_geom calls update_bundle, setup_bundle