FieldDictionaryItem – MAPL
FieldDictionaryItem Interface
6 statements
Source File
public interface FieldDictionaryItem
Calls
Module Procedures
private function new_FieldDictionaryItem_(long_name, canonical_units) result(item)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: long_name
character(len=*), intent(in) :: canonical_units
Return Value type(FieldDictionaryItem)
private function new_FieldDictionaryItem_one_alias(long_name, canonical_units, alias) result(item)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: long_name
character(len=*), intent(in) :: canonical_units
character(len=*), intent(in) :: alias
Return Value type(FieldDictionaryItem)
private function new_FieldDictionaryItem_multi_aliases(long_name, canonical_units, aliases) result(item)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: long_name
character(len=*), intent(in) :: canonical_units
character(len=*), intent(in) :: aliases(:)
Return Value type(FieldDictionaryItem)
private function new_FieldDictionaryItem_vector(long_name, canonical_units, aliases) result(item)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: long_name
character(len=*), intent(in) :: canonical_units
type(StringVector), intent(in) :: aliases
Return Value type(FieldDictionaryItem)
Call graph
fielddictionaryitem calls new_fielddictionaryitem_, new_fielddictionaryitem_multi_aliases, new_fielddictionaryitem_one_alias, new_fielddictionaryitem_vector
new_fielddictionaryitem_multi_aliases calls push_back