FieldsAreSameTypeKind – MAPL
FieldsAreSameTypeKind Interface
3 statements
Source File
public interface FieldsAreSameTypeKind
Called by
Module Procedures
private function are_same_type_kind(x, y, rc) result(same_tk)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Return Value logical
Call graph
test_fieldsaresametypekind calls fieldsaresametypekind
test_accumulate_mean_r4 calls initialize
test_accumulate_r4 calls initialize
test_accumulate_with_undef_some_steps calls initialize
test_accumulate calls initialize
test_calculate_mean_r4 calls initialize
test_clear calls initialize
test_initialize calls initialize
test_invalidate calls initialize
test_max_accumulate_r4 calls initialize
test_min_accumulate_r4 calls initialize
test_update calls initialize