FieldBundleCreate – MAPL
FieldBundleCreate Interface
5 statements
Source File
public interface FieldBundleCreate
Called by
Module Procedures
private function create_bundle_empty(unusable, name, fieldBundleType, rc) result(bundle)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: name
type(FieldBundleType_Flag), intent(in), optional :: fieldBundleType
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle)
private function create_bundle_from_state(state, unusable, name, fieldBundleType, rc) result(bundle)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: name
type(FieldBundleType_Flag), intent(in), optional :: fieldBundleType
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle)
private function create_bundle_from_field_list(fieldList, unusable, name, fieldBundleType, rc) result(bundle)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: fieldList(:)
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: name
type(FieldBundleType_Flag), intent(in), optional :: fieldBundleType
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle)
Call graph
setup_bundle calls fieldbundlecreate
test_propagate_geom calls fieldbundlecreate
test_propagate_interp_weights calls fieldbundlecreate
test_regrid_2d_vector calls fieldbundlecreate
test_regrid_bracket calls fieldbundlecreate
test_change_geom calls setup_bundle
test_change_typekind calls setup_bundle
test_change_units calls setup_bundle
test_change_weights calls setup_bundle
test_change_weights_with_ungridded calls setup_bundle
test_create_fields calls setup_bundle
test_create_fields_with_ungridded calls setup_bundle
test_same_geom calls setup_bundle