FieldDictionary – MAPL
FieldDictionary Interface
3 statements
Source File
public interface FieldDictionary
Calls
Module Procedures
private function new_from_yaml(filename, stream, rc) result(fd)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: filename
character(len=*), intent(in), optional :: stream
integer, intent(out), optional :: rc
Return Value type(FieldDictionary)
Call graph
fielddictionary calls new_from_yaml
new_from_yaml calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, add_item, mapl_return, mapl_verify, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item calls mapl_return, mapl_verify, insert, add_aliases, get_aliases
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_aliases calls mapl_assert, mapl_return, begin, insert, next, of
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize