FieldSCAL – MAPL
FieldSCAL Interface
4 statements
Source File
public interface FieldSCAL
Calls
Called by
Module Procedures
private subroutine scale_r4(a, x, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: a
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
private subroutine scale_r8(a, x, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: a
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
Call graph
fieldscal calls scale_r4, scale_r8
scale_r4 calls assign_fptr, mapl_return, mapl_verify
scale_r8 calls assign_fptr, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_throw_exception calls initialize
test_fieldscal_r4 calls fieldscal
test_fieldscal_r8 calls fieldscal