FieldSpec – MAPL
FieldSpec Interface
4 statements
Source File
public interface FieldSpec
Calls
Module Procedures
public function new_FieldSpec_geom(unusable, geom, vertical_grid, vertical_dim_spec, typekind, ungridded_dims, standard_name, long_name, units, attributes, regrid_param, horizontal_dims_spec, default_value, accumulation_type, timestep) result(field_spec)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Geom), intent(in), optional :: geom
class(VerticalGrid), intent(in), optional :: vertical_grid
type(VerticalDimSpec), intent(in) :: vertical_dim_spec
type(ESMF_TypeKind_Flag), intent(in) :: typekind
type(UngriddedDims), intent(in), optional :: ungridded_dims
character(len=*), intent(in), optional :: standard_name
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: units
type(StringVector), intent(in), optional :: attributes
type(EsmfRegridderParam), intent(in), optional :: regrid_param
type(HorizontalDimsSpec), intent(in), optional :: horizontal_dims_spec
real, intent(in), optional :: default_value
character(len=*), intent(in), optional :: accumulation_type
type(ESMF_TimeInterval), intent(in), optional :: timestep
Return Value type(FieldSpec), target
private function new_FieldSpec_varspec(variable_spec) result(field_spec)
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: variable_spec
Return Value type(FieldSpec)
Call graph
fieldspec calls new_fieldspec_geom
new_fieldspec_geom calls get_aspects, set_attributes_aspect, set_frequency_aspect, set_geom_aspect, set_typekind_aspect, set_ungridded_dims_aspect, set_units_aspect, set_vertical_grid_aspect