FieldBundleGet – MAPL
FieldBundleGet Interface
3 statements
Source File
public interface FieldBundleGet
Called by
Module Procedures
private subroutine bundle_get(fieldBundle, unusable, fieldCount, fieldList, geom, fieldBundleType, typekind, interpolation_weights, ungridded_dims, num_levels, vert_staggerloc, num_vgrid_levels, units, standard_name, long_name, is_active, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: fieldBundle
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: fieldCount
type(ESMF_Field), intent(out), optional, allocatable :: fieldList(:)
type(ESMF_Geom), intent(out), optional :: geom
type(FieldBundleType_Flag), intent(out), optional :: fieldBundleType
type(ESMF_TypeKind_Flag), intent(out), optional :: typekind
real(kind=ESMF_KIND_R4), intent(out), optional, allocatable :: interpolation_weights(:)
type(UngriddedDims), intent(out), optional :: ungridded_dims
integer, intent(out), optional :: num_levels
type(VerticalStaggerLoc), intent(out), optional :: vert_staggerloc
integer, intent(out), optional :: num_vgrid_levels
character(len=:), intent(out), optional, allocatable :: units
character(len=:), intent(out), optional, allocatable :: standard_name
character(len=:), intent(out), optional, allocatable :: long_name
logical, intent(out), optional :: is_active
integer, intent(out), optional :: rc
Call graph
teardown_bundle calls fieldbundleget
test_change_geom calls fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls fieldbundleget, update_bundle, teardown_bundle
test_change_units calls fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls fieldbundleget, update_bundle, teardown_bundle
test_propagate_geom calls fieldbundleget
test_propagate_interp_weights calls fieldbundleget
test_same_geom calls fieldbundleget, update_bundle, teardown_bundle
test_allocate calls destroy
test_interp_constant calls update
test_interp_midway calls update
test_mapl_undef calls update