FieldReallocate – MAPL
FieldReallocate Interface
3 statements
Source File
public interface FieldReallocate
Called by
Module Procedures
private subroutine field_reallocate(field, unusable, geom, typekind, num_levels, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Geom), intent(in), optional :: geom
type(ESMF_TypeKind_Flag), intent(in), optional :: typekind
integer, intent(in), optional :: num_levels
integer, intent(out), optional :: rc
Call graph
test_change_geom calls fieldreallocate
test_change_n_levels calls fieldreallocate
test_change_typekind calls fieldreallocate
test_same_geom_do_not_reallocate calls fieldreallocate
test_same_n_levels_do_not_reallocate calls fieldreallocate
test_same_typekind_do_not_reallocate calls fieldreallocate