find_if – MAPL
find_if Interface
3 statements
Source File
private interface find_if
Calls
Module Procedures
private function vector_reverse_find_if(first, last, p) result(it)
Arguments
Type Intent Optional Attributes Name
type(RegridderVectorRIterator), intent(in) :: first
type(RegridderVectorRIterator), intent(in) :: last
private function p(item)
Arguments
Type Intent Optional Attributes Name
class(Regridder), intent(in) :: item
Return Value logical
Return Value type(RegridderVectorRIterator)
Call graph
find_if calls vector_reverse_find_if
vector_reverse_find_if calls of, vector_riter_next
vector_riter_next calls vector_iter_prev
vector_riter_of_offset_default calls of