find_if – MAPL
find_if Interface
3 statements
Source File
private interface find_if
Calls
Module Procedures
private function map_find_if(first, last, p) result(it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtVec_MapIterator), intent(in) :: first
type(ActualPtVec_MapIterator), intent(in) :: last
private function p(item)
Arguments
Type Intent Optional Attributes Name
type(ActualPtVec_Pair), intent(in) :: item
Return Value logical
Return Value type(ActualPtVec_MapIterator)
Call graph
find_if calls map_find_if
map_find_if calls map_iter_next, map_iter_of
map_iter_next calls map_s_iter_next
map_iter_of calls map_s_iter_of
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value