find_if_not – MAPL
find_if_not Interface
3 statements
Source File
private interface find_if_not
Calls
Module Procedures
private function map_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(IntegerRequestMapIterator), intent(in) :: first
type(IntegerRequestMapIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(IntegerRequestPair), intent(in) :: item
Return Value logical
Return Value type(IntegerRequestMapIterator)
Call graph
find_if_not calls map_find_if_not
map_find_if_not calls map_iter_next, map_iter_of
map_iter_next calls map_s_iter_next
map_iter_of calls map_s_iter_of
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value