ftn_begin – MAPL
ftn_begin Interface
3 statements
Source File
private interface ftn_begin
Calls
Module Procedures
private function omap_I_iter_ftn_begin(cont) result(begin)
Arguments
Type Intent Optional Attributes Name
type(omap_Map), intent(in), target :: cont
Return Value type(omap_MapIterator)
Call graph
ftn_begin calls omap_i_iter_ftn_begin
omap_i_iter_ftn_begin calls omap_i_ftn_begin
omap_i_ftn_begin calls omap_i_s_ftn_begin