get_lon_corners – MAPL
get_lon_corners Interface
42 statements
Source File
interface
Calls
Called by
private module function get_lon_corners(centers) result(corners) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=R8), intent(in) :: centers(:)
Return Value real(kind=R8),allocatable,(:)
Call graph
get_lon_corners calls get_lon_corners
make_lonaxis_from_metadata calls get_lon_corners, make_lonaxis_from_metadata
make_lonaxis calls make_lonaxis_from_metadata
make_latlongeomspec_from_hconfig calls make_lonaxis
make_latlongeomspec_from_metadata calls make_lonaxis
test_make_lon_axis_from_hconfig calls make_lonaxis