get_ungridded_dims – MAPL
get_ungridded_dims Interface
4 statements
Source File
public interface get_ungridded_dims
Called by
Module Procedures
private function get_ungridded_dims_bundle(bundle, rc) result(dims)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
integer, intent(out), optional :: rc
Return Value type(UngriddedDims)
private function get_ungridded_dims_field(field, rc) result(ungridded)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
integer, intent(out), optional :: rc
Return Value type(UngriddedDims)
Call graph
add_ungridded_dimensions calls get_ungridded_dims
ungridded_dim_names calls get_ungridded_dims
add_variable calls ungridded_dim_names
bundle_to_metadata calls add_ungridded_dimensions, add_variables
add_variables calls add_variable