get_lon_axis – MAPL
get_lon_axis Interface
64 statements
Source File
interface
Calls
Called by
private pure module function get_lon_axis(spec) result(axis) Implementation →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomSpec), intent(in) :: spec
Return Value type(LonAxis)
Call graph
get_lon_axis calls get_lon_axis
create_basic_grid calls get_lon_axis, create_basic_grid
fill_coordinates calls get_lon_axis, fill_coordinates
typesafe_make_file_metadata calls get_lon_axis
make_file_metadata calls typesafe_make_file_metadata, make_file_metadata
typesafe_make_geom calls create_basic_grid, fill_coordinates
make_geom calls typesafe_make_geom