get_lat_distribution – MAPL
get_lat_distribution Interface
61 statements
Source File
interface
Calls
Called by
private pure module function get_lat_distribution(decomp) result(lat_distribution) Implementation →
Arguments
Type Intent Optional Attributes Name
class(LatLonDecomposition), intent(in) :: decomp
Return Value integer,allocatable,(:)
Call graph
get_lat_distribution calls get_lat_distribution
create_basic_grid calls get_lat_distribution, create_basic_grid
fill_coordinates calls get_lat_distribution, get_lat_subset, fill_coordinates
get_lat_subset calls get_lat_distribution, get_lat_subset
typesafe_make_geom calls create_basic_grid, fill_coordinates
make_geom calls typesafe_make_geom