get_value – MAPL
get_value Interface
13 statements
Source File
public interface get_value
Calls
Called by
resource_get_i4_gc w get_value
w
resource_get_i4seq_gc w
w
resource_get_i8_gc w
w
resource_get_i8seq_gc w
w
resource_get_logical_gc w
w
resource_get_logical_seq_gc w
w
resource_get_r4_gc w
w
resource_get_r4seq_gc w
w
resource_get_r8_gc w
w
resource_get_r8seq_gc w
w
resource_get_string_gc w
w
test_get_i4 w
w
test_get_i4_not_found_default w
w
test_get_i4_not_found_no_default w
w
test_get_i4_value_equals_default w
w
test_get_i4_value_not_equal_default w
w
test_get_i4seq w
w
test_get_i8 w
w
test_get_i8seq w
w
test_get_logical w
w
test_get_logical_seq w
w
test_get_r4 w
w
test_get_r4seq w
w
test_get_r8 w
w
test_get_r8seq w
w
test_get_string w
w
test_make_valuestring_i4 w
w
test_make_valuestring_i4seq w
w
test_make_valuestring_i8 w
w
test_make_valuestring_i8seq w
w
test_make_valuestring_logical w
w
test_make_valuestring_logicalseq w
w
test_make_valuestring_r4 w
w
test_make_valuestring_r4seq w
w
test_make_valuestring_r8 w
w
test_make_valuestring_r8seq w
w
test_make_valuestring_string w
w
Module Procedures
private subroutine get_value_i4(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
integer(kind=ESMF_KIND_I4), intent(inout) :: value
integer(kind=ESMF_KIND_I4), intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_i8(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
integer(kind=ESMF_KIND_I8), intent(inout) :: value
integer(kind=ESMF_KIND_I8), intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_r4(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
real(kind=ESMF_KIND_R4), intent(inout) :: value
real(kind=ESMF_KIND_R4), intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_r8(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
real(kind=ESMF_KIND_R8), intent(inout) :: value
real(kind=ESMF_KIND_R8), intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_string(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
character(len=:), intent(inout), allocatable :: value
character(len=*), intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_logical(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
logical, intent(inout) :: value
logical, intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_i4seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
integer(kind=ESMF_KIND_I4), intent(inout), dimension(:), allocatable :: value
integer(kind=ESMF_KIND_I4), intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_i8seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
integer(kind=ESMF_KIND_I8), intent(inout), dimension(:), allocatable :: value
integer(kind=ESMF_KIND_I8), intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_r4seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
real(kind=ESMF_KIND_R4), intent(inout), dimension(:), allocatable :: value
real(kind=ESMF_KIND_R4), intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_r8seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
real(kind=ESMF_KIND_R8), intent(inout), dimension(:), allocatable :: value
real(kind=ESMF_KIND_R8), intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
private subroutine get_value_logical_seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
logical, intent(inout), dimension(:), allocatable :: value
logical, intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
Call graph
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
get_value_i4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical_seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_string calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify