get_outer_meta – MAPL
get_outer_meta Interface
3 statements
Source File
public interface get_outer_meta
Called by
Module Procedures
private function get_outer_meta_from_outer_gc(gridcomp, rc) result(outer_meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Return Value type(OuterMetaComponent), pointer
Call graph
get_child_user_states calls get_outer_meta
get_outer_meta_from_inner_gc calls get_outer_meta
get_substates calls get_outer_meta, get_substates
setservices calls get_outer_meta, get_outer_meta_from_inner_gc, setservices
setup calls get_outer_meta
test_child_outer_items_created calls get_outer_meta, get_child_user_states
test_child_user_items_created calls get_outer_meta
test_mapl_invalid_name calls get_outer_meta
test_parent_user_items_created calls get_outer_meta
test_state_items_complete calls get_outer_meta
test_anything calls get_substates
test_finalize_children calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup