get_hconfig – MAPL
get_hconfig Interface
13 statements
Source File
public interface get_hconfig
Calls
Called by
Module Procedures
private subroutine get_hconfig_as_i4(value, params, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(out) :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_i8(value, params, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I8), intent(out) :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_r4(value, params, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(out) :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_r8(value, params, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(out) :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_logical(value, params, rc)
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_i4seq(value, params, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(out), dimension(:), allocatable :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_i8seq(value, params, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I8), intent(out), dimension(:), allocatable :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_r4seq(value, params, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(out), dimension(:), allocatable :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_r8seq(value, params, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(out), dimension(:), allocatable :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_logical_seq(value, params, rc)
Arguments
Type Intent Optional Attributes Name
logical, intent(out), dimension(:), allocatable :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
private subroutine get_hconfig_as_string(value, params, rc)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(out), allocatable :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
Call graph
get_hconfig calls get_hconfig_as_i4, get_hconfig_as_i4seq, get_hconfig_as_i8, get_hconfig_as_i8seq, get_hconfig_as_logical, get_hconfig_as_logical_seq, get_hconfig_as_r4, get_hconfig_as_r4seq, get_hconfig_as_r8, get_hconfig_as_r8seq, get_hconfig_as_string
get_hconfig_as_i4 calls esmf_hconfigasi4, mapl_return, mapl_verify
get_hconfig_as_i4seq calls esmf_hconfigasi4seq, mapl_return, mapl_verify
get_hconfig_as_i8 calls esmf_hconfigasi8, mapl_return, mapl_verify
get_hconfig_as_i8seq calls esmf_hconfigasi8seq, mapl_return, mapl_verify
get_hconfig_as_logical calls esmf_hconfigaslogical, mapl_return, mapl_verify
get_hconfig_as_logical_seq calls esmf_hconfigaslogicalseq, mapl_return, mapl_verify
get_hconfig_as_r4 calls esmf_hconfigasr4, mapl_return, mapl_verify
get_hconfig_as_r4seq calls esmf_hconfigasr4seq, mapl_return, mapl_verify
get_hconfig_as_r8 calls esmf_hconfigasr8, mapl_return, mapl_verify
get_hconfig_as_r8seq calls esmf_hconfigasr8seq, mapl_return, mapl_verify
get_hconfig_as_string calls esmf_hconfigasstring, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_value_i4 calls get_hconfig
get_value_i4seq calls get_hconfig
get_value_i8 calls get_hconfig
get_value_i8seq calls get_hconfig
get_value_logical calls get_hconfig
get_value_logical_seq calls get_hconfig
get_value_r4 calls get_hconfig
get_value_r4seq calls get_hconfig
get_value_r8 calls get_hconfig
get_value_r8seq calls get_hconfig
get_value_string calls get_hconfig
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string