get_coordinates – MAPL
get_coordinates Interface
3 statements
Source File
public interface get_coordinates
Calls
Called by
Module Procedures
private interface get_coordinates_dim()
Arguments
None
Call graph
get_coordinates calls get_coordinates_dim
get_coordinates_dim calls get_coordinates_dim, mapl_assert, get_coordinate_data, get_coordinate_variable, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_coordinate_data calls mapl_return
get_coordinate_variable calls mapl_assert, mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_lataxis_from_metadata calls get_coordinates, make_lataxis_from_metadata
make_lonaxis_from_metadata calls get_coordinates, make_lonaxis_from_metadata
make_lataxis calls make_lataxis_from_metadata
make_lonaxis calls make_lonaxis_from_metadata
make_latlongeomspec_from_hconfig calls make_lataxis, make_lonaxis
make_latlongeomspec_from_metadata calls make_lataxis, make_lonaxis
test_make_lon_axis_from_hconfig calls make_lonaxis