GriddedComponentDriverMap – MAPL
GriddedComponentDriverMap Interface
5 statements
Source File
public interface GriddedComponentDriverMap
Calls
Module Procedures
private function omap_new_omap_empty() result(m)
Arguments
None
Return Value type(GriddedComponentDriverMap)
private function omap_new_omap_copy(x) result(m)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverMap), intent(in) :: x
Return Value type(GriddedComponentDriverMap)
private function omap_new_omap_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverPair), intent(in) :: il(:)
Return Value type(GriddedComponentDriverMap)
Call graph
griddedcomponentdrivermap calls omap_new_omap_copy, omap_new_omap_empty, omap_new_omap_initializer_list
omap_new_omap_initializer_list calls insert
omap_insert_key_value calls at, insert, omap_k_push_back