GridVectorBasis – MAPL
GridVectorBasis Interface
3 statements
Source File
public interface GridVectorBasis
Calls
Called by
Module Procedures
private interface new_GridVectorBasis()
Arguments
None
Call graph
gridvectorbasis calls new_gridvectorbasis
new_gridvectorbasis calls new_gridvectorbasis, ESMF_GeomGet, assign_fptr, create_fields, get_unit_vector, gridgetcoords, gridgetcorners, mapl_assert, mid_pt_sphere, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
create_fields calls create_fields
get_unit_vector calls get_unit_vector
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
gridgetcorners calls grid_get_corners
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mid_pt_sphere calls mid_pt_sphere
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_basis calls gridvectorbasis