GridGetCoords – MAPL
GridGetCoords Interface
5 statements
Source File
private interface GridGetCoords
Calls
Called by
Module Procedures
private interface grid_get_coords_1d()
Arguments
None
private interface grid_get_coords_2d()
Arguments
None
private interface grid_get_centers()
Arguments
None
Call graph
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
grid_get_centers calls grid_get_centers, gridgetcoords, mapl_return, mapl_verify
grid_get_coords_1d calls grid_get_coords_1d, gridgetcoords, mapl_return, mapl_verify
grid_get_coords_2d calls grid_get_coords_2d, ESMF_GridGetCoord, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
grid_get_corners calls gridgetcoords, grid_get_corners
mapl_geomgetcoords calls gridgetcoords, mapl_geomgetcoords
new_gridvectorbasis calls gridgetcoords, gridgetcorners, new_gridvectorbasis
gridgetcorners calls grid_get_corners
gridvectorbasis calls new_gridvectorbasis
new_ns_basis calls mapl_geomgetcoords, new_ns_basis
get_basis calls gridvectorbasis