IntegerRequestMap – MAPL
IntegerRequestMap Interface
5 statements
Source File
public interface IntegerRequestMap
Calls
Module Procedures
private function map_new_map_empty() result(m)
Arguments
None
Return Value type(IntegerRequestMap)
private function map_new_map_copy(x) result(m)
Arguments
Type Intent Optional Attributes Name
type(IntegerRequestMap), intent(in) :: x
Return Value type(IntegerRequestMap)
private function map_new_map_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(IntegerRequestPair), intent(in) :: il(:)
Return Value type(IntegerRequestMap)
Call graph
integerrequestmap calls map_new_map_copy, map_new_map_empty, map_new_map_initializer_list
map_new_map_initializer_list calls insert
map_insert_pair calls insert