IntegerMaplGeomMap – MAPL
IntegerMaplGeomMap Interface
5 statements
Source File
public interface IntegerMaplGeomMap
Calls
Module Procedures
private function map_new_map_empty() result(m)
Arguments
None
Return Value type(IntegerMaplGeomMap)
private function map_new_map_copy(x) result(m)
Arguments
Type Intent Optional Attributes Name
type(IntegerMaplGeomMap), intent(in) :: x
Return Value type(IntegerMaplGeomMap)
private function map_new_map_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(Pair), intent(in) :: il(:)
Return Value type(IntegerMaplGeomMap)
Call graph
integermaplgeommap calls map_new_map_copy, map_new_map_empty, map_new_map_initializer_list
map_new_map_initializer_list calls insert
map_insert_pair calls insert