LatLonDecomposition – MAPL
LatLonDecomposition Interface
5 statements
Source File
public interface LatLonDecomposition
Calls
Module Procedures
private interface new_LatLonDecomposition_basic()
Arguments
None
private interface new_LatLonDecomposition_petcount()
Arguments
None
private interface new_LatLonDecomposition_topo()
Arguments
None
Call graph
latlondecomposition calls new_latlondecomposition_basic, new_latlondecomposition_petcount, new_latlondecomposition_topo
new_latlondecomposition_basic calls new_latlondecomposition_basic
new_latlondecomposition_petcount calls new_latlondecomposition_petcount
new_latlondecomposition_topo calls new_latlondecomposition_topo, mapl_decomposedim
mapl_decomposedim calls mapl_decomposedim