make_routehandle – MAPL
make_routehandle Interface
3 statements
Source File
public interface make_routehandle
Calls
Module Procedures
private function make_routehandle_from_spec(spec, rc) result(routehandle)
Arguments
Type Intent Optional Attributes Name
type(RoutehandleSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(ESMF_RouteHandle)
Call graph
make_routehandle calls make_routehandle_from_spec, make_routehandle_from_param
make_routehandle_from_spec calls make_routehandle, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_routehandle_from_param calls mapl_return, mapl_verify, ESMF_FieldRegridStore, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset
mapl_throw_exception calls initialize