make_routehandle – MAPL
make_routehandle Interface
3 statements
Source File
public interface make_routehandle
Calls
Called by
Module Procedures
private function make_routehandle_from_param(geom_in, geom_out, param, rc) result(routehandle)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom_in
type(ESMF_Geom), intent(in) :: geom_out
type(RoutehandleParam), intent(in) :: param
integer, intent(out), optional :: rc
Return Value type(ESMF_RouteHandle)
Call graph
make_routehandle calls make_routehandle_from_param, make_routehandle_from_spec
make_routehandle_from_param calls ESMF_FieldRegridStore, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_routehandle calls make_routehandle
make_routehandle_from_spec calls make_routehandle
get_routehandle calls add_routehandle
make_regridder_typesafe calls get_routehandle