make_LatAxis – MAPL
make_LatAxis Interface
4 statements
Source File
public interface make_LatAxis
Calls
Called by
Module Procedures
private interface make_LatAxis_from_hconfig()
Arguments
None
private interface make_LatAxis_from_metadata()
Arguments
None
Call graph
make_lataxis calls make_lataxis_from_hconfig, make_lataxis_from_metadata
make_lataxis_from_hconfig calls make_lataxis_from_hconfig, esmf_hconfigasi4, get_lat_range, mapl_assert, mapl_range, mapl_return, mapl_verify
make_lataxis_from_metadata calls make_lataxis_from_metadata, fix_bad_pole, get_coordinates, get_dim_name, get_lat_corners, mapl_return, mapl_verify
fix_bad_pole calls fix_bad_pole
get_coordinates calls get_coordinates_dim
get_dim_name calls get_dim_name
get_lat_corners calls get_lat_corners
get_lat_range calls get_lat_range
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_latlongeomspec_from_hconfig calls make_lataxis, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls make_lataxis, make_latlongeomspec_from_metadata
make_latlongeomspec calls make_latlongeomspec_from_hconfig, make_latlongeomspec_from_metadata
make_geom_spec_from_hconfig calls make_latlongeomspec
make_geom_spec_from_metadata calls make_latlongeomspec