make_geom – MAPL
make_geom Interface
76 statements
Source File
interface
Calls
Called by
private module function make_geom(this, geom_spec, rc) result(geom) Implementation →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
class(GeomSpec), intent(in) :: geom_spec
integer, intent(out), optional :: rc
Return Value type(ESMF_Geom)
Call graph
make_geom calls make_geom, mapl_assert, mapl_return, mapl_verify, typesafe_make_geom
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
typesafe_make_geom calls mapl_return, mapl_verify, ESMF_GeomCreate, create_basic_grid, fill_coordinates
create_basic_grid calls create_basic_grid
fill_coordinates calls fill_coordinates
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_make_from_hconfig calls make_geom