make_LatLonGeomSpec – MAPL
make_LatLonGeomSpec Interface
4 statements
Source File
public interface make_LatLonGeomSpec
Calls
Called by
Module Procedures
private interface make_LatLonGeomSpec_from_hconfig()
Arguments
None
private interface make_LatLonGeomSpec_from_metadata()
Arguments
None
Call graph
make_latlongeomspec calls make_latlongeomspec_from_hconfig, make_latlongeomspec_from_metadata
make_latlongeomspec_from_hconfig calls make_latlongeomspec_from_hconfig, get_extent, make_lataxis, make_lonaxis, make_decomposition, mapl_return, mapl_verify
make_latlongeomspec_from_metadata calls make_latlongeomspec_from_metadata, get_extent, make_lataxis, make_latlondecomposition, make_lonaxis, mapl_return, mapl_verify
get_extent calls get_extent
make_lataxis calls make_lataxis_from_hconfig, make_lataxis_from_metadata
make_latlondecomposition calls make_latlondecomposition_current_vm, make_latlondecomposition_vm
make_lonaxis calls make_lonaxis_from_hconfig, make_lonaxis_from_metadata
make_decomposition calls make_latlondecomposition, mapl_return, mapl_verify, esmf_hconfigasi4, esmf_hconfigasi4seq, esmf_hconfigisdefined, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_geom_spec_from_hconfig calls make_latlongeomspec, make_geom_spec_from_hconfig, make_spec
make_geom_spec_from_metadata calls make_latlongeomspec, make_geom_spec_from_metadata, make_spec
test_make_from_hconfig calls make_spec