make_LatLonDecomposition – MAPL
make_LatLonDecomposition Interface
4 statements
Source File
public interface make_LatLonDecomposition
Calls
Called by
Module Procedures
private interface make_LatLonDecomposition_current_vm()
Arguments
None
private interface make_LatLonDecomposition_vm()
Arguments
None
Call graph
make_latlondecomposition calls make_latlondecomposition_current_vm, make_latlondecomposition_vm
make_latlondecomposition_current_vm calls make_latlondecomposition_current_vm, make_latlondecomposition, ESMF_VMGetCurrent, mapl_return, mapl_verify
make_latlondecomposition_vm calls make_latlondecomposition_vm, ESMF_VMGet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_decomposition calls make_latlondecomposition
make_latlongeomspec_from_metadata calls make_latlondecomposition, make_latlongeomspec_from_metadata
make_latlongeomspec_from_hconfig calls make_decomposition, make_latlongeomspec_from_hconfig
make_latlongeomspec calls make_latlongeomspec_from_metadata, make_latlongeomspec_from_hconfig
make_geom_spec_from_hconfig calls make_latlongeomspec
make_geom_spec_from_metadata calls make_latlongeomspec