make_LonAxis – MAPL
make_LonAxis Interface
4 statements
Source File
public interface make_LonAxis
Calls
Called by
Module Procedures
private interface make_LonAxis_from_hconfig()
Arguments
None
private interface make_LonAxis_from_metadata()
Arguments
None
Call graph
make_lonaxis calls make_lonaxis_from_hconfig, make_lonaxis_from_metadata
make_lonaxis_from_hconfig calls make_lonaxis_from_hconfig, esmf_hconfigasi4, get_lon_range, mapl_assert, mapl_range, mapl_return, mapl_verify
make_lonaxis_from_metadata calls make_lonaxis_from_metadata, get_coordinates, get_dim_name, get_lon_corners, mapl_return, mapl_verify
get_coordinates calls get_coordinates_dim
get_dim_name calls get_dim_name
get_lon_corners calls get_lon_corners
get_lon_range calls get_lon_range
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_latlongeomspec_from_hconfig calls make_lonaxis, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls make_lonaxis, make_latlongeomspec_from_metadata
test_make_lon_axis_from_hconfig calls make_lonaxis
make_latlongeomspec calls make_latlongeomspec_from_hconfig, make_latlongeomspec_from_metadata
make_geom_spec_from_hconfig calls make_latlongeomspec
make_geom_spec_from_metadata calls make_latlongeomspec