MAPL_InfoSetPrivate – MAPL
MAPL_InfoSetPrivate Interface
8 statements
Source File
public interface MAPL_InfoSetPrivate
Called by
Module Procedures
private subroutine info_stateitem_set_private_string(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
character(len=*), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_private_logical(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
logical, intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_private_i4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_private_r4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_private_r8(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R8), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_private_r4_1d(state, short_name, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(in) :: values(:)
integer, intent(out), optional :: rc
Call graph
test_set_stateitem_private_i4 calls mapl_infosetprivate
test_set_stateitem_private_logical calls mapl_infosetprivate
test_set_stateitem_private_r4 calls mapl_infosetprivate
test_set_stateitem_private_r4_1d calls mapl_infosetprivate
test_set_stateitem_private_r8 calls mapl_infosetprivate
test_set_stateitem_private_string calls mapl_infosetprivate
test_setprivate_is_private calls mapl_infosetprivate