MAPL_UserCompSetInternalState – MAPL
MAPL_UserCompSetInternalState Interface
9 statements
Source File
public interface MAPL_UserCompSetInternalState
Called by
Subroutines
private subroutine ESMF_UserCompSetInternalState(gridcomp, name, wrapper, status)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
character(len=*), intent(in) :: name
type(*), intent(inout) :: wrapper
integer, intent(out), optional :: status
Call graph
attach_coupler_meta calls mapl_usercompsetinternalstate
attach_inner_meta calls mapl_usercompsetinternalstate
attach_outer_meta calls mapl_usercompsetinternalstate
setservices calls mapl_usercompsetinternalstate
create_grid_comp_primary calls attach_outer_meta, setservices_
make_coupler calls attach_coupler_meta
setservices_ calls attach_inner_meta, setservices_
create_grid_comp calls create_grid_comp_primary
add_state_extension calls make_coupler
add_child_by_name calls create_grid_comp
extend_ calls add_state_extension
make_driver calls create_grid_comp
setup calls create_grid_comp
test_is_generic calls create_grid_comp
test_mapl_invalid_name calls create_grid_comp