MAPL_SameGeom – MAPL
MAPL_SameGeom Interface
3 statements
Source File
public interface MAPL_SameGeom
Calls
Called by
Module Procedures
private function same_geom(geom_a, geom_b)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom_a
type(ESMF_Geom), intent(in) :: geom_b
Return Value logical
Call graph
mapl_samegeom calls same_geom
same_geom calls mapl_geomgetid
mapl_geomgetid calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
equal_to calls mapl_samegeom
make_action calls mapl_samegeom, match, make_action
match_geom calls mapl_samegeom
match calls match_geom
operator(==) calls equal_to
can_connect_units calls match
get_cost_geom calls match
get_cost_string calls match
get_cost_typekind calls match
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match
get_cost calls get_cost_geom, get_cost_string, get_cost_typekind
update_item calls update_item_geom, update_item_string, update_item_typekind
can_connect_to calls can_connect_units