MAPL_UserCompGetInternalState – MAPL
MAPL_UserCompGetInternalState Interface
9 statements
Source File
public interface MAPL_UserCompGetInternalState
Called by
Subroutines
private subroutine ESMF_UserCompGetInternalState(gridcomp, name, wrapper, status)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
character(len=*), intent(in) :: name
type(*), intent(inout) :: wrapper
integer, intent(out), optional :: status
Call graph
free_coupler_meta calls mapl_usercompgetinternalstate
free_inner_meta calls mapl_usercompgetinternalstate
free_outer_meta calls mapl_usercompgetinternalstate, free_inner_meta
get_coupler_meta calls mapl_usercompgetinternalstate
get_inner_meta calls mapl_usercompgetinternalstate
get_outer_meta_from_outer_gc calls mapl_usercompgetinternalstate
init calls mapl_usercompgetinternalstate
run calls mapl_usercompgetinternalstate
get_outer_meta calls get_outer_meta_from_outer_gc
clock_advance calls get_coupler_meta
get_outer_gridcomp calls get_inner_meta
initialize calls get_coupler_meta
invalidate calls get_coupler_meta
make_coupler calls get_coupler_meta
update calls get_coupler_meta