MAPL_InfoCreateFromInternal – MAPL
MAPL_InfoCreateFromInternal Interface
4 statements
Source File
public interface MAPL_InfoCreateFromInternal
Called by
Module Procedures
private function info_field_create_from_internal(field, key, rc) result(info)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in), optional :: key
integer, intent(out), optional :: rc
Return Value type(ESMF_Info)
private function info_bundle_create_from_internal(bundle, key, rc) result(info)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
character(len=*), intent(in), optional :: key
integer, intent(out), optional :: rc
Return Value type(ESMF_Info)
Call graph
mapl_fieldbundleget calls mapl_infocreatefrominternal
test_field_set_info calls mapl_infocreatefrominternal
test_info_get_internal_info calls mapl_infocreatefrominternal
teardown_bundle calls mapl_fieldbundleget
test_change_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_units calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_same_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle