MAPL_FieldGet – MAPL
MAPL_FieldGet Interface
3 statements
Source File
public interface MAPL_FieldGet
Called by
Module Procedures
private subroutine field_get(field, unusable, short_name, typekind, num_levels, vert_staggerloc, num_vgrid_levels, ungridded_dims, units, standard_name, long_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=:), intent(out), optional, allocatable :: short_name
type(ESMF_TypeKind_Flag), intent(out), optional :: typekind
integer, intent(out), optional :: num_levels
type(VerticalStaggerLoc), intent(out), optional :: vert_staggerloc
integer, intent(out), optional :: num_vgrid_levels
type(UngriddedDims), intent(out), optional :: ungridded_dims
character(len=:), intent(out), optional, allocatable :: units
character(len=:), intent(out), optional, allocatable :: standard_name
character(len=:), intent(out), optional, allocatable :: long_name
integer, intent(out), optional :: rc
Call graph
add_ungridded_dimensions calls mapl_fieldget
add_variable calls mapl_fieldget, get_variable_dim_names
add_vertical_dimensions calls mapl_fieldget
get_vertical_dimension_name_from_field calls mapl_fieldget
test_change_geom calls mapl_fieldget, reallocate_field
test_change_units calls mapl_fieldget
test_change_weights calls mapl_fieldget
test_change_weights_with_ungridded calls mapl_fieldget
test_create_fields calls mapl_fieldget
test_create_fields_with_ungridded calls mapl_fieldget
test_field_update_from_field_ignore_geom calls mapl_fieldget, initialize, update_field
test_get_units calls mapl_fieldget
test_same_geom calls mapl_fieldget
ungridded_dim_names calls mapl_fieldget
add_variables calls add_variable
bundle_to_metadata calls add_ungridded_dimensions, add_vertical_dimensions, add_variables
get_variable_dim_names calls get_vertical_dimension_name_from_field, ungridded_dim_names
test_change_n_levels calls reallocate_field
test_change_n_levels_surface calls reallocate_field
test_change_typekind calls reallocate_field
test_same_geom_do_not_reallocate calls reallocate_field
test_same_n_levels_do_not_reallocate calls reallocate_field
test_same_typekind_do_not_reallocate calls reallocate_field