MAPL_InfoSetInternal – MAPL
MAPL_InfoSetInternal Interface
15 statements
Source File
public interface MAPL_InfoSetInternal
Called by
Module Procedures
private subroutine info_field_set_internal_info(field, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in) :: key
type(ESMF_Info), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_field_set_internal_string(field, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in) :: key
character(len=*), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_field_set_internal_i4(field, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in) :: key
integer, intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_set_internal_info(bundle, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
character(len=*), intent(in) :: key
type(ESMF_Info), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_set_internal_string(bundle, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
character(len=*), intent(in) :: key
character(len=*), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_set_internal_i4(bundle, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
character(len=*), intent(in) :: key
integer, intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_set_internal_r4_1d(bundle, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(in), dimension(:) :: values
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_internal_string(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
character(len=*), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_internal_logical(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
logical, intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_internal_i4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
integer, intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_internal_r4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_internal_r8(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R8), intent(in) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_set_internal_r4_1d(state, short_name, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(in) :: values(:)
integer, intent(out), optional :: rc
Call graph
setup_bundle calls mapl_infosetinternal
test_field_set_string calls mapl_infosetinternal
test_info_get_internal_info calls mapl_infosetinternal
test_interp_constant calls mapl_infosetinternal
test_interp_midway calls mapl_infosetinternal
test_mapl_undef calls mapl_infosetinternal
test_set_stateitem_internal_i4 calls mapl_infosetinternal
test_set_stateitem_internal_logical calls mapl_infosetinternal
test_set_stateitem_internal_r4 calls mapl_infosetinternal
test_set_stateitem_internal_r4_1d calls mapl_infosetinternal
test_set_stateitem_internal_r8 calls mapl_infosetinternal
test_set_stateitem_internal_string calls mapl_infosetinternal
test_setinternal_bundle calls mapl_infosetinternal
test_change_geom calls update_bundle, setup_bundle
test_change_typekind calls update_bundle, setup_bundle
test_change_units calls update_bundle, setup_bundle
test_change_weights calls update_bundle, setup_bundle
test_change_weights_with_ungridded calls update_bundle, setup_bundle
test_create_fields calls update_bundle, setup_bundle
test_create_fields_with_ungridded calls update_bundle, setup_bundle
test_field_update_from_field_ignore_geom calls update_field
test_same_geom calls update_bundle, setup_bundle