MAPL_AddAttributeToFields – MAPL
MAPL_AddAttributeToFields Interface
3 statements
Source File
public interface MAPL_AddAttributeToFields
Calls
Called by
Module Procedures
private recursive subroutine MAPL_AddAttributeToFields_I4(gc, field_name, att_name, att_val, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout), pointer :: gc
character(len=*), intent(in) :: field_name
character(len=*), intent(in) :: att_name
integer(kind=int32), intent(in) :: att_val
integer, intent(out), optional :: rc
Call graph
mapl_addattributetofields calls mapl_addattributetofields_i4
mapl_addattributetofields_i4 calls mapl_addattributetofields_i4, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoSet, esmf_stateget, mapl_assert, mapl_getobjectfromgc, get_child_gridcomp, get_num_children, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_getobjectfromgc calls mapl_internalstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
initialize_extdata calls mapl_addattributetofields
initialize_gc calls initialize_extdata