MAPL_InfoGetPrivate – MAPL
MAPL_InfoGetPrivate Interface
8 statements
Source File
public interface MAPL_InfoGetPrivate
Called by
Module Procedures
private subroutine info_stateitem_get_private_string(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_private_logical(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
logical, intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_private_i4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_private_r4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_private_r8(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R8), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_private_r4_1d(state, short_name, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out), allocatable, dimension(:) :: values
integer, intent(out), optional :: rc
Call graph
test_set_stateitem_private_i4 calls mapl_infogetprivate
test_set_stateitem_private_logical calls mapl_infogetprivate
test_set_stateitem_private_r4 calls mapl_infogetprivate
test_set_stateitem_private_r4_1d calls mapl_infogetprivate
test_set_stateitem_private_r8 calls mapl_infogetprivate
test_set_stateitem_private_string calls mapl_infogetprivate
test_setprivate_is_private calls mapl_infogetprivate