MAPL_ConnectAll – MAPL
MAPL_ConnectAll Interface
3 statements
Source File
public interface MAPL_ConnectAll
Calls
Called by
Module Procedures
private subroutine gridcomp_connect_all(gridcomp, src_comp, dst_comp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
character(len=*), intent(in) :: src_comp
character(len=*), intent(in) :: dst_comp
integer, intent(out), optional :: rc
Call graph
mapl_connectall calls gridcomp_connect_all
gridcomp_connect_all calls mapl_gridcompgetoutermeta, connect_all, mapl_return, mapl_verify
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
connect_all calls mapl_return, mapl_assert, add_connection
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_connection calls vector_push_back
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
setservices calls mapl_connectall