MAPL_InfoGetShared – MAPL
MAPL_InfoGetShared Interface
10 statements
Source File
public interface MAPL_InfoGetShared
Called by
Module Procedures
private subroutine info_state_get_shared_string(state, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_field_get_shared_i4(field, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(out) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_shared_string(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_shared_logical(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
logical, intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_shared_i4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_shared_r4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_shared_r8(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R8), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_shared_r4_1d(state, short_name, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out), allocatable :: values(:)
integer, intent(out), optional :: rc
Call graph
test_copy_shared_field calls mapl_infogetshared
test_set_namespace calls mapl_infogetshared
test_set_stateitem_shared_i4 calls mapl_infogetshared
test_set_stateitem_shared_logical calls mapl_infogetshared
test_set_stateitem_shared_r4 calls mapl_infogetshared
test_set_stateitem_shared_r4_1d calls mapl_infogetshared
test_set_stateitem_shared_r8 calls mapl_infogetshared
test_set_stateitem_shared_string calls mapl_infogetshared