MAPL_AddExportSpec – MAPL
MAPL_AddExportSpec Interface
3 statements
Source File
public interface MAPL_AddExportSpec
Calls
Module Procedures
private subroutine add_export_spec(gridcomp, unusable, short_name, standard_name, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: standard_name
character(len=*), intent(in), optional :: units
integer, intent(out), optional :: rc
Call graph
mapl_addexportspec calls add_export_spec
add_export_spec calls mapl_gridcompgetoutermeta, get_component_spec, mapl_return, mapl_verify, vector_push_back
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity