MAPL_AddImportSpec – MAPL
MAPL_AddImportSpec Interface
3 statements
Source File
public interface MAPL_AddImportSpec
Calls
Module Procedures
private subroutine add_import_spec_legacy(gc, short_name, long_name, units, dims, vlocation, datatype, num_subtiles, refresh_interval, averaging_interval, halowidth, precision, default, restart, ungridded_dims, field_type, staggering, rotation, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: short_name
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: units
integer, intent(in), optional :: dims
integer, intent(in), optional :: vlocation
integer, intent(in), optional :: datatype
integer, intent(in), optional :: num_subtiles
integer, intent(in), optional :: refresh_interval
integer, intent(in), optional :: averaging_interval
integer, intent(in), optional :: halowidth
integer, intent(in), optional :: precision
real, intent(in), optional :: default
integer, intent(in), optional :: restart
integer, intent(in), optional :: ungridded_dims(:)
integer, intent(in), optional :: field_type
integer, intent(in), optional :: staggering
integer, intent(in), optional :: rotation
integer, intent(out), optional :: rc
Call graph
mapl_addimportspec calls add_import_spec_legacy
add_import_spec_legacy calls mapl_addspec, mapl_return, mapl_verify
mapl_addspec calls add_spec_basic, add_spec_explicit
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_spec_basic calls mapl_return, mapl_verify, mapl_gridcompgetoutermeta, get_component_spec, vector_push_back
add_spec_explicit calls mapl_addspec, mapl_return, mapl_verify
get_error_message calls at, insert
mapl_throw_exception calls initialize