MAPL_GridCompCreate – MAPL
MAPL_GridCompCreate Interface
3 statements
Source File
public interface MAPL_GridCompCreate
Called by
Module Procedures
private recursive function create_grid_comp_primary(name, set_services, config, unusable, petlist, rc) result(gridcomp)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
class(AbstractUserSetServices), intent(in) :: set_services
type(ESMF_HConfig), intent(in) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: petlist(:)
integer, intent(out), optional :: rc
Return Value type(ESMF_GridComp)
Call graph
mapl_run_driver calls mapl_gridcompcreate
setup calls mapl_gridcompcreate
test_child_call_frequency calls mapl_gridcompcreate
test_child_call_frequency_with_offset calls mapl_gridcompcreate
test_default_timestep calls mapl_gridcompcreate
test_double_timestep calls mapl_gridcompcreate
test_is_generic calls mapl_gridcompcreate
run_geos calls mapl_run_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
geos calls run_geos