MAPL_GridCompIsGeneric – MAPL
MAPL_GridCompIsGeneric Interface
3 statements
Source File
public interface MAPL_GridCompIsGeneric
Calls
Called by
Module Procedures
private function gridcomp_is_generic(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(in) :: gridcomp
integer, intent(out), optional :: rc
Return Value logical
Call graph
mapl_gridcompisgeneric calls gridcomp_is_generic
gridcomp_is_generic calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
gridcomp_get_outer_meta calls mapl_gridcompisgeneric, mapl_gridcompgetoutermeta, get_outer_gridcomp
gridcomp_is_user calls mapl_gridcompisgeneric
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_gridcompisuser calls gridcomp_is_user
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
get_outer_gridcomp calls mapl_gridcompisuser
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta
mapl_addchild calls add_child_by_name
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic
mapl_connectall calls gridcomp_connect_all
mapl_gridcompget calls gridcomp_get
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
mapl_runchild calls run_child_by_name
mapl_runchildren calls run_children
get_outer_meta_from_inner_gc calls get_outer_gridcomp
setup calls mapl_gridcompsetverticalgeom
test_full_run_sequence calls mapl_gridcompsetverticalgeom