MAPL_GridCompIsUser – MAPL
MAPL_GridCompIsUser Interface
3 statements
Source File
public interface MAPL_GridCompIsUser
Calls
Called by
Module Procedures
private function gridcomp_is_user(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(in) :: gridcomp
integer, intent(out), optional :: rc
Return Value logical
Call graph
mapl_gridcompisuser calls gridcomp_is_user
gridcomp_is_user calls mapl_gridcompisgeneric, mapl_return, mapl_verify
mapl_gridcompisgeneric calls gridcomp_is_generic
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_is_generic calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsSet
mapl_throw_exception calls initialize
get_outer_gridcomp calls mapl_gridcompisuser
get_outer_meta_from_inner_gc calls get_outer_gridcomp
gridcomp_get_outer_meta calls get_outer_gridcomp, mapl_gridcompgetoutermeta
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
run calls get_outer_meta_from_inner_gc
setservices calls get_outer_meta_from_inner_gc, setservices
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta