MAPL_RunChildren – MAPL
MAPL_RunChildren Interface
3 statements
Source File
public interface MAPL_RunChildren
Calls
Called by
Module Procedures
private subroutine run_children(gridcomp, unusable, phase_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: phase_name
integer, intent(out), optional :: rc
Call graph
mapl_runchildren calls run_children
run_children calls mapl_gridcompgetoutermeta, run_children, mapl_return, mapl_verify
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
run_children_ calls mapl_return, mapl_verify, run_child, omap_ftn_begin, omap_ftn_end, omap_iter_first, omap_iter_next
run calls mapl_runchildren