MAPL_FieldInfoSetInternal – MAPL
MAPL_FieldInfoSetInternal Interface
3 statements
Source File
public interface MAPL_FieldInfoSetInternal
Called by
Module Procedures
private subroutine field_info_set_internal(field, unusable, num_levels, vert_staggerloc, ungridded_dims, units, long_name, standard_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: num_levels
type(VerticalStaggerLoc), intent(in), optional :: vert_staggerloc
type(UngriddedDims), intent(in), optional :: ungridded_dims
character(len=*), intent(in), optional :: units
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: standard_name
integer, intent(out), optional :: rc
Call graph
test_change_geom calls mapl_fieldinfosetinternal
test_change_n_levels calls mapl_fieldinfosetinternal
test_change_n_levels_surface calls mapl_fieldinfosetinternal
test_change_typekind calls mapl_fieldinfosetinternal
test_field_update_from_field_ignore_geom calls mapl_fieldinfosetinternal
test_same_geom_do_not_reallocate calls mapl_fieldinfosetinternal
test_same_typekind_do_not_reallocate calls mapl_fieldinfosetinternal