MAPL_GridCompSetGeom – MAPL
MAPL_GridCompSetGeom Interface
7 statements
Source File
private interface MAPL_GridCompSetGeom
Calls
Called by
Module Procedures
private interface MAPL_GridCompSetGeom()
Arguments
None
private subroutine MAPL_GridCompSetGeomGrid(gridcomp, grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_Grid), intent(in) :: grid
integer, intent(out), optional :: rc
private subroutine MAPL_GridCompSetGeomMesh(gridcomp, mesh, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_Mesh), intent(in) :: mesh
integer, intent(out), optional :: rc
private subroutine MAPL_GridCompSetGeomXGrid(gridcomp, xgrid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_XGrid), intent(in) :: xgrid
integer, intent(out), optional :: rc
private subroutine MAPL_GridCompSetGeomLocStream(gridcomp, locstream, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_LocStream), intent(in) :: locstream
integer, intent(out), optional :: rc
Call graph
mapl_gridcompsetgeom calls mapl_gridcompsetgeom, mapl_gridcompsetgeomgrid, mapl_gridcompsetgeomlocstream, mapl_gridcompsetgeommesh, mapl_gridcompsetgeomxgrid
mapl_gridcompsetgeomgrid calls mapl_gridcompsetgeom, ESMF_GeomCreate, mapl_return, mapl_verify
mapl_gridcompsetgeomlocstream calls mapl_gridcompsetgeom, ESMF_GeomCreate, mapl_return, mapl_verify
mapl_gridcompsetgeommesh calls mapl_gridcompsetgeom, ESMF_GeomCreate, mapl_return, mapl_verify
mapl_gridcompsetgeomxgrid calls mapl_gridcompsetgeom, ESMF_GeomCreate, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize