MAPL_InfoGet – MAPL
MAPL_InfoGet Interface
8 statements
Source File
public interface MAPL_InfoGet
Called by
Module Procedures
private subroutine info_get_string(info, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_get_logical(info, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in) :: key
logical, intent(out) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_get_i4(info, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(out) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_get_r4(info, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_get_r8(info, key, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R8), intent(out) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine info_get_r4_1d(info, key, values, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out), allocatable :: values(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Call graph
get_num_levels_bundle_info calls mapl_infoget
get_vertical_dim_spec_names_bundle_info calls mapl_infoget
make_ungriddeddim calls mapl_infoget
make_ungriddeddims calls mapl_infoget, make_ungriddeddim
test_field_set_info calls mapl_infoget
get_ungridded_dims_bundle_info calls make_ungriddeddims
mapl_fieldbundleget calls make_ungriddeddims
test_get_num_levels calls get_num_levels_bundle_info
test_get_vertical_dim_spec_names calls get_vertical_dim_spec_names_bundle_info
test_make_ungridded_dim calls make_ungriddeddim
test_make_ungridded_dims calls make_ungriddeddims
teardown_bundle calls mapl_fieldbundleget
test_change_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_units calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_get_ungridded_dims calls get_ungridded_dims_bundle_info
test_same_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle