MAPL_ResourceGet – MAPL
MAPL_ResourceGet Interface
13 statements
Source File
public interface MAPL_ResourceGet
Calls
Called by
Module Procedures
private subroutine resource_get_i4_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
integer(kind=ESMF_KIND_I4), intent(inout) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer(kind=ESMF_KIND_I4), intent(in), optional :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_i8_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
integer(kind=ESMF_KIND_I8), intent(inout) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer(kind=ESMF_KIND_I8), intent(in), optional :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_r4_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
real(kind=ESMF_KIND_R4), intent(inout) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=ESMF_KIND_R4), intent(in), optional :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_r8_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
real(kind=ESMF_KIND_R8), intent(inout) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=ESMF_KIND_R8), intent(in), optional :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_logical_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
logical, intent(inout) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_i4seq_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
integer(kind=ESMF_KIND_I4), intent(inout), dimension(:), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer(kind=ESMF_KIND_I4), intent(in), optional, dimension(:) :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_i8seq_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
integer(kind=ESMF_KIND_I8), intent(inout), dimension(:), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer(kind=ESMF_KIND_I8), intent(in), optional, dimension(:) :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_r4seq_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
real(kind=ESMF_KIND_R4), intent(inout), dimension(:), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=ESMF_KIND_R4), intent(in), optional, dimension(:) :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_r8seq_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
real(kind=ESMF_KIND_R8), intent(inout), dimension(:), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=ESMF_KIND_R8), intent(in), optional, dimension(:) :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_logical_seq_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
logical, intent(inout), dimension(:), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional, dimension(:) :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
private subroutine resource_get_string_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
character(len=:), intent(inout), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
Call graph
mapl_resourceget calls resource_get_i4_gc, resource_get_i4seq_gc, resource_get_i8_gc, resource_get_i8seq_gc, resource_get_logical_gc, resource_get_logical_seq_gc, resource_get_r4_gc, resource_get_r4seq_gc, resource_get_r8_gc, resource_get_r8seq_gc, resource_get_string_gc
resource_get_i4_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_i4seq_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_i8_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_i8seq_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_logical_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_logical_seq_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_r4_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_r4seq_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_r8_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_r8seq_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
resource_get_string_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
mapl_gridcompget calls gridcomp_get
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setservices calls mapl_resourceget