MAPL_RunChild – MAPL
MAPL_RunChild Interface
3 statements
Source File
public interface MAPL_RunChild
Calls
Called by
Module Procedures
private subroutine run_child_by_name(gridcomp, child_name, unusable, phase_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
character(len=*), intent(in) :: child_name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: phase_name
integer, intent(out), optional :: rc
Call graph
mapl_runchild calls run_child_by_name
run_child_by_name calls mapl_gridcompgetoutermeta, run_child, mapl_return, mapl_verify, get_phase_index, mapl_assert, run, get_child, get_phases
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
run calls mapl_runchild
test_mapl_runchild calls mapl_runchild
test_mapl_runchild_other_phase calls mapl_runchild