MAPL_InfoGetInternal – MAPL
MAPL_InfoGetInternal Interface
13 statements
Source File
public interface MAPL_InfoGetInternal
Called by
Module Procedures
private subroutine info_field_get_internal_string(field, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
integer, intent(out), optional :: rc
private subroutine info_field_get_internal_i4(field, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_get_internal_string(bundle, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_get_internal_i4(bundle, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
character(len=*), intent(in) :: key
integer(kind=ESMF_KIND_I4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_bundle_get_internal_r4_1d(bundle, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out), allocatable :: values(:)
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_internal_string(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
character(len=:), intent(out), allocatable :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_internal_logical(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
logical, intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_internal_i4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
integer, intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_internal_r4(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_internal_r8(state, short_name, key, value, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R8), intent(out) :: value
integer, intent(out), optional :: rc
private subroutine info_stateitem_get_internal_r4_1d(state, short_name, key, values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: key
real(kind=ESMF_KIND_R4), intent(out), allocatable :: values(:)
integer, intent(out), optional :: rc
Call graph
add_variable calls mapl_infogetinternal
mapl_fieldbundleget calls mapl_infogetinternal
test_change_geom calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_units calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_field_set_string calls mapl_infogetinternal
test_field_update_from_field_ignore_geom calls mapl_infogetinternal
test_same_geom calls mapl_infogetinternal, mapl_fieldbundleget, update_bundle, teardown_bundle
test_set_stateitem_internal_i4 calls mapl_infogetinternal
test_set_stateitem_internal_logical calls mapl_infogetinternal
test_set_stateitem_internal_r4 calls mapl_infogetinternal
test_set_stateitem_internal_r4_1d calls mapl_infogetinternal
test_set_stateitem_internal_r8 calls mapl_infogetinternal
test_set_stateitem_internal_string calls mapl_infogetinternal
test_setinternal_bundle calls mapl_infogetinternal
add_variables calls add_variable
teardown_bundle calls mapl_fieldbundleget
test_interp_constant calls update
test_interp_midway calls update
test_mapl_undef calls update
bundle_to_metadata calls add_variables