MAPL_FieldSet – MAPL
MAPL_FieldSet Interface
3 statements
Source File
public interface MAPL_FieldSet
Called by
Module Procedures
private subroutine field_set(field, num_levels, vert_staggerloc, ungridded_dims, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(in), optional :: num_levels
type(VerticalStaggerLoc), intent(in), optional :: vert_staggerloc
type(UngriddedDims), intent(in), optional :: ungridded_dims
character(len=*), intent(in), optional :: units
integer, intent(out), optional :: rc
Call graph
test_change_geom calls mapl_fieldset, update_bundle
test_change_n_levels calls mapl_fieldset
test_change_n_levels_surface calls mapl_fieldset
test_change_typekind calls mapl_fieldset, update_bundle
test_field_update_from_field_ignore_geom calls mapl_fieldset, update_field
test_same_geom_do_not_reallocate calls mapl_fieldset
test_same_typekind_do_not_reallocate calls mapl_fieldset
test_change_units calls update_bundle
test_change_weights calls update_bundle
test_change_weights_with_ungridded calls update_bundle
test_create_fields calls update_bundle
test_create_fields_with_ungridded calls update_bundle
test_same_geom calls update_bundle