MAPL_AddChild – MAPL
MAPL_AddChild Interface
7 statements
Source File
public interface MAPL_AddChild
Called by
Module Procedures
private recursive function AddChildFromGC(GC, name, SS, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: name
real :: SS
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromMeta(META, NAME, GRID, CONFIGFILE, SS, parentGC, petList, rc)
$ call ESMF_GridCompSetServices (child_meta%gridcomp, SS, userRC=userRC, rc=status);if(MAPL_Verify(status ,”/home/runner/work/MAPL/MAPL/generic/MAPL_Generic.F90”,4743 ,rc)) return $ if(MAPL_Verify(userRC,”/home/runner/work/MAPL/MAPL/generic/MAPL_Generic.F90”,4744 ,rc)) return
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: META
character(len=*), intent(in) :: NAME
type(ESMF_Grid), intent(inout), optional :: GRID
character(len=*), intent(in), optional :: CONFIGFILE
real :: SS
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(in), optional :: petList(:)
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromDSO_old(name, userRoutine, grid, ParentGC, SharedObj, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
type(ESMF_GridComp), intent(inout), optional :: ParentGC
character(len=*), intent(in), optional :: SharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromDSO(gc, name, userRoutine, grid, sharedObj, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
character(len=*), intent(in), optional :: sharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromDSOMeta(META, name, userRoutine, sharedObj, grid, petList, configFile, parentGC, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: META
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
character(len=*), intent(in) :: sharedObj
type(ESMF_Grid), intent(inout), optional :: grid
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(out), optional :: rc
Return Value integer
Call graph
run_component_driver calls mapl_addchild
main calls run_component_driver
comp_testing_driver calls main