MAPL_FieldEmptyComplete – MAPL
MAPL_FieldEmptyComplete Interface
3 statements
Source File
public interface MAPL_FieldEmptyComplete
Called by
Module Procedures
private subroutine field_empty_complete(field, typekind, unusable, gridToFieldMap, ungridded_dims, num_levels, vert_staggerloc, units, standard_name, long_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
type(ESMF_TypeKind_Flag), intent(in) :: typekind
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: gridToFieldMap(:)
type(UngriddedDims), intent(in), optional :: ungridded_dims
integer, intent(in), optional :: num_levels
type(VerticalStaggerLoc), intent(in), optional :: vert_staggerloc
character(len=*), intent(in), optional :: units
character(len=*), intent(in), optional :: standard_name
character(len=*), intent(in), optional :: long_name
integer, intent(out), optional :: rc
Call graph
setup_field calls mapl_fieldemptycomplete
test_reset_empty calls mapl_fieldemptycomplete
test_reset_gridset calls mapl_fieldemptycomplete
setup_bundle calls setup_field
test_change_geom calls update_bundle, setup_bundle
test_change_typekind calls update_bundle, setup_bundle
test_change_units calls update_bundle, setup_bundle
test_change_weights calls update_bundle, setup_bundle
test_change_weights_with_ungridded calls update_bundle, setup_bundle
test_create_fields calls update_bundle, setup_bundle
test_create_fields_with_ungridded calls update_bundle, setup_bundle
test_same_geom calls update_bundle, setup_bundle