MAPL_AddSpec – MAPL
MAPL_AddSpec Interface
4 statements
Source File
public interface MAPL_AddSpec
Calls
Called by
Module Procedures
private subroutine add_spec_basic(gridcomp, var_spec, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(VariableSpec), intent(in) :: var_spec
integer, intent(out), optional :: rc
private subroutine add_spec_explicit(gridcomp, state_intent, unusable, short_name, standard_name, typekind, ungridded_dims, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_StateIntent_Flag), intent(in) :: state_intent
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: standard_name
type(ESMF_TypeKind_Flag), intent(in), optional :: typekind
type(UngriddedDimsSpec), intent(in) :: ungridded_dims
character(len=*), intent(in), optional :: units
integer, intent(out), optional :: rc
Call graph
mapl_addspec calls add_spec_basic, add_spec_explicit
add_spec_basic calls mapl_gridcompgetoutermeta, get_component_spec, mapl_return, mapl_verify, vector_push_back
add_spec_explicit calls mapl_addspec, mapl_return, mapl_verify
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
add_import_spec_legacy calls mapl_addspec
mapl_addimportspec calls add_import_spec_legacy