MAPL_SetPointer – MAPL
MAPL_SetPointer Interface
4 statements
Source File
public interface MAPL_SetPointer
Calls
Module Procedures
private interface MAPL_SetPointer2DR4()
Arguments
None
private interface MAPL_SetPointer3DR4()
Arguments
None
Call graph
mapl_setpointer calls mapl_setpointer2dr4, mapl_setpointer3dr4
mapl_setpointer2dr4 calls mapl_setpointer2dr4, ESMF_GridGet, esmf_fieldemptycomplete, esmf_fieldget, esmf_stateget, mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_setpointer3dr4 calls mapl_setpointer3dr4, ESMF_GridGet, esmf_fieldemptycomplete, esmf_fieldget, esmf_stateget, mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception