MAPL_AttributeSet – MAPL
MAPL_AttributeSet Interface
5 statements
Source File
public interface MAPL_AttributeSet
Calls
Called by
Module Procedures
private interface MAPL_StateAttSetI4()
Arguments
None
private interface MAPL_BundleAttSetI4()
Arguments
None
private interface MAPL_FieldAttSetI4()
Arguments
None
Call graph
mapl_attributeset calls mapl_bundleattseti4, mapl_fieldattseti4, mapl_stateattseti4
mapl_bundleattseti4 calls mapl_bundleattseti4, ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_fieldbundleget, mapl_return, mapl_verify
mapl_fieldattseti4 calls mapl_fieldattseti4, ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_fieldget, mapl_return, mapl_verify
mapl_stateattseti4 calls mapl_stateattseti4, mapl_attributeset, ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_stateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_esmfstatereadfromfile calls mapl_attributeset
mapl_fieldalloccommit calls mapl_attributeset, mapl_fieldalloccommit
mapl_statecreatefromspecnew calls mapl_attributeset, mapl_fieldalloccommit
mapl_genericinitialize calls mapl_esmfstatereadfromfile, mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
mapl_staterefresh calls mapl_esmfstatereadfromfile
initialize calls mapl_genericinitialize, mapl_statecreatefromspec
initialize_ calls mapl_fieldalloccommit, mapl_genericinitialize
mapl_allocatecoupling calls mapl_fieldalloccommit, mapl_allocatecoupling
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
mapl_readforcingx calls mapl_statecreatefromvarspecnew
refresh_state calls mapl_genericstaterestore
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx