MAPL_InfoSetNamespace – MAPL
MAPL_InfoSetNamespace Interface
3 statements
Source File
public interface MAPL_InfoSetNamespace
Called by
Module Procedures
private subroutine set_namespace(state, namespace, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: namespace
integer, intent(out), optional :: rc
Call graph
test_set_namespace calls mapl_infosetnamespace
test_set_stateitem_private_i4 calls mapl_infosetnamespace
test_set_stateitem_private_logical calls mapl_infosetnamespace
test_set_stateitem_private_r4 calls mapl_infosetnamespace
test_set_stateitem_private_r4_1d calls mapl_infosetnamespace
test_set_stateitem_private_r8 calls mapl_infosetnamespace
test_set_stateitem_private_string calls mapl_infosetnamespace
test_setprivate_is_private calls mapl_infosetnamespace