match – MAPL
match Interface
5 statements
Source File
private interface match
Calls
Called by
Module Procedures
private function match_geom(a, b) result(match)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in), allocatable :: a
type(ESMF_Geom), intent(in), allocatable :: b
Return Value logical
private function match_typekind(a, b) result(match)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TypeKind_Flag), intent(in) :: a
type(ESMF_TypeKind_Flag), intent(in) :: b
Return Value logical
private function match_string(a, b) result(match)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(in), allocatable :: a
character(len=:), intent(in), allocatable :: b
Return Value logical
Call graph
match calls match_geom, match_string, match_typekind
match_geom calls mapl_samegeom
match_string calls mirror
mapl_samegeom calls same_geom
same_geom calls mapl_geomgetid
can_connect_units calls match
get_cost_geom calls match
get_cost_string calls match
get_cost_typekind calls match
make_action calls match, make_action
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match
get_cost calls get_cost_geom, get_cost_string, get_cost_typekind
update_item calls update_item_geom, update_item_string, update_item_typekind
can_connect_to calls can_connect_units, can_connect_to
connect_to calls can_connect_to, connect_to
extension_cost calls get_cost, extension_cost
make_extension_safely calls update_item
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to
make_extension calls make_extension_safely
test_connect_unique_mirror calls can_connect_to
test_mirror_bracket_size calls can_connect_to