match – MAPL
match Interface
4 statements
Source File
private interface match
Calls
Called by
Module Procedures
private function match_r4(missing, b)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: missing
real(kind=ESMF_KIND_R4), intent(in) :: b
Return Value logical
private function match_r8(missing, b)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: missing
real(kind=ESMF_KIND_R8), intent(in) :: b
Return Value logical
Call graph
match calls match_r4, match_r8
fraction_r4r8r4v calls match
fraction_r8r8r8v calls match
missing_r4r8r4v calls match
missing_r8r8r8v calls match
monotonic_r4r8r4v calls match
monotonic_r8r8r8v calls match
vote_r4r8r4v calls match
vote_r8r8r8v calls match