MethodPhasesMap – MAPL
MethodPhasesMap Interface
5 statements
Source File
public interface MethodPhasesMap
Calls
Module Procedures
private function map_new_map_empty() result(m)
Arguments
None
Return Value type(MethodPhasesMap)
private function map_new_map_copy(x) result(m)
Arguments
Type Intent Optional Attributes Name
type(MethodPhasesMap), intent(in) :: x
Return Value type(MethodPhasesMap)
private function map_new_map_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(MethodPhasesPair), intent(in) :: il(:)
Return Value type(MethodPhasesMap)
Call graph
methodphasesmap calls map_new_map_copy, map_new_map_empty, map_new_map_initializer_list
map_new_map_initializer_list calls insert
map_insert_pair calls insert