next – MAPL
next Interface
5 statements
Source File
private interface next
Calls
Module Procedures
private function omap_K_riter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
Return Value type(omap_VectorRIterator)
private function omap_K_riter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(omap_VectorRIterator)
private function omap_K_riter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(omap_VectorRIterator)
Call graph
next calls omap_k_riter_next_1, omap_k_riter_next_n_default, omap_k_riter_next_n_size_kind, omap_iter_next_1, omap_iter_next_n_default, omap_iter_next_n_size_kind
omap_k_riter_next_1 calls next
omap_k_riter_next_n_default calls add
omap_k_riter_next_n_size_kind calls add
omap_iter_next_1 calls next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next
omap_k_riter_add_n_size_kind calls sub