next – MAPL
next Interface
5 statements
Source File
public interface next
Calls
Module Procedures
private function omap_I_s_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_I_SetIterator), intent(in) :: it
Return Value type(omap_I_SetIterator)
private function omap_I_s_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_I_SetIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(omap_I_SetIterator)
private function omap_I_s_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_I_SetIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(omap_I_SetIterator)
Call graph
next calls omap_i_s_iter_next_1, omap_i_s_iter_next_n_default, omap_i_s_iter_next_n_size_kind, omap_iter_next_1, omap_iter_next_n_default, omap_iter_next_n_size_kind
omap_i_s_iter_next_1 calls next
omap_i_s_iter_next_n_default calls omap_i_s_iter_next
omap_i_s_iter_next_n_size_kind calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_iter_next_1 calls next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next