next – MAPL
next Interface
5 statements
Source File
private interface next
Calls
Called by
Module Procedures
private function omap_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverMapIterator), intent(in) :: it
Return Value type(GriddedComponentDriverMapIterator)
private function omap_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverMapIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(GriddedComponentDriverMapIterator)
private function omap_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverMapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(GriddedComponentDriverMapIterator)
Call graph
next calls omap_iter_next_1, omap_iter_next_n_default, omap_iter_next_n_size_kind, omap_i_s_iter_next_1, omap_i_iter_next_1, omap_k_iter_next_1, omap_k_riter_next_1
omap_iter_next_1 calls next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next
omap_iter_next calls omap_k_iter_next
omap_i_iter_next_1 calls next
omap_i_s_ftn_end calls next
omap_i_s_iter_next_1 calls next
omap_k_iter_next_1 calls next
omap_k_riter_next_1 calls next
omap_i_ftn_end calls omap_i_s_ftn_end
omap_i_s_iter_ftn_end calls omap_i_s_ftn_end
ftn_end calls omap_i_s_iter_ftn_end, omap_i_iter_ftn_end
omap_i_iter_ftn_end calls omap_i_ftn_end