next – MAPL
next Interface
5 statements
Source File
private interface next
Calls
Called by
Module Procedures
private function map_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtComponentDriverMapIterator), intent(in) :: it
Return Value type(ActualPtComponentDriverMapIterator)
private function map_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtComponentDriverMapIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(ActualPtComponentDriverMapIterator)
private function map_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtComponentDriverMapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(ActualPtComponentDriverMapIterator)
Call graph
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind, map_s_iter_next_1
map_iter_next_1 calls next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_ftn_end calls next
map_s_iter_next_1 calls next
map_ftn_end calls map_s_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end
ftn_end calls map_s_iter_ftn_end, map_iter_ftn_end
map_iter_ftn_end calls map_ftn_end
run calls map_ftn_end, run