NS_VectorBasis – MAPL
NS_VectorBasis Interface
3 statements
Source File
public interface NS_VectorBasis
Calls
Called by
Module Procedures
private interface new_NS_Basis()
Arguments
None
Call graph
ns_vectorbasis calls new_ns_basis
new_ns_basis calls new_ns_basis, assign_fptr, create_fields, mapl_geomgetcoords, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
create_fields calls create_fields
mapl_geomgetcoords calls mapl_geomgetcoords
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_basis calls ns_vectorbasis