omap_Vector – MAPL
omap_Vector Interface
7 statements
Source File
private interface omap_Vector
Calls
Module Procedures
private function omap_K_new_vector_empty() result(v)
Arguments
None
Return Value type(omap_Vector)
private function omap_K_new_vector_fill_size_kind(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer(kind=GFTL_SIZE_KIND), intent(in) :: n
character(len=*), intent(in), optional :: value
Return Value type(omap_Vector)
private function omap_K_new_vector_fill_default(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
character(len=*), intent(in), optional :: value
Return Value type(omap_Vector)
private function omap_K_new_vector_range(first, last) result(v)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorIterator), intent(in) :: first
type(omap_VectorIterator), intent(in) :: last
Return Value type(omap_Vector)
private function omap_K_new_vector_copy(x) result(v)
Arguments
Type Intent Optional Attributes Name
type(omap_Vector) :: x
Return Value type(omap_Vector)
Call graph
omap_vector calls omap_k_new_vector_copy, omap_k_new_vector_empty, omap_k_new_vector_fill_default, omap_k_new_vector_fill_size_kind, omap_k_new_vector_range
omap_k_new_vector_copy calls resize
omap_k_new_vector_fill_default calls resize
omap_k_new_vector_fill_size_kind calls resize
omap_k_new_vector_range calls of, omap_k_push_back
omap_k_push_back calls resize, omap_k_grow_to
omap_k_grow_to calls omap_k_capacity, omap_k_set_capacity
omap_k_resize_size_kind calls reserve