operator(==) – MAPL
operator(==) Interface
3 statements
Source File
public interface operator(==)
Calls
Module Procedures
private function omap_I_s_equal(a, b) result(equal)
Arguments
Type Intent Optional Attributes Name
type(omap_I_Set), intent(in), target :: a
type(omap_I_Set), intent(in), target :: b
Return Value logical
Call graph
operator(==) calls omap_i_s_equal
omap_i_s_equal calls omap_i_s_begin, omap_i_s_iter_next, omap_i_s_iter_of, omap_i_s_order_eq
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_iter_of calls omap_i_s_get_value
omap_i_s_order_eq calls omap_i_s_lessthan
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_s_lessthan calls omap_i_key_less_than