operator(==) – MAPL
operator(==) Interface
3 statements
Source File
public interface operator(==)
Calls
Module Procedures
private function map_s_equal(a, b) result(equal)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in), target :: a
type(map_Set), intent(in), target :: b
Return Value logical
Call graph
operator(==) calls map_s_equal
map_s_equal calls map_s_begin, map_s_iter_next, map_s_iter_of, map_s_order_eq
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_order_eq calls map_s_lessthan
map_s_advpos calls map_s_get_child, to_node
map_s_lessthan calls map_key_less_than