operator(+) – MAPL
operator(+) Interface
6 statements
Source File
private interface operator(+)
Calls
Module Procedures
private function omap_K_iter_a_plus_n_size_kind(a, n) result(new_iter)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorIterator), intent(in) :: a
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(omap_VectorIterator)
private function omap_K_iter_n_plus_a_size_kind(n, a) result(new_iter)
Arguments
Type Intent Optional Attributes Name
integer(kind=selected_int_kind(18)), intent(in) :: n
type(omap_VectorIterator), intent(in) :: a
Return Value type(omap_VectorIterator)
private function omap_K_iter_n_plus_a_default(n, a) result(new_iter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(omap_VectorIterator), intent(in) :: a
Return Value type(omap_VectorIterator)
private function omap_K_iter_a_plus_n_default(a, n) result(new_iter)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorIterator), intent(in) :: a
integer, intent(in) :: n
Return Value type(omap_VectorIterator)
Call graph
operator(+) calls omap_k_iter_a_plus_n_default, omap_k_iter_a_plus_n_size_kind, omap_k_iter_n_plus_a_default, omap_k_iter_n_plus_a_size_kind
omap_k_iter_a_plus_n_default calls add
omap_k_iter_a_plus_n_size_kind calls add
omap_k_iter_n_plus_a_default calls add
omap_k_iter_n_plus_a_size_kind calls add