OuterMetaComponent – MAPL
OuterMetaComponent Interface
3 statements
Source File
public interface OuterMetaComponent
Calls
Module Procedures
private function new_outer_meta(gridcomp, user_gc_driver, hconfig) result(outer_meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(in) :: gridcomp
type(GriddedComponentDriver), intent(in) :: user_gc_driver
type(ESMF_HConfig), intent(in) :: hconfig
Return Value type(OuterMetaComponent)
Call graph
outermetacomponent calls new_outer_meta
new_outer_meta calls initialize_phases_map
initialize_phases_map calls insert, stringvector