prev – MAPL
prev Interface
5 statements
Source File
private interface prev
Calls
Module Procedures
private function omap_K_riter_prev_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
Return Value type(omap_VectorRIterator)
private function omap_K_riter_prev_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(omap_VectorRIterator)
private function omap_K_riter_prev_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(omap_VectorRIterator)
Call graph
prev calls omap_k_riter_prev_1, omap_k_riter_prev_n_default, omap_k_riter_prev_n_size_kind, omap_iter_prev_1, omap_iter_prev_n_default, omap_iter_prev_n_size_kind
omap_k_riter_prev_1 calls prev
omap_k_riter_prev_n_default calls sub
omap_k_riter_prev_n_size_kind calls sub
omap_iter_prev_1 calls prev
omap_iter_prev_n_default calls omap_iter_prev
omap_iter_prev_n_size_kind calls omap_iter_prev
omap_k_riter_sub_n_size_kind calls add