qsortl – MAPL
qsortl Interface
16 statements
Source File
interface
Called by
private subroutine qsortl(a, b, r, n) bind(C,name="QSORTL")
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: a(*)
type(*), intent(inout) :: b(*)
integer, intent(in), value :: r
integer, intent(in), value :: n
Call graph
sort1ld calls qsortl
sort1lr calls qsortl
sort1ls calls qsortl
sort2al calls qsortl
sort2ld calls qsortl
sort2lr calls qsortl
sort2ls calls qsortl
mapl_sort calls sort1ld, sort1lr, sort1ls, sort2al, sort2ld, sort2lr, sort2ls
arrdescrinit calls mapl_sort
foo calls mapl_sort
getnodecomm calls mapl_sort
mapl_balancecreate calls mapl_sort
mapl_cfiopartition calls mapl_sort
mapl_getimsjms calls mapl_sort
mapl_tilemaskget calls mapl_sort
mapl_varread_r4_1d calls mapl_sort
mapl_varread_r8_1d calls mapl_sort
mapl_varreadncpar_r8_1d calls mapl_sort
set_optimal_server calls mapl_sort
sort_four_arrays_by_time calls mapl_sort
sort_index calls mapl_sort
sort_three_arrays_by_time calls mapl_sort
split_server_pools calls mapl_sort
test_mapl_sort calls mapl_sort