RegridderManager – MAPL
RegridderManager Interface
3 statements
Source File
public interface RegridderManager
Calls
Module Procedures
private function new_RegridderManager() result(mgr)
$ call mgr%add_factory(horzHorzFluxRegridderFactory())
Arguments
None
Return Value type(RegridderManager)
Call graph
regriddermanager calls new_regriddermanager
new_regriddermanager calls add_factory
add_factory calls vector_push_back
vector_push_back calls resize, vector_grow_to