RegridAction – MAPL
RegridAction Interface
3 statements
Source File
public interface RegridAction
Calls
Called by
Module Procedures
private function new_ScalarRegridAction(geom_in, f_in, geom_out, f_out) result(action)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom) :: geom_in
type(ESMF_Field), intent(in) :: f_in
type(ESMF_Geom) :: geom_out
type(ESMF_Field), intent(in) :: f_out
Return Value type(ScalarRegridAction)
Call graph
regridaction calls new_scalarregridaction
new_scalarregridaction calls esmfregridderparam, get_regridder, get_regridder_manager
get_regridder calls find, of, add_regridder, make_regridder, mapl_return, mapl_verify, vector_back, vector_begin
add_regridder calls vector_push_back
make_regridder calls mapl_return, mapl_verify, mapl_assert, make_regridder, of, get_param, supports
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_action calls regridaction, make_action