supports_hconfig – MAPL
supports_hconfig Interface
42 statements
Source File
interface
Calls
Called by
private module function supports_hconfig(hconfig, rc) result(supports) Implementation →
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value logical
Call graph
supports_hconfig calls supports_hconfig, esmf_hconfigisdefined, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
supports_hconfig_ calls supports, supports_hconfig_
supports_metadata_ calls supports, supports_metadata_