supports_metadata – MAPL
supports_metadata Interface
42 statements
Source File
interface
Calls
Called by
private module function supports_metadata(file_metadata, rc) result(supports) Implementation →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value logical
Call graph
supports_metadata calls supports_metadata, get_dim_name, mapl_return, mapl_verify
get_dim_name calls get_dim_name, mapl_return, mapl_verify, ESMF_UtilStringLowerCase, mapl_assert, of, get_attribute, get_dimensions, get_string, get_variables, is_attribute_present, map_ftn_begin, map_ftn_end, map_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
supports_hconfig_ calls supports, supports_hconfig_
supports_metadata_ calls supports, supports_metadata_