to_ClassAspect – MAPL
to_ClassAspect Interface
4 statements
Source File
public interface to_ClassAspect
Called by
Module Procedures
private function to_class_from_poly(aspect, rc) result(class_aspect)
Arguments
Type Intent Optional Attributes Name
class(StateItemAspect), intent(in), pointer :: aspect
integer, intent(out), optional :: rc
Return Value class(ClassAspect), pointer
private function to_class_from_map(map, rc) result(class_aspect)
Arguments
Type Intent Optional Attributes Name
type(AspectMap), intent(in), pointer :: map
integer, intent(out), optional :: rc
Return Value class(ClassAspect), pointer
Call graph
setup_ calls activate, create
test_allocate calls create
test_created_fields_have_num_levels calls add_to_state, setup
test_do_not_propagate_satisfied_import calls activate
setup calls setup_
test_add_to_state calls add_to_states
test_find_closest_name calls find_closest_extension
test_find_closest_simple calls find_closest_extension
test_find_closest_subtype calls find_closest_extension
test_get_coordinate_field_change_units_center calls get_coordinate_field, setup
test_get_coordinate_field_change_units_edge calls get_coordinate_field, setup
test_get_coordinate_field_simple calls get_coordinate_field, setup