update_item – MAPL
update_item Interface
5 statements
Source File
private interface update_item
Calls
Called by
Module Procedures
private function update_item_geom(a, b)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(inout), allocatable :: a
type(ESMF_Geom), intent(in), allocatable :: b
Return Value logical
private function update_item_typekind(a, b)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TypeKind_Flag), intent(inout) :: a
type(ESMF_TypeKind_Flag), intent(in) :: b
Return Value logical
private function update_item_string(a, b)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(inout), allocatable :: a
character(len=:), intent(in), allocatable :: b
Return Value logical
Call graph
update_item calls update_item_geom, update_item_string, update_item_typekind
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match
match calls match_geom, match_string, match_typekind
match_geom calls mapl_samegeom
match_string calls mirror
make_extension_safely calls update_item
make_extension calls make_extension_safely