user_setservices – MAPL
user_setservices Interface
4 statements
Source File
public interface user_setservices
Called by
Module Procedures
private function new_ProcSetServices(userRoutine) result(proc_setservices)
Arguments
Type Intent Optional Attributes Name
procedure(I_SetServices) :: userRoutine
Return Value type(ProcSetServices)
private function new_DSOSetServices(sharedObj, userRoutine) result(dso_setservices)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: sharedObj
character(len=*), intent(in), optional :: userRoutine
Return Value type(DSOSetServices)
Call graph
mapl_run_driver calls user_setservices
setservices calls user_setservices, setservices
setup calls user_setservices
test_equal_child_spec_cfg_differs calls user_setservices
test_equal_child_spec_ss_differs calls user_setservices
test_is_generic calls user_setservices
test_mapl_invalid_name calls user_setservices
test_parse_childspec_basic calls user_setservices
test_parse_childspec_with_config_file calls user_setservices
test_parse_childspecmap_1 calls user_setservices
test_parse_childspecmap_2 calls user_setservices
run_geos calls mapl_run_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
test_wasfinal calls setup
test_wasinit calls setup
test_wasrun_1 calls setup
test_wasrun_extra calls setup