ut_are_convertible – MAPL
ut_are_convertible Interface
61 statements
Source File
interface
Called by
public function ut_are_convertible(unit1, unit2) bind(c, name='ut_are_convertible')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: unit1
type(c_ptr), intent(in), value :: unit2
Return Value integer(kind=c_int)
Call graph
are_convertible_udunit calls ut_are_convertible
are_convertible calls are_convertible_udunit, are_convertible_str
are_convertible_str calls are_convertible_udunit
can_connect_units calls are_convertible
construct_converter calls are_convertible
test_are_convertible calls are_convertible
test_are_not_convertible calls are_convertible
converter calls construct_converter
can_connect_to calls can_connect_units