VirtualConnectionPtVector – MAPL
VirtualConnectionPtVector Interface
8 statements
Source File
public interface VirtualConnectionPtVector
Calls
Module Procedures
private function vector_new_vector_empty() result(v)
Arguments
None
Return Value type(VirtualConnectionPtVector)
private function vector_new_vector_fill_size_kind(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer(kind=GFTL_SIZE_KIND), intent(in) :: n
type(VirtualConnectionPt), intent(in), optional :: value
Return Value type(VirtualConnectionPtVector)
private function vector_new_vector_fill_default(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(VirtualConnectionPt), intent(in), optional :: value
Return Value type(VirtualConnectionPtVector)
private function vector_new_vector_range(first, last) result(v)
Arguments
Type Intent Optional Attributes Name
type(VirtualConnectionPtVectorIterator), intent(in) :: first
type(VirtualConnectionPtVectorIterator), intent(in) :: last
Return Value type(VirtualConnectionPtVector)
private function vector_new_vector_copy(x) result(v)
Arguments
Type Intent Optional Attributes Name
type(VirtualConnectionPtVector) :: x
Return Value type(VirtualConnectionPtVector)
private function vector_new_vector_initializer_list(il) result(v)
Arguments
Type Intent Optional Attributes Name
type(VirtualConnectionPt), intent(in), dimension(:) :: il
Return Value type(VirtualConnectionPtVector)
Call graph
virtualconnectionptvector calls vector_new_vector_copy, vector_new_vector_empty, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_initializer_list, vector_new_vector_range
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_initializer_list calls resize
vector_new_vector_range calls of, vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve