checkpoint_tester – MAPL
checkpoint_tester Program
93 statements
Source File
Uses
iso_fortran_env
ESMF
NetCDF
mapl_restart_support_mod
mpi
Calls
Variables
Type Attributes Name Initial
integer(kind=INT64) :: count_rate
integer(kind=INT64) :: end_app
integer(kind=INT64) :: end_time
integer(kind=INT64) :: start_app
integer(kind=INT64) :: start_read
integer :: comm_size
integer :: i
integer :: rank
integer :: reader_rank
integer :: reader_size
integer :: status
real(kind=REAL64), allocatable :: all_proc_throughput(:)
real(kind=REAL64) :: application_time
real(kind=REAL64) :: average_time
real(kind=REAL64) :: average_volume
real(kind=REAL64) :: close_time
real(kind=REAL64) :: create_time
real(kind=REAL64) :: data_volume
real(kind=REAL64) :: mean_fs_throughput
real(kind=REAL64) :: mean_throughput
real(kind=REAL64) :: read_2d_time
real(kind=REAL64) :: read_3d_time
real(kind=REAL64) :: read_time
real(kind=REAL64) :: std_fs_throughput
real(kind=REAL64) :: std_throughput
real(kind=REAL64) :: time_sum
real(kind=REAL64), allocatable :: total_throughput(:)
type(test_support) :: support
Call graph
checkpoint_tester calls ESMF_Initialize, mpi_allreduce, mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, close_file, create_arrays, create_communicators, open_file, read_file, reset, set_parameters
close_file calls mpi_barrier, nf90_close
create_arrays calls mpi_comm_rank, mpi_comm_size, allocate_n_arrays, compute_decomposition
create_communicators calls mpi_barrier, mpi_comm_rank, mpi_comm_split
open_file calls mpi_barrier, mpi_comm_rank, mpi_info_create, mpi_info_set, nf90_open
read_file calls mpi_barrier, read_level, read_variable
set_parameters calls mpi_comm_size, ESMF_ConfigCreate, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigLoadFile, mpi_abort
allocate_n_arrays calls mpi_comm_rank
read_level calls mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_get_var, nf90_inq_varid
read_variable calls mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_get_var, nf90_inq_varid