geos – MAPL
geos Program
69 statements
Source File
Uses
mapl3
ESMF
Calls
Variables
Type Attributes Name Initial
integer :: status
type(ESMF_Config) :: config
Subroutines
subroutine finalize(config, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
integer, intent(out), optional :: rc
subroutine initialize(config, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(out) :: config
integer, intent(out), optional :: rc
subroutine run_geos(config, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
integer, intent(out), optional :: rc
Source Code
program geos
   use mapl3
   use esmf
   implicit none
   integer :: status
   type(ESMF_Config) :: config
   call initialize(config=config, _RC)
   call run_geos(config, _RC)
   call finalize(config=config, _RC)
contains
#undef I_AM_MAIN
#include "MAPL_Generic.h"
   subroutine initialize(config, rc)
      type(ESMF_Config), intent(out) :: config
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_HConfig) :: hconfig
      type(ESMF_HConfig), allocatable :: mapl_hconfig
      logical :: has_mapl_section
      call ESMF_Initialize(configFilenameFromArgNum=1, configKey=['esmf'], config=config, _RC)
      call ESMF_ConfigGet(config, hconfig=hconfig, _RC)
      has_mapl_section = ESMF_HConfigIsDefined(hconfig, keystring='mapl', _RC)
      if (has_mapl_section) then
         mapl_hconfig = ESMF_HConfigCreateAt(hconfig, keystring='mapl', _RC)
      end if
      call MAPL_Initialize(mapl_hconfig=mapl_hconfig, _RC)
      _RETURN(_SUCCESS)
   end subroutine initialize
   subroutine run_geos(config, rc)
      type(ESMF_Config), intent(inout) :: config
      integer, optional, intent(out) :: rc
      type(ESMF_HConfig) :: cap_hconfig, hconfig
      logical :: has_cap_hconfig
      integer :: status
      call ESMF_ConfigGet(config, hconfig=hconfig, _RC)
      has_cap_hconfig = ESMF_HConfigIsDefined(hconfig, keystring='cap', _RC)
      _ASSERT(has_cap_hconfig, 'No cap section found in configuration file')
      cap_hconfig = ESMF_HConfigCreateAt(hconfig, keystring='cap', _RC)
      call MAPL_run_driver(cap_hconfig, _RC)
      call ESMF_HConfigDestroy(cap_hconfig, _RC)
      _RETURN(_SUCCESS)
   end subroutine run_geos
   subroutine finalize(config, rc)
      type(ESMF_Config), intent(inout) :: config
      integer, optional, intent(out) :: rc
      integer :: status
      call MAPL_Finalize(_RC)
      call ESMF_ConfigDestroy(config, _RC)
      call ESMF_Finalize(_RC)
      _RETURN(_SUCCESS)
   end subroutine finalize
end program geos
Call graph
geos calls finalize, initialize, mapl_abort, mapl_verify, run_geos
finalize calls mapl_verify, ESMF_ConfigDestroy, ESMF_Finalize, mapl_finalize, mapl_return
initialize calls mapl_verify, ESMF_ConfigGet, ESMF_Initialize, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_initialize, mapl_return
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
run_geos calls mapl_verify, ESMF_ConfigGet, ESMF_HConfigDestroy, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_run_driver