Test_VerticalLinearMap – MAPL
Test_VerticalLinearMap Program
28 statements
Source File
Uses
iso_fortran_env
mapl3g_VerticalLinearMap
mapl3g_CSR_SparseMatrix
mapl_ErrorHandling
Calls
Variables
Type Attributes Name Initial
integer :: status
real(kind=REAL32), allocatable :: dst(:)
real(kind=REAL32), allocatable :: fin(:)
real(kind=REAL32), allocatable :: src(:)
type(CSR_SparseMatrix_sp) :: matrix
Source Code
program Test_VerticalLinearMap
   use mapl_ErrorHandling
   use mapl3g_CSR_SparseMatrix, only: SparseMatrix_sp => CSR_SparseMatrix_sp, matmul
   use mapl3g_VerticalLinearMap, only: compute_linear_map_fixedlevels_to_fixedlevels
   ! use mapl3g_VerticalLinearMap, only: apply_linear_map
   use, intrinsic :: iso_fortran_env, only: REAL32
   implicit none
   real(REAL32), allocatable :: src(:), dst(:), fin(:)
   ! real(REAL32), allocatable :: matrix(:, :)
   type(SparseMatrix_sp) :: matrix
   integer :: status
   src = [30., 20., 10.]
   dst = [20., 10.]
   call compute_linear_map_fixedlevels_to_fixedlevels(src, dst, matrix, _RC)
   fin = [7., 8., 3.]
   print *, "Expected: [8.0, 3.0]", ", found: ", matmul(matrix, fin)
   src = [30., 20., 10.]
   dst = [25., 15.]
   call compute_linear_map_fixedlevels_to_fixedlevels(src, dst, matrix, _RC)
   fin = [7., 8., 3.]
   print *, "Expected: [7.5, 5.5]", ", found: ", matmul(matrix, fin)
   src = [30., 20., 10.]
   dst = [28., 11.]
   call compute_linear_map_fixedlevels_to_fixedlevels(src, dst, matrix, _RC)
   fin = [7., 8., 3.]
   print *, "Expected: [7.2, 3.5]", ", found: ", matmul(matrix, fin)
end program Test_VerticalLinearMap
Call graph
test_verticallinearmap calls compute_linear_map_fixedlevels_to_fixedlevels, mapl_abort, mapl_verify
compute_linear_map_fixedlevels_to_fixedlevels calls add_row, mapl_assert, mapl_return
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, at, insert