':chart_with_upwards_trend: MAPL3':
  - base-branch: 'release/MAPL-v3'

':wrench: Github Actions':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'

':astonished: Non 0 Diff':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.F90'
      - '**/*.F'
      - '**/*.f90'
      - '**/*.f'
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.py'
      - '**/CMakeLists.txt'
      - '**/*.cmake'
