# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - :hourglass: Long Term
# Label to use when marking an issue as stale
staleLabel: :snowflake: Stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. If there are no updates within 7 days, it will be closed.
  You can add the "Long Term" label to prevent the Stale bot from closing
  this issue.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: Closing due to inactivity

