# Top level

include = ["*.f90", "*.F90"]

[check]
line-length = 120
select = ["ALL"]
ignore = [
    "S102", # incorrect space before comment
    "S091", # file extension should be .f90 or .F90
    "C021", # real literal 360. missing kind suffix
    "C022", # real has implicit kind
    "C121", # 'use' statement missing 'only' clause
]
fix = false
unsafe-fixes = false
preview = false
