# Do not warn for links which redirect to another URL
do-not-warn-for-redirect-to = ["*"]

# Ignore files that are not documentation
# Note does not seem to work at the moment, see
# https://github.com/becheran/mlc/issues/158
ignore-path = ["CHANGELOG.md","./CHANGELOG.md"]
