# Markup Link Checker configuration
# See https://github.com/becheran/mlc for documentation

# Do not warn for links which redirect to another URL
do-not-warn-for-redirect-to = ["*"]

# Ignore files that are not documentation
ignore-path = ["CHANGELOG.md","./CHANGELOG.md"]
