CapDriver_Main – MAPL
CapDriver_Main Program
16 statements
Source File
Uses
mpi
MAPL
ExtDataUtRoot_GridCompMod
Calls
Variables
Type Attributes Name Initial
character(len=*), parameter :: Iam = "CapDriver_Main"
integer :: status
type(MAPL_Cap) :: cap
type(MAPL_CapOptions) :: cap_options
type(MAPL_FargparseCLI) :: cli
Source Code
program CapDriver_Main
   use MPI
   use MAPL
   use ExtDataUtRoot_GridCompMod, only:  ROOT_SetServices => SetServices
   implicit none
   character(len=*), parameter :: Iam="CapDriver_Main"
   type (MAPL_Cap) :: cap
   type (MAPL_FargparseCLI) :: cli
   type (MAPL_CapOptions) :: cap_options
   integer :: status
   cli = MAPL_FargparseCLI()
   cap_options = MAPL_CapOptions(cli)
   cap = MAPL_Cap('Root', ROOT_SetServices, cap_options = cap_options)
   call cap%run(_RC)
end program CapDriver_Main
Call graph
capdriver_main calls mapl_fargparsecli, mapl_abort, mapl_verify, run
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
run calls mapl_verify, finalize_mpi, mapl_return, run_ensemble
finalize_mpi calls mapl_return, mpi_finalize, mapl_finalize
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
run_ensemble calls mapl_verify, mapl_return, create_member_subcommunicator, finalize_io_clients_servers, free_sub_comm, initialize_io_clients_servers, run_member