driver_GetHorzIJIndex – MAPL
driver_GetHorzIJIndex Program
15 statements
Source File
Uses
GridComp
MAPL
Calls
Variables
Type Attributes Name Initial
integer :: status
type(MAPL_Cap) :: cap
type(MAPL_CapOptions) :: cap_options
type(MAPL_FargparseCLI) :: cli
Source Code
program driver_GetHorzIJIndex
   use MAPL
   use GridComp, only: SetServices
   implicit none
   type (MAPL_Cap) :: cap
   type (MAPL_FargparseCLI) :: cli
   type (MAPL_CapOptions) :: cap_options
   integer :: status
   cli = MAPL_FargparseCLI()
   cap_options = MAPL_CapOptions(cli)
   cap = MAPL_Cap('GetHorzIJIndex', SetServices, cap_options = cap_options, _RC)
   call cap%run(_RC)
end program driver_GetHorzIJIndex
Call graph
driver_gethorzijindex calls mapl_fargparsecli, mapl_abort, mapl_verify, run
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
run calls mapl_verify, finalize_mpi, mapl_return, run_ensemble
finalize_mpi calls mapl_return, mpi_finalize, mapl_finalize
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
run_ensemble calls mapl_verify, mapl_return, create_member_subcommunicator, finalize_io_clients_servers, free_sub_comm, initialize_io_clients_servers, run_member