Example_Driver – MAPL
Example_Driver Program
14 statements
Source File
Uses
MAPL
mpi
Calls
Contents
Variables
status cap cap_options cli
Source Code
Example_Driver
Variables
Type Attributes Name Initial
integer :: status
type(MAPL_Cap) :: cap
type(MAPL_CapOptions) :: cap_options
type(MAPL_FlapCLI) :: cli
Source Code
program Example_Driver
   use MPI
   use MAPL
   implicit none
   type (MAPL_Cap) :: cap
   type (MAPL_FlapCLI) :: cli
   type (MAPL_CapOptions) :: cap_options
   integer :: status
   cli = MAPL_FlapCLI(description = 'GEOS AGCM', &
                                     authors     = 'GMAO')
   cap_options = MAPL_CapOptions(cli)
   cap = MAPL_Cap('example', cap_options = cap_options)
   call cap%run(_RC)
end program Example_Driver
Call graph
example_driver calls mapl_capoptions, mapl_verify, mapl_abort
mapl_capoptions calls old_capoptions_from_flap
mapl_verify calls mapl_throw_exception
mapl_abort calls mpi_abort
old_capoptions_from_flap calls mapl_verify, mapl_return, mapl_assert
mapl_throw_exception calls initialize
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert calls mapl_assert_condition, mapl_assert_return_code