ExtData_Driver – MAPL
ExtData_Driver Program
21 statements
Source File
Uses
ExtDataDriverMod
ExtDataUtRoot_GridCompMod
ESMF
MAPL
mpi
ExtData_DriverGridCompMod
Calls
Contents
Variables
Iam status Driver cap_options cli
Source Code
ExtData_Driver
Variables
Type Attributes Name Initial
character(len=*), parameter :: Iam = "ExtData_Driver"
integer :: status
type(ExtDataDriver) :: Driver
type(MAPL_CapOptions) :: cap_options
type(MAPL_FlapCLI) :: cli
Source Code
program ExtData_Driver
  use MPI
  use ESMF
  use ExtData_DriverGridCompMod, only: ExtData_DriverGridComp, new_ExtData_DriverGridComp
  use ExtDataUtRoot_GridCompMod, only:  ROOT_SetServices => SetServices
  use ExtDataDriverMod
  use MAPL
  implicit none
  integer :: status
  character(len=*), parameter :: Iam="ExtData_Driver"
  type(ExtDataDriver) :: Driver
  type (MAPL_CapOptions) :: cap_options
  type (MAPL_FlapCLI) :: cli
  cli = MAPL_FlapCLI(description='extdata driver',authors='gmao')
  cap_options=MAPL_CapOptions(cli)
  driver = ExtDataDriver('ExtDataApp',Root_SetServices,cap_options=cap_options,_RC)
  call driver%run(_RC)
  stop
end program ExtData_Driver
Call graph
extdata_driver calls mapl_capoptions, mapl_verify, extdatadriver, mapl_abort
mapl_capoptions calls old_capoptions_from_flap
mapl_verify calls mapl_throw_exception
extdatadriver calls newextdatadriver
mapl_abort calls mpi_abort
old_capoptions_from_flap calls mapl_verify, mapl_assert, mapl_return
newextdatadriver calls mapl_capoptions, mapl_verify, mapl_initialize, mapl_return
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_initialize calls mapl_verify, mapl_return, initialize_pflogger, start_global_time_profiler, initialize_profiler
mapl_return calls mapl_throw_exception, get_error_message