test – MAPL
test Program
102 statements
Source File
Uses
ESMF_CFIOMod
Calls
Variables
Type Attributes Name Initial
character(len=20) :: fileName
integer :: curTime
integer :: date
integer :: fmode
integer :: hhmmss(tm) = (/0, 30000, 60000, 90000, 120000, 150000, 180000, 210000/)
integer :: i
integer, parameter :: im = 540
integer :: im1
integer, parameter :: jm = 361
integer :: jm1
integer, parameter :: km = 72
integer :: km1
integer :: rc
integer :: t
integer :: timeInc
integer, parameter :: tm = 8
logical :: passed = .true.
logical :: twoD
real :: dlat
real :: dlon
real :: dsig
real :: lat(jm)
real :: lev(km)
real :: lon(im)
real :: ps(im,jm)
real :: q(im,jm,km)
real :: sig
real :: tmpu(im,jm,km)
real :: ts(im,jm)
real :: u(im,jm,km)
real :: v(im,jm,km)
type(ESMF_CFIO) :: cfio
type(ESMF_CFIOGrid), pointer :: grid
type(ESMF_CFIOVarInfo), pointer :: vars(:)
Call graph
test calls esmf_cfiocreate, esmf_cfioget, esmf_cfiogridcreate, esmf_cfiogridget, esmf_cfiogridset, esmf_cfioset, esmf_cfiovarinfocreate, esmf_cfiovarinfoset, esmf_cfiovarwrite, esmf_cfiofileclose, esmf_cfiofilecreate
esmf_cfiovarwrite calls esmf_cfiovarwrite1d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite3d_
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
esmf_cfiofilecreate calls ESMF_UtilStringUpperCase, esmf_cfiosdffilecreate, esmf_cfioset
esmf_cfioget calls err
esmf_cfiosdffileclose calls cfio_close
esmf_cfiosdffilecreate calls esmf_cfioget, esmf_cfioset, cfio_create_, cfio_putcharatt, cfio_putintatt, cfio_putrealatt, err, getlist, strtemplate_
esmf_cfioset calls addlist, err, strtoint
esmf_cfiovarwrite1d_ calls esmf_cfioget, esmf_cfiosdfvarwrite, strtoint
esmf_cfiovarwrite2d_ calls esmf_cfioget, esmf_cfiosdfvarwrite, strtoint
esmf_cfiovarwrite3d_ calls esmf_cfioget, esmf_cfiosdfvarwrite, strtoint