test – MAPL
test Program
88 statements
Source File
Uses
ESMF_CFIOGridMod
ESMF_CFIOGrADSMOD
ESMF_CFIOFileMod
ESMF_CFIOSdfMod
ESMF_CFIOVarInfoMod
ESMF_CFIOMod
Calls
Contents
Variables
inFile source standardName title vName argc begTime curTime date fid fmode im jm k km km_out nSteps rc t timeInc isGrADS new_file passed twoD ak amiss bk lat lev lev_out lon range tmpu cfio cfio_out ggrid grid vars
Variables
Type Attributes Name Initial
character(len=256) :: inFile
character(len=256) :: source
character(len=256) :: standardName
character(len=256) :: title
character(len=256) :: vName
integer :: argc
integer :: begTime
integer :: curTime
integer :: date
integer :: fid
integer :: fmode = 1
integer :: im
integer :: jm
integer :: k
integer :: km
integer :: km_out
integer :: nSteps
integer :: rc
integer :: t
integer :: timeInc
logical :: isGrADS = .false.
logical :: new_file
logical :: passed = .true.
logical :: twoD
real :: ak(19) = (/291.70, 792.92, 2155.39, 4918.34, 8314.25, 7993.08, 7577.38, 7057.52, 6429.63, 5698.38, 4879.13, 3998.95, 3096.31, 2219.02, 1420.39, 754.13, 268.38, 0.0000, 0.0000/)
real :: amiss
real :: bk(19) = (/0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0380541, 0.0873088, 0.1489307, 0.2232996, 0.3099406, 0.4070096, 0.5112977, 0.6182465, 0.7221927, 0.8168173, 0.8957590, 0.9533137, 0.9851122, 1.0/)
real, pointer :: lat(:)
real, pointer :: lev(:)
real, pointer :: lev_out(:)
real, pointer :: lon(:)
real :: range(2) = (/-1.E10, 1.E10/)
real, pointer :: tmpu(:,:,:)
type(ESMF_CFIO) :: cfio
type(ESMF_CFIO) :: cfio_out
type(ESMF_CFIOGrid), pointer :: ggrid
type(ESMF_CFIOGrid) :: grid
type(ESMF_CFIOVarInfo), pointer :: vars(:)
Call graph
test calls esmf_cfiogridget, esmf_cfiovarwrite, esmf_cfiovarread, esmf_cfiocreate, esmf_cfioset, esmf_cfiofileclose, esmf_cfiofileopen, esmf_cfioget, esmf_cfiovarinfocreate, esmf_cfiogridcreate, esmf_cfiovarinfoget, esmf_cfiofilecreate, esmf_cfiogridset
esmf_cfiovarwrite calls esmf_cfiovarwrite3d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite1d_
esmf_cfiovarread calls esmf_cfiovarread1d_, esmf_cfiovarread3d_, esmf_cfiovarread2d_
esmf_cfioset calls strtoint, err, addlist
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
esmf_cfiofileopen calls esmf_cfioset, esmf_cfioget, esmf_cfiosdffileopen
esmf_cfioget calls err
esmf_cfiovarinfocreate calls esmf_cfiogridcreate
esmf_cfiovarinfoget calls err
esmf_cfiofilecreate calls esmf_cfioset, esmf_utilstringuppercase, esmf_cfiosdffilecreate