test – MAPL
test Program
109 statements
Source File
Uses
ESMF_CFIOGridMod
ESMF_CFIOFileMod
ESMF_CFIOSdfMod
ESMF_CFIOVarInfoMod
ESMF_CFIOMod
Calls
Contents
Variables
fileName curTime date fmode hhmmss i im im1 jm jm1 km km1 rc t timeInc passed twoD dlat dlon dsig kappa lat lev lon ps range sig tmpu ts u v cfio grid vars
Variables
Type Attributes Name Initial
character(len=20) :: fileName
integer :: curTime
integer :: date
integer :: fmode
integer :: hhmmss(2) = (/0, 60000/)
integer :: i
integer, parameter :: im = 72
integer :: im1
integer, parameter :: jm = 46
integer :: jm1
integer, parameter :: km = 18
integer :: km1
integer :: rc
integer :: t
integer :: timeInc
logical :: passed = .true.
logical :: twoD
real :: dlat
real :: dlon
real :: dsig
real :: kappa = 0.28571428571428575
real :: lat(jm)
real :: lev(km)
real :: lon(im)
real, pointer :: ps(:,:,:)
real :: range(2) = (/-1.E10, 1.E10/)
real :: sig
real, pointer :: tmpu(:,:,:)
real, pointer :: ts(:,:,:)
real, pointer :: u(:,:,:)
real, pointer :: v(:,:,:)
type(ESMF_CFIO) :: cfio
type(ESMF_CFIOGrid), pointer :: grid
type(ESMF_CFIOVarInfo), pointer :: vars(:)
Call graph
test calls esmf_cfiovarwrite, esmf_cfiofileclose, esmf_cfiovarinfocreate, esmf_cfiogridset, esmf_cfiogridcreate, esmf_cfiovarinfoset, esmf_cfiogridget, esmf_cfiocreate, esmf_cfioset, esmf_cfioget, esmf_cfiofilecreate
esmf_cfiovarwrite calls esmf_cfiovarwrite3d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite1d_
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
esmf_cfiovarinfocreate calls esmf_cfiogridcreate
esmf_cfiovarinfoset calls err, addlist
esmf_cfioset calls err, addlist, strtoint
esmf_cfioget calls err
esmf_cfiofilecreate calls esmf_cfioset, esmf_utilstringuppercase, esmf_cfiosdffilecreate
esmf_cfiovarwrite3d_ calls esmf_cfioget, strtoint, esmf_cfiosdfvarwrite
esmf_cfiosdffileclose calls cfio_close
esmf_cfiovarwrite2d_ calls esmf_cfioget, strtoint, esmf_cfiosdfvarwrite
esmf_cfiovarwrite1d_ calls esmf_cfioget, strtoint, esmf_cfiosdfvarwrite
esmf_cfiosdffilecreate calls esmf_cfioset, esmf_cfioget, err, cfio_putcharatt, cfio_create_, strtemplate_, getlist, cfio_putintatt, cfio_putrealatt