test – MAPL
test Program
128 statements
Source File
Uses
ESMF_CFIOGridMod
ESMF_CFIOFileMod
ESMF_CFIOSdfMod
ESMF_CFIOVarInfoMod
ESMF_CFIOMod
Calls
Contents
Variables
fileName nameLat str curTime date fmode hhmmss i ig im jm km rc t timeInc passed twoD ak bk dlat dlon kappa lat lat1 lat2 lev lon lon1 lon2 ps range tmpu ts u v cfio grids vars
Variables
Type Attributes Name Initial
character(len=20) :: fileName
character(len=50) :: nameLat
character :: str
integer :: curTime
integer :: date
integer :: fmode
integer :: hhmmss(2) = (/0, 60000/)
integer :: i
integer :: ig = 2
integer :: im = 72
integer :: jm = 46
integer :: km = 18
integer :: rc
integer :: t
integer :: timeInc
logical :: passed = .true.
logical :: twoD
real :: ak(19) = (/291.70, 792.92, 2155.39, 4918.34, 8314.25, 7993.08, 7577.38, 7057.52, 6429.63, 5698.38, 4879.13, 3998.95, 3096.31, 2219.02, 1420.39, 754.13, 268.38, 0.0000, 0.0000/)
real :: bk(19) = (/0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0380541, 0.0873088, 0.1489307, 0.2232996, 0.3099406, 0.4070096, 0.5112977, 0.6182465, 0.7221927, 0.8168173, 0.8957590, 0.9533137, 0.9851122, 1.0/)
real :: dlat
real :: dlon
real :: kappa = 0.28571428571428575
real :: lat(46)
real :: lat1(46)
real :: lat2(46)
real :: lev(18) = (/100.5145, 118.2502, 139.115, 163.6615, 192.541, 226.5135, 266.4789, 313.4988, 368.8161, 433.8927, 510.4555, 600.5238, 696.793, 787.7, 867.1572, 929.6454, 970.5525, 992.555/)
real :: lon(72)
real :: lon1(72)
real :: lon2(72)
real, pointer :: ps(:,:,:)
real :: range(2) = (/-1.E10, 1.E10/)
real, pointer :: tmpu(:,:,:)
real, pointer :: ts(:,:,:)
real, pointer :: u(:,:,:)
real, pointer :: v(:,:,:)
type(ESMF_CFIO) :: cfio
type(ESMF_CFIOGrid), pointer :: grids(:)
type(ESMF_CFIOVarInfo), pointer :: vars(:)
Call graph
test calls esmf_cfiogridcreate, esmf_cfiovarinfocreate, esmf_cfiogridset, esmf_cfiocreate, esmf_cfiovarinfoset, esmf_cfioset, esmf_cfioget, esmf_cfiofilecreate, esmf_cfiovarwrite, esmf_cfiofileclose
esmf_cfiovarinfocreate calls esmf_cfiogridcreate
esmf_cfiovarinfoset calls err, addlist
esmf_cfioset calls err, addlist, strtoint
esmf_cfioget calls err
esmf_cfiofilecreate calls esmf_cfioset, esmf_cfiosdffilecreate, esmf_utilstringuppercase
esmf_cfiovarwrite calls esmf_cfiovarwrite3d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite1d_
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
esmf_cfiosdffilecreate calls esmf_cfioset, esmf_cfioget, err, cfio_create_, cfio_putcharatt, strtemplate_, cfio_putintatt, getlist, cfio_putrealatt
esmf_cfiovarwrite3d_ calls esmf_cfioget, strtoint, esmf_cfiosdfvarwrite
esmf_cfiovarwrite2d_ calls esmf_cfioget, strtoint, esmf_cfiosdfvarwrite
esmf_cfiovarwrite1d_ calls esmf_cfioget, strtoint, esmf_cfiosdfvarwrite
esmf_cfiosdffileclose calls cfio_close