CFIO_PutCharAtt – MAPL
CFIO_PutCharAtt Subroutine
17 statements
Source File
public subroutine CFIO_PutCharAtt(fid, name, count, buf, rc)
CFIO_PutCharAtt – Write a user-defined character attribute
This routine allows the user to define a character (string) attribute in an open CFIO file.
History
1998.07.30 Lucchesi Initial interface design.
1998.07.30 Lucchesi Initial coding.
1998.09.24 Lucchesi Changed error handling.
Arguments
Type Intent Optional Attributes Name
integer :: fid
File handle
character(len=*) :: name
Name of attribute
integer :: count
Number of characters to write
character(len=MLEN) :: buf
Buffer containing string
integer :: rc
Error return code: rc = 0 all is well
NetCDF Errors
rc = -36 error from NF90_PUT_ATT (global attribute) rc = -55 error from NF90_REDEF (enter define mode) rc = -56 error from NF90_ENDDEF (exit define mode)
Calls
Called by
Contents
Source Code
CFIO_PutCharAtt
Source Code
      subroutine CFIO_PutCharAtt ( fid, name, count, buf, rc )
!
! !USES:
!
      Implicit NONE
!
! !INPUT PARAMETERS:
!
      integer        fid        !! File handle
      character(len=*)  name       !! Name of attribute
      integer        count      !! Number of characters to write
      character(len=MLEN) :: buf !! Buffer containing string
!
! !OUTPUT PARAMETERS:
!
      integer     rc     !! Error return code:
                         !!   rc = 0    all is well
                         !!
                         !!  NetCDF Errors
                         !!  -------------
                         !!   rc = -36  error from NF90_PUT_ATT (global attribute)
                         !!   rc = -55  error from NF90_REDEF (enter define mode)
                         !!   rc = -56  error from NF90_ENDDEF (exit define mode)
!
!-------------------------------------------------------------------------
      _UNUSED_DUMMY(count)
      rc = NF90_REDEF ( fid )
      if (err("PutCharAtt: could not enter define mode",rc,-55) .NE. 0) &
         return
      rc = NF90_PUT_ATT ( fid, NF90_GLOBAL, name, buf )
      if (err("PutCharAtt: error writing attribute",rc,-36) .NE. 0) &
         return
      rc = NF90_ENDDEF(fid)
      if (err("PutCharAtt: could not exit define mode",rc,-56) .NE. 0) &
         return
      rc = 0
      return
      end subroutine CFIO_PutCharAtt
Call graph
cfio_putcharatt calls nf90_enddef, nf90_put_att, nf90_redef, err
esmf_cfiosdffilecreate calls cfio_putcharatt
esmf_cfiofilecreate calls esmf_cfiosdffilecreate
mapl_cfiocreatewrite calls esmf_cfiofilecreate
test calls esmf_cfiofilecreate