compute_nhmsf – MAPL
compute_nhmsf Function
5 statements
Source File
function compute_nhmsf(nsec) result(nhmsf)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nsec
Return Value integer
Called by
Contents
Source Code
compute_nhmsf
Source Code
   function compute_nhmsf (nsec) result(nhmsf)
      integer :: nhmsf
      integer, intent(in) :: nsec
      nhmsf =  nsec/3600*10000 + mod(nsec,3600)/60*100 + mod(nsec,60)
   end function compute_nhmsf
Call graph
tick calls compute_nhmsf
time_ave calls compute_nhmsf, tick