construct_date_fields_null – MAPL
construct_date_fields_null Function
4 statements
Source File
public pure function construct_date_fields_null() result(fields)
Arguments
None
Return Value type(date_fields)
Called by
Contents
Source Code
construct_date_fields_null
Source Code
   pure function construct_date_fields_null() result(fields)
      type(date_fields) :: fields
      fields%is_valid_ = .FALSE.
   end function construct_date_fields_null
Call graph
date_fields calls construct_date_fields_null, construct_date_fields_string
parse_date calls date_fields
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields
construct_date_fields_string calls parse_date
test_parse_date calls parse_date