construct_date_fields_string – MAPL
construct_date_fields_string Function
6 statements
Source File
public pure function construct_date_fields_string(date_string, delimiter) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: date_string
character(len=*), intent(in) :: delimiter
Return Value type(date_fields)
Calls
Called by
Contents
Source Code
construct_date_fields_string
Source Code
   pure function construct_date_fields_string(date_string, delimiter) result(fields)
      character(len=*), intent(in) :: date_string
      character(len=*), intent(in) :: delimiter
      type(date_fields) :: fields
      fields = parse_date(date_string, delimiter)
   end function construct_date_fields_string
Call graph
construct_date_fields_string calls parse_date
parse_date calls date_fields, read_whole_number, undelimit
date_fields calls construct_date_fields_string, construct_date_fields_default, construct_date_fields_null
read_whole_number calls read_whole_number_indexed
construct_date_fields_default calls is_valid_date
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields
test_parse_date calls parse_date