construct_time_fields_null – MAPL
construct_time_fields_null Function
4 statements
Source File
public pure function construct_time_fields_null() result(fields)
Arguments
None
Return Value type(time_fields)
Called by
Contents
Source Code
construct_time_fields_null
Source Code
   pure function construct_time_fields_null() result(fields)
      type(time_fields) :: fields
      fields%is_valid_ = .FALSE.
   end function construct_time_fields_null
Call graph
time_fields calls construct_time_fields_null, construct_time_fields_string
parse_time calls time_fields
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_is_valid_time calls time_fields
construct_time_fields_string calls parse_time
test_parse_time calls parse_time