construct_time_fields_default – MAPL
construct_time_fields_default Function
14 statements
Source File
public pure function construct_time_fields_default(hour, minute, second, millisecond, timezone_offset) result(fields)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: hour
integer, intent(in) :: minute
integer, intent(in) :: second
integer, intent(in) :: millisecond
integer, intent(in) :: timezone_offset
Return Value type(time_fields)
Calls
Called by
Contents
Source Code
construct_time_fields_default
Source Code
   pure function construct_time_fields_default(hour, minute, second, millisecond, &
      timezone_offset) result(fields)
      integer, intent(in) :: hour
      integer, intent(in) :: minute
      integer, intent(in) :: second
      integer, intent(in) :: millisecond
      integer, intent(in) :: timezone_offset
      type(time_fields) :: fields
      fields%hour_ = hour
      fields%minute_ = minute
      fields%second_ = second
      fields%millisecond_ = millisecond
      fields%timezone_offset_ = timezone_offset
      fields%is_valid_ = is_valid_time(fields)
   end function construct_time_fields_default
Call graph
construct_time_fields_default calls is_valid_time
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
time_fields calls construct_time_fields_default, construct_time_fields_string
parse_time calls time_fields
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_is_valid_time calls time_fields
construct_time_fields_string calls parse_time
test_parse_time calls parse_time