construct_time_fields_string – MAPL
construct_time_fields_string Function
6 statements
Source File
public pure function construct_time_fields_string(time_string, delimiter) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: time_string
character(len=*), intent(in) :: delimiter
Return Value type(time_fields)
Calls
Called by
Contents
Source Code
construct_time_fields_string
Source Code
   pure function construct_time_fields_string(time_string, delimiter) result(fields)
      character(len=*), intent(in) :: time_string
      character(len=*), intent(in) :: delimiter
      type(time_fields) :: fields
      fields = parse_time(time_string, delimiter)
   end function construct_time_fields_string
Call graph
construct_time_fields_string calls parse_time
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
time_fields calls construct_time_fields_string, construct_time_fields_default, construct_time_fields_null
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
construct_time_fields_default calls is_valid_time
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_is_valid_time calls time_fields
test_parse_time calls parse_time