convert_to_integer – MAPL
convert_to_integer Subroutine
8 statements
Source File
public subroutine convert_to_integer(string_in, int_out, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string_in
integer, intent(out) :: int_out
integer, intent(out), optional :: rc
Called by
Contents
Source Code
convert_to_integer
Source Code
   subroutine convert_to_integer(string_in, int_out, rc)
      character(len=*), intent(in) :: string_in
      integer, intent(out) :: int_out
      integer, optional, intent(out) :: rc
      integer :: stat
      read(string_in, '(I16)', iostat=stat) int_out
      if(present(rc)) rc = stat
   end subroutine convert_to_integer
Call graph
convert_netcdf_datetimestring_to_esmf_time calls convert_to_integer
test_convert_to_integer calls convert_to_integer
convert_netcdf_datetime_to_esmf calls convert_netcdf_datetimestring_to_esmf_time
test_convert_netcdf_datetimestring_to_esmf_time calls convert_netcdf_datetimestring_to_esmf_time
test_convert_netcdf_datetime_to_esmf calls convert_netcdf_datetime_to_esmf