convert_to_ISO8601DateTime – MAPL
convert_to_ISO8601DateTime Subroutine
29 statements
Source File
public subroutine convert_to_ISO8601DateTime(datetime_string, iso_string, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: datetime_string
character(len=:), intent(out), allocatable :: iso_string
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_to_ISO8601DateTime
Source Code
   subroutine convert_to_ISO8601DateTime(datetime_string, iso_string, rc)
      character(len=*), intent(in) :: datetime_string
      character(len=:), allocatable, intent(out) :: iso_string
      integer, optional, intent(out) :: rc
      integer, parameter :: YY = 1
      integer, parameter :: MM = 2
      integer, parameter :: DD = 3
      integer, parameter :: HH = 4
      integer, parameter :: M = 5
      integer, parameter :: S = 6
      integer, parameter :: N(2, S) = reshape([1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [2, S])
      integer, parameter :: MIN_LEN = 14
      character(len=*), parameter :: ISO_DD = '-'
      character(len=*), parameter :: ISO_TD = ':'
      character(len=*), parameter :: ISO_DTD = 'T'
      character(len=*), parameter :: ISO_POINT = '.'
      character(len=len(datetime_string)) :: undelimited
      character(len=:), allocatable :: intermediate
      integer :: undelimited_length
      iso_string = datetime_string
      undelimited = adjustl(undelimit_all(datetime_string))
      undelimited_length=len_trim(undelimited)
      _ASSERT(undelimited_length >= MIN_LEN, 'datetime_string is too short: ' // trim(undelimited))
      intermediate = undelimited(N(1,YY):N(2,YY)) // ISO_DD // &
                     undelimited(N(1,MM):N(2,MM)) // ISO_DD // &
                     undelimited(N(1,DD):N(2,DD)) // ISO_DTD // &
                     undelimited(N(1,HH):N(2,HH)) // ISO_TD // &
                     undelimited(N(1,M):N(2,M)) // ISO_TD // &
                     undelimited(N(1,S):N(2,S))
      if(undelimited_length > MIN_LEN) intermediate = intermediate // ISO_POINT // undelimited(MIN_LEN+1:undelimited_length)
      iso_string = intermediate
      _RETURN(_SUCCESS)
   end subroutine convert_to_ISO8601DateTime
Call graph
convert_to_iso8601datetime calls mapl_assert, mapl_return, undelimit_all
mapl_return calls mapl_throw_exception
undelimit_all calls is_digit
test_convert_to_iso8601datetime calls convert_to_iso8601datetime