create_member_subcommunicator – MAPL
create_member_subcommunicator Function
17 statements
Source File
function create_member_subcommunicator(comm, n_members, npes_member, rc) result(subcommunicator)
Uses
MAPL_SimpleCommSplitterMod
create_member_subcommunicator – Create a subcommunicator
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer :: n_members
integer :: npes_member
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function create_member_subcommunicator(comm, n_members, npes_member, rc) result(subcommunicator)
      use MAPL_SimpleCommSplitterMod
      integer, intent(in) :: comm
      integer :: n_members, npes_member
      integer, optional, intent(out) :: rc
      type(SimpleCommSplitter) :: splitter
      type (SplitCommunicator) :: split_comm
      integer :: status
      subcommunicator = MPI_COMM_NULL ! in case of failure
      splitter = SimpleCommSplitter(comm, n_members, npes_member)
      split_comm = splitter%split(rc=status)
      ! _VERIFY(status)
      subcommunicator = split_comm%get_subcommunicator()
      _UNUSED_DUMMY(rc)
   end function create_member_subcommunicator
Call graph
create_member_subcommunicator calls get_subcommunicator, split
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
main calls create_member_subcommunicator