create_grid – MAPL
create_grid Subroutine
35 statements
Source File
public subroutine create_grid(this, grid_name, rc)
Type Bound
regrid_support
Arguments
Type Intent Optional Attributes Name
class(regrid_support) :: this
character(len=*), intent(in) :: grid_name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
create_grid
Source Code
    subroutine create_grid(this,grid_name,rc)
    class(regrid_support) :: this
    character(len=*), intent(in) :: grid_name
    integer, optional, intent(out) :: rc
    type (FileMetaDataUtils) :: metadata
    type (FileMetaData) :: basic_metadata
    character(len=:),allocatable :: lev_name
    integer :: im_world,jm_world,lm_world
    type(NetCDF4_FileFormatter) :: formatter
    character(len=:), allocatable :: filename
    character(len=2) :: dateline,pole
    integer :: status
    type(ESMF_CONFIG) :: cfoutput
    filename = this%filenames%at(1)
    call formatter%open(trim(filename),pFIO_Read,_RC)
    basic_metadata=formatter%read(_RC)
    call metadata%create(basic_metadata,trim(filename))
    call formatter%close(_RC)
    lm_world=0
    lev_name=metadata%get_level_name()
    if (trim(lev_name)/='') then
       lm_world = metadata%get_dimension(lev_name,_RC)
    end if
    call UnpackGridName(Grid_name,im_world,jm_world,dateline,pole)
    cfoutput = create_cf(grid_name,im_world,jm_world,this%nx,this%ny,lm_world,this%cs_stretch_param,this%lon_range,this%lat_range,this%tripolar_file_out,_RC)
    this%new_grid=grid_manager%make_grid(cfoutput,prefix=trim(grid_name)//".",_RC)
    _RETURN(_SUCCESS)
    end subroutine create_grid
Call graph
create_grid calls get_dimension, make_grid, create, create_cf, get_level_name, mapl_return, mapl_verify, unpackgridname
create_cf calls mapl_verify, mapl_assert, mapl_configsetattribute, mapl_configcreate
get_level_name calls mapl_return, begin, get_coordinate_variable, get_variables, is_attribute_present, key, next, get_variable_attribute
mapl_return calls mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_variable_attribute calls mapl_return, mapl_verify, mapl_assert, is_attribute_present, get_attribute, get_value, get_variable, get_file_name
mapl_configcreate calls ESMF_ConfigCreate
get_file_name calls mapl_return
process_command_line calls create_grid
main calls process_command_line
regrid_util calls main