defined – MAPL
defined Function
6 statements
Source File
function defined(q, undef)
Arguments
Type Intent Optional Attributes Name
real :: q
real :: undef
Return Value logical
Called by
Contents
Source Code
defined
Source Code
   function defined ( q,undef )
      implicit none
      logical  defined
      real     q,undef
      defined = q /= undef
   end function defined
Call graph
latlon_zstar calls defined
time_ave calls defined, latlon_zstar