err – MAPL
err Function
12 statements
Source File
public function err(outstring, iret, ec)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: outstring
integer :: iret
integer :: ec
Return Value integer
Called by
Contents
Source Code
err
Source Code
      integer function err ( outstring, iret, ec )
      character(len=*) outstring
      integer ec, iret
      if (iret .EQ. 0) then
        err = iret
      else
        print *,"CFIO_",outstring
        iret = ec
        err = ec
      endif
      return
      end function err
Call graph
cfio_attinquire calls err
cfio_close calls err
cfio_diminquire calls err
cfio_getattnames calls err
cfio_getcharatt calls err
cfio_getintatt calls err
cfio_getmissing calls err
cfio_getrealatt calls err
cfio_getvar calls err
cfio_open calls err
cfio_putcharatt calls err
cfio_putintatt calls err
cfio_putrealatt calls err
cfio_putvar calls err
cfio_sgetvar calls err
cfio_sputvar calls err
esmf_cfioeosfilecreate calls err
esmf_cfioget calls err
esmf_cfiosdffilecreate calls err
esmf_cfiosdffileopen calls err
esmf_cfioset calls err
esmf_cfiovarinfoget calls err
esmf_cfiovarinfoset calls err
getbegdatetime calls err
getdatetimevec calls err