fieldExp – MAPL
fieldExp Subroutine
62 statements
Source File
public subroutine fieldExp(field_out, field_in, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field_out
type(ESMF_Field), intent(inout) :: field_in
integer, intent(out), optional :: rc
Calls
Called by
Call graph
fieldexp calls esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef, mapl_return, mapl_verify
fieldshaveundef calls mapl_return, mapl_verify, ESMF_AttributeGet
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_stateeval calls fieldexp
evaluate_derived_field calls mapl_stateeval, evaluate_mask