FileMetadata_deserialize – MAPL
FileMetadata_deserialize Subroutine
39 statements
Source File
public subroutine FileMetadata_deserialize(buffer, fmd, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(FileMetadata), intent(inout) :: fmd
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine FileMetadata_deserialize(buffer, fmd, rc)
      integer, intent(in) :: buffer(:)
      type (FileMetadata), intent(inout) :: fmd
      integer, optional, intent(out) :: rc
      integer :: status
      fmd = FileMetaData()
      call deserialize(fmd, buffer, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   contains
      subroutine deserialize(this, buffer, rc)
         class (FileMetadata), intent(inout) :: this
         integer, intent(in) :: buffer(:)
         integer, optional, intent(out) :: rc
         integer :: n,length
         integer :: status
         n = 1
         call deserialize_intrinsic(buffer(n:),length)
         _ASSERT(length <= size(buffer), "length does not match")
         length = serialize_buffer_length(length)
         n = n+length
         call StringIntegerMap_deserialize(buffer(n:),this%dimensions, status)
         _VERIFY(status)
         call deserialize_intrinsic(buffer(n:),length)
         n = n + length
         call deserialize_intrinsic(buffer(n:),length)
         call Variable_deserialize(buffer(n:n+length-1),this%global_var, status)
         _VERIFY(status)
         n = n + length
         call StringVariableMap_deserialize(buffer(n:), this%variables, status)
         call deserialize_intrinsic(buffer(n:),length)
         n = n + length
         call StringVector_deserialize(buffer(n:), this%order, status)
         _VERIFY(status)
         _RETURN(_SUCCESS)
      end subroutine deserialize
   end subroutine FileMetadata_deserialize
Call graph
filemetadata_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, stringintegermap_deserialize, stringvariablemap_deserialize, stringvector_deserialize, variable_deserialize
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
stringintegermap_deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return, insert, stringintegermap
stringvariablemap_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, variable_deserialize, insert, coordinatevariable_deserialize
stringvector_deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return, push_back, stringvector
variable_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, stringvector_deserialize, stringattributemap_deserialize, unlimitedentity_deserialize
coordinatevariable_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, variable_deserialize
stringattributemap_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, insert, attribute_deserialize
unlimitedentity_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, get_rank, set
attribute_deserialize calls mapl_return, mapl_verify, unlimitedentity_deserialize
historycollectionvector_deserialize calls filemetadata_deserialize
test_serialize calls filemetadata_deserialize