finalize_global_memory_profiler – MAPL
finalize_global_memory_profiler Subroutine
5 statements
Source File
public subroutine finalize_global_memory_profiler()
Arguments
None
Calls
Source Code
   subroutine finalize_global_memory_profiler()
      type(MemoryProfiler), pointer :: memory_profiler
      memory_profiler => get_global_memory_profiler()
      call memory_profiler%finalize()
   end subroutine finalize_global_memory_profiler
Call graph
finalize_global_memory_profiler calls finalize, get_global_memory_profiler
mapl_verify calls mapl_throw_exception