get_integer_digit_from_string – MAPL
get_integer_digit_from_string Function
9 statements
Source File
public pure function get_integer_digit_from_string(s, i)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
integer, intent(in) :: i
Return Value integer
Calls
Called by
Contents
Source Code
get_integer_digit_from_string
Source Code
   pure integer function get_integer_digit_from_string(s, i)
      character(len=*), intent(in) :: s
      integer, intent(in) :: i
      if((i>0) .and. (i<len(s)+1)) then
         get_integer_digit_from_string = get_integer_digit(s(i:i))
      else
         get_integer_digit_from_string = INVALID
      end if
   end function get_integer_digit_from_string
Call graph
get_integer_digit_from_string calls get_integer_digit
read_whole_number_indexed calls get_integer_digit_from_string
test_get_integer_digit_from_string calls get_integer_digit_from_string
read_whole_number calls read_whole_number_indexed
test_read_whole_number_indexed calls read_whole_number_indexed
construct_iso8601duration calls read_whole_number_indexed
parse_date calls read_whole_number
parse_timezone_offset calls read_whole_number
test_read_whole_number calls read_whole_number
iso8601duration calls construct_iso8601duration
parse_time calls read_whole_number, parse_timezone_offset
construct_iso8601date calls parse_date
convert_iso8601_to_esmf_timeinterval calls iso8601duration
test_parse_date calls parse_date
test_parse_timezone_offset calls parse_timezone_offset
construct_iso8601time calls parse_time
test_parse_time calls parse_time