get_month_ends – MAPL
get_month_ends Function
14 statements
Source File
public pure function get_month_ends(y) result(month_ends)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
Return Value integer, dimension(NUM_MONTHS)
Calls
Called by
Source Code
   pure function get_month_ends(y) result(month_ends)
      integer, intent(in) :: y
      integer, parameter :: NUM_MONTHS = 12
      integer, dimension(NUM_MONTHS) :: month_ends
      ! last day numbers of months for leap years
      integer, dimension(NUM_MONTHS) :: MONTH_END_LEAP
      ! last day numbers of months for regular years
      integer, dimension(NUM_MONTHS) :: MONTH_END
      MONTH_END = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
      MONTH_END_LEAP = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
      if(is_leap_year(y)) then
         month_ends = MONTH_END_LEAP
      else
         month_ends = MONTH_END
      endif
   end function get_month_ends
Call graph
get_month_ends calls is_leap_year
get_month_end calls get_month_ends
test_get_month_ends calls get_month_ends
is_valid_date calls get_month_end
test_get_month_end calls get_month_end
parse_date calls is_valid_date
test_is_valid_date calls is_valid_date
construct_iso8601date calls parse_date
test_parse_date calls parse_date