get_month_end – MAPL
get_month_end Function
7 statements
Source File
public pure function get_month_end(y, m)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
integer, intent(in) :: m
Return Value integer
Calls
Called by
Contents
Source Code
get_month_end
Source Code
   pure integer function get_month_end(y, m)
      integer, intent(in) :: y
      integer, intent(in) :: m
      integer, dimension(:), allocatable :: month_ends
      month_ends = get_month_ends(y)
      get_month_end = month_ends(m)
   end function get_month_end
Call graph
get_month_end calls get_month_ends
get_month_ends calls is_leap_year
is_valid_date calls get_month_end
test_get_month_end calls get_month_end
parse_date calls is_valid_date
test_is_valid_date calls is_valid_date
construct_iso8601date calls parse_date
test_parse_date calls parse_date
iso8601date calls construct_iso8601date