get_global_time_profiler – MAPL
get_global_time_profiler Function
4 statements
Source File
public function get_global_time_profiler() result(time_profiler)
Arguments
None
Return Value type(TimeProfiler), pointer
Called by
Contents
Source Code
get_global_time_profiler
Source Code
   function get_global_time_profiler() result(time_profiler)
      type(TimeProfiler), pointer :: time_profiler
      time_profiler => global_time_profiler
   end function get_global_time_profiler
Call graph
finalize_global_time_profiler calls get_global_time_profiler
initialize_global_time_profiler calls get_global_time_profiler
main calls get_global_time_profiler, mapl_finalize, mapl_initialize, finalize, initialize
mapl_genericfinalize calls get_global_time_profiler
mapl_genericrecord calls get_global_time_profiler
mapl_genericrefresh calls get_global_time_profiler, mapl_genericrefresh
start_global_time_profiler calls get_global_time_profiler
stop_global_time_profiler calls get_global_time_profiler
finalize calls finalize_global_time_profiler
initialize calls initialize_global_time_profiler
mapl_finalize calls stop_global_time_profiler
mapl_initialize calls start_global_time_profiler
comp_testing_driver calls main
initialize_ioserver calls initialize
mapl_internalstatecreate calls initialize
newextdatadriver calls mapl_initialize
run calls finalize, initialize, mapl_finalize
test_accumulate_multi calls finalize
test_accumulate_nested calls finalize
test_accumulate_sub calls finalize
test_simple_report_timer calls finalize
test_simple_report_timer_b calls finalize
test_start_one calls finalize
test_stop_wrong_meter calls finalize
time_ave calls finalize, initialize, mapl_finalize, mapl_initialize
ut_regridding calls finalize, initialize, mapl_finalize, mapl_initialize