get_current_thread – MAPL
get_current_thread Function
3 statements
Source File
public function get_current_thread() result(current_thread)
Arguments
None
Return Value integer
Called by
Source Code
    integer function get_current_thread() result(current_thread)
        current_thread = 0  ! default if OpenMP is not used
        !$ current_thread = omp_get_thread_num() ! get the actual thread id if OpenMP is used
    end function get_current_thread
Call graph
get_grid calls get_current_thread
mapl_friendlyget calls get_internal_state
mapl_genericfinalize calls get_internal_state, get_child_export_state, get_child_gridcomp, get_child_import_state
mapl_genericinitialize calls get_internal_state, get_child_export_state, get_child_gridcomp, get_child_import_state
mapl_genericrecord calls get_internal_state, get_child_export_state, get_child_gridcomp, get_child_import_state
mapl_genericrefresh calls get_internal_state, get_child_export_state, get_child_gridcomp, get_child_import_state, mapl_genericrefresh
mapl_genericstaterestore calls get_internal_state, get_child_export_state, get_child_gridcomp, get_child_import_state, mapl_genericstaterestore
mapl_genericstatesave calls get_internal_state, get_child_export_state, get_child_gridcomp, get_child_import_state, mapl_genericstatesave
mapl_childaddattribtoimportspec calls get_child_gridcomp
mapl_destroystatesave calls get_child_gridcomp
mapl_disablerecord calls get_child_gridcomp
mapl_exchangegridset calls get_child_gridcomp
mapl_gcget calls get_child_gridcomp
mapl_genericrunchildren calls get_child_export_state, get_child_gridcomp, get_child_import_state
mapl_genericruncouplers calls get_child_export_state, get_child_import_state
mapl_genericsetservices calls get_child_gridcomp
mapl_getallexchangegrids calls get_child_gridcomp
mapl_getchildlocstream calls get_child_gridcomp
mapl_importstateget calls get_child_gridcomp, get_child_import_state
mapl_internalesmfstateget calls get_child_gridcomp
mapl_setstatesave calls get_child_gridcomp
mapl_stateprintspeccsv calls get_child_gridcomp
run_component_driver calls get_child_export_state, get_child_gridcomp, get_child_import_state