get_config_attributes – MAPL
get_config_attributes Subroutine
26 statements
Source File
subroutine get_config_attributes(config, comp_name, RUN_DT, restart_file, shared_obj, phase, subset, NX, NY, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
character(len=ESMF_MAXSTR), intent(inout) :: comp_name
integer, intent(inout) :: RUN_DT
character(len=ESMF_MAXSTR), intent(inout) :: restart_file
character(len=ESMF_MAXSTR), intent(inout) :: shared_obj
integer, intent(inout) :: phase
logical, intent(inout) :: subset
integer, intent(inout) :: NX
integer, intent(inout) :: NY
integer, intent(out) :: rc
Calls
Called by
Source Code
  subroutine get_config_attributes(config, comp_name, RUN_DT, restart_file, shared_obj, phase, subset, NX, NY, rc)
    type(ESMF_Config), intent(inout) :: config
    character(len=ESMF_MAXSTR), intent(inout) :: comp_name, shared_obj, restart_file
    integer, intent(inout) :: NX, NY, phase, RUN_DT
    logical, intent(inout) :: subset
    integer, intent(out) :: rc
    integer :: status
    call ESMF_ConfigGetAttribute(config, value=comp_name, label="COMPONENT_TO_RECORD:", _RC)
    call ESMF_ConfigGetAttribute(config, value=RUN_DT, label="RUN_DT:", _RC)
    call ESMF_ConfigGetAttribute(config, value=restart_file, label="RESTART_FILE:", _RC)
    call ESMF_ConfigGetAttribute(config, value=shared_obj, label = "LIBRARY_FILE:", _RC)
    call ESMF_ConfigGetAttribute(config, value=phase, label="PHASE:", default=1, _RC)
    call ESMF_ConfigGetAttribute(config, value=subset, label="SUBSET:", default=.false., _RC)
    call ESMF_ConfigGetAttribute(config, value=NX, label = "NX:", _RC)
    call ESMF_ConfigGetAttribute(config, value=NY, label = "NX:", _RC)
    _RETURN(_SUCCESS)
  end subroutine get_config_attributes
Call graph
get_config_attributes calls ESMF_ConfigGetAttribute, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_component_driver calls get_config_attributes
main calls run_component_driver
comp_testing_driver calls main