get_second – MAPL
get_second Function
4 statements
Source File
public function get_second(self)
Type Bound
ISO8601Time
Arguments
Type Intent Optional Attributes Name
class(ISO8601Time), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_second(self)
      class(ISO8601Time), intent(in) :: self
      get_second = self%second_
   end function get_second
Call graph
convert_iso8601_to_integer_time calls get_second
get_second_datetime calls get_second
test_construct_iso8601time calls get_second
test_iso8601time_getters calls get_second
convert_iso8601_to_esmf_time calls get_second_datetime
test_construct_iso8601datetime calls get_second_datetime
test_convert_iso8601_to_integer_time calls convert_iso8601_to_integer_time
test_iso8601datetime_getters calls get_second_datetime