GridCase_local – MAPL
GridCase_local Function
23 statements
Source File
public function GridCase_local(nx, ny, im_world, jm_world, lon_range, lat_range, default_decomposition, ims, jms, lons, lats) result(param)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: im_world
integer, intent(in) :: jm_world
type(RealMinMax), intent(in) :: lon_range
type(RealMinMax), intent(in) :: lat_range
logical, intent(in) :: default_decomposition
integer, intent(in) :: ims(:)
integer, intent(in) :: jms(:)
real, intent(in) :: lons(:)
real, intent(in) :: lats(:)
Return Value type(GridCase)
Calls
Called by
Contents
Source Code
GridCase_local
Source Code
   function GridCase_local(nx, ny, im_world, jm_world, lon_range, lat_range, default_decomposition, ims, jms, lons, lats) result(param)
      integer, intent(in) :: nx, ny
      integer, intent(in) :: im_world, jm_world
      type (RealMinMax), intent(in) :: lon_range, lat_range
      logical, intent(in) :: default_decomposition
      integer, intent(in) :: ims(:), jms(:)
      real, intent(in) :: lons(:), lats(:) ! in degrees
      type (GridCase) :: param
      param%nx = nx
      param%ny = ny
      param%im_world = im_world
      param%jm_world = jm_world
      param%dateline = 'XY'
      param%lon_range = lon_range
      param%pole = 'XY'
      param%lat_range = lat_range
      param%default_decomposition = default_decomposition
      param%ims = ims
      param%jms = jms
      param%lons = lons
      param%lats = lats
      call param%setNumPETsRequested(nx*ny)
   end function GridCase_local
Call graph
gridcase_local calls setnumpetsrequested
gridcase calls gridcase_local
getparameters calls gridcase