GridCase_global – MAPL
GridCase_global Function
21 statements
Source File
public function GridCase_global(nx, ny, im_world, jm_world, dateline, pole, default_decomposition, ims, jms, lons, lats) result(param)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: im_world
integer, intent(in) :: jm_world
character(len=2), intent(in) :: dateline
character(len=2), intent(in) :: pole
logical, intent(in) :: default_decomposition
integer, intent(in) :: ims(:)
integer, intent(in) :: jms(:)
real, intent(in) :: lons(:)
real, intent(in) :: lats(:)
Return Value type(GridCase)
Calls
Called by
Contents
Source Code
GridCase_global
Source Code
   function GridCase_global(nx, ny, im_world, jm_world, dateline, pole, default_decomposition, ims, jms, lons, lats) result(param)
      integer, intent(in) :: nx, ny
      integer, intent(in) :: im_world, jm_world
      character(len=2), intent(in) :: dateline, pole
      logical, intent(in) :: default_decomposition
      integer, intent(in) :: ims(:), jms(:)
      real, intent(in) :: lons(:), lats(:) ! in degrees
      type (GridCase) :: param
      param%nx = nx
      param%ny = ny
      param%im_world = im_world
      param%jm_world = jm_world
      param%dateline = dateline
      param%pole = pole
      param%default_decomposition = default_decomposition
      param%ims = ims
      param%jms = jms
      param%lons = lons
      param%lats = lats
      call param%setNumPETsRequested(nx*ny)
   end function GridCase_global
Call graph
gridcase_global calls setnumpetsrequested
gridcase calls gridcase_global
getparameters calls gridcase