HistoryCollectionVector_serialize – MAPL
HistoryCollectionVector_serialize Subroutine
15 statements
Source File
public subroutine HistoryCollectionVector_serialize(histVec, buffer)
Arguments
Type Intent Optional Attributes Name
type(HistoryCollectionVector), intent(in) :: histVec
integer, intent(inout), allocatable :: buffer(:)
Calls
Call graph
historycollectionvector_serialize calls at, serialize
mapl_return calls at, insert, mapl_throw_exception
stringintegermap_serialize calls serialize_buffer_length, serialize_intrinsic, begin, key, next
stringvariablemap_serialize calls serialize_buffer_length, serialize_intrinsic, serialize, mapl_return, begin, key, next, mapl_verify
stringvector_serialize calls serialize_buffer_length, serialize_intrinsic, begin, get, next
mapl_verify calls mapl_throw_exception
stringattributemap_serialize calls serialize_buffer_length, serialize_intrinsic, mapl_return, serialize, begin, key, next