is_valid_time – MAPL
is_valid_time Function
4 statements
Source File
public pure function is_valid_time(time)
Arguments
Type Intent Optional Attributes Name
type(time_fields), intent(in) :: time
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_time
Source Code
   pure logical function is_valid_time(time)
      type(time_fields), intent(in) :: time
      is_valid_time = is_valid_hour(time%hour()) .and. &
         is_valid_minute(time%minute()) .and. &
         is_valid_second(time%second()) .and. &
         is_valid_millisecond(time%millisecond()) .and. &
         is_valid_timezone_offset(time%timezone_offset())
   end function is_valid_time
Call graph
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
construct_time_fields_default calls is_valid_time
test_is_valid_time calls is_valid_time, time_fields
time_fields calls construct_time_fields_default
parse_time calls time_fields
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
construct_time_fields_string calls parse_time
test_parse_time calls parse_time