is_valid_date – MAPL
is_valid_date Function
4 statements
Source File
public pure function is_valid_date(date)
Arguments
Type Intent Optional Attributes Name
type(date_fields), intent(in) :: date
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_date
Source Code
   pure logical function is_valid_date(date)
      type(date_fields), intent(in) :: date
      is_valid_date = is_valid_year(date%year()) .and. &
         is_valid_month(date%month()) .and. &
         is_valid_day(date%year(), date%month(), date%day())
   end function is_valid_date
Call graph
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
is_valid_day calls get_month_end
get_month_end calls get_month_ends
get_month_ends calls is_leap_year
construct_date_fields_default calls is_valid_date
test_is_valid_date calls is_valid_date, date_fields
date_fields calls construct_date_fields_default
parse_date calls date_fields
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields
construct_date_fields_string calls parse_date
test_parse_date calls parse_date