is_valid_minute – MAPL
is_valid_minute Function
4 statements
Source File
public pure function is_valid_minute(minute)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: minute
Return Value logical
Called by
Contents
Source Code
is_valid_minute
Source Code
   pure logical function is_valid_minute(minute)
      integer, intent(in) :: minute
      is_valid_minute = minute .in. [0, 59]
   end function is_valid_minute
Call graph
is_valid_time calls is_valid_minute
test_is_valid_minute calls is_valid_minute
construct_time_fields_default calls is_valid_time
test_is_valid_time calls is_valid_time, time_fields
time_fields calls construct_time_fields_default
parse_time calls time_fields
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields