is_valid_second – MAPL
is_valid_second Function
6 statements
Source File
public pure function is_valid_second(second)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: second
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_second
Source Code
   pure logical function is_valid_second(second)
      integer, intent(in) :: second
      integer, parameter :: LB_SECOND = -1
      integer, parameter :: UB_SECOND = 61
      is_valid_second = is_between(LB_SECOND, UB_SECOND, second)
   end function is_valid_second
Call graph
is_valid_second calls is_between
is_valid_time calls is_valid_second
test_is_valid_second calls is_valid_second
parse_time calls is_valid_time
test_is_valid_time calls is_valid_time
construct_iso8601time calls parse_time
test_parse_time calls parse_time
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time