is_valid_time – MAPL
is_valid_time Function
4 statements
Source File
public pure function is_valid_time(time)
Arguments
Type Intent Optional Attributes Name
type(time_fields), intent(in) :: time
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_time
Source Code
   pure logical function is_valid_time(time)
      type(time_fields), intent(in) :: time
      is_valid_time = is_valid_hour(time%hour_) .and. &
         is_valid_minute(time%minute_) .and. &
         is_valid_second(time%second_) .and. &
         is_valid_millisecond(time%millisecond_) .and. &
         is_valid_timezone_offset(time%timezone_offset_)
   end function is_valid_time
Call graph
is_valid_time calls is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset
is_valid_hour calls is_between
is_valid_millisecond calls is_between
is_valid_minute calls is_between
is_valid_second calls is_between
parse_time calls is_valid_time
test_is_valid_time calls is_valid_time
construct_iso8601time calls parse_time
test_parse_time calls parse_time
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time
construct_iso8601datetime calls iso8601time
convert_iso8601_to_integer_time calls iso8601time
test_iso8601datetime_getters calls iso8601time