is_valid_timezone_offset – MAPL
is_valid_timezone_offset Function
4 statements
Source File
public pure function is_valid_timezone_offset(timezone_offset)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: timezone_offset
Return Value logical
Called by
Contents
Source Code
is_valid_timezone_offset
Source Code
   pure logical function is_valid_timezone_offset(timezone_offset)
      integer, intent(in) :: timezone_offset
      is_valid_timezone_offset = (timezone_offset == Z)
   end function is_valid_timezone_offset
Call graph
is_valid_time calls is_valid_timezone_offset
test_is_valid_timezone_offset calls is_valid_timezone_offset
parse_time calls is_valid_time
test_is_valid_time calls is_valid_time
construct_iso8601time calls parse_time
test_parse_time calls parse_time
test_construct_iso8601time calls construct_iso8601time
iso8601time calls construct_iso8601time