is_whole_number – MAPL
is_whole_number Function
4 statements
Source File
public pure function is_whole_number(n)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Return Value logical
Called by
Contents
Source Code
is_whole_number
Source Code
   pure logical function is_whole_number(n)
      integer, intent(in) :: n
      is_whole_number = .not. (n < 0)
   end function is_whole_number
Call graph
read_whole_number_indexed calls is_whole_number
parse_timezone_offset calls is_whole_number, read_whole_number
test_is_whole_number calls is_whole_number
parse_time calls is_whole_number, parse_timezone_offset, read_whole_number
read_whole_number calls read_whole_number_indexed
test_read_whole_number_indexed calls read_whole_number_indexed
test_parse_timezone_offset calls parse_timezone_offset
construct_iso8601time calls parse_time
construct_iso8601duration calls read_whole_number_indexed
test_parse_time calls parse_time
parse_date calls read_whole_number
iso8601duration calls construct_iso8601duration
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time
test_read_whole_number calls read_whole_number
construct_iso8601date calls parse_date
test_parse_date calls parse_date
test_iso8601datetime_getters calls iso8601time
convert_iso8601_to_integer_time calls iso8601time
convert_iso8601_to_esmf_timeinterval calls iso8601duration
construct_iso8601datetime calls iso8601time