local_esmf_timeset – MAPL
local_esmf_timeset Function
18 statements
Source File
function local_esmf_timeset(yymmdd, hhmmss, rc) result(etime)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: yymmdd
integer, intent(in) :: hhmmss
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Called by
Contents
Source Code
local_esmf_timeset
Source Code
   function local_esmf_timeset(yymmdd,hhmmss,rc) result(etime)
      type(ESMF_Time) :: etime
      integer, intent(in) :: yymmdd
      integer, intent(in) :: hhmmss
      integer, intent(out), optional :: rc
      integer :: year,month,day,hour,minute,second,status
      year = yymmdd/10000
      month = mod(yymmdd/100,100)
      day = mod(yymmdd,100)
      hour = hhmmss/10000
      minute = mod(hhmmss/100,100)
      second = mod(hhmmss,100)
      call ESMF_TimeSet(etime,yy=year,mm=month,dd=day,h=hour,m=minute,s=second,_RC)
      if (present(rc)) then
         rc=_SUCCESS
      endif
   end function local_esmf_timeset
Call graph
local_esmf_timeset calls ESMF_TimeSet, mapl_abort, mapl_verify
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
time_ave calls local_esmf_timeset