MAPL_abort – MAPL
MAPL_abort Subroutine
5 statements
Source File
public subroutine MAPL_abort()
Arguments
None
Calls
Called by
Contents
Source Code
MAPL_abort
Source Code
   subroutine MAPL_abort
      integer :: status
      integer :: error_code
      call MPI_Abort(MPI_COMM_WORLD,error_code,status)
  end subroutine MAPL_abort
Call graph
mapl_abort calls mpi_abort
extdata_driver calls mapl_abort
main calls mapl_abort
create_output_grid calls mapl_abort
add_new_field_to_bundle calls mapl_abort
example_driver calls mapl_abort
copy_bundle_to_bundle calls mapl_abort
get_file_levels calls mapl_abort
latlon_zstar calls mapl_abort, latlon_zmean
get_file_times calls mapl_abort
time_ave calls mapl_abort, create_output_grid, add_new_field_to_bundle, copy_bundle_to_bundle, get_file_levels, latlon_zstar, get_file_times, has_level, get_level_info, local_esmf_timeset, get_long_names, get_units
latlon_zmean calls mapl_abort, get_esmf_grid_layout
get_esmf_grid_layout calls mapl_abort
has_level calls mapl_abort
get_level_info calls mapl_abort
local_esmf_timeset calls mapl_abort
ut_regridding calls mapl_abort
get_long_names calls mapl_abort
get_units calls mapl_abort