MAPL_Return – MAPL
MAPL_Return Subroutine
15 statements
Source File
public subroutine MAPL_Return(status, filename, line, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
character(len=*), intent(in) :: filename
integer, intent(in) :: line
integer, intent(out), optional :: rc
Calls
Called by
BinIOMod::FREE_FILE w MAPL_ErrorHandlingMod::MAPL_Return
w
BinIOMod::GETFILE w
w
BinIOMod::MAPL_Backspace w
w
BinIOMod::MAPL_ClimUpdate w
w
BinIOMod::MAPL_Rewind w
w
BinIOMod::MAPL_Skip w
w
BundleTestSupport::compare_bundle w
w
BundleTestSupport::create_cf w
w
comp_testing_driver::get_config_attributes w
w
comp_testing_driver::run_component_driver w
w
ctest_io_CLI::process_command_line w
w
ESMF_CFIOCollectionMod::CFIOCollection%find w
w
ESMFL_MOD::ESMFL_BundleCpyField w
w
ESMFL_MOD::ESMFL_field_is_undefined w
w
ESMFL_MOD::ESMFL_FieldRegrid w
w
ESMFL_MOD::ESMFL_GridCoordGet w
w
ESMFL_MOD::ESMFL_StateFieldIsNeeded w
w
ESMFL_MOD::ESMFL_StateFreePointers w
w
ESMFL_MOD::ESMFL_StateGetField w
w
ESMFL_MOD::ESMFL_StateGetFieldArray w
w
ESMFL_MOD::ESMFL_StateSetFieldNeeded w
w
ExtData_DriverGridCompMod::ExtData_DriverGridComp%run w
w
ExtData_DriverGridCompMod::ExtData_DriverGridComp%set_services w
w
ExtDataDriverMod::ExtDataDriver%finalize_io_clients_servers w
w
ExtDataDriverMod::ExtDataDriver%initialize_io_clients_servers w
w
ExtDataDriverMod::ExtDataDriver%initialize_mpi w
w
ExtDataDriverMod::ExtDataDriver%run w
w
ExtDataDriverMod::newExtDataDriver w
w
ExtDataUtRoot_GridCompMod::SetServices w
w
FakeHistData0Mod::FakeHistData0%run w
w
field_utils_setup::mk_field_common w
w
field_utils_setup::mk_field_r4_2d w
w
field_utils_setup::mk_field_r4_ungrid w
w
field_utils_setup::mk_field_r8_2d w
w
field_utils_setup::mk_grid w
w
field_utils_setup::mk_r4field w
w
field_utils_setup::mk_r4ungrid_field w
w
field_utils_setup::mk_r8field w
w
FileIOSharedMod::alloc_ w
w
FileIOSharedMod::ArrDescrInit w
w
FileIOSharedMod::dealloc_ w
w
FileIOSharedMod::MAPL_TileMaskGet w
w
linearVerticalInterpolation_mod::vertInterpolation_pressKappa w
w
main::check_resources w
w
main::report w
w
main::report w
w
main::report w
w
main::run w
w
main::run w
w
main::run w
w
main::run w
w
main::time w
w
main::time w
w
main::time w
w
main::write_header w
w
main::write_header w
w
main::write_header w
w
MAPL_AbstractGridFactoryMod::AbstractGridFactory%cartesian_to_spherical_3d_real64 w
w
MAPL_AbstractGridFactoryMod::AbstractGridFactory%get_basis w
w
MAPL_AbstractGridFactoryMod::AbstractGridFactory%make_arbitrary_decomposition w
w
MAPL_AbstractGridFactoryMod::AbstractGridFactory%make_grid w
w
MAPL_AbstractGridFactoryMod::AbstractGridFactory%spherical_to_cartesian_3d_real64 w
w
MAPL_AbstractRegridderMod::AbstractRegridder%initialize_base w
w
MAPL_AbstractRegridderMod::AbstractRegridder%regrid_vector_3d_real64 w
w
MAPL_AbstractRegridderMod::AbstractRegridder%supports w
w
MAPL_ApplicationSupport::MAPL_Finalize w
w
MAPL_ApplicationSupport::MAPL_Initialize w
w
mapl_BaseProfiler::BaseProfiler%start_self w
w
mapl_BW_Benchmark::BW_Benchmark%run w
w
mapl_BW_BenchmarkSpec::make_BW_Benchmark w
w
mapl_BW_BenchmarkSpec::make_BW_BenchmarkSpec w
w
MAPL_CapGridCompMod::MAPL_CapGridCompCreate w
w
MAPL_CFIOMod::MAPL_CFIOClose w
w
MAPL_CFIOMod::MAPL_CFIOCreateFromFile w
w
MAPL_CFIOMod::MAPL_CFIOCreatewrite w
w
MAPL_CFIOMod::MAPL_CFIODestroy w
w
MAPL_CFIOMod::MAPL_CFIOGet w
w
MAPL_CFIOMod::MAPL_CFIOGetTimeString w
w
MAPL_CFIOMod::MAPL_CFIOOpenWrite w
w
MAPL_CFIOMod::MAPL_CFIOReadBundleRead w
w
MAPL_CFIOMod::MAPL_CFIOReadBundleWait w
w
MAPL_CFIOMod::MAPL_CFIOSet w
w
MAPL_CFIOMod::MAPL_CFIOSetKrank w
w
MAPL_CFIOMod::MAPL_CFIOWriteBundlePost w
w
MAPL_CFIOMod::MAPL_CFIOWriteBundleWait w
w
MAPL_CFIOMod::MAPL_CFIOWriteBundleWrite w
w
MAPL_CFIOMod::MAPL_GetCurrentFile w
w
mapl_ComboSpec::make_BW_Benchmark w
w
mapl_ComboSpec::make_ComboSpec w
w
mapl_ComboSpec::make_GathervKernel w
w
MAPL_CommGroupDescriptionMod::CommGroupDescription%comm_group_range w
w
MAPL_CommsMod::MAPL_CollectiveGather3D w
w
MAPL_CommsMod::MAPL_CollectiveScatter3D w
w
MAPL_CommsMod::MAPL_CollectiveWait w
w
MAPL_CommsMod::MAPL_CreateRequest w
w
MAPL_CommsMod::MAPL_RoundRobinPEList w
w
MAPL_ConfigMod::MAPL_ConfigCreate w
w
MAPL_DataCollectionMod::MAPLDataCollection%find w
w
MAPL_DateTime_Parsing_ESMF::set_ESMF_Time_from_ISO8601 w
w
MAPL_DateTime_Parsing_ESMF::set_ESMF_TimeInterval_from_datetime_duration w
w
MAPL_ESMFFieldBundleRead::MAPL_create_bundle_from_metdata_id w
w
MAPL_ESMFFieldBundleRead::MAPL_read_bundle w
w
MAPL_ESMFFieldBundleWrite::FieldBundleWriter%create_from_bundle w
w
MAPL_ESMFFieldBundleWrite::FieldBundleWriter%start_new_file w
w
MAPL_ESMFFieldBundleWrite::FieldBundleWriter%write_to_file w
w
MAPL_ExtData_IOBundleMod::ExtData_IoBundle%clean w
w
MAPL_ExtData_IOBundleMod::ExtData_IoBundle%make_cfio w
w
MAPL_ExtData_IOBundleMod::new_ExtData_IoBundle w
w
MAPL_ExtDataBracket::ExtDataBracket%set_parameters w
w
MAPL_ExtDataConfig::ExtDataConfig%add_new_rule w
w
MAPL_ExtDataConfig::ExtDataConfig%new_ExtDataConfig_from_yaml w
w
MAPL_ExtDataFileStream::ExtDataFileStream%detect_metadata w
w
MAPL_ExtDataGridComp2G::SetServices w
w
MAPL_ExtDataGridCompMod::SetServices w
w
MAPL_ExtDataMask::ExtDataMask%evaluate_box_mask w
w
MAPL_ExtDataMask::ExtDataMask%evaluate_mask w
w
MAPL_ExtDataMask::ExtDataMask%evaluate_region_mask w
w
MAPL_ExtDataMask::ExtDataMask%evaluate_zone_mask w
w
MAPL_ExtDataNG_IOBundleMod::ExtDataNG_IOBundle%clean w
w
MAPL_ExtDataNG_IOBundleMod::ExtDataNG_IOBundle%make_io w
w
MAPL_ExtDataNG_IOBundleMod::new_ExtDataNG_IOBundle w
w
MAPL_ExtDataOldTypesCreator::ExtDataOldTypesCreator%fillin_derived w
w
MAPL_ExtDataOldTypesCreator::ExtDataOldTypesCreator%fillin_primary w
w
MAPL_ExtDataOldTypesCreator::new_ExtDataOldTypesCreator w
w
MAPL_ExtDataPointerUpdate::ExtDataPointerUpdate%create_from_parameters w
w
MAPL_ExtDataRule::ExtDataRule%set_defaults w
w
MAPL_ExtDataRule::ExtDataRule%split_vector w
w
MAPL_ExtDataTimeSample::ExtDataTimeSample%set_defaults w
w
MAPL_ExtDataTypeDef::DerivedExport%evaluate_derived_field w
w
MAPL_FieldBinaryOperations::fieldAdd w
w
MAPL_FieldBinaryOperations::fieldDivide w
w
MAPL_FieldBinaryOperations::fieldMultiply w
w
MAPL_FieldBinaryOperations::fieldPower w
w
MAPL_FieldBinaryOperations::fieldSubtract w
w
MAPL_FieldPointerUtilities::FieldsHaveUndef w
w
MAPL_FieldUnaryFunctions::fieldAbs w
w
MAPL_FieldUnaryFunctions::fieldAcos w
w
MAPL_FieldUnaryFunctions::fieldAsin w
w
MAPL_FieldUnaryFunctions::fieldAtan w
w
MAPL_FieldUnaryFunctions::fieldCos w
w
MAPL_FieldUnaryFunctions::fieldCosh w
w
MAPL_FieldUnaryFunctions::fieldExp w
w
MAPL_FieldUnaryFunctions::fieldLog w
w
MAPL_FieldUnaryFunctions::fieldLog10 w
w
MAPL_FieldUnaryFunctions::fieldSin w
w
MAPL_FieldUnaryFunctions::fieldSinh w
w
MAPL_FieldUnaryFunctions::fieldSqrt w
w
MAPL_FieldUnaryFunctions::fieldTan w
w
MAPL_FieldUnaryFunctions::fieldTanh w
w
MAPL_FieldUtilities::FieldNegate w
w
MAPL_FieldUtilities::FieldPow w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_coordinate_info w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_file_name w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_level_name w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_time_info w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_var_attr_int32 w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_var_attr_int64 w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_var_attr_real32 w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_var_attr_real64 w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_var_attr_string w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%get_variable_attribute w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%var_get_missing_value w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%var_has_attr w
w
MAPL_FileMetadataUtilsMod::FileMetadataUtils%var_has_missing_value w
w
mapl_GathervKernel::GathervKernel%init w
w
mapl_GathervKernel::GathervKernel%run w
w
mapl_GathervSpec::make_GathervKernel w
w
mapl_GathervSpec::make_GathervSpec w
w
MAPL_GenericCplCompMod::GenericCplSetServices w
w
MAPL_GenericCplCompMod::MAPL_CplCompSetAlarm w
w
MAPL_GenericCplCompMod::MAPL_CplCompSetVarSpecs w
w
MAPL_GenericMod::MAPL_AddRecord w
w
MAPL_GenericMod::MAPL_AdvertiseService w
w
MAPL_GenericMod::MAPL_ChildAddAttribToImportSpec w
w
MAPL_GenericMod::MAPL_ConnectService w
w
MAPL_GenericMod::MAPL_DateStampGet w
w
MAPL_GenericMod::MAPL_DisableRecord w
w
MAPL_GenericMod::MAPL_DoNotAllocateImport w
w
MAPL_GenericMod::MAPL_DoNotAllocateInternal w
w
MAPL_GenericMod::MAPL_DoNotDeferExport w
w
MAPL_GenericMod::MAPL_ESMFStateReadFromFile w
w
MAPL_GenericMod::MAPL_ExchangeGridGet w
w
MAPL_GenericMod::MAPL_ExchangeGridSet w
w
MAPL_GenericMod::MAPL_ExportStateGet w
w
MAPL_GenericMod::MAPL_FriendlyGet w
w
MAPL_GenericMod::MAPL_GCGet w
w
MAPL_GenericMod::MAPL_GenericFinalize w
w
MAPL_GenericMod::MAPL_GenericInitialize w
w
MAPL_GenericMod::MAPL_GenericMakeXchgNatural w
w
MAPL_GenericMod::MAPL_GenericRecord w
w
MAPL_GenericMod::MAPL_GenericRefresh w
w
MAPL_GenericMod::MAPL_GenericRunChildren w
w
MAPL_GenericMod::MAPL_GenericRunCouplers w
w
MAPL_GenericMod::MAPL_GenericSetServices w
w
MAPL_GenericMod::MAPL_GenericStateRestore w
w
MAPL_GenericMod::MAPL_GenericStateSave w
w
MAPL_GenericMod::MAPL_GetAllExchangeGrids w
w
MAPL_GenericMod::MAPL_GetChildLocstream w
w
MAPL_GenericMod::MAPL_GridCompSetEntryPoint w
w
MAPL_GenericMod::MAPL_GridCreate w
w
MAPL_GenericMod::MAPL_ImportStateGet w
w
MAPL_GenericMod::MAPL_InternalESMFStateGet w
w
MAPL_GenericMod::MAPL_InternalStateCreate w
w
MAPL_GenericMod::MAPL_InternalStateRetrieve w
w
MAPL_GenericMod::MAPL_MethodAdd w
w
MAPL_GenericMod::MAPL_RecordAlarmIsRinging w
w
MAPL_GenericMod::MAPL_RequestService w
w
MAPL_GenericMod::MAPL_SetVarSpecForCC w
w
MAPL_GenericMod::MAPL_StateAlarmAdd w
w
MAPL_GenericMod::MAPL_StateAlarmGet w
w
MAPL_GenericMod::MAPL_StateCreateFromSpec w
w
MAPL_GenericMod::MAPL_StateCreateFromSpecNew w
w
MAPL_GenericMod::MAPL_StatePrintSpecCSV w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%alphabatize_variables w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%bundlePost w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%check_chunking w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%CreateFileMetaData w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%CreateVariable w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%modifyTime w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%process_data_from_file w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%regridScalar w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%regridVector w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%request_data_from_file w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%set_default_chunking w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%set_param w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%stage2DLatLon w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%stageData w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%swap_undef_value w
w
MAPL_GridManager_private::GridManager%delete w
w
MAPL_GridManager_private::GridManager%get_factory w
w
MAPL_GridManager_private::GridManager%make_clone w
w
MAPL_GridManager_private::GridManager%make_factory_from_distGrid w
w
MAPL_GridManager_private::GridManager%make_grid_from_distGrid w
w
MAPL_GridManagerMod::get_factory w
w
MAPL_GridManagerMod::get_factory_id w
w
MAPL_HistoryGridCompMod::SetServices w
w
MAPL_ISO8601_DateTime::construct_ISO8601Date w
w
MAPL_ISO8601_DateTime::construct_ISO8601DateTime w
w
MAPL_ISO8601_DateTime::construct_ISO8601Duration w
w
MAPL_ISO8601_DateTime::construct_ISO8601Time w
w
MAPL_ISO8601_DateTime::convert_ISO8601_to_integer_date w
w
MAPL_ISO8601_DateTime::convert_ISO8601_to_integer_time w
w
MAPL_ISO8601_DateTime_ESMF::convert_ISO8601_to_esmf_time w
w
MAPL_ISO8601_DateTime_ESMF::convert_ISO8601_to_esmf_timeinterval w
w
MAPL_LatLonGridFactoryMod::LatLonGridFactory%get_latitudes w
w
MAPL_LatLonGridFactoryMod::LatLonGridFactory%get_longitudes w
w
MAPL_LoadBalanceMod::MAPL_BalanceCreate w
w
MAPL_LoadBalanceMod::MAPL_BalanceDestroy w
w
MAPL_LoadBalanceMod::MAPL_BalanceGet w
w
MAPL_LocStreamMod::MAPL_GridCoordAdjust w
w
MAPL_LocStreamMod::MAPL_LocStreamAdjustNsubtiles w
w
MAPL_LocStreamMod::MAPL_LocStreamCreateXform w
w
MAPL_LocStreamMod::MAPL_LocStreamFracArea w
w
MAPL_LocStreamMod::MAPL_LocStreamGet w
w
MAPL_LocStreamMod::MAPL_LocStreamIsAssociated w
w
MAPL_LocStreamMod::MAPL_LocStreamTileWeight w
w
MAPL_LocStreamMod::MAPL_LocStreamXformIsAssociated w
w
mapl_MaplGrid::MAPL_GetImsJms w
w
mapl_MaplGrid::MAPL_GridGet w
w
mapl_MaplGrid::MAPL_GridHasDE w
w
mapl_MaplGrid::MaplGrid%set w
w
MAPL_MemUtilsMod::MAPL_MemCommited w
w
MAPL_MemUtilsMod::MAPL_MemUsed w
w
MAPL_MemUtilsMod::MAPL_MemUtilsDisable w
w
MAPL_MemUtilsMod::MAPL_MemUtilsFree w
w
MAPL_MemUtilsMod::MAPL_MemUtilsInit w
w
MAPL_NewArthParserMod::CheckSyntax w
w
MAPL_NewArthParserMod::MAPL_StateEval w
w
MAPL_NewArthParserMod::parser_variables_in_expression w
w
mapl_NewRegridderManager_private::NewRegridderManager%find_prototype w
w
mapl_NewRegridderManager_private::NewRegridderManager%make_regridder_ w
w
MAPL_NUOPCWrapperMod::get_cap_parameters_from_gc w
w
MAPL_NUOPCWrapperMod::init_wrapper w
w
MAPL_NUOPCWrapperMod::SetServices w
w
MAPL_ObsUtilMod::copy_platform_nckeys w
w
MAPL_ObsUtilMod::Find_M_files_for_currTime w
w
MAPL_ObsUtilMod::get_filename_from_template w
w
MAPL_ObsUtilMod::get_filename_from_template_use_index w
w
MAPL_ObsUtilMod::get_obsfile_Tbracket_from_epoch w
w
MAPL_ObsUtilMod::get_var_from_name_w_group w
w
MAPL_ObsUtilMod::read_M_files_4_swath w
w
MAPL_ObsUtilMod::reset_times_to_current_day w
w
MAPL_ObsUtilMod::sort_four_arrays_by_time w
w
MAPL_ObsUtilMod::sort_three_arrays_by_time w
w
MAPL_ObsUtilMod::time_real_to_ESMF w
w
MAPL_ObsUtilMod::union_platform w
w
MAPL_OpenMP_Support::get_callbacks w
w
MAPL_OpenMP_Support::make_subgridcomps w
w
MAPL_OrbGridCompMod::SetServices w
w
MAPL_ProfMod::MAPL_ProfDisable w
w
MAPL_ProfMod::MAPL_ProfEnable w
w
MAPL_RegridderManager_private::RegridderManager%make_regridder_from_grids w
w
MAPL_ResourceMod::MAPL_GetResource_config_array w
w
MAPL_ResourceMod::MAPL_GetResource_config_scalar w
w
MAPL_ServerManager::ServerManager%finalize w
w
MAPL_ServerManager::ServerManager%get_splitcomm w
w
MAPL_ServerManager::ServerManager%initialize w
w
mapl_ServiceServices::FillRequestBundle w
w
mapl_ServiceServices::ProvidedServiceGet w
w
mapl_ServiceServices::ProvidedServiceSet w
w
mapl_ServiceServices::RequestedServiceGet w
w
mapl_ServiceServicesTypes::ServiceConnectionGet w
w
MAPL_SimpleBundleMod::MAPL_SimpleBundleDestroy w
w
MAPL_SimpleBundleMod::MAPL_SimpleBundleGetIndex w
w
MAPL_SimpleBundleMod::MAPL_SimpleBundleRead w
w
MAPL_SimpleCommSplitterMod::SimpleCommSplitter%add_group_simple w
w
MAPL_SimpleCommSplitterMod::SimpleCommSplitter%compute_color w
w
MAPL_SimpleCommSplitterMod::SimpleCommSplitter%get_node_id w
w
MAPL_SimpleCommSplitterMod::SimpleCommSplitter%get_node_sizes w
w
MAPL_SimpleCommSplitterMod::SimpleCommSplitter%split w
w
MAPL_SphericalGeometry::get_points_in_spherical_domain w
w
mapl_StateSpecification::MAPL_VarSpecCreateInListNew w
w
MAPL_StringTemplate::fill_grads_template w
w
MAPL_SunMod::MAPL_SunGetDaylightDuration w
w
MAPL_SunMod::MAPL_SunGetDaylightDurationMax w
w
MAPL_SunMod::MAPL_SunGetLocalSolarHourAngle w
w
MAPL_SunMod::MAPL_SunOrbitCreate w
w
MAPL_SunMod::MAPL_SunOrbitCreated w
w
MAPL_SunMod::MAPL_SunOrbitCreateFromConfig w
w
MAPL_SunMod::MAPL_SunOrbitDestroy w
w
MAPL_SunMod::MAPL_SunOrbitQuery w
w
MAPL_TilingRegridderMod::TilingRegridder%find_tile_file w
w
MAPL_TilingRegridderMod::TilingRegridder%initialize_subclass w
w
MAPL_TimeDataMod::timeData%add_time_to_metadata w
w
MAPL_TimeDataMod::timeData%compute_time_vector w
w
MAPL_TimeDataMod::timeData%define_time_variable w
w
mapl_TimeProfiler::start_global_time_profiler w
w
mapl_TimeProfiler::stop_global_time_profiler w
w
MAPL_TimeStringConversion::string_to_esmf_time w
w
MAPL_TimeStringConversion::string_to_esmf_timeinterval w
w
MAPL_TimeStringConversion::string_to_integer_date w
w
MAPL_TimeStringConversion::string_to_integer_time w
w
mapl_VarConn::VarConn%checkReq w
w
mapl_VarConn::VarConn%varIsConnected_name w
w
mapl_VarConn::VarConn%varIsListed w
w
MAPL_VarSpecMod::MAPL_VarSpecAddChildName w
w
MAPL_VarSpecMod::MAPL_VarSpecCreateInList w
w
MAPL_VarSpecMod::MAPL_VarSpecPrintCSV w
w
MAPL_VarSpecMod::MAPL_VarSpecReconnect w
w
MAPL_VerticalDataMod::verticalData%append_vertical_metadata w
w
MAPL_VerticalDataMod::verticalData%correct_topo w
w
MAPL_VerticalDataMod::verticalData%flip_levels w
w
MAPL_VerticalDataMod::verticalData%regrid_eta_to_pressure w
w
MAPL_VerticalDataMod::verticalData%regrid_select_level w
w
MAPL_VerticalDataMod::verticalData%setup_eta_to_pressure w
w
NCIOMod::MAPL_IOChangeRes w
w
NCIOMod::MAPL_IOCountLevels w
w
NCIOMod::MAPL_IOCountNonDimVars w
w
NCIOMod::MAPL_IOGetNonDimVars w
w
NCIOMod::MAPL_IOGetTime w
w
NCIOMod::MAPL_NCIOGetFileType w
w
pFIO_AbstractDataMessageMod::AbstractDataMessage%deserialize w
w
pFIO_AbstractDataMessageMod::AbstractDataMessage%serialize w
w
pFIO_AbstractDataReferenceMod::AbstractDataReference%deserialize_base w
w
pFIO_AbstractDataReferenceMod::AbstractDataReference%serialize_base w
w
pFIO_AbstractMessageMod::AbstractMessage%dispatch w
w
pFIO_AbstractServerMod::AbstractServer%report_profile w
w
pFIO_AttributeMod::Attribute_deserialize w
w
pFIO_BaseThreadMod::BaseThread%clear_RequestHandle w
w
pFIO_BaseThreadMod::BaseThread%get_connection w
w
pFIO_BaseThreadMod::BaseThread%insert_RequestHandle w
w
pFIO_BaseThreadMod::BaseThread%set_connection w
w
pFIO_ClientManagerMod::ClientManager%add_ext_collection w
w
pFIO_ClientManagerMod::ClientManager%add_hist_collection w
w
pFIO_ClientManagerMod::ClientManager%collective_prefetch_data w
w
pFIO_ClientManagerMod::ClientManager%collective_stage_data w
w
pFIO_ClientManagerMod::ClientManager%done_collective_prefetch w
w
pFIO_ClientManagerMod::ClientManager%done_collective_stage w
w
pFIO_ClientManagerMod::ClientManager%modify_metadata w
w
pFIO_ClientManagerMod::ClientManager%post_wait w
w
pFIO_ClientManagerMod::ClientManager%set_current w
w
pFIO_ClientManagerMod::ClientManager%set_optimal_server w
w
pFIO_ClientManagerMod::ClientManager%set_server_size w
w
pFIO_ClientManagerMod::ClientManager%split_server_pools w
w
pFIO_ClientManagerMod::ClientManager%stage_nondistributed_data w
w
pFIO_ClientManagerMod::ClientManager%terminate w
w
pFIO_ClientThreadMod::ClientThread%add_ext_collection w
w
pFIO_ClientThreadMod::ClientThread%add_hist_collection w
w
pFIO_ClientThreadMod::ClientThread%collective_prefetch_data w
w
pFIO_ClientThreadMod::ClientThread%collective_stage_data w
w
pFIO_ClientThreadMod::ClientThread%done_collective_prefetch w
w
pFIO_ClientThreadMod::ClientThread%done_collective_stage w
w
pFIO_ClientThreadMod::ClientThread%done_prefetch w
w
pFIO_ClientThreadMod::ClientThread%modify_metadata w
w
pFIO_ClientThreadMod::ClientThread%prefetch_data w
w
pFIO_ClientThreadMod::ClientThread%stage_nondistributed_data w
w
pFIO_ClientThreadMod::ClientThread%terminate w
w
pFIO_CoordinateVariableMod::CoordinateVariable%get_coordinate_data w
w
pFIO_CoordinateVariableMod::CoordinateVariable%replace_coordinate_data w
w
pFIO_CoordinateVariableMod::CoordinateVariable%serialize w
w
pFIO_CoordinateVariableMod::CoordinateVariable_deserialize w
w
pFIO_DirectoryServiceMod::DirectoryService%connect_to_client w
w
pFIO_DirectoryServiceMod::DirectoryService%connect_to_server w
w
pFIO_DirectoryServiceMod::DirectoryService%free_directory_resources w
w
pFIO_DirectoryServiceMod::DirectoryService%publish w
w
pFIO_FileMetadataMod::FileMetadata%add_attribute_0d w
w
pFIO_FileMetadataMod::FileMetadata%add_attribute_1d w
w
pFIO_FileMetadataMod::FileMetadata%add_dimension w
w
pFIO_FileMetadataMod::FileMetadata%add_variable w
w
pFIO_FileMetadataMod::FileMetadata%get_attribute w
w
pFIO_FileMetadataMod::FileMetadata%get_attributes w
w
pFIO_FileMetadataMod::FileMetadata%get_coordinate_variable w
w
pFIO_FileMetadataMod::FileMetadata%get_dimension w
w
pFIO_FileMetadataMod::FileMetadata%get_order w
w
pFIO_FileMetadataMod::FileMetadata%get_variable w
w
pFIO_FileMetadataMod::FileMetadata%get_variables w
w
pFIO_FileMetadataMod::FileMetadata%modify_dimension w
w
pFIO_FileMetadataMod::FileMetadata%modify_variable w
w
pFIO_FileMetadataMod::FileMetadata%serialize w
w
pFIO_FileMetadataMod::FileMetadata%set_order w
w
pFIO_FileMetadataMod::FileMetadata_deserialize w
w
pFIO_LocalMemReferenceMod::LocalMemReference%deserialize w
w
pFIO_LocalMemReferenceMod::LocalMemReference%serialize w
w
pFIO_MessageVectorUtilMod::deserialize_message_vector w
w
pFIO_MpiSocketMod::MpiSocket%receive w
w
pFIO_MpiSocketMod::MpiSocket%send w
w
pFIO_NetCDF4_FileFormatterMod::NetCDF4_FileFormatter%create w
w
pFIO_NetCDF4_FileFormatterMod::NetCDF4_FileFormatter%create_par w
w
pFIO_NetCDF4_FileFormatterMod::NetCDF4_FileFormatter%get_var_real64_4 w
w
pFIO_NetCDF4_FileFormatterMod::NetCDF4_FileFormatter%inq_dim w
w
pFIO_NetCDF4_FileFormatterMod::NetCDF4_FileFormatter%inq_var_string_length w
w
pFIO_NetCDF4_FileFormatterMod::NetCDF4_FileFormatter%put_var_real64_4 w
w
pFIO_ServerThreadMod::ServerThread%init w
w
pFIO_ServerThreadMod::ServerThread%run w
w
pFIO_SimpleSocketMod::SimpleSocket%send w
w
pFIO_StringAttributeMapUtilMod::StringAttributeMap_deserialize w
w
pFIO_StringAttributeMapUtilMod::StringAttributeMap_serialize w
w
pFIO_StringIntegerMapUtilMod::StringIntegerMap_deserialize w
w
pFIO_StringUnlimitedEntityMapUtilMod::StringUnlimitedEntityMap_deserialize w
w
pFIO_StringVariableMapUtilMod::StringVariableMap_deserialize w
w
pFIO_StringVariableMapUtilMod::StringVariableMap_serialize w
w
pFIO_StringVectorUtilMod::StringVector_deserialize w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%get_rank w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%get_shape w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%get_value w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%get_values w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%is_empty w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%serialize w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%set w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity_deserialize w
w
pFIO_UtilitiesMod::i_to_string w
w
pFIO_UtilitiesMod::word_size w
w
pFIO_VariableMod::Variable%add_attribute_1d w
w
pFIO_VariableMod::Variable%add_const_value w
w
pFIO_VariableMod::Variable%get_attribute w
w
pFIO_VariableMod::Variable%get_ith_dimension w
w
pFIO_VariableMod::Variable%is_attribute_present w
w
pFIO_VariableMod::Variable%serialize w
w
pFIO_VariableMod::Variable_deserialize w
w
Plain_netCDF_Time::bisect_find_LB_R8_I8 w
w
Plain_netCDF_Time::check_nc_status w
w
Plain_netCDF_Time::convert_twostring_2_esmfinterval w
w
Plain_netCDF_Time::ESMF_time_to_two_integer w
w
Plain_netCDF_Time::get_att_char_netcdf w
w
Plain_netCDF_Time::get_att_real_netcdf w
w
Plain_netCDF_Time::get_attribute_from_group w
w
Plain_netCDF_Time::get_ncfile_dimension w
w
Plain_netCDF_Time::get_v1d_netcdf_R8 w
w
Plain_netCDF_Time::get_v1d_netcdf_R8_complete w
w
Plain_netCDF_Time::get_v2d_netcdf_R4 w
w
Plain_netCDF_Time::get_v2d_netcdf_R8 w
w
Plain_netCDF_Time::parse_timeunit_i4 w
w
Plain_netCDF_Time::parse_timeunit_i8 w
w
Plain_netCDF_Time::time_esmf_2_nc_int w
w
Plain_netCDF_Time::time_nc_int_2_esmf w
w
Plain_netCDF_Time::two_integer_to_ESMF_time w
w
Regrid_Util::get_file_levels w
w
Regrid_Util::get_file_times w
w
regrid_util_support_mod::regrid_support%create_grid w
w
regrid_util_support_mod::regrid_support%has_level w
w
regrid_util_support_mod::regrid_support%process_command_line w
w
RUTMod::SetServices w
w
SupportMod::regrid w
w
SupportMod::RegridSupport%create_cubed_sphere_grid w
w
SupportMod::RegridSupport%create_esmf_grids w
w
SupportMod::RegridSupport%create_lat_lon_grid w
w
SupportMod::RegridSupport%transfer_metadata w
w
Test_CFIO_Bundle::MyGridCreate_ w
w
utCFIO::MyGridCreate_ w
w
Source Code
   subroutine MAPL_Return(status, filename, line, rc)
      integer, intent(in) :: status
      character(*), intent(in) :: filename
      integer, intent(in) :: line
      integer, intent(out), optional :: rc
      logical :: condition, fail
      character(:), allocatable :: message
      condition = (status == 0)
      fail = .not. condition
      if (fail) then
         message = get_error_message(status)
         !$omp critical (MAPL_ErrorHandling4)
         call MAPL_throw_exception(filename, line, message=message)
         !$omp end critical (MAPL_ErrorHandling4)
      end if
      ! Regardless of error:
      if (present(rc)) rc = status
   end subroutine MAPL_Return
Call graph
mapl_return calls at, insert, mapl_throw_exception