MAPL_VarSpecSamePrec – MAPL
MAPL_VarSpecSamePrec Function
8 statements
Source File
public function MAPL_VarSpecSamePrec(s1, s2)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: s1
type(MAPL_VarSpec), intent(in) :: s2
Return Value logical
Called by
Source Code
   function MAPL_VarSpecSamePrec(s1, s2)
      type (MAPL_VarSpec ), intent(in) :: s1, s2
      logical                          :: MAPL_VarSpecSamePrec
      MAPL_VarSpecSamePrec = .FALSE.
      if (S1%SPECPtr%PRECISION /= S2%SPECPtr%PRECISION       ) RETURN
      MAPL_VarSpecSamePrec = .TRUE.
      RETURN
   end function MAPL_VarSpecSamePrec
Call graph
mapl_genericsetservices calls mapl_varspecsameprec
setservices calls mapl_genericsetservices