mk_field_r8_2d – MAPL
mk_field_r8_2d Function
19 statements
Source File
public function mk_field_r8_2d(farray, regDecomp, minIndex, maxIndex, indexflag, name, rc) result(field)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in), dimension(:,:), target :: farray
integer, intent(in), dimension(:) :: regDecomp
integer, intent(in), dimension(:) :: minIndex
integer, intent(in), dimension(:) :: maxIndex
type(ESMF_Index_Flag), intent(in) :: indexflag
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Called by
Source Code
   function mk_field_r8_2d(farray, regDecomp, minIndex, maxIndex, indexflag, name, rc) result(field)
      real(kind=ESMF_KIND_R8), dimension(:,:), target, intent(in) :: farray
      integer, dimension(:), intent(in) :: regDecomp
      integer, dimension(:), intent(in) :: minIndex
      integer, dimension(:), intent(in) :: maxIndex
      type(ESMF_Index_Flag), intent(in) :: indexflag
      character(len=*), intent(in) :: name
      integer, optional, intent(out) :: rc
      type(ESMF_Field) :: field
      real(kind=ESMF_KIND_R8), dimension(:,:), pointer :: ptr
      integer :: status
      field = mk_field_common(tk = ESMF_TYPEKIND_R8, regDecomp=regDecomp, minIndex=minIndex, maxIndex=maxIndex, indexflag = indexflag, name = name, _RC)
      call ESMF_FieldGet(field, farrayPtr = ptr, _RC)
      ptr => farray
      _RETURN(_SUCCESS)
   end function mk_field_r8_2d
Call graph
mk_field_r8_2d calls esmf_fieldget, mapl_return, mapl_verify, mk_field_common
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mk_field_common calls mapl_return, mapl_verify, esmf_fieldcreate, mk_grid
mk_grid calls mapl_return, mapl_verify, ESMF_GridCreateNoPeriDim
mk_field calls mk_field_r8_2d
set_up_data calls mk_field
test_fieldconvertprec_r4r8 calls mk_field