mk_grid – MAPL
mk_grid Function
14 statements
Source File
public function mk_grid(regDecomp, minIndex, maxIndex, indexflag, grid_name, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: regDecomp
integer, intent(in), dimension(:) :: minIndex
integer, intent(in), dimension(:) :: maxIndex
type(ESMF_Index_Flag), intent(in) :: indexflag
character(len=*), intent(in) :: grid_name
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Contents
Source Code
mk_grid
Source Code
   function mk_grid(regDecomp, minIndex, maxIndex, indexflag, grid_name, rc) result(grid)
      integer, dimension(:), intent(in) :: regDecomp
      integer, dimension(:), intent(in) :: minIndex
      integer, dimension(:), intent(in) :: maxIndex
      type(ESMF_Index_Flag), intent(in) :: indexflag
      character(len=*), intent(in) :: grid_name
      integer, optional, intent(out) :: rc
      type(ESMF_Grid) :: grid
      integer :: status
      grid = ESMF_GridCreateNoPeriDim(regDecomp = regDecomp, maxIndex = maxIndex, minIndex = minIndex, indexflag = indexflag, name = grid_name, _RC)
      _RETURN(_SUCCESS)
   end function mk_grid
Call graph
mk_grid calls ESMF_GridCreateNoPeriDim, mapl_return, mapl_verify
mapl_return calls mapl_throw_exception
mapl_verify calls mapl_throw_exception
mk_field_common calls mk_grid
mk_field_r4_2d calls mk_field_common
mk_field_r4_ungrid calls mk_field_common
mk_field_r8_2d calls mk_field_common
mk_field calls mk_field_r4_2d, mk_field_r8_2d
set_up_data calls mk_field_r4_ungrid, mk_field
test_fieldconvertprec_r4r8 calls mk_field