mk_r4ungrid_field – MAPL
mk_r4ungrid_field Function
12 statements
Source File
public function mk_r4ungrid_field(field_name, lbound, ubound, rc) result(r4field)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: field_name
integer, intent(in) :: lbound
integer, intent(in) :: ubound
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Source Code
   function mk_r4ungrid_field(field_name, lbound, ubound, rc) result(r4field)
      type(ESMF_Field) :: r4field
      character(len=*), intent(in) :: field_name
      integer, intent(in) :: lbound
      integer, intent(in) :: ubound
      integer, optional, intent(out) :: rc
      integer :: status
      r4field = mk_field_r4_ungrid(name = field_name, ungriddedLBound=[lbound],ungriddedUBound=[ubound],_RC)
      _RETURN(_SUCCESS)
   end function mk_r4ungrid_field
Call graph
mk_r4ungrid_field calls mapl_return, mapl_verify, mk_field_r4_ungrid
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mk_field_r4_ungrid calls mapl_return, mapl_verify, mk_field_common
mk_field_common calls mapl_return, mapl_verify, esmf_fieldcreate, mk_grid
mk_grid calls mapl_return, mapl_verify, ESMF_GridCreateNoPeriDim