parse_time – MAPL
parse_time Function
63 statements
Source File
public pure function parse_time(timestring, delimiter) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: timestring
character(len=1), intent(in), optional :: delimiter
Return Value type(time_fields)
Calls
Called by
Contents
Source Code
parse_time
Source Code
   pure function parse_time(timestring, delimiter) result(fields)
      character(len=*), intent(in) :: timestring
      character, optional, intent(in) :: delimiter
      type(time_fields) :: fields
      character(len=:), allocatable :: timestring_
      integer, parameter :: LENGTH = 6
      character, parameter :: DECIMAL_POINT = '.'
      integer, parameter :: FIELDWIDTH = 2
      integer, parameter :: MS_WIDTH = 3
      integer :: pos
      character(len=:), allocatable :: undelimited
      character :: c
      character(len=LENGTH) :: offset
      integer :: offset_minutes
      integer :: undelimited_length
      integer :: signum
      integer :: hour
      integer :: minute
      integer :: second
      integer :: millisecond
      integer :: timezone_offset
      fields = time_fields()
      timestring_ = trim(timestring)
      ! Get timezone
      ! Find timezone portion
      pos = scan(timestring_, '-Z+')
      if(.not. pos > 0) return
      c = timestring_(pos:pos)
      ! Check first character of timezone portion
      select case(c)
         case('Z')
            signum = 0
         case('-')
            signum = -1
         case('+')
            signum = +1
         case default
            return
      end select
      ! Set timezone offset
      if(signum == 0) then
         if(pos /= len(timestring_)) return
         timezone_offset = Z
      else
         offset = timestring_(pos+1:len(timestring_))
         offset = undelimit(offset, delimiter)
         offset_minutes = parse_timezone_offset(offset, FIELDWIDTH)
         if(.not. is_whole_number(offset_minutes)) return
         timezone_offset = signum * offset_minutes
      end if
      ! Select portion starting at fields%hour and ending before timezone
      undelimited = adjustl(timestring_(1:pos-1))
      ! Remove delimiter and decimal point
      undelimited = undelimit(undelimited, delimiter)
      undelimited=trim(undelimit(undelimited, DECIMAL_POINT))
      undelimited_length = len(undelimited)
      ! Check length of undelimited string with or without milliseconds
      select case(undelimited_length)
         case(LENGTH)
            millisecond = 0
         case(LENGTH+MS_WIDTH)
            millisecond = read_whole_number(undelimited(7:9))
         case default
            return
      end select
      ! Read time fields
      hour = read_whole_number(undelimited(1:2))
      minute = read_whole_number(undelimited(3:4))
      second = read_whole_number(undelimited(5:6))
      fields = time_fields(hour, minute, second, millisecond, timezone_offset)
   end function parse_time
Call graph
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string
get_integer_digit_from_string calls get_integer_digit
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
test_parse_time calls parse_time
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_is_valid_time calls time_fields