parse_date – MAPL
parse_date Function
18 statements
Source File
public pure function parse_date(datestring, delimiter) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: datestring
character(len=1), intent(in) :: delimiter
Return Value type(date_fields)
Calls
Called by
Contents
Source Code
parse_date
Source Code
   pure function parse_date(datestring, delimiter) result(fields)
      character(len=*), intent(in) :: datestring
      character, intent(in) :: delimiter
      type(date_fields) :: fields
      integer, parameter :: LENGTH = 8
      integer, parameter :: YEAR_POSITION = 1
      integer, parameter :: MONTH_POSITION = 5
      integer, parameter :: DAY_POSITION = 7
      integer :: year, month, day
      character(len=LENGTH) :: undelimited
      ! initialize fields to empty (is_valid_ .FALSE.)
      fields = date_fields()
      ! Eliminate delimiters so that there is one parsing block
      undelimited=undelimit(datestring, DELIMITER)
      if(len(undelimited) /= LENGTH) return
      year = read_whole_number(undelimited(YEAR_POSITION:MONTH_POSITION-1))
      month = read_whole_number(undelimited(MONTH_POSITION:DAY_POSITION-1))
      day = read_whole_number(undelimited(DAY_POSITION:LENGTH))
      fields = date_fields(year, month, day)
   end function parse_date
Call graph
parse_date calls date_fields, read_whole_number, undelimit
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
read_whole_number calls read_whole_number_indexed
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
get_integer_digit_from_string calls get_integer_digit
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
test_parse_date calls parse_date
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields