read_whole_number – MAPL
read_whole_number Function
4 statements
Source File
public pure function read_whole_number(string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value integer
Calls
Called by
Contents
Source Code
read_whole_number
Source Code
   pure integer function read_whole_number(string)
      character(len=*), intent(in) :: string
      read_whole_number = read_whole_number_indexed(string, 1, len(string))
   end function read_whole_number
Call graph
read_whole_number calls read_whole_number_indexed
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
get_integer_digit_from_string calls get_integer_digit
parse_date calls read_whole_number
parse_time calls read_whole_number, parse_timezone_offset
parse_timezone_offset calls read_whole_number
test_read_whole_number calls read_whole_number
construct_iso8601date calls parse_date
construct_iso8601time calls parse_time
test_parse_date calls parse_date
test_parse_time calls parse_time
test_parse_timezone_offset calls parse_timezone_offset
iso8601date calls construct_iso8601date
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time
construct_iso8601datetime calls iso8601date, iso8601time
convert_iso8601_to_integer_date calls iso8601date
convert_iso8601_to_integer_time calls iso8601time
test_construct_iso8601date calls iso8601date
test_iso8601datetime_getters calls iso8601date, iso8601time