report – MAPL
report Subroutine
26 statements
Source File
subroutine report(spec, avg_time, rel_std_time, comm, rc)
Arguments
Type Intent Optional Attributes Name
type(GathervSpec), intent(in) :: spec
real, intent(in) :: avg_time
real, intent(in) :: rel_std_time
integer, intent(in) :: comm
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
report
Source Code
   subroutine report(spec, avg_time, rel_std_time, comm, rc)
      type(GathervSpec), intent(in) :: spec
      real, intent(in) :: avg_time
      real, intent(in) :: rel_std_time
      integer, intent(in) :: comm
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: rank
      integer :: npes
      integer :: group
      real :: bw_gb
      integer, parameter :: WORD=4
      call MPI_Comm_rank(comm, rank, _IERROR)
      _RETURN_UNLESS(rank == 0)
      call MPI_Comm_size(MPI_COMM_WORLD, npes, _IERROR)
      group = npes /spec%n_writers
      bw_gb = 1.e-9 * WORD * (spec%nx**2)*6*spec%n_levs / avg_time
      write(*,'(4(i6.0,","),3(f15.4,:,","))') spec%nx, spec%n_levs, spec%n_writers, group, avg_time, rel_std_time, bw_gb
      _RETURN(_SUCCESS)
   end subroutine report
Call graph
report calls mpi_comm_rank, mpi_comm_size, mapl_return, mapl_verify
mapl_return calls mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls report
time calls run
main calls run