run – MAPL
run Subroutine
54 statements
Source File
subroutine run(spec, rc)
Arguments
Type Intent Optional Attributes Name
type(BW_BenchmarkSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run(spec, rc)
      type(BW_BenchmarkSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      real :: tot_time
      real :: tot_time_sq
      real :: avg_time
      real :: std_time
      type(BW_Benchmark) :: benchmark
      integer :: writer_comm
      integer :: gather_comm
      integer :: i
      real :: t
      integer :: color, rank, npes
      call MPI_Comm_rank(MPI_COMM_WORLD, rank, _IERROR)
      call MPI_Comm_size(MPI_COMM_WORLD, npes, _IERROR)
      color = (rank*spec%n_writers) / npes
      call MPI_Comm_split(MPI_COMM_WORLD, color, 0, gather_comm, _IERROR)
      call MPI_Comm_rank(gather_comm, rank, _IERROR)
      call MPI_Comm_split(MPI_COMM_WORLD, rank, 0, writer_comm, _IERROR)
      if (rank /= 0) writer_comm = MPI_COMM_NULL
      _RETURN_IF(writer_comm == MPI_COMM_NULL)
      benchmark = make_BW_Benchmark(spec, writer_comm, _RC)
      call write_header(writer_comm, _RC)
      tot_time = 0
      tot_time_sq = 0
      associate (n => spec%n_tries)
        do i = 1, n
           t = time(benchmark, writer_comm, _RC)
           tot_time = tot_time + t
           tot_time_sq = tot_time_sq + t**2
        end do
        avg_time = tot_time / n
        std_time = -1 ! unless
        if (n > 1) then
           std_time = sqrt((tot_time_sq - spec%n_tries*avg_time**2)/(n-1))
        end if
      end associate
      call report(spec, avg_time, std_time, writer_comm, _RC)
      _RETURN(_SUCCESS)
   end subroutine run
Call graph
run calls mpi_comm_rank, mpi_comm_size, mpi_comm_split, make_bw_benchmark, mapl_return, mapl_verify, report, write_header
make_bw_benchmark calls mpi_comm_rank, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
report calls mpi_comm_rank, mpi_comm_size, mapl_return, mapl_verify
write_header calls mpi_comm_rank, mapl_return, mapl_verify
main calls run