test_ESMF_Time_from_ISO8601 – MAPL
test_ESMF_Time_from_ISO8601 Subroutine
11 statements
Source File
public subroutine test_ESMF_Time_from_ISO8601()
Arguments
None
Calls
Source Code
   subroutine test_ESMF_Time_from_ISO8601()
      character(len=*), parameter :: isostring = '1999-12-31T23:29:59'
      character(len=len(isostring)) :: actual
      type(ESMF_Time) :: time
      integer :: status
      call set_ESMF_Time_from_ISO8601(time, isostring, rc = status)
      @assertTrue(status == _SUCCESS, 'Failed to set ESMF_Time')
      call ESMF_TimeGet(time, timeStringISOFrac = actual, rc = status)
      @assertTrue(status == _SUCCESS, 'Failed to get isostring')
      @assertEqual(isostring, actual, 'ISO8601 strings do not match.')
   end subroutine test_ESMF_Time_from_ISO8601
Call graph
test_esmf_time_from_iso8601 calls ESMF_TimeGet, assertequal, asserttrue, set_esmf_time_from_iso8601
set_esmf_time_from_iso8601 calls ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception