test_parse_date – MAPL
test_parse_date Subroutine
13 statements
Source File
public subroutine test_parse_date()
Arguments
None
Calls
Contents
Source Code
test_parse_date
Source Code
   subroutine test_parse_date()
      type(date_fields) :: date
      date = parse_date('2022-07-07', DATE_DELIMITER)
      @assertTrue(date%is_valid_)
      @assertEqual(2022, date%year_)
      @assertEqual(7, date%month_)
      @assertEqual(7, date%day_)
      date = parse_date('20220707', DATE_DELIMITER)
      @assertTrue(date%is_valid_)
      @assertEqual(2022, date%year_)
      @assertEqual(7, date%month_)
      @assertEqual(7, date%day_)
   end subroutine test_parse_date
Call graph
test_parse_date calls assertequal, asserttrue, parse_date
parse_date calls date_fields, read_whole_number, undelimit
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
read_whole_number calls read_whole_number_indexed
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number