test_construct_time_fields_null – MAPL
test_construct_time_fields_null Subroutine
5 statements
Source File
public subroutine test_construct_time_fields_null()
Arguments
None
Calls
Contents
Source Code
test_construct_time_fields_null
Source Code
   subroutine test_construct_time_fields_null()
      type(time_fields) :: tf
      tf = time_fields()
      @assertFalse(tf % is_valid(), 'null tf should not be valid.')
   end subroutine test_construct_time_fields_null
Call graph
test_construct_time_fields_null calls assertfalse, time_fields
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit