test_string_to_integer_date_delimiters – MAPL
test_string_to_integer_date_delimiters Subroutine
8 statements
Source File
public subroutine test_string_to_integer_date_delimiters()
Arguments
None
Calls
Source Code
    subroutine test_string_to_integer_date_delimiters()
        character(len=*), parameter :: date_string = '2000-04-21'
        integer :: expected_date = -1
        integer :: actual_date = -2
        expected_date = 2000*YEAR_FACTOR + 4*MONTH_FACTOR + 21*DAY_FACTOR
        actual_date = string_to_integer_date(date_string)
        @assertEqual(expected_date, actual_date)
    end subroutine test_string_to_integer_date_delimiters
Call graph
test_string_to_integer_date_delimiters calls assertequal, string_to_integer_date
string_to_integer_date calls mapl_return
mapl_return calls at, insert, mapl_throw_exception