test_construct_date_fields_null – MAPL
test_construct_date_fields_null Subroutine
5 statements
Source File
public subroutine test_construct_date_fields_null()
Arguments
None
Calls
Contents
Source Code
test_construct_date_fields_null
Source Code
   subroutine test_construct_date_fields_null()
      type(date_fields) :: df
      df = date_fields()
      @assertFalse(df % is_valid(), 'null df should not be valid.')
   end subroutine test_construct_date_fields_null
Call graph
test_construct_date_fields_null calls assertfalse, date_fields
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
parse_date calls date_fields, read_whole_number, undelimit