test_is_valid_month – MAPL
test_is_valid_month Subroutine
9 statements
Source File
public subroutine test_is_valid_month()
Arguments
None
Calls
Source Code
   subroutine test_is_valid_month()
      integer :: i
      @assertFalse(is_valid_month(0))
      @assertFalse(is_valid_month(-1))
      @assertFalse(is_valid_month(13))
      do i = 1, 12
         @assertTrue(is_valid_month(i))
      end do
   end subroutine test_is_valid_month
Call graph
test_is_valid_month calls assertfalse, asserttrue, is_valid_month
is_valid_month calls is_between