test_are_valid_date_fields – MAPL
test_are_valid_date_fields Subroutine
7 statements
Source File
public subroutine test_are_valid_date_fields()
Arguments
None
Calls
Contents
Source Code
test_are_valid_date_fields
Source Code
   subroutine test_are_valid_date_fields
      type(date_fields) :: df
      df = date_fields(2023, 4, 25)
      @assertTrue(df % is_valid(), 'df should be valid.')
      df = date_fields(2023, 4, 31)
      @assertFalse(df % is_valid(), 'df should not be valid.')
   end subroutine test_are_valid_date_fields
Call graph
test_are_valid_date_fields calls assertfalse, asserttrue, date_fields
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
parse_date calls date_fields, read_whole_number, undelimit