test_count_nodes_depth_0 – MAPL
test_count_nodes_depth_0 Subroutine
13 statements
Source File
public subroutine test_count_nodes_depth_0()
Arguments
None
Calls
Source Code
   subroutine test_count_nodes_depth_0()
      type (MeterNode), target :: node
      class (AbstractMeterNodeIterator), allocatable :: iter
      integer :: count
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      count = 0
      allocate(iter, source=node%begin())
      do while (iter /= node%end())
         count = count + 1
         call iter%next()
      end do
      @assertEqual(node%get_num_nodes(), count)
   end subroutine test_count_nodes_depth_0
Call graph
test_count_nodes_depth_0 calls assertequal, next, begin, get_num_nodes