test_get_year_field – MAPL
test_get_year_field Subroutine
7 statements
Source File
public subroutine test_get_year_field()
Arguments
None
Calls
Contents
Source Code
test_get_year_field
Source Code
   subroutine test_get_year_field
      type(date_fields) :: df
      integer :: d = 23, m = 4, y = 2023
      df = date_fields(y, m, d)
      @assertTrue(df % is_valid(), 'Failed to initialize df')
      @assertEqual(y, df % year(), 'Wrong year')
   end subroutine test_get_year_field
Call graph
test_get_year_field calls assertequal, asserttrue, date_fields
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
parse_date calls date_fields, read_whole_number, undelimit