test_convert_to_ISO8601DateTime – MAPL
test_convert_to_ISO8601DateTime Subroutine
27 statements
Source File
public subroutine test_convert_to_ISO8601DateTime()
Arguments
None
Calls
Contents
Source Code
test_convert_to_ISO8601DateTime
Source Code
   subroutine test_convert_to_ISO8601DateTime()
      character(len=*), parameter :: expected_A = '2023-04-23T21:05:37'
      character(len=*), parameter :: expected_B = '2023-04-23T21:05:37.337'
      character(len=:), allocatable :: output
      character(len=MAX_LEN) :: actual
      integer :: status
      call convert_to_ISO8601DateTime('2023-04-23 21:05:37', output, rc = status)
      actual = trim(output)
      @assertEqual(status, 0, 'Convert failed')
      @assertEqual(expected_A, trim(actual), 'Datetime strings do not match.')
      call convert_to_ISO8601DateTime('20230423 210537', output, rc = status)
      actual = trim(output)
      @assertEqual(status, 0, 'Convert failed')
      @assertEqual(expected_A, trim(actual), 'Datetime strings do not match.')
      call convert_to_ISO8601DateTime('2023-04-23 21:05:37.337', output, rc = status)
      actual = trim(output)
      @assertEqual(status, 0, 'Convert failed')
      @assertEqual(expected_B, trim(actual), 'Datetime strings do not match.')
      call convert_to_ISO8601DateTime('20230423210537337', output, rc = status)
      actual = trim(output)
      @assertEqual(status, 0, 'Convert failed')
      @assertEqual(expected_B, trim(actual), 'Datetime strings do not match.')
      call convert_to_ISO8601DateTime('2023-4-23 21:05:37', output, rc = status)
      @assertFalse(status == 0, 'Failed to catch illegal value.')
      call convert_to_ISO8601DateTime('2023-04-23 21:5:37', output, rc = status)
      @assertFalse(status == 0, 'Failed to catch illegal value.')
   end subroutine test_convert_to_ISO8601DateTime
Call graph
test_convert_to_iso8601datetime calls assertequal, assertfalse, convert_to_iso8601datetime
convert_to_iso8601datetime calls mapl_assert, mapl_return, undelimit_all
mapl_return calls mapl_throw_exception
undelimit_all calls is_digit