test_parse_time – MAPL
test_parse_time Subroutine
17 statements
Source File
public subroutine test_parse_time()
Arguments
None
Calls
Contents
Source Code
test_parse_time
Source Code
   subroutine test_parse_time()
      type(time_fields) :: time
      time = parse_time('17:41:07.513Z', TIME_DELIMITER)
      @assertTrue(time%is_valid_)
      @assertEqual(17, time%hour_)
      @assertEqual(41, time%minute_)
      @assertEqual(7, time%second_)
      @assertEqual(513, time%millisecond_)
      @assertEqual(0, time%timezone_offset_)
      time = parse_time('174107.513Z', TIME_DELIMITER)
      @assertTrue(time%is_valid_)
      @assertEqual(17, time%hour_)
      @assertEqual(41, time%minute_)
      @assertEqual(7, time%second_)
      @assertEqual(513, time%millisecond_)
      @assertEqual(0, time%timezone_offset_)
   end subroutine test_parse_time
Call graph
test_parse_time calls assertequal, asserttrue, parse_time
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string