test_connect_with_unused_process – MAPL
test_connect_with_unused_process Subroutine
33 statements
Source File
public subroutine test_connect_with_unused_process(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Contents
Source Code
test_connect_with_unused_process
Source Code
   subroutine test_connect_with_unused_process(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DirectoryService) :: ds
      integer :: comm
      integer :: color, key
      integer :: ierror
      type (MockServer) :: mock_server
      type (MockClient) :: mock_client
      ds = DirectoryService(this%getMpiCommunicator())
      if (this%getProcessRank() == 3) then
         color = 5
      else
         color = this%getProcessRank()/3
         key = 0
      end if
      call MPI_Comm_split(this%getMpiCommunicator(), color, key, comm, ierror)
      @assertEqual(0, ierror)
      select case (color)
      case (1) ! server
         mock_server = MockServer(comm)
         call ds%publish(PortInfo('input', mock_server), mock_server)
         select case (this%getProcessRank())
         case (4) ! have one
            call ds%connect_to_client('input', mock_server)
         case (5)
            call ds%connect_to_client('input', mock_server)
         end select
      case (0) ! client
         mock_client = MockClient()
         call ds%connect_to_server('input', mock_client, comm)
      end select
      call ds%free_directory_resources()
   end subroutine test_connect_with_unused_process
Call graph
test_connect_with_unused_process calls assertequal, connect_to_client, connect_to_server, free_directory_resources, getmpicommunicator, getprocessrank, mpi_comm_split, publish