test_is_valid_minute – MAPL
test_is_valid_minute Subroutine
10 statements
Source File
public subroutine test_is_valid_minute()
Arguments
None
Calls
Source Code
   subroutine test_is_valid_minute()
      integer, parameter :: IMIN = 0
      integer, parameter :: IMAX = 59
      integer :: i
      do i= IMIN, IMAX
         @assertTrue(is_valid_minute(i))
      end do
      @assertFalse(is_valid_minute(IMAX+1))
      @assertFalse(is_valid_minute(IMIN-1))
   end subroutine test_is_valid_minute
Call graph
test_is_valid_minute calls assertfalse, asserttrue, is_valid_minute
is_valid_minute calls is_between