#define _RC rc=status
#define _RETURN(status) if(present(rc)) rc=status
#define _SUCCESS ESMF_SUCCESS
#define _FAILURE _SUCCESS-1
module mapl3g_acg3
   use mapl3g_Generic, only: MAPL_GridCompAddFieldSpec
   use mapl3g_State_API, only: MAPL_StateGetPointer
   use mapl_ErrorHandling
   use mapl_KeywordEnforcer
   use esmf, only: ESMF_STATEITEM_FIELD, ESMF_SUCCESS, ESMF_STATEINTENT_IMPORT, ESMF_STATEINTENT_EXPORT, ESMF_STATEINTENT_INTERNAL
   use esmf, only: ESMF_State, ESMF_GridComp, Esmf_StateIntent_Flag, ESMF_Field
   use mapl3g_VerticalStaggerLoc

   implicit none(type, external) 

   public :: add_field_spec
   public :: get_pointers
   private

! ACG3 is hardwired to use these three ESMF_State variable names from
! category headings in acg/acg3.acg.
   type(ESMF_State) :: IMPORT, EXPORT, INTERNAL
   type(ESMF_GridComp) :: gc
   character(len=*), parameter :: comp_name = 'comp_name'

contains

   subroutine add_field_spec(rc)
      integer, optional, intent(out) :: rc
      integer :: status
! These are the files generated by ACG3
#include "acg3_imports.h"
#include "acg3_exports.h"
#include "acg3_internals.h"
      _RETURN(status)
   end subroutine add_field_spec

   subroutine get_pointers(rc)
      integer, optional, intent(out) :: rc
      integer :: status
! These are the files generated by ACG3
#include "acg3_declare_pointers.h"
#include "acg3_get_pointers.h"
      _RETURN(status)
   end subroutine get_pointers

end module mapl3g_acg3
