activate_dependencies – MAPL
activate_dependencies Subroutine
17 statements
Source File
private subroutine activate_dependencies(spec, registry, rc)
Arguments
Type Intent Optional Attributes Name
class(StateItemSpec), intent(in) :: spec
type(HierarchicalRegistry), intent(in), target :: registry
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine activate_dependencies(spec, registry, rc)
      class(StateItemSpec), intent(in) :: spec
      type(HierarchicalRegistry), target, intent(in) :: registry
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      type(ActualPtVector) :: dependencies
      class(StateItemSpec), pointer :: dep_spec
      dependencies = spec%get_dependencies()
      do i = 1, dependencies%size()
         dep_spec => registry%get_item_spec(dependencies%of(i), _RC)
         call dep_spec%set_active()
      end do
      _RETURN(_SUCCESS)
   end subroutine activate_dependencies
Call graph
activate_dependencies calls of, get_dependencies, get_item_spec, mapl_return, mapl_verify, set_active
get_item_spec calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
map_at_rc calls map_find
connect_sibling calls activate_dependencies
connect calls connect_sibling