add_variable – MAPL
add_variable Subroutine
37 statements
Source File
private subroutine add_variable(this, var_name, var, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: var_name
class(Variable), intent(in), target :: var
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_variable(this, var_name, var, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: var_name
      class (Variable), target, intent(in) :: var
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (StringVector), pointer :: dims
      type (StringVectorIterator) :: iter
      integer, pointer :: dim_this
      character(len=:), pointer :: dim_name
      type (UnlimitedEntity), pointer :: const_value_ptr
      integer, allocatable :: shp(:), shp_const(:)
      integer :: empty(0)
      ! ensure all of var's dimensions are defined
      shp = empty
      dims => var%get_dimensions()
      iter = dims%begin()
      do while (iter /= dims%end())
         dim_name => iter%get()
         dim_this => this%dimensions%at(dim_name)
         _ASSERT( associated(dim_this),"FileMetadata::add_variable() - undefined dimension: " // dim_name)
         shp =[shp,dim_this]
         call iter%next()
      end do
      const_value_ptr => var%get_const_value()
      if ( .not. const_value_ptr%is_empty() ) then
         shp_const = const_value_ptr%get_shape()
         _ASSERT( all(shp == shp_const), "const_value shape does not match dims")
      endif
      call this%variables%insert(var_name, var)
      call this%order%push_back(var_name)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_variable
Call graph
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
add_fvar calls add_variable
add_metadata calls add_variable
add_metadata_route_handle calls add_variable
add_time_to_metadata calls add_variable
append_metadata calls add_variable
append_vertical_metadata calls add_variable
create_file_metada calls add_variable
create_metadata_variable calls add_variable
createvariable calls add_variable
initialize_ calls add_variable
init calls add_variable
inq_variables calls add_variable
mapl_bundlewritencpar calls add_variable
merge calls add_variable
run calls add_variable
setup calls add_variable
test_add_variable calls add_variable
test_equal_diff_variables calls add_variable
test_merge_meta calls add_variable
test_serialize calls add_variable
test_var_dims_defined calls add_variable
test_write_read_simple_variable calls add_variable
test_write_read_variable_attribute calls add_variable
transfer_metadata calls add_variable
typesafe_make_file_metadata calls add_variable
main calls add_variable