add_to_state – MAPL
add_to_state Subroutine
9 statements
Source File
private subroutine add_to_state(this, multi_state, actual_pt, rc)
$ alias = ESMF_NamedAlias(this%payload, name=short_name, rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/generic3g/specs/StateSpec.F90”,155 ,rc)) return $ call ESMF_StateAdd(state, this%payload, short_name, rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/generic3g/specs/StateSpec.F90”,156 ,rc)) return $
Type Bound
StateSpec
Arguments
Type Intent Optional Attributes Name
class(StateSpec), intent(in) :: this
type(MultiState), intent(inout) :: multi_state
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_to_state(this, multi_state, actual_pt, rc)
      class(StateSpec), intent(in) :: this
      type(MultiState), intent(inout) :: multi_state
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      type(ESMF_State) :: alias
      integer :: status
      _FAIL('unimplemented')
!!$      alias = ESMF_NamedAlias(this%payload, name=short_name, _RC)
!!$      call ESMF_StateAdd(state, this%payload, short_name, _RC)
!!$
   end subroutine add_to_state
Call graph
add_to_state calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize