add_metadata_route_handle – MAPL
add_metadata_route_handle Subroutine
108 statements
Source File
private subroutine add_metadata_route_handle(this, bundle, timeInfo, vdata, rc)
Type Bound
StationSampler
Arguments
Type Intent Optional Attributes Name
class(StationSampler), intent(inout) :: this
type(ESMF_FieldBundle), intent(in) :: bundle
type(timeData), intent(inout) :: timeInfo
type(verticalData), intent(inout), optional :: vdata
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine add_metadata_route_handle (this,bundle,timeInfo,vdata,rc)
    class(StationSampler),  intent(inout)       :: this
    type(ESMF_FieldBundle), intent(in)          :: bundle
    type(TimeData),         intent(inout)       :: timeInfo
    type(VerticalData), optional, intent(inout) :: vdata
    integer, optional, intent(out)              :: rc
    type(variable)   :: v
    type(ESMF_Grid)  :: grid
    type(ESMF_Field) :: field
    integer          :: fieldCount
    integer          :: field_rank
    integer          :: nstation
    logical          :: is_present
    integer          :: ub(ESMF_MAXDIM)
    integer          :: lb(ESMF_MAXDIM)
    logical          :: do_vertical_regrid
    integer          :: status
    integer          :: i
    character(len=ESMF_MAXSTR), allocatable ::  fieldNameList(:)
    character(len=ESMF_MAXSTR) :: var_name, long_name, units, vdims
    type(ESMF_Info) :: infoh
    !__ 1. metadata add_dimension,
    !     add_variable for time, latlon, station
    !
    this%bundle = bundle
    nstation = this%nstation
    if (present(vdata)) then
       this%vdata = vdata
    else
       this%vdata = VerticalData(_RC)
    end if
    call this%vdata%append_vertical_metadata(this%fmd,this%bundle,_RC) ! specify lev in fmd
    do_vertical_regrid = (this%vdata%regrid_type /= VERTICAL_METHOD_NONE)
    if (this%vdata%regrid_type == VERTICAL_METHOD_ETA2LEV) then
       call this%vdata%get_interpolating_variable(this%bundle,_RC)
    endif
    call timeInfo%add_time_to_metadata(this%fmd,_RC) ! specify time in fmd
    this%time_info = timeInfo
    call this%fmd%add_dimension('station_index',nstation)
    v = Variable(type=pFIO_REAL32, dimensions='station_index')
    call v%add_attribute('long_name','longitude')
    call v%add_attribute('unit','degree_east')
    call this%fmd%add_variable('longitude',v)
    v = Variable(type=pFIO_REAL32, dimensions='station_index')
    call v%add_attribute('long_name','latitude')
    call v%add_attribute('unit','degree_north')
    call this%fmd%add_variable('latitude',v)
    v = Variable(type=pFIO_INT32, dimensions='station_index')
    call this%fmd%add_variable('station_id',v)
    v = Variable(type=pFIO_STRING, dimensions='station_index')
    call v%add_attribute('long_name','station name')
    call this%fmd%add_variable('station_name',v)
    !__ 2. filemetadata: extract field from bundle, add_variable
    !
    call ESMF_FieldBundleGet(bundle, fieldCount=fieldCount, _RC)
    allocate (fieldNameList(fieldCount), _STAT)
    call ESMF_FieldBundleGet(bundle, fieldNameList=fieldNameList, _RC)
    do i=1, fieldCount
       var_name=trim(fieldNameList(i))
       call ESMF_FieldBundleGet(bundle,var_name,field=field,_RC)
       call ESMF_FieldGet(field,rank=field_rank,_RC)
       call ESMF_InfoGetFromHost(field,infoh,_RC)
       is_present = ESMF_InfoIsPresent(infoh, 'LONG_NAME',_RC)
       if ( is_present ) then
          call ESMF_InfoGet(infoh, KEY="LONG_NAME",VALUE=long_name, _RC)
       else
          long_name = var_name
       endif
       is_present = ESMF_InfoIsPresent(infoh, 'UNITS',_RC)
       if ( is_present ) then
          call ESMF_InfoGet(infoh, KEY="UNITS",VALUE=units, _RC)
       else
          units = 'unknown'
       endif
       if (field_rank==2) then
          vdims = "station_index,time"
          v = variable(type=PFIO_REAL32,dimensions=trim(vdims),chunksizes=[nstation,1])
       else if (field_rank==3) then
          vdims = "lev,station_index,time"
          call ESMF_FieldGet(field,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
          v = variable(type=PFIO_REAL32,dimensions=trim(vdims),chunksizes=[ub(1)-lb(1)+1,1,1])
       end if
       call v%add_attribute('units',         trim(units))
       call v%add_attribute('long_name',     trim(long_name))
       call v%add_attribute('missing_value', MAPL_UNDEF)
       call v%add_attribute('_FillValue',    MAPL_UNDEF)
       call v%add_attribute('valid_range',   (/-MAPL_UNDEF,MAPL_UNDEF/))
       call this%fmd%add_variable(trim(var_name),v,_RC)
    end do
    deallocate (fieldNameList)
    !__ 3. locstream route handle
    !
    call ESMF_FieldBundleGet(bundle,grid=grid,_RC)
    this%regridder = LocStreamRegridder(grid,this%esmf_ls,_RC)
    _RETURN(_SUCCESS)
  end subroutine add_metadata_route_handle
Call graph
add_metadata_route_handle calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, esmf_fieldbundleget, esmf_fieldget, add_attribute, add_dimension, add_time_to_metadata, add_variable, append_vertical_metadata, get_interpolating_variable, mapl_return, mapl_verify
add_dimension calls mapl_return, insert
add_time_to_metadata calls add_dimension, add_variable, mapl_return, mapl_verify, define_time_variable
add_variable calls mapl_return, at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
append_vertical_metadata calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, esmf_fieldbundleget, esmf_fieldget, add_attribute, add_dimension, add_variable, mapl_return, mapl_verify, mapl_assert, add_const_value
get_interpolating_variable calls esmf_fieldbundleget, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
initialize calls add_metadata_route_handle