add_to_state – MAPL
add_to_state Subroutine
21 statements
Source File
private subroutine add_to_state(this, multi_state, actual_pt, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
type(MultiState), intent(inout) :: multi_state
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_to_state(this, multi_state, actual_pt, rc)
      class(FieldSpec), intent(in) :: this
      type(MultiState), intent(inout) :: multi_state
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      type(ESMF_Field) :: alias
      integer :: status
      type(ESMF_State) :: state, substate
      character(:), allocatable :: short_name
      call multi_state%get_state(state, actual_pt%get_state_intent(), _RC)
      call get_substate(state, actual_pt%get_comp_name(), substate=substate, _RC)
      short_name = actual_pt%get_esmf_name()
      alias = ESMF_NamedAlias(this%payload, name=short_name, _RC)
      call ESMF_StateAdd(substate, [alias], _RC)
      _RETURN(_SUCCESS)
   end subroutine add_to_state
Call graph
add_to_state calls ESMF_NamedAlias, esmf_stateadd, get_state, get_comp_name, get_esmf_name, get_state_intent, get_substate, mapl_return, mapl_verify
get_comp_name calls get_comp_name
get_esmf_name calls get_esmf_name, get_extension_string, is_extension
get_state_intent calls get_state_intent
get_substate calls esmf_stateadd, mapl_return, mapl_verify, esmf_statecreate, esmf_stateget, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
get_extension_string calls is_extension
get_state_by_esmf_intent calls get_state, mapl_return, mapl_verify
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
test_vertical calls add_to_state