add_item_spec_actual – MAPL
add_item_spec_actual Subroutine
16 statements
Source File
private subroutine add_item_spec_actual(this, actual_pt, spec, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(ActualConnectionPt), intent(in) :: actual_pt
class(StateItemSpec), intent(in), target :: spec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_item_spec_actual(this, actual_pt, spec, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(ActualConnectionPt), intent(in) :: actual_pt
      class(StateItemSpec), target, intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      class(StateItemSpec), pointer :: internal_spec
      _ASSERT(.not. this%has_item_spec(actual_pt), 'Duplicate item name.')
      call this%local_specs%push_back(spec)
      internal_spec => this%local_specs%back()
      call this%link_item_spec_actual(actual_pt, internal_spec, _RC)
      ! Internal state items are always active.
      if (actual_pt%is_internal()) call internal_spec%set_active()
      _RETURN(_SUCCESS)
   end subroutine add_item_spec_actual
Call graph
add_item_spec_actual calls mapl_assert, has_item_spec, is_internal, link_item_spec_actual, mapl_return, mapl_verify, set_active, vector_back, vector_push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
is_internal calls is_internal, get_state_intent
link_item_spec_actual calls mapl_assert, has_item_spec, mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
map_insert_pair calls insert
vector_resize_size_kind calls reserve
add_item_spec_virtual calls add_item_spec
add_item_spec_virtual_override calls add_item_spec
extend_ calls add_item_spec
init_post_advertise calls add_item_spec
initialize_advertise calls add_item_spec
test_add_item_duplicate_fail calls add_item_spec
test_connect calls add_item_spec
test_connect_chain calls add_item_spec
test_create_extension calls add_item_spec
test_do_not_propagate_import calls add_item_spec
test_e2e_preserve_actual_pt calls add_item_spec
test_export_to_export_connection calls add_item_spec
test_get_item_spec_found calls add_item_spec
test_get_item_spec_multi calls add_item_spec
test_import_from_child calls add_item_spec
test_import_from_parent calls add_item_spec
test_internal_activation calls add_item_spec
test_internal_to_export_connection calls add_item_spec
test_multi_import calls add_item_spec
test_propagate_import calls add_item_spec
test_sibling_activation calls add_item_spec
connect_sibling calls extend_
initialize calls initialize_advertise
connect calls connect_sibling