add_variable – MAPL
add_variable Subroutine
41 statements
Source File
public subroutine add_variable(metadata, field, rc)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout) :: metadata
type(ESMF_Field), intent(in) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_variable(metadata, field,  rc)
      type(ESMF_Field), intent(in) :: field
      type(FileMetaData), intent(inout) :: metadata
      integer, intent(out), optional :: rc
      type(Variable) :: v
      integer :: status
      character(len=:), allocatable :: dims
      type(ESMF_TYPEKIND_FLAG) :: typekind
      integer :: pfio_type
      type(ESMF_Info) :: info
      character(len=:), allocatable :: char
      character(len=ESMF_MAXSTR) :: fname
      type(MAPLGeom), pointer :: mapl_geom
      type(StringVector) :: grid_variables
      type(ESMF_Geom) :: esmfgeom
      call ESMF_FieldGet(field, geom=esmfgeom, _RC)
      mapl_geom => get_mapl_geom(esmfgeom, _RC)
      grid_variables = mapl_geom%get_gridded_dims()
      dims = string_vec_to_comma_sep(grid_variables)
      dims = 'lon,lat'
      call ESMF_FieldGet(field, name=fname, typekind = typekind, _RC)
      ! add vertical dimension
      ! add any ungridded dimensions
      ! add time dimension
      dims = dims//",time"
      pfio_type = esmf_to_pfio_type(typekind ,_RC)
      v = Variable(type=pfio_type, dimensions=dims)
      call ESMF_InfoGetFromHost(field, info, _RC)
      call ESMF_InfoGetCharAlloc(info, 'MAPL/units', char, _RC)
      call v%add_attribute('units',char)
      call ESMF_InfoGetCharAlloc(info, 'MAPL/standard_name', char, _RC)
      call v%add_attribute('long_name',char)
      call metadata%add_variable(trim(fname), v, _RC)
      _RETURN(_SUCCESS)
   end subroutine add_variable
Call graph
add_variable calls ESMF_InfoGetCharAlloc, ESMF_InfoGetFromHost, esmf_fieldget, get_gridded_dims, add_attribute, add_variable, esmf_to_pfio_type, get_mapl_geom, mapl_return, mapl_verify, string_vec_to_comma_sep
esmf_to_pfio_type calls mapl_return, mapl_assert
get_mapl_geom calls mapl_return, mapl_verify, get_geom_manager, get_mapl_geom_from_id, mapl_geomgetid
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_vec_to_comma_sep calls begin, next, of
add_variables calls add_variable
bundle_to_metadata calls add_variables