add_import_coupler – MAPL
add_import_coupler Subroutine
7 statements
Source File
private subroutine add_import_coupler(this, actual_pt, coupler)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
type(ActualConnectionPt), intent(in) :: actual_pt
type(GriddedComponentDriver), intent(in) :: coupler
Calls
Called by
Source Code
   subroutine add_import_coupler(this, actual_pt, coupler)
      class(HierarchicalRegistry), target, intent(inout) :: this
      type(ActualConnectionPt), intent(in) :: actual_pt
      type(GriddedComponentDriver), intent(in) :: coupler
      integer :: status
      call this%import_couplers%insert(actual_pt, coupler)
   end subroutine add_import_coupler
Call graph
add_import_coupler calls insert
map_insert_pair calls insert
connect_sibling calls add_import_coupler
connect calls connect_sibling