add_state_extension – MAPL
add_state_extension Subroutine
26 statements
Source File
private subroutine add_state_extension(this, extension_pt, src_spec, extension, source_coupler, rc)
Uses
mapl3g_ESMF_Subset
mapl3g_MultiState
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
type(ActualConnectionPt), intent(in) :: extension_pt
class(StateItemSpec), intent(in) :: src_spec
class(StateItemSpec), intent(in) :: extension
type(GriddedComponentDriver), intent(in), optional, target :: source_coupler
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_state_extension(this, extension_pt, src_spec, extension, source_coupler, rc)
      use mapl3g_ESMF_Subset, only: ESMF_Clock
      use mapl3g_MultiState
      class(HierarchicalRegistry), target, intent(inout) :: this
      type(ActualConnectionPt), intent(in) :: extension_pt
      class(StateItemSpec), intent(in) :: src_spec
      class(StateItemSpec), intent(in) :: extension
      type(GriddedComponentDriver), target, optional, intent(in) :: source_coupler
      integer, optional, intent(out) :: rc
      integer :: status
      class(ExtensionAction), allocatable :: action
      type(GriddedComponentDriver), pointer :: new_driver
      type(ESMF_GridComp) :: new_coupler
      type(ESMF_Clock) :: clock
      action = src_spec%make_action(extension, _RC)
      new_coupler = make_coupler(action, source_coupler, _RC)
      ! Need to ensure the stored copy of driver is kept and others are just pointers.
      allocate(new_driver)
      call this%export_couplers%insert(extension_pt, new_driver)
      deallocate(new_driver)
      new_driver => this%export_couplers%of(extension_pt)
      ! TODO: need to create clock and multi-state.  But this is the wrong layer for such a thing.
      new_driver = GriddedComponentDriver(new_coupler, clock, MultiState())
      _RETURN(_SUCCESS)
   end subroutine add_state_extension
Call graph
add_state_extension calls insert, make_action, make_coupler, map_of, mapl_return, mapl_verify
make_action calls mapl_assert
make_coupler calls mapl_return, mapl_verify, ESMF_GridCompCreate, esmf_gridcompsetservices, attach_coupler_meta, get_coupler_meta
map_of calls insert, map_s_iter_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
attach_coupler_meta calls mapl_return, mapl_assert, mapl_usercompsetinternalstate
get_coupler_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
get_error_message calls at, insert
map_insert_pair calls insert
map_s_iter_of calls map_s_get_value
mapl_throw_exception calls initialize
map_s_insert_initializer_list calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
extend_ calls add_state_extension
connect_sibling calls extend_
connect calls connect_sibling