add_extension_pt – MAPL
add_extension_pt Subroutine
13 statements
Source File
private subroutine add_extension_pt(this, virtual_pt, actual_pt)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
type(VirtualConnectionPt), intent(in) :: virtual_pt
type(ActualConnectionPt), intent(in) :: actual_pt
Calls
Called by
Source Code
   subroutine add_extension_pt(this, virtual_pt, actual_pt)
      class(HierarchicalRegistry), target, intent(inout) :: this
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      type(ActualConnectionPt), intent(in) :: actual_pt
      type(ActualPtVector), pointer :: actual_pts
      associate (extensions => this%virtual_pts)
        if (extensions%count(virtual_pt) == 0) then
           call extensions%insert(virtual_pt, ActualPtVector())
        end if
        actual_pts => this%virtual_pts%of(virtual_pt)
        call actual_pts%push_back(actual_pt)
      end associate
   end subroutine add_extension_pt
Call graph
add_extension_pt calls insert, map_of, vector_push_back
map_of calls insert, map_s_iter_of
vector_push_back calls resize, vector_grow_to
map_insert_pair calls insert
map_s_iter_of calls map_s_get_value
vector_grow_to calls vector_capacity, vector_set_capacity
map_s_insert_initializer_list calls insert
vector_resize_size_kind calls reserve
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt, link_item_spec
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual
connect_export_to_export calls link_item_spec
connect calls connect_export_to_export
initialize_advertise calls propagate_exports, propagate_unsatisfied_imports
propagate_exports_all calls propagate_exports
propagate_exports_child calls propagate_exports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_exports, propagate_unsatisfied_imports