add_routehandle – MAPL
add_routehandle Subroutine
16 statements
Source File
public subroutine add_routehandle(this, spec, rc)
Type Bound
RoutehandleManager
Arguments
Type Intent Optional Attributes Name
class(RoutehandleManager), intent(inout), target :: this
type(RoutehandleSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_routehandle(this, spec, rc)
      class(RoutehandleManager), target, intent(inout) :: this
      type(RoutehandleSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      type(ESMF_Routehandle) :: routehandle
      integer :: status
      associate (b => this%specs%begin(), e => this%specs%end())
          _ASSERT(find(b, e, spec) == e, "Spec already exists in registry.")
      end associate
      routehandle = make_routehandle(spec, _RC)
      call this%specs%push_back(spec)
      call this%routehandles%push_back(routehandle)
      _RETURN(_SUCCESS)
   end subroutine add_routehandle
Call graph
add_routehandle calls find, make_routehandle, mapl_assert, mapl_return, mapl_verify, vector_begin, vector_push_back
make_routehandle calls make_routehandle_from_param
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
make_routehandle_from_param calls mapl_return, mapl_verify, ESMF_FieldRegridStore, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
get_routehandle calls add_routehandle
make_regridder_typesafe calls get_routehandle
make_regridder calls make_regridder