add_to_bundle – MAPL
add_to_bundle Subroutine
7 statements
Source File
private subroutine add_to_bundle(this, bundle, rc)
Type Bound
ServiceSpec
Arguments
Type Intent Optional Attributes Name
class(ServiceSpec), intent(in) :: this
type(ESMF_FieldBundle), intent(inout) :: bundle
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_to_bundle(this, bundle, rc)
      class(ServiceSpec), intent(in) :: this
      type(ESMF_FieldBundle), intent(inout) :: bundle
      integer, optional, intent(out) :: rc
      integer :: status
      _FAIL('ServiceService::Cannot nest bundles.')
   end subroutine add_to_bundle
Call graph
add_to_bundle calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize