add_item_spec_virtual – MAPL
add_item_spec_virtual Subroutine
13 statements
Source File
private subroutine add_item_spec_virtual(this, virtual_pt, spec, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(VirtualConnectionPt), intent(in) :: virtual_pt
class(StateItemSpec), intent(in), target :: spec
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_item_spec_virtual(this, virtual_pt, spec, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      class(StateItemSpec), target, intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(ActualConnectionPt) :: actual_pt
      actual_pt = ActualConnectionPt(virtual_pt)
      call this%add_item_spec(virtual_pt, spec, actual_pt, _RC)
      _RETURN(_SUCCESS)
   end subroutine add_item_spec_virtual
Call graph
add_item_spec_virtual calls add_item_spec, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_item_spec_actual calls mapl_return, mapl_verify, mapl_assert, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
is_internal calls is_internal
link_item_spec_actual calls mapl_return, mapl_assert, has_item_spec, insert
vector_push_back calls resize, vector_grow_to