add_ungridded_dimensions – MAPL
add_ungridded_dimensions Subroutine
30 statements
Source File
public subroutine add_ungridded_dimensions(bundle, metadata, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
type(FileMetadata), intent(inout) :: metadata
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_ungridded_dimensions(bundle, metadata, rc)
      type(ESMF_FieldBundle), intent(in) :: bundle
      type(FileMetaData), intent(inout) :: metadata
      integer, optional, intent(out) :: rc
      integer :: status
      type(UngriddedDims) :: field_ungridded_dims, ungridded_dims
      type(UngriddedDim) :: u
      integer :: i, j
      type(ESMF_Field) :: field
      type(ESMF_Field), allocatable :: fieldList(:)
      type(StringSet) :: dim_names
      character(:), allocatable :: dim_name
      logical :: is_new
      call MAPL_FieldBundleGet(bundle, fieldList=fieldList, _RC)
      do i = 1, size(fieldList)
         call MAPL_FieldGet(fieldList(i), ungridded_dims=field_ungridded_dims, _RC)
         do j = 1, field_ungridded_dims%get_num_ungridded()
            u = ungridded_dims%get_ith_dim_spec(i)
            dim_name = u%get_name()
            call dim_names%insert(dim_name, is_new=is_new)
            if (is_new) then
               call metadata%add_dimension(u%get_name(), u%get_extent())
            end if
         end do
      end do
      _RETURN(_SUCCESS)
   end subroutine add_ungridded_dimensions
Call graph
add_ungridded_dimensions calls insert, mapl_fieldbundleget, mapl_fieldget, add_dimension, get_extent, get_ith_dim_spec, get_name, get_num_ungridded, mapl_return, mapl_verify
mapl_return calls insert, at, mapl_throw_exception
mapl_verify calls mapl_throw_exception
bundle_to_metadata calls add_ungridded_dimensions