add_phase_ – MAPL
add_phase_ Subroutine
18 statements
Source File
private subroutine add_phase_(phases_map, method_flag, phase_name, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(MethodPhasesMap), intent(inout) :: phases_map
type(ESMF_Method_Flag), intent(in) :: method_flag
character(len=*), intent(in) :: phase_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_phase_(phases_map, method_flag, phase_name, unusable, rc)
      type(MethodPhasesMap), intent(inout) :: phases_map
      type(ESMF_Method_Flag), intent(in) :: method_flag
      character(len=*), intent(in) :: phase_name
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) ::rc
      type(StringVector), pointer :: phase_names
      _ASSERT(phases_map%count(method_flag) > 0, "Unsupported value for 'method_flag'.")
      if (phases_map%count(method_flag) == 0) then
         call phases_map%insert(method_flag, StringVector())
      end if
      phase_names => phases_map%of(method_flag)
      _ASSERT(find(phase_names%begin(), phase_names%end(), phase_name) == phase_names%end(), "duplicate phase name: " // phase_name)
      call phase_names%push_back(phase_name)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_phase_
Call graph
add_phase_ calls begin, find, mapl_assert, insert, map_of, mapl_return, push_back, stringvector
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
map_of calls insert, map_s_iter_of
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
map_s_iter_of calls map_s_get_value
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_s_insert_initializer_list calls insert
add_phase calls add_phase_
set_entry_point calls add_phase
gridcomp_set_entry_point calls set_entry_point
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point