add_to_state – MAPL
add_to_state Subroutine
9 statements
Source File
private subroutine add_to_state(this, multi_state, actual_pt, rc)
Type Bound
InvalidSpec
Arguments
Type Intent Optional Attributes Name
class(InvalidSpec), intent(in) :: this
type(MultiState), intent(inout) :: multi_state
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_to_state(this, multi_state, actual_pt, rc)
      class(InvalidSpec), intent(in) :: this
      type(MultiState), intent(inout) :: multi_state
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      _FAIL('Attempt to use invalid spec')
      _RETURN(_SUCCESS)
   end subroutine add_to_state
Call graph
add_to_state calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize