add_dim_spec – MAPL
add_dim_spec Subroutine
16 statements
Source File
private subroutine add_dim_spec(this, dim_spec, rc)
Type Bound
UngriddedDimsSpec
Arguments
Type Intent Optional Attributes Name
class(UngriddedDimsSpec), intent(inout) :: this
type(UngriddedDimSpec), intent(in) :: dim_spec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_dim_spec(this, dim_spec, rc)
      class(UngriddedDimsSpec), intent(inout) :: this
      type(UngriddedDimSpec), intent(in) :: dim_spec
      integer, optional, intent(out) :: rc
      integer :: status
      if (dim_spec%get_name() == 'levels') then
         _ASSERT(this%get_num_ungridded() == 0, 'vertical levels must be 1st ungridded dimension.')
      end if
      call this%dim_specs%push_back(dim_spec)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(status)
   end subroutine add_dim_spec
Call graph
add_dim_spec calls mapl_assert, get_name, get_num_ungridded, mapl_return, vector_push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
parse_var_specs calls add_dim_spec
test_field_set_info calls add_dim_spec
parse_component_spec calls parse_var_specs
setservices_ calls parse_component_spec, setservices_