add_spec_explicit – MAPL
add_spec_explicit Subroutine
17 statements
Source File
private subroutine add_spec_explicit(gridcomp, state_intent, unusable, short_name, standard_name, typekind, ungridded_dims, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_StateIntent_Flag), intent(in) :: state_intent
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: standard_name
type(ESMF_TypeKind_Flag), intent(in), optional :: typekind
type(UngriddedDimsSpec), intent(in) :: ungridded_dims
character(len=*), intent(in), optional :: units
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_spec_explicit(gridcomp, state_intent, unusable, short_name, standard_name, typekind, ungridded_dims, units, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(ESMF_Stateintent_Flag), intent(in) :: state_intent
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(*), intent(in) :: short_name
      character(*), intent(in) :: standard_name
      type(ESMF_TypeKind_Flag), optional, intent(in) :: typekind
      type(UngriddedDimsSpec), intent(in) :: ungridded_dims
      character(*), optional, intent(in) :: units
      integer, optional, intent(out) :: rc
      integer :: status
      type(VariableSpec) :: var_spec
!!$      var_spec = VariableSpec(...)
      call MAPL_AddSpec(gridcomp, var_spec, _RC)
      _RETURN(_SUCCESS)
   end subroutine add_spec_explicit
Call graph
add_spec_explicit calls mapl_addspec, mapl_return, mapl_verify
mapl_addspec calls add_spec_explicit, add_spec_basic
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_spec_basic calls mapl_return, mapl_verify, mapl_gridcompgetoutermeta, get_component_spec, vector_push_back
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
vector_push_back calls resize, vector_grow_to
add_import_spec_legacy calls mapl_addspec
mapl_addimportspec calls add_import_spec_legacy