add_internal_spec – MAPL
add_internal_spec Subroutine
17 statements
Source File
private subroutine add_internal_spec(gridcomp, unusable, short_name, standard_name, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: standard_name
character(len=*), intent(in), optional :: units
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_internal_spec(gridcomp, unusable, short_name, standard_name, units, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), intent(in) :: short_name
      character(len=*), intent(in) :: standard_name
      character(len=*), optional, intent(in) :: units
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      type(ComponentSpec), pointer :: component_spec
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      component_spec => outer_meta%get_component_spec()
      call component_spec%var_specs%push_back(VariableSpec(ESMF_STATEINTENT_INTERNAL, &
           short_name=short_name, standard_name=standard_name))
      _RETURN(ESMF_SUCCESS)
   end subroutine add_internal_spec
Call graph
add_internal_spec calls mapl_gridcompgetoutermeta, get_component_spec, mapl_return, mapl_verify, vector_push_back
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
vector_resize_size_kind calls reserve
mapl_addinternalspec calls add_internal_spec