add_import_coupler – MAPL
add_import_coupler Subroutine
5 statements
Source File
private subroutine add_import_coupler(this, driver)
Type Bound
GriddedComponentDriver
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriver), intent(inout) :: this
type(GriddedComponentDriver), intent(in) :: driver
Calls
Source Code
   subroutine add_import_coupler(this, driver)
      class(GriddedComponentDriver), intent(inout) :: this
      type(GriddedComponentDriver), intent(in) :: driver
      call this%import_couplers%push_back(driver)
   end subroutine add_import_coupler
Call graph
add_import_coupler calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve