add_item – MAPL
add_item Subroutine
12 statements
Source File
private subroutine add_item(this, standard_name, field_item, rc)
Type Bound
FieldDictionary
Arguments
Type Intent Optional Attributes Name
class(FieldDictionary), intent(inout) :: this
character(len=*), intent(in) :: standard_name
type(FieldDictionaryItem), intent(in) :: field_item
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_item(this, standard_name, field_item, rc)
      class(FieldDictionary), intent(inout) :: this
      character(*), intent(in) :: standard_name
      type(FieldDictionaryItem), intent(in) :: field_item
      integer, intent(out), optional :: rc
      integer :: status
      call this%entries%insert(standard_name, field_item)
      call this%add_aliases(standard_name, field_item%get_aliases(), _RC)
      _RETURN(_SUCCESS)
   end subroutine add_item
Call graph
add_item calls insert, add_aliases, get_aliases, mapl_return, mapl_verify
add_aliases calls mapl_return, begin, insert, mapl_assert, next, of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls insert, at
map_insert_pair calls insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
new_from_yaml calls add_item
test_add_item calls add_item
fielddictionary calls new_from_yaml