add_vertical_dimensions – MAPL
add_vertical_dimensions Subroutine
42 statements
Source File
public subroutine add_vertical_dimensions(bundle, metadata, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
type(FileMetadata), intent(inout) :: metadata
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_vertical_dimensions(bundle, metadata, rc)
      type(ESMF_FieldBundle), intent(in) :: bundle
      type(FileMetaData), intent(inout) :: metadata
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: num_levels
      type(StringVector) :: vertical_names
      type(StringVectorIterator) :: iter
      character(len=:), allocatable :: dim_name
      type(VerticalStaggerLoc) :: vert_staggerloc
      integer :: i, num_vgrid_levels, field_vgrid_levels
      type(ESMF_Field), allocatable :: fieldList(:)
      call MAPL_FieldBundleGet(bundle, fieldList=fieldList, _RC)
      num_vgrid_levels = 0
      vertical_names = StringVector()
      do i = 1, size(fieldList)
         call MAPL_FieldGet(fieldList(i), vert_staggerloc=vert_staggerloc, _RC)
         if (vert_staggerloc == VERTICAL_STAGGER_NONE) cycle
         ! Ensure consistent vertical grid
         call MAPL_FieldGet(fieldList(i), num_vgrid_levels=field_vgrid_levels, _RC)
         if (num_vgrid_levels > 0) then
            _ASSERT(field_vgrid_levels == num_vgrid_levels, "Inconsistent vertical grid in bundle.")
         else
            num_vgrid_levels = field_vgrid_levels
         end if
         dim_name = vert_staggerloc%get_dimension_name()
         call vertical_names%push_back(dim_name)
      end do
      associate (e => vertical_names%ftn_end())
        iter = vertical_names%ftn_begin()
        do while(iter /= e)
           call iter%next()
           dim_name = iter%of()
           num_levels = vert_staggerloc%get_num_levels(num_vgrid_levels)
           call metadata%add_dimension(dim_name, num_levels)
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine add_vertical_dimensions
Call graph
add_vertical_dimensions calls ftn_begin, ftn_end, mapl_assert, mapl_fieldbundleget, mapl_fieldget, next, add_dimension, get_dimension_name, get_num_levels, of, mapl_return, mapl_verify, push_back, stringvector
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
bundle_to_metadata calls add_vertical_dimensions