add_factory – MAPL
add_factory Subroutine
5 statements
Source File
private subroutine add_factory(this, factory)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout) :: this
class(RegridderFactory), intent(in) :: factory
Calls
Called by
Source Code
   subroutine add_factory(this, factory)
      class(RegridderManager), intent(inout) :: this
      class(RegridderFactory), intent(in) :: factory
      call this%factories%push_back(factory)
   end subroutine add_factory
Call graph
add_factory calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
new_regriddermanager calls add_factory
regriddermanager calls new_regriddermanager