add_variables – MAPL
add_variables Subroutine
21 statements
Source File
public subroutine add_variables(metadata, bundle, rc)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout) :: metadata
type(ESMF_FieldBundle), intent(in) :: bundle
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_variables(metadata, bundle, rc)
      type(ESMF_FieldBundle), intent(in) :: bundle
      type(FileMetaData), intent(inout) :: metadata
      integer, intent(out), optional :: rc
      integer :: status, num_fields, i
      character(len=ESMF_MAXSTR), allocatable :: field_names(:)
      type(ESMF_Field) :: field
      call ESMF_FieldBundleGet(bundle, fieldCount=num_fields, _RC)
      allocate(field_names(num_fields))
      call ESMF_FieldBundleGet(bundle, fieldNameList=field_names, _RC)
      do i=1,num_fields
         call ESMF_FieldBundleGet(bundle, field_names(i), field=field, _RC)
         call add_variable(metadata, field, _RC)
      enddo
      _RETURN(_SUCCESS)
   end subroutine add_variables
Call graph
add_variables calls esmf_fieldbundleget, add_variable, mapl_return, mapl_verify
add_variable calls mapl_return, mapl_verify, ESMF_InfoGetCharAlloc, ESMF_InfoGetFromHost, esmf_fieldget, get_gridded_dims, add_attribute, add_variable, esmf_to_pfio_type, get_mapl_geom, string_vec_to_comma_sep
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmf_to_pfio_type calls mapl_return, mapl_assert
get_mapl_geom calls mapl_return, mapl_verify, get_geom_manager, get_mapl_geom_from_id, mapl_geomgetid
string_vec_to_comma_sep calls begin, next, of
bundle_to_metadata calls add_variables