add_comp_name – MAPL
add_comp_name Function
7 statements
Source File
private function add_comp_name(this, comp_name) result(a_pt)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
character(len=*), intent(in) :: comp_name
Return Value type(ActualConnectionPt)
Calls
Called by
Source Code
   function add_comp_name(this, comp_name) result(a_pt)
      type(ActualConnectionPt) :: a_pt
      class(ActualConnectionPt), intent(in) :: this
      character(*), intent(in) :: comp_name
      a_pt%v_pt = this%v_pt%add_comp_name(comp_name)
      if (allocated(this%label)) a_pt%label = this%label
   end function add_comp_name
Call graph
add_comp_name calls add_comp_name
connect_export_to_export calls add_comp_name
propagate_unsatisfied_imports_virtual_pt calls add_comp_name
connect calls connect_export_to_export
initialize_advertise calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_unsatisfied_imports
initialize calls initialize_advertise