add_child_by_name – MAPL
add_child_by_name Subroutine
17 statements
Source File
private subroutine add_child_by_name(gridcomp, child_name, setservices, config, rc)
Uses
mapl3g_UserSetServices
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
character(len=*), intent(in) :: child_name
class(AbstractUserSetServices), intent(in) :: setservices
type(ESMF_HConfig), intent(inout) :: config
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_child_by_name(gridcomp, child_name, setservices, config, rc)
      use mapl3g_UserSetServices
      type(ESMF_GridComp), intent(inout) :: gridcomp
      character(len=*), intent(in) :: child_name
      class(AbstractUserSetServices), intent(in) :: setservices
      type(ESMF_HConfig), intent(inout) :: config
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      _ASSERT(is_valid_name(child_name), 'Child name <' // child_name //'> does not conform to GEOS standards.')
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      call outer_meta%add_child(child_name, setservices, config, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine add_child_by_name
Call graph
add_child_by_name calls mapl_assert, mapl_gridcompgetoutermeta, add_child, is_valid_name, mapl_return, mapl_verify, add_child_by_name, ESMF_ClockCreate, esmf_gridcompsetservices, create_grid_comp, get_clock, insert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_assert, mapl_return, mapl_verify, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
mapl_addchild calls add_child_by_name
setservices calls mapl_addchild, setservices