add_import_spec_legacy – MAPL
add_import_spec_legacy Subroutine
27 statements
Source File
private subroutine add_import_spec_legacy(gc, short_name, long_name, units, dims, vlocation, datatype, num_subtiles, refresh_interval, averaging_interval, halowidth, precision, default, restart, ungridded_dims, field_type, staggering, rotation, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: short_name
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: units
integer, intent(in), optional :: dims
integer, intent(in), optional :: vlocation
integer, intent(in), optional :: datatype
integer, intent(in), optional :: num_subtiles
integer, intent(in), optional :: refresh_interval
integer, intent(in), optional :: averaging_interval
integer, intent(in), optional :: halowidth
integer, intent(in), optional :: precision
real, intent(in), optional :: default
integer, intent(in), optional :: restart
integer, intent(in), optional :: ungridded_dims(:)
integer, intent(in), optional :: field_type
integer, intent(in), optional :: staggering
integer, intent(in), optional :: rotation
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_import_spec_legacy(gc, short_name, long_name,               &
        units,  dims, vlocation,                 &
        datatype,num_subtiles, refresh_interval, &
        averaging_interval, halowidth, precision, default,  &
        restart, ungridded_dims, field_type,     &
        staggering, rotation, rc)
      type (ESMF_GridComp)            , intent(inout)   :: gc
      character (len=*)               , intent(in)      :: short_name
      character (len=*)  , optional   , intent(in)      :: long_name
      character (len=*)  , optional   , intent(in)      :: units
      integer            , optional   , intent(in)      :: dims
      integer            , optional   , intent(in)      :: datatype
      integer            , optional   , intent(in)      :: num_subtiles
      integer            , optional   , intent(in)      :: vlocation
      integer            , optional   , intent(in)      :: refresh_interval
      integer            , optional   , intent(in)      :: averaging_interval
      integer            , optional   , intent(in)      :: halowidth
      integer            , optional   , intent(in)      :: precision
      real               , optional   , intent(in)      :: default
      integer            , optional   , intent(in)      :: restart
      integer            , optional   , intent(in)      :: ungridded_dims(:)
      integer            , optional   , intent(in)      :: field_type
      integer            , optional   , intent(in)      :: staggering
      integer            , optional   , intent(in)      :: rotation
      integer            , optional   , intent(out)     :: rc
      integer :: status
      type(VariableSpec) :: var_spec
!!$      var_spec = VariableSpec(&
!!$           state_intent=ESMF_STATEINTENT_IMPORT, &
!!$           short_name=short_name, &
!!$           typekind=to_typekind(precision), &
!!$           state_item=to_state_item(datatype), &
!!$           units=units, &
!!$           ungridded_dims=to_ungridded_dims(dims, vlocation, ungridded_dims, ungridded_coords))
      call MAPL_AddSpec(gc, var_spec, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine add_import_spec_legacy
Call graph
add_import_spec_legacy calls mapl_addspec, mapl_return, mapl_verify
mapl_addspec calls add_spec_basic, add_spec_explicit
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_spec_basic calls mapl_return, mapl_verify, mapl_gridcompgetoutermeta, get_component_spec, vector_push_back
add_spec_explicit calls mapl_addspec, mapl_return, mapl_verify
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
vector_push_back calls resize, vector_grow_to
mapl_addimportspec calls add_import_spec_legacy