add_comp_name – MAPL
add_comp_name Function
7 statements
Source File
private function add_comp_name(this, comp_name) result(v_pt)
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
character(len=*), intent(in) :: comp_name
Return Value type(VirtualConnectionPt)
Called by
Source Code
   function add_comp_name(this, comp_name) result(v_pt)
      type(VirtualConnectionPt) :: v_pt
      class(VirtualConnectionPt), intent(in) :: this
      character(*), intent(in) :: comp_name
      v_pt = this
      if (.not. allocated(v_pt%comp_name)) v_pt%comp_name = comp_name
   end function add_comp_name
Call graph
add_comp_name calls add_comp_name
make_virtualpt calls add_comp_name
propagate_exports_virtual_pt calls add_comp_name
test_e2e_preserve_actual_pt calls add_comp_name
test_less2 calls add_comp_name
test_multi_import calls add_comp_name, propagate_unsatisfied_imports
test_propagate_import calls add_comp_name, propagate_unsatisfied_imports
test_sibling_activation calls add_comp_name, propagate_exports, propagate_unsatisfied_imports
connect_export_to_export calls add_comp_name
initialize_advertise calls make_virtualpt, propagate_exports, propagate_unsatisfied_imports
propagate_unsatisfied_imports_virtual_pt calls add_comp_name
connect calls connect_export_to_export
initialize calls initialize_advertise
propagate_exports_all calls propagate_exports
propagate_exports_child calls propagate_exports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports