add_mapl_geom – MAPL
add_mapl_geom Module Function
28 statements
Source File
module function add_mapl_geom(this, geom_spec, rc) result(mapl_geom)
Arguments
Type Intent Optional Attributes Name
class(GeomManager), intent(inout), target :: this
class(GeomSpec), intent(in) :: geom_spec
integer, intent(out), optional :: rc
Return Value type(MaplGeom), pointer
Calls
Source Code
   module function add_mapl_geom(this, geom_spec, rc) result(mapl_geom)
      type(MaplGeom), pointer :: mapl_geom
      class(GeomManager), target, intent(inout) :: this
      class(GeomSpec), intent(in) :: geom_spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(MaplGeom) :: tmp_mapl_geom
      type(GeomSpecVectorIterator) :: iter
      mapl_geom => null() ! unless
      associate (b => this%geom_specs%begin(), e => this%geom_specs%end())
        iter = find(b, e, geom_spec)
        _ASSERT(iter == e, "Requested geom_spec already exists.")
      end associate
      tmp_mapl_geom = this%make_mapl_geom(geom_spec, _RC)
      associate (id => this%id_counter)
        id = id + 1
        _ASSERT(id <= MAX_ID, "Too many geoms created.")
        call tmp_mapl_geom%set_id(id, _RC)
        call this%geom_ids%push_back(id)
        call this%geom_specs%push_back(geom_spec)
        call this%mapl_geoms%insert(id, tmp_mapl_geom)
        mapl_geom => this%mapl_geoms%of(id)
      end associate
      _RETURN(_SUCCESS)
   end function add_mapl_geom
Call graph
add_mapl_geom calls begin, find, insert, make_mapl_geom, mapl_assert, mapl_return, mapl_verify, of, push_back, set_id