add_to_state – MAPL
add_to_state Subroutine
34 statements
Source File
private subroutine add_to_state(this, multi_state, actual_pt, rc)
Type Bound
WildcardSpec
Arguments
Type Intent Optional Attributes Name
class(WildcardSpec), intent(in) :: this
type(MultiState), intent(inout) :: multi_state
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_to_state(this, multi_state, actual_pt, rc)
      class(WildcardSpec), intent(in) :: this
      type(MultiState), intent(inout) :: multi_state
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      call with_target_attribute(this, multi_state, actual_pt, _RC)
      _RETURN(_SUCCESS)
   contains
      subroutine with_target_attribute(this, multi_state, actual_pt, rc)
         class(WildcardSpec), target, intent(in) :: this
         type(MultiState), intent(inout) :: multi_state
         type(ActualConnectionPt), intent(in) :: actual_pt
         integer, optional, intent(out) :: rc
         integer :: status
         type(ActualPtStateItemSpecMapIterator) :: iter
         class(StateItemSpec), pointer :: spec_ptr
         type(ActualConnectionPt), pointer :: effective_pt
         associate (e => this%matched_items%ftn_end())
           iter = this%matched_items%ftn_begin()
           do while (iter /= e)
              iter = next(iter)
              ! Ignore actual_pt argument and use internally recorded name
              effective_pt => iter%first()
              spec_ptr => iter%second()
              call spec_ptr%add_to_state(multi_state, effective_pt, _RC)
           end do
         end associate
         _RETURN(_SUCCESS)
      end subroutine with_target_attribute
   end subroutine add_to_state
Call graph
add_to_state calls add_to_state, next, map_ftn_begin, map_ftn_end, map_iter_first, mapl_return, mapl_verify
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
mapl_throw_exception calls initialize
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value