add_spec_basic – MAPL
add_spec_basic Subroutine
14 statements
Source File
private subroutine add_spec_basic(gridcomp, var_spec, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(VariableSpec), intent(in) :: var_spec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_spec_basic(gridcomp, var_spec, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(VariableSpec), intent(in) :: var_spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      type(ComponentSpec), pointer :: component_spec
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      component_spec => outer_meta%get_component_spec()
      call component_spec%var_specs%push_back(var_spec)
      _RETURN(_SUCCESS)
   end subroutine add_spec_basic
Call graph
add_spec_basic calls mapl_gridcompgetoutermeta, get_component_spec, mapl_return, mapl_verify, vector_push_back
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
vector_resize_size_kind calls reserve
mapl_addspec calls add_spec_basic, add_spec_explicit
add_import_spec_legacy calls mapl_addspec
add_spec_explicit calls mapl_addspec
mapl_addimportspec calls add_import_spec_legacy