add_var_attribute_1d – MAPL
add_var_attribute_1d Subroutine
19 statements
Source File
private subroutine add_var_attribute_1d(this, var_name, attr_name, values, unusable, rc)
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: attr_name
class(*), intent(in) :: values(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_var_attribute_1d(this, var_name, attr_name, values, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: var_name
      character(len=*), intent(in) :: attr_name
      class (*), intent(in) :: values(:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class (Variable), pointer :: var
      integer :: status
      var => this%get_variable(var_name, _RC)
      call var%add_attribute(attr_name, values)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_var_attribute_1d
Call graph
add_var_attribute_1d calls add_attribute, get_variable, mapl_return, mapl_verify
get_variable calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_attribute_1d calls mapl_return, insert
get_error_message calls at, insert
mapl_throw_exception calls initialize
map_at_rc calls map_find