add_to_states – MAPL
add_to_states Subroutine
29 statements
Source File
private subroutine add_to_states(this, multi_state, mode, rc)
Uses
mapl3g_MultiState
ESMF
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
type(MultiState), intent(inout) :: multi_state
character(len=*), intent(in) :: mode
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_to_states(this, multi_state, mode, rc)
      use esmf
      use mapl3g_MultiState
      class(HierarchicalRegistry), target, intent(inout) :: this
      type(MultiState), intent(inout) :: multi_state
      character(*), intent(in) :: mode
      integer, optional, intent(out) :: rc
      integer :: status
      type(ActualPtSpecPtrMapIterator) :: actual_iter
      type(ActualConnectionPt), pointer :: actual_pt
      type(StateItemSpecPtr), pointer :: item_spec_ptr
      class(StateItemSpec), pointer :: item_spec
      _ASSERT(any([mode == 'user', mode == 'outer']), 'invalid mode: <' // mode // '>')
      associate (e => this%actual_specs_map%end())
        actual_iter = this%actual_specs_map%begin()
        do while (actual_iter /= e)
           actual_pt => actual_iter%first()
           if (actual_pt%is_represented_in(mode)) then
              item_spec_ptr =>  actual_iter%second()
              item_spec => item_spec_ptr%ptr
              call item_spec%add_to_state(multi_state, actual_pt, _RC)
           end if
           call actual_iter%next()
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine add_to_states
Call graph
add_to_states calls add_to_state, mapl_assert, is_represented_in, map_begin, map_iter_first, map_iter_next, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
is_represented_in calls get_comp_name, get_state_intent, is_extension
map_begin calls map_s_begin
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_comp_name calls get_comp_name
get_error_message calls at, insert
get_state_intent calls get_state_intent
map_iter_of calls map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_s_advpos calls map_s_get_child, to_node
map_s_iter_of calls map_s_get_value
initialize_post_advertise calls add_to_states
initialize calls initialize_post_advertise