add_connection – MAPL
add_connection Subroutine
5 statements
Source File
private subroutine add_connection(this, conn)
Type Bound
ComponentSpec
Arguments
Type Intent Optional Attributes Name
class(ComponentSpec), intent(inout) :: this
class(Connection), intent(in) :: conn
Calls
Called by
Source Code
   subroutine add_connection(this, conn)
      class(ComponentSpec), intent(inout) :: this
      class(Connection), intent(in) :: conn
      call this%connections%push_back(conn)
   end subroutine add_connection
Call graph
add_connection calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
connect_all calls add_connection
gridcomp_connect_all calls connect_all
mapl_connectall calls gridcomp_connect_all
setservices calls mapl_connectall