add_const_value – MAPL
add_const_value Subroutine
12 statements
Source File
private subroutine add_const_value(this, const_value, rc)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(inout), target :: this
type(UnlimitedEntity), intent(in) :: const_value
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_const_value(this, const_value, rc)
      class (Variable), target, intent(inout) :: this
      type (UnlimitedEntity), intent(in) :: const_value
      integer, optional, intent(out) :: rc
      integer :: rank, dims
      !integer,allocatable :: shp(:), dims(:)
      rank = const_value%get_rank()
      dims = this%dimensions%size()
      _ASSERT( dims == rank, "dimensions and rank don't match.  Add dimension first")
      this%const_value = const_value
      _RETURN(_SUCCESS)
   end subroutine add_const_value
Call graph
add_const_value calls mapl_assert, get_rank, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_rank calls mapl_return, get_shape
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
get_shape calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
append_metadata calls add_const_value
append_vertical_metadata calls add_const_value
create_file_metada calls add_const_value
run calls add_const_value, create_bundle_rh, createfilemetadata
test_serialize calls add_const_value
typesafe_make_file_metadata calls add_const_value
add_metadata calls append_vertical_metadata
add_metadata_route_handle calls append_vertical_metadata
create_bundle_rh calls append_vertical_metadata
createfilemetadata calls append_vertical_metadata
initialize_ calls append_vertical_metadata
make_file_metadata calls typesafe_make_file_metadata, make_file_metadata
main calls run, create_file_metada, create_from_bundle
create_from_bundle calls createfilemetadata
initialize calls add_metadata_route_handle, create_bundle_rh, createfilemetadata
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle