add_action – MAPL
add_action Subroutine
5 statements
Source File
private subroutine add_action(this, action)
Type Bound
BundleAction
Arguments
Type Intent Optional Attributes Name
class(BundleAction), intent(inout) :: this
class(ExtensionAction), intent(in) :: action
Calls
Called by
Source Code
   subroutine add_action(this, action)
      class(BundleAction), intent(inout) :: this
      class(ExtensionAction), intent(in) :: action
      call this%actions%push_back(action)
   end subroutine add_action
Call graph
add_action calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
make_action calls add_action