add_child_by_name – MAPL
add_child_by_name Module Subroutine
25 statements
Source File
recursive module subroutine add_child_by_name(this, child_name, setservices, hconfig, rc) Interface →
Uses
mapl3g_GenericGridComp
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
character(len=*), intent(in) :: child_name
class(AbstractUserSetServices), intent(in) :: setservices
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module recursive subroutine add_child_by_name(this, child_name, setservices, hconfig, rc)
      use mapl3g_GenericGridComp, only: generic_setservices => setservices
      class(OuterMetaComponent), intent(inout) :: this
      character(len=*), intent(in) :: child_name
      class(AbstractUserSetServices), intent(in) :: setservices
      type(ESMF_Hconfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      type(GriddedComponentDriver) :: child_gc_driver
      type(ESMF_GridComp) :: child_gc
      type(ESMF_Clock) :: clock, child_clock
      _ASSERT(is_valid_name(child_name), 'Child name <' // child_name //'> does not conform to GEOS standards.')
      clock = this%user_gc_driver%get_clock()
      child_clock = ESMF_ClockCreate(clock, _RC)
      child_gc = create_grid_comp(child_name, setservices, hconfig, clock, _RC)
      call ESMF_GridCompSetServices(child_gc, generic_setservices, _RC)
      child_gc_driver = GriddedComponentDriver(child_gc, child_clock, MultiState())
      _ASSERT(this%children%count(child_name) == 0, 'duplicate child name: <'//child_name//'>.')
      call this%children%insert(child_name, child_gc_driver)
      _RETURN(ESMF_SUCCESS)
   end subroutine add_child_by_name
Call graph
add_child_by_name calls ESMF_ClockCreate, esmf_gridcompsetservices, create_grid_comp, get_clock, mapl_assert, insert, is_valid_name, mapl_return, mapl_verify, add_child_by_name, add_child
create_grid_comp calls create_grid_comp_primary
get_clock calls get_clock
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
create_grid_comp_primary calls ESMF_ClockCreate, mapl_return, mapl_verify, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, outer_name, set_is_generic
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
omap_insert_key_value calls at, insert, omap_k_push_back
setservices_ calls add_child, setservices_
setup calls add_child
test_mapl_invalid_name calls add_child
mapl_addchild calls add_child_by_name
test_finalize_children calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup