add_item_spec_virtual_override – MAPL
add_item_spec_virtual_override Subroutine
13 statements
Source File
private subroutine add_item_spec_virtual_override(this, virtual_pt, spec, actual_pt, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(VirtualConnectionPt), intent(in) :: virtual_pt
class(StateItemSpec), intent(in), target :: spec
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_item_spec_virtual_override(this, virtual_pt, spec, actual_pt, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      class(StateItemSpec), target, intent(in) :: spec
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      call this%add_extension_pt(virtual_pt, actual_pt)
      call this%add_item_spec(actual_pt, spec, _RC)
      _RETURN(_SUCCESS)
   end subroutine add_item_spec_virtual_override
Call graph
add_item_spec_virtual_override calls add_item_spec, add_extension_pt, mapl_return, mapl_verify
add_extension_pt calls insert, map_of, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_item_spec_actual calls mapl_return, mapl_verify, mapl_assert, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
get_error_message calls at, insert
map_of calls insert, map_s_iter_of
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to