add_to_state – MAPL
add_to_state Subroutine
23 statements
Source File
private subroutine add_to_state(this, multi_state, actual_pt, rc)
Type Bound
ServiceSpec
Arguments
Type Intent Optional Attributes Name
class(ServiceSpec), intent(in) :: this
type(MultiState), intent(inout) :: multi_state
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_to_state(this, multi_state, actual_pt, rc)
      class(ServiceSpec), intent(in) :: this
      type(MultiState), intent(inout) :: multi_state
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      type(ESMF_FieldBundle) :: alias
      character(:), allocatable :: short_name
      type(ESMF_State) :: substate
      integer :: status
      short_name = actual_pt%get_esmf_name()
      alias = ESMF_NamedAlias(this%payload, name=short_name, _RC)
      ! Add bundle to both import and export specs.
      call get_substate(multi_state%importstate, actual_pt%get_comp_name(), substate=substate, _RC)
      call ESMF_StateAdd(substate, [alias], _RC)
      call get_substate(multi_state%exportstate, actual_pt%get_comp_name(), substate=substate, _RC)
      call ESMF_StateAdd(substate, [alias], _RC)
      _RETURN(_SUCCESS)
   end subroutine add_to_state
Call graph
add_to_state calls ESMF_NamedAlias, esmf_stateadd, get_comp_name, get_esmf_name, get_substate, mapl_return, mapl_verify
get_comp_name calls get_comp_name
get_esmf_name calls get_esmf_name, get_extension_string, is_extension
get_substate calls esmf_stateadd, mapl_return, mapl_verify, esmf_statecreate, esmf_stateget, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
get_extension_string calls is_extension
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception