add_subregistry – MAPL
add_subregistry Subroutine
13 statements
Source File
private subroutine add_subregistry(this, subregistry, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
class(HierarchicalRegistry), target :: subregistry
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_subregistry(this, subregistry, rc)
      class(HierarchicalRegistry), target, intent(inout) :: this
      class(HierarchicalRegistry), target :: subregistry
      integer, optional, intent(out) :: rc
      type(RegistryPtr) :: wrap
      character(:), allocatable :: name
      name = subregistry%get_name()
      _ASSERT(.not. this%has_subregistry(name), 'Duplicate subregistry entry.')
      wrap%registry => subregistry
      call this%subregistries%insert(name, wrap)
      _RETURN(_SUCCESS)
   end subroutine add_subregistry
Call graph
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_connect calls add_subregistry
test_connect_chain calls add_subregistry
test_do_not_propagate_import calls add_subregistry
test_e2e_preserve_actual_pt calls add_subregistry
test_export_to_export_connection calls add_subregistry
test_get_subregistry calls add_subregistry
test_get_subregistry_fail_not_found calls add_subregistry
test_import_from_child calls add_subregistry
test_import_from_parent calls add_subregistry
test_multi_import calls add_subregistry
test_propagate_import calls add_subregistry
test_sibling_activation calls add_subregistry