add_regridder – MAPL
add_regridder Subroutine
7 statements
Source File
private subroutine add_regridder(this, spec, regriddr)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout) :: this
class(RegridderSpec), intent(in) :: spec
class(Regridder), intent(in) :: regriddr
Calls
Called by
Source Code
   subroutine add_regridder(this, spec, regriddr)
      class(RegridderManager), intent(inout) :: this
      class(RegridderSpec), intent(in) :: spec
      class(Regridder), intent(in) :: regriddr
      call this%specs%push_back(spec)
      call this%regridders%push_back(regriddr)
   end subroutine add_regridder
Call graph
add_regridder calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
get_regridder calls add_regridder
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder
regridaction calls new_scalarregridaction
make_action calls regridaction