allocate – MAPL
allocate Subroutine
87 statements
Source File
private subroutine allocate(this, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine allocate(this, rc)
      class(FieldSpec), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_FieldStatus_Flag) :: fstatus
      type(LU_Bound), allocatable :: bounds(:)
      _RETURN_UNLESS(this%is_active())
      call ESMF_FieldGet(this%payload, status=fstatus, _RC)
      _RETURN_IF(fstatus == ESMF_FIELDSTATUS_COMPLETE)
      bounds = get_ungridded_bounds(this)
      call ESMF_FieldEmptyComplete(this%payload, this%typekind, &
           ungriddedLBound=bounds%lower,  &
           ungriddedUBound=bounds%upper,  &
           _RC)
      call ESMF_FieldGet(this%payload, status=fstatus, _RC)
      call ESMF_FieldGet(this%payload, status=fstatus, _RC)
      _ASSERT(fstatus == ESMF_FIELDSTATUS_COMPLETE, 'ESMF field status problem.')
      if (allocated(this%default_value)) then
         call set_field_default(_RC)
      end if
      call this%set_info(this%payload, _RC)
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine set_field_default(rc)
         integer, intent(out), optional :: rc
         real(kind=ESMF_KIND_R4), pointer :: x_r4_1d(:),x_r4_2d(:,:),x_r4_3d(:,:,:),x_r4_4d(:,:,:,:)
         real(kind=ESMF_KIND_R8), pointer :: x_r8_1d(:),x_r8_2d(:,:),x_r8_3d(:,:,:),x_r8_4d(:,:,:,:)
         integer :: status, rank
         call ESMF_FieldGet(this%payload,rank=rank,_RC)
         if (this%typekind == ESMF_TYPEKIND_R4) then
            if (rank == 1) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r4_1d,_RC)
               x_r4_1d = this%default_value
            else if (rank == 2) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r4_2d,_RC)
               x_r4_2d = this%default_value
            else if (rank == 3) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r4_3d,_RC)
               x_r4_3d = this%default_value
            else if (rank == 4) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r4_4d,_RC)
               x_r4_4d = this%default_value
            else
               _FAIL('unsupported rank')
            end if
         else if (this%typekind == ESMF_TYPEKIND_R8) then
            if (rank == 1) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r8_1d,_RC)
               x_r8_1d = this%default_value
            else if (rank == 2) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r8_2d,_RC)
               x_r8_2d = this%default_value
            else if (rank == 3) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r8_3d,_RC)
               x_r8_3d = this%default_value
            else if (rank == 4) then
               call ESMF_FieldGet(this%payload,farrayptr=x_r8_4d,_RC)
               x_r8_4d = this%default_value
            else
               _FAIL('unsupported rank')
            end if
         else
            _FAIL('unsupported typekind')
         end if
         _RETURN(ESMF_SUCCESS)
      end subroutine set_field_default
   end subroutine allocate
Call graph
allocate calls esmf_fieldemptycomplete, esmf_fieldget, mapl_assert, get_ungridded_bounds, is_active, mapl_return, mapl_verify, set_info
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_ungridded_bounds calls get_bounds, get_vertical_bounds
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_info calls mapl_return, mapl_verify, ESMF_InfoDestroy, ESMF_InfoGetFromHost, ESMF_InfoSet, make_info
get_bounds calls of, get_bounds, get_num_ungridded
get_error_message calls at, insert
get_vertical_bounds calls get_num_levels
make_info calls mapl_return, mapl_verify, ESMF_InfoDestroy, ESMF_InfoSet, ESMF_InfoCreate, get_ith_dim_spec, get_num_ungridded, make_info
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_ith_dim_spec calls mapl_return, mapl_verify, at