allocate – MAPL
allocate Subroutine
26 statements
Source File
private subroutine allocate(this, rc)
Type Bound
BracketSpec
Arguments
Type Intent Optional Attributes Name
class(BracketSpec), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine allocate(this, rc)
      class(BracketSpec), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      type(ESMF_Field) :: field, alias
      do i = 1, this%bracket_size
         call this%field_specs(i)%allocate(_RC)
         field = this%field_specs(i)%get_payload()
         alias = ESMF_NamedAlias(field, name=int_to_string(i), _RC)
         call ESMF_FieldBundleAdd(this%payload, [alias], multiflag=.true., _RC)
      end do
      _RETURN(ESMF_SUCCESS)
   contains
      function int_to_string(i) result(s)
         character(:), allocatable :: s
         integer, intent(in) :: i
         character(len=20) :: buffer
         write(buffer, '(i0)') i
         s = trim(buffer)
      end function int_to_string
   end subroutine allocate
Call graph
allocate calls ESMF_NamedAlias, esmf_fieldbundleadd, get_payload, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize