append_message – MAPL
append_message Subroutine
8 statements
Source File
public subroutine append_message(msg)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: msg
Called by
Source Code
   subroutine append_message(msg)
      character(len=*), intent(in) :: msg
      if (.not. allocated(log)) then
         log = msg
      else
         log = log // ' :: ' // msg
      end if
   end subroutine append_message
Call graph
append_message calls append_message
finalize calls append_message
init calls append_message
run_extra calls append_message
run calls append_message