apply_to_children_custom – MAPL
apply_to_children_custom Subroutine
24 statements
Source File
private subroutine apply_to_children_custom(this, oper, rc)
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
procedure(I_child_op) :: oper
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine apply_to_children_custom(this, oper, rc)
      class(OuterMetaComponent), intent(inout) :: this
      procedure(I_child_op) :: oper
      integer, optional, intent(out) :: rc
      integer :: status
      type(GriddedComponentDriverMapIterator) :: iter
      type(GriddedComponentDriver), pointer :: child
      type(OuterMetaComponent), pointer :: child_meta
      type(ESMF_GridComp) :: child_outer_gc
      associate(b => this%children%begin(), e => this%children%end())
        iter = b
        do while (iter /= e)
           child => iter%second()
           child_outer_gc = child%get_gridcomp()
           child_meta => get_outer_meta(child_outer_gc, _RC)
           call oper(this, child_meta, _RC)
           call iter%next()
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine apply_to_children_custom
Call graph
apply_to_children_custom calls get_outer_meta, get_gridcomp, mapl_return, mapl_verify, omap_begin, omap_iter_next
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
omap_begin calls omap_k_begin
omap_iter_next calls omap_k_iter_next
get_error_message calls at, insert
get_outer_meta_from_outer_gc calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
apply_to_children calls apply_to_children_custom
initialize_advertise calls apply_to_children
initialize_geom calls apply_to_children
initialize calls initialize_advertise, initialize_geom