are_convertible_str – MAPL
are_convertible_str Function
20 statements
Source File
private function are_convertible_str(from, to, rc) result(convertible)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: from
character(len=*), intent(in) :: to
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function are_convertible_str(from, to, rc) result(convertible)
      logical :: convertible
      character(*), intent(in) :: from, to
      integer, optional, intent(out) :: rc
      integer :: status
      type(UDUnit) :: unit1, unit2
      unit1 = UDUnit(from)
      unit2 = UDUnit(to)
      convertible = are_convertible_udunit(unit1, unit2, _RC)
      _RETURN(UT_SUCCESS)
   end function are_convertible_str
Call graph
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_are_convertible, ut_get_status, get_cptr, success
are_convertible calls are_convertible_str
can_connect_units calls are_convertible
construct_converter calls are_convertible
test_are_convertible calls are_convertible
test_are_not_convertible calls are_convertible
converter calls construct_converter
can_connect_to calls can_connect_units, can_connect_to
connect_to calls can_connect_to
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to