are_convertible_udunit – MAPL
are_convertible_udunit Function
19 statements
Source File
private function are_convertible_udunit(unit1, unit2, rc) result(convertible)
Arguments
Type Intent Optional Attributes Name
type(UDUnit), intent(in) :: unit1
type(UDUnit), intent(in) :: unit2
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function are_convertible_udunit(unit1, unit2, rc) result(convertible)
      logical :: convertible
      type(UDUnit), intent(in) :: unit1, unit2
      integer, optional, intent(out) :: rc
      integer :: status
      integer(c_int), parameter :: ZERO = 0_c_int
      convertible = (ut_are_convertible(unit1%get_cptr(), unit2%get_cptr())  /= ZERO)
      status = ut_get_status()
      _ASSERT(success(status), status)
      _RETURN(UT_SUCCESS)
   end function are_convertible_udunit
Call graph
are_convertible_udunit calls ut_are_convertible, ut_get_status, get_cptr, success
are_convertible calls are_convertible_udunit, are_convertible_str
are_convertible_str calls are_convertible_udunit
can_connect_units calls are_convertible
construct_converter calls are_convertible
test_are_convertible calls are_convertible
test_are_not_convertible calls are_convertible
converter calls construct_converter
can_connect_to calls can_connect_units, can_connect_to
connect_to calls can_connect_to
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to