attach_inner_meta – MAPL
attach_inner_meta Subroutine
20 statements
Source File
public subroutine attach_inner_meta(self_gc, outer_gc, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: self_gc
type(ESMF_GridComp), intent(in) :: outer_gc
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine attach_inner_meta(self_gc, outer_gc, rc)
      type(ESMF_GridComp), intent(inout) :: self_gc
      type(ESMF_GridComp), intent(in) :: outer_gc
      integer, optional, intent(out) :: rc
      type(InnerMetaComponent), pointer :: inner_meta
      integer :: status
      _SET_NAMED_PRIVATE_STATE(self_gc, InnerMetaComponent, INNER_META_PRIVATE_STATE, inner_meta)
      inner_meta = InnerMetaComponent(self_gc, outer_gc)
      _RETURN(_SUCCESS)
   end subroutine attach_inner_meta
Call graph
attach_inner_meta calls mapl_assert, mapl_usercompsetinternalstate, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
setservices_ calls attach_inner_meta, setservices_
create_grid_comp_primary calls setservices_
create_grid_comp calls create_grid_comp_primary