attach_coupler_meta – MAPL
attach_coupler_meta Subroutine
18 statements
Source File
public subroutine attach_coupler_meta(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine attach_coupler_meta(gridcomp, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(CouplerMetaComponent), pointer :: meta
      _SET_NAMED_PRIVATE_STATE(gridcomp, CouplerMetaComponent, COUPLER_META_PRIVATE_STATE, meta)
      _RETURN(_SUCCESS)
   end subroutine attach_coupler_meta
Call graph
attach_coupler_meta calls mapl_assert, mapl_usercompsetinternalstate, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_coupler calls attach_coupler_meta
add_state_extension calls make_coupler
extend_ calls add_state_extension
connect_sibling calls extend_