attach_outer_meta – MAPL
attach_outer_meta Subroutine
18 statements
Source File
public subroutine attach_outer_meta(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine attach_outer_meta(gridcomp, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      _SET_NAMED_PRIVATE_STATE(gridcomp, OuterMetaComponent, OUTER_META_PRIVATE_STATE, outer_meta)
      _RETURN(_SUCCESS)
   end subroutine attach_outer_meta
Call graph
attach_outer_meta calls mapl_assert, mapl_usercompsetinternalstate, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
create_grid_comp_primary calls attach_outer_meta
create_grid_comp calls create_grid_comp_primary
add_child_by_name calls create_grid_comp, add_child_by_name
make_driver calls create_grid_comp
setup calls create_grid_comp
test_is_generic calls create_grid_comp
test_mapl_invalid_name calls create_grid_comp
mapl_run_driver calls make_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
test_wasfinal calls setup
test_wasinit calls setup
test_wasrun_1 calls setup
test_wasrun_extra calls setup