BundleAddState_ – MAPL
BundleAddState_ Subroutine
129 statements
Source File
private recursive subroutine BundleAddState_(BUNDLE, STATE, rc, GRID, VALIDATE)
The recursive subrountine BundleAddState_ adds contents of State to Bundle. Extracts fields from an ESMF State and adds them to a ESMF Bundle. In essesence, it serializes an ESMF state in a flat Bundle. The BUNDLE must have been created prior to calling this routine.
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
type(ESMF_State), intent(inout) :: STATE
integer, optional :: rc
type(ESMF_Grid), intent(in), optional :: GRID
logical, intent(in), optional :: VALIDATE
Calls
Called by
Source Code
    RECURSIVE subroutine BundleAddState_ ( BUNDLE, STATE, rc, &
                                           GRID, VALIDATE )
!
! !ARGUMENTS:
!
    implicit NONE
    type(ESMF_FieldBundle), intent(inout)         :: BUNDLE
    type(ESMF_State),  intent(INout)            :: STATE
    integer, optional                        :: rc
    type(ESMF_Grid),  optional, intent(in)   :: GRID
    logical, optional, intent(in)            :: VALIDATE
!
    character(len=*), parameter          :: Iam="ESMFL_StateSerialize"
    integer                              :: STATUS
    type(ESMF_State)                     :: tSTATE
    type(ESMF_FieldBundle)                    :: tBUNDLE
    type(ESMF_Field)                     :: tFIELD
    type(ESMF_Grid)                      :: tGRID
    integer                              :: I, J
    integer                              :: ItemCount, FieldCount
    type (ESMF_StateItem_Flag), pointer  :: ItemTypes(:)
    character(len=ESMF_MAXSTR ), pointer :: ItemNames(:), FieldNames(:)
    logical                              :: needGrid = .true.
    logical                              :: validate_ = .false.
    integer, allocatable :: orderlist(:)
    integer :: jj
    character(len=ESMF_MAXSTR)           :: attrName
    character(len=ESMF_MAXSTR), allocatable :: currList(:)
    integer                                 :: natt
    type(ESMF_Info)                      :: infoh
!                           ---
    if ( present(validate) ) validate_ = validate
!   Query state for number of items and allocate space for them
!   -----------------------------------------------------------
    call ESMF_StateGet(STATE,ItemCount=ItemCount,RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(ItemCount>0, 'itemCount should be > 0')
    allocate ( ItemNames(ItemCount), stat=STATUS)
    _VERIFY(STATUS)
    allocate ( ItemTypes(ItemCount), stat=STATUS)
    _VERIFY(STATUS)
!   Next, retrieve the names and types of each item in the state
!   ------------------------------------------------------------
    call ESMF_StateGet ( STATE,      ItemNameList = ItemNames, &
                                ItemtypeList = ItemTypes, &
                                rc=STATUS)
    _VERIFY(STATUS)
!   Loop over each item on STATE
!   ----------------------------
    attrName = MAPL_StateItemOrderList
    call ESMF_InfoGetFromHost(state,infoh,RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_InfoGet(infoh,key=attrName,size=natt,RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(natt > 0, 'natt should be > 0')
    allocate(orderlist(natt), stat=status)
    _VERIFY(STATUS)
    allocate(currList(natt), stat=status)
    _VERIFY(STATUS)
    ! get the current list
    call ESMF_InfoGet(infoh,key=attrName,values=currList,rc=status)
    _VERIFY(STATUS)
    orderList = -1 ! not found
    do i = 1, natt
       ! search loop
       do jj = 1, ITEMCOUNT
          if (itemNames(jj) == currList(i)) then
             orderList(i) = jj
             exit
          end if
       end do
    end do
    deallocate(currList)
    do JJ = 1, natt
       I = ORDERLIST(JJ)
!@@@    do I = 1, ItemCount
!         Got a field
!         -----------
          if (ItemTypes(I) == ESMF_StateItem_Field) THEN
             call ESMF_StateGet ( STATE, ItemNames(i), tFIELD, rc=status)
             _VERIFY(STATUS)
             call AddThisField_()
!         Got a Bundle
!         ------------
          else if (ItemTypes(I) == ESMF_StateItem_FieldBundle) then
             call ESMF_StateGet(STATE, ItemNames(i), tBUNDLE, rc=STATUS)
             _VERIFY(STATUS)
             call ESMF_FieldBundleGet ( tBUNDLE, FieldCount = FieldCount, rc=STATUS)
             _VERIFY(STATUS)
             _ASSERT(FieldCount>0, 'FieldCount should be > 0')
             do j = 1, FieldCount
                call ESMF_FieldBundleGet ( tBUNDLE, j, tFIELD, rc=STATUS)
                _VERIFY(STATUS)
                call AddThisField_()
             end do
!         Got another state
!         -----------------
          else if (ItemTypes(I) == ESMF_StateItem_State) then
             call ESMF_StateGet(STATE, ItemNames(i), tSTATE, rc=STATUS)
             _VERIFY(STATUS)
             call BundleAddState_ ( BUNDLE, tSTATE, rc=STATUS )
             _VERIFY(STATUS)
             if (needGrid) then
                call ESMF_FieldBundleGet ( BUNDLE, GRID=tGRID, rc=STATUS )
                _VERIFY(STATUS)
                needGrid = .false.
             end if
!         What is this?
!         ------------
          else
             cycle
          end IF
    end do
    deallocate(orderlist)
!   Make sure the Bundle is not empty
!   ---------------------------------
    call ESMF_FieldBundleGet ( BUNDLE, FieldCount = FieldCount, rc=STATUS)
    _VERIFY(STATUS)
    _ASSERT(FieldCount>0, 'FieldCount should be > 0')
!   Set the grid
!   ------------
    if ( present(GRID) ) then
       call ESMF_FieldBundleSet ( BUNDLE, grid=GRID, rc=STATUS )
       _VERIFY(STATUS)
       needGrid = .false.
    else
       _ASSERT(.not. needGrid, 'could not find a grid')
    end if
!   Make sure field names are unique
!   --------------------------------
    allocate ( FieldNames(FieldCount), stat=STATUS )
    _VERIFY(STATUS)
    call ESMF_FieldBundleGet ( BUNDLE, FieldNameList=FieldNames, rc=STATUS )
    _VERIFY(STATUS)
!   Make sure field names are unique
!   --------------------------------
    if ( validate_ ) then
       do j = 1, FieldCount
          do i = j+1, FieldCount
             if ( trim(FieldNames(i)) == trim(FieldNames(j)) ) then
                STATUS = -1              ! same name
                _VERIFY(STATUS)
             end if
          end do
       end do
    end if
!   All done
!   --------
    deallocate(ItemNames)
    deallocate(ItemTypes)
    deallocate(FieldNames)
    _RETURN(ESMF_SUCCESS)
CONTAINS
    subroutine AddThisField_()
      call MAPL_FieldBundleAdd ( BUNDLE, tField, rc=STATUS )
      _VERIFY(STATUS)
      if ( needGrid ) then
         call ESMF_FieldGet ( tFIELD, grid=tGRID, rc=STATUS )
         _VERIFY(STATUS)
         needGrid = .false.
      end if
    end subroutine AddThisField_
  end subroutine BundleAddState_
Call graph
bundleaddstate_ calls bundleaddstate_, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldbundleget, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_assert, mapl_fieldbundleadd, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, mapl_return, mapl_verify, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_fieldbundleadd
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
esmfl_bundleaddstate calls bundleaddstate_
mapl_cfiocreatefromstate calls esmfl_bundleaddstate
mapl_cfioreadstate calls esmfl_bundleaddstate
mapl_cfiowritestate calls esmfl_bundleaddstate
mapl_simplebundlecreatefromstate calls esmfl_bundleaddstate
esmf_iocreate calls mapl_cfiocreatefromstate
esmf_ioread calls mapl_cfioreadstate
esmf_iowrite calls mapl_cfiowritestate
mapl_cfiocreate calls mapl_cfiocreatefromstate
mapl_cfioread calls mapl_cfioreadstate
mapl_cfiowrite calls mapl_cfiowritestate
mapl_simplebundlecreate calls mapl_simplebundlecreatefromstate
initialize_ calls mapl_cfioread
mapl_simplebundleread calls mapl_cfioread, mapl_simplebundlecreate
mapl_simplebundlewrite1 calls mapl_cfiocreate, mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiocreate, mapl_cfiowrite
test_main calls mapl_cfioread, esmf_iocreate, esmf_ioread, esmf_iowrite