BundleRegrid1 – MAPL
BundleRegrid1 Subroutine
52 statements
Source File
private subroutine BundleRegrid1(srcBUN, Sgrid2D, dstBUN, Dgrid2D, vm, rh, rc)
The subroutine BundleRegrid1 regrids members of a bundle using ESMF_FieldRegrid.
History
17Apr2006 Cruz Initial code.
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
type(ESMF_Grid), intent(in) :: Sgrid2D
type(ESMF_FieldBundle), intent(inout) :: dstBUN
type(ESMF_Grid), intent(in) :: Dgrid2D
type(ESMF_VM), intent(inout) :: vm
type(ESMF_RouteHandle), intent(inout) :: rh
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine BundleRegrid1 (srcBUN, Sgrid2D, dstBUN, Dgrid2D, &
                             vm, rh, rc)
!
  implicit NONE
! !ARGUMENTS:
   type(ESMF_FieldBundle), intent(inOUT)      :: srcBUN
   type(ESMF_FieldBundle), intent(inout)      :: dstBUN
   type(ESMF_Grid), intent(in)           :: Sgrid2D
   type(ESMF_Grid), intent(in)           :: Dgrid2D
   type(ESMF_RouteHandle), intent(inout) :: rh
   type(ESMF_VM), intent(inout)          :: vm
   integer, optional, intent(out)        :: rc
!
!-------------------------------------------------------------------------
! local vars
   type(ESMF_Field)        :: dstFLD
   type(ESMF_Field)        :: srcFLD
   type(ESMF_Array)        :: dstARR
   type(ESMF_Grid)         :: grid3D
   integer :: sCPD(3), dCPD(3)
   integer :: rank, deid, kmax, status, numVars
! begin
   _UNUSED_DUMMY(Sgrid2D)
   _UNUSED_DUMMY(Dgrid2D)
   _UNUSED_DUMMY(rh)
   call ESMF_VMGet(vm, localPet=deid, rc=status)
   _VERIFY(status)
   ! get number of fields in bundle
   ! number in srcBUN should be the same as in dstBUN (we can change later)
   call ESMF_FieldBundleGet      (srcBUN, FieldCount=NumVars,  RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_FieldBundleGet (srcBUN,  1, srcFLD,            RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_FieldBundleGet (dstBUN,  1, dstFLD,            RC=STATUS)
   _VERIFY(STATUS)
   ! get rank from any field
   call ESMF_FieldGet(dstFLD, array=dstARR, rc=status)
   _VERIFY(status)
   call ESMF_ArrayGet(dstARR, RANK=rank, rc=status)
   _VERIFY(status)
   ! get sCPD from srcFLD, Sgrid2D does not have correct 3rd dim
   call ESMF_FieldGet(srcFLD, grid=grid3D, rc=status)
   _VERIFY(STATUS)
   call MAPL_GridGet(grid3D, &
         localCellCountPerDim=sCPD, &
         RC=STATUS)
   _VERIFY(STATUS)
   ! get dCPD from Dgrid2D
   call ESMF_FieldGet(dstFLD, grid=grid3D, rc=status)
   _VERIFY(STATUS)
   call MAPL_GridGet(grid3D, &
         localCellCountPerDim=dCPD,RC=STATUS)
   _VERIFY(STATUS)
   ! for MAPL and GSI sCPD(3) = dCPD(3)
   ! assume 2D field
   kmax=1
   ! if rank is three then km = # levels in srcFLD
   if (rank==3) kmax=sCPD(3)
#if 0
   ! loop over fields in bundle
   do L=1,NumVars
     call ESMF_FieldBundleGet     (srcBUN, L, srcFLD,           RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_FieldGet           (srcFLD, NAME=srcName,         RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_FieldBundleGet     (dstBUN, L, dstFLD,           RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_FieldGet           (dstFLD, NAME=dstName,         RC=STATUS)
     _VERIFY(STATUS)
     ! allocate f90 pointer to hold data
     ! note halo width = 0
     if(rank==3) then
       call ESMF_FieldGet (srcFLD, 0, sptr3d, rc = status)
       _VERIFY(status)
       call ESMF_FieldGet(dstFLD, dptr3d, rc = status)
       _VERIFY(status)
     else
       call ESMF_FieldGetDataPointer (srcFLD, sptr2d, rc = status)
       _VERIFY(status)
       call ESMF_FieldGetDataPointer (dstFLD, dptr2d, rc = status)
       _VERIFY(status)
     end if
     ! these are 2d pointers used to create 2d fields
     allocate(sptr(1:sCPD(1),1:sCPD(2)), STAT=STATUS)
     _VERIFY(status)
     allocate(dptr(1:dCPD(1),1:dCPD(2)), STAT=STATUS)
     _VERIFY(status)
     ! 2d ESMF arrays associated with pointers sptr and dptr
     newSrcARR = ESMF_ArrayCreate(sptr, ESMF_DATA_REF, RC=STATUS)
     _VERIFY(STATUS)
     newDstARR = ESMF_ArrayCreate(dptr, ESMF_DATA_REF, RC=STATUS)
     _VERIFY(STATUS)
     ! local fields built with 2d sized arrays and 2D grids
     srcFLD2D = ESMF_FieldCreate(Sgrid2D, newSrcARR,    &
                   horzRelloc = ESMF_CELL_CENTER,         &
                   datamap=dmap,                       &
                   haloWidth=0, &
                   name   = fname, rc=status )
     _VERIFY(STATUS)
     dstFLD2D = ESMF_FieldCreate(Dgrid2D, newDstARR,    &
                   horzRelloc = ESMF_CELL_CENTER,         &
                   datamap=dmap,                       &
                   haloWidth=0, &
                   name   = fname, rc=status )
     _VERIFY(STATUS)
     ! loop over field's vertical levels
     do k=1, kmax
     ! modify field's pointer by reference
     if (rank==3) then
       sptr(:,:) = sptr3d(:,:,k)
     else
       sptr(:,:) = sptr2d(:,:)
     end if
     call ESMF_FieldRegrid(srcFLD2D, dstFLD2D, rh, rc=status)
     _VERIFY(STATUS)
     !  Update contents (array pointer) of dstFLD
     call ESMF_FieldGetDataPointer (dstFLD2D, dptr, rc = status)
     _VERIFY(status)
     if (rank==3) then
       dptr3d(:,:,k) = dptr(:,:)
     else
       dptr2d(:,:) = dptr(:,:)
     end if
     end do ! k
     deallocate(sptr, dptr, stat=status)
     _VERIFY(STATUS)
   end do ! L
#else
   _RETURN(-1)
#endif
   end subroutine BundleRegrid1
Call graph
bundleregrid1 calls ESMF_VMGet, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_gridget, mapl_return, mapl_verify
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
esmfl_regrid calls bundleregrid1