Bundle2State – MAPL
Bundle2State Subroutine
103 statements
Source File
private subroutine Bundle2State(BUN, STA, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUN
type(ESMF_State), intent(inout) :: STA
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine Bundle2State (BUN, STA, rc)
!-------------------------------------------------------------------
! extract fields from bundle and add to a state
   type(ESMF_FieldBundle), intent(inout) :: BUN !ALT: intent(in)
   type(ESMF_State) , intent(inout):: STA
  integer, intent(out), optional   :: rc
! locals
   integer          :: L, status,NumVars
   type(ESMF_Field) :: FLD
   type(ESMF_Field) :: stateFIELD
   character(len=ESMF_MAXSTR)              :: name
   character(len=ESMF_MAXSTR), parameter   :: IAm='Bundle2State'
   real, pointer :: src_ptr1d(:)
   real, pointer :: dst_ptr1d(:)
   real, pointer :: src_ptr2d(:,:)
   real, pointer :: dst_ptr2d(:,:)
   real, pointer :: src_ptr3d(:,:,:)
   real, pointer :: dst_ptr3d(:,:,:)
   real(kind=ESMF_KIND_R8), pointer :: src_pr81d(:)
   real(kind=ESMF_KIND_R8), pointer :: dst_pr81d(:)
   real(kind=ESMF_KIND_R8), pointer :: src_pr82d(:,:)
   real(kind=ESMF_KIND_R8), pointer :: dst_pr82d(:,:)
   real(kind=ESMF_KIND_R8), pointer :: src_pr83d(:,:,:)
   real(kind=ESMF_KIND_R8), pointer :: dst_pr83d(:,:,:)
   type(ESMF_TypeKind_Flag) :: src_tk, dst_tk
   integer                  :: src_fieldRank, dst_fieldRank
   logical                  :: NotInState
   character(len=ESMF_MAXSTR) :: NameInBundle
   type(ESMF_StateItem_Flag) :: itemType
!
   call ESMF_FieldBundleGet (BUN, name=name, FieldCount=NumVars, RC=STATUS)
   if(verbose .and. MAPL_AM_I_ROOT()) print *,' Unwrapping ',trim(name)
   do L=1,NumVars
      call ESMF_FieldBundleGet (BUN, L, FLD, RC=STATUS)
      _VERIFY(STATUS)
      call ESMF_FieldGet(FLD, Name=NameInBundle, rc=STATUS)
      _VERIFY(STATUS)
      call ESMF_StateGet (STA, nameInBundle, stateField,  RC=STATUS)
      notInState=(status/=ESMF_SUCCESS)
      if (.not.notINState) then
         call ESMF_StateGet (STA, NameInBundle, itemType=itemType,  RC=STATUS)
         _VERIFY(STATUS)
      end if
      if (itemType /= ESMF_STATEITEM_FIELD) then
         cycle
      end if
      if (NotInState) then
         call MAPL_StateAdd (STA, FLD, rc=status)
         _VERIFY(STATUS)
      else
         ! copy content to StateField
         call ESMF_FieldGet(stateFIELD, &
              dimCount=dst_fieldRank, &
              typeKind=dst_tk, rc=status)
         _VERIFY(STATUS)
         call ESMF_FieldGet(FLD, dimCount=src_fieldRank, &
              typeKind=src_tk, rc=status)
         _VERIFY(STATUS)
         ! make sure that type kind rank agrees between
         ! fld and stateField
         _ASSERT(dst_fieldRank == src_fieldRank, 'Rank mismatch between fld and stateField')
         _ASSERT(dst_tk == src_tk, 'Type Kind mismatch between fld and stateField')
         ! for appropriate TKR:
         if (dst_tk == ESMF_TypeKind_R4) then
            select case (dst_fieldRank)
            case (1)
               call ESMF_FieldGet(fld, farrayPtr=src_ptr1d, rc=status)
               _VERIFY(STATUS)
               call ESMF_FieldGet(stateField, farrayPtr=dst_ptr1d, rc=status)
               _VERIFY(STATUS)
               dst_ptr1d = src_ptr1d
            case (2)
               call ESMF_FieldGet(fld, farrayPtr=src_ptr2d, rc=status)
               _VERIFY(STATUS)
               call ESMF_FieldGet(stateField, farrayPtr=dst_ptr2d, rc=status)
               _VERIFY(STATUS)
               dst_ptr2d = src_ptr2d
            case (3)
               call ESMF_FieldGet(fld, farrayPtr=src_ptr3d, rc=status)
               _VERIFY(STATUS)
               call ESMF_FieldGet(stateField, farrayPtr=dst_ptr3d, rc=status)
               _VERIFY(STATUS)
               dst_ptr3d = src_ptr3d
            case default
            end select
         else if (dst_tk == ESMF_TypeKind_R8) then
            select case (dst_fieldRank)
            case (1)
              call ESMF_FieldGet(fld, farrayPtr=src_pr81d, rc=status)
              _VERIFY(STATUS)
              call ESMF_FieldGet(stateField, farrayPtr=dst_pr81d, rc=status)
              _VERIFY(STATUS)
              dst_pr81d = src_pr81d
           case (2)
              call ESMF_FieldGet(fld, farrayPtr=src_pr82d, rc=status)
              _VERIFY(STATUS)
              call ESMF_FieldGet(stateField, farrayPtr=dst_pr82d, rc=status)
              _VERIFY(STATUS)
              dst_pr82d = src_pr82d
           case (3)
              call ESMF_FieldGet(fld, farrayPtr=src_pr83d, rc=status)
              _VERIFY(STATUS)
              call ESMF_FieldGet(stateField, farrayPtr=dst_pr83d, rc=status)
              _VERIFY(STATUS)
              dst_pr83d = src_pr83d
            case default
               _FAIL( 'unsupported rank (>= 4)')
            end select
         end if
      end if
   end do
   _RETURN(ESMF_SUCCESS)
   end subroutine Bundle2State
Call graph
bundle2state calls esmf_fieldbundleget, esmf_fieldget, esmf_stateget, mapl_am_i_root, mapl_assert, mapl_stateadd, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_stateadd calls mapl_stateaddbundle, mapl_stateaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_stateaddbundle calls mapl_stateaddbundle, esmf_fieldbundleget, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_stateadd
mapl_stateaddfield calls mapl_stateaddfield, esmf_fieldget, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_stateadd
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
esmfl_bundle2state calls bundle2state