Bundles2Bundle – MAPL
Bundles2Bundle Subroutine
36 statements
Source File
private subroutine Bundles2Bundle(BUN1, BUN2, mergedBUN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUN1
type(ESMF_FieldBundle), intent(inout) :: BUN2
type(ESMF_FieldBundle), intent(inout) :: mergedBUN
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine Bundles2Bundle (BUN1, BUN2, mergedBUN, rc)
!-------------------------------------------------------------------
   type(ESMF_FieldBundle), intent(inout) :: BUN1
   type(ESMF_FieldBundle), intent(inout) :: BUN2
   type(ESMF_FieldBundle), intent(inout) :: mergedBUN
   integer, intent(out), optional :: rc
!
   type(ESMF_VM)           :: vm
   type(ESMF_Field)        :: FLD
   integer :: status, mype, L, numVars1, numVars2
   character(len=ESMF_MAXSTR)            :: name1, name2, name3
   character(len=ESMF_MAXSTR), parameter :: IAm = 'Bundles2Bundle'
! begin
   call ESMF_VMGetCurrent(vm)
   call ESMF_VMGet(vm, localPet=mype, rc=status)
   _VERIFY(STATUS)
   ! get number of fields in bundles
   call ESMF_FieldBundleGet (BUN1, name=name1, FieldCount=NumVars1, RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_FieldBundleGet (BUN2, name=name2, FieldCount=NumVars2, RC=STATUS)
   _VERIFY(STATUS)
   ! mergedBUN is an empty bundle created by the parent routine
   call ESMF_FieldBundleGet (mergedBUN, name=name3,  RC=STATUS)
   _VERIFY(STATUS)
   ! loop over fields in bundle and add to mergedBUN
   if(verbose .and. MAPL_AM_I_ROOT()) &
   print *,' Add ',NumVars1,' fields from ',trim(name1), &
   ' into ', trim(name3)
   do L=1,NumVars1
     call ESMF_FieldBundleGet (BUN1, L, FLD, RC=STATUS)
     _VERIFY(STATUS)
     call MAPL_FieldBundleAdd (mergedBUN, FLD, rc=status)
     _VERIFY(STATUS)
   end do ! L
   if(verbose .and. MAPL_AM_I_ROOT()) &
   print *,' Add ',NumVars2,' fields from ',trim(name2), &
   ' into ', trim(name3)
   do L=1,NumVars2
     call ESMF_FieldBundleGet (BUN2, L, FLD, RC=STATUS)
     _VERIFY(STATUS)
     call MAPL_FieldBundleAdd (mergedBUN, FLD, rc=status)
     _VERIFY(STATUS)
   end do ! L
   _RETURN(ESMF_SUCCESS)
   end subroutine Bundles2Bundle
Call graph
bundles2bundle calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, mapl_am_i_root, mapl_fieldbundleadd, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_fieldbundleadd, esmf_fieldget
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
esmfl_bundles2bundle calls bundles2bundle