bundle_to_metadata – MAPL
bundle_to_metadata Function
24 statements
Source File
public function bundle_to_metadata(bundle, geom, rc) result(metadata)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
type(ESMF_Geom), intent(in) :: geom
integer, intent(out), optional :: rc
Return Value type(FileMetadata)
Calls
Source Code
   function bundle_to_metadata(bundle, geom, rc) result(metadata)
      type(FileMetaData) :: metadata
      type(ESMF_FieldBundle), intent(in) :: bundle
      type(ESMF_Geom), intent(in) :: geom
      integer, optional, intent(out) :: rc
      integer:: status
      type(MaplGeom), pointer :: mapl_geom
      type(Variable) :: time_var
      type(ESMF_Time) :: fake_time
      mapl_geom => get_mapl_geom(geom, _RC)
      metadata = mapl_geom%get_file_metadata()
      ! Add metadata for vertical geom, note could be both center and edge
      ! Add metadata for all unique ungridded dimensions the set of fields has
      ! Add time metadata
      call ESMF_TimeSet(fake_time, timeString="1900-04-03T21:00:00", _RC)
      call metadata%add_dimension('time', pFIO_UNLIMITED)
      time_var = create_time_variable(fake_time, _RC)
      call metadata%add_variable('time', time_var, _RC)
      ! Variables
      call add_variables(metadata, bundle, _RC)
      _RETURN(_SUCCESS)
   end function bundle_to_metadata
Call graph
bundle_to_metadata calls ESMF_TimeSet, get_file_metadata, add_dimension, add_variable, add_variables, create_time_variable, get_mapl_geom, mapl_return, mapl_verify
add_variables calls mapl_return, mapl_verify, esmf_fieldbundleget, add_variable
create_time_variable calls mapl_return, mapl_verify, ESMF_TimeGet, add_attribute
get_mapl_geom calls mapl_return, mapl_verify, get_geom_manager, get_mapl_geom_from_id, mapl_geomgetid
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception