can_connect_to – MAPL
can_connect_to Function
10 statements
Source File
private function can_connect_to(this, src_spec, rc)
Type Bound
WildcardSpec
Arguments
Type Intent Optional Attributes Name
class(WildcardSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: src_spec
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function can_connect_to(this, src_spec, rc)
      class(WildcardSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: src_spec
      integer, optional, intent(out) :: rc
      integer :: status
      can_connect_to = this%reference_spec%can_connect_to(src_spec, _RC)
      _RETURN(_SUCCESS)
   end function can_connect_to
Call graph
can_connect_to calls can_connect_to, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
connect_to calls can_connect_to