can_connect_units – MAPL
can_connect_units Function
15 statements
Source File
private function can_connect_units(dst_units, src_units, rc)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(in), allocatable :: dst_units
character(len=:), intent(in), allocatable :: src_units
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function can_connect_units(dst_units, src_units, rc)
      character(:), allocatable, intent(in) :: dst_units
      character(:), allocatable, intent(in) :: src_units
      integer, optional, intent(out) :: rc
      integer :: status
      ! If mirror or same, we can connect without a coupler
      can_connect_units = match(dst_units, src_units)
      _RETURN_IF(can_connect_units)
      ! Otherwise need a coupler, but need to check if units are convertible
      can_connect_units = UDUNITS_are_convertible(src_units, dst_units, _RC)
      _RETURN(_SUCCESS)
   end function can_connect_units
Call graph
can_connect_units calls are_convertible, match, mapl_return, mapl_verify
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_are_convertible, ut_get_status, get_cptr, success
get_error_message calls at, insert
mapl_throw_exception calls initialize
match_geom calls mapl_samegeom
match_string calls mirror
mapl_samegeom calls same_geom
can_connect_to calls can_connect_units, can_connect_to
connect_to calls can_connect_to, connect_to
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to
test_connect_unique_mirror calls can_connect_to, connect_to
test_mirror_bracket_size calls can_connect_to