can_connect_to – MAPL
can_connect_to Function
21 statements
Source File
private function can_connect_to(this, src_spec, rc)
Type Bound
BracketSpec
Arguments
Type Intent Optional Attributes Name
class(BracketSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: src_spec
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function can_connect_to(this, src_spec, rc)
      class(BracketSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: src_spec
      integer, optional, intent(out) :: rc
      select type(src_spec)
      class is (BracketSpec)
         can_connect_to = all ([ &
              this%reference_spec%can_connect_to(src_spec%reference_spec), &
              match_integer(this%bracket_size, src_spec%bracket_size) & ! allow for mirroring
              ])
      class default
         can_connect_to = .false.
      end select
      _RETURN(_SUCCESS)
   contains
      ! At least one of src/dst must have allocated a bracket size.
      ! THe other can mirror.
      logical function match_integer(dst, src) result(match)
         integer, allocatable, intent(in) :: dst, src
         match = allocated(dst) .or. allocated(src)
         if (allocated(dst) .and. allocated(src)) then
            match = (src == dst)
         end if
      end function match_integer
   end function can_connect_to
Call graph
can_connect_to calls can_connect_to, mapl_return, of, can_connect_units, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
connect_to calls can_connect_to
test_connect_unique_mirror calls can_connect_to, connect_to
test_mirror_bracket_size calls can_connect_to