can_connect_to – MAPL
can_connect_to Function
33 statements
Source File
private function can_connect_to(this, src_spec, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: src_spec
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function can_connect_to(this, src_spec, rc)
      class(FieldSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: src_spec
      integer, optional, intent(out) :: rc
      logical :: can_convert_units_
      integer :: status
      select type(src_spec)
      class is (FieldSpec)
         can_convert_units_ = can_connect_units(this%units, src_spec%units, _RC)
         can_connect_to = all ([ &
              this%ungridded_dims == src_spec%ungridded_dims, &
              this%vertical_dim == src_spec%vertical_dim, &
              this%ungridded_dims == src_spec%ungridded_dims, &
              includes(this%attributes, src_spec%attributes), &
              can_convert_units_ &
              ])
      class default
         can_connect_to = .false.
      end select
      _RETURN(_SUCCESS)
   contains
      logical function includes(mandatory, provided)
         type(StringVector), target, intent(in) :: mandatory
         type(StringVector), target, intent(in) :: provided
         integer :: i, j
         character(:), pointer :: attribute_name
         m: do i = 1, mandatory%size()
            attribute_name => mandatory%of(i)
            p: do j = 1, provided%size()
               if (attribute_name == provided%of(j)) cycle m
            end do p
            ! ith not found
            includes = .false.
            return
         end do m
         includes = .true.
      end function includes
   end function can_connect_to
Call graph
can_connect_to calls of, can_connect_units, mapl_return, mapl_verify, can_connect_to
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
get_error_message calls at, insert
mapl_throw_exception calls initialize
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_are_convertible, ut_get_status, get_cptr, success
match_geom calls mapl_samegeom
match_string calls mirror
connect_to calls can_connect_to, connect_to
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to
test_connect_unique_mirror calls can_connect_to, connect_to
test_mirror_bracket_size calls can_connect_to