cat_ungridded_dim_names – MAPL
cat_ungridded_dim_names Function
12 statements
Source File
public function cat_ungridded_dim_names(dims) result(dim_names)
Arguments
Type Intent Optional Attributes Name
class(UngriddedDims), intent(in) :: dims
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function cat_ungridded_dim_names(dims) result(dim_names)
      character(len=:), allocatable :: dim_names
      class(UngriddedDims), intent(in) :: dims
      type(UngriddedDim) :: u
      integer :: i
      character, parameter :: JOIN = ','
      dim_names = EMPTY
      do i = 1, dims%get_num_ungridded()
         u = dims%get_ith_dim_spec(i)
         dim_names = JOIN // u%get_name()
      end do
   end function cat_ungridded_dim_names
Call graph
cat_ungridded_dim_names calls get_ith_dim_spec, get_name, get_num_ungridded
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
ungridded_dim_names calls cat_ungridded_dim_names
add_variable calls ungridded_dim_names
add_variables calls add_variable
bundle_to_metadata calls add_variables