check_virtual – MAPL
check_virtual Function
15 statements
Source File
public function check_virtual(r, virtual_pt, expected_names) result(check)
Arguments
Type Intent Optional Attributes Name
type(HierarchicalRegistry), intent(in) :: r
type(VirtualConnectionPt), intent(in) :: virtual_pt
character(len=*), intent(in) :: expected_names(:)
Return Value logical
Calls
Called by
Source Code
   logical function check_virtual(r, virtual_pt, expected_names) result(check)
      type(HierarchicalRegistry), intent(in) :: r
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      character(*), intent(in) :: expected_names(:)
      type(ActualPtVector), pointer :: actual_pts
      type(ActualConnectionPt), pointer :: actual_pt
      integer :: i
      check = .false.
      actual_pts => r%get_actual_pts(virtual_pt)
      @assert_that(associated(actual_pts), is(true()))
      do i = 1, actual_pts%size()
         actual_pt => actual_pts%of(i)
         check = check_actual(r, actual_pt, expected_names(i))
      end do
   end function check_virtual
Call graph
check_virtual calls assert_that, of, check_actual, get_actual_pts, true
check_actual calls assert_that, true, assertequal, get_item_spec
get_actual_pts calls at
get_item_spec calls at, mapl_return, mapl_verify
map_at_rc calls map_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
check calls check_virtual
test_export_to_export_connection calls check
test_get_item_spec_found calls check
test_get_item_spec_multi calls check
test_internal_to_export_connection calls check
test_sibling_activation calls check