check_field_value – MAPL
check_field_value Subroutine
102 statements
Source File
public subroutine check_field_value(expectations, state, short_name, description, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: expectations
type(ESMF_State), intent(inout) :: state
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: description
integer, intent(out) :: rc
Calls
Source Code
   subroutine check_field_value(expectations, state, short_name, description, rc)
      type(ESMF_HConfig), intent(in) :: expectations
      type(ESMF_State), intent(inout) :: state
      character(*), intent(in) :: short_name
      character(*), intent(in) :: description
      integer, intent(out) :: rc
      character(len=:), allocatable :: expected_field_typekind_str
      real :: expected_field_value
      integer :: rank
      type(ESMF_TypeKind_Flag) :: typekind
      integer :: status
      character(len=:), allocatable :: msg
      type(ESMF_Field) :: field
      type(ESMF_StateItem_Flag) :: itemtype
      msg = description
      itemtype = get_itemtype(state, short_name, _RC)
      if (itemtype /= ESMF_STATEITEM_FIELD) then ! that's ok
         rc = 0
         return
      end if
     if (.not. ESMF_HConfigIsDefined(expectations,keyString='value')) then
         rc = 0
         return
      end if
      expected_field_value = ESMF_HConfigAsR4(expectations,keyString='value',_RC)
      call ESMF_StateGet(state, short_name, field, _RC)
      call ESMF_FieldGet(field, typekind=typekind, rank=rank, rc=status)
      @assert_that('field get failed '//short_name,  status, is(0))
      if (typekind == ESMF_TYPEKIND_R4) then
         block
           real(kind=ESMF_KIND_R4), pointer :: x2(:,:),x3(:,:,:),x4(:,:,:,:)
           select case(rank)
           case(2)
              call ESMF_FieldGet(field, farrayptr=x2, _RC)
              @assert_that('value of '//short_name, all(x2 == expected_field_value), is(true()))
           case(3)
              call ESMF_FieldGet(field, farrayptr=x3, _RC)
              @assert_that('value of '//short_name, all(x3 == expected_field_value), is(true()))
           case(4)
              call ESMF_FieldGet(field, farrayptr=x4, _RC)
              @assert_that('value of '//short_name, all(x4 == expected_field_value), is(true()))
           end select
         end block
      elseif (typekind == ESMF_TYPEKIND_R8) then
         block
           real(kind=ESMF_KIND_R8), pointer :: x2(:,:),x3(:,:,:),x4(:,:,:,:)
           select case(rank)
           case(2)
              call ESMF_FieldGet(field, farrayptr=x2, _RC)
              @assert_that('value of '//short_name, all(x2 == expected_field_value), is(true()))
           case(3)
              call ESMF_FieldGet(field, farrayptr=x3, _RC)
              @assert_that('value of '//short_name, all(x3 == expected_field_value), is(true()))
           case(4)
              call ESMF_FieldGet(field, farrayptr=x4, _RC)
              @assert_that('value of '//short_name, all(x4 == expected_field_value), is(true()))
           end select
         end block
      else
         _VERIFY(-1)
      end if
      rc = 0
   end subroutine check_field_value
Call graph
check_field_value calls anyexceptions, assert_that, esmf_fieldget, esmf_hconfigasr4, esmf_hconfigisdefined, esmf_stateget, get_itemtype, sourcelocation, true, x2, x3, x4
get_itemtype calls anyexceptions, assert_that, esmf_stateget, sourcelocation