check_flip – MAPL
check_flip Function
48 statements
Source File
private function check_flip(metadata, rc) result(flip)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout), target :: metadata
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function check_flip(metadata, rc) result(flip)
      type(FileMetadata), target, intent(inout) :: metadata
      integer, optional, intent(out) :: rc
      character(len=:), pointer :: positive
      type(CoordinateVariable), pointer :: var
      type (StringVariableMap), pointer :: vars
      type (StringVariableMapIterator) :: var_iter
      character(len=:), pointer :: var_name
      logical :: isPresent
      logical :: flip
      type(Attribute), pointer :: attr => null()
      class(*), pointer :: vpos
      integer :: status
      flip = .false.
      vars => metadata%get_variables(_RC)
      var_iter = vars%ftn_begin()
      do while(var_iter /=vars%ftn_end())
         call var_iter%next()
         var_name => var_iter%first()
         var => metadata%get_coordinate_variable(trim(var_name))
         if (associated(var)) then
            if (index(var_name,'lev') .ne. 0 .or. index(var_name,'edge') .ne. 0) then
               isPresent = var%is_attribute_present('positive')
               if (isPresent) then
                  attr => var%get_attribute('positive')
                  _ASSERT(associated(attr),"restart file leve dim has no positive attribute")
                  vpos => attr%get_value()
                  select type(vpos)
                  type is (character(*))
                     positive => vpos
                  class default
                     _FAIL('units must be string')
                  end select
               else
                  positive => null()
               end if
               if (associated(positive)) then
                  flip = (trim(positive) == "up")
                  _RETURN(_SUCCESS)
               end if
            end if
         end if
      enddo
      _RETURN(_SUCCESS)
   end function check_flip
Call graph
check_flip calls mapl_assert, get_attribute, get_coordinate_variable, get_value, get_variables, is_attribute_present, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_coordinate_variable calls mapl_assert, mapl_return, mapl_verify, at
get_value calls mapl_return
get_variables calls mapl_return
is_attribute_present calls mapl_return, m_at
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_bundlereadncpar calls check_flip
mapl_varreadncpar calls mapl_bundlereadncpar, mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d, mapl_statevarreadncpar
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_statevarreadncpar calls mapl_varreadncpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_staterefresh calls mapl_esmfstatereadfromfile