check_match – MAPL
check_match Subroutine
18 statements
Source File
public subroutine check_match(hconfig, key, expected, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
character(len=*), intent(in) :: key
character(len=*), intent(in) :: expected
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine check_match(hconfig, key, expected, rc)
      type(ESMF_HConfig), intent(in) :: hconfig
      character(len=*), intent(in) :: key
      character(len=*), intent(in) :: expected
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=:), allocatable :: strval
      logical :: ok
      strval = ESMF_HConfigAsString(hconfig, keyString=trim(key), asOkay=ok, _RC)
      @assertTrue(ok, trim(key) // ' not found')
      if(ok) then
         @assertEqual(trim(expected), strval, 'Wrong value for ' // trim(key))
      end if
   end subroutine check_match
Call graph
check_match calls anyexceptions, assert_that, assertequal, asserttrue, esmf_hconfigasstring, sourcelocation
test_merge_hconfig_duplicate calls check_match
test_merge_hconfig_mapl_section calls check_match
test_merge_hconfig_no_mapl calls check_match