check_chunking – MAPL
check_chunking Subroutine
39 statements
Source File
private subroutine check_chunking(this, lev_size, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
integer, intent(in) :: lev_size
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine check_chunking(this,lev_size,rc)
        class (MAPL_GriddedIO), intent(inout) :: this
        integer, intent(in) :: lev_size
        integer, optional, intent(out) :: rc
        integer ::  global_dim(3)
        integer :: status
        character(len=5) :: c1,c2
        call MAPL_GridGet(this%output_grid,globalCellCountPerDim=global_dim,rc=status)
        _VERIFY(status)
        if (global_dim(1)*6 == global_dim(2)) then
           write(c2,'(I5)')global_dim(1)
           write(c1,'(I5)')this%chunking(1)
           _ASSERT(this%chunking(1) <= global_dim(1), "Chunk for Xdim "//c1//" must be less than or equal to "//c2)
           write(c1,'(I5)')this%chunking(2)
           _ASSERT(this%chunking(2) <= global_dim(1), "Chunk for Ydim "//c1//" must be less than or equal to "//c2)
           _ASSERT(this%chunking(3) <= 6, "Chunksize for face dimension must be 6 or less")
           if (lev_size > 0) then
              write(c2,'(I5)')lev_size
              write(c1,'(I5)')this%chunking(4)
              _ASSERT(this%chunking(4) <= lev_size, "Chunk for level size "//c1//" must be less than or equal to "//c2)
           end if
           _ASSERT(this%chunking(5) == 1, "Time must have chunk size of 1")
        else
           write(c2,'(I5)')global_dim(1)
           write(c1,'(I5)')this%chunking(1)
           _ASSERT(this%chunking(1) <= global_dim(1), "Chunk for lon "//c1//" must be less than or equal to "//c2)
           write(c2,'(I5)')global_dim(2)
           write(c1,'(I5)')this%chunking(2)
           _ASSERT(this%chunking(2) <= global_dim(2), "Chunk for lat "//c1//" must be less than or equal to "//c2)
           if (lev_size > 0) then
              write(c2,'(I5)')lev_size
              write(c1,'(I5)')this%chunking(3)
              _ASSERT(this%chunking(3) <= lev_size, "Chunk for level size "//c1//" must be less than or equal to "//c2)
           end if
           _ASSERT(this%chunking(4) == 1, "Time must have chunk size of 1")
        endif
        _RETURN(ESMF_SUCCESS)
     end subroutine check_chunking
Call graph
check_chunking calls mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
createfilemetadata calls check_chunking
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main