check_actual – MAPL
check_actual Function
16 statements
Source File
public function check_actual(r, actual_pt, expected_name) result(check)
Arguments
Type Intent Optional Attributes Name
type(HierarchicalRegistry), intent(in) :: r
type(ActualConnectionPt), intent(in) :: actual_pt
character(len=*), intent(in) :: expected_name
Return Value logical
Calls
Called by
Source Code
   logical function check_actual(r, actual_pt, expected_name) result(check)
      type(HierarchicalRegistry), intent(in) :: r
      type(ActualConnectionPt), intent(in) :: actual_pt
      character(*), intent(in) :: expected_name
      class(StateItemSpec), pointer :: spec
      check = .false.
      spec => r%get_item_spec(actual_pt)
      @assert_that(associated(spec), is(true()))
      select type(spec)
      type is (MockItemSpec)
         @assertEqual(expected_name, spec%name)
         check = .true.
      class default
         @assert_that(1,is(2))
      end select
   end function check_actual
Call graph
check_actual calls assert_that, assertequal, get_item_spec, true
get_item_spec calls at, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
check calls check_actual, check_virtual
check_virtual calls check_actual
test_export_to_export_connection calls check
test_get_item_spec_found calls check
test_get_item_spec_multi calls check
test_internal_to_export_connection calls check
test_sibling_activation calls check