check_and_fill_consistency – MAPL
check_and_fill_consistency Subroutine
66 statements
Source File
private subroutine check_and_fill_consistency(this, unusable, rc)
Uses
MAPL_BaseMod
MAPL_Constants
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine check_and_fill_consistency(this, unusable, rc)
      use MAPL_BaseMod, only: MAPL_DecomposeDim
      use MAPL_Constants, only: PI => MAPL_PI_R8
      class (CubedSphereGridFactory), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'check_and_fill_consistency'
      _UNUSED_DUMMY(unusable)
      if (.not. allocated(this%grid_name)) then
         this%grid_name = MAPL_GRID_NAME_DEFAULT
      end if
      if (this%grid_type == MAPL_UNDEFINED_INTEGER) then
         this%grid_type = FV_GRID_TYPE_DEFAULT ! fv default
      end if
      if ( (this%target_lon /= MAPL_UNDEFINED_REAL) .and. &
           (this%target_lat /= MAPL_UNDEFINED_REAL) .and. &
           (this%stretch_factor /= MAPL_UNDEFINED_REAL) ) then
         _ASSERT(this%target_lat >= -90.0, 'Latitude should be greater than -90.0 degrees')
         _ASSERT(this%target_lat <= 90, 'Latitude should be less than 90.0 degrees')
         this%stretched_cube = .true.
         this%target_lon_degrees = this%target_lon
         this%target_lat_degrees = this%target_lat
         this%target_lon=this%target_lon*pi/180.d0
         this%target_lat=this%target_lat*pi/180.d0
      end if
      ! Check decomposition/bounds
      ! WY notes: not necessary for this assert
      !_ASSERT(allocated(this%ims) .eqv. allocated(this%jms),'inconsistent options')
      call verify(this%nx, this%im_world, this%ims, rc=status)
      if (allocated(this%jms_2d)) then
        _ASSERT(size(this%jms_2d,2)==6, 'incompatible shape')
        _ASSERT(sum(this%jms_2d) == 6*this%im_world, 'incompatible shape')
      else
         call verify(this%ny, this%im_world, this%jms, rc=status)
      endif
      _RETURN(_SUCCESS)
   contains
      subroutine verify(n, m_world, ms, rc)
         integer, intent(inout) :: n
         integer, intent(inout) :: m_world
         integer, allocatable, intent(inout) :: ms(:)
         integer, optional, intent(out) :: rc
         integer :: status
         if (allocated(ms)) then
            _ASSERT(size(ms) > 0, 'must be > 0 PEs in each dimension')
            if (n == MAPL_UNDEFINED_INTEGER) then
               n = size(ms)
            else
               _ASSERT(n == size(ms), 'inconsistent specs')
            end if
            if (m_world == MAPL_UNDEFINED_INTEGER) then
               m_world = sum(ms)
            else
               _ASSERT(m_world == sum(ms), 'inconsistent specs')
            end if
         else
            _ASSERT(n /= MAPL_UNDEFINED_INTEGER,'n not specified')
            _ASSERT(m_world /= MAPL_UNDEFINED_INTEGER,'m_world not specified')
            allocate(ms(n), stat=status)
            _VERIFY(status)
            call MAPL_DecomposeDim (m_world, ms, n, symmetric=.true.)
         end if
         _RETURN(_SUCCESS)
      end subroutine verify
   end subroutine check_and_fill_consistency
Call graph
check_and_fill_consistency calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
cubedspheregridfactory_from_parameters calls check_and_fill_consistency
initialize_from_config_with_prefix calls check_and_fill_consistency
initialize_from_file_metadata calls check_and_fill_consistency
cubedspheregridfactory calls cubedspheregridfactory_from_parameters