child_ss – MAPL
child_ss Subroutine
11 statements
Source File
public subroutine child_ss(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
integer, intent(out) :: rc
Calls
Source Code
   subroutine child_ss(gridcomp, rc)
      type(ESMF_Gridcomp) :: gridcomp
      integer, intent(out) :: rc
      integer :: status
      rc=0
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_RUN, run_child, _RC)
   end subroutine child_ss
Call graph
child_ss calls anyexceptions, assert_that, mapl_gridcompsetentrypoint, sourcelocation