clear_log – MAPL
clear_log Subroutine
3 statements
Source File
public subroutine clear_log()
Arguments
None
Called by
Source Code
   subroutine clear_log()
      if (allocated(log)) deallocate(log)
   end subroutine clear_log
Call graph
setup calls clear_log
teardown calls clear_log
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_wasfinal calls setup
test_wasinit calls setup, teardown
test_wasrun_1 calls setup, teardown
test_wasrun_extra calls setup, teardown