clear_RequestHandle – MAPL
clear_RequestHandle Subroutine
17 statements
Source File
private subroutine clear_RequestHandle(this, rc)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine clear_RequestHandle(this, rc)
      class(BaseThread), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      class(AbstractRequestHandle), pointer :: rh_ptr
      type (IntegerRequestMapIterator) :: iter
      integer :: status
      iter = this%open_requests%begin()
      do while (iter /= this%open_requests%end())
         rh_ptr => iter%second()
         call rh_ptr%wait()
         call rh_ptr%data_reference%deallocate(status)
         _VERIFY(status)
         iter = this%open_requests%erase(iter)
      enddo
      _RETURN(_SUCCESS)
   end subroutine clear_RequestHandle
Call graph
clear_requesthandle calls erase, map_begin, mapl_return, mapl_verify, clear_requesthandle
map_begin calls map_s_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_erase_range calls erase
map_s_begin calls map_s_iter_next
mapl_throw_exception calls initialize
map_s_iter_next calls map_s_advpos
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait_all calls clear_requesthandle
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls wait_all, post_wait, finalize_io_clients_servers
terminate calls wait_all
wait calls wait_all
finalize_io_clients_servers calls terminate
post_wait calls post_wait_all
start calls clean_up
main calls terminate, run
mapl_bundlewritencpar calls post_wait
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run_model calls post_wait