clock_advance – MAPL
clock_advance Subroutine
20 statements
Source File
private recursive subroutine clock_advance(this, sourceState, exportState, clock, rc)
Type Bound
CouplerMetaComponent
Arguments
Type Intent Optional Attributes Name
class(CouplerMetaComponent), intent(inout) :: this
type(ESMF_State), intent(inout) :: sourceState
type(ESMF_State), intent(inout) :: exportState
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine clock_advance(this, sourceState, exportState, clock, rc)
        class(CouplerMetaComponent), intent(inout) :: this
        type(ESMF_State), intent(inout) :: sourceState
        type(ESMF_State), intent(inout) :: exportState
        type(ESMF_Clock), intent(inout) :: clock
        integer, optional, intent(out) :: rc
        integer :: status
        type(ESMF_Alarm) :: alarm
        logical :: is_ringing
        call ESMF_ClockGetAlarm(clock, "MAPL::RUN_ALARM", alarm, _RC)
        is_ringing = ESMF_AlarmIsRinging(alarm, _RC)
        _RETURN_UNLESS(is_ringing)
!#        call this%action%run(_RC) ! eventually needs access to clock
        _RETURN(_SUCCESS)
     end subroutine clock_advance
Call graph
clock_advance calls ESMF_AlarmIsRinging, ESMF_ClockGetAlarm, mapl_return, mapl_verify, clock_advance
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize