clock_advance – MAPL
clock_advance Subroutine
16 statements
Source File
private recursive subroutine clock_advance(gridcomp, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine clock_advance(gridcomp, importState, exportState, clock, rc)
      type(ESMF_GridComp) :: gridcomp
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      integer :: status
      type(CouplerMetaComponent), pointer :: coupler_meta
      coupler_meta => get_coupler_meta(gridcomp)
      call coupler_meta%clock_advance(importState, exportState, clock, _RC)
      ! TBD: is this where it belongs?
      call ESMF_ClockAdvance(clock, _RC)
      _RETURN(_SUCCESS)
   end subroutine clock_advance
Call graph
clock_advance calls ESMF_ClockAdvance, clock_advance, get_coupler_meta, mapl_return, mapl_verify, ESMF_AlarmIsRinging, ESMF_ClockGetAlarm
get_coupler_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception