compute_linear_map_fixedlevels_to_fixedlevels – MAPL
compute_linear_map_fixedlevels_to_fixedlevels Subroutine
24 statements
Source File
public subroutine compute_linear_map_fixedlevels_to_fixedlevels(src, dst, matrix, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: src(:)
real(kind=REAL32), intent(in) :: dst(:)
type(CSR_SparseMatrix_sp), intent(out) :: matrix
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine compute_linear_map_fixedlevels_to_fixedlevels(src, dst, matrix, rc)
      real(REAL32), intent(in) :: src(:)
      real(REAL32), intent(in) :: dst(:)
      type(SparseMatrix_sp), intent(out) :: matrix
      ! real(REAL32), allocatable, intent(out) :: matrix(:, :)
      integer, optional, intent(out) :: rc
      real(REAL32) :: val, weight(2)
      integer :: ndx, status
      type(IndexValuePair) :: pair(2) ! [pair(1), pair(2)] is a bracket
      _ASSERT(maxval(dst) <= maxval(src), "maxval(dst) > maxval(src)")
      _ASSERT(minval(dst) >= minval(src), "minval(dst) < minval(src)")
      ! allocate(matrix(size(dst), size(src)), source=0., _STAT)
      ! Expected 2 non zero entries in each row
      matrix = SparseMatrix_sp(size(dst), size(src), 2*size(dst))
      do ndx = 1, size(dst)
         val = dst(ndx)
         call find_bracket_(val, src, pair)
         call compute_linear_interpolation_weights_(val, pair%value_, weight)
         if (pair(1) == pair(2)) then
            ! matrix(ndx, pair(1)%index) = weight(1)
            call add_row(matrix, ndx, pair(1)%index, [weight(1)])
         else
            ! matrix(ndx, pair(1)%index) = weight(1)
            ! matrix(ndx, pair(2)%index) = weight(2)
            call add_row(matrix, ndx, pair(1)%index, [weight(1), weight(2)])
         end if
      end do
      _RETURN(_SUCCESS)
   end subroutine compute_linear_map_fixedlevels_to_fixedlevels
Call graph
compute_linear_map_fixedlevels_to_fixedlevels calls add_row, mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception
test_linear_map_fixedlevels_to_fixedlevels calls compute_linear_map_fixedlevels_to_fixedlevels
test_verticallinearmap calls compute_linear_map_fixedlevels_to_fixedlevels