compute_time_vector – MAPL
compute_time_vector Function
50 statements
Source File
private function compute_time_vector(this, metadata, rc) result(times)
Type Bound
timeData
Arguments
Type Intent Optional Attributes Name
class(timeData), intent(inout) :: this
type(FileMetadata), intent(inout) :: metadata
integer, intent(out), optional :: rc
Return Value real, allocatable, (:)
Calls
Called by
Source Code
  function compute_time_vector(this,metadata,rc) result(times)
    class(timeData), intent(inout) :: this
    type(FileMetadata), intent(inout) :: metadata
    integer, optional, intent(out) :: rc
    real, allocatable :: times(:)
    integer :: status
    type(ESMF_Time) :: currTime,startTime
    type(ESMF_TimeInterval) :: tint
    integer :: i
    real(ESMF_KIND_R8) :: tint_s
    type(ESMFTimeVectorIterator) :: iter
    type(ESMF_Time), pointer :: tptr
    ! for now return minutes, this should be optional argument in future
    this%tcount=this%tcount+1
    call ESMF_ClockGet(this%clock,currTime=currTime,rc=status)
    _VERIFY(status)
    startTime = this%get_start_time(metadata,rc=status)
    _VERIFY(status)
    currTime=currTime-this%offSet
    call this%tvec%push_back(currTime)
    iter = this%tvec%begin()
    allocate(times(this%tvec%size()))
    i=0
    do while (iter /= this%tvec%end())
       i=i+1
       tptr => iter%get()
       tint = tptr - startTime
       select case(trim(this%funits))
       case('seconds')
          call ESMF_TimeIntervalGet(tint,s_r8=tint_s,rc=status)
          _VERIFY(status)
          times(i)=tint_s
       case('minutes')
          call ESMF_TimeIntervalGet(tint,m_r8=tint_s,rc=status)
          _VERIFY(status)
          times(i)=tint_s
       case('hours')
          call ESMF_TimeIntervalGet(tint,h_r8=tint_s,rc=status)
          _VERIFY(status)
          times(i)=tint_s
       case('days')
          call ESMF_TimeIntervalGet(tint,d_r8=tint_s,rc=status)
          _VERIFY(status)
          times(i)=tint_s
       case default
       end select
       call iter%next()
    enddo
    _RETURN(ESMF_SUCCESS)
  end function compute_time_vector
Call graph
compute_time_vector calls ESMF_ClockGet, ESMF_TimeIntervalGet, get_start_time, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next, v_push_back
get_start_time calls mapl_verify, mapl_assert, get_attribute, get_value, get_variable, parse_time_string
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_return, mapl_assert, m_at
get_error_message calls at, insert
get_value calls mapl_return
get_variable calls mapl_return, mapl_verify, at
mapl_throw_exception calls initialize
parse_time_string calls mapl_verify, mapl_assert, ESMF_TimeSet
v_grow_to calls v_capacity, v_set_capacity
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_resize_32 calls resize
bundlepost calls compute_time_vector
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main