connect_to – MAPL
connect_to Subroutine
47 statements
Source File
private subroutine connect_to(this, src_spec, actual_pt, rc)
Type Bound
BracketSpec
Arguments
Type Intent Optional Attributes Name
class(BracketSpec), intent(inout) :: this
class(StateItemSpec), intent(inout) :: src_spec
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine connect_to(this, src_spec, actual_pt, rc)
      class(BracketSpec), intent(inout) :: this
      class(StateItemSpec), intent(inout) :: src_spec
      type(ActualConnectionPt), intent(in) :: actual_pt ! unused
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      _ASSERT(this%can_connect_to(src_spec), 'illegal connection')
      select type (src_spec)
      class is (BracketSpec)
         call this%destroy(_RC) ! use bundle from src
         this%payload = src_spec%payload
         call mirror_bracket(dst=this%bracket_size, src=src_spec%bracket_size)
         associate (n => this%bracket_size)
           this%field_specs = [(this%reference_spec, i=1,n)]
           src_spec%field_specs = [(src_spec%reference_spec, i=1,n)]
           do i = 1, this%bracket_size
              call this%field_specs(i)%create(_RC)
              call this%field_specs(i)%connect_to(src_spec%field_specs(i), actual_pt, _RC)
           end do
         end associate
      class default
         _FAIL('Cannot connect field spec to non field spec.')
      end select
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(actual_pt)
   contains
      subroutine mirror_bracket(dst, src)
         integer, allocatable, intent(inout) :: dst
         integer, allocatable, intent(inout) :: src
         if (.not. allocated(src)) then
            _ASSERT(allocated(dst), 'cannot mirror unallocated bracket size')
            src = dst
         end if
         if (.not. allocated(dst)) then
            _ASSERT(allocated(src), 'cannot mirror unallocated bracket size')
            dst = src
         end if
      end subroutine mirror_bracket
   end subroutine connect_to
Call graph
connect_to calls field_specs, mapl_assert, can_connect_to, connect_to, create, destroy, mapl_return, mapl_verify, mirror
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
can_connect_to calls mapl_return, can_connect_to, mapl_verify, of, can_connect_units
create calls mapl_return, mapl_verify, esmf_fieldemptycreate, mapl_fieldemptyset
destroy calls mapl_return, mapl_verify, esmf_fieldbundledestroy, destroy, esmf_fielddestroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_fieldemptyset calls mapl_assert, mapl_return, mapl_verify, ESMF_GeomGet, esmf_fieldemptyset
mapl_throw_exception calls initialize
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
test_connect_unique_mirror calls connect_to