connect_sibling – MAPL
connect_sibling Subroutine
70 statements
Source File
private recursive subroutine connect_sibling(this, dst_registry, src_registry, unusable, rc)
$ call move_alloc(from=new_spec, to=old_spec)
Type Bound
SimpleConnection
Arguments
Type Intent Optional Attributes Name
class(SimpleConnection), intent(in) :: this
type(HierarchicalRegistry), intent(inout), target :: dst_registry
type(HierarchicalRegistry), intent(inout), target :: src_registry
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine connect_sibling(this, dst_registry, src_registry, unusable, rc)
      class(SimpleConnection), intent(in) :: this
      type(HierarchicalRegistry), target, intent(inout) :: dst_registry
      type(HierarchicalRegistry), target, intent(inout) :: src_registry
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(StateItemSpecPtr), target, allocatable :: src_specs(:), dst_specs(:)
      class(StateItemSpec), pointer :: src_spec, dst_spec
      integer :: i, j
      integer :: status
      type(ConnectionPt) :: src_pt, dst_pt
      integer :: i_extension
      integer :: cost, lowest_cost
      class(StateItemSpec), pointer :: best_spec
      class(StateItemSpec), pointer :: last_spec
      class(StateItemSpec), target, allocatable :: old_spec
      class(StateItemSpec), allocatable, target :: new_spec
      type(ActualConnectionPt) :: effective_pt
      type(ActualConnectionPt) :: extension_pt
      type(GriddedComponentDriver), pointer :: source_coupler
      type(ActualPtVector), pointer :: src_actual_pts
      type(ActualConnectionPt), pointer :: best_pt
      src_pt = this%get_source()
      dst_pt = this%get_destination()
      dst_specs = dst_registry%get_actual_pt_SpecPtrs(dst_pt%v_pt, _RC)
      src_specs = src_registry%get_actual_pt_SpecPtrs(src_pt%v_pt, _RC)
      src_actual_pts => src_registry%get_actual_pts(src_pt%v_pt)
      _ASSERT(src_actual_pts%size() > 0, 'Empty virtual point?  This should not happen.')
      do i = 1, size(dst_specs)
         dst_spec => dst_specs(i)%ptr
         ! Connection is transitive -- if any src_specs can connect, all can connect.
         ! So we can just check this property on the 1st item.
         src_spec => src_specs(1)%ptr
         _ASSERT(dst_spec%can_connect_to(src_spec), "impossible connection")
         call find_closest_spec(dst_spec, src_specs, src_actual_pts, closest_spec=best_spec, closest_pt=best_pt, lowest_cost=lowest_cost, _RC)
         call best_spec%set_active()
         call activate_dependencies(best_spec, src_registry, _RC)
         ! Now build out sequence of extensions that form a chain to
         ! dst_spec.  This includes creating couplers (handled inside
         ! registry.)
         last_spec => best_spec
         old_spec = best_spec
         source_coupler => null()
         do i_extension = 1, lowest_cost
            new_spec = old_spec%make_extension(dst_spec, _RC)
            call new_spec%set_active()
            extension_pt = src_registry%extend(src_pt%v_pt, old_spec, new_spec, source_coupler=source_coupler, _RC)
            source_coupler => src_registry%get_export_coupler(extension_pt)
            ! ifort 2021.6 does something odd with the following move_alloc
!!$            call move_alloc(from=new_spec, to=old_spec)
            deallocate(old_spec)
            allocate(old_spec, source=new_spec)
            deallocate(new_spec)
            last_spec => old_spec
         end do
         call dst_spec%set_active()
         ! If couplers were needed, then the final coupler must also be
         ! referenced in the dst registry so that gridcomps can do update()
         ! requests.
         if (lowest_cost >= 1) then
            call dst_registry%add_import_coupler(ActualConnectionPt(dst_pt%v_pt), source_coupler)
         end if
         ! In the case of wildcard specs, we need to pass an actual_pt to
         ! the dst_spec to support multiple matches.  A bit of a kludge.
         effective_pt = ActualConnectionPt(VirtualConnectionPt(ESMF_STATEINTENT_IMPORT, &
              src_pt%v_pt%get_esmf_name(), comp_name=src_pt%v_pt%get_comp_name()))
         call dst_spec%connect_to(last_spec, effective_pt, _RC)
         call dst_spec%set_active()
      end do
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine connect_sibling
Call graph
connect_sibling calls can_connect_to, connect_to, mapl_assert, make_extension, activate_dependencies, add_import_coupler, extend_, find_closest_spec, get_actual_pt_specptrs, get_actual_pts, get_comp_name, get_destination, get_esmf_name, get_export_coupler, get_source, mapl_return, mapl_verify, set_active
connect calls connect_sibling