connect – MAPL
connect Subroutine
22 statements
Source File
private recursive subroutine connect(this, registry, rc)
Type Bound
SimpleConnection
Arguments
Type Intent Optional Attributes Name
class(SimpleConnection), intent(in) :: this
type(HierarchicalRegistry), intent(inout), target :: registry
integer, intent(out), optional :: rc
Calls
Source Code
   recursive subroutine connect(this, registry, rc)
      class(SimpleConnection), intent(in) :: this
      type(HierarchicalRegistry), target, intent(inout) :: registry
      integer, optional, intent(out) :: rc
      type(HierarchicalRegistry), pointer :: src_registry, dst_registry
      integer :: status
      type(VirtualConnectionPt) :: s_v_pt
      type(VirtualConnectionPt), pointer :: d_v_pt
      type(ConnectionPt) :: s_pt,d_pt
      type(ActualPtVec_MapIterator) :: iter
      type(ConnectionPt) :: src_pt, dst_pt
      src_pt = this%get_source()
      dst_pt = this%get_destination()
      dst_registry => registry%get_subregistry(dst_pt)
      src_registry => registry%get_subregistry(src_pt)
      _ASSERT(associated(src_registry), 'Unknown source registry')
      _ASSERT(associated(dst_registry), 'Unknown destination registry')
      call this%connect_sibling(dst_registry, src_registry, _RC)
      _RETURN(_SUCCESS)
   end subroutine connect
Call graph
connect calls mapl_assert, get_subregistry, connect_sibling, get_destination, get_source, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
connect_sibling calls mapl_assert, get_destination, get_source, mapl_return, mapl_verify, can_connect_to, connect_to, make_extension, activate_dependencies, add_import_coupler, extend_, find_closest_spec, get_actual_pt_specptrs, get_actual_pts, get_comp_name, get_esmf_name, get_export_coupler, set_active
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception