connect_to – MAPL
connect_to Subroutine
50 statements
Source File
private subroutine connect_to(this, src_spec, actual_pt, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(inout) :: this
class(StateItemSpec), intent(inout) :: src_spec
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine connect_to(this, src_spec, actual_pt, rc)
      class(FieldSpec), intent(inout) :: this
      class(StateItemSpec), intent(inout) :: src_spec
      type(ActualConnectionPt), intent(in) :: actual_pt ! unused
      integer, optional, intent(out) :: rc
      integer :: status
      interface mirror
         procedure :: mirror_typekind
         procedure :: mirror_string
      end interface mirror
      _ASSERT(this%can_connect_to(src_spec), 'illegal connection')
      select type (src_spec)
      class is (FieldSpec)
         ! ok
         call this%destroy(_RC)
         this%payload = src_spec%payload
         call mirror(dst=this%typekind, src=src_spec%typekind)
         call mirror(dst=this%units, src=src_spec%units)
      class default
         _FAIL('Cannot connect field spec to non field spec.')
      end select
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(actual_pt)
   contains
      subroutine mirror_typekind(dst, src)
         type(ESMF_TypeKind_Flag), intent(inout) :: dst, src
         if (dst == src) return
         if (dst == MAPL_TYPEKIND_MIRROR) then
            dst = src
         end if
         if (src == MAPL_TYPEKIND_MIRROR) then
            src = dst
         end if
         _ASSERT(dst == src, 'unsupported typekind mismatch')
      end subroutine mirror_typekind
      subroutine mirror_string(dst, src)
         character(len=:), allocatable, intent(inout) :: dst, src
         if (allocated(dst) .eqv. allocated(src)) return
         if (.not. allocated(dst)) then
            dst = src
         end if
         if (.not. allocated(src)) then
            src = dst
         end if
      end subroutine mirror_string
   end subroutine connect_to
Call graph
connect_to calls mapl_assert, can_connect_to, destroy, mapl_return, mapl_verify, mirror, connect_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
can_connect_to calls mapl_return, mapl_verify, of, can_connect_units
destroy calls mapl_return, mapl_verify, esmf_fielddestroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
test_connect_unique_mirror calls connect_to