connect – MAPL
connect Subroutine
39 statements
Source File
private recursive subroutine connect(this, registry, rc)
Type Bound
MatchConnection
Arguments
Type Intent Optional Attributes Name
class(MatchConnection), intent(in) :: this
type(HierarchicalRegistry), intent(inout), target :: registry
integer, intent(out), optional :: rc
Calls
Source Code
   recursive subroutine connect(this, registry, rc)
      class(MatchConnection), intent(in) :: this
      type(HierarchicalRegistry), target, intent(inout) :: registry
      integer, optional, intent(out) :: rc
      integer :: status
      type(ConnectionPt) :: src_pt, dst_pt
      type(HierarchicalRegistry), pointer :: src_registry, dst_registry
      type(VirtualConnectionPtVector) :: src_v_pts, dst_v_pts
      type(VirtualConnectionPt), pointer :: dst_pattern, src_v_pt
      type(VirtualConnectionPt) :: src_pattern, dst_v_pt
      type(VirtualConnectionPt), pointer :: s_v_pt, d_v_pt
      type(StateItemSpecPtr), allocatable :: dst_specs(:)
      integer :: i, j, k
      class(StateItemSpec), allocatable :: new_spec
      type(ConnectionPt) :: s_pt, d_pt
      src_pt = this%get_source()
      dst_pt = this%get_destination()
      src_registry => registry%get_subregistry(src_pt)
      dst_registry => registry%get_subregistry(dst_pt)
      dst_v_pts = dst_registry%filter(dst_pt%v_pt)
      do i = 1, dst_v_pts%size()
         dst_pattern => dst_v_pts%of(i)
         src_pattern = VirtualConnectionPt(ESMF_STATEINTENT_IMPORT, &
              '^'//dst_pattern%get_esmf_name()//'$', comp_name=dst_pattern%get_comp_name())
         dst_specs = dst_registry%get_actual_pt_SpecPtrs(dst_pattern, _RC)
         src_pattern = VirtualConnectionPt(ESMF_STATEINTENT_EXPORT, &
              dst_pattern%get_esmf_name(), comp_name=dst_pattern%get_comp_name())
         src_v_pts = src_registry%filter(src_pattern)
         do j = 1, src_v_pts%size()
            src_v_pt => src_v_pts%of(j)
            dst_v_pt = VirtualConnectionPt(ESMF_STATEINTENT_IMPORT, &
                 src_v_pt%get_esmf_name(), comp_name=src_v_pt%get_comp_name())
            s_pt = ConnectionPt(src_pt%component_name, src_v_pt)
            d_pt = ConnectionPt(dst_pt%component_name, dst_pattern)
            call registry%add_connection(SimpleConnection(s_pt, d_pt), _RC)
         end do
      end do
      _RETURN(_SUCCESS)
   end subroutine connect
Call graph
connect calls get_subregistry, of, add_connection, filter, get_actual_pt_specptrs, get_comp_name, get_destination, get_esmf_name, get_source, mapl_return, mapl_verify
add_connection calls mapl_return, mapl_verify, connect
filter calls map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, matches, vector_push_back
get_actual_pt_specptrs calls mapl_return, mapl_verify, at, of, get_item_spec
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception