connect – MAPL
connect Subroutine
15 statements
Source File
private recursive subroutine connect(this, registry, rc)
Type Bound
ReexportConnection
Arguments
Type Intent Optional Attributes Name
class(ReexportConnection), intent(in) :: this
type(HierarchicalRegistry), intent(inout), target :: registry
integer, intent(out), optional :: rc
Calls
Source Code
   recursive subroutine connect(this, registry, rc)
      class(ReexportConnection), intent(in) :: this
      type(HierarchicalRegistry), target, intent(inout) :: registry
      integer, optional, intent(out) :: rc
      integer :: status
      type(HierarchicalRegistry), pointer :: src_registry
      type(ConnectionPt) :: src_pt
      src_pt = this%get_source()
      src_registry => registry%get_subregistry(src_pt)
      _ASSERT(associated(src_registry), 'Unknown source registry')
      call this%connect_export_to_export(registry, src_registry, _RC)
      _RETURN(_SUCCESS)
   end subroutine connect
Call graph
connect calls mapl_assert, get_subregistry, connect_export_to_export, get_source, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
connect_export_to_export calls mapl_assert, get_source, mapl_return, mapl_verify, has_item_spec, link_item_spec, of, add_comp_name, get_actual_pts, get_destination, get_item_spec, get_name, is_internal, vector_begin, vector_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception