connect_all – MAPL
connect_all Subroutine
14 statements
Source File
private subroutine connect_all(this, src_comp, dst_comp, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
character(len=*), intent(in) :: src_comp
character(len=*), intent(in) :: dst_comp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine connect_all(this, src_comp, dst_comp, rc)
      class(OuterMetaComponent), intent(inout) :: this
      character(*), intent(in) :: src_comp
      character(*), intent(in) :: dst_comp
      integer, optional, intent(out) :: rc
      integer :: status
      class(Connection), allocatable :: conn
      _ASSERT(this%children%count(src_comp) == 1, 'No child component named <'//src_comp//'>.')
      _ASSERT(this%children%count(dst_comp) == 1, 'No child component named <'//dst_comp//'>.')
      conn = MatchConnection( &
           ConnectionPt(src_comp, VirtualConnectionPt(state_intent='export', short_name='^.*$')), &
           ConnectionPt(dst_comp, VirtualConnectionPt(state_intent='import', short_name='^.*$'))  &
           )
      call this%component_spec%add_connection(conn)
      _RETURN(_SUCCESS)
   end subroutine connect_all
Call graph
connect_all calls mapl_assert, add_connection, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_connection calls vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
gridcomp_connect_all calls connect_all
mapl_connectall calls gridcomp_connect_all
setservices calls mapl_connectall