connect_to – MAPL
connect_to Subroutine
32 statements
Source File
private subroutine connect_to(this, src_spec, actual_pt, rc)
Type Bound
WildcardSpec
Arguments
Type Intent Optional Attributes Name
class(WildcardSpec), intent(inout) :: this
class(StateItemSpec), intent(inout) :: src_spec
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine connect_to(this, src_spec, actual_pt, rc)
      class(WildcardSpec), intent(inout) :: this
      class(StateItemSpec), intent(inout) :: src_spec
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      call with_target_attribute(this, src_spec, actual_pt, rc)
      _RETURN(_SUCCESS)
   contains
      subroutine with_target_attribute(this, src_spec, actual_pt, rc)
         class(WildcardSpec), target, intent(inout) :: this
         class(StateItemSpec), intent(inout) :: src_spec
         type(ActualConnectionPt), intent(in) :: actual_pt
         integer, optional, intent(out) :: rc
         integer :: status
         class(StateItemSpec), pointer :: spec
         logical :: can_connect
         can_connect = this%can_connect_to(src_spec, _RC)
         _ASSERT(can_connect, 'illegal connection')
         _ASSERT(this%matched_items%count(actual_pt) == 0, 'duplicate connection pt')
         call this%matched_items%insert(actual_pt, this%reference_spec)
         spec => this%matched_items%of(actual_pt)
         call spec%create(_RC)
         call spec%connect_to(src_spec, actual_pt, _RC)
         _RETURN(ESMF_SUCCESS)
      end subroutine with_target_attribute
   end subroutine connect_to
Call graph
connect_to calls connect_to, create, mapl_assert, insert, can_connect_to, map_of, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
can_connect_to calls mapl_return, mapl_verify, can_connect_to
map_of calls insert, map_s_iter_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
map_s_iter_of calls map_s_get_value
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_s_insert_initializer_list calls insert