connect_export_to_export – MAPL
connect_export_to_export Subroutine
54 statements
Source File
private subroutine connect_export_to_export(this, registry, src_registry, unusable, rc)
Type Bound
ReexportConnection
Arguments
Type Intent Optional Attributes Name
class(ReexportConnection), intent(in) :: this
type(HierarchicalRegistry), intent(inout) :: registry
type(HierarchicalRegistry), intent(in) :: src_registry
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine connect_export_to_export(this, registry, src_registry, unusable, rc)
      class(ReexportConnection), intent(in) :: this
      type(HierarchicalRegistry), intent(inout) :: registry
      type(HierarchicalRegistry), intent(in) :: src_registry
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ActualPtVectorIterator) :: iter
      class(StateItemSpec), pointer :: spec
      type(ActualConnectionPt), pointer :: src_actual_pt
      type(ActualConnectionPt), allocatable :: dst_actual_pt
      type(ActualPtVector), pointer :: actual_pts
      integer :: status
      type(VirtualConnectionPt) :: src_pt, dst_pt
      type(ConnectionPt) :: src, dst
      src = this%get_source()
      dst = this%get_destination()
      src_pt = src%v_pt
      dst_pt = dst%v_pt
      _ASSERT(.not. registry%has_item_spec(dst_pt), 'Specified virtual point already exists in this registry')
      _ASSERT(src_registry%has_item_spec(src_pt), 'Specified virtual point does not exist.')
      actual_pts => src_registry%get_actual_pts(src_pt)
      associate (e => actual_pts%end())
        iter = actual_pts%begin()
        do while (iter /= e)
           src_actual_pt => iter%of()
           if (src_actual_pt%is_internal()) then
              ! Don't encode with comp name
              dst_actual_pt = ActualConnectionPt(dst_pt)
           else
              dst_actual_pt = src_actual_pt%add_comp_name(src_registry%get_name())
           end if
           spec => src_registry%get_item_spec(src_actual_pt)
           _ASSERT(associated(spec), 'This should not happen.')
           call registry%link_item_spec(dst_pt, spec, dst_actual_pt, _RC)
           call iter%next()
        end do
      end associate
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   contains
      function str_replace(buffer, pattern, replacement) result(new_str)
         character(:), allocatable :: new_str
         character(*), intent(in) :: buffer
         character(*), intent(in) :: pattern
         character(*), intent(in) :: replacement
         integer :: idx
         idx = scan(buffer, pattern)
         new_str = buffer(:idx-1) // replacement // buffer(idx+len(pattern):)
      end function str_replace
   end subroutine connect_export_to_export
Call graph
connect_export_to_export calls mapl_assert, has_item_spec, link_item_spec, of, add_comp_name, get_actual_pts, get_destination, get_item_spec, get_name, get_source, is_internal, mapl_return, mapl_verify, vector_begin, vector_iter_next
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_comp_name calls add_comp_name
get_actual_pts calls at
get_item_spec calls mapl_return, mapl_verify, at
is_internal calls is_internal
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
connect calls connect_export_to_export