connect_to – MAPL
connect_to Subroutine
25 statements
Source File
private subroutine connect_to(this, src_spec, actual_pt, rc)
Type Bound
ServiceSpec
Arguments
Type Intent Optional Attributes Name
class(ServiceSpec), intent(inout) :: this
class(StateItemSpec), intent(inout) :: src_spec
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine connect_to(this, src_spec, actual_pt, rc)
      class(ServiceSpec), intent(inout) :: this
      class(StateItemSpec), intent(inout) :: src_spec
      type(ActualConnectionPt), intent(in) :: actual_pt ! unused
      integer, optional, intent(out) :: rc
      integer :: fieldCount
      type(ESMF_Field), allocatable :: fieldList(:)
      integer :: status
      logical :: can_connect
      can_connect = this%can_connect_to(src_spec, _RC)
      _ASSERT(can_connect, 'illegal connection')
      select type (src_spec)
      class is (ServiceSpec)
         src_spec%dependency_specs = [src_spec%dependency_specs, this%dependency_specs]
      class default
         _FAIL('Cannot connect field spec to non field spec.')
      end select
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(actual_pt)
   end subroutine connect_to
Call graph
connect_to calls mapl_assert, can_connect_to, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
can_connect_to calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize