copy_callbacks – MAPL
copy_callbacks Subroutine
31 statements
Source File
private subroutine copy_callbacks(state, multi_states, rc)
Uses
mapl_ESMF_Interfaces
mapl_CallbackMap
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(ESMF_State), intent(inout) :: multi_states(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine copy_callbacks(state, multi_states, rc)
       use mapl_ESMF_Interfaces
       use mapl_CallbackMap
       type(ESMF_State), intent(inout) :: state
       type(ESMF_State), intent(inout) :: multi_states(:)
       integer, optional, intent(out) :: rc
       integer :: n_multi, i
       integer :: status
       type(CallbackMethodWrapper), pointer :: wrapper
       type(CallbackMap), pointer :: callbacks
       type(CallbackMapIterator) :: iter
       procedure(), pointer :: userRoutine
       n_multi = size(multi_states)
       call get_callbacks(state, callbacks, _RC)
       _ASSERT(associated(callbacks), 'callbacks must be associated')
       associate( e => callbacks%end())
          iter = callbacks%begin()
          do while (iter /= e)
             wrapper => iter%second()
             do i = 1, n_multi
                userRoutine => wrapper%userRoutine
                call ESMF_MethodAdd(multi_states(i), label=iter%first(), userRoutine=userRoutine, _RC)
             end do
             call iter%next()
          end do
       end associate
       _RETURN(ESMF_SUCCESS)
    end subroutine copy_callbacks
Call graph
copy_callbacks calls ESMF_MethodAdd, mapl_assert, get_callbacks, map_begin, map_iter_first, map_iter_next, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_callbacks calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoSet
map_begin calls map_s_begin
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_iter_of calls map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_s_advpos calls map_s_get_child, to_node
map_s_iter_of calls map_s_get_value
make_substates_from_num_grids calls copy_callbacks, make_substates
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates
activate_threading calls create_subobjects