create_grid – MAPL
create_grid Function
21 statements
Source File
private function create_grid(this, key, currTime, grid_type, rc) result(ogrid)
call grid_validate (ogrid,)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
character(len=*), intent(in) :: key
type(ESMF_Time), intent(inout) :: currTime
character(len=*), intent(in), optional :: grid_type
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
  function create_grid(this, key, currTime, grid_type, rc)  result(ogrid)
    type (ESMF_Grid) :: ogrid
    class(samplerHQ)  :: this
    character(len=*), intent(in) :: key
    type(ESMF_Time), intent(inout) :: currTime
    character(len=*), optional, intent(in) :: grid_type
    integer, intent(out), optional :: rc
    integer :: status
    type(ESMF_Config) :: config_grid
    character(len=ESMF_MAXSTR) :: time_string
    if (present(grid_type)) this%grid_type = trim(grid_type)
    config_grid = this%find_config(key)
    call ESMF_TimeGet(currTime, timeString=time_string, _RC)
    !
    ! -- the `ESMF_ConfigSetAttribute` shows a risk
    !    to overwrite the nextline in config
    !
    call ESMF_ConfigSetAttribute( config_grid, trim(time_string), label=trim(key)//'.Epoch_init:', _RC)
    ogrid = grid_manager%make_grid(config_grid, prefix=trim(key)//'.', _RC )
    !!    call grid_validate (ogrid,)
    _RETURN(_SUCCESS)
  end function create_grid
Call graph
create_grid calls ESMF_ConfigSetAttribute, ESMF_TimeGet, make_grid, find_config, mapl_return, mapl_verify
find_config calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
make_grid_from_distgrid calls make_grid, mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoSet, make_factory
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
destroy_rh_regen_ogrid calls create_grid
initialize calls create_grid
run calls destroy_rh_regen_ogrid