create_communicators – MAPL
create_communicators Subroutine
32 statements
Source File
public subroutine create_communicators(this)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
Calls
Called by
Call graph
create_communicators calls mpi_barrier, mpi_comm_rank, mpi_comm_split, mapl_verify
mapl_verify calls mapl_throw_exception
checkpoint_tester calls create_communicators