create_arrays – MAPL
create_arrays Subroutine
47 statements
Source File
public subroutine create_arrays(this)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
Calls
Called by
Call graph
create_arrays calls mpi_comm_rank, mpi_comm_size, allocate_n_arrays, compute_decomposition, mapl_verify
allocate_n_arrays calls mpi_comm_rank, mapl_verify
mapl_verify calls mapl_throw_exception
checkpoint_tester calls create_arrays