create_holding_field – MAPL
create_holding_field Subroutine
19 statements
Source File
private subroutine create_holding_field(state, primary_name, derived_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
character(len=*), intent(in) :: primary_name
character(len=*), intent(in) :: derived_name
integer, intent(out), optional :: rc
Calls
Called by
Call graph
create_holding_field calls ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_fieldemptycreate, mapl_stateadd, mapl_return, mapl_verify
mapl_stateadd calls mapl_stateaddbundle, mapl_stateaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_stateaddbundle calls mapl_stateaddbundle, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoIsPresent, ESMF_InfoRemove, esmf_fieldbundleget, esmf_stateadd
mapl_stateaddfield calls mapl_stateaddfield, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoIsPresent, ESMF_InfoRemove, esmf_fieldget, esmf_stateadd
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_ calls create_holding_field