create_fields – MAPL
create_fields Module Subroutine
47 statements
Source File
module subroutine create_fields(elements, geom, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: elements(NI,NJ)
type(ESMF_Geom), intent(in) :: geom
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine create_fields(elements, geom, rc)
      type(ESMF_Field), intent(inout) :: elements(NI,NJ)
      type(ESMF_Geom), intent(in) :: geom
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i, j
      type(ESMF_GeomType_Flag) :: geomtype
      type(ESMF_Grid) :: grid
      type(ESMF_LocStream) :: locstream
      type(ESMF_Mesh) :: mesh
      call ESMF_GeomGet(geom, geomtype=geomtype, _RC)
      if (geomtype == ESMF_GEOMTYPE_GRID) then
         call ESMF_GeomGet(geom, grid=grid, _RC)
         do j = 1, nj
            do i = 1, ni
               elements(i,j) = ESMF_FieldCreate(grid, typekind=ESMF_TYPEKIND_R8, &
                    staggerloc=ESMF_STAGGERLOC_CENTER, _RC)
            end do
         end do
      elseif (geomtype == ESMF_GEOMTYPE_LOCSTREAM) then
         call ESMF_GeomGet(geom, locstream=locstream, _RC)
         do j = 1, nj
            do i = 1, ni
               elements(i,j) = ESMF_FieldCreate(locstream, typekind=ESMF_TYPEKIND_R8, _RC)
            end do
         end do
      elseif (geomtype == ESMF_GEOMTYPE_MESH) then
         call ESMF_GeomGet(geom, mesh=mesh, _RC)
         do j = 1, nj
            do i = 1, ni
               elements(i,j) = ESMF_FieldCreate(mesh, typekind=ESMF_TYPEKIND_R8, _RC)
            end do
         end do
      elseif (geomtype == ESMF_GEOMTYPE_XGRID) then
         _FAIL('Unsupported geomtype XGRID')
      else
         _FAIL('Unknown geomtype.')
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine create_fields
Call graph
create_fields calls ESMF_GeomGet, esmf_fieldcreate, mapl_assert, mapl_return, mapl_verify, create_fields
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_gridvectorbasis calls create_fields, new_gridvectorbasis
new_ns_basis calls create_fields, new_ns_basis
gridvectorbasis calls new_gridvectorbasis
ns_vectorbasis calls new_ns_basis