create_grid_comp_primary – MAPL
create_grid_comp_primary Function
39 statements
Source File
private recursive function create_grid_comp_primary(name, set_services, config, clock, unusable, petlist, rc) result(gridcomp)
Uses
mapl3g_UserSetServices
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
class(AbstractUserSetServices), intent(in) :: set_services
type(ESMF_HConfig), intent(in) :: config
type(ESMF_Clock), intent(in) :: clock
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: petlist(:)
integer, intent(out), optional :: rc
Return Value type(ESMF_GridComp)
Calls
Called by
Source Code
   recursive type(ESMF_GridComp) function create_grid_comp_primary( &
        name, set_services, config, clock, unusable, petlist, rc) result(gridcomp)
      use :: mapl3g_UserSetServices, only: AbstractUserSetServices
      character(*), intent(in) :: name
      class(AbstractUserSetServices), intent(in) :: set_services
      type(ESMF_HConfig), intent(in) :: config
      type(ESMF_Clock), intent(in) :: clock
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: petlist(:)
      integer, optional, intent(out) :: rc
      type(ESMF_GridComp) :: user_gridcomp
      type(OuterMetaComponent), pointer :: outer_meta
      type(OuterMetaComponent) :: outer_meta_tmp
      type(ESMF_Clock) :: user_clock
      type(GriddedComponentDriver) :: user_gc_driver
      integer :: status
      gridcomp = ESMF_GridCompCreate(name=outer_name(name), petlist=petlist,  _RC)
      call set_is_generic(gridcomp, _RC)
      user_gridcomp = ESMF_GridCompCreate(name=name, petlist=petlist,  _RC)
      call set_is_generic(user_gridcomp, .false., _RC)
      call attach_outer_meta(gridcomp, _RC)
      outer_meta => get_outer_meta(gridcomp, _RC)
      user_clock = ESMF_ClockCreate(clock, _RC)
      user_gc_driver = GriddedComponentDriver(user_gridcomp, user_clock, MultiState())
#ifndef __GFORTRAN__
      outer_meta = OuterMetaComponent(gridcomp, user_gc_driver, config)
#else
      ! GFortran 12 & 13 cannot directly assign to outer_meta.  But
      ! the assignment works for an object without the POINTER
      ! attribute.  An internal procedure is a workaround, but
      ! ... ridiculous.
      call ridiculous(outer_meta, OuterMetaComponent(gridcomp, user_gc_driver, config))
#endif
      call outer_meta%setservices(set_services, _RC)
      call outer_meta%init_meta(_RC)
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(unusable)
#ifdef __GFORTRAN__
   contains
      subroutine ridiculous(a, b)
         type(OuterMetaComponent), intent(out) :: a
         type(OuterMetaComponent), intent(in) :: b
         a = b
      end subroutine ridiculous
#endif
   end function create_grid_comp_primary
Call graph
create_grid_comp_primary calls ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic
get_outer_meta calls get_outer_meta_from_outer_gc
setservices_ calls setservices_
attach_outer_meta calls mapl_return, mapl_assert, mapl_usercompsetinternalstate
init_meta calls mapl_return, mapl_verify, get_logger, get_name
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_is_generic calls mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoSet
create_grid_comp calls create_grid_comp_primary
add_child_by_name calls create_grid_comp, add_child_by_name
make_driver calls create_grid_comp
setup calls create_grid_comp
test_is_generic calls create_grid_comp
test_mapl_invalid_name calls create_grid_comp
mapl_run_driver calls make_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
test_wasfinal calls setup
test_wasinit calls setup
test_wasrun_1 calls setup
test_wasrun_extra calls setup
run_geos calls mapl_run_driver