create_output_grid – MAPL
create_output_grid Function
62 statements
Source File
function create_output_grid(grid_name, lm, rc) result(new_grid)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: grid_name
integer, intent(in) :: lm
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
   function create_output_grid(grid_name,lm,rc) result(new_grid)
      type(ESMF_Grid) :: new_grid
      character(len=*), intent(inout) :: grid_name
      integer, intent(in) :: lm
      integer, optional, intent(out) :: rc
      type(ESMF_Config) :: cf
      integer :: nn,im_world,jm_world,nx, ny
      character(len=5) :: imsz,jmsz
      character(len=2) :: pole,dateline
      nn   = len_trim(grid_name)
      imsz = grid_name(3:index(grid_name,'x')-1)
      jmsz = grid_name(index(grid_name,'x')+1:nn-3)
      pole = grid_name(1:2)
      dateline = grid_name(nn-1:nn)
      read(IMSZ,*) im_world
      read(JMSZ,*) jm_world
      cf = MAPL_ConfigCreate(_RC)
      call MAPL_ConfigSetAttribute(cf,value=lm, label=trim(grid_name)//".LM:",_RC)
      if (dateline=='CF') then
         call MAPL_MakeDecomposition(nx,ny,reduceFactor=6,_RC)
         call MAPL_ConfigSetAttribute(cf,value=NX, label=trim(grid_name)//".NX:",_RC)
         call MAPL_ConfigSetAttribute(cf,value="Cubed-Sphere", label=trim(grid_name)//".GRID_TYPE:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=6, label=trim(grid_name)//".NF:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=im_world,label=trim(grid_name)//".IM_WORLD:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=ny, label=trim(grid_name)//".NY:",_RC)
      else if (dateline=='TM') then
         _FAIL("Tripolar not yet implemented for outpout")
      else
         call MAPL_MakeDecomposition(nx,ny,_RC)
         call MAPL_ConfigSetAttribute(cf,value=NX, label=trim(grid_name)//".NX:",_RC)
         call MAPL_ConfigSetAttribute(cf,value="LatLon", label=trim(grid_name)//".GRID_TYPE:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=im_world,label=trim(grid_name)//".IM_WORLD:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=jm_world,label=trim(grid_name)//".JM_WORLD:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=ny, label=trim(grid_name)//".NY:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=pole, label=trim(grid_name)//".POLE:",_RC)
         call MAPL_ConfigSetAttribute(cf,value=dateline, label=trim(grid_name)//".DATELINE:",_RC)
         if (pole=='XY' .and. dateline=='XY') then
            _FAIL("regional lat-lon output not supported")
         end if
      end if
      new_grid = grid_manager%make_grid(cf,prefix=trim(grid_name)//".",_RC)
      if (present(rc)) then
         rc=_SUCCESS
      end if
   end function create_output_grid
Call graph
create_output_grid calls mapl_assert, mapl_configsetattribute, mapl_makedecomposition, make_grid, mapl_abort, mapl_configcreate, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_makedecomposition calls mapl_makedecomposition, mapl_verify, mapl_return, ESMF_VMGet, ESMF_VMGetCurrent
mapl_abort calls mpi_abort
mapl_configcreate calls ESMF_ConfigCreate, buffer, mapl_return
mapl_verify calls mapl_throw_exception
make_grid_from_distgrid calls make_grid, mapl_verify, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoSet, make_factory
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_configsetattribute_int32 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_ints32 calls mapl_assert, mapl_configsetattribute, mapl_verify, mapl_return
mapl_configsetattribute_real32 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_real64 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_reals32 calls mapl_assert, mapl_configsetattribute, mapl_verify, mapl_return
mapl_configsetattribute_string calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
time_ave calls create_output_grid