create_basic_grid – MAPL
create_basic_grid Function
34 statements
Source File
private function create_basic_grid(this, unusable, rc) result(grid)
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
   function create_basic_grid(this, unusable, rc) result(grid)
      type (ESMF_Grid) :: grid
      class (LatLonGridFactory), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ESMF_Info) :: infoh
      integer :: status
      _UNUSED_DUMMY(unusable)
      if (this%periodic) then
         grid = ESMF_GridCreate1PeriDim( &
              & name = this%grid_name, &
              & countsPerDEDim1=this%ims, &
              & countsPerDEDim2=this%jms, &
              & indexFlag=ESMF_INDEX_DELOCAL, &
              & gridEdgeLWidth=[0,0], &
              & gridEdgeUWidth=[0,1], &
              & coordDep1=[1,2], &
              & coordDep2=[1,2], &
              & coordSys=ESMF_COORDSYS_SPH_RAD, &
              & rc=status)
         _VERIFY(status)
      else
         grid = ESMF_GridCreateNoPeriDim( &
              & name = this%grid_name, &
              & countsPerDEDim1=this%ims, &
              & countsPerDEDim2=this%jms, &
              & indexFlag=ESMF_INDEX_DELOCAL, &
              & gridEdgeLWidth=[0,0], &
              & gridEdgeUWidth=[1,1], &
              & coordDep1=[1,2], &
              & coordDep2=[1,2], &
              & coordSys=ESMF_COORDSYS_SPH_RAD, &
              & rc=status)
         _VERIFY(status)
      end if
      ! Allocate coords at default stagger location
      call ESMF_GridAddCoord(grid, rc=status)
      _VERIFY(status)
      call ESMF_GridAddCoord(grid, staggerloc=ESMF_STAGGERLOC_CORNER, rc=status)
      _VERIFY(status)
      call ESMF_InfoGetFromHost(grid,infoh,rc=status)
      _VERIFY(status)
      if (this%lm /= MAPL_UNDEFINED_INTEGER) then
         call ESMF_InfoSet(infoh,'GRID_LM',this%lm,rc=status)
         _VERIFY(status)
      end if
      call ESMF_InfoSet(infoh,'GridType','LatLon',rc=status)
      _VERIFY(status)
      if (.not.this%periodic) then
         call ESMF_InfoSet(infoh,key='Global',value=.false.,rc=status)
         _VERIFY(status)
      end if
      _RETURN(_SUCCESS)
   end function create_basic_grid
Call graph
create_basic_grid calls ESMF_GridAddCoord, ESMF_GridCreate1PeriDim, ESMF_GridCreateNoPeriDim, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_new_grid calls create_basic_grid