create_clock – MAPL
create_clock Function
19 statements
Source File
private function create_clock(rc) result(clock)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Return Value type(ESMF_Clock)
Calls
Called by
Source Code
   function create_clock(rc) result(clock)
      type(ESMF_Clock) :: clock
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Time) :: start_time, stop_time
      type(ESMF_TimeInterval) :: time_step
      call ESMF_CalendarSetDefault(ESMF_CALKIND_GREGORIAN, _RC)
      call ESMF_TimeIntervalSet(time_step, s=900, _RC)
      call ESMF_TimeSet(start_time, timeString='2023-12-22T21:00:00', _RC)
      call ESMF_TimeSet(stop_time, timeString='2023-12-23T21:00:00', _RC)
      clock = ESMF_ClockCreate(timestep=time_step, startTime=start_time, stopTime=stop_time, _RC)
      _RETURN(_SUCCESS)
   end function create_clock
Call graph
create_clock calls ESMF_CalendarSetDefault, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_gc_t calls create_clock
main calls make_gc_t