create_flipped_field – MAPL
create_flipped_field Function
54 statements
Source File
private function create_flipped_field(field, rc) result(flipped_field)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Called by
Source Code
   function create_flipped_field(field,rc) result(flipped_field)
      type(ESMF_Field), intent(inout) :: field
      integer, intent(out), optional :: rc
      type(ESMF_Field) :: flipped_field
      integer :: status,rank
      character(len=ESMF_MAXSTR) :: fname
      integer :: vloc,lb(1),ub(1)
      type(ESMF_Grid) :: grid
      type(ESMF_TYPEKIND_FLAG) :: tk
      real(KIND=ESMF_KIND_R4), pointer :: ptr_r4_in(:,:,:),ptr_r4_out(:,:,:)
      real(KIND=ESMF_KIND_R8), pointer :: ptr_r8_in(:,:,:),ptr_r8_out(:,:,:)
      type(ESMF_Info) :: infoh
      call ESMF_FieldGet(field,rank=rank,name=fname,rc=status)
      _VERIFY(status)
      if (rank==3) then
         call ESMF_InfoGetFromHost(field,infoh,rc=status)
         _VERIFY(status)
         call ESMF_InfoGet(infoh,'VLOCATION',vloc,rc=status)
         _VERIFY(status)
         if (vloc==MAPL_VLocationCenter .or. vloc==MAPL_VLocationEdge) then
            call ESMF_FieldGet(Field,grid=grid,ungriddedLbound=lb,ungriddedUBound=ub,typekind=tk,rc=status)
            _VERIFY(status)
            flipped_field = ESMF_FieldCreate(grid,tk,name=trim(fname),ungriddedLBound=lb,ungriddedUBound=ub,rc=status)
            _VERIFY(status)
            call MAPL_FieldCopyAttributes(field_in=field,field_out=flipped_field,rc=status)
            _VERIFY(status)
            if (tk==ESMF_TYPEKIND_R4) then
               call ESMF_FieldGet(field,farrayptr=ptr_r4_in,rc=status)
               _VERIFY(status)
               call ESMF_FieldGet(flipped_field,farrayptr=ptr_r4_out,rc=status)
               _VERIFY(status)
               ptr_r4_out=ptr_r4_in
            else if (tk==ESMF_TYPEKIND_R8) then
               call ESMF_FieldGet(field,farrayptr=ptr_r8_in,rc=status)
               _VERIFY(status)
               call ESMF_FieldGet(flipped_field,farrayptr=ptr_r8_out,rc=status)
               _VERIFY(status)
               ptr_r8_out=ptr_r8_in
            end if
            call flip_field(flipped_field,rc=status)
            _VERIFY(status)
            call ESMF_InfoGetFromHost(flipped_field,infoh,rc=status)
            _VERIFY(status)
            call ESMF_InfoSet(infoh,'FLIPPED',"flipped",rc=status)
            _VERIFY(status)
         else
            flipped_field=field
         end if
      else
         flipped_field=field
      end if
      _RETURN(_SUCCESS)
   end function create_flipped_field
Call graph
create_flipped_field calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_fieldcreate, esmf_fieldget, mapl_fieldcopyattributes, flip_field, mapl_return, mapl_verify
mapl_fieldcopyattributes calls mapl_fieldcopyattributes, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify
flip_field calls ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_statevarwritencpar calls create_flipped_field
mapl_varwritencpar calls mapl_statevarwritencpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile