create – MAPL
create Subroutine
11 statements
Source File
private subroutine create(this, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create(this, rc)
      class(FieldSpec), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      this%payload = ESMF_FieldEmptyCreate(_RC)
      call MAPL_FieldEmptySet(this%payload, this%geom, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine create
Call graph
create calls esmf_fieldemptycreate, mapl_fieldemptyset, mapl_return, mapl_verify
mapl_fieldemptyset calls mapl_return, mapl_verify, ESMF_GeomGet, esmf_fieldemptyset, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
connect_to calls create
test_vertical calls create
test_connect_unique_mirror calls connect_to