create_file – MAPL
create_file Subroutine
87 statements
Source File
public subroutine create_file(this)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
Calls
Called by
Call graph
create_file calls mpi_barrier, mpi_comm_rank, mpi_info_create, mpi_info_set, nf90_create, nf90_def_dim, nf90_def_var, nf90_def_var_fill, nf90_enddef, mapl_verify
mapl_verify calls mapl_throw_exception
checkpoint_tester calls create_file