create_clock – MAPL
create_clock Function
33 statements
Source File
private function create_clock(hconfig, rc) result(clock)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(ESMF_Clock)
Calls
Called by
Source Code
   function create_clock(hconfig, rc) result(clock)
      type(ESMF_Clock) :: clock
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Time) :: startTime, stopTime, end_of_segment
      type(ESMF_TimeInterval) :: timeStep, segment_duration
      type(ESMF_HConfig) :: clock_config
      clock_config = ESMF_HConfigCreateAt(hconfig, keystring='clock', _RC)
      call ESMF_CalendarSetDefault(ESMF_CALKIND_GREGORIAN,_RC)
      call set_time(startTime, 'start', clock_config, _RC)
      call ESMF_TimePrint(startTime, options='string', prestring='start time set: ' ,_RC)
      call set_time(stopTime, 'stop', clock_config, _RC)
      call ESMF_TimePrint(stopTime, options='string', prestring='stop time set: ', _RC)
      call set_time_interval(timeStep, 'dt', clock_config, _RC)
      call set_time_interval(segment_duration, 'segment_duration', clock_config, _RC)
      end_of_segment = startTime + segment_duration
      if (end_of_segment < stopTime) stopTime = end_of_segment
      call ESMF_TimePrint(stopTime, options='string', prestring='actual stop time set: ', _RC)
      clock = ESMF_ClockCreate(timeStep=timeStep, startTime=startTime, stopTime=stopTime, _RC)
      _RETURN(_SUCCESS)
   end function create_clock
Call graph
create_clock calls ESMF_CalendarSetDefault, ESMF_ClockCreate, ESMF_TimePrint, esmf_hconfigcreateat, mapl_return, mapl_verify, set_time, set_time_interval
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_time calls mapl_return, mapl_verify, ESMF_TimeSet, esmf_hconfigasstring
set_time_interval calls mapl_return, mapl_verify, ESMF_TimeIntervalSet, esmf_hconfigasstring, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
make_driver calls create_clock
mapl_run_driver calls make_driver
run_geos calls mapl_run_driver
geos calls run_geos