create_time_variable – MAPL
create_time_variable Function
16 statements
Source File
public function create_time_variable(current_time, rc) result(time_var)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: current_time
integer, intent(out), optional :: rc
Return Value type(Variable)
Calls
Called by
Source Code
   function create_time_variable(current_time, rc) result(time_var)
      type(Variable) :: time_var
      type(ESMF_Time), intent(in) :: current_time
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=ESMF_MAXSTR) :: iso_time_string
      call ESMF_TimeGet(current_time, timeString=iso_time_string, _RC)
      iso_time_string = "minutes since "//trim(iso_time_string)
      time_var = Variable(type=PFIO_REAL32, dimensions='time')
      call time_var%add_attribute('long_name', 'time')
      call time_var%add_attribute('units', iso_time_string, _RC)
      _RETURN(_SUCCESS)
   end function create_time_variable
Call graph
create_time_variable calls ESMF_TimeGet, add_attribute, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
bundle_to_metadata calls create_time_variable