create_basic_grid – MAPL
create_basic_grid Module Function
27 statements
Source File
module function create_basic_grid(spec, unusable, rc) result(grid) Interface →
Arguments
Type Intent Optional Attributes Name
type(LatLonGeomSpec), intent(in) :: spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
   module function create_basic_grid(spec, unusable, rc) result(grid)
      type(ESMF_Grid) :: grid
      type(LatLonGeomSpec), intent(in) :: spec
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type(LonAxis) :: lon_axis
      type(LatAxis) :: lat_axis
      type(LatLonDecomposition) :: decomp
      lon_axis = spec%get_lon_axis()
      lat_axis = spec%get_lat_axis()
      decomp = spec%get_decomposition()
      if (lon_axis%is_periodic()) then
         grid = ESMF_GridCreate1PeriDim( &
              & countsPerDEDim1=decomp%get_lon_distribution(), &
              & countsPerDEDim2=decomp%get_lat_distribution(), &
              & indexFlag=ESMF_INDEX_DELOCAL, &
              & gridEdgeLWidth=[0,0], &
              & gridEdgeUWidth=[0,1], &
              & coordDep1=[1,2], &
              & coordDep2=[1,2], &
              & coordSys=ESMF_COORDSYS_SPH_RAD, &
              & _RC)
       else
         grid = ESMF_GridCreateNoPeriDim( &
              & countsPerDEDim1=decomp%get_lon_distribution(), &
              & countsPerDEDim2=decomp%get_lat_distribution(), &
              & indexFlag=ESMF_INDEX_DELOCAL, &
              & gridEdgeLWidth=[0,0], &
              & gridEdgeUWidth=[1,1], &
              & coordDep1=[1,2], &
              & coordDep2=[1,2], &
              & coordSys=ESMF_COORDSYS_SPH_RAD, &
              & _RC)
      end if
      ! Allocate coords at default stagger location
      call ESMF_GridAddCoord(grid, _RC)
      call ESMF_GridAddCoord(grid, staggerloc=ESMF_STAGGERLOC_CORNER, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function create_basic_grid
Call graph
create_basic_grid calls ESMF_GridAddCoord, ESMF_GridCreate1PeriDim, ESMF_GridCreateNoPeriDim, get_decomposition, get_lat_axis, get_lat_distribution, get_lon_axis, get_lon_distribution, is_periodic, mapl_return, mapl_verify, create_basic_grid
get_decomposition calls get_decomposition
get_lat_axis calls get_lat_axis
get_lat_distribution calls get_lat_distribution
get_lon_axis calls get_lon_axis
get_lon_distribution calls get_lon_distribution
is_periodic calls is_periodic
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
typesafe_make_geom calls create_basic_grid
make_geom calls typesafe_make_geom, make_geom