delete_regridder – MAPL
delete_regridder Subroutine
19 statements
Source File
private subroutine delete_regridder(this, spec, rc)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout), target :: this
class(RegridderSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine delete_regridder(this, spec, rc)
      class(RegridderManager), target, intent(inout) :: this
      class(RegridderSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(RegridderSpecVectorIterator) :: spec_iter
      type(RegridderVectorIterator) :: regridder_iter
      associate (specs => this%specs, regridders => this%regridders)
        associate (b => specs%begin(), e => specs%end())
          spec_iter = find(b, e, spec)
          _ASSERT(spec_iter /= e, 'spec not found in RegridderManager.')
          regridder_iter = regridders%begin() + (spec_iter - b)
          regridder_iter = regridders%erase(regridder_iter)
          spec_iter = specs%erase(spec_iter)
        end associate
      end associate
      _RETURN(_SUCCESS)
   end subroutine delete_regridder
Call graph
delete_regridder calls find, mapl_assert, erase, mapl_return, vector_begin
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize