delete_routehandle – MAPL
delete_routehandle Subroutine
16 statements
Source File
public subroutine delete_routehandle(this, spec, rc)
Type Bound
RoutehandleManager
Arguments
Type Intent Optional Attributes Name
class(RoutehandleManager), intent(inout) :: this
type(RoutehandleSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine delete_routehandle(this, spec, rc)
      class(RoutehandleManager), intent(inout) :: this
      type(RoutehandleSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      type(RoutehandleSpecVectorIterator) :: iter
      type(RoutehandleVectorIterator) :: rh_iter
      associate (b => this%specs%begin(), e => this%specs%end())
        iter = find(b, e, spec)
        _ASSERT(iter /= e, "Spec not found in registry.")
        iter = this%specs%erase(iter)
        rh_iter = this%routehandles%begin() + (iter - b)
        rh_iter = this%routehandles%erase(rh_iter)
      end associate
      _RETURN(_SUCCESS)
   end subroutine delete_routehandle
Call graph
delete_routehandle calls find, mapl_assert, erase, mapl_return, vector_begin
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize