deserialize_logical_1d – MAPL
deserialize_logical_1d Subroutine
12 statements
Source File
private subroutine deserialize_logical_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
logical, intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine deserialize_logical_1d(buffer, array, rc)
      integer(kind=INT32), intent(in) :: buffer(:)
      logical, allocatable, intent(out) :: array(:)
      integer, optional, intent(out) :: rc
      integer(kind=INT32) :: n
      _ASSERT(size(buffer) >= 1, "wrong buffer")
      n = buffer(1)
      allocate(array(n-1))
      array = buffer(2:n) /= 0
      _RETURN(_SUCCESS)
   end subroutine deserialize_logical_1d
Call graph
deserialize_logical_1d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
deserialize_intrinsic calls deserialize_logical_1d
coordinatevariable_deserialize calls deserialize_intrinsic
deserialize calls deserialize_intrinsic
filemetadata_deserialize calls deserialize_intrinsic
historycollectionvector_deserialize calls deserialize_intrinsic
stringattributemap_deserialize calls deserialize_intrinsic
stringintegermap_deserialize calls deserialize_intrinsic
stringunlimitedentitymap_deserialize calls deserialize_intrinsic
stringvariablemap_deserialize calls deserialize_intrinsic
stringvector_deserialize calls deserialize_intrinsic
test_serialize_int64_array calls deserialize_intrinsic
test_serialize_int64_scalar calls deserialize_intrinsic
test_serialize_int_array calls deserialize_intrinsic
test_serialize_int_scalar calls deserialize_intrinsic
test_serialize_logical_array calls deserialize_intrinsic
test_serialize_logical_scalar calls deserialize_intrinsic
test_serialize_real_array calls deserialize_intrinsic
test_serialize_real_scalar calls deserialize_intrinsic
test_serialize_string calls deserialize_intrinsic
unlimitedentity_deserialize calls deserialize_intrinsic
variable_deserialize calls deserialize_intrinsic