destroy – MAPL
destroy Subroutine
28 statements
Source File
private subroutine destroy(this, rc)
Type Bound
BracketSpec
Arguments
Type Intent Optional Attributes Name
class(BracketSpec), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy(this, rc)
      class(BracketSpec), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      call destroy_component_fields(this, _RC)
      call ESMF_FieldBundleDestroy(this%payload, nogarbage=.true., _RC)
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine destroy_component_fields(this, rc)
         class(BracketSpec), intent(inout) :: this
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: i
         type(ESMF_Field), allocatable :: fields(:)
         integer :: fieldCount
         if (allocated(this%field_specs)) then
            do i = 1, this%bracket_size
               call this%field_specs(i)%destroy(_RC)
            end do
         end if
         _RETURN(_SUCCESS)
      end subroutine destroy_component_fields
   end subroutine destroy
Call graph
destroy calls esmf_fieldbundledestroy, destroy, mapl_return, mapl_verify, esmf_fielddestroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
connect_to calls destroy
test_connect_unique_mirror calls connect_to