destroy – MAPL
destroy Subroutine
9 statements
Source File
private subroutine destroy(this, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy(this, rc)
      class(FieldSpec), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      call ESMF_FieldDestroy(this%payload, nogarbage=.true., _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine destroy
Call graph
destroy calls esmf_fielddestroy, mapl_return, mapl_verify, destroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
connect_to calls destroy, connect_to
test_connect_unique_mirror calls connect_to