destroy_objects – MAPL
destroy_objects Subroutine
55 statements
Source File
public subroutine destroy_objects(importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: importState
type(ESMF_State), intent(inout) :: exportState
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy_objects(importState, exportState, clock, rc)
      type(ESMF_State), intent(inout) :: importState, exportState
      type(ESMF_Clock), intent(inout) :: clock
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Field) :: importField, exportField
      type(ESMF_Grid) :: grid
      call get_field(importState, importField, _RC)
      call get_field(exportState, exportField, _RC)
      call ESMF_StateDestroy(importState, _RC)
      call ESMF_StateDestroy(exportState, _RC)
      call ESMF_FieldGet(importField, grid=grid, _RC)
      call ESMF_FieldDestroy(importField, _RC)
      call ESMF_FieldDestroy(exportField, _RC)
      call ESMF_GridDestroy(grid, _RC)
      call ESMF_ClockDestroy(clock, _RC)
      _RETURN(_SUCCESS)
   end subroutine destroy_objects
Call graph
destroy_objects calls ESMF_ClockDestroy, ESMF_GridDestroy, anyexceptions, assert_that, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy, get_field, sourcelocation
get_field calls anyexceptions, assert_that, sourcelocation, esmf_stateget
test_accumulate calls destroy_objects
test_accumulate_mean_r4 calls destroy_objects
test_accumulate_r4 calls destroy_objects
test_calculate_mean calls destroy_objects
test_calculate_mean_r4 calls destroy_objects
test_clear_accumulator calls destroy_objects
test_clear_valid_mean calls destroy_objects
test_initialize calls destroy_objects
test_invalidate calls destroy_objects
test_max_accumulate_r4 calls destroy_objects
test_min_accumulate_r4 calls destroy_objects
test_update calls destroy_objects