equals_r8_scalar – MAPL
equals_r8_scalar Function
4 statements
Source File
private function equals_r8_scalar(u, v) result(lval)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: u
real(kind=ESMF_KIND_R8), intent(in) :: v
Return Value logical
Called by
Source Code
   logical function equals_r8_scalar(u, v) result(lval)
      real(kind=ESMF_KIND_R8), intent(in) :: u, v
      lval = (u == v)
   end function equals_r8_scalar
Call graph
are_equal calls equals_r8_scalar
get_value_i4 calls are_equal
get_value_i4seq calls are_equal
get_value_i8 calls are_equal
get_value_i8seq calls are_equal
get_value_logical calls are_equal
get_value_logical_seq calls are_equal
get_value_r4 calls are_equal
get_value_r4seq calls are_equal
get_value_r8 calls are_equal
get_value_r8seq calls are_equal
get_value_string calls are_equal
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string