equal – MAPL
equal Function
56 statements
Source File
private function equal(a, b)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: a
class(FileMetadata), intent(in), target :: b
Return Value logical
Calls
Source Code
   logical function equal(a, b)
      class (FileMetadata), target, intent(in) :: a
      class (FileMetadata), target, intent(in) :: b
      equal = same_dimensions(a,b)
      if (.not. equal) return
      equal = same_attributes(a,b)
      if (.not. equal) return
      equal = same_variables(a,b)
   contains
      logical function same_dimensions(a, b) result(equal)
         class (FileMetadata), target, intent(in) :: a
         class (FileMetadata), target, intent(in) :: b
         type (StringIntegerMapIterator) :: iter
         integer, pointer :: dim_a, dim_b
         character(len=:), pointer :: dim_name
         equal = a%dimensions%size() == b%dimensions%size()
         if (.not. equal) return
         iter = a%dimensions%begin()
         do while (iter /= a%dimensions%end())
            dim_name => iter%key()
            dim_b => b%dimensions%at(dim_name)
            equal = (associated(dim_b))
            if (.not. equal) return
            dim_a => iter%value()
            equal = (dim_a == dim_b)
            if (.not. equal) return
            call iter%next()
         end do
      end function same_dimensions
      logical function same_attributes(a, b) result(equal)
         class (FileMetadata), target, intent(in) :: a
         class (FileMetadata), target, intent(in) :: b
         equal = (a%global_var == b%global_var)
      end function same_attributes
      logical function same_variables(a, b) result(equal)
         class (FileMetadata), target, intent(in) :: a
         class (FileMetadata), target, intent(in) :: b
         type (StringVariableMapIterator) :: iter
         class (Variable), pointer :: var_a, var_b
         character(len=:), pointer :: var_name
         integer :: status
         equal = a%variables%size() == b%variables%size()
         if (.not. equal) return
         iter = a%variables%ftn_begin()
         do while (iter /= a%variables%ftn_end())
            call iter%next()
            var_name => iter%first()
            var_b => b%variables%at(var_name, rc=status)
            equal = (associated(var_b))
            if (.not. equal) return
            var_a => iter%second()
            equal = (var_a == var_b)
            if (.not. equal) return
         end do
      end function same_variables
   end function equal
Call graph
equal calls at, begin, key, next, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
map_at_rc calls map_find
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_find calls map_s_find
map_s_advpos calls map_s_get_child, to_node
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value