equals – MAPL
equals Function
6 statements
Source File
private function equals(a, b)
Uses
MAPL_GridManagerMod
Two regridders are equivalent if their specs are identical. This can be used to check if a given regridder is already contained in the regridder_manager without instantiating the regridder. Currently the implementation assumes that two regridders are identical if the corresponding grids are the same and the same method is in use. This will need to be changed to incorporate LocStreams.
Type Bound
RegridderSpec
Arguments
Type Intent Optional Attributes Name
class(RegridderSpec), intent(in) :: a
type(RegridderSpec), intent(in) :: b
Return Value logical
Calls
Source Code
   logical function equals(a, b)
      use MAPL_GridManagerMod, only: get_factory_id
      class (RegridderSpec), intent(in) :: a
      type (RegridderSpec), intent(in) :: b
      equals = &
           & (get_factory_id(a%grid_in) == get_factory_id(b%grid_in)) .and. &
           & (get_factory_id(a%grid_out) == get_factory_id(b%grid_out)) .and. &
           & (a%regrid_method == b%regrid_method) .and. &
           & (a%hints == b%hints)
   end function equals
Call graph
equals calls get_factory_id
get_factory_id calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize