erase_RequestHandle – MAPL
erase_RequestHandle Subroutine
10 statements
Source File
private subroutine erase_RequestHandle(this, request_id, rc)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(inout), target :: this
integer, intent(in) :: request_id
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine erase_RequestHandle(this,request_id, rc)
      class(BaseThread), target, intent(inout) :: this
      integer, intent(in) :: request_id
      integer, optional, intent(out) :: rc
      type(IntegerRequestMapIterator) :: iter
      iter = this%open_requests%find(request_id)
      iter = this%open_requests%erase(iter)
      _RETURN(_SUCCESS)
   end subroutine erase_RequestHandle
Call graph
erase_requesthandle calls erase, map_find, mapl_return
map_find calls map_s_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_erase_range calls erase
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
mapl_throw_exception calls initialize
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
wait calls erase_requesthandle