ESMFL_field_is_undefined – MAPL
ESMFL_field_is_undefined Function
38 statements
Source File
public function ESMFL_field_is_undefined(field, rc) result(field_is_undefined)
Uses
mpi
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
integer, intent(out), optional :: rc
Return Value logical
Calls
Call graph
esmfl_field_is_undefined calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldget, mapl_assert, mpi_allreduce, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize