ESMFL_StateFieldIsNeeded – MAPL
ESMFL_StateFieldIsNeeded Function
17 statements
Source File
public function ESMFL_StateFieldIsNeeded(STATE, NAME, RC) result(NEEDED)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Return Value logical
Calls
Source Code
function ESMFL_StateFieldIsNeeded(STATE, NAME, RC) result(NEEDED)
   type(ESMF_State),  intent(INOUT) :: STATE
   character(len=*),  intent(IN   ) :: NAME
   integer, optional, intent(  OUT) :: RC
   logical                          :: NEEDED
   integer                          :: STATUS
   type(ESMF_Field)                 :: FIELD
   type(ESMF_Info)                  :: infoh
   call ESMF_StateGet(STATE, trim(NAME), FIELD, RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_InfoGetFromHost(FIELD,infoh,RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_InfoSet(infoh,'Needed',NEEDED,RC=STATUS)
   if(STATUS /= ESMF_SUCCESS) NEEDED = .false.
   _RETURN(ESMF_SUCCESS)
 end function ESMFL_StateFieldIsNeeded
Call graph
esmfl_statefieldisneeded calls ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_stateget, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception