esmf_state_intent_to_string – MAPL
esmf_state_intent_to_string Function
16 statements
Source File
public function esmf_state_intent_to_string(state_intent, rc) result(state_intent_str)
Arguments
Type Intent Optional Attributes Name
type(ESMF_StateIntent_Flag), intent(in) :: state_intent
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Source Code
   function esmf_state_intent_to_string(state_intent, rc) result(state_intent_str)
      type(ESMF_StateIntent_Flag), intent(in) :: state_intent
      integer, optional, intent(out) :: rc
      character(:), allocatable :: state_intent_str ! result
      if (state_intent==ESMF_STATEINTENT_IMPORT) then
         state_intent_str = "import"
      else if (state_intent==ESMF_STATEINTENT_EXPORT) then
         state_intent_str = "export"
      else if (state_intent==ESMF_STATEINTENT_INTERNAL) then
         state_intent_str = "internal"
      else
         _FAIL("invalid state intent")
      end if
      _RETURN(_SUCCESS)
   end function esmf_state_intent_to_string
Call graph
esmf_state_intent_to_string calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception