ESMFL_HALO_R4_2D – MAPL
ESMFL_HALO_R4_2D Subroutine
150 statements
Source File
private subroutine ESMFL_HALO_R4_2D(GRID, INPUT, RC)
Uses
MAPL_GridManagerMod
MAPL_AbstractGridFactoryMod
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: GRID
real, intent(inout) :: INPUT(:,:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  SUBROUTINE ESMFL_HALO_R4_2D(GRID, INPUT, RC)
!-------------------------------------------------------------------------
     use MAPL_GridManagerMod, only: get_factory
     use MAPL_AbstractGridFactoryMod
     TYPE(ESMF_Grid),         INTENT(INout) :: GRID
     REAL,                    INTENT(INOUT) :: INPUT(:,:)
     integer, optional,       intent(OUT)   :: RC
! Local variables
     integer                    :: STATUS
     INTEGER :: LAST, LEN1, LEN2
     integer :: nn_north, nn_south, nn_east, nn_west
     integer :: j_north, j_south, i_east, i_west
     integer, save                            :: NX=-1
     integer, save                            :: NY=-1
     integer                                  :: NX0, NY0
     type (ESMF_DELayout)                     :: layout
     integer                                  :: myid
     integer                                  :: ndes
     integer                                  :: dimCount
     integer, allocatable                     :: minindex(:,:)
     integer, allocatable                     :: maxindex(:,:)
     integer, pointer                         :: ims(:) => null()
     integer, pointer                         :: jms(:) => null()
     type (ESMF_VM)                           :: VM
     type (ESMF_DistGrid)                     :: distGrid
     integer                                  :: IM, JM, DIMS(3)
#define MAX_HALOTYPES 8
     type HaloType
        character(len=ESMF_MAXSTR)            :: gridname = ""
        type(ESMF_DELayout)                   :: layout
        integer                               :: NX = -1
        integer                               :: NY = -1
        integer                               :: domainIdx = -1
        integer                               :: myId
        logical                               :: isCube = .false.
        logical                               :: inUse = .false.
     end type HaloType
     type(HaloType), save                     :: myHaloTypes(MAX_HALOTYPES)
     type(HaloType)                           :: thisHaloType
     logical                                  :: found
     integer                                  :: I
     integer                                  :: isd, ied
     integer                                  :: jsd, jed
     character(len=ESMF_MAXSTR)               :: gridname
     class (AbstractGridFactory), pointer :: factory
     call ESMF_GridGet    (GRID,   name=gridname, RC=STATUS)
     _VERIFY(STATUS)
     found = .false.
     DO I = 1, MAX_HALOTYPES
        if (gridname == myHaloTypes(I)%gridname) then
           found = .true.
           thisHaloType = myHaloTypes(I)
           exit
        end if
     END DO
     if (.not. found) then
! try to find unused slot to save this Halo for future use
        DO I = 1, MAX_HALOTYPES
           if(.not.myHaloTypes(I)%inUse) then
              found = .true.
              thisHaloType%domainIdx = I
              exit
           end if
        END DO
        if (.not.found) then
           print *, "Error: need bigger MAX_HALOTYPES value"
           _FAIL( 'no unused slot for halo types')
        end if
        call ESMF_GridGet(GRID,   distGrid=distGrid, dimCount=dimCount, RC=STATUS)
        _VERIFY(STATUS)
        call ESMF_DistGridGet(distGRID, delayout=layout, rc=STATUS)
        _VERIFY(STATUS)
        call ESMF_DELayoutGet (layout, VM=vm, RC=STATUS)
        _VERIFY(STATUS)
        call ESMF_VmGet(VM, localPet=MYID, petCount=ndes, rc=status)
        _VERIFY(STATUS)
        thisHaloType%myId = MyId
!    Layout sizes
!    ------------
        allocate(minindex(dimCount,ndes), maxindex(dimCount,ndes), stat=status)
        _VERIFY(STATUS)
! Processors in each direction
!-----------------------------
        call MAPL_DistGridGet(distgrid, &
             minIndex=minindex, &
             maxIndex=maxindex, rc=status)
        _VERIFY(STATUS)
        call MAPL_GetImsJms(Imins=minindex(1,:),Imaxs=maxindex(1,:),&
             Jmins=minindex(2,:),Jmaxs=maxindex(2,:),Ims=ims,Jms=jms,rc=status)
        _VERIFY(STATUS)
        NX = size(ims)
        NY = size(jms)
        deallocate(jms, ims)
        deallocate(maxindex, minindex)
        thisHaloType%gridname = gridname
        thisHaloType%inUse    = .true.
        thisHaloType%NX = NX
        thisHaloType%NY = NY
        thisHaloType%layout = layout
        call MAPL_GridGet(grid, globalCellCountPerDim=DIMS, RC=status)
        _VERIFY(STATUS)
        IM = DIMS(1)
        JM = DIMS(2)
        if (JM == 6*IM) then
           thisHaloType%isCube = .true.
        else
           thisHaloType%isCube = .false.
        end if
        myHaloTypes(thisHaloType%domainIdx) = thisHaloType
     end if
     if (thisHaloType%isCube) then
        factory => get_factory(grid, rc=status)
        _VERIFY(status)
        isd = lbound(input,1)
        ied = ubound(input,1)
        jsd = lbound(input,2)
        jed = ubound(input,2)
        ! fill the corners with MAPL_UNDEF, they will be overwritten
        ! by the CubeHalo, unless these are the actual cube corners
        input(isd,jsd) = MAPL_UNDEF
        input(ied,jsd) = MAPL_UNDEF
        input(isd,jed) = MAPL_UNDEF
        input(ied,jed) = MAPL_UNDEF
        call factory%halo(input, rc=status)
        _VERIFY(status)
        _RETURN(ESMF_SUCCESS)
     end if
! This is section of the code is valid ONLY for rectilinear grids!
     NX = thisHaloType%NX
     NY = thisHaloType%NY
     myId = thisHaloType%myId
     layout = thisHaloType%layout
!    My processor coordinates
!    -------------------------
!ALT: we will use 0-based NX0, NY0 here, unlike in MAPL_Generic !
     NX0 = mod(MYID,NX)
     NY0 = MYID/NX
     j_north = mod(NY0   +1,NY)
     j_south = mod(NY0+NY-1,NY)
     i_east  = MOD(NX0   +1,NX)
     i_west  = MOD(NX0+NX-1,NX)
     ! Nearest neighbors processor' ids
     nn_north = NX0 + NX*j_north
     nn_south = NX0 + NX*j_south
     nn_west  = i_west + NX*NY0
     nn_east  = i_east + NX*NY0
!  Fill NORTHERN ghost region
     LAST = SIZE(INPUT,2)-1
     LEN1 = SIZE(INPUT,1)
     call MAPL_CommsSendRecv(LAYOUT, &
          INPUT(:,2        ),  LEN1,  NN_SOUTH,  &
          INPUT(:,last+1   ),  LEN1,  NN_NORTH,  &
          RC=STATUS)
     _VERIFY(STATUS)
     if(NY0==NY-1) then
        INPUT(:,last+1   ) = INPUT(:,last )
     end if
!  Fill SOUTHERN ghost region
     CALL MAPL_CommsSendRecv(layout,             &
          INPUT(:,last     ),  LEN1,  NN_NORTH,  &
          INPUT(:,1        ),  LEN1,  NN_SOUTH,  &
          RC=STATUS)
     _VERIFY(STATUS)
     if(NY0==0) then
        INPUT(:,1   ) = INPUT(:,2 )
     endif
     LAST = SIZE(INPUT,1)-1
     LEN2 = SIZE(INPUT,2)
!  Fill EASTERN ghost region
     CALL MAPL_CommsSendRecv(layout,           &
          INPUT(2     , : ),  LEN2,  NN_WEST,  &
          INPUT(last+1, : ),  LEN2,  NN_EAST,  &
          RC=STATUS)
     _VERIFY(STATUS)
!  Fill WESTERN ghost region
     CALL MAPL_CommsSendRecv(layout,           &
          INPUT(last  , : ),  LEN2,  NN_EAST,  &
          INPUT(1     , : ),  LEN2,  NN_WEST,  &
          RC=STATUS)
     _VERIFY(STATUS)
     _RETURN(ESMF_SUCCESS)
   end SUBROUTINE ESMFL_HALO_R4_2D
Call graph
esmfl_halo_r4_2d calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, halo, mapl_assert, mapl_commssendrecv, get_factory, mapl_distgridget, mapl_getimsjms, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commssendrecv calls mapl_commssendrecv_i4_0, mapl_commssendrecv_r4_0, mapl_commssendrecv_r4_1, mapl_commssendrecv_r4_2, mapl_commssendrecv_r8_1, mapl_commssendrecv_r8_2
get_factory calls mapl_return, mapl_verify, get_factory
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridget calls ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_getimsjms, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_halo calls esmfl_halo_r4_2d
mapl_locstreamtransformg2t calls esmfl_halo
mapl_locstreamtransform calls mapl_locstreamtransformg2t, mapl_locstreamtransformfield
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform