ESMFL_StateSetFieldNeeded – MAPL
ESMFL_StateSetFieldNeeded Subroutine
16 statements
Source File
public subroutine ESMFL_StateSetFieldNeeded(STATE, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Calls
Source Code
 subroutine ESMFL_StateSetFieldNeeded(STATE, NAME, RC)
   type(ESMF_State),  intent(INOUT) :: STATE
   character(len=*),  intent(IN   ) :: NAME
   integer, optional, intent(  OUT) :: RC
   integer                          :: STATUS
   type(ESMF_Field)                 :: FIELD
   type(ESMF_Info)                  :: infoh
   call ESMF_StateGet(STATE, trim(NAME), FIELD, RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_InfoGetFromHost(FIELD,infoh,RC=STATUS)
   _VERIFY(STATUS)
   call ESMF_InfoSet(infoh,key="Needed",value=.false.,RC=STATUS)
   _VERIFY(STATUS)
   _RETURN(ESMF_SUCCESS)
 end subroutine ESMFL_StateSetFieldNeeded
Call graph
esmfl_statesetfieldneeded calls ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_stateget, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception