ESMFL_GridCoordGet – MAPL
ESMFL_GridCoordGet Subroutine
91 statements
Source File
public subroutine ESMFL_GridCoordGet(GRID, coord, name, location, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: GRID
real, dimension(:,:), pointer :: coord
character(len=*), intent(in) :: name
type(ESMF_StaggerLoc) :: location
integer :: units
integer, optional :: rc
Calls
Called by
Source Code
subroutine ESMFL_GridCoordGet(GRID, coord, name, Location, Units, rc)
  !ARGUMENTS:
   type(ESMF_Grid),   intent(INout ) :: GRID
   real, dimension(:,:), pointer  :: coord
   character (len=*) , intent(IN) :: name
   type(ESMF_StaggerLoc)          :: location
   integer                        :: units
   integer, optional              :: rc
 !EOP
! local variables
  integer                   :: rank
  type(ESMF_CoordSys_Flag)  :: crdSys
  type(ESMF_TypeKind_Flag)  :: tk
  integer                   :: counts(ESMF_MAXDIM)
  integer                   :: crdOrder
  real(ESMF_KIND_R4), pointer :: r4d2(:,:)
  real(ESMF_KIND_R8), pointer :: r8d2(:,:)
  real(ESMF_KIND_R8)        :: conv2rad
  integer                   :: STATUS
  integer                   :: i
  integer                   :: j
!ALT  integer                   :: i1, in, j1, jn
  integer                   :: coordDimCount(ESMF_MAXDIM)
  character(len=ESMF_MAXSTR):: gridname
  _UNUSED_DUMMY(Units)
  call ESMF_GridGet(grid, coordSys=crdSys, coordTypeKind=tk, &
          dimCount=rank, coordDimCount=coordDimCount, rc=status)
  _VERIFY(STATUS)
  if (name == "Longitude") then
    crdOrder = 1
  else if (name == "Latitude") then
    crdOrder = 2
  else
   STATUS=ESMF_FAILURE
   _VERIFY(STATUS)
  endif
  call ESMF_GridGet(grid, name=gridname, rc=status)
  _VERIFY(STATUS)
  if (gridname(1:10) == 'tile_grid_') then
     call MAPL_GridGet(GRID, localCellCountPerDim=counts, rc=status)
     _VERIFY(STATUS)
     allocate(coord(counts(1), counts(2)), STAT=status)
     _VERIFY(STATUS)
     coord = 0.0 ! initialize just in case
!ALT     call MAPL_GRID_INTERIOR(GRID,I1,IN,J1,JN)
     do I=1, counts(1)
        do J=1, counts(2)
           if (crdOrder == 1) then
              coord(i,j) = i !ALT + I1 - 1
           else
              coord(i,j) = j !ALT + J1 - 1
           end if
        end do
     end do
     coord = coord * (MAPL_PI_R8 / 180.d+0)
     _RETURN(ESMF_SUCCESS)
  end if
  if (crdSys == ESMF_COORDSYS_SPH_DEG) then
     conv2rad = MAPL_PI_R8 / 180._ESMF_KIND_R8
  else if (crdSys == ESMF_COORDSYS_SPH_RAD) then
     conv2rad = 1._ESMF_KIND_R8
  else
     _FAIL('Unsupported coordinate system:  ESMF_COORDSYS_CART')
  end if
  if (tk == ESMF_TYPEKIND_R4) then
     if (coordDimCount(crdOrder)==2) then
        call ESMF_GridGetCoord(grid, localDE=0, coordDim=crdOrder, &
             staggerloc=location, &
             computationalCount=COUNTS,  &
             farrayPtr=R4D2, rc=status)
        _VERIFY(STATUS)
        allocate(coord(counts(1), counts(2)), STAT=status)
        _VERIFY(STATUS)
        coord = conv2rad * R4D2
     else
        _RETURN(ESMF_FAILURE)
     endif
  else if (tk == ESMF_TYPEKIND_R8) then
     if (coordDimCount(crdOrder)==2) then
        call ESMF_GridGetCoord(grid, localDE=0, coordDim=crdOrder, &
             staggerloc=location, &
             computationalCount=COUNTS,  &
             farrayPtr=R8D2, rc=status)
        _VERIFY(STATUS)
        allocate(coord(counts(1), counts(2)), STAT=status)
        _VERIFY(STATUS)
        coord = conv2rad * R8D2
     else
        _RETURN(ESMF_FAILURE)
     endif
  else
     _RETURN(ESMF_FAILURE)
  endif
  _RETURN(ESMF_SUCCESS)
 end subroutine ESMFL_GridCoordGet
Call graph
esmfl_gridcoordget calls ESMF_GridGet, ESMF_GridGetCoord, mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
bundleregrid calls esmfl_gridcoordget
mapl_genericinitialize calls esmfl_gridcoordget
mapl_gradsctlwrite calls esmfl_gridcoordget
esmfl_regrid calls bundleregrid, stateregrid
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
run calls mapl_gradsctlwrite
stateregrid calls bundleregrid