extension_cost – MAPL
extension_cost Function
17 statements
Source File
private function extension_cost(this, src_spec, rc) result(cost)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: src_spec
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function extension_cost(this, src_spec, rc) result(cost)
      class(FieldSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: src_spec
      integer, optional, intent(out) :: rc
      integer :: status
      cost = 0
      select type (src_spec)
      type is (FieldSpec)
         cost = cost + get_cost(this%geom, src_spec%geom)
         cost = cost + get_cost(this%typekind, src_spec%typekind)
         cost = cost + get_cost(this%units, src_spec%units)
      class default
         _FAIL('Cannot extend to this StateItemSpec subclass.')
      end select
      _RETURN(_SUCCESS)
   end function extension_cost
Call graph
extension_cost calls get_cost, mapl_assert, mapl_return, extension_cost
get_cost calls get_cost_geom, get_cost_string, get_cost_typekind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_cost_geom calls match
get_cost_string calls match
get_cost_typekind calls match
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
match calls match_geom, match_string, match_typekind