extension_cost – MAPL
extension_cost Function
18 statements
Source File
private function extension_cost(this, src_spec, rc) result(cost)
Type Bound
MockItemSpec
Arguments
Type Intent Optional Attributes Name
class(MockItemSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: src_spec
integer, intent(out), optional :: rc
Return Value integer
Calls
Source Code
   integer function extension_cost(this, src_spec, rc) result(cost)
      class(MockItemSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: src_spec
      integer, optional, intent(out) :: rc
      integer :: status
      cost = 0
      select type(src_spec)
      type is (MockItemSpec)
         if (this%name /= src_spec%name) cost = cost + 1
         if (allocated(src_spec%subtype) .and. allocated(this%subtype)) then
            if (this%subtype /= src_spec%subtype) cost = cost + 1
         end if
      class default
         _FAIL('incompatible spec')
      end select
      _RETURN(_SUCCESS)
   end function extension_cost
Call graph
extension_cost calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize