extend_ – MAPL
extend_ Function
23 statements
Source File
private function extend_(this, v_pt, spec, extension, source_coupler, rc) result(extension_pt)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
type(VirtualConnectionPt), intent(in) :: v_pt
class(StateItemSpec), intent(in) :: spec
class(StateItemSpec), intent(in) :: extension
type(GriddedComponentDriver), intent(in), optional, target :: source_coupler
integer, intent(out), optional :: rc
Return Value type(ActualConnectionPt)
Calls
Called by
Source Code
   function extend_(this, v_pt, spec, extension, source_coupler, rc) result(extension_pt)
      type(ActualConnectionPt) :: extension_pt
      class(HierarchicalRegistry), target, intent(inout) :: this
      type(VirtualConnectionPt), intent(in) :: v_pt
      class(StateItemSpec), intent(in) :: spec
      class(StateItemSpec), intent(in) :: extension
      type(GriddedComponentDriver), optional, target, intent(in) :: source_coupler ! for chains of extensions
      integer, optional, intent(out) :: rc
      integer :: status
      type(ActualPtVector), pointer :: actual_pts
      type(ActualConnectionPt), pointer :: actual_pt
      class(ExtensionAction), allocatable :: action
      actual_pts => this%get_actual_pts(v_pt)
      _ASSERT(associated(actual_pts), 'No actual pts found for v_pt')
      actual_pt => actual_pts%back()
      extension_pt = actual_pt%extend()
      call this%add_item_spec(v_pt, extension, extension_pt, _RC)
      call this%add_state_extension(extension_pt, spec, extension, source_coupler=source_coupler, _RC)
      _RETURN(_SUCCESS)
   end function extend_
Call graph
extend_ calls mapl_assert, add_item_spec, add_state_extension, extend_, get_actual_pts, mapl_return, mapl_verify, vector_back, is_extension
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_state_extension calls mapl_return, mapl_verify, insert, make_action, make_coupler, map_of
get_actual_pts calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
connect_sibling calls extend_
connect calls connect_sibling