FargparseCLI – MAPL
FargparseCLI Function
29 statements
Source File
public function FargparseCLI(unusable, extra_options, cast_extras, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
procedure(I_extraoptions), optional :: extra_options
procedure(I_castextras), optional :: cast_extras
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
Calls
Source Code
   function FargparseCLI(unusable, extra_options, cast_extras, rc) result (cap_options)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type (MAPL_CapOptions_) :: cap_options
      procedure(I_extraoptions), optional :: extra_options
      procedure(I_castextras), optional :: cast_extras
      integer, optional, intent(out) :: rc
      integer :: status
      type(FargparseCLI_Type) :: fargparse_cli
      call fargparse_cli%parser%initialize('executable')
      call fargparse_cli%add_command_line_options(fargparse_cli%parser, _RC)
      if (present(extra_options)) then
         call extra_options(fargparse_cli%parser, _RC)
      end if
      fargparse_cli%options = fargparse_cli%parser%parse_args()
      call fargparse_cli%fill_cap_options(cap_options, _RC)
      if (present(cast_extras)) then
         call cast_extras(fargparse_cli, _RC)
      end if
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function FargparseCLI
Call graph
fargparsecli calls initialize, parse_args, add_command_line_options, fill_cap_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, add_argument, push_back
fill_cap_options calls mapl_return, mapl_verify, at, cast, mapl_assert, of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception