fieldLog – MAPL
fieldLog Subroutine
62 statements
Source File
public subroutine fieldLog(field_out, field_in, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field_out
type(ESMF_Field), intent(inout) :: field_in
integer, intent(out), optional :: rc
Calls
Called by
Call graph
fieldlog calls esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef, mapl_return, mapl_verify
fieldshaveundef calls mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoIsPresent
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_stateeval calls fieldlog
evaluate_derived_field calls mapl_stateeval, evaluate_mask