FieldNegate – MAPL
FieldNegate Subroutine
46 statements
Source File
public subroutine FieldNegate(field, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
subroutine FieldNegate(field,rc)
   type(ESMF_Field), intent(inout) :: field
   integer, intent(out), optional :: rc
   type(ESMF_TYPEKIND_FLAG) :: type_kind
   real(kind=ESMF_KIND_R4), pointer :: f_ptr_r4(:)
   real(kind=ESMF_KIND_R8), pointer :: f_ptr_r8(:)
   logical :: has_undef
   real(kind = ESMF_Kind_R4), allocatable :: undef_r4(:)
   real(kind = ESMF_Kind_R8), allocatable :: undef_r8(:)
   integer :: status
   type(ESMF_Field) :: fields(1)
   fields(1) = field
   has_undef = FieldsHaveUndef(fields,_RC)
   call ESMF_FieldGet(field,typekind=type_kind,_RC)
   if (type_kind == ESMF_TYPEKIND_R4) then
      call assign_fptr(field,f_ptr_r4,_RC)
      if (has_undef) then
         call GetFieldsUndef(fields,undef_r4,_RC)
         where(f_ptr_r4 /= undef_r4(1))
            f_ptr_r4 = -f_ptr_r4
         end where
      else
         f_ptr_r4 = -f_ptr_r4
      end if
   else if (type_kind == ESMF_TYPEKIND_R4) then
      call assign_fptr(field,f_ptr_r8,_RC)
      if (has_undef) then
         call GetFieldsUndef(fields,undef_r8,_RC)
         where(f_ptr_r8 /= undef_r8(1))
            f_ptr_r8 = -f_ptr_r8
         end where
      else
         f_ptr_r8 = -f_ptr_r8
      end if
   else
      _FAIL('unsupported typekind')
   end if
   _RETURN(ESMF_SUCCESS)
end subroutine FieldNegate
Call graph
fieldnegate calls esmf_fieldget, assign_fptr, getfieldsundef, mapl_assert, fieldshaveundef, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
getfieldsundef calls getfieldsundef_r4, getfieldsundef_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fieldshaveundef calls mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoIsPresent
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
getfieldsundef_r4 calls mapl_assert, mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoGet
getfieldsundef_r8 calls mapl_assert, mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoGet
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
evalf calls fieldnegate, field_unary
field_unary calls fieldnegate
test_fieldnegr4 calls fieldnegate
mapl_stateeval calls evalf
calcderivedfield calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
run calls mapl_runexpression
run_ calls evaluate_derived_field, calcderivedfield, fillstate