fill_coordinates – MAPL
fill_coordinates Module Subroutine
53 statements
Source File
module subroutine fill_coordinates(spec, grid, unusable, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(LatLonGeomSpec), intent(in) :: spec
type(ESMF_Grid), intent(inout) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine fill_coordinates(spec, grid, unusable, rc)
      type(LatLonGeomSpec), intent(in) :: spec
      type(ESMF_Grid), intent(inout) :: grid
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=ESMF_KIND_R8), pointer :: centers(:,:)
      real(kind=ESMF_KIND_R8), pointer :: corners(:,:)
      integer :: i, j
      type(LonAxis) :: lon_axis
      type(LatAxis) :: lat_axis
      type(LonAxis) :: local_lon_axis
      type(LatAxis) :: local_lat_axis
      type(LatLonDecomposition) :: decomp
      integer :: nx, ny, ix, iy
      lon_axis = spec%get_lon_axis()
      lat_axis = spec%get_lat_axis()
      decomp = spec%get_decomposition()
      nx = size(decomp%get_lon_distribution())
      ny = size(decomp%get_lat_distribution())
      call get_ranks(nx, ny, ix, iy, _RC)
     ! First we handle longitudes:
      call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=centers, _RC)
      call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CORNER, &
           farrayPtr=corners, _RC)
      lon_axis = spec%get_lon_axis()
      local_lon_axis = decomp%get_lon_subset(lon_axis, rank=ix)
      do j = 1, size(centers,2)
         centers(:,j) = local_lon_axis%get_centers()
      end do
      do j = 1, size(corners,2)
         corners(:,j) = local_lon_axis%get_corners()
      end do
      centers = centers * MAPL_DEGREES_TO_RADIANS_R8
      corners = corners * MAPL_DEGREES_TO_RADIANS_R8
      ! Now latitudes
      call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=centers, _RC)
      call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CORNER, &
           farrayPtr=corners, _RC)
      local_lat_axis = decomp%get_lat_subset(lat_axis, rank=iy)
      do i = 1, size(centers,1)
         centers(i,:) = local_lat_axis%get_centers()
      end do
      do i = 1, size(corners,1)
         corners(i,:) = local_lat_axis%get_corners()
      end do
      centers = centers * MAPL_DEGREES_TO_RADIANS_R8
      corners = corners * MAPL_DEGREES_TO_RADIANS_R8
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine fill_coordinates
Call graph
fill_coordinates calls ESMF_GridGetCoord, get_centers, get_corners, get_decomposition, get_lat_axis, get_lat_distribution, get_lat_subset, get_lon_axis, get_lon_distribution, get_lon_subset, get_ranks, mapl_return, mapl_verify, fill_coordinates
get_centers calls get_centers
get_corners calls get_corners
get_decomposition calls get_decomposition
get_lat_axis calls get_lat_axis
get_lat_distribution calls get_lat_distribution
get_lat_subset calls get_lat_subset
get_lon_axis calls get_lon_axis
get_lon_distribution calls get_lon_distribution
get_lon_subset calls get_lon_subset
get_ranks calls get_ranks
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
typesafe_make_geom calls fill_coordinates
make_geom calls typesafe_make_geom, make_geom