FillBundle – MAPL
FillBundle Subroutine
30 statements
Source File
private subroutine FillBundle(inState, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: inState
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine FillBundle(inState,rc)
      type(ESMF_State), intent(inout) :: inState
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: itemcount,i
      character(len=ESMF_MAXSTR), allocatable :: outNameList(:)
      type(ESMF_StateItem_Flag), allocatable :: item_type(:)
      type(ESMF_Field) :: field
      type(ESMF_FieldBundle) :: bundle
      call ESMF_StateGet(InState,itemcount=itemCount,_RC)
      allocate(outNameList(itemCount),stat=status)
      _VERIFY(status)
      allocate(item_type(itemCount),stat=status)
      _VERIFY(status)
      call ESMF_StateGet(InState,itemTypeList=item_type,itemNameList=outNameList,_RC)
      call ESMF_StateGet(InState,"test_bundle",bundle,_RC)
      do i=1,itemCount
         if (item_type(i) == ESMF_STATEITEM_FIELD) then
            call ESMF_StateGet(InState,trim(outNameList(i)),field,_RC)
            call MAPL_FieldBundleAdd(bundle,field,_RC)
         end if
      enddo
      _RETURN(ESMF_SUCCESS)
   end subroutine FillBundle
Call graph
fillbundle calls esmf_stateget, mapl_fieldbundleadd, mapl_return, mapl_verify
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_fieldbundleadd, esmf_fieldget
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_ calls fillbundle