fill_time_in_bundle – MAPL
fill_time_in_bundle Subroutine
22 statements
Source File
private subroutine fill_time_in_bundle(this, xname, bundle, ogrid, rc)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
character(len=*), intent(in) :: xname
type(ESMF_FieldBundle), intent(inout) :: bundle
type(ESMF_Grid), intent(in) :: ogrid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine fill_time_in_bundle (this, xname, bundle, ogrid, rc)
    implicit none
    class(samplerHQ) :: this
    character(len=*), intent(in) :: xname
    type(ESMF_FieldBundle), intent(inout) :: bundle
    integer, optional, intent(out) :: rc
    integer :: status
    type(ESMF_Grid), intent(in) :: ogrid
    class(AbstractGridFactory), pointer :: factory
    type(ESMF_Field) :: field
    real(kind=ESMF_KIND_R4), pointer :: ptr2d(:,:)
    ! __ get field xname='time'
    call ESMF_FieldBundleGet (bundle, xname, field=field, _RC)
    call ESMF_FieldGet (field, farrayptr=ptr2d, _RC)
    ! __ obs_time from swath factory
    factory => grid_manager%get_factory(ogrid,_RC)
    call factory%get_obs_time (ogrid, ptr2d, _RC)
    _RETURN(ESMF_SUCCESS)
  end subroutine fill_time_in_bundle
Call graph
fill_time_in_bundle calls esmf_fieldbundleget, esmf_fieldget, get_factory, get_obs_time, mapl_return, mapl_verify
get_factory calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, m_at
get_obs_time calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find
run calls fill_time_in_bundle