fill_units – MAPL
fill_units Subroutine
21 statements
Source File
private subroutine fill_units(this, units, rc)
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: this
character(len=:), intent(out), allocatable :: units
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine fill_units(this, units, rc)
      class(VariableSpec), intent(in) :: this
      character(:), allocatable, intent(out) :: units
      integer, optional, intent(out) :: rc
      character(len=ESMF_MAXSTR) :: canonical_units
      integer :: status
      ! Only fill if not already specified
      if (allocated(this%units)) then
         units = this%units
         _RETURN(_SUCCESS)
      end if
      ! Only fill if standard name is provided
      _RETURN_UNLESS(allocated(this%standard_name))
      call NUOPC_FieldDictionaryGetEntry(this%standard_name, canonical_units, status)
      _ASSERT(status == ESMF_SUCCESS,'Units not found for standard name: <'//this%standard_name//'>')
      units = trim(canonical_units)
      _RETURN(_SUCCESS)
   end subroutine fill_units
Call graph
fill_units calls NUOPC_FieldDictionaryGetEntry, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_bracketspec calls fill_units
make_fieldspec calls fill_units
make_itemspec calls make_bracketspec, make_fieldspec
initialize_advertise calls make_itemspec
initialize calls initialize_advertise