filter – MAPL
filter Function
17 statements
Source File
private function filter(this, pattern) result(matches)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
type(VirtualConnectionPt), intent(in) :: pattern
Return Value type(VirtualConnectionPtVector)
Calls
Called by
Source Code
   function filter(this, pattern) result(matches)
      type(VirtualConnectionPtVector) :: matches
      class(HierarchicalRegistry), target, intent(in) :: this
      type(VirtualConnectionPt), intent(in) :: pattern
      type(VirtualConnectionPt), pointer :: v_pt
      type(ActualPtVec_MapIterator) :: iter
      associate (e => this%virtual_pts%ftn_end())
        iter = this%virtual_pts%ftn_begin()
        do while (iter /= e)
           call iter%next()
           v_pt => iter%first()
           if (pattern%matches(v_pt)) then
              call matches%push_back(v_pt)
           end if
        end do
      end associate
   end function filter
Call graph
filter calls map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, matches, vector_push_back
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
matches calls get_full_name, get_state_intent, regcomp, regexec
vector_push_back calls resize, vector_grow_to
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
vector_grow_to calls vector_capacity, vector_set_capacity
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_advpos calls map_s_get_child, to_node
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value
vector_resize_size_kind calls reserve
connect calls filter