finalize – MAPL
finalize Subroutine
35 statements
Source File
private recursive subroutine finalize(this, importState, exportState, clock, unusable, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine finalize(this, importState, exportState, clock, unusable, rc)
      class(OuterMetaComponent), intent(inout) :: this
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      ! optional arguments
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(GriddedComponentDriver), pointer :: child
      type(GriddedComponentDriverMapIterator) :: iter
      integer :: status, userRC
      character(*), parameter :: PHASE_NAME = 'GENERIC::FINALIZE_USER'
      type(StringVector), pointer :: finalize_phases
      logical :: found
      finalize_phases => this%user_phases_map%at(ESMF_METHOD_FINALIZE, _RC)
      ! User gridcomp may not have any given phase; not an error condition if not found.
      associate (phase => get_phase_index(finalize_phases, phase_name=phase_name, found=found))
        _RETURN_UNLESS(found)
        ! TODO:  Should user finalize be after children finalize?
        ! TODO:  Should there be a phase option here?  Probably not
        ! right as is when things get more complicated.
        call this%run_custom(ESMF_METHOD_FINALIZE, PHASE_NAME, _RC)
        associate(b => this%children%begin(), e => this%children%end())
          iter = b
          do while (iter /= e)
             child => iter%second()
             call child%finalize(phase_idx=GENERIC_FINALIZE_USER, _RC)
             call iter%next()
          end do
        end associate
      end associate
      _RETURN(ESMF_SUCCESS)
   end subroutine finalize
Call graph
finalize calls finalize, get_phase_index, at, mapl_return, mapl_verify, omap_begin, omap_iter_next, run_custom
get_phase_index calls get_phase_index_
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
omap_begin calls omap_k_begin
omap_iter_next calls omap_k_iter_next
run_custom calls finalize, get_phase_index, mapl_return, mapl_verify, initialize, mapl_assert, run, get_phases
test_finalize_children calls finalize