finalize – MAPL
finalize Subroutine
15 statements
Source File
private recursive subroutine finalize(gridcomp, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine finalize(gridcomp, importState, exportState, clock, rc)
      type(ESMF_GridComp) :: gridcomp
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      outer_meta => get_outer_meta(gridcomp, _RC)
      call outer_meta%finalize(importState, exportState, clock, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine finalize
Call graph
finalize calls get_outer_meta, finalize, mapl_return, mapl_verify, get_phase_index, at, omap_begin, omap_iter_next, run_custom
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_phase_index calls get_phase_index_
get_error_message calls at, insert
get_outer_meta_from_outer_gc calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_throw_exception calls initialize
omap_begin calls omap_k_begin
omap_iter_next calls omap_k_iter_next
run_custom calls mapl_return, mapl_verify, finalize, get_phase_index, initialize, mapl_assert, run, get_phases