finalize – MAPL
finalize Subroutine
18 statements
Source File
public subroutine finalize(unusable, rc)
Uses
mapl_ErrorHandlingMod
mapl_KeywordEnforcerMod
Type Bound
ExtData_DriverGridComp
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine finalize(unusable, rc)
      use mapl_KeywordEnforcerMod
      use mapl_ErrorHandlingMod
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class(DistributedProfiler), pointer :: t_p, m_p
      integer :: status
      t_p => get_global_time_profiler()
      call t_p%stop(_RC)
      m_p => get_global_memory_profiler()
      call m_p%stop(_RC)
      call report_global_profiler()
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine finalize
Call graph
finalize calls get_global_memory_profiler, get_global_time_profiler, mapl_return, mapl_verify, report_global_profiler
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
report_global_profiler calls get_global_memory_profiler, get_global_time_profiler, mapl_return, mapl_verify, mpi_barrier, mpi_comm_rank, mpi_comm_size, add_column, generate_report, get_num_meters, info
run calls finalize
extdata_driver calls run