find_closest_spec – MAPL
find_closest_spec Subroutine
28 statements
Source File
private subroutine find_closest_spec(goal_spec, candidate_specs, candidate_pts, closest_Spec, closest_pt, lowest_cost, rc)
Arguments
Type Intent Optional Attributes Name
class(StateItemSpec), intent(in) :: goal_spec
type(StateItemSpecPtr), intent(in), target :: candidate_specs(:)
type(ActualPtVector), intent(in), target :: candidate_pts
class(StateItemSpec), pointer :: closest_Spec
type(ActualConnectionPt), pointer :: closest_pt
integer, intent(out) :: lowest_cost
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine find_closest_spec(goal_spec, candidate_specs, candidate_pts, closest_spec, closest_pt, lowest_cost, rc)
      class(StateItemSpec), intent(in) :: goal_spec
      type(StateItemSpecPtr), target, intent(in) :: candidate_specs(:)
      type(ActualPtVector), target, intent(in) :: candidate_pts
      class(StateItemSpec), pointer :: closest_Spec
      type(ActualConnectionPt), pointer :: closest_pt
      integer, intent(out) :: lowest_cost
      integer, optional, intent(out) :: rc
      integer :: status
      class(StateItemSpec), pointer :: spec
      integer :: cost
      integer :: j
      _ASSERT(size(candidate_specs) > 0, 'no candidates found')
      closest_spec => candidate_specs(1)%ptr
      closest_pt => candidate_pts%of(1)
      lowest_cost = goal_spec%extension_cost(closest_spec, _RC)
      do j = 2, size(candidate_specs)
         if (lowest_cost == 0) exit
         spec => candidate_specs(j)%ptr
         cost = goal_spec%extension_cost(spec)
         if (cost < lowest_cost) then
            lowest_cost = cost
            closest_spec => spec
            closest_pt => candidate_pts%of(j)
         end if
      end do
   end subroutine find_closest_spec
Call graph
find_closest_spec calls extension_cost, mapl_assert, of, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
connect_sibling calls find_closest_spec
connect calls connect_sibling