find_ – MAPL
find_ Function
60 statements
Source File
private function find_(this, file_name, rc) result(formatter)
Type Bound
CFIOCollection
Arguments
Type Intent Optional Attributes Name
class(CFIOCollection), intent(inout), target :: this
character(len=*), intent(in) :: file_name
integer, intent(out), optional :: rc
Return Value type(ESMF_CFIO), pointer
Calls
Called by
Source Code
  function find_(this, file_name, rc) result(formatter)
    type (ESMF_CFIO), pointer :: formatter
    class (CFIOCollection), target, intent(inout) :: this
    character(len=*), intent(in) :: file_name
    integer, optional, intent(out) :: rc
    integer, pointer :: file_id
    type (StringIntegerMapIterator) :: iter
    type (NetCDF4_FileFormatter) :: fmtr
    integer :: status
    class (AbstractGridFactory), allocatable :: factory
    file_id => this%file_ids%at(trim(file_name))
    if (associated(file_id)) then
       formatter => this%formatters%at(file_id)
       this%file => this%files%at(file_id)
    else
       if (this%formatters%size() >= MAX_FORMATTERS) then
          formatter => this%formatters%front()
          call ESMF_CFIODestroy(formatter)
          call this%formatters%erase(this%formatters%begin())
          deallocate(formatter)
          nullify(formatter)
          call this%files%erase(this%files%begin())
          iter = this%file_ids%begin()
          do while (iter /= this%file_ids%end())
             file_id => iter%value()
             if (file_id == 1) then
                call this%file_ids%erase(iter)
                exit
             end if
             call iter%next()
          end do
          ! Fix the old file_id's accordingly
          iter = this%file_ids%begin()
          do while (iter /= this%file_ids%end())
             file_id => iter%value()
             file_id = file_id -1
             call iter%next()
          end do
       end if
       allocate(formatter)
       formatter = ESMF_CFIOCreate()
       call ESMF_CFIOSet(formatter,fname=trim(file_name),format='SDF')
       call ESMF_CFIOFileOpen(formatter, fmode=1)
       call this%formatters%push_back(formatter)
       ! size() returns 64-bit integer;  cast to 32 bit for this usage.
       call this%file_ids%insert(trim(file_name), int(this%formatters%size()))
       call fmtr%open(trim(file_name), mode=pFIO_READ, rc=status)
       _VERIFY(status)
       ! file is the metadata, not the file name
       call this%files%push_back(fmtr%read())
       call fmtr%close(rc=status)
       _VERIFY(status)
       this%file => this%files%back()
       if (allocated(this%src_grid)) then
       end if
       if (.not. allocated(this%src_grid)) then
          ! First file access can be used to generate the grid
          allocate(factory, source=grid_manager%make_factory(trim(file_name)))
          this%src_grid = grid_manager%make_grid(factory)
       end if
    end if
    _RETURN(_SUCCESS)
  end function find_
Call graph
find_ calls at, insert, next, erase, make_factory, make_grid, esmf_cfiocreate, esmf_cfiodestroy, esmf_cfiofileopen, esmf_cfioset, mapl_return, mapl_verify, v_back, v_begin, v_front, v_push_back
mapl_cfiocreatefromfile calls find_
mapl_cfioreadbundle calls find_
mapl_cfioreadbundleread calls find_
mapl_cfioreadparallel_ calls find_, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread
utcfio calls test_main