find_extension_index – MAPL
find_extension_index Function
4 statements
Source File
private pure function find_extension_index(filename) result(dot_index)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Return Value integer
Called by
Source Code
   pure integer function find_extension_index(filename) result(dot_index)
      character(len=*), intent(in) :: filename
      dot_index = scan(trim(filename),'.', back=.true.)
   end function find_extension_index
Call graph
get_file_basename calls find_extension_index
get_file_extension calls find_extension_index
addchildfromdsometa calls get_file_extension, adjust_dso_name, is_valid_dso_name
adjust_dso_name calls get_file_basename
is_supported_dso_name calls get_file_extension
is_valid_dso_name calls get_file_extension
test_get_file_basename calls get_file_basename
test_get_file_extension calls get_file_extension
mapl_addchild calls addchildfromdsometa, addchildfromdso
addchildfromdso calls addchildfromdsometa
run_dsosetservices calls adjust_dso_name, is_supported_dso_name
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild