find_tile_file – MAPL
find_tile_file Subroutine
76 statements
Source File
private subroutine find_tile_file(this, file_name, swap, unusable, rc)
Uses
MAPL_AbstractGridFactoryMod
MAPL_GridManagerMod
Type Bound
TilingRegridder
Arguments
Type Intent Optional Attributes Name
class(TilingRegridder), intent(inout) :: this
character(len=:), allocatable :: file_name
logical, intent(out) :: swap
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine find_tile_file(this, file_name, swap, unusable, rc)
      class (TilingRegridder), intent(inout) :: this
      character(len=:), allocatable :: file_name
      logical, intent(out) :: swap
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = 'find_tile_file'
      type (RegridderSpec) :: spec
      character(len=:), allocatable :: grid_name_in
      character(len=:), allocatable :: grid_name_out
      character(len=:), allocatable :: trial_name
      logical :: exists
      _UNUSED_DUMMY(unusable)
      spec = this%get_spec()
      block
        use MAPL_AbstractGridFactoryMod
        use MAPL_GridManagerMod
        class (AbstractGridFactory), pointer :: factory
        factory => get_factory(spec%grid_in)
        grid_name_in = factory%generate_grid_name()
        factory => get_factory(spec%grid_out)
        grid_name_out = factory%generate_grid_name()
      end block
      ! First we search for a ".bin" file
      trial_name = make_tile_file_name(grid_name_in, grid_name_out, '.bin')
      inquire(file=trial_name, exist=exists)
      if (exists) then
         swap = .false.
      else ! swap
         swap = .true.
         trial_name = make_tile_file_name(grid_name_out, grid_name_in, '.bin')
         inquire(file=trial_name, exist=exists)
      end if
      if (exists) then
         file_name = trial_name
         this%file_type = GEOS_BINARY
         _RETURN(_SUCCESS)
      end if
      ! Next we search for a tempest ".nc4" file
      trial_name = make_tile_file_name(grid_name_in, grid_name_out,'.nc4')
      inquire(file=trial_name, exist=exists)
      if (exists) then
         swap = .false.
      else ! swap
         swap = .true.
         trial_name = make_tile_file_name(grid_name_out, grid_name_in, '.nc4')
         inquire(file=trial_name, exist=exists)
         ! This was the last chance - fail if we still have not found the file.
         _ASSERT(exists, 'could not find tempest file')
      end if
      if (exists) then
         file_name = trial_name
         this%file_type = TEMPEST
         _RETURN(_SUCCESS)
      end if
      _RETURN(_FAILURE)
      _UNUSED_DUMMY(unusable)
   contains
      function get_grid_name(grid, unusable, rc) result(name)
         character(len=:), allocatable :: name
         type (ESMF_Grid), intent(in) :: grid
         class (KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         character(len=MAPL_TileNameLength) :: buffer
         call ESMF_GridGet(grid, name=buffer, rc=status)
         _VERIFY(status)
         name = trim(buffer)
      end function get_grid_name
   end subroutine find_tile_file
Call graph
find_tile_file calls generate_grid_name, mapl_assert, get_factory, get_spec, make_tile_file_name, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_factory calls mapl_return, get_factory, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, m_at
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception
m_at calls m_find
initialize_subclass calls find_tile_file
initialize_base calls initialize
make_regridder_from_grids calls initialize
newlatlontolatlonregridder calls initialize
latlontolatlonregridder calls newlatlontolatlonregridder