find_ – MAPL
find_ Function
61 statements
Source File
private function find_(this, file_name, rc) result(metadata)
Type Bound
MAPLDataCollection
Arguments
Type Intent Optional Attributes Name
class(MAPLDataCollection), intent(inout), target :: this
character(len=*), intent(in) :: file_name
integer, intent(out), optional :: rc
Return Value type(FileMetadataUtils), pointer
Calls
Called by
Source Code
  function find_(this, file_name, rc) result(metadata)
    type (FileMetadataUtils), pointer :: metadata
    class (MAPLDataCollection), target, intent(inout) :: this
    character(len=*), intent(in) :: file_name
    integer, optional, intent(out) :: rc
    type (NetCDF4_FileFormatter) :: formatter
    type (FileMetadata) :: basic_metadata
    integer, pointer :: file_id
    type (StringIntegerMapIterator) :: iter
    class (AbstractGridFactory), allocatable :: factory
    integer :: status
    type(StringIntegerMap), pointer :: dimensions
    integer, pointer :: tile_size
    logical :: skip_grid
    file_id => this%file_ids%at(file_name)
    if (associated(file_id)) then
       metadata => this%metadatas%at(file_id)
    else
       if (this%metadatas%size() >= MAX_FORMATTERS) then
          metadata => this%metadatas%front()
          call this%metadatas%erase(this%metadatas%begin())
          nullify(metadata)
          iter = this%file_ids%begin()
          do while (iter /= this%file_ids%end())
             file_id => iter%value()
             if (file_id == 1) then
                call this%file_ids%erase(iter)
                exit
             end if
             call iter%next()
          end do
          ! Fix the old file_id's accordingly
          iter = this%file_ids%begin()
          do while (iter /= this%file_ids%end())
             file_id => iter%value()
             file_id = file_id -1
             call iter%next()
          end do
       end if
       allocate(metadata)
       call formatter%open(file_name, pFIO_READ,rc=status)
       _VERIFY(status)
       basic_metadata = formatter%read(_RC)
       call formatter%close(rc=status)
       _VERIFY(status)
       call metadata%create(basic_metadata,file_name)
       call this%metadatas%push_back(metadata)
       deallocate(metadata)
       metadata => this%metadatas%back()
       dimensions => metadata%get_dimensions()
       tile_size => dimensions%at("tile_index")
       skip_grid = associated(tile_size)
       if ( (.not. allocated(this%src_grid)) .and. (.not. skip_grid)) then
          allocate(factory, source=grid_manager%make_factory(trim(file_name),force_file_coordinates=this%use_file_coords))
          this%src_grid = grid_manager%make_grid(factory)
       end if
       ! size() returns 64-bit integer;  cast to 32 bit for this usage.
       call this%file_ids%insert(file_name, int(this%metadatas%size()))
    end if
    _RETURN(_SUCCESS)
  end function find_
Call graph
find_ calls at, insert, next, erase, make_factory, make_grid, create, get_dimensions, mapl_return, mapl_verify, v_back, v_begin, v_front, v_push_back
get_dimensions calls get_dimensions
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
make_factory_from_distgrid calls mapl_return, mapl_verify, initialize, make_clone
make_grid_from_distgrid calls make_factory, make_grid, mapl_return, mapl_verify, ESMF_InfoGetFromHost, ESMF_InfoSet
mapl_throw_exception calls initialize
v_erase_one calls erase
v_grow_to calls v_capacity, v_set_capacity
create_bracketing_fields calls find_
create_primary_field calls find_
detect_metadata calls find_
make_metadata calls find_
makemetadata calls find_
mapl_create_bundle_from_metdata_id calls find_
mapl_read_bundle calls find_, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find_
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls create_primary_field, fillin_primary, makemetadata, getclimyear, getlevs
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields, mapl_extdatagetfstarttime, mapl_extdataprefetch, updatebrackettime
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
get_file_bracket calls get_time_on_file
regrid_util calls main