fraction_r8r8r8v – MAPL
fraction_r8r8r8v Subroutine
31 statements
Source File
private subroutine fraction_r8r8r8v(dynamicMaskList, dynamicSrcMaskValue, dynamicDstMaskValue, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DynamicMaskElementR8R8R8V), pointer :: dynamicMaskList(:)
real(kind=ESMF_KIND_R8), intent(in), optional :: dynamicSrcMaskValue
real(kind=ESMF_KIND_R8), intent(in), optional :: dynamicDstMaskValue
integer, intent(out) :: rc
Calls
Source Code
   subroutine fraction_r8r8r8v(dynamicMaskList, dynamicSrcMaskValue, &
        dynamicDstMaskValue, rc)
      type(ESMF_DynamicMaskElementR8R8R8V), pointer              :: dynamicMaskList(:)
      real(ESMF_KIND_R8),            intent(in), optional :: dynamicSrcMaskValue
      real(ESMF_KIND_R8),            intent(in), optional :: dynamicDstMaskValue
      integer,                       intent(out)          :: rc
      integer :: i, j, k, n
      real(ESMF_KIND_R8), allocatable  :: renorm(:)
      if (associated(dynamicMaskList)) then
         n = size(dynamicMaskList(1)%srcElement(1)%ptr)
         allocate(renorm(n))
         do i=1, size(dynamicMaskList)
            dynamicMaskList(i)%dstElement = 0.0 ! set to zero
            renorm = 0.d0 ! reset
            do j=1, size(dynamicMaskList(i)%factor)
               do k = 1, size(dynamicMaskList(i)%srcElement(j)%ptr)
                  if (.not. &
                       match(dynamicSrcMaskValue,dynamicMaskList(i)%srcElement(j)%ptr(k))) then
                     if (nint(dynamicMaskList(i)%srcElement(j)%ptr(k)) == 0) then
                        dynamicMaskList(i)%dstElement(k) = dynamicMaskList(i)%dstElement(k) + &
                             & dynamicMaskList(i)%factor(j)
                        renorm(k) = renorm(k) + dynamicMaskList(i)%factor(j)
                     end if
                  endif
               end do
            end do
         enddo
      endif
      ! return successfully
      rc = ESMF_SUCCESS
      _UNUSED_DUMMY(dynamicDstMaskValue)
   end subroutine fraction_r8r8r8v
Call graph
fraction_r8r8r8v calls match, ptr
match calls match_r4, match_r8