free_outer_meta – MAPL
free_outer_meta Subroutine
15 statements
Source File
public subroutine free_outer_meta(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine free_outer_meta(gridcomp, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaWrapper) :: wrapper
      type(ESMF_GridComp) :: user_gridcomp
      call MAPL_UserCompGetInternalState(gridcomp, OUTER_META_PRIVATE_STATE, wrapper, status)
      _ASSERT(status==ESMF_SUCCESS, "OuterMetaComponent not created for this gridcomp")
      user_gridcomp = wrapper%outer_meta%user_gc_driver%get_gridcomp()
      call free_inner_meta(user_gridcomp, _RC)
      deallocate(wrapper%outer_meta)
      _RETURN(_SUCCESS)
   end subroutine free_outer_meta
Call graph
free_outer_meta calls mapl_assert, mapl_usercompgetinternalstate, free_inner_meta, get_gridcomp, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
free_inner_meta calls mapl_assert, mapl_usercompgetinternalstate, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize