free_coupler_meta – MAPL
free_coupler_meta Subroutine
11 statements
Source File
public subroutine free_coupler_meta(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine free_coupler_meta(gridcomp, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(CouplerMetaWrapper) :: wrapper
      call MAPL_UserCompGetInternalState(gridcomp, COUPLER_META_PRIVATE_STATE, wrapper, status)
      _ASSERT(status==ESMF_SUCCESS, "CouplerMetaComponent not created for this gridcomp")
      deallocate(wrapper%coupler_meta)
      _RETURN(_SUCCESS)
   end subroutine free_coupler_meta
Call graph
free_coupler_meta calls mapl_assert, mapl_usercompgetinternalstate, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize