generate_file_corner_bounds – MAPL
generate_file_corner_bounds Subroutine
29 statements
Source File
private subroutine generate_file_corner_bounds(this, grid, local_start, global_start, global_count, rc)
Uses
MAPL_BaseMod
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), allocatable :: local_start(:)
integer, intent(out), allocatable :: global_start(:)
integer, intent(out), allocatable :: global_count(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine generate_file_corner_bounds(this,grid,local_start,global_start,global_count,rc)
      use MAPL_BaseMod
      class(CubedSphereGridFactory), intent(inout) :: this
      type(ESMF_Grid),      intent(inout) :: grid
      integer, allocatable, intent(out) :: local_start(:)
      integer, allocatable, intent(out) :: global_start(:)
      integer, allocatable, intent(out) :: global_count(:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: global_dim(3),i1,j1,in,jn,tile
      integer :: face_j1, is, js
      character(len=*), parameter :: Iam = MOD_NAME // 'generate_file_bounds'
      _UNUSED_DUMMY(this)
      call MAPL_GridGet(grid,globalCellCountPerDim=global_dim,rc=status)
      _VERIFY(status)
      call MAPL_GridGetInterior(grid,i1,in,j1,jn)
      tile = 1 + (j1-1)/global_dim(1)
      face_j1 = j1-(tile-1)*global_dim(1)
      is = i1
      js = face_j1
      allocate(local_start,source=[is,js,tile])
      allocate(global_start,source=[1,1,1])
      allocate(global_count,source=[global_dim(1)+1,global_dim(1)+1,6])
      _RETURN(_SUCCESS)
   end subroutine generate_file_corner_bounds
Call graph
generate_file_corner_bounds calls mapl_gridgetinterior, mapl_gridget, mapl_return, mapl_verify
mapl_gridgetinterior calls mapl_gridgetinterior, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, ESMF_DELayoutGet, ESMF_VMGet
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize