generate_file_bounds – MAPL
generate_file_bounds Subroutine
38 statements
Source File
private subroutine generate_file_bounds(this, grid, local_start, global_start, global_count, metaData, rc)
Uses
MAPL_BaseMod
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), allocatable :: local_start(:)
integer, intent(out), allocatable :: global_start(:)
integer, intent(out), allocatable :: global_count(:)
type(FileMetadata), intent(in), optional :: metaData
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine generate_file_bounds(this,grid,local_start,global_start,global_count,metaData,rc)
      use MAPL_BaseMod
      class(CubedSphereGridFactory), intent(inout) :: this
      type(ESMF_Grid),      intent(inout) :: grid
      integer, allocatable, intent(out) :: local_start(:)
      integer, allocatable, intent(out) :: global_start(:)
      integer, allocatable, intent(out) :: global_count(:)
      type(FileMetadata), intent(in), optional :: metaData
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: global_dim(3),i1,j1,in,jn,tile
      character(len=*), parameter :: Iam = MOD_NAME // 'generate_file_bounds'
      logical :: face_format
      if (present(metadata)) then
         face_format = metadata%has_dimension('nf')
      else
         face_format = .true.
      end if
      call MAPL_GridGet(grid,globalCellCountPerDim=global_dim,rc=status)
      _VERIFY(status)
      call MAPL_GridGetInterior(grid,i1,in,j1,jn)
      if (face_format) then
         tile = 1 + (j1-1)/global_dim(1)
         allocate(local_start,source=[i1,j1-(tile-1)*global_dim(1),tile])
         allocate(global_start,source=[1,1,1])
         allocate(global_count,source=[global_dim(1),global_dim(1),6])
      else
         allocate(local_start,source=[i1,j1])
         allocate(global_start,source=[1,1])
         allocate(global_count,source=[global_dim(1),global_dim(2)])
      end if
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(this)
   end subroutine generate_file_bounds
Call graph
generate_file_bounds calls mapl_gridgetinterior, has_dimension, mapl_gridget, mapl_return, mapl_verify
mapl_gridgetinterior calls mapl_gridgetinterior, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, ESMF_DELayoutGet, ESMF_VMGet
has_dimension calls mapl_return, find
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize