generate_rh_name – MAPL
generate_rh_name Function
38 statements
Source File
private function generate_rh_name(grid_in, grid_out, regrid_method, rc) result(file_name)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid_in
type(ESMF_Grid), intent(in) :: grid_out
integer, intent(in) :: regrid_method
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Call graph
generate_rh_name calls mapl_gridget, mapl_return, mapl_verify
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
create_route_handle calls generate_rh_name
initialize_subclass calls create_route_handle
select_route_handle calls create_route_handle
do_regrid calls select_route_handle
regrid_scalar_2d_real32 calls do_regrid
regrid_scalar_2d_real64 calls do_regrid
regrid_scalar_3d_real32 calls do_regrid
regrid_scalar_3d_real64 calls do_regrid
regrid_vector_2d_real32 calls do_regrid
regrid_vector_2d_real64 calls do_regrid
regrid_vector_3d_real32 calls do_regrid
regrid_vector_3d_real64 calls do_regrid
transpose_regrid_scalar_2d_real32 calls do_regrid
transpose_regrid_scalar_3d_real32 calls do_regrid
transpose_regrid_vector_2d_real32 calls do_regrid
transpose_regrid_vector_3d_real32 calls do_regrid