get_dim_name – MAPL
get_dim_name Module Function
50 statements
Source File
module function get_dim_name(file_metadata, units, rc) result(dim_name) Interface →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in), target :: file_metadata
character(len=*), intent(in) :: units
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   module function get_dim_name(file_metadata, units, rc) result(dim_name)
      character(:), allocatable :: dim_name
      type(FileMetadata), target, intent(in) :: file_metadata
      character(*), intent(in) :: units
      integer, optional, intent(out) :: rc
      integer :: status
      type(StringVariableMap), pointer :: vars
      type(Variable), pointer :: var
      type(StringVariableMapIterator) :: iter
      type(StringVector), pointer :: dims
      character(:), allocatable :: units_lower_case
      character(:), allocatable :: units_found
      logical :: has_units
      type(Attribute), pointer :: attr
      logical :: found
      integer :: counter
      dim_name = ''
      units_lower_case = ESMF_UtilStringLowerCase(units, _RC)
      found = .false.
      counter = 0
      vars => file_metadata%get_variables(_RC)
      associate ( e => vars%ftn_end() )
        iter = vars%ftn_begin()
        do while (iter /= e)
           call iter%next()
           var => iter%second()
           has_units = var%is_attribute_present('units', _RC)
           if (.not. has_units) cycle
           attr => var%get_attribute('units', _RC)
           units_found = attr%get_string(_RC)
           units_found = ESMF_UtilStringLowerCase(units_found, _RC)
           if (units_found /= units_lower_case) cycle
           dims => var%get_dimensions()
           if (dims%size() /= 1) cycle
           found = .true.
           counter = counter + 1
           _ASSERT(counter == 1, 'Too many variables match requested units: ' // units)
           dim_name = dims%of(1)
        end do
      end associate
      _ASSERT(found, "No variable found with units: " // units//".")
      _RETURN(_SUCCESS)
   end function get_dim_name
Call graph
get_dim_name calls ESMF_UtilStringLowerCase, mapl_assert, of, get_attribute, get_dimensions, get_string, get_variables, is_attribute_present, map_ftn_begin, map_ftn_end, map_iter_next, mapl_return, mapl_verify, get_dim_name
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_string calls mapl_return, get_value
get_variables calls mapl_return
is_attribute_present calls mapl_return, m_at
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
m_at calls m_find
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_lataxis_from_metadata calls get_dim_name, make_lataxis_from_metadata
make_lonaxis_from_metadata calls get_dim_name, make_lonaxis_from_metadata
supports_metadata calls get_dim_name, supports_metadata
make_lataxis calls make_lataxis_from_metadata
make_lonaxis calls make_lonaxis_from_metadata