get_coordinates_dim – MAPL
get_coordinates_dim Module Function
23 statements
Source File
module function get_coordinates_dim(file_metadata, dim_name, rc) result(coordinates) Interface →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: file_metadata
character(len=*), intent(in) :: dim_name
integer, intent(out), optional :: rc
Return Value real(kind=R8), dimension(:), allocatable
Calls
Called by
Source Code
   module function get_coordinates_dim(file_metadata, dim_name, rc) result(coordinates)
      real(kind=R8), dimension(:), allocatable :: coordinates
      type(FileMetadata), intent(in) :: file_metadata
      character(len=*), intent(in) :: dim_name
      integer, optional, intent(out) :: rc
      integer :: status
      class (CoordinateVariable), pointer :: v
      class (*), pointer :: ptr(:)
      v => file_metadata%get_coordinate_variable(dim_name, _RC)
      ptr => v%get_coordinate_data()
      _ASSERT(associated(ptr),'coordinate data not allocated')
      select type (ptr)
      type is (real(kind=REAL64))
         coordinates = ptr
      type is (real(kind=REAL32))
         coordinates = ptr
      class default
         _FAIL('unsuppoted kind for coordinate data -- must be REAL32 or REAL64')
      end select
      _RETURN(_SUCCESS)
   end function get_coordinates_dim
Call graph
get_coordinates_dim calls mapl_assert, get_coordinate_data, get_coordinate_variable, mapl_return, mapl_verify, get_coordinates_dim
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_coordinate_data calls mapl_return
get_coordinate_variable calls mapl_assert, mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_at_rc calls map_find
get_coordinates calls get_coordinates_dim
make_lataxis_from_metadata calls get_coordinates, make_lataxis_from_metadata
make_lonaxis_from_metadata calls get_coordinates, make_lonaxis_from_metadata