get_item – MAPL
get_item Function
11 statements
Source File
private function get_item(this, standard_name, rc) result(item)
Type Bound
FieldDictionary
Arguments
Type Intent Optional Attributes Name
class(FieldDictionary), intent(in) :: this
character(len=*), intent(in) :: standard_name
integer, intent(out), optional :: rc
Return Value type(FieldDictionaryItem)
Calls
Called by
Source Code
   function get_item(this, standard_name, rc) result(item)
      type(FieldDictionaryItem) :: item
      class(FieldDictionary), intent(in) :: this
      character(*), intent(in) :: standard_name
      integer, optional, intent(out) :: rc
      integer :: status
      item = this%entries%at(standard_name, _RC)
      _RETURN(_SUCCESS)
   end function get_item
Call graph
get_item calls at, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
map_find calls map_s_find
test_get_field_item calls get_item