get_vertical_dimension_name – MAPL
get_vertical_dimension_name Function
16 statements
Source File
public function get_vertical_dimension_name(dim_spec_name) result(dim_name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: dim_spec_name
Return Value character(len=:), allocatable
Called by
Source Code
   function get_vertical_dimension_name(dim_spec_name) result(dim_name)
      character(len=:), allocatable :: dim_name
      character(len=*), intent(in) :: dim_spec_name
      character(len=*), parameter :: VERTICAL_CENTER_NAME = 'lev'
      character(len=*), parameter :: VERTICAL_EDGE_NAME = 'edge'
      character(len=*), parameter :: VERTICAL_UNKNOWN_NAME = EMPTY
      dim_name = VERTICAL_UNKNOWN_NAME
      if(dim_spec_name == 'VERTICAL_DIM_EDGE') then
         dim_name = VERTICAL_EDGE_NAME
         return
      end if
      if(dim_spec_name == 'VERTICAL_DIM_CENTER') then
         dim_name = VERTICAL_CENTER_NAME
         return
      end if
   end function get_vertical_dimension_name
Call graph
add_vertical_dimensions calls get_vertical_dimension_name
get_vertical_dimension_name_from_field calls get_vertical_dimension_name
test_get_vertical_dimension_name calls get_vertical_dimension_name
add_variable calls get_vertical_dimension_name_from_field
bundle_to_metadata calls add_vertical_dimensions, add_variables
add_variables calls add_variable