get_global_memory_profiler – MAPL
get_global_memory_profiler Function
4 statements
Source File
public function get_global_memory_profiler() result(memory_profiler)
Arguments
None
Return Value class(DistributedProfiler), pointer
Called by
Source Code
   function get_global_memory_profiler() result(memory_profiler)
      class(DistributedProfiler), pointer :: memory_profiler
      memory_profiler => global_memory_profiler
   end function get_global_memory_profiler
Call graph
addchildfromdsometa calls get_global_memory_profiler
addchildfrommeta calls get_global_memory_profiler
finalize calls get_global_memory_profiler, report_global_profiler, mapl_genericfinalize
mapl_genericfinalize calls get_global_memory_profiler
mapl_genericinitialize calls get_global_memory_profiler
mapl_genericrecord calls get_global_memory_profiler
mapl_genericwrapper calls get_global_memory_profiler
report_global_profiler calls get_global_memory_profiler
mapl_addchild calls addchildfromdsometa, addchildfrommeta, addchildfromdso, addchildfromgc, addchildfromdso_old
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta
finalize_ calls mapl_genericfinalize
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
run calls finalize
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild
extdata_driver calls run
main calls run_component_driver