get_variable – MAPL
get_variable Function
16 statements
Source File
private function get_variable(this, var_name, unusable, rc) result(var)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(Variable), pointer
Calls
Called by
Source Code
   function get_variable(this, var_name, unusable, rc) result(var)
      class (Variable), pointer :: var
      class (FileMetadata), target, intent(in) :: this
      character(len=*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      var => this%variables%at(var_name, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function get_variable
Call graph
get_variable calls at, mapl_return, mapl_verify, get_variable
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
map_find calls map_s_find
add_var_attribute_0d calls get_variable
add_var_attribute_1d calls get_variable
compute_time_for_current calls get_variable, get_file_start_time
createfilemetadata calls get_variable
get_file_start_time calls get_variable
get_start_time calls get_variable
mapl_iogettime calls get_variable
transfer_metadata calls get_variable
write_data calls get_variable
compute_time_vector calls get_start_time
create_from_bundle calls createfilemetadata
get_var_attr_int32 calls get_variable
get_var_attr_int64 calls get_variable
get_var_attr_real32 calls get_variable
get_var_attr_real64 calls get_variable
get_var_attr_string calls get_variable
get_variable_attribute calls get_variable
getlevs calls get_variable
initialize calls createfilemetadata
run calls createfilemetadata
var_get_missing_value calls get_variable
var_has_attr calls get_variable
var_has_missing_value calls get_variable
main calls transfer_metadata, write_data