get_state_by_esmf_intent – MAPL
get_state_by_esmf_intent Subroutine
21 statements
Source File
private subroutine get_state_by_esmf_intent(this, state, state_intent, rc)
Type Bound
MultiState
Arguments
Type Intent Optional Attributes Name
class(MultiState), intent(in) :: this
type(ESMF_State), intent(out) :: state
type(ESMF_StateIntent_Flag), intent(in) :: state_intent
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_state_by_esmf_intent(this, state, state_intent, rc)
      class(MultiState), intent(in) :: this
      type(ESMF_State), intent(out) :: state
      type(ESMF_StateIntent_Flag), intent(in) :: state_intent
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: string_intent
      if (state_intent == ESMF_STATEINTENT_IMPORT) then
         string_intent = 'import'
      else if (state_intent == ESMF_STATEINTENT_EXPORT) then
         string_intent = 'export'
      else if (state_intent == ESMF_STATEINTENT_INTERNAL) then
         string_intent = 'internal'
      else
         string_intent = '<unknown>'
      end if
      call this%get_state(state, string_intent, _RC)
      _RETURN(_SUCCESS)
   end subroutine get_state_by_esmf_intent
Call graph
get_state_by_esmf_intent calls get_state, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_to_state calls get_state
get_field calls get_state
test_anything calls get_state
test_child_user_items_created calls get_state
test_parent_outer_items_created calls get_state
test_parent_user_items_created calls get_state
test_state_items_complete calls get_state
test_vertical calls get_state, add_to_state
test_child_outer_items_created calls get_field