get_long_name – MAPL
get_long_name Function
13 statements
Source File
private function get_long_name(this, standard_name, rc) result(long_name)
Type Bound
FieldDictionary
Arguments
Type Intent Optional Attributes Name
class(FieldDictionary), intent(in), target :: this
character(len=*), intent(in) :: standard_name
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_long_name(this, standard_name, rc) result(long_name)
      character(:), allocatable :: long_name
      class(FieldDictionary), target, intent(in) :: this
      character(*), intent(in) :: standard_name
      integer, optional, intent(out) :: rc
      type(FieldDictionaryItem), pointer :: item
      integer :: status
      item => this%entries%at(standard_name, _RC)
      long_name = item%get_long_name()
      _RETURN(_SUCCESS)
   end function get_long_name
Call graph
get_long_name calls at, get_long_name, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
map_find calls map_s_find
test_get_long_name calls get_long_name