get_decomposition – MAPL
get_decomposition Module Function
5 statements
Source File
pure module function get_decomposition(spec) result(decomposition) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomSpec), intent(in) :: spec
Return Value type(LatLonDecomposition)
Called by
Source Code
   pure module function get_decomposition(spec) result(decomposition)
      type(LatLonDecomposition) :: decomposition
      class(LatLonGeomSpec), intent(in) :: spec
      decomposition = spec%decomposition
   end function get_decomposition
Call graph
get_decomposition calls get_decomposition
create_basic_grid calls get_decomposition, create_basic_grid
fill_coordinates calls get_decomposition, fill_coordinates
typesafe_make_geom calls create_basic_grid, fill_coordinates