get_clock – MAPL
get_clock Module Function
5 statements
Source File
module function get_clock(this) result(clock) Interface →
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriver), intent(in) :: this
Return Value type(ESMF_Clock)
Called by
Source Code
   module function get_clock(this) result(clock)
      type(ESMF_Clock) :: clock
      class(GriddedComponentDriver), intent(in) :: this
      clock = this%clock
   end function get_clock
Call graph
get_clock calls get_clock
add_child_by_name calls get_clock, add_child_by_name
integrate calls get_clock
mapl_run_driver calls integrate
run_geos calls mapl_run_driver