get_name – MAPL
get_name Function
5 statements
Source File
private pure function get_name(this) result(name)
Type Bound
UngriddedDimSpec
Arguments
Type Intent Optional Attributes Name
class(UngriddedDimSpec), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   pure function get_name(this) result(name)
      character(:), allocatable :: name
      class(UngriddedDimSpec), intent(in) :: this
      name = this%name
   end function get_name
Call graph
add_dim_spec calls get_name
parse_var_specs calls add_dim_spec
test_field_set_info calls add_dim_spec
parse_component_spec calls parse_var_specs
setservices_ calls parse_component_spec