get_num_levels_bundle_info – MAPL
get_num_levels_bundle_info Function
16 statements
Source File
public function get_num_levels_bundle_info(info, rc) result(num)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function get_num_levels_bundle_info(info, rc) result(num)
      type(ESMF_Info), intent(in) :: info(:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i, n
      num = 0
      do i=1, size(info)
         n = get_num_levels_info(info(i), _RC)
         num = max(num, n)
         if(n == 0) cycle
         _ASSERT(n == num, 'Fields with vertical levels must have the same number of levels.')
      end do
      _RETURN(_SUCCESS)
   end function get_num_levels_bundle_info
Call graph
get_num_levels_bundle_info calls ESMF_InfoGet, ESMF_InfoGetCharAlloc, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_get_num_levels calls get_num_levels_bundle_info