get_hconfig_as_i8 – MAPL
get_hconfig_as_i8 Subroutine
10 statements
Source File
private subroutine get_hconfig_as_i8(value, params, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I8), intent(out) :: value
class(HConfigParams), intent(in) :: params
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_hconfig_as_i8(value, params, rc)
      integer(kind=ESMF_KIND_I8), intent(out) :: value
      class(HConfigParams), intent(in) :: params
      integer, optional, intent(out) :: rc
      integer :: status
      value = ESMF_HConfigAsI8(params%hconfig, keyString=params%label, _RC)
      _RETURN(_SUCCESS)
   end subroutine get_hconfig_as_i8
Call graph
get_hconfig_as_i8 calls esmf_hconfigasi8, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_hconfig calls get_hconfig_as_i8
get_value_i4 calls get_hconfig
get_value_i4seq calls get_hconfig
get_value_i8 calls get_hconfig
get_value_i8seq calls get_hconfig
get_value_logical calls get_hconfig
get_value_logical_seq calls get_hconfig
get_value_r4 calls get_hconfig
get_value_r4seq calls get_hconfig
get_value_r8 calls get_hconfig
get_value_r8seq calls get_hconfig
get_value_string calls get_hconfig
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string