get_phase_index_ – MAPL
get_phase_index_ Function
14 statements
Source File
private function get_phase_index_(phases, phase_name, unusable, found) result(phase_index)
Arguments
Type Intent Optional Attributes Name
type(StringVector), intent(in) :: phases
character(len=*), intent(in) :: phase_name
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(out), optional :: found
Return Value integer
Calls
Called by
Source Code
   integer function get_phase_index_(phases, phase_name, unusable, found) result(phase_index)
      type(StringVector), intent(in) :: phases
      character(len=*), intent(in) :: phase_name
      class(KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(out) :: found
      phase_index = -1 ! unless
      associate (b => phases%begin(), e => phases%end())
        associate (iter => find(b, e, phase_name))
          phase_index = 1 + distance(b, iter)
          if (present(found)) found = (iter /= e)
        end associate
      end associate
      _UNUSED_DUMMY(unusable)
   end function get_phase_index_
Call graph
get_phase_index_ calls begin, distance, find
get_phase_index calls get_phase_index_
finalize calls get_phase_index, run_custom, finalize
run_child_by_name calls get_phase_index, run_child
run_custom calls get_phase_index
run calls get_phase_index, run
set_entry_point calls get_phase_index
gridcomp_set_entry_point calls set_entry_point
initialize_advertise calls run_custom
initialize_geom calls run_custom
initialize_post_advertise calls run_custom
initialize_realize calls run_custom
initialize_user calls run_custom
test_finalize_children calls finalize
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
initialize calls initialize_advertise, initialize_geom, initialize_post_advertise, initialize_realize, initialize_user
run_children_ calls run_child
test_init_children calls initialize_user