get_dimensions – MAPL
get_dimensions Function
5 statements
Source File
private function get_dimensions(this) result(dimensions)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
Return Value type(StringVector), pointer
Called by
Source Code
   function get_dimensions(this) result(dimensions)
      class (Variable), target, intent(in) :: this
      type (StringVector), pointer :: dimensions
      dimensions => this%dimensions
   end function get_dimensions
Call graph
add_variable calls get_dimensions
def_variables calls get_dimensions
get_dim_name calls get_dimensions
mapl_create_bundle_from_metdata_id calls get_dimensions
modify_variable calls get_dimensions
transfer_metadata calls get_dimensions
write_data calls get_dimensions
write_variables calls get_dimensions