get_value_logical_seq – MAPL
get_value_logical_seq Subroutine
55 statements
Source File
private subroutine get_value_logical_seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
logical, intent(inout), dimension(:), allocatable :: value
logical, intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_value_logical_seq(params, value, default, valuestring, rc)
      logical, dimension(:), allocatable, intent(inout) :: value
      logical, dimension(:), optional, intent(in) :: default
      character(len=*), parameter :: typestring = 'L'
      character(len=*), parameter :: edit_descriptor = EDIT_DESC_L
#include "hconfig_get_value_template.h"
   end subroutine get_value_logical_seq
Call graph
get_value_logical_seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value calls get_value_logical_seq