get_field – MAPL
get_field Subroutine
19 statements
Source File
public subroutine get_field(state, field, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_field(state, field, rc)
      type(ESMF_State), intent(inout) :: state
      type(ESMF_Field), intent(inout) :: field
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=ESMF_MAXSTR) :: itemNameList(1)
      call ESMF_StateGet(state, itemNameList=itemNameList, _RC)
      call ESMF_StateGet(state, itemName=itemNameList(1), field=field, _RC)
      _RETURN(_SUCCESS)
   end subroutine get_field
Call graph
get_field calls anyexceptions, assert_that, esmf_stateget, sourcelocation
destroy_objects calls get_field
test_accumulate_mean_r4 calls get_field, destroy_objects
test_invalidate calls get_field, destroy_objects
test_update calls get_field, destroy_objects
test_accumulate calls destroy_objects
test_accumulate_r4 calls destroy_objects
test_calculate_mean calls destroy_objects
test_calculate_mean_r4 calls destroy_objects
test_clear_accumulator calls destroy_objects
test_clear_valid_mean calls destroy_objects
test_initialize calls destroy_objects
test_max_accumulate_r4 calls destroy_objects
test_min_accumulate_r4 calls destroy_objects