get_cost_string – MAPL
get_cost_string Function
5 statements
Source File
private function get_cost_string(a, b) result(cost)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(in), allocatable :: a
character(len=:), intent(in), allocatable :: b
Return Value integer
Calls
Called by
Source Code
   integer function get_cost_string(a, b) result(cost)
      character(:), allocatable, intent(in) :: a, b
      cost = 0
      if (.not. match(a,b)) cost = 1
   end function get_cost_string
Call graph
get_cost_string calls match
match calls match_geom, match_string, match_typekind
match_geom calls mapl_samegeom
match_string calls mirror
mapl_samegeom calls same_geom
get_cost calls get_cost_string
extension_cost calls get_cost, extension_cost