get_coordinate_info – MAPL
get_coordinate_info Subroutine
96 statements
Source File
private subroutine get_coordinate_info(this, coordinate_name, coordSize, coordUnits, long_name, standard_name, coords, coordinate_attr, rc)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: coordinate_name
integer, intent(out), optional :: coordSize
character(len=*), intent(out), optional :: coordUnits
character(len=*), intent(out), optional :: long_name
character(len=*), intent(out), optional :: standard_name
real, intent(inout), optional, allocatable :: coords(:)
character(len=*), intent(out), optional :: coordinate_attr
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_coordinate_info(this,coordinate_name,coordSize,coordUnits,long_name,standard_name,coords,coordinate_attr,rc)
      class (FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: coordinate_name
      integer, optional, intent(out) :: coordSize
      character(len=*), optional, intent(out) :: coordUnits
      character(len=*), optional, intent(out) :: long_name
      character(len=*), optional, intent(out) :: standard_name
      character(len=*), optional, intent(out) :: coordinate_attr
      real, allocatable, optional,  intent(inout) :: coords(:)
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: fname
      class(CoordinateVariable), pointer :: var
      type(Attribute), pointer :: attr
      character(len=:), pointer :: vdim
      class(*), pointer :: coordUnitPtr
      class(*), pointer :: ptr(:)
      fname = this%get_file_name(_RC)
      var => this%get_coordinate_variable(trim(coordinate_name),rc=status)
      _VERIFY(status)
      if (present(coordSize)) then
         vdim => var%get_ith_dimension(1)
         coordSize = this%get_dimension(vdim,rc=status)
      end if
      if (present(coordUnits)) then
         attr => var%get_attribute('units')
         coordUnitPtr => attr%get_value()
         select type(coordUnitPtr)
         type is (character(*))
            coordUnits = trim(coordUnitPtr)
         class default
            _FAIL(trim(coordinate_name)//' units must be string in '//fname)
         end select
      end if
      if (present(long_name)) then
         if (this%var_has_attr(coordinate_name,"long_name")) then
            attr => var%get_attribute('long_name')
            coordUnitPtr => attr%get_value()
            select type(coordUnitPtr)
            type is (character(*))
               long_name = trim(coordUnitPtr)
            class default
               _FAIL(trim(coordinate_name)//' long_name must be string in '//fname)
            end select
         else
             long_name = 'not found'
         endif
      end if
      if (present(standard_name)) then
         if (this%var_has_attr(coordinate_name,"standard_name")) then
            attr => var%get_attribute('standard_name')
            coordUnitPtr => attr%get_value()
            select type(coordUnitPtr)
            type is (character(*))
               standard_name = trim(coordUnitPtr)
            class default
               _FAIL(trim(coordinate_name)//' standard_name must be string in '//fname)
            end select
         else
             standard_name = 'not found'
         endif
      end if
      if (present(coordinate_attr)) then
         if (this%var_has_attr(coordinate_name,"coordinate")) then
            attr => var%get_attribute('coordinate')
            coordUnitPtr => attr%get_value()
            select type(coordUnitPtr)
            type is (character(*))
               coordinate_attr = trim(coordUnitPtr)
            class default
               _FAIL(trim(coordinate_name)//' name must be string in '//fname)
            end select
         else
             coordinate_attr = 'not found'
         endif
      end if
      if (present(coords)) then
         ptr => var%get_coordinate_data()
         _ASSERT(associated(ptr),"coord variable coordinate data not found in "//fname)
         select type (ptr)
         type is (real(kind=REAL64))
            coords=ptr
         type is (real(kind=REAL32))
            coords=ptr
         type is (integer(kind=INT64))
            coords=ptr
         type is (integer(kind=INT32))
            coords=ptr
         class default
            _FAIL("unsupported coordinate variable type in "//fname)
         end select
      end if
      _RETURN(_SUCCESS)
   end subroutine get_coordinate_info
Call graph
get_coordinate_info calls mapl_assert, get_attribute, get_coordinate_data, get_coordinate_variable, get_dimension, get_file_name, get_ith_dimension, get_value, mapl_return, mapl_verify, var_has_attr
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_coordinate_data calls mapl_return
get_coordinate_variable calls mapl_return, mapl_verify, get_coordinate_variable, mapl_assert, at
get_dimension calls mapl_return, mapl_verify, get_dimension, at, find
get_file_name calls mapl_return
get_ith_dimension calls mapl_return, at
get_value calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
var_has_attr calls mapl_assert, get_file_name, mapl_return, mapl_verify, get_variable, is_attribute_present
get_error_message calls at, insert
get_variable calls mapl_return, mapl_verify, get_variable, at
is_attribute_present calls mapl_return, m_at
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
get_file_levels calls get_coordinate_info
get_time_info calls get_coordinate_info
getlevs calls get_coordinate_info
initialize_ calls get_coordinate_info, getlevs, getclimyear, create_primary_field, fillin_primary
time_ave calls get_coordinate_info, get_file_levels, get_file_times, mapl_read_bundle
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
detect_metadata calls get_time_info
get_file_times calls get_time_info
get_time_on_file calls get_time_info
getclimyear calls get_time_info
main calls get_file_levels, get_file_times, mapl_read_bundle, run_component_driver
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info
run_component_driver calls get_time_info
updatebrackettime calls get_time_info
fillin_primary calls detect_metadata
get_file_bracket calls get_time_on_file
run_ calls create_bracketing_fields, mapl_extdatagetfstarttime, updatebrackettime
regrid_util calls main
ut_regridding calls mapl_read_bundle
comp_testing_driver calls main