get_vertical_dimension_num_levels – MAPL
get_vertical_dimension_num_levels Function
6 statements
Source File
public function get_vertical_dimension_num_levels(dim_spec_name, num_levels) result(num)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: dim_spec_name
integer, intent(in) :: num_levels
Return Value integer
Called by
Source Code
   integer function get_vertical_dimension_num_levels(dim_spec_name, num_levels) result(num)
      character(len=*), intent(in) :: dim_spec_name
      integer, intent(in) :: num_levels
      num = num_levels
      if(dim_spec_name == 'VERTICAL_DIM_EDGE') num = num_levels + 1
   end function get_vertical_dimension_num_levels
Call graph
add_vertical_dimensions calls get_vertical_dimension_num_levels
test_get_vertical_dimension_num_levels calls get_vertical_dimension_num_levels
bundle_to_metadata calls add_vertical_dimensions