get_child_by_name – MAPL
get_child_by_name Function
12 statements
Source File
private function get_child_by_name(this, child_name, rc) result(child_component)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(in) :: this
character(len=*), intent(in) :: child_name
integer, intent(out), optional :: rc
Return Value type(GriddedComponentDriver)
Calls
Called by
Source Code
   type(GriddedComponentDriver) function get_child_by_name(this, child_name, rc) result(child_component)
      class(OuterMetaComponent), intent(in) :: this
      character(len=*), intent(in) :: child_name
      integer, optional, intent(out) :: rc
      integer :: status
      class(GriddedComponentDriver), pointer :: child_ptr
      child_ptr => this%children%at(child_name, rc=status)
      _ASSERT(associated(child_ptr), 'Child not found: <'//child_name//'>.')
      child_component = child_ptr
      _RETURN(_SUCCESS)
   end function get_child_by_name
Call graph
get_child_by_name calls mapl_assert, at, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
omap_at_rc calls at
get_child_user_states calls get_child
get_substates calls get_child, get_substates
run_child_by_name calls get_child, run_child
test_child_user_items_created calls get_child
test_state_items_complete calls get_child
test_anything calls get_substates
test_child_outer_items_created calls get_child_user_states
run_children_ calls run_child