get_field_attributes_from_state – MAPL
get_field_attributes_from_state Function
36 statements
Source File
private function get_field_attributes_from_state(state) result(attributes)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
Return Value type(Field_Attributes), allocatable, (:)
Calls
Called by
Source Code
    function get_field_attributes_from_state(state) result(attributes)
        type(Field_Attributes), allocatable :: attributes(:)
        type(ESMF_State), intent(in)        :: state
        integer                                 :: num_items, rc, i
        type(ESMF_Field)                        :: field
        character(len=ESMF_MAXSTR), allocatable :: item_names(:)
        character(len=ESMF_MAXSTR)              :: str
        type(ESMF_Info)                         :: infoh
        call ESMF_StateGet(state, itemcount = num_items, rc = rc)
        VERIFY_NUOPC_(rc)
        allocate(item_names(num_items))
        allocate(attributes(num_items))
        call ESMF_StateGet(state, itemnamelist = item_names, rc = rc)
        VERIFY_NUOPC_(rc)
        do i = 1, num_items
            call ESMF_StateGet(state, item_names(i), field, rc = rc)
            VERIFY_NUOPC_(rc)
            call ESMF_FieldValidate(field, rc = rc)
            VERIFY_NUOPC_(rc)
            attributes(i)%field = field
            call ESMF_InfoGetFromHost(field,infoh,rc = rc)
            VERIFY_NUOPC_(rc)
            call ESMF_InfoGet(infoh,'LONG_NAME',str,rc = rc)
            VERIFY_NUOPC_(rc)
            attributes(i)%long_name = trim(str)
            call ESMF_FieldGet(field, name = str, rc = rc)
            VERIFY_NUOPC_(rc)
            attributes(i)%short_name = trim(str)
            call ESMF_InfoGetFromHost(field,infoh,rc = rc)
            VERIFY_NUOPC_(rc)
            call ESMF_InfoGet(infoh,'UNITS',str,rc = rc)
            VERIFY_NUOPC_(rc)
            if (str == "" .or. str == " ") str = "1" ! NUOPC doesn't like blank units
            attributes(i)%units = trim(str)
        end do
    end function get_field_attributes_from_state
Call graph
get_field_attributes_from_state calls ESMF_FieldValidate, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_LogFoundError, esmf_fieldget, esmf_stateget
advertise_fields calls get_field_attributes_from_state
realize_fields calls get_field_attributes_from_state