get_ith_dim_spec – MAPL
get_ith_dim_spec Function
11 statements
Source File
private function get_ith_dim_spec(this, i, rc) result(dim_spec)
Type Bound
UngriddedDimsSpec
Arguments
Type Intent Optional Attributes Name
class(UngriddedDimsSpec), intent(in), target :: this
integer, intent(in) :: i
integer, intent(out), optional :: rc
Return Value type(UngriddedDimSpec), pointer
Calls
Called by
Source Code
   function get_ith_dim_spec(this, i, rc) result(dim_spec)
      type(UngriddedDimSpec), pointer :: dim_spec
      class(UngriddedDimsSpec), target, intent(in) :: this
      integer, intent(in) :: i
      integer, optional, intent(out) :: rc
      integer :: status
      dim_spec => this%dim_specs%at(i, _RC)
      _RETURN(_SUCCESS)
   end function get_ith_dim_spec
Call graph
get_ith_dim_spec calls at, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_info calls get_ith_dim_spec
set_info calls make_info
allocate calls set_info
test_field_set_info calls set_info