get_extent – MAPL
get_extent Module Function
5 statements
Source File
pure module function get_extent(this) result(extent) Interface →
Arguments
Type Intent Optional Attributes Name
class(CoordinateAxis), intent(in) :: this
Return Value integer
Called by
Source Code
   pure module function get_extent(this) result(extent)
      class(CoordinateAxis), intent(in) :: this
      integer :: extent
      extent = size(this%centers)
   end function get_extent
Call graph
get_extent calls get_extent
make_latlongeomspec_from_hconfig calls get_extent, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls get_extent, make_latlongeomspec_from_metadata
typesafe_make_file_metadata calls get_extent
make_file_metadata calls typesafe_make_file_metadata, make_file_metadata
make_latlongeomspec calls make_latlongeomspec_from_hconfig, make_latlongeomspec_from_metadata