get_file_extension – MAPL
get_file_extension Function
11 statements
Source File
public pure function get_file_extension(filename) result(extension)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   pure function get_file_extension(filename) result(extension)
      ! Function that returns the extension of a string filename
      ! where filename is "basename.extension"
      character(len=*), intent(in) :: filename
      character(len=:), allocatable :: extension
      integer :: dot_index
      dot_index = find_extension_index(trim(filename))
      ! If the filename has no extension, return blank string
      if (dot_index > 0) then
         extension = trim(filename(dot_index:))
      else
         extension = ''
      endif
   end function get_file_extension
Call graph
get_file_extension calls find_extension_index
addchildfromdsometa calls get_file_extension, is_valid_dso_name
is_supported_dso_name calls get_file_extension
is_valid_dso_name calls get_file_extension
test_get_file_extension calls get_file_extension
mapl_addchild calls addchildfromdsometa, addchildfromdso, addchildfromdso_old
addchildfromdso calls addchildfromdsometa
run_dsosetservices calls is_supported_dso_name
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild
main calls run_component_driver