get_aspect_multi – MAPL
get_aspect_multi Subroutine
13 statements
Source File
public subroutine get_aspect_multi()
Arguments
None
Calls
Source Code
   subroutine get_aspect_multi()
      type(StringVector) :: aspect_names
      type(MockItemSpec) :: spec, goal
      spec = MockItemSpec(name='3')
      goal = MockItemSpec(name='0')
      aspect_names = spec%get_aspect_order(goal)
      associate ( expected => aspect_names%size() ) ! returns INT64
        @assert_that(int(expected), is(3))
      end associate
      @assertEqual(aspect_names%of(1), 'a1')
      @assertEqual(aspect_names%of(2), 'b2')
      @assertEqual(aspect_names%of(3), 'c3')
   end subroutine get_aspect_multi
Call graph
get_aspect_multi calls assert_that, assertequal, get_aspect_order, of