get_actual_pt_SpecPtrs – MAPL
get_actual_pt_SpecPtrs Function
22 statements
Source File
private function get_actual_pt_SpecPtrs(this, virtual_pt, rc) result(specs)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
type(VirtualConnectionPt), intent(in) :: virtual_pt
integer, intent(out), optional :: rc
Return Value type(StateItemSpecPtr), allocatable, (:)
Calls
Called by
Source Code
   function get_actual_pt_SpecPtrs(this, virtual_pt, rc) result(specs)
      type(StateItemSpecPtr), allocatable :: specs(:)
      class(HierarchicalRegistry), target, intent(in) :: this
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i, n
      type(ActualPtVector), pointer :: actual_pts
      type(ActualConnectionPt), pointer :: actual_pt
      actual_pts => this%virtual_pts%at(virtual_pt, rc=status)
      if (status /= 0) allocate(specs(0))
      _VERIFY(status)
      n = actual_pts%size()
      allocate(specs(n))
      do i = 1, n
         actual_pt => actual_pts%of(i)
         specs(i)%ptr => this%get_item_spec(actual_pt, _RC)
      end do
      _RETURN(_SUCCESS)
   end function get_actual_pt_SpecPtrs
Call graph
get_actual_pt_specptrs calls at, of, get_item_spec, mapl_return, mapl_verify
get_item_spec calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
map_find calls map_s_find
connect calls get_actual_pt_specptrs, connect_sibling
connect_sibling calls get_actual_pt_specptrs