get_latlon_from_factory – MAPL
get_latlon_from_factory Subroutine
26 statements
Source File
private subroutine get_latlon_from_factory(grid, lons, lats, rc)
Uses
MAPL_AbstractGridFactoryMod
MAPL_Constants
MAPL_LatLonGridFactoryMod
MAPL_GridManagerMod
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
real, intent(out) :: lons(:)
real, intent(out) :: lats(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine get_latlon_from_factory(grid, lons, lats, rc)
    use MAPL_AbstractGridFactoryMod
    use MAPL_LatLonGridFactoryMod
    use MAPL_GridManagerMod
    use MAPL_Constants, only: MAPL_RADIANS_TO_DEGREES
    type (ESMF_GRid), intent(in) :: grid
    real, intent(out) :: lons(:), lats(:)
    integer :: i
    integer, optional, intent(out) :: rc
    integer :: status
    class (AbstractGridFactory), pointer :: factory
    factory => get_factory(grid, rc=status)
    _VERIFY(status)
    select type (factory)
    type is (LatLonGridFactory)
      lons = MAPL_RADIANS_TO_DEGREES * factory%get_longitudes()
      lats = MAPL_RADIANS_TO_DEGREES * factory%get_latitudes()
    class default
      do i=1,size(lons)
         lons(i)=i
      enddo
      do i=1,size(lats)
         lats(i)=i
      enddo
    end select
  end subroutine get_latlon_from_factory
Call graph
get_latlon_from_factory calls get_latitudes, get_longitudes, get_factory, mapl_verify
get_factory calls mapl_verify, get_factory, mapl_return, ESMF_InfoGet, ESMF_InfoGetFromHost, m_at
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
m_at calls m_find
mapl_cfiocreatefrombundle calls get_latlon_from_factory
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main