get_aspect_one – MAPL
get_aspect_one Subroutine
11 statements
Source File
public subroutine get_aspect_one()
Arguments
None
Calls
Source Code
   subroutine get_aspect_one()
      type(StringVector) :: aspect_names
      type(MockItemSpec) :: spec, goal
      spec = MockItemSpec(name='1')
      goal = MockItemSpec(name='0')
      aspect_names = spec%get_aspect_order(goal)
      associate ( expected => aspect_names%size() ) ! returns INT64
        @assert_that(int(expected), is(1))
      end associate
      @assertEqual(aspect_names%of(1), 'a1')
   end subroutine get_aspect_one
Call graph
get_aspect_one calls assert_that, assertequal, get_aspect_order, of