get_export_coupler – MAPL
get_export_coupler Function
11 statements
Source File
private function get_export_coupler(this, actual_pt, rc) result(coupler)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Return Value type(GriddedComponentDriver), pointer
Calls
Called by
Source Code
   function get_export_coupler(this, actual_pt, rc) result(coupler)
      type(GriddedComponentDriver), pointer :: coupler
      class(HierarchicalRegistry), target, intent(in) :: this
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      coupler => this%export_couplers%at(actual_pt, _RC)
      _RETURN(_SUCCESS)
   end function get_export_coupler
Call graph
get_export_coupler calls at, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
map_find calls map_s_find
connect_sibling calls get_export_coupler
connect calls connect_sibling