get_vertical_dim_spec_names_bundle_info – MAPL
get_vertical_dim_spec_names_bundle_info Function
16 statements
Source File
public function get_vertical_dim_spec_names_bundle_info(info, rc) result(names)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info(:)
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Called by
Source Code
   function get_vertical_dim_spec_names_bundle_info(info, rc) result(names)
      type(StringVector) :: names
      type(ESMF_Info), intent(in) :: info(:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      character(len=:), allocatable :: spec_name
      names = StringVector()
      do i=1, size(info)
         spec_name = get_vertical_dim_spec_info(info(i), _RC)
         if(find_index(names, spec_name) == 0) call names%push_back(spec_name)
      end do
      _RETURN(_SUCCESS)
   end function get_vertical_dim_spec_names_bundle_info
Call graph
get_vertical_dim_spec_names_bundle_info calls ESMF_InfoGet, ESMF_InfoIsPresent, begin, mapl_assert, next, of, mapl_return, mapl_verify, push_back, stringvector
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_get_vertical_dim_spec_names calls get_vertical_dim_spec_names_bundle_info