get_ungridded_dims_bundle_info – MAPL
get_ungridded_dims_bundle_info Function
15 statements
Source File
public function get_ungridded_dims_bundle_info(info, rc) result(vec)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info(:)
integer, intent(out), optional :: rc
Return Value type(UngriddedDimVector)
Calls
Called by
Source Code
   function get_ungridded_dims_bundle_info(info, rc) result(vec)
      type(UngriddedDimVector) :: vec
      type(ESMF_Info), intent(in) :: info(:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      type(UngriddedDims) :: dims
      do i=1, size(info)
         dims = make_ungriddedDims(info(i), key=KEY_UNGRIDDED_DIMS, _RC)
         call merge_ungridded_dims(vec, dims, rc)
      end do
      _RETURN(_SUCCESS)
   end function get_ungridded_dims_bundle_info
Call graph
get_ungridded_dims_bundle_info calls mapl_assert, ftn_begin, ftn_end, get_ith_dim_spec, get_name, get_num_ungridded, next, of, push_back, make_ungriddeddims, mapl_return, mapl_verify
make_ungriddeddims calls mapl_return, mapl_verify, ESMF_InfoCreate, ESMF_InfoDestroy, mapl_infoget, make_dim_key, make_ungriddeddim
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_dim_key calls mapl_assert, mapl_return
make_ungriddeddim calls mapl_return, mapl_verify, mapl_infoget
test_get_ungridded_dims calls get_ungridded_dims_bundle_info