get_esmf_name – MAPL
get_esmf_name Function
6 statements
Source File
private function get_esmf_name(this) result(name)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_esmf_name(this) result(name)
      character(:), allocatable :: name
      class(ActualConnectionPt), intent(in) :: this
      name = this%v_pt%get_esmf_name()
      if (this%is_extension()) &
           name = name // this%get_extension_string()
   end function get_esmf_name
Call graph
get_esmf_name calls get_esmf_name, get_extension_string, is_extension
get_extension_string calls is_extension
add_to_state calls get_esmf_name
test_vertical calls add_to_state