get_esmf_name – MAPL
get_esmf_name Function
5 statements
Source File
private function get_esmf_name(this) result(name)
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_esmf_name(this) result(name)
      character(:), allocatable :: name
      class(VirtualConnectionPt), intent(in) :: this
      name = this%short_name
   end function get_esmf_name
Call graph
connect calls get_esmf_name, connect_sibling
connect_sibling calls get_esmf_name
get_esmf_name calls get_esmf_name
test_alt_constructor calls get_esmf_name
test_get_intent calls get_esmf_name
add_to_state calls get_esmf_name
test_vertical calls add_to_state