get_second_datetime – MAPL
get_second_datetime Function
4 statements
Source File
public function get_second_datetime(self)
Type Bound
ISO8601DateTime
Arguments
Type Intent Optional Attributes Name
class(ISO8601DateTime), intent(in) :: self
Return Value integer
Calls
Called by
Source Code
   integer function get_second_datetime(self)
      class(ISO8601DateTime), intent(in) :: self
      get_second_datetime = self%time_%get_second()
   end function get_second_datetime
Call graph
get_second_datetime calls get_second
convert_iso8601_to_esmf_time calls get_second_datetime
test_construct_iso8601datetime calls get_second_datetime
test_iso8601datetime_getters calls get_second_datetime