get_coupler_meta – MAPL
get_coupler_meta Function
19 statements
Source File
public function get_coupler_meta(gridcomp, rc) result(meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Return Value type(CouplerMetaComponent), pointer
Calls
Called by
Source Code
   function get_coupler_meta(gridcomp, rc) result(meta)
      type(CouplerMetaComponent), pointer :: meta
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      !TODO: This block is a workaround for weird link error with NAG
      !      7.2 Appears to be a collision in numbering of local
      !      scopes.
      block
      end block
      _GET_NAMED_PRIVATE_STATE(gridcomp, CouplerMetaComponent, COUPLER_META_PRIVATE_STATE, meta)
      _RETURN(_SUCCESS)
   end function get_coupler_meta
Call graph
get_coupler_meta calls mapl_assert, mapl_usercompgetinternalstate, mapl_return
mapl_return calls at, insert, mapl_throw_exception
make_coupler calls get_coupler_meta
test_propagate_geom calls make_coupler
test_propagate_interp_weights calls make_coupler
test_propagate_shared_attrs calls make_coupler