get_subregistry_comp – MAPL
get_subregistry_comp Function
25 statements
Source File
private function get_subregistry_comp(this, comp_name, rc) result(subregistry)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
character(len=*), intent(in) :: comp_name
integer, intent(out), optional :: rc
Return Value type(HierarchicalRegistry), pointer
Calls
Called by
Source Code
   function get_subregistry_comp(this, comp_name, rc) result(subregistry)
      type(HierarchicalRegistry), pointer :: subregistry
      class(HierarchicalRegistry), target, intent(in) :: this
      character(len=*), intent(in) :: comp_name
      integer, optional, intent(out) :: rc
      type(RegistryPtr), pointer :: wrap
      integer :: status
      subregistry => null()
      if (comp_name == this%get_name() .or. comp_name == SELF) then
         subregistry => this
         _RETURN(_SUCCESS)
      end if
      wrap => this%subregistries%at(comp_name,_RC)
      _ASSERT(associated(wrap%registry), 'null pointer encountered for subregistry.')
      select type (q => wrap%registry)
      type is (HierarchicalRegistry)
         subregistry => q
         _RETURN(_SUCCESS)
      class default
         _FAIL('Illegal subtype of AbstractRegistry encountered.')
      end select
   end function get_subregistry_comp
Call graph
get_subregistry_comp calls mapl_assert, at, get_name, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_find calls map_s_find
connect calls get_subregistry
get_subregistry_conn calls get_subregistry
propagate_exports_all calls get_subregistry
propagate_unsatisfied_imports_all calls get_subregistry
test_get_subregistry calls get_subregistry
test_get_subregistry_fail_not_found calls get_subregistry