get_accumulator_transform – MAPL
get_accumulator_transform Subroutine
27 statements
Source File
public subroutine get_accumulator_transform(accumulation_type, typekind, transform, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: accumulation_type
type(ESMF_TypeKind_Flag), intent(in) :: typekind
class(ExtensionTransform), intent(out), allocatable :: transform
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine get_accumulator_transform(accumulation_type, typekind, transform, rc)
      character(len=*), intent(in) :: accumulation_type
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      class(ExtensionTransform), allocatable, intent(out) :: transform
      integer, optional, intent(out) :: rc
      integer :: status
      allocate(transform, source=NullTransform())
      if(typekind /= ESMF_TYPEKIND_R4) then
         _FAIL('Unsupported typekind')
      end if
      select case(accumulation_type)
      case (SIMPLE_ACCUMULATION)
         allocate(transform, source=AccumulatorTransform(typekind))
      case (MEAN_ACCUMULATION)
         allocate(transform, source=MeanTransform(typekind))
      case (MAX_ACCUMULATION)
         allocate(transform, source=MaxTransform(typekind))
      case (MIN_ACCUMULATION)
         allocate(transform, source=MinTransform(typekind))
      case (INSTANTANEOUS)
         _FAIL('No AccumulatorTransform for instantaneous.')
      case default
         _FAIL('Unsupported AccumulatorTransform')
      end select
      _RETURN(_SUCCESS)
   end subroutine get_accumulator_transform
Call graph
get_accumulator_transform calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception