get_dimensions – MAPL
get_dimensions Function
5 statements
Source File
private function get_dimensions(this) result(dimensions)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(in), target :: this
Return Value type(StringIntegerMap), pointer
Calls
Called by
Source Code
   function get_dimensions(this) result(dimensions)
      type (StringIntegerMap), pointer :: dimensions
      class (FileMetadataUtils), target, intent(in) :: this
      dimensions => this%metadata%get_dimensions()
   end function get_dimensions
Call graph
get_dimensions calls get_dimensions
find_ calls get_dimensions
iobundle_add_entry calls get_dimensions
create_bracketing_fields calls find_
create_primary_field calls find_
detect_metadata calls find_
make_metadata calls find_
makemetadata calls find_
mapl_create_bundle_from_metdata_id calls find_
mapl_read_bundle calls find_, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find_
run_ calls iobundle_add_entry, create_bracketing_fields, mapl_extdatagetfstarttime, mapl_extdataprefetch, updatebrackettime
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls create_primary_field, fillin_primary, makemetadata, getclimyear, getlevs
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
get_file_bracket calls get_time_on_file
regrid_util calls main