get_expression_variables – MAPL
get_expression_variables Function
17 statements
Source File
public function get_expression_variables(expression, rc) result(variables)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: expression
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Called by
Source Code
   function get_expression_variables(expression, rc) result(variables)
      type(StringVector) :: variables
      character(len=*), intent(in) :: expression
      integer, optional, intent(out) :: rc
      integer :: status
      type(StringVector) :: raw_vars
      type(StringVectorIterator) :: iter
      raw_vars = parser_variables_in_expression(expression, _RC)
      iter = raw_vars%begin()
      do while(iter /= raw_vars%end())
        call variables%push_back(replace_delimiter(iter%of()))
        call iter%next()
      end do
      _RETURN(_SUCCESS)
   end function get_expression_variables
Call graph
get_expression_variables calls begin, next, of, mapl_return, mapl_verify, parser_variables_in_expression, replace_delimiter, push_back
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parser_variables_in_expression calls mapl_return, push_back, mapl_assert, lowcase, realnum
test_get_expression_variables calls get_expression_variables