get_year_datetime – MAPL
get_year_datetime Function
4 statements
Source File
public function get_year_datetime(self)
Type Bound
ISO8601DateTime
Arguments
Type Intent Optional Attributes Name
class(ISO8601DateTime), intent(in) :: self
Return Value integer
Calls
Called by
Source Code
   integer function get_year_datetime(self)
      class(ISO8601DateTime), intent(in) :: self
      get_year_datetime= self%date_%get_year()
   end function get_year_datetime
Call graph
get_year_datetime calls get_year
convert_iso8601_to_esmf_time calls get_year_datetime
test_construct_iso8601datetime calls get_year_datetime
test_iso8601datetime_getters calls get_year_datetime