get_num_levels – MAPL
get_num_levels Function
5 statements
Source File
private function get_num_levels(this) result(num_levels)
Type Bound
VerticalGeom
Arguments
Type Intent Optional Attributes Name
class(VerticalGeom), intent(in) :: this
Return Value integer
Called by
Call graph
get_vertical_bounds calls get_num_levels
get_ungridded_bounds calls get_vertical_bounds
allocate calls get_ungridded_bounds