get_month_datetime – MAPL
get_month_datetime Function
4 statements
Source File
public function get_month_datetime(self)
Type Bound
ISO8601DateTime
Arguments
Type Intent Optional Attributes Name
class(ISO8601DateTime), intent(in) :: self
Return Value integer
Calls
Called by
Source Code
   integer function get_month_datetime(self)
      class(ISO8601DateTime), intent(in) :: self
      get_month_datetime = self%date_%get_month()
   end function get_month_datetime
Call graph
get_month_datetime calls get_month
convert_iso8601_to_esmf_time calls get_month_datetime
test_construct_iso8601datetime calls get_month_datetime
test_iso8601datetime_getters calls get_month_datetime