get_coordinate_variable – MAPL
get_coordinate_variable Function
13 statements
Source File
private function get_coordinate_variable(this, var_name, unusable, rc) result(var)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(in), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(CoordinateVariable), pointer
Calls
Called by
Source Code
   function get_coordinate_variable(this, var_name, unusable, rc) result(var)
      class (CoordinateVariable), pointer :: var
      class (FileMetadataUtils), target, intent(in) :: this
      character(len=*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      var => this%metadata%get_coordinate_variable(var_name, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function get_coordinate_variable
Call graph
get_coordinate_variable calls get_coordinate_variable, mapl_return, mapl_verify, mapl_assert, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
map_at_rc calls map_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_coordinate_info calls get_coordinate_variable
get_level_name calls get_coordinate_variable
get_time_info calls get_coordinate_variable, get_coordinate_info
create_grid calls get_level_name
detect_metadata calls get_time_info
get_file_levels calls get_coordinate_info, get_level_name
get_file_times calls get_time_info
get_time_on_file calls get_time_info
getclimyear calls get_time_info
getlevs calls get_coordinate_info, get_level_name
initialize_ calls get_coordinate_info, getclimyear, getlevs
mapl_create_bundle_from_metdata_id calls get_level_name
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info, mapl_create_bundle_from_metdata_id
run_component_driver calls get_time_info
updatebrackettime calls get_time_info
time_ave calls get_coordinate_info, get_level_name, get_file_levels, get_file_times, mapl_read_bundle
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
fillin_primary calls detect_metadata
get_file_bracket calls get_time_on_file
main calls get_file_levels, get_file_times, mapl_read_bundle, run_component_driver
process_command_line calls create_grid
run_ calls mapl_extdatagetfstarttime, updatebrackettime
ut_regridding calls mapl_read_bundle