get_gridcomp – MAPL
get_gridcomp Function
6 statements
Source File
private function get_gridcomp(this) result(gridcomp)
Uses
ESMF
Type Bound
GriddedComponentDriver
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriver), intent(in) :: this
Return Value type(ESMF_GridComp)
Called by
Source Code
   function get_gridcomp(this) result(gridcomp)
      use esmf, only: ESMF_GridComp
      type(ESMF_GridComp) :: gridcomp
      class(GriddedComponentDriver), intent(in) :: this
      gridcomp = this%gridcomp
   end function get_gridcomp
Call graph
apply_to_children_custom calls get_gridcomp
free_outer_meta calls get_gridcomp
get_child_user_states calls get_gridcomp
get_substates calls get_gridcomp, get_substates
set_entry_point calls get_gridcomp
setservices_ calls get_gridcomp, setservices_
setup calls get_gridcomp
test_child_user_items_created calls get_gridcomp
apply_to_children calls apply_to_children_custom
gridcomp_set_entry_point calls set_entry_point
test_anything calls get_substates
test_child_outer_items_created calls get_child_user_states
test_finalize_children calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
create_grid_comp_primary calls setservices_
initialize_advertise calls apply_to_children
initialize_geom calls apply_to_children
create_grid_comp calls create_grid_comp_primary
initialize calls initialize_advertise, initialize_geom
setservices calls mapl_gridcompsetentrypoint