get_subconfig – MAPL
get_subconfig Function
19 statements
Source File
public function get_subconfig(hconfig, keystring, rc) result(subconfig)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
character(len=*), intent(in) :: keystring
integer, intent(out), optional :: rc
Return Value type(ESMF_HConfig)
Calls
Called by
Source Code
   function get_subconfig(hconfig, keyString, rc) result(subconfig)
      type(ESMF_HConfig) :: subconfig
      type(ESMF_HConfig), intent(in) :: hconfig
      character(*), intent(in) :: keystring
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: has_key
      logical :: is_map
      has_key = ESMF_HConfigIsDefined(hconfig, keyString=keyString, _RC)
      _ASSERT(has_key, 'Hconfig is expected to have '//keyString//' but does not.')
      is_map = ESMF_HConfigIsMap(hconfig, keyString=keyString, _RC)
      _ASSERT(is_map, 'HConfig expected a YAML mapping for '//keyString//'but does not.')
      subconfig = ESMF_HConfigCreateAt(hconfig, keyString=keystring, _RC)
      _RETURN(_SUCCESS)
   end function get_subconfig
Call graph
get_subconfig calls esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_child_hconfig calls get_subconfig
setservices calls make_child_hconfig, setservices
test_make_child_hconfig calls make_child_hconfig