get_dimensions – MAPL
get_dimensions Function
5 statements
Source File
private function get_dimensions(this) result(dimensions)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
Return Value type(StringIntegerMap), pointer
Called by
Source Code
   function get_dimensions(this) result(dimensions)
      type (StringIntegerMap), pointer :: dimensions
      class (FileMetadata), target, intent(in) :: this
      dimensions => this%dimensions
   end function get_dimensions
Call graph
def_dimensions calls get_dimensions
get_dimensions calls get_dimensions
init calls get_dimensions
inq_dimensions calls get_dimensions
mapl_iochangeres calls get_dimensions
mapl_iocountlevels calls get_dimensions
mapl_iocountnondimvars calls get_dimensions
mapl_iogetnondimvars calls get_dimensions
merge calls get_dimensions
test_get_dimensions calls get_dimensions
transfer_metadata calls get_dimensions
find_ calls get_dimensions
iobundle_add_entry calls get_dimensions
read calls inq_dimensions
write calls def_dimensions
main calls transfer_metadata, init
create_bracketing_fields calls find_
create_primary_field calls find_
detect_metadata calls find_
make_metadata calls find_
makemetadata calls find_
mapl_create_bundle_from_metdata_id calls find_
mapl_read_bundle calls find_
request_data_from_file calls find_
run_ calls iobundle_add_entry