get_outer_meta_from_inner_gc – MAPL
get_outer_meta_from_inner_gc Function
13 statements
Source File
public function get_outer_meta_from_inner_gc(gridcomp, rc) result(outer_meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Return Value type(OuterMetaComponent), pointer
Calls
Called by
Source Code
   function get_outer_meta_from_inner_gc(gridcomp, rc) result(outer_meta)
      type(OuterMetaComponent), pointer :: outer_meta
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_GridComp) :: outer_gc
      outer_gc = get_outer_gridcomp(gridcomp, _RC)
      outer_meta => get_outer_meta(outer_gc, _RC)
      _RETURN(_SUCCESS)
   end function get_outer_meta_from_inner_gc
Call graph
get_outer_meta_from_inner_gc calls get_outer_meta, get_outer_gridcomp, mapl_return, mapl_verify
get_outer_meta calls get_outer_meta_from_outer_gc
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridcompisuser calls gridcomp_is_user
get_error_message calls at, insert
get_inner_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
get_outer_meta_from_outer_gc calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_throw_exception calls initialize
gridcomp_is_user calls mapl_return, mapl_verify, mapl_gridcompisgeneric
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
run calls get_outer_meta_from_inner_gc
setservices calls get_outer_meta_from_inner_gc, setservices