get_value_logical – MAPL
get_value_logical Subroutine
52 statements
Source File
private subroutine get_value_logical(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
logical, intent(inout) :: value
logical, intent(in), optional :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_value_logical(params, value, default, valuestring, rc)
      logical, intent(inout) :: value
      logical, optional, intent(in) :: default
      character(len=*), parameter :: typestring = 'L'
      character(len=*), parameter :: edit_descriptor = EDIT_DESC_L
#include "hconfig_get_value_template.h"
   end subroutine get_value_logical
Call graph
get_value_logical calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value calls get_value_logical