get_var_attr_real64 – MAPL
get_var_attr_real64 Function
31 statements
Source File
private function get_var_attr_real64(this, var_name, attr_name, rc) result(attr_real64)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value real(kind=REAL64)
Calls
Source Code
   function get_var_attr_real64(this,var_name,attr_name,rc) result(attr_real64)
      real(REAL64) :: attr_real64
      class(FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      real(REAL64) :: tmp(1)
      integer :: status
      character(:), allocatable :: fname
      type(Attribute), pointer :: attr
      type(Variable), pointer :: var
      class(*), pointer :: attr_val(:)
      fname = this%get_file_name(_RC)
      var => this%get_variable(var_name,_RC)
      _ASSERT(associated(var),"no variable named "//var_name//" in "//fname)
      attr => var%get_attribute(attr_name,_RC)
      _ASSERT(associated(attr),"no attribute named "//attr_name//" in "//var_name//" in "//fname)
      attr_val => attr%get_values()
      select type(attr_val)
      type is(real(kind=REAL64))
         tmp = attr_val
         attr_real64 = tmp(1)
      class default
         _FAIL('unsupported subclass (not real64) for units of attribute named '//attr_name//' in '//var_name//' in '//fname)
      end select
      _RETURN(_SUCCESS)
   end function get_var_attr_real64
Call graph
get_var_attr_real64 calls mapl_assert, get_attribute, get_file_name, get_values, get_variable, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_file_name calls mapl_return
get_values calls mapl_return
get_variable calls mapl_return, mapl_verify, get_variable, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find