get_routehandle – MAPL
get_routehandle Function
21 statements
Source File
public function get_routehandle(this, spec, rc) result(routehandle)
Type Bound
RoutehandleManager
Arguments
Type Intent Optional Attributes Name
class(RoutehandleManager), intent(inout), target :: this
type(RoutehandleSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(ESMF_RouteHandle)
Calls
Called by
Source Code
   function get_routehandle(this, spec, rc) result(routehandle)
      type(ESMF_Routehandle) :: routehandle
      class(RoutehandleManager), target, intent(inout) :: this
      type(RoutehandleSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      associate (b => this%specs%begin(), e => this%specs%end())
        associate ( iter => find(b, e, spec))
          if (iter /= this%specs%end()) then
             routehandle = this%routehandles%of(iter - this%specs%begin() + 1)
             _RETURN(_SUCCESS)
          end if
        end associate
      end associate
      call this%add_routehandle(spec, _RC)
      routehandle = this%routehandles%back()
      _RETURN(_SUCCESS)
   end function get_routehandle
Call graph
get_routehandle calls find, of, add_routehandle, mapl_return, mapl_verify, vector_back, vector_begin
add_routehandle calls find, mapl_return, mapl_verify, vector_begin, make_routehandle, mapl_assert, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_routehandle calls make_routehandle_from_param
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to
make_routehandle_from_param calls mapl_return, mapl_verify, ESMF_FieldRegridStore, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
vector_grow_to calls vector_capacity, vector_set_capacity
make_regridder_typesafe calls get_routehandle
make_regridder calls make_regridder
get_regridder calls make_regridder