get_logger_root – MAPL
get_logger_root Function
8 statements
Source File
private function get_logger_root(this, rc) result(lgr)
Type Bound
LoggerManager
Arguments
Type Intent Optional Attributes Name
class(LoggerManager), intent(inout), target :: this
integer, intent(out), optional :: rc
Return Value class(Logger), pointer
Called by
Source Code
   function get_logger_root(this, rc) result(lgr)
      class (Logger), pointer :: lgr
      class (LoggerManager), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      lgr => this%log_
      _RETURN(_SUCCESS)
   end function get_logger_root
Call graph
addchild_preamble calls get_logger
addchildfromdsometa calls get_logger
addchildfrommeta calls get_logger
append_file calls get_logger
checkunused calls get_logger
create_file_handle calls get_logger
create_geosat_grid_find_mask calls get_logger
create_grid calls get_logger
getnodecomm calls get_logger
getnoderootscomm calls get_logger
historytrajectory_from_config calls get_logger
init_meta calls get_logger
initialize_from_config_with_prefix calls get_logger
initialize_pflogger calls get_logger
mapl_genericfinalize calls get_logger
mapl_genericstateset calls get_logger
mapl_genericwrapper calls get_logger
mapl_sungetsolarconstantfromnrlfile calls get_logger
mapl_varspecaddreffromitem calls get_logger
mapl_varspecaddreffromitemnew calls get_logger
mapl_varspecprint1csv calls get_logger
new_stationsampler_readfile calls get_logger
read_m_files_4_swath calls get_logger
regen_rcx_for_obs_platform calls get_logger
report_global_profiler calls get_logger
run calls get_logger
run_model calls get_logger
set calls get_logger
start_back calls get_logger
verify_epoch_equals_freq calls get_logger