get_lon_subset – MAPL
get_lon_subset Module Function
19 statements
Source File
pure module function get_lon_subset(this, axis, rank) result(local_axis) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonDecomposition), intent(in) :: this
type(LonAxis), intent(in) :: axis
integer, intent(in) :: rank
Return Value type(LonAxis)
Calls
Called by
Source Code
   pure module function get_lon_subset(this, axis, rank) result(local_axis)
      type(LonAxis) :: local_axis
      class(LatLonDecomposition), intent(in) :: this
      type(LonAxis), intent(in) :: axis
      integer, intent(in) :: rank
      real(kind=R8), allocatable :: centers(:)
      real(kind=R8), allocatable :: corners(:)
      integer :: i_0, i_1, i_n
      call get_idx_range(this%lon_distribution, rank, i_0, i_1)
      i_n = i_1 ! unless
      associate (nx => size(this%get_lon_distribution()))
        if (.not. axis%is_periodic() .and. (1+rank == nx)) then
           i_n = i_n + 1
        end if
      end associate
      centers = get_subset(axis%get_centers(), i_0, i_1)
      corners = get_subset(axis%get_corners(), i_0, i_n)
      local_axis = LonAxis(centers, corners)
   end function get_lon_subset
Call graph
get_lon_subset calls get_centers, get_corners, get_lon_distribution, is_periodic, get_idx_range, get_subset, get_lon_subset
get_centers calls get_centers
get_corners calls get_corners
get_lon_distribution calls get_lon_distribution
is_periodic calls is_periodic
fill_coordinates calls get_lon_subset, fill_coordinates
typesafe_make_geom calls fill_coordinates