get_outer_gridcomp – MAPL
get_outer_gridcomp Function
15 statements
Source File
private function get_outer_gridcomp(gridcomp, rc) result(outer_gc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Return Value type(ESMF_GridComp)
Calls
Called by
Source Code
   type(ESMF_GridComp) function get_outer_gridcomp(gridcomp, rc) result(outer_gc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(InnerMetaComponent), pointer :: inner_meta
      logical :: is_user_gridcomp
      is_user_gridcomp =  MAPL_GridCompIsUser(gridcomp, _RC)
      _ASSERT(is_user_gridcomp, 'gridcomp argument must be a user gridcomp')
      inner_meta => get_inner_meta(gridcomp, _RC)
      outer_gc = inner_meta%get_outer_gridcomp()
      _RETURN(_SUCCESS)
   end function get_outer_gridcomp
Call graph
get_outer_gridcomp calls mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridcompisuser calls gridcomp_is_user
get_inner_meta calls mapl_assert, mapl_return, mapl_usercompgetinternalstate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_is_user calls mapl_return, mapl_verify, mapl_gridcompisgeneric
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_meta_from_inner_gc calls get_outer_gridcomp
gridcomp_get_outer_meta calls get_outer_gridcomp, mapl_gridcompgetoutermeta
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
run calls get_outer_meta_from_inner_gc
setservices calls get_outer_meta_from_inner_gc, setservices
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta
mapl_addchild calls add_child_by_name
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic
mapl_connectall calls gridcomp_connect_all
mapl_gridcompget calls gridcomp_get
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
mapl_runchild calls run_child_by_name
mapl_runchildren calls run_children
setup calls mapl_gridcompsetverticalgeom
test_full_run_sequence calls mapl_gridcompsetverticalgeom