get_coordinate_variable – MAPL
get_coordinate_variable Function
24 statements
Source File
private function get_coordinate_variable(this, var_name, unusable, rc) result(var)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(CoordinateVariable), pointer
Calls
Called by
Source Code
   function get_coordinate_variable(this, var_name, unusable, rc) result(var)
      class (CoordinateVariable), pointer :: var
      class (FileMetadata), target, intent(in) :: this
      character(len=*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class (Variable), pointer :: tmp
      integer :: status
      tmp => this%variables%at(var_name, _RC)
      _ASSERT(associated(tmp),'can not find '//trim(var_name))
      select type (tmp)
      class is (CoordinateVariable)
         var => tmp
      class default
         var => null()
      end select
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function get_coordinate_variable
Call graph
get_coordinate_variable calls mapl_assert, at, mapl_return, mapl_verify, get_coordinate_variable
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_find calls map_s_find
check_flip calls get_coordinate_variable
get_coordinates_dim calls get_coordinate_variable, get_coordinates_dim
initialize_from_file_metadata calls get_coordinate_variable
mapl_iochangeres calls get_coordinate_variable
write_coordinate_variables calls get_coordinate_variable
get_coordinate_info calls get_coordinate_variable
get_level_name calls get_coordinate_variable
get_time_info calls get_coordinate_variable, get_coordinate_info
mapl_bundlereadncpar calls check_flip
write calls write_coordinate_variables
get_coordinates calls get_coordinates_dim
mapl_varreadncpar calls mapl_bundlereadncpar
create_grid calls get_level_name
detect_metadata calls get_time_info
get_file_levels calls get_coordinate_info, get_level_name
get_file_times calls get_time_info
get_time_on_file calls get_time_info
getclimyear calls get_time_info
getlevs calls get_coordinate_info, get_level_name
initialize_ calls get_coordinate_info
mapl_create_bundle_from_metdata_id calls get_level_name
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info
run_component_driver calls get_time_info
updatebrackettime calls get_time_info
time_ave calls get_coordinate_info, get_level_name