get_RequestHandle – MAPL
get_RequestHandle Function
12 statements
Source File
private function get_RequestHandle(this, request_id, rc) result(rh_ptr)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(in), target :: this
integer, intent(in) :: request_id
integer, intent(out), optional :: rc
Return Value class(AbstractRequestHandle), pointer
Calls
Called by
Source Code
   function get_RequestHandle(this,request_id, rc) result(rh_ptr)
      class (BaseThread), target, intent(in) :: this
      integer, intent(in) :: request_id
      integer, optional, intent(out) :: rc
      class(AbstractRequestHandle), pointer :: rh_ptr
      type (IntegerRequestMapIterator) :: iter
      iter = this%open_requests%find(request_id)
      _ASSERT( iter /= this%open_requests%end(), "could not find the request handle id")
      rh_Ptr => iter%second()
      _RETURN(_SUCCESS)
   end function get_RequestHandle
Call graph
get_requesthandle calls mapl_assert, map_find, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
map_find calls map_s_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
handle_done_stage calls get_requesthandle
put calls get_requesthandle
receive_output_data calls get_requesthandle, receive_output_data
wait calls get_requesthandle
start calls receive_output_data