get_corners – MAPL
get_corners Module Function
5 statements
Source File
pure module function get_corners(this) result(corners) Interface →
Arguments
Type Intent Optional Attributes Name
class(CoordinateAxis), intent(in) :: this
Return Value real(kind=R8), allocatable, (:)
Called by
Source Code
   pure module function get_corners(this) result(corners)
      real(kind=R8), allocatable :: corners(:)
      class(CoordinateAxis), intent(in) :: this
      corners = this%corners
   end function get_corners
Call graph
get_corners calls get_corners
fill_coordinates calls get_corners, get_lat_subset, get_lon_subset, fill_coordinates
get_lat_subset calls get_corners, get_lat_subset
get_lon_subset calls get_corners, get_lon_subset
typesafe_make_geom calls fill_coordinates