get_child_user_states – MAPL
get_child_user_states Subroutine
23 statements
Source File
public subroutine get_child_user_states(states, outer_meta, child_name, rc)
Uses
mapl3g_GriddedComponentDriver
Arguments
Type Intent Optional Attributes Name
type(MultiState), intent(out) :: states
type(OuterMetaComponent), intent(in), target :: outer_meta
character(len=*), intent(in) :: child_name
integer, intent(out) :: rc
Calls
Called by
Source Code
   subroutine get_child_user_states(states, outer_meta, child_name, rc)
      use mapl3g_GriddedComponentDriver
      type(MultiState), intent(out) :: states
      type(OuterMetaComponent), target, intent(in) :: outer_meta
      character(*), intent(in) :: child_name
      integer, intent(out) :: rc
      integer :: status
      type(GriddedComponentDriver) :: child_comp
      type(ESMF_GridComp) :: child_gc
      type(OuterMetaComponent), pointer :: child_meta
      type(GriddedComponentDriver), pointer :: user_component
      rc = +1
      child_comp = outer_meta%get_child(child_name, rc=status)
      if (status /= 0) then
         rc = +2
         return
      end if
      child_gc = child_comp%get_gridcomp()
      child_meta => get_outer_meta(child_gc, rc=status)
      user_component => child_meta%get_user_gc_driver()
      states = user_component%get_states()
      rc = 0
   end subroutine get_child_user_states
Call graph
get_child_user_states calls get_outer_meta, get_child, get_gridcomp, get_states, get_user_gc_driver
test_child_outer_items_created calls get_child_user_states