get_accumulator_action – MAPL
get_accumulator_action Subroutine
25 statements
Source File
public subroutine get_accumulator_action(accumulation_type, typekind, action, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: accumulation_type
type(ESMF_TypeKind_Flag), intent(in) :: typekind
class(ExtensionAction), intent(out), allocatable :: action
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine get_accumulator_action(accumulation_type, typekind, action, rc)
      character(len=*), intent(in) :: accumulation_type
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      class(ExtensionAction), allocatable, intent(out) :: action
      integer, optional, intent(out) :: rc
      integer :: status
      if(typekind /= ESMF_TYPEKIND_R4) then
         _FAIL('Unsupported typekind')
      end if
      _ASSERT(accumulation_type_is_valid(accumulation_type), 'Unsupported AccumulatorAction')
      select case(accumulation_type)
      case (SIMPLE_ACCUMULATION)
         action = AccumulatorAction(typekind)
      case (MEAN_ACCUMULATION)
         action = MeanAction(typekind)
      case (MAX_ACCUMULATION)
         action = MaxAction(typekind)
      case (MIN_ACCUMULATION)
         action = MinAction(typekind)
      case default
         _FAIL('Unsupported AccumulatorAction')
      end select
      _RETURN(_SUCCESS)
   end subroutine get_accumulator_action
Call graph
get_accumulator_action calls mapl_assert, accumulation_type_is_valid, mapl_return
mapl_return calls at, insert, mapl_throw_exception