get_cost_geom – MAPL
get_cost_geom Function
5 statements
Source File
private function get_cost_geom(a, b) result(cost)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in), allocatable :: a
type(ESMF_Geom), intent(in), allocatable :: b
Return Value integer
Calls
Called by
Source Code
   integer function get_cost_geom(a, b) result(cost)
      type(ESMF_GEOM), allocatable, intent(in) :: a, b
      cost = 0
      if (.not. match(a, b)) cost = 1
   end function get_cost_geom
Call graph
get_cost_geom calls match
match calls match_geom, match_string, match_typekind
match_geom calls mapl_samegeom
match_string calls mirror
mapl_samegeom calls same_geom
get_cost calls get_cost_geom
extension_cost calls get_cost, extension_cost