get_factory_id – MAPL
get_factory_id Function
19 statements
Source File
public function get_factory_id(grid, unusable, rc) result(id)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer(kind=ESMF_KIND_I8)
Calls
Called by
Source Code
   function get_factory_id(grid, unusable, rc) result(id)
      integer (kind=ESMF_KIND_I8) :: id
      type (ESMF_Grid) :: grid
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'get_factory_id'
      type(ESMF_Info) :: infoh
      _UNUSED_DUMMY(unusable)
      call ESMF_InfoGetFromHost(grid,infoh,rc=status)
      _VERIFY(status)
      call ESMF_InfoGet(infoh,factory_id_attribute,id,rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function get_factory_id
Call graph
get_factory_id calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
equals calls get_factory_id
less_than calls get_factory_id
make_regridder_ calls get_factory_id
make_regridder_from_grids calls get_factory_id
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
request_data_from_file calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
create_from_bundle calls createfilemetadata
initialize calls create_bundle_rh, createfilemetadata
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run calls create_bundle_rh, createfilemetadata