get_grid_type – MAPL
get_grid_type Subroutine
27 statements
Source File
private subroutine get_grid_type(this, unusable, grid_type_in, grid_type_out, rc)
Type Bound
RegridderSpec
Arguments
Type Intent Optional Attributes Name
class(RegridderSpec), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(out), optional :: grid_type_in
character(len=*), intent(out), optional :: grid_type_out
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine get_grid_type(this,unusable,grid_type_in, grid_type_out, rc)
      class (RegridderSpec), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(out) :: grid_type_in
      character(len=*), optional, intent(out) :: grid_type_out
      integer, optional, intent(out) :: rc
      type(ESMF_Info) :: infohin, infohout
      integer :: status
      _UNUSED_DUMMY(unusable)
      if (present(grid_type_in)) then
         call ESMF_InfoGetFromHost(this%grid_in,infohin,rc=status)
         _VERIFY(status)
         call ESMF_InfoGet(infohin,'GridType',grid_type_in,rc=status)
         _VERIFY(status)
      end if
      if (present(grid_type_out)) then
         call ESMF_InfoGetFromHost(this%grid_out,infohout,rc=status)
         _VERIFY(status)
         call ESMF_InfoGet(infohout,'GridType',grid_type_out,rc=status)
         _VERIFY(status)
      end if
      _RETURN(_SUCCESS)
   end subroutine get_grid_type
Call graph
get_grid_type calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize