get_mapl_geom – MAPL
get_mapl_geom Function
14 statements
Source File
public function get_mapl_geom(geom, rc) result(mapl_geom)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom
integer, intent(out), optional :: rc
Return Value type(MAPLGeom), pointer
Calls
Called by
Source Code
   function get_mapl_geom(geom, rc) result(mapl_geom)
      type(MAPLGeom), pointer :: mapl_geom
      type(ESMF_Geom), intent(in) :: geom
      integer, optional, intent(out) :: rc
      integer :: status, id
      type(GeomManager), pointer :: geom_mgr
      geom_mgr => get_geom_manager()
      id = MAPL_GeomGetId(geom, _RC)
      mapl_geom => geom_mgr%get_mapl_geom_from_id(id, _RC)
      _RETURN(_SUCCESS)
   end function get_mapl_geom
Call graph
get_mapl_geom calls get_geom_manager, get_mapl_geom_from_id, mapl_geomgetid, mapl_return, mapl_verify
mapl_geomgetid calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_variable calls get_mapl_geom
bundle_to_metadata calls get_mapl_geom, add_variables
add_variables calls add_variable