get_hour – MAPL
get_hour Function
4 statements
Source File
public function get_hour(self)
Type Bound
ISO8601Time
Arguments
Type Intent Optional Attributes Name
class(ISO8601Time), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_hour(self)
      class(ISO8601Time), intent(in) :: self
      get_hour = self%hour_
   end function get_hour
Call graph
convert_iso8601_to_integer_time calls get_hour
get_hour_datetime calls get_hour
test_construct_iso8601time calls get_hour
test_iso8601time_getters calls get_hour
convert_iso8601_to_esmf_time calls get_hour_datetime
test_construct_iso8601datetime calls get_hour_datetime
test_convert_iso8601_to_integer_time calls convert_iso8601_to_integer_time
test_iso8601datetime_getters calls get_hour_datetime