get_mask_routine_r4 – MAPL
get_mask_routine_r4 Function
21 statements
Source File
private function get_mask_routine_r4(mask_type, rc) result(mask_routine)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mask_type
integer, intent(out), optional :: rc
Return Value procedure(I_r4r8r4), pointer
Calls
Called by
Source Code
   function get_mask_routine_r4(mask_type, rc) result(mask_routine)
      procedure(I_r4r8r4), pointer :: mask_routine
      character(*), intent(in) :: mask_type
      integer, intent(out), optional :: rc
      integer :: status
      select case (mask_type)
      case ('missing_value')
         mask_routine => missing_r4r8r4v
      case ('monotonic')
         mask_routine => monotonic_r4r8r4v
      case ('vote')
         mask_routine => vote_r4r8r4v
      case ('fraction')
         mask_routine => fraction_r4r8r4v
      case default
         mask_routine => null()
         _FAIL("Unsupported mask type: "//mask_type)
      end select
      _RETURN(_SUCCESS)
   end function get_mask_routine_r4
Call graph
get_mask_routine_r4 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_dynamicmask_r4r8 calls get_mask_routine_r4
dynamicmask calls new_dynamicmask_r4r8