get_states – MAPL
get_states Module Function
5 statements
Source File
module function get_states(this) result(states) Interface →
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriver), intent(in) :: this
Return Value type(MultiState)
Called by
Source Code
   module function get_states(this) result(states)
      type(MultiState) :: states
      class(GriddedComponentDriver), intent(in) :: this
      states = this%states
   end function get_states
Call graph
get_states calls get_states
get_child_user_states calls get_states
get_internal_state calls get_states
get_substates calls get_states, get_substates
initialize_post_advertise calls get_states
test_child_user_items_created calls get_states
test_parent_user_items_created calls get_states
test_state_items_complete calls get_states
initialize calls initialize_post_advertise
test_anything calls get_substates
test_child_outer_items_created calls get_child_user_states