get_user_gc_driver – MAPL
get_user_gc_driver Function
5 statements
Source File
private function get_user_gc_driver(this) result(user_gc_driver)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(in), target :: this
Return Value type(GriddedComponentDriver), pointer
Called by
Source Code
   function get_user_gc_driver(this) result(user_gc_driver)
      type(GriddedComponentDriver), pointer :: user_gc_driver
      class(OuterMetaComponent), target, intent(in) :: this
      user_gc_driver => this%user_gc_driver
   end function get_user_gc_driver
Call graph
get_child_user_states calls get_user_gc_driver
get_substates calls get_user_gc_driver, get_substates
gridcomp_set_entry_point calls get_user_gc_driver
setup calls get_user_gc_driver
test_child_user_items_created calls get_user_gc_driver
test_parent_user_items_created calls get_user_gc_driver
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
test_anything calls get_substates
test_child_outer_items_created calls get_child_user_states
test_finalize_children calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
setservices calls mapl_gridcompsetentrypoint, setservices