get_v1d_netcdf_R8 – MAPL
get_v1d_netcdf_R8 Subroutine
31 statements
Source File
public subroutine get_v1d_netcdf_R8(filename, name, array, Xdim, group_name, rc)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: name
real(kind=REAL64), intent(out), dimension(Xdim) :: array
integer, intent(in) :: Xdim
character(len=*), intent(in), optional :: group_name
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine get_v1d_netcdf_R8(filename, name, array, Xdim, group_name, rc)
    use netcdf
    implicit none
    character(len=*), intent(in) :: name, filename
    character(len=*), optional, intent(in) :: group_name
    integer, intent(in) :: Xdim
    real(REAL64), dimension(Xdim), intent(out) :: array
    integer, optional, intent(out) :: rc
    integer :: status
    integer :: ncid, varid, ncid2
    call check_nc_status(nf90_open(trim(fileName), NF90_NOWRITE, ncid), _RC)
    if(present(group_name)) then
       ncid2= ncid
       call check_nc_status(nf90_inq_ncid(ncid2, group_name, ncid), _RC)
    end if
    call check_nc_status(nf90_inq_varid(ncid, name, varid), _RC)
    call check_nc_status(nf90_get_var(ncid, varid, array), _RC)
    if(present(group_name)) then
       call check_nc_status(nf90_close(ncid2), _RC)
    else
       call check_nc_status(nf90_close(ncid), _RC)
    end if
    _RETURN(_SUCCESS)
  end subroutine get_v1d_netcdf_R8
Call graph
get_v1d_netcdf_r8 calls nf90_close, nf90_get_var, nf90_inq_ncid, nf90_inq_varid, nf90_open, check_nc_status, mapl_return, mapl_verify
check_nc_status calls mapl_return, mapl_assert, nf90_strerror
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception