get_variable_dim_names – MAPL
get_variable_dim_names Function
26 statements
Source File
public function get_variable_dim_names(field, geom, rc) result(dim_names)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
type(ESMF_Geom), intent(in) :: geom
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_variable_dim_names(field, geom, rc) result(dim_names)
      character(len=:), allocatable :: dim_names
      type(ESMF_Field), intent(in) :: field
      type(ESMF_Geom), intent(in) :: geom
      integer, optional, intent(out) :: rc
      type(MAPLGeom), pointer :: mapl_geom
      type(StringVector) :: grid_variables
      type(ESMF_Geom) :: esmfgeom
      character(len=:), allocatable :: vert_dim_name, ungridded_names
      integer :: status
      call ESMF_FieldGet(field, geom=esmfgeom, _RC)
      mapl_geom => get_mapl_geom(esmfgeom, _RC)
      grid_variables = mapl_geom%get_gridded_dims()
      dim_names = string_vec_to_comma_sep(grid_variables)
      ! add vertical dimension
      vert_dim_name = get_vertical_dimension_name_from_field(field, _RC)
      if(vert_dim_name /= EMPTY) dim_names = dim_names // "," // vert_dim_name
      ! add any ungridded dimensions
      ungridded_names = ungridded_dim_names(field, _RC)
      if(ungridded_names /= EMPTY) dim_names = dim_names // ungridded_names
      ! add time dimension
      dim_names = dim_names // ",time"
      _RETURN(_SUCCESS)
   end function get_variable_dim_names
Call graph
get_variable_dim_names calls esmf_fieldget, get_gridded_dims, get_mapl_geom, get_vertical_dimension_name_from_field, mapl_return, mapl_verify, string_vec_to_comma_sep, ungridded_dim_names
get_mapl_geom calls mapl_return, mapl_verify, get_geom_manager, get_mapl_geom_from_id, mapl_geomgetid
get_vertical_dimension_name_from_field calls mapl_return, mapl_verify, mapl_fieldget, get_dimension_name
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_vec_to_comma_sep calls begin, next, of
ungridded_dim_names calls mapl_return, mapl_verify, mapl_fieldget, cat_ungridded_dim_names
cat_ungridded_dim_names calls get_name, get_ith_dim_spec, get_num_ungridded
mapl_geomgetid calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost
add_variable calls get_variable_dim_names
add_variables calls add_variable
bundle_to_metadata calls add_variables