get_var_attr_string – MAPL
get_var_attr_string Function
29 statements
Source File
private function get_var_attr_string(this, var_name, attr_name, rc) result(attr_string)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_var_attr_string(this,var_name,attr_name,rc) result(attr_string)
      character(len=:), allocatable :: attr_string
      class(FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: fname
      type(Attribute), pointer :: attr
      type(Variable), pointer :: var
      class(*), pointer :: attr_val
      fname = this%get_file_name(_RC)
      var => this%get_variable(var_name,_RC)
      _ASSERT(associated(var),"no variable named "//var_name//" in "//fname)
      attr => var%get_attribute(attr_name,_RC)
      _ASSERT(associated(attr),"no attribute named "//attr_name//" in "//var_name//" in "//fname)
      attr_val => attr%get_value()
      select type(attr_val)
      type is(character(*))
         attr_string = attr_val
      class default
         _FAIL('unsupported subclass (not string) for units of attribute named '//attr_name//' in '//var_name//' in '//fname)
      end select
      _RETURN(_SUCCESS)
   end function get_var_attr_string
Call graph
get_var_attr_string calls mapl_assert, get_attribute, get_file_name, get_value, get_variable, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_file_name calls mapl_return
get_value calls mapl_return
get_variable calls mapl_return, mapl_verify, get_variable, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
mapl_create_bundle_from_metdata_id calls get_var_attr_string
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main