get_lon_range – MAPL
get_lon_range Module Function
59 statements
Source File
module function get_lon_range(hconfig, im_world, rc) result(ranges) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(in) :: im_world
integer, intent(out), optional :: rc
Return Value type(AxisRanges)
Calls
Called by
Source Code
   module function get_lon_range(hconfig, im_world, rc) result(ranges)
      type(AxisRanges) :: ranges
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, intent(in) :: im_world
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=R8) :: delta
      character(:), allocatable :: dateline
      real(kind=ESMF_KIND_R4), allocatable :: t_range(:)
      logical :: has_range
      logical :: has_dateline
      has_range = ESMF_HConfigIsDefined(hconfig, keystring='lon_range', _RC)
      has_dateline = ESMF_HConfigIsDefined(hconfig, keystring='dateline', _RC)
      _ASSERT(has_range .neqv. has_dateline, 'Exactly one of lon_range or dateline must be defined in hconfig')
      if (has_range) then ! is regional
         t_range = ESMF_HConfigAsR4Seq(hconfig, keyString='lon_range', _RC)
         _ASSERT(size(t_range) == 2, 'illegal size of lon_range')
         _ASSERT(t_range(1) < t_range(2), 'illegal lon_range')
         delta = (t_range(2) - t_range(1)) / im_world
         ranges%corner_min = t_range(1)
         ranges%corner_max = t_range(2)
         ranges%center_min = t_range(1) + delta/2
         ranges%center_max = t_range(2) - delta/2
         _RETURN(_SUCCESS)
      end if
      delta = 360.d0 / im_world
      dateline = ESMF_HConfigAsString(hconfig, keyString='dateline', _RC)
      select case (dateline)
      case ('DC')
         ranges%corner_min = -180.d0 - delta/2
         ranges%corner_max = +180.d0 - delta/2
         ranges%center_min = -180
         ranges%center_max = +180 - delta
      case ('DE')
         ranges%corner_min = -180
         ranges%corner_max = +180
         ranges%center_min = -180 + delta/2
         ranges%center_max = +180 - delta/2
      case ('GC')
         ranges%corner_min = -delta/2
         ranges%corner_max = 360 - delta/2
         ranges%center_min = 0
         ranges%center_max = 360 - delta
      case ('GE')
         ranges%corner_min = 0
         ranges%corner_max = 360 - delta
         ranges%center_min = delta/2
         ranges%center_max = 360 - delta/2
      case default
         _FAIL("Illegal value for dateline: "//dateline)
      end select
      _RETURN(_SUCCESS)
   end function get_lon_range
Call graph
get_lon_range calls esmf_hconfigasr4seq, esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify, get_lon_range
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_lonaxis_from_hconfig calls get_lon_range, make_lonaxis_from_hconfig
test_get_lon_range_dc calls get_lon_range
test_get_lon_range_de calls get_lon_range
test_get_lon_range_gc calls get_lon_range
test_get_lon_range_ge calls get_lon_range
test_get_lon_range_regional calls get_lon_range
make_lonaxis calls make_lonaxis_from_hconfig