get_length – MAPL
get_length Function
4 statements
Source File
private function get_length(this) result(length)
Type Bound
ModifyMetadataMessage
Arguments
Type Intent Optional Attributes Name
class(ModifyMetadataMessage), intent(in) :: this
Return Value integer
Calls
Source Code
   integer function get_length(this) result(length)
      class (ModifyMetadataMessage), intent(in) :: this
      length = &
           & serialize_buffer_length(this%collection_id) + &
           & StringVariableMap_get_length(this%var_map)
   end function get_length
Call graph
get_length calls serialize_buffer_length, stringvariablemap_get_length
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
stringvariablemap_get_length calls stringvariablemap_serialize
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
stringvariablemap_serialize calls serialize_buffer_length, serialize_intrinsic, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, mapl_return, mapl_verify, serialize