get_phases – MAPL
get_phases Function
8 statements
Source File
private function get_phases(this, method_flag) result(phases)
Uses
ESMF
gFTL2_StringVector
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout), target :: this
type(ESMF_Method_Flag), intent(in) :: method_flag
Return Value type(StringVector), pointer
Calls
Called by
Source Code
   function get_phases(this, method_flag) result(phases)
      use :: esmf, only: ESMF_Method_Flag
      use :: gFTL2_StringVector, only: StringVector
      type(StringVector), pointer :: phases
      class(OuterMetaComponent), target, intent(inout):: this
      type(ESMF_Method_Flag), intent(in) :: method_flag
      phases => this%user_phases_map%of(method_flag)
   end function get_phases
Call graph
get_phases calls map_of
map_of calls insert, map_s_iter_of
map_s_iter_of calls map_s_get_value
map_s_insert_initializer_list calls insert
run_child_by_name calls get_phases, run_child
run_custom calls get_phases
run calls get_phases, run
setservices calls get_phases
finalize calls run_custom, finalize
initialize_advertise calls run_custom
initialize_geom calls run_custom
initialize_post_advertise calls run_custom
initialize_realize calls run_custom
initialize_user calls run_custom
initialize calls initialize_advertise, initialize_geom, initialize_post_advertise, initialize_realize, initialize_user
run_children_ calls run_child
test_finalize_children calls finalize
test_init_children calls initialize_user
mapl_runchild calls run_child_by_name