get_default_phase_name – MAPL
get_default_phase_name Function
19 statements
Source File
public function get_default_phase_name(method_flag, use_name) result(phase_name)
Uses
ESMF
Arguments
Type Intent Optional Attributes Name
type(ESMF_Method_Flag), intent(in) :: method_flag
character(len=*), intent(in), optional :: use_name
Return Value character(len=:), allocatable
Called by
Source Code
   function get_default_phase_name(method_flag, use_name) result(phase_name)
      use :: esmf, only: operator(==)
      character(:), allocatable :: phase_name
      type(ESMF_Method_Flag), intent(in) :: method_flag
      character(*), optional, intent(in) :: use_name
      if (present(use_name)) then
         phase_name = use_name
         return
      end if
      if (method_flag == ESMF_METHOD_INITIALIZE) then
         phase_name = 'GENERIC::INIT_USER'
      elseif (method_flag == ESMF_METHOD_RUN) then
         phase_name = 'GENERIC::RUN_USER'
      elseif (method_flag == ESMF_METHOD_FINALIZE) then
         phase_name = 'GENERIC::FINALIZE_USER'
      else
         phase_name = '<unknown>'
      end if
   end function get_default_phase_name
Call graph
set_entry_point calls get_default_phase_name
gridcomp_set_entry_point calls set_entry_point
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
setservices calls mapl_gridcompsetentrypoint