get_outer_gridcomp – MAPL
get_outer_gridcomp Function
5 statements
Source File
private function get_outer_gridcomp(this) result(gc)
Type Bound
InnerMetaComponent
Arguments
Type Intent Optional Attributes Name
class(InnerMetaComponent), intent(in) :: this
Return Value type(ESMF_GridComp)
Called by
Source Code
   function get_outer_gridcomp(this) result(gc)
      type(ESMF_GridComp) :: gc
      class(InnerMetaComponent), intent(in) :: this
      gc = this%outer_gc
   end function get_outer_gridcomp
Call graph
get_outer_gridcomp calls get_outer_gridcomp
get_outer_meta_from_inner_gc calls get_outer_gridcomp
gridcomp_get_outer_meta calls get_outer_gridcomp, mapl_gridcompgetoutermeta
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
run calls get_outer_meta_from_inner_gc
setservices calls get_outer_meta_from_inner_gc, setservices
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta