get_extension_string – MAPL
get_extension_string Function
10 statements
Source File
private function get_extension_string(this) result(s)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_extension_string(this) result(s)
      class(ActualConnectionPt), intent(in) :: this
      character(:), allocatable :: s
      character(16) :: buf
      s = ''
      if (this%is_extension()) then
         write(buf, '("(",i0,")")') this%label
         s = trim(buf)
      end if
   end function get_extension_string
Call graph
get_extension_string calls is_extension
get_esmf_name calls get_extension_string
get_full_name calls get_extension_string
add_to_state calls get_esmf_name
write_formatted calls get_full_name
test_vertical calls add_to_state