get_month – MAPL
get_month Function
4 statements
Source File
public function get_month(self)
Type Bound
ISO8601Date
Arguments
Type Intent Optional Attributes Name
class(ISO8601Date), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_month(self)
      class(ISO8601Date), intent(in) :: self
      get_month = self%month_
   end function get_month
Call graph
convert_iso8601_to_integer_date calls get_month
get_month_datetime calls get_month
test_construct_iso8601date calls get_month
test_iso8601date_getters calls get_month
convert_iso8601_to_esmf_time calls get_month_datetime
test_construct_iso8601datetime calls get_month_datetime
test_convert_iso8601_to_integer_date calls convert_iso8601_to_integer_date
test_iso8601datetime_getters calls get_month_datetime