get_name – MAPL
get_name Function
5 statements
Source File
private function get_name(this) result(name)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_name(this) result(name)
      character(:), allocatable:: name
      class(HierarchicalRegistry), intent(in) :: this
      name = this%name
   end function get_name
Call graph
add_subregistry calls get_name
connect_export_to_export calls get_name
get_subregistry_comp calls get_name
propagate_exports_virtual_pt calls get_name
propagate_unsatisfied_imports_virtual_pt calls get_name
connect calls connect_export_to_export, get_subregistry
test_connect calls add_subregistry
test_connect_chain calls add_subregistry
test_do_not_propagate_import calls add_subregistry, propagate_unsatisfied_imports
test_e2e_preserve_actual_pt calls add_subregistry
test_export_to_export_connection calls add_subregistry
test_get_subregistry calls add_subregistry, get_subregistry
test_get_subregistry_fail_not_found calls add_subregistry, get_subregistry
test_import_from_child calls add_subregistry
test_import_from_parent calls add_subregistry
test_multi_import calls add_subregistry, propagate_unsatisfied_imports
test_propagate_import calls add_subregistry, propagate_unsatisfied_imports
test_sibling_activation calls add_subregistry, propagate_exports, propagate_unsatisfied_imports
get_subregistry_conn calls get_subregistry
initialize_advertise calls propagate_exports, propagate_unsatisfied_imports
propagate_exports_all calls get_subregistry, propagate_exports
propagate_exports_child calls propagate_exports
propagate_unsatisfied_imports_all calls get_subregistry, propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
initialize calls initialize_advertise