get_regridder – MAPL
get_regridder Function
23 statements
Source File
private function get_regridder(this, spec, rc) result(regriddr)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout), target :: this
class(RegridderSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value class(Regridder), pointer
Calls
Called by
Source Code
   function get_regridder(this, spec, rc) result(regriddr)
      class(Regridder), pointer :: regriddr
      class(RegridderManager), target, intent(inout) :: this
      class(RegridderSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      class(Regridder), allocatable :: tmp_regridder
      associate (b => this%specs%begin(), e => this%specs%end())
        associate (iter => find(b, e, spec))
          if (iter /= e) then
             regriddr => this%regridders%of((iter-b+1))
             _RETURN(_SUCCESS)
          end if
          tmp_regridder = this%make_regridder(spec, _RC)
          call this%add_regridder(spec, tmp_regridder)
          regriddr => this%regridders%back()
        end associate
      end associate
      _RETURN(_SUCCESS)
   end function get_regridder
Call graph
get_regridder calls find, of, add_regridder, make_regridder, mapl_return, mapl_verify, vector_back, vector_begin
add_regridder calls vector_push_back
make_regridder calls mapl_return, mapl_verify, mapl_assert, make_regridder, of, get_param, supports
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder
regridaction calls new_scalarregridaction
make_action calls regridaction, make_action