get_comp_name – MAPL
get_comp_name Function
6 statements
Source File
private function get_comp_name(this) result(name)
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_comp_name(this) result(name)
      character(:), allocatable :: name
      class(VirtualConnectionPt), intent(in) :: this
      name = ''
      if (allocated(this%comp_name)) name = this%comp_name
   end function get_comp_name
Call graph
connect calls get_comp_name, connect_sibling
connect_sibling calls get_comp_name
get_comp_name calls get_comp_name
add_to_state calls get_comp_name
is_represented_in calls get_comp_name
add_to_states calls is_represented_in
test_vertical calls add_to_state
initialize_post_advertise calls add_to_states