get_component_spec – MAPL
get_component_spec Function
5 statements
Source File
private function get_component_spec(this) result(component_spec)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(in), target :: this
Return Value type(ComponentSpec), pointer
Called by
Source Code
   function get_component_spec(this) result(component_spec)
      type(ComponentSpec), pointer :: component_spec
      class(OuterMetaComponent), target, intent(in) :: this
      component_spec => this%component_spec
   end function get_component_spec
Call graph
add_export_spec calls get_component_spec
add_internal_spec calls get_component_spec
add_spec_basic calls get_component_spec
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic, add_spec_explicit
add_import_spec_legacy calls mapl_addspec
add_spec_explicit calls mapl_addspec
mapl_addimportspec calls add_import_spec_legacy