get_lgr – MAPL
get_lgr Function
5 statements
Source File
private function get_lgr(this) result(lgr)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(in), target :: this
Return Value class(Logger), pointer
Called by
Source Code
   function get_lgr(this) result(lgr)
      class(Logger), pointer :: lgr
      class(OuterMetaComponent), target, intent(in) :: this
      lgr => this%lgr
   end function get_lgr
Call graph
gridcomp_get calls get_lgr
mapl_gridcompget calls gridcomp_get
init_geom calls mapl_gridcompget
init_post_advertise calls mapl_gridcompget
resource_get_i4_gc calls mapl_gridcompget
resource_get_i4seq_gc calls mapl_gridcompget
resource_get_i8_gc calls mapl_gridcompget
resource_get_i8seq_gc calls mapl_gridcompget
resource_get_logical_gc calls mapl_gridcompget
resource_get_logical_seq_gc calls mapl_gridcompget
resource_get_r4_gc calls mapl_gridcompget
resource_get_r4seq_gc calls mapl_gridcompget
resource_get_r8_gc calls mapl_gridcompget
resource_get_r8seq_gc calls mapl_gridcompget
resource_get_string_gc calls mapl_gridcompget
setservices calls mapl_gridcompget, setservices
mapl_resourceget calls resource_get_i4_gc, resource_get_i4seq_gc, resource_get_i8_gc, resource_get_i8seq_gc, resource_get_logical_gc, resource_get_logical_seq_gc, resource_get_r4_gc, resource_get_r4seq_gc, resource_get_r8_gc, resource_get_r8seq_gc, resource_get_string_gc