get_state_intent – MAPL
get_state_intent Function
14 statements
Source File
private function get_state_intent(this) result(state_intent)
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_state_intent(this) result(state_intent)
      character(:), allocatable :: state_intent
      class(VirtualConnectionPt), intent(in) :: this
      select case (this%state_intent%state)
      case (ESMF_STATEINTENT_IMPORT%state)
         state_intent = 'import'
      case (ESMF_STATEINTENT_EXPORT%state)
         state_intent = 'export'
      case (ESMF_STATEINTENT_INTERNAL%state)
         state_intent = 'internal'
      case default
         state_intent = '<invalid>'
      end select
   end function get_state_intent
Call graph
get_state_intent calls get_state_intent
is_export calls get_state_intent, is_export
is_import calls get_state_intent, is_import
is_internal calls get_state_intent, is_internal
matches calls get_state_intent
test_alt_constructor calls get_state_intent
test_get_intent calls get_state_intent
write_formatted calls get_state_intent
add_to_state calls get_state_intent
filter calls matches
is_represented_in calls get_state_intent
add_item_spec_actual calls is_internal
add_to_states calls is_represented_in
connect calls filter
connect_export_to_export calls is_internal
propagate_exports_virtual_pt calls is_export
propagate_unsatisfied_imports_virtual_pt calls is_import
test_vertical calls add_to_state