get_value_r8seq – MAPL
get_value_r8seq Subroutine
55 statements
Source File
private subroutine get_value_r8seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
real(kind=ESMF_KIND_R8), intent(inout), dimension(:), allocatable :: value
real(kind=ESMF_KIND_R8), intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_value_r8seq(params, value, default, valuestring, rc)
      real(kind=ESMF_KIND_R8), dimension(:), allocatable, intent(inout) :: value
      real(kind=ESMF_KIND_R8), dimension(:), optional, intent(in) :: default
      character(len=*), parameter :: typestring = 'R8'
      character(len=*), parameter :: edit_descriptor = EDIT_DESC_R8
#include "hconfig_get_value_template.h"
   end subroutine get_value_r8seq
Call graph
get_value_r8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value calls get_value_r8seq