get_vertical_dimension_name_from_field – MAPL
get_vertical_dimension_name_from_field Function
12 statements
Source File
public function get_vertical_dimension_name_from_field(field, rc) result(dim_name)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_vertical_dimension_name_from_field(field, rc) result(dim_name)
      character(len=:), allocatable :: dim_name
      type(ESMF_Field), intent(in) :: field
      integer, intent(out), optional :: rc
      integer :: status
      type(VerticalStaggerLoc) :: vert_staggerloc
      call MAPL_FieldGet(field, vert_staggerLoc=vert_staggerLoc, _RC)
      dim_name = vert_staggerLoc%get_dimension_name()
      _RETURN(_SUCCESS)
   end function get_vertical_dimension_name_from_field
Call graph
get_vertical_dimension_name_from_field calls mapl_fieldget, get_dimension_name, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_variable_dim_names calls get_vertical_dimension_name_from_field
add_variable calls get_variable_dim_names
add_variables calls add_variable
bundle_to_metadata calls add_variables