get_inner_meta – MAPL
get_inner_meta Function
17 statements
Source File
public function get_inner_meta(gridcomp, rc) result(inner_meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Return Value type(InnerMetaComponent), pointer
Calls
Called by
Source Code
   function get_inner_meta(gridcomp, rc) result(inner_meta)
      type(InnerMetaComponent), pointer :: inner_meta
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      _GET_NAMED_PRIVATE_STATE(gridcomp, InnerMetaComponent, INNER_META_PRIVATE_STATE, inner_meta)
      _RETURN(_SUCCESS)
   end function get_inner_meta
Call graph
get_inner_meta calls mapl_assert, mapl_usercompgetinternalstate, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_outer_gridcomp calls get_inner_meta
get_outer_meta_from_inner_gc calls get_outer_gridcomp
gridcomp_get_outer_meta calls get_outer_gridcomp, mapl_gridcompgetoutermeta
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
run calls get_outer_meta_from_inner_gc
setservices calls get_outer_meta_from_inner_gc, setservices
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta