get_start_time – MAPL
get_start_time Function
25 statements
Source File
private function get_start_time(this, metadata, rc) result(startTime)
Type Bound
timeData
Arguments
Type Intent Optional Attributes Name
class(timeData), intent(inout) :: this
type(FileMetadata), intent(inout) :: metadata
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Called by
Source Code
  function get_start_time(this,metadata,rc) result(startTime)
    class(timeData), intent(inout) :: this
    type(FileMetaData), intent(inout) :: metadata
    integer, optional, intent(out) :: rc
    type(ESMF_Time) :: startTime
    integer :: status
    class(Variable), pointer :: v
    type(Attribute), pointer :: attr
    class(*), pointer :: units
    _UNUSED_DUMMY(this)
    v => metadata%get_variable('time',rc=status)
    _VERIFY(status)
    attr => v%get_attribute('units')
    units => attr%get_value()
    select type(units)
    type is (character(*))
       startTime = parse_time_string(units,rc=status)
       _VERIFY(status)
    class default
       _FAIL('unsupported subclass for units')
    end select
  end function get_start_time
Call graph
get_start_time calls mapl_assert, get_attribute, get_value, get_variable, mapl_verify, parse_time_string
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, m_at, mapl_return
get_value calls mapl_return
get_variable calls mapl_verify, at, mapl_return
mapl_verify calls mapl_throw_exception
parse_time_string calls mapl_assert, mapl_verify, ESMF_TimeSet
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
m_find calls s_find
map_at_rc calls map_find
compute_time_vector calls get_start_time
bundlepost calls compute_time_vector
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file