get_converter – MAPL
get_converter Subroutine
11 statements
Source File
public subroutine get_converter(conv, from, to, rc)
Arguments
Type Intent Optional Attributes Name
type(Converter), intent(inout) :: conv
character(len=*), intent(in) :: from
character(len=*), intent(in) :: to
integer(kind=ut_status), intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_converter(conv, from, to, rc)
      type(Converter),intent(inout) :: conv
      character(len=*), intent(in) :: from, to
      integer(ut_status), optional, intent(out) :: rc
      integer(ut_status) :: status
      conv = get_converter_function(from, to)
      _ASSERT_RC(.not. conv%is_free(), 'Failed to get converter function', UTF_CONVERTER_NOT_INITIALIZED)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(status)
   end subroutine get_converter
Call graph
get_converter calls mapl_assert, is_free, mapl_return
mapl_return calls at, insert, mapl_throw_exception
getfieldunitsconverter calls get_converter
test_convert_double calls get_converter
test_convert_doubles calls get_converter
test_convert_float calls get_converter
test_convert_floats calls get_converter
test_get_converter calls get_converter