get_full_name – MAPL
get_full_name Function
6 statements
Source File
private function get_full_name(this) result(name)
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_full_name(this) result(name)
      character(:), allocatable :: name
      class(VirtualConnectionPt), intent(in) :: this
      name = this%short_name
      if (allocated(this%comp_name)) name = this%comp_name // '/' // name
   end function get_full_name
Call graph
get_full_name calls get_full_name
less_than calls get_full_name
matches calls get_full_name
write_formatted calls get_full_name
operator(lt) calls less_than
filter calls matches
connect calls filter