get_lat_subset – MAPL
get_lat_subset Module Function
19 statements
Source File
pure module function get_lat_subset(this, axis, rank) result(local_axis) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonDecomposition), intent(in) :: this
type(LatAxis), intent(in) :: axis
integer, intent(in) :: rank
Return Value type(LatAxis)
Calls
Called by
Source Code
   pure module function get_lat_subset(this, axis, rank) result(local_axis)
      type(LatAxis) :: local_axis
      class(LatLonDecomposition), intent(in) :: this
      type(LatAxis), intent(in) :: axis
      integer, intent(in) :: rank
      real(kind=R8), allocatable :: centers(:)
      real(kind=R8), allocatable :: corners(:)
      integer :: j_0, j_1, j_n
      call get_idx_range(this%lat_distribution, rank, j_0, j_1)
      j_n = j_1 ! unless
      associate (ny => size(this%get_lat_distribution()))
        if (1+rank == ny) then
           j_n = j_n + 1
        end if
      end associate
      centers = get_subset(axis%get_centers(), j_0, j_1)
      corners = get_subset(axis%get_corners(), j_0, j_n)
      local_axis = LatAxis(centers, corners)
   end function get_lat_subset
Call graph
get_lat_subset calls get_centers, get_corners, get_lat_distribution, get_idx_range, get_subset, get_lat_subset
get_centers calls get_centers
get_corners calls get_corners
get_lat_distribution calls get_lat_distribution
fill_coordinates calls get_lat_subset, fill_coordinates
typesafe_make_geom calls fill_coordinates