get_comp_name – MAPL
get_comp_name Function
5 statements
Source File
private function get_comp_name(this) result(name)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_comp_name(this) result(name)
      character(:), allocatable :: name
      class(ActualConnectionPt), intent(in) :: this
      name = this%v_pt%get_comp_name()
   end function get_comp_name
Call graph
get_comp_name calls get_comp_name
add_to_state calls get_comp_name
is_represented_in calls get_comp_name
add_to_states calls is_represented_in
test_vertical calls add_to_state
initialize_post_advertise calls add_to_states
initialize calls initialize_post_advertise