get_variable – MAPL
get_variable Function
13 statements
Source File
private function get_variable(this, var_name, unusable, rc) result(var)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(in), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(Variable), pointer
Calls
Called by
Source Code
   function get_variable(this, var_name, unusable, rc) result(var)
      class (Variable), pointer :: var
      class (FileMetadataUtils), target, intent(in) :: this
      character(len=*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      var => this%metadata%get_variable(var_name, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function get_variable
Call graph
get_variable calls get_variable, mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
map_at_rc calls map_find
get_var_attr_int32 calls get_variable
get_var_attr_int64 calls get_variable
get_var_attr_real32 calls get_variable
get_var_attr_real64 calls get_variable
get_var_attr_string calls get_variable
get_variable_attribute calls get_variable
getlevs calls get_variable, get_variable_attribute, get_coordinate_info, get_level_name
var_get_missing_value calls get_variable, get_var_attr_real32, var_has_attr
var_has_attr calls get_variable
var_has_missing_value calls get_variable
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
get_coordinate_info calls var_has_attr
get_file_times calls get_var_attr_int32
get_level_name calls get_variable_attribute
initialize_ calls getlevs, get_coordinate_info, create_primary_field
mapl_create_bundle_from_metdata_id calls get_var_attr_string, get_level_name
swap_undef_value calls var_get_missing_value, var_has_missing_value
time_ave calls var_get_missing_value, get_coordinate_info, get_file_times, get_level_name
create_grid calls get_level_name
get_file_levels calls get_coordinate_info, get_level_name
get_time_info calls get_coordinate_info
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
process_data_from_file calls swap_undef_value
run_ calls create_bracketing_fields