get_num_ungridded – MAPL
get_num_ungridded Function
4 statements
Source File
private pure function get_num_ungridded(this)
Type Bound
UngriddedDimsSpec
Arguments
Type Intent Optional Attributes Name
class(UngriddedDimsSpec), intent(in) :: this
Return Value integer
Called by
Source Code
   pure integer function get_num_ungridded(this)
      class(UngriddedDimsSpec), intent(in) :: this
      get_num_ungridded = this%dim_specs%size()
   end function get_num_ungridded
Call graph
add_dim_spec calls get_num_ungridded
get_bounds calls get_num_ungridded
make_info calls get_num_ungridded
get_ungridded_bounds calls get_bounds
parse_var_specs calls add_dim_spec
set_info calls make_info
test_field_set_info calls add_dim_spec, set_info
allocate calls get_ungridded_bounds, set_info
parse_component_spec calls parse_var_specs
setservices_ calls parse_component_spec