get_long_names – MAPL
get_long_names Function
27 statements
Source File
function get_long_names(bundle, rc) result(long_names)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
integer, intent(out), optional :: rc
Return Value character(len=ESMF_MAXSTR), allocatable, (:)
Calls
Called by
Source Code
   function get_long_names(bundle,rc) result(long_names)
      character(len=ESMF_MAXSTR), allocatable :: long_names(:)
      type(ESMF_FieldBundle), intent(in) :: bundle
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=ESMF_MAXSTR), allocatable :: field_list(:)
      type(ESMF_Field) :: field
      type(ESMF_Info) :: infoh
      integer :: i,num_fields
      call ESMF_FieldBundleGet(bundle,fieldCount=num_fields,_RC)
      allocate(field_list(num_fields))
      allocate(long_names(num_fields))
      call ESMF_FieldBundleGet(bundle,fieldNameList=field_list,_RC)
      do i=1,num_fields
         call ESMF_FieldBundleGet(bundle,field_list(i),field=field,_RC)
         call ESMF_InfoGetFromHost(field,infoh,_RC)
         call ESMF_InfoGet(infoh,key='LONG_NAME',value=long_names(i),_RC)
      enddo
      if (present(rc)) then
         RC=_SUCCESS
      end if
   end function get_long_names
Call graph
get_long_names calls ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldbundleget, mapl_abort, mapl_verify
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
time_ave calls get_long_names