get_subregistry_conn – MAPL
get_subregistry_conn Function
11 statements
Source File
private function get_subregistry_conn(this, conn_pt, rc) result(subregistry)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
type(ConnectionPt), intent(in) :: conn_pt
integer, intent(out), optional :: rc
Return Value type(HierarchicalRegistry), pointer
Calls
Called by
Source Code
   function get_subregistry_conn(this, conn_pt, rc) result(subregistry)
      type(HierarchicalRegistry), pointer :: subregistry
      class(HierarchicalRegistry), target, intent(in) :: this
      type(ConnectionPt), intent(in) :: conn_pt
      integer, optional, intent(out) :: rc
      integer :: status
      subregistry => this%get_subregistry(conn_pt%component_name,_RC)
      _RETURN(_SUCCESS)
   end function get_subregistry_conn
Call graph
get_subregistry_conn calls get_subregistry, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_subregistry_comp calls mapl_return, mapl_verify, mapl_assert, at, get_name
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
connect calls get_subregistry
propagate_exports_all calls get_subregistry
propagate_unsatisfied_imports_all calls get_subregistry
test_get_subregistry calls get_subregistry
test_get_subregistry_fail_not_found calls get_subregistry