get_centers – MAPL
get_centers Module Function
5 statements
Source File
pure module function get_centers(this) result(centers) Interface →
Arguments
Type Intent Optional Attributes Name
class(CoordinateAxis), intent(in) :: this
Return Value real(kind=R8), allocatable, (:)
Called by
Source Code
   pure module function get_centers(this) result(centers)
      real(kind=R8), allocatable :: centers(:)
      class(CoordinateAxis), intent(in) :: this
      centers = this%centers
   end function get_centers
Call graph
get_centers calls get_centers
fill_coordinates calls get_centers, get_lat_subset, get_lon_subset, fill_coordinates
get_lat_subset calls get_centers, get_lat_subset
get_lon_subset calls get_centers, get_lon_subset
test_make_lon_axis_from_hconfig calls get_centers
typesafe_make_file_metadata calls get_centers
make_file_metadata calls typesafe_make_file_metadata, make_file_metadata
typesafe_make_geom calls fill_coordinates