get_value_i4seq – MAPL
get_value_i4seq Subroutine
55 statements
Source File
private subroutine get_value_i4seq(params, value, default, valuestring, rc)
Arguments
Type Intent Optional Attributes Name
type(HConfigParams), intent(inout) :: params
integer(kind=ESMF_KIND_I4), intent(inout), dimension(:), allocatable :: value
integer(kind=ESMF_KIND_I4), intent(in), optional, dimension(:) :: default
character(len=:), intent(out), optional, allocatable :: valuestring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_value_i4seq(params, value, default, valuestring, rc)
      integer(kind=ESMF_KIND_I4), dimension(:), allocatable, intent(inout) :: value
      integer(kind=ESMF_KIND_I4), dimension(:), optional, intent(in) :: default
      character(len=*), parameter :: typestring = 'I4'
      character(len=*), parameter :: edit_descriptor = EDIT_DESC_I4
#include "hconfig_get_value_template.h"
   end subroutine get_value_i4seq
Call graph
get_value_i4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value calls get_value_i4seq