get_outer_meta_from_outer_gc – MAPL
get_outer_meta_from_outer_gc Function
17 statements
Source File
private function get_outer_meta_from_outer_gc(gridcomp, rc) result(outer_meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
integer, intent(out), optional :: rc
Return Value type(OuterMetaComponent), pointer
Calls
Called by
Source Code
   function get_outer_meta_from_outer_gc(gridcomp, rc) result(outer_meta)
      type(OuterMetaComponent), pointer :: outer_meta
      type(ESMF_GridComp), intent(inout) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      _GET_NAMED_PRIVATE_STATE(gridcomp, OuterMetaComponent, OUTER_META_PRIVATE_STATE, outer_meta)
      _RETURN(_SUCCESS)
   end function get_outer_meta_from_outer_gc
Call graph
get_outer_meta_from_outer_gc calls mapl_assert, mapl_usercompgetinternalstate, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_outer_meta calls get_outer_meta_from_outer_gc
apply_to_children_custom calls get_outer_meta
create_grid_comp_primary calls get_outer_meta
finalize calls get_outer_meta
get_child_user_states calls get_outer_meta
get_outer_meta_from_inner_gc calls get_outer_meta
get_substates calls get_outer_meta, get_substates
gridcomp_get_outer_meta calls get_outer_meta
initialize calls get_outer_meta
read_restart calls get_outer_meta
run calls get_outer_meta, get_outer_meta_from_inner_gc
setservices calls get_outer_meta, get_outer_meta_from_inner_gc
setup calls get_outer_meta
test_child_outer_items_created calls get_outer_meta, get_child_user_states
test_child_user_items_created calls get_outer_meta
test_mapl_invalid_name calls get_outer_meta
test_parent_user_items_created calls get_outer_meta
test_state_items_complete calls get_outer_meta
write_restart calls get_outer_meta
apply_to_children calls apply_to_children_custom
create_grid_comp calls create_grid_comp_primary
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
test_anything calls get_substates
test_finalize_children calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup