get_field – MAPL
get_field Subroutine
32 statements
Source File
public subroutine get_field(field, states, state_intent, unusable, field_name, substate_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(out) :: field
type(MultiState), intent(in) :: states
character(len=*), intent(in) :: state_intent
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: field_name
character(len=*), intent(in), optional :: substate_name
integer, intent(out) :: rc
Calls
Called by
Source Code
   subroutine get_field(field, states, state_intent, unusable, field_name, substate_name, rc)
      type(ESMF_Field), intent(out) :: field
      type(MultiState), intent(in) :: states
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(*), intent(in) :: state_intent
      character(*), intent(in) :: field_name
      character(*), optional, intent(in) :: substate_name
      integer, intent(out) :: rc
      integer :: status
      type(ESMF_State) :: state, substate
      rc = +1
      call states%get_state(state, state_intent, rc=status)
      if (status /= 0) then
         rc = +2
         return
      end if
      if (present(substate_name)) then
         call ESMF_StateGet(state, substate_name, substate, rc=status)
         if (status /= 0) then
            rc = +3
            return
         end if
      else
         substate = state
      end if
      call ESMF_StateGet(substate, field_name, field, rc=status)
      if (status /= 0) then
         rc = 4
         return
      end if
      rc = 0
   end subroutine get_field
Call graph
get_field calls esmf_stateget, get_state
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_child_outer_items_created calls get_field