get_param – MAPL
get_param Function
5 statements
Source File
private function get_param(this) result(param)
Type Bound
RegridderSpec
Arguments
Type Intent Optional Attributes Name
class(RegridderSpec), intent(in) :: this
Return Value class(RegridderParam), allocatable
Called by
Source Code
   function get_param(this) result(param)
      class(RegridderParam), allocatable :: param
      class(RegridderSpec), intent(in) :: this
      param = this%param
   end function get_param
Call graph
make_regridder calls get_param, make_regridder
make_regridder_typesafe calls get_param
get_regridder calls make_regridder
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder
regridaction calls new_scalarregridaction