get_ranks – MAPL
get_ranks Module Subroutine
16 statements
Source File
module subroutine get_ranks(nx, ny, ix, iy, rc) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(out) :: ix
integer, intent(out) :: iy
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine get_ranks(nx, ny, ix, iy, rc)
      integer, intent(in) :: nx, ny
      integer, intent(out) :: ix, iy
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: petCount, localPet
      type(ESMF_VM) :: vm
      call ESMF_VMGetCurrent(vm, _RC)
      call ESMF_VMGet(vm, petCount=petCount, localPet=localPet, _RC)
      ix = mod(localPet, nx)
      iy = localPet / nx
      _RETURN(_SUCCESS)
   end subroutine get_ranks
Call graph
get_ranks calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_return, mapl_verify, get_ranks
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
fill_coordinates calls get_ranks, fill_coordinates
typesafe_make_geom calls fill_coordinates