get_lon_distribution – MAPL
get_lon_distribution Module Function
5 statements
Source File
pure module function get_lon_distribution(decomp) result(lon_distribution) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonDecomposition), intent(in) :: decomp
Return Value integer, allocatable, (:)
Called by
Source Code
   pure module function get_lon_distribution(decomp) result(lon_distribution)
      integer, allocatable :: lon_distribution(:)
      class(LatLonDecomposition), intent(in) :: decomp
      lon_distribution = decomp%lon_distribution
   end function get_lon_distribution
Call graph
get_lon_distribution calls get_lon_distribution
create_basic_grid calls get_lon_distribution, create_basic_grid
fill_coordinates calls get_lon_distribution, get_lon_subset, fill_coordinates
get_lon_subset calls get_lon_distribution, get_lon_subset
typesafe_make_geom calls create_basic_grid, fill_coordinates