get_item_spec – MAPL
get_item_spec Function
14 statements
Source File
private function get_item_spec(this, actual_pt, rc) result(spec)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Return Value class(StateItemSpec), pointer
Calls
Called by
Source Code
   function get_item_spec(this, actual_pt, rc) result(spec)
      class(StateItemSpec), pointer :: spec
      class(HierarchicalRegistry), target, intent(in) :: this
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      type(StateItemSpecPtr), pointer :: wrap
      spec => null()
      wrap => this%actual_specs_map%at(actual_pt, _RC)
      if (associated(wrap)) spec => wrap%ptr
      _RETURN(_SUCCESS)
   end function get_item_spec
Call graph
get_item_spec calls at, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize
map_find calls map_s_find
activate_dependencies calls get_item_spec
check_actual calls get_item_spec
connect_export_to_export calls get_item_spec
get_actual_pt_specptrs calls get_item_spec
init_post_advertise calls get_item_spec
make_servicespec calls get_item_spec
propagate_exports_virtual_pt calls get_item_spec
propagate_unsatisfied_imports_virtual_pt calls get_item_spec
test_create_extension calls get_item_spec
test_get_item_spec_found calls get_item_spec
test_get_item_spec_not_found calls get_item_spec
test_internal_activation calls get_item_spec
test_internal_to_export_connection calls get_item_spec
test_multi_import calls get_item_spec
test_sibling_activation calls get_item_spec
check calls check_actual
check_virtual calls check_actual
connect calls get_actual_pt_specptrs, connect_export_to_export
connect_sibling calls activate_dependencies, get_actual_pt_specptrs
make_itemspec calls make_servicespec