get_file_times – MAPL
get_file_times Subroutine
45 statements
Source File
subroutine get_file_times(filename, itime, alltimes, tseries, timeInterval, tint, tsteps, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer, intent(in) :: itime(2)
logical, intent(in) :: alltimes
type(ESMF_Time), intent(inout), allocatable :: tseries(:)
type(ESMF_TimeInterval), intent(inout) :: timeInterval
integer, intent(out) :: tint
integer, intent(out) :: tsteps
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_file_times(filename,itime,alltimes,tseries,timeInterval,tint,tsteps,rc)
      character(len=*), intent(in) :: filename
      integer, intent(in) :: itime(2)
      logical, intent(in) :: alltimes
      type(ESMF_Time), allocatable, intent(inout) :: tseries(:)
      type(ESMF_TimeInterval), intent(inout) :: timeInterval
      integer, intent(out) :: tint
      integer, intent(out) :: tsteps
      integer, intent(out), optional :: rc
      integer :: status
      integer :: second,minute,hour,day,month,year
      type(NetCDF4_fileFormatter) :: formatter
      type(FileMetadata) :: basic_metadata
      type(FileMetadataUtils) :: metadata
      call formatter%open(trim(filename),pFIO_Read,_RC)
      basic_metadata=formatter%read(_RC)
      call metadata%create(basic_metadata,trim(filename))
      call formatter%close(_RC)
      tsteps = metadata%get_dimension('time',_RC)
      call metadata%get_time_info(timeVector=tSeries,_RC)
      if (.not.allTimes) then
         tSteps=1
         call UnpackDateTIme(itime,year,month,day,hour,minute,second)
         deallocate(tSeries)
         allocate(tSeries(1))
         call ESMF_TimeSet(tSeries(1), yy=year, mm=month, dd=day,  h=hour,  m=minute, s=second,_RC)
      end if
      if (tSteps == 1) then
         call ESMF_TimeIntervalSet( TimeInterval, h=6, m=0, s=0, _RC )
      else
         TimeInterval=tSeries(2)-tSeries(1)
      end if
      call ESMF_TimeIntervalGet(TimeInterval,h=hour,m=minute,s=second,_RC)
      tint=hour*10000+minute*100+second
      _RETURN(_SUCCESS)
   end subroutine get_file_times
Call graph
get_file_times calls ESMF_TimeIntervalGet, ESMF_TimeIntervalSet, ESMF_TimeSet, create, get_dimension, get_time_info, mapl_return, mapl_verify, unpackdatetime
get_dimension calls mapl_return, mapl_verify, get_dimension, at, find
get_time_info calls ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_return, mapl_verify, ESMF_TimeGet, mapl_assert, get_attribute, get_coordinate_data, get_coordinate_info, get_coordinate_variable, get_file_name, get_value
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_return, mapl_assert, m_at
get_coordinate_data calls mapl_return
get_coordinate_info calls get_dimension, mapl_return, mapl_verify, mapl_assert, get_attribute, get_coordinate_data, get_coordinate_variable, get_file_name, get_value, get_ith_dimension, var_has_attr
get_coordinate_variable calls mapl_return, mapl_verify, get_coordinate_variable
get_error_message calls at, insert
get_file_name calls mapl_return
get_value calls mapl_return
mapl_throw_exception calls initialize
main calls get_file_times
regrid_util calls main