get_actual_pts – MAPL
get_actual_pts Function
7 statements
Source File
private function get_actual_pts(this, virtual_pt) result(actual_pts)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
type(VirtualConnectionPt), intent(in) :: virtual_pt
Return Value type(ActualPtVector), pointer
Calls
Called by
Source Code
   function get_actual_pts(this, virtual_pt) result(actual_pts)
      type(ActualPtVector), pointer :: actual_pts
      class(HierarchicalRegistry), target, intent(in) :: this
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      integer :: status
      ! failure is ok; just returns null pointer
      actual_pts => this%virtual_pts%at(virtual_pt, rc=status)
   end function get_actual_pts
Call graph
get_actual_pts calls at
map_at_rc calls map_find
map_find calls map_s_find
check_virtual calls get_actual_pts
connect_export_to_export calls get_actual_pts
connect_sibling calls get_actual_pts, extend_
extend_ calls get_actual_pts
test_connect calls get_actual_pts
test_connect_chain calls get_actual_pts
test_import_from_child calls get_actual_pts
test_import_from_parent calls get_actual_pts
check calls check_virtual
connect calls connect_sibling, connect_export_to_export
test_export_to_export_connection calls check
test_get_item_spec_found calls check
test_get_item_spec_multi calls check
test_internal_to_export_connection calls check
test_sibling_activation calls check