GETFILE – MAPL
GETFILE Function
73 statements
Source File
public function GETFILE(Name, DO_OPEN, Form, ALL_PES, BLOCKSIZE, NUMBUFFERS, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: Name
integer, intent(in), optional :: DO_OPEN
character(len=*), intent(in), optional :: Form
logical, intent(in), optional :: ALL_PES
integer, intent(in), optional :: BLOCKSIZE
integer, intent(in), optional :: NUMBUFFERS
integer, intent(out), optional :: RC
Return Value integer
Calls
Called by
Source Code
  INTEGER FUNCTION GETFILE( NAME, DO_OPEN, FORM, ALL_PES, &
                             BLOCKSIZE, NUMBUFFERS, RC )
    IMPLICIT NONE
    character(LEN=*), intent(in   )           :: Name
    integer         , intent(in   ), OPTIONAL :: DO_OPEN
    character(LEN=*), intent(in   ), OPTIONAL :: Form
    logical         , intent(in   ), OPTIONAL :: ALL_PES
    integer         , intent(in   ), OPTIONAL :: BLOCKSIZE
    integer         , intent(in   ), OPTIONAL :: NUMBUFFERS
    integer         , intent(  out), OPTIONAL :: RC
    INTEGER I
    integer :: DO_OPEN_
    logical :: ALL_PES_
    integer          :: status
    LOGICAL FILEOPEN, UNITOPEN, FOUND
    if(INDEX(NAME,'*') /= 0) then
        getfile = getfilemem(name,rc=status)
    _VERIFY(STATUS)
        _RETURN(ESMF_SUCCESS)
    endif
    if (NAME == "stdout" .or. NAME== "STDOUT") then
       GETFILE = STD_OUT_UNIT_NUMBER
       _RETURN(ESMF_SUCCESS)
    end if
    if (.not. present(DO_OPEN)) then
       DO_OPEN_ = 1
    else
       DO_OPEN_ = DO_OPEN
    end if
    ALL_PES_ = .false.
    if (present(ALL_PES)) then
       ALL_PES_ = ALL_PES
    end if
    if (.not. MAPL_AM_I_ROOT() .and. .not. ALL_PES_) then
       GETFILE = UNDEF
       _RETURN(ESMF_SUCCESS)
    end if
!   Check if the file is already open
    INQUIRE ( FILE=NAME, NUMBER=GETFILE, OPENED=FILEOPEN )
!   If the file isnt already open THEN
    IF ( .NOT. FILEOPEN ) THEN
       I = 20
       FOUND = .FALSE.
       DO WHILE ( I.LE.LAST_UNIT .AND. .NOT.FOUND )
          IF ( .NOT. TAKEN(I) ) THEN
             TAKEN(I) = .TRUE.
             INQUIRE ( UNIT=I, OPENED=UNITOPEN )
             IF ( .NOT. UNITOPEN ) THEN
                status = 0
                if ( DO_OPEN_ .NE. 0 ) then
                   call MAPL_open(UNIT=i,FILE=Name,FORM=FORM, &
                                  BLOCKSIZE= BLOCKSIZE, NUMBUFFERS=NUMBUFFERS, RC=STATUS)
                endif
                if ( status /= 0 ) then
                   write (0,*) 'ERROR opening "',trim(Name),'" using GETFILE'
                   write (0,*) ' IOSTAT = ',status
                   _RETURN(ESMF_FAILURE)
                endif
                GETFILE = I
                FOUND = .TRUE.
             ENDIF
          ENDIF
          I = I + 1
       ENDDO
!
!      IF there are no available logical units THEN
!         Write an error message
!         Return Error status
!      ENDIF there are no available logical units
!
       IF ( .NOT. FOUND ) THEN
          WRITE (0,*) ' COULD NOT FIND ANY AVAILABLE UNITS '
          _RETURN(ESMF_FAILURE)
       ENDIF
    ENDIF ! the file isnt already open
    _RETURN(ESMF_SUCCESS)
  END FUNCTION GETFILE
Call graph
getfile calls mapl_am_i_root, getfilemem, mapl_open, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_open calls mapl_am_i_root, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
cap_finalize calls getfile
initialize calls getfile, regen_rcx_for_obs_platform
mapl_climupdate calls getfile
mapl_clockinit calls getfile
mapl_destroystatesave calls getfile, mapl_destroystatesave
mapl_esmfstatereadfromfile calls getfile
mapl_esmfstatewritetofile calls getfile
mapl_genericstaterestore calls getfile, mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_gradsctlwrite calls getfile
mapl_gridcoordadjustfromfile calls getfile
mapl_locstreamcreatefromfile calls getfile
mapl_readforcingx calls getfile
mapl_staterefresh calls getfile, mapl_esmfstatereadfromfile
readrestart calls getfile
regen_rcx_for_obs_platform calls getfile
run calls getfile, mapl_gradsctlwrite
writerestart calls getfile
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
capture calls mapl_esmfstatewritetofile
destroy_state calls mapl_destroystatesave
finalize_gc calls cap_finalize
initialize_gc calls mapl_clockinit
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericrefresh calls mapl_staterefresh
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterecord calls mapl_esmfstatewritetofile
refresh_state calls mapl_genericstaterestore