GetFieldUnitsConverter – MAPL
GetFieldUnitsConverter Subroutine
15 statements
Source File
public subroutine GetFieldUnitsConverter(from_identifier, to_identifier, conv, unusable, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: from_identifier
character(len=*), intent(in) :: to_identifier
type(FieldUnitsConverter), intent(out) :: conv
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine GetFieldUnitsConverter(from_identifier, to_identifier, conv, unusable, rc)
      character(len=*), intent(in) :: from_identifier, to_identifier
      type(FieldUnitsConverter), intent(out) :: conv
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      call get_converter(conv, from_identifier, to_identifier, _RC)
      _RETURN(_SUCCESS)
   end subroutine GetFieldUnitsConverter
Call graph
getfieldunitsconverter calls get_converter, mapl_return, mapl_verify
get_converter calls get_converter_function, is_free
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_converter_function calls is_free, instance_is_uninitialized
get_error_message calls at, insert
mapl_throw_exception calls initialize
instance_is_uninitialized calls is_free