GetFieldsUndef_r4 – MAPL
GetFieldsUndef_r4 Subroutine
20 statements
Source File
private subroutine GetFieldsUndef_r4(fields, undef_values, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: fields(:)
real(kind=ESMF_KIND_R4), intent(inout), allocatable :: undef_values(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine GetFieldsUndef_r4(fields,undef_values,rc)
     type(ESMF_Field), intent(inout) :: fields(:)
     real(kind=ESMF_KIND_R4), allocatable,intent(inout) :: undef_values(:)
     integer, optional, intent(out) :: rc
     integer :: status, i
     logical :: isPresent
     type(ESMF_Info) :: infoh
     allocate(undef_values(size(fields)))
     do i =1,size(fields)
        call ESMF_InfoGetFromHost(fields(i),infoh,_RC)
        isPresent = ESMF_InfoIsPresent(infoh,"missing_value",_RC)
        _ASSERT(isPresent,"missing undef value")
        call ESMF_InfoGet(infoh,value=undef_values(i),key="missing_value",_RC)
     enddo
     _RETURN(_SUCCESS)
  end subroutine GetFieldsUndef_r4
Call graph
getfieldsundef_r4 calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
getfieldsundef calls getfieldsundef_r4
fieldabs calls getfieldsundef
fieldacos calls getfieldsundef
fieldadd calls getfieldsundef
fieldasin calls getfieldsundef
fieldatan calls getfieldsundef
fieldcos calls getfieldsundef
fieldcosh calls getfieldsundef
fielddivide calls getfieldsundef
fieldexp calls getfieldsundef
fieldlog calls getfieldsundef
fieldlog10 calls getfieldsundef
fieldmultiply calls getfieldsundef
fieldnegate calls getfieldsundef
fieldpow calls getfieldsundef
fieldpower calls getfieldsundef
fieldsin calls getfieldsundef
fieldsinh calls getfieldsundef
fieldsqrt calls getfieldsundef
fieldsubtract calls getfieldsundef
fieldtan calls getfieldsundef
fieldtanh calls getfieldsundef