gridcomp_is_user – MAPL
gridcomp_is_user Function
11 statements
Source File
private function gridcomp_is_user(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(in) :: gridcomp
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function gridcomp_is_user(gridcomp, rc)
      type(ESMF_GridComp), intent(in) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Info) :: info
      logical :: found
      gridcomp_is_user = .not. MAPL_GridCompIsGeneric(gridcomp, _RC)
      _RETURN(_SUCCESS)
   end function gridcomp_is_user
Call graph
gridcomp_is_user calls mapl_gridcompisgeneric, mapl_return, mapl_verify
mapl_gridcompisgeneric calls gridcomp_is_generic
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_is_generic calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsSet
mapl_throw_exception calls initialize
mapl_gridcompisuser calls gridcomp_is_user
get_outer_gridcomp calls mapl_gridcompisuser
get_outer_meta_from_inner_gc calls get_outer_gridcomp
gridcomp_get_outer_meta calls get_outer_gridcomp
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
run calls get_outer_meta_from_inner_gc
setservices calls get_outer_meta_from_inner_gc