grid_get_coords_2d – MAPL
grid_get_coords_2d Module Subroutine
13 statements
Source File
module subroutine grid_get_coords_2d(grid, longitudes, latitudes, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
real(kind=ESMF_KIND_R8), pointer :: longitudes(:,:)
real(kind=ESMF_KIND_R8), pointer :: latitudes(:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine grid_get_coords_2d(grid, longitudes, latitudes, rc)
      type(ESMF_Grid), intent(in) :: grid
      real(kind=ESMF_KIND_R8), pointer :: longitudes(:,:)
      real(kind=ESMF_KIND_R8), pointer :: latitudes(:,:)
      integer, optional, intent(out) :: rc
      integer :: status
      call ESMF_GridGetCoord(grid, localDE=0, coordDim=1, farrayPtr=longitudes, &
           staggerloc=ESMF_STAGGERLOC_CENTER, _RC)
      call ESMF_GridGetCoord(grid, localDE=1, coordDim=2, farrayPtr=latitudes, &
           staggerloc=ESMF_STAGGERLOC_CENTER, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine grid_get_coords_2d
Call graph
grid_get_coords_2d calls ESMF_GridGetCoord, mapl_return, mapl_verify, grid_get_coords_2d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
gridgetcoords calls grid_get_coords_2d
grid_get_centers calls gridgetcoords, grid_get_centers
grid_get_coords_1d calls gridgetcoords, grid_get_coords_1d
grid_get_corners calls gridgetcoords, grid_get_corners
mapl_geomgetcoords calls gridgetcoords, mapl_geomgetcoords
new_gridvectorbasis calls gridgetcoords, new_gridvectorbasis