GridGetLatLons_ – MAPL
GridGetLatLons_ Subroutine
32 statements
Source File
private subroutine GridGetLatLons_(grid, lons, lats, rc)
Uses
MAPL_GetLatLonCoordMod
This is a candidate for ESMFL, here for dependency reasons
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid) :: grid
real, pointer :: lons(:)
real, pointer :: lats(:)
integer, optional :: rc
Calls
Called by
Source Code
  subroutine GridGetLatLons_ ( grid, lons, lats, rc )
    use MAPL_GetLatLonCoordMod
    implicit NONE
    type(ESMF_Grid) :: grid
    real, pointer   :: lons(:), lats(:)
    integer, optional :: rc
!                     ---
    integer                :: IM_WORLD, JM_WORLD, dims(3), STATUS
!                          ----
!      Get world dimensions
!      --------------------
       call MAPL_GridGet ( grid, globalCellCountPerDim=DIMS, RC=STATUS)
       _VERIFY(STATUS)
       IM_WORLD = dims(1)
       JM_WORLD = dims(2)
!      Allocate memory for output if necessary
!      ---------------------------------------
       if ( .not. associated(lons) ) then
            allocate(lons(IM_WORLD), stat=STATUS)
       else
            if(size(LONS,1) /= IM_WORLD) STATUS = 1
       end if
       _VERIFY(status)
       if ( .not. associated(lats) ) then
            allocate(lats(JM_WORLD), stat=STATUS)
       else
            if(size(LATS,1) /= JM_WORLD) STATUS = 1
       end if
       _VERIFY(status)
       call MAPL_GetLatLonCoord(grid,1,lons,rc=status)
       _VERIFY(status)
       call MAPL_GetLatLonCoord(grid,2,lats,rc=status)
       _VERIFY(status)
       lons = lons*(180._REAL64/MAPL_PI_R8)
       lats = lats*(180._REAL64/MAPL_PI_R8)
       _RETURN(ESMF_SUCCESS)
     end subroutine GridGetLatLons_
Call graph
gridgetlatlons_ calls mapl_getlatloncoord, mapl_gridget, mapl_return, mapl_verify
mapl_getlatloncoord calls mapl_getlatloncoord_real32, mapl_getlatloncoord_real64
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_getlatloncoord_real32 calls mapl_gridget, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet, ESMF_GridGetCoord, ESMF_VMGet, arraygather, mapl_assert, mapl_commsbcast
mapl_getlatloncoord_real64 calls mapl_gridget, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet, ESMF_GridGetCoord, ESMF_VMGet, arraygather, mapl_assert, mapl_commsbcast
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
mapl_cfioreadbundle calls gridgetlatlons_
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread
utcfio calls test_main