gridcomp_get – MAPL
gridcomp_get Subroutine
19 statements
Source File
private subroutine gridcomp_get(gridcomp, unusable, hconfig, outer_meta, logger, registry, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_HConfig), intent(out), optional :: hconfig
type(OuterMetaComponent), intent(out), optional, pointer :: outer_meta
class(Logger), intent(out), optional, pointer :: logger
type(HierarchicalRegistry), intent(out), optional, pointer :: registry
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine gridcomp_get(gridcomp, unusable, &
        hconfig, &
        outer_meta, &
        logger, &
        registry, &
        rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Hconfig), optional, intent(out) :: hconfig
      type(OuterMetaComponent), pointer, optional, intent(out) :: outer_meta
      class(Logger_t), optional, pointer, intent(out) :: logger
      type(HierarchicalRegistry), optional, pointer, intent(out) :: registry
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta_
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta_, _RC)
      if (present(hconfig)) hconfig = outer_meta_%get_hconfig()
      if (present(outer_meta)) outer_meta => outer_meta_
      if (present(logger)) logger => outer_meta_%get_lgr()
      if (present(registry)) registry => outer_meta_%get_registry()
      _RETURN(_SUCCESS)
   end subroutine gridcomp_get
Call graph
gridcomp_get calls mapl_gridcompgetoutermeta, get_hconfig, get_lgr, get_registry, mapl_return, mapl_verify
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
mapl_gridcompget calls gridcomp_get
init_geom calls mapl_gridcompget
init_post_advertise calls mapl_gridcompget
resource_get_i4_gc calls mapl_gridcompget
resource_get_i4seq_gc calls mapl_gridcompget
resource_get_i8_gc calls mapl_gridcompget
resource_get_i8seq_gc calls mapl_gridcompget
resource_get_logical_gc calls mapl_gridcompget
resource_get_logical_seq_gc calls mapl_gridcompget
resource_get_r4_gc calls mapl_gridcompget
resource_get_r4seq_gc calls mapl_gridcompget
resource_get_r8_gc calls mapl_gridcompget
resource_get_r8seq_gc calls mapl_gridcompget
resource_get_string_gc calls mapl_gridcompget
setservices calls mapl_gridcompget, setservices, mapl_resourceget
mapl_resourceget calls resource_get_i4_gc, resource_get_i4seq_gc, resource_get_i8_gc, resource_get_i8seq_gc, resource_get_logical_gc, resource_get_logical_seq_gc, resource_get_r4_gc, resource_get_r4seq_gc, resource_get_r8_gc, resource_get_r8seq_gc, resource_get_string_gc