GridCoordGet – MAPL
GridCoordGet Subroutine
79 statements
Source File
private subroutine GridCoordGet(GRID, coord, name, location, units, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: GRID
real, dimension(:,:), pointer :: coord
character(len=*), intent(in) :: name
type(ESMF_StaggerLoc) :: location
integer :: units
integer, optional :: rc
Calls
Called by
Source Code
subroutine GridCoordGet(GRID, coord, name, Location, Units, rc)
  !ARGUMENTS:
   type(ESMF_Grid),   intent(INout ) :: GRID
   real, dimension(:,:), pointer  :: coord
   character (len=*) , intent(IN) :: name
   type(ESMF_StaggerLoc)          :: location
   integer                        :: units
   integer, optional              :: rc
 !EOP
   !local variables
  integer                   :: rank
  type(ESMF_CoordSys_Flag)  :: crdSys
  type(ESMF_TypeKind_Flag)  :: tk
  integer                   :: counts(ESMF_MAXDIM)
  integer                   :: crdOrder
  real(ESMF_KIND_R4), pointer :: r4d2(:,:)
  real(ESMF_KIND_R8), pointer :: r8d2(:,:)
  real(ESMF_KIND_R8)        :: conv2rad
  integer                   :: STATUS
  integer                   :: i
  integer                   :: j
!ALT  integer                   :: i1, in, j1, jn
  integer                   :: coordDimCount(ESMF_MAXDIM)
  character(len=ESMF_MAXSTR):: gridname
  _UNUSED_DUMMY(Units)
  call ESMF_GridGet(grid, coordSys=crdSys, coordTypeKind=tk, &
          dimCount=rank, coordDimCount=coordDimCount, _RC)
  if (name == "Longitude") then
    crdOrder = 1
  else if (name == "Latitude") then
    crdOrder = 2
  else
   STATUS=ESMF_FAILURE
   _VERIFY(STATUS)
  endif
  call ESMF_GridGet(grid, name=gridname, _RC)
  if (gridname(1:10) == 'tile_grid_') then
     call MAPL_GridGet(GRID, localCellCountPerDim=counts, _RC)
     allocate(coord(counts(1), counts(2)), __STAT__)
     coord = 0.0 ! initialize just in case
     do concurrent (i=1:counts(1),j=1:counts(2))
        coord(i,j) =  merge(i,j,crdorder==1)
     end do
     coord = coord * (MAPL_PI_R8 / 180.d+0)
     _RETURN(ESMF_SUCCESS)
  end if
  if (crdSys == ESMF_COORDSYS_SPH_DEG) then
     conv2rad = MAPL_PI_R8 / 180._ESMF_KIND_R8
  else if (crdSys == ESMF_COORDSYS_SPH_RAD) then
     conv2rad = 1._ESMF_KIND_R8
  else
     _FAIL('Unsupported coordinate system:  ESMF_COORDSYS_CART')
  end if
  if (tk == ESMF_TYPEKIND_R4) then
     if (coordDimCount(crdOrder)==2) then
        call ESMF_GridGetCoord(grid, localDE=0, coordDim=crdOrder, &
             staggerloc=location, &
             computationalCount=COUNTS,  &
             farrayPtr=R4D2, _RC)
        allocate(coord(counts(1), counts(2)), __STAT__)
        coord = conv2rad * R4D2
     else
        _FAIL('Must have 2 gridded dimensions')
     endif
  else if (tk == ESMF_TYPEKIND_R8) then
     if (coordDimCount(crdOrder)==2) then
        call ESMF_GridGetCoord(grid, localDE=0, coordDim=crdOrder, &
             staggerloc=location, &
             computationalCount=COUNTS,  &
             farrayPtr=R8D2, _RC)
        allocate(coord(counts(1), counts(2)), __STAT__)
        coord = conv2rad * R8D2
     else
        _FAIL('Must have 2 gridded dimensions')
     endif
  else
     _FAIL('Invalid type kind')
  endif
  _RETURN(ESMF_SUCCESS)
 end subroutine GridCoordGet
Call graph
gridcoordget calls ESMF_GridGet, ESMF_GridGetCoord, mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
set calls gridcoordget
create_subobjects calls set
mapl_gridcreate calls set
activate_threading calls create_subobjects
initialize_ calls mapl_gridcreate
omp_driver calls activate_threading