grid_get_coords_1d – MAPL
grid_get_coords_1d Module Subroutine
20 statements
Source File
module subroutine grid_get_coords_1d(grid, longitudes, latitudes, rc) Interface →
Uses
iso_c_binding
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
real(kind=ESMF_KIND_R8), pointer :: longitudes(:)
real(kind=ESMF_KIND_R8), pointer :: latitudes(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine grid_get_coords_1d(grid, longitudes, latitudes, rc)
      use, intrinsic :: iso_c_binding, only: c_ptr, c_f_pointer, c_loc
      type(ESMF_Grid), intent(in) :: grid
      real(kind=ESMF_KIND_R8), pointer :: longitudes(:)
      real(kind=ESMF_KIND_R8), pointer :: latitudes(:)
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=ESMF_KIND_R8), dimension(:,:), pointer :: lons_2d, lats_2d
      type(c_ptr) :: loc
      call GridGetCoords(grid, lons_2d, lats_2d, _RC)
      associate (n => product(shape(lons_2d)))
        loc = c_loc(lons_2d)
        call c_f_pointer(loc, longitudes, [n])
        loc = c_loc(lats_2d)
        call c_f_pointer(loc, latitudes, [n])
      end associate
      _RETURN(ESMF_SUCCESS)
   end subroutine grid_get_coords_1d
Call graph
grid_get_coords_1d calls gridgetcoords, mapl_return, mapl_verify, grid_get_coords_1d
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
grid_get_centers calls grid_get_centers, gridgetcoords, mapl_return, mapl_verify
grid_get_coords_2d calls grid_get_coords_2d, mapl_return, mapl_verify, ESMF_GridGetCoord
get_error_message calls at, insert
mapl_throw_exception calls initialize
grid_get_corners calls gridgetcoords, grid_get_corners
mapl_geomgetcoords calls gridgetcoords, mapl_geomgetcoords
new_gridvectorbasis calls gridgetcoords, new_gridvectorbasis