gridcomp_get_outer_meta – MAPL
gridcomp_get_outer_meta Subroutine
22 statements
Source File
private recursive subroutine gridcomp_get_outer_meta(gridcomp, outer_meta, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(OuterMetaComponent), intent(out), pointer :: outer_meta
integer, intent(out), optional :: rc
Calls
Called by
Call graph
gridcomp_get_outer_meta calls get_outer_meta, mapl_gridcompgetoutermeta, mapl_gridcompisgeneric, get_outer_gridcomp, mapl_return, mapl_verify
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridcompisuser calls gridcomp_is_user
get_error_message calls at, insert
get_inner_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
get_outer_meta_from_outer_gc calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
gridcomp_is_generic calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsSet
mapl_throw_exception calls initialize
gridcomp_is_user calls mapl_gridcompisgeneric, mapl_return, mapl_verify
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta
mapl_addchild calls add_child_by_name
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic
mapl_connectall calls gridcomp_connect_all
mapl_gridcompget calls gridcomp_get
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
mapl_runchild calls run_child_by_name
mapl_runchildren calls run_children
setup calls mapl_gridcompsetverticalgeom
test_full_run_sequence calls mapl_gridcompsetverticalgeom