grid_get_centers – MAPL
grid_get_centers Module Subroutine
15 statements
Source File
module subroutine grid_get_centers(grid, centers, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
real(kind=ESMF_KIND_R8), intent(out), allocatable :: centers(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine grid_get_centers(grid, centers, rc)
      type(ESMF_Grid), intent(in) :: grid
      real(kind=ESMF_KIND_R8), allocatable, intent(out) :: centers(:,:,:)
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=ESMF_KIND_R8), pointer :: longitudes(:,:)
      real(kind=ESMF_KIND_R8), pointer :: latitudes(:,:)
      call GridGetCoords(grid, longitudes, latitudes, _RC)
      allocate(centers(size(longitudes,1),size(longitudes,2),2))
      centers(:,:,1) = longitudes
      centers(:,:,2) = latitudes
      _RETURN(ESMF_SUCCESS)
   end subroutine grid_get_centers
Call graph
grid_get_centers calls gridgetcoords, mapl_return, mapl_verify, grid_get_centers
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
grid_get_coords_1d calls grid_get_coords_1d, gridgetcoords, mapl_return, mapl_verify
grid_get_coords_2d calls grid_get_coords_2d, mapl_return, mapl_verify, ESMF_GridGetCoord
get_error_message calls at, insert
mapl_throw_exception calls initialize
grid_get_corners calls gridgetcoords, grid_get_corners
mapl_geomgetcoords calls gridgetcoords, mapl_geomgetcoords
new_gridvectorbasis calls gridgetcoords, new_gridvectorbasis