gridcomp_is_generic – MAPL
gridcomp_is_generic Function
18 statements
Source File
private function gridcomp_is_generic(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(in) :: gridcomp
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function gridcomp_is_generic(gridcomp, rc)
      type(ESMF_GridComp), intent(in) :: gridcomp
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Info) :: info
      logical :: found
      gridcomp_is_generic = .false.
      call ESMF_InfoGetFromHost(gridcomp, info, _RC)
      found = ESMF_InfoIsSet(info, key='MAPL/GRIDCOMP_IS_GENERIC', _RC)
      if (found) then
         call ESMF_InfoGet(info, key='MAPL/GRIDCOMP_IS_GENERIC', value=gridcomp_is_generic, _RC)
      end if
      _RETURN(_SUCCESS)
   end function gridcomp_is_generic
Call graph
gridcomp_is_generic calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_gridcompisgeneric calls gridcomp_is_generic
gridcomp_get_outer_meta calls mapl_gridcompisgeneric, mapl_gridcompgetoutermeta
gridcomp_is_user calls mapl_gridcompisgeneric
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_gridcompisuser calls gridcomp_is_user
add_child_by_name calls mapl_gridcompgetoutermeta
add_export_spec calls mapl_gridcompgetoutermeta
add_internal_spec calls mapl_gridcompgetoutermeta
add_spec_basic calls mapl_gridcompgetoutermeta
get_outer_gridcomp calls mapl_gridcompisuser
gridcomp_connect_all calls mapl_gridcompgetoutermeta
gridcomp_get calls mapl_gridcompgetoutermeta
gridcomp_set_entry_point calls mapl_gridcompgetoutermeta
mapl_gridcompsetgeom calls mapl_gridcompgetoutermeta
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta
run_child_by_name calls mapl_gridcompgetoutermeta
run_children calls mapl_gridcompgetoutermeta