grid_get_corners – MAPL
grid_get_corners Module Subroutine
24 statements
Source File
module subroutine grid_get_corners(grid, corners, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
real(kind=ESMF_KIND_R8), intent(out), allocatable :: corners(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine grid_get_corners(grid, corners, rc)
      type(ESMF_Grid), intent(inout) :: grid
      real(kind=ESMF_KIND_R8), allocatable, intent(out) :: corners(:,:,:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: im, jm
      real(kind=ESMF_KIND_R8), pointer :: longitudes(:,:)
      real(kind=ESMF_KIND_R8), pointer :: latitudes(:,:)
      real(kind=ESMF_KIND_R8), allocatable :: corner_lons(:,:)
      real(kind=ESMF_KIND_R8), allocatable :: corner_lats(:,:)
      call GridGetCoords(grid, longitudes, latitudes, _RC)
      im = size(longitudes,1)
      jm = size(longitudes,2)
      allocate(corner_lons(im+1,jm+1))
      allocate(corner_lats(im+1,jm+1))
      call MAPL_GridGetCorners(grid, corner_lons, corner_lats, _RC)
      allocate(corners(size(longitudes,1),size(longitudes,2),2))
      corners(:,:,1) = corner_lons
      corners(:,:,2) = corner_lats
      _RETURN(ESMF_SUCCESS)
   end subroutine grid_get_corners
Call graph
grid_get_corners calls gridgetcoords, mapl_gridgetcorners, mapl_return, mapl_verify, grid_get_corners
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
mapl_gridgetcorners calls mapl_gridgetcorners, mapl_return, mapl_verify, ESMF_FieldHalo, ESMF_FieldHaloRelease, ESMF_FieldHaloStore, ESMF_GridGet, ESMF_GridGetCoord, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoSet, esmf_fieldcreate, esmf_fielddestroy, mapl_assert, mapl_gridget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
grid_get_centers calls grid_get_centers
grid_get_coords_1d calls grid_get_coords_1d
grid_get_coords_2d calls grid_get_coords_2d
get_error_message calls at, insert
mapl_throw_exception calls initialize
gridgetcorners calls grid_get_corners
new_gridvectorbasis calls gridgetcorners, new_gridvectorbasis