handle_ModifyMetadata – MAPL
handle_ModifyMetadata Subroutine
16 statements
Source File
private subroutine handle_ModifyMetadata(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(ModifyMetadataMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine handle_ModifyMetadata(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (ModifyMetadataMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      type (HistoryCollection),pointer :: hist_collection
      class(AbstractSocket),pointer :: connection
      type (DummyMessage) :: handshake_msg
      integer :: status
      hist_collection=>this%hist_collections%at(message%collection_id)
      call hist_collection%ModifyMetadata(message%var_map)
      connection=>this%get_connection()
      call connection%send(handshake_msg,_RC)
      _RETURN(_SUCCESS)
   end subroutine handle_ModifyMetadata
Call graph
handle_modifymetadata calls at, get_connection, mapl_return, mapl_verify, modifymetadata, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modifymetadata calls mapl_return, mapl_verify, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, modify_variable
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_throw_exception calls initialize
modify_variable calls mapl_return, mapl_assert, at, begin, get, next, get_dimensions, map_set_
v_at_32 calls v_at_size_kind