has_item_spec_actual – MAPL
has_item_spec_actual Function
5 statements
Source File
private function has_item_spec_actual(this, actual_pt) result(has_item_spec)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in) :: this
type(ActualConnectionPt), intent(in) :: actual_pt
Return Value logical
Called by
Source Code
   logical function has_item_spec_actual(this, actual_pt) result(has_item_spec)
      class(HierarchicalRegistry), intent(in) :: this
      type(ActualConnectionPt), intent(in) :: actual_pt
      has_item_spec = (this%actual_specs_map%count(actual_pt) > 0)
   end function has_item_spec_actual
Call graph
add_item_spec_actual calls has_item_spec, link_item_spec_actual
connect_export_to_export calls has_item_spec
link_item_spec_actual calls has_item_spec
link_item_spec_virtual calls has_item_spec
test_do_not_propagate_import calls has_item_spec
test_e2e_preserve_actual_pt calls has_item_spec
test_internal_to_export_connection calls has_item_spec
test_propagate_import calls has_item_spec
connect calls connect_export_to_export
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual