has_level – MAPL
has_level Function
12 statements
Source File
function has_level(grid, rc) result(grid_has_level)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function has_level(grid,rc) result(grid_has_level)
      logical :: grid_has_level
      type(ESMF_Grid), intent(in) :: grid
      integer, intent(out), optional :: rc
      integer :: status, global_dims(3)
      call MAPL_GridGet(grid,globalCellCountPerDim=global_dims,_RC)
      grid_has_level = (global_dims(3)>0)
      if (present(rc)) then
         RC=_SUCCESS
      end if
   end function has_level
Call graph
has_level calls mapl_abort, mapl_gridget, mapl_verify
mapl_abort calls mpi_abort
mapl_gridget calls mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde, mapl_return
mapl_verify calls mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_verify, mapl_return, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_verify, ESMF_DistGridGet, ESMF_GridGet, mapl_return, ESMF_DELayoutGet
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
time_ave calls has_level