has_variable – MAPL
has_variable Function
14 statements
Source File
private function has_variable(this, var_name, unusable, rc) result(has)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function has_variable(this, var_name, unusable, rc) result(has)
      class (FileMetadata), target, intent(in) :: this
      character(len=*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class (Variable), pointer :: var
      has = (this%variables%count(var_name) > 0)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function has_variable
Call graph
has_variable calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
is_var_present calls has_variable
stage2dlatlon calls has_variable
bundlepost calls stage2dlatlon
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file