has_subregistry – MAPL
has_subregistry Function
5 statements
Source File
private function has_subregistry(this, name)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in) :: this
character(len=*), intent(in) :: name
Return Value logical
Called by
Source Code
   logical function has_subregistry(this, name)
      class(HierarchicalRegistry), intent(in) :: this
      character(len=*), intent(in) :: name
      has_subregistry = (this%subregistries%count(name) > 0)
   end function has_subregistry
Call graph
add_subregistry calls has_subregistry
test_connect calls add_subregistry
test_connect_chain calls add_subregistry
test_do_not_propagate_import calls add_subregistry
test_e2e_preserve_actual_pt calls add_subregistry
test_export_to_export_connection calls add_subregistry
test_get_subregistry calls add_subregistry
test_get_subregistry_fail_not_found calls add_subregistry
test_import_from_child calls add_subregistry
test_import_from_parent calls add_subregistry
test_multi_import calls add_subregistry
test_propagate_import calls add_subregistry
test_sibling_activation calls add_subregistry