has_logger – MAPL
has_logger Function
4 statements
Source File
private function has_logger(this)
Type Bound
HConfigParams
Arguments
Type Intent Optional Attributes Name
class(HConfigParams), intent(in) :: this
Return Value logical
Called by
Source Code
   logical function has_logger(this)
      class(HConfigParams), intent(in) :: this
      has_logger = associated(this%logger)
   end function has_logger
Call graph
get_value_i4 calls has_logger, log_message
get_value_i4seq calls has_logger, log_message
get_value_i8 calls has_logger, log_message
get_value_i8seq calls has_logger, log_message
get_value_logical calls has_logger, log_message
get_value_logical_seq calls has_logger, log_message
get_value_r4 calls has_logger, log_message
get_value_r4seq calls has_logger, log_message
get_value_r8 calls has_logger, log_message
get_value_r8seq calls has_logger, log_message
get_value_string calls has_logger, log_message
log_message calls has_logger
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string