hconfig_to_esmf_timeinterval – MAPL
hconfig_to_esmf_timeinterval Function
16 statements
Source File
public function hconfig_to_esmf_timeinterval(hconfig, key, unusable, rc) result(time_interval)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
character(len=*), intent(in) :: key
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_TimeInterval)
Calls
Called by
Source Code
   function hconfig_to_esmf_timeinterval(hconfig, key, unusable, rc) result(time_interval)
      type(ESMF_TimeInterval) :: time_interval
      type(ESMF_HConfig), intent(in) :: hconfig
      character(len=*), intent(in) :: key
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=:), allocatable :: iso_duration
      _UNUSED_DUMMY(unusable)
      iso_duration = ESMF_HConfigAsString(hconfig, keystring=key, _RC)
      time_interval = string_to_esmf_timeinterval(iso_duration, _RC)
      _RETURN(_SUCCESS)
   end function hconfig_to_esmf_timeinterval
Call graph
hconfig_to_esmf_timeinterval calls esmf_hconfigasstring, mapl_return, mapl_verify, string_to_esmf_timeinterval
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_to_esmf_timeinterval calls mapl_return, mapl_verify, ESMF_TimeIntervalSet, mapl_assert
create_output_alarm calls hconfig_to_esmf_timeinterval
mapl_run_driver calls hconfig_to_esmf_timeinterval
run_geos calls mapl_run_driver
test_create_output_alarm calls create_output_alarm
geos calls run_geos