HistoryCollectionVector_deserialize – MAPL
HistoryCollectionVector_deserialize Subroutine
18 statements
Source File
public subroutine HistoryCollectionVector_deserialize(buffer, histVec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(HistoryCollectionVector), intent(inout) :: histVec
Calls
Call graph
historycollectionvector_deserialize calls deserialize_intrinsic, push_back, filemetadata_deserialize
filemetadata_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, stringintegermap_deserialize, stringvariablemap_deserialize, stringvector_deserialize, variable_deserialize
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
stringintegermap_deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return, insert, stringintegermap
stringvariablemap_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, variable_deserialize, insert, coordinatevariable_deserialize
stringvector_deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return, push_back, stringvector
variable_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, stringvector_deserialize, stringattributemap_deserialize, unlimitedentity_deserialize
coordinatevariable_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, variable_deserialize
stringattributemap_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, insert, attribute_deserialize
unlimitedentity_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, get_rank, set