initialize – MAPL
initialize Subroutine
13 statements
Source File
public subroutine initialize(unusable, comm, logging_config, logger_name, rc)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
character(len=*), intent(in), optional :: logging_config
character(len=*), intent(in), optional :: logger_name
integer, intent(out), optional :: rc
Called by
Source Code
   subroutine initialize(unusable, comm, logging_config, logger_name, rc)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      character(len=*), optional,intent(in) :: logging_config
      character(len=*), optional,intent(in) :: logger_name
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(comm)
      _UNUSED_DUMMY(logging_config)
      _UNUSED_DUMMY(logger_name)
      _RETURN(_SUCCESS)
   end subroutine initialize
Call graph
initialize calls initialize
mapl_initialize calls initialize
geos calls initialize
main calls initialize, mapl_initialize
newextdatadriver calls mapl_initialize
time_ave calls mapl_initialize
ut_regridding calls mapl_initialize
extdatadriver calls newextdatadriver
comp_testing_driver calls main
regrid_util calls main