initialize_post_advertise – MAPL
initialize_post_advertise Subroutine
27 statements
Source File
private recursive subroutine initialize_post_advertise(this, importState, exportState, clock, unusable, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  recursive subroutine initialize_post_advertise(this, importState, exportState, clock, unusable, rc)
      class(OuterMetaComponent), intent(inout) :: this
      ! optional arguments
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(*), parameter :: PHASE_NAME = 'GENERIC::INIT_POST_ADVERTISE'
      type(MultiState) :: outer_states, user_states
      call this%run_custom(ESMF_METHOD_INITIALIZE, PHASE_NAME, _RC)
      user_states = this%user_gc_driver%get_states()
      call this%registry%add_to_states(user_states, mode='user', _RC)
      outer_states = MultiState(importState=importState, exportState=exportState)
      call this%registry%add_to_states(outer_states, mode='outer', _RC)
      call recurse(this, phase_idx=GENERIC_INIT_POST_ADVERTISE, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine initialize_post_advertise
Call graph
initialize_post_advertise calls get_states, recurse, add_to_states, mapl_return, mapl_verify, run_custom
get_states calls get_states
recurse calls recurse_
add_to_states calls mapl_return, mapl_verify, add_to_state, mapl_assert, is_represented_in, map_begin, map_iter_first, map_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_custom calls mapl_return, mapl_verify, finalize, get_phase_index, initialize, mapl_assert, run, get_phases
initialize calls initialize_post_advertise