initialize_field – MAPL
initialize_field Subroutine
33 statements
Source File
public subroutine initialize_field(field, typekind, grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
type(ESMF_TypeKind_Flag), intent(in) :: typekind
type(ESMF_Grid), intent(inout), optional :: grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_field(field, typekind, grid, rc)
      type(ESMF_Field), intent(inout) :: field
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      type(ESMF_Grid), optional, intent(inout) :: grid
      integer, optional, intent(out) :: rc
      type(ESMF_Grid) :: grid_
      logical :: grid_created
      integer :: status
      grid_created = .FALSE.
      if(present(grid)) then
         grid_created = ESMF_GridIsCreated(grid, _RC)
         if(grid_created) grid_ = grid
      end if
      if(.not. grid_created) then
         grid_ = ESMF_GridCreateNoPeriDimUfrm(maxIndex=MAX_INDEX, &
            & minCornerCoord=MIN_CORNER_COORD, maxCornerCoord=MAX_CORNER_COORD, _RC)
      end if
      field = ESMF_FieldCreate(grid=grid_, typekind=typekind, _RC)
      if(present(grid)) grid = grid_
      _RETURN(_SUCCESS)
   end subroutine initialize_field
Call graph
initialize_field calls ESMF_GridCreateNoPeriDimUfrm, ESMF_GridIsCreated, anyexceptions, assert_that, esmf_fieldcreate, sourcelocation
test_accumulate calls initialize_field
test_accumulate_mean_r4 calls initialize_field
test_accumulate_r4 calls initialize_field
test_accumulate_with_undef_some_steps calls initialize_field
test_max_accumulate_r4 calls initialize_field
test_min_accumulate_r4 calls initialize_field