initialize_geom – MAPL
initialize_geom Subroutine
38 statements
Source File
private recursive subroutine initialize_geom(this, unusable, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine initialize_geom(this, unusable, rc)
      class(OuterMetaComponent), intent(inout) :: this
      ! optional arguments
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type(MaplGeom), pointer :: mapl_geom
      character(*), parameter :: PHASE_NAME = 'GENERIC::INIT_GEOM'
      type(GeomManager), pointer :: geom_mgr
      if (this%component_spec%has_geom_hconfig()) then
         geom_mgr => get_geom_manager()
         mapl_geom => geom_mgr%get_mapl_geom(this%component_spec%geom_hconfig, _RC)
         this%geom = mapl_geom%get_geom()
      end if
      call this%run_custom(ESMF_METHOD_INITIALIZE, PHASE_NAME, _RC)
      call apply_to_children(this, set_child_geom, _RC)
      call recurse(this, phase_idx=GENERIC_INIT_GEOM, _RC)
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine set_child_geom(this, child_meta, rc)
         class(OuterMetaComponent), target, intent(inout) :: this
         type(OuterMetaComponent), target, intent(inout) ::  child_meta
         integer, optional, intent(out) :: rc
         integer :: status
         if (allocated(this%geom)) then
            call child_meta%set_geom(this%geom)
         end if
         if (allocated(this%vertical_geom)) then
            call child_meta%set_vertical_geom(this%vertical_geom)
         end if
         _RETURN(ESMF_SUCCESS)
      end subroutine set_child_geom
   end subroutine initialize_geom
Call graph
initialize_geom calls get_geom, get_geom_manager, get_mapl_geom, apply_to_children, recurse, has_geom_hconfig, mapl_return, mapl_verify, run_custom
apply_to_children calls apply_to_children_custom
recurse calls recurse_
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_custom calls mapl_return, mapl_verify, finalize, get_phase_index, initialize, mapl_assert, run, get_phases
initialize calls initialize_geom