initialize_phases – MAPL
initialize_phases Subroutine
18 statements
Source File
public recursive subroutine initialize_phases(this, unusable, phases, rc)
Arguments
Type Intent Optional Attributes Name
class(ComponentDriver), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: phases(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      recursive subroutine initialize_phases(this, unusable, phases, rc)
         class(ComponentDriver), intent(inout) :: this
         class(KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(in) :: phases(:)
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: i
         do i = 1, size(phases)
            call this % initialize(phase_idx=phases(i), _RC)
         end do
         _RETURN(_SUCCESS)
         _UNUSED_DUMMY(unusable)
      end subroutine initialize_phases
Call graph
initialize_phases calls initialize, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_run_driver calls initialize_phases
test_child_call_frequency calls initialize_phases
test_child_call_frequency_with_offset calls initialize_phases
test_default_timestep calls initialize_phases
test_double_timestep calls initialize_phases
run_geos calls mapl_run_driver
geos calls run_geos