initialize_realize – MAPL
initialize_realize Subroutine
20 statements
Source File
private recursive subroutine initialize_realize(this, unusable, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine initialize_realize(this, unusable, rc)
      class(OuterMetaComponent), intent(inout) :: this
      ! optional arguments
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(*), parameter :: PHASE_NAME = 'GENERIC::INIT_REALIZE'
      call this%run_custom(ESMF_METHOD_INITIALIZE, PHASE_NAME, _RC)
      call recurse(this, phase_idx=GENERIC_INIT_REALIZE, _RC)
      call this%registry%allocate(_RC)
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(unusable)
   contains
   end subroutine initialize_realize
Call graph
initialize_realize calls recurse, mapl_return, mapl_verify, run_custom
recurse calls recurse_
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_custom calls mapl_return, mapl_verify, finalize, get_phase_index, initialize, mapl_assert, run, get_phases
finalize calls finalize
get_phase_index calls get_phase_index_
initialize calls initialize, initialize_realize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
run calls run
get_error_message calls at, insert
get_phases calls map_of
mapl_throw_exception calls initialize
recurse_ calls mapl_return, mapl_verify, initialize, omap_ftn_begin, omap_ftn_end, omap_iter_next