initialize_ioserver – MAPL
initialize_ioserver Subroutine
5 statements
Source File
subroutine initialize_ioserver(comm)
initialize_ioserver – Initialize the IO Server using the command line options
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
Calls
Called by
Source Code
   subroutine initialize_ioserver(comm)
      integer, intent(in) :: comm
      call ioserver_manager%initialize(comm, &
                    application_size     = cap_options%npes_model, &
                    nodes_input_server   = cap_options%nodes_input_server, &
                    nodes_output_server  = cap_options%nodes_output_server, &
                    npes_input_server    = cap_options%npes_input_server, &
                    npes_output_server   = cap_options%npes_output_server, &
                    oserver_type         = cap_options%oserver_type, &
                    npes_backend_pernode = cap_options%npes_backend_pernode, &
                    isolate_nodes        = cap_options%isolate_nodes, &
                    fast_oclient         = cap_options%fast_oclient, &
                    with_profiler        = cap_options%with_io_profiler, &
                 rc=status)
      _VERIFY(status)
   end subroutine initialize_ioserver
Call graph
initialize_ioserver calls initialize, mapl_abort, mapl_verify
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
main calls initialize_ioserver