init_geom – MAPL
init_geom Subroutine
17 statements
Source File
private subroutine init_geom(gridcomp, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   subroutine init_geom(gridcomp, importState, exportState, clock, rc)
      type(ESMF_GridComp)   :: gridcomp
      type(ESMF_State)      :: importState
      type(ESMF_State)      :: exportState
      type(ESMF_Clock)      :: clock
      integer, intent(out)  :: rc
      integer :: status
      type(ESMF_HConfig) :: hconfig
      type(ESMF_Geom) :: geom
      call MAPL_GridCompGet(gridcomp, hconfig=hconfig, _RC)
      geom = make_geom(hconfig)
      call MAPL_GridCompSetGeom(gridcomp, geom, _RC)
      _RETURN(_SUCCESS)
   end subroutine init_geom
Call graph
init_geom calls mapl_gridcompget, mapl_gridcompsetgeom, make_geom, mapl_return, mapl_verify
mapl_gridcompget calls gridcomp_get
make_geom calls mapl_return, mapl_verify, ESMF_HConfigDestroy, esmf_hconfigcreateat, get_geom, get_geom_manager, get_mapl_geom
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get calls mapl_return, mapl_verify, mapl_gridcompgetoutermeta, get_hconfig, get_lgr, get_registry
mapl_throw_exception calls initialize
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta