init_meta – MAPL
init_meta Subroutine
12 statements
Source File
private subroutine init_meta(this, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init_meta(this, rc)
      class(OuterMetaComponent), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: user_gc_name
      user_gc_name = this%user_gc_driver%get_name(_RC)
      this%registry = HierarchicalRegistry(user_gc_name)
      this%lgr => logging%get_logger('MAPL.GENERIC')
      _RETURN(_SUCCESS)
   end subroutine init_meta
Call graph
init_meta calls get_logger, get_name, mapl_return, mapl_verify
get_name calls mapl_return, mapl_verify, ESMF_GridCompGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_grid_comp_primary calls init_meta
create_grid_comp calls create_grid_comp_primary
add_child_by_name calls create_grid_comp, add_child_by_name
make_driver calls create_grid_comp
setup calls create_grid_comp
test_is_generic calls create_grid_comp
test_mapl_invalid_name calls create_grid_comp
mapl_run_driver calls make_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
test_wasfinal calls setup
test_wasinit calls setup
test_wasrun_1 calls setup
test_wasrun_extra calls setup