initialize – MAPL
initialize Subroutine
37 statements
Source File
public subroutine initialize(path, encoding, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: path
integer(kind=ut_encoding), intent(in), optional :: encoding
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize(path, encoding, rc)
      character(len=*), optional, intent(in) :: path
      integer(ut_encoding), optional, intent(in) :: encoding
      integer, optional, intent(out) :: rc
      integer :: status
      _RETURN_UNLESS(instance_is_uninitialized())
      ! System must be once and only once.
      _ASSERT(instance_is_uninitialized(), UTF_DUPLICATE_INITIALIZATION)
      ! Disable error messages from udunits2
      call disable_ut_error_message_handler()
      call initialize_system(SYSTEM_INSTANCE, path, encoding, rc=status)
      if(status /= UT_SUCCESS) then
         ! On failure, free memory
         call finalize()
         _RETURN(UTF_INITIALIZATION_FAILURE)
      end if
      _ASSERT(.not. SYSTEM_INSTANCE%is_free(), UTF_NOT_INITIALIZED)
      _RETURN(UT_SUCCESS)
   end subroutine initialize
Call graph
initialize calls ut_set_ignore_error_message_handler, is_free, finalize, initialize
finalize calls is_free