initialize_from_esmf_distGrid – MAPL
initialize_from_esmf_distGrid Subroutine
32 statements
Source File
private subroutine initialize_from_esmf_distGrid(this, dist_grid, lon_array, lat_array, unusable, rc)
Uses
MAPL_ConfigMod
MAPL_Constants
Type Bound
XYGridFactory
Arguments
Type Intent Optional Attributes Name
class(XYGridFactory), intent(inout) :: this
type(ESMF_DistGrid), intent(in) :: dist_grid
type(ESMF_LocalArray), intent(in) :: lon_array
type(ESMF_LocalArray), intent(in) :: lat_array
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_from_esmf_distGrid(this, dist_grid, lon_array, lat_array, unusable, rc)
      use MAPL_ConfigMod
      use MAPL_Constants, only: PI => MAPL_PI_R8
      class (XYGridFactory), intent(inout)  :: this
      type (ESMF_DistGrid), intent(in) :: dist_grid
      type (ESMF_LocalArray), intent(in) :: lon_array
      type (ESMF_LocalArray), intent(in) :: lat_array
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME // 'initialize_from_esmf_distGrid'
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(dist_grid)
      _UNUSED_DUMMY(lon_array)
      _UNUSED_DUMMY(lat_array)
      ! not supported
      _FAIL("XY initialize from distgrid non supported")
   end subroutine initialize_from_esmf_distGrid
Call graph
initialize_from_esmf_distgrid calls mapl_assert, initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_from_config calls initialize
initialize_from_config_file calls initialize
make_factory_from_config calls initialize
make_factory_from_distgrid calls initialize
make_factory_from_file calls initialize
setup calls initialize
find_ calls make_factory
make_grid_from_config calls make_factory
make_grid_from_distgrid calls make_factory
mapl_esmfstatereadfromfile calls make_factory
time_ave calls make_factory