initialize_global_memory_profiler – MAPL
initialize_global_memory_profiler Subroutine
13 statements
Source File
public subroutine initialize_global_memory_profiler(name, unusable, comm, enabled, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
logical, intent(in), optional :: enabled
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_global_memory_profiler(name, unusable, comm, enabled, rc)
      character(*), intent(in) :: name
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      logical, optional, intent(in) :: enabled
      integer, optional, intent(out) :: rc
      integer :: status
      call initialize_global_profiler(global_memory_profiler, MallocGauge(), name, comm=comm, enabled=enabled, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine initialize_global_memory_profiler
Call graph
initialize_global_memory_profiler calls initialize_global_profiler, mapl_return, mapl_verify
initialize_global_profiler calls mapl_return, mapl_verify, start
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return
initialize calls initialize_global_memory_profiler
run calls initialize
extdata_driver calls run