initialize – MAPL
initialize Subroutine
17 statements
Source File
public subroutine initialize(path, encoding, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: path
integer(kind=ut_encoding), intent(in), optional :: encoding
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize(path, encoding, rc)
      character(len=*), optional, intent(in) :: path
      integer(ut_encoding), optional, intent(in) :: encoding
      integer, optional, intent(out) :: rc
      integer :: status
      ! System must be initialized once and only once.
      _ASSERT_RC(instance_is_uninitialized(), 'UDSystem is initialized already.', UTF_INITIALIZATION_FAILURE)
      ! Disable error messages from udunits2
      call disable_ut_error_message_handler()
      call initialize_system(SYSTEM_INSTANCE, path, encoding, rc=status)
      if(.not. is_ut_success(status)) then
         ! On failure, free memory
         call finalize()
         _RETURN(_FAILURE)
      end if
      _ASSERT_RC(.not. SYSTEM_INSTANCE%is_free(), 'Failed to initialize UDSystem', UTF_NOT_INITIALIZED)
      _RETURN(_SUCCESS)
   end subroutine initialize
Call graph
initialize calls mapl_assert, ut_set_ignore_error_message_handler, is_free, finalize, mapl_return, initialize
finalize calls is_free
mapl_return calls at, insert, mapl_throw_exception