initialize_global_profiler – MAPL
initialize_global_profiler Subroutine
23 statements
Source File
private subroutine initialize_global_profiler(profiler, gauge, name, unusable, comm, enabled, rc)
$ profiler = DistributedProfiler(name, gauge, comm=comm)
$ profiler = StubProfiler(name)
Arguments
Type Intent Optional Attributes Name
class(DistributedProfiler), intent(inout), allocatable :: profiler
class(AbstractGauge), intent(in) :: gauge
character(len=*), intent(in) :: name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
logical, intent(in), optional :: enabled
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_global_profiler(profiler, gauge, name, unusable, comm, enabled, rc)
      class(DistributedProfiler), allocatable, intent(inout) :: profiler
      class(AbstractGauge), intent(in) :: gauge
      character(*), intent(in) :: name
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      logical, optional, intent(in) :: enabled
      integer, optional, intent(out) :: rc
      logical :: enabled_
      integer :: status
      enabled_ = .false.
      if (present(enabled)) enabled_ = enabled
      if (enabled_) then
!!$         profiler = DistributedProfiler(name, gauge, comm=comm)
         ! Compiler workaround for ifort 2021.3
         allocate(profiler, source=DistributedProfiler(name, gauge, comm=comm))
      else
!!$         profiler = StubProfiler(name)
         ! Compiler workaround for ifort 2021.3
         allocate(profiler, source=StubProfiler(name))
      end if
      call profiler%start(_RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine initialize_global_profiler
Call graph
initialize_global_profiler calls start, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return
initialize_global_memory_profiler calls initialize_global_profiler
initialize_global_time_profiler calls initialize_global_profiler
initialize calls initialize_global_memory_profiler, initialize_global_time_profiler
run calls initialize
extdata_driver calls run