initialize_from_file_metadata – MAPL
initialize_from_file_metadata Subroutine
213 statements
Source File
private subroutine initialize_from_file_metadata(this, file_metadata, unusable, force_file_coordinates, rc)
Uses
mapl_KeywordEnforcerMod
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(inout) :: this
type(FileMetadata), intent(in), target :: file_metadata
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: force_file_coordinates
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_file_metadata(this, file_metadata, unusable, force_file_coordinates, rc)
      use MAPL_KeywordEnforcerMod
      use MAPL_BaseMod, only: MAPL_DecomposeDim
      class (LatLonGridFactory), intent(inout)  :: this
      type (FileMetadata), target, intent(in) :: file_metadata
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in) :: force_file_coordinates
      integer, optional, intent(out) :: rc
      integer :: status
      class (CoordinateVariable), pointer :: v
      class (*), pointer :: ptr(:)
      character(:), allocatable :: lon_name
      character(:), allocatable :: lat_name
      character(:), allocatable :: lev_name
      integer :: i
      logical :: hasLon, hasLat, hasLongitude, hasLatitude, hasLev,hasLevel,regLat,regLon
      real(kind=REAL64) :: del12,delij
      integer :: i_min, i_max
      real(kind=REAL64) :: d_lat, d_lat_temp, extrap_lat
      logical :: is_valid, use_file_coords, compute_lons, compute_lats
      _UNUSED_DUMMY(unusable)
      if (present(force_file_coordinates)) then
         use_file_coords = force_file_Coordinates
      else
         use_file_coords = .false.
      end if
      ! Cannot assume that lats and lons are evenly spaced
      this%is_regular = .false.
      associate (im => this%im_world, jm => this%jm_world, lm => this%lm)
         lon_name = 'lon'
         hasLon = file_metadata%has_dimension(lon_name)
         if (hasLon) then
            im = file_metadata%get_dimension(lon_name, rc=status)
            _VERIFY(status)
         else
            lon_name = 'longitude'
            hasLongitude = file_metadata%has_dimension(lon_name)
            if (hasLongitude) then
               im = file_metadata%get_dimension(lon_name, rc=status)
               _VERIFY(status)
            else
               _FAIL('no longitude coordinate')
            end if
         end if
         lat_name = 'lat'
         hasLat = file_metadata%has_dimension(lat_name)
         if (hasLat) then
            jm = file_metadata%get_dimension(lat_name, rc=status)
            _VERIFY(status)
         else
            lat_name = 'latitude'
            hasLatitude = file_metadata%has_dimension(lat_name)
            if (hasLatitude) then
               jm = file_metadata%get_dimension(lat_name, rc=status)
               _VERIFY(status)
            else
               _FAIL('no latitude coordinate')
            end if
         end if
         hasLev=.false.
         hasLevel=.false.
         lev_name = 'lev'
         hasLev = file_metadata%has_dimension(lev_name)
         if (hasLev) then
            lm = file_metadata%get_dimension(lev_name,rc=status)
            _VERIFY(status)
         else
            lev_name = 'levels'
            hasLevel = file_metadata%has_dimension(lev_name)
            if (hasLevel) then
               lm = file_metadata%get_dimension(lev_name,rc=status)
               _VERIFY(status)
            end if
         end if
        ! TODO: if 'lat' and 'lon' are not present then
        ! assume ... pole/dateline are ?
        ! TODO: check radians vs degrees.  Assume degrees for now.
        ! TODO: modify CoordinateVariable so that get_coordinate_data() is overloaded
        ! for different types (as subroutine) to avoid casting here.
        ! TODO: add get_coordinate_variable() interface to avoid the need to cast
        v => file_metadata%get_coordinate_variable(lon_name, rc=status)
        _VERIFY(status)
        ptr => v%get_coordinate_data()
        _ASSERT(associated(ptr),'coordinate data not allocated')
        select type (ptr)
        type is (real(kind=REAL64))
           this%lon_centers = ptr
        type is (real(kind=REAL32))
           this%lon_centers = ptr
        class default
           _FAIL('unsuppoted type of data; must be REAL32 or REAL64')
        end select
        if (any((this%lon_centers(2:im)-this%lon_centers(1:im-1))<0)) then
           where(this%lon_centers > 180) this%lon_centers=this%lon_centers-360
        end if
        v => file_metadata%get_coordinate_variable(lat_name, rc=status)
        _VERIFY(status)
        ptr => v%get_coordinate_data()
        _ASSERT(associated(ptr),'coordinate data not allocated')
        select type (ptr)
        type is (real(kind=REAL64))
           this%lat_centers = ptr
        type is (real(kind=REAL32))
           this%lat_centers = ptr
        class default
           _FAIL('unsupported type of data; must be REAL32 or REAL64')
        end select
        ! Check: is this a "mis-specified" pole-centered grid?
        if (size(this%lat_centers) >= 4) then
           ! Assume lbound=1 and ubound=size for now
           i_min = 1 !lbound(this%lat_centers)
           i_max = size(this%lat_centers) !ubound(this%lat_centers)
           d_lat = (this%lat_centers(i_max-1) - this%lat_centers(i_min+1))/&
                    (size(this%lat_centers)-3)
           is_valid = .True.
           ! Check: is this a regular grid (i.e. constant spacing away from the poles)?
           do i=(i_min+1),(i_max-2)
              d_lat_temp = this%lat_centers(i+1) - this%lat_centers(i)
              is_valid = (is_valid.and.(abs((d_lat_temp/d_lat)-1.0) < 1.0e-5))
              if (.not. is_valid) then
                 exit
              end if
           end do
           if (is_valid) then
              ! Should the southernmost point actually be at the pole?
              extrap_lat = this%lat_centers(i_min+1) - d_lat
              if (extrap_lat <= ((d_lat/20.0)-90.0)) then
                 this%lat_centers(i_min) = -90.0
              end if
              ! Should the northernmost point actually be at the pole?
              extrap_lat = this%lat_centers(i_max-1) + d_lat
              if (extrap_lat >= (90.0-(d_lat/20.0))) then
                 this%lat_centers(i_max) =  90.0
              end if
           end if
        end if
         ! Corners are the midpoints of centers (and extrapolated at the
         ! poles for lats.)
         allocate(this%lon_corners(im+1), this%lat_corners(jm+1))
         this%lon_corners(1) = (this%lon_centers(im) + this%lon_centers(1))/2 - 180
         this%lon_corners(2:im) = (this%lon_centers(1:im-1) + this%lon_centers(2:im))/2
         this%lon_corners(im+1) = (this%lon_centers(im) + this%lon_centers(1))/2 + 180
         ! This section about pole/dateline is probably not needed in file data case.
         if (abs(this%lon_centers(1) + 180) < 1000*epsilon(1.0)) then
            this%dateline = 'DC'
         else if (abs(this%lon_centers(1)) < 1000*epsilon(1.0)) then
            this%dateline = 'GC'
         else if (abs(this%lon_corners(1) + 180) < 1000*epsilon(1.0)) then
            this%dateline = 'DE'
         else if (abs(this%lon_corners(1)) < 1000*epsilon(1.0)) then
            this%dateline = 'GE'
         else ! assume 'XY'
            this%dateline = 'XY'
            this%lon_range = RealMinMax(this%lon_centers(1), this%lon_centers(jm))
         end if
         this%lat_corners(1) = this%lat_centers(1) - (this%lat_centers(2)-this%lat_centers(1))/2
         this%lat_corners(2:jm) = (this%lat_centers(1:jm-1) + this%lat_centers(2:jm))/2
         this%lat_corners(jm+1) = this%lat_centers(jm) - (this%lat_centers(jm-1)-this%lat_centers(jm))/2
         if (abs(this%lat_centers(1) + 90) < 1000*epsilon(1.0)) then
            this%pole = 'PC'
         else if (abs(this%lat_corners(1) + 90) < 1000*epsilon(1.0)) then
            this%pole = 'PE'
         else ! assume XY
            this%pole = 'XY'
            this%lat_range = RealMinMax(this%lat_centers(1), this%lat_centers(jm))
         end if
         if (this%lat_corners(1) < -90) this%lat_corners(1)=-90
         if (this%lat_corners(jm+1) > 90) this%lat_corners(jm+1)=90
         ! check if evenly spaced
         regLon=.true.
         do i=2,size(this%lon_centers)
            del12=this%lon_centers(2)-this%lon_centers(1)
            delij=this%lon_centers(i)-this%lon_centers(i-1)
            if ((del12-delij)>epsilon(1.0)) regLon=.false.
         end do
         regLat=.true.
         do i=2,size(this%lat_centers)
            del12=this%lat_centers(2)-this%lat_centers(1)
            delij=this%lat_centers(i)-this%lat_centers(i-1)
            if ((del12-delij)>epsilon(1.0)) regLat=.false.
         end do
         this%is_regular = (regLat .and. regLon)
         if (use_file_coords) then
            this%is_regular = .false.
            this%lon_centers = MAPL_DEGREES_TO_RADIANS_R8 * this%lon_centers
            this%lat_centers = MAPL_DEGREES_TO_RADIANS_R8 * this%lat_centers
            this%lon_corners = MAPL_DEGREES_TO_RADIANS_R8 * this%lon_corners
            this%lat_corners = MAPL_DEGREES_TO_RADIANS_R8 * this%lat_corners
         else
            compute_lons=.false.
            compute_lats=.false.
            if (regLon .and. (this%dateline.ne.'XY')) then
               compute_lons=.true.
            end if
            if (regLat .and. (this%pole.ne.'XY')) then
               compute_lats=.true.
            end if
            if (compute_lons .and. compute_lats) then
               this%lon_centers = this%compute_lon_centers(this%dateline, rc=status)
               _VERIFY(status)
               this%lon_centers_degrees = this%compute_lon_centers(this%dateline, &
                      convert_to_radians=.false., rc=status)
               _VERIFY(status)
               this%lon_corners = this%compute_lon_corners(this%dateline, rc=status)
               _VERIFY(status)
               this%lat_centers_degrees = this%compute_lat_centers(this%pole, &
                      convert_to_radians=.false., rc=status)
               this%lat_centers = this%compute_lat_centers(this%pole, rc=status)
               _VERIFY(status)
               this%lat_corners = this%compute_lat_corners(this%pole, rc=status)
               _VERIFY(status)
            else
               this%lon_centers_degrees = this%lon_centers
               this%lat_centers_degrees = this%lat_centers
               this%lon_centers = MAPL_DEGREES_TO_RADIANS_R8 * this%lon_centers
               this%lat_centers = MAPL_DEGREES_TO_RADIANS_R8 * this%lat_centers
               this%lon_corners = MAPL_DEGREES_TO_RADIANS_R8 * this%lon_corners
               this%lat_corners = MAPL_DEGREES_TO_RADIANS_R8 * this%lat_corners
            end if
         end if
    end associate
    call this%make_arbitrary_decomposition(this%nx, this%ny, rc=status)
    _VERIFY(status)
    ! Determine IMS and JMS with constraint for ESMF that each DE has at least an extent
    ! of 2.  Required for ESMF_FieldRegrid().
    allocate(this%ims(0:this%nx-1))
    allocate(this%jms(0:this%ny-1))
    call MAPL_DecomposeDim(this%im_world, this%ims, this%nx, min_DE_extent=2)
    call MAPL_DecomposeDim(this%jm_world, this%jms, this%ny, min_DE_extent=2)
    call this%check_and_fill_consistency(rc=status)
    _VERIFY(status)
    _RETURN(_SUCCESS)
   end subroutine initialize_from_file_metadata
Call graph
initialize_from_file_metadata calls mapl_assert, mapl_decomposedim, check_and_fill_consistency, compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners, get_coordinate_data, get_coordinate_variable, get_dimension, has_dimension, make_arbitrary_decomposition, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_decomposedim calls mapl_decomposedim
check_and_fill_consistency calls mapl_assert, mapl_return, mapl_verify, check_decomposition, generate_newnxy
compute_lat_centers calls mapl_assert, mapl_return, mapl_range
compute_lat_corners calls mapl_assert, mapl_return, mapl_range
compute_lon_centers calls mapl_return, mapl_verify, mapl_range
compute_lon_corners calls mapl_return, mapl_verify, mapl_range
get_coordinate_data calls mapl_return
get_coordinate_variable calls mapl_assert, mapl_return, mapl_verify, at
get_dimension calls mapl_return, at, find
has_dimension calls mapl_return, find
make_arbitrary_decomposition calls mapl_return, mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception