initialize_field_source – MAPL
initialize_field_source Subroutine
22 statements
Source File
public subroutine initialize_field_source(field, source, grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
type(ESMF_Field), intent(inout) :: source
type(ESMF_Grid), intent(out), optional :: grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_field_source(field, source, grid, rc)
      type(ESMF_Field), intent(inout) :: field
      type(ESMF_Field), intent(inout) :: source
      type(ESMF_Grid), optional, intent(out) :: grid
      integer, optional, intent(out) :: rc
      type(ESMF_TypeKind_Flag) :: typekind
      type(ESMF_Grid) :: grid_
      integer :: status
      call ESMF_FieldGet(source, grid=grid_, typekind=typekind, _RC)
      field = ESMF_FieldCreate(grid=grid_, typekind=typekind, _RC)
      if(present(grid)) grid=grid_
      _RETURN(_SUCCESS)
   end subroutine initialize_field_source
Call graph
initialize_field_source calls anyexceptions, assert_that, esmf_fieldcreate, esmf_fieldget, sourcelocation
initialize_field calls initialize_field_source
test_accumulate_mean_r4 calls initialize_field
test_accumulate_r4 calls initialize_field
test_accumulate_with_undef_some_steps calls initialize_field
test_accumulate calls initialize_field
test_max_accumulate_r4 calls initialize_field
test_min_accumulate_r4 calls initialize_field