init_post_advertise – MAPL
init_post_advertise Subroutine
55 statements
Source File
private subroutine init_post_advertise(gc, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gc
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   subroutine init_post_advertise(gc, importState, exportState, clock, rc)
      type(ESMF_GridComp) :: gc
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      type(OuterMetaComponent), pointer :: outer_meta
      integer :: status
      type(VirtualConnectionPt) :: export_v_pt, import_v_pt
      type(ActualConnectionPt) :: a_pt
      type(ConnectionPt) :: s_pt, d_pt
      type(SimpleConnection) :: conn
      type(HierarchicalRegistry), pointer :: registry
      class(StateItemSpec), pointer :: export_spec
      class(StateItemSpec), pointer :: import_spec
      type(ESMF_HConfig) :: hconfig, states_spec, state_spec, mapl_config
      type(ESMF_HConfigIter) :: iter,e,b
      character(:), allocatable :: var_name
      call MAPL_GridCompGet(gc, hconfig=hconfig, registry=registry, _RC)
      ! We would do this quite differently in an actual ExtData implementation.
      ! Here we are using information from the generic spec.
      mapl_config = ESMF_HConfigCreateAt(hconfig, keystring='mapl', _RC)
      if (ESMF_HConfigIsDefined(mapl_config, keystring='states')) then
         states_spec = ESMF_HConfigCreateAt(mapl_config, keystring='states')
         if (ESMF_HConfigIsDefined(states_spec, keystring='export')) then
            state_spec = ESMF_HConfigCreateAt(states_spec, keystring='export')
            b = ESMF_HConfigIterBegin(state_spec)
            e = ESMF_HConfigIterEnd(state_spec)
            iter = ESMF_HConfigIterBegin(state_spec)
            do while (ESMF_HConfigIterLoop(iter,b,e))
               var_name = ESMF_HConfigAsStringMapKey(iter,_RC)
               export_v_pt = VirtualConnectionPt(ESMF_STATEINTENT_EXPORT, var_name)
               import_v_pt = VirtualConnectionPt(ESMF_STATEINTENT_IMPORT, var_name)
               a_pt = ActualConnectionPt(export_v_pt)
               export_spec => registry%get_item_spec(a_pt, _RC)
               allocate(import_spec, source=export_spec)
               ! Need new payload ... (but maybe not as it will get tossed at connect() anyway.)
               call import_spec%create(_RC)
               call registry%add_item_spec(import_v_pt, import_spec)
               ! And now connect
               export_v_pt = VirtualConnectionPt(ESMF_STATEINTENT_EXPORT, var_name)
               s_pt = ConnectionPt('collection_1', export_v_pt)
               d_pt = ConnectionPt('<self>', import_v_pt)
               conn = SimpleConnection(source=s_pt, destination=d_pt)
               call registry%add_connection(conn, _RC)
            end do
         end if
      end if
      call ESMF_HConfigDestroy(mapl_config, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine init_post_advertise
Call graph
init_post_advertise calls ESMF_HConfigAsStringMapKey, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, create, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_gridcompget, add_item_spec, add_connection, get_item_spec, mapl_return, mapl_verify
mapl_gridcompget calls gridcomp_get
add_connection calls mapl_return, mapl_verify, connect
get_item_spec calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception