initialize_objects – MAPL
initialize_objects Subroutine
53 statements
Source File
public subroutine initialize_objects(importState, exportState, clock, typekind, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: importState
type(ESMF_State), intent(inout) :: exportState
type(ESMF_Clock), intent(inout) :: clock
type(ESMF_TypeKind_Flag), intent(in) :: typekind
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_objects(importState, exportState, clock, typekind, rc)
      type(ESMF_State), intent(inout) :: importState, exportState
      type(ESMF_Clock), intent(inout) :: clock
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Field) :: importField, exportField
      type(ESMF_Time) :: startTime
      type(ESMF_TimeInterval) :: timeStep
      type(ESMF_Grid) :: grid
      call ESMF_TimeIntervalSet(timeStep, s=TIME_STEP, _RC)
      call ESMF_TimeSet(startTime, yy=START_TIME, _RC)
      clock = ESMF_ClockCreate(timeStep=timeStep, startTime=startTime, _RC)
      grid = ESMF_GridCreateNoPeriDimUfrm(maxIndex=MAX_INDEX, minCornerCoord=MIN_CORNER_COORD, maxCornerCoord=MAX_CORNER_COORD, _RC)
      importField = ESMF_FieldCreate(grid=grid, typekind=typekind, _RC)
      exportField = ESMF_FieldCreate(grid=grid, typekind=typekind, _RC)
      importState = ESMF_StateCreate(stateIntent=ESMF_STATEINTENT_IMPORT, fieldList=[importField], name='import', _RC)
      exportState = ESMF_StateCreate(stateIntent=ESMF_STATEINTENT_EXPORT, fieldList=[exportField], name='export', _RC)
      _RETURN(_SUCCESS)
   end subroutine initialize_objects
Call graph
initialize_objects calls ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, anyexceptions, assert_that, esmf_fieldcreate, esmf_statecreate, sourcelocation
test_accumulate calls initialize_objects
test_accumulate_mean_r4 calls initialize_objects
test_accumulate_r4 calls initialize_objects
test_calculate_mean calls initialize_objects
test_calculate_mean_r4 calls initialize_objects
test_clear_accumulator calls initialize_objects
test_clear_valid_mean calls initialize_objects
test_initialize calls initialize_objects
test_invalidate calls initialize_objects
test_max_accumulate_r4 calls initialize_objects
test_min_accumulate_r4 calls initialize_objects
test_update calls initialize_objects