initialize_from_file_metadata – MAPL
initialize_from_file_metadata Subroutine
91 statements
Source File
private subroutine initialize_from_file_metadata(this, file_metadata, unusable, force_file_coordinates, rc)
Uses
mapl_KeywordEnforcerMod
MAPL_BaseMod
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
type(FileMetadata), intent(in), target :: file_metadata
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: force_file_coordinates
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_file_metadata(this, file_metadata, unusable, force_file_coordinates, rc)
      use MAPL_KeywordEnforcerMod
      use MAPL_BaseMod, only: MAPL_DecomposeDim
      class (CubedSphereGridFactory), intent(inout)  :: this
      type (FileMetadata), target, intent(in) :: file_metadata
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in) :: force_file_coordinates
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam= MOD_NAME // 'initialize_from_file_metadata()'
      integer :: status
      logical :: hasLev,hasLevel,hasXdim,hasLon
      logical :: is_stretched
      character(:), allocatable :: lev_name
      type(Attribute), pointer :: attr
      class(*), pointer :: attr_val(:)
      associate(im => this%im_world)
         hasXdim = file_metadata%has_dimension('Xdim')
         hasLon = file_metadata%has_dimension('lon',rc=status)
         if (hasXdim .and. (.not.haslon)) then
            im = file_metadata%get_dimension('Xdim',rc=status)
            _VERIFY(status)
         else if (hasLon .and. (.not.hasXdim)) then
            im = file_metadata%get_dimension('lon',rc=status)
            _VERIFY(status)
         else
            _FAIL("can not identify dimenions of cubed-sphere file")
         end if
      end associate
      call this%make_arbitrary_decomposition(this%nx, this%ny, reduceFactor=6, rc=status)
      _VERIFY(status)
      is_stretched = file_metadata%has_attribute('STRETCH_FACTOR') .and. &
                     file_metadata%has_attribute('TARGET_LON') .and. &
                     file_metadata%has_attribute('TARGET_LAT')
      if (is_stretched) then
         attr => file_metadata%get_attribute('STRETCH_FACTOR')
         attr_val => attr%get_values()
         select type(q=>attr_val)
         type is (real(kind=REAL32))
            this%stretch_factor = q(1)
         class default
            _FAIL('unsupport subclass for stretch params')
         end select
         attr => file_metadata%get_attribute('TARGET_LAT')
         attr_val => attr%get_values()
         select type(q=>attr_val)
         type is (real(kind=REAL32))
            this%target_lat = q(1)
         type is (real(kind=REAL64))
            this%target_lat = q(1)
         class default
            _FAIL('unsupport subclass for stretch params')
         end select
         attr => file_metadata%get_attribute('TARGET_LON')
         attr_val => attr%get_values()
         select type(q=>attr_val)
         type is (real(kind=REAL32))
            this%target_lon = q(1)
         type is (real(kind=REAL64))
            this%target_lon = q(1)
         class default
            _FAIL('unsupport subclass for stretch params')
         end select
      end if
      hasLev=.false.
      hasLevel=.false.
      lev_name = 'lev'
      hasLev = file_metadata%has_dimension(lev_name)
      if (hasLev) then
         this%lm = file_metadata%get_dimension(lev_name,rc=status)
         _VERIFY(status)
      else
         lev_name = 'levels'
         hasLevel = file_metadata%has_dimension(lev_name)
         if (hasLevel) then
            this%lm = file_metadata%get_dimension(lev_name,rc=status)
            _VERIFY(status)
         end if
      end if
      allocate(this%ims(0:this%nx-1))
      allocate(this%jms(0:this%ny-1))
      call MAPL_DecomposeDim(this%im_world, this%ims, this%nx, min_DE_extent=2)
      call MAPL_DecomposeDim(this%im_world, this%jms, this%ny, min_DE_extent=2)
      call this%check_and_fill_consistency(rc=status)
      _VERIFY(status)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(force_file_coordinates)
   end subroutine initialize_from_file_metadata
Call graph
initialize_from_file_metadata calls mapl_assert, mapl_decomposedim, check_and_fill_consistency, get_attribute, get_dimension, get_values, has_attribute, has_dimension, make_arbitrary_decomposition, mapl_verify, q
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_decomposedim calls mapl_decomposedim
check_and_fill_consistency calls mapl_assert, mapl_return
get_attribute calls mapl_assert, get_attribute, mapl_return, m_at
get_dimension calls at, find, mapl_return
get_values calls mapl_return
has_attribute calls is_attribute_present
has_dimension calls find, mapl_return
make_arbitrary_decomposition calls mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent, mapl_return
mapl_verify calls mapl_throw_exception
is_attribute_present calls mapl_return, m_at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
m_at calls m_find