initialize_field_new – MAPL
initialize_field_new Subroutine
21 statements
Source File
public subroutine initialize_field_new(field, typekind, grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
type(ESMF_TypeKind_Flag), intent(in) :: typekind
type(ESMF_Grid), intent(out), optional :: grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_field_new(field, typekind, grid, rc)
      type(ESMF_Field), intent(inout) :: field
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      type(ESMF_Grid), optional, intent(out) :: grid
      integer, optional, intent(out) :: rc
      type(ESMF_Grid) :: grid_
      integer :: status
      call create_grid(grid_, _RC)
      field = ESMF_FieldCreate(grid=grid_, typekind=typekind, _RC)
      if(present(grid)) grid=grid_
      _RETURN(_SUCCESS)
   end subroutine initialize_field_new
Call graph
initialize_field_new calls anyexceptions, assert_that, esmf_fieldcreate, create_grid, sourcelocation
create_grid calls anyexceptions, assert_that, sourcelocation, ESMF_GridCreate
initialize_field calls initialize_field_new
test_accumulate_mean_r4 calls initialize_field
test_accumulate_r4 calls initialize_field
test_accumulate_with_undef_some_steps calls initialize_field
test_accumulate calls initialize_field
test_max_accumulate_r4 calls initialize_field
test_min_accumulate_r4 calls initialize_field