instance_is_uninitialized – MAPL
instance_is_uninitialized Function
3 statements
Source File
private function instance_is_uninitialized()
Arguments
None
Return Value logical
Calls
Called by
Source Code
   logical function instance_is_uninitialized()
      instance_is_uninitialized = SYSTEM_INSTANCE%is_free()
   end function instance_is_uninitialized
Call graph
instance_is_uninitialized calls is_free
construct_unit calls instance_is_uninitialized
get_converter_function calls instance_is_uninitialized
initialize calls instance_is_uninitialized, initialize
udunit calls construct_unit
get_converter calls get_converter_function
getfieldunitsconverter calls get_converter
new_converter calls get_converter
test_convert_double calls get_converter
test_convert_doubles calls get_converter
test_convert_float calls get_converter
test_convert_floats calls get_converter
test_get_converter calls get_converter
convertunitsaction calls new_converter