integrate – MAPL
integrate Subroutine
22 statements
Source File
private subroutine integrate(driver, rc)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriver), intent(inout) :: driver
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine integrate(driver, rc)
      type(GriddedComponentDriver), intent(inout) :: driver
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Clock) :: clock
      type(ESMF_Time) :: currTime, stopTime
      clock = driver%get_clock()
      call ESMF_ClockGet(clock, currTime=currTime, stopTime=stopTime, _RC)
      do while (currTime < stopTime)
         ! TODO:  include Bill's monitoring log messages here
         call driver%run(_RC)
         call ESMF_ClockAdvance(clock, _RC)
         call ESMF_ClockGet(clock, currTime=currTime, _RC)
      end do
      call ESMF_TimePrint(currTime, options='string', preString='Cap time after loop: ', _RC)
      _RETURN(_SUCCESS)
   end subroutine integrate
Call graph
integrate calls ESMF_ClockAdvance, ESMF_ClockGet, ESMF_TimePrint, get_clock, run, mapl_return, mapl_verify
get_clock calls get_clock
run calls run, mapl_return, mapl_verify, ESMF_GridCompRun, run_export_couplers, run_import_couplers
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_export_couplers calls run_export_couplers
run_import_couplers calls run_import_couplers
mapl_run_driver calls integrate
run_geos calls mapl_run_driver
geos calls run_geos