intervals_and_offset_are_compatible – MAPL
intervals_and_offset_are_compatible Subroutine
41 statements
Source File
public subroutine intervals_and_offset_are_compatible(interval, interval2, offset, compatible, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TimeInterval), intent(in) :: interval
type(ESMF_TimeInterval), intent(in) :: interval2
type(ESMF_TimeInterval), intent(in), optional :: offset
logical, intent(out) :: compatible
integer, intent(inout), optional :: rc
Calls
Source Code
   subroutine intervals_and_offset_are_compatible(interval, interval2, offset, compatible, rc)
      type(ESMF_TimeInterval), intent(in) :: interval
      type(ESMF_TimeInterval), intent(in) :: interval2
      type(ESMF_TimeInterval), optional, intent(in) :: offset
      logical, intent(out) :: compatible
      integer, optional, intent(inout) :: rc
      integer :: status
      type(ESMF_TimeInterval), pointer  :: zero => null()
      integer(kind=I4) :: units(NUM_INTERVAL_UNITS), units2(NUM_INTERVAL_UNITS)
      compatible = .FALSE.
      zero => zero_time_interval()
      _ASSERT(interval2 /= zero, 'The second interval must be nonzero.')
      units = to_array(interval, _RC)
      units2 = to_array(interval2, _RC)
      _RETURN_IF(cannot_compare(units == 0, units2 == 0))
      associate(abs1 => ESMF_TimeIntervalAbsValue(interval), &
            & abs2 => ESMF_TimeIntervalAbsValue(interval2))
         _RETURN_IF(abs1 < abs2 .or. mod(abs1, abs2) /= zero)
         compatible = abs1 >= abs2 .and. mod(abs1, abs2) == zero
         _RETURN_UNLESS(present(offset))
         compatible = compatible .and. mod(ESMF_TimeIntervalAbsValue(offset), abs2) == zero
      end associate
      _RETURN(_SUCCESS)
      contains
!     These combinations (larger, smaller): (yy and/or mm, d), (yy and/or mm, h),
!     (yy and/or mm, m), and (yy and/or mm, s) do not work because the
!     ESMF_TimeInterval overload of the mod function gives incorrect results for
!     these combinations. Presumably ms, us, and ns for the smaller interval do
!     not work.
      logical function cannot_compare(z, z2)
         logical, intent(in) :: z(:), z2(:)
         integer, parameter :: MONTH = 2
         cannot_compare = any(z .neqv. z2) .or. .not. (all(z(:MONTH)) .or. all(z(MONTH+1:)))
      end function cannot_compare
   end subroutine intervals_and_offset_are_compatible
Call graph
intervals_and_offset_are_compatible calls ESMF_TimeIntervalAbsValue, ESMF_TimeIntervalGet, mapl_assert, zero_time_interval, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception