invalidate_consumers – MAPL
invalidate_consumers Subroutine
14 statements
Source File
private recursive subroutine invalidate_consumers(this, rc)
Type Bound
CouplerMetaComponent
Arguments
Type Intent Optional Attributes Name
class(CouplerMetaComponent), target :: this
integer, intent(out) :: rc
Calls
Called by
Source Code
    recursive subroutine invalidate_consumers(this, rc)
      class(CouplerMetaComponent), target :: this
      integer, intent(out) :: rc
      integer :: status
      class(ComponentDriver), pointer :: consumer
      integer :: i
      do i = 1, this%consumers%size()
         consumer => this%consumers%of(i)
         call consumer%run(phase_idx=GENERIC_COUPLER_INVALIDATE, _RC)
      end do
      _RETURN(_SUCCESS)
   end subroutine invalidate_consumers
Call graph
invalidate_consumers calls of, mapl_return, mapl_verify, run
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
invalidate calls invalidate_consumers, invalidate