invalidate – MAPL
invalidate Subroutine
17 statements
Source File
private recursive subroutine invalidate(this, sourceState, exportState, clock, rc)
Type Bound
CouplerMetaComponent
Arguments
Type Intent Optional Attributes Name
class(CouplerMetaComponent) :: this
type(ESMF_State) :: sourceState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Called by
Source Code
   recursive subroutine invalidate(this, sourceState, exportState, clock, rc)
        class(CouplerMetaComponent) :: this
        type(ESMF_State) :: sourceState
        type(ESMF_State) :: exportState
        type(ESMF_Clock) :: clock
        integer, intent(out) :: rc
        integer :: status
        _RETURN_IF(this%is_stale())
!#        call this%action%invalidate(_RC) ! eventually needs access to clock
        call this%invalidate_consumers(_RC)
        call this%set_stale()
        _RETURN(_SUCCESS)
    end subroutine invalidate
Call graph
invalidate calls invalidate_consumers, is_stale, mapl_return, mapl_verify, set_stale, invalidate
invalidate_consumers calls mapl_return, mapl_verify, of, run
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize