invalidate – MAPL
invalidate Subroutine
15 statements
Source File
private recursive subroutine invalidate(gridcomp, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine invalidate(gridcomp, importState, exportState, clock, rc)
      type(ESMF_GridComp) :: gridcomp
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      integer :: status
      type(CouplerMetaComponent), pointer :: meta
      meta => get_coupler_meta(gridcomp, _RC)
      call meta%invalidate(importstate, exportState, clock, _RC)
      _RETURN(_SUCCESS)
   end subroutine invalidate
Call graph
invalidate calls get_coupler_meta, invalidate, mapl_return, mapl_verify, invalidate_consumers, is_stale, set_stale
get_coupler_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
invalidate_consumers calls mapl_return, mapl_verify, of, run
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception