IOBundle_Add_Entry – MAPL
IOBundle_Add_Entry Subroutine
40 statements
Source File
private subroutine IOBundle_Add_Entry(IOBundles, item, entry_num, rc)
Arguments
Type Intent Optional Attributes Name
type(IoBundleNGVector), intent(inout), target :: IOBundles
type(PrimaryExport), intent(inout), target :: item
integer, intent(in) :: entry_num
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine IOBundle_Add_Entry(IOBundles,item,entry_num,rc)
     type(IOBundleNGVector), target, intent(inout) :: IOBundles
     type(primaryExport), target, intent(inout)  :: item
     integer, intent(in)                    :: entry_num
     integer, intent(out), optional         :: rc
     integer :: status
     type (ExtDataNG_IOBundle) :: io_bundle
     type (GriddedIOItemVector) :: itemsL, itemsR
     logical :: update
     character(len=ESMF_MAXPATHLEN) :: current_file
     integer :: time_index
     type(StringIntegerMap), pointer :: dimensions
     integer, pointer :: tile_size
     logical :: on_tiles
     dimensions => item%file_metadata%get_dimensions()
     tile_size => dimensions%at("tile_index")
     on_tiles = associated(tile_size)
     call item%modelGridFields%comp1%get_parameters('L',update=update,file=current_file,time_index=time_index)
     if (update) then
        if (trim(current_file)/=file_not_found) then
           call itemsL%push_back(item%fileVars)
           io_bundle = ExtDataNG_IOBundle(MAPL_ExtDataLeft, entry_num, current_file, time_index, item%trans, item%fracval, item%file_template, &
               item%pfioCollection_id,item%iclient_collection_id,itemsL,on_tiles,rc=status)
           _VERIFY(status)
           call IOBundles%push_back(io_bundle)
           call extdata_lgr%info('%a updated L bracket with: %a at time index %i3 ',item%name, current_file, time_index)
        end if
     end if
     call item%modelGridFields%comp1%get_parameters('R',update=update,file=current_file,time_index=time_index)
     if (update) then
        if (trim(current_file)/=file_not_found) then
           call itemsR%push_back(item%fileVars)
           io_bundle = ExtDataNG_IOBundle(MAPL_ExtDataRight, entry_num, current_file, time_index, item%trans, item%fracval, item%file_template, &
               item%pfioCollection_id,item%iclient_collection_id,itemsR,on_tiles,rc=status)
           _VERIFY(status)
           call IOBundles%push_back(io_bundle)
           call extdata_lgr%info('%a updated R bracket with: %a at time index %i3 ',item%name,current_file, time_index)
        end if
     end if
     _RETURN(ESMF_SUCCESS)
  end subroutine IOBundle_Add_Entry
Call graph
iobundle_add_entry calls at, get_dimensions, get_parameters, info, mapl_return, mapl_verify, v_push_back
get_dimensions calls get_dimensions
get_parameters calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_resize_32 calls resize
run_ calls iobundle_add_entry