is_active – MAPL
is_active Function
4 statements
Source File
private pure function is_active(this)
Type Bound
StateItemSpec
Arguments
Type Intent Optional Attributes Name
class(StateItemSpec), intent(in) :: this
Return Value logical
Called by
Source Code
   pure logical function is_active(this)
      class(StateItemSpec), intent(in) :: this
      is_active = this%active
   end function is_active
Call graph
allocate calls is_active
propagate_unsatisfied_imports_virtual_pt calls is_active
test_internal_activation calls is_active
test_internal_to_export_connection calls is_active
test_multi_import calls is_active, propagate_unsatisfied_imports
test_sibling_activation calls is_active, propagate_unsatisfied_imports
initialize_advertise calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
initialize calls initialize_advertise