is_coordinate_variable – MAPL
is_coordinate_variable Function
23 statements
Source File
private function is_coordinate_variable(this, var_name, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value logical
Calls
Source Code
   logical function is_coordinate_variable(this, var_name, unusable, rc)
      class (FileMetadata),target, intent(in) :: this
      character(*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class (Variable), pointer :: tmp
      integer :: status
      tmp => this%variables%at(var_name, _RC)
      _ASSERT(associated(tmp), 'can not find the varaible '//trim(var_name))
      select type (tmp)
      class is (CoordinateVariable)
         is_coordinate_variable = .true.
      class default
         is_coordinate_variable = .false.
      end select
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function is_coordinate_variable
Call graph
is_coordinate_variable calls mapl_assert, at, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_find calls map_s_find