is_export – MAPL
is_export Function
4 statements
Source File
private function is_export(this)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value logical
Calls
Called by
Source Code
   logical function is_export(this)
      class(ActualConnectionPt), intent(in) :: this
      is_export = this%v_pt%is_export()
   end function is_export
Call graph
is_export calls is_export, get_state_intent
propagate_exports_virtual_pt calls is_export
initialize_advertise calls propagate_exports
propagate_exports_all calls propagate_exports
propagate_exports_child calls propagate_exports
test_sibling_activation calls propagate_exports
initialize calls initialize_advertise