is_extension – MAPL
is_extension Function
4 statements
Source File
private function is_extension(this)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value logical
Called by
Source Code
   logical function is_extension(this)
      class(ActualConnectionPt), intent(in) :: this
      is_extension = allocated(this%label)
   end function is_extension
Call graph
extend_ calls is_extension, extend_
get_esmf_name calls is_extension, get_extension_string
get_extension_string calls is_extension
get_full_name calls is_extension, get_extension_string
is_represented_in calls is_extension
extend calls extend_
add_to_state calls get_esmf_name
add_to_states calls is_represented_in
write_formatted calls get_full_name
connect_sibling calls extend_
initialize_post_advertise calls add_to_states
test_vertical calls add_to_state
connect calls connect_sibling
initialize calls initialize_post_advertise