is_import – MAPL
is_import Function
4 statements
Source File
private function is_import(this)
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
Return Value logical
Calls
Called by
Source Code
   logical function is_import(this)
      class(VirtualConnectionPt), intent(in) :: this
      is_import = (this%get_state_intent() == 'import')
   end function is_import
Call graph
is_import calls get_state_intent, is_import
propagate_unsatisfied_imports_virtual_pt calls is_import
initialize_advertise calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_unsatisfied_imports