is_import – MAPL
is_import Function
4 statements
Source File
private function is_import(this)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value logical
Calls
Called by
Source Code
   logical function is_import(this)
      class(ActualConnectionPt), intent(in) :: this
      is_import = this%v_pt%is_import()
   end function is_import
Call graph
is_import calls is_import, get_state_intent
propagate_unsatisfied_imports_virtual_pt calls is_import
initialize_advertise calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_unsatisfied_imports
initialize calls initialize_advertise