is_internal – MAPL
is_internal Function
4 statements
Source File
private function is_internal(this)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
Return Value logical
Calls
Called by
Source Code
   logical function is_internal(this)
      class(ActualConnectionPt), intent(in) :: this
      is_internal = this%v_pt%is_internal()
   end function is_internal
Call graph
is_internal calls is_internal, get_state_intent
add_item_spec_actual calls is_internal
connect_export_to_export calls is_internal
connect calls connect_export_to_export
add_item_spec_virtual calls add_item_spec
add_item_spec_virtual_override calls add_item_spec
extend_ calls add_item_spec
init_post_advertise calls add_item_spec
initialize_advertise calls add_item_spec
test_add_item_duplicate_fail calls add_item_spec
test_connect calls add_item_spec
test_connect_chain calls add_item_spec
test_create_extension calls add_item_spec
test_do_not_propagate_import calls add_item_spec
test_e2e_preserve_actual_pt calls add_item_spec
test_export_to_export_connection calls add_item_spec
test_get_item_spec_found calls add_item_spec
test_get_item_spec_multi calls add_item_spec
test_import_from_child calls add_item_spec
test_import_from_parent calls add_item_spec
test_internal_activation calls add_item_spec
test_internal_to_export_connection calls add_item_spec
test_multi_import calls add_item_spec
test_propagate_import calls add_item_spec
test_sibling_activation calls add_item_spec
connect_sibling calls extend_
initialize calls initialize_advertise