is_periodic – MAPL
is_periodic Module Function
20 statements
Source File
pure module function is_periodic(this) Interface →
Arguments
Type Intent Optional Attributes Name
class(CoordinateAxis), intent(in) :: this
Return Value logical
Called by
Source Code
   pure logical module function is_periodic(this)
      class(CoordinateAxis), intent(in) :: this
      real(kind=R8) :: span, spacing
      real(kind=R8), parameter :: tolerance = 0.01
      associate (corners => this%corners)
        associate (n => size(corners))
          if (n == 1) then
             is_periodic = .false.
             return
          end if
          span = corners(n) - corners(1)
          spacing = corners(2) - corners(1)
          if (abs(span - 360) < (tolerance * spacing)) then
             is_periodic = .true.
          else
             is_periodic = .false.
          end if
        end associate
      end associate
   end function is_periodic
Call graph
is_periodic calls is_periodic
create_basic_grid calls is_periodic, create_basic_grid
get_lon_subset calls is_periodic, get_lon_subset
test_is_not_periodic calls is_periodic
test_is_periodic calls is_periodic
fill_coordinates calls get_lon_subset
typesafe_make_geom calls create_basic_grid