is_represented_in – MAPL
is_represented_in Function
15 statements
Source File
private function is_represented_in(this, mode)
Type Bound
ActualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(ActualConnectionPt), intent(in) :: this
character(len=*), intent(in) :: mode
Return Value logical
Calls
Called by
Source Code
   logical function is_represented_in(this, mode)
      class(ActualConnectionPt), intent(in) :: this
      character(*), intent(in) :: mode ! user or outer grid comp
      is_represented_in = .false. ! unless
      select case (mode)
      case ('user') ! only add undecorated items
         if (this%is_extension()) return
         if (this%get_comp_name() /= '') return
      case ('outer') ! do not add internal items
         if (this%get_state_intent() == 'internal') return
      case default
         error stop "Illegal mode in ActualConnectionPt.F90 - should be checked by calling procedure."
      end select
      is_represented_in = .true.
   end function is_represented_in
Call graph
is_represented_in calls get_comp_name, get_state_intent, is_extension
get_comp_name calls get_comp_name
get_state_intent calls get_state_intent
add_to_states calls is_represented_in
initialize_post_advertise calls add_to_states
initialize calls initialize_post_advertise