is_valid_name – MAPL
is_valid_name Function
8 statements
Source File
public pure function is_valid_name(name) result(is_valid)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Return Value logical
Called by
Source Code
   pure logical function is_valid_name(name) result(is_valid)
      character(len=*), intent(in) :: name
      is_valid =  len(name) > 0
      if (.not. is_valid) return
      is_valid = (verify(name(1:1), LOWER // UPPER) == 0)
      if (.not. is_valid) return
      is_valid = (verify(name(2:), LOWER // UPPER // DIGITS // '_') == 0)
   end function is_valid_name
Call graph
add_child_by_name calls is_valid_name, add_child, add_child_by_name
mapl_addchild calls add_child_by_name
setservices calls mapl_addchild, setservices
setservices_ calls add_child
setup calls add_child
test_mapl_invalid_name calls add_child