link_item_spec_actual – MAPL
link_item_spec_actual Subroutine
17 statements
Source File
private subroutine link_item_spec_actual(this, actual_pt, spec, unusable, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(ActualConnectionPt), intent(in) :: actual_pt
class(StateItemSpec), target :: spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine link_item_spec_actual(this, actual_pt, spec, unusable, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(ActualConnectionPt), intent(in) :: actual_pt
      class(StateItemSpec), target :: spec
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(StateItemSpecPtr) :: wrap
      _ASSERT(.not. this%has_item_spec(actual_pt), 'Duplicate item name.')
      wrap = StateItemSpecPtr(spec)
      call this%actual_specs_map%insert(actual_pt, wrap)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine link_item_spec_actual
Call graph
link_item_spec_actual calls mapl_assert, has_item_spec, insert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
add_item_spec_actual calls link_item_spec_actual
connect_export_to_export calls link_item_spec
link_item_spec_virtual calls link_item_spec
add_item_spec_virtual calls add_item_spec
add_item_spec_virtual_override calls add_item_spec
connect calls connect_export_to_export
extend_ calls add_item_spec
init_post_advertise calls add_item_spec
initialize_advertise calls add_item_spec
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual
test_add_item_duplicate_fail calls add_item_spec
test_connect calls add_item_spec
test_connect_chain calls add_item_spec
test_create_extension calls add_item_spec
test_do_not_propagate_import calls add_item_spec
test_e2e_preserve_actual_pt calls add_item_spec
test_export_to_export_connection calls add_item_spec
test_get_item_spec_found calls add_item_spec
test_get_item_spec_multi calls add_item_spec
test_import_from_child calls add_item_spec
test_import_from_parent calls add_item_spec
test_internal_activation calls add_item_spec
test_internal_to_export_connection calls add_item_spec
test_multi_import calls add_item_spec
test_propagate_import calls add_item_spec
test_sibling_activation calls add_item_spec