link_item_spec_virtual – MAPL
link_item_spec_virtual Subroutine
17 statements
Source File
private subroutine link_item_spec_virtual(this, virtual_pt, spec, actual_pt, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(VirtualConnectionPt), intent(in) :: virtual_pt
class(StateItemSpec), target :: spec
type(ActualConnectionPt), intent(in) :: actual_pt
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine link_item_spec_virtual(this, virtual_pt, spec, actual_pt, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(VirtualConnectionPt), intent(in) :: virtual_pt
      class(StateItemSpec), target :: spec
      type(ActualConnectionPt), intent(in) :: actual_pt
      integer, optional, intent(out) :: rc
      integer :: status
      call this%add_extension_pt(virtual_pt, actual_pt)
      if (this%has_item_spec(actual_pt)) then ! that's ok?
         _RETURN(_SUCCESS)
      end if
      call this%link_item_spec(actual_pt, spec, _RC)
      _RETURN(_SUCCESS)
   end subroutine link_item_spec_virtual
Call graph
link_item_spec_virtual calls has_item_spec, link_item_spec, add_extension_pt, mapl_return, mapl_verify
add_extension_pt calls insert, map_of, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
link_item_spec_actual calls has_item_spec, mapl_return, mapl_assert, insert
map_of calls insert, map_s_iter_of
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
map_insert_pair calls insert
map_s_iter_of calls map_s_get_value
vector_grow_to calls vector_capacity, vector_set_capacity
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual
connect_export_to_export calls link_item_spec
connect calls connect_export_to_export
initialize_advertise calls propagate_exports, propagate_unsatisfied_imports
propagate_exports_all calls propagate_exports
propagate_exports_child calls propagate_exports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_exports, propagate_unsatisfied_imports
initialize calls initialize_advertise