log_message – MAPL
log_message Subroutine
13 statements
Source File
private subroutine log_message(this, typestring, valuestring, rc)
Type Bound
HConfigParams
Arguments
Type Intent Optional Attributes Name
class(HConfigParams), intent(in) :: this
character(len=*), intent(in) :: typestring
character(len=*), intent(in) :: valuestring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine log_message(this, typestring, valuestring, rc)
      class(HConfigParams), intent(in) :: this
      character(len=*), intent(in) :: typestring
      character(len=*), intent(in) :: valuestring
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=:), allocatable :: message
      _ASSERT(this%has_logger(), 'There is no logger.')
      message = typestring //' '// this%label //' = '// valuestring
      call this%logger%info(message)
      _RETURN(_SUCCESS)
   end subroutine log_message
Call graph
log_message calls info, mapl_assert, has_logger, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_value_i4 calls log_message
get_value_i4seq calls log_message
get_value_i8 calls log_message
get_value_i8seq calls log_message
get_value_logical calls log_message
get_value_logical_seq calls log_message
get_value_r4 calls log_message
get_value_r4seq calls log_message
get_value_r8 calls log_message
get_value_r8seq calls log_message
get_value_string calls log_message
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string