make_geom – MAPL
make_geom Module Function
16 statements
Source File
module function make_geom(this, geom_spec, rc) result(geom) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
class(GeomSpec), intent(in) :: geom_spec
integer, intent(out), optional :: rc
Return Value type(ESMF_Geom)
Calls
Called by
Source Code
   module function make_geom(this, geom_spec, rc) result(geom)
      type(ESMF_Geom) :: geom
      class(LatLonGeomFactory), intent(in) :: this
      class(GeomSpec), intent(in) :: geom_spec
      integer, optional, intent(out) :: rc
      integer :: status
      select type (geom_spec)
      type is (LatLonGeomSpec)
         geom = typesafe_make_geom(geom_spec, _RC)
      class default
         _FAIL("geom_spec type not supported")
      end select
      _RETURN(_SUCCESS)
   end function make_geom
Call graph
make_geom calls mapl_assert, mapl_return, mapl_verify, typesafe_make_geom, make_geom
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
typesafe_make_geom calls mapl_return, mapl_verify, ESMF_GeomCreate, create_basic_grid, fill_coordinates
create_basic_grid calls create_basic_grid, mapl_return, mapl_verify, ESMF_GridAddCoord, ESMF_GridCreate1PeriDim, ESMF_GridCreateNoPeriDim, get_decomposition, get_lat_axis, get_lat_distribution, get_lon_axis, get_lon_distribution, is_periodic
fill_coordinates calls fill_coordinates, mapl_return, mapl_verify, ESMF_GridGetCoord, get_centers, get_corners, get_decomposition, get_lat_axis, get_lat_distribution, get_lat_subset, get_lon_axis, get_lon_distribution, get_lon_subset, get_ranks
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_make_from_hconfig calls make_geom