make_action – MAPL
make_action Function
26 statements
Source File
private function make_action(this, dst_spec, rc) result(action)
Type Bound
BracketSpec
Arguments
Type Intent Optional Attributes Name
class(BracketSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: dst_spec
integer, intent(out), optional :: rc
Return Value class(ExtensionAction), allocatable
Calls
Source Code
   function make_action(this, dst_spec, rc) result(action)
      class(ExtensionAction), allocatable :: action
      class(BracketSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: dst_spec
      integer, optional, intent(out) :: rc
      integer :: status
      class(ExtensionAction), allocatable :: subaction
      integer :: i
      type(BundleAction) :: bundle_action
      action = NullAction() ! default
      select type (dst_spec)
      type is (BracketSpec)
         _ASSERT(this%bracket_size == dst_spec%bracket_size, 'bracket size mismatch')
         bundle_action = BundleAction()
         do i = 1, this%bracket_size
            subaction = this%field_specs(i)%make_action(dst_spec%field_specs(i), _RC)
            call bundle_action%add_action(subaction)
         end do
!##ifdef __GFORTRAN__
!#         deallocate(action)
!##endif
         action = bundle_action
      class default
         _FAIL('Dst_spec is incompatible with BracketSpec.')
      end select
      _RETURN(_SUCCESS)
   end function make_action
Call graph
make_action calls field_specs, mapl_assert, add_action, make_action, mapl_return, mapl_verify, mapl_samegeom, match, regridaction
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_action calls vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_samegeom calls same_geom
match calls match_geom, match_string, match_typekind
regridaction calls new_scalarregridaction
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to