make_offset_string – MAPL
make_offset_string Subroutine
8 statements
Source File
public subroutine make_offset_string(offset, offset_string, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: offset
character(len=*), intent(out) :: offset_string
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine make_offset_string(offset, offset_string, rc)
      integer, intent(in) :: offset
      character(len=*), intent(out) :: offset_string
      integer, optional, intent(out) :: rc
      integer :: status
      write(offset_string, fmt='("PT", I03, "S")', iostat=status) offset
      _VERIFY(status)
   end subroutine make_offset_string
Call graph
make_offset_string calls mapl_verify
mapl_verify calls mapl_throw_exception
test_compare_negative_string_to_negative_heartbeat calls make_offset_string
test_compare_positive_string_to_positive_heartbeat calls make_offset_string
test_create_from_parameters_string_negative calls make_offset_string
test_create_from_parameters_string_positive calls make_offset_string