make_info – MAPL
make_info Function
20 statements
Source File
private function make_info(this, rc) result(info)
Type Bound
UngriddedDimSpec
Arguments
Type Intent Optional Attributes Name
class(UngriddedDimSpec), intent(in) :: this
integer, intent(out), optional :: rc
Return Value type(ESMF_Info)
Calls
Called by
Source Code
   function make_info(this, rc) result(info)
      type(ESMF_Info) :: info
      class(UngriddedDimSpec), intent(in) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      info = ESMF_InfoCreate(_RC)
      if (allocated(this%name)) then
         call ESMF_InfoSet(info, key='name', value=this%name, _RC)
      end if
      if (allocated(this%units)) then
         call ESMF_InfoSet(info, key='units', value=this%units, _RC)
      end if
      call ESMF_InfoSet(info, key='coordinates', values=this%coordinates, _RC)
      _RETURN(_SUCCESS)
   end function make_info
Call graph
make_info calls ESMF_InfoCreate, ESMF_InfoSet, mapl_return, mapl_verify, make_info
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
set_info calls make_info
allocate calls set_info
test_field_set_info calls set_info