make_extension_safely – MAPL
make_extension_safely Function
10 statements
Source File
private function make_extension_safely(this, dst_spec) result(extension)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
type(FieldSpec), intent(in) :: dst_spec
Return Value type(FieldSpec)
Calls
Called by
Source Code
   function make_extension_safely(this, dst_spec) result(extension)
      type(FieldSpec) :: extension
      class(FieldSpec), intent(in) :: this
      type(FieldSpec), intent(in) :: dst_spec
      logical :: found
      extension = this
      if (update_item(extension%geom, dst_spec%geom)) return
      if (update_item(extension%typekind, dst_spec%typekind)) return
      if (update_item(extension%units, dst_spec%units)) return
    end function make_extension_safely
Call graph
make_extension_safely calls update_item
update_item calls update_item_geom, update_item_string, update_item_typekind
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match
match calls match_geom, match_string, match_typekind
make_extension calls make_extension_safely