make_driver – MAPL
make_driver Function
22 statements
Source File
private function make_driver(hconfig, rc) result(driver)
Uses
mapl3g_GenericGridComp
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(inout) :: hconfig
integer, intent(out), optional :: rc
Return Value type(GriddedComponentDriver)
Calls
Called by
Source Code
   function make_driver(hconfig, rc) result(driver)
      use mapl3g_GenericGridComp, only: generic_SetServices => setServices
      type(GriddedComponentDriver) :: driver
      type(ESMF_HConfig), intent(inout) :: hconfig
      integer, optional, intent(out) :: rc
      type(ESMF_GridComp) :: cap_gridcomp
      type(ESMF_Clock) :: clock
      character(:), allocatable :: cap_name
      integer :: status, user_status
      cap_name = ESMF_HConfigAsString(hconfig, keystring='cap_name', _RC)
      ! TODO:  Rename to MAPL_CreateGridComp() ?
      clock = create_clock(hconfig, _RC)
      cap_gridcomp = create_grid_comp(cap_name, user_setservices(cap_setservices), hconfig, clock, _RC)
      call ESMF_GridCompSetServices(cap_gridcomp, generic_setServices, userRC=user_status, _RC)
      _VERIFY(user_status)
      driver = GriddedComponentDriver(cap_gridcomp, clock, MultiState())
      _RETURN(_SUCCESS)
   end function make_driver
Call graph
make_driver calls esmf_gridcompsetservices, esmf_hconfigasstring, create_grid_comp, user_setservices, create_clock, mapl_return, mapl_verify
create_grid_comp calls create_grid_comp_primary
user_setservices calls new_dsosetservices, new_procsetservices
create_clock calls mapl_return, mapl_verify, ESMF_CalendarSetDefault, ESMF_ClockCreate, ESMF_TimePrint, esmf_hconfigcreateat, set_time, set_time_interval
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
create_grid_comp_primary calls mapl_return, mapl_verify, ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, outer_name, set_is_generic
get_error_message calls at, insert
mapl_throw_exception calls initialize
set_time calls esmf_hconfigasstring, mapl_return, mapl_verify, ESMF_TimeSet
set_time_interval calls esmf_hconfigasstring, mapl_return, mapl_verify, ESMF_TimeIntervalSet, mapl_assert
mapl_run_driver calls make_driver
run_geos calls mapl_run_driver
geos calls run_geos