make_dim_key – MAPL
make_dim_key Function
19 statements
Source File
public function make_dim_key(n, rc) result(key)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function make_dim_key(n, rc) result(key)
      character(len=:), allocatable :: key
      integer, intent(in) :: n
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=32) :: raw
      key = ''
      _ASSERT(n > 0, 'Index must be positive.')
      if(n <= size(KEY_DIM_STRINGS)) then
         key = KEY_DIM_STRINGS(n)
         _RETURN(_SUCCESS)
      end if
      write(raw, fmt='(I0)', iostat=status) n
      _ASSERT(status == 0, 'Write failed')
      key = KEYSTUB_DIM // trim(raw)
      _RETURN(_SUCCESS)
   end function make_dim_key
Call graph
make_dim_key calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception
make_ungridded_dims_info calls make_dim_key
make_ungriddeddims calls make_dim_key
get_ungridded_dims_bundle_info calls make_ungriddeddims
make_esmf_info calls make_ungridded_dims_info
mapl_fieldbundleget calls make_ungriddeddims
setup_bundle calls make_info, setup_field
setup_field calls make_info
test_make_ungridded_dims calls make_info, make_ungriddeddims
teardown_bundle calls mapl_fieldbundleget
test_change_geom calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_change_typekind calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_change_units calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_change_weights calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_create_fields calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle
test_field_set_info calls set_info
test_get_num_levels calls make_esmf_info
test_get_ungridded_dims calls get_ungridded_dims_bundle_info, make_esmf_info
test_get_vertical_dim_spec_names calls make_esmf_info
test_same_geom calls mapl_fieldbundleget, setup_bundle, update_bundle, teardown_bundle