make_subgrids_from_num_grids – MAPL
make_subgrids_from_num_grids Function
18 statements
Source File
private function make_subgrids_from_num_grids(primary_grid, num_grids, unusable, rc) result(subgrids)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: primary_grid
integer, intent(in) :: num_grids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid), allocatable, (:)
Calls
Called by
Source Code
    function make_subgrids_from_num_grids(primary_grid, num_grids, unusable, rc) result(subgrids)
        type(ESMF_Grid), allocatable :: subgrids(:)
        type(ESMF_Grid), intent(inout) :: primary_grid
        integer, intent(in) :: num_grids
        class(KeywordEnforcer), optional, intent(in) :: unusable
        integer, optional, intent(out) :: rc
        integer :: local_count(3)
        integer :: status
        type(Interval), allocatable :: bounds(:)
        call MAPL_GridGet(primary_grid,localcellcountPerDim=local_count, _RC)
        bounds = find_bounds(local_count(2), num_grids)
        subgrids = make_subgrids(primary_grid, bounds, _RC)
        _RETURN(ESMF_SUCCESS)
        _UNUSED_DUMMY(unusable)
    end function make_subgrids_from_num_grids
Call graph
make_subgrids_from_num_grids calls make_subgrids, find_bounds, mapl_gridget, mapl_return, mapl_verify
make_subgrids calls make_subgrids_from_num_grids, make_subgrids_from_bounds
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_subgrids_from_bounds calls mapl_gridget, mapl_return, mapl_verify, ESMF_GridGet, ESMF_InfoGetFromHost, ESMF_GridAddCoord, ESMF_GridCreateNoPeriDim, ESMF_GridGetCoord, ESMF_InfoRemove, ESMF_InfoSet, ESMF_VMGet, ESMF_VMGetCurrent, mapl_gridgetcorners, subset_array
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
create_subobjects calls make_subgrids
make_subfields_from_num_grids calls make_subgrids
make_subfields calls make_subfields_from_num_grids
activate_threading calls create_subobjects
make_subfieldbundles_ordinary calls make_subfields
make_substates_from_num_grids calls make_subfields
omp_driver calls activate_threading