make_esmf_time – MAPL
make_esmf_time Subroutine
11 statements
Source File
public subroutine make_esmf_time(f, datetime, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f(NF)
type(ESMF_Time), intent(inout) :: datetime
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine make_esmf_time(f, datetime, rc)
      integer, intent(in) :: f(NF)
      type(ESMF_Time), intent(inout) :: datetime
      integer, optional, intent(out) :: rc
      integer :: status
      status = 0
      call ESMF_TimeSet(datetime, yy=f(1), mm=f(2), dd=f(3), h=f(4), m=f(5), s=f(6), _RC)
      _RETURN(_SUCCESS)
   end subroutine make_esmf_time
Call graph
make_esmf_time calls ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_up calls make_esmf_time