make_ItemSpec – MAPL
make_ItemSpec Function
36 statements
Source File
private function make_ItemSpec(this, geom, vertical_geom, registry, rc) result(item_spec)
$ case (MAPL_STATEITEM_FIELDBUNDLE) $ allocate(FieldBundleSpec::item_spec) $ item_spec = this%make_FieldBundleSpec(geom, rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/generic3g/specs/VariableSpec.F90”,207 ,rc)) return
Type Bound
VariableSpec
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: this
type(ESMF_Geom), intent(in) :: geom
type(VerticalGeom), intent(in) :: vertical_geom
type(HierarchicalRegistry), intent(in) :: registry
integer, intent(out), optional :: rc
Return Value class(StateItemSpec), allocatable
Calls
Called by
Source Code
   function make_ItemSpec(this, geom, vertical_geom, registry, rc) result(item_spec)
      class(StateItemSpec), allocatable :: item_spec
      class(VariableSpec), intent(in) :: this
      type(ESMF_Geom), intent(in) :: geom
      type(VerticalGeom), intent(in) :: vertical_geom
      type(HierarchicalRegistry), intent(in) :: registry
      integer, optional, intent(out) :: rc
      integer :: status
      type(ActualPtVector) :: dependencies
      select case (this%itemtype%ot)
      case (MAPL_STATEITEM_FIELD%ot)
         allocate(FieldSpec::item_spec)
         item_spec = this%make_FieldSpec(geom, vertical_geom,  _RC)
!!$      case (MAPL_STATEITEM_FIELDBUNDLE)
!!$         allocate(FieldBundleSpec::item_spec)
!!$         item_spec = this%make_FieldBundleSpec(geom, _RC)
      case (MAPL_STATEITEM_SERVICE%ot)
         allocate(ServiceSpec::item_spec)
         item_spec = this%make_ServiceSpec(registry, _RC)
      case (MAPL_STATEITEM_WILDCARD%ot)
         allocate(WildcardSpec::item_spec)
         item_spec = this%make_WildcardSpec(geom, vertical_geom,  _RC)
      case (MAPL_STATEITEM_BRACKET%ot)
         allocate(BracketSpec::item_spec)
         item_spec = this%make_BracketSpec(geom, vertical_geom,  _RC)
      case default
         ! Fail, but still need to allocate a result.
         allocate(InvalidSpec::item_spec)
         _FAIL('Unsupported type.')
      end select
      dependencies = this%make_dependencies(_RC)
      call item_spec%set_dependencies(dependencies)
      _RETURN(_SUCCESS)
   end function make_ItemSpec
Call graph
make_itemspec calls mapl_assert, make_bracketspec, make_dependencies, make_fieldspec, make_servicespec, make_wildcardspec, mapl_return, mapl_verify, set_dependencies
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_bracketspec calls mapl_return, mapl_verify, fill_units
make_dependencies calls mapl_return, of, vector_push_back
make_fieldspec calls mapl_return, mapl_verify, fill_units
make_servicespec calls mapl_return, mapl_verify, of, get_item_spec
make_wildcardspec calls mapl_return, new_fieldspec_geom
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
fill_units calls mapl_assert, mapl_return, NUOPC_FieldDictionaryGetEntry
get_error_message calls at, insert
get_item_spec calls mapl_return, mapl_verify, at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
initialize_advertise calls make_itemspec
initialize calls initialize_advertise