make_LatLonGeomSpec_from_hconfig – MAPL
make_LatLonGeomSpec_from_hconfig Module Function
17 statements
Source File
module function make_LatLonGeomSpec_from_hconfig(hconfig, rc) result(spec) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(LatLonGeomSpec)
Calls
Called by
Source Code
   module function make_LatLonGeomSpec_from_hconfig(hconfig, rc) result(spec)
      type(LatLonGeomSpec) :: spec
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      logical :: is_regional
      integer :: status
      spec%lon_axis = make_LonAxis(hconfig, _RC)
      spec%lat_axis = make_LatAxis(hconfig, _RC)
      associate (im => spec%lon_axis%get_extent(), jm => spec%lat_axis%get_extent())
        spec%decomposition = make_Decomposition(hconfig, dims=[im,jm], _RC)
      end associate
      _RETURN(_SUCCESS)
   end function make_LatLonGeomSpec_from_hconfig
Call graph
make_latlongeomspec_from_hconfig calls get_extent, make_lataxis, make_lonaxis, make_decomposition, mapl_return, mapl_verify, make_latlongeomspec_from_hconfig
get_extent calls get_extent
make_lataxis calls make_lataxis_from_hconfig, make_lataxis_from_metadata
make_lonaxis calls make_lonaxis_from_hconfig, make_lonaxis_from_metadata
make_decomposition calls mapl_return, mapl_verify, esmf_hconfigasi4, esmf_hconfigasi4seq, esmf_hconfigisdefined, make_latlondecomposition, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_lataxis_from_hconfig calls make_lataxis_from_hconfig
make_lataxis_from_metadata calls make_lataxis_from_metadata
make_latlondecomposition calls make_latlondecomposition_current_vm, make_latlondecomposition_vm
make_lonaxis_from_hconfig calls make_lonaxis_from_hconfig
make_lonaxis_from_metadata calls make_lonaxis_from_metadata
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_latlongeomspec calls make_latlongeomspec_from_hconfig
make_geom_spec_from_hconfig calls make_latlongeomspec, make_geom_spec_from_hconfig
make_geom_spec_from_metadata calls make_latlongeomspec, make_geom_spec_from_metadata