make_LonAxis_from_hconfig – MAPL
make_LonAxis_from_hconfig Module Function
23 statements
Source File
module function make_LonAxis_from_hconfig(hconfig, rc) result(axis) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(LonAxis)
Calls
Called by
Source Code
   module function make_LonAxis_from_hconfig(hconfig, rc) result(axis)
      type(LonAxis) :: axis
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: im_world
      real(kind=R8), allocatable :: centers(:), corners(:)
      type(AxisRanges) :: ranges
      logical :: found
      !call MAPL_HConfigGet(hconfig, 'im_world', im_world, found=found, _RC)
      im_world = ESMF_HConfigAsI4(hconfig, keyString='im_world', asOkay=found, _RC)
      _ASSERT(found, '"im_world" not found.')
      _ASSERT(im_world > 0, "Config parameter 'im_world' must be greater than 0.")
      ranges = get_lon_range(hconfig, im_world, _RC)
      centers = MAPL_Range(ranges%center_min, ranges%center_max, im_world, _RC)
      corners = MAPL_Range(ranges%corner_min, ranges%corner_max, im_world+1, _RC)
      axis%CoordinateAxis = CoordinateAxis(centers, corners)
      _RETURN(_SUCCESS)
   end function make_LonAxis_from_hconfig
Call graph
make_lonaxis_from_hconfig calls esmf_hconfigasi4, get_lon_range, mapl_assert, mapl_range, mapl_return, mapl_verify, make_lonaxis_from_hconfig
get_lon_range calls get_lon_range, mapl_assert, mapl_return, mapl_verify, esmf_hconfigasr4seq, esmf_hconfigasstring, esmf_hconfigisdefined
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_range_real32 calls mapl_assert, mapl_return
mapl_range_real64 calls mapl_assert, mapl_return
mapl_throw_exception calls initialize
make_lonaxis calls make_lonaxis_from_hconfig
make_latlongeomspec_from_hconfig calls make_lonaxis, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls make_lonaxis, make_latlongeomspec_from_metadata
test_make_lon_axis_from_hconfig calls make_lonaxis