make_regridder_typesafe – MAPL
make_regridder_typesafe Function
24 statements
Source File
private function make_regridder_typesafe(this, spec, rc) result(regriddr)
Type Bound
EsmfRegridderFactory
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridderFactory), intent(inout) :: this
type(RegridderSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value class(Regridder), allocatable
Calls
Called by
Source Code
   function make_regridder_typesafe(this, spec, rc) result(regriddr)
      class(Regridder), allocatable  :: regriddr
      class(EsmfRegridderFactory), intent(inout) :: this
      type(RegridderSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Routehandle) :: routehandle
      type(RoutehandleSpec) :: rh_spec
      regriddr = NULL_REGRIDDER
      associate (p => spec%get_param())
        select type (p)
        type is (EsmfRegridderParam)
!#           routehandle = make_routehandle(spec%get_geom_in(), spec%get_geom_out(), p%get_routehandle_param(), _RC)
           rh_spec = RoutehandleSpec(spec%get_geom_in(), spec%get_geom_out(), p%get_routehandle_param())
           routehandle = this%rh_manager%get_routehandle(rh_spec, _RC)
        class default
           _FAIL('Wrong RegridderParam subclass passed to EsmfRegridderFactory.')
        end select
      end associate
      deallocate(regriddr) ! workaround for gfortran 12.3
      regriddr = EsmfRegridder(routehandle=routehandle, regridder_spec=spec)
      _RETURN(_SUCCESS)
   end function make_regridder_typesafe
Call graph
make_regridder_typesafe calls esmfregridder, get_routehandle_param, mapl_assert, get_geom_in, get_geom_out, get_param, get_routehandle, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_routehandle calls mapl_return, mapl_verify, find, of, add_routehandle, vector_back, vector_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_routehandle calls mapl_assert, mapl_return, mapl_verify, find, vector_begin, make_routehandle, vector_push_back
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_routehandle calls make_routehandle_from_param
vector_push_back calls resize, vector_grow_to
make_regridder calls make_regridder
get_regridder calls make_regridder
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder