make_ServiceSpec – MAPL
make_ServiceSpec Function
31 statements
Source File
private function make_ServiceSpec(this, registry, rc) result(service_spec)
Type Bound
VariableSpec
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: this
type(HierarchicalRegistry), intent(in) :: registry
integer, intent(out), optional :: rc
Return Value type(ServiceSpec)
Calls
Called by
Source Code
   function make_ServiceSpec(this, registry, rc) result(service_spec)
      type(ServiceSpec) :: service_spec
      class(VariableSpec), intent(in) :: this
      type(HierarchicalRegistry), intent(in) :: registry
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i, n
      type(StateItemSpecPtr), allocatable :: specs(:)
      type(ActualConnectionPt) :: a_pt
      if (.not. valid(this)) then
         _RETURN(_FAILURE)
      end if
      n = this%service_items%size()
      allocate(specs(n))
      do i = 1, n
         a_pt = ActualConnectionPt(VirtualConnectionPt(ESMF_STATEINTENT_INTERNAL, this%service_items%of(i)))
         specs(i)%ptr => registry%get_item_spec(a_pt, _RC)
      end do
      service_spec = ServiceSpec(specs)
      _RETURN(_SUCCESS)
   contains
      logical function valid(this) result(is_valid)
         class(VariableSpec), intent(in) :: this
         is_valid = .false. ! unless
         if (.not. this%itemtype == MAPL_STATEITEM_SERVICE) return
         is_valid = .true.
      end function valid
   end function make_ServiceSpec
Call graph
make_servicespec calls of, get_item_spec, mapl_return, mapl_verify
get_item_spec calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
map_at_rc calls map_find
make_itemspec calls make_servicespec
initialize_advertise calls make_itemspec
initialize calls initialize_advertise