make_esmf_info – MAPL
make_esmf_info Function
48 statements
Source File
public function make_esmf_info(num_levels, vert_stagger, num_ungridded, names, units_array, coordinates, rc) result(info)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: num_levels
character(len=*), intent(in), optional :: vert_stagger
integer, intent(in), optional :: num_ungridded
character(len=*), intent(in), optional :: names(:)
character(len=*), intent(in), optional :: units_array(:)
real, intent(in), optional :: coordinates(:,:)
integer, intent(out), optional :: rc
Return Value type(ESMF_Info)
Calls
Called by
Source Code
   function make_esmf_info(num_levels, vert_stagger, num_ungridded, names, units_array, coordinates, rc) &
         result(info)
      type(ESMF_Info) :: info
      integer, optional, intent(in) :: num_levels
      character(len=*), optional, intent(in) :: vert_stagger
      integer, optional, intent(in) :: num_ungridded
      character(len=*), optional, intent(in) :: names(:)
      character(len=*), optional, intent(in) :: units_array(:)
      real, optional, intent(in) :: coordinates(:, :)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: num_levels_, num_ungridded_
      character(len=:), allocatable :: vert_stagger_
      num_ungridded_ = -1
      num_levels_ = NUM_LEVELS_DEFAULT
      if(present(num_levels)) num_levels_ = num_levels
      vert_stagger_ = VERT_STAGGER_DEFAULT
      if(present(vert_stagger)) vert_stagger_ = vert_stagger
      info = ESMF_InfoCreate(_RC)
      call make_vertical_dim(info, vert_stagger_, _RC)
      call ESMF_InfoSet(info, KEY_NUM_LEVELS, num_levels_, _RC)
      SET_RC(status)
      if(present(names) .and. present(units_array)) then
         if(size(names) /= size(units_array)) return
         num_ungridded_ = size(names)
      end if
      if(present(num_ungridded)) then
         if((num_ungridded_ >= 0) .and. (num_ungridded /= num_ungridded)) return
         num_ungridded_ = num_ungridded
      end if
      call make_ungridded_dims_info(info, num_ungridded_, names, units_array, coordinates, _RC)
      SET_RC(status)
   end function make_esmf_info
Call graph
make_esmf_info calls ESMF_InfoCreate, ESMF_InfoSet, anyexceptions, assert_that, make_ungridded_dims_info, make_vertical_dim, sourcelocation
make_ungridded_dims_info calls ESMF_InfoSet, anyexceptions, assert_that, sourcelocation, make_dim_key
make_vertical_dim calls ESMF_InfoSet, anyexceptions, assert_that, sourcelocation
make_dim_key calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception
test_get_num_levels calls make_esmf_info
test_get_ungridded_dims calls make_esmf_info
test_get_vertical_dim_spec_names calls make_esmf_info