make_file_metadata – MAPL
make_file_metadata Module Function
19 statements
Source File
module function make_file_metadata(this, geom_spec, unusable, chunksizes, rc) result(file_metadata) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
class(GeomSpec), intent(in) :: geom_spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: chunksizes(:)
integer, intent(out), optional :: rc
Return Value type(FileMetadata)
Calls
Called by
Source Code
   module function make_file_metadata(this, geom_spec, unusable, chunksizes, rc) result(file_metadata)
      type(FileMetadata) :: file_metadata
      class(LatLonGeomFactory), intent(in) :: this
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(in) :: chunksizes(:)
      class(GeomSpec), intent(in) :: geom_spec
      integer, optional, intent(out) :: rc
      integer :: status
      file_metadata = FileMetadata()
      select type (geom_spec)
      type is (LatLonGeomSpec)
         file_metadata = typesafe_make_file_metadata(geom_spec, chunksizes=chunksizes, _RC)
      class default
         _FAIL('geom_spec is not of dynamic type LatLonGeomSpec.')
      end select
      _RETURN(_SUCCESS)
   end function make_file_metadata
Call graph
make_file_metadata calls mapl_assert, mapl_return, mapl_verify, typesafe_make_file_metadata, make_file_metadata
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
typesafe_make_file_metadata calls mapl_return, get_centers, get_extent, get_lat_axis, get_lon_axis, add_attribute, add_const_value, add_dimension, add_variable