make_decomposition – MAPL
make_decomposition Function
42 statements
Source File
function make_decomposition(hconfig, dims, rc) result(decomp)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(in) :: dims(2)
integer, intent(out), optional :: rc
Return Value type(LatLonDecomposition)
Calls
Called by
Source Code
   function make_decomposition(hconfig, dims, rc) result(decomp)
      type(LatLonDecomposition) :: decomp
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, intent(in) :: dims(2)
      integer, optional, intent(out) :: rc
      integer, allocatable :: ims(:), jms(:)
      integer :: nx, ny
      integer :: status
      logical :: has_ims, has_jms, has_nx, has_ny
      has_ims = ESMF_HConfigIsDefined(hconfig, keystring='ims', _RC)
      has_jms = ESMF_HConfigIsDefined(hconfig, keystring='jms', _RC)
      _ASSERT(has_ims .eqv. has_jms, 'ims and jms must be both defined or both undefined')
      if (has_ims) then
         ims = ESMF_HConfigAsI4Seq(hconfig, keyString='ims', _RC)
         jms = ESMF_HConfigAsI4Seq(hconfig, keyString='jms', _RC)
         decomp = LatLonDecomposition(ims, jms)
         _RETURN(_SUCCESS)
      end if
      has_nx = ESMF_HConfigIsDefined(hconfig, keystring='nx', _RC)
      has_ny = ESMF_HConfigIsDefined(hconfig, keystring='ny', _RC)
      _ASSERT(has_nx .eqv. has_ny, 'nx and ny must be both defined or both undefined')
      if (has_nx) then
         nx = ESMF_HConfigAsI4(hconfig, keyString='nx', _RC)
         ny = ESMF_HConfigAsI4(hconfig, keyString='ny', _RC)
         decomp = LatLonDecomposition(dims, topology=[nx, ny])
         _RETURN(_SUCCESS)
      end if
      ! Invent a decomposition
      decomp = make_LatLonDecomposition(dims, _RC)
      _RETURN(_SUCCESS)
   end function make_decomposition
Call graph
make_decomposition calls esmf_hconfigasi4, esmf_hconfigasi4seq, esmf_hconfigisdefined, make_latlondecomposition, mapl_assert, mapl_return, mapl_verify
make_latlondecomposition calls make_latlondecomposition_current_vm, make_latlondecomposition_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_latlondecomposition_current_vm calls make_latlondecomposition_current_vm, make_latlondecomposition, mapl_return, mapl_verify, ESMF_VMGetCurrent
make_latlondecomposition_vm calls make_latlondecomposition_vm, mapl_return, mapl_verify, ESMF_VMGet
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_latlongeomspec_from_hconfig calls make_decomposition, make_latlongeomspec_from_hconfig
make_latlongeomspec calls make_latlongeomspec_from_hconfig
make_geom_spec_from_hconfig calls make_latlongeomspec
make_geom_spec_from_metadata calls make_latlongeomspec