make_LatLonGeomSpec_from_metadata – MAPL
make_LatLonGeomSpec_from_metadata Module Function
20 statements
Source File
module function make_LatLonGeomSpec_from_metadata(file_metadata, rc) result(spec) Interface →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value type(LatLonGeomSpec)
Calls
Called by
Source Code
   module function make_LatLonGeomSpec_from_metadata(file_metadata, rc) result(spec)
      type(LatLonGeomSpec) :: spec
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      integer :: status
      type(LonAxis) :: lon_axis
      type(LatAxis) :: lat_axis
      type(LatLonDecomposition) :: decomposition
      lon_axis = make_LonAxis(file_metadata, _RC)
      lat_axis = make_LatAxis(file_metadata, _RC)
      associate (im_world => lon_axis%get_extent(), jm_world => lat_axis%get_extent())
        decomposition = make_LatLonDecomposition([im_world, jm_world], _RC)
      end associate
      spec = LatLonGeomSpec(lon_axis, lat_axis, decomposition)
      _RETURN(_SUCCESS)
   end function make_LatLonGeomSpec_from_metadata
Call graph
make_latlongeomspec_from_metadata calls get_extent, make_lataxis, make_latlondecomposition, make_lonaxis, mapl_return, mapl_verify, make_latlongeomspec_from_metadata
get_extent calls get_extent
make_lataxis calls make_lataxis_from_hconfig, make_lataxis_from_metadata
make_latlondecomposition calls make_latlondecomposition_current_vm, make_latlondecomposition_vm
make_lonaxis calls make_lonaxis_from_hconfig, make_lonaxis_from_metadata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_lataxis_from_hconfig calls make_lataxis_from_hconfig
make_lataxis_from_metadata calls make_lataxis_from_metadata
make_latlondecomposition_current_vm calls make_latlondecomposition_current_vm
make_latlondecomposition_vm calls make_latlondecomposition_vm
make_lonaxis_from_hconfig calls make_lonaxis_from_hconfig
make_lonaxis_from_metadata calls make_lonaxis_from_metadata
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_latlongeomspec calls make_latlongeomspec_from_metadata
make_geom_spec_from_hconfig calls make_latlongeomspec, make_geom_spec_from_hconfig
make_geom_spec_from_metadata calls make_latlongeomspec, make_geom_spec_from_metadata