make_ungriddedDims – MAPL
make_ungriddedDims Function
37 statements
Source File
public function make_ungriddedDims(info, key, rc) result(ungridded_dims)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
character(len=*), intent(in), optional :: key
integer, intent(out), optional :: rc
Return Value type(UngriddedDims)
Calls
Called by
Source Code
   function make_ungriddedDims(info, key, rc) result(ungridded_dims)
      type(UngriddedDims) :: ungridded_dims
      type(ESMF_Info), intent(in) :: info
      character(*), optional, intent(in) :: key
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: num_ungridded_dims
      integer :: i
      type(ESMF_Info) :: dim_info
      character(:), allocatable :: dim_key
      type(UngriddedDim), allocatable :: dim_specs(:)
      character(:), allocatable :: full_key
      ungridded_dims = UngriddedDims()
      full_key = KEY_NUM_UNGRIDDED_DIMS
      if (present(key)) then
         full_key = key // full_key
      end if
      call MAPL_InfoGet(info, key=full_key, value=num_ungridded_dims, _RC)
      allocate(dim_specs(num_ungridded_dims))
      do i = 1, num_ungridded_dims
         dim_key = make_dim_key(i, _RC)
         if (present(key)) then
            dim_key = key // dim_key
         end if
         dim_info = ESMF_InfoCreate(info, key=dim_key, _RC)
         dim_specs(i) = make_ungriddedDim(dim_info, _RC)
         call ESMF_InfoDestroy(dim_info, _RC)
      end do
      ungridded_dims = UngriddedDims(dim_specs)
      _RETURN(_SUCCESS)
   end function make_ungriddedDims
Call graph
make_ungriddeddims calls ESMF_InfoCreate, ESMF_InfoDestroy, mapl_infoget, make_dim_key, make_ungriddeddim, mapl_return, mapl_verify
make_dim_key calls mapl_return, mapl_assert
make_ungriddeddim calls mapl_infoget, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_ungridded_dims_bundle_info calls make_ungriddeddims
mapl_fieldbundleget calls make_ungriddeddims
test_make_ungridded_dims calls make_ungriddeddims
teardown_bundle calls mapl_fieldbundleget
test_change_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_units calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_get_ungridded_dims calls get_ungridded_dims_bundle_info
test_same_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle