make_dependencies – MAPL
make_dependencies Function
15 statements
Source File
private function make_dependencies(this, rc) result(dependencies)
Type Bound
VariableSpec
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: this
integer, intent(out), optional :: rc
Return Value type(ActualPtVector)
Calls
Called by
Source Code
   function make_dependencies(this, rc) result(dependencies)
      type(ActualPtVector) :: dependencies
      class(VariableSpec), intent(in) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      type(ActualConnectionPt) :: a_pt
      dependencies = ActualPtVector()
      do i = 1, this%dependencies%size()
         a_pt = ActualConnectionPt(VirtualConnectionPt(ESMF_STATEINTENT_EXPORT, this%dependencies%of(i)))
         call dependencies%push_back(a_pt)
      end do
      _RETURN(_SUCCESS)
   end function make_dependencies
Call graph
make_dependencies calls of, mapl_return, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
mapl_throw_exception calls initialize
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
make_itemspec calls make_dependencies
initialize_advertise calls make_itemspec
initialize calls initialize_advertise