make_geom_spec_from_metadata – MAPL
make_geom_spec_from_metadata Module Function
20 statements
Source File
module function make_geom_spec_from_metadata(this, file_metadata, rc) result(geom_spec)
Arguments
Type Intent Optional Attributes Name
class(GeomManager), intent(inout), target :: this
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value class(GeomSpec), allocatable
Calls
Source Code
   module function make_geom_spec_from_metadata(this, file_metadata, rc) result(geom_spec)
      class(GeomSpec), allocatable :: geom_spec
      class(GeomManager), target, intent(inout) :: this
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      class(GeomFactory), pointer :: factory
      integer :: status
      geom_spec = NullGeomSpec()
      factory => find_factory(this%factories, supports_metadata, _RC)
      geom_spec = factory%make_spec(file_metadata, _RC)
      _RETURN(_SUCCESS)
   contains
      logical function supports_metadata(factory)
         class(GeomFactory), intent(in) :: factory
         supports_metadata = factory%supports(file_metadata)
      end function supports_metadata
   end function make_geom_spec_from_metadata
Call graph
make_geom_spec_from_metadata calls mapl_return, mapl_verify, make_spec, find_factory, make_geom_spec_from_metadata, make_latlongeomspec
find_factory calls mapl_return, find_if, mapl_assert, of, vector_begin