make_LonAxis_from_metadata – MAPL
make_LonAxis_from_metadata Module Function
22 statements
Source File
module function make_LonAxis_from_metadata(file_metadata, rc) result(axis) Interface →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value type(LonAxis)
Calls
Called by
Source Code
   module function make_LonAxis_from_metadata(file_metadata, rc) result(axis)
      type(LonAxis) :: axis
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      real(kind=R8), allocatable :: centers(:)
      real(kind=R8), allocatable :: corners(:)
      integer :: im_world
      integer :: status
      character(:), allocatable :: dim_name
      dim_name = get_dim_name(file_metadata, units='degrees east', _RC)
      centers = get_coordinates(file_metadata, dim_name, _RC)
      im_world = size(centers)
      ! Enforce convention for longitude range.
      if (any((centers(2:im_world) - centers(1:im_world-1)) < 0)) then
         where(centers > 180) centers = centers - 360
      end if
      corners = get_lon_corners(centers)
      axis = LonAxis(centers, corners)
      _RETURN(_SUCCESS)
   end function make_LonAxis_from_metadata
Call graph
make_lonaxis_from_metadata calls get_coordinates, get_dim_name, get_lon_corners, mapl_return, mapl_verify, make_lonaxis_from_metadata
get_coordinates calls get_coordinates_dim
get_dim_name calls get_dim_name, mapl_return, mapl_verify, ESMF_UtilStringLowerCase, mapl_assert, of, get_attribute, get_dimensions, get_string, get_variables, is_attribute_present, map_ftn_begin, map_ftn_end, map_iter_next
get_lon_corners calls get_lon_corners
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_coordinates_dim calls get_coordinates_dim
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_lonaxis calls make_lonaxis_from_metadata
make_latlongeomspec_from_hconfig calls make_lonaxis, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls make_lonaxis, make_latlongeomspec_from_metadata
test_make_lon_axis_from_hconfig calls make_lonaxis