make_LatAxis_from_hconfig – MAPL
make_LatAxis_from_hconfig Module Function
25 statements
Source File
module function make_LatAxis_from_hconfig(hconfig, rc) result(axis) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(LatAxis)
Calls
Called by
Source Code
   module function make_LatAxis_from_hconfig(hconfig, rc) result(axis)
      type(LatAxis) :: axis
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: jm_world
      real(kind=R8), allocatable :: centers(:), corners(:)
      type(AxisRanges) :: ranges
      logical :: found
      jm_world = ESMF_HConfigAsI4(hconfig, keyString='jm_world', asOkay=found, _RC)
      _ASSERT(found, '"jm_world" not found.')
      _ASSERT(jm_world > 0, 'jm_world must be greater than 1')
      ranges = get_lat_range(hconfig, jm_world, _RC)
      centers = MAPL_Range(ranges%center_min, ranges%center_max, jm_world, _RC)
      corners = MAPL_Range(ranges%corner_min, ranges%corner_max, jm_world+1, _RC)
      ! IMPORTANT: this fix must be _after the call to MAPL_Range.
      if (corners(1) < -90.d0) corners(1) = -90.0d0
      if (corners(jm_world+1) > 90.d0) corners(jm_world+1) = 90.0d0
      axis%CoordinateAxis = CoordinateAxis(centers, corners)
      _RETURN(_SUCCESS)
   end function make_LatAxis_from_hconfig
Call graph
make_lataxis_from_hconfig calls esmf_hconfigasi4, get_lat_range, mapl_assert, mapl_range, mapl_return, mapl_verify, make_lataxis_from_hconfig
get_lat_range calls get_lat_range, mapl_assert, mapl_return, mapl_verify, esmf_hconfigasr4seq, esmf_hconfigasstring, esmf_hconfigisdefined
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_range_real32 calls mapl_assert, mapl_return
mapl_range_real64 calls mapl_assert, mapl_return
mapl_throw_exception calls initialize
make_lataxis calls make_lataxis_from_hconfig
make_latlongeomspec_from_hconfig calls make_lataxis, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls make_lataxis, make_latlongeomspec_from_metadata