make_action – MAPL
make_action Function
10 statements
Source File
private function make_action(this, dst_spec, rc) result(action)
Uses
mapl3g_ExtensionAction
mapl3g_NullAction
Type Bound
StateItemSpec
Arguments
Type Intent Optional Attributes Name
class(StateItemSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: dst_spec
integer, intent(out), optional :: rc
Return Value class(ExtensionAction), allocatable
Calls
Called by
Source Code
   function make_action(this, dst_spec, rc) result(action)
      use mapl3g_ExtensionAction
      use mapl3g_NullAction
      class(ExtensionAction), allocatable :: action
      class(StateItemSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: dst_spec
      integer, optional, intent(out) :: rc
      action = NullAction()
      _FAIL('Subclass has not implemented make_action')
   end function make_action
Call graph
make_action calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_state_extension calls make_action
test_create_extension calls make_action
extend_ calls add_state_extension
connect_sibling calls extend_
connect calls connect_sibling