make_geom – MAPL
make_geom Function
22 statements
Source File
public function make_geom(geom_mgr, hconfig, rc) result(geom)
Arguments
Type Intent Optional Attributes Name
type(GeomManager), intent(inout) :: geom_mgr
type(ESMF_HConfig), intent(in), optional :: hconfig
integer, intent(out), optional :: rc
Return Value type(ESMF_Geom)
Calls
Called by
Source Code
   function make_geom(geom_mgr, hconfig, rc) result(geom)
      type(ESMF_Geom) :: geom
      type(GeomManager), intent(inout) :: geom_mgr
      type(ESMF_HConfig), optional, intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      type(MaplGeom), pointer :: mapl_geom
      integer :: status
      type(ESMF_HConfig) :: hconfig_
      hconfig_ = ESMF_HConfigCreate(content="{class: latlon, im_world: 12, jm_world: 13, pole: PC, dateline: DC, nx: 1, ny: 1}", &
           _RC)
      if (present(hconfig)) hconfig_ = hconfig
      mapl_geom => geom_mgr%get_mapl_geom(hconfig_, _RC)
      geom = mapl_geom%get_geom()
      if (present(rc)) rc = 0
   end function make_geom
Call graph
make_geom calls ESMF_HConfigCreate, anyexceptions, assert_that, get_geom, get_mapl_geom, sourcelocation
test_basic calls make_geom
test_do_not_reuse_regridder calls make_geom
test_regrid_2d_vector calls make_geom
test_regrid_3d calls make_geom
test_regrid_bracket calls make_geom
test_regrid_values calls make_geom
test_reuse_regridder calls make_geom