make_lataxis_from_metadata – MAPL
make_lataxis_from_metadata Module Function
22 statements
Source File
module function make_lataxis_from_metadata(file_metadata, rc) result(axis) Interface →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value type(LatAxis)
Calls
Called by
Source Code
   module function make_lataxis_from_metadata(file_metadata, rc) result(axis)
      type(LatAxis) :: axis
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      real(kind=R8), allocatable :: centers(:)
      real(kind=R8), allocatable :: corners(:)
      integer :: jm_world
      integer :: status
      character(:), allocatable :: dim_name
      dim_name = get_dim_name(file_metadata, units='degrees north', _RC)
      centers = get_coordinates(file_metadata, dim_name, _RC)
      jm_world = size(centers)
      call fix_bad_pole(centers)
      corners = get_lat_corners(centers)
      ! fix corners
      if (corners(1) < -90) corners(1) = -90
      if (corners(jm_world+1) > 90) corners(jm_world+1) = 90
      axis = LatAxis(centers, corners)
      _RETURN(_SUCCESS)
   end function make_lataxis_from_metadata
Call graph
make_lataxis_from_metadata calls fix_bad_pole, get_coordinates, get_dim_name, get_lat_corners, mapl_return, mapl_verify, make_lataxis_from_metadata
fix_bad_pole calls fix_bad_pole
get_coordinates calls get_coordinates_dim
get_dim_name calls get_dim_name, mapl_return, mapl_verify, ESMF_UtilStringLowerCase, mapl_assert, of, get_attribute, get_dimensions, get_string, get_variables, is_attribute_present, map_ftn_begin, map_ftn_end, map_iter_next
get_lat_corners calls get_lat_corners
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_coordinates_dim calls get_coordinates_dim
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_lataxis calls make_lataxis_from_metadata
make_latlongeomspec_from_hconfig calls make_lataxis, make_latlongeomspec_from_hconfig
make_latlongeomspec_from_metadata calls make_lataxis, make_latlongeomspec_from_metadata