make_LatLonDecomposition_vm – MAPL
make_LatLonDecomposition_vm Module Function
13 statements
Source File
module function make_LatLonDecomposition_vm(dims, vm, rc) result(decomp) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dims(2)
type(ESMF_VM), intent(in) :: vm
integer, intent(out), optional :: rc
Return Value type(LatLonDecomposition)
Calls
Called by
Source Code
   module function make_LatLonDecomposition_vm(dims, vm, rc) result(decomp)
      type(LatLonDecomposition) :: decomp
      integer, intent(in) :: dims(2)
      type(ESMF_VM), intent(in) :: vm
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: petCount
      call ESMF_VMGet(vm, petCount=petCount, _RC)
      decomp = LatLonDecomposition(dims, petCount=petCount)
      _RETURN(_SUCCESS)
   end function make_LatLonDecomposition_vm
Call graph
make_latlondecomposition_vm calls ESMF_VMGet, mapl_return, mapl_verify, make_latlondecomposition_vm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_latlondecomposition calls make_latlondecomposition_vm
make_decomposition calls make_latlondecomposition
make_latlondecomposition_current_vm calls make_latlondecomposition, make_latlondecomposition_current_vm
make_latlongeomspec_from_metadata calls make_latlondecomposition, make_latlongeomspec_from_metadata
make_latlongeomspec_from_hconfig calls make_decomposition