make_routehandle_from_param – MAPL
make_routehandle_from_param Function
31 statements
Source File
private function make_routehandle_from_param(geom_in, geom_out, param, rc) result(routehandle)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom_in
type(ESMF_Geom), intent(in) :: geom_out
type(RoutehandleParam), intent(in) :: param
integer, intent(out), optional :: rc
Return Value type(ESMF_RouteHandle)
Calls
Called by
Source Code
   function make_routehandle_from_param(geom_in, geom_out, param, rc) result(routehandle)
      type(ESMF_Routehandle) :: routehandle
      type(ESMF_Geom), intent(in) :: geom_in
      type(ESMF_Geom), intent(in) :: geom_out
      type(RoutehandleParam), intent(in) :: param
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Field) :: field_in
      type(ESMF_Field) :: field_out
      integer :: srcTermProcessing=0
      field_in = ESMF_FieldEmptyCreate(name='tmp', _RC)
      call ESMF_FieldEmptySet(field_in, geom_in, _RC)
      call ESMF_FieldEmptyComplete(field_in, typekind=ESMF_TypeKind_R4, _RC)
      field_out = ESMF_FieldEmptyCreate(name='tmp', _RC)
      call ESMF_FieldEmptySet(field_out, geom_out, _RC)
      call ESMF_FieldEmptyComplete(field_out, typekind=ESMF_TypeKind_R4, _RC)
      call ESMF_FieldRegridStore(field_in, field_out, &
           srcMaskValues=param%srcMaskValues, &
           dstMaskValues=param%dstMaskValues, &
           regridmethod=param%regridmethod, &
           polemethod=param%polemethod, &
           regridPoleNPnts=param%regridPoleNPnts, &
           linetype=param%linetype, &
           normtype=param%normtype, &
           extrapmethod=param%extrapmethod, &
           extrapNumSrcPnts=param%extrapNumSrcPnts, &
           extrapDistExponent=param%extrapDistExponent, &
           extrapNumLevels=param%extrapNumLevels, &
           unmappedaction=param%unmappedaction, &
           ignoreDegenerate=param%ignoreDegenerate, &
           srcTermProcessing=srcTermProcessing, &
           routehandle=routehandle, &
           _RC)
      call ESMF_FieldDestroy(field_in, noGarbage=.true., _RC)
      call ESMF_FieldDestroy(field_out, noGarbage=.true., _RC)
      _RETURN(_SUCCESS)
   end function make_routehandle_from_param
Call graph
make_routehandle_from_param calls ESMF_FieldRegridStore, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_routehandle calls make_routehandle_from_param, make_routehandle_from_spec
add_routehandle calls make_routehandle
make_routehandle_from_spec calls make_routehandle
get_routehandle calls add_routehandle
make_regridder_typesafe calls get_routehandle