make_ungriddedDim – MAPL
make_ungriddedDim Function
14 statements
Source File
public function make_ungriddedDim(info, rc) result(dim)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(in) :: info
integer, intent(out), optional :: rc
Return Value type(UngriddedDim)
Calls
Called by
Source Code
   function make_ungriddedDim(info, rc) result(dim)
      type(UngriddedDim) :: dim
      type(ESMF_Info), intent(in) :: info
      integer, optional, intent(out) :: rc
      integer :: status
      call MAPL_InfoGet(info, key='name', value=dim%name, _RC)
      call MAPL_InfoGet(info, key='units', value=dim%units, _RC)
      call MAPL_InfoGet(info, key='coordinates', values=dim%coordinates, _RC)
      _RETURN(_SUCCESS)
   end function make_ungriddedDim
Call graph
make_ungriddeddim calls mapl_infoget, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_ungriddeddims calls make_ungriddeddim
test_make_ungridded_dim calls make_ungriddeddim
get_ungridded_dims_bundle_info calls make_ungriddeddims
mapl_fieldbundleget calls make_ungriddeddims
test_make_ungridded_dims calls make_ungriddeddims
teardown_bundle calls mapl_fieldbundleget
test_change_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_units calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_get_ungridded_dims calls get_ungridded_dims_bundle_info
test_same_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle