make_LatLonDecomposition_current_vm – MAPL
make_LatLonDecomposition_current_vm Module Function
13 statements
Source File
module function make_LatLonDecomposition_current_vm(dims, rc) result(decomp) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dims(2)
integer, intent(out), optional :: rc
Return Value type(LatLonDecomposition)
Calls
Called by
Source Code
   module function make_LatLonDecomposition_current_vm(dims, rc) result(decomp)
      type(LatLonDecomposition) :: decomp
      integer, intent(in) :: dims(2)
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_VM) :: vm
      call ESMF_VMGetCurrent(vm, _RC)
      decomp = make_LatLonDecomposition(dims, vm, _RC)
      _RETURN(_SUCCESS)
   end function make_LatLonDecomposition_current_vm
Call graph
make_latlondecomposition_current_vm calls ESMF_VMGetCurrent, make_latlondecomposition, mapl_return, mapl_verify, make_latlondecomposition_current_vm
make_latlondecomposition calls make_latlondecomposition_current_vm, make_latlondecomposition_vm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_latlondecomposition_vm calls make_latlondecomposition_vm, mapl_return, mapl_verify, ESMF_VMGet
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_decomposition calls make_latlondecomposition
make_latlongeomspec_from_metadata calls make_latlondecomposition, make_latlongeomspec_from_metadata
make_latlongeomspec_from_hconfig calls make_decomposition