make_WildcardSpec – MAPL
make_WildcardSpec Function
23 statements
Source File
private function make_WildcardSpec(this, geom, vertical_geom, rc) result(wildcard_spec)
Type Bound
VariableSpec
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: this
type(ESMF_Geom), intent(in) :: geom
type(VerticalGeom), intent(in) :: vertical_geom
integer, intent(out), optional :: rc
Return Value type(WildcardSpec)
Calls
Called by
Source Code
   function make_WildcardSpec(this, geom, vertical_geom, rc) result(wildcard_spec)
      type(WildcardSpec) :: wildcard_spec
      class(VariableSpec), intent(in) :: this
      type(ESMF_Geom), intent(in) :: geom
      type(VerticalGeom), intent(in) :: vertical_geom
      integer, optional, intent(out) :: rc
      integer :: status
      type(FieldSpec) :: field_spec
      field_spec = new_FieldSpec_geom(geom=geom, vertical_geom=vertical_geom, &
           vertical_dim=this%vertical_dim_spec, typekind=this%typekind, ungridded_dims=this%ungridded_dims, &
           attributes=this%attributes, default_value=this%default_value)
      wildcard_spec = WildCardSpec(field_spec)
      _RETURN(_SUCCESS)
   contains
      logical function valid(this) result(is_valid)
         class(VariableSpec), intent(in) :: this
         is_valid = .false. ! unless
         if (allocated(this%standard_name)) return
         if (allocated(this%units)) return ! maybe this can be relaxed - match only thisgs that have same units?
         if (this%attributes%size() > 0) return
         if (allocated(this%default_value)) return
         is_valid = .true.
      end function valid
   end function make_WildcardSpec
Call graph
make_wildcardspec calls mapl_return, new_fieldspec_geom
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_itemspec calls make_wildcardspec
initialize_advertise calls make_itemspec
initialize calls initialize_advertise