make_subFieldBundles_ordinary – MAPL
make_subFieldBundles_ordinary Function
39 statements
Source File
private function make_subFieldBundles_ordinary(bundle, num_grids, unusable, rc) result(sub_bundles)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
integer, intent(in) :: num_grids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle), allocatable, (:)
Calls
Called by
Source Code
    function make_subFieldBundles_ordinary(bundle, num_grids, unusable, rc) result(sub_bundles)
       type(ESMF_FieldBundle), allocatable :: sub_bundles(:)
       type(ESMF_FieldBundle), intent(in) :: bundle
       integer, intent(in) :: num_grids
       class(KeywordEnforcer), optional, intent(in) :: unusable
       integer, optional, intent(out) :: rc
       integer :: i, j, num_fields, status
       type(ESMF_Field), allocatable :: field_list(:)
       type(ESMF_Field), allocatable :: subfields(:)
       character(len=ESMF_MAXSTR) :: name
       type(ESMF_Info) :: info_in, info_out
       allocate(sub_bundles(num_grids))
       ! get number of fields and field list from field bundle
       call ESMF_FieldBundleGet(bundle, fieldCount=num_fields, name=name, _RC)
       allocate(field_list(num_fields))
       call ESMF_FieldBundleGet(bundle, fieldList=field_list, _RC)
       ! make subfields for each field and add each subfield to corresponding field bundle
       do i = 1, num_grids
          sub_bundles(i) = ESMF_FieldBundleCreate(name=name, _RC)
          call ESMF_InfoGetFromHost(bundle, info_in, _RC)
          call ESMF_InfoGetFromHost(sub_bundles(i), info_out, _RC)
          call ESMF_InfoSet(info_out, key="", value=info_in, _RC)
       end do
       do i = 1, size(field_list)
          subfields = make_subfields(field_list(i), num_grids, _RC)
          do j = 1, size(subfields)
             call ESMF_FieldBundleAdd(sub_bundles(j), subfields(j:j), _RC)
          end do
       end do
       _RETURN(ESMF_SUCCESS)
       _UNUSED_DUMMY(unusable)
    end function make_subFieldBundles_ordinary
Call graph
make_subfieldbundles_ordinary calls ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_fieldbundleadd, esmf_fieldbundlecreate, esmf_fieldbundleget, make_subfields, mapl_return, mapl_verify
make_subfields calls make_subfields_from_num_grids
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_subfields_from_num_grids calls ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify, esmf_fieldcreate, esmf_fieldget, make_subgrids, find_bounds, mapl_gridget
mapl_throw_exception calls initialize
make_subgrids calls make_subgrids_from_bounds, make_subgrids_from_num_grids
mapl_gridget calls ESMF_InfoGetFromHost, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
make_subfieldbundles calls make_subfieldbundles_ordinary
make_substates_from_num_grids calls make_subfieldbundles, make_substates
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates