make_child_name – MAPL
make_child_name Function
19 statements
Source File
public function make_child_name(collection_name, rc) result(child_name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: collection_name
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function make_child_name(collection_name, rc) result(child_name)
      character(len=:), allocatable :: child_name
      character(len=*), intent(in) :: collection_name
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      character(*), parameter :: ESCAPE = '\'
      child_name = ''
      do i = 1, len(collection_name)
         associate (c => collection_name(i:i))
           if (c == '.') then
              child_name = child_name // ESCAPE
           end if
           child_name = child_name // c
         end associate
     end do
      _RETURN(_SUCCESS)
   end function make_child_name
Call graph
make_child_name calls mapl_return
mapl_return calls at, insert, mapl_throw_exception
setservices calls make_child_name, setservices
test_make_child_name calls make_child_name