make_gc_t – MAPL
make_gc_t Function
16 statements
Source File
public function make_gc_t(rc) result(gc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Return Value type(GC_T)
Calls
Called by
Source Code
   function make_gc_t(rc) result(gc)
      type(GC_T) :: gc
      integer, optional, intent(out) :: rc
      integer :: status
      gc%gridcomp = ESMF_GridcompCreate(name='foo',_RC)
      gc%importState = ESMF_StateCreate(_RC)
      gc%exportState = ESMF_StateCreate(_RC)
      gc%clock = create_clock(_RC)
      call ESMF_GridCompSetServices(gc%gridcomp, setServices, _RC)
      rc = 0
   end function make_gc_t
Call graph
make_gc_t calls ESMF_GridCompCreate, esmf_gridcompsetservices, esmf_statecreate, create_clock, mapl_verify
create_clock calls mapl_verify, ESMF_CalendarSetDefault, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
main calls make_gc_t