make_mapl_geom_from_spec – MAPL
make_mapl_geom_from_spec Module Function
31 statements
Source File
module function make_mapl_geom_from_spec(this, spec, rc) result(mapl_geom)
Uses
gftl_StringVector
Arguments
Type Intent Optional Attributes Name
class(GeomManager), intent(inout), target :: this
class(GeomSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(MaplGeom)
Calls
Source Code
   module function make_mapl_geom_from_spec(this, spec, rc) result(mapl_geom)
      use gftl_StringVector
      type(MaplGeom) :: mapl_geom
      class(GeomManager), target, intent(inout) :: this
      class(GeomSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      class(GeomFactory), pointer :: factory
      integer :: status
      integer :: i
      type(ESMF_Geom) :: geom
      type(FileMetadata) :: file_metadata
      type(StringVector) :: gridded_dims
      logical :: found
      found = .false.
      do i = 1, this%factories%size()
         factory => this%factories%of(i)
         if (.not. factory%supports(spec)) cycle
         found = .true.
         exit
      end do
      _ASSERT(found, 'No factory supports spec.')
      geom = factory%make_geom(spec, _RC)
      file_metadata = factory%make_file_metadata(spec, _RC)
      gridded_dims = factory%make_gridded_dims(spec, _RC)
      mapl_geom = MaplGeom(spec, geom, file_metadata, gridded_dims)
      _RETURN(_SUCCESS)
   end function make_mapl_geom_from_spec
Call graph
make_mapl_geom_from_spec calls make_file_metadata, make_geom, make_gridded_dims, mapl_assert, mapl_return, mapl_verify, maplgeom, supports, of
supports_metadata calls supports_metadata, supports, mapl_return, mapl_verify