make_BracketSpec – MAPL
make_BracketSpec Function
29 statements
Source File
private function make_BracketSpec(this, geom, vertical_geom, rc) result(bracket_spec)
Type Bound
VariableSpec
Arguments
Type Intent Optional Attributes Name
class(VariableSpec), intent(in) :: this
type(ESMF_Geom), intent(in) :: geom
type(VerticalGeom), intent(in) :: vertical_geom
integer, intent(out), optional :: rc
Return Value type(BracketSpec)
Calls
Called by
Source Code
   function make_BracketSpec(this, geom, vertical_geom, rc) result(bracket_spec)
      type(BracketSpec) :: bracket_spec
      class(VariableSpec), intent(in) :: this
      type(ESMF_Geom), intent(in) :: geom
      type(VerticalGeom), intent(in) :: vertical_geom
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: units
      type(FieldSpec) :: field_spec
      if (.not. valid(this)) then
         _RETURN(_FAILURE)
      end if
      call fill_units(this, units, _RC)
      field_spec = FieldSpec(geom=geom, vertical_geom = vertical_geom, vertical_dim = this%vertical_dim_spec, typekind=this%typekind, ungridded_dims=this%ungridded_dims, &
           standard_name=this%standard_name, long_name=' ', units=units, attributes=this%attributes, default_value=this%default_value)
      bracket_spec = BracketSpec(field_spec, this%bracket_size)
      _RETURN(_SUCCESS)
   contains
      logical function valid(this) result(is_valid)
         class(VariableSpec), intent(in) :: this
         is_valid = .false. ! unless
         if (.not. this%itemtype == MAPL_STATEITEM_BRACKET) return
         if (.not. allocated(this%standard_name)) return
         if (.not. allocated(this%bracket_size)) return
         is_valid = .true.
      end function valid
   end function make_BracketSpec
Call graph
make_bracketspec calls fill_units, mapl_return, mapl_verify
fill_units calls mapl_return, NUOPC_FieldDictionaryGetEntry, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
make_itemspec calls make_bracketspec
initialize_advertise calls make_itemspec
initialize calls initialize_advertise