make_geom_spec_from_metadata – MAPL
make_geom_spec_from_metadata Module Function
11 statements
Source File
module function make_geom_spec_from_metadata(this, file_metadata, rc) result(geom_spec) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value class(GeomSpec), allocatable
Calls
Called by
Source Code
   module function make_geom_spec_from_metadata(this, file_metadata, rc) result(geom_spec)
      class(GeomSpec), allocatable :: geom_spec
      class(LatLonGeomFactory), intent(in) :: this
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      integer :: status
      geom_spec = make_LatLonGeomSpec(file_metadata, _RC)
      _RETURN(_SUCCESS)
   end function make_geom_spec_from_metadata
Call graph
make_geom_spec_from_metadata calls make_latlongeomspec, mapl_return, mapl_verify, make_geom_spec_from_metadata, make_spec
make_latlongeomspec calls make_latlongeomspec_from_hconfig, make_latlongeomspec_from_metadata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_latlongeomspec_from_hconfig calls make_latlongeomspec_from_hconfig, mapl_return, mapl_verify, get_extent, make_lataxis, make_lonaxis, make_decomposition
make_latlongeomspec_from_metadata calls make_latlongeomspec_from_metadata, mapl_return, mapl_verify, get_extent, make_lataxis, make_latlondecomposition, make_lonaxis
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_geom_spec_from_hconfig calls make_spec
test_make_from_hconfig calls make_spec