make_extension – MAPL
make_extension Function
18 statements
Source File
private function make_extension(this, dst_spec, rc) result(extension)
Type Bound
MockItemSpec
Arguments
Type Intent Optional Attributes Name
class(MockItemSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: dst_spec
integer, intent(out), optional :: rc
Return Value class(StateItemSpec), allocatable
Calls
Source Code
   function make_extension(this, dst_spec, rc) result(extension)
      class(StateItemSpec), allocatable :: extension
      class(MockItemSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: dst_spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(MockItemSpec) :: tmp
      select type(dst_spec)
      type is (MockItemSpec)
         tmp = this%make_extension_typesafe(dst_spec, _RC)
         allocate(extension, source=tmp)
      class default
         _FAIL('incompatible spec')
      end select
      _RETURN(_SUCCESS)
   end function make_extension
Call graph
make_extension calls mapl_assert, make_extension_typesafe, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_extension_typesafe calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize