make_child_hconfig – MAPL
make_child_hconfig Function
18 statements
Source File
public function make_child_hconfig(hconfig, collection_name, rc) result(child_hconfig)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
character(len=*), intent(in) :: collection_name
integer, intent(out), optional :: rc
Return Value type(ESMF_HConfig)
Calls
Called by
Source Code
   function make_child_hconfig(hconfig, collection_name, rc) result(child_hconfig)
      type(ESMF_HConfig) :: child_hconfig
      type(ESMF_HConfig), intent(in) :: hconfig
      character(len=*), intent(in) :: collection_name
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_HConfig) :: collections_hconfig
      collections_hconfig = get_subconfig(hconfig, 'collections', _RC)
      child_hconfig = get_subconfig(collections_hconfig, collection_name, _RC)
      call ESMF_HConfigDestroy(collections_hconfig, _RC)
      call ESMF_HConfigAdd(child_hconfig, content=collection_name, addKeyString='collection_name', _RC)
      _RETURN(_SUCCESS)
   end function make_child_hconfig
Call graph
make_child_hconfig calls ESMF_HConfigAdd, ESMF_HConfigDestroy, get_subconfig, mapl_return, mapl_verify
get_subconfig calls mapl_return, mapl_verify, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
setservices calls make_child_hconfig, setservices
test_make_child_hconfig calls make_child_hconfig