make_vertical_geom – MAPL
make_vertical_geom Subroutine
12 statements
Source File
public subroutine make_vertical_geom(info, num_levels, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Info), intent(inout) :: info
integer, intent(in) :: num_levels
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine make_vertical_geom(info, num_levels, rc)
      type(ESMF_Info), intent(inout) :: info
      integer, intent(in) :: num_levels
      integer, optional, intent(out) :: rc
      integer :: status
      call ESMF_InfoSet(info, KEY_NUM_LEVELS, num_levels, _RC)
      SET_RC(status)
   end subroutine make_vertical_geom
Call graph
make_vertical_geom calls ESMF_InfoSet, anyexceptions, assert_that, sourcelocation
make_esmf_info calls make_vertical_geom
test_get_num_levels calls make_esmf_info
test_get_ungridded_dims calls make_esmf_info
test_get_vertical_dim_spec_names calls make_esmf_info