make_fmt – MAPL
make_fmt Function
5 statements
Source File
private function make_fmt(descriptor) result(fmt)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: descriptor
Return Value character(len=:), allocatable
Called by
Source Code
   function make_fmt(descriptor) result(fmt)
      character(len=:), allocatable :: fmt
      character(len=*), intent(in) :: descriptor
      fmt =  '(*(' // descriptor // ':", "))'
   end function make_fmt
Call graph
get_value_i4 calls make_fmt
get_value_i4seq calls make_fmt
get_value_i8 calls make_fmt
get_value_i8seq calls make_fmt
get_value_logical calls make_fmt
get_value_logical_seq calls make_fmt
get_value_r4 calls make_fmt
get_value_r4seq calls make_fmt
get_value_r8 calls make_fmt
get_value_r8seq calls make_fmt
get_value_string calls make_fmt
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string