make_extension – MAPL
make_extension Function
18 statements
Source File
private function make_extension(this, dst_spec, rc) result(extension)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: dst_spec
integer, intent(out), optional :: rc
Return Value class(StateItemSpec), allocatable
Calls
Source Code
   function make_extension(this, dst_spec, rc) result(extension)
      class(StateItemSpec), allocatable :: extension
      class(FieldSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: dst_spec
      integer, optional, intent(out) :: rc
      integer :: status
      find_mismatch: select type (dst_spec)
      type is (FieldSpec)
         allocate(extension, source=this%make_extension_safely(dst_spec))
         call extension%create(_RC)
      class default
         extension=this
         _FAIL('Unsupported subclass.')
      end select find_mismatch
      _RETURN(_SUCCESS)
   end function make_extension
Call graph
make_extension calls create, mapl_assert, make_extension_safely, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_extension_safely calls update_item
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
update_item calls update_item_geom, update_item_string, update_item_typekind
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match