make_routehandle_from_spec – MAPL
make_routehandle_from_spec Function
10 statements
Source File
private function make_routehandle_from_spec(spec, rc) result(routehandle)
Arguments
Type Intent Optional Attributes Name
type(RoutehandleSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(ESMF_RouteHandle)
Calls
Called by
Source Code
   function make_routehandle_from_spec(spec, rc) result(routehandle)
      type(ESMF_Routehandle) :: routehandle
      type(RoutehandleSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      routehandle = make_routehandle(spec%geom_in, spec%geom_out, spec%rh_param, _RC)
      _RETURN(_SUCCESS)
   end function make_routehandle_from_spec
Call graph
make_routehandle_from_spec calls make_routehandle, mapl_return, mapl_verify
make_routehandle calls make_routehandle_from_param, make_routehandle_from_spec
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_routehandle_from_param calls mapl_return, mapl_verify, ESMF_FieldRegridStore, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset
mapl_throw_exception calls initialize