make_geom – MAPL
make_geom Function
17 statements
Source File
public function make_geom(rc) result(geom)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: rc
Return Value type(ESMF_Geom)
Calls
Called by
Source Code
   function make_geom(rc) result(geom)
      integer, intent(out) :: rc
      type(ESMF_Geom) :: geom
      type(ESMF_Grid) :: grid
      integer :: status
      type(ESMF_HConfig) :: hconfig
      type(GeomManager), pointer :: geom_mgr
      class(GeomSpec), allocatable :: geom_spec
      type(MaplGeom), pointer :: mapl_geom
      rc = 0
      geom_mgr => get_geom_manager()
      hconfig = ESMF_HConfigCreate(content='{class: latlon, im_world: 6, jm_world: 7, pole: PC, dateline: DC}', _RC)
      mapl_geom => geom_mgr%get_mapl_geom(hconfig, _RC)
      geom = mapl_geom%get_geom()
   end function make_geom
Call graph
make_geom calls ESMF_HConfigCreate, get_geom, get_geom_manager, get_mapl_geom, mapl_verify
mapl_verify calls mapl_throw_exception
setup calls make_geom
test_get_coordinate_field_change_units_center calls make_geom, setup
test_get_coordinate_field_change_units_edge calls make_geom, setup
test_get_coordinate_field_simple calls make_geom, setup
test_created_fields_have_num_levels calls setup