makeMetadata – MAPL
makeMetadata Subroutine
14 statements
Source File
private subroutine makeMetadata(file, collection_id, metadata, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file
integer, intent(in) :: collection_id
type(FileMetadataUtils), intent(inout), pointer :: metadata
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine makeMetadata(file,collection_id,metadata,rc)
        character(len=*), intent(in   ) :: file
        integer, intent(in)                       :: collection_id
        type(FileMetadataUtils), pointer, intent(inout)   :: metadata
        integer, optional,          intent(out  ) :: rc
        type(MAPLDataCollection), pointer :: collection => null()
        integer :: status
        Collection => DataCollections%at(collection_id)
        metadata => collection%find(file, _RC)
        call lgr%debug(' Retrieving formatter for: %a', trim(file))
        _RETURN(_SUCCESS)
     end subroutine makeMetadata
Call graph
makemetadata calls at, debug, find_, mapl_return, mapl_verify
find_ calls mapl_return, mapl_verify, at, insert, next, erase, make_factory, make_grid, create, get_dimensions, v_back, v_begin, v_front, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_dimensions calls get_dimensions
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
v_push_back calls resize, v_grow_to
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls makemetadata, getclimyear, getlevs
mapl_extdatagetfstarttime calls makemetadata
updatebrackettime calls makemetadata
run_ calls mapl_extdatagetfstarttime, updatebrackettime