make_action – MAPL
make_action Function
33 statements
Source File
private function make_action(this, dst_spec, rc) result(action)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
class(StateItemSpec), intent(in) :: dst_spec
integer, intent(out), optional :: rc
Return Value class(ExtensionAction), allocatable
Calls
Called by
Source Code
   function make_action(this, dst_spec, rc) result(action)
      class(ExtensionAction), allocatable :: action
      class(FieldSpec), intent(in) :: this
      class(StateItemSpec), intent(in) :: dst_spec
      integer, optional, intent(out) :: rc
      integer :: status
      action = NullAction() ! default
      select type (dst_spec)
      type is (FieldSpec)
         if (.not. MAPL_SameGeom(this%geom, dst_spec%geom)) then
            deallocate(action)
            action = RegridAction(this%geom, this%payload, dst_spec%geom, dst_spec%payload)
            _RETURN(_SUCCESS)
         end if
         if (this%typekind /= dst_spec%typekind) then
            deallocate(action)
            action = CopyAction(this%payload, dst_spec%payload)
            _RETURN(_SUCCESS)
         end if
         if (.not. match(this%units,dst_spec%units)) then
            deallocate(action)
            action = ConvertUnitsAction(this%payload, this%units, dst_spec%payload, dst_spec%units)
            _RETURN(_SUCCESS)
         end if
      class default
         _FAIL('Dst spec is incompatible with FieldSpec.')
      end select
      _RETURN(_SUCCESS)
   end function make_action
Call graph
make_action calls mapl_assert, mapl_samegeom, match, regridaction, mapl_return, make_action
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_samegeom calls same_geom
match calls match_geom, match_string, match_typekind
regridaction calls new_scalarregridaction
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
match_geom calls mapl_samegeom
match_string calls mirror
new_scalarregridaction calls esmfregridderparam, get_regridder, get_regridder_manager
same_geom calls mapl_geomgetid
get_regridder calls mapl_return, find, of, add_regridder, make_regridder, mapl_verify, vector_back, vector_begin
mapl_geomgetid calls mapl_return, ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_verify