make_coupler – MAPL
make_coupler Function
24 statements
Source File
public function make_coupler(transform, source, rc) result(coupler_gridcomp)
Arguments
Type Intent Optional Attributes Name
class(ExtensionTransform), intent(in) :: transform
class(ComponentDriver), intent(in), optional, target :: source
integer, intent(out), optional :: rc
Return Value type(ESMF_GridComp)
Calls
Called by
Source Code
   function make_coupler(transform, source, rc) result(coupler_gridcomp)
      type(ESMF_GridComp) :: coupler_gridcomp
      class(ExtensionTransform), intent(in) :: transform
      class(ComponentDriver), target, optional, intent(in) :: source
      integer, optional, intent(out) :: rc
      integer :: status
      type(CouplerMetaComponent), pointer :: coupler_meta
      type(TransformId) :: id
      character(:), allocatable :: name
      id = transform%get_transformId()
      name = 'coupler['//id%to_string()//']'
      coupler_gridcomp = ESMF_GridCompCreate(name=name, contextFlag=ESMF_CONTEXT_PARENT_VM, _RC)
      call attach_coupler_meta(coupler_gridcomp, _RC)
      coupler_meta => get_coupler_meta(coupler_gridcomp, _RC)
#ifndef __GFORTRAN__
      coupler_meta = CouplerMetaComponent(transform, source)
#else
      call ridiculous(coupler_meta, CouplerMetaComponent(transform,source))
#endif
      call ESMF_GridCompSetServices(coupler_gridComp, setServices, _RC)
      _RETURN(_SUCCESS)
   contains
#ifdef __GFORTRAN__
      subroutine ridiculous(a, b)
         type(CouplerMetaComponent), intent(out) :: a
         type(CouplerMetaComponent), intent(in) :: b
         a = b
      end subroutine ridiculous
#endif
   end function make_coupler
Call graph
make_coupler calls ESMF_GridCompCreate, esmf_gridcompsetservices, get_transformId, to_string, attach_coupler_meta, get_coupler_meta, mapl_return, mapl_verify
attach_coupler_meta calls mapl_return, mapl_assert, mapl_usercompsetinternalstate
get_coupler_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_propagate_geom calls make_coupler
test_propagate_interp_weights calls make_coupler
test_propagate_shared_attrs calls make_coupler
test_get_coordinate_field_change_units_center calls get_coordinate_field
test_get_coordinate_field_change_units_edge calls get_coordinate_field
test_get_coordinate_field_simple calls get_coordinate_field