make_gridded_dims – MAPL
make_gridded_dims Module Function
16 statements
Source File
module function make_gridded_dims(this, geom_spec, rc) result(gridded_dims) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
class(GeomSpec), intent(in) :: geom_spec
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Called by
Source Code
   module function make_gridded_dims(this, geom_spec, rc) result(gridded_dims)
      type(StringVector) :: gridded_dims
      class(LatLonGeomFactory), intent(in) :: this
      class(GeomSpec), intent(in) :: geom_spec
      integer, optional, intent(out) :: rc
      gridded_dims = StringVector()
      select type (geom_spec)
      type is (LatLonGeomSpec)
         call gridded_dims%push_back('lon')
         call gridded_dims%push_back('lat')
      class default
         _FAIL('geom_spec is not of dynamic type LatLonGeomSpec.')
      end select
      _RETURN(_SUCCESS)
   end function make_gridded_dims
Call graph
make_gridded_dims calls mapl_assert, mapl_return, push_back, stringvector, make_gridded_dims
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize