make_grid_from_config – MAPL
make_grid_from_config Function
35 statements
Source File
private function make_grid_from_config(this, config, unusable, prefix, rc) result(grid)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
type(ESMF_Config), intent(inout) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: prefix
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Source Code
   function make_grid_from_config(this, config, unusable, prefix, rc) result(grid)
      use ESMF
      type (ESMF_Grid) :: grid
      class (GridManager), intent(inout) :: this
      type (ESMF_Config), intent(inout) :: config
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: prefix
      integer, optional,  intent(out) :: rc
      class (AbstractGridFactory), allocatable :: factory
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_grid_from_config'
      character(len=ESMF_MAXSTR) :: grid_type
      type(ESMF_Info) :: infoh
      character(len=:), allocatable :: label
      _UNUSED_DUMMY(unusable)
      label = 'GRID_TYPE:'
      if (present(prefix)) then
         label = trim(prefix) // label
      end if
      call ESMF_ConfigGetAttribute(config, label=label, value=grid_type, rc=status)
      _ASSERT(status==0,'label ['//label//'] not found')
      allocate(factory, source=this%make_factory(trim(grid_type), config, prefix=prefix, rc=status))
      _VERIFY(status)
      ! Making ESMF grids is expensive.  Add the factory to the cache (if new)
      ! and use the cached factory to create the grid.   Each factory
      ! only creates the grid once.
      grid = this%make_grid(factory, rc=status)
      _VERIFY(status)
      ! TLC: Using 'GridType' instead of 'GRID_TYPE' for legacy reasons.
      call ESMF_InfoGetFromHost(grid,infoh,rc=status)
      _VERIFY(status)
      call ESMF_InfoSet(infoh,'GridType',grid_type,rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function make_grid_from_config
Call graph
make_grid_from_config calls ESMF_ConfigGetAttribute, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_assert, make_factory, make_grid, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_factory_from_distgrid calls mapl_return, mapl_verify, initialize, make_clone
make_grid_from_distgrid calls ESMF_InfoGetFromHost, ESMF_InfoSet, make_factory, make_grid, mapl_return, mapl_verify
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_clone calls mapl_assert, mapl_return, mapl_verify, clone, initialize_prototypes, m_at