make_info – MAPL
make_info Function
27 statements
Source File
private function make_info(this, rc) result(info)
Type Bound
UngriddedDimsSpec
Arguments
Type Intent Optional Attributes Name
class(UngriddedDimsSpec), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value type(ESMF_Info)
Calls
Called by
Source Code
   function make_info(this, rc)  result(info)
      type(ESMF_Info) :: info
      class(UngriddedDimsSpec), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      type(UngriddedDimSpec), pointer :: dim_spec
      type(ESMF_Info) :: dim_info
      character(5) :: dim_key
      info = ESMF_InfoCreate(_RC)
      call ESMF_InfoSet(info, key='num_ungridded_dimensions', value=this%get_num_ungridded(), _RC)
      do i = 1, this%get_num_ungridded()
         dim_spec => this%get_ith_dim_spec(i, _RC)
         dim_info = dim_spec%make_info(_RC)
         write(dim_key, '("dim_", i0)') i
         call ESMF_InfoSet(info, key=dim_key, value=dim_info, _RC)
         call ESMF_InfoDestroy(dim_info, _RC)
      end do
      _RETURN(_SUCCESS)
   end function make_info
Call graph
make_info calls ESMF_InfoCreate, ESMF_InfoDestroy, ESMF_InfoSet, get_ith_dim_spec, get_num_ungridded, make_info, mapl_return, mapl_verify
get_ith_dim_spec calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
set_info calls make_info
allocate calls set_info
test_field_set_info calls set_info