make_geom_spec_from_hconfig – MAPL
make_geom_spec_from_hconfig Module Function
21 statements
Source File
module function make_geom_spec_from_hconfig(this, hconfig, rc) result(geom_spec)
Arguments
Type Intent Optional Attributes Name
class(GeomManager), intent(inout), target :: this
type(ESMF_HConfig), intent(inout) :: hconfig
integer, intent(out), optional :: rc
Return Value class(GeomSpec), allocatable
Calls
Source Code
   module function make_geom_spec_from_hconfig(this, hconfig, rc) result(geom_spec)
      class(GeomSpec), allocatable :: geom_spec
      class(GeomManager), target, intent(inout) :: this
      type(ESMF_HConfig), intent(inout) :: hconfig
      integer, optional, intent(out) :: rc
      class(GeomFactory), pointer :: factory
      integer :: status
      geom_spec = NullGeomSpec()
      factory => find_factory(this%factories, supports_hconfig, _RC)
      deallocate(geom_spec)
      geom_spec = factory%make_spec(hconfig, _RC)
      _RETURN(_SUCCESS)
   contains
      logical function supports_hconfig(factory)
         class(GeomFactory), intent(in) :: factory
         supports_hconfig = factory%supports(hconfig)
      end function supports_hconfig
   end function make_geom_spec_from_hconfig
Call graph
make_geom_spec_from_hconfig calls mapl_return, mapl_verify, make_spec, find_factory
find_factory calls mapl_return, find_if, mapl_assert, of, vector_begin
make_geom_spec_from_metadata calls make_geom_spec_from_metadata, make_latlongeomspec, mapl_return, mapl_verify