map_find_if_not – MAPL
map_find_if_not Function
18 statements
Source File
private function map_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtStateItemSpecMapIterator), intent(in) :: first
type(ActualPtStateItemSpecMapIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(ActualPtStateItemSpecPair), intent(in) :: item
Return Value logical
Return Value type(ActualPtStateItemSpecMapIterator)
Calls
Called by
Call graph
map_find_if_not calls map_iter_next, map_iter_of
map_iter_next calls map_s_iter_next
map_iter_of calls map_s_iter_of
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
find_if_not calls map_find_if_not