map_iter_of – MAPL
map_iter_of Function
5 statements
Source File
private function map_iter_of(this) result(p)
Type Bound
ActualPtVec_MapIterator
Arguments
Type Intent Optional Attributes Name
class(ActualPtVec_MapIterator), intent(in), target :: this
Return Value type(ActualPtVec_Pair), pointer
Calls
Called by
Call graph
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
map_find_if_not calls map_iter_of
map_find_if calls map_iter_of
map_iter_first calls map_iter_of
map_iter_second calls map_iter_of
find_if_not calls map_find_if_not
find_if calls map_find_if
filter calls map_iter_first
propagate_exports_virtual_pt calls map_iter_first
propagate_unsatisfied_imports_virtual_pt calls map_iter_first
write_formatted calls map_iter_first
connect calls filter
initialize_advertise calls propagate_exports, propagate_unsatisfied_imports
propagate_exports_all calls propagate_exports
propagate_exports_child calls propagate_exports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_exports, propagate_unsatisfied_imports