map_s_find – MAPL
map_s_find Function
13 statements
Source File
private function map_s_find(this, value) result(find)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
type(IntegerRequestPair), intent(in) :: value
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
map_s_lessthan calls map_key_less_than
map_find calls map_s_find
map_s_count calls map_s_find
map_s_erase_value calls map_s_find, erase
erase_requesthandle calls map_find
get_requesthandle calls map_find
map_at_rc calls map_find
map_erase_key calls map_find
handle_done_stage calls get_requesthandle
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_merge calls erase
put calls get_requesthandle
receive_output_data calls get_requesthandle, receive_output_data
wait calls erase_requesthandle, get_requesthandle