map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
RegistryPtrMap
Arguments
Type Intent Optional Attributes Name
class(RegistryPtrMap), intent(inout) :: this
type(RegistryPtrPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
add_subregistry calls insert
map_new_map_initializer_list calls insert
registryptrmap calls map_new_map_initializer_list
test_connect calls add_subregistry
test_connect_chain calls add_subregistry
test_do_not_propagate_import calls add_subregistry
test_e2e_preserve_actual_pt calls add_subregistry
test_export_to_export_connection calls add_subregistry
test_get_subregistry calls add_subregistry
test_get_subregistry_fail_not_found calls add_subregistry
test_import_from_child calls add_subregistry
test_import_from_parent calls add_subregistry
test_multi_import calls add_subregistry
test_propagate_import calls add_subregistry
test_sibling_activation calls add_subregistry