map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(inout) :: this
type(IntegerRequestPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
insert_requesthandle calls insert
map_new_map_initializer_list calls insert
integerrequestmap calls map_new_map_initializer_list
collective_prefetch_data calls insert_requesthandle, collective_prefetch_data
collective_stage_data calls insert_requesthandle, collective_stage_data
get_datafrommem calls insert_requesthandle, get_datafrommem
handle_collectivestagedata calls insert_requesthandle
handle_done_prefetch calls insert_requesthandle
handle_stagedata calls insert_requesthandle
prefetch_data calls insert_requesthandle, prefetch_data
stage_data calls insert_requesthandle, stage_data
stage_nondistributed_data calls insert_requesthandle, collective_stage_data
run calls collective_prefetch_data, collective_stage_data, stage_nondistributed_data, prefetch_data
test_prefetch_data calls prefetch_data
test_wait calls prefetch_data