map_s_verify – MAPL
map_s_verify Function
45 statements
Source File
private recursive function map_s_verify(this) result(verify)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
Return Value logical
Calls
Call graph
map_s_verify calls map_s_begin, map_s_get_child, map_s_has_child, map_s_iter_next
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node