map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
ActualPtVec_Map
Arguments
Type Intent Optional Attributes Name
class(ActualPtVec_Map), intent(inout) :: this
type(ActualPtVec_Pair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
add_extension_pt calls insert
map_new_map_initializer_list calls insert
actualptvec_map calls map_new_map_initializer_list
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual