map_s_iter_next_n_default – MAPL
map_s_iter_next_n_default Function
11 statements
Source File
private function map_s_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_iter_next_n_default calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
next calls map_s_iter_next_n_default