map_of – MAPL
map_of Function
18 statements
Source File
private function map_of(this, key) result(res)
Type Bound
ActualPtStateItemSpecMap
Arguments
Type Intent Optional Attributes Name
class(ActualPtStateItemSpecMap), intent(inout), target :: this
type(ActualConnectionPt), intent(in) :: key
Return Value class(StateItemSpec), pointer
Calls
Called by
Call graph
map_of calls insert, map_s_iter_of
map_s_iter_of calls map_s_get_value
map_s_insert_initializer_list calls insert
connect_to calls map_of