map_s_find – MAPL
map_s_find Function
13 statements
Source File
private function map_s_find(this, value) result(find)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
type(Pair), intent(in) :: value
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
map_s_lessthan calls map_key_less_than
map_find calls map_s_find
map_s_count calls map_s_find
map_s_erase_value calls map_s_find, erase
map_at_rc calls map_find
map_erase_key calls map_find
remove_variable calls map_find
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_merge calls erase
def_variables calls at
equal calls at
get_coordinate_variable calls at
get_variable calls at
is_coordinate_variable calls at
set_order calls at