map_s_ftn_end – MAPL
map_s_ftn_end Function
7 statements
Source File
private function map_s_ftn_end(this) result(end_)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_ftn_end calls next, map_s_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_begin calls map_s_iter_next
map_iter_next_1 calls next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
map_s_iter_next calls map_s_advpos
map_iter_next calls map_s_iter_next
map_s_advpos calls map_s_get_child, to_node
map_ftn_end calls map_s_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end
ftn_end calls map_s_iter_ftn_end
check_flip calls map_ftn_end
equal calls map_ftn_end
get_dim_name calls map_ftn_end
get_level_name calls map_ftn_end
map_iter_ftn_end calls map_ftn_end
mapl_create_bundle_from_metdata_id calls map_ftn_end
mapl_iochangeres calls map_ftn_end
mapl_iocountlevels calls map_ftn_end
mapl_iocountnondimvars calls map_ftn_end
mapl_iogetnondimvars calls map_ftn_end
merge calls map_ftn_end
modifymetadata calls map_ftn_end
stringvariablemap_serialize calls map_ftn_end
transfer_metadata calls map_ftn_end
write_const_variables calls map_ftn_end
write_coordinate_variables calls map_ftn_end
write_data calls map_ftn_end
write_variables calls map_ftn_end