map_s_advpos – MAPL
map_s_advpos Subroutine
27 statements
Source File
private recursive subroutine map_s_advpos(this, pos, dir)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
type(map_s_Node), intent(inout), pointer :: pos
integer, intent(in) :: dir
Calls
Called by
Call graph
map_s_advpos calls map_s_get_child, to_node
map_s_erase_nonleaf calls map_s_advpos
map_s_iter_next calls map_s_advpos
map_s_iter_prev calls map_s_advpos
map_iter_next calls map_s_iter_next
map_iter_prev calls map_s_iter_prev
map_s_begin calls map_s_iter_next
map_s_deep_copy calls map_s_iter_next
map_s_equal calls map_s_iter_next
map_s_erase_iter calls map_s_iter_next
map_s_erase_range calls map_s_erase_nonleaf, map_s_iter_next
map_s_find_if_not calls map_s_iter_next
map_s_find_if calls map_s_iter_next
map_s_insert_range calls map_s_iter_next
map_s_iter_advance_default calls map_s_iter_next
map_s_iter_advance_size_kind calls map_s_iter_next
map_s_iter_next_n_default calls map_s_iter_next
map_s_iter_next_n_size_kind calls map_s_iter_next
map_s_iter_prev_n_default calls map_s_iter_prev
map_s_iter_prev_n_size_kind calls map_s_iter_prev
map_s_less_than calls map_s_iter_next
map_s_lower_bound calls map_s_iter_next
map_s_merge calls map_s_iter_next
map_s_upper_bound calls map_s_iter_next
map_s_verify calls map_s_iter_next