map_s_insert_initializer_list – MAPL
map_s_insert_initializer_list Subroutine
8 statements
Source File
private recursive subroutine map_s_insert_initializer_list(this, values)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout) :: this
type(MethodPhasesPair), intent(in) :: values(:)
Calls
Called by
Call graph
map_s_insert_initializer_list calls insert
map_insert_key_value calls insert
map_insert_pair calls insert
map_of calls insert
map_s_copy_list calls insert
map_s_deep_copy calls insert
map_s_insert_range calls insert
map_s_insert_single_with_hint calls insert
map_s_merge calls insert
map_s_new_set_initializer_list calls insert
map_set_ calls insert
map_set calls map_s_new_set_initializer_list
add_phase_ calls map_of, insert
get_phases calls map_of
map_deep_copy calls map_s_deep_copy
set_entry_point calls map_of
add_phase calls add_phase_
gridcomp_set_entry_point calls set_entry_point
initialize_phases_map calls insert
map_new_map_initializer_list calls insert
run_child_by_name calls get_phases
run_custom calls get_phases
run calls get_phases
setservices calls get_phases