map_at_rc – MAPL
map_at_rc Function
16 statements
Source File
private function map_at_rc(this, key, rc) result(res)
Type Bound
ActualPtComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(ActualPtComponentDriverMap), intent(in), target :: this
type(ActualConnectionPt), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(GriddedComponentDriver), pointer
Calls
Called by
Call graph
map_at_rc calls map_find
map_find calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
get_export_coupler calls at
get_import_coupler calls at
connect_sibling calls get_export_coupler
connect calls connect_sibling