map_s_ftn_begin – MAPL
map_s_ftn_begin Function
6 statements
Source File
private function map_s_ftn_begin(this) result(begin)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
Return Value type(map_SetIterator)
Called by
Call graph
map_ftn_begin calls map_s_ftn_begin
map_s_iter_ftn_begin calls map_s_ftn_begin
ftn_begin calls map_s_iter_ftn_begin, map_iter_ftn_begin
filter calls map_ftn_begin
map_iter_ftn_begin calls map_ftn_begin
connect calls filter