map_iter_next_n_size_kind – MAPL
map_iter_next_n_size_kind Function
11 statements
Source File
private function map_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtVec_MapIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(ActualPtVec_MapIterator)
Calls
Called by
Call graph
map_iter_next_n_size_kind calls map_iter_next
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
next calls map_iter_next_n_size_kind, map_iter_next_1, map_s_iter_next_1
map_iter_next_1 calls next
map_s_ftn_end calls next
map_s_iter_next_1 calls next
map_ftn_end calls map_s_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end
ftn_end calls map_s_iter_ftn_end
filter calls map_ftn_end
map_iter_ftn_end calls map_ftn_end