map_of – MAPL
map_of Function
18 statements
Source File
private function map_of(this, key) result(res)
Type Bound
MethodPhasesMap
Arguments
Type Intent Optional Attributes Name
class(MethodPhasesMap), intent(inout), target :: this
type(ESMF_Method_Flag), intent(in) :: key
Return Value type(StringVector), pointer
Calls
Called by
Call graph
map_of calls insert, map_s_iter_of
map_s_iter_of calls map_s_get_value
map_s_insert_initializer_list calls insert
add_phase_ calls map_of
get_phases calls map_of
set_entry_point calls map_of, add_phase
add_phase calls add_phase_
gridcomp_set_entry_point calls set_entry_point
run_child_by_name calls get_phases, run_child
run_custom calls get_phases
run calls get_phases, run
setservices calls get_phases, mapl_gridcompsetentrypoint
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
finalize calls run_custom, finalize
initialize_advertise calls run_custom
initialize_geom calls run_custom
initialize_post_advertise calls run_custom
initialize_realize calls run_custom
initialize_user calls run_custom
initialize calls initialize_advertise, initialize_geom, initialize_post_advertise, initialize_realize, initialize_user
run_children_ calls run_child
test_finalize_children calls finalize
test_init_children calls initialize_user