map_s_begin – MAPL
map_s_begin Function
7 statements
Source File
private function map_s_begin(this) result(begin)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
map_begin calls map_s_begin
map_s_deep_copy calls map_s_begin
map_s_equal calls map_s_begin
map_s_ftn_end calls map_s_begin
map_s_iter_begin calls map_s_begin
map_s_less_than calls map_s_begin
map_s_merge calls map_s_begin
map_s_verify calls map_s_begin
begin calls map_s_iter_begin, map_iter_begin
operator(==) calls map_s_equal
operator(lt) calls map_s_less_than
get_range calls map_begin
map_deep_copy calls map_s_deep_copy
map_ftn_end calls map_s_ftn_end
map_iter_begin calls map_begin
map_s_iter_ftn_end calls map_s_ftn_end
propagate_exports_child calls map_begin
propagate_unsatisfied_imports_child calls map_begin
write_formatted calls map_begin
ftn_end calls map_s_iter_ftn_end, map_iter_ftn_end
filter calls map_ftn_end
map_iter_ftn_end calls map_ftn_end
connect calls filter