map_ftn_end – MAPL
map_ftn_end Function
6 statements
Source File
private function map_ftn_end(this) result(iter)
Type Bound
ChildSpecMap
Arguments
Type Intent Optional Attributes Name
class(ChildSpecMap), intent(in), target :: this
Return Value type(ChildSpecMapIterator)
Calls
Called by
Call graph
map_ftn_end calls map_s_ftn_end
map_s_ftn_end calls next, map_s_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_begin calls map_s_iter_next
map_iter_next_1 calls next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
map_s_iter_next calls map_s_advpos
map_iter_ftn_end calls map_ftn_end
setservices_ calls map_ftn_end, setservices_
ftn_end calls map_iter_ftn_end
create_grid_comp_primary calls setservices_
create_grid_comp calls create_grid_comp_primary