map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
MethodPhasesMap
Arguments
Type Intent Optional Attributes Name
class(MethodPhasesMap), intent(inout) :: this
type(MethodPhasesPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
add_phase_ calls insert
initialize_phases_map calls insert
map_new_map_initializer_list calls insert
add_phase calls add_phase_
methodphasesmap calls map_new_map_initializer_list
new_outer_meta calls initialize_phases_map
outermetacomponent calls new_outer_meta
set_entry_point calls add_phase