map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
ActualPtSpecPtrMap
Arguments
Type Intent Optional Attributes Name
class(ActualPtSpecPtrMap), intent(inout) :: this
type(ActualPtSpecPtrPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
link_item_spec_actual calls insert
map_new_map_initializer_list calls insert
actualptspecptrmap calls map_new_map_initializer_list
add_item_spec_actual calls link_item_spec_actual
connect_export_to_export calls link_item_spec
link_item_spec_virtual calls link_item_spec