map_s_begin – MAPL
map_s_begin Function
7 statements
Source File
private function map_s_begin(this) result(begin)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
map_begin calls map_s_begin
map_s_deep_copy calls map_s_begin
map_s_equal calls map_s_begin
map_s_ftn_end calls map_s_begin
map_s_iter_begin calls map_s_begin
map_s_less_than calls map_s_begin
map_s_merge calls map_s_begin
map_s_verify calls map_s_begin
begin calls map_s_iter_begin, map_iter_begin
operator(==) calls map_s_equal
operator(lt) calls map_s_less_than
clear_requesthandle calls map_begin, clear_requesthandle
map_deep_copy calls map_s_deep_copy
map_ftn_end calls map_s_ftn_end
map_iter_begin calls map_begin
map_s_iter_ftn_end calls map_s_ftn_end
ftn_end calls map_s_iter_ftn_end, map_iter_ftn_end
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
map_iter_ftn_end calls map_ftn_end
wait_all calls clear_requesthandle
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls wait_all
terminate calls wait_all
wait calls wait_all