map_iter_advance_default – MAPL
map_iter_advance_default Subroutine
9 statements
Source File
private subroutine map_iter_advance_default(it, n)
Arguments
Type Intent Optional Attributes Name
type(ActualPtSpecPtrMapIterator), intent(inout) :: it
integer, intent(in) :: n
Calls
Called by
Call graph
map_iter_advance_default calls map_iter_next
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
advance calls map_iter_advance_default