map_at_rc – MAPL
map_at_rc Function
16 statements
Source File
private function map_at_rc(this, key, rc) result(res)
Type Bound
RegistryPtrMap
Arguments
Type Intent Optional Attributes Name
class(RegistryPtrMap), intent(in), target :: this
character(len=*), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(RegistryPtr), pointer
Calls
Called by
Call graph
map_at_rc calls map_find
map_find calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
get_subregistry_comp calls at
connect calls get_subregistry
get_subregistry_conn calls get_subregistry
propagate_exports_all calls get_subregistry
propagate_unsatisfied_imports_all calls get_subregistry
test_get_subregistry calls get_subregistry
test_get_subregistry_fail_not_found calls get_subregistry