map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
StateItemSpecMap
Arguments
Type Intent Optional Attributes Name
class(StateItemSpecMap), intent(inout) :: this
type(StateItemSpecPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
add_item calls insert
map_new_map_initializer_list calls insert
stateitemspecmap calls map_new_map_initializer_list
test_add_one_field calls add_item
test_get_item calls add_item