map_ftn_end – MAPL
map_ftn_end Function
6 statements
Source File
private function map_ftn_end(this) result(iter)
Type Bound
ActualPtVec_Map
Arguments
Type Intent Optional Attributes Name
class(ActualPtVec_Map), intent(in), target :: this
Return Value type(ActualPtVec_MapIterator)
Calls
Called by
Call graph
map_ftn_end calls map_s_ftn_end
map_s_ftn_end calls next, map_s_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_begin calls map_s_iter_next
map_iter_next_1 calls next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
map_s_iter_next calls map_s_advpos
filter calls map_ftn_end
map_iter_ftn_end calls map_ftn_end
ftn_end calls map_iter_ftn_end
connect calls filter