map_iter_first – MAPL
map_iter_first Function
11 statements
Source File
private function map_iter_first(this) result(first)
Type Bound
ActualPtSpecPtrMapIterator
Arguments
Type Intent Optional Attributes Name
class(ActualPtSpecPtrMapIterator), intent(in), target :: this
Return Value type(ActualConnectionPt), pointer
Calls
Called by
Call graph
map_iter_first calls map_iter_of
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
add_to_states calls map_iter_first
report calls map_iter_first
initialize_post_advertise calls add_to_states
initialize calls initialize_post_advertise