map_s_insert_initializer_list – MAPL
map_s_insert_initializer_list Subroutine
8 statements
Source File
private recursive subroutine map_s_insert_initializer_list(this, values)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout) :: this
type(ActualPtVec_Pair), intent(in) :: values(:)
Calls
Called by
Call graph
map_s_insert_initializer_list calls insert
map_insert_key_value calls insert
map_insert_pair calls insert
map_of calls insert
map_s_copy_list calls insert
map_s_deep_copy calls insert
map_s_insert_range calls insert
map_s_insert_single_with_hint calls insert
map_s_merge calls insert
map_s_new_set_initializer_list calls insert
map_set_ calls insert
map_set calls map_s_new_set_initializer_list
add_extension_pt calls map_of, insert
map_deep_copy calls map_s_deep_copy
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt
map_new_map_initializer_list calls insert