map_s_ftn_begin – MAPL
map_s_ftn_begin Function
6 statements
Source File
private function map_s_ftn_begin(this) result(begin)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
Return Value type(map_SetIterator)
Called by
Call graph
map_ftn_begin calls map_s_ftn_begin
map_s_iter_ftn_begin calls map_s_ftn_begin
ftn_begin calls map_s_iter_ftn_begin
check_flip calls map_ftn_begin
equal calls map_ftn_begin
get_dim_name calls map_ftn_begin
get_level_name calls map_ftn_begin
map_iter_ftn_begin calls map_ftn_begin
mapl_create_bundle_from_metdata_id calls map_ftn_begin
mapl_iochangeres calls map_ftn_begin
mapl_iocountlevels calls map_ftn_begin
mapl_iocountnondimvars calls map_ftn_begin
mapl_iogetnondimvars calls map_ftn_begin
merge calls map_ftn_begin
modifymetadata calls map_ftn_begin
stringvariablemap_serialize calls map_ftn_begin
transfer_metadata calls map_ftn_begin
write_const_variables calls map_ftn_begin
write_coordinate_variables calls map_ftn_begin
write_data calls map_ftn_begin
write_variables calls map_ftn_begin