map_begin – MAPL
map_begin Function
6 statements
Source File
private function map_begin(this) result(iter)
Type Bound
ActualPtVec_Map
Arguments
Type Intent Optional Attributes Name
class(ActualPtVec_Map), intent(in), target :: this
Return Value type(ActualPtVec_MapIterator)
Calls
Called by
Call graph
map_begin calls map_s_begin
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
get_range calls map_begin
map_iter_begin calls map_begin
propagate_exports_child calls map_begin
propagate_unsatisfied_imports_child calls map_begin
write_formatted calls map_begin
begin calls map_iter_begin