map_deep_copy – MAPL
map_deep_copy Subroutine
8 statements
Source File
private recursive subroutine map_deep_copy(this, x)
Type Bound
VirtualPtStateItemPtrMap
Arguments
Type Intent Optional Attributes Name
class(VirtualPtStateItemPtrMap), intent(out) :: this
type(VirtualPtStateItemPtrMap), intent(in), target :: x
Calls
Call graph
map_deep_copy calls map_s_deep_copy
map_s_deep_copy calls insert, map_s_begin, map_s_iter_next, map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
map_s_insert_initializer_list calls insert