map_of – MAPL
map_of Function
18 statements
Source File
private function map_of(this, key) result(res)
Type Bound
ActualPtVec_Map
Arguments
Type Intent Optional Attributes Name
class(ActualPtVec_Map), intent(inout), target :: this
type(VirtualConnectionPt), intent(in) :: key
Return Value type(ActualPtVector), pointer
Calls
Called by
Call graph
map_of calls insert, map_s_iter_of
map_s_iter_of calls map_s_get_value
map_s_insert_initializer_list calls insert
add_extension_pt calls map_of
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt, link_item_spec
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual
connect_export_to_export calls link_item_spec