map_iter_of – MAPL
map_iter_of Function
5 statements
Source File
private function map_iter_of(this) result(p)
Type Bound
StringVariableMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringVariableMapIterator), intent(in), target :: this
Return Value type(Pair), pointer
Calls
Called by
Call graph
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
map_find_if_not calls map_iter_of
map_find_if calls map_iter_of
map_iter_first calls map_iter_of
map_iter_second calls map_iter_of
find_if_not calls map_find_if_not
find_if calls map_find_if
check_flip calls map_iter_first
equal calls map_iter_first
get_level_name calls map_iter_first
mapl_create_bundle_from_metdata_id calls map_iter_first
mapl_iochangeres calls map_iter_first
mapl_iocountlevels calls map_iter_first
mapl_iocountnondimvars calls map_iter_first
mapl_iogetnondimvars calls map_iter_first
merge calls map_iter_first
modifymetadata calls map_iter_first
stringvariablemap_serialize calls map_iter_first
transfer_metadata calls map_iter_first
write_const_variables calls map_iter_first
write_coordinate_variables calls map_iter_first
write_data calls map_iter_first
write_variables calls map_iter_first