map_find – MAPL
map_find Function
9 statements
Source File
private function map_find(this, key) result(iter)
Type Bound
StringVariableMap
Arguments
Type Intent Optional Attributes Name
class(StringVariableMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(StringVariableMapIterator)
Calls
Called by
Call graph
map_find calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
map_s_lessthan calls map_key_less_than
map_at_rc calls map_find
map_erase_key calls map_find
remove_variable calls map_find
def_variables calls at
equal calls at
get_coordinate_variable calls at, get_coordinate_variable
get_variable calls at, get_variable
is_coordinate_variable calls at
set_order calls at
add_var_attribute_0d calls get_variable
add_var_attribute_1d calls get_variable
add_variable calls def_variables
alphabatize_variables calls set_order
check_flip calls get_coordinate_variable
compute_time_for_current calls get_variable
createfilemetadata calls get_variable
get_coordinates_dim calls get_coordinate_variable
get_file_start_time calls get_variable
get_start_time calls get_variable
initialize_from_file_metadata calls get_coordinate_variable
mapl_iochangeres calls get_coordinate_variable
mapl_iogettime calls get_variable
test_serialize calls set_order
transfer_metadata calls get_variable
write calls def_variables
write_coordinate_variables calls get_coordinate_variable
write_data calls get_variable