map_iter_first – MAPL
map_iter_first Function
11 statements
Source File
private function map_iter_first(this) result(first)
Type Bound
StringVariableMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringVariableMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Calls
Called by
Call graph
map_iter_first calls map_iter_of
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
check_flip calls map_iter_first
equal calls map_iter_first
get_level_name calls map_iter_first
mapl_create_bundle_from_metdata_id calls map_iter_first, get_level_name
mapl_iochangeres calls map_iter_first
mapl_iocountlevels calls map_iter_first
mapl_iocountnondimvars calls map_iter_first
mapl_iogetnondimvars calls map_iter_first
merge calls map_iter_first
modifymetadata calls map_iter_first
stringvariablemap_serialize calls map_iter_first
transfer_metadata calls map_iter_first
write_const_variables calls map_iter_first
write_coordinate_variables calls map_iter_first
write_data calls map_iter_first
write_variables calls map_iter_first
create_grid calls get_level_name
get_file_levels calls get_level_name
getlevs calls get_level_name
handle_modifymetadata calls modifymetadata
mapl_bundlereadncpar calls check_flip
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
serialize calls stringvariablemap_serialize
stringvariablemap_get_length calls stringvariablemap_serialize
write calls write_const_variables, write_coordinate_variables
write_formatted calls write_variables
main calls transfer_metadata, write_data
time_ave calls get_level_name