map_begin – MAPL
map_begin Function
6 statements
Source File
private function map_begin(this) result(iter)
Type Bound
RegistryPtrMap
Arguments
Type Intent Optional Attributes Name
class(RegistryPtrMap), intent(in), target :: this
Return Value type(RegistryPtrMapIterator)
Calls
Called by
Call graph
map_begin calls map_s_begin
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
map_iter_begin calls map_begin
propagate_exports_all calls map_begin
propagate_unsatisfied_imports_all calls map_begin
begin calls map_iter_begin