map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
ChildSpecMap
Arguments
Type Intent Optional Attributes Name
class(ChildSpecMap), intent(inout) :: this
type(ChildSpecPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
map_new_map_initializer_list calls insert
parse_children calls insert
test_parse_childspecmap_1 calls insert, parse_children
test_parse_childspecmap_2 calls insert, parse_children
childspecmap calls map_new_map_initializer_list
parse_component_spec calls parse_children
test_parse_childspecmap_empty calls parse_children
setservices_ calls parse_component_spec