map_iter_next_n_default – MAPL
map_iter_next_n_default Function
11 statements
Source File
private function map_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(StringVariableMapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(StringVariableMapIterator)
Calls
Called by
Call graph
map_iter_next_n_default calls map_iter_next
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
next calls map_iter_next_n_default, map_iter_next_1, map_s_iter_next_1
map_iter_next_1 calls next
map_s_ftn_end calls next
map_s_iter_next_1 calls next
map_ftn_end calls map_s_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end
ftn_end calls map_s_iter_ftn_end
check_flip calls map_ftn_end
equal calls map_ftn_end
get_dim_name calls map_ftn_end
get_level_name calls map_ftn_end
map_iter_ftn_end calls map_ftn_end
mapl_create_bundle_from_metdata_id calls map_ftn_end
mapl_iochangeres calls map_ftn_end
mapl_iocountlevels calls map_ftn_end
mapl_iocountnondimvars calls map_ftn_end
mapl_iogetnondimvars calls map_ftn_end
merge calls map_ftn_end
modifymetadata calls map_ftn_end
stringvariablemap_serialize calls map_ftn_end
transfer_metadata calls map_ftn_end
write_const_variables calls map_ftn_end
write_coordinate_variables calls map_ftn_end
write_data calls map_ftn_end
write_variables calls map_ftn_end