map_erase_key – MAPL
map_erase_key Function
13 statements
Source File
private function map_erase_key(this, k) result(n)
Type Bound
ActualPtComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(ActualPtComponentDriverMap), intent(inout) :: this
type(ActualConnectionPt), intent(in) :: k
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Call graph
map_erase_key calls erase, map_find
map_find calls map_s_find
map_erase_range calls erase
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan