map_set_ – MAPL
map_set_ Subroutine
10 statements
Source File
private subroutine map_set_(this, key, value)
Type Bound
StringVariableMap
Arguments
Type Intent Optional Attributes Name
class(StringVariableMap), intent(inout) :: this
character(len=*), intent(in) :: key
class(Variable), intent(in) :: value
Calls
Called by
Call graph
map_set_ calls insert
map_s_insert_initializer_list calls insert
modify_variable calls map_set_
create_file_handle calls modify_variable
modifymetadata calls modify_variable
modifytime calls modify_variable
test_equal_diff_variables calls modify_variable
handle_modifymetadata calls modifymetadata
run calls modifytime
start_new_file calls modifytime
main calls start_new_file
time_ave calls start_new_file