map_erase_range – MAPL
map_erase_range Function
8 statements
Source File
private function map_erase_range(this, first, last) result(new_iter)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(inout), target :: this
type(IntegerRequestMapIterator), intent(in) :: first
type(IntegerRequestMapIterator), intent(in) :: last
Return Value type(IntegerRequestMapIterator)
Calls
Called by
Call graph
map_erase_range calls erase
map_s_erase_iter calls erase, map_s_iter_next
map_s_erase_range calls map_s_deallocate_child, map_s_erase_nonleaf, map_s_get_parent, map_s_has_child, map_s_iter_next, map_s_rebalance, map_s_which_child
map_s_erase_value calls erase, map_s_find
map_s_erase_nonleaf calls map_s_rebalance, map_s_advpos, map_s_get_child, map_s_which_side_am_i, set_parent
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_iter_next calls map_s_advpos
map_s_rebalance calls map_s_has_child, get_height, map_s_get_child, map_s_rot, map_s_update_height
map_s_which_child calls map_s_get_child
clear_requesthandle calls erase, clear_requesthandle
erase_requesthandle calls erase
map_erase_key calls erase
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait_all calls clear_requesthandle
wait calls erase_requesthandle, wait_all
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls wait_all
terminate calls wait_all