map_s_erase_value – MAPL
map_s_erase_value Function
13 statements
Source File
private function map_s_erase_value(this, value) result(n)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout), target :: this
type(IntegerRequestPair), intent(in) :: value
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Called by
Call graph
map_s_erase_value calls erase, map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_erase_iter calls erase, map_s_iter_next
map_s_erase_range calls map_s_deallocate_child, map_s_erase_nonleaf, map_s_get_parent, map_s_has_child, map_s_iter_next, map_s_rebalance, map_s_which_child
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
map_s_erase_nonleaf calls map_s_get_child, map_s_rebalance, map_s_advpos, map_s_which_side_am_i, set_parent
map_s_iter_next calls map_s_advpos
map_s_lessthan calls map_key_less_than
map_s_rebalance calls map_s_get_child, map_s_has_child, get_height, map_s_rot, map_s_update_height
map_s_which_child calls map_s_get_child
map_erase_iter calls erase
map_erase_range calls erase
map_s_merge calls erase
clear_requesthandle calls erase
erase_requesthandle calls erase
map_erase_key calls erase