map_s_find_node – MAPL
map_s_find_node Function
23 statements
Source File
private function map_s_find_node(this, value, last) result(find_node)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
type(IntegerRequestPair), intent(in) :: value
logical, intent(in) :: last
Return Value type(map_s_Node), pointer
Calls
Called by
Call graph
map_s_find_node calls map_s_get_child, map_s_get_value, map_s_lessthan, map_s_order_eq, to_node
map_s_lessthan calls map_key_less_than
map_s_order_eq calls map_s_lessthan
map_s_find calls map_s_find_node
map_s_insert_single calls map_s_find_node
map_s_lower_bound calls map_s_find_node
map_s_upper_bound calls map_s_find_node
map_find calls map_s_find
map_s_count calls map_s_find
map_s_erase_value calls map_s_find, erase
erase_requesthandle calls map_find
get_requesthandle calls map_find
map_at_rc calls map_find
map_erase_key calls map_find
handle_done_stage calls get_requesthandle
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_merge calls erase
put calls get_requesthandle
receive_output_data calls get_requesthandle
wait calls erase_requesthandle, get_requesthandle