map_iter_ftn_end – MAPL
map_iter_ftn_end Function
6 statements
Source File
private function map_iter_ftn_end(cont) result(end)
Arguments
Type Intent Optional Attributes Name
type(VirtualPtStateItemPtrMap), intent(in), target :: cont
Return Value type(VirtualPtStateItemPtrMapIterator)
Calls
Called by
Call graph
map_iter_ftn_end calls map_ftn_end
map_ftn_end calls map_s_ftn_end
map_s_ftn_end calls next, map_s_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_begin calls map_s_iter_next
ftn_end calls map_iter_ftn_end