map_s_iter_of – MAPL
map_s_iter_of Function
9 statements
Source File
private function map_s_iter_of(this) result(value)
Type Bound
map_SetIterator
Arguments
Type Intent Optional Attributes Name
class(map_SetIterator), intent(in) :: this
Return Value type(ActualPtVec_Pair), pointer
Calls
Called by
Call graph
map_s_iter_of calls map_s_get_value
map_iter_of calls map_s_iter_of
map_of calls map_s_iter_of
map_s_deep_copy calls map_s_iter_of
map_s_equal calls map_s_iter_of
map_s_find_if_not calls map_s_iter_of
map_s_find_if calls map_s_iter_of
map_s_insert_range calls map_s_iter_of
map_s_less_than calls map_s_iter_of
map_s_merge calls map_s_iter_of
find_if_not calls map_s_find_if_not, map_find_if_not
find_if calls map_s_find_if, map_find_if
operator(==) calls map_s_equal
operator(lt) calls map_s_less_than
add_extension_pt calls map_of
map_deep_copy calls map_s_deep_copy
map_find_if_not calls map_iter_of
map_find_if calls map_iter_of
map_iter_first calls map_iter_of
map_iter_second calls map_iter_of
add_item_spec_virtual_override calls add_extension_pt
filter calls map_iter_first
link_item_spec_virtual calls add_extension_pt
propagate_exports_virtual_pt calls map_iter_first, link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls map_iter_first, link_item_spec_virtual
write_formatted calls map_iter_first
connect calls filter