map_key_less_than – MAPL
map_key_less_than Function
6 statements
Source File
private function map_key_less_than(a, b) result(less_than)
Arguments
Type Intent Optional Attributes Name
type(VirtualPtStateItemSpecPair), intent(in) :: a
type(VirtualPtStateItemSpecPair), intent(in) :: b
Return Value logical
Called by
Call graph
map_s_insert_single calls map_key_less_than, map_s_find_node, map_s_order_eq
map_s_less_than calls map_key_less_than
map_s_lessthan calls map_key_less_than
map_s_lower_bound calls map_key_less_than, map_s_find_node
map_s_upper_bound calls map_key_less_than, map_s_find_node
map_s_value_compare calls map_key_less_than
operator(lt) calls map_s_less_than
map_s_find_node calls map_s_lessthan, map_s_order_eq
map_s_order_eq calls map_s_lessthan
map_s_equal calls map_s_order_eq
map_s_find calls map_s_find_node, map_s_order_eq
operator(==) calls map_s_equal
map_find calls map_s_find
map_s_count calls map_s_find
map_s_erase_value calls map_s_find