map_iter_next_n_default – MAPL
map_iter_next_n_default Function
11 statements
Source File
private function map_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(ActualPtStateItemSpecMapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(ActualPtStateItemSpecMapIterator)
Calls
Called by
Call graph
map_iter_next_n_default calls map_iter_next
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
next calls map_iter_next_n_default, map_iter_next_1, map_s_iter_next_1
map_iter_next_1 calls next
map_s_ftn_end calls next
map_s_iter_next_1 calls next
map_ftn_end calls map_s_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end
ftn_end calls map_s_iter_ftn_end
add_to_state calls map_ftn_end
map_iter_ftn_end calls map_ftn_end