map_s_deallocate_child – MAPL
map_s_deallocate_child Subroutine
11 statements
Source File
private subroutine map_s_deallocate_child(this, side)
Type Bound
map_s_Node
Arguments
Type Intent Optional Attributes Name
class(map_s_Node), intent(inout) :: this
integer, intent(in) :: side
Called by
Call graph
map_s_erase_range calls map_s_deallocate_child
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_erase_value calls erase
map_s_merge calls erase