map_s_lower_bound – MAPL
map_s_lower_bound Function
13 statements
Source File
private function map_s_lower_bound(this, value) result(lb)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
type(RegistryPtrPair), intent(in) :: value
Return Value type(map_SetIterator)
Calls
Call graph
map_s_lower_bound calls map_key_less_than, map_s_find_node, map_s_iter_next
map_s_find_node calls map_s_get_child, map_s_get_value, map_s_lessthan, map_s_order_eq, to_node
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
map_s_lessthan calls map_key_less_than
map_s_order_eq calls map_s_lessthan