map_iter_of – MAPL
map_iter_of Function
5 statements
Source File
private function map_iter_of(this) result(p)
Type Bound
ActualPtSpecPtrMapIterator
Arguments
Type Intent Optional Attributes Name
class(ActualPtSpecPtrMapIterator), intent(in), target :: this
Return Value type(ActualPtSpecPtrPair), pointer
Calls
Called by
Call graph
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
map_find_if_not calls map_iter_of
map_find_if calls map_iter_of
map_iter_first calls map_iter_of
map_iter_second calls map_iter_of
find_if_not calls map_find_if_not
find_if calls map_find_if
add_to_states calls map_iter_first
report calls map_iter_first
initialize_post_advertise calls add_to_states
initialize calls initialize_post_advertise