map_find_if – MAPL
map_find_if Function
18 statements
Source File
private function map_find_if(first, last, p) result(it)
Arguments
Type Intent Optional Attributes Name
type(VirtualPtStateItemSpecMapIterator), intent(in) :: first
type(VirtualPtStateItemSpecMapIterator), intent(in) :: last
private function p(item)
Arguments
Type Intent Optional Attributes Name
type(VirtualPtStateItemSpecPair), intent(in) :: item
Return Value logical
Return Value type(VirtualPtStateItemSpecMapIterator)
Calls
Called by
Call graph
map_find_if calls map_iter_next, map_iter_of
map_iter_next calls map_s_iter_next
map_iter_of calls map_s_iter_of
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
find_if calls map_find_if