map_at_rc – MAPL
map_at_rc Function
16 statements
Source File
private function map_at_rc(this, key, rc) result(res)
Type Bound
FieldDictionaryItemMap
Arguments
Type Intent Optional Attributes Name
class(FieldDictionaryItemMap), intent(in), target :: this
character(len=*), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(FieldDictionaryItem), pointer
Calls
Called by
Call graph
map_at_rc calls map_find
map_find calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
get_item calls at
get_long_name calls at
get_units calls at
test_get_field_item calls get_item
test_get_long_name calls get_long_name
test_get_units calls get_units