map_at_rc – MAPL
map_at_rc Function
16 statements
Source File
private function map_at_rc(this, key, rc) result(res)
Type Bound
ActualPtSpecPtrMap
Arguments
Type Intent Optional Attributes Name
class(ActualPtSpecPtrMap), intent(in), target :: this
type(ActualConnectionPt), intent(in) :: key
integer, intent(out), optional :: rc
Return Value class(StateItemSpecPtr), pointer
Calls
Called by
Call graph
map_at_rc calls map_find
map_find calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
get_item_spec calls at
activate_dependencies calls get_item_spec
check_actual calls get_item_spec
connect_export_to_export calls get_item_spec
get_actual_pt_specptrs calls get_item_spec
init_post_advertise calls get_item_spec
make_servicespec calls get_item_spec
propagate_exports_virtual_pt calls get_item_spec
propagate_unsatisfied_imports_virtual_pt calls get_item_spec
test_create_extension calls get_item_spec
test_get_item_spec_found calls get_item_spec
test_get_item_spec_not_found calls get_item_spec
test_internal_activation calls get_item_spec
test_internal_to_export_connection calls get_item_spec
test_multi_import calls get_item_spec
test_sibling_activation calls get_item_spec
check calls check_actual
check_virtual calls check_actual
connect calls get_actual_pt_specptrs, connect_export_to_export
connect_sibling calls activate_dependencies, get_actual_pt_specptrs
make_itemspec calls make_servicespec