map_at_rc – MAPL
map_at_rc Function
16 statements
Source File
private function map_at_rc(this, key, rc) result(res)
Type Bound
ActualPtVec_Map
Arguments
Type Intent Optional Attributes Name
class(ActualPtVec_Map), intent(in), target :: this
type(VirtualConnectionPt), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(ActualPtVector), pointer
Calls
Called by
Call graph
map_at_rc calls map_find
map_find calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
get_actual_pt_specptrs calls at
get_actual_pts calls at
write_formatted calls at
check_virtual calls get_actual_pts
connect calls get_actual_pt_specptrs, connect_sibling, connect_export_to_export
connect_export_to_export calls get_actual_pts
connect_sibling calls get_actual_pt_specptrs, get_actual_pts, extend_
extend_ calls get_actual_pts
test_connect calls get_actual_pts
test_connect_chain calls get_actual_pts
test_import_from_child calls get_actual_pts
test_import_from_parent calls get_actual_pts
check calls check_virtual