map_s_insert_initializer_list – MAPL
map_s_insert_initializer_list Subroutine
8 statements
Source File
private recursive subroutine map_s_insert_initializer_list(this, values)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout) :: this
type(Pair), intent(in) :: values(:)
Calls
Called by
Call graph
map_s_insert_initializer_list calls insert
map_insert_key_value calls insert
map_insert_pair calls insert
map_of calls insert
map_s_copy_list calls insert
map_s_deep_copy calls insert
map_s_insert_range calls insert
map_s_insert_single_with_hint calls insert
map_s_merge calls insert
map_s_new_set_initializer_list calls insert
map_set_ calls insert
map_set calls map_s_new_set_initializer_list
map_deep_copy calls map_s_deep_copy
modify_variable calls map_set_
add_variable calls insert
create_file_handle calls modify_variable
map_new_map_initializer_list calls insert
mapl_bundlewritencpar calls insert
modifymetadata calls modify_variable
modifytime calls insert, modify_variable
run_model calls insert
run calls insert
stringvariablemap_deserialize calls insert
test_equal_diff_variables calls modify_variable