map_iter_next – MAPL
map_iter_next Subroutine
4 statements
Source File
private recursive subroutine map_iter_next(this)
Type Bound
StringVariableMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringVariableMapIterator), intent(inout) :: this
Calls
Called by
Call graph
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
check_flip calls map_iter_next
equal calls map_iter_next
get_dim_name calls map_iter_next
get_level_name calls map_iter_next
map_find_if_not calls map_iter_next
map_find_if calls map_iter_next
map_iter_advance_default calls map_iter_next
map_iter_advance_size_kind calls map_iter_next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
mapl_create_bundle_from_metdata_id calls map_iter_next
mapl_iochangeres calls map_iter_next
mapl_iocountlevels calls map_iter_next
mapl_iocountnondimvars calls map_iter_next
mapl_iogetnondimvars calls map_iter_next
modifymetadata calls map_iter_next
stringvariablemap_serialize calls map_iter_next
transfer_metadata calls map_iter_next
write_const_variables calls map_iter_next
write_coordinate_variables calls map_iter_next
write_data calls map_iter_next
write_variables calls map_iter_next