MAPL_GridCompSetGeomLocStream – MAPL
MAPL_GridCompSetGeomLocStream Subroutine
13 statements
Source File
private subroutine MAPL_GridCompSetGeomLocStream(gridcomp, locstream, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_LocStream), intent(in) :: locstream
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GridCompSetGeomLocStream(gridcomp, locstream, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(ESMF_LocStream), intent(in) :: locstream
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Geom) :: geom
      geom = ESMF_GeomCreate(locstream, _RC)
      call MAPL_GridCompSetGeom(gridcomp, geom, _RC)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GridCompSetGeomLocStream
Call graph
mapl_gridcompsetgeomlocstream calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeom calls mapl_gridcompsetgeomlocstream, mapl_gridcompsetgeom, mapl_gridcompsetgeomgrid, mapl_gridcompsetgeommesh, mapl_gridcompsetgeomxgrid
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_gridcompsetgeomgrid calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeommesh calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeomxgrid calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_throw_exception calls initialize