MAPL_StateVarWriteNCPar – MAPL
MAPL_StateVarWriteNCPar Subroutine
190 statements
Source File
private subroutine MAPL_StateVarWriteNCPar(filename, STATE, ARRDES, CLOCK, NAME, forceWriteNoRestart, oClients, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(ESMF_State), intent(in) :: STATE
type(ArrDescr), intent(inout) :: ARRDES
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in), optional :: NAME
logical, intent(in), optional :: forceWriteNoRestart
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_StateVarWriteNCPar(filename, STATE, ARRDES, CLOCK, NAME, forceWriteNoRestart, oClients, RC)
    character(len=*)            , intent(IN   ) :: filename
    type (ESMF_State)           , intent(IN   ) :: STATE
    type(ArrDescr)              , intent(INOUT) :: ARRDES
    type(ESMF_Clock)            , intent(IN   ) :: CLOCK
    character(len=*),   optional, intent(IN   ) :: NAME
    logical,            optional, intent(IN   ) :: forceWriteNoRestart
    type (ClientManager), optional, intent(inout) :: oClients
    integer,            optional, intent(  OUT) :: RC
! Local vars
    type (ESMF_FieldBundle)              :: bundle
    type (ESMF_Field)                    :: field
    type (ESMF_Info)                     :: infoh_field, infoh_bundle, infoh_state
    integer                              :: status
    integer                              :: I, J, ITEMCOUNT
    type (ESMF_StateItem_Flag), pointer  :: ITEMTYPES(:)
    character(len=ESMF_MAXSTR ), pointer :: ITEMNAMES(:)
    logical, pointer                     :: DOIT(:)
    logical                              :: skipWriting
    integer                              :: RST, dna
    character(len=ESMF_MAXSTR)           :: FieldName,BundleName,StateName
    logical                              :: forceWriteNoRestart_
    type (ESMF_Field)                  :: new_field, added_field
    type (ESMF_FieldBundle)            :: bundle_write
    integer                            :: nBundle
    logical                            :: isPresent
    character(len=ESMF_MAXSTR)         :: positive
    logical                            :: flip
    logical                            :: is_test_framework, isGridCapture
    integer :: fieldIsValid
    type(ESMF_Array) :: array
    call ESMF_StateGet(STATE,ITEMCOUNT=ITEMCOUNT,RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(ITEMCOUNT>0, 'itemcount must be > 0')
    allocate(ITEMNAMES(ITEMCOUNT),STAT=STATUS)
    _VERIFY(STATUS)
    allocate(ITEMTYPES(ITEMCOUNT),STAT=STATUS)
    _VERIFY(STATUS)
    allocate(DOIT     (ITEMCOUNT),STAT=STATUS)
    _VERIFY(STATUS)
    call ESMF_StateGet(STATE,ITEMNAMELIST=ITEMNAMES,ITEMTYPELIST=ITEMTYPES,RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_StateGet(STATE,name=StateName,RC=STATUS)
    _VERIFY(STATUS)
    forceWriteNoRestart_ = .false.
    if(present(forceWriteNoRestart)) then
       forceWriteNoRestart_ = forceWriteNoRestart
    endif
    if(present(NAME)) then
       DOIT = ITEMNAMES==NAME
       _ASSERT(count(DOIT)/=0, 'count(DOIT) must not be 0')
    else
       DOIT = .true.
    endif
    bundle_write = ESMF_FieldBundleCreate(name=trim(StateName),rc=STATUS)
    _VERIFY(STATUS)
    call ESMF_FieldBundleSet(bundle_write,grid=arrdes%grid,rc=STATUS)
    _VERIFY(STATUS)
    call ESMF_InfoGetFromHost(state,infoh_state,rc=status)
    _VERIFY(STATUS)
    call ESMF_InfoGet(infoh_state,'POSITIVE',positive,rc=status)
    _VERIFY(status)
    call ESMF_InfoGetFromHost(bundle_write,infoh_bundle,rc=status)
    _VERIFY(STATUS)
    call ESMF_InfoSet(infoh_bundle,'POSITIVE',positive,rc=status)
    _VERIFY(status)
    flip = trim(positive)=="up"
    DO I = 1, ITEMCOUNT
       IF (DOIT     (I)) then
          IF (ITEMTYPES(I) == ESMF_StateItem_FieldBundle) then
             call ESMF_StateGet(state, itemnames(i), bundle, rc=status)
             _VERIFY(STATUS)
             skipWriting = .false.
             if (.not. forceWriteNoRestart_) then
                call ESMF_InfoGetFromHost(bundle,infoh_bundle,rc=status)
                _VERIFY(STATUS)
                isPresent = ESMF_InfoIsPresent(infoh_bundle,'RESTART',rc=status)
                _VERIFY(STATUS)
                if (isPresent) then
                   call ESMF_InfoGet(infoh_bundle,'RESTART',RST,rc=status)
                   _VERIFY(STATUS)
                   skipWriting = (RST == MAPL_RestartSkip)
                end if
             else
                skipWriting = .true.
             end if
             call ESMF_InfoGetFromHost(state, infoh_state, _RC)
             isPresent = ESMF_InfoIsPresent(infoh_state, 'MAPL_TestFramework', _RC)
             if (isPresent) then
                call ESMF_InfoSet(infoh_state, key='MAPL_TestFramework', value=is_test_framework, _RC)
                if (is_test_framework) skipWriting = .false.
             end if
             if (skipWriting) cycle
             call ESMF_FieldBundleGet(bundle, fieldCount=nBundle, rc=STATUS)
             _VERIFY(STATUS)
             call ESMF_FieldBundleGet(bundle, name=BundleName, rc=status)
             _VERIFY(STATUS)
             DO J = 1,nBundle
               call ESMF_FieldBundleGet(bundle, fieldIndex=J, field=field, rc=status)
               _VERIFY(STATUS)
               call ESMF_FieldGet(field,name=FieldName,rc=status)
               _VERIFY(STATUS)
               ! Tack on BundleName to distiguish duplicate FieldNames in different Bundles (PCHEM for instance)
               FieldName = trim(BundleName) //'_'// trim(FieldName)
               new_field = MAPL_FieldCreate(Field,FieldName,rc=status)
               _VERIFY(STATUS)
               call MAPL_FieldBundleAdd(bundle_write,new_field,rc=status)
               _VERIFY(STATUS)
             ENDDO
          ELSE IF (ITEMTYPES(I) == ESMF_StateItem_Field) THEN
             call ESMF_StateGet(state, itemnames(i), field, rc=status)
             _VERIFY(STATUS)
             call ESMF_FieldGet(field,array=array,rc=FieldIsValid)
             if (fieldIsValid == 0) then
                skipWriting = .false.
                if (.not. forceWriteNoRestart_) then
                   call ESMF_InfoGetFromHost(field,infoh_field,rc=status)
                   _VERIFY(STATUS)
                   isPresent = ESMF_InfoIsPresent(infoh_field,'RESTART',rc=status)
                   _VERIFY(STATUS)
                   if (isPresent) then
                      call ESMF_InfoGet(infoh_field, key='RESTART', value=RST, rc=status)
                      _VERIFY(STATUS)
                      skipWriting = (RST == MAPL_RestartSkip)
                   end if
                else
                   skipWriting = .true.
                end if
                call ESMF_InfoGetFromHost(state, infoh_state, _RC)
                isPresent = ESMF_InfoIsPresent(infoh_state, 'MAPL_TestFramework', _RC)
                if (isPresent) then
                   call ESMF_InfoGet(infoh_state, key='MAPL_TestFramework', value=is_test_framework, _RC)
                   if (is_test_framework) skipWriting = .false.
                end if
                if (skipWriting) cycle
                call ESMF_InfoGetFromHost(field, infoh_field, _RC)
                isPresent = ESMF_InfoIsPresent(infoh_field, 'doNotAllocate', _RC)
                if (isPresent) then
                   call ESMF_InfoGet(infoh_field, key='doNotAllocate', value=dna, rc=status)
                   _VERIFY(STATUS)
                   skipWriting = (dna /= 0)
                endif
                call ESMF_InfoGetFromHost(state, infoh_state, _RC)
                isPresent = ESMF_InfoIsPresent(infoh_state, 'MAPL_TestFramework', _RC)
                if (isPresent) then
                   call ESMF_InfoGet(infoh_state, key='MAPL_TestFramework', value=is_test_framework, _RC)
                   if (is_test_framework) skipWriting = .false.
                end if
                if (skipWriting) cycle
                if (flip) then
                   added_field = create_flipped_field(field,rc=status)
                   _VERIFY(status)
                else
                   added_field = field
                end if
                call MAPL_FieldBundleAdd(bundle_write,added_field,rc=status)
                _VERIFY(STATUS)
             end if
          end IF
       END IF
    END DO
    deallocate(ITEMNAMES)
    deallocate(ITEMTYPES)
    deallocate(DOIT     )
    call ESMF_InfoGetFromHost(state, infoh_state, _RC)
    isPresent = ESMF_InfoIsPresent(infoh_state, 'MAPL_GridCapture', _RC)
    if (isPresent) then
       call ESMF_InfoGet(infoh_state, key='MAPL_GridCapture', value=isGridCapture, _RC)
       call ESMF_InfoGetFromHost(bundle_write, infoh_bundle, _RC)
       call ESMF_InfoSet(infoh_bundle, key="MAPL_GridCapture", value=isGridCapture, _RC)
    end if
    call MAPL_BundleWriteNCPar(Bundle_Write, arrdes, CLOCK, filename, oClients=oClients, rc=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_StateVarWriteNCPar
Call graph
mapl_statevarwritencpar calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoSet, esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_assert, mapl_fieldbundleadd, mapl_fieldcreate, create_flipped_field, mapl_bundlewritencpar, mapl_return, mapl_verify
mapl_varwritencpar calls mapl_statevarwritencpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave