MAPL_SetFieldTimeFromField – MAPL
MAPL_SetFieldTimeFromField Module Subroutine
17 statements
Source File
module subroutine MAPL_SetFieldTimeFromField(FIELD, TIME, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
type(ESMF_Time), intent(inout) :: TIME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  module subroutine  MAPL_SetFieldTimeFromField (FIELD, TIME, RC )
    type(ESMF_FIELD),        intent(INOUT) :: FIELD
    type(ESMF_TIME),         intent(INOUT) :: TIME !ALT: IN
    integer, optional,       intent(  OUT) :: RC
    character(len=ESMF_MAXSTR),parameter   :: IAm=" MAPL_SetFieldTimeFromField"
    integer                                :: STATUS
    character(len=ESMF_MAXSTR)             :: TIMESTAMP
    type(ESMF_Info)                        :: infoh
    call ESMF_TimeGet(TIME,timeString=TIMESTAMP,_RC)
    call ESMF_InfoGetFromHost(FIELD,infoh,_RC)
    call ESMF_InfoSet(infoh,'TimeStamp',TIMESTAMP,_RC)
    _RETURN(ESMF_SUCCESS)
  end subroutine  MAPL_SetFieldTimeFromField
Call graph
mapl_setfieldtimefromfield calls ESMF_InfoGetFromHost, ESMF_InfoSet, ESMF_TimeGet, mapl_return, mapl_verify, mapl_setfieldtimefromfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_fieldsettime calls mapl_setfieldtimefromfield
mapl_climupdate calls mapl_fieldsettime
mapl_setfieldtimefromstate calls mapl_fieldsettime, mapl_setfieldtimefromstate