MAPL_Initialize – MAPL
MAPL_Initialize Subroutine
27 statements
Source File
public subroutine MAPL_Initialize(unusable, comm, logging_config, enable_global_timeprof, enable_global_memprof, rc)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
character(len=*), intent(in), optional :: logging_config
logical, intent(in), optional :: enable_global_timeprof
logical, intent(in), optional :: enable_global_memprof
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_Initialize(unusable,comm,logging_config,enable_global_timeprof, enable_global_memprof, rc)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      character(len=*), optional,intent(in) :: logging_config
      logical, optional, intent(in) :: enable_global_timeprof
      logical, optional, intent(in) :: enable_global_memprof
      integer, optional, intent(out) :: rc
      character(:), allocatable :: logging_configuration_file
      integer :: comm_world,status
      _UNUSED_DUMMY(unusable)
      call initialize_profiler(comm=comm_world, enable_global_timeprof=enable_global_timeprof, enable_global_memprof=enable_global_memprof, _RC)
      if (present(logging_config)) then
         logging_configuration_file=logging_config
      else
         logging_configuration_file=''
      end if
      if (present(comm)) then
         comm_world = comm
      else
         comm_world=MPI_COMM_WORLD
      end if
#ifdef BUILD_WITH_PFLOGGER
      call initialize_pflogger(comm=comm_world,logging_config=logging_configuration_file, _RC)
#endif
      _RETURN(_SUCCESS)
   end subroutine MAPL_Initialize
Call graph
mapl_initialize calls initialize_profiler, initialize_pflogger, mapl_return, mapl_verify
initialize_pflogger calls mapl_return, mapl_verify, basic_config, filehandler, load_file, mpi_comm_rank, mpiformatter, mpilock, get_logger, initialize, warning, push_back, set_formatter, set_level, set_lock, streamhandler
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
main calls mapl_initialize
new_mapl_cap_from_dso calls mapl_initialize
new_mapl_cap_from_set_services calls mapl_initialize
newextdatadriver calls mapl_initialize
time_ave calls mapl_initialize
ut_regridding calls mapl_initialize
extdatadriver calls newextdatadriver
mapl_cap calls new_mapl_cap_from_dso, new_mapl_cap_from_set_services
comp_testing_driver calls main
regrid_util calls main