MAPL_Deprecated – MAPL
MAPL_Deprecated Subroutine
17 statements
Source File
public subroutine MAPL_Deprecated(file_name, module_name, procedure_name, rc)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: module_name
character(len=*), intent(in) :: procedure_name
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine MAPL_Deprecated(file_name, module_name, procedure_name, rc)
      use, intrinsic :: iso_fortran_env, only: ERROR_UNIT
      character(*), intent(in) :: file_name
      character(*), intent(in) :: module_name
      character(*), intent(in) :: procedure_name
      integer, optional, intent(out) :: rc
      integer :: status
      write(ERROR_UNIT,*,iostat=status) "Invoking deprecated procedure: ", procedure_name
      _VERIFY(status)
      write(ERROR_UNIT,*,iostat=status) "    ...             in module: ", module_name
      _VERIFY(status)
      write(ERROR_UNIT,*,iostat=status) "    ...               in file: ", file_name
      _VERIFY(status)
      _ASSERT(.not. FAIL_ON_DEPRECATED, "    ... aborting.")
      _RETURN(_SUCCESS)
   end subroutine MAPL_Deprecated
Call graph
mapl_deprecated calls mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize