MAPL_GridCompSetVerticalGeom – MAPL
MAPL_GridCompSetVerticalGeom Subroutine
12 statements
Source File
public subroutine MAPL_GridCompSetVerticalGeom(gridcomp, vertical_geom, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(VerticalGeom), intent(in) :: vertical_geom
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GridCompSetVerticalGeom(gridcomp, vertical_geom, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(VerticalGeom), intent(in) :: vertical_geom
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      call outer_meta%set_vertical_geom(vertical_geom)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GridCompSetVerticalGeom
Call graph
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, set_vertical_geom
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
setup calls mapl_gridcompsetverticalgeom
test_full_run_sequence calls mapl_gridcompsetverticalgeom
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup