MAPL_LocStreamCreateTileGrid – MAPL
MAPL_LocStreamCreateTileGrid Subroutine
42 statements
Source File
private subroutine MAPL_LocStreamCreateTileGrid(LocStream, Grid, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(inout) :: LocStream
type(ESMF_Grid), intent(inout) :: Grid
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_LocStreamCreateTileGrid(LocStream, GRID, RC)
    type(MAPL_LocStream),  intent(INOUT) :: LocStream
    type(ESMF_Grid),       intent(INout) :: Grid
    integer, optional,     intent(  OUT) :: RC
! Local variables
    integer                    :: STATUS
    type(MAPL_LocStreamType), pointer :: STREAM
    type (ESMF_Grid)                  :: TILEGRID
    type (ESMF_DistGrid)              :: distgrid
    type(ESMF_Info)                   :: infoh
    character(len=MAPL_TileNameLength):: GNAME
    integer                           :: arbIndexCount
    integer, allocatable              :: arbIndex(:,:)
    integer, parameter                :: DUMMY_NSUBTILES=1
    integer(kind=INT64)               :: ADDR
! Begin
!------
! Make sure Location stream has been created
!-------------------------------------------
    _ASSERT(associated(LocStream%Ptr),'needs informative message')
! Alias to the pointer
!---------------------
    STREAM => LocStream%Ptr
! Get the attached grid's info
!-----------------------------
    call ESMF_GridGet(GRID, NAME=GNAME, RC=STATUS)
    _VERIFY(STATUS)
! Create TILEGRID
!----------------
    distgrid = ESMF_DistGridCreate( &
         arbSeqIndexList=STREAM%LOCAL_ID, rc=status)
    _VERIFY(STATUS)
    TILEGRID = ESMF_GridEmptyCreate(rc=status)
    _VERIFY(STATUS)
    arbIndexCount = size(STREAM%LOCAL_ID)
    allocate(arbIndex(arbIndexCount,1), stat=status)
    _VERIFY(STATUS)
    arbIndex(:,1) = STREAM%LOCAL_ID
    call ESMF_GridSet(tilegrid,  &
         name="tile_grid_"//trim(Stream%NAME)//'@'//trim(GNAME),    &
         distgrid=distgrid, &
         indexFlag=ESMF_INDEX_DELOCAL, &
         distDim = (/1/), &
         localArbIndexCount=arbIndexCount, &
         localArbIndex=arbIndex, &
         minIndex=(/1/), &
         maxIndex=(/STREAM%NT_GLOBAL/), &
         rc=status)
    _VERIFY(STATUS)
    deallocate(arbIndex)
    call ESMF_GridCommit(tilegrid, rc=status)
    _VERIFY(STATUS)
    call ESMF_InfoGetFromHost(tilegrid,infoh,rc=status)
    _VERIFY(STATUS)
    call ESMF_InfoSet(infoh,'GRID_EXTRADIM',DUMMY_NSUBTILES,rc=status)
    _VERIFY(STATUS)
    STREAM%TILEGRID = TILEGRID
!ALT: here we are using a C routine to get the pointer to LocStream
!     and we are going to store it in TILEGRID as INTEGER*8 attribute
    call c_MAPL_LocStreamRetrievePtr(LocStream, ADDR)
    call ESMF_InfoSet(infoh,'TILEGRID_LOCSTREAM_ADDR',ADDR,rc=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_LocStreamCreateTileGrid
Call graph
mapl_locstreamcreatetilegrid calls ESMF_DistGridCreate, ESMF_GridCommit, ESMF_GridEmptyCreate, ESMF_GridGet, ESMF_GridSet, ESMF_InfoGetFromHost, ESMF_InfoSet, c_mapl_locstreamretrieveptr, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_locstreamcreatefromfile calls mapl_locstreamcreatetilegrid
mapl_locstreamcreatefromstream calls mapl_locstreamcreatetilegrid
mapl_locstreamcreate calls mapl_locstreamcreatefromfile, mapl_locstreamcreatefromstream
initialize calls mapl_locstreamcreate
initialize_ calls mapl_locstreamcreate