MAPL_GridCompSetGeomGrid – MAPL
MAPL_GridCompSetGeomGrid Subroutine
13 statements
Source File
private subroutine MAPL_GridCompSetGeomGrid(gridcomp, grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_Grid), intent(in) :: grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GridCompSetGeomGrid(gridcomp, grid, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(ESMF_Grid), intent(in) :: grid
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Geom) :: geom
      geom = ESMF_GeomCreate(grid, ESMF_STAGGERLOC_INVALID, _RC)
      call MAPL_GridCompSetGeom(gridcomp, geom, _RC)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GridCompSetGeomGrid
Call graph
mapl_gridcompsetgeomgrid calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeom calls mapl_gridcompsetgeomgrid, mapl_gridcompsetgeom, mapl_gridcompsetgeomlocstream, mapl_gridcompsetgeommesh, mapl_gridcompsetgeomxgrid
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_gridcompsetgeomlocstream calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeommesh calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeomxgrid calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_throw_exception calls initialize