MAPL_VarWriteNCpar_R4_4d – MAPL
MAPL_VarWriteNCpar_R4_4d Subroutine
75 statements
Source File
private subroutine MAPL_VarWriteNCpar_R4_4d(formatter, name, A, ARRDES, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_VarWriteNCpar_R4_4d(formatter, name, A, ARRDES, oClients, RC)
    type(Netcdf4_Fileformatter) , intent(IN   ) :: formatter
    character(len=*)            , intent(IN   ) :: name
    real(kind=ESMF_KIND_R4)     , intent(IN   ) :: A(:,:,:,:)
    type(ArrDescr), optional    , intent(INOUT) :: ARRDES
    type (ClientManager), optional, intent(inout)  :: oClients
    integer,           optional , intent(  OUT) :: RC
    integer                               :: status
    integer :: K, L
    integer ::  i1, j1, in, jn,  global_dim(3), dim3, dim4,i
    type(ArrayReference)     :: ref
    integer :: start_bound,end_bound,counts_per_writer
    logical :: in_bounds
    real(kind=ESMF_KIND_R4), pointer :: a_temp(:,:,:,:)
    character(len=:), allocatable :: writer_filename
    if (present(arrdes)) then
       if (present(oClients)) then
          if (arrdes%split_checkpoint) then
             call MAPL_GridGet(arrdes%grid,globalCellCountPerDim=global_dim,rc=status)
              _VERIFY(status)
             call MAPL_Grid_interior(arrdes%grid,i1,in,j1,jn)
             _ASSERT( i1 == arrdes%I1(arrdes%NX0), "interior starting i1 not match")
             _ASSERT( j1 == arrdes%j1(arrdes%NY0), "interior starting j1 not match")
             _ASSERT( size(a,1) == in-i1+1, "size not match")
             _ASSERT( size(a,2) == jn-j1+1, "size not match")
             counts_per_writer = global_dim(2)/arrdes%num_writers
             allocate(a_temp(0,0,0,0))
             do i=1,arrdes%num_writers
                start_bound = (i-1)*counts_per_writer+1
                end_bound   = i*counts_per_writer
                in_bounds = (j1 .ge. start_bound) .and. (jn .le. end_bound)
                dim3 = size(a,3)
                dim4 = size(a,4)
                if (in_bounds) then
                   ref = ArrayReference(A)
                else
                   ref = ArrayReference(a_temp)
                end if
                writer_filename = get_fname_by_rank(trim(arrdes%filename),i-1)
                call oClients%collective_stage_data(arrdes%collection_id(i),trim(writer_filename),trim(name), &
                            ref,start=[i1,j1-(i-1)*counts_per_writer,1,1], &
                            global_start=[1,1,1,1], global_count=[global_dim(1),global_dim(2)/arrdes%num_writers,dim3,dim4])
             enddo
             _RETURN(_SUCCESS)
          else
             call MAPL_GridGet(arrdes%grid,globalCellCountPerDim=global_dim,rc=status)
              _VERIFY(status)
             call MAPL_Grid_interior(arrdes%grid,i1,in,j1,jn)
             _ASSERT( i1 == arrdes%I1(arrdes%NX0), "interior starting i1 not match")
             _ASSERT( j1 == arrdes%j1(arrdes%NY0), "interior starting j1 not match")
             ref = ArrayReference(A)
             _ASSERT( size(a,1) == in-i1+1, "size not match")
             _ASSERT( size(a,2) == jn-j1+1, "size not match")
             call oClients%collective_stage_data(arrdes%collection_id(1),trim(arrdes%filename),trim(name), &
                         ref,start=[i1,j1,1,1], &
                         global_start=[1,1,1,1], global_count=[global_dim(1),global_dim(2),size(a,3),size(a,4)])
             _RETURN(_SUCCESS)
          end if
       else
          do K = 1,size(A,4)
             do L = 1,size(A,3)
                call MAPL_VarWrite(formatter, name, A(:,:,L,K), arrdes=arrdes, &
                     & oClients=oClients, lev=l, offset2=k, rc=status)
                _VERIFY(status)
             end do
          end do
       end if
    else
       do K = 1,size(A,4)
          do L = 1,size(A,3)
             call MAPL_VarWrite(formatter, name, A(:,:,L,K), &
                  & oClients=oClients, lev=l, offset2=k, rc=status)
             _VERIFY(status)
          end do
       enddo
    endif
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarWriteNCpar_R4_4d
Call graph
mapl_varwritencpar_r4_4d calls mapl_assert, mapl_grid_interior, mapl_varwrite, collective_stage_data, get_fname_by_rank, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_grid_interior calls mapl_grid_interior
mapl_varwrite calls mapl_varwritencpar_r4_4d, mapl_varwritencpar_r4_1d, mapl_varwritencpar_r4_2d, mapl_varwritencpar_r4_3d, mapl_varwritencpar_r8_1d, mapl_varwritencpar_r8_2d, mapl_varwritencpar_r8_3d, mapl_varwritencpar_r8_4d
collective_stage_data calls mapl_return, mapl_verify, collective_stage_data, current
get_fname_by_rank calls i_to_string
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldwritencpar calls mapl_varwrite
mapl_varwritencpar_r4_3d calls mapl_varwrite
mapl_varwritencpar_r8_3d calls mapl_varwrite
mapl_varwritencpar_r8_4d calls mapl_varwrite
mapl_bundlewritencpar calls mapl_fieldwritencpar
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar