MAPL_MethodAdd – MAPL
MAPL_MethodAdd Subroutine
24 statements
Source File
public subroutine MAPL_MethodAdd(state, label, userRoutine, rc)
Uses
mapl_ESMF_Interfaces
MAPL_OpenMP_Support
mapl_CallbackMap
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
character(len=*), intent(in) :: label
procedure(I_CallBackMethod) :: userRoutine
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine MAPL_MethodAdd(state, label, userRoutine, rc)
      use mapl_ESMF_Interfaces
      use mapl_CallbackMap
      use mapl_OpenMP_Support, only : get_callbacks
      type(ESMF_State), intent(inout) :: state
      character(*), intent(in) :: label
      procedure(I_CallBackMethod) :: userRoutine
      integer, optional, intent(out) :: rc
      integer :: status
      type(CallbackMap), pointer :: callbacks
      call ESMF_MethodAdd(state, label=label, userRoutine=userRoutine, _RC)
      call get_callbacks(state, callbacks, _RC)
      call callbacks%insert(label, wrap(userRoutine))
      _RETURN(ESMF_SUCCESS)
   contains
      function wrap(userRoutine) result(wrapper)
         type(CallbackMethodWrapper) :: wrapper
         procedure(I_CallBackMethod) :: userRoutine
         wrapper%userRoutine => userRoutine
      end function wrap
   end subroutine MAPL_MethodAdd
Call graph
mapl_methodadd calls ESMF_MethodAdd, insert, get_callbacks, mapl_return, mapl_verify
get_callbacks calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoSet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
mapl_throw_exception calls initialize