MAPL_SimpleBundleCreateFromBundle – MAPL
MAPL_SimpleBundleCreateFromBundle Function
291 statements
Source File
private function MAPL_SimpleBundleCreateFromBundle(Bundle, rc, Levs, LevUnits, ptop, delp, only_vars, strict, name) result(self)
Given an ESMF Bundle, creates a corresponding Simple Bundle. The specification of a vertical grid is optional but useful in many cases. The 1-D Levs will default to the layer number, and units of “1”. Input parameters (ptop,delp) can be used to record the corresponding Lagrangian Control Volume Grid. When delp is not specified, variables DELP or delp are used if present inside the bundle.
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout), target :: Bundle
ESMF Bundle
integer, intent(out), optional :: rc
real(kind=ESMF_KIND_R4), intent(in), optional :: Levs(:)
Vertical coordinates Constant levels
character(len=*), intent(in), optional :: LevUnits
Level units
real(kind=ESMF_KIND_R4), intent(in), optional :: ptop
top pressure (Pa) Lagrangian Control Volume Info
real(kind=ESMF_KIND_R4), intent(in), optional, pointer :: delp(:,:,:)
layer thickness (Pa)
character(len=*), intent(in), optional :: only_vars
comma separated field names
logical, intent(in), optional :: strict
force name matching, ignored if only_vars is not present
character(len=*), intent(in), optional :: name
name
Return Value type(MAPL_SimpleBundle)
Simple Bundle
Calls
Called by
Source Code
  Function MAPL_SimpleBundleCreateFromBundle ( Bundle, rc,     &
                                               Levs, LevUnits, &
                                               ptop, delp,     &
                                               only_vars,      &
                                               strict,         &
                                               name) result (self)
    type(MAPL_SimpleBundle)                        :: self          !! Simple Bundle
    type(ESMF_FieldBundle), target, intent(inout)  :: Bundle        !! ESMF Bundle
    integer, OPTIONAL,              intent(out)    :: rc
    real(ESMF_KIND_R4), OPTIONAL,   intent(in)     :: Levs(:)       !! Vertical coordinates
                                                                    !! Constant levels
    character(len=*), OPTIONAL,     intent(in)     :: LevUnits      !! Level units
    real(ESMF_KIND_R4), OPTIONAL,   intent(in)     :: ptop          !! top pressure (Pa)
                                                                    !! Lagrangian Control Volume Info
    real(ESMF_KIND_R4), OPTIONAL, pointer, &
                                    intent(in)     :: delp(:,:,:)   !! layer thickness (Pa)
    character(len=*), OPTIONAL,     intent(in)     :: only_vars     !! comma separated field names
    logical, OPTIONAL,              intent(in)     :: strict        !! force name matching, ignored if only_vars is not present
    character(len=*), OPTIONAL,     intent(in)     :: name          !! name
!                           ------
    type(ESMF_Field) :: Field
    type(ESMF_Array) :: Array
    type(ESMF_TypeKind_Flag) :: typeKind
    real(ESMF_KIND_R8), pointer :: LonsRad(:,:), LatsRad(:,:)
    integer :: arrayRank, I, n, n1d, n2d, n3d, NumVars
    integer :: im, jm, km, dims(3)
    type(ESMF_FieldStatus_Flag) :: fieldStatus
    logical :: strict_match
    logical :: isPresent
    logical :: isPresentBundle
    logical :: haveDelp
    integer :: n_vars
    character(len=ESMF_MAXSTR) :: message
    logical, allocatable       :: isRequested(:)
    character(len=ESMF_MAXSTR), allocatable :: var_list(:)
    character(len=ESMF_MAXSTR) :: bundleName
    character(len=ESMF_MAXSTR) :: fieldName
    integer :: status
    self%Bundle => Bundle ! remember where it came from
    self%bundleAlloc = .false. ! this is the default. We can overwrite it later
    call ESMF_FieldBundleGet (BUNDLE, name=bundleName, &
                                      grid=self%grid, &
                                      FieldCount=NumVars, _RC )
    if (present(name)) then
       if (len_trim(name) > ESMF_MAXSTR) then
           message = 'string "'//trim(name)//'" is too long to be used '// &
                     'as a Simple Bundle name'
           __raise__(MAPL_RC_ERROR, message)
       end if
       self%name = trim(name)
    else
       self%name = bundleName
    end if
!                             -------------------
!                             Requested variables
!                             -------------------
    if (present(strict)) then
       strict_match = strict
    else
       strict_match = .true.  ! by default do strict name matching
    end if
    allocate(isRequested(NumVars), __STAT__)
    isRequested = .false.
    if (present(only_vars)) then
       n_vars = csv_tokens_count_(only_vars)
       _ASSERT(n_vars <= NumVars,'needs informative message')
       allocate(var_list(n_vars), __STAT__)
       var_list = '__NONE__'
       call csv_tokens_get_(only_vars, var_list, _RC)
       do i = 1, size(var_list)
          isPresent = .false.
          do n = 1, NumVars
             call MAPL_FieldBundleGet(BUNDLE, n, FIELD, _RC)
             call ESMF_FieldGet (FIELD, name=fieldName, _RC)
             if (fieldName == var_list(i)) then
                isPresent = .true.
                exit
             end if
          end do
          if (isPresent) then
             isRequested(n) = .true.
          else
             if (strict_match) then
                message = 'could not find field '//trim(var_list(i))// &
                          ' in Simple Bundle <'//trim(self%name)//'>'
                __raise__(MAPL_RC_ERROR, message)
             end if
          end if
       end do
       deallocate(var_list)
    else
       isRequested = .true.
    end if
!                             --------------------
!                             Coordinate variables
!                             --------------------
    call MAPL_GridGet(self%Grid, localCellCountPerDim = dims, _RC)
    im = dims(1);  jm = dims(2);  km = dims(3)
    allocate(self%coords%Lons(im,jm), self%coords%Lats(im,jm), self%coords%Levs(km), __STAT__)
!   Retrieve the lat/lon from Grid and convert to degrees
!   -----------------------------------------------------
   call ESMF_GridGetCoord (self%Grid, coordDim=1, localDE=0, &
                           staggerloc=ESMF_STAGGERLOC_CENTER, &
                           farrayPtr=LonsRad, _RC)
   call ESMF_GridGetCoord (self%Grid, coordDim=2, localDE=0, &
                           staggerloc=ESMF_STAGGERLOC_CENTER, &
                           farrayPtr=LatsRad, _RC)
   self%coords%Lons(:,:) = ( 180. / MAPL_PI) * LonsRad(:,:)
   self%coords%Lats(:,:) = ( 180. / MAPL_PI) * LatsRad(:,:)
!  1-D Levels
!  ----------
   if ( present(Levs) ) then
      if ( size(Levs) == km ) then
         self%coords%Levs(:) = Levs(:)
      else
         STATUS = 77
         _VERIFY(STATUS)
      end if
   else
      self%coords%Levs(:) = (/ (i, i = 1, km) /)
   end if
   if ( present(LevUnits) ) then
      self%coords%LevUnits = LevUnits
   else
      self%coords%LevUnits = '1'
   end if
!  Optional Lagrangian Control Volume info
!  ---------------------------------------
   if ( present(ptop) ) self%coords%lcv%ptop = ptop
   if ( present(delp) ) then ! User specied
!ALT      self%coords%lcv%delp = delp
      self%coords%lcv%delp => delp
   else ! Look inside bundle for delp or DELP
      self%coords%lcv%delp => NULL()
      haveDelp = .FALSE.
      call ESMF_FieldBundleGet (Bundle, fieldName='DELP', isPresent=isPresentBundle, RC=STATUS)
      _VERIFY(STATUS)
      if (isPresentBundle) then
         call ESMF_FieldBundleGet (Bundle, fieldName='DELP', field=Field, RC=STATUS)
         _VERIFY(STATUS)
         haveDelp = .TRUE.
      else
         call ESMF_FieldBundleGet (Bundle, fieldName='delp', isPresent=isPresentBundle, RC=STATUS)
         _VERIFY(STATUS)
         if (isPresentBundle) then
            call ESMF_FieldBundleGet (Bundle, fieldName='delp', field=Field, RC=STATUS)
            _VERIFY(STATUS)
            haveDelp = .TRUE.
         end if
      end if
      if (haveDelp) then
         call ESMF_FieldGet(Field, status=fieldStatus, _RC)
         if (fieldStatus == ESMF_FIELDSTATUS_COMPLETE) then
            call ESMF_FieldGet(Field, 0, self%coords%lcv%delp, _RC)
         end if
      end if
   end if
!                             --------------------
!                                 Data Arrays
!                             --------------------
!   A little overestimate for the sizes, but why bother
!   ---------------------------------------------------
    allocate(self%r1(NumVars), &
             self%r2(NumVars), &
             self%r3(NumVars), &
             __STAT__)
    n1d = 0
    n2d = 0
    n3d = 0
    DO I = 1, NumVars
       call MAPL_FieldBundleGet(BUNDLE, I, FIELD, _RC)
       call ESMF_FieldGet (FIELD, name=fieldName, status=fieldStatus, _RC)
       if (fieldStatus == ESMF_FIELDSTATUS_COMPLETE .and. isRequested(I)) then
          call ESMF_FieldGet (FIELD, ARRAY=array, _RC )
          call ESMF_ArrayGet (array, rank=arrayRank, typeKind = typeKind, _RC )
       else
          cycle
       end if
!      Real*4
!      ------
       if ( typeKind == ESMF_TYPEKIND_R4 ) then
          if ( arrayRank == 1 ) then
             n1d = n1d + 1
             call ESMF_FieldGet(Field, localDE=0, farrayPtr=self%r1(n1d)%qr4, _RC )
             self%r1(n1d)%name = trim(fieldName)
             self%r1(n1d)%myKind = ESMF_KIND_R4
             self%r1(n1d)%q => self%r1(n1d)%qr4 ! convenience alias
          else if ( arrayRank == 2 ) then
             n2d = n2d + 1
             call ESMF_FieldGet(Field, localDE=0, farrayPtr=self%r2(n2d)%qr4, _RC )
             self%r2(n2d)%name = trim(fieldName)
             self%r2(n2d)%myKind = ESMF_KIND_R4
             self%r2(n2d)%q => self%r2(n2d)%qr4 ! convenience alias
         else if ( arrayRank == 3 ) then
             n3d = n3d + 1
             call ESMF_FieldGet(Field, localDE=0, farrayPtr=self%r3(n3d)%qr4, _RC )
             self%r3(n3d)%name = trim(fieldName)
             self%r3(n3d)%myKind = ESMF_KIND_R4
             self%r3(n3d)%q => self%r3(n3d)%qr4 ! convenience alias
          else
             STATUS = 77
             _VERIFY(STATUS)
          end if
!      Real*8
!      ------
       else if ( typeKind == ESMF_TYPEKIND_R8 ) then
          if ( arrayRank == 1 ) then
             n1d = n1d + 1
             call ESMF_FieldGet(Field, localDE=0, farrayPtr=self%r1(n1d)%qr8, _RC )
             self%r1(n1d)%name = trim(fieldName)
             self%r1(n1d)%myKind = ESMF_KIND_R8
          else if ( arrayRank == 2 ) then
             n2d = n2d + 1
             call ESMF_FieldGet(Field, localDE=0, farrayPtr=self%r2(n2d)%qr8, _RC )
             self%r2(n2d)%name = trim(fieldName)
             self%r2(n2d)%myKind = ESMF_KIND_R8
          else if ( arrayRank == 3 ) then
             n3d = n3d + 1
             call ESMF_FieldGet(Field, localDE=0, farrayPtr=self%r3(n3d)%qr8, _RC )
             self%r3(n3d)%name = trim(fieldName)
             self%r3(n3d)%myKind = ESMF_KIND_R8
          else
             STATUS = 77
             _VERIFY(STATUS)
          end if
!      Unknown kind
!      ------------
       else
          STATUS = 88
          _VERIFY(STATUS)
       end if
    end do
    self%n1d = n1d
    self%n2d = n2d
    self%n3d = n3d
    deallocate(isRequested, __STAT__)
    _RETURN(_SUCCESS)
  contains
    function csv_tokens_count_(str, delimiter) result(n)
      implicit none
      integer                         :: n
      character(len=*), intent(in)    :: str
      character, optional, intent(in) :: delimiter
      ! local
      character, parameter :: char_comma = ','
      character            :: c
      integer              :: i
      if (present(delimiter)) then
         c = delimiter
      else
         c = char_comma
      end if
      n = 1
      do i = 1, len_trim(str)
         if (str(i:i) == c) then
            n = n + 1
         end if
      end do
    end function csv_tokens_count_
    subroutine csv_tokens_get_(str, list, delimiter, ignore, rc)
      implicit none
      character(len=*), intent(in)     :: str
      character(len=*), intent(inout)  :: list(:)
      character, optional, intent(in)  :: delimiter
      character, optional, intent(in)  :: ignore
      integer, optional, intent(inout) :: rc
      ! local
      character, parameter :: char_empty = ''
      character, parameter :: char_space = ' '
      character, parameter :: char_comma = ','
      character :: c_dlm, c_ign
      integer   :: i, j, n, err
      if (present(delimiter)) then
         c_dlm = delimiter
      else
         c_dlm = char_comma
      end if
      if (present(ignore)) then
         c_ign = ignore
      else
         c_ign = char_space
      end if
      list = char_empty
      j = 1
      n = 1
      err = 0
      do i = 1, len_trim(str)
         if (str(i:i) /= c_dlm) then
            if (n > size(list)) then
               err = 99
               exit
            end if
            if (str(i:i) /= c_ign) then
               list(n)(j:j) = str(i:i)
               j = j + 1
            end if
         else
            j = 1
            n = n + 1
         end if
      end do
      if (present(rc)) then
         rc = err
      end if
    end subroutine csv_tokens_get_
  end Function MAPL_SimpleBundleCreateFromBundle
Call graph
mapl_simplebundlecreatefrombundle calls ESMF_GridGetCoord, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_assert, mapl_fieldbundleget, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleget calls mapl_fieldbundlegetbyindex
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundlegetbyindex calls mapl_fieldbundlegetbyindex
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
mapl_simplebundlecreate calls mapl_simplebundlecreatefrombundle, mapl_simplebundlecreatefromstate
mapl_simplebundlecreatefromstate calls mapl_simplebundlecreatefrombundle
mapl_simplebundleread calls mapl_simplebundlecreate