MAPL_CopyFriendlinessInField – MAPL
MAPL_CopyFriendlinessInField Subroutine
31 statements
Source File
private subroutine MAPL_CopyFriendlinessInField(FIELDOUT, FIELDIN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELDOUT
type(ESMF_Field), intent(inout) :: FIELDIN
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_CopyFriendlinessInField(FIELDOUT,FIELDIN,RC)
      type(ESMF_FIELD),      intent(INOUT) :: FIELDOUT
      type(ESMF_FIELD),      intent(INout) :: FIELDIN
      integer,    optional,  intent(  OUT) :: rc
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_CopyFriendlinessInField"
      integer                               :: status
      integer                               :: I, NF
      character(len=ESMF_MAXSTR)            :: NAME
      logical                               :: VALUE
      type(ESMF_INFO)                       :: infohin
      type(ESMF_INFO)                       :: infohout
      call ESMF_InfoGetFromHost(FIELDIN, infohin, RC=status)
      _VERIFY(STATUS)
      call ESMF_InfoGetFromHost(FIELDOUT,infohout,RC=STATUS)
      _VERIFY(STATUS)
      call ESMF_InfoGet(infohin,size=NF,RC=STATUS)
      _VERIFY(STATUS)
      do I=1,NF
         call ESMF_InfoGet(infohin, idx=I,ikey=NAME, RC=status)
         _VERIFY(STATUS)
         NAME = trim(NAME)
         if(NAME(1:10)=='FriendlyTo') then
            call ESMF_InfoGet(infohin,key=NAME,value=VALUE, RC=status)
            _VERIFY(STATUS)
            call ESMF_InfoSet(infohout,NAME,VALUE, RC=status)
            _VERIFY(STATUS)
         end if
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_CopyFriendlinessInField
Call graph
mapl_copyfriendlinessinfield calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_copyfriendliness calls mapl_copyfriendlinessinfield, mapl_copyfriendlinessinstate
mapl_copyfriendlinessinstate calls mapl_copyfriendlinessinfield