MAPL_ExtDataPrefetch – MAPL
MAPL_ExtDataPrefetch Subroutine
24 statements
Source File
private subroutine MAPL_ExtDataPrefetch(IOBundles, file_weights, rc)
Arguments
Type Intent Optional Attributes Name
type(IoBundleNGVector), intent(inout), target :: IOBundles
logical, intent(in) :: file_weights
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataPrefetch(IOBundles,file_weights,rc)
     type(IOBundleNGVector), target, intent(inout) :: IOBundles
     logical, intent(in) :: file_weights
     integer, optional,      intent(out  ) :: rc
     integer :: n,nfiles,regrid_hints
     type(ExtDataNG_IOBundle), pointer :: io_bundle => null()
     integer :: status
     nfiles = IOBundles%size()
     regrid_hints = 0
     if (file_weights) regrid_hints = IOR(regrid_hints,REGRID_HINT_FILE_WEIGHTS)
     do n = 1, nfiles
        io_bundle => IOBundles%at(n)
        if (io_bundle%on_tiles) then
           call io_bundle%tile_io%request_data_from_file(io_bundle%file_name,io_bundle%time_index,_RC)
        else
           call io_bundle%grid_io%set_param(regrid_hints=regrid_hints)
           call io_bundle%grid_io%request_data_from_file(io_bundle%file_name,io_bundle%time_index,_RC)
        end if
     enddo
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataPrefetch
Call graph
mapl_extdataprefetch calls at, mapl_return, mapl_verify, request_data_from_file, set_param
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
request_data_from_file calls mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldget, mapl_am_i_root, mapl_assert, collective_prefetch_data, mapl_gridget
set_param calls mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
collective_prefetch_data calls mapl_return, mapl_verify, collective_prefetch_data, current
get_error_message calls at, insert
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_throw_exception calls initialize
run_ calls mapl_extdataprefetch