MAPL_GridCompGetFriendlies0 – MAPL
MAPL_GridCompGetFriendlies0 Subroutine
190 statements
Source File
private recursive subroutine MAPL_GridCompGetFriendlies0(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: TO(:)
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   recursive subroutine MAPL_GridCompGetFriendlies0 ( GC, TO, BUNDLE, AddGCPrefix, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      character(len=*),              intent(IN   )  :: TO(:)
      type(ESMF_FieldBundle  ),           intent(INOUT)  :: BUNDLE
      logical, optional,             intent(IN   )  :: AddGCPrefix
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      integer                               :: status
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),        pointer  :: STATE
      type (ESMF_State), pointer                     :: INTERNAL
      type (ESMF_Field)                     :: FIELD, TempField
      character (len=ESMF_MAXSTR), allocatable  :: itemNameList(:)
      type(ESMF_StateItem_Flag),   allocatable  :: itemtypeList(:)
      type(ESMF_FieldBundle)                    :: B
      integer                               :: I, N
      integer                               :: J, NF
      integer, allocatable :: orderlist(:)
      integer :: jj
      character(len=ESMF_MAXSTR)           :: attrName
      character(len=ESMF_MAXSTR), allocatable :: currList(:)
      integer                                 :: natt
      logical                                 :: haveAttr
      logical                                 :: AddPrefix_
      character(len=ESMF_MAXSTR)              :: GC_NAME, fieldname
      type(ESMF_GridComp), pointer :: gridcomp
      type(ESMF_Info) :: infoh
      ! Get my MAPL_Generic state
      !--------------------------
      AddPrefix_ = .false.
      if (present(AddGCPrefix) ) then
         AddPrefix_ = AddGCPrefix
      end if
      call MAPL_InternalStateGet ( GC, STATE, RC=status)
      _VERIFY(status)
      ! Call recursively the children
      !==============================OB
      ! as a consequence of some assuptions in CHEM
      ! we are going to allow recursing ONLY
      ! when addGCPrefix is passed in and it is set to .true.
      ! Physics does not pass this agrument
      if (AddPrefix_ .and. allocated(state%GCnamelist)) then
         do I = 1, size(state%GCnamelist)
            call write_parallel("Executing getFriendlies for " // &
                 trim(state%GCnamelist(I)))
            gridcomp => state%GET_CHILD_GRIDCOMP(I)
            call MAPL_GridCompGetFriendlies( gridcomp , TO, BUNDLE, &
                 AddGCPrefix, RC=status)
            _VERIFY(status)
         end do
      end if
      !    _RETURN(0)
      ! now call itself
      if (.not.associated(state%component_spec%internal%old_var_specs)) then
         _RETURN(ESMF_SUCCESS)
      end if
      INTERNAL => STATE%get_internal_state()
      call ESMF_StateGet(INTERNAL, ITEMCOUNT=N,  RC=status)
      _VERIFY(status)
      allocate(itemNameList(N)     ,STAT=status)
      _VERIFY(status)
      allocate(itemtypeList(N),STAT=status)
      _VERIFY(status)
      call ESMF_StateGet(INTERNAL,ITEMNAMELIST=itemNamelist,ITEMTYPELIST=itemtypeList,RC=status)
      _VERIFY(status)
      attrName = MAPL_StateItemOrderList
      call ESMF_InfoGetFromHost(internal,infoh,RC=STATUS)
      haveAttr = ESMF_InfoIsPresent(infoh,attrName,RC=STATUS)
      _VERIFY(STATUS)
      if (haveAttr) then
         call ESMF_InfoGet(infoh,key=attrName,size=natt,RC=STATUS)
         _VERIFY(STATUS)
      else
         natt = N
      end if
      if (natt == 0) then
         _RETURN(ESMF_SUCCESS)
      endif
      allocate(orderlist(natt), stat=status)
      _VERIFY(status)
      if (haveAttr) then
         allocate(currList(natt), stat=status)
         _VERIFY(status)
         ! get the current list
         call ESMF_InfoGet(infoh,key=attrName,values=currList,rc=status)
         _VERIFY(STATUS)
         orderList = -1 ! not found
         do i = 1, natt
            ! search loop
            do jj = 1, N
               if (itemNameList(jj) == currList(i)) then
                  orderList(i) = jj
                  exit
               end if
            end do
         end do
         deallocate(currList)
      else
         do i = 1, natt
            orderList(i) = i
         end do
      end if
      do JJ = 1, natt
         I = ORDERLIST(JJ)
         !    do I=1,N
         if(itemtypeList(I)==ESMF_STATEITEM_FIELD) then
            call ESMF_StateGet(INTERNAL,itemNameList(I),FIELD,RC=status)
            _VERIFY(status)
            call Am_I_Friendly_ ( FIELD, TO, RC=status )
            if(status==ESMF_SUCCESS) then
               if (AddPrefix_) then
                  call ESMF_GridCompGet(GC, NAME=GC_NAME, RC=status)
                  _VERIFY(status)
                  if (scan(itemNameList(I),"::")==0) then
                     TempField = MAPL_FieldCreate(FIELD, name=(trim(GC_NAME)//'::'//trim(itemNameList(I))), RC=status)
                     _VERIFY(status)
                     call PutFieldInBundle__(BUNDLE, TempField, RC=status)
                     _VERIFY(status)
                  else
                     call PutFieldInBundle__(BUNDLE, FIELD, RC=status )
                     _VERIFY(status)
                  end if
               else
                  call PutFieldInBundle__(BUNDLE, FIELD, RC=status )
                  _VERIFY(status)
               end if ! (AddPrefix_)
            end if
         else if(itemtypeList(I)==ESMF_STATEITEM_FieldBundle) then
            call ESMF_StateGet(INTERNAL,itemNameList(I), B, RC=status)
            _VERIFY(status)
            call ESMF_FieldBundleGet(B,FieldCount=NF, RC=status)
            _VERIFY(status)
            call Am_I_Friendly__ ( B, TO, RC=status )
            if(status==ESMF_SUCCESS) then
               ! if the bundle is "friendly", copy every single field
               DO J=1,NF
                  if (AddPrefix_) then
                     call ESMF_GridCompGet(GC, NAME=GC_NAME, RC=status)
                     _VERIFY(status)
                     call MAPL_FieldBundleGet(B,   J,   FIELD,  RC=status)
                     _VERIFY(status)
                     call ESMF_FieldGet (FIELD, name=fieldname, RC=status)
                     _VERIFY(status)
                     if (scan(fieldname,"::")==0) then
                        TempField = MAPL_FieldCreate(FIELD, name=(trim(GC_NAME)//'::'//trim(fieldname)), RC=status)
                        _VERIFY(status)
                        call PutFieldInBundle__(BUNDLE, TempField, RC=status)
                        _VERIFY(status)
                     else
                        call MAPL_FieldBundleGet(B,   J,   FIELD,  RC=status)
                        _VERIFY(status)
                        call PutFieldInBundle__(BUNDLE, FIELD, RC=status )
                        _VERIFY(status)
                     end if
                  else
                     call MAPL_FieldBundleGet(B,   J,   FIELD,  RC=status)
                     _VERIFY(status)
                     call PutFieldInBundle__ (BUNDLE, FIELD, RC=status )
                     _VERIFY(status)
                  end if ! (AddPrefix_)
               END DO
            else
               ! check the fields for "friendliness"
               DO J=1,NF
                  if (AddPrefix_) then
                     call ESMF_GridCompGet(GC, NAME=GC_NAME, RC=status)
                     _VERIFY(status)
                     call MAPL_FieldBundleGet(B,   J,   FIELD,  RC=status)
                     _VERIFY(status)
                     call ESMF_FieldGet (FIELD, name=fieldname, RC=status)
                     _VERIFY(status)
                     if (scan(fieldname,"::")==0) then
                        TempField = MAPL_FieldCreate(FIELD, name=(trim(GC_NAME)//'::'//trim(fieldname)), RC=status)
                        _VERIFY(status)
                        call PutFieldInBundle__(BUNDLE, TempField, RC=status)
                        _VERIFY(status)
                     else
                        call MAPL_FieldBundleGet(B,   J,   FIELD,  RC=status)
                        _VERIFY(status)
                        call Am_I_Friendly_ ( FIELD, TO, RC=status )
                        if(status==ESMF_SUCCESS) then
                           call PutFieldInBundle__  (BUNDLE, FIELD, RC=status )
                           _VERIFY(status)
                        end if
                     end if
                  else
                     call MAPL_FieldBundleGet(B,   J,   FIELD,  RC=status)
                     _VERIFY(status)
                     call Am_I_Friendly_ ( FIELD, TO, RC=status )
                     if(status==ESMF_SUCCESS) then
                        call PutFieldInBundle__  (BUNDLE, FIELD, RC=status )
                        _VERIFY(status)
                     END if
                  end if ! (AddPrefix_)
               END DO
            end if
         end if
      end do
      deallocate(orderlist, stat=status)
      _VERIFY(status)
      deallocate(itemNameList     ,STAT=status)
      _VERIFY(status)
      deallocate(itemtypeList,STAT=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GridCompGetFriendlies0
Call graph
mapl_gridcompgetfriendlies0 calls ESMF_GridCompGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, esmf_fieldbundleget, esmf_fieldget, esmf_stateget, mapl_fieldbundleget, mapl_fieldcreate, mapl_gridcompgetfriendlies, write_parallel, am_i_friendly_, am_i_friendly__, get_child_gridcomp, get_internal_state, mapl_internalstateget, mapl_return, mapl_verify, putfieldinbundle__
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies3
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0