MAPL_GeomGetCoords – MAPL
MAPL_GeomGetCoords Module Subroutine
43 statements
Source File
module subroutine MAPL_GeomGetCoords(geom, longitudes, latitudes, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom
real(kind=ESMF_KIND_R8), pointer :: longitudes(:)
real(kind=ESMF_KIND_R8), pointer :: latitudes(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   module subroutine MAPL_GeomGetCoords(geom, longitudes, latitudes, rc)
      type(ESMF_Geom), intent(in) :: geom
      real(kind=ESMF_KIND_R8), pointer :: longitudes(:)
      real(kind=ESMF_KIND_R8), pointer :: latitudes(:)
      integer, optional, intent(out) :: rc
      type(ESMF_GeomType_Flag) :: geomtype
      type(ESMF_Grid) :: grid
      type(ESMF_LocStream) :: locstream
      integer :: status
      call ESMF_GeomGet(geom, geomtype=geomtype, _RC)
      if (geomtype == ESMF_GEOMTYPE_GRID) then
         call ESMF_GeomGet(geom, grid=grid, _RC)
         call GridGetCoords(grid, longitudes, latitudes, _RC)
      else if (geomtype == ESMF_GEOMTYPE_LOCSTREAM) then
         call ESMF_GeomGet(geom, locstream=locstream, _RC)
         call get_locstream_coords(locstream, longitudes, latitudes, _RC)
      else if (any([geomtype==ESMF_GEOMTYPE_MESH, geomtype==ESMF_GEOMTYPE_XGRID])) then
         _FAIL("Unsupported geom type.")
      else
         _FAIL("Illeggal geom type.")
      end if
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine get_locstream_coords(locstream, longitudes, latitudes, rc)
         type(ESMF_LocStream), intent(in) :: locstream
         real(kind=ESMF_KIND_R8), pointer :: longitudes(:)
         real(kind=ESMF_KIND_R8), pointer :: latitudes(:)
         integer, optional, intent(out) :: rc
         integer :: status
         call ESMF_LocStreamGetKey(locstream, keyName='ESMF:Lon', farray=longitudes, _RC)
         call ESMF_LocStreamGetKey(locstream, keyName='ESMF:Lat', farray=latitudes, _RC)
         _RETURN(ESMF_SUCCESS)
      end subroutine get_locstream_coords
   end subroutine MAPL_GeomGetCoords
Call graph
mapl_geomgetcoords calls ESMF_GeomGet, ESMF_LocStreamGetKey, gridgetcoords, mapl_assert, mapl_return, mapl_verify, mapl_geomgetcoords
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
grid_get_centers calls grid_get_centers, gridgetcoords, mapl_return, mapl_verify
grid_get_coords_1d calls grid_get_coords_1d, gridgetcoords, mapl_return, mapl_verify
grid_get_coords_2d calls grid_get_coords_2d, mapl_return, mapl_verify, ESMF_GridGetCoord
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_ns_basis calls mapl_geomgetcoords, new_ns_basis
ns_vectorbasis calls new_ns_basis