MAPL_DecomposeDim – MAPL
MAPL_DecomposeDim Module Subroutine
76 statements
Source File
pure module subroutine MAPL_DecomposeDim(dim_world, dim, NDEs, unusable, symmetric, min_DE_extent) Interface →
Uses
mapl_KeywordEnforcerMod
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dim_world
integer, intent(out) :: dim(0:NDEs-1)
integer, intent(in) :: NDEs
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: symmetric
integer, intent(in), optional :: min_DE_extent
Called by
Source Code
  pure module subroutine MAPL_DecomposeDim ( dim_world,dim,NDEs, unusable, symmetric, min_DE_extent )
    use MAPL_KeywordEnforcerMod
    integer, intent(in) :: dim_world, NDEs
    integer, intent(out) :: dim(0:NDEs-1)
    class (KeywordEnforcer), optional, intent(in) :: unusable
    logical, intent(in), optional :: symmetric
    integer, optional, intent(in) :: min_DE_extent
    integer    im,rm
    logical :: do_symmetric
    integer :: is,ie,isg,ieg
    integer :: ndiv,ndivs,imax,ndmax,ndmirror,n
    integer :: ibegin(0:NDEs-1)
    integer :: iend(0:NDEs-1)
    logical :: symmetrize
    integer :: NDEs_used
    if (present(symmetric)) then
       do_symmetric=symmetric
    else
       do_symmetric=.false.
    end if
    if (present(min_DE_extent)) then
       NDEs_used = min(NDEs, dim_world / min_DE_extent)
    else
       NDEs_used = NDEs
    end if
    if (do_symmetric) then
       isg = 1
       ieg = dim_world
       ndivs = NDEs_used
       is = isg
       n = 0
       do ndiv=0,ndivs-1
          !modified for mirror-symmetry
          !original line
          !                 ie = is + CEILING( real(ieg-is+1)/(ndivs-ndiv) ) - 1
          !problem of dividing nx points into n domains maintaining symmetry
          !i.e nx=18 n=4 4554 and 5445 are solutions but 4455 is not.
          !this will always work for nx even n even or odd
          !this will always work for nx odd, n odd
          !this will never  work for nx odd, n even: for this case we supersede the mirror calculation
          !                 symmetrize = .NOT. ( mod(ndivs,2).EQ.0 .AND. mod(ieg-isg+1,2).EQ.1 )
          !nx even n odd fails if n>nx/2
          symmetrize = ( even(ndivs) .AND. even(ieg-isg+1) ) .OR. &
               (  odd(ndivs) .AND.  odd(ieg-isg+1) ) .OR. &
               (  odd(ndivs) .AND. even(ieg-isg+1) .AND. ndivs.LT.(ieg-isg+1)/2 )
          !mirror domains are stored in the list and retrieved if required.
          if( ndiv.EQ.0 )then
             !initialize max points and max domains
             imax = ieg
             ndmax = ndivs
          end if
          !do bottom half of decomposition, going over the midpoint for odd ndivs
          if( ndiv.LT.(ndivs-1)/2+1 )then
             !domain is sized by dividing remaining points by remaining domains
             ie = is + CEILING( REAL(imax-is+1)/(ndmax-ndiv) ) - 1
             ndmirror = (ndivs-1) - ndiv !mirror domain
             if( ndmirror.GT.ndiv .AND. symmetrize )then !only for domains over the midpoint
                !mirror extents, the max(,) is to eliminate overlaps
                ibegin(ndmirror) = max( isg+ieg-ie, ie+1 )
                iend(ndmirror)   = max( isg+ieg-is, ie+1 )
                imax = ibegin(ndmirror) - 1
                ndmax = ndmax - 1
             end if
          else
             if( symmetrize )then
                !do top half of decomposition by retrieving saved values
                is = ibegin(ndiv)
                ie = iend(ndiv)
             else
                ie = is + CEILING( REAL(imax-is+1)/(ndmax-ndiv) ) - 1
             end if
          end if
          dim(ndiv) = ie-is+1
          is = ie + 1
       end do
    else
       im = dim_world/NDEs_used
       rm = dim_world-NDEs_used*im
       do n = 0,NDEs_used-1
          dim(n) = im
          if( n.le.rm-1 ) dim(n) = im+1
       enddo
    end if
    dim(NDEs_used:) = 0
  contains
    pure logical function even(n)
      integer, intent(in) :: n
      even = mod(n,2).EQ.0
    end function even
    pure logical function odd(n)
      integer, intent(in) :: n
      odd = mod(n,2).EQ.1
    end function odd
  end subroutine MAPL_DecomposeDim
Call graph
mapl_decomposedim calls mapl_decomposedim
generate_newnxy calls mapl_decomposedim
initialize_from_file_metadata calls mapl_decomposedim, check_and_fill_consistency
make_distribution calls mapl_decomposedim, make_distribution
mapl_latlongridcreate calls mapl_decomposedim, mapl_latlongridcreate
new_latlondecomposition_topo calls mapl_decomposedim, new_latlondecomposition_topo
test_mapl_decomposedim_even calls mapl_decomposedim
test_mapl_decomposedim_minde calls mapl_decomposedim
test_mapl_decomposedim_uneven calls mapl_decomposedim
check_and_fill_consistency calls generate_newnxy
latlondecomposition calls new_latlondecomposition_topo
initialize_from_config_with_prefix calls check_and_fill_consistency
latlongridfactory_from_parameters calls check_and_fill_consistency
swathgridfactory_from_parameters calls check_and_fill_consistency