MAPL_VarWriteNCpar_R4_2d – MAPL
MAPL_VarWriteNCpar_R4_2d Subroutine
165 statements
Source File
private subroutine MAPL_VarWriteNCpar_R4_2d(formatter, name, A, ARRDES, lev, offset2, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(in), optional :: lev
integer, intent(in), optional :: offset2
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_VarWriteNCpar_R4_2d(formatter, name, A, ARRDES, lev, offset2, oClients, RC)
    type(Netcdf4_Fileformatter)           , intent(IN   ) :: formatter
    character(len=*)            , intent(IN   ) :: name
    real(kind=ESMF_KIND_R4)     , intent(IN   ) :: A(:,:)
    type(ArrDescr),    optional , intent(INOUT) :: ARRDES
    integer,           optional , intent(IN   ) :: lev
    integer,           optional , intent(IN   ) :: offset2
    type (ClientManager), optional, intent(inout) :: oClients
    integer,           optional , intent(  OUT) :: RC
! Local variables
    real(kind=ESMF_KIND_R4),  allocatable :: VAR(:,:)
    integer                               :: IM_WORLD
    integer                               :: status
    real(kind=ESMF_KIND_R4),  allocatable :: recvbuf(:)
    integer                               :: I,J,N,K,L,myrow,myiorank,ndes_x
    integer                               :: start(4), cnt(4)
    integer                               :: jsize, jprev, num_io_rows
    integer, allocatable                  :: recvcounts(:), displs(:)
    type (ArrayReference) :: ref
    integer ::  i1, j1, in, jn,  global_dim(3), jp1
    integer :: start_bound,end_bound,counts_per_writer
    logical :: in_bounds
    real(kind=ESMF_KIND_R4), pointer :: a_temp(:,:)
    character(len=:), allocatable :: writer_filename
    if (present(arrdes)) then
       if(present(oClients)) then
          if (arrdes%split_checkpoint) then
             call MAPL_GridGet(arrdes%grid,globalCellCountPerDim=global_dim,rc=status)
              _VERIFY(status)
             call MAPL_Grid_interior(arrdes%grid,i1,in,j1,jn)
             _ASSERT( i1 == arrdes%I1(arrdes%NX0), "interior starting i1 not match")
             _ASSERT( j1 == arrdes%j1(arrdes%NY0), "interior starting j1 not match")
             _ASSERT( size(a,1) == in-i1+1, "size not match")
             _ASSERT( size(a,2) == jn-j1+1, "size not match")
             counts_per_writer = global_dim(2)/arrdes%num_writers
             allocate(a_temp(0,0))
             do i=1,arrdes%num_writers
                start_bound = (i-1)*counts_per_writer+1
                end_bound   = i*counts_per_writer
                in_bounds = (j1 .ge. start_bound) .and. (jn .le. end_bound)
                if (in_bounds) then
                   ref = ArrayReference(A)
                   jp1 = j1 - (i-1)*counts_per_writer
                else
                   ref = ArrayReference(a_temp)
                   jp1 = 1
                end if
                writer_filename = get_fname_by_rank(trim(arrdes%filename),i-1)
                call oClients%collective_stage_data(arrdes%collection_id(i),trim(writer_filename),trim(name), &
                            ref,start=[i1,jp1], &
                            global_start=[1,1], global_count=[global_dim(1),global_dim(2)/arrdes%num_writers])
             enddo
             _RETURN(_SUCCESS)
          else
             call MAPL_GridGet(arrdes%grid,globalCellCountPerDim=global_dim,rc=status)
              _VERIFY(status)
             call MAPL_Grid_interior(arrdes%grid,i1,in,j1,jn)
             _ASSERT( i1 == arrdes%I1(arrdes%NX0), "interior starting i1 not match")
             _ASSERT( j1 == arrdes%j1(arrdes%NY0), "interior starting j1 not match")
             ref = ArrayReference(A)
             _ASSERT( size(a,1) == in-i1+1, "size not match")
             _ASSERT( size(a,2) == jn-j1+1, "size not match")
             call oClients%collective_stage_data(arrdes%collection_id(1),trim(arrdes%filename),trim(name), &
                         ref,start=[i1,j1], &
                         global_start=[1,1], global_count=[global_dim(1),global_dim(2)])
             _RETURN(_SUCCESS)
          end if
       end if
    endif
    if (present(arrdes)) then
       IM_WORLD = arrdes%im_world
       ndes_x = size(arrdes%in)
       call mpi_comm_rank(arrdes%ycomm,myrow,status)
       _VERIFY(STATUS)
       call mpi_comm_rank(arrdes%iogathercomm,myiorank,status)
       _VERIFY(STATUS)
       call mpi_comm_size(arrdes%iogathercomm,num_io_rows,status)
       _VERIFY(STATUS)
       num_io_rows=num_io_rows/ndes_x
       allocate (recvcounts(ndes_x*num_io_rows), displs(ndes_x*num_io_rows), stat=status)
       _VERIFY(STATUS)
       if(myiorank==0) then
          do j=1,num_io_rows
             jsize = arrdes%jn(myrow+j) - arrdes%j1(myrow+j) + 1
             recvcounts((j-1)*ndes_x+1:(j-1)*ndes_x+ndes_x) = ( arrdes%IN -  arrdes%I1 + 1) * jsize
          enddo
          displs(1) = 0
          do i=2,ndes_x*num_io_rows
             displs(i) = displs(i-1) + recvcounts(i-1)
          enddo
          jsize = 0
          do j=1,num_io_rows
             jsize=jsize + (arrdes%jn(myrow+j) - arrdes%j1(myrow+j) + 1)
          enddo
          allocate(VAR(IM_WORLD,jsize), stat=status)
          _VERIFY(STATUS)
          allocate(recvbuf(IM_WORLD*jsize), stat=status)
          _VERIFY(STATUS)
       end if
       if(myiorank/=0) then
          allocate(recvbuf(0), stat=status)
          _VERIFY(STATUS)
       endif
       call mpi_gatherv( a, size(a), MPI_REAL, recvbuf, recvcounts, displs, MPI_REAL, &
                      0, arrdes%iogathercomm, status )
       _VERIFY(STATUS)
       if(myiorank==0) then
          jprev = 0
          k=1
          do l=1,num_io_rows
            jsize = arrdes%jn(myrow+l) - arrdes%j1(myrow+l) + 1
            do n=1,ndes_x
              do j=1,jsize
                do i=arrdes%i1(n),arrdes%in(n)
                  VAR(i,jprev+j) = recvbuf(k)
                  k=k+1
                end do
              end do
            end do
            jprev = jprev + jsize
          end do
          jsize=jprev
          start(1) = 1
          start(2) = arrdes%j1(myrow+1)
          start(3) = 1
          if (present(lev)) start(3)=lev
          start(4) = 1
          if (present(offset2)) start(4) = offset2
          cnt(1) = IM_WORLD
          cnt(2) = jsize
          cnt(3) = 1
          cnt(4) = 1
          if(arrdes%split_checkpoint) then
             start(2) = 1
          endif
          call formatter%put_var(trim(name),VAR,start=start,count=cnt,rc=status)
          if(status /= NF90_NOERR) then
             print*,'Error writing variable ',status
             print*, NF90_STRERROR(status)
             _VERIFY(STATUS)
          endif
          deallocate(VAR, stat=status)
          _VERIFY(STATUS)
       endif ! myiorank
       deallocate(recvbuf, stat=status)
       _VERIFY(STATUS)
       deallocate (recvcounts, displs, stat=status)
       _VERIFY(STATUS)
    else
          start(1) = 1
          start(2) = 1
          start(3) = 1
          if (present(lev)) start(3)=lev
          start(4) = 1
          if (present(offset2)) start(4) = offset2
          cnt(1) = size(a,1)
          cnt(2) = size(a,2)
          cnt(3) = 1
          cnt(4) = 1
          call formatter%put_var(trim(name),A,start=start,count=cnt,rc=status)
          if(status /= NF90_NOERR) then
             print*,'Error writing variable ',status
             print*, NF90_STRERROR(status)
             _VERIFY(STATUS)
          endif
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarWriteNCpar_R4_2d
Call graph
mapl_varwritencpar_r4_2d calls mapl_assert, mapl_grid_interior, mpi_comm_rank, mpi_comm_size, mpi_gatherv, nf90_strerror, put_var, collective_stage_data, get_fname_by_rank, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_grid_interior calls mapl_grid_interior
collective_stage_data calls mapl_return, mapl_verify, collective_stage_data, current
get_fname_by_rank calls i_to_string
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_varwrite calls mapl_varwritencpar_r4_2d, mapl_varwritencpar_r4_3d, mapl_varwritencpar_r4_4d, mapl_varwritencpar_r8_3d, mapl_varwritencpar_r8_4d
mapl_fieldwritencpar calls mapl_varwrite
mapl_varwritencpar_r4_3d calls mapl_varwrite
mapl_varwritencpar_r4_4d calls mapl_varwrite
mapl_varwritencpar_r8_3d calls mapl_varwrite
mapl_varwritencpar_r8_4d calls mapl_varwrite
mapl_bundlewritencpar calls mapl_fieldwritencpar
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar