MAPL_GridCompSetVerticalGrid – MAPL
MAPL_GridCompSetVerticalGrid Subroutine
12 statements
Source File
public subroutine MAPL_GridCompSetVerticalGrid(gridcomp, vertical_grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
class(VerticalGrid), intent(in) :: vertical_grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GridCompSetVerticalGrid(gridcomp, vertical_grid, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      class(VerticalGrid), intent(in) :: vertical_grid
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      call outer_meta%set_vertical_grid(vertical_grid)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GridCompSetVerticalGrid
Call graph
mapl_gridcompsetverticalgrid calls mapl_gridcompgetoutermeta, set_vertical_grid, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setup calls mapl_gridcompsetverticalgrid
test_full_run_sequence calls mapl_gridcompsetverticalgrid
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup