MAPL_HConfigMatch – MAPL
MAPL_HConfigMatch Function
224 statements
Source File
public function MAPL_HConfigMatch(a, b, rc) result(match)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: a
type(ESMF_HConfig), intent(in) :: b
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function MAPL_HConfigMatch(a, b, rc) result(match)
      type(ESMF_HConfig), intent(in) :: a, b
      integer, optional, intent(out) :: rc
      integer :: status
      ! Workaround for GFortran recursion bug
      integer, parameter :: MAX_DEPTH = 10
      type(ESMF_HConfig) :: a_hconfigs(MAX_DEPTH)
      type(ESMF_HConfig) :: b_hconfigs(MAX_DEPTH)
      integer :: depth = 0
      match = recursive_HConfigMatch(a, b, _RC)
      _RETURN(_SUCCESS)
   contains
      recursive logical function recursive_HConfigMatch(a, b, rc) result(match)
         type(ESMF_HConfig), intent(in) :: a, b
         integer, optional, intent(out) :: rc
         integer :: status
         character(:), allocatable :: a_type, b_type
         match = .false. ! unless
         depth = depth + 1
         _ASSERT(depth <= MAX_DEPTH, "Recursion limit execeeded in MAPL_HConfigMatch()")
         a_type = get_hconfig_type(a, _RC)
         b_type = get_hconfig_type(b, _RC)
         if (a_type /= b_type) then
            _RETURN(_SUCCESS)
         end if
         if (a_type == 'MAPPING') then
            match = MAPL_HConfigMatchMapping(a, b, _RC)
         else if (a_type == 'SEQUENCE') then
            match = MAPL_HConfigMatchSequence(a, b, _RC)
         else if (a_type == 'SCALAR') then
            match = MAPL_HConfigMatchScalar(a, b, _RC)
         else
            _FAIL('unsupported HConfig type.')
         end if
         depth = depth - 1
         _RETURN(_SUCCESS)
      end function recursive_HConfigMatch
      function get_hconfig_type(hconfig, rc) result(hconfig_type)
         type(ESMF_HConfig), intent(in) :: hconfig
         integer, optional, intent(out) :: rc
         integer :: status
         character(:), allocatable :: hconfig_type
         logical :: is_scalar
         logical :: is_sequence
         logical :: is_mapping
         is_scalar = ESMF_HConfigIsScalar(hconfig, _RC)
         if (is_scalar) then
            hconfig_type = 'SCALAR'
            _RETURN(_SUCCESS)
         end if
         is_sequence = ESMF_HConfigIsSequence(hconfig, _RC)
         if (is_sequence) then
            hconfig_type = 'SEQUENCE'
            _RETURN(_SUCCESS)
         end if
         is_mapping = ESMF_HConfigIsMap(hconfig, _RC)
         if (is_mapping) then
            hconfig_type = 'MAPPING'
            _RETURN(_SUCCESS)
         end if
         hconfig_type = 'UNKNOWN'
         _FAIL('unsupported HConfig type.')
         _RETURN(_SUCCESS)
      end function get_hconfig_type
      recursive logical function MAPL_HConfigMatchScalar(a, b, rc) result(match)
         type(ESMF_HConfig), intent(in) :: a, b
         integer, optional, intent(out) :: rc
         integer :: status
         character(:), allocatable :: a_str, b_str
         logical :: a_is, b_is
         logical :: a_as_bool, b_as_bool
         integer(kind=ESMF_KIND_I8) :: a_as_int, b_as_int
         real(kind=ESMF_KIND_R8) :: a_as_float, b_as_float
         match = .false. ! nless
         a_as_bool  = ESMF_HConfigAsLogical(a, asOkay=a_is, _RC)
         b_as_bool  = ESMF_HConfigAsLogical(b, asOkay=b_is, _RC)
         _RETURN_UNLESS(a_is .eqv. b_is)
         if (a_is) then
            match = a_as_bool .eqv. b_as_bool
            _RETURN(_SUCCESS)
         end if
         a_as_int  = ESMF_HConfigAsI8(a, asOkay=a_is, _RC)
         b_as_int  = ESMF_HConfigAsI8(b, asOkay=b_is, _RC)
         _RETURN_UNLESS(a_is .eqv. b_is)
         if (a_is) then
            match = (a_as_int == b_as_int)
            _RETURN(_SUCCESS)
         end if
         a_as_float  = ESMF_HConfigAsR8(a, asOkay=a_is, _RC)
         b_as_float  = ESMF_HConfigAsR8(b, asOkay=b_is, _RC)
         _RETURN_UNLESS(a_is .eqv. b_is)
         if (a_is) then
            match = (a_as_float == b_as_float)
            _RETURN(_SUCCESS)
         end if
         ! Otherwise they are strings ...
         a_str = ESMF_HConfigAsString(a, _RC)
         b_str = ESMF_HConfigAsString(b, _RC)
         match = (a_str == b_str)
         _RETURN(_SUCCESS)
      end function MAPL_HConfigMatchScalar
      recursive logical function MAPL_HConfigMatchSequence(a, b, rc) result(match)
         type(ESMF_HConfig), intent(in) :: a, b
         integer, optional, intent(out) :: rc
         integer :: status
         type(ESMF_HConfig) :: a_val_hconfig, b_val_hconfig
         integer :: i
         integer :: a_size, b_size
         match = .false. ! unless
         a_size = ESMF_HConfigGetSize(a, _RC)
         b_size = ESMF_HConfigGetSize(b, _RC)
         _RETURN_UNLESS(a_size == b_size)
         do i = 1, a_size
            a_hconfigs(depth) = ESMF_HConfigCreateAt(a, index=i, _RC)
            b_hconfigs(depth) = ESMF_HConfigCreateAt(b, index=i, _RC)
            match = recursive_HConfigMatch(a_hconfigs(depth), b_hconfigs(depth), _RC)
            call ESMF_HConfigDestroy(a_hconfigs(depth), _RC)
            call ESMF_HConfigDestroy(b_hconfigs(depth), _RC)
            _RETURN_UNLESS(match)
         end do
         match = .true.
         _RETURN(_SUCCESS)
      end function MAPL_HConfigMatchSequence
      recursive logical function MAPL_HConfigMatchMapping(a, b, rc) result(match)
         type(ESMF_HConfig), intent(in) :: a, b
         integer, optional, intent(out) :: rc
         integer :: status
         type(ESMF_HConfig) :: a_val_hconfig, b_val_hconfig
         character(:), allocatable :: key
         type(ESMF_HConfigIter) :: iter, iter_begin, iter_end
         integer :: a_size, b_size
         match = .false. ! unless
         a_size = ESMF_HConfigGetSize(a, _RC)
         b_size = ESMF_HConfigGetSize(b, _RC)
         _RETURN_UNLESS(a_size == b_size)
         iter_begin = ESMF_HConfigIterBegin(a, _RC)
         iter_end = ESMF_HConfigIterEnd(a, _RC)
         iter = iter_begin
         do while (ESMF_HConfigIterLoop(iter, iter_begin, iter_end, rc=status))
            _VERIFY(status)
            key = ESMF_HConfigAsStringMapKey(iter, _RC)
            match = ESMF_HConfigIsDefined(b, keystring=key, _RC)
            _RETURN_UNLESS(match)
            a_hconfigs(depth) = ESMF_HConfigCreateAt(a, keyString=key, _RC)
            b_hconfigs(depth) = ESMF_HConfigCreateAt(b, keyString=key, _RC)
            match = recursive_HConfigMatch(a_hconfigs(depth), b_hconfigs(depth), _RC)
            call ESMF_HConfigDestroy(a_hconfigs(depth), _RC)
            call ESMF_HConfigDestroy(b_hconfigs(depth), _RC)
            _RETURN_UNLESS(match)
         end do
         match = .true.
         _RETURN(_SUCCESS)
      end function MAPL_HConfigMatchMapping
   end function MAPL_HConfigMatch
Call graph
mapl_hconfigmatch calls ESMF_HConfigAsStringMapKey, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, esmf_hconfigasi8, esmf_hconfigaslogical, esmf_hconfigasr8, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigisscalar, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_make_child_hconfig calls mapl_hconfigmatch
test_match_bool calls mapl_hconfigmatch
test_match_bool_mismatch calls mapl_hconfigmatch
test_match_bool_str_mismatch calls mapl_hconfigmatch
test_match_int_ignore_sign calls mapl_hconfigmatch
test_match_int_str_mismatch calls mapl_hconfigmatch
test_match_mapping_match calls mapl_hconfigmatch
test_match_mapping_mismatch_keys_1 calls mapl_hconfigmatch
test_match_mapping_mismatch_keys_2 calls mapl_hconfigmatch
test_match_mapping_mismatch_size_1 calls mapl_hconfigmatch
test_match_mapping_mismatch_size_2 calls mapl_hconfigmatch
test_match_mapping_mismatch_values calls mapl_hconfigmatch
test_match_scalar_match calls mapl_hconfigmatch
test_match_scalar_mismatch calls mapl_hconfigmatch
test_match_sequence_match calls mapl_hconfigmatch
test_match_sequence_mismatch_content calls mapl_hconfigmatch
test_match_sequence_mismatch_size calls mapl_hconfigmatch
test_match_type_mismatch calls mapl_hconfigmatch
test_reproducer_from_history calls mapl_hconfigmatch