MAPL_ExtDataDestroyCFIO – MAPL
MAPL_ExtDataDestroyCFIO Subroutine
17 statements
Source File
private subroutine MAPL_ExtDataDestroyCFIO(IOBundles, rc)
Arguments
Type Intent Optional Attributes Name
type(IoBundleNGVector), intent(inout), target :: IOBundles
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataDestroyCFIO(IOBundles,rc)
     type(IOBundleNGVector), target, intent(inout) :: IOBundles
     integer, optional,      intent(out  ) :: rc
     type(IOBundleNGVectorIterator) :: bundle_iter
     type (ExtDataNG_IOBundle), pointer :: io_bundle
     integer :: status
     bundle_iter = IOBundles%begin()
     do while (bundle_iter /= IOBundles%end())
        io_bundle => bundle_iter%of()
        call io_bundle%clean(_RC)
        call bundle_iter%next
     enddo
     call IOBundles%clear()
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataDestroyCFIO
Call graph
mapl_extdatadestroycfio calls of, clean, mapl_return, mapl_verify, vector_begin, vector_clear, vector_iter_next
clean calls mapl_return, mapl_verify, esmf_fieldbundledestroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_clear calls vector_downsize
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_ calls mapl_extdatadestroycfio