MAPL_IOCountNonDimVars – MAPL
MAPL_IOCountNonDimVars Subroutine
25 statements
Source File
public subroutine MAPL_IOCountNonDimVars(cf, nvars, rc)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout) :: cf
integer, intent(out) :: nvars
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine MAPL_IOCountNonDimVars(cf,nvars,rc)
  type(FileMetadata), intent(inout) :: cf
  integer, intent(out) :: nvars
  integer, intent(out), optional :: rc
  type(StringVariableMap), pointer :: vars
  type(StringVariableMapIterator) :: iter
  type(StringIntegerMap), pointer :: dims
  integer, pointer :: dimsize => null()
  character(len=:), pointer :: name
  integer :: status
  nvars = 0
  dims => cf%get_dimensions()
  vars => cf%get_variables(_RC)
  iter = vars%ftn_begin()
  do while(iter/=vars%ftn_end())
     call iter%next()
     name =>  iter%first()
     dimsize => dims%at(trim(name))
     if (.not.associated(dimsize)) nvars=nvars+1
     if (associated(dimsize)) nullify(dimsize)
  end do
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_IOCountNonDimVars
Call graph
mapl_iocountnondimvars calls at, get_dimensions, get_variables, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, mapl_return, mapl_verify
get_variables calls mapl_return
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_advpos calls map_s_get_child, to_node
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value