MAPL_LocStreamAttachGrid – MAPL
MAPL_LocStreamAttachGrid Subroutine
41 statements
Source File
private subroutine MAPL_LocStreamAttachGrid(LocStream, Grid, ISMINE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(inout) :: LocStream
type(ESMF_Grid), intent(inout) :: Grid
logical, optional, pointer :: ISMINE(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_LocStreamAttachGrid(LocStream, GRID, ISMINE, RC)
    type(MAPL_LocStream),  intent(INOUT) :: LocStream
    type(ESMF_Grid),       intent(INout) :: Grid
    logical, optional,     pointer       :: ISMINE(:)
    integer, optional,     intent(  OUT) :: RC
! Local variables
    integer                    :: STATUS
    type(MAPL_LocStreamType), pointer :: STREAM
    type(MAPL_Tiling       ), pointer :: TILING
    integer                           :: IM_WORLD, JM_WORLD
    integer                           :: I1, IN, J1, JN
    integer                           :: gridRank
    integer                           :: DIMS(ESMF_MAXGRIDDIM)
! Begin
!------
  _UNUSED_DUMMY(ISMINE)
! Make sure Location stream has been created
!-------------------------------------------
    _ASSERT(associated(LocStream%Ptr),'needs informative message')
! Alias to the pointer
!---------------------
    STREAM => LocStream%Ptr
! Location stream must have some allowed grids
!---------------------------------------------
    _ASSERT(STREAM%N_GRIDS>0,'needs informative message')
! Find the given grid among the allowed grids
!--------------------------------------------
    STREAM%CURRENT_TILING = GRIDINDEX(STREAM, GRID, RC=STATUS)
    _VERIFY(STATUS)
    TILING => STREAM%TILING(STREAM%CURRENT_TILING)
!C    STREAM%GLOBAL_INDEXLOCATION => TILING%GLOBAL_INDEXLOCATION
! Put associated ESMF_LogRectGrid in stream and query grid info
!--------------------------------------------------------------
    STREAM%GRID = GRID
! Verify that the grid is the right size
!---------------------------------------
    call ESMF_GridGet(GRID, dimCount=gridRank, rc=STATUS)
    _VERIFY(STATUS)
    call MAPL_GridGet(GRID, globalCellCountPerDim=DIMS, RC=STATUS)
    _VERIFY(STATUS)
    IM_WORLD = DIMS(1)
    JM_WORLD = DIMS(2)
    _ASSERT(IM_WORLD==TILING%IM,'needs informative message')
    if (JM_WORLD /= TILING%JM) then
       print *,'error tiling jm/jm ',jm_world, tiling%jm
       _RETURN(_FAILURE)
    end if
! Find out which tiles are in local PE
!-------------------------------------
    call MAPL_GRID_INTERIOR  (GRID, I1,IN,J1,JN)
! Local location uses local indexing
!-----------------------------------
    STREAM%LOCAL_IndexLocation(:)%I = STREAM%LOCAL_IndexLocation(:)%I-I1+1
    STREAM%LOCAL_IndexLocation(:)%J = STREAM%LOCAL_IndexLocation(:)%J-J1+1
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_LocStreamAttachGrid
Call graph
mapl_locstreamattachgrid calls ESMF_GridGet, mapl_assert, mapl_grid_interior, gridindex, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_grid_interior calls mapl_grid_interior, ESMF_GridGet, mapl_verify, ESMF_DistGridGet, mapl_distgridget, ESMF_DELayoutGet
gridindex calls ESMF_GridGet, mapl_assert, mapl_return, mapl_verify
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
mapl_locstreamcreatefromfile calls mapl_locstreamattachgrid
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize calls mapl_locstreamcreate
initialize_ calls mapl_locstreamcreate