MAPL_SimpleBundleCreateEmpty – MAPL
MAPL_SimpleBundleCreateEmpty Function
68 statements
Source File
private function MAPL_SimpleBundleCreateEmpty(grid, rc, Levs, LevUnits, ptop, delp, name) result(self)
Given inputs, create a SimpleBundle.
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(out), optional :: rc
real(kind=ESMF_KIND_R4), intent(in), optional :: Levs(:)
Vertical coordinates Constant levels
character(len=*), intent(in), optional :: LevUnits
Level units
real(kind=ESMF_KIND_R4), intent(in), optional :: ptop
top pressure (Pa) Lagrangian Control Volume Info
real(kind=ESMF_KIND_R4), intent(in), optional, pointer :: delp(:,:,:)
layer thickness (Pa)
character(len=*), intent(in), optional :: name
name
Return Value type(MAPL_SimpleBundle)
Simple Bundle !rename to simpleBundle
Calls
Called by
Source Code
  Function MAPL_SimpleBundleCreateEmpty ( grid, rc, &
                                          Levs, LevUnits, &
                                          ptop, delp,     &
                                          name) result (self)
    type(MAPL_SimpleBundle)                        :: self          !! Simple Bundle !rename to simpleBundle
    type(ESMF_Grid),                intent(in)     :: grid
    integer, OPTIONAL,              intent(out)    :: rc
    real(ESMF_KIND_R4), OPTIONAL,   intent(in)     :: Levs(:)       !! Vertical coordinates
                                                                    !! Constant levels
    character(len=*), OPTIONAL,     intent(in)     :: LevUnits      !! Level units
    real(ESMF_KIND_R4), OPTIONAL,   intent(in)     :: ptop          !! top pressure (Pa)
                                                                    !! Lagrangian Control Volume Info
    real(ESMF_KIND_R4), OPTIONAL, pointer, &
                                    intent(in)     :: delp(:,:,:)   !! layer thickness (Pa)
    character(len=*), OPTIONAL,     intent(in)     :: name          !! name
!
    character(len=ESMF_MAXSTR) :: bundleName
    integer :: im, jm, km, dims(3), i
    character(len=ESMF_MAXSTR) :: message
    real(ESMF_KIND_R8), pointer :: LonsRad(:,:), LatsRad(:,:)
    __Iam__('MAPL_SimpleBundleCreateEmpty')
!                           ------
    _UNUSED_DUMMY(Iam)
    self%Bundle => null()
!   Name the SimpleBundle
    if (present(name)) then
       if (len_trim(name) > ESMF_MAXSTR) then
           message = 'string "'//trim(name)//'" is too long to be used '// &
                     'as a Simple Bundle name'
           __raise__(MAPL_RC_ERROR, message)
       end if
       self%name = trim(name)
    else
       self%name = bundleName
    end if
!                             --------------------
!                             Coordinate variables
!                             --------------------
    self%grid = grid
    call MAPL_GridGet(self%Grid, localCellCountPerDim = dims, _RC)
    im = dims(1);  jm = dims(2);  km = dims(3)
    allocate(self%coords%Lons(im,jm), self%coords%Lats(im,jm), self%coords%Levs(km), __STAT__)
!   Retrieve the lat/lon from Grid and convert to degrees
!   -----------------------------------------------------
   call ESMF_GridGetCoord (self%Grid, coordDim=1, localDE=0, &
                           staggerloc=ESMF_STAGGERLOC_CENTER, &
                           farrayPtr=LonsRad, _RC)
   call ESMF_GridGetCoord (self%Grid, coordDim=2, localDE=0, &
                           staggerloc=ESMF_STAGGERLOC_CENTER, &
                           farrayPtr=LatsRad, _RC)
   self%coords%Lons(:,:) = ( 180. / MAPL_PI) * LonsRad(:,:)
   self%coords%Lats(:,:) = ( 180. / MAPL_PI) * LatsRad(:,:)
!  1-D Levels
!  ----------
   if ( present(Levs) ) then
      if ( size(Levs) == km ) then
         self%coords%Levs(:) = Levs(:)
      else
         _FAIL('Levs different than Levs from ESMF_Grid')
      end if
   else
      self%coords%Levs(:) = [(i, i = 1, km)]
   end if
   if ( present(LevUnits) ) then
      self%coords%LevUnits = LevUnits
   else
      self%coords%LevUnits = '1'
   end if
!  Optional Lagrangian Control Volume info
!  ---------------------------------------
   if ( present(ptop) ) self%coords%lcv%ptop = ptop
   if ( present(delp) ) then ! User specied
!ALT      self%coords%lcv%delp = delp
      self%coords%lcv%delp => delp
   else ! Look inside bundle for delp or DELP
      self%coords%lcv%delp => NULL()
   end if
   _RETURN(_SUCCESS)
  end Function MAPL_SimpleBundleCreateEmpty
Call graph
mapl_simplebundlecreateempty calls ESMF_GridGetCoord, mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
mapl_simplebundlecreate calls mapl_simplebundlecreateempty
mapl_simplebundleread calls mapl_simplebundlecreate