MAPL_FieldEmptySet – MAPL
MAPL_FieldEmptySet Subroutine
38 statements
Source File
private subroutine MAPL_FieldEmptySet(field, geom, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
type(ESMF_Geom), intent(inout) :: geom
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_FieldEmptySet(field, geom, rc)
      type(ESMF_Field), intent(inout) :: field
      type(ESMF_Geom), intent(inout) :: geom
      integer, optional, intent(out) ::rc
      type(ESMF_GeomType_Flag) :: geom_type
      type(ESMF_Grid) :: grid
      type(ESMF_Mesh) :: mesh
      type(ESMF_XGrid) :: xgrid
      type(ESMF_LocStream) :: locstream
      integer :: status
      call ESMF_GeomGet(geom, geomtype=geom_type, _RC)
      if(geom_type == ESMF_GEOMTYPE_GRID) then
         call ESMF_GeomGet(geom, grid=grid, _RC)
         call ESMF_FieldEmptySet(field, grid, _RC)
      else if (geom_type == ESMF_GEOMTYPE_MESH) then
         call ESMF_GeomGet(geom, mesh=mesh, _RC)
         call ESMF_FieldEmptySet(field, mesh, _RC)
      else if (geom_type == ESMF_GEOMTYPE_XGRID) then
         call ESMF_GeomGet(geom, xgrid=xgrid, _RC)
         call ESMF_FieldEmptySet(field, xgrid, _RC)
      else if (geom_type == ESMF_GEOMTYPE_LOCSTREAM) then
         call ESMF_GeomGet(geom, locstream=locstream, _RC)
         call ESMF_FieldEmptySet(field, locstream, _RC)
      else
         _FAIL('Unsupported type of Geom')
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_FieldEmptySet
Call graph
mapl_fieldemptyset calls ESMF_GeomGet, esmf_fieldemptyset, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
create calls mapl_fieldemptyset
connect_to calls create
test_vertical calls create
test_connect_unique_mirror calls connect_to