MAPL_StateAddExportSpec_ – MAPL
MAPL_StateAddExportSpec_ Subroutine
60 statements
Source File
private subroutine MAPL_StateAddExportSpec_(GC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, DATATYPE, NUM_SUBTILES, REFRESH_INTERVAL, AVERAGING_INTERVAL, HALOWIDTH, PRECISION, DEFAULT, UNGRIDDED_DIMS, UNGRIDDED_UNIT, UNGRIDDED_NAME, UNGRIDDED_COORDS, FIELD_TYPE, STAGGERING, ROTATION, DEPENDS_ON, DEPENDS_ON_CHILDREN, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: LONG_NAME
character(len=*), intent(in), optional :: UNITS
integer, intent(in), optional :: DIMS
integer, intent(in), optional :: VLOCATION
integer, intent(in), optional :: DATATYPE
integer, intent(in), optional :: NUM_SUBTILES
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
integer, intent(in), optional :: HALOWIDTH
integer, intent(in), optional :: PRECISION
real, intent(in), optional :: DEFAULT
integer, intent(in), optional :: UNGRIDDED_DIMS(:)
character(len=*), intent(in), optional :: UNGRIDDED_UNIT
character(len=*), intent(in), optional :: UNGRIDDED_NAME
real, intent(in), optional :: UNGRIDDED_COORDS(:)
integer, intent(in), optional :: FIELD_TYPE
integer, intent(in), optional :: STAGGERING
integer, intent(in), optional :: ROTATION
character(len=*), intent(in), optional :: DEPENDS_ON(:)
logical, intent(in), optional :: DEPENDS_ON_CHILDREN
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_StateAddExportSpec_(GC, SHORT_NAME, LONG_NAME,            &
        UNITS, Dims, VLocation,               &
        DATATYPE,NUM_SUBTILES,                &
        REFRESH_INTERVAL, AVERAGING_INTERVAL, &
        HALOWIDTH, PRECISION, DEFAULT, UNGRIDDED_DIMS,   &
        UNGRIDDED_UNIT, UNGRIDDED_NAME,     &
        UNGRIDDED_COORDS,                     &
        FIELD_TYPE, STAGGERING, ROTATION, &
        DEPENDS_ON, DEPENDS_ON_CHILDREN, RC )
      !ARGUMENTS:
      type (ESMF_GridComp)            , intent(INOUT)   :: GC
      character (len=*)               , intent(IN)      :: SHORT_NAME
      character (len=*)  , optional   , intent(IN)      :: LONG_NAME
      character (len=*)  , optional   , intent(IN)      :: UNITS
      integer            , optional   , intent(IN)      :: DIMS
      integer            , optional   , intent(IN)      :: DATATYPE
      integer            , optional   , intent(IN)      :: VLOCATION
      integer            , optional   , intent(IN)      :: NUM_SUBTILES
      integer            , optional   , intent(IN)      :: REFRESH_INTERVAL
      integer            , optional   , intent(IN)      :: AVERAGING_INTERVAL
      integer            , optional   , intent(IN)      :: HALOWIDTH
      integer            , optional   , intent(IN)      :: PRECISION
      real               , optional   , intent(IN)      :: DEFAULT
      integer            , optional   , intent(IN)      :: UNGRIDDED_DIMS(:)
      character (len=*)  , optional   , intent(IN)      :: UNGRIDDED_NAME
      character (len=*)  , optional   , intent(IN)      :: UNGRIDDED_UNIT
      real               , optional   , intent(IN)      :: UNGRIDDED_COORDS(:)
      integer            , optional   , intent(IN)      :: FIELD_TYPE
      integer            , optional   , intent(IN)      :: STAGGERING
      integer            , optional   , intent(IN)      :: ROTATION
      logical            , optional   , intent(IN)      :: DEPENDS_ON_CHILDREN
      character (len=*)  , optional   , intent(IN)      :: DEPENDS_ON(:)
      integer            , optional   , intent(OUT)     :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddExportSpec"
      integer                               :: status
      integer                               :: usable_AI
      integer                               :: usable_RI
      real                                  :: dt
      type (ESMF_Config)                    :: CF
      type (MAPL_MetaComp), pointer         :: STATE
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      CF = STATE%CF
      !  Get the clock increment interval
      call ESMF_ConfigGetAttribute( CF, dt,  Label="RUN_DT:", RC=status)
      _VERIFY(status)
      if (present(REFRESH_INTERVAL)) then
         usable_RI = REFRESH_INTERVAL
      else
         usable_RI = nint(dt)
      endif
      if (present(AVERAGING_INTERVAL)) then
         usable_AI = AVERAGING_INTERVAL
      else
         usable_AI = nint(dt)
      endif
      if (present(UNGRIDDED_DIMS)) then
         if (present(UNGRIDDED_UNIT) .or. present(UNGRIDDED_NAME) .or. present(UNGRIDDED_COORDS)) then
            _ASSERT(size(UNGRIDDED_DIMS) == 1,'needs informative message')
            _ASSERT(UNGRIDDED_DIMS(1) == size(UNGRIDDED_COORDS),'needs informative message')
         end if
      end if
      if (present(DIMS)) then
         _ASSERT(DIMS /= MAPL_DimsNone,'needs informative message')
      end if
      call MAPL_VarSpecCreateInListNew(STATE%COMPONENT_SPEC%EXPORT,                         &
           LONG_NAME  = LONG_NAME,                                               &
           UNITS      = UNITS,                                                   &
           SHORT_NAME = SHORT_NAME,                                              &
           DIMS       = DIMS,                                                    &
           STAT       = DATATYPE,                                                &
           NUM_SUBTILES=NUM_SUBTILES,                                            &
           ACCMLT_INTERVAL= usable_AI,                                           &
           COUPLE_INTERVAL= usable_RI,                                           &
           VLOCATION  = VLOCATION,                                               &
           HALOWIDTH  = HALOWIDTH,                                               &
           PRECISION  = PRECISION,                                               &
           DEFAULT    = DEFAULT,                                                 &
           UNGRIDDED_DIMS = UNGRIDDED_DIMS,                                      &
           UNGRIDDED_NAME = UNGRIDDED_NAME,                                    &
           UNGRIDDED_UNIT = UNGRIDDED_UNIT,                                    &
           UNGRIDDED_COORDS = UNGRIDDED_COORDS,                                  &
           FIELD_TYPE = FIELD_TYPE,                                              &
           STAGGERING = STAGGERING,                                              &
           ROTATION = ROTATION,                                                  &
           DEPENDS_ON = DEPENDS_ON, &
           DEPENDS_ON_CHILDREN = DEPENDS_ON_CHILDREN, &
           RC=status  )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddExportSpec_
Call graph
mapl_stateaddexportspec_ calls ESMF_ConfigGetAttribute, mapl_assert, mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspeccreateinlistnew calls mapl_assert, mapl_return, mapl_verify, update_legacy, vector_push_back
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
update_legacy calls of
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
mapl_addexportspec calls mapl_stateaddexportspec_
addnewspec calls mapl_addexportspec
setservices calls mapl_addexportspec, addstate
addstate calls addnewspec