MAPL_VerifyFriendlyInField – MAPL
MAPL_VerifyFriendlyInField Function
21 statements
Source File
private function MAPL_VerifyFriendlyInField(FIELD, FRIEND2COMP, RC) result(FRIENDLY)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
character(len=*), intent(in) :: FRIEND2COMP
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Source Code
   function MAPL_VerifyFriendlyInField(FIELD,FRIEND2COMP,RC) result(FRIENDLY)
      type (ESMF_field),          intent(INout)    :: FIELD
      character(len=*),           intent(IN)    :: FRIEND2COMP
      integer  , optional,        intent(OUT)   :: RC
      logical                                   :: FRIENDLY
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_VerifyFriendlyField"
      integer                               :: status
      logical                               :: isPresent
      type(ESMF_INFO)                       :: infoh
      call ESMF_InfoGetFromHost(FIELD, infoh, RC=status)
      isPresent=ESMF_InfoIsPresent(infoh,key="FriendlyTo"//trim(FRIEND2COMP),RC=STATUS)
      _VERIFY(STATUS)
      if(isPresent) then
         call ESMF_InfoGet(infoh,key="FriendlyTo"//trim(FRIEND2COMP),value=FRIENDLY, RC=status)
         _VERIFY(STATUS)
      else
         FRIENDLY = .false.
      end if
      _RETURN(ESMF_SUCCESS)
   end function MAPL_VerifyFriendlyInField
Call graph
mapl_verifyfriendlyinfield calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verifyfriendly calls mapl_verifyfriendlyinfield, mapl_verifyfriendlyinstate
mapl_verifyfriendlyinstate calls mapl_verifyfriendly