MAPL_IOCountLevels – MAPL
MAPL_IOCountLevels Subroutine
41 statements
Source File
public subroutine MAPL_IOCountLevels(cf, nlev, rc)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout), target :: cf
integer, intent(out) :: nlev
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine MAPL_IOCountLevels(cf,nlev,rc)
  type(FileMetadata), target, intent(inout) :: cf
  integer, intent(out) :: nlev
  integer, intent(out), optional :: rc
  integer :: status
  type(StringVariableMap), pointer :: vars
  type(StringVariableMapIterator) :: iter
  type(StringIntegerMap), pointer :: dims
  integer, pointer :: dimsize => null()
  character(len=:), pointer :: name
  type(StringVector), pointer :: vdims
  type(Variable), pointer :: var
  integer :: levsize
  nlev = 0
  dims => cf%get_dimensions()
  vars => cf%get_variables()
  iter = vars%ftn_begin()
  do while(iter/=vars%ftn_end())
     call iter%next()
     name => iter%first()
     var => iter%second()
     dimsize => dims%at(trim(name))
     if (.not.associated(dimsize)) then
        vdims => var%get_dimensions()
        if (vdims%get_index('lev') /=0) then
           levsize = cf%get_dimension('lev',rc=status)
           _VERIFY(status)
           nlev=nlev+levsize
        else if (vdims%get_index('edge') /=0) then
           levsize = cf%get_dimension('edge',rc=status)
           _VERIFY(status)
           nlev=nlev+levsize
        else
           nlev=nlev+1
        end if
     end if
     if (associated(dimsize)) nullify(dimsize)
  end do
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_IOCountLevels
Call graph
mapl_iocountlevels calls at, get_index, get_dimensions, get_dimension, get_variables, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, mapl_return, mapl_verify
get_dimension calls at, mapl_return, find
get_variables calls mapl_return
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_advpos calls map_s_get_child, to_node
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value