MAPL_GridCompSetGeomXGrid – MAPL
MAPL_GridCompSetGeomXGrid Subroutine
13 statements
Source File
private subroutine MAPL_GridCompSetGeomXGrid(gridcomp, xgrid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_XGrid), intent(in) :: xgrid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GridCompSetGeomXGrid(gridcomp, xgrid, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(ESMF_XGrid), intent(in) :: xgrid
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Geom) :: geom
      geom = ESMF_GeomCreate(xgrid, _RC)
      call MAPL_GridCompSetGeom(gridcomp, geom, _RC)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GridCompSetGeomXGrid
Call graph
mapl_gridcompsetgeomxgrid calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeom calls mapl_gridcompsetgeomxgrid, mapl_gridcompsetgeom, mapl_gridcompsetgeomgrid, mapl_gridcompsetgeomlocstream, mapl_gridcompsetgeommesh
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_gridcompsetgeomgrid calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeomlocstream calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_gridcompsetgeommesh calls ESMF_GeomCreate, mapl_gridcompsetgeom, mapl_return, mapl_verify
mapl_throw_exception calls initialize