MAPL_GeomGetId – MAPL
MAPL_GeomGetId Function
15 statements
Source File
public function MAPL_GeomGetId(geom, isPresent, rc) result(id)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom
logical, intent(out), optional :: isPresent
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function MAPL_GeomGetId(geom, isPresent, rc) result(id)
      type(ESMF_Geom), intent(in) :: geom
      logical, optional, intent(out) :: isPresent
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Info) :: info
      integer, parameter :: NOT_FOUND = -1
      call ESMF_InfoGetFromHost(geom, info, _RC)
      call ESMF_InfoGet(info, ID_INFO_KEY, id, default=NOT_FOUND, _RC)
      if (present(isPresent)) isPresent = (id /= NOT_FOUND)
      _RETURN(_SUCCESS)
   end function MAPL_GeomGetId
Call graph
mapl_geomgetid calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_mapl_geom calls mapl_geomgetid
add_variable calls get_mapl_geom
bundle_to_metadata calls get_mapl_geom, add_variables
add_variables calls add_variable