MAPL_IOGetTime – MAPL
MAPL_IOGetTime Subroutine
24 statements
Source File
public subroutine MAPL_IOGetTime(cf, nymd, nhms, rc)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout) :: cf
integer, intent(out) :: nymd
integer, intent(out) :: nhms
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine MAPL_IOGetTime(cf,nymd,nhms,rc)
  type(FileMetadata), intent(inout) :: cf
  integer, intent(out) :: nymd,nhms
  integer, intent(out), optional :: rc
  integer :: status
  class(Variable), pointer :: var
  type(Attribute), pointer :: attr
  class(*), pointer :: units
  integer :: year,month,day,hour,min,sec
  var => cf%get_variable('time',rc=status)
  _VERIFY(status)
  attr => var%get_attribute('units')
  units => attr%get_value()
  select type(units)
  type is (character(*))
     call MAPL_NCIOParseTimeUnits(units,year,month,day,hour,min,sec,status)
  class default
     _FAIL( 'unsupported subclass for units')
  end select
  nymd = year*10000 + month*100 + day
  nhms = hour*10000 + min*100   + sec
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_IOGetTime
Call graph
mapl_iogettime calls mapl_assert, get_attribute, get_value, get_variable, mapl_ncioparsetimeunits, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_value calls mapl_return
get_variable calls mapl_return, mapl_verify, at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
map_at_rc calls map_find