MAPL_WireComponent – MAPL
MAPL_WireComponent Subroutine
212 statements
Source File
private recursive subroutine MAPL_WireComponent(GC, RC)
The routine MAPL_WireComponent connects the child components, creates the couplers, and adds child info to GC’s import and export specs.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, optional :: RC
Calls
Called by
Source Code
   recursive subroutine MAPL_WireComponent(GC, RC)
      ! !ARGUMENTS:
      type(ESMF_GridComp), intent(INOUT) :: GC
      integer,   optional                :: RC      ! return code
      !=============================================================================
      !
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)            :: IAm
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      ! Local types
      ! -----------
      type SpecWrapper
         type (MAPL_VarSpec),              pointer :: SPEC(:)
      end type SpecWrapper
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: STATE
      type (ESMF_CplComp),               pointer  :: CCS(:,:)
      type (MAPL_VarSpec),               pointer  :: IMPORT_SPECS(:)
      type (MAPL_VarSpec),               pointer  :: EXPORT_SPECS(:)
      type (MAPL_VarSpec),               pointer  :: IM_SPECS(:)
      type (MAPL_VarSpec),               pointer  :: EX_SPECS(:)
      type (SpecWrapper), pointer, dimension(:,:) :: SRCS
      type (SpecWrapper), pointer, dimension(:,:) :: DSTS
      character(len=ESMF_MAXSTR)                  :: SRCNAME
      character(len=ESMF_MAXSTR)                  :: DSTNAME
      character(len=ESMF_MAXSTR)                  :: SHORT_NAME
      character(len=ESMF_MAXSTR)                  :: ENAME
      integer                                     :: I, J, K, N
      integer                                     :: NC
      integer                                     :: STAT
      logical                                     :: SATISFIED
      logical                                     :: PARENTIMPORT
      logical :: is_connected
      type (MAPL_Connectivity), pointer           :: conn
      type (VarConn), pointer                :: CONNECT
      type (VarConn), pointer                :: DONOTCONN
      type(ESMF_GridComp), pointer :: gridcomp
      type (ESMF_Info) :: infoh
      ! Begin
      ! Get my name and set-up traceback handle
      ! ---------------------------------------
      Iam = 'MAPL_WireComponent'
      call ESMF_GridCompGet( GC, NAME=comp_name, _RC)
      Iam = trim(comp_name) // trim(Iam)
      ! Retrieve the pointer to the child components
      ! --------------------------------------------
      call MAPL_InternalStateRetrieve ( GC, STATE, _RC)
      IMPORT_SPECS => STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      EXPORT_SPECS => STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      ! First look for import couplings that are satisfied internally
      ! -------------------------------------------------------------
      if (STATE%get_num_children() == 0) then
         _RETURN(ESMF_SUCCESS)
      end if
      call MAPL_ConnectivityGet(gc, connectivityPtr=conn, _RC)
      CONNECT => CONN%CONNECT
      DONOTCONN => CONN%DONOTCONN
      NC = STATE%get_num_children()
      allocate(SRCS(NC,NC), DSTS(NC,NC), __STAT__)
      DO I=1,NC
         DO J=1,NC
            NULLIFY(SRCS(J,I)%SPEC)
            NULLIFY(DSTS(J,I)%SPEC)
         END DO
      END DO
      ! first check if we need to add Exports from children
      do I=1,NC       !  Cycle thru children's imports
         gridcomp => STATE%get_child_gridcomp(I)
         call MAPL_GridCompGetVarSpecs(gridcomp, EXPORT=EX_SPECS, _RC)
         if (.not. associated(EX_SPECS)) then
            cycle
         end if
         do K=1,size(EX_SPECS)
            call MAPL_VarSpecGet(EX_SPECS(K), SHORT_NAME=SHORT_NAME, _RC)
            is_connected = connect%varIsConnected(IMPORT_NAME=SHORT_NAME, &
                 export=I, import=MAPL_Self, _RC)
            if (is_connected) then
               call MAPL_VarSpecAddRefToList(STATE%COMPONENT_SPEC%EXPORT, EX_SPECS(K), &
                    rc=status)
               if (status /= MAPL_DuplicateEntry) then
                  _VERIFY(status)
               else
                  _FAIL('ERROR: duplicate entry for ' // trim(short_name))
               endif
            end if
         end do
      end do
      ! try to satisfy imports internally
      do I=1,NC       !  Cycle thru children's imports
         ! check "do not connect" list for
         PARENTIMPORT = .true.
         if (DONOTCONN%varIsListed(SHORT_NAME="MAPL_AnyChildImport", &
              IMPORT=I, RC=status)) then
            _VERIFY(status)
            PARENTIMPORT = .false.
         end if
         gridcomp => STATE%get_child_gridcomp(I)
         call MAPL_GridCompGetVarSpecs(gridcomp, IMPORT=IM_SPECS, RC=status)
         _VERIFY(status)
         if (.not. associated(IM_SPECS)) then
            cycle
         end if
         do K=1,size(IM_SPECS)
            call MAPL_VarSpecGet(IM_SPECS(K), SHORT_NAME=SHORT_NAME, &
                 STAT=STAT, RC=status)
            _VERIFY(status)
            ! do not connect Friendly bundles
#if 0
            IF (IAND(STAT, MAPL_BundleItem) /= 0) then
               cycle
            end if
#endif
            ! check "do not connect" list
            if (DONOTCONN%varIsListed(SHORT_NAME=SHORT_NAME, &
                 IMPORT=I, RC=status)) then
               _VERIFY(status)
               cycle
            end if
            _VERIFY(status)
            !  Cycle thru all exports
            !------------------------
            call MAPL_VarSpecGet(IM_SPECS(K), STAT=STAT, RC=status)
            _VERIFY(status)
            SATISFIED = .false.
            do J=1,NC
               if(I==J) cycle
               ! then check if this is internally satisfied
               if (connect%varIsConnected(IMPORT_NAME=SHORT_NAME, &
                    IMPORT=I, EXPORT=J, RC=status)) then
                  _VERIFY(status)
                  SATISFIED = .true.
                  STAT = ior(STAT,MAPL_CplSATISFIED)
                  call MAPL_VarSpecSet(IM_SPECS(K), STAT=STAT, RC=status)
                  _VERIFY(status)
                  exit
               end if
            end do
            do J=1,NC
               gridcomp => STATE%get_child_gridcomp(J)
               call MAPL_GridCompGetVarSpecs(gridcomp, EXPORT=EX_SPECS, RC=status)
               _VERIFY(status)
               ! Trying to satisfy I's imports from J's exports
               ! ----------------------------------------------
               ! then check if this is internally satisfied
               if (connect%varIsConnected(IMPORT_NAME=SHORT_NAME, EXPORT_NAME=ENAME, &
                    IMPORT=I, EXPORT=J, RC=status)) then
                  ! If a match is found, add it to that coupler's src and dst specs
                  ! ?? Mark the import satisfied and the export needed.
                  ! -----------------------------------------------------------------
                  _VERIFY(status)
                  N =  MAPL_VarSpecGetIndex(EX_SPECS,ENAME,RC=status)
                  if(N /= -1) then
                     _VERIFY(status)
                  else
                     print *,'ERROR: cannot find export ',trim(ENAME)
                     _RETURN(ESMF_FAILURE)
                  endif
                  !ALT: currently the function comparing the SPECS assumes SAME names;
                  !     so we temporarily change the SHORT_NAME, and restore the name after comparison
                  call MAPL_VarSpecSet(EX_SPECS(N), SHORT_NAME=SHORT_NAME, RC=status)
                  _VERIFY(status)
                  if (EX_SPECS(N) == IM_SPECS(K)) then
                     call MAPL_VarSpecSet(EX_SPECS(N), SHORT_NAME=ENAME, RC=status)
                     _VERIFY(status)
                     ! this a direct connection
                     ! SPECS are the same, no additional averaging is needed
                     call MAPL_Reconnect(STATE,       &
                          STATE%get_child_gridcomp(I), MAPL_Import, K,         &
                          STATE%get_child_gridcomp(J), MAPL_Export, N, RC=status)
                     _VERIFY(status)
                  else
                     _ASSERT(MAPL_VarSpecSamePrec(EX_SPECS(N), IM_SPECS(K)),'needs informative message')
                     call MAPL_VarSpecSet(EX_SPECS(N), SHORT_NAME=ENAME, RC=status)
                     _VERIFY(status)
                     ! coupler is needed
                     call MAPL_VarSpecAddRefToList(DSTS(J,I)%SPEC,IM_SPECS(K), RC=status)
                     _VERIFY(status)
                     call MAPL_VarSpecAddRefToList(SRCS(J,I)%SPEC,EX_SPECS(N), RC=status)
                     _VERIFY(status)
                  end if
               else
                  ! Imports that are not internally satisfied have their specs put in the GC's
                  ! import spec to be externally satisfied.  Their status is left unaltered.
                  ! --------------------------------------------------------------------------
                  if (.not. SATISFIED .and. PARENTIMPORT) then
                     _VERIFY(status)
                     call MAPL_VarSpecGet(IM_SPECS(K), STAT=STAT, RC=status)
                     _VERIFY(status)
                     if (iand(STAT,MAPL_CplSATISFIED) /= 0) then
                        cycle
                     end if
                     call MAPL_VarSpecAddRefToList(STATE%COMPONENT_SPEC%IMPORT, IM_SPECS(K), RC=status)
                     if (status /= MAPL_DuplicateEntry) then
                        _VERIFY(status)
                     else
                        N =  MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS, IM_SPECS(K),RC=status)
                        if(N /= -1) then
                           _VERIFY(status)
                        else
                           _RETURN(ESMF_FAILURE)
                        endif
                        call MAPL_Reconnect(STATE,       &
                             GC, MAPL_Import, N,         &
                             STATE%get_child_gridcomp(I), MAPL_Import, K, RC=status)
                        _VERIFY(status)
                     end if
                  endif
               end if
            enddo
         enddo
      enddo
      allocate(STATE%CCS(NC,NC),STAT=status)
      _VERIFY(status)
      allocate(STATE%CIM(NC,NC),STAT=status)
      _VERIFY(status)
      allocate(STATE%CEX(NC,NC),STAT=status)
      _VERIFY(status)
      allocate(STATE%CCcreated(NC,NC),STAT=status)
      _VERIFY(status)
      STATE%CCcreated = .false.
      CCS          => STATE%CCS
      do I=1,NC
         do J=1,NC
            if(associated(DSTS(J,I)%SPEC)) then
               if(I/=J) then
                  call ESMF_GridCompGet( STATE%get_child_gridcomp(J), NAME=SRCNAME, RC=status )
                  _VERIFY(status)
                  call ESMF_GridCompGet( STATE%get_child_gridcomp(I), NAME=DSTNAME, RC=status )
                  _VERIFY(status)
                  CCS(J,I) = ESMF_CplCompCreate (                        &
                       NAME       = trim(SRCNAME)//'_2_'//trim(DSTNAME), &
                                !                     LAYOUT     = STATE%GRID%LAYOUT,                   &
                       contextFlag = ESMF_CONTEXT_PARENT_VM,              &
                       CONFIG     = STATE%CF,                  RC=status )
                  _VERIFY(status)
                  !                STATE%CIM(J,I) = ESMF_StateCreate (     &
                  !                     STATENAME = trim(SRCNAME)//'_2_'//trim(DSTNAME) // '_Imports', &
                  !                     STATETYPE = ESMF_STATEEXPORT,               &
                  !                     RC=status )
                  !                _VERIFY(status)
                  !                STATE%CEX(J,I) = ESMF_StateCreate (     &
                  !                     STATENAME = trim(SRCNAME)//'_2_'//trim(DSTNAME) // '_Exports', &
                  !                     STATETYPE = ESMF_STATEEXPORT,               &
                  !                     RC=status )
                  !                _VERIFY(status)
                  STATE%CCcreated(J,I) = .true.
                  call ESMF_InfoGetFromHost(CCS(J,I), infoh, _RC)
                  call ESMF_InfoSet(infoh,key='ClockYetToAdvance', value=.true., _RC)
                  call WRITE_PARALLEL("Coupler needed for "//trim(SRCNAME)// ' and ' //&
                       trim(DSTNAME))
                  call ESMF_CplCompSetServices (CCS(J,I), GenericCplSetServices, RC=status )
                  _VERIFY(status)
                  call MAPL_CplCompSetVarSpecs(CCS(J,I),SRCS(J,I)%SPEC,DSTS(J,I)%SPEC,RC=status)
                  _VERIFY(status)
               endif
            endif
         enddo
      enddo
      ! Add my children's exports specs to mine
      ! ---------------------------------------
      ! currently disabled (they will be explicitly added to the EXPORT as nested)
      !    call MAPL_StateAddExportSpecFrmAll ( STATE, RC=status  )
      !    _VERIFY(status)
      deallocate(SRCS, DSTS, STAT=status)
      _VERIFY(status)
      ! Wire my children
      ! ---------------------------------------
      do I=1,NC
!ALT      call MAPL_WireComponent(GCS(I), RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_WireComponent
Call graph
mapl_wirecomponent calls ESMF_CplCompCreate, ESMF_GridCompGet, ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_cplcompsetservices, mapl_assert, mapl_varspecaddreftolist, mapl_varspecget, mapl_varspecgetindex, mapl_varspecset, write_parallel, varisconnected, get_child_gridcomp, get_num_children, mapl_connectivityget, mapl_cplcompsetvarspecs, mapl_gridcompgetvarspecs, mapl_internalstateretrieve, mapl_reconnect, mapl_return, mapl_varspecsameprec, mapl_verify, varislisted
mapl_genericsetservices calls mapl_wirecomponent
setservices calls mapl_genericsetservices