MAPL_BundleReadNCPar – MAPL
MAPL_BundleReadNCPar Subroutine
123 statements
Source File
private subroutine MAPL_BundleReadNCPar(Bundle, arrdes, filename, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
type(ArrDescr), intent(inout) :: arrdes
character(len=*), intent(in) :: filename
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_BundleReadNCPar(Bundle, arrdes, filename, rc)
    type(ESMF_FieldBundle), intent(inout)   :: Bundle
    type(ArrDescr), intent(inout)           :: arrdes
    character(len=*),   intent(in   )       :: filename
    integer, optional, intent(out)          :: rc
    integer                            :: nVars
    integer                            :: l
    type(ESMF_Field)                   :: field
    character(len=ESMF_MAXSTR)         :: FieldName
    integer                            :: info
    integer                            :: STATUS
    integer                            :: ind
    type(ESMF_Grid)                    :: grid
    integer                            :: MAPL_DIMS, reader_rank
    integer, pointer                   :: MASK(:) => null()
    type(Netcdf4_Fileformatter)        :: formatter
    type(FileMetaData)                 :: metadata
    character(len=:), allocatable      :: fname_by_rank
    logical :: grid_file_match,flip, restore_export, isPresent
    type(ESMF_VM) :: vm
    integer :: comm
    type(ESMF_INFO) :: infoh
    call ESMF_FieldBundleGet(Bundle,FieldCount=nVars,rc=STATUS)
    _VERIFY(STATUS)
    !open the file for parallel reading
    if (arrdes%readers_comm/=MPI_COMM_NULL) then
       call MPI_Info_create(info,STATUS)
       _VERIFY(STATUS)
       call MPI_Info_set(info,"romio_cb_read", trim(arrdes%romio_cb_read),STATUS)
       _VERIFY(STATUS)
       call MPI_Info_set(info,"cb_buffer_size", trim(arrdes%cb_buffer_size),STATUS)
       _VERIFY(STATUS)
       if (arrdes%num_readers == 1) then
          call formatter%open(filename,pFIO_READ,rc=status)
          _VERIFY(STATUS)
       else
          if(arrdes%split_restart .and. .not. arrdes%tile) then
             call MPI_COMM_RANK(arrdes%readers_comm,reader_rank,status)
             _VERIFY(STATUS)
             fname_by_rank = get_fname_by_rank(trim(filename),reader_rank)
             call formatter%open(trim(fname_by_rank),pFIO_READ,rc=status)
             _VERIFY(STATUS)
          else
             call formatter%open(filename,pFIO_READ,comm=arrdes%readers_comm,info=info,rc=status)
             _VERIFY(STATUS)
          endif
       end if
       metadata=formatter%read(rc=status)
       _VERIFY(status)
       call ESMF_FieldBundleGet(bundle,grid=grid,rc=status)
       _VERIFY(status)
       grid_file_match=compare_grid_file(metadata,grid,rc=status)
       _VERIFY(status)
       flip = check_flip(metadata,rc=status)
       _VERIFY(status)
       !_ASSERT(grid_file_match,"File grid dimensions in "//trim(filename)//" do not match grid")
    endif
    call ESMF_VMGetCurrent(vm,rc=status)
    _VERIFY(status)
    call ESMF_VMGet(vm,mpiCommunicator=comm,rc=status)
    _VERIFY(status)
    call MPI_BCast(flip,1,MPI_LOGICAL,0,comm,status)
    _VERIFY(status)
    do l=1,nVars
      call ESMF_FieldBundleGet(bundle, fieldIndex=l, field=field, rc=status)
      _VERIFY(STATUS)
      call ESMF_FieldGet(field,name=FieldName,rc=status)
      _VERIFY(STATUS)
! Check for old style aerosol names
      ind= index(FieldName, '::')
      if (ind> 0) then
        FieldName = trim(FieldName(ind+2:))
      end if
      if(.not.associated(MASK)) then
         call ESMF_InfoGetFromHost(field,infoh,rc=status)
         _VERIFY(STATUS)
         call ESMF_InfoGet(infoh,'DIMS',MAPL_DIMS,rc=status)
         _VERIFY(STATUS)
         if (MAPL_DIMS == MAPL_DimsTileOnly .or. MAPL_DIMS == MAPL_DimsTileTile) then
            call ESMF_FieldGet   (field, grid=grid, rc=status)
            _VERIFY(STATUS)
            call MAPL_TileMaskGet(grid,  mask, rc=status)
            _VERIFY(STATUS)
!@         else
!@            allocate(Mask(1))
         endif
      endif
      restore_export = .false.
      call ESMF_InfoGetFromHost(bundle, infoh, _RC)
      isPresent = ESMF_InfoIsPresent(infoh, 'MAPL_RestoreExport', _RC)
      if (isPresent) then
         call ESMF_InfoGet(infoh, key='MAPL_RestoreExport', value=restore_export, _RC)
      end if
      if (restore_export) then
         call MAPL_AllocateCoupling(field, _RC)
      end if
      call MAPL_FieldReadNCPar(formatter, FieldName, field, arrdes=arrdes, HomePE=mask, rc=status)
      _VERIFY(STATUS)
      if (flip) then
          call flip_field(field,rc=status)
          _VERIFY(status)
      end if
    enddo
    if(associated(MASK)) then
       DEALOC_(MASK)
    end if
    if (arrdes%readers_comm/=MPI_COMM_NULL) then
       call formatter%close()
       _VERIFY(STATUS)
       call MPI_Info_free(info, status)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_BundleReadNCPar
Call graph
mapl_bundlereadncpar calls ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, esmf_fieldget, mapl_allocatecoupling, mapl_deallocnodearray, mapl_syncsharedmemory, mpi_bcast, mpi_comm_rank, mpi_info_create, mpi_info_free, mpi_info_set, check_flip, compare_grid_file, flip_field, get_fname_by_rank, mapl_fieldreadncpar, mapl_return, mapl_tilemaskget, mapl_verify
mapl_varreadncpar calls mapl_bundlereadncpar, mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d, mapl_statevarreadncpar
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_statevarreadncpar calls mapl_varreadncpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore