MAPL_FieldBundleGet – MAPL
MAPL_FieldBundleGet Subroutine
92 statements
Source File
public subroutine MAPL_FieldBundleGet(fieldBundle, unusable, fieldList, geom, typekind, ungriddedUbound, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: fieldBundle
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Field), intent(out), optional, allocatable :: fieldList(:)
type(ESMF_Geom), intent(out), optional :: geom
type(ESMF_TypeKind_Flag), intent(out), optional :: typekind
integer, intent(out), optional, allocatable :: ungriddedUbound(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_FieldBundleGet(fieldBundle, unusable, fieldList, geom, typekind, ungriddedUbound, rc)
      type(ESMF_FieldBundle), intent(in) :: fieldBundle
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Field), optional, allocatable, intent(out) :: fieldList(:)
      type(ESMF_Geom), optional, intent(out) :: geom
      type(ESMF_TypeKind_Flag), optional, intent(out) :: typekind
      integer, allocatable, optional, intent(out) :: ungriddedUbound(:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: fieldCount
      type(ESMF_GeomType_Flag) :: geomtype
      character(:), allocatable :: typekind_str
      type(ESMF_Info) :: ungridded_info
      type(UngriddedDims) :: ungridded_dims
      type(LU_Bound), allocatable :: bounds(:)
      integer :: num_levels
      character(:), allocatable :: vloc
      if (present(fieldList)) then
         call ESMF_FieldBundleGet(fieldBundle, fieldCount=fieldCount, _RC)
         allocate(fieldList(fieldCount))
         call ESMF_FieldBundleGet(fieldBundle, fieldList=fieldList, itemOrderflag=ESMF_ITEMORDER_ADDORDER, _RC)
      end if
      if (present(geom)) then
         call get_geom(fieldBundle, geom, rc)
      end if
      if (present(typekind)) then
         call MAPL_InfoGetInternal(fieldBundle, key=KEY_TYPEKIND, value=typekind_str, _RC)
         select case (typekind_str)
         case ('R4')
            typekind = ESMF_TYPEKIND_R4
         case ('R8')
            typekind = ESMF_TYPEKIND_R8
         case ('I4')
            typekind = ESMF_TYPEKIND_I4
         case ('I8')
            typekind = ESMF_TYPEKIND_I8
         case ('LOGICAL')
            typekind = ESMF_TYPEKIND_LOGICAL
         case default
            _FAIL('unsupported typekind')
         end select
      end if
       if (present(ungriddedUbound)) then
         ungridded_info = MAPL_InfoCreateFromInternal(fieldBundle, _RC)
         ungridded_dims =  make_ungriddedDims(ungridded_info, KEY_UNGRIDDED_DIMS, _RC)
         bounds = ungridded_dims%get_bounds()
         call MAPL_InfoGetInternal(fieldBundle, key=KEY_VLOC, value=vloc, _RC)
         if (vloc /= 'VERTICAL_DIM_NONE') then
            call MAPL_InfoGetInternal(fieldBundle, key=KEY_NUM_LEVELS, value=num_levels, _RC)
            select case (vloc)
            case ('VERTICAL_DIM_CENTER')
               bounds = [LU_Bound(1, num_levels), bounds]
            case ('VERTICAL_DIM_EDGE')
               bounds = [LU_Bound(1, num_levels+1), bounds]
            case default
               _FAIL('unsupported vertical location')
            end select
         end if
         ungriddedUbound = bounds%upper
      end if
      _RETURN(_SUCCESS)
   contains
      subroutine get_geom(fieldBundle, geom, rc)
         type(ESMF_FieldBundle), intent(in) :: fieldBundle
         type(ESMF_Geom), intent(inout) :: geom
         integer, optional, intent(out) :: rc
         integer :: status
         type(ESMF_GeomType_Flag) :: geomtype
         type(ESMF_Grid) :: grid
         call ESMF_FieldBundleGet(fieldBundle, geomtype=geomtype, _RC)
         if (geomtype == ESMF_GEOMTYPE_GRID) then
            call ESMF_FieldBundleGet(fieldBundle, grid=grid, _RC)
            ! memory leak
            geom = ESMF_GeomCreate(grid=grid, _RC)
            _RETURN(_SUCCESS)
         end if
         _FAIL('unsupported geomtype; needs simple extension')
         _RETURN(_SUCCESS)
      end subroutine get_geom
   end subroutine MAPL_FieldBundleGet
Call graph
mapl_fieldbundleget calls ESMF_GeomCreate, esmf_fieldbundleget, mapl_assert, mapl_infocreatefrominternal, mapl_infogetinternal, get_bounds, make_ungriddeddims, mapl_return, mapl_verify
make_ungriddeddims calls mapl_return, mapl_verify, ESMF_InfoCreate, ESMF_InfoDestroy, mapl_infoget, make_dim_key, make_ungriddeddim
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_dim_key calls mapl_assert, mapl_return
make_ungriddeddim calls mapl_return, mapl_verify, mapl_infoget
teardown_bundle calls mapl_fieldbundleget
test_change_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_typekind calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_units calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_change_weights_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_create_fields_with_ungridded calls mapl_fieldbundleget, update_bundle, teardown_bundle
test_same_geom calls mapl_fieldbundleget, update_bundle, teardown_bundle