MAPL_IOGetNonDimVars – MAPL
MAPL_IOGetNonDimVars Function
24 statements
Source File
public function MAPL_IOGetNonDimVars(cf, rc) result(nondim_vars)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(inout) :: cf
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Source Code
  function MAPL_IOGetNonDimVars(cf,rc) result(nondim_vars)
  type(FileMetadata), intent(inout) :: cf
  integer, intent(out), optional :: rc
  type(StringVector) :: nondim_vars
  type(StringVariableMap), pointer :: vars
  type(StringVariableMapIterator) :: iter
  type(StringIntegerMap), pointer :: dims
  integer, pointer :: dimsize => null()
  character(len=:), pointer :: name
  integer :: status
  dims => cf%get_dimensions()
  vars => cf%get_variables(_RC)
  iter = vars%ftn_begin()
  do while(iter/=vars%ftn_end())
     call iter%next()
     name =>  iter%first()
     dimsize => dims%at(trim(name))
     if (.not.associated(dimsize)) call nondim_vars%push_back(trim(name))
     if (associated(dimsize)) nullify(dimsize)
  end do
  _RETURN(ESMF_SUCCESS)
  end function MAPL_IOGetNonDimVars
Call graph
mapl_iogetnondimvars calls at, get_dimensions, get_variables, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, mapl_return, mapl_verify, push_back
get_variables calls mapl_return
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_advpos calls map_s_get_child, to_node
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value