MAPL_FieldAttSetI4 – MAPL
MAPL_FieldAttSetI4 Module Subroutine
27 statements
Source File
module subroutine MAPL_FieldAttSetI4(FIELD, NAME, VALUE, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
character(len=*), intent(in) :: NAME
integer, intent(in) :: VALUE
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  module subroutine MAPL_FieldAttSetI4(FIELD, NAME, VALUE, RC)
    type(ESMF_Field),                 intent(INOUT) :: FIELD
    character(len=*),                 intent(IN   ) :: NAME
    integer,                          intent(IN   ) :: VALUE
    integer, optional,                intent(  OUT) :: RC
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_FieldAttSet"
    integer                               :: STATUS
    type(ESMF_Array)                        :: array
    type(ESMF_FieldStatus_Flag)             :: fieldStatus
    type(ESMF_Info)                         :: infoh
    call ESMF_InfoGetFromHost(FIELD,infoh,_RC)
    call ESMF_InfoSet(infoh,NAME,VALUE,_RC)
    call ESMF_FieldGet(field, status=fieldStatus, _RC)
    if(fieldStatus == ESMF_FIELDSTATUS_COMPLETE) then
       call ESMF_FieldGet(field, Array=array, _RC)
       call ESMF_InfoGetFromHost(array,infoh,_RC)
       call ESMF_InfoSet(infoh,NAME,VALUE,_RC)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldAttSetI4
Call graph
mapl_fieldattseti4 calls ESMF_InfoGetFromHost, ESMF_InfoSet, esmf_fieldget, mapl_return, mapl_verify, mapl_fieldattseti4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_attributeset calls mapl_fieldattseti4
mapl_esmfstatereadfromfile calls mapl_attributeset
mapl_fieldalloccommit calls mapl_attributeset, mapl_fieldalloccommit
mapl_stateattseti4 calls mapl_attributeset, mapl_stateattseti4
mapl_statecreatefromspecnew calls mapl_attributeset
mapl_genericinitialize calls mapl_esmfstatereadfromfile, mapl_statecreatefromspecnew
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
mapl_staterefresh calls mapl_esmfstatereadfromfile