MAPL_StateCreateFromSpec – MAPL
MAPL_StateCreateFromSpec Subroutine
15 statements
Source File
public subroutine MAPL_StateCreateFromSpec(STATE, SPEC, DEFER, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
type(MAPL_VarSpec), intent(inout), target :: SPEC(:)
logical, intent(in), optional :: DEFER
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_StateCreateFromSpec(STATE,SPEC,DEFER,RC)
      type(ESMF_State),                 intent(INOUT) :: STATE
      type(MAPL_VarSpec), target,       intent(INOUT) :: SPEC(:)
      logical, optional,                intent(IN   ) :: DEFER
      integer, optional,                intent(  OUT) :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateCreateFromSpec"
      integer                               :: status
      type (StateSpecification) :: state_spec
      state_spec%old_var_specs => spec
      call state_spec%update_vector()
      call MAPL_StateCreateFromSpecNew(state, state_spec, defer,rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine MAPL_StateCreateFromSpec
Call graph
mapl_statecreatefromspec calls mapl_return, mapl_statecreatefromspecnew, mapl_verify, update_vector
mapl_return calls get_error_message, mapl_throw_exception
mapl_statecreatefromspecnew calls mapl_return, mapl_verify, ESMF_FieldIsCreated, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoSet, esmf_fieldbundlecreate, esmf_fieldbundleiscreated, esmf_fieldbundleset, esmf_fieldget, esmf_stateadd, esmf_statecreate, esmf_stateiscreated, mapl_allocatecoupling, mapl_attributeset, mapl_fieldalloccommit, mapl_fieldcreate, mapl_fieldcreateempty, mapl_stateadd, mapl_varspecget, mapl_varspecgetindex, mapl_varspecset, write_parallel, of
mapl_verify calls mapl_throw_exception
update_vector calls vector_clear, vector_push_back
initialize calls mapl_statecreatefromspec