MAPL_FieldBundleSet – MAPL
MAPL_FieldBundleSet Subroutine
24 statements
Source File
public subroutine MAPL_FieldBundleSet(fieldBundle, unusable, geom, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: fieldBundle
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Geom), intent(in), optional :: geom
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_FieldBundleSet(fieldBundle, unusable, geom, rc)
      type(ESMF_FieldBundle), intent(inout) :: fieldBundle
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Geom), optional, intent(in) :: geom
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_GeomType_Flag) :: geomtype
      type(ESMF_Grid) :: grid
      if (present(geom)) then
         call ESMF_GeomGet(geom, geomtype=geomtype, _RC)
         if (geomtype == ESMF_GEOMTYPE_GRID) then
            call ESMF_GeomGet(geom, grid=grid, _RC)
            call ESMF_FieldBundleSet(fieldBundle, grid=grid, _RC)
            _RETURN(_SUCCESS)
         end if
         _FAIL('unsupported geomtype')
      end if
      _RETURN(_SUCCESS)
   end subroutine MAPL_FieldBundleSet
Call graph
mapl_fieldbundleset calls ESMF_GeomGet, esmf_fieldbundleset, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setup_bundle calls mapl_fieldbundleset
test_change_geom calls setup_bundle
test_change_typekind calls setup_bundle
test_change_units calls setup_bundle
test_change_weights calls setup_bundle
test_change_weights_with_ungridded calls setup_bundle
test_create_fields calls setup_bundle
test_create_fields_with_ungridded calls setup_bundle
test_same_geom calls setup_bundle