MAPL_BundleWrite – MAPL
MAPL_BundleWrite Subroutine
27 statements
Source File
private subroutine MAPL_BundleWrite(UNIT, BUNDLE, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_BundleWrite(UNIT,BUNDLE, ARRDES, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_FieldBundle)          , intent(INOUT) :: BUNDLE
    type(ArrDescr),    optional , intent(INOUT) :: ARRDES
    integer,           optional , intent(  OUT) :: RC
    integer                                 :: status
    integer                                 :: J, N, fieldCount
    type (ESMF_Field)                       :: field
    character(len=ESMF_MAXSTR),allocatable  :: nameList(:)
    character(len=ESMF_MAXSTR)              :: BundleName
    call ESMF_FieldBundleGet(bundle, fieldCount=N, name=BundleName, rc=STATUS)
    _VERIFY(STATUS)
    allocate(namelist(N), stat=status)
    _VERIFY(STATUS)
    call ESMF_FieldBundleGet(bundle, fieldNameList=nameList, fieldCount=FieldCount, rc=STATUS)
    _VERIFY(STATUS)
    _ASSERT(N==fieldCount, 'inconsistent fieldcount')
    DO J = 1, N
       call MAPL_FieldBundleGet(bundle, fieldIndex=J, field=field, rc=status)
       _VERIFY(STATUS)
       call MAPL_FieldWrite(unit, field, arrdes=ARRDES, rc=status)
       _VERIFY(STATUS)
    END DO
    deallocate(nameList)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_BundleWrite
Call graph
mapl_bundlewrite calls esmf_fieldbundleget, mapl_assert, mapl_fieldbundleget, mapl_fieldwrite, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleget calls mapl_fieldbundlegetbyindex
mapl_fieldwrite calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_arrayget, esmf_fieldget, mapl_deallocnodearray, mapl_syncsharedmemory, mapl_varwrite, write_parallel, mapl_tilemaskget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_varwrite calls mapl_bundlewrite, mapl_statevarwrite, mapl_fieldwrite, mapl_varwrite_r4_2d, mapl_varwrite_r4_3d, mapl_varwrite_r4_4d, mapl_varwrite_r8_2d, mapl_varwrite_r8_3d, mapl_varwrite_r8_4d
mapl_statevarwrite calls mapl_bundlewrite, mapl_fieldwrite
mapl_esmfstatewritetofile calls mapl_varwrite
mapl_varwrite_r4_2d calls mapl_varwrite
mapl_varwrite_r4_3d calls mapl_varwrite
mapl_varwrite_r4_4d calls mapl_varwrite
mapl_varwrite_r8_2d calls mapl_varwrite
mapl_varwrite_r8_3d calls mapl_varwrite
mapl_varwrite_r8_4d calls mapl_varwrite
run calls mapl_varwrite
writerestart calls mapl_varwrite
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave