MAPL_run_driver – MAPL
MAPL_run_driver Subroutine
30 statements
Source File
public subroutine MAPL_run_driver(hconfig, is_model_pet, unusable, servers, rc)
Uses
MAPL_ApplicationSupport
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(inout) :: hconfig
logical, intent(in) :: is_model_pet
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_GridComp), intent(in), optional :: servers(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_run_driver(hconfig, is_model_pet, unusable, servers, rc)
      USE MAPL_ApplicationSupport
      type(ESMF_HConfig), intent(inout) :: hconfig
      logical, intent(in) :: is_model_pet
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_GridComp), optional, intent(in) :: servers(:)
      integer, optional, intent(out) :: rc
      type(GriddedComponentDriver) :: driver
      integer :: status
      driver = make_driver(hconfig, is_model_pet, _RC)
      if (is_model_pet) then
         call initialize_phases(driver, phases=GENERIC_INIT_PHASE_SEQUENCE, _RC)
         call driver%read_restart(_RC)
         call integrate(driver, _RC)
         call driver%write_restart(_RC)
         call driver%finalize(_RC)
      end if
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine MAPL_run_driver
Call graph
mapl_run_driver calls ESMF_CalendarSetDefault, ESMF_ClockCreate, ESMF_ClockGet, ESMF_TimePrint, ESMF_TimeSet, ESMF_VMGet, ESMF_VMGetCurrent, esmf_gridcompsetservices, esmf_hconfigasstring, esmf_hconfigcreateat, create_grid_comp, user_setservices, mpi_allgather, clock_advance, finalize, get_clock, read_restart, run, write_restart, hconfig_to_esmf_timeinterval, initialize_phases, mapl_return, mapl_verify
hconfig_to_esmf_timeinterval calls esmf_hconfigasstring, mapl_return, mapl_verify, string_to_esmf_timeinterval
initialize_phases calls mapl_return, mapl_verify, initialize
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_to_esmf_timeinterval calls mapl_return, mapl_verify, ESMF_TimeIntervalSet, mapl_assert
run_geos calls mapl_run_driver
geos calls run_geos