mapl_initialize – MAPL
mapl_initialize Subroutine
17 statements
Source File
public subroutine mapl_initialize(hconfig, unusable, is_model_pet, servers, mpiCommunicator, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(inout) :: hconfig
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(out), optional :: is_model_pet
type(ESMF_GridComp), intent(out), optional, allocatable :: servers(:)
integer, intent(in), optional :: mpiCommunicator
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine mapl_initialize(hconfig, unusable, is_model_pet, servers, mpiCommunicator, rc)
      type(ESMF_HConfig), intent(inout) :: hconfig
      class(KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(out) :: is_model_pet
      integer, optional, intent(in) :: mpiCommunicator
      type(ESMF_GridComp), allocatable, optional, intent(out) :: servers(:)
      integer, optional, intent(out) :: rc
      integer :: status
      call the_mapl_object%initialize(hconfig=hconfig, is_model_pet=is_model_pet, servers=servers, mpiCommunicator=mpiCommunicator, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine mapl_initialize
Call graph
mapl_initialize calls initialize, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception