match_geom – MAPL
match_geom Function
8 statements
Source File
private function match_geom(a, b) result(match)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in), allocatable :: a
type(ESMF_Geom), intent(in), allocatable :: b
Return Value logical
Calls
Called by
Source Code
   logical function match_geom(a, b) result(match)
      type(ESMF_Geom), allocatable, intent(in) :: a, b
      integer :: status
      match = .false.
      if (allocated(a) .and. allocated(b)) then
         match = MAPL_SameGeom(a, b)
      end if
   end function match_geom
Call graph
match_geom calls mapl_samegeom
mapl_samegeom calls same_geom
same_geom calls mapl_geomgetid
mapl_geomgetid calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
match calls match_geom
can_connect_units calls match
get_cost_geom calls match
get_cost_string calls match
get_cost_typekind calls match
make_action calls match, make_action
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match
get_cost calls get_cost_geom, get_cost_string, get_cost_typekind
update_item calls update_item_geom, update_item_string, update_item_typekind
can_connect_to calls can_connect_units, can_connect_to
connect_to calls can_connect_to
extension_cost calls get_cost
make_extension_safely calls update_item
test_can_connect_typekind calls can_connect_to
test_convertible_units calls can_connect_to
test_matched_attribute calls can_connect_to
test_mirror_units calls can_connect_to
test_mismatched_attribute calls can_connect_to
test_mismatched_units calls can_connect_to
test_multiple_attribute calls can_connect_to
test_same_units calls can_connect_to