match_r8 – MAPL
match_r8 Function
4 statements
Source File
private function match_r8(missing, b)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: missing
real(kind=ESMF_KIND_R8), intent(in) :: b
Return Value logical
Called by
Source Code
   logical function match_r8(missing,b)
      real(kind=ESMF_KIND_R8), intent(in) :: missing, b
      match_r8 = (missing==b)
   end function match_r8
Call graph
match calls match_r8
fraction_r4r8r4v calls match
fraction_r8r8r8v calls match
missing_r4r8r4v calls match
missing_r8r8r8v calls match
monotonic_r4r8r4v calls match
monotonic_r8r8r8v calls match
vote_r4r8r4v calls match
vote_r8r8r8v calls match