matches – MAPL
matches Function
10 statements
Source File
private function matches(this, item)
Uses
regex_module
Type Bound
VirtualConnectionPt
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPt), intent(in) :: this
type(VirtualConnectionPt), intent(in) :: item
Return Value logical
Calls
Called by
Source Code
   logical function matches(this, item)
      use regex_module
      class(VirtualConnectionPt), intent(in) :: this
      type(VirtualConnectionPt), intent(in) :: item
      type(regex_type) :: regex
      matches = (this%get_state_intent() == item%get_state_intent())
      if (.not. matches) return
      call regcomp(regex,'^'//this%get_full_name()//'$',flags='xmi')
      matches = regexec(regex,item%get_full_name())
   end function matches
Call graph
matches calls get_full_name, get_state_intent, regcomp, regexec
filter calls matches
connect calls filter