merge_hconfig – MAPL
merge_hconfig Function
32 statements
Source File
public function merge_hconfig(parent_hconfig, child_hconfig, rc) result(total_hconfig)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: parent_hconfig
type(ESMF_HConfig), intent(in) :: child_hconfig
integer, intent(out), optional :: rc
Return Value type(ESMF_HConfig)
Calls
Called by
Source Code
   function merge_hconfig(parent_hconfig, child_hconfig, rc) result(total_hconfig)
      type(ESMF_HConfig) :: total_hconfig
      type(ESMF_HConfig), intent(in) :: parent_hconfig
#if defined(ESMF_HCONFIGSET_HAS_INTENT_INOUT)
      type(ESMF_HConfig), intent(inout) :: child_hconfig
#else
      type(ESMF_HConfig), intent(in) :: child_hconfig
#endif
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_HConfigIter) :: iter_begin, iter_end, iter
      character(:), allocatable :: key
      type(ESMF_HConfig) :: val
      logical :: duplicate_key
      _ASSERT(ESMF_HConfigIsMap(parent_hconfig), 'parent hconfig must be a mapping.')
      _ASSERT(ESMF_HConfigIsMap(child_hconfig), 'child hconfig must be a mapping.')
      total_hconfig = ESMF_HConfigCreate(child_hconfig, _RC)
      iter_begin = ESMF_HConfigIterBegin(parent_hconfig, rc=rc)
      iter_end = ESMF_HConfigIterEnd(parent_hconfig, rc=rc)
      iter = iter_begin
      do while (ESMF_HConfigIterLoop(iter, iter_begin, iter_end, rc=status))
         _VERIFY(status)
         ! ignore mapl section
         key = ESMF_HConfigAsStringMapKey(iter, rc=rc)
         if (key == MAPL_SECTION) cycle
         ! ignore duplicate key
         duplicate_key = ESMF_HConfigIsDefined(child_hconfig, keystring=key, _RC)
         if (duplicate_key) cycle
         val = ESMF_HConfigCreateAtMapVal(iter, _RC)
         call ESMF_HConfigSet(child_hconfig, keystring=key, content=val, _RC)
      end do
      _RETURN(_SUCCESS)
   end function merge_hconfig
Call graph
merge_hconfig calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, ESMF_HConfigSet, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_merge_hconfig_bad_parent calls merge_hconfig
test_merge_hconfig_duplicate calls merge_hconfig
test_merge_hconfig_mapl_section calls merge_hconfig
test_merge_hconfig_no_mapl calls merge_hconfig
test_merge_hconfig_problem_child calls merge_hconfig