method_less – MAPL
method_less Function
22 statements
Source File
private function method_less(a, b) result(less)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Method_Flag), intent(in) :: a
type(ESMF_Method_Flag), intent(in) :: b
Return Value logical
Calls
Called by
Source Code
   logical function method_less(a,b) result(less)
      type(ESMF_Method_Flag), intent(in) :: a, b
      associate (idx_a => find(a), idx_b => find(b))
        less = (idx_a < idx_b)
      end associate
   contains
      integer function find(a) result(idx)
         use :: esmf, only: ESMF_METHOD_INITIALIZE, ESMF_METHOD_RUN, ESMF_METHOD_FINALIZE
         use :: esmf, only: ESMF_METHOD_READRESTART, ESMF_METHOD_WRITERESTART
         use :: esmf, only: operator(==)
         type(ESMF_Method_Flag), intent(in) :: a
         type(ESMF_Method_Flag), parameter :: METHODS(*) = [ &
              ESMF_METHOD_INITIALIZE,  &
              ESMF_METHOD_RUN,         &
              ESMF_METHOD_FINALIZE,    &
              ESMF_METHOD_READRESTART, &
              ESMF_METHOD_WRITERESTART]
         integer :: i
         do i = 1, size(METHODS)
            if (a == METHODS(i)) then
               idx = i
               return
            end if
         end do
         idx = -1 ! should not be reachable
      end function find
   end function method_less
Call graph
method_less calls find
find calls map_find_basic
map_key_less_than calls method_less
map_s_insert_single calls map_key_less_than, map_s_find_node, map_s_order_eq
map_s_less_than calls map_key_less_than
map_s_lessthan calls map_key_less_than
map_s_lower_bound calls map_key_less_than, map_s_find_node
map_s_upper_bound calls map_key_less_than, map_s_find_node
map_s_value_compare calls map_key_less_than
operator(lt) calls map_s_less_than
map_s_find_node calls map_s_lessthan, map_s_order_eq
map_s_order_eq calls map_s_lessthan
map_s_equal calls map_s_order_eq
map_s_find calls map_s_find_node, map_s_order_eq