mirror_ungridded_dims – MAPL
mirror_ungridded_dims Function
5 statements
Source File
public function mirror_ungridded_dims() result(spec)
Arguments
None
Return Value type(UngriddedDims)
Called by
Source Code
   function mirror_ungridded_dims() result(spec)
      type(UngriddedDims) :: spec
      spec%dim_specs = UngriddedDimVector()
      spec%is_mirror = .true.
   end function mirror_ungridded_dims
Call graph
register_imports calls mirror_ungridded_dims
test_mirror_ungridded_dims calls mirror_ungridded_dims
setservices calls register_imports