mirror – MAPL
mirror Function
6 statements
Source File
private function mirror(str)
Arguments
Type Intent Optional Attributes Name
character(len=:), allocatable :: str
Return Value logical
Called by
Source Code
   logical function mirror(str)
      character(:), allocatable :: str
      mirror = .not. allocated(str)
      if (mirror) return
      mirror = (str == '_MIRROR_')
   end function mirror
Call graph
connect_to calls mirror, connect_to
match_string calls mirror
match calls match_string
can_connect_units calls match
get_cost_geom calls match
get_cost_string calls match
get_cost_typekind calls match
make_action calls match, make_action
test_connect_unique_mirror calls connect_to
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match
get_cost calls get_cost_geom, get_cost_string, get_cost_typekind
update_item calls update_item_geom, update_item_string, update_item_typekind
can_connect_to calls can_connect_units