MockItemSpec – MAPL
MockItemSpec Function
38 statements
Source File
public function MockItemSpec(value, state_intent, short_name, typekind, units, mirror, time_dependent, supports_conversion) result(mock_spec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: value
type(ESMF_StateIntent_Flag), intent(in), optional :: state_intent
character(len=*), intent(in), optional :: short_name
type(ESMF_TypeKind_Flag), intent(in), optional :: typekind
character(len=*), intent(in), optional :: units
logical, intent(in), optional :: mirror
logical, intent(in), optional :: time_dependent
logical, intent(in), optional :: supports_conversion
Return Value type(StateItemSpec), target
Calls
Called by
Source Code
   function MockItemSpec(value, state_intent, short_name, typekind, units, mirror, time_dependent, supports_conversion) result(mock_spec)
      type(StateItemSpec), target :: mock_spec
      integer, intent(in) :: value
      type(ESMF_StateIntent_Flag), optional, intent(in) :: state_intent
      character(*), optional, intent(in) :: short_name
      type(ESMF_Typekind_Flag), optional, intent(in) :: typekind
      character(*), optional, intent(in) :: units
      logical, optional, intent(in) :: mirror
      logical, optional, intent(in) :: time_dependent
      logical, optional, intent(in) :: supports_conversion
      type(MockAspect) :: mock_aspect
      logical :: mirror_
      logical :: time_dependent_
      logical :: supports_conversion_
      type(ESMF_StateIntent_Flag) :: state_intent_
      type(VariableSpec), target :: var_spec
      character(:), allocatable :: short_name_, units_
      type(VirtualConnectionPtVector) :: dependencies
      type(AspectMap), pointer :: aspects
      type(StateRegistry), target :: registry
      mirror_ = .false.
      if (present(mirror)) mirror_ = mirror
      time_dependent_ = .false.
      if (present(time_dependent)) time_dependent_ = time_dependent
      supports_conversion_ = .false.
      if (present(supports_conversion)) supports_conversion_ = supports_conversion
      state_intent_ = ESMF_STATEINTENT_EXPORT
      if (present(state_intent)) state_intent_ = state_intent
      short_name_ = 'AAA'
      if (present(short_name)) short_name_ = short_name
      units_ = 'barn'
      if (present(units)) units_ = units
      var_spec = make_VariableSpec(state_intent=state_intent_, short_name=short_name_, typekind=typekind, units=units_)
      mock_spec = var_spec%make_StateItemSpec(registry)
      aspects => mock_spec%get_aspects()
      mock_aspect = MockAspect(value, mirror_, time_dependent_, supports_conversion_)
      call aspects%insert(CLASS_ASPECT_ID, mock_aspect)
   end function MockItemSpec
Call graph
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec
make_variablespec calls mapl_return
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_add_extension_spec calls mockitemspec
test_add_primary_spec calls mockitemspec
test_add_to_state calls mockitemspec
test_connect calls mockitemspec
test_do_not_propagate_export_as_import calls mockitemspec
test_do_not_propagate_import calls mockitemspec
test_do_not_propagate_satisfied_import calls mockitemspec
test_find_closest_name calls mockitemspec
test_find_closest_simple calls mockitemspec
test_find_closest_subtype calls mockitemspec
test_link_extension calls mockitemspec
test_link_extension_spec calls mockitemspec
test_propagate_duplicate_import calls mockitemspec
test_propagate_export calls mockitemspec
test_propagate_import calls mockitemspec