modifyTime – MAPL
modifyTime Subroutine
23 statements
Source File
private subroutine modifyTime(this, oClients, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine modifyTime(this, oClients, rc)
        class(MAPL_GriddedIO), intent(inout) :: this
        type (ClientManager), optional, intent(inout) :: oClients
        integer, optional, intent(out) :: rc
        type(Variable) :: v
        type(StringVariableMap) :: var_map
        integer :: status
        if (this%timeInfo%is_initialized) then
           v = this%timeInfo%define_time_variable(_RC)
           call this%metadata%modify_variable('time',v,rc=status)
           _VERIFY(status)
           if (present(oClients)) then
              call var_map%insert('time',v)
              call oClients%modify_metadata(this%write_collection_id, var_map=var_map, rc=status)
              _VERIFY(status)
           end if
        else
           _FAIL("Time was not initialized for the GriddedIO class instance")
        end if
        _RETURN(ESMF_SUCCESS)
     end subroutine modifyTime
Call graph
modifytime calls mapl_assert, insert, define_time_variable, mapl_return, mapl_verify, modify_metadata, modify_variable
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
define_time_variable calls mapl_assert, mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, add_attribute, v_clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modify_metadata calls mapl_return, mapl_verify, current, modify_metadata
modify_variable calls mapl_assert, mapl_return, at, begin, get, next, get_dimensions, map_set_
run calls modifytime
start_new_file calls modifytime
main calls start_new_file
time_ave calls start_new_file
regrid_util calls main