new_RegridderManager – MAPL
new_RegridderManager Function
4 statements
Source File
private function new_RegridderManager() result(mgr)
$ call mgr%add_factory(horzHorzFluxRegridderFactory())
Arguments
None
Return Value type(RegridderManager)
Calls
Called by
Source Code
   function new_RegridderManager() result(mgr)
      type(RegridderManager) :: mgr
      ! Load default factories
      call mgr%add_factory(EsmfRegridderFactory())
!!$      call mgr%add_factory(horzHorzFluxRegridderFactory())
   end function new_RegridderManager
Call graph
new_regriddermanager calls add_factory
add_factory calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
regriddermanager calls new_regriddermanager