new_UngriddedDimsSpec_arr – MAPL
new_UngriddedDimsSpec_arr Function
8 statements
Source File
private function new_UngriddedDimsSpec_arr(dim_specs) result(spec)
Arguments
Type Intent Optional Attributes Name
type(UngriddedDimSpec), intent(in) :: dim_specs(:)
Return Value type(UngriddedDimsSpec)
Calls
Called by
Source Code
   function new_UngriddedDimsSpec_arr(dim_specs) result(spec)
      type(UngriddedDimsSpec) :: spec
      type(UngriddedDimSpec), intent(in) :: dim_specs(:)
      integer :: i
      do i = 1, size(dim_specs)
         call spec%dim_specs%push_back(dim_specs(i))
      end do
   end function new_UngriddedDimsSpec_arr
Call graph
new_ungriddeddimsspec_arr calls vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
ungriddeddimsspec calls new_ungriddeddimsspec_arr