new_DynamicMask_r8 – MAPL
new_DynamicMask_r8 Function
22 statements
Source File
private function new_DynamicMask_r8(mask_type, src_mask_value, dst_mask_value, handleAllElements, rc) result(mask)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mask_type
real(kind=ESMF_KIND_R8), intent(in), optional :: src_mask_value
real(kind=ESMF_KIND_R8), intent(in), optional :: dst_mask_value
logical, optional :: handleAllElements
integer, intent(out), optional :: rc
Return Value type(DynamicMask)
Calls
Called by
Source Code
   function new_DynamicMask_r8(mask_type, src_mask_value, dst_mask_value, handleAllElements, rc) result(mask)
      type(DynamicMask) :: mask
      character(*), intent(in) :: mask_type
      real(kind=ESMF_KIND_R8), optional, intent(in) :: src_mask_value
      real(kind=ESMF_KIND_R8), optional, intent(in) :: dst_mask_value
      logical, optional :: handleAllElements
      integer, optional, intent(out) :: rc
      integer :: status
      type(DynamicMaskSpec) :: spec
      spec%mask_type = mask_type
      if (present(handleAllElements)) spec%handleAllElements = handleAllElements
      spec%src_mask_value_r8 = src_mask_value
      spec%src_mask_value_r4 = spec%src_mask_value_r8
      ! No default for dst_mask_value.  Usually left unallocated
      if (present(dst_mask_value)) then
         spec%dst_mask_value_r8 = dst_mask_value
         spec%dst_mask_value_r4 = dst_mask_value
      end if
      mask = DynamicMask(spec, _RC)
      _RETURN(_SUCCESS)
   end function new_DynamicMask_r8
Call graph
new_dynamicmask_r8 calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
dynamicmask calls new_dynamicmask_r8