new_DynamicMask_r4r8 – MAPL
new_DynamicMask_r4r8 Function
21 statements
Source File
private function new_DynamicMask_r4r8(spec, rc) result(mask)
Arguments
Type Intent Optional Attributes Name
type(DynamicMaskSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(DynamicMask)
Calls
Called by
Source Code
   function new_DynamicMask_r4r8(spec, rc) result(mask)
      type(DynamicMask) :: mask
      type(DynamicMaskSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      procedure(I_r4r8r4), pointer :: mask_routine_r4
      procedure(I_r8r8r8), pointer :: mask_routine_r8
      mask%spec = spec
      allocate(mask%esmf_mask_r4)
      mask_routine_r4 => get_mask_routine_r4(spec%mask_type, _RC)
      call ESMF_DynamicMaskSetR4R8R4V(mask%esmf_mask_r4, mask_routine_r4, &
           dynamicSrcMaskValue=spec%src_mask_value_r4, &
           dynamicDstMaskValue=spec%dst_mask_value_r4, &
           handleAllElements=spec%handleAllElements, &
           _RC)
      allocate(mask%esmf_mask_r8)
      mask_routine_r8 => get_mask_routine_r8(spec%mask_type, _RC)
      call ESMF_DynamicMaskSetR8R8R8V(mask%esmf_mask_r8, mask_routine_r8, &
           dynamicSrcMaskValue=spec%src_mask_value_r8, &
           dynamicDstMaskValue=spec%dst_mask_value_r8, &
           handleAllElements=spec%handleAllElements, &
           _RC)
      _RETURN(_SUCCESS)
   end function new_DynamicMask_r4r8
Call graph
new_dynamicmask_r4r8 calls ESMF_DynamicMaskSetR4R8R4V, ESMF_DynamicMaskSetR8R8R8V, get_mask_routine_r4, get_mask_routine_r8, mapl_return, mapl_verify
get_mask_routine_r4 calls mapl_return, mapl_assert
get_mask_routine_r8 calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
dynamicmask calls new_dynamicmask_r4r8