new_from_yaml – MAPL
new_from_yaml Function
74 statements
Source File
private function new_from_yaml(filename, stream, rc) result(fd)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: filename
character(len=*), intent(in), optional :: stream
integer, intent(out), optional :: rc
Return Value type(FieldDictionary)
Calls
Called by
Source Code
   function new_from_yaml(filename, stream, rc) result(fd)
      type(FieldDictionary) :: fd
      character(len=*), optional, intent(in) :: filename
      character(len=*), optional, intent(in) :: stream
      integer, optional, intent(out) :: rc
      type(ESMF_HConfig), target :: node
      type(ESMF_HConfigIter) :: hconfigIter,hconfigIterBegin,hconfigIterEnd
      integer :: status
      character(:), allocatable :: standard_name
      type(FieldDictionaryItem) :: item
      type(ESMF_HConfig) :: val
      _ASSERT( .not.(present(filename) .and. present(stream)), "cannot specify both")
      if (present(filename)) then
         node = ESMF_HConfigCreate(filename=filename,_RC)
      else if (present(stream)) then
         node = ESMF_HConfigCreate(content=stream,_RC)
      else
         node = ESMF_HConfigCreate(content='{}',_RC)
         _RETURN(_SUCCESS)
      end if
      _ASSERT(ESMF_HConfigIsMap(node), 'FieldDictionary requires a YAML mapping node')
      hconfigIter = ESMF_HConfigIterBegin(node)
      hconfigIterBegin = ESMF_HConfigIterBegin(node)
      hconfigIterEnd = ESMF_HConfigIterEnd(node)
      do while (ESMF_HConfigIterLoop(hconfigIter,hconfigIterBegin,hconfigIterEnd))
         standard_name = ESMF_HConfigAsStringMapKey(hconfigIter,_RC)
         _ASSERT(len_trim(standard_name) /= 0, 'Standard name is all blanks.')
         _ASSERT(fd%entries%count(standard_name) == 0, 'Duplicate standard name: <'//trim(standard_name)//'>')
         val = ESMF_HConfigCreateAtMapVal(hconfigIter,_RC)
         item = to_item(val,_RC)
         call fd%add_item(standard_name, item)
      enddo
      _RETURN(_SUCCESS)
   contains
      function to_item(item_node, rc) result(item)
         type(FieldDictionaryItem) :: item
         type(ESMF_HConfig), intent(in) :: item_node
         integer, optional, intent(out) :: rc
         integer :: status
         type(ESMF_HConfig) :: aliases_node, alias_node
         character(:), allocatable :: long_name, units, temp_string
         type(StringVector) :: aliases
         type(ESMF_HConfigIter) :: hconfigIter,hconfigIterBegin,hconfigIterEnd
         _ASSERT(ESMF_HConfigIsMap(item_node), 'Each node in FieldDictionary yaml must be a mapping node')
         long_name = ESMF_HconfigAsString(item_node,keyString='long_name',_RC)
         units = ESMF_HConfigAsString(item_node,keyString='canonical_units',_RC)
         if (ESMF_HConfigIsDefined(item_node,keyString='aliases')) then
            aliases_node = ESMF_HConfigCreateAt(item_node,keyString='aliases',_RC)
            _ASSERT(ESMF_HConfigIsSequence(aliases_node), "'aliases' must be a sequence")
            hconfigIter = ESMF_HConfigIterBegin(aliases_node)
            hconfigIterBegin = ESMF_HConfigIterBegin(aliases_node)
            hconfigIterEnd = ESMF_HConfigIterEnd(aliases_node)
            do while (ESMF_HConfigIterLoop(hconfigIter,hconfigIterBegin,hconfigIterEnd))
               temp_string = ESMF_HConfigAsString(hconfigIter,_RC)
               call aliases%push_back(temp_string)
            enddo
         end if
         item = FieldDictionaryItem(long_name, units, aliases)
         _RETURN(_SUCCESS)
      end function to_item
   end function new_from_yaml
Call graph
new_from_yaml calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, add_item, mapl_return, mapl_verify, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item calls mapl_return, mapl_verify, insert, add_aliases, get_aliases
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_aliases calls mapl_assert, mapl_return, begin, insert, next, of
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_insert_pair calls insert
fielddictionary calls new_from_yaml