new_GridVectorBasis – MAPL
new_GridVectorBasis Module Function
80 statements
Source File
module function new_GridVectorBasis(geom, inverse, rc) result(basis) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(inout) :: geom
logical, intent(in), optional :: inverse
integer, intent(out), optional :: rc
Return Value type(VectorBasis)
Calls
Called by
Source Code
   module function new_GridVectorBasis(geom, inverse, rc) result(basis)
      type(VectorBasis) :: basis
      type(ESMF_Geom), intent(inout) :: geom
      logical, optional, intent(in) :: inverse
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Grid) :: grid
      type(ESMF_GeomType_Flag) :: geomtype
      logical :: inverse_
      integer :: i, j
      real(kind=ESMF_KIND_R8), allocatable :: centers(:,:,:)
      real(kind=ESMF_KIND_R8), allocatable :: corners(:,:,:)
      inverse_ = .false.
      if (present(inverse)) inverse_ = inverse
      call ESMF_GeomGet(geom, geomtype=geomtype, _RC)
      _ASSERT(geomtype == ESMF_GEOMTYPE_GRID, 'GridVectorBasis is only valid for ESMF_Grid geoms.')
      call ESMF_GeomGet(geom, grid=grid, _RC)
      call create_fields(basis%elements, geom, _RC)
      call GridGetCoords(grid, centers, _RC)
      call GridGetCorners(grid, corners, _RC)
      call fill_fields(basis, centers, corners, inverse_, _RC)
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine fill_fields(basis, centers, corners, inverse, rc)
         type(VectorBasis), intent(inout) :: basis
         real(kind=ESMF_KIND_R8), intent(in) :: centers(:,:,:)
         real(kind=ESMF_KIND_R8), intent(in) :: corners(:,:,:)
         logical, intent(in) :: inverse
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: k1, k2
         integer :: im, jm
         type(Ptr_2d) :: x(NI,NJ)
         im = size(centers,1)
         jm = size(centers,2)
         do k2 = 1, NJ
            do k1 = 1, NI
               call assign_fptr(basis%elements(k1,k2), int([im,jm],kind=ESMF_KIND_I8), x(k1,k2)%ptr, _RC)
            end do
         end do
         do concurrent (i=1:im, j=1:jm)
            associate (local_basis => fill_element(centers(i,j,:), corners(i:i+1,j+j+1,:), inverse) )
              do k2 = 1, NJ
                 do k1 = 1, NI
                    x(k1,k2)%ptr(i,j) = local_basis(k1,k2)
                 end do
              end do
            end associate
         end do
         _RETURN(ESMF_SUCCESS)
      end subroutine fill_fields
      !--------------------------------------
      !
      !   ^ lat
      !   !
      !   !         x c    p4     x  d
      !   !
      !   !
      !   !         p1     C       p3
      !   !
      !   !
      !   !         x a    p2     x  b
      !   !
      !   !
      !   !------------------------------> lon
      !
      !--------------------------------------
      pure function fill_element(center, corners, inverse) result(basis)
         real(kind=ESMF_KIND_R8), intent(in) :: center(2)
         real(kind=ESMF_KIND_R8), intent(in) :: corners(2,2,2) ! last dim is lat/lon
         logical, intent(in) :: inverse
         real(kind=ESMF_KIND_R8) :: basis(NI,2)
         associate ( &
              p1 => mid_pt_sphere(corners(1,1,:),corners(1,2,:)), &
              p2 => mid_pt_sphere(corners(1,1,:),corners(2,1,:)), &
              p3 => mid_pt_sphere(corners(2,1,:),corners(2,2,:)), &
              p4 => mid_pt_sphere(corners(1,2,:),corners(2,2,:)) )
           associate ( &
                e1 => get_unit_vector(p3, center, p1), &
                e2 => get_unit_vector(p4, center, p2) )
             if (.not. inverse) then
                basis(:,1) = e1
                basis(:,2) = e2
                return
             end if
             associate (dot => dot_product(e1, e2))
               basis(:,1) = (e1 - dot*e2) / (1-dot**2)
               basis(:,2) = (e2 - dot*e1) / (1-dot**2)
             end associate
           end associate
         end associate
      end function fill_element
   end function new_GridVectorBasis
Call graph
new_gridvectorbasis calls ESMF_GeomGet, assign_fptr, create_fields, get_unit_vector, gridgetcoords, gridgetcorners, mapl_assert, mid_pt_sphere, mapl_return, mapl_verify, new_gridvectorbasis
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
create_fields calls create_fields
get_unit_vector calls get_unit_vector
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
gridgetcorners calls grid_get_corners
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mid_pt_sphere calls mid_pt_sphere
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
gridvectorbasis calls new_gridvectorbasis
get_basis calls gridvectorbasis