new_outer_meta – MAPL
new_outer_meta Function
11 statements
Source File
private function new_outer_meta(gridcomp, user_gc_driver, hconfig) result(outer_meta)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(in) :: gridcomp
type(GriddedComponentDriver), intent(in) :: user_gc_driver
type(ESMF_HConfig), intent(in) :: hconfig
Return Value type(OuterMetaComponent)
Calls
Called by
Source Code
   type(OuterMetaComponent) function new_outer_meta(gridcomp, user_gc_driver, hconfig) result(outer_meta)
      type(ESMF_GridComp), intent(in) :: gridcomp
      type(GriddedComponentDriver), intent(in) :: user_gc_driver
      type(ESMF_HConfig), intent(in) :: hconfig
      outer_meta%self_gridcomp = gridcomp
      outer_meta%user_gc_driver = user_gc_driver
      outer_meta%hconfig = hconfig
      counter = counter + 1
      outer_meta%counter = counter
      call initialize_phases_map(outer_meta%user_phases_map)
   end function new_outer_meta
Call graph
new_outer_meta calls initialize_phases_map
initialize_phases_map calls insert, stringvector
map_insert_pair calls insert
outermetacomponent calls new_outer_meta