new_ScalarRegridAction – MAPL
new_ScalarRegridAction Function
15 statements
Source File
private function new_ScalarRegridAction(geom_in, f_in, geom_out, f_out) result(action)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom) :: geom_in
type(ESMF_Field), intent(in) :: f_in
type(ESMF_Geom) :: geom_out
type(ESMF_Field), intent(in) :: f_out
Return Value type(ScalarRegridAction)
Calls
Called by
Source Code
   function new_ScalarRegridAction(geom_in, f_in, geom_out, f_out) result (action)
      type(ScalarRegridAction) :: action
      type(ESMF_Geom) :: geom_in
      type(ESMF_Field), intent(in) :: f_in
      type(ESMF_Geom) :: geom_out
      type(ESMF_Field), intent(in) :: f_out
      type(RegridderSpec) :: spec
      type(RegridderManager), pointer :: regridder_manager
      integer :: status
      regridder_manager => get_regridder_manager()
      spec = RegridderSpec(EsmfRegridderParam(), geom_in, geom_out)
      action%regrdr => regridder_manager%get_regridder(spec, rc=status)
      action%f_in = f_in
      action%f_out = f_out
   end function new_ScalarRegridAction
Call graph
new_scalarregridaction calls esmfregridderparam, get_regridder, get_regridder_manager
get_regridder calls find, of, add_regridder, make_regridder, mapl_return, mapl_verify, vector_back, vector_begin
add_regridder calls vector_push_back
make_regridder calls mapl_return, mapl_verify, mapl_assert, make_regridder, of, get_param, supports
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
vector_push_back calls resize, vector_grow_to
regridaction calls new_scalarregridaction
make_action calls regridaction, make_action