new_NS_Basis – MAPL
new_NS_Basis Module Function
50 statements
Source File
module function new_NS_Basis(geom, rc) result(basis) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(inout) :: geom
integer, intent(out), optional :: rc
Return Value type(VectorBasis)
Calls
Called by
Source Code
   module function new_NS_Basis(geom, rc) result(basis)
      type(VectorBasis) :: basis
      type(ESMF_Geom), intent(inout) :: geom
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=ESMF_KIND_R8), pointer :: longitudes(:)
      real(kind=ESMF_KIND_R8), pointer :: latitudes(:)
      call create_fields(basis%elements, geom, _RC)
      call MAPL_GeomGetCoords(geom, longitudes, latitudes, _RC)
      call fill_fields(basis, longitudes, latitudes, _RC)
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine fill_fields(basis, longitudes, latitudes, rc)
         type(VectorBasis), intent(inout) :: basis
         real(kind=ESMF_KIND_R8), intent(in) :: longitudes(:)
         real(kind=ESMF_KIND_R8), intent(in) :: latitudes(:)
         integer, optional, intent(out) :: rc
         integer :: status
         type(Ptr_1d) :: x(NI,NJ)
         integer :: i, j, n
         real(kind=ESMF_KIND_R8) :: local_basis(NI,NJ)
         do j = 1, NJ
            do i = 1, NI
               call assign_fptr(basis%elements(i,j), x(i,j)%ptr, _RC)
            end do
         end do
         do n = 1, size(x(1,1)%ptr)
            local_basis = fill_element(longitudes(i), latitudes(i))
            do j = 1, NJ
               do i = 1, NI
                  x(i,j)%ptr(n) = local_basis(i,j)
               end do
            end do
         end do
         _RETURN(ESMF_SUCCESS)
      end subroutine fill_fields
      pure function fill_element(longitude, latitude) result(x)
         real(kind=ESMF_KIND_R8) :: x(NI,NJ)
         real(kind=ESMF_KIND_R8), intent(in) :: longitude
         real(kind=ESMF_KIND_R8), intent(in) :: latitude
         x(:,1) = [ -sin(longitude), cos(longitude), 0._ESMF_KIND_R8 ]
         x(:,2) = [ -sin(latitude)*cos(longitude), -sin(latitude)*sin(longitude), cos(latitude) ]
      end function fill_element
   end function new_NS_Basis
Call graph
new_ns_basis calls assign_fptr, create_fields, mapl_geomgetcoords, mapl_return, mapl_verify, new_ns_basis
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
create_fields calls create_fields, mapl_return, mapl_verify, ESMF_GeomGet, esmf_fieldcreate, mapl_assert
mapl_geomgetcoords calls mapl_geomgetcoords, mapl_return, mapl_verify, ESMF_GeomGet, ESMF_LocStreamGetKey, gridgetcoords, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
gridgetcoords calls grid_get_centers, grid_get_coords_1d, grid_get_coords_2d
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
ns_vectorbasis calls new_ns_basis
get_basis calls ns_vectorbasis