new_DSOSetServices – MAPL
new_DSOSetServices Function
11 statements
Source File
private function new_DSOSetServices(sharedObj, userRoutine) result(dso_setservices)
Uses
mapl_DSO_Utilities
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: sharedObj
character(len=*), intent(in), optional :: userRoutine
Return Value type(DSOSetServices)
Called by
Source Code
   function new_DSOSetServices(sharedObj, userRoutine) result(dso_setservices)
      use mapl_DSO_Utilities
      type(DSOSetServices) :: dso_setservices
      character(len=*), intent(in) :: sharedObj
      character(len=*), optional, intent(in) :: userRoutine
      character(:), allocatable :: userRoutine_
      userRoutine_ = 'setservices_' ! unless
      if (present(userRoutine)) userRoutine_ = userRoutine
      dso_setservices%sharedObj   = sharedObj
      dso_setservices%userRoutine = userRoutine_
   end function new_DSOSetServices
Call graph
user_setservices calls new_dsosetservices
make_driver calls user_setservices
parse_child calls user_setservices
parse_setservices calls user_setservices
setservices calls user_setservices
setup calls user_setservices
test_equal_child_spec_cfg_differs calls user_setservices
test_equal_child_spec_ss_differs calls user_setservices
test_is_generic calls user_setservices
test_mapl_invalid_name calls user_setservices
test_parse_childspec_basic calls user_setservices
test_parse_childspec_with_config_file calls user_setservices
test_parse_childspecmap_1 calls user_setservices
test_parse_childspecmap_2 calls user_setservices