new_v_pt – MAPL
new_v_pt Function
5 statements
Source File
public function new_v_pt(state_intent, short_name) result(v_pt)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: state_intent
character(len=*), intent(in) :: short_name
Return Value type(VirtualConnectionPt)
Called by
Source Code
   function new_v_pt(state_intent, short_name) result(v_pt)
      type(VirtualConnectionPt) :: v_pt
      character(*), intent(in) :: state_intent, short_name
      v_pt = VirtualConnectionPt(state_intent=state_intent, short_name=short_name)
   end function new_v_pt
Call graph
new_a_pt calls new_v_pt
test_connect_chain calls new_v_pt
test_connect calls new_v_pt
test_do_not_propagate_import calls new_v_pt
test_e2e_preserve_actual_pt calls new_v_pt
test_export_to_export_connection calls new_v_pt
test_import_from_child calls new_v_pt
test_import_from_parent calls new_v_pt
test_internal_to_export_connection calls new_v_pt
test_multi_import calls new_v_pt, new_a_pt
test_propagate_import calls new_v_pt
test_sibling_activation calls new_v_pt
test_add_item_duplicate_fail calls new_a_pt
test_create_extension calls new_a_pt
test_get_item_spec_found calls new_a_pt
test_get_item_spec_multi calls new_a_pt
test_get_item_spec_not_found calls new_a_pt
test_internal_activation calls new_a_pt