new_StateItemSpec – MAPL
new_StateItemSpec Function
7 statements
Source File
public function new_StateItemSpec(aspects, dependencies) result(spec)
Arguments
Type Intent Optional Attributes Name
type(AspectMap), intent(in) :: aspects
type(VirtualConnectionPtVector), intent(in) :: dependencies
Return Value type(StateItemSpec)
Called by
Source Code
   function new_StateItemSpec(aspects, dependencies) result(spec)
      type(StateItemSpec) :: spec
      type(AspectMap), intent(in) :: aspects
      type(VirtualConnectionPtVector), intent(in) :: dependencies
      spec%aspects = aspects
      spec%dependencies = dependencies
   end function new_StateItemSpec
Call graph
stateitemspec calls new_stateitemspec
mockitemspec calls make_stateitemspec
setup_ calls make_stateitemspec
test_allocate calls make_stateitemspec
setup calls setup_
test_add_extension_spec calls mockitemspec
test_add_primary_spec calls mockitemspec
test_add_to_state calls mockitemspec
test_connect calls mockitemspec
test_do_not_propagate_export_as_import calls mockitemspec
test_do_not_propagate_import calls mockitemspec
test_do_not_propagate_satisfied_import calls mockitemspec
test_find_closest_name calls mockitemspec
test_find_closest_simple calls mockitemspec
test_find_closest_subtype calls mockitemspec
test_link_extension calls mockitemspec
test_link_extension_spec calls mockitemspec
test_propagate_duplicate_import calls mockitemspec
test_propagate_export calls mockitemspec
test_propagate_import calls mockitemspec
test_created_fields_have_num_levels calls setup
test_get_coordinate_field_change_units_center calls setup
test_get_coordinate_field_change_units_edge calls setup
test_get_coordinate_field_simple calls setup