new_MAPL_Cap_from_set_services – MAPL
new_MAPL_Cap_from_set_services Function
33 statements
Source File
private function new_MAPL_Cap_from_set_services(name, set_services, unusable, cap_options, rc) result(cap)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
procedure :: set_services
class(KeywordEnforcer), intent(in), optional :: unusable
type(MAPL_CapOptions), intent(in), optional :: cap_options
integer, intent(out), optional :: rc
Return Value type(MAPL_Cap)
Calls
Called by
Source Code
   function new_MAPL_Cap_from_set_services(name, set_services, unusable, cap_options, rc) result(cap)
      type (MAPL_Cap) :: cap
      character(*), intent(in) :: name
      procedure() :: set_services
      class (KeywordEnforcer),  optional, intent(in) :: unusable
      type ( MAPL_CapOptions), optional, intent(in) :: cap_options
      integer, optional, intent(out) :: rc
      integer :: status
      cap%name = name
      cap%set_services => set_services
      cap%non_dso = .true.
      if (present(cap_options)) then
         allocate(cap%cap_options, source = cap_options)
      else
         allocate(cap%cap_options, source = MAPL_CapOptions())
      endif
      if (cap%cap_options%use_comm_world) then
         cap%comm_world       = MPI_COMM_WORLD
         cap%cap_options%comm = MPI_COMM_WORLD
      else
         cap%comm_world = cap%cap_options%comm
      endif
      call cap%initialize_mpi(rc=status)
      _VERIFY(status)
      call MAPL_Initialize(comm=cap%comm_world, &
                           logging_config=cap%cap_options%logging_config, &
                           rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
    end function new_MAPL_Cap_from_set_services
Call graph
new_mapl_cap_from_set_services calls initialize_mpi, mapl_initialize, mapl_return, mapl_verify
initialize_mpi calls mapl_return, mapl_verify, ESMF_InitializePreMPI, mapl_assert, mpi_comm_rank, mpi_comm_size, mpi_init_thread
mapl_initialize calls mapl_return, mapl_verify, initialize_profiler, initialize_pflogger
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
initialize_pflogger calls mapl_return, mapl_verify, mpi_comm_rank, basic_config, filehandler, load_file, mpiformatter, mpilock, get_logger, initialize, warning, push_back, set_formatter, set_level, set_lock, streamhandler
mapl_throw_exception calls initialize
mapl_cap calls new_mapl_cap_from_set_services