newExtDataDriver – MAPL
newExtDataDriver Function
25 statements
Source File
public function newExtDataDriver(name, set_services, unusable, cap_options, rc) result(driver)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
procedure :: set_services
class(KeywordEnforcer), intent(in), optional :: unusable
class(MAPL_CapOptions), intent(in), optional :: cap_options
integer, intent(out), optional :: rc
Return Value type(ExtDataDriver)
Calls
Called by
Source Code
   function newExtDataDriver(name,set_services, unusable, cap_options, rc) result(driver)
      type(ExtDataDriver) :: driver
      character(*), intent(in) :: name
      procedure() :: set_services
      class(KeywordEnforcer),  optional, intent(in) :: unusable
      class(MAPL_CapOptions), optional, intent(in) :: cap_options
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      driver%name = name
      driver%set_services => set_services
      if (present(cap_options)) then
         driver%cap_options = cap_options
      else
         driver%cap_options = MAPL_CapOptions()
      endif
      call driver%initialize_mpi()
      call MAPL_Initialize(comm=MPI_COMM_WORLD, &
           logging_config=driver%cap_options%logging_config, &
           rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function newExtDataDriver
Call graph
newextdatadriver calls initialize_mpi, mapl_initialize, mapl_return, mapl_verify
initialize_mpi calls mapl_return, mapl_verify, mapl_assert, mpi_comm_rank, mpi_comm_size, mpi_init
mapl_initialize calls mapl_return, mapl_verify, initialize_profiler, initialize_pflogger
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
initialize_pflogger calls mapl_return, mapl_verify, mpi_comm_rank, basic_config, filehandler, load_file, mpiformatter, mpilock, get_logger, initialize, warning, push_back, set_formatter, set_level, set_lock, streamhandler
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
extdatadriver calls newextdatadriver