omap_I_s_has_child – MAPL
omap_I_s_has_child Function
6 statements
Source File
private function omap_I_s_has_child(this, side) result(has_child)
Type Bound
omap_I_s_Node
Arguments
Type Intent Optional Attributes Name
class(omap_I_s_Node), intent(in) :: this
integer, intent(in) :: side
Return Value logical
Called by
Call graph
omap_i_s_erase_range calls omap_i_s_has_child, omap_i_s_rebalance, omap_i_s_erase_nonleaf
omap_i_s_rebalance calls omap_i_s_has_child
omap_i_s_verify calls omap_i_s_has_child
omap_i_s_erase_nonleaf calls omap_i_s_rebalance
omap_i_s_insert_single calls omap_i_s_rebalance
omap_i_erase_iter calls erase
omap_i_erase_range calls erase
omap_i_s_erase_iter calls erase
omap_i_s_erase_value calls erase
omap_i_s_merge calls erase