omap_I_erase_key – MAPL
omap_I_erase_key Function
13 statements
Source File
private function omap_I_erase_key(this, k) result(n)
Type Bound
omap_Map
Arguments
Type Intent Optional Attributes Name
class(omap_Map), intent(inout) :: this
character(len=*), intent(in) :: k
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Call graph
omap_i_erase_key calls erase, omap_i_find
omap_i_find calls omap_i_s_find
omap_i_erase_range calls erase
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan