omap_I_s_insert_single – MAPL
omap_I_s_insert_single Subroutine
53 statements
Source File
private recursive subroutine omap_I_s_insert_single(this, value, unused, is_new, iter)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(inout), target :: this
type(GriddedComponentDriverPair), intent(in) :: value
type(KeywordEnforcer), optional :: unused
logical, intent(out), optional :: is_new
type(omap_I_SetIterator), intent(out), optional :: iter
Calls
Call graph
omap_i_s_insert_single calls omap_i_key_less_than, omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_rebalance, omap_i_s_set_child, omap_i_s_set_parent, omap_i_s_set_value, to_node
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, to_node, omap_i_s_get_child, omap_i_s_lessthan
omap_i_s_order_eq calls omap_i_s_lessthan
omap_i_s_rebalance calls get_height, omap_i_s_get_child, omap_i_s_has_child, omap_i_s_rot, omap_i_s_update_height
omap_i_s_lessthan calls omap_i_key_less_than
omap_i_s_rot calls omap_i_s_set_parent, omap_i_s_get_child, omap_i_s_update_height, omap_i_s_which_side_am_i
omap_i_s_update_height calls get_height
omap_i_s_which_side_am_i calls omap_i_s_get_parent, omap_i_s_which_child