omap_I_iter_prev_n_default – MAPL
omap_I_iter_prev_n_default Function
11 statements
Source File
private function omap_I_iter_prev_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_MapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(omap_MapIterator)
Calls
Called by
Call graph
omap_i_iter_prev_n_default calls omap_i_iter_prev
omap_i_iter_prev calls omap_i_s_iter_prev
omap_i_s_iter_prev calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node
prev calls omap_i_iter_prev_n_default