omap_I_iter_next – MAPL
omap_I_iter_next Subroutine
4 statements
Source File
private recursive subroutine omap_I_iter_next(this)
Type Bound
omap_MapIterator
Arguments
Type Intent Optional Attributes Name
class(omap_MapIterator), intent(inout) :: this
Calls
Called by
Call graph
omap_i_iter_next calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_find_if calls omap_i_iter_next
omap_i_find_if_not calls omap_i_iter_next
omap_i_iter_advance_default calls omap_i_iter_next
omap_i_iter_advance_size_kind calls omap_i_iter_next
omap_i_iter_next_n_default calls omap_i_iter_next
omap_i_iter_next_n_size_kind calls omap_i_iter_next
advance calls omap_i_iter_advance_default, omap_i_iter_advance_size_kind
find_if_not calls omap_i_find_if_not
find_if calls omap_i_find_if
next calls omap_i_iter_next_n_default, omap_i_iter_next_n_size_kind