omap_I_at_rc – MAPL
omap_I_at_rc Function
16 statements
Source File
private function omap_I_at_rc(this, key, rc) result(res)
Type Bound
omap_Map
Arguments
Type Intent Optional Attributes Name
class(omap_Map), intent(in), target :: this
character(len=*), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(GriddedComponentDriver), pointer
Calls
Called by
Call graph
omap_i_at_rc calls omap_i_find
omap_i_find calls omap_i_s_find
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan
omap_at_rc calls at
omap_insert_key_value calls at
omap_set_ calls at
add_child_by_name calls insert
get_child_by_name calls at
omap_insert_pair calls insert
omap_new_omap_initializer_list calls insert