omap_I_s_get_child – MAPL
omap_I_s_get_child Function
24 statements
Source File
private function omap_I_s_get_child(this, side) result(child)
Type Bound
omap_I_s_Node
Arguments
Type Intent Optional Attributes Name
class(omap_I_s_Node), intent(in), target :: this
integer, intent(in) :: side
Return Value type(omap_I_s_Node), pointer
Called by
Call graph
omap_i_s_advpos calls omap_i_s_get_child
omap_i_s_erase_nonleaf calls omap_i_s_get_child, omap_i_s_advpos, omap_i_s_rebalance
omap_i_s_find_node calls omap_i_s_get_child
omap_i_s_rebalance calls omap_i_s_get_child, omap_i_s_rot
omap_i_s_rot calls omap_i_s_get_child
omap_i_s_verify calls omap_i_s_get_child
omap_i_s_which_child calls omap_i_s_get_child
omap_i_s_erase_range calls omap_i_s_erase_nonleaf, omap_i_s_rebalance, omap_i_s_which_child
omap_i_s_find calls omap_i_s_find_node
omap_i_s_insert_single calls omap_i_s_find_node, omap_i_s_rebalance
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_iter_prev calls omap_i_s_advpos
omap_i_s_lower_bound calls omap_i_s_find_node
omap_i_s_upper_bound calls omap_i_s_find_node
omap_i_s_which_side_am_i calls omap_i_s_which_child