omap_I_s_update_height – MAPL
omap_I_s_update_height Subroutine
10 statements
Source File
private subroutine omap_I_s_update_height(this)
Type Bound
omap_I_s_Node
Arguments
Type Intent Optional Attributes Name
class(omap_I_s_Node), intent(inout) :: this
Calls
Called by
Call graph
omap_i_s_update_height calls get_height
omap_i_s_rebalance calls omap_i_s_update_height, omap_i_s_rot
omap_i_s_rot calls omap_i_s_update_height
omap_i_s_erase_nonleaf calls omap_i_s_rebalance
omap_i_s_erase_range calls omap_i_s_rebalance, omap_i_s_erase_nonleaf
omap_i_s_insert_single calls omap_i_s_rebalance
omap_i_erase_iter calls erase
omap_i_erase_range calls erase
omap_i_s_erase_iter calls erase
omap_i_s_erase_value calls erase
omap_i_s_merge calls erase