omap_K_reverse_find_if – MAPL
omap_K_reverse_find_if Function
18 statements
Source File
private function omap_K_reverse_find_if(first, last, p) result(it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: first
type(omap_VectorRIterator), intent(in) :: last
private function p(item)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: item
Return Value logical
Return Value type(omap_VectorRIterator)
Calls
Called by
Call graph
omap_k_reverse_find_if calls of, omap_k_riter_next
omap_k_riter_next calls omap_k_iter_prev
omap_k_riter_of_offset_default calls of
find_if calls omap_k_reverse_find_if