omap_I_s_iter_prev – MAPL
omap_I_s_iter_prev Subroutine
4 statements
Source File
private subroutine omap_I_s_iter_prev(this)
Type Bound
omap_I_SetIterator
Arguments
Type Intent Optional Attributes Name
class(omap_I_SetIterator), intent(inout) :: this
Calls
Called by
Call graph
omap_i_s_iter_prev calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_iter_prev calls omap_i_s_iter_prev
omap_i_s_iter_prev_n_default calls omap_i_s_iter_prev
omap_i_s_iter_prev_n_size_kind calls omap_i_s_iter_prev
prev calls omap_i_s_iter_prev_n_default, omap_i_s_iter_prev_n_size_kind, omap_i_iter_prev_n_default, omap_i_iter_prev_n_size_kind
omap_i_iter_prev_n_default calls omap_i_iter_prev
omap_i_iter_prev_n_size_kind calls omap_i_iter_prev