omap_K_iter_add_n_size_kind – MAPL
omap_K_iter_add_n_size_kind Subroutine
6 statements
Source File
private subroutine omap_K_iter_add_n_size_kind(this, n)
Type Bound
omap_VectorIterator
Arguments
Type Intent Optional Attributes Name
class(omap_VectorIterator), intent(inout) :: this
integer(kind=selected_int_kind(18)), intent(in) :: n
Called by
Call graph
omap_k_iter_a_plus_n_default calls add
omap_k_iter_a_plus_n_size_kind calls add
omap_k_iter_advance_default calls add
omap_k_iter_advance_size_kind calls add
omap_k_iter_n_plus_a_default calls add
omap_k_iter_n_plus_a_size_kind calls add
omap_k_iter_next_n_default calls add
omap_k_iter_next_n_size_kind calls add
omap_k_riter_sub_n_default calls add
omap_k_riter_sub_n_size_kind calls add
advance calls omap_k_iter_advance_default, omap_k_iter_advance_size_kind
next calls omap_k_iter_next_n_default, omap_k_iter_next_n_size_kind
operator(+) calls omap_k_iter_a_plus_n_default, omap_k_iter_a_plus_n_size_kind, omap_k_iter_n_plus_a_default, omap_k_iter_n_plus_a_size_kind
omap_k_riter_prev_n_default calls sub
omap_k_riter_prev_n_size_kind calls sub