omap_I_s_ftn_begin – MAPL
omap_I_s_ftn_begin Function
6 statements
Source File
private function omap_I_s_ftn_begin(this) result(begin)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(in), target :: this
Return Value type(omap_I_SetIterator)
Called by
Call graph
omap_i_ftn_begin calls omap_i_s_ftn_begin
omap_i_s_iter_ftn_begin calls omap_i_s_ftn_begin
ftn_begin calls omap_i_s_iter_ftn_begin, omap_i_iter_ftn_begin
omap_i_iter_ftn_begin calls omap_i_ftn_begin