omap_K_begin – MAPL
omap_K_begin Function
10 statements
Source File
private function omap_K_begin(this) result(iter)
Type Bound
omap_Vector
Arguments
Type Intent Optional Attributes Name
class(omap_Vector), intent(in), target :: this
Return Value type(omap_VectorIterator)
Called by
Call graph
omap_begin calls omap_k_begin
omap_erase_key calls omap_k_begin
omap_find calls omap_k_begin
omap_k_iter_begin calls omap_k_begin
omap_k_iter_ftn_begin calls omap_k_begin
omap_k_rend calls omap_k_begin
begin calls omap_k_iter_begin, omap_iter_begin
ftn_begin calls omap_k_iter_ftn_begin
apply_to_children_custom calls omap_begin
finalize calls omap_begin, finalize
omap_iter_begin calls omap_begin
apply_to_children calls apply_to_children_custom
test_finalize_children calls finalize
initialize_advertise calls apply_to_children
initialize_geom calls apply_to_children