omap_I_s_iter_ftn_end – MAPL
omap_I_s_iter_ftn_end Function
5 statements
Source File
private function omap_I_s_iter_ftn_end(cont) result(end)
Arguments
Type Intent Optional Attributes Name
type(omap_I_Set), intent(in), target :: cont
Return Value type(omap_I_SetIterator)
Calls
Called by
Call graph
omap_i_s_iter_ftn_end calls omap_i_s_ftn_end
omap_i_s_ftn_end calls next, omap_i_s_begin
next calls omap_iter_next_1, omap_iter_next_n_default, omap_iter_next_n_size_kind
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_iter_next_1 calls next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next
ftn_end calls omap_i_s_iter_ftn_end