omap_I_s_count – MAPL
omap_I_s_count Function
12 statements
Source File
private function omap_I_s_count(this, value) result(count)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(in), target :: this
type(GriddedComponentDriverPair), intent(in) :: value
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Call graph
omap_i_s_count calls omap_i_s_find
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan
omap_i_s_lessthan calls omap_i_key_less_than