omap_I_find – MAPL
omap_I_find Function
9 statements
Source File
private function omap_I_find(this, key) result(iter)
Type Bound
omap_Map
Arguments
Type Intent Optional Attributes Name
class(omap_Map), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(omap_MapIterator)
Calls
Called by
Call graph
omap_i_find calls omap_i_s_find
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan
omap_i_s_lessthan calls omap_i_key_less_than
omap_erase_iter calls omap_i_find
omap_i_at_rc calls omap_i_find
omap_i_erase_key calls omap_i_find
omap_iter_at calls omap_i_find
omap_iter_first calls omap_iter_at
omap_iter_second calls omap_iter_at
omap_at_rc calls at
omap_insert_key_value calls at
omap_set_ calls at
run_children_ calls omap_iter_first