omap_ftn_end – MAPL
omap_ftn_end Function
6 statements
Source File
private function omap_ftn_end(this) result(iter)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(in), target :: this
Return Value type(GriddedComponentDriverMapIterator)
Calls
Called by
Call graph
omap_ftn_end calls omap_k_ftn_end
omap_iter_ftn_end calls omap_ftn_end
recurse_ calls omap_ftn_end
run_children_ calls omap_ftn_end
run_clock_advance calls omap_ftn_end
ftn_end calls omap_iter_ftn_end
recurse calls recurse_
run calls run_clock_advance, run_children, run
initialize_advertise calls recurse
initialize_geom calls recurse
initialize_post_advertise calls recurse
initialize_realize calls recurse
initialize_user calls recurse
run_children calls run_children
mapl_runchildren calls run_children
initialize calls initialize_advertise, initialize_geom, initialize_post_advertise, initialize_realize, initialize_user
test_init_children calls initialize_user