omap_insert_key_value – MAPL
omap_insert_key_value Subroutine
13 statements
Source File
private recursive subroutine omap_insert_key_value(this, key, value)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(inout) :: this
character(len=*), intent(in) :: key
type(GriddedComponentDriver), intent(in) :: value
Calls
Called by
Call graph
omap_insert_key_value calls at, insert, omap_k_push_back
omap_k_push_back calls resize, omap_k_grow_to
omap_i_at_rc calls omap_i_find
omap_i_insert_pair calls insert
omap_k_grow_to calls omap_k_capacity, omap_k_set_capacity
omap_i_find calls omap_i_s_find
omap_k_resize_size_kind calls reserve
add_child_by_name calls insert, add_child_by_name
omap_insert_pair calls insert
omap_new_omap_initializer_list calls insert
griddedcomponentdrivermap calls omap_new_omap_initializer_list