omap_iter_first – MAPL
omap_iter_first Function
11 statements
Source File
private function omap_iter_first(this) result(first)
Type Bound
GriddedComponentDriverMapIterator
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Calls
Called by
Call graph
omap_iter_first calls omap_iter_at
omap_iter_at calls of, omap_i_find
omap_i_find calls omap_i_s_find
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
run_children_ calls omap_iter_first
run calls run_children
run_children calls run_children
mapl_runchildren calls run_children