omap_K_riter_add_n_size_kind – MAPL
omap_K_riter_add_n_size_kind Subroutine
6 statements
Source File
private subroutine omap_K_riter_add_n_size_kind(this, n)
Type Bound
omap_VectorRIterator
Arguments
Type Intent Optional Attributes Name
class(omap_VectorRIterator), intent(inout) :: this
integer(kind=selected_int_kind(18)), intent(in) :: n
Calls
Called by
Call graph
omap_k_riter_add_n_size_kind calls sub
omap_k_riter_advance_default calls add
omap_k_riter_advance_size_kind calls add
omap_k_riter_next_n_default calls add
omap_k_riter_next_n_size_kind calls add
advance calls omap_k_riter_advance_default, omap_k_riter_advance_size_kind
next calls omap_k_riter_next_n_default, omap_k_riter_next_n_size_kind