omap_K_resize_size_kind – MAPL
omap_K_resize_size_kind Subroutine
42 statements
Source File
private subroutine omap_K_resize_size_kind(this, count, unused, value, rc)
Type Bound
omap_Vector
Arguments
Type Intent Optional Attributes Name
class(omap_Vector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: count
type(KeywordEnforcer), intent(in), optional :: unused
character(len=*), intent(in), optional :: value
integer, intent(out), optional :: rc
Calls
Called by
Call graph
omap_k_resize_size_kind calls reserve
omap_k_reserve_size_kind calls omap_k_capacity, omap_k_max_size, omap_k_set_capacity
omap_k_new_vector_copy calls resize
omap_k_new_vector_fill_default calls resize
omap_k_new_vector_fill_size_kind calls resize
omap_k_push_back calls resize
omap_k_resize_default calls resize
omap_vector calls omap_k_new_vector_copy, omap_k_new_vector_fill_default, omap_k_new_vector_fill_size_kind, omap_k_new_vector_range
omap_insert_key_value calls omap_k_push_back
omap_k_new_vector_range calls omap_k_push_back
omap_set_ calls omap_k_push_back