omap_K_set_capacity – MAPL
omap_K_set_capacity Subroutine
21 statements
Source File
private subroutine omap_K_set_capacity(this, capacity)
Type Bound
omap_Vector
Arguments
Type Intent Optional Attributes Name
class(omap_Vector), intent(inout), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Called by
Call graph
omap_k_grow_to calls omap_k_set_capacity
omap_k_reserve_size_kind calls omap_k_set_capacity
omap_k_shrink_to_fit calls omap_k_set_capacity
omap_k_insert_count_size_kind calls omap_k_grow_to
omap_k_insert_range calls omap_k_grow_to
omap_k_push_back calls omap_k_grow_to
omap_insert_key_value calls omap_k_push_back
omap_k_new_vector_range calls omap_k_push_back
omap_k_reserve_default calls reserve
omap_k_resize_size_kind calls reserve
omap_set_ calls omap_k_push_back
omap_vector calls omap_k_new_vector_range
omap_k_insert_count_default calls insert
omap_k_insert_one calls insert