omap_I_s_erase_range – MAPL
omap_I_s_erase_range Function
30 statements
Source File
private function omap_I_s_erase_range(this, first, last) result(next_iter)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(inout) :: this
type(omap_I_SetIterator), intent(in) :: first
type(omap_I_SetIterator), intent(in) :: last
Return Value type(omap_I_SetIterator)
Calls
Called by
Call graph
omap_i_s_erase_range calls omap_i_s_deallocate_child, omap_i_s_erase_nonleaf, omap_i_s_get_parent, omap_i_s_has_child, omap_i_s_iter_next, omap_i_s_rebalance, omap_i_s_which_child
omap_i_s_erase_nonleaf calls omap_i_s_rebalance, omap_i_s_advpos, omap_i_s_get_child, omap_i_s_which_side_am_i, set_parent
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_rebalance calls omap_i_s_has_child, get_height, omap_i_s_get_child, omap_i_s_rot, omap_i_s_update_height
omap_i_s_which_child calls omap_i_s_get_child
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_s_rot calls omap_i_s_get_child, omap_i_s_update_height, omap_i_s_which_side_am_i, omap_i_s_set_parent
omap_i_s_update_height calls get_height
omap_i_s_which_side_am_i calls omap_i_s_get_parent, omap_i_s_which_child
omap_i_erase_iter calls erase
omap_i_erase_range calls erase
omap_i_s_erase_iter calls erase
omap_i_s_erase_value calls erase
omap_i_s_merge calls erase
omap_erase_iter calls erase
omap_erase_key calls erase
omap_i_erase_key calls erase