omap_I_s_advpos – MAPL
omap_I_s_advpos Subroutine
27 statements
Source File
private recursive subroutine omap_I_s_advpos(this, pos, dir)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(in), target :: this
type(omap_I_s_Node), intent(inout), pointer :: pos
integer, intent(in) :: dir
Calls
Called by
Call graph
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_s_erase_nonleaf calls omap_i_s_advpos
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_iter_prev calls omap_i_s_advpos
omap_i_iter_next calls omap_i_s_iter_next
omap_i_iter_prev calls omap_i_s_iter_prev
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_deep_copy calls omap_i_s_iter_next
omap_i_s_equal calls omap_i_s_iter_next
omap_i_s_erase_iter calls omap_i_s_iter_next
omap_i_s_erase_range calls omap_i_s_erase_nonleaf, omap_i_s_iter_next
omap_i_s_find_if calls omap_i_s_iter_next
omap_i_s_find_if_not calls omap_i_s_iter_next
omap_i_s_insert_range calls omap_i_s_iter_next
omap_i_s_iter_advance_default calls omap_i_s_iter_next
omap_i_s_iter_advance_size_kind calls omap_i_s_iter_next
omap_i_s_iter_next_n_default calls omap_i_s_iter_next
omap_i_s_iter_next_n_size_kind calls omap_i_s_iter_next
omap_i_s_iter_prev_n_default calls omap_i_s_iter_prev
omap_i_s_iter_prev_n_size_kind calls omap_i_s_iter_prev
omap_i_s_less_than calls omap_i_s_iter_next
omap_i_s_lower_bound calls omap_i_s_iter_next
omap_i_s_merge calls omap_i_s_iter_next
omap_i_s_upper_bound calls omap_i_s_iter_next
omap_i_s_verify calls omap_i_s_iter_next