omap_erase_key – MAPL
omap_erase_key Function
18 statements
Source File
private function omap_erase_key(this, k) result(n)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(inout) :: this
character(len=*), intent(in) :: k
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Call graph
omap_erase_key calls find, erase, omap_k_begin, omap_of
find calls omap_k_reverse_find_basic
omap_of calls omap_i_of
omap_i_erase_range calls erase
omap_i_of calls insert, omap_i_s_iter_of
omap_k_reverse_find_basic calls of, omap_k_riter_next
omap_i_s_iter_of calls omap_i_s_get_value
omap_k_riter_next calls omap_k_iter_prev