omap_K_new_vector_range – MAPL
omap_K_new_vector_range Function
11 statements
Source File
private function omap_K_new_vector_range(first, last) result(v)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorIterator), intent(in) :: first
type(omap_VectorIterator), intent(in) :: last
Return Value type(omap_Vector)
Calls
Called by
Call graph
omap_k_new_vector_range calls of, omap_k_push_back
omap_k_push_back calls resize, omap_k_grow_to
omap_k_grow_to calls omap_k_capacity, omap_k_set_capacity
omap_k_resize_size_kind calls reserve
omap_vector calls omap_k_new_vector_range