omap_insert_pair – MAPL
omap_insert_pair Subroutine
5 statements
Source File
private recursive subroutine omap_insert_pair(this, p)
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(inout) :: this
type(GriddedComponentDriverPair), intent(in) :: p
Calls
Call graph
omap_insert_pair calls insert
omap_insert_key_value calls at, insert, omap_k_push_back
omap_k_push_back calls resize, omap_k_grow_to