omap_I_s_erase_nonleaf – MAPL
omap_I_s_erase_nonleaf Subroutine
71 statements
Source File
private subroutine omap_I_s_erase_nonleaf(this, pos, side)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(inout) :: this
type(omap_I_s_Node), intent(inout), pointer :: pos
integer, intent(in) :: side
Calls
Called by
Call graph
omap_i_s_erase_nonleaf calls omap_i_s_advpos, omap_i_s_get_child, omap_i_s_rebalance, omap_i_s_which_side_am_i, set_parent
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_s_rebalance calls omap_i_s_get_child, get_height, omap_i_s_has_child, omap_i_s_rot, omap_i_s_update_height
omap_i_s_which_side_am_i calls omap_i_s_get_parent, omap_i_s_which_child
omap_i_s_rot calls omap_i_s_get_child, omap_i_s_which_side_am_i, omap_i_s_update_height, omap_i_s_set_parent
omap_i_s_update_height calls get_height
omap_i_s_which_child calls omap_i_s_get_child
omap_i_s_erase_range calls omap_i_s_erase_nonleaf
omap_i_erase_iter calls erase
omap_i_erase_range calls erase
omap_i_s_erase_iter calls erase
omap_i_s_erase_value calls erase
omap_i_s_merge calls erase