omap_at_rc – MAPL
omap_at_rc Function
8 statements
Source File
private function omap_at_rc(this, key, rc) result(res)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(in), target :: this
character(len=*), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(GriddedComponentDriver), pointer
Calls
Called by
Call graph
omap_at_rc calls at
omap_i_at_rc calls omap_i_find
omap_i_find calls omap_i_s_find
get_child_by_name calls at
get_child_user_states calls get_child
get_substates calls get_child
run_child_by_name calls get_child
test_child_user_items_created calls get_child
test_state_items_complete calls get_child