omap_new_omap_initializer_list – MAPL
omap_new_omap_initializer_list Function
8 statements
Source File
private function omap_new_omap_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverPair), intent(in) :: il(:)
Return Value type(GriddedComponentDriverMap)
Calls
Called by
Call graph
omap_new_omap_initializer_list calls insert
omap_insert_key_value calls at, insert, omap_k_push_back
omap_k_push_back calls resize, omap_k_grow_to
griddedcomponentdrivermap calls omap_new_omap_initializer_list