omap_I_erase_range – MAPL
omap_I_erase_range Function
8 statements
Source File
private function omap_I_erase_range(this, first, last) result(new_iter)
Type Bound
omap_Map
Arguments
Type Intent Optional Attributes Name
class(omap_Map), intent(inout), target :: this
type(omap_MapIterator), intent(in) :: first
type(omap_MapIterator), intent(in) :: last
Return Value type(omap_MapIterator)
Calls
Called by
Call graph
omap_i_erase_range calls erase
omap_i_s_erase_iter calls erase, omap_i_s_iter_next
omap_i_s_erase_range calls omap_i_s_deallocate_child, omap_i_s_erase_nonleaf, omap_i_s_get_parent, omap_i_s_has_child, omap_i_s_iter_next, omap_i_s_rebalance, omap_i_s_which_child
omap_i_s_erase_value calls erase, omap_i_s_find
omap_i_s_erase_nonleaf calls omap_i_s_rebalance, omap_i_s_advpos, omap_i_s_get_child, omap_i_s_which_side_am_i, set_parent
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_rebalance calls omap_i_s_has_child, get_height, omap_i_s_get_child, omap_i_s_rot, omap_i_s_update_height
omap_i_s_which_child calls omap_i_s_get_child
omap_erase_iter calls erase
omap_erase_key calls erase
omap_i_erase_key calls erase