omap_erase_iter – MAPL
omap_erase_iter Function
9 statements
Source File
private function omap_erase_iter(this, iter) result(new_iter)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(inout) :: this
type(GriddedComponentDriverMapIterator), intent(in) :: iter
Return Value type(GriddedComponentDriverMapIterator)
Calls
Call graph
omap_erase_iter calls erase, of, omap_i_find
omap_i_find calls omap_i_s_find
omap_i_erase_range calls erase
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan