omap_set_ – MAPL
omap_set_ Subroutine
16 statements
Source File
private subroutine omap_set_(this, key, value)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(inout) :: this
character(len=*), intent(in) :: key
type(GriddedComponentDriver), intent(in) :: value
Calls
Call graph
omap_set_ calls at, insert, omap_i_set_, omap_k_push_back
omap_i_set_ calls insert
omap_k_push_back calls resize, omap_k_grow_to
omap_i_at_rc calls omap_i_find
omap_i_insert_pair calls insert
omap_k_grow_to calls omap_k_capacity, omap_k_set_capacity
omap_i_find calls omap_i_s_find
omap_i_s_insert_initializer_list calls insert
omap_k_resize_size_kind calls reserve