omap_I_s_erase_value – MAPL
omap_I_s_erase_value Function
13 statements
Source File
private function omap_I_s_erase_value(this, value) result(n)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(inout), target :: this
type(GriddedComponentDriverPair), intent(in) :: value
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Called by
Call graph
omap_i_s_erase_value calls erase, omap_i_s_find
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_erase_iter calls erase, omap_i_s_iter_next
omap_i_s_erase_range calls omap_i_s_deallocate_child, omap_i_s_erase_nonleaf, omap_i_s_get_parent, omap_i_s_has_child, omap_i_s_iter_next, omap_i_s_rebalance, omap_i_s_which_child
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan
omap_i_s_erase_nonleaf calls omap_i_s_get_child, omap_i_s_rebalance, omap_i_s_advpos, omap_i_s_which_side_am_i, set_parent
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_lessthan calls omap_i_key_less_than
omap_i_s_rebalance calls omap_i_s_get_child, omap_i_s_has_child, get_height, omap_i_s_rot, omap_i_s_update_height
omap_i_s_which_child calls omap_i_s_get_child
omap_i_erase_iter calls erase
omap_i_erase_range calls erase
omap_i_s_merge calls erase
omap_erase_iter calls erase
omap_erase_key calls erase
omap_i_erase_key calls erase