omap_I_find_if – MAPL
omap_I_find_if Function
18 statements
Source File
private function omap_I_find_if(first, last, p) result(it)
Arguments
Type Intent Optional Attributes Name
type(omap_MapIterator), intent(in) :: first
type(omap_MapIterator), intent(in) :: last
private function p(item)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverPair), intent(in) :: item
Return Value logical
Return Value type(omap_MapIterator)
Calls
Called by
Call graph
omap_i_find_if calls omap_i_iter_next, omap_i_iter_of
omap_i_iter_next calls omap_i_s_iter_next
omap_i_iter_of calls omap_i_s_iter_of
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_iter_of calls omap_i_s_get_value
omap_i_s_advpos calls omap_i_s_get_child, to_node
find_if calls omap_i_find_if