omap_I_key_less_than – MAPL
omap_I_key_less_than Function
6 statements
Source File
private function omap_I_key_less_than(a, b) result(less_than)
Arguments
Type Intent Optional Attributes Name
type(GriddedComponentDriverPair), intent(in) :: a
type(GriddedComponentDriverPair), intent(in) :: b
Return Value logical
Called by
Call graph
omap_i_s_insert_single calls omap_i_key_less_than, omap_i_s_find_node, omap_i_s_order_eq
omap_i_s_less_than calls omap_i_key_less_than
omap_i_s_lessthan calls omap_i_key_less_than
omap_i_s_lower_bound calls omap_i_key_less_than, omap_i_s_find_node
omap_i_s_upper_bound calls omap_i_key_less_than, omap_i_s_find_node
omap_i_s_value_compare calls omap_i_key_less_than
operator(lt) calls omap_i_s_less_than
omap_i_s_find_node calls omap_i_s_lessthan, omap_i_s_order_eq
omap_i_s_order_eq calls omap_i_s_lessthan
omap_i_s_equal calls omap_i_s_order_eq
omap_i_s_find calls omap_i_s_find_node, omap_i_s_order_eq
operator(==) calls omap_i_s_equal
omap_i_find calls omap_i_s_find
omap_i_s_count calls omap_i_s_find
omap_i_s_erase_value calls omap_i_s_find