omap_I_s_insert_initializer_list – MAPL
omap_I_s_insert_initializer_list Subroutine
8 statements
Source File
private recursive subroutine omap_I_s_insert_initializer_list(this, values)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(inout) :: this
type(GriddedComponentDriverPair), intent(in) :: values(:)
Calls
Called by
Call graph
omap_i_s_insert_initializer_list calls insert
omap_i_insert_key_value calls insert
omap_i_insert_pair calls insert
omap_i_of calls insert
omap_i_s_copy_list calls insert
omap_i_s_deep_copy calls insert
omap_i_s_insert_range calls insert
omap_i_s_insert_single_with_hint calls insert
omap_i_s_merge calls insert
omap_i_s_new_set_initializer_list calls insert
omap_i_set_ calls insert
omap_i_set calls omap_i_s_new_set_initializer_list
omap_i_deep_copy calls omap_i_s_deep_copy
omap_of calls omap_i_of
omap_set_ calls omap_i_set_, insert
omap_erase_key calls omap_of
omap_i_new_map_initializer_list calls insert
omap_insert_key_value calls insert