omap_K_iter_of_offset_size_kind – MAPL
omap_K_iter_of_offset_size_kind Function
6 statements
Source File
private function omap_K_iter_of_offset_size_kind(this, i) result(ptr)
Type Bound
omap_VectorIterator
Arguments
Type Intent Optional Attributes Name
class(omap_VectorIterator), intent(in) :: this
integer(kind=selected_int_kind(18)), intent(in) :: i
Return Value character(len=:), pointer
Called by
Call graph
omap_erase_iter calls of
omap_iter_at calls of
omap_k_find_basic calls of
omap_k_find_if calls of
omap_k_find_if_not calls of
omap_k_new_vector_range calls of
omap_k_riter_of calls of
omap_k_riter_of_offset_default calls of
omap_k_riter_of_offset_size_kind calls of
find_if_not calls omap_k_find_if_not
find_if calls omap_k_find_if
find calls omap_k_find_basic
omap_vector calls omap_k_new_vector_range
omap_iter_first calls omap_iter_at
omap_iter_second calls omap_iter_at
omap_k_reverse_find_basic calls of
omap_k_reverse_find_if calls of
omap_k_reverse_find_if_not calls of
run_children_ calls omap_iter_first