omap_K_riter_next_1 – MAPL
omap_K_riter_next_1 Function
6 statements
Source File
private function omap_K_riter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(omap_VectorRIterator), intent(in) :: it
Return Value type(omap_VectorRIterator)
Calls
Called by
Call graph
omap_k_riter_next_1 calls next
next calls omap_iter_next_1, omap_iter_next_n_default, omap_iter_next_n_size_kind, omap_k_riter_next_1
omap_iter_next_1 calls next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next
omap_iter_next calls omap_k_iter_next