omap_begin – MAPL
omap_begin Function
6 statements
Source File
private function omap_begin(this) result(iter)
Type Bound
GriddedComponentDriverMap
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMap), intent(in), target :: this
Return Value type(GriddedComponentDriverMapIterator)
Calls
Called by
Call graph
omap_begin calls omap_k_begin
apply_to_children_custom calls omap_begin
finalize calls omap_begin, finalize
omap_iter_begin calls omap_begin
apply_to_children calls apply_to_children_custom
begin calls omap_iter_begin
test_finalize_children calls finalize
initialize_advertise calls apply_to_children
initialize_geom calls apply_to_children
initialize calls initialize_advertise, initialize_geom