omap_I_s_insert_range – MAPL
omap_I_s_insert_range Subroutine
11 statements
Source File
private recursive subroutine omap_I_s_insert_range(this, first, last)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(inout) :: this
type(omap_I_SetIterator), intent(in) :: first
type(omap_I_SetIterator), intent(in) :: last
Calls
Call graph
omap_i_s_insert_range calls insert, omap_i_s_iter_next, omap_i_s_iter_of
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_iter_of calls omap_i_s_get_value
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_s_insert_initializer_list calls insert