omap_I_s_deep_copy – MAPL
omap_I_s_deep_copy Subroutine
25 statements
Source File
private recursive subroutine omap_I_s_deep_copy(this, other)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(out), target :: this
class(omap_I_Set), intent(in), target :: other
Calls
Called by
Call graph
omap_i_s_deep_copy calls insert, omap_i_s_begin, omap_i_s_iter_next, omap_i_s_iter_of
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_iter_of calls omap_i_s_get_value
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_s_insert_initializer_list calls insert
omap_i_deep_copy calls omap_i_s_deep_copy