omap_K_insert_one – MAPL
omap_K_insert_one Function
7 statements
Source File
private recursive function omap_K_insert_one(this, pos, value) result(iter)
Type Bound
omap_Vector
Arguments
Type Intent Optional Attributes Name
class(omap_Vector), intent(inout), target :: this
type(omap_VectorIterator), intent(in) :: pos
character(len=*), intent(in) :: value
Return Value type(omap_VectorIterator)
Calls
Call graph
omap_k_insert_one calls insert
omap_k_insert_range calls omap_k_grow_to
omap_k_grow_to calls omap_k_capacity, omap_k_set_capacity