omap_K_iter_next – MAPL
omap_K_iter_next Subroutine
4 statements
Source File
private subroutine omap_K_iter_next(this)
Type Bound
omap_VectorIterator
Arguments
Type Intent Optional Attributes Name
class(omap_VectorIterator), intent(inout) :: this
Called by
Call graph
omap_iter_next calls omap_k_iter_next
omap_k_find_basic calls omap_k_iter_next
omap_k_find_if calls omap_k_iter_next
omap_k_find_if_not calls omap_k_iter_next
omap_k_riter_prev calls omap_k_iter_next
find_if_not calls omap_k_find_if_not
find_if calls omap_k_find_if
find calls omap_k_find_basic
apply_to_children_custom calls omap_iter_next
finalize calls omap_iter_next, finalize
omap_iter_advance_default calls omap_iter_next
omap_iter_advance_size_kind calls omap_iter_next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next
recurse_ calls omap_iter_next
run_children_ calls omap_iter_next
run_clock_advance calls omap_iter_next
advance calls omap_iter_advance_default, omap_iter_advance_size_kind
apply_to_children calls apply_to_children_custom
next calls omap_iter_next_n_default, omap_iter_next_n_size_kind
recurse calls recurse_
run calls run_clock_advance
test_finalize_children calls finalize