omap_I_begin – MAPL
omap_I_begin Function
6 statements
Source File
private function omap_I_begin(this) result(iter)
Type Bound
omap_Map
Arguments
Type Intent Optional Attributes Name
class(omap_Map), intent(in), target :: this
Return Value type(omap_MapIterator)
Calls
Called by
Call graph
omap_i_begin calls omap_i_s_begin
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_iter_begin calls omap_i_begin
begin calls omap_i_iter_begin