omap_K_ftn_begin – MAPL
omap_K_ftn_begin Function
10 statements
Source File
private function omap_K_ftn_begin(this) result(iter)
Type Bound
omap_Vector
Arguments
Type Intent Optional Attributes Name
class(omap_Vector), intent(in), target :: this
Return Value type(omap_VectorIterator)
Called by
Call graph
omap_ftn_begin calls omap_k_ftn_begin
omap_iter_ftn_begin calls omap_ftn_begin
recurse_ calls omap_ftn_begin
run_children_ calls omap_ftn_begin
run_clock_advance calls omap_ftn_begin
ftn_begin calls omap_iter_ftn_begin
recurse calls recurse_
run calls run_clock_advance, run_children, run
initialize_advertise calls recurse
initialize_geom calls recurse
initialize_post_advertise calls recurse
initialize_realize calls recurse
initialize_user calls recurse
run_children calls run_children