omap_iter_at – MAPL
omap_iter_at Function
17 statements
Source File
private function omap_iter_at(this) result(p)
Type Bound
GriddedComponentDriverMapIterator
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriverMapIterator), intent(in), target :: this
Return Value type(GriddedComponentDriverPair), pointer
Calls
Called by
Call graph
omap_iter_at calls of, omap_i_find
omap_i_find calls omap_i_s_find
omap_i_s_find calls omap_i_s_find_node, omap_i_s_get_value, omap_i_s_order_eq
omap_i_s_find_node calls omap_i_s_get_value, omap_i_s_order_eq, omap_i_s_get_child, omap_i_s_lessthan, to_node
omap_i_s_order_eq calls omap_i_s_lessthan
omap_iter_first calls omap_iter_at
omap_iter_second calls omap_iter_at
run_children_ calls omap_iter_first
run calls run_children
run_children calls run_children