omap_I_s_verify – MAPL
omap_I_s_verify Function
45 statements
Source File
private recursive function omap_I_s_verify(this) result(verify)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(in), target :: this
Return Value logical
Calls
Call graph
omap_i_s_verify calls omap_i_s_begin, omap_i_s_get_child, omap_i_s_has_child, omap_i_s_iter_next
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node