omap_K_push_back – MAPL
omap_K_push_back Subroutine
10 statements
Source File
private recursive subroutine omap_K_push_back(this, value, unused, rc)
Type Bound
omap_Vector
Arguments
Type Intent Optional Attributes Name
class(omap_Vector), intent(inout) :: this
character(len=*), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
omap_k_push_back calls resize, omap_k_grow_to
omap_k_grow_to calls omap_k_capacity, omap_k_set_capacity
omap_k_resize_size_kind calls reserve
omap_insert_key_value calls omap_k_push_back
omap_k_new_vector_range calls omap_k_push_back
omap_set_ calls omap_k_push_back
omap_vector calls omap_k_new_vector_range
add_child_by_name calls insert, add_child_by_name
omap_insert_pair calls insert
omap_new_omap_initializer_list calls insert
griddedcomponentdrivermap calls omap_new_omap_initializer_list