omap_I_ftn_end – MAPL
omap_I_ftn_end Function
6 statements
Source File
private function omap_I_ftn_end(this) result(iter)
Type Bound
omap_Map
Arguments
Type Intent Optional Attributes Name
class(omap_Map), intent(in), target :: this
Return Value type(omap_MapIterator)
Calls
Called by
Call graph
omap_i_ftn_end calls omap_i_s_ftn_end
omap_i_s_ftn_end calls next, omap_i_s_begin
next calls omap_iter_next_1, omap_iter_next_n_default, omap_iter_next_n_size_kind
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_iter_next_1 calls next
omap_iter_next_n_default calls omap_iter_next
omap_iter_next_n_size_kind calls omap_iter_next
omap_i_iter_ftn_end calls omap_i_ftn_end
ftn_end calls omap_i_iter_ftn_end