omap_I_s_begin – MAPL
omap_I_s_begin Function
7 statements
Source File
private function omap_I_s_begin(this) result(begin)
Type Bound
omap_I_Set
Arguments
Type Intent Optional Attributes Name
class(omap_I_Set), intent(in), target :: this
Return Value type(omap_I_SetIterator)
Calls
Called by
Call graph
omap_i_s_begin calls omap_i_s_iter_next
omap_i_s_iter_next calls omap_i_s_advpos
omap_i_s_advpos calls omap_i_s_get_child, to_node
omap_i_begin calls omap_i_s_begin
omap_i_s_deep_copy calls omap_i_s_begin
omap_i_s_equal calls omap_i_s_begin
omap_i_s_ftn_end calls omap_i_s_begin
omap_i_s_iter_begin calls omap_i_s_begin
omap_i_s_less_than calls omap_i_s_begin
omap_i_s_merge calls omap_i_s_begin
omap_i_s_verify calls omap_i_s_begin
begin calls omap_i_s_iter_begin, omap_i_iter_begin
operator(==) calls omap_i_s_equal
operator(lt) calls omap_i_s_less_than
omap_i_deep_copy calls omap_i_s_deep_copy
omap_i_ftn_end calls omap_i_s_ftn_end
omap_i_iter_begin calls omap_i_begin
omap_i_s_iter_ftn_end calls omap_i_s_ftn_end
ftn_end calls omap_i_s_iter_ftn_end, omap_i_iter_ftn_end
omap_i_iter_ftn_end calls omap_i_ftn_end