open_file – MAPL
open_file Subroutine
63 statements
Source File
public subroutine open_file(this)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
Calls
Called by
Call graph
open_file calls mpi_abort, mpi_barrier, mpi_comm_rank, mpi_info_create, mpi_info_set, nf90_open, mapl_verify
mapl_verify calls mapl_throw_exception
checkpoint_tester calls open_file