parent_ss – MAPL
parent_ss Subroutine
50 statements
Source File
public subroutine parent_ss(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
integer, intent(out) :: rc
Calls
Source Code
   subroutine parent_ss(gridcomp, rc)
      type(ESMF_Gridcomp) :: gridcomp
      integer, intent(out) :: rc
      type(ChildSpec) :: child_spec
      integer :: status
      logical :: use_default_timestep
      logical :: use_default_runTime
      type(ESMF_TimeInterval), allocatable :: timeStep
      type(ESMF_TimeInterval), allocatable :: offset
      type(ESMF_HConfig) :: hconfig
      rc=0
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_RUN, run_parent, _RC)
      call MAPL_GridCompGet(gridcomp, hconfig=hconfig, _RC)
      call MAPL_GridCompGetResource(gridcomp, keystring='use_default_timestep', value=use_default_timestep, default=.true., _RC)
      if (.not. use_default_timestep) then
         allocate(timeStep)
         call ESMF_TimeIntervalSet(timeStep, s=1800)
      end if
      call MAPL_GridCompGetResource(gridcomp, keystring='use_default_runTime', value=use_default_runTime, default=.true., _RC)
      if (.not. use_default_runTime) then
         allocate(offset)
         ! offset by 900 seconds
         call ESMF_TimeIntervalSet(offset, timeIntervalString="PT900S", _RC)
      end if
      child_spec = ChildSpec(user_SetServices(child_ss), timeStep=timeStep, offset=offset)
      call MAPL_GridCompAddChild(gridcomp, 'child', child_spec, _RC)
   end subroutine parent_ss
Call graph
parent_ss calls ESMF_TimeIntervalSet, anyexceptions, assert_that, mapl_gridcompaddchild, mapl_gridcompget, mapl_gridcompgetresource, mapl_gridcompsetentrypoint, user_setservices, sourcelocation