parse_component_spec – MAPL
parse_component_spec Function
32 statements
Source File
public function parse_component_spec(hconfig, rc) result(spec)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(inout), target :: hconfig
integer, intent(out), optional :: rc
Return Value type(ComponentSpec)
Calls
Called by
Source Code
   type(ComponentSpec) function parse_component_spec(hconfig, rc) result(spec)
      type(ESMF_HConfig), target, intent(inout) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: has_mapl_section
      logical :: has_geom_section
      type(ESMF_HConfig) :: subcfg
      has_mapl_section = ESMF_HConfigIsDefined(hconfig, keyString=MAPL_SECTION, _RC)
      _RETURN_UNLESS(has_mapl_section)
      subcfg = ESMF_HConfigCreateAt(hconfig, keyString=MAPL_SECTION, _RC)
      has_geom_section = ESMF_HConfigIsDefined(subcfg,keyString=COMPONENT_GEOM_SECTION, _RC)
      if (has_geom_section) then
         spec%geom_hconfig = parse_geom_spec(subcfg, _RC)
      end if
      spec%var_specs = parse_var_specs(subcfg, _RC)
      spec%connections = parse_connections(subcfg, _RC)
      spec%children = parse_children(subcfg, _RC)
      call ESMF_HConfigDestroy(subcfg, _RC)
      _RETURN(_SUCCESS)
   end function parse_component_spec
Call graph
parse_component_spec calls ESMF_HConfigDestroy, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_return, mapl_verify, parse_children, parse_connections, parse_geom_spec, parse_var_specs
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parse_children calls ESMF_HConfigDestroy, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_return, mapl_verify, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, insert, parse_child
parse_connections calls esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_return, mapl_verify, esmf_hconfigasstring, esmf_hconfiggetsize, mapl_assert, vector_push_back
parse_geom_spec calls esmf_hconfigcreateat, mapl_return, mapl_verify
parse_var_specs calls ESMF_HConfigDestroy, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_return, mapl_verify, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, esmf_hconfigasi4, esmf_hconfigasr4, esmf_hconfigasstring, esmf_hconfiggetsize, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, add_dim_spec, to_esmf_state_intent, vector_push_back, push_back, stringvector
setservices_ calls parse_component_spec, setservices_
create_grid_comp_primary calls setservices_
create_grid_comp calls create_grid_comp_primary