parse_var_specs – MAPL
parse_var_specs Function
328 statements
Source File
private function parse_var_specs(hconfig, rc) result(var_specs)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in), optional :: hconfig
integer, intent(out), optional :: rc
Return Value type(VariableSpecVector)
Calls
Called by
Source Code
   function parse_var_specs(hconfig, rc) result(var_specs)
      type(VariableSpecVector) :: var_specs
      type(ESMF_HConfig), optional, intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: has_states_section
      type(ESMF_HConfig) :: subcfg
      has_states_section = ESMF_HConfigIsDefined(hconfig,keyString=COMPONENT_STATES_SECTION, _RC)
      _RETURN_UNLESS(has_states_section)
      subcfg = ESMF_HConfigCreateAt(hconfig,keyString=COMPONENT_STATES_SECTION, _RC)
      call parse_state_specs(var_specs, subcfg, COMPONENT_INTERNAL_STATE_SECTION,  _RC)
      call parse_state_specs(var_specs, subcfg, COMPONENT_EXPORT_STATE_SECTION, _RC)
      call parse_state_specs(var_specs, subcfg, COMPONENT_IMPORT_STATE_SECTION, _RC)
      call ESMF_HConfigDestroy(subcfg, _RC)
      _RETURN(_SUCCESS)
   contains
      subroutine parse_state_specs(var_specs, hconfig, state_intent, rc)
         type(VariableSpecVector), intent(inout) :: var_specs
         type(ESMF_HConfig), target, intent(in) :: hconfig
         character(*), intent(in) :: state_intent
         integer, optional, intent(out) :: rc
         type(VariableSpec) :: var_spec
         type(ESMF_HConfigIter) :: iter,e,b
         character(:), allocatable :: name
         character(:), allocatable :: short_name
         character(:), allocatable :: substate
         type(ESMF_HConfig) :: attributes
         type(ESMF_TypeKind_Flag) :: typekind
         real, allocatable :: default_value
         type(VerticalDimSpec) :: vertical_dim_spec
         type(UngriddedDimsSpec) :: ungridded_dim_specs
         character(:), allocatable :: standard_name
         character(:), allocatable :: units
         type(ESMF_StateItem_Flag), allocatable :: itemtype
         type(ESMF_StateIntent_Flag) :: esmf_state_intent
         type(StringVector) :: service_items
         integer :: status
         logical :: has_state
         logical :: has_standard_name
         logical :: has_units
         type(ESMF_HConfig) :: subcfg
         type(StringVector) :: dependencies
         has_state = ESMF_HConfigIsDefined(hconfig,keyString=state_intent, _RC)
         _RETURN_UNLESS(has_state)
         subcfg = ESMF_HConfigCreateAt(hconfig,keyString=state_intent, _RC)
         b = ESMF_HConfigIterBegin(subcfg, _RC)
         e = ESMF_HConfigIterEnd(subcfg, _RC)
         iter = b
         do while (ESMF_HConfigIterLoop(iter,b,e))
            name = ESMF_HConfigAsStringMapKey(iter, _RC)
            attributes = ESMF_HConfigCreateAtMapVal(iter,_RC)
            call split(name, short_name, substate)
            typekind = to_typekind(attributes, _RC)
            call val_to_float(default_value, attributes, 'default_value', _RC)
            vertical_dim_spec = to_VerticalDimSpec(attributes,_RC)
            ungridded_dim_specs = to_UngriddedDimsSpec(attributes, _RC)
            has_standard_name = ESMF_HConfigIsDefined(attributes,keyString='standard_name', _RC)
            if (has_standard_name) then
               standard_name = ESMF_HConfigAsString(attributes,keyString='standard_name', _RC)
            end if
            has_units = ESMF_HConfigIsDefined(attributes,keyString='units', _RC)
            if (has_units) then
               units = ESMF_HConfigAsString(attributes,keyString='units', _RC)
            end if
            call to_itemtype(itemtype, attributes, _RC)
            call to_service_items(service_items, attributes, _RC)
            dependencies = to_dependencies(attributes, _RC)
            esmf_state_intent = to_esmf_state_intent(state_intent)
            var_spec = VariableSpec(esmf_state_intent, short_name=short_name, &
                 itemtype=itemtype, &
                 service_items=service_items, &
                 standard_name=standard_name, &
                 units=units, &
                 typekind=typekind, &
                 substate=substate, &
                 default_value=default_value, &
                 vertical_dim_spec=vertical_dim_spec, &
                 ungridded_dims=ungridded_dim_specs, &
                 dependencies=dependencies &
                 )
            call var_specs%push_back(var_spec)
            call ESMF_HConfigDestroy(attributes, _RC)
         end do
         call ESMF_HConfigDestroy(subcfg, _RC)
         _RETURN(_SUCCESS)
      end subroutine parse_state_specs
      subroutine split(name, short_name, substate)
         character(*), intent(in) :: name
         character(:), allocatable, intent(out) :: short_name
         character(:), allocatable, intent(out) :: substate
         integer :: idx
         idx = index(name, '/')
         if (idx == 0) then
            short_name = name
            return
         end if
         short_name = name(idx+1:)
         substate = name(:idx-1)
      end subroutine split
      subroutine val_to_float(x, attributes, key, rc)
         real, allocatable, intent(out) :: x
         type(ESMF_HConfig), intent(in) :: attributes
         character(*), intent(in) :: key
         integer, optional, intent(out) :: rc
         integer :: status
         logical :: has_default_value
         has_default_value = ESMF_HConfigIsDefined(attributes,keyString=KEY_DEFAULT_VALUE, _RC)
         _RETURN_UNLESS(has_default_value)
         allocate(x)
         x = ESMF_HConfigAsR4(attributes,keyString=KEY_DEFAULT_VALUE,_RC)
         _RETURN(_SUCCESS)
      end subroutine val_to_float
      function to_typekind(attributes, rc) result(typekind)
         use :: mapl3g_ESMF_Utilities, only: MAPL_TYPEKIND_MIRROR
         type(ESMF_TypeKind_Flag) :: typekind
         type(ESMF_HConfig), intent(in) :: attributes
         integer, optional, intent(out) :: rc
         integer :: status
         logical :: typekind_is_specified
         character(:), allocatable :: typekind_str
         typekind = ESMF_TYPEKIND_R4 ! GEOS defaults
         typekind_is_specified = ESMF_HConfigIsDefined(attributes, keyString='typekind', _RC)
         _RETURN_UNLESS(typekind_is_specified)
         typekind_str= ESMF_HConfigAsString(attributes,keyString='typekind',_RC)
         select case (typekind_str)
         case ('R4')
            typekind = ESMF_TYPEKIND_R4
         case ('R8')
            typekind = ESMF_TYPEKIND_R8
         case ('I4')
            typekind = ESMF_TYPEKIND_I4
         case ('I8')
            typekind = ESMF_TYPEKIND_I8
         case ('mirror')
            typekind = MAPL_TYPEKIND_MIRROR
         case default
            _FAIL('Unsupported typekind: <'//typekind_str//'>')
         end select
         _RETURN(_SUCCESS)
      end function to_typekind
      function to_VerticalDimSpec(attributes, rc) result(vertical_dim_spec)
         type(VerticalDimSpec) :: vertical_dim_spec
         type(ESMF_HConfig), intent(in) :: attributes
         integer, optional, intent(out) :: rc
         integer :: status
         character(:), allocatable :: vertical_str
         logical :: has_dim_spec
         vertical_dim_spec = VERTICAL_DIM_NONE ! GEOS default
         has_dim_spec = ESMF_HConfigIsDefined(attributes,keyString=KEY_VERTICAL_DIM_SPEC, _RC)
         _RETURN_UNLESS(has_dim_spec)
         vertical_str= ESMF_HConfigAsString(attributes,keyString=KEY_VERTICAL_DIM_SPEC,_RC)
         select case (vertical_str)
         case ('vertical_dim_none', 'N')
            vertical_dim_spec = VERTICAL_DIM_NONE
         case ('vertical_dim_center', 'C')
            vertical_dim_spec = VERTICAL_DIM_CENTER
         case ('vertical_dim_edge', 'E')
            vertical_dim_spec = VERTICAL_DIM_EDGE
         case default
            _FAIL('Unsupported vertical_dim_spec')
         end select
         _RETURN(_SUCCESS)
      end function to_VerticalDimSpec
      function to_UngriddedDimsSpec(attributes,rc) result(ungridded_dims_spec)
         type(UngriddedDimsSpec) :: ungridded_dims_spec
         type(ESMF_HConfig), intent(in) :: attributes
         integer, optional, intent(out) :: rc
         integer :: status
         type(ESMF_HConfig) :: dim_specs, dim_spec
         character(len=:), allocatable :: dim_name
         integer :: dim_size,i
         type(UngriddedDimSpec) :: temp_dim_spec
         logical :: has_ungridded_dim_specs
         integer :: n_specs
         has_ungridded_dim_specs = ESMF_HConfigIsDefined(attributes, keyString=KEY_UNGRIDDED_DIM_SPECS, _RC)
         _RETURN_UNLESS(has_ungridded_dim_specs)
         dim_specs = ESMF_HConfigCreateAt(attributes, keyString=KEY_UNGRIDDED_DIM_SPECS, _RC)
         n_specs = ESMF_HConfigGetSize(dim_specs, _RC)
         do i = 1, n_specs
            dim_spec = ESMF_HConfigCreateAt(dim_specs, index=i, _RC)
            dim_name = ESMF_HConfigAsString(dim_spec, keyString=KEY_UNGRIDDED_DIM_NAME, _RC)
            dim_size = ESMF_HConfigAsI4(dim_spec, keyString=KEY_UNGRIDDED_DIM_EXTENT, _RC)
            temp_dim_spec = UngriddedDimSpec(dim_size)
            call ungridded_dims_spec%add_dim_spec(temp_dim_spec, _RC)
            call ESMF_HConfigDestroy(dim_spec, _RC)
         end do
         call ESMF_HConfigDestroy(dim_specs, _RC)
         _RETURN(_SUCCESS)
      end function to_UngriddedDimsSpec
      subroutine to_itemtype(itemtype, attributes, rc)
         type(ESMF_StateItem_Flag), allocatable, intent(out) :: itemtype
         type(ESMF_HConfig), target, intent(in) :: attributes
         integer, optional, intent(out) :: rc
         integer :: status
         character(:), allocatable :: subclass
         logical :: has_itemtype
         has_itemtype = ESMF_HConfigIsDefined(attributes,keyString='class',_RC)
         _RETURN_UNLESS(has_itemtype)
         subclass= ESMF_HConfigAsString(attributes, keyString='class',_RC)
         select case (subclass)
         case ('field')
            itemtype = MAPL_STATEITEM_FIELD
         case ('service')
            itemtype = MAPL_STATEITEM_SERVICE
         case ('wildcard')
            itemtype = MAPL_STATEITEM_WILDCARD
         case default
            _FAIL('unknown subclass for state item: '//subclass)
         end select
         _RETURN(_SUCCESS)
      end subroutine to_itemtype
      subroutine to_service_items(service_items, attributes, rc)
         type(StringVector), intent(out) :: service_items
         type(ESMF_HConfig), target, intent(in) :: attributes
         integer, optional, intent(out) :: rc
         integer :: status
         type(ESMF_HConfig) :: seq
         integer :: num_items, i
         character(:), allocatable :: item_name
         logical :: has_service_items
         has_service_items = ESMF_HConfigIsDefined(attributes,keyString='items',_RC)
         _RETURN_UNLESS(has_service_items)
         seq = ESMF_HConfigCreateAt(attributes,keyString='items',_RC)
         _ASSERT(ESMF_HConfigIsSequence(seq),"items must be a sequence")
         num_items = ESMF_HConfigGetSize(seq,_RC)
         do i = 1,num_items
            item_name = ESMF_HConfigAsString(seq,index = i, _RC)
            call service_items%push_back(item_name)
         end do
         _RETURN(_SUCCESS)
      end subroutine to_service_items
      function to_dependencies(attributes, rc) result(dependencies)
         type(StringVector) :: dependencies
         type(ESMF_HConfig), intent(in) :: attributes
         integer, optional, intent(out) :: rc
         integer :: status
         logical :: has_dependencies
         type(ESMF_HConfig) :: dependencies_hconfig
         integer :: i, n_dependencies
         character(:), allocatable :: name
         dependencies = StringVector()
         has_dependencies = ESMF_HConfigIsDefined(attributes, keyString='dependencies', _RC)
         _RETURN_UNLESS(has_dependencies)
         dependencies_hconfig = ESMF_HConfigCreateAt(attributes, keyString='dependencies', _RC)
         _ASSERT(ESMF_HConfigIsSequence(dependencies_hconfig), 'expected sequence for attribute <dependencies>')
         n_dependencies = ESMF_HConfigGetSize(dependencies_hconfig, _RC)
         do i = 1, n_dependencies
            name = ESMF_HConfigAsString(dependencies_hconfig, index=i, _RC)
            call dependencies%push_back(name)
         end do
         _RETURN(_SUCCESS)
      end function to_dependencies
   end function parse_var_specs
Call graph
parse_var_specs calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, esmf_hconfigasi4, esmf_hconfigasr4, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, add_dim_spec, mapl_return, mapl_verify, to_esmf_state_intent, vector_push_back, push_back, stringvector
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_dim_spec calls mapl_assert, mapl_return, get_name, get_num_ungridded, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
to_esmf_state_intent calls mapl_assert, mapl_return
vector_push_back calls resize, vector_grow_to
parse_component_spec calls parse_var_specs
setservices_ calls parse_component_spec, setservices_
create_grid_comp_primary calls setservices_