parse_children – MAPL
parse_children Function
43 statements
Source File
public function parse_children(hconfig, rc) result(children)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(ChildSpecMap)
Calls
Called by
Source Code
   function parse_children(hconfig, rc) result(children)
      type(ChildSpecMap) :: children
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: has_children
      logical :: is_map
      type(ESMF_HConfig) :: children_cfg, child_cfg
      type(ESMF_HConfigIter) :: iter, iter_begin, iter_end
      type(ChildSpec) :: child_spec
      character(:), allocatable :: child_name
      has_children = ESMF_HConfigIsDefined(hconfig, keyString=COMPONENT_CHILDREN_SECTION, _RC)
      _RETURN_UNLESS(has_children)
      children_cfg = ESMF_HConfigCreateAt(hconfig, keyString=COMPONENT_CHILDREN_SECTION, _RC)
      is_map = ESMF_HConfigIsMap(children_cfg, _RC)
      _ASSERT(is_map, 'children spec must be mapping')
      iter_begin = ESMF_HCOnfigIterBegin(children_cfg, _RC)
      iter_end = ESMF_HConfigIterEnd(children_cfg, _RC)
      iter = iter_begin
      do while (ESMF_HConfigIterLoop(iter, iter_begin, iter_end))
         child_name = ESMF_HConfigAsStringMapKey(iter, _RC)
         child_cfg = ESMF_HConfigCreateAtMapVal(iter, _RC)
         child_spec = parse_child(child_cfg, _RC)
         call children%insert(child_name, child_spec)
         call ESMF_HConfigDestroy(child_cfg, _RC)
      end do
      call ESMF_HConfigDestroy(children_cfg, _RC)
      _RETURN(_SUCCESS)
   end function parse_children
Call graph
parse_children calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, insert, mapl_return, mapl_verify, parse_child
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parse_child calls esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify, esmf_hconfigasstring, user_setservices
user_setservices calls new_dsosetservices, new_procsetservices
get_error_message calls at, insert
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_component_spec calls parse_children
test_parse_childspecmap_1 calls parse_children
test_parse_childspecmap_2 calls parse_children
test_parse_childspecmap_empty calls parse_children
setservices_ calls parse_component_spec, setservices_
create_grid_comp_primary calls setservices_