parser_variables_in_expression – MAPL
parser_variables_in_expression Function
103 statements
Source File
public function parser_variables_in_expression(FuncStr, rc) result(variables_in_expression)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: FuncStr
integer, optional :: rc
Return Value type(StringVector)
Calls
Called by
Call graph
parser_variables_in_expression calls mapl_assert, checkundef, getvariables, mapl_return, mathfunctionindex, parseerrmsg, realnum, removespaces, replace, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
checkundef calls lowcase
mapl_return calls get_error_message, mapl_throw_exception
mathfunctionindex calls lowcase
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_mask_variables calls parser_variables_in_expression
get_variables_in_expression calls parser_variables_in_expression, get_mask_variables
get_extra_derived_items calls get_variables_in_expression
initialize_ calls get_extra_derived_items