parse_setservices – MAPL
parse_setservices Function
17 statements
Source File
public function parse_setservices(config, rc) result(user_ss)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in), target :: config
integer, intent(out), optional :: rc
Return Value type(DSOSetServices)
Calls
Called by
Source Code
   type(DSOSetServices) function parse_setservices(config, rc) result(user_ss)
      type(ESMF_HConfig), target, intent(in) :: config
      integer, optional, intent(out) :: rc
      character(:), allocatable :: sharedObj, userRoutine
      integer :: status
      sharedObj = ESMF_HConfigAsString(config,keyString='sharedObj',rc=status)
      _ASSERT(status == 0, 'setServices spec does not specify sharedObj')
      if (ESMF_HConfigIsDefined(config,keyString='userRoutine')) then
         userRoutine = ESMF_HConfigAsString(config,keyString='userRoutine',_RC)
      else
         userRoutine = 'setservices_'
      end if
      user_ss = user_setservices(sharedObj, userRoutine)
      _RETURN(_SUCCESS)
   end function parse_setservices
Call graph
parse_setservices calls esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, user_setservices, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
user_setservices calls new_dsosetservices, new_procsetservices
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_parse_setservices calls parse_setservices
test_parse_setservices_default calls parse_setservices