parse_item_common – MAPL
parse_item_common Subroutine
25 statements
Source File
public subroutine parse_item_common(item, item_name, expression, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfigIter), intent(in) :: item
character(len=:), intent(out), allocatable :: item_name
character(len=:), intent(out), allocatable :: expression
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine parse_item_common(item, item_name, expression, rc)
      type(ESMF_HConfigIter), intent(in) :: item
      character(len=:), allocatable, intent(out) :: item_name
      character(len=:), allocatable, intent(out) :: expression
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: EXPRESSION_KEY = 'expr'
      integer :: status
      logical :: asOK, isScalar, isMap
      type(ESMF_HConfig) :: value
      isScalar = ESMF_HConfigIsScalarMapKey(item, _RC)
      _ASSERT(isScalar, 'Variable list item does not have a scalar name.')
      isMap = ESMF_HConfigIsMapMapVal(item, _RC)
      _ASSERT(isMap, 'Variable list item does not have a map value.')
      item_name = ESMF_HConfigAsStringMapKey(item, asOkay=asOK, _RC)
      _ASSERT(asOK, 'Item name could not be processed as a String.')
      value = ESMF_HConfigCreateAtMapVal(item, _RC)
      expression = ESMF_HConfigAsString(value, keyString=EXPRESSION_KEY, _RC)
      _RETURN(_SUCCESS)
   end subroutine parse_item_common
Call graph
parse_item_common calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIsMapMapVal, ESMF_HConfigIsScalarMapKey, esmf_hconfigasstring, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_parse_item_common calls parse_item_common