parse_geom_spec – MAPL
parse_geom_spec Function
10 statements
Source File
private function parse_geom_spec(hconfig, rc) result(geom_hconfig)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in), optional :: hconfig
integer, intent(out), optional :: rc
Return Value type(ESMF_HConfig)
Calls
Called by
Source Code
   function parse_geom_spec(hconfig, rc) result(geom_hconfig)
      type(ESMF_HConfig) :: geom_hconfig
      type(ESMF_HConfig), optional, intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      geom_hconfig = ESMF_HConfigCreateAt(hconfig,keyString=COMPONENT_GEOM_SECTION, _RC)
      _RETURN(_SUCCESS)
   end function parse_geom_spec
Call graph
parse_geom_spec calls esmf_hconfigcreateat, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_component_spec calls parse_geom_spec
setservices_ calls parse_component_spec, setservices_
create_grid_comp_primary calls setservices_