parse_child – MAPL
parse_child Function
53 statements
Source File
public function parse_child(hconfig, rc) result(child)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(ChildSpec)
Calls
Called by
Source Code
   function parse_child(hconfig, rc) result(child)
      type(ChildSpec) :: child
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      class(AbstractUserSetServices), allocatable :: setservices
      character(*), parameter :: dso_keys(*) = [character(len=9) :: 'dso', 'DSO', 'sharedObj', 'sharedobj']
      character(*), parameter :: userProcedure_keys(*) = [character(len=10) :: 'SetServices', 'setServices', 'setservices']
      integer :: i
      character(:), allocatable :: dso_key, userProcedure_key, try_key
      logical :: dso_found, userProcedure_found
      logical :: has_key
      logical :: has_config_file
      character(:), allocatable :: sharedObj, userProcedure, config_file
      dso_found = .false.
      ! Ensure precisely one name is used for dso
      do i = 1, size(dso_keys)
         try_key = trim(dso_keys(i))
         has_key = ESMF_HconfigIsDefined(hconfig, keyString=try_key, _RC)
         if (has_key) then
            _ASSERT(.not. dso_found, 'multiple specifications for dso in hconfig for child')
            dso_found = .true.
            dso_key = try_key
         end if
      end do
      _ASSERT(dso_found, 'Must specify a dso for hconfig of child')
      sharedObj = ESMF_HconfigAsString(hconfig, keyString=dso_key, _RC)
      userProcedure_found = .false.
      do i = 1, size(userProcedure_keys)
         try_key = userProcedure_keys(i)
         if (ESMF_HconfigIsDefined(hconfig, keyString=try_key)) then
            _ASSERT(.not. userProcedure_found, 'multiple specifications for dso in hconfig for child')
            userProcedure_found = .true.
            userProcedure_key = try_key
         end if
      end do
      userProcedure = 'setservices_'
      if (userProcedure_found) then
         userProcedure = ESMF_HconfigAsString(hconfig, keyString=userProcedure_key,_RC)
      end if
      has_config_file = ESMF_HconfigIsDefined(hconfig, keyString='config_file', _RC)
      if (has_config_file) then
         config_file = ESMF_HconfigAsString(hconfig, keyString='config_file',_RC)
      end if
      setservices = user_setservices(sharedObj, userProcedure)
      child = ChildSpec(setservices, config_file=config_file)
      _RETURN(_SUCCESS)
   end function parse_child
Call graph
parse_child calls esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, user_setservices, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
user_setservices calls new_dsosetservices, new_procsetservices
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_children calls parse_child
test_parse_childspec_basic calls parse_child
test_parse_childspec_with_config_file calls parse_child
parse_component_spec calls parse_children
test_parse_childspecmap_1 calls parse_children
test_parse_childspecmap_2 calls parse_children
test_parse_childspecmap_empty calls parse_children
setservices_ calls parse_component_spec, setservices_