post_wait_all – MAPL
post_wait_all Subroutine
5 statements
Source File
private subroutine post_wait_all(this)
Uses
pFIO_AbstractRequestHandleMod
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout), target :: this
Calls
Called by
Source Code
   subroutine post_wait_all(this)
      use pFIO_AbstractRequestHandleMod
      class (ClientThread), target, intent(inout) :: this
      call this%wait_all()
   end subroutine post_wait_all
Call graph
post_wait_all calls wait_all
wait_all calls clear_requesthandle
clear_requesthandle calls erase, map_begin, mapl_return, mapl_verify
map_begin calls map_s_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
post_wait calls post_wait_all
mapl_bundlewritencpar calls post_wait
run calls post_wait
run_model calls post_wait
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
main calls run_model
mapl_esmfstatewritetofile calls mapl_varwritencpar