propagate_unsatisfied_imports_child – MAPL
propagate_unsatisfied_imports_child Subroutine
18 statements
Source File
private subroutine propagate_unsatisfied_imports_child(this, child_r, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(HierarchicalRegistry), intent(in), target :: child_r
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine propagate_unsatisfied_imports_child(this, child_r, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(HierarchicalRegistry), target, intent(in) :: child_r
      integer, optional, intent(out) :: rc
      type(ActualPtVector), pointer :: actual_pts_vector
      type(ActualPtVec_MapIterator) :: iter
      integer :: status
      associate (e => child_r%virtual_pts%end())
        iter = child_r%virtual_pts%begin()
        do while (iter /= e)
           call this%propagate_unsatisfied_imports(child_r, iter, _RC)
           call iter%next()
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine propagate_unsatisfied_imports_child
Call graph
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports, map_begin, map_iter_next, mapl_return, mapl_verify
map_begin calls map_s_begin
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
propagate_unsatisfied_imports_virtual_pt calls mapl_return, mapl_verify, mapl_assert, of, add_comp_name, get_item_spec, get_name, is_active, is_import, link_item_spec_virtual, map_iter_first