propagate_unsatisfied_imports_virtual_pt – MAPL
propagate_unsatisfied_imports_virtual_pt Subroutine
25 statements
Source File
private subroutine propagate_unsatisfied_imports_virtual_pt(this, child_r, iter, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout) :: this
type(HierarchicalRegistry), intent(in), target :: child_r
type(ActualPtVec_MapIterator), intent(in) :: iter
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine propagate_unsatisfied_imports_virtual_pt(this, child_r, iter, rc)
      class(HierarchicalRegistry), intent(inout) :: this
      type(HierarchicalRegistry), target, intent(in) :: child_r
      type(ActualPtVec_MapIterator), intent(in) :: iter
      integer, optional, intent(out) :: rc
      integer :: i
      integer :: status
      class(StateItemSpec), pointer :: item
      type(VirtualConnectionPt), pointer :: virtual_pt
      type(ActualPtVector), pointer :: actual_pts
      type(ActualConnectionPt), pointer :: actual_pt
      virtual_pt => iter%first()
      actual_pts => iter%second()
      do i = 1, actual_pts%size()
         actual_pt => actual_pts%of(i)
         item => child_r%get_item_spec(actual_pt)
         _ASSERT(associated(item), 'Should not happen.')
         if (actual_pt%is_import() .and. .not. item%is_active()) then
            call this%link_item_spec_virtual(virtual_pt, item, actual_pt%add_comp_name(child_r%get_name()), _RC)
         end if
      end do
      _RETURN(_SUCCESS)
   end subroutine propagate_unsatisfied_imports_virtual_pt
Call graph
propagate_unsatisfied_imports_virtual_pt calls mapl_assert, of, add_comp_name, get_item_spec, get_name, is_active, is_import, link_item_spec_virtual, map_iter_first, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_comp_name calls add_comp_name
get_item_spec calls mapl_return, mapl_verify, at
is_import calls is_import
link_item_spec_virtual calls mapl_return, mapl_verify, has_item_spec, link_item_spec, add_extension_pt
map_iter_first calls map_iter_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
initialize_advertise calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls propagate_unsatisfied_imports
initialize calls initialize_advertise