propagate_unsatisfied_imports_all – MAPL
propagate_unsatisfied_imports_all Subroutine
19 statements
Source File
private subroutine propagate_unsatisfied_imports_all(this, rc)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine propagate_unsatisfied_imports_all(this, rc)
      class(HierarchicalRegistry), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      type(RegistryPtrMapIterator) :: iter
      type(HierarchicalRegistry), pointer :: child
      integer :: status
      associate (e => this%subregistries%end())
        iter = this%subregistries%begin()
        do while (iter /= e)
           child => this%get_subregistry(iter%first(), _RC)
           call this%propagate_unsatisfied_imports(child, _RC)
           call iter%next()
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine propagate_unsatisfied_imports_all
Call graph
propagate_unsatisfied_imports_all calls get_subregistry, propagate_unsatisfied_imports, map_begin, map_iter_first, map_iter_next, mapl_return, mapl_verify
map_begin calls map_s_begin
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_subregistry_comp calls mapl_return, mapl_verify, mapl_assert, at, get_name
get_subregistry_conn calls get_subregistry, mapl_return, mapl_verify
map_iter_of calls map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
propagate_unsatisfied_imports_virtual_pt calls mapl_return, mapl_verify, mapl_assert, of, add_comp_name, get_item_spec, get_name, is_active, is_import, link_item_spec_virtual, map_iter_first