PutFieldInBundle__ – MAPL
PutFieldInBundle__ Subroutine
39 statements
Source File
private subroutine PutFieldInBundle__(Bundle, Field, multiflag, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
type(ESMF_Field), intent(in) :: Field
logical, intent(in), optional :: multiflag
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine PutFieldInBundle__(Bundle, Field, multiflag, RC)
      type(ESMF_FieldBundle),  intent(inout) :: Bundle
      type(ESMF_Field),  intent(in   ) :: Field
      logical, optional, intent(in   ) :: multiflag
      integer, optional, intent(  out) :: rc
      ! ErrLog vars
      integer                   :: status
      ! Local var
      integer                   :: DIMS, I
      integer                   :: fieldRank
      type(ESMF_Field), pointer :: splitFields(:) => null()
      type(ESMF_Info)           :: infoh
      _UNUSED_DUMMY(multiflag)
      call ESMF_FieldGet(FIELD, dimCount=fieldRank, rc=status)
      _VERIFY(status)
      if (fieldRank == 4) then
         call ESMF_InfoGetFromHost(FIELD, infoh, RC=status)
         call ESMF_InfoGet(infoh,'DIMS',DIMS, RC=status)
         _VERIFY(status)
         if (DIMS == MAPL_DimsHorzVert) then
            call MAPL_FieldSplit(field, splitFields, RC=status)
            _VERIFY(status)
            do I=1, size(splitFields)
               call MAPL_FieldBundleAdd(BUNDLE, splitFields(I), rc=status )
               _VERIFY(status)
            end do
            deallocate(splitFields)
         else
            call MAPL_FieldBundleAdd(BUNDLE, FIELD, rc=status )
            _VERIFY(status)
         end if
      else
         call MAPL_FieldBundleAdd(BUNDLE, FIELD, rc=status )
         _VERIFY(status)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine PutFieldInBundle__
Call graph
putfieldinbundle__ calls ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, mapl_fieldbundleadd, mapl_fieldsplit, mapl_return, mapl_verify
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_fieldsplit calls mapl_fieldsplit, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, mapl_return, mapl_verify, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_fieldcreate, mapl_assert, mapl_fieldcopyattributes
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, mapl_return, mapl_verify, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_fieldbundleadd
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldcopyattributes calls mapl_fieldcopyattributes
mapl_gridcompgetfriendlies0 calls putfieldinbundle__, mapl_gridcompgetfriendlies
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies3
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0