read_restart – MAPL
read_restart Subroutine
15 statements
Source File
private recursive subroutine read_restart(gridcomp, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine read_restart(gridcomp, importState, exportState, clock, rc)
      type(ESMF_GridComp) :: gridcomp
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      outer_meta => get_outer_meta(gridcomp, _RC)
      call outer_meta%read_restart(importState, exportState, clock, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine read_restart
Call graph
read_restart calls get_outer_meta, mapl_return, mapl_verify, read_restart
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_outer_meta_from_outer_gc calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code