ReadRestart – MAPL
ReadRestart Subroutine
165 statements
Source File
private subroutine ReadRestart(CC, SRC, DST, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CplComp) :: CC
type(ESMF_State) :: SRC
type(ESMF_State) :: DST
type(ESMF_Clock) :: CLOCK
integer, intent(out) :: RC
Calls
Source Code
  subroutine ReadRestart(CC, SRC, DST, CLOCK, RC)
! !ARGUMENTS:
    type (ESMF_CplComp)      :: CC
    type (ESMF_State)        :: SRC
    type (ESMF_State)        :: DST
    type (ESMF_Clock)        :: CLOCK
    integer, intent(  OUT)   :: RC
!EOPI
! ErrLog Variables
    character(len=ESMF_MAXSTR)    :: IAm
    character(len=ESMF_MAXSTR)    :: COMP_NAME
    integer                       :: STATUS
! Locals
    type (MAPL_GenericCplState), pointer  :: STATE
    type (MAPL_GenericCplWrap )           :: WRAP
    type(ESMF_VM)                         :: VM
    type(ESMF_Grid)                       :: grid
    type(ESMF_Field)                      :: field
    type(ESMF_Info)                       :: infoh
    character(len=ESMF_MAXSTR)            :: name
    character(len=ESMF_MAXSTR)            :: filename
    logical                               :: file_exists
    logical                               :: am_i_root
    integer                               :: unit
    integer                               :: n_vars
    integer                               :: n_count
    integer                               :: n_undefs
    integer                               :: rank
    integer                               :: i
    integer                               :: dims
    integer, pointer                      :: mask(:) => null()
    real, allocatable                     :: buf1(:), buf2(:,:), buf3(:,:,:)
    real, pointer                         :: ptr1(:), ptr2(:,:), ptr3(:,:,:)
! Begin...
! Get the target components name and set-up traceback handle.
! -----------------------------------------------------------
    _UNUSED_DUMMY(dst)
    _UNUSED_DUMMY(clock)
    IAm = "MAPL_GenericCplComReadRestart"
    call ESMF_CplCompGet( CC, NAME=COMP_NAME, RC=STATUS )
    _VERIFY(STATUS)
    Iam = trim(COMP_NAME) // Iam
! Retrieve the pointer to the internal state. It comes in a wrapper.
! ------------------------------------------------------------------
    call ESMF_CplCompGetInternalState ( CC, WRAP, STATUS )
    _VERIFY(STATUS)
    STATE     =>  WRAP%INTERNAL_STATE
!ALT remove this line when done
    call write_parallel('STUBBED in CPL ReadRestart')
!ALT: Uncomment when done
!strategy
!root tries to open the restart (or inquire)
!if the file is there
! read the restart:
!==================
!    call ESMF_CplCompGet(CC, vm=vm, name=name, rc=status)
!    _VERIFY(STATUS)
!    filename = trim(name) // '_rst' ! following Andrea's suggestion
    call ESMF_CplCompGet(CC, vm=vm, rc=status)
    _VERIFY(STATUS)
    filename = trim(state%name) // '_rst' ! following Andrea's suggestion
    am_i_root = MAPL_AM_I_ROOT(vm)
    if (am_i_root) then
       ! check if file exists
       inquire(file=filename, exist=file_exists)
    end if
    call MAPL_CommsBcast(vm, file_exists, n=1, ROOT=MAPL_Root, rc=status)
    _VERIFY(status)
    if (file_exists) then
       !ALT: ideally, we should check the monthly alarm: read only when not ringing.
       ! read metadata: grid info, number of vars
       unit=0 ! just to initialize
       if (am_i_root) then
          UNIT = GETFILE(filename, rc=status)
          _VERIFY(status)
          read(unit) n_vars
          _ASSERT(size(state%src_spec) == n_vars, "Number of variables on the restart does not agree with spec")
       end if
       ! for each var
       n_vars = size(state%src_spec)
       do i = 1, n_vars
          ! varname we can get from query SHORT_NAME in state%src_spec(i)
          call MAPL_VarSpecGet(state%src_spec(i), SHORT_NAME=name, rc=status)
          _VERIFY(status)
          call ESMF_StateGet(SRC, name, field=field, rc=status)
          _VERIFY(status)
          call ESMF_FieldGet(field, grid=grid, rc=status)
          _VERIFY(status)
          rank = state%accum_rank(i)
          call ESMF_InfoGetFromHost(field,infoh,rc=status)
          _VERIFY(STATUS)
          call ESMF_InfoGet(infoh,'DIMS',DIMS,rc=status)
          _VERIFY(STATUS)
          mask => null()
          if (DIMS == MAPL_DimsTileOnly .or. DIMS == MAPL_DimsTileTile) then
             call MAPL_TileMaskGet(grid,  mask, rc=status)
             _VERIFY(STATUS)
          end if
          ! ALT note: calling a procedure with optional argument, and passing NULL pointer to indicate "absent", needs ifort16 or newer
          if (am_i_root) then
             read(unit) n_count
          end if
          call MAPL_CommsBcast(vm, n_count, n=1, ROOT=MAPL_Root, rc=status)
          _VERIFY(status)
          state%accum_count(i) = n_count
          if (am_i_root) then
             read(unit) n_undefs
          end if
          call MAPL_CommsBcast(vm, n_undefs, n=1, ROOT=MAPL_Root, rc=status)
          _VERIFY(status)
          select case(rank)
          case (3)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(i), &
                  farrayPtr=ptr3, RC=status)
             _VERIFY(status)
             call MAPL_VarRead(unit, grid, ptr3, rc=status)
             _VERIFY(STATUS)
             if (n_undefs /=0) then
                allocate(buf3(size(ptr3,1),size(ptr3,2),size(ptr3,3)), stat=status)
                _VERIFY(STATUS)
                call MAPL_VarRead(unit, grid, buf3, rc=status)
                _VERIFY(STATUS)
                if (.not. associated(state%array_count(i)%ptr3c)) then
                   allocate(state%array_count(i)%ptr3c(size(ptr3,1),size(ptr3,2),size(ptr3,3)), stat=status)
                   _VERIFY(STATUS)
                end if
                state%array_count(i)%ptr3c = buf3
                deallocate(buf3)
             end if
          case (2)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(i), &
                  farrayPtr=ptr2, RC=status)
             _VERIFY(status)
             call MAPL_VarRead(unit, grid, ptr2, mask=mask, rc=status)
             _VERIFY(STATUS)
             if (n_undefs /=0) then
                allocate(buf2(size(ptr2,1),size(ptr2,2)), stat=status)
                _VERIFY(STATUS)
                call MAPL_VarRead(unit, grid, buf2, mask=mask, rc=status)
                _VERIFY(STATUS)
                if (.not. associated(state%array_count(i)%ptr2c)) then
                   allocate(state%array_count(i)%ptr2c(size(ptr2,1),size(ptr2,2)), stat=status)
                   _VERIFY(STATUS)
                end if
                state%array_count(i)%ptr2c = buf2
                deallocate(buf2)
             end if
          case (1)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(i), &
                  farrayPtr=ptr1, RC=status)
             _VERIFY(status)
             call MAPL_VarRead(unit, grid, ptr1, mask=mask, rc=status)
             _VERIFY(STATUS)
             if (n_undefs /=0) then
                allocate(buf1(size(ptr1,1)), stat=status)
                _VERIFY(STATUS)
                call MAPL_VarRead(unit, grid, buf1, mask=mask, rc=status)
                _VERIFY(STATUS)
                if (.not. associated(state%array_count(i)%ptr1c)) then
                   allocate(state%array_count(i)%ptr1c(size(ptr1,1)), stat=status)
                   _VERIFY(STATUS)
                end if
                state%array_count(i)%ptr1c = buf1
                deallocate(buf1)
             end if
          case default
             _FAIL( "Unsupported rank")
          end select
          _DEALLOC(mask)
       end do
       if (am_i_root) call Free_File(unit = UNIT, rc=STATUS)
    else
       RC = ESMF_RC_FILE_READ
       return
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine ReadRestart
Call graph
readrestart calls ESMF_CplCompGet, ESMF_CplCompGetInternalState, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, esmf_localarrayget, esmf_stateget, mapl_am_i_root, mapl_assert, mapl_commsbcast, mapl_deallocnodearray, mapl_syncsharedmemory, mapl_varread, mapl_varspecget, write_parallel, free_file, getfile, mapl_return, mapl_tilemaskget, mapl_verify