read_file – MAPL
read_file Subroutine
27 statements
Source File
public subroutine read_file(this)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
Calls
Called by
Call graph
read_file calls mpi_barrier, mapl_verify, read_level, read_variable
mapl_verify calls mapl_throw_exception
read_level calls mpi_barrier, mapl_verify, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_get_var, nf90_inq_varid
read_variable calls mpi_barrier, mapl_verify, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_get_var, nf90_inq_varid
checkpoint_tester calls read_file