realize_fields – MAPL
realize_fields Subroutine
35 statements
Source File
private subroutine realize_fields(model, import_state, export_state, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
type(ESMF_State) :: import_state
type(ESMF_State) :: export_state
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
    subroutine realize_fields(model, import_state, export_state, clock, rc)
        type(ESMF_GridComp)  :: model
        type(ESMF_State)     :: import_state, export_state
        type(ESMF_Clock)     :: clock
        integer, intent(out) :: rc
        type(MAPL_Cap), pointer             :: cap
        type(Field_Attributes), allocatable :: export_attributes(:), import_attributes(:)
        integer                             :: i, status
        _UNUSED_DUMMY(clock)
        cap => get_cap_from_gc(model, rc)
        VERIFY_NUOPC_(rc)
        export_attributes = get_field_attributes_from_state(cap%cap_gc%export_state)
        import_attributes = get_field_attributes_from_state(cap%cap_gc%import_state)
        do i = 1, size(export_attributes)
            associate(export => export_attributes(i))
                call MAPL_AllocateCoupling(export%field, status)
                _VERIFY(status)
                call NUOPC_Realize(export_state, field=export%field, rc=status)
                VERIFY_NUOPC_(status)
            end associate
        end do
        do i = 1, size(import_attributes)
            associate(import => import_attributes(i))
                call ESMF_FieldValidate(import%field, rc=status)
                VERIFY_NUOPC_(status)
                call NUOPC_Realize(import_state, field=import%field, rc=status)
                VERIFY_NUOPC_(status)
            end associate
        end do
        _RETURN(_SUCCESS)
    end subroutine realize_fields
Call graph
realize_fields calls ESMF_FieldValidate, ESMF_LogFoundError, NUOPC_Realize, mapl_allocatecoupling, get_cap_from_gc, get_field_attributes_from_state, mapl_return, mapl_verify
mapl_allocatecoupling calls mapl_allocatecoupling, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, ESMF_InfoIsPresent, mapl_fieldalloccommit
get_cap_from_gc calls ESMF_LogFoundError, mapl_return, ESMF_UserCompGetInternalState
get_field_attributes_from_state calls ESMF_FieldValidate, ESMF_LogFoundError, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, esmf_stateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_fieldalloccommit calls mapl_fieldalloccommit