record_component – MAPL
record_component Subroutine
38 statements
Source File
private subroutine record_component(POS, PHASE, METHOD, GC, IMPORT, EXPORT, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: POS
integer, intent(in) :: PHASE
type(ESMF_Method_Flag), intent(in) :: METHOD
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: IMPORT
type(ESMF_State), intent(inout) :: EXPORT
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine record_component(POS, PHASE, METHOD, GC, IMPORT, EXPORT, CLOCK, RC)
     character(len=*),       intent(IN   ) :: POS    ! Before or after
     integer,                intent(IN   ) :: PHASE  ! Phase
     type(ESMF_Method_Flag), intent(IN   ) :: METHOD ! Method
     type(ESMF_GridComp),    intent(INOUT) :: GC     ! Gridded component
     type(ESMF_State),       intent(INOUT) :: IMPORT ! Import state
     type(ESMF_State),       intent(INOUT) :: EXPORT ! Export state
     type(ESMF_Clock),       intent(INOUT) :: CLOCK  ! The clock
     integer, optional,      intent(  OUT) :: RC     ! Error code:
     type (MAPL_MetaComp), pointer :: STATE
     logical :: is_test_framework, is_test_framework_driver
     logical :: is_grid_capture, restore_export
     type(ESMF_Info) :: infoh
     integer :: status
     call MAPL_InternalStateGet (GC, STATE, _RC)
     call get_test_framework_resource(STATE, is_test_framework, is_test_framework_driver, &
                                      is_grid_capture, restore_export, _RC)
     if (method == ESMF_METHOD_INITIALIZE) then
        call ESMF_InfoGetFromHost(export,infoh,RC=STATUS)
        call ESMF_InfoSet(infoh, key="MAPL_RestoreExport", value=restore_export, _RC)
     else if (method == ESMF_METHOD_RUN) then
        call ESMF_InfoGetFromHost(import,infoh,RC=STATUS)
        call ESMF_InfoSet(infoh, key="MAPL_GridCapture", value=is_grid_capture, _RC)
        if (is_test_framework) then
           call capture(POS, phase, GC, import, export, clock, _RC)
        else if (is_test_framework_driver) then
           ! force skipReading and skipWriting in NCIO to be false
           call ESMF_InfoGetFromHost(import,infoh,RC=STATUS)
           call ESMF_InfoSet(infoh, key="MAPL_TestFramework", value=.true., _RC)
        end if
     end if
     _RETURN(_SUCCESS)
   end subroutine record_component
Call graph
record_component calls ESMF_InfoGetFromHost, ESMF_InfoSet, capture, get_test_framework_resource, mapl_internalstateget, mapl_return, mapl_verify
capture calls ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_internalstateget, mapl_return, mapl_verify, ESMF_ClockGet, ESMF_GridCompGet, mapl_getresource, get_internal_state, mapl_esmfstatewritetofile, parse_time_string
get_test_framework_resource calls mapl_return, mapl_verify, mapl_getresource
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_genericwrapper calls record_component