recurse_ – MAPL
recurse_ Subroutine
19 statements
Source File
private recursive subroutine recurse_(this, phase_idx, rc)
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout), target :: this
integer :: phase_idx
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine recurse_(this, phase_idx, rc)
      class(OuterMetaComponent), target, intent(inout) :: this
      integer :: phase_idx
      integer, optional, intent(out) :: rc
      integer :: status
      type(GriddedComponentDriverMapIterator) :: iter
      type(GriddedComponentDriver), pointer :: child
      associate(e => this%children%ftn_end())
        iter = this%children%ftn_begin()
        do while (iter /= e)
           call iter%next()
           child => iter%second()
           call child%initialize(phase_idx=phase_idx, _RC)
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine recurse_
Call graph
recurse_ calls initialize, mapl_return, mapl_verify, omap_ftn_begin, omap_ftn_end, omap_iter_next
initialize calls initialize, mapl_return, mapl_verify, ESMF_GridCompInitialize, initialize_advertise, initialize_geom, initialize_post_advertise, initialize_realize, initialize_user
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
omap_ftn_begin calls omap_k_ftn_begin
omap_ftn_end calls omap_k_ftn_end
omap_iter_next calls omap_k_iter_next
get_error_message calls at, insert
mapl_throw_exception calls initialize
recurse calls recurse_
initialize_advertise calls recurse
initialize_geom calls recurse
initialize_post_advertise calls recurse
initialize_realize calls recurse
initialize_user calls recurse
test_init_children calls initialize_user