register_imports – MAPL
register_imports Subroutine
34 statements
Source File
public subroutine register_imports(gridcomp, hconfig, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine register_imports(gridcomp, hconfig, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      type(ESMF_HConfigIter) :: iter, iter_begin, iter_end
      type(ESMF_HConfig) :: var_list
      character(len=:), allocatable :: item_name
      type(StringVector) :: variable_names
      type(HistoryOptions) :: options
      integer :: status
      ! Get Options for collection
      call parse_options(hconfig, options, _RC)
      ! Get variable list
      var_list = ESMF_HConfigCreateAt(hconfig, keystring=VAR_LIST_KEY, rc=status)
      if(status==ESMF_RC_NOT_FOUND) then
         _FAIL(VAR_LIST_KEY // ' was not found.')
      end if
      _VERIFY(status)
      iter_begin = ESMF_HConfigIterBegin(var_list,_RC)
      iter_end = ESMF_HConfigIterEnd(var_list,_RC)
      iter = iter_begin
      ! Add VariableSpec objects
      do while (ESMF_HConfigIterLoop(iter,iter_begin,iter_end,rc=status))
         _VERIFY(status)
         call parse_item(iter, item_name, variable_names, _RC)
         call parse_options(iter, options, _RC)
         call add_var_specs(gridcomp, variable_names, options, _RC)
      end do
      _RETURN(_SUCCESS)
   end subroutine register_imports
Call graph
register_imports calls ESMF_HConfigIterLoop, esmf_hconfigcreateat, esmf_hconfigiterbegin, esmf_hconfigiterend, ftn_begin, ftn_end, mapl_assert, mapl_gridcompaddvarspec, next, of, make_variablespec, mapl_return, mapl_verify
make_variablespec calls mapl_return
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setservices calls register_imports