regrid_scalar_3d_real32 – MAPL
regrid_scalar_3d_real32 Subroutine
61 statements
Source File
private subroutine regrid_scalar_3d_real32(this, q_in, q_out, rc)
Uses
MAPL_BaseMod
MAPL_CommsMod
Type Bound
LatLonToLatLonRegridder
Arguments
Type Intent Optional Attributes Name
class(LatLonToLatLonRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: q_in(:,:,:)
real(kind=REAL32), intent(out) :: q_out(:,:,:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_scalar_3d_real32(this, q_in, q_out, rc)
      use MAPL_CommsMod
      use MAPL_BaseMod
      class (LatLonToLatLonRegridder), intent(in) :: this
      real (kind=REAL32), intent(in) :: q_in(:,:,:)
      real (kind=REAL32), intent(out) :: q_out(:,:,:)
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME//'regrid_scalar_2d_real32'
      integer :: k
      type (RegridderSpec) :: spec
      logical :: redistribute
      _ASSERT(size(q_in,3) == size(q_out,3), 'inconsistent array shape')
      spec = this%get_spec()
      block
        integer :: N_in(NUM_DIMS)
        integer :: dims(5)
        call MAPL_GridGet(spec%grid_in, globalCellCountPerDim=dims, rc=status)
        _VERIFY(status)
        N_in = dims(1:2)
        if ((N_in(1) /= size(q_in,1)) .or. (N_in(2) /= size(q_in,2))) then
           redistribute = .true.
        else
           redistribute = .false.
        end if
      end block
      if (redistribute) then
         block
           real (kind=REAL32), pointer :: q_in_global(:,:,:)
           real (kind=REAL32), allocatable :: q_out_global(:,:,:)
           integer :: N_out(NUM_DIMS)
           integer :: dims(5)
           q_in_global=> null()
           call MAPL_CollectiveGather3D(spec%grid_in, q_in, q_in_global, rc=status)
           _VERIFY(status)
           call MAPL_GridGet(spec%grid_out, globalCellCountPerDim=dims, rc=status)
           _VERIFY(status)
           N_out = dims(1:2)
           allocate(q_out_global(n_out(1), n_out(2), size(q_in_global,3)))
           if (size(q_in_global) > 1) then
              do k = 1, size(q_in_global,3)
                 call this%regrid(q_in_global(:,:,k), q_out_global(:,:,k), rc=status)
                 _VERIFY(status)
              end do
           end if
           deallocate(q_in_global)
           call MAPL_CollectiveScatter3D(spec%grid_out, q_out_global, q_out, rc=status)
           _VERIFY(status)
           deallocate(q_out_global)
         end block
      else
         if (size(q_in) > 1) then
            do k = 1, size(q_in,3)
               call this%regrid(q_in(:,:,k), q_out(:,:,k), rc=status)
               _VERIFY(status)
            end do
         end if
      end if
      _RETURN(_SUCCESS)
   end subroutine regrid_scalar_3d_real32
Call graph
regrid_scalar_3d_real32 calls dims, mapl_assert, regrid, get_spec, mapl_collectivegather3d, mapl_collectivescatter3d, mapl_gridget, mapl_return, mapl_verify, q_in_global, q_out_global
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_collectivegather3d calls mapl_assert, mapl_gridget, mapl_return, mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent, mapl_arrayigather, mapl_collectivewait, mapl_createrequest, mapl_roundrobinpelist
mapl_collectivescatter3d calls mapl_assert, mapl_return, mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent, mapl_arrayiscatter, mapl_collectivewait, mapl_createrequest, mapl_roundrobinpelist
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception