regrid_method_int_to_string – MAPL
regrid_method_int_to_string Function
32 statements
Source File
public function regrid_method_int_to_string(int_regrid_method) result(string_regrid_method)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: int_regrid_method
Return Value character(len=:), allocatable
Called by
Call graph
createvariable calls regrid_method_int_to_string
initialize calls regrid_method_int_to_string, createfilemetadata
createfilemetadata calls createvariable
create_from_bundle calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle