remove_variable – MAPL
remove_variable Subroutine
24 statements
Source File
private subroutine remove_variable(this, var_name, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: var_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine remove_variable(this, var_name, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: var_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(StringVectorIterator)      :: viter
      type(StringVariableMapIterator) :: miter
      viter = this%order%begin()
      do while (viter /= this%order%end())
         if ( var_name == viter%get() ) then
           call  this%order%erase(viter)
           exit
         endif
         call viter%next()
      enddo
      miter = this%variables%find(var_name)
      miter = this%variables%erase(miter)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine remove_variable
Call graph
remove_variable calls begin, erase, get, next, map_find, mapl_return
map_find calls map_s_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
mapl_throw_exception calls initialize
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan