report_global_profiler – MAPL
report_global_profiler Subroutine
75 statements
Source File
public subroutine report_global_profiler(unusable, comm, rc)
Uses
pflogger
mpi
mapl_KeywordEnforcerMod
mapl_ErrorHandlingMod
$ call inclusive%add_column(FormattedTextColumn(’ % ‘,’(f6.2)’, 6, PercentageColumn(InclusiveColumn()), separator=’-‘)) $ call exclusive%add_column(FormattedTextColumn(’ % ‘,’(f6.2)’, 6, PercentageColumn(ExclusiveColumn()), separator=’-‘))
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine report_global_profiler(unusable,comm,rc)
      use mapl_KeywordEnforcerMod
      use mapl_ErrorHandlingMod
      use mpi
      use pflogger, only: logging
      use pflogger, only: Logger
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      integer, optional, intent(out) :: rc
      type (ProfileReporter) :: reporter
      integer :: i, world_comm
      character(:), allocatable :: report_lines(:)
      type (MultiColumn) :: inclusive
      type (MultiColumn) :: exclusive
      integer :: npes, my_rank, ierror
      character(1) :: empty(0)
      class (BaseProfiler), pointer :: t_p
      class (BaseProfiler), pointer :: m_p
      type(Logger), pointer :: lgr
      if (present(comm)) then
         world_comm = comm
      else
         world_comm=MPI_COMM_WORLD
      end if
      call MPI_Comm_size(world_comm, npes, ierror)
      _VERIFY(ierror)
      call MPI_Comm_Rank(world_comm, my_rank, ierror)
      _VERIFY(ierror)
      t_p => get_global_time_profiler()
      if (t_p%get_num_meters() > 0) then
         reporter = ProfileReporter(empty)
         call reporter%add_column(NameColumn(50, separator= " "))
         call reporter%add_column(FormattedTextColumn('#-cycles','(i8.0)', 8, NumCyclesColumn(),separator='-'))
         inclusive = MultiColumn(['Inclusive'], separator='=')
         call inclusive%add_column(FormattedTextColumn(' T (sec) ','(f9.3)', 9, InclusiveColumn(), separator='-'))
         call inclusive%add_column(FormattedTextColumn('   %  ','(f6.2)', 6, PercentageColumn(InclusiveColumn(),'MAX'),separator='-'))
         call reporter%add_column(inclusive)
         exclusive = MultiColumn(['Exclusive'], separator='=')
         call exclusive%add_column(FormattedTextColumn(' T (sec) ','(f9.3)', 9, ExclusiveColumn(), separator='-'))
         call exclusive%add_column(FormattedTextColumn('   %  ','(f6.2)', 6, PercentageColumn(ExclusiveColumn()), separator='-'))
         call reporter%add_column(exclusive)
         if (my_rank == 0) then
            report_lines = reporter%generate_report(t_p)
            lgr => logging%get_logger('MAPL.profiler')
            call lgr%info('Report on process: %i0', my_rank)
            do i = 1, size(report_lines)
               call lgr%info('%a', report_lines(i))
            end do
         end if
      end if
      m_p => get_global_memory_profiler()
      if (m_p%get_num_meters() > 0) then
         reporter = ProfileReporter(empty)
         call reporter%add_column(NameColumn(50, separator= " "))
         inclusive = MultiColumn(['Inclusive'], separator='=')
         call inclusive%add_column(MemoryTextColumn(['  MEM  '],'(i4,1x,a2)', 9, InclusiveColumn(), separator='-'))
!!$      call inclusive%add_column(FormattedTextColumn('   %  ','(f6.2)', 6, PercentageColumn(InclusiveColumn()), separator='-'))
         call reporter%add_column(inclusive)
         exclusive = MultiColumn(['Exclusive'], separator='=')
         call exclusive%add_column(MemoryTextColumn(['  MEM  '],'(i4,1x,a2)', 9, ExclusiveColumn(), separator='-'))
         call exclusive%add_column(FormattedTextColumn(' MEM (KB)','(-3p,f15.3, 0p)', 15, ExclusiveColumn(), separator='-'))
!!$      call exclusive%add_column(FormattedTextColumn('   %  ','(f6.2)', 6, PercentageColumn(ExclusiveColumn()), separator='-'))
         call reporter%add_column(exclusive)
         if (my_rank == 0) then
            report_lines = reporter%generate_report(m_p)
            lgr => logging%get_logger('MAPL.profiler')
            do i = 1, size(report_lines)
               call lgr%info('%a', report_lines(i))
            end do
         end if
      end if
      call MPI_Barrier(world_comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine report_global_profiler
Call graph
report_global_profiler calls mpi_barrier, mpi_comm_rank, mpi_comm_size, generate_report, get_logger, add_column, get_global_memory_profiler, get_global_time_profiler, get_num_meters, info, mapl_return, mapl_verify
add_column calls get_num_rows_header, get_num_rows_separator, get_width, set_width, vector_push_back
get_num_meters calls get_num_nodes
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
finalize calls report_global_profiler
run calls finalize
extdata_driver calls run