report – MAPL
report Subroutine
21 statements
Source File
private subroutine report(this, rc)
Uses
mapl3g_FieldSpec
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in), target :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine report(this, rc)
      use mapl3g_FieldSpec
      class(HierarchicalRegistry), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      type(ActualPtSpecPtrMapIterator) :: actual_iter
      type(ActualConnectionPt), pointer :: actual_pt
      type(StateItemSpecPtr), pointer :: item_spec_ptr
      class(StateItemSpec), pointer :: item_spec
      associate (e => this%actual_specs_map%end())
        actual_iter = this%actual_specs_map%begin()
        do while (actual_iter /= e)
           actual_pt => actual_iter%first()
           item_spec_ptr =>  actual_iter%second()
           item_spec => item_spec_ptr%ptr
           call actual_iter%next()
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine report
Call graph
report calls map_begin, map_iter_first, map_iter_next, mapl_return
map_begin calls map_s_begin
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_iter_of calls map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
map_s_advpos calls map_s_get_child, to_node
map_s_iter_of calls map_s_get_value