resource_get_i4seq_gc – MAPL
resource_get_i4seq_gc Subroutine
25 statements
Source File
private subroutine resource_get_i4seq_gc(gc, keystring, value, unusable, default, value_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: keystring
integer(kind=ESMF_KIND_I4), intent(inout), dimension(:), allocatable :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer(kind=ESMF_KIND_I4), intent(in), optional, dimension(:) :: default
logical, intent(out), optional :: value_set
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine resource_get_i4seq_gc(gc, keystring, value, unusable, default, value_set, rc)
      integer(kind=ESMF_KIND_I4), dimension(:), allocatable, intent(inout) :: value
      integer(kind=ESMF_KIND_I4), dimension(:), optional, intent(in) :: default
      type(ESMF_GridComp), intent(inout) :: gc
      character(len=*), intent(in) :: keystring
      class(KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(out) :: value_set
      integer, optional, intent(out) :: rc
      class(Logger_t), pointer :: logger
      type(ESMF_HConfig) :: hconfig
      type(HConfigParams) :: params
      integer :: status
      call MAPL_GridCompGet(gc, hconfig=hconfig, logger=logger, _RC)
      params = HConfigParams(hconfig, keystring, value_set, logger)
      call MAPL_HConfigGet(params, value, default, _RC)
      if(present(value_set)) value_set = params%value_set
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine resource_get_i4seq_gc
Call graph
resource_get_i4seq_gc calls get_value, mapl_gridcompget, mapl_return, mapl_verify
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
mapl_gridcompget calls gridcomp_get
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_value_i4 calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_i4seq calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_i8 calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_i8seq calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_logical calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_logical_seq calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_r4 calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_r4seq calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_r8 calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_r8seq calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
get_value_string calls mapl_return, mapl_verify, esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt
gridcomp_get calls mapl_return, mapl_verify, mapl_gridcompgetoutermeta, get_hconfig, get_lgr, get_registry
mapl_throw_exception calls initialize
mapl_resourceget calls resource_get_i4seq_gc
setservices calls mapl_resourceget