rewind_clock – MAPL
rewind_clock Subroutine
39 statements
Source File
private subroutine rewind_clock(this, time, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
type(ESMF_Time), intent(inout) :: time
integer, intent(out) :: rc
Calls
Called by
Source Code
  subroutine rewind_clock(this, time, rc)
    class(MAPL_CapGridComp), intent(inout) :: this
    type(ESMF_Time), intent(inout) :: time
    integer, intent(out) :: rc
    integer :: status
    type(ESMF_Time) :: current_time,ct
    call ESMF_ClockGet(this%clock,currTime=current_time,rc=status)
    _VERIFY(status)
    if (current_time >  time) then
       call ESMF_ClockSet(this%clock,direction=ESMF_DIRECTION_REVERSE,rc=status)
       _VERIFY(status)
       do
          call ESMF_ClockAdvance(this%clock,rc=status)
          _VERIFY(status)
          call ESMF_ClockGet(this%clock,currTime=ct,rc=status)
          _VERIFY(status)
          if (ct==time) exit
       enddo
       call ESMF_ClockSet(this%clock,direction=ESMF_DIRECTION_FORWARD,rc=status)
       _VERIFY(status)
    end if
    call ESMF_ClockGet(this%clock_hist,currTime=current_time,rc=status)
    _VERIFY(status)
    if (current_time >  time) then
       call ESMF_ClockSet(this%clock_hist,direction=ESMF_DIRECTION_REVERSE,rc=status)
       _VERIFY(status)
       do
          call ESMF_ClockAdvance(this%clock_hist,rc=status)
          _VERIFY(status)
          call ESMF_ClockGet(this%clock_hist,currTime=ct,rc=status)
          _VERIFY(status)
          if (ct==time) exit
       enddo
       call ESMF_ClockSet(this%clock_hist,direction=ESMF_DIRECTION_FORWARD,rc=status)
       _VERIFY(status)
    end if
    _RETURN(_SUCCESS)
  end subroutine rewind_clock
Call graph
rewind_clock calls ESMF_ClockAdvance, ESMF_ClockGet, ESMF_ClockSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
rewind_model calls rewind_clock