run_child_by_name – MAPL
run_child_by_name Subroutine
22 statements
Source File
private recursive subroutine run_child_by_name(this, child_name, unusable, phase_name, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
character(len=*), intent(in) :: child_name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: phase_name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine run_child_by_name(this, child_name, unusable, phase_name, rc)
      class(OuterMetaComponent), intent(inout) :: this
      character(len=*), intent(in) :: child_name
      class(KE), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: phase_name
      integer, optional, intent(out) :: rc
      integer :: status
      type(GriddedComponentDriver) :: child
      logical :: found
      integer :: phase_idx
      child = this%get_child(child_name, _RC)
      phase_idx = 1
      if (present(phase_name)) then
         phase_idx = get_phase_index(this%get_phases(ESMF_METHOD_RUN), phase_name=phase_name, found=found)
         _ASSERT(found, "run phase: <"//phase_name//"> not found.")
      end if
      call child%run(phase_idx=phase_idx, _RC)
      _RETURN(_SUCCESS)
   end subroutine run_child_by_name
Call graph
run_child_by_name calls get_phase_index, mapl_assert, run, get_child, get_phases, mapl_return, mapl_verify, run_child
get_phase_index calls get_phase_index_
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
run calls run, mapl_return, mapl_verify, ESMF_GridCompRun, run_export_couplers, run_import_couplers, run_children, mapl_runchild
get_phases calls map_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_child_by_name calls mapl_assert, mapl_return, at
get_error_message calls at, insert
get_phase_index_ calls begin, distance, find
map_of calls insert, map_s_iter_of
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run_children_ calls run_child
mapl_runchild calls run_child_by_name
run_children calls run_children
test_mapl_runchild calls mapl_runchild
test_mapl_runchild_other_phase calls mapl_runchild