run_geos – MAPL
run_geos Subroutine
20 statements
Source File
subroutine run_geos(hconfig, is_model_pet, servers, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(inout) :: hconfig
logical, intent(in) :: is_model_pet
type(ESMF_GridComp), intent(in), optional :: servers(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run_geos(hconfig, is_model_pet, servers, rc)
      type(ESMF_HConfig), intent(inout) :: hconfig
      logical, intent(in) :: is_model_pet
      type(ESMF_GridComp), optional, intent(in) :: servers(:)
      integer, optional, intent(out) :: rc
      logical :: has_cap_hconfig
      type(ESMF_HConfig) :: cap_hconfig
      integer :: status
      has_cap_hconfig = ESMF_HConfigIsDefined(hconfig, keystring='cap', _RC)
      _ASSERT(has_cap_hconfig, 'No cap section found in configuration file')
      cap_hconfig = ESMF_HConfigCreateAt(hconfig, keystring='cap', _RC)
      call MAPL_run_driver(cap_hconfig, is_model_pet=is_model_pet, servers=servers, _RC)
      call ESMF_HConfigDestroy(cap_hconfig, _RC)
      _RETURN(_SUCCESS)
   end subroutine run_geos
Call graph
run_geos calls ESMF_HConfigDestroy, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_run_driver, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_run_driver calls esmf_hconfigcreateat, mapl_return, mapl_verify, ESMF_CalendarSetDefault, ESMF_ClockCreate, ESMF_ClockGet, ESMF_TimePrint, ESMF_TimeSet, ESMF_VMGet, ESMF_VMGetCurrent, esmf_gridcompsetservices, esmf_hconfigasstring, create_grid_comp, user_setservices, mpi_allgather, clock_advance, finalize, get_clock, run, hconfig_to_esmf_timeinterval, initialize_phases
mapl_verify calls mapl_throw_exception
hconfig_to_esmf_timeinterval calls mapl_return, mapl_verify, esmf_hconfigasstring, string_to_esmf_timeinterval
initialize_phases calls mapl_return, mapl_verify, initialize
string_to_esmf_timeinterval calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeIntervalSet
geos calls run_geos