run_custom – MAPL
run_custom Subroutine
30 statements
Source File
private subroutine run_custom(this, method_flag, phase_name, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
type(ESMF_Method_Flag), intent(in) :: method_flag
character(len=*), intent(in) :: phase_name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run_custom(this, method_flag, phase_name, rc)
      class(OuterMetaComponent), intent(inout) :: this
      type(ESMF_METHOD_FLAG), intent(in) :: method_flag
      character(*), intent(in) :: phase_name
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: phase_idx
      type(StringVector), pointer :: phases
      logical :: found
      phases => this%get_phases(method_flag)
      phase_idx = get_phase_index(phases, phase_name, found=found)
      _RETURN_UNLESS(found)
      if (method_flag == ESMF_METHOD_INITIALIZE) then
         call this%user_gc_driver%initialize(phase_idx=phase_idx, _RC)
      else if (method_flag == ESMF_METHOD_RUN) then
         call this%user_gc_driver%run(phase_idx=phase_idx, _RC)
      else if (method_flag == ESMF_METHOD_FINALIZE) then
         call this%user_gc_driver%finalize(phase_idx=phase_idx, _RC)
      else
         _FAIL('Unknown ESMF method flag.')
      end if
      _RETURN(_SUCCESS)
   end subroutine run_custom
Call graph
run_custom calls finalize, get_phase_index, initialize, mapl_assert, run, get_phases, mapl_return, mapl_verify
finalize calls finalize, mapl_return, mapl_verify, ESMF_GridCompFinalize, run_custom
get_phase_index calls get_phase_index_
initialize calls initialize, mapl_return, mapl_verify, ESMF_GridCompInitialize, initialize_advertise, initialize_geom, initialize_post_advertise, initialize_realize, initialize_user
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
run calls run, mapl_return, mapl_verify, ESMF_GridCompRun, run_export_couplers, run_import_couplers
get_phases calls map_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_phase_index_ calls begin, distance, find
map_of calls insert, map_s_iter_of
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_advertise calls run_custom
initialize_geom calls run_custom
initialize_post_advertise calls run_custom
initialize_realize calls run_custom
initialize_user calls run_custom
test_finalize_children calls finalize
test_init_children calls initialize_user