run_ProcSetServices – MAPL
run_ProcSetServices Subroutine
11 statements
Source File
private subroutine run_ProcSetServices(this, gridComp, rc)
Type Bound
ProcSetServices
Arguments
Type Intent Optional Attributes Name
class(ProcSetServices), intent(in) :: this
type(ESMF_GridComp) :: gridComp
integer, intent(out) :: rc
Calls
Source Code
   subroutine run_ProcSetServices(this, gridcomp, rc)
      class(ProcSetServices), intent(in) :: this
      type(ESMF_GridComp) :: gridComp
      integer, intent(out) :: rc
      integer :: status, userRC
      call ESMF_GridCompSetServices(gridcomp, this%userRoutine, userRC=userRC, _RC)
      _VERIFY(userRC)
      _RETURN(ESMF_SUCCESS)
   end subroutine run_ProcSetServices
Call graph
run_procsetservices calls esmf_gridcompsetservices, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize