run_children – MAPL
run_children Subroutine
18 statements
Source File
private subroutine run_children(gridcomp, unusable, phase_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: phase_name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run_children(gridcomp, unusable, phase_name, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), intent(in) :: phase_name
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      call outer_meta%run_children(phase_name=phase_name, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine run_children
Call graph
run_children calls mapl_gridcompgetoutermeta, run_children, mapl_return, mapl_verify
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
run_children_ calls mapl_return, mapl_verify, run_child, omap_ftn_begin, omap_ftn_end, omap_iter_first, omap_iter_next
get_outer_meta calls get_outer_meta_from_outer_gc
mapl_gridcompisgeneric calls gridcomp_is_generic
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
omap_ftn_begin calls omap_k_ftn_begin
omap_ftn_end calls omap_k_ftn_end
omap_iter_first calls omap_iter_at
omap_iter_next calls omap_k_iter_next
mapl_runchildren calls run_children
run calls mapl_runchildren