run_import_couplers – MAPL
run_import_couplers Module Subroutine
18 statements
Source File
recursive module subroutine run_import_couplers(this, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriver), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive module subroutine run_import_couplers(this, rc)
      class(GriddedComponentDriver), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      type(ComponentDriverVectorIterator) :: iter
      class(ComponentDriver), pointer :: driver
      associate (e => this%import_couplers%ftn_end() )
        iter = this%import_couplers%ftn_begin()
        do while (iter /= e)
           call iter%next()
           driver => iter%of()
           call driver%run(phase_idx=GENERIC_COUPLER_UPDATE, _RC)
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine run_import_couplers
Call graph
run_import_couplers calls of, mapl_return, mapl_verify, vector_ftn_begin, vector_ftn_end, vector_iter_next, run, run_import_couplers
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run calls run_import_couplers, run
integrate calls run
run_child_by_name calls run
run_clock_advance calls run
run_custom calls run
update_source calls run