run_export_couplers – MAPL
run_export_couplers Module Subroutine
20 statements
Source File
recursive module subroutine run_export_couplers(this, unusable, phase_idx, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(GriddedComponentDriver), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: phase_idx
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive module subroutine run_export_couplers(this, unusable, phase_idx, rc)
      class(GriddedComponentDriver), intent(inout) :: this
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(in) :: phase_idx
      integer, optional, intent(out) :: rc
      integer :: status
      type(ComponentDriverVectorIterator) :: iter
      class(ComponentDriver), pointer :: driver
      associate (e => this%export_couplers%ftn_end() )
        iter = this%export_couplers%ftn_begin()
        do while (iter /= e)
           call iter%next()
           driver => iter%of()
           call driver%run(phase_idx=GENERIC_COUPLER_INVALIDATE, _RC)
        end do
      end associate
      _RETURN(_SUCCESS)
   end subroutine run_export_couplers
Call graph
run_export_couplers calls of, mapl_return, mapl_verify, vector_ftn_begin, vector_ftn_end, vector_iter_next, run, run_export_couplers
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run calls run_export_couplers, run
integrate calls run
run_child_by_name calls run
run_clock_advance calls run
run_custom calls run
update_source calls run