run_DSOSetServices – MAPL
run_DSOSetServices Subroutine
14 statements
Source File
private subroutine run_DSOSetServices(this, GridComp, rc)
Uses
mapl_DSO_Utilities
Type Bound
DSOSetServices
Arguments
Type Intent Optional Attributes Name
class(DSOSetServices), intent(in) :: this
type(ESMF_GridComp) :: GridComp
integer, intent(out) :: rc
Calls
Source Code
   subroutine run_DSOSetServices(this, gridcomp, rc)
      use mapl_DSO_Utilities
      class(DSOSetservices), intent(in) :: this
      type(ESMF_GridComp) :: GridComp
      integer, intent(out) :: rc
      integer :: status, userRC
      logical :: found
      _ASSERT(is_supported_dso_name(this%sharedObj), 'unsupported dso name:: <'//this%sharedObj//'>')
      call ESMF_GridCompSetServices(gridcomp, sharedObj=adjust_dso_name(this%sharedObj), &
           userRoutine=this%userRoutine, userRoutinefound=found, userRC=userRC, rc=status)
      _VERIFY(userRC)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine run_DSOSetServices
Call graph
run_dsosetservices calls esmf_gridcompsetservices, mapl_assert, adjust_dso_name, is_supported_dso_name, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
adjust_dso_name calls get_file_basename
is_supported_dso_name calls get_file_extension, is_supported_dso_extension
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_file_basename calls find_extension_index
get_file_extension calls find_extension_index
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize