run_clock_advance – MAPL
run_clock_advance Subroutine
21 statements
Source File
private recursive subroutine run_clock_advance(this, unusable, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine run_clock_advance(this, unusable, rc)
      class(OuterMetaComponent), intent(inout) :: this
      ! optional arguments
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type(GriddedComponentDriverMapIterator) :: iter
      type(GriddedComponentDriver), pointer :: child
      associate(e => this%children%ftn_end())
        iter = this%children%ftn_begin()
        do while (iter /= e)
           call iter%next()
           child => iter%second()
           call child%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
        end do
      end associate
      call this%user_gc_driver%clock_advance(_RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine run_clock_advance
Call graph
run_clock_advance calls clock_advance, run, mapl_return, mapl_verify, omap_ftn_begin, omap_ftn_end, omap_iter_next
clock_advance calls clock_advance, mapl_return, mapl_verify, ESMF_ClockAdvance
run calls run, mapl_return, mapl_verify, ESMF_GridCompRun, run_export_couplers, run_import_couplers, run_clock_advance
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
omap_ftn_begin calls omap_k_ftn_begin
omap_ftn_end calls omap_k_ftn_end
omap_iter_next calls omap_k_iter_next
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_export_couplers calls run_export_couplers
run_import_couplers calls run_import_couplers