run_child_by_name – MAPL
run_child_by_name Subroutine
19 statements
Source File
private subroutine run_child_by_name(gridcomp, child_name, unusable, phase_name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
character(len=*), intent(in) :: child_name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: phase_name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run_child_by_name(gridcomp, child_name, unusable, phase_name, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      character(len=*), intent(in) :: child_name
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: phase_name
      integer, optional, intent(out) :: rc
      integer :: status
      type(OuterMetaComponent), pointer :: outer_meta
      call MAPL_GridCompGetOuterMeta(gridcomp, outer_meta, _RC)
      call outer_meta%run_child(child_name, phase_name=phase_name, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine run_child_by_name
Call graph
run_child_by_name calls mapl_gridcompgetoutermeta, run_child, mapl_return, mapl_verify, get_phase_index, mapl_assert, run, get_child, get_phases
mapl_gridcompgetoutermeta calls gridcomp_get_outer_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
gridcomp_get_outer_meta calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisgeneric, get_outer_gridcomp
mapl_throw_exception calls initialize
get_outer_meta calls get_outer_meta_from_outer_gc
get_phase_index calls get_phase_index_
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridcompisgeneric calls gridcomp_is_generic
run calls run, mapl_runchild
get_outer_gridcomp calls mapl_return, mapl_verify, mapl_assert, mapl_gridcompisuser, get_inner_meta, get_outer_gridcomp
get_phases calls map_of
mapl_runchild calls run_child_by_name
test_mapl_runchild calls mapl_runchild
test_mapl_runchild_other_phase calls mapl_runchild