run – MAPL
run Subroutine
18 statements
Source File
public subroutine run(this, importState, exportState, clock, rc)
Uses
ESMF
Type Bound
CopyAction
Arguments
Type Intent Optional Attributes Name
class(CopyAction), intent(inout) :: this
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine run(this, importState, exportState, clock, rc)
      use esmf
      class(CopyAction), intent(inout) :: this
      type(ESMF_State)      :: importState
      type(ESMF_State)      :: exportState
      type(ESMF_Clock)      :: clock
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Field) :: f_in, f_out
      call ESMF_StateGet(importState, itemName='import[1]', field=f_in, _RC)
      call ESMF_StateGet(exportState, itemName='export[1]', field=f_out, _RC)
      call FieldCopy(f_in, f_out, _RC)
      _RETURN(_SUCCESS)
   end subroutine run
Call graph
run calls esmf_stateget, fieldcopy, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception