run – MAPL
run Subroutine
27 statements
Source File
public subroutine run(this, rc)
Type Bound
ConvertUnitsAction
Arguments
Type Intent Optional Attributes Name
class(ConvertUnitsAction), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine run(this, rc)
      class(ConvertUnitsAction), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_TypeKind_Flag) :: typekind
      real(kind=ESMF_KIND_R4), pointer :: x4_in(:)
      real(kind=ESMF_KIND_R4), pointer :: x4_out(:)
      real(kind=ESMF_KIND_R8), pointer :: x8_in(:)
      real(kind=ESMF_KIND_R8), pointer :: x8_out(:)
      call ESMF_FieldGet(this%f_in, typekind=typekind, _RC)
      if (typekind == ESMF_TYPEKIND_R4) then
         call assign_fptr(this%f_in, x4_in, _RC)
         call assign_fptr(this%f_out, x4_out, _RC)
         x4_out = this%converter%convert(x4_in)
      elseif (typekind == ESMF_TYPEKIND_R8) then
         call assign_fptr(this%f_in, x8_in, _RC)
         call assign_fptr(this%f_out, x8_out, _RC)
         x8_out = this%converter%convert(x8_in)
      end if
      _RETURN(_SUCCESS)
   end subroutine run
Call graph
run calls convert, esmf_fieldget, assign_fptr, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception