run – MAPL
run Subroutine
23 statements
Source File
private recursive subroutine run(gridcomp, importState, exportState, clock, rc)
Uses
gFTL2_StringVector
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine run(gridcomp, importState, exportState, clock, rc)
      use gFTL2_StringVector
      type(ESMF_GridComp) :: gridcomp
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      integer :: status
      integer :: phase
      character(:), pointer :: phase_name
      type(OuterMetaComponent), pointer :: outer_meta
      type(StringVector), pointer :: phases
      outer_meta => get_outer_meta(gridcomp, _RC)
      call ESMF_GridCompGet(gridcomp, currentPhase=phase, _RC)
      phases => outer_meta%get_phases(ESMF_METHOD_RUN)
      phase_name => phases%of(phase)
      call outer_meta%run(phase_name=phase_name, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine run
Call graph
run calls ESMF_GridCompGet, get_outer_meta, of, get_phases, mapl_return, mapl_verify, run, get_phase_index, get_export_couplers, get_import_couplers, map_ftn_begin, map_ftn_end, map_iter_next, run_clock_advance
get_outer_meta calls get_outer_meta_from_outer_gc
get_phases calls map_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception