s_orderEq – MAPL
s_orderEq Function
5 statements
Source File
private function s_orderEq(x, y) result(equal)
Arguments
Type Intent Optional Attributes Name
type(pair), intent(in) :: x
type(pair), intent(in) :: y
Return Value logical
Calls
Called by
Call graph
s_ordereq calls s_lessthan
find_index calls s_ordereq
s_find calls s_ordereq, find_index
s_insert calls s_ordereq, find_index
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_count calls s_find
s_deepcopy calls s_insert
s_remove calls s_find
m_at calls m_find
m_deepcopy calls s_deepcopy
remove_attribute calls m_find, remove_attribute
start_back calls m_find, insert
add_attribute_0d calls insert
add_attribute_1d calls insert
equal calls m_at
get_attribute calls m_at
is_attribute_present calls m_at
m_new_map_from_pair_array calls insert
put_datatofile calls insert
start calls start_back
stringattributemap_deserialize calls insert
transfer_metadata calls m_at