same_geom – MAPL
same_geom Function
14 statements
Source File
private function same_geom(geom_a, geom_b)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(in) :: geom_a
type(ESMF_Geom), intent(in) :: geom_b
Return Value logical
Calls
Called by
Source Code
   logical function same_geom(geom_a, geom_b)
      type(ESMF_Geom), intent(in) :: geom_a
      type(ESMF_Geom), intent(in) :: geom_b
      logical :: has_id_a
      logical :: has_id_b
      integer :: id_a
      integer :: id_b
      same_geom = .false. ! unless
      id_a = MAPL_GeomGetId(geom_a, isPresent=has_id_a)
      id_b = MAPL_GeomGetId(geom_b, isPresent=has_id_b)
      if (has_id_a .and. has_id_b) then
         same_geom = (id_a == id_b)
      end if
   end function same_geom
Call graph
same_geom calls mapl_geomgetid
mapl_geomgetid calls ESMF_InfoGet, ESMF_InfoGetFromHost, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_samegeom calls same_geom
equal_to calls mapl_samegeom
make_action calls mapl_samegeom, match, make_action
match_geom calls mapl_samegeom
match calls match_geom
operator(==) calls equal_to
can_connect_units calls match
get_cost_geom calls match
get_cost_string calls match
get_cost_typekind calls match
update_item_geom calls match
update_item_string calls match
update_item_typekind calls match