serialize – MAPL
serialize Subroutine
12 statements
Source File
private subroutine serialize(this, buffer, rc)
Type Bound
ModifyMetadataMessage
Arguments
Type Intent Optional Attributes Name
class(ModifyMetadataMessage), intent(in) :: this
integer, intent(inout) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine serialize(this, buffer, rc)
      class (ModifyMetadataMessage), intent(in) :: this
      integer, intent(inout) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer, allocatable ::  map_buf(:)
      integer :: status
      call StringVariableMap_serialize(this%var_map, map_buf, rc=status)
      _VERIFY(status)
      buffer = [ &
           & serialize_intrinsic(this%collection_id), &
           & map_buf]
      _RETURN(_SUCCESS)
   end subroutine serialize
Call graph
serialize calls serialize_intrinsic, mapl_return, mapl_verify, stringvariablemap_serialize
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
stringvariablemap_serialize calls serialize_intrinsic, mapl_return, mapl_verify, serialize_buffer_length, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, serialize