serialize_real64_0d – MAPL
serialize_real64_0d Function
8 statements
Source File
private function serialize_real64_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
Calls
Called by
Source Code
   function serialize_real64_0d(scalar, rc) result(buffer)
      integer(kind=INT32), allocatable :: buffer(:)
      real(kind=REAL64), intent(in) :: scalar
      integer, optional, intent(out) :: rc
      buffer = [transfer(scalar,[1])]
      _RETURN(_SUCCESS)
   end function serialize_real64_0d
Call graph
serialize_real64_0d calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
serialize_intrinsic calls serialize_real64_0d
serialize calls serialize_intrinsic
stringattributemap_serialize calls serialize_intrinsic
stringintegermap_serialize calls serialize_intrinsic
stringunlimitedentitymap_serialize calls serialize_intrinsic
stringvariablemap_serialize calls serialize_intrinsic
stringvector_serialize calls serialize_intrinsic
test_serialize_int64_array calls serialize_intrinsic
test_serialize_int64_scalar calls serialize_intrinsic
test_serialize_int_array calls serialize_intrinsic
test_serialize_int_scalar calls serialize_intrinsic
test_serialize_logical_array calls serialize_intrinsic
test_serialize_logical_scalar calls serialize_intrinsic
test_serialize_real_array calls serialize_intrinsic
test_serialize_real_scalar calls serialize_intrinsic
test_serialize_string calls serialize_intrinsic