set_is_generic – MAPL
set_is_generic Subroutine
16 statements
Source File
private subroutine set_is_generic(gridcomp, flag, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
logical, intent(in), optional :: flag
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_is_generic(gridcomp, flag, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      logical, optional, intent(in) :: flag
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: flag_
      type(ESMF_Info) :: info
      flag_ = .true.
      if (present(flag)) flag_ = flag
      call ESMF_InfoGetFromHost(gridcomp, info, _RC)
      call ESMF_InfoSet(info, key='MAPL/GRIDCOMP_IS_GENERIC', value=flag_, _RC)
      _RETURN(_SUCCESS)
   end subroutine set_is_generic
Call graph
set_is_generic calls ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_grid_comp_primary calls set_is_generic
create_grid_comp calls create_grid_comp_primary
add_child_by_name calls create_grid_comp, add_child_by_name
make_driver calls create_grid_comp
setup calls create_grid_comp
test_is_generic calls create_grid_comp
test_mapl_invalid_name calls create_grid_comp
mapl_run_driver calls make_driver
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_finalize_children calls setup
test_full_run_sequence calls setup
test_init_children calls setup
test_mapl_runchild calls setup
test_mapl_runchild_other_phase calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup
test_wasfinal calls setup
test_wasinit calls setup
test_wasrun_1 calls setup
test_wasrun_extra calls setup