set_entry_point – MAPL
set_entry_point Subroutine
31 statements
Source File
private subroutine set_entry_point(this, method_flag, userProcedure, unusable, phase_name, rc)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
type(ESMF_Method_Flag), intent(in) :: method_flag
procedure(I_Run) :: userProcedure
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: phase_name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_entry_point(this, method_flag, userProcedure, unusable, phase_name, rc)
      class(OuterMetaComponent), intent(inout) :: this
      type(ESMF_Method_Flag), intent(in) :: method_flag
      procedure(I_Run) :: userProcedure
      class(KE), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: phase_name
      integer, optional, intent(out) ::rc
      integer :: status
      character(:), allocatable :: phase_name_
      type(ESMF_GridComp) :: user_gridcomp
      logical :: found
      if (present(phase_name)) then
         phase_name_ = phase_name
      else
         phase_name_ = get_default_phase_name(method_flag)
      end if
      call add_phase(this%user_phases_map, method_flag=method_flag, phase_name=phase_name_, _RC)
      associate (phase_idx => get_phase_index(this%user_phases_map%of(method_flag), phase_name=phase_name_, found=found))
        _ASSERT(found, "run phase: <"//phase_name_//"> not found.")
        user_gridcomp = this%user_gc_driver%get_gridcomp()
        call ESMF_GridCompSetEntryPoint(user_gridcomp, method_flag, userProcedure, phase=phase_idx, _RC)
      end associate
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine set_entry_point
Call graph
set_entry_point calls ESMF_GridCompSetEntryPoint, add_phase, get_phase_index, mapl_assert, get_default_phase_name, get_gridcomp, map_of, mapl_return, mapl_verify
add_phase calls add_phase_
get_phase_index calls get_phase_index_
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
map_of calls insert, map_s_iter_of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_phase_ calls mapl_assert, map_of, mapl_return, begin, find, insert, push_back, stringvector
get_error_message calls at, insert
get_phase_index_ calls begin, distance, find
map_s_iter_of calls map_s_get_value
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
map_s_insert_initializer_list calls insert
gridcomp_set_entry_point calls set_entry_point
mapl_gridcompsetentrypoint calls gridcomp_set_entry_point
setservices calls mapl_gridcompsetentrypoint, setservices