set_active – MAPL
set_active Subroutine
9 statements
Source File
private pure subroutine set_active(this, active)
Type Bound
StateItemSpec
Arguments
Type Intent Optional Attributes Name
class(StateItemSpec), intent(inout) :: this
logical, intent(in), optional :: active
Called by
Source Code
   pure subroutine set_active(this, active)
      class(StateItemSpec), intent(inout) :: this
      logical, optional, intent(in) :: active
      if (present(active)) then
         this%active = active
      else
         this%active =  .true.
      end if
   end subroutine set_active
Call graph
activate_dependencies calls set_active
add_item_spec_actual calls set_active
connect_sibling calls set_active, activate_dependencies, extend_
connect calls connect_sibling
add_item_spec_virtual calls add_item_spec
add_item_spec_virtual_override calls add_item_spec
extend_ calls add_item_spec
init_post_advertise calls add_item_spec
initialize_advertise calls add_item_spec
test_add_item_duplicate_fail calls add_item_spec
test_connect calls add_item_spec
test_connect_chain calls add_item_spec
test_create_extension calls add_item_spec
test_do_not_propagate_import calls add_item_spec
test_e2e_preserve_actual_pt calls add_item_spec
test_export_to_export_connection calls add_item_spec
test_get_item_spec_found calls add_item_spec
test_get_item_spec_multi calls add_item_spec
test_import_from_child calls add_item_spec
test_import_from_parent calls add_item_spec
test_internal_activation calls add_item_spec
test_internal_to_export_connection calls add_item_spec
test_multi_import calls add_item_spec
test_propagate_import calls add_item_spec
test_sibling_activation calls add_item_spec
initialize calls initialize_advertise