set_id – MAPL
set_id Module Subroutine
11 statements
Source File
module subroutine set_id(this, id, rc)
Arguments
Type Intent Optional Attributes Name
class(MaplGeom), intent(inout) :: this
integer, intent(in) :: id
integer, intent(out), optional :: rc
Calls
Source Code
   module subroutine set_id(this, id, rc)
      class(MaplGeom), intent(inout) :: this
      integer, intent(in) :: id
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Info) :: infoh
      call MAPL_GeomSetId(this%geom, id, _RC)
      _RETURN(_SUCCESS)
   end subroutine set_id
Call graph
set_id calls mapl_return, mapl_verify, mapl_geomsetid
mapl_geomsetid calls ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize