Set_fID – MAPL
Set_fID Subroutine
20 statements
Source File
public subroutine Set_fID(fIDIn, fIDOut, RC)
The subroutine Set_fID sets the file ID shadow variables.
History
09 Jan 2016 - S. D. Eastham - Initial version
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: fIDIn
integer, intent(in), optional :: fIDOut
integer, optional :: RC
Calls
Source Code
      Subroutine Set_fID(fIDIn, fIDOut, RC)
!
! !USES:
!
!      Use Precision_Mod, Only: f4
!
! !INPUT PARAMETERS:
!
      Integer, Optional                    :: RC
      Integer, Intent(In), Optional        :: fIDIn
      Integer, Intent(In), Optional        :: fIDOut
!
! !OUTPUT PARAMETERS:
!
      !Real(kind=sp), Intent(Out) :: TestOut
!
!-----------------------------------------------------------------------
!BOC
!
! !LOCAL VARIABLES:
!
      !=================================================================
      ! Set_fID starts here!
      !=================================================================
      RC = 0
      If (Present(fIDIn)) Then
         If (fIDInLocal.lt.0) Then
            fIDInLocal = fIDIn
         Else
            Call Assert(-1,'Set_fID','fIDIn already set')
         End If
      End If
      If (Present(fIDOut)) Then
         If (fIDOutLocal.lt.0) Then
            fIDOutLocal = fIDOut
         Else
            Call Assert(-1,'Set_fID','fIDOut already set')
         End If
      End If
      End Subroutine Set_fID
Call graph
set_fid calls assert
assert calls nf90_close, cleanup
cleanup calls nf90_close