set_time_interval – MAPL
set_time_interval Subroutine
73 statements
Source File
private subroutine set_time_interval(interval, key, hconfig, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TimeInterval), intent(out) :: interval
character(len=*), intent(in) :: key
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_time_interval(interval, key, hconfig, rc)
      type(ESMF_TimeInterval), intent(out) :: interval
      character(*), intent(in) :: key
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: strlen,ppos,cpos,lpos,tpos
      integer year,month,day,hour,min,sec
      character(len=:), allocatable :: date_string,time_string
      character(:), allocatable :: iso_duration
      iso_duration = ESMF_HConfigAsString(hconfig, keystring=key, _RC)
!#      call ESMF_TimeIntervalSet(interval, timeString=iso_duration, _RC)
      year=0
      month=0
      day=0
      hour=0
      min=0
      sec=0
      strlen = len_trim(iso_duration)
      tpos = index(iso_duration,'T')
      ppos = index(iso_duration,'P')
      _ASSERT(iso_duration(1:1) == 'P','Not valid time duration')
      if (tpos /= 0) then
         if (tpos /= ppos+1) then
            date_string = iso_duration(ppos+1:tpos-1)
         end if
         time_string = iso_duration(tpos+1:strlen)
      else
         date_string = iso_duration(ppos+1:strlen)
      end if
      if (allocated(date_string)) then
         strlen = len_trim(date_string)
         lpos = 0
         cpos = index(date_string,'Y')
         if (cpos /= 0) then
            read(date_string(lpos+1:cpos-1),*)year
            lpos = cpos
         end if
         cpos = index(date_string,'M')
         if (cpos /= 0) then
            read(date_string(lpos+1:cpos-1),*)month
            lpos = cpos
         end if
         cpos = index(date_string,'D')
         if (cpos /= 0) then
            read(date_string(lpos+1:cpos-1),*)day
            lpos = cpos
         end if
      end if
      if (allocated(time_string)) then
         strlen = len_trim(time_string)
         lpos = 0
         cpos = index(time_string,'H')
         if (cpos /= 0) then
            read(time_string(lpos+1:cpos-1),*)hour
            lpos = cpos
         end if
         cpos = index(time_string,'M')
         if (cpos /= 0) then
            read(time_string(lpos+1:cpos-1),*)min
            lpos = cpos
         end if
         cpos = index(time_string,'S')
         if (cpos /= 0) then
            read(time_string(lpos+1:cpos-1),*)sec
            lpos = cpos
         end if
      end if
      call ESMF_TimeIntervalSet(interval, yy=year, mm=month, d=day, h=hour, m=min, s=sec,_RC)
      _RETURN(_SUCCESS)
   end subroutine set_time_interval
Call graph
set_time_interval calls ESMF_TimeIntervalSet, esmf_hconfigasstring, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
create_clock calls set_time_interval
make_driver calls create_clock
mapl_run_driver calls make_driver
run_geos calls mapl_run_driver