set_undef – MAPL
set_undef Subroutine
5 statements
Source File
public elemental subroutine set_undef(t)
Uses
MAPL_InternalConstantsMod
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(inout) :: t
Called by
Source Code
   elemental subroutine set_undef(t)
      use MAPL_InternalConstantsMod, only: MAPL_UNDEFINED_REAL
      real(kind=ESMF_KIND_R4), intent(inout) :: t
      t = MAPL_UNDEFINED_REAL
   end subroutine set_undef
Call graph
test_accumulate_mean_r4 calls set_undef
test_calculate_mean_r4 calls set_undef
test_max_accumulate_r4 calls set_undef
test_min_accumulate_r4 calls set_undef