set_parameters – MAPL
set_parameters Subroutine
68 statements
Source File
public subroutine set_parameters(this, config_file)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
character(len=*), intent(in) :: config_file
Calls
Called by
Call graph
set_parameters calls ESMF_ConfigCreate, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigLoadFile, mpi_abort, mpi_comm_size, mapl_verify
mapl_verify calls mapl_throw_exception
checkpoint_tester calls set_parameters