set_start_stop_time – MAPL
set_start_stop_time Function
32 statements
Source File
public function set_start_stop_time(clock, hconfig, rc) result(start_stop_time)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(inout) :: clock
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value type(ESMF_Time), (2)
Calls
Called by
Source Code
   function set_start_stop_time(clock, hconfig, rc) result(start_stop_time)
      type(ESMF_Time) :: start_stop_time(2)
      type(ESMF_Clock), intent(inout) :: clock
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, intent(out), optional :: rc
      integer :: status
      logical :: has_start, has_stop, has_timespec
      character(len=:), allocatable :: time_string
      type(ESMF_HConfig) :: time_hconfig
      time_hconfig = ESMF_HConfigCreateAt(hconfig, keyString='time_spec', _RC)
      call ESMF_ClockGet(clock, startTime=start_stop_time(1), stopTime=start_stop_time(2), _RC)
      has_start = ESMF_HConfigIsDefined(time_hconfig, keyString='start', _RC)
      has_stop = ESMF_HConfigIsDefined(time_hconfig, keyString='stop', _RC)
      if (has_start) then
         time_string = ESMF_HConfigAsString(time_hconfig, keyString='start', _RC)
         call ESMF_TimeSet(start_stop_time(1), timeString=time_string, _RC)
      end if
      if (has_stop) then
         time_string = ESMF_HConfigAsString(time_hconfig, keyString='stop', _RC)
         call ESMF_TimeSet(start_stop_time(2), timeString=time_string, _RC)
      end if
      _RETURN(_SUCCESS)
   end function set_start_stop_time
Call graph
set_start_stop_time calls ESMF_ClockGet, ESMF_TimeSet, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
test_set_start_stop_time calls set_start_stop_time