set_grid – MAPL
set_grid Subroutine
55 statements
Source File
private subroutine set_grid(this, grid, unusable, lm, grid_type, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
type(ESMF_Grid), intent(in) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: lm
character(len=*), intent(in), optional :: grid_type
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine set_grid(this, grid, unusable, lm, grid_type, rc)
     class(MAPL_CapGridComp),          intent(inout) :: this
     type(ESMF_Grid),                  intent(in   ) :: grid
     class(KeywordEnforcer), optional, intent(in   ) :: unusable
     integer,                optional, intent(in   ) :: lm
     character(len=*),       optional, intent(in)    :: grid_type
     integer,                optional, intent(  out) :: rc
     type(ESMF_Grid)           :: mapl_grid
     type(ExternalGridFactory) :: external_grid_factory
     type(ESMF_Info)           :: infoh
     integer                   :: status
     character(len=ESMF_MAXSTR):: grid_type_
     _UNUSED_DUMMY(unusable)
     external_grid_factory = ExternalGridFactory(grid=grid, lm=lm, _RC)
     mapl_grid = grid_manager%make_grid(external_grid_factory, _RC)
     ! grid_type is an optional parameter that allows GridType to be set explicitly.
     call ESMF_ConfigGetAttribute(this%config, value = grid_type_, Label="GridType:", default="", rc=status)
     if (status == ESMF_RC_OBJ_NOT_CREATED) then
       grid_type_ = ""
     else
       _VERIFY(status)
     endif
     if (present(grid_type)) then
        if(grid_type_ /= "") then
          _ASSERT(grid_type_ == grid_type, "The grid types don't match")
        endif
        if (grid_manager%is_valid_prototype(grid_type)) then
           call ESMF_InfoGetFromHost(mapl_grid, infoh, _RC)
           call ESMF_InfoSet(infoh, 'GridType', grid_type, _RC)
        else
           _RETURN(_FAILURE)
        end if
     else if (grid_type_ /= "") then
        if (grid_manager%is_valid_prototype(grid_type_)) then
           call ESMF_InfoGetFromHost(mapl_grid, infoh, _RC)
           call ESMF_InfoSet(infoh, 'GridType', grid_type, _RC)
        else
           _RETURN(_FAILURE)
        end if
     endif
     call ESMF_GridCompSet(this%gc, grid=mapl_grid, _RC)
     _RETURN(_SUCCESS)
  end subroutine set_grid
Call graph
set_grid calls ESMF_ConfigGetAttribute, ESMF_GridCompSet, ESMF_InfoGetFromHost, ESMF_InfoSet, mapl_assert, make_grid, is_valid_prototype, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
is_valid_prototype calls mapl_return, mapl_verify, initialize_prototypes, m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
initialize_prototypes calls mapl_return, insert
m_find calls s_find
make_grid_from_distgrid calls ESMF_InfoGetFromHost, ESMF_InfoSet, make_grid, mapl_return, mapl_verify, make_factory
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq