set_vertical_geom – MAPL
set_vertical_geom Subroutine
5 statements
Source File
private subroutine set_vertical_geom(this, verticaL_geom)
Type Bound
OuterMetaComponent
Arguments
Type Intent Optional Attributes Name
class(OuterMetaComponent), intent(inout) :: this
type(VerticalGeom), intent(in) :: verticaL_geom
Called by
Source Code
   subroutine set_vertical_geom(this, vertical_geom)
      class(OuterMetaComponent), intent(inout) :: this
      type(VerticalGeom), intent(in) :: verticaL_geom
      this%vertical_geom = vertical_geom
   end subroutine set_vertical_geom
Call graph
mapl_gridcompsetverticalgeom calls set_vertical_geom
setservices calls set_vertical_geom, setservices
setup calls mapl_gridcompsetverticalgeom
test_full_run_sequence calls mapl_gridcompsetverticalgeom
test_child_outer_items_created calls setup
test_child_user_items_created calls setup
test_parent_outer_items_created calls setup
test_parent_user_items_created calls setup
test_propagate_imports calls setup
test_state_items_complete calls setup