set_info – MAPL
set_info Subroutine
25 statements
Source File
private subroutine set_info(this, field, rc)
Type Bound
FieldSpec
Arguments
Type Intent Optional Attributes Name
class(FieldSpec), intent(in) :: this
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_info(this, field, rc)
      class(FieldSpec), intent(in) :: this
      type(ESMF_Field), intent(inout) :: field
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Info) :: ungridded_dims_info
      type(ESMF_Info) :: vertical_dim_info
      type(ESMF_Info) :: field_info
      call ESMF_InfoGetFromHost(field, field_info, _RC)
      ungridded_dims_info = this%ungridded_dims%make_info(_RC)
      call ESMF_InfoSet(field_info, key='MAPL/ungridded_dims', value=ungridded_dims_info, _RC)
      call ESMF_InfoDestroy(ungridded_dims_info, _RC)
      vertical_dim_info = this%vertical_dim%make_info(_RC)
      call ESMF_InfoSet(field_info, key='MAPL/vertical', value=vertical_dim_info, _RC)
      call ESMF_InfoDestroy(vertical_dim_info, _RC)
      _RETURN(_SUCCESS)
   end subroutine set_info
Call graph
set_info calls ESMF_InfoDestroy, ESMF_InfoGetFromHost, ESMF_InfoSet, make_info, mapl_return, mapl_verify
make_info calls ESMF_InfoDestroy, ESMF_InfoSet, mapl_return, mapl_verify, ESMF_InfoCreate, get_ith_dim_spec, get_num_ungridded, make_info
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_ith_dim_spec calls mapl_return, mapl_verify, at
mapl_throw_exception calls initialize
allocate calls set_info
test_field_set_info calls set_info