setNumPETsRequested – MAPL
setNumPETsRequested Subroutine
5 statements
Source File
private pure subroutine setNumPETsRequested(this, numPETsRequested)
Type Bound
ESMF_TestParameter
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestParameter), intent(inout) :: this
integer, intent(in) :: numPETsRequested
Called by
Source Code
   pure subroutine setNumPETsRequested(this, numPETsRequested)
      class (ESMF_TestParameter), intent(inout) :: this
      integer, intent(in) :: numPETsRequested
      this%numPETsRequested = numPETsRequested
   end subroutine setNumPETsRequested
Call graph
gridcase_global calls setnumpetsrequested
gridcase_local calls setnumpetsrequested
new_scenariodescription calls setnumpetsrequested
newesmf_testparameter calls setnumpetsrequested
esmf_testparameter calls newesmf_testparameter
gridcase calls gridcase_global, gridcase_local
scenariodescription calls new_scenariodescription