setServices – MAPL
setServices Subroutine
12 statements
Source File
subroutine setServices(gridcomp, rc)
Uses
ESMF
mapl_ErrorHandlingMod
mapl3g_HistoryGridComp
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
integer, intent(out) :: rc
Calls
Source Code
   subroutine setServices(gridcomp, rc)
      type(ESMF_GridComp) :: gridcomp
      integer, intent(out) :: rc
      type(ESMF_HConfig) :: hconfig, collections_config, child_hconfig
      character(len=:), allocatable :: child_name, collection_name
      type(ESMF_HConfigIter) :: iter, iter_begin, iter_end
      logical :: has_active_collections
      class(logger), pointer :: lgr
      type(ChildSpec) :: child_spec
      integer :: num_collections, status
      type(ESMF_TimeInterval), allocatable :: timeStep
      type(ESMF_TimeInterval), allocatable :: offset
      ! Set entry points
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_INITIALIZE, init, phase_name="GENERIC::INIT_USER", _RC)
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_RUN, run, phase_name='run', _RC)
      ! Determine collections
      call MAPL_GridCompGet(gridcomp, hconfig=hconfig, _RC)
      has_active_collections = ESMF_HConfigIsDefined(hconfig, keyString='active_collections', _RC)
      if (.not. has_active_collections) then
         call MAPL_GridCompGet(gridcomp,logger=lgr, _RC)
         call lgr%warning("no active collection specified in History")
         _RETURN(_SUCCESS)
      end if
      collections_config = ESMF_HConfigCreateAt(hconfig, keystring='active_collections', _RC)
      num_collections = ESMF_HConfigGetSize(collections_config, _RC)
      _RETURN_UNLESS(num_collections > 0)
      iter_begin = ESMF_HConfigIterBegin(collections_config,_RC)
      iter_end = ESMF_HConfigIterEnd(collections_config, _RC)
      iter = iter_begin
      do while (ESMF_HConfigIterLoop(iter, iter_begin, iter_end, rc=status))
         _VERIFY(status)
         collection_name = ESMF_HConfigAsString(iter, _RC)
         child_hconfig = make_child_hconfig(hconfig, collection_name, _RC)
         child_name = make_child_name(collection_name, _RC)
         call get_child_timespec(child_hconfig, timeStep, offset, _RC)
         child_spec = ChildSpec(user_setservices(collection_setServices), hconfig=child_hconfig, timeStep=timeStep, offset=offset)
         call MAPL_GridCompAddChild(gridcomp, child_name, child_spec,_RC)
      end do
      _RETURN(_SUCCESS)
   end subroutine setServices
Call graph
setservices calls mapl_return, mapl_verify, setservices, ESMF_HConfigIterLoop, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_gridcompaddchild, mapl_gridcompget, mapl_gridcompsetentrypoint, user_setservices, warning, hconfig_to_esmf_timeinterval, make_child_hconfig, make_child_name
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
hconfig_to_esmf_timeinterval calls mapl_return, mapl_verify, esmf_hconfigasstring, string_to_esmf_timeinterval
make_child_hconfig calls mapl_return, mapl_verify, ESMF_HConfigAdd, ESMF_HConfigDestroy, get_subconfig
make_child_name calls mapl_return
get_subconfig calls mapl_return, mapl_verify, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, mapl_assert
string_to_esmf_timeinterval calls mapl_return, mapl_verify, ESMF_TimeIntervalSet, mapl_assert