setServices – MAPL
setServices Subroutine
36 statements
Source File
public subroutine setServices(gridcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
integer, intent(out) :: rc
Calls
Source Code
   subroutine setServices(gridcomp, rc)
      type(ESMF_GridComp) :: gridcomp
      integer, intent(out) :: rc
      type(HistoryCollectionGridComp), pointer :: collection_gridcomp
      type(ESMF_HConfig) :: hconfig
      character(*), parameter :: PRIVATE_STATE = "HistoryCollectionGridComp"
      integer :: status
      type(VerticalGeom) :: vertical_geom
      type(OuterMetaComponent), pointer :: outer_meta
      ! Set entry points
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_INITIALIZE, init_geom, phase_name='GENERIC::INIT_ADVERTISE_GEOM', _RC)
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_INITIALIZE, init, _RC)
      call MAPL_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_RUN, run, phase_name='run', _RC)
      ! Attach private state
      _SET_NAMED_PRIVATE_STATE(gridcomp, HistoryCollectionGridComp, PRIVATE_STATE, collection_gridcomp)
      outer_meta => get_outer_meta_from_inner_gc(gridcomp,_RC)
      vertical_geom = VerticalGeom(4)
      call outer_meta%set_vertical_geom(vertical_geom)
      call MAPL_GridCompGet(gridcomp, hconfig=hconfig, _RC)
      call register_imports(gridcomp,hconfig,_RC)
      _RETURN(_SUCCESS)
   end subroutine setServices
Call graph
setservices calls mapl_assert, mapl_gridcompget, mapl_gridcompsetentrypoint, mapl_usercompsetinternalstate, set_vertical_geom, get_outer_meta_from_inner_gc, mapl_return, mapl_verify, register_imports
get_outer_meta_from_inner_gc calls mapl_assert, mapl_return, mapl_verify, get_outer_meta, mapl_gridcompisuser, get_outer_gridcomp, get_inner_meta
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
register_imports calls mapl_assert, mapl_return, mapl_verify, ESMF_HConfigIterLoop, esmf_hconfigcreateat, esmf_hconfigiterbegin, esmf_hconfigiterend, ftn_begin, ftn_end, mapl_addspec, next, of, mirror_ungridded_dims
get_inner_meta calls mapl_assert, mapl_return, mapl_usercompgetinternalstate