setup_bundle – MAPL
setup_bundle Subroutine
41 statements
Source File
public subroutine setup_bundle(bundle, weights, geom, typekind, units, with_ungridded)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(out) :: bundle
real(kind=ESMF_KIND_R4), intent(in) :: weights(:)
type(ESMF_Geom), intent(in) :: geom
type(ESMF_TypeKind_Flag), intent(in) :: typekind
character(len=*), intent(in) :: units
logical, intent(in), optional :: with_ungridded
Calls
Called by
Source Code
   subroutine setup_bundle(bundle, weights, geom, typekind, units, with_ungridded)
      type(ESMF_FieldBundle), intent(out) :: bundle
      real(kind=ESMF_KIND_R4), intent(in) :: weights(:)
      type(ESMF_Geom), intent(in) :: geom
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      character(len=*), intent(in) :: units
      logical, optional, intent(in) :: with_ungridded
      integer :: i
      type(ESMF_Field) :: f
      integer :: fieldCount
      type(UngriddedDims) :: ungridded_dims
      type(ESMF_Info) :: ungridded_info
      bundle = ESMF_FieldBundleCreate()
      call MAPL_FieldBundleSet(bundle, geom=geom)
      fieldCount = size(weights) - 1
      do i = 1, fieldCount
         call setup_field(f, geom, typekind, units, with_ungridded=with_ungridded)
         call ESMF_FieldBundleAdd(bundle, [f], multiflag=.true.)
      end do
      ungridded_dims = UngriddedDims()
      ungridded_info = ungridded_dims%make_info()
      call MAPL_InfoSetInternal(bundle, KEY_UNGRIDDED_DIMS, value=ungridded_info)
      call MAPL_InfoSetInternal(bundle, KEY_INTERPOLATION_WEIGHTS, weights)
      if (typekind == ESMF_TYPEKIND_R4) then
         call MAPL_InfoSetInternal(bundle, KEY_TYPEKIND, "R4")
      else
         call MAPL_InfoSetInternal(bundle, KEY_TYPEKIND, "R8")
      end if
      call MAPL_InfoSetInternal(bundle, KEY_UNITS, units)
      call MAPL_InfoSetInternal(bundle, KEY_VLOC, "VERTICAL_DIM_NONE")
      ungridded_dims = UngriddedDims()
      if (present(with_ungridded)) then
         if (with_ungridded) then
            call MAPL_InfoSetInternal(bundle, KEY_VLOC, "VERTICAL_DIM_CENTER")
            call MAPL_InfoSetInternal(bundle, KEY_NUM_LEVELS, NUM_LEVELS)
            call ungridded_dims%add_dim(UngriddedDim(NUM_RADII, "radius", 'nm'))
         end if
      end if
      ungridded_info = ungridded_dims%make_info()
      call MAPL_InfoSetInternal(bundle, KEY_UNGRIDDED_DIMS, value=ungridded_info)
   end subroutine setup_bundle
Call graph
setup_bundle calls esmf_fieldbundleadd, esmf_fieldbundlecreate, mapl_infosetinternal, add_dim, make_info, mapl_fieldbundleset, setup_field
mapl_fieldbundleset calls ESMF_GeomGet, esmf_fieldbundleset, mapl_assert, mapl_return, mapl_verify
setup_field calls mapl_infosetinternal, add_dim, make_info, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset, fieldset, get_bounds
test_change_geom calls setup_bundle
test_change_typekind calls setup_bundle
test_change_units calls setup_bundle
test_change_weights calls setup_bundle
test_change_weights_with_ungridded calls setup_bundle
test_create_fields calls setup_bundle
test_create_fields_with_ungridded calls setup_bundle
test_same_geom calls setup_bundle