setup – MAPL
setup Subroutine
84 statements
Source File
public subroutine setup(this)
Type Bound
Scenario
Arguments
Type Intent Optional Attributes Name
class(Scenario), intent(inout) :: this
Calls
Source Code
   subroutine setup(this)
      class(Scenario), intent(inout) :: this
      type(ESMF_HConfig) :: config
      integer :: status, user_status
      integer :: i
      type(ESMF_State) :: importState, exportState
      character(:), allocatable :: file_name
      type(VerticalGeom) :: vertical_geom
      type(ESMF_Time) :: t
      type(ESMF_TimeInterval) :: dt
      type(ESMF_Clock) :: clock
      file_name = './scenarios/' // this%scenario_name // '/' // this%scenario_root
      config = ESMF_HConfigCreate(filename=file_name)
      call NUOPC_FieldDictionarySetup(filename='./scenarios/FieldDictionary.yml', _RC)
      @assert_that(status, is(0))
      associate (outer_gc => this%outer_gc, outer_states => this%outer_states, grid => this%grid)
        call ESMF_TimeSet(t, h=0)
        call ESMF_TimeIntervalSet(dt, h=1)
        clock = ESMF_ClockCreate(dt, t)
        outer_gc = create_grid_comp('ROOT', user_setservices('libsimple_parent_gridcomp'), config, clock, _RC)
        call ESMF_GridCompSetServices(outer_gc, generic_setServices, userRC=user_status, _RC)
        _VERIFY(user_status)
        vertical_geom = VerticalGeom(4)
        call MAPL_GridCompSetVerticalGeom(outer_gc,vertical_geom,_RC)
        importState = ESMF_StateCreate(_RC)
        exportState = ESMF_StateCreate(_RC)
        outer_states = MultiState(importState=importState, exportState=exportState)
        do i = 1, size(GENERIC_INIT_PHASE_SEQUENCE)
           associate (phase => GENERIC_INIT_PHASE_SEQUENCE(i))
             call ESMF_GridCompInitialize(outer_gc, &
                  importState=importState, exportState=exportState, clock=clock, &
                  phase=phase, userRC=user_status, _RC)
             _VERIFY(user_status)
           end associate
        end do
!#        if (this%scenario_name == 'precision_extension') then
           call ESMF_GridCompRun(outer_gc, &
                  importState=importState, exportState=exportState, clock=clock, &
                  userRC=user_status, _RC)
           _VERIFY(user_status)
!#        end if
      end associate
      file_name = './scenarios/' // this%scenario_name // '/expectations.yaml'
      this%expectations = ESMF_HConfigCreate(filename=file_name, _RC)
   end subroutine setup
Call graph
setup calls ESMF_ClockCreate, ESMF_GridCompInitialize, ESMF_GridCompRun, ESMF_HConfigCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, NUOPC_FieldDictionarySetup, anyexceptions, assert_that, esmf_gridcompsetservices, esmf_statecreate, create_grid_comp, user_setservices, mapl_gridcompsetverticalgeom, sourcelocation
create_grid_comp calls create_grid_comp_primary
user_setservices calls new_dsosetservices, new_procsetservices
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta, mapl_return, mapl_verify, set_vertical_geom