setup_geom – MAPL
setup_geom Subroutine
7 statements
Source File
public subroutine setup_geom(geom, im)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(out) :: geom
integer, intent(in) :: im
Calls
Called by
Source Code
   subroutine setup_geom(geom, im)
      type(ESMF_Geom), intent(out) :: geom
      integer, intent(in) :: im
      type(ESMF_Grid) :: grid
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[IM,IM])
      geom = ESMF_GeomCreate(grid)
   end subroutine setup_geom
Call graph
setup_geom calls ESMF_GeomCreate, ESMF_GridCreateNoPeriDim
test_change_geom calls setup_geom
test_change_typekind calls setup_geom
test_change_units calls setup_geom
test_change_weights calls setup_geom
test_change_weights_with_ungridded calls setup_geom
test_create_fields calls setup_geom
test_create_fields_with_ungridded calls setup_geom
test_same_geom calls setup_geom