setup_field – MAPL
setup_field Subroutine
28 statements
Source File
public subroutine setup_field(field, geom, typekind, units, with_ungridded)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(out) :: field
type(ESMF_Geom), intent(in) :: geom
type(ESMF_TypeKind_Flag), intent(in) :: typekind
character(len=*), intent(in) :: units
logical, intent(in), optional :: with_ungridded
Calls
Called by
Source Code
   subroutine setup_field(field, geom, typekind, units, with_ungridded)
      type(ESMF_Field), intent(out) :: field
      type(ESMF_Geom), intent(in) :: geom
      type(ESMF_TypeKind_Flag), intent(in) :: typekind
      character(len=*), intent(in) :: units
      logical, optional, intent(in) :: with_ungridded
      type(UngriddedDims) :: ungridded_dims
      type(ESMF_Info) :: ungridded_info
      type(LU_Bound), allocatable :: bounds(:)
      field = ESMF_FieldEmptyCreate()
      call ESMF_FieldEmptySet(field, geom=geom)
      call MAPL_InfoSetInternal(field, KEY_UNITS, units)
      call MAPL_InfoSetInternal(field, KEY_VLOC, "VERTICAL_DIM_NONE")
      ungridded_dims = UngriddedDims()
      bounds = ungridded_dims%get_bounds()
      if (present(with_ungridded)) then
         if (with_ungridded) then
            call MAPL_InfoSetInternal(field, KEY_VLOC, "VERTICAL_DIM_CENTER")
            call MAPL_InfoSetInternal(field, KEY_NUM_LEVELS, NUM_LEVELS)
            call ungridded_dims%add_dim(UngriddedDim(NUM_RADII, "radius", 'nm'))
            bounds = [LU_Bound(1, NUM_LEVELS), ungridded_dims%get_bounds()]
         end if
      end if
      ungridded_info = ungridded_dims%make_info()
      call MAPL_InfoSetInternal(field, KEY_UNGRIDDED_DIMS, value=ungridded_info)
      call ESMF_FieldEmptyComplete(field, typekind=typekind, ungriddedLBound=bounds%lower, ungriddedUBound=bounds%upper)
      call FieldSet(field, FILL_VALUE)
   end subroutine setup_field
Call graph
setup_field calls esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset, fieldset, mapl_infosetinternal, add_dim, get_bounds, make_info
make_dim_key calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setup_bundle calls setup_field
test_change_geom calls setup_bundle
test_change_typekind calls setup_bundle
test_change_units calls setup_bundle
test_change_weights calls setup_bundle
test_change_weights_with_ungridded calls setup_bundle
test_create_fields calls setup_bundle
test_create_fields_with_ungridded calls setup_bundle
test_same_geom calls setup_bundle