setup_eta_to_pressure – MAPL
setup_eta_to_pressure Subroutine
133 statements
Source File
private subroutine setup_eta_to_pressure(this, regrid_handle, output_grid, rc)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout) :: this
class(AbstractRegridder), intent(inout), optional :: regrid_handle
type(ESMF_Grid), intent(inout), optional :: output_grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine setup_eta_to_pressure(this,regrid_handle,output_grid,rc)
        class(verticaldata), intent(inout) :: this
        class(abstractRegridder), optional, intent(inout) :: regrid_handle
        type(ESMF_Grid), optional, intent(inout) :: output_grid
        integer, optional, intent(out) :: rc
        integer :: status
        real,         allocatable  :: ptrx(:,:,:)
        real, pointer              :: ptr3(:,:,:)
        real,         allocatable  :: orig_surface_level(:,:)
        integer ::  counts(3)
        if (allocated(this%ple3d)) deallocate(this%ple3d)
        if (allocated(this%pl3d)) deallocate(this%pl3d)
        call ESMF_FieldGet(this%interp_var,localde=0,farrayptr=ptr3,rc=status)
        _VERIFY(status)
        allocate(orig_surface_level(size(ptr3,1),size(ptr3,2)),stat=status)
        _VERIFY(status)
! the ptr3 interpolating variable is a zero-based (0-lm) edge variable
!---------------------------------------------------------------------
       if(lbound(ptr3,3)==0) then
          allocate( this%ple3d(size(ptr3,1),size(ptr3,2),size(ptr3,3)  ), stat=status)
          _VERIFY(status)
          allocate(  this%pl3d(size(ptr3,1),size(ptr3,2),size(ptr3,3)-1), stat=status)
          _VERIFY(status)
          if    (this%func=='log') then
             this%ple3d = log(ptr3)
             this%pl3d  = log( 0.5*(ptr3(:,:,1:)+ptr3(:,:,0:ubound(ptr3,3)-1)) )
          elseif(this%func=='pow') then
             this%ple3d = ptr3**this%pow
             this%pl3d  =    ( 0.5*(ptr3(:,:,1:)+ptr3(:,:,0:ubound(ptr3,3)-1)) )**this%pow
          else
             this%ple3d = ptr3
             this%pl3d  =    ( 0.5*(ptr3(:,:,1:)+ptr3(:,:,0:ubound(ptr3,3)-1)) )
          end if
          orig_surface_level = ptr3(:,:,ubound(ptr3,3))
          this%ascending = (ptr3(1,1,0)<ptr3(1,1,1))
       else
! the ptr3 interpolating variable is a (1-lm) mid-layer variable
!---------------------------------------------------------------
          allocate(  ptrx(size(ptr3,1),size(ptr3,2),0:size(ptr3,3)  ), stat=status)
          _VERIFY(status)
          allocate( this%ple3d(size(ptr3,1),size(ptr3,2),0:size(ptr3,3)  ), stat=status)
          _VERIFY(status)
          allocate(  this%pl3d(size(ptr3,1),size(ptr3,2),  size(ptr3,3)  ), stat=status)
          _VERIFY(status)
          ptrx(:,:,0               ) = 0.5*( 3* ptr3(:,:,1)             -ptr3(:,:,2)                )
          ptrx(:,:,1:size(ptr3,3)-1) = 0.5*(    ptr3(:,:,2:size(ptr3,3))+ptr3(:,:,1:size(ptr3,3)-1) )
          ptrx(:,:,  size(ptr3,3)  ) = 0.5*( 3* ptr3(:,:,  size(ptr3,3))-ptr3(:,:,  size(ptr3,3)-1) )
          if    (this%func=='log') then
             this%ple3d = log(ptrx)
             this%pl3d  = log( 0.5*(ptrx(:,:,1:)+ptrx(:,:,0:ubound(ptrx,3)-1)) )
          elseif(this%func=='pow') then
             this%ple3d = ptrx**this%pow
             this%pl3d  =    ( 0.5*(ptrx(:,:,1:)+ptrx(:,:,0:ubound(ptrx,3)-1)) )**this%pow
          else
             this%ple3d = ptrx
             this%pl3d  =    ( 0.5*(ptrx(:,:,1:)+ptrx(:,:,0:ubound(ptrx,3)-1)) )
          end if
          this%ascending = (ptrx(1,1,0)<ptrx(1,1,1))
          orig_surface_level = ptrx(:,:,ubound(ptrx,3))
          deallocate(ptrx)
       end if
       if (present(output_grid)) then
          _ASSERT(present(regrid_handle),"Must provide regridding handle")
          call MAPL_GridGet(output_grid,localCellCountPerDim=counts,rc=status)
          _VERIFY(status)
          if (.not.allocated(this%surface_level)) then
              allocate(this%surface_level(counts(1),counts(2)),stat=status)
             _VERIFY(status)
          end if
       end if
       if (present(regrid_handle)) then
          call regrid_handle%regrid(orig_surface_level,this%surface_level,rc=status)
          _VERIFY(status)
       end if
       deallocate(orig_surface_level)
       call init_indices(_RC)
       _RETURN(_SUCCESS)
       contains
          ! initialize for pl3d ( not ple3d)
          subroutine init_indices(rc)
            integer, optional, intent(inout) :: rc
            integer :: status
            integer :: k, lev, km, D1, D2, levo, km_e
            integer :: flip_sign, i,j
            real, allocatable :: pb(:,:), pt(:,:), ple3d(:,:,:)
            real :: pp
            D1   = size(this%pl3d,1)
            D2   = size(this%pl3d,2)
            km   = size(this%pl3d,3)
            levo = size(this%interp_levels)
            flip_sign = 1
            if( .not. this%ascending ) flip_sign = -1
            ! for cell values
            if(allocated(this%ks))  deallocate(this%ks)
            if(allocated(this%weight)) deallocate(this%weight)
            allocate(this%ks(D1,D2,levo),source  = -1)
            allocate(this%weight(D1,D2,levo),source = 0.0)
            do lev =1, levo
               pp = flip_sign*this%interp_levels(lev)
               pb = flip_sign*this%pl3d(:,:,km)
               do k = km-1, 1,-1 ! levels of input
                 if(all(pb<pp)) exit
                 pt = flip_sign*this%pl3d(:,:,k)
                 where (pp>pt .and. pp<=pb)
                    this%ks(:,:,lev) = k
                    this%weight(:,:,lev) = (pb-pp)/(pb-pt)
                 end where
                 pb = pt
               enddo
            enddo
            deallocate(this%pl3d) ! not needed any more. release the memory
            ! for edge values
            if(allocated(this%ks_e))  deallocate(this%ks_e)
            if(allocated(this%weight_e)) deallocate(this%weight_e)
            allocate(this%ks_e(D1,D2,levo),source  = -1)
            allocate(this%weight_e(D1,D2,levo),source = 0.0)
            km_e = size(this%ple3d,3)
            this%nedge = km_e
            allocate(ple3d(D1,D2,km_e))
            ple3d = this%ple3d
            do lev =1, levo
               pp = flip_sign*this%interp_levels(lev)
               pb = flip_sign*ple3d(:,:,km_e)
               do k = km_e-1, 1,-1 ! levels of input
                 if(all(pb<pp)) exit
                 pt = flip_sign*ple3d(:,:,k)
                 where (pp>pt .and. pp<=pb)
                    this%ks_e(:,:,lev) = k
                    this%weight_e(:,:,lev) = (pb-pp)/(pb-pt)
                 end where
                 pb = pt
               enddo
            enddo
            deallocate(this%ple3d) ! not needed any more. release the memory
            _RETURN(_SUCCESS)
          end subroutine
     end subroutine setup_eta_to_pressure
Call graph
setup_eta_to_pressure calls esmf_fieldget, mapl_assert, regrid, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
regrid_vector_3d_real64 calls mapl_assert, mapl_return
append_file calls setup_eta_to_pressure
bundlepost calls setup_eta_to_pressure
interp_accumulate_fields calls setup_eta_to_pressure
regrid_accumulate_on_xsubset calls setup_eta_to_pressure
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls append_file, bundlepost, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main