setup_ – MAPL
setup_ Subroutine
39 statements
Source File
public subroutine setup_(var_name, geom, vgrid, registry, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var_name
type(ESMF_Geom), intent(in) :: geom
type(ModelVerticalGrid), intent(in) :: vgrid
type(StateRegistry), intent(inout) :: registry
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine setup_(var_name, geom, vgrid, registry, rc)
      character(*), intent(in) :: var_name
      type(ESMF_Geom), intent(in) :: geom
      type(ModelVerticalGrid), intent(in) :: vgrid
      type(StateRegistry), intent(inout) :: registry
      integer, optional, intent(out) :: rc
      type(VerticalDimSpec) :: vertical_dim_spec
      type(VariableSpec) :: var_spec
      class(StateItemSpec), allocatable :: fld_spec
      type(VirtualConnectionPt) :: v_pt
      type(StateItemExtension), pointer :: extension
      class(StateItemSpec), pointer :: spec
      integer :: status
      select case(var_name)
      case("PLE")
         vertical_dim_spec = VERTICAL_DIM_EDGE
      case("PL")
         vertical_dim_spec = VERTICAL_DIM_CENTER
      case default
         _FAIL("unsupported var name " // var_name)
      end select
      var_spec = VariableSpec(&
           short_name=var_name, &
           state_intent=ESMF_STATEINTENT_EXPORT, &
           standard_name="air_pressure", &
           units="hPa", &
           vertical_dim_spec=vertical_dim_spec, &
           default_value=3.)
      allocate(fld_spec, source=make_itemSpec(var_spec, r, rc=status)); _VERIFY(status)
      call fld_spec%set_geometry(geom=geom, vertical_grid=vgrid, _RC)
      v_pt = VirtualConnectionPt(state_intent="export", short_name=var_name)
      call registry%add_primary_spec(v_pt, fld_spec)
      extension => registry%get_primary_extension(v_pt, _RC)
      spec => extension%get_spec()
      call spec%set_active()
      call spec%create(_RC)
      call spec%allocate(_RC)
      _RETURN(_SUCCESS)
   end subroutine setup_
Call graph
setup_ calls create, mapl_assert, add_primary_spec, get_primary_extension, get_spec, set_active, make_itemspec, mapl_return, mapl_verify, set_geometry
make_itemspec calls mapl_assert, set_active, mapl_return, mapl_verify, make_dependencies, set_dependencies, set_raw_dependencies
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setup calls setup_
test_created_fields_have_num_levels calls setup
test_get_coordinate_field_change_units_center calls setup
test_get_coordinate_field_change_units_edge calls setup
test_get_coordinate_field_simple calls setup