setup – MAPL
setup Subroutine
19 statements
Source File
public subroutine setup()
Arguments
None
Calls
Source Code
   subroutine setup()
      type(ESMF_HConfig) :: hconfig
      type(MaplGeom) :: mapl_geom
      type(GeomManager), pointer :: geom_mgr
      integer :: status
      geom_mgr => get_geom_manager()
      hconfig = ESMF_HConfigCreate(content="{class: latlon, im_world: 12, jm_world: 13, pole: PC, dateline: DC}", _RC)
      mapl_geom = geom_mgr%get_mapl_geom(hconfig, _RC)
      geom = mapl_geom%get_geom()
      call ESMF_HConfigDestroy(hconfig)
   end subroutine setup
Call graph
setup calls ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, get_geom, get_geom_manager, get_mapl_geom, sourcelocation