setup – MAPL
setup Subroutine
46 statements
Source File
public subroutine setup(vgrid, rc)
Arguments
Type Intent Optional Attributes Name
type(ModelVerticalGrid), intent(out) :: vgrid
integer, intent(out) :: rc
Calls
Called by
Source Code
   subroutine setup(vgrid, rc)
      type(ModelVerticalGrid), intent(out) :: vgrid
      integer, intent(out) :: rc
      type(ESMF_Geom) :: geom
      type(VirtualConnectionPt) :: ple_pt
      type(VariableSpec) :: var_spec
      class(StateItemSpec), allocatable :: ple_spec
      type(StateItemExtension), pointer :: extension
      class(StateItemSpec), pointer :: spec
      integer :: status
      rc = 0
      ! Inside user "set_geom" phase.
      geom = make_geom(_RC)
      vgrid = ModelVerticalGrid(num_levels=LM)
      call vgrid%add_variant(short_name='PLE')
      ! inside OuterMeta
      r = StateRegistry('dyn')
      call vgrid%set_registry(r) ! MAPL_SetVerticalGrid(...)
      ple_pt = VirtualConnectionPt(state_intent='export', short_name='PLE')
     var_spec = VariableSpec(&
           short_name='PLE', &
           state_intent=ESMF_STATEINTENT_EXPORT, &
           standard_name='air_pressure', &
           units='hPa', &
           vertical_dim_spec=VERTICAL_DIM_EDGE, &
           default_value=3.)
     allocate(ple_spec, source=var_spec%make_itemSpec(geom=geom, vertical_grid=vgrid, registry=r, rc=status))
     _VERIFY(status)
      call r%add_primary_spec(ple_pt, ple_spec)
      extension => r%get_primary_extension(ple_pt, _RC)
      spec => extension%get_spec()
      call spec%set_active()
      call spec%create(_RC)
      call spec%allocate(_RC)
   end subroutine setup
Call graph
setup calls anyexceptions, assert_that, create, add_primary_spec, add_variant, get_primary_extension, get_spec, make_itemspec, set_active, set_registry, make_geom, sourcelocation
make_geom calls anyexceptions, assert_that, sourcelocation, ESMF_HConfigCreate, get_geom, get_geom_manager, get_mapl_geom
test_created_fields_have_num_levels calls setup
test_get_coordinate_field_change_units calls setup
test_get_coordinate_field_simple calls setup