set – MAPL
set Subroutine
63 statements
Source File
private subroutine set(this, grid, unusable, rc)
Type Bound
MaplGrid
Arguments
Type Intent Optional Attributes Name
class(MaplGrid), intent(inout) :: this
type(ESMF_Grid), intent(in) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine set(this, grid, unusable, rc)
    class(MaplGrid), intent(inout) :: this
    type(ESMF_Grid), intent(in) :: grid
    class(KeywordEnforcer), optional, intent(in) :: unusable
    integer, optional, intent(out) :: rc
    integer                          :: ndes
    integer                          :: dimcount
    integer                          :: counts(3)
    integer, allocatable             :: minindex(:,:)
    integer, allocatable             :: maxindex(:,:)
    integer, pointer                 :: ims(:) => null()
    integer, pointer                 :: jms(:) => null()
    type(ESMF_DistGrid)              :: distgrid
    type(ESMF_VM)                    :: vm
    integer              :: status
    class(Logger), pointer :: lgr => null()
    _UNUSED_DUMMY(unusable)
    ! At this point, this component must have a valid grid!
    !------------------------------------------------------
    call ESMF_GridValidate(grid, _RC)
    this%ESMFGRID = GRID
! We keep these in the component's grid  for convenience
!-------------------------------------------------------
    call ESMF_GridGet(this%ESMFGRID, DistGrid=distgrid, dimCount=dimCount, _RC)
    call ESMF_DistGridGet(distGRID, deLayout=this%LAYOUT, _RC)
    call ESMF_VmGetCurrent(VM, _RC)
    call ESMF_VmGet(VM, localPet=this%MYID, petCount=ndes, _RC)
! Vertical coordinate must exist and be THE THIRD DIMENSION
! ---------------------------------------------------------
    this%VERTDIM = 3
    call MAPL_GridGet(this%ESMFGRID, localCellCountPerDim=COUNTS, _RC)
#ifdef DEBUG
    print *,'dbg:myId=',this%MYID,trim(Iam)
    print *,'dbg:local gridcounts=',counts
#endif
! Local sizes of three dimensions
!--------------------------------
    this%IM = COUNTS(1)
    this%JM = COUNTS(2)
    this%LM = COUNTS(3)
    call MAPL_GridGet(this%ESMFGRID, globalCellCountPerDim=COUNTS, _RC)
    this%IM_WORLD = COUNTS(1)
    this%JM_WORLD = COUNTS(2)
    allocate(minindex(dimCount,ndes), maxindex(dimCount,ndes), __STAT__)
! Processors in each direction
!-----------------------------
    call MAPL_DistGridGet(distgrid, &
         minIndex=minindex, &
         maxIndex=maxindex, _RC)
    call MAPL_GetImsJms(Imins=minindex(1,:),Imaxs=maxindex(1,:),&
         Jmins=minindex(2,:),Jmaxs=maxindex(2,:),Ims=ims,Jms=jms,_RC)
    deallocate(maxindex, minindex)
    this%NX = size(ims)
    this%NY = size(jms)
! My processor coordinates
!-------------------------
    this%NX0 = mod(this%MYID,this%NX) + 1
    this%NY0 = this%MYID/this%NX + 1
    lgr => logging%get_logger('MAPL.BASE')
    call lgr%debug("grid global max= [%3(i0,:,',')~]", WrapArray(counts))
    call lgr%debug(" NX: %i0 ;   NY: %i0", this%nx, this%ny)
    call lgr%debug("NX0: %i0 ;  NY0: %i0", this%nx0, this%ny0)
    call lgr%debug("ims: [%1000(i0,:,',')~]", WrapArray(ims))
    call lgr%debug("jms: [%1000(i0,:,',')~]", WrapArray(jms))
    deallocate(jms, ims)
    call GridCoordGet(   this%ESMFGRID, this%LATS       , &
         Name     = "Latitude"              , &
         Location = ESMF_STAGGERLOC_CENTER  , &
         Units    = MAPL_UnitsRadians      , &
         _RC                               )
    call GridCoordGet(   this%ESMFGRID, this%LONS       , &
         Name     = "Longitude"             , &
         Location = ESMF_STAGGERLOC_CENTER  , &
         Units    = MAPL_UnitsRadians      , &
         _RC                               )
    _RETURN(ESMF_SUCCESS)
 end subroutine set
Call graph
set calls ESMF_DistGridGet, ESMF_GridGet, ESMF_GridValidate, ESMF_VMGet, ESMF_VMGetCurrent, wraparray, get_logger, debug, gridcoordget, mapl_distgridget, mapl_getimsjms, mapl_gridget, mapl_return, mapl_verify
wraparray calls wrap1d, wrap2d, wrap3d, wrap4d, wrap5d
gridcoordget calls ESMF_GridGet, mapl_gridget, mapl_return, mapl_verify, ESMF_GridGetCoord, mapl_assert
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridget calls ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_getimsjms, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
create_subobjects calls set
mapl_gridcreate calls set
activate_threading calls create_subobjects
initialize_ calls mapl_gridcreate
omp_driver calls activate_threading
mapl_genericwrapper calls omp_driver