spherical_to_cartesian_2d_real32 – MAPL
spherical_to_cartesian_2d_real32 Subroutine
42 statements
Source File
private subroutine spherical_to_cartesian_2d_real32(this, u, v, xyz, basis, unusable, rc)
Uses
mapl_KeywordEnforcerMod
ESMF
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout), target :: this
real(kind=REAL32), intent(in) :: u(:,:)
real(kind=REAL32), intent(in) :: v(:,:)
real(kind=REAL32), intent(out) :: xyz(:,:,:,:)
character(len=*), intent(in) :: basis
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine spherical_to_cartesian_2d_real32(this,u,v,xyz,basis,unusable,rc)
      use esmf
      use MAPL_KeywordEnforcerMod
      real(REAL32), intent(IN) :: u(:,:)
      real(REAL32), intent(IN) :: v(:,:)
      real(REAL32), intent(OUT) :: xyz(:,:,:,:)
      character(len=*), intent(in) :: basis
      class (AbstractGridFactory), target, intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      real(REAL64), pointer :: basis_vectors(:,:,:,:)
      real(REAL32) :: uv(2)
      integer :: i, j, im, jm
      character(len=*), parameter :: Iam= MOD_NAME // 'spherical_to_cartesian_2d'
      integer :: status
      _UNUSED_DUMMY(unusable)
      im = size(u,1)
      jm = size(u,2)
      _ASSERT(im == size(v,1), 'u-v shape mismatch for IM')
      _ASSERT(jm == size(v,2), 'u-v shape mismatch for JM')
      _ASSERT(3 == size(xyz,1), 'u-v shape mismatch (LM=1)')
      _ASSERT(1 == size(xyz,2), 'u-xyz shape mismatch (LM=1)')
      _ASSERT(im == size(xyz,3), 'u-xyz shape mismatch for IM')
      _ASSERT(jm == size(xyz,4), 'u-xyz shape mismatch for JM')
      basis_vectors => this%get_basis(basis,rc=status)
      _VERIFY(status)
      do j=1,jm
         do i=1,im
            if (u(i,j) == MAPL_UNDEF .or. v(i,j) == MAPL_UNDEF) then
               xyz(:,1,i,j) = MAPL_UNDEF
            else
               uv = [u(i,j),v(i,j)]
               xyz(:,1,i,j) = matmul(basis_vectors(:,:,i,j), uv)
            end if
         enddo
      enddo
      _RETURN(_SUCCESS)
   end subroutine spherical_to_cartesian_2d_real32
Call graph
spherical_to_cartesian_2d_real32 calls mapl_assert, get_basis, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_basis calls mapl_assert, mapl_return, mapl_verify, ESMF_GridGetCoord, computegridbasis, computexyzbasis
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
computegridbasis calls mapl_return, mapl_verify, ESMF_GridGetCoord, mapl_gridgetcorners, get_unit_vector, mapl_gridget, mid_pt_sphere
computexyzbasis calls mapl_return, mapl_verify
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_gridgetcorners calls mapl_gridgetcorners
get_unit_vector calls latlon2xyz
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mid_pt_sphere calls latlon2xyz, xyz2latlon