stage2DLatLon – MAPL
stage2DLatLon Subroutine
59 statements
Source File
private subroutine stage2DLatLon(this, fileName, oClients, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout), target :: this
character(len=*), intent(in) :: fileName
type(ClientManager), intent(inout), optional, target :: oClients
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine stage2DLatLon(this, fileName, oClients, rc)
     class (MAPL_GriddedIO), target, intent(inout) :: this
     character(len=*), intent(in) :: fileName
     type (ClientManager), optional, target, intent(inout) :: oClients
     integer, optional, intent(out) :: rc
     integer :: status
     real(REAL64), pointer :: ptr2d(:,:)
     type(ArrayReference), target :: ref
     class (AbstractGridFactory), pointer :: factory
     integer, allocatable :: localStart(:),globalStart(:),globalCount(:)
     logical :: hasll
     hasll = this%metadata%has_variable('lons') .and. this%metadata%has_variable('lats')
     if (hasll) then
        factory => get_factory(this%output_grid,rc=status)
        _VERIFY(status)
        call factory%generate_file_bounds(this%output_grid,LocalStart,GlobalStart,GlobalCount,rc=status)
        _VERIFY(status)
        call ESMF_GridGetCoord(this%output_grid, localDE=0, coordDim=1, &
        staggerloc=ESMF_STAGGERLOC_CENTER, &
        farrayPtr=ptr2d, rc=status)
        _VERIFY(STATUS)
        this%lons=ptr2d*MAPL_RADIANS_TO_DEGREES
        associate (lons => this%lons)
          ref = ArrayReference(lons)
        end associate
        call oClients%collective_stage_data(this%write_collection_id,trim(filename),'lons', &
             ref,start=localStart, global_start=GlobalStart, global_count=GlobalCount)
        call ESMF_GridGetCoord(this%output_grid, localDE=0, coordDim=2, &
        staggerloc=ESMF_STAGGERLOC_CENTER, &
        farrayPtr=ptr2d, rc=status)
        _VERIFY(STATUS)
        if (.not.allocated(this%lats)) allocate(this%lats(size(ptr2d,1),size(ptr2d,2)))
        this%lats=ptr2d*MAPL_RADIANS_TO_DEGREES
        associate (lats => this%lats)
          ref = ArrayReference(lats)
        end associate
         call oClients%collective_stage_data(this%write_collection_id,trim(filename),'lats', &
              ref,start=localStart, global_start=GlobalStart, global_count=GlobalCount)
        deallocate(LocalStart,GlobalStart,GlobalCount)
     end if
     hasll = this%metadata%has_variable('corner_lons') .and. this%metadata%has_variable('corner_lats')
     if (hasll) then
        factory => get_factory(this%output_grid,rc=status)
        _VERIFY(status)
        call factory%generate_file_corner_bounds(this%output_grid,LocalStart,GlobalStart,GlobalCount,rc=status)
        _VERIFY(status)
        call ESMF_GridGetCoord(this%output_grid, localDE=0, coordDim=1, &
        staggerloc=ESMF_STAGGERLOC_CORNER, &
        farrayPtr=ptr2d, rc=status)
        _VERIFY(STATUS)
        this%corner_lons=ptr2d*MAPL_RADIANS_TO_DEGREES
        associate (corner_lons => this%corner_lons)
          ref = ArrayReference(corner_lons)
        end associate
         call oClients%collective_stage_data(this%write_collection_id,trim(filename),'corner_lons', &
              ref,start=localStart, global_start=GlobalStart, global_count=GlobalCount)
        call ESMF_GridGetCoord(this%output_grid, localDE=0, coordDim=2, &
        staggerloc=ESMF_STAGGERLOC_CORNER, &
        farrayPtr=ptr2d, rc=status)
        _VERIFY(STATUS)
        if (.not.allocated(this%corner_lats)) allocate(this%corner_lats(size(ptr2d,1),size(ptr2d,2)))
        this%corner_lats=ptr2d*MAPL_RADIANS_TO_DEGREES
        associate (corner_lats => this%corner_lats)
          ref = ArrayReference(corner_lats)
        end associate
         call oClients%collective_stage_data(this%write_collection_id,trim(filename),'corner_lats', &
              ref,start=localStart, global_start=GlobalStart, global_count=GlobalCount)
     end if
     _RETURN(_SUCCESS)
  end subroutine stage2DLatLon
Call graph
stage2dlatlon calls ESMF_GridGetCoord, generate_file_bounds, generate_file_corner_bounds, collective_stage_data, get_factory, has_variable, mapl_return, mapl_verify
collective_stage_data calls mapl_return, mapl_verify, collective_stage_data, current, get_connection, get_unique_collective_request_id, insert_requesthandle, put, receive, send
get_factory calls mapl_return, mapl_verify, get_factory, ESMF_InfoGet, ESMF_InfoGetFromHost, m_at
has_variable calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
current calls at
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_connection calls mapl_return, mapl_assert
insert_requesthandle calls mapl_return, insert
m_at calls m_find
bundlepost calls stage2dlatlon
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main