start_new_file – MAPL
start_new_file Subroutine
11 statements
Source File
private subroutine start_new_file(this, filename, rc)
Type Bound
FieldBundleWriter
Arguments
Type Intent Optional Attributes Name
class(FieldBundleWriter), intent(inout) :: this
character(len=*), intent(in) :: filename
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine start_new_file(this,filename,rc)
         class(fieldBundleWriter),intent(inout) :: this
         character(len=*), intent(in) :: filename
         integer, optional, intent(out) :: rc
         integer :: status
         this%file_name=filename
         call this%cfio%modifyTime(oClients=o_clients,_RC)
         _RETURN(_SUCCESS)
      end subroutine start_new_file
Call graph
start_new_file calls mapl_return, mapl_verify, modifytime
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modifytime calls mapl_return, mapl_verify, mapl_assert, insert, define_time_variable, modify_metadata, modify_variable
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
define_time_variable calls mapl_return, mapl_verify, mapl_assert, ESMF_ClockGet, ESMF_TimeGet, add_attribute, v_clear
get_error_message calls at, insert
mapl_throw_exception calls initialize
modify_metadata calls mapl_return, mapl_verify, current, modify_metadata
modify_variable calls mapl_return, mapl_assert, at, begin, get, next, get_dimensions, map_set_
main calls start_new_file
time_ave calls start_new_file
regrid_util calls main