State2Bundle – MAPL
State2Bundle Subroutine
68 statements
Source File
private subroutine State2Bundle(STA, BUN, usrfldlist, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STA
type(ESMF_FieldBundle), intent(inout) :: BUN
character(len=*), intent(in), optional :: usrfldlist
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine State2Bundle (STA, BUN, usrfldlist, rc)
!-------------------------------------------------------------------------
! extract fields from state and add to a bundle
   type(ESMF_FieldBundle), intent(inout) :: BUN
   type(ESMF_State) , intent(inout) :: STA
   character(len=*),intent(in),optional :: usrfldlist
   integer, intent(out), optional   :: rc
! locals
   integer          :: status
   integer          :: mype
   integer          :: i, itemcount
   type(ESMF_VM)    :: VM
   type(ESMF_Field) :: FLD
   type(ESMF_Grid)  :: GRID
   character (len=ESMF_MAXSTR)           :: fldname
   character (len=ESMF_MAXSTR), pointer  :: namelist(:)
   type(ESMF_StateItem_Flag)  , pointer  :: typelist(:)
   character(len=ESMF_MAXSTR)            :: name
   character(len=ESMF_MAXSTR), parameter :: IAm='State2Bundle'
   logical                               :: field_found_already
! start
   call ESMF_VMGetCurrent(VM)
   call ESMF_VMGet(vm, localPet=mype, rc=status)
   _VERIFY(STATUS)
   call ESMF_StateGet(STA, itemcount=itemcount, rc=status)
   _VERIFY(STATUS)
   if(itemcount==0) then
      if (verbose) print *,' state is empty'
      _RETURN(ESMF_FAILURE)
   end if
   allocate(namelist(itemcount), stat=status)
   _VERIFY(STATUS)
   allocate(typelist(itemcount), stat=status)
   _VERIFY(STATUS)
   call ESMF_StateGet(STA, itemnamelist=namelist, &
                      itemtypelist=typelist, rc=status)
   _VERIFY(STATUS)
   field_found_already = .false.
   do i=1,itemcount
      if(typelist(i)/=ESMF_STATEITEM_FIELD) cycle
      call ESMF_StateGet(STA, trim(namelist(i)), FLD, &
           rc=status)
      _VERIFY(STATUS)
      if(verbose .and. MAPL_AM_I_ROOT()) print *, ' Got ',trim(namelist(i)),' from field'
      ! get grid from first field in state, and create bundle
      if (.not. field_found_already) then
         field_found_already = .true.
         call ESMF_StateGet(STA, name=name, rc=status)
         _VERIFY(STATUS)
         name = name//'to bundle'
         call ESMF_FieldGet (FLD, grid=GRID, rc=status)
         _VERIFY(STATUS)
         ! create bundle with input grid
         BUN = ESMF_FieldBundleCreate ( name=name, rc=status )
         _VERIFY(STATUS)
         call ESMF_FieldBundleSet(BUN, grid=grid, rc=status)
         _VERIFY(STATUS)
      end if
     ! populate bundle
     if (present(usrfldlist) ) then
         call ESMF_FieldGet(FLD, NAME=fldname, rc=status )
         _VERIFY(STATUS)
         if(.not. check_list_(fldname,usrfldlist)) cycle
     endif
     call MAPL_FieldBundleAdd (BUN, FLD, rc=status)
     _VERIFY(STATUS)
   end do
   deallocate(typelist)
   deallocate(namelist)
   if (.not. field_found_already) then
      _RETURN(ESMF_FAILURE)
   end if
   _RETURN(ESMF_SUCCESS)
   end subroutine State2Bundle
Call graph
state2bundle calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundlecreate, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_am_i_root, mapl_fieldbundleadd, check_list_, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, esmf_fieldget, mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoRemove, ESMF_InfoSet, esmf_fieldbundleadd
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
esmfl_state2bundle calls state2bundle
statediff calls state2bundle
esmfl_diff calls statediff
statestatistics calls statediff
esmfl_statistics calls statestatistics