StringAttributeMap_deserialize – MAPL
StringAttributeMap_deserialize Subroutine
30 statements
Source File
public subroutine StringAttributeMap_deserialize(buffer, map, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(StringAttributeMap), intent(inout) :: map
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine StringAttributeMap_deserialize(buffer, map, rc)
       integer, intent(in) :: buffer(:)
       type (StringAttributeMap), intent(inout) :: map
       integer, optional, intent(out) :: rc
       character(len=:),allocatable :: key
       integer :: length,n,n0,n1,n2
       type (Attribute) :: attr
       integer :: status
       n = 1
       call deserialize_intrinsic(buffer(n:),length)
       _ASSERT(length == size(buffer), "length does not match")
       n0 = serialize_buffer_length(length)
       n = n + n0
       length = length - n0
       map = StringAttributeMap()
       do while (length > 0)
          call deserialize_intrinsic(buffer(n:),key)
          n1 = serialize_buffer_length(key)
          n = n + n1
          !allocate(attr)
          call deserialize_intrinsic(buffer(n:),n2)
          call Attribute_deserialize(buffer(n:n+n2-1), attr, status)
          _VERIFY(status)
          n = n + n2
          length = length - n1 - n2
          call map%insert(key,attr)
          deallocate(key)
          !deallocate(attr)
       enddo
       _RETURN(_SUCCESS)
    end subroutine StringAttributeMap_deserialize
Call graph
stringattributemap_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, insert, attribute_deserialize, mapl_return, mapl_verify
attribute_deserialize calls mapl_return, mapl_verify, unlimitedentity_deserialize
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
unlimitedentity_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, get_rank, set
variable_deserialize calls stringattributemap_deserialize
main calls stringattributemap_deserialize
coordinatevariable_deserialize calls variable_deserialize
filemetadata_deserialize calls variable_deserialize, stringvariablemap_deserialize
stringvariablemap_deserialize calls variable_deserialize, coordinatevariable_deserialize
test_serialize calls variable_deserialize, filemetadata_deserialize, coordinatevariable_deserialize
historycollectionvector_deserialize calls filemetadata_deserialize