success – MAPL
success Function
4 statements
Source File
private function success(utstatus)
Arguments
Type Intent Optional Attributes Name
integer(kind=ut_status) :: utstatus
Return Value logical
Called by
Source Code
   logical function success(utstatus)
      integer(ut_status) :: utstatus
      success = (utstatus == UT_SUCCESS)
   end function success
Call graph
are_convertible_udunit calls success
construct_converter calls success, are_convertible
construct_system calls success
construct_unit calls success
are_convertible calls are_convertible_udunit, are_convertible_str
converter calls construct_converter
udsystem calls construct_system
udunit calls construct_unit
are_convertible_str calls are_convertible_udunit
can_connect_units calls are_convertible
test_are_convertible calls are_convertible
test_are_not_convertible calls are_convertible
can_connect_to calls can_connect_units