supports_hconfig – MAPL
supports_hconfig Module Function
11 statements
Source File
module function supports_hconfig(this, hconfig, rc) result(supports) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical module function supports_hconfig(this, hconfig, rc) result(supports)
      class(LatLonGeomFactory), intent(in) :: this
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      type(LatLonGeomSpec) :: spec
      supports = spec%supports(hconfig, _RC)
      _RETURN(_SUCCESS)
   end function supports_hconfig
Call graph
supports_hconfig calls supports, mapl_return, mapl_verify, supports_hconfig
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
supports_hconfig_ calls supports_hconfig_, mapl_return, mapl_verify, esmf_hconfigasstring, esmf_hconfigisdefined, supports
supports_metadata_ calls supports_metadata_, mapl_return, mapl_verify, supports
get_error_message calls at, insert
mapl_throw_exception calls initialize