supports_hconfig_ – MAPL
supports_hconfig_ Module Function
36 statements
Source File
module function supports_hconfig_(this, hconfig, rc) result(supports) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomSpec), intent(in) :: this
type(ESMF_HConfig), intent(in) :: hconfig
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical module function supports_hconfig_(this, hconfig, rc) result(supports)
      class(LatLonGeomSpec), intent(in) :: this
      type(ESMF_HConfig), intent(in) :: hconfig
      integer, optional, intent(out) :: rc
      integer :: status
      type(LonAxis) :: lon_axis
      type(LatAxis) :: lat_axis
      character(:), allocatable :: geom_schema
      ! Mandatory entry: "class: latlon"
      supports = ESMF_HConfigIsDefined(hconfig, keystring='schema', _RC)
      _RETURN_UNLESS(supports)
      geom_schema = ESMF_HConfigAsString(hconfig, keyString='schema', _RC)
      supports = (geom_schema == 'latlon')
      _RETURN_UNLESS(supports)
      supports = lon_axis%supports(hconfig, _RC)
      _RETURN_UNLESS(supports)
      supports = lat_axis%supports(hconfig, _RC)
      _RETURN_UNLESS(supports)
      _RETURN(_SUCCESS)
   end function supports_hconfig_
Call graph
supports_hconfig_ calls esmf_hconfigasstring, esmf_hconfigisdefined, supports, mapl_return, mapl_verify, supports_hconfig_
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
supports_hconfig calls supports_hconfig, esmf_hconfigisdefined, mapl_return, mapl_verify, supports
supports_metadata calls supports_metadata, mapl_return, mapl_verify, get_dim_name, supports
get_error_message calls at, insert
mapl_throw_exception calls initialize