supports – MAPL
supports Function
21 statements
Source File
private function supports(spec, unusable, rc)
Type Bound
HorizontalFluxRegridder
Arguments
Type Intent Optional Attributes Name
type(RegridderSpec), intent(in) :: spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value logical
Calls
Source Code
   logical function supports(spec, unusable, rc)
      type(RegridderSpec), intent(in) :: spec
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: counts_in(5)
      integer :: counts_out(5)
      integer :: status
      _UNUSED_DUMMY(unusable)
      supports = (spec%regrid_method == REGRID_METHOD_CONSERVE_HFLUX)
      if (.not. supports) return
      call MAPL_GridGet(spec%grid_in, localCellCountPerDim=counts_in, _RC)
      call MAPL_GridGet(spec%grid_out, localCellCountPerDim=counts_out, _RC)
      supports = all(mod(counts_in(1:2), counts_out(1:2)) == 0) .or. all(mod(counts_out, counts_in) == 0)
      _RETURN(_SUCCESS)
   end function supports
Call graph
supports calls mapl_gridget, mapl_return, mapl_verify
mapl_gridget calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize