supports_metadata – MAPL
supports_metadata Module Function
12 statements
Source File
module function supports_metadata(file_metadata, rc) result(supports) Interface →
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical module function supports_metadata(file_metadata, rc) result(supports)
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: dim_name
      supports = .true.
      dim_name = get_dim_name(file_metadata, units='degrees_north', _RC)
      supports = (dim_name /= '')
      _RETURN(_SUCCESS)
   end function supports_metadata
Call graph
supports_metadata calls get_dim_name, mapl_return, mapl_verify, supports_metadata
get_dim_name calls get_dim_name, mapl_return, mapl_verify, ESMF_UtilStringLowerCase, mapl_assert, of, get_attribute, get_dimensions, get_string, get_variables, is_attribute_present, map_ftn_begin, map_ftn_end, map_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_return, mapl_assert, m_at
get_string calls mapl_return, get_value
get_variables calls mapl_return
is_attribute_present calls mapl_return, m_at
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_next calls map_s_iter_next