supports_metadata – MAPL
supports_metadata Module Function
11 statements
Source File
module function supports_metadata(this, file_metadata, rc) result(supports) Interface →
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomFactory), intent(in) :: this
type(FileMetadata), intent(in) :: file_metadata
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical module function supports_metadata(this, file_metadata, rc) result(supports)
      class(LatLonGeomFactory), intent(in) :: this
      type(FileMetadata), intent(in) :: file_metadata
      integer, optional, intent(out) :: rc
      integer :: status
      type(LatLonGeomSpec) :: spec
      supports = spec%supports(file_metadata, _RC)
      _RETURN(_SUCCESS)
   end function supports_metadata
Call graph
supports_metadata calls supports, mapl_return, mapl_verify, supports_metadata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
supports_hconfig_ calls supports_hconfig_, mapl_return, mapl_verify, esmf_hconfigasstring, esmf_hconfigisdefined, supports
supports_metadata_ calls supports_metadata_, mapl_return, mapl_verify, supports
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_mapl_geom_from_spec calls supports