tearDown – MAPL
tearDown Subroutine
6 statements
Source File
public subroutine tearDown(outer_gc, hconfig)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: outer_gc
type(ESMF_HConfig), intent(inout) :: hconfig
Calls
Called by
Source Code
   subroutine tearDown(outer_gc, hconfig)
      type(ESMF_GridComp), intent(inout) :: outer_gc
      type(ESMF_HConfig), intent(inout) :: hconfig
      call clear_log()
      call ESMF_HConfigDestroy(hconfig)
   end subroutine tearDown
Call graph
teardown calls ESMF_HConfigDestroy, clear_log
test_wasinit calls teardown
test_wasrun_1 calls teardown
test_wasrun_extra calls teardown