teardown_bundle – MAPL
teardown_bundle Subroutine
10 statements
Source File
public subroutine teardown_bundle(bundle)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
Calls
Called by
Source Code
   subroutine teardown_bundle(bundle)
      type(ESMF_FieldBundle), intent(inout) :: bundle
      type(ESMF_Field), allocatable :: fieldList(:)
      integer :: i
      call MAPL_FieldBundleGet(bundle, fieldList=fieldList)
      do i = 1, size(fieldList)
         call ESMF_FieldDestroy(fieldList(i))
      end do
      call ESMF_FieldBundleDestroy(bundle)
   end subroutine teardown_bundle
Call graph
teardown_bundle calls esmf_fieldbundledestroy, esmf_fielddestroy, mapl_fieldbundleget
mapl_fieldbundleget calls ESMF_GeomCreate, esmf_fieldbundleget, mapl_assert, mapl_infocreatefrominternal, mapl_infogetinternal, get_bounds, make_ungriddeddims, mapl_return, mapl_verify
make_ungriddeddims calls mapl_return, mapl_verify, ESMF_InfoCreate, ESMF_InfoDestroy, mapl_infoget, make_dim_key, make_ungriddeddim
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_dim_key calls mapl_assert, mapl_return
make_ungriddeddim calls mapl_return, mapl_verify, mapl_infoget
test_change_geom calls teardown_bundle
test_change_typekind calls teardown_bundle
test_change_units calls teardown_bundle
test_change_weights calls teardown_bundle
test_change_weights_with_ungridded calls teardown_bundle
test_create_fields calls teardown_bundle
test_create_fields_with_ungridded calls teardown_bundle
test_same_geom calls teardown_bundle