tear_down – MAPL
tear_down Subroutine
17 statements
Source File
public subroutine tear_down()
Arguments
None
Calls
Source Code
   subroutine tear_down()
      integer :: status, rc
      call ESMF_TimeSet(start_time, _RC)
      call ESMF_TimeIntervalSet(timestep, _RC)
      call ESMF_ClockDestroy(clock, _RC)
      call ESMF_TimeSet(default_time, _RC)
      call ESMF_TimeIntervalSet(time_interval, _RC)
      call ESMF_TimeSet(update_time, _RC)
      call ESMF_TimeSet(reference_time, _RC)
   end subroutine tear_down
Call graph
tear_down calls ESMF_ClockDestroy, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_verify
mapl_verify calls mapl_throw_exception