teardown_geom – MAPL
teardown_geom Subroutine
7 statements
Source File
public subroutine teardown_geom(geom)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Geom), intent(inout) :: geom
Calls
Called by
Source Code
   subroutine teardown_geom(geom)
      type(ESMF_Geom), intent(inout) :: geom
      type(ESMF_Grid) :: grid
      call ESMF_GeomGet(geom, grid=grid)
      call ESMF_GridDestroy(grid)
      call ESMF_GeomDestroy(geom)
   end subroutine teardown_geom
Call graph
teardown_geom calls ESMF_GeomDestroy, ESMF_GeomGet, ESMF_GridDestroy
test_change_geom calls teardown_geom
test_change_typekind calls teardown_geom
test_change_units calls teardown_geom
test_change_weights calls teardown_geom
test_change_weights_with_ungridded calls teardown_geom
test_create_fields calls teardown_geom
test_create_fields_with_ungridded calls teardown_geom
test_same_geom calls teardown_geom