test_make_grid_multi – MAPL
test_make_grid_multi Subroutine
36 statements
Source File
public subroutine test_make_grid_multi()
Arguments
None
Calls
Source Code
   subroutine test_make_grid_multi()
      type (GridManager) :: grid_manager
      type (ESMF_Grid) :: grid
      integer :: status
      character(len=40) :: grid_name
      type(ESMF_Info) :: infoh
      call grid_manager%add_prototype('grid_type_1', MockGridFactory('foo'))
      call grid_manager%add_prototype('grid_type_2', MockGridFactory('bar'))
      grid = grid_manager%make_grid(config, prefix='default.', rc=status)
      @assertEqual(0, status)
      call ESMF_InfoGetFromHost(grid,infoh,rc=status)
      call ESMF_InfoGet(infoh,'GRID_NAME',grid_name,rc=status)
      if (status /= 0) then
         call grid_manager%delete(grid)
      end if
      @assertEqual(0, status)
      if ('mock' /= trim(grid_name)) then
         call grid_manager%delete(grid)
         return
      end if
      @assertEqual('foo', trim(grid_name))
      call grid_manager%delete(grid)
      grid = grid_manager%make_grid(config, prefix='other.', rc=status)
      call ESMF_InfoGetFromHost(grid,infoh,rc=status)
      call ESMF_InfoGet(infoh,'GRID_NAME',grid_name,rc=status)
      if (status /= 0) then
         call grid_manager%delete(grid)
         return
      end if
      @assertEqual(0, status)
      if ('mock' /= trim(grid_name)) then
         call grid_manager%delete(grid)
      end if
      @assertEqual('bar', trim(grid_name))
      call grid_manager%delete(grid)
   end subroutine test_make_grid_multi
Call graph
test_make_grid_multi calls ESMF_InfoGet, ESMF_InfoGetFromHost, assertequal, make_grid, add_prototype, delete
add_prototype calls insert
delete calls ESMF_GridDestroy, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_grid_from_distgrid calls ESMF_InfoGetFromHost, make_grid, mapl_return, ESMF_InfoSet, make_factory, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception