test_regrid_2d_vector – MAPL
test_regrid_2d_vector Subroutine
109 statements
Source File
public subroutine test_regrid_2d_vector(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_regrid_2d_vector(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(GeomManager), target :: geom_mgr
      type(RegridderManager), target :: regridder_mgr
      type(RegridderSpec) :: spec
      integer :: status
      class(Regridder), pointer :: my_regridder
      type(ESMF_Geom) :: geom_1, geom_2
      type(ESMF_HConfig) :: hconfig
      type(ESMF_Field) :: f1, f2, f3, f4
      type(ESMF_Fieldbundle) :: uv1, uv2
      real(kind=ESMF_KIND_R4), pointer :: u1(:,:)
      real(kind=ESMF_KIND_R4), pointer :: v1(:,:)
      real(kind=ESMF_KIND_R4), pointer :: u2(:,:)
      real(kind=ESMF_KIND_R4), pointer :: v2(:,:)
      type(DynamicMask) :: dyn_mask
      geom_mgr = GeomManager()
      regridder_mgr = RegridderManager(geom_mgr)
      hconfig = ESMF_HConfigCreate(content="{class: latlon, im_world: 12, jm_world: 13, pole: PE, dateline: DE, nx: 1, ny: 1}", _RC)
      geom_1 = make_geom(geom_mgr, hconfig, _RC)
      hconfig = ESMF_HConfigCreate(content="{class: latlon, im_world: 6, jm_world: 5, pole: PE, dateline: DE, nx: 1, ny: 1}", _RC)
      geom_2 = make_geom(geom_mgr, hconfig, _RC) ! variant of geom_1
      dyn_mask = DynamicMask(mask_type='missing_value', src_mask_value=real(MAPL_UNDEF,kind=ESMF_KIND_R8), handleAllElements=.true.,_RC)
      spec = RegridderSpec(EsmfRegridderParam(regridmethod=ESMF_REGRIDMETHOD_BILINEAR, dyn_mask=dyn_mask), geom_1, geom_2)
      my_regridder => regridder_mgr%get_regridder(spec, _RC)
      ! North-east field
      f1 = make_field(geom_1, 'u', value=2._ESMF_KIND_R4, _RC)
      f2 = make_field(geom_1, 'v', value=2._ESMF_KIND_R4, _RC)
      uv1 = MAPL_FieldBundleCreate(name='[u,v]', fieldList=[f1,f2], fieldBundleType=FIELDBUNDLETYPE_VECTOR, _RC)
      call ESMF_FieldGet(f1, farrayptr=u1, _RC)
      u1(::4,6) = MAPL_UNDEF ! checkerboard
      call ESMF_FieldGet(f2, farrayptr=v1, _RC)
      v1(::4,6) = MAPL_UNDEF ! checkerboard
      f3 = make_field(geom_2, 'u', value=0._ESMF_KIND_R4, _RC)
      f4 = make_field(geom_2, 'v', value=0._ESMF_KIND_R4, _RC)
      uv2 = MAPL_FieldBundleCreate(name='[u,v]', fieldList=[f3,f4], fieldBundleType=FIELDBUNDLETYPE_VECTOR, _RC)
      call my_regridder%regrid(uv1, uv2, _RC)
      call ESMF_FieldGet(f3, farrayptr=u2, _RC)
      call ESMF_FieldGet(f4, farrayptr=v2, _RC)
      ! Still north-east?  Note we have a large tolerance due to
      ! coarse grids and inherent issues with vector regridding.
      ! Errors are much smaller at realistic resolutions.
      @assert_that(u2, every_item(is(near(2._ESMF_KIND_R4, 1.e-1))))
      @assert_that(v2, every_item(is(near(2._ESMF_KIND_R4, 1.e-1))))
   end subroutine test_regrid_2d_vector
Call graph
test_regrid_2d_vector calls ESMF_HConfigCreate, anyexceptions, assert_that, esmf_fieldget, esmfregridderparam, every_item, geommanager, fieldbundlecreate, near, get_regridder, make_field, make_geom, regrid, sourcelocation
make_field calls anyexceptions, assert_that, esmf_fieldget, sourcelocation, mapl_fieldcreate
make_geom calls ESMF_HConfigCreate, anyexceptions, assert_that, sourcelocation, get_geom, get_mapl_geom