test_set_stateitem_shared_logical – MAPL
test_set_stateitem_shared_logical Subroutine
44 statements
Source File
public subroutine test_set_stateitem_shared_logical()
Arguments
None
Calls
Source Code
   subroutine test_set_stateitem_shared_logical()
      type(ESMF_State) :: state
      type(ESMF_Field) :: field
      integer :: status
      logical :: l
      logical, parameter :: expected = .true.
      state = ESMF_StateCreate(name='export', _RC)
      field = ESMF_FieldEmptyCreate(name='f', _RC)
      call ESMF_StateAdd(state, [field], _RC)
      call MAPL_InfoSetShared(state, short_name='f', key='a', value=expected, _RC)
      l = .false.
      call MAPL_InfoGetShared(state, short_name='f', key='a', value=l, _RC)
      @assert_that(l, is(true()))
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_set_stateitem_shared_logical
Call graph
test_set_stateitem_shared_logical calls anyexceptions, assert_that, esmf_fielddestroy, esmf_fieldemptycreate, esmf_stateadd, esmf_statecreate, esmf_statedestroy, mapl_infogetshared, mapl_infosetshared, sourcelocation, true