test_same_geom_do_not_reallocate – MAPL
test_same_geom_do_not_reallocate Subroutine
100 statements
Source File
public subroutine test_same_geom_do_not_reallocate(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_same_geom_do_not_reallocate(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_Field) :: f
      type(ESMF_Grid), target :: grid1
      type(ESMF_Geom) :: geom1
      type(ESMF_Geom) :: geom2
      integer :: status
      type(ESMF_FieldStatus_Flag) :: field_status
      type(ESMF_TypeKind_Flag) :: typekind
      real(kind=ESMF_KIND_R4), pointer :: x(:,:)
      grid1 = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', _RC)
      geom1 = ESMF_GeomCreate(grid1, _RC)
      f = ESMF_FieldCreate(geom1, typekind=ESMF_TYPEKIND_R4, name='in', _RC)
      call MAPL_InfoSetInternal(f, key=KEY_NUM_LEVELS, value=ORIGINAL_NUM_LEVELS, _RC)
      call MAPL_InfoSetInternal(f, key=KEY_VLOC, value='VERTICAL_DIM_EDGE', _RC)
      call MAPL_InfoSetInternal(f, key=KEY_NUM_LEVELS, value=ORIGINAL_NUM_LEVELS, _RC)
      call MAPL_InfoSetInternal(f, key=KEY_VLOC, value='VERTICAL_DIM_EDGE', _RC)
      call ESMF_FieldGet(f, fArrayPtr=x, _RC)
      call MAPL_InfoSetInternal(f, key=KEY_NUM_LEVELS, value=ORIGINAL_NUM_LEVELS, _RC)
      call MAPL_InfoSetInternal(f, key=KEY_VLOC, value='VERTICAL_DIM_EDGE', _RC)
      x = FILL_VALUE
      geom2 = geom1
      call FieldReallocate(f, geom=geom2, _RC) ! same geom
      call ESMF_FieldGet(f, status=field_status, typekind=typekind, _RC)
      @assert_that(field_status == ESMF_FIELDSTATUS_COMPLETE, is(true()))
      @assert_that(typekind == ESMF_TYPEKIND_R4, is(true()))
      call ESMF_FieldGet(f, fArrayPtr=x, _RC)
      @assert_that(all(x == FILL_VALUE), is(true()))
      call ESMF_FieldDestroy(f, _RC)
      call ESMF_GridDestroy(grid1, _RC)
      call ESMF_GeomDestroy(geom2, _RC)
      _UNUSED_DUMMY(this)
   end subroutine test_same_geom_do_not_reallocate
Call graph
test_same_geom_do_not_reallocate calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, fieldreallocate, mapl_infosetinternal, sourcelocation, true