test_can_connect_typekind – MAPL
test_can_connect_typekind Subroutine
14 statements
Source File
public subroutine test_can_connect_typekind()
Arguments
None
Calls
Source Code
   subroutine test_can_connect_typekind()
      type(FieldSpec) :: spec_r4, spec_r8, spec_mirror
      type(ESMF_Geom) :: geom
      type(StringVector) :: import_attributes, export_attributes
      spec_r4 = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='m')
      spec_r8 = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R8, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='m')
      spec_mirror = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=MAPL_TYPEKIND_MIRROR, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='m')
      @assert_that(spec_r4%can_connect_to(spec_r4), is(true()))
      @assert_that(spec_r4%can_connect_to(spec_r8), is(true()))
      @assert_that(spec_r8%can_connect_to(spec_r4), is(true()))
      @assert_that(spec_r8%can_connect_to(spec_r8), is(true()))
      @assert_that(spec_mirror%can_connect_to(spec_r4), is(true()))
      @assert_that(spec_mirror%can_connect_to(spec_r8), is(true()))
   end subroutine test_can_connect_typekind
Call graph
test_can_connect_typekind calls assert_that, can_connect_to, true
can_connect_to calls of, can_connect_units, mapl_return, mapl_verify
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
get_error_message calls at, insert
mapl_throw_exception calls initialize