test_add_cycle – MAPL
test_add_cycle Subroutine
10 statements
Source File
public subroutine test_add_cycle()
Arguments
None
Calls
Source Code
   subroutine test_add_cycle()
      type (AdvancedMeter) :: t
      t = AdvancedMeter(MpiTimerGauge())
      call t%add_cycle(increment=1.0_REAL64)
      @assertEqual(1.0, t%get_total())
      call t%add_cycle(increment=2.0_REAL64)
      @assertEqual(3.0, t%get_total())
      @assertEqual(2, t%get_num_cycles())
      @assertFalse(t%is_active())
   end subroutine test_add_cycle
Call graph
test_add_cycle calls assertequal, assertfalse, add_cycle, get_num_cycles, get_total, is_active