test_make_valuestring_i8seq – MAPL
test_make_valuestring_i8seq Subroutine
14 statements
Source File
public subroutine test_make_valuestring_i8seq()
Arguments
None
Calls
Source Code
   subroutine test_make_valuestring_i8seq()
      character(len=*), parameter :: EXPECTED = '[4294967296, 2494967296, 4294697296' // ELLIPSIS // ']' // DEFTAG
      integer(kind=I8), parameter :: DEFAULT(4) = [4294967296_I8, 2494967296_I8, 4294697296_I8, 2949672964_I8]
      integer(kind=I8), allocatable :: value(:)
      type(HConfigParams) :: params
      integer :: status
      character(len=:), allocatable :: valuestring
      character(len=:), allocatable :: error_message
      params = HConfigParams(hconfig, 'label')
      call get_value(params, value, default=DEFAULT, valuestring=valuestring, rc=status)
      @assertEqual(0, status, ERROR_GET_FAILED)
      if(EXPECTED /= valuestring) error_message = valuestring_mismatch(valuestring, EXPECTED)
      @assertEqual(EXPECTED, valuestring, error_message)
   end subroutine test_make_valuestring_i8seq
Call graph
test_make_valuestring_i8seq calls assertequal, get_value, valuestring_mismatch
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
get_value_i4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical_seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_string calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify