test_setInternal – MAPL
test_setInternal Subroutine
43 statements
Source File
public subroutine test_setInternal()
Arguments
None
Calls
Source Code
   subroutine test_setInternal()
      type(ESMF_State) :: state
      type(ESMF_Field) :: field
      integer :: status
      real(ESMF_KIND_R4), allocatable :: w(:)
      real(ESMF_KIND_R4), parameter :: expected(2) = [1., 2.]
      state = ESMF_StateCreate(name='import', _RC)
      field = ESMF_FieldEmptyCreate(name='f', _RC)
      call ESMF_StateAdd(state, [field], _RC)
      call MAPL_InfoSetInternal(state, short_name='f', key='a', values=expected, _RC)
      call MAPL_InfoGetInternal(state, short_name='f', key='a', values=w, _RC)
      @assert_that(w, is(equal_to(expected)))
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_setInternal
Call graph
test_setinternal calls anyexceptions, assert_that, equal_to, esmf_fielddestroy, esmf_fieldemptycreate, esmf_stateadd, esmf_statecreate, esmf_statedestroy, mapl_infogetinternal, mapl_infosetinternal, sourcelocation