test_FieldClone3D_metadata – MAPL
test_FieldClone3D_metadata Subroutine
25 statements
Source File
public subroutine test_FieldClone3D_metadata(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldClone3D_metadata(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x, y
      type(ESMF_Info) :: x_info, y_info
      type(ESMF_Grid) :: grid
      type(ESMF_Geom) :: geom
      integer :: status, rc
      grid= mk_grid('a', _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      x = MAPL_FieldCreate(geom=geom, typekind=ESMF_TYPEKIND_R4, num_levels=3, vert_staggerloc=VERTICAL_STAGGER_EDGE, units='m', standard_name='foo', _RC)
      call FieldClone(x, y, _RC)
      call ESMF_InfoGetFromHost(x, x_info, _RC)
      call ESMF_InfoGetFromHost(y, y_info, _RC)
      @assertTrue(x_info == y_info, 'incorrect copy of info')
      call ESMF_FieldDestroy(y, _RC)
      call ESMF_FieldDestroy(x, _RC)
   end subroutine test_FieldClone3D_metadata
Call graph
test_fieldclone3d_metadata calls ESMF_GeomCreate, ESMF_InfoGetFromHost, asserttrue, esmf_fielddestroy, fieldclone, mapl_fieldcreate, mapl_verify, mk_grid
mapl_verify calls mapl_throw_exception
mk_grid calls mapl_verify, ESMF_GridCreateNoPeriDim, mapl_return
mapl_return calls mapl_throw_exception, at, insert