test_retrieve_exists – MAPL
test_retrieve_exists Subroutine
29 statements
Source File
public subroutine test_retrieve_exists()
Arguments
None
Calls
Source Code
   subroutine test_retrieve_exists()
      type (ESMF_Grid), target :: g1_in, g1_out
      type (RegridderSpec) :: regridder_spec
      type (RegridderFactorySpec) :: factory_spec
      type (RegridderFactoryRegistry) :: registry
      class (AbstractRegridderFactory), pointer :: factory
      class (AbstractRegridder), allocatable :: regridder
      type (ESMF_Info) :: infohin,infohout
      g1_in = ESMF_GridEmptyCreate()
      g1_out = ESMF_GridEmptyCreate()
      call ESMF_InfoGetFromHost(g1_in,infohin)
      call ESMF_InfoSet(infohin,'GridType','A')
      call ESMF_InfoGetFromHost(g1_out,infohout)
      call ESMF_InfoSet(infohout,'GridType','B')
      regridder_spec = RegridderSpec(g1_in, g1_out)
      factory_spec = RegridderFactorySpec(regridder_spec)
      factory => registry%at(factory_spec)
      @assertFalse(associated(factory))
      call registry%insert(factory_spec, MockRegridderFactory('A to B'))
      factory => registry%at(factory_spec)
      @assertTrue(associated(factory))
      allocate(regridder, source=factory%make_regridder(regridder_spec))
      select type (regridder)
      type is (MockRegridder)
         @assertEqual('A to B::A -> B', regridder%get_name())
      class default
         call throw('incorrect type of regridder returned')
      end select
   end subroutine test_retrieve_exists
Call graph
test_retrieve_exists calls ESMF_GridEmptyCreate, ESMF_InfoGetFromHost, ESMF_InfoSet, assertequal, assertfalse, asserttrue, at, get_name, insert, make_regridder, mockregridderfactory, regridderfactoryspec, regridderspec, throw