test_get_zero – MAPL
test_get_zero Subroutine
19 statements
Source File
public subroutine test_get_zero()
Arguments
None
Calls
Source Code
   subroutine test_get_zero()
      type(ESMF_TimeInterval) :: interval
      integer(ESMF_KIND_I4) :: ns
      integer(ESMF_KIND_I4), parameter :: EXPECTED_NS = 0
      integer(ESMF_KIND_I4), parameter :: INITIAL_NS = 1
      integer :: status
      call ESMF_TimeIntervalSet(interval, ns=INITIAL_NS, _RC)
      interval = zero_time_interval()
      call ESMF_TimeIntervalGet(interval, ns=ns, _RC)
      @assertEqual(EXPECTED_NS, ns, 'Interval is not zero.')
   end subroutine test_get_zero
Call graph
test_get_zero calls ESMF_TimeIntervalGet, ESMF_TimeIntervalSet, anyexceptions, assert_that, assertequal, zero_time_interval, sourcelocation