test_invalidate – MAPL
test_invalidate Subroutine
58 statements
Source File
public subroutine test_invalidate()
Arguments
None
Calls
Source Code
   subroutine test_invalidate()
      type(AccumulatorAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      type(ESMF_Field) :: import_field
      real(kind=R4), parameter :: invalidate_value = 4.0_R4
      logical :: equals_expected_value
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call get_field(importState, import_field, _RC)
      call FieldSet(import_field, invalidate_value, _RC)
      call acc%invalidate(importState, exportState, clock, _RC)
      @assertFalse(acc%update_calculated, 'update_calculated .TRUE.')
      equals_expected_value = FieldIsConstant(acc%accumulation_field, invalidate_value, _RC)
      @assertTrue(equals_expected_value, 'accumulation_field not equal to invalidate_value')
      call acc%invalidate(importState, exportState, clock, _RC)
      @assertFalse(acc%update_calculated, 'update_calculated .TRUE.')
      equals_expected_value = FieldIsConstant(acc%accumulation_field, 2*invalidate_value, _RC)
      @assertTrue(equals_expected_value, 'accumulation_field .FALSE.')
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_invalidate
Call graph
test_invalidate calls anyexceptions, assert_that, assertfalse, asserttrue, fieldisconstant, fieldset, initialize, invalidate, destroy_objects, get_field, initialize_objects, sourcelocation
destroy_objects calls anyexceptions, assert_that, get_field, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy
get_field calls anyexceptions, assert_that, sourcelocation, esmf_stateget
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate