test_wasrun_extra – MAPL
test_wasrun_extra Subroutine
15 statements
Source File
public subroutine test_wasrun_extra(this)
Uses
scratchpad
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_wasrun_extra(this)
      use scratchpad
      class(MpiTestMethod), intent(inout) :: this
      integer :: status
      type(ESMF_GridComp) :: outer_gc
      type(ESMF_HConfig) :: config
      config = ESMF_HConfigCreate(content='{}', rc=status)
      call setup(outer_gc, config, status)
      @assert_that(status, is(0))
      call ESMF_GridCompRun(outer_gc, phase=2, rc=status)
      @assert_that(status, is(0))
      @assertEqual("wasRun_extra_A", log)
      call teardown(outer_gc, config)
      if(.false.) print*,shape(this)
   end subroutine test_wasrun_extra
Call graph
test_wasrun_extra calls ESMF_GridCompRun, ESMF_HConfigCreate, assert_that, assertequal, setup, teardown
setup calls assert_that, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_gridcompsetservices, create_grid_comp, user_setservices, clear_log
teardown calls ESMF_HConfigDestroy, clear_log
create_grid_comp calls create_grid_comp_primary
user_setservices calls new_dsosetservices, new_procsetservices
create_grid_comp_primary calls ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic