test_update – MAPL
test_update Subroutine
125 statements
Source File
public subroutine test_update()
Arguments
None
Calls
Source Code
   subroutine test_update()
      type(AccumulatorAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      type(ESMF_Field) :: import_field, export_field
      real(kind=R4), parameter :: invalidate_value = 4.0_R4
      real(kind=R4) :: update_value
      logical :: equals_expected_value
      ! Set up
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      ! Initialize
      call acc%initialize(importState, exportState, clock, _RC)
      ! Set import_field for invalidate step.
      call get_field(importState, import_field, _RC)
      call FieldSet(import_field, invalidate_value, _RC)
      ! Invalidate.
      call acc%invalidate(importState, exportState, clock, _RC)
      ! Check invalidate.
      @assert_that(acc%update_calculated, is(false()))
      equals_expected_value = FieldIsConstant(acc%accumulation_field, invalidate_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! Set expected value for update.
      update_value = invalidate_value
      ! Update.
      call acc%update(importState, exportState, clock, _RC)
      ! Check update.
      @assert_that(acc%update_calculated, is(true()))
      ! Check that accumulation_field is cleared.
      equals_expected_value = FieldIsConstant(acc%accumulation_field, acc%CLEAR_VALUE_R4, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! Check result_field
      equals_expected_value = FieldIsConstant(acc%result_field, update_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! Check export_field.
      call get_field(exportState, export_field, _RC)
      equals_expected_value = FieldIsConstant(export_field, update_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! Invalidate
      call acc%invalidate(importState, exportState, clock, _RC)
      ! Check invalidate.
      @assert_that(acc%update_calculated, is(false()))
      ! Invalidate again.
      call acc%invalidate(importState, exportState, clock, _RC)
      ! Check invalidate, again.
      @assert_that(acc%update_calculated, is(false()))
      ! This time accumulation_field should show true accumulation.
      update_value = 2 * invalidate_value
      equals_expected_value = FieldIsConstant(acc%accumulation_field, update_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! Update
      call acc%update(importState, exportState, clock, _RC)
      ! Check update.
      @assert_that(acc%update_calculated, is(true()))
      ! Check that accumulation_field is cleared.
      equals_expected_value = FieldIsConstant(acc%accumulation_field, acc%CLEAR_VALUE_R4, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! This time result_field should show true accumulation.
      equals_expected_value = FieldIsConstant(acc%result_field, update_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! This time export_field should show true accumulation.
      call get_field(exportState, export_field, _RC)
      equals_expected_value = FieldIsConstant(export_field, update_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      ! Tear down.
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_update
Call graph
test_update calls anyexceptions, assert_that, false, fieldisconstant, fieldset, initialize, invalidate, update, destroy_objects, get_field, initialize_objects, sourcelocation, true