test_make_valuestring_i4seq – MAPL
test_make_valuestring_i4seq Subroutine
14 statements
Source File
public subroutine test_make_valuestring_i4seq()
Arguments
None
Calls
Source Code
   subroutine test_make_valuestring_i4seq()
      character(len=*), parameter :: EXPECTED = '[613, 361, 631' // ELLIPSIS // ']' // DEFTAG
      integer(kind=I4), parameter :: DEFAULT(5) = [613, 361, 631, 136, 163]
      integer(kind=I4), allocatable :: value(:)
      type(HConfigParams) :: params
      integer :: status
      character(len=:), allocatable :: valuestring
      character(len=:), allocatable :: error_message
      params = HConfigParams(hconfig, 'label')
      call get_value(params, value, default=DEFAULT, valuestring=valuestring, rc=status)
      @assertEqual(0, status, ERROR_GET_FAILED)
      if(EXPECTED /= valuestring) error_message = valuestring_mismatch(valuestring, EXPECTED)
      @assertEqual(EXPECTED, valuestring, error_message)
   end subroutine test_make_valuestring_i4seq
Call graph
test_make_valuestring_i4seq calls assertequal, get_value, valuestring_mismatch