test_wasfinal – MAPL
test_wasfinal Subroutine
14 statements
Source File
public subroutine test_wasfinal(this)
Uses
scratchpad
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_wasfinal(this)
      use scratchpad
      class(MpiTestMethod), intent(inout) :: this
      integer :: status
      type(ESMF_GridComp) :: outer_gc
      type(ESMF_HConfig) :: config
      config = ESMF_HConfigCreate(content='{}', rc=status)
      call setup(outer_gc, config, status)
      @assert_that(status, is(0))
      call ESMF_GridCompFinalize(outer_gc, phase=GENERIC_FINALIZE_USER, rc=status)
      @assert_that(status, is(0))
      @assertEqual("wasFinal_A", log)
      ! Note - do not need to call teardown, as we are
      ! finalizing ourselves.  But .. we do need to check that the
      ! user_gc has been finalized, and that the various internal states
      ! have been freed.
      if(.false.) print*,shape(this)
   end subroutine test_wasfinal
Call graph
test_wasfinal calls ESMF_GridCompFinalize, ESMF_HConfigCreate, assert_that, assertequal, setup
setup calls assert_that, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_gridcompsetservices, create_grid_comp, user_setservices, clear_log
create_grid_comp calls create_grid_comp_primary
user_setservices calls new_dsosetservices, new_procsetservices
create_grid_comp_primary calls ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic