test_reproducer_from_history – MAPL
test_reproducer_from_history Subroutine
31 statements
Source File
public subroutine test_reproducer_from_history()
Arguments
None
Calls
Source Code
   subroutine test_reproducer_from_history()
      type(ESMF_HConfig) :: a, b
      logical :: match
      integer :: status
      a = ESMF_HConfigCreate(content='{geom: {class: latlon}, collection_name: c1}', _RC)
      b = ESMF_HConfigCreate(content='{geom: {class: latlon}, collection_name: c1}', _RC)
      match = MAPL_HConfigMatch(a, b, _RC)
      @assert_that(match, is(true()))
      call ESMF_HConfigDestroy(a, _RC)
      call ESMF_HConfigDestroy(b, _RC)
   end subroutine test_reproducer_from_history
Call graph
test_reproducer_from_history calls ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, mapl_hconfigmatch, sourcelocation, true
mapl_hconfigmatch calls ESMF_HConfigDestroy, ESMF_HConfigAsStringMapKey, ESMF_HConfigIterLoop, esmf_hconfigasi8, esmf_hconfigaslogical, esmf_hconfigasr8, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigisscalar, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize