test_do_not_propagate_satisfied_import – MAPL
test_do_not_propagate_satisfied_import Subroutine
24 statements
Source File
public subroutine test_do_not_propagate_satisfied_import()
Arguments
None
Calls
Source Code
   subroutine test_do_not_propagate_satisfied_import()
      type(StateRegistry), target :: r_child, r_parent
      integer :: status
      type(VirtualConnectionPt) :: v_pt
      type(MockItemSpec), target :: spec
      r_parent = StateRegistry('parent')
      r_child = StateRegistry('child')
      call r_parent%add_subregistry(r_child)
      v_pt = VirtualConnectionPt(state_intent='import', short_name='T')
      spec = MockItemSpec('T_child')
      call spec%set_active()
      call r_child%add_primary_spec(v_pt, spec, _RC)
      call r_parent%propagate_unsatisfied_imports(_RC)
      @assert_that(r_parent%num_owned_items(), is(0))
      @assert_that(r_parent%has_virtual_pt(v_pt), is(false()))
   end subroutine test_do_not_propagate_satisfied_import
Call graph
test_do_not_propagate_satisfied_import calls anyexceptions, assert_that, false, add_primary_spec, add_subregistry, has_virtual_pt, num_owned_items, propagate_unsatisfied_imports, set_active, sourcelocation
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception