test_connect – MAPL
test_connect Subroutine
23 statements
Source File
public subroutine test_connect(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_connect(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(HierarchicalRegistry) :: r
      type(HierarchicalRegistry), target :: r_A, r_B ! child registries
      type(VirtualConnectionPt) :: cp_A, cp_B
      type(SimpleConnection) :: conn
      type(ActualPtVector), pointer :: actual_pts
      integer :: status
      r = HierarchicalRegistry('P')
      r_a = HierarchicalRegistry('child_A')
      r_b = HierarchicalRegistry('child_B')
      call r%add_subregistry(r_a)
      call r%add_subregistry(r_b)
      cp_A = new_v_pt('export', 'ae')
      cp_B = new_v_pt('import', 'ai')
      call r_a%add_item_spec(cp_A, MockItemSpec('AE'))
      call r_b%add_item_spec(cp_B, MockItemSpec('AI'))
      conn = SimpleConnection(CP('child_A', cp_A), CP('child_B', cp_B))
      call r%add_connection(conn, rc=status)
      @assert_that(status, is(0))
      ! Check that extension was created
      actual_pts => r_a%get_actual_pts(cp_A)
      @assert_that(int(actual_pts%size()), is(2))
   end subroutine test_connect
Call graph
test_connect calls assert_that, add_item_spec, add_connection, add_subregistry, get_actual_pts, new_v_pt
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
get_actual_pts calls at
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item_spec_actual calls mapl_assert, mapl_return, mapl_verify, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception