test_import_from_child – MAPL
test_import_from_child Subroutine
20 statements
Source File
public subroutine test_import_from_child(this)
$ if (.not. check(r_parent, vpt_parent, [‘AE’])) return
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_import_from_child(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(HierarchicalRegistry), target :: r_parent, r_child
      type(VirtualConnectionPt) :: vpt_parent, vpt_child
      type(SimpleConnection) :: conn
      integer :: status
      type(ActualPtVector), pointer :: actual_pts
      r_parent = HierarchicalRegistry('parent')
      r_child = HierarchicalRegistry('child')
      call r_parent%add_subregistry(r_child)
      vpt_parent = new_v_pt('import', 'ai')
      vpt_child = new_v_pt('export', 'ae')
      call r_parent%add_item_spec(vpt_parent, MockItemSpec('AI'))
      call r_child%add_item_spec(vpt_child, MockItemSpec('AE'))
      conn = SimpleConnection(CP('child', vpt_child), CP('parent', vpt_parent))
      call r_parent%add_connection(conn, rc=status)
      @assert_that(status, is(0))
!!$      if (.not. check(r_parent, vpt_parent, ['AE'])) return
      ! Check that extension was created
      actual_pts => r_child%get_actual_pts(vpt_child)
      @assert_that(int(actual_pts%size()), is(2))
   end subroutine test_import_from_child
Call graph
test_import_from_child calls assert_that, add_item_spec, add_connection, add_subregistry, get_actual_pts, new_v_pt
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
get_actual_pts calls at
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item_spec_actual calls mapl_assert, mapl_return, mapl_verify, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception