test_get_fptr_shape_3D – MAPL
test_get_fptr_shape_3D Subroutine
12 statements
Source File
public subroutine test_get_fptr_shape_3D()
Arguments
None
Calls
Source Code
    subroutine test_get_fptr_shape_3D()
       integer :: expected(ARRAY_RANK), actual(ARRAY_RANK)
       integer, allocatable :: gridToFieldMap(:)
       integer, allocatable :: localElementCount(:)
       logical :: has_vertical
       has_vertical = .TRUE.
       gridToFieldMap = [1, 2]
       localElementCount = [3, 5, 7]
       expected = [product(localElementCount(1:2)), localElementCount(3), 1]
       actual = get_fptr_shape(gridToFieldMap, localElementCount, has_vertical)
       @assert_that(GENERIC_MESSAGE, actual, is(equal_to(expected)))
    end subroutine test_get_fptr_shape_3D
Call graph
test_get_fptr_shape_3d calls assert_that, equal_to, get_fptr_shape
get_fptr_shape calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception