test_match_mapping_mismatch_size_2 – MAPL
test_match_mapping_mismatch_size_2 Subroutine
31 statements
Source File
public subroutine test_match_mapping_mismatch_size_2()
Arguments
None
Calls
Source Code
   subroutine test_match_mapping_mismatch_size_2()
      type(ESMF_HConfig) :: a, b
      logical :: match
      integer :: status
      a = ESMF_HConfigCreate(content='{a: 1, b: 2}', _RC)
      b = ESMF_HConfigCreate(content='{a: 1}', _RC)
      match = MAPL_HConfigMatch(b, a, _RC)
      @assert_that(match, is(false()))
      call ESMF_HConfigDestroy(a, _RC)
      call ESMF_HConfigDestroy(b, _RC)
   end subroutine test_match_mapping_mismatch_size_2
Call graph
test_match_mapping_mismatch_size_2 calls ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, false, mapl_hconfigmatch, sourcelocation
mapl_hconfigmatch calls ESMF_HConfigDestroy, ESMF_HConfigAsStringMapKey, ESMF_HConfigIterLoop, esmf_hconfigasi8, esmf_hconfigaslogical, esmf_hconfigasr8, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigisscalar, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception