test_reuse_regridder – MAPL
test_reuse_regridder Subroutine
28 statements
Source File
public subroutine test_reuse_regridder(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_reuse_regridder(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(GeomManager) :: geom_mgr
      type(RegridderManager), target :: regridder_mgr
      type(RegridderSpec) :: regridder_spec
      integer :: status
      class(Regridder), pointer :: regridder_1, regridder_2
      type(ESMF_Geom) :: geom
      geom_mgr = GeomManager()
      regridder_mgr = RegridderManager()
      geom = make_geom(geom_mgr, _RC)
      regridder_spec = RegridderSpec(EsmfRegridderParam(), geom, geom)
      regridder_1 => regridder_mgr%get_regridder(regridder_spec, _RC)
      regridder_2 => regridder_mgr%get_regridder(regridder_spec, _RC)
      @assertTrue(associated(regridder_2, regridder_1))
   end subroutine test_reuse_regridder
Call graph
test_reuse_regridder calls anyexceptions, assert_that, asserttrue, esmfregridderparam, geommanager, get_regridder, make_geom, sourcelocation
get_regridder calls find, of, add_regridder, make_regridder, mapl_return, mapl_verify, vector_back, vector_begin
make_geom calls ESMF_HConfigCreate, get_geom, get_mapl_geom
add_regridder calls vector_push_back
make_regridder calls mapl_return, mapl_verify, mapl_assert, make_regridder, of, get_param, supports
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception