test_mirror_ungridded_dims – MAPL
test_mirror_ungridded_dims Subroutine
15 statements
Source File
public subroutine test_mirror_ungridded_dims()
Arguments
None
Calls
Source Code
   subroutine test_mirror_ungridded_dims()
      type(FieldSpec) :: import_spec
      type(FieldSpec) :: export_spec
      type(ESMF_Geom) :: geom
      type(UngriddedDims) :: mirror_ungrid, export_dims
      type(UngriddedDimVector) :: ungrid_dims
      type(UngriddedDim) :: ungrid_dim
      mirror_ungrid = mirror_ungridded_dims()
      ungrid_dim = UngriddedDim(2)
      call ungrid_dims%push_back(ungrid_dim)
      export_dims = UngriddedDims(ungrid_dims)
      import_spec = FieldSpec( &
           geom=geom, vertical_grid=BasicVerticalGrid(1), vertical_dim_spec=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = mirror_ungrid, &
           standard_name='A', long_name='AA', attributes=StringVector(), &
           units='m')
      export_spec = FieldSpec( &
           geom=geom, vertical_grid=BasicVerticalGrid(1), vertical_dim_spec=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = export_dims, &
           standard_name='A', long_name='AA', attributes=StringVector(), &
           units='m')
      @assert_that(import_spec%can_connect_to(export_spec), is(true()))
   end subroutine test_mirror_ungridded_dims
Call graph
test_mirror_ungridded_dims calls assert_that, can_connect_to, push_back, mirror_ungridded_dims, stringvector, true
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception