test_internal_activation – MAPL
test_internal_activation Subroutine
17 statements
Source File
public subroutine test_internal_activation()
Arguments
None
Calls
Source Code
   subroutine test_internal_activation()
      type(HierarchicalRegistry) :: r
      class(StateItemSpec), pointer :: spec
      type(ActualConnectionPt) :: apt_1, apt_2, apt_3
           apt_1 = new_a_pt('internal', 'A')
           apt_2 = new_a_pt('export', 'A')
           apt_3 = new_a_pt('import', 'A')
        call r%add_item_spec(apt_1, MockItemSpec('A1'))
        call r%add_item_spec(apt_2, MockItemSpec('A2'))
        call r%add_item_spec(apt_3, MockItemSpec('A3'))
        spec => r%get_item_spec(apt_1)
        @assert_that(spec%is_active(), is(true()))
        spec => r%get_item_spec(apt_2)
        @assert_that(spec%is_active(), is(false()))
        spec => r%get_item_spec(apt_3)
        @assert_that(spec%is_active(), is(false()))
   end subroutine test_internal_activation
Call graph
test_internal_activation calls assert_that, false, add_item_spec, get_item_spec, is_active, new_a_pt, true
get_item_spec calls at, mapl_return, mapl_verify
new_a_pt calls new_v_pt
add_item_spec_actual calls mapl_return, mapl_verify, mapl_assert, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception