test_create_output_alarm – MAPL
test_create_output_alarm Subroutine
81 statements
Source File
public subroutine test_create_output_alarm()
Arguments
None
Calls
Source Code
   subroutine test_create_output_alarm()
      type(ESMF_HConfig) :: hconfig
      type(ESMF_Time) :: time,start_stop_time(2)
      integer :: status
      type(ESMF_Time) :: start_time, stop_time
      type(ESMF_TimeInterval) :: dt
      type(ESMF_Clock) :: clock
      type(ESMF_Alarm) :: alarm
      logical :: is_ringing
      type(ESMF_Time) currTime
      character(len=:), allocatable :: comp_name
      comp_name = "coll1"
      call ESMF_TimeIntervalSet(dt, h=1, _RC)
      call ESMF_TimeSet(start_time, timeString="2000-04-03T21:00:00", _RC)
      call ESMF_TimeSet(stop_time, timeString="2000-04-22T21:00:00", _RC)
      clock = ESMF_ClockCreate(timeStep=dt, startTime=start_time, stopTime=stop_time, _RC)
      hconfig = ESMF_HConfigCreate(content = &
        "{time_spec: {frequency: PT3H}}", _RC)
      call create_output_alarm(clock, hconfig, comp_name, _RC)
      call ESMF_ClockGetAlarm(clock, comp_name//"_write_alarm", alarm, _RC)
      call ESMF_ClockAdvance(clock, _RC)
      is_ringing = ESMF_AlarmIsRinging(alarm, _RC)
      @assert_that(is_ringing, is(false()))
      call ESMF_ClockAdvance(clock, _RC)
      is_ringing = ESMF_AlarmIsRinging(alarm, _RC)
      @assert_that(is_ringing, is(false()))
      call ESMF_ClockAdvance(clock, _RC)
      is_ringing = ESMF_AlarmIsRinging(alarm, _RC)
      @assert_that(is_ringing, is(true()))
   end subroutine test_create_output_alarm
Call graph
test_create_output_alarm calls ESMF_AlarmIsRinging, ESMF_ClockAdvance, ESMF_ClockCreate, ESMF_ClockGetAlarm, ESMF_HConfigCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, anyexceptions, assert_that, false, create_output_alarm, sourcelocation, true
create_output_alarm calls ESMF_TimeSet, ESMF_AlarmCreate, ESMF_ClockGet, ESMF_TimeGet, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfigisdefined, mapl_unpacktime, hconfig_to_esmf_timeinterval, mapl_return, mapl_verify, string_to_integer_time
hconfig_to_esmf_timeinterval calls esmf_hconfigasstring, mapl_return, mapl_verify, string_to_esmf_timeinterval
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_to_integer_time calls mapl_return
string_to_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_return, mapl_verify, mapl_assert