test_field_update_from_field_ignore_geom – MAPL
test_field_update_from_field_ignore_geom Subroutine
107 statements
Source File
public subroutine test_field_update_from_field_ignore_geom(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_field_update_from_field_ignore_geom(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_Field) :: f, f_ref
      type(ESMF_Grid) :: grid, grid_ref
      type(ESMF_Geom) :: geom, geom_ref, new_geom
      character(:), allocatable :: new_units
      integer :: status
      type(ESMF_FieldStatus_Flag) :: field_status
      real(ESMF_KIND_R8), pointer :: x8(:,:,:,:)
      type(ESMF_TypeKind_Flag) :: typekind
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      grid_ref = ESMF_GridCreateNoPeriDim(maxIndex=[7,7], name='I_AM_GROOT', _RC)
      geom_ref = ESMF_GeomCreate(grid_ref, _RC)
      f = ESMF_FieldCreate(geom, typekind=ESMF_TYPEKIND_R4, name='in', &
           ungriddedLbound=[1,1], ungriddedUbound=[ORIGINAL_NUM_LEVELS+1,3], _RC)
      f_ref = ESMF_FieldCreate(geom_ref, typekind=ESMF_TYPEKIND_R8, name='in', &
           ungriddedLbound=[1,1], ungriddedUbound=[ORIGINAL_NUM_LEVELS,3], _RC)
      call MAPL_InfoSetInternal(f, key=KEY_NUM_LEVELS, value=ORIGINAL_NUM_LEVELS+1, _RC)
      call MAPL_InfoSetInternal(f, key=KEY_VLOC, value='VERTICAL_DIM_EDGE', _RC)
      call MAPL_InfoSetInternal(f, key=KEY_UNITS, value=ORIGINAL_UNITS)
      call MAPL_InfoSetInternal(f_ref, key=KEY_NUM_LEVELS, value=ORIGINAL_NUM_LEVELS, _RC)
      call MAPL_InfoSetInternal(f_ref, key=KEY_VLOC, value='VERTICAL_DIM_EDGE', _RC)
      call MAPL_InfoSetInternal(f_ref, key=KEY_UNITS, value=REFERENCE_UNITS)
      call FieldUpdate(f, f_ref, ignore='geom', _RC)
      call ESMF_FieldGet(f, status=field_status, typekind=typekind, geom=new_geom, _RC)
      @assert_that(field_status == ESMF_FIELDSTATUS_COMPLETE, is(true()))
      @assert_that(typekind == ESMF_TYPEKIND_R8, is(true()))
      @assert_that(new_geom == geom, is(true()))
      call MAPL_InfoGetInternal(f, key=KEY_UNITS, value=new_units, _RC)
      @assertEqual(REFERENCE_UNITS, new_units)
      ! check that field shape is changed due to new num levels
      call ESMF_FieldGet(f, fArrayPtr=x8, _RC)
      @assert_that(shape(x8),is(equal_to([4,4,ORIGINAL_NUM_LEVELS,3])))
      call ESMF_FieldDestroy(f, _RC)
      call ESMF_GridDestroy(grid, _RC)
      call ESMF_GeomDestroy(geom, _RC)
      _UNUSED_DUMMY(this)
   end subroutine test_field_update_from_field_ignore_geom
Call graph
test_field_update_from_field_ignore_geom calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, assertequal, equal_to, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, fieldupdate, mapl_infogetinternal, mapl_infosetinternal, sourcelocation, true