test_merge_hconfig – MAPL
test_merge_hconfig Subroutine
70 statements
Source File
public subroutine test_merge_hconfig()
Arguments
None
Calls
Source Code
   subroutine test_merge_hconfig()
      type(ESMF_HConfig) :: hc_main, hc_1, hc_2, expected_config, merged_config
      integer :: status
      hc_main = ESMF_HConfigCreate( content=&
           '{subconfigs: [hc1.yaml, hc2.yaml]}', _RC)
      hc_1 = ESMF_HConfigCreate(content='{Collections: {foo: {template: filea}}}', _RC)
      call ESMF_HConfigFileSave(hc_1, "hc1.yaml", _RC)
      hc_2 = ESMF_HConfigCreate(content='{Collections: {bar: {template: fileb}}}', _RC)
      call ESMF_HConfigFileSave(hc_2, "hc2.yaml", _RC)
      expected_config = ESMF_HConfigCreate(content= &
          '{Collections: {foo: {template: filea}, bar: {template: fileb}}}', _RC)
      merged_config = ESMF_HConfigCreate(_RC)
      call merge_config(merged_config, hc_main, _RC)
      @assertTrue(MAPL_HConfigMatch(merged_config, expected_config))
      call ESMF_HConfigDestroy(hc_main, _RC)
      call ESMF_HConfigDestroy(hc_1, _RC)
      call ESMF_HConfigDestroy(hc_2, _RC)
      call ESMF_HConfigDestroy(expected_config, _RC)
      call ESMF_HConfigDestroy(merged_config, _RC)
   end subroutine test_merge_hconfig
Call graph
test_merge_hconfig calls ESMF_HConfigCreate, ESMF_HConfigDestroy, ESMF_HConfigFileSave, anyexceptions, assert_that, asserttrue, mapl_hconfigmatch, merge_config, sourcelocation
merge_config calls ESMF_HConfigCreate, ESMF_HConfigDestroy, merge_config, ESMF_HConfigAdd, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, ESMF_HConfigSet, esmf_hconfigasstringseq, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception