test_get_coordinate_field_simple – MAPL
test_get_coordinate_field_simple Subroutine
23 statements
Source File
public subroutine test_get_coordinate_field_simple(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_get_coordinate_field_simple(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ModelVerticalGrid) :: vgrid
      type(GriddedComponentDriver), pointer :: coupler
      type(ESMF_Field) :: vcoord
      type(ESMF_Geom) :: geom
      integer :: rc, status
      real(ESMF_KIND_R4), pointer :: a(:,:,:)
      call setup("PLE", vgrid, _RC)
      geom = make_geom(_RC)
      call vgrid%get_coordinate_field( &
           vcoord, coupler, &
           standard_name="air_pressure", &
           geom=geom, &
           typekind=ESMF_TYPEKIND_R4, &
           units="hPa", &
           vertical_dim_spec=VERTICAL_DIM_EDGE, &
           _RC)
      @assert_that(associated(coupler), is(false()))
      call ESMF_FieldGet(vcoord, fArrayPtr=a, _RC)
      @assert_that(a, every_item(is(equal_to(3.))))
      _UNUSED_DUMMY(this)
   end subroutine test_get_coordinate_field_simple
Call graph
test_get_coordinate_field_simple calls assert_that, equal_to, esmf_fieldget, every_item, false, get_coordinate_field, make_geom, mapl_verify, setup
make_geom calls mapl_verify, ESMF_HConfigCreate, get_geom, get_geom_manager, get_mapl_geom
mapl_verify calls mapl_throw_exception
setup calls make_geom, mapl_verify, create, mapl_assert, add_primary_spec, add_variant, get_primary_extension, get_spec, set_active, set_registry, make_itemspec, set_geometry