test_get_lon_range_GE – MAPL
test_get_lon_range_GE Subroutine
15 statements
Source File
public subroutine test_get_lon_range_GE()
Arguments
None
Calls
Source Code
   subroutine test_get_lon_range_GE()
      type(AxisRanges) :: ranges
      type(ESMF_HConfig) :: hconfig
      integer :: status
      hconfig = ESMF_HConfigCreate(content="{dateline: GE}", rc=status)
      @assert_that(status, is(0))
      ranges = get_lon_range(hconfig, 4, rc=status)
      @assert_that(status, is(0))
      @assert_that(ranges%center_min, is(+45._R8))
      @assert_that(ranges%center_max, is(+315._R8))
      @assert_that(ranges%corner_min, is(0._R8))
      @assert_that(ranges%corner_max, is(270._R8))
      call ESMF_HConfigDestroy(hconfig)
       call ESMF_HConfigDestroy(hconfig)
  end subroutine test_get_lon_range_GE
Call graph
test_get_lon_range_ge calls ESMF_HConfigCreate, ESMF_HConfigDestroy, assert_that, get_lon_range
get_lon_range calls get_lon_range, esmf_hconfigasr4seq, esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception