test_get_item_spec_not_found – MAPL
test_get_item_spec_not_found Subroutine
8 statements
Source File
public subroutine test_get_item_spec_not_found()
Arguments
None
Calls
Source Code
   subroutine test_get_item_spec_not_found()
      type(HierarchicalRegistry) :: r
      class(StateItemSpec), pointer :: spec
      r = HierarchicalRegistry('A')
      spec => r%get_item_spec(new_a_pt('import', 'a'))
      @assertExceptionRaised('status=1')
      @assert_that(associated(spec), is(false()))
   end subroutine test_get_item_spec_not_found
Call graph
test_get_item_spec_not_found calls assert_that, assertexceptionraised, false, get_item_spec, new_a_pt
get_item_spec calls at, mapl_return, mapl_verify
new_a_pt calls new_v_pt
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize