test_same_n_levels_do_not_reallocate – MAPL
test_same_n_levels_do_not_reallocate Subroutine
81 statements
Source File
public subroutine test_same_n_levels_do_not_reallocate(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_same_n_levels_do_not_reallocate(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_Field) :: f
      type(ESMF_Grid) :: grid
      type(ESMF_Geom) :: geom, other_geom
      integer :: status
      type(ESMF_FieldStatus_Flag) :: field_status
      real(ESMF_KIND_R4), pointer :: x(:,:,:,:)
      type(ESMF_TypeKind_Flag) :: typekind
      type(FieldDelta) :: delta
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      f = ESMF_FieldCreate(geom, typekind=ESMF_TYPEKIND_R4, name='in', &
           ungriddedLbound=[1,1], ungriddedUbound=[ORIGINAL_NUM_LEVELS+1,3], _RC)
      call MAPL_InfoSetInternal(f, key=KEY_NUM_LEVELS, value=ORIGINAL_NUM_LEVELS, _RC)
      call MAPL_InfoSetInternal(f, key=KEY_VLOC, value='VERTICAL_DIM_EDGE', _RC)
      call ESMF_FieldGet(f, fArrayPtr=x, _RC)
      x = FILL_VALUE
      delta = FieldDelta(num_levels=ORIGINAL_NUM_LEVELS)
      call delta%reallocate_field(f, _RC)
      call ESMF_FieldGet(f, status=field_status, typekind=typekind, geom=other_geom, _RC)
      @assert_that(field_status == ESMF_FIELDSTATUS_COMPLETE, is(true()))
      @assert_that(typekind == ESMF_TYPEKIND_R4, is(true()))
      @assert_that(other_geom == geom, is(true()))
      ! Check that Field data is unchanged
      call ESMF_FieldGet(f, fArrayPtr=x, _RC)
      @assert_that(all(x == FILL_VALUE), is(true()))
      call ESMF_FieldDestroy(f, _RC)
      call ESMF_GridDestroy(grid, _RC)
      call ESMF_GeomDestroy(geom, _RC)
      _UNUSED_DUMMY(this)
   end subroutine test_same_n_levels_do_not_reallocate
Call graph
test_same_n_levels_do_not_reallocate calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_infosetinternal, reallocate_field, sourcelocation, true
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception