test_propagate_geom – MAPL
test_propagate_geom Subroutine
185 statements
Source File
public subroutine test_propagate_geom(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_propagate_geom(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(GeomManager), pointer :: geom_mgr
      integer :: status
      type(ESMF_Field) :: f, f_alias, bracket(2)
      type(ESMF_FieldBundle) :: fb, fb_alias
      type(ESMF_Geom) ::  geom_1, geom_2, geom
      type(ESMF_Grid) :: grid, grid_2
      class(ExtensionTransform), allocatable :: transform
      type(ESMF_GridComp) :: coupler
      type(GriddedComponentDriver) :: driver
      geom_mgr => get_geom_manager()
      call setup(_RC)
      ! Change the geom
       call MAPL_FieldBundleSet(fb, geom=geom_2, _RC)
      ! Run
      call driver%run(phase_idx=GENERIC_COUPLER_INVALIDATE, _RC) ! probably not needed for test
      call driver%run(phase_idx=GENERIC_COUPLER_UPDATE, _RC)
      ! Check geom on f
      call MAPL_FieldGet(f, geom=geom, _RC)
      call ESMF_GeomGet(geom_2, grid=grid_2, _RC)
      call ESMF_GeomGet(geom, grid=grid, _RC)
      @assert_that(grid == grid_2, is(true()))
   contains
      subroutine setup(rc)
         integer, optional, intent(out) :: rc
         type(ESMF_HConfig) :: hconfig
         type(MaplGeom) :: mapl_geom
         type(MultiState) :: states
         integer :: status
         real(kind=ESMF_KIND_R4), pointer :: x(:,:)
         hconfig = ESMF_HConfigCreate(content="{class: latlon, im_world: 12, jm_world: 13, pole: PC, dateline: DC}", _RC)
         mapl_geom = geom_mgr%get_mapl_geom(hconfig, _RC)
         geom_1 = mapl_geom%get_geom()
         block
           type(ESMF_Info) :: info
           call ESMF_InfoGetFromHost(geom_1, info, _RC)
           call ESMF_InfoSet(info, 'name', 'geom_1', _RC)
         end block
         hconfig = ESMF_HConfigCreate(content="{class: latlon, im_world: 6, jm_world: 7, pole: PC, dateline: DC}", _RC)
         mapl_geom = geom_mgr%get_mapl_geom(hconfig, _RC)
         geom_2 = mapl_geom%get_geom()
         block
           type(ESMF_Info) :: info
           call ESMF_InfoGetFromHost(geom_2, info, _RC)
           call ESMF_InfoSet(info, 'name', 'geom_2', _RC)
         end block
         transform = TimeInterpolateTransform()
         coupler = make_coupler(transform, _RC)
         driver = GriddedComponentDriver(coupler)
         bracket(1) = MAPL_FieldCreate(geom=geom_1, typekind=ESMF_TYPEKIND_R4, _RC)
         bracket(2) = MAPL_FieldCreate(geom=geom_1, typekind=ESMF_TYPEKIND_R4, _RC)
         call ESMF_FieldGet(bracket(1), fArrayPtr=x, _RC)
         x = 1.
         call ESMF_FieldGet(bracket(2), fArrayPtr=x, _RC)
         x = 3.
         fb = MAPL_FieldBundleCreate(fieldList=bracket, _RC)
         call MAPL_FieldBundleSet(fb, geom=geom_1, interpolation_weights=[0.0, 0.5,0.5], _RC)
         block
           real, allocatable :: w(:)
           call MAPL_FieldBundleGet(fb, interpolation_weights=w, _RC)
         end block
         fb_alias = ESMF_NamedAlias(fb, name='import[1]', _RC)
         f = MAPL_FieldCreate(geom=geom_1, typekind=ESMF_TYPEKIND_R4, _RC)
         f_alias = ESMF_NamedAlias(f, name='export[1]', _RC)
         states = driver%get_states()
         call ESMF_StateAdd(states%importState, fieldBundleList=[fb_alias], _RC)
         call ESMF_StateAdd(states%exportState, fieldList=[f_alias], _RC)
         call driver%initialize(_RC)
         if (present(rc)) rc = _SUCCESS
      end subroutine setup
   end subroutine test_propagate_geom
Call graph
test_propagate_geom calls ESMF_GeomGet, ESMF_HConfigCreate, ESMF_InfoGetFromHost, ESMF_InfoSet, ESMF_NamedAlias, anyexceptions, assert_that, esmf_fieldget, esmf_stateadd, get_geom, get_geom_manager, get_mapl_geom, fieldbundlecreate, fieldbundleget, fieldbundleset, fieldget, mapl_fieldcreate, get_states, initialize, run, make_coupler, sourcelocation, true, w