test_double_mirror_units_fail – MAPL
test_double_mirror_units_fail Subroutine
7 statements
Source File
public subroutine test_double_mirror_units_fail()
Arguments
None
Calls
Source Code
   subroutine test_double_mirror_units_fail()
      type(UnitsAspect) :: import
      type(UnitsAspect) :: export
      import = UnitsAspect() ! mirror
      export = UnitsAspect() ! mirror
      @assert_that(export%can_connect_to(import), is(false()))
   end subroutine test_double_mirror_units_fail
Call graph
test_double_mirror_units_fail calls assert_that, false, can_connect_to