test_allocate – MAPL
test_allocate Subroutine
54 statements
Source File
public subroutine test_allocate()
Arguments
None
Calls
Source Code
   subroutine test_allocate()
      type(VariableSpec) :: var_spec
      type(StateItemSpec), target :: state_item_spec
      type(ESMF_FieldBundle) :: field_bundle
      integer :: status
      integer :: fieldCount
      type(AspectMap), pointer :: aspects
      type(BracketClassAspect) :: bracket_aspect
      integer, parameter :: BRACKET_SIZE = 2
      type(StateRegistry), target :: registry
      var_spec = make_VariableSpec(itemtype=MAPL_STATEITEM_BRACKET, state_intent=ESMF_STATEINTENT_EXPORT, &
           short_name='a', standard_name='A', geom=geom, units='m', bracket_size=BRACKET_SIZE, _RC)
      state_item_spec = var_spec%make_StateItemSpec(registry, vertical_grid=BasicVerticalGrid(5), _RC)
      call state_item_spec%create(_RC)
      call state_item_spec%allocate(_RC)
      aspects => state_item_spec%get_aspects()
      bracket_aspect = to_BracketClassAspect(aspects, _RC)
      field_bundle = bracket_aspect%get_payload()
      call ESMF_FieldBundleValidate(field_bundle, _RC)
      call ESMF_FieldBundleGet(field_bundle, fieldCount=fieldCount, _RC)
      @assert_that(fieldCount, is(BRACKET_SIZE))
      call bracket_aspect%destroy(_RC)
   end subroutine test_allocate
Call graph
test_allocate calls anyexceptions, assert_that, esmf_fieldbundleget, esmf_fieldbundlevalidate, to_bracketclassaspect, create, destroy, get_aspects, get_payload, make_stateitemspec, make_variablespec, sourcelocation
make_variablespec calls mapl_return