test_MAPL_invalid_name – MAPL
test_MAPL_invalid_name Subroutine
30 statements
Source File
public subroutine test_MAPL_invalid_name(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_MAPL_invalid_name(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_HConfig) :: config
      integer :: status
      type(ESMF_Time) :: t
      type(ESMF_TimeInterval) :: dt
      type(ESMF_Clock) :: clock
      call ESMF_TimeSet(t, h=0)
      call ESMF_TimeIntervalSet(dt, h=1)
      clock = ESMF_ClockCreate(dt, t)
      config = ESMF_HConfigCreate(content='{}', rc=status)
      @assert_that(status, is(0))
      associate (ss_parent => user_setservices('libsimple_parent_gridcomp'))
        parent_gc = create_grid_comp('parent', ss_parent, config, clock, rc=status)
      end associate
      @assert_that(status, is(0))
      parent_meta => get_outer_meta(parent_gc, rc=status)
      @assert_that(status, is(0))
      user_gc = parent_meta%get_gridcomp()
      associate (ss_leaf => user_setservices('libsimple_leaf_gridcomp'))
        ! Empty name
        call parent_meta%add_child('', ss_leaf, config, rc=status)
        @assertExceptionRaised('Child name <> does not conform to GEOS standards.')
        ! Illegal starting character
        call parent_meta%add_child('1A', ss_leaf, config, rc=status)
        @assertExceptionRaised('Child name <1A> does not conform to GEOS standards.')
        ! Illegal character: hyphen
        call parent_meta%add_child('A-1', ss_leaf, config, rc=status)
        @assertExceptionRaised('Child name <A-1> does not conform to GEOS standards.')
      end associate
      call ESMF_HConfigDestroy(config, rc=status)
      @assert_that(status, is(0))
   end subroutine test_MAPL_invalid_name
Call graph
test_mapl_invalid_name calls ESMF_ClockCreate, ESMF_HConfigCreate, ESMF_HConfigDestroy, ESMF_TimeIntervalSet, ESMF_TimeSet, assert_that, assertexceptionraised, create_grid_comp, get_outer_meta, user_setservices, add_child, get_gridcomp
create_grid_comp calls create_grid_comp_primary
get_outer_meta calls get_outer_meta_from_outer_gc
user_setservices calls new_dsosetservices, new_procsetservices
add_child_by_name calls add_child_by_name
create_grid_comp_primary calls ESMF_ClockCreate, get_outer_meta, ESMF_GridCompCreate, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic
get_outer_meta_from_outer_gc calls mapl_assert, mapl_usercompgetinternalstate, mapl_return