test_find_closest_simple – MAPL
test_find_closest_simple Subroutine
29 statements
Source File
public subroutine test_find_closest_simple()
Arguments
None
Calls
Source Code
   subroutine test_find_closest_simple()
      type(StateRegistry), target :: r
      type(VirtualConnectionPt) :: v_pt
      type(ExtensionFamily), pointer :: family
      type(StateItemExtension), pointer :: primary
      type(StateItemSpec) :: goal_spec
      type(StateItemExtension), pointer :: closest
      integer :: status
      r = StateRegistry('A')
      v_pt = VirtualConnectionPt(state_intent='export', short_name='E1')
      call r%add_primary_spec(v_pt, MockItemSpec(1, typekind=R8))
      family => r%get_extension_family(v_pt, _RC)
      primary => family%get_primary(_RC)
      goal_spec = MockItemSpec(2)
      closest => family%find_closest_extension(goal_spec,_RC)
      @assert_that(associated(closest, primary), is(true()))
   end subroutine test_find_closest_simple
Call graph
test_find_closest_simple calls anyexceptions, assert_that, add_primary_spec, find_closest_extension, get_extension_family, get_primary, mockitemspec, sourcelocation, true
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec