test_invalidate – MAPL
test_invalidate Subroutine
59 statements
Source File
public subroutine test_invalidate(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_invalidate(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(MeanAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      integer, parameter :: N = 4
      integer :: i
      type(ESMF_Field) :: importField
      logical :: counter_is_set = .FALSE.
      integer(kind=ESMF_KIND_I4), pointer :: fptr(:)
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call get_field(importState, importField, _RC)
      call FieldSet(importField, 1.0_R4, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call assign_fptr(acc%counter_field, fptr, _RC)
      counter_is_set = all(fptr == 0)
      @assertTrue(counter_is_set, 'Counter field is nonzero.')
      do i=1, N
         call acc%invalidate(importState, exportState, clock, _RC)
      end do
      call assign_fptr(acc%counter_field, fptr, _RC)
      counter_is_set = all(fptr == N)
      @assertTrue(counter_is_set, 'counter_scalar not equal to N')
      call destroy_objects(importState, exportState, clock, _RC)
      call ESMF_FieldDestroy(importField)
   end subroutine test_invalidate
Call graph
test_invalidate calls anyexceptions, assert_that, asserttrue, esmf_fielddestroy, assign_fptr, fieldset, initialize, invalidate, destroy_objects, get_field, initialize_objects, sourcelocation
destroy_objects calls anyexceptions, assert_that, esmf_fielddestroy, get_field, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fieldget, esmf_statedestroy
get_field calls anyexceptions, assert_that, sourcelocation, esmf_stateget
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate, create_grid