test_copy_shared_field – MAPL
test_copy_shared_field Subroutine
42 statements
Source File
public subroutine test_copy_shared_field()
Arguments
None
Calls
Source Code
   subroutine test_copy_shared_field()
      type(ESMF_Field) :: f_in, f_out
      integer :: status
      integer :: ia, ib
      f_in = ESMF_FieldEmptyCreate(name='f_in', _RC)
      f_out= ESMF_FieldEmptyCreate(name='f_out', _RC)
      call MAPL_FieldInfoSetShared(f_in, key='a', value=1, _RC)
      call MAPL_FieldInfoSetShared(f_in, key='b', value=2, _RC)
      call MAPL_FieldInfoCopyShared(f_in, f_out, _RC)
      call MAPL_FieldInfoGetShared(f_out, key='a', value=ia, _RC)
      call MAPL_FieldInfoGetShared(f_out, key='b', value=ib, _RC)
      @assert_that(ia, is(1))
      @assert_that(ib, is(2))
   end subroutine test_copy_shared_field
Call graph
test_copy_shared_field calls anyexceptions, assert_that, esmf_fieldemptycreate, mapl_fieldinfocopyshared, mapl_fieldinfogetshared, mapl_fieldinfosetshared, sourcelocation