test_get_num_levels – MAPL
test_get_num_levels Subroutine
22 statements
Source File
public subroutine test_get_num_levels()
Arguments
None
Calls
Source Code
   subroutine test_get_num_levels()
      integer :: status
      integer, parameter :: EXPECTED_NUM_LEVELS = 3
      integer :: num_levels
      integer :: i
      call safe_dealloc(bundle_info)
      allocate(bundle_info(2))
      do i=1, size(bundle_info)
         bundle_info(i) = make_esmf_info(num_levels=EXPECTED_NUM_LEVELS, _RC)
      end do
      num_levels = get_num_levels_bundle_info(bundle_info, _RC)
      @assertEqual(EXPECTED_NUM_LEVELS, num_levels, 'num_levels does not match.')
      call safe_dealloc(bundle_info)
   end subroutine test_get_num_levels
Call graph
test_get_num_levels calls anyexceptions, assert_that, assertequal, get_num_levels_bundle_info, make_esmf_info, safe_dealloc, sourcelocation
get_num_levels_bundle_info calls ESMF_InfoGet, ESMF_InfoGetCharAlloc, mapl_assert, mapl_return, mapl_verify
make_esmf_info calls anyexceptions, assert_that, sourcelocation, ESMF_InfoCreate, make_ungridded_dims_info, make_vertical_dim, make_vertical_geom
safe_dealloc calls deallocate_destroy
deallocate_destroy calls destroy_all
make_ungridded_dims_info calls anyexceptions, assert_that, sourcelocation, ESMF_InfoSet, make_dim_key
make_vertical_dim calls anyexceptions, assert_that, sourcelocation, ESMF_InfoSet
make_vertical_geom calls anyexceptions, assert_that, sourcelocation, ESMF_InfoSet
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
destroy_all calls ESMF_InfoDestroy
make_dim_key calls mapl_assert, mapl_return