test_filter_identity_3d – MAPL
test_filter_identity_3d Subroutine
25 statements
Source File
public subroutine test_filter_identity_3d(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_filter_identity_3d(this)
      class(ESMF_TestMethod), intent(inout) :: this
      integer :: status, rc
      real(ESMF_KIND_R4), pointer :: ptr3d(:,:,:)
      real(ESMF_KIND_R4), allocatable :: expected_array(:,:,:), masked_array(:,:,:)
      real(ESMF_KIND_R4) :: rval
      type(ESMF_Config) :: cf
      type(ESMF_HConfig) :: hcf
      hcf = ESMF_HConfigCreate(content='{FILTER.foo: "@+extra_2d"}', _RC)
      cf = ESMF_ConfigCreate(hconfig=hcf, _RC)
      call ESMF_FieldGet(field_3d, 0, farrayPtr=ptr3d, _RC)
      rval = 17.0
      ptr3d = rval
      allocate(expected_array(3,3,2),_STAT)
      expected_array = rval
      call MAPL_StateFilterItem(state, cf, "field_3d", masked_array, _RC)
      @assertEqual(expected_array, masked_array)
      _RETURN(_SUCCESS)
   end subroutine test_filter_identity_3d
Call graph
test_filter_identity_3d calls ESMF_ConfigCreate, ESMF_HConfigCreate, assertequal, esmf_fieldget, statefilteritem, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception