test_accumulate – MAPL
test_accumulate Subroutine
76 statements
Source File
public subroutine test_accumulate()
Arguments
None
Calls
Source Code
   subroutine test_accumulate()
      type(AccumulatorAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      type(ESMF_Field) :: update_field, import_field
      type(ESMF_Grid) :: grid
      type(ESMF_TypeKind_Flag) :: typekind
      logical :: matches_expected
      real(kind=ESMF_KIND_R4), parameter :: value_r4 = 3.0_ESMF_KIND_R4
      typekind = ESMF_TYPEKIND_R4
      call initialize_objects(importState, exportState, clock, typekind, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call get_field(importState, import_field, _RC)
      call ESMF_FieldGet(import_field, grid=grid, _RC)
      call initialize_field(update_field, typekind=typekind, grid=grid, _RC)
      call FieldSet(update_field, value_r4, _RC)
      call acc%accumulate(update_field, _RC)
      matches_expected = FieldIsConstant(acc%accumulation_field, value_r4, _RC)
      @assert_that(matches_expected, is(true()))
      call ESMF_FieldDestroy(update_field, _RC)
      typekind = ESMF_TYPEKIND_R8
      call initialize_field(update_field, typekind=typekind, grid=grid, _RC)
      call FieldSet(update_field, 3.0_ESMF_KIND_R8, _RC)
      call acc%accumulate(update_field)
      @assertExceptionRaised()
      call ESMF_FieldDestroy(update_field, _RC)
   end subroutine test_accumulate
Call graph
test_accumulate calls anyexceptions, assert_that, assertexceptionraised, esmf_fielddestroy, esmf_fieldget, fieldisconstant, fieldset, accumulate, initialize, get_field, initialize_field, initialize_objects, sourcelocation, true
get_field calls anyexceptions, assert_that, sourcelocation, esmf_stateget
initialize_field calls anyexceptions, assert_that, sourcelocation, ESMF_GridCreateNoPeriDimUfrm, ESMF_GridIsCreated, esmf_fieldcreate
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate