test_do_not_propagate_import – MAPL
test_do_not_propagate_import Subroutine
19 statements
Source File
public subroutine test_do_not_propagate_import()
Arguments
None
Calls
Source Code
   subroutine test_do_not_propagate_import()
      type(HierarchicalRegistry), target :: r_parent
      type(HierarchicalRegistry), target :: r_child, other_child
      integer :: status
      type(VirtualConnectionPt) :: c_pt, e_pt
      r_parent = HierarchicalRegistry('parent')
      r_child = HierarchicalRegistry('child')
      other_child = HierarchicalRegistry('other')
      call r_parent%add_subregistry(r_child)
      call r_parent%add_subregistry(other_child)
      c_pt = new_v_pt('import', 'T')
      e_pt = new_v_pt('export', 'T')
      call r_child%add_item_spec(c_pt, MockItemSpec('T_child'))
      call other_child%add_item_spec(e_pt, MockItemSpec('T_child'))
      call r_parent%add_connection(SimpleConnection(CP('other', e_pt), CP('child', c_pt)))
      call r_parent%propagate_unsatisfied_imports(rc=status)
      @assert_that(status, is(0))
      @assert_that(r_parent%has_item_spec(new_v_pt('import', 'T')), is(false()))
   end subroutine test_do_not_propagate_import
Call graph
test_do_not_propagate_import calls assert_that, false, add_item_spec, has_item_spec, propagate_unsatisfied_imports, add_connection, add_subregistry, new_v_pt
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return