test_make_from_hconfig – MAPL
test_make_from_hconfig Subroutine
13 statements
Source File
public subroutine test_make_from_hconfig()
Arguments
None
Calls
Source Code
   subroutine test_make_from_hconfig()
      type(ESMF_HConfig) :: hconfig
      integer :: status
      type(LatLonGeomFactory) :: factory
      class(GeomSpec), allocatable :: geom_spec
      type(ESMF_Geom) :: geom
      hconfig = ESMF_HConfigCreate(content="{im_world: 12, jm_world: 13, pole: PC, dateline: DC, nx: 1, ny: 1}", rc=status)
      @assert_that(status, is(0))
      allocate(geom_spec, source=factory%make_spec(hconfig, rc=status))
      @assert_that(status, is(0))
      geom = factory%make_geom(geom_spec, rc=status)
      @assert_that(status, is(0))
   end subroutine test_make_from_hconfig
Call graph
test_make_from_hconfig calls ESMF_HConfigCreate, assert_that, make_geom, make_spec
make_geom calls make_geom, mapl_assert, mapl_return, mapl_verify, typesafe_make_geom
make_geom_spec_from_metadata calls make_geom_spec_from_metadata, mapl_return, mapl_verify, make_latlongeomspec
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
typesafe_make_geom calls mapl_return, mapl_verify, ESMF_GeomCreate, create_basic_grid, fill_coordinates