test_get_fptr_shape_2D_ungrid – MAPL
test_get_fptr_shape_2D_ungrid Subroutine
12 statements
Source File
public subroutine test_get_fptr_shape_2D_ungrid()
Arguments
None
Calls
Source Code
    subroutine test_get_fptr_shape_2D_ungrid()
       integer :: expected(ARRAY_RANK), actual(ARRAY_RANK)
       integer, allocatable :: gridToFieldMap(:)
       integer, allocatable :: localElementCount(:)
       logical :: has_vertical
       has_vertical = .FALSE.
       gridToFieldMap = [1, 2]
       localElementCount = [3, 5, 7, 11]
       expected = [product(localElementCount(1:2)), 1, product(localElementCount(3:))]
       actual = get_fptr_shape(gridToFieldMap, localElementCount, has_vertical)
       @assert_that(GENERIC_MESSAGE, actual, is(equal_to(expected)))
    end subroutine test_get_fptr_shape_2D_ungrid
Call graph
test_get_fptr_shape_2d_ungrid calls assert_that, equal_to, get_fptr_shape
get_fptr_shape calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception