test_calculate_mean_R4 – MAPL
test_calculate_mean_R4 Subroutine
102 statements
Source File
public subroutine test_calculate_mean_R4()
Arguments
None
Calls
Source Code
   subroutine test_calculate_mean_R4()
      type(MeanAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      integer(kind=ESMF_KIND_I8), parameter :: COUNTER = 4
      real(kind=ESMF_KIND_R4), parameter :: MEAN = 4.0_R4
      logical :: matches_expected
      real(kind=ESMF_KIND_R4), pointer :: fptr(:)
      integer :: n
      logical, allocatable :: mask(:)
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call FieldSet(acc%accumulation_field, COUNTER*MEAN, _RC)
      acc%counter_scalar = COUNTER
      ! All points are not UNDEF and valid_mean .TRUE.
      acc%valid_mean = .TRUE.
      call acc%calculate_mean_R4(_RC)
      matches_expected = FieldIsConstant(acc%accumulation_field, MEAN, _RC)
      @assertTrue(matches_expected, 'accumulation_field not equal to MEAN')
      ! One point is UNDEF
      call FieldSet(acc%accumulation_field, COUNTER*MEAN, _RC)
      call assign_fptr(acc%accumulation_field, fptr, _RC)
      n = size(fptr)-1
      call set_undef(fptr(n))
      allocate(mask(size(fptr)))
      mask = .TRUE.
      mask(n) = .FALSE.
      call acc%calculate_mean_R4(_RC)
      @assertTrue(all(pack(fptr, mask) == MEAN), 'Some valid points not equal to MEAN')
      @assertTrue(undef(fptr(n)), 'mean at point was not UNDEF')
      ! valid_mean .FALSE. at one point
      acc%valid_mean = .TRUE.
      call FieldSet(acc%accumulation_field, COUNTER*MEAN, _RC)
      acc%valid_mean(n) = .FALSE.
      call acc%calculate_mean_R4(_RC)
      @assertTrue(all(pack(fptr, acc%valid_mean) == MEAN), 'Some valid points not equal to MEAN')
      @assertTrue(undef(fptr(n)), 'mean at point was not UNDEF')
      ! One point is UNDEF; valid_mean .FALSE. at one point
      acc%valid_mean = .TRUE.
      call FieldSet(acc%accumulation_field, COUNTER*MEAN, _RC)
      acc%valid_mean(n) = .FALSE.
      call assign_fptr(acc%accumulation_field, fptr, _RC)
      call set_undef(fptr(n))
      mask = (.not. undef(fptr)) .and. acc%valid_mean
      call acc%calculate_mean_R4(_RC)
      @assertTrue(all(pack(fptr, mask) == MEAN), 'Some valid points not equal to MEAN')
      @assertTrue(undef(fptr(n)), 'mean at point was not UNDEF')
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_calculate_mean_R4
Call graph
test_calculate_mean_r4 calls anyexceptions, assert_that, asserttrue, assign_fptr, fieldisconstant, fieldset, calculate_mean_r4, initialize, destroy_objects, initialize_objects, set_undef, undef, sourcelocation
destroy_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy, get_field
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate