test_parse_item_common – MAPL
test_parse_item_common Subroutine
31 statements
Source File
public subroutine test_parse_item_common()
Arguments
None
Calls
Source Code
   subroutine test_parse_item_common()
      type(ESMF_HConfig) :: hconfig
      type(ESMF_HConfigIter) :: hc_iter, hc_iter_begin, hc_iter_end
      character(len=:), allocatable :: expression, item_name, content, expected_name, expected_expression
      integer :: status
      expected_name = 'A_1'
      expected_expression = 'GC1.F1+GC2.F2'
      content = '{' // expected_name // ': {expr: ' // expected_expression // '}}'
!      content = '{A_1: {expr: GC1.F1+GC2.F2}}'
      hconfig = ESMF_HConfigCreate(content=content, _RC)
      hc_iter_begin = ESMF_HConfigIterBegin(hconfig, _RC)
      hc_iter_end = ESMF_HConfigIterEnd(hconfig, _RC)
      hc_iter = hc_iter_begin
      do while (ESMF_HConfigIterLoop(hc_iter, hc_iter_begin, hc_iter_end, rc=status))
         @assertEqual(0, status, 'Nonzero status returned.')
         call parse_item_common(hc_iter, item_name, expression)
         @assertEqual(expected_name, item_name, 'Actual item_name does not match actual item_name.')
         @assertEqual(expected_expression, expression, 'Actual expression does not match actual expression')
      end do
   end subroutine test_parse_item_common
Call graph
test_parse_item_common calls ESMF_HConfigCreate, ESMF_HConfigIterLoop, anyexceptions, assert_that, assertequal, esmf_hconfigiterbegin, esmf_hconfigiterend, parse_item_common, sourcelocation
parse_item_common calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIsMapMapVal, ESMF_HConfigIsScalarMapKey, esmf_hconfigasstring, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception