test_mirror_bracket_size – MAPL
test_mirror_bracket_size Subroutine
16 statements
Source File
public subroutine test_mirror_bracket_size()
Arguments
None
Calls
Source Code
   subroutine test_mirror_bracket_size()
      type(BracketSpec) :: spec_1, spec_2, spec_mirror
      type(ESMF_Geom) :: geom
      spec_1 = BracketSpec( &
           field_spec=FieldSpec(geom=geom, vertical_geom=VerticalGeom(), &
           vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='barn'), &
           bracket_size=1)
      spec_2 = BracketSpec( &
           field_spec=FieldSpec(geom=geom, vertical_geom=VerticalGeom(), &
           vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='barn'), &
           bracket_size=2)
      spec_mirror = BracketSpec( &
           field_spec=FieldSpec(geom=geom, vertical_geom=VerticalGeom(), &
           vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='barn'))
      @assert_that(spec_1%can_connect_to(spec_1), is(true()))
      @assert_that(spec_2%can_connect_to(spec_2), is(true()))
      @assert_that(spec_1%can_connect_to(spec_2), is(false()))
      @assert_that(spec_2%can_connect_to(spec_1), is(false()))
      @assert_that(spec_mirror%can_connect_to(spec_mirror), is(false()))
      @assert_that(spec_mirror%can_connect_to(spec_1), is(true()))
      @assert_that(spec_mirror%can_connect_to(spec_2), is(true()))
      @assert_that(spec_1%can_connect_to(spec_mirror), is(true()))
      @assert_that(spec_2%can_connect_to(spec_mirror), is(true()))
   end subroutine test_mirror_bracket_size
Call graph
test_mirror_bracket_size calls assert_that, false, can_connect_to, true
can_connect_to calls can_connect_to, mapl_return, of, can_connect_units, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception