test_wasrun_1 – MAPL
test_wasrun_1 Subroutine
15 statements
Source File
public subroutine test_wasrun_1(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_wasrun_1(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_HConfig) :: config
      integer :: status, userRC
      type(ESMF_GridComp) :: outer_gc
      config = ESMF_HConfigCreate(content='{}', rc=status)
      call setup(outer_gc, config, status)
      @assert_that('DSO problem', status, is(0))
      call ESMF_GridCompRun(outer_gc, userRC=userRC, phase=1, rc=status)
      @assert_that(status, is(0))
      @assert_that(userRC, is(0))
      @assertEqual("wasRun_A", log)
      call teardown(outer_gc, config)
      if(.false.) print*,shape(this)
   end subroutine test_wasrun_1
Call graph
test_wasrun_1 calls ESMF_GridCompRun, ESMF_HConfigCreate, assert_that, assertequal, setup, teardown
setup calls assert_that, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_gridcompsetservices, create_grid_comp, user_setservices, clear_log
teardown calls ESMF_HConfigDestroy, clear_log
create_grid_comp calls create_grid_comp_primary
user_setservices calls new_dsosetservices, new_procsetservices
create_grid_comp_primary calls ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic