test_get_expression_variables – MAPL
test_get_expression_variables Subroutine
20 statements
Source File
public subroutine test_get_expression_variables()
Arguments
None
Calls
Source Code
   subroutine test_get_expression_variables()
      type(StringVector) :: variables
      type(StringVectorIterator) :: iter
      character(len=:), allocatable :: expected(:), variable
      integer :: status, i
      i = 0
      expected = [character(len=16) :: 'GC1/F1', 'GC2/F2']
      variables = get_expression_variables('GC1.F1 + GC2.F2', _RC)
      iter = variables%begin()
      do while(iter /= variables%end())
         i = i + 1
         variable = iter%of()
         @assertEqual(expected(i), variable, 'Expected does not match actual.')
         call iter%next()
      end do
   end subroutine test_get_expression_variables
Call graph
test_get_expression_variables calls anyexceptions, assert_that, assertequal, begin, next, of, get_expression_variables, sourcelocation
get_expression_variables calls begin, next, of, mapl_return, mapl_verify, parser_variables_in_expression, replace_delimiter, push_back
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parser_variables_in_expression calls mapl_return, push_back, mapl_assert, lowcase, realnum