test_matching_ungridded_dims – MAPL
test_matching_ungridded_dims Subroutine
11 statements
Source File
public subroutine test_matching_ungridded_dims()
Arguments
None
Calls
Source Code
   subroutine test_matching_ungridded_dims()
      type(UngriddedDimsAspect) :: import, export
      type(UngriddedDims) :: ungridded_dims1, ungridded_dims2
      call ungridded_dims1%add_dim(UngriddedDim(2))
      call ungridded_dims1%add_dim(UngriddedDim(3))
      call ungridded_dims2%add_dim(UngriddedDim(2))
      call ungridded_dims2%add_dim(UngriddedDim(3))
      import = UngriddedDimsAspect(ungridded_dims1)
      export = UngriddedDimsAspect(ungridded_dims2)
      @assert_that(export%can_connect_to(import), is(true()))
   end subroutine test_matching_ungridded_dims
Call graph
test_matching_ungridded_dims calls assert_that, add_dim, can_connect_to, true
mapl_return calls at, insert, mapl_throw_exception