test_convert_doubles – MAPL
test_convert_doubles Subroutine
17 statements
Source File
public subroutine test_convert_doubles()
Arguments
None
Calls
Source Code
   subroutine test_convert_doubles()
      real(c_double), parameter :: FROM(3) = [1.0, 2.0, 3.0]
      real(c_double), parameter :: EXPECTED(3) = 1000.0 * FROM
      real(c_double) :: actual(size(EXPECTED))
      type(Converter) :: conv
      integer(ut_status) :: status
      character(len=*), parameter :: FROM_STRING = KM
      character(len=*), parameter :: TO_STRING = M
      call initialize_udunits_system(rc=status)
      @assertEqual(_SUCCESS, status, 'Failed to initialize')
      call get_converter(conv, FROM_STRING, TO_STRING, rc=status)
      @assertEqual(_SUCCESS, status, 'Failed to get converter')
      actual = conv%convert(FROM)
      @assertEqual(actual, EXPECTED, 'Actual does not equal expected.')
      call conv%free()
      call finalize_udunits_system()
   end subroutine test_convert_doubles
Call graph
test_convert_doubles calls assertequal, finalize_udunits_system, initialize_udunits_system, convert, get_converter
get_converter calls mapl_assert, is_free, mapl_return
mapl_return calls at, insert, mapl_throw_exception