test_is_generic – MAPL
test_is_generic Subroutine
45 statements
Source File
public subroutine test_is_generic(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_is_generic(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_GridComp) :: outer_gc
      type(ESMF_Clock) :: clock
      integer :: status
      type(ESMF_Info) :: info
      type(ESMF_HConfig) :: hconfig
      logical :: is_generic
      type(ESMF_Time) :: t
      type(ESMF_TimeInterval) :: dt
      call ESMF_TimeSet(t, h=0)
      call ESMF_TimeIntervalSet(dt, h=1)
      clock = ESMF_ClockCreate(dt, t)
      hconfig = ESMF_HConfigCreate(content='{}')
      outer_gc = create_grid_comp('ROOT', user_setservices('libsimple_parent_gridcomp'), hconfig, clock, _RC)
      call ESMF_InfoGetFromHost(outer_gc, info, _RC)
      call ESMF_InfoGet(info, key='MAPL/GRIDCOMP_IS_GENERIC', value=is_generic, _RC)
      @assert_that(is_generic,is(true()))
      call ESMF_HConfigDestroy(hconfig, _RC)
      call ESMF_ClockDestroy(clock, _RC)
      _UNUSED_DUMMY(this)
   end subroutine test_is_generic
Call graph
test_is_generic calls ESMF_ClockCreate, ESMF_ClockDestroy, ESMF_HConfigCreate, ESMF_HConfigDestroy, ESMF_InfoGet, ESMF_InfoGetFromHost, ESMF_TimeIntervalSet, ESMF_TimeSet, anyexceptions, assert_that, create_grid_comp, user_setservices, sourcelocation, true
create_grid_comp calls create_grid_comp_primary
user_setservices calls new_dsosetservices, new_procsetservices
create_grid_comp_primary calls ESMF_ClockCreate, ESMF_GridCompCreate, get_outer_meta, setservices_, attach_outer_meta, init_meta, mapl_return, mapl_verify, outer_name, set_is_generic