test_can_connect_accum_instantaneous – MAPL
test_can_connect_accum_instantaneous Subroutine
9 statements
Source File
public subroutine test_can_connect_accum_instantaneous()
Arguments
None
Calls
Source Code
   subroutine test_can_connect_accum_instantaneous()
      type(FrequencyAspect) :: import, export
      type(ESMF_TimeInterval) :: dt1, dt2
      call ESMF_TimeIntervalSet(dt1, s=2)
      call ESMF_TimeIntervalSet(dt2, s=3) ! not commensurate
      import = FrequencyAspect(timeStep=dt1) ! instantaneous
      export = FrequencyAspect(timeStep=dt2)
      @assert_that(export%can_connect_to(import), is(true()))
   end subroutine test_can_connect_accum_instantaneous
Call graph
test_can_connect_accum_instantaneous calls ESMF_TimeIntervalSet, assert_that, can_connect_to, true