test_make_ungridded_dim – MAPL
test_make_ungridded_dim Subroutine
17 statements
Source File
public subroutine test_make_ungridded_dim()
Arguments
None
Calls
Source Code
   subroutine test_make_ungridded_dim()
      type(UngriddedDim) :: a, b
      type(ESMF_Info) :: info
      integer :: status
      a = UngriddedDim(name='a', units='m', coordinates=[2.,3.,5.])
      info = a%make_info(_RC)
      b = make_UngriddedDim(info, _RC)
      @assert_that(a == b, is(true()))
   end subroutine test_make_ungridded_dim
Call graph
test_make_ungridded_dim calls anyexceptions, assert_that, make_info, make_ungriddeddim, sourcelocation, true
make_ungriddeddim calls mapl_infoget, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception