test_link_extension_spec – MAPL
test_link_extension_spec Subroutine
76 statements
Source File
public subroutine test_link_extension_spec()
Arguments
None
Calls
Source Code
   subroutine test_link_extension_spec()
      type(StateRegistry), target :: r
      type(VirtualConnectionPt) :: x
      integer :: status
      type(ExtensionFamily), pointer :: family
      type(StateItemExtensionPtr), pointer :: wrapper
      type(StateItemSpec), allocatable :: spec_x, spec_y
      type(StateItemSpec), pointer :: spec
      type(StateItemExtensionPtrVector) :: extensions
      type(StateItemExtension), target :: ext_x, ext_y
      type(StateItemExtension), pointer :: ext
      class(StateItemAspect), pointer :: class_aspect
      r = StateRegistry('A')
      x = VirtualConnectionPt(state_intent='import', short_name='x')
      call r%add_virtual_pt(x, _RC)
      allocate(spec_x, source=MockItemSpec(value=1))
      ext_x = StateItemExtension(spec_x)
      call r%link_extension(x, ext_x, _RC)
      @assert_that(r%num_owned_items(), is(0))
      family => r%get_extension_family(x, _RC)
      @assert_that(associated(family%get_primary()), is(false()))
      extensions = family%get_extensions()
      @assert_that(int(extensions%size()), is(1))
      wrapper => extensions%of(1)
      ext => wrapper%ptr
      spec => ext%get_spec()
      class_aspect => spec%get_aspect(CLASS_ASPECT_ID, _RC)
      select type (class_aspect)
      type is (MockAspect)
         @assert_that(class_aspect%value, is(1))
      class default
         @assert_that(1, is(0))
      end select
      allocate(spec_y, source=MockItemSpec(2))
      ext_y = StateItemExtension(spec_y)
      call r%link_extension(x, ext_y)
      @assert_that(r%num_owned_items(), is(0))
      family => r%get_extension_family(x, _RC)
      @assert_that(associated(family%get_primary()), is(false()))
      extensions = family%get_extensions()
      @assert_that(int(extensions%size()), is(2))
      wrapper => extensions%of(2)
      ext => wrapper%ptr
      spec => ext%get_spec()
      class_aspect => spec%get_aspect(CLASS_ASPECT_ID, _RC)
      select type (class_aspect)
      type is (MockAspect)
         @assert_that(class_aspect%value, is(2))
      class default
         @assert_that(1, is(0))
      end select
   end subroutine test_link_extension_spec
Call graph
test_link_extension_spec calls anyexceptions, assert_that, false, add_virtual_pt, get_aspect, get_extension_family, get_extensions, get_primary, get_spec, link_extension, num_owned_items, of, mockitemspec, sourcelocation
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec