test_make_grid_no_prototype – MAPL
test_make_grid_no_prototype Subroutine
11 statements
Source File
public subroutine test_make_grid_no_prototype()
Arguments
None
Calls
Source Code
   subroutine test_make_grid_no_prototype()
      type (GridManager) :: grid_manager
      type (ESMF_Grid) :: grid
      integer :: status
      grid = grid_manager%make_grid(config, rc=status)
      ! should have failed, but need to clean up otherwise
      if (status == 0) then
         call grid_manager%delete(grid)
      end if
      @assertExceptionRaised('label [GRID_TYPE:] not found')
      ! Check that it actually failed
      @assertFalse(0 == status, 'made a grid even though there is no prototype')
   end subroutine test_make_grid_no_prototype
Call graph
test_make_grid_no_prototype calls assertexceptionraised, assertfalse, make_grid, delete
delete calls ESMF_GridDestroy, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_grid_from_distgrid calls make_grid, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoSet, make_factory, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception