test_get_units – MAPL
test_get_units Subroutine
45 statements
Source File
public subroutine test_get_units(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_get_units(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_Field) :: field
      type(ESMF_Geom) :: geom
      type(ESMF_Grid) :: grid
      character(*), parameter :: EXPECTED_UNITS = 'km'
      character(:), allocatable :: units
      integer :: status
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      field = MAPL_FieldCreate(geom, typekind=ESMF_TYPEKIND_R4, units=EXPECTED_UNITS, _RC)
      call MAPL_FieldGet(field, units=units, _RC)
      @assertEqual(units, EXPECTED_UNITS)
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_GridDestroy(grid, _RC)
      call ESMF_GeomDestroy(geom, _RC)
   end subroutine test_get_units
Call graph
test_get_units calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, assertequal, esmf_fielddestroy, mapl_fieldcreate, mapl_fieldget, sourcelocation