test_assign – MAPL
test_assign Subroutine
11 statements
Source File
public subroutine test_assign()
Arguments
None
Calls
Source Code
   subroutine test_assign()
      type(String) :: str
      character(:), allocatable :: s
      character(8) :: s8
      str = 'abcd'
      @assert_that(str == 'abcd', is(true()))
      s = str
      @assert_that(s, is(equal_to('abcd')))
      call str%get(s8)
      @assert_that(trim(s8), is(equal_to('abcd')))
   end subroutine test_assign
Call graph
test_assign calls assert_that, equal_to, get, true