test_get_field_item – MAPL
test_get_field_item Subroutine
10 statements
Source File
public subroutine test_get_field_item()
Arguments
None
Calls
Source Code
   subroutine test_get_field_item()
      type(FieldDictionary) :: fd
      type(FieldDictionaryItem) :: item
      integer :: status
      fd = FieldDictionary(stream='{X_Y_Z: {canonical_units: m, long_name: "X Y Z"}}')
      item = fd%get_item('X_Y_Z', rc=status)
      @assert_that(status, is(0))
      @assertEqual('m', item%get_units())
      @assertEqual('X Y Z', item%get_long_name())
   end subroutine test_get_field_item
Call graph
test_get_field_item calls assert_that, assertequal, get_item, get_long_name, get_units
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception