test_vertical – MAPL
test_vertical Subroutine
29 statements
Source File
public subroutine test_vertical()
Uses
mapl3g_MultiState
Arguments
None
Calls
Source Code
   subroutine test_vertical()
      use mapl3g_MultiState
      type(FieldSpec) :: field_spec
      type(ESMF_Grid) :: grid
      type(ESMF_Geom) :: geom
      type(VerticalGeom) :: vertical_geom
      type(VerticalDimSpec) :: vertical_dim_spec
      type(ESMF_Info) :: info
      type(ESMF_State) :: state
      type(MultiState) :: multi_state
      type(ESMF_Field) :: f
      integer :: rank
      integer :: status
      type(StringVector) :: attributes
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', rc=status)
      call ESMF_InfoGetFromHost(grid, info, rc=status)
      call ESMF_InfoSet(info, '/MAPL/GEOM/VERTICAL', 'CENTER', rc=status)
      geom = ESMF_GeomCreate(grid, ESMF_STAGGERLOC_INVALID)
      vertical_dim_spec = VERTICAL_DIM_CENTER
      field_spec = FieldSpec(geom, vertical_geom, vertical_dim_spec, ESMF_TYPEKIND_R4, UngriddedDimsSpec(), &
           '', '', '', attributes)
      call field_spec%create(rc=status)
      call field_spec%allocate(rc=status)
      multi_state = MultiState(importState=ESMF_StateCreate(), exportState=ESMF_StateCreate())
      call field_spec%add_to_state(multi_state, ActualConnectionPt(VirtualConnectionPt(ESMF_STATEINTENT_EXPORT, 'T')), rc=status)
      call multi_state%get_state(state, ESMF_STATEINTENT_EXPORT, rc=status)
      call ESMF_StateGet(state, 'T', f, rc=status)
      call ESMF_FieldGet(f, rank=rank, rc=status)
      @assert_that(rank, is(3))
   end subroutine test_vertical
Call graph
test_vertical calls ESMF_GeomCreate, ESMF_GridCreateNoPeriDim, ESMF_InfoGetFromHost, ESMF_InfoSet, assert_that, esmf_fieldget, esmf_statecreate, esmf_stateget, get_state, add_to_state, create
add_to_state calls get_state, ESMF_NamedAlias, esmf_stateadd, get_comp_name, get_esmf_name, get_state_intent, get_substate, mapl_return, mapl_verify
create calls esmf_fieldemptycreate, mapl_fieldemptyset, mapl_return, mapl_verify