test_set_stateitem_private_r4_1d – MAPL
test_set_stateitem_private_r4_1d Subroutine
48 statements
Source File
public subroutine test_set_stateitem_private_r4_1d()
Arguments
None
Calls
Source Code
   subroutine test_set_stateitem_private_r4_1d()
      type(ESMF_State) :: state
      type(ESMF_Field) :: field
      integer :: status
      real(kind=ESMF_KIND_R4), allocatable :: r(:)
      real(kind=ESMF_KIND_R4), parameter :: expected(*) = [1.0, 3.0, 7.0]
      state = ESMF_StateCreate(name='import', _RC)
      call MAPL_InfoSetNameSpace(state, namespace='/compA', _RC)
      field = ESMF_FieldEmptyCreate(name='f', _RC)
      call ESMF_StateAdd(state, [field], _RC)
      call MAPL_InfoSetPrivate(state, short_name='f', key='a', values=expected, _RC)
      call MAPL_InfoGetPrivate(state, short_name='f', key='a', values=r, _RC)
      @assert_that(r, is(equal_to(expected)))
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_set_stateitem_private_r4_1d
Call graph
test_set_stateitem_private_r4_1d calls anyexceptions, assert_that, equal_to, esmf_fielddestroy, esmf_fieldemptycreate, esmf_stateadd, esmf_statecreate, esmf_statedestroy, mapl_infogetprivate, mapl_infosetnamespace, mapl_infosetprivate, sourcelocation