test_compute_linear_map – MAPL
test_compute_linear_map Subroutine
35 statements
Source File
public subroutine test_compute_linear_map()
Arguments
None
Calls
Source Code
   subroutine test_compute_linear_map()
      real(REAL32), allocatable :: vcoord_src(:), vcoord_dst(:)
      real(REAL32), allocatable :: fin(:)
      ! real(REAL32), allocatable :: matrix(:, :)
      type(SparseMatrix_sp) :: matrix
      integer :: status
      vcoord_src = [30., 20., 10.]
      vcoord_dst = [20., 10.]
      call compute_linear_map(vcoord_src, vcoord_dst, matrix, _RC)
      fin = [7., 8., 3.]
      @assertEqual([8., 3.], matmul(matrix, fin))
      vcoord_src = [30., 20., 10.]
      vcoord_dst = [25., 15.]
      call compute_linear_map(vcoord_src, vcoord_dst, matrix, _RC)
      fin = [2., 4., 6.]
      @assertEqual([3.,5.], matmul(matrix, fin))
      fin = [7., 8., 3.]
      @assertEqual([7.5, 5.5], matmul(matrix, fin))
      vcoord_src = [30., 20., 10.]
      vcoord_dst = [28., 12.]
      call compute_linear_map(vcoord_src, vcoord_dst, matrix, _RC)
      fin = [20., 10., 5.]
      @assertEqual([18., 6.], matmul(matrix, fin))
   end subroutine test_compute_linear_map
Call graph
test_compute_linear_map calls anyexceptions, assert_that, assertequal, compute_linear_map, sourcelocation
compute_linear_map calls add_row, mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception