test_get_i4_not_found_default – MAPL
test_get_i4_not_found_default Subroutine
17 statements
Source File
public subroutine test_get_i4_not_found_default()
Arguments
None
Calls
Source Code
   subroutine test_get_i4_not_found_default()
      character(len=*), parameter :: LABEL = 'inv_alpha'
      integer(kind=I4), parameter :: DEFAULT = 137
      character(len=*), parameter :: EXPECTED_VALUESTRING = '137' // DEFTAG
      integer(kind=I4) :: actual
      character(len=:), allocatable :: valuestring
      type(HConfigParams) :: params
      logical :: found
      integer :: status
      params = HConfigParams(hconfig, LABEL, check_value_set=.TRUE.)
      call get_value(params, actual, default=DEFAULT, valuestring=valuestring, rc=status)
      found = params%value_set
      @assertEqual(0, status, ERROR_GET_FAILED)
      @assertTrue(found, ERROR_NOT_FOUND // LABEL)
      @assertEqual(DEFAULT, actual, ERROR_MISMATCH)
      @assertEqual(EXPECTED_VALUESTRING, valuestring, valuestring_mismatch(valuestring, EXPECTED_VALUESTRING))
   end subroutine test_get_i4_not_found_default
Call graph
test_get_i4_not_found_default calls assertequal, asserttrue, get_value, valuestring_mismatch
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
get_value_i4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical_seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_string calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify