test_init_children – MAPL
test_init_children Subroutine
17 statements
Source File
public subroutine test_init_children(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_init_children(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_State) :: importState, exportState
      type(ESMF_Time) :: t
      type(ESMF_TimeInterval) :: dt
      type(ESMF_Clock) :: clock
      integer :: status
      call ESMF_TimeSet(t, h=0)
      call ESMF_TimeIntervalSet(dt, h=1)
      clock = ESMF_ClockCreate(dt, t)
      call setup(this, rc=status)
      @assert_that(status, is(0))
      call parent_meta%initialize_user(rc=status)
      @assert_that(status, is(0))
      @assertEqual("wasInit :: wasInit_child_1 :: wasInit_child_2", log)
      call teardown(this)
   end subroutine test_init_children
Call graph
test_init_children calls ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, assert_that, assertequal, initialize_user, setup, teardown
setup calls ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, assert_that, ESMF_HConfigCreate, ESMF_HConfigDestroy, esmf_gridcompsetservices, create_grid_comp, get_outer_meta, user_setservices, add_child, get_gridcomp, get_user_gc_driver, clear_log
teardown calls assert_that, ESMF_GridCompDestroy
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception