test_construct_converter – MAPL
test_construct_converter Subroutine
16 statements
Source File
public subroutine test_construct_converter()
Arguments
None
Calls
Source Code
   subroutine test_construct_converter()
      type(UDUnit) :: unit1
      type(UDUnit) :: unit2
      type(Converter) :: conv
      integer(ut_status) :: status
      call initialize_udunits_system(rc=status)
      @assertEqual(UT_SUCCESS, status, 'Failed to initialize')
      unit1 = UDUnit(KM)
      unit2 = UDUnit(M)
      conv = Converter(unit1, unit2)
      @assertFalse(conv%is_free(), 'cv_converter is not set')
      call unit1%free()
      call unit2%free()
      call conv%free()
      call finalize_udunits_system()
   end subroutine test_construct_converter
Call graph
test_construct_converter calls assertequal, assertfalse, finalize_udunits_system, initialize_udunits_system, is_free