test_get_standard_name_from_alias_multi – MAPL
test_get_standard_name_from_alias_multi Subroutine
15 statements
Source File
public subroutine test_get_standard_name_from_alias_multi()
Arguments
None
Calls
Source Code
   subroutine test_get_standard_name_from_alias_multi()
      type(FieldDictionary) :: fd
      character(:), allocatable :: standard_name
      integer :: status
      fd = FieldDictionary(stream = '{' // &
           'X_Y_Z: {canonical_units: m, long_name: "X Y Z", aliases: [x, y]},' //  &
           'A_B_C: {canonical_units: s, long_name: "A B C", aliases: [a, b, c]} }')
      standard_name = fd%get_standard_name('y', rc=status)
      @assert_that(status, is(0))
      @assertEqual('X_Y_Z', standard_name)
      standard_name = fd%get_standard_name('b', rc=status)
      @assert_that(status, is(0))
      @assertEqual('A_B_C', standard_name)
      standard_name = fd%get_standard_name('c', rc=status)
      @assert_that(status, is(0))
      @assertEqual('A_B_C', standard_name)
   end subroutine test_get_standard_name_from_alias_multi
Call graph
test_get_standard_name_from_alias_multi calls assert_that, assertequal, get_standard_name
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception