test_make_grid_prototype – MAPL
test_make_grid_prototype Subroutine
9 statements
Source File
public subroutine test_make_grid_prototype()
Arguments
None
Calls
Source Code
   subroutine test_make_grid_prototype()
      type (GridManager) :: grid_manager
      type (ESMF_Grid) :: grid
      integer :: status
      call grid_manager%add_prototype('grid_type_1', MockGridFactory('foo'))
      grid = grid_manager%make_grid( config, prefix='default.', rc=status)
      @assertEqual(0, status)
      call grid_manager%delete(grid)
   end subroutine test_make_grid_prototype
Call graph
test_make_grid_prototype calls assertequal, make_grid, add_prototype, delete
add_prototype calls insert
delete calls ESMF_GridDestroy, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_grid_from_distgrid calls make_grid, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoSet, make_factory, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception