test_simple – MAPL
test_simple Subroutine
9 statements
Source File
public subroutine test_simple()
Arguments
None
Calls
Source Code
   subroutine test_simple()
      type (DirPath) :: path
      character(len=:), allocatable :: full_name
      integer :: status
      call path%append('dir1')
      full_name = path%find('exist.dat', rc=status)
      @assertEqual(0, status)
      @assertEqual('dir1/exist.dat', full_name)
   end subroutine test_simple
Call graph
test_simple calls assertequal, append, find