test_initialize – MAPL
test_initialize Subroutine
50 statements
Source File
public subroutine test_initialize()
Arguments
None
Calls
Source Code
   subroutine test_initialize()
      type(AccumulatorAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      type(ESMF_Field) :: import_field
      integer :: status
      real(kind=R4), parameter :: TEST_VALUE = 1.0_R4
      real(kind=R4) :: clear_value
      logical :: equals_expected_value
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      @assert_that(acc%initialized(), is(false()))
      call get_field(importState, import_field, _RC)
      call FieldSet(import_field, TEST_VALUE, _RC)
      equals_expected_value = FieldIsConstant(import_field, TEST_VALUE, _RC)
      @assert_that(equals_expected_value, is(true()))
      call acc%initialize(importState, exportState, clock, _RC)
      @assert_that(acc%initialized(), is(true()))
      clear_value = acc%CLEAR_VALUE_R4
      equals_expected_value = FieldIsConstant(acc%accumulation_field, clear_value, _RC)
      @assert_that(equals_expected_value, is(true()))
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_initialize
Call graph
test_initialize calls anyexceptions, assert_that, false, fieldisconstant, fieldset, initialized, initialize, destroy_objects, get_field, initialize_objects, sourcelocation, true
destroy_objects calls anyexceptions, assert_that, get_field, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy
get_field calls anyexceptions, assert_that, sourcelocation, esmf_stateget
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate