test_send_terminate – MAPL
test_send_terminate Subroutine
18 statements
Source File
public subroutine test_send_terminate(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_send_terminate(this)
      class (MpiTestMethod), intent(inout) :: this
      integer :: comm
      type (MpiSocket) :: s
      class (AbstractMessage), allocatable :: message
      type (ProtocolParser), target :: parser
      comm = this%getMpiCommunicator()
      parser = ProtocolParser()
      select case (this%getProcessRank())
      case (0) ! server
         s = MpiSocket(comm, 1, parser)
         call s%receive(message)
         @assertEqual(TERMINATE_ID, message%get_type_id())
      case (1) ! client
         s = MpiSocket(comm, 0, parser)
         call s%send(TerminateMessage())
      end select
   end subroutine test_send_terminate
Call graph
test_send_terminate calls assertequal, get_type_id, getmpicommunicator, getprocessrank, receive, send
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception