test_set_state – MAPL
test_set_state Subroutine
26 statements
Source File
public subroutine test_set_state()
Arguments
None
Calls
Source Code
   subroutine test_set_state()
      type(ESMF_State) :: state
      integer :: status
      character(:), allocatable :: name
      state = ESMF_StateCreate(name='export', _RC)
      call MAPL_InfoSetShared(state, key='component', value='comp_A', _RC)
      call MAPL_InfoGetShared(state, key='component', value=name, _RC)
      @assertEqual('comp_A', name)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_set_state
Call graph
test_set_state calls anyexceptions, assert_that, assertequal, esmf_statecreate, esmf_statedestroy, mapl_infogetshared, mapl_infosetshared, sourcelocation