test_get_item_spec_found – MAPL
test_get_item_spec_found Subroutine
11 statements
Source File
public subroutine test_get_item_spec_found()
Arguments
None
Calls
Source Code
   subroutine test_get_item_spec_found()
      type(HierarchicalRegistry) :: r
      class(StateItemSpec), pointer :: spec
      type(ActualConnectionPt) :: cp
      r = HierarchicalRegistry('A')
      cp = new_a_pt('import','a')
      call r%add_item_spec(cp, MockItemSpec('A'))
      spec => r%get_item_spec(cp)
      @assert_that(associated(spec), is(true()))
      if (.not. check(r, cp, 'A')) return
   end subroutine test_get_item_spec_found
Call graph
test_get_item_spec_found calls assert_that, check, add_item_spec, get_item_spec, new_a_pt, true
check calls check_actual, check_virtual
new_a_pt calls new_v_pt
check_actual calls assert_that, get_item_spec, true, assertequal
check_virtual calls assert_that, true, check_actual, get_actual_pts, of
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception