test_get_long_name – MAPL
test_get_long_name Subroutine
12 statements
Source File
public subroutine test_get_long_name()
Arguments
None
Calls
Source Code
   subroutine test_get_long_name()
      type(FieldDictionary) :: fd
      character(:), allocatable :: long_name
      integer :: status
      fd = FieldDictionary(stream = '{' // &
           'X_Y_Z: {canonical_units: m, long_name: "X Y Z"},' //  &
           'A_B_C: {canonical_units: s, long_name: "A B C"} }')
      long_name = fd%get_long_name('A_B_C', rc=status)
      @assert_that(status, is(0))
      @assertEqual('A B C', long_name)
      long_name = fd%get_long_name('X_Y_Z', rc=status)
      @assert_that(status, is(0))
      @assertEqual('X Y Z', long_name)
   end subroutine test_get_long_name
Call graph
test_get_long_name calls assert_that, assertequal, get_long_name
get_long_name calls at, get_long_name, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
map_at_rc calls map_find
mapl_throw_exception calls initialize