test_handle_AddReadDataCollection – MAPL
test_handle_AddReadDataCollection Subroutine
25 statements
Source File
public subroutine test_handle_AddReadDataCollection()
Arguments
None
Calls
Source Code
   subroutine test_handle_AddReadDataCollection()
      type (ServerThread) :: s
      character(len=:), allocatable :: expected
      type (MockSocketLog), target :: log
      type (MockSocket) :: client_socket
      type (MockServer) :: mock_server
      integer :: i
      client_socket = MockSocket(log)
      call client_socket%add_message(AddReadDataCollectionMessage('foo'))
      call client_socket%add_message(AddReadDataCollectionMessage('bar'))
      call client_socket%add_message(TerminateMessage())
      mock_server = MockServer()
      call s%init(client_socket, mock_server)
      call s%set_rank(1)
      do i = 1,3
        call s%run()
      enddo
      expected = ""
      expected = expected // "receive<AddReadDataCollection('foo')>"
      expected = expected // " :: send<Id(001)>"
      expected = expected // " :: receive<AddReadDataCollection('bar')>"
      expected = expected // " :: send<Id(002)>"
      expected = expected // " :: receive<Terminate>"
      @assertEqual(expected, log%log)
   end subroutine test_handle_AddReadDataCollection
Call graph
test_handle_addreaddatacollection calls assertequal, add_message, init, run, set_rank
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception