test_export_to_export_connection – MAPL
test_export_to_export_connection Subroutine
15 statements
Source File
public subroutine test_export_to_export_connection()
Arguments
None
Calls
Source Code
   subroutine test_export_to_export_connection()
      type(HierarchicalRegistry) :: r
      type(HierarchicalRegistry), target :: r_A
      type(VirtualConnectionPt) :: cp_1, cp_2
      integer :: status
      r = HierarchicalRegistry('R')
      r_A = HierarchicalRegistry('A')
      call r%add_subregistry(r_A)
      cp_1 = new_v_pt('export', 'ae1')
      cp_2 = new_v_pt('export', 'ae2')
      ! True export
      call r_A%add_item_spec(cp_1, MockItemSpec('AE1'))
      ! E-to-E with rename
      call r%add_connection(ReexportConnection(CP('A',cp_1), CP('R',cp_2)), rc=status)
      @assert_that(status, is(0))
      if (.not. check(r, cp_2, ['AE1'])) return
   end subroutine test_export_to_export_connection
Call graph
test_export_to_export_connection calls assert_that, check, add_connection, add_item_spec, add_subregistry, new_v_pt
check calls check_actual, check_virtual
check_actual calls assert_that, assertequal, get_item_spec, true
check_virtual calls assert_that, check_actual, get_actual_pts, of, true
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception