test_created_fields_have_num_levels – MAPL
test_created_fields_have_num_levels Subroutine
29 statements
Source File
public subroutine test_created_fields_have_num_levels(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_created_fields_have_num_levels(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ModelVerticalGrid) :: vgrid
      integer :: rank
      integer, allocatable :: localElementCount(:)
      type(VirtualConnectionPt) :: ple_pt
      class(StateItemSpec), pointer :: spec
      type(MultiState) :: multi_state
      type(StateItemExtension), pointer :: extension
      type(ESMF_Field) :: ple
      integer :: rc, status
      call setup("PLE", vgrid, _RC)
      ple_pt = VirtualConnectionPt(state_intent='export', short_name='PLE')
      extension => r%get_primary_extension(ple_pt, _RC)
      spec => extension%get_spec()
      multi_state = MultiState()
      call spec%add_to_state(multi_state, ActualConnectionPt(ple_pt), _RC)
      call ESMF_StateGet(multi_state%exportState, itemName='PLE', field=ple, _RC)
      call ESMF_FieldGet(ple, rank=rank, _RC)
      allocate(localElementCount(rank))
      call ESMF_FieldGet(ple, localElementCount=localElementCount, _RC)
      @assert_that(localElementCount, is(equal_to([IM,JM,LM+1])))
   end subroutine test_created_fields_have_num_levels
Call graph
test_created_fields_have_num_levels calls add_to_state, assert_that, equal_to, esmf_fieldget, esmf_stateget, get_primary_extension, get_spec, mapl_verify, setup
mapl_verify calls mapl_throw_exception
setup calls get_primary_extension, get_spec, mapl_verify, create, mapl_assert, add_primary_spec, add_variant, set_active, set_registry, make_geom, make_itemspec, set_geometry