test_FieldSinR4 – MAPL
test_FieldSinR4 Subroutine
16 statements
Source File
public subroutine test_FieldSinR4(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldSinR4(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x
      real(kind=ESMF_KIND_R4), pointer :: x_ptr(:,:)
      real(kind=ESMF_KIND_R4), allocatable :: result_array(:,:)
      integer :: status, rc
      x = XR4
      call ESMF_FieldGet(x , farrayPtr = x_ptr, _RC)
      x_ptr = 2.0
      result_array = x_ptr
      result_array = sin(2.0)
      call FieldSin(x, x, _RC)
      @assertEqual(x_ptr, result_array)
   end subroutine test_FieldSinR4
Call graph
test_fieldsinr4 calls assertequal, esmf_fieldget, fieldsin, mapl_verify
fieldsin calls esmf_fieldget, mapl_verify, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef, mapl_return
mapl_verify calls mapl_throw_exception
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
getfieldsundef calls getfieldsundef_r4, getfieldsundef_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fieldshaveundef calls mapl_verify, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoIsPresent
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
are_conformable_array calls mapl_verify, fieldsareconformable, mapl_return
are_conformable_scalar calls esmf_fieldget, mapl_verify, mapl_return, fieldgetlocalelementcount
assign_fptr_r4_rank1 calls mapl_verify, mapl_return, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_verify, mapl_return, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_verify, mapl_return, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_verify, mapl_return, fieldgetcptr
get_error_message calls at, insert
getfieldsundef_r4 calls mapl_verify, mapl_assert, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoGet
getfieldsundef_r8 calls mapl_verify, mapl_assert, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoGet
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message