test_parse_ChildSpecMap_2 – MAPL
test_parse_ChildSpecMap_2 Subroutine
14 statements
Source File
public subroutine test_parse_ChildSpecMap_2()
Arguments
None
Calls
Source Code
   subroutine test_parse_ChildSpecMap_2()
      type(ESMF_HConfig), target :: config
      type(ESMF_HConfig), pointer :: config_ptr
      type(ChildSpecMap) :: expected, found
      integer :: status, rc
      config = ESMF_HConfigCreate(content='children: {' // &
           'A: {sharedObj: libA},' // &
           'B: {sharedObj: libB}}')
      config_ptr => config
      call expected%insert('A', ChildSpec(user_setservices('libA', 'setservices_')))
      call expected%insert('B', ChildSpec(user_setservices('libB', 'setservices_')))
      found = parse_children(config_ptr, _RC)
      @assert_that(found%of('A') == expected%of('A'), is(true()))
      @assert_that(found%of('B') == expected%of('B'), is(true()))
   end subroutine test_parse_ChildSpecMap_2
Call graph
test_parse_childspecmap_2 calls ESMF_HConfigCreate, assert_that, user_setservices, insert, of, mapl_verify, parse_children, true
mapl_verify calls mapl_throw_exception
parse_children calls insert, mapl_verify, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, parse_child
mapl_return calls mapl_throw_exception, at, insert
parse_child calls user_setservices, mapl_verify, esmf_hconfigisdefined, mapl_assert, mapl_return, esmf_hconfigasstring