test_field_create_vert_only – MAPL
test_field_create_vert_only Subroutine
65 statements
Source File
public subroutine test_field_create_vert_only(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_field_create_vert_only(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_Field) :: field
      type(ESMF_Geom) :: geom
      type(ESMF_Grid) :: grid
      real(kind=ESMF_KIND_R4), pointer :: farray(:, :, :)
      integer, parameter :: num_vgrid_levels = 5
      integer :: num_levels, status
      field = ESMF_FieldEmptyCreate(_RC)
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[3,2], _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      call ESMF_FieldEmptySet(field, geom, _RC)
      call MAPL_FieldEmptyComplete( &
           field, &
           typekind=ESMF_TYPEKIND_R4, &
           gridToFieldMap=[0, 0], &
           num_levels=num_vgrid_levels+1, & ! +1 since it's an edge variable
           vert_staggerloc=VERTICAL_STAGGER_EDGE, &
           _RC)
      call MAPL_FieldGet(field, num_levels=num_levels, _RC)
      @assertEqual(num_levels, num_vgrid_levels+1)
      call assign_fptr_condensed_array(field, farray, _RC)
      @assertEqual(shape(farray), [1, num_vgrid_levels+1, 1])
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_GeomDestroy(geom, _RC)
      call ESMF_GridDestroy(grid, _RC)
      _UNUSED_DUMMY(this)
   end subroutine test_field_create_vert_only
Call graph
test_field_create_vert_only calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, assertequal, esmf_fielddestroy, esmf_fieldemptycreate, esmf_fieldemptyset, assign_fptr_condensed_array, fieldget, mapl_fieldemptycomplete, sourcelocation