test_accumulate_mean_R4 – MAPL
test_accumulate_mean_R4 Subroutine
103 statements
Source File
public subroutine test_accumulate_mean_R4()
Arguments
None
Calls
Source Code
   subroutine test_accumulate_mean_R4()
      type(MeanAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      type(ESMF_Field) :: update_field
      real(kind=ESMF_KIND_R4), pointer :: upPtr(:), accPtr(:)
      real(kind=ESMF_KIND_R4), parameter :: IMPORT_VALUE = 2.0_R4
      real(kind=ESMF_KIND_R4), parameter :: UPDATE_VALUE = 3.0_R4
      real(kind=ESMF_KIND_R4) :: result_value = IMPORT_VALUE
      integer :: n
      type(ESMF_Field) :: importField
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call get_field(importState, importField, _RC)
      call FieldSet(importField, IMPORT_VALUE, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call initialize_field(update_field, typekind=ESMF_TYPEKIND_R4, _RC)
      call assign_fptr(update_field, upPtr, _RC)
      upPtr = UPDATE_VALUE
      ! accumulated not undef, update_field not undef
      call acc%accumulate_R4(update_field, _RC)
      result_value = result_value + UPDATE_VALUE
      call assign_fptr(acc%accumulation_field, accPtr, _RC)
      @assertTrue(all(accPtr == result_value), 'accumulation_field not equal to expected value.')
      ! accumulated undef at point, update_field not undef
      call assign_fptr(acc%accumulation_field, accPtr, _RC)
      n = size(accPtr) - 1
      call set_undef(accPtr(n))
      call acc%accumulate_R4(update_field, _RC)
      result_value = result_value + UPDATE_VALUE
      @assertTrue(undef(accPtr(n)), 'invalid point is not UNDEF')
      @assertTrue(all(pack(accPtr, .not. undef(accPtr)) == result_value), 'valid point not equal to expected value.')
      ! accumulated undef at point, update_field undef at point
      n = size(upPtr) - 1
      call set_undef(upPtr(n))
      call acc%accumulate_R4(update_field, _RC)
      result_value = result_value + UPDATE_VALUE
      @assertTrue(undef(accPtr(n)), 'invalid point is not UNDEF')
      ! accumulated not undef, update_field undef at point
      call FieldSet(importField, result_value, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call acc%accumulate_R4(update_field, _RC)
      result_value = result_value + UPDATE_VALUE
      @assertTrue(undef(accPtr(n)), 'invalid point is not UNDEF')
      @assertTrue(all(pack(accPtr, .not. undef(upPtr)) == result_value), 'valid point not equal to expected value.')
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_accumulate_mean_R4
Call graph
test_accumulate_mean_r4 calls anyexceptions, assert_that, asserttrue, assign_fptr, fieldset, accumulate_r4, initialize, destroy_objects, get_field, initialize_field, initialize_objects, set_undef, undef, sourcelocation