test_basic – MAPL
test_basic Subroutine
45 statements
Source File
public subroutine test_basic(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_basic(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(GeomManager), target :: geom_mgr
      type(RegridderManager) :: regridder_mgr
      type(RegridderSpec) :: regridder_spec
      integer :: status
      class(Regridder), pointer :: my_regridder
      type(ESMF_Geom) :: geom
      type(ESMF_Field) :: f1, f2
      real(kind=ESMF_KIND_R4), pointer :: x(:,:)
      geom_mgr = GeomManager()
      regridder_mgr = RegridderManager(geom_mgr)
      geom = make_geom(geom_mgr, _RC)
      ! use default esmf regrid parameters: method, zero region, etc
      regridder_spec = RegridderSpec(EsmfRegridderParam(), geom, geom)
      my_regridder => regridder_mgr%get_regridder(regridder_spec, _RC)
      f1 = make_field(geom, 'f1', value=3._ESMF_KIND_R4, _RC)
      f2 = make_field(geom, 'f2', value=0._ESMF_KIND_R4, _RC)
      call my_regridder%regrid(f1, f2, _RC)
      call ESMF_FieldGet(f2, farrayptr=x, _RC)
      @assert_that(x, every_item(is(equal_to(3._ESMF_KIND_R4))))
   end subroutine test_basic
Call graph
test_basic calls anyexceptions, assert_that, equal_to, esmf_fieldget, esmfregridderparam, every_item, geommanager, get_regridder, make_field, make_geom, regrid, sourcelocation
make_field calls anyexceptions, assert_that, esmf_fieldget, sourcelocation, mapl_fieldcreate
make_geom calls anyexceptions, assert_that, sourcelocation, ESMF_HConfigCreate, get_geom, get_mapl_geom