test_make_valuestring_logicalseq – MAPL
test_make_valuestring_logicalseq Subroutine
14 statements
Source File
public subroutine test_make_valuestring_logicalseq()
Arguments
None
Calls
Source Code
   subroutine test_make_valuestring_logicalseq()
      character(len=*), parameter :: EXPECTED = '[T, F, F' // ELLIPSIS // ']' // DEFTAG
      logical, parameter :: DEFAULT(4) = [ .TRUE., .FALSE., .FALSE., .TRUE. ]
      logical, allocatable :: value(:)
      type(HConfigParams) :: params
      integer :: status
      character(len=:), allocatable :: valuestring
      character(len=:), allocatable :: error_message
      params = HConfigParams(hconfig, 'label')
      call get_value(params, value, default=DEFAULT, valuestring=valuestring, rc=status)
      @assertEqual(0, status, ERROR_GET_FAILED)
      if(EXPECTED /= valuestring) error_message = valuestring_mismatch(valuestring, EXPECTED)
      @assertEqual(EXPECTED, valuestring, error_message)
   end subroutine test_make_valuestring_logicalseq
Call graph
test_make_valuestring_logicalseq calls assertequal, get_value, valuestring_mismatch
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
get_value_i4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical_seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_string calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify