test_cptr_wrapper – MAPL
test_cptr_wrapper Subroutine
17 statements
Source File
public subroutine test_cptr_wrapper()
Arguments
None
Calls
Source Code
   subroutine test_cptr_wrapper()
      type(UDSystem) :: wrapper
      type(c_ptr) :: cptr
      logical :: cassoc
      wrapper = UDSystem()
      cptr = wrapper%get_cptr()
      cassoc = c_associated(cptr)
      @assertTrue(cassoc, 'Did not get c_ptr')
      if(cassoc) then
         @assertFalse(wrapper%is_free(), 'c_ptr should be set.')
         call wrapper%free()
         cptr = wrapper%get_cptr()
         @assertFalse(c_associated(cptr), 'c_ptr should not be associated')
         @assertTrue(wrapper%is_free(), 'c_ptr should not be set')
      end if
      if(c_associated(cptr)) call ut_free_system(cptr)
   end subroutine test_cptr_wrapper
Call graph
test_cptr_wrapper calls assertfalse, asserttrue, ut_free_system, get_cptr, is_free