test_serialize_string – MAPL
test_serialize_string Subroutine
23 statements
Source File
public subroutine test_serialize_string()
Arguments
None
Calls
Source Code
   subroutine test_serialize_string()
      !character(len=:), allocatable :: str
      !call check(str); if (anyExceptions()) return
      call check(''); if (anyExceptions()) return
      call check('a'); if (anyExceptions()) return
      call check('ab'); if (anyExceptions()) return
      call check('abc'); if (anyExceptions()) return
      call check('abcd'); if (anyExceptions()) return
      call check('abcde'); if (anyExceptions()) return
      call check('some very long string '); if (anyExceptions()) return
   contains
      subroutine check(expected)
         character(len=*), intent(in) :: expected
         character(len=:), allocatable :: found
         call deserialize_intrinsic(serialize_intrinsic(expected),found)
         @assertEqual(expected, found)
      end subroutine check
   end subroutine test_serialize_string
Call graph
test_serialize_string calls anyexceptions, assertequal, deserialize_intrinsic, serialize_intrinsic
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
deserialize_int32_0d calls mapl_assert, mapl_return
deserialize_int32_1d calls mapl_assert, mapl_return
deserialize_int64_0d calls mapl_assert, mapl_return
deserialize_int64_1d calls mapl_assert, mapl_return
deserialize_logical_0d calls mapl_assert, mapl_return
deserialize_logical_1d calls mapl_assert, mapl_return
deserialize_real32_0d calls mapl_assert, mapl_return
deserialize_real32_1d calls mapl_assert, mapl_return
deserialize_real64_0d calls mapl_assert, mapl_return
deserialize_real64_1d calls mapl_assert, mapl_return
deserialize_string calls mapl_assert, mapl_return
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return