test_match_sequence_match – MAPL
test_match_sequence_match Subroutine
31 statements
Source File
public subroutine test_match_sequence_match()
Arguments
None
Calls
Source Code
   subroutine test_match_sequence_match()
      type(ESMF_HConfig) :: a, b
      logical :: match
      integer :: status
      a = ESMF_HConfigCreate(content='[1, 2, 0]', _RC)
      b = ESMF_HConfigCreate(content='[1, 2, 0]', _RC)
      match = MAPL_HConfigMatch(a, b, _RC)
      @assert_that(match, is(true()))
      call ESMF_HConfigDestroy(a, _RC)
      call ESMF_HConfigDestroy(b, _RC)
   end subroutine test_match_sequence_match
Call graph
test_match_sequence_match calls ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, mapl_hconfigmatch, sourcelocation, true