test_change_n_levels – MAPL
test_change_n_levels Subroutine
70 statements
Source File
public subroutine test_change_n_levels(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_change_n_levels(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_Field) :: f
      type(ESMF_Grid) :: grid
      type(ESMF_Geom) :: geom
      integer :: status
      type(ESMF_FieldStatus_Flag) :: field_status
      type(ESMF_TypeKind_Flag) :: typekind
      real(ESMF_KIND_R4), pointer :: x(:,:,:,:)
      type(FieldDelta) :: delta
      integer, parameter :: NEW_NUM_LEVELS = 7
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      f = MAPL_FieldCreate(geom, typekind=ESMF_TYPEKIND_R4, name='in', &
           ungridded_dims=UngriddedDims([3]), &
           num_levels=ORIG_VGRID_LEVELS, vert_staggerloc=VERTICAL_STAGGER_EDGE, _RC)
      call MAPL_FieldSet(f, num_levels=ORIG_VGRID_LEVELS+1, _RC)
      delta = FieldDelta(num_levels=NEW_NUM_LEVELS+1) ! edge
      call delta%reallocate_field(f, _RC)
      call ESMF_FieldGet(f, status=field_status, typekind=typekind, _RC)
      @assert_that(field_status == ESMF_FIELDSTATUS_COMPLETE, is(true()))
      @assert_that(typekind == ESMF_TYPEKIND_R4, is(true()))
      call ESMF_FieldGet(f, fArrayPtr=x, _RC)
      @assert_that(shape(x), is(equal_to([4,4,NEW_NUM_LEVELS+1,3])))
      call ESMF_FieldDestroy(f, _RC)
      call ESMF_GridDestroy(grid, _RC)
      call ESMF_GeomDestroy(geom, _RC)
      _UNUSED_DUMMY(this)
   end subroutine test_change_n_levels
Call graph
test_change_n_levels calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, equal_to, esmf_fielddestroy, esmf_fieldget, fieldset, mapl_fieldcreate, reallocate_field, sourcelocation, true
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception