test_parse_childSpec_basic – MAPL
test_parse_childSpec_basic Subroutine
11 statements
Source File
public subroutine test_parse_childSpec_basic()
Arguments
None
Calls
Source Code
   subroutine test_parse_childSpec_basic()
      type(ESMF_HConfig) :: config
      type(ChildSpec) :: found
      integer :: rc, status
      type(ChildSpec) :: expected
      config = ESMF_HConfigCreate(content='{sharedObj: libA, setServices: setservices_}')
      expected = ChildSpec(user_setservices('libA', 'setservices_'))
      found = parse_child(config, _RC)
      @assert_that(expected == found, is(true()))
   end subroutine test_parse_childSpec_basic
Call graph
test_parse_childspec_basic calls ESMF_HConfigCreate, assert_that, user_setservices, mapl_verify, parse_child, true
user_setservices calls new_dsosetservices, new_procsetservices
mapl_verify calls mapl_throw_exception
parse_child calls user_setservices, mapl_verify, esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message