test_child_call_frequency_with_offset – MAPL
test_child_call_frequency_with_offset Subroutine
102 statements
Source File
public subroutine test_child_call_frequency_with_offset()
Arguments
None
Calls
Source Code
   subroutine test_child_call_frequency_with_offset()
      type(ESMF_Time) :: t0, t1
      type(ESMF_TimeInterval) :: timeStep
      type(ESMF_Clock) :: clock
      integer :: status, user_status
      type(ESMF_HConfig) :: cap_hconfig
      type(ESMF_GridComp) :: cap_gridcomp
      type(GriddedComponentDriver) :: driver
      call ESMF_TimeSet(t0, timeString="2000-04-03T21:00:00", _RC)
      call ESMF_TimeSet(t1, timeString="2000-04-03T22:00:00", _RC)
      call ESMF_TimeIntervalSet(timestep, s=900)
      clock = ESMF_ClockCreate(timeStep=timeStep, startTime=t0, stoptime=t1, refTime=t0, _RC)
      cap_hconfig = ESMF_HConfigCreate(content='{use_default_timestep: false, use_default_runTime: false}', _RC)
      cap_gridcomp = MAPL_GridCompCreate('CAP', user_setservices(parent_ss), cap_hconfig, _RC)
      call ESMF_GridCompSetServices(cap_gridcomp, generic_setservices, userRC=user_status, _RC)
      driver = GriddedComponentDriver(cap_gridcomp, MultiState(), clock)
      call initialize_phases(driver, phases=GENERIC_INIT_PHASE_SEQUENCE, _RC)
      child_run_count = 0
      call driver%run(phase_idx=GENERIC_RUN_USER, _RC)
      call driver%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
      @assert_that(child_run_count, is(equal_to(0)))
      call driver%run(phase_idx=GENERIC_RUN_USER, _RC)
      call driver%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
      @assert_that(child_run_count, is(equal_to(1)))
      call driver%run(phase_idx=GENERIC_RUN_USER, _RC)
      call driver%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
      @assert_that(child_run_count, is(equal_to(1)))
      call driver%run(phase_idx=GENERIC_RUN_USER, _RC)
      call driver%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
      @assert_that(child_run_count, is(equal_to(2)))
      call driver%run(phase_idx=GENERIC_RUN_USER, _RC)
      call driver%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
      @assert_that(child_run_count, is(equal_to(2)))
 end subroutine test_child_call_frequency_with_offset
Call graph
test_child_call_frequency_with_offset calls ESMF_ClockCreate, ESMF_HConfigCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, anyexceptions, assert_that, equal_to, esmf_gridcompsetservices, mapl_gridcompcreate, user_setservices, run, initialize_phases, sourcelocation
initialize_phases calls initialize, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception