test_make_child_hconfig – MAPL
test_make_child_hconfig Subroutine
18 statements
Source File
public subroutine test_make_child_hconfig()
Arguments
None
Calls
Source Code
   subroutine test_make_child_hconfig()
      type(ESMF_HConfig) :: hconfig
      type(ESMF_HConfig) :: expected_child_hconfig, found_child_hconfig
      integer :: status
      hconfig = ESMF_HConfigCreate( content=&
           '{geoms: {geom1: &geom1 {class: latlon}}, collections: {c1: {geom: *geom1}}}', &
           rc=status)
      @assert_that(status, is(0))
      expected_child_hconfig = ESMF_HConfigCreate(content=&
           '{collection_name: c1, geom: {class: latlon}}', rc=status)
      @assert_that(status, is(0))
      found_child_hconfig = make_child_hconfig(hconfig, 'c1', rc=status)
      @assert_that(status, is(0))
       @assertTrue(MAPL_HConfigMatch(found_child_hconfig, expected_child_hconfig))
      call ESMF_HConfigDestroy(hconfig, rc=status)
      @assert_that(status, is(0))
      call ESMF_HConfigDestroy(expected_child_hconfig, rc=status)
      @assert_that(status, is(0))
      call ESMF_HConfigDestroy(found_child_hconfig, rc=status)
      @assert_that(status, is(0))
   end subroutine test_make_child_hconfig
Call graph
test_make_child_hconfig calls ESMF_HConfigCreate, ESMF_HConfigDestroy, assert_that, asserttrue, make_child_hconfig, mapl_hconfigmatch
make_child_hconfig calls ESMF_HConfigDestroy, ESMF_HConfigAdd, get_subconfig, mapl_return, mapl_verify
mapl_hconfigmatch calls ESMF_HConfigDestroy, ESMF_HConfigAsStringMapKey, ESMF_HConfigIterLoop, esmf_hconfigasi8, esmf_hconfigaslogical, esmf_hconfigasr8, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigisscalar, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_subconfig calls esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, mapl_assert, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception