test_get_num_nodes_2 – MAPL
test_get_num_nodes_2 Subroutine
16 statements
Source File
public subroutine test_get_num_nodes_2()
Arguments
None
Calls
Source Code
   subroutine test_get_num_nodes_2()
      type (MeterNode) :: node
      class (AbstractMeterNode), pointer :: child
      @assertEqual(1, node%get_num_nodes())
      call node%add_child('a', AdvancedMeter(MpiTimerGauge()))
      child => node%get_child('a')
      call child%add_child('1', AdvancedMeter(MpiTimerGauge()))
      call child%add_child('2', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('b', AdvancedMeter(MpiTimerGauge()))
      child => node%get_child('b')
      call child%add_child('1', AdvancedMeter(MpiTimerGauge()))
      call child%add_child('2', AdvancedMeter(MpiTimerGauge()))
      @assertEqual(7, node%get_num_nodes())
      call node%add_child('a', AdvancedMeter(MpiTimerGauge())) ! should already exist
      @assertEqual(7, node%get_num_nodes())
   end subroutine test_get_num_nodes_2
Call graph
test_get_num_nodes_2 calls assertequal, add_child, get_child, get_num_nodes
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
find_child calls at
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity