test_make_geom – MAPL
test_make_geom Subroutine
38 statements
Source File
public subroutine test_make_geom()
Arguments
None
Calls
Source Code
   subroutine test_make_geom()
      type(ESMF_HConfig) :: hconfig
      type(ESMF_Geom) :: geom
      type(ESMF_Grid) :: grid
      integer :: rank
      integer :: status
      hconfig = ESMF_HConfigCreate(content= &
         "{geom: {class: latlon, im_world: 12, jm_world: 13, pole: PC, " // &
         "dateline: DC, nx: 1, ny: 1}}", _RC)
      geom = make_geom(hconfig, _RC)
      call ESMF_GeomGet(geom, grid=grid, rank=rank, _RC)
      @assert_that(rank, is(2))
      call ESMF_HConfigDestroy(hconfig, _RC)
      call ESMF_GridDestroy(grid, nogarbage=.true., _RC)
      call ESMF_GeomDestroy(geom, _RC)
   end subroutine test_make_geom
Call graph
test_make_geom calls ESMF_GeomDestroy, ESMF_GeomGet, ESMF_GridDestroy, ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, make_geom, sourcelocation
make_geom calls ESMF_HConfigDestroy, esmf_hconfigcreateat, get_geom, get_geom_manager, get_mapl_geom, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception