test_propagate_export – MAPL
test_propagate_export Subroutine
30 statements
Source File
public subroutine test_propagate_export()
Arguments
None
Calls
Source Code
   subroutine test_propagate_export()
      type(StateRegistry), target :: r_child, r_parent
      integer :: status
      type(VirtualConnectionPt) :: v_pt, new_v_pt
      type(ExtensionFamily), pointer :: family
      r_parent = StateRegistry('parent')
      r_child = StateRegistry('child')
      call r_parent%add_subregistry(r_child)
      v_pt = VirtualConnectionPt(state_intent='export', short_name='T')
      call r_child%add_primary_spec(v_pt, MockItemSpec(4), _RC)
      call r_parent%propagate_exports(_RC)
      @assert_that(r_parent%num_owned_items(), is(0))
      @assert_that(r_parent%has_virtual_pt(v_pt), is(false()))
      new_v_pt = VirtualConnectionPt(v_pt, 'child')
      @assert_that(r_parent%has_virtual_pt(new_v_pt), is(true()))
      family => r_parent%get_extension_family(new_v_pt, _RC)
      @assert_that(associated(family%get_primary()), is(true()))
   end subroutine test_propagate_export
Call graph
test_propagate_export calls anyexceptions, assert_that, false, add_primary_spec, add_subregistry, get_extension_family, get_primary, has_virtual_pt, num_owned_items, propagate_exports, mockitemspec, sourcelocation, true
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec