test_match_scalar_mismatch – MAPL
test_match_scalar_mismatch Subroutine
31 statements
Source File
public subroutine test_match_scalar_mismatch()
Arguments
None
Calls
Source Code
   subroutine test_match_scalar_mismatch()
      type(ESMF_HConfig) :: a, b
      logical :: match
      integer :: status
      a = ESMF_HConfigCreate(content='a', _RC)
      b = ESMF_HConfigCreate(content='b', _RC)
      match = MAPL_HConfigMatch(a, b, _RC)
      @assert_that(match, is(false()))
      call ESMF_HConfigDestroy(a, _RC)
      call ESMF_HConfigDestroy(b, _RC)
   end subroutine test_match_scalar_mismatch
Call graph
test_match_scalar_mismatch calls ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, false, mapl_hconfigmatch, sourcelocation