test_sibling_activation – MAPL
test_sibling_activation Subroutine
47 statements
Source File
public subroutine test_sibling_activation(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_sibling_activation(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(HierarchicalRegistry), target :: r
      type(HierarchicalRegistry), target :: r_A, r_B, r_P, r_C
      class(StateItemSpec), pointer :: spec
      type(VirtualConnectionPt) :: vpt_1, vpt_2, vpt_4
      class(Connection), allocatable :: e2e, sib
      r = HierarchicalRegistry('R')
      r_P = HierarchicalRegistry('P')
      r_A = HierarchicalRegistry('A')
      r_B = HierarchicalRegistry('B')
      r_C = HierarchicalRegistry('C')
      call r%add_subregistry(r_P)
      call r%add_subregistry(r_B)
      call r_P%add_subregistry(r_A)
      call r_B%add_subregistry(r_C)
      vpt_1 = new_v_pt('export', 'A1')
      vpt_2 = new_v_pt('export', 'A2')
      vpt_4 = new_v_pt('import', 'A4')
      call r_A%add_item_spec(vpt_1, MockItemSpec('name:A1'))
      call r_C%add_item_spec(vpt_4, MockItemSpec('name:A4'))
        !-------------------------------------------
        !
        !                    sib*
        !          P  vpt_2   --->    vpt_4*  B
        !              ^              |
        !     e2e      |              |     i2i (implicit)
        !              |              V
        !          A  vpt_1           vpt_4  C
        !
      !-------------------------------------------
      e2e = ReexportConnection(CP('A',vpt_1), CP('P',vpt_2))
      sib = SimpleConnection(CP('P',vpt_2), CP('B', vpt_4))
      spec => r_A%get_item_spec(ActualConnectionPt(vpt_1)) ! ultimate export
      @assert_that(spec%is_active(), is(false()))
      call r_P%add_connection(e2e)
      @assert_that(spec%is_active(), is(false()))
      if (.not. check(r_P, vpt_2, ['name:A1'])) return
      call r_B%propagate_unsatisfied_imports()
      call r_P%propagate_exports()
      ! 1 => A, 2 => A, 3 => C, 4 => D
      call r%add_connection(sib)
      spec => r_A%get_item_spec(ActualConnectionPt(vpt_1))
      @assert_that(associated(spec),is(true()))
      @assert_that('vpt_1', spec%is_active(), is(true()))
      spec => r_P%get_item_spec(ActualConnectionPt(vpt_1%add_comp_name('A')))
      @assert_that(associated(spec),is(true()))
      @assert_that(spec%is_active(), is(true()))
      spec => r_P%get_item_spec(ActualConnectionPt(vpt_1%add_comp_name('A')))
      @assert_that(associated(spec),is(true()))
      @assert_that(spec%is_active(), is(true()))
      spec => r_B%get_item_spec(ActualConnectionPt(vpt_4%add_comp_name('C')))
      @assert_that(associated(spec),is(true()))
      @assert_that(spec%is_active(), is(true()))
      spec => r_C%get_item_spec(ActualConnectionPt(vpt_4))
      @assert_that(associated(spec),is(true()))
      @assert_that('vpt_4', spec%is_active(), is(true()))
   end subroutine test_sibling_activation
Call graph
test_sibling_activation calls assert_that, false, check, add_item_spec, propagate_exports, propagate_unsatisfied_imports, add_comp_name, add_connection, add_subregistry, get_item_spec, is_active, new_v_pt, true
check calls check_actual, check_virtual
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
get_item_spec calls at, mapl_return, mapl_verify