test_add_duplicate_dimension – MAPL
test_add_duplicate_dimension Subroutine
5 statements
Source File
public subroutine test_add_duplicate_dimension()
Arguments
None
Calls
Source Code
   subroutine test_add_duplicate_dimension()
      type (FileMetadata) :: cf
      call cf%add_dimension('x', 10)
      call cf%add_dimension('x', 10)
   end subroutine test_add_duplicate_dimension
Call graph
test_add_duplicate_dimension calls add_dimension
mapl_return calls insert, at, mapl_throw_exception