test_merge_hconfig_duplicate – MAPL
test_merge_hconfig_duplicate Subroutine
58 statements
Source File
public subroutine test_merge_hconfig_duplicate()
Arguments
None
Calls
Source Code
   subroutine test_merge_hconfig_duplicate()
      integer :: status
      call ESMF_HConfigAdd(hconfig_content, content=PVALUE1, addKeyString=KEY1, _RC)
      call ESMF_HConfigAdd(parent, content=hconfig_content, addKeyString=MAPLKEY, _RC)
      call ESMF_HConfigAdd(parent, content=PVALUE4, addKeyString=KEY4, _RC)
      call ESMF_HConfigAdd(parent, content=PVALUE2, addKeyString=KEY2, _RC)
      call ESMF_HConfigAdd(child, content=CHVALUE1, addKeyString=KEY1, _RC)
      call ESMF_HConfigAdd(child, content=CHVALUE2, addKeyString=KEY2, _RC)
      call ESMF_HConfigAdd(child, content=CHVALUE3, addKeyString=KEY3, _RC)
      merged = merge_hconfig(parent, child, _RC)
      call check_match(merged, KEY1, CHVALUE1, _RC)
      call check_match(merged, KEY2, CHVALUE2, _RC)
      call check_match(merged, KEY3, CHVALUE3, _RC)
   end subroutine test_merge_hconfig_duplicate
Call graph
test_merge_hconfig_duplicate calls ESMF_HConfigAdd, anyexceptions, assert_that, check_match, merge_hconfig, sourcelocation
check_match calls anyexceptions, assert_that, sourcelocation, assertequal, asserttrue, esmf_hconfigasstring
merge_hconfig calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, ESMF_HConfigSet, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception