test_serialize – MAPL
test_serialize Subroutine
30 statements
Source File
public subroutine test_serialize()
Arguments
None
Calls
Source Code
   subroutine test_serialize()
      type (Attribute) :: a
      type (Attribute) :: b
      integer,allocatable :: buffer(:)
      a = Attribute(10)
      call a%serialize(buffer)
      call Attribute_deserialize(buffer, b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = Attribute([10,20,30])
      call a%serialize(buffer)
      call Attribute_deserialize(buffer, b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = Attribute([.true.,.false.])
      call a%serialize(buffer)
      call Attribute_deserialize(buffer, b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = Attribute('abcd')
      call a%serialize(buffer)
      call Attribute_deserialize(buffer, b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = Attribute('abcdefgh')
      call a%serialize(buffer)
      call Attribute_deserialize(buffer, b)
      @assertTrue(a==b)
      deallocate(buffer)
   end subroutine test_serialize
Call graph
test_serialize calls asserttrue, serialize, attribute_deserialize
attribute_deserialize calls mapl_return, mapl_verify, unlimitedentity_deserialize
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
unlimitedentity_deserialize calls mapl_assert, serialize_buffer_length, get_rank, mapl_return, mapl_verify, deserialize_intrinsic, set