test_matched_attribute – MAPL
test_matched_attribute Subroutine
12 statements
Source File
public subroutine test_matched_attribute()
Arguments
None
Calls
Source Code
   subroutine test_matched_attribute()
      type(FieldSpec) :: import_spec
      type(FieldSpec) :: export_spec
      type(ESMF_Geom) :: geom
      type(StringVector) :: import_attributes, export_attributes
      call import_attributes%push_back('radius')
      call export_attributes%push_back('radius')
      call export_attributes%push_back('other')
      import_spec = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='m', &
           attributes=import_attributes)
      export_spec = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='m', &
           attributes=export_attributes)
      @assert_that(import_spec%can_connect_to(export_spec), is(true()))
   end subroutine test_matched_attribute
Call graph
test_matched_attribute calls assert_that, can_connect_to, push_back, true
can_connect_to calls of, can_connect_units, mapl_return, mapl_verify
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
get_error_message calls at, insert
mapl_throw_exception calls initialize