test_stress – MAPL
test_stress Subroutine
31 statements
Source File
public subroutine test_stress(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_stress(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DirectoryService) :: ds
      integer :: comm
      integer :: color, key
      type (MockServer) :: mock_server
      type (MockClient) :: mock_client
      integer :: ierror
      ds = DirectoryService(this%getMpiCommunicator())
      select case (this%getProcessRank())
      case (0:3)
         color = 0 ! client
      case (4:5) ! none
         color = 2
      case (6:7)
         color = 1 ! server
      end select
      key = 0
      call MPI_Comm_split(this%getMpiCommunicator(), color, key, comm, ierror)
      @assertEqual(0, ierror)
      select case (color)
      case (1) ! server
         mock_server = MockServer(comm)
         call ds%publish(portInfo('input', mock_server), mock_server)
         call ds%connect_to_client('input', mock_server)
      case (0) ! client
         mock_client = MockClient()
         call ds%connect_to_server('input', mock_client, comm)
      end select
      call ds%free_directory_resources()
    end subroutine test_stress
Call graph
test_stress calls assertequal, getmpicommunicator, getprocessrank, mpi_comm_split, connect_to_client, connect_to_server, free_directory_resources, publish