test_calculate_mean – MAPL
test_calculate_mean Subroutine
41 statements
Source File
public subroutine test_calculate_mean()
Arguments
None
Calls
Source Code
   subroutine test_calculate_mean()
      type(MeanAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      integer(kind=ESMF_KIND_I8), parameter :: COUNTER = 4
      real(kind=ESMF_KIND_R4), parameter :: MEAN = 4.0_R4
      logical :: matches_expected
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call FieldSet(acc%accumulation_field, COUNTER*MEAN, _RC)
      acc%counter_scalar = 0_I8
      acc%valid_mean = .TRUE.
      call acc%calculate_mean()
      @assertExceptionRaised()
      acc%counter_scalar = COUNTER
      call acc%calculate_mean()
      matches_expected = FieldIsConstant(acc%accumulation_field, MEAN, _RC)
      @assertTrue(matches_expected, 'accumulation_field not equal to MEAN.')
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_calculate_mean
Call graph
test_calculate_mean calls anyexceptions, assert_that, assertexceptionraised, asserttrue, fieldisconstant, fieldset, calculate_mean, initialize, destroy_objects, initialize_objects, sourcelocation
destroy_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy, get_field
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate