test_get_parent_orphan – MAPL
test_get_parent_orphan Subroutine
6 statements
Source File
public subroutine test_get_parent_orphan()
Arguments
None
Calls
Source Code
   subroutine test_get_parent_orphan()
      type(ConcreteComposite) :: composite
      type(MaplGenericComponent) :: component
      composite = ConcreteComposite(component)
      @assert_that(associated(composite%get_parent()), is(false()))
   end subroutine test_get_parent_orphan
Call graph
test_get_parent_orphan calls assert_that, false, get_parent