Test_MAPL_GetResource_scalar_int8 – MAPL
Test_MAPL_GetResource_scalar_int8 Subroutine
18 statements
Source File
public subroutine Test_MAPL_GetResource_scalar_int8()
Arguments
None
Calls
Source Code
   subroutine Test_MAPL_GetResource_scalar_int8()
      type(ESMF_Config) :: config
      integer :: status
      integer(kind=int64) :: expected, actual
      character(len=*), parameter :: LABEL = 'label'
      character(len=*), parameter :: VAL = '1'
      logical :: value_is_set
      config = ESMF_ConfigCreate(rc = status)
      @assertEqual(0, status, 'Failed to create ESMF_Config')
      call ESMF_ConfigSetAttribute(config, PRINT_ALL, label = 'PRINTRC:', rc = status)
      @assertEqual(0, status, 'Failed to set PRINTRC')
      call ESMF_ConfigSetAttribute(config, VAL, label = LABEL, rc = status)
      @assertEqual(0, status, 'Failed to set attribute')
      expected = 1
      call MAPL_GetResource_config_scalar(config, actual, label = LABEL, value_is_set = value_is_set, rc = status)
      @assertEqual(0, status, 'Failed to get resource')
      @assertEqual(expected, actual, 'actual does not match expected.')
   end subroutine Test_MAPL_GetResource_scalar_int8
Call graph
test_mapl_getresource_scalar_int8 calls ESMF_ConfigCreate, ESMF_ConfigSetAttribute, assertequal, mapl_getresource_config_scalar
mapl_getresource_config_scalar calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, begin, mapl_am_i_root, mapl_assert, next, of, mapl_return, mapl_verify, push_back
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception