test_find_closest_name – MAPL
test_find_closest_name Subroutine
50 statements
Source File
public subroutine test_find_closest_name()
Arguments
None
Calls
Source Code
   subroutine test_find_closest_name()
      type(StateRegistry), target :: r
      type(VirtualConnectionPt) :: v_pt
      type(ExtensionFamily), pointer :: family
      type(StateItemExtension) :: extension
      type(StateItemExtension), pointer :: primary
      type(StateItemExtension), pointer :: ext_1, ext_2
      type(StateItemSpec) :: goal_spec
      type(StateItemExtension), pointer :: closest
      integer :: status
      r = StateRegistry('A')
      v_pt = VirtualConnectionPt(state_intent='export', short_name='E1')
      call r%add_primary_spec(v_pt, MockItemSpec(3, typekind=R8, units='m'))
      extension = StateItemExtension(MockItemSpec(4,typekind=R4, units='km'))
      ext_1 => r%add_extension(v_pt, extension, _RC)
      extension = StateItemExtension(MockItemSpec(5,typekind=R4, units='m'))
      ext_2 => r%add_extension(v_pt, extension, _RC)
      family => r%get_extension_family(v_pt, _RC)
      primary => family%get_primary(_RC)
      goal_spec = MockItemSpec(4, typekind=R8)
      closest => family%find_closest_extension(goal_spec,_RC)
      @assert_that(associated(closest, primary), is(true()))
      goal_spec = MockItemSpec(5, typekind=R4, units='m')
      closest => family%find_closest_extension(goal_spec,_RC)
      @assert_that(associated(closest, ext_2), is(true()))
   end subroutine test_find_closest_name
Call graph
test_find_closest_name calls anyexceptions, assert_that, add_extension, add_primary_spec, find_closest_extension, get_extension_family, get_primary, mockitemspec, sourcelocation, true