test_alt_constructor – MAPL
test_alt_constructor Subroutine
12 statements
Source File
public subroutine test_alt_constructor()
Arguments
None
Calls
Source Code
   subroutine test_alt_constructor()
      type(VirtualConnectionPt) :: v_pt
      v_pt = VirtualConnectionPt(state_intent='import', short_name='T')
      @assertEqual('T', v_pt%get_esmf_name())
      @assertTrue(v_pt%get_state_intent() == 'import')
      v_pt = VirtualConnectionPt(state_intent='export', short_name='U')
      @assertEqual('U', v_pt%get_esmf_name())
      @assertTrue(v_pt%get_state_intent() == 'export')
      v_pt = VirtualConnectionPt(state_intent='internal', short_name='V')
      @assertEqual('V', v_pt%get_esmf_name())
      @assertTrue(v_pt%get_state_intent() == 'internal')
   end subroutine test_alt_constructor
Call graph
test_alt_constructor calls assertequal, asserttrue, get_esmf_name, get_state_intent