test_do_not_reuse_regridder – MAPL
test_do_not_reuse_regridder Subroutine
40 statements
Source File
public subroutine test_do_not_reuse_regridder(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_do_not_reuse_regridder(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(GeomManager) :: geom_mgr
      type(RegridderManager), target :: regridder_mgr
      type(RegridderSpec) :: spec_1, spec_2
      integer :: status
      class(Regridder), pointer :: regridder_1, regridder_2
      type(ESMF_Geom) :: geom_1, geom_2
      type(ESMF_HConfig) :: hconfig
      geom_mgr = GeomManager()
      regridder_mgr = RegridderManager()
      geom_1 = make_geom(geom_mgr, _RC)
      hconfig = ESMF_HConfigCreate(content="{schema: latlon, im_world: 12, jm_world: 11, pole: PC, dateline: DC, nx: 1, ny: 1}", _RC)
      geom_2 = make_geom(geom_mgr, hconfig, _RC) ! variant of geom_1
      spec_1 = RegridderSpec(EsmfRegridderParam(), geom_1, geom_1)
      regridder_1 => regridder_mgr%get_regridder(spec_1, _RC)
      spec_2 = RegridderSpec(EsmfRegridderParam(), geom_1, geom_2)
      regridder_2 => regridder_mgr%get_regridder(spec_2, _RC)
      @assertFalse(associated(regridder_1, regridder_2))
   end subroutine test_do_not_reuse_regridder
Call graph
test_do_not_reuse_regridder calls ESMF_HConfigCreate, anyexceptions, assert_that, assertfalse, esmfregridderparam, geommanager, get_regridder, make_geom, sourcelocation
get_regridder calls find, of, add_regridder, make_regridder, mapl_return, mapl_verify, vector_back, vector_begin
make_geom calls ESMF_HConfigCreate, get_geom, get_mapl_geom
add_regridder calls vector_push_back
make_regridder calls mapl_return, mapl_verify, mapl_assert, make_regridder, of, get_param, supports
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception