test_add_extension_spec – MAPL
test_add_extension_spec Subroutine
62 statements
Source File
public subroutine test_add_extension_spec()
Arguments
None
Calls
Source Code
   subroutine test_add_extension_spec()
      type(StateRegistry), target :: r
      type(VirtualConnectionPt) :: x
      integer :: status
      type(ExtensionFamily), pointer :: family
      type(StateItemExtensionPtr), pointer :: wrapper
      type(StateItemSpec), pointer :: spec
      type(StateItemExtension), pointer :: extension
      type(StateItemExtensionPtrVector) :: extensions
      class(StateItemAspect), pointer :: class_aspect
      r = StateRegistry('A')
      x = VirtualConnectionPt(state_intent='import', short_name='x')
      call r%add_virtual_pt(x, _RC)
      call r%add_spec(x, MockItemSpec(value=1), _RC)
      @assert_that(r%num_owned_items(), is(1))
      family => r%get_extension_family(x, _RC)
      @assert_that(associated(family), is(true()))
      @assert_that(family%has_primary(), is(false()))
      extensions = family%get_extensions()
      @assert_that(int(extensions%size()), is(1))
      wrapper => extensions%of(1)
      extension => wrapper%ptr
      spec => extension%get_spec()
      class_aspect => spec%get_aspect(CLASS_ASPECT_ID)
      select type (class_aspect)
      type is (MockAspect)
         @assert_that(class_aspect%value, is(1))
      class default
         @assert_that(1, is(0))
      end select
      call r%add_spec(x, MockItemSpec(value=2), _RC)
      @assert_that(r%num_owned_items(), is(2))
      @assert_that(family%has_primary(), is(false()))
      extensions = family%get_extensions()
      @assert_that(int(extensions%size()), is(2))
      wrapper => extensions%of(2)
      extension => wrapper%ptr
      spec => extension%get_spec()
      class_aspect => spec%get_aspect(CLASS_ASPECT_ID)
      select type (class_aspect)
      type is (MockAspect)
         @assert_that(class_aspect%value, is(2))
      class default
         @assert_that(1, is(0))
      end select
   end subroutine test_add_extension_spec
Call graph
test_add_extension_spec calls anyexceptions, assert_that, false, add_spec, add_virtual_pt, get_aspect, get_extension_family, get_extensions, get_spec, has_primary, num_owned_items, of, mockitemspec, sourcelocation, true
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec