test_get_subregistry_fail_not_found – MAPL
test_get_subregistry_fail_not_found Subroutine
13 statements
Source File
public subroutine test_get_subregistry_fail_not_found()
Arguments
None
Calls
Source Code
   subroutine test_get_subregistry_fail_not_found()
      type(HierarchicalRegistry), target :: child_registry
      type(HierarchicalRegistry), target :: r
      class(AbstractRegistry), pointer :: ptr
      integer :: status
      child_registry = HierarchicalRegistry('A')
      r = HierarchicalRegistry('parent')
      call r%add_subregistry(child_registry)
      ptr => r%get_subregistry('B', rc=status)
      @assertExceptionRaised('status=1')
      @assert_that(status, is(not(0)))
      @assert_that(associated(ptr), is(false()))
   end subroutine test_get_subregistry_fail_not_found
Call graph
test_get_subregistry_fail_not_found calls assert_that, assertexceptionraised, false, get_subregistry, add_subregistry
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_subregistry_comp calls mapl_assert, get_name, mapl_return, at, mapl_verify
get_subregistry_conn calls get_subregistry, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception