test_parse_timespec – MAPL
test_parse_timespec Subroutine
39 statements
Source File
public subroutine test_parse_timespec()
Arguments
None
Calls
Source Code
   subroutine test_parse_timespec()
      type(ESMF_TimeInterval) :: expected_duration
      type(ESMF_TimeInterval) :: expected_offset
      character(len=*), parameter :: ISO_DURATION = 'P3M'
      character(len=*), parameter :: ISO_OFFSET = 'P1D'
      character(len=*), parameter :: NL = new_line('10')
      character(len=:), allocatable :: content
      type(ESMF_HConfig) :: hconfig
      type(ESMF_TimeInterval), allocatable :: actual_duration
      type(ESMF_TimeInterval), allocatable :: actual_offset
      integer :: expected_mm
      integer :: rc, status
      ! Test with correct key for timestep
      call ESMF_TimeIntervalSet(expected_duration, mm=3, _RC)
      call ESMF_TimeIntervalSet(expected_offset, d=1, _RC)
      content = 'timestep: ' // ISO_DURATION // NL // 'run_time_offset: ' // ISO_OFFSET
      hconfig = ESMF_HConfigCreate(content=content, _RC)
      call parse_timespec(hconfig, actual_duration, actual_offset, _RC)
      @assert_that(allocated(actual_duration), is(true()))
      @assertTrue(actual_duration == expected_duration, MAKE_MESSAGE('timestep'))
      @assertTrue(actual_offset == expected_offset, MAKE_MESSAGE('reference time offset'))
      call ESMF_HConfigDestroy(hconfig, _RC)
      ! Test with incorrect key for timestep; should return without allocating actual_duration (invalid)
      expected_mm = 1
      call ESMF_TimeIntervalSet(actual_duration, mm=expected_mm, _RC)
      content = 'run_dmc: ' // ISO_DURATION
      hconfig = ESMF_HConfigCreate(content=content, _RC)
      call parse_timespec(hconfig, actual_duration, actual_offset, _RC)
      @assert_that(allocated(actual_duration), is(false()))
      @assert_that(allocated(actual_offset), is(false()))
      call ESMF_HConfigDestroy(hconfig, _RC)
   end subroutine test_parse_timespec
Call graph
test_parse_timespec calls ESMF_HConfigCreate, ESMF_HConfigDestroy, ESMF_TimeIntervalSet, assert_that, asserttrue, false, parse_timespec, mapl_verify, true
mapl_verify calls mapl_throw_exception