test_get_item – MAPL
test_get_item Subroutine
15 statements
Source File
public subroutine test_get_item()
Uses
mapl3g_StateItemSpecMap
Arguments
None
Calls
Source Code
   subroutine test_get_item()
      use mapl3g_stateitemspecmap
      type(StateSpec) :: state_spec
      class(StateItemSpec), pointer :: item_spec
      type(FieldSpec) :: field_spec
      type(ESMF_Geom) :: geom
      type(BasicVerticalGrid) :: vertical_grid
      type(VerticalDimSpec) :: vertical_dim_spec
      field_spec = FieldSpec(geom=geom, vertical_grid=vertical_grid, vertical_dim_spec=vertical_dim_spec, &
           typekind=ESMF_TYPEKIND_R4, ungridded_dims=UngriddedDims())
      call state_spec%add_item('A', field_spec)
      ! Different name/key
      item_spec => state_spec%get_item('B')
      @assert_that(associated(item_spec), is(false()))
      ! Same name/key
      item_spec => state_spec%get_item('A')
      @assert_that(associated(item_spec), is(true()))
   end subroutine test_get_item
Call graph
test_get_item calls assert_that, false, add_item, get_item, true