test_get_coordinate_data – MAPL
test_get_coordinate_data Subroutine
19 statements
Source File
public subroutine test_get_coordinate_data()
Arguments
None
Calls
Source Code
   subroutine test_get_coordinate_data()
      type (Variable) :: var
      type (CoordinateVariable) :: cvar
      class(*), pointer :: c32(:),c64(:)
      var  = Variable(type=pFIO_INT32)
      cvar = CoordinateVariable(var, [1.0_real32, 10.0_real32])
      c32 => cvar%get_coordinate_data()
      select type (c32)
      type is (real(real32))
         @assertEqual(c32, [1.0_real32, 10.0_real32])
      end select
      var  = Variable(type=pFIO_INT32)
      cvar = CoordinateVariable(var, [1.0_real64, 10.0_real64])
      c64 => cvar%get_coordinate_data()
      select type (c64)
      type is (real(real64))
        @assertEqual(c64, [1.0_real64, 10.0_real64])
      end select
   end subroutine test_get_coordinate_data
Call graph
test_get_coordinate_data calls assertequal, get_coordinate_data
mapl_return calls at, insert, mapl_throw_exception