test_add_primary_spec – MAPL
test_add_primary_spec Subroutine
32 statements
Source File
public subroutine test_add_primary_spec()
Arguments
None
Calls
Source Code
   subroutine test_add_primary_spec()
      type(StateRegistry), target :: r
      type(VirtualConnectionPt) :: x
      integer :: status
      type(ExtensionFamily), pointer :: family
      type(StateItemExtension), pointer :: primary
      type(StateItemSpec), pointer :: spec
      class(StateItemAspect), pointer :: class_aspect
      r = StateRegistry('A')
      x = VirtualConnectionPt(state_intent='import', short_name='x')
      call r%add_primary_spec(x, MockItemSpec(1), _RC)
      @assert_that(r%num_owned_items(), is(1))
      family => r%get_extension_family(x, _RC)
      primary => family%get_primary()
      @assert_that(associated(primary), is(true()))
      spec => primary%get_spec()
      class_aspect => spec%get_aspect(CLASS_ASPECT_ID)
      select type (class_aspect)
      type is (MockAspect)
         @assert_that(class_aspect%value, is(1))
      class default
         @assert_that(1, is(0))
      end select
   end subroutine test_add_primary_spec
Call graph
test_add_primary_spec calls anyexceptions, assert_that, add_primary_spec, get_aspect, get_extension_family, get_primary, get_spec, num_owned_items, mockitemspec, sourcelocation, true
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec