test_convert_float – MAPL
test_convert_float Subroutine
17 statements
Source File
public subroutine test_convert_float()
Arguments
None
Calls
Source Code
   subroutine test_convert_float()
      real(c_float), parameter :: FROM = 1.0
      real(c_float), parameter :: EXPECTED = 1000.0
      real(c_float) :: actual
      type(Converter) :: conv
      integer(ut_status) :: status
      character(len=*), parameter :: FROM_STRING = KM
      character(len=*), parameter :: TO_STRING = M
      call initialize_udunits_system(rc=status)
      @assertEqual(_SUCCESS, status, 'Failed to initialize')
      call get_converter(conv, FROM_STRING, TO_STRING, rc=status)
      @assertEqual(_SUCCESS, status, 'Failed to get converter')
      actual = conv%convert(FROM)
      @assertEqual(actual, EXPECTED, 'Actual does not equal expected.')
      call conv%free()
      call finalize_udunits_system()
   end subroutine test_convert_float
Call graph
test_convert_float calls assertequal, finalize_udunits_system, initialize_udunits_system, convert, get_converter
get_converter calls mapl_assert, is_free, mapl_return
mapl_return calls at, insert, mapl_throw_exception