test_propagate_imports – MAPL
test_propagate_imports Subroutine
11 statements
Source File
public subroutine test_propagate_imports(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_propagate_imports(this)
      class(MpiTestMethod), intent(inout) :: this
      integer :: status
      type(ESMF_GridComp) :: outer_gc
      type(ESMF_Field) :: f
      type(MultiState) :: states
      call setup(outer_gc, states, status)
      @assert_that(status, is(0))
      ! Child A import is unsatisfied, so it should propagate up
      call ESMF_StateGet(states%importState, 'child_A/I_A1', f, rc=status)
      @assert_that('Expected unsatisfied import in parent.', status, is(0))
   end subroutine test_propagate_imports
Call graph
test_propagate_imports calls assert_that, esmf_stateget, setup
setup calls assert_that, ESMF_ClockCreate, ESMF_GridCompInitialize, ESMF_GridCreateNoPeriDim, ESMF_HConfigCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, NUOPC_FieldDictionarySetup, anyexceptions, esmf_gridcompsetservices, esmf_statecreate, generic_init_phase_sequence, create_grid_comp, user_setservices, mapl_gridcompsetgeom, mapl_gridcompsetverticalgeom, sourcelocation
mapl_gridcompsetverticalgeom calls mapl_gridcompgetoutermeta, set_vertical_geom, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception