test_read_xml_nopath – MAPL
test_read_xml_nopath Subroutine
13 statements
Source File
public subroutine test_read_xml_nopath()
Arguments
None
Calls
Source Code
   subroutine test_read_xml_nopath()
      integer :: status
      type(c_ptr) :: utsystem
      call read_xml(utsystem=utsystem, status=status)
      if(.not. c_associated(utsystem)) then
         @assertFalse(status == UT_OS, 'Operating system error')
         @assertFalse(status == UT_PARSE_ERROR, 'Database file could not be parsed.')
         @assertFalse(status == UT_OPEN_ARG, 'Non-null path could not be opened.')
         @assertFalse(status == UT_OPEN_ENV, 'Environment variable is set but could not open.')
         @assertFalse(status == UT_OPEN_DEFAULT, 'Default database could not be opened.')
      end if
      call ut_free_system(utsystem)
   end subroutine test_read_xml_nopath
Call graph
test_read_xml_nopath calls assertfalse, ut_free_system, read_xml
read_xml calls ut_get_status, ut_read_xml_cptr, cstring