test_parse_childSpec_with_config_file – MAPL
test_parse_childSpec_with_config_file Subroutine
25 statements
Source File
public subroutine test_parse_childSpec_with_config_file()
Arguments
None
Calls
Source Code
   subroutine test_parse_childSpec_with_config_file()
      type(ESMF_HConfig) :: hconfig, child_hconfig
      character(*), parameter :: CHILD_HCONFIG_CONTENT = '{a: 8}'
      type(ChildSpec) :: found
      integer :: status, rc
      class(AbstractUserSetServices), allocatable :: ss
      type(ChildSpec) :: expected
      integer :: unit
      open(newunit=unit,file='a.yml',form='formatted', status='unknown')
      write(unit,'(a)')CHILD_HCONFIG_CONTENT
      close(unit)
      hconfig = ESMF_HConfigCreate(content='{setServices: setservices_, sharedObj: libA, config_file: a.yml}')
      child_hconfig = ESMF_HConfigCreate(content=CHILD_HCONFIG_CONTENT)
      ss = user_setservices('libA', 'setservices_')
      expected = ChildSpec(ss, hconfig=child_hconfig)
      found = parse_child(hconfig, _RC)
      @assert_that(expected == found, is(true()))
      open(newunit=unit,file='a.yml',form='formatted', status='unknown')
      close(unit,status='delete')
      call ESMF_HConfigDestroy(hconfig, _RC)
      call ESMF_HConfigDestroy(child_hconfig, _RC)
   end subroutine test_parse_childSpec_with_config_file
Call graph
test_parse_childspec_with_config_file calls ESMF_HConfigCreate, ESMF_HConfigDestroy, assert_that, parse_child, user_setservices, mapl_verify, true
mapl_verify calls mapl_throw_exception