test_link_extension – MAPL
test_link_extension Subroutine
20 statements
Source File
public subroutine test_link_extension()
Arguments
None
Calls
Source Code
   subroutine test_link_extension()
      type(StateRegistry), target :: r
      type(VirtualConnectionPt) :: x
      integer :: status
      type(StateItemExtension), target :: extension
      r = StateRegistry('A')
      x = VirtualConnectionPt(state_intent='import', short_name='x')
      call r%add_virtual_pt(x, _RC)
      extension = StateItemExtension(MockItemSpec(value=11))
      call r%link_extension(x, extension, _RC)
      @assert_that(r%num_owned_items(), is(0))
   end subroutine test_link_extension
Call graph
test_link_extension calls anyexceptions, assert_that, add_virtual_pt, link_extension, num_owned_items, mockitemspec, sourcelocation
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec
make_variablespec calls mapl_return
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception