test_mirror_geom – MAPL
test_mirror_geom Subroutine
7 statements
Source File
public subroutine test_mirror_geom()
Arguments
None
Calls
Source Code
   subroutine test_mirror_geom()
      type(FieldSpec) :: import_spec
      type(FieldSpec) :: export_spec
      import_spec = FieldSpec( &
           vertical_grid=BasicVerticalGrid(1), vertical_dim_spec=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDims(), &
           standard_name='A', long_name='AA', attributes=StringVector())
      export_spec = FieldSpec( &
           geom=geom, vertical_grid=BasicVerticalGrid(1), vertical_dim_spec=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDims(), &
           standard_name='A', long_name='AA', attributes=StringVector(), &
           units='m')
      @assert_that(import_spec%can_connect_to(export_spec), is(true()))
   end subroutine test_mirror_geom
Call graph
test_mirror_geom calls assert_that, can_connect_to, stringvector, true
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception