test_one_timer – MAPL
test_one_timer Subroutine
13 statements
Source File
public subroutine test_one_timer()
Arguments
None
Calls
Source Code
   subroutine test_one_timer()
      type (NameColumn) :: column
      type (MeterNode), target :: node
      integer, parameter :: WIDTH = 10
      character(:), allocatable :: header(:)
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      column = NameColumn(width=WIDTH)
      ! Check proper padding.
      call column%get_header(header)
      @assertEqual(WIDTH, len(header))
      @assertEqual(WIDTH, len(column%get_row(node)))
      @assertEqual('Name      ',header(1))
      @assertEqual('all       ',column%get_row(node))
   end subroutine test_one_timer
Call graph
test_one_timer calls assertequal, get_header, get_row
get_header calls get_num_rows_header, get_separator, get_width
get_row calls get_depth, get_name, get_width
get_num_rows_header calls get_num_rows_separator
get_separator calls get_width