test_can_connect_accum_fail – MAPL
test_can_connect_accum_fail Subroutine
12 statements
Source File
public subroutine test_can_connect_accum_fail()
Arguments
None
Calls
Source Code
   subroutine test_can_connect_accum_fail()
      type(FrequencyAspect) :: import, export
      type(ESMF_TimeInterval) :: dt1, dt2
      type(ESMF_TimeInterval) :: offset1, offset2
      call ESMF_TimeIntervalSet(dt1, s=4)
      call ESMF_TimeIntervalSet(dt2, s=3) ! not commensurate
      call ESMF_TimeIntervalSet(offset1, s=0)
      call ESMF_TimeIntervalSet(offset2, s=0)
      import = FrequencyAspect(timeStep=dt2, offset=offset2, accumulation_type='mean')
      export = FrequencyAspect(timeStep=dt1, offset=offset1)
      @assert_that(export%can_connect_to(import), is(false()))
   end subroutine test_can_connect_accum_fail
Call graph
test_can_connect_accum_fail calls ESMF_TimeIntervalSet, assert_that, false, can_connect_to