test_interp_constant – MAPL
test_interp_constant Subroutine
108 statements
Source File
public subroutine test_interp_constant(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_interp_constant(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(ESMF_State) :: importState, exportState
      type(ESMF_FieldBundle) :: bracket
      type(ESMF_Field) :: f
      type(TimeinterpolateAction) :: action
      type(ESMF_Clock) :: clock
      type(ESMF_Geom) :: geom
      type(ESMF_Grid) :: grid
      integer :: status
      real(kind=ESMF_KIND_R4), pointer :: x(:)
      importState = ESMF_StateCreate(_RC)
      exportState = ESMF_StateCreate(_RC)
      bracket = ESMF_FieldBundleCreate(name='import[1]', _RC)
      call ESMF_StateAdd(importState, [bracket], _RC)
      call MAPL_InfoSetInternal(importState, 'import[1]', 'weights', values=[7.0], _RC)
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', _RC)
      geom = ESMF_GeomCreate(grid, _RC)
      f = ESMF_FieldEmptyCreate(name='export[1]', _RC)
      call ESMF_FieldEmptySet(f, geom=geom, _RC)
      call ESMF_FieldEmptyComplete(f, typekind=ESMF_TYPEKIND_R4, _RC)
      call ESMF_StateAdd(exportState, [f], _RC)
      call action%update(importState, exportState, clock, _RC)
      call assign_fptr(f, x, _RC)
      @assert_that(x, every_item(is(equal_to(7.))))
      call ESMF_FieldDestroy(f, _RC)
      call ESMF_FieldBundleDestroy(bracket, _RC)
      call ESMF_StateDestroy(importState, _RC)
      call ESMF_StateDestroy(exportState, _RC)
      call ESMF_GridDestroy(grid, _RC)
      call ESMF_GeomDestroy(geom, _RC)
   end subroutine test_interp_constant
Call graph
test_interp_constant calls ESMF_GeomCreate, ESMF_GeomDestroy, ESMF_GridCreateNoPeriDim, ESMF_GridDestroy, anyexceptions, assert_that, equal_to, esmf_fieldbundlecreate, esmf_fieldbundledestroy, esmf_fielddestroy, esmf_fieldemptycomplete, esmf_fieldemptycreate, esmf_fieldemptyset, esmf_stateadd, esmf_statecreate, esmf_statedestroy, every_item, assign_fptr, mapl_infosetinternal, update, sourcelocation
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception