test_accumulate_nested – MAPL
test_accumulate_nested Subroutine
30 statements
Source File
public subroutine test_accumulate_nested()
Arguments
None
Calls
Source Code
   subroutine test_accumulate_nested()
      type(TimeProfiler), target :: main, lap
      class(AbstractMeterNode), pointer :: main_node
      class(AbstractMeterNode), pointer :: child
      class(AbstractMeter), pointer :: t
      main = TimeProfiler('main')
      call main%start()
      lap = TimeProfiler('lap')
      call lap%start()
      call lap%start('A')
      call lap%stop('A')
      call lap%finalize()
      call main%accumulate(lap)
      ! should now have 'lap' as a subtimer of 'main'
      @assertEqual(3, main%get_num_meters())
      main_node => main%get_root_node()
      @assertTrue(main_node%has_child('lap'))
      child => main_node%get_child('lap')
      t => child%get_meter()
      select type (t)
      class is (AdvancedMeter)
         @assertEqual(1, t%get_num_cycles())
      end select
      @assertTrue(child%has_child('A'))
      child => child%get_child('A')
      t => child%get_meter()
      select type (t)
      class is (AdvancedMeter)
         @assertEqual(1, t%get_num_cycles())
      end select
   end subroutine test_accumulate_nested
Call graph
test_accumulate_nested calls assertequal, asserttrue, get_child, get_meter, get_num_cycles, has_child, start, accumulate, finalize, get_num_meters, get_root_node
accumulate calls get_root_node, accumulate, vector_back
finalize calls finalize, get_meter, vector_pop_back, mpi_op_free, mpi_type_free
get_num_meters calls get_num_nodes
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
start_self calls mapl_return
vector_pop_back calls vector_downsize
mapl_return calls get_error_message, mapl_throw_exception