test_get_i4_not_found_no_default – MAPL
test_get_i4_not_found_no_default Subroutine
11 statements
Source File
public subroutine test_get_i4_not_found_no_default()
Arguments
None
Calls
Source Code
   subroutine test_get_i4_not_found_no_default()
      character(len=*), parameter :: LABEL = 'inv_alpha'
      integer(kind=I4) :: actual
      type(HConfigParams) :: params
      logical :: found
      integer :: status_
      params = HConfigParams(hconfig, LABEL)
      call get_value(params, actual, rc=status_)
      found = params%value_set
      @assertFalse(status_ == 0, 'get_value should have failed.')
   end subroutine test_get_i4_not_found_no_default
Call graph
test_get_i4_not_found_no_default calls assertfalse, get_value
get_value calls get_value_i4, get_value_i4seq, get_value_i8, get_value_i8seq, get_value_logical, get_value_logical_seq, get_value_r4, get_value_r4seq, get_value_r8, get_value_r8seq, get_value_string
get_value_i4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_i8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_logical_seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r4seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8 calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_r8seq calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify
get_value_string calls esmf_hconfigisdefined, are_equal, get_hconfig, has_logger, log_message, make_fmt, mapl_return, mapl_verify