test_change_typekind – MAPL
test_change_typekind Subroutine
45 statements
Source File
public subroutine test_change_typekind(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_change_typekind(this)
      class(ESMF_TestMethod), intent(inout) :: this
      integer :: status
      type(Fieldbundledelta) :: delta
      type(ESMF_Geom) :: geom
      type(ESMF_FieldBundle) :: bundle
      type(ESMF_Field), allocatable :: fieldList(:)
      real(kind=ESMF_KIND_R8), pointer :: x_r8(:,:)
      real(kind=ESMF_KIND_R4), allocatable :: weights(:)
      integer :: i
      call setup_geom(geom, 4)
      call setup_bundle(bundle, weights=DEFAULT_WEIGHTS, geom=geom, typekind=ESMF_TYPEKIND_R4, units='m')
      delta = FieldBundleDelta(FieldDelta(typekind=ESMF_TYPEKIND_R8))
      call delta%update_bundle(bundle, _RC)
      call MAPL_FieldBundleGet(bundle, fieldList=fieldList, _RC)
      @assert_that(size(fieldList), is(FIELD_COUNT))
      do i = 1, FIELD_COUNT
         call ESMF_FieldGet(fieldList(i), fArrayPtr=x_r8, _RC)
         @assert_that(shape(x_r8), is(equal_to([4,4])))
      end do
      call MAPL_FieldBundleGet(bundle, interpolation_weights=weights, _RC)
      @assert_that(weights, is(equal_to(DEFAULT_WEIGHTS)))
      call teardown_bundle(bundle)
      call teardown_geom(geom)
      _UNUSED_DUMMY(this)
   end subroutine test_change_typekind
Call graph
test_change_typekind calls anyexceptions, assert_that, equal_to, esmf_fieldget, mapl_fieldbundleget, update_bundle, setup_bundle, setup_geom, teardown_bundle, teardown_geom, sourcelocation
setup_bundle calls esmf_fieldbundleadd, esmf_fieldbundlecreate, mapl_fieldbundleset, add_dim, setup_field
setup_geom calls ESMF_GeomCreate, ESMF_GridCreateNoPeriDim
teardown_bundle calls mapl_fieldbundleget, esmf_fieldbundledestroy, esmf_fielddestroy
teardown_geom calls ESMF_GeomDestroy, ESMF_GeomGet, ESMF_GridDestroy