test_addReadDataCollection_unique_handle – MAPL
test_addReadDataCollection_unique_handle Subroutine
17 statements
Source File
public subroutine test_addReadDataCollection_unique_handle()
Arguments
None
Calls
Source Code
   subroutine test_addReadDataCollection_unique_handle()
      type (MockClientThread) :: c
      class (AbstractSocket), pointer :: connection
      integer :: handle_foo
      integer :: handle_bar
      type (MockSocketLog), target :: log
      call c%set_connection(MockSocket(log))
      connection => c%get_connection()
      select type (connection)
      type is (MockSocket)
         call connection%add_message(IdMessage(1))
         call connection%add_message(IdMessage(2))
      end select
      handle_foo = c%add_data_collection(file_template='foo')
      handle_bar = c%add_data_collection(file_template='bar')
      @assertFalse(handle_foo == handle_bar)
   end subroutine test_addReadDataCollection_unique_handle
Call graph
test_addreaddatacollection_unique_handle calls add_message, assertfalse, add_data_collection, get_connection, set_connection
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception