test_get_fptr_shape_wrong_order_raise_exception – MAPL
test_get_fptr_shape_wrong_order_raise_exception Subroutine
13 statements
Source File
public subroutine test_get_fptr_shape_wrong_order_raise_exception()
Arguments
None
Calls
Source Code
    subroutine test_get_fptr_shape_wrong_order_raise_exception()
       integer :: expected(ARRAY_RANK), actual(ARRAY_RANK)
       integer, allocatable :: gridToFieldMap(:)
       integer, allocatable :: localElementCount(:)
       logical :: has_vertical
       integer :: status
       gridToFieldMap = [4, 5]
       has_vertical = .TRUE.
       localElementCount = [2, 3, 5, 7, 11]
       expected = [product(localElementCount(4:5)), localElementCount(3), product(localElementCount(1:2))]
       ! This tests throws an Exception for improper input arguments.
       ! In other words, the improper input arguments ARE the point.
       actual = get_fptr_shape(gridToFieldMap, localElementCount, has_vertical, rc=status)
       @assertExceptionRaised()
    end subroutine test_get_fptr_shape_wrong_order_raise_exception
Call graph
test_get_fptr_shape_wrong_order_raise_exception calls assertexceptionraised, get_fptr_shape
get_fptr_shape calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception