test_parse_ChildSpecMap_empty – MAPL
test_parse_ChildSpecMap_empty Subroutine
10 statements
Source File
public subroutine test_parse_ChildSpecMap_empty()
Arguments
None
Calls
Source Code
   subroutine test_parse_ChildSpecMap_empty()
      type(ChildSpecMap) :: expected, found
      integer :: status, rc
      type(ESMF_HConfig) :: hconfig
      hconfig = ESMF_HConfigCreate(content='{}')
      found = parse_children(hconfig, _RC)
      @assert_that(found == expected, is(true()))
      call ESMF_HConfigDestroy(hconfig)
   end subroutine test_parse_ChildSpecMap_empty
Call graph
test_parse_childspecmap_empty calls ESMF_HConfigCreate, ESMF_HConfigDestroy, assert_that, mapl_verify, parse_children, true
mapl_verify calls mapl_throw_exception
parse_children calls ESMF_HConfigDestroy, mapl_verify, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, insert, mapl_return, parse_child
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_child calls mapl_verify, esmf_hconfigisdefined, mapl_assert, mapl_return, esmf_hconfigasstring, user_setservices
user_setservices calls new_dsosetservices, new_procsetservices
get_error_message calls at, insert
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message