test_make_ungridded_dims – MAPL
test_make_ungridded_dims Subroutine
19 statements
Source File
public subroutine test_make_ungridded_dims()
Arguments
None
Calls
Source Code
   subroutine test_make_ungridded_dims()
      type(UngriddedDims) :: a, b
      type(ESMF_Info) :: info
      integer :: status
      a = UngriddedDims()
      call a%add_dim(UngriddedDim(name='a1', units='m', coordinates=[2.,3.,5.]))
      call a%add_dim(UngriddedDim(name='a2', units='cm', extent=5))
      info = a%make_info(_RC)
      b = make_UngriddedDims(info, _RC)
      @assert_that(a == b, is(true()))
   end subroutine test_make_ungridded_dims
Call graph
test_make_ungridded_dims calls anyexceptions, assert_that, add_dim, make_info, make_ungriddeddims, sourcelocation, true
make_ungriddeddims calls ESMF_InfoCreate, ESMF_InfoDestroy, mapl_infoget, make_dim_key, make_ungriddeddim, mapl_return, mapl_verify
make_dim_key calls mapl_assert, mapl_return
make_ungriddeddim calls mapl_infoget, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception