test_finalize_children – MAPL
test_finalize_children Subroutine
17 statements
Source File
public subroutine test_finalize_children(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_finalize_children(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_State) :: importState, exportState
      integer :: status
      type(ESMF_Time) :: t
      type(ESMF_TimeInterval) :: dt
      type(ESMF_Clock) :: clock
      call ESMF_TimeSet(t, h=0)
      call ESMF_TimeIntervalSet(dt, h=1)
      clock = ESMF_ClockCreate(dt, t)
      call setup(this, rc=status)
      @assert_that(status, is(0))
      call parent_meta%finalize(importState, exportState, clock, rc=status)
      @assert_that(status, is(0))
      @assertEqual("wasFinal :: wasFinal_child_1 :: wasFinal_child_2", log)
      call teardown(this)
   end subroutine test_finalize_children
Call graph
test_finalize_children calls ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, assert_that, assertequal, finalize, setup, teardown
finalize calls finalize, get_phase_index, at, mapl_return, mapl_verify, omap_begin, omap_iter_next, run_custom
setup calls ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, assert_that, ESMF_HConfigCreate, ESMF_HConfigDestroy, esmf_gridcompsetservices, create_grid_comp, get_outer_meta, user_setservices, add_child, clear_log, get_gridcomp, get_user_gc_driver
teardown calls assert_that, ESMF_GridCompDestroy