test_propagate_import – MAPL
test_propagate_import Subroutine
28 statements
Source File
public subroutine test_propagate_import()
Arguments
None
Calls
Source Code
   subroutine test_propagate_import()
      type(StateRegistry), target :: r_child, r_parent
      integer :: status
      type(VirtualConnectionPt) :: v_pt
      type(ExtensionFamily), pointer :: family
      r_parent = StateRegistry('parent')
      r_child = StateRegistry('child')
      call r_parent%add_subregistry(r_child)
      v_pt = VirtualConnectionPt(state_intent='import', short_name='T')
      call r_child%add_primary_spec(v_pt, MockItemSpec(12), _RC)
      call r_parent%propagate_unsatisfied_imports(_RC)
      @assert_that(r_parent%num_owned_items(), is(0))
      @assert_that(r_parent%has_virtual_pt(v_pt), is(true()))
      family => r_parent%get_extension_family(v_pt, _RC)
      @assert_that(family%has_primary(), is(false()))
   end subroutine test_propagate_import
Call graph
test_propagate_import calls anyexceptions, assert_that, false, add_primary_spec, add_subregistry, get_extension_family, has_primary, has_virtual_pt, num_owned_items, propagate_unsatisfied_imports, mockitemspec, sourcelocation, true
mockitemspec calls get_aspects, insert, make_stateitemspec, make_variablespec