test_FieldAddR4_missing – MAPL
test_FieldAddR4_missing Subroutine
21 statements
Source File
public subroutine test_FieldAddR4_missing(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldAddR4_missing(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x
      type(ESMF_Field) :: y
      real(kind=ESMF_KIND_R4), pointer :: x_ptr(:,:), y_ptr(:,:)
      real(kind=ESMF_KIND_R4), allocatable :: result_array(:,:)
      integer :: status, rc
      x = XR4
      y = YR4
      call ESMF_FieldGet(x , farrayPtr = x_ptr, _RC)
      call ESMF_FieldGet(y , farrayPtr = y_ptr, _RC)
      x_ptr = reshape(source=[2.0,2.0,2.0,undef],shape=[2,2])
      y_ptr = reshape(source=[undef,3.0,3.0,undef],shape=[2,2])
      result_array = x_ptr
      result_array = reshape(source=[undef,5.0,5.0,undef],shape=[2,2])
      call FieldAdd(y, x, y, _RC)
      @assertEqual(y_ptr, result_array)
   end subroutine test_FieldAddR4_missing
Call graph
test_fieldaddr4_missing calls assertequal, esmf_fieldget, fieldadd, mapl_verify
fieldadd calls esmf_fieldget, mapl_verify, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef, mapl_return
mapl_verify calls mapl_throw_exception
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
getfieldsundef calls getfieldsundef_r4, getfieldsundef_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fieldshaveundef calls mapl_verify, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoIsPresent
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
are_conformable_array calls mapl_verify, fieldsareconformable, mapl_return
are_conformable_scalar calls esmf_fieldget, mapl_verify, mapl_return, fieldgetlocalelementcount
assign_fptr_r4_rank1 calls mapl_verify, mapl_return, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_verify, mapl_return, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_verify, mapl_return, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_verify, mapl_return, fieldgetcptr
get_error_message calls at, insert
getfieldsundef_r4 calls mapl_verify, mapl_assert, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoGet
getfieldsundef_r8 calls mapl_verify, mapl_assert, mapl_return, ESMF_InfoGetFromHost, ESMF_InfoIsPresent, ESMF_InfoGet
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message