test_e2e_preserve_actual_pt – MAPL
test_e2e_preserve_actual_pt Subroutine
14 statements
Source File
public subroutine test_e2e_preserve_actual_pt()
Arguments
None
Calls
Source Code
   subroutine test_e2e_preserve_actual_pt()
      type(HierarchicalRegistry), target :: r
      type(HierarchicalRegistry), target :: r_A
      type(VirtualConnectionPt) :: vpt_1, vpt_2
      integer :: status
      r = HierarchicalRegistry('R')
      r_A = HierarchicalRegistry('A')
      call r%add_subregistry(r_A)
      vpt_1 = new_v_pt('export', 'ae1')
      vpt_2 = new_v_pt('export', 'ae2')
      ! True export
      call r_A%add_item_spec(vpt_1, MockItemSpec('AE1'))
      ! E-to-E with rename
      call r%add_connection(ReexportConnection(CP('A',vpt_1), CP('R',vpt_2)), rc=status)
      @assert_that(r%has_item_spec(ActualConnectionPt(vpt_1%add_comp_name('A'))), is(true()))
   end subroutine test_e2e_preserve_actual_pt
Call graph
test_e2e_preserve_actual_pt calls assert_that, add_item_spec, has_item_spec, add_comp_name, add_connection, add_subregistry, new_v_pt, true
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item_spec_actual calls has_item_spec, mapl_assert, mapl_return, mapl_verify, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception