test_can_connect_bracket_to_field – MAPL
test_can_connect_bracket_to_field Subroutine
8 statements
Source File
public subroutine test_can_connect_bracket_to_field()
Arguments
None
Calls
Source Code
   subroutine test_can_connect_bracket_to_field()
      type(BracketClassAspect) :: export
      type(FieldClassAspect) :: import
      export = BracketClassAspect(2, 'A', 'Abc')
      import = FieldClassASpect('B','Efg')
      ! cannot connect to another bracket
      @assert_that(export%can_connect_to(export), is(false()))
      @assert_that(export%can_connect_to(import), is(true()))
   end subroutine test_can_connect_bracket_to_field
Call graph
test_can_connect_bracket_to_field calls assert_that, false, can_connect_to, true