test_connect_geoms – MAPL
test_connect_geoms Subroutine
6 statements
Source File
public subroutine test_connect_geoms()
Arguments
None
Calls
Source Code
   subroutine test_connect_geoms()
      type(GeomAspect) :: import, export
      import = GeomAspect(geom2)
      export = GeomAspect(geom1)
      @assert_that(export%can_connect_to(import), is(true()))
   end subroutine test_connect_geoms
Call graph
test_connect_geoms calls assert_that, can_connect_to, true