test_mismatched_ungridded_dims_fail – MAPL
test_mismatched_ungridded_dims_fail Subroutine
11 statements
Source File
public subroutine test_mismatched_ungridded_dims_fail()
Arguments
None
Calls
Source Code
   subroutine test_mismatched_ungridded_dims_fail()
      type(UngriddedDimsAspect) :: import, export
      type(UngriddedDims) :: ungridded_dims1, ungridded_dims2
      call ungridded_dims1%add_dim(UngriddedDim(2))
      call ungridded_dims1%add_dim(UngriddedDim(3))
      call ungridded_dims2%add_dim(UngriddedDim(2))
      call ungridded_dims2%add_dim(UngriddedDim(1)) ! different
      import = UngriddedDimsAspect(ungridded_dims1)
      export = UngriddedDimsAspect(ungridded_dims2)
      @assert_that(export%can_connect_to(import), is(false()))
   end subroutine test_mismatched_ungridded_dims_fail
Call graph
test_mismatched_ungridded_dims_fail calls assert_that, false, add_dim, can_connect_to
mapl_return calls at, insert, mapl_throw_exception