test_add_item_duplicate_fail – MAPL
test_add_item_duplicate_fail Subroutine
12 statements
Source File
public subroutine test_add_item_duplicate_fail()
Arguments
None
Calls
Source Code
   subroutine test_add_item_duplicate_fail()
      type(HierarchicalRegistry) :: r
      integer :: status
      type(ActualConnectionPt) :: cp
      r = HierarchicalRegistry('A')
      cp = new_a_pt('A','A')
      call r%add_item_spec(cp, MockItemSpec('A'), rc=status)
      @assert_that(status, is(0))
      call r%add_item_spec(cp, MockItemSpec('A'), rc=status)
      @assertExceptionRaised('Duplicate item name.')
      @assert_that(status, is(not(0)))
   end subroutine test_add_item_duplicate_fail
Call graph
test_add_item_duplicate_fail calls assert_that, assertexceptionraised, add_item_spec, new_a_pt
new_a_pt calls new_v_pt
add_item_spec_actual calls mapl_assert, has_item_spec, is_internal, link_item_spec_actual, mapl_return, mapl_verify, set_active, vector_back, vector_push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
is_internal calls is_internal
link_item_spec_actual calls mapl_assert, has_item_spec, mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_push_back calls resize, vector_grow_to