test_equal_diff_variables – MAPL
test_equal_diff_variables Subroutine
29 statements
Source File
public subroutine test_equal_diff_variables()
Arguments
None
Calls
Source Code
   subroutine test_equal_diff_variables()
      type (FileMetadata) :: cf1, cf2
      type (Variable) :: v1, v2, v3
      call cf1%add_dimension('x', 10)
      call cf1%add_dimension('y', 20)
      call cf1%add_dimension('z', 30)
      cf2 = cf1
      v1 = Variable(type=pFIO_INT32, dimensions='x')
      v2 = Variable(type=pFIO_REAL64, dimensions='x,y,z')
      call v3%add_attribute('flag', .true.)
      call cf1%add_variable('v1', v1)
      @assertTrue(cf1 == cf1)
      @assertFalse(cf1 /= cf1)
      call cf1%add_variable('v2', v2)
      @assertFalse(cf1 == cf2)
      @assertFalse(cf2 == cf1)
      call cf2%add_variable('v2', v2)
      @assertFalse(cf1 == cf2)
      @assertFalse(cf2 == cf1)
      call cf2%add_variable('v1', v1)
      @assertTrue(cf1 == cf2)
      v3 = v1
      call cf1%add_variable('v3', v3)
      ! Modify v3 before adding to cf2
      ! Deep copy means v3 in cf1 is not affected.
      call v3%add_attribute('other', [1,2,3])
      call cf2%add_variable('v3', v3)
      @assertFalse(cf1 == cf2)
      ! get back to v1
      call cf2%modify_variable('v3',v1)
      @assertTrue(cf1 == cf2)
   end subroutine test_equal_diff_variables
Call graph
test_equal_diff_variables calls assertfalse, asserttrue, add_attribute, add_dimension, add_variable, modify_variable
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
modify_variable calls at, begin, get, mapl_assert, next, get_dimensions, map_set_, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
map_set_ calls insert
mapl_return calls get_error_message, mapl_throw_exception