test_clear_valid_mean – MAPL
test_clear_valid_mean Subroutine
28 statements
Source File
public subroutine test_clear_valid_mean()
Arguments
None
Calls
Source Code
   subroutine test_clear_valid_mean()
      type(MeanAction) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      acc%valid_mean = .TRUE.
      call acc%clear_valid_mean(_RC)
      @assertTrue(.not. any(acc%valid_mean), 'valid_mean .TRUE. in elements')
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_clear_valid_mean
Call graph
test_clear_valid_mean calls anyexceptions, assert_that, asserttrue, clear_valid_mean, initialize, destroy_objects, initialize_objects, sourcelocation
destroy_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy, get_field
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_GridCreateNoPeriDimUfrm, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate