test_set_stateitem_shared_i4 – MAPL
test_set_stateitem_shared_i4 Subroutine
43 statements
Source File
public subroutine test_set_stateitem_shared_i4()
Arguments
None
Calls
Source Code
   subroutine test_set_stateitem_shared_i4()
      type(ESMF_State) :: state
      type(ESMF_Field) :: field
      integer :: status
      integer(kind=ESMF_KIND_I4) :: i
      integer(kind=ESMF_KIND_I4), parameter :: expected = 1
      state = ESMF_StateCreate(name='export', _RC)
      field = ESMF_FieldEmptyCreate(name='f', _RC)
      call ESMF_StateAdd(state, [field], _RC)
      call MAPL_InfoSetShared(state, short_name='f', key='a', value=expected, _RC)
      call MAPL_InfoGetShared(state, short_name='f', key='a', value=i, _RC)
      @assert_that(i, is(expected))
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_set_stateitem_shared_i4
Call graph
test_set_stateitem_shared_i4 calls anyexceptions, assert_that, esmf_fielddestroy, esmf_fieldemptycreate, esmf_stateadd, esmf_statecreate, esmf_statedestroy, mapl_infogetshared, mapl_infosetshared, sourcelocation