test_get_ungridded_dims – MAPL
test_get_ungridded_dims Subroutine
42 statements
Source File
public subroutine test_get_ungridded_dims()
Arguments
None
Calls
Source Code
   subroutine test_get_ungridded_dims()
      integer :: status
      integer :: i
      integer, parameter :: N = 2
      integer, parameter :: D = 3
      character(len=*), parameter :: EXPECTED_NAMES(N) = ['color', 'phase']
      character(len=*), parameter :: EXPECTED_UNITS(N) = ['K  ', 'rad']
      real, parameter :: REAL_ARRAY(D) = [1.0, 2.0, 3.0]
      real :: EXPECTED_COORDINATES(N, D)
      character(len=:), allocatable :: name
      character(len=:), allocatable :: units
      real, allocatable :: coordinates(:)
      type(UngriddedDimVector) :: vec
      type(UngriddedDim) :: undim
      call safe_dealloc(bundle_info)
      do i=1, N
         EXPECTED_COORDINATES(i,:) = REAL_ARRAY
      end do
      allocate(bundle_info(N))
      do i=1, N
         bundle_info(i) = make_esmf_info(names=EXPECTED_NAMES, units_array=EXPECTED_UNITS, coordinates=EXPECTED_COORDINATES, _RC)
      end do
      vec = get_ungridded_dims_bundle_info(bundle_info, _RC)
      do i=1, N
         undim = vec%at(i)
         name = undim%get_name()
         @assertEqual(EXPECTED_NAMES(i), name, 'ungridded dimension name does not match.')
         units = undim%get_units()
         @assertEqual(EXPECTED_UNITS(i), units, 'ungridded dimension units does not match.')
         coordinates = undim%get_coordinates()
         @assertEqual(EXPECTED_COORDINATES(i, :), coordinates, 0.01, 'ungridded dimensions coordinates does not match.')
      end do
      call safe_dealloc(bundle_info)
   end subroutine test_get_ungridded_dims
Call graph
test_get_ungridded_dims calls anyexceptions, assert_that, assertequal, at, get_coordinates, get_name, get_units, get_ungridded_dims_bundle_info, make_esmf_info, safe_dealloc, sourcelocation
get_ungridded_dims_bundle_info calls get_name, mapl_assert, ftn_begin, ftn_end, get_ith_dim_spec, get_num_ungridded, next, of, push_back, make_ungriddeddims, mapl_return, mapl_verify
make_esmf_info calls anyexceptions, assert_that, sourcelocation, ESMF_InfoCreate, make_ungridded_dims_info, make_vertical_dim, make_vertical_geom
safe_dealloc calls deallocate_destroy