test_parse_ChildSpecMap_1 – MAPL
test_parse_ChildSpecMap_1 Subroutine
12 statements
Source File
public subroutine test_parse_ChildSpecMap_1()
Arguments
None
Calls
Source Code
   subroutine test_parse_ChildSpecMap_1()
      type(ESMF_HConfig), target :: config
      type(ESMF_HConfig), pointer :: config_ptr
      type(ChildSpecMap) :: expected, found
      integer :: status, rc
      config = ESMF_HConfigCreate(content='children: {A: {sharedObj: libA}}')
      config_ptr => config
      call expected%insert('A', ChildSpec(user_setservices('libA', 'setservices_')))
      found = parse_children(config_ptr, _RC)
      @assert_that(found == expected, is(true()))
   end subroutine test_parse_ChildSpecMap_1
Call graph
test_parse_childspecmap_1 calls ESMF_HConfigCreate, assert_that, user_setservices, insert, mapl_verify, parse_children, true
user_setservices calls new_dsosetservices, new_procsetservices
mapl_verify calls mapl_throw_exception
parse_children calls insert, mapl_verify, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreateAtMapVal, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, parse_child
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
map_insert_pair calls insert
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_child calls user_setservices, mapl_verify, esmf_hconfigisdefined, mapl_assert, mapl_return, esmf_hconfigasstring