test_connect_unique_mirror – MAPL
test_connect_unique_mirror Subroutine
21 statements
Source File
public subroutine test_connect_unique_mirror()
Arguments
None
Calls
Source Code
   subroutine test_connect_unique_mirror()
      type(BracketSpec) :: spec_1, spec_1b, spec_2, spec_mirror
      type(ESMF_Geom) :: geom
      type(ActualConnectionPt) :: actual_pt
      integer :: status
      type(ESMF_Grid) :: grid
      type(ESMF_Info) :: info
      grid = ESMF_GridCreateNoPeriDim(maxIndex=[4,4], name='I_AM_GROOT', rc=status)
      call ESMF_InfoGetFromHost(grid, info, rc=status)
      geom = ESMF_GeomCreate(grid, ESMF_STAGGERLOC_INVALID)
      spec_1 = BracketSpec( &
           field_spec=FieldSpec(geom=geom, vertical_geom=VerticalGeom(), &
           vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='barn'), &
           bracket_size=1)
      spec_1b = spec_1
      spec_2 = BracketSpec( &
           field_spec=FieldSpec(geom=geom, vertical_geom=VerticalGeom(), &
           vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='barn'), &
           bracket_size=2)
      spec_mirror = BracketSpec( &
           field_spec=FieldSpec(geom=geom, vertical_geom=VerticalGeom(), &
           vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', units='barn'))
      call spec_mirror%create(rc=status)
      @assert_that(status, is(0))
      call spec_mirror%connect_to(spec_1, actual_pt, rc=status)
      @assert_that(status, is(0))
      @assert_that(spec_mirror%can_connect_to(spec_2), is(false()))
      @assert_that(spec_mirror%can_connect_to(spec_1b), is(true()))
   end subroutine test_connect_unique_mirror
Call graph
test_connect_unique_mirror calls ESMF_GeomCreate, ESMF_GridCreateNoPeriDim, ESMF_InfoGetFromHost, assert_that, false, can_connect_to, connect_to, create, true
can_connect_to calls can_connect_to, mapl_return, mapl_verify, of, can_connect_units
connect_to calls can_connect_to, field_specs, mapl_assert, connect_to, create, destroy, mapl_return, mapl_verify, mirror
create calls esmf_fieldbundlecreate, mapl_return, mapl_verify, esmf_fieldemptycreate, mapl_fieldemptyset
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
destroy calls mapl_return, mapl_verify, esmf_fieldbundledestroy, destroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception