test_connect_swap_role – MAPL
test_connect_swap_role Subroutine
23 statements
Source File
public subroutine test_connect_swap_role(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_connect_swap_role(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DirectoryService) :: ds
      integer :: comm
      integer :: color, key, ierror
      type (MockServer) :: mock_server
      type (MockClient) :: mock_client
      ds = DirectoryService(this%getMpiCommunicator())
      color = this%getProcessRank()
      key = 0
      call MPI_Comm_split(this%getMpiCommunicator(), color, key, comm, ierror)
      @assertEqual(0, ierror)
      select case (this%getProcessRank())
      case (1) ! server
         mock_server = MockServer(comm)
         call ds%publish(PortInfo('input', mock_server), mock_server)
         call ds%connect_to_client('input', mock_server)
      case (0) ! client
         mock_client = MockClient()
         call ds%connect_to_server('input', mock_client, comm)
      end select
!C$      select type (s)
!C$      type is (MpiSocket)
!C$      class default
!C$         @assertTrue(.false.)
!C$      end select
!C$
      call ds%free_directory_resources()
   end subroutine test_connect_swap_role
Call graph
test_connect_swap_role calls assertequal, getmpicommunicator, getprocessrank, mpi_comm_split, connect_to_client, connect_to_server, free_directory_resources, publish