test_FieldGetCptr – MAPL
test_FieldGetCptr Subroutine
12 statements
Source File
public subroutine test_FieldGetCptr(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldGetCptr(this)
       class(MpiTestMethod), intent(inout) :: this
     type(ESMF_Field) :: x
      type(c_ptr) :: cptr
      integer :: status, rc
      x = XR4
      call FieldGetCptr(x, cptr, _RC)
      x = XR8
      call FieldGetCptr(x, cptr, _RC)
   end subroutine test_FieldGetCptr
Call graph
test_fieldgetcptr calls fieldgetcptr, mapl_verify
fieldgetcptr calls get_cptr
mapl_verify calls mapl_throw_exception
get_cptr calls mapl_verify, esmf_fieldget, mapl_assert, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8, mapl_return
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_cptr_i4 calls mapl_verify, esmf_fieldget, mapl_assert, mapl_return
get_cptr_i8 calls mapl_verify, esmf_fieldget, mapl_assert, mapl_return
get_cptr_r4 calls mapl_verify, esmf_fieldget, mapl_assert, mapl_return
get_cptr_r8 calls mapl_verify, esmf_fieldget, mapl_assert, mapl_return
mapl_return calls mapl_throw_exception, get_error_message