test_get_i4seq – MAPL
test_get_i4seq Subroutine
16 statements
Source File
public subroutine test_get_i4seq()
Arguments
None
Calls
Source Code
   subroutine test_get_i4seq()
      character(len=*), parameter :: LABEL = 'five'
      integer(kind=I4), parameter :: EXPECTED(5) = [-1, 0, 1, 2, 3]
      integer(kind=I4), allocatable :: actual(:)
      type(HConfigParams) :: params
      logical :: found
      integer :: status
      call ESMF_HConfigAdd(hconfig, EXPECTED, addKeyString=LABEL, rc=status)
      @assertEqual(0, status, ERROR_ADD_FAIL)
      params = HConfigParams(hconfig, LABEL, check_value_set=.TRUE.)
      call get_value(params, actual, rc=status)
      found = params%value_set
      @assertEqual(0, status, ERROR_GET_FAILED)
      @assertTrue(found, ERROR_NOT_FOUND // LABEL)
      @assertTrue(all(actual == EXPECTED), ERROR_MISMATCH)
   end subroutine test_get_i4seq
Call graph
test_get_i4seq calls ESMF_HConfigAdd, assertequal, asserttrue, get_value