test_field_accumulation – MAPL
test_field_accumulation Subroutine
17 statements
Source File
public subroutine test_field_accumulation()
Arguments
None
Calls
Source Code
   subroutine test_field_accumulation()
      type(FieldSpec), target :: field_spec
      type(VerticalDimSpec) :: vertical_dim_spec
      type(ESMF_Typekind_Flag) :: typekind
      character(len=8) :: accumulation_type
      type(AspectCollection), pointer :: aspects
      type(FrequencyAspect), pointer :: aspect
      character(len=8) :: actual_accumulation_type
      aspects => null()
      typekind = ESMF_TYPEKIND_R4
      accumulation_type = 'mean'
      field_spec = FieldSpec(vertical_dim_spec=vertical_dim_spec, typekind=typekind, &
         accumulation_type=accumulation_type, ungridded_dims=UngriddedDims())
      aspects => field_spec%get_aspects()
      aspect => aspects%get_frequency_aspect()
      actual_accumulation_type = aspect%get_accumulation_type()
      @assertEqual(accumulation_type, actual_accumulation_type, 'accumulation_type does not match expected.')
   end subroutine test_field_accumulation
Call graph
test_field_accumulation calls assertequal, get_accumulation_type, get_aspects, get_frequency_aspect