test_MAPL_RunChild_other_phase – MAPL
test_MAPL_RunChild_other_phase Subroutine
10 statements
Source File
public subroutine test_MAPL_RunChild_other_phase(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_MAPL_RunChild_other_phase(this)
      class(MpiTestMethod), intent(inout) :: this
      integer :: status
      call setup(this, rc=status)
      @assert_that(status, is(0))
      call MAPL_RunChild(user_gc, child_name='child_1', phase_name='extra', rc=status)
      @assert_that(status, is(0))
      @assertEqual("wasRun_extra_child_1", log)
      call teardown(this)
   end subroutine test_MAPL_RunChild_other_phase
Call graph
test_mapl_runchild_other_phase calls assert_that, assertequal, mapl_runchild, setup, teardown
mapl_runchild calls run_child_by_name
setup calls assert_that, ESMF_ClockCreate, ESMF_HConfigCreate, ESMF_HConfigDestroy, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_gridcompsetservices, create_grid_comp, get_outer_meta, user_setservices, add_child, clear_log, get_gridcomp, get_user_gc_driver
teardown calls assert_that, ESMF_GridCompDestroy
create_grid_comp calls create_grid_comp_primary
get_outer_meta calls get_outer_meta_from_outer_gc
user_setservices calls new_dsosetservices, new_procsetservices
run_child_by_name calls mapl_gridcompgetoutermeta, run_child, mapl_return, mapl_verify