test_add_virtual_pt – MAPL
test_add_virtual_pt Subroutine
14 statements
Source File
public subroutine test_add_virtual_pt()
Arguments
None
Calls
Source Code
   subroutine test_add_virtual_pt()
      type(StateRegistry) :: r
      type(VirtualConnectionPt) :: x
      integer :: status
      r = StateRegistry('A')
      x = VirtualConnectionPt(state_intent='import', short_name='x')
      @assert_that(r%has_virtual_pt(x), is(false()))
      call r%add_virtual_pt(x, _RC)
      @assert_that(r%has_virtual_pt(x), is(true()))
   end subroutine test_add_virtual_pt
Call graph
test_add_virtual_pt calls anyexceptions, assert_that, false, add_virtual_pt, has_virtual_pt, sourcelocation, true
mapl_return calls at, insert, mapl_throw_exception