test_get_item_spec_multi – MAPL
test_get_item_spec_multi Subroutine
14 statements
Source File
public subroutine test_get_item_spec_multi()
Arguments
None
Calls
Source Code
   subroutine test_get_item_spec_multi()
      type(HierarchicalRegistry) :: r
      type(ActualConnectionPt) :: cp_1, cp_2, cp_3
      cp_1 = new_a_pt('export', 'ae1')
      cp_2 = new_a_pt('export', 'ae2')
      cp_3 = new_a_pt('import', 'ai')
      r = HierarchicalRegistry('A')
      call r%add_item_spec(cp_1, MockItemSpec('AE1'))
      call r%add_item_spec(cp_2, MockItemSpec('AE2'))
      call r%add_item_spec(cp_3, MockItemSpec('AI'))
      if (.not. check(r, cp_1, 'AE1')) return
      if (.not. check(r, cp_2, 'AE2')) return
      if (.not. check(r, cp_3, 'AI'))return
   end subroutine test_get_item_spec_multi
Call graph
test_get_item_spec_multi calls check, add_item_spec, new_a_pt
check calls check_actual, check_virtual
new_a_pt calls new_v_pt
check_actual calls assert_that, assertequal, get_item_spec, true
check_virtual calls check_actual, assert_that, get_actual_pts, of, true