test_make_lon_axis_from_hconfig – MAPL
test_make_lon_axis_from_hconfig Subroutine
13 statements
Source File
public subroutine test_make_lon_axis_from_hconfig()
Arguments
None
Calls
Source Code
   subroutine test_make_lon_axis_from_hconfig()
      type(ESMF_HConfig) :: hconfig
      type(LonAxis) :: axis
      integer :: status
      real(kind=R8), allocatable :: expected_centers(:)
      hconfig = ESMF_HConfigCreate( &
           content="{im_world: 4, jm_world: 5, nx: 1, ny: 1, dateline: DC}", &
           rc=status)
      @assert_that(status, is(0))
      axis = make_LonAxis(hconfig, rc=status)
      @assert_that(status, is(0))
      expected_centers = [-180, -90, 0, 90]
      @assert_that(axis%get_centers(), is(equal_to(expected_centers)))
      call ESMF_HConfigDestroy(hconfig)
   end subroutine test_make_lon_axis_from_hconfig
Call graph
test_make_lon_axis_from_hconfig calls ESMF_HConfigCreate, ESMF_HConfigDestroy, assert_that, equal_to, get_centers, make_lonaxis
get_centers calls get_centers
make_lonaxis calls make_lonaxis_from_hconfig, make_lonaxis_from_metadata
make_lonaxis_from_hconfig calls make_lonaxis_from_hconfig, esmf_hconfigasi4, get_lon_range, mapl_assert, mapl_range, mapl_return, mapl_verify
make_lonaxis_from_metadata calls make_lonaxis_from_metadata, get_coordinates, get_dim_name, get_lon_corners, mapl_return, mapl_verify