test_clear – MAPL
test_clear Subroutine
43 statements
Source File
public subroutine test_clear(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_clear(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(MeanTransform) :: acc
      type(ESMF_State) :: importState, exportState
      type(ESMF_Clock) :: clock
      integer :: status
      integer(kind=ESMF_KIND_I4), parameter :: COUNTER = 4
      logical :: cleared = .FALSE.
      integer(kind=ESMF_KIND_I4), pointer :: fptr(:)
      call initialize_objects(importState, exportState, clock, ESMF_TYPEKIND_R4, _RC)
      call acc%initialize(importState, exportState, clock, _RC)
      call assign_fptr(acc%counter_field, fptr, _RC)
      fptr = COUNTER
      call acc%clear(_RC)
      call assign_fptr(acc%counter_field, fptr, _RC)
      cleared = all(fptr == 0)
      @assertTrue(cleared, 'Counter field is nonzero.')
      call destroy_objects(importState, exportState, clock, _RC)
   end subroutine test_clear
Call graph
test_clear calls anyexceptions, assert_that, asserttrue, assign_fptr, clear, initialize, destroy_objects, initialize_objects, sourcelocation
destroy_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockDestroy, ESMF_GridDestroy, esmf_fielddestroy, esmf_fieldget, esmf_statedestroy, get_field
initialize_objects calls anyexceptions, assert_that, sourcelocation, ESMF_ClockCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_fieldcreate, esmf_statecreate, create_grid