test_get_fptr_shape_noz – MAPL
test_get_fptr_shape_noz Subroutine
12 statements
Source File
public subroutine test_get_fptr_shape_noz()
Arguments
None
Calls
Source Code
    subroutine test_get_fptr_shape_noz()
       integer :: expected(ARRAY_RANK), actual(ARRAY_RANK)
       integer, allocatable :: gridToFieldMap(:)
       integer, allocatable :: localElementCount(:)
       logical :: has_vertical
       has_vertical = .FALSE.
       gridToFieldMap = [1, 2]
       localElementCount = [2, 3, 5, 7]
       expected = [product(localElementCount(1:2)), 1, product(localElementCount(3:))]
       actual = get_fptr_shape_private(gridToFieldMap, localElementCount, has_vertical)
       @assert_that(GENERIC_MESSAGE, actual, is(equal_to(expected)))
    end subroutine test_get_fptr_shape_noz
Call graph
test_get_fptr_shape_noz calls assert_that, equal_to, get_fptr_shape_private
get_fptr_shape_private calls mapl_assert, mapl_return
mapl_return calls at, insert, mapl_throw_exception