test_default_timeStep – MAPL
test_default_timeStep Subroutine
60 statements
Source File
public subroutine test_default_timeStep()
Arguments
None
Calls
Source Code
   subroutine test_default_timeStep()
      type(ESMF_Time) :: t0, t1, expected_refTime
      type(ESMF_TimeInterval) :: timeStep, expected_timeStep
      type(ESMF_Clock) :: clock
      integer :: status, user_status
      type(ESMF_HConfig) :: cap_hconfig
      type(ESMF_GridComp) :: cap_gridcomp
      type(GriddedComponentDriver) :: driver
      call ESMF_TimeSet(t0, timeString="2000-04-03T21:00:00", _RC)
      call ESMF_TimeSet(t1, timeString="2000-04-03T22:00:00", _RC)
      call ESMF_TimeIntervalSet(timestep, s=900)
      clock = ESMF_ClockCreate(timeStep=timeStep, startTime=t0, stoptime=t1, refTime=t0, _RC)
      cap_hconfig = ESMF_HConfigCreate(content='{use_default_timestep: true, use_default_runTime: true}', _RC)
      cap_gridcomp = MAPL_GridCompCreate('CAP', user_setservices(parent_ss), cap_hconfig, _RC)
      call ESMF_GridCompSetServices(cap_gridcomp, generic_setservices, userRC=user_status, _RC)
      driver = GriddedComponentDriver(cap_gridcomp, MultiState(), clock)
      call initialize_phases(driver, phases=GENERIC_INIT_PHASE_SEQUENCE, _RC)
      call driver%run(phase_idx=GENERIC_RUN_USER, _RC)
      call driver%run(phase_idx=GENERIC_RUN_CLOCK_ADVANCE, _RC)
      call ESMF_TimeIntervalSet(expected_timeStep, s=900)
      expected_refTime = t0
      @assert_that(child_timestep == expected_timestep, is(true()))
      @assert_that(child_reftime == expected_reftime, is(true()))
   end subroutine test_default_timeStep
Call graph
test_default_timestep calls ESMF_ClockCreate, ESMF_HConfigCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, anyexceptions, assert_that, esmf_gridcompsetservices, mapl_gridcompcreate, user_setservices, run, initialize_phases, sourcelocation, true
initialize_phases calls initialize, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception