test_merge_hconfig_problem_child – MAPL
test_merge_hconfig_problem_child Subroutine
15 statements
Source File
public subroutine test_merge_hconfig_problem_child()
Arguments
None
Calls
Source Code
   subroutine test_merge_hconfig_problem_child()
      integer :: status
      call ESMF_HConfigAdd(parent, content=PVALUE1, addKeyString=KEY1, _RC)
      call ESMF_HConfigAdd(child, content = "['A', 'B', 'C', 'D', 'E', 'F']", _RC)
      merged = merge_hconfig(parent, child, rc=status)
      @assertTrue(status /= 0, 'The return code should be nonzero.')
   end subroutine test_merge_hconfig_problem_child
Call graph
test_merge_hconfig_problem_child calls ESMF_HConfigAdd, anyexceptions, assert_that, asserttrue, merge_hconfig, sourcelocation
merge_hconfig calls ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, ESMF_HConfigSet, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception