test_write_mapping – MAPL
test_write_mapping Subroutine
41 statements
Source File
public subroutine test_write_mapping()
Arguments
None
Calls
Source Code
   subroutine test_write_mapping()
      type(ESMF_HConfig) :: hconfig
      character(100) :: buffer
      integer :: status
      hconfig = ESMF_HConfigCreate(content='{}', _RC)
      write(buffer, *, iostat=status) hconfig
      _VERIFY(status)
      @assertEqual(expected='{}', found=trim(buffer))
      call ESMF_HConfigDestroy(hconfig)
      hconfig = ESMF_HConfigCreate(content='{a: b}', _RC)
      write(buffer, *, iostat=status) hconfig
      _VERIFY(status)
      @assertEqual(expected='{a: b}', found=trim(buffer))
      call ESMF_HConfigDestroy(hconfig)
      hconfig = ESMF_HConfigCreate(content='{a: b, c: 1, d: 3.14, e: true}', _RC)
      write(buffer, *, iostat=status) hconfig
      _VERIFY(status)
      @assertEqual(expected='{a: b, c: 1, d: 3.14, e: true}', found=trim(buffer))
      call ESMF_HConfigDestroy(hconfig)
   end subroutine test_write_mapping
Call graph
test_write_mapping calls ESMF_HConfigCreate, ESMF_HConfigDestroy, anyexceptions, assert_that, assertequal, sourcelocation