test_add_item – MAPL
test_add_item Subroutine
5 statements
Source File
public subroutine test_add_item()
Arguments
None
Calls
Source Code
   subroutine test_add_item()
      type(FieldDictionary) :: fd
      fd = FieldDictionary() ! empty
      call fd%add_item('X_Y_Z', FieldDictionaryItem(canonical_units='m', long_name='X Y Z'))
   end subroutine test_add_item
Call graph
test_add_item calls add_item
add_item calls insert, add_aliases, get_aliases, mapl_return, mapl_verify
add_aliases calls mapl_return, begin, insert, mapl_assert, next, of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls insert, at
map_insert_pair calls insert
mapl_throw_exception calls initialize