test_parse_setServices_default – MAPL
test_parse_setServices_default Subroutine
7 statements
Source File
public subroutine test_parse_setServices_default()
Arguments
None
Calls
Source Code
   subroutine test_parse_setServices_default()
      type(ESMF_HConfig) :: config
      class(DSOSetServices), allocatable :: ss_expected
      config = ESMF_HConfigCreate(content='{sharedObj: libA}')
      ss_expected = DSOSetServices('libA', 'setservices_')
      @assert_that(parse_setservices(config) == ss_expected, is(true()))
   end subroutine test_parse_setServices_default
Call graph
test_parse_setservices_default calls ESMF_HConfigCreate, assert_that, parse_setservices, true
parse_setservices calls esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, user_setservices, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
user_setservices calls new_dsosetservices, new_procsetservices
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize