test_make_field_name – MAPL
test_make_field_name Subroutine
16 statements
Source File
public subroutine test_make_field_name()
Arguments
None
Calls
Source Code
   subroutine test_make_field_name()
      type(ComponentBuilder) :: builder
      type(FieldSpec) :: field_spec
      type(ESMF_Field) :: field
      character(len=ESMF_MAXSTR) :: name
      integer :: status
      type(ESMF_Geom) :: geom
      type(VerticalGeom) :: vertical_geom
      type(VerticalDimSpec) :: vertical_dim_spec
      field_spec = FieldSpec(geom, vertical_geom, vertical_dim_spec, ESMF_TYPEKIND_R4, UngriddedDims(), &
           '', '', 'unknown', StringVector())
      field = builder%make_field('A', field_spec, rc=status)
      @assert_that(status, is(0))
      call ESMF_FieldGet(field, name=name, rc=status)
      @assert_that(status, is(0))
      @assertEqual(name, 'A')
   end subroutine test_make_field_name
Call graph
test_make_field_name calls assert_that, assertequal, esmf_fieldget, make_field, stringvector
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception