test_set_stateitem_internal_string – MAPL
test_set_stateitem_internal_string Subroutine
43 statements
Source File
public subroutine test_set_stateitem_internal_string()
Arguments
None
Calls
Source Code
   subroutine test_set_stateitem_internal_string()
      type(ESMF_State) :: state
      type(ESMF_Field) :: field
      integer :: status
      character(len=:), allocatable :: s
      character(len=*), parameter :: expected = 'hello'
      state = ESMF_StateCreate(name='import', _RC)
      field = ESMF_FieldEmptyCreate(name='f', _RC)
      call ESMF_StateAdd(state, [field], _RC)
      call MAPL_InfoSetInternal(state, short_name='f', key='a', value=expected, _RC)
      call MAPL_InfoGetInternal(state, short_name='f', key='a', value=s, _RC)
      @assert_that(s, is(expected))
      call ESMF_FieldDestroy(field, _RC)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_set_stateitem_internal_string
Call graph
test_set_stateitem_internal_string calls anyexceptions, assert_that, esmf_fielddestroy, esmf_fieldemptycreate, esmf_stateadd, esmf_statecreate, esmf_statedestroy, mapl_infogetinternal, mapl_infosetinternal, sourcelocation