test_setInternal_bundle – MAPL
test_setInternal_bundle Subroutine
43 statements
Source File
public subroutine test_setInternal_bundle()
Arguments
None
Calls
Source Code
   subroutine test_setInternal_bundle()
      type(ESMF_State) :: state
      type(ESMF_FieldBundle) :: bundle
      integer :: status
      real(ESMF_KIND_R4), allocatable :: w(:)
      real(ESMF_KIND_R4), parameter :: expected(2) = [1., 2.]
      state = ESMF_StateCreate(name='import', _RC)
      bundle = ESMF_FieldBundleCreate(name='b', _RC)
      call ESMF_StateAdd(state, [bundle], _RC)
      call MAPL_InfoSetInternal(state, short_name='b', key='a', values=expected, _RC)
      call MAPL_InfoGetInternal(state, short_name='b', key='a', values=w, _RC)
      @assert_that(w, is(equal_to(expected)))
      call ESMF_FieldBundleDestroy(bundle, _RC)
      call ESMF_StateDestroy(state, _RC)
   end subroutine test_setInternal_bundle
Call graph
test_setinternal_bundle calls anyexceptions, assert_that, equal_to, esmf_fieldbundlecreate, esmf_fieldbundledestroy, esmf_stateadd, esmf_statecreate, esmf_statedestroy, mapl_infogetinternal, mapl_infosetinternal, sourcelocation