test_get_vertical_dim_spec_names – MAPL
test_get_vertical_dim_spec_names Subroutine
34 statements
Source File
public subroutine test_get_vertical_dim_spec_names()
Arguments
None
Calls
Source Code
   subroutine test_get_vertical_dim_spec_names()
      integer :: status
      character(len=*), parameter :: EXPECTED_NAME_1 = 'VERTICAL_DIM_CENTER'
      character(len=*), parameter :: EXPECTED_NAME_2 = 'VERTICAL_DIM_EDGE'
      type(StringVector), allocatable :: names
      integer :: sz
      call safe_dealloc(bundle_info)
      allocate(bundle_info(3))
      bundle_info(1) = make_esmf_info(vloc=EXPECTED_NAME_1, _RC)
      bundle_info(2) = make_esmf_info(vloc=EXPECTED_NAME_2, _RC)
      bundle_info(3) = make_esmf_info(vloc=EXPECTED_NAME_1, _RC)
      names = get_vertical_dim_spec_names_bundle_info(bundle_info, _RC)
      sz = names%size()
      @assertEqual(2, sz, 'There should only be two unique vertical_dim_spec names.')
      @assertEqual(EXPECTED_NAME_1, names%at(1), 'vertical_dim_spec_name 1 does not match.')
      @assertEqual(EXPECTED_NAME_2, names%at(2), 'vertical_dim_spec_name 2 does not match.')
      call safe_dealloc(bundle_info)
   end subroutine test_get_vertical_dim_spec_names
Call graph
test_get_vertical_dim_spec_names calls anyexceptions, assert_that, assertequal, at, get_vertical_dim_spec_names_bundle_info, make_esmf_info, safe_dealloc, sourcelocation
get_vertical_dim_spec_names_bundle_info calls ESMF_InfoGet, ESMF_InfoGetCharAlloc, ESMF_InfoIsPresent, begin, next, of, mapl_return, mapl_verify, push_back, stringvector
make_esmf_info calls anyexceptions, assert_that, sourcelocation, ESMF_InfoCreate, make_ungridded_dims_info, make_vertical_dim, make_vertical_geom
safe_dealloc calls deallocate_destroy
deallocate_destroy calls destroy_all
make_ungridded_dims_info calls anyexceptions, assert_that, sourcelocation, ESMF_InfoSet, make_dim_key
make_vertical_dim calls anyexceptions, assert_that, sourcelocation, ESMF_InfoSet
make_vertical_geom calls anyexceptions, assert_that, sourcelocation, ESMF_InfoSet
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
destroy_all calls ESMF_InfoDestroy
make_dim_key calls mapl_return, mapl_assert