test_internal_to_export_connection – MAPL
test_internal_to_export_connection Subroutine
19 statements
Source File
public subroutine test_internal_to_export_connection()
Arguments
None
Calls
Source Code
   subroutine test_internal_to_export_connection()
      type(HierarchicalRegistry), target :: r
      type(VirtualConnectionPt) :: vpt_1, vpt_2
      class(StateItemSpec), pointer :: spec
      integer :: status
      r = HierarchicalRegistry('R')
      vpt_1 = new_v_pt('internal', 'a')
      vpt_2 = new_v_pt('export', 'a')
      ! True export
      call r%add_item_spec(vpt_1, MockItemSpec('AE1'))
      ! Internal-to-export
      call r%add_connection(ReexportConnection(CP('R',vpt_1), CP('R',vpt_2)), rc=status)
      @assert_that(status, is(0))
      if (.not. check(r, vpt_2, ['AE1'])) return
      ! Internal is always active, so this export should be as well:
      associate (a_pt => ActualConnectionPt(vpt_2))
        @assert_that('expected a_pt not found', r%has_item_spec(a_pt), is(true()))
        spec => r%get_item_spec(ActualConnectionPt(vpt_2))
        @assert_that(associated(spec), is(true()))
        @assert_that(spec%is_active(), is(true()))
      end associate
   end subroutine test_internal_to_export_connection
Call graph
test_internal_to_export_connection calls assert_that, check, add_item_spec, has_item_spec, add_connection, get_item_spec, is_active, new_v_pt, true
check calls check_actual, check_virtual
add_connection calls connect, mapl_return, mapl_verify
get_item_spec calls at, mapl_return, mapl_verify
add_item_spec_actual calls has_item_spec, mapl_return, mapl_verify, mapl_assert, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
check_actual calls assert_that, get_item_spec, true, assertequal
check_virtual calls assert_that, true, check_actual, of, get_actual_pts
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception