test_convertible_units – MAPL
test_convertible_units Subroutine
8 statements
Source File
public subroutine test_convertible_units()
Arguments
None
Calls
Source Code
   subroutine test_convertible_units()
      type(FieldSpec) :: import_spec
      type(FieldSpec) :: export_spec
      type(ESMF_Geom) :: geom
      import_spec = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', attributes=StringVector(), &
           units='m')
      export_spec = FieldSpec( &
           geom=geom, vertical_geom=VerticalGeom(), vertical_dim=VerticalDimSpec(), &
           typekind=ESMF_TYPEKIND_R4, &
           ungridded_dims = UngriddedDimsSpec(), &
           standard_name='A', long_name='AA', attributes=StringVector(), &
           units='km')
      @assert_that(import_spec%can_connect_to(export_spec), is(true()))
   end subroutine test_convertible_units
Call graph
test_convertible_units calls assert_that, can_connect_to, stringvector, true
can_connect_to calls of, can_connect_units, mapl_return, mapl_verify
can_connect_units calls mapl_return, mapl_verify, are_convertible, match
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_convertible calls are_convertible_str, are_convertible_udunit
match calls match_geom, match_string, match_typekind
get_error_message calls at, insert
mapl_throw_exception calls initialize