test_get_subregistry – MAPL
test_get_subregistry Subroutine
10 statements
Source File
public subroutine test_get_subregistry()
Arguments
None
Calls
Source Code
   subroutine test_get_subregistry()
      type(HierarchicalRegistry), target :: child_registry
      type(HierarchicalRegistry), target :: r
      class(AbstractRegistry), pointer :: ptr
      r = HierarchicalRegistry('parent')
      child_registry = HierarchicalRegistry('child')
      call r%add_subregistry(child_registry)
      ptr => r%get_subregistry('child')
      @assert_that(associated(ptr), is(true()))
   end subroutine test_get_subregistry
Call graph
test_get_subregistry calls assert_that, get_subregistry, add_subregistry, true
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_subregistry_comp calls mapl_assert, get_name, mapl_return, at, mapl_verify
get_subregistry_conn calls get_subregistry, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_insert_pair calls insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception