test_fail_add_existing_dim_with_mismatch – MAPL
test_fail_add_existing_dim_with_mismatch Subroutine
6 statements
Source File
public subroutine test_fail_add_existing_dim_with_mismatch()
Arguments
None
Calls
Source Code
   subroutine test_fail_add_existing_dim_with_mismatch()
      type (FileMetadata) :: cf
      call cf%add_dimension('x', 10)
      call cf%add_dimension('x', 11)
      @assertExceptionRaised('FileMetadata::add_dimension() - dimension already exists with different extent.')
   end subroutine test_fail_add_existing_dim_with_mismatch
Call graph
test_fail_add_existing_dim_with_mismatch calls assertexceptionraised, add_dimension
mapl_return calls insert, at, mapl_throw_exception