test_create_extension – MAPL
test_create_extension Subroutine
22 statements
Source File
public subroutine test_create_extension()
Arguments
None
Calls
Source Code
   subroutine test_create_extension()
      type(HierarchicalRegistry), target :: r_A, r_B
      class(StateItemSpec), pointer :: dst_spec, src_spec
      class(ExtensionAction), allocatable :: action
      type(ActualConnectionPt) :: e1, i1
      integer :: status
      e1 = new_a_pt('export', 'Q')
      i1 = new_a_pt('import', 'Q')
      call r_A%add_item_spec(e1, MockItemSpec('E1','fruit'))
      call r_B%add_item_spec(i1, MockItemSpec('I1','animal'))
      src_spec => r_A%get_item_spec(e1)
      dst_spec => r_B%get_item_spec(i1)
      @assert_that((dst_spec%can_connect_to(src_spec)), is(true()))
      action = src_spec%make_action(dst_spec, rc=status)
      @assert_that(status, is(0))
      select type (action)
      type is (MockAction)
         @assertEqual('fruit ==> animal', action%details)
      class default
         @assert_that(1, is(2))
      end select
   end subroutine test_create_extension
Call graph
test_create_extension calls assert_that, assertequal, can_connect_to, add_item_spec, get_item_spec, make_action, new_a_pt, true
get_item_spec calls at, mapl_return, mapl_verify
make_action calls mapl_assert
new_a_pt calls new_v_pt
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item_spec_actual calls mapl_assert, mapl_return, mapl_verify, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception