test_connect_chain – MAPL
test_connect_chain Subroutine
26 statements
Source File
public subroutine test_connect_chain(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_connect_chain(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(HierarchicalRegistry) :: r
      type(HierarchicalRegistry), target :: r_A, r_B, r_grandchild
      type(VirtualConnectionPt) :: vpt_1, vpt_2, vpt_3
      type(ActualPtVector), pointer :: actual_pts
      integer :: status
      r = HierarchicalRegistry('R')
      r_grandchild = HierarchicalRegistry('grandchild')
      r_A = HierarchicalRegistry('A')
      r_B = HierarchicalRegistry('B')
      call r_A%add_subregistry(r_grandchild)
      call r%add_subregistry(r_A)
      call r%add_subregistry(r_B)
      vpt_1 = new_v_pt('export', 'ae1')
      vpt_2 = new_v_pt('export', 'ae2')
      vpt_3 = new_v_pt('import', 'ai')
      call r_grandchild%add_item_spec(vpt_1, MockItemSpec('AE1'))
      call r_B%add_item_spec(vpt_3, MockItemSpec('AI'))
      ! E-to-E
      call r_A%add_connection(ReexportConnection(CP('grandchild',vpt_1), CP('A',vpt_2)), rc=status)
      @assert_that(status, is(0))
      ! sibling
      call r%add_connection(SimpleConnection(CP('A',vpt_2), CP('B', vpt_3)), rc=status)
      @assert_that(status, is(0))
       ! Check that extension was created
      actual_pts => r_a%get_actual_pts(vpt_2)
      @assert_that(int(actual_pts%size()), is(2))
   end subroutine test_connect_chain
Call graph
test_connect_chain calls assert_that, add_item_spec, add_connection, add_subregistry, get_actual_pts, new_v_pt
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
get_actual_pts calls at
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_item_spec_actual calls mapl_assert, mapl_return, mapl_verify, has_item_spec, is_internal, link_item_spec_actual, set_active, vector_back, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception