test_multi_import – MAPL
test_multi_import Subroutine
35 statements
Source File
public subroutine test_multi_import(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_multi_import(this)
      class(ESMF_TestMethod), intent(inout) :: this
      type(HierarchicalRegistry), target :: r_C, r_D, r_A, r_B
      type(HierarchicalRegistry) :: r_P
      type(VirtualConnectionPt) :: T_A, T_B, T_C, T_D
      class(StateItemSpec), pointer :: spec
      r_A = HierarchicalRegistry('A')
      r_B = HierarchicalRegistry('B')
      r_C = HierarchicalRegistry('C')
      r_D = HierarchicalRegistry('D')
      r_P = HierarchicalRegistry('parent')
      call r_B%add_subregistry(r_C)
      call r_B%add_subregistry(r_D)
      call r_P%add_subregistry(r_A)
      call r_P%add_subregistry(r_B)
      T_A = new_v_pt('export', 'T')
      T_B = new_v_pt('import', 'T')
      T_C = new_v_pt('import', 'T')
      T_D = new_v_pt('import', 'T')
      call r_A%add_item_spec(T_A, MockItemSpec('T_A'))
      call r_C%add_item_spec(T_C, MockItemSpec('T_C'))
      call r_D%add_item_spec(T_D, MockItemSpec('T_D'))
      ! i2i
      call r_B%propagate_unsatisfied_imports()
      ! sibling
      call r_P%add_connection(SimpleConnection(CP('A',T_A), CP('B', T_B)))
      ! Export should be active
      spec => r_A%get_item_spec(new_a_pt('export', 'T'))
      @assert_that(spec%is_active(), is(true()))
      ! Primary imports should be active
      spec => r_C%get_item_spec(new_a_pt('import', 'T'))
      @assert_that(spec%is_active(), is(true()))
      spec => r_D%get_item_spec(new_a_pt('import', 'T'))
      @assert_that(spec%is_active(), is(true()))
      ! Secondary imports should be active
      spec => r_B%get_item_spec(ActualConnectionPt(T_C%add_comp_name('C')))
      @assert_that(spec%is_active(), is(true()))
      spec => r_B%get_item_spec(ActualConnectionPt(T_D%add_comp_name('D')))
      @assert_that(spec%is_active(), is(true()))
   end subroutine test_multi_import
Call graph
test_multi_import calls assert_that, add_item_spec, propagate_unsatisfied_imports, add_comp_name, add_connection, add_subregistry, get_item_spec, is_active, new_a_pt, new_v_pt, true
add_connection calls connect, mapl_return, mapl_verify
add_subregistry calls mapl_assert, insert, get_name, has_subregistry, mapl_return
get_item_spec calls at, mapl_return, mapl_verify
new_a_pt calls new_v_pt