to_esmf_state_intent – MAPL
to_esmf_state_intent Function
18 statements
Source File
public function to_esmf_state_intent(str_state_intent, rc) result(state_intent)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str_state_intent
integer, intent(out), optional :: rc
Return Value type(ESMF_StateIntent_Flag)
Calls
Called by
Source Code
   function to_esmf_state_intent(str_state_intent, rc) result(state_intent)
      type(ESMF_StateIntent_Flag) :: state_intent
      character(*), intent(in) :: str_state_intent
      integer, optional, intent(out) :: rc
      select case (str_state_intent)
      case ('import')
         state_intent = ESMF_STATEINTENT_IMPORT
      case ('export')
         state_intent = ESMF_STATEINTENT_EXPORT
      case ('internal')
         state_intent = ESMF_STATEINTENT_INTERNAL
      case default
         state_intent = ESMF_STATEINTENT_INVALID
         _FAIL('invalid state intent: ' // str_state_intent)
      end select
      _RETURN(_SUCCESS)
   end function to_esmf_state_intent
Call graph
to_esmf_state_intent calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_var_specs calls to_esmf_state_intent
parse_component_spec calls parse_var_specs
setservices_ calls parse_component_spec, setservices_