transpose_regrid_vector_3d_real32 – MAPL
transpose_regrid_vector_3d_real32 Subroutine
99 statements
Source File
private subroutine transpose_regrid_vector_3d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
real, intent(in) :: u_in(:,:,:)
real, intent(in) :: v_in(:,:,:)
real, intent(out) :: u_out(:,:,:)
real, intent(out) :: v_out(:,:,:)
logical, intent(in), optional :: rotate
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine transpose_regrid_vector_3d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
      class (EsmfRegridder), intent(in) :: this
      real, intent(in) :: u_in(:,:,:)
      real, intent(in) :: v_in(:,:,:)
      real, intent(out) :: u_out(:,:,:)
      real, intent(out) :: v_out(:,:,:)
      logical, optional, intent(in) :: rotate
      integer, optional, intent(out) :: rc
      character(*), parameter :: Iam = 'MAPL_EsmfRegridder::transpose_regrid_vector_3d_real32()'
      integer :: status
      type (RegridderSpec) :: spec
      class (AbstractGridFactory), pointer :: factory
      real, pointer :: p_src(:,:,:,:), p_dst(:,:,:,:)
      type (ESMF_Field) :: src_field, dst_field
      integer :: km,kin,kout
      integer :: im_src, jm_src
      integer :: im_dst, jm_dst
      character(len=ESMF_MAXSTR) :: grid_axis_in, grid_axis_out
      logical :: hasDE
      type(ESMF_VM) :: vm
      spec = this%get_spec()
      call ESMF_VMGetCurrent(vm,rc=status)
      _VERIFY(status)
      km = size(u_in,3)
      _ASSERT(km == size(v_in,3),'inconsistent array shape')
      if (size(u_out) /= 0) then
         _ASSERT(km == size(u_out,3),'inconsistent array shape')
         _ASSERT(km == size(v_out,3),'inconsistent array shape')
      end if
      im_src = size(u_in,1)
      jm_src = size(u_in,2)
      _ASSERT(im_src == size(v_in,1),'inconsistent array shape')
      _ASSERT(jm_src == size(v_in,2),'inconsistent array shape')
      im_dst = size(u_out,1)
      jm_dst = size(u_out,2)
      _ASSERT(im_dst == size(v_out,1),'inconsistent array shape')
      _ASSERT(jm_dst == size(v_out,2),'inconsistent array shape')
      allocate(p_src(3,km,im_src,jm_src))
      allocate(p_dst(3,km,im_dst,jm_dst))
      grid_axis_in = 'north-south'
      grid_axis_out = 'north-south'
      if (present(rotate)) then
         if (rotate) then
            grid_axis_in = 'grid'
            grid_axis_out = 'xyz'
         end if
      end if
      factory => grid_manager%get_factory(spec%grid_out,rc=status)
      _VERIFY(status)
      hasDE = MAPL_GridHasDE(spec%grid_out,rc=status)
      _VERIFY(status)
      if (hasDE) then
         km = size(u_in,3)
      else
         km = 0
      end if
      call ESMF_VMAllReduce(vm,sendData=km,recvData=kin,reduceFlag=ESMF_REDUCE_MAX,rc=status)
      _VERIFY(status)
      src_field = ESMF_FieldCreate(spec%grid_out, typekind = ESMF_TYPEKIND_R4, &
           & gridToFieldMap=[3,4],ungriddedLBound=[1,1],ungriddedUBound=[3,kin],rc=status)
      _VERIFY(status)
      if (hasDE) then
         call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
         _VERIFY(status)
         call factory%spherical_to_cartesian(u_in, v_in, p_src, grid_axis_in, rc=status)
         _VERIFY(status)
      end if
      hasDE = MAPL_GridHasDE(spec%grid_in,rc=status)
      _VERIFY(status)
      if (hasDE) then
         km = size(u_out,3)
      else
         km = 0
      end if
      call ESMF_VMAllReduce(vm,sendData=km,recvData=kout,reduceFlag=ESMF_REDUCE_MAX,rc=status)
      _VERIFY(status)
      dst_field = ESMF_FieldCreate(spec%grid_in, typekind = ESMF_TYPEKIND_R4, &
           & gridToFieldMap=[3,4],ungriddedLBound=[1,1],ungriddedUBound=[3,kout],rc=status)
      _VERIFY(status)
      if (hasDE) then
         call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
         _VERIFY(status)
         p_dst = MAPL_UNDEF
      end if
      call this%do_regrid(src_field, dst_field, doTranspose=.true.,rc=status)
      _VERIFY(status)
      factory => grid_manager%get_factory(spec%grid_in,rc=status)
      _VERIFY(status)
      if (hasDE) then
         call factory%cartesian_to_spherical(p_dst, u_out, v_out, grid_axis_out,rc=status)
         _VERIFY(status)
      end if
      call ESMF_FieldDestroy(src_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(dst_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      deallocate(p_src)
      deallocate(p_dst)
      _RETURN(ESMF_SUCCESS)
   end subroutine transpose_regrid_vector_3d_real32
Call graph
transpose_regrid_vector_3d_real32 calls ESMF_VMAllReduce, ESMF_VMGetCurrent, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_assert, cartesian_to_spherical, spherical_to_cartesian, do_regrid, get_factory, get_spec, mapl_gridhasde, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
do_regrid calls esmf_fieldget, mapl_assert, get_spec, mapl_verify, ESMF_FieldRegrid, select_route_handle
get_factory calls mapl_return, mapl_verify, ESMF_InfoGet, ESMF_InfoGetFromHost, m_at
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception