typesafe_make_file_metadata – MAPL
typesafe_make_file_metadata Function
27 statements
Source File
function typesafe_make_file_metadata(geom_spec, unusable, chunksizes, rc) result(file_metadata)
Arguments
Type Intent Optional Attributes Name
type(LatLonGeomSpec), intent(in) :: geom_spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: chunksizes(:)
integer, intent(out), optional :: rc
Return Value type(FileMetadata)
Calls
Called by
Source Code
   function typesafe_make_file_metadata(geom_spec, unusable, chunksizes, rc) result(file_metadata)
      type(FileMetadata) :: file_metadata
      type(LatLonGeomSpec), intent(in) :: geom_spec
      class(KE), optional, intent(in) :: unusable
      integer, optional, intent(in) :: chunksizes(:)
      integer, optional, intent(out) :: rc
      type(LonAxis) :: lon_axis
      type(LatAxis) :: lat_axis
      type(Variable) :: v
      lon_axis = geom_spec%get_lon_axis()
      lat_axis = geom_spec%get_lat_axis()
      call file_metadata%add_dimension('lon', lon_axis%get_extent())
      call file_metadata%add_dimension('lat', lat_axis%get_extent())
      ! Coordinate variables
      v = Variable(type=PFIO_REAL64, dimensions='lon', chunksizes=chunksizes)
      call v%add_attribute('long_name', 'longitude')
      call v%add_attribute('units', 'degrees_east')
      call v%add_const_value(UnlimitedEntity(lon_axis%get_centers()))
      call file_metadata%add_variable('lon', v)
      v = Variable(type=PFIO_REAL64, dimensions='lat', chunksizes=chunksizes)
      call v%add_attribute('long_name', 'latitude')
      call v%add_attribute('units', 'degrees_north')
      call v%add_const_value(UnlimitedEntity(lat_axis%get_centers()))
      call file_metadata%add_variable('lat', v)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function typesafe_make_file_metadata
Call graph
typesafe_make_file_metadata calls get_centers, get_extent, get_lat_axis, get_lon_axis, add_attribute, add_const_value, add_dimension, add_variable, mapl_return
get_centers calls get_centers
get_extent calls get_extent
get_lat_axis calls get_lat_axis
get_lon_axis calls get_lon_axis
add_const_value calls mapl_return, mapl_assert, get_rank
add_dimension calls mapl_return, insert
add_variable calls mapl_return, at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
mapl_return calls get_error_message, mapl_throw_exception
make_file_metadata calls typesafe_make_file_metadata, make_file_metadata