typesafe_make_geom – MAPL
typesafe_make_geom Function
15 statements
Source File
function typesafe_make_geom(spec, rc) result(geom)
Arguments
Type Intent Optional Attributes Name
class(LatLonGeomSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Return Value type(ESMF_Geom)
Calls
Called by
Source Code
   function typesafe_make_geom(spec, rc) result(geom)
      type(ESMF_Geom) :: geom
      class(LatLonGeomSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Grid) :: grid
      grid = create_basic_grid(spec, _RC)
      call fill_coordinates(spec, grid, _RC)
      geom = ESMF_GeomCreate(grid=grid, _RC)
      _RETURN(_SUCCESS)
   end function typesafe_make_geom
Call graph
typesafe_make_geom calls ESMF_GeomCreate, create_basic_grid, fill_coordinates, mapl_return, mapl_verify
create_basic_grid calls create_basic_grid, mapl_return, mapl_verify, ESMF_GridAddCoord, ESMF_GridCreate1PeriDim, ESMF_GridCreateNoPeriDim, get_decomposition, get_lat_axis, get_lat_distribution, get_lon_axis, get_lon_distribution, is_periodic
fill_coordinates calls fill_coordinates, mapl_return, mapl_verify, ESMF_GridGetCoord, get_centers, get_corners, get_decomposition, get_lat_axis, get_lat_distribution, get_lat_subset, get_lon_axis, get_lon_distribution, get_lon_subset, get_ranks
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_geom calls typesafe_make_geom, make_geom
test_make_from_hconfig calls make_geom