ungridded_dim_names – MAPL
ungridded_dim_names Function
12 statements
Source File
public function ungridded_dim_names(field, rc) result(dim_names)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function ungridded_dim_names(field, rc) result(dim_names)
      character(len=:), allocatable :: dim_names
      type(ESMF_Field), intent(in) :: field
      integer, optional, intent(out) :: rc
      integer :: status
      type(UngriddedDims) :: ungridded_dims
      call MAPL_FieldGet(field, ungridded_dims=ungridded_dims, _RC)
      dim_names = cat_ungridded_dim_names(ungridded_dims)
      _RETURN(_SUCCESS)
   end function ungridded_dim_names
Call graph
ungridded_dim_names calls mapl_fieldget, cat_ungridded_dim_names, mapl_return, mapl_verify
cat_ungridded_dim_names calls get_name, get_ith_dim_spec, get_num_ungridded
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_variable_dim_names calls ungridded_dim_names
add_variable calls get_variable_dim_names
add_variables calls add_variable
bundle_to_metadata calls add_variables