UnpackGridName – MAPL
UnpackGridName Subroutine
16 statements
Source File
public subroutine UnpackGridName(gridName, im, jm, date, pole)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: gridName
integer, intent(out) :: im
integer, intent(out) :: jm
character(len=2), intent(out) :: date
character(len=2), intent(out) :: pole
Called by
Call graph
create_grid calls unpackgridname
process_command_line calls create_grid
main calls process_command_line
regrid_util calls main