update_source – MAPL
update_source Subroutine
13 statements
Source File
private recursive subroutine update_source(this, rc)
Type Bound
CouplerMetaComponent
Arguments
Type Intent Optional Attributes Name
class(CouplerMetaComponent) :: this
integer, intent(out) :: rc
Calls
Called by
Source Code
   recursive subroutine update_source(this, rc)
      class(CouplerMetaComponent) :: this
      integer, intent(out) :: rc
      integer :: status
      _RETURN_UNLESS(associated(this%source))
      call this%source%run(phase_idx=GENERIC_COUPLER_UPDATE, _RC)
      _RETURN(_SUCCESS)
   end subroutine update_source
Call graph
update_source calls run, mapl_return, mapl_verify
run calls run, mapl_return, mapl_verify, ESMF_GridCompRun, run_export_couplers, run_import_couplers
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_export_couplers calls run_export_couplers
run_import_couplers calls run_import_couplers
update calls update_source, update