update_item_string – MAPL
update_item_string Function
9 statements
Source File
private function update_item_string(a, b)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(inout), allocatable :: a
character(len=:), intent(in), allocatable :: b
Return Value logical
Calls
Called by
Source Code
   logical function update_item_string(a, b)
      character(:), allocatable, intent(inout) :: a
      character(:), allocatable, intent(in) :: b
      update_item_string = .false.
      if (.not. match(a, b)) then
         a = b
         update_item_string = .true.
      end if
   end function update_item_string
Call graph
update_item_string calls match
match calls match_geom, match_string, match_typekind
match_geom calls mapl_samegeom
match_string calls mirror
mapl_samegeom calls same_geom
update_item calls update_item_string
make_extension_safely calls update_item
make_extension calls make_extension_safely