update – MAPL
update Subroutine
19 statements
Source File
private recursive subroutine update(this, importState, exportState, clock, rc)
Type Bound
CouplerMetaComponent
Arguments
Type Intent Optional Attributes Name
class(CouplerMetaComponent), intent(inout) :: this
type(ESMF_State), intent(inout) :: importState
type(ESMF_State), intent(inout) :: exportState
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine update(this, importState, exportState, clock, rc)
      class(CouplerMetaComponent), intent(inout) :: this
      type(ESMF_State), intent(inout) :: importState
      type(ESMF_State), intent(inout) :: exportState
      type(ESMF_Clock), intent(inout) :: clock
      integer, optional, intent(out) :: rc
      integer :: status
      _RETURN_IF(this%is_up_to_date())
!#      call this%propagate_attributes(_RC)
      call this%update_source(_RC)
      call this%action%run(_RC)
      call this%set_up_to_date()
      _RETURN(_SUCCESS)
   end subroutine update
Call graph
update calls is_up_to_date, mapl_return, mapl_verify, set_up_to_date, update_source, run, update
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
update_source calls mapl_return, mapl_verify, run
run calls run, mapl_return, mapl_verify, ESMF_GridCompRun, run_export_couplers, run_import_couplers
get_error_message calls at, insert
mapl_throw_exception calls initialize