update – MAPL
update Subroutine
15 statements
Source File
private recursive subroutine update(gridcomp, importState, exportState, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gridcomp
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine update(gridcomp, importState, exportState, clock, rc)
      type(ESMF_GridComp) :: gridcomp
      type(ESMF_State) :: importState
      type(ESMF_State) :: exportState
      type(ESMF_Clock) :: clock
      integer, intent(out) :: rc
      integer :: status
      type(CouplerMetaComponent), pointer :: meta
      meta => get_coupler_meta(gridcomp, _RC)
      call meta%update(importState, exportState, clock, _RC)
      _RETURN(_SUCCESS)
   end subroutine update
Call graph
update calls get_coupler_meta, mapl_return, mapl_verify, update, is_up_to_date, set_up_to_date, update_source, run
get_coupler_meta calls mapl_return, mapl_assert, mapl_usercompgetinternalstate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
update_source calls mapl_return, mapl_verify, run
run calls run
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception