update – MAPL
update Subroutine
44 statements
Source File
public subroutine update(this, importState, exportState, clock, rc)
Uses
ESMF
Type Bound
ConvertUnitsAction
Arguments
Type Intent Optional Attributes Name
class(ConvertUnitsAction), intent(inout) :: this
type(ESMF_State) :: importState
type(ESMF_State) :: exportState
type(ESMF_Clock) :: clock
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine update(this, importState, exportState, clock, rc)
      use esmf
      class(ConvertUnitsAction), intent(inout) :: this
      type(ESMF_State)      :: importState
      type(ESMF_State)      :: exportState
      type(ESMF_Clock)      :: clock
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_TypeKind_Flag) :: typekind
      type(ESMF_Field) :: f_in, f_out
      real(kind=ESMF_KIND_R4), pointer :: x4_in(:)
      real(kind=ESMF_KIND_R4), pointer :: x4_out(:)
      real(kind=ESMF_KIND_R8), pointer :: x8_in(:)
      real(kind=ESMF_KIND_R8), pointer :: x8_out(:)
      call ESMF_StateGet(importState, itemName='import[1]', field=f_in, _RC)
      call ESMF_StateGet(exportState, itemName='export[1]', field=f_out, _RC)
      call ESMF_FieldGet(f_in, typekind=typekind, _RC)
      if (typekind == ESMF_TYPEKIND_R4) then
         call assign_fptr(f_in, x4_in, _RC)
         call assign_fptr(f_out, x4_out, _RC)
         x4_out = this%converter%convert(x4_in)
         _RETURN(_SUCCESS)
      end if
      if (typekind == ESMF_TYPEKIND_R8) then
         call assign_fptr(f_in, x8_in, _RC)
         call assign_fptr(f_out, x8_out, _RC)
         x8_out = this%converter%convert(x8_in)
         _RETURN(_SUCCESS)
      end if
      _FAIL('unsupported typekind')
      _UNUSED_DUMMY(clock)
   end subroutine update
Call graph
update calls convert, esmf_fieldget, esmf_stateget, assign_fptr, mapl_assert, mapl_return, mapl_verify
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception