v_at_32 – MAPL
v_at_32 Function
9 statements
Source File
private function v_at_32(this, i, unused, rc) result(res)
Type Bound
CommGroupDescriptionVector
Arguments
Type Intent Optional Attributes Name
class(CommGroupDescriptionVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(CommGroupDescription), pointer
Calls
Called by
Call graph
v_at_32 calls v_at_size_kind
compute_color calls at
split calls at, compute_color
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls split
new_multigroupserver calls split
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator
main calls initialize, create_member_subcommunicator
run_ensemble calls create_member_subcommunicator
time_ave calls initialize
ut_regridding calls initialize