v_erase_range – MAPL
v_erase_range Subroutine
14 statements
Source File
private subroutine v_erase_range(this, first, last)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(inout), target :: this
type(FileMetadataUtilsVectorIterator), intent(in) :: first
type(FileMetadataUtilsVectorIterator), intent(in) :: last
Called by
Call graph
find_ calls erase
v_erase_one calls erase
create_bracketing_fields calls find_
create_primary_field calls find_
detect_metadata calls find_
make_metadata calls find_
makemetadata calls find_
mapl_create_bundle_from_metdata_id calls find_
mapl_read_bundle calls find_, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find_
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls create_primary_field, makemetadata
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle