v_iter_get – MAPL
v_iter_get Function
5 statements
Source File
private function v_iter_get(this) result(item)
Type Bound
MeterNodeVectorIterator
Arguments
Type Intent Optional Attributes Name
class(MeterNodeVectorIterator), intent(in) :: this
Return Value class(AbstractMeterNode), pointer
Called by
Call graph
get_exclusive calls v_iter_get
get_num_nodes calls v_iter_get
next calls v_iter_get
reset calls v_iter_get
get_num_meters calls get_num_nodes
test_count_nodes_depth_0 calls get_num_nodes
test_count_nodes_depth_1 calls get_num_nodes
test_get_exclusive calls get_exclusive
test_get_num_nodes calls get_num_nodes
test_get_num_nodes_2 calls get_num_nodes
test_node_reset calls reset
report_global_profiler calls get_num_meters
test_accumulate_nested calls get_num_meters
test_accumulate_sub calls get_num_meters
test_start_one calls get_num_meters
finalize calls report_global_profiler