valuestring_mismatch – MAPL
valuestring_mismatch Function
6 statements
Source File
public function valuestring_mismatch(actual, expected) result(error_message)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: actual
character(len=*), intent(in) :: expected
Return Value character(len=:), allocatable
Called by
Source Code
   function valuestring_mismatch(actual, expected) result(error_message)
      character(len=:), allocatable :: error_message
      character(len=*), intent(in) :: actual
      character(len=*), intent(in) :: expected
      error_message = 'Actual valuestring, "' // actual // &
         '", does not match expected valuestring, "' // expected // '".'
   end function valuestring_mismatch
Call graph
test_get_i4_not_found_default calls valuestring_mismatch
test_get_i4_value_equals_default calls valuestring_mismatch
test_get_i4_value_not_equal_default calls valuestring_mismatch
test_make_valuestring_i4 calls valuestring_mismatch
test_make_valuestring_i4seq calls valuestring_mismatch
test_make_valuestring_i8 calls valuestring_mismatch
test_make_valuestring_i8seq calls valuestring_mismatch
test_make_valuestring_logical calls valuestring_mismatch
test_make_valuestring_logicalseq calls valuestring_mismatch
test_make_valuestring_r4 calls valuestring_mismatch
test_make_valuestring_r4seq calls valuestring_mismatch
test_make_valuestring_r8 calls valuestring_mismatch
test_make_valuestring_r8seq calls valuestring_mismatch
test_make_valuestring_string calls valuestring_mismatch