var_has_missing_value – MAPL
var_has_missing_value Function
16 statements
Source File
private function var_has_missing_value(this, var_name, rc)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function var_has_missing_value(this,var_name,rc)
      class(FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: fname
      type(Variable), pointer :: var
      fname = this%get_file_name(_RC)
      var => this%get_variable(var_name,_RC)
      _ASSERT(associated(var),"no variable named "//var_name//" in "//fname)
      var_has_missing_value = var%is_attribute_present("_FillValue")
      _RETURN(_SUCCESS)
   end function var_has_missing_value
Call graph
var_has_missing_value calls mapl_assert, get_file_name, get_variable, is_attribute_present, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file_name calls mapl_return
get_variable calls mapl_return, mapl_verify, get_variable, at
is_attribute_present calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
swap_undef_value calls var_has_missing_value
process_data_from_file calls swap_undef_value
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
main calls mapl_read_bundle
run_ calls mapl_extdatareadprefetch
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle