Variable_deserialize – MAPL
Variable_deserialize Subroutine
54 statements
Source File
public subroutine Variable_deserialize(buffer, var, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(Variable), intent(inout) :: var
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine Variable_deserialize(buffer, var, rc)
      integer, intent(in) :: buffer(:)
      type (Variable), intent(inout) :: var
      integer, optional, intent(out) :: rc
      integer :: status
      var = Variable()
      call deserialize(var, buffer, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   contains
      subroutine deserialize(this, buffer, rc)
         class (Variable), intent(inout) :: this
         integer,intent(in) :: buffer(:)
         integer, optional, intent(out) :: rc
         integer :: n,length, v_type
         integer :: status
         n = 1
         call deserialize_intrinsic(buffer(n:),length)
         _ASSERT(length == size(buffer), "length does not match")
         length = serialize_buffer_length(length)
         n = n+length
         call deserialize_intrinsic(buffer(n:),v_type)
         length = serialize_buffer_length(v_type)
         n = n+length
         call deserialize_intrinsic(buffer(n:),this%type)
         length = serialize_buffer_length(this%type)
         n = n+length
         call StringVector_deserialize(buffer(n:), this%dimensions, status)
         _VERIFY(status)
         call deserialize_intrinsic(buffer(n:),length)
         n = n + length
         call deserialize_intrinsic(buffer(n:),length)
         call StringAttributeMap_deserialize(buffer(n:n+length-1),this%attributes, status)
         _VERIFY(status)
         n = n + length
         call deserialize_intrinsic(buffer(n:),length)
         call UnlimitedEntity_deserialize(buffer(n:(n+length-1)), this%const_value, status)
         _VERIFY(status)
         n = n + length
         call deserialize_intrinsic(buffer(n:),this%deflation)
         length = serialize_buffer_length(this%deflation)
         n = n + length
         call deserialize_intrinsic(buffer(n:),this%quantize_algorithm)
         length = serialize_buffer_length(this%quantize_algorithm)
         n = n + length
         call deserialize_intrinsic(buffer(n:),this%quantize_level)
         length = serialize_buffer_length(this%quantize_level)
         n = n + length
         call deserialize_intrinsic(buffer(n:),this%chunksizes)
         _RETURN(_SUCCESS)
      end subroutine deserialize
  end subroutine Variable_deserialize
Call graph
variable_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, stringattributemap_deserialize, stringvector_deserialize, unlimitedentity_deserialize
mapl_return calls at, insert, mapl_throw_exception
mapl_verify calls mapl_throw_exception
stringattributemap_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, insert, attribute_deserialize
stringvector_deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return, push_back, stringvector
unlimitedentity_deserialize calls deserialize_intrinsic, mapl_assert, serialize_buffer_length, mapl_return, mapl_verify, get_rank, set
attribute_deserialize calls mapl_return, mapl_verify, unlimitedentity_deserialize
coordinatevariable_deserialize calls variable_deserialize
filemetadata_deserialize calls variable_deserialize, stringvariablemap_deserialize
stringvariablemap_deserialize calls variable_deserialize, coordinatevariable_deserialize
test_serialize calls variable_deserialize, filemetadata_deserialize, coordinatevariable_deserialize
historycollectionvector_deserialize calls filemetadata_deserialize