vector_insert_range – MAPL
vector_insert_range Function
20 statements
Source File
private function vector_insert_range(this, pos, first, last, value) result(iter)
Type Bound
ConnectionVector
Arguments
Type Intent Optional Attributes Name
class(ConnectionVector), intent(inout), target :: this
type(ConnectionVectorIterator), intent(in) :: pos
type(ConnectionVectorIterator), intent(in) :: first
type(ConnectionVectorIterator), intent(in) :: last
class(Connection), intent(in) :: value
Return Value type(ConnectionVectorIterator)
Calls
Called by
Call graph
vector_insert_range calls vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_default calls insert
vector_insert_one calls insert