vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
VariableSpecVector
Arguments
Type Intent Optional Attributes Name
class(VariableSpecVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_export_spec calls vector_push_back
add_internal_spec calls vector_push_back
add_spec_basic calls vector_push_back
add_var_spec calls vector_push_back
parse_var_specs calls vector_push_back
vector_new_vector_range calls vector_push_back
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic
variablespecvector calls vector_new_vector_range
parse_component_spec calls parse_var_specs
vector_insert_count_default calls insert
vector_insert_one calls insert
add_import_spec_legacy calls mapl_addspec
add_spec_explicit calls mapl_addspec
setservices_ calls parse_component_spec