vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(inout) :: this
class(TextColumn), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_column calls vector_push_back
vector_new_vector_range calls vector_push_back
textcolumnvector calls vector_new_vector_range
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column, generate_report, finalize
finalize calls mapl_genericfinalize, report_profile, report_global_profiler
finalize_ calls mapl_genericfinalize
start calls report_profile
time_ave calls generate_report, finalize
finalize_io_clients_servers calls finalize
run calls finalize
regrid_util calls main
ut_regridding calls finalize