vector_insert_count_default – MAPL
vector_insert_count_default Function
8 statements
Source File
private function vector_insert_count_default(this, pos, count, value) result(iter)
Type Bound
VirtualConnectionPtVector
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPtVector), intent(inout), target :: this
type(VirtualConnectionPtVectorIterator), intent(in) :: pos
integer, intent(in) :: count
type(VirtualConnectionPt), intent(in) :: value
Return Value type(VirtualConnectionPtVectorIterator)
Calls
Call graph
vector_insert_count_default calls insert
vector_insert_list calls vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity