vector_capacity – MAPL
vector_capacity Function
10 statements
Source File
private pure function vector_capacity(this) result(capacity)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(in) :: this
Return Value integer(kind=GFTL_SIZE_KIND)
Called by
Call graph
vector_grow_to calls vector_capacity
vector_reserve_size_kind calls vector_capacity
vector_shrink_to_fit calls vector_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_column calls vector_push_back
vector_new_vector_range calls vector_push_back
vector_reserve_default calls reserve
vector_resize_size_kind calls reserve
textcolumnvector calls vector_new_vector_range
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
vector_insert_count_default calls insert
vector_insert_one calls insert
main calls add_column