vector_copy_from_array – MAPL
vector_copy_from_array Subroutine
10 statements
Source File
private subroutine vector_copy_from_array(this, array)
Type Bound
RoutehandleVector
Arguments
Type Intent Optional Attributes Name
class(RoutehandleVector), intent(inout) :: this
type(ESMF_RouteHandle), intent(in) :: array(:)
Calls
Call graph
vector_copy_from_array calls reserve
vector_reserve_size_kind calls vector_capacity, vector_max_size, vector_set_capacity