vector_begin – MAPL
vector_begin Function
10 statements
Source File
private function vector_begin(this) result(iter)
Type Bound
IoBundleNGVector
Arguments
Type Intent Optional Attributes Name
class(IoBundleNGVector), intent(in), target :: this
Return Value type(IoBundleNGVectorIterator)
Called by
Call graph
mapl_extdatacreatecfio calls vector_begin
mapl_extdatadestroycfio calls vector_begin
run_ calls vector_begin, mapl_extdatacreatecfio, mapl_extdatadestroycfio
vector_iter_begin calls vector_begin
vector_iter_ftn_begin calls vector_begin
vector_rend calls vector_begin
begin calls vector_iter_begin
ftn_begin calls vector_iter_ftn_begin