vector_begin – MAPL
vector_begin Function
10 statements
Source File
private function vector_begin(this) result(iter)
Type Bound
GeomFactoryVector
Arguments
Type Intent Optional Attributes Name
class(GeomFactoryVector), intent(in), target :: this
Return Value type(GeomFactoryVectorIterator)
Called by
Call graph
find_factory calls vector_begin
vector_iter_begin calls vector_begin
vector_iter_ftn_begin calls vector_begin
vector_rend calls vector_begin
begin calls vector_iter_begin
ftn_begin calls vector_iter_ftn_begin
make_geom_spec_from_hconfig calls find_factory
make_geom_spec_from_metadata calls find_factory