vector_new_vector_range – MAPL
vector_new_vector_range Function
11 statements
Source File
private function vector_new_vector_range(first, last) result(v)
Arguments
Type Intent Optional Attributes Name
type(RoutehandleSpecVectorIterator), intent(in) :: first
type(RoutehandleSpecVectorIterator), intent(in) :: last
Return Value type(RoutehandleSpecVector)
Calls
Called by
Call graph
vector_new_vector_range calls of, vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
routehandlespecvector calls vector_new_vector_range