vector_iter_next – MAPL
vector_iter_next Subroutine
4 statements
Source File
private subroutine vector_iter_next(this)
Type Bound
IoBundleNGVectorIterator
Arguments
Type Intent Optional Attributes Name
class(IoBundleNGVectorIterator), intent(inout) :: this
Called by
Call graph
mapl_extdatacreatecfio calls vector_iter_next
mapl_extdatadestroycfio calls vector_iter_next
run_ calls vector_iter_next, mapl_extdatacreatecfio, mapl_extdatadestroycfio
vector_find_if_not calls vector_iter_next
vector_find_if calls vector_iter_next
vector_riter_prev calls vector_iter_next
find_if_not calls vector_find_if_not
find_if calls vector_find_if