vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
RegridderSpecVector
Arguments
Type Intent Optional Attributes Name
class(RegridderSpecVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_regridder calls vector_push_back
vector_new_vector_range calls vector_push_back
regridderspecvector calls vector_new_vector_range
get_regridder calls add_regridder
vector_insert_count_default calls insert
vector_insert_one calls insert
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder