vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_column calls vector_push_back
vector_new_vector_range calls vector_push_back
textcolumnvector calls vector_new_vector_range
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
vector_insert_count_default calls insert
vector_insert_one calls insert
main calls add_column, generate_report
finalize calls mapl_genericfinalize, report_profile, report_global_profiler
finalize_ calls mapl_genericfinalize
start calls report_profile
time_ave calls generate_report