vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
DimSpecVector
Arguments
Type Intent Optional Attributes Name
class(DimSpecVector), intent(inout) :: this
type(UngriddedDimSpec), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_dim_spec calls vector_push_back
new_ungriddeddimsspec_arr calls vector_push_back
vector_new_vector_range calls vector_push_back
dimspecvector calls vector_new_vector_range
ungriddeddimsspec calls new_ungriddeddimsspec_arr
parse_var_specs calls add_dim_spec
test_field_set_info calls add_dim_spec
parse_component_spec calls parse_var_specs
setservices_ calls parse_component_spec