vector_set_capacity – MAPL
vector_set_capacity Subroutine
21 statements
Source File
private subroutine vector_set_capacity(this, capacity)
Type Bound
ActualPtVector
Arguments
Type Intent Optional Attributes Name
class(ActualPtVector), intent(inout), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Called by
Call graph
vector_grow_to calls vector_set_capacity
vector_reserve_size_kind calls vector_set_capacity
vector_shrink_to_fit calls vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_extension_pt calls vector_push_back
make_dependencies calls vector_push_back
vector_copy_from_array calls reserve
vector_new_vector_range calls vector_push_back
vector_reserve_default calls reserve
vector_resize_size_kind calls reserve
actualptvector calls vector_new_vector_range
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt
make_itemspec calls make_dependencies
vector_insert_count_default calls insert
vector_insert_one calls insert