vector_iter_of_offset_size_kind – MAPL
vector_iter_of_offset_size_kind Function
6 statements
Source File
private function vector_iter_of_offset_size_kind(this, i) result(ptr)
Type Bound
IoBundleNGVectorIterator
Arguments
Type Intent Optional Attributes Name
class(IoBundleNGVectorIterator), intent(in) :: this
integer(kind=selected_int_kind(18)), intent(in) :: i
Return Value type(ExtDataNG_IOBundle), pointer
Called by
Call graph
mapl_extdatacreatecfio calls of
mapl_extdatadestroycfio calls of
run_ calls of, mapl_extdatacreatecfio, mapl_extdatadestroycfio
vector_find_if_not calls of
vector_find_if calls of
vector_new_vector_range calls of
vector_riter_of_offset_default calls of
vector_riter_of_offset_size_kind calls of
vector_riter_of calls of
find_if_not calls vector_find_if_not
find_if calls vector_find_if
iobundlengvector calls vector_new_vector_range
vector_reverse_find_if_not calls of
vector_reverse_find_if calls of