vector_reverse_find_if_not – MAPL
vector_reverse_find_if_not Function
18 statements
Source File
private function vector_reverse_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(RegridderSpecVectorRIterator), intent(in) :: first
type(RegridderSpecVectorRIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(RegridderSpec), intent(in) :: item
Return Value logical
Return Value type(RegridderSpecVectorRIterator)
Calls
Called by
Call graph
vector_reverse_find_if_not calls of, vector_riter_next
vector_riter_next calls vector_iter_prev
vector_riter_of_offset_default calls of
find_if_not calls vector_reverse_find_if_not