vector_reverse_find_basic – MAPL
vector_reverse_find_basic Function
14 statements
Source File
private function vector_reverse_find_basic(first, last, value) result(iter)
Arguments
Type Intent Optional Attributes Name
type(RoutehandleSpecVectorRIterator), intent(in) :: first
type(RoutehandleSpecVectorRIterator), intent(in) :: last
type(RoutehandleSpec), intent(in) :: value
Return Value type(RoutehandleSpecVectorRIterator)
Calls
Called by
Call graph
vector_reverse_find_basic calls of, vector_riter_next
vector_riter_next calls vector_iter_prev
vector_riter_of_offset_default calls of
find calls vector_reverse_find_basic