vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
RegridderSpecVector
Arguments
Type Intent Optional Attributes Name
class(RegridderSpecVector), intent(inout) :: this
type(RegridderSpec), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_regridder calls vector_push_back
vector_new_vector_range calls vector_push_back
regridderspecvector calls vector_new_vector_range
get_regridder calls add_regridder
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder
regridaction calls new_scalarregridaction