vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
RegridderFactoryVector
Arguments
Type Intent Optional Attributes Name
class(RegridderFactoryVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_factory calls vector_push_back
vector_new_vector_range calls vector_push_back
regridderfactoryvector calls vector_new_vector_range
new_regriddermanager calls add_factory
vector_insert_count_default calls insert
vector_insert_one calls insert
regriddermanager calls new_regriddermanager