vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
StateItemVector
Arguments
Type Intent Optional Attributes Name
class(StateItemVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_item_spec_actual calls vector_push_back
vector_new_vector_range calls vector_push_back
stateitemvector calls vector_new_vector_range
vector_insert_count_default calls insert
vector_insert_one calls insert
add_item_spec_virtual calls add_item_spec
add_item_spec_virtual_override calls add_item_spec
extend_ calls add_item_spec
init_post_advertise calls add_item_spec
initialize_advertise calls add_item_spec
test_add_item_duplicate_fail calls add_item_spec
test_connect calls add_item_spec
test_connect_chain calls add_item_spec
test_create_extension calls add_item_spec
test_do_not_propagate_import calls add_item_spec
test_e2e_preserve_actual_pt calls add_item_spec
test_export_to_export_connection calls add_item_spec
test_get_item_spec_found calls add_item_spec
test_get_item_spec_multi calls add_item_spec
test_import_from_child calls add_item_spec
test_import_from_parent calls add_item_spec
test_internal_activation calls add_item_spec
test_internal_to_export_connection calls add_item_spec
test_multi_import calls add_item_spec
test_propagate_import calls add_item_spec
test_sibling_activation calls add_item_spec