vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
ActualPtVector
Arguments
Type Intent Optional Attributes Name
class(ActualPtVector), intent(inout) :: this
type(ActualConnectionPt), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_extension_pt calls vector_push_back
make_dependencies calls vector_push_back
vector_new_vector_range calls vector_push_back
actualptvector calls vector_new_vector_range
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt, link_item_spec
make_itemspec calls make_dependencies
initialize_advertise calls make_itemspec
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual
connect_export_to_export calls link_item_spec
initialize calls initialize_advertise