vector_riter_next_n_size_kind – MAPL
vector_riter_next_n_size_kind Function
8 statements
Source File
private function vector_riter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(RegridderFactoryVectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(RegridderFactoryVectorRIterator)
Calls
Called by
Call graph
vector_riter_next_n_size_kind calls add
vector_riter_add_n_size_kind calls sub
next calls vector_riter_next_n_size_kind, vector_riter_next_1, vector_iter_next_1
vector_iter_next_1 calls next
vector_riter_next_1 calls next