vector_resize_size_kind – MAPL
vector_resize_size_kind Subroutine
39 statements
Source File
private subroutine vector_resize_size_kind(this, count, unused, value, rc)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: count
type(KeywordEnforcer), intent(in), optional :: unused
class(TextColumn), intent(in), optional :: value
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_resize_size_kind calls reserve
vector_reserve_size_kind calls vector_capacity, vector_max_size, vector_set_capacity
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_push_back calls resize
vector_resize_default calls resize
textcolumnvector calls vector_new_vector_copy, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_range
add_column calls vector_push_back
vector_new_vector_range calls vector_push_back
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column