vector_begin – MAPL
vector_begin Function
10 statements
Source File
private function vector_begin(this) result(iter)
Type Bound
RegridderSpecVector
Arguments
Type Intent Optional Attributes Name
class(RegridderSpecVector), intent(in), target :: this
Return Value type(RegridderSpecVectorIterator)
Called by
Call graph
delete_regridder calls vector_begin
get_regridder calls vector_begin
vector_iter_begin calls vector_begin
vector_iter_ftn_begin calls vector_begin
vector_rend calls vector_begin
begin calls vector_iter_begin
ftn_begin calls vector_iter_ftn_begin
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder
regridaction calls new_scalarregridaction
make_action calls regridaction