vector_riter_add_n_size_kind – MAPL
vector_riter_add_n_size_kind Subroutine
6 statements
Source File
private subroutine vector_riter_add_n_size_kind(this, n)
Type Bound
RegridderVectorRIterator
Arguments
Type Intent Optional Attributes Name
class(RegridderVectorRIterator), intent(inout) :: this
integer(kind=selected_int_kind(18)), intent(in) :: n
Calls
Called by
Call graph
vector_riter_add_n_size_kind calls sub
vector_riter_advance_default calls add
vector_riter_advance_size_kind calls add
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add
advance calls vector_riter_advance_default, vector_riter_advance_size_kind
next calls vector_riter_next_n_default, vector_riter_next_n_size_kind
vector_iter_next_1 calls next
vector_riter_next_1 calls next