vector_ftn_begin – MAPL
vector_ftn_begin Function
10 statements
Source File
private function vector_ftn_begin(this) result(iter)
Type Bound
ComponentDriverVector
Arguments
Type Intent Optional Attributes Name
class(ComponentDriverVector), intent(in), target :: this
Return Value type(ComponentDriverVectorIterator)
Called by
Call graph
run_export_couplers calls vector_ftn_begin, run_export_couplers
run_import_couplers calls vector_ftn_begin, run_import_couplers
run calls run_export_couplers, run_import_couplers, run