vector_new_vector_initializer_list – MAPL
vector_new_vector_initializer_list Function
10 statements
Source File
private function vector_new_vector_initializer_list(il) result(v)
Arguments
Type Intent Optional Attributes Name
type(ExtDataNG_IOBundle), intent(in), dimension(:) :: il
Return Value type(IoBundleNGVector)
Calls
Called by
Call graph
vector_new_vector_initializer_list calls resize
vector_resize_size_kind calls reserve
iobundlengvector calls vector_new_vector_initializer_list