vector_insert_list – MAPL
vector_insert_list Function
18 statements
Source File
private function vector_insert_list(this, pos, values) result(iter)
Type Bound
RegridderSpecVector
Arguments
Type Intent Optional Attributes Name
class(RegridderSpecVector), intent(inout), target :: this
type(RegridderSpecVectorIterator), intent(in) :: pos
type(RegridderSpec), intent(in) :: values(:)
Return Value type(RegridderSpecVectorIterator)
Calls
Called by
Call graph
vector_insert_list calls vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_default calls insert
vector_insert_one calls insert