vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
RoutehandleSpecVector
Arguments
Type Intent Optional Attributes Name
class(RoutehandleSpecVector), intent(inout) :: this
type(RoutehandleSpec), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_routehandle calls vector_push_back
vector_new_vector_range calls vector_push_back
routehandlespecvector calls vector_new_vector_range
get_routehandle calls add_routehandle
make_regridder_typesafe calls get_routehandle