vector_iter_prev – MAPL
vector_iter_prev Subroutine
4 statements
Source File
private subroutine vector_iter_prev(this)
Type Bound
GeomSpecVectorIterator
Arguments
Type Intent Optional Attributes Name
class(GeomSpecVectorIterator), intent(inout) :: this
Called by
Call graph
vector_riter_next calls vector_iter_prev
vector_reverse_find_basic calls vector_riter_next
vector_reverse_find_if_not calls vector_riter_next
vector_reverse_find_if calls vector_riter_next
find_if_not calls vector_reverse_find_if_not
find_if calls vector_reverse_find_if
find calls vector_reverse_find_basic