vector_resize_size_kind – MAPL
vector_resize_size_kind Subroutine
38 statements
Source File
private subroutine vector_resize_size_kind(this, count, unused, value, rc)
Type Bound
DimSpecVector
Arguments
Type Intent Optional Attributes Name
class(DimSpecVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: count
type(KeywordEnforcer), intent(in), optional :: unused
type(UngriddedDimSpec), intent(in), optional :: value
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_resize_size_kind calls reserve
vector_reserve_size_kind calls vector_capacity, vector_max_size, vector_set_capacity
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_initializer_list calls resize
vector_push_back calls resize
vector_resize_default calls resize
dimspecvector calls vector_new_vector_copy, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_initializer_list, vector_new_vector_range
add_dim_spec calls vector_push_back
new_ungriddeddimsspec_arr calls vector_push_back
vector_new_vector_range calls vector_push_back
ungriddeddimsspec calls new_ungriddeddimsspec_arr
parse_var_specs calls add_dim_spec
test_field_set_info calls add_dim_spec