vector_back – MAPL
vector_back Function
6 statements
Source File
private function vector_back(this) result(res)
Type Bound
RegridderVector
Arguments
Type Intent Optional Attributes Name
class(RegridderVector), intent(in), target :: this
Return Value class(Regridder), pointer
Called by
Call graph
get_regridder calls vector_back
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder
regridaction calls new_scalarregridaction
make_action calls regridaction