vector_of_size_kind – MAPL
vector_of_size_kind Function
7 statements
Source File
private function vector_of_size_kind(this, i) result(res)
Type Bound
DimSpecVector
Arguments
Type Intent Optional Attributes Name
class(DimSpecVector), intent(in), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: i
Return Value type(UngriddedDimSpec), pointer
Called by
Call graph
equal_to calls of
get_bounds calls of
get_ith_dim_spec calls at
operator(==) calls equal_to
get_ungridded_bounds calls get_bounds
make_info calls get_ith_dim_spec
allocate calls get_ungridded_bounds
set_info calls make_info