vector_resize_size_kind – MAPL
vector_resize_size_kind Subroutine
38 statements
Source File
private subroutine vector_resize_size_kind(this, count, unused, value, rc)
Type Bound
VariableSpecVector
Arguments
Type Intent Optional Attributes Name
class(VariableSpecVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: count
type(KeywordEnforcer), intent(in), optional :: unused
type(VariableSpec), intent(in), optional :: value
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_resize_size_kind calls reserve
vector_reserve_size_kind calls vector_capacity, vector_max_size, vector_set_capacity
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_initializer_list calls resize
vector_push_back calls resize
vector_resize_default calls resize
variablespecvector calls vector_new_vector_copy, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_initializer_list, vector_new_vector_range
add_export_spec calls vector_push_back
add_internal_spec calls vector_push_back
add_spec_basic calls vector_push_back
add_var_spec calls vector_push_back
parse_var_specs calls vector_push_back
vector_new_vector_range calls vector_push_back
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic
parse_component_spec calls parse_var_specs