vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
RoutehandleSpecVector
Arguments
Type Intent Optional Attributes Name
class(RoutehandleSpecVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_routehandle calls vector_push_back
vector_new_vector_range calls vector_push_back
routehandlespecvector calls vector_new_vector_range
get_routehandle calls add_routehandle
vector_insert_count_default calls insert
vector_insert_one calls insert
make_regridder_typesafe calls get_routehandle