vector_begin – MAPL
vector_begin Function
10 statements
Source File
private function vector_begin(this) result(iter)
Type Bound
RoutehandleSpecVector
Arguments
Type Intent Optional Attributes Name
class(RoutehandleSpecVector), intent(in), target :: this
Return Value type(RoutehandleSpecVectorIterator)
Called by
Call graph
add_routehandle calls vector_begin
delete_routehandle calls vector_begin
get_routehandle calls vector_begin, add_routehandle
vector_iter_begin calls vector_begin
vector_iter_ftn_begin calls vector_begin
vector_rend calls vector_begin
begin calls vector_iter_begin
ftn_begin calls vector_iter_ftn_begin
make_regridder_typesafe calls get_routehandle
make_regridder calls make_regridder