vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
ActualPtVector
Arguments
Type Intent Optional Attributes Name
class(ActualPtVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_extension_pt calls vector_push_back
make_dependencies calls vector_push_back
vector_new_vector_range calls vector_push_back
actualptvector calls vector_new_vector_range
add_item_spec_virtual_override calls add_extension_pt
link_item_spec_virtual calls add_extension_pt
make_itemspec calls make_dependencies
vector_insert_count_default calls insert
vector_insert_one calls insert
initialize_advertise calls make_itemspec
propagate_exports_virtual_pt calls link_item_spec_virtual
propagate_unsatisfied_imports_virtual_pt calls link_item_spec_virtual