vector_iter_of_offset_size_kind – MAPL
vector_iter_of_offset_size_kind Function
6 statements
Source File
private function vector_iter_of_offset_size_kind(this, i) result(ptr)
Type Bound
ComponentDriverVectorIterator
Arguments
Type Intent Optional Attributes Name
class(ComponentDriverVectorIterator), intent(in) :: this
integer(kind=selected_int_kind(18)), intent(in) :: i
Return Value class(ComponentDriver), pointer
Called by
Call graph
run_export_couplers calls of, run_export_couplers
run_import_couplers calls of, run_import_couplers
vector_find_if_not calls of
vector_find_if calls of
vector_new_vector_range calls of
vector_riter_of_offset_default calls of
vector_riter_of_offset_size_kind calls of
vector_riter_of calls of
componentdrivervector calls vector_new_vector_range
find_if_not calls vector_find_if_not
find_if calls vector_find_if
run calls run_export_couplers, run_import_couplers
vector_reverse_find_if_not calls of
vector_reverse_find_if calls of