vector_of_size_kind – MAPL
vector_of_size_kind Function
7 statements
Source File
private function vector_of_size_kind(this, i) result(res)
Type Bound
RegridderFactoryVector
Arguments
Type Intent Optional Attributes Name
class(RegridderFactoryVector), intent(in), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: i
Return Value class(RegridderFactory), pointer
Called by
Call graph
make_regridder calls of
get_regridder calls make_regridder
new_scalarregridaction calls get_regridder
test_basic calls get_regridder
test_do_not_reuse_regridder calls get_regridder
test_regrid_3d calls get_regridder
test_regrid_values calls get_regridder
test_reuse_regridder calls get_regridder