vector_of_size_kind – MAPL
vector_of_size_kind Function
7 statements
Source File
private function vector_of_size_kind(this, i) result(res)
Type Bound
ActualPtVector
Arguments
Type Intent Optional Attributes Name
class(ActualPtVector), intent(in), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: i
Return Value type(ActualConnectionPt), pointer
Called by
Call graph
activate_dependencies calls of
check_virtual calls of
find_closest_spec calls of
get_actual_pt_specptrs calls of
propagate_exports_virtual_pt calls of
propagate_unsatisfied_imports_virtual_pt calls of
write_formatted calls of
check calls check_virtual
connect calls get_actual_pt_specptrs, connect_sibling
connect_sibling calls activate_dependencies, find_closest_spec, get_actual_pt_specptrs
initialize_advertise calls propagate_exports, propagate_unsatisfied_imports
propagate_exports_all calls propagate_exports
propagate_exports_child calls propagate_exports
propagate_unsatisfied_imports_all calls propagate_unsatisfied_imports
propagate_unsatisfied_imports_child calls propagate_unsatisfied_imports
test_do_not_propagate_import calls propagate_unsatisfied_imports
test_export_to_export_connection calls check
test_get_item_spec_found calls check
test_get_item_spec_multi calls check
test_internal_to_export_connection calls check
test_multi_import calls propagate_unsatisfied_imports
test_propagate_import calls propagate_unsatisfied_imports
test_sibling_activation calls check, propagate_exports, propagate_unsatisfied_imports