vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
VariableSpecVector
Arguments
Type Intent Optional Attributes Name
class(VariableSpecVector), intent(inout) :: this
type(VariableSpec), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_export_spec calls vector_push_back
add_internal_spec calls vector_push_back
add_spec_basic calls vector_push_back
add_var_spec calls vector_push_back
parse_var_specs calls vector_push_back
vector_new_vector_range calls vector_push_back
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic, add_spec_explicit
variablespecvector calls vector_new_vector_range
parse_component_spec calls parse_var_specs
add_import_spec_legacy calls mapl_addspec
add_spec_explicit calls mapl_addspec
setservices_ calls parse_component_spec, setservices_
mapl_addimportspec calls add_import_spec_legacy