vector_set_capacity – MAPL
vector_set_capacity Subroutine
21 statements
Source File
private subroutine vector_set_capacity(this, capacity)
Type Bound
VariableSpecVector
Arguments
Type Intent Optional Attributes Name
class(VariableSpecVector), intent(inout), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Called by
Call graph
vector_grow_to calls vector_set_capacity
vector_reserve_size_kind calls vector_set_capacity
vector_shrink_to_fit calls vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_export_spec calls vector_push_back
add_internal_spec calls vector_push_back
add_spec_basic calls vector_push_back
add_var_spec calls vector_push_back
parse_var_specs calls vector_push_back
vector_copy_from_array calls reserve
vector_new_vector_range calls vector_push_back
vector_reserve_default calls reserve
vector_resize_size_kind calls reserve
mapl_addexportspec calls add_export_spec
mapl_addinternalspec calls add_internal_spec
mapl_addspec calls add_spec_basic
variablespecvector calls vector_new_vector_range
parse_component_spec calls parse_var_specs
vector_insert_count_default calls insert
vector_insert_one calls insert