vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
ConnectionVector
Arguments
Type Intent Optional Attributes Name
class(ConnectionVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
add_connection calls vector_push_back
parse_connections calls vector_push_back
vector_new_vector_range calls vector_push_back
connectionvector calls vector_new_vector_range
connect_all calls add_connection
parse_component_spec calls parse_connections
vector_insert_count_default calls insert
vector_insert_one calls insert
gridcomp_connect_all calls connect_all
setservices_ calls parse_component_spec