vector_iter_of_offset_size_kind – MAPL
vector_iter_of_offset_size_kind Function
6 statements
Source File
private function vector_iter_of_offset_size_kind(this, i) result(ptr)
Type Bound
GeomFactoryVectorIterator
Arguments
Type Intent Optional Attributes Name
class(GeomFactoryVectorIterator), intent(in) :: this
integer(kind=selected_int_kind(18)), intent(in) :: i
Return Value class(GeomFactory), pointer
Called by
Call graph
find_factory calls of
vector_find_if_not calls of
vector_find_if calls of
vector_new_vector_range calls of
vector_riter_of_offset_default calls of
vector_riter_of_offset_size_kind calls of
vector_riter_of calls of
find_if_not calls vector_find_if_not
find_if calls vector_find_if
geomfactoryvector calls vector_new_vector_range
make_geom_spec_from_hconfig calls find_factory
make_geom_spec_from_metadata calls find_factory
vector_reverse_find_if_not calls of
vector_reverse_find_if calls of