vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
ConnectionVector
Arguments
Type Intent Optional Attributes Name
class(ConnectionVector), intent(inout) :: this
class(Connection), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
add_connection calls vector_push_back
parse_connections calls vector_push_back
vector_new_vector_range calls vector_push_back
connectionvector calls vector_new_vector_range
connect_all calls add_connection
parse_component_spec calls parse_connections
gridcomp_connect_all calls connect_all
setservices_ calls parse_component_spec, setservices_
mapl_connectall calls gridcomp_connect_all