vector_reserve_size_kind – MAPL
vector_reserve_size_kind Subroutine
19 statements
Source File
private subroutine vector_reserve_size_kind(this, capacity, unused, rc)
Type Bound
VirtualConnectionPtVector
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPtVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
class(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_reserve_size_kind calls vector_capacity, vector_max_size, vector_set_capacity
vector_copy_from_array calls reserve
vector_reserve_default calls reserve
vector_resize_size_kind calls reserve
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_initializer_list calls resize
vector_push_back calls resize
vector_resize_default calls resize