vector_resize_size_kind – MAPL
vector_resize_size_kind Subroutine
38 statements
Source File
private subroutine vector_resize_size_kind(this, count, unused, value, rc)
Type Bound
VarConnVector
Arguments
Type Intent Optional Attributes Name
class(VarConnVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: count
type(KeywordEnforcer), intent(in), optional :: unused
type(VarConnType), intent(in), optional :: value
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_resize_size_kind calls reserve
vector_reserve_size_kind calls vector_capacity, vector_max_size, vector_set_capacity
append calls resize
vector_new_vector_copy calls resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_initializer_list calls resize
vector_push_back calls resize
vector_resize_default calls resize
varconnvector calls vector_new_vector_copy, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_initializer_list, vector_new_vector_range
mapl_addconnectivitye2e calls append
mapl_addconnectivityrename calls append
mapl_donotconnect calls append
vector_new_vector_range calls vector_push_back
mapl_addconnectivity calls mapl_addconnectivityrename
mapl_terminateimport calls mapl_donotconnect
mapl_addconnectivitymany calls mapl_addconnectivityrename
mapl_donotconnectanyimport calls mapl_donotconnect
mapl_donotconnectmany calls mapl_donotconnect
mapl_stateaddexportspecfrmchldname calls mapl_addconnectivitye2e
mapl_terminateimportallbut calls mapl_donotconnect