vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
VirtualConnectionPtVector
Arguments
Type Intent Optional Attributes Name
class(VirtualConnectionPtVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
filter calls vector_push_back
vector_new_vector_range calls vector_push_back
virtualconnectionptvector calls vector_new_vector_range
connect calls filter
vector_insert_count_default calls insert
vector_insert_one calls insert