vector_back – MAPL
vector_back Function
6 statements
Source File
private function vector_back(this) result(res)
Type Bound
StateItemVector
Arguments
Type Intent Optional Attributes Name
class(StateItemVector), intent(in), target :: this
Return Value class(StateItemSpec), pointer
Called by
Call graph
add_item_spec_actual calls vector_back
add_item_spec_virtual calls add_item_spec
add_item_spec_virtual_override calls add_item_spec
extend_ calls add_item_spec
init_post_advertise calls add_item_spec
initialize_advertise calls add_item_spec
test_add_item_duplicate_fail calls add_item_spec
test_connect calls add_item_spec
test_connect_chain calls add_item_spec
test_create_extension calls add_item_spec
test_do_not_propagate_import calls add_item_spec
test_e2e_preserve_actual_pt calls add_item_spec
test_export_to_export_connection calls add_item_spec
test_get_item_spec_found calls add_item_spec
test_get_item_spec_multi calls add_item_spec
test_import_from_child calls add_item_spec
test_import_from_parent calls add_item_spec
test_internal_activation calls add_item_spec
test_internal_to_export_connection calls add_item_spec
test_multi_import calls add_item_spec
test_propagate_import calls add_item_spec
test_sibling_activation calls add_item_spec
connect_sibling calls extend_
initialize calls initialize_advertise