vector_iter_sub_n_size_kind – MAPL
vector_iter_sub_n_size_kind Subroutine
6 statements
Source File
private subroutine vector_iter_sub_n_size_kind(this, n)
Type Bound
RegridderFactoryVectorIterator
Arguments
Type Intent Optional Attributes Name
class(RegridderFactoryVectorIterator), intent(inout) :: this
integer(kind=selected_int_kind(18)), intent(in) :: n
Called by
Call graph
vector_iter_a_minus_n_default calls sub
vector_iter_a_minus_n_size_kind calls sub
vector_iter_prev_n_default calls sub
vector_iter_prev_n_size_kind calls sub
vector_riter_add_n_default calls sub
vector_riter_add_n_size_kind calls sub
prev calls vector_iter_prev_n_default, vector_iter_prev_n_size_kind
vector_riter_advance_default calls add
vector_riter_advance_size_kind calls add
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add