wait – MAPL
wait Subroutine
10 statements
Source File
private subroutine wait(this, request_id)
Uses
pFIO_AbstractRequestHandleMod
Type Bound
MockClientThread
Arguments
Type Intent Optional Attributes Name
class(MockClientThread), intent(inout), target :: this
integer, intent(in) :: request_id
Calls
Source Code
   subroutine wait(this, request_id)
      use pFIO_AbstractRequestHandleMod
      class (MockClientThread), target, intent(inout) :: this
      integer, intent(in) :: request_id
      class(AbstractRequestHandle), pointer :: handle
      this%counter = this%counter + 1
      handle => this%get_RequestHandle(request_id)
      call handle%wait()
      call this%erase_RequestHandle(request_id)
   end subroutine wait
Call graph
wait calls erase_requesthandle, get_requesthandle
erase_requesthandle calls erase, map_find, mapl_return
get_requesthandle calls mapl_assert, map_find, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
map_find calls map_s_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
map_erase_range calls erase
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize