write_variable – MAPL
write_variable Subroutine
100 statements
Source File
public subroutine write_variable(this, var_name, local_var)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
character(len=*), intent(in) :: var_name
real, intent(in) :: local_var(:,:,:)
Calls
Called by
Call graph
write_variable calls mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_gatherv, nf90_inq_varid, nf90_put_var, mapl_verify
mapl_verify calls mapl_throw_exception
write_file calls write_variable
checkpoint_tester calls write_file