write_file – MAPL
write_file Subroutine
27 statements
Source File
public subroutine write_file(this)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
Calls
Called by
Call graph
write_file calls mpi_barrier, mapl_verify, write_level, write_variable
mapl_verify calls mapl_throw_exception
write_level calls mpi_barrier, mapl_verify, mpi_comm_rank, mpi_comm_size, mpi_gatherv, nf90_inq_varid, nf90_put_var
write_variable calls mpi_barrier, mapl_verify, mpi_comm_rank, mpi_comm_size, mpi_gatherv, nf90_inq_varid, nf90_put_var
checkpoint_tester calls write_file