write_formatted – MAPL
write_formatted Subroutine
9 statements
Source File
private subroutine write_formatted(this, unit, iotype, v_list, iostat, iomsg)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(in) :: this
integer, intent(in) :: unit
character(len=*), intent(in) :: iotype
integer, intent(in) :: v_list(:)
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Source Code
   subroutine write_formatted(this, unit, iotype, v_list, iostat, iomsg)
      class(FileMetadataUtils), intent(in) :: this
      integer, intent(in) :: unit
      character(*), intent(in) :: iotype
      integer, intent(in) :: v_list(:)
      integer, intent(out) :: iostat
      character(*), intent(inout) :: iomsg
      call this%metadata%write_formatted(unit, iotype, v_list, iostat, iomsg)
   end subroutine write_formatted
Call graph
write_formatted calls write_formatted, write_dims, write_variables
write_dims calls begin, key, next
write_variables calls of, get_dimensions, get_type, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next