write_variables – MAPL
write_variables Subroutine
48 statements
Source File
private subroutine write_variables(variables, unit, iotype, v_list, iostat, iomsg)
Arguments
Type Intent Optional Attributes Name
type(StringVariableMap), intent(in), target :: variables
integer, intent(in) :: unit
character(len=*), intent(in) :: iotype
integer, intent(in) :: v_list(:)
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Called by
Source Code
   subroutine write_variables(variables, unit, iotype, v_list, iostat, iomsg)
      type(StringVariableMap), target, intent(in) :: variables
      integer, intent(in) :: unit
      character(*), intent(in) :: iotype
      integer, intent(in) :: v_list(:)
      integer, intent(out) :: iostat
      character(*), intent(inout) :: iomsg
      type(StringVariableMapIterator) :: var_iter
      character(:), allocatable :: type_name, dims_str
      class(Variable), pointer :: var
      type(StringVector), pointer :: dims
      character(:), pointer :: var_name
      integer :: i
      iostat = 0
      write(unit,'(a,/)')'variables:'
      associate (e => variables%ftn_end())
        var_iter = variables%ftn_begin()
        do while (var_iter /= e)
           call var_iter%next()
           var_name => var_iter%first()
           var => var_iter%second()
           dims => var%get_dimensions()
           select case (var%get_type())
           case (pFIO_REAL32)
              type_name = 'float'
           case (pFIO_REAL64)
              type_name = 'double'
           case default
              type_name = '<unknown>'
           end select
           dims_str = "(" // dims%of(1)
           do i = 2, dims%size()
              dims_str = dims_str // ", " // dims%of(i)
           end do
           dims_str = dims_str // ")"
           write(unit, '(T8,a,1x,a,a,/)', iostat=iostat, iomsg=iomsg) type_name, var_name, dims_str
           if (iostat /= 0) return
        end do
      end associate
      _UNUSED_DUMMY(iotype)
      _UNUSED_DUMMY(v_list)
   end subroutine write_variables
Call graph
write_variables calls of, get_dimensions, get_type, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_advpos calls map_s_get_child, to_node
map_s_begin calls map_s_iter_next
map_s_iter_of calls map_s_get_value
write_formatted calls write_variables, write_formatted