write_state – MAPL
write_state Subroutine
22 statements
Source File
private subroutine write_state(in_state, unit, iotype, v_list, iostat, iomsg)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: in_state
integer, intent(in) :: unit
character(len=*), intent(in) :: iotype
integer, intent(in) :: v_list(:)
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Called by
Source Code
   subroutine write_state(in_state, unit, iotype, v_list, iostat, iomsg)
      type(ESMF_State), intent(in) :: in_state
      integer, intent(in)         :: unit
      character(*), intent(in)    :: iotype
      integer, intent(in)         :: v_list (:)
      integer, intent(out)        :: iostat
      character(*), intent(inout) :: iomsg
      type(ESMF_State) :: state
      integer :: status
      character(ESMF_MAXSTR) :: name
      integer :: itemCount
      state = in_state
      call ESMF_StateGet(state, name=name, itemCount=itemCount, rc=status)
      if (status /= 0) then
         iostat = status
         iomsg = 'invalid state'
         return
      end if
      write(unit,'(a,a,a,i0,a,a)',iostat=iostat, iomsg=iomsg) 'State: ', trim(name),  ' has ', itemCount, ' items.', new_line('a')
      if (iostat /=0) return
      call write_state_(state, unit, iotype, v_list, iostat, iomsg, depth=0)
   end subroutine write_state
Call graph
write_state calls esmf_stateget, write_state_
write_state_ calls esmf_stateget, write_state_
write(formatted) calls write_state