write_const_variables – MAPL
write_const_variables Subroutine
53 statements
Source File
private subroutine write_const_variables(this, cf, unusable, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
type(FileMetadata), intent(in), target :: cf
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine write_const_variables(this, cf, unusable, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      type (FileMetadata), target, intent(in) :: cf
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type (StringVariableMap), pointer :: vars
      type (StringVariableMapIterator) :: var_iter
      type (UnlimitedEntity), pointer :: const_value_ptr
      character(len=:), pointer :: var_name
      type (Variable), pointer :: var
      integer, allocatable :: shp(:)
      class (*), pointer :: var_values(:)
      vars => cf%get_variables()
      var_iter = vars%ftn_begin()
      do while (var_iter /= vars%ftn_end())
         call var_iter%next()
         var_name => var_iter%first()
         var => var_iter%second()
         const_value_ptr => var%get_const_value()
         if ( .not. const_value_ptr%is_empty()) then
            shp = const_value_ptr%get_shape()
            var_values => const_value_ptr%get_values()
            select type(q => var_values)
            type is (integer(INT32))
               call this%put_var(trim(var_name), q, count=shp, rc=status)
               _VERIFY(status)
            type is (integer(INT64))
               call this%put_var(trim(var_name), q, count=shp, rc=status)
               _VERIFY(status)
            type is (real(REAL32))
               call this%put_var(trim(var_name), q, count=shp, rc=status)
               _VERIFY(status)
            type is (real(REAL64))
               call this%put_var(trim(var_name), q, count=shp, rc=status)
               _VERIFY(status)
            class default
               status = _FAILURE
               _VERIFY(status)
            end select
         end if
      enddo
      _UNUSED_DUMMY(unusable)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine write_const_variables
Call graph
write_const_variables calls put_var, get_const_value, get_shape, get_values, get_variables, is_empty, map_ftn_begin, map_ftn_end, map_iter_first, map_iter_next, mapl_return, mapl_verify
get_shape calls mapl_return
get_values calls mapl_return
get_variables calls mapl_return
is_empty calls mapl_return, get_value
map_ftn_begin calls map_s_ftn_begin
map_ftn_end calls map_s_ftn_end
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
map_iter_of calls map_s_iter_of
map_s_ftn_end calls next, map_s_begin
map_s_iter_next calls map_s_advpos
mapl_throw_exception calls initialize
put_var_real64_4 calls mapl_return, mapl_verify, nf90_inq_varid, nf90_put_var
write calls write_const_variables