write – MAPL
write Subroutine
25 statements
Source File
private subroutine write(this, cf, unusable, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
type(FileMetadata), intent(in) :: cf
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine write(this, cf, unusable, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      type (FileMetadata), intent(in) :: cf
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      call this%def_dimensions(cf, rc=status)
      _VERIFY(status)
      call this%def_variables(cf, rc=status)
      _VERIFY(status)
      call this%put_attributes(cf, NF90_GLOBAL, rc=status)
      _VERIFY(status)
      !$omp critical
      status= nf90_enddef(this%ncid)
      !$omp end critical
      _VERIFY(status)
      call this%write_coordinate_variables(cf, rc=status)
      _VERIFY(status)
      call this%write_const_variables(cf, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine write
Call graph
write calls nf90_enddef, def_dimensions, def_variables, mapl_return, mapl_verify, put_attributes, write_const_variables, write_coordinate_variables