write_formatted – MAPL
write_formatted Subroutine
60 statements
Source File
private subroutine write_formatted(this, unit, iotype, v_list, iostat, iomsg)
Type Bound
HierarchicalRegistry
Arguments
Type Intent Optional Attributes Name
class(HierarchicalRegistry), intent(in) :: this
integer, intent(in) :: unit
character(len=*), intent(in) :: iotype
integer, intent(in) :: v_list(:)
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Source Code
   subroutine write_formatted(this, unit, iotype, v_list, iostat, iomsg)
      class(HierarchicalRegistry), intent(in) :: this
      integer, intent(in) :: unit
      character(*), intent(in) :: iotype
      integer, intent(in) :: v_list(:)
      integer, intent(out) :: iostat
      character(*), intent(inout) :: iomsg
      type(ActualPtVec_MapIterator) :: virtual_iter
      type(ActualConnectionPt), pointer :: actual_pt
      write(unit,*,iostat=iostat,iomsg=iomsg) new_line('a')
      if (iostat /= 0) return
      call write_header(this, iostat=iostat, iomsg=iomsg)
      if (iostat /= 0) return
      call write_virtual_pts(this, iostat=iostat, iomsg=iomsg)
      if (iostat /= 0) return
   contains
      subroutine write_header(this, iostat, iomsg)
         class(HierarchicalRegistry), intent(in) :: this
         integer, intent(out) :: iostat
         character(*), intent(inout) :: iomsg
         write(unit,'(a,a,a,i0,a,i0,a,i0,a)',iostat=iostat,iomsg=iomsg) &
              'HierarchicalRegistry(name=', this%name, &
              ', n_local=', this%local_specs%size(), &
              ', n_actual=', this%actual_specs_map%size(), &
              ', n_virtual=', this%virtual_pts%size(), ')'// new_line('a')
         if (iostat /= 0) return
         write(unit,*,iostat=iostat,iomsg=iomsg) '   actuals: '// new_line('a')
      end subroutine write_header
      subroutine write_virtual_pts(this, iostat, iomsg)
         class(HierarchicalRegistry), target, intent(in) :: this
         integer, intent(out) :: iostat
         character(*), intent(inout) :: iomsg
         write(unit,*,iostat=iostat,iomsg=iomsg) '   virtuals: '// new_line('a')
         if (iostat /= 0) return
         associate (e => this%virtual_pts%end())
           virtual_iter = this%virtual_pts%begin()
           do while (virtual_iter /= e)
              associate (virtual_pt => virtual_iter%first())
                write(unit,*,iostat=iostat,iomsg=iomsg)'        ',virtual_pt,  new_line('a')
                if (iostat /= 0) return
                call write_actual_pts(this, virtual_pt, iostat=iostat, iomsg=iomsg)
                if (iostat /= 0) return
              end associate
              call virtual_iter%next()
           end do
         end associate
      end subroutine write_virtual_pts
      subroutine write_actual_pts(this, virtual_pt, iostat, iomsg)
         class(HierarchicalRegistry), target, intent(in) :: this
         type(VirtualConnectionPt), intent(in) :: virtual_pt
         integer, intent(out) :: iostat
         character(*), intent(inout) :: iomsg
         type(ActualPtVector), pointer :: actual_pts
         type(ActualConnectionPt), pointer :: actual_pt
         integer :: i
         actual_pts => this%virtual_pts%at(virtual_pt, rc=iostat)
         if (iostat /= 0) return
         do i = 1, actual_pts%size()
            actual_pt => actual_pts%of(i)
            write(unit,*,iostat=iostat,iomsg=iomsg)'           ',actual_pt, new_line('a')
            if (iostat /= 0) return
         end do
      end subroutine write_actual_pts
   end subroutine write_formatted
Call graph
write_formatted calls at, of, map_begin, map_iter_first, map_iter_next
map_begin calls map_s_begin
map_iter_first calls map_iter_of
map_iter_next calls map_s_iter_next
map_at_rc calls map_find
map_iter_of calls map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_find calls map_s_find
map_s_advpos calls map_s_get_child, to_node
map_s_iter_of calls map_s_get_value