WriteRestart – MAPL
WriteRestart Subroutine
166 statements
Source File
private subroutine WriteRestart(CC, SRC, DST, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CplComp) :: CC
type(ESMF_State) :: SRC
type(ESMF_State) :: DST
type(ESMF_Clock) :: CLOCK
integer, intent(out) :: RC
Calls
Source Code
  subroutine WriteRestart(CC, SRC, DST, CLOCK, RC)
! !ARGUMENTS:
    type (ESMF_CplComp)      :: CC
    type (ESMF_State)        :: SRC
    type (ESMF_State)        :: DST
    type (ESMF_Clock)        :: CLOCK
    integer, intent(  OUT)   :: RC
!EOPI
! ErrLog Variables
    character(len=ESMF_MAXSTR)    :: IAm
    character(len=ESMF_MAXSTR)    :: COMP_NAME
    integer                       :: STATUS
! Locals
    type (MAPL_GenericCplState), pointer  :: STATE
    type (MAPL_GenericCplWrap )           :: WRAP
    type(ESMF_VM)                         :: VM
    type(ESMF_Grid)                       :: grid
    type(ESMF_Field)                      :: field
    type(ESMF_Info)                       :: infoh
    character(len=ESMF_MAXSTR)            :: name
    character(len=ESMF_MAXSTR)            :: filename
    logical                               :: am_i_root
    logical                               :: local_undefs
    integer                               :: unit
    integer                               :: n_vars
    integer                               :: n_count
    integer                               :: n_undefs
    integer                               :: rank
    integer                               :: i
    integer                               :: dims
    integer                               :: have_undefs
    integer, pointer                      :: mask(:) => null()
    real, allocatable                     :: buf1(:), buf2(:,:), buf3(:,:,:)
    real, pointer                         :: ptr1(:), ptr2(:,:), ptr3(:,:,:)
! Begin...
! Get the target components name and set-up traceback handle.
! -----------------------------------------------------------
    _UNUSED_DUMMY(dst)
    _UNUSED_DUMMY(clock)
    IAm = "MAPL_GenericCplComWriteRestart"
    call ESMF_CplCompGet( CC, NAME=COMP_NAME, RC=STATUS )
    _VERIFY(STATUS)
    Iam = trim(COMP_NAME) // Iam
! Retrieve the pointer to the internal state. It comes in a wrapper.
! ------------------------------------------------------------------
    call ESMF_CplCompGetInternalState ( CC, WRAP, STATUS )
    _VERIFY(STATUS)
    STATE     =>  WRAP%INTERNAL_STATE
    call ESMF_CplCompGet(CC, vm=vm, rc=status)
    _VERIFY(STATUS)
    filename = trim(comp_name) // '_checkpoint' ! following Andrea's and Larry's suggestions
    am_i_root = MAPL_AM_I_ROOT(vm)
    unit=0 ! just to initialize
    n_vars = size(state%src_spec)
    if (am_i_root) then
       UNIT = GETFILE(filename, rc=status)
       _VERIFY(status)
       write(unit) n_vars
    end if
       ! for each var
    do i = 1, n_vars
       ! varname we can get from query SHORT_NAME in state%src_spec(i)
       call MAPL_VarSpecGet(state%src_spec(i), SHORT_NAME=name, rc=status)
       _VERIFY(status)
       call ESMF_StateGet(SRC, name, field=field, rc=status)
       _VERIFY(status)
       call ESMF_FieldGet(field, grid=grid, rc=status)
       _VERIFY(status)
       rank = state%accum_rank(i)
       call ESMF_InfoGetFromHost(field,infoh,rc=status)
       _VERIFY(STATUS)
       call ESMF_InfoGet(infoh,'DIMS',DIMS,rc=status)
       _VERIFY(STATUS)
       mask => null()
       if (DIMS == MAPL_DimsTileOnly .or. DIMS == MAPL_DimsTileTile) then
          call MAPL_TileMaskGet(grid,  mask, rc=status)
          _VERIFY(STATUS)
       end if
       !we need to get the MAX n_count
       call MAPL_CommsAllReduceMax(vm, sendbuf=state%accum_count(i), &
            recvbuf=n_count, cnt=1, RC=status)
       _VERIFY(status)
       if (am_i_root) then
          write(unit) n_count
       end if
       select case (rank)
          case(1)
             local_undefs = associated(state%array_count(i)%ptr1c)
          case(2)
             local_undefs = associated(state%array_count(i)%ptr2c)
          case(3)
             local_undefs = associated(state%array_count(i)%ptr3c)
          case default
             _FAIL( "Unsupported rank")
          end select
       have_undefs = 0
       n_undefs = 0
       if (local_undefs) have_undefs = 1
       call MAPL_CommsAllReduceMax(vm, sendbuf=have_undefs, &
            recvbuf=n_undefs, cnt=1, RC=status)
       _VERIFY(status)
       if (am_i_root) then
          write(unit) n_undefs
       end if
       select case(rank)
          case (3)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(i), &
                  farrayPtr=ptr3, RC=status)
             _VERIFY(status)
             call MAPL_VarWrite(unit, grid, ptr3, rc=status)
             _VERIFY(STATUS)
             if (n_undefs /=0) then
                allocate(buf3(size(ptr3,1),size(ptr3,2),size(ptr3,3)), stat=status)
                _VERIFY(STATUS)
                if (associated(state%array_count(i)%ptr3c)) then
                   buf3 = state%array_count(i)%ptr3c
                else
                   buf3 = state%accum_count(i)
                end if
                call MAPL_VarWrite(unit, grid, buf3, rc=status)
                _VERIFY(STATUS)
                deallocate(buf3)
             end if
          case (2)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(i), &
                  farrayPtr=ptr2, RC=status)
             _VERIFY(status)
             call MAPL_VarWrite(unit, grid, ptr2, mask=mask, rc=status)
             _VERIFY(STATUS)
             if (n_undefs /=0) then
                allocate(buf2(size(ptr2,1),size(ptr2,2)), stat=status)
                _VERIFY(STATUS)
                if (associated(state%array_count(i)%ptr2c)) then
                   buf2 = state%array_count(i)%ptr2c
                else
                   buf2 = state%accum_count(i)
                end if
                call MAPL_VarWrite(unit, grid, buf2, mask=mask, rc=status)
                _VERIFY(STATUS)
                deallocate(buf2)
             end if
          case (1)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(i), &
                  farrayPtr=ptr1, RC=status)
             _VERIFY(status)
             call MAPL_VarWrite(unit, grid, ptr1, mask=mask, rc=status)
             _VERIFY(STATUS)
             if (n_undefs /=0) then
                allocate(buf1(size(ptr1,1)), stat=status)
                _VERIFY(STATUS)
                if (associated(state%array_count(i)%ptr1c)) then
                   buf1 = state%array_count(i)%ptr1c
                else
                   buf1 = state%accum_count(i)
                end if
                call MAPL_VarWrite(unit, grid, buf1, mask=mask, rc=status)
                _VERIFY(STATUS)
                deallocate(buf1)
             end if
          case default
             _FAIL(" Unsupported rank")
          end select
          _DEALLOC(mask)
       end do
       if(am_i_root) call Free_File(unit = UNIT, rc=STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine WriteRestart
Call graph
writerestart calls ESMF_CplCompGet, ESMF_CplCompGetInternalState, ESMF_InfoGet, ESMF_InfoGetFromHost, esmf_fieldget, esmf_localarrayget, esmf_stateget, mapl_am_i_root, mapl_assert, mapl_commsallreducemax, mapl_deallocnodearray, mapl_syncsharedmemory, mapl_varspecget, mapl_varwrite, free_file, getfile, mapl_return, mapl_tilemaskget, mapl_verify