date_fields – MAPL
date_fields Interface
5 statements
Source File
public interface date_fields
Calls
Called by
Contents
Module Procedures
construct_date_fields_default construct_date_fields_string construct_date_fields_null
Module Procedures
public pure function construct_date_fields_default(year, month, day) result(fields)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: day
Return Value type(date_fields)
public pure function construct_date_fields_string(date_string, delimiter) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: date_string
character(len=*), intent(in) :: delimiter
Return Value type(date_fields)
public pure function construct_date_fields_null() result(fields)
Arguments
None
Return Value type(date_fields)
Call graph
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
parse_date calls date_fields, read_whole_number, undelimit
is_valid_day calls get_month_end
read_whole_number calls read_whole_number_indexed
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields
test_parse_date calls parse_date