initialize_array – MAPL
initialize_array Interface
4 statements
Source File
public interface initialize_array
Calls
Called by
Contents
Module Procedures
initialize_array_r4 initialize_array_r8
Module Procedures
public subroutine initialize_array_R4(x, xmin, xrange)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(inout) :: x(:,:)
real(kind=ESMF_KIND_R4), intent(in) :: xmin
real(kind=ESMF_KIND_R4), intent(in) :: xrange
public subroutine initialize_array_R8(x, xmin, xrange)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(inout) :: x(:,:)
real(kind=ESMF_KIND_R8), intent(in) :: xmin
real(kind=ESMF_KIND_R8), intent(in) :: xrange
Call graph
initialize_array calls initialize_array_r4, initialize_array_r8
initialize_array_r4 calls mapl_assert
initialize_array_r8 calls mapl_assert
test_fieldconvertprec_r4r8 calls initialize_array