MAPL_MemFileInquire – MAPL
MAPL_MemFileInquire Interface
3 statements
Source File
public interface MAPL_MemFileInquire
Called by
Module Procedures
private function INQFILEMEM(Name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: Name
Return Value logical
Call graph
mapl_esmfstatereadfromfile calls mapl_memfileinquire
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericrefresh calls mapl_esmfstatereadfromfile, mapl_genericrefresh
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore