mk_field – MAPL
mk_field Interface
4 statements
Source File
public interface mk_field
Calls
Called by
Contents
Module Procedures
mk_field_r4_2d mk_field_r8_2d
Module Procedures
public function mk_field_r4_2d(farray, regDecomp, minIndex, maxIndex, indexflag, name, rc) result(field)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in), dimension(:,:), target :: farray
integer, intent(in), dimension(:) :: regDecomp
integer, intent(in), dimension(:) :: minIndex
integer, intent(in), dimension(:) :: maxIndex
type(ESMF_Index_Flag), intent(in) :: indexflag
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
public function mk_field_r8_2d(farray, regDecomp, minIndex, maxIndex, indexflag, name, rc) result(field)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in), dimension(:,:), target :: farray
integer, intent(in), dimension(:) :: regDecomp
integer, intent(in), dimension(:) :: minIndex
integer, intent(in), dimension(:) :: maxIndex
type(ESMF_Index_Flag), intent(in) :: indexflag
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Call graph
mk_field calls mk_field_r4_2d, mk_field_r8_2d
mk_field_r4_2d calls esmf_fieldget, mapl_return, mapl_verify, mk_field_common
mk_field_r8_2d calls esmf_fieldget, mapl_return, mapl_verify, mk_field_common
mapl_return calls mapl_throw_exception
mapl_verify calls mapl_throw_exception
mk_field_common calls mapl_return, mapl_verify, esmf_fieldcreate, mk_grid
mk_grid calls mapl_return, mapl_verify, ESMF_GridCreateNoPeriDim
set_up_data calls mk_field
test_fieldconvertprec_r4r8 calls mk_field