AdjustPtrBounds – MAPL
AdjustPtrBounds Interface
6 statements
Source File
private interface AdjustPtrBounds
Calls
Module Procedures
private subroutine AdjustPtrBounds1dr4(PTR, A, I1, IN)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), pointer :: PTR(:)
real(kind=ESMF_KIND_R4), target :: A(I1:IN)
integer :: I1
integer :: IN
private subroutine AdjustPtrBounds1dr8(PTR, A, I1, IN)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), pointer :: PTR(:)
real(kind=ESMF_KIND_R8), target :: A(I1:IN)
integer :: I1
integer :: IN
private subroutine AdjustPtrBounds3dr4(PTR, A, I1, IN, J1, JN, L1, LN)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:,:)
real(kind=ESMF_KIND_R4), target :: A(I1:IN,J1:JN,L1:LN)
integer :: I1
integer :: IN
integer :: J1
integer :: JN
integer :: L1
integer :: LN
private subroutine AdjustPtrBounds3dr8(PTR, A, I1, IN, J1, JN, L1, LN)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:)
real(kind=ESMF_KIND_R8), target :: A(I1:IN,J1:JN,L1:LN)
integer :: I1
integer :: IN
integer :: J1
integer :: JN
integer :: L1
integer :: LN
Call graph
adjustptrbounds calls adjustptrbounds1dr4, adjustptrbounds1dr8, adjustptrbounds3dr4, adjustptrbounds3dr8