advance – MAPL
advance Interface
4 statements
Source File
public interface advance
Calls
Contents
Module Procedures
map_s_iter_advance_size_kind map_s_iter_advance_default
Module Procedures
private subroutine map_s_iter_advance_size_kind(it, n)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(inout) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
private subroutine map_s_iter_advance_default(it, n)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(inout) :: it
integer, intent(in) :: n
Call graph
advance calls map_s_iter_advance_default, map_s_iter_advance_size_kind
map_s_iter_advance_default calls next
map_s_iter_advance_size_kind calls next
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_iter_next_n_size_kind calls next