advance – MAPL
advance Interface
4 statements
Source File
private interface advance
Calls
Contents
Module Procedures
vector_riter_advance_size_kind vector_riter_advance_default
Module Procedures
private subroutine vector_riter_advance_size_kind(it, n)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(inout) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
private subroutine vector_riter_advance_default(it, n)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(inout) :: it
integer, intent(in) :: n
Call graph
advance calls vector_riter_advance_default, vector_riter_advance_size_kind
vector_riter_advance_default calls add
vector_riter_advance_size_kind calls add