ArrayScatter – MAPL
ArrayScatter Interface
8 statements
Source File
public interface ArrayScatter
Calls
Called by
Contents
Module Procedures
ArrayScatter_R4_1 ArrayScatter_R8_1 ArrayScatter_R4_2 ArrayScatter_R8_2 ArrayScatterRcvCnt_I4_1 ArrayScatterRcvCnt_R4_1
Module Procedures
private subroutine ArrayScatter_R4_1(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(out) :: local_array(:)
real(kind=ESMF_KIND_R4), intent(in), target :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayScatter_R8_1(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(out) :: local_array(:)
real(kind=ESMF_KIND_R8), intent(in), target :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayScatter_R4_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(out) :: local_array(:,:)
real(kind=ESMF_KIND_R4), intent(in), target :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayScatter_R8_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(out) :: local_array(:,:)
real(kind=ESMF_KIND_R8), intent(in), target :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayScatterRcvCnt_I4_1(local_array, global_array, sendcounts, vm, srcPe, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(out) :: local_array(:)
integer(kind=ESMF_KIND_I4), intent(in), target :: global_array(:)
integer :: sendcounts(:)
type(ESMF_VM) :: vm
integer, intent(in), optional :: srcPe
integer, intent(out), optional :: rc
private subroutine ArrayScatterRcvCnt_R4_1(local_array, global_array, sendcounts, vm, srcPe, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(out) :: local_array(:)
real(kind=ESMF_KIND_R4), intent(in), target :: global_array(:)
integer :: sendcounts(:)
type(ESMF_VM) :: vm
integer, intent(in), optional :: srcPe
integer, intent(out), optional :: rc
Call graph
arrayscatter calls arrayscatter_r4_1, arrayscatter_r4_2, arrayscatter_r8_1, arrayscatter_r8_2, arrayscatterrcvcnt_i4_1, arrayscatterrcvcnt_r4_1
arrayscatter_r4_1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsscatterv, mapl_distgridget, mapl_return, mapl_verify
arrayscatter_r4_2 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsscatterv, mapl_distgridget, mapl_return, mapl_verify
arrayscatter_r8_1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsscatterv, mapl_distgridget, mapl_return, mapl_verify
arrayscatter_r8_2 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsscatterv, mapl_distgridget, mapl_return, mapl_verify
arrayscatterrcvcnt_i4_1 calls ESMF_VMGet, ESMF_VMScatterV, mapl_assert, mapl_return, mapl_verify
arrayscatterrcvcnt_r4_1 calls ESMF_VMGet, ESMF_VMScatterV, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commsscatterv calls mapl_commsscatterv_i4_1, mapl_commsscatterv_r4_1, mapl_commsscatterv_r4_2, mapl_commsscatterv_r8_1, mapl_commsscatterv_r8_2
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_commsscatterv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_scatterv
mapl_commsscatterv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_scatterv
mapl_commsscatterv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_scatterv
mapl_commsscatterv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_scatterv
mapl_commsscatterv_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_scatterv
mapl_throw_exception calls initialize
mapl_cfioreadbundle calls arrayscatter
mapl_varread_r4_1d calls arrayscatter
mapl_varread_r4_2d calls arrayscatter, mapl_varread
mapl_varread_r8_1d calls arrayscatter
mapl_varread_r8_2d calls arrayscatter, mapl_varread
process_data_from_file calls arrayscatter
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r4_2d, mapl_varread_r8_1d, mapl_varread_r8_2d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_fieldread calls mapl_varread
mapl_simplebundleread calls mapl_cfioread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
readrestart calls mapl_varread
test_main calls mapl_cfioread, esmf_ioread