ArrayReference – MAPL
ArrayReference Interface
8 statements
Source File
public interface ArrayReference
Calls
Contents
Module Procedures
new_ArrayReference_0d new_ArrayReference_1d new_ArrayReference_2d new_ArrayReference_3d new_ArrayReference_4d new_ArrayReference_5d
Module Procedures
private function new_ArrayReference_0d(scalar, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: scalar
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
private function new_ArrayReference_1d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:)
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
private function new_ArrayReference_2d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:)
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
private function new_ArrayReference_3d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:,:)
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
private function new_ArrayReference_4d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
private function new_ArrayReference_5d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
Call graph
arrayreference calls new_arrayreference_0d, new_arrayreference_1d, new_arrayreference_2d, new_arrayreference_3d, new_arrayreference_4d, new_arrayreference_5d
new_arrayreference_0d calls mapl_assert, mapl_return, type_kind
new_arrayreference_1d calls mapl_assert, mapl_return
new_arrayreference_2d calls mapl_assert, mapl_return
new_arrayreference_3d calls mapl_assert, mapl_return
new_arrayreference_4d calls mapl_assert, mapl_return
new_arrayreference_5d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
type_kind calls mapl_assert, mapl_return
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize