array_format – MAPL
array_format Interface
4 statements
Source File
private interface array_format
Calls
Called by
Module Procedures
private pure function array_format_simple(scalar_format) result(array_format)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: scalar_format
Return Value character(len=:), allocatable
private pure function array_format_string(scalar_format, array_size_string) result(array_format)
Create array format string from scalar format string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: scalar_format
character(len=*), intent(in) :: array_size_string
Return Value character(len=:), allocatable
Call graph
array_format calls array_format_simple, array_format_string
mapl_getresource_config_array calls array_format
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefrommapl_array
arrdescrsetncpar calls mapl_getresource
capture calls mapl_getresource
get_test_framework_resource calls mapl_getresource
initialize_gc calls mapl_getresource
mapl_clockinit calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource
mapl_esmfstatewritetofile calls mapl_getresource
mapl_genericfinalize calls mapl_getresource
mapl_genericinitialize calls mapl_getresource
mapl_genericrecord calls mapl_getresource
mapl_genericrefresh calls mapl_getresource
mapl_genericstaterestore calls mapl_getresource
mapl_genericstatesave calls mapl_getresource
mapl_genericwrapper calls mapl_getresource
mapl_readforcingx calls mapl_getresource
mapl_staterecord calls mapl_getresource
mapl_staterefresh calls mapl_getresource