ArrayGather – MAPL
ArrayGather Interface
9 statements
Source File
public interface ArrayGather
Calls
Called by
Module Procedures
private subroutine ArrayGather_I4_1(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(in) :: local_array(:)
integer(kind=ESMF_KIND_I4), intent(out) :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayGather_R4_1(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: local_array(:)
real(kind=ESMF_KIND_R4), intent(out) :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayGather_R8_1(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: local_array(:)
real(kind=ESMF_KIND_R8), intent(out) :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayGather_R4_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: local_array(:,:)
real(kind=ESMF_KIND_R4), intent(out) :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayGather_R8_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: local_array(:,:)
real(kind=ESMF_KIND_R8), intent(out) :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
private subroutine ArrayGatherRcvCnt_I4_1(local_array, global_array, recvcounts, vm, dstPe, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(in) :: local_array(:)
integer(kind=ESMF_KIND_I4), intent(out) :: global_array(:)
integer :: recvcounts(:)
type(ESMF_VM) :: vm
integer, intent(in), optional :: dstPe
integer, intent(out), optional :: rc
private subroutine ArrayGatherRcvCnt_R4_1(local_array, global_array, recvcounts, vm, dstPe, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: local_array(:)
real(kind=ESMF_KIND_R4), intent(out) :: global_array(:)
integer :: recvcounts(:)
type(ESMF_VM) :: vm
integer, intent(in), optional :: dstPe
integer, intent(out), optional :: rc
Call graph
arraygather calls arraygather_i4_1, arraygather_r4_1, arraygather_r4_2, arraygather_r8_1, arraygather_r8_2, arraygatherrcvcnt_i4_1, arraygatherrcvcnt_r4_1
arraygather_i4_1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMBarrier, ESMF_VMGet, mapl_assert, mapl_commsgatherv, mapl_distgridget, mapl_return, mapl_verify
arraygather_r4_1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMBarrier, ESMF_VMGet, mapl_assert, mapl_commsgatherv, mapl_distgridget, mapl_return, mapl_verify
arraygather_r4_2 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMBarrier, ESMF_VMGet, mapl_assert, mapl_commsgatherv, mapl_distgridget, mapl_return, mapl_verify
arraygather_r8_1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMBarrier, ESMF_VMGet, mapl_assert, mapl_commsgatherv, mapl_distgridget, mapl_return, mapl_verify
arraygather_r8_2 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMBarrier, ESMF_VMGet, mapl_assert, mapl_commsgatherv, mapl_distgridget, mapl_return, mapl_verify
arraygatherrcvcnt_i4_1 calls ESMF_VMGatherV, ESMF_VMGet, mapl_assert, mapl_return, mapl_verify
arraygatherrcvcnt_r4_1 calls ESMF_VMGatherV, ESMF_VMGet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commsgatherv calls mapl_commsgatherv_i4_1, mapl_commsgatherv_r4_1, mapl_commsgatherv_r4_2, mapl_commsgatherv_r8_1, mapl_commsgatherv_r8_2
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_commsgatherv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_throw_exception calls initialize
bundlediff calls arraygather
bundleregrid calls arraygather
mapl_areamean_2d_r8_bitrep calls arraygather
mapl_cfiocreatefrombundle calls arraygather
mapl_cfiowritebundlepost calls arraygather
mapl_fieldwritencpar calls arraygather
mapl_getlatloncoord_real32 calls arraygather
mapl_getlatloncoord_real64 calls arraygather
mapl_gridgetlatlons calls arraygather
mapl_varwrite_i4_1d calls arraygather
mapl_varwrite_r4_1d calls arraygather
mapl_varwrite_r4_2d calls arraygather
mapl_varwrite_r8_1d calls arraygather
mapl_varwrite_r8_2d calls arraygather
esmf_iocreate calls mapl_cfiocreatefrombundle
esmfl_diff calls bundlediff
esmfl_regrid calls bundleregrid
mapl_areamean calls mapl_areamean_2d_r8_bitrep
mapl_cfiocreate calls mapl_cfiocreatefrombundle
mapl_getlatloncoord calls mapl_getlatloncoord_real32, mapl_getlatloncoord_real64
mapl_varwrite calls mapl_varwrite_i4_1d, mapl_varwrite_r4_1d, mapl_varwrite_r4_2d, mapl_varwrite_r8_1d, mapl_varwrite_r8_2d
bundlestatistics calls bundlediff
mapl_bundlewritencpar calls mapl_fieldwritencpar
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
mygridcreate_ calls mapl_gridgetlatlons
statediff calls bundlediff
stateregrid calls bundleregrid