ArrayScatterShm – MAPL
ArrayScatterShm Interface
3 statements
Source File
public interface ArrayScatterShm
Calls
Called by
Module Procedures
private subroutine ArrayScatterShmR4D1(local_array, global_array, grid, mask, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: local_array(:)
real, target :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(out), optional :: rc
Call graph
arrayscattershm calls arrayscattershmr4d1
arrayscattershmr4d1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_broadcasttonodes, mapl_commsscatterv, mapl_syncsharedmemory, mapl_distgridget, mapl_return, mapl_verify
mapl_broadcasttonodes calls broadcasttonodes_1di4, broadcasttonodes_1dr4, broadcasttonodes_1dr8, broadcasttonodes_2di4, broadcasttonodes_2dr4, broadcasttonodes_2dr8, broadcasttonodes_3di4, broadcasttonodes_3dr4, broadcasttonodes_3dr8, broadcasttonodes_4dr4, broadcasttonodes_4dr8
mapl_commsscatterv calls mapl_commsscatterv_i4_1, mapl_commsscatterv_r4_1, mapl_commsscatterv_r4_2, mapl_commsscatterv_r8_1, mapl_commsscatterv_r8_2
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_varread_r4_1d calls arrayscattershm
mapl_varread_r4_2d calls arrayscattershm, mapl_varread
mapl_varreadncpar_r4_1d calls arrayscattershm
mapl_varread calls mapl_varreadncpar_r4_1d, mapl_varreadncpar_r4_3d, mapl_varreadncpar_r8_3d, mapl_varread_r4_1d, mapl_varread_r4_2d, mapl_fieldread, mapl_varread_r4_3d, mapl_varread_r4_4d, mapl_varread_r8_2d, mapl_varread_r8_3d, mapl_varread_r8_4d
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_fieldread calls mapl_varread
mapl_fieldreadncpar calls mapl_varread
mapl_readforcingx calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
mapl_varreadncpar_r4_3d calls mapl_varread
mapl_varreadncpar_r8_3d calls mapl_varread
readrestart calls mapl_varread
mapl_bundleread calls mapl_fieldread
mapl_bundlereadncpar calls mapl_fieldreadncpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarread calls mapl_fieldread