assign_fptr – MAPL
assign_fptr Interface
6 statements
Source File
public interface assign_fptr
Calls
Called by
MAPL_ExtDataBracket::ExtDataBracket%interpolate_to_time w MAPL_FieldPointerUtilities::assign_fptr
w
MAPL_ExtDataBracket::ExtDataBracket%swap_node_fields w
w
MAPL_FieldBinaryOperations::fieldAdd w
w
MAPL_FieldBinaryOperations::fieldDivide w
w
MAPL_FieldBinaryOperations::fieldMultiply w
w
MAPL_FieldBinaryOperations::fieldPower w
w
MAPL_FieldBinaryOperations::fieldSubtract w
w
mapl_FieldBLAS::axpy_r4 w
w
mapl_FieldBLAS::axpy_r8 w
w
mapl_FieldBLAS::convert_prec_R4_to_R8 w
w
mapl_FieldBLAS::convert_prec_R8_to_R4 w
w
mapl_FieldBLAS::gemv_r4 w
w
mapl_FieldBLAS::gemv_r8 w
w
mapl_FieldBLAS::scale_r4 w
w
mapl_FieldBLAS::scale_r8 w
w
MAPL_FieldUnaryFunctions::fieldAbs w
w
MAPL_FieldUnaryFunctions::fieldAcos w
w
MAPL_FieldUnaryFunctions::fieldAsin w
w
MAPL_FieldUnaryFunctions::fieldAtan w
w
MAPL_FieldUnaryFunctions::fieldCos w
w
MAPL_FieldUnaryFunctions::fieldCosh w
w
MAPL_FieldUnaryFunctions::fieldExp w
w
MAPL_FieldUnaryFunctions::fieldLog w
w
MAPL_FieldUnaryFunctions::fieldLog10 w
w
MAPL_FieldUnaryFunctions::fieldSin w
w
MAPL_FieldUnaryFunctions::fieldSinh w
w
MAPL_FieldUnaryFunctions::fieldSqrt w
w
MAPL_FieldUnaryFunctions::fieldTan w
w
MAPL_FieldUnaryFunctions::fieldTanh w
w
MAPL_FieldUtilities::FieldIsConstantR4 w
w
MAPL_FieldUtilities::FieldNegate w
w
MAPL_FieldUtilities::FieldPow w
w
MAPL_FieldUtilities::FieldSet_r4 w
w
MAPL_FieldUtilities::FieldSet_r8 w
w
Module Procedures
private subroutine assign_fptr_r4_rank1(x, fptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
real(kind=ESMF_KIND_R4), intent(out), pointer :: fptr(:)
integer, intent(out), optional :: rc
private subroutine assign_fptr_r8_rank1(x, fptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
real(kind=ESMF_KIND_R8), intent(out), pointer :: fptr(:)
integer, intent(out), optional :: rc
private subroutine assign_fptr_r4_rank2(x, fp_shape, fptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
integer(kind=ESMF_KIND_I8), intent(in) :: fp_shape(:)
real(kind=ESMF_KIND_R4), intent(out), pointer :: fptr(:,:)
integer, intent(out), optional :: rc
private subroutine assign_fptr_r8_rank2(x, fp_shape, fptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
integer(kind=ESMF_KIND_I8), intent(in) :: fp_shape(:)
real(kind=ESMF_KIND_R8), intent(out), pointer :: fptr(:,:)
integer, intent(out), optional :: rc
Call graph
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
assign_fptr_r4_rank1 calls fieldgetcptr, fieldgetlocalsize, mapl_return, mapl_verify
assign_fptr_r4_rank2 calls fieldgetcptr, mapl_return, mapl_verify
assign_fptr_r8_rank1 calls fieldgetcptr, fieldgetlocalsize, mapl_return, mapl_verify
assign_fptr_r8_rank2 calls fieldgetcptr, mapl_return, mapl_verify
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_cptr calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8
get_error_message calls at, insert
get_local_size calls mapl_return, mapl_verify, fieldgetlocalelementcount
mapl_throw_exception calls initialize