bisect – MAPL
bisect Interface
3 statements
Source File
public interface bisect
Calls
Called by
Contents
Module Procedures
bisect_find_LB_R8_I8
Module Procedures
public subroutine bisect_find_LB_R8_I8(xa, x, n, n_LB, n_UB, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: xa(:)
real(kind=ESMF_KIND_R8), intent(in) :: x
integer(kind=ESMF_KIND_I8), intent(out) :: n
integer(kind=ESMF_KIND_I8), intent(in), optional :: n_LB
integer(kind=ESMF_KIND_I8), intent(in), optional :: n_UB
integer, intent(out), optional :: rc
Call graph
bisect calls bisect_find_lb_r8_i8
create_grid calls bisect, create_grid
get_x_subset calls bisect, get_x_subset
initialize calls create_grid, initialize
regrid_accumulate_on_xsubset calls get_x_subset, regrid_accumulate_on_xsubset
reinitialize calls create_grid, reinitialize