BroadcastToNodes_3DR8 – MAPL
BroadcastToNodes_3DR8 Interface
306 statements
Source File
interface
Calls
Called by
private module subroutine BroadcastToNodes_3DR8(DATA, N, ROOT, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout) :: DATA(:,:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: rc
Call graph
broadcasttonodes_3dr8 calls broadcasttonodes_3dr8, mpi_bcast, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_broadcasttonodes calls broadcasttonodes_3dr8
arrayscattershmr4d1 calls mapl_broadcasttonodes
mapl_bcastshared_1dr4 calls mapl_broadcasttonodes
mapl_bcastshared_2dr4 calls mapl_broadcasttonodes
mapl_tilemaskget calls mapl_broadcasttonodes
arrayscattershm calls arrayscattershmr4d1
mapl_bcastshared calls mapl_bcastshared_1dr4, mapl_bcastshared_2dr4
mapl_bundlereadncpar calls mapl_tilemaskget, mapl_fieldreadncpar
mapl_bundlewritencpar calls mapl_tilemaskget, mapl_fieldwritencpar
mapl_fieldread calls mapl_tilemaskget
mapl_fieldreadncpar calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_fieldwritencpar calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget, mapl_fieldread
mapl_statevarwrite calls mapl_tilemaskget, mapl_fieldwrite
process_data_from_file calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget
mapl_varread calls mapl_fieldread, mapl_statevarread
mapl_varreadncpar calls mapl_bundlereadncpar
mapl_varwrite calls mapl_fieldwrite, mapl_statevarwrite
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_bundleread calls mapl_fieldread
mapl_bundlewrite calls mapl_fieldwrite
mapl_cfioreadbundle calls mapl_bcastshared
mapl_cfiowritebundlepost calls mapl_bcastshared
mapl_locstreamcreatefromfile calls mapl_bcastshared
mapl_statevarwritencpar calls mapl_bundlewritencpar
mapl_varread_r4_1d calls arrayscattershm
mapl_varread_r4_2d calls arrayscattershm