BroadcastToNodes_1DR8 – MAPL
BroadcastToNodes_1DR8 Interface
313 statements
Source File
interface
Called by
private module subroutine BroadcastToNodes_1DR8(DATA, N, ROOT, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout) :: DATA(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: rc
Call graph
mapl_broadcasttonodes calls broadcasttonodes_1dr8
arrayscattershmr4d1 calls mapl_broadcasttonodes
mapl_bcastshared_1dr4 calls mapl_broadcasttonodes
mapl_bcastshared_1dr8 calls mapl_broadcasttonodes
mapl_bcastshared_2di4 calls mapl_broadcasttonodes
mapl_bcastshared_2dr4 calls mapl_broadcasttonodes
mapl_bcastshared_2dr8 calls mapl_broadcasttonodes
mapl_tilemaskget calls mapl_broadcasttonodes
arrayscattershm calls arrayscattershmr4d1
mapl_bcastshared calls mapl_bcastshared_1dr4, mapl_bcastshared_1dr8, mapl_bcastshared_2di4, mapl_bcastshared_2dr4, mapl_bcastshared_2dr8
mapl_bundlereadncpar calls mapl_tilemaskget
mapl_bundlewritencpar calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
mapl_fieldreadncpar calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_fieldwritencpar calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
process_data_from_file calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget