BroadcastToNodes_4DR8 – MAPL
BroadcastToNodes_4DR8 Interface
306 statements
Source File
interface
Calls
Called by
private module subroutine BroadcastToNodes_4DR8(DATA, N, ROOT, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout) :: DATA(:,:,:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: rc
Call graph
broadcasttonodes_4dr8 calls broadcasttonodes_4dr8, mapl_return, mapl_verify, mpi_bcast
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_broadcasttonodes calls broadcasttonodes_4dr8
arrayscattershmr4d1 calls mapl_broadcasttonodes
mapl_bcastshared_1dr4 calls mapl_broadcasttonodes
mapl_tilemaskget calls mapl_broadcasttonodes
mapl_bcastshared_2dr4 calls mapl_broadcasttonodes
arrayscattershm calls arrayscattershmr4d1
mapl_statevarread calls mapl_tilemaskget, mapl_fieldread
mapl_fieldwrite calls mapl_tilemaskget
mapl_bcastshared calls mapl_bcastshared_1dr4, mapl_bcastshared_2dr4
mapl_fieldread calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget, mapl_fieldwrite
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget
mapl_varread_r4_1d calls arrayscattershm
mapl_bundlewrite calls mapl_fieldwrite
mapl_varread_r4_2d calls arrayscattershm
mapl_varread calls mapl_statevarread, mapl_fieldread
mapl_varwrite calls mapl_fieldwrite, mapl_statevarwrite
mapl_cfioreadbundle calls mapl_bcastshared
mapl_locstreamcreatefromfile calls mapl_bcastshared
mapl_cfiowritebundlepost calls mapl_bcastshared
mapl_bundleread calls mapl_fieldread