c_chdir – MAPL
c_chdir Interface
6 statements
Source File
interface
Called by
private function c_chdir(path) bind(C,name="chdir")
Arguments
Type Intent Optional Attributes Name
character(kind=c_char, len=1) :: path(*)
Return Value integer
Call graph
chdir calls c_chdir
create_member_subcommunicator calls c_chdir
initialize_p0 calls create_member_subcommunicator
run_ensemble calls create_member_subcommunicator
run calls run_ensemble
capdriver_main calls run
driver_gethorzijindex calls run