c_f_pfio_get_att_string – MAPL
c_f_pfio_get_att_string Interface
12 statements
Source File
interface
Called by
private function c_f_pfio_get_att_string(ncid, varid, name, string, attlen) result(stat) bind(C, name='pfio_get_att_string')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), value :: ncid
integer(kind=C_INT), intent(in), value :: varid
character(kind=C_CHAR, len=1), intent(in) :: name(*)
character(kind=C_CHAR, len=1), intent(inout) :: string(*)
integer(kind=C_INT), intent(inout) :: attlen
Return Value integer
Call graph
pfio_get_att_string calls c_f_pfio_get_att_string
get_attribute_from_group calls pfio_get_att_string
inq_attributes calls pfio_get_att_string
create_grid calls get_attribute_from_group, create_grid
read calls inq_attributes