c_f_pfio_get_var_string_len – MAPL
c_f_pfio_get_var_string_len Interface
44 statements
Source File
interface
Called by
private function c_f_pfio_get_var_string_len(ncid, varid, str_len_ptr, size) result(stat) bind(C, name='pfio_get_var_string_len')
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), value :: ncid
integer(kind=C_INT), intent(in), value :: varid
type(c_ptr), intent(in), value :: str_len_ptr
integer(kind=C_INT), intent(in), value :: size
Return Value integer
Call graph
pfio_nf90_get_var_string_len calls c_f_pfio_get_var_string_len
inq_var_string_length calls pfio_nf90_get_var_string_len
main calls inq_var_string_length