CallbackMap – MAPL
CallbackMap Interface
5 statements
Source File
public interface CallbackMap
Calls
Called by
Contents
Module Procedures
map_new_map_empty map_new_map_copy map_new_map_initializer_list
Module Procedures
private function map_new_map_empty() result(m)
Arguments
None
Return Value type(CallbackMap)
private function map_new_map_copy(x) result(m)
Arguments
Type Intent Optional Attributes Name
type(CallbackMap), intent(in) :: x
Return Value type(CallbackMap)
private function map_new_map_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(CallbackPair), intent(in) :: il(:)
Return Value type(CallbackMap)
Call graph
callbackmap calls map_new_map_copy, map_new_map_empty, map_new_map_initializer_list
map_new_map_empty calls map_set
map_new_map_initializer_list calls callbackmap, insert
map_set calls map_s_new_set_copy, map_s_new_set_empty, map_s_new_set_initializer_list
map_s_new_set_initializer_list calls insert