CF_Time_Integer – MAPL
CF_Time_Integer Interface
3 statements
Source File
public interface CF_Time_Integer
Calls
Module Procedures
private function construct_cf_time_integer(duration, units) result(cft)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: duration
character(len=*), intent(in) :: units
Return Value type(CF_Time_Integer)
Call graph
cf_time_integer calls construct_cf_time_integer
construct_cf_time_integer calls initialize_cf_time
initialize_cf_time calls split
split calls split_characters