ClientThread – MAPL
ClientThread Interface
3 statements
Source File
public interface ClientThread
Calls
Module Procedures
private function new_ClientThread(sckt) result(c)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), optional :: sckt
Return Value type(ClientThread), target
Call graph
clientthread calls new_clientthread
new_clientthread calls set_connection
set_connection calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception