ClientManager – MAPL
ClientManager Interface
3 statements
Source File
public interface ClientManager
Calls
Module Procedures
private function new_ClientManager(client_comm, unusable, n_client, fast_oclient, rc) result(c_manager)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: client_comm
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: n_client
logical, intent(in), optional :: fast_oclient
integer, intent(out), optional :: rc
Return Value type(ClientManager)
Call graph
clientmanager calls new_clientmanager
new_clientmanager calls mpi_comm_rank, mapl_return, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity