CollectiveStageDataMessage – MAPL
CollectiveStageDataMessage Interface
3 statements
Source File
public interface CollectiveStageDataMessage
Calls
Module Procedures
private function new_CollectiveStageDataMessage(request_id, collection_id, file_name, var_name, data_reference, unusable, start, global_start, global_count) result(message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: request_id
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: global_start(:)
integer, intent(in), optional :: global_count(:)
Return Value type(CollectiveStageDataMessage)
Call graph
collectivestagedatamessage calls new_collectivestagedatamessage
new_collectivestagedatamessage calls initcollective
initcollective calls mapl_assert, init, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
init calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception