CommGroupDescription – MAPL
CommGroupDescription Interface
3 statements
Source File
public interface CommGroupDescription
Calls
Contents
Module Procedures
new_CommGroupDescription
Module Procedures
private function new_CommGroupDescription(npes, nnodes, isolate_nodes, name, unusable, npes_per_node, rc) result(CommGroup)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npes
integer, intent(in) :: nnodes
logical, intent(in) :: isolate_nodes
character(len=*), intent(in) :: name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: npes_per_node
integer, intent(out), optional :: rc
Return Value type(CommGroupDescription)
Call graph
commgroupdescription calls new_commgroupdescription
new_commgroupdescription calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize