ConcreteComposite – MAPL
ConcreteComposite Interface
5 statements
Source File
public interface ConcreteComposite
Calls
Module Procedures
private function new_root_composite(component) result(composite)
Arguments
Type Intent Optional Attributes Name
class(AbstractFrameworkComponent), intent(in) :: component
Return Value type(ConcreteComposite)
private function new_composite(component, parent) result(composite)
Arguments
Type Intent Optional Attributes Name
class(AbstractFrameworkComponent), intent(in) :: component
class(ConcreteComposite), intent(in), target :: parent
Return Value type(ConcreteComposite)
private function new_placeholder(parent) result(composite)
Arguments
Type Intent Optional Attributes Name
class(ConcreteComposite), intent(in), target :: parent
Return Value type(ConcreteComposite)
Call graph
concretecomposite calls new_composite, new_placeholder, new_root_composite