Converter – MAPL
Converter Interface
3 statements
Source File
public interface Converter
Calls
Module Procedures
private function construct_converter(from_unit, to_unit) result(conv)
Arguments
Type Intent Optional Attributes Name
type(UDUnit), intent(in) :: from_unit
type(UDUnit), intent(in) :: to_unit
Return Value type(Converter)
Call graph
converter calls construct_converter
construct_converter calls are_convertible, cv_free, ut_get_converter, ut_get_status, get_cptr, is_free, set_cptr, success
are_convertible calls are_convertible_str, are_convertible_udunit
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_get_status, get_cptr, success, ut_are_convertible