convert_time_nc2esmf – MAPL
convert_time_nc2esmf Interface
3 statements
Source File
public interface convert_time_nc2esmf
Calls
Module Procedures
public subroutine time_nc_int_2_esmf(time, tunit, n, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(out) :: time
character(len=*), intent(in) :: tunit
integer, intent(in) :: n
integer, intent(out), optional :: rc
Call graph
convert_time_nc2esmf calls time_nc_int_2_esmf
time_nc_int_2_esmf calls ESMF_TimeGet, parse_timeunit, mapl_return, mapl_verify
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_timeunit_i4 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
parse_timeunit_i8 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert