convert_CF_Time_to_datetime_duration – MAPL
convert_CF_Time_to_datetime_duration Interface
6 statements
Source File
public interface convert_CF_Time_to_datetime_duration
Calls
Called by
Module Procedures
private subroutine convert_CF_Time_to_datetime_duration_integer(cft, dt_duration, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time_Integer), intent(in) :: cft
type(datetime_duration), intent(out) :: dt_duration
integer, intent(out), optional :: rc
private subroutine convert_CF_Time_to_datetime_duration_real(cft, dt_duration, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time_Real), intent(in) :: cft
type(datetime_duration), intent(out) :: dt_duration
integer, intent(out), optional :: rc
private subroutine convert_CF_Time_to_datetime_duration_integer_duration(duration, units, dt_duration, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: duration
character(len=*), intent(in) :: units
type(datetime_duration), intent(out) :: dt_duration
integer, intent(out), optional :: rc
private subroutine convert_CF_Time_to_datetime_duration_real_duration(duration, units, dt_duration, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=R64), intent(in) :: duration
character(len=*), intent(in) :: units
type(datetime_duration), intent(out) :: dt_duration
integer, intent(out), optional :: rc
Call graph
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
convert_cf_time_to_datetime_duration_integer calls get_time_unit, mapl_assert, mapl_return, set_value
convert_cf_time_to_datetime_duration_integer_duration calls convert_cf_time_to_datetime_duration, mapl_return, mapl_verify
convert_cf_time_to_datetime_duration_real calls get_time_unit, mapl_assert, mapl_return, set_value
convert_cf_time_to_datetime_duration_real_duration calls convert_cf_time_to_datetime_duration, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_esmf_time_from_netcdf_datetime_integer calls convert_cf_time_to_datetime_duration
get_esmf_time_from_netcdf_datetime_real calls convert_cf_time_to_datetime_duration
test_convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration
test_set_esmf_timeinterval_integer calls convert_cf_time_to_datetime_duration
test_set_esmf_timeinterval_real calls convert_cf_time_to_datetime_duration
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf
compute_time_for_current calls time_esmf_to_real