convert_time_esmf2nc – MAPL
convert_time_esmf2nc Interface
3 statements
Source File
public interface convert_time_esmf2nc
Calls
Module Procedures
public subroutine time_esmf_2_nc_int(time, tunit, n, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: time
character(len=*), intent(in) :: tunit
integer(kind=ESMF_KIND_I8), intent(out) :: n
integer, intent(out), optional :: rc
Call graph
convert_time_esmf2nc calls time_esmf_2_nc_int
time_esmf_2_nc_int calls ESMF_TimeIntervalGet, parse_timeunit, mapl_return, mapl_verify
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_timeunit_i4 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
parse_timeunit_i8 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert