CoordinateVariable – MAPL
CoordinateVariable Interface
3 statements
Source File
public interface CoordinateVariable
Calls
Contents
Module Procedures
new_CoordinateVariable
Module Procedures
private function new_CoordinateVariable(var, coordinate_data, rc) result(coordinate_variable)
Arguments
Type Intent Optional Attributes Name
type(Variable), intent(in) :: var
class(*), intent(in) :: coordinate_data(:)
integer, intent(out), optional :: rc
Return Value type(CoordinateVariable)
Call graph
coordinatevariable calls new_coordinatevariable
new_coordinatevariable calls mapl_return, set_coordinate_data
mapl_return calls get_error_message, mapl_throw_exception
set_coordinate_data calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize