create_file_handle – MAPL
create_file_handle Interface
52 statements
Source File
interface
module function create_new_bundle(this,rc) result(new_bundle) class(MaskSamplerGeosat), intent(inout) :: this type(ESMF_FieldBundle) :: new_bundle integer, optional, intent(out) :: rc end function create_new_bundle
module subroutine add_metadata(this,currTime,rc)
Calls
private module subroutine create_file_handle(this, filename, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
class(MaskSamplerGeosat), intent(inout) :: this
character(len=*), intent(in) :: filename
integer, intent(out), optional :: rc
Call graph
create_file_handle calls create_file_handle, mapl_am_i_root, put_var, create, define_time_variable, mapl_return, mapl_verify, modify_variable
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
create calls mapl_return, mapl_verify, nf90_create
define_time_variable calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, mapl_assert, add_attribute, v_clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modify_variable calls mapl_return, at, begin, get, mapl_assert, next, get_dimensions, m_set