CubedSphereGridFactory – MAPL
CubedSphereGridFactory Interface
3 statements
Source File
public interface CubedSphereGridFactory
Calls
Module Procedures
private function CubedSphereGridFactory_from_parameters(unusable, grid_name, grid_type, im_world, lm, nx, ny, ims, jms, stretch_factor, target_lon, target_lat, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: grid_type
integer, intent(in), optional :: im_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(in), optional :: ims(:)
integer, intent(in), optional :: jms(:)
real(kind=REAL32), intent(in), optional :: stretch_factor
real(kind=REAL32), intent(in), optional :: target_lon
real(kind=REAL32), intent(in), optional :: target_lat
integer, intent(out), optional :: rc
Return Value type(CubedSphereGridFactory)
Call graph
cubedspheregridfactory calls cubedspheregridfactory_from_parameters
cubedspheregridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_bounds, set_with_default_character, set_with_default_integer, set_with_default_real64, set_with_default_real
check_and_fill_consistency calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize