cv_convert_doubles – MAPL
cv_convert_doubles Interface
61 statements
Source File
interface
Called by
public subroutine cv_convert_doubles(converter, in_, count_, out_) bind(c, name='cv_convert_doubles')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: converter
real(kind=c_double), intent(in) :: in_(*)
integer(kind=c_int), intent(in), value :: count_
real(kind=c_double), intent(out) :: out_(count_)
Call graph
convert_double_1d calls cv_convert_doubles
convert_double_2d calls cv_convert_doubles
convert_double_3d calls cv_convert_doubles
convert_double_4d calls cv_convert_doubles
convert_double_5d calls cv_convert_doubles
test_convert_double calls convert
test_convert_doubles calls convert
test_convert_float calls convert
test_convert_floats calls convert