cv_convert_floats – MAPL
cv_convert_floats Interface
61 statements
Source File
interface
Called by
public subroutine cv_convert_floats(converter, in_, count_, out_) bind(c, name='cv_convert_floats')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: converter
real(kind=c_float), intent(in) :: in_(*)
integer(kind=c_int), intent(in), value :: count_
real(kind=c_float), intent(out) :: out_(count_)
Call graph
convert_float_1d calls cv_convert_floats
convert_float_2d calls cv_convert_floats
convert_float_3d calls cv_convert_floats
convert_float_4d calls cv_convert_floats
convert_float_5d calls cv_convert_floats