deserialize_intrinsic – MAPL
deserialize_intrinsic Interface
13 statements
Source File
public interface deserialize_intrinsic
Calls
Called by
Module Procedures
private subroutine deserialize_string(buffer, str, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
character(len=:), allocatable :: str
integer, intent(out), optional :: rc
private subroutine deserialize_int32_0d(buffer, scalar, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
integer(kind=INT32), intent(out) :: scalar
integer, intent(out), optional :: rc
private subroutine deserialize_int32_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
integer(kind=INT32), intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
private subroutine deserialize_int64_0d(buffer, scalar, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
integer(kind=INT64), intent(out) :: scalar
integer, intent(out), optional :: rc
private subroutine deserialize_int64_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
integer(kind=INT64), intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
private subroutine deserialize_real32_0d(buffer, scalar, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
real(kind=REAL32), intent(out) :: scalar
integer, intent(out), optional :: rc
private subroutine deserialize_real32_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
real(kind=REAL32), intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
private subroutine deserialize_real64_0d(buffer, scalar, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
real(kind=REAL64), intent(out) :: scalar
integer, intent(out), optional :: rc
private subroutine deserialize_real64_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
real(kind=REAL64), intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
private subroutine deserialize_logical_0d(buffer, scalar, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
logical, intent(out) :: scalar
integer, intent(out), optional :: rc
private subroutine deserialize_logical_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
logical, intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
Call graph
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
deserialize_int32_0d calls mapl_assert, mapl_return
deserialize_int32_1d calls mapl_assert, mapl_return
deserialize_int64_0d calls mapl_assert, mapl_return
deserialize_int64_1d calls mapl_assert, mapl_return
deserialize_logical_0d calls mapl_assert, mapl_return
deserialize_logical_1d calls mapl_assert, mapl_return
deserialize_real32_0d calls mapl_assert, mapl_return
deserialize_real32_1d calls mapl_assert, mapl_return
deserialize_real64_0d calls mapl_assert, mapl_return
deserialize_real64_1d calls mapl_assert, mapl_return
deserialize_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
coordinatevariable_deserialize calls deserialize_intrinsic
deserialize calls deserialize_intrinsic
filemetadata_deserialize calls deserialize_intrinsic
historycollectionvector_deserialize calls deserialize_intrinsic
stringattributemap_deserialize calls deserialize_intrinsic
stringintegermap_deserialize calls deserialize_intrinsic
stringunlimitedentitymap_deserialize calls deserialize_intrinsic
stringvariablemap_deserialize calls deserialize_intrinsic
stringvector_deserialize calls deserialize_intrinsic
test_serialize_int64_array calls deserialize_intrinsic
test_serialize_int64_scalar calls deserialize_intrinsic
test_serialize_int_array calls deserialize_intrinsic
test_serialize_int_scalar calls deserialize_intrinsic
test_serialize_logical_array calls deserialize_intrinsic
test_serialize_logical_scalar calls deserialize_intrinsic
test_serialize_real_array calls deserialize_intrinsic
test_serialize_real_scalar calls deserialize_intrinsic
test_serialize_string calls deserialize_intrinsic
unlimitedentity_deserialize calls deserialize_intrinsic
variable_deserialize calls deserialize_intrinsic