DimsSpec – MAPL
DimsSpec Interface
5 statements
Source File
public interface DimsSpec
Calls
Called by
Contents
Module Procedures
new_DimsSpec_simple new_DimsSpec_w_ungridded new_DimsSpec_w_halo
Module Procedures
private pure function new_DimsSpec_simple(horz_stagger_loc, vert_stagger_loc) result(spec)
Arguments
Type Intent Optional Attributes Name
type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
type(VerticalStaggerLoc), intent(in) :: vert_stagger_loc
Return Value type(DimsSpec)
private pure function new_DimsSpec_w_ungridded(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs) result(spec)
Arguments
Type Intent Optional Attributes Name
type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
type(VerticalStaggerLoc), intent(in) :: vert_stagger_loc
type(UngriddedDimSpec), intent(in) :: ungridded_dim_specs(:)
Return Value type(DimsSpec)
private pure function new_DimsSpec_w_halo(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs, halo_width) result(spec)
Arguments
Type Intent Optional Attributes Name
type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
type(VerticalStaggerLoc), intent(in) :: vert_stagger_loc
type(UngriddedDimSpec), intent(in) :: ungridded_dim_specs(:)
integer, intent(in) :: halo_width
Return Value type(DimsSpec)
Call graph
dimsspec calls new_dimsspec_simple, new_dimsspec_w_halo, new_dimsspec_w_ungridded
new_dimsspec_simple calls dimsspec
new_dimsspec_w_ungridded calls dimsspec