DirectoryService – MAPL
DirectoryService Interface
3 statements
Source File
public interface DirectoryService
Calls
Module Procedures
private function new_DirectoryService(comm, unusable, rc) result(ds)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(DirectoryService)
Call graph
directoryservice calls new_directoryservice
new_directoryservice calls mpi_barrier, mpi_comm_dup, mpi_comm_rank, make_directory_window, mapl_return, mapl_verify, put_directory
make_directory_window calls mpi_comm_rank, mapl_verify, mpi_alloc_mem, mpi_win_create, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_directory calls mapl_verify, mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
get_error_message calls at, insert
mapl_throw_exception calls initialize