DistributedProfiler – MAPL
DistributedProfiler Interface
3 statements
Source File
public interface DistributedProfiler
Calls
Module Procedures
private function new_DistributedProfiler(name, gauge, comm, comm_world) result(distributed_profiler)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
class(AbstractGauge), intent(in) :: gauge
integer, intent(in) :: comm
integer, intent(in), optional :: comm_world
Return Value type(DistributedProfiler), target
Call graph
distributedprofiler calls new_distributedprofiler
new_distributedprofiler calls make_meter, set_comm_world, set_node