ESMF_ioDestroy – MAPL
ESMF_ioDestroy Interface
3 statements
Source File
public interface ESMF_ioDestroy
Calls
Called by
Contents
Module Procedures
MAPL_CFIODestroy
Module Procedures
public subroutine MAPL_CFIODestroy(MCFIO, RC)
The subroutine MAPL_CFIODestroy destroys a MAPL CFIO object. It closes any file associated with it and deallocates memory.
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(out), optional :: RC
Call graph
esmf_iodestroy calls mapl_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy, esmf_cfiofileclose, mapl_return, mapl_verify
esmf_cfiodestroy calls grids, cfio_close, esmf_cfiogriddestroy, esmf_cfiovarinfodestroy, varobjs
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
cfio_close calls ncclos, err
esmf_cfioget calls err
esmf_cfiosdffileclose calls cfio_close
esmf_cfiovarinfodestroy calls esmf_cfiogriddestroy, cnodedestroy, inodedestroy, rnodedestroy
get_error_message calls at
mapl_throw_exception calls initialize
test_main calls esmf_iodestroy
utcfio calls test_main