ESMF_CFIOVarReadT2 – MAPL
ESMF_CFIOVarReadT2 Interface
3 statements
Source File
public interface ESMF_CFIOVarReadT2
Calls
Contents
Module Procedures
ESMF_CFIOVarReadT3D__ ESMF_CFIOVarReadT2D__
Module Procedures
private subroutine ESMF_CFIOVarReadT3D__(cfio, vName, date, curTime, field, kbeg, kount, rc, cfio2)
ESMF_CFIOVarReadT3D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
integer, intent(in) :: date
yyyymmdd
integer, intent(in) :: curTime
hhmmss
real, pointer :: field(:,:,:)
array contains data
integer, intent(in), optional :: kbeg
first level to read
integer, intent(in), optional :: kount
number of levels to read
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -20 unable to find variable rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
private subroutine ESMF_CFIOVarReadT2D__(cfio, vName, date, curTime, field, kbeg, kount, rc, cfio2)
ESMF_CFIOVarReadT2D_ – Read a variable from an existing file !INTERFACE:
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
integer, intent(in) :: date
yyyymmdd
integer, intent(in) :: curTime
hhmmss
real, pointer :: field(:,:)
array contains data
integer, intent(in), optional :: kbeg
first level to read
integer, intent(in), optional :: kount
number of levels to read
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
Call graph
esmf_cfiovarreadt2 calls esmf_cfiovarreadt2d__, esmf_cfiovarreadt3d__
esmf_cfiovarreadt2d__ calls esmf_cfiovarread, getdate, cfio_parseinttime, diffdate, varobjs
esmf_cfiovarreadt3d__ calls esmf_cfiovarread, getdate, cfio_parseinttime, diffdate, varobjs
esmf_cfiovarread calls esmf_cfiovarread1d_, esmf_cfiovarread2d_, esmf_cfiovarread3d_
getdate calls getdateint4, getdateint8
diffdate calls cfio_parseinttime, julday
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, strtoint
esmf_cfiovarread2d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
getdateint4 calls getdateint8
getdateint8 calls cfio_parseinttime, julday, caldat