ESMFL_Bundle2State – MAPL
ESMFL_Bundle2State Interface
3 statements
Source File
public interface ESMFL_Bundle2State
Calls
Contents
Module Procedures
Bundle2State
Module Procedures
private subroutine Bundle2State(BUN, STA, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUN
type(ESMF_State), intent(inout) :: STA
integer, intent(out), optional :: rc
Call graph
esmfl_bundle2state calls bundle2state
bundle2state calls esmf_fieldbundleget, esmf_fieldget, esmf_stateget, mapl_am_i_root, mapl_assert, mapl_stateadd, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_stateadd calls mapl_stateaddbundle, mapl_stateaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_stateaddbundle calls mapl_stateaddbundle
mapl_stateaddfield calls mapl_stateaddfield
get_error_message calls at
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize