ESMFL_BundleGetPointerToData – MAPL
ESMFL_BundleGetPointerToData Interface
6 statements
Source File
public interface ESMFL_BundleGetPointerToData
Calls
Called by
Contents
Module Procedures
ESMFL_BundleGetPointerByIndex2 ESMFL_BundleGetPointerByIndex3 ESMFL_BundleGetPointerByName2 ESMFL_BundleGetPointerByName3
Module Procedures
private subroutine ESMFL_BundleGetPointerByIndex2(BUNDLE, INDEX, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
integer, intent(in) :: INDEX
real, pointer :: PTR(:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_BundleGetPointerByIndex3(BUNDLE, INDEX, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
integer, intent(in) :: INDEX
real, pointer :: PTR(:,:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_BundleGetPointerByName2(BUNDLE, NAME, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
character(len=*), intent(in) :: NAME
real, pointer :: PTR(:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_BundleGetPointerByName3(BUNDLE, NAME, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
character(len=*), intent(in) :: NAME
real, pointer :: PTR(:,:,:)
integer, intent(out), optional :: RC
Call graph
esmfl_bundlegetpointertodata calls esmfl_bundlegetpointerbyindex2, esmfl_bundlegetpointerbyindex3, esmfl_bundlegetpointerbyname2, esmfl_bundlegetpointerbyname3
esmfl_bundlegetpointerbyindex2 calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify
esmfl_bundlegetpointerbyindex3 calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify
esmfl_bundlegetpointerbyname2 calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify
esmfl_bundlegetpointerbyname3 calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_extdatainterpfield calls esmfl_bundlegetpointertodata
run_ calls esmfl_bundlegetpointertodata, mapl_extdatainterpfield