ESMFL_Diff – MAPL
ESMFL_Diff Interface
4 statements
Source File
public interface ESMFL_Diff
Calls
Module Procedures
private subroutine StateDiff(srcSTA, dstSTA, rc)
Determine the diff of two state.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: srcSTA
type(ESMF_State), intent(inout), optional :: dstSTA
integer, intent(out), optional :: rc
private subroutine BundleDiff(srcBUN, dstBUN, rc)
The subroutine BundleDiff determines the diff of two bundles.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
type(ESMF_FieldBundle), intent(inout), optional :: dstBUN
integer, intent(out), optional :: rc
return code
Call graph
esmfl_diff calls bundlediff, statediff
bundlediff calls ESMF_UtilStringInt2String, ESMF_VMBarrier, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, esmf_fieldget, arraygather, mapl_am_i_root, esmfl_failedrc, esmfl_fieldgetdims, mapl_return
statediff calls bundlediff, ESMF_VMGet, ESMF_VMGetCurrent, esmf_stateget, mapl_am_i_root, esmfl_failedrc, mapl_return, state2bundle