ESMF_CFIODownBit – MAPL
ESMF_CFIODownBit Interface
4 statements
Source File
public interface ESMF_CFIODownBit
Calls
Called by
Module Procedures
private subroutine ESMF_CFIODownBit3D_(x, xr, nbits, undef, flops, rc)
ESMF_CFIODownBit - GRIB-based compression pre-conditioner
Read more…
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:,:,:)
input array
real(kind=REAL32), intent(out) :: xr(:,:,:)
precision reduced array; can
Read more…
integer, intent(in) :: nbits
number of bits per word to retain - no action if nbits<1
real, intent(in), optional :: undef
logical, intent(in), optional :: flops
if true, uses slower float point based algorithm
integer, intent(out) :: rc
error code = 0 - all is well /= 0 - something went wrong
private subroutine ESMF_CFIODownBit2D_(x, xr, nbits, undef, flops, rc)
ESMF_CFIODownBit - GRIB-based compression pre-conditioner
Read more…
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:,:)
input array
real(kind=REAL32), intent(out) :: xr(:,:)
precision reduced array; can share storage with input array if it has same kind
integer, intent(in) :: nbits
number of bits per word to retain
real, intent(in), optional :: undef
missing value
logical, intent(in), optional :: flops
if true, uses slower float point based algorithm
integer, intent(out) :: rc
error code = 0 - all is well /= 0 - something went wrong
Call graph
esmf_cfiodownbit calls esmf_cfiodownbit2d_, esmf_cfiodownbit3d_
esmf_cfiodownbit2d_ calls shavemantissa32
esmf_cfiodownbit3d_ calls esmf_cfiodownbit2d_
mapl_cfiowritebundlewait calls esmf_cfiodownbit
utdownbit calls esmf_cfiodownbit
mapl_cfiowritebundle calls mapl_cfiowritebundlewait
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
test_main calls esmf_iowrite