ESMF_CFIOSdfVarWrite – MAPL
ESMF_CFIOSdfVarWrite Interface
3 statements
Source File
public interface ESMF_CFIOSdfVarWrite
Calls
Called by
Module Procedures
private subroutine ESMF_CFIOSdfVarWrite3D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, rc)
ESMF_CFIOSdfVarWrite3D_ – Write a variable to a output file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -15 data outside of valid range rc = -16 data outside of packing range rc = -17 data outside of pack and valid range rc = -38 error from NF90_VAR_PUT (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID (lat or lon) rc = -42 error from NF90_INQ_DIMID (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -45 error from NF90_VAR_PUT rc = -46 error from NF90_GET_VAR rc = -52 error from NF90_INQUIRE_VARIABLE rc = -53 error from NF90_GET_ATT
private subroutine ESMF_CFIOSdfVarWrite2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, rc)
ESMF_CFIOSdfVarWrite2D_ – Write a variable to a output file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
private subroutine ESMF_CFIOSdfVarWrite1D_(cfio, vName, field, date, curTime, timeString, rc)
ESMF_CFIOSdfVarWrite1D_ – Write a variable to a output file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Call graph
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfiosdfvarwrite1d_ calls cfio_sputvar, err, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, strtoint, writebnds
esmf_cfiosdfvarwrite2d_ calls cfio_putvar, cfio_sputvar, err, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, strtoint, writebnds
esmf_cfiosdfvarwrite3d_ calls cfio_putvar, err, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, strtoint, writebnds
cfio_putvar calls err, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_put_var, cfio_parseinttime, diffdate
cfio_sputvar calls err, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_put_var, cfio_parseinttime, diffdate
esmf_cfiosdffileclose calls cfio_close
esmf_cfiosdffilecreate calls err, esmf_cfioset, strtemplate_, cfio_create_, cfio_putcharatt, cfio_putintatt, cfio_putrealatt, esmf_cfioget, getlist
esmf_cfioset calls err, strtoint, addlist
strtemplate_ calls die, gx_
writebnds calls nf90_inq_varid, nf90_put_var, cfio_parseinttime, diffdate
esmf_cfiovarwrite1d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite2d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite3d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite calls esmf_cfiovarwrite1d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite3d_
mapl_cfiowritebundlewrite calls esmf_cfiovarwrite
test calls esmf_cfiovarwrite
mapl_cfiowritebundle calls mapl_cfiowritebundlewrite