ESMFL_StateGetPointerToData – MAPL
ESMFL_StateGetPointerToData Interface
10 statements
Source File
public interface ESMFL_StateGetPointerToData
Calls
Called by
Contents
Module Procedures
ESMFL_StateGetPtrToDataR4_1 ESMFL_StateGetPtrToDataR4_2 ESMFL_StateGetPtrToDataR4_3 ESMFL_StateGetPtrToDataR4_4 ESMFL_StateGetPtrToDataR8_1 ESMFL_StateGetPtrToDataR8_2 ESMFL_StateGetPtrToDataR8_3 ESMFL_StateGetPtrToDataR8_4
Module Procedures
private subroutine ESMFL_StateGetPtrToDataR4_1(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R4), pointer :: PTR(:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR4_2(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR4_3(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR4_4(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:,:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR8_1(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R8), pointer :: PTR(:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR8_2(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR8_3(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
private subroutine ESMFL_StateGetPtrToDataR8_4(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
Call graph
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
esmfl_stategetptrtodatar4_1 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar4_2 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar4_3 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar4_4 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar8_1 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar8_2 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar8_3 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
esmfl_stategetptrtodatar8_4 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
mapl_allocatecoupling calls mapl_allocatecoupling, esmf_fieldget, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_fieldalloccommit
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
comparestate calls esmfl_stategetpointertodata
copystate calls esmfl_stategetpointertodata
evaluate_box_mask calls esmfl_stategetpointertodata
evaluate_region_mask calls esmfl_stategetpointertodata
evaluate_zone_mask calls esmfl_stategetpointertodata
fillstate calls esmfl_stategetpointertodata
forceallocation calls esmfl_stategetpointertodata
initialize_ calls esmfl_stategetpointertodata, forceallocation
initialize calls esmfl_stategetpointertodata
mapl_extdataevaluatemask calls esmfl_stategetpointertodata
mapl_readforcingx calls esmfl_stategetpointertodata
run_ calls esmfl_stategetpointertodata, comparestate, copystate, fillstate, set_constant_field, calcderivedfield
set_constant_field calls esmfl_stategetpointertodata
calcderivedfield calls mapl_extdataevaluatemask
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2