ESMFL_Bundles2Bundle – MAPL
ESMFL_Bundles2Bundle Interface
3 statements
Source File
public interface ESMFL_Bundles2Bundle
Calls
Contents
Module Procedures
Bundles2Bundle
Module Procedures
private subroutine Bundles2Bundle(BUN1, BUN2, mergedBUN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUN1
type(ESMF_FieldBundle), intent(inout) :: BUN2
type(ESMF_FieldBundle), intent(inout) :: mergedBUN
integer, intent(out), optional :: rc
Call graph
esmfl_bundles2bundle calls bundles2bundle
bundles2bundle calls esmf_vmgetcurrent, mapl_verify, esmf_vmget, mapl_am_i_root, esmf_fieldbundleget, mapl_fieldbundleadd, mapl_return
mapl_verify calls mapl_throw_exception
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield