ESMFL_State2Bundle – MAPL
ESMFL_State2Bundle Interface
3 statements
Source File
public interface ESMFL_State2Bundle
Calls
Contents
Module Procedures
State2Bundle
Module Procedures
private subroutine State2Bundle(STA, BUN, usrfldlist, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STA
type(ESMF_FieldBundle), intent(inout) :: BUN
character(len=*), intent(in), optional :: usrfldlist
integer, intent(out), optional :: rc
Call graph
esmfl_state2bundle calls state2bundle
state2bundle calls esmf_vmgetcurrent, mapl_verify, esmf_stateget, esmf_vmget, mapl_return, mapl_am_i_root, esmf_fieldget, esmf_fieldbundlecreate, esmf_fieldbundleset, check_list_, mapl_fieldbundleadd
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_throw_exception calls initialize
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield