ESMF_CFIOVarReadT – MAPL
ESMF_CFIOVarReadT Interface
3 statements
Source File
public interface ESMF_CFIOVarReadT
Calls
Called by
Contents
Module Procedures
ESMF_CFIOVarReadT3D_ ESMF_CFIOVarReadT2D_
Module Procedures
private subroutine ESMF_CFIOVarReadT3D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, cfio2, rc)
ESMF_CFIOVarReadT3D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to read
integer, intent(in), optional :: kount
number of levels to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE rc = -99 must specify date/curTime of timeString
private subroutine ESMF_CFIOVarReadT2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, cfio2, rc)
ESMF_CFIOVarReadT2D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to read
integer, intent(in), optional :: kount
number of levels to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE rc = -99 must specify date/curTime of timeString
Call graph
esmf_cfiovarreadt calls esmf_cfiovarreadt2d_, esmf_cfiovarreadt3d_
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__, strtoint
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__, strtoint
esmf_cfiovarreadt2d__ calls esmf_cfiovarread, getdate, cfio_parseinttime, diffdate, varobjs
esmf_cfiovarreadt3d__ calls esmf_cfiovarread, getdate, cfio_parseinttime, diffdate, varobjs
esmf_cfiovarread calls esmf_cfiovarread1d_, esmf_cfiovarread2d_, esmf_cfiovarread3d_
getdate calls getdateint4, getdateint8
diffdate calls cfio_parseinttime, julday
mapl_cfioreadbundle calls esmf_cfiovarreadt
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread
utcfio calls test_main