ESMFL_statistics – MAPL
ESMFL_statistics Interface
4 statements
Source File
public interface ESMFL_statistics
Calls
Contents
Module Procedures
StateStatistics BundleStatistics
Module Procedures
private subroutine StateStatistics(srcSTA, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: srcSTA
integer, intent(out), optional :: rc
private subroutine BundleStatistics(srcBUN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
integer, intent(out), optional :: rc
Call graph
esmfl_statistics calls statestatistics, bundlestatistics
statestatistics calls statediff, mapl_return, mapl_verify
bundlestatistics calls mapl_return, mapl_verify, bundlediff
statediff calls mapl_return, bundlediff, esmf_vmgetcurrent, esmf_stateget, esmf_vmget, mapl_am_i_root, esmfl_failedrc, state2bundle
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
bundlediff calls mapl_return, arraygather, esmf_vmbarrier, esmfl_fieldgetdims, esmf_utilstringint2string, esmf_vmgetcurrent, esmf_vmget, mapl_am_i_root, esmfl_failedrc, esmf_fieldbundleget, esmf_fieldget