ESMFL_Regrid – MAPL
ESMFL_Regrid Interface
6 statements
Source File
public interface ESMFL_Regrid
Calls
Contents
Module Procedures
BundleRegrid StateRegrid FieldRegrid1 BundleRegrid1
Module Procedures
private subroutine BundleRegrid(srcBUN, dstBUN, rc)
The subroutine BundleRegrid regrids a source bundle (srcBUN) into a destination bundle (dstBUN) using hinterp. A bundle is thought of as being comprised of n 2D slices (nslices) distributed among the n PEs (ns_per_pe). The limits among each ns_per_pe region are given by n1 and n2 which are functions of mype (the local PE):
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
source bundle
type(ESMF_FieldBundle), intent(inout) :: dstBUN
destination bundle
integer, intent(out), optional :: rc
return code
private subroutine StateRegrid(srcSTA, dstSTA, rc)
The subroutine StateRegrid regrids a state.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: srcSTA
type(ESMF_State), intent(inout) :: dstSTA
integer, intent(out), optional :: rc
return code
private subroutine FieldRegrid1(srcFLD, Sgrid2D, dstFLD, Dgrid2D, vm, rh, fname, rc)
The subroutine FieldRegrid1 regrids 3D fields using ESMF_FieldRegrid.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: srcFLD
type(ESMF_Grid), intent(in) :: Sgrid2D
type(ESMF_Field), intent(inout) :: dstFLD
type(ESMF_Grid), intent(in) :: Dgrid2D
type(ESMF_VM), intent(inout) :: vm
type(ESMF_RouteHandle), intent(inout) :: rh
character(len=*), intent(in) :: fname
integer, intent(out), optional :: rc
private subroutine BundleRegrid1(srcBUN, Sgrid2D, dstBUN, Dgrid2D, vm, rh, rc)
The subroutine BundleRegrid1 regrids members of a bundle using ESMF_FieldRegrid.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
type(ESMF_Grid), intent(in) :: Sgrid2D
type(ESMF_FieldBundle), intent(inout) :: dstBUN
type(ESMF_Grid), intent(in) :: Dgrid2D
type(ESMF_VM), intent(inout) :: vm
type(ESMF_RouteHandle), intent(inout) :: rh
integer, intent(out), optional :: rc
Call graph
esmfl_regrid calls bundleregrid, bundleregrid1, fieldregrid1, stateregrid
bundleregrid calls ESMF_VMGet, ESMF_VMGetCurrent, esmfl_failedrc, mapl_return
bundleregrid1 calls ESMF_VMGet, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_gridget, mapl_return, mapl_verify
stateregrid calls bundleregrid, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundlecreate, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_assert, esmfl_failedrc, esmfl_stategetfield, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
esmfl_failedrc calls ESMF_Finalize
esmfl_stategetfield calls esmf_fieldbundleget, esmf_stateget, mapl_assert, mapl_return, mapl_verify, esmf_fieldemptycreate, mapl_allocatecoupling, mapl_fieldbundleadd, mapl_fieldcreate
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception