ESMFL_FieldGetPointerToData – MAPL
ESMFL_FieldGetPointerToData Interface
10 statements
Source File
public interface ESMFL_FieldGetPointerToData
Calls
Called by
Module Procedures
private subroutine ESMFL_FieldGetPtrToDataR4_1(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R4), pointer :: PTR(:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR4_2(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR4_3(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR4_4(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:,:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR8_1(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R8), pointer :: PTR(:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR8_2(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR8_3(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:)
integer, intent(out), optional :: RC
private subroutine ESMFL_FieldGetPtrToDataR8_4(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:,:)
integer, intent(out), optional :: RC
Call graph
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar4_1, esmfl_fieldgetptrtodatar4_2, esmfl_fieldgetptrtodatar4_3, esmfl_fieldgetptrtodatar4_4, esmfl_fieldgetptrtodatar8_1, esmfl_fieldgetptrtodatar8_2, esmfl_fieldgetptrtodatar8_3, esmfl_fieldgetptrtodatar8_4
esmfl_fieldgetptrtodatar4_1 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_4 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_1 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_4 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
regridscalar calls esmfl_fieldgetpointertodata
regridvector calls esmfl_fieldgetpointertodata
swap_undef_value calls esmfl_fieldgetpointertodata
bundlepost calls regridscalar, regridvector
interp_accumulate_fields calls regridscalar, regridvector
process_data_from_file calls regridscalar, regridvector, swap_undef_value
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls bundlepost, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls write_to_file
time_ave calls mapl_read_bundle, write_to_file
ut_regridding calls mapl_read_bundle, write_to_file