ESMF_CFIOVarRead – MAPL
ESMF_CFIOVarRead Interface
3 statements
Source File
public interface ESMF_CFIOVarRead
Calls
Called by
Contents
Module Procedures
ESMF_CFIOVarRead3D_ ESMF_CFIOVarRead2D_ ESMF_CFIOVarRead1D_
Module Procedures
private subroutine ESMF_CFIOVarRead3D_(cfio, vName, field, date, curTime, kbeg, kount, xBeg, xCount, yBeg, yCount, timeString, rc)
ESMF_CFIOVarRead3D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
integer, intent(in), optional :: xBeg
first point for lon
integer, intent(in), optional :: xCount
number of points to read
integer, intent(in), optional :: yBeg
first point for lat
integer, intent(in), optional :: yCount
number of points to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
private subroutine ESMF_CFIOVarRead2D_(cfio, vName, field, date, curTime, kbeg, kount, xBeg, xCount, yBeg, yCount, timeString, rc)
ESMF_CFIOVarRead2D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
integer, intent(in), optional :: xBeg
first point for lon
integer, intent(in), optional :: xCount
number of points to read
integer, intent(in), optional :: yBeg
first point for lat
integer, intent(in), optional :: yCount
number of points to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
private subroutine ESMF_CFIOVarRead1D_(cfio, vName, field, date, curTime, xBeg, xCount, timeString, rc)
ESMF_CFIOVarRead1D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: xBeg
first point for lon
integer, intent(in), optional :: xCount
number of points to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Call graph
esmf_cfiovarread calls esmf_cfiovarread1d_, esmf_cfiovarread2d_, esmf_cfiovarread3d_
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, strtoint
esmf_cfiovarread2d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfioget calls err
esmf_cfiovarinfoget calls attcharcnts, attintcnts, attrealcnts, err
esmf_cfiosdfvarread1d_ calls strtoint, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiosdfvarread2d_ calls strtoint, err, cfio_getvar, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiosdfvarread3d_ calls strtoint, err, cfio_getvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiovarreadt2d__ calls esmf_cfiovarread
esmf_cfiovarreadt3d__ calls esmf_cfiovarread
mapl_cfioreadbundle calls esmf_cfiovarread, esmf_cfiovarreadt
test calls esmf_cfiovarread
esmf_cfiovarreadt2 calls esmf_cfiovarreadt2d__, esmf_cfiovarreadt3d__
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
esmf_cfiovarreadt calls esmf_cfiovarreadt2d_, esmf_cfiovarreadt3d_
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread
utcfio calls test_main