ESMF_CFIOSdfVarReadT – MAPL
ESMF_CFIOSdfVarReadT Interface
3 statements
Source File
public interface ESMF_CFIOSdfVarReadT
Calls
Contents
Module Procedures
ESMF_CFIOSdfVarReadT3D_ ESMF_CFIOSdfVarReadT2D_ ESMF_CFIOSdfVarReadT3D__ ESMF_CFIOSdfVarReadT2D__
Module Procedures
private subroutine ESMF_CFIOSdfVarReadT3D_(cfio, vName, field, timeString, cfio2, rc)
ESMF_CFIOSdfVarReadT3D_ – Read a variable from an existing file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:,:)
array contains data
character(len=*), intent(in) :: timeString
string expression for date and time
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_VAR_PUT (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID (lat or lon) rc = -42 error from NF90_INQ_DIMID (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE rc = -99 must specify date/curTime of timeString
private subroutine ESMF_CFIOSdfVarReadT2D_(cfio, vName, field, timeString, cfio2, rc)
ESMF_CFIOSdfVarReadT2D_` – Read a variable from an existing file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:)
array contains data
character(len=*), intent(in) :: timeString
string expression for date and time
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_VAR_PUT (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID (lat or lon) rc = -42 error from NF90_INQ_DIMID (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NV_GET_VARA rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE rc = -99 must specify date/curTime of timeString
private subroutine ESMF_CFIOSdfVarReadT3D__(cfio, vName, date, curTime, field, rc, cfio2)
ESMF_CFIOSdfVarReadT3D_ – Read a variable from an existing file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
integer, intent(in) :: date
yyyymmdd
integer, intent(in) :: curTime
hhmmss
real, pointer :: field(:,:,:)
array contains data
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_VAR_PUT (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID (lat or lon) rc = -42 error from NF90_INQ_DIMID (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
private subroutine ESMF_CFIOSdfVarReadT2D__(cfio, vName, date, curTime, field, rc, cfio2)
ESMF_CFIOSdfVarReadT2D_ – Read a variable from an existing file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
integer, intent(in) :: date
yyyymmdd
integer, intent(in) :: curTime
hhmmss
real, pointer :: field(:,:)
array contains data
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_VAR_PUT (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID (lat or lon) rc = -42 error from NF90_INQ_DIMID (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
Call graph
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d_, esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d_, esmf_cfiosdfvarreadt3d__
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__, strtoint
esmf_cfiosdfvarreadt2d__ calls esmf_cfiosdfvarread, getdate, cfio_getmissing, diffdate, err, getbegdatetime, varobjs
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__, strtoint
esmf_cfiosdfvarreadt3d__ calls esmf_cfiosdfvarread, getdate, cfio_getmissing, diffdate, err, getbegdatetime, varobjs
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
getdate calls getdateint4, getdateint8
cfio_getmissing calls err, nf90_get_att, nf90_inquire, nf90_inquire_attribute, nf90_inquire_variable
diffdate calls cfio_parseinttime, julday
getbegdatetime calls getdate, err, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_inquire, nf90_inquire_dimension, nf90_inquire_variable, cfio_parseinttime, identifydim, parsetimeunits