ESMF_CFIOVarWrite – MAPL
ESMF_CFIOVarWrite Interface
3 statements
Source File
public interface ESMF_CFIOVarWrite
Calls
Called by
Contents
Module Procedures
ESMF_CFIOVarWrite3D_ ESMF_CFIOVarWrite2D_ ESMF_CFIOVarWrite1D_
Module Procedures
private subroutine ESMF_CFIOVarWrite3D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
ESMF_CFIOVarWrite3D_ – Write a variable to a output file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
string expression for date and time
logical, intent(in), optional :: doComp
do compression
logical, intent(in), optional :: doChunk
do chunk compression
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -15 data outside of valid range rc = -16 data outside of packing range rc = -17 data outside of pack and valid range rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -45 error from NF90_PUT_VAR rc = -46 error from NF90_GET_VAR rc = -52 error from NF90_INQUIRE_VARIABLE rc = -53 error from NF90_GET_ATT rc = -54 Format is not known
private subroutine ESMF_CFIOVarWrite2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
ESMF_CFIOVarWrite2D_ – Write a variable to a output file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
string expression for date and time
logical, intent(in), optional :: doComp
do compression
logical, intent(in), optional :: doChunk
do chunk compression
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -15 data outside of valid range rc = -16 data outside of packing range rc = -17 data outside of pack and valid range rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -45 error from NF90_PUT_VAR rc = -46 error from NF90_GET_VAR rc = -52 error from NF90_INQUIRE_VARIABLE rc = -53 error from NF90_GET_ATT rc = -54 Format is not known
private subroutine ESMF_CFIOVarWrite1D_(cfio, vName, field, date, curTime, timeString, rc)
ESMF_CFIOVarWrite1D_ – Write a variable to a output file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -15 data outside of valid range rc = -16 data outside of packing range rc = -17 data outside of pack and valid range rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -45 error from NF90_PUT_VAR rc = -46 error from NF90_GET_VAR rc = -52 error from NF90_INQUIRE_VARIABLE rc = -53 error from NF90_GET_ATT rc = -54 Format is not known
Call graph
esmf_cfiovarwrite calls esmf_cfiovarwrite1d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite3d_
esmf_cfiovarwrite1d_ calls esmf_cfiosdfvarwrite, esmf_cfioget, strtoint
esmf_cfiovarwrite2d_ calls esmf_cfiosdfvarwrite, esmf_cfioget, strtoint
esmf_cfiovarwrite3d_ calls esmf_cfiosdfvarwrite, esmf_cfioget, strtoint
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfioget calls err
esmf_cfiosdfvarwrite1d_ calls strtoint, err, cfio_sputvar, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, writebnds, varobjs
esmf_cfiosdfvarwrite2d_ calls strtoint, err, cfio_putvar, cfio_sputvar, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, writebnds, varobjs
esmf_cfiosdfvarwrite3d_ calls strtoint, err, cfio_putvar, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, writebnds, varobjs
mapl_cfiowritebundlewrite calls esmf_cfiovarwrite
test calls esmf_cfiovarwrite
mapl_cfiowritebundle calls mapl_cfiowritebundlewrite
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
test_main calls esmf_iowrite