Esmf_TestMethod – MAPL
Esmf_TestMethod Interface
4 statements
Source File
public interface Esmf_TestMethod
Calls
Module Procedures
private function newEsmf_TestMethod_basic(name, userMethod, numPETs) result(esmf_Test)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
procedure(runMethod) :: userMethod
integer, intent(in) :: numPETs
Return Value type(ESMF_TestMethod), target
private function newEsmf_TestMethod_setUpTearDown(name, userMethod, numPETs, setUp, tearDown) result(esmf_Test)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
procedure(runMethod) :: userMethod
integer, intent(in) :: numPETs
procedure(runMethod) :: setUp
procedure(runMethod) :: tearDown
Return Value type(ESMF_TestMethod), target
Call graph
esmf_testmethod calls newesmf_testmethod_basic, newesmf_testmethod_setupteardown
newesmf_testmethod_basic calls setname, settestparameter
newesmf_testmethod_setupteardown calls setname, settestparameter