ESMFL_Add2Bundle – MAPL
ESMFL_Add2Bundle Interface
3 statements
Source File
public interface ESMFL_Add2Bundle
Calls
Contents
Module Procedures
Add2Bundle
Module Procedures
private subroutine Add2Bundle(BUN, mergedBUN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUN
type(ESMF_FieldBundle), intent(inout) :: mergedBUN
integer, intent(out), optional :: rc
Call graph
esmfl_add2bundle calls add2bundle
add2bundle calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, mapl_am_i_root, mapl_fieldbundleadd, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield
get_error_message calls at
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize