ESMFL_FCOLLECT – MAPL
ESMFL_FCOLLECT Interface
5 statements
Source File
public interface ESMFL_FCOLLECT
Calls
Called by
Module Procedures
private subroutine ESMFL_FCOLLECT_I4(GRID, FULLINPUT, INPUT, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: GRID
integer, intent(inout) :: FULLINPUT(:)
integer, intent(in) :: INPUT(:)
integer, intent(out), optional :: rc
private subroutine ESMFL_FCOLLECT_R4(GRID, FULLINPUT, INPUT, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: GRID
real, intent(inout) :: FULLINPUT(:)
real, intent(in) :: INPUT(:)
integer, intent(out), optional :: rc
private subroutine ESMFL_FCOLLECT_R8(GRID, FULLINPUT, INPUT, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: GRID
real(kind=ESMF_KIND_R8), intent(inout) :: FULLINPUT(:)
real(kind=ESMF_KIND_R8), intent(in) :: INPUT(:)
integer, intent(out), optional :: rc
Call graph
esmfl_fcollect calls esmfl_fcollect_i4, esmfl_fcollect_r4, esmfl_fcollect_r8
esmfl_fcollect_i4 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsallgatherv, mapl_distgridget, mapl_return, mapl_verify
esmfl_fcollect_r4 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsallgatherv, mapl_distgridget, mapl_return, mapl_verify
esmfl_fcollect_r8 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsallgatherv, mapl_distgridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commsallgatherv calls mapl_commsallgatherv_i4_1, mapl_commsallgatherv_r4_1, mapl_commsallgatherv_r8_1
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_commsallgatherv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_allgatherv
mapl_commsallgatherv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_allgatherv
mapl_commsallgatherv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_allgatherv
mapl_throw_exception calls initialize
mapl_locstreamcreatexform calls esmfl_fcollect
mapl_locstreamtransformt2t calls esmfl_fcollect
mapl_locstreamtransform calls mapl_locstreamtransformt2t, mapl_locstreamtransformt2tr4r8, mapl_locstreamtransformt2tr8r4
initialize calls mapl_locstreamcreatexform
mapl_locstreamtransformt2tr4r8 calls mapl_locstreamtransformt2t
mapl_locstreamtransformt2tr8r4 calls mapl_locstreamtransformt2t
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run calls regridtransform, regridtransformt2g, regridtransformt2g2g