ESMF_CFIOEosVarWrite – MAPL
ESMF_CFIOEosVarWrite Interface
3 statements
Source File
public interface ESMF_CFIOEosVarWrite
Calls
Contents
Module Procedures
ESMF_CFIOEosVarWrite3D_ ESMF_CFIOEosVarWrite2D_ ESMF_CFIOEosVarWrite1D_
Module Procedures
private subroutine ESMF_CFIOEosVarWrite3D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
ESMF_CFIOEosVarWrite3D_ – Write a variable to a output file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
logical, intent(in), optional :: doComp
do szip compression
logical, intent(in), optional :: doChunk
do szip compression string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -15 data outside of valid range rc = -16 data outside of packing range rc = -17 data outside of pack and valid range rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -45 error from NF90_PUT_VAR rc = -46 error from NF90_GET_VAR rc = -52 error from NF90_INQUIRE_VARIABLE rc = -53 error from NF90_GET_ATT
private subroutine ESMF_CFIOEosVarWrite2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
logical, intent(in), optional :: doComp
do szip compression
logical, intent(in), optional :: doChunk
do szip compression string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
private subroutine ESMF_CFIOEosVarWrite1D_(cfio, vName, field, date, curTime, timeString, doComp, doChunk, rc)
ESMF_CFIOEosVarWrite1D_ – Write a variable to a output file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
character(len=*), intent(in), optional :: timeString
logical, intent(in), optional :: doComp
do szip compression
logical, intent(in), optional :: doChunk
do szip compression string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Call graph
esmf_cfioeosvarwrite calls esmf_cfioeosvarwrite1d_, esmf_cfioeosvarwrite2d_, esmf_cfioeosvarwrite3d_
esmf_cfioeosvarwrite1d_ calls eos_putvar, err, strtoint, writebnds, varobjs
esmf_cfioeosvarwrite2d_ calls eos_putvar, err, strtoint, writebnds, varobjs
esmf_cfioeosvarwrite3d_ calls eos_putvar, err, strtoint, writebnds, varobjs
writebnds calls varobjs, diffdate
diffdate calls cfio_parseinttime, julday