EtaHybridVerticalCoordinate – MAPL
EtaHybridVerticalCoordinate Interface
5 statements
Source File
public interface EtaHybridVerticalCoordinate
Calls
Called by
Contents
Module Procedures
new_EtaHybridVerticalCoordinate_by_ak_bk new_EtaHybridVerticalCoordinate_by_cfg new_EtaHybridVerticalCoordinate_by_file
Module Procedures
private function new_EtaHybridVerticalCoordinate_by_ak_bk(ak, bk, unusable, ref_pressure, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: ak(:)
real(kind=REAL64), intent(in) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=REAL64), intent(in), optional :: ref_pressure
integer, intent(inout), optional :: rc
Return Value type(EtaHybridVerticalCoordinate)
private function new_EtaHybridVerticalCoordinate_by_cfg(config, unusable, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(inout), optional :: rc
Return Value type(EtaHybridVerticalCoordinate)
private function new_EtaHybridVerticalCoordinate_by_file(filename, unusable, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(inout), optional :: rc
Return Value type(EtaHybridVerticalCoordinate)
Call graph
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_cfg, new_etahybridverticalcoordinate_by_file
new_etahybridverticalcoordinate_by_ak_bk calls mapl_assert
new_etahybridverticalcoordinate_by_cfg calls etahybridverticalcoordinate, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine, mapl_verify
new_etahybridverticalcoordinate_by_file calls etahybridverticalcoordinate, ESMF_ConfigLoadFile, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_eta_onestep_r4 calls etahybridverticalcoordinate, get_eta
get_eta_onestep_r8 calls etahybridverticalcoordinate, get_eta
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8
get_eta_r4 calls get_eta