ExtDataOldTypesCreator – MAPL
ExtDataOldTypesCreator Interface
3 statements
Source File
public interface ExtDataOldTypesCreator
Calls
Module Procedures
public function new_ExtDataOldTypesCreator(config_file, current_time, unusable, rc) result(ExtDataObj)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: config_file
type(ESMF_Time), intent(in) :: current_time
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ExtDataOldTypesCreator)
Call graph
extdataoldtypescreator calls new_extdataoldtypescreator
new_extdataoldtypescreator calls mapl_return, mapl_verify, new_extdataconfig_from_yaml
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
new_extdataconfig_from_yaml calls mapl_return, mapl_verify, new_extdataconfig_from_yaml, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigIterLoop, esmf_hconfigasi4, esmf_hconfigasstringseq, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, insert, add_new_rule, m_at, sort_rules_by_start