ExtDataMask – MAPL
ExtDataMask Interface
3 statements
Source File
public interface ExtDataMask
Calls
Contents
Module Procedures
new_ExtDataMask
Module Procedures
private function new_ExtDataMask(mask_expression, rc) result(new_mask)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mask_expression
integer, intent(out), optional :: rc
Return Value type(ExtDataMask)
Call graph
extdatamask calls new_extdatamask
new_extdatamask calls mapl_assert, esmf_utilstringlowercase, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message