ExtDataNG_IOBundle – MAPL
ExtDataNG_IOBundle Interface
3 statements
Source File
public interface ExtDataNG_IOBundle
Calls
Called by
Contents
Module Procedures
new_ExtDataNG_IOBundle
Module Procedures
public function new_ExtDataNG_IOBundle(bracket_side, entry_index, file_name, time_index, regrid_method, fraction, template, metadata_coll_id, server_coll_id, items, on_tiles, rc) result(io_bundle)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: bracket_side
integer, intent(in) :: entry_index
character(len=*), intent(in) :: file_name
integer, intent(in) :: time_index
integer, intent(in) :: regrid_method
integer, intent(in) :: fraction
character(len=*), intent(in) :: template
integer, intent(in) :: metadata_coll_id
integer, intent(in) :: server_coll_id
type(GriddedIOitemVector) :: items
logical, intent(in) :: on_tiles
integer, intent(out), optional :: rc
Return Value type(ExtDataNG_IOBundle)
Call graph
extdatang_iobundle calls new_extdatang_iobundle
new_extdatang_iobundle calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
iobundle_add_entry calls extdatang_iobundle
run_ calls iobundle_add_entry