ExtDataTimeSample – MAPL
ExtDataTimeSample Interface
3 statements
Source File
public interface ExtDataTimeSample
Calls
Contents
Module Procedures
new_ExtDataTimeSample
Module Procedures
private function new_ExtDataTimeSample(config, unusable, rc) result(TimeSample)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ExtDataTimeSample)
Call graph
extdatatimesample calls new_extdatatimesample
new_extdatatimesample calls esmf_hconfigaslogical, esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify, set_defaults, string_to_esmf_time, source_time
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_defaults calls mapl_return, mapl_verify, source_time
string_to_esmf_time calls mapl_return, mapl_verify, ESMF_TimeSet, string_to_integer_date, string_to_integer_time
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
string_to_integer_date calls mapl_return
string_to_integer_time calls mapl_return