ExtDataRule – MAPL
ExtDataRule Interface
3 statements
Source File
public interface ExtDataRule
Calls
Contents
Module Procedures
new_ExtDataRule
Module Procedures
private function new_ExtDataRule(config, sample_map, key, unusable, multi_rule, rc) result(rule)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: config
type(ExtDataTimeSampleMap) :: sample_map
character(len=*), intent(in) :: key
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: multi_rule
integer, intent(out), optional :: rc
Return Value type(ExtDataRule)
Call graph
extdatarule calls new_extdatarule
new_extdatarule calls esmf_hconfigaslogical, esmf_hconfigasr4seq, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, insert, mapl_assert, linear_trans, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize