ExtDataFileStream – MAPL
ExtDataFileStream Interface
3 statements
Source File
public interface ExtDataFileStream
Calls
Contents
Module Procedures
new_ExtDataFileStream
Module Procedures
private function new_ExtDataFileStream(config, current_time, unusable, rc) result(data_set)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: config
type(ESMF_Time), intent(in) :: current_time
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ExtDataFileStream)
Call graph
extdatafilestream calls new_extdatafilestream
new_extdatafilestream calls ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, esmf_hconfigasstring, esmf_hconfigisdefined, file_template, mapl_assert, mapl_dataaddcollection, mapl_return, mapl_verify, string_to_esmf_time, string_to_esmf_timeinterval, valid_range
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_dataaddcollection calls begin, get, next, push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_to_esmf_time calls ESMF_TimeSet, mapl_return, mapl_verify, string_to_integer_date, string_to_integer_time
string_to_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_assert, mapl_return, mapl_verify
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
string_to_integer_date calls mapl_return
string_to_integer_time calls mapl_return