ExtDataDerived – MAPL
ExtDataDerived Interface
3 statements
Source File
public interface ExtDataDerived
Calls
Module Procedures
private function new_ExtDataDerived(config, unusable, rc) result(rule)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ExtDataDerived)
Call graph
extdataderived calls new_extdataderived
new_extdataderived calls esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize