extract_CF_Time_duration – MAPL
extract_CF_Time_duration Interface
4 statements
Source File
public interface extract_CF_Time_duration
Calls
Module Procedures
private subroutine extract_CF_Time_duration_cf_time_real(cft, duration, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time_Real), intent(in) :: cft
real(kind=R64), intent(out) :: duration
integer, intent(out), optional :: rc
private subroutine extract_CF_Time_duration_cf_time_integer(cft, duration, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time_Integer), intent(in) :: cft
integer, intent(out) :: duration
integer, intent(out), optional :: rc
Call graph
extract_cf_time_duration calls extract_cf_time_duration_cf_time_integer, extract_cf_time_duration_cf_time_real
extract_cf_time_duration_cf_time_integer calls mapl_return
extract_cf_time_duration_cf_time_real calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize