FieldGetLocalElementCount – MAPL
FieldGetLocalElementCount Interface
3 statements
Source File
public interface FieldGetLocalElementCount
Calls
Called by
Module Procedures
private function get_local_element_count(x, rc) result(element_count)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
Return Value integer, allocatable, (:)
Call graph
fieldgetlocalelementcount calls get_local_element_count
get_local_element_count calls esmf_fieldget, mapl_fieldgetlocalelementcount, mapl_return, mapl_verify
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_return, mapl_verify, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
are_broadcast_conformable calls fieldgetlocalelementcount
are_conformable_scalar calls fieldgetlocalelementcount
gemv_r4 calls fieldgetlocalelementcount
gemv_r8 calls fieldgetlocalelementcount
get_local_size calls fieldgetlocalelementcount
test_fieldgetlocalelementcount calls fieldgetlocalelementcount
fieldgemv calls gemv_r4, gemv_r8
fieldgetlocalsize calls get_local_size
fieldsarebroadcastconformable calls are_broadcast_conformable
fieldsareconformable calls are_conformable_scalar