FieldConvertPrec – MAPL
FieldConvertPrec Interface
3 statements
Source File
public interface FieldConvertPrec
Calls
Called by
Contents
Module Procedures
convert_prec
Module Procedures
private subroutine convert_prec(x, y, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Call graph
fieldconvertprec calls convert_prec
convert_prec calls esmf_fieldget, fieldcopy, mapl_assert, convert_prec_r4_to_r8, convert_prec_r8_to_r4, is_valid_typekind, mapl_return, mapl_verify
fieldcopy calls copy
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_prec_r4_to_r8 calls mapl_return, mapl_verify, assign_fptr
convert_prec_r8_to_r4 calls mapl_return, mapl_verify, assign_fptr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
copy calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_fieldconvertprec_r4r8 calls fieldconvertprec