FieldIsConstant – MAPL
FieldIsConstant Interface
3 statements
Source File
public interface FieldIsConstant
Calls
Called by
Module Procedures
private function FieldIsConstantR4(field, constant_val, rc) result(field_is_constant)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
real(kind=ESMF_KIND_R4) :: constant_val
integer, intent(out), optional :: rc
Return Value logical
Call graph
fieldisconstant calls fieldisconstantr4
fieldisconstantr4 calls esmf_fieldget, assign_fptr, mapl_assert, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
comparestate calls fieldisconstant
run_ calls comparestate