FieldClone – MAPL
FieldClone Interface
3 statements
Source File
public interface FieldClone
Calls
Called by
Contents
Module Procedures
clone
Module Procedures
private subroutine clone(x, y, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Call graph
fieldclone calls clone
clone calls ESMF_GridGet, esmf_fieldcreate, esmf_fieldget, mapl_assert, get_local_element_count, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_throw_exception calls initialize
compile calls fieldclone
test_fieldclone3d calls fieldclone
parsef calls compile
mapl_stateeval calls parsef
calcderivedfield calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval