FieldsAreBroadCastConformable – MAPL
FieldsAreBroadCastConformable Interface
3 statements
Source File
public interface FieldsAreBroadCastConformable
Calls
Called by
Module Procedures
private function are_broadcast_conformable(x, y, rc) result(conformable)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Return Value logical
Call graph
fieldsarebroadcastconformable calls are_broadcast_conformable
are_broadcast_conformable calls esmf_fieldget, fieldgetlocalelementcount, fieldsareconformable, mapl_return, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, fieldgetlocalelementcount, mapl_return, mapl_verify
get_error_message calls at, insert
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_throw_exception calls initialize
copy_broadcast calls fieldsarebroadcastconformable
mapl_stateeval calls fieldsarebroadcastconformable, evalf
fieldcopybroadcast calls copy_broadcast
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
evalf calls fieldcopybroadcast
initialize_ calls fillstate
run_ calls calcderivedfield, evaluate_derived_field, fillstate
run calls mapl_runexpression
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem