FieldGEMV – MAPL
FieldGEMV Interface
4 statements
Source File
public interface FieldGEMV
Calls
Module Procedures
private subroutine gemv_r4(alpha, A, x, beta, y, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: alpha
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:)
type(ESMF_Field), intent(inout) :: x(:)
real(kind=ESMF_KIND_R4), intent(in) :: beta
type(ESMF_Field), intent(inout) :: y(:)
integer, intent(out), optional :: rc
private subroutine gemv_r8(alpha, A, x, beta, y, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: alpha
real(kind=ESMF_KIND_R8), intent(in) :: A(:,:,:)
type(ESMF_Field), intent(inout) :: x(:)
real(kind=ESMF_KIND_R8), intent(in) :: beta
type(ESMF_Field), intent(inout) :: y(:)
integer, intent(out), optional :: rc
Call graph
fieldgemv calls gemv_r4, gemv_r8
gemv_r4 calls esmf_fieldget, assign_fptr, fieldgetlocalelementcount, fieldsareconformable, mapl_assert, verify_typekind, mapl_return, mapl_verify
gemv_r8 calls esmf_fieldget, assign_fptr, fieldgetlocalelementcount, fieldsareconformable, mapl_assert, verify_typekind, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldgetlocalelementcount calls get_local_element_count
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
verify_typekind calls verify_typekind_array, verify_typekind_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, fieldgetlocalelementcount, mapl_return, mapl_verify
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
verify_typekind_array calls verify_typekind, mapl_return, mapl_verify
verify_typekind_scalar calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify