FieldSpread – MAPL
FieldSpread Interface
3 statements
Source File
public interface FieldSpread
Calls
Contents
Module Procedures
spread_scalar
Module Procedures
private function spread_scalar(source, ncopies, rc) result(vector)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: source
integer, intent(in) :: ncopies
integer, intent(out), optional :: rc
Return Value type(ESMF_Field), allocatable, (:)
Call graph
fieldspread calls spread_scalar
spread_scalar calls fieldcopy, mapl_assert, mapl_return, mapl_verify
fieldcopy calls copy
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
copy calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize