FieldGetLocalSize – MAPL
FieldGetLocalSize Interface
3 statements
Source File
public interface FieldGetLocalSize
Calls
Called by
Contents
Module Procedures
get_local_size
Module Procedures
private function get_local_size(x, rc) result(sz)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
Return Value integer(kind=ESMF_KIND_I8)
Call graph
fieldgetlocalsize calls get_local_size
get_local_size calls fieldgetlocalelementcount, mapl_return, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
get_local_element_count calls mapl_return, mapl_verify, esmf_fieldget, mapl_fieldgetlocalelementcount
mapl_throw_exception calls initialize
assign_fptr_r4_rank1 calls fieldgetlocalsize
assign_fptr_r8_rank1 calls fieldgetlocalsize
copy calls fieldgetlocalsize
test_fieldgetlocalsize calls fieldgetlocalsize
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r8_rank1
fieldcopy calls copy
copy_broadcast calls copy