FieldsAreConformable – MAPL
FieldsAreConformable Interface
4 statements
Source File
public interface FieldsAreConformable
Calls
Called by
Module Procedures
private function are_conformable_scalar(x, y, rc) result(conformable)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Return Value logical
private function are_conformable_array(x, y, rc) result(conformable)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y(:)
integer, intent(out), optional :: rc
Return Value logical
Call graph
fieldsareconformable calls are_conformable_array, are_conformable_scalar
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, fieldgetlocalelementcount, mapl_return, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_throw_exception calls initialize
are_broadcast_conformable calls fieldsareconformable
axpy_r4 calls fieldsareconformable
axpy_r8 calls fieldsareconformable
copy_broadcast calls fieldsareconformable
copy calls fieldsareconformable
fieldabs calls fieldsareconformable
fieldacos calls fieldsareconformable
fieldadd calls fieldsareconformable
fieldasin calls fieldsareconformable
fieldatan calls fieldsareconformable
fieldcos calls fieldsareconformable
fieldcosh calls fieldsareconformable
fielddivide calls fieldsareconformable
fieldexp calls fieldsareconformable
fieldlog calls fieldsareconformable
fieldlog10 calls fieldsareconformable
fieldmultiply calls fieldsareconformable
fieldpow calls fieldsareconformable
fieldpower calls fieldsareconformable
fieldsin calls fieldsareconformable
fieldsinh calls fieldsareconformable
fieldsqrt calls fieldsareconformable
fieldsubtract calls fieldsareconformable
fieldtan calls fieldsareconformable
fieldtanh calls fieldsareconformable
gemv_r4 calls fieldsareconformable
gemv_r8 calls fieldsareconformable
test_fieldsareconformabler4 calls fieldsareconformable
test_fieldsareconformabler8 calls fieldsareconformable