FieldCOPY – MAPL
FieldCOPY Interface
3 statements
Source File
public interface FieldCOPY
Calls
Called by
Contents
Module Procedures
copy
Module Procedures
private subroutine copy(x, y, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Call graph
fieldcopy calls copy
copy calls esmf_fieldget, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, mapl_assert, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8, mapl_return, mapl_verify
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, mapl_return, mapl_verify, fieldgetlocalelementcount
get_cptr calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8
get_error_message calls at
get_local_size calls mapl_return, mapl_verify, fieldgetlocalelementcount
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_prec calls fieldcopy
spread_scalar calls fieldcopy
test_fieldcopy_r4 calls fieldcopy
test_fieldcopy_r4r8 calls fieldcopy
test_fieldcopy_r8 calls fieldcopy
test_fieldcopy_r8r4 calls fieldcopy
fieldconvertprec calls convert_prec
fieldspread calls spread_scalar
test_fieldconvertprec_r4r8 calls fieldconvertprec