FieldSet – MAPL
FieldSet Interface
4 statements
Source File
public interface FieldSet
Calls
Called by
Module Procedures
private subroutine FieldSet_r4(field, constant_val, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
real(kind=ESMF_KIND_r4), intent(in) :: constant_val
integer, intent(out), optional :: rc
private subroutine FieldSet_r8(field, constant_val, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
real(kind=ESMF_KIND_r8), intent(in) :: constant_val
integer, intent(out), optional :: rc
Call graph
fieldset calls fieldset_r4, fieldset_r8
fieldset_r4 calls esmf_fieldget, assign_fptr, mapl_assert, mapl_return, mapl_verify
fieldset_r8 calls esmf_fieldget, assign_fptr, mapl_assert, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
evalf calls fieldset
set_constant_field calls fieldset
mapl_stateeval calls evalf
run_ calls set_constant_field, evaluate_derived_field, calcderivedfield, fillstate
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
initialize_ calls fillstate
run calls mapl_runexpression