FieldCopyBroadcast – MAPL
FieldCopyBroadcast Interface
3 statements
Source File
public interface FieldCopyBroadcast
Calls
Called by
Module Procedures
private subroutine copy_broadcast(x, y, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Call graph
fieldcopybroadcast calls copy_broadcast
copy_broadcast calls esmf_fieldget, fieldgetcptr, fieldsarebroadcastconformable, fieldsareconformable, mapl_assert, copy_bcast_r4_r4, copy_bcast_r4_r8, copy_bcast_r8_r4, copy_bcast_r8_r8, copy, mapl_fieldgetlocalelementcount, mapl_return, mapl_verify
fieldgetcptr calls get_cptr
fieldsarebroadcastconformable calls are_broadcast_conformable
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
copy calls esmf_fieldget, fieldgetcptr, fieldsareconformable, mapl_assert, mapl_return, mapl_verify, fieldgetlocalsize, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evalf calls fieldcopybroadcast
mapl_stateeval calls evalf
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
initialize_ calls fillstate
run_ calls evaluate_derived_field, calcderivedfield, fillstate
run calls mapl_runexpression