FieldGetCptr – MAPL
FieldGetCptr Interface
3 statements
Source File
public interface FieldGetCptr
Calls
Called by
Module Procedures
private subroutine get_cptr(x, cptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(c_ptr), intent(out) :: cptr
integer, intent(out), optional :: rc
Call graph
fieldgetcptr calls get_cptr
get_cptr calls esmf_fieldget, mapl_assert, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_cptr_i4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_i8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_r4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_r8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
assign_fptr_r4_rank1 calls fieldgetcptr
assign_fptr_r4_rank2 calls fieldgetcptr
assign_fptr_r8_rank1 calls fieldgetcptr
assign_fptr_r8_rank2 calls fieldgetcptr
copy calls fieldgetcptr
copy_broadcast calls fieldgetcptr, copy
test_fieldgetcptr calls fieldgetcptr
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldcopy calls copy
fieldcopybroadcast calls copy_broadcast