FieldAXPY – MAPL
FieldAXPY Interface
4 statements
Source File
public interface FieldAXPY
Calls
Called by
Module Procedures
private subroutine axpy_r4(a, x, y, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: a
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
private subroutine axpy_r8(a, x, y, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: a
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Call graph
fieldaxpy calls axpy_r4, axpy_r8
axpy_r4 calls assign_fptr, fieldsareconformable, mapl_assert, verify_typekind, mapl_return, mapl_verify
axpy_r8 calls assign_fptr, fieldsareconformable, mapl_assert, verify_typekind, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
verify_typekind calls verify_typekind_array, verify_typekind_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls mapl_return, mapl_verify, esmf_fieldget, fieldgetlocalelementcount
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
verify_typekind_array calls verify_typekind, mapl_return, mapl_verify
verify_typekind_scalar calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget
test_fieldaxpy_r4 calls fieldaxpy
test_fieldaxpy_r8 calls fieldaxpy