find_if – MAPL
find_if Interface
3 statements
Source File
public interface find_if
Calls
Contents
Module Procedures
vector_find_if
Module Procedures
private function vector_find_if(first, last, p) result(it)
Arguments
Type Intent Optional Attributes Name
type(entryPointVectorIterator), intent(in) :: first
type(entryPointVectorIterator), intent(in) :: last
private function p(item)
Arguments
Type Intent Optional Attributes Name
type(runEntryPoint), intent(in) :: item
Return Value logical
Return Value type(entryPointVectorIterator)
Call graph
find_if calls vector_find_if
vector_find_if calls next, of
next calls vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind
vector_riter_next_1 calls next
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add