find_if_not – MAPL
find_if_not Interface
3 statements
Source File
public interface find_if_not
Calls
Module Procedures
private function vector_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(MeterNodeStackIterator), intent(in) :: first
type(MeterNodeStackIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(MeterNodePtr), intent(in) :: item
Return Value logical
Return Value type(MeterNodeStackIterator)
Call graph
find_if_not calls vector_find_if_not
vector_find_if_not calls of, vector_iter_next