find_if_not – MAPL
find_if_not Interface
3 statements
Source File
private interface find_if_not
Calls
Module Procedures
private function vector_reverse_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: first
type(VectorRIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(runEntryPoint), intent(in) :: item
Return Value logical
Return Value type(VectorRIterator)
Call graph
find_if_not calls vector_reverse_find_if_not
vector_reverse_find_if_not calls of, vector_riter_next
vector_riter_next calls vector_iter_prev
vector_riter_of_offset_default calls of