find_if_not – MAPL
find_if_not Interface
3 statements
Source File
private interface find_if_not
Calls
Contents
Module Procedures
vector_reverse_find_if_not
Module Procedures
private function vector_reverse_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: first
type(VectorRIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(MeterNodePtr), intent(in) :: item
Return Value logical
Return Value type(VectorRIterator)
Call graph
find_if_not calls vector_reverse_find_if_not
vector_reverse_find_if_not calls next, of
next calls vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind
vector_riter_next_1 calls next
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add