FormattedTextColumn – MAPL
FormattedTextColumn Interface
4 statements
Source File
public interface FormattedTextColumn
Calls
Module Procedures
private function new_FormattedTextColumn_scalar_header(header, format, width, data_column, separator) result(column)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: header
character(len=*), intent(in) :: format
integer, intent(in) :: width
class(AbstractColumn), intent(in) :: data_column
character(len=1), optional :: separator
Return Value type(FormattedTextColumn)
private function new_FormattedTextColumn_array_header(header, format, width, data_column, separator) result(column)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: header(:)
character(len=*), intent(in) :: format
integer, intent(in) :: width
class(AbstractColumn), intent(in) :: data_column
character(len=1), optional :: separator
Return Value type(FormattedTextColumn)
Call graph
formattedtextcolumn calls new_formattedtextcolumn_array_header, new_formattedtextcolumn_scalar_header
new_formattedtextcolumn_array_header calls set_separator, set_width