ftn_end – MAPL
ftn_end Interface
3 statements
Source File
public interface ftn_end
Calls
Module Procedures
private function map_s_iter_ftn_end(cont) result(end)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in), target :: cont
Return Value type(map_SetIterator)
Call graph
ftn_end calls map_s_iter_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end
map_s_ftn_end calls next, map_s_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_begin calls map_s_iter_next