get_ESMF_Time_from_NetCDF_DateTime – MAPL
get_ESMF_Time_from_NetCDF_DateTime Interface
4 statements
Source File
public interface get_ESMF_Time_from_NetCDF_DateTime
Calls
Called by
Module Procedures
private subroutine get_ESMF_Time_from_NetCDF_DateTime_integer(duration, units_string, interval, basetime, unusable, time, time_unit, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: duration
character(len=*), intent(in) :: units_string
type(ESMF_TimeInterval), intent(inout) :: interval
type(ESMF_Time), intent(inout) :: basetime
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Time), intent(inout), optional :: time
character(len=:), intent(out), optional, allocatable :: time_unit
integer, intent(out), optional :: rc
private subroutine get_ESMF_Time_from_NetCDF_DateTime_real(duration, units_string, interval, basetime, unusable, time, time_unit, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: duration
character(len=*), intent(in) :: units_string
type(ESMF_TimeInterval), intent(inout) :: interval
type(ESMF_Time), intent(inout) :: basetime
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Time), intent(inout), optional :: time
character(len=:), intent(out), optional, allocatable :: time_unit
integer, intent(out), optional :: rc
Call graph
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime_integer calls convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, mapl_assert, set_esmf_timeinterval, mapl_return, mapl_verify, set_esmf_time_from_iso8601
get_esmf_time_from_netcdf_datetime_real calls convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, mapl_assert, set_esmf_timeinterval, mapl_return, mapl_verify, set_esmf_time_from_iso8601
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
extract_cf_time_unit calls extract_cf_time_unit_cf_time, extract_cf_time_unit_units
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time, extract_iso8601_from_cf_time_units
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
set_esmf_timeinterval calls set_esmf_timeinterval_from_datetime_duration
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_esmf_time_from_iso8601 calls mapl_return, mapl_verify, ESMF_TimeSet
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime