get_v2d_netcdf – MAPL
get_v2d_netcdf Interface
4 statements
Source File
public interface get_v2d_netcdf
Calls
Module Procedures
public subroutine get_v2d_netcdf_R4(filename, name, array, Xdim, Ydim, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: name
real, intent(out), dimension(Xdim,Ydim) :: array
integer, intent(in) :: Xdim
integer, intent(in) :: Ydim
integer, intent(out), optional :: rc
public subroutine get_v2d_netcdf_R8(filename, name, array, Xdim, Ydim, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: name
real(kind=REAL64), intent(out), dimension(Xdim,Ydim) :: array
integer, intent(in) :: Xdim
integer, intent(in) :: Ydim
integer, intent(out), optional :: rc
Call graph
get_v2d_netcdf calls get_v2d_netcdf_r4, get_v2d_netcdf_r8
get_v2d_netcdf_r4 calls nf90_close, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_open, check_nc_status, mapl_return, mapl_verify
get_v2d_netcdf_r8 calls nf90_close, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_open, check_nc_status, mapl_return, mapl_verify
check_nc_status calls mapl_return, mapl_assert, nf90_strerror
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize