get_eta – MAPL
get_eta Interface
4 statements
Source File
public interface get_eta
Calls
Called by
Contents
Module Procedures
get_eta_onestep_r4 get_eta_onestep_r8
Module Procedures
private subroutine get_eta_onestep_r4(filename, ptop, pint, ak, bk, unusable, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=REAL32), intent(out) :: ptop
real(kind=REAL32), intent(out) :: pint
real(kind=REAL32), intent(out) :: ak(:)
real(kind=REAL32), intent(out) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
private subroutine get_eta_onestep_r8(filename, ptop, pint, ak, bk, unusable, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=REAL64), intent(out) :: ptop
real(kind=REAL64), intent(out) :: pint
real(kind=REAL64), intent(out) :: ak(:)
real(kind=REAL64), intent(out) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Call graph
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8
get_eta_onestep_r4 calls get_eta, etahybridverticalcoordinate, mapl_verify
get_eta_onestep_r8 calls get_eta, etahybridverticalcoordinate, mapl_verify
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_cfg, new_etahybridverticalcoordinate_by_file
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
new_etahybridverticalcoordinate_by_ak_bk calls mapl_assert
new_etahybridverticalcoordinate_by_cfg calls etahybridverticalcoordinate, mapl_verify, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine
new_etahybridverticalcoordinate_by_file calls etahybridverticalcoordinate, mapl_verify, ESMF_ConfigLoadFile
get_eta_r4 calls get_eta