GetDate – MAPL
GetDate Interface
4 statements
Source File
public interface GetDate
Calls
Called by
Contents
Module Procedures
GetDateInt8 GetDateInt4
Module Procedures
public subroutine GetDateInt8(yyyymmdd_1, hhmmss_1, offset, yyyymmdd_2, hhmmss_2, rc)
Arguments
Type Intent Optional Attributes Name
integer :: yyyymmdd_1
integer :: hhmmss_1
integer(kind=INT64) :: offset
integer :: yyyymmdd_2
integer :: hhmmss_2
integer :: rc
public subroutine GetDateInt4(yyyymmdd_1, hhmmss_1, offset, yyyymmdd_2, hhmmss_2, rc)
Arguments
Type Intent Optional Attributes Name
integer :: yyyymmdd_1
integer :: hhmmss_1
integer :: offset
integer :: yyyymmdd_2
integer :: hhmmss_2
integer :: rc
Call graph
getdate calls getdateint8, getdateint4
getdateint8 calls cfio_parseinttime, caldat, julday
getdateint4 calls getdateint8
getbegdatetime calls getdate
esmf_cfiovarreadt3d__ calls getdate
getdatetimevec calls getdate
gettindex calls getdate, getdatetimevec
esmf_cfiovarreadt2d__ calls getdate
gettimesonfile calls getdate, getdatetimevec
esmf_cfiosdfvarreadt2d__ calls getdate, getbegdatetime
esmf_cfiosdfvarreadt3d__ calls getdate, getbegdatetime
esmf_cfiosdffileopen calls getbegdatetime
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
cfio_sgetvar calls getdatetimevec
esmf_cfiovarreadt2 calls esmf_cfiovarreadt3d__, esmf_cfiovarreadt2d__
cfio_getvar calls getdatetimevec
mapl_cfioreadparallel_ calls gettindex
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d__, esmf_cfiosdfvarreadt2d_, esmf_cfiosdfvarreadt3d_
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__
esmf_cfiofileopen calls esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls esmf_cfiosdffileopen, cfio_sgetvar, cfio_getvar
esmf_cfiosdfvarread3d_ calls esmf_cfiosdffileopen, cfio_getvar
esmf_cfiovarreadt calls esmf_cfiovarreadt3d_, esmf_cfiovarreadt2d_
esmf_cfiosdfvarread1d_ calls esmf_cfiosdffileopen, cfio_sgetvar
mapl_cfioreadparallel calls mapl_cfioreadparallel_