getNodeComm – MAPL
getNodeComm Interface
306 statements
Source File
interface
Calls
Called by
private module function getNodeComm(Comm, rc) result(NodeComm) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Comm
integer, intent(out), optional :: rc
Return Value integer
Call graph
getnodecomm calls getnodecomm, mapl_return, mapl_assert, mpi_comm_size, mpi_get_processor_name, mpi_allgather, mpi_comm_rank, mpi_comm_split, mapl_sort, mapl_verify, mapl_noderanklist, mpi_allreduce
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_sort calls sort1ls, sort2ss, sort2ld, sort2lr, sort2ls, sort1sr, sort2sr, sort2al, sort2as, sort2sd, sort1ss, sort1lr, sort1ld, sort1sd
mapl_verify calls mapl_throw_exception
mapl_getnodeinfo calls getnodecomm, mapl_getnodeinfo
mapl_corespernodeget calls mapl_getnodeinfo, mapl_corespernodeget
mapl_shmemamonfirstnode calls mapl_getnodeinfo, mapl_shmemamonfirstnode
main calls mapl_getnodeinfo
initialize_gc calls mapl_getnodeinfo
ut_regridding calls mapl_getnodeinfo
regrid_util calls main