getNodeRootsComm – MAPL
getNodeRootsComm Interface
306 statements
Source File
interface
Calls
Called by
private module function getNodeRootsComm(Comm, rc) result(NodeRootsComm) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Comm
integer, intent(out), optional :: rc
Return Value integer
Call graph
getnoderootscomm calls getnoderootscomm, get_logger, info, mapl_assert, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_getnodeinfo calls getnoderootscomm, mapl_getnodeinfo
initialize_gc calls mapl_getnodeinfo
main calls mapl_getnodeinfo
mapl_corespernodeget calls mapl_getnodeinfo, mapl_corespernodeget
mapl_shmemamonfirstnode calls mapl_getnodeinfo, mapl_shmemamonfirstnode
ut_regridding calls mapl_getnodeinfo
regrid_util calls main