GridCase – MAPL
GridCase Interface
4 statements
Source File
public interface GridCase
Calls
Called by
Contents
Module Procedures
GridCase_global GridCase_local
Module Procedures
public function GridCase_global(nx, ny, im_world, jm_world, dateline, pole, default_decomposition, ims, jms, lons, lats) result(param)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: im_world
integer, intent(in) :: jm_world
character(len=2), intent(in) :: dateline
character(len=2), intent(in) :: pole
logical, intent(in) :: default_decomposition
integer, intent(in) :: ims(:)
integer, intent(in) :: jms(:)
real, intent(in) :: lons(:)
real, intent(in) :: lats(:)
Return Value type(GridCase)
public function GridCase_local(nx, ny, im_world, jm_world, lon_range, lat_range, default_decomposition, ims, jms, lons, lats) result(param)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: im_world
integer, intent(in) :: jm_world
type(RealMinMax), intent(in) :: lon_range
type(RealMinMax), intent(in) :: lat_range
logical, intent(in) :: default_decomposition
integer, intent(in) :: ims(:)
integer, intent(in) :: jms(:)
real, intent(in) :: lons(:)
real, intent(in) :: lats(:)
Return Value type(GridCase)
Call graph
gridcase calls gridcase_global, gridcase_local
gridcase_global calls setnumpetsrequested
gridcase_local calls setnumpetsrequested
getparameters calls gridcase