GridType – MAPL
GridType Interface
4 statements
Source File
public interface GridType
Calls
Contents
Module Procedures
newGridType_name newGridType_mapl
Module Procedures
private function newGridType_name(name) result(grid_type)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Return Value type(GridType)
private function newGridType_mapl(grid) result(grid_type)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
Return Value type(GridType)
Call graph
gridtype calls newgridtype_name, newgridtype_mapl
newgridtype_mapl calls esmf_attributeget