HistoryTrajectory – MAPL
HistoryTrajectory Interface
3 statements
Source File
public interface HistoryTrajectory
Calls
Contents
Module Procedures
HistoryTrajectory_from_config
Module Procedures
private interface HistoryTrajectory_from_config()
Arguments
None
Call graph
historytrajectory calls historytrajectory_from_config
historytrajectory_from_config calls historytrajectory_from_config, ESMF_AlarmCreate, ESMF_ClockGet, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigGetDim, ESMF_ConfigNextLine, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, debug, get_logger, hms_2_s, mapl_am_i_root, mapl_assert, obs, convert_twostring_2_esmfinterval, mapl_return, mapl_verify
hms_2_s calls hms_2_s
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_twostring_2_esmfinterval calls ESMF_TimeIntervalSet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception