init_IO_ClientManager – MAPL
init_IO_ClientManager Interface
3 statements
Source File
public interface init_IO_ClientManager
Calls
Called by
Module Procedures
private subroutine init_ClientManager(client_comm, unusable, n_i, n_o, fast_oclient, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: client_comm
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: n_i
integer, intent(in), optional :: n_o
logical, intent(in), optional :: fast_oclient
integer, intent(out), optional :: rc
Call graph
init_io_clientmanager calls init_clientmanager
init_clientmanager calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize calls init_io_clientmanager
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run