INTERP_LIN_1111_2 – MAPL
INTERP_LIN_1111_2 Interface
62 statements
Source File
interface
Calls
Called by
private module subroutine INTERP_LIN_1111_2(OY, OX, IY, IX) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out) :: OY(:)
real(kind=REAL64), intent(in) :: OX(:)
real(kind=REAL64), intent(in) :: IY(:)
real(kind=REAL64), intent(in) :: IX(:)
Call graph
interp_lin_1111_2 calls interp_lin_1111_2, interp_lin_0011_2
interp_lin_0011_2 calls interp_lin_0011_2
mapl_interp calls interp_lin_1111_2, interp_lin_2111_2, interp_lin_2121_2, interp_lin_3321_2
interp_lin_2111_2 calls interp_lin_1111_2, interp_lin_2111_2
interp_lin_2121_2 calls interp_lin_1111_2, interp_lin_2121_2
interp_lin_3321_2 calls interp_lin_1111_2, interp_lin_3321_2