ISO8601DateTime – MAPL
ISO8601DateTime Interface
3 statements
Source File
public interface ISO8601DateTime
Calls
Called by
Contents
Module Procedures
construct_ISO8601DateTime
Module Procedures
public function construct_ISO8601DateTime(isostring, rc) result(datetime)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(inout), optional :: rc
Return Value type(ISO8601DateTime)
Call graph
iso8601datetime calls construct_iso8601datetime
construct_iso8601datetime calls iso8601date, iso8601time, mapl_assert, mapl_return, mapl_verify
iso8601date calls construct_iso8601date
iso8601time calls construct_iso8601time
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
construct_iso8601date calls mapl_assert, parse_date
construct_iso8601time calls mapl_assert, mapl_return, parse_time
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_iso8601_to_esmf_time calls iso8601datetime