ISO8601Duration – MAPL
ISO8601Duration Interface
3 statements
Source File
public interface ISO8601Duration
Calls
Called by
Contents
Module Procedures
construct_ISO8601Duration
Module Procedures
public function construct_ISO8601Duration(isostring, imin, imax, rc) result(duration)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(in) :: imin
integer, intent(in) :: imax
integer, intent(out), optional :: rc
Return Value type(ISO8601Duration)
Call graph
iso8601duration calls construct_iso8601duration
construct_iso8601duration calls mapl_assert, is_digit, mapl_return, read_whole_number_indexed
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
get_error_message calls at
get_integer_digit_from_string calls get_integer_digit
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_iso8601_to_esmf_timeinterval calls iso8601duration