LatLonGridFactory – MAPL
LatLonGridFactory Interface
3 statements
Source File
public interface LatLonGridFactory
Calls
Module Procedures
private function LatLonGridFactory_from_parameters(unusable, grid_name, im_world, jm_world, lm, nx, ny, ims, jms, pole, dateline, lon_range, lat_range, force_decomposition, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(in), optional :: ims(:)
integer, intent(in), optional :: jms(:)
character(len=2), intent(in), optional :: pole
character(len=2), intent(in), optional :: dateline
type(RealMinMax), intent(in), optional :: lon_range
type(RealMinMax), intent(in), optional :: lat_range
logical, intent(in), optional :: force_decomposition
integer, intent(out), optional :: rc
Return Value type(LatLonGridFactory)
Call graph
latlongridfactory calls latlongridfactory_from_parameters
latlongridfactory_from_parameters calls set_with_default, check_and_fill_consistency, compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners, mapl_return, mapl_verify
set_with_default calls set_with_default_character, set_with_default_integer, set_with_default_logical, set_with_default_range, set_with_default_real
check_and_fill_consistency calls mapl_return, mapl_verify, mapl_assert, check_decomposition, generate_newnxy
compute_lat_centers calls mapl_return, mapl_assert, mapl_range
compute_lat_corners calls mapl_return, mapl_assert, mapl_range
compute_lon_centers calls mapl_return, mapl_verify, mapl_range
compute_lon_corners calls mapl_return, mapl_verify, mapl_range
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
check_decomposition calls mapl_return
generate_newnxy calls mapl_return, mapl_decomposedim, generate_new_decomp
get_error_message calls at, insert
mapl_throw_exception calls initialize