LatLonToLatLonRegridder – MAPL
LatLonToLatLonRegridder Interface
3 statements
Source File
public interface LatLonToLatLonRegridder
Calls
Module Procedures
private function newLatLonToLatLonRegridder(grid_in, grid_out, regrid_method, unusable, rc) result(regridder)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid_in
type(ESMF_Grid), intent(in) :: grid_out
integer :: regrid_method
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(LatLonToLatLonRegridder)
Call graph
latlontolatlonregridder calls newlatlontolatlonregridder
newlatlontolatlonregridder calls initialize, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
initialize_base calls mapl_return, initialize, mapl_verify
initialize_subclass calls mapl_return, mapl_allocnodearray, mapl_deallocnodearray, mapl_syncsharedmemory, copy_global_to_local, find_tile_file, get_spec, mapl_verify, read_geos_binary, read_tempest
mapl_throw_exception calls initialize