linspace – MAPL
linspace Interface
4 statements
Source File
private interface linspace
Calls
Called by
Module Procedures
private subroutine linspace1(d1, d2, n, y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: d1
real(kind=dp), intent(in) :: d2
real(kind=dp), intent(in) :: n
real(kind=dp), intent(inout), DIMENSION(:) :: y
private subroutine linspace2(d1, d2, n, y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: d1
real(kind=dp), intent(in) :: d2
integer, intent(in) :: n
real(kind=dp), intent(inout), DIMENSION(:) :: y
Call graph
linspace calls linspace1, linspace2
find_sweeppoints calls linspace
orbits_swath calls find_sweeppoints
domasking_ calls orbits_swath
domasking_cs calls orbits_swath
run_ calls domasking_, domasking_cs