LocalMemReference – MAPL
LocalMemReference Interface
9 statements
Source File
public interface LocalMemReference
Calls
Called by
Contents
Module Procedures
new_LocalMemReference new_LocalMemReference_0d new_LocalMemReference_1d new_LocalMemReference_2d new_LocalMemReference_3d new_LocalMemReference_4d new_LocalMemReference_5d
Module Procedures
private function new_LocalMemReference(type_kind, shp, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer, intent(in) :: shp(:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
private function new_LocalMemReference_0d(scalar, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: scalar
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
private function new_LocalMemReference_1d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
private function new_LocalMemReference_2d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
private function new_LocalMemReference_3d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:,:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
private function new_LocalMemReference_4d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
private function new_LocalMemReference_5d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:,:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
Call graph
localmemreference calls new_localmemreference, new_localmemreference_0d, new_localmemreference_1d, new_localmemreference_2d, new_localmemreference_3d, new_localmemreference_4d, new_localmemreference_5d
new_localmemreference calls mapl_return, mapl_verify
new_localmemreference_0d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_1d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_2d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_3d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_4d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_5d calls localmemreference, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize