LocStreamFactory – MAPL
LocStreamFactory Interface
3 statements
Source File
public interface LocStreamFactory
Calls
Contents
Module Procedures
LocStreamFactory_from_arrays
Module Procedures
private function LocStreamFactory_from_arrays(lons, lats, unusable, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: lons(:)
real(kind=REAL64), intent(in) :: lats(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(LocStreamFactory)
Call graph
locstreamfactory calls locstreamfactory_from_arrays
locstreamfactory_from_arrays calls mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize