LocstreamRegridder – MAPL
LocstreamRegridder Interface
3 statements
Source File
public interface LocstreamRegridder
Calls
Contents
Module Procedures
new_LocstreamRegridder
Module Procedures
private function new_LocstreamRegridder(grid, locstream, unusable, regrid_method, rc) result(regridder)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
type(ESMF_LocStream), intent(inout) :: locstream
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_RegridMethod_Flag), intent(in), optional :: regrid_method
integer, intent(out), optional :: rc
Return Value type(LocstreamRegridder)
Call graph
locstreamregridder calls new_locstreamregridder
new_locstreamregridder calls ESMF_FieldRegridStore, esmf_fieldcreate, esmf_fielddestroy, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize