make_substates – MAPL
make_substates Interface
3 statements
Source File
public interface make_substates
Calls
Called by
Contents
Module Procedures
make_substates_from_num_grids
Module Procedures
private recursive function make_substates_from_num_grids(state, num_subgrids, unusable, rc) result(substates)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
integer, intent(in) :: num_subgrids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_State), allocatable, (:)
Call graph
make_substates calls make_substates_from_num_grids
make_substates_from_num_grids calls make_substates, mapl_return, esmf_stateget, esmf_fieldget, mapl_verify, esmf_statecreate, esmf_attributecopy, make_subfields, esmf_stateadd, make_subfieldbundles, copy_callbacks
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_subfields calls make_subfields_from_num_grids
make_subfieldbundles calls make_subfieldbundles_ordinary
copy_callbacks calls mapl_return, mapl_verify, get_callbacks, mapl_assert, esmf_methodadd
get_callbacks calls mapl_return, mapl_verify, esmf_attributeget, esmf_attributeset
make_subfields_from_num_grids calls mapl_return, esmf_fieldget, mapl_verify, esmf_attributecopy, find_bounds, make_subgrids, mapl_gridget, esmf_fieldcreate
make_subfieldbundles_ordinary calls mapl_return, mapl_verify, esmf_attributecopy, make_subfields, esmf_fieldbundleget, esmf_fieldbundlecreate, esmf_fieldbundleadd
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
create_subobjects calls make_substates