make_subfields – MAPL
make_subfields Interface
3 statements
Source File
public interface make_subfields
Calls
Called by
Contents
Module Procedures
make_subfields_from_num_grids
Module Procedures
private function make_subfields_from_num_grids(primary_field, num_subgrids, unusable, rc) result(subfields)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: primary_field
integer, intent(in) :: num_subgrids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Field), allocatable, (:)
Call graph
make_subfields calls make_subfields_from_num_grids
make_subfields_from_num_grids calls ESMF_AttributeCopy, esmf_fieldcreate, esmf_fieldget, make_subgrids, find_bounds, mapl_gridget, mapl_return, mapl_verify
make_subgrids calls make_subgrids_from_bounds, make_subgrids_from_num_grids
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
make_subgrids_from_bounds calls ESMF_AttributeCopy, mapl_gridget, mapl_return, mapl_verify, ESMF_GridGet, ESMF_AttributeRemove, ESMF_AttributeSet, ESMF_GridAddCoord, ESMF_GridCreateNoPeriDim, ESMF_GridGetCoord, ESMF_VMGet, ESMF_VMGetCurrent, mapl_gridgetcorners, subset_array
make_subgrids_from_num_grids calls make_subgrids, find_bounds, mapl_gridget, mapl_return, mapl_verify
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
make_subfieldbundles_ordinary calls make_subfields
make_substates_from_num_grids calls make_subfields, make_subfieldbundles, make_substates
make_subfieldbundles calls make_subfieldbundles_ordinary
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates
activate_threading calls create_subobjects