make_subgrids – MAPL
make_subgrids Interface
4 statements
Source File
public interface make_subgrids
Calls
Called by
Contents
Module Procedures
make_subgrids_from_num_grids make_subgrids_from_bounds
Module Procedures
private function make_subgrids_from_num_grids(primary_grid, num_grids, unusable, rc) result(subgrids)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: primary_grid
integer, intent(in) :: num_grids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid), allocatable, (:)
private function make_subgrids_from_bounds(primary_grid, bounds, unusable, rc) result(subgrids)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: primary_grid
type(Interval), intent(in) :: bounds(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid), allocatable, (:)
Call graph
make_subgrids calls make_subgrids_from_num_grids, make_subgrids_from_bounds
make_subgrids_from_num_grids calls make_subgrids, mapl_gridget, mapl_verify, find_bounds, mapl_return
make_subgrids_from_bounds calls esmf_gridgetcoord, esmf_attributecopy, mapl_gridget, mapl_verify, esmf_attributeset, mapl_return, esmf_gridget, esmf_vmgetcurrent, esmf_vmget, esmf_gridcreatenoperidim, esmf_gridaddcoord, mapl_gridgetcorners, esmf_attributeremove, subset_array
mapl_gridget calls mapl_verify, mapl_return, esmf_gridget, esmf_attributeget, mapl_gridhasde
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_gridgetcorners calls mapl_gridgetcorners, esmf_gridgetcoord, mapl_gridget, mapl_verify, esmf_attributeset, mapl_return, esmf_gridget, esmf_attributeget, mapl_assert, esmf_fieldhalostore, esmf_fielddestroy, esmf_fieldcreate, esmf_fieldhalo, esmf_fieldhalorelease
mapl_throw_exception calls initialize
mapl_gridhasde calls mapl_verify, mapl_return, esmf_gridget, esmf_distgridget, esmf_delayoutget
create_subobjects calls make_subgrids
make_subfields_from_num_grids calls make_subgrids
make_subfields calls make_subfields_from_num_grids
make_substates_from_num_grids calls make_subfields
make_subfieldbundles_ordinary calls make_subfields
make_substates calls make_substates_from_num_grids
make_subfieldbundles calls make_subfieldbundles_ordinary