make_subfieldBundles – MAPL
make_subfieldBundles Interface
3 statements
Source File
public interface make_subfieldBundles
Calls
Called by
Contents
Module Procedures
make_subfieldBundles_ordinary
Module Procedures
private function make_subFieldBundles_ordinary(bundle, num_grids, unusable, rc) result(sub_bundles)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
integer, intent(in) :: num_grids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle), allocatable, (:)
Call graph
make_subfieldbundles calls make_subfieldbundles_ordinary
make_subfieldbundles_ordinary calls ESMF_AttributeCopy, esmf_fieldbundleadd, esmf_fieldbundlecreate, esmf_fieldbundleget, make_subfields, mapl_return, mapl_verify
make_subfields calls make_subfields_from_num_grids
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
make_subfields_from_num_grids calls ESMF_AttributeCopy, mapl_return, mapl_verify, esmf_fieldcreate, esmf_fieldget, make_subgrids, find_bounds, mapl_gridget
mapl_throw_exception calls initialize
make_substates_from_num_grids calls make_subfieldbundles, make_substates
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates
activate_threading calls create_subobjects