map_Set – MAPL
map_Set Interface
5 statements
Source File
private interface map_Set
Calls
Called by
Contents
Module Procedures
map_s_new_set_empty map_s_new_set_copy map_s_new_set_initializer_list
Module Procedures
private function map_s_new_set_empty() result(s)
Arguments
None
Return Value type(map_Set)
private function map_s_new_set_copy(x) result(s)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in) :: x
Return Value type(map_Set)
private function map_s_new_set_initializer_list(il) result(s)
Arguments
Type Intent Optional Attributes Name
type(CallbackPair), intent(in), dimension(:) :: il
Return Value type(map_Set)
Call graph
map_set calls map_s_new_set_copy, map_s_new_set_empty, map_s_new_set_initializer_list
map_s_new_set_initializer_list calls insert
map_new_map_empty calls map_set
callbackmap calls map_new_map_empty, map_new_map_initializer_list
map_new_map_initializer_list calls callbackmap