MAPL_LocStreamTransform – MAPL
MAPL_LocStreamTransform Interface
8 statements
Source File
public interface MAPL_LocStreamTransform
Calls
Called by
Contents
Module Procedures
MAPL_LocStreamTransformField MAPL_LocStreamTransformT2G MAPL_LocStreamTransformG2T MAPL_LocStreamTransformT2T MAPL_LocStreamTransformT2TR4R8 MAPL_LocStreamTransformT2TR8R4
Module Procedures
private subroutine MAPL_LocStreamTransformField(LocStream, OUTPUT, INPUT, MASK, GRID_ID, GLOBAL, ISMINE, INTERP, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
type(ESMF_Field), intent(out) :: OUTPUT
type(ESMF_Field), intent(inout) :: INPUT
integer, intent(in), optional :: MASK(:)
integer, intent(in), optional :: GRID_ID
logical, intent(in), optional :: GLOBAL
logical, intent(in), optional :: ISMINE(:)
logical, intent(in), optional :: INTERP
integer, intent(out), optional :: RC
private subroutine MAPL_LocStreamTransformT2G(LocStream, OUTPUT, INPUT, MASK, SAMPLE, TRANSPOSE, variance, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
real, intent(inout) :: OUTPUT(:,:)
real, intent(inout) :: INPUT(:)
logical, intent(in), optional :: MASK(:)
logical, intent(in), optional :: SAMPLE
logical, intent(in), optional :: TRANSPOSE
logical, intent(in), optional :: variance
integer, intent(out), optional :: RC
private subroutine MAPL_LocStreamTransformG2T(LocStream, OUTPUT, INPUT, MASK, GRID_ID, GLOBAL, ISMINE, INTERP, TRANSPOSE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
real, intent(inout) :: OUTPUT(:)
real, intent(inout) :: INPUT(:,:)
logical, intent(in), optional :: MASK(:)
integer, intent(in), optional :: GRID_ID
logical, intent(in), optional :: GLOBAL
logical, intent(in), optional :: ISMINE(:)
logical, intent(in), optional :: INTERP
logical, intent(in), optional :: TRANSPOSE
integer, intent(out), optional :: RC
private subroutine MAPL_LocStreamTransformT2T(OUTPUT, XFORM, INPUT, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: OUTPUT(:)
type(MAPL_LocStreamXform), intent(in) :: XFORM
real, intent(in) :: INPUT(:)
integer, intent(out), optional :: RC
private subroutine MAPL_LocStreamTransformT2TR4R8(OUTPUT, XFORM, INPUT, RC)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(out) :: OUTPUT(:)
type(MAPL_LocStreamXform), intent(in) :: XFORM
real, intent(in) :: INPUT(:)
integer, intent(out), optional :: RC
private subroutine MAPL_LocStreamTransformT2TR8R4(OUTPUT, XFORM, INPUT, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: OUTPUT(:)
type(MAPL_LocStreamXform), intent(in) :: XFORM
real(kind=ESMF_KIND_R8), intent(in) :: INPUT(:)
integer, intent(out), optional :: RC
Call graph
mapl_locstreamtransform calls mapl_locstreamtransformfield, mapl_locstreamtransformg2t, mapl_locstreamtransformt2g, mapl_locstreamtransformt2tr4r8, mapl_locstreamtransformt2t, mapl_locstreamtransformt2tr8r4
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t, mapl_locstreamtransformt2g, mapl_verify, mapl_assert, esmf_fieldget, esmf_arrayget, mapl_return
mapl_locstreamtransformg2t calls mapl_verify, mapl_assert, mapl_return, esmfl_halo, mapl_grid_interior
mapl_locstreamtransformt2g calls mapl_verify, mapl_assert, mapl_return, mapl_grid_interior
mapl_locstreamtransformt2tr4r8 calls mapl_locstreamtransformt2t, mapl_verify, mapl_return
mapl_locstreamtransformt2t calls esmfl_fcollect, mapl_verify, mapl_assert, mapl_return, mpi_isend, mpi_wait, mpi_recv
mapl_locstreamtransformt2tr8r4 calls mapl_locstreamtransformt2t, mapl_verify, mapl_return
esmfl_fcollect calls esmfl_fcollect_i4, esmfl_fcollect_r4, esmfl_fcollect_r8
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
esmfl_halo calls esmfl_halo_r4_2d
mapl_grid_interior calls mapl_grid_interior
regridtransform calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
run calls regridtransform, regridtransformt2g2g, regridtransformt2g