MAPL_FargparseCLI – MAPL
MAPL_FargparseCLI Interface
4 statements
Source File
public interface MAPL_FargparseCLI
Calls
Contents
Module Procedures
new_CapOptions_from_fargparse new_CapOptions_from_fargparse_back_comp
Module Procedures
private function new_CapOptions_from_fargparse(unusable, dummy, extra, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: dummy
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
private function new_CapOptions_from_fargparse_back_comp(unusable, extra, rc) result(fargparsecap)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_FargparseCLI)
Call graph
mapl_fargparsecli calls new_capoptions_from_fargparse, new_capoptions_from_fargparse_back_comp
new_capoptions_from_fargparse calls argparser, add_command_line_options, fill_cap_options, mapl_return, mapl_verify
new_capoptions_from_fargparse_back_comp calls argparser, add_command_line_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, add_argument, push_back
fill_cap_options calls mapl_return, mapl_verify, cast, mapl_assert, of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize