MAPL_FieldCopyAttributes – MAPL
MAPL_FieldCopyAttributes Interface
364 statements
Source File
interface
Calls
Called by
public module subroutine MAPL_FieldCopyAttributes(FIELD_IN, FIELD_OUT, RC) Implementation →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD_IN
type(ESMF_Field), intent(inout) :: FIELD_OUT
integer, intent(out), optional :: RC
Call graph
mapl_fieldcopyattributes calls mapl_fieldcopyattributes, ESMF_AttributeCopy, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_flipped_field calls mapl_fieldcopyattributes
mapl_fieldcreatenewgrid calls mapl_fieldcopyattributes, mapl_fieldcreatenewgrid
mapl_fieldcreater4 calls mapl_fieldcopyattributes, mapl_fieldcreater4
mapl_fieldcreaterename calls mapl_fieldcopyattributes, mapl_fieldcreaterename
mapl_fieldsplit calls mapl_fieldcopyattributes, mapl_fieldsplit
mapl_statevarwritencpar calls create_flipped_field, mapl_fieldcreate
mapl_fieldcreate calls mapl_fieldcreatenewgrid, mapl_fieldcreater4, mapl_fieldcreaterename
mapl_varwritencpar calls mapl_statevarwritencpar
initialize calls mapl_fieldsplit, mapl_fieldcreate
putfieldinbundle__ calls mapl_fieldsplit
addvariable_to_acc_bundle calls mapl_fieldcreate
addvariable_to_output_bundle calls mapl_fieldcreate
create_bracketing_fields calls mapl_fieldcreate
createfilelevbracket calls mapl_fieldcreate
createvariable calls mapl_fieldcreate
esmfl_bundlecpyfield calls mapl_fieldcreate
esmfl_stategetfield calls mapl_fieldcreate
initialize_ calls mapl_fieldcreate
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_gridcompgetfriendlies0 calls mapl_fieldcreate, putfieldinbundle__
mapl_statecreatefromspecnew calls mapl_fieldcreate
mapl_statevarreadncpar calls mapl_fieldcreate
run calls mapl_fieldcreate