MAPL_LocStreamCreate – MAPL
MAPL_LocStreamCreate Interface
4 statements
Source File
public interface MAPL_LocStreamCreate
Calls
Called by
Contents
Module Procedures
MAPL_LocStreamCreateFromFile MAPL_LocStreamCreateFromStream
Module Procedures
private subroutine MAPL_LocStreamCreateFromFile(LocStream, LAYOUT, FILENAME, NAME, MASK, GRID, NewGridNames, use_pfaf, RC)
Creates a location stream from a file. This does not decompose the location stream; so the global stream is described in each processor. The stream can be decomposed later in various ways. Currently we only decompose it by “attaching” it to a decomposed grid.
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(out) :: LocStream
type(ESMF_DELayout), intent(in) :: LAYOUT
character(len=*), intent(in) :: FILENAME
character(len=*), intent(in) :: NAME
integer, intent(in), optional :: MASK(:)
type(ESMF_Grid), intent(inout), optional :: GRID
logical, intent(in), optional :: NewGridNames
logical, intent(in), optional :: use_pfaf
integer, intent(out), optional :: RC
private subroutine MAPL_LocStreamCreateFromStream(LocStreamOut, LocStreamIn, NAME, MASK, RC)
Creates a location stream as a subset of another according to mask.
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(out) :: LocStreamOut
type(MAPL_LocStream), intent(in) :: LocStreamIn
character(len=*), intent(in) :: NAME
integer, intent(in), optional :: MASK(:)
integer, intent(out), optional :: RC
Call graph
mapl_locstreamcreate calls mapl_locstreamcreatefromfile, mapl_locstreamcreatefromstream
mapl_locstreamcreatefromfile calls ESMF_GridGet, ESMF_VMGetCurrent, d, global_geolocation, global_id, mapl_allocateshared, mapl_am_i_root, mapl_assert, mapl_bcastshared, mapl_commsbcast, mapl_deallocnodearray, mapl_grid_interior, mapl_syncsharedmemory, read_parallel, local_geolocation, local_id, local_indexlocation, free_file, getfile, mapl_locstreamattachgrid, mapl_locstreamcreatetilegrid, mapl_return, mapl_verify
mapl_locstreamcreatefromstream calls ESMF_VMAllFullReduce, ESMF_VMGetCurrent, d, mapl_assert, local_geolocation, local_id, local_indexlocation, mapl_locstreamcreatetilegrid, mapl_return, mapl_verify
initialize calls mapl_locstreamcreate