MAPL_TimerAdd – MAPL
MAPL_TimerAdd Interface
3 statements
Source File
public interface MAPL_TimerAdd
Calls
Called by
Module Procedures
private subroutine MAPL_GenericStateClockAdd(GC, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Call graph
mapl_timeradd calls mapl_genericstateclockadd
mapl_genericstateclockadd calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
setservices calls mapl_timeradd