MAPL_DeAllocNodeArray_1DL4 – MAPL
MAPL_DeAllocNodeArray_1DL4 Interface
306 statements
Source File
interface
Calls
Called by
private module subroutine MAPL_DeAllocNodeArray_1DL4(Ptr, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
logical, pointer :: Ptr(:)
integer, intent(out), optional :: rc
Call graph
mapl_deallocnodearray_1dl4 calls mapl_deallocnodearray_1dl4, mapl_return, mapl_verify, releasesharedmemory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
releasesharedmemory calls releasesharedmemory, mapl_return, segs, mapl_assert, shmctl, mpi_barrier, shmdt
mapl_throw_exception calls initialize
mapl_deallocnodearray calls mapl_deallocnodearray_1dl4
mapl_locstreamcreatefromfile calls mapl_deallocnodearray
writerestart calls mapl_deallocnodearray
readrestart calls mapl_deallocnodearray
mapl_statevarread calls mapl_deallocnodearray, mapl_fieldread
add_horz_coordinates_from_file calls mapl_deallocnodearray
initialize_subclass calls mapl_deallocnodearray
mapl_varread_r4_1d calls mapl_deallocnodearray
mapl_fieldread calls mapl_deallocnodearray
mapl_varread_r4_2d calls mapl_deallocnodearray
mapl_statevarwrite calls mapl_deallocnodearray, mapl_fieldwrite
mapl_fieldwrite calls mapl_deallocnodearray
mapl_cfioreadbundle calls mapl_deallocnodearray
mapl_cfiowritebundlepost calls mapl_deallocnodearray
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
mapl_bundleread calls mapl_fieldread
mapl_bundlewrite calls mapl_fieldwrite
mapl_varread calls mapl_statevarread, mapl_varread_r4_1d, mapl_fieldread, mapl_varread_r4_2d
mapl_varwrite calls mapl_statevarwrite, mapl_fieldwrite
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost