MAPL_AddExportSpec – MAPL
MAPL_AddExportSpec Interface
6 statements
Source File
public interface MAPL_AddExportSpec
Calls
Called by
Contents
Module Procedures
MAPL_StateAddExportSpec_ MAPL_StateAddExportSpecFrmChld MAPL_StateAddExportSpecFrmChld_all MAPL_StateAddExportSpecFrmAll
Module Procedures
private subroutine MAPL_StateAddExportSpec_(GC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, DATATYPE, NUM_SUBTILES, REFRESH_INTERVAL, AVERAGING_INTERVAL, HALOWIDTH, PRECISION, DEFAULT, UNGRIDDED_DIMS, UNGRIDDED_UNIT, UNGRIDDED_NAME, UNGRIDDED_COORDS, FIELD_TYPE, STAGGERING, ROTATION, DEPENDS_ON, DEPENDS_ON_CHILDREN, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: LONG_NAME
character(len=*), intent(in), optional :: UNITS
integer, intent(in), optional :: DIMS
integer, intent(in), optional :: VLOCATION
integer, intent(in), optional :: DATATYPE
integer, intent(in), optional :: NUM_SUBTILES
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
integer, intent(in), optional :: HALOWIDTH
integer, intent(in), optional :: PRECISION
real, intent(in), optional :: DEFAULT
integer, intent(in), optional :: UNGRIDDED_DIMS(:)
character(len=*), intent(in), optional :: UNGRIDDED_UNIT
character(len=*), intent(in), optional :: UNGRIDDED_NAME
real, intent(in), optional :: UNGRIDDED_COORDS(:)
integer, intent(in), optional :: FIELD_TYPE
integer, intent(in), optional :: STAGGERING
integer, intent(in), optional :: ROTATION
character(len=*), intent(in), optional :: DEPENDS_ON(:)
logical, intent(in), optional :: DEPENDS_ON_CHILDREN
integer, intent(out), optional :: RC
private subroutine MAPL_StateAddExportSpecFrmChld(GC, SHORT_NAME, CHILD_ID, RC, TO_NAME)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: CHILD_ID
integer, intent(out), optional :: RC
character(len=*), intent(in), optional :: TO_NAME
private subroutine MAPL_StateAddExportSpecFrmChld_All(GC, CHILD_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(in) :: CHILD_ID
integer, intent(out), optional :: RC
private subroutine MAPL_StateAddExportSpecFrmAll(STATE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
integer, intent(out), optional :: RC
Call graph
mapl_addexportspec calls mapl_stateaddexportspec_, mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_stateaddexportspec_ calls ESMF_ConfigGetAttribute, mapl_assert, mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify
mapl_stateaddexportspecfrmall calls ESMF_GridCompGet, get_num_children, mapl_varspecaddreftolist, mapl_varspecget, mapl_varspecset, get_child_gridcomp, mapl_gridcompgetvarspecs, mapl_return, mapl_varspeccreateinlist, mapl_verify
mapl_stateaddexportspecfrmchld calls gcnamelist, mapl_internalstateretrieve, mapl_return, mapl_stateaddexportspecfrmchldname, mapl_verify
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld, mapl_varspecget, get_child_gridcomp, mapl_gridcompgetvarspecs, mapl_internalstateretrieve, mapl_return, mapl_verify
addnewspec calls mapl_addexportspec
setservices calls mapl_addexportspec