MAPL_SunGetSolarConstant – MAPL
MAPL_SunGetSolarConstant Interface
6 statements
Source File
public interface MAPL_SunGetSolarConstant
Calls
Module Procedures
private subroutine MAPL_SunGetSolarConstantByYearDoY(Year, DayOfYear, SC, HK, rc)
Given the year and day-of-year, this function returns the CMIP5 solar constant and the 8 band fractions for the Chou solar code. These are based on annual values from 1610 to 2008 and a repeating cycle after 2008. For dates prior tp 1 January 1610, it returns the value at the start of 1610.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Year
integer, intent(in) :: DayOfYear
real, intent(out) :: SC
real, intent(out), optional :: HK(:)
integer, intent(out), optional :: rc
private subroutine MAPL_SunGetSolarConstantByTime(Time, SC, HK, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: Time
real, intent(out) :: SC
real, intent(out), optional :: HK(:)
integer, intent(out), optional :: rc
private subroutine MAPL_SunGetSolarConstantFromNetcdfFile(CLOCK, fileName, SC, HK, MESOPHOT, JCALC4, rc)
Acquire the solar constant and the eight band fractions for the Chou solar code from an external NetCDF file. The initial configuration assumes monthly values beginning in January, and does not interpolate beyond the range of available data.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in) :: fileName
real, intent(out) :: SC
real, intent(out), optional :: HK(:)
real, intent(out), optional :: MESOPHOT(:)
real, intent(out), optional :: JCALC4(:)
integer, intent(out), optional :: rc
private subroutine MAPL_SunGetSolarConstantFromNRLFile(CLOCK, filename_in, SC, MG, SB, PersistSolar, rc)
Acquire the TSI, Mg, and SB from file.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in) :: filename_in
real, intent(out) :: SC
real, intent(out) :: MG
real, intent(out) :: SB
logical, intent(in), optional :: PersistSolar
integer, intent(out), optional :: rc
Call graph
mapl_sungetsolarconstant calls mapl_sungetsolarconstantbytime, mapl_sungetsolarconstantbyyeardoy, mapl_sungetsolarconstantfromnetcdffile, mapl_sungetsolarconstantfromnrlfile
mapl_sungetsolarconstantbytime calls mapl_sungetsolarconstantbyyeardoy, ESMF_TimeGet, mapl_return, mapl_verify
mapl_sungetsolarconstantbyyeardoy calls mapl_assert, mapl_return
mapl_sungetsolarconstantfromnetcdffile calls ESMF_ClockGet, ESMF_TimeGet, mapl_assert, mapl_climinterpfac, nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, nf90_strerror, mapl_return, mapl_verify
mapl_sungetsolarconstantfromnrlfile calls ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeIntervalGet, ESMF_TimeIntervalSet, ESMF_TimeSet, ESMF_VMGet, ESMF_VMGetCurrent, mapl_assert, mapl_commsbcast, get_logger, debug, mapl_return, mapl_verify