MAPL_CommsSend – MAPL
MAPL_CommsSend Interface
8 statements
Source File
public interface MAPL_CommsSend
Calls
Contents
Module Procedures
MAPL_CommsSend_I4_0 MAPL_CommsSend_I4_1 MAPL_CommsSend_R4_1 MAPL_CommsSend_R4_2 MAPL_CommsSend_R8_1 MAPL_CommsSend_R8_2
Module Procedures
private subroutine MAPL_CommsSend_I4_0(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSend_I4_1(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSend_R4_1(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSend_R4_2(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data(:,:)
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSend_R8_1(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSend_R8_2(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data(:,:)
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
Call graph
mapl_commssend calls mapl_commssend_i4_0, mapl_commssend_i4_1, mapl_commssend_r4_1, mapl_commssend_r4_2, mapl_commssend_r8_1, mapl_commssend_r8_2
mapl_commssend_i4_0 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_send, mapl_return, mapl_verify
mapl_commssend_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_send, mapl_return, mapl_verify
mapl_commssend_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_send, mapl_return, mapl_verify
mapl_commssend_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_send, mapl_return, mapl_verify
mapl_commssend_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_send, mapl_return, mapl_verify
mapl_commssend_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_send, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize