MAPL_GridCompGetFriendlies – MAPL
MAPL_GridCompGetFriendlies Interface
6 statements
Source File
public interface MAPL_GridCompGetFriendlies
Calls
Called by
Contents
Module Procedures
MAPL_GridCompGetFriendlies0 MAPL_GridCompGetFriendlies1 MAPL_GridCompGetFriendlies2 MAPL_GridCompGetFriendlies3
Module Procedures
private recursive subroutine MAPL_GridCompGetFriendlies0(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: TO(:)
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
private subroutine MAPL_GridCompGetFriendlies1(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: TO
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
private subroutine MAPL_GridCompGetFriendlies2(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC(:)
character(len=*), intent(in) :: TO
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
private subroutine MAPL_GridCompGetFriendlies3(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC(:)
character(len=*), intent(in) :: TO(:)
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
Call graph
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies3
mapl_gridcompgetfriendlies0 calls mapl_gridcompgetfriendlies, ESMF_AttributeGet, ESMF_GridCompGet, esmf_fieldbundleget, esmf_fieldget, esmf_stateget, gcnamelist, get_internal_state, mapl_fieldbundleget, mapl_fieldcreate, write_parallel, am_i_friendly_, am_i_friendly__, get_child_gridcomp, mapl_internalstateget, mapl_return, mapl_verify, putfieldinbundle__
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0, mapl_return, mapl_verify
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0, mapl_return, mapl_verify