MAPL_VarSpecAddToList – MAPL
MAPL_VarSpecAddToList Interface
4 statements
Source File
public interface MAPL_VarSpecAddToList
Calls
Contents
Module Procedures
MAPL_VarSpecAddFromItem MAPL_VarSpecAddFromList
Module Procedures
private subroutine MAPL_VarSpecAddFromItem(SPEC, ITEM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecAddFromList(SPEC, ITEM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM(:)
integer, intent(out), optional :: RC
Call graph
mapl_varspecaddtolist calls mapl_varspecaddfromitem, mapl_varspecaddfromlist
mapl_varspecaddfromitem calls mapl_return, mapl_varspeccreateinlist, mapl_verify
mapl_varspecaddfromlist calls mapl_varspecaddfromitem, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspeccreateinlist calls mapl_return, mapl_verify, mapl_assert, mapl_varspecgetindex
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
get_error_message calls at
mapl_throw_exception calls initialize