MAPL_GetNewRank – MAPL
MAPL_GetNewRank Interface
306 statements
Source File
interface
Calls
Called by
public module function MAPL_GetNewRank(node, rc) result(rank) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: node
integer, intent(out), optional :: rc
Return Value integer
Call graph
mapl_getnewrank calls mapl_getnewrank, mapl_noderanklist, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_roundrobinpelist calls mapl_getnewrank
make_regridder calls mapl_roundrobinpelist, make_regridder
mapl_cfiocreatefrombundle calls mapl_roundrobinpelist, make_regridder
mapl_cfioreadbundle calls mapl_roundrobinpelist, make_regridder, mapl_collectivescatter3d
mapl_cfioreadbundleread calls mapl_roundrobinpelist
mapl_cfiosetkrank calls mapl_roundrobinpelist
mapl_collectivegather3d calls mapl_roundrobinpelist
mapl_collectivescatter3d calls mapl_roundrobinpelist
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls mapl_cfioreadbundleread, mapl_cfiocreatefromfile
mapl_cfioreadstate calls mapl_cfioreadbundle
regrid_scalar_3d_real32 calls mapl_collectivegather3d, mapl_collectivescatter3d
mapl_cfioreadparallel calls mapl_cfioreadparallel_
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls mapl_cfioread, esmf_ioread, esmf_iocreate