MAPL_MemUtilsWrite – MAPL
MAPL_MemUtilsWrite Interface
4 statements
Source File
public interface MAPL_MemUtilsWrite
Calls
Called by
Contents
Module Procedures
MAPL_MemUtilsWriteVM MAPL_MemUtilsWriteComm
Module Procedures
private subroutine MAPL_MemUtilsWriteVM(vm, text, always, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
character(len=*), intent(in) :: text
logical, intent(in), optional :: always
integer, intent(out), optional :: RC
private subroutine MAPL_MemUtilsWriteComm(text, Comm, always, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: text
integer, optional :: Comm
logical, intent(in), optional :: always
integer, intent(out), optional :: RC
Call graph
mapl_memutilswrite calls mapl_memutilswritecomm, mapl_memutilswritevm
mapl_memutilswritecomm calls write_parallel, mpi_allreduce, mpi_comm_size, mapl_return, mapl_verify, mem_dump
mapl_memutilswritevm calls mapl_memutilswritecomm, ESMF_VMGet, mapl_return, mapl_verify
write_parallel calls write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r4_1, write_parallel_r8_0, write_parallel_r8_1, write_parallel_string_0
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mem_dump calls mapl_return, mapl_verify, get_unit
get_error_message calls at
mapl_throw_exception calls initialize
write_parallel_i4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_i4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_r4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_r4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_r8_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_r8_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_string_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write
mapl_genericinitialize calls mapl_memutilswrite
run_mapl_gridcomp calls mapl_memutilswrite
test_main calls mapl_memutilswrite
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
run_gc calls run_mapl_gridcomp
utcfio calls test_main