MAPL_VarReadNCPar – MAPL
MAPL_VarReadNCPar Interface
7 statements
Source File
public interface MAPL_VarReadNCPar
Calls
Called by
Contents
Module Procedures
MAPL_StateVarReadNCPar MAPL_BundleReadNCPar MAPL_ArrayReadNCpar_1d MAPL_ArrayReadNCpar_2d MAPL_ArrayReadNCpar_3d
Module Procedures
private subroutine MAPL_StateVarReadNCPar(filename, STATE, ARRDES, bootstrapable, NAME, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(ESMF_State), intent(inout) :: STATE
type(ArrDescr), intent(inout) :: ARRDES
logical, intent(in) :: bootstrapable
character(len=*), intent(in), optional :: NAME
integer, intent(out), optional :: RC
private subroutine MAPL_BundleReadNCPar(Bundle, arrdes, filename, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
type(ArrDescr), intent(inout) :: arrdes
character(len=*), intent(in) :: filename
integer, intent(out), optional :: rc
private subroutine MAPL_ArrayReadNCpar_1d(varn, filename, farrayPtr, arrDes, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: varn
character(len=*), intent(in) :: filename
real, pointer :: farrayPtr(:)
type(ArrDescr), intent(inout) :: arrDes
integer, intent(out), optional :: rc
private subroutine MAPL_ArrayReadNCpar_2d(varn, filename, farrayPtr, arrDes, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: varn
character(len=*), intent(in) :: filename
real, pointer :: farrayPtr(:,:)
type(ArrDescr), intent(inout) :: arrDes
integer, intent(out), optional :: rc
private subroutine MAPL_ArrayReadNCpar_3d(varn, filename, farrayPtr, arrDes, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: varn
character(len=*), intent(in) :: filename
real, pointer :: farrayPtr(:,:,:)
type(ArrDescr), intent(inout) :: arrDes
integer, intent(out), optional :: rc
Call graph
mapl_varreadncpar calls mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d, mapl_bundlereadncpar, mapl_statevarreadncpar
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_statevarreadncpar calls mapl_varreadncpar
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
refresh_state calls mapl_genericstaterestore