MAPL_VarWriteNCPar – MAPL
MAPL_VarWriteNCPar Interface
4 statements
Source File
public interface MAPL_VarWriteNCPar
Calls
Called by
Module Procedures
private subroutine MAPL_StateVarWriteNCPar(filename, STATE, ARRDES, CLOCK, NAME, forceWriteNoRestart, oClients, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(ESMF_State), intent(in) :: STATE
type(ArrDescr), intent(inout) :: ARRDES
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in), optional :: NAME
logical, intent(in), optional :: forceWriteNoRestart
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
private subroutine MAPL_BundleWriteNCPar(Bundle, arrdes, CLOCK, filename, oClients, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
type(ArrDescr), intent(inout) :: arrdes
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in) :: filename
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: rc
Call graph
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave
mapl_genericwrapper calls record_component