MAPL_CoresPerNodeGet – MAPL
MAPL_CoresPerNodeGet Interface
306 statements
Source File
interface
Calls
Called by
public module function MAPL_CoresPerNodeGet(comm, RC) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(out), optional :: RC
Return Value integer
Call graph
mapl_corespernodeget calls mapl_corespernodeget, mapl_getnodeinfo, mapl_verify, mapl_return
mapl_getnodeinfo calls mapl_getnodeinfo, mapl_verify, mapl_return, getnodecomm, getnoderootscomm
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_cfioreadbundle calls mapl_corespernodeget
mapl_cfiocreatefrombundle calls mapl_corespernodeget
mapl_collectivegather3d calls mapl_corespernodeget
initialize_gc calls mapl_corespernodeget
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadstate, mapl_cfioreadfield, mapl_cfioreadarray3d, mapl_cfioreadarray2d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadstate, mapl_cfioreadfield, mapl_cfioreadarray3d, mapl_cfioreadarray2d
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
regrid_scalar_3d_real32 calls mapl_collectivegather3d
mapl_cfioreadarray3d calls mapl_cfioreadfield
test_main calls esmf_ioread, esmf_iocreate, mapl_cfioread
mapl_simplebundleread calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
initialize_ calls mapl_cfioread
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
utcfio calls test_main
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2