MAPL_CommsBcast – MAPL
MAPL_CommsBcast Interface
24 statements
Source File
public interface MAPL_CommsBcast
Calls
Called by
Contents
Module Procedures
MAPL_CommsBcast_STRING_0 MAPL_CommsBcast_L4_0 MAPL_CommsBcast_I4_0 MAPL_CommsBcast_R4_0 MAPL_CommsBcast_R8_0 MAPL_CommsBcast_I4_1 MAPL_CommsBcast_R4_1 MAPL_CommsBcast_R8_1 MAPL_CommsBcast_I4_2 MAPL_CommsBcast_R4_2 MAPL_CommsBcast_R8_2 MAPL_CommsBcastVm_STRING_0 MAPL_CommsBcastVm_L4_0 MAPL_CommsBcastVm_I4_0 MAPL_CommsBcastVm_R4_0 MAPL_CommsBcastVm_R8_0 MAPL_CommsBcastVm_I4_1 MAPL_CommsBcastVm_R4_1 MAPL_CommsBcastVm_R8_1 MAPL_CommsBcastVm_I4_2 MAPL_CommsBcastVm_R4_2 MAPL_CommsBcastVm_R8_2
Module Procedures
private subroutine MAPL_CommsBcast_STRING_0(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
character(len=*), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_L4_0(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
logical, intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_I4_0(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_R4_0(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_R8_0(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_I4_1(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_R4_1(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_R8_1(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_I4_2(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_R4_2(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcast_R8_2(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVM_STRING_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
character(len=*), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_L4_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
logical, intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_I4_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
integer(kind=ESMF_KIND_I4), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_R4_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
real(kind=ESMF_KIND_R4), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_R8_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
real(kind=ESMF_KIND_R8), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_I4_1(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_R4_1(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
real(kind=ESMF_KIND_R4), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_R8_1(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
real(kind=ESMF_KIND_R8), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_I4_2(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_R4_2(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
real(kind=ESMF_KIND_R4), intent(inout) :: data(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
private subroutine MAPL_CommsBcastVm_R8_2(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
real(kind=ESMF_KIND_R8), intent(inout) :: data(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
Call graph
mapl_commsbcast calls mapl_commsbcast_string_0, mapl_commsbcastvm_r8_0, mapl_commsbcast_i4_0, mapl_commsbcast_r8_2, mapl_commsbcast_r8_0, mapl_commsbcast_r8_1, mapl_commsbcast_i4_2, mapl_commsbcast_r4_2, mapl_commsbcastvm_r4_1, mapl_commsbcastvm_r8_1, mapl_commsbcastvm_l4_0, mapl_commsbcast_r4_0, mapl_commsbcast_i4_1, mapl_commsbcastvm_r4_0, mapl_commsbcast_l4_0, mapl_commsbcast_r4_1, mapl_commsbcastvm_i4_2, mapl_commsbcastvm_r4_2, mapl_commsbcastvm_i4_1, mapl_commsbcastvm_i4_0, mapl_commsbcastvm_string_0, mapl_commsbcastvm_r8_2
mapl_commsbcast_string_0 calls mapl_commsbcast, esmf_delayoutget, mapl_return, mapl_verify
mapl_commsbcastvm_r8_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_i4_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r8_2 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r8_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r8_1 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_i4_2 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r4_2 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r4_1 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r8_1 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_l4_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r4_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_i4_1 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r4_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_l4_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r4_1 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_i4_2 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r4_2 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_i4_1 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_i4_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_string_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget, mapl_assert
mapl_commsbcastvm_r8_2 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
read_parallel_r4_2 calls mapl_commsbcast
read_parallel_r8_2 calls mapl_commsbcast
read_parallel_r8_0 calls mapl_commsbcast
mapl_bcastshared_1dr4 calls mapl_commsbcast
mapl_locstreamcreatefromfile calls mapl_commsbcast
mapl_varwrite_r8_1d calls mapl_commsbcast
read_parallel_i4_1 calls mapl_commsbcast
read_parallel_r4_0 calls mapl_commsbcast
read_parallel_r4_1 calls mapl_commsbcast
read_parallel_r8_1 calls mapl_commsbcast
mapl_areamean_2d_r8_bitrep calls mapl_commsbcast
read_parallel_string_0 calls mapl_commsbcast
mapl_fieldread calls mapl_commsbcast
mapl_getlatloncoord_real32 calls mapl_commsbcast
mapl_bcastshared_2dr4 calls mapl_commsbcast
initialize calls mapl_commsbcast
mapl_esmfstatereadfromfile calls mapl_commsbcast
mapl_getlatloncoord_real64 calls mapl_commsbcast
mapl_varwrite_r4_1d calls mapl_commsbcast
read_parallel_i4_0 calls mapl_commsbcast
read_parallel_i4_2 calls mapl_commsbcast
mapl_varread_r8_1d calls mapl_commsbcast
mapl_sungetsolarconstantfromnrlfile calls mapl_commsbcast
mapl_varread_r4_1d calls mapl_commsbcast
mapl_cfiocreatefrombundle calls mapl_commsbcast
readrestart calls mapl_commsbcast