MAPL_BcastShared – MAPL
MAPL_BcastShared Interface
7 statements
Source File
public interface MAPL_BcastShared
Calls
Called by
Module Procedures
private subroutine MAPL_BcastShared_1DR4(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
real, intent(inout), pointer :: Data(:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
private subroutine MAPL_BcastShared_1DR8(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
real(kind=REAL64), intent(inout), pointer :: Data(:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
private subroutine MAPL_BcastShared_2DI4(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
integer, intent(inout), pointer :: Data(:,:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
private subroutine MAPL_BcastShared_2DR4(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
real, intent(inout), pointer :: Data(:,:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
private subroutine MAPL_BcastShared_2DR8(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
real(kind=REAL64), intent(inout), pointer :: Data(:,:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
Call graph
mapl_bcastshared calls mapl_bcastshared_1dr4, mapl_bcastshared_1dr8, mapl_bcastshared_2di4, mapl_bcastshared_2dr4, mapl_bcastshared_2dr8
mapl_bcastshared_1dr4 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
mapl_bcastshared_1dr8 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
mapl_bcastshared_2di4 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
mapl_bcastshared_2dr4 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
mapl_bcastshared_2dr8 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
add_horz_coordinates_from_abifile calls mapl_bcastshared
add_horz_coordinates_from_file calls mapl_bcastshared
get_obs_time calls mapl_bcastshared
mapl_cfioreadbundle calls mapl_bcastshared
mapl_cfiowritebundlepost calls mapl_bcastshared
mapl_locstreamcreatefromfile calls mapl_bcastshared
read_geos_binary calls mapl_bcastshared
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize_subclass calls read_geos_binary
make_new_grid calls add_horz_coordinates_from_file, add_horz_coordinates_from_abifile
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
esmf_iowrite calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle
initialize calls mapl_locstreamcreate
initialize_ calls mapl_cfioread, mapl_locstreamcreate
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread