MAPL_CheckpointState – MAPL
MAPL_CheckpointState Interface
3 statements
Source File
public interface MAPL_CheckpointState
Calls
Contents
Module Procedures
MAPL_ESMFStateWriteToFile
Module Procedures
private subroutine MAPL_ESMFStateWriteToFile(STATE, CLOCK, FILENAME, FILETYPE, MPL, HDR, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in) :: FILENAME
character(len=*), intent(inout) :: FILETYPE
type(MAPL_MetaComp), intent(inout) :: MPL
logical, intent(in) :: HDR
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
Call graph
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_esmfstatewritetofile calls esmf_clockget, free_file, mpi_info_create, mapl_isstateempty, mpi_info_set, mpi_comm_rank, esmf_gridget, esmf_attributeget, mapl_locstreamisassociated, mapl_gridget, arrdescrset, mapl_locstreamget, mapl_assert, mpi_file_close, mpi_comm_size, write_parallel, mapl_getresource, mpi_info_free, mapl_varwritencpar, mpi_file_open, mapl_return, warn_empty, mapl_verify, getfile, mapl_varwrite, mpi_barrier, arrdescrsetncpar, esmf_timeget