MAPL_Sort – MAPL
MAPL_Sort Interface
16 statements
Source File
public interface MAPL_Sort
Calls
Called by
Contents
Module Procedures
SORT1SS SORT1SR SORT1SD SORT1LS SORT1LR SORT1LD SORT2LS SORT2LR SORT2LD SORT2SS SORT2SR SORT2SD SORT2AS SORT2AL
Module Procedures
private subroutine SORT1SS(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
integer(kind=INT32), intent(inout), optional :: B(:)
private subroutine SORT1SR(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
real(kind=REAL32), intent(inout) :: B(:)
private subroutine SORT1SD(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
real(kind=REAL64), intent(inout) :: B(:)
private subroutine SORT1LS(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
integer(kind=INT32), intent(inout), optional :: B(:)
private subroutine SORT1LR(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
real(kind=REAL32), intent(inout) :: B(:)
private subroutine SORT1LD(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
real(kind=REAL64), intent(inout) :: B(:)
private subroutine SORT2LS(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
integer(kind=INT32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2LR(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
real(kind=REAL32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2LD(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
real(kind=REAL64), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2SS(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
integer(kind=INT32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2SR(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
real(kind=REAL32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2SD(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
real(kind=REAL64), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2AS(B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
private subroutine SORT2AL(B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
Call graph
mapl_sort calls sort2ld, sort2sr, sort2as, sort1sd, sort2al, sort1ss, sort1sr, sort1ls, sort1lr, sort1ld, sort2ls, sort2sd, sort2lr, sort2ss
sort2ld calls mapl_assert, qsortl
sort2sr calls mapl_assert, qsorts
sort2as calls mapl_assert, qsorts
sort1sd calls qsorts
sort2al calls mapl_assert, qsortl
sort1ss calls qsorts
sort1sr calls qsorts
sort1ls calls qsortl
sort1lr calls qsortl
sort1ld calls qsortl
sort2ls calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort2lr calls mapl_assert, qsortl
sort2ss calls mapl_assert, qsorts
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
split_server_pools calls mapl_sort
mapl_tilemaskget calls mapl_sort
foo calls mapl_sort
mapl_varread_r4_1d calls mapl_sort
getnodecomm calls mapl_sort, getnodecomm
mapl_getimsjms calls mapl_sort
mapl_varread_r8_1d calls mapl_sort
mapl_cfiopartition calls mapl_sort
arrdescrinit calls mapl_sort
test_mapl_sort calls mapl_sort
set_optimal_server calls mapl_sort
set calls mapl_getimsjms
mapl_gridgetsection calls mapl_getimsjms
mapl_fieldwrite calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
writerestart calls mapl_tilemaskget
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r8_1d
mapl_genericinitialize calls mapl_getimsjms
esmfl_halo_r4_2d calls mapl_getimsjms
get_esmf_grid_layout calls mapl_getimsjms
mapl_cfioreadparallel_ calls mapl_cfiopartition