MAPL_ArrayIScatter – MAPL
MAPL_ArrayIScatter Interface
3 statements
Source File
public interface MAPL_ArrayIScatter
Calls
Called by
Module Procedures
private subroutine MAPL_ArrayIScatter_R4_2(global_array, request, hw, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: global_array(:,:)
type(MAPL_CommRequest), intent(inout) :: request
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
Call graph
mapl_arrayiscatter calls mapl_arrayiscatter_r4_2
mapl_arrayiscatter_r4_2 calls mpi_isend, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_cfioreadbundleread calls mapl_arrayiscatter
mapl_collectivescatter3d calls mapl_arrayiscatter
mapl_cfioreadbundle calls mapl_collectivescatter3d
mapl_cfioreadparallel_ calls mapl_cfioreadbundleread
regrid_scalar_3d_real32 calls mapl_collectivescatter3d
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread