MAPL_CommsGatherV – MAPL
MAPL_CommsGatherV Interface
7 statements
Source File
public interface MAPL_CommsGatherV
Calls
Called by
Module Procedures
private subroutine MAPL_CommsGatherV_I4_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
integer(kind=ESMF_KIND_I4), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsGatherV_R4_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R4), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsGatherV_R4_2(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:,:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R4), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsGatherV_R8_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R8), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsGatherV_R8_2(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:,:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R8), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(in) :: root
integer, intent(out), optional :: RC
Call graph
mapl_commsgatherv calls mapl_commsgatherv_i4_1, mapl_commsgatherv_r4_1, mapl_commsgatherv_r4_2, mapl_commsgatherv_r8_1, mapl_commsgatherv_r8_2
mapl_commsgatherv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_gatherv, mapl_return, mapl_verify
mapl_commsgatherv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_gatherv, mapl_return, mapl_verify
mapl_commsgatherv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_gatherv, mapl_return, mapl_verify
mapl_commsgatherv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_gatherv, mapl_return, mapl_verify
mapl_commsgatherv_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_gatherv, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
arraygather_i4_1 calls mapl_commsgatherv
arraygather_r4_1 calls mapl_commsgatherv
arraygather_r4_2 calls mapl_commsgatherv
arraygather_r8_1 calls mapl_commsgatherv
arraygather_r8_2 calls mapl_commsgatherv
mapl_tilemaskget calls mapl_commsgatherv
arraygather calls arraygather_i4_1, arraygather_r4_1, arraygather_r4_2, arraygather_r8_1, arraygather_r8_2
mapl_bundlereadncpar calls mapl_tilemaskget
mapl_bundlewritencpar calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
mapl_fieldreadncpar calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_fieldwritencpar calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
process_data_from_file calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget