MAPL_VarSpecAddRefToList – MAPL
MAPL_VarSpecAddRefToList Interface
4 statements
Source File
public interface MAPL_VarSpecAddRefToList
Calls
Called by
Module Procedures
private subroutine MAPL_VarSpecAddRefFromItem(SPEC, ITEM, ALLOW_DUPLICATES, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM
logical, intent(in), optional :: ALLOW_DUPLICATES
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecAddRefFromList(SPEC, ITEM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM(:)
integer, intent(out), optional :: RC
Call graph
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_varspecaddreffromitem calls mapl_varspecgetindex, mapl_varspecprint, get_logger, error, mapl_return, mapl_verify
mapl_varspecaddreffromlist calls mapl_varspecaddreffromitem, mapl_return, mapl_verify
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecprintmany calls mapl_varspecprint, mapl_return, mapl_verify
mapl_varspecprintone calls mapl_return, info
mapl_genericspecenum calls mapl_varspecaddreftolist, mapl_genericspecenum
mapl_setvarspecforcc calls mapl_varspecaddreftolist
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_genericsetservices calls mapl_genericspecenum, mapl_wirecomponent
addnewspec calls mapl_addexportspec, mapl_addimportspec
setservices calls mapl_addexportspec, mapl_genericsetservices, mapl_addinternalspec
addstate calls addnewspec