MAPL_Am_I_Rank – MAPL
MAPL_Am_I_Rank Interface
5 statements
Source File
public interface MAPL_Am_I_Rank
Calls
Called by
Contents
Module Procedures
MAPL_Am_I_Rank_Only MAPL_Am_I_Rank_Layout MAPL_Am_I_Rank_Vm
Module Procedures
private function MAPL_Am_I_Rank_Only(rank) result(R)
Arguments
Type Intent Optional Attributes Name
integer, optional :: rank
Return Value logical
private function MAPL_Am_I_Rank_Layout(layout, rank) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer, optional :: rank
Return Value logical
private function MAPL_Am_I_Rank_Vm(VM, rank) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
integer, optional :: rank
Return Value logical
Call graph
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout
mapl_am_i_rank_only calls mapl_am_i_rank, esmf_vmgetcurrent
mapl_am_i_rank_vm calls esmf_vmget
mapl_am_i_rank_layout calls mapl_am_i_rank, esmf_delayoutget
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root calls mapl_am_i_root_vm, mapl_am_i_root_layout