MAPL_Get – MAPL
MAPL_Get Interface
3 statements
Source File
public interface MAPL_Get
Calls
Called by
Module Procedures
private subroutine MAPL_GenericStateGet(STATE, IM, JM, LM, VERTDIM, NX, NY, NX0, NY0, LAYOUT, GCNames, LONS, LATS, grid, ORBIT, RUNALARM, IMPORTspec, EXPORTspec, INTERNALspec, INTERNAL_ESMF_STATE, TILETYPES, TILEKIND, TILELATS, TILELONS, TILEAREA, LOCSTREAM, EXCHANGEGRID, CLOCK, NumInitPhases, NumRunPhases, GCS, CCS, GIM, GEX, CF, HEARTBEAT, childrens_names, childrens_gridcomps, childrens_import_states, childrens_export_states, RC)
This is the way of querying the opaque {\em MAPL_Generic} state object. The arguments are: - STATE The MAPL object to be queried. - IM Size of the first horizontal dimension (X) of local arrays. - JM Size of the second horizontal dimension (Y) of local arrays. - LM Size of the vertical dimension. - VERTDIM Position of the vertical dimension of 2 or higher dimensional arrays. - NX Size of the DE array dimension aligned with the first horizontal dimension of arrays - NY Size of the DE array dimension aligned with the second horizontal dimension of arrays - NX0, NY0 Coordinates of current DE. - LONS X coordinates of array locations. Currently longitude in radians. - LATS Y coordinates of array locations. Currently latitude in radians. - INTERNAL_ESMF_STATE The gridded component’s INTERNAL state. - GCNames Names of the children. - GCS The child gridded components. - GIM The childrens’ IMPORT states. - GEX The childrens’ EXPORT states. - CCS Array of child-to-child couplers.
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: STATE
integer, intent(out), optional :: IM
integer, intent(out), optional :: JM
integer, intent(out), optional :: LM
integer, intent(out), optional :: VERTDIM
integer, intent(out), optional :: NX
integer, intent(out), optional :: NY
integer, intent(out), optional :: NX0
integer, intent(out), optional :: NY0
type(ESMF_DELayout), intent(out), optional :: LAYOUT
character(len=ESMF_MAXSTR), optional, pointer :: GCNames(:)
real, optional, pointer :: LONS(:,:)
real, optional, pointer :: LATS(:,:)
type(ESMF_Grid), optional :: grid
type(MAPL_SunOrbit), intent(out), optional :: ORBIT
type(ESMF_Alarm), intent(out), optional :: RUNALARM
type(MAPL_VarSpec), optional, pointer :: IMPORTspec(:)
type(MAPL_VarSpec), optional, pointer :: EXPORTspec(:)
type(MAPL_VarSpec), optional, pointer :: INTERNALspec(:)
type(ESMF_State), intent(out), optional :: INTERNAL_ESMF_STATE
integer, optional, pointer :: TILETYPES(:)
integer, optional, pointer :: TILEKIND(:)
real, optional, pointer :: TILELATS(:)
real, optional, pointer :: TILELONS(:)
real, optional, pointer :: TILEAREA(:)
type(MAPL_LocStream), intent(out), optional :: LOCSTREAM
type(MAPL_LocStream), intent(out), optional :: EXCHANGEGRID
type(ESMF_Clock), intent(out), optional :: CLOCK
integer, intent(out), optional :: NumInitPhases
integer, intent(out), optional :: NumRunPhases
type(ESMF_GridComp), optional, pointer :: GCS(:)
type(ESMF_CplComp), optional, pointer :: CCS(:,:)
type(ESMF_State), optional, pointer :: GIM(:)
type(ESMF_State), optional, pointer :: GEX(:)
type(ESMF_Config), intent(out), optional :: CF
real, intent(out), optional :: HEARTBEAT
character(len=ESMF_MAXSTR), optional, allocatable :: childrens_names(:)
type(ESMF_GridComp), optional, allocatable :: childrens_gridcomps(:)
type(ESMF_State), optional, allocatable :: childrens_import_states(:)
type(ESMF_State), optional, allocatable :: childrens_export_states(:)
integer, intent(out), optional :: RC
Call graph
mapl_get calls mapl_genericstateget
mapl_genericstateget calls ESMF_GridGet, get_child_export_state, get_child_gridcomp, get_child_import_state, get_grid, get_internal_state, get_num_children, mapl_locstreamget, mapl_return, mapl_sunorbitcreated, mapl_sunorbitcreatefromconfig, mapl_verify
get_child_export_state calls get_export_state, get_ith_child
get_child_gridcomp calls get_gridcomp, get_ith_child
get_child_import_state calls get_import_state, get_ith_child
get_grid calls get_current_thread, is_threading_active
get_internal_state calls get_current_thread, is_threading_active
get_num_children calls get_num_children
mapl_locstreamget calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_sunorbitcreated calls mapl_return
mapl_sunorbitcreatefromconfig calls mapl_return, mapl_verify, ESMF_ConfigGetAttribute
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
get_export_state calls get_current_thread, is_threading_active
get_gridcomp calls get_current_thread, is_threading_active
get_import_state calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_throw_exception calls initialize
initialize_ calls mapl_get
initialize_gc calls mapl_get
mapl_donotallocateimport calls mapl_get
mapl_donotallocateinternal calls mapl_get
mapl_internalesmfstateget calls mapl_get, mapl_internalesmfstateget
run_ calls mapl_get
get_field_from_internal calls mapl_internalesmfstateget