MAPL_VarSpecGetIndex – MAPL
MAPL_VarSpecGetIndex Interface
4 statements
Source File
public interface MAPL_VarSpecGetIndex
Calls
Called by
Module Procedures
private function MAPL_VarSpecGetIndexByName(SPEC, NAME, RC) result(INDEX)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC(:)
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Return Value integer
private function MAPL_VarSpecGetIndexOfItem(SPEC, ITEM, RC) result(INDEX)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM
integer, intent(out), optional :: RC
Return Value integer
Call graph
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
checkreq calls mapl_varspecgetindex
mapl_donotallocatevar calls mapl_varspecgetindex
mapl_donotdeferexport calls mapl_varspecgetindex
mapl_friendlyget calls mapl_varspecgetindex
mapl_readforcingx calls mapl_varspecgetindex
mapl_setvarspecforcc calls mapl_varspecgetindex
mapl_stateaddimportspecfrmchld calls mapl_varspecgetindex
mapl_stateaddinternalspec calls mapl_varspecgetindex
mapl_statecreatefromspecnew calls mapl_varspecgetindex
mapl_stategetspecattrib calls mapl_varspecgetindex
mapl_statesetspecattrib calls mapl_varspecgetindex
mapl_varspecaddreffromitem calls mapl_varspecgetindex
mapl_varspecaddreffromitemnew calls mapl_varspecgetindex
mapl_varspeccreateinlist calls mapl_varspecgetindex
mapl_varspecreconnect calls mapl_varspecgetindex
mapl_wirecomponent calls mapl_varspecgetindex
test_add_spec_grows_container calls mapl_varspecgetindex