MAPL_VerifyFriendly – MAPL
MAPL_VerifyFriendly Interface
4 statements
Source File
public interface MAPL_VerifyFriendly
Calls
Called by
Contents
Module Procedures
MAPL_VerifyFriendlyInField MAPL_VerifyFriendlyInState
Module Procedures
private function MAPL_VerifyFriendlyInField(FIELD, FRIEND2COMP, RC) result(FRIENDLY)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
character(len=*), intent(in) :: FRIEND2COMP
integer, intent(out), optional :: RC
Return Value logical
private function MAPL_VerifyFriendlyInState(STATE, NAME, FRIEND2COMP, RC) result(FRIENDLY)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: STATE
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: FRIEND2COMP
integer, intent(out), optional :: RC
Return Value logical
Call graph
mapl_verifyfriendly calls mapl_verifyfriendlyinfield, mapl_verifyfriendlyinstate
mapl_verifyfriendlyinfield calls ESMF_AttributeGet, mapl_return, mapl_verify
mapl_verifyfriendlyinstate calls mapl_verifyfriendly, esmf_stateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize