MAPL_CommsAllGather – MAPL
MAPL_CommsAllGather Interface
4 statements
Source File
public interface MAPL_CommsAllGather
Calls
Called by
Contents
Module Procedures
MAPL_CommsAllGather_I4_1 MAPL_CommsAllGather_L4_1
Module Procedures
private subroutine MAPL_CommsAllGather_I4_1(vm, sendbuf, sendcnt, recvbuf, recvcnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer, intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
integer, intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllGather_L4_1(vm, sendbuf, sendcnt, recvbuf, recvcnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
logical, intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
logical, intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcnt
integer, intent(out), optional :: RC
Call graph
mapl_commsallgather calls mapl_commsallgather_i4_1, mapl_commsallgather_l4_1
mapl_commsallgather_i4_1 calls ESMF_VMGet, mpi_allgather, mapl_return, mapl_verify
mapl_commsallgather_l4_1 calls ESMF_VMGet, mpi_allgather, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_locstreamcreatexform calls mapl_commsallgather
initialize calls mapl_locstreamcreatexform