MAPL_CommsRecv – MAPL
MAPL_CommsRecv Interface
8 statements
Source File
public interface MAPL_CommsRecv
Calls
Contents
Module Procedures
MAPL_CommsRecv_I4_0 MAPL_CommsRecv_I4_1 MAPL_CommsRecv_R4_1 MAPL_CommsRecv_R4_2 MAPL_CommsRecv_R8_1 MAPL_CommsRecv_R8_2
Module Procedures
private subroutine MAPL_CommsRecv_I4_0(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsRecv_I4_1(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsRecv_R4_1(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsRecv_R4_2(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: data(:,:)
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsRecv_R8_1(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsRecv_R8_2(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: data(:,:)
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
Call graph
mapl_commsrecv calls mapl_commsrecv_i4_0, mapl_commsrecv_i4_1, mapl_commsrecv_r8_1, mapl_commsrecv_r4_1, mapl_commsrecv_r4_2, mapl_commsrecv_r8_2
mapl_commsrecv_i4_0 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_recv, mapl_return
mapl_commsrecv_i4_1 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_recv, mapl_return
mapl_commsrecv_r8_1 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_recv, mapl_return
mapl_commsrecv_r4_1 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_recv, mapl_return
mapl_commsrecv_r4_2 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_recv, mapl_return
mapl_commsrecv_r8_2 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_recv, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize