MAPL_AddConnectivity – MAPL
MAPL_AddConnectivity Interface
5 statements
Source File
public interface MAPL_AddConnectivity
Calls
Called by
Contents
Module Procedures
MAPL_AddConnectivityRename MAPL_AddConnectivityRenameMany MAPL_AddConnectivityMany
Module Procedures
private subroutine MAPL_AddConnectivityRename(GC, SRC_NAME, SRC_ID, DST_NAME, DST_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SRC_NAME
integer, intent(in) :: SRC_ID
character(len=*), intent(in) :: DST_NAME
integer, intent(in) :: DST_ID
integer, intent(out), optional :: RC
private subroutine MAPL_AddConnectivityRenameMany(GC, SRC_NAME, SRC_ID, DST_NAME, DST_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SRC_NAME(:)
integer, intent(in) :: SRC_ID
character(len=*), intent(in) :: DST_NAME(:)
integer, intent(in) :: DST_ID
integer, intent(out), optional :: RC
private subroutine MAPL_AddConnectivityMany(GC, SHORT_NAME, SRC_ID, DST_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME(:)
integer, intent(in) :: SRC_ID
integer, intent(in) :: DST_ID
integer, intent(out), optional :: RC
Call graph
mapl_addconnectivity calls mapl_addconnectivityrename, mapl_addconnectivitymany, mapl_addconnectivityrenamemany
mapl_addconnectivityrename calls mapl_connectivityget, mapl_verify, mapl_return
mapl_addconnectivitymany calls mapl_addconnectivityrename, mapl_verify, mapl_return
mapl_addconnectivityrenamemany calls mapl_addconnectivity, mapl_verify, mapl_return
mapl_connectivityget calls mapl_verify, mapl_return, mapl_getobjectfromgc
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
mapl_throw_exception calls initialize
setservices calls mapl_addconnectivity, setservices