MAPL_ShmemAmOnFirstNode – MAPL
MAPL_ShmemAmOnFirstNode Interface
306 statements
Source File
interface
Calls
Called by
public module function MAPL_ShmemAmOnFirstNode(comm, RC) result(a) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(out), optional :: RC
Return Value logical
Call graph
mapl_shmemamonfirstnode calls mapl_shmemamonfirstnode, mapl_assert, mapl_getnodeinfo, mpi_comm_rank, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_getnodeinfo calls mapl_getnodeinfo, mapl_return, mapl_verify, getnodecomm, getnoderootscomm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_cfioreadbundle calls mapl_shmemamonfirstnode
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread
utcfio calls test_main