MAPL_AllocNodeArray_4DR8 – MAPL
MAPL_AllocNodeArray_4DR8 Interface
313 statements
Source File
interface
Called by
private module subroutine MAPL_AllocNodeArray_4DR8(Ptr, Shp, lbd, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), pointer :: Ptr(:,:,:,:)
integer, intent(in) :: Shp(4)
integer, intent(in), optional :: lbd(4)
integer, intent(out), optional :: rc
Call graph
mapl_allocnodearray calls mapl_allocnodearray_4dr8
initialize_subclass calls mapl_allocnodearray
mapl_allocateshared_1di4 calls mapl_allocnodearray
mapl_allocateshared_1dl4 calls mapl_allocnodearray
mapl_allocateshared_1dr4 calls mapl_allocnodearray
mapl_allocateshared_1dr8 calls mapl_allocnodearray
mapl_allocateshared_2di4 calls mapl_allocnodearray
mapl_allocateshared_2dr4 calls mapl_allocnodearray
mapl_allocateshared_2dr8 calls mapl_allocnodearray
mapl_cfioreadbundle calls mapl_allocnodearray
mapl_cfiowritebundlepost calls mapl_allocnodearray
mapl_tilemaskget calls mapl_allocnodearray
mapl_varread_r4_1d calls mapl_allocnodearray
mapl_varread_r4_2d calls mapl_allocnodearray
mapl_varreadncpar_r4_1d calls mapl_allocnodearray