MAPL_FieldGetTime – MAPL
MAPL_FieldGetTime Interface
4 statements
Source File
public interface MAPL_FieldGetTime
Calls
Called by
Contents
Module Procedures
MAPL_GetFieldTimeFromField MAPL_GetFieldTimeFromState
Module Procedures
private interface MAPL_GetFieldTimeFromField()
Arguments
None
private interface MAPL_GetFieldTimeFromState()
Arguments
None
Call graph
mapl_fieldgettime calls mapl_getfieldtimefromfield, mapl_getfieldtimefromstate
mapl_getfieldtimefromfield calls mapl_getfieldtimefromfield, esmf_attributeget, mapl_verify, mapl_timestringget, esmf_timeset, mapl_return
mapl_getfieldtimefromstate calls mapl_getfieldtimefromstate, mapl_fieldgettime, mapl_verify, mapl_return, esmf_stateget
mapl_verify calls mapl_throw_exception
mapl_timestringget calls mapl_timestringget
mapl_return calls mapl_throw_exception, get_error_message
mapl_climupdate calls mapl_fieldgettime