MAPL_LEAP – MAPL
MAPL_LEAP Interface
361 statements
Source File
interface
Calls
Called by
public module function MAPL_LEAP(NY) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: NY
Return Value logical
Call graph
mapl_leap calls mapl_leap
mapl_incymd calls mapl_leap, mapl_incymd
test_mapl_leap calls mapl_leap
mapl_tick calls mapl_incymd, mapl_tick