MAPL_GetLatLonCoord – MAPL
MAPL_GetLatLonCoord Interface
4 statements
Source File
public interface MAPL_GetLatLonCoord
Calls
Called by
Contents
Module Procedures
MAPL_GetLatLonCoord_REAL64 MAPL_GetLatLonCoord_REAL32
Module Procedures
private subroutine MAPL_GetLatLonCoord_REAL64(grid, dim, x, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
integer, intent(in) :: dim
real(kind=REAL64), intent(out) :: x(:)
integer, intent(out), optional :: rc
private subroutine MAPL_GetLatLonCoord_REAL32(grid, dim, x, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
integer, intent(in) :: dim
real(kind=REAL32), intent(out) :: x(:)
integer, intent(out), optional :: rc
Call graph
mapl_getlatloncoord calls mapl_getlatloncoord_real64, mapl_getlatloncoord_real32
mapl_getlatloncoord_real64 calls esmf_gridgetcoord, mapl_verify, esmf_gridget, mapl_gridget, arraygather, esmf_distgridget, esmf_delayoutget, esmf_vmget, mapl_assert, mapl_commsbcast
mapl_getlatloncoord_real32 calls esmf_gridgetcoord, mapl_verify, esmf_gridget, mapl_gridget, arraygather, esmf_distgridget, esmf_delayoutget, esmf_vmget, mapl_assert, mapl_commsbcast
gridgetlatlons_ calls mapl_getlatloncoord
initialize_subclass calls mapl_getlatloncoord
mapl_cfioreadbundle calls gridgetlatlons_
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadstate, mapl_cfioreadfield
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadstate, mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
test_main calls esmf_ioread, mapl_cfioread
mapl_simplebundleread calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
initialize_ calls mapl_cfioread