MAPL_Set – MAPL
MAPL_Set Interface
4 statements
Source File
public interface MAPL_Set
Calls
Called by
Contents
Module Procedures
MAPL_GenericStateSet MAPL_GenericStateSetFromGC
Module Procedures
private subroutine MAPL_GenericStateSet(STATE, ORBIT, LM, RUNALARM, CHILDINIT, LOCSTREAM, EXCHANGEGRID, CLOCK, NAME, CF, ConfigFile, component, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
type(MAPL_SunOrbit), intent(in), optional :: ORBIT
integer, intent(in), optional :: LM
type(ESMF_Alarm), intent(in), optional :: RUNALARM
logical, intent(in), optional :: CHILDINIT
type(MAPL_LocStream), intent(in), optional :: LOCSTREAM
type(MAPL_LocStream), intent(in), optional :: EXCHANGEGRID
type(ESMF_Clock), intent(in), optional :: CLOCK
character(len=*), intent(in), optional :: NAME
type(ESMF_Config), intent(in), optional :: CF
character(len=*), intent(in), optional :: ConfigFile
class(AbstractComponent), intent(in), optional :: component
integer, intent(out), optional :: RC
private subroutine MAPL_GenericStateSetFromGC(GC, ORBIT, LM, RUNALARM, CHILDINIT, LOCSTREAM, EXCHANGEGRID, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_SunOrbit), intent(in), optional :: ORBIT
integer, intent(in), optional :: LM
type(ESMF_Alarm), intent(in), optional :: RUNALARM
logical, intent(in), optional :: CHILDINIT
type(MAPL_LocStream), intent(in), optional :: LOCSTREAM
type(MAPL_LocStream), intent(in), optional :: EXCHANGEGRID
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(out), optional :: RC
Call graph
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
mapl_genericstateset calls ESMF_ConfigCreate, ESMF_ConfigLoadFile, get_composite, get_logger, initialize, mapl_return, mapl_verify, set_component, set_composite, set_logger
mapl_genericstatesetfromgc calls mapl_genericstateset, mapl_internalstateget, mapl_return, mapl_verify
initialize calls initialize_global_time_profiler
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
initialize_global_time_profiler calls get_global_time_profiler
mapl_throw_exception calls initialize
initialize_gc calls mapl_set
mapl_capgridcompcreate calls mapl_set
run_component_driver calls mapl_set
initialize_cap_gc calls mapl_capgridcompcreate
main calls run_component_driver
run_model calls initialize_cap_gc
comp_testing_driver calls main
run_member calls run_model