MAPL_Range – MAPL
MAPL_Range Interface
4 statements
Source File
public interface MAPL_Range
Calls
Called by
Contents
Module Procedures
MAPL_Range_REAL64 MAPL_Range_REAL32
Module Procedures
private function MAPL_Range_REAL64(x0, x1, n, conversion_factor, rc) result(range)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: x0
real(kind=REAL64), intent(in) :: x1
integer, intent(in) :: n
real(kind=REAL64), intent(in), optional :: conversion_factor
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
private function MAPL_Range_REAL32(x0, x1, n, conversion_factor, rc) result(range)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: x0
real(kind=REAL32), intent(in) :: x1
integer, intent(in) :: n
real(kind=REAL64), intent(in), optional :: conversion_factor
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Call graph
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_range_real32 calls mapl_assert, mapl_return
mapl_range_real64 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
compute_lat_centers calls mapl_range
compute_lat_corners calls mapl_range
compute_lon_centers calls mapl_range
compute_lon_corners calls mapl_range
create_lat_lon_grid calls mapl_range
mapl_bundlewritencpar calls mapl_range
mapl_cfiocreatefrombundle calls mapl_range
mapl_latlongridcreate calls mapl_range, mapl_latlongridcreate
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
create_esmf_grids calls create_lat_lon_grid
initialize_from_config_with_prefix calls compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners
initialize_from_file_metadata calls compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners
latlongridfactory_from_parameters calls compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_statevarwritencpar calls mapl_bundlewritencpar
latlongridfactory calls latlongridfactory_from_parameters
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate
main calls create_esmf_grids
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile
utcfio calls test_main