MAPL_CommsAllReduceMin – MAPL
MAPL_CommsAllReduceMin Interface
11 statements
Source File
public interface MAPL_CommsAllReduceMin
Calls
Contents
Module Procedures
MAPL_CommsAllReduceMin_I4_0 MAPL_CommsAllReduceMin_R4_0 MAPL_CommsAllReduceMin_R8_0 MAPL_CommsAllReduceMin_I4_1 MAPL_CommsAllReduceMin_R4_1 MAPL_CommsAllReduceMin_R8_1 MAPL_CommsAllReduceMin_I4_2 MAPL_CommsAllReduceMin_R4_2 MAPL_CommsAllReduceMin_R8_2
Module Procedures
private subroutine MAPL_CommsAllReduceMin_I4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_R4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_R8_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_I4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_R4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_R8_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_I4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:,:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_R4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMin_R8_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Call graph
mapl_commsallreducemin calls mapl_commsallreducemin_i4_0, mapl_commsallreducemin_i4_1, mapl_commsallreducemin_i4_2, mapl_commsallreducemin_r4_0, mapl_commsallreducemin_r4_1, mapl_commsallreducemin_r4_2, mapl_commsallreducemin_r8_0, mapl_commsallreducemin_r8_1, mapl_commsallreducemin_r8_2
mapl_commsallreducemin_i4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_i4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_i4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_r4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_r4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_r4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_r8_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_r8_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemin_r8_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize