MAPL_ReadForcing – MAPL
MAPL_ReadForcing Interface
4 statements
Source File
public interface MAPL_ReadForcing
Calls
Contents
Module Procedures
MAPL_ReadForcing1 MAPL_ReadForcing2
Module Procedures
private subroutine MAPL_ReadForcing1(STATE, NAME, DATAFILE, CURRENTTIME, FORCING, INIT_ONLY, ON_TILES, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: DATAFILE
type(ESMF_Time), intent(inout) :: CURRENTTIME
real, intent(out) :: FORCING(:)
logical, intent(in), optional :: INIT_ONLY
logical, intent(in), optional :: ON_TILES
integer, intent(out), optional :: RC
private subroutine MAPL_ReadForcing2(STATE, NAME, DATAFILE, CURRENTTIME, FORCING, INIT_ONLY, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: DATAFILE
type(ESMF_Time), intent(inout) :: CURRENTTIME
real, intent(out) :: FORCING(:,:)
logical, intent(in), optional :: INIT_ONLY
integer, intent(out), optional :: RC
Call graph
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
mapl_readforcing1 calls mapl_readforcingx, mapl_return
mapl_readforcing2 calls mapl_readforcingx, mapl_return
mapl_readforcingx calls mapl_return, ESMF_TimeGet, ESMF_TimeSet, esmf_stateget, esmfl_stategetpointertodata, mapl_am_i_root, mapl_assert, mapl_interp_fac, mapl_varspecgetindex, read_parallel, getfile, mapl_backspace, mapl_genericstateget, mapl_getnumsubtiles, mapl_locstreamget, mapl_statecreatefromvarspecnew, mapl_stategetspecattrib, mapl_stategettimestamp, mapl_varspeccreateinlistnew, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception