MAPL_EQsat – MAPL
MAPL_EQsat Interface
10 statements
Source File
public interface MAPL_EQsat
Calls
Called by
Contents
Module Procedures
QSAT0 QSAT1 QSAT2 QSAT3 QSATd0 QSATd1 QSATd2 QSATd3
Module Procedures
private recursive function QSAT0(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: TL
real(kind=REAL32), intent(in), optional :: PL
real(kind=REAL32), intent(out), optional :: DQ
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL32)
private function QSAT1(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: TL(:)
real(kind=REAL32), intent(in), optional :: PL(:)
real(kind=REAL32), intent(out), optional :: DQ(:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL32), (SIZE(TL,1))
private function QSAT2(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: TL(:,:)
real(kind=REAL32), intent(in), optional :: PL(:,:)
real(kind=REAL32), intent(out), optional :: DQ(:,:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL32), (SIZE(TL,1),SIZE(TL,2))
private function QSAT3(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: TL(:,:,:)
real(kind=REAL32), intent(in), optional :: PL(:,:,:)
real(kind=REAL32), intent(out), optional :: DQ(:,:,:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL32), (SIZE(TL,1),SIZE(TL,2),SIZE(TL,3))
private recursive function QSATD0(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: TL
real(kind=REAL64), intent(in), optional :: PL
real(kind=REAL64), intent(out), optional :: DQ
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL64)
private function QSATD1(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: TL(:)
real(kind=REAL64), intent(in), optional :: PL(:)
real(kind=REAL64), intent(out), optional :: DQ(:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL64), (SIZE(TL,1))
private function QSATD2(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: TL(:,:)
real(kind=REAL64), intent(in), optional :: PL(:,:)
real(kind=REAL64), intent(out), optional :: DQ(:,:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL64), (SIZE(TL,1),SIZE(TL,2))
private function QSATD3(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: TL(:,:,:)
real(kind=REAL64), intent(in), optional :: PL(:,:,:)
real(kind=REAL64), intent(out), optional :: DQ(:,:,:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL64), (SIZE(TL,1),SIZE(TL,2),SIZE(TL,3))
Call graph
mapl_eqsat calls qsat0, qsat1, qsat2, qsat3, qsatd0, qsatd1, qsatd2, qsatd3
qsat0 calls qsat0, mapl_eqsatset
qsat1 calls qsat0, mapl_eqsatset
qsat2 calls qsat0, mapl_eqsatset
qsat3 calls qsat0, mapl_eqsatset
qsatd0 calls qsatd0, mapl_eqsatset
qsatd1 calls qsatd0, mapl_eqsatset
qsatd2 calls qsatd0, mapl_eqsatset
qsatd3 calls qsatd0, mapl_eqsatset
tstqsat calls mapl_eqsat