MAPL_FieldCreate – MAPL
MAPL_FieldCreate Interface
5 statements
Source File
public interface MAPL_FieldCreate
Calls
Called by
Contents
Module Procedures
MAPL_FieldCreateRename MAPL_FieldCreateNewgrid MAPL_FieldCreateR4
Module Procedures
private interface MAPL_FieldCreateRename()
Arguments
None
private interface MAPL_FieldCreateNewgrid()
Arguments
None
private interface MAPL_FieldCreateR4()
Arguments
None
Call graph
mapl_fieldcreate calls mapl_fieldcreatenewgrid, mapl_fieldcreater4, mapl_fieldcreaterename
mapl_fieldcreatenewgrid calls mapl_fieldcreatenewgrid, ESMF_AttributeSet, ESMF_GridGet, esmf_arrayget, esmf_fieldcreate, esmf_fieldget, esmf_localarrayget, mapl_assert, mapl_fieldcopyattributes, mapl_gridget, mapl_return, mapl_verify
mapl_fieldcreater4 calls mapl_fieldcreater4, ESMF_GridGet, esmf_fieldemptycomplete, esmf_fieldget, mapl_assert, mapl_fieldcopyattributes, mapl_fieldcreateempty, mapl_return, mapl_verify
mapl_fieldcreaterename calls mapl_fieldcreaterename, ESMF_GridGet, esmf_fieldemptycomplete, esmf_fieldget, mapl_assert, mapl_fieldcopyattributes, mapl_fieldcreateempty, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldcopyattributes calls mapl_fieldcopyattributes
mapl_fieldcreateempty calls mapl_fieldcreateempty
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
create_bracketing_fields calls mapl_fieldcreate, createfilelevbracket
createfilelevbracket calls mapl_fieldcreate
createvariable calls mapl_fieldcreate
esmfl_bundlecpyfield calls mapl_fieldcreate
esmfl_stategetfield calls mapl_fieldcreate
initialize calls mapl_fieldcreate, mapl_statecreatefromspec
initialize_ calls mapl_fieldcreate, createfilelevbracket
mapl_gridcompgetfriendlies0 calls mapl_fieldcreate, mapl_gridcompgetfriendlies
mapl_statecreatefromspecnew calls mapl_fieldcreate
mapl_statevarreadncpar calls mapl_fieldcreate, mapl_varreadncpar
mapl_statevarwritencpar calls mapl_fieldcreate
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies3
mapl_varreadncpar calls mapl_statevarreadncpar
mapl_varwritencpar calls mapl_statevarwritencpar
createfilemetadata calls createvariable
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
run_ calls create_bracketing_fields
stateregrid calls esmfl_stategetfield
esmfl_regrid calls stateregrid
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_readforcingx calls mapl_statecreatefromvarspecnew