MAPL_AllocNodeArray_5DR8 – MAPL
MAPL_AllocNodeArray_5DR8 Interface
306 statements
Source File
interface
Calls
Called by
private module subroutine MAPL_AllocNodeArray_5DR8(Ptr, Shp, lbd, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), pointer :: Ptr(:,:,:,:,:)
integer, intent(in) :: Shp(5)
integer, intent(in), optional :: lbd(5)
integer, intent(out), optional :: rc
Call graph
mapl_allocnodearray_5dr8 calls mapl_allocnodearray_5dr8, mapl_return, mapl_verify, getsharedmemory, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
getsharedmemory calls getsharedmemory, mapl_return, mapl_assert, segsnew, mpi_barrier, shmget, segs, shmat
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_allocnodearray calls mapl_allocnodearray_5dr8
mapl_cfioreadbundle calls mapl_allocnodearray
initialize_subclass calls mapl_allocnodearray
mapl_allocateshared_1dl4 calls mapl_allocnodearray, mapl_allocateshared_1dl4
mapl_allocateshared_1dr8 calls mapl_allocnodearray, mapl_allocateshared_1dr8
mapl_allocateshared_1dr4 calls mapl_allocnodearray, mapl_allocateshared_1dr4
mapl_allocateshared_2dr4 calls mapl_allocnodearray, mapl_allocateshared_2dr4
mapl_allocateshared_1di4 calls mapl_allocnodearray, mapl_allocateshared_1di4
mapl_allocateshared_2dr8 calls mapl_allocnodearray, mapl_allocateshared_2dr8
mapl_tilemaskget calls mapl_allocnodearray
mapl_varread_r4_1d calls mapl_allocnodearray
mapl_varread_r4_2d calls mapl_allocnodearray
mapl_cfiowritebundlepost calls mapl_allocnodearray
readrestart calls mapl_tilemaskget
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r4_2d
mapl_statevarread calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
mapl_fieldread calls mapl_tilemaskget
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_fieldwrite calls mapl_tilemaskget
writerestart calls mapl_tilemaskget