MAPL_ArrayIGather – MAPL
MAPL_ArrayIGather Interface
3 statements
Source File
public interface MAPL_ArrayIGather
Calls
Called by
Contents
Module Procedures
MAPL_ArrayIGather_R4_2
Module Procedures
private subroutine MAPL_ArrayIGather_R4_2(local_array, request, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: local_array(:,:)
type(MAPL_CommRequest), intent(inout) :: request
integer, intent(out), optional :: rc
Call graph
mapl_arrayigather calls mapl_arrayigather_r4_2
mapl_arrayigather_r4_2 calls mpi_isend, mapl_return, mapl_verify, send
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_cfiowritebundlepost calls mapl_arrayigather
mapl_collectivegather3d calls mapl_arrayigather
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
regrid_scalar_3d_real32 calls mapl_collectivegather3d
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
test_main calls esmf_iowrite