MAPL_CommsAllGatherV – MAPL
MAPL_CommsAllGatherV Interface
5 statements
Source File
public interface MAPL_CommsAllGatherV
Calls
Called by
Contents
Module Procedures
MAPL_CommsAllGatherV_I4_1 MAPL_CommsAllGatherV_R4_1 MAPL_CommsAllGatherV_R8_1
Module Procedures
private subroutine MAPL_CommsAllGatherV_I4_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllGatherV_R4_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllGatherV_R8_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(out), optional :: RC
Call graph
mapl_commsallgatherv calls mapl_commsallgatherv_i4_1, mapl_commsallgatherv_r4_1, mapl_commsallgatherv_r8_1
mapl_commsallgatherv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_allgatherv, mapl_return, mapl_verify
mapl_commsallgatherv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_allgatherv, mapl_return, mapl_verify
mapl_commsallgatherv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_allgatherv, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
esmfl_fcollect_i4 calls mapl_commsallgatherv
esmfl_fcollect_r4 calls mapl_commsallgatherv
esmfl_fcollect_r8 calls mapl_commsallgatherv
mapl_tilemaskget calls mapl_commsallgatherv
esmfl_fcollect calls esmfl_fcollect_i4, esmfl_fcollect_r4, esmfl_fcollect_r8
mapl_bundlereadncpar calls mapl_tilemaskget, mapl_fieldreadncpar
mapl_bundlewritencpar calls mapl_tilemaskget, mapl_fieldwritencpar
mapl_fieldread calls mapl_tilemaskget
mapl_fieldreadncpar calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_fieldwritencpar calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget, mapl_fieldread
mapl_statevarwrite calls mapl_tilemaskget, mapl_fieldwrite
process_data_from_file calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget
mapl_varread calls mapl_fieldread, mapl_statevarread
mapl_varreadncpar calls mapl_bundlereadncpar
mapl_varwrite calls mapl_fieldwrite, mapl_statevarwrite
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_bundleread calls mapl_fieldread
mapl_bundlewrite calls mapl_fieldwrite
mapl_locstreamcreatexform calls esmfl_fcollect
mapl_locstreamtransformt2t calls esmfl_fcollect
mapl_statevarwritencpar calls mapl_bundlewritencpar