MAPL_VarSpecSet – MAPL
MAPL_VarSpecSet Interface
3 statements
Source File
public interface MAPL_VarSpecSet
Calls
Called by
Module Procedures
private subroutine MAPL_VarSpecSetNew(spec, short_name, long_name, units, dims, vlocation, field, bundle, state, stat, accmlt_interval, couple_interval, offset, label, friendlyto, field_type, staggering, rotation, grid, donotallocate, alwaysallocate, rc)
Arguments
Type Intent Optional Attributes Name
class(MAPL_VarSpecType), intent(inout) :: spec
character(len=*), intent(in), optional :: short_name
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: units
integer, intent(in), optional :: dims
integer, intent(in), optional :: vlocation
type(ESMF_Field), intent(in), optional :: field
type(ESMF_fieldbundle), intent(in), optional :: bundle
type(ESMF_State), intent(in), optional :: state
integer, intent(in), optional :: stat
integer, intent(in), optional :: accmlt_interval
integer, intent(in), optional :: couple_interval
integer, intent(in), optional :: offset
integer, intent(in), optional :: label
character(len=*), intent(in), optional :: friendlyto
integer, intent(in), optional :: field_type
integer, intent(in), optional :: staggering
integer, intent(in), optional :: rotation
type(ESMF_Grid), intent(in), optional :: grid
logical, intent(in), optional :: donotallocate
logical, intent(in), optional :: alwaysallocate
integer, intent(out), optional :: rc
Call graph
mapl_varspecset calls mapl_varspecsetnew
mapl_varspecsetnew calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_childaddattribtoimportspec calls mapl_varspecset
mapl_donotallocatevar calls mapl_varspecset
mapl_donotdeferexport calls mapl_varspecset
mapl_genericsetservices calls mapl_varspecset, mapl_genericspecenum, mapl_wirecomponent
mapl_genericspecenum calls mapl_varspecset, mapl_genericspecenum
mapl_stateaddexportspecfrmall calls mapl_varspecset
mapl_stateaddinternalspec calls mapl_varspecset
mapl_statecreatefromspecnew calls mapl_varspecset
mapl_statecreatefromvarspecnew calls mapl_varspecset, mapl_statecreatefromspecnew
mapl_statesetspecattrib calls mapl_varspecset
mapl_varspecreconnect calls mapl_varspecset
mapl_wirecomponent calls mapl_varspecset
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_donotallocateimport calls mapl_donotallocatevar
mapl_donotallocateinternal calls mapl_donotallocatevar
mapl_genericinitialize calls mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_readforcingx calls mapl_statecreatefromvarspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statesettimestamp calls mapl_statesetspecattrib
setservices calls mapl_genericsetservices