MAPL_GetLogger – MAPL
MAPL_GetLogger Interface
4 statements
Source File
public interface MAPL_GetLogger
Calls
Called by
Contents
Module Procedures
MAPL_GetLogger_gc MAPL_GetLogger_meta
Module Procedures
private subroutine MAPL_GetLogger_gc(gc, lgr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
class(Logger), pointer :: lgr
integer, intent(out), optional :: rc
private subroutine MAPL_GetLogger_meta(meta, lgr, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(in) :: meta
class(Logger), pointer :: lgr
integer, intent(out), optional :: rc
$ class(Logger), pointer :: meta_lgr $ $ meta_lgr => logging%get_logger(‘MAPL.GENERIC’) $ call meta_lgr%warning(‘obsolete interface MAPL_GetLogger()’)
Call graph
mapl_getlogger calls mapl_getlogger_gc, mapl_getlogger_meta
mapl_getlogger_gc calls mapl_getobjectfromgc, mapl_verify, mapl_return
mapl_getlogger_meta calls mapl_return
mapl_getobjectfromgc calls mapl_internalstateget
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_throw_exception calls initialize
warn_empty calls mapl_getlogger
initialize_ calls mapl_getlogger
perpetual_clock calls mapl_getlogger
mapl_clockinit calls mapl_getlogger
initialize_gc calls mapl_getlogger, perpetual_clock, mapl_clockinit
mapl_esmfstatewritetofile calls warn_empty
mapl_esmfstatereadfromfile calls warn_empty
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize calls mapl_genericfinalize
record_state calls mapl_genericstatesave
finalize_ calls mapl_genericfinalize
refresh_state calls mapl_genericstaterestore
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh