MAPL_VarSpecGet – MAPL
MAPL_VarSpecGet Interface
7 statements
Source File
public interface MAPL_VarSpecGet
Calls
Called by
Contents
Module Procedures
MAPL_VarSpecGetRegular MAPL_VarSpecGetNew MAPL_VarSpecGetFieldPtr MAPL_VarSpecGetBundlePtr MAPL_VarSpecGetStatePtr
Module Procedures
private subroutine MAPL_VarSpecGetRegular(SPEC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, FIELD, BUNDLE, STATE, NUM_SUBTILES, STAT, ACCMLT_INTERVAL, COUPLE_INTERVAL, OFFSET, LABEL, DEFAULT, defaultProvided, FRIENDLYTO, RESTART, HALOWIDTH, PRECISION, ATTR_RNAMES, ATTR_INAMES, ATTR_RVALUES, ATTR_IVALUES, UNGRIDDED_DIMS, UNGRIDDED_UNIT, UNGRIDDED_NAME, UNGRIDDED_COORDS, FIELD_TYPE, STAGGERING, ROTATION, GRID, doNotAllocate, alwaysAllocate, depends_on_children, depends_on, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
character(len=*), intent(out), optional :: SHORT_NAME
character(len=*), intent(out), optional :: LONG_NAME
character(len=*), intent(out), optional :: UNITS
integer, intent(out), optional :: DIMS
integer, intent(out), optional :: VLOCATION
type(ESMF_Field), intent(out), optional :: FIELD
type(ESMF_FieldBundle), intent(out), optional :: BUNDLE
type(ESMF_State), intent(out), optional :: STATE
integer, intent(out), optional :: NUM_SUBTILES
integer, intent(out), optional :: STAT
integer, intent(out), optional :: ACCMLT_INTERVAL
integer, intent(out), optional :: COUPLE_INTERVAL
integer, intent(out), optional :: OFFSET
integer, intent(out), optional :: LABEL
real, intent(out), optional :: DEFAULT
logical, intent(out), optional :: defaultProvided
character(len=*), intent(out), optional :: FRIENDLYTO
integer, intent(out), optional :: RESTART
integer, intent(out), optional :: HALOWIDTH
integer, intent(out), optional :: PRECISION
character(len=ESMF_MAXSTR), optional, pointer :: ATTR_RNAMES(:)
character(len=ESMF_MAXSTR), optional, pointer :: ATTR_INAMES(:)
real, optional, pointer :: ATTR_RVALUES(:)
integer, optional, pointer :: ATTR_IVALUES(:)
integer, optional, pointer :: UNGRIDDED_DIMS(:)
character(len=*), intent(out), optional :: UNGRIDDED_UNIT
character(len=*), intent(out), optional :: UNGRIDDED_NAME
real, optional, pointer :: UNGRIDDED_COORDS(:)
integer, optional :: FIELD_TYPE
integer, optional :: STAGGERING
integer, optional :: ROTATION
type(ESMF_Grid), intent(out), optional :: GRID
logical, intent(out), optional :: doNotAllocate
logical, intent(out), optional :: alwaysAllocate
logical, intent(out), optional :: depends_on_children
character(len=:), intent(out), optional, allocatable :: depends_on(:)
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecGetNew(SPEC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, FIELD, BUNDLE, STATE, NUM_SUBTILES, STAT, ACCMLT_INTERVAL, COUPLE_INTERVAL, OFFSET, LABEL, DEFAULT, defaultProvided, FRIENDLYTO, RESTART, HALOWIDTH, PRECISION, ATTR_RNAMES, ATTR_INAMES, ATTR_RVALUES, ATTR_IVALUES, UNGRIDDED_DIMS, UNGRIDDED_UNIT, UNGRIDDED_NAME, UNGRIDDED_COORDS, FIELD_TYPE, STAGGERING, ROTATION, GRID, doNotAllocate, alwaysAllocate, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpecType), intent(in) :: SPEC
character(len=*), intent(out), optional :: SHORT_NAME
character(len=*), intent(out), optional :: LONG_NAME
character(len=*), intent(out), optional :: UNITS
integer, intent(out), optional :: DIMS
integer, intent(out), optional :: VLOCATION
type(ESMF_Field), intent(out), optional :: FIELD
type(ESMF_FieldBundle), intent(out), optional :: BUNDLE
type(ESMF_State), intent(out), optional :: STATE
integer, intent(out), optional :: NUM_SUBTILES
integer, intent(out), optional :: STAT
integer, intent(out), optional :: ACCMLT_INTERVAL
integer, intent(out), optional :: COUPLE_INTERVAL
integer, intent(out), optional :: OFFSET
integer, intent(out), optional :: LABEL
real, intent(out), optional :: DEFAULT
logical, intent(out), optional :: defaultProvided
character(len=*), intent(out), optional :: FRIENDLYTO
integer, intent(out), optional :: RESTART
integer, intent(out), optional :: HALOWIDTH
integer, intent(out), optional :: PRECISION
character(len=ESMF_MAXSTR), optional, pointer :: ATTR_RNAMES(:)
character(len=ESMF_MAXSTR), optional, pointer :: ATTR_INAMES(:)
real, optional, pointer :: ATTR_RVALUES(:)
integer, optional, pointer :: ATTR_IVALUES(:)
integer, optional, pointer :: UNGRIDDED_DIMS(:)
character(len=*), intent(out), optional :: UNGRIDDED_UNIT
character(len=*), intent(out), optional :: UNGRIDDED_NAME
real, optional, pointer :: UNGRIDDED_COORDS(:)
integer, optional :: FIELD_TYPE
integer, optional :: STAGGERING
integer, optional :: ROTATION
type(ESMF_Grid), intent(out), optional :: GRID
logical, intent(out), optional :: doNotAllocate
logical, intent(out), optional :: alwaysAllocate
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecGetFieldPtr(SPEC, FIELDPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
type(ESMF_Field), pointer :: FIELDPTR
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecGetBundlePtr(SPEC, BUNDLEPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
type(ESMF_FieldBundle), pointer :: BUNDLEPTR
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecGetStatePtr(SPEC, STATEPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
type(ESMF_State), pointer :: STATEPTR
integer, intent(out), optional :: RC
Call graph
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
initialize calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_bundleinit calls mapl_varspecget
mapl_cplcompsetvarspecs calls mapl_varspecget
mapl_friendlyget calls mapl_varspecget
mapl_genericspecenum calls mapl_varspecget, mapl_genericspecenum
mapl_getnumsubtiles calls mapl_varspecget
mapl_labelget calls mapl_varspecget
mapl_setvarspecforcc calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_stateaddexportspecfrmall calls mapl_varspecget
mapl_stateaddexportspecfrmchld_all calls mapl_varspecget
mapl_stateaddinternalspec calls mapl_varspecget
mapl_statecreatefromspecnew calls mapl_varspecget
mapl_statecreatefromvarspecnew calls mapl_varspecget, mapl_statecreatefromspecnew
mapl_stategetspecattrib calls mapl_varspecget
mapl_terminateimportallbut calls mapl_varspecget
mapl_varspecreconnect calls mapl_varspecget
mapl_wirecomponent calls mapl_varspecget, mapl_cplcompsetvarspecs
readrestart calls mapl_varspecget
test_simple_constructor calls mapl_varspecget
writerestart calls mapl_varspecget
mapl_addexportspec calls mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld_all
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_terminateimport calls mapl_terminateimportallbut
mapl_genericinitialize calls mapl_getnumsubtiles
mapl_readforcingx calls mapl_getnumsubtiles, mapl_statecreatefromvarspecnew, mapl_stategetspecattrib
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_stategettimestamp calls mapl_stategetspecattrib