MAPL_GetResource – MAPL
MAPL_GetResource Interface
6 statements
Source File
public interface MAPL_GetResource
Calls
Called by
Contents
Module Procedures
MAPL_GetResourceFromConfig_scalar MAPL_GetResourceFromMAPL_scalar MAPL_GetResourceFromConfig_array MAPL_GetResourceFromMAPL_array
Module Procedures
private subroutine MAPL_GetResourceFromConfig_scalar(config, val, label, unusable, default, value_is_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
class(*), intent(inout) :: val
character(len=*), intent(in) :: label
class(KeywordEnforcer), intent(in), optional :: unusable
class(*), intent(in), optional :: default
logical, intent(out), optional :: value_is_set
integer, intent(out), optional :: rc
private subroutine MAPL_GetResourceFromMAPL_scalar(state, val, label, unusable, default, value_is_set, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: state
class(*), intent(inout) :: val
character(len=*), intent(in) :: label
class(KeywordEnforcer), intent(in), optional :: unusable
class(*), intent(in), optional :: default
logical, intent(out), optional :: value_is_set
integer, intent(out), optional :: rc
private subroutine MAPL_GetResourceFromConfig_array(config, vals, label, unusable, default, value_is_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
class(*), intent(inout) :: vals(:)
character(len=*), intent(in) :: label
class(KeywordEnforcer), intent(in), optional :: unusable
class(*), intent(in), optional :: default(:)
logical, intent(out), optional :: value_is_set
integer, intent(out), optional :: rc
private subroutine MAPL_GetResourceFromMAPL_array(state, vals, label, unusable, default, value_is_set, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: state
class(*), intent(inout) :: vals(:)
character(len=*), intent(in) :: label
class(KeywordEnforcer), intent(in), optional :: unusable
class(*), intent(in), optional :: default(:)
logical, intent(out), optional :: value_is_set
integer, intent(out), optional :: rc
Call graph
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar
mapl_getresourcefromconfig_array calls mapl_getresource_config_array, mapl_return, mapl_verify
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar, mapl_return, mapl_verify
mapl_getresourcefrommapl_array calls mapl_getresource_config_array, mapl_return, mapl_verify
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar, mapl_return, mapl_verify
mapl_getresource_config_array calls mapl_return, mapl_verify, ESMF_ConfigGetAttribute, array_format, mapl_assert, compare_all, get_actual_label, get_print_settings, make_string_character_array, print_resource, set_do_print
mapl_getresource_config_scalar calls mapl_return, mapl_verify, ESMF_ConfigGetAttribute, mapl_assert, get_actual_label, get_print_settings, make_string_character, print_resource, set_do_print
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
array_format calls array_format_simple, array_format_string
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_actual_label calls mapl_return, mapl_verify, ESMF_ConfigFindLabel, get_labels_with_prefix
get_error_message calls at
get_print_settings calls mapl_verify, ESMF_ConfigGetAttribute, mapl_am_i_root
mapl_throw_exception calls initialize
print_resource calls mapl_return
set_do_print calls vector_contains_str, push_back
arrdescrsetncpar calls mapl_getresource
capture calls mapl_getresource, mapl_esmfstatewritetofile
get_test_framework_resource calls mapl_getresource
initialize_gc calls mapl_getresource, mapl_clockinit
mapl_clockinit calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource, arrdescrsetncpar
mapl_esmfstatewritetofile calls mapl_getresource, arrdescrsetncpar
mapl_genericfinalize calls mapl_getresource, mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_getresource
mapl_genericrecord calls mapl_getresource, mapl_staterecord
mapl_genericrefresh calls mapl_getresource, mapl_genericrefresh, mapl_staterefresh
mapl_genericstaterestore calls mapl_getresource, mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_getresource, mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_genericwrapper calls mapl_getresource, record_component
mapl_staterecord calls mapl_getresource, mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_getresource, mapl_esmfstatereadfromfile
mapl_checkpointstate calls mapl_esmfstatewritetofile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
record_component calls capture, get_test_framework_resource
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore