MAPL_Reverse_Schmidt – MAPL
MAPL_Reverse_Schmidt Interface
378 statements
Source File
interface
Calls
Called by
public module subroutine MAPL_Reverse_Schmidt(Grid, stretched, npts, lon, lat, lonR8, latR8, lonRe, latRe, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: Grid
logical, intent(out) :: stretched
integer, intent(in) :: npts
real, intent(in), optional :: lon(npts)
real, intent(in), optional :: lat(npts)
real(kind=ESMF_KIND_R8), intent(in), optional :: lonR8(npts)
real(kind=ESMF_KIND_R8), intent(in), optional :: latR8(npts)
real(kind=ESMF_KIND_R8), intent(out), optional :: lonRe(npts)
real(kind=ESMF_KIND_R8), intent(out), optional :: latRe(npts)
integer, intent(out), optional :: rc
Call graph
mapl_reverse_schmidt calls mapl_reverse_schmidt, ESMF_AttributeGet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_getglobalhorzijindex calls mapl_reverse_schmidt, mapl_getglobalhorzijindex
mapl_gethorzijindex calls mapl_getglobalhorzijindex, mapl_gethorzijindex