MAPL_Am_I_Root – MAPL
MAPL_Am_I_Root Interface
4 statements
Source File
public interface MAPL_Am_I_Root
Calls
Called by
BinIOMod::GETFILE w MAPL_CommsMod::MAPL_Am_I_Root
w
BinIOMod::MAPL_Backspace w
w
BinIOMod::MAPL_FieldRead w
w
BinIOMod::MAPL_OPEN w
w
BinIOMod::MAPL_Rewind w
w
BinIOMod::MAPL_Skip w
w
BinIOMod::MAPL_VarRead_R4_1d w
w
BinIOMod::MAPL_VarRead_R4_2d w
w
BinIOMod::MAPL_VarRead_R8_1d w
w
BinIOMod::MAPL_VarRead_R8_2d w
w
BinIOMod::MAPL_VarWrite_I4_1d w
w
BinIOMod::MAPL_VarWrite_R4_1d w
w
BinIOMod::MAPL_VarWrite_R4_2d w
w
BinIOMod::MAPL_VarWrite_R8_1d w
w
BinIOMod::MAPL_VarWrite_R8_2d w
w
BinIOMod::READ_PARALLEL_I4_0 w
w
BinIOMod::READ_PARALLEL_I4_1 w
w
BinIOMod::READ_PARALLEL_I4_2 w
w
BinIOMod::READ_PARALLEL_R4_0 w
w
BinIOMod::READ_PARALLEL_R4_1 w
w
BinIOMod::READ_PARALLEL_R4_2 w
w
BinIOMod::READ_PARALLEL_R8_0 w
w
BinIOMod::READ_PARALLEL_R8_1 w
w
BinIOMod::READ_PARALLEL_R8_2 w
w
BinIOMod::READ_PARALLEL_STRING_0 w
w
ESMFL_MOD::Add2Bundle w
w
ESMFL_MOD::Bundle2State w
w
ESMFL_MOD::BundleDiff w
w
ESMFL_MOD::Bundles2Bundle w
w
ESMFL_MOD::MAPL_AreaMean_2d_r8_bitrep w
w
ESMFL_MOD::State2Bundle w
w
ESMFL_MOD::StateDiff w
w
ExtData_DriverGridCompMod::initialize_gc w
w
ExtData_DriverGridCompMod::run_MultipleTimes w
w
ExtDataDriverMod::ExtDataDriver%run w
w
FileIOSharedMod::MAPL_TileMaskGet w
w
FileIOSharedMod::WRITE_PARALLEL_I4_0 w
w
FileIOSharedMod::WRITE_PARALLEL_I4_1 w
w
FileIOSharedMod::WRITE_PARALLEL_R4_0 w
w
FileIOSharedMod::WRITE_PARALLEL_R4_1 w
w
FileIOSharedMod::WRITE_PARALLEL_R8_0 w
w
FileIOSharedMod::WRITE_PARALLEL_R8_1 w
w
FileIOSharedMod::WRITE_PARALLEL_STRING_0 w
w
HistoryTrajectory_implement::append_file w
w
HistoryTrajectory_implement::close_file_handle w
w
HistoryTrajectory_implement::create_file_handle w
w
HistoryTrajectory_implement::create_grid w
w
HistoryTrajectory_implement::destroy_rh_regen_LS w
w
HistoryTrajectory_implement::HistoryTrajectory_from_config w
w
HistoryTrajectory_implement::initialize_ w
w
MAPL_CapGridCompMod::CAP_FINALIZE w
w
MAPL_CapGridCompMod::initialize_gc w
w
MAPL_CapGridCompMod::MAPL_CapGridComp%step w
w
MAPL_CFIOMod::MAPL_CFIOCreateFromBundle w
w
MAPL_CFIOMod::MAPL_CFIOReadArray2D w
w
MAPL_CFIOMod::MAPL_CFIOReadArray3D w
w
MAPL_CFIOMod::MAPL_CFIOReadBundle w
w
MAPL_CFIOMod::MAPL_CFIOReadBundleRead w
w
MAPL_CFIOMod::MAPL_CFIOReadParallel_ w
w
MAPL_CubedSphereGridFactoryMod::CubedSphereGridFactory%initialize_from_config_with_prefix w
w
MAPL_GenericCplCompMod::ReadRestart w
w
MAPL_GenericCplCompMod::WriteRestart w
w
MAPL_GenericMod::MAPL_ESMFStateReadFromFile w
w
MAPL_GenericMod::MAPL_GenericFinalize w
w
MAPL_GenericMod::MAPL_GenericInitialize w
w
MAPL_GenericMod::MAPL_ReadForcingX w
w
MAPL_GenericMod::warn_empty w
w
MAPL_HistoryGridCompMod::Get_Tdim w
w
MAPL_HistoryGridCompMod::Initialize w
w
MAPL_HistoryGridCompMod::MAPL_GradsCtlWrite w
w
MAPL_HistoryGridCompMod::Run w
w
MAPL_LatLonGridFactoryMod::LatLonGridFactory%initialize_from_config_with_prefix w
w
MAPL_LocStreamMod::MAPL_LocStreamCreateFromFile w
w
MAPL_MaxMinMod::pmaxmin2d_r4 w
w
MAPL_OrbGridCompMod::SetServices w
w
MAPL_ResourceMod::get_print_settings w
w
MAPL_SimpleBundleMod::MAPL_SimpleBundlePrint w
w
MAPL_SwathGridFactoryMod::SwathGridFactory%add_horz_coordinates_from_file w
w
MAPL_SwathGridFactoryMod::SwathGridFactory%get_obs_time w
w
MAPL_SwathGridFactoryMod::SwathGridFactory%initialize_from_config_with_prefix w
w
MAPL_TileIOMod::MAPL_TileIO%request_data_from_file w
w
MAPL_XYGridFactoryMod::XYGridFactory%add_horz_coordinates_from_ABIfile w
w
MAPL_XYGridFactoryMod::XYGridFactory%file_has_corners w
w
MAPL_XYGridFactoryMod::XYGridFactory%initialize_from_config_with_prefix w
w
NCIOMod::MAPL_FieldWriteNCPar w
w
NCIOMod::MAPL_StateVarReadNCPar w
w
NCIOMod::MAPL_VarReadNCpar_R4_1d w
w
NCIOMod::MAPL_VarReadNCpar_R8_1d w
w
Regrid_Util::generate_report w
w
Regrid_Util::main w
w
regrid_util_support_mod::regrid_support%process_command_line w
w
RUTMod::SetServices w
w
StationSamplerMod::StationSampler%append_file w
w
StationSamplerMod::StationSampler%close_file_handle w
w
StationSamplerMod::StationSampler%create_file_handle w
w
Test_CFIO_Bundle::test_main w
w
time_ave::generate_report w
w
utCFIO::MyGridCreate_ w
w
utCFIO::MyGridCreate_ w
w
utCFIO::test_main w
w
utCFIO::test_main w
w
utCFIO::test_main w
w
Module Procedures
private function MAPL_Am_I_Root_Layout(layout) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
Return Value logical
private function MAPL_Am_I_Root_Vm(VM) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), optional :: VM
Return Value logical
Call graph
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_am_i_rank_layout calls mapl_am_i_rank, ESMF_DELayoutGet
mapl_am_i_rank_only calls mapl_am_i_rank, ESMF_VMGetCurrent
mapl_am_i_rank_vm calls ESMF_VMGet