MAPL_SunGetInsolation – MAPL
MAPL_SunGetInsolation Interface
5 statements
Source File
public interface MAPL_SunGetInsolation
Calls
Called by
Module Procedures
private recursive subroutine SOLAR_1D(LONS, LATS, ORBIT, ZTH, SLR, INTV, CLOCK, TIME, currTime, DIST, ZTHB, ZTHD, ZTH1, ZTHN, ZTHP, STEPSIZE, RC)
GEOS_SunGetInsolation returns the cosine of the solar zenith angle and the insolation at the top of the atmosphere for the given reference time, latitudes, longitudes, and orbit. It is overloaded to accept either 1d or 2d FORTRAN arrays or ESMF arrays of lats and lons and to produce the corresponding outputs.
Read more…
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: LONS(:)
real, intent(in) :: LATS(:)
type(MAPL_SunOrbit), intent(in) :: ORBIT
real, intent(out) :: ZTH(:)
real, intent(out) :: SLR(:)
type(ESMF_TimeInterval), intent(inout), optional :: INTV
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(in), optional :: TIME
type(ESMF_Time), intent(in), optional :: currTime
real, intent(out), optional :: DIST
real, intent(out), optional :: ZTHB(:)
real, intent(out), optional :: ZTHD(:)
real, intent(out), optional :: ZTH1(:)
real, intent(out), optional :: ZTHN(:)
real, intent(out), optional :: ZTHP(:)
real, intent(in), optional :: STEPSIZE
integer, intent(out), optional :: RC
private recursive subroutine SOLAR_2D(LONS, LATS, ORBIT, ZTH, SLR, INTV, CLOCK, TIME, currTime, DIST, ZTHB, ZTHD, ZTH1, ZTHN, ZTHP, STEPSIZE, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: LONS(:,:)
real, intent(in) :: LATS(:,:)
type(MAPL_SunOrbit), intent(in) :: ORBIT
real, intent(out) :: ZTH(:,:)
real, intent(out) :: SLR(:,:)
type(ESMF_TimeInterval), intent(inout), optional :: INTV
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(in), optional :: TIME
type(ESMF_Time), intent(in), optional :: currTime
real, intent(out), optional :: DIST
real, intent(out), optional :: ZTHB(:,:)
real, intent(out), optional :: ZTHD(:,:)
real, intent(out), optional :: ZTH1(:,:)
real, intent(out), optional :: ZTHN(:,:)
real, intent(out), optional :: ZTHP(:,:)
real, intent(in), optional :: STEPSIZE
integer, intent(out), optional :: RC
private subroutine SOLAR_ARR_INT(LONS, LATS, ORBIT, ZTH, SLR, INTV, CLOCK, TIME, currTime, DIST, ZTHB, ZTHD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Array), intent(in) :: LONS
type(ESMF_Array), intent(in) :: LATS
type(MAPL_SunOrbit), intent(in) :: ORBIT
type(ESMF_Array), intent(out) :: ZTH
type(ESMF_Array), intent(out) :: SLR
type(ESMF_TimeInterval), intent(inout), optional :: INTV
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(in), optional :: TIME
type(ESMF_Time), intent(in), optional :: currTime
real, intent(out), optional :: DIST
type(ESMF_Array), intent(out), optional :: ZTHB
type(ESMF_Array), intent(out), optional :: ZTHD
integer, intent(out), optional :: RC
$ character(len=ESMF_MAXSTR) :: IAm = “SunGetInsolationArr”
Call graph
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
solar_1d calls mapl_sungetinsolation, ESMF_ClockAdvance, ESMF_ClockCreate, ESMF_ClockDestroy, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeIntervalGet, mapl_assert, write_parallel, calcradfromta, calctafromea, getiday, invert_keplers_newton, mapl_return, mapl_sunorbitcreated, mapl_verify, rect_pmpi
solar_2d calls mapl_sungetinsolation, ESMF_ClockAdvance, ESMF_ClockCreate, ESMF_ClockDestroy, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeIntervalGet, mapl_assert, write_parallel, calcradfromta, calctafromea, getiday, invert_keplers_newton, mapl_return, mapl_sunorbitcreated, mapl_verify, rect_pmpi
solar_arr_int calls mapl_sungetinsolation, esmf_arrayget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
write_parallel calls write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r4_1, write_parallel_r8_0, write_parallel_r8_1, write_parallel_string_0
getiday calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_sunorbitcreated calls mapl_return
mapl_verify calls mapl_throw_exception