MAPL_CFIOWrite – MAPL
MAPL_CFIOWrite Interface
4 statements
Source File
public interface MAPL_CFIOWrite
Calls
Called by
Module Procedures
private subroutine MAPL_CFIOWriteState(MCFIO, CLOCK, STATE, VERBOSE, NBITS, RC)
The subroutine MAPL_CFIOWriteState serializes an ESMF state into a Bundle and writes it to a file. Only the MAPL_CFIO object is a required argument as pointers to the actual data to be written is recorded in it during creation.
Read more…
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
type(ESMF_Clock), intent(inout) :: CLOCK
type(ESMF_State), intent(inout) :: STATE
logical, intent(in), optional :: VERBOSE
integer, intent(in), optional :: NBITS
integer, intent(out), optional :: RC
private subroutine MAPL_CFIOWriteBundle(MCFIO, CLOCK, BUNDLE, VERBOSE, NBITS, created, RC)
The subroutine MAPL_CFIOWriteBundle writes an ESMF Bundle to a File. Only the MAPL_CFIO object is a required argument as pointers to the actual data to be written is recorded in it during creation.
Read more…
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
type(ESMF_Clock), intent(inout), optional :: CLOCK
type(ESMF_FIELDBUNDLE), intent(inout), optional :: BUNDLE
logical, intent(in), optional :: VERBOSE
integer, intent(in), optional :: NBITS
logical, intent(in), optional :: created
integer, intent(out), optional :: RC
Call graph
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowritebundle calls mapl_assert, mapl_cfiocreatewrite, mapl_cfioset, mapl_cfiowritebundlepost, mapl_cfiowritebundlewait, mapl_cfiowritebundlewrite, mapl_return, mapl_verify
mapl_cfiowritestate calls mapl_cfiowritebundle, esmf_fieldbundlecreate, esmf_fieldbundledestroy, esmfl_bundleaddstate, mapl_return, mapl_verify
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2