MAPL_CopyFriendliness – MAPL
MAPL_CopyFriendliness Interface
4 statements
Source File
public interface MAPL_CopyFriendliness
Calls
Contents
Module Procedures
MAPL_CopyFriendlinessInField MAPL_CopyFriendlinessInState
Module Procedures
private subroutine MAPL_CopyFriendlinessInField(FIELDOUT, FIELDIN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELDOUT
type(ESMF_Field), intent(inout) :: FIELDIN
integer, intent(out), optional :: rc
private subroutine MAPL_CopyFriendlinessInState(STATEOUT, nameOUT, STATEIN, nameIN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATEOUT
character(len=*), intent(in) :: nameOUT
type(ESMF_State), intent(in) :: STATEIN
character(len=*), intent(in) :: nameIN
integer, intent(out), optional :: rc
Call graph
mapl_copyfriendliness calls mapl_copyfriendlinessinfield, mapl_copyfriendlinessinstate
mapl_copyfriendlinessinfield calls ESMF_AttributeGet, ESMF_AttributeSet, mapl_return, mapl_verify
mapl_copyfriendlinessinstate calls mapl_copyfriendlinessinfield, esmf_stateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize