MAPL_SimpleBundleWrite – MAPL
MAPL_SimpleBundleWrite Interface
4 statements
Source File
public interface MAPL_SimpleBundleWrite
Calls
Module Procedures
private subroutine MAPL_SimpleBundleWrite1(self, filename, Clock, verbose, rc)
Writes a MAPL SimpleBundle to file fiven an ESMF Clock object. The file opened, written to, and closed.
Arguments
Type Intent Optional Attributes Name
type(MAPL_SimpleBundle) :: self
character(len=*), intent(in) :: filename
type(ESMF_Clock), intent(inout) :: Clock
logical, intent(in), optional :: verbose
integer, intent(out), optional :: rc
private subroutine MAPL_SimpleBundleWrite2(self, filename, time, verbose, rc)
Writes a MAPL SimpleBundle to file fiven an ESMF Time object. The file opened, written to, and closed. A fake timestep of 30 minutes is assumed.
Arguments
Type Intent Optional Attributes Name
type(MAPL_SimpleBundle) :: self
character(len=*), intent(in) :: filename
type(ESMF_Time), intent(in) :: time
logical, intent(in), optional :: verbose
integer, intent(out), optional :: rc
Call graph
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
mapl_simplebundlewrite1 calls mapl_cfiocreate, mapl_cfiowrite, mapl_cfiodestroy, mapl_return, mapl_verify
mapl_simplebundlewrite2 calls ESMF_ClockCreate, ESMF_TimeIntervalSet, mapl_cfiocreate, mapl_cfiowrite, mapl_cfiodestroy, mapl_return, mapl_verify
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiodestroy calls mapl_return, mapl_verify, esmf_cfiodestroy, esmf_cfiofileclose
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception