MAPL_VarSpecDestroy – MAPL
MAPL_VarSpecDestroy Interface
4 statements
Source File
public interface MAPL_VarSpecDestroy
Calls
Called by
Contents
Module Procedures
MAPL_VarSpecDestroy0 MAPL_VarSpecDestroy1
Module Procedures
private subroutine MAPL_VarSpecDestroy0(SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecDestroy1(SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
integer, intent(out), optional :: RC
Call graph
mapl_varspecdestroy calls mapl_varspecdestroy0, mapl_varspecdestroy1
mapl_varspecdestroy0 calls mapl_return
mapl_varspecdestroy1 calls mapl_varspecdestroy0, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_genericstatedestroy calls mapl_varspecdestroy
mapl_genericfinalize calls mapl_genericstatedestroy
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize