MAPL_AllocateShared_1DL4 – MAPL
MAPL_AllocateShared_1DL4 Interface
306 statements
Source File
interface
Calls
Called by
private module subroutine MAPL_AllocateShared_1DL4(Ptr, Shp, lbd, TransRoot, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), pointer :: Ptr(:)
integer, intent(in) :: Shp(1)
integer, intent(in), optional :: lbd(1)
logical, intent(in) :: TransRoot
integer, intent(out), optional :: rc
Call graph
mapl_allocateshared_1dl4 calls mapl_allocateshared_1dl4, mapl_allocnodearray, mapl_return, mapl_verify
mapl_allocnodearray calls mapl_allocnodearray_1di4, mapl_allocnodearray_1dl4, mapl_allocnodearray_1dr4, mapl_allocnodearray_1dr8, mapl_allocnodearray_2di4, mapl_allocnodearray_2dr4, mapl_allocnodearray_2dr8, mapl_allocnodearray_3di4, mapl_allocnodearray_3dr4, mapl_allocnodearray_3dr8, mapl_allocnodearray_4di4, mapl_allocnodearray_4dr4, mapl_allocnodearray_4dr8, mapl_allocnodearray_5dr8, mapl_allocnodearray_6dr8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_allocateshared calls mapl_allocateshared_1dl4
add_horz_coordinates_from_file calls mapl_allocateshared
mapl_cfiocreatefrombundle calls mapl_allocateshared
mapl_locstreamcreatefromfile calls mapl_allocateshared
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
make_new_grid calls add_horz_coordinates_from_file
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
initialize calls mapl_locstreamcreate
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate