MAPL_TerminateImport – MAPL
MAPL_TerminateImport Interface
7 statements
Source File
public interface MAPL_TerminateImport
Calls
Called by
Contents
Module Procedures
MAPL_DoNotConnect MAPL_DoNotConnectMany MAPL_DoNotConnectAnyImport MAPL_TerminateImportAllBut MAPL_TerminateImportAll
Module Procedures
private subroutine MAPL_DoNotConnect(GC, SHORT_NAME, CHILD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: CHILD
integer, intent(out), optional :: RC
private subroutine MAPL_DoNotConnectMany(GC, SHORT_NAME, CHILD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME(:)
integer, intent(in) :: CHILD
integer, intent(out), optional :: RC
private subroutine MAPL_DoNotConnectAnyImport(GC, CHILD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(in) :: CHILD
integer, intent(out), optional :: RC
private subroutine MAPL_TerminateImportAllBut(GC, SHORT_NAMES, CHILD_IDS, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAMES(:)
integer, intent(in) :: CHILD_IDS(:)
integer, intent(out), optional :: RC
private subroutine MAPL_TerminateImportAll(GC, ALL, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
logical, intent(in) :: ALL
integer, intent(out), optional :: RC
Call graph
mapl_terminateimport calls mapl_donotconnect, mapl_terminateimportall, mapl_donotconnectmany, mapl_terminateimportallbut, mapl_donotconnectanyimport
mapl_donotconnect calls mapl_connectivityget, mapl_verify, mapl_return
mapl_terminateimportall calls mapl_terminateimport, mapl_verify, mapl_getobjectfromgc, mapl_return
mapl_donotconnectmany calls mapl_donotconnect, mapl_verify, mapl_return
mapl_terminateimportallbut calls mapl_donotconnect, mapl_connectivityget, mapl_verify, mapl_getobjectfromgc, mapl_assert, mapl_return, mapl_varspecget
mapl_donotconnectanyimport calls mapl_donotconnect, mapl_verify, mapl_return
mapl_connectivityget calls mapl_verify, mapl_getobjectfromgc, mapl_return
mapl_verify calls mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_return calls mapl_throw_exception, get_error_message
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetstateptr, mapl_varspecgetfieldptr, mapl_varspecgetbundleptr, mapl_varspecgetnew
mapl_throw_exception calls initialize
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetnew calls mapl_return