MAPL_GetNodeInfo – MAPL
MAPL_GetNodeInfo Interface
306 statements
Source File
interface
Calls
Called by
public module subroutine MAPL_GetNodeInfo(comm, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(out), optional :: rc
Call graph
mapl_getnodeinfo calls mapl_getnodeinfo, getnodecomm, mapl_verify, getnoderootscomm, mapl_return
getnodecomm calls getnodecomm, mapl_verify, mapl_return, mpi_get_processor_name, mapl_assert, mpi_allgather, mpi_comm_size, mpi_comm_rank, mpi_comm_split, mapl_sort, mapl_noderanklist, mpi_allreduce
mapl_verify calls mapl_throw_exception
getnoderootscomm calls getnoderootscomm, mapl_return, mapl_assert, mpi_comm_size, mpi_comm_rank, mpi_comm_split
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_corespernodeget calls mapl_getnodeinfo, mapl_corespernodeget
mapl_shmemamonfirstnode calls mapl_getnodeinfo, mapl_shmemamonfirstnode
main calls mapl_getnodeinfo
initialize_gc calls mapl_getnodeinfo, mapl_corespernodeget
ut_regridding calls mapl_getnodeinfo
regrid_util calls main
mapl_cfioreadbundle calls mapl_corespernodeget, mapl_shmemamonfirstnode
mapl_collectivegather3d calls mapl_corespernodeget
mapl_cfiocreatefrombundle calls mapl_corespernodeget
mapl_cfioreadstate calls mapl_cfioreadbundle
regrid_scalar_3d_real32 calls mapl_collectivegather3d
mapl_cfioreadfield calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
esmf_iocreate calls mapl_cfiocreatefrombundle