MAPL_GetObjectFromGC – MAPL
MAPL_GetObjectFromGC Interface
3 statements
Source File
public interface MAPL_GetObjectFromGC
Calls
Called by
Module Procedures
private subroutine MAPL_InternalStateGet(GC, MAPLOBJ, RC)
This is the recommended way of getting the opaque MAPL Generic state object from the gridded component (GC). It can be called at any time after MAPL_GenericSetServices has been called on GC. Note that you get a pointer to the object.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_MetaComp), pointer :: MAPLOBJ
integer, intent(out), optional :: RC
Call graph
mapl_getobjectfromgc calls mapl_internalstateget
mapl_internalstateget calls ESMF_GridCompGet, ESMF_UserCompGetInternalState, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
finalize_gc calls mapl_getobjectfromgc
finalize calls mapl_getobjectfromgc
initialize_ calls mapl_getobjectfromgc
initialize_gc calls mapl_getobjectfromgc
initialize calls mapl_getobjectfromgc
mapl_addattributetofields_i4 calls mapl_getobjectfromgc
mapl_connectivityget calls mapl_getobjectfromgc
mapl_disablerecord calls mapl_getobjectfromgc
mapl_donotallocateimport calls mapl_getobjectfromgc
mapl_donotallocateinternal calls mapl_getobjectfromgc
mapl_genericfinalize calls mapl_getobjectfromgc
mapl_genericinitialize calls mapl_getobjectfromgc
mapl_genericrunchildren calls mapl_getobjectfromgc
mapl_getallexchangegrids calls mapl_getobjectfromgc
mapl_getlogger_gc calls mapl_getobjectfromgc
mapl_getrootgc calls mapl_getobjectfromgc
mapl_setstatesave calls mapl_getobjectfromgc
mapl_terminateimportall calls mapl_getobjectfromgc
mapl_terminateimportallbut calls mapl_getobjectfromgc
omp_driver calls mapl_getobjectfromgc
record_state calls mapl_getobjectfromgc
run_ calls mapl_getobjectfromgc
run_mapl_gridcomp calls mapl_getobjectfromgc
run calls mapl_getobjectfromgc