MAPL_AllocateShared – MAPL
MAPL_AllocateShared Interface
8 statements
Source File
public interface MAPL_AllocateShared
Calls
Called by
Contents
Module Procedures
MAPL_AllocateShared_1DL4 MAPL_AllocateShared_1DI4 MAPL_AllocateShared_1DR4 MAPL_AllocateShared_1DR8 MAPL_AllocateShared_2DR4 MAPL_AllocateShared_2DR8
Module Procedures
private interface MAPL_AllocateShared_1DL4()
Arguments
None
private interface MAPL_AllocateShared_1DI4()
Arguments
None
private interface MAPL_AllocateShared_1DR4()
Arguments
None
private interface MAPL_AllocateShared_1DR8()
Arguments
None
private interface MAPL_AllocateShared_2DR4()
Arguments
None
private interface MAPL_AllocateShared_2DR8()
Arguments
None
Call graph
mapl_allocateshared calls mapl_allocateshared_1di4, mapl_allocateshared_1dl4, mapl_allocateshared_1dr4, mapl_allocateshared_1dr8, mapl_allocateshared_2dr4, mapl_allocateshared_2dr8
mapl_allocateshared_1di4 calls mapl_allocateshared_1di4, mapl_allocnodearray, mapl_return, mapl_verify
mapl_allocateshared_1dl4 calls mapl_allocateshared_1dl4, mapl_allocnodearray, mapl_return, mapl_verify
mapl_allocateshared_1dr4 calls mapl_allocateshared_1dr4, mapl_allocnodearray, mapl_return, mapl_verify
mapl_allocateshared_1dr8 calls mapl_allocateshared_1dr8, mapl_allocnodearray, mapl_return, mapl_verify
mapl_allocateshared_2dr4 calls mapl_allocateshared_2dr4, mapl_allocnodearray, mapl_return, mapl_verify
mapl_allocateshared_2dr8 calls mapl_allocateshared_2dr8, mapl_allocnodearray, mapl_return, mapl_verify
add_horz_coordinates_from_file calls mapl_allocateshared
mapl_cfiocreatefrombundle calls mapl_allocateshared
mapl_locstreamcreatefromfile calls mapl_allocateshared
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
make_new_grid calls add_horz_coordinates_from_file
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
initialize calls mapl_locstreamcreate
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main