MAPL_AddInternalSpec – MAPL
MAPL_AddInternalSpec Interface
3 statements
Source File
public interface MAPL_AddInternalSpec
Calls
Called by
Contents
Module Procedures
MAPL_StateAddInternalSpec
Module Procedures
private subroutine MAPL_StateAddInternalSpec(GC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, DATATYPE, NUM_SUBTILES, REFRESH_INTERVAL, AVERAGING_INTERVAL, DEFAULT, RESTART, HALOWIDTH, PRECISION, FRIENDLYTO, ADD2EXPORT, ATTR_RNAMES, ATTR_INAMES, ATTR_RVALUES, ATTR_IVALUES, UNGRIDDED_DIMS, FIELD_TYPE, STAGGERING, ROTATION, RC)
MAPL_StateAddInternalSpec — Sets specifications for an item in the INTERNAL state.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: LONG_NAME
character(len=*), intent(in), optional :: UNITS
integer, intent(in), optional :: DIMS
integer, intent(in), optional :: VLOCATION
integer, intent(in), optional :: DATATYPE
integer, intent(in), optional :: NUM_SUBTILES
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
real, intent(in), optional :: DEFAULT
integer, intent(in), optional :: RESTART
character(len=*), intent(in), optional :: HALOWIDTH
integer, intent(in), optional :: PRECISION
character(len=*), intent(in), optional :: FRIENDLYTO
logical, intent(in), optional :: ADD2EXPORT
character(len=*), intent(in), optional :: ATTR_RNAMES(:)
character(len=*), intent(in), optional :: ATTR_INAMES(:)
real, intent(in), optional :: ATTR_RVALUES(:)
integer, intent(in), optional :: ATTR_IVALUES(:)
integer, intent(in), optional :: UNGRIDDED_DIMS(:)
integer, intent(in), optional :: FIELD_TYPE
integer, intent(in), optional :: STAGGERING
integer, intent(in), optional :: ROTATION
integer, intent(out), optional :: RC
Call graph
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_stateaddinternalspec calls ESMF_ConfigGetAttribute, mapl_varspecaddreftolist, mapl_varspecget, mapl_varspecgetindex, mapl_varspecset, mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecset calls mapl_varspecsetnew
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspeccreateinlistnew calls mapl_return, mapl_verify, mapl_assert, update_legacy
mapl_verify calls mapl_throw_exception
setservices calls mapl_addinternalspec