MAPL_FlapCLI – MAPL
MAPL_FlapCLI Interface
4 statements
Source File
public interface MAPL_FlapCLI
Calls
Contents
Module Procedures
new_CapOptions_from_flap new_CapOptions_from_flap_back_comp
Module Procedures
private function new_CapOptions_from_flap(unusable, description, authors, dummy, extra, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: description
character(len=*), intent(in) :: authors
character(len=*), intent(in) :: dummy
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
private function new_CapOptions_from_flap_back_comp(unusable, description, authors, extra, rc) result(flapcap)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: description
character(len=*), intent(in) :: authors
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_FlapCLI)
Call graph
mapl_flapcli calls new_capoptions_from_flap, new_capoptions_from_flap_back_comp
new_capoptions_from_flap calls add_command_line_options, fill_cap_options, mapl_return, mapl_verify
new_capoptions_from_flap_back_comp calls add_command_line_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, mapl_verify, add
fill_cap_options calls mapl_return, mapl_verify, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize