MAPL_DeAlloc – MAPL
MAPL_DeAlloc Interface
3 statements
Source File
public interface MAPL_DeAlloc
Calls
Contents
Module Procedures
MAPL_DeAlloc_R_2D
Module Procedures
private subroutine MAPL_DeAlloc_R_2D(A, RC)
Arguments
Type Intent Optional Attributes Name
real, pointer :: A(:,:)
integer, intent(out), optional :: RC
Call graph
mapl_dealloc calls mapl_dealloc_r_2d
mapl_dealloc_r_2d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message