MAPL_Cap – MAPL
MAPL_Cap Interface
4 statements
Source File
public interface MAPL_Cap
Calls
Contents
Module Procedures
new_MAPL_Cap_from_set_services new_MAPL_Cap_from_dso
Module Procedures
private function new_MAPL_Cap_from_set_services(name, set_services, unusable, cap_options, rc) result(cap)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: name
procedure :: set_services
class(KeywordEnforcer), intent(in), optional :: unusable
type(MAPL_CapOptions), intent(in), optional :: cap_options
integer, intent(out), optional :: rc
Return Value type(MAPL_Cap)
private function new_MAPL_Cap_from_dso(name, unusable, cap_options, rc) result(cap)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: name
class(KeywordEnforcer), intent(in), optional :: unusable
type(MAPL_CapOptions), intent(in), optional :: cap_options
integer, intent(out), optional :: rc
Return Value type(MAPL_Cap)
Call graph
mapl_cap calls new_mapl_cap_from_set_services, new_mapl_cap_from_dso
new_mapl_cap_from_set_services calls mapl_verify, mapl_initialize, mapl_return
new_mapl_cap_from_dso calls mapl_verify, mapl_initialize, mapl_return
mapl_verify calls mapl_throw_exception
mapl_initialize calls mapl_verify, mapl_return, start_global_time_profiler, initialize_pflogger, initialize_profiler
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
start_global_time_profiler calls mapl_verify, mapl_return, get_global_time_profiler
initialize_pflogger calls mapl_verify, mapl_return, filehandler, mpiformatter, initialize, streamhandler, mpi_comm_rank, mpilock