MAPL_BalanceWork – MAPL
MAPL_BalanceWork Interface
4 statements
Source File
public interface MAPL_BalanceWork
Calls
Contents
Module Procedures
MAPL_BalanceWork4 MAPL_BalanceWork8
Module Procedures
private subroutine MAPL_BalanceWork4(A, Idim, Direction, Handle, rc)
Depending on the argument “Direction”, this performs the actual distribution of work or the gathering of results for a given strategy. The strategy has to have been predefined by a call to MAPL_BalanceCreate. A strategy “Handle” obtained from that call can be optionally used to specify the strategy. Otherwise, a default strategy is assumed (see MAPL_BalanceCreate for details). Work (Results) is distributed (retrieved) using the buffer A, which is assumed to consist of Jdim contiguous blocks of size Idim. Of course, Jdim can be 1. The blocksize of A (Idim) must be at least as large as the BufLen associated with the strategy. This size can be obtained by quering the strategy using its handle or be saving it from the MAPL_BalanceCreate call. Again, see MAPL_BalanceCreate for details.
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: A(:)
integer, intent(in) :: Idim
integer, intent(in) :: Direction
integer, intent(in), optional :: Handle
integer, intent(out), optional :: rc
private subroutine MAPL_BalanceWork8(A, Idim, Direction, Handle, rc)
Depending on the argument “Direction”, this performs the actual distribution of work or the gathering of results for a given strategy. The strategy has to have been predefined by a call to MAPL_BalanceCreate. A strategy “Handle” obtained from that call can be optionally used to specify the strategy. Otherwise, a default strategy is assumed (see MAPL_BalanceCreate for details). Work (Results) is distributed (retrieved) using the buffer A, which is assumed to consist of Jdim contiguous blocks of size Idim. Of course, Jdim can be 1. The blocksize of A (Idim) must be at least as large as the BufLen associated with the strategy. This size can be obtained by quering the strategy using its handle or be saving it from the MAPL_BalanceCreate call. Again, see MAPL_BalanceCreate for details.
Arguments
Type Intent Optional Attributes Name
real(kind=MAPL_R8), intent(inout) :: A(:)
integer, intent(in) :: Idim
integer, intent(in) :: Direction
integer, intent(in), optional :: Handle
integer, intent(out), optional :: rc
Call graph
mapl_balancework calls mapl_balancework4, mapl_balancework8
mapl_balancework4 calls mapl_assert, mpi_recv, mpi_send, mpi_type_commit, mpi_type_free, mpi_type_vector, mapl_return
mapl_balancework8 calls mapl_assert, mpi_recv, mpi_send, mpi_type_commit, mpi_type_free, mpi_type_vector, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize