MAPL_CommsSendRecv – MAPL
MAPL_CommsSendRecv Interface
8 statements
Source File
public interface MAPL_CommsSendRecv
Calls
Called by
Contents
Module Procedures
MAPL_CommsSendRecv_I4_0 MAPL_CommsSendRecv_R4_0 MAPL_CommsSendRecv_R4_1 MAPL_CommsSendRecv_R4_2 MAPL_CommsSendRecv_R8_1 MAPL_CommsSendRecv_R8_2
Module Procedures
private subroutine MAPL_CommsSendRecv_I4_0(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: sendbuf
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSendRecv_R4_0(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: sendbuf
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSendRecv_R4_1(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: sendbuf(:)
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSendRecv_R4_2(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: sendbuf(:,:)
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSendRecv_R8_1(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: sendbuf(:)
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
private subroutine MAPL_CommsSendRecv_R8_2(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(inout) :: sendbuf(:,:)
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
Call graph
mapl_commssendrecv calls mapl_commssendrecv_i4_0, mapl_commssendrecv_r4_0, mapl_commssendrecv_r4_1, mapl_commssendrecv_r4_2, mapl_commssendrecv_r8_1, mapl_commssendrecv_r8_2
mapl_commssendrecv_i4_0 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_commssendrecv_r4_0 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_commssendrecv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_commssendrecv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_commssendrecv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_commssendrecv_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
esmfl_halo_r4_2d calls mapl_commssendrecv
halo calls mapl_commssendrecv
esmfl_halo calls esmfl_halo_r4_2d
mapl_locstreamtransformg2t calls esmfl_halo
mapl_locstreamtransform calls mapl_locstreamtransformg2t
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t