MAPL_TimerOff – MAPL
MAPL_TimerOff Interface
3 statements
Source File
public interface MAPL_TimerOff
Calls
Called by
Module Procedures
private subroutine MAPL_GenericStateClockOff(STATE, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Call graph
mapl_timeroff calls mapl_genericstateclockoff
mapl_genericstateclockoff calls get_actual_timer_name, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
append_file calls mapl_timeroff
create_geosat_grid_find_mask calls mapl_timeroff, create_geosat_grid_find_mask
initialize_ calls mapl_timeroff, mapl_genericinitialize
initialize calls mapl_timeroff, mapl_genericinitialize, create_geosat_grid_find_mask, initialize
mapl_genericfinalize calls mapl_timeroff
mapl_genericinitialize calls mapl_timeroff
mapl_genericrecord calls mapl_timeroff
mapl_genericrefresh calls mapl_timeroff, mapl_genericrefresh
mapl_genericrunchildren calls mapl_timeroff
mapl_genericwrapper calls mapl_timeroff
regrid_append_file calls mapl_timeroff, regrid_append_file
run_ calls mapl_timeroff
run calls mapl_timeroff, append_file, regrid_append_file
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize