MAPL_StateAdd – MAPL
MAPL_StateAdd Interface
4 statements
Source File
public interface MAPL_StateAdd
Calls
Called by
Module Procedures
private interface MAPL_StateAddField()
Arguments
None
private interface MAPL_StateAddBundle()
Arguments
None
Call graph
mapl_stateadd calls mapl_stateaddbundle, mapl_stateaddfield
mapl_stateaddbundle calls mapl_stateaddbundle, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldbundleget, esmf_stateadd, mapl_return, mapl_verify
mapl_stateaddfield calls mapl_stateaddfield, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldget, esmf_stateadd, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
bundle2state calls mapl_stateadd
create_aux_field calls mapl_stateadd
create_holding_field calls mapl_stateadd
create_primary_field calls mapl_stateadd
initialize_ calls mapl_stateadd, create_aux_field, create_holding_field, create_primary_field, mapl_genericinitialize
initialize_extdata calls mapl_stateadd
initialize_gc calls mapl_stateadd, initialize_extdata
initialize calls mapl_stateadd, mapl_genericinitialize, mapl_statecreatefromspec
mapl_statecreatefromspecnew calls mapl_stateadd
esmfl_bundle2state calls bundle2state
mapl_genericinitialize calls mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
mapl_readforcingx calls mapl_statecreatefromvarspecnew
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx