MAPL_Write_Bundle – MAPL
MAPL_Write_Bundle Interface
3 statements
Source File
public interface MAPL_Write_Bundle
Calls
Contents
Module Procedures
Write_bundle_single_time
Module Procedures
private subroutine write_bundle_single_time(bundle, clock, output_file, nbits_to_keep, deflate, quantize_algorithm, quantize_level, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in) :: output_file
integer, intent(in), optional :: nbits_to_keep
integer, intent(in), optional :: deflate
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(out), optional :: rc
Call graph
mapl_write_bundle calls write_bundle_single_time
write_bundle_single_time calls create_from_bundle, mapl_return, mapl_verify, write_to_file
create_from_bundle calls mapl_return, mapl_verify, ESMF_TimeIntervalSet, add_hist_collection, esmf_fieldbundleget, push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
write_to_file calls mapl_return, mapl_verify, done_collective_stage
get_error_message calls at
mapl_throw_exception calls initialize