MAPL_CommsAllReduceMax – MAPL
MAPL_CommsAllReduceMax Interface
11 statements
Source File
public interface MAPL_CommsAllReduceMax
Calls
Called by
Contents
Module Procedures
MAPL_CommsAllReduceMax_I4_0 MAPL_CommsAllReduceMax_R4_0 MAPL_CommsAllReduceMax_R8_0 MAPL_CommsAllReduceMax_I4_1 MAPL_CommsAllReduceMax_R4_1 MAPL_CommsAllReduceMax_R8_1 MAPL_CommsAllReduceMax_I4_2 MAPL_CommsAllReduceMax_R4_2 MAPL_CommsAllReduceMax_R8_2
Module Procedures
private subroutine MAPL_CommsAllReduceMax_I4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_R4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_R8_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_I4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_R4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_R8_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_I4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:,:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_R4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceMax_R8_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Call graph
mapl_commsallreducemax calls mapl_commsallreducemax_i4_0, mapl_commsallreducemax_r4_1, mapl_commsallreducemax_r4_0, mapl_commsallreducemax_r8_0, mapl_commsallreducemax_i4_1, mapl_commsallreducemax_r8_1, mapl_commsallreducemax_i4_2, mapl_commsallreducemax_r4_2, mapl_commsallreducemax_r8_2
mapl_commsallreducemax_i4_0 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_r4_1 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_r4_0 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_r8_0 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_i4_1 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_r8_1 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_i4_2 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_r4_2 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_commsallreducemax_r8_2 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
pmaxmin2d_r4 calls mapl_commsallreducemax
writerestart calls mapl_commsallreducemax
pmaxmin3d_r4 calls pmaxmin2d_r4
pmaxmin1d_r4 calls pmaxmin2d_r4
pmaxmin2d_r8 calls pmaxmin2d_r4
mapl_maxmin calls pmaxmin2d_r4, pmaxmin3d_r4, pmaxmin1d_r4, pmaxmin2d_r8, pmaxmin3d_r8, pmaxmin1d_r8
pmaxmin3d_r8 calls pmaxmin3d_r4
pmaxmin1d_r8 calls pmaxmin1d_r4
mapl_simplebundleprint calls mapl_maxmin