MAPL_VarSpecPrint – MAPL
MAPL_VarSpecPrint Interface
4 statements
Source File
public interface MAPL_VarSpecPrint
Calls
Called by
Contents
Module Procedures
MAPL_VarSpecPrintOne MAPL_VarSpecPrintMany
Module Procedures
private subroutine MAPL_VarSpecPrintOne(SPEC, RC)
$ call lgr%info(‘DIMS = %i0’,SPEC%SPECPtr%DIMS) $ call lgr%info(‘LOCATION = %dims = %i0’,SPEC%SPECPtr%location)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
integer, intent(out), optional :: RC
private subroutine MAPL_VarSpecPrintMany(SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC(:)
integer, intent(out), optional :: RC
Call graph
mapl_varspecprint calls mapl_varspecprintone, mapl_varspecprintmany
mapl_varspecprintone calls mapl_return
mapl_varspecprintmany calls mapl_varspecprint, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_stateprintspec calls mapl_varspecprint, mapl_stateprintspec
mapl_varspecaddreffromitem calls mapl_varspecprint
mapl_varspecaddreffromitemnew calls mapl_varspecprint
mapl_setvarspecforcc calls mapl_varspecprint, mapl_varspecaddreftolist
mapl_varspecaddreffromlist calls mapl_varspecaddreffromitem
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist, mapl_varspecaddreffromitemnew
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_genericspecenum calls mapl_varspecaddreftolist, mapl_genericspecenum
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_addimportspec calls mapl_stateaddimportspecfrmchld