MAPL_VarWrite – MAPL
MAPL_VarWrite Interface
10 statements
Source File
public interface MAPL_VarWrite
Calls
Called by
Contents
Module Procedures
MAPL_VarWriteNCpar_R4_1d MAPL_VarWriteNCpar_R4_2d MAPL_VarWriteNCpar_R4_3d MAPL_VarWriteNCpar_R4_4d MAPL_VarWriteNCpar_R8_1d MAPL_VarWriteNCpar_R8_2d MAPL_VarWriteNCpar_R8_3d MAPL_VarWriteNCpar_R8_4d
Module Procedures
private subroutine MAPL_VarWriteNCpar_R4_1d(formatter, name, A, layout, ARRDES, MASK, offset1, offset2, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(in) :: A(:)
type(ESMF_DELayout), intent(in), optional :: layout
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(in), optional :: MASK(:)
integer, intent(in), optional :: offset1
integer, intent(in), optional :: offset2
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R4_2d(formatter, name, A, ARRDES, lev, offset2, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(in), optional :: lev
integer, intent(in), optional :: offset2
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R4_3d(formatter, name, A, ARRDES, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R4_4d(formatter, name, A, ARRDES, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R8_1d(formatter, name, A, layout, ARRDES, MASK, offset1, offset2, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R8), intent(in) :: A(:)
type(ESMF_DELayout), intent(in), optional :: layout
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(in), optional :: MASK(:)
integer, intent(in), optional :: offset1
integer, intent(in), optional :: offset2
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R8_2d(formatter, name, A, ARRDES, lev, offset2, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R8), intent(in) :: A(:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(in), optional :: lev
integer, intent(in), optional :: offset2
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R8_3d(formatter, name, A, ARRDES, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R8), intent(in) :: A(:,:,:)
type(ArrDescr), intent(inout) :: ARRDES
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
private subroutine MAPL_VarWriteNCpar_R8_4d(formatter, name, A, ARRDES, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R8), intent(in) :: A(:,:,:,:)
type(ArrDescr), intent(inout) :: ARRDES
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
Call graph
mapl_varwrite calls mapl_varwritencpar_r4_1d, mapl_varwritencpar_r4_2d, mapl_varwritencpar_r4_3d, mapl_varwritencpar_r4_4d, mapl_varwritencpar_r8_1d, mapl_varwritencpar_r8_2d, mapl_varwritencpar_r8_3d, mapl_varwritencpar_r8_4d
mapl_varwritencpar_r4_1d calls mapl_assert, mapl_commsbcast, mpi_comm_create, mpi_comm_free, mpi_comm_group, mpi_comm_rank, mpi_comm_size, mpi_gatherv, mpi_group_free, mpi_group_incl, mpi_group_translate_ranks, nf90_strerror, mapl_return, mapl_verify, put_var
mapl_varwritencpar_r4_2d calls collective_stage_data, mapl_assert, mapl_grid_interior, mpi_comm_rank, mpi_comm_size, mpi_gatherv, nf90_strerror, mapl_gridget, mapl_return, mapl_verify, put_var
mapl_varwritencpar_r4_3d calls mapl_varwrite, collective_stage_data, mapl_assert, mapl_grid_interior, mapl_gridget, mapl_return, mapl_verify
mapl_varwritencpar_r4_4d calls mapl_varwrite, collective_stage_data, mapl_assert, mapl_grid_interior, mapl_gridget, mapl_return, mapl_verify
mapl_varwritencpar_r8_1d calls mapl_assert, mapl_commsbcast, mpi_comm_create, mpi_comm_free, mpi_comm_group, mpi_comm_rank, mpi_comm_size, mpi_gatherv, mpi_group_free, mpi_group_incl, mpi_group_translate_ranks, nf90_strerror, mapl_return, mapl_verify, put_var
mapl_varwritencpar_r8_2d calls collective_stage_data, mapl_assert, mapl_grid_interior, mpi_comm_rank, mpi_comm_size, mpi_gatherv, nf90_strerror, mapl_gridget, mapl_return, mapl_verify, put_var
mapl_varwritencpar_r8_3d calls mapl_varwrite, collective_stage_data, mapl_assert, mapl_grid_interior, mapl_gridget, mapl_return, mapl_verify
mapl_varwritencpar_r8_4d calls mapl_varwrite, collective_stage_data, mapl_assert, mapl_grid_interior, mapl_gridget, mapl_return, mapl_verify
mapl_fieldwritencpar calls mapl_varwrite
mapl_bundlewritencpar calls mapl_fieldwritencpar
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
mapl_esmfstatewritetofile calls mapl_varwritencpar