MAPL_ConfigSetAttribute – MAPL
MAPL_ConfigSetAttribute Interface
8 statements
Source File
public interface MAPL_ConfigSetAttribute
Calls
Called by
Contents
Module Procedures
MAPL_ConfigSetAttribute_real32 MAPL_ConfigSetAttribute_reals32 MAPL_ConfigSetAttribute_real64 MAPL_ConfigSetAttribute_int32 MAPL_ConfigSetAttribute_ints32 MAPL_ConfigSetAttribute_string
Module Procedures
private subroutine MAPL_ConfigSetAttribute_real32(config, value, label, rc)
Set a 4-byte real value in the config object.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
real(kind=REAL32), intent(in) :: value
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
private subroutine MAPL_ConfigSetAttribute_reals32(config, value, label, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
real(kind=REAL32), intent(in) :: value(:)
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
private subroutine MAPL_ConfigSetAttribute_real64(config, value, label, rc)
Set a 8-byte real value in the config object.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
real(kind=REAL64), intent(in) :: value
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
private subroutine MAPL_ConfigSetAttribute_int32(config, value, label, rc)
Set a 4-byte integer value in the config object.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
integer(kind=INT32), intent(in) :: value
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
private subroutine MAPL_ConfigSetAttribute_ints32(config, value, label, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
integer(kind=INT32), intent(in) :: value(:)
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
private subroutine MAPL_ConfigSetAttribute_string(config, value, label, rc)
Set a string value in the config object.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: value
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
Call graph
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configsetattribute_int32 calls ESMF_ConfigGetAttribute, mapl_return
mapl_configsetattribute_ints32 calls mapl_configsetattribute, mapl_assert, mapl_return, mapl_verify
mapl_configsetattribute_real32 calls ESMF_ConfigGetAttribute, mapl_return
mapl_configsetattribute_real64 calls ESMF_ConfigGetAttribute, mapl_return
mapl_configsetattribute_reals32 calls mapl_configsetattribute, mapl_assert, mapl_return, mapl_verify
mapl_configsetattribute_string calls ESMF_ConfigGetAttribute, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
addgrid calls mapl_configsetattribute
create_cf calls mapl_configsetattribute
create_output_grid calls mapl_configsetattribute
initialize calls mapl_configsetattribute
initialize_from_esmf_distgrid calls mapl_configsetattribute
initialize_gc calls mapl_configsetattribute
mapl_extdatagridchangelev calls mapl_configsetattribute
mapl_gridcreate calls mapl_configsetattribute
test_setattribute_string calls mapl_configsetattribute
create_grid calls create_cf
createfilelevbracket calls mapl_extdatagridchangelev
initialize_ calls mapl_gridcreate, createfilelevbracket
time_ave calls create_output_grid
ut_regridding calls create_cf
create_bracketing_fields calls createfilelevbracket
process_command_line calls create_grid
main calls process_command_line
run_ calls create_bracketing_fields