MAPL_CommsScatterV – MAPL
MAPL_CommsScatterV Interface
7 statements
Source File
public interface MAPL_CommsScatterV
Calls
Called by
Module Procedures
private subroutine MAPL_CommsScatterV_I4_1(layout, sendbuf, sendcnts, displs, recvbuf, recvcnt, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnts(:)
integer, intent(in) :: displs(:)
integer(kind=ESMF_KIND_I4), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnt
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsScatterV_R4_1(layout, sendbuf, sendcnts, displs, recvbuf, recvcnt, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnts(:)
integer, intent(in) :: displs(:)
real(kind=ESMF_KIND_R4), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnt
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsScatterV_R4_2(layout, sendbuf, sendcnts, displs, recvbuf, recvcnt, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnts(:)
integer, intent(in) :: displs(:)
real(kind=ESMF_KIND_R4), intent(out) :: recvbuf(:,:)
integer, intent(in) :: recvcnt
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsScatterV_R8_1(layout, sendbuf, sendcnts, displs, recvbuf, recvcnt, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnts(:)
integer, intent(in) :: displs(:)
real(kind=ESMF_KIND_R8), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnt
integer, intent(in) :: root
integer, intent(out), optional :: RC
private subroutine MAPL_CommsScatterV_R8_2(layout, sendbuf, sendcnts, displs, recvbuf, recvcnt, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnts(:)
integer, intent(in) :: displs(:)
real(kind=ESMF_KIND_R8), intent(out) :: recvbuf(:,:)
integer, intent(in) :: recvcnt
integer, intent(in) :: root
integer, intent(out), optional :: RC
Call graph
mapl_commsscatterv calls mapl_commsscatterv_i4_1, mapl_commsscatterv_r4_1, mapl_commsscatterv_r4_2, mapl_commsscatterv_r8_1, mapl_commsscatterv_r8_2
mapl_commsscatterv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_scatterv, mapl_return, mapl_verify
mapl_commsscatterv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_scatterv, mapl_return, mapl_verify
mapl_commsscatterv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_scatterv, mapl_return, mapl_verify
mapl_commsscatterv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_scatterv, mapl_return, mapl_verify
mapl_commsscatterv_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_scatterv, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
arrayscatter_r4_1 calls mapl_commsscatterv
arrayscatter_r4_2 calls mapl_commsscatterv
arrayscatter_r8_1 calls mapl_commsscatterv
arrayscatter_r8_2 calls mapl_commsscatterv
arrayscattershmr4d1 calls mapl_commsscatterv
arrayscatter calls arrayscatter_r4_1, arrayscatter_r4_2, arrayscatter_r8_1, arrayscatter_r8_2
arrayscattershm calls arrayscattershmr4d1
bundleregrid calls arrayscatter
mapl_cfioreadbundle calls arrayscatter
mapl_varread_r4_1d calls arrayscatter, arrayscattershm
mapl_varread_r4_2d calls arrayscatter, arrayscattershm
mapl_varread_r8_1d calls arrayscatter
mapl_varread_r8_2d calls arrayscatter
mapl_varreadncpar_r4_1d calls arrayscatter, arrayscattershm
process_data_from_file calls arrayscatter
esmf_ioread calls mapl_cfioreadbundle
esmfl_regrid calls bundleregrid
mapl_cfioread calls mapl_cfioreadbundle
mapl_varread calls mapl_varreadncpar_r4_1d, mapl_varread_r4_1d, mapl_varread_r4_2d, mapl_varread_r8_1d, mapl_varread_r8_2d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_extdatareadprefetch calls process_data_from_file
stateregrid calls bundleregrid