MAPL_AllocateShared_1DR8 – MAPL
MAPL_AllocateShared_1DR8 Interface
306 statements
Source File
interface
Called by
private module subroutine MAPL_AllocateShared_1DR8(Ptr, Shp, lbd, TransRoot, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), pointer :: Ptr(:)
integer, intent(in) :: Shp(1)
integer, intent(in), optional :: lbd(1)
logical, intent(in) :: TransRoot
integer, intent(out), optional :: rc
Call graph
mapl_allocateshared calls mapl_allocateshared_1dr8
add_horz_coordinates_from_file calls mapl_allocateshared
get_obs_time calls mapl_allocateshared
mapl_cfiocreatefrombundle calls mapl_allocateshared
mapl_locstreamcreatefromfile calls mapl_allocateshared
read_geos_binary calls mapl_allocateshared
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize_subclass calls read_geos_binary
make_new_grid calls add_horz_coordinates_from_file
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
initialize_ calls mapl_locstreamcreate
initialize calls mapl_locstreamcreate
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate