MAPL_GriddedIO – MAPL
MAPL_GriddedIO Interface
3 statements
Source File
public interface MAPL_GriddedIO
Calls
Module Procedures
private function new_MAPL_GriddedIO(metadata, input_bundle, output_bundle, write_collection_id, read_collection_id, metadata_collection_id, regrid_method, fraction, items, rc) result(GriddedIO)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in), optional :: metadata
type(ESMF_FieldBundle), intent(in), optional :: input_bundle
type(ESMF_FieldBundle), intent(in), optional :: output_bundle
integer, intent(in), optional :: write_collection_id
integer, intent(in), optional :: read_collection_id
integer, intent(in), optional :: metadata_collection_id
integer, intent(in), optional :: regrid_method
integer, intent(in), optional :: fraction
type(GriddedIOitemVector), intent(in), optional :: items
integer, intent(out), optional :: rc
Return Value type(MAPL_GriddedIO)
Call graph
mapl_griddedio calls new_mapl_griddedio
new_mapl_griddedio calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize