MAPL_AddChild – MAPL
MAPL_AddChild Interface
7 statements
Source File
public interface MAPL_AddChild
Calls
Called by
Contents
Module Procedures
AddChildFromGC AddChildFromMeta AddChildFromDSO_old AddChildFromDSO AddChildFromDSOMeta
Module Procedures
private recursive function AddChildFromGC(GC, name, SS, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: name
real :: SS
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromMeta(META, NAME, GRID, CONFIGFILE, SS, parentGC, petList, rc)
$ gridcomp => META%GET_CHILD_GRIDCOMP(I)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: META
character(len=*), intent(in) :: NAME
type(ESMF_Grid), intent(inout), optional :: GRID
character(len=*), intent(in), optional :: CONFIGFILE
real :: SS
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(in), optional :: petList(:)
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromDSO_old(name, userRoutine, grid, ParentGC, SharedObj, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
type(ESMF_GridComp), intent(inout), optional :: ParentGC
character(len=*), intent(in), optional :: SharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromDSO(gc, name, userRoutine, grid, sharedObj, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
character(len=*), intent(in), optional :: sharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
private recursive function AddChildFromDSOMeta(META, name, userRoutine, grid, sharedObj, petList, configFile, parentGC, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: META
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
character(len=*), intent(in), optional :: sharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(out), optional :: rc
Return Value integer
Call graph
mapl_addchild calls addchildfromgc, addchildfromdso_old, addchildfrommeta, addchildfromdso, addchildfromdsometa
addchildfromgc calls addchildfrommeta, mapl_internalstateretrieve, mapl_return, mapl_verify
addchildfromdso_old calls addchildfromdso, mapl_return, mapl_verify, mapl_assert
addchildfrommeta calls mapl_return, get_global_time_profiler, mapl_verify, esmf_gridcompsetservices, addchild_preamble
addchildfromdso calls addchildfromdsometa, mapl_internalstateretrieve, mapl_return, mapl_verify
addchildfromdsometa calls mapl_return, get_global_time_profiler, mapl_verify, esmf_gridcompsetservices, addchild_preamble, is_valid_dso_name, get_file_extension, adjust_dso_name
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
addchild_preamble calls mapl_return, mapl_verify, mapl_assert, esmf_vmgetcurrent, esmf_vmget, mapl_internalstatecreate, esmf_configloadfile, esmf_configcreate, esmf_gridcompcreate, esmf_statecreate
is_valid_dso_name calls get_file_extension, is_valid_dso_extension
get_file_extension calls find_extension_index
adjust_dso_name calls get_file_basename
setservices calls mapl_addchild, setservices
initialize_gc calls mapl_addchild