MAPL_Alloc – MAPL
MAPL_Alloc Interface
3 statements
Source File
public interface MAPL_Alloc
Calls
Contents
Module Procedures
MAPL_Alloc_R_2D
Module Procedures
private subroutine MAPL_Alloc_R_2D(A, IM, JM, RC)
Arguments
Type Intent Optional Attributes Name
real, pointer :: A(:,:)
integer, intent(in) :: IM
integer, intent(in) :: JM
integer, intent(out), optional :: RC
Call graph
mapl_alloc calls mapl_alloc_r_2d
mapl_alloc_r_2d calls mapl_heapset, mapl_verify, mapl_assert, mapl_return
mapl_heapset calls mapl_verify, mapl_assert, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception