MAPL_SimpleBundleCreate – MAPL
MAPL_SimpleBundleCreate Interface
5 statements
Source File
public interface MAPL_SimpleBundleCreate
Calls
Called by
Contents
Module Procedures
MAPL_SimpleBundleCreateEmpty MAPL_SimpleBundleCreateFromBundle MAPL_SimpleBundleCreateFromState
Module Procedures
private function MAPL_SimpleBundleCreateEmpty(grid, rc, Levs, LevUnits, ptop, delp, name) result(self)
Given inputs, create a SimpleBundle.
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(out), optional :: rc
real(kind=ESMF_KIND_R4), intent(in), optional :: Levs(:)
Vertical coordinates Constant levels
character(len=*), intent(in), optional :: LevUnits
Level units
real(kind=ESMF_KIND_R4), intent(in), optional :: ptop
top pressure (Pa) Lagrangian Control Volume Info
real(kind=ESMF_KIND_R4), intent(in), optional, pointer :: delp(:,:,:)
layer thickness (Pa)
character(len=*), intent(in), optional :: name
name
Return Value type(MAPL_SimpleBundle)
Simple Bundle !rename to simpleBundle
private function MAPL_SimpleBundleCreateFromBundle(Bundle, rc, Levs, LevUnits, ptop, delp, only_vars, strict, name) result(self)
Given an ESMF Bundle, creates a corresponding Simple Bundle. The specification of a vertical grid is optional but useful in many cases. The 1-D Levs will default to the layer number, and units of “1”. Input parameters (ptop,delp) can be used to record the corresponding Lagrangian Control Volume Grid. When delp is not specified, variables DELP or delp are used if present inside the bundle.
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout), target :: Bundle
ESMF Bundle
integer, intent(out), optional :: rc
real(kind=ESMF_KIND_R4), intent(in), optional :: Levs(:)
Vertical coordinates Constant levels
character(len=*), intent(in), optional :: LevUnits
Level units
real(kind=ESMF_KIND_R4), intent(in), optional :: ptop
top pressure (Pa) Lagrangian Control Volume Info
real(kind=ESMF_KIND_R4), intent(in), optional, pointer :: delp(:,:,:)
layer thickness (Pa)
character(len=*), intent(in), optional :: only_vars
comma separated field names
logical, intent(in), optional :: strict
force name matching, ignored if only_vars is not present
character(len=*), intent(in), optional :: name
name
Return Value type(MAPL_SimpleBundle)
Simple Bundle
private function MAPL_SimpleBundleCreateFromState(State, rc, Levs, LevUnits, ptop, delp, only_vars, strict, name) result(self)
Given an ESMF Staete, creates a corresponding Simple Bundle. The specificatiopn of a vertical grid is optional but useful in many cases. The 1-D Levs will default to the layer number, and units of “1”. Input parameters (ptop,delp) can be used to record the corresponding Lagrangian Control Volume Grid. When delp is not specified, variables DELP or delp are used if present inside the bundle.
Read more…
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout), target :: State
ESMF State
integer, intent(out), optional :: rc
real(kind=ESMF_KIND_R4), intent(in), optional :: Levs(:)
Vertical coordinates Constant levels
character(len=*), intent(in), optional :: LevUnits
Level units
real(kind=ESMF_KIND_R4), intent(in), optional :: ptop
top pressure (Pa) Lagrangian Control Volume Info
real(kind=ESMF_KIND_R4), intent(in), optional, pointer :: delp(:,:,:)
layer thickness (Pa)
character(len=*), intent(in), optional :: only_vars
comma separated field names
logical, intent(in), optional :: strict
force name maching, ignored if only_vars is not present
character(len=*), intent(in), optional :: name
name
Return Value type(MAPL_SimpleBundle)
Simple Bundle
Call graph
mapl_simplebundlecreate calls mapl_simplebundlecreateempty, mapl_simplebundlecreatefrombundle, mapl_simplebundlecreatefromstate
mapl_simplebundlecreateempty calls ESMF_GridGetCoord, mapl_assert, mapl_gridget, mapl_return, mapl_verify
mapl_simplebundlecreatefrombundle calls ESMF_GridGetCoord, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_assert, mapl_fieldbundleget, mapl_gridget, mapl_return, mapl_verify, r1, r2, r3
mapl_simplebundlecreatefromstate calls mapl_simplebundlecreatefrombundle, esmf_fieldbundlecreate, esmf_stateget, esmfl_bundleaddstate, mapl_return, mapl_verify
esmfl_bundleaddstate calls bundleaddstate_
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleget calls mapl_fieldbundlegetbyindex
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_simplebundleread calls mapl_simplebundlecreate