MAPL_MaxMin – MAPL
MAPL_MaxMin Interface
8 statements
Source File
public interface MAPL_MaxMin
Calls
Called by
Module Procedures
private subroutine pmaxmin3d_r4(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R4), intent(in) :: a(:,:,:)
real(kind=ESMF_KIND_R4), intent(out), optional :: pmin
real(kind=ESMF_KIND_R4), intent(out), optional :: pmax
real(kind=ESMF_KIND_R4), intent(in), optional :: fac
private subroutine pmaxmin2d_r4(qname, a, pmin_, pmax_, fac_)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R4), intent(in) :: a(:,:)
real(kind=ESMF_KIND_R4), intent(out), optional :: pmin_
real(kind=ESMF_KIND_R4), intent(out), optional :: pmax_
real(kind=ESMF_KIND_R4), intent(in), optional :: fac_
private subroutine pmaxmin1d_r4(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R4), intent(in) :: a(:)
real(kind=ESMF_KIND_R4), intent(out), optional :: pmin
real(kind=ESMF_KIND_R4), intent(out), optional :: pmax
real(kind=ESMF_KIND_R4), intent(in), optional :: fac
private subroutine pmaxmin3d_r8(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R8), intent(in) :: a(:,:,:)
real(kind=ESMF_KIND_R8), intent(out), optional :: pmin
real(kind=ESMF_KIND_R8), intent(out), optional :: pmax
real(kind=ESMF_KIND_R8), intent(in), optional :: fac
private subroutine pmaxmin2d_r8(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R8), intent(in) :: a(:,:)
real(kind=ESMF_KIND_R8), intent(out), optional :: pmin
real(kind=ESMF_KIND_R8), intent(out), optional :: pmax
real(kind=ESMF_KIND_R8), intent(in), optional :: fac
private subroutine pmaxmin1d_r8(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R8), intent(in) :: a(:)
real(kind=ESMF_KIND_R8), intent(out), optional :: pmin
real(kind=ESMF_KIND_R8), intent(out), optional :: pmax
real(kind=ESMF_KIND_R8), intent(in), optional :: fac
Call graph
mapl_maxmin calls pmaxmin1d_r4, pmaxmin1d_r8, pmaxmin2d_r4, pmaxmin2d_r8, pmaxmin3d_r4, pmaxmin3d_r8
pmaxmin1d_r4 calls pmaxmin2d_r4
pmaxmin1d_r8 calls pmaxmin1d_r4
pmaxmin2d_r4 calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_am_i_root, mapl_commsallreducemax, mpi_reduce
pmaxmin2d_r8 calls pmaxmin2d_r4
pmaxmin3d_r4 calls pmaxmin2d_r4
pmaxmin3d_r8 calls pmaxmin3d_r4
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_commsallreducemax calls mapl_commsallreducemax_i4_0, mapl_commsallreducemax_i4_1, mapl_commsallreducemax_i4_2, mapl_commsallreducemax_r4_0, mapl_commsallreducemax_r4_1, mapl_commsallreducemax_r4_2, mapl_commsallreducemax_r8_0, mapl_commsallreducemax_r8_1, mapl_commsallreducemax_r8_2
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_commsallreducemax_i4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_i4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_i4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r8_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r8_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r8_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_simplebundleprint calls mapl_maxmin