MAPL_VarRead – MAPL
MAPL_VarRead Interface
13 statements
Source File
public interface MAPL_VarRead
Calls
Called by
Module Procedures
private subroutine MAPL_StateVarRead(UNIT, STATE, NAME, ARRDES, bootstrapable, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_State), intent(inout) :: STATE
character(len=*), intent(in), optional :: NAME
type(ArrDescr), intent(inout), optional :: ARRDES
logical, intent(in), optional :: bootstrapable
integer, intent(out), optional :: RC
private subroutine MAPL_BundleRead(UNIT, BUNDLE, ARRDES, BOOTSTRAPABLE, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
type(ArrDescr), intent(inout), optional :: ARRDES
logical, intent(in), optional :: BOOTSTRAPABLE
integer, intent(out), optional :: RC
private subroutine MAPL_FieldRead(UNIT, field, ARRDES, HomePE, ignoreEOF, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Field), intent(inout) :: field
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(in), optional, target :: HomePE(:)
logical, intent(in), optional :: ignoreEOF
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R4_1d(UNIT, GRID, A, MASK, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R4), intent(out) :: A(:)
integer, intent(in), optional :: MASK(:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R4_2d(UNIT, GRID, A, MASK, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R4), intent(out) :: A(:,:)
integer, intent(in), optional :: MASK(:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R4_3d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R4), intent(out) :: A(:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R4_4d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R4), intent(out) :: A(:,:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R8_1d(UNIT, GRID, A, MASK, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(out) :: A(:)
integer, intent(in), optional :: MASK(:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R8_2d(UNIT, GRID, A, MASK, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(out) :: A(:,:)
integer, intent(in), optional :: MASK(:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R8_3d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(out) :: A(:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine MAPL_VarRead_R8_4d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(out) :: A(:,:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Call graph
mapl_varread calls mapl_bundleread, mapl_fieldread, mapl_statevarread, mapl_varread_r4_1d, mapl_varread_r4_2d, mapl_varread_r4_3d, mapl_varread_r4_4d, mapl_varread_r8_1d, mapl_varread_r8_2d, mapl_varread_r8_3d, mapl_varread_r8_4d
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_fieldread calls mapl_varread
mapl_readforcingx calls mapl_varread
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
readrestart calls mapl_varread
mapl_bundleread calls mapl_fieldread
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarread calls mapl_fieldread, mapl_bundleread
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
refresh_state calls mapl_genericstaterestore