MAPL_AllocNodeArray – MAPL
MAPL_AllocNodeArray Interface
3 statements
Source File
private interface MAPL_AllocNodeArray
Calls
Contents
Module Procedures
MAPL_AllocNodeArray_Tiling
Module Procedures
private subroutine MAPL_AllocNodeArray_Tiling(Ptr, shp, rc)
Arguments
Type Intent Optional Attributes Name
type(XTile), intent(inout), pointer :: Ptr(:)
integer, intent(in) :: shp(1)
integer, intent(out), optional :: rc
Call graph
mapl_allocnodearray calls mapl_allocnodearray_tiling
mapl_allocnodearray_tiling calls getsharedmemory, mapl_return, mapl_verify
getsharedmemory calls getsharedmemory, mapl_return, mapl_assert, shmat, shmget, mpi_barrier, segs, segsnew
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize