MAPL_DeAllocNodeArray_4DR8 – MAPL
MAPL_DeAllocNodeArray_4DR8 Interface
313 statements
Source File
interface
Called by
private module subroutine MAPL_DeAllocNodeArray_4DR8(Ptr, rc) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), pointer :: Ptr(:,:,:,:)
integer, intent(out), optional :: rc
Call graph
mapl_deallocnodearray calls mapl_deallocnodearray_4dr8
add_horz_coordinates_from_abifile calls mapl_deallocnodearray
add_horz_coordinates_from_file calls mapl_deallocnodearray
get_obs_time calls mapl_deallocnodearray
initialize_subclass calls mapl_deallocnodearray
mapl_bundlereadncpar calls mapl_deallocnodearray
mapl_bundlewritencpar calls mapl_deallocnodearray
mapl_cfioreadbundle calls mapl_deallocnodearray
mapl_cfiowritebundlepost calls mapl_deallocnodearray
mapl_fieldread calls mapl_deallocnodearray
mapl_fieldreadncpar calls mapl_deallocnodearray
mapl_fieldwrite calls mapl_deallocnodearray
mapl_fieldwritencpar calls mapl_deallocnodearray
mapl_locstreamcreatefromfile calls mapl_deallocnodearray
mapl_statevarread calls mapl_deallocnodearray
mapl_statevarwrite calls mapl_deallocnodearray
mapl_varread_r4_1d calls mapl_deallocnodearray
mapl_varread_r4_2d calls mapl_deallocnodearray
mapl_varreadncpar_r4_1d calls mapl_deallocnodearray
read_geos_binary calls mapl_deallocnodearray
readrestart calls mapl_deallocnodearray
writerestart calls mapl_deallocnodearray