MAPL_CapOptions – MAPL
MAPL_CapOptions Interface
4 statements
Source File
public interface MAPL_CapOptions
Calls
Contents
Module Procedures
new_CapOptions new_CapOptions_copy
Module Procedures
private function new_CapOptions(unusable, cap_rc_file, egress_file, ensemble_subdir_prefix, esmf_logging_mode, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: cap_rc_file
character(len=*), intent(in), optional :: egress_file
character(len=*), intent(in), optional :: ensemble_subdir_prefix
type(ESMF_LogKind_Flag), intent(in), optional :: esmf_logging_mode
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
private function new_CapOptions_copy(options) result(copy)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CapOptions), intent(in) :: options
Return Value type(MAPL_CapOptions)
Call graph
mapl_capoptions calls new_capoptions, new_capoptions_copy
new_capoptions calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize