MAPL_CapOptions – MAPL
MAPL_CapOptions Interface
3 statements
Source File
public interface MAPL_CapOptions
Calls
Module Procedures
private function old_CapOptions_from_Flap(flapCLI, unusable, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
type(MAPL_FlapCLI), intent(inout) :: flapCLI
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
Call graph
mapl_capoptions calls old_capoptions_from_flap
old_capoptions_from_flap calls get, get_varying, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize