MAPL_AddImportSpec – MAPL
MAPL_AddImportSpec Interface
4 statements
Source File
public interface MAPL_AddImportSpec
Calls
Called by
Contents
Module Procedures
MAPL_StateAddImportSpec_ MAPL_StateAddImportSpecFrmChld
Module Procedures
private subroutine MAPL_StateAddImportSpec_(GC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, DATATYPE, NUM_SUBTILES, REFRESH_INTERVAL, AVERAGING_INTERVAL, HALOWIDTH, PRECISION, DEFAULT, RESTART, UNGRIDDED_DIMS, FIELD_TYPE, STAGGERING, ROTATION, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: LONG_NAME
character(len=*), intent(in), optional :: UNITS
integer, intent(in), optional :: DIMS
integer, intent(in), optional :: VLOCATION
integer, intent(in), optional :: DATATYPE
integer, intent(in), optional :: NUM_SUBTILES
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
integer, intent(in), optional :: HALOWIDTH
integer, intent(in), optional :: PRECISION
real, intent(in), optional :: DEFAULT
integer, intent(in), optional :: RESTART
integer, intent(in), optional :: UNGRIDDED_DIMS(:)
integer, intent(in), optional :: FIELD_TYPE
integer, intent(in), optional :: STAGGERING
integer, intent(in), optional :: ROTATION
integer, intent(out), optional :: RC
private subroutine MAPL_StateAddImportSpecFrmChld(STATE, SHORT_NAME, CHILD_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: CHILD_ID
integer, intent(out), optional :: RC
Call graph
mapl_addimportspec calls mapl_stateaddimportspec_, mapl_stateaddimportspecfrmchld
mapl_stateaddimportspec_ calls mapl_internalstateretrieve, mapl_verify, mapl_varspeccreateinlistnew, mapl_assert, esmf_configgetattribute, mapl_return
mapl_stateaddimportspecfrmchld calls mapl_verify, mapl_return, mapl_gridcompgetvarspecs, mapl_varspecaddreftolist, mapl_varspecgetindex
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_verify calls mapl_throw_exception
mapl_varspeccreateinlistnew calls mapl_verify, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_gridcompgetvarspecs calls mapl_internalstateretrieve, mapl_verify, mapl_return, esmf_gridcompget, mapl_stategetvarspecs
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_internalstatecreate calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompsetinternalstate
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_stategetvarspecs calls mapl_return
mapl_varspecaddreffromitem calls mapl_verify, mapl_return, mapl_varspecgetindex, mapl_varspecprint
mapl_varspecaddreffromlist calls mapl_verify, mapl_return, mapl_varspecaddreffromitem
setservices calls mapl_addimportspec, setservices
addnewspec calls mapl_addimportspec