MAPL_CapOptions – MAPL
MAPL_CapOptions Interface
3 statements
Source File
public interface MAPL_CapOptions
Calls
Called by
Contents
Module Procedures
old_CapOptions_from_flap
Module Procedures
private function old_CapOptions_from_Flap(flapCLI, unusable, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
type(MAPL_FlapCLI), intent(inout) :: flapCLI
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
Call graph
mapl_capoptions calls old_capoptions_from_flap
old_capoptions_from_flap calls mapl_verify, mapl_return, mapl_assert
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
newextdatadriver calls mapl_capoptions
main calls mapl_capoptions, run
run calls mapl_capoptions
extdata_driver calls mapl_capoptions, extdatadriver
example_driver calls mapl_capoptions
extdatadriver calls newextdatadriver