MAPL_CommsAllReduceSum – MAPL
MAPL_CommsAllReduceSum Interface
11 statements
Source File
public interface MAPL_CommsAllReduceSum
Calls
Called by
Module Procedures
private subroutine MAPL_CommsAllReduceSum_I4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_R4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_R8_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_I4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_R4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_R8_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_I4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:,:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_R4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
private subroutine MAPL_CommsAllReduceSum_R8_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Call graph
mapl_commsallreducesum calls mapl_commsallreducesum_i4_0, mapl_commsallreducesum_i4_1, mapl_commsallreducesum_i4_2, mapl_commsallreducesum_r4_0, mapl_commsallreducesum_r4_1, mapl_commsallreducesum_r4_2, mapl_commsallreducesum_r8_0, mapl_commsallreducesum_r8_1, mapl_commsallreducesum_r8_2
mapl_commsallreducesum_i4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_i4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_i4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_r4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_r4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_r4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_r8_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_r8_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducesum_r8_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_areamean_2d_r8 calls mapl_commsallreducesum
mapl_areamean calls mapl_areamean_2d_r8, mapl_areamean_2d_r8_bitrep
mapl_areamean_2d_r8_bitrep calls mapl_areamean