MAPL_NPES – MAPL
MAPL_NPES Interface
4 statements
Source File
public interface MAPL_NPES
Calls
Contents
Module Procedures
MAPL_NPES_Layout MAPL_NPES_Vm
Module Procedures
private function MAPL_NPES_Layout(layout) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout), optional :: layout
Return Value integer
private function MAPL_NPES_Vm(VM) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
Return Value integer
Call graph
mapl_npes calls mapl_npes_layout, mapl_npes_vm
mapl_npes_layout calls mapl_npes_vm, esmf_delayoutget
mapl_npes_vm calls esmf_vmget