MAPL_AreaMean – MAPL
MAPL_AreaMean Interface
4 statements
Source File
public interface MAPL_AreaMean
Calls
Called by
Contents
Module Procedures
MAPL_AreaMean_2d_r8_bitrep MAPL_AreaMean_2d_r8
Module Procedures
private subroutine MAPL_AreaMean_2d_r8_bitrep(qave, q, area, grid, bitreproducible, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out) :: qave
real, intent(in) :: q(:,:)
real, intent(in) :: area(:,:)
type(ESMF_Grid), intent(inout) :: grid
logical, intent(in) :: bitreproducible
integer, intent(out), optional :: rc
private subroutine MAPL_AreaMean_2d_r8(qave, q, area, grid, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out) :: qave
real, intent(in) :: q(:,:)
real, intent(in) :: area(:,:)
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), optional :: rc
Call graph
mapl_areamean calls mapl_areamean_2d_r8_bitrep, mapl_areamean_2d_r8
mapl_areamean_2d_r8_bitrep calls mapl_areamean, esmf_vmgetcurrent, mapl_verify, mapl_am_i_root, mapl_gridget, mapl_return, arraygather, mapl_commsbcast
mapl_areamean_2d_r8 calls esmf_vmgetcurrent, mapl_verify, mapl_return, mapl_commsallreducesum