MAPL_FieldBundleAdd – MAPL
MAPL_FieldBundleAdd Interface
3 statements
Source File
public interface MAPL_FieldBundleAdd
Calls
Called by
Base_Implementation::MAPL_BundleCreate w MAPL_Base::MAPL_FieldBundleAdd
w
ESMFL_MOD::Add2Bundle w
w
ESMFL_MOD::BundleAddState_ w
w
ESMFL_MOD::Bundles2Bundle w
w
ESMFL_MOD::ESMFL_BundleCpyField w
w
ESMFL_MOD::ESMFL_StateGetField w
w
ESMFL_MOD::State2Bundle w
w
HistoryTrajectory_implement::create_new_bundle w
w
MAPL_CFIOMod::MAPL_CFIOCreateFromFile w
w
MAPL_CFIOMod::MAPL_CFIOReadBundle w
w
MAPL_CFIOMod::MAPL_CFIOReadField w
w
MAPL_EpochSwathMod::sampler%addVariable_to_acc_bundle w
w
MAPL_EpochSwathMod::sampler%addVariable_to_output_bundle w
w
MAPL_EpochSwathMod::sampler%Create_bundle_RH w
w
MAPL_EpochSwathMod::sampler%CreateVariable w
w
MAPL_ESMFFieldBundleRead::MAPL_create_bundle_from_metdata_id w
w
MAPL_ExtDataGridComp2G::MAPL_ExtDataPopulateBundle w
w
MAPL_ExtDataGridCompMod::MAPL_ExtDataPopulateBundle w
w
MAPL_GenericMod::MAPL_BundleInit w
w
MAPL_GenericMod::MAPL_ProcessServiceConnections w
w
MAPL_GenericMod::PutFieldInBundle__ w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%CreateVariable w
w
MAPL_HistoryGridCompMod::Initialize w
w
MAPL_OrbGridCompMod::Initialize_ w
w
NCIOMod::MAPL_ArrayReadNCpar_1d w
w
NCIOMod::MAPL_ArrayReadNCpar_2d w
w
NCIOMod::MAPL_ArrayReadNCpar_3d w
w
NCIOMod::MAPL_StateVarReadNCPar w
w
NCIOMod::MAPL_StateVarWriteNCPar w
w
time_ave w
w
time_ave::add_new_field_to_bundle w
w
time_ave::copy_bundle_to_bundle w
w
ut_ReGridding w
w
Module Procedures
private interface MAPL_FieldBundleAddField()
Arguments
None
Call graph
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldbundleadd, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception