MaskSamplerGeosat_from_config – MAPL
MaskSamplerGeosat_from_config Interface
52 statements
Source File
interface
module function create_new_bundle(this,rc) result(new_bundle) class(MaskSamplerGeosat), intent(inout) :: this type(ESMF_FieldBundle) :: new_bundle integer, optional, intent(out) :: rc end function create_new_bundle
module subroutine add_metadata(this,currTime,rc)
Calls
Called by
private module function MaskSamplerGeosat_from_config(config, string, clock, GENSTATE, rc) result(mask) Implementation →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: string
type(ESMF_Clock), intent(in) :: clock
type(MAPL_MetaComp), intent(in), optional, pointer :: GENSTATE
integer, intent(out), optional :: rc
Return Value type(MaskSamplerGeosat)
Call graph
masksamplergeosat_from_config calls masksamplergeosat_from_config, ESMF_ClockGet, ESMF_ConfigGetAttribute, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_am_i_root, mapl_assert, convert_twostring_2_esmfinterval, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_twostring_2_esmfinterval calls ESMF_TimeIntervalSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
masksamplergeosat calls masksamplergeosat_from_config