MaskSamplerGeosat – MAPL
MaskSamplerGeosat Interface
3 statements
Source File
public interface MaskSamplerGeosat
Calls
Module Procedures
private interface MaskSamplerGeosat_from_config()
module function create_new_bundle(this,rc) result(new_bundle) class(MaskSamplerGeosat), intent(inout) :: this type(ESMF_FieldBundle) :: new_bundle integer, optional, intent(out) :: rc end function create_new_bundle
Read more…
Arguments
None
Call graph
masksamplergeosat calls masksamplergeosat_from_config
masksamplergeosat_from_config calls masksamplergeosat_from_config, ESMF_ClockGet, ESMF_ConfigGetAttribute, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_am_i_root, mapl_assert, convert_twostring_2_esmfinterval, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_twostring_2_esmfinterval calls ESMF_TimeIntervalSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception