MaskSampler – MAPL
MaskSampler Interface
3 statements
Source File
public interface MaskSampler
Calls
Module Procedures
private interface MaskSampler_from_config()
Arguments
None
Call graph
masksampler calls masksampler_from_config
masksampler_from_config calls masksampler_from_config, ESMF_ClockGet, ESMF_ConfigGetAttribute, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_am_i_root, mapl_assert, convert_twostring_2_esmfinterval, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_twostring_2_esmfinterval calls ESMF_TimeIntervalSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception