memcpy – MAPL
memcpy Interface
6 statements
Source File
private interface memcpy
Calls
Contents
Module Procedures
memcpy_r8 memcpy_r8_gather memcpy_r8_scatter memcpy_r8_gather_scatter
Module Procedures
private subroutine memcpy_r8(lhs, rhs, dim, nelems, lhs_stride, rhs_stride)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out), dimension(0:dim-1) :: lhs
real(kind=REAL64), intent(in), dimension(0:dim-1) :: rhs
integer, intent(in) :: dim
integer, intent(in), optional :: nelems
integer, intent(in), optional :: lhs_stride
integer, intent(in), optional :: rhs_stride
private subroutine memcpy_r8_gather(lhs, rhs, dim, nelems, lhs_stride, rhs_indx)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out), dimension(0:dim-1) :: lhs
real(kind=REAL64), intent(in), dimension(0:dim-1) :: rhs
integer, intent(in) :: dim
integer, intent(in) :: nelems
integer, intent(in) :: lhs_stride
integer, intent(in), dimension(nelems) :: rhs_indx
private subroutine memcpy_r8_scatter(lhs, rhs, dim, nelems, lhs_indx, rhs_stride)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out), dimension(0:dim-1) :: lhs
real(kind=REAL64), intent(in), dimension(0:dim-1) :: rhs
integer, intent(in) :: dim
integer, intent(in) :: nelems
integer, intent(in), dimension(nelems) :: lhs_indx
integer, intent(in) :: rhs_stride
private subroutine memcpy_r8_gather_scatter(lhs, rhs, dim, nelems, lhs_indx, rhs_indx)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out), dimension(0:dim-1) :: lhs
real(kind=REAL64), intent(in), dimension(0:dim-1) :: rhs
integer, intent(in) :: dim
integer, intent(in) :: nelems
integer, intent(in), dimension(nelems) :: lhs_indx
integer, intent(in), dimension(nelems) :: rhs_indx
Call graph
memcpy calls memcpy_r8, memcpy_r8_gather, memcpy_r8_gather_scatter, memcpy_r8_scatter