MemoryProfiler – MAPL
MemoryProfiler Interface
3 statements
Source File
public interface MemoryProfiler
Calls
Module Procedures
private function new_MemoryProfiler(name, comm_world) result(prof)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(in), optional :: comm_world
Return Value type(MemoryProfiler), target
Call graph
memoryprofiler calls new_memoryprofiler
new_memoryprofiler calls start, make_meter, set_comm_world, set_node
start_self calls mapl_assert, start, get_name, mapl_return