MeterNodeIterator – MAPL
MeterNodeIterator Interface
3 statements
Source File
public interface MeterNodeIterator
Calls
Called by
Contents
Module Procedures
new_MeterNodeIterator
Module Procedures
private function new_MeterNodeIterator(meter_node) result(iterator)
Arguments
Type Intent Optional Attributes Name
type(MeterNode), intent(in), target :: meter_node
Return Value type(MeterNodeIterator)
Call graph
meternodeiterator calls new_meternodeiterator
begin calls meternodeiterator
end calls meternodeiterator
accumulate calls begin, accumulate, next, reset
next calls begin
get_exclusive calls next
get_num_nodes calls next, get_num_nodes
reset calls next, reset