MockServerThread – MAPL
MockServerThread Interface
3 statements
Source File
public interface MockServerThread
Calls
Module Procedures
private function new_MockServerThread(sckt) result(s)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), target :: sckt
Return Value type(MockServerThread)
Call graph
mockserverthread calls new_mockserverthread
new_mockserverthread calls set_connection
set_connection calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception