MpiMutex – MAPL
MpiMutex Interface
3 statements
Source File
public interface MpiMutex
Calls
Module Procedures
private function new_MpiMutex(comm) result(lock)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
Return Value type(MpiMutex)
Call graph
mpimutex calls new_mpimutex
new_mpimutex calls blklens, buffer, displs, mpi_alloc_mem, mpi_comm_dup, mpi_comm_rank, mpi_comm_size, mpi_type_commit, mpi_type_extent, mpi_type_indexed, mpi_win_create, mapl_verify, scratchpad
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize