MpiSocket – MAPL
MpiSocket Interface
3 statements
Source File
public interface MpiSocket
Calls
Module Procedures
private function new_MpiSocket(comm, remote_rank, parser, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in) :: remote_rank
type(ProtocolParser), intent(in), target :: parser
integer, intent(out), optional :: rc
Return Value type(MpiSocket)
Call graph
mpisocket calls new_mpisocket
new_mpisocket calls mpi_comm_create_group, mpi_comm_group, mpi_comm_rank, mpi_group_incl, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize