MpiServer – MAPL
MpiServer Interface
3 statements
Source File
public interface MpiServer
Calls
Module Procedures
private function new_MpiServer(comm, port_name, profiler_name, with_profiler, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
character(len=*), intent(in) :: port_name
character(len=*), intent(in), optional :: profiler_name
logical, intent(in), optional :: with_profiler
integer, intent(out), optional :: rc
Return Value type(MpiServer)
Call graph
mpiserver calls new_mpiserver
new_mpiserver calls init, mapl_return, mapl_verify
init calls mapl_return, mapl_verify, mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize