MultiColumn – MAPL
MultiColumn Interface
3 statements
Source File
public interface MultiColumn
Calls
Module Procedures
private function new_MultiColumn(header, separator) result(column)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: header(:)
character(len=1), intent(in), optional :: separator
Return Value type(MultiColumn)
Call graph
multicolumn calls new_multicolumn
new_multicolumn calls get_num_rows_separator, set_separator, set_width