MultiLayerServer – MAPL
MultiLayerServer Interface
3 statements
Source File
public interface MultiLayerServer
Calls
Module Procedures
private function new_MultiLayerServer(comm, port_name, nwriters, pfio_writer, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
character(len=*), intent(in) :: port_name
integer, intent(in) :: nwriters
character(len=*), intent(in) :: pfio_writer
integer, intent(out), optional :: rc
Return Value type(MultiLayerServer)
Call graph
multilayerserver calls new_multilayerserver
new_multilayerserver calls mapl_assert, mpi_comm_spawn, init, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
init calls mapl_return, mapl_verify, mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize