MultiGroupServer – MAPL
MultiGroupServer Interface
3 statements
Source File
public interface MultiGroupServer
Calls
Contents
Module Procedures
new_MultiGroupServer
Module Procedures
private function new_MultiGroupServer(server_comm, port_name, nwriter_per_node, with_profiler, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: server_comm
character(len=*), intent(in) :: port_name
integer, intent(in) :: nwriter_per_node
logical, intent(in), optional :: with_profiler
integer, intent(out), optional :: rc
Return Value type(MultiGroupServer)
Call graph
multigroupserver calls new_multigroupserver
new_multigroupserver calls add_connection, back_ranks, buffers, front_ranks, get_name, get_subcommunicator, init, mapl_assert, mpi_allgather, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_recv, mpi_send, mapl_return, mapl_verify, set_status
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize