nearlyEqual – MAPL
nearlyEqual Interface
4 statements
Source File
public interface nearlyEqual
Calls
Called by
Contents
Module Procedures
nearlyEqual_real32 nearlyEqual_real64
Module Procedures
private elemental function nearlyEqual_real32(r1, r2) result(yes)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: r1
real(kind=REAL32), intent(in) :: r2
Return Value logical
private elemental function nearlyEqual_real64(r1, r2) result(yes)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: r1
real(kind=REAL64), intent(in) :: r2
Return Value logical
Call graph
nearlyequal calls nearlyequal_real32, nearlyequal_real64
equal calls nearlyequal
equal_c calls nearlyequal
test_1d calls nearlyequal
test_2d calls nearlyequal
test_3d calls nearlyequal
test_4d calls nearlyequal
test_scalar calls nearlyequal