next – MAPL
next Interface
5 statements
Source File
private interface next
Calls
Called by
Module Procedures
private function vector_riter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
Return Value type(VectorRIterator)
private function vector_riter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VectorRIterator)
private function vector_riter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(VectorRIterator)
Call graph
next calls vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind, vector_iter_next_1
vector_riter_next_1 calls next
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add
vector_riter_add_n_size_kind calls sub
vector_iter_next_1 calls next