next – MAPL
next Interface
5 statements
Source File
private interface next
Calls
Called by
Contents
Module Procedures
vector_riter_next_1 vector_riter_next_n_size_kind vector_riter_next_n_default
Module Procedures
private function vector_riter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
Return Value type(VectorRIterator)
private function vector_riter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VectorRIterator)
private function vector_riter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(VectorRIterator)
Call graph
next calls vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind, vector_iter_next_1
vector_riter_next_1 calls next
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add
vector_find_if_not calls next
vector_find_if calls next
vector_iter_next_1 calls next
vector_reverse_find_if_not calls next
vector_reverse_find_if calls next
find_if_not calls vector_find_if_not, vector_reverse_find_if_not
find_if calls vector_find_if, vector_reverse_find_if