next – MAPL
next Interface
5 statements
Source File
public interface next
Calls
Module Procedures
private function map_s_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
Return Value type(map_SetIterator)
private function map_s_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(map_SetIterator)
private function map_s_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(map_SetIterator)
Call graph
next calls map_s_iter_next_1, map_s_iter_next_n_default, map_s_iter_next_n_size_kind, map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_iter_next_1 calls next
map_s_iter_next_n_default calls map_s_iter_next
map_s_iter_next_n_size_kind calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_iter_next_1 calls next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
map_s_advpos calls map_s_get_child, to_node