next – MAPL
next Interface
5 statements
Source File
private interface next
Calls
Called by
Contents
Module Procedures
map_iter_next_1 map_iter_next_n_size_kind map_iter_next_n_default
Module Procedures
private function map_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
Return Value type(CallbackMapIterator)
private function map_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(CallbackMapIterator)
private function map_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(CallbackMapIterator)
Call graph
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_iter_next_n_size_kind calls next
map_find_if calls next
map_find_if_not calls next
map_iter_advance_default calls next
map_iter_advance_size_kind calls next
map_s_begin calls next
map_s_deep_copy calls next
map_s_equal calls next
map_s_erase_iter calls next
map_s_erase_range calls next
map_s_find_if calls next
map_s_find_if_not calls next
map_s_ftn_end calls next
map_s_insert_range calls next
map_s_iter_advance_default calls next
map_s_iter_advance_size_kind calls next
map_s_iter_next_1 calls next
map_s_iter_next_n_default calls next
map_s_iter_next_n_size_kind calls next
map_s_less_than calls next
map_s_lower_bound calls next
map_s_merge calls next
map_s_upper_bound calls next
map_s_verify calls next