next – MAPL
next Interface
5 statements
Source File
public interface next
Calls
Contents
Module Procedures
vector_iter_next_1 vector_iter_next_n_size_kind vector_iter_next_n_default
Module Procedures
private function vector_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VarSpecVectorIterator), intent(in) :: it
Return Value type(VarSpecVectorIterator)
private function vector_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VarSpecVectorIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VarSpecVectorIterator)
private function vector_iter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VarSpecVectorIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(VarSpecVectorIterator)
Call graph
next calls vector_iter_next_1, vector_iter_next_n_default, vector_iter_next_n_size_kind, vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind
vector_iter_next_1 calls next
vector_iter_next_n_default calls add
vector_iter_next_n_size_kind calls add
vector_riter_next_1 calls next
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add