OpenMPServer – MAPL
OpenMPServer Interface
3 statements
Source File
public interface OpenMPServer
Calls
Module Procedures
private function new_OpenMPServer(comm, directory_service) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
class(AbstractDirectoryService), intent(inout), target :: directory_service
Return Value type(OpenMPServer)
Call graph
openmpserver calls new_openmpserver
new_openmpserver calls init, publish
init calls mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception