operator(+) – MAPL
operator(+) Interface
6 statements
Source File
private interface operator(+)
Calls
Contents
Module Procedures
vector_riter_a_plus_n_size_kind vector_riter_n_plus_a_size_kind vector_riter_n_plus_a_default vector_riter_a_plus_n_default
Module Procedures
private function vector_riter_a_plus_n_size_kind(a, n) result(new_iter)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: a
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VectorRIterator)
private function vector_riter_n_plus_a_size_kind(n, a) result(new_iter)
Arguments
Type Intent Optional Attributes Name
integer(kind=selected_int_kind(18)), intent(in) :: n
type(VectorRIterator), intent(in) :: a
Return Value type(VectorRIterator)
private function vector_riter_n_plus_a_default(n, a) result(new_iter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(VectorRIterator), intent(in) :: a
Return Value type(VectorRIterator)
private function vector_riter_a_plus_n_default(a, n) result(new_iter)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: a
integer, intent(in) :: n
Return Value type(VectorRIterator)
Call graph
operator(+) calls vector_riter_a_plus_n_default, vector_riter_a_plus_n_size_kind, vector_riter_n_plus_a_default, vector_riter_n_plus_a_size_kind