operator(<) – MAPL
operator(<) Interface
3 statements
Source File
private interface operator(<)
Calls
Contents
Module Procedures
map_s_less_than
Module Procedures
private function map_s_less_than(a, b) result(lt)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in) :: a
type(map_Set), intent(in) :: b
Return Value logical
Call graph
operator(lt) calls map_s_less_than
map_s_less_than calls begin, next, of, map_key_less_than
begin calls map_iter_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_iter_next_n_size_kind calls next