operator(+) – MAPL
operator(+) Interface
6 statements
Source File
public interface operator(+)
Calls
Contents
Module Procedures
vector_iter_a_plus_n_size_kind vector_iter_n_plus_a_size_kind vector_iter_n_plus_a_default vector_iter_a_plus_n_default
Module Procedures
private function vector_iter_a_plus_n_size_kind(a, n) result(new_iter)
Arguments
Type Intent Optional Attributes Name
type(VarSpecVectorIterator), intent(in) :: a
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VarSpecVectorIterator)
private function vector_iter_n_plus_a_size_kind(n, a) result(new_iter)
Arguments
Type Intent Optional Attributes Name
integer(kind=selected_int_kind(18)), intent(in) :: n
type(VarSpecVectorIterator), intent(in) :: a
Return Value type(VarSpecVectorIterator)
private function vector_iter_n_plus_a_default(n, a) result(new_iter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(VarSpecVectorIterator), intent(in) :: a
Return Value type(VarSpecVectorIterator)
private function vector_iter_a_plus_n_default(a, n) result(new_iter)
Arguments
Type Intent Optional Attributes Name
type(VarSpecVectorIterator), intent(in) :: a
integer, intent(in) :: n
Return Value type(VarSpecVectorIterator)
Call graph
operator(+) calls vector_iter_a_plus_n_default, vector_iter_a_plus_n_size_kind, vector_iter_n_plus_a_default, vector_iter_n_plus_a_size_kind
vector_iter_a_plus_n_default calls add
vector_iter_a_plus_n_size_kind calls add
vector_iter_n_plus_a_default calls add
vector_iter_n_plus_a_size_kind calls add