operator(==) – MAPL
operator(==) Interface
3 statements
Source File
public interface operator(==)
Calls
Contents
Module Procedures
map_s_equal
Module Procedures
private function map_s_equal(a, b) result(equal)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in), target :: a
type(map_Set), intent(in), target :: b
Return Value logical
Call graph
operator(==) calls map_s_equal
map_s_equal calls begin, next, of, map_s_order_eq
begin calls map_iter_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_order_eq calls map_s_lessthan
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_iter_next_n_size_kind calls next
map_s_lessthan calls map_key_less_than