Orbits_Track0 – MAPL
Orbits_Track0 Interface
4 statements
Source File
public interface Orbits_Track0
Calls
Called by
Contents
Module Procedures
Orbits_Track1 Orbits_Track2
Module Procedures
private subroutine Orbits_Track1(name, Satcoef_vec1, Normcoef_vec1)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
real(kind=dp), intent(out), dimension(1:Num_coef) :: Satcoef_vec1
real(kind=dp), intent(out), dimension(1:Num_normcoef) :: Normcoef_vec1
private subroutine Orbits_Track2(iSat, Satcoef_vec, Normcoef_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
real(kind=dp), intent(out), dimension(1:Num_coef) :: Satcoef_vec
real(kind=dp), intent(out), dimension(1:Num_normcoef) :: Normcoef_vec
Call graph
orbits_track0 calls orbits_track1, orbits_track2
orbits_track1 calls satname2int
get_estimateeci calls orbits_track0
get_latlon calls get_estimateeci
orbits calls get_estimateeci
find_delta_t calls get_latlon
find_waypointslat calls get_latlon
redifine_timeint calls get_latlon
orbits_track calls find_waypointslat