parse_timeunit – MAPL
parse_timeunit Interface
4 statements
Source File
public interface parse_timeunit
Calls
Called by
Module Procedures
public subroutine parse_timeunit_i4(tunit, n, t0, dt, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: tunit
integer, intent(in) :: n
type(ESMF_Time), intent(out) :: t0
type(ESMF_TimeInterval), intent(out) :: dt
integer, intent(out), optional :: rc
public subroutine parse_timeunit_i8(tunit, n, t0, dt, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: tunit
integer(kind=ESMF_KIND_I8), intent(in) :: n
type(ESMF_Time), intent(out) :: t0
type(ESMF_TimeInterval), intent(out) :: dt
integer, intent(out), optional :: rc
Call graph
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
parse_timeunit_i4 calls ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert, mapl_return, mapl_verify
parse_timeunit_i8 calls ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
time_esmf_2_nc_int calls parse_timeunit
time_nc_int_2_esmf calls parse_timeunit
convert_time_esmf2nc calls time_esmf_2_nc_int
convert_time_nc2esmf calls time_nc_int_2_esmf
create_grid calls time_esmf_2_nc_int
get_x_subset calls time_esmf_2_nc_int
get_xy_subset calls time_esmf_2_nc_int
initialize_from_config_with_prefix calls time_esmf_2_nc_int