prev – MAPL
prev Interface
5 statements
Source File
public interface prev
Calls
Contents
Module Procedures
vector_iter_prev_1 vector_iter_prev_n_size_kind vector_iter_prev_n_default
Module Procedures
private function vector_iter_prev_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(MeterNodeStackIterator), intent(in) :: it
Return Value type(MeterNodeStackIterator)
private function vector_iter_prev_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(MeterNodeStackIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(MeterNodeStackIterator)
private function vector_iter_prev_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(MeterNodeStackIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(MeterNodeStackIterator)
Call graph
prev calls vector_iter_prev_1, vector_iter_prev_n_default, vector_iter_prev_n_size_kind, vector_riter_prev_1, vector_riter_prev_n_default, vector_riter_prev_n_size_kind
vector_iter_prev_1 calls prev
vector_iter_prev_n_default calls sub
vector_iter_prev_n_size_kind calls sub
vector_riter_prev_1 calls prev
vector_riter_prev_n_default calls sub
vector_riter_prev_n_size_kind calls sub