ProtocolParser – MAPL
ProtocolParser Interface
3 statements
Source File
public interface ProtocolParser
Calls
Module Procedures
private function new_ProtocolParser() result(parser)
Arguments
None
Return Value type(ProtocolParser)
Call graph
protocolparser calls new_protocolparser
new_protocolparser calls initialize
initialize calls get_type_id, insert