RDMAReference – MAPL
RDMAReference Interface
3 statements
Source File
public interface RDMAReference
Calls
Contents
Module Procedures
new_RDMAReference
Module Procedures
private function new_RDMAReference(type_kind, msize_word, comm, rank, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer(kind=INT64), intent(in) :: msize_word
integer, intent(in) :: comm
integer, intent(in) :: rank
integer, intent(out), optional :: rc
Return Value type(RDMAReference)
Call graph
rdmareference calls new_rdmareference
new_rdmareference calls mpi_comm_dup, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize