READ_PARALLEL – MAPL
READ_PARALLEL Interface
12 statements
Source File
public interface READ_PARALLEL
Calls
Called by
Contents
Module Procedures
READ_PARALLEL_STRING_0 READ_PARALLEL_I4_0 READ_PARALLEL_I4_1 READ_PARALLEL_I4_2 READ_PARALLEL_R4_0 READ_PARALLEL_R4_1 READ_PARALLEL_R4_2 READ_PARALLEL_R8_0 READ_PARALLEL_R8_1 READ_PARALLEL_R8_2
Module Procedures
private subroutine READ_PARALLEL_STRING_0(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
character(len=*), intent(out) :: data
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_I4_0(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(out) :: data
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_I4_1(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(out) :: data(:)
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_I4_2(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(out) :: data(:,:)
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_R4_0(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(out) :: data
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_R4_1(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(out) :: data(:)
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_R4_2(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(out) :: data(:,:)
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_R8_0(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(out) :: data
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_R8_1(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(out) :: data(:)
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
private subroutine READ_PARALLEL_R8_2(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R8), intent(out) :: data(:,:)
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Call graph
read_parallel calls read_parallel_i4_0, read_parallel_i4_1, read_parallel_i4_2, read_parallel_r4_0, read_parallel_r4_1, read_parallel_r4_2, read_parallel_r8_0, read_parallel_r8_1, read_parallel_r8_2, read_parallel_string_0
read_parallel_i4_0 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_i4_1 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_i4_2 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_r4_0 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_r4_1 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_r4_2 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_r8_0 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_r8_1 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_r8_2 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify, records
read_parallel_string_0 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify
mapl_fieldread calls read_parallel, mapl_varread
mapl_gridcoordadjustfromfile calls read_parallel
mapl_locstreamcreatefromfile calls read_parallel
mapl_readforcingx calls read_parallel
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
mapl_varread calls mapl_fieldread, mapl_bundleread, mapl_statevarread, mapl_varread_r4_2d, mapl_varread_r4_3d, mapl_varread_r4_4d, mapl_varread_r8_2d, mapl_varread_r8_3d, mapl_varread_r8_4d
mapl_bundleread calls mapl_fieldread
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_statevarread calls mapl_fieldread, mapl_bundleread
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
initialize calls mapl_locstreamcreate
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
readrestart calls mapl_varread
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_staterefresh calls mapl_esmfstatereadfromfile