RegridderSpecRouteHandleMap – MAPL
RegridderSpecRouteHandleMap Interface
4 statements
Source File
public interface RegridderSpecRouteHandleMap
Calls
Module Procedures
private function m_new_map_empty() result(m)
Arguments
None
Return Value type(RegridderSpecRouteHandleMap)
private function m_new_map_from_pair_array(pairs) result(m)
Arguments
Type Intent Optional Attributes Name
type(pair), intent(in) :: pairs(:)
Return Value type(RegridderSpecRouteHandleMap)
Call graph
regridderspecroutehandlemap calls m_new_map_empty, m_new_map_from_pair_array
m_new_map_from_pair_array calls insert
m_insert_pair calls s_insert