ReplaceMetadataMessage – MAPL
ReplaceMetadataMessage Interface
3 statements
Source File
public interface ReplaceMetadataMessage
Calls
Module Procedures
private function new_ReplaceMetadataMessage(collection_id, fmd, rc) result(message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: collection_id
type(FileMetadata), intent(in) :: fmd
integer, intent(out), optional :: rc
Return Value type(ReplaceMetadataMessage)
Call graph
replacemetadatamessage calls new_replacemetadatamessage
new_replacemetadatamessage calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize