samplerHQ – MAPL
samplerHQ Interface
3 statements
Source File
public interface samplerHQ
Calls
Module Procedures
private function new_samplerHQ(clock, key, config, rc) result(hq)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: clock
character(len=*), intent(in) :: key
type(ESMF_Config), intent(inout) :: config
integer, intent(out), optional :: rc
Return Value type(samplerHQ)
Call graph
samplerhq calls new_samplerhq
new_samplerhq calls ESMF_AlarmCreate, ESMF_ClockGet, ESMF_ConfigGetAttribute, ESMF_TimeIntervalSet, hms_2_s, mapl_assert, mapl_return, mapl_verify
hms_2_s calls hms_2_s
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize