serialize_intrinsic – MAPL
serialize_intrinsic Interface
13 statements
Source File
public interface serialize_intrinsic
Calls
Called by
Module Procedures
private function serialize_string(str, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_int32_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_int32_1d(array, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_int64_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_int64_1d(array, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_real32_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_real32_1d(array, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_real64_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_real64_1d(array, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_logical_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
private function serialize_logical_1d(array, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
Call graph
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
serialize calls serialize_intrinsic
stringattributemap_serialize calls serialize_intrinsic
stringintegermap_serialize calls serialize_intrinsic
stringunlimitedentitymap_serialize calls serialize_intrinsic
stringvariablemap_serialize calls serialize_intrinsic
stringvector_serialize calls serialize_intrinsic
test_serialize_int64_array calls serialize_intrinsic
test_serialize_int64_scalar calls serialize_intrinsic
test_serialize_int_array calls serialize_intrinsic
test_serialize_int_scalar calls serialize_intrinsic
test_serialize_logical_array calls serialize_intrinsic
test_serialize_logical_scalar calls serialize_intrinsic
test_serialize_real_array calls serialize_intrinsic
test_serialize_real_scalar calls serialize_intrinsic
test_serialize_string calls serialize_intrinsic