serialize_buffer_length – MAPL
serialize_buffer_length Interface
13 statements
Source File
public interface serialize_buffer_length
Calls
Called by
pFIO_AbstractCollectiveDataMessageMod::AbstractCollectiveDataMessage%deserialize w pFIO_UtilitiesMod::serialize_buffer_length
w
pFIO_AbstractCollectiveDataMessageMod::AbstractCollectiveDataMessage%get_length w
w
pFIO_AbstractDataMessageMod::AbstractDataMessage%deserialize w
w
pFIO_AbstractDataMessageMod::AbstractDataMessage%get_length w
w
pFIO_AddExtCollectionMessageMod::AddExtCollectionMessage%get_length w
w
pFIO_CoordinateVariableMod::CoordinateVariable%serialize w
w
pFIO_CoordinateVariableMod::CoordinateVariable_deserialize w
w
pFIO_FileMetadataMod::FileMetadata%serialize w
w
pFIO_FileMetadataMod::FileMetadata_deserialize w
w
pFIO_ForwardDataMessageMod::ForwardDataMessage%deserialize w
w
pFIO_ForwardDataMessageMod::ForwardDataMessage%get_length w
w
pFIO_ModifyMetadataMessageMod::ModifyMetadataMessage%deserialize w
w
pFIO_ModifyMetadataMessageMod::ModifyMetadataMessage%get_length w
w
pFIO_ReplaceMetadataMessageMod::ReplaceMetadataMessage%deserialize w
w
pFIO_ReplaceMetadataMessageMod::ReplaceMetadataMessage%get_length w
w
pFIO_StringAttributeMapUtilMod::StringAttributeMap_deserialize w
w
pFIO_StringAttributeMapUtilMod::StringAttributeMap_serialize w
w
pFIO_StringIntegerMapUtilMod::StringIntegerMap_deserialize w
w
pFIO_StringIntegerMapUtilMod::StringIntegerMap_serialize w
w
pFIO_StringUnlimitedEntityMapUtilMod::StringUnlimitedEntityMap_deserialize w
w
pFIO_StringUnlimitedEntityMapUtilMod::StringUnlimitedEntityMap_serialize w
w
pFIO_StringVariableMapUtilMod::StringVariableMap_deserialize w
w
pFIO_StringVariableMapUtilMod::StringVariableMap_serialize w
w
pFIO_StringVectorUtilMod::StringVector_deserialize w
w
pFIO_StringVectorUtilMod::StringVector_serialize w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity%serialize w
w
pFIO_UnlimitedEntityMod::UnlimitedEntity_deserialize w
w
pFIO_VariableMod::Variable%serialize w
w
pFIO_VariableMod::Variable_deserialize w
w
test_pFIO_Utilities::test_serialize_buffer_length_int64_0d w
w
test_pFIO_Utilities::test_serialize_buffer_length_int64_1d w
w
test_pFIO_Utilities::test_serialize_buffer_length_int_0d w
w
test_pFIO_Utilities::test_serialize_buffer_length_int_1d w
w
test_pFIO_Utilities::test_serialize_buffer_length_logical_0d w
w
test_pFIO_Utilities::test_serialize_buffer_length_logical_1d w
w
test_pFIO_Utilities::test_serialize_buffer_length_real_0d w
w
test_pFIO_Utilities::test_serialize_buffer_length_real_1d w
w
test_pFIO_Utilities::test_serialize_buffer_length_string w
w
Module Procedures
private function serialize_buffer_length_string(str, rc) result(length)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_int32_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_int32_1d(array, rc) result(length)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_int64_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_int64_1d(array, rc) result(length)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_real32_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_real32_1d(array, rc) result(length)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_real64_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_real64_1d(array, rc) result(length)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_logical_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
private function serialize_buffer_length_logical_1d(array, rc) result(length)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer
Call graph
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize