ServerThread – MAPL
ServerThread Interface
3 statements
Source File
public interface ServerThread
Calls
Module Procedures
private function new_ServerThread(sckt, server, rc) result(s)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), target :: sckt
class(AbstractServer), intent(in), optional, target :: server
integer, intent(out), optional :: rc
Return Value type(ServerThread)
Call graph
serverthread calls new_serverthread
new_serverthread calls mapl_return, mapl_verify, set_connection
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_connection calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize