set_with_default – MAPL
set_with_default Interface
7 statements
Source File
private interface set_with_default
Calls
Called by
Module Procedures
private elemental subroutine set_with_default_integer(to, from, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: to
integer, intent(in), optional :: from
integer, intent(in) :: default
private elemental subroutine set_with_default_real(to, from, default)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: to
real, intent(in), optional :: from
real, intent(in) :: default
private elemental subroutine set_with_default_real64(to, from, default)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out) :: to
real(kind=REAL64), intent(in), optional :: from
real(kind=REAL64), intent(in) :: default
private subroutine set_with_default_character(to, from, default)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(out), allocatable :: to
character(len=*), intent(in), optional :: from
character(len=*), intent(in) :: default
private elemental subroutine set_with_default_bounds(to, from, default)
Arguments
Type Intent Optional Attributes Name
type(RealMinMax), intent(out) :: to
type(RealMinMax), intent(in), optional :: from
type(RealMinMax), intent(in) :: default
Call graph
set_with_default calls set_with_default_bounds, set_with_default_character, set_with_default_integer, set_with_default_real, set_with_default_real64
swathgridfactory_from_parameters calls set_with_default
swathgridfactory calls swathgridfactory_from_parameters