set_ESMF_TimeInterval – MAPL
set_ESMF_TimeInterval Interface
3 statements
Source File
public interface set_ESMF_TimeInterval
Calls
Called by
Module Procedures
public subroutine set_ESMF_TimeInterval_from_datetime_duration(interval, duration, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TimeInterval), intent(inout) :: interval
class(datetime_duration), intent(in) :: duration
integer, intent(out), optional :: rc
Call graph
set_esmf_timeinterval calls set_esmf_timeinterval_from_datetime_duration
set_esmf_timeinterval_from_datetime_duration calls ESMF_TimeIntervalSet, day_is_set, hour_is_real, hour_is_set, minute_is_real, minute_is_set, month_is_set, mapl_return, mapl_verify, second_is_real, second_is_set, year_is_set
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_esmf_time_from_netcdf_datetime_integer calls set_esmf_timeinterval
get_esmf_time_from_netcdf_datetime_real calls set_esmf_timeinterval
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_real_to_esmf calls convert_netcdf_datetime_to_esmf