set_with_default – MAPL
set_with_default Interface
4 statements
Source File
private interface set_with_default
Calls
Called by
Module Procedures
private elemental subroutine set_with_default_integer(to, from, default)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: to
integer, intent(in), optional :: from
integer, intent(in) :: default
private subroutine set_with_default_character(to, from, default)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(out), allocatable :: to
character(len=*), intent(in), optional :: from
character(len=*), intent(in) :: default
Call graph
set_with_default calls set_with_default_character, set_with_default_integer
tripolargridfactory_from_parameters calls set_with_default
tripolargridfactory calls tripolargridfactory_from_parameters