shmat – MAPL
shmat Interface
32 statements
Source File
interface
Called by
private module function shmat(shmid, shmaddr, shmflg) bind(c, name="shmat")
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: shmid
type(c_ptr), value :: shmaddr
integer(kind=c_int), value :: shmflg
Return Value type(c_ptr)
Call graph
getsharedmemory calls shmat, getsharedmemory
mapl_allocnodearray_1di4 calls getsharedmemory
mapl_allocnodearray_1dl4 calls getsharedmemory
mapl_allocnodearray_1dr4 calls getsharedmemory
mapl_allocnodearray_1dr8 calls getsharedmemory
mapl_allocnodearray_2di4 calls getsharedmemory
mapl_allocnodearray_2dr4 calls getsharedmemory
mapl_allocnodearray_2dr8 calls getsharedmemory
mapl_allocnodearray_3di4 calls getsharedmemory
mapl_allocnodearray_3dr4 calls getsharedmemory
mapl_allocnodearray_3dr8 calls getsharedmemory
mapl_allocnodearray_4di4 calls getsharedmemory
mapl_allocnodearray_4dr4 calls getsharedmemory
mapl_allocnodearray_4dr8 calls getsharedmemory
mapl_allocnodearray_5dr8 calls getsharedmemory
mapl_allocnodearray_6dr8 calls getsharedmemory
mapl_allocnodearray_tiling calls getsharedmemory