shmdt – MAPL
shmdt Interface
36 statements
Source File
interface
Called by
private module function shmdt(shmaddr) bind(c, name="shmdt")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: shmaddr
Return Value integer(kind=c_int)
Call graph
releasesharedmemory calls shmdt, releasesharedmemory
mapl_finalizeshmem calls shmdt, mapl_finalizeshmem
mapl_deallocnodearray_4dr4 calls releasesharedmemory
mapl_deallocnodearray_5dr8 calls releasesharedmemory
finalize_gc calls mapl_finalizeshmem
mapl_deallocnodearray_6dr8 calls releasesharedmemory
mapl_deallocnodearray_4di4 calls releasesharedmemory
mapl_deallocnodearray_tiling calls releasesharedmemory
mapl_deallocnodearray_1di4 calls releasesharedmemory
mapl_deallocnodearray_1dl4 calls releasesharedmemory
mapl_deallocnodearray_2di4 calls releasesharedmemory
mapl_deallocnodearray_3di4 calls releasesharedmemory
mapl_deallocnodearray_1dr4 calls releasesharedmemory
mapl_deallocnodearray_2dr4 calls releasesharedmemory
mapl_deallocnodearray_3dr4 calls releasesharedmemory
mapl_deallocnodearray_1dr8 calls releasesharedmemory
mapl_deallocnodearray_2dr8 calls releasesharedmemory
mapl_deallocnodearray_3dr8 calls releasesharedmemory
mapl_deallocnodearray_4dr8 calls releasesharedmemory