ShmemReference – MAPL
ShmemReference Interface
3 statements
Source File
public interface ShmemReference
Calls
Contents
Module Procedures
new_ShmemReference
Module Procedures
private function new_ShmemReference(type_kind, msize_word, InNode_Comm, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer(kind=INT64), intent(in) :: msize_word
integer, intent(in) :: InNode_Comm
integer, intent(out), optional :: rc
Return Value type(ShmemReference)
Call graph
shmemreference calls new_shmemreference
new_shmemreference calls mpi_comm_dup, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize