SimpleCommSplitter – MAPL
SimpleCommSplitter Interface
4 statements
Source File
public interface SimpleCommSplitter
Calls
Called by
Contents
Module Procedures
new_SimpleCommSplitter ensemble_comm_splitter
Module Procedures
private function new_SimpleCommSplitter(communicator, unusable, base_name) result(splitter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: communicator
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: base_name
Return Value type(SimpleCommSplitter)
private function ensemble_comm_splitter(communicator, n_members, npes_member, unusable, isolate_nodes, base_name) result(splitter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: communicator
integer, intent(in) :: n_members
integer, intent(in) :: npes_member
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: isolate_nodes
character(len=*), intent(in), optional :: base_name
Return Value type(SimpleCommSplitter)
Call graph
simplecommsplitter calls ensemble_comm_splitter, new_simplecommsplitter
ensemble_comm_splitter calls simplecommsplitter, add_group
new_simplecommsplitter calls set_shared_communicator