sort_multi_arrays_by_time – MAPL
sort_multi_arrays_by_time Interface
4 statements
Source File
public interface sort_multi_arrays_by_time
Calls
Module Procedures
public subroutine sort_three_arrays_by_time(U, V, T, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(inout) :: U(:)
real(kind=ESMF_KIND_R8), intent(inout) :: V(:)
real(kind=ESMF_KIND_R8), intent(inout) :: T(:)
integer, intent(out), optional :: rc
public subroutine sort_four_arrays_by_time(U, V, T, ID, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8) :: U(:)
real(kind=ESMF_KIND_R8) :: V(:)
real(kind=ESMF_KIND_R8) :: T(:)
integer :: ID(:)
integer, intent(out), optional :: rc
Call graph
sort_multi_arrays_by_time calls sort_four_arrays_by_time, sort_three_arrays_by_time
sort_four_arrays_by_time calls mapl_assert, mapl_sort, mapl_return
sort_three_arrays_by_time calls mapl_assert, mapl_sort, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_sort calls sort1ld, sort1lr, sort1ls, sort1sd, sort1sr, sort1ss, sort2al, sort2as, sort2ld, sort2lr, sort2ls, sort2sd, sort2sr, sort2ss
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
sort1ld calls qsortl
sort1lr calls qsortl
sort1ls calls qsortl
sort1sd calls qsorts
sort1sr calls qsorts
sort1ss calls qsorts
sort2al calls mapl_assert, qsortl
sort2as calls mapl_assert, qsorts
sort2ld calls mapl_assert, qsortl
sort2lr calls mapl_assert, qsortl
sort2ls calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort2sr calls mapl_assert, qsorts
sort2ss calls mapl_assert, qsorts