StageDataMessage – MAPL
StageDataMessage Interface
3 statements
Source File
public interface StageDataMessage
Calls
Module Procedures
private function new_StageDataMessage(request_id, file_md_id, file_name, var_name, data_reference, unusable, start) result(message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: request_id
integer, intent(in) :: file_md_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
Return Value type(StageDataMessage)
Call graph
stagedatamessage calls new_stagedatamessage
new_stagedatamessage calls init
init calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception