StateFilterItem – MAPL
StateFilterItem Interface
4 statements
Source File
public interface StateFilterItem
Calls
Called by
Module Procedures
private subroutine StateFilter_R4_2D(state, config, itemName, array, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: itemName
real(kind=REAL32), intent(out), allocatable :: array(:,:)
integer, intent(out), optional :: rc
private subroutine StateFilter_R4_3D(state, config, itemName, array, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: itemName
real(kind=REAL32), intent(out), allocatable :: array(:,:,:)
integer, intent(out), optional :: rc
Call graph
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
statefilter_r4_2d calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, esmf_fielddestroy, esmf_fieldget, esmf_stateget, fieldclone, mapl_assert, evaluate_mask, mapl_return, mapl_stateeval, mapl_verify, substitute_name
statefilter_r4_3d calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, esmf_fielddestroy, esmf_fieldget, esmf_stateget, fieldclone, mapl_assert, evaluate_mask, mapl_return, mapl_stateeval, mapl_verify, substitute_name
fieldclone calls clone
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
evaluate_mask calls mapl_return, mapl_verify, evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
mapl_return calls get_error_message, mapl_throw_exception
mapl_stateeval calls esmf_stateget, mapl_assert, mapl_verify, fieldsarebroadcastconformable, bytecode_dealloc, checksyntax, evalf, parsef
mapl_verify calls mapl_throw_exception
substitute_name calls mapl_assert, mapl_return
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem