StationSampler – MAPL
StationSampler Interface
3 statements
Source File
public interface StationSampler
Calls
Module Procedures
private function new_StationSampler_readfile(filename, nskip_line, rc) result(sampler)
write(6,) ‘i=’, i write(6,) ‘line=’, trim(line)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer, intent(in), optional :: nskip_line
integer, intent(out), optional :: rc
Return Value type(StationSampler)
Call graph
stationsampler calls new_stationsampler_readfile
new_stationsampler_readfile calls mapl_assert, get_logger, count_substring, create_locstream, csv_read_line_with_ch_i_r, debug, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
count_substring calls mapl_return
create_locstream calls mapl_return, mapl_verify, ESMF_LocStreamAddKey, ESMF_LocStreamCreate, ESMF_VMGet, ESMF_VMGetCurrent
csv_read_line_with_ch_i_r calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize