StateMask – MAPL
StateMask Interface
3 statements
Source File
public interface StateMask
Calls
Module Procedures
private function new_StateMask(mask_expression, rc) result(new_mask)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: mask_expression
integer, intent(out), optional :: rc
Return Value type(StateMask)
Call graph
statemask calls new_statemask
new_statemask calls ESMF_UtilStringLowerCase, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize