StringCompositeMap – MAPL
StringCompositeMap Interface
4 statements
Source File
public interface StringCompositeMap
Calls
Module Procedures
private function m_new_map_empty() result(m)
Arguments
None
Return Value type(StringCompositeMap)
private function m_new_map_from_pair_array(pairs) result(m)
Arguments
Type Intent Optional Attributes Name
type(StringCompositePair), intent(in) :: pairs(:)
Return Value type(StringCompositeMap)
Call graph
stringcompositemap calls m_new_map_empty, m_new_map_from_pair_array
m_new_map_from_pair_array calls insert
m_insert_pair calls s_insert