SwathGridFactory – MAPL
SwathGridFactory Interface
3 statements
Source File
public interface SwathGridFactory
Calls
Module Procedures
private function SwathGridFactory_from_parameters(unusable, grid_name, im_world, jm_world, lm, nx, ny, ims, jms, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(in), optional :: ims(:)
integer, intent(in), optional :: jms(:)
integer, intent(out), optional :: rc
Return Value type(SwathGridFactory)
Call graph
swathgridfactory calls swathgridfactory_from_parameters
swathgridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_bounds, set_with_default_character, set_with_default_integer, set_with_default_real64, set_with_default_real
check_and_fill_consistency calls mapl_return, mapl_verify, check_decomposition, generate_newnxy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
check_decomposition calls mapl_return
generate_newnxy calls mapl_return, mapl_decomposedim, generate_new_decomp
get_error_message calls at, insert
mapl_throw_exception calls initialize