timeData – MAPL
timeData Interface
3 statements
Source File
public interface timeData
Calls
Contents
Module Procedures
new_time_data
Module Procedures
private function new_time_data(clock, ntime, frequency, offset, funits, integer_time, rc) result(tData)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(inout) :: clock
integer, intent(in) :: ntime
integer, intent(in) :: frequency
type(ESMF_TimeInterval) :: offset
character(len=*), intent(in), optional :: funits
logical, intent(in), optional :: integer_time
integer, intent(out), optional :: rc
Return Value type(timeData)
Call graph
timedata calls new_time_data
new_time_data calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize