time_fields – MAPL
time_fields Interface
5 statements
Source File
public interface time_fields
Calls
Called by
Contents
Module Procedures
construct_time_fields_default construct_time_fields_string construct_time_fields_null
Module Procedures
public pure function construct_time_fields_default(hour, minute, second, millisecond, timezone_offset) result(fields)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: hour
integer, intent(in) :: minute
integer, intent(in) :: second
integer, intent(in) :: millisecond
integer, intent(in) :: timezone_offset
Return Value type(time_fields)
public pure function construct_time_fields_string(time_string, delimiter) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: time_string
character(len=*), intent(in) :: delimiter
Return Value type(time_fields)
public pure function construct_time_fields_null() result(fields)
Arguments
None
Return Value type(time_fields)
Call graph
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_is_valid_time calls time_fields
test_parse_time calls parse_time