TimeProfiler – MAPL
TimeProfiler Interface
3 statements
Source File
public interface TimeProfiler
Calls
Module Procedures
private function new_TimeProfiler(name, comm_world) result(prof)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(in), optional :: comm_world
Return Value type(TimeProfiler), target
Call graph
timeprofiler calls new_timeprofiler
new_timeprofiler calls make_meter, set_comm_world, set_node