TripolarGridFactory – MAPL
TripolarGridFactory Interface
3 statements
Source File
public interface TripolarGridFactory
Calls
Module Procedures
private function TripolarGridFactory_from_parameters(unusable, grid_file_name, grid_name, im_world, jm_world, lm, nx, ny, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: grid_file_name
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(out), optional :: rc
Return Value type(TripolarGridFactory)
Call graph
tripolargridfactory calls tripolargridfactory_from_parameters
tripolargridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_character, set_with_default_integer
check_and_fill_consistency calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize