UDSystem – MAPL
UDSystem Interface
3 statements
Source File
public interface UDSystem
Calls
Module Procedures
private function construct_system(path, encoding) result(instance)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: path
integer(kind=ut_encoding), intent(in), optional :: encoding
Return Value type(UDSystem)
Call graph
udsystem calls construct_system
construct_system calls ut_free_system, read_xml, set_cptr, success
read_xml calls ut_get_status, ut_read_xml_cptr, cstring