UDUnit – MAPL
UDUnit Interface
3 statements
Source File
public interface UDUnit
Calls
Module Procedures
private function construct_unit(identifier) result(instance)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: identifier
Return Value type(UDUnit)
Call graph
udunit calls construct_unit
construct_unit calls ut_free, ut_get_status, ut_parse, cstring, get_cptr, instance_is_uninitialized, set_cptr, success
instance_is_uninitialized calls is_free