UngriddedDimSpec – MAPL
UngriddedDimSpec Interface
5 statements
Source File
public interface UngriddedDimSpec
Calls
Called by
Contents
Module Procedures
new_UngriddedDimSpec_extent new_UngriddedDimSpec_name_and_coords new_UngriddedDimSpec_name_units_and_coords
Module Procedures
private pure function new_UngriddedDimSpec_extent(extent) result(spec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: extent
Return Value type(UngriddedDimSpec)
private pure function new_UngriddedDimSpec_name_and_coords(name, coordinates) result(spec)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
real, intent(in) :: coordinates(:)
Return Value type(UngriddedDimSpec)
private pure function new_UngriddedDimSpec_name_units_and_coords(name, units, coordinates) result(spec)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=*), intent(in) :: units
real, intent(in) :: coordinates(:)
Return Value type(UngriddedDimSpec)
Call graph
ungriddeddimspec calls new_ungriddeddimspec_extent, new_ungriddeddimspec_name_and_coords, new_ungriddeddimspec_name_units_and_coords
new_ungriddeddimspec_extent calls ungriddeddimspec, default_coords
new_ungriddeddimspec_name_and_coords calls ungriddeddimspec