UnlimitedEntity – MAPL
UnlimitedEntity Interface
9 statements
Source File
public interface UnlimitedEntity
Calls
Called by
Contents
Module Procedures
new_UnlimitedEntity_empty new_UnlimitedEntity_0d new_UnlimitedEntity_1d new_UnlimitedEntity_2d new_UnlimitedEntity_3d new_UnlimitedEntity_4d new_UnlimitedEntity_5d
Module Procedures
private function new_UnlimitedEntity_empty() result(attr)
Arguments
None
Return Value type(UnlimitedEntity)
private function new_UnlimitedEntity_0d(value, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: value
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
private function new_UnlimitedEntity_1d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
private function new_UnlimitedEntity_2d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:,:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
private function new_UnlimitedEntity_3d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:,:,:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
private function new_UnlimitedEntity_4d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
private function new_UnlimitedEntity_5d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:,:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
Call graph
unlimitedentity calls new_unlimitedentity_0d, new_unlimitedentity_1d, new_unlimitedentity_2d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_5d, new_unlimitedentity_empty
new_unlimitedentity_0d calls mapl_return
new_unlimitedentity_1d calls mapl_assert, mapl_return
new_unlimitedentity_2d calls unlimitedentity, mapl_assert, mapl_return
new_unlimitedentity_3d calls unlimitedentity, mapl_assert, mapl_return
new_unlimitedentity_4d calls unlimitedentity, mapl_assert, mapl_return
new_unlimitedentity_5d calls unlimitedentity, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
unlimitedentity_deserialize calls unlimitedentity
attribute_deserialize calls unlimitedentity_deserialize
stringunlimitedentitymap_deserialize calls unlimitedentity_deserialize
test_serialize calls unlimitedentity_deserialize, attribute_deserialize
stringattributemap_deserialize calls attribute_deserialize
main calls stringattributemap_deserialize