ut_get_status – MAPL
ut_get_status Interface
61 statements
Source File
interface
Called by
public function ut_get_status() bind(c, name='ut_get_status')
Arguments
None
Return Value integer(kind=ut_status)
Call graph
are_convertible_udunit calls ut_get_status
construct_converter calls ut_get_status, are_convertible
construct_unit calls ut_get_status
read_xml calls ut_get_status
are_convertible calls are_convertible_udunit, are_convertible_str
converter calls construct_converter
udunit calls construct_unit
are_convertible_str calls are_convertible_udunit
construct_system calls read_xml
test_read_xml_nopath calls read_xml
udsystem calls construct_system
test_are_convertible calls are_convertible
test_are_not_convertible calls are_convertible