VarConnVector – MAPL
VarConnVector Interface
8 statements
Source File
public interface VarConnVector
Calls
Contents
Module Procedures
vector_new_vector_empty vector_new_vector_fill_size_kind vector_new_vector_fill_default vector_new_vector_range vector_new_vector_copy vector_new_vector_initializer_list
Module Procedures
private function vector_new_vector_empty() result(v)
Arguments
None
Return Value type(VarConnVector)
private function vector_new_vector_fill_size_kind(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer(kind=GFTL_SIZE_KIND), intent(in) :: n
type(VarConnType), intent(in), optional :: value
Return Value type(VarConnVector)
private function vector_new_vector_fill_default(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(VarConnType), intent(in), optional :: value
Return Value type(VarConnVector)
private function vector_new_vector_range(first, last) result(v)
Arguments
Type Intent Optional Attributes Name
type(VarConnVectorIterator), intent(in) :: first
type(VarConnVectorIterator), intent(in) :: last
Return Value type(VarConnVector)
private function vector_new_vector_copy(x) result(v)
Arguments
Type Intent Optional Attributes Name
type(VarConnVector) :: x
Return Value type(VarConnVector)
private function vector_new_vector_initializer_list(il) result(v)
Arguments
Type Intent Optional Attributes Name
type(VarConnType), intent(in), dimension(:) :: il
Return Value type(VarConnVector)
Call graph
varconnvector calls vector_new_vector_copy, vector_new_vector_empty, vector_new_vector_fill_default, vector_new_vector_fill_size_kind, vector_new_vector_initializer_list, vector_new_vector_range
vector_new_vector_copy calls elements, resize
vector_new_vector_fill_default calls resize
vector_new_vector_fill_size_kind calls resize
vector_new_vector_initializer_list calls resize
vector_new_vector_range calls of, push_back