Variable – MAPL
Variable Interface
3 statements
Source File
public interface Variable
Calls
Called by
Contents
Module Procedures
new_Variable
Module Procedures
private function new_Variable(unusable, type, dimensions, chunksizes, const_value, deflation, quantize_algorithm, quantize_level, rc) result(var)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: type
character(len=*), intent(in), optional :: dimensions
integer, intent(in), optional :: chunksizes(:)
type(UnlimitedEntity), intent(in), optional :: const_value
integer, intent(in), optional :: deflation
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(out), optional :: rc
Return Value type(Variable)
Call graph
variable calls new_variable
new_variable calls mapl_return, stringvector
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
variable_deserialize calls variable
stringvariablemap_deserialize calls variable_deserialize
test_serialize calls variable_deserialize
deserialize calls stringvariablemap_deserialize