VarspecDescription – MAPL
VarspecDescription Interface
3 statements
Source File
public interface VarspecDescription
Calls
Module Procedures
private function new_VarspecDescriptionFromConfig(cf, nwords, rc) result(VarspecDescr)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: cf
integer, intent(in) :: nwords
integer, intent(out), optional :: rc
Return Value type(VarspecDescription)
Call graph
varspecdescription calls new_varspecdescriptionfromconfig
new_varspecdescriptionfromconfig calls ESMF_ConfigGetAttribute, at, push_back