verticalData – MAPL
verticalData Interface
3 statements
Source File
public interface verticalData
Calls
Contents
Module Procedures
newVerticalData
Module Procedures
private function newVerticalData(levels, vcoord, vscale, vunit, positive, long_name, standard_name, force_no_regrid, rc) result(vData)
Arguments
Type Intent Optional Attributes Name
real, intent(in), optional, pointer :: levels(:)
character(len=*), intent(in), optional :: vcoord
real, intent(in), optional :: vscale
character(len=*), intent(in), optional :: vunit
character(len=*), intent(in), optional :: positive
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: standard_name
logical, intent(in), optional :: force_no_regrid
integer, intent(out), optional :: rc
Return Value type(verticalData)
Call graph
verticaldata calls newverticaldata
newverticaldata calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize