VerticalCoordinate – MAPL
VerticalCoordinate Interface
3 statements
Source File
public interface VerticalCoordinate
Calls
Module Procedures
private function new_verticalCoordinate(metadata, var_name, rc) result(vertical_coord)
Arguments
Type Intent Optional Attributes Name
type(FileMetadataUtils), intent(in) :: metadata
character(len=*), intent(in) :: var_name
integer, intent(out), optional :: rc
Return Value type(VerticalCoordinate)
Call graph
verticalcoordinate calls new_verticalcoordinate
new_verticalcoordinate calls begin, get, mapl_assert, next, get_var, detect_cf_vertical_coord_var, get_attribute_string, get_coordinate_variable, get_coords, get_dimensions, get_source_file, get_variable, has_variable, is_attribute_present, mapl_return, mapl_verify, parse_formula_terms, safe_are_convertible