wrapArray – MAPL
wrapArray Interface
7 statements
Source File
public interface wrapArray
Calls
Called by
Module Procedures
private function wrap1d(array) result(wrapper)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:)
Return Value type(WrapArray1d)
private function wrap2d(array) result(wrapper)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:,:)
Return Value type(WrapArray2d)
private function wrap3d(array) result(wrapper)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:,:,:)
Return Value type(WrapArray3d)
private function wrap4d(array) result(wrapper)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:,:,:,:)
Return Value type(WrapArray4d)
private function wrap5d(array) result(wrapper)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:,:,:,:,:)
Return Value type(WrapArray5d)
Call graph
wraparray calls wrap1d, wrap2d, wrap3d, wrap4d, wrap5d
set calls wraparray
updatebrackettime calls wraparray
create_subobjects calls set
mapl_gridcreate calls set
run_ calls updatebrackettime
activate_threading calls create_subobjects
initialize_ calls mapl_gridcreate
omp_driver calls activate_threading