WRITE_PARALLEL – MAPL
WRITE_PARALLEL Interface
9 statements
Source File
public interface WRITE_PARALLEL
Calls
Called by
Contents
Module Procedures
WRITE_PARALLEL_I4_0 WRITE_PARALLEL_I4_1 WRITE_PARALLEL_R4_0 WRITE_PARALLEL_R4_1 WRITE_PARALLEL_R8_0 WRITE_PARALLEL_R8_1 WRITE_PARALLEL_STRING_0
Module Procedures
private subroutine WRITE_PARALLEL_I4_0(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(in) :: data
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
private subroutine WRITE_PARALLEL_I4_1(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(in) :: data(:)
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
private subroutine WRITE_PARALLEL_R4_0(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: data
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
private subroutine WRITE_PARALLEL_R4_1(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: data(:)
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
private subroutine WRITE_PARALLEL_R8_0(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: data
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
private subroutine WRITE_PARALLEL_R8_1(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: data(:)
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
private subroutine WRITE_PARALLEL_STRING_0(data, UNIT, ARRDES, format, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: data
integer, intent(in), optional :: UNIT
type(ArrDescr), intent(inout), optional :: ARRDES
character(len=*), intent(in), optional :: format
integer, intent(out), optional :: RC
Call graph
write_parallel calls write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r4_1, write_parallel_r8_0, write_parallel_r8_1, write_parallel_string_0
write_parallel_i4_0 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, mapl_return, mapl_verify, records
write_parallel_i4_1 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, mapl_return, mapl_verify, records
write_parallel_r4_0 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, mapl_return, mapl_verify, records
write_parallel_r4_1 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, mapl_return, mapl_verify, records
write_parallel_r8_0 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, mapl_return, mapl_verify, records
write_parallel_r8_1 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, mapl_return, mapl_verify, records
write_parallel_string_0 calls mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
alloc_ calls mapl_assert, dealloc_, mapl_return, mapl_verify
dealloc_ calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
finalize calls write_parallel
initialize calls write_parallel
mapl_esmfstatereadfromfile calls write_parallel
mapl_esmfstatewritetofile calls write_parallel
mapl_fieldwrite calls write_parallel
mapl_genericconncheck calls write_parallel
mapl_gridcompgetfriendlies0 calls write_parallel
mapl_memutilswritecomm calls write_parallel
mapl_setvarspecforcc calls write_parallel
mapl_statecreatefromspecnew calls write_parallel
mapl_stateprintspec calls write_parallel
mapl_stateprintspeccsv calls write_parallel
mapl_statevarreadncpar calls write_parallel
mapl_wirecomponent calls write_parallel
readrestart calls write_parallel
run calls write_parallel
solar_1d calls write_parallel
solar_2d calls write_parallel