XYGridFactory – MAPL
XYGridFactory Interface
3 statements
Source File
public interface XYGridFactory
Calls
Contents
Module Procedures
XYGridFactory_from_parameters
Module Procedures
private function XYGridFactory_from_parameters(unusable, grid_file_name, grid_name, im_world, jm_world, lm, nx, ny, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: grid_file_name
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(out), optional :: rc
Return Value type(XYGridFactory)
Call graph
xygridfactory calls xygridfactory_from_parameters
xygridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_character, set_with_default_integer
check_and_fill_consistency calls mapl_return, mapl_verify, file_has_corners
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
file_has_corners calls mapl_return, mapl_verify, ESMF_VMBroadcast, ESMF_VMGetCurrent, mapl_am_i_root, nf90_inq_varid, nf90_open
get_error_message calls at
mapl_throw_exception calls initialize