---
CATEGORIES:
  - IMPORT
  - EXPORT
  - INTERNAL
DIMS_OPTIONS:
  z:
    name: MAPL_DimsVertOnly
    rank: 1
  xy:
    name: MAPL_DimsHorzOnly
    rank: 2
  xyz:
    name: MAPL_DimsHorzVert
    rank: 3
V_LOCATION:
  C: MAPL_VlocationCenter
  E: MAPL_VlocationEdge
  N: MAPL_VlocationNone
RESTART_OPTIONS:
  OPT: MAPL_RestartOptional
  SKIP: MAPL_RestartSkip
  REQ: MAPL_RestartRequired
  BOOT: MAPL_RestartBoot
  SKIPI: MAPL_RestartSkipInitial
ADD2EXPORT_OPTIONS:
  T: .true.
  F: .false.
OPTIONS:
  MANDATORY:
    SHORT_NAME:
      name: short_name
      emit: mangle_name
    NAME:
      name: short_name
      emit: mangle_name
    DIMS:
      name: dims
      emit: entry
    LONG_NAME:
      name: long_name
      emit: mangle_name
    LONG NAME:
      name: long_name
      emit: mangle_name
    UNITS:
      name: units
      emit: string
  OPTIONAL:
    ADD2EXPORT:
      name: add2export
      emit: entry
    ADDEXP:
      name: add2export
      emit: entry
    ATTR_INAMES:
      name: attr_inames
      emit: array
    ATTR_IVALUES:
      name: attr_ivalues
      emit: array
    ATTR_RNAMES:
      name: attr_rnames
      emit: array
    ATTR_RVALUES:
      name: attr_rvalues
      emit: array
    AVERAGING_INTERVAL: averaging_interval
    AVINT: averaging_interval
    DATATYPE: datatype
    DEFAULT: default
    FIELD_TYPE: field_type
    FRIENDLYTO:
      name: friendlyto
      emit: string
    FRIEND2:
      name: friendlyto
      emit: string
    HALOWIDTH: halowidth
    NUM_SUBTILES: num_subtitles
    NUMSUBS: num_subtitles
    PRECISION: precision
    PREC: precision
    REFRESH_INTERVAL: refresh_interval
    RESTART:
      name: restart
      emit: entry
    ROTATION: rotation
    STAGGERING: staggering
    UNGRIDDED_DIMS:
      name: ungridded_dims
      emit: array
    UNGRID:
      name: ungridded_dims
      emit: array
    UNGRIDDED:
      name: ungridded_dims
      emit: array
    UNGRIDDED_COORDS:
      name: ungridded_coords
      emit: array
    UNGRIDDED_NAME: ungridded_name
    UNGRIDDED_UNIT: ungridded_unit
    VLOCATION:
      name: vlocation
      emit: entry
    VLOC:
      name: vlocation
      emit: entry
  NONOUTPUT:
    CONDITION:
      name: condition
      emit: identity
    COND:
      name: condition
      emit: identity
    ALLOC:
      name: alloc
      emit: identity
    MANGLED_NAME:
      name: mangled_name
      emit: mangle_name
    INTERNAL_NAME:
      name: internal_name
      emit: internal_name
    RANK: rank
