#!/usr/bin/env python3
"""
MAPL_IncludeFiles_to_ACG.py

Converts MAPL include files generated by MAPL_GridCompSpecs_ACG.py back to ACG spec files.

Author: OpenCode and Darian Boggs
Date: 2026-05-26
"""

import argparse
import re
import sys
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Set
from collections import defaultdict

################################# CONSTANTS ####################################

SCHEMA_VERSION_DEFAULT = "2.0.0"
LOG_FILE_DEFAULT = "MAPL_IncludeFiles_to_ACG.log"
MISSING_VALUE = "@MISSING@"

# Reverse mappings from MAPL constants to abbreviations
DIMS_REVERSE_MAP = {
    'MAPL_DimsHorzOnly': 'xy',
    'MAPL_DimsHorzVert': 'xyz',
    'MAPL_DimsVertOnly': 'z'
}

VLOC_REVERSE_MAP = {
    'MAPL_VlocationNone': 'N',
    'MAPL_VlocationCenter': 'C',
    'MAPL_VlocationEdge': 'E'
}

RESTART_REVERSE_MAP = {
    'MAPL_RestartOptional': 'OPT',
    'MAPL_RestartSkip': 'SKIP',
    'MAPL_RestartRequired': 'REQ',
    'MAPL_RestartBoot': 'BOOT',
    'MAPL_RestartSkipInitial': 'SKIPI'
}

# Rank mapping for dimensions
DIMS_TO_RANK = {
    'xyz': 3,
    'xy': 2,
    'z': 1
}

# Mandatory columns (always present)
MANDATORY_COLUMNS_BASE = ['NAME', 'UNITS', 'DIMS', 'VLOC', 'LONG_NAME']

# All possible optional columns
OPTIONAL_COLUMNS = [
    'RESTART', 'COND', 'DATATYPE', 'DEFAULT', 'FRIENDLYTO', 
    'ADD2EXPORT', 'ALLOC', 'PRECISION', 'UNGRIDDED', 
    'UNGRIDDED_COORDS', 'UNGRIDDED_NAME', 'UNGRIDDED_UNIT',
    'HALOWIDTH', 'NUM_SUBTILES', 'AVERAGING_INTERVAL',
    'REFRESH_INTERVAL', 'ROTATION', 'STAGGERING', 'FIELD_TYPE',
    'ATTR_INAMES', 'ATTR_IVALUES', 'ATTR_RNAMES', 'ATTR_RVALUES',
    'DEPENDS_ON', 'DEPENDS_ON_CHILDREN'
]

# Map AddSpec parameter names to output column names
# Only include true aliases (where output differs from uppercase param name)
PARAM_TO_COLUMN = {
    'short_name': 'NAME',           # Convention: use NAME instead of SHORT_NAME
    'vlocation': 'VLOC',            # Abbreviation
    'ungridded_dims': 'UNGRIDDED',  # Abbreviation
    'num_subtitles': 'NUM_SUBTILES', # Typo fix: subtitles -> SUBTILES
    'condition': 'COND'             # Abbreviation (used in internal processing)
}

def param_to_column_name(param_name: str) -> str:
    """Convert parameter name to column name. Use exceptions dict or uppercase."""
    return PARAM_TO_COLUMN.get(param_name, param_name.upper())

################################### ENUMS ######################################

class FileType(Enum):
    DECLARE_POINTER = "declare_pointer"
    GET_POINTER = "get_pointer"
    ADD_IMPORT = "add_import"
    ADD_EXPORT = "add_export"
    ADD_INTERNAL = "add_internal"
    FORTRAN_SOURCE = "fortran_source"
    UNKNOWN = "unknown"

class Category(Enum):
    IMPORT = "IMPORT"
    EXPORT = "EXPORT"
    INTERNAL = "INTERNAL"

################################### LOGGER #####################################

class Logger:
    """Handles logging to file and console"""
    
    def __init__(self, log_path: Path, verbose: bool = True):
        self.log_path = log_path
        self.verbose = verbose
        self.log_file = open(log_path, 'w')
        self.error_count = 0
        self.warning_count = 0
        self.fatal_error = False
        self.closed = False
        
    def info(self, message: str):
        """Log INFO level message"""
        if not self.closed:
            self.log_file.write(f"INFO: {message}\n")
            self.log_file.flush()
        
    def warning(self, message: str):
        """Log WARNING level message"""
        self.warning_count += 1
        if not self.closed:
            self.log_file.write(f"WARNING: {message}\n")
            self.log_file.flush()
        if self.verbose:
            print(f"WARNING: {message}", file=sys.stderr)
    
    def error(self, message: str, fatal: bool = False):
        """Log ERROR level message"""
        self.error_count += 1
        if fatal:
            self.fatal_error = True
        if not self.closed:
            self.log_file.write(f"ERROR: {message}\n")
            self.log_file.flush()
        if self.verbose:
            print(f"ERROR: {message}", file=sys.stderr)
    
    def close(self):
        """Close log file and print summary"""
        if self.closed:
            return
        summary = f"\nSummary: {self.error_count} errors, {self.warning_count} warnings"
        self.info(summary)
        if self.verbose:
            print(summary)
        self.log_file.close()
        self.closed = True

############################ FILE TYPE DETECTOR ################################

class FileTypeDetector:
    """Detects type of include or Fortran source files"""
    
    ACG_WARNING = "W  A  R  N  I  N  G"
    
    @staticmethod
    def detect(filepath: Path, logger: Logger) -> FileType:
        """Detect file type by examining contents"""
        try:
            with open(filepath, 'r') as f:
                content = f.read()
            
            # Check for Fortran source file
            if filepath.suffix.upper() in ['.F90', '.F', '.F03']:
                return FileType.FORTRAN_SOURCE
            
            # Check for specific patterns
            if 'real' in content.lower() and 'pointer' in content.lower() and 'dimension' in content.lower():
                return FileType.DECLARE_POINTER
            elif 'MAPL_GetPointer' in content:
                return FileType.GET_POINTER
            elif 'MAPL_AddImportSpec' in content:
                return FileType.ADD_IMPORT
            elif 'MAPL_AddExportSpec' in content:
                return FileType.ADD_EXPORT
            elif 'MAPL_AddInternalSpec' in content:
                return FileType.ADD_INTERNAL
            else:
                return FileType.UNKNOWN
                
        except Exception as e:
            logger.error(f"Error reading file {filepath}: {e}")
            return FileType.UNKNOWN

######################## DECLARE POINTER PARSER ################################

class DeclarePointerParser:
    """Parses declare pointer include files"""
    
    POINTER_PATTERN = re.compile(
        r'^\s*real(?:\(kind=(\d+)\))?,\s*pointer,\s*dimension\(([:\,]+)\)\s*::\s*(\w+)',
        re.IGNORECASE
    )
    
    def __init__(self, logger: Logger):
        self.logger = logger
    
    def parse(self, filepath: Path) -> Dict[str, Dict]:
        """
        Parse declare pointer file
        
        Returns: {
            'VARNAME': {
                'rank': 3,
                'precision': 8  # optional
            },
            ...
        }
        """
        result = {}
        
        try:
            with open(filepath, 'r') as f:
                for line_num, line in enumerate(f, 1):
                    match = self.POINTER_PATTERN.match(line)
                    if match:
                        precision_str, dimension_str, varname = match.groups()
                        
                        # Compute rank from dimension string (count colons + 1)
                        rank = dimension_str.count(':')
                        
                        field_data = {'rank': rank}
                        if precision_str:
                            field_data['precision'] = int(precision_str)
                        
                        result[varname] = field_data
                        self.logger.info(f"DeclarePointer: {varname} rank={rank}")
                        
        except Exception as e:
            self.logger.error(f"Error parsing DeclarePointer file {filepath}: {e}")
        
        return result

########################## GET POINTER PARSER ##################################

class GetPointerParser:
    """Parses get pointer include files"""
    
    GETPOINTER_PATTERN = re.compile(
        r'call\s+MAPL_GetPointer\s*\(\s*(\w+)\s*,\s*(\w+)\s*,\s*[\'"](\w+)[\'"]',
        re.IGNORECASE
    )
    
    ALLOC_PATTERN = re.compile(r'alloc\s*=\s*(\.true\.|\.false\.)', re.IGNORECASE)
    
    IF_PATTERN = re.compile(r'^\s*if\s*\((.*?)\)\s*then', re.IGNORECASE)
    ENDIF_PATTERN = re.compile(r'^\s*endif', re.IGNORECASE)
    
    def __init__(self, logger: Logger):
        self.logger = logger
    
    def parse(self, filepath: Path) -> Dict[Tuple[str, str], Dict]:
        """
        Parse get pointer file
        
        Returns: {
            ('NAME', 'import'): {
                'category': 'import',
                'varname': 'varname',
                'condition': 'trim(VAR) == "VALUE"',  # optional
                'alloc': True  # optional
            },
            ...
        }
        Note: Keys are tuples of (name, category) to handle fields in multiple categories
        """
        result = {}
        current_condition = None
        condition_stack = []
        
        try:
            with open(filepath, 'r') as f:
                for line_num, line in enumerate(f, 1):
                    # Check for if statement
                    if_match = self.IF_PATTERN.match(line)
                    if if_match:
                        condition = if_match.group(1).strip()
                        condition_stack.append(condition)
                        current_condition = condition
                        continue
                    
                    # Check for endif
                    if self.ENDIF_PATTERN.match(line):
                        if condition_stack:
                            condition_stack.pop()
                        current_condition = condition_stack[-1] if condition_stack else None
                        continue
                    
                    # Check for MAPL_GetPointer call
                    match = self.GETPOINTER_PATTERN.search(line)
                    if match:
                        category_var, varname, name = match.groups()
                        
                        # Determine category from variable name
                        category = category_var.lower()
                        
                        field_data = {
                            'category': category,
                            'varname': varname
                        }
                        
                        if current_condition:
                            field_data['condition'] = current_condition
                        
                        # Check for alloc parameter
                        alloc_match = self.ALLOC_PATTERN.search(line)
                        if alloc_match:
                            alloc_value = alloc_match.group(1).lower()
                            field_data['alloc'] = (alloc_value == '.true.')
                        
                        # Use compound key (name, category) to handle duplicates
                        key = (name, category)
                        result[key] = field_data
                        self.logger.info(f"GetPointer: {name} category={category}")
                        
        except Exception as e:
            self.logger.error(f"Error parsing GetPointer file {filepath}: {e}")
        
        return result

########################### ADD SPEC PARSER ####################################

class AddSpecParser:
    """Parses add spec include files (import/export/internal)"""
    
    ADDSPEC_START = re.compile(
        r'call\s+MAPL_Add(Import|Export|Internal)Spec\s*\(\s*gc\s*,',
        re.IGNORECASE
    )
    
    PARAM_PATTERN = re.compile(r'(\w+)\s*=\s*([^,&]+)')
    
    IF_PATTERN = re.compile(r'^\s*if\s*\((.*?)\)\s*then', re.IGNORECASE)
    ENDIF_PATTERN = re.compile(r'^\s*endif', re.IGNORECASE)
    
    def __init__(self, logger: Logger):
        self.logger = logger
    
    def parse(self, filepath: Path, category: Category) -> List[Dict]:
        """
        Parse add spec file
        
        Returns list of field dictionaries
        """
        result = []
        current_condition = None
        condition_stack = []
        
        try:
            with open(filepath, 'r') as f:
                lines = f.readlines()
            
            i = 0
            while i < len(lines):
                line = lines[i]
                
                # Check for if statement
                if_match = self.IF_PATTERN.match(line)
                if if_match:
                    condition = if_match.group(1).strip()
                    condition_stack.append(condition)
                    current_condition = condition
                    i += 1
                    continue
                
                # Check for endif
                if self.ENDIF_PATTERN.match(line):
                    if condition_stack:
                        condition_stack.pop()
                    current_condition = condition_stack[-1] if condition_stack else None
                    i += 1
                    continue
                
                # Check for AddSpec call
                if self.ADDSPEC_START.search(line):
                    # Accumulate the complete call
                    call_lines = [line]
                    i += 1
                    while i < len(lines):
                        call_lines.append(lines[i])
                        if '_RC)' in lines[i]:
                            break
                        i += 1
                    
                    # Parse the complete call
                    field = self.parse_addspec_call(call_lines, current_condition, category)
                    if field:
                        result.append(field)
                        self.logger.info(f"AddSpec: {field.get('NAME', 'UNKNOWN')} in {category.value}")
                    
                    i += 1
                else:
                    i += 1
                    
        except Exception as e:
            self.logger.error(f"Error parsing AddSpec file {filepath}: {e}")
        
        return result
    
    def parse_addspec_call(self, call_lines: List[str], condition: Optional[str], category: Category) -> Optional[Dict]:
        """Parse a single AddSpec call"""
        # Join lines and remove continuation characters
        call_text = ' '.join(call_lines)
        call_text = call_text.replace('&', ' ')
        
        # Extract parameters
        field = {}
        
        if condition:
            field['COND'] = condition
        
        # Find all parameter=value pairs
        for match in self.PARAM_PATTERN.finditer(call_text):
            param_name = match.group(1).strip().lower()
            param_value = match.group(2).strip()
            
            # Skip special parameters
            if param_name in ['gc', '_rc']:
                continue
            
            # Map parameter name to column name
            column_name = param_to_column_name(param_name)
            
            # Process value
            value = self.process_value(param_value, column_name)
            if value:
                field[column_name] = value
        
        return field if field else None
    
    def process_value(self, value: str, column_name: str) -> str:
        """Process parameter value - unmangle names, map constants, clean up"""
        value = value.strip()
        
        # Remove trailing commas and parentheses
        value = value.rstrip(',)')
        value = value.strip()
        
        # Map MAPL constants
        if column_name == 'DIMS':
            for mapl_const, abbrev in DIMS_REVERSE_MAP.items():
                if mapl_const in value:
                    return abbrev
        elif column_name == 'VLOC':
            for mapl_const, abbrev in VLOC_REVERSE_MAP.items():
                if mapl_const in value:
                    return abbrev
        elif column_name == 'RESTART':
            for mapl_const, abbrev in RESTART_REVERSE_MAP.items():
                if mapl_const in value:
                    return abbrev
        
        # Unmangle names (handle Fortran string concatenation)
        if column_name in ['NAME', 'LONG_NAME', 'FRIENDLYTO']:
            value = self.unmangle_name(value)
        
        # Remove quotes/apostrophes
        if value.startswith("'") and value.endswith("'"):
            value = value[1:-1]
        elif value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        
        # Handle arrays - remove brackets
        if value.startswith('[') and value.endswith(']'):
            value = value[1:-1]
            value = value.strip()
        
        # Handle logical values
        if value.lower() in ['.true.', '.false.']:
            return 'T' if value.lower() == '.true.' else 'F'
        
        return value
    
    def unmangle_name(self, name_str: str) -> str:
        """
        Reverse name mangling:
        'ZLE' -> ZLE
        'PREFIX'//trim(comp_name)//'SUFFIX' -> *SUFFIX
        """
        # Remove outer quotes first
        if name_str.startswith("'") and name_str.endswith("'"):
            name_str = name_str[1:-1]
        elif name_str.startswith('"') and name_str.endswith('"'):
            name_str = name_str[1:-1]
        
        # Check for concatenation pattern
        if '//' in name_str:
            # Pattern: PREFIX//trim(comp_name)//SUFFIX or variations
            # Look for the suffix after the last //
            parts = name_str.split('//')
            if len(parts) > 1:
                # Get the last part (suffix)
                suffix = parts[-1].strip().strip("'\"")
                if suffix:
                    return '*' + suffix
                # If no suffix, try to get prefix
                prefix = parts[0].strip().strip("'\"")
                if prefix:
                    return prefix + '*'
        
        return name_str

###################### COMPONENT NAME EXTRACTOR ################################

class ComponentNameExtractor:
    """Extracts component name from various sources"""
    
    FILENAME_PATTERNS = [
        re.compile(r'^(\w+)_Import', re.IGNORECASE),
        re.compile(r'^(\w+)_Export', re.IGNORECASE),
        re.compile(r'^(\w+)_Internal', re.IGNORECASE),
        re.compile(r'^(\w+)_DeclarePointer', re.IGNORECASE),
        re.compile(r'^(\w+)_GetPointer', re.IGNORECASE),
    ]
    
    def __init__(self, logger: Logger):
        self.logger = logger
    
    def extract(self, cli_component: Optional[str], file_paths: List[Path]) -> str:
        """Extract component name with priority and cross-checking"""
        extracted_names = set()
        
        # Extract from filenames
        for path in file_paths:
            name = self.extract_from_filename(path)
            if name:
                extracted_names.add(name)
        
        # Determine final component name
        if cli_component:
            # CLI component is authoritative
            if extracted_names and cli_component not in extracted_names:
                self.logger.warning(
                    f"Component name from CLI '{cli_component}' differs from extracted names: {extracted_names}"
                )
            return cli_component
        
        elif len(extracted_names) == 1:
            # Single consistent name found
            component = list(extracted_names)[0]
            self.logger.info(f"Component name extracted: {component}")
            return component
        
        elif len(extracted_names) > 1:
            # Multiple different names found
            self.logger.warning(
                f"Multiple component names found: {extracted_names}. Using first one."
            )
            return sorted(extracted_names)[0]
        
        else:
            # No name found
            self.logger.error("Could not extract component name from filenames")
            return "UNKNOWN"
    
    def extract_from_filename(self, path: Path) -> Optional[str]:
        """Extract component name from filename using patterns"""
        stem = path.stem
        for pattern in self.FILENAME_PATTERNS:
            match = pattern.match(stem)
            if match:
                return match.group(1)
        return None

######################### FIELD DATA MERGER ####################################

class FieldDataMerger:
    """Merges field data from different sources"""
    
    def __init__(self, logger: Logger):
        self.logger = logger
    
    def merge(self, 
              addspec_data: Dict[Category, List[Dict]],
              declare_data: Dict[str, Dict],
              getpointer_data: Dict[Tuple[str, str], Dict]) -> Dict[Category, List[Dict]]:
        """Merge data from all sources"""
        
        merged_data = {}
        
        # Track which fields we've seen in addspec (authoritative)
        addspec_fields = set()
        
        for category, fields in addspec_data.items():
            if not fields:
                continue
            
            merged_fields = []
            
            for field in fields:
                name = field.get('NAME')
                if not name:
                    self.logger.error(f"Field in {category.value} missing NAME")
                    continue
                
                addspec_fields.add((name, category.value.lower()))
                
                # Compute expected rank from DIMS and UNGRIDDED
                dims = field.get('DIMS')
                ungridded = field.get('UNGRIDDED')
                if dims:
                    expected_rank = self.compute_rank(dims, ungridded)
                    
                    # Cross-check with DeclarePointer
                    if name in declare_data:
                        actual_rank = declare_data[name]['rank']
                        if actual_rank != expected_rank:
                            self.logger.error(
                                f"Rank mismatch for {name}: DeclarePointer={actual_rank}, "
                                f"computed from DIMS+UNGRIDDED={expected_rank}"
                            )
                        # Add precision if available
                        if 'precision' in declare_data[name]:
                            field['PRECISION'] = str(declare_data[name]['precision'])
                    else:
                        self.logger.warning(f"Field {name} not found in DeclarePointer file")
                
                # Cross-check with GetPointer using compound key
                gp_key = (name, category.value.lower())
                if gp_key in getpointer_data:
                    gp_category = getpointer_data[gp_key]['category']
                    expected_category = category.value.lower()
                    
                    if gp_category != expected_category:
                        self.logger.error(
                            f"Category mismatch for {name}: GetPointer={gp_category}, "
                            f"AddSpec={expected_category}"
                        )
                    
                    # Check condition consistency
                    gp_condition = getpointer_data[gp_key].get('condition')
                    addspec_condition = field.get('COND')
                    
                    if gp_condition and addspec_condition:
                        if gp_condition != addspec_condition:
                            self.logger.warning(
                                f"Condition mismatch for {name}: GetPointer='{gp_condition}', "
                                f"AddSpec='{addspec_condition}'"
                            )
                    elif gp_condition and not addspec_condition:
                        self.logger.warning(
                            f"Condition in GetPointer but not AddSpec for {name}: '{gp_condition}'"
                        )
                    
                    # Add alloc if present
                    if 'alloc' in getpointer_data[gp_key]:
                        field['ALLOC'] = 'T' if getpointer_data[gp_key]['alloc'] else 'F'
                else:
                    self.logger.warning(f"Field {name} in {category.value} not found in GetPointer file")
                
                # Check for missing mandatory fields
                for mandatory_col in MANDATORY_COLUMNS_BASE:
                    if mandatory_col not in field:
                        self.logger.error(f"Missing mandatory field {mandatory_col} for {name}")
                        field[mandatory_col] = MISSING_VALUE
                
                merged_fields.append(field)
            
            merged_data[category] = merged_fields
        
        # Check for orphaned fields in DeclarePointer or GetPointer
        for name in declare_data:
            # Check if this name appears in any category in addspec
            if not any((name, cat) in addspec_fields for cat in ['import', 'export', 'internal']):
                self.logger.warning(f"Field {name} in DeclarePointer but not in AddSpec files")
        
        for (name, cat) in getpointer_data:
            if (name, cat) not in addspec_fields:
                self.logger.warning(f"Field {name} ({cat}) in GetPointer but not in AddSpec files")
        
        return merged_data
    
    def compute_rank(self, dims: str, ungridded: Optional[str] = None) -> int:
        """Compute expected rank from DIMS and UNGRIDDED_DIMS"""
        dims_rank = DIMS_TO_RANK.get(dims, 0)
        
        if not ungridded:
            return dims_rank
        
        # Count commas in ungridded to get number of dimensions
        ungridded_rank = ungridded.count(',') + 1 if ungridded.strip() else 0
        
        return dims_rank + ungridded_rank

######################## ACG SPEC GENERATOR ####################################

class ACGSpecGenerator:
    """Generates ACG spec file from merged field data"""
    
    def __init__(self, schema_version: str, component: str, logger: Logger):
        self.schema_version = schema_version
        self.component = component
        self.logger = logger
    
    def generate(self, merged_data: Dict[Category, List[Dict]], output_path: Path):
        """Generate and write ACG spec file"""
        try:
            with open(output_path, 'w') as f:
                # Write header
                f.write(f"schema_version: {self.schema_version}\n")
                f.write(f"component: {self.component}\n")
                
                # Write each category
                for i, (category, fields) in enumerate(merged_data.items()):
                    if not fields:
                        continue
                    
                    # Blank line before category
                    f.write("\n")
                    
                    # Write category header
                    f.write(f"category: {category.value}\n")
                    
                    # Determine columns for this category
                    columns = self.determine_columns(fields)
                    
                    # Compute column widths
                    widths = self.compute_column_widths(fields, columns)
                    
                    # Write comment separator
                    separator = self.generate_comment_separator(widths, columns)
                    f.write(separator + "\n")
                    
                    # Write metadata comment
                    f.write("#  VARIABLE")
                    f.write(" " * (widths['NAME'] - len("VARIABLE")))
                    f.write(" | DIMENSIONS")
                    # Calculate remaining space
                    dims_section_width = widths['UNITS'] + widths['DIMS'] + widths['VLOC'] + 6  # 6 for pipes and spaces
                    f.write(" " * (dims_section_width - len("DIMENSIONS")))
                    f.write(" | Additional Metadata\n")
                    
                    # Write comment separator
                    f.write(separator + "\n")
                    
                    # Write column headers
                    header_parts = []
                    for col in columns:
                        header_parts.append(col.ljust(widths[col]))
                    f.write(" | ".join(header_parts) + "\n")
                    
                    # Write comment separator
                    f.write(separator + "\n")
                    
                    # Write data rows
                    for field in fields:
                        row = self.format_row(field, columns, widths)
                        f.write(row + "\n")
            
            self.logger.info(f"Successfully generated ACG spec file: {output_path}")
            
        except Exception as e:
            self.logger.error(f"Error writing ACG spec file: {e}")
            raise
    
    def determine_columns(self, fields: List[Dict]) -> List[str]:
        """Determine which columns to include"""
        # Start with mandatory columns
        columns = []
        
        # NAME always first
        columns.append('NAME')
        
        # Other mandatory columns (except LONG_NAME which goes last)
        for col in MANDATORY_COLUMNS_BASE:
            if col not in ['NAME', 'LONG_NAME']:
                columns.append(col)
        
        # Check optional columns
        for col in OPTIONAL_COLUMNS:
            # Include if any field has a non-empty value
            if any(field.get(col) for field in fields):
                columns.append(col)
        
        # LONG_NAME always last
        if any('LONG_NAME' in field for field in fields):
            columns.append('LONG_NAME')
        
        return columns
    
    def compute_column_widths(self, fields: List[Dict], columns: List[str]) -> Dict[str, int]:
        """Compute width for each column to align pipes"""
        widths = {}
        
        for col in columns:
            # Start with column name length
            max_width = len(col)
            
            # Check all field values
            for field in fields:
                value = field.get(col, '')
                if value:
                    max_width = max(max_width, len(str(value)))
            
            # Add padding
            widths[col] = max_width + 1
        
        return widths
    
    def format_row(self, field: Dict, columns: List[str], widths: Dict[str, int]) -> str:
        """Format a data row with aligned pipes"""
        parts = []
        
        for col in columns:
            value = field.get(col, '')
            if value is None:
                value = ''
            parts.append(str(value).ljust(widths[col]))
        
        return " | ".join(parts)
    
    def generate_comment_separator(self, widths: Dict[str, int], columns: List[str]) -> str:
        """Generate comment line with dashes"""
        # Calculate total width of row
        total_width = sum(widths.values()) + len(columns) * 3 - 3  # Account for " | " separators
        return "#" + "-" * (total_width + 1)

################################### MAIN #######################################

def main():
    """Main function"""
    
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description='Convert MAPL include files back to ACG spec file',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  %(prog)s ACG_Import___.h ACG_Export___.h ACG_DeclarePointer___.h -o ACG_StateSpecs.rc
  %(prog)s *.h --component Ocean --schema 2.0.0
        """
    )
    
    parser.add_argument('files', nargs='+', metavar='FILE',
                        help='Include files (.h) and optional Fortran source files (.F90)')
    parser.add_argument('-o', '--output', metavar='FILE',
                        help='Output ACG spec file (default: {component}_StateSpecs.rc)')
    parser.add_argument('--component', metavar='NAME',
                        help='Component name (extracted from files if not provided)')
    parser.add_argument('--schema', metavar='VERSION', default=SCHEMA_VERSION_DEFAULT,
                        help=f'Schema version (default: {SCHEMA_VERSION_DEFAULT})')
    parser.add_argument('--log', metavar='FILE', default=LOG_FILE_DEFAULT,
                        help=f'Error log file (default: {LOG_FILE_DEFAULT})')
    
    args = parser.parse_args()
    
    # Initialize logger
    logger = Logger(Path(args.log))
    logger.info("MAPL_IncludeFiles_to_ACG.py started")
    logger.info(f"Input files: {args.files}")
    
    try:
        # Detect file types
        detector = FileTypeDetector()
        file_types = {}
        
        for filepath_str in args.files:
            filepath = Path(filepath_str)
            if not filepath.exists():
                logger.error(f"File not found: {filepath}")
                continue
            
            file_type = detector.detect(filepath, logger)
            file_types[filepath] = file_type
            logger.info(f"Detected {filepath.name}: {file_type.value}")
        
        # Check for required file types
        has_addspec = any(ft in [FileType.ADD_IMPORT, FileType.ADD_EXPORT, FileType.ADD_INTERNAL] 
                         for ft in file_types.values())
        has_declare = FileType.DECLARE_POINTER in file_types.values()
        has_get = FileType.GET_POINTER in file_types.values()
        
        if not has_addspec:
            logger.error("No AddSpec files found. At least one AddSpec file is required.", fatal=True)
            logger.close()
            sys.exit(-1)
        
        if not has_declare:
            logger.warning("No DeclarePointer file found")
        
        if not has_get:
            logger.warning("No GetPointer file found")
        
        # Parse files
        declare_data = {}
        getpointer_data = {}
        addspec_data = {Category.IMPORT: [], Category.EXPORT: [], Category.INTERNAL: []}
        
        for filepath, file_type in file_types.items():
            if file_type == FileType.DECLARE_POINTER:
                parser_obj = DeclarePointerParser(logger)
                declare_data = parser_obj.parse(filepath)
                
            elif file_type == FileType.GET_POINTER:
                parser_obj = GetPointerParser(logger)
                getpointer_data = parser_obj.parse(filepath)
                
            elif file_type == FileType.ADD_IMPORT:
                parser_obj = AddSpecParser(logger)
                addspec_data[Category.IMPORT] = parser_obj.parse(filepath, Category.IMPORT)
                
            elif file_type == FileType.ADD_EXPORT:
                parser_obj = AddSpecParser(logger)
                addspec_data[Category.EXPORT] = parser_obj.parse(filepath, Category.EXPORT)
                
            elif file_type == FileType.ADD_INTERNAL:
                parser_obj = AddSpecParser(logger)
                addspec_data[Category.INTERNAL] = parser_obj.parse(filepath, Category.INTERNAL)
        
        # Extract component name
        extractor = ComponentNameExtractor(logger)
        component = extractor.extract(args.component, [Path(f) for f in args.files])
        
        # Merge field data
        merger = FieldDataMerger(logger)
        merged_data = merger.merge(addspec_data, declare_data, getpointer_data)
        
        # Determine output filename
        if args.output:
            output_path = Path(args.output)
        else:
            output_path = Path(f"{component}_StateSpecs.rc")
        
        # Generate ACG spec file
        generator = ACGSpecGenerator(args.schema, component, logger)
        generator.generate(merged_data, output_path)
        
        print(f"Generated ACG spec file: {output_path}")
        
    except Exception as e:
        logger.error(f"Fatal error: {str(e)}")
        import traceback
        logger.error(traceback.format_exc())
        logger.close()
        # Exit with -1 for fatal errors
        sys.exit(-1)
        
    finally:
        logger.close()
    
    # Exit codes:
    # 0 = success (no errors)
    # positive number = count of non-fatal errors
    # -1 = fatal error (handled in except block above)
    sys.exit(logger.error_count if logger.error_count > 0 else 0)

if __name__ == "__main__":
    main()
