test – MAPL
test Program
102 statements
Source File
Uses
ESMF_CFIOMod
Calls
Contents
Variables
fileName curTime date fmode hhmmss i im im1 jm jm1 km km1 rc t timeInc tm passed twoD dlat dlon dsig lat lev lon ps q sig tmpu ts u v cfio grid vars
Variables
Type Attributes Name Initial
character(len=20) :: fileName
integer :: curTime
integer :: date
integer :: fmode
integer :: hhmmss(tm) = (/0, 30000, 60000, 90000, 120000, 150000, 180000, 210000/)
integer :: i
integer, parameter :: im = 540
integer :: im1
integer, parameter :: jm = 361
integer :: jm1
integer, parameter :: km = 72
integer :: km1
integer :: rc
integer :: t
integer :: timeInc
integer, parameter :: tm = 8
logical :: passed = .true.
logical :: twoD
real :: dlat
real :: dlon
real :: dsig
real :: lat(jm)
real :: lev(km)
real :: lon(im)
real :: ps(im,jm)
real :: q(im,jm,km)
real :: sig
real :: tmpu(im,jm,km)
real :: ts(im,jm)
real :: u(im,jm,km)
real :: v(im,jm,km)
type(ESMF_CFIO) :: cfio
type(ESMF_CFIOGrid), pointer :: grid
type(ESMF_CFIOVarInfo), pointer :: vars(:)
Call graph
test calls esmf_cfiovarwrite, esmf_cfiofileclose, esmf_cfiofilecreate
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
esmf_cfiofilecreate calls ESMF_UtilStringUpperCase, esmf_cfiosdffilecreate, esmf_cfioset
esmf_cfioget calls err
esmf_cfiosdffileclose calls cfio_close
esmf_cfiosdffilecreate calls esmf_cfioget, esmf_cfioset, attcharcnts, attcharnames, attchars, attintcnts, attintnames, attints, attrealcnts, attrealnames, attreals, cfio_putcharatt, cfio_putintatt, cfio_putrealatt, err, getlist, strtemplate_
esmf_cfioset calls addlist, err, strtoint