accumulate – MAPL
accumulate Subroutine
25 statements
Source File
private recursive subroutine accumulate(this, other)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(inout) :: this
class(AbstractMeterNode), intent(in), target :: other
Calls
Contents
Source Code
accumulate
Source Code
   recursive subroutine accumulate(this, other)
      class (MeterNode), intent(inout) :: this
      class (AbstractMeterNode), target, intent(in) :: other
      class (AbstractMeterNode), pointer :: child
      class (AbstractMeterNodeIterator), allocatable :: iter
      class (AbstractMeter), pointer :: t
      character(:), pointer :: name
      ! GFortran 8.2 complains about recursive call of nonrecursive
      ! procedure (nested copy of data structure)
      name => other%get_name()
      child => this%get_child(name)
      if (associated(child)) then
         t => child%get_meter()
      else
         call this%add_child(name, this%get_meter())
         child => this%get_child(name)
         t => child%get_meter()
         call t%reset()
      end if
      call t%accumulate(other%get_meter())
      ! recurse over children of other
      iter = other%begin()
      call iter%next() ! skip top node (already handled)
      do while (iter /= other%end())
         call child%accumulate(iter%get())
         call iter%next()
      end do
   end subroutine accumulate
Call graph
accumulate calls accumulate, add_child, begin, get_child, get_meter, get_name, get, next, reset
add_child calls meternode, find_child, get_depth
begin calls meternodeiterator
get_child calls find_child
next calls begin
reset calls get, next, reset
meternode calls new_meternode
meternodeiterator calls new_meternodeiterator