acquire – MAPL
acquire Subroutine
19 statements
Source File
private subroutine acquire(this)
Type Bound
MpiMutex
Arguments
Type Intent Optional Attributes Name
class(MpiMutex), intent(inout) :: this
Calls
Called by
Source Code
   subroutine acquire(this)
      class (MpiMutex), intent(inout) :: this
      integer :: ierror,rc,status
      call MPI_Win_lock(MPI_LOCK_EXCLUSIVE, 0, 0, this%window, ierror)
      _VERIFY(ierror)
      call MPI_Get(this%local_data, this%npes-1, MPI_LOGICAL, 0, &
           & 0_MPI_ADDRESS_KIND, 1, this%pe_locks_type, this%window, ierror)
      _VERIFY(ierror)
      call MPI_Put(.true., 1, MPI_LOGICAL, 0, int(this%rank,kind=MPI_ADDRESS_KIND), &
           & 1, MPI_LOGICAL, this%window, ierror)
      _VERIFY(ierror)
      call MPI_Win_unlock(0, this%window, ierror)
      _VERIFY(ierror)
      ! Check other processes for holding the lock
      if (any(this%local_data)) then ! wait for signal from process with the lock
         block
           integer :: buffer ! unused
           call MPI_Recv(buffer, 0, MPI_LOGICAL, MPI_ANY_SOURCE, &
                & LOCK_TAG, this%comm, MPI_STATUS_IGNORE, ierror)
           _VERIFY(ierror)
         end block
      end if
   end subroutine acquire
Call graph
acquire calls mpi_get, mpi_put, mpi_recv, mpi_win_lock, mpi_win_unlock, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
connect_to_client calls acquire
connect_to_server calls acquire
publish calls acquire
initialize calls connect_to_client, connect_to_server, publish
test_connect calls connect_to_client, connect_to_server, publish
test_connect_multi calls connect_to_client, connect_to_server, publish
test_connect_swap_role calls connect_to_client, connect_to_server, publish
test_connect_with_unused_process calls connect_to_client, connect_to_server, publish
test_publish calls publish
test_stress calls connect_to_client, connect_to_server, publish
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main