activate_threading – MAPL
activate_threading Subroutine
26 statements
Source File
private recursive subroutine activate_threading(this, num_threads, unusable, rc)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout) :: this
integer, intent(in) :: num_threads
class(KeywordEnforcer), optional :: unusable
integer, intent(out), optional :: rc
Calls
Contents
Source Code
activate_threading
Source Code
   recursive subroutine activate_threading(this, num_threads, unusable, rc)
     class(MaplGenericComponent), intent(inout) :: this
     integer, intent(in) :: num_threads
     class(KeywordEnforcer), optional :: unusable
     integer, optional, intent(out) :: rc
     class(AbstractFrameworkComponent), pointer :: child
     integer :: num_children, i, status
     this%threading_active = .TRUE.
     num_children = this%get_num_children()
     if (.NOT. allocated(this%subcomponents)) then
        call this%create_subobjects(num_threads, _RC)
     end if
     do i = 1, num_children
        child => this%get_child(i)
        select type (child)
        class is (MaplGenericComponent)
           call child%activate_threading(num_threads)
        class default
           _FAIL('illegal type for child')
        end select
     end do
     _RETURN(0)
     _UNUSED_DUMMY(unusable)
   end subroutine activate_threading
Call graph
activate_threading calls activate_threading, get_child, get_num_children, mapl_assert, create_subobjects, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
create_subobjects calls mapl_return, mapl_verify, make_subgrids, make_substates, make_subgridcomps, subcomponents
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_subgrids calls make_subgrids_from_bounds, make_subgrids_from_num_grids
make_substates calls make_substates_from_num_grids
get_error_message calls at
make_subgridcomps calls mapl_return, mapl_verify, ESMF_GridCompCreate, ESMF_GridCompGet, ESMF_InternalStateGet, ESMF_UserCompGetInternalState, ESMF_UserCompSetInternalState, ESMF_VMGet, ESMF_VMGetCurrent, esmf_gridcompsetservices
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize