add_child_component – MAPL
add_child_component Function
9 statements
Source File
private function add_child_component(this, name, user_component) result(child)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout), target :: this
character(len=*), intent(in) :: name
class(AbstractComponent), intent(in) :: user_component
Return Value class(AbstractFrameworkComponent), pointer
Calls
Source Code
   function add_child_component(this, name, user_component) result(child)
      class(AbstractFrameworkComponent), pointer :: child
      class(MaplGenericComponent), target, intent(inout) :: this
      character(*), intent(in) :: name
      class(AbstractComponent), intent(in) :: user_component
      type(MaplGenericComponent) :: tmp
      child => this%add_child(name, tmp)
      call child%set_component(user_component)
   end function add_child_component
Call graph
add_child_component calls add_child, set_component
add_child calls get_component, add_child, insert, m_at, push_back
m_at calls m_find