add_ext_collection – MAPL
add_ext_collection Function
21 statements
Source File
private function add_ext_collection(this, template, rc) result(collection_id)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
character(len=*), intent(in) :: template
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function add_ext_collection(this, template, rc) result(collection_id)
      integer :: collection_id
      class (ClientThread), intent(inout) :: this
      character(len=*), intent(in) :: template
      integer, optional, intent(out) :: rc
      class (AbstractMessage), pointer :: message
      class(AbstractSocket),pointer :: connection
      integer :: status
      connection=>this%get_connection()
      call connection%send(AddExtCollectionMessage(template),_RC)
      message => connection%receive()
      select type(message)
      type is(IDMessage)
        collection_id = message%id
      class default
        _FAIL( " should get id message")
      end select
      _RETURN(_SUCCESS)
   end function add_ext_collection
Call graph
add_ext_collection calls mapl_assert, get_connection, mapl_return, mapl_verify, receive, send, add_ext_collection
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run calls add_ext_collection
test_addextcollection_send_message calls add_ext_collection
test_addextcollection_unique_handle calls add_ext_collection
test_prefetch_data calls add_ext_collection
test_wait calls add_ext_collection
create_bracketing_fields calls add_ext_collection
initialize_ calls add_ext_collection
mapl_read_bundle calls add_ext_collection
main calls run, mapl_read_bundle
run_ calls create_bracketing_fields
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main