add_DataReference – MAPL
add_DataReference Subroutine
6 statements
Source File
private subroutine add_DataReference(this, DataRef)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout) :: this
class(AbstractDataReference), intent(in), target :: DataRef
Calls
Called by
Source Code
   subroutine add_DataReference(this,DataRef)
      class (AbstractServer), intent(inout) :: this
      class(AbstractDataReference),target,intent(in) :: DataRef
      call this%dataRefPtrs%push_back(DataRef)
      call this%set_status(this%num_clients)
   end subroutine add_DataReference
Call graph
add_datareference calls set_status, v_push_back
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
create_remote_win calls add_datareference
handle_done_collective_prefetch calls add_datareference
start calls create_remote_win