add_prototype – MAPL
add_prototype Subroutine
6 statements
Source File
private subroutine add_prototype(this, grid_type, prototype)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: grid_type
class(AbstractGridFactory), intent(in) :: prototype
Calls
Called by
Source Code
   subroutine add_prototype(this, grid_type, prototype)
      class (GridManager), intent(inout) :: this
      character(len=*), intent(in) :: grid_type
      class (AbstractGridFactory), intent(in) :: prototype
      call this%prototypes%insert(grid_type, prototype)
   end subroutine add_prototype
Call graph
add_prototype calls insert
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
test_add_prototype calls add_prototype
test_grid_type calls add_prototype
test_make_grid_multi calls add_prototype
test_make_grid_prototype calls add_prototype