add_prototype_by_spec – MAPL
add_prototype_by_spec Subroutine
6 statements
Source File
private subroutine add_prototype_by_spec(this, regridder_type, prototype)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout) :: this
type(RegridderTypeSpec), intent(in) :: regridder_type
class(AbstractRegridder), intent(in) :: prototype
Calls
Source Code
   subroutine add_prototype_by_spec(this, regridder_type, prototype)
      class (RegridderManager), intent(inout) :: this
      type (RegridderTypeSpec), intent(in) :: regridder_type
      class (AbstractRegridder), intent(in) :: prototype
      call this%prototypes%insert(regridder_type, prototype)
   end subroutine add_prototype_by_spec
Call graph
add_prototype_by_spec calls insert
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back