add_attribute_0d – MAPL
add_attribute_0d Subroutine
14 statements
Source File
private subroutine add_attribute_0d(this, attr_name, attr_value, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: attr_name
class(*), intent(in) :: attr_value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_attribute_0d(this, attr_name, attr_value, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: attr_name
      class (*), intent(in) :: attr_value
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      call this%global_var%add_attribute(attr_name, attr_value)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_attribute_0d
Call graph
add_attribute_0d calls add_attribute, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
add_attribute_1d calls mapl_return, insert
get_error_message calls at, insert
mapl_throw_exception calls initialize
createfilemetadata calls add_attribute
inq_attributes calls add_attribute
mapl_bundlewritencpar calls add_attribute
mapl_writetilingnc4 calls add_attribute
merge calls add_attribute
test_equal_diff_attributes calls add_attribute
test_get_attribute_scalar calls add_attribute
test_get_attribute_vector calls add_attribute
test_get_attributes calls add_attribute
test_write_read_simple_attribute calls add_attribute
transfer_metadata calls add_attribute
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
mapl_statevarwritencpar calls mapl_bundlewritencpar
read calls inq_attributes
run calls createfilemetadata
main calls transfer_metadata, create_from_bundle
mapl_esmfstatewritetofile calls mapl_varwritencpar
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle