add_cycle – MAPL
add_cycle Subroutine
14 statements
Source File
private subroutine add_cycle(this, increment)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(inout) :: this
real(kind=REAL64), intent(in) :: increment
Calls
Called by
Source Code
   subroutine add_cycle(this, increment)
      class(AdvancedMeter), intent(inout) :: this
      real(kind=REAL64), intent(in) :: increment
      real(kind=REAL64) :: old_mean, new_mean
      associate ( n => this%num_cycles, t => increment )
        this%min_cycle = min(this%min_cycle, t)
        this%max_cycle = max(this%max_cycle, t)
        old_mean = this%get_mean_cycle()
        n = n + 1
        new_mean = old_mean + (t - old_mean) / n ! denominator provably always > 0 (modulo integer overflow)
        this%sum_square_deviation = this%sum_square_deviation + (t - old_mean)*(t - new_mean)
        this%total = this%total + t
      end associate
   end subroutine add_cycle
Call graph
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles
stop calls add_cycle
test_accumulate calls add_cycle
test_add_cycle calls add_cycle
test_get_max calls add_cycle
test_get_max_cycle calls add_cycle
test_get_mean_cycle calls add_cycle
test_get_min calls add_cycle
test_get_min_cycle calls add_cycle
test_get_num_cycles calls add_cycle
test_get_standard_deviation calls add_cycle
test_get_total calls add_cycle
test_reset calls add_cycle
test_trivial calls add_cycle