add_wrapper_comp – MAPL
add_wrapper_comp Subroutine
18 statements
Source File
private subroutine add_wrapper_comp(driver, name, cap_rc_file, root_set_services, pet_list, wrapper_gc, rc)
Uses
NUOPC_Driver
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: driver
character(len=*), intent(in) :: name
character(len=*), intent(in) :: cap_rc_file
procedure(set_services_interface) :: root_set_services
integer, intent(in), optional :: pet_list(:)
type(ESMF_GridComp), intent(out) :: wrapper_gc
integer, intent(out) :: rc
Calls
Source Code
    subroutine add_wrapper_comp(driver, name, cap_rc_file, root_set_services, pet_list, wrapper_gc, rc)
        use NUOPC_Driver
        type(ESMF_GridComp), intent(inout) :: driver
        character(len=*),    intent(in   ) :: name, cap_rc_file
        procedure(set_services_interface)  :: root_set_services
        integer, intent(in), optional      :: pet_list(:)
        type(ESMF_GridComp), intent(out)   :: wrapper_gc
        integer,             intent(out)   :: rc
        type(cap_parameters_wrapper) :: wrapper
        call NUOPC_DriverAddComp(driver, name, SetServices, comp = wrapper_gc, &
                petlist = pet_list, rc = rc)
        VERIFY_NUOPC_(rc)
        allocate(wrapper%ptr)
        wrapper%ptr = cap_parameters(name, cap_rc_file, root_set_services)
        call ESMF_UserCompSetInternalState(wrapper_gc, internal_parameters_name, wrapper, rc)
        VERIFY_NUOPC_(rc)
        _RETURN(_SUCCESS)
    end subroutine add_wrapper_comp
Call graph
add_wrapper_comp calls ESMF_LogFoundError, ESMF_UserCompSetInternalState, NUOPC_DriverAddComp, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize