add_message – MAPL
add_message Subroutine
6 statements
Source File
private subroutine add_message(this, message)
Uses
pFIO_TerminateMessageMod
Type Bound
MockSocket
Arguments
Type Intent Optional Attributes Name
class(MockSocket), intent(inout) :: this
class(AbstractMessage), intent(in) :: message
Calls
Called by
Source Code
   subroutine add_message(this, message)
      use pFIO_TerminateMessageMod
      class (MockSocket), intent(inout) :: this
      class (AbstractMessage), intent(in) :: message
      call this%messages%push_back(message)
   end subroutine add_message
Call graph
add_message calls v_push_back
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
test_handle_addextcollection calls add_message
test_handle_prefetchdata calls add_message
test_return_on_terminate calls add_message
test_return_on_terminate_b calls add_message