add_child – MAPL
add_child Function
16 statements
Source File
private function add_child(this, name, component) result(child)
Type Bound
CompositeComponent
Arguments
Type Intent Optional Attributes Name
class(CompositeComponent), intent(inout), target :: this
character(len=*), intent(in) :: name
class(AbstractFrameworkComponent), intent(in) :: component
Return Value class(AbstractFrameworkComponent), pointer
Calls
Called by
Source Code
   function add_child(this, name, component) result(child)
      class(AbstractFrameworkComponent), pointer :: child
      class(CompositeComponent), target, intent(inout) :: this
      character(*), intent(in) :: name
      class(AbstractFrameworkComponent), intent(in) :: component
      class(AbstractComposite), pointer :: child_composite
      child_composite => this%composite%add_child(name, ConcreteComposite(component, parent=this%composite))
      ! Possibly the introduction of a SurrogateComposite class at the
      ! top of the inheritance hierarchy would eliminate some of the
      ! SELECT TYPE statements below.  As an isolated instance
      ! the current solution is not completely abhorrent.
      select type (child_composite)
      class is (ConcreteComposite)
         child => child_composite%get_component()
         select type(child)
         class is (CompositeComponent)
            child%composite => child_composite
         end select
      end select
   end function add_child
Call graph
add_child calls get_component, add_child, insert, m_at, push_back
m_at calls m_find
m_find calls s_find
m_insert_pair calls s_insert
add_child_component calls add_child
addchild_preamble calls add_child
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
mapl_addchild calls addchildfromdsometa, addchildfrommeta, addchildfromdso, addchildfromgc
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild