add_time_to_metadata – MAPL
add_time_to_metadata Subroutine
22 statements
Source File
private subroutine add_time_to_metadata(this, metadata, rc)
Type Bound
timeData
Arguments
Type Intent Optional Attributes Name
class(timeData), intent(inout) :: this
type(FileMetadata), intent(inout) :: metadata
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine add_time_to_metadata(this,metadata,rc)
    class(timeData), intent(inout) :: this
    type(FileMetadata), intent(inout) :: metadata
    integer, intent(out), optional :: rc
    type(Variable) :: v
    integer :: tdim
    integer :: status
    if (this%is_initialized) then
       if (this%ntime==-1) then
          tdim = pFIO_UNLIMITED
       else
          tdim = this%ntime
       end if
       call metadata%add_dimension('time',tdim)
       v = this%define_time_variable(_RC)
       call metadata%add_variable('time',v,_RC)
    end if
    _RETURN(_SUCCESS)
  end subroutine add_time_to_metadata
Call graph
add_time_to_metadata calls add_dimension, add_variable, define_time_variable, mapl_return, mapl_verify
add_dimension calls mapl_return, insert
add_variable calls mapl_return, at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
define_time_variable calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, mapl_assert, add_attribute, v_clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_throw_exception calls initialize
v_clear calls v_downsize
add_metadata calls add_time_to_metadata, add_metadata
add_metadata_route_handle calls add_time_to_metadata
createfilemetadata calls add_time_to_metadata
create_from_bundle calls createfilemetadata
initialize calls add_metadata_route_handle, createfilemetadata
run calls createfilemetadata
initialize_ calls add_metadata, initialize_
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main