add_group_simple – MAPL
add_group_simple Subroutine
43 statements
Source File
private subroutine add_group_simple(this, unusable, npes, nnodes, isolate_nodes, npes_per_node, name, rc)
Type Bound
SimpleCommSplitter
Arguments
Type Intent Optional Attributes Name
class(SimpleCommSplitter), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: npes
integer, intent(in), optional :: nnodes
logical, intent(in), optional :: isolate_nodes
integer, intent(in), optional :: npes_per_node
character(len=*), intent(in), optional :: name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_group_simple(this, unusable, npes, nnodes, isolate_nodes, npes_per_node, name, rc)
      class (SimpleCommSplitter), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: npes
      integer, optional, intent(in) :: nnodes
      logical, optional, intent(in) :: isolate_nodes
      integer, optional, intent(in) :: npes_per_node
      character(*), optional, intent(in) :: name
      integer, optional, intent(out) :: rc
      character(:), allocatable :: name_
      logical :: isolate_nodes_
      integer :: n, npes_,nnodes_, status
      character(24) :: buffer
      _UNUSED_DUMMY(unusable)
      if (present(name)) then
         name_ = name
      else
         n = this%group_descriptions%size() + 1
         write(buffer,'(i0)') n
         name_ = this%base_name // trim(buffer)
      end if
      isolate_nodes_ = .true.
      if (present(isolate_nodes)) then
         isolate_nodes_ = isolate_nodes
      endif
      npes_ = 0
      if (present(npes)) npes_ = npes
      nnodes_ = 0
      if (present(nnodes)) then
         nnodes_ = nnodes
         _ASSERT( nnodes_ ==0 .or. npes_ == 0, "npes and nnodes are exclusive")
      endif
      if (nnodes_ > 0) then
         _ASSERT(isolate_nodes, " nnodes should be isolated")
      endif
      call this%group_descriptions%push_back(CommGroupDescription(npes_, nnodes_, isolate_nodes_, name_, npes_per_node = npes_per_node, rc=status))
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine add_group_simple
Call graph
add_group_simple calls mapl_assert, mapl_return, mapl_verify, v_push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
ensemble_comm_splitter calls add_group
initialize calls add_group
new_multicommserver calls add_group
new_multigroupserver calls add_group
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
simplecommsplitter calls ensemble_comm_splitter
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main