add_attribute_1d – MAPL
add_attribute_1d Subroutine
9 statements
Source File
private subroutine add_attribute_1d(this, attr_name, attr_values, rc)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(inout), target :: this
character(len=*), intent(in) :: attr_name
class(*), intent(in) :: attr_values(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_attribute_1d(this, attr_name, attr_values, rc)
      class (Variable), target, intent(inout) :: this
      character(len=*), intent(in) :: attr_name
      class (*), intent(in) :: attr_values(:)
      integer, optional, intent(out) :: rc
      call this%attributes%insert(attr_name, Attribute(attr_values))
      _RETURN(_SUCCESS)
   end subroutine add_attribute_1d
Call graph
add_attribute_1d calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_insert_pair calls s_insert
mapl_throw_exception calls initialize
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back