add_connection – MAPL
add_connection Subroutine
12 statements
Source File
private subroutine add_connection(this, socket)
Type Bound
BaseServer
Arguments
Type Intent Optional Attributes Name
class(BaseServer), intent(inout), target :: this
class(AbstractSocket), intent(in), target :: socket
Calls
Called by
Source Code
   subroutine add_connection(this, socket)
      class (BaseServer), target, intent(inout) :: this
      class (AbstractSocket), target, intent(in) :: socket
      class(ServerThread), pointer :: thread_ptr
      integer :: k
      allocate(thread_ptr, source=ServerThread(socket, this))
      k = this%threads%size() + 1
      call thread_ptr%set_rank(k)
      call this%threads%push_Back(thread_ptr)
      nullify(thread_ptr)
      this%num_clients = this%num_clients + 1
   end subroutine add_connection
Call graph
add_connection calls set_rank, v_push_back
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
connect_to_client calls add_connection
connect_to_server calls add_connection
new_multicommserver calls add_connection
new_multigroupserver calls add_connection
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize calls connect_to_client, connect_to_server
test_connect calls connect_to_client, connect_to_server
test_connect_multi calls connect_to_client, connect_to_server
test_connect_swap_role calls connect_to_client, connect_to_server
test_connect_with_unused_process calls connect_to_client, connect_to_server
test_stress calls connect_to_client, connect_to_server
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main