add_factory – MAPL
add_factory Subroutine
23 statements
Source File
private subroutine add_factory(this, factory, id)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout), target :: this
class(AbstractGridFactory), intent(in) :: factory
integer(kind=ESMF_KIND_I8), intent(out), optional :: id
Calls
Called by
Source Code
   subroutine add_factory(this, factory, id)
      class (GridManager), target, intent(inout) :: this
      class (AbstractGridFactory), intent(in) :: factory
      integer(kind=ESMF_KIND_I8), optional, intent(out)  :: id
      type (Integer64GridFactoryMapIterator) :: iter
      class (AbstractGridFactory), pointer :: other
      ! First check to see if we already have it:
      iter = this%factories%begin()
      do while (iter /= this%factories%end())
         other => iter%value()
         if (factory == other) then
            if (present(id)) then
               id = iter%key()
            end if
            return
         end if
         call iter%next()
      end do
      ! OK - it really is new:
      this%counter = this%counter + 1 ! unique ID
      call this%factories%insert(this%counter, factory)
      if (present(id)) then
         id = this%counter
      end if
   end subroutine add_factory
Call graph
add_factory calls insert, m_begin, m_key, m_next
m_begin calls s_begin
m_next calls s_next
m_insert_pair calls s_insert
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
get_id calls add_factory
make_grid_from_factory calls add_factory