add_mask – MAPL
add_mask Subroutine
33 statements
Source File
private subroutine add_mask(this, grid, rc)
Type Bound
XYGridFactory
Arguments
Type Intent Optional Attributes Name
class(XYGridFactory), intent(in) :: this
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_mask(this,grid,rc)
      class(XYGridFactory), intent(in) :: this
      type(ESMF_Grid), intent(inout) :: grid
      integer, intent(out), optional :: rc
      integer(ESMF_KIND_I4), pointer :: mask(:,:)
      real(ESMF_KIND_R8), pointer :: fptr(:,:)
      integer :: status
      type(ESMF_VM) :: vm
      integer :: has_undef, local_has_undef
      call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
         staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=fptr, _RC)
      local_has_undef = 0
      if (any(fptr == MAPL_UNDEF)) local_has_undef = 1
      call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
         staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=fptr, _RC)
      if (any(fptr == MAPL_UNDEF)) local_has_undef = local_has_undef + 1
      call ESMF_VMGetCurrent(vm,_RC)
      call ESMF_VMAllFullReduce(vm, [local_has_undef], has_undef, 1, ESMF_REDUCE_MAX, _RC)
      _RETURN_IF(has_undef == 0)
      call ESMF_GridAddItem(grid,staggerLoc=ESMF_STAGGERLOC_CENTER,itemflag=ESMF_GRIDITEM_MASK,_RC)
      call ESMF_GridGetItem(grid,localDE=0,staggerLoc=ESMF_STAGGERLOC_CENTER, &
          itemflag=ESMF_GRIDITEM_MASK,farrayPtr=mask,_RC)
      mask = MAPL_MASK_IN
      where(fptr==MAPL_UNDEF) mask = MAPL_MASK_OUT
      _RETURN(_SUCCESS)
    end subroutine add_mask
Call graph
add_mask calls ESMF_GridAddItem, ESMF_GridGetCoord, ESMF_GridGetItem, ESMF_VMAllFullReduce, ESMF_VMGetCurrent, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
make_new_grid calls add_mask