add_variable – MAPL
add_variable Subroutine
37 statements
Source File
private subroutine add_variable(this, var_name, var, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: var_name
class(Variable), intent(in), target :: var
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
add_fvar w FileMetadata%add_variable
w
add_metadata w
w
create_file_metada w
w
create_metadata_variable w
w
CubedSphereGridFactory%append_metadata w
w
FakeHistData%run w
w
FakeHistData0%init w
w
FakeHistData0%run w
w
FileMetadata%merge w
w
initialize_ w
w
LatLonGridFactory%append_metadata w
w
main w
w
MAPL_BundleWriteNCPar w
w
MAPL_GriddedIO%CreateVariable w
w
NetCDF4_FileFormatter%inq_variables w
w
RegridSupport%transfer_metadata w
w
run w
w
setUp w
w
StationSampler%add_metadata_route_handle w
w
StationSampler%create_metadata_variable w
w
SwathGridFactory%append_metadata w
w
test_add_variable w
w
test_equal_diff_variables w
w
test_merge_meta w
w
test_serialize w
w
test_var_dims_defined w
w
test_write_read_simple_variable w
w
test_write_read_variable_attribute w
w
timeData%add_time_to_metadata w
w
TripolarGridFactory%append_metadata w
w
verticalData%append_vertical_metadata w
w
XYGridFactory%append_metadata w
w
Source Code
   subroutine add_variable(this, var_name, var, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: var_name
      class (Variable), target, intent(in) :: var
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (StringVector), pointer :: dims
      type (StringVectorIterator) :: iter
      integer, pointer :: dim_this
      character(len=:), pointer :: dim_name
      type (UnlimitedEntity), pointer :: const_value_ptr
      integer, allocatable :: shp(:), shp_const(:)
      integer :: empty(0)
      ! ensure all of var's dimensions are defined
      shp = empty
      dims => var%get_dimensions()
      iter = dims%begin()
      do while (iter /= dims%end())
         dim_name => iter%get()
         dim_this => this%dimensions%at(dim_name)
         _ASSERT( associated(dim_this),"FileMetadata::add_variable() - undefined dimension: " // dim_name)
         shp =[shp,dim_this]
         call iter%next()
      end do
      const_value_ptr => var%get_const_value()
      if ( .not. const_value_ptr%is_empty() ) then
         shp_const = const_value_ptr%get_shape()
         _ASSERT( all(shp == shp_const), "const_value shape does not match dims")
      endif
      call this%variables%insert(var_name, var)
      call this%order%push_back(var_name)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_variable
Call graph
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back