add_hist_collection – MAPL
add_hist_collection Function
20 statements
Source File
private function add_hist_collection(this, fmd, unusable, mode, rc) result(hist_collection_id)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
type(FileMetadata), intent(in) :: fmd
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: mode
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function add_hist_collection(this, fmd, unusable,mode, rc) result(hist_collection_id)
      integer :: hist_collection_id
      class (ClientManager), intent(inout) :: this
      type(FileMetadata),intent(in) :: fmd
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in) :: mode
      integer, optional, intent(out) :: rc
      class (ClientThread), pointer :: clientPtr
      integer :: i
      do i = 1, this%size()
         ClientPtr => this%clients%at(i)
         hist_collection_id = clientPtr%add_hist_collection(fmd, mode=mode)
      enddo
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function add_hist_collection
Call graph
add_hist_collection calls at, add_hist_collection, mapl_return, mapl_assert, get_connection, receive, send
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
create_file_metada calls add_hist_collection
create_from_bundle calls add_hist_collection
initialize calls add_hist_collection
mapl_bundlewritencpar calls add_hist_collection
run calls add_hist_collection
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
main calls create_from_bundle, create_file_metada
mapl_statevarwritencpar calls mapl_bundlewritencpar
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
mapl_esmfstatewritetofile calls mapl_varwritencpar
regrid_util calls main
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile