add_new_rule – MAPL
add_new_rule Subroutine
39 statements
Source File
private subroutine add_new_rule(this, key, export_rule, multi_rule, rc)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(inout) :: this
character(len=*), intent(in) :: key
type(ESMF_HConfig), intent(in) :: export_rule
logical, intent(in), optional :: multi_rule
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_new_rule(this,key,export_rule,multi_rule,rc)
      class(ExtDataConfig), intent(inout) :: this
      character(len=*), intent(in) :: key
      type(ESMF_HConfig), intent(in) :: export_rule
      logical, optional, intent(in) :: multi_rule
      integer, intent(out), optional :: rc
      integer :: semi_pos,status
      type(ExtDataRule) :: rule,ucomp,vcomp
      type(ExtDataRule), pointer :: temp_rule
      character(len=:), allocatable :: uname,vname
      logical :: usable_multi_rule
      if (present(multi_rule)) then
         usable_multi_rule = multi_rule
      else
         usable_multi_rule = .false.
      end if
      call rule%set_defaults(rc=status)
      _VERIFY(status)
      rule = ExtDataRule(export_rule,this%sample_map,key,multi_rule=usable_multi_rule,_RC)
      semi_pos = index(key,";")
      if (semi_pos > 0) then
         call rule%split_vector(key,ucomp,vcomp,rc=status)
         uname = key(1:semi_pos-1)
         vname = key(semi_pos+1:len_trim(key))
         temp_rule => this%rule_map%at(trim(uname))
         _ASSERT(.not.associated(temp_rule),"duplicated export entry key: "//trim(key))
         call this%rule_map%insert(trim(uname),ucomp)
         temp_rule => this%rule_map%at(trim(vname))
         _ASSERT(.not.associated(temp_rule),"duplicated export entry key: "//trim(key))
         call this%rule_map%insert(trim(vname),vcomp)
      else
         temp_rule => this%rule_map%at(trim(key))
         _ASSERT(.not.associated(temp_rule),"duplicated export entry key: "//trim(key))
         call this%rule_map%insert(trim(key),rule)
      end if
      _RETURN(_SUCCESS)
   end subroutine add_new_rule
Call graph
add_new_rule calls mapl_assert, insert, m_at, mapl_return, mapl_verify, set_defaults, split_vector
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_defaults calls mapl_return
split_vector calls mapl_assert, mapl_return
get_error_message calls at, insert
m_find calls s_find
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
new_extdataconfig_from_yaml calls add_new_rule, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml
initialize_ calls new_extdataoldtypescreator