add_dimension – MAPL
add_dimension Subroutine
14 statements
Source File
private subroutine add_dimension(this, dim_name, extent, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: dim_name
integer, intent(in) :: extent
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_dimension(this, dim_name, extent, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: dim_name
      integer, intent(in) :: extent
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      call this%dimensions%insert(dim_name, extent)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_dimension
Call graph
add_dimension calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls insert, at
mapl_throw_exception calls initialize
add_metadata_route_handle calls add_dimension
add_time_to_metadata calls add_dimension
append_metadata calls add_dimension
append_vertical_metadata calls add_dimension
create_file_metada calls add_dimension
init calls add_dimension
initialize_ calls add_dimension
mapl_bundlewritencpar calls add_dimension
merge calls add_dimension
run calls add_dimension
setup calls add_dimension
test_add_variable calls add_dimension
test_equal_diff_variables calls add_dimension
test_equal_dims calls add_dimension
test_get_dimension calls add_dimension
test_get_dimensions calls add_dimension
test_merge_meta calls add_dimension
test_serialize calls add_dimension
test_var_dims_defined calls add_dimension
test_write_read_simple_attribute calls add_dimension
test_write_read_simple_variable calls add_dimension
test_write_read_trivial calls add_dimension
test_write_read_variable_attribute calls add_dimension
transfer_metadata calls add_dimension
main calls add_dimension