add_metadata – MAPL
add_metadata Module Subroutine
80 statements
Source File
module subroutine add_metadata(this, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(MaskSamplerGeosat), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
module subroutine  add_metadata(this,rc)
    class(MaskSamplerGeosat), intent(inout) :: this
    integer, optional, intent(out)          :: rc
    type(variable)   :: v
    type(ESMF_Field) :: field
    integer          :: fieldCount
    integer          :: field_rank
    integer          :: nstation
    logical          :: is_present
    integer          :: ub(ESMF_MAXDIM)
    integer          :: lb(ESMF_MAXDIM)
    logical          :: do_vertical_regrid
    integer          :: status
    integer          :: i
    character(len=ESMF_MAXSTR), allocatable ::  fieldNameList(:)
    character(len=ESMF_MAXSTR) :: var_name, long_name, units, vdims
    character(len=40) :: datetime_units
    !__ 1. metadata add_dimension,
    !     add_variable for time, latlon, mask_points
    !
    call this%vdata%append_vertical_metadata(this%metadata,this%bundle,_RC) ! specify lev in fmd
    call this%time_info%add_time_to_metadata(this%metadata,_RC)
    call this%metadata%add_dimension('mask_index', this%npt_mask_tot)
    v = Variable(type=pFIO_REAL64, dimensions='mask_index')
    call v%add_attribute('long_name','longitude')
    call v%add_attribute('unit','degree_east')
    call this%metadata%add_variable('longitude',v)
    v = Variable(type=pFIO_REAL64, dimensions='mask_index')
    call v%add_attribute('long_name','latitude')
    call v%add_attribute('unit','degree_north')
    call this%metadata%add_variable('latitude',v)
    ! To be added when values are available
    !v = Variable(type=pFIO_INT32, dimensions='mask_index')
    !call v%add_attribute('long_name','The Cubed Sphere Global Face ID')
    !call this%metadata%add_variable('mask_CS_Face_ID',v)
    !
    !v = Variable(type=pFIO_INT32, dimensions='mask_index')
    !call v%add_attribute('long_name','The Cubed Sphere Global Index I')
    !call this%metadata%add_variable('mask_CS_global_index_I',v)
    !
    !v = Variable(type=pFIO_INT32, dimensions='mask_index')
    !call v%add_attribute('long_name','The Cubed Sphere Global Index J')
    !call this%metadata%add_variable('mask_CS_global_index_J',v)
    !__ 2. filemetadata: extract field from bundle, add_variable to metadata
    !
    call ESMF_FieldBundleGet(this%bundle, fieldCount=fieldCount, _RC)
    allocate (fieldNameList(fieldCount), _STAT)
    call ESMF_FieldBundleGet(this%bundle, fieldNameList=fieldNameList, _RC)
    do i=1, fieldCount
       var_name=trim(fieldNameList(i))
       call ESMF_FieldBundleGet(this%bundle,var_name,field=field,_RC)
       call ESMF_FieldGet(field,rank=field_rank,_RC)
       call ESMF_AttributeGet(field,name="LONG_NAME",isPresent=is_present,_RC)
       if ( is_present ) then
          call ESMF_AttributeGet(field, NAME="LONG_NAME",VALUE=long_name, _RC)
       else
          long_name = var_name
       endif
       call ESMF_AttributeGet(field,name="UNITS",isPresent=is_present,_RC)
       if ( is_present ) then
          call ESMF_AttributeGet(field, NAME="UNITS",VALUE=units, _RC)
       else
          units = 'unknown'
       endif
       if (field_rank==2) then
          vdims = "mask_index,time"
          v = variable(type=PFIO_REAL32,dimensions=trim(vdims))
       else if (field_rank==3) then
          vdims = "lev,mask_index,time"
          call ESMF_FieldGet(field,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
          v = variable(type=PFIO_REAL32,dimensions=trim(vdims))
       end if
       call v%add_attribute('units',         trim(units))
       call v%add_attribute('long_name',     trim(long_name))
       call v%add_attribute('missing_value', MAPL_UNDEF)
       call v%add_attribute('_FillValue',    MAPL_UNDEF)
       call v%add_attribute('valid_range',   (/-MAPL_UNDEF,MAPL_UNDEF/))
       call this%metadata%add_variable(trim(var_name),v,_RC)
    end do
    deallocate (fieldNameList, _STAT)
    _RETURN(_SUCCESS)
  end subroutine add_metadata
Call graph
add_metadata calls ESMF_AttributeGet, esmf_fieldbundleget, esmf_fieldget, add_attribute, add_dimension, add_time_to_metadata, add_variable, append_vertical_metadata, mapl_return, mapl_verify, add_metadata
add_dimension calls mapl_return, insert
add_time_to_metadata calls add_dimension, add_variable, mapl_return, mapl_verify, define_time_variable
add_variable calls mapl_return, at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
append_vertical_metadata calls ESMF_AttributeGet, esmf_fieldbundleget, esmf_fieldget, add_attribute, add_dimension, add_variable, mapl_return, mapl_verify, mapl_assert, add_const_value
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
initialize_ calls add_metadata, initialize_