add_child – MAPL
add_child Function
9 statements
Source File
private function add_child(this, name, composite) result(child)
Type Bound
ConcreteComposite
Arguments
Type Intent Optional Attributes Name
class(ConcreteComposite), intent(inout), target :: this
character(len=*), intent(in) :: name
class(AbstractComposite), intent(in) :: composite
Return Value class(AbstractComposite), pointer
Calls
Called by
Source Code
   function add_child(this, name, composite) result(child)
      class(AbstractComposite), pointer :: child
      class(ConcreteComposite), target, intent(inout) :: this
      character(*), intent(in) :: name
      class(AbstractComposite), intent(in) :: composite
      call this%children_names%push_back(name)
      call this%children%insert(name, composite)
      child => this%children%at(name)
   end function add_child
Call graph
add_child calls insert, m_at, push_back, add_child
m_at calls m_find
m_find calls s_find
m_insert_pair calls s_insert
s_find calls at, exists, find_index, s_ordereq
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
test_get_child calls add_child
add_child_component calls add_child
addchild_preamble calls add_child
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
mapl_addchild calls addchildfromdsometa, addchildfrommeta
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta