add_var_attribute_0d – MAPL
add_var_attribute_0d Subroutine
17 statements
Source File
private subroutine add_var_attribute_0d(this, var_name, attr_name, value, unusable, rc)
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: attr_name
class(*), intent(in) :: value
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine add_var_attribute_0d(this, var_name, attr_name, value, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: var_name
      character(len=*), intent(in) :: attr_name
      class (*), intent(in) :: value
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class (Variable), pointer :: var
      var => this%get_variable(var_name)
      call var%add_attribute(attr_name, value)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine add_var_attribute_0d
Call graph
add_var_attribute_0d calls add_attribute, get_variable, mapl_return
get_variable calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
add_attribute_1d calls mapl_return, insert
get_error_message calls at, insert
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find