add_column – MAPL
add_column Subroutine
16 statements
Source File
private subroutine add_column(this, column)
Type Bound
MultiColumn
Arguments
Type Intent Optional Attributes Name
class(MultiColumn), intent(inout) :: this
class(TextColumn), intent(in) :: column
Calls
Called by
Source Code
   subroutine add_column(this, column)
      class (MultiColumn), intent(inout) :: this
      class (TextColumn), intent(in) :: column
      integer :: h, h0, w
      w = this%get_width()
      if (this%columns%size() > 0) then
         call this%columns%push_back(SeparatorColumn(' '))
         w = w + 1
      end if
      call this%columns%push_back(column)
      h0 = size(this%shared_header) + this%get_num_rows_separator()
      h = column%get_num_rows_header()
      this%num_rows_header = max(this%num_rows_header, h0 + h)
      w = w + column%get_width()
      call this%set_width(w)
   end subroutine add_column
Call graph
add_column calls get_num_rows_header, get_num_rows_separator, get_width, set_width, v_push_back
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column, generate_report, finalize, mapl_finalize
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report, finalize, mapl_finalize
finalize_io_clients_servers calls finalize
finalize_mpi calls mapl_finalize
run calls mapl_finalize, finalize_io_clients_servers, finalize_mpi
regrid_util calls main
ut_regridding calls finalize, mapl_finalize
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
comp_testing_driver calls main
extdata_driver calls run