add_horz_coordinates_from_ABIfile – MAPL
add_horz_coordinates_from_ABIfile Subroutine
87 statements
Source File
private subroutine add_horz_coordinates_from_ABIfile(this, grid, unusable, rc)
Uses
MAPL_IOMod
MAPL_Constants
MAPL_CommsMod
Type Bound
XYGridFactory
Arguments
Type Intent Optional Attributes Name
class(XYGridFactory), intent(in) :: this
type(ESMF_Grid), intent(inout) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine add_horz_coordinates_from_ABIfile(this, grid, unusable, rc)
      use MAPL_CommsMod
      use MAPL_IOMod
      use MAPL_Constants
      class (XYGridFactory), intent(in) :: this
      type (ESMF_Grid), intent(inout) :: grid
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_VM) :: vm
      integer :: i, j
      integer :: ix, jx
      integer :: i_1, i_n, j_1, j_n
      real(REAL64), pointer :: fptr_x(:,:)   ! lon
      real(REAL64), pointer :: fptr_y(:,:)   ! lat
      real(REAL64), pointer :: x(:)
      real(REAL64), pointer :: y(:)
      real(REAL64), pointer :: lambda0(:)
      real(REAL64) :: lambda0_deg
      real(REAL64) :: x0, y0
      real(REAL64) :: lam_sat
      character(len=ESMF_MAXSTR) :: fn, key_x, key_y, key_p, key_p_att
      _UNUSED_DUMMY(unusable)
      call MAPL_Grid_Interior (grid, i_1, i_n, j_1, j_n)
      call MAPL_AllocateShared(x,[this%Xdim_true],transroot=.true.,_RC)
      call MAPL_AllocateShared(y,[this%Ydim_true],transroot=.true.,_RC)
      call MAPL_AllocateShared(lambda0,[1],transroot=.true.,_RC)
      call MAPL_SyncSharedMemory(_RC)
      if (mapl_am_i_root()) then
         fn    = this%grid_file_name
         key_x = this%var_name_x
         key_y = this%var_name_y
         key_p = this%var_name_proj
         key_p_att = this%att_name_proj
         call get_v1d_netcdf_R8_complete (fn, key_x, x, _RC)
         call get_v1d_netcdf_R8_complete (fn, key_y, y, _RC)
         call get_att_real_netcdf (fn, key_p, key_p_att, lambda0_deg, _RC)
         lambda0 = lambda0_deg*MAPL_DEGREES_TO_RADIANS_R8
      end if
      call MAPL_SyncSharedMemory(_RC)
      call ESMF_VMGetCurrent(vm, _RC)
      call MAPL_BcastShared (vm, data=x, N=this%Xdim_true, Root=MAPL_ROOT, RootOnly=.false., _RC)
      call MAPL_BcastShared (vm, data=y, N=this%Ydim_true, Root=MAPL_ROOT, RootOnly=.false., _RC)
      call MAPL_BcastShared (vm, data=lambda0, N=1,        Root=MAPL_ROOT, RootOnly=.false., _RC)
      call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=fptr_x, _RC)
      call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=fptr_y, _RC)
      lam_sat = lambda0(1)
      do i = i_1, i_n
         ix = i - i_1 + 1
         do j= j_1, j_n
            jx = j - j_1 + 1
            x0 = x( i * this%thin_factor )
            y0 = y( j * this%thin_factor )
            call ABI_XY_2_lonlat (x0, y0, lam_sat, fptr_x(ix, jx), fptr_y(ix, jx) )
         end do
      end do
      call MAPL_SyncSharedMemory(_RC)
      if(MAPL_ShmInitialized) then
         call MAPL_DeAllocNodeArray(x,_RC)
         call MAPL_DeAllocNodeArray(y,_RC)
      else
         deallocate(x)
         deallocate(y)
      end if
      _RETURN(_SUCCESS)
    end subroutine add_horz_coordinates_from_ABIfile
Call graph
add_horz_coordinates_from_abifile calls ESMF_GridGetCoord, ESMF_VMGetCurrent, mapl_allocateshared, mapl_am_i_root, mapl_bcastshared, mapl_deallocnodearray, mapl_grid_interior, mapl_syncsharedmemory, abi_xy_2_lonlat, get_att_real_netcdf, get_v1d_netcdf_r8_complete, mapl_return, mapl_verify
make_new_grid calls add_horz_coordinates_from_abifile