add_prototype_by_grid_types – MAPL
add_prototype_by_grid_types Subroutine
10 statements
Source File
private subroutine add_prototype_by_grid_types(this, grid_type_in, grid_type_out, regrid_method, prototype)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout) :: this
character(len=*), intent(in) :: grid_type_in
character(len=*), intent(in) :: grid_type_out
integer, intent(in) :: regrid_method
class(AbstractRegridder), intent(in) :: prototype
Calls
Called by
Source Code
   subroutine add_prototype_by_grid_types(this, grid_type_in, grid_type_out, regrid_method, prototype)
      class (RegridderManager), intent(inout) :: this
      character(len=*), intent(in) :: grid_type_in
      character(len=*), intent(in) :: grid_type_out
      integer, intent(in) :: regrid_method
      class (AbstractRegridder), intent(in) :: prototype
      type (RegridderTypeSpec) :: regridder_type
      regridder_type = RegridderTypeSpec(grid_type_in, grid_type_out, regrid_method)
      call this%add_prototype(regridder_type, prototype)
   end subroutine add_prototype_by_grid_types
Call graph
add_prototype_by_grid_types calls add_prototype
init calls add_prototype
make_regridder_from_grids calls init