add_hist_collection – MAPL
add_hist_collection Function
25 statements
Source File
private function add_hist_collection(this, fmd, unusable, mode, rc) result(hist_collection_id)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout), target :: this
type(FileMetadata), intent(in) :: fmd
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: mode
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function add_hist_collection(this, fmd, unusable,  mode, rc) result(hist_collection_id)
      integer :: hist_collection_id
      class (ClientThread), target, intent(inout) :: this
      type(FileMetadata),intent(in) :: fmd
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in) :: mode
      integer, optional, intent(out) :: rc
      class (AbstractMessage), pointer :: message
      class(AbstractSocket), pointer :: connection
      connection=>this%get_connection()
      call connection%send(AddHistCollectionMessage(fmd, mode=mode))
      message => connection%receive()
      select type(message)
      type is(IDMessage)
        hist_collection_id = message%id
      class default
        _FAIL( " should get id message")
      end select
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function add_hist_collection
Call graph
add_hist_collection calls mapl_assert, get_connection, mapl_return, receive, send, add_hist_collection
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run calls add_hist_collection
create_file_metada calls add_hist_collection
create_from_bundle calls add_hist_collection
initialize calls add_hist_collection
mapl_bundlewritencpar calls add_hist_collection
main calls run, create_from_bundle, create_file_metada
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
mapl_esmfstatewritetofile calls mapl_varwritencpar
regrid_util calls main