add_data_message – MAPL
add_data_message Subroutine
18 statements
Source File
private subroutine add_data_message(this, msg, i_ptr, rc)
Type Bound
ForwardDataAndMessage
Arguments
Type Intent Optional Attributes Name
class(ForwardDataAndMessage), intent(inout) :: this
class(AbstractMessage) :: msg
integer, intent(in) :: i_ptr(:)
integer, intent(out), optional :: rc
Calls
Called by
Call graph
add_data_message calls mapl_return, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
receive_output_data calls add_data_message