AddChildFromDSO_old – MAPL
AddChildFromDSO_old Function
16 statements
Source File
private recursive function AddChildFromDSO_old(name, userRoutine, grid, ParentGC, SharedObj, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
type(ESMF_GridComp), intent(inout), optional :: ParentGC
character(len=*), intent(in), optional :: SharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
AddChildFromDSO_old
Source Code
   recursive integer function AddChildFromDSO_old(name, userRoutine, grid, ParentGC, SharedObj, petList, configFile, RC)
      !ARGUMENTS:
      character(len=*), intent(IN)    :: name
      character(len=*), intent(in)    :: userRoutine
      type(ESMF_Grid),  optional,    intent(INout) :: grid
      type(ESMF_GridComp), optional, intent(INOUT) :: ParentGC
      character(len=*), optional, intent(in)       :: SharedObj
      integer, optional  , intent(IN   ) :: petList(:)
      character(len=*), optional, intent(IN   ) :: configFile
      integer, optional  , intent(  OUT) :: rc
      !EOP
      integer                    :: status
      _ASSERT(present(ParentGC),'must have a parent to use this interface')
      addchildfromdso_old = addChildFromDSO(parentGC, name, userRoutine, grid=grid, sharedObj=sharedObj, petList=petList, configFile=configFile, _RC)
      _RETURN(ESMF_SUCCESS)
   end function AddChildFromDSO_Old
Call graph
addchildfromdso_old calls mapl_assert, mapl_verify, addchildfromdso, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
addchildfromdso calls mapl_verify, mapl_return, mapl_internalstateretrieve, addchildfromdsometa
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_throw_exception calls initialize
addchildfromdsometa calls mapl_verify, mapl_return, get_global_time_profiler, get_file_extension, is_valid_dso_name, addchild_preamble, adjust_dso_name, esmf_gridcompsetservices
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
get_file_extension calls find_extension_index
mapl_internalstatecreate calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompsetinternalstate
is_valid_dso_name calls get_file_extension, is_valid_dso_extension
addchild_preamble calls mapl_assert, mapl_verify, mapl_return, mapl_internalstatecreate, esmf_vmget, esmf_configloadfile, esmf_configcreate, esmf_gridcompcreate, esmf_statecreate, esmf_vmgetcurrent
adjust_dso_name calls get_file_basename
mapl_addchild calls addchildfromdso_old
setservices calls mapl_addchild, setservices
initialize_gc calls mapl_addchild