AddChildFromMeta – MAPL
AddChildFromMeta Function
48 statements
Source File
private recursive function AddChildFromMeta(META, NAME, GRID, CONFIGFILE, SS, parentGC, petList, rc)
$ gridcomp => META%GET_CHILD_GRIDCOMP(I)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: META
character(len=*), intent(in) :: NAME
type(ESMF_Grid), intent(inout), optional :: GRID
character(len=*), intent(in), optional :: CONFIGFILE
real :: SS
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(in), optional :: petList(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
AddChildFromMeta
Source Code
   recursive integer function AddChildFromMeta(META, NAME, GRID, &
        CONFIGFILE, SS, PARENTGC, &
        petList, RC)
      !ARGUMENTS:
      type(MAPL_MetaComp), target,   intent(INOUT) :: META
      character(len=*),              intent(IN   ) :: NAME
      type(ESMF_Grid),  optional,    intent(INout) :: GRID
      character(len=*), optional,    intent(IN   ) :: CONFIGFILE
      external                                     :: SS
      type(ESMF_GridComp), optional, intent(IN   ) :: parentGC
      integer,           optional  , intent(IN   ) :: petList(:)
      integer,           optional  , intent(  OUT) :: rc
      !EOPI
      integer                                     :: status
      integer                                     :: I
      type(MAPL_MetaComp), pointer                :: child_meta
      class(BaseProfiler), pointer                :: t_p
      integer :: userRC
      character(:), allocatable :: stage_description
      class(Logger), pointer :: lgr
      if (.not.allocated(META%GCNameList)) then
         ! this is the first child to be added
         allocate(META%GCNameList(0), __STAT__)
      end if
      I = META%get_num_children() + 1
      AddChildFromMeta = I
      call AddChild_preamble(meta, I, name, grid=grid, configfile=configfile, parentGC=parentgc, petList=petlist, child_meta=child_meta, _RC)
      stage_description = 'setServices() of the gridded component <'//trim(name)//'>'
      lgr => logging%get_logger('MAPL.GENERIC')
      t_p => get_global_time_profiler()
      call t_p%start(trim(NAME),_RC)
      call child_meta%t_profiler%start(_RC)
      call child_meta%t_profiler%start('SetService',_RC)
!!$     gridcomp => META%GET_CHILD_GRIDCOMP(I)
      call lgr%debug("Started %a", stage_description)
      call ESMF_GridCompSetServices ( child_meta%gridcomp, SS, userRC=userRC, _RC )
      _VERIFY(userRC)
      call lgr%debug("Finished %a", stage_description)
      call child_meta%t_profiler%stop('SetService',_RC)
      call child_meta%t_profiler%stop(_RC)
      call t_p%stop(trim(NAME),_RC)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end function AddChildFromMeta
Call graph
addchildfrommeta calls mapl_verify, get_global_time_profiler, addchild_preamble, esmf_gridcompsetservices, mapl_return
mapl_verify calls mapl_throw_exception
addchild_preamble calls mapl_verify, mapl_return, mapl_assert, esmf_configloadfile, esmf_configcreate, esmf_gridcompcreate, esmf_statecreate, mapl_internalstatecreate, esmf_vmgetcurrent, esmf_vmget
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_internalstatecreate calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompsetinternalstate
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
addchildfromgc calls addchildfrommeta
mapl_addchild calls addchildfrommeta, addchildfromgc
setservices calls mapl_addchild, setservices
initialize_gc calls mapl_addchild