AddChildFromGC – MAPL
AddChildFromGC Function
16 statements
Source File
private recursive function AddChildFromGC(GC, name, SS, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: name
real :: SS
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
AddChildFromGC
Source Code
   recursive integer function AddChildFromGC(GC, name, SS, petList, configFile, RC)
      !ARGUMENTS:
      type(ESMF_GridComp), intent(INOUT) :: GC
      character(len=*),    intent(IN   ) :: name
      external                           :: SS
      integer, optional  , intent(IN   ) :: petList(:)
      character(len=*), optional, intent(IN   ) :: configFile
      integer, optional  , intent(  OUT) :: rc
      !EOPI
      integer                                     :: status
      type(MAPL_MetaComp), pointer                :: META
      call MAPL_InternalStateRetrieve(GC, META, _RC)
      AddChildFromGC = AddChildFromMeta(Meta, name, SS=SS, PARENTGC=GC, petList=petList, configFile=configFile, _RC)
      _RETURN(ESMF_SUCCESS)
   end function AddChildFromGC
Call graph
addchildfromgc calls mapl_internalstateretrieve, mapl_return, addchildfrommeta, mapl_verify
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_return calls get_error_message, mapl_throw_exception
addchildfrommeta calls mapl_return, mapl_verify, get_global_time_profiler, esmf_gridcompsetservices, addchild_preamble
mapl_verify calls mapl_throw_exception
mapl_internalstateget calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_internalstatecreate calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompsetinternalstate
mapl_throw_exception calls initialize
addchild_preamble calls mapl_return, mapl_verify, mapl_internalstatecreate, esmf_vmget, esmf_configloadfile, mapl_assert, esmf_configcreate, esmf_gridcompcreate, esmf_statecreate, esmf_vmgetcurrent
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_addchild calls addchildfromgc
setservices calls mapl_addchild, setservices
initialize_gc calls mapl_addchild