AddChildFromDSO – MAPL
AddChildFromDSO Function
18 statements
Source File
private recursive function AddChildFromDSO(gc, name, userRoutine, grid, sharedObj, petList, configFile, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
character(len=*), intent(in), optional :: sharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
AddChildFromDSO
Source Code
   recursive integer function AddChildFromDSO(gc, name, userRoutine, grid, sharedObj, petList, configFile, RC)
      !ARGUMENTS:
      type(ESMF_GridComp), intent(INOUT) :: gc
      character(len=*), intent(IN)    :: name
      character(len=*), intent(in)    :: userRoutine
      type(ESMF_Grid),  optional,    intent(INout) :: grid
      character(len=*), optional, intent(in)       :: sharedObj
      integer, optional  , intent(IN   ) :: petList(:)
      character(len=*), optional, intent(IN   ) :: configFile
      integer, optional  , intent(  OUT) :: rc
      !EOP
      integer                    :: status
      type(MAPL_MetaComp), pointer                :: META
      call MAPL_InternalStateRetrieve(gc, meta, _RC)
      AddChildFromDSO = AddChildFromDSOMeta(meta, name, userRoutine, grid=grid, sharedObj=sharedObj, petList=petList, configFile=configFile, parentGC=gc, _RC)
      _RETURN(ESMF_SUCCESS)
   end function AddChildFromDSO
Call graph
addchildfromdso calls mapl_internalstateretrieve, mapl_return, mapl_verify, addchildfromdsometa
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
addchildfromdsometa calls mapl_return, mapl_verify, is_valid_dso_name, get_global_time_profiler, get_file_extension, addchild_preamble, adjust_dso_name, esmf_gridcompsetservices
mapl_internalstateget calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_internalstatecreate calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompsetinternalstate
is_valid_dso_name calls get_file_extension, is_valid_dso_extension
mapl_throw_exception calls initialize
get_file_extension calls find_extension_index
addchild_preamble calls mapl_return, mapl_verify, mapl_internalstatecreate, esmf_statecreate, esmf_vmgetcurrent, esmf_vmget, esmf_configloadfile, mapl_assert, esmf_configcreate, esmf_gridcompcreate
adjust_dso_name calls get_file_basename
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file_basename calls find_extension_index
addchildfromdso_old calls addchildfromdso
mapl_addchild calls addchildfromdso, addchildfromdso_old
setservices calls mapl_addchild, setservices
initialize_gc calls mapl_addchild