AddChildFromDSOMeta – MAPL
AddChildFromDSOMeta Function
51 statements
Source File
private recursive function AddChildFromDSOMeta(META, name, userRoutine, grid, sharedObj, petList, configFile, parentGC, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: META
character(len=*), intent(in) :: name
character(len=*), intent(in) :: userRoutine
type(ESMF_Grid), intent(inout), optional :: grid
character(len=*), intent(in), optional :: sharedObj
integer, intent(in), optional :: petList(:)
character(len=*), intent(in), optional :: configFile
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
AddChildFromDSOMeta
Source Code
   recursive integer function AddChildFromDSOMeta(meta, name, userRoutine, grid, sharedObj, petList, configFile, parentGC, RC)
      !ARGUMENTS:
      type(MAPL_MetaComp), target,   intent(INOUT) :: META
      character(len=*), intent(IN)                 :: name
      character(len=*), intent(in)                 :: userRoutine
      type(ESMF_Grid),  optional,    intent(INOUT) :: grid
      character(len=*), optional, intent(IN)       :: sharedObj
      integer, optional, intent(IN)             :: petList(:)
      character(len=*), optional, intent(IN)    :: configFile
      type(ESMF_GridComp), optional, intent(IN) :: parentGC
      integer, optional, intent(OUT)            :: rc
      !EOP
      integer :: status
      integer :: userRC
      integer :: I
      type(MAPL_MetaComp), pointer :: child_meta
      class(BaseProfiler), pointer :: t_p
      class(Logger), pointer :: lgr
      character(len=:), allocatable :: shared_object_library_to_load
      character(len=:), allocatable :: extension
      if (.not.allocated(meta%GCNameList)) then
         ! this is the first child to be added
         allocate(meta%GCNameList(0), _STAT)
      end if
      I = meta%get_num_children() + 1
      AddChildFromDSOMeta = I
      call AddChild_preamble(meta, I, name, grid=grid, configfile=configfile, parentGC=parentGC, petList=petlist, child_meta=child_meta, _RC)
      t_p => get_global_time_profiler()
      call t_p%start(trim(name),_RC)
      call child_meta%t_profiler%start(_RC)
      call child_meta%t_profiler%start('SetService',_RC)
      if (.not. is_valid_dso_name(SharedObj)) then
         extension = get_file_extension(SharedObj)
         lgr => logging%get_logger('MAPL.GENERIC')
         call lgr%warning("AddChildFromDSO: changing shared library extension from %a~ to system specific extension %a~", &
              "'"//extension//"'", "'"//SYSTEM_DSO_EXTENSION//"'")
      end if
      shared_object_library_to_load = adjust_dso_name(sharedObj)
      call ESMF_GridCompSetServices ( child_meta%gridcomp, userRoutine, &
           sharedObj=shared_object_library_to_load,userRC=userRC,_RC)
      _VERIFY(userRC)
      call child_meta%t_profiler%stop('SetService',_RC)
      call child_meta%t_profiler%stop(_RC)
      call t_p%stop(trim(name),_RC)
      _RETURN(ESMF_SUCCESS)
   end function AddChildFromDSOMeta
Call graph
addchildfromdsometa calls mapl_verify, get_global_time_profiler, get_file_extension, is_valid_dso_name, addchild_preamble, adjust_dso_name, esmf_gridcompsetservices, mapl_return
mapl_verify calls mapl_throw_exception
get_file_extension calls find_extension_index
is_valid_dso_name calls get_file_extension, is_valid_dso_extension
addchild_preamble calls mapl_verify, mapl_return, esmf_vmget, mapl_assert, esmf_configloadfile, esmf_configcreate, esmf_gridcompcreate, esmf_statecreate, mapl_internalstatecreate, esmf_vmgetcurrent
adjust_dso_name calls get_file_basename
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_internalstatecreate calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompsetinternalstate
get_file_basename calls find_extension_index
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
addchildfromdso calls addchildfromdsometa
mapl_addchild calls addchildfromdsometa, addchildfromdso, addchildfromdso_old
addchildfromdso_old calls addchildfromdso
setservices calls mapl_addchild, setservices
initialize_gc calls mapl_addchild