AddChild_preamble – MAPL
AddChild_preamble Subroutine
124 statements
Source File
private recursive subroutine AddChild_preamble(meta, I, name, grid, configfile, parentGC, petList, child_meta, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: meta
integer, intent(in) :: I
character(len=*), intent(in) :: name
type(ESMF_Grid), intent(inout), optional :: grid
character(len=*), intent(in), optional :: configfile
type(ESMF_GridComp), intent(in), optional :: parentGC
integer, intent(in), optional :: petList(:)
type(MAPL_MetaComp), pointer :: child_meta
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
AddChild_preamble
Source Code
   recursive subroutine AddChild_preamble(meta, I, name, grid, configfile, parentGC, petlist, child_meta, unusable, rc)
      type(MAPL_MetaComp), target,   intent(INOUT) :: meta
      integer, intent(in) :: I
      character(*), intent(in) :: name
      type(ESMF_Grid),  optional,    intent(INout) :: grid
      character(len=*), optional,    intent(IN   ) :: configfile
      type(ESMF_GridComp), optional, intent(IN   ) :: parentGC
      integer,           optional  , intent(IN   ) :: petList(:)
      type(MAPL_MetaComp), pointer                :: child_meta
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer                                     :: status
      type(MAPL_MetaComp), pointer                :: tmp_meta
      class(AbstractFrameworkComponent), pointer  :: tmp_framework
      character(len=ESMF_MAXSTR)                  :: child_name
      type(ESMF_Context_Flag)                     :: contextFlag
      class(Logger), pointer :: lgr
      type(ESMF_State), pointer :: child_import_state
      type(ESMF_State), pointer :: child_export_state
      type(StubComponent) :: stub_component
      type(ESMF_VM) :: vm
      integer :: comm
      call make_full_name(name, child_name, parentGC, _RC)
      call grow_children_names(meta%GCNamelist, child_name, _RC)
      allocate(tmp_meta, _STAT)
      tmp_framework => META%add_child(child_name, tmp_meta)
      deallocate(tmp_meta)
      _ASSERT(associated(tmp_framework),'add_child() failed')
      select type (tmp_framework)
         class is (MAPL_MetaComp)
         child_meta => tmp_framework
         call child_meta%set_component(stub_component)
         if (present(petList)) then
            contextFlag = ESMF_CONTEXT_OWN_VM ! this is default
         else
            contextFlag = ESMF_CONTEXT_PARENT_VM ! more efficient
         end if
         if (present(configfile)) then
            child_meta%cf = ESMF_ConfigCreate(_RC)
            call ESMF_ConfigLoadFile(child_meta%cf, configfile, _RC)
         else ! use parents config
            child_meta%cf = meta%cf
         end if
         child_meta%gridcomp = ESMF_GridCompCreate   ( &
              name   = child_name,          &
              CONFIG = child_meta%cf,       &
              grid = grid,                  &
              petList = petList,            &
              contextFlag = contextFlag,    &
              _RC)
         ! Create each child's import/export state
         ! ----------------------------------
         child_import_state => META%get_child_import_state(i)
         child_import_state = ESMF_StateCreate (             &
              name = trim(META%GCNameList(I)) // '_Imports', &
              stateIntent = ESMF_STATEINTENT_IMPORT, _RC)
         child_export_state => META%get_child_export_state(i)
         child_export_state = ESMF_StateCreate (             &
              name = trim(META%GCNameList(I)) // '_Exports', &
              stateIntent = ESMF_STATEINTENT_EXPORT, _RC)
         ! create MAPL_Meta
         call MAPL_InternalStateCreate ( child_meta%gridcomp, child_meta, _RC)
         ! Create child components time profiler
         call ESMF_VMGetCurrent(vm, _RC)
         call ESMF_VMGet(vm, mpiCommunicator=comm, _RC)
         CHILD_META%t_profiler = DistributedProfiler(trim(name), MpiTimerGauge(), comm=comm)
      end select
      ! put parentGC there
      if (present(parentGC)) then
         allocate(child_meta%parentGC, __STAT__)
         child_meta%parentGC = parentGC
      end if
      lgr => logging%get_logger('MAPL.GENERIC')
      call lgr%debug('Adding logger for component %a ',trim(child_name))
      child_meta%full_name = meta%full_name // SEPARATOR // trim(child_name)
      child_meta%compname = trim(child_name)
      call child_meta%set_logger(logging%get_logger(child_meta%full_name))
      ! copy communicator to childs mapl_metacomp
      call ESMF_VMGetCurrent(vm, _RC)
      call ESMF_VMGet(vm, mpiCommunicator=comm, _RC)
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(unusable)
   contains
      subroutine make_full_name(name, child_name, parentGC, unusable, rc)
         character(*), intent(in) :: name
         character(*), intent(out) :: child_name
         type(ESMF_GridComp), optional, intent(in) :: parentGC
         class(KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         integer :: status
         character(ESMF_MAXSTR) :: pname
         type(ESMF_GridComp) :: tmp_gc ! kludge because ESMF makes things INTENT(INOUT)
         child_name = trim(name)
         ! Adjust with parent name if provided
         if (index(name,":") == 0) then
            if (present(parentGC)) then
               tmp_gc = parentGC
               call ESMF_GridCompGet(tmp_gc, name=pname, _RC)
               child_name = pname(1:index(pname,":"))//trim(name)
            end if
         end if
         _RETURN(ESMF_SUCCESS)
         _UNUSED_DUMMY(unusable)
      end subroutine make_full_name
      subroutine grow_children_names(names, child_name, unusable, rc)
         character(ESMF_MAXSTR), allocatable, intent(inout) :: names(:)
         character(*), intent(in) :: child_name
         class(KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         character(ESMF_MAXSTR), allocatable :: tmp(:)
         integer :: n
         integer :: status
         ! realloc names
         n = size(names)
         allocate(tmp(n+1), __STAT__)
         tmp(1:n) = names
         deallocate(names)
         call move_alloc(from=tmp, to=names)
         names(n+1) = child_name
         _RETURN(ESMF_SUCCESS)
         _UNUSED_DUMMY(unusable)
      end subroutine grow_children_names
   end subroutine AddChild_preamble
Call graph
addchild_preamble calls ESMF_ConfigCreate, ESMF_ConfigLoadFile, ESMF_GridCompCreate, ESMF_VMGet, ESMF_VMGetCurrent, add_child, debug, esmf_statecreate, gcnamelist, get_logger, mapl_assert, get_child_export_state, get_child_import_state, mapl_internalstatecreate, mapl_return, mapl_verify, set_component, set_logger
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_child_export_state calls get_export_state, get_ith_child
get_child_import_state calls get_import_state, get_ith_child
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
mapl_addchild calls addchildfromdsometa, addchildfrommeta, addchildfromdso, addchildfromgc, addchildfromdso_old
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild
main calls run_component_driver