AddGrid – MAPL
AddGrid Subroutine
62 statements
Source File
private subroutine AddGrid(this, output_grids, resolution, rc)
Uses
MAPL_ConfigMod
MAPL_BaseMod
MAPL_GridManagerMod
MAPL_GenericMod
MAPL_AbstractGridFactoryMod
MAPL_StringGridMapMod
Type Bound
HistoryCollection
Arguments
Type Intent Optional Attributes Name
class(HistoryCollection), intent(inout) :: this
type(StringGridMap), intent(inout) :: output_grids
integer, intent(in) :: resolution(2)
integer, intent(inout), optional :: rc
Calls
Contents
Source Code
AddGrid
Source Code
     subroutine AddGrid(this,output_grids,resolution,rc)
        use MAPL_GridManagerMod
        use MAPL_AbstractGridFactoryMod
        use MAPL_ConfigMod
        use MAPL_GenericMod
        use MAPL_BaseMod
        use MAPL_StringGridMapMod
        class (HistoryCollection), intent(inout) :: this
        integer, intent(in) :: resolution(2)
        type (StringGridMap), intent(inout) :: output_grids
        integer, intent(inout), optional :: rc
        integer :: status
        character(len=*), parameter :: Iam = "AddGrid"
        type(ESMF_Config) :: cfg
        integer :: nx,ny,im_world,jm_world
        character(len=ESMF_MAXSTR) :: tlabel
        type(ESMF_Grid) :: output_grid
        type(ESMF_Grid), pointer :: lgrid
        class(AbstractGridFactory), pointer :: factory
        tlabel="NewHistGrid"
        im_world=resolution(1)
        jm_world=resolution(2)
        cfg = MAPL_ConfigCreate(_RC)
        if (resolution(2)==resolution(1)*6) then
           call MAPL_MakeDecomposition(nx,ny,reduceFactor=6,_RC)
        else
           call MAPL_MakeDecomposition(nx,ny,_RC)
        end if
        call MAPL_ConfigSetAttribute(cfg,value=nx, label=trim(tlabel)//".NX:",_RC)
        call MAPL_ConfigSetAttribute(cfg,value=ny, label=trim(tlabel)//".NY:",_RC)
        if (resolution(2)==resolution(1)*6) then
          call MAPL_ConfigSetAttribute(cfg,value="Cubed-Sphere", label=trim(tlabel)//".GRID_TYPE:",_RC)
          call MAPL_ConfigSetAttribute(cfg,value=6, label=trim(tlabel)//".NF:",_RC)
          call MAPL_ConfigSetAttribute(cfg,value=im_world,label=trim(tlabel)//".IM_WORLD:",_RC)
        else
          call MAPL_ConfigSetAttribute(cfg,value="LatLon", label=trim(tlabel)//".GRID_TYPE:",_RC)
          call MAPL_ConfigSetAttribute(cfg,value=im_world,label=trim(tlabel)//".IM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cfg,value=jm_world,label=trim(tlabel)//".JM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cfg,value='PC', label=trim(tlabel)//".POLE:",_RC)
          call MAPL_ConfigSetAttribute(cfg,value='DC', label=trim(tlabel)//".DATELINE:",_RC)
        end if
        output_grid = grid_manager%make_grid(cfg,prefix=trim(tlabel)//'.',_RC)
        factory => grid_manager%get_factory(output_grid,_RC)
        this%output_grid_label = factory%generate_grid_name()
        lgrid => output_grids%at(trim(this%output_grid_label))
        if (.not.associated(lgrid)) call output_grids%insert(this%output_grid_label,output_grid)
     end subroutine AddGrid
Call graph
addgrid calls at, generate_grid_name, insert, mapl_configsetattribute, mapl_makedecomposition, make_grid, get_factory, mapl_configcreate, mapl_verify
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_makedecomposition calls mapl_makedecomposition, mapl_verify, mapl_return, ESMF_VMGet, ESMF_VMGetCurrent
get_factory calls get_factory, mapl_verify, mapl_return
mapl_configcreate calls ESMF_ConfigCreate
mapl_verify calls mapl_throw_exception
mapl_configsetattribute_int32 calls mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_ints32 calls mapl_configsetattribute, mapl_verify, mapl_return, mapl_assert
mapl_configsetattribute_real32 calls mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_real64 calls mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_reals32 calls mapl_configsetattribute, mapl_verify, mapl_return, mapl_assert
mapl_configsetattribute_string calls mapl_return, ESMF_ConfigGetAttribute
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at