addList – MAPL
addList Subroutine
96 statements
Source File
public subroutine addList(name, count, vName, attInt, attChar, attReal, iList, rList, cList)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(in) :: count
character(len=*), intent(in), optional :: vName
integer, intent(in), optional :: attInt(*)
character(len=MLEN), intent(in), optional :: attChar
real, intent(in), optional :: attReal(*)
type(iNode), optional, pointer :: iList
type(rNode), optional, pointer :: rList
type(cNode), optional, pointer :: cList
Called by
Contents
Source Code
addList
Source Code
        subroutine addList(name, count, vName, attInt, attChar, attReal, &
                           iList, rList, cList)
!
! !ARGUMENTS:
!
! !INPUT PARAMETERS:
!
           character(len=*), intent(in) :: name
           integer, intent(in) :: count
           character(len=*), intent(in), OPTIONAL :: vName
           integer, intent(in), OPTIONAL :: attInt(*)
           real, intent(in), OPTIONAL :: attReal(*)
           character(len=MLEN), intent(in), OPTIONAL :: attChar
!
! !OUTPUT PARAMETERS:
!
           type(iNode), pointer, OPTIONAL :: iList  ! int list
           type(rNode), pointer, OPTIONAL :: rList  ! real list
           type(cNode), pointer, OPTIONAL :: cList  ! char list
!
! !DESCRIPTION:
!     put user defined attribute into a list
!EOP
!------------------------------------------------------------------------------
           type(iNode), pointer :: p, q
           type(rNode), pointer :: rp, rq
           type(cNode), pointer :: cp, cq
           integer :: i
!          put int attribute into an integer list
           if ( present(attInt) .and. present(iList)) then
              if ( .not. associated(iList) ) then
                 allocate(iList)
                 iList%count = count
                 iList%name = name
                 if (present(vName)) iList%vName = vName
                 allocate(iList%intData(count))
                 do i =1, count
                    iList%intData(i) = attInt(i)
                 end do
                 iList%next => null()
              else
                 q => iList
                 p => iList%next
                 do while ( associated(p) )
                     q => p
                     p => p%next
                 end do
                 allocate(p)
                 p%count = count
                 p%name = name
                 if (present(vName)) p%vName = vName
                 allocate(p%intData(count))
                 do i =1, p%count
                    p%intData(i) = attInt(i)
                 end do
                 q%next => p
              end if
           end if
!          put real attribute into a real list
           if ( present(attReal) .and. present(rList)) then
              if ( .not. associated(rList) ) then
                 allocate(rList)
                 rList%count = count
                 rList%name = name
                 if (present(vName)) rList%vName = vName
                 allocate(rList%realData(count))
                 do i =1, count
                    rList%realData(i) = attReal(i)
                 end do
                 rList%next => null()
              else
                 rq => rList
                 rp => rList%next
                 do while ( associated(rp) )
                     rq => rp
                     rp => rp%next
                 end do
                 allocate(rp)
                 rp%count = count
                 rp%name = name
                 if (present(vName)) rp%vName = vName
                 allocate(rp%RealData(count))
                 do i =1, rp%count
                    rp%realData(i) = attReal(i)
                 end do
                 rq%next => rp
              end if
           end if
!          put char attribute into a char list
           if ( present(attChar) .and. present(cList)) then
              if ( .not. associated(cList) ) then
                 allocate(cList)
                 cList%count = count
                 cList%name = name
                 if (present(vName)) cList%vName = vName
                 cList%charData = attChar(1:count)
                 cList%next => null()
              else
                 cq => cList
                 cp => cList%next
                 do while ( associated(cp) )
                     cq => cp
                     cp => cp%next
                 end do
                 allocate(cp)
                 cp%count = count
                 cp%name = name
                 if (present(vName)) cp%vName = vName
                 cp%charData = attChar(1:count)
                 cq%next => cp
              end if
           end if
        end subroutine addList
Call graph
esmf_cfioset calls addlist
esmf_cfiovarinfoset calls addlist
test calls esmf_cfioset, esmf_cfiovarinfoset
mapl_cfioreadbundle calls esmf_cfioset
esmf_cfiofileopen calls esmf_cfioset
esmf_cfiofilecreate calls esmf_cfioset
esmf_cfiosdffilecreate calls esmf_cfioset
esmf_cfiosdfvarwrite2d_ calls esmf_cfioset
esmf_cfiosdfvarwrite1d_ calls esmf_cfioset
find calls esmf_cfioset
mapl_cfiocreatewrite calls esmf_cfioset
mapl_cfiocreatefrombundle calls esmf_cfioset, esmf_cfiovarinfoset
esmf_cfiosdfvarwrite3d_ calls esmf_cfioset