addNewSpec – MAPL
addNewSpec Subroutine
21 statements
Source File
private subroutine addNewSpec(this, gc, specType, rc)
Type Bound
VarspecDescription
Arguments
Type Intent Optional Attributes Name
class(VarspecDescription), intent(in) :: this
type(ESMF_GridComp), intent(inout) :: gc
character(len=*), intent(in) :: specType
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine addNewSpec(this,gc,specType,rc)
      class(VarspecDescription), intent(in) :: this
      type(ESMF_GridComp), intent(inout) :: gc
      character(*), intent(in) :: specType
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = "addNewSpec"
      if (specType == "IMPORT") then
         call MAPL_AddImportSpec(GC, &
              SHORT_NAME = this%short_name, &
              LONG_NAME = this%long_name, &
              UNITS = this%units, &
              DIMS = this%dims, &
              VLOCATION = this%location, &
              STAGGERING = this%staggering, &
              ROTATION = this%rotation, &
              RC = status)
      else if (specType == "EXPORT") then
         call MAPL_AddExportSpec(GC, &
              SHORT_NAME = this%short_name, &
              LONG_NAME = this%long_name, &
              UNITS = this%units, &
              DIMS = this%dims, &
              VLOCATION = this%location, &
              STAGGERING = this%staggering, &
              ROTATION = this%rotation, &
              RC = status)
      else
         _RETURN(_FAILURE)
      end if
      _VERIFY(status)
   end subroutine AddNewSpec
Call graph
addnewspec calls mapl_addexportspec, mapl_addimportspec
mapl_addexportspec calls mapl_stateaddexportspec_, mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_addimportspec calls mapl_stateaddimportspec_, mapl_stateaddimportspecfrmchld
mapl_stateaddexportspec_ calls ESMF_ConfigGetAttribute, mapl_assert, mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify
mapl_stateaddexportspecfrmall calls ESMF_GridCompGet, mapl_varspecaddreftolist, mapl_varspecget, mapl_varspecset, get_child_gridcomp, get_num_children, mapl_gridcompgetvarspecs, mapl_return, mapl_varspeccreateinlist, mapl_verify
mapl_stateaddexportspecfrmchld calls mapl_internalstateretrieve, mapl_return, mapl_stateaddexportspecfrmchldname, mapl_verify
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld, mapl_varspecget, get_child_gridcomp, mapl_gridcompgetvarspecs, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_stateaddimportspec_ calls ESMF_ConfigGetAttribute, mapl_assert, mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist, mapl_varspecgetindex, get_child_gridcomp, get_num_children, mapl_gridcompgetvarspecs, mapl_return, mapl_verify
addstate calls addnewspec
setservices calls addstate