AddState – MAPL
AddState Subroutine
45 statements
Source File
private subroutine AddState(gc, cf, stateType, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_Config), intent(inout) :: cf
character(len=*), intent(in) :: stateType
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine AddState(gc,cf,stateType,rc)
      type(ESMF_GridComp), intent(inout) :: gc
      type(ESMF_Config), intent(inout) :: cf
      character(len=*), intent(in) :: stateType
      integer, intent(out), optional :: rc
      integer :: status
      type(VarspecDescriptionVector) :: VarspecVec
      type(VarspecDescriptionVectorIterator) :: Iter
      type(VarspecDescription) :: VarspecDescr
      type(VarspecDescription), pointer :: VarspecPtr
      integer :: nrows,ncolumn,i
      if (trim(stateType) == 'IMPORT') then
         call ESMF_ConfigGetDim(cf,nrows,ncolumn,label="IMPORT_STATE::",rc=status)
         if (status==ESMF_SUCCESS) then
            call ESMF_ConfigFindLabel(cf,label="IMPORT_STATE::",_RC)
            do i=1,nrows
               call ESMF_ConfigNextLine(cf,_RC)
               VarspecDescr = VarspecDescription(CF,ncolumn,rc)
               call VarspecVec%push_back(VarspecDescr)
            enddo
         end if
      end if
      if (trim(stateType) == 'EXPORT') then
         call ESMF_ConfigGetDim(cf,nrows,ncolumn,label="EXPORT_STATE::",rc=status)
         if (status==ESMF_SUCCESS) then
         call ESMF_ConfigFindLabel(cf,label="EXPORT_STATE::",_RC)
            do i=1,nrows
               call ESMF_ConfigNextLine(cf,_RC)
               VarspecDescr = VarspecDescription(CF,ncolumn,rc)
               call VarspecVec%push_back(VarspecDescr)
            enddo
         endif
      end if
      iter = VarspecVec%begin()
      do while (iter /= VarspecVec%end())
         VarspecPtr => iter%get()
         call VarspecPtr%addNewSpec(gc,stateType,_RC)
         call iter%next()
      end do
   end subroutine AddState
Call graph
addstate calls ESMF_ConfigFindLabel, ESMF_ConfigGetDim, ESMF_ConfigNextLine, addnewspec, mapl_verify, v_begin, v_iter_get, v_iter_next, v_push_back
addnewspec calls mapl_addexportspec, mapl_addimportspec
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_addexportspec calls mapl_stateaddexportspec_, mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_addimportspec calls mapl_stateaddimportspec_, mapl_stateaddimportspecfrmchld
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
setservices calls addstate