addVariable_to_acc_bundle – MAPL
addVariable_to_acc_bundle Subroutine
26 statements
Source File
private subroutine addVariable_to_acc_bundle(this, itemName, rc)
Type Bound
sampler
Arguments
Type Intent Optional Attributes Name
class(sampler), intent(inout) :: this
character(len=*), intent(in) :: itemName
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine addVariable_to_acc_bundle(this,itemName,rc)
    class (sampler), intent(inout) :: this
    character(len=*), intent(in) :: itemName
    integer, optional, intent(out) :: rc
    type(ESMF_Field) :: field,newField
    type(ESMF_Array) :: array1
    real(KIND=ESMF_KIND_R4), pointer :: pt2d(:,:)
    class (AbstractGridFactory), pointer :: factory
    integer :: fieldRank
    logical :: isPresent
    integer :: status
    call ESMF_FieldBundleGet(this%input_bundle,itemName,field=field,_RC)
    call ESMF_FieldGet(field,rank=fieldRank,rc=status)
    if (this%doVertRegrid .and. (fieldRank ==3) ) then
       newField = MAPL_FieldCreate(field,this%output_grid,lm=this%vData%lm,_RC)
    else
       newField = MAPL_FieldCreate(field,this%output_grid,_RC)
    end if
    call MAPL_FieldBundleAdd(this%acc_bundle,newField,_RC)
    _RETURN(_SUCCESS)
  end subroutine addVariable_to_acc_bundle
Call graph
addvariable_to_acc_bundle calls esmf_fieldbundleget, esmf_fieldget, mapl_fieldbundleadd, mapl_fieldcreate, mapl_return, mapl_verify
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_fieldcreate calls mapl_fieldcreatenewgrid, mapl_fieldcreater4, mapl_fieldcreaterename
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield
mapl_fieldcreatenewgrid calls mapl_fieldcreatenewgrid
mapl_fieldcreater4 calls mapl_fieldcreater4
mapl_fieldcreaterename calls mapl_fieldcreaterename
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_bundle_rh calls addvariable_to_acc_bundle
initialize calls create_bundle_rh
run calls create_bundle_rh