adjust_dso_name – MAPL
adjust_dso_name Function
5 statements
Source File
public pure function adjust_dso_name(guess)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: guess
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   pure function adjust_dso_name(guess)
      character(:), allocatable :: adjust_dso_name
      character(*), intent(in) :: guess
      adjust_dso_name = get_file_basename(guess) // SYSTEM_DSO_EXTENSION
  end function adjust_dso_name
Call graph
adjust_dso_name calls get_file_basename
get_file_basename calls find_extension_index
addchildfromdsometa calls adjust_dso_name
mapl_addchild calls addchildfromdsometa, addchildfromdso, addchildfromdso_old
addchildfromdso calls addchildfromdsometa
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild
main calls run_component_driver