advanceClockToTime – MAPL
advanceClockToTime Subroutine
24 statements
Source File
private subroutine advanceClockToTime(this, time, rc)
Type Bound
ExtData_DriverGridComp
Arguments
Type Intent Optional Attributes Name
class(ExtData_DriverGridComp), intent(inout) :: this
type(ESMF_Time), intent(inout) :: time
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine advanceClockToTime(this, time,rc)
    class(ExtData_DriverGridComp), intent(inout) :: this
    type(ESMF_Time), intent(inout) :: time
    integer, intent(out), optional :: rc
    integer :: status
    type(ESMF_Time) :: currTime
    logical :: matched
    call ESMF_ClockGet(this%clock,currTime=currTime,rc=status)
    _VERIFY(status)
    if (time==currTime) then
       _RETURN(ESMF_SUCCESS)
    end if
    matched = .false.
    do while (.not. matched)
       call ESMF_ClockAdvance(this%clock,rc=status)
       _VERIFY(status)
       call ESMF_ClockGet(this%clock,currTime=currTime,rc=status)
       _VERIFY(status)
       if (currTime==Time) matched = .true.
    enddo
    _RETURN(ESMF_SUCCESS)
  end subroutine advanceClockToTime
Call graph
advanceclocktotime calls ESMF_ClockAdvance, ESMF_ClockGet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_multipletimes calls advanceclocktotime
run_gc calls run_multipletimes