AdvanceAndCount – MAPL
AdvanceAndCount Subroutine
27 statements
Source File
private subroutine AdvanceAndCount(cf, nLines, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: cf
integer, intent(out) :: nLines
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
AdvanceAndCount
Source Code
  subroutine AdvanceAndCount(CF,nLines,rc)
     type(ESMF_Config), intent(inout) :: cf
     integer, intent(out)             :: nLines
     integer, optional, intent(out)   :: rc
     integer :: iCnt
     logical :: inBlock
     character(len=ESMF_MAXPATHLEN) :: thisLine
     integer :: status
     character(len=ESMF_MAXSTR) :: Iam
     Iam = "AdvanceAndCount"
     inBlock = .true.
     iCnt = 0
     do while(inBlock)
         call ESMF_ConfigNextLine(CF,rc=status)
         _VERIFY(STATUS)
         call ESMF_ConfigGetAttribute(CF,thisLine,rc=status)
         _VERIFY(STATUS)
         if (trim(thisLine) == "%%") then
            inBlock = .false.
         else
            iCnt = iCnt + 1
         end if
     end do
     nLines = iCnt
     _RETURN(ESMF_SUCCESS)
  end subroutine advanceAndCount
Call graph
advanceandcount calls ESMF_ConfigGetAttribute, ESMF_ConfigNextLine, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
initialize_ calls advanceandcount