advertise_fields – MAPL
advertise_fields Subroutine
36 statements
Source File
private subroutine advertise_fields(model, import_state, export_state, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
type(ESMF_State) :: import_state
type(ESMF_State) :: export_state
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
    subroutine advertise_fields(model, import_state, export_state, clock, rc)
        type(ESMF_GridComp)  :: model
        type(ESMF_State)     :: import_state, export_state
        type(ESMF_Clock)     :: clock
        integer, intent(out) :: rc
        type(MAPL_Cap), pointer             :: cap
        type(Field_Attributes), allocatable :: export_attributes(:), import_attributes(:)
        _UNUSED_DUMMY(clock)
        cap => get_cap_from_gc(model, rc)
        VERIFY_NUOPC_(rc)
        export_attributes = get_field_attributes_from_state(cap%cap_gc%export_state)
        import_attributes = get_field_attributes_from_state(cap%cap_gc%import_state)
        call advertise_to_state(import_state, import_attributes)
        call advertise_to_state(export_state, export_attributes)
        _RETURN(_SUCCESS)
    contains
        subroutine advertise_to_state(state, fields)
            type(ESMF_State),       intent(inout) :: state
            type(field_attributes), intent(in   ) :: fields(:)
            integer :: i, status
            do i = 1, size(fields)
                associate(short_name => fields(i)%short_name, units => fields(i)%units)
                    if (.not. NUOPC_FieldDictionaryHasEntry(short_name)) then
                        call NUOPC_FieldDictionaryAddEntry(standardName=trim(short_name), &
                                canonicalUnits=trim(units), rc=status)
                        VERIFY_NUOPC_(status)
                    end if
                    call NUOPC_Advertise(state, StandardName=trim(short_name), &
                            TransferOfferGeomObject="will provide", rc=status)
                    VERIFY_NUOPC_(status)
                end associate
            end do
        end subroutine advertise_to_state
    end subroutine advertise_fields
Call graph
advertise_fields calls ESMF_LogFoundError, NUOPC_Advertise, NUOPC_FieldDictionaryAddEntry, NUOPC_FieldDictionaryHasEntry, get_cap_from_gc, get_field_attributes_from_state, mapl_return
get_cap_from_gc calls ESMF_LogFoundError, mapl_return, ESMF_UserCompGetInternalState
get_field_attributes_from_state calls ESMF_LogFoundError, ESMF_AttributeGet, ESMF_FieldValidate, esmf_fieldget, esmf_stateget
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize