advpos – MAPL
advpos Subroutine
44 statements
Source File
private subroutine advpos(this, pos, dir)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
integer(kind=SIZE_KIND), intent(inout) :: pos
integer, intent(in) :: dir
Calls
Called by
Call graph
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
erase_nonleaf calls advpos
s_next calls advpos
s_prev calls advpos
equalsets calls s_next, s_begin
m_next calls s_next
m_previous calls s_prev
s_begin calls s_next
s_deepcopy calls s_next, s_begin
s_erase_multi calls erase_nonleaf, s_next
s_erase_one calls s_next
check_flip calls m_next
equal calls m_next
get_level_name calls m_next
getlevs calls m_next
m_begin calls s_begin
m_deepcopy calls s_deepcopy
mapl_iochangeres calls m_next
mapl_iocountlevels calls m_next
mapl_iocountnondimvars calls m_next
mapl_iogetnondimvars calls m_next
modifymetadata calls m_next
stringvariablemap_serialize calls m_next
transfer_metadata calls m_next
write_const_variables calls m_next
write_coordinate_variables calls m_next
write_data calls m_next
write_variables calls m_next