advpos – MAPL
advpos Subroutine
44 statements
Source File
private subroutine advpos(this, pos, dir)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
integer(kind=SIZE_KIND), intent(inout) :: pos
integer, intent(in) :: dir
Calls
Called by
Call graph
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
erase_nonleaf calls advpos
s_next calls advpos
s_prev calls advpos
equalsets calls s_next, s_begin
m_next calls s_next
m_previous calls s_prev
s_begin calls s_next
s_deepcopy calls s_next, s_begin
s_erase_multi calls erase_nonleaf, s_next
s_erase_one calls s_next, erase
count_rules_for_item calls m_next, m_begin
get_item_type calls m_next, m_begin
get_time_range calls m_next, m_begin
has_rule_for calls m_next, m_begin
m_begin calls s_begin
m_deepcopy calls s_deepcopy
get_extra_derived_items calls has_rule_for
initialize_ calls count_rules_for_item, get_item_type, get_time_range
m_erase_one calls erase
s_remove calls erase