advpos – MAPL
advpos Subroutine
44 statements
Source File
private subroutine advpos(this, pos, dir)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
integer(kind=SIZE_KIND), intent(inout) :: pos
integer, intent(in) :: dir
Calls
Called by
Call graph
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
erase_nonleaf calls advpos
s_next calls advpos
s_prev calls advpos
equalsets calls s_next, s_begin
m_next calls s_next
m_previous calls s_prev
s_begin calls s_next
s_deepcopy calls s_next, s_begin
s_erase_multi calls erase_nonleaf, s_next
s_erase_one calls s_next, erase
equal calls m_next, m_begin
m_begin calls s_begin
m_deepcopy calls s_deepcopy
put_attributes calls m_next, m_begin
put_var_attributes calls m_next, m_begin
stringattributemap_serialize calls m_next, m_begin
transfer_metadata calls m_next, m_begin
def_variables calls put_var_attributes
m_erase_one calls erase
put_datatofile calls stringattributemap_serialize
s_remove calls erase
serialize calls stringattributemap_serialize
write calls put_attributes
main calls transfer_metadata