allocate – MAPL
allocate Subroutine
14 statements
Source File
private subroutine allocate(this, rc)
Type Bound
LocalMemReference
Arguments
Type Intent Optional Attributes Name
class(LocalMemReference), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine allocate(this, rc)
      class (LocalMemReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer(kind=INT64) :: n_words
      integer(kind=INT64) :: n
      integer :: status
      n = product(int(this%shape,INT64))
      n_words = n * word_size(this%type_kind)
      allocate(this%i_ptr(n_words), stat=status)
      _VERIFY(status)
#ifdef __NAG_COMPILER_BUILD
      if (n > 0) then
         this%base_address = c_loc(this%i_ptr)
      else
         this%base_address =  C_NULL_PTR
      endif
#else
      this%base_address = c_loc(this%i_ptr)
#endif
      _RETURN(_SUCCESS)
   end subroutine allocate
Call graph
allocate calls mapl_return, mapl_verify, word_size
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception