alloc_ – MAPL
alloc_ Subroutine
35 statements
Source File
public subroutine alloc_(A, TYPE, IM, JM, rc)
Arguments
Type Intent Optional Attributes Name
type(PTR), intent(inout) :: A
integer, intent(in) :: TYPE
integer, intent(in) :: IM
integer, intent(in), optional :: JM
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
alloc_
Source Code
  subroutine alloc_(A,type,im,jm,rc)
    type (Ptr),        intent(INOUT) :: A
    integer,           intent(IN)    :: TYPE
    integer,           intent(IN)    :: IM
    integer, optional, intent(IN)    :: JM
    integer, optional, intent(out)   :: rc
    integer :: status
    call dealloc_(A,RC=STATUS)
    _VERIFY(STATUS)
    select case (type)
    case (R4_2)
       _ASSERT(present(jm), 'jm not present for 2d')
       allocate(A%r4_2(IM,JM))
    case (R4_1)
       _ASSERT(.not.present(jm), 'jm is present for 1d')
       allocate(A%r4_1(IM))
    case (R8_2)
       _ASSERT(present(jm), 'jm not present for 2d')
       allocate(A%r8_2(IM,JM))
    case (R8_1)
       _ASSERT(.not.present(jm),'jm is present for 1d')
       allocate(A%r8_1(IM))
    case (i4_1)
       _ASSERT(.not.present(jm), 'jm present for 1d')
       allocate(A%I4_1(IM))
    case (i4_2)
       _ASSERT(present(jm), 'jm not present for 2d')
       allocate(A%I4_2(IM,JM))
    case default
       _FAIL( 'unsupported tkr')
    end select
    a%allocated=type
    _RETURN(ESMF_SUCCESS)
  end subroutine alloc_
Call graph
alloc_ calls mapl_assert, dealloc_, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
dealloc_ calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varwrite_i4_1d calls alloc_
mapl_varwrite_r4_1d calls alloc_
mapl_varwrite_r4_2d calls alloc_
mapl_varwrite_r8_1d calls alloc_
mapl_varwrite_r8_2d calls alloc_
write_parallel_i4_1 calls alloc_
write_parallel_r4_1 calls alloc_
write_parallel_r8_1 calls alloc_
mapl_varwrite calls mapl_varwrite_i4_1d, mapl_varwrite_r4_1d, mapl_varwrite_r4_2d, mapl_varwrite_r8_1d, mapl_varwrite_r8_2d
write_parallel calls write_parallel_i4_1, write_parallel_r4_1, write_parallel_r8_1