allocate – MAPL
allocate Subroutine
23 statements
Source File
private subroutine allocate(this, rc)
Type Bound
RDMAReference
Arguments
Type Intent Optional Attributes Name
class(RDMAReference), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine allocate(this, rc)
      class (RDMAReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer(kind=MPI_ADDRESS_KIND) :: windowsize
      integer :: disp_unit,status, Rank
      integer(kind=MPI_ADDRESS_KIND) :: n_bytes
      integer :: int_size
#if !defined (SUPPORT_FOR_MPI_ALLOC_MEM_CPTR)
      integer(kind=MPI_ADDRESS_KIND) :: baseaddr
#endif
      int_size   = c_sizeof(int_size)
      disp_unit  = int_size
      n_bytes    = this%msize_word * int_size
      call MPI_Comm_rank(this%comm,Rank,status)
      windowsize = 0_MPI_ADDRESS_KIND
      if (Rank == this%mem_rank) windowsize = n_bytes
#if defined (SUPPORT_FOR_MPI_ALLOC_MEM_CPTR)
      call MPI_Win_allocate(windowsize, disp_unit, MPI_INFO_NULL, this%comm, &
               this%base_address, this%win, status)
      _VERIFY(status)
#else
      call MPI_Win_allocate(windowsize, disp_unit, MPI_INFO_NULL, this%comm, &
               baseaddr, this%win, status)
      _VERIFY(status)
      this%base_address = transfer(baseaddr, this%base_address)
#endif
      call MPI_Win_fence(0, this%win, status)
      _VERIFY(status)
      this%RDMA_allocated = .true.
      _RETURN(_SUCCESS)
   end subroutine allocate
Call graph
allocate calls mpi_comm_rank, mpi_win_allocate, mpi_win_fence, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize