Am_I_Friendly__ – MAPL
Am_I_Friendly__ Subroutine
17 statements
Source File
private subroutine Am_I_Friendly__(BUNDLE, TO, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
character(len=*), intent(in) :: TO(:)
integer, intent(out) :: RC
Calls
Called by
Contents
Source Code
Am_I_Friendly__
Source Code
   subroutine Am_I_Friendly__ ( BUNDLE, TO, RC )
      type(ESMF_FieldBundle),  intent(INout)  :: BUNDLE
      character(len=*),  intent(IN)  :: TO(:)
      integer,           intent(OUT) :: RC
      logical            :: FRIENDLY, isPresent
      integer            :: I, status
      RC = ESMF_FAILURE
      do I = 1, size(TO)
         FRIENDLY = .false.
         call ESMF_AttributeGet (BUNDLE, NAME="FriendlyTo"//trim(TO(I)), &
              isPresent=isPresent, RC=status)
         if (isPresent) then
            call ESMF_AttributeGet (BUNDLE, NAME="FriendlyTo"//trim(TO(I)), &
                 VALUE=FRIENDLY, RC=status)
            if (FRIENDLY) RC = ESMF_SUCCESS
         endif
      end do
      return
   end subroutine Am_I_Friendly__
Call graph
am_i_friendly__ calls esmf_attributeget
mapl_gridcompgetfriendlies0 calls am_i_friendly__, mapl_gridcompgetfriendlies
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies3
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0