am_i_initialized – MAPL
am_i_initialized Function
5 statements
Source File
private function am_i_initialized(this) result(logical_temp)
Type Bound
timeData
Arguments
Type Intent Optional Attributes Name
class(timeData), intent(inout) :: this
Return Value logical
Called by
Call graph
bundlepost calls am_i_initialized
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main