am_i_running – MAPL
am_i_running Function
19 statements
Source File
private function am_i_running(yaml_file, rc) result(am_running)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: yaml_file
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Contents
Source Code
am_i_running
Source Code
  function am_i_running(yaml_file,rc) result(am_running)
     logical :: am_running
     character(len=*), intent(in) :: yaml_file
     integer, intent(out), optional :: rc
      type(Parser)              :: p
      class(YAML_Node), allocatable :: config
      integer :: status
      am_running=.true.
      p = Parser('core')
      config = p%load(yaml_file,rc=status)
      if (status/=_SUCCESS) then
          _FAIL("Error parsing: "//trim(yaml_file))
      end if
      if (config%has("USE_EXTDATA")) then
         am_running = config%of("USE_EXTDATA")
      end if
      _RETURN(_SUCCESS)
   end function am_i_running
Call graph
am_i_running calls parser, mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls get_error_message, mapl_throw_exception
initialize_ calls am_i_running