am_I_reading_PE – MAPL
am_I_reading_PE Function
8 statements
Source File
private function am_I_reading_PE(this, id) result(yes)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(in) :: this
integer, intent(in) :: id
Return Value logical
Calls
Called by
Source Code
   function am_I_reading_PE(this,id) result (yes)
      class(AbstractServer),intent(in) :: this
      integer, intent(in) :: id
      integer :: node_rank,innode_rank
      logical :: yes
      call this%distribute_task(id, node_rank,innode_rank)
      yes = (node_rank   == this%Node_Rank) .and. &
            (innode_rank == this%InNode_Rank)
   end function am_I_reading_PE
Call graph
am_i_reading_pe calls distribute_task
read_and_gather calls am_i_reading_pe
handle_done_collective_prefetch calls read_and_gather