append_file – MAPL
append_file Subroutine
192 statements
Source File
private subroutine append_file(this, current_time, rc)
if (mapl_am_i_root()) write(6,*) ‘item%xname=’, trim(item%xname)
Type Bound
StationSampler
Arguments
Type Intent Optional Attributes Name
class(StationSampler), intent(inout) :: this
type(ESMF_Time), intent(in) :: current_time
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine append_file(this,current_time,rc)
    class(StationSampler), intent(inout) :: this
    type(ESMF_Time), intent(in) :: current_time
    integer, optional, intent(out) :: rc
    !
    integer :: status
    integer :: fieldCount
    integer :: ub(1), lb(1)
    type(GriddedIOitemVectorIterator) :: iter
    type(GriddedIOitem), pointer :: item
    type(ESMF_Grid)  :: grid
    type(ESMF_Field) :: src_field  !  ,dst_field
    type(ESMF_Field) :: new_src_field,new_dst_field
    real(kind=REAL32), pointer :: p_src_3d(:,:,:),p_src_2d(:,:), qin_3d(:,:,:)   ! source
    real(kind=REAL32), pointer :: p_dst_3d(:,:)                    ! destination
    real(kind=REAL32), pointer :: p_ds_3d(:,:),p_ds_2d(:)          ! distributed LS
    real(kind=REAL32), pointer :: p_chunk_3d(:,:),p_chunk_2d(:)    ! chunk LS
    real(kind=REAL32), pointer :: p_rt_3d(:,:),p_rt_2d(:)          ! root LS
    real(kind=REAL32), pointer :: p_rt_3d_aux(:,:)
    real(kind=REAL32), allocatable :: p_new_lev(:,:,:)
    real(kind=REAL32), allocatable :: p_dst_t(:,:)
    real(kind=REAL32), allocatable :: arr(:,:)
    character(len=ESMF_MAXSTR), allocatable :: fieldNameList(:)
    character(len=ESMF_MAXSTR) :: xname
    real(kind=ESMF_KIND_R8), allocatable :: rtimes(:)
    integer :: rank
    integer :: i, j, k, nz, lm
    type(ESMF_VM) :: vm
    integer :: mypet, petcount, mpic, iroot
    integer :: n0, nx, nx2
    integer :: na, nb, nx_sum, nsend, nsend_v
    ! intermediate fields as placeholder
    type(ESMF_Field)               :: field_ds_2d
    type(ESMF_Field)               :: field_chunk_2d
    type(ESMF_Field)               :: field_chunk_3d
    integer :: sec
    integer, allocatable :: ix(:) !  counter for each obs(k)%nobs_epoch
    logical :: EX ! file
    logical :: zero_obs
    integer, allocatable :: recvcount(:), sendcount(:), displs(:)
    integer, allocatable :: recvcount_v(:), displs_v(:)
    integer :: is, ie, ierr
    integer :: M, N, ip
    this%obs_written=this%obs_written+1
    !__ 1. put_var: time variable
    !
    rtimes = this%compute_time_for_current(current_time,_RC) ! rtimes: seconds since opening file
    if (mapl_am_i_root()) then
       call this%formatter%put_var('time',rtimes(1:1),&
            start=[this%obs_written],count=[1],_RC)
    end if
    !__ 2. regrid + put_var:
    !      ungridded_dim from src to dst [regrid]
    !
    !      caution about zero-sized array for MPI
    !      redist
    !
    nx_sum = this%nstation
    lm = this%vdata%lm
    call ESMF_VMGetCurrent(vm,_RC)
    call ESMF_VMGet(vm, mpiCommunicator=mpic, petCount=petCount, localPet=mypet, _RC)
    iroot = 0
    ip = mypet
    N = nx_sum
    M = petCount
    nsend = int(ip+1, INT64) * int(N, INT64) / int(M, INT64) - &
         int(ip  , INT64) * int(N, INT64) / int(M, INT64)
    allocate ( recvcount (petCount) )
    allocate ( displs    (petCount) )
    do ip=0, M-1
       recvcount(ip+1) =  int(ip+1, INT64) * int(N, INT64) / int(M, INT64) - &
            int(ip  , INT64) * int(N, INT64) / int(M, INT64)
    end do
    displs(1)=0
    do i = 2, petCount
       displs(i) = displs(i-1) + recvcount(i-1)
    end do
    nsend_v = nsend * lm      ! vertical
    allocate (recvcount_v, source = recvcount * lm )
    allocate (displs_v, source = displs * lm )
    if (mapl_am_i_root()) then
       allocate ( p_rt_2d(nx_sum) )
    else
       allocate ( p_rt_2d(1) )
    end if
    ! p_rt_3d (lm, nx)
    if (mapl_am_i_root()) then
       allocate ( p_rt_3d(lm, nx_sum) )
       allocate ( p_rt_3d_aux(nx_sum, lm) )
    else
       allocate ( p_rt_3d(lm, 1) )
       allocate ( p_rt_3d_aux(1,lm) )
    end if
    !__  Aux. field
    !
    call MAPL_TimerOn(this%GENSTATE,"FieldCreate")
    call ESMF_FieldBundleGet(this%bundle,grid=grid,_RC)
    field_ds_2d    = ESMF_FieldCreate (this%LS_ds, name='field_2d_ds', typekind=ESMF_TYPEKIND_R4, _RC)
    field_chunk_2d = ESMF_FieldCreate (this%LS_chunk, name='field_2d_chunk', typekind=ESMF_TYPEKIND_R4, _RC)
    new_src_field  = ESMF_FieldCreate (grid, name='new_src_field', typekind=ESMF_TYPEKIND_R4, &
         gridToFieldMap=[2,3],ungriddedLBound=[1],ungriddedUBound=[lm],_RC)
    new_dst_field  = ESMF_FieldCreate (this%LS_ds, name='new_dst_field', typekind=ESMF_TYPEKIND_R4, &
         gridToFieldMap=[2],ungriddedLBound=[1],ungriddedUBound=[lm],_RC)
    field_chunk_3d = ESMF_FieldCreate (this%LS_chunk, name='field_3d_chunk', typekind=ESMF_TYPEKIND_R4, &
         gridToFieldMap=[2],ungriddedLBound=[1],ungriddedUBound=[lm],_RC)
    call ESMF_FieldGet(field_ds_2d,   localDE=0, farrayptr=p_ds_2d,    _RC)
    call ESMF_FieldGet(field_chunk_2d,localDE=0, farrayPtr=p_chunk_2d, _RC)
    call ESMF_FieldGet(new_src_field, localDE=0, farrayPtr=p_src_3d,   _RC)
    call ESMF_FieldGet(new_dst_field, localDE=0, farrayPtr=p_dst_3d,   _RC)
    call ESMF_FieldGet(field_chunk_3d,localDE=0, farrayPtr=p_chunk_3d, _RC)
    call MAPL_TimerOff(this%GENSTATE,"FieldCreate")
    iter = this%items%begin()
    do while (iter /= this%items%end())
       item => iter%get()
       if (item%itemType == ItemTypeScalar) then
          !! if (mapl_am_i_root()) write(6,*) 'item%xname=', trim(item%xname)
          call ESMF_FieldBundleGet(this%bundle,trim(item%xname),field=src_field,_RC)
          call ESMF_FieldGet(src_field,rank=rank,_RC)
          select case (rank)
          case(2)
             call ESMF_FieldGet(src_field,localDE=0,farrayptr=p_src_2d,_RC)
             call ESMF_FieldRegrid (src_field, field_ds_2d, this%regridder%route_handle, _RC)
             call ESMF_FieldRedist (field_ds_2d, field_chunk_2d, this%RH, _RC )
             call MPI_gatherv ( p_chunk_2d, nsend, MPI_REAL, &
                  p_rt_2d, recvcount, displs, MPI_REAL,&
                  iroot, mpic, ierr )
             call MAPL_TimerOn(this%GENSTATE,"put2D")
             if (mapl_am_i_root()) then
                call this%formatter%put_var(trim(item%xname),p_rt_2d,&
                     start=[1,this%obs_written],count=[this%nstation,1],_RC)
             end if
             call MAPL_TimerOff(this%GENSTATE,"put2D")
          case(3)
             ! -- CS-> LS_ds; ds->chunk; gather
             !
             call ESMF_FieldGet(src_field,localDE=0,farrayptr=qin_3d,_RC)
             call MAPL_TimerOn(this%GENSTATE,"reshape")
             p_src_3d = reshape(qin_3d,shape(p_src_3d),order=[2,3,1])
             call MAPL_TimerOff(this%GENSTATE,"reshape")
             call MAPL_TimerOn(this%GENSTATE,"3d_regrid")
             call ESMF_FieldRegrid (new_src_field, new_dst_field, this%regridder%route_handle, _RC)
             call MAPL_TimerOff(this%GENSTATE,"3d_regrid")
             call MPI_Barrier(mpic,ierr)
             _VERIFY (ierr)
             call MAPL_TimerOn(this%GENSTATE,"FieldRedist")
             call ESMF_FieldRedist (new_dst_field, field_chunk_3d, this%RH, _RC)
             call MPI_Barrier(mpic,ierr)
             _VERIFY (ierr)
             call MAPL_TimerOff(this%GENSTATE,"FieldRedist")
             call MAPL_TimerOn(this%GENSTATE,"gatherv")
             if (this%level_by_level) then
                ! p_chunk_3d (lm, nx)
                allocate (p_dst_t, source = reshape(p_chunk_3d, [size(p_chunk_3d,2),size(p_chunk_3d,1)], order=[2,1]))
                do k = 1, lm
                   call MPI_gatherv ( p_dst_t(1,k), nsend, MPI_REAL, &
                        p_rt_3d_aux(1,k), recvcount, displs, MPI_REAL,&
                        iroot, mpic, ierr )
                   _VERIFY (ierr)
                end do
                deallocate(p_dst_t)
                p_rt_3d = reshape(p_rt_3d_aux, shape(p_rt_3d), order=[2,1])
             else
                call MPI_gatherv ( p_chunk_3d, nsend_v, MPI_REAL, &
                     p_rt_3d, recvcount_v, displs_v, MPI_REAL,&
                     iroot, mpic, ierr )
             end if
             call MAPL_TimerOff(this%GENSTATE,"gatherv")
             call MAPL_TimerOn(this%GENSTATE,"put3D")
             if (mapl_am_i_root()) then
                nz=size(p_rt_3d,1); nx=size(p_rt_3d,2)
                call this%formatter%put_var(trim(item%xname),p_rt_3d,&
                     start=[1,1,this%obs_written],count=[nz,nx,1],_RC)
                !note:     lev,station,time
             end if
             call MAPL_TimerOff(this%GENSTATE,"put3D")
          case default
             _FAIL('grid2LS regridder: rank > 3 not implemented')
          end select
       else
          _FAIL ('ItemType vector not supported')
       endif
       call iter%next()
    end do
    call MAPL_TimerOn(this%GENSTATE,"FieldDestroy")
    call ESMF_FieldDestroy(field_ds_2d,    noGarbage=.true., _RC)
    call ESMF_FieldDestroy(field_chunk_2d, noGarbage=.true., _RC)
    call ESMF_FieldDestroy(field_chunk_3d, noGarbage=.true., _RC)
    call ESMF_FieldDestroy(new_dst_field,  noGarbage=.true., _RC)
    call ESMF_FieldDestroy(new_src_field,  noGarbage=.true., _RC)
    call MAPL_TimerOff(this%GENSTATE,"FieldDestroy")
    _RETURN(_SUCCESS)
  end subroutine append_file
Call graph
append_file calls ESMF_FieldRedist, ESMF_FieldRegrid, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_am_i_root, mapl_assert, mapl_timeroff, mapl_timeron, mpi_barrier, mpi_gatherv, put_var, compute_time_for_current, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next
run calls append_file