append – MAPL
append Subroutine
32 statements
Source File
private subroutine append(CONN, SHORT_NAME, TO_NAME, FROM_EXPORT, TO_IMPORT, RC)
Type Bound
VarConn
Arguments
Type Intent Optional Attributes Name
class(VarConn), intent(inout) :: CONN
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: TO_NAME
integer, intent(in), optional :: FROM_EXPORT
integer, intent(in), optional :: TO_IMPORT
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine append(CONN, SHORT_NAME, TO_NAME, &
        FROM_EXPORT, TO_IMPORT, RC  )
      class (VarConn ), intent(inout) :: CONN
      character (len=*)             , intent(IN   ) :: SHORT_NAME
      character (len=*),    optional, intent(IN   ) :: TO_NAME
      integer,              optional, intent(IN   ) :: FROM_EXPORT
      integer,              optional, intent(IN   ) :: TO_IMPORT
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      integer                    :: usableFROM_EXPORT
      integer                    :: usableTO_IMPORT
      type(VarConnType), pointer :: new_conn
      character(len=ESMF_MAXSTR) :: usableTONAME
      usableFROM_EXPORT=MAPL_ConnUnknown
      usableTO_IMPORT=MAPL_ConnUnknown
      if(present(TO_NAME)) then
         usableTONAME = TO_NAME
      else
         usableTONAME = SHORT_NAME
      endif
      if(present(FROM_EXPORT)) then
         usableFROM_EXPORT=FROM_EXPORT
      end if
      if(present(TO_IMPORT)) then
         usableTO_IMPORT=TO_IMPORT
      end if
      ! Push and then construct.
      call conn%conn_v%resize(conn%conn_v%size()+1)
      new_conn => CONN%conn_v%back()
      new_conn%From = VarConnPoint(SHORT_NAME, gc_id=usableFROM_EXPORT)
      new_conn%To   = VarConnPoint(usableTONAME, gc_id=usableTO_IMPORT)
      if(short_name == "MAPL_AnyChildImport") new_conn%used = .true.
      _RETURN(ESMF_SUCCESS)
   end subroutine append
Call graph
append calls resize, mapl_return, vector_back
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
vector_resize_size_kind calls reserve
mapl_addconnectivitye2e calls append
mapl_addconnectivityrename calls append
mapl_donotconnect calls append
mapl_addconnectivity calls mapl_addconnectivityrename, mapl_addconnectivitymany, mapl_addconnectivityrenamemany
mapl_terminateimport calls mapl_donotconnect, mapl_donotconnectanyimport, mapl_donotconnectmany, mapl_terminateimportallbut, mapl_terminateimportall
mapl_addconnectivitymany calls mapl_addconnectivityrename
mapl_donotconnectanyimport calls mapl_donotconnect
mapl_donotconnectmany calls mapl_donotconnect
mapl_stateaddexportspecfrmchldname calls mapl_addconnectivitye2e
mapl_terminateimportallbut calls mapl_donotconnect
mapl_addconnectivityrenamemany calls mapl_addconnectivity
mapl_stateaddexportspecfrmchld calls mapl_stateaddexportspecfrmchldname
mapl_terminateimportall calls mapl_terminateimport
mapl_addexportspec calls mapl_stateaddexportspecfrmchld
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld