append_file – MAPL
append_file Subroutine
85 statements
Source File
private subroutine append_file(this, current_time, rc)
Type Bound
StationSampler
Arguments
Type Intent Optional Attributes Name
class(StationSampler), intent(inout) :: this
type(ESMF_Time), intent(in) :: current_time
integer, intent(out), optional :: rc
Calls
Contents
Source Code
append_file
Source Code
  subroutine append_file(this,current_time,rc)
    class(StationSampler), intent(inout) :: this
    type(ESMF_Time), intent(in) :: current_time
    integer, optional, intent(out) :: rc
    !
    integer :: status
    integer :: fieldCount
    integer :: ub(1), lb(1)
    type(ESMF_Field) :: src_field,dst_field
    real(kind=REAL32), pointer :: p_src_3d(:,:,:),p_src_2d(:,:)
    real(kind=REAL32), pointer :: p_dst_3d(:,:),p_dst_2d(:)
    real(kind=REAL32), allocatable :: arr(:,:)
    character(len=ESMF_MAXSTR), allocatable ::  fieldNameList(:)
    character(len=ESMF_MAXSTR) :: xname
    real(kind=ESMF_KIND_R8), allocatable :: rtimes(:)
    integer :: i, rank
    integer :: nx, nz
    this%obs_written=this%obs_written+1
    !__ 1. put_var: time variable
    !
    rtimes = this%compute_time_for_current(current_time,_RC) ! rtimes: seconds since opening file
    if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
       call this%vdata%setup_eta_to_pressure(_RC)
    end if
    if (mapl_am_i_root()) then
       call this%formatter%put_var('time',rtimes(1:1),&
            start=[this%obs_written],count=[1],_RC)
    end if
    !__ 2. put_var: ungridded_dim from src to dst [regrid]
    !
    call ESMF_FieldBundleGet(this%bundle, fieldCount=fieldCount, _RC)
    allocate (fieldNameList(fieldCount))
    call ESMF_FieldBundleGet(this%bundle, fieldNameList=fieldNameList, _RC)
    do i=1, fieldCount
       xname=trim(fieldNameList(i))
       call ESMF_FieldBundleGet(this%bundle,xname,field=src_field,_RC)
       call ESMF_FieldGet(src_field,rank=rank,_RC)
       if (rank==2) then
          call ESMF_FieldGet(src_field,farrayptr=p_src_2d,_RC)
          dst_field = ESMF_FieldCreate(this%esmf_ls,name=xname, &
               typekind=ESMF_TYPEKIND_R4,_RC)
          call ESMF_FieldGet(dst_field,farrayptr=p_dst_2d,_RC)
          call this%regridder%regrid(p_src_2d,p_dst_2d,_RC)
          if (mapl_am_i_root()) then
             call this%formatter%put_var(xname,p_dst_2d,&
                  start=[1,this%obs_written],count=[this%nstation,1],_RC)
          end if
          call ESMF_FieldDestroy(dst_field,nogarbage=.true.)
       else if (rank==3) then
          call ESMF_FieldGet(src_field,farrayptr=p_src_3d,_RC)
          call ESMF_FieldGet(src_field,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
          if (this%vdata%lm/=(ub(1)-lb(1)+1)) then
             lb(1)=1
             ub(1)=this%vdata%lm
          end if
          dst_field = ESMF_FieldCreate(this%esmf_ls,name=xname,&
               typekind=ESMF_TYPEKIND_R4,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
          call ESMF_FieldGet(dst_field,farrayptr=p_dst_3d,_RC)
          call this%regridder%regrid(p_src_3d,p_dst_3d,_RC)
          if (mapl_am_i_root()) then
             nx=size(p_dst_3d,1); nz=size(p_dst_3d,2); allocate(arr(nz, nx))
             arr=reshape(p_dst_3d,[nz,nx],order=[2,1])
             call this%formatter%put_var(xname,arr,&
                  start=[1,1,this%obs_written],count=[nz,nx,1],_RC)
             !note:     lev,station,time
             deallocate(arr)
          end if
          call ESMF_FieldDestroy(dst_field,nogarbage=.true.)
       else
          _FAIL('grid2LS regridder: rank > 3 not implemented')
       end if
    end do
    deallocate (fieldNameList)
    _RETURN(_SUCCESS)
  end subroutine append_file
Call graph
append_file calls esmf_fieldbundleget, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_am_i_root, mapl_assert, compute_time_for_current, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
compute_time_for_current calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeIntervalGet, get_file_start_time
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
get_file_start_time calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeSet, get_attribute, get_value
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm