append – MAPL
append Subroutine
14 statements
Source File
private subroutine append(this, directory, unusable, rc)
Type Bound
DirPath
Arguments
Type Intent Optional Attributes Name
class(DirPath), intent(inout) :: this
character(len=*), intent(in) :: directory
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine append(this, directory, unusable, rc)
      class (DirPath), intent(inout) :: this
      character(len=*), intent(in) :: directory
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      call this%push_back(directory)
      if (present(rc)) then
         rc = MAPL_SUCCESS
      end if
   end subroutine append
Call graph
append calls push_back
initialize_gc calls append
test_complex calls append
test_simple calls append