append_variable_metadata – MAPL
append_variable_metadata Subroutine
10 statements
Source File
private subroutine append_variable_metadata(this, var)
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
type(Variable), intent(inout) :: var
Calls
Source Code
   subroutine append_variable_metadata(this,var)
      class (CubedSphereGridFactory), intent(inout) :: this
      type(Variable), intent(inout) :: var
      _UNUSED_DUMMY(this)
      call var%add_attribute('coordinates','lons lats')
      call var%add_attribute('grid_mapping','cubed_sphere')
   end subroutine append_variable_metadata
Call graph
append_variable_metadata calls add_attribute
add_attribute_1d calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception