append_metadata – MAPL
append_metadata Subroutine
22 statements
Source File
private subroutine append_metadata(this, metadata)
Uses
MAPL_Constants
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(inout) :: this
type(FileMetadata), intent(inout) :: metadata
Calls
Contents
Source Code
append_metadata
Source Code
   subroutine append_metadata(this, metadata)
      use MAPL_Constants
      class (LatLonGridFactory), intent(inout) :: this
      type (FileMetadata), intent(inout) :: metadata
      type (Variable) :: v
      real(kind=REAL64), allocatable :: temp_coords(:)
      ! Horizontal grid dimensions
      call metadata%add_dimension('lon', this%im_world)
      call metadata%add_dimension('lat', this%jm_world)
      ! Coordinate variables
      v = Variable(type=PFIO_REAL64, dimensions='lon')
      call v%add_attribute('long_name', 'longitude')
      call v%add_attribute('units', 'degrees_east')
      temp_coords = this%get_longitudes_degrees()
      call v%add_const_value(UnlimitedEntity(temp_coords))
      call metadata%add_variable('lon', v)
      deallocate(temp_coords)
      v = Variable(type=PFIO_REAL64, dimensions='lat')
      call v%add_attribute('long_name', 'latitude')
      call v%add_attribute('units', 'degrees_north')
      temp_coords=this%get_latitudes_degrees()
      call v%add_const_value(UnlimitedEntity(temp_coords))
      call metadata%add_variable('lat', v)
   end subroutine append_metadata
Call graph
append_metadata calls add_attribute, add_const_value, add_dimension, add_variable, get_latitudes_degrees, get_longitudes_degrees
get_latitudes_degrees calls mapl_return
get_longitudes_degrees calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize