append_metadata – MAPL
append_metadata Subroutine
82 statements
Source File
private subroutine append_metadata(this, metadata)
! At present pfio does not seem to work with string variables ! allocate(cvar(4,6)) ! cvar =reshape([” Y:-X”, ” X:-Y”, ” Y:Y “, ” X:X “, & ! ” Y:Y “, ” X:X “, ” Y:-X”, ” X:-Y”, & ! ” Y:-X”, ” X:-Y”, ” Y:Y “, ” X:X “, & ! ” Y:Y “, ” X:X “, ” Y:-X”, ” X:-Y”, & ! ” Y:-X”, ” X:-Y”, ” Y:Y “, ” X:X “, & ! ” Y:Y “, ” X:X “, ” Y:-X”, ” X:-Y” ], [ncontact,nf]) ! v = Variable(type=PFIO_STRING, dimensions=’orientationStrLen,ncontact,nf’) ! call v%add_attribute(‘long_name’, ‘orientation of boundary’) ! call v%add_const_value(UnlimitedEntity(cvar)) ! call metadata%add_variable(‘orientation’, v)
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
type(FileMetadata), intent(inout) :: metadata
$ class (KeywordEnforcer), optional, intent(in) :: unusable $ integer, optional, intent(out) :: rc
Calls
Source Code
   subroutine append_metadata(this, metadata)!, unusable, rc)
      class (CubedSphereGridFactory), intent(inout) :: this
      type (FileMetadata), intent(inout) :: metadata
!!$      class (KeywordEnforcer), optional, intent(in) :: unusable
!!$      integer, optional, intent(out) :: rc
      integer :: im
      type (Variable) :: v
      integer, parameter :: MAXLEN=80
      character(len=MAXLEN) :: gridspec_file_name
      !!! character(len=5), allocatable :: cvar(:,:)
      integer, allocatable :: ivar(:,:)
      integer, allocatable :: ivar2(:,:,:)
      real(REAL64), allocatable :: temp_coords(:)
      integer :: status
      integer, parameter :: ncontact = 4
      integer, parameter :: nf = 6
      ! Grid dimensions
      call metadata%add_dimension('Xdim', this%im_world, rc=status)
      call metadata%add_dimension('Ydim', this%im_world, rc=status)
      call metadata%add_dimension('XCdim', this%im_world+1, rc=status)
      call metadata%add_dimension('YCdim', this%im_world+1, rc=status)
      call metadata%add_dimension('nf', nf, rc=status)
      call metadata%add_dimension('ncontact', ncontact, rc=status)
      call metadata%add_dimension('orientationStrLen', 5, rc=status)
      ! Coordinate variables
      v = Variable(type=PFIO_REAL64, dimensions='Xdim')
      call v%add_attribute('long_name', 'Fake Longitude for GrADS Compatibility')
      call v%add_attribute('units', 'degrees_east')
      temp_coords = this%get_fake_longitudes()
      call metadata%add_variable('Xdim', CoordinateVariable(v, temp_coords))
      deallocate(temp_coords)
      v = Variable(type=PFIO_REAL64, dimensions='Ydim')
      call v%add_attribute('long_name', 'Fake Latitude for GrADS Compatibility')
      call v%add_attribute('units', 'degrees_north')
      temp_coords = this%get_fake_latitudes()
      call metadata%add_variable('Ydim', CoordinateVariable(v, temp_coords))
      deallocate(temp_coords)
      v = Variable(type=PFIO_INT32, dimensions='nf')
      call v%add_attribute('long_name','cubed-sphere face')
      call v%add_attribute('axis','e')
      call v%add_attribute('grads_dim','e')
      call v%add_const_value(UnlimitedEntity([1,2,3,4,5,6]))
      call metadata%add_variable('nf',v)
      v = Variable(type=PFIO_INT32, dimensions='ncontact')
      call v%add_attribute('long_name','number of contact points')
      call v%add_const_value(UnlimitedEntity([1,2,3,4]))
      call metadata%add_variable('ncontact',v)
      ! Other variables
      allocate(ivar(4,6))
      ivar = reshape( [5, 3, 2, 6, &
                       1, 3, 4, 6, &
                       1, 5, 4, 2, &
                       3, 5, 6, 2, &
                       3, 1, 6, 4, &
                       5, 1, 2, 4 ], [ncontact,nf])
      v = Variable(type=PFIO_INT32, dimensions='ncontact,nf')
      call v%add_attribute('long_name', 'adjacent face starting from left side going clockwise')
      call v%add_const_value(UnlimitedEntity(ivar))
      call metadata%add_variable('contacts', v)
      !!! At present pfio does not seem to work with string variables
      !!! allocate(cvar(4,6))
      !!! cvar =reshape([" Y:-X", " X:-Y", " Y:Y ", " X:X ", &
      !!!                " Y:Y ", " X:X ", " Y:-X", " X:-Y", &
      !!!                " Y:-X", " X:-Y", " Y:Y ", " X:X ", &
      !!!                " Y:Y ", " X:X ", " Y:-X", " X:-Y", &
      !!!                " Y:-X", " X:-Y", " Y:Y ", " X:X ", &
      !!!                " Y:Y ", " X:X ", " Y:-X", " X:-Y" ], [ncontact,nf])
      !!! v = Variable(type=PFIO_STRING, dimensions='orientationStrLen,ncontact,nf')
      !!! call v%add_attribute('long_name', 'orientation of boundary')
      !!! call v%add_const_value(UnlimitedEntity(cvar))
      !!! call metadata%add_variable('orientation', v)
      im = this%im_world
      allocate(ivar2(4,4,6))
      ivar2 = reshape(            &
               [[im, im,  1, im,  &
                  1, im,  1,  1,  &
                  1, im,  1,  1,  &
                 im, im,  1, im], &
                [im,  1, im, im,  &
                  1,  1, im,  1,  &
                  1,  1, im,  1,  &
                 im,  1, im, im], &
                [im, im,  1, im,  &
                  1, im,  1,  1,  &
                  1, im,  1,  1,  &
                 im, im,  1, im], &
                [im,  1, im, im,  &
                  1,  1, im,  1,  &
                  1,  1, im,  1,  &
                 im,  1, im, im], &
                [im, im,  1, im,  &
                  1, im,  1,  1,  &
                  1, im,  1,  1,  &
                 im, im,  1, im], &
                [im,  1, im, im,  &
                  1,  1, im,  1,  &
                  1,  1, im,  1,  &
                 im,  1, im, im] ], [ncontact,ncontact,nf])
      v = Variable(type=PFIO_INT32, dimensions='ncontact,ncontact,nf')
      call v%add_attribute('long_name', 'anchor point')
      call v%add_const_value(UnlimitedEntity(ivar2))
      call metadata%add_variable('anchor', v)
      call Metadata%add_attribute('grid_mapping_name', 'gnomonic cubed-sphere')
      call Metadata%add_attribute('file_format_version', '2.92')
      call Metadata%add_attribute('additional_vars', 'contacts,orientation,anchor')
      write(gridspec_file_name,'("C",i0,"_gridspec.nc4")') this%im_world
      call Metadata%add_attribute('gridspec_file', trim(gridspec_file_name))
      v = Variable(type=PFIO_REAL64, dimensions='Xdim,Ydim,nf')
      call v%add_attribute('long_name','longitude')
      call v%add_attribute('units','degrees_east')
      call metadata%add_variable('lons',v)
      v = Variable(type=PFIO_REAL64, dimensions='Xdim,Ydim,nf')
      call v%add_attribute('long_name','latitude')
      call v%add_attribute('units','degrees_north')
      call metadata%add_variable('lats',v)
      v = Variable(type=PFIO_REAL64, dimensions='XCdim,YCdim,nf')
      call v%add_attribute('long_name','longitude')
      call v%add_attribute('units','degrees_east')
      call metadata%add_variable('corner_lons',v)
      v = Variable(type=PFIO_REAL64, dimensions='XCdim,YCdim,nf')
      call v%add_attribute('long_name','latitude')
      call v%add_attribute('units','degrees_north')
      call metadata%add_variable('corner_lats',v)
      if (this%stretched_cube) then
         call metadata%add_attribute('STRETCH_FACTOR',this%stretch_factor)
         call metadata%add_attribute('TARGET_LON',this%target_lon_degrees)
         call metadata%add_attribute('TARGET_LAT',this%target_lat_degrees)
      end if
   end subroutine append_metadata
Call graph
append_metadata calls add_attribute, add_const_value, add_dimension, add_variable, get_fake_latitudes, get_fake_longitudes
add_const_value calls mapl_assert, get_rank, mapl_return
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
get_fake_latitudes calls ESMF_GridGetCoord, ESMF_VMGet, ESMF_VMGetCurrent, mapl_grid_interior, mpi_allgather, mpi_allgatherv, make_grid, mapl_verify
get_fake_longitudes calls ESMF_GridGetCoord, ESMF_VMGet, ESMF_VMGetCurrent, mapl_grid_interior, mpi_allgather, mpi_allgatherv, make_grid, mapl_verify