append_metadata – MAPL
append_metadata Subroutine
22 statements
Source File
private subroutine append_metadata(this, metadata)
Uses
MAPL_Constants
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(inout) :: this
type(FileMetadata), intent(inout) :: metadata
Calls
Source Code
   subroutine append_metadata(this, metadata)
      use MAPL_Constants
      class (LatLonGridFactory), intent(inout) :: this
      type (FileMetadata), intent(inout) :: metadata
      type (Variable) :: v
      real(kind=REAL64), allocatable :: temp_coords(:)
      ! Horizontal grid dimensions
      call metadata%add_dimension('lon', this%im_world)
      call metadata%add_dimension('lat', this%jm_world)
      ! Coordinate variables
      v = Variable(type=PFIO_REAL64, dimensions='lon')
      call v%add_attribute('long_name', 'longitude')
      call v%add_attribute('units', 'degrees_east')
      temp_coords = this%get_longitudes_degrees()
      call v%add_const_value(UnlimitedEntity(temp_coords))
      call metadata%add_variable('lon', v)
      deallocate(temp_coords)
      v = Variable(type=PFIO_REAL64, dimensions='lat')
      call v%add_attribute('long_name', 'latitude')
      call v%add_attribute('units', 'degrees_north')
      temp_coords=this%get_latitudes_degrees()
      call v%add_const_value(UnlimitedEntity(temp_coords))
      call metadata%add_variable('lat', v)
   end subroutine append_metadata
Call graph
append_metadata calls add_attribute, add_const_value, add_dimension, add_variable, get_latitudes_degrees, get_longitudes_degrees
add_const_value calls mapl_assert, get_rank, mapl_return
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
get_latitudes_degrees calls mapl_return
get_longitudes_degrees calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
get_rank calls get_shape, mapl_return
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize