are_same_type_kind – MAPL
are_same_type_kind Function
15 statements
Source File
private function are_same_type_kind(x, y, rc) result(same_tk)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Contents
Source Code
are_same_type_kind
Source Code
   logical function are_same_type_kind(x, y, rc) result(same_tk)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_TypeKind_Flag) :: tk_x, tk_y
      same_tk = .false.
      call ESMF_FieldGet(x, typekind=tk_x, _RC)
      call ESMF_FieldGet(y, typekind=tk_y, _RC)
      same_tk = (tk_x == tk_y)
      _RETURN(_SUCCESS)
   end function are_same_type_kind
Call graph
are_same_type_kind calls esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
fieldsaresametypekind calls are_same_type_kind
test_fieldsaresametypekind calls fieldsaresametypekind