are_conformable_array – MAPL
are_conformable_array Function
18 statements
Source File
private function are_conformable_array(x, y, rc) result(conformable)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y(:)
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function are_conformable_array(x, y, rc) result(conformable)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y(:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: j
      logical :: element_not_conformable
      conformable = .false.
      element_not_conformable = .false.
      do j = 1, size(y)
         element_not_conformable = .not. FieldsAreConformable(x, y(j), _RC)
         if(element_not_conformable) return
      end do
      conformable = .true.
      _RETURN(_SUCCESS)
   end function are_conformable_array
Call graph
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_scalar calls mapl_return, mapl_verify, esmf_fieldget, fieldgetlocalelementcount
get_error_message calls at, insert
mapl_throw_exception calls initialize
fieldgetlocalelementcount calls get_local_element_count
are_broadcast_conformable calls fieldsareconformable
axpy_r4 calls fieldsareconformable
axpy_r8 calls fieldsareconformable
copy_broadcast calls fieldsareconformable
copy calls fieldsareconformable
fieldabs calls fieldsareconformable
fieldacos calls fieldsareconformable
fieldadd calls fieldsareconformable
fieldasin calls fieldsareconformable
fieldatan calls fieldsareconformable
fieldcos calls fieldsareconformable
fieldcosh calls fieldsareconformable
fielddivide calls fieldsareconformable
fieldexp calls fieldsareconformable
fieldlog calls fieldsareconformable
fieldlog10 calls fieldsareconformable
fieldmultiply calls fieldsareconformable
fieldpow calls fieldsareconformable
fieldpower calls fieldsareconformable
fieldsin calls fieldsareconformable
fieldsinh calls fieldsareconformable
fieldsqrt calls fieldsareconformable
fieldsubtract calls fieldsareconformable
fieldtan calls fieldsareconformable
fieldtanh calls fieldsareconformable
gemv_r4 calls fieldsareconformable
gemv_r8 calls fieldsareconformable
test_fieldsareconformabler4 calls fieldsareconformable
test_fieldsareconformabler8 calls fieldsareconformable