are_almost_equal – MAPL
are_almost_equal Function
11 statements
Source File
public elemental function are_almost_equal(x, y) result(almost_equal)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: x
real(kind=ESMF_KIND_R4), intent(in) :: y
Return Value logical
Called by
Contents
Source Code
are_almost_equal
Source Code
   elemental function are_almost_equal(x, y) result(almost_equal)
      real(kind=ESMF_KIND_R4), parameter :: EPS = epsilon(real(1.0, kind=ESMF_KIND_R4))
      real(kind=ESMF_KIND_R8), intent(in) :: x
      real(kind=ESMF_KIND_R4), intent(in) :: y
      logical :: almost_equal
      if(y==0) then
         almost_equal = (x==0)
      else
         almost_equal = (abs(x-y)/abs(y) < EPS)
      end if
   end function are_almost_equal
Call graph
test_almost_equal_array calls are_almost_equal
test_almost_equal_scalar calls are_almost_equal
test_fieldcopy_r8r4 calls are_almost_equal