are_broadcast_conformable – MAPL
are_broadcast_conformable Function
30 statements
Source File
private function are_broadcast_conformable(x, y, rc) result(conformable)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function are_broadcast_conformable(x, y, rc) result(conformable)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y
      integer, optional, intent(out) :: rc
      integer :: rank_x, rank_y
      integer, dimension(:), allocatable :: count_x, count_y
      integer :: status
      logical :: normal_conformable
      conformable = .false.
      ! this should really used the geom and ungridded dims
      ! for now we will do this until we have a geom agnostic stuff worked out...
      ! the ideal algorithm would be if geom == geom and input does not have ungridded
      ! and thing we are copying to does, then we are "conformable"
      normal_conformable = FIeldsAreConformable(x,y,_RC)
      if (normal_conformable) then
         conformable = .true.
         _RETURN(_SUCCESS)
      end if
      call ESMF_FieldGet(x, rank=rank_x, _RC)
      call ESMF_FieldGet(y, rank=rank_y, _RC)
      if( (rank_x+1) == rank_y) then
         count_x = FieldGetLocalElementCount(x, _RC)
         count_y = FieldGetLocalElementCount(y, _RC)
         conformable = all(count_x == count_y(:rank_y-1))
      end if
      _RETURN(_SUCCESS)
   end function are_broadcast_conformable
Call graph
are_broadcast_conformable calls esmf_fieldget, fieldgetlocalelementcount, fieldsareconformable, mapl_return, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, fieldgetlocalelementcount, mapl_return, mapl_verify
get_error_message calls at, insert
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_throw_exception calls initialize
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_return, mapl_verify, mapl_assert
fieldsarebroadcastconformable calls are_broadcast_conformable
copy_broadcast calls fieldsarebroadcastconformable
mapl_stateeval calls fieldsarebroadcastconformable
fieldcopybroadcast calls copy_broadcast
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
evalf calls fieldcopybroadcast
initialize_ calls fillstate
run_ calls calcderivedfield, evaluate_derived_field, fillstate
run calls mapl_runexpression