are_conformable_scalar – MAPL
are_conformable_scalar Function
22 statements
Source File
private function are_conformable_scalar(x, y, rc) result(conformable)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function are_conformable_scalar(x, y, rc) result(conformable)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y
      integer, optional, intent(out) :: rc
      integer :: rank_x, rank_y
      integer, dimension(:), allocatable :: count_x, count_y
      integer :: status
      conformable = .false.
      call ESMF_FieldGet(x, rank=rank_x, _RC)
      call ESMF_FieldGet(y, rank=rank_y, _RC)
      if(rank_x == rank_y) then
         count_x = FieldGetLocalElementCount(x, _RC)
         count_y = FieldGetLocalElementCount(y, _RC)
         conformable = all(count_x == count_y)
      end if
      _RETURN(_SUCCESS)
   end function are_conformable_scalar
Call graph
are_conformable_scalar calls esmf_fieldget, fieldgetlocalelementcount, mapl_return, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_throw_exception calls initialize
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_return, mapl_verify, mapl_assert
fieldsareconformable calls are_conformable_scalar
are_broadcast_conformable calls fieldsareconformable
are_conformable_array calls fieldsareconformable
axpy_r4 calls fieldsareconformable
axpy_r8 calls fieldsareconformable
copy_broadcast calls fieldsareconformable
copy calls fieldsareconformable
fieldabs calls fieldsareconformable
fieldacos calls fieldsareconformable
fieldadd calls fieldsareconformable
fieldasin calls fieldsareconformable
fieldatan calls fieldsareconformable
fieldcos calls fieldsareconformable
fieldcosh calls fieldsareconformable
fielddivide calls fieldsareconformable
fieldexp calls fieldsareconformable
fieldlog calls fieldsareconformable
fieldlog10 calls fieldsareconformable
fieldmultiply calls fieldsareconformable
fieldpow calls fieldsareconformable
fieldpower calls fieldsareconformable
fieldsin calls fieldsareconformable
fieldsinh calls fieldsareconformable
fieldsqrt calls fieldsareconformable
fieldsubtract calls fieldsareconformable
fieldtan calls fieldsareconformable
fieldtanh calls fieldsareconformable
gemv_r4 calls fieldsareconformable
gemv_r8 calls fieldsareconformable
test_fieldsareconformabler4 calls fieldsareconformable
test_fieldsareconformabler8 calls fieldsareconformable