array_format_string – MAPL
array_format_string Function
10 statements
Source File
private pure function array_format_string(scalar_format, array_size_string) result(array_format)
Create array format string from scalar format string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: scalar_format
character(len=*), intent(in) :: array_size_string
Return Value character(len=:), allocatable
Called by
Source Code
   pure function array_format_string(scalar_format, array_size_string) result(array_format)
      character(len=*), intent(in) :: scalar_format
      character(len=*), intent(in) :: array_size_string
      character(len=:), allocatable :: array_format
      character(len=:), allocatable :: one_group
      integer :: lsf
      lsf = len_trim(scalar_format)
      one_group = scalar_format(2:(lsf-1))
      array_format = '('//trim(adjustl(array_size_string))// '(' // one_group//',1X))'
!      array_format = '('//trim(adjustl(array_size_string))//scalar_format(1:len_trim(scalar_format)-1)//',1X))'
   end function array_format_string
Call graph
array_format calls array_format_string
mapl_getresource_config_array calls array_format
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefrommapl_array