ArrayScatterRcvCnt_I4_1 – MAPL
ArrayScatterRcvCnt_I4_1 Subroutine
39 statements
Source File
private subroutine ArrayScatterRcvCnt_I4_1(local_array, global_array, sendcounts, vm, srcPe, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=ESMF_KIND_I4), intent(out) :: local_array(:)
integer(kind=ESMF_KIND_I4), intent(in), target :: global_array(:)
integer :: sendcounts(:)
type(ESMF_VM) :: vm
integer, intent(in), optional :: srcPe
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
arrayscatterrcvcnt_i4_1 calls mapl_assert, mapl_return, esmf_vmget, mapl_verify, esmf_vmscatterv
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
arrayscatter calls arrayscatterrcvcnt_i4_1
mapl_varread_r4_1d calls arrayscatter
mapl_varread_r8_1d calls arrayscatter
mapl_cfioreadbundle calls arrayscatter
mapl_varread_r4_2d calls arrayscatter, mapl_varread
mapl_varread_r8_2d calls arrayscatter, mapl_varread
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r8_1d, mapl_varread_r4_2d, mapl_varread_r8_2d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioreadstate calls mapl_cfioreadbundle
test_main calls mapl_cfioread, esmf_ioread
initialize_ calls mapl_cfioread
mapl_simplebundleread calls mapl_cfioread
mapl_fieldread calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_climupdate calls mapl_varread
readrestart calls mapl_varread
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_cfioreadarray2d calls mapl_cfioreadfield