ArrayGatherRcvCnt_R4_1 – MAPL
ArrayGatherRcvCnt_R4_1 Subroutine
39 statements
Source File
private subroutine ArrayGatherRcvCnt_R4_1(local_array, global_array, recvcounts, vm, dstPe, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: local_array(:)
real(kind=ESMF_KIND_R4), intent(out) :: global_array(:)
integer :: recvcounts(:)
type(ESMF_VM) :: vm
integer, intent(in), optional :: dstPe
integer, intent(out), optional :: rc
Calls
Called by
Call graph
arraygatherrcvcnt_r4_1 calls ESMF_VMGatherV, ESMF_VMGet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
arraygather calls arraygatherrcvcnt_r4_1
bundlediff calls arraygather
bundleregrid calls arraygather
mapl_areamean_2d_r8_bitrep calls arraygather
mapl_cfiocreatefrombundle calls arraygather
mapl_cfiowritebundlepost calls arraygather
mapl_fieldwritencpar calls arraygather
mapl_getlatloncoord_real32 calls arraygather
mapl_getlatloncoord_real64 calls arraygather
mapl_gridgetlatlons calls arraygather
mapl_varwrite_i4_1d calls arraygather
mapl_varwrite_r4_1d calls arraygather
mapl_varwrite_r4_2d calls arraygather
mapl_varwrite_r8_1d calls arraygather
mapl_varwrite_r8_2d calls arraygather
esmf_iocreate calls mapl_cfiocreatefrombundle
esmfl_diff calls bundlediff
esmfl_regrid calls bundleregrid
mapl_areamean calls mapl_areamean_2d_r8_bitrep
mapl_cfiocreate calls mapl_cfiocreatefrombundle
mapl_getlatloncoord calls mapl_getlatloncoord_real32, mapl_getlatloncoord_real64
mapl_varwrite calls mapl_varwrite_i4_1d, mapl_varwrite_r4_1d, mapl_varwrite_r4_2d, mapl_varwrite_r8_1d, mapl_varwrite_r8_2d
bundlestatistics calls bundlediff
mapl_bundlewritencpar calls mapl_fieldwritencpar
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
mygridcreate_ calls mapl_gridgetlatlons
statediff calls bundlediff
stateregrid calls bundleregrid