ArrayGather_R8_2 – MAPL
ArrayGather_R8_2 Subroutine
137 statements
Source File
private subroutine ArrayGather_R8_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: local_array(:,:)
real(kind=ESMF_KIND_R8), intent(out) :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
Calls
Contents
Call graph
arraygather_r8_2 calls mapl_assert, mapl_verify, esmf_distgridget, esmf_delayoutget, esmf_gridget, esmf_vmget, mapl_distgridget, mapl_commsgatherv, esmf_vmbarrier, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_distgridget calls mapl_verify, esmf_distgridget
mapl_commsgatherv calls mapl_commsgatherv_i4_1, mapl_commsgatherv_r8_1, mapl_commsgatherv_r8_2, mapl_commsgatherv_r4_2, mapl_commsgatherv_r4_1
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_commsgatherv_i4_1 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_gatherv
mapl_throw_exception calls initialize
mapl_commsgatherv_r8_1 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_gatherv
mapl_commsgatherv_r8_2 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_gatherv
mapl_commsgatherv_r4_2 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_gatherv
mapl_commsgatherv_r4_1 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_gatherv