array_format_simple – MAPL
array_format_simple Function
8 statements
Source File
private pure function array_format_simple(scalar_format) result(array_format)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: scalar_format
Return Value character(len=:), allocatable
Called by
Contents
Source Code
array_format_simple
Source Code
   pure function array_format_simple(scalar_format) result(array_format)
      character(len=*), intent(in) :: scalar_format
      character(len=:), allocatable :: array_format
      character(len=:), allocatable :: base_format
      character(len=*), parameter :: UNLIMITED_FORMAT_ITEM = "*"
      base_format = scalar_format(2:(len_trim(scalar_format)-1))
      array_format = '(' // UNLIMITED_FORMAT_ITEM // '(' // base_format //', 1X))'
   end function array_format_simple
Call graph
array_format calls array_format_simple
mapl_getresource_config_array calls array_format
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefrommapl_array