ArrayGather_R4_2 – MAPL
ArrayGather_R4_2 Subroutine
138 statements
Source File
private subroutine ArrayGather_R4_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: local_array(:,:)
real(kind=ESMF_KIND_R4), intent(out) :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
Calls
Call graph
arraygather_r4_2 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMBarrier, ESMF_VMGet, mapl_assert, mapl_commsgatherv, mapl_distgridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commsgatherv calls mapl_commsgatherv_i4_1, mapl_commsgatherv_r4_1, mapl_commsgatherv_r4_2, mapl_commsgatherv_r8_1, mapl_commsgatherv_r8_2
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_commsgatherv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_commsgatherv_r8_2 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_gatherv
mapl_throw_exception calls initialize