ArrayScatter_R4_2 – MAPL
ArrayScatter_R4_2 Subroutine
170 statements
Source File
private subroutine ArrayScatter_R4_2(local_array, global_array, grid, mask, depe, hw, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(out) :: local_array(:,:)
real(kind=ESMF_KIND_R4), intent(in), target :: global_array(:,:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(in), optional :: depe
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
arrayscatter_r4_2 calls mapl_assert, mapl_verify, esmf_gridget, esmf_distgridget, esmf_delayoutget, esmf_vmget, mapl_distgridget, mapl_commsscatterv, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_distgridget calls mapl_verify, esmf_distgridget
mapl_commsscatterv calls mapl_commsscatterv_i4_1, mapl_commsscatterv_r4_1, mapl_commsscatterv_r8_2, mapl_commsscatterv_r4_2, mapl_commsscatterv_r8_1
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_commsscatterv_i4_1 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_scatterv
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_commsscatterv_r4_1 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_scatterv
mapl_commsscatterv_r8_2 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_scatterv
mapl_commsscatterv_r4_2 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_scatterv
mapl_commsscatterv_r8_1 calls mapl_verify, esmf_delayoutget, esmf_vmget, mapl_return, mpi_scatterv
arrayscatter calls arrayscatter_r4_2
mapl_varread_r4_1d calls arrayscatter
mapl_varread_r8_1d calls arrayscatter
mapl_cfioreadbundle calls arrayscatter
mapl_varread_r4_2d calls arrayscatter, mapl_varread
mapl_varread_r8_2d calls arrayscatter, mapl_varread
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r8_1d, mapl_varread_r4_2d, mapl_varread_r8_2d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioreadstate calls mapl_cfioreadbundle
test_main calls mapl_cfioread, esmf_ioread
initialize_ calls mapl_cfioread
mapl_simplebundleread calls mapl_cfioread
mapl_fieldread calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_climupdate calls mapl_varread
readrestart calls mapl_varread
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_cfioreadarray2d calls mapl_cfioreadfield