ArrayScatterShmR4D1 – MAPL
ArrayScatterShmR4D1 Subroutine
126 statements
Source File
private subroutine ArrayScatterShmR4D1(local_array, global_array, grid, mask, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: local_array(:)
real, target :: global_array(:)
type(ESMF_Grid) :: grid
integer, intent(in), optional :: mask(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine ArrayScatterShmR4D1(local_array, global_array, grid, mask, rc)
! Mask is really a permutation on the first dimension
    real,         intent(  OUT) :: local_array(:)
!    TYPE_(kind=EKIND_), target, intent(IN) :: global_array DIMENSIONS_
    real, target                :: global_array(:)
    type (ESMF_Grid)                          :: grid
    integer, optional,          intent(IN   ) :: mask(:)
    integer, optional,          intent(  OUT) :: rc
! Local variables
    integer                               :: status
    real,    pointer        :: myglob(:) => null()
    real,    pointer        :: VAR(:)
    type (ESMF_DistGrid)                  :: distGrid
    type(ESMF_DELayout)                   :: LAYOUT
    type (ESMF_VM)                        :: vm
    integer,               allocatable    :: AL(:,:)
    integer,               allocatable    :: AU(:,:)
    integer, dimension(:), allocatable    :: SENDCOUNTS, DISPLS
    integer                               :: KK
    integer                               :: nDEs
    integer                               :: recvcount
    integer                               :: I, K, II, deId
    integer                               :: gridRank
    integer                               :: LX
    integer                               :: srcPE
    integer                               :: ISZ
    logical                               :: alloc_var
    logical                               :: use_shmem
! Works only on 1D and 2D arrays
! Note: for tile variables the gridRank is 1
! and the case RANK_=2 needs additional attention
! use_shmem controls communication (bcastToNodes+local copy vs scatterv)
    use_shmem = .true.
    ! temporary Shmem restricted only to 1d and tile vars
    if (.not.present(mask)) use_shmem = .false.
! Optional change of source PE. Default=MAPL_Root
    srcPE = MAPL_Root
! Initialize
    alloc_var = .true.
! Get grid and layout information
    call ESMF_GridGet    (GRID,   dimCount=gridRank, rc=STATUS);_VERIFY(STATUS)
    call ESMF_GridGet    (GRID,   distGrid=distGrid, rc=STATUS);_VERIFY(STATUS)
    call ESMF_DistGridGet(distGRID, delayout=layout, rc=STATUS);_VERIFY(STATUS)
    call ESMF_DELayoutGet(layout, vm=vm, rc=status);_VERIFY(STATUS)
    call ESMF_VmGet(vm, localPet=deId, petCount=nDEs, rc=status);_VERIFY(STATUS)
    if (use_shmem) then
       srcPE = deId
    end if
    allocate (AL(gridRank,0:nDEs-1),  stat=status)
    _VERIFY(STATUS)
    allocate (AU(gridRank,0:nDEs-1),  stat=status)
    _VERIFY(STATUS)
    allocate (sendcounts(0:nDEs-1), stat=status)
    _VERIFY(STATUS)
    call MAPL_DistGridGet(distgrid, &
         minIndex=AL, maxIndex=AU, rc=status)
    _VERIFY(STATUS)
    ISZ = size(GLOBAL_ARRAY,1)
    if (use_shmem) then
       call MAPL_SyncSharedMemory(rc=STATUS)
       _VERIFY(STATUS)
       call MAPL_BroadcastToNodes(global_array, N=ISZ, ROOT=MAPL_Root, rc=status)
       _VERIFY(STATUS)
       call MAPL_SyncSharedMemory(rc=STATUS)
       _VERIFY(STATUS)
    end if
! Compute count to be sent to each PE
    if(present(mask)) then
       sendcounts = 0
       do II = 1,ISZ
          sendcounts(mask(ii)) = sendcounts(mask(ii)) + 1
       enddo
    else
       do I = 0,nDEs-1
          LX = AU(1,I) - AL(1,I) + 1
          sendcounts(I) = LX
       end do
    end if
! Count I will recieve
    recvcount = sendcounts(deId)
! Put VAR together at the srcPE
    if (deId == srcPE) then
       allocate(DISPLS(0:nDEs          ), stat=status)
       _VERIFY(STATUS)
! Compute displacements into the VAR vector
       displs(0) = 0
       do I = 1,nDEs
          displs(I) = displs(I-1) + sendcounts(I-1)
       end do
       myglob => global_array
! Fill the VAR vector
       if (present(mask)) then
          allocate(VAR(displs(deId):displs(deId+1)-1), stat=status)
          _VERIFY(STATUS)
          KK = DISPLS(deId)
          do I=1,ISZ
             K = MASK(I)
             if(K == deId) then
                II = KK
                VAR(II) = MYGLOB(I)
                KK = KK + 1
             end if
          end do
       else
          var => myglob
          alloc_var = .false.
       endif !  present(mask)
     else
        allocate(var(0:1), stat=status)
        _VERIFY(STATUS)
        allocate(DISPLS(0:nDEs), stat=status)
        _VERIFY(STATUS)
     end if !  I am srcPEa
! Do the communications
    if (use_shmem) then
       ! copy my piece from var (var is local but was filled from shared array)
       call MAPL_SyncSharedMemory(rc=STATUS)
       _VERIFY(STATUS)
       local_array = var(displs(deId):displs(deId+1)-1)
       call MAPL_SyncSharedMemory(rc=STATUS)
       _VERIFY(STATUS)
    else
       call MAPL_CommsScatterV(layout, var, sendcounts, displs, &
                               local_array, recvcount, srcPE, status)
       _VERIFY(STATUS)
    end if
! Clean-up
    deallocate(displs, stat=status)
    _VERIFY(STATUS)
    if(alloc_var) then
       deallocate(VAR, stat=status)
       _VERIFY(STATUS)
    end if
    deallocate(sendcounts, stat=status)
    _VERIFY(STATUS)
    deallocate(AU,         stat=status)
    _VERIFY(STATUS)
    deallocate(AL,         stat=status)
    _VERIFY(STATUS)
! All done
    _RETURN(ESMF_SUCCESS)
  end subroutine ArrayScatterShmR4D1
Call graph
arrayscattershmr4d1 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_broadcasttonodes, mapl_commsscatterv, mapl_syncsharedmemory, mapl_distgridget, mapl_return, mapl_verify
mapl_broadcasttonodes calls broadcasttonodes_1di4, broadcasttonodes_1dr4, broadcasttonodes_1dr8, broadcasttonodes_2di4, broadcasttonodes_2dr4, broadcasttonodes_2dr8, broadcasttonodes_3di4, broadcasttonodes_3dr4, broadcasttonodes_3dr8, broadcasttonodes_4dr4, broadcasttonodes_4dr8
mapl_commsscatterv calls mapl_commsscatterv_i4_1, mapl_commsscatterv_r4_1, mapl_commsscatterv_r4_2, mapl_commsscatterv_r8_1, mapl_commsscatterv_r8_2
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
arrayscattershm calls arrayscattershmr4d1
mapl_varread_r4_1d calls arrayscattershm
mapl_varread_r4_2d calls arrayscattershm, mapl_varread
mapl_varreadncpar_r4_1d calls arrayscattershm
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r4_2d, mapl_varreadncpar_r4_1d
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_fieldread calls mapl_varread
mapl_fieldreadncpar calls mapl_varread
mapl_readforcingx calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
mapl_varreadncpar_r4_3d calls mapl_varread
mapl_varreadncpar_r8_3d calls mapl_varread
readrestart calls mapl_varread