ArrDescrCreateWriterComm – MAPL
ArrDescrCreateWriterComm Subroutine
43 statements
Source File
public subroutine ArrDescrCreateWriterComm(arrdes, full_comm, num_writers, rc)
Arguments
Type Intent Optional Attributes Name
type(ArrDescr), intent(inout) :: arrdes
integer, intent(in) :: full_comm
integer, intent(in) :: num_writers
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine ArrDescrCreateWriterComm(arrdes, full_comm, num_writers, rc)
       type(ArrDescr), intent(inout) :: arrdes
       integer, intent(in) :: full_comm
       integer, intent(in) :: num_writers
       integer, optional, intent(out) :: rc
       integer :: status, nx, ny, color, ny_by_writers, myid, j, writer_rank
       nx = size(arrdes%i1)
       ny = size(arrdes%j1)
       _ASSERT(num_writers <= ny,'num writers must be less or equal to than NY')
       _ASSERT(mod(ny,num_writers)==0,'num writerss must evenly divide NY')
       call mpi_comm_rank(full_comm,myid, status)
       _VERIFY(status)
       color =  arrdes%NX0
       call MPI_COMM_SPLIT(full_comm, color, MYID, arrdes%Ycomm, status)
       _VERIFY(status)
       color = arrdes%NY0
       call MPI_COMM_SPLIT(full_comm, color, MYID, arrdes%Xcomm, status)
       _VERIFY(status)
       ny_by_writers = ny/num_writers
       if (mod(myid,nx*ny/num_writers) == 0) then
          color = 0
       else
          color = MPI_UNDEFINED
       endif
       call MPI_COMM_SPLIT(full_comm, color, myid, arrdes%writers_comm, status)
       _VERIFY(status)
       if (num_writers==ny) then
          call MAPL_Comm_dup(arrdes%Xcomm, ArrDes%IOgathercomm, status)
       else
            j = arrdes%NY0 - mod(arrdes%NY0-1,ny_by_writers)
          call MPI_COMM_SPLIT(full_comm, j, myid, arrdes%IOgathercomm, status)
          _VERIFY(status)
       endif
       if (arrdes%writers_comm /= MPI_COMM_NULL) then
          call mpi_comm_rank(arrdes%writers_comm,writer_rank,status)
          _VERIFY(STATUS)
       end if
       call MPI_BCast(writer_rank,1,MPI_INTEGER,0,arrdes%iogathercomm,status)
       _VERIFY(STATUS)
       arrdes%writer_id = writer_rank
       _RETURN(_SUCCESS)
    end subroutine ArrDescrCreateWriterComm
Call graph
arrdescrcreatewritercomm calls mapl_assert, mpi_bcast, mpi_comm_rank, mpi_comm_split, mapl_comm_dup, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_comm_dup calls mapl_return, mapl_verify, mpi_comm_dup
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
arrdescrsetncpar calls arrdescrcreatewritercomm
mapl_esmfstatewritetofile calls arrdescrcreatewritercomm, arrdescrsetncpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_esmfstatereadfromfile calls arrdescrsetncpar
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericrecord calls mapl_staterecord
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
record_component calls capture
record_state calls mapl_genericstatesave
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
mapl_genericwrapper calls record_component
refresh_state calls mapl_genericstaterestore