ArrDescrSet – MAPL
ArrDescrSet Subroutine
20 statements
Source File
public subroutine ArrDescrSet(ArrDes, offset, readers_comm, ioscattercomm, writers_comm, iogathercomm, i1, in, j1, jn, im_world, jm_world, lm_world)
Arguments
Type Intent Optional Attributes Name
type(ArrDescr), intent(inout) :: ArrDes
integer(kind=MPI_OFFSET_KIND), intent(in), optional :: offset
integer, intent(in), optional :: readers_comm
integer, intent(in), optional :: ioscattercomm
integer, intent(in), optional :: writers_comm
integer, intent(in), optional :: iogathercomm
integer, optional, target :: i1(:)
integer, optional, target :: in(:)
integer, optional, target :: j1(:)
integer, optional, target :: jn(:)
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm_world
Called by
Source Code
    subroutine ArrDescrSet(ArrDes, offset, &
         readers_comm, ioscattercomm, &
         writers_comm, iogathercomm, &
         i1, in, j1, jn, im_world, jm_world, lm_world)
      type(ArrDescr),                 intent(INOUT) :: ArrDes
      integer(kind=MPI_OFFSET_KIND), &
                           optional,  intent(IN   ) :: offset
      integer, optional,              intent(IN   ) :: readers_comm, ioscattercomm
      integer, optional,              intent(IN   ) :: writers_comm, iogathercomm
      integer, optional, target                    :: i1(:), in(:), j1(:), jn(:)
      integer, optional,              intent(IN   ) :: im_world, jm_world, lm_world
      if(present(offset  )) ArrDes%offset   = offset
      if(present(readers_comm )) ArrDes%readers_comm  = readers_comm
      if(present(ioscattercomm)) ArrDes%ioscattercomm = ioscattercomm
      if(present(writers_comm )) ArrDes%writers_comm  = writers_comm
      if(present(iogathercomm )) ArrDes%iogathercomm  = iogathercomm
      if(present(i1      )) ArrDes%i1       => i1
      if(present(in      )) ArrDes%in       => in
      if(present(j1      )) ArrDes%j1       => j1
      if(present(jn      )) ArrDes%jn       => jn
      if(present(im_world)) ArrDes%im_world = im_world
      if(present(jm_world)) ArrDes%jm_world = jm_world
      if(present(lm_world)) ArrDes%lm_world = lm_world
    end subroutine ArrDescrSet
Call graph
arrdescrsetncpar calls arrdescrset
mapl_bundlewritencpar calls arrdescrset
mapl_esmfstatereadfromfile calls arrdescrset, arrdescrsetncpar
mapl_esmfstatewritetofile calls arrdescrset, arrdescrsetncpar, mapl_varwritencpar
mapl_readforcingx calls arrdescrset
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarwritencpar calls mapl_bundlewritencpar
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore