ArrDescrCreateReaderComm – MAPL
ArrDescrCreateReaderComm Subroutine
36 statements
Source File
public subroutine ArrDescrCreateReaderComm(arrdes, full_comm, num_readers, rc)
Arguments
Type Intent Optional Attributes Name
type(ArrDescr), intent(inout) :: arrdes
integer, intent(in) :: full_comm
integer, intent(in) :: num_readers
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine ArrDescrCreateReaderComm(arrdes, full_comm, num_readers, rc)
       type(ArrDescr), intent(inout) :: arrdes
       integer, intent(in) :: full_comm
       integer, intent(in) :: num_readers
       integer, optional, intent(out) :: rc
       integer :: status, nx, ny, color, ny_by_readers, myid, j
       nx = size(arrdes%i1)
       ny = size(arrdes%j1)
       _ASSERT(num_readers <= ny,'num readers must be less than or equal to NY')
       _ASSERT(mod(ny,num_readers)==0,'num readers must evenly divide NY')
       call mpi_comm_rank(full_comm,myid, status)
       _VERIFY(status)
       color =  arrdes%NX0
       call MPI_COMM_SPLIT(full_comm, color, MYID, arrdes%Ycomm, status)
       _VERIFY(status)
       color = arrdes%NY0
       call MPI_COMM_SPLIT(full_comm, color, MYID, arrdes%Xcomm, status)
       _VERIFY(status)
       ny_by_readers = ny/num_readers
       if (mod(myid,nx*ny/num_readers) == 0) then
          color = 0
       else
          color = MPI_UNDEFINED
       endif
       call MPI_COMM_SPLIT(full_comm, color, MYID, arrdes%readers_comm, status)
       _VERIFY(status)
       if (num_readers==ny) then
          call MAPL_Comm_dup(arrdes%Xcomm, ArrDes%IOscattercomm, status)
       else
          j = arrdes%NY0 - mod(arrdes%NY0-1,ny_by_readers)
          call MPI_COMM_SPLIT(full_comm, j, MYID, arrdes%IOscattercomm, status)
          _VERIFY(status)
       endif
       _RETURN(_SUCCESS)
    end subroutine ArrDescrCreateReaderComm
Call graph
arrdescrcreatereadercomm calls mapl_assert, mpi_comm_rank, mpi_comm_split, mapl_comm_dup, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_comm_dup calls mapl_return, mapl_verify, mpi_comm_dup
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
arrdescrsetncpar calls arrdescrcreatereadercomm
mapl_esmfstatereadfromfile calls arrdescrcreatereadercomm, arrdescrsetncpar
mapl_esmfstatewritetofile calls arrdescrsetncpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
refresh_state calls mapl_genericstaterestore
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave