ArrDescrSetNCPar – MAPL
ArrDescrSetNCPar Subroutine
88 statements
Source File
private subroutine ArrDescrSetNCPar(ArrDes, MPL, tile, offset, num_readers, num_writers, RC)
Arguments
Type Intent Optional Attributes Name
type(ArrDescr), intent(inout) :: ArrDes
type(MAPL_MetaComp), intent(inout) :: MPL
logical, intent(in), optional :: tile
integer(kind=MPI_OFFSET_KIND), intent(in), optional :: offset
integer, intent(in), optional :: num_readers
integer, intent(in), optional :: num_writers
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine ArrDescrSetNCPar(ArrDes, MPL, tile, offset, num_readers, num_writers, rc)
      type(ArrDescr),                 intent(INOUT) :: ArrDes
      type(MAPL_MetaComp),            intent(INOUT) :: MPL
      logical, optional,              intent(in   ) :: tile
      integer(kind=MPI_OFFSET_KIND), &
           optional,  intent(IN   ) :: offset
      integer, optional,              intent(IN   ) :: num_readers
      integer, optional,              intent(IN   ) :: num_writers
      integer, optional,              intent(  OUT) :: RC
      integer                       :: COUNTS(2),CCPD(3), km_world
      integer                       :: status
      integer(kind=MPI_OFFSET_KIND) :: offset_local
      logical                       :: tile_loc
      type(ESMF_Grid)               :: TILEGRID
      character(len=MPI_MAX_INFO_VAL) :: romio_cb_read,cb_buffer_size,romio_cb_write
      if (present(tile)) then
         tile_loc=tile
      else
         tile_loc=.false.
      endif
      if (present(offset)) then
         offset_local = offset
      else
         offset_local = 0
      endif
      if (tile_loc) then
         call MAPL_LocStreamGet(MPL%LocStream, TILEGRID=TILEGRID,RC=status)
         _VERIFY(status)
         call MAPL_GridGet(TILEGRID,globalCellCountPerDim=COUNTS,RC=status)
         _VERIFY(status)
         call ArrDescrSet(arrdes, offset_local, &
              readers_comm  = mpl%grid%readers_comm,  &
              ioscattercomm = mpl%grid%comm, &
              writers_comm = mpl%grid%writers_comm, &
              iogathercomm = mpl%grid%comm, &
              i1 = mpl%grid%i1, in = mpl%grid%in,     &
              j1 = mpl%grid%j1, jn = mpl%grid%jn,     &
              im_world = COUNTS(1),                   &
              jm_world = COUNTS(2))
         arrdes%ycomm = mpl%grid%Ycomm
         arrdes%xcomm = mpl%grid%Xcomm
         arrdes%NY0   = mpl%grid%NY0
         arrdes%NX0   = mpl%grid%NX0
         arrdes%tile=.true.
         arrdes%grid=tilegrid
      else
         call MAPL_GridGet(mpl%grid%ESMFGRID,globalCellCountPerDim=CCPD,RC=status)
         _VERIFY(status)
         km_world = CCPD(3)
         call ArrDescrSet(arrdes, offset_local, &
              readers_comm  = mpl%grid%readers_comm,  &
              ioscattercomm = mpl%grid%ioscattercomm, &
              writers_comm = mpl%grid%writers_comm, &
              iogathercomm = mpl%grid%iogathercomm, &
              i1 = mpl%grid%i1, in = mpl%grid%in,     &
              j1 = mpl%grid%j1, jn = mpl%grid%jn,     &
              im_world = mpl%grid%im_world,           &
              jm_world = mpl%grid%jm_world,           &
              lm_world = km_world)
         arrdes%ycomm = mpl%grid%Ycomm
         arrdes%xcomm = mpl%grid%Xcomm
         arrdes%NY0   = mpl%grid%NY0
         arrdes%NX0   = mpl%grid%NX0
         arrdes%tile=.false.
         arrdes%grid=MPL%GRID%ESMFGRID
         call set_arrdes_by_face()
      endif
      call MAPL_GetResource(MPL, romio_cb_read, Label="ROMIO_CB_READ:", default="automatic", RC=status)
      _VERIFY(status)
      arrdes%romio_cb_read = romio_cb_read
      call MAPL_GetResource(MPL, romio_cb_write, Label="ROMIO_CB_WRITE:", default="enable", RC=status)
      _VERIFY(status)
      arrdes%romio_cb_write = romio_cb_write
      call MAPL_GetResource(MPL, cb_buffer_size, Label="CB_BUFFER_SIZE:", default="16777216", RC=status)
      _VERIFY(status)
      arrdes%cb_buffer_size = cb_buffer_size
      if (present(num_readers)) arrdes%num_readers=num_readers
      if (present(num_writers)) arrdes%num_writers=num_writers
      arrdes%write_restart_by_oserver = mpl%grid%write_restart_by_oserver
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine set_arrdes_by_face()
         integer :: color, key
         character(len=ESMF_MAXSTR)    :: Iam="ArrDescrSetNCPar_face"
         integer :: status
         if (mpl%grid%im_world /= mpl%grid%jm_world/6) return ! only apply to cube
         color = (arrdes%j1(mpl%grid%NY0)-1)/mpl%grid%im_world + 1
         arrdes%face_index = color
         key   = 1
         if ( mpl%grid%write_restart_by_face) then
            arrdes%write_restart_by_face = .true.
            if (mpl%grid%writers_comm /= MPI_COMM_NULL) then
               call MPI_COMM_SPLIT( mpl%grid%writers_comm,color,key,arrdes%face_writers_comm, status)
               _VERIFY(status)
            endif
         endif
         if ( mpl%grid%read_restart_by_face) then
            arrdes%read_restart_by_face = .true.
            if (mpl%grid%readers_comm /= MPI_COMM_NULL) then
               call MPI_COMM_SPLIT( mpl%grid%readers_comm,color,key,arrdes%face_readers_comm, status)
               _VERIFY(status)
            endif
         endif
      end subroutine set_arrdes_by_face
   end subroutine ArrDescrSetNCPar
Call graph
arrdescrsetncpar calls mapl_getresource, mpi_comm_split, arrdescrset, mapl_gridget, mapl_locstreamget, mapl_return, mapl_verify
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_locstreamget calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_getresourcefromconfig_array calls mapl_return, mapl_verify, mapl_getresource_config_array
mapl_getresourcefromconfig_scalar calls mapl_return, mapl_verify, mapl_getresource_config_scalar
mapl_getresourcefrommapl_array calls mapl_return, mapl_verify, mapl_getresource_config_array
mapl_getresourcefrommapl_scalar calls mapl_return, mapl_verify, mapl_getresource_config_scalar
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
mapl_esmfstatereadfromfile calls arrdescrsetncpar
mapl_esmfstatewritetofile calls arrdescrsetncpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore
mapl_genericwrapper calls record_component