ArrDescrCommFree – MAPL
ArrDescrCommFree Subroutine
19 statements
Source File
public subroutine ArrDescrCommFree(arrdes, rc)
Arguments
Type Intent Optional Attributes Name
type(ArrDescr), intent(inout) :: arrdes
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine ArrDescrCommFree(arrdes, rc)
    type(ArrDescr), intent(inout) :: arrdes
    integer, optional, intent(out) :: rc
    integer :: status
    call MAPL_CommFree(arrdes%Xcomm, _RC)
    call MAPL_CommFree(arrdes%Ycomm, _RC)
    call MAPL_CommFree(arrdes%readers_comm, _RC)
    call MAPL_CommFree(arrdes%writers_comm, _RC)
    call MAPL_CommFree(arrdes%IOgathercomm, _RC)
    call MAPL_CommFree(arrdes%IOscattercomm, _RC)
    _RETURN(ESMF_SUCCESS)
  end subroutine ArrDescrCommFree
Call graph
arrdescrcommfree calls mapl_commfree, mapl_return, mapl_verify
mapl_commfree calls mapl_return, mapl_verify, mpi_comm_free
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_esmfstatereadfromfile calls arrdescrcommfree
mapl_esmfstatewritetofile calls arrdescrcommfree
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore
mapl_genericwrapper calls record_component