assign_fptr_r8_rank1 – MAPL
assign_fptr_r8_rank1 Subroutine
17 statements
Source File
private subroutine assign_fptr_r8_rank1(x, fptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
real(kind=ESMF_KIND_R8), intent(out), pointer :: fptr(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine assign_fptr_r8_rank1(x, fptr, rc)
      type(ESMF_Field), intent(inout) :: x
      real(kind=ESMF_KIND_R8), pointer, intent(out) :: fptr(:)
      integer, optional, intent(out) :: rc
      ! local declarations
      type(c_ptr) :: cptr
      integer(ESMF_KIND_I8), allocatable :: fp_shape(:)
      integer(ESMF_KIND_I8) :: local_size
      integer :: status
      local_size = FieldGetLocalSize(x, _RC)
      fp_shape = [ local_size ]
      call FieldGetCptr(x, cptr, _RC)
      call c_f_pointer(cptr, fptr, fp_shape)
      _RETURN(_SUCCESS)
   end subroutine assign_fptr_r8_rank1
Call graph
assign_fptr_r8_rank1 calls fieldgetcptr, fieldgetlocalsize, mapl_return, mapl_verify
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_cptr calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8
get_error_message calls at, insert
get_local_size calls mapl_return, mapl_verify, fieldgetlocalelementcount
mapl_throw_exception calls initialize
fieldgetlocalelementcount calls get_local_element_count
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_cptr_i4 calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert
get_cptr_i8 calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert
get_cptr_r4 calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert
get_cptr_r8 calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert
assign_fptr calls assign_fptr_r8_rank1