Attribute_deserialize – MAPL
Attribute_deserialize Subroutine
10 statements
Source File
public subroutine Attribute_deserialize(buffer, this, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(Attribute), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
Attribute_deserialize
Source Code
   subroutine Attribute_deserialize(buffer, this, rc)
      integer, intent(in) :: buffer(:)
      type (Attribute), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      call UnlimitedEntity_deserialize(buffer, this%UnlimitedEntity, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine Attribute_deserialize
Call graph
attribute_deserialize calls mapl_return, mapl_verify, unlimitedentity_deserialize
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
unlimitedentity_deserialize calls mapl_return, mapl_verify, unlimitedentity
unlimitedentity calls new_unlimitedentity_0d, new_unlimitedentity_1d, new_unlimitedentity_2d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_5d, new_unlimitedentity_empty
get_error_message calls at
mapl_throw_exception calls initialize
new_unlimitedentity_0d calls mapl_return
new_unlimitedentity_1d calls mapl_return, mapl_assert
new_unlimitedentity_2d calls mapl_return, unlimitedentity, mapl_assert
new_unlimitedentity_3d calls mapl_return, unlimitedentity, mapl_assert
new_unlimitedentity_4d calls mapl_return, unlimitedentity, mapl_assert
new_unlimitedentity_5d calls mapl_return, unlimitedentity, mapl_assert
stringattributemap_deserialize calls attribute_deserialize
test_serialize calls attribute_deserialize
main calls stringattributemap_deserialize