axpy_r8 – MAPL
axpy_r8 Subroutine
20 statements
Source File
private subroutine axpy_r8(a, x, y, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: a
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine axpy_r8(a, x, y, rc)
      real(kind=ESMF_KIND_R8), intent(in) :: a
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y
      integer, optional, intent(out) :: rc
      real(kind=ESMF_KIND_R8), pointer :: x_ptr(:), y_ptr(:)
      logical :: conformable
      integer :: status
      call verify_typekind(x, ESMF_TYPEKIND_R8)
      call verify_typekind(y, ESMF_TYPEKIND_R8)
      conformable = FieldsAreConformable(x, y)
      _ASSERT(conformable, 'FieldAXPY() - fields not conformable.')
      call assign_fptr(x, x_ptr, _RC)
      call assign_fptr(y, y_ptr, _RC)
      y_ptr = y_ptr + a * x_ptr
      _RETURN(_SUCCESS)
   end subroutine axpy_r8
Call graph
axpy_r8 calls assign_fptr, fieldsareconformable, mapl_assert, verify_typekind, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
verify_typekind calls verify_typekind_array, verify_typekind_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls mapl_return, mapl_verify, esmf_fieldget, fieldgetlocalelementcount
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
verify_typekind_array calls verify_typekind, mapl_return, mapl_verify
verify_typekind_scalar calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget
fieldgetcptr calls get_cptr
fieldgetlocalelementcount calls get_local_element_count
fieldgetlocalsize calls get_local_size
fieldaxpy calls axpy_r8
test_fieldaxpy_r4 calls fieldaxpy
test_fieldaxpy_r8 calls fieldaxpy