barrier – MAPL
barrier Subroutine
6 statements
Source File
private subroutine barrier(this)
Type Bound
ESMF_TestCase
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestCase), intent(in) :: this
Calls
Called by
Source Code
   subroutine barrier(this)
      class (ESMF_TestCase), intent(in) :: this
      type (ESMF_VM) :: vm
      vm = this%getVM()
      call ESMF_VMBarrier(vm)
   end subroutine barrier
Call graph
barrier calls ESMF_VMBarrier, getvm
getvm calls ESMF_GridCompGet
setup calls barrier