begin – MAPL
begin Function
5 statements
Source File
private function begin(this) result(iterator)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(in), target :: this
$ iterator = MeterNodeIterator(this)
Return Value class(AbstractMeterNodeIterator), allocatable
Calls
Called by
Contents
Source Code
begin
Source Code
   function begin(this) result(iterator)
      class (AbstractMeterNodeIterator), allocatable :: iterator
      class (MeterNode), target, intent(in) :: this
!!$      iterator = MeterNodeIterator(this)
      allocate(iterator, source=MeterNodeIterator(this))
   end function begin
Call graph
begin calls meternodeiterator
meternodeiterator calls new_meternodeiterator
accumulate calls begin, accumulate, next, reset
next calls begin
get_exclusive calls next
get_num_nodes calls next, get_num_nodes
reset calls next, reset