BroadcastToNodes_2DI4 – MAPL
BroadcastToNodes_2DI4 Module Procedure
17 statements
Source File
module procedure BroadcastToNodes_2DI4 module subroutine BroadcastToNodes_2DI4(DATA, N, ROOT, rc) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: DATA(:,:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
broadcasttonodes_2di4 calls mpi_bcast, mapl_return, mapl_verify, broadcasttonodes_2di4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_broadcasttonodes calls broadcasttonodes_2di4
arrayscattershmr4d1 calls mapl_broadcasttonodes
mapl_bcastshared_1dr4 calls mapl_broadcasttonodes
mapl_bcastshared_2dr4 calls mapl_broadcasttonodes
mapl_tilemaskget calls mapl_broadcasttonodes
arrayscattershm calls arrayscattershmr4d1
mapl_bcastshared calls mapl_bcastshared_1dr4, mapl_bcastshared_2dr4
mapl_bundlereadncpar calls mapl_tilemaskget
mapl_bundlewritencpar calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
mapl_fieldreadncpar calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_fieldwritencpar calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
process_data_from_file calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget