built_vecsize – MAPL
built_vecsize Subroutine
14 statements
Source File
private subroutine built_vecsize(sim_start, sim_end, time_day, say)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: sim_start
real(kind=dp), intent(in) :: sim_end
real(kind=dp), intent(in) :: time_day
integer :: say
Called by
Contents
Source Code
built_vecsize
Source Code
subroutine built_vecsize(sim_start, sim_end, time_day, say)
       implicit none
       real(dp), intent(in) :: sim_start, sim_end, time_day
       integer          :: say
       real(dp)             :: temp1
       say = 1
       temp1 = sim_start
       !print*, "inside simend-----", sim_end, temp1, time_day
       !WRITE(*,"(1F10.2)")  sim_end
       do while (sim_end.GE.temp1)
         temp1 = temp1 + time_day
         if (temp1.LE.sim_end) then
          say = say + 1
           end if
            enddo
end subroutine built_vecsize
Call graph
find_delta_t calls built_vecsize
find_waypointslat calls built_vecsize
orbits_track calls built_vecsize, find_waypointslat
redifine_timeint calls built_vecsize
domasking_ calls orbits_track, orbits_swath
domasking_cs calls orbits_track, orbits_swath
orbits_swath calls orbits_track
run_ calls domasking_, domasking_cs