built_vec – MAPL
built_vec Subroutine
18 statements
Source File
private subroutine built_vec(sim_start, sim_end, time_day, t1)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: sim_start
real(kind=dp), intent(in) :: sim_end
real(kind=dp), intent(in) :: time_day
real(kind=dp), dimension(:) :: t1
Called by
Contents
Source Code
built_vec
Source Code
subroutine built_vec(sim_start, sim_end, time_day, t1)
       implicit none
       real(dp), intent(in) :: sim_start, sim_end, time_day
       integer          :: say
       real(dp)             :: temp1
       real(dp),  dimension(:) :: t1
       say = 1
       temp1 = sim_start ! garante that it lesim start !time
       t1(1) = sim_start
       do while (sim_end.GE.temp1)
         temp1 = temp1 + time_day
          say = say + 1
          if (say>size(t1)) then
             exit
          end if
          t1(say) = temp1
       enddo
end subroutine built_vec
Call graph
find_delta_t calls built_vec
redifine_timeint calls built_vec
find_waypointslat calls built_vec
orbits_track calls find_waypointslat
orbits_swath calls orbits_track
domasking_ calls orbits_track, orbits_swath
domasking_cs calls orbits_track, orbits_swath
run_ calls domasking_, domasking_cs