bundlepost – MAPL
bundlepost Subroutine
69 statements
Source File
private subroutine bundlepost(this, filename, oClients, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout), target :: this
character(len=*), intent(in) :: filename
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: rc
Calls
Contents
Source Code
bundlepost
Source Code
     subroutine bundlepost(this,filename,oClients,rc)
        class (MAPL_GriddedIO), target, intent(inout) :: this
        character(len=*), intent(in) :: filename
        type (ClientManager), optional, intent(inout) :: oClients
        integer, optional, intent(out) :: rc
        integer :: status
        type(ESMF_Field) :: outField
        integer :: tindex
        type(ArrayReference) :: ref
        type(GriddedIOitemVectorIterator) :: iter
        type(GriddedIOitem), pointer :: item
        logical :: have_time
        have_time = this%timeInfo%am_i_initialized()
        if (have_time) then
           this%times = this%timeInfo%compute_time_vector(this%metadata,rc=status)
           _VERIFY(status)
           ref = ArrayReference(this%times)
           call oClients%stage_nondistributed_data(this%write_collection_id,trim(filename),'time',ref)
           tindex = size(this%times)
           if (tindex==1) then
              call this%stage2DLatLon(filename,oClients=oClients,_RC)
           end if
        else
           tindex = -1
        end if
        if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
           call this%vdata%setup_eta_to_pressure(regrid_handle=this%regrid_handle,output_grid=this%output_grid,rc=status)
           _VERIFY(status)
        end if
        iter = this%items%begin()
        do while (iter /= this%items%end())
           item => iter%get()
           if (item%itemType == ItemTypeScalar) then
              call this%RegridScalar(item%xname,rc=status)
              _VERIFY(status)
              call ESMF_FieldBundleGet(this%output_bundle,item%xname,field=outField,rc=status)
              _VERIFY(status)
              if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
                 call this%vdata%correct_topo(outField,rc=status)
                 _VERIFY(status)
              end if
              call this%stageData(outField,filename,tIndex, oClients=oClients,rc=status)
              _VERIFY(status)
           else if (item%itemType == ItemTypeVector) then
              call this%RegridVector(item%xname,item%yname,rc=status)
              _VERIFY(status)
              call ESMF_FieldBundleGet(this%output_bundle,item%xname,field=outField,rc=status)
              _VERIFY(status)
              if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
                 call this%vdata%correct_topo(outField,rc=status)
                 _VERIFY(status)
              end if
              call this%stageData(outField,filename,tIndex,oClients=oClients,rc=status)
              _VERIFY(status)
              call ESMF_FieldBundleGet(this%output_bundle,item%yname,field=outField,rc=status)
              _VERIFY(status)
              if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
                 call this%vdata%correct_topo(outField,rc=status)
                 _VERIFY(status)
              end if
              call this%stageData(outField,filename,tIndex,oClients=oClients,rc=status)
              _VERIFY(status)
           end if
           call iter%next()
        enddo
        _RETURN(ESMF_SUCCESS)
     end subroutine bundlepost
Call graph
bundlepost calls esmf_fieldbundleget, get, next, mapl_return, mapl_verify, regridscalar, regridvector, stage2dlatlon, stagedata, stage_nondistributed_data
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
regridscalar calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, mapl_gridhasde
regridvector calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_gridhasde
stage2dlatlon calls mapl_return, mapl_verify, ESMF_GridGetCoord, collective_stage_data, corner_lats, generate_file_bounds, generate_file_corner_bounds, lats, get_factory
stagedata calls mapl_return, mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent, collective_stage_data, esmf_fieldget, generate_file_bounds, generate_file_reference2d, generate_file_reference3d, downbit, mapl_assert, get_factory, mapl_gridhasde