BundleDiff – MAPL
BundleDiff Subroutine
241 statements
Source File
private subroutine BundleDiff(srcBUN, dstBUN, rc)
The subroutine BundleDiff determines the diff of two bundles.
History
24Apr2006 Cruz Initial code.
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
type(ESMF_FieldBundle), intent(inout), optional :: dstBUN
integer, intent(out), optional :: rc
return code
Calls
Called by
Source Code
   subroutine BundleDiff (srcBUN, dstBUN, rc)
!
  implicit NONE
! !ARGUMENTS:
   type(ESMF_FieldBundle),           intent(inout) :: srcBUN
   type(ESMF_FieldBundle), optional, intent(inout) :: dstBUN
   integer,                optional, intent(out)   :: rc     !! return code
!
!-------------------------------------------------------------------------
! local vars
   type(ESMF_VM)           :: vm
   type(ESMF_Field)        :: dstFLD
   type(ESMF_Field)        :: srcFLD
   type(ESMF_Grid)         :: grid3D
   real(kind=REAL32), dimension(:,:    ), pointer   :: sptr2d, dptr2d
   real(kind=REAL32), dimension(:,:,:  ), pointer   :: sptr3d, dptr3d
   real(kind=REAL32), dimension(:,:,:,:), pointer   :: sptr4d, dptr4d
   real(kind=REAL32), allocatable, dimension(:,:) :: srcBuf, dstBuf, diff
   integer :: rank, k, mype, kmax, status, L, numVars, u, umax ! umax is the 4th dimension
   integer :: globalCPD(3)
   character(len=ESMF_MAXSTR)            :: srcName
   character(len=ESMF_MAXSTR), parameter :: fname = 'aleph'
   character(len=ESMF_MAXSTR), parameter :: IAm = 'BundleDiff'
! begin
   call ESMF_VMGetCurrent(vm)
   call ESMF_VMGet(vm, localPet=mype, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   ! get number of fields in bundles
   ! number in srcBUN should be the same as in dstBUN (we can change later)
   call ESMF_FieldBundleGet      (srcBUN, FieldCount=NumVars,  RC=STATUS)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   ! use only srcBUN; bundles are conformant
   call ESMF_FieldBundleGet     (srcBUN, 1, srcFLD, RC=STATUS)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   ! get grid
   call ESMF_FieldGet(srcFLD, grid=grid3D, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   ! get global counts per dim
   call ESMFL_FieldGetDims(srcFLD, gCPD=globalCPD)
   allocate(srcbuf(globalCPD(1),globalCPD(2)), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   allocate(dstbuf(globalCPD(1),globalCPD(2)), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   allocate(diff(globalCPD(1),globalCPD(2)), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   ! loop over fields in bundle
   if(verbose .and. mype==MAPL_Root) print *,' Loop through bundles'
   do L=1,NumVars
     call ESMF_FieldBundleGet     (srcBUN, L, srcFLD, RC=STATUS)
     if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
     call ESMF_FieldGet           (srcFLD, NAME=srcName, RC=STATUS)
     if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
     if(present(dstBUN)) then
        call ESMF_FieldBundleGet     (dstBUN, L, dstFLD, RC=STATUS)
        if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
     endif
     ! get rank from any field
     call ESMFL_FieldGetDims(srcFLD, ar=rank)
     ! allocate f90 pointer to hold data
     ! note halo width = 0
     umax = 1 ! by default, no 4th dimension
     if(rank==4) then
       call ESMF_FieldGet (srcFLD, localDE=0, farrayPtr=sptr4d, rc = status)
       if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
       if (present(dstBUN)) then
         call ESMF_FieldGet (dstFLD, localDE=0, farrayPtr=dptr4d, rc = status)
         if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
       endif
       umax = size(sptr4d,4)
     else if(rank==3) then
       call ESMF_FieldGet (srcFLD, localDE=0, farrayPtr=sptr3d, rc = status)
       if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
       if (present(dstBUN)) then
         call ESMF_FieldGet (dstFLD, localDE=0, farrayPtr=dptr3d, rc = status)
         if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
       endif
     else if(rank==2) then
       call ESMF_FieldGet (srcFLD, localDE=0, farrayPtr=sptr2d, rc = status)
       if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
       if (present(dstBUN)) then
          call ESMF_FieldGet (dstFLD, localDE=0, farrayPtr=dptr2d, rc = status)
          if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
       endif
     else
       if (MAPL_AM_I_Root()) print*, "WARNING: rank=1 field not implmented yet"
       cycle
     end if
    ! loop over field's vertical levels
     call ESMFL_FieldGetDims(srcFLD, lm=kmax)
     do u = 1, umax ! loop 4th ungrid dimension
        if ( umax > 1) then
          srcName = trim(srcName)//'_'//trim(ESMF_UtilStringInt2String (u))
        endif
        do k=1, kmax
          if (rank==4) then
            call ArrayGather(sptr4d(:,:,k,u), srcBuf, grid3D, RC=STATUS)
            if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
            if (present(dstBUN)) then
               call ArrayGather(dptr4d(:,:,k,u), dstBuf, grid3D, RC=STATUS)
               if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
            endif
          elseif (rank==3) then
            call ArrayGather(sptr3d(:,:,k), srcBuf, grid3D, RC=STATUS)
            if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
            if (present(dstBUN)) then
               call ArrayGather(dptr3d(:,:,k), dstBuf, grid3D, RC=STATUS)
               if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
            endif
          else
            call ArrayGather(sptr2d, srcBuf, grid3D, RC=STATUS)
            if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
            if (present(dstBUN)) then
              call ArrayGather(dptr2d, dstBuf, grid3D, RC=STATUS)
              if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
            endif
          end if
          call ESMF_VMBarrier(vm, rc=status)
          if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
          if(verbose .and. mype==MAPL_Root) then
            ! stats on level-by-level basis
            if(present(dstBUN)) then
               call stats_ ( 6, globalCPD(1), globalCPD(2), k, &
                         srcBuf,                    &
                         trim(srcName), 'lev', MAPL_undef , &
                         trim(srcName)//' diff statistics', 1, &
                         dstBuf )
            else
               call stats_ ( 6, globalCPD(1), globalCPD(2), k, &
                         srcBuf,                    &
                         trim(srcName), 'lev', MAPL_undef , &
                         trim(srcName)//' statistics', 1 &
                         )
            endif
          end if
        end do ! k
     end do ! u, ungrid fourth
   end do ! L
   if(present(dstBUN)) deallocate(dstBuf)
   deallocate(srcbuf, diff, stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   _RETURN(ESMF_SUCCESS)
CONTAINS
         logical function spv(aspv, amiss)
            real, intent(in) :: aspv
            real, intent(in) :: amiss
            real, parameter :: rfrcval = 1.0e-6
            spv = abs((aspv-amiss)/amiss).le.rfrcval
         end function spv
!>
! Print statistics of one 3-d variable. This is from the PSAS library.
! with some simplifications.
!
        subroutine stats_ (lu,mx,my,k,a1,&
                           atype,htype,amiss,header,inc, a2)
        implicit none
        integer lu              ! Output unit
        integer mx,my           ! Array sizes
        integer k               ! level
        real a1(mx,my)          ! The array1
        character(*), intent(in) :: atype       ! Type of the variable
        character(*), intent(in) :: htype       ! Typf of the levels
        real amiss              ! missing value flag of a
        character(len=*) header    ! A header message
        integer inc             ! order of the listing
        real,optional :: a2(mx,my)        ! The array2
!
        integer i,j
        integer imx,imn,jmx,jmn
        integer cnt
        real a(mx,my)        ! diff
        real amx,amn
        real avg,dev,d,rms,sumsq,relerr
        logical first
!       ..A practical value for the magnitude of the fraction of a real
!       number.
        character(len=255) dash
!       ..function
!       compute diff
        if (present(a2)) then
           a = a1 - a2
        else
           a = a1
        endif
        ! only print header when k==1
        if (k==1) then
           do i = 1, 255
              dash(i:i) = '-'
           end do
           i = len(trim(header))
           write(lu,'(//a)') trim(header)
           write(lu,'(a/)')  dash(1:i)
           if(present(a2)) then
              write(lu,'(a,1x,a,5x,a,6x,a,9x,a,9x,a,15x,a)') 'lvl',&
               'count','mean','rmse','rele','maxi','mini'
           else
              write(lu,'(a,1x,a,5x,a,6x,a,9x,a,15x,a)') 'lvl',&
               'count','mean','stdev','maxi','mini'
           endif ! present
        end if ! k==1
! compute some statistics on diff
          cnt=0
          avg=0.
          rms=0.
          do j=1,my
            do i=1,mx
              if(.not.spv(a(i,j),amiss)) then
                cnt=cnt+1
                avg=avg+a(i,j)
                if(present(a2)) then
                   sumsq = sumsq + a(i,j)*a(i,j)
                   relerr = relerr + (a1(i,j) - a2(i,j)) !/a1(i,j)
                endif
              endif
            end do
          end do
          avg=avg/max(1,cnt)
          if(present(a2)) then
             sumsq=sumsq/max(1,cnt)
             rms = sqrt(sumsq)
             relerr=relerr/max(1,cnt)
          endif
          dev=0.
          do j=1,my
            do i=1,mx
              if(.not.spv(a(i,j),amiss)) then
                d=a(i,j)-avg
                dev=dev+d*d
              endif
            end do
          end do
          dev=sqrt(dev/max(1,cnt-1))
          amx=a(1,1)
          amn=a(1,1)
          first=.true.
          do j=1,my
            do i=1,mx
              if(.not.spv(a(i,j),amiss)) then
                if(first) then
                  imx=i
                  imn=i
                  jmx=j
                  jmn=j
                  amx=a(imx,jmx)
                  amn=a(imn,jmn)
                  first=.false.
                else
                  if(a(i,j).gt.amx) then
                    amx=a(i,j)
                    imx=i
                    jmx=j
                  endif
                  if(a(i,j).lt.amn) then
                    amn=a(i,j)
                    imn=i
                    jmn=j
                  endif
                endif
              endif
            end do
          end do
          if(present(a2)) then
             write(lu,'(i3,1p,i7,1p,3e10.3e1,0p,'// &
                '2(1p,e10.3e1,0p,a,i3,a,i3,a))') &
                k,cnt,avg,rms,relerr, &
                amx,'(',imx,',',jmx,')', &
                amn,'(',imn,',',jmn,')'
           else
             write(lu,'(i3,1p,i7,1p,2e10.3e1,0p,'// &
                '2(1p,e10.3e1,0p,a,i3,a,i3,a))') &
                k,cnt,avg,dev, &
                amx,'(',imx,',',jmx,')', &
                amn,'(',imn,',',jmn,')'
           endif
           _UNUSED_DUMMY(ATYPE)
           _UNUSED_DUMMY(HTYPE)
           _UNUSED_DUMMY(INC)
      end  subroutine stats_
   end subroutine BundleDiff
Call graph
bundlediff calls ESMF_UtilStringInt2String, ESMF_VMBarrier, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, esmf_fieldget, arraygather, mapl_am_i_root, esmfl_failedrc, esmfl_fieldgetdims, mapl_return
arraygather calls arraygather_i4_1, arraygather_r4_1, arraygather_r4_2, arraygather_r8_1, arraygather_r8_2, arraygatherrcvcnt_i4_1, arraygatherrcvcnt_r4_1
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
esmfl_failedrc calls ESMF_Finalize
esmfl_fieldgetdims calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldget, esmfl_failedrc, esmf_arrayget, mapl_gridget
mapl_return calls get_error_message, mapl_throw_exception
esmfl_diff calls bundlediff, statediff
bundlestatistics calls bundlediff
statediff calls bundlediff
esmfl_statistics calls bundlestatistics, statestatistics
statestatistics calls statediff