BundleStatistics – MAPL
BundleStatistics Subroutine
10 statements
Source File
private subroutine BundleStatistics(srcBUN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: srcBUN
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
BundleStatistics
Source Code
   subroutine BundleStatistics(srcBUN, rc)
     implicit NONE
     type(ESMF_FieldBundle), intent(inout) :: srcBUN
     integer, optional, intent(out)   :: rc     ! return code
     integer :: status
     call Bundlediff(srcBUN, rc=status)
     _VERIFY(status)
     _RETURN(ESMF_SUCCESS)
   end subroutine BundleStatistics
Call graph
bundlestatistics calls bundlediff, mapl_verify, mapl_return
bundlediff calls mapl_return, esmf_vmgetcurrent, esmfl_failedrc, esmf_vmget, esmf_fieldget, esmf_fieldbundleget, esmfl_fieldgetdims, mapl_am_i_root, esmf_utilstringint2string, arraygather, esmf_vmbarrier
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
esmfl_failedrc calls esmf_finalize
esmfl_fieldgetdims calls esmf_vmgetcurrent, esmfl_failedrc, esmf_vmget, esmf_fieldget, esmf_arrayget, mapl_gridget
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
arraygather calls arraygather_r4_2, arraygatherrcvcnt_i4_1, arraygatherrcvcnt_r4_1, arraygather_i4_1, arraygather_r4_1, arraygather_r8_2, arraygather_r8_1
esmfl_statistics calls bundlestatistics