bytecode_dealloc – MAPL
bytecode_dealloc Subroutine
15 statements
Source File
private subroutine bytecode_dealloc(comp, rc)
Arguments
Type Intent Optional Attributes Name
type(tComp), intent(inout) :: comp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine bytecode_dealloc(comp,rc)
     type(tComp),       intent(inout) :: comp
     integer, optional, intent(out  ) :: rc
     integer      :: i
     integer :: status
     do i=1,comp%StackSize
        call MAPL_FieldDestroy(comp%stack(i),_RC)
     end do
     deallocate(comp%stack)
     deallocate(comp%ByteCode)
     deallocate(comp%Immed)
     _RETURN(ESMF_SUCCESS)
  end subroutine bytecode_dealloc
Call graph
bytecode_dealloc calls mapl_fielddestroy, mapl_return, mapl_verify
mapl_fielddestroy calls destroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
destroy calls mapl_return, mapl_verify, esmf_fielddestroy, esmf_fieldget, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_stateeval calls bytecode_dealloc
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
initialize_ calls fillstate
run calls mapl_runexpression
run_ calls fillstate, evaluate_derived_field, calcderivedfield
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem