calculate_mae – MAPL
calculate_mae Function
12 statements
Source File
private function calculate_mae(nsd) result(mae)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nsd
Return Value real(kind=REAL32)
Called by
Source Code
     function calculate_mae(nsd) result(mae)
        ! This function is based on Table 3 of doi 10.5194/gmd-12-4099-2019
        ! The algorithm is weird, but it does duplicate the table
        integer, intent(in) :: nsd
        real(kind=REAL32) :: mae
        real(kind=REAL32) :: mae_base
        integer :: correction
        mae_base = 4.0 * (1.0/16.0)**floor(real(nsd)/2.0) * (1.0/8.0)**ceiling(real(nsd)/2.0)
        correction = 1
        if ( (nsd > 2 .and. mod(nsd, 2) == 0) .or. nsd == 7 ) then
           correction = 2
        end if
        mae = mae_base * correction
     end function calculate_mae
Call graph
createvariable calls calculate_mae
createfilemetadata calls createvariable
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle