calcRadfromTA – MAPL
calcRadfromTA Function
4 statements
Source File
private function calcRadfromTA(TA, ECC, OMSQECC) result(Rad)
Arguments
Type Intent Optional Attributes Name
real :: TA
real :: ECC
real :: OMSQECC
Return Value real
Called by
Contents
Call graph
solar_1d calls calcradfromta, mapl_sungetinsolation
solar_2d calls calcradfromta, mapl_sungetinsolation
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
solar_arr_int calls mapl_sungetinsolation