CalcDerivedField – MAPL
CalcDerivedField Subroutine
20 statements
Source File
private subroutine CalcDerivedField(state, exportName, exportExpr, masking, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
character(len=*), intent(in) :: exportName
character(len=*), intent(in) :: exportExpr
logical, intent(in) :: masking
integer, intent(out), optional :: rc
Calls
Called by
Source Code
 subroutine CalcDerivedField(state,exportName,exportExpr,masking,rc)
     type(ESMF_State),        intent(inout) :: state
     character(len=*),        intent(in   ) :: exportName
     character(len=*),        intent(in   ) :: exportExpr
     logical,                 intent(in   ) :: masking
     integer, optional,       intent(out  ) :: rc
     integer :: status
     type(ESMF_Field)                   :: field
     if (masking) then
        call MAPL_ExtDataEvaluateMask(state,exportName,exportExpr,_RC)
     else
        call ESMF_StateGet(state,exportName,field,_RC)
        call MAPL_StateEval(state,exportExpr,field,_RC)
     end if
     _RETURN(ESMF_SUCCESS)
  end subroutine CalcDerivedField
Call graph
calcderivedfield calls esmf_stateget, mapl_extdataevaluatemask, mapl_return, mapl_stateeval, mapl_verify
mapl_extdataevaluatemask calls esmf_stateget, mapl_return, mapl_verify, ESMF_GridGetCoord, ESMF_UtilStringLowerCase, esmf_fieldget, esmfl_stategetpointertodata, mapl_assert, mapl_extdataextractintegers, mapl_gridget
mapl_return calls get_error_message, mapl_throw_exception
mapl_stateeval calls esmf_stateget, mapl_verify, fieldsarebroadcastconformable, mapl_assert, bytecode_dealloc, checksyntax, evalf, parsef
mapl_verify calls mapl_throw_exception
run_ calls calcderivedfield