calcMAfromEA – MAPL
calcMAfromEA Function
4 statements
Source File
private function calcMAfromEA(EA, ECC) result(MA)
Arguments
Type Intent Optional Attributes Name
real :: EA
real :: ECC
Return Value real
Called by
Contents
Call graph
mapl_sunorbitcreate calls calcmafromea
mapl_sunorbitcreatefromconfig calls mapl_sunorbitcreate
mapl_genericstateget calls mapl_sunorbitcreatefromconfig
mapl_readforcingx calls mapl_genericstateget
mapl_get calls mapl_genericstateget