calcTAfromEA – MAPL
calcTAfromEA Function
4 statements
Source File
private function calcTAfromEA(EA, EAFAC) result(TA)
Arguments
Type Intent Optional Attributes Name
real :: EA
real :: EAFAC
Return Value real
Called by
Contents
Call graph
mapl_sungetdaylightduration calls calctafromea
solar_1d calls calctafromea, mapl_sungetinsolation
mapl_sungetlocalsolarhourangle calls calctafromea
solar_2d calls calctafromea, mapl_sungetinsolation
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
solar_arr_int calls mapl_sungetinsolation