CALDAT – MAPL
CALDAT Subroutine
23 statements
Source File
public subroutine CALDAT(JULIAN, MM, ID, IYYY)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64) :: JULIAN
integer :: MM
integer :: ID
integer :: IYYY
Called by
Contents
Source Code
CALDAT
Source Code
      SUBROUTINE CALDAT (JULIAN,MM,ID,IYYY)
!
!C   ROUTINE CONVERTS JULIAN DAY TO MONTH, DAY, & YEAR.
!C   THIS CODE IS LIFTED FROM THE BOOK:
!C   W.H. PRESS ET AL., NUMERICAL RECIPES, CAMBRIDGE UNIV. PRESS, 1986.
!C   THE ONLY MODIFICATION IS THAT REAL ARITHMETIC IS DONE IN R*8.
!C
!C   THE ROUTINE OUTPUTS THE MONTH, DAY, AND YEAR ON WHICH THE
!C   SPECIFIED JULIAN DAY STARTED AT NOON.
!C
!C   TO CONVERT MODIFIED JULIAN DAY, CALL THIS ROUTINE WITH
!C     JULIAN = MJD + 2400001
!C
      integer(INT64) JULIAN
      integer IGREG
      integer JALPHA, JA, JB, JC, JD, JE, ID, MM, IYYY
      PARAMETER (IGREG=2299161)
      IF (JULIAN.GE.IGREG) THEN
         JALPHA=INT((DBLE(JULIAN-1867216)-0.25D0)/36524.25D0)
         JA=JULIAN+1+JALPHA-INT(0.25D0*DBLE(JALPHA))
      ELSE
         JA=JULIAN
      ENDIF
      JB=JA+1524
      JC=INT(6680.D0+(DBLE(JB-2439870)-122.1D0)/365.25D0)
      JD=365*JC+INT(0.25D0*DBLE(JC))
      JE=INT(DBLE(JB-JD)/30.6001D0)
      ID=JB-JD-INT(30.6001D0*DBLE(JE))
      MM=JE-1
      IF (MM.GT.12) MM=MM-12
      IYYY=JC-4715
      IF (MM.GT.2) IYYY=IYYY-1
      IF (IYYY.LE.0) IYYY=IYYY-1
      RETURN
      END subroutine CALDAT
Call graph
getdateint8 calls caldat
getdateint4 calls getdateint8
getdate calls getdateint8, getdateint4
getdatetimevec calls getdate
esmf_cfiovarreadt3d__ calls getdate
getbegdatetime calls getdate
gettimesonfile calls getdate, getdatetimevec
esmf_cfiovarreadt2d__ calls getdate
esmf_cfiosdfvarreadt2d__ calls getdate, getbegdatetime
esmf_cfiosdfvarreadt3d__ calls getdate, getbegdatetime
gettindex calls getdate, getdatetimevec
cfio_getvar calls getdatetimevec
esmf_cfiosdffileopen calls getbegdatetime
esmf_cfiovarreadt2 calls esmf_cfiovarreadt3d__, esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
cfio_sgetvar calls getdatetimevec
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d__
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__
mapl_cfioreadparallel_ calls gettindex