CAP_FINALIZE – MAPL
CAP_FINALIZE Subroutine
26 statements
Source File
private subroutine CAP_FINALIZE(clock, filen, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: clock
character(len=*), optional :: filen
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine CAP_FINALIZE ( clock,filen, rc )
    type(ESMF_Clock),    intent(in   ) :: clock
    character(len=*),    optional      :: filen
    integer, optional,   intent(  out) :: rc
    integer        :: UNIT
    integer        :: datetime(2)
    integer        :: YY, MM, DD, H, M, S
    integer        :: status
    character(len=ESMF_MAXSTR)            :: filen_
    type(ESMF_Time)     :: CurrentTime
    filen_ = "cap_restart"
    if (present(filen))     filen_ = trim(filen )
    ! Retrieve Current Time for Cap Restart
    ! -------------------------------------
    call ESMF_ClockGet ( clock, currTime=currentTime, rc=status )
    _VERIFY(STATUS)
    call ESMF_TimeGet  ( CurrentTime, YY = YY, &
         MM = MM, &
         DD = DD, &
         H  = H , &
         M  = M , &
         S  = S, rc=status )
    _VERIFY(STATUS)
    CALL MAPL_PackDateTime(DATETIME, YY, MM, DD, H, M, S)
    ! Write CAP Restart File and Ending Time for Current Segment
    ! ----------------------------------------------------------
    if( MAPL_AM_I_ROOT() ) then
       UNIT = GETFILE( filen_, form="formatted" )
       write(unit,100) datetime
100    format(i8.8,1x,i6.6)
       call FREE_FILE (UNIT)
    endif
    _RETURN(ESMF_SUCCESS)
  end subroutine CAP_FINALIZE
Call graph
cap_finalize calls ESMF_ClockGet, ESMF_TimeGet, mapl_am_i_root, mapl_packdatetime, free_file, getfile, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_packdatetime calls mapl_packdatetime
free_file calls mapl_return, mapl_assert
getfile calls mapl_am_i_root, mapl_return, mapl_verify, getfilemem, mapl_open
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_open calls mapl_am_i_root, mapl_return, mapl_verify
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
finalize_gc calls cap_finalize