capture – MAPL
capture Subroutine
48 statements
Source File
private subroutine capture(POS, PHASE, GC, IMPORT, EXPORT, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: POS
integer, intent(in) :: PHASE
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: IMPORT
type(ESMF_State), intent(inout) :: EXPORT
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine capture(POS, PHASE, GC, IMPORT, EXPORT, CLOCK, RC)
     character(len=*),    intent(IN   ) :: POS    ! Before or after
     integer,             intent(IN   ) :: PHASE  ! Run phase
     type(ESMF_GridComp), intent(INOUT) :: GC     ! Gridded component
     type(ESMF_State),    intent(INOUT) :: IMPORT ! Import state
     type(ESMF_State),    intent(INOUT) :: EXPORT ! Export state
     type(ESMF_Clock),    intent(INOUT) :: CLOCK  ! The clock
     integer, optional,   intent(  OUT) :: RC     ! Error code:
     type (MAPL_MetaComp), pointer :: STATE
     integer :: status
     character(len=ESMF_MAXSTR) :: filename, comp_name, time_label
     character(len=4) :: filetype
     type(ESMF_State), pointer :: internal
     integer :: hdr
     type(ESMF_Time) :: start_time, curr_time, target_time
     character(len=1) :: phase_
     call ESMF_GridCompGet(GC, NAME=comp_name, _RC)
     call MAPL_InternalStateGet (GC, STATE, _RC)
     call ESMF_ClockGet(clock, startTime=start_time, currTime=curr_time, _RC)
     call MAPL_GetResource(STATE, time_label, label='TARGET_TIME:', default='')
     if (time_label == '') then
        target_time = start_time
     else
        target_time = parse_time_string(time_label, _RC)
     end if
     filetype = 'pnc4'
     filename = trim(comp_name)//"_"
     if (curr_time == target_time) then
        internal => state%get_internal_state()
        ! force skipReading and skipWriting in NCIO to be false
        call ESMF_AttributeSet(import, name="MAPL_TestFramework", value=.true., _RC)
        write(phase_, '(i1)') phase
        call MAPL_ESMFStateWriteToFile(import, CLOCK, trim(FILENAME)//"import_"//trim(POS)//"_runPhase"//phase_, &
             FILETYPE, STATE, .false., state%grid%write_restart_by_oserver, _RC)
        call MAPL_ESMFStateWriteToFile(export, CLOCK, trim(FILENAME)//"export_"//trim(POS)//"_runPhase"//phase_, &
             FILETYPE, STATE, .false., state%grid%write_restart_by_oserver, _RC)
        call MAPL_GetResource(STATE, hdr, default=0, LABEL="INTERNAL_HEADER:", _RC)
        call MAPL_ESMFStateWriteToFile(internal, CLOCK, trim(FILENAME)//"internal_"//trim(POS)//"_runPhase"//phase_, &
             FILETYPE, STATE, hdr/=0, state%grid%write_restart_by_oserver, _RC)
     end if
     _RETURN(_SUCCESS)
   end subroutine capture
Call graph
capture calls ESMF_AttributeSet, ESMF_ClockGet, ESMF_GridCompGet, mapl_getresource, get_internal_state, mapl_esmfstatewritetofile, mapl_internalstateget, mapl_return, mapl_verify, parse_time_string
record_component calls capture
mapl_genericwrapper calls record_component