cartesian_to_spherical_3d_real64 – MAPL
cartesian_to_spherical_3d_real64 Subroutine
47 statements
Source File
private subroutine cartesian_to_spherical_3d_real64(this, xyz, u, v, basis, unusable, rc)
Uses
ESMF
MAPL_KeywordEnforcerMod
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout), target :: this
real(kind=REAL64), intent(in) :: xyz(:,:,:,:)
real(kind=REAL64), intent(out) :: u(:,:,:)
real(kind=REAL64), intent(out) :: v(:,:,:)
character(len=*), intent(in) :: basis
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine cartesian_to_spherical_3d_real64(this,xyz,u,v,basis,unusable,rc)
     use esmf
     use MAPL_KeywordEnforcerMod
     real(REAL64), intent(IN) :: xyz(:,:,:,:)
     character(len=*), intent(IN) :: basis
     real(REAL64), intent(OUT) :: u(:,:,:)
     real(REAL64), intent(OUT) :: v(:,:,:)
     class (AbstractGridFactory), target, intent(inout) :: this
     class (KeywordEnforcer), optional, intent(in) :: unusable
     integer, optional, intent(out) :: rc
     real(REAL64), pointer :: basis_vectors(:,:,:,:)
     real(REAL64) :: uv(2)
     integer :: i, j, k, im, jm, km
     character(len=*), parameter :: Iam= MOD_NAME // 'cartesian_to_spherical_3d'
     integer :: status
     _UNUSED_DUMMY(unusable)
     im = size(u,1)
     jm = size(u,2)
     km = size(u,3)
     _ASSERT(im == size(v,1), 'u-v shape mismatch for IM')
     _ASSERT(jm == size(v,2), 'u-v shape mismatch for JM')
     _ASSERT(3 == size(xyz,1), 'u-v shape mismatch (LM=1)')
     _ASSERT(km == size(xyz,2), 'u-xyz shape mismatch (LM=1)')
     _ASSERT(im == size(xyz,3), 'u-xyz shape mismatch for IM')
     _ASSERT(jm == size(xyz,4), 'u-xyz shape mismatch for JM')
     basis_vectors => this%get_basis(basis,rc=status)
     _VERIFY(status)
     do j=1,jm
        do i=1,im
           do k = 1, km
              if (xyz(1,k,i,j) == MAPL_UNDEF .or. xyz(2,k,i,j) == MAPL_UNDEF .or. &
                   xyz(3,k,i,j) == MAPL_UNDEF) then
                 u(i,j,k)=MAPL_UNDEF
                 v(i,j,k)=MAPL_UNDEF
              else
                 uv = matmul(transpose(basis_vectors(:,:,i,j)),xyz(:,k,i,j))
                 u(i,j,k)=uv(1)
                 v(i,j,k)=uv(2)
              end if
           enddo
        enddo
     enddo
     _RETURN(_SUCCESS)
   end subroutine cartesian_to_spherical_3d_real64
Call graph
cartesian_to_spherical_3d_real64 calls mapl_assert, get_basis, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_basis calls mapl_assert, mapl_return, mapl_verify, ESMF_GridGetCoord, computegridbasis, computexyzbasis
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
computegridbasis calls mapl_return, mapl_verify, ESMF_GridGetCoord, mapl_gridgetcorners, get_unit_vector, mapl_gridget, mid_pt_sphere
computexyzbasis calls mapl_return, mapl_verify
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_gridgetcorners calls mapl_gridgetcorners
get_unit_vector calls latlon2xyz
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mid_pt_sphere calls latlon2xyz, xyz2latlon
regrid_vector_2d_real32 calls cartesian_to_spherical
regrid_vector_2d_real64 calls cartesian_to_spherical
regrid_vector_3d_real32 calls cartesian_to_spherical
regrid_vector_3d_real64 calls cartesian_to_spherical
test_cartesian_to_spherical_x calls cartesian_to_spherical
test_cartesian_to_spherical_y calls cartesian_to_spherical
test_cartesian_to_spherical_z calls cartesian_to_spherical
transpose_regrid_vector_2d_real32 calls cartesian_to_spherical
transpose_regrid_vector_3d_real32 calls cartesian_to_spherical