center – MAPL
center Subroutine
22 statements
Source File
private subroutine center(this, rows, space)
Type Bound
TextColumn
Arguments
Type Intent Optional Attributes Name
class(TextColumn), intent(in) :: this
character(len=*), intent(inout) :: rows(:)
character(len=1), intent(in), optional :: space
Calls
Called by
Source Code
   subroutine center(this, rows, space)
      class (TextColumn), intent(in) :: this
      character(*), intent(inout) :: rows(:)
      character(1), optional, intent(in) :: space
      integer :: w, i
      integer :: n, n_0, n_1
      character(:), allocatable :: tmp
      character(1) :: space_
      if (present(space)) then
         space_ = space
      else
         space_ = ' '
      end if
      w = this%get_width()
      do i = 1, size(rows)
         tmp = trim(adjustl(rows(i)))
         n = len(tmp)
         n_0 = (w - n)/2
         n_1 = w - (n + n_0)
         rows(i)(:) = repeat(space_,n_0) // tmp // repeat(space_, n_1)
      end do
   end subroutine center
Call graph
center calls get_width
get_header calls center
generate_report_profiler calls get_header
generate_report calls generate_report
mapl_genericfinalize calls generate_report
report_global_profiler calls generate_report
report_profile calls generate_report
test_simple_report_timer calls generate_report
test_simple_report_timer_b calls generate_report
main calls generate_report