CFIO_parseIntTime – MAPL
CFIO_parseIntTime Subroutine
7 statements
Source File
public subroutine CFIO_parseIntTime(hhmmss, hour, min, sec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: hhmmss
integer, intent(out) :: hour
integer, intent(out) :: min
integer, intent(out) :: sec
Called by
Contents
Source Code
CFIO_parseIntTime
Source Code
      subroutine CFIO_parseIntTime ( hhmmss, hour, min, sec )
         integer, intent(in)  :: hhmmss
         integer, intent(out) :: hour, min, sec
         hour = hhmmss / 10000
         min  = mod(hhmmss,10000)/100
         sec  = mod(hhmmss,100)
      end subroutine CFIO_parseIntTime
Call graph
getbegdatetime calls cfio_parseinttime
esmf_cfiovarreadt3d__ calls cfio_parseinttime, diffdate
esmf_cfiovarreadt2d__ calls cfio_parseinttime, diffdate
getdateint8 calls cfio_parseinttime
diffdate calls cfio_parseinttime
cfio_create_ calls cfio_parseinttime
cfio_putvar calls cfio_parseinttime, diffdate
writebnds calls cfio_parseinttime, diffdate
cfio_sputvar calls cfio_parseinttime, diffdate
esmf_cfiosdfvarwrite3d_ calls cfio_putvar, writebnds
esmf_cfiosdfvarwrite2d_ calls cfio_putvar, writebnds, cfio_sputvar
esmf_cfiosdfvarwrite1d_ calls writebnds, cfio_sputvar
esmf_cfiosdffilecreate calls cfio_create_
esmf_cfiosdffileopen calls getbegdatetime
esmf_cfiosdfvarreadt2d__ calls getbegdatetime, diffdate
esmf_cfiovarreadt2 calls esmf_cfiovarreadt3d__, esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
esmf_cfiosdfvarreadt3d__ calls getbegdatetime, diffdate
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
getdateint4 calls getdateint8
getdate calls getdateint8
cfio_getvar calls diffdate
cfio_sgetvar calls diffdate