CFIO_Close – MAPL
CFIO_Close Subroutine
9 statements
Source File
public subroutine CFIO_Close(fid, rc)
CFIO_Close – Closes file
This routine is used to close an open CFIO stream.
History
1997.10.13 da Silva/Lucchesi Initial interface design.
1998.03.30 Lucchesi Documentation expanded. Clean-up of code. Added rc.
Arguments
Type Intent Optional Attributes Name
integer :: fid
File handle
integer :: rc
Error return code: rc = 0 all is well
NetCDF Errors
rc = -54 error from ncclos (file close)
Calls
Called by
Source Code
      subroutine CFIO_Close ( fid, rc )
!
! !USES:
!
      Implicit NONE
!
! !INPUT PARAMETERS:
!
      integer        fid              !! File handle
!
! !OUTPUT PARAMETERS:
!
      integer     rc     !! Error return code:
                         !!   rc = 0    all is well
                         !!
                         !!  NetCDF Errors
                         !!  -------------
                         !!   rc = -54  error from ncclos (file close)
!
!-------------------------------------------------------------------------
      call ncclos (fid, rc)
      if (err("Close: error closing file",rc,-54) .NE. 0) return
      rc = 0
      return
      end subroutine CFIO_Close
Call graph
cfio_close calls ncclos, err
esmf_cfiodestroy calls cfio_close
esmf_cfiosdffileclose calls cfio_close
esmf_cfiofileclose calls esmf_cfiosdffileclose
esmf_cfiosdfvarread1d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarread2d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarread3d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarwrite1d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarwrite2d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarwrite3d_ calls esmf_cfiosdffileclose
find calls esmf_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy
unfind calls esmf_cfiodestroy