CFIO_Create_ – MAPL
CFIO_Create_ Subroutine
962 statements
Source File
private subroutine CFIO_Create_(cfio, rc)
CFIO_Create_ – Creates a DAO gridded file for writing.
This routine is used to open a new file for a CFIO stream.
!ALT!!!
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
integer :: rc
Error return code: 0 All is well -1 Time increment is 0 -18 incorrect time increment -30 can’t open file -31 error from NF90_DEF_DIM -32 error from NF90_DEF_VAR (dimension variable) -33 error from NF90_PUT_ATT (dimension attribute) -34 error from NF90_DEF_VAR (variable) -35 error from NF90_PUT_ATT (variable attribute) -36 error from NF90_PUT_ATT (global attribute) -37 error from NF90_ENDDEF -38 error from NF90_VAR_PUT (dimension variable) -39 Num of real var elements and Cnt differ -40 error setting deflate compression routine -41 error setting fletcher checksum routine
Calls
Called by
Contents
Source Code
CFIO_Create_
Source Code
      subroutine CFIO_Create_ ( cfio, rc )
!
! !USES:
!
      Implicit NONE
!
! !INPUT PARAMETERS:
!
!
! !OUTPUT PARAMETERS:
!
      integer        fid     !! File handle
      integer        rc      !! Error return code:
                             !! 0  All is well
                             !! -1 Time increment is 0
                             !! -18 incorrect time increment
                             !! -30 can't open file
                             !! -31 error from NF90_DEF_DIM
                             !! -32 error from NF90_DEF_VAR (dimension variable)
                             !! -33 error from NF90_PUT_ATT (dimension attribute)
                             !! -34 error from NF90_DEF_VAR (variable)
                             !! -35  error from NF90_PUT_ATT (variable attribute)
                             !! -36  error from NF90_PUT_ATT (global attribute)
                             !! -37  error from NF90_ENDDEF
                             !! -38  error from NF90_VAR_PUT (dimension variable)
                             !! -39 Num of real var elements and Cnt differ
                             !! -40 error setting deflate compression routine
                             !! -41 error setting fletcher checksum routine
!
! !INPUT/OUTPUT PARAMETERS:
!
     type(ESMF_CFIO), intent(inout) :: cfio
!
!-------------------------------------------------------------------------
      ! REAL(KIND=REAL32) variables for 32-bit output to netCDF file.
      integer :: im, jm, km, tm
      real(kind=REAL64), pointer :: lon_64(:), lat_64(:), levs_64(:)
      real(kind=REAL64), pointer :: lon2_64(:), lat2_64(:)
      character(len=MVARLEN) :: levunits
      integer :: yyyymmdd_beg, hhmmss_beg, timinc
      integer :: nvars
      character(len=MLEN), pointer :: vname(:)
      character(len=MVARLEN), pointer :: vtitle(:)
      character(len=MVARLEN), pointer :: vunits(:)
      integer, pointer :: kmvar(:), station(:)
      real, pointer :: valid_range(:,:), packing_range(:,:)
      integer, pointer :: akid(:), bkid(:), ptopid(:)
      integer, pointer ::  vid(:)
      real(kind=REAL32) amiss_32
      real(kind=REAL32) scale_32, offset_32
      real(kind=REAL32) high_32,low_32
      real(kind=REAL32), pointer :: ak_32(:), bk_32(:), layer(:)
      real(kind=REAL32) :: ptop_32(1)
      integer i, j
      integer timeid, timedim
      integer, pointer :: latid(:), lonid(:), stationid(:)
      integer, pointer :: levid(:), layerid(:)
      integer, pointer :: latdim(:), londim(:), stationdim(:)
      integer, pointer :: faceid(:), facedim(:)
      integer, pointer :: latvid(:), lonvid(:)
      integer, pointer :: latvdim(:), lonvdim(:)
      integer, pointer :: ncontid(:), stringid(:)
      integer, pointer :: ncontdim(:), stringdim(:)
      integer, pointer :: gmid(:), gmdim(:)
      integer, pointer :: levdim(:), layerdim(:)
      integer, pointer :: gDims3D(:,:), gDims2D(:,:)
      integer dims3D(5), dims2D(4), dims1D(1), ptopdim
      integer corner(1), edges(1)
      integer :: corner2d(3), edges2d(3)
      integer :: nsize
      integer, pointer :: lat2id(:), lon2id(:)
!      integer corner(4), edges(4)
      character(len=80) :: timeUnits
      logical surfaceOnly
      integer year,mon,day,hour,minute,sec
      integer count
      integer maxLen
      integer rtcode
      logical :: aveFile = .false.
!      real(kind=REAL32) bndsdata(2)
      integer bndsid, dimsbnd(2), bndsdim
      integer ig
      integer ndim
      character cig
      integer nDefaultChunksize(5) ! Set Chunksize to im,jm,1,1 by default
      logical :: useFaceDim
      integer :: ncont
      integer, allocatable :: ivar(:)
      character(len=5), allocatable :: cvar(:)
      character(len=4) :: verStr
      character(len=80) :: imStr
! Variables for packing
      integer(kind=INT16) amiss_16
      real(kind=REAL32), pointer ::  pRange_32(:,:),vRange_32(:,:)
      logical packflag
! Set metadata strings.  These metadata values are specified in the
! COARDS conventions
      character (len=50), pointer :: lonDimName
      character (len=50), pointer :: latDimName
      character (len=50), target :: lonName = "longitude"
      character (len=50), target :: lon2Name = "Fake Longitude for GrADS Compatibility"
      character (len=50) :: lonUnits = "degrees_east"
      character (len=50), target :: latName = "latitude"
      character (len=50), target :: lat2Name = "Fake Latitude for GrADS Compatibility"
      character (len=50) :: latUnits = "degrees_north"
      character (len=50) :: levName = "vertical level"
!                           levUnits: specified by user in argument list
      character (len=50) :: layerName = "edges"
      character (len=50) :: layerUnits = "layer"
      character (len=50) :: timeName = "time"
!                           timeUnits: string is built below
      character (len=50) :: coordinatesName
      integer :: iCnt
      real(kind=REAL32), pointer :: realVarAtt(:)
      integer, pointer :: intVarAtt(:)
      real(kind=REAL32) :: scale_factor, add_offset
      character (len=50) :: nameLatDim, nameLonDim
      character (len=50) :: nameLat, nameLon, nameLev, nameEdge
      character (len=50) :: nameAk, nameBk, namePtop, nameStation
      logical  bTimeSet
      integer :: sz_lon, sz_lat
      integer :: jm6, nf
      integer :: cid
      integer :: fVersion, xOffset, yOffset, chunkDim
      nvars = cfio%mVars
      yyyymmdd_beg = cfio%date
      hhmmss_beg = cfio%begTime
      timinc = cfio%timeInc
      allocate(vname(nvars), vtitle(nvars), vunits(nvars), kmvar(nvars), &
            valid_range(2,nvars), packing_range(2,nvars), vid(nvars),    &
            vRange_32(2,nvars), pRange_32(2,nvars), stat = rtcode)
      allocate(latid(cfio%mGrids), lonid(cfio%mGrids),                   &
               lat2id(cfio%mGrids), lon2id(cfio%mGrids),                 &
               levid(cfio%mGrids), layerid(cfio%mGrids),                 &
               latdim(cfio%mGrids), londim(cfio%mGrids),                 &
               levdim(cfio%mGrids), layerdim(cfio%mGrids),               &
               akid(cfio%mGrids),bkid(cfio%mGrids),ptopid(cfio%mGrids),  &
               gDims3D(5,cfio%mGrids), gDims2D(4,cfio%mGrids),           &
               stationdim(cfio%mGrids), stationid(cfio%mGrids),          &
               faceid(cfio%mGrids), facedim(cfio%mGrids),                &
               lonvid(cfio%mGrids), lonvdim(cfio%mGrids),                &
               latvid(cfio%mGrids), latvdim(cfio%mGrids),                &
               ncontid(cfio%mGrids), ncontdim(cfio%mGrids),              &
               stringid(cfio%mGrids), stringdim(cfio%mGrids),            &
               gmid(cfio%mGrids), gmdim(cfio%mGrids))
      do i=1,nvars
         vname(i) = cfio%varObjs(i)%vName
         vtitle(i) = cfio%varObjs(i)%vTitle
         vunits(i) = cfio%varObjs(i)%vUnits
         kmvar(i) = cfio%varObjs(i)%grid%km
         if ( cfio%varObjs(i)%twoDimVar ) kmvar(i) = 0
         valid_range(1, i) = cfio%varObjs(i)%validRange(1)
         valid_range(2, i) = cfio%varObjs(i)%validRange(2)
         packing_range(1, i) = cfio%varObjs(i)%packingRange(1)
         packing_range(2, i) = cfio%varObjs(i)%packingRange(2)
         if ( cfio%varObjs(i)%timAve ) then
            aveFile = .true.
         end if
      enddo
      do j=1,nvars
        do i=1,2
           vRange_32(i,j) = valid_range(i,j)
           pRange_32(i,j) = packing_range(i,j)
        enddo
      enddo
      amiss_32 = cfio%varObjs(1)%amiss
      amiss_16 = PACK_FILL
! Variable initialization
      surfaceOnly = .TRUE.
      nf = 1
      useFaceDim = .false.
      if (cfio%formatVersion > 2.0) then
         useFaceDim = .true.
         nf = 6
         ncont = 4
      end if
! Basic error-checking.
      if (timinc .eq. 0) then
        rc=-1
        return
      endif
! Check to see if there is only surface data in this file definition
      do i=1,nvars
        if (kmvar(i) .NE. 0) then
          surfaceOnly = .FALSE.
          exit
        endif
      enddo
! Create the new NetCDF file. [ Enter define mode. ]
      if (isFileExtensionNetCDF4(trim(cfio%fName))) then
         rc = nf90_create (trim(cfio%fName), IOR(NF90_CLOBBER,NF90_NETCDF4), fid)
      else
         rc = nf90_create (trim(cfio%fName), IOR(IOR(NF90_CLOBBER,NF90_NETCDF4),NF90_CLASSIC_MODEL), fid) !NETCDF4/HDF5
      end if
      if (err("Create: can't create file",rc,-30) .LT. 0) return
!     Time Variable is defaulted to UNLIMITED
      bTimeSet = .FALSE.
      tm = 0
! Convert double-precision output variables to single-precision
   do ig = 1, cfio%mGrids
      im = cfio%grids(ig)%im
      jm = cfio%grids(ig)%jm
      km = cfio%grids(ig)%km
      tm = max(tm,cfio%grids(ig)%tm)
      if ( index(cfio%grids(ig)%gName, 'station') .gt. &
           0 ) then
         if (im .ne. jm) rtcode = err("It isn't station grid",-1,-1)
      end if
      levunits = trim(cfio%grids(ig)%levUnits)
      allocate(station(im))
      do i=1,im
         station(i) = i
      enddo
! Define dimensions.
      lonDimName => lonName
      latDimName => latName
      if (cfio%grids(ig)%twoDimLat) then
         nameLonDim = 'lons'
         nameLatDim = 'lats'
         coordinatesName = trim(nameLonDim) // ' ' // trim(nameLatDim)
         lonDimName => lon2Name
         latDimName => lat2Name
      endif
      if ( ig .eq. 1 ) then
         if (cfio%mGrids .eq. 1) then
            if (cfio%grids(ig)%twoDimLat) then
               nameLon = 'Xdim'
               nameLat = 'Ydim'
            else
               nameLon = 'lon'
               nameLat = 'lat'
            end if
            nameLev = 'lev'
            nameEdge = 'edges'
            nameStation = 'station'
         else
            nameLon = 'lon0'
            nameLat = 'lat0'
            nameLev = 'lev0'
            nameEdge = 'edges0'
            nameStation = 'station0'
         end if
      else
        write (cig,"(I1)") ig-1
        nameLon = 'lon'//cig
        nameLat = 'lat'//cig
        nameLev = 'lev'//cig
        nameEdge = 'edges'//cig
        nameStation = 'station'//cig
      end if
      if (index(cfio%grids(ig)%gName,'station') .gt. 0) then
         rc = NF90_DEF_DIM(fid, nameStation, im, stationdim(ig))
         if (err("Create: error defining station",rc,-31) .LT. 0) return
      else
         if (cfio%formatVersion > 2.0) then
            rc = NF90_DEF_DIM(fid, nameLon, im, londim(ig))
            if (err("Create: error defining x",rc,-31) .LT. 0) return
            jm6 = jm/nf
            rc = NF90_DEF_DIM(fid, nameLat, jm6, latdim(ig))
            if (err("Create: error defining y",rc,-31) .LT. 0) return
            rc = NF90_DEF_DIM(fid, 'nf', nf, facedim(ig))
            if (err("Create: error defining nf",rc,-31) .LT. 0) return
            if (cfio%useVertexCoordinates) then
               rc = NF90_DEF_DIM(fid, 'xv', im+1, lonvdim(ig))
               if (err("Create: error defining xv",rc,-31) .LT. 0) return
               rc = NF90_DEF_DIM(fid, 'yv', jm6+1, latvdim(ig))
               if (err("Create: error defining yv",rc,-31) .LT. 0) return
            end if
         else
            rc = NF90_DEF_DIM(fid, nameLon, im, londim(ig))
            if (err("Create: error defining lon",rc,-31) .LT. 0) return
            rc = NF90_DEF_DIM(fid, nameLat, jm, latdim(ig))
            if (err("Create: error defining lat",rc,-31) .LT. 0) return
         end if
      end if
      if (.NOT. surfaceOnly) then
        rc = NF90_DEF_DIM(fid, nameLev,km,levdim(ig))
        if (err("Create: error defining lev",rc,-31) .LT. 0) return
      endif
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_hybrid_sigma_pressure_coordinate' ) then
         rc = NF90_DEF_DIM(fid, nameEdge, km+1, layerdim(ig))
         if (err("Create: error defining edges",rc,-31) .LT. 0) return
      endif
! Define dimension variables.
      if (index(cfio%grids(ig)%gName,'station') .gt. 0) then
         rc = NF90_DEF_VAR (fid, nameLon, NF90_DOUBLE, stationdim(ig), lonid(ig))
         if (err("Create: error creating lon",rc,-32) .LT. 0) return
         rc = NF90_DEF_VAR (fid, nameLat, NF90_DOUBLE, stationdim(ig), latid(ig))
         if (err("Create: error creating lat",rc,-32) .LT. 0) return
      else
         if (cfio%formatVersion > 2.0) then
            rc = NF90_DEF_DIM(fid, 'ncontact', ncont, ncontdim(ig))
            if (err("Create: error defining ncontact",rc,-31) .LT. 0) return
            rc = NF90_DEF_DIM(fid, 'orientationStrLen', 5, stringdim(ig))
            if (err("Create: error defining orientationStrLen",rc,-31) .LT. 0) return
            rc = NF90_DEF_VAR (fid, 'nf', NF90_INT, facedim(ig), faceid(ig))
            if (err("Create: error creating nf",rc,-32) .LT. 0) return
            if (cfio%useVertexCoordinates) then
               rc = NF90_DEF_VAR (fid, 'xv', NF90_DOUBLE, lonvdim(ig), lonvid(ig))
               if (err("Create: error creating xv",rc,-32) .LT. 0) return
               rc = NF90_DEF_VAR (fid, 'yv', NF90_DOUBLE, latvdim(ig), latvid(ig))
               if (err("Create: error creating yv",rc,-32) .LT. 0) return
            end if
            rc = NF90_DEF_VAR (fid, 'ncontact', NF90_INT, ncontdim(ig), ncontid(ig))
            if (err("Create: error creating ncontact",rc,-32) .LT. 0) return
!            rc = NF90_DEF_VAR (fid, 'string', NF90_INT, stringdim(ig), stringid(ig))
!            if (err("Create: error creating string",rc,-32) .LT. 0) return
            rc = NF90_DEF_VAR (fid, 'cubed_sphere', NF90_CHAR, gmid(ig))
            if (err("Create: error creating cubed_sphere",rc,-32) .LT. 0) return
         end if ! new format
         rc = NF90_DEF_VAR (fid, nameLon, NF90_DOUBLE, londim(ig), lonid(ig))
         if (err("Create: error creating lon",rc,-32) .LT. 0) return
         rc = NF90_DEF_VAR (fid, nameLat, NF90_DOUBLE, latdim(ig), latid(ig))
         if (err("Create: error creating lat",rc,-32) .LT. 0) return
         if (cfio%formatVersion > 2.0) then
            dims2D(3) = facedim(ig)
            dims2D(2) = latdim(ig)
            dims2D(1) = londim(ig)
            rc = NF90_DEF_VAR (fid, nameLonDim, NF90_DOUBLE, dims2D(1:3), lon2id(ig))
            if (err("Create: error creating lons",rc,-32) .LT. 0) return
            rc = NF90_DEF_VAR (fid, nameLatDim, NF90_DOUBLE, dims2D(1:3), lat2id(ig))
            if (err("Create: error creating lats",rc,-32) .LT. 0) return
            ! contacts
            dims2D(2) = facedim(ig)
            dims2D(1) = ncontdim(ig)
            rc = NF90_DEF_VAR (fid, 'contacts', NF90_INT, dims2D(1:2), cid)
            if (err("Create: error creating contacts",rc,-32) .LT. 0) return
            rc = NF90_PUT_ATT(fid,cid,'long_name','adjacent face starting from left side going clockwise' )
            if (err("Create: error creating contacts attribute",rc,-33) .LT. 0) &
                 return
            ! fill contact values
            nsize=2
            corner2d = 1
            edges2d = 1
            edges2d(1) = ncont
            edges2d(2) = nf
            allocate(ivar(nf*ncont), stat=rtcode)
            ivar = (/5, 3, 2, 6, &
                     1, 3, 4, 6, &
                     1, 5, 4, 2, &
                     3, 5, 6, 2, &
                     3, 1, 6, 4, &
                     5, 1, 2, 4 /)
            rc = NF90_PUT_VAR(fid, cid, ivar,corner2d(1:nsize), edges2d(1:nsize))
            if (err("Create: error writing contacts",rc,-38) .LT. 0) return
            deallocate(ivar)
            ! orientation
            dims2D(1) = stringdim(ig)
            dims2D(2) = ncontdim(ig)
            dims2D(3) = facedim(ig)
            rc = NF90_DEF_VAR (fid, 'orientation', NF90_CHAR, dims2D(1:3), cid)
            if (err("Create: error creating orientation",rc,-32) .LT. 0) return
            rc = NF90_PUT_ATT(fid,cid,'long_name','orientation of boundary' )
            if (err("Create: error creating orientation attribute",rc,-33) .LT. 0) &
                 return
            ! fill orientation values
            nsize=3
            corner2d = 1
            edges2d = 1
            edges2d(1) = 5
            edges2d(2) = ncont
            edges2d(3) = nf
            allocate(cvar(nf*ncont), stat=rtcode)
            cvar = (/" Y:-X", &
                     " X:-Y", &
                     " Y:Y ", &
                     " X:X ", &
                     " Y:Y ", &
                     " X:X ", &
                     " Y:-X", &
                     " X:-Y", &
                     " Y:-X", &
                     " X:-Y", &
                     " Y:Y ", &
                     " X:X ", &
                     " Y:Y ", &
                     " X:X ", &
                     " Y:-X", &
                     " X:-Y", &
                     " Y:-X", &
                     " X:-Y", &
                     " Y:Y ", &
                     " X:X ", &
                     " Y:Y ", &
                     " X:X ", &
                     " Y:-X", &
                     " X:-Y" /)
            rc = NF90_PUT_VAR(fid, cid, cvar,corner2d(1:nsize), edges2d(1:nsize))
            if (err("Create: error writing orientation",rc,-38) .LT. 0) return
            deallocate(cvar)
            ! anchor
            nsize=3
            dims2D(1) = ncontdim(ig)
            dims2D(2) = ncontdim(ig)
            dims2D(3) = facedim(ig)
            rc = NF90_DEF_VAR (fid, 'anchor', NF90_INT, dims2D(1:nsize), cid)
            if (err("Create: error creating anchor",rc,-32) .LT. 0) return
            rc = NF90_PUT_ATT(fid,cid,'long_name','anchor point' )
            if (err("Create: error creating contacts attribute",rc,-33) .LT. 0) &
                 return
            ! fill anchor values
            corner2d = 1
            edges2d = 1
            edges2d(1) = ncont
            edges2d(2) = ncont
            edges2d(3) = nf
            allocate(ivar(nf*ncont*ncont), stat=rtcode)
            ivar = (/ & !FACE 1
                 im, im,  1, im, &
                  1, im,  1,  1, &
                  1, im,  1,  1, &
                 im, im,  1, im, &
                 !FACE 2
                 im,  1, im, im, &
                  1,  1, im,  1, &
                  1,  1, im,  1, &
                 im,  1, im,  im, &
                 !FACE 3
                 im, im,  1, im, &
                  1, im,  1,  1, &
                  1, im,  1,  1, &
                 im, im,  1, im, &
                 !FACE 4
                 im,  1, im, im, &
                  1,  1, im,  1, &
                  1,  1, im,  1, &
                 im,  1, im, im, &
                 !FACE 5
                 im, im,  1, im, &
                  1, im,  1,  1, &
                  1, im,  1,  1, &
                 im, im,  1, im, &
                 !FACE 6
                 im,  1, im, im, &
                  1,  1, im,  1, &
                  1,  1, im,  1, &
                 im,  1, im, im  /)
            rc = NF90_PUT_VAR(fid, cid, ivar,corner2d(1:nsize), edges2d(1:nsize))
            if (err("Create: error writing anchor",rc,-38) .LT. 0) return
            deallocate(ivar)
         else
         if (cfio%grids(ig)%twoDimLat) then
            dims2D(2) = latdim(ig)
            dims2D(1) = londim(ig)
            rc = NF90_DEF_VAR (fid, nameLonDim, NF90_DOUBLE, dims2D(1:2), lon2id(ig))
               if (err("Create: error creating lons",rc,-32) .LT. 0) return
            rc = NF90_DEF_VAR (fid, nameLatDim, NF90_DOUBLE, dims2D(1:2), lat2id(ig))
               if (err("Create: error creating lats",rc,-32) .LT. 0) return
            end if
         end if
      end if
      if (.NOT. surfaceOnly) then
        rc = NF90_DEF_VAR (fid, nameLev, NF90_DOUBLE, levdim(ig), levid(ig))
        if (err("Create: error creating lev",rc,-32) .LT. 0) return
      endif
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_hybrid_sigma_pressure_coordinate' ) then
         rc = NF90_DEF_VAR (fid, nameEdge, NF90_DOUBLE, layerdim(ig), layerid(ig))
         if (err("Create: error creating edges",rc,-32) .LT. 0) return
      endif
! Set attributes for dimensions.
         if (cfio%formatVersion > 2.0) then
            rc = NF90_PUT_ATT(fid,faceid(ig),'long_name','cubed-sphere face' )
            if (err("Create: error creating nf attribute",rc,-33) .LT. 0) &
                 return
            rc = NF90_PUT_ATT(fid,faceid(ig),'axis','e')
            if (err("Create: error creating nf attribute",rc,-33) .LT. 0) &
                 return
            rc = NF90_PUT_ATT(fid,faceid(ig),'grads_dim','e')
            if (err("Create: error creating nf attribute",rc,-33) .LT. 0) &
                 return
            rc = NF90_PUT_ATT(fid,lonvid(ig),'long_name','number of vertices along the x-edge' )
            if (cfio%useVertexCoordinates) then
               if (err("Create: error creating xv attribute",rc,-33) .LT. 0) &
                    return
               rc = NF90_PUT_ATT(fid,latvid(ig),'long_name','number of vertices along the y-edge' )
               if (err("Create: error creating yv attribute",rc,-33) .LT. 0) &
                    return
            end if
            rc = NF90_PUT_ATT(fid,ncontid(ig),'long_name','number of contact points' )
            if (err("Create: error creating ncontact attribute",rc,-33) .LT. 0) &
                 return
!            rc = NF90_PUT_ATT(fid,stringid(ig),'long_name','string length')
!            if (err("Create: error creating string attribute",rc,-33) .LT. 0) &
!                 return
            rc = NF90_PUT_ATT(fid,gmid(ig),'grid_mapping_name','gnomonic cubed-sphere' )
            if (err("Create: error creating cubed_sphere attribute",rc,-33) .LT. 0) &
                 return
            write(verStr,'(f4.2)') cfio%formatVersion
            rc = NF90_PUT_ATT(fid,gmid(ig),'file_format_version',verStr )
            if (err("Create: error creating cubed_sphere attribute",rc,-33) .LT. 0) &
              return
            rc = NF90_PUT_ATT(fid,gmid(ig),'additional_vars','contacts,orientation,anchor' )
            if (err("Create: error creating cubed_sphere attribute",rc,-33) .LT. 0) &
              return
            write(imStr,*) cfio%grids(ig)%im
            rc = NF90_PUT_ATT(fid,gmid(ig),'gridspec_file',&
                 'C'//trim(adjustl(imStr))//'_gridspec.nc4')
            if (err("Create: error creating cubed_sphere attribute",rc,-33) .LT. 0) &
              return
      end if
!ALT      if (cfio%grids(ig)%twoDimLat) then
!ALT         rc = NF90_PUT_ATT(fid,lonid(ig),'axis','lons')
!ALT         if (err("Create: error creating lon attribute",rc,-33) .LT. 0) &
!ALT              return
!ALT      end if
      rc = NF90_PUT_ATT(fid,lonid(ig),'long_name',lonDimName)
      if (err("Create: error creating lon attribute",rc,-33) .LT. 0) &
        return
      if (cfio%grids(ig)%twoDimLat) then
         rc = NF90_PUT_ATT(fid,lonid(ig),'units','degrees_east')
      else
         rc = NF90_PUT_ATT(fid,lonid(ig),'units',lonUnits)
      end if
      if (err("Create: error creating lon attribute",rc,-33) .LT. 0)  &
        return
!ALT      if (cfio%grids(ig)%twoDimLat) then
!ALT         rc = NF90_PUT_ATT(fid,latid(ig),'axis','lats')
!ALT         if (err("Create: error creating lat attribute",rc,-33) .LT. 0) &
!ALT              return
!ALT      end if
      rc = NF90_PUT_ATT(fid,latid(ig),'long_name',latDimName)
      if (err("Create: error creating lat attribute",rc,-33) .LT. 0) &
        return
      if (cfio%grids(ig)%twoDimLat) then
         rc = NF90_PUT_ATT(fid,latid(ig),'units','degrees_north')
      else
         rc = NF90_PUT_ATT(fid,latid(ig),'units',latUnits)
      end if
      if (err("Create: error creating lat attribute",rc,-33) .LT. 0) &
           return
      if (cfio%grids(ig)%twoDimLat) then
         rc = NF90_PUT_ATT(fid,lon2id(ig),'long_name',lonName)
         if (err("Create: error creating lon2 attribute",rc,-33) .LT. 0) &
              return
         rc = NF90_PUT_ATT(fid,lon2id(ig),'units',lonUnits)
         if (err("Create: error creating lon2 attribute",rc,-33) .LT. 0)  &
              return
         rc = NF90_PUT_ATT(fid,lat2id(ig),'long_name',latName)
         if (err("Create: error creating lat2 attribute",rc,-33) .LT. 0) &
              return
         rc = NF90_PUT_ATT(fid,lat2id(ig),'units',latUnits)
         if (err("Create: error creating lat2 attribute",rc,-33) .LT. 0) &
              return
      end if
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_hybrid_sigma_pressure_coordinate' ) then
         rc = NF90_PUT_ATT(fid,layerid(ig),'long_name',layerName)
         if (err("Create: error creating layer attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_PUT_ATT(fid,layerid(ig),'units',layerUnits)
         if (err("Create: error creating layer attribute",rc,-33) .LT. 0)&
           return
      endif
      if (.NOT. surfaceOnly) then
        rc = NF90_PUT_ATT(fid,levid(ig),'long_name',levName)
        if (err("Create: error creating lev attribute",rc,-33) .LT. 0)&
           return
        rc = NF90_PUT_ATT(fid,levid(ig),'units',levunits)
        if (err("Create: error creating lev attribute",rc,-33) .LT. 0)&
           return
        rc = NF90_PUT_ATT(fid,levid(ig),'positive','down')
        if (err("Create: error creating lev attribute",rc,-33) .LT. 0)&
           return
        rc = NF90_PUT_ATT(fid,levid(ig),'coordinate', &
               cfio%grids(ig)%coordinate)
        if (err("Create: error creating lev attribute",rc,-33) .LT. 0)&
           return
        rc = NF90_PUT_ATT(fid,levid(ig),'standard_name', &
             cfio%grids(ig)%standardName)
        if (err("Create: error creating lev attribute",rc,-33) .LT. 0)&
           return
        if ( len(cfio%grids(ig)%formulaTerm) .gt. 0 .and. &
             trim(cfio%grids(ig)%formulaTerm) .ne. 'unknown') then
           rc = NF90_PUT_ATT(fid,levid(ig),'formula_term', &
              cfio%grids(ig)%formulaTerm)
           if (err("Create: error creating lev attribute",rc,-33) .LT. 0)&
           return
        end if
      endif
! end of mGrid loop
  end do
      if( tm .LE. 0 ) then
         rc = NF90_DEF_DIM(fid, 'time', NF90_UNLIMITED, timedim)
      else
         rc = NF90_DEF_DIM(fid, 'time', tm, timedim)
         bTimeSet = .TRUE.
      endif
      if (err("Create: error defining time",rc,-31) .LT. 0) return
      if ( aveFile ) then
         rc = NF90_DEF_DIM(fid, 'nv', 2, bndsdim)
         if (err("Create: error defining time bounds",rc,-31) .LT. 0)&
              return
      end if
      do ig =1, cfio%mGrids
        if ( trim(cfio%grids(ig)%standardName) .eq.           &
           'atmosphere_hybrid_sigma_pressure_coordinate' .or. &
             trim(cfio%grids(ig)%standardName) .eq.           &
           'atmosphere_sigma_coordinate' ) then
            if (ig .eq. 1) then
              if (cfio%mGrids .eq. 1) then
                 rc = NF90_DEF_DIM(fid, "ptop", 1, ptopdim)
              else
                 rc = NF90_DEF_DIM(fid, "ptop0", 1, ptopdim)
              end if
            end if
        endif
      end do
      rc = NF90_DEF_VAR (fid, 'time', NF90_INT, timedim, timeid)
      if (err("Create: error creating time",rc,-32) .LT. 0) return
      rc = NF90_PUT_ATT(fid,timeid,'long_name',timeName)
      if (err("Create: error creating time attribute",rc,-33) .LT. 0)&
        return
!ams       write (dateString,200) yyyymmdd_beg, hhmmss_beg
!ams 200   format (I8,I6)
!ams       read (dateString,201) year,mon,day,hour,minute,sec
!ams 201   format (I4,5I2)
      call CFIO_parseIntTime ( yyyymmdd_beg, year, mon, day )
      call CFIO_parseIntTime ( hhmmss_beg, hour,minute,sec )
      write (timeUnits,202) year,mon,day,hour,minute,sec
202   format ('minutes since ',I4.4,'-',I2.2,'-',I2.2,' ',I2.2,':', &
              I2.2,':',I2.2)
      rc = NF90_PUT_ATT(fid,timeid,'units',timeUnits)
      if (err("Create: error creating time attribute",rc,-33) .LT. 0) &
        return
!ams       write (strBuf,203) timinc
!ams 203   format (I6)
!ams       read (strBuf,204) hour, minute, sec
!ams 204   format (3I2)
      call CFIO_parseIntTime ( timinc, hour, minute, sec )
      if ( sec .NE. 0) then
        print *, 'CFIO_Create: Time increments not on minute', &
                ' boundaries are not currently allowed.'
        rc = -18
        return
      endif
      rc = NF90_PUT_ATT(fid,timeid,'time_increment',timInc)
      if (err("Create: error creating time attribute",rc,-33) .LT. 0) &
        return
      rc = NF90_PUT_ATT(fid,timeid,'begin_date',yyyymmdd_beg)
      if (err("Create: error creating time attribute",rc,-33) .LT. 0) &
        return
      rc = NF90_PUT_ATT(fid,timeid,'begin_time',hhmmss_beg)
      if (err("Create: error creating time attribute",rc,-33) .LT. 0) &
        return
      if ( aveFile ) then
         rc = NF90_PUT_ATT(fid,timeid,'bounds','time_bnds')
         if (err("Create: error creating time attribute",rc,-33) .LT. 0) &
             return
      end if
  do ig = 1, cfio%mGrids
      im = cfio%grids(ig)%im
      jm = cfio%grids(ig)%jm
      km = cfio%grids(ig)%km
      tm = max(tm,cfio%grids(ig)%tm)
      if ( index(cfio%grids(ig)%gName, 'station') .gt. &
           0 ) then
         if (im .ne. jm) rtcode = err("It isn't station grid",-1,-1)
      end if
      gDims3D(5,ig) = 0
      gDims3D(4,ig) = timedim
      gDims3D(3,ig) = levdim(ig)
      gDims3D(2,ig) = latdim(ig)
      gDims3D(1,ig) = londim(ig)
      gDims2D(4,ig) = 0
      gDims2D(3,ig) = timedim
      gDims2D(2,ig) = latdim(ig)
      gDims2D(1,ig) = londim(ig)
      if (index(cfio%grids(ig)%gName,'station') .gt. 0) then
         gDims3D(4,ig) = 0
         gDims3D(3,ig) = timedim
         gDims3D(2,ig) = levdim(ig)
         gDims3D(1,ig) = stationdim(ig)
         gDims2D(3,ig) = 0
         gDims2D(2,ig) = timedim
         gDims2D(1,ig) = stationdim(ig)
      end if
      if (useFaceDim) then
         gDims3D(5,ig) = timedim
         gDims3D(4,ig) = levdim(ig)
         gDims3D(3,ig) = facedim(ig)
         gDims3D(2,ig) = latdim(ig)
         gDims3D(1,ig) = londim(ig)
         gDims2D(4,ig) = timedim
         gDims2D(3,ig) = facedim(ig)
         gDims2D(2,ig) = latdim(ig)
         gDims2D(1,ig) = londim(ig)
      end if
      if ( ig .eq. 1 ) then
         if (cfio%mGrids .eq. 1) then
           nameAk = 'ak'
           nameBk = 'bk'
           namePtop = 'ptop'
         else
           nameAk = 'ak0'
           nameBk = 'bk0'
           namePtop = 'ptop0'
         end if
      else
        write (cig,"(I1)") ig-1
        nameAk = 'ak'//cig
        nameBk = 'bk'//cig
        namePtop = 'ptop'//cig
      end if
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_hybrid_sigma_pressure_coordinate' ) then
         dims1D = layerdim(ig)
         rc = NF90_DEF_VAR (fid, nameAk, NF90_FLOAT, dims1D, akid(ig))
         rc = NF90_PUT_ATT(fid,akid(ig),'long_name',&
                     'ak component of hybrid coordinate')
         if (err("Create: error creating ak attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_PUT_ATT(fid,akid(ig),'units','dimensionless')
         if (err("Create: error creating ak attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_DEF_VAR (fid, nameBk, NF90_FLOAT, dims1D, bkid(ig))
         rc = NF90_PUT_ATT(fid,bkid(ig),'long_name',&
                     'bk component of hybrid coordinate')
         if (err("Create: error creating bk attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_PUT_ATT(fid,bkid(ig),'units','dimensionless')
         if (err("Create: error creating bk attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_DEF_VAR (fid, namePtop, NF90_FLOAT, ptopdim, ptopid(ig))
         if (err("Create: error define ptopid",rc,-34) .LT. 0) return
         rc = NF90_PUT_ATT(fid,ptopid(ig),'long_name',&
                     'ptop component of hybrid coordinate')
         if (err("Create: error creating ptop attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_PUT_ATT(fid,ptopid(ig),'units',     &
                     trim(cfio%grids(ig)%ptopUnit))
         if (err("Create: error creating ptop attribute",rc,-33) .LT. 0)&
            return
      end if
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_sigma_coordinate' ) then
         rc = NF90_DEF_VAR (fid, namePtop, NF90_FLOAT, ptopdim, ptopid(ig))
         if (err("Create: error define ptopid",rc,-34) .LT. 0) return
         rc = NF90_PUT_ATT(fid,ptopid(ig),'long_name',&
                     'ptop component of sigma coordinate')
         if (err("Create: error creating ptop attribute",rc,-33) .LT. 0)&
            return
         rc = NF90_PUT_ATT(fid,ptopid(ig),'units',    &
                     trim(cfio%grids(ig)%ptopUnit))
         if (err("Create: error creating ptop attribute",rc,-33) .LT. 0)&
            return
      end if
! end of mGrids loop
  end do
      scale_32 = 1.0     ! No packing for now.
      offset_32 = 0.0    ! No packing for now.
! Set up packing attributes for each variable.
! Define physical variables.  Set attributes for physical variables.
      do i=1,nvars
        scale_32 = 1.0                        ! default to no packing.
        offset_32 = 0.0
        if (pRange_32(1,i) .NE. amiss_32 .OR. pRange_32(2,i) .NE.  &
       amiss_32) then
          if (pRange_32(1,i) .GT. pRange_32(2,i)) then
            high_32 = pRange_32(1,i)
            low_32  = pRange_32(2,i)
          else
            high_32 = pRange_32(2,i)
            low_32  = pRange_32(1,i)
          endif
          scale_32 = (high_32 - low_32)/PACK_BITS*2
          offset_32 = high_32 - scale_32*PACK_BITS
          if (scale_32 .EQ. 0.0) then              ! If packing range is 0,
             scale_32 = 1.0                        ! no packing.
             offset_32 = 0.0
             packflag = .FALSE.
          else
             packflag = .TRUE.
          endif
        else
          packflag = .FALSE.
        endif
        do ig = 1, cfio%mGrids
           if (trim(cfio%varObjs(i)%grid%gName) .eq.              &
               trim(cfio%grids(ig)%gName)) then
              dims3D = gDims3D(:,ig)
              dims2D = gDims2D(:,ig)
           end if
        end do
        if ( kmvar(i) .eq. 0 ) then
          ndim = 3
          if (index(cfio%varObjs(i)%grid%gName,'station') .gt. 0) ndim = 2
          if (useFaceDim) ndim = ndim + 1
          if (packflag) then
            rc = NF90_DEF_VAR (fid, vname(i), NF90_SHORT, dims2D(1:ndim), vid(i))
          else if (cfio%prec .EQ. 1) then
            rc = NF90_DEF_VAR (fid, vname(i), NF90_DOUBLE, dims2D(1:ndim), vid(i))
          else
            rc = NF90_DEF_VAR (fid, vname(i), NF90_FLOAT, dims2D(1:ndim), vid(i))
          endif
        else
          ndim = 4
          if (index(cfio%varObjs(i)%grid%gName,'station') .gt. 0) ndim = 3
          if (useFaceDim) ndim = ndim + 1
          if (packflag) then
            rc = NF90_DEF_VAR (fid, vname(i), NF90_SHORT, dims3D(1:ndim), vid(i))
          else if (cfio%prec .EQ. 1) then
            rc = NF90_DEF_VAR (fid, vname(i), NF90_DOUBLE, dims3D(1:ndim), vid(i))
          else
            rc = NF90_DEF_VAR (fid, vname(i), NF90_FLOAT, dims3D(1:ndim), vid(i))
          endif
        endif
        if (err("Create: error defining variable",rc,-34) .LT. 0)  &
         return
!#if defined(HAS_NETCDF4)
!
! Chunksize is set to IM,JM,1,1 works for 2D and 3D variables
!
        if ( (associated(cfio%varObjs(i)%ChunkSize)) ) then
           rc=NF90_DEF_VAR_CHUNKING(fid, vid(i), &
                NF90_CHUNKED, cfio%varObjs(i)%ChunkSize)
           if (err("Create: error setting Chunked variable",rc,-40) .LT. 0) &
           return
        else
!
! Set Chunsize to IM,JM,1,1 by default
! If Time (tm) has been set in grid, set the file to contiguous
!
           if( bTimeSet .eqv. .FALSE. ) then
              if (useFaceDim) then
                 chunkDim=5
                 nDefaultChunkSize(2)=jm/nf !!!ALT!!!
              else
                 chunkDim=4
                 nDefaultChunkSize(2)=jm
              end if
              nDefaultChunkSize(1)=im
              nDefaultChunkSize(3)=1 !nf
              nDefaultChunkSize(4)=1
              nDefaultChunkSize(5)=1
              rc=NF90_DEF_VAR_CHUNKING(fid, vid(i), NF90_CHUNKED,  &
                   nDefaultChunkSize(1:chunkDim))
           endif
        end if
!
! Handle deflation
!
        if (cfio%deflate > 0 .and. cfio%deflate <= 9) then
           rc = NF90_DEF_VAR_deflate(fid, vid(i), 1, 1, cfio%deflate)
           if (err("Create: error setting deflate filter",rc,-40) .LT. 0) return
        end if
! enable error checking
!        rc = NF90_DEF_VAR_fletcher32(fid, vid(i), 1)
!        if (err("Create: error setting fletcher",rc,-41) .LT. 0) return
!#endif
        rc = NF90_PUT_ATT(fid, vid(i), 'long_name',vtitle(i))
        if (err("Create: error defining long_name attribute",rc,-35) &
          .LT. 0) return
        rc = NF90_PUT_ATT(fid, vid(i), 'units',vunits(i))
        if (err("Create: error defining units attribute",rc,-35) &
          .LT. 0) return
        if (packflag) then
          rc = NF90_PUT_ATT(fid,vid(i),'_FillValue',amiss_32)
          if (err("Create: error defining FillValue attribute",rc,-35) &
          .LT. 0) return
          if ( scale_32 .ne. 1.0 .or. offset_32 .ne. 0.0 ) then
          rc = NF90_PUT_ATT(fid,vid(i),'scale_factor',scale_32)
          if (err("Create: error defining scale_factor attribute",rc,-35) &
              .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'add_offset',offset_32)
          if (err("Create: error defining add_offset attribute",rc,-35) &
              .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'packmin',low_32)
          if (err("Create: error defining packmin attribute",rc,-35)  &
             .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'packmax',high_32)
          if (err("Create: error defining packmax attribute",rc,-35) &
             .LT. 0) return
          end if
          rc = NF90_PUT_ATT(fid,vid(i),'missing_value',amiss_16)
          if (err("Create: error defining missing_value attribute",rc,-35) &
          .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'fmissing_value',amiss_32)
          if (err("Create: error defining fmissing_value attribute",rc,-35) &
          .LT. 0) return
        else
          rc = NF90_PUT_ATT(fid,vid(i),'_FillValue',amiss_32)
          if (err("Create: error defining FillValue attribute",rc,-35) &
          .LT. 0) return
          if ( scale_32 .ne. 1.0 .or. offset_32 .ne. 0.0 ) then
          rc = NF90_PUT_ATT(fid,vid(i),'scale_factor',scale_32)
          if (err("Create: error defining scale_factor attribute",rc,-35) &
              .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'add_offset',offset_32)
          if (err("Create: error defining add_offset attribute",rc,-35) &
              .LT. 0) return
          end if
          rc = NF90_PUT_ATT(fid,vid(i),'missing_value',amiss_32)
          if (err("Create: error defining missing_value attribute",rc,-35) &
          .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'fmissing_value',amiss_32)
          if (err("Create: error defining fmissing_value attribute",rc,-35) &
          .LT. 0) return
! ADDED BY BYIN for more variable meta data
         cfio%fid = fid
!        get real variable attributes from rList
         do iCnt = 1, cfio%mVars
            if ( associated(cfio%varObjs(i)%rList) ) then
               call getMaxLenCnt(maxLen, cfio%varObjs(i)%nVarAttReal, &
                                 rList=cfio%varObjs(i)%rList)
               count = cfio%varObjs(i)%nVarAttReal
               allocate(cfio%varObjs(i)%attRealNames(count),     &
                     cfio%varObjs(i)%attRealCnts(count),      &
                     cfio%varObjs(i)%varAttReals(count,maxLen), stat=rtcode)
               call getList(rList=cfio%varObjs(i)%rList,    &
                       realAttNames=cfio%varObjs(i)%attRealNames, &
                       realAttCnts=cfio%varObjs(i)%attRealCnts,   &
                       realAtts=cfio%varObjs(i)%varAttReals)
            end if
         end do
!        write real variable attributes to output file
         do iCnt = 1, cfio%varObjs(i)%nVarAttReal
            allocate(realVarAtt(size(cfio%varObjs(i)%varAttReals)/ &
                     cfio%varObjs(i)%nVarAttReal), stat=rc)
            realVarAtt = cfio%varObjs(i)%varAttReals(iCnt,:)
            if (cfio%varObjs(i)%attRealCnts(iCnt) .ne. size(realVarAtt)) then
              rc=err("FileCreate: Num of real var elements and Cnt differ",-39,-39)
              return
            end if
            rc = NF90_PUT_ATT(cfio%fid,vid(i),cfio%varObjs(i)%attRealNames(iCnt),&
                        realVarAtt)
            if (err("FileCreate: error from NF90_PUT_ATT for real att",rc,-35) &
                .LT. 0) return
            deallocate(realVarAtt)
         end do
!        get integer variable attributes from iList
         do iCnt = 1, cfio%mVars
            if ( associated(cfio%varObjs(i)%iList) ) then
               call getMaxLenCnt(maxLen, cfio%varObjs(i)%nVarAttInt, &
                                 iList=cfio%varObjs(i)%iList)
               count = cfio%varObjs(i)%nVarAttInt
               allocate(cfio%varObjs(i)%attIntNames(count),     &
                     cfio%varObjs(i)%attIntCnts(count),      &
                     cfio%varObjs(i)%varAttInts(count,maxLen), stat=rtcode)
               call getList(iList=cfio%varObjs(i)%iList,    &
                       intAttNames=cfio%varObjs(i)%attIntNames, &
                       intAttCnts=cfio%varObjs(i)%attIntCnts,   &
                       intAtts=cfio%varObjs(i)%varAttInts)
            end if
         end do
!        write int variable attributes to output file
         do iCnt = 1, cfio%varObjs(i)%nVarAttInt
            allocate(intVarAtt(size(cfio%varObjs(i)%varAttInts)/ &
                     cfio%varObjs(i)%nVarAttInt), stat=rc)
            intVarAtt = cfio%varObjs(i)%varAttInts(iCnt,:)
            if (cfio%varObjs(i)%attIntCnts(iCnt) .gt. size(intVarAtt)) then
              rc=err("FileCreate: Num of int var elements and Cnt differ",-39,-39)
              return
            end if
            rc = NF90_PUT_ATT(cfio%fid,vid(i),cfio%varObjs(i)%attIntNames(iCnt),intVarAtt)
            if (err("FileCreate: error from NF90_PUT_ATT for int att",rc,-35) &
                .LT. 0) return
            deallocate(intVarAtt)
         end do
!        get char variable attributes from cList
         do iCnt = 1, cfio%mVars
            if ( associated(cfio%varObjs(i)%cList) ) then
               call getMaxLenCnt(maxLen, cfio%varObjs(i)%nVarAttChar, &
                                 cList=cfio%varObjs(i)%cList)
               count = cfio%varObjs(i)%nVarAttChar
               allocate(cfio%varObjs(i)%attCharNames(count),     &
                     cfio%varObjs(i)%attCharCnts(count),      &
                     cfio%varObjs(i)%varAttChars(count), stat=rtcode)
               call getList(cList=cfio%varObjs(i)%cList,    &
                       charAttNames=cfio%varObjs(i)%attCharNames, &
                       charAttCnts=cfio%varObjs(i)%attCharCnts,   &
                       charAtts=cfio%varObjs(i)%varAttChars)
            end if
         end do
!        write char variable attributes to output file
         do iCnt = 1, cfio%varObjs(i)%nVarAttChar
            rc = NF90_PUT_ATT(cfio%fid,vid(i),cfio%varObjs(i)%attCharNames(iCnt),&
                        cfio%varObjs(i)%varAttChars(iCnt))
            if (err("FileCreate: error from NF90_PUT_ATT for char att",rc,-35) &
                .LT. 0) return
         end do
!         write scaleFactor, addOffSet, and standardName to output
!         if (cfio%varObjs(i)%scaleFactor /= 0) then
            scale_factor = cfio%varObjs(i)%scaleFactor
            rc = NF90_PUT_ATT(cfio%fid, vid(i), 'scale_factor', scale_factor)
            if (err("FileCreate: error from NF90_PUT_ATT for scale_factor",rc,-35) &
                .LT. 0) return
!         end if
!         if (cfio%varObjs(i)%addOffSet /= 0) then
            add_offset = cfio%varObjs(i)%addOffSet
            rc = NF90_PUT_ATT(cfio%fid, vid(i), 'add_offset', add_offset)
            if (err("FileCreate: error from NF90_PUT_ATT for add_offset",rc,-35) &
                .LT. 0) return
!           end if
         if ( LEN_TRIM(cfio%varObjs(i)%standardName) .gt. 0 ) then
            rc = NF90_PUT_ATT(cfio%fid, vid(i), 'standard_name', &
                        cfio%varObjs(i)%standardName)
            if (err("FileCreate: error from NF90_PUT_ATT for standard_name",rc,-35) &
                .LT. 0) return
         end if
        end if
        if (vRange_32(1,i) .NE. amiss_32 .OR. vRange_32(2,i) .NE.  &
           amiss_32) then
          if (vRange_32(1,i) .GT. vRange_32(2,i)) then
            high_32 = vRange_32(1,i)
            low_32  = vRange_32(2,i)
          else
            high_32 = vRange_32(2,i)
            low_32  = vRange_32(1,i)
          endif
          rc = NF90_PUT_ATT(fid,vid(i),'vmin',low_32)
          if (err("Create: error defining vmin attribute",rc,-35) &
             .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'vmax',high_32)
          if (err("Create: error defining vmax attribute",rc,-35) &
             .LT. 0) return
        else
          rc = NF90_PUT_ATT(fid,vid(i),'vmin',amiss_32)
          if (err("Create: error defining vmin attribute",rc,-35) &
             .LT. 0) return
          rc = NF90_PUT_ATT(fid,vid(i),'vmax',amiss_32)
          if (err("Create: error defining vmax attribute",rc,-35) &
             .LT. 0) return
        endif
        rc = NF90_PUT_ATT(fid,vid(i),'valid_range',vRange_32(:,i))
        if (err("Create: error defining valid_range attribute",rc,-35) &
           .LT. 0) return
        if ( cfio%varObjs(i)%timAve ) then
           rc = NF90_PUT_ATT(fid, vid(i), 'cell_methods',  &
                    'time: '//trim(cfio%varObjs(i)%cellMthd))
           if (err("Create: error defining cell_methods attribute",rc,-35) &
                   .LT. 0) return
        end if
        if (cfio%mGrids == 1) then
           ig = 1
           if (cfio%grids(ig)%twoDimLat) then
              rc = NF90_PUT_ATT(fid, vid(i), 'coordinates',  &
                   coordinatesName)
              if (err("Create: error defining coordinates attribute",rc,-35) &
                   .LT. 0) return
           end if
           if (cfio%formatVersion > 2.0) then
              rc = NF90_PUT_ATT(fid, vid(i), 'grid_mapping',  &
                   'cubed_sphere')
              if (err("Create: error defining grid_mapping attribute",rc,-35) &
                   .LT. 0) return
           end if
        end if
      enddo
      if ( aveFile ) then
         dimsbnd(1) = bndsdim
         dimsbnd(2) = timedim
         rc =  NF90_DEF_VAR (fid, 'time_bnds', NF90_FLOAT, dimsbnd, bndsid)
      end if
! Exit define mode.
      rc = NF90_ENDDEF (fid)
      if (err("Create: error exiting define mode",rc,-37) .LT. 0)  &
       return
! Write out dimension variables.
  do ig = 1, cfio%mGrids
      im = cfio%grids(ig)%im
      jm = cfio%grids(ig)%jm
      km = cfio%grids(ig)%km
      tm = max(tm,cfio%grids(ig)%tm)
      if (cfio%grids(ig)%twoDimLat) then
         sz_lon = im*jm
         sz_lat = sz_lon
      else
         sz_lon = im
         sz_lat = jm
      end if
      allocate(lon_64(sz_lon), lat_64(sz_lat), levs_64(km), ak_32(km+1),         &
            bk_32(km+1), layer(km+1), stat = rtcode)
      ptop_32(1) = cfio%grids(ig)%ptop
      do i=1,sz_lon
         lon_64(i) = cfio%grids(ig)%lon(i)
      enddo
      do i=1,sz_lat
         lat_64(i) = cfio%grids(ig)%lat(i)
      enddo
      fVersion = nint(cfio%formatVersion)
      if (cfio%grids(ig)%twoDimLat) then
         xOffset = 0 ! offset to bring index to the middle of face 1
         yOffset = 0 ! offset to bring index to the middle of face 1
         if (jm == 6*im) then
            xOffset = (im/2)*(jm/6)
            yOffset = (im/2)
         end if
         allocate(lon2_64(im), lat2_64(jm), stat = rtcode)
         do i=1,im
            if (fVersion < 3) then
               lon2_64(i) = i ! index
            else
               lon2_64(i) = cfio%grids(ig)%lon(i+xOffset) ! lons at first face
               if (lon2_64(i) > 180.0d0 ) lon2_64(i) = lon2_64(i) - 360.0d0
            end if
         enddo
         do i=1,jm
            if (fVersion < 3) then
               lat2_64(i) = i ! index
            else
               lat2_64(i) = cfio%grids(ig)%lat((i-1)*im + yOffset+1) ! lats at face 1
            end if
         enddo
      end if
      do i=1,km
         levs_64(i) = cfio%grids(ig)%lev(i)
      enddo
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_hybrid_sigma_pressure_coordinate' ) then
         if (associated(cfio%grids(ig)%ak) .and. &
             associated(cfio%grids(ig)%bk) ) then
            do i=1,km+1
               layer(i) = i
               ak_32(i) = cfio%grids(ig)%ak(i)
               bk_32(i) = cfio%grids(ig)%bk(i)
            enddo
         else
             if (err(": ak or bk is not set",-1,-1) .lt. 0 ) return
         end if
      end if
      if (useFaceDim) then
         allocate(ivar(nf), stat=rtcode)
         do i=1, nf
            ivar(i) = i
         end do
         corner(1) = 1
         edges(1) = nf
         rc = NF90_PUT_VAR(fid,faceid(ig),ivar,corner,edges)
         if (err("Create: error writing nf",rc,-38) .LT. 0) return
         deallocate(ivar)
         allocate(ivar(ncont), stat=rtcode)
         do i=1, ncont
            ivar(i) = i
         end do
         corner(1) = 1
         edges(1) = ncont
         rc = NF90_PUT_VAR(fid,ncontid(ig),ivar,corner,edges)
         if (err("Create: error writing nf",rc,-38) .LT. 0) return
         deallocate(ivar)
      end if
      if (cfio%grids(ig)%twoDimLat) then
         corner(1) = 1
         edges(1) = im
         rc = NF90_PUT_VAR(fid,lonid(ig),lon2_64,corner,edges)
         if (err("Create: error writing lons2",rc,-38) .LT. 0) return
         corner(1) = 1
         if (useFaceDim) then
            edges(1) = jm/nf
         else
            edges(1) = jm
         end if
         rc = NF90_PUT_VAR(fid,latid(ig),lat2_64,corner,edges)
         if (err("Create: error writing lats2",rc,-38) .LT. 0) return
         nsize=2
         corner2d = 1
         edges2d = 1
         edges2d(1) = im
         if (useFaceDim) then
            nsize = 3
            edges2d(2) = jm/nf
            edges2d(3) = nf
         else
            edges2d(2) = jm
         end if
         rc = NF90_PUT_VAR(fid, lon2id(ig), lon_64,corner2d(1:nsize), edges2d(1:nsize))
         if (err("Create: error writing lons",rc,-38) .LT. 0) return
!         corner2d = 1
!         edges2d(1) = im
!         edges2d(2) = jm
         rc = NF90_PUT_VAR(fid, lat2id(ig), lat_64,corner2d(1:nsize), edges2d(1:nsize))
         if (err("Create: error writing lats",rc,-38) .LT. 0) return
         deallocate(lon2_64, stat = rtcode)
         deallocate(lat2_64, stat = rtcode)
      else
         corner(1) = 1
         edges(1) = im
         rc = NF90_PUT_VAR(fid, lonid(ig), lon_64, corner, edges)
         if (err("Create: error writing lons",rc,-38) .LT. 0) return
         corner(1) = 1
         edges(1) = jm
         rc = NF90_PUT_VAR(fid, latid(ig), lat_64, corner, edges)
         if (err("Create: error writing lats",rc,-38) .LT. 0) return
      end if
      deallocate(lon_64, stat = rtcode)
      deallocate(lat_64, stat = rtcode)
      if (.NOT. surfaceOnly) then
        corner(1) = 1
        edges(1) = km
        rc = NF90_PUT_VAR(fid, levid(ig), levs_64, corner, edges)
        if (err("Create: error writing levs",rc,-38) .LT. 0) return
      endif
      deallocate(levs_64, stat = rtcode)
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_hybrid_sigma_pressure_coordinate' ) then
        corner(1) = 1
        edges(1) = 1
        rc = NF90_PUT_VAR(fid, ptopid(ig), ptop_32, corner, edges)
        if (err("Create: error writing ptopid prs",rc,-38) .LT. 0) return
        corner(1) = 1
        edges(1) = km+1
        rc = NF90_PUT_VAR(fid, layerid(ig), layer, corner, edges)
        if (err("Create: error writing layers",rc,-38) .LT. 0) return
        rc = NF90_PUT_VAR(fid, akid(ig), ak_32, corner, edges)
        rc = NF90_PUT_VAR(fid, bkid(ig), bk_32, corner, edges)
        if (err("Create: error writing ak/bk",rc,-38) .LT. 0) return
      endif
      deallocate(layer, stat = rtcode)
      deallocate(ak_32, stat = rtcode)
      deallocate(bk_32, stat = rtcode)
      if ( trim(cfio%grids(ig)%standardName) .eq. &
           'atmosphere_sigma_coordinate' ) then
        corner(1) = 1
        edges(1) = 1
        rc = NF90_PUT_VAR(fid, ptopid(ig), ptop_32, corner, edges)
      endif
! end of mGrids loop
 end do
      corner(1) = 1
      edges(1) = 1
      rc = NF90_PUT_VAR(fid, timeid, (/0/), corner, edges)
      if (err("Create: error writing times",rc,-38) .LT. 0) return
      deallocate(latid, stat = rtcode)
      deallocate(lonid, stat = rtcode)
      deallocate(lat2id, stat = rtcode)
      deallocate(lon2id, stat = rtcode)
      deallocate(levid, stat = rtcode)
      deallocate(layerid, stat = rtcode)
      deallocate(latdim, stat = rtcode)
      deallocate(londim, stat = rtcode)
      deallocate(levdim, stat = rtcode)
      deallocate(layerdim, stat = rtcode)
      deallocate(akid, stat = rtcode)
      deallocate(bkid, stat = rtcode)
      deallocate(ptopid, stat = rtcode)
      deallocate(gDims3D, stat = rtcode)
      deallocate(gDims2D, stat = rtcode)
      deallocate(stationdim, stat = rtcode)
      deallocate(stationid, stat = rtcode)
      deallocate(station, stat = rtcode)
      deallocate(vname, stat = rtcode)
      deallocate(vtitle, stat = rtcode)
      deallocate(vunits, stat = rtcode)
      deallocate(kmvar, stat = rtcode)
      deallocate(valid_range, stat = rtcode)
      deallocate(packing_range, stat = rtcode)
      deallocate(vid, stat = rtcode)
      deallocate(vRange_32, stat = rtcode)
      deallocate(pRange_32, stat = rtcode)
      deallocate(faceid, stat = rtcode)
      deallocate(facedim, stat = rtcode)
      deallocate(lonvid, stat = rtcode)
      deallocate(lonvdim, stat = rtcode)
      deallocate(latvid, stat = rtcode)
      deallocate(latvdim, stat = rtcode)
      deallocate(ncontid, stat = rtcode)
      deallocate(ncontdim, stat = rtcode)
      deallocate(stringid, stat = rtcode)
      deallocate(stringdim, stat = rtcode)
      deallocate(gmid, stat = rtcode)
      deallocate(gmdim, stat = rtcode)
      rc=rtcode
      return
contains
  logical function isFileExtensionNetCDF4(fileName)
    character(len=*) :: fileName
    character(len=len(fileName)) :: ext
    integer :: i
    isFileExtensionNetCDF4 = .false.
    ext = ''
    i = index(fileName,'.',back=.true.)
    if (i==0) return
    ext = fileName(i+1:)
    if (ext == 'nc4' .or. ext == 'h5') then
       isFileExtensionNetCDF4 = .true.
    end if
    return
  end function isFileExtensionNetCDF4
      end subroutine CFIO_Create_
Call graph
cfio_create_ calls grids, nf90_create, nf90_def_dim, nf90_def_var, nf90_def_var_chunking, nf90_def_var_deflate, nf90_enddef, nf90_put_att, nf90_put_var, cfio_parseinttime, err, getlist, getmaxlencnt, varobjs
getlist calls getmaxlencnt
esmf_cfiosdffilecreate calls cfio_create_
esmf_cfiofilecreate calls esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite1d_ calls esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite2d_ calls esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite3d_ calls esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
mapl_cfiocreatewrite calls esmf_cfiofilecreate
test calls esmf_cfiofilecreate
esmf_cfiovarwrite1d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite2d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite3d_ calls esmf_cfiosdfvarwrite
mapl_cfiowritebundle calls mapl_cfiocreatewrite