CFIO_GetCharAtt – MAPL
CFIO_GetCharAtt Subroutine
26 statements
Source File
public subroutine CFIO_GetCharAtt(fid, name, count, buf, rc)
CFIO_GetCharAtt – Read a user-defined character attribute
This routine allows the user to read a character attribute from an open CFIO file.
History
1998.07.30 Lucchesi Initial interface design.
1998.07.30 Lucchesi Initial coding.
1998.09.29 Lucchesi Changed error handling.
Arguments
Type Intent Optional Attributes Name
integer :: fid
File handle
character(len=*) :: name
Name of attribute
integer :: count
On input: Number of items in attribute On output: If rc = -1, count will contain the correct number of attributes
character(len=1) :: buf(count)
Buffer with character values
integer :: rc
Error return code: rc = 0 all is well rc = -1 invalid count rc = -2 type mismatch
NetCDF Errors
rc = -36 error from NF90_PUT_ATT (global attribute) rc = -51 error from NF90_GET_ATT (global attribute)
Calls
Called by
Contents
Source Code
CFIO_GetCharAtt
Source Code
      subroutine CFIO_GetCharAtt ( fid, name, count, buf, rc )
!
! !USES:
!
      Implicit NONE
!
! !INPUT PARAMETERS:
!
      integer        fid        !! File handle
      character(len=*)  name       !! Name of attribute
!
! !INPUT/OUTPUT PARAMETERS:
!
      integer        count      !! On input: Number of items in attribute
                                !! On output: If rc = -1, count will contain
                                !!        the correct number of attributes
!
! !OUTPUT PARAMETERS:
!
      character :: buf(count) !! Buffer with character values
!      character(len=MLEN) :: buf !! Buffer with character values
      integer   rc         !! Error return code:
                           !!   rc = 0    all is well
                           !!   rc = -1   invalid count
                           !!   rc = -2   type mismatch
                           !!
                           !!  NetCDF Errors
                           !!  -------------
                           !!   rc = -36  error from NF90_PUT_ATT (global attribute)
                           !!   rc = -51  error from NF90_GET_ATT (global attribute)
!
!-------------------------------------------------------------------------
      integer length, type
      character(len=count) :: chartmp
      rc = NF90_INQUIRE_ATTRIBUTE (fid, NF90_GLOBAL, name, type, length)
      if (err("GetCharAtt: error reading attribute info",rc,-58) &
           .NE. 0) return
      if ( count .NE. length ) then
        rc = -1
        count = length
        return
      endif
      if ( type .NE. NCCHAR) then
        rc = -2
        return
      endif
      rc  = NF90_GET_ATT(fid,NF90_GLOBAL,name,chartmp)
      if (err("GetCharAtt: error reading attribute value",rc,-51) &
           .NE. 0) return
      buf = chartmp
      rc = 0
      return
      end subroutine CFIO_GetCharAtt
Call graph
cfio_getcharatt calls nf90_get_att, nf90_inquire_attribute, err
esmf_cfiosdffileopen calls cfio_getcharatt
esmf_cfiofileopen calls esmf_cfiosdffileopen
esmf_cfiosdfvarread1d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
find calls esmf_cfiofileopen
mapl_cfioopenwrite calls esmf_cfiofileopen
mapl_cfioreadbundle calls esmf_cfiofileopen
test calls esmf_cfiofileopen
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
esmf_cfiosdfvarreadt2d__ calls esmf_cfiosdfvarread
esmf_cfiosdfvarreadt3d__ calls esmf_cfiosdfvarread
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread
esmf_cfiovarread2d_ calls esmf_cfiosdfvarread
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle