checkUnused – MAPL
checkUnused Function
22 statements
Source File
private function checkUnused(this)
Type Bound
VarConn
Arguments
Type Intent Optional Attributes Name
class(VarConn), intent(inout), target :: this
Return Value logical
Calls
Called by
Source Code
   logical function checkUnused(this)
      class(VarConn), target, intent(inout) :: this
      integer                               :: I
      class(Logger), pointer :: lgr
      type(VarConnType), pointer :: conn
      character(len=ESMF_MAXSTR)            :: from_name, to_name
      associate (conn_v => this%conn_v)
        checkUnused = .true.
        do I = 1, conn_v%size()
           conn => conn_v%of(i)
           if (conn%notRequired) cycle
           if (.not. conn%USED) then
              checkUnused = .false.
              lgr => logging%get_logger('MAPL.GENERIC')
              from_name = conn%FROM%get_short_name()
              to_name   = conn%TO%get_short_name()
              call lgr%error( &
                   'SRC_NAME: <%a~>  DST_NAME: <%a~> is not satisfied', &
                   trim(from_name),trim(to_name))
           end if
        end do
      end associate
      return
   end function CheckUnused
Call graph
checkunused calls get_logger, of, error, get_short_name
mapl_genericconncheck calls checkunused, mapl_genericconncheck
mapl_genericsetservices calls mapl_genericconncheck
setservices calls mapl_genericsetservices