check_unexpected_index – MAPL
check_unexpected_index Subroutine
26 statements
Source File
private subroutine check_unexpected_index(grid, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine check_unexpected_index(grid, rc)
     type(ESMF_Grid), intent(inout) :: grid
     integer, intent(out), optional :: rc
! locals
     integer :: status, i, j, II(1), JJ(1)
     real, dimension(:,:), pointer :: lats, lons
     real :: lon(1), lat(1)
      call ESMFL_GridCoordGet(   grid, lats                      , &
                              Name     = "Latitude"              , &
                              Location = ESMF_STAGGERLOC_CENTER  , &
                              Units    = MAPL_UnitsRadians    , _RC)
      call ESMFL_GridCoordGet(   grid, lons                      , &
                              Name     = "Longitude"             , &
                              Location = ESMF_STAGGERLOC_CENTER  , &
                              Units    = MAPL_UnitsRadians    , _RC)
      ! centers of antipodal points
       lons = lons + MAPL_PI
       lats = -lats
      _ASSERT(all(shape(LATS) == shape(LONS)), 'LATS and LONS must have the same shape')
      do j = 1, size(lats,2)
         do i = 1, size(lats, 1)
            lon = lons(i,j)
            lat = lats(i,j)
            call MAPL_GetHorzIJIndex(1, II(1), JJ(1),  &
                grid=grid, lon=lon, lat=lat, _RC)
            _ASSERT(II(1) == -1, 'Expected -1 for point outside of domain')
            _ASSERT(JJ(1) == -1, 'Expected -1 for point outside of domain')
         end do
      end do
     _RETURN(_SUCCESS)
  end subroutine check_unexpected_index
Call graph
check_unexpected_index calls mapl_assert, mapl_gethorzijindex, esmfl_gridcoordget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gethorzijindex calls mapl_gethorzijindex, mapl_assert, mapl_return, mapl_verify, ESMF_GridGet, ESMF_GridGetCoord, mapl_gridget, mapl_getglobalhorzijindex, mapl_grid_interior
esmfl_gridcoordget calls mapl_assert, mapl_return, mapl_verify, ESMF_GridGet, ESMF_GridGetCoord, mapl_gridget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridget calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_AttributeGet, ESMF_DistGridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_throw_exception calls initialize
mapl_getglobalhorzijindex calls mapl_getglobalhorzijindex
mapl_grid_interior calls mapl_grid_interior
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_DistGridGet, ESMF_DELayoutGet
run calls check_unexpected_index