check_resources – MAPL
check_resources Subroutine
18 statements
Source File
subroutine check_resources(rc)
Uses
SupportMod
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
check_resources
Source Code
   subroutine check_resources(rc)
      use SupportMod
      integer, optional, intent(out) :: rc
      integer:: status
      type (ESMF_VM) :: vm_global
      call ESMF_VMGetGlobal(vm_global, rc=status)
      call ESMF_VMGet(vm_global, petcount=pet_count, localpet=local_pet, rc=status)
      if (mod(pet_count,N_TILES) /= 0) then ! should just require a multiple, but ...
         rc = -1
         if (local_pet == 0) then
            write(*,*)'The number of mpi processes must be a multile of 6.'
         end if
         _RETURN(_FAILURE)
      end if
      _RETURN(_SUCCESS)
   end subroutine check_resources
Call graph
check_resources calls ESMF_VMGet, ESMF_VMGetGlobal, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
main calls check_resources