check_token – MAPL
check_token Function
12 statements
Source File
private function check_token(token) result(is_valid)
Arguments
Type Intent Optional Attributes Name
character(len=2), intent(in) :: token
Return Value logical
Called by
Contents
Source Code
check_token
Source Code
   function check_token(token) result(is_valid)
      character(len=2), intent(in) :: token
      logical :: is_valid
      integer :: i
      is_valid = .false.
      do i=1,size(valid_tokens)
         if (token==valid_tokens(i)) then
            is_valid=.true.
            exit
         end if
      enddo
   end function check_token
Call graph
fill_grads_template calls check_token
mapl_read_bundle calls fill_grads_template
mapl_getcurrentfile calls fill_grads_template
getlevs calls fill_grads_template
mapl_cfioreadbundle calls fill_grads_template
getclimyear calls fill_grads_template
mapl_genericfinalize calls fill_grads_template
run calls fill_grads_template
updatebrackettime calls fill_grads_template
get_file calls fill_grads_template
create_primary_field calls fill_grads_template
strtemplate calls fill_grads_template
finalize_ calls mapl_genericfinalize
main calls mapl_read_bundle
initialize_ calls getlevs, getclimyear, create_primary_field
time_ave calls mapl_read_bundle
mapl_cfioreadstate calls mapl_cfioreadbundle
ut_regridding calls mapl_read_bundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
finalize calls mapl_genericfinalize
run_ calls updatebrackettime