CheckIfConformal – MAPL
CheckIfConformal Function
75 statements
Source File
private function CheckIfConformal(field_1, field_2, rc) result(res)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field_1
type(ESMF_Field), intent(inout) :: field_2
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Contents
Source Code
CheckIfConformal
Source Code
  FUNCTION CheckIfConformal(field_1,field_2,rc) result(res)
     TYPE(ESMF_Field),      intent(inout) :: field_1
     TYPE(ESMF_Field),      intent(inout) :: field_2
     integer, optional,     intent(out  ) :: rc
     logical                               :: res
     character(len=ESMF_MAXSTR), parameter :: Iam ="CheckIfConformal"
     integer                               :: status
     type(ESMF_Array)                      :: array_1,array_2
     type (ESMF_LocalArray), target        :: larrayList(1)
     type(ESMF_LocalArray), pointer        :: larray_1,larray_2
     integer                               :: rank_1, rank_2
     integer                               :: lbnds_1(ESMF_MAXDIM), ubnds_1(ESMF_MAXDIM)
     integer                               :: lbnds_2(ESMF_MAXDIM), ubnds_2(ESMF_MAXDIM)
     integer                               :: i
     call ESMF_FieldGet(field_1,array=array_1,rc=status)
     _VERIFY(STATUS)
     call ESMF_ArrayGet(array_1, localarrayList=larrayList, rc=status)
     _VERIFY(STATUS)
     larray_1 => lArrayList(1) ! alias
     call ESMF_LocalArrayGet(larray_1,rank=rank_1,totalLBound=lbnds_1,totalUBound=ubnds_1,rc=status)
     _VERIFY(STATUS)
     call ESMF_FieldGet(field_2,array=array_2,rc=status)
     _VERIFY(STATUS)
     call ESMF_ArrayGet(array_2, localarrayList=larrayList, rc=status)
     _VERIFY(STATUS)
     larray_2 => lArrayList(1) ! alias
     call ESMF_LocalArrayGet(larray_2,rank=rank_2,totalLBound=lbnds_2,totalUBound=ubnds_2,rc=status)
     _VERIFY(STATUS)
     if (rank_1 == 2 .and.  rank_2 == 2) then
        do i=1,2
           if (lbnds_1(i) /= lbnds_2(i)) then
              res = .false.
           else if (ubnds_1(i) /= ubnds_2(i)) then
              res = .false.
           else
              res = .true.
           end if
        end do
     end if
     if (rank_1 == 3 .and.  rank_2 == 3) then
        do i=1,3
           if (lbnds_1(i) /= lbnds_2(i)) then
              res = .false.
           else if (ubnds_1(i) /= ubnds_2(i)) then
              res = .false.
           else
              res = .true.
           end if
        end do
     end if
     if (rank_1 == 3 .and.  rank_2 == 2) then
        do i=1,2
           if (lbnds_1(i) /= lbnds_2(i)) then
              res = .false.
           else if (ubnds_1(i) /= ubnds_2(i)) then
              res = .false.
           else
              res = .true.
           end if
        end do
     end if
     if (rank_1 == 2 .and.  rank_2 == 3) then
        do i=1,2
           if (lbnds_1(i) /= lbnds_2(i)) then
              res = .false.
           else if (ubnds_1(i) /= ubnds_2(i)) then
              res = .false.
           else
              res = .true.
           end if
        end do
     end if
     _RETURN(ESMF_SUCCESS)
  END FUNCTION CheckIfConformal
Call graph
checkifconformal calls esmf_fieldget, esmf_arrayget, mapl_return, mapl_verify, esmf_localarrayget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_stateeval calls checkifconformal
mapl_runexpression calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
calcderivedfield calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
run calls mapl_runexpression
run_ calls fillstate, calcderivedfield