CheckUpdate – MAPL
CheckUpdate Subroutine
73 statements
Source File
private subroutine CheckUpdate(doUpdate, updateTime, currTime, hasRun, primaryItem, derivedItem, rc)
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: doUpdate
type(ESMF_Time), intent(inout) :: updateTime
type(ESMF_Time), intent(inout) :: currTime
logical, intent(in) :: hasRun
type(PrimaryExport), intent(inout), optional :: primaryItem
type(DerivedExport), intent(inout), optional :: derivedItem
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine CheckUpdate(doUpdate,updateTime,currTime,hasRun,primaryItem,derivedItem,rc)
     logical,                       intent(out  ) :: doUpdate
     type(ESMF_Time),               intent(inout) :: updateTime
     type(ESMF_Time),               intent(inout) :: currTime
     logical        ,               intent(in   ) :: hasRun
     type(PrimaryExport), optional, intent(inout) :: primaryItem
     type(DerivedExport), optional, intent(inout) :: derivedItem
     integer,             optional, intent(out  ) :: rc
     character(len=ESMF_MAXSTR) :: Iam
     integer                    :: status
     type(ESMF_Time)            :: time,time0,refresh_time
     Iam = "CheckUpdate"
     time0 = currTime
     time  = currTime
     if (present(primaryItem)) then
        if (primaryItem%AlarmIsEnabled) then
           doUpdate = primaryItem%update_alarm%is_ringing(currTime,_RC)
           if (hasRun .eqv. .false.) doUpdate = .true.
           updateTime = currTime
        else if (trim(primaryItem%cyclic) == 'single') then
           doUpdate = .true.
        else
           if (primaryItem%refresh_template == "0") then
              doUpdate = .true.
              updateTime = time0 + PrimaryItem%tshift
           else
              updateTime = time0
              if (.not. associated(PrimaryItem%refresh_time)) then
                doUpdate = .false.
              else
                 refresh_time = timestamp_(time, PrimaryItem%refresh_template, _RC)
                 if (refresh_time /= primaryItem%refresh_time) then
                    doUpdate = .true.
                    primaryItem%refresh_time = refresh_time
                    updateTime = refresh_time
                 else
                    doUpdate = .false.
                 end if
              end if
           end if
        end if
     else if (present(derivedItem)) then
        if (DerivedItem%AlarmIsEnabled) then
           doUpdate = derivedItem%update_alarm%is_ringing(currTime,_RC)
           updateTime = currTime
        else
           if (derivedItem%refresh_template == "0") then
              doUpdate = .true.
              updateTime = time0 + derivedItem%tshift
           else
              updateTime = time0
              if (.not. associated(derivedItem%refresh_time)) then
                doUpdate = .false.
              else
                 refresh_time = timestamp_(time, derivedItem%refresh_template, _RC)
                 if (refresh_time /= derivedItem%refresh_time) then
                    doUpdate = .true.
                    derivedItem%refresh_time = refresh_time
                    time = refresh_time
                 else
                    doUpdate = .false.
                 end if
              end if
           end if
        end if
     end if
     _RETURN(ESMF_SUCCESS)
  end subroutine CheckUpdate
Call graph
checkupdate calls is_ringing, mapl_return, mapl_verify, timestamp_
is_ringing calls mapl_return, mapl_verify, ESMF_TimeIntervalGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
timestamp_ calls mapl_return, mapl_verify, ESMF_TimeGet, ESMF_TimeSet, ESMF_UtilStringLowerCase, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
run_ calls checkupdate