check_if_initialized – MAPL
check_if_initialized Function
10 statements
Source File
private function check_if_initialized(this, rc) result(field_initialized)
Type Bound
ExtDataNode
Arguments
Type Intent Optional Attributes Name
class(ExtDataNode), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Call graph
check_if_initialized calls ESMF_FieldIsCreated, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
interpolate_to_time calls check_if_initialized
mapl_extdatainterpfield calls interpolate_to_time
run_ calls mapl_extdatainterpfield