checkUndef – MAPL
checkUndef Function
24 statements
Source File
private function checkUndef(str, ibegin, inext) result(isUndef)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(out), optional :: ibegin
integer, intent(out), optional :: inext
Return Value logical
Calls
Called by
Source Code
  FUNCTION checkUndef (str, ibegin, inext) RESULT (isUndef)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Return index of variable at begin of string str (returns 0 if no variable found)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    CHARACTER (LEN=*),               INTENT(in) :: str       ! String
    LOGICAL                                     :: isUndef   ! Index of variable
    INTEGER, OPTIONAL,              INTENT(out) :: ibegin, & ! Start position of variable name
                                                   inext     ! Position of character after name
    INTEGER                                     :: ib,in,lstr
    CHARACTER (LEN=ESMF_MAXSTR)                 :: fun
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    isUndef = .false.
    lstr = LEN_TRIM(str)
    IF (lstr > 0) THEN
       DO ib=1,lstr                                          ! Search for first character in str
          IF (str(ib:ib) /= ' ') EXIT                        ! When lstr>0 at least 1 char in str
       END DO
       DO in=ib,lstr                                         ! Search for name terminators
          IF (SCAN(str(in:in),'+-*/^) ') > 0) EXIT
       END DO
       CALL LowCase (str(ib:in-1), fun)
       IF (trim(fun) == 'undef') THEN
             isUndef = .true.                           ! Variable name found
       END IF
    END IF
    IF (PRESENT(ibegin)) ibegin = ib
    IF (PRESENT(inext))  inext  = in
  END FUNCTION checkUndef
Call graph
checkundef calls lowcase
checksyntax calls checkundef
mathitemindex calls checkundef
parser_variables_in_expression calls checkundef
compilesubstr calls mathitemindex, compilesubstr
get_mask_variables calls parser_variables_in_expression
get_variables_in_expression calls parser_variables_in_expression, get_mask_variables
initialize_ calls checksyntax, fillstate, get_extra_derived_items
mapl_setexpression calls checksyntax
mapl_stateeval calls checksyntax, parsef
parsef calls checksyntax, compile
calcderivedfield calls mapl_stateeval
compile calls compilesubstr
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
get_extra_derived_items calls get_variables_in_expression
initialize calls mapl_setexpression
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run calls mapl_runexpression
run_ calls calcderivedfield, fillstate, evaluate_derived_field