check_nc_status – MAPL
check_nc_status Subroutine
9 statements
Source File
public subroutine check_nc_status(status, rc)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine check_nc_status(status, rc)
    use netcdf
    implicit none
    integer, intent(in) :: status
    integer, intent(out), optional :: rc
    _ASSERT(status == nf90_noerr, 'netCDF error: '//trim(nf90_strerror(status)))
    _RETURN(_SUCCESS)
  end subroutine check_nc_status
Call graph
check_nc_status calls mapl_assert, nf90_strerror, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_att_char_netcdf calls check_nc_status
get_att_real_netcdf calls check_nc_status
get_attribute_from_group calls check_nc_status
get_ncfile_dimension calls check_nc_status
get_v1d_netcdf_r8 calls check_nc_status
get_v1d_netcdf_r8_complete calls check_nc_status
get_v2d_netcdf_r4 calls check_nc_status
get_v2d_netcdf_r8 calls check_nc_status
get_var_from_name_w_group calls check_nc_status
get_v2d_netcdf calls get_v2d_netcdf_r4, get_v2d_netcdf_r8
add_horz_coordinates_from_abifile calls get_att_real_netcdf, get_v1d_netcdf_r8_complete
create_geosat_grid_find_mask calls get_att_real_netcdf, get_ncfile_dimension, get_v1d_netcdf_r8_complete, create_geosat_grid_find_mask
create_grid calls get_attribute_from_group, get_ncfile_dimension, get_v1d_netcdf_r8
initialize_from_config_with_prefix calls get_ncfile_dimension, read_m_files_4_swath
read_m_files_4_swath calls get_ncfile_dimension, get_var_from_name_w_group
add_horz_coordinates_from_file calls read_m_files_4_swath
get_obs_time calls read_m_files_4_swath
make_new_grid calls add_horz_coordinates_from_abifile, add_horz_coordinates_from_file
initialize_ calls create_geosat_grid_find_mask