check_list_ – MAPL
check_list_ Function
25 statements
Source File
private function check_list_(this, list)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: this
character(len=*), intent(in) :: list
Return Value logical
Called by
Contents
Source Code
check_list_
Source Code
  logical function check_list_ (this,list)
  implicit none
  character(len=*), intent(in) :: this
  character(len=*), intent(in) :: list
  integer i,ll,ls,le
  check_list_=.false.
  if (trim(list)=="NONE") then ! this is when does not specify variables
      check_list_=.true.
  endif
  ll  = len_trim(list)
  ls  = 1
  do i=1,ll
     le=i
     if(list(i:i)==",") then
        if (trim(this)==list(ls:le-1)) then
           check_list_=.true.
           exit
        endif
        ls=le+1
     endif
  enddo
  if (trim(this)==list(ls:ll)) then
      check_list_=.true.
  endif
  end function check_list_
Call graph
state2bundle calls check_list_
statediff calls state2bundle
esmfl_state2bundle calls state2bundle
statestatistics calls statediff
esmfl_diff calls statediff
esmfl_statistics calls statestatistics