clear_hist_collections – MAPL
clear_hist_collections Subroutine
9 statements
Source File
private subroutine clear_hist_collections(this)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout) :: this
Calls
Called by
Source Code
  subroutine clear_hist_collections(this)
    class (ServerThread),intent(inout) :: this
    integer :: i
    type(HistoryCollection),pointer :: hist
    do i = 1, this%hist_collections%size()
      hist=>this%hist_collections%at(i)
      call hist%clear()
    enddo
  end subroutine clear_hist_collections
Call graph
clear_hist_collections calls at, clear
clear calls erase, m_at, m_begin, m_key, mapl_return, mapl_verify
m_at calls m_find
m_begin calls s_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_at_32 calls v_at_size_kind
get_error_message calls at, insert
m_erase_one calls erase
m_find calls s_find
mapl_throw_exception calls initialize
s_begin calls s_next
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections
start calls start_back, clean_up, put_datatofile