clear_backlog – MAPL
clear_backlog Subroutine
9 statements
Source File
private subroutine clear_backlog(this)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout) :: this
Calls
Called by
Source Code
  subroutine clear_backlog(this)
    class (ServerThread),intent(inout) :: this
    type (MessageVectorIterator) :: iter
    iter = this%request_backlog%begin()
    do while (iter /= this%request_backlog%end())
       call this%request_backlog%erase(iter)
       iter = this%request_backlog%begin()
    enddo
  end subroutine clear_backlog
Call graph
clear_backlog calls erase, v_begin
v_erase_one calls erase
clean_up calls clear_backlog
put_datatofile calls clear_backlog
start calls clean_up, put_datatofile