clean – MAPL
clean Subroutine
9 statements
Source File
public subroutine clean(this, rc)
Type Bound
ExtDataNG_IOBundle
Arguments
Type Intent Optional Attributes Name
class(ExtDataNG_IOBundle), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine clean(this, rc)
    class (ExtDataNG_IOBundle), intent(inout) :: this
    integer, optional, intent(out) :: rc
    integer :: status
    call ESMF_FieldBundleDestroy(this%pbundle, noGarbage=.true.,rc=status)
    _VERIFY(status)
     _RETURN(ESMF_SUCCESS)
  end subroutine clean
Call graph
clean calls esmf_fieldbundledestroy, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_extdatadestroycfio calls clean
run_ calls mapl_extdatadestroycfio