clear_subarray – MAPL
clear_subarray Subroutine
13 statements
Source File
private subroutine clear_subarray(this, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine clear_subarray(this, rc)
    class (ServerThread),intent(inout) :: this
    integer, optional, intent(out) :: rc
    integer:: i, sub_arr_type, ierror
    do i = 1, this%sub_array_types%size()
      sub_arr_type = this%sub_array_types%at(i)
      call MPI_type_free(sub_arr_type,ierror)
      _VERIFY(ierror)
    enddo
    call this%sub_array_types%erase(this%sub_array_types%begin(), this%sub_array_types%end())
    _RETURN(_SUCCESS)
  end subroutine clear_subarray
Call graph
clear_subarray calls at, begin, erase, mpi_type_free, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
put_datatofile calls clear_subarray
start calls put_datatofile