clear_DataReference – MAPL
clear_DataReference Subroutine
11 statements
Source File
private subroutine clear_DataReference(this)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout), target :: this
Calls
Called by
Source Code
   subroutine clear_DataReference(this)
      class (AbstractServer), target, intent(inout) :: this
      class (AbstractDataReference), pointer :: datarefPtr
      integer :: n, i
      n = this%dataRefPtrs%size()
      do i = 1, n
         dataRefPtr => this%dataRefPtrs%at(i)
         call dataRefPtr%deallocate()
      enddo
      call this%dataRefPtrs%erase(this%dataRefPtrs%begin(), this%dataRefPtrs%end())
   end subroutine clear_DataReference
Call graph
clear_datareference calls at, erase, v_begin
v_at_32 calls v_at_size_kind
v_erase_one calls erase
clean_up calls clear_datareference
update_status calls clear_datareference
handle_done_collective_prefetch calls clean_up
handle_done_collective_stage calls clean_up
handle_done calls update_status
start calls clean_up