clear – MAPL
clear Subroutine
19 statements
Source File
private subroutine clear(this, rc)
Type Bound
HistoryCollection
Arguments
Type Intent Optional Attributes Name
class(HistoryCollection), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine clear(this, rc)
    class (HistoryCollection), target, intent(inout) :: this
    integer, optional, intent(out) :: rc
    type(NetCDF4_FileFormatter), pointer :: f_ptr
    type(StringNetCDF4_FileFormatterMapIterator) :: iter
    character(:),pointer :: file_name
    integer :: status
    iter = this%formatters%begin()
    do while (iter /= this%formatters%end())
      file_name => iter%key()
      f_ptr => this%formatters%at(file_name)
      call f_ptr%close(rc=status)
      _VERIFY(status)
      ! remove the files
      call this%formatters%erase(iter)
      iter = this%formatters%begin()
    enddo
    _RETURN(_SUCCESS)
  end subroutine clear
Call graph
clear calls erase, m_at, m_begin, m_key, mapl_return, mapl_verify
m_at calls m_find
m_begin calls s_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_erase_one calls erase
m_find calls s_find
mapl_throw_exception calls initialize
s_begin calls s_next
s_find calls at, exists, find_index, s_ordereq
s_next calls advpos
clear_hist_collections calls clear
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections
start calls clean_up, put_datatofile, start_back