clone – MAPL
clone Function
5 statements
Source File
private function clone(this)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(in) :: this
Return Value class(AbstractRegridder), allocatable
Called by
Source Code
   function clone(this)
      class (AbstractRegridder), allocatable :: clone
      class (AbstractRegridder), intent(in) :: this
      allocate(clone, source=this)
   end function clone
Call graph
make_regridder_from_grids calls clone
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder