close_file_handle – MAPL
close_file_handle Subroutine
13 statements
Source File
private subroutine close_file_handle(this, rc)
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Contents
Source Code
close_file_handle
Source Code
      subroutine close_file_handle(this,rc)
         class(HistoryTrajectory), intent(inout) :: this
         integer, optional, intent(out) :: rc
         integer :: status
         if (trim(this%file_name) /= '') then
            if (mapl_am_i_root()) then
               call this%file_handle%close(_RC)
            end if
         end if
         _RETURN(_SUCCESS)
      end subroutine close_file_handle
Call graph
close_file_handle calls mapl_am_i_root, mapl_verify, mapl_return
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout