cNodeDestroy – MAPL
cNodeDestroy Subroutine
16 statements
Source File
public subroutine cNodeDestroy(List)
Arguments
Type Intent Optional Attributes Name
type(cNode), pointer :: List
Called by
Source Code
   subroutine cNodeDestroy(List)
     type(cNode), pointer :: List, p, q
     if (.not. associated(List)) return
     q => List
     p => List%next
     do while ( associated(p) )
        if (associated(q)) then
           deallocate(q)
        end if
        q => p
        p => p%next
     end do
     if (associated(q)) then
        deallocate(q)
     end if
   end subroutine cNodeDestroy
Call graph
esmf_cfiovarinfodestroy calls cnodedestroy
esmf_cfiodestroy calls esmf_cfiovarinfodestroy
find calls esmf_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy, find
unfind calls esmf_cfiodestroy
esmf_iodestroy calls mapl_cfiodestroy
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
finalize calls mapl_cfiodestroy
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls find
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy