collective_prefetch_data – MAPL
collective_prefetch_data Function
27 statements
Source File
private function collective_prefetch_data(this, collection_id, file_name, var_name, data_reference, unusable, start, global_start, global_count, rc) result(request_id)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: global_start(:)
integer, intent(in), optional :: global_count(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function collective_prefetch_data(this, collection_id, file_name, var_name, data_reference, &
        & unusable, start,global_start,global_count, rc) result(request_id)
      class (ClientThread), intent(inout) :: this
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in) :: start(:)
      integer, optional, intent(in) :: global_start(:)
      integer, optional, intent(in) :: global_count(:)
      integer, optional, intent(out):: rc
      integer :: request_id
      class (AbstractMessage), pointer :: handshake_msg
      class(AbstractSocket),pointer :: connection
      integer :: status
      request_id = this%get_unique_collective_request_id()
      connection => this%get_connection()
      call connection%send(CollectivePrefetchDataMessage( &
           request_id, &
           collection_id, &
           file_name, &
           var_name, &
           data_reference,unusable=unusable, start=start,&
           global_start=global_start,global_count=global_count),_RC)
      handshake_msg => connection%receive()
      deallocate(handshake_msg)
      associate (id => request_id)
        ! the get call iRecv
        call this%insert_RequestHandle(id, connection%get(id, data_reference))
      end associate
      _RETURN(_SUCCESS)
   end function collective_prefetch_data
Call graph
collective_prefetch_data calls get, get_connection, get_unique_collective_request_id, insert_requesthandle, mapl_return, mapl_verify, receive, send, collective_prefetch_data
get_connection calls mapl_return, mapl_assert
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
run calls collective_prefetch_data
request_data_from_file calls collective_prefetch_data
main calls run, mapl_read_bundle
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run_ calls mapl_extdataprefetch
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle