collective_stage_data – MAPL
collective_stage_data Function
27 statements
Source File
private function collective_stage_data(this, collection_id, file_name, var_name, data_reference, unusable, start, global_start, global_count, rc) result(request_id)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout), target :: this
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: global_start(:)
integer, intent(in), optional :: global_count(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function collective_stage_data(this, collection_id, file_name, var_name, data_reference, &
        & unusable, start,global_start,global_count, rc) result(request_id)
      class (ClientThread), target, intent(inout) :: this
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in) :: start(:)
      integer, optional, intent(in) :: global_start(:)
      integer, optional, intent(in) :: global_count(:)
      integer, optional, intent(out) :: rc
      integer :: request_id
      class (AbstractMessage), pointer :: handshake_msg
      class(AbstractSocket),pointer :: connection
      integer :: status
      request_id = this%get_unique_collective_request_id()
      connection => this%get_connection()
      call connection%send(CollectiveStageDataMessage( &
           request_id, &
           collection_id, &
           file_name, &
           var_name, &
           data_reference,unusable=unusable, start=start,&
           global_start=global_start,global_count=global_count),_RC)
      handshake_msg => connection%receive()
      deallocate(handshake_msg)
      associate (id => request_id)
        ! the put call iSend
        call this%insert_RequestHandle(id, connection%put(id, data_reference))
      end associate
      _RETURN(_SUCCESS)
   end function collective_stage_data
Call graph
collective_stage_data calls get_connection, get_unique_collective_request_id, insert_requesthandle, mapl_return, mapl_verify, put, receive, send, collective_stage_data
get_connection calls mapl_return, mapl_assert
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
run calls collective_stage_data, bundlepost, regrid_append_file
stage_nondistributed_data calls collective_stage_data
bundlepost calls stage_nondistributed_data, stagedata
mapl_fieldwritencpar calls collective_stage_data, mapl_varwrite
mapl_varwritencpar_r4_2d calls collective_stage_data
mapl_varwritencpar_r4_3d calls collective_stage_data, mapl_varwrite
mapl_varwritencpar_r4_4d calls collective_stage_data, mapl_varwrite
mapl_varwritencpar_r8_2d calls collective_stage_data
mapl_varwritencpar_r8_3d calls collective_stage_data, mapl_varwrite
mapl_varwritencpar_r8_4d calls collective_stage_data, mapl_varwrite
regrid_append_file calls collective_stage_data, stage2dlatlon, regrid_append_file
run_model calls collective_stage_data
stage2dlatlon calls collective_stage_data, stage2dlatlon
stagedata calls collective_stage_data
main calls run, run_model, write_to_file
mapl_varwrite calls mapl_varwritencpar_r4_2d, mapl_varwritencpar_r4_3d, mapl_varwritencpar_r4_4d, mapl_varwritencpar_r8_2d, mapl_varwritencpar_r8_3d, mapl_varwritencpar_r8_4d
mapl_bundlewritencpar calls mapl_fieldwritencpar
write_to_file calls bundlepost
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file