comm_group_range – MAPL
comm_group_range Subroutine
65 statements
Source File
private subroutine comm_group_range(this, my_node, my_rank, nodes_sizes, start_node, start_rank, next_node, next_rank, IamInGroup, unusable, rc)
Type Bound
CommGroupDescription
Arguments
Type Intent Optional Attributes Name
class(CommGroupDescription), intent(in) :: this
integer, intent(in) :: my_node
integer, intent(in) :: my_rank
integer, intent(in) :: nodes_sizes(:)
integer, intent(in) :: start_node
integer, intent(in) :: start_rank
integer, intent(out) :: next_node
integer, intent(out) :: next_rank
logical, intent(inout) :: IamInGroup
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine comm_group_range(this,my_node, my_rank, nodes_sizes, start_node, start_rank, &
                               next_node, next_rank, IamInGroup, unusable, rc)
      class(CommGroupDescription), intent(in) :: this
      integer, intent(in)   :: my_node, my_rank
      integer, intent(in)   :: nodes_sizes(:)
      integer, intent(in)   :: start_node, start_rank
      integer, intent(out)  :: next_node, next_rank
      logical, intent(inout)  :: IamInGroup
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: np, start_node_, start_rank_, i_node, i_rank
       _UNUSED_DUMMY(unusable)
       start_node_ = start_node
       start_rank_ = start_rank
       if (this%isolate_nodes .and. start_rank /= 0) then
          start_node_ = start_node_ + 1
          start_rank_ = 0
       endif
       ! case 1, group is divided by npes
       if(this%npes > 0) then
         np = 0
         outer: do i_node = start_node_, size(nodes_sizes)
           do i_rank = start_rank_, nodes_sizes(i_node)-1
              if( my_node == i_node .and. my_rank == i_rank) then
                  _ASSERT( .not. IamInGroup, "I have been included in the other group")
                  IamInGroup = .true.
              endif
              np = np+1
              if (np == this%npes) then
                 next_node = i_node
                 next_rank = i_rank + 1
                 if (this%isolate_nodes .or. next_rank > nodes_sizes(i_node)-1 ) then
                    next_rank = 0
                    next_node = i_node + 1
                 endif
                 exit outer
              endif
           enddo
        enddo outer
      endif
      ! case 2, group is divided by nnodes
      if (this%nnodes > 0) then
         next_node = start_node_ + this%nnodes
         next_rank = 0
         if (start_node_ <= my_node .and. my_node < next_node) then
            _ASSERT( .not. IamInGroup, "I have been included in the other group")
            IamInGroup = .true.
         endif
      endif
      ! case 3, npes per node
      if (this%npes_per_node > 0) then
         _ASSERT( all(nodes_sizes == nodes_sizes(1)) , " all nodes should have the same amount of cores")
         next_rank  = start_rank + this%npes_per_node
         next_node  = 0 ! no used
         if (start_rank <=my_rank .and. my_rank < next_rank) then
            _ASSERT( .not. IamInGroup, "I have been included in the other group")
            IamInGroup = .true.
         endif
      endif
      ! case 4, empty group
      if (this%npes == 0 .and. this%nnodes ==0 .and. this%npes_per_node ==0) then
        next_node = start_node
        next_rank = start_rank
      endif
      _RETURN(_SUCCESS)
   end subroutine comm_group_range
Call graph
comm_group_range calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
compute_color calls comm_group_range
split calls compute_color
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls split
new_multigroupserver calls split
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator
main calls initialize, create_member_subcommunicator
run_ensemble calls create_member_subcommunicator
time_ave calls initialize
ut_regridding calls initialize