compute_min_max – MAPL
compute_min_max Subroutine
27 statements
Source File
private subroutine compute_min_max(array, min_value, max_value, undef_value, mpi_comm, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: array(:,:)
real, intent(out) :: min_value
real, intent(out) :: max_value
real, intent(in) :: undef_value
integer, intent(in) :: mpi_comm
integer, intent(out), optional :: rc
Calls
Called by
Call graph
compute_min_max calls mpi_allreduce, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
downbit2d calls compute_min_max
downbit calls downbit2d, downbit1d, downbit3d
downbit1d calls downbit2d
downbit3d calls downbit2d
shavebits calls downbit
stagedata calls downbit
bundlepost calls stagedata
run calls shavebits