compute_lat_corners – MAPL
compute_lat_corners Function
39 statements
Source File
private function compute_lat_corners(this, pole, unusable, rc) result(lat_corners)
Uses
MAPL_Constants
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
character(len=2), intent(in) :: pole
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Source Code
   function compute_lat_corners(this, pole, unusable, rc) result(lat_corners)
      use MAPL_Constants, only: MAPL_DEGREES_TO_RADIANS_R8
      use MAPL_BaseMod
      real(kind=REAL64), allocatable :: lat_corners(:)
      class (LatLonGridFactory), intent(in) :: this
      character(2), intent(in) :: pole
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      real(kind=REAL64) :: delta, min_coord, max_coord
      logical :: regional
      integer :: status
      _UNUSED_DUMMY(unusable)
      allocate(lat_corners(this%jm_world+1))
      regional  = (pole == 'XY')
      if (regional) then
         delta = (this%lat_range%max - this%lat_range%min) / this%jm_world
         min_coord = this%lat_range%min
         max_coord = this%lat_range%max
      else ! global grid
         select case (pole)
         case ('PE')
            delta = 180.d0 / this%jm_world
            min_coord = -90.d0
            max_coord = +90.d0
         case ('PC')
            _ASSERT(this%jm_world > 1, 'degenerate grid')
            delta = 180.d0 / (this%jm_world-1)
            min_coord = -90.d0-delta/2
            max_coord = +90.d0+delta/2
         end select
      end if
      lat_corners = MAPL_Range(min_coord, max_coord, this%jm_world+1, &
           & conversion_factor=MAPL_DEGREES_TO_RADIANS_R8, rc=status)
      if (pole == 'PC') then
         lat_corners(1)=-90.d0*MAPL_DEGREES_TO_RADIANS_R8
         lat_corners(this%jm_world+1)=90.d0*MAPL_DEGREES_TO_RADIANS_R8
      end if
      _RETURN(_SUCCESS)
   end function compute_lat_corners
Call graph
compute_lat_corners calls mapl_assert, mapl_range, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_range_real32 calls mapl_assert, mapl_return
mapl_range_real64 calls mapl_assert, mapl_return
mapl_throw_exception calls initialize
initialize_from_config_with_prefix calls compute_lat_corners
initialize_from_file_metadata calls compute_lat_corners
latlongridfactory_from_parameters calls compute_lat_corners
latlongridfactory calls latlongridfactory_from_parameters