compute_linear_weights – MAPL
compute_linear_weights Subroutine
26 statements
Source File
private subroutine compute_linear_weights(Weight, Xin, Xout, rc)
Arguments
Type Intent Optional Attributes Name
type(Weights), intent(inout) :: Weight(:)
real(kind=REAL32), intent(in) :: Xin(:)
real(kind=REAL32), intent(in) :: Xout(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
compute_linear_weights
Source Code
   subroutine compute_linear_weights(Weight, Xin, Xout, rc)
      type(Weights),  intent(inout) :: Weight(:)
      real(kind=REAL32), intent(in) :: Xin(:)
      real(kind=REAL32), intent(in) :: Xout(:)
      integer, optional, intent(out) :: rc
      ! Compute weights for binned interpolation along a dimension.
      ! Xout are the N_in + 1 input bin edges.
      ! Xin  are the N_out + 1 output bin edges
      ! Weigths are the mapping
      integer :: j_out, j0, j1
      integer :: N_in
      integer :: status
      character(len=*), parameter :: Iam = 'compute_linear_weights'
      N_in  = size(Xin )
      do j_out=1,size(Weight)
         j0 = 1
         do
            if(Xout(j_out  ) <= Xin(j0+1)) exit
            j0=j0+1
            _ASSERT(j0 < N_in, 'index error')
         end do
         j1 = j0 + 1
         allocate(weight(j_out)%f(j0:j1), stat=status)
         _VERIFY(status)
         associate (b => weight(j_out)%f)
           b(j0  ) = (Xin(j1)-Xout(j_out))/(Xin(j1)-Xin(j0))
           b(j0+1) = 1.0 - b(j0)
         end associate
      end do
   end subroutine compute_linear_weights
Call graph
compute_linear_weights calls b, mapl_assert, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
initialize_subclass calls compute_linear_weights