compute_binning_weights – MAPL
compute_binning_weights Subroutine
55 statements
Source File
private subroutine compute_binning_weights(Weight, Xin, Xout, HasPoles, rc)
Arguments
Type Intent Optional Attributes Name
type(Weights), intent(inout) :: Weight(:)
real(kind=REAL32), intent(in) :: Xin(:)
real(kind=REAL32), intent(in) :: Xout(:)
logical, intent(in) :: HasPoles
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
compute_binning_weights
Source Code
  subroutine compute_binning_weights(Weight,Xin,Xout,HasPoles,rc)
    type(Weights),     intent(INOUT) :: Weight(:)
    real(kind=REAL32), intent(IN   ) :: Xin(:), Xout(:)
    logical,           intent(IN   ) :: HasPoles
    integer, optional, intent(OUT  ) :: rc
    ! Compute weights for binned interpolation along a dimension.
    ! Xout are the N_in + 1 input bin edges.
    ! Xin  are the N_out + 1 output bin edges
    ! Weigths are the mapping
    integer :: j_out, j0, j1, j
    integer :: N_in, N_out
    integer :: status
    real    :: dx, ff
    character(len=*), parameter :: Iam = 'compute_binning_weights'
    N_in  = size(Xin )-1
    N_out = size(Weight)
    do j_out=1,N_out
       j0 = 1
       do
          if(Xout(j_out  )>=Xin(j0) .and. Xout(j_out  )<=Xin(j0+1)) exit
          j0=j0+1
          _ASSERT(j0 <= N_in, 'index error')
       end do
       j1 = j0
       do
          if(Xout(j_out+1)>=Xin(j1) .and. Xout(j_out+1)<=Xin(j1+1)) exit
          j1=j1+1
          _ASSERT(j1 <= N_in, 'index error')
       end do
       allocate(weight(j_out)%f(j0:j1), stat=status)
       _VERIFY(status)
       associate (b => weight (j_out)%f)
         if(j0==j1) then
            b(j0) = 1.
         else
            dx    = Xin(j0+1)-Xout(j_out)
            ff    = dx
            b(j0) = dx
            do j=j0+1,j1-1
               dx   = Xin(j+1) - Xin(j)
               ff   = ff + dx
               b(j) = dx
            end do
            dx    = Xout(j_out+1)-Xin(j1)
            ff    = ff + dx
            b(j1) = dx
            b     = b/ff
         end if
       end associate
    end do
    if(HasPoles) then
       deallocate(Weight(    1)%f)
       deallocate(Weight(N_out)%f)
       allocate  (Weight(    1)%f(1   :1   ))
       allocate  (Weight(N_out)%f(N_in:N_in))
       Weight(    1)%f  =  1.
       Weight(N_out)%f  =  1.
    endif
 end subroutine compute_binning_weights
Call graph
compute_binning_weights calls mapl_assert, mapl_verify, b
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
initialize_subclass calls compute_binning_weights