compute_lon_corners – MAPL
compute_lon_corners Function
40 statements
Source File
private function compute_lon_corners(this, dateline, unusable, rc) result(lon_corners)
Uses
MAPL_BaseMod
MAPL_Constants
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
character(len=2), intent(in) :: dateline
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Contents
Source Code
compute_lon_corners
Source Code
   function compute_lon_corners(this, dateline, unusable, rc) result(lon_corners)
      use MAPL_Constants, only:MAPL_DEGREES_TO_RADIANS_R8
      use MAPL_BaseMod
      real(kind=REAL64), allocatable :: lon_corners(:)
      class (LatLonGridFactory), intent(in) :: this
      character(2), intent(in) :: dateline
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      real(kind=REAL64) :: delta, min_coord, max_coord
      logical :: regional
      integer :: status
      _UNUSED_DUMMY(unusable)
      allocate(lon_corners(this%im_world+1))
      regional  = (dateline == 'XY')
      if (regional) then
         delta = (this%lon_range%max - this%lon_range%min) / this%im_world
         min_coord = this%lon_range%min
         max_coord = this%lon_range%max
      else
         delta = 360.d0 / this%im_world
         select case (dateline)
         case ('DC')
            min_coord = -180.d0 - delta/2
            max_coord = +180.d0 - delta/2
         case ('DE')
            min_coord = -180.d0
            max_coord = +180.d0
         case ('GC')
            min_coord = 0.d0-delta/2
            max_coord = 360.d0-delta/2
         case ('GE')
            min_coord = 0.d0
            max_coord = 360.d0 - delta
         end select
      end if
      lon_corners = MAPL_Range(min_coord, max_coord, this%im_world+1, &
           & conversion_factor=MAPL_DEGREES_TO_RADIANS_R8, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function compute_lon_corners
Call graph
compute_lon_corners calls mapl_range, mapl_return, mapl_verify
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_range_real32 calls mapl_return, mapl_assert
mapl_range_real64 calls mapl_return, mapl_assert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
initialize_from_config_with_prefix calls compute_lon_corners
initialize_from_file_metadata calls compute_lon_corners
latlongridfactory_from_parameters calls compute_lon_corners
latlongridfactory calls latlongridfactory_from_parameters