compute_time_for_current – MAPL
compute_time_for_current Module Function
34 statements
Source File
module function compute_time_for_current(this, current_time, rc) result(rtime) Interface →
Uses
MAPL_NetCDF
Arguments
Type Intent Optional Attributes Name
class(MaskSamplerGeosat), intent(inout) :: this
type(ESMF_Time), intent(in) :: current_time
integer, intent(out), optional :: rc
Return Value real(kind=ESMF_KIND_R8)
Calls
Called by
Source Code
  module function compute_time_for_current(this,current_time,rc) result(rtime)
    use  MAPL_NetCDF, only : convert_NetCDF_DateTime_to_ESMF
    class(MaskSamplerGeosat), intent(inout) :: this
    type(ESMF_Time), intent(in) :: current_time
    integer, optional, intent(out) :: rc
    real(kind=ESMF_KIND_R8) :: rtime
    integer :: status
    type(ESMF_TimeInterval) :: t_interval
    class(Variable), pointer :: var
    type(Attribute), pointer :: attr
    class(*), pointer :: pTimeUnits
    character(len=ESMF_MAXSTR) :: datetime_units
    character(len=ESMF_MAXSTR) :: tunit
    type(ESMF_time), allocatable :: esmf_time_1d(:)
    real(kind=ESMF_KIND_R8), allocatable :: rtime_1d(:)
    var => this%metadata%get_variable('time',_RC)
    attr => var%get_attribute('units')
    ptimeUnits => attr%get_value()
    select type(pTimeUnits)
    type is (character(*))
       datetime_units = ptimeUnits
    class default
       _FAIL("Time unit must be character")
    end select
    allocate (  esmf_time_1d(1), rtime_1d(1), _STAT )
    esmf_time_1d(1)= current_time
    call time_ESMF_to_real ( rtime_1d, esmf_time_1d, datetime_units, _RC )
    rtime =  rtime_1d(1)
    _RETURN(_SUCCESS)
  end function compute_time_for_current
Call graph
compute_time_for_current calls mapl_assert, get_attribute, get_value, get_variable, mapl_return, mapl_verify, time_esmf_to_real, compute_time_for_current
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_value calls mapl_return
get_variable calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
time_esmf_to_real calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeIntervalGet, convert_netcdf_datetime_to_esmf
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_esmf_time_from_netcdf_datetime_integer calls mapl_assert, mapl_return, mapl_verify, convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, set_esmf_timeinterval, set_esmf_time_from_iso8601
get_esmf_time_from_netcdf_datetime_real calls mapl_assert, mapl_return, mapl_verify, convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, set_esmf_timeinterval, set_esmf_time_from_iso8601
m_find calls s_find
regrid_append_file calls compute_time_for_current, regrid_append_file