compute_time_for_current – MAPL
compute_time_for_current Function
30 statements
Source File
private function compute_time_for_current(this, current_time, rc) result(rtimes)
Type Bound
StationSampler
Arguments
Type Intent Optional Attributes Name
class(StationSampler), intent(inout) :: this
type(ESMF_Time), intent(in) :: current_time
integer, intent(out), optional :: rc
Return Value real(kind=ESMF_KIND_R8), allocatable, (:)
Calls
Called by
Source Code
  function compute_time_for_current(this,current_time,rc) result(rtimes)
    class(StationSampler), intent(inout) :: this
    type(ESMF_Time), intent(in) :: current_time
    integer, optional, intent(out) :: rc
    real(ESMF_KIND_R8), allocatable :: rtimes(:)
    integer :: status
    type(ESMF_TimeInterval) :: tint
    type(ESMF_Time) :: file_start_time
    character(len=ESMF_MAXSTR) :: tunit
    allocate(rtimes(1),_STAT)
    call this%get_file_start_time(file_start_time,tunit,_RC)
    tint = current_time-file_start_time
    select case(trim(tunit))
    case ('days')
       call ESMF_TimeIntervalGet(tint,d_r8=rtimes(1),_RC)
    case ('hours')
       call ESMF_TimeIntervalGet(tint,h_r8=rtimes(1),_RC)
    case ('minutes')
       call ESMF_TimeIntervalGet(tint,m_r8=rtimes(1),_RC)
    case default
       _FAIL('illegal value for tunit: '//trim(tunit))
    end select
    _RETURN(_SUCCESS)
  end function compute_time_for_current
Call graph
compute_time_for_current calls ESMF_TimeIntervalGet, mapl_assert, get_file_start_time, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file_start_time calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeSet, get_attribute, get_value, get_variable
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_attribute calls mapl_assert, mapl_return, m_at
get_error_message calls at, insert
get_value calls mapl_return
get_variable calls mapl_return, m_at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_at calls m_find
append_file calls compute_time_for_current
run calls append_file