CompletelyEnclosed – MAPL
CompletelyEnclosed Function
20 statements
Source File
private function CompletelyEnclosed(F, b, e) result(res)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: F
integer, intent(in) :: b
integer, intent(in) :: e
Return Value logical
Called by
Contents
Source Code
CompletelyEnclosed
Source Code
  FUNCTION CompletelyEnclosed (F, b, e) RESULT (res)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Check if function substring F(b:e) is completely enclosed by a pair of parenthesis
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    CHARACTER (LEN=*), INTENT(in) :: F                       ! Function substring
    INTEGER,           INTENT(in) :: b,e                     ! First and last pos. of substring
    LOGICAL                       :: res
    INTEGER                       :: j,k
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    res=.false.
    IF (F(b:b) == '(' .AND. F(e:e) == ')') THEN
       k = 0
       DO j=b+1,e-1
          IF     (F(j:j) == '(') THEN
             k = k+1
          ELSEIF (F(j:j) == ')') THEN
             k = k-1
          END IF
          IF (k < 0) EXIT
       END DO
       IF (k == 0) res=.true.                                ! All opened parenthesis closed
    END IF
  END FUNCTION CompletelyEnclosed
Call graph
compilesubstr calls completelyenclosed, compilesubstr
compile calls compilesubstr
parsef calls compile
mapl_stateeval calls parsef