compute_color – MAPL
compute_color Function
46 statements
Source File
private function compute_color(this, unusable, rc) result(color)
Type Bound
SimpleCommSplitter
Arguments
Type Intent Optional Attributes Name
class(SimpleCommSplitter), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function compute_color(this, unusable, rc) result(color)
      class (SimpleCommSplitter), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: shared_communicator
      integer :: ierror
      integer :: color_
      integer :: node_id
      integer :: node_comm, rank_on_node, start_node, start_rank, next_node, next_rank
      integer, allocatable :: node_sizes(:)
      logical :: IamInGroup
      integer :: status
      type (CommGroupDescription), pointer :: group_descr
      integer :: info = MPI_INFO_NULL
      _UNUSED_DUMMY(unusable)
      ! Note that the shared communicator may not be ordered with pe's contiguous
      ! within a node.  Thus, the assignment algorithm must step through
      ! nodes and then through pe's within a node.   Messy - and will probably
      ! never be exercised in the nontrivial case.
      shared_communicator = this%get_shared_communicator()
      call MPI_Comm_split_type(shared_communicator, MPI_COMM_TYPE_SHARED, 0, info, node_comm, ierror)
      _VERIFY(ierror)
      call MPI_Comm_rank(node_comm, rank_on_node, ierror); _VERIFY(ierror)
      node_id = this%get_node_id(rc=status); _VERIFY(status)
      node_sizes = this%get_node_sizes(rc=status); _VERIFY(status)
      color = MPI_UNDEFINED ! unless ...
      start_node = 1
      start_rank = 0
      IamInGroup = .false.
      do color_ = 1, this%group_descriptions%size()
         group_descr => this%group_descriptions%at(color_)
         call group_descr%comm_group_range(node_id, rank_on_node, node_sizes, start_node, start_rank, next_node, next_rank, IamInGroup)
         start_node = next_node
         start_rank = next_rank
         if (IamInGroup) then
            color = color_
            exit
         endif
      enddo
      call Mpi_Comm_free(node_comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
   end function compute_color
Call graph
compute_color calls mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, at, comm_group_range, get_node_id, get_node_sizes, get_shared_communicator, mapl_return, mapl_verify
comm_group_range calls mapl_return, mapl_assert
get_node_id calls mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, get_shared_communicator, mapl_return, mapl_verify, mpi_allgather, mpi_bcast, mpi_comm_size
get_node_sizes calls mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, get_shared_communicator, mapl_return, mapl_verify, mpi_allgather, mpi_comm_size
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
split calls compute_color
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls split
new_multigroupserver calls split
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator, initialize_io_clients_servers
main calls initialize, create_member_subcommunicator, initialize_ioserver
run_ensemble calls create_member_subcommunicator, initialize_io_clients_servers
time_ave calls initialize
ut_regridding calls initialize
run calls run_ensemble, initialize_io_clients_servers
regrid_util calls main