compare_all – MAPL
compare_all Function
11 statements
Source File
private pure function compare_all(astrings, bstrings)
Compare all the strings in two string arrays
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), dimension(:) :: astrings
character(len=*), intent(in), dimension(:) :: bstrings
Return Value logical
Called by
Source Code
   pure function compare_all(astrings, bstrings)
      character(len=*), dimension(:), intent(in) :: astrings
      character(len=*), dimension(:), intent(in) :: bstrings
      logical :: compare_all
      integer :: i
      compare_all = (size(astrings) == size(bstrings))
      do i=1, size(astrings)
         if(.not. compare_all) exit
         compare_all = (trim(astrings(i)) == trim(bstrings(i)))
      end do
   end function compare_all
Call graph
mapl_getresource_config_array calls compare_all
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefrommapl_array
arrdescrsetncpar calls mapl_getresource
capture calls mapl_getresource
get_test_framework_resource calls mapl_getresource
initialize_gc calls mapl_getresource
mapl_clockinit calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource
mapl_esmfstatewritetofile calls mapl_getresource
mapl_genericfinalize calls mapl_getresource
mapl_genericinitialize calls mapl_getresource
mapl_genericrecord calls mapl_getresource
mapl_genericrefresh calls mapl_getresource
mapl_genericstaterestore calls mapl_getresource
mapl_genericstatesave calls mapl_getresource
mapl_genericwrapper calls mapl_getresource
mapl_readforcingx calls mapl_getresource
mapl_staterecord calls mapl_getresource
mapl_staterefresh calls mapl_getresource