compute_doy – MAPL
compute_doy Function
20 statements
Source File
private function compute_doy(time, rc) result(doy)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: time
integer, intent(out), optional :: rc
Return Value real(kind=ESMF_KIND_R8)
Calls
Called by
Contents
Call graph
compute_doy calls ESMF_TimeGet, ESMF_TimeIntervalGet, ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
fillstate calls compute_doy
run_ calls fillstate