CompareState – MAPL
CompareState Subroutine
76 statements
Source File
private subroutine CompareState(State1, State2, tol, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: State1
type(ESMF_State), intent(inout) :: State2
real, intent(in) :: tol
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine CompareState(State1,State2,tol,rc)
      type(ESMF_State), intent(inout) :: State1
      type(ESMF_State), intent(inout) :: State2
      real, intent(in)                :: tol
      integer, optional, intent(out) :: rc
      integer :: status
      integer                             :: i
      real, pointer                       :: ptr3_1(:,:,:)
      real, pointer                       :: ptr3_2(:,:,:)
      real, pointer                       :: ptr2_1(:,:)
      real, pointer                       :: ptr2_2(:,:)
      real, pointer                       :: ptr1_1(:)
      real, pointer                       :: ptr1_2(:)
      integer :: itemcount,rank1,rank2
      character(len=ESMF_MAXSTR), allocatable :: NameList(:)
      logical, allocatable :: foundDiff(:)
      type(ESMF_Field) :: Field1,Field2
      logical :: all_undef1, all_undef2
      call ESMF_StateGet(State1,itemcount=itemCount,_RC)
         allocate(NameList(itemCount),stat=status)
         _VERIFY(status)
         allocate(foundDiff(itemCount),stat=status,source=.false.)
         _VERIFY(status)
         call ESMF_StateGet(State1,itemNameList=NameList,_RC)
         do i=1,itemCount
            call ESMF_StateGet(State1,trim(nameList(i)),field1,_RC)
            call ESMF_StateGet(State2,trim(nameList(i)),field2,_RC)
            call ESMF_FieldGet(field1,rank=rank1,_RC)
            call ESMF_FieldGet(field2,rank=rank2,_RC)
            all_undef1 = FieldIsConstant(field1,MAPL_UNDEF,_RC)
            all_undef2 = FieldIsConstant(field2,MAPL_UNDEF,_RC)
            if (all_undef1 .or. all_undef2) then
               exit
            end if
            _ASSERT(rank1==rank2,'needs informative message')
            foundDiff(i)=.false.
            if (rank1==1) then
               call MAPL_GetPointer(state1,ptr1_1,trim(nameList(i)),_RC)
               call MAPL_GetPointer(state2,ptr1_2,trim(nameList(i)),_RC)
               if (any((ptr1_1-ptr1_2) > tol)) then
                   foundDiff(i) = .true.
               end if
            else if (rank1==2) then
               call MAPL_GetPointer(state1,ptr2_1,trim(nameList(i)),_RC)
               call MAPL_GetPointer(state2,ptr2_2,trim(nameList(i)),_RC)
               if (any((ptr2_1-ptr2_2) > tol)) then
                   foundDiff(i) = .true.
               end if
            else if (rank1==3) then
               call MAPL_GetPointer(state1,ptr3_1,trim(nameList(i)),_RC)
               call MAPL_GetPointer(state2,ptr3_2,trim(nameList(i)),_RC)
               if (any((ptr3_1-ptr3_2) > tol)) then
                   foundDiff(i) = .true.
               end if
            end if
            if (foundDiff(i)) then
               _FAIL('found difference when compare state')
            end if
         enddo
         _RETURN(ESMF_SUCCESS)
      end subroutine CompareState
Call graph
comparestate calls esmf_fieldget, esmf_stateget, esmfl_stategetpointertodata, fieldisconstant, mapl_assert, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
fieldisconstant calls fieldisconstantr4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_stategetptrtodatar4_1 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
fieldisconstantr4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, assign_fptr
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_allocatecoupling calls mapl_allocatecoupling
run_ calls comparestate