Compile – MAPL
Compile Subroutine
48 statements
Source File
private subroutine Compile(Comp, F, Var, field, rc)
Arguments
Type Intent Optional Attributes Name
type(tComp) :: Comp
character(len=*), intent(in) :: F
character(len=*), intent(in), DIMENSION(:) :: Var
type(ESMF_Field), intent(inout) :: field
integer, intent(out) :: rc
Calls
Called by
Contents
Source Code
Compile
Source Code
  SUBROUTINE Compile (Comp, F, Var, field, rc)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Compile i-th function string F into bytecode
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    TYPE (tComp) :: Comp              ! Bytecode
    CHARACTER (LEN=*),               INTENT(in   ) :: F         ! Function string
    CHARACTER (LEN=*), DIMENSION(:), INTENT(in   ) :: Var       ! Array with variable names
    TYPE(ESMF_Field)               , INTENT(inout) :: field     ! resultant field, use to get its rank, etc . . .
    INTEGER                        , INTENT(out  ) :: rc
    INTEGER                                     :: istat, i
    TYPE(ESMF_Array)                            :: Array
    type (ESMF_LocalArray), target        :: larrayList(1)
    TYPE(ESMF_LocalArray) ,pointer        :: lArray
    INTEGER                          :: ResRank
    INTEGER                          :: lb(ESMF_MAXDIM)
    INTEGER                          :: ub(ESMF_MAXDIM)
    character(len=ESMF_MAXSTR), parameter       :: Iam = "Compile"
    integer                                     :: status
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IF (ASSOCIATED(Comp%ByteCode)) DEALLOCATE ( Comp%ByteCode, &
                                                   Comp%Immed,    &
                                                   Comp%Stack     )
    Comp%ByteCodeSize = 0
    Comp%ImmedSize    = 0
    Comp%StackSize    = 0
    Comp%StackPtr     = 0
    CALL CompileSubstr (Comp,F,1,LEN_TRIM(F),Var)               ! Compile string to determine size
    ALLOCATE ( Comp%ByteCode(Comp%ByteCodeSize), &
               Comp%Immed(Comp%ImmedSize),       &
               Comp%Stack(Comp%StackSize),       &
               STAT = istat                      )
    call ESMF_FieldGet(field,array=array,rc=status)
    _VERIFY(STATUS)
    call ESMF_ArrayGet(array,localarrayList=larrayList,rc=status)
    _VERIFY(STATUS)
    lArray => lArrayList(1)
    call ESMF_LocalArrayGet(larray,rank=ResRank,totallbound=lb,totalubound=ub,rc=status)
    _VERIFY(STATUS)
    DO i=1,Comp%StackSize
       Comp%Stack(i)%rank = ResRank
       Comp%Stack(i)%lb = lb
       Comp%Stack(i)%ub = ub
       IF (ResRank == 2) then
          allocate(Comp%Stack(i)%Q2D(lb(1):ub(1),lb(2):ub(2)) )
       ELSE IF (ResRank == 3) then
          allocate(Comp%Stack(i)%Q3D(lb(1):ub(1),lb(2):ub(2),lb(3):ub(3)) )
       END IF
    END DO
    Comp%ByteCodeSize = 0
    Comp%ImmedSize    = 0
    Comp%StackSize    = 0
    Comp%StackPtr     = 0
    CALL CompileSubstr (Comp,F,1,LEN_TRIM(F),Var)            ! Compile string into bytecode
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE Compile
Call graph
compile calls compilesubstr, esmf_arrayget, esmf_fieldget, mapl_verify, esmf_localarrayget, mapl_return
compilesubstr calls compilesubstr, completelyenclosed, isbinaryop, operatorindex, addcompiledbyte, mathfunctionindex, mathitemindex
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mathfunctionindex calls lowcase
mathitemindex calls realnum, checkundef, variableindex
mapl_throw_exception calls initialize
checkundef calls lowcase
parsef calls compile
mapl_stateeval calls parsef
mapl_runexpression calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
calcderivedfield calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
run calls mapl_runexpression
run_ calls fillstate, calcderivedfield