ComputeGridBasis – MAPL
ComputeGridBasis Function
48 statements
Source File
private function ComputeGridBasis(grid, unusable, rc) result(basis)
Uses
MAPL_BaseMod
ESMF
MAPL_KeywordEnforcerMod
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:,:,:,:)
Calls
Called by
Source Code
   function ComputeGridBasis(grid,unusable,rc) result(basis)
      use esmf
      use MAPL_KeywordEnforcerMod
      use MAPL_BaseMod, only : MAPL_GridGetCorners,MAPL_GridGet
      type(ESMF_Grid), intent(inout) :: grid
      real(REAL64), allocatable :: basis(:,:,:,:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam= MOD_NAME // 'computeGridBasis'
      integer :: status
      real(REAL64), allocatable :: corners(:,:,:)
      real(REAL64), pointer :: Xcenters(:,:),Ycenters(:,:)
      real(REAL64) :: p1(2),p2(2),p3(2),p4(2),c1(2)
      integer :: i, j, im, jm, counts(3)
      _UNUSED_DUMMY(unusable)
      call MAPL_GridGet(grid,localCellCountPerDim=counts,rc=status)
      _VERIFY(status)
      im=counts(1)
      jm=counts(2)
      allocate(basis(3,2,im,jm),stat=status)
      _VERIFY(status)
      allocate(corners(im+1,jm+1,2),stat=status)
      _VERIFY(status)
      call MAPL_GridGetCorners(grid,corners(:,:,1),corners(:,:,2),rc=status)
      _VERIFY(status)
      call ESMF_GridGetCoord(grid,localDE=0,coordDim=1,staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=Xcenters, rc=status)
      _VERIFY(status)
      call ESMF_GridGetCoord(grid,localDE=0,coordDim=2,staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=Ycenters, rc=status)
      _VERIFY(status)
      do j=1,jm
         do i=1,im
            p1 = mid_pt_sphere(corners(i,j,:),corners(i,j+1,:))
            p2 = mid_pt_sphere(corners(i,j,:),corners(i+1,j,:))
            p3 = mid_pt_sphere(corners(i+1,j,:),corners(i+1,j+1,:))
            p4 = mid_pt_sphere(corners(i,j+1,:),corners(i+1,j+1,:))
            c1(1) = Xcenters(i,j)
            c1(2) = Ycenters(i,j)
            basis(:,1,i,j) = get_unit_vector(p3, c1, p1)
            basis(:,2,i,j) = get_unit_vector(p4, c1, p2)
         enddo
      enddo
      deallocate(corners)
      _RETURN(_SUCCESS)
   end function ComputeGridBasis
Call graph
computegridbasis calls ESMF_GridGetCoord, mapl_gridgetcorners, get_unit_vector, mapl_gridget, mapl_return, mapl_verify, mid_pt_sphere
mapl_gridgetcorners calls mapl_gridgetcorners, ESMF_GridGetCoord, mapl_gridget, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, ESMF_AttributeSet, ESMF_FieldHalo, ESMF_FieldHaloRelease, ESMF_FieldHaloStore, esmf_fieldcreate, esmf_fielddestroy, mapl_assert
get_unit_vector calls latlon2xyz
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mid_pt_sphere calls latlon2xyz, xyz2latlon
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
get_basis calls computegridbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis
regrid_vector_2d_real32 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_2d_real64 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_3d_real32 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_3d_real64 calls cartesian_to_spherical, spherical_to_cartesian
test_cartesian_to_spherical_x calls cartesian_to_spherical
test_cartesian_to_spherical_y calls cartesian_to_spherical
test_cartesian_to_spherical_z calls cartesian_to_spherical
test_spherical_to_cartesian_east_wind calls spherical_to_cartesian
test_spherical_to_cartesian_north_wind calls spherical_to_cartesian
transpose_regrid_vector_2d_real32 calls cartesian_to_spherical, spherical_to_cartesian
transpose_regrid_vector_3d_real32 calls cartesian_to_spherical, spherical_to_cartesian