compute_lon_centers – MAPL
compute_lon_centers Function
52 statements
Source File
private function compute_lon_centers(this, dateline, unusable, convert_to_radians, rc) result(lon_centers)
Uses
MAPL_Constants
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
character(len=2), intent(in) :: dateline
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: convert_to_radians
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Contents
Source Code
compute_lon_centers
Source Code
   function compute_lon_centers(this, dateline, unusable, convert_to_radians, rc) result(lon_centers)
      use MAPL_Constants, only:MAPL_DEGREES_TO_RADIANS_R8
      use MAPL_BaseMod
      real(kind=REAL64), allocatable :: lon_centers(:)
      class (LatLonGridFactory), intent(in) :: this
      character(2), intent(in) :: dateline
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in)  :: convert_to_radians
      integer, optional, intent(out) :: rc
      real(kind=REAL64) :: delta, min_coord, max_coord
      logical :: local_convert_to_radians
      logical :: regional
      integer :: status
      _UNUSED_DUMMY(unusable)
      if (present(convert_to_radians)) then
         local_convert_to_radians = convert_to_radians
      else
         local_convert_to_radians = .true.
      end if
      allocate(lon_centers(this%im_world))
      regional  = (dateline == 'XY')
      if (regional) then
         delta = (this%lon_range%max - this%lon_range%min) / this%im_world
         min_coord = this%lon_range%min + delta/2
         max_coord = this%lon_range%max - delta/2
      else
         delta = 360.d0 / this%im_world
         select case (dateline)
         case ('DC')
            min_coord = -180.d0
            max_coord = +180.d0 - delta
         case ('DE')
            min_coord = -180.d0 + delta/2
            max_coord = +180.d0 - delta/2
         case ('GC')
            min_coord = 0.d0
            max_coord = 360.d0 - delta
         case ('GE')
            min_coord = delta/2
            max_coord = 360.d0 - delta/2
         end select
      end if
      if (local_convert_to_radians) then
         lon_centers = MAPL_Range(min_coord, max_coord, this%im_world, &
              & conversion_factor=MAPL_DEGREES_TO_RADIANS_R8, rc=status)
         _VERIFY(status)
      else
         lon_centers = MAPL_Range(min_coord, max_coord, this%im_world, rc=status)
         _VERIFY(status)
      end if
      _RETURN(_SUCCESS)
   end function compute_lon_centers
Call graph
compute_lon_centers calls mapl_range, mapl_return, mapl_verify
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_range_real32 calls mapl_return, mapl_assert
mapl_range_real64 calls mapl_return, mapl_assert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
initialize_from_config_with_prefix calls compute_lon_centers
initialize_from_file_metadata calls compute_lon_centers
latlongridfactory_from_parameters calls compute_lon_centers
latlongridfactory calls latlongridfactory_from_parameters