compute_times_for_interval – MAPL
compute_times_for_interval Function
37 statements
Source File
private function compute_times_for_interval(this, interval, rc) result(rtimes)
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(in) :: interval(2)
integer, intent(out), optional :: rc
Return Value real(kind=ESMF_KIND_R8), allocatable, (:)
Calls
Contents
Source Code
compute_times_for_interval
Source Code
      function compute_times_for_interval(this,interval,rc) result(rtimes)
         class(HistoryTrajectory), intent(inout) :: this
         integer, intent(in) :: interval(2)
         integer, optional, intent(out) :: rc
         real(ESMF_KIND_R8), allocatable :: rtimes(:)
         integer :: ntimes,i,status,icnt
         type(ESMF_TimeInterval) :: tint
         type(ESMF_Time) :: file_start_time
         character(len=ESMF_MAXSTR) :: tunits
         ntimes = interval(2)-interval(1)+1
         if (all(interval==0)) then
            _RETURN(_SUCCESS)
         end if
         call this%get_file_start_time(file_start_time,tunits,_RC)
         allocate(rtimes(ntimes),_STAT)
         icnt=0
         do i=interval(1),interval(2)
            icnt=icnt+1
            tint = this%times(i)-file_start_time
            select case(trim(tunits))
            case ('days')
              call ESMF_TimeIntervalGet(tint,d_r8=rtimes(icnt),_RC)
            case ('hours')
              call ESMF_TimeIntervalGet(tint,h_r8=rtimes(icnt),_RC)
            case ('minutes')
              call ESMF_TimeIntervalGet(tint,m_r8=rtimes(icnt),_RC)
            end select
         enddo
         _RETURN(_SUCCESS)
      end function compute_times_for_interval
Call graph
compute_times_for_interval calls mapl_return, mapl_verify, esmf_timeintervalget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize