ComputeXYZBasis – MAPL
ComputeXYZBasis Function
30 statements
Source File
private function ComputeXYZBasis(grid_basis, unusable, rc) result(basis)
Uses
ESMF
MAPL_KeywordEnforcerMod
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: grid_basis(:,:,:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:,:,:,:)
Calls
Called by
Source Code
   function ComputeXYZBasis(grid_basis,unusable,rc) result(basis)
      use esmf
      use MAPL_KeywordEnforcerMod
      real(REAL64), intent(in) :: grid_basis(:,:,:,:)
      real(REAL64), allocatable :: basis(:,:,:,:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam= MOD_NAME // 'computeXYZBasis'
      integer :: status
      integer :: im, jm, i, j
      real(real64) :: dp,fac
      _UNUSED_DUMMY(unusable)
      im = size(grid_basis,3)
      jm = size(grid_basis,4)
      allocate(basis(3,2,im,jm),stat=status)
      _VERIFY(status)
      do j=1,jm
         do i=1,im
            dp = dot_product(grid_basis(:,1,i,j),grid_basis(:,2,i,j))
            fac = 1.0d0/(dp**2-1.0d0)
            basis(:,1,i,j)=fac*(grid_basis(:,2,i,j)*dp-grid_basis(:,1,i,j))
            basis(:,2,i,j)=fac*(grid_basis(:,1,i,j)*dp-grid_basis(:,2,i,j))
         enddo
      enddo
      _RETURN(_SUCCESS)
   end function ComputeXYZBasis
Call graph
computexyzbasis calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_basis calls computexyzbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis
regrid_vector_2d_real32 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_2d_real64 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_3d_real32 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_3d_real64 calls cartesian_to_spherical, spherical_to_cartesian
test_cartesian_to_spherical_x calls cartesian_to_spherical
test_cartesian_to_spherical_y calls cartesian_to_spherical
test_cartesian_to_spherical_z calls cartesian_to_spherical
test_spherical_to_cartesian_east_wind calls spherical_to_cartesian
test_spherical_to_cartesian_north_wind calls spherical_to_cartesian
transpose_regrid_vector_2d_real32 calls cartesian_to_spherical, spherical_to_cartesian
transpose_regrid_vector_3d_real32 calls cartesian_to_spherical, spherical_to_cartesian