confirm_imports_for_vregrid – MAPL
confirm_imports_for_vregrid Subroutine
27 statements
Source File
private subroutine confirm_imports_for_vregrid(primary_exports, import_state, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExports), intent(in) :: primary_exports
type(ESMF_State), intent(in) :: import_state
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine confirm_imports_for_vregrid(primary_exports, import_state, rc)
     type(PrimaryExports), intent(in) :: primary_exports
     type(ESMF_State), intent(in) :: import_state
     integer, intent(out), optional :: rc
     integer :: status, i, num_items
     logical :: found_allowed
     type(PrimaryExport), pointer      :: item
     character(len=*), parameter :: PLE_IMPORT = 'PLE'
     ! for now only required import is PLE, but this will grow, hence array
     character(len=3), parameter :: required_imports(1) = [character(len=3) :: &
          PLE_IMPORT]
     type(ESMF_StateItem_Flag) :: item_type
     found_allowed = .false.
     num_items = primary_exports%item_vec%size()
     do i=1,num_items
        item => primary_exports%item_Vec%at(i)
        found_allowed = item%allow_vertical_regrid
        if (found_allowed) exit
     end do
     if (found_allowed) then
        do i=1,size(required_imports)
           call ESMF_StateGet(import_state, required_imports(i), item_type, _RC)
           _ASSERT(item_type == ESMF_STATEITEM_FIELD, "Vertically regridding in extdata is allowed but required import "//trim(required_imports(i))//" not present, modify cap to import PLE")
        enddo
     end if
     _RETURN(_SUCCESS)
  end subroutine confirm_imports_for_vregrid
Call graph
confirm_imports_for_vregrid calls esmf_stateget, mapl_assert, at, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_ calls confirm_imports_for_vregrid