config_accumulate – MAPL
config_accumulate Subroutine
12 statements
Source File
private subroutine config_accumulate(this, key, cf, rc)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
character(len=*), intent(in) :: key
type(ESMF_Config), intent(in) :: cf
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine config_accumulate (this, key, cf, rc)
    class(samplerHQ)  :: this
    type(ESMF_Config), intent(in) :: cf
    character(len=*) , intent(in) :: key
    integer, intent(out), optional :: rc
    integer :: status
    this%ngrid = this%ngrid + 1
    this%CF_loc(this%ngrid)%key = trim(key)
    this%CF_loc(this%ngrid)%cf = cf
    _RETURN(_SUCCESS)
  end subroutine config_accumulate
Call graph
config_accumulate calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize calls config_accumulate