connect_to_client – MAPL
connect_to_client Subroutine
117 statements
Source File
private subroutine connect_to_client(this, port_name, server, rc)
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(inout), target :: this
character(len=*), intent(in) :: port_name
class(BaseServer), intent(inout), target :: server
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine connect_to_client(this, port_name, server, rc)
      class (DirectoryService), target, intent(inout) :: this
      character(*), intent(in) :: port_name
      class (BaseServer), target, intent(inout) :: server
      integer, optional, intent(out) :: rc
      class (AbstractSocket), pointer :: sckt
      type (Directory) :: dir
      integer, allocatable :: counts(:), displs(:)
      integer :: client_rank
      integer :: client_root_rank
      integer, allocatable :: client_ranks(:)
      integer, allocatable :: my_client_ranks(:)
      integer, allocatable :: server_ranks(:)
      integer, allocatable :: my_server_ranks(:)
      integer :: status(MPI_STATUS_SIZE)
      integer :: p
      integer :: server_comm
      integer :: ierror
      logical :: found
      integer :: server_npes
      integer :: client_npes
      integer :: rank_in_server
      integer :: n
      integer :: cnts
      integer :: n_entries
      server%terminate  = .false.
      server_comm = MPI_COMM_NULL
      server_comm = server%get_communicator()
      if (server_comm == MPI_COMM_NULL) then
         _RETURN(_SUCCESS)
      endif
      call MPI_Comm_rank(server_comm, rank_in_server, ierror)
      _VERIFY(ierror)
      if (rank_in_server == 0) then
         call this%mutex%acquire()
         dir = this%get_directory(this%win_client_directory)
         client_root_rank = -1
         found = .false.
         n_entries = dir%num_entries
         do n = 1, n_entries
            if (port_name == dir%entries(n)%port_name) then
               found = .true.
               client_root_rank =  dir%entries(n)%partner_root_rank
               exit
            end if
         end do
         if (found) then
            ! Clear entry
            dir%entries(n:n_entries-1) = dir%entries(n+1:n_entries)
            dir%entries(n_entries)%port_name = ''
            dir%entries(n_entries)%partner_root_rank = -1
            dir%num_entries = n_entries - 1
            call this%put_directory(dir, this%win_client_directory)
         end if
         call this%mutex%release()
         if (found) then
            call MPI_Send(this%rank, 1, MPI_INTEGER, client_root_rank, DISCOVERY_TAG, this%comm, ierror)
         else
            call MPI_Recv(client_root_rank, 1, MPI_INTEGER, MPI_ANY_SOURCE, DISCOVERY_TAG, this%comm, status, ierror)
         end if
         _VERIFY(ierror)
         if (client_root_rank /= TERMINATE) then ! not a termination signal
            call MPI_Recv(client_npes, 1, MPI_INTEGER, client_root_rank, NPES_TAG, this%comm, status, ierror)
            _VERIFY(ierror)
            allocate(client_ranks(client_npes))
            call MPI_Recv(client_ranks, client_npes, MPI_INTEGER, client_root_rank, RANKS_TAG, this%comm, status, ierror)
            _VERIFY(ierror)
         else
            client_npes = TERMINATE
         end if
      end if
      call MPI_Comm_size(server_comm, server_npes, ierror)
      _VERIFY(ierror)
      call MPI_Bcast(client_npes, 1, MPI_INTEGER, 0, server_comm, ierror)
      _VERIFY(ierror)
      if (client_npes == TERMINATE) then
        server%terminate = .true.
        _RETURN(_SUCCESS)
      endif
      allocate(counts(0:server_npes-1), displs(0:server_npes-1))
      do p = 0, server_npes - 1
         counts(p) = ((p+1)*client_npes) / server_npes - (p*client_npes) / server_npes
      end do
      displs(0) = 0
      do p = 1, server_npes-1
         displs(p) = displs(p-1) + counts(p-1)
      end do
      cnts = counts(rank_in_server)
      allocate(my_client_ranks(cnts))
      allocate(server_ranks(client_npes))
      allocate(my_server_ranks(cnts))
      my_server_ranks = this%rank
      call MPI_GatherV(my_server_ranks, cnts, MPI_INTEGER, &
           & server_ranks, counts, displs, MPI_INTEGER, &
           & 0, server_comm, ierror)
      _VERIFY(ierror)
      if (rank_in_server == 0) then
        call MPI_Send(server_ranks, client_npes, MPI_INTEGER, client_root_rank, 0, this%comm, ierror)
        _VERIFY(ierror)
        call MPI_Send(server_npes,   1,          MPI_INTEGER, client_root_rank, 0, this%comm, ierror)
        _VERIFY(ierror)
      endif
      if (rank_in_server /= 0) then
         allocate(client_ranks(1))
      end if
      call MPI_ScatterV(client_ranks, counts, displs, MPI_INTEGER, &
           & my_client_ranks, cnts, MPI_INTEGER, &
           & 0, server_comm, ierror)
      _VERIFY(ierror)
      do p = 1, cnts
         client_rank = my_client_ranks(p)
         call MPI_Send(this%rank, 1, MPI_INTEGER, client_rank, CONNECT_TAG, this%comm, ierror)
         _VERIFY(ierror)
         allocate(sckt, source=MpiSocket(this%comm, client_rank, this%parser))
         call server%add_connection(sckt)
         nullify(sckt)
      end do
      _RETURN(_SUCCESS)
   end subroutine connect_to_client
Call graph
connect_to_client calls mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_gatherv, mpi_recv, mpi_scatterv, mpi_send, acquire, add_connection, get_communicator, get_directory, mapl_return, mapl_verify, put_directory, release
acquire calls mpi_recv, mapl_verify, mpi_get, mpi_put, mpi_win_lock, mpi_win_unlock
add_connection calls set_rank, v_push_back
get_directory calls mapl_verify, mpi_get, mpi_win_lock, mpi_win_unlock, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_directory calls mapl_verify, mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
release calls mpi_send, mapl_verify, mpi_get, mpi_put, mpi_win_lock, mpi_win_unlock
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_push_back calls resize, v_grow_to
initialize calls connect_to_client
test_connect calls connect_to_client
test_connect_multi calls connect_to_client
test_connect_swap_role calls connect_to_client
test_connect_with_unused_process calls connect_to_client
test_stress calls connect_to_client
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run