connect_to_server – MAPL
connect_to_server Subroutine
115 statements
Source File
private subroutine connect_to_server(this, port_name, client, client_comm, unusable, server_size, rc)
Uses
pFIO_ClientThreadMod
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(inout), target :: this
character(len=*), intent(in) :: port_name
class(ClientThread), intent(inout), target :: client
integer, intent(in) :: client_comm
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: server_size
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine connect_to_server(this, port_name, client, client_comm, unusable, server_size, rc)
      use pFIO_ClientThreadMod
      class (DirectoryService), target, intent(inout) :: this
      character(*), intent(in) :: port_name
      class (ClientThread), target, intent(inout) :: client
      integer, intent(in) :: client_comm
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: server_size
      integer, optional, intent(out) :: rc
      class (AbstractSocket), pointer :: sckt
      integer :: rank_in_client
      integer :: ierror
      integer :: status(MPI_STATUS_SIZE)
      type (Directory) :: dir
      type (DirectoryEntry) :: dir_entry
      logical :: found
      integer :: n
      integer :: server_rank
      integer :: tmp_rank
      integer :: server_root_rank
      integer :: client_npes
      integer :: server_npes
      integer, allocatable :: client_ranks(:)
      integer, allocatable :: server_ranks(:)
      class(ServerThread), pointer :: server_thread_ptr
      class(BaseServer), pointer :: server_ptr
      type(SimpleSocket), target :: ss
      ! First, check ports to see if server is local, in which case
      ! a SimpleSocket is used for the connection.
      ! Note: In this scenario, the server _must_ always publish prior to this.
      do n = 1, this%n_local_ports
         if (trim(this%local_ports(n)%port_name) == port_name) then
            ss = SimpleSocket(client)
            allocate(sckt, source=ss)
            server_ptr => this%local_ports(n)%server_ptr
            call server_ptr%add_connection(sckt)
            server_thread_ptr => server_ptr%threads%at(1) ! should be "last"
            ss = SimpleSocket(server_thread_ptr)
            allocate(sckt, source=ss)
            call client%set_connection(sckt)
            nullify(sckt)
            if (present(server_size)) server_size = server_ptr%npes
            allocate(server_ptr%serverthread_done_msgs(1))
            server_ptr%serverthread_done_msgs = .false.
            _RETURN(_SUCCESS)
         end if
      end do
      call MPI_Comm_rank(client_comm, rank_in_client, ierror)
      _VERIFY(ierror)
      if (rank_in_client == 0) then
         call this%mutex%acquire()
         dir = this%get_directory(this%win_server_directory)
         found = .false.
         do n = 1, dir%num_entries
            if (port_name == dir%entries(n)%port_name) then
               if (dir%entries(n)%partner_root_rank >= 0) then
                  found = .true.
                  server_root_rank =  dir%entries(n)%partner_root_rank
               end if
               exit
            end if
         end do
         if (.not. found) then  ! advertise self
            dir = this%get_directory(this%win_client_directory)
            n = dir%num_entries + 1
            dir%num_entries = n
            dir_entry%port_name = port_name
            call MPI_Comm_rank(this%comm, dir_entry%partner_root_rank, ierror) ! global comm
            _VERIFY(ierror)
            dir%entries(n) = dir_entry
            call this%put_directory(dir, this%win_client_directory)
         end if
         call this%mutex%release()
         if (found) then
            call MPI_Send(this%rank, 1, MPI_INTEGER, server_root_rank, DISCOVERY_TAG, this%comm, ierror)
         else
            call MPI_Recv(server_root_rank, 1, MPI_INTEGER, MPI_ANY_SOURCE, DISCOVERY_TAG, this%comm, status, ierror)
         end if
         _VERIFY(ierror)
      end if
      ! complete handshake
      if (rank_in_client == 0) then
         call MPI_Comm_size(client_comm, client_npes, ierror)
         _VERIFY(ierror)
         allocate(client_ranks(client_npes))
         allocate(server_ranks(client_npes))
      else
         allocate(client_ranks(1)) ! MPI does not like 0-sized arrays, even when they are unused
         allocate(server_ranks(1)) ! MPI does not like 0-sized arrays, even when they are unused
      end if
      call MPI_Gather(this%rank, 1, MPI_INTEGER, client_ranks, 1, MPI_INTEGER, 0, client_comm, ierror)
      _VERIFY(ierror)
      if (rank_in_client == 0) then
         call MPI_Send(client_npes, 1, MPI_INTEGER, server_root_rank, NPES_TAG, this%comm, ierror)
         _VERIFY(ierror)
         call MPI_Send(client_ranks, client_npes, MPI_INTEGER, server_root_rank, RANKS_TAG, this%comm, ierror)
         _VERIFY(ierror)
         call MPI_Recv(server_ranks, client_npes, MPI_INTEGER, server_root_rank, 0, this%comm, status, ierror)
         _VERIFY(ierror)
         call MPI_Recv(server_npes, 1, MPI_INTEGER, server_root_rank, 0, this%comm, status, ierror)
         _VERIFY(ierror)
         if (present(server_size)) server_size = server_npes
      end if
      call MPI_Scatter(server_ranks, 1, MPI_INTEGER, &
        & server_rank, 1, MPI_INTEGER, &
        & 0, client_comm, ierror)
      _VERIFY(ierror)
      if (present(server_size)) call MPI_Bcast(server_size, 1, MPI_INTEGER, 0, client_comm,ierror)
      ! Construct the connection
      call MPI_Recv(tmp_rank, 1, MPI_INTEGER, server_rank, CONNECT_TAG, this%comm, status, ierror)
      _VERIFY(ierror)
      _ASSERT(tmp_rank == server_rank, "shake the wrong hand")
      allocate(sckt, source=MpiSocket(this%comm, server_rank, this%parser))
      call client%set_connection(sckt)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine connect_to_server
Call graph
connect_to_server calls mapl_assert, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_gather, mpi_recv, mpi_scatter, mpi_send, at, acquire, add_connection, get_directory, mapl_return, mapl_verify, put_directory, release, set_connection
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
acquire calls mpi_recv, mapl_verify, mpi_get, mpi_put, mpi_win_lock, mpi_win_unlock
add_connection calls set_rank, v_push_back
get_directory calls mapl_verify, mpi_get, mpi_win_lock, mpi_win_unlock, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_directory calls mapl_verify, mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
release calls mpi_send, mapl_verify, mpi_get, mpi_put, mpi_win_lock, mpi_win_unlock
set_connection calls mapl_return
initialize calls connect_to_server
test_connect calls connect_to_server
test_connect_multi calls connect_to_server
test_connect_swap_role calls connect_to_server
test_connect_with_unused_process calls connect_to_server
test_stress calls connect_to_server
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run