construct_ISO8601DateTime – MAPL
construct_ISO8601DateTime Function
19 statements
Source File
public function construct_ISO8601DateTime(isostring, rc) result(datetime)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(inout), optional :: rc
Return Value type(ISO8601DateTime)
Calls
Called by
Contents
Source Code
construct_ISO8601DateTime
Source Code
   function construct_ISO8601DateTime(isostring, rc) result(datetime)
      character(len=*), intent(in) :: isostring
      integer, optional, intent(inout) :: rc
      type(ISO8601DateTime) :: datetime
      character, parameter :: DELIMITER = TIME_PREFIX
      integer :: status
      integer :: time_index = 0
      time_index = index(isostring,TIME_PREFIX)
      if(time_index > 0) then
         datetime%date_ = ISO8601Date(isostring(1:time_index-1), _RC)
         datetime%time_ = ISO8601Time(isostring(time_index:len(isostring)), _RC)
         _RETURN(_SUCCESS)
      else
         _FAIL('Invalid ISO 8601 datetime string')
      end if
   end function construct_ISO8601DateTime
Call graph
construct_iso8601datetime calls iso8601date, iso8601time, mapl_assert, mapl_return, mapl_verify
iso8601date calls construct_iso8601date
iso8601time calls construct_iso8601time
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
construct_iso8601date calls mapl_assert, parse_date
construct_iso8601time calls mapl_assert, mapl_return, parse_time
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_date calls is_valid_date, read_whole_number, undelimit
parse_time calls time_fields, is_valid_time, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
iso8601datetime calls construct_iso8601datetime
test_construct_iso8601datetime calls construct_iso8601datetime
convert_iso8601_to_esmf_time calls iso8601datetime