construct_unit – MAPL
construct_unit Function
14 statements
Source File
private function construct_unit(identifier) result(instance)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: identifier
Return Value type(UDUnit)
Calls
Called by
Source Code
   function construct_unit(identifier) result(instance)
      type(UDUnit) :: instance
      character(len=*), intent(in) :: identifier
      character(kind=c_char, len=:), allocatable :: cchar_identifier
      type(c_ptr) :: utunit1
      ! Unit system must be initialized (instantiated).
      if(instance_is_uninitialized()) return
      cchar_identifier = cstring(identifier)
      utunit1 = ut_parse(SYSTEM_INSTANCE%get_cptr(), cchar_identifier, SYSTEM_INSTANCE%encoding)
      if(success(ut_get_status())) then
         call instance%set_cptr(utunit1)
      else
         ! Free memory in the case of failure
         if(c_associated(utunit1)) call ut_free(utunit1)
      end if
   end function construct_unit
Call graph
construct_unit calls ut_free, ut_get_status, ut_parse, cstring, get_cptr, instance_is_uninitialized, set_cptr, success
instance_is_uninitialized calls is_free
udunit calls construct_unit