construct_ISO8601Date – MAPL
construct_ISO8601Date Function
14 statements
Source File
public function construct_ISO8601Date(isostring, rc) result(date)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(out) :: rc
Return Value type(ISO8601Date)
Calls
Called by
Contents
Source Code
construct_ISO8601Date
Source Code
   function construct_ISO8601Date(isostring, rc) result(date)
      character(len=*), intent(in) :: isostring
      integer, intent(out) :: rc
      type(ISO8601Date) :: date
      type(date_fields) :: fields
      fields = parse_date(trim(adjustl(isostring)))
      if(fields%is_valid_) then
         date%year_ = fields%year_
         date%month_ = fields%month_
         date%day_ = fields%day_
      else
         _FAIL('Invalid ISO 8601 date string')
      end if
   end function construct_ISO8601Date
Call graph
construct_iso8601date calls mapl_assert, parse_date
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
parse_date calls is_valid_date, read_whole_number, undelimit
is_valid_date calls get_month_end, is_between, is_valid_month, is_valid_year
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
read_whole_number calls read_whole_number_indexed
get_error_message calls at
get_month_end calls get_month_ends
is_valid_month calls is_between
is_valid_year calls is_between
mapl_throw_exception calls initialize
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
iso8601date calls construct_iso8601date
construct_iso8601datetime calls iso8601date
convert_iso8601_to_integer_date calls iso8601date
test_construct_iso8601date calls iso8601date
test_iso8601datetime_getters calls iso8601date
iso8601datetime calls construct_iso8601datetime
test_construct_iso8601datetime calls construct_iso8601datetime
test_convert_iso8601_to_integer_date calls convert_iso8601_to_integer_date
convert_iso8601_to_esmf_time calls iso8601datetime