construct_ISO8601Time – MAPL
construct_ISO8601Time Function
18 statements
Source File
public function construct_ISO8601Time(isostring, rc) result(time)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(inout) :: rc
Return Value type(ISO8601Time)
Calls
Called by
Contents
Source Code
construct_ISO8601Time
Source Code
   function construct_ISO8601Time(isostring, rc) result(time)
      character(len=*), intent(in) :: isostring
      integer, intent(inout) :: rc
      type(ISO8601Time) :: time
      type(time_fields) :: fields
      fields = parse_time(trim(adjustl(isostring)))
      if(fields%is_valid_) then
         time%hour_ = fields%hour_
         time%minute_ = fields%minute_
         time%second_ = fields%second_
         time%millisecond_ = fields%millisecond_
         time%timezone_offset_ = fields%timezone_offset_
         _RETURN(_SUCCESS)
      else
         _FAIL('Invalid ISO 8601 time string')
      end if
   end function construct_ISO8601Time
Call graph
construct_iso8601time calls mapl_assert, mapl_return, parse_time
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
parse_time calls time_fields, is_valid_time, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
time_fields calls construct_time_fields
get_error_message calls at
is_valid_time calls is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
is_valid_hour calls is_between
is_valid_millisecond calls is_between
is_valid_minute calls is_between
is_valid_second calls is_between
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time
construct_iso8601datetime calls iso8601time
convert_iso8601_to_integer_time calls iso8601time
test_iso8601datetime_getters calls iso8601time
iso8601datetime calls construct_iso8601datetime
test_construct_iso8601datetime calls construct_iso8601datetime
test_convert_iso8601_to_integer_time calls convert_iso8601_to_integer_time
convert_iso8601_to_esmf_time calls iso8601datetime