construct_converter – MAPL
construct_converter Function
15 statements
Source File
private function construct_converter(from_unit, to_unit) result(conv)
Arguments
Type Intent Optional Attributes Name
type(UDUnit), intent(in) :: from_unit
type(UDUnit), intent(in) :: to_unit
Return Value type(Converter)
Calls
Called by
Source Code
   function construct_converter(from_unit, to_unit) result(conv)
      type(Converter) :: conv
      type(UDUnit), intent(in) :: from_unit
      type(UDUnit), intent(in) :: to_unit
      type(c_ptr) :: cvconverter1
      logical :: convertible
      ! Must supply units that are initialized and convertible
      if(from_unit%is_free() .or. to_unit%is_free()) return
      if(.not. are_convertible(from_unit, to_unit)) return
      cvconverter1 = ut_get_converter(from_unit%get_cptr(), to_unit%get_cptr())
      if(success(ut_get_status())) then
         call conv%set_cptr(cvconverter1)
      else
         ! Free memory in the case of failure
         if(c_associated(cvconverter1)) call cv_free(cvconverter1)
      end if
   end function construct_converter
Call graph
construct_converter calls are_convertible, cv_free, ut_get_converter, ut_get_status, get_cptr, is_free, set_cptr, success
are_convertible calls are_convertible_str, are_convertible_udunit
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_get_status, get_cptr, success, ut_are_convertible
converter calls construct_converter