construct_time_fields – MAPL
construct_time_fields Function
13 statements
Source File
public pure function construct_time_fields(hour, minute, second, millisecond, timezone_offset) result(fields)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: hour
integer, intent(in) :: minute
integer, intent(in) :: second
integer, intent(in) :: millisecond
integer, intent(in) :: timezone_offset
Return Value type(time_fields)
Called by
Contents
Source Code
construct_time_fields
Source Code
   pure function construct_time_fields(hour, minute, second, millisecond, &
      timezone_offset) result(fields)
      integer, intent(in) :: hour
      integer, intent(in) :: minute
      integer, intent(in) :: second
      integer, intent(in) :: millisecond
      integer, intent(in) :: timezone_offset
      type(time_fields) :: fields
      fields%hour_ = hour
      fields%minute_ = minute
      fields%second_ = second
      fields%millisecond_ = millisecond
      fields%timezone_offset_ = timezone_offset
   end function construct_time_fields
Call graph
time_fields calls construct_time_fields
parse_time calls time_fields
test_is_valid_time calls time_fields
construct_iso8601time calls parse_time
test_parse_time calls parse_time
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time