construct_date_fields_default – MAPL
construct_date_fields_default Function
10 statements
Source File
public pure function construct_date_fields_default(year, month, day) result(fields)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: day
Return Value type(date_fields)
Calls
Called by
Contents
Source Code
construct_date_fields_default
Source Code
   pure function construct_date_fields_default(year, month, day) result(fields)
      integer, intent(in) :: year
      integer, intent(in) :: month
      integer, intent(in) :: day
      type(date_fields) :: fields
      fields%year_ = year
      fields%month_ = month
      fields%day_ = day
      fields%is_valid_ = is_valid_date(fields)
   end function construct_date_fields_default
Call graph
construct_date_fields_default calls is_valid_date
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
is_valid_day calls get_month_end
get_month_end calls get_month_ends
date_fields calls construct_date_fields_default, construct_date_fields_string
parse_date calls date_fields
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields
construct_date_fields_string calls parse_date
test_parse_date calls parse_date