convert_ISO8601_to_esmf_time – MAPL
convert_ISO8601_to_esmf_time Function
13 statements
Source File
public function convert_ISO8601_to_esmf_time(isostring, rc) result(time)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Source Code
   function convert_ISO8601_to_esmf_time(isostring, rc) result(time)
      character(len=*), intent(in) :: isostring
      integer, optional, intent(out) :: rc
      type(ESMF_Time) :: time
      type(ISO8601DateTime) :: datetime
      integer :: status
      datetime = ISO8601DateTime(isostring, _RC)
      call ESMF_TimeSet(time,yy = datetime%get_year(), mm = datetime%get_month(), &
         dd = datetime%get_day(), h = datetime%get_hour(), m = datetime%get_minute(), &
         s= datetime%get_second(), _RC)
      _RETURN(_SUCCESS)
   end function convert_ISO8601_to_esmf_time
Call graph
convert_iso8601_to_esmf_time calls ESMF_TimeSet, get_day_datetime, get_hour_datetime, get_minute_datetime, get_month_datetime, get_second_datetime, get_year_datetime, mapl_return, mapl_verify
get_day_datetime calls get_day
get_hour_datetime calls get_hour
get_minute_datetime calls get_minute
get_month_datetime calls get_month
get_second_datetime calls get_second
get_year_datetime calls get_year
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize