convert_ESMF_Time_to_NetCDF_DateTimeString – MAPL
convert_ESMF_Time_to_NetCDF_DateTimeString Subroutine
38 statements
Source File
public subroutine convert_ESMF_Time_to_NetCDF_DateTimeString(esmf_datetime, datetime_string, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: esmf_datetime
character(len=:), intent(out), allocatable :: datetime_string
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_ESMF_Time_to_NetCDF_DateTimeString
Source Code
   subroutine convert_ESMF_Time_to_NetCDF_DateTimeString(esmf_datetime, datetime_string, unusable, rc)
      type(ESMF_Time), intent(inout) :: esmf_datetime
      character(len=:), allocatable, intent(out) :: datetime_string
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: ERR_PRE = 'Failed to write string: '
      integer :: yy, mm, dd, h, m, s
      character(len=10) :: FMT
      character(len=4) :: yy_string
      character(len=2) :: mm_string
      character(len=2) :: dd_string
      character(len=2) :: h_string
      character(len=2) :: m_string
      character(len=2) :: s_string
      character(len=LEN_NETCDF_DATETIME) :: tmp_string
      integer :: status, iostatus
      _UNUSED_DUMMY(unusable)
      call ESMF_TimeGet(esmf_datetime, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
      FMT='(BZ, I2.2)'
      write(s_string, fmt=FMT, iostat=iostatus) s
      _ASSERT(iostatus == 0, ERR_PRE // 'second')
      write(m_string, fmt=FMT, iostat=iostatus) m
      _ASSERT(iostatus == 0, ERR_PRE // 'minute')
      write(h_string, fmt=FMT, iostat=iostatus) h
      _ASSERT(iostatus == 0, ERR_PRE // 'hour')
      write(dd_string, fmt=FMT, iostat=iostatus) dd
      _ASSERT(iostatus == 0, ERR_PRE // 'day')
      write(mm_string, fmt=FMT, iostat=iostatus) mm
      _ASSERT(iostatus == 0, ERR_PRE // 'month')
      FMT='(BZ, I4.4)'
      write(yy_string, fmt=FMT, iostat=iostatus) yy
      _ASSERT(iostatus == 0, ERR_PRE // 'year')
      tmp_string = yy_string // DATE_DELIM // mm_string // DATE_DELIM // dd_string // PART_DELIM // &
         h_string // TIME_DELIM // m_string // TIME_DELIM // s_string
      datetime_string = tmp_string
      _RETURN(_SUCCESS)
   end subroutine convert_ESMF_Time_to_NetCDF_DateTimeString
Call graph
convert_esmf_time_to_netcdf_datetimestring calls ESMF_TimeGet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
make_netcdf_datetime_units_string calls convert_esmf_time_to_netcdf_datetimestring
test_convert_esmf_time_to_netcdf_datetimestring calls convert_esmf_time_to_netcdf_datetimestring
convert_esmf_to_netcdf_datetime calls make_netcdf_datetime_units_string
test_make_netcdf_datetime_units_string calls make_netcdf_datetime_units_string
test_convert_esmf_to_netcdf_datetime calls convert_esmf_to_netcdf_datetime