convert_twostring_2_esmfinterval – MAPL
convert_twostring_2_esmfinterval Subroutine
17 statements
Source File
public subroutine convert_twostring_2_esmfinterval(symd, shms, interval, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: symd
character(len=*) :: shms
type(ESMF_TimeInterval), intent(out) :: interval
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine convert_twostring_2_esmfinterval(symd, shms, interval, rc)
    character(len=*) :: symd
    character(len=*) :: shms
    type(ESMF_TimeInterval), intent(out) :: interval
    integer, optional, intent(out) :: rc
    character(len=20) :: s1, s2
    integer :: y, m, d, hh, mm, ss
    integer :: status
    s1=trim(symd)
    read(s1, '(3i2)') y, m, d
    s2=trim(shms)
    read(s2, '(3i2)') hh, mm, ss
    call ESMF_TimeIntervalSet(interval, yy=y, mm=m, d=d, h=hh, m=mm, s=ss, _RC)
    _RETURN(_SUCCESS)
  end subroutine convert_twostring_2_esmfinterval
Call graph
convert_twostring_2_esmfinterval calls ESMF_TimeIntervalSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
historytrajectory_from_config calls convert_twostring_2_esmfinterval
initialize_from_config_with_prefix calls convert_twostring_2_esmfinterval
masksamplergeosat_from_config calls convert_twostring_2_esmfinterval, masksamplergeosat_from_config
masksamplergeosat calls masksamplergeosat_from_config