convert_to_cart – MAPL
convert_to_cart Function
7 statements
Source File
private function convert_to_cart(v) result(xyz)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: v(2)
Return Value real(kind=real64), (3)
Called by
Contents
Source Code
convert_to_cart
Source Code
 function convert_to_cart(v) result(xyz)
    real(real64), intent(in) :: v(2)
    real(real64) :: xyz(3)
    xyz(1)=cos(v(2))*cos(v(1))
    xyz(2)=cos(v(2))*sin(v(1))
    xyz(3)=sin(v(2))
 end function convert_to_cart
Call graph
point_in_polygon calls convert_to_cart
get_area_spherical_polygon calls convert_to_cart
get_points_in_spherical_domain calls point_in_polygon
mapl_gethorzijindex calls get_points_in_spherical_domain, mapl_gethorzijindex