convert_CF_Time_to_datetime_duration_integer_duration – MAPL
convert_CF_Time_to_datetime_duration_integer_duration Subroutine
11 statements
Source File
private subroutine convert_CF_Time_to_datetime_duration_integer_duration(duration, units, dt_duration, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: duration
character(len=*), intent(in) :: units
type(datetime_duration), intent(out) :: dt_duration
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine convert_CF_Time_to_datetime_duration_integer_duration(duration, units, dt_duration, rc)
      integer, intent(in) :: duration
      character(len=*), intent(in) :: units
      type(datetime_duration), intent(out) :: dt_duration
      integer, optional, intent(out) :: rc
      integer :: status
      call convert_CF_Time_to_datetime_duration(CF_Time_Integer(duration, units), dt_duration, _RC)
      _RETURN(_SUCCESS)
   end subroutine convert_CF_Time_to_datetime_duration_integer_duration
Call graph
convert_cf_time_to_datetime_duration_integer_duration calls convert_cf_time_to_datetime_duration, mapl_return, mapl_verify
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
convert_cf_time_to_datetime_duration_integer calls mapl_return, get_time_unit, mapl_assert, set_value
convert_cf_time_to_datetime_duration_real calls mapl_return, get_time_unit, mapl_assert, set_value
convert_cf_time_to_datetime_duration_real_duration calls convert_cf_time_to_datetime_duration, mapl_return, mapl_verify
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_esmf_time_from_netcdf_datetime_integer calls convert_cf_time_to_datetime_duration
get_esmf_time_from_netcdf_datetime_real calls convert_cf_time_to_datetime_duration
test_convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration
test_set_esmf_timeinterval_integer calls convert_cf_time_to_datetime_duration
test_set_esmf_timeinterval_real calls convert_cf_time_to_datetime_duration
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf