convert_NetCDF_DateTimeString_to_ESMF_Time – MAPL
convert_NetCDF_DateTimeString_to_ESMF_Time Subroutine
47 statements
Source File
public subroutine convert_NetCDF_DateTimeString_to_ESMF_Time(datetime_string, datetime, unusable, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: datetime_string
type(ESMF_Time), intent(inout) :: datetime
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_NetCDF_DateTimeString_to_ESMF_Time
Source Code
   subroutine convert_NetCDF_DateTimeString_to_ESMF_Time(datetime_string, datetime, unusable, rc)
      character(len=*), intent(in) :: datetime_string
      type(ESMF_Time), intent(inout) :: datetime
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: yy, mm, dd, h, m, s, i, j
      character(len=4) :: part
      _UNUSED_DUMMY(unusable)
      _ASSERT(is_valid_netcdf_datetime_string(datetime_string), 'Invalid datetime string')
      i = 1
      j = i + 3
      part = datetime_string(i:j)
      call convert_to_integer(part, yy, rc = status)
      _ASSERT(status == 0, 'Unable to convert year string')
      i = j + 2
      j = j + 3
      part = datetime_string(i:j)
      call convert_to_integer(part, mm, rc = status)
      _ASSERT(status == 0, 'Unable to convert month string')
      i = j + 2
      j = j + 3
      part = datetime_string(i:j)
      call convert_to_integer(part, dd, rc = status)
      _ASSERT(status == 0, 'Unable to convert day string')
      i = j + 2
      j = j + 3
      part = datetime_string(i:j)
      call convert_to_integer(part, h, rc = status)
      _ASSERT(status == 0, 'Unable to convert hour string')
      i = j + 2
      j = j + 3
      part = datetime_string(i:j)
      call convert_to_integer(part, m, rc = status)
      _ASSERT(status == 0, 'Unable to convert minute string')
      i = j + 2
      j = j + 3
      part = datetime_string(i:j)
      call convert_to_integer(part, s, rc = status)
      _ASSERT(status == 0, 'Unable to convert second string')
      call ESMF_CalendarSetDefault(CALKIND_FLAG, _RC)
      call ESMF_TimeSet(datetime, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
      _RETURN(_SUCCESS)
   end subroutine convert_NetCDF_DateTimeString_to_ESMF_Time
Call graph
convert_netcdf_datetimestring_to_esmf_time calls ESMF_CalendarSetDefault, ESMF_TimeSet, mapl_assert, convert_to_integer, is_valid_netcdf_datetime_string, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_netcdf_datetime_to_esmf calls convert_netcdf_datetimestring_to_esmf_time
test_convert_netcdf_datetimestring_to_esmf_time calls convert_netcdf_datetimestring_to_esmf_time
test_convert_netcdf_datetime_to_esmf calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf, time_real_to_esmf