convert_NetCDF_DateTime_to_ESMF – MAPL
convert_NetCDF_DateTime_to_ESMF Subroutine
38 statements
Source File
public subroutine convert_NetCDF_DateTime_to_ESMF(int_time, units_string, interval, time0, unusable, time1, tunit, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: int_time
character(len=*), intent(in) :: units_string
type(ESMF_TimeInterval), intent(inout) :: interval
type(ESMF_Time), intent(inout) :: time0
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Time), intent(inout), optional :: time1
character(len=:), intent(out), optional, allocatable :: tunit
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_NetCDF_DateTime_to_ESMF
Source Code
   subroutine convert_NetCDF_DateTime_to_ESMF(int_time, units_string, &
         interval, time0, unusable, time1, tunit, rc)
      integer, intent(in) :: int_time
      character(len=*), intent(in) :: units_string
      type(ESMF_TimeInterval), intent(inout) :: interval
      type(ESMF_Time), intent(inout) :: time0
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Time), optional, intent(inout) :: time1
      character(len=:), allocatable, optional, intent(out) :: tunit
      integer, optional, intent(out) :: rc
      character(len=:), allocatable :: tunit_
      character(len=len_trim(units_string)) :: parts(2)
      character(len=len_trim(units_string)) :: head
      character(len=len_trim(units_string)) :: tail
      integer :: span, factor
      integer :: status
      _UNUSED_DUMMY(unusable)
      _ASSERT(int_time >= 0, 'Negative span not supported')
      _ASSERT((len(lr_trim(units_string)) > 0), 'units empty')
      ! get time unit, tunit
      parts = split(lr_trim(units_string), PART_DELIM)
      head = parts(1)
      tail = parts(2)
      tunit_ = lr_trim(head)
      _ASSERT(is_time_unit(tunit_), 'Unrecognized time unit')
      if(present(tunit)) tunit = tunit_
      ! get span
      parts = split(lr_trim(tail), PART_DELIM)
      head = parts(1)
      tail = parts(2)
      factor = get_shift_sign(head)
      _ASSERT(factor /= 0, 'Unrecognized preposition')
      span = factor * int_time
      call convert_NetCDF_DateTimeString_to_ESMF_Time(lr_trim(tail), time0, _RC)
      call make_ESMF_TimeInterval(span, tunit_, time0, interval, _RC)
      ! get time1
      if(present(time1)) time1 = time0 + interval
      _RETURN(_SUCCESS)
   end subroutine convert_NetCDF_DateTime_to_ESMF
Call graph
convert_netcdf_datetime_to_esmf calls mapl_assert, convert_netcdf_datetimestring_to_esmf_time, get_shift_sign, is_time_unit, lr_trim, make_esmf_timeinterval, mapl_return, mapl_verify, split
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_netcdf_datetimestring_to_esmf_time calls mapl_assert, mapl_return, mapl_verify, ESMF_CalendarSetDefault, ESMF_TimeSet, convert_to_integer, is_valid_netcdf_datetime_string
get_shift_sign calls lr_trim
is_time_unit calls lr_trim
make_esmf_timeinterval calls mapl_assert, lr_trim, mapl_return, mapl_verify, ESMF_TimeIntervalSet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_convert_netcdf_datetime_to_esmf calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf, time_real_to_esmf