convert_prec – MAPL
convert_prec Subroutine
26 statements
Source File
private subroutine convert_prec(x, y, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_prec
Source Code
   subroutine convert_prec(x, y, rc)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y
      integer, optional, intent(out) :: rc
      type(ESMF_TypeKind_Flag), parameter :: expected_tks(2) = [ESMF_TYPEKIND_R4, ESMF_TYPEKIND_R8]
      type(ESMF_TypeKind_Flag) :: tk_x, tk_y
      integer :: status
      call ESMF_FieldGet(x, typekind=tk_x, _RC)
      _ASSERT(is_valid_typekind(tk_x, expected_tks), 'Unexpected typekind')
      call ESMF_FieldGet(y, typekind=tk_y, _RC)
      _ASSERT(is_valid_typekind(tk_y, expected_tks), 'Unexpected typekind')
      if(tk_x == tk_y) then
         call FieldCOPY(x, y, _RC)
      else if(tk_x == ESMF_TYPEKIND_R4) then
         call convert_prec_R4_to_R8(x, y, _RC)
      else
         call convert_prec_R8_to_R4(x, y, _RC)
      end if
      _RETURN(_SUCCESS)
   end subroutine convert_prec
Call graph
convert_prec calls esmf_fieldget, fieldcopy, mapl_assert, convert_prec_r4_to_r8, convert_prec_r8_to_r4, is_valid_typekind, mapl_return, mapl_verify
fieldcopy calls copy
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_prec_r4_to_r8 calls mapl_return, mapl_verify, assign_fptr
convert_prec_r8_to_r4 calls mapl_return, mapl_verify, assign_fptr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
copy calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldsareconformable calls are_conformable_array, are_conformable_scalar
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
fieldconvertprec calls convert_prec
test_fieldconvertprec_r4r8 calls fieldconvertprec