convert_ISO8601_to_integer_date – MAPL
convert_ISO8601_to_integer_date Function
12 statements
Source File
public function convert_ISO8601_to_integer_date(isostring, rc) result(integer_date)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
convert_ISO8601_to_integer_date
Source Code
   function convert_ISO8601_to_integer_date(isostring, rc) result(integer_date)
      character(len=*), intent(in) :: isostring
      integer, optional, intent(out) :: rc
      integer :: integer_date
      type(ISO8601Date) :: date
      integer :: status
      date = ISO8601Date(isostring, _RC)
      integer_date = date%get_year()*ID_YEAR + date%get_month()*ID_MONTH + &
         date%get_day()*ID_DAY
      _RETURN(_SUCCESS)
   end function convert_ISO8601_to_integer_date
Call graph
convert_iso8601_to_integer_date calls iso8601date, mapl_verify, mapl_return
iso8601date calls construct_iso8601date
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
construct_iso8601date calls parse_date, mapl_assert
mapl_throw_exception calls initialize
parse_date calls undelimit, read_whole_number, is_valid_date
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
test_convert_iso8601_to_integer_date calls convert_iso8601_to_integer_date