convert_CF_Time_datetime_string_to_ISO8601 – MAPL
convert_CF_Time_datetime_string_to_ISO8601 Function
32 statements
Source File
private function convert_CF_Time_datetime_string_to_ISO8601(datetime_string) result(isodatetime)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: datetime_string
Return Value character(len=MAX_CHARACTER_LENGTH)
Calls
Called by
Source Code
   function convert_CF_Time_datetime_string_to_ISO8601(datetime_string) result(isodatetime)
      character(len=*), intent(in) :: datetime_string
      character(len=MAX_CHARACTER_LENGTH) :: isodatetime
      character(len=MAX_CHARACTER_LENGTH) :: remainder
      character(len=MAX_CHARACTER_LENGTH) :: part(NUM_TIME_UNITS)
      isodatetime = EMPTY_STRING
      remainder = datetime_string
      call split(trim(remainder), part(YEAR_TIME_UNIT), remainder, DATE_DELIM)
      call split(trim(remainder), part(MONTH_TIME_UNIT), remainder, DATE_DELIM)
      call split(trim(remainder), part(DAY_TIME_UNIT), remainder, CF_DELIM)
      call split(trim(remainder), part(HOUR_TIME_UNIT), remainder, TIME_DELIM)
      call split(trim(remainder), part(MINUTE_TIME_UNIT), remainder, TIME_DELIM)
      part(SECOND_TIME_UNIT) = trim(remainder)
      call update_datetime(isodatetime, part(YEAR_TIME_UNIT), 4, DATE_DELIM)
      call update_datetime(isodatetime, part(MONTH_TIME_UNIT), 2, DATE_DELIM)
      call update_datetime(isodatetime, part(DAY_TIME_UNIT), 2, ISO_DELIM)
      call update_datetime(isodatetime, part(HOUR_TIME_UNIT), 2, TIME_DELIM)
      call update_datetime(isodatetime, part(MINUTE_TIME_UNIT), 2, TIME_DELIM)
      call update_datetime(isodatetime, part(SECOND_TIME_UNIT), 2)
   contains
      subroutine update_datetime(datetime_, text, width, delm)
         character(len=MAX_CHARACTER_LENGTH), intent(inout) :: datetime_
         character(len=*), intent(in) :: text
         integer, optional, intent(in) :: width
         character(len=*), optional, intent(in) :: delm
         character(len=MAX_CHARACTER_LENGTH) :: text_
         text_ = text
         if(present(width)) text_ = zero_pad(text, width)
         datetime_ = trim(datetime_) // trim(text_)
         if(present(delm)) datetime_ = trim(datetime_) // trim(delm)
      end subroutine update_datetime
   end function convert_CF_Time_datetime_string_to_ISO8601
Call graph
convert_cf_time_datetime_string_to_iso8601 calls split, zero_pad
split calls split_characters
extract_iso8601_from_cf_time_cf_time calls convert_cf_time_datetime_string_to_iso8601
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time, extract_iso8601_from_cf_time_units
extract_iso8601_from_cf_time_units calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_integer calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_real calls extract_iso8601_from_cf_time
test_extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real