convert_CF_Time_to_datetime_duration_real – MAPL
convert_CF_Time_to_datetime_duration_real Subroutine
15 statements
Source File
private subroutine convert_CF_Time_to_datetime_duration_real(cft, dt_duration, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time_Real), intent(in) :: cft
type(datetime_duration), intent(out) :: dt_duration
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine convert_CF_Time_to_datetime_duration_real(cft, dt_duration, rc)
      class(CF_Time_Real), intent(in) :: cft
      type(datetime_duration), intent(out) :: dt_duration
      integer, optional, intent(out) :: rc
      integer(kind(TIME_UNIT)) :: tu
      if(.not. cft % is_valid) then
         _RETURN(_FAILURE)
      end if
      tu = get_time_unit(cft % time_unit)
      _ASSERT(tu /= UNKNOWN_TIME_UNIT, 'Unable to find TIME_UNIT ' // cft % time_unit)
      call dt_duration % set_value(tu, cft % duration)
      _RETURN(_SUCCESS)
   end subroutine convert_CF_Time_to_datetime_duration_real
Call graph
convert_cf_time_to_datetime_duration_real calls get_time_unit, mapl_assert, mapl_return, set_value
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real_duration
convert_cf_time_to_datetime_duration_integer_duration calls convert_cf_time_to_datetime_duration
convert_cf_time_to_datetime_duration_real_duration calls convert_cf_time_to_datetime_duration
get_esmf_time_from_netcdf_datetime_integer calls convert_cf_time_to_datetime_duration
get_esmf_time_from_netcdf_datetime_real calls convert_cf_time_to_datetime_duration
test_convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration
test_set_esmf_timeinterval_integer calls convert_cf_time_to_datetime_duration
test_set_esmf_timeinterval_real calls convert_cf_time_to_datetime_duration
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf