convert_ESMF_to_NetCDF_DateTime – MAPL
convert_ESMF_to_NetCDF_DateTime Subroutine
26 statements
Source File
public subroutine convert_ESMF_to_NetCDF_DateTime(tunit, t0, int_time, units_string, unusable, t1, interval, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: tunit
type(ESMF_Time), intent(inout) :: t0
integer, intent(out) :: int_time
character(len=:), intent(out), allocatable :: units_string
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Time), intent(inout), optional :: t1
type(ESMF_TimeInterval), intent(inout), optional :: interval
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_ESMF_to_NetCDF_DateTime
Source Code
   subroutine convert_ESMF_to_NetCDF_DateTime(tunit, t0, int_time, units_string, unusable, t1, interval, rc)
      character(len=*), intent(in) :: tunit
      type(ESMF_Time),  intent(inout) :: t0
      integer, intent(out) :: int_time
      character(len=:), allocatable, intent(out) :: units_string
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Time), optional, intent(inout) :: t1
      type(ESMF_TimeInterval), optional, intent(inout) :: interval
      integer, optional, intent(out) :: rc
      type(ESMF_TimeInterval) :: interval_
      integer :: status
      _UNUSED_DUMMY(unusable)
      if(present(interval)) then
         interval_ = interval
      elseif(present(t1)) then
         interval_ = t1 - t0
      else
         _FAIL( 'Only one input argument present')
      end if
      call make_NetCDF_DateTime_int_time(interval_, t0, tunit, int_time, _RC)
      call make_NetCDF_DateTime_units_string(t0, tunit, units_string, _RC)
      _RETURN(_SUCCESS)
   end subroutine convert_ESMF_to_NetCDF_DateTime
Call graph
convert_esmf_to_netcdf_datetime calls mapl_assert, make_netcdf_datetime_int_time, make_netcdf_datetime_units_string, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_netcdf_datetime_int_time calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeIntervalGet, lr_trim
make_netcdf_datetime_units_string calls mapl_return, mapl_verify, convert_esmf_time_to_netcdf_datetimestring
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
convert_esmf_time_to_netcdf_datetimestring calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_convert_esmf_to_netcdf_datetime calls convert_esmf_to_netcdf_datetime