convert_ISO8601_to_integer_time – MAPL
convert_ISO8601_to_integer_time Function
12 statements
Source File
public function convert_ISO8601_to_integer_time(isostring, rc) result(integer_time)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
convert_ISO8601_to_integer_time
Source Code
   function convert_ISO8601_to_integer_time(isostring, rc) result(integer_time)
      character(len=*), intent(in) :: isostring
      integer, optional, intent(out) :: rc
      integer :: integer_time
      type(ISO8601Time) :: time
      integer :: status
      time = ISO8601Time(isostring, _RC)
      integer_time = time%get_hour()*IT_HOUR + time%get_minute()*IT_MINUTE + &
         time%get_second()*IT_SECOND
      _RETURN(_SUCCESS)
   end function convert_ISO8601_to_integer_time
Call graph
convert_iso8601_to_integer_time calls iso8601time, get_hour, get_minute, get_second, mapl_return, mapl_verify
iso8601time calls construct_iso8601time
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
construct_iso8601time calls mapl_return, mapl_assert, parse_time
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
parse_time calls time_fields, is_valid_time, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
test_convert_iso8601_to_integer_time calls convert_iso8601_to_integer_time