convert_ISO8601_to_esmf_timeinterval – MAPL
convert_ISO8601_to_esmf_timeinterval Function
13 statements
Source File
public function convert_ISO8601_to_esmf_timeinterval(isostring, rc) result(interval)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
integer, intent(out), optional :: rc
Return Value type(ESMF_TimeInterval)
Calls
Contents
Source Code
convert_ISO8601_to_esmf_timeinterval
Source Code
   function convert_ISO8601_to_esmf_timeinterval(isostring, rc) result(interval)
      character(len=*), intent(in) :: isostring
      integer, optional, intent(out) :: rc
      type(ESMF_TimeInterval) :: interval
      type(ISO8601Duration) :: duration
      integer :: status
      duration = ISO8601Duration(isostring, 0, 1, _RC)
      call ESMF_TimeIntervalSet(interval, yy=duration%get_years(), &
         mm=duration%get_months(), d=duration%get_days(), &
         h=duration%get_hours(), m=duration%get_minutes(), &
         s=duration%get_seconds(), _RC)
      _RETURN(_SUCCESS)
   end function convert_ISO8601_to_esmf_timeinterval
Call graph
convert_iso8601_to_esmf_timeinterval calls ESMF_TimeIntervalSet, iso8601duration, get_days, get_hours, get_minutes, get_months, get_seconds, get_years, mapl_return, mapl_verify
iso8601duration calls construct_iso8601duration
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
construct_iso8601duration calls mapl_return, mapl_assert, is_digit, read_whole_number_indexed
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number