convert_prec_R8_to_R4 – MAPL
convert_prec_R8_to_R4 Subroutine
15 statements
Source File
private subroutine convert_prec_R8_to_R4(original, converted, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: original
type(ESMF_Field), intent(inout) :: converted
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
convert_prec_R8_to_R4
Source Code
   subroutine convert_prec_R8_to_R4(original, converted, rc)
      type(ESMF_Field), intent(inout) :: original
      type(ESMF_Field), intent(inout) :: converted
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=ESMF_KIND_R8), pointer :: original_ptr(:)
      real(kind=ESMF_KIND_R4), pointer :: converted_ptr(:)
      call assign_fptr(original, original_ptr, _RC)
      call assign_fptr(converted, converted_ptr, _RC)
      converted_ptr = original_ptr
      _RETURN(_SUCCESS)
   end subroutine convert_prec_R8_to_R4
Call graph
convert_prec_r8_to_r4 calls assign_fptr, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
convert_prec calls convert_prec_r8_to_r4
fieldconvertprec calls convert_prec
test_fieldconvertprec_r4r8 calls fieldconvertprec