coordinate_has_bounds – MAPL
coordinate_has_bounds Function
13 statements
Source File
private function coordinate_has_bounds(metadata, coord_name, rc) result(has_bounds)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: metadata
character(len=*), intent(in) :: coord_name
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Call graph
coordinate_has_bounds calls get_variable, is_attribute_present, mapl_return, mapl_verify
get_variable calls mapl_return, m_at
is_attribute_present calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find
initialize_from_file_metadata calls coordinate_has_bounds