copy_global_to_local – MAPL
copy_global_to_local Subroutine
37 statements
Source File
private subroutine copy_global_to_local(this)
Uses
pFIO
MAPL_BaseMod
Type Bound
TilingRegridder
Arguments
Type Intent Optional Attributes Name
class(TilingRegridder), intent(inout) :: this
Calls
Called by
Source Code
   subroutine copy_global_to_local(this)
      use MAPL_BaseMod, only: MAPL_Grid_interior
      use pFIO
      class (TilingRegridder), intent(inout) :: this
      type (IntegerVector) :: local_indices
      type (IntegerVectorIterator) :: iter
      integer :: i_tile
      logical :: cell_is_local
      integer :: i1, in, j1, jn ! index bounds for grid_out
      integer :: i, j
      type (RegridderSpec) :: spec
      integer :: n
      integer :: n_tiles
      spec = this%get_spec()
      call MAPL_Grid_interior(spec%grid_out, i1, in, j1, jn)
      n_tiles = size(this%global_x_tiles)
      do i_tile = 1, n_tiles
         i = this%global_x_tiles(i_tile)%idx_i_out
         j = this%global_x_tiles(i_tile)%idx_j_out
         cell_is_local = (i1<=i .and. in>=i .and.  j1<=j .and. jn>=j)
         if (cell_is_local) then
            call local_indices%push_back(i_tile)
         end if
      end do
      allocate(this%local_x_tiles(local_indices%size()))
      associate (tiles => this%local_x_tiles)
        iter = local_indices%begin()
        n = 0
        do while (iter /= local_indices%end())
           n = n + 1
           this%local_x_tiles(n) = this%global_x_tiles(iter%get())
           call iter%next
        end do
        ! fix offsets
        tiles(:)%idx_i_out = tiles(:)%idx_i_out - i1 + 1
        tiles(:)%idx_j_out = tiles(:)%idx_j_out - j1 + 1
      end associate
   end subroutine copy_global_to_local
Call graph
copy_global_to_local calls begin, get, mapl_grid_interior, next, get_spec, push_back
mapl_grid_interior calls mapl_grid_interior, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_verify
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_verify calls mapl_throw_exception
initialize_subclass calls copy_global_to_local
initialize_base calls initialize
make_regridder_from_grids calls initialize
newlatlontolatlonregridder calls initialize
latlontolatlonregridder calls newlatlontolatlonregridder