CopyState – MAPL
CopyState Subroutine
66 statements
Source File
private subroutine CopyState(inState, outState, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: inState
type(ESMF_State), intent(inout) :: outState
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine CopyState(inState,outState,rc)
      type(ESMF_State), intent(inout) :: inState
      type(ESMF_State), intent(inout) :: outState
      integer, optional, intent(out) :: rc
      integer :: status
      integer                             :: I
      real, pointer                       :: IMptr3(:,:,:)
      real, pointer                       :: Exptr3(:,:,:)
      real, pointer                       :: IMptr2(:,:)
      real, pointer                       :: Exptr2(:,:)
      real, pointer                       :: IMptr1(:)
      real, pointer                       :: Exptr1(:)
      integer :: itemcountIn,itemCountOut,rank
      character(len=ESMF_MAXSTR), allocatable :: inNameList(:)
      character(len=ESMF_MAXSTR), allocatable :: outNameList(:)
      type(ESMF_StateItem_Flag), allocatable :: item_type_in(:)
      type(ESMF_Field) :: expf,impf
      call ESMF_StateGet(inState,itemcount=itemCountIn,_RC)
      allocate(InNameList(itemCountIn),stat=status)
      _VERIFY(status)
      allocate(item_type_in(itemCountIn),stat=status)
      _VERIFY(status)
      call ESMF_StateGet(inState,itemNameList=InNameList,itemTypeList=item_type_in,_RC)
      call ESMF_StateGet(outState,itemcount=ItemCountOut,_RC)
      allocate(outNameList(ItemCountOut),stat=status)
      _VERIFY(status)
      call ESMF_StateGet(outState,itemNameList=outNameList,_RC)
      call ESMF_StateGet(inState,itemNameList=inNameList,_RC)
      do i=1,itemCountIn
         if (item_type_in(i) == ESMF_STATEITEM_FIELD) then
            call ESMF_StateGet(inState,trim(inNameList(i)),impf,_RC)
            call ESMF_StateGet(outState,trim(inNameList(i)),expf,_RC)
            call ESMF_FieldGet(impf,rank=rank,_RC)
            if (rank==1) then
               call MAPL_GetPointer(inState,IMptr1,inNameList(i),_RC)
               call MAPL_GetPointer(outState,Exptr1,inNameList(i),alloc=.true.,_RC)
               EXptr1=IMptr1
            else if (rank==2) then
               call MAPL_GetPointer(inState,IMptr2,inNameList(i),_RC)
               call MAPL_GetPointer(outState,Exptr2,inNameList(i),alloc=.true.,_RC)
               EXptr2=IMptr2
            else if (rank==3) then
               call MAPL_GetPointer(inState,IMptr3,inNameList(i),_RC)
               call MAPL_GetPointer(outState,EXptr3,inNameList(i),alloc=.true.,_RC)
               EXptr3=IMptr3
            end if
         end if
      end do
      deallocate(inNameList,outNameList)
      _RETURN(ESMF_SUCCESS)
   end subroutine CopyState
Call graph
copystate calls esmf_fieldget, esmf_stateget, esmfl_stategetpointertodata, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_stategetptrtodatar4_1 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify, mapl_allocatecoupling
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_allocatecoupling calls mapl_allocatecoupling
run_ calls copystate