copy_bcast_r8_r4 – MAPL
copy_bcast_r8_r4 Subroutine
12 statements
Source File
private subroutine copy_bcast_r8_r4(cptr_x, cptr_y, n1, n2)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: cptr_x
type(c_ptr), intent(in) :: cptr_y
integer(kind=ESMF_KIND_I8), intent(in) :: n1
integer(kind=ESMF_KIND_I8), intent(in) :: n2
Called by
Source Code
   subroutine copy_bcast_r8_r4(cptr_x, cptr_y, n1,n2)
      type(c_ptr), intent(in) :: cptr_x, cptr_y
      integer(ESMF_KIND_I8), intent(in) :: n1,n2
      integer :: i
      real(kind=ESMF_KIND_R8), pointer :: x_ptr(:)
      real(kind=ESMF_KIND_R4), pointer :: y_ptr(:,:)
      call c_f_pointer(cptr_x, x_ptr, [n1])
      call c_f_pointer(cptr_y, y_ptr, [n1,n2])
      do i=1,n2
         y_ptr(:,i) = x_ptr
      enddo
   end subroutine copy_bcast_r8_r4
Call graph
copy_broadcast calls copy_bcast_r8_r4
fieldcopybroadcast calls copy_broadcast
evalf calls fieldcopybroadcast
mapl_stateeval calls evalf