copy_bundle_to_bundle – MAPL
copy_bundle_to_bundle Subroutine
23 statements
Source File
subroutine copy_bundle_to_bundle(input_bundle, output_bundle, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: input_bundle
type(ESMF_FieldBundle), intent(inout) :: output_bundle
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
copy_bundle_to_bundle
Source Code
   subroutine copy_bundle_to_bundle(input_bundle,output_bundle,rc)
      type(ESMF_FieldBundle), intent(inout) :: input_bundle
      type(ESMF_FieldBundle), intent(inout) :: output_bundle
      integer, intent(out), optional :: rc
      integer :: status
      character(len=ESMF_MAXSTR), allocatable :: field_list(:)
      type(ESMF_Field) :: field
      integer :: i,num_fields
      call ESMF_FieldBundleGet(input_bundle,fieldCount=num_fields,_RC)
      allocate(field_list(num_fields))
      call ESMF_FieldBundleGet(input_bundle,fieldNameList=field_list,_RC)
      do i=1,num_fields
         call ESMF_FieldBundleGet(input_bundle,field_list(i),field=field,_RC)
         call MAPL_FieldBundleAdd(output_bundle,field,_RC)
      enddo
      if (present(rc)) then
         RC=_SUCCESS
      end if
   end subroutine copy_bundle_to_bundle
Call graph
copy_bundle_to_bundle calls esmf_fieldbundleget, mapl_fieldbundleadd, mapl_verify, mapl_abort
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_verify calls mapl_throw_exception
mapl_abort calls mpi_abort
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_verify, esmf_fieldbundleadd, esmf_fieldget, esmf_attributeget, esmf_attributeremove, esmf_attributeset, mapl_return
mapl_throw_exception calls initialize
time_ave calls copy_bundle_to_bundle