CopyFieldtoPtr – MAPL
CopyFieldtoPtr Subroutine
32 statements
Source File
private subroutine CopyFieldtoPtr(field, ptrs, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
type(Ptrs_Type), intent(inout) :: ptrs
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
CopyFieldtoPtr
Source Code
  SUBROUTINE CopyFieldtoPtr(field,ptrs,rc)
     ! take data from input field and copy to output field
     ! if input is 2D and output is 3D replicate 2D on each slice of 3D
     TYPE(ESMF_Field),      intent(inout) :: field
     TYPE(Ptrs_Type),      intent(inout) :: ptrs
     integer, optional,     intent(out  ) :: rc
     real, pointer        :: var2d(:,:), var3d(:,:,:)
     type(ESMF_Array)      :: array
     integer               :: rank
     character(len=ESMF_MAXSTR), parameter :: Iam="CopyFieldtoField"
     integer :: status
     integer :: i
     call ESMF_FieldGet(field,array=array,rc=status)
     _VERIFY(STATUS)
     call ESMF_ArrayGet(array,rank=rank,rc=status)
     _VERIFY(STATUS)
     if (rank == 3 .and. ptrs%rank ==3) then
        call ESMF_FieldGet(field,0,var3d,rc=status)
        _VERIFY(STATUS)
        ptrs%Q3D=var3d
     else if (rank == 2 .and. ptrs%rank ==2) then
        call ESMF_FieldGet(field,0,var2d,rc=status)
        _VERIFY(STATUS)
        ptrs%Q2D=var2d
     else if (rank == 2 .and. ptrs%rank ==3) then
        call ESMF_FieldGet(field,0,var2d,rc=status)
        _VERIFY(STATUS)
        do i=ptrs%lb(3),ptrs%ub(3)
           ptrs%Q3D(:,:,i)=var2d
        end do
     end if
     _RETURN(ESMF_SUCCESS)
  END SUBROUTINE CopyFieldToPtr
Call graph
copyfieldtoptr calls esmf_fieldget, esmf_arrayget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
evalf calls copyfieldtoptr
mapl_stateeval calls evalf
mapl_runexpression calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
calcderivedfield calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
run calls mapl_runexpression
run_ calls fillstate, calcderivedfield