copy_r8_r4 – MAPL
copy_r8_r4 Subroutine
9 statements
Source File
private subroutine copy_r8_r4(cptr_x, cptr_y, n)
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: cptr_x
type(c_ptr), intent(in) :: cptr_y
integer(kind=ESMF_KIND_I8), intent(in) :: n
Called by
Contents
Source Code
copy_r8_r4
Source Code
   subroutine copy_r8_r4(cptr_x, cptr_y, n)
      type(c_ptr), intent(in) :: cptr_x, cptr_y
      integer(ESMF_KIND_I8), intent(in) :: n
      real(kind=ESMF_KIND_R8), pointer :: x_ptr(:)
      real(kind=ESMF_KIND_R4), pointer :: y_ptr(:)
      call c_f_pointer(cptr_x, x_ptr, [n])
      call c_f_pointer(cptr_y, y_ptr, [n])
      y_ptr=x_ptr
   end subroutine copy_r8_r4
Call graph
copy calls copy_r8_r4
fieldcopy calls copy
copy_broadcast calls copy
fieldcopybroadcast calls copy_broadcast
convert_prec calls fieldcopy
spread_scalar calls fieldcopy
test_fieldcopy_r4 calls fieldcopy
test_fieldcopy_r4r8 calls fieldcopy
test_fieldcopy_r8 calls fieldcopy
test_fieldcopy_r8r4 calls fieldcopy
fieldconvertprec calls convert_prec
fieldspread calls spread_scalar
evalf calls fieldcopybroadcast