copy – MAPL
copy Subroutine
44 statements
Source File
private subroutine copy(x, y, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_Field), intent(inout) :: y
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine copy(x, y, rc)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_Field), intent(inout) :: y
      integer, optional, intent(out) :: rc
      type(ESMF_TypeKind_Flag) :: tk_x, tk_y
      type(c_ptr) :: cptr_x, cptr_y
      integer(kind=ESMF_KIND_I8) :: n
      integer :: status
      logical :: conformable
      logical :: x_is_double
      logical :: y_is_double
      character(len=*), parameter :: UNSUPPORTED_TK = &
         'Unsupported typekind in FieldCOPY() for '
      conformable = FieldsAreConformable(x, y)
      !wdb fixme need to pass RC
      _ASSERT(conformable, 'FieldCopy() - fields not conformable.')
      call FieldGetCptr(x, cptr_x, _RC)
      call ESMF_FieldGet(x, typekind = tk_x, _RC)
      n  = FieldGetLocalSize(x, _RC)
      call FieldGetCptr(y, cptr_y, _RC)
      call ESMF_FieldGet(y, typekind = tk_y, _RC)
     !wdb  fixme convert between precisions ? get rid of extra cases
      y_is_double = (tk_y == ESMF_TYPEKIND_R8)
      _ASSERT(y_is_double .or. (tk_y == ESMF_TYPEKIND_R4), UNSUPPORTED_TK//'y.')
      x_is_double = (tk_x == ESMF_TYPEKIND_R8)
      _ASSERT(x_is_double .or. (tk_x == ESMF_TYPEKIND_R4), UNSUPPORTED_TK//'x.')
      if (y_is_double) then
         if (x_is_double) then
            call copy_r8_r8(cptr_x, cptr_y, n)
         else
            call copy_r4_r8(cptr_x, cptr_y, n)
         end if
      else
         if (x_is_double) then
            call copy_r8_r4(cptr_x, cptr_y, n)
         else
            call copy_r4_r4(cptr_x, cptr_y, n)
         end if
      end if
      _RETURN(_SUCCESS)
   end subroutine copy
Call graph
copy calls esmf_fieldget, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, mapl_assert, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8, mapl_return, mapl_verify
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, mapl_return, mapl_verify, fieldgetlocalelementcount
get_cptr calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8
get_error_message calls at, insert
get_local_size calls mapl_return, mapl_verify, fieldgetlocalelementcount
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetlocalelementcount calls get_local_element_count
get_cptr_i4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_i8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_r4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_r8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
fieldcopy calls copy
copy_broadcast calls copy
fieldcopybroadcast calls copy_broadcast
convert_prec calls fieldcopy
spread_scalar calls fieldcopy
test_fieldcopy_r4 calls fieldcopy
test_fieldcopy_r4r8 calls fieldcopy
test_fieldcopy_r8 calls fieldcopy
test_fieldcopy_r8r4 calls fieldcopy
fieldconvertprec calls convert_prec
fieldspread calls spread_scalar
evalf calls fieldcopybroadcast
mapl_stateeval calls evalf
test_fieldconvertprec_r4r8 calls fieldconvertprec