copy_data_to – MAPL
copy_data_to Subroutine
21 statements
Source File
private subroutine copy_data_to(this, to, rc)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(in) :: this
class(AbstractDataReference), intent(inout) :: to
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine copy_data_to(this,to, rc)
     class(AbstractDataReference),intent(in) :: this
     class(AbstractDataReference),intent(inout) :: to
     integer, optional, intent(out) :: rc
     integer,pointer :: fromPtr(:)
     integer,pointer :: toPtr(:)
     integer(kind=INT64) :: n_words,n
     n_words = product(int(this%shape,INT64))*word_size(this%type_kind)
     _RETURN_IF(n_words == 0)
     n       = product(int(to%shape,INT64))*word_size(to%type_kind)
     _ASSERT(this%type_kind == to%type_kind,"copy type_kind not match")
     _ASSERT(n_words == n, "copy size does not match")
     call c_f_pointer(this%base_address,fromPtr,[n])
     call c_f_pointer(to%base_address,toPtr,[n])
     toPtr(1:n) = fromPtr(1:n)
     _RETURN(_SUCCESS)
   end subroutine copy_data_to
Call graph
copy_data_to calls mapl_assert, mapl_return, word_size
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_assert, mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
collective_stage_data calls copy_data_to
put calls copy_data_to
stage_data calls copy_data_to
stage_nondistributed_data calls copy_data_to