copy – MAPL
copy Subroutine
5 statements
Source File
private subroutine copy(new, old)
Type Bound
MemoryProfiler
Arguments
Type Intent Optional Attributes Name
class(MemoryProfiler), intent(inout), target :: new
class(BaseProfiler), intent(in), target :: old
Calls
Source Code
   subroutine copy(new, old)
      class(MemoryProfiler), target, intent(inout) :: new
      class(BaseProfiler), target, intent(in) :: old
      call new%copy_profiler(old)
   end subroutine copy
Call graph
copy calls copy_profiler
copy_profiler calls get_child, get_name, of, vector_begin, vector_empty, vector_iter_next, vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity