CopyStateItems – MAPL
CopyStateItems Subroutine
36 statements
Source File
private subroutine CopyStateItems(src, dst, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: src
type(ESMF_State), intent(inout) :: dst
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine CopyStateItems(src, dst, rc)
    type(ESMF_State), intent(in) :: src
    type(ESMF_State), intent(inout) :: dst
    integer, optional, intent(out) :: rc
! local vars
    type (ESMF_StateItem_Flag), pointer  :: itemTypes(:)
    character(len=ESMF_MAXSTR ), pointer :: itemNames(:)
    integer :: status
    integer :: n, itemCount
    type(ESMF_Field) :: field(1)
    type(ESMF_FieldBundle) :: bundle(1)
    call ESMF_StateGet(src,  itemCount=itemCount, _RC)
    allocate(itemnames(itemcount), _STAT)
    allocate(itemtypes(itemcount), _STAT)
    call ESMF_StateGet(src, itemNameList=itemNames, &
                       itemTypeList=itemTypes, _RC)
    do n=1,itemCount
       if(itemTypes(n)==ESMF_STATEITEM_FIELD) then
          call ESMF_StateGet(src, itemNames(n), field(1), _RC)
          call ESMF_StateAdd(dst, field, _RC)
       else if(itemTypes(n)==ESMF_STATEITEM_FieldBundle) then
          call ESMF_StateGet(src, itemNames(n), bundle(1), _RC)
          call ESMF_StateAdd(dst, bundle, _RC)
       end if
    end do
    deallocate(itemTypes)
    deallocate(itemNames)
    _RETURN(ESMF_SUCCESS)
  end subroutine CopyStateItems
Call graph
copystateitems calls esmf_stateadd, esmf_stateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize calls copystateitems