copy – MAPL
copy Subroutine
10 statements
Source File
private subroutine copy(new, old)
Type Bound
DistributedProfiler
Arguments
Type Intent Optional Attributes Name
class(DistributedProfiler), intent(inout), target :: new
class(BaseProfiler), intent(in), target :: old
Calls
Source Code
   subroutine copy(new, old)
      class(DistributedProfiler), target, intent(inout) :: new
      class(BaseProfiler), target, intent(in) :: old
      call new%copy_profiler(old)
      select type (old)
      class is (DistributedProfiler)
         new%gauge = old%gauge
         new%comm = old%comm
      end select
   end subroutine copy
Call graph
copy calls copy_profiler
copy_profiler calls get_child, get_name, of, vector_begin, vector_empty, vector_iter_next, vector_push_back
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity