correct_topo – MAPL
correct_topo Subroutine
33 statements
Source File
private subroutine correct_topo(this, field, rc)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout) :: this
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine correct_topo(this,field,rc)
        class(verticalData), intent(inout) :: this
        type(ESMF_Field), intent(inout) :: field
        integer, optional, intent(out) :: rc
        integer :: rank,k,status
        real, pointer :: ptr(:,:,:)
        type(ESMF_Grid) :: grid
        logical :: has_de
        _ASSERT(allocated(this%surface_level),"class not setup to do topography correction")
        if (this%regrid_type == VERTICAL_METHOD_ETA2LEV) then
           call ESMF_FieldGet(field,grid=grid,_RC)
           has_de = MAPL_GridHasDE(grid,_RC)
           if (has_de) then
              call ESMF_FieldGet(field,rank=rank,_RC)
              if (rank==3) then
                 call ESMF_FieldGet(field,0,farrayptr=ptr,_RC)
                 do k=1,size(ptr,3)
                    if (this%ascending) then
                       where(this%surface_level<this%scaled_levels(k)) ptr(:,:,k)=MAPL_UNDEF
                    else
                       where(this%surface_level>this%scaled_levels(k)) ptr(:,:,k)=MAPL_UNDEF
                    end if
                 end do
              end if
           end if
        end if
        _RETURN(_SUCCESS)
     end subroutine correct_topo
Call graph
correct_topo calls esmf_fieldget, mapl_assert, mapl_gridhasde, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
bundlepost calls correct_topo
interp_accumulate_fields calls correct_topo
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls bundlepost, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main