count_rules_for_item – MAPL
count_rules_for_item Function
23 statements
Source File
private function count_rules_for_item(this, item_name, rc) result(number_of_rules)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(in), target :: this
character(len=*), intent(in) :: item_name
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function count_rules_for_item(this,item_name,rc) result(number_of_rules)
      integer :: number_of_rules
      class(ExtDataConfig), target, intent(in) :: this
      character(len=*), intent(in) :: item_name
      integer, optional, intent(out) :: rc
      type(ExtDataRuleMapIterator) :: rule_iterator
      character(len=:), pointer :: key
      integer :: idx
      rule_iterator = this%rule_map%begin()
      number_of_rules = 0
      do while(rule_iterator /= this%rule_map%end())
         key => rule_iterator%key()
         idx = index(key,rule_sep)
         if (idx > 0) then
            if (trim(item_name)==key(1:idx-1)) number_of_rules = number_of_rules + 1
         else
            if (trim(item_name) == trim(key)) number_of_rules = number_of_rules + 1
         end if
         call rule_iterator%next()
      enddo
      _RETURN(_SUCCESS)
   end function count_rules_for_item
Call graph
count_rules_for_item calls m_begin, m_key, m_next, mapl_return
m_begin calls s_begin
m_next calls s_next
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
initialize_ calls count_rules_for_item