create_file_handle – MAPL
create_file_handle Subroutine
31 statements
Source File
private subroutine create_file_handle(this, filename, rc)
Type Bound
StationSampler
Arguments
Type Intent Optional Attributes Name
class(StationSampler), intent(inout) :: this
character(len=*), intent(inout) :: filename
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine create_file_handle(this,filename,rc)
    class(StationSampler), intent(inout) :: this
    character(len=*), intent(inout) :: filename  ! for ouput nc
    integer, optional, intent(out) :: rc
    type(variable) :: v
    integer :: status, j
    this%ofile = trim(filename)
    v = this%time_info%define_time_variable(_RC)
    call this%metadata%modify_variable('time',v,_RC)
    this%obs_written = 0
    if (.not. mapl_am_I_root()) then
       _RETURN(_SUCCESS)
    end if
    call this%formatter%create(trim(filename),_RC)
    call this%formatter%write(this%metadata,_RC)
    call this%formatter%put_var('longitude',this%lons,_RC)
    call this%formatter%put_var('latitude',this%lats,_RC)
    call this%formatter%put_var('station_id',this%station_id,_RC)
    call this%formatter%put_var('station_name',this%station_name,_RC)
    _RETURN(_SUCCESS)
  end subroutine create_file_handle
Call graph
create_file_handle calls mapl_am_i_root, put_var, create, define_time_variable, mapl_return, mapl_verify, modify_variable
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
create calls mapl_return, mapl_verify, nf90_create
define_time_variable calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, mapl_assert, add_attribute, v_clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modify_variable calls mapl_return, at, begin, get, mapl_assert, next, get_dimensions, m_set