CreateTimeInterval – MAPL
CreateTimeInterval Subroutine
93 statements
Source File
private subroutine CreateTimeInterval(item, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_Clock), intent(in) :: clock
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
CreateTimeInterval
Source Code
     subroutine CreateTimeInterval(item,clock,rc)
        type(PrimaryExport)      , intent(inout) :: item
        type(ESMF_Clock)          , intent(in   ) :: clock
        integer, optional         , intent(out  ) :: rc
        integer                    :: iyy,imm,idd,ihh,imn,isc
        integer                    :: lasttoken
        character(len=2)           :: token
        type(ESMF_Time)            :: time,start_time
        integer                    :: cindex,pindex
        character(len=ESMF_MAXSTR) :: creffTime, ctInt
        integer :: status
        logical :: found
        creffTime = ''
        ctInt     = ''
        call ESMF_ClockGet (CLOCK, currTIME=time, startTime=start_time, _RC)
        if (.not.item%hasFileReffTime) then
           ! if int_frequency is less than zero than try to guess it from the file template
           ! if that fails then it must be a single file or a climatology
           call ESMF_TimeGet(time, yy=iyy, mm=imm, dd=idd,h=ihh, m=imn, s=isc  ,_RC)
           !=======================================================================
           ! Using "now" as a reference time makes it difficult to find a file if
           ! we need to extrapolate, and doesn't make an awful lot of sense anyway.
           ! Instead, use the start of (current year - 20) or 1985, whichever is
           ! earlier (SDE 2016-12-30)
           iyy = Min(iyy-20,1985)
           imm = 1
           idd = 1
           ihh = 0
           imn = 0
           isc = 0
           !=======================================================================
           lasttoken = index(item%file,'%',back=.true.)
           if (lasttoken.gt.0) then
              token = item%file(lasttoken+1:lasttoken+2)
              select case(token)
              case("y4")
                 call ESMF_TimeSet(item%reff_time,yy=iyy,mm=1,dd=1,h=0,m=0,s=0,_RC)
                 call ESMF_TimeIntervalSet(item%frequency,startTime=start_time,yy=1,_RC)
              case("m2")
                 call ESMF_TimeSet(item%reff_time,yy=iyy,mm=imm,dd=1,h=0,m=0,s=0,_RC)
                 call ESMF_TimeIntervalSet(item%frequency,startTime=start_time,mm=1,_RC)
              case("d2")
                 call ESMF_TimeSet(item%reff_time,yy=iyy,mm=imm,dd=idd,h=0,m=0,s=0,_RC)
                 call ESMF_TimeIntervalSet(item%frequency,startTime=start_time,d=1,_RC)
              case("h2")
                 call ESMF_TimeSet(item%reff_time,yy=iyy,mm=imm,dd=idd,h=ihh,m=0,s=0,_RC)
                 call ESMF_TimeIntervalSet(item%frequency,startTime=start_time,h=1,_RC)
              case("n2")
                 call ESMF_TimeSet(item%reff_time,yy=iyy,mm=imm,dd=idd,h=ihh,m=imn,s=0,_RC)
                 call ESMF_TimeIntervalSet(item%frequency,startTime=start_time,m=1,_RC)
              end select
           else
              ! couldn't find any tokens so all the data must be on one file
              call ESMF_TimeIntervalSet(item%frequency,_RC)
              ! check if non-token file exists
              inquire(file=trim(item%file),EXIST=found)
              _ASSERT(found,'File ' // trim(item%file) // ' not found')
           end if
        else
           ! Reference time should look like:
           ! YYYY-MM-DDThh:mm:ssPYYYY-MM-DDThh:mm:ss
           ! The date before the P is the reference time, from which future times
           ! will be taken. The date after the P is the frequency with which the
           ! file changes. For example, if the data is referenced to 1985 and
           ! there is 1 file per year, the reference time should be
           ! 1985-01-01T00:00:00P0001-00-00T00:00:00
           ! Get refference time, if not provided use current model date
           pindex=index(item%FileReffTime,'P')
           if (pindex==0) then
              _FAIL( 'ERROR: File template ' // item%file // ' has invalid reference date format')
           end if
           cReffTime = item%FileReffTime(1:pindex-1)
           if (trim(cReffTime) == '') then
              item%reff_time = Time
           else
              call MAPL_NCIOParseTimeUnits(cReffTime,iyy,imm,idd,ihh,imn,isc,status)
              _VERIFY(STATUS)
              call ESMF_TimeSet(item%reff_time,yy=iyy,mm=imm,dd=idd,h=ihh,m=imn,s=isc,rc=status)
              _VERIFY(STATUS)
           end if
           ! now get time interval. Put 0000-00-00 in front if not there so parsetimeunits doesn't complain
           ctInt = item%FileReffTime(pindex+1:)
           cindex = index(ctInt,'T')
           if (cindex == 0) ctInt = '0000-00-00T'//trim(ctInt)
           call MAPL_NCIOParseTimeUnits(ctInt,iyy,imm,idd,ihh,imn,isc,status)
           _VERIFY(STATUS)
           call ESMF_TimeIntervalSet(item%frequency,yy=iyy,mm=imm,d=idd,h=ihh,m=imn,s=isc,rc=status)
           _VERIFY(STATUS)
        end if
        if (lgr%isEnabledFor(DEBUG)) then
           call lgr%debug(' >> REFFTIME for %a~: %a',trim(item%file), '<'//trim(item%FileReffTime)//'>')
           call ESMF_TimeGet(item%reff_time,yy=iyy,mm=imm,dd=idd,h=ihh,m=imn,s=isc,rc=status)
           call lgr%debug(' >> Reference time: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iYy, iMm, iDd, iHh, iMn, iSc)
           call ESMF_TimeIntervalGet(item%frequency,yy=iyy,mm=imm,d=idd,h=ihh,m=imn,s=isc,rc=status)
           call lgr%debug(' >> Frequency     : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iYy, iMm, iDd, iHh, iMn, iSc)
        endif
        _RETURN(ESMF_SUCCESS)
     end subroutine CreateTimeInterval
Call graph
createtimeinterval calls ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeIntervalGet, ESMF_TimeIntervalSet, ESMF_TimeSet, debug, file, filerefftime, mapl_assert, isenabledfor, mapl_ncioparsetimeunits, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_ calls createtimeinterval