create_par – MAPL
create_par Subroutine
49 statements
Source File
private subroutine create_par(this, file, unusable, mode, comm, info, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
character(len=*), intent(in) :: file
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: mode
integer, intent(in), optional :: comm
integer, intent(in), optional :: info
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create_par(this, file, unusable, mode, comm, info, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      character(len=*), intent(in) :: file
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: mode
      integer, optional, intent(in) :: comm
      integer, optional, intent(in) :: info
      integer, optional, intent(out) :: rc
      integer :: comm_
      integer :: info_
      integer :: status
      integer :: mode_
      integer :: pfio_mode
      if (present(mode)) then
         pfio_mode=mode
      else
         pfio_mode=PFIO_NOCLOBBER
      end if
      select case (pfio_mode)
      case (pFIO_CLOBBER)
         mode_ = NF90_CLOBBER
      case (pFIO_NOCLOBBER)
         mode_ = NF90_NOCLOBBER
      end select
      if (present(comm)) then
         comm_ = comm
      else
         comm_ = MPI_COMM_WORLD
      end if
      if (present(info)) then
         info_ = info
      else
         info_ = MPI_INFO_NULL
      end if
      this%parallel = .true.
      this%comm = comm_
      this%info = info_
      mode_ = IOR(mode_, NF90_NETCDF4)
      mode_ = IOR(mode_, NF90_SHARE)
      mode_ = IOR(mode_, NF90_MPIIO)
      !$omp critical
      status = nf90_create(file, mode_, comm=comm_, info=info_, ncid=this%ncid)
      !$omp end critical
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine create_par
Call graph
create_par calls nf90_create, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_bundlewritencpar calls create_par
run calls create_par
write_metadata calls create_par
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
main calls write_metadata, run
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile