create_output_bundle – MAPL
create_output_bundle Subroutine
39 statements
Source File
private subroutine create_output_bundle(this, rc)
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Contents
Source Code
create_output_bundle
Source Code
      subroutine create_output_bundle(this,rc)
         class(HistoryTrajectory), intent(inout) :: this
         integer, optional, intent(out) :: rc
         integer :: status
         type(GriddedIOitemVectorIterator) :: iter
         type(GriddedIOitem), pointer :: item
         type(ESMF_Field) :: src_field,dst_field
         integer :: rank,lb(1),ub(1)
         this%output_bundle = ESMF_FieldBundleCreate(_RC)
         iter = this%items%begin()
         do while (iter /= this%items%end())
            item => iter%get()
            if (item%itemType == ItemTypeScalar) then
               call ESMF_FieldBundleGet(this%bundle,trim(item%xname),field=src_field,_RC)
               call ESMF_FieldGet(src_field,rank=rank,_RC)
               if (rank==2) then
                  dst_field = ESMF_FieldCreate(this%root_locstream,name=trim(item%xname), &
                     typekind=ESMF_TYPEKIND_R4,_RC)
               else if (rank==3) then
                  call ESMF_FieldGet(src_field,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
                  if (this%vdata%lm/=(ub(1)-lb(1)+1)) then
                     lb(1)=1
                     ub(1)=this%vdata%lm
                  end if
                  dst_field = ESMF_FieldCreate(this%root_locstream,name=trim(item%xname), &
                     typekind=ESMF_TYPEKIND_R4,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
               end if
               call MAPL_FieldBundleAdd(this%output_bundle,dst_field,_RC)
            else if (item%itemType == ItemTypeVector) then
               _FAIL("ItemTypeVector not yet supported")
            end if
            call iter%next()
         enddo
      end subroutine create_output_bundle
Call graph
create_output_bundle calls esmf_fieldbundlecreate, mapl_verify, esmf_fieldget, esmf_fieldcreate, esmf_fieldbundleget, mapl_fieldbundleadd, mapl_assert
mapl_verify calls mapl_throw_exception
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_verify, esmf_fieldget, esmf_fieldbundleadd, esmf_attributeget, esmf_attributeremove, esmf_attributeset, mapl_return