createFileLevBracket – MAPL
createFileLevBracket Subroutine
38 statements
Source File
private subroutine createFileLevBracket(item, cf, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_Config), intent(inout) :: cf
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
createFileLevBracket
Source Code
  subroutine createFileLevBracket(item,cf,rc)
     type(PrimaryExport), intent(inout) :: item
     type(ESMF_Config), intent(inout) :: cf
     integer, optional, intent(out) :: rc
     integer :: status
     type (ESMF_Grid) :: grid, newgrid
     if (item%vartype==MAPL_FieldItem) then
        call ESMF_FieldGet(item%modelGridFields%v1_finterp1,grid=grid,_RC)
        newGrid = MAPL_ExtDataGridChangeLev(grid,cf,item%lm,_RC)
        call ESMF_FieldGet(item%modelGridFields%v1_finterp1,grid=grid,_RC)
        item%modelGridFields%v1_faux1 = MAPL_FieldCreate(item%modelGridFields%v1_finterp1,newGrid,lm=item%lm,newName=trim(item%var),_RC)
        item%modelGridFields%v1_faux2 = MAPL_FieldCreate(item%modelGridFields%v1_finterp2,newGrid,lm=item%lm,newName=trim(item%var),_RC)
     else if (item%vartype==MAPL_ExtDataVectorItem) then
        call ESMF_FieldGet(item%modelGridFields%v1_finterp1,grid=grid,_RC)
        newGrid = MAPL_ExtDataGridChangeLev(grid,cf,item%lm,_RC)
        call ESMF_FieldGet(item%modelGridFields%v1_finterp1,grid=grid,_RC)
        item%modelGridFields%v1_faux1 = MAPL_FieldCreate(item%modelGridFields%v1_finterp1,newGrid,lm=item%lm,newName=trim(item%fcomp1),_RC)
        item%modelGridFields%v1_faux2 = MAPL_FieldCreate(item%modelGridFields%v1_finterp2,newGrid,lm=item%lm,newName=trim(item%fcomp1),_RC)
        call ESMF_FieldGet(item%modelGridFields%v1_finterp1,grid=grid,_RC)
        item%modelGridFields%v2_faux1 = MAPL_FieldCreate(item%modelGridFields%v2_finterp1,newGrid,lm=item%lm,newName=trim(item%fcomp2),_RC)
        item%modelGridFields%v2_faux2 = MAPL_FieldCreate(item%modelGridFields%v2_finterp2,newGrid,lm=item%lm,newName=trim(item%fcomp2),_RC)
     end if
     _RETURN(_SUCCESS)
  end subroutine createFileLevBracket
Call graph
createfilelevbracket calls esmf_fieldget, mapl_fieldcreate, mapl_extdatagridchangelev, mapl_return, mapl_verify
mapl_fieldcreate calls mapl_fieldcreatenewgrid, mapl_fieldcreater4, mapl_fieldcreaterename
mapl_extdatagridchangelev calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_ConfigGetAttribute, ESMF_GridGet, mapl_configsetattribute, make_grid, mapl_configcreate, mapl_gridget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_fieldcreatenewgrid calls mapl_fieldcreatenewgrid
mapl_fieldcreater4 calls mapl_fieldcreater4
mapl_fieldcreaterename calls mapl_fieldcreaterename
get_error_message calls at
mapl_configcreate calls ESMF_ConfigCreate
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_throw_exception calls initialize
initialize_ calls createfilelevbracket