CreateFileMetaData – MAPL
CreateFileMetaData Subroutine
110 statements
Source File
private subroutine CreateFileMetaData(this, items, bundle, timeInfo, vdata, ogrid, global_attributes, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout), target :: this
type(GriddedIOitemVector), intent(inout), target :: items
type(ESMF_FieldBundle), intent(inout) :: bundle
type(timeData), intent(inout) :: timeInfo
type(verticalData), intent(inout), optional :: vdata
type(ESMF_Grid), intent(inout), optional, pointer :: ogrid
type(StringStringMap), intent(in), optional, target :: global_attributes
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine CreateFileMetaData(this,items,bundle,timeInfo,vdata,ogrid,global_attributes,rc)
        class (MAPL_GriddedIO), target, intent(inout) :: this
        type(GriddedIOitemVector), target, intent(inout) :: items
        type(ESMF_FieldBundle), intent(inout) :: bundle
        type(TimeData), intent(inout) :: timeInfo
        type(VerticalData), intent(inout), optional :: vdata
        type (ESMF_Grid), intent(inout), pointer, optional :: ogrid
        type(StringStringMap), target, intent(in), optional :: global_attributes
        integer, intent(out), optional :: rc
        type(ESMF_Grid) :: input_grid
        class (AbstractGridFactory), pointer :: factory
        type(GriddedIOitemVectorIterator) :: iter
        type(GriddedIOitem), pointer :: item
        type(stringVector) :: order
        integer :: metadataVarsSize
        type(StringStringMapIterator) :: s_iter
        character(len=:), pointer :: attr_name, attr_val
        class(Variable), pointer :: coord_var
        integer :: status
        if ( allocated (this%metadata) ) deallocate(this%metadata)
        allocate(this%metadata)
        call MAPL_FieldBundleDestroy(this%output_bundle, _RC)
        this%items = items
        this%input_bundle = bundle
        this%output_bundle = ESMF_FieldBundleCreate(rc=status)
        _VERIFY(status)
        this%timeInfo = timeInfo
        call ESMF_FieldBundleGet(this%input_bundle,grid=input_grid,rc=status)
        _VERIFY(status)
        if (present(ogrid)) then
           this%output_grid=ogrid
        else
           call ESMF_FieldBundleGet(this%input_bundle,grid=this%output_grid,rc=status)
           _VERIFY(status)
        end if
        this%regrid_handle => new_regridder_manager%make_regridder(input_grid,this%output_grid,this%regrid_method,hints=this%regrid_hints,rc=status)
        _VERIFY(status)
        ! We get the regrid_method here because in the case of Identity, we set it to
        ! REGRID_METHOD_IDENTITY in the regridder constructor if identity. Now we need
        ! to change the regrid_method in the GriddedIO object to be the same as the
        ! the regridder object.
        this%regrid_method = this%regrid_handle%get_regrid_method()
        call ESMF_FieldBundleSet(this%output_bundle,grid=this%output_grid,rc=status)
        _VERIFY(status)
        factory => get_factory(this%output_grid,rc=status)
        _VERIFY(status)
        call factory%append_metadata(this%metadata)
        coord_var => this%metadata%get_variable('lons')
        if (associated(coord_var)) call coord_var%set_deflation(this%deflateLevel)
        coord_var => this%metadata%get_variable('lats')
        if (associated(coord_var)) call coord_var%set_deflation(this%deflateLevel)
        coord_var => this%metadata%get_variable('corner_lons')
        if (associated(coord_var)) call coord_var%set_deflation(this%deflateLevel)
        coord_var => this%metadata%get_variable('corner_lats')
        if (associated(coord_var)) call coord_var%set_deflation(this%deflateLevel)
        if (present(vdata)) then
           this%vdata=vdata
        else
           this%vdata=VerticalData(rc=status)
           _VERIFY(status)
        end if
        call this%vdata%append_vertical_metadata(this%metadata,this%input_bundle,rc=status)
        _VERIFY(status)
        this%doVertRegrid = (this%vdata%regrid_type /= VERTICAL_METHOD_NONE)
        if (this%vdata%regrid_type == VERTICAL_METHOD_ETA2LEV) call this%vdata%get_interpolating_variable(this%input_bundle,rc=status)
        _VERIFY(status)
        call this%timeInfo%add_time_to_metadata(this%metadata,rc=status)
        _VERIFY(status)
        if (.not.allocated(this%chunking)) then
           call this%set_default_chunking(rc=status)
           _VERIFY(status)
        else
           call this%check_chunking(this%vdata%lm,_RC)
        end if
        order = this%metadata%get_order(rc=status)
        _VERIFY(status)
        metadataVarsSize = order%size()
        ! If quantize algorithm is set, create a quantization_info variable
        if (this%quantizeAlgorithm /= MAPL_NOQUANTIZE) then
           call this%CreateQuantizationInfo(_RC)
        end if
        iter = this%items%begin()
        do while (iter /= this%items%end())
           item => iter%get()
           if (item%itemType == ItemTypeScalar) then
              call this%CreateVariable(item%xname,rc=status)
              _VERIFY(status)
           else if (item%itemType == ItemTypeVector) then
              call this%CreateVariable(item%xname,rc=status)
              _VERIFY(status)
              call this%CreateVariable(item%yname,rc=status)
              _VERIFY(status)
           end if
           call iter%next()
        enddo
        if (this%itemOrderAlphabetical) then
           call this%alphabatize_variables(metadataVarsSize,rc=status)
           _VERIFY(status)
        end if
        if (present(global_attributes)) then
           s_iter = global_attributes%begin()
           do while(s_iter /= global_attributes%end())
              attr_name => s_iter%key()
              attr_val => s_iter%value()
              call this%metadata%add_attribute(attr_name,attr_val,_RC)
              call s_iter%next()
           enddo
        end if
        _RETURN(_SUCCESS)
      end subroutine CreateFileMetaData
Call graph
createfilemetadata calls append_metadata, esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_fieldbundleset, mapl_fieldbundledestroy, key, add_attribute, make_regridder, add_time_to_metadata, alphabatize_variables, append_vertical_metadata, check_chunking, createquantizationinfo, createvariable, get_factory, get_interpolating_variable, get_order, get_regrid_method, get_variable, mapl_return, mapl_verify, set_default_chunking, set_deflation, v_begin, v_iter_get, v_iter_next
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main