create_from_bundle – MAPL
create_from_bundle Subroutine
58 statements
Source File
private subroutine create_from_bundle(this, bundle, clock, output_file, vertical_data, n_steps, time_interval, nbits_to_keep, deflate, quantize_algorithm, quantize_level, rc)
Type Bound
FieldBundleWriter
Arguments
Type Intent Optional Attributes Name
class(FieldBundleWriter), intent(inout) :: this
type(ESMF_FieldBundle), intent(inout) :: bundle
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in), optional :: output_file
type(verticalData), intent(inout), optional :: vertical_data
integer, intent(in), optional :: n_steps
integer, intent(in), optional :: time_interval
integer, intent(in), optional :: nbits_to_keep
integer, intent(in), optional :: deflate
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
create_from_bundle
Source Code
      subroutine create_from_bundle(this,bundle,clock,output_file,vertical_data,n_steps,time_interval,nbits_to_keep,deflate,quantize_algorithm,quantize_level,rc)
         class(FieldBundleWRiter), intent(inout) :: this
         type(ESMF_FieldBundle), intent(inout) :: bundle
         type(ESMF_Clock), intent(inout) :: clock
         character(len=*), optional, intent(in) :: output_file
         type(VerticalData), optional, intent(inout) :: vertical_data
         integer, optional, intent(in)  :: n_steps
         integer, optional, intent(in)  :: time_interval
         integer, optional, intent(in)  :: nbits_to_keep
         integer, optional, intent(in)  :: deflate
         integer, optional, intent(in)  :: quantize_algorithm
         integer, optional, intent(in)  :: quantize_level
         integer, optional, intent(out) :: rc
         type(TimeData) :: time_info
         integer :: num_fields,i,file_steps,collection_id,status
         character(ESMF_MAXSTR), allocatable :: field_names(:)
         type(GriddedIOItemVector) :: items
         type(GriddedIOItem) :: item
         type(ESMF_TimeInterval) :: offset
         integer :: time_interval_
         call ESMF_TimeIntervalSet(offset,s=0,rc=status)
         _VERIFY(status)
         if (present(n_steps)) then
            file_steps = n_steps
         else
            file_steps = 1
         end if
         if (present(time_interval)) then
            time_interval_=time_interval
         else
            time_interval_=0
         end if
         call this%cfio%set_param(nbits_to_keep=nbits_to_keep,deflation=deflate,quantize_algorithm=quantize_algorithm,quantize_level=quantize_level)
         time_info = TimeData(clock,file_steps,time_interval_,offset)
         call ESMF_FieldBundleGet(bundle, fieldCount=num_fields,rc=status)
         _VERIFY(status)
         allocate(field_names(num_fields),stat=status)
         _VERIFY(status)
         call ESMF_FieldBundleGet(bundle, fieldNameList=field_names,rc=status)
         _VERIFY(status)
         do i=1,num_fields
            item%itemType=ItemTypeScalar
            item%xname = trim(field_names(i))
            call items%push_back(item)
         enddo
         if (present(vertical_data)) then
            call this%cfio%createFileMetadata(items,bundle,time_info,vdata=vertical_data,rc=status)
            _VERIFY(status)
         else
            call this%cfio%createFileMetadata(items,bundle,time_info,rc=status)
            _VERIFY(status)
         end if
         if (present(output_file)) this%file_name = output_file
         collection_id = o_clients%add_hist_collection(this%cfio%metadata)
         call this%cfio%set_param(write_collection_id=collection_id)
         _RETURN(_SUCCESS)
      end subroutine create_from_bundle
Call graph
create_from_bundle calls ESMF_TimeIntervalSet, add_hist_collection, esmf_fieldbundleget, mapl_return, mapl_verify, push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
write_bundle_single_time calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time