create_aux_field – MAPL
create_aux_field Subroutine
36 statements
Source File
private subroutine create_aux_field(item, extDataState, old_item, rank, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_State), intent(inout) :: extDataState
type(PrimaryExport), intent(inout) :: old_item
integer, intent(in) :: rank
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine create_aux_field(item,ExtDataState,old_item,rank,rc)
     type(PrimaryExport), intent(inout) :: item
     type(ESMF_State), intent(inout) :: extDataState
     type(PrimaryExport), intent(inout) :: old_item
     integer, intent(in) :: rank
     integer, intent(out), optional :: rc
     integer :: status
     type(ESMF_Field) :: field,new_field
     type(ESMF_Grid)  :: grid
     type(ESMF_StateItem_Flag) :: item_type
     call ESMF_StateGet(ExtDataState,trim(old_item%name),field,_RC)
     if (index(old_item%file_template,"/dev/null")/=0) then
        _RETURN(_SUCCESS)
     end if
     call ESMF_StateGet(ExtDataState, itemName=item%name, itemType=item_type, _RC)
     if (item_type == ESMF_STATEITEM_FIELD) then
        _RETURN(_SUCCESS)
     end if
     call ESMF_FieldGet(field,grid=grid,_RC)
     if (rank==2) then
        new_field=ESMF_FieldCreate(grid,name=item%name,typekind=ESMF_TYPEKIND_R4,_RC)
     else if (rank==3) then
        new_field=ESMF_FieldCreate(grid,name=item%name,typekind=ESMF_TYPEKIND_R4, &
         ungriddedLBound=[1], ungriddedUBound=[item%vcoord%num_levels],_RC)
     end if
     call MAPL_StateAdd(ExtDataState,new_field,_RC)
     _RETURN(_SUCCESS)
  end subroutine create_aux_field
Call graph
create_aux_field calls esmf_fieldcreate, esmf_fieldget, esmf_stateget, mapl_stateadd, mapl_return, mapl_verify
mapl_stateadd calls mapl_stateaddbundle, mapl_stateaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_stateaddbundle calls mapl_stateaddbundle, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldbundleget, esmf_stateadd
mapl_stateaddfield calls mapl_stateaddfield, esmf_fieldget, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_stateadd
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_ calls create_aux_field