create_field_from_field – MAPL
create_field_from_field Function
21 statements
Source File
private function create_field_from_field(input_field, rc) result(output_field)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: input_field
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Called by
Call graph
create_field_from_field calls esmf_fieldcreate, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
evaluate_box_mask calls create_field_from_field
evaluate_region_mask calls create_field_from_field
evaluate_zone_mask calls create_field_from_field
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
evaluate_derived_field calls evaluate_mask
run_ calls evaluate_derived_field