create_member_subcommunicator – MAPL
create_member_subcommunicator Function
25 statements
Source File
private function create_member_subcommunicator(this, comm, unusable, rc) result(subcommunicator)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
integer, intent(in) :: comm
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function create_member_subcommunicator(this, comm, unusable, rc) result(subcommunicator)
      class (MAPL_Cap), intent(inout) :: this
      integer, intent(in) :: comm
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (SplitCommunicator) :: split_comm
      integer :: status
      character(:), allocatable :: dir_name
!!$      external :: chdir
      _UNUSED_DUMMY(unusable)
      subcommunicator = MPI_COMM_NULL ! in case of failure
      this%splitter = SimpleCommSplitter(comm, this%cap_options%n_members, this%npes_member, base_name=this%cap_options%ensemble_subdir_prefix)
      split_comm = this%splitter%split(rc=status); _VERIFY(status)
      subcommunicator = split_comm%get_subcommunicator()
      if (this%cap_options%n_members > 1) then
         dir_name = split_comm%get_name()
         status = c_chdir(dir_name)
         _VERIFY(status)
      end if
      _RETURN(_SUCCESS)
   end function create_member_subcommunicator
Call graph
create_member_subcommunicator calls c_chdir, get_name, get_subcommunicator, mapl_return, mapl_verify, split
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
split calls mapl_return, mapl_verify, mapl_assert, mpi_comm_split, at, compute_color, get_shared_communicator
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
compute_color calls mapl_return, mapl_verify, at, get_shared_communicator, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, comm_group_range, get_node_id, get_node_sizes
get_error_message calls at, insert
mapl_throw_exception calls initialize
comm_group_range calls mapl_return, mapl_assert
get_node_id calls mapl_return, mapl_verify, get_shared_communicator, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, mpi_allgather, mpi_bcast, mpi_comm_size
get_node_sizes calls mapl_return, mapl_verify, get_shared_communicator, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, mpi_allgather, mpi_comm_size
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_at_32 calls v_at_size_kind
initialize_p0 calls create_member_subcommunicator
run_ensemble calls create_member_subcommunicator
run calls run_ensemble