create_locstream_on_proc – MAPL
create_locstream_on_proc Function
28 statements
Source File
private function create_locstream_on_proc(this, unusable, grid, rc) result(locstream)
Type Bound
LocStreamFactory
Arguments
Type Intent Optional Attributes Name
class(LocStreamFactory) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Grid), optional :: grid
integer, intent(out), optional :: rc
Return Value type(ESMF_LocStream)
Calls
Called by
Source Code
      function create_locstream_on_proc (this,unusable,grid,rc) result(locstream)
         type(ESMF_LocStream) :: locstream
         class (LocStreamFactory) :: this
         class (KeywordEnforcer), optional, intent(in) :: unusable
         type(ESMF_Grid), optional :: grid
         integer, optional, intent(out) :: rc
         integer :: local_count,status
         real(kind=REAL64), allocatable :: tlons(:),tlats(:)
         local_count = size(this%lons)
         allocate(tlons(size(this%lons)),source=this%lons,stat=status)
         _VERIFY(status)
         allocate(tlats(size(this%lats)),source=this%lats,stat=status)
         _VERIFY(status)
         tlons=tlons*MAPL_PI_R8/180.0d0
         tlats=tlats*MAPL_PI_R8/180.0d0
         locstream = ESMF_LocStreamCreate(localCount=local_count,coordSys=ESMF_COORDSYS_SPH_RAD,_RC)
         call ESMF_LocStreamAddKey(locstream,keyName="ESMF:Lat",farray=tlats,datacopyflag=ESMF_DATACOPY_VALUE, &
                 keyUnits="Radians", keyLongName="Latitude",_RC)
         call ESMF_LocStreamAddKey(locstream,keyName="ESMF:Lon",farray=tlons,datacopyflag=ESMF_DATACOPY_VALUE, &
                 keyUnits="Radians", keyLongName="Longitude",_RC)
         if (present(grid)) then
            locstream = ESMF_LocStreamCreate(locstream,background=grid,_RC)
         end if
         _RETURN(_SUCCESS)
       end function create_locstream_on_proc
Call graph
create_locstream_on_proc calls ESMF_LocStreamAddKey, ESMF_LocStreamCreate, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_geosat_grid_find_mask calls create_locstream_on_proc, create_geosat_grid_find_mask
create_grid calls create_locstream_on_proc
new_stationsampler_readfile calls create_locstream_on_proc
stationsampler calls new_stationsampler_readfile
initialize_ calls create_geosat_grid_find_mask, initialize_