create_grid – MAPL
create_grid Subroutine
35 statements
Source File
public subroutine create_grid(this, grid_name, rc)
Arguments
Type Intent Optional Attributes Name
class(regrid_support) :: this
character(len=*), intent(in) :: grid_name
integer, intent(out), optional :: rc
Calls
Contents
Source Code
create_grid
Source Code
    subroutine create_grid(this,grid_name,rc)
    class(regrid_support) :: this
    character(len=*), intent(in) :: grid_name
    integer, optional, intent(out) :: rc
    type (FileMetaDataUtils) :: metadata
    type (FileMetaData) :: basic_metadata
    character(len=:),allocatable :: lev_name
    integer :: im_world,jm_world,lm_world
    type(NetCDF4_FileFormatter) :: formatter
    character(len=:), allocatable :: filename
    character(len=2) :: dateline,pole
    integer :: status
    type(ESMF_CONFIG) :: cfoutput
    filename = this%filenames%at(1)
    call formatter%open(trim(filename),pFIO_Read,_RC)
    basic_metadata=formatter%read(_RC)
    call metadata%create(basic_metadata,trim(filename))
    call formatter%close(_RC)
    lm_world=0
    lev_name=metadata%get_level_name()
    if (trim(lev_name)/='') then
       lm_world = metadata%get_dimension(lev_name,_RC)
    end if
    call UnpackGridName(Grid_name,im_world,jm_world,dateline,pole)
    cfoutput = create_cf(grid_name,im_world,jm_world,this%nx,this%ny,lm_world,this%cs_stretch_param,this%lon_range,this%lat_range,this%tripolar_file_out,_RC)
    this%new_grid=grid_manager%make_grid(cfoutput,prefix=trim(grid_name)//".",_RC)
    _RETURN(_SUCCESS)
    end subroutine create_grid
Call graph
create_grid calls mapl_verify, create_cf, unpackgridname, mapl_return
mapl_verify calls mapl_throw_exception
create_cf calls mapl_verify, mapl_configsetattribute, mapl_configcreate, mapl_assert
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_configsetattribute calls mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configcreate calls esmf_configcreate
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_configsetattribute_real32 calls mapl_return, esmf_configgetattribute
mapl_configsetattribute_real64 calls mapl_return, esmf_configgetattribute
mapl_configsetattribute_int32 calls mapl_return, esmf_configgetattribute
mapl_configsetattribute_ints32 calls mapl_verify, mapl_return, mapl_configsetattribute, mapl_assert
mapl_configsetattribute_reals32 calls mapl_verify, mapl_return, mapl_configsetattribute, mapl_assert
mapl_configsetattribute_string calls mapl_return, esmf_configgetattribute
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message