create_bracketing_fields – MAPL
create_bracketing_fields Subroutine
191 statements
Source File
private subroutine create_bracketing_fields(item, extDataState, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_State), intent(inout) :: extDataState
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine create_bracketing_fields(item,ExtDataState,rc)
     type(PrimaryExport), intent(inout) :: item
     type(ESMF_State), intent(inout) :: extDataState
     integer, intent(out), optional :: rc
     integer :: status,lm,fieldRank
     type(ESMF_Field) :: field,left_field,right_field
     type(ESMF_Grid)  :: grid,bracket_grid
     real(kind=REAL32), pointer :: ptr3d(:,:,:)
     character(len=ESMF_MAXPATHLEN) :: file_left, file_right, filename
     logical :: found_file
     type(FileMetadataUtils), pointer :: metadata
     type(MAPLDataCollection), pointer :: collection
     type(ESMF_Field) :: temp_field
     if (item%modelGridFields%initialized) then
        _RETURN(_SUCCESS)
     else
        found_file = .false.
        call item%modelGridFields%comp1%get_parameters('L',file=file_left)
        if (trim(file_left) /= file_not_found) then
           filename = file_left
           found_file = .true.
        else
           call item%modelGridFields%comp1%get_parameters('R',file=file_right)
           if (trim(file_right) /= file_not_found) then
              filename = file_right
              found_file = .true.
           end if
        end if
        if (found_file) then
           collection => DataCollections%at(item%pfioCollection_id)
           metadata => collection%find(filename,_RC)
           item%file_metadata = metadata
           item%modelGridFields%initialized = .true.
        end if
     end if
     if (found_file) then
        item%iclient_collection_id=i_clients%add_ext_collection(trim(item%file_template))
        item%t_interp_bundle = ESMF_FieldBundleCreate(_RC)
        if (item%vartype == MAPL_FieldItem) then
           call ESMF_StateGet(ExtDataState, trim(item%name), field,_RC)
           call ESMF_FieldGet(field,grid=grid,rank=fieldRank,_RC)
           lm=0
           if (fieldRank==3) then
              call ESMF_FieldGet(field,0,farrayPtr=ptr3d,_RC)
              lm = size(ptr3d,3)
           end if
           if (item%vcoord%num_levels /= lm .and. lm /= 0 .and. (item%vcoord%vertical_type == model_pressure)) then
              item%do_VertInterp = .true.
           else if (item%vcoord%num_levels /= lm .and. lm /= 0 .and. item%vcoord%num_levels /= 0) then
              item%do_Fill = .true.
           end if
           bracket_grid = MAPL_ExtDataGridChangeLev(grid,item%vcoord%num_levels,_RC)
           left_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%fcomp1),_RC)
           call set_field_units(left_field, item%units, _RC)
           call set_mw(left_field, item, _RC)
           right_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%fcomp1),_RC)
           call set_field_units(right_field, item%units, _RC)
           call set_mw(right_field, item, _RC)
           if ((item%vcoord%num_levels /= lm) .and. (lm > 0)) then
              temp_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%vcomp1),_RC)
              call set_field_units(temp_field, item%units, _RC)
              call set_mw(temp_field, item, _RC)
              call MAPL_FieldBundleAdd(item%t_interp_bundle, temp_field, _RC)
           else
              call MAPL_FieldBundleAdd(item%t_interp_bundle, field, _RC)
           end if
           call item%modelGridFields%comp1%set_parameters(left_field=left_field,right_field=right_field, _RC)
        else if (item%vartype == MAPL_VectorField) then
           call ESMF_StateGet(ExtDataState, trim(item%vcomp1), field,_RC)
           call ESMF_FieldGet(field,grid=grid,rank=fieldRank,_RC)
           lm = 0
           if (fieldRank==3) then
              call ESMF_FieldGet(field,0,farrayPtr=ptr3d,_RC)
              lm = size(ptr3d,3)
           end if
           if (item%vcoord%num_levels /= lm .and. lm /= 0 .and. (item%vcoord%vertical_type == model_pressure)) then
              item%do_VertInterp = .true.
           else if (item%vcoord%num_levels /= lm .and. lm /= 0 .and. item%vcoord%num_levels /= 0) then
              item%do_Fill = .true.
           end if
           bracket_grid = MAPL_ExtDataGridChangeLev(grid,item%vcoord%num_levels,_RC)
           left_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%fcomp1),_RC)
           call set_field_units(left_field, item%units, _RC)
           _HERE
           call set_mw(left_field, item, _RC)
           right_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%fcomp1),_RC)
           call set_field_units(right_field, item%units, _RC)
           _HERE
           call set_mw(right_field, item, _RC)
           call item%modelGridFields%comp1%set_parameters(left_field=left_field,right_field=right_field, _RC)
           if (item%vcoord%num_levels /= lm) then
              temp_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%vcomp1),_RC)
              call set_field_units(temp_field, item%units, _RC)
           _HERE
              call set_mw(temp_field, item, _RC)
              call MAPL_FieldBundleAdd(item%t_interp_bundle, temp_field, _RC)
           else
              call MAPL_FieldBundleAdd(item%t_interp_bundle, field, _RC)
           end if
           call ESMF_StateGet(ExtDataState, trim(item%vcomp2), field,_RC)
           left_field = MAPL_FieldCreate(field,item%fcomp2,doCopy=.true.,_RC)
           call set_field_units(left_field, item%units, _RC)
           call set_mw(left_field, item, _RC)
           right_field = MAPL_FieldCreate(field,item%fcomp2,doCopy=.true.,_RC)
           call set_field_units(right_field, item%units, _RC)
           call set_mw(right_field, item, _RC)
           call item%modelGridFields%comp2%set_parameters(left_field=left_field,right_field=right_field, _RC)
           if (item%vcoord%num_levels /= lm) then
              temp_field = MAPL_FieldCreate(field,bracket_grid,lm=item%vcoord%num_levels,newName=trim(item%vcomp2),_RC)
              call set_field_units(temp_field, item%units, _RC)
              call set_mw(temp_field, item, _RC)
              call MAPL_FieldBundleAdd(item%t_interp_bundle, temp_field, _RC)
           else
              call MAPL_FieldBundleAdd(item%t_interp_bundle, field, _RC)
           end if
        end if
     end if
     _RETURN(_SUCCESS)
     contains
     subroutine set_field_units(field, units, rc)
        type(ESMF_Field), intent(inout) :: field
        character(len=*), intent(in) :: units
        integer, optional, intent(out) :: rc
        integer :: status
        call ESMF_AttributeSet(field,name='UNITS',value=units, _RC)
        _RETURN(_SUCCESS)
     end subroutine set_field_units
     subroutine set_mw(field, item, rc)
        type(ESMF_Field), intent(inout) :: field
        type(PrimaryExport), intent(inout) :: item
        integer, optional, intent(out) :: rc
        integer :: status
        if (allocated(item%molecular_weight)) then
           call ESMF_AttributeSet(field,name='molecular_weight',value=item%molecular_weight, _RC)
        end if
        _RETURN(_SUCCESS)
     end subroutine set_mw
  end subroutine create_bracketing_fields
Call graph
create_bracketing_fields calls ESMF_AttributeSet, esmf_fieldbundlecreate, esmf_fieldget, esmf_stateget, mapl_fieldbundleadd, mapl_fieldcreate, at, add_ext_collection, find, get_parameters, mapl_extdatagridchangelev, mapl_return, mapl_verify, set_parameters
run_ calls create_bracketing_fields