CreateQuantizationInfo – MAPL
CreateQuantizationInfo Subroutine
29 statements
Source File
private subroutine CreateQuantizationInfo(this, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine CreateQuantizationInfo(this,rc)
        class (MAPL_GriddedIO), intent(inout) :: this
        integer, optional, intent(out) :: rc
        integer :: status
        class (AbstractGridFactory), pointer :: factory
        character(len=:), allocatable :: varName, netcdf_version
        type(Variable) :: v
        factory => get_factory(this%output_grid,_RC)
        v = Variable(type=PFIO_CHAR)
        ! In the future when we can do per variable quantization, we will need
        ! to do things like quantization_info1, quantization_info2, etc.
        ! For now, we will just use quantization_info as it is per collection
        varName = "quantization_info"
        ! We need to convert the quantization algorithm to a string
        select case (this%quantizeAlgorithm)
        case (MAPL_QUANTIZE_BITGROOM)
           call v%add_attribute('algorithm', 'bitgroom')
        case (MAPL_QUANTIZE_BITROUND)
           call v%add_attribute('algorithm', 'bitround')
        case (MAPL_QUANTIZE_GRANULAR_BITROUND)
           call v%add_attribute('algorithm', 'granular_bitround')
        case default
           _FAIL('Unknown quantization algorithm')
        end select
        ! Next add the implementation details
        ! 3. implementation: This property contains free-form text
        ! that concisely conveys the algorithm provenance, including the
        ! name of the library or client that performed the quantization,
        ! the software version, and the name of the author(s) if deemed
        ! relevant.
        !
        ! In the current case, all algorithms are from libnetcdf
        ! we make a string using nf90_inq_libvers()
        netcdf_version = 'libnetcdf ' // nf90_inq_libvers()
        call v%add_attribute('implementation', netcdf_version)
        ! NOTE: In the future if we add the MAPL bit-shaving
        ! to use the quantization parts of the code, it will
        ! need a different implementation string
        call factory%append_variable_metadata(v)
        call this%metadata%add_variable(trim(varName),v,_RC)
        _RETURN(_SUCCESS)
     end subroutine CreateQuantizationInfo
Call graph
createquantizationinfo calls append_variable_metadata, mapl_assert, nf90_inq_libvers, add_attribute, add_variable, get_factory, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_variable calls mapl_assert, mapl_return, at, begin, get, next, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
get_factory calls mapl_return, mapl_verify, get_factory, ESMF_AttributeGet, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_attribute_1d calls mapl_return, insert
get_error_message calls at, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
createfilemetadata calls createquantizationinfo
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main