create_esmf_grids – MAPL
create_esmf_grids Subroutine
11 statements
Source File
public subroutine create_esmf_grids(this, rc)
Type Bound
RegridSupport
Arguments
Type Intent Optional Attributes Name
class(RegridSupport), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create_esmf_grids(this, rc)
      class (RegridSupport), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      call this%create_cubed_sphere_grid(rc=status)
      _VERIFY(status)
      call this%create_lat_lon_grid(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine create_esmf_grids
Call graph
create_esmf_grids calls create_cubed_sphere_grid, create_lat_lon_grid, mapl_return, mapl_verify
create_cubed_sphere_grid calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridAddItem, ESMF_GridCreateCubedSphere, ESMF_GridGet, get_dimension, mapl_distgridget
create_lat_lon_grid calls mapl_return, mapl_verify, ESMF_GridAddCoord, ESMF_GridCreate, ESMF_GridGetCoord, mapl_range
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_range calls mapl_range_real32, mapl_range_real64
get_dimension calls mapl_return, at, find
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_throw_exception calls initialize
mapl_range_real32 calls mapl_return, mapl_assert
mapl_range_real64 calls mapl_return, mapl_assert
main calls create_esmf_grids