create_new_bundle – MAPL
create_new_bundle Module Procedure
39 statements
Source File
module procedure create_new_bundle module function create_new_bundle(this, rc) result(new_bundle) Interface →
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle)
Calls
Called by
Contents
Call graph
create_new_bundle calls esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_fieldcreate, esmf_fieldget, get, mapl_assert, mapl_fieldbundleadd, next, mapl_return, mapl_verify, create_new_bundle
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, esmf_fieldget, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldbundleadd
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize calls create_new_bundle, initialize
reinitialize calls create_new_bundle, reinitialize
destroy_rh_regen_ls calls reinitialize