create_route_handle – MAPL
create_route_handle Subroutine
147 statements
Source File
private subroutine create_route_handle(this, kind, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
type(ESMF_TypeKind_Flag), intent(in) :: kind
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create_route_handle(this, kind, rc)
     class (EsmfRegridder), intent(in) :: this
     type(ESMF_TypeKind_Flag), intent(in) :: kind
     integer, optional, intent(out) :: rc
     integer :: status
     character(len=*), parameter :: Iam = 'create_route_handle'
     type (RegridderSpec) :: spec
     real, pointer :: src_dummy_r4(:,:), dst_dummy_r4(:,:)
     real(real64), pointer :: src_dummy_r8(:,:), dst_dummy_r8(:,:)
     type (ESMF_Field) :: src_field, dst_field
     integer :: srcTermProcessing, num_mask_values
     integer, pointer :: factorIndexList(:,:)
     integer, allocatable :: dstMaskValues(:)
     real(ESMF_KIND_R8), pointer :: factorList(:)
     type(ESMF_RouteHandle) :: dummy_rh
     type(ESMF_UnmappedAction_Flag) :: unmappedaction
     logical :: global, isPresent, has_mask, has_dstMaskValues
     type(RegridderSpecRouteHandleMap), pointer :: route_handles, transpose_route_handles
     type(ESMF_RouteHandle) :: route_handle, transpose_route_handle
     character(len=ESMF_MAXPATHLEN) :: rh_file,rh_trans_file
     logical :: rh_file_exists, file_weights, compute_transpose
     type(Logger), pointer :: lgr
     lgr => logging%get_logger('MAPL')
     if (kind == ESMF_TYPEKIND_R4) then
        route_handles => route_handles_r4
        transpose_route_handles => transpose_route_handles_r4
     else if(kind == ESMF_TYPEKIND_R8) then
        route_handles => route_handles_r8
        transpose_route_handles => transpose_route_handles_r8
     else
        _FAIL('unsupported type kind (must be R4 or R8)')
     end if
     unmappedaction = ESMF_UNMAPPEDACTION_ERROR
     spec = this%get_spec()
     if (route_handles%count(spec) == 0) then  ! new route_handle
        file_weights = IAND(spec%hints,REGRID_HINT_FILE_WEIGHTS) /= 0
        compute_transpose = IAND(spec%hints,REGRID_HINT_COMPUTE_TRANSPOSE) /= 0
        if (file_weights) then
           rh_file = generate_rh_name(spec%grid_in,spec%grid_out,spec%regrid_method,_RC)
           rh_trans_file = "transpose_"//rh_file
           inquire(file=rh_file,exist=rh_file_exists)
        else
           rh_file_exists = .false.
        end if
        if (rh_file_exists) then
           call lgr%info('Reading weight file: %a', trim(rh_file))
           route_handle = ESMF_RouteHandleCreate(rh_file,_RC)
           call route_handles%insert(spec, route_handle)
           if (compute_transpose) then
              transpose_route_handle = ESMF_RouteHandleCreate(rh_trans_file,_RC)
              call transpose_route_handles%insert(spec, transpose_route_handle)
           end if
        else
           src_field = ESMF_FieldCreate(spec%grid_in, typekind=kind, &
                & indexflag=ESMF_INDEX_DELOCAL, staggerloc=ESMF_STAGGERLOC_CENTER, rc=status)
           _VERIFY(status)
           if (MAPL_GridHasDE(spec%grid_in)) then
              if (kind == ESMF_TYPEKIND_R4) then
                 call ESMF_FieldGet(src_field, localDe=0, farrayPtr=src_dummy_r4, rc=status)
                 _VERIFY(status)
                 src_dummy_r4 = 0
              else if (kind == ESMF_TYPEKIND_R8) then
                 call ESMF_FieldGet(src_field, localDe=0, farrayPtr=src_dummy_r8, rc=status)
                 _VERIFY(status)
                 src_dummy_r8 = 0
              end if
           end if
           dst_field = ESMF_FieldCreate(spec%grid_out, typekind=kind, &
                & indexflag=ESMF_INDEX_DELOCAL, staggerloc=ESMF_STAGGERLOC_CENTER, rc=status)
           _VERIFY(status)
           if (MAPL_GridHasDE(spec%grid_out)) then
              if (kind == ESMF_TYPEKIND_R4) then
                 call ESMF_FieldGet(dst_field, localDe=0, farrayPtr=dst_dummy_r4, rc=status)
                 _VERIFY(status)
                 dst_dummy_r4 = 0
              else if (kind == ESMF_TYPEKIND_R8) then
                 call ESMF_FieldGet(dst_field, localDe=0, farrayPtr=dst_dummy_r8, rc=status)
                 _VERIFY(status)
                 dst_dummy_r8 = 0
              end if
           end if
           call ESMF_GridGetItem(spec%grid_out,itemflag=ESMF_GRIDITEM_MASK, &
           staggerloc=ESMF_STAGGERLOC_CENTER, isPresent = has_mask, _RC)
           call ESMF_AttributeGet(spec%grid_out, name=MAPL_DESTINATIONMASK, isPresent=has_dstMaskValues, _RC)
           if (has_dstMaskValues) then
              _ASSERT(has_mask, "masking destination values when no masks is present")
              call ESMF_AttributeGet(spec%grid_out, name=MAPL_DESTINATIONMASK, itemcount=num_mask_values, _RC)
              allocate(dstMaskValues(num_mask_values), _STAT)
              call ESMF_AttributeGet(spec%grid_out, name=MAPL_DESTINATIONMASK, valuelist=dstMaskValues, _RC)
           end if
           counter = counter + 1
           srcTermProcessing=0
           call ESMF_AttributeGet(spec%grid_in, name='Global',isPresent=isPresent,rc=status)
           if (isPresent) then
              call ESMF_AttributeGet(spec%grid_in, name='Global',value=global,rc=status)
              if (.not.global) unmappedaction=ESMF_UNMAPPEDACTION_IGNORE
           end if
           select case (spec%regrid_method)
           case (REGRID_METHOD_BILINEAR, REGRID_METHOD_BILINEAR_MONOTONIC)
              call ESMF_FieldRegridStore(src_field, dst_field, &
                   & regridmethod=ESMF_REGRIDMETHOD_BILINEAR, &
                   & dstMaskValues = dstMaskValues, &
                   & linetype=ESMF_LINETYPE_GREAT_CIRCLE, & ! closer to SJ Lin interpolation weights?
                   & srcTermProcessing = srcTermProcessing, &
                   & factorList=factorList, factorIndexList=factorIndexList, &
                   & routehandle=route_handle, unmappedaction=unmappedaction, rc=status)
              _VERIFY(status)
           case (REGRID_METHOD_PATCH)
              call ESMF_FieldRegridStore(src_field, dst_field, &
                   & regridmethod=ESMF_REGRIDMETHOD_PATCH, &
                   & dstMaskValues = dstMaskValues, &
                   & linetype=ESMF_LINETYPE_GREAT_CIRCLE, & ! closer to SJ Lin interpolation weights?
                   & srcTermProcessing = srcTermProcessing, &
                   & factorList=factorList, factorIndexList=factorIndexList, &
                   & routehandle=route_handle, unmappedaction=unmappedaction, rc=status)
              _VERIFY(status)
           case (REGRID_METHOD_CONSERVE_2ND)
              call ESMF_FieldRegridStore(src_field, dst_field, &
                   & regridmethod=ESMF_REGRIDMETHOD_CONSERVE_2ND, &
                   & dstMaskValues = dstMaskValues, &
                   & linetype=ESMF_LINETYPE_GREAT_CIRCLE, & ! closer to SJ Lin interpolation weights?
                   & srcTermProcessing = srcTermProcessing, &
                   & factorList=factorList, factorIndexList=factorIndexList, &
                   & routehandle=route_handle, unmappedaction=unmappedaction, rc=status)
              _VERIFY(status)
           case (REGRID_METHOD_CONSERVE, REGRID_METHOD_CONSERVE_MONOTONIC, REGRID_METHOD_VOTE, REGRID_METHOD_FRACTION)
              call ESMF_FieldRegridStore(src_field, dst_field, &
                   & regridmethod=ESMF_REGRIDMETHOD_CONSERVE, &
                   & dstMaskValues = dstMaskValues, &
                   & srcTermProcessing = srcTermProcessing, &
                   & factorList=factorList, factorIndexList=factorIndexList, &
                   & routehandle=route_handle, unmappedaction=unmappedaction, rc=status)
              _VERIFY(status)
           case (REGRID_METHOD_NEAREST_STOD)
              call ESMF_FieldRegridStore(src_field, dst_field, &
                   & regridmethod=ESMF_REGRIDMETHOD_NEAREST_STOD, &
                   & dstMaskValues = dstMaskValues, &
                   & factorList=factorList, factorIndexList=factorIndexList, &
                   & routehandle=route_handle, unmappedaction=unmappedaction, rc=status)
              _VERIFY(status)
           case default
              _FAIL('unknown regrid method')
           end select
           call route_handles%insert(spec, route_handle)
           if (compute_transpose) then
              call ESMF_FieldSMMStore(src_field,dst_field,dummy_rh,transpose_route_handle, &
                  & factorList,factorIndexList,srcTermProcessing=srcTermProcessing, &
                  & rc=status)
              _VERIFY(status)
              call transpose_route_handles%insert(spec, transpose_route_handle)
           end if
           ! Free resources
           deallocate(factorList,factorIndexList)
           call ESMF_FieldDestroy(src_field, rc=status)
           _VERIFY(status)
           call ESMF_FieldDestroy(dst_field, rc=status)
           _VERIFY(status)
           if (file_weights) then
              call lgr%info('Writing weight file: %a', trim(rh_file))
              call ESMF_RouteHandleWrite(route_handle,rh_file,_RC)
              if (compute_transpose) then
                 call lgr%info('Writing transpose weight file: %a', trim(rh_trans_file))
                 call ESMF_RouteHandleWrite(transpose_route_handle,rh_trans_file,_RC)
              end if
           end if
        end if
     end if
     _RETURN(_SUCCESS)
   end subroutine create_route_handle
Call graph
create_route_handle calls ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, ESMF_GridGetItem, ESMF_RouteHandleCreate, ESMF_RouteHandleWrite, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_assert, get_logger, insert, generate_rh_name, get_spec, info, mapl_gridhasde, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
generate_rh_name calls mapl_return, mapl_verify, mapl_gridget
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
initialize_subclass calls create_route_handle
select_route_handle calls create_route_handle
do_regrid calls select_route_handle
regrid_scalar_2d_real32 calls do_regrid
regrid_scalar_2d_real64 calls do_regrid
regrid_scalar_3d_real32 calls do_regrid
regrid_scalar_3d_real64 calls do_regrid
regrid_vector_2d_real32 calls do_regrid
regrid_vector_2d_real64 calls do_regrid
regrid_vector_3d_real32 calls do_regrid
regrid_vector_3d_real64 calls do_regrid
transpose_regrid_scalar_2d_real32 calls do_regrid
transpose_regrid_scalar_3d_real32 calls do_regrid
transpose_regrid_vector_2d_real32 calls do_regrid
transpose_regrid_vector_3d_real32 calls do_regrid