create_cf – MAPL
create_cf Function
76 statements
Source File
public function create_cf(grid_name, im_world, jm_world, nx, ny, lm, cs_stretch_param, lon_range, lat_range, tripolar_file, rc) result(cf)
Uses
MAPL_ConfigMod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: grid_name
integer, intent(in) :: im_world
integer, intent(in) :: jm_world
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: lm
real, intent(in) :: cs_stretch_param(3)
real, intent(in) :: lon_range(2)
real, intent(in) :: lat_range(2)
character(len=*), intent(in) :: tripolar_file
integer, intent(out), optional :: rc
Return Value type(ESMF_Config)
Calls
Called by
Source Code
    function create_cf(grid_name,im_world,jm_world,nx,ny,lm,cs_stretch_param,lon_range,lat_range,tripolar_file,rc) result(cf)
       use MAPL_ConfigMod
       type(ESMF_Config)              :: cf
       character(len=*), intent(in) :: grid_name
       integer, intent(in)          :: im_world,jm_world
       integer, intent(in)          :: nx,ny
       integer, intent(in)          :: lm
       real, intent(in)             :: cs_stretch_param(3)
       real, intent(in)             :: lon_range(2)
       real, intent(in)             :: lat_range(2)
       character(len=*), intent(in) :: tripolar_file
       integer, optional, intent(out) :: rc
       integer :: status
       character(len=2) :: pole,dateline
       integer :: nn
       nn = len_trim(grid_name)
       dateline=grid_name(nn-1:nn)
       pole=grid_name(1:2)
       cf = MAPL_ConfigCreate(_RC)
       call MAPL_ConfigSetAttribute(cf,value=NX, label=trim(grid_name)//".NX:",_RC)
       call MAPL_ConfigSetAttribute(cf,value=lm, label=trim(grid_name)//".LM:",_RC)
       if (dateline=='CF') then
          call MAPL_ConfigSetAttribute(cf,value="Cubed-Sphere", label=trim(grid_name)//".GRID_TYPE:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=6, label=trim(grid_name)//".NF:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=im_world,label=trim(grid_name)//".IM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=ny/6, label=trim(grid_name)//".NY:",_RC)
          if (any(cs_stretch_param/=uninit)) then
             call MAPL_ConfigSetAttribute(cf,value=cs_stretch_param(1),label=trim(grid_name)//".STRETCH_FACTOR:",_RC)
             call MAPL_ConfigSetAttribute(cf,value=cs_stretch_param(2),label=trim(grid_name)//".TARGET_LON:",_RC)
             call MAPL_ConfigSetAttribute(cf,value=cs_stretch_param(3),label=trim(grid_name)//".TARGET_LAT:",_RC)
          end if
       else if (dateline=='TM') then
          call MAPL_ConfigSetAttribute(cf,value="Tripolar", label=trim(grid_name)//".GRID_TYPE:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=im_world,label=trim(grid_name)//".IM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=jm_world,label=trim(grid_name)//".JM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=ny, label=trim(grid_name)//".NY:",_RC)
          _ASSERT(tripolar_file /= "empty","asked for tripolar output but did not specify the coordinate file")
          call MAPL_ConfigSetAttribute(cf,value=tripolar_file,label=trim(grid_name)//".GRIDSPEC:",_RC)
       else
          call MAPL_ConfigSetAttribute(cf,value="LatLon", label=trim(grid_name)//".GRID_TYPE:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=im_world,label=trim(grid_name)//".IM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=jm_world,label=trim(grid_name)//".JM_WORLD:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=ny, label=trim(grid_name)//".NY:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=pole, label=trim(grid_name)//".POLE:",_RC)
          call MAPL_ConfigSetAttribute(cf,value=dateline, label=trim(grid_name)//".DATELINE:",_RC)
          if (pole=='XY' .and. dateline=='XY') then
             _ASSERT(all(lon_range/=uninit),'if regional must specify lon_range')
             _ASSERT(all(lat_range/=uninit),'if regional must specify lat_range')
             call MAPL_ConfigSetAttribute(cf,value=lon_range,label=trim(grid_name)//".LON_RANGE:",_RC)
             call MAPL_ConfigSetAttribute(cf,value=lat_range,label=trim(grid_name)//".LAT_RANGE:",_RC)
          end if
       end if
     end function create_cf
Call graph
create_cf calls mapl_assert, mapl_configsetattribute, mapl_configcreate, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configcreate calls ESMF_ConfigCreate, buffer, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_configsetattribute_int32 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_ints32 calls mapl_assert, mapl_configsetattribute, mapl_verify, mapl_return
mapl_configsetattribute_real32 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_real64 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_reals32 calls mapl_assert, mapl_configsetattribute, mapl_verify, mapl_return
mapl_configsetattribute_string calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
create_grid calls create_cf
process_command_line calls create_grid
main calls process_command_line
regrid_util calls main