create_remote_win – MAPL
create_remote_win Subroutine
61 statements
Source File
private subroutine create_remote_win(this, rc)
Type Bound
BaseServer
Arguments
Type Intent Optional Attributes Name
class(BaseServer), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine create_remote_win(this, rc)
      class (BaseServer), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      class (AbstractDataReference), pointer :: remotePtr
      integer :: rank
      integer(KIND=INT64) :: msize_word
      integer(KIND=INT64),allocatable :: offsets(:), msize_words(:)
      type (MessageVectorIterator) :: iter
      type (StringInteger64MapIterator) :: request_iter
      class (AbstractMessage), pointer :: msg
      integer :: collection_counter, collection_total
      character(len=*),parameter :: Iam = 'create_remote_win'
      class (ServerThread) , pointer :: thread_ptr
      if (associated(ioserver_profiler)) call ioserver_profiler%start("create_shared_mem")
      this%stage_offset = StringInteger64map()
      collection_counter = 0
      collection_total   = 0
      thread_ptr => this%threads%at(1)
      !(1) loop to get the total number of collection
      iter   = thread_ptr%request_backlog%begin()
      do while (iter /= thread_ptr%request_backlog%end())
         msg => iter%get()
         select type (q=>msg)
         type is (CollectiveStageDataMessage)
            request_iter = this%stage_offset%find(i_to_string(q%collection_id))
            if ( request_iter == this%stage_offset%end()) then
               collection_total = collection_total + 1
               call this%stage_offset%insert(i_to_string(q%collection_id),int(collection_total, kind=INT64))
            endif
         end select
         call iter%next()
      end do
      !(2) loop to get the total size and offset of each collection and request
      allocate(offsets(collection_total), msize_words(collection_total))
      offsets = 0
      iter   = thread_ptr%request_backlog%begin()
      do while (iter /= thread_ptr%request_backlog%end())
         msg => iter%get()
         select type (q=>msg)
         type is (CollectiveStageDataMessage)
            collection_counter = this%stage_offset%of(i_to_string(q%collection_id))
            request_iter = this%stage_offset%find(i_to_string(q%request_id))
            if ( request_iter == this%stage_offset%end()) then
               ! insert local offset for each node
               call this%stage_offset%insert(i_to_string(q%request_id),offsets(collection_counter))
               msize_word = word_size(q%type_kind)*product(int(q%global_count,INT64))
               offsets(collection_counter) = offsets(collection_counter) + msize_word
            endif
         end select
         call iter%next()
      end do
      ! (3) allocate the memory
      msize_words = offsets
      do collection_counter = 1, collection_total
         rank = this%get_writing_PE(collection_counter)
         msize_word = msize_words(collection_counter)
         call this%stage_offset%insert(i_to_string(MSIZE_ID + collection_counter ),msize_word)
         allocate(remotePtr, source  = RDMAReference(pFIO_INT32,msize_word, this%comm, rank ))
         call this%add_DataReference(remotePtr)
         remotePtr=>null()
      enddo
      if (associated(ioserver_profiler)) call ioserver_profiler%stop("create_shared_mem")
      _RETURN(_SUCCESS)
   end subroutine create_remote_win
Call graph
create_remote_win calls find, insert, at, start, of, add_datareference, get_writing_pe, i_to_string, mapl_return, v_begin, v_iter_get, v_iter_next, word_size, stringinteger64map
add_datareference calls set_status, v_push_back
get_writing_pe calls mpi_allreduce
i_to_string calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls insert, at
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
v_at_32 calls v_at_size_kind
v_push_back calls resize, v_grow_to