Create_bundle_RH – MAPL
Create_bundle_RH Subroutine
91 statements
Source File
private subroutine Create_bundle_RH(this, items, bundle, timeInfo, vdata, ogrid, global_attributes, rc)
Type Bound
sampler
Arguments
Type Intent Optional Attributes Name
class(sampler), intent(inout) :: this
type(GriddedIOitemVector), intent(inout), target :: items
type(ESMF_FieldBundle), intent(inout) :: bundle
type(timeData), intent(inout), optional :: timeInfo
type(verticalData), intent(inout), optional :: vdata
type(ESMF_Grid), intent(inout), optional, pointer :: ogrid
type(StringStringMap), intent(in), optional, target :: global_attributes
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine Create_bundle_RH(this,items,bundle,timeInfo,vdata,ogrid,global_attributes,rc)
        class (sampler), intent(inout) :: this
        type(GriddedIOitemVector), target, intent(inout) :: items
        type(ESMF_FieldBundle), intent(inout) :: bundle
        type(TimeData), optional, intent(inout) :: timeInfo
        type(VerticalData), intent(inout), optional :: vdata
        type (ESMF_Grid), intent(inout), pointer, optional :: ogrid
        type(StringStringMap), target, intent(in), optional :: global_attributes
        integer, intent(out), optional :: rc
        type(ESMF_Grid) :: input_grid
        class (AbstractGridFactory), pointer :: factory
        type(ESMF_Field) :: new_field
        type(GriddedIOitemVectorIterator) :: iter
        type(GriddedIOitem), pointer :: item
        type(stringVector) :: order
        integer :: metadataVarsSize
        type(StringStringMapIterator) :: s_iter
        character(len=:), pointer :: attr_name, attr_val
        integer :: status
        this%items = items
        this%input_bundle = bundle
        this%output_bundle = ESMF_FieldBundleCreate(rc=status)
        _VERIFY(status)
        if(present(timeInfo)) this%timeInfo = timeInfo
        call ESMF_FieldBundleGet(this%input_bundle,grid=input_grid,rc=status)
        _VERIFY(status)
        if (present(ogrid)) then
           this%output_grid=ogrid
        else
           call ESMF_FieldBundleGet(this%input_bundle,grid=this%output_grid,rc=status)
           _VERIFY(status)
        end if
        this%regrid_handle => new_regridder_manager%make_regridder(input_grid,this%output_grid,this%regrid_method,rc=status)
        _VERIFY(status)
        ! We get the regrid_method here because in the case of Identity, we set it to
        ! REGRID_METHOD_IDENTITY in the regridder constructor if identity. Now we need
        ! to change the regrid_method in the GriddedIO object to be the same as the
        ! the regridder object.
        this%regrid_method = this%regrid_handle%get_regrid_method()
        call ESMF_FieldBundleSet(this%output_bundle,grid=this%output_grid,rc=status)
        _VERIFY(status)
        factory => get_factory(this%output_grid,rc=status)
        _VERIFY(status)
        ! __ please note, metadata in this section is not used in put_var to netCDF
        !    the design used mGriddedIO%metadata in MAPL_HistoryGridComp.F90
        !    In other words, factory%append_metadata appeared here and in GriddedIO.F90
        !
        if (allocated(this%metadata)) then
           deallocate (this%metadata)
        end if
        allocate(this%metadata)
        call factory%append_metadata(this%metadata)
        if (present(vdata)) then
           this%vdata=vdata
        else
           this%vdata=VerticalData(rc=status)
           _VERIFY(status)
        end if
        call this%vdata%append_vertical_metadata(this%metadata,this%input_bundle,rc=status)
        _VERIFY(status)
        this%doVertRegrid = (this%vdata%regrid_type /= VERTICAL_METHOD_NONE)
        if (this%vdata%regrid_type == VERTICAL_METHOD_ETA2LEV) call this%vdata%get_interpolating_variable(this%input_bundle,rc=status)
        _VERIFY(status)
        iter = this%items%begin()
        do while (iter /= this%items%end())
           item => iter%get()
           if (item%itemType == ItemTypeScalar) then
              call this%CreateVariable(item%xname,rc=status)
              _VERIFY(status)
           else if (item%itemType == ItemTypeVector) then
              call this%CreateVariable(item%xname,rc=status)
              _VERIFY(status)
              call this%CreateVariable(item%yname,rc=status)
              _VERIFY(status)
           end if
           call iter%next()
        enddo
        ! __ add acc_bundle and output_bundle
        !
        this%acc_bundle = ESMF_FieldBundleCreate(_RC)
        call ESMF_FieldBundleSet(this%acc_bundle,grid=this%output_grid,_RC)
        iter = this%items%begin()
        do while (iter /= this%items%end())
           item => iter%get()
           call this%addVariable_to_acc_bundle(item%xname,_RC)
           if (item%itemType == ItemTypeVector) then
              call this%addVariable_to_acc_bundle(item%yname,_RC)
           end if
           call iter%next()
        enddo
        ! __ add time to acc_bundle
        !
        new_field = ESMF_FieldCreate(this%output_grid ,name='time', &
               typekind=ESMF_TYPEKIND_R4,_RC)
        call MAPL_FieldBundleAdd( this%acc_bundle, new_field, _RC )
        _RETURN(_SUCCESS)
      end subroutine Create_Bundle_RH
Call graph
create_bundle_rh calls append_metadata, esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_fieldbundleset, esmf_fieldcreate, mapl_fieldbundleadd, make_regridder, addvariable_to_acc_bundle, append_vertical_metadata, createvariable, get_factory, get_interpolating_variable, get_regrid_method, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
addvariable_to_acc_bundle calls esmf_fieldbundleget, mapl_fieldbundleadd, mapl_return, mapl_verify, esmf_fieldget, mapl_fieldcreate
append_vertical_metadata calls esmf_fieldbundleget, mapl_return, mapl_verify, ESMF_AttributeGet, esmf_fieldget, mapl_assert, add_attribute, add_const_value, add_dimension, add_variable
createvariable calls esmf_fieldbundleget, mapl_fieldbundleadd, get_factory, mapl_return, mapl_verify, ESMF_AttributeGet, esmf_fieldget, mapl_fieldcreate
get_factory calls mapl_return, mapl_verify, get_factory
get_interpolating_variable calls esmf_fieldbundleget, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
initialize calls create_bundle_rh
run calls create_bundle_rh