create_from_parameters – MAPL
create_from_parameters Subroutine
50 statements
Source File
private subroutine create_from_parameters(this, update_time, update_freq, update_offset, time, clock, rc)
Type Bound
ExtDataPointerUpdate
Arguments
Type Intent Optional Attributes Name
class(ExtDataPointerUpdate), intent(inout) :: this
character(len=*), intent(in) :: update_time
character(len=*), intent(in) :: update_freq
character(len=*), intent(in) :: update_offset
type(ESMF_Time), intent(inout) :: time
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create_from_parameters(this,update_time,update_freq,update_offset,time,clock,rc)
      class(ExtDataPointerUpdate), intent(inout) :: this
      character(len=*), intent(in) :: update_time
      character(len=*), intent(in) :: update_freq
      character(len=*), intent(in) :: update_offset
      type(ESMF_Time), intent(inout) :: time
      type(ESMF_Clock), intent(inout) :: clock
      integer, optional, intent(out) :: rc
      integer :: status,int_time,year,month,day,hour,minute,second
      logical :: negative_offset
      type(ESMF_TimeInterval) :: timestep
      integer :: multiplier
      integer :: i, j
      logical :: is_heartbeat
      this%last_checked = time
      call ESMF_ClockGet(clock, timestep=timestep, _RC)
      if (update_freq == "-") then
         this%single_shot = .true.
      else if (update_freq /= "PT0S") then
         this%simple_alarm_created = .true.
         int_time = string_to_integer_time(update_time)
         hour=int_time/10000
         minute=mod(int_time/100,100)
         second=mod(int_time,100)
         call ESMF_TimeGet(time,yy=year,mm=month,dd=day,_RC)
         call ESMF_TimeSet(this%reference_time,yy=year,mm=month,dd=day,h=hour,m=minute,s=second,_RC)
         this%last_ring = this%reference_time
         this%update_freq = string_to_esmf_timeinterval(update_freq,_RC)
      end if
      i = index(update_offset,"-") + 1
      j = index(update_offset, '+') + 1
      _ASSERT(i==1 .or. j==1, '"+" and "-" cannot both be present in update_offset string.')
      negative_offset = i > 1
      if(.not. negative_offset) i = j
      call parse_heartbeat_timestring(update_offset(i:), is_heartbeat=is_heartbeat, multiplier=multiplier)
      if(is_heartbeat) then
         this%offset = multiplier * timestep
      else
         this%offset=string_to_esmf_timeinterval(update_offset(i:),_RC)
      end if
      if(negative_offset) this%offset = -this%offset
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(clock)
   end subroutine create_from_parameters
Call graph
create_from_parameters calls ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_return, mapl_verify, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeIntervalSet
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fillin_derived calls create_from_parameters
fillin_primary calls create_from_parameters
test_compare_negative_string_to_negative_heartbeat calls create_from_parameters
test_compare_positive_string_to_positive_heartbeat calls create_from_parameters
test_create_from_parameters_heartbeat_negative calls create_from_parameters
test_create_from_parameters_heartbeat_negative_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive_explicit calls create_from_parameters
test_create_from_parameters_heartbeat_positive_negative calls create_from_parameters
test_create_from_parameters_string_negative calls create_from_parameters
test_create_from_parameters_string_positive calls create_from_parameters
test_get_adjusted_time calls create_from_parameters
initialize_ calls fillin_derived, fillin_primary