create_timeunit – MAPL
create_timeunit Subroutine
16 statements
Source File
public subroutine create_timeunit(time, datetime_units, input_unit, rc)
print*, ‘datetime_units:’, trim(datetime_units)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: time
character(len=*), intent(out) :: datetime_units
character(len=*), intent(in), optional :: input_unit
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine create_timeunit (time, datetime_units, input_unit, rc)
    type(ESMF_Time), intent(in) :: time
    character(len=*), intent(out) :: datetime_units
    character(len=*), optional, intent(in) :: input_unit
    integer, optional, intent(out) :: rc
    integer :: i, len
    integer :: status
    character(len=ESMF_MAXSTR) :: string
    call ESMF_timeget (time, timestring=string, _RC)
    datetime_units = 'seconds'
    if (present(input_unit)) datetime_units = trim(input_unit)
    datetime_units = trim(datetime_units) // trim(string)
    !!print*, 'datetime_units:', trim(datetime_units)
    _RETURN(_SUCCESS)
  end subroutine create_timeunit
Call graph
create_timeunit calls ESMF_TimeGet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize