create_metadata_variable – MAPL
create_metadata_variable Subroutine
53 statements
Source File
private subroutine create_metadata_variable(this, vname, rc)
Type Bound
StationSampler
Arguments
Type Intent Optional Attributes Name
class(StationSampler), intent(inout) :: this
character(len=*), intent(in) :: vname
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine  create_metadata_variable(this,vname,rc)
    class(StationSampler), intent(inout) :: this
    character(len=*), intent(in)         :: vname
    integer, optional, intent(out)       :: rc
    type(ESMF_Field) :: field
    type(variable) :: v
    logical :: is_present
    integer :: field_rank, status
    character(len=ESMF_MAXSTR) :: var_name,long_name,units,vdims
    integer :: rank,lb(1),ub(1)
    integer :: k, ig
    integer, allocatable :: chunksizes(:)
    call ESMF_FieldBundleGet(this%bundle,vname,field=field,_RC)
    call ESMF_FieldGet(field,name=var_name,rank=field_rank,_RC)
    call ESMF_AttributeGet(field,name="LONG_NAME",isPresent=is_present,_RC)
    long_name = var_name
    if ( is_present ) then
       call ESMF_AttributeGet  (FIELD, NAME="LONG_NAME",VALUE=long_name, _RC)
    endif
    call ESMF_AttributeGet(field,name="UNITS",isPresent=is_present,_RC)
    units = 'unknown'
    if ( is_present ) then
       call ESMF_AttributeGet  (FIELD, NAME="UNITS",VALUE=units, _RC)
    endif
    vdims = "station_index,time"
    select case (field_rank)
    case(2)
       chunksizes = [this%nstation,1]
    case(3)
       vdims = "lev,"//trim(vdims)
       call ESMF_FieldGet(field,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
       chunksizes = [ub(1)-lb(1)+1,1,1]
    case default
       _FAIL('unsupported rank')
    end select
    v = variable(type=PFIO_REAL32,dimensions=trim(vdims))
    call v%add_attribute('units',trim(units))
    call v%add_attribute('long_name',trim(long_name))
    call v%add_attribute('missing_value',MAPL_UNDEF)
    call v%add_attribute('_FillValue',MAPL_UNDEF)
    call v%add_attribute('valid_range',(/-MAPL_UNDEF,MAPL_UNDEF/))
    call this%metadata%add_variable(trim(var_name),v,_RC)
    _RETURN(_SUCCESS)
  end subroutine create_metadata_variable
Call graph
create_metadata_variable calls ESMF_AttributeGet, esmf_fieldbundleget, esmf_fieldget, mapl_assert, add_attribute, add_variable, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_variable calls mapl_assert, mapl_return, at, begin, get, next, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_attribute_1d calls mapl_return, insert
get_error_message calls at, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_value calls mapl_return
m_insert_pair calls s_insert
add_metadata_route_handle calls create_metadata_variable
initialize calls add_metadata_route_handle