create_file_handle – MAPL
create_file_handle Module Subroutine
34 statements
Source File
module subroutine create_file_handle(this, filename, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(MaskSamplerGeosat), intent(inout) :: this
character(len=*), intent(in) :: filename
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  module subroutine create_file_handle(this,filename,rc)
    class(MaskSamplerGeosat), intent(inout) :: this
    character(len=*), intent(in)            :: filename
    integer, optional, intent(out)          :: rc
    type(variable) :: v
    integer :: status, j
    real(kind=REAL64), allocatable :: x(:)
    integer :: nx
    this%ofile = trim(filename)
    v = this%time_info%define_time_variable(_RC)
    call this%metadata%modify_variable('time',v,_RC)
    this%obs_written = 0
    if (.not. mapl_am_I_root()) then
       _RETURN(_SUCCESS)
    end if
    call this%formatter%create(trim(filename),_RC)
    call this%formatter%write(this%metadata,_RC)
    nx = size (this%lons)
    allocate ( x(nx), _STAT )
    x(:) = this%lons(:) * MAPL_RADIANS_TO_DEGREES
    call this%formatter%put_var('longitude',x,_RC)
    x(:) = this%lats(:) * MAPL_RADIANS_TO_DEGREES
    call this%formatter%put_var('latitude',x,_RC)
!    call this%formatter%put_var('mask_id',this%mask_id,_RC)
!    call this%formatter%put_var('mask_name',this%mask_name,_RC)
    _RETURN(_SUCCESS)
  end subroutine create_file_handle
Call graph
create_file_handle calls mapl_am_i_root, put_var, create, define_time_variable, mapl_return, mapl_verify, modify_variable, create_file_handle
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
create calls mapl_return, mapl_verify, nf90_create
define_time_variable calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, mapl_assert, add_attribute, v_clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modify_variable calls mapl_return, at, begin, get, mapl_assert, next, get_dimensions, m_set