create – MAPL
create Subroutine
29 statements
Source File
private subroutine create(this, file, unusable, mode, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
character(len=*), intent(in) :: file
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: mode
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create(this, file, unusable, mode, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      character(len=*), intent(in) :: file
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: mode
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: mode_
      integer :: pfio_mode
      if (present(mode)) then
         pfio_mode=mode
      else
         pfio_mode=PFIO_NOCLOBBER
      end if
      select case (pfio_mode)
      case (pFIO_CLOBBER)
         mode_ = NF90_CLOBBER
      case (pFIO_NOCLOBBER)
         mode_ = NF90_NOCLOBBER
      end select
      !$omp critical
      status = nf90_create(file, IOR(mode_, NF90_NETCDF4), this%ncid)
      !$omp end critical
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine create
Call graph
create calls nf90_create, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_file_handle calls create
find_ calls create
init calls create
mapl_bundlewritencpar calls create
mapl_writetilingnc4 calls create
put_datatofile calls create, find_, put_datatofile
setup calls create
test_add_variable calls create
test_write_read_simple_attribute calls create
test_write_read_simple_variable calls create
test_write_read_trivial calls create
test_write_read_variable_attribute calls create
main calls create, init
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
clean_up calls put_datatofile
handle_done_stage calls put_datatofile
mapl_esmfstatewritetofile calls mapl_varwritencpar
start_back calls put_datatofile
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile
start calls start_back, clean_up