create_subobjects – MAPL
create_subobjects Subroutine
27 statements
Source File
private subroutine create_subobjects(this, num_threads, unusable, rc)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout) :: this
integer, intent(in) :: num_threads
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine create_subobjects(this, num_threads, unusable, rc)
     class(MaplGenericComponent), intent(inout) :: this
     integer, intent(in) :: num_threads
     class(KeywordEnforcer), optional, intent(in) :: unusable
     integer, optional, intent(out) :: rc
     integer :: i, status
     type(ESMF_Grid), allocatable :: subgrids(:)
     allocate(this%subcomponents(num_threads))
     this%subcomponents(:)%import_state = make_substates(this%import_state, num_threads, _RC)
     this%subcomponents(:)%export_state = make_substates(this%export_state, num_threads, _RC)
     this%subcomponents(:)%internal_state = make_substates(this%internal_state, num_threads, _RC)
     subgrids = make_subgrids(this%grid%ESMFGrid, num_threads, _RC) ! make_subgrids requires grid of type ESMF_Grid
     do i = 1, size(subgrids)
        call this%subcomponents(i)%grid%set(subgrids(i), _RC)
     end do
     deallocate(subgrids)
     this%subcomponents(:)%gridcomp = make_subgridcomps(this%gridcomp, this%run_entry_points, num_threads, _RC)
     _RETURN(0)
     _UNUSED_DUMMY(unusable)
   end subroutine create_subobjects
Call graph
create_subobjects calls make_subgrids, make_substates, make_subgridcomps, mapl_return, mapl_verify, set
make_subgrids calls make_subgrids_from_bounds, make_subgrids_from_num_grids
make_substates calls make_substates_from_num_grids
make_subgridcomps calls mapl_return, mapl_verify, ESMF_GridCompCreate, ESMF_GridCompGet, ESMF_InternalStateGet, ESMF_UserCompGetInternalState, ESMF_UserCompSetInternalState, ESMF_VMGet, ESMF_VMGetCurrent, esmf_gridcompsetservices
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_GridValidate, ESMF_VMGet, ESMF_VMGetCurrent, wraparray, get_logger, debug, gridcoordget, mapl_distgridget, mapl_getimsjms, mapl_gridget
activate_threading calls create_subobjects
omp_driver calls activate_threading
mapl_genericwrapper calls omp_driver