cross_prod – MAPL
cross_prod Function
7 statements
Source File
private function cross_prod(v1, v2) result(vout)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: v1(3)
real(kind=real64), intent(in) :: v2(3)
Return Value real(kind=real64), (3)
Called by
Contents
Source Code
cross_prod
Source Code
 function cross_prod(v1,v2) result(vout)
    real(real64), intent(in) :: v1(3),v2(3)
    real(real64) :: vout(3)
    vout(1)=v1(2)*v2(3)-v1(3)*v2(2)
    vout(2)=v1(3)*v2(1)-v1(1)*v2(3)
    vout(3)=v1(1)*v2(2)-v1(2)*v2(1)
 end function cross_prod
Call graph
lines_intersect calls cross_prod
point_in_polygon calls lines_intersect
get_points_in_spherical_domain calls point_in_polygon
mapl_gethorzijindex calls get_points_in_spherical_domain