cstring – MAPL
cstring Function
5 statements
Source File
public function cstring(s) result(cs)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
Return Value character(kind=c_char, len=:), allocatable
Called by
Source Code
   function cstring(s) result(cs)
      character(len=*), intent(in) :: s
      character(kind=c_char, len=:), allocatable :: cs
      cs = adjustl(trim(s)) // c_null_char
   end function cstring
Call graph
construct_unit calls cstring
read_xml calls cstring
test_cstring calls cstring
udunit calls construct_unit
construct_system calls read_xml
test_read_xml_nopath calls read_xml
udsystem calls construct_system