CSV_read_line_with_CH_I_R – MAPL
CSV_read_line_with_CH_I_R Subroutine
34 statements
Source File
private subroutine CSV_read_line_with_CH_I_R(line, name, lon, lat, rc)
write(6,*) trim(name), lon, lat
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
character(len=*), intent(out) :: name
real(kind=REAL64), intent(out) :: lon
real(kind=REAL64), intent(out) :: lat
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine CSV_read_line_with_CH_I_R(line, name, lon, lat, rc)
    character (len=*), intent(in) :: line
    character (len=*), intent(out) :: name
    real(kind=REAL64), intent(out) :: lon, lat
    integer, optional, intent(out) :: rc
    integer :: n
    integer :: i, j, k
    integer :: ios
    i=index(line, ',')
    j=index(line(i+1:), ',')
    _ASSERT (i>0, 'not CSV format')
    _ASSERT (j>0, 'CSV format: find only 1 comma, should be > 1')
    j=i+j
    read(line(1:i-1), '(a100)', iostat=ios)  name
    _ASSERT (ios==0, 'read error')
    k=index(line(i+1:j-1), '.')
    if (k > 0) then
       read(line(i+1:j-1), *, iostat=ios) lon
    else
       read(line(i+1:j-1), *, iostat=ios) i
       lon = i
    endif
    _ASSERT (ios==0, 'read error')
    k=index(line(j+1:), '.')
    if (k > 0) then
       read(line(j+1:), *, iostat=ios) lat
    else
       read(line(j+1:), *, iostat=ios) i
       lat = i
    endif
    _ASSERT (ios==0, 'read error')
    !!write(6,*) trim(name), lon, lat
    _RETURN(_SUCCESS)
  end subroutine CSV_read_line_with_CH_I_R
Call graph
csv_read_line_with_ch_i_r calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_stationsampler_readfile calls csv_read_line_with_ch_i_r
stationsampler calls new_stationsampler_readfile