CubedSphereGridFactory_from_parameters – MAPL
CubedSphereGridFactory_from_parameters Function
32 statements
Source File
private function CubedSphereGridFactory_from_parameters(unusable, grid_name, grid_type, im_world, lm, nx, ny, ims, jms, stretch_factor, target_lon, target_lat, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: grid_type
integer, intent(in), optional :: im_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(in), optional :: ims(:)
integer, intent(in), optional :: jms(:)
real(kind=REAL32), intent(in), optional :: stretch_factor
real(kind=REAL32), intent(in), optional :: target_lon
real(kind=REAL32), intent(in), optional :: target_lat
integer, intent(out), optional :: rc
Return Value type(CubedSphereGridFactory)
Calls
Called by
Source Code
   function CubedSphereGridFactory_from_parameters(unusable, grid_name, grid_type, &
        & im_world, lm, nx, ny, ims, jms, stretch_factor, target_lon, target_lat, &
        & rc) result(factory)
      type (CubedSphereGridFactory) :: factory
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: grid_name
      integer, optional, intent(in) :: grid_type
      ! grid details:
      integer, optional, intent(in) :: im_world
      integer, optional, intent(in) :: lm
      ! decomposition:
      integer, optional, intent(in) :: nx
      integer, optional, intent(in) :: ny
      integer, optional, intent(in) :: ims(:)
      integer, optional, intent(in) :: jms(:)
      ! stretched grid
      real(REAL32), optional, intent(in) :: stretch_factor, target_lon, target_lat
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'CubedSphereGridFactory_from_parameters'
      if (present(unusable)) print*,shape(unusable)
      call set_with_default(factory%grid_name, grid_name, MAPL_GRID_NAME_DEFAULT)
      call set_with_default(factory%grid_type, grid_type, FV_GRID_TYPE_DEFAULT)
      call set_with_default(factory%nx, nx, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%ny, ny, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%im_world, im_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%lm, lm, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%stretch_factor,stretch_factor,MAPL_UNDEFINED_REAL)
      call set_with_default(factory%target_lon,target_lon,MAPL_UNDEFINED_REAL)
      call set_with_default(factory%target_lat,target_lat,MAPL_UNDEFINED_REAL)
      ! default is unallocated
      if (present(ims)) factory%ims = ims
      if (present(jms)) factory%jms = jms
      call factory%check_and_fill_consistency(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function CubedSphereGridFactory_from_parameters
Call graph
cubedspheregridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_bounds, set_with_default_character, set_with_default_integer, set_with_default_real64, set_with_default_real
check_and_fill_consistency calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
cubedspheregridfactory calls cubedspheregridfactory_from_parameters