current – MAPL
current Function
5 statements
Source File
private function current(this) result(clientPtr)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(in), target :: this
Return Value class(ClientThread), pointer
Called by
Contents
Source Code
current
Source Code
   function current(this) result(clientPtr)
      class (ClientManager), target, intent(in) :: this
      class (ClientThread), pointer :: clientPtr
      clientPtr => this%clients%at(this%current_client)
   end function current
Call graph
collective_prefetch_data calls current, collective_prefetch_data
collective_stage_data calls current, collective_stage_data
done_collective_prefetch calls current, done_collective_prefetch
done_collective_stage calls current, done_collective_stage
done_prefetch calls current, done_prefetch
done_stage calls current, done_stage
modify_metadata calls current, modify_metadata
post_wait calls current
prefetch_data calls current, prefetch_data
replace_metadata calls current, replace_metadata
shake_hand calls current, shake_hand
stage_data calls current, stage_data
stage_nondistributed_data calls current, collective_stage_data
wait calls current
modify_metadata_all calls modify_metadata
replace_metadata_all calls replace_metadata