deactivate_threading – MAPL
deactivate_threading Subroutine
21 statements
Source File
private recursive subroutine deactivate_threading(this, unusable, rc)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout) :: this
class(KeywordEnforcer), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine deactivate_threading(this, unusable, rc)
     class(MaplGenericComponent), intent(inout) :: this
     class(KeywordEnforcer), optional :: unusable
     integer, optional, intent(out) :: rc
     class(AbstractFrameworkComponent), pointer :: child
     integer :: num_children, i
     num_children = this%get_num_children()
     do i = 1, num_children
        child => this%get_child(i)
        select type (child)
        class is (MaplGenericComponent)
           call child%deactivate_threading()
        class default
           _FAIL('illegal type for child')
        end select
     end do
     this%threading_active = .FALSE.
     _RETURN(0)
     _UNUSED_DUMMY(unusable)
   end subroutine deactivate_threading
Call graph
deactivate_threading calls deactivate_threading, mapl_assert, get_child, get_num_children, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_num_children calls get_num_children
mapl_return calls get_error_message, mapl_throw_exception
get_child_by_index calls get_component, get_child
get_child_by_name calls get_component, get_child
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
omp_driver calls deactivate_threading
mapl_genericwrapper calls omp_driver