dealloc_ – MAPL
dealloc_ Subroutine
43 statements
Source File
public subroutine dealloc_(A, rc)
Arguments
Type Intent Optional Attributes Name
type(PTR), intent(inout) :: A
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine dealloc_(A,RC)
    type (Ptr), intent(INOUT)        :: A
    integer, optional, intent(out)   :: rc
    if(a%allocated/=not_allocated) then
       select case (a%allocated)
       case (R4_2)
          if(associated(A%r4_2)) then
             deallocate(A%r4_2)
             nullify(A%r4_2)
          end if
       case (R4_1)
          if(associated(A%r4_1)) then
             deallocate(A%r4_1)
             nullify(A%r4_1)
          end if
       case (R8_2)
          if(associated(A%r8_2)) then
             deallocate(A%r8_2)
             nullify(A%r8_2)
          end if
       case (R8_1)
          if(associated(A%r8_1)) then
             deallocate(A%r8_1)
             nullify(A%r8_1)
          end if
       case (i4_1)
          if(associated(A%i4_1)) then
             deallocate(A%i4_1)
             nullify(A%i4_1)
          end if
       case (i4_2)
          if(associated(A%i4_2)) then
             deallocate(A%i4_2)
             nullify(A%i4_2)
          end if
       case default
          _FAIL( 'unsupported tkr')
       end select
       a%allocated=not_allocated
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine dealloc_
Call graph
dealloc_ calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
alloc_ calls dealloc_
mapl_destroyfile calls dealloc_
write_parallel_i4_0 calls dealloc_
write_parallel_r4_0 calls dealloc_
write_parallel_r8_0 calls dealloc_
write_parallel calls write_parallel_i4_0, write_parallel_r4_0, write_parallel_r8_0
mapl_destroystatesave calls mapl_destroyfile
mapl_staterefresh calls mapl_destroyfile
mapl_varwrite_i4_1d calls alloc_
mapl_varwrite_r4_1d calls alloc_
mapl_varwrite_r4_2d calls alloc_
mapl_varwrite_r8_1d calls alloc_
mapl_varwrite_r8_2d calls alloc_
write_parallel_i4_1 calls alloc_
write_parallel_r4_1 calls alloc_
write_parallel_r8_1 calls alloc_