deallocate – MAPL
deallocate Subroutine
15 statements
Source File
private subroutine deallocate(this, rc)
Type Bound
ShmemReference
Arguments
Type Intent Optional Attributes Name
class(ShmemReference), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine deallocate(this, rc)
      class (ShmemReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: ierr
      if (.not. this%shmem_allocated)  then
         _RETURN(_SUCCESS)
      endif
      call MPI_Win_fence(0, this%win, ierr)
      call MPI_Win_free(this%win,ierr)
      call MPI_Comm_free(this%InNode_Comm, ierr)
      this%shmem_allocated = .false.
      _RETURN(_SUCCESS)
   end subroutine deallocate
Call graph
deallocate calls mpi_comm_free, mpi_win_fence, mpi_win_free, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize