deallocate – MAPL
deallocate Subroutine
18 statements
Source File
private subroutine deallocate(this, rc)
Type Bound
RDMAReference
Arguments
Type Intent Optional Attributes Name
class(RDMAReference), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine deallocate(this, rc)
      class (RDMAReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      if ( .not. this%RDMA_allocated ) then
         _RETURN(_SUCCESS)
      endif
      call MPI_Win_fence(0, this%win, status)
      _VERIFY(status)
      call MPI_Win_free(this%win,status)
      _VERIFY(status)
      call MPi_comm_free(this%comm, status)
      _VERIFY(status)
      this%RDMA_allocated = .false.
      _RETURN(_SUCCESS)
   end subroutine deallocate
Call graph
deallocate calls mpi_comm_free, mpi_win_fence, mpi_win_free, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize