debug – MAPL
debug Subroutine
35 statements
Source File
private subroutine debug(this, message, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, unusable, extra, line, file, rc)
Type Bound
Logger
Arguments
Type Intent Optional Attributes Name
class(Logger), intent(inout), target :: this
character(len=*), intent(in) :: message
class(*), intent(in), optional :: arg1
class(*), intent(in), optional :: arg2
class(*), intent(in), optional :: arg3
class(*), intent(in), optional :: arg4
class(*), intent(in), optional :: arg5
class(*), intent(in), optional :: arg6
class(*), intent(in), optional :: arg7
class(*), intent(in), optional :: arg8
class(*), intent(in), optional :: arg9
class(KeywordEnforcer), intent(in), optional :: unusable
type(StringUnlimitedMap), intent(in), optional, target :: extra
integer, intent(in), optional :: line
character(len=*), intent(in), optional :: file
integer, intent(out), optional :: rc
Called by
Source Code
   subroutine debug(this, message, ARG_LIST, unusable, extra, line, file, rc)
      class (Logger), target, intent(inout) :: this
      character(len=*), intent(in) :: message
      include 'recordOptArgs.inc'
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type (StringUnlimitedMap), optional, target, intent(in) :: extra
      integer, optional, intent(in) :: line
      character(*), optional, intent(in) :: file
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(message)
      _UNUSED_DUMMY(arg1)
      _UNUSED_DUMMY(arg2)
      _UNUSED_DUMMY(arg3)
      _UNUSED_DUMMY(arg4)
      _UNUSED_DUMMY(arg5)
      _UNUSED_DUMMY(arg6)
      _UNUSED_DUMMY(arg7)
      _UNUSED_DUMMY(arg8)
      _UNUSED_DUMMY(arg9)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(extra)
      _UNUSED_DUMMY(line)
      _UNUSED_DUMMY(file)
      _RETURN(_SUCCESS)
   end subroutine debug
Call graph
addchild_preamble calls debug
addchildfrommeta calls debug
append_file calls debug
create_file_handle calls debug
create_grid calls debug
createtimeinterval calls debug
getbrackettimeonfile calls debug
getbrackettimeonsinglefile calls debug
gettimesonfile calls debug
historytrajectory_from_config calls debug
initialize_ calls debug
initialize_from_config_with_prefix calls debug
makemetadata calls debug
mapl_extdatainterpfield calls debug
mapl_genericwrapper calls debug
mapl_sungetsolarconstantfromnrlfile calls debug
new_stationsampler_readfile calls debug
perpetual_clock calls debug
read_m_files_4_swath calls debug
regen_rcx_for_obs_platform calls debug
run_ calls debug
run calls debug
set calls debug
updatebrackettime calls debug
verify_epoch_equals_freq calls debug