decode – MAPL
decode Function
7 statements
Source File
private function decode(this, buffer) result(message)
Type Bound
ProtocolParser
Arguments
Type Intent Optional Attributes Name
class(ProtocolParser), intent(in) :: this
integer, intent(in) :: buffer(:)
Return Value class(AbstractMessage), allocatable
Calls
Called by
Source Code
   function decode(this, buffer) result(message)
      class (ProtocolParser), intent(in) :: this
      class (AbstractMessage), allocatable :: message
      integer, intent(in) :: buffer(:)
      allocate(message, source=this%prototypes%at(buffer(1)))
      call message%deserialize(buffer(2:))
   end function decode
Call graph
decode calls deserialize, m_at
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
deserialize_message_vector calls decode
receive calls decode
test_parse_terminate calls decode
create_remote_win calls deserialize_message_vector
deserialize calls deserialize_message_vector
test_back_and_forth calls receive
test_send_terminate calls receive
main calls deserialize_message_vector
start_back calls deserialize
start calls create_remote_win, start_back