def_variables – MAPL
def_variables Subroutine
86 statements
Source File
private subroutine def_variables(this, cf, unusable, varname, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
type(FileMetadata), intent(in), target :: cf
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: varname
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine def_variables(this, cf, unusable, varname, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      type (FileMetadata), target, intent(in) :: cf
      class (KeywordEnforcer), optional, intent(in) :: unusable
      !integer, optional, intent(in) :: chunksizes(:)
      character(*), optional,intent(in) :: varname
      integer, optional, intent(out) :: rc
      integer :: status
      type (StringVariableMap), pointer :: vars
      type (StringVector) :: order
      type (StringVectorIterator) :: var_iter
      type (StringVectorIterator) :: dim_iter
      integer :: xtype
      type (StringVector), pointer :: var_dims
      integer :: idim
      integer, allocatable :: dimids(:)
      integer, pointer :: chunksizes(:)
      integer :: deflation
      integer :: quantize_algorithm
      integer :: quantize_level
      integer :: zstandard_level
      character(len=:), pointer :: var_name
      character(len=:), pointer :: dim_name
      class (Variable), pointer :: var
      integer :: varid
      vars => cf%get_variables()
      order = cf%get_order()
      var_iter = order%begin()
      do while (var_iter /= order%end())
         var_name => var_iter%get()
         if ( present (varname)) then
           if (var_name /= varname) then
             call var_iter%next()
             cycle
           endif
         endif
         var => vars%at(var_name)
         xtype = get_xtype(var%get_type(),rc=status)
         _VERIFY(status)
         var_dims => var%get_dimensions()
         allocate(dimids(var_dims%size()))
         dim_iter = var_dims%begin()
         idim = 1
         do while (dim_iter /= var_dims%end())
            dim_name => dim_iter%get()
            !$omp critical
            status = nf90_inq_dimid(this%ncid, dim_name, dimids(idim))
            !$omp end critical
            call dim_iter%next()
            idim = idim + 1
         end do
         _VERIFY(status)
         !$omp critical
         status = nf90_def_var(this%ncid, var_name, xtype, dimids, varid)
         !$omp end critical
         _VERIFY(status)
         ! There is no nf90 interface for string. skip the fill
         if (xtype /=12) then
           !$omp critical
           status = nf90_def_var_fill(this%ncid, varid, NF90_NOFILL, 0)
           !$omp end critical
         endif
         _VERIFY(status)
         chunksizes => var%get_chunksizes()
         if (size(chunksizes) > 0) then
            !$omp critical
           status = nf90_def_var_chunking(this%ncid, varid, NF90_CHUNKED, chunksizes=chunksizes)
           !$omp end critical
           _VERIFY(status)
         end if
         deflation = var%get_deflation()
         if (deflation > 0) then
            !$omp critical
           status = nf90_def_var_deflate(this%ncid, varid, 1, 1, deflation)
           !$omp end critical
           _VERIFY(status)
         end if
         quantize_algorithm = var%get_quantize_algorithm()
         quantize_level = var%get_quantize_level()
         if (quantize_level /= 0) then
#ifdef NF_HAS_QUANTIZE
           !$omp critical
           status = nf90_def_var_quantize(this%ncid, varid, quantize_algorithm, quantize_level)
           !$omp end critical
           _VERIFY(status)
#else
           _FAIL("netcdf was not built with quantize support")
#endif
         end if
         zstandard_level = var%get_zstandard_level()
         if (zstandard_level /= 0) then
#ifdef NF_HAS_ZSTD
           !$omp critical
           status = nf90_def_var_zstandard(this%ncid, varid, zstandard_level)
           !$omp end critical
           _VERIFY(status)
#else
           _FAIL("netcdf was not built with zstandard support")
#endif
         end if
         call this%put_var_attributes(var, varid, rc=status)
         _VERIFY(status)
         deallocate(dimids)
         call var_iter%next()
      end do
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine def_variables
Call graph
def_variables calls begin, get, mapl_assert, next, nf90_def_var, nf90_def_var_chunking, nf90_def_var_deflate, nf90_def_var_fill, nf90_inq_dimid, get_chunksizes, get_deflation, get_dimensions, get_order, get_quantize_algorithm, get_quantize_level, get_type, get_variables, get_xtype, get_zstandard_level, m_at, mapl_return, mapl_verify, put_var_attributes
add_variable calls def_variables
write calls def_variables