define_time_variable – MAPL
define_time_variable Function
71 statements
Source File
private function define_time_variable(this, rc) result(v)
Type Bound
timeData
Arguments
Type Intent Optional Attributes Name
class(timeData), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value type(Variable)
Calls
Called by
Source Code
  function define_time_variable(this,rc) result(v)
    class(TimeData), intent(inout) :: this
    integer, optional, intent(out) :: rc
    type(Variable) :: v
    integer :: status
    character(len=ESMF_MAXSTR) :: startTime,timeUnits
    type(ESMF_Time) :: currTime
    integer :: i1,i2,i3,ipos1,ipos2,isc,imn,ihr
    integer :: begin_date, begin_time, time_increment, packed_hms
    _ASSERT(this%frequency/=TimeData_uninit_int,"Frequency component was not set before use.")
    call ESMF_ClockGet(this%clock,currTime=currTime,rc=status)
    _VERIFY(status)
    currTime = currTime - this%offset
    call ESMF_TimeGet(currTime,timeString=StartTime,rc=status)
    _VERIFY(status)
    timeUnits = trim(this%funits)//" since "//startTime( 1: 10)//" "//startTime(12:19)
    ipos1=index(startTime,"-")
    ipos2=index(startTime,"-",back=.true.)
    read(startTime(1:ipos1-1),'(i4)')i1
    read(startTime(ipos1+1:ipos2-1),'(i2)')i2
    read(startTime(ipos2+1:10),'(i2)')i3
    begin_date=10000*i1+100*i2+i3
    ipos1=index(startTime,":")
    ipos2=index(startTime,":",back=.true.)
    read(startTime(12:ipos1-1),'(i2)')i1
    read(startTime(ipos1+1:ipos2-1),'(i2)')i2
    read(startTime(ipos2+1:19),'(i2)')i3
    begin_time=10000*i1+100*i2+i3
    isc=mod(this%frequency,60)
    i2=this%frequency-isc
    i2=i2/60
    imn=mod(i2,60)
    i2=i2-imn
    ihr=i2/60
    packed_hms=10000*ihr+100*imn+isc
    select case(trim(this%funits))
    case('seconds')
       time_increment = packed_hms
    case('minutes')
       if (this%integer_time) then
          _ASSERT(mod(this%frequency,60)==0,"Requested output frequency not representable as an integer minute")
       end if
       time_increment = packed_hms
    case('hours')
       if (this%integer_time) then
          _ASSERT(mod(this%frequency,3600)==0,"Requested output frequency not representable as an integer hour")
       end if
       time_increment = packed_hms
    case('days')
       if (this%integer_time) then
          _ASSERT(mod(this%frequency,86400)==0,"Requested output frequency not representable as an integer day")
       end if
       time_increment = this%frequency/86400
    case default
       _FAIL( 'Not supported yet')
    end select
    call this%tvec%clear()
    this%tcount=0
    if (this%integer_time) then
       v = Variable(type=PFIO_INT32,dimensions='time')
    else
       v = Variable(type=PFIO_REAL32,dimensions='time')
    end if
    call v%add_attribute('long_name','time')
    call v%add_attribute('units',trim(timeUnits))
    call v%add_attribute('begin_date',begin_date)
    call v%add_attribute('begin_time',begin_time)
    call v%add_attribute('time_increment',time_increment)
    _RETURN(ESMF_SUCCESS)
  end function define_time_variable
Call graph
define_time_variable calls ESMF_ClockGet, ESMF_TimeGet, mapl_assert, add_attribute, mapl_return, mapl_verify, v_clear
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_clear calls v_downsize
add_attribute_1d calls mapl_return, insert
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
add_time_to_metadata calls define_time_variable
create_file_handle calls define_time_variable, create_file_handle
modifytime calls define_time_variable
add_metadata calls add_time_to_metadata, add_metadata
add_metadata_route_handle calls add_time_to_metadata
createfilemetadata calls add_time_to_metadata
run calls modifytime, createfilemetadata
start_new_file calls modifytime
create_from_bundle calls createfilemetadata
initialize calls add_metadata_route_handle, createfilemetadata
main calls start_new_file, create_from_bundle
time_ave calls start_new_file, create_from_bundle
initialize_ calls add_metadata
write_bundle_single_time calls create_from_bundle
regrid_util calls main
ut_regridding calls create_from_bundle