define_collection_attributes – MAPL
define_collection_attributes Function
16 statements
Source File
private function define_collection_attributes(this, rc) result(global_attributes)
Type Bound
HistoryCollectionGlobalAttributes
Arguments
Type Intent Optional Attributes Name
class(HistoryCollectionGlobalAttributes), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value type(StringStringMap)
Calls
Called by
Source Code
     function define_collection_attributes(this,rc) result(global_attributes)
        class(HistoryCollectionGlobalAttributes), intent(inout) :: this
        integer, optional, intent(out) :: rc
        type(StringStringMap) :: global_attributes
        call global_attributes%insert("Title",trim(this%descr))
        call global_attributes%insert("History","File written by MAPL_PFIO")
        call global_attributes%insert("Source",trim(this%source))
        call global_attributes%insert("Contact",trim(this%contact))
        call global_attributes%insert("Conventions",trim(this%conventions))
        call global_attributes%insert("Institution",trim(this%institution))
        call global_attributes%insert("References",trim(this%references))
        call global_attributes%insert("Filename",trim(this%filename))
        call global_attributes%insert("Comment",trim(this%comment))
        _RETURN(_SUCCESS)
     end function define_collection_attributes
Call graph
define_collection_attributes calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls insert, at
mapl_throw_exception calls initialize
initialize calls define_collection_attributes
run calls define_collection_attributes