deg2rad – MAPL
deg2rad Function
5 statements
Source File
private function deg2rad(angle)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: angle
Return Value real(kind=dp)
Called by
Contents
Source Code
deg2rad
Source Code
REAL(dp) FUNCTION deg2rad(angle)
       IMPLICIT NONE
       REAL(dp), INTENT(IN) :: angle
       deg2rad = MAPL_DEGREES_TO_RADIANS_R8 * angle
END FUNCTION deg2rad
Call graph
get_distance calls deg2rad
get_azimuth calls deg2rad
get_reckon calls deg2rad
find_delta_t calls get_distance
find_sweeppoints calls get_azimuth, get_reckon
orbits_swath calls find_sweeppoints
domasking_ calls orbits_swath
domasking_cs calls orbits_swath