delete – MAPL
delete Subroutine
19 statements
Source File
private subroutine delete(this, grid, unusable, rc)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(in) :: this
type(ESMF_Grid), intent(inout) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine delete(this, grid, unusable, rc)
      use ESMF
      class (GridManager), intent(in) :: this
      type (ESMF_Grid), intent(inout) :: grid
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'destroy_grid'
      if (.not. this%keep_grids) then
         call ESMF_GridDestroy(grid, noGarbage=.true., rc=status)
         _ASSERT(status==0,'failed to destroy grid')
      end if
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine delete
Call graph
delete calls ESMF_GridDestroy, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_grid_type calls delete
test_make_grid_multi calls delete
test_make_grid_no_prototype calls delete
test_make_grid_prototype calls delete