deserialize_base – MAPL
deserialize_base Subroutine
15 statements
Source File
private subroutine deserialize_base(this, buffer, rc)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine deserialize_base(this, buffer, rc)
      class (AbstractDataReference), intent(inout) :: this
      integer, intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: n_base, n_rank
      n_base = size(transfer(this%base_address,[1]))
      _ASSERT( size(buffer) >= n_base+2, "buffer size is too small")
      this%base_address = transfer(buffer(1:n_base), this%base_address)
      this%type_kind = buffer(n_base+1)
      n_rank = buffer(n_base+2)
      allocate(this%shape(n_rank))
      this%shape = buffer(n_base+3:n_base+3+n_rank-1)
      _RETURN(_SUCCESS)
   end subroutine deserialize_base
Call graph
deserialize_base calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
deserialize calls deserialize_base
test_serialize calls deserialize