deserialize_message_vector – MAPL
deserialize_message_vector Subroutine
21 statements
Source File
public subroutine deserialize_message_vector(buffer, msgVec, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(MessageVector), intent(inout) :: msgVec
integer, intent(out), optional :: rc
Calls
Called by
Call graph
deserialize_message_vector calls get_length, mapl_assert, decode, mapl_return, v_push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
decode calls deserialize, m_at
mapl_return calls get_error_message, mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
m_find calls s_find
v_resize_32 calls resize
create_remote_win calls deserialize_message_vector
deserialize calls deserialize_message_vector
main calls deserialize_message_vector
start_back calls deserialize
start calls create_remote_win, start_back