deserialize – MAPL
deserialize Subroutine
9 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
HandShakeMessage
Arguments
Type Intent Optional Attributes Name
class(HandShakeMessage), intent(inout) :: this
integer(kind=INT32), intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
deserialize
Source Code
   subroutine deserialize(this, buffer, rc)
      class (HandShakeMessage), intent(inout) :: this
      integer(kind=INT32), intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(buffer)
   end subroutine deserialize
Call graph
deserialize calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize