deserialize – MAPL
deserialize Subroutine
19 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
RDMAReference
Arguments
Type Intent Optional Attributes Name
class(RDMAReference), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine deserialize(this, buffer, rc)
      class (RDMAReference), intent(inout) :: this
      integer, intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer(kind=INT64) :: long_dummy
      integer :: size_msize,n, n1, status
      size_msize  = size(transfer(long_dummy,[1]))
      n = size(buffer)
      n1 = n - size_msize + 1
      this%msize_word   = transfer(buffer(n1:n), this%msize_word)
      call  deserialize_intrinsic(buffer(n1-1:n1-1), this%RDMA_allocated)
      call  deserialize_intrinsic(buffer(n1-2:n1-2), this%mem_rank)
      call  deserialize_intrinsic(buffer(n1-3:n1-3), this%comm)
      call  deserialize_intrinsic(buffer(n1-4:n1-4), this%win)
      call  this%deserialize_base(buffer(1:n1-5), rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine deserialize
Call graph
deserialize calls deserialize_intrinsic, deserialize_base, mapl_return, mapl_verify
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
deserialize_base calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
deserialize_int32_0d calls mapl_return, mapl_assert
deserialize_int32_1d calls mapl_return, mapl_assert
deserialize_int64_0d calls mapl_return, mapl_assert
deserialize_int64_1d calls mapl_return, mapl_assert
deserialize_logical_0d calls mapl_return, mapl_assert
deserialize_logical_1d calls mapl_return, mapl_assert
deserialize_real32_0d calls mapl_return, mapl_assert
deserialize_real32_1d calls mapl_return, mapl_assert
deserialize_real64_0d calls mapl_return, mapl_assert
deserialize_real64_1d calls mapl_return, mapl_assert
deserialize_string calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception