deserialize – MAPL
deserialize Subroutine
10 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
LocalMemReference
Arguments
Type Intent Optional Attributes Name
class(LocalMemReference), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine deserialize(this, buffer, rc)
      class (LocalMemReference), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer, intent(in) :: buffer(:)
      integer :: status
      call this%deserialize_base(buffer, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine deserialize
Call graph
deserialize calls deserialize_base, mapl_return, mapl_verify
deserialize_base calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
test_serialize calls deserialize