deserialize_int64_1d – MAPL
deserialize_int64_1d Subroutine
12 statements
Source File
private subroutine deserialize_int64_1d(buffer, array, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
integer(kind=INT64), intent(out), allocatable :: array(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
deserialize_int64_1d
Source Code
   subroutine deserialize_int64_1d(buffer, array, rc)
      integer(kind=INT32), intent(in) :: buffer(:)
      integer(kind=INT64), allocatable, intent(out) :: array(:)
      integer, optional, intent(out) :: rc
      integer(kind=INT32) :: n
      _ASSERT(size(buffer) >= 1, "wrong buffer")
      n = buffer(1)
      allocate(array(n-1))
      array = transfer(buffer(2:n),array)
      _RETURN(_SUCCESS)
   end subroutine deserialize_int64_1d
Call graph
deserialize_int64_1d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
deserialize_intrinsic calls deserialize_int64_1d
stringattributemap_deserialize calls deserialize_intrinsic
stringvector_deserialize calls deserialize_intrinsic
deserialize calls deserialize_intrinsic, stringvariablemap_deserialize
stringvariablemap_deserialize calls deserialize_intrinsic
stringintegermap_deserialize calls deserialize_intrinsic
historycollectionvector_deserialize calls deserialize_intrinsic
stringunlimitedentitymap_deserialize calls deserialize_intrinsic
main calls stringattributemap_deserialize
create_remote_win calls historycollectionvector_deserialize