deserialize – MAPL
deserialize Subroutine
14 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
ForwardDataAndMessage
Arguments
Type Intent Optional Attributes Name
class(ForwardDataAndMessage), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine deserialize(this, buffer, rc)
      class (ForwardDataAndMessage), intent(inout) :: this
      integer, intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: n
      !integer :: k
      call deserialize_message_vector(buffer,this%msg_vec)
      n = 1 + buffer(1)
      !k = 0
      if (size(buffer) > n) then
         allocate(this%idata(buffer(n)-1))
         this%idata(:) = buffer(n+1:)
         !k = buffer(n)
      endif
      !_ASSERT(size(buffer) == buffer(1)+ k,"buffer size does not match")
      _RETURN(_SUCCESS)
   end subroutine deserialize
Call graph
deserialize calls deserialize_message_vector, mapl_return
deserialize_message_vector calls mapl_return, get_length, mapl_assert, decode, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
decode calls deserialize, m_at
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_push_back calls resize, v_grow_to
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_grow_to calls v_capacity, v_set_capacity
start_back calls deserialize
start calls start_back