deserialize_string – MAPL
deserialize_string Subroutine
13 statements
Source File
private subroutine deserialize_string(buffer, str, rc)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: buffer(:)
character(len=:), allocatable :: str
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
deserialize_string
Source Code
   subroutine deserialize_string(buffer, str, rc)
      integer(kind=INT32), intent(in) :: buffer(:)
      character(len=:), allocatable :: str
      integer, optional, intent(out) :: rc
      integer(kind=INT32) :: buf_size, str_len
      _ASSERT(size(buffer) >= 2, "wrong buffer")
      buf_size = buffer(1)
      str_len = buffer(2)
      allocate(character(str_len) :: str)
      str = transfer(buffer(3:buf_size), str)
      _RETURN(_SUCCESS)
   end subroutine deserialize_string
Call graph
deserialize_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
deserialize_intrinsic calls deserialize_string
deserialize calls deserialize_intrinsic, stringvariablemap_deserialize
historycollectionvector_deserialize calls deserialize_intrinsic
stringattributemap_deserialize calls deserialize_intrinsic
stringintegermap_deserialize calls deserialize_intrinsic
stringunlimitedentitymap_deserialize calls deserialize_intrinsic
stringvariablemap_deserialize calls deserialize_intrinsic
stringvector_deserialize calls deserialize_intrinsic
create_remote_win calls historycollectionvector_deserialize
main calls stringattributemap_deserialize