deserialize – MAPL
deserialize Subroutine
8 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
AddExtCollectionMessage
Arguments
Type Intent Optional Attributes Name
class(AddExtCollectionMessage), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine deserialize(this, buffer, rc)
      class (AddExtCollectionMessage), intent(inout) :: this
      integer, intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      call deserialize_intrinsic(buffer, this%template)
      _RETURN(_SUCCESS)
   end subroutine deserialize
Call graph
deserialize calls deserialize_intrinsic, mapl_return
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
mapl_return calls get_error_message, mapl_throw_exception
deserialize_int32_0d calls mapl_return, mapl_assert
deserialize_int32_1d calls mapl_return, mapl_assert
deserialize_int64_0d calls mapl_return, mapl_assert
deserialize_int64_1d calls mapl_return, mapl_assert
deserialize_logical_0d calls mapl_return, mapl_assert
deserialize_logical_1d calls mapl_return, mapl_assert
deserialize_real32_0d calls mapl_return, mapl_assert
deserialize_real32_1d calls mapl_return, mapl_assert
deserialize_real64_0d calls mapl_return, mapl_assert
deserialize_real64_1d calls mapl_return, mapl_assert
deserialize_string calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code