deserialize – MAPL
deserialize Subroutine
26 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
AbstractCollectiveDataMessage
Arguments
Type Intent Optional Attributes Name
class(AbstractCollectiveDataMessage), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
deserialize
Source Code
   subroutine deserialize(this, buffer, rc)
      class (AbstractCollectiveDataMessage), intent(inout) :: this
      integer, intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: n
      n = 1
      call deserialize_intrinsic(buffer(n:), this%request_id)
      n = n + serialize_buffer_length(this%request_id)
      call deserialize_intrinsic(buffer(n:), this%collection_id)
      n = n + serialize_buffer_length(this%collection_id)
      call deserialize_intrinsic(buffer(n:), this%file_name)
      n = n + serialize_buffer_length(this%file_name)
      call deserialize_intrinsic(buffer(n:),this%var_name)
      n = n + serialize_buffer_length(this%var_name)
      call deserialize_intrinsic(buffer(n:), this%type_kind)
      n = n + serialize_buffer_length(this%type_kind)
      call deserialize_intrinsic(buffer(n:), this%start)
      n = n + serialize_buffer_length(this%start)
      call deserialize_intrinsic(buffer(n:), this%count)
      n = n + serialize_buffer_length(this%count)
      call deserialize_intrinsic(buffer(n:), this%global_start)
      n = n + serialize_buffer_length(this%global_start)
      call deserialize_intrinsic(buffer(n:), this%global_count)
      _RETURN(_SUCCESS)
   end subroutine deserialize
Call graph
deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
mapl_return calls get_error_message, mapl_throw_exception
deserialize_int32_0d calls mapl_return, mapl_assert
deserialize_int32_1d calls mapl_return, mapl_assert
deserialize_int64_0d calls mapl_return, mapl_assert
deserialize_int64_1d calls mapl_return, mapl_assert
deserialize_logical_0d calls mapl_return, mapl_assert
deserialize_logical_1d calls mapl_return, mapl_assert
deserialize_real32_0d calls mapl_return, mapl_assert
deserialize_real32_1d calls mapl_return, mapl_assert
deserialize_real64_0d calls mapl_return, mapl_assert
deserialize_real64_1d calls mapl_return, mapl_assert
deserialize_string calls mapl_return, mapl_assert
get_error_message calls at
mapl_throw_exception calls initialize
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return