deserialize – MAPL
deserialize Subroutine
14 statements
Source File
private subroutine deserialize(this, buffer, rc)
Type Bound
AddHistCollectionMessage
Arguments
Type Intent Optional Attributes Name
class(AddHistCollectionMessage), intent(inout) :: this
integer, intent(in) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
deserialize
Source Code
   subroutine deserialize(this, buffer,rc)
      class (AddHistCollectionMessage), intent(inout) :: this
      integer, intent(in) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: n, length, status
      n = 1
      call FileMetaData_deserialize(buffer(n:), this%fmd, status)
      _VERIFY(status)
      call deserialize_intrinsic(buffer(n:), length)
      n = n + length
      call deserialize_intrinsic(buffer(n:), this%create_mode)
      _RETURN(_SUCCESS)
   end subroutine deserialize
Call graph
deserialize calls deserialize_intrinsic, filemetadata_deserialize, mapl_return, mapl_verify
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
filemetadata_deserialize calls mapl_return, mapl_verify, filemetadata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
filemetadata calls new_filemetadata
deserialize_int32_0d calls mapl_return, mapl_assert
deserialize_int32_1d calls mapl_return, mapl_assert
deserialize_int64_0d calls mapl_return, mapl_assert
deserialize_int64_1d calls mapl_return, mapl_assert
deserialize_logical_0d calls mapl_return, mapl_assert
deserialize_logical_1d calls mapl_return, mapl_assert
deserialize_real32_0d calls mapl_return, mapl_assert
deserialize_real32_1d calls mapl_return, mapl_assert
deserialize_real64_0d calls mapl_return, mapl_assert
deserialize_real64_1d calls mapl_return, mapl_assert
deserialize_string calls mapl_return, mapl_assert
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
new_filemetadata calls stringintegermap, stringvector