destroy_rh_regen_LS – MAPL
destroy_rh_regen_LS Module Procedure
77 statements
Source File
module procedure destroy_rh_regen_LS module subroutine destroy_rh_regen_LS(this, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Call graph
destroy_rh_regen_ls calls ESMF_ClockGet, esmf_fieldbundledestroy, esmf_fieldbundleget, esmf_fielddestroy, mapl_am_i_root, reinitialize, destroy_locstream, destroy_route_handle, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
destroy_locstream calls mapl_return, mapl_verify, ESMF_LocStreamDestroy
destroy_route_handle calls mapl_return, mapl_verify, ESMF_LocStreamDestroy, ESMF_RouteHandleDestroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm