destroy_rh_regen_ogrid – MAPL
destroy_rh_regen_ogrid Subroutine
75 statements
Source File
private subroutine destroy_rh_regen_ogrid(this, key_grid_label, output_grids, sp, rc)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
character(len=*), intent(in) :: key_grid_label
type(StringGridMap), intent(inout), target :: output_grids
class(sampler) :: sp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine destroy_rh_regen_ogrid (this, key_grid_label, output_grids, sp, rc)
    implicit none
    class(samplerHQ) :: this
    class(sampler) :: sp
    type (StringGridMap), target, intent(inout) :: output_grids
    character(len=*), intent(in)  :: key_grid_label
    integer, intent(out), optional :: rc
    integer :: status
    class(AbstractGridFactory), pointer :: factory
    type(ESMF_Time) :: currTime
    type(ESMF_TimeInterval) :: dur
    character(len=ESMF_MAXSTR) :: time_string
    type(ESMF_Grid), pointer :: pgrid
    type(ESMF_Grid) :: ogrid
    type(ESMF_Grid) :: input_grid
    character(len=ESMF_MAXSTR) :: key_str
    type (StringGridMapIterator) :: iter
    character(len=:), pointer :: key
    type (ESMF_Config) ::  config_grid
    integer :: i, numVars
    character(len=ESMF_MAXSTR), allocatable :: names(:)
    type(ESMF_Field) :: field
    if ( .NOT. ESMF_AlarmIsRinging(this%alarm) ) then
       write(6,*) 'ck: regen,  not in alarming'
       rc=0
       return
    endif
    !__ s1. destroy ogrid + regen ogrid
    key_str=trim(key_grid_label)
    pgrid => output_grids%at(trim(key_grid_label))
    call grid_manager%destroy(pgrid,_RC)
    call ESMF_ClockGet (this%clock, CurrTime=currTime, _RC )
    iter = output_grids%begin()
    do while (iter /= output_grids%end())
       key => iter%key()
       if (trim(key)==trim(key_str)) then
          ogrid = this%create_grid (key_str, currTime, _RC)
          call output_grids%set(key, ogrid)
          this%ogrid = ogrid
       endif
       call iter%next()
    enddo
    !__ s2. destroy RH
    call sp%regrid_handle%destroy(_RC)
    !__ s3. destroy acc_bundle / output_bundle
   call ESMF_FieldBundleGet(sp%acc_bundle,fieldCount=numVars,_RC)
   allocate(names(numVars),stat=status)
   call ESMF_FieldBundleGet(sp%acc_bundle,fieldNameList=names,_RC)
   do i=1,numVars
      call ESMF_FieldBundleGet(sp%acc_bundle,trim(names(i)),field=field,_RC)
      call ESMF_FieldDestroy(field,noGarbage=.true., _RC)
   enddo
   call ESMF_FieldBundleDestroy(sp%acc_bundle,noGarbage=.true.,_RC)
   call ESMF_FieldBundleGet(sp%output_bundle,fieldCount=numVars,_RC)
   allocate(names(numVars),stat=status)
   call ESMF_FieldBundleGet(sp%output_bundle,fieldNameList=names,_RC)
   do i=1,numVars
      call ESMF_FieldBundleGet(sp%output_bundle,trim(names(i)),field=field,_RC)
      call ESMF_FieldDestroy(field,noGarbage=.true., _RC)
   enddo
   call ESMF_FieldBundleDestroy(sp%output_bundle,noGarbage=.true.,_RC)
   _RETURN(ESMF_SUCCESS)
  end subroutine destroy_rh_regen_ogrid
Call graph
destroy_rh_regen_ogrid calls ESMF_AlarmIsRinging, ESMF_ClockGet, esmf_fieldbundledestroy, esmf_fieldbundleget, esmf_fielddestroy, destroy, create_grid, m_at, m_begin, m_key, m_next, m_set, mapl_return, mapl_verify
create_grid calls mapl_return, mapl_verify, ESMF_ConfigSetAttribute, ESMF_TimeGet, make_grid
m_at calls m_find
m_begin calls s_begin
m_next calls s_next
m_set calls s_insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls destroy_rh_regen_ogrid