destroy – MAPL
destroy Subroutine
9 statements
Source File
private subroutine destroy(this, rc)
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy(this, rc)
      class(AbstractGridFactory), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      call ESMF_GridDestroy(this%grid, noGarbage=.true., _RC)
      _RETURN(_SUCCESS)
   end subroutine destroy
Call graph
destroy calls ESMF_GridDestroy, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
destroy_grid calls destroy
destroy_rh_regen_ogrid calls destroy
run calls destroy_rh_regen_ogrid