destroy_state – MAPL
destroy_state Subroutine
12 statements
Source File
private subroutine destroy_state(this, rc)
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
integer, intent(out) :: rc
Calls
Contents
Source Code
destroy_state
Source Code
  subroutine destroy_state(this, rc)
    class(MAPL_CapGridComp), intent(inout) :: this
    integer, intent(out) :: rc
    integer :: status
    call MAPL_DestroyStateSave(this%gcs(this%root_id),rc=status)
    _VERIFY(status)
     if (allocated(this%alarm_list)) deallocate(this%alarm_list)
     if (allocated(this%AlarmRingTime)) deallocate(this%alarmRingTime)
     if (allocated(this%ringingState)) deallocate(this%ringingState)
    _RETURN(_SUCCESS)
  end subroutine destroy_state
Call graph
destroy_state calls mapl_destroystatesave, mapl_verify, mapl_return
mapl_destroystatesave calls mapl_destroystatesave, mapl_verify, mapl_internalstateretrieve, mapl_destroyfile, getfile
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_destroyfile calls dealloc_
mapl_throw_exception calls initialize
getfile calls mapl_verify, mapl_return, getfilemem, mapl_am_i_root, mapl_open
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_internalstatecreate calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompsetinternalstate
dealloc_ calls mapl_return, mapl_assert
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_open calls mapl_verify, mapl_return, mapl_am_i_root