destroy_grid – MAPL
destroy_grid Subroutine
24 statements
Source File
private subroutine destroy_grid(this, grid, unusable, rc)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout), target :: this
type(ESMF_Grid), intent(inout) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy_grid(this, grid, unusable, rc)
      use ESMF
      class (GridManager), target, intent(inout) :: this
      type (ESMF_Grid), intent(inout) :: grid
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      integer (kind=ESMF_KIND_I8) :: id
      class(AbstractGridFactory), pointer :: factory
      type(Integer64GridFactoryMapIterator) :: iter
      call ESMF_AttributeGet(grid, factory_id_attribute, id, _RC)
      factory => this%factories%at(id)
      call factory%destroy(_RC)
      iter = this%factories%find(id)
      call this%factories%erase(iter)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine destroy_grid
Call graph
destroy_grid calls ESMF_AttributeGet, erase, destroy, m_at, m_find, mapl_return, mapl_verify
destroy calls mapl_return, mapl_verify, ESMF_GridDestroy
m_at calls m_find
m_find calls s_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_erase_one calls erase
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
destroy_rh_regen_ogrid calls destroy
run calls destroy_rh_regen_ogrid