destroy_route_handle – MAPL
destroy_route_handle Subroutine
39 statements
Source File
private subroutine destroy_route_handle(this, kind, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(inout) :: this
type(ESMF_TypeKind_Flag), intent(in) :: kind
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy_route_handle(this, kind, rc)
      class(EsmfRegridder), intent(inout) :: this
      type(ESMF_TypeKind_Flag), intent(in) :: kind
      integer, optional, intent(out) :: rc
     type (RegridderSpec) :: spec
     type(ESMF_RouteHandle) :: dummy_rh
     type(RegridderSpecRouteHandleMap), pointer :: route_handles, transpose_route_handles
     type(ESMF_RouteHandle) :: route_handle
     type(RegridderSpecRouteHandleMapIterator) :: iter
     integer :: status
     logical :: compute_transpose
     if (kind == ESMF_TYPEKIND_R4) then
        route_handles => route_handles_r4
        transpose_route_handles => transpose_route_handles_r4
     else if(kind == ESMF_TYPEKIND_R8) then
        route_handles => route_handles_r8
        transpose_route_handles => transpose_route_handles_r8
     else
        _FAIL('unsupported type kind (must be R4 or R8)')
     end if
     spec = this%get_spec()
     _ASSERT(route_handles%count(spec) == 1, 'Did not find this spec in route handle table.')
     route_handle = route_handles%at(spec)
     call ESMF_RouteHandleDestroy(route_handle, noGarbage=.true.,_RC)
     iter = route_handles%find(spec)
     call route_handles%erase(iter)
     compute_transpose = IAND(spec%hints,REGRID_HINT_COMPUTE_TRANSPOSE) /= 0
     if (compute_transpose) then
        _ASSERT(transpose_route_handles%count(spec) == 1, 'Did not find this spec in route handle table.')
        route_handle = transpose_route_handles%at(spec)
        call ESMF_RouteHandleDestroy(route_handle, noGarbage=.true., _RC)
        iter = transpose_route_handles%find(spec)
        call transpose_route_handles%erase(iter)
     end if
      _RETURN(_SUCCESS)
   end subroutine destroy_route_handle
Call graph
destroy_route_handle calls ESMF_RouteHandleDestroy, mapl_assert, erase, get_spec, m_at, m_find, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_at calls m_find
m_find calls s_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_erase_one calls erase
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
destroy calls destroy_route_handle