destroy_locstream – MAPL
destroy_locstream Subroutine
12 statements
Source File
private subroutine destroy_locstream(this, locstream, rc)
Type Bound
LocStreamFactory
Arguments
Type Intent Optional Attributes Name
class(LocStreamFactory) :: this
type(ESMF_LocStream) :: locstream
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine destroy_locstream(this,locstream,rc)
        class (LocStreamFactory) :: this
        type(ESMF_LocStream) :: locstream
        integer, optional, intent(out) :: rc
        integer :: status
        if (allocated(this%lons)) deallocate (this%lons)
        if (allocated(this%lats)) deallocate (this%lats)
        call ESMF_LocStreamDestroy (locstream,noGarbage=.true.,_RC)
        _RETURN(_SUCCESS)
      end subroutine destroy_locstream
Call graph
destroy_locstream calls ESMF_LocStreamDestroy, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
destroy_rh_regen_ls calls destroy_locstream