destroy – MAPL
destroy Subroutine
9 statements
Source File
private subroutine destroy(this, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine destroy(this, rc)
      class(EsmfRegridder), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      call this%destroy_route_handle(ESMF_TYPEKIND_R4, _RC)
      _RETURN(_SUCCESS)
   end subroutine destroy
Call graph
destroy calls destroy_route_handle, mapl_return, mapl_verify
destroy_route_handle calls mapl_return, mapl_verify, ESMF_RouteHandleDestroy, mapl_assert, erase, get_spec, m_at, m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
m_at calls m_find
m_find calls s_find
mapl_throw_exception calls initialize
m_erase_one calls erase
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
s_find calls at, exists, find_index, s_ordereq