destroy_route_handle – MAPL
destroy_route_handle Subroutine
11 statements
Source File
private subroutine destroy_route_handle(this, rc)
Type Bound
LocstreamRegridder
Arguments
Type Intent Optional Attributes Name
class(LocstreamRegridder) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine destroy_route_handle(this,rc)
     class(LocstreamRegridder) :: this
     integer, optional, intent(out) :: rc
     integer :: status
     call ESMF_RouteHandleDestroy(this%route_handle, noGarbage=.true., _RC)
     call ESMF_LocStreamDestroy (this%locstream, noGarbage=.true., _RC)
     _RETURN(_SUCCESS)
   end subroutine destroy_route_handle
Call graph
destroy_route_handle calls ESMF_LocStreamDestroy, ESMF_RouteHandleDestroy, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
destroy_rh_regen_ls calls destroy_route_handle