detect_cf_vertical_coord_var – MAPL
detect_cf_vertical_coord_var Function
25 statements
Source File
private function detect_cf_vertical_coord_var(var, rc) result(is_vertical_coord_var)
Arguments
Type Intent Optional Attributes Name
type(Variable), intent(in) :: var
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
    function detect_cf_vertical_coord_var(var, rc) result(is_vertical_coord_var)
       logical :: is_vertical_coord_var
       type(Variable), intent(in) :: var
       integer, optional, intent(out) :: rc
       integer :: status
       logical :: has_positive, has_pressure_units, has_units
       character(len=:), allocatable :: units
       character(len=3) :: pressure_hpa
       is_vertical_coord_var = .false.
       pressure_hpa = "Pa"
       has_positive = var%is_attribute_present("positive", _RC)
       has_units = var%is_attribute_present("units", _RC)
       has_pressure_units = .false.
       if (has_units) then
          units = var%get_attribute_string("units", _RC)
          has_pressure_units = safe_are_convertible(units, pressure_hpa, _RC)
       end if
       is_vertical_coord_var = has_pressure_units .or. has_positive
       _RETURN(_SUCCESS)
    end function detect_cf_vertical_coord_var
Call graph
detect_cf_vertical_coord_var calls get_attribute_string, is_attribute_present, mapl_return, mapl_verify, safe_are_convertible
get_attribute_string calls mapl_return, mapl_verify, mapl_assert, get_attribute, get_value
is_attribute_present calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
safe_are_convertible calls mapl_return, mapl_verify, is_free, udunits_are_convertible
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_return, mapl_assert, m_at
get_error_message calls at, insert
get_value calls mapl_return
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
new_verticalcoordinate calls detect_cf_vertical_coord_var
verticalcoordinate calls new_verticalcoordinate