detect_metadata – MAPL
detect_metadata Subroutine
36 statements
Source File
private subroutine detect_metadata(this, metadata_out, time, multi_rule, get_range, rc)
Type Bound
ExtDataFileStream
Arguments
Type Intent Optional Attributes Name
class(ExtDataFileStream), intent(inout) :: this
type(FileMetadataUtils), intent(inout) :: metadata_out
type(ESMF_Time), intent(in) :: time
logical, intent(in) :: multi_rule
logical, intent(in), optional :: get_range
integer, intent(out), optional :: rc
Calls
Contents
Source Code
detect_metadata
Source Code
   subroutine detect_metadata(this,metadata_out,time,multi_rule,get_range,rc)
      class(ExtDataFileStream), intent(inout) :: this
      type(FileMetadataUtils), intent(inout) :: metadata_out
      type(ESMF_Time),          intent(in)  :: time
      logical, intent(in)  :: multi_rule
      logical, optional, intent(in)  :: get_range
      integer, optional, intent(out) :: rc
      logical :: get_range_
      type(MAPLDataCollection), pointer :: collection
      type(FileMetadataUtils), pointer :: metadata
      type(ESMF_Time), allocatable :: time_series(:)
      integer :: status
      if (multi_rule) then
         _ASSERT(allocated(this%valid_range),"must use a collection with valid range")
      end if
      if (present(get_range)) then
         get_range_ = get_range
      else
         get_range_ = .false.
      end if
      collection => DataCollections%at(this%collection_id)
      if (get_range_ .and. (.not.allocated(this%valid_range))) then
         if (index('%',this%file_template) == 0) then
            metadata => collection%find(this%file_template)
            call metadata%get_time_info(timeVector=time_series,_RC)
            allocate(this%valid_range(2))
            this%valid_range(1)=time_series(1)
            this%valid_range(2)=time_series(size(time_series))
         end if
      end if
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(metadata_out)
      _UNUSED_DUMMY(time)
   end subroutine detect_metadata
Call graph
detect_metadata calls at, find, mapl_assert, get_time_info, mapl_return, mapl_verify, valid_range
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_time_info calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, get_coordinate_info, get_file_name
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_coordinate_info calls mapl_assert, mapl_return, mapl_verify, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, get_file_name, get_dimension, get_ith_dimension, var_has_attr
get_error_message calls at
get_file_name calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
var_has_attr calls mapl_assert, mapl_return, mapl_verify, get_file_name, get_variable, is_attribute_present