die – MAPL
die Subroutine
5 statements
Source File
private subroutine die(name)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: name
Called by
Contents
Source Code
die
Source Code
subroutine die (name)
character(len=*) :: name
print *, trim(name)//': fatal error in CFIO, but not aborting...'
return
end subroutine die
Call graph
gx_ calls die
strtemplate_ calls die, gx_
esmf_cfiostrtemplate calls strtemplate_
esmf_cfiosdffilecreate calls strtemplate_
esmf_cfiosdffileopen calls strtemplate_
esmf_cfiosdfvarread1d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarwrite1d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite2d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite3d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfiofilecreate calls esmf_cfiosdffilecreate
esmf_cfiofileopen calls esmf_cfiosdffileopen