DiffDate – MAPL
DiffDate Function
28 statements
Source File
public function DiffDate(yyyymmhh_1, hhmmss_1, yyyymmhh_2, hhmmss_2)
DiffDate — Calculates the number of seconds between two times.
This function returns the number of seconds between two times. Each time is specified with two integers, one representing a date in the format YYYYMMDD and one representing a time in the format HHMMSS. This function determines the Julian day of each date using the “julday” function from the book “Numerical Recipes in FORTRAN, the art of scientific computing (2nd Ed.), by William H. Press, Saul A. Teukolsky, William T. Vetterling, and Brian P. Flannery (Cambridge University Press, 1992). The difference between the two times is then calculated and returned. The times need not be in chronological order as the function returns the abs value. -1 is returned in the event of an error.
RETURNED VALUE:
Integer function returns number of seconds between the the times given as input. -1 is returned in the event of an error.
History
17Oct97 Lucchesi Initial version.
2010.05.11 Lucchesi Integer for julian seconds changed to 64-bit. StartDate constant no longer needed.
! DiffDate = iabs (julsec2 - julsec1)
Arguments
Type Intent Optional Attributes Name
integer :: yyyymmhh_1
integer :: hhmmss_1
integer :: yyyymmhh_2
integer :: hhmmss_2
Return Value integer(kind=int64)
Calls
Called by
Call graph
diffdate calls cfio_parseinttime, julday
cfio_getvar calls diffdate
cfio_putvar calls diffdate
cfio_sgetvar calls diffdate
cfio_sputvar calls diffdate
esmf_cfiosdfvarreadt2d__ calls diffdate
esmf_cfiosdfvarreadt3d__ calls diffdate
esmf_cfiovarreadt2d__ calls diffdate
esmf_cfiovarreadt3d__ calls diffdate
writebnds calls diffdate
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d__, esmf_cfiosdfvarreadt2d_, esmf_cfiosdfvarreadt3d_
esmf_cfiovarreadt2 calls esmf_cfiovarreadt2d__, esmf_cfiovarreadt3d__
esmf_cfioeosvarwrite1d_ calls writebnds
esmf_cfioeosvarwrite2d_ calls writebnds
esmf_cfioeosvarwrite3d_ calls writebnds
esmf_cfiosdfvarread1d_ calls cfio_sgetvar
esmf_cfiosdfvarread2d_ calls cfio_getvar, cfio_sgetvar
esmf_cfiosdfvarread3d_ calls cfio_getvar
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__
esmf_cfiosdfvarwrite1d_ calls cfio_sputvar, writebnds
esmf_cfiosdfvarwrite2d_ calls cfio_putvar, cfio_sputvar, writebnds
esmf_cfiosdfvarwrite3d_ calls cfio_putvar, writebnds
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
esmf_cfioeosvarwrite calls esmf_cfioeosvarwrite1d_, esmf_cfioeosvarwrite2d_, esmf_cfioeosvarwrite3d_
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfiovarreadt calls esmf_cfiovarreadt2d_, esmf_cfiovarreadt3d_