dispatch – MAPL
dispatch Subroutine
10 statements
Source File
private recursive subroutine dispatch(this, visitor, rc)
Type Bound
AbstractMessage
Arguments
Type Intent Optional Attributes Name
class(AbstractMessage), intent(in) :: this
class(SurrogateMessageVisitor), intent(inout), target :: visitor
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    recursive subroutine dispatch(this, visitor, rc)
       class (AbstractMessage), intent(in) :: this
       class (SurrogateMessageVisitor), target, intent(inout) :: visitor
       integer, optional, intent(out) :: rc
       integer :: status
       call visitor%handle(this, rc=status)
       _VERIFY(status)
       _RETURN(_SUCCESS)
    end subroutine dispatch
Call graph
dispatch calls handle, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
handle_done calls dispatch
run calls dispatch
run_done calls dispatch
start calls run
test_handle_addextcollection calls run
test_handle_prefetchdata calls run
test_return_on_terminate calls run
test_return_on_terminate_b calls run