distribute_task – MAPL
distribute_task Subroutine
13 statements
Source File
private subroutine distribute_task(this, id, node_rank, innode_rank)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(in) :: this
integer, intent(in) :: id
integer, intent(out) :: node_rank
integer, intent(out) :: innode_rank
Called by
Source Code
   subroutine distribute_task(this,id, node_rank, innode_rank)
      class(AbstractServer),intent(in) :: this
      integer, intent(in)   :: id
      integer,intent(out) :: node_rank,innode_rank
      integer :: rank
      innode_rank = mod(id, this%InNode_npes)
      rank        = mod(id, this%npes)
      node_rank   = this%Node_Ranks(rank)
     _UNUSED_DUMMY(this)
   end subroutine distribute_task
Call graph
am_i_reading_pe calls distribute_task
get_datafrommem calls distribute_task, get_datafrommem
read_and_gather calls distribute_task, am_i_reading_pe
read_and_share calls distribute_task
handle_done_collective_prefetch calls read_and_gather, read_and_share