do_regrid – MAPL
do_regrid Subroutine
32 statements
Source File
private subroutine do_regrid(this, src_field, dst_field, unusable, doTranspose, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
type(ESMF_Field), intent(in) :: src_field
type(ESMF_Field), intent(inout) :: dst_field
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: doTranspose
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine do_regrid(this, src_field, dst_field, unusable, doTranspose, rc)
      class (EsmfRegridder), intent(in) :: this
      type (ESMF_Field), intent(in) :: src_field
      type (ESMF_Field), intent(inout) :: dst_field
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in) :: doTranspose
      integer, optional, intent(out) :: rc
      type (ESMF_RouteHandle) :: route_handle
      type (RegridderSpec) :: spec
      type(ESMF_TypeKind_Flag) :: src_kind, dst_kind
      character(*), parameter :: Iam = 'MAPL_EsmfRegridder::do_regrid()'
      integer :: status
      _UNUSED_DUMMY(unusable)
      call ESMF_FieldGet(src_field, typekind = src_kind, rc = status)
      _VERIFY(status)
      call ESMF_FieldGet(dst_field, typekind = dst_kind, rc = status)
      _VERIFY(status)
      _ASSERT(src_kind == dst_kind,'inconsistent kinds')
      route_handle = this%select_route_handle(src_kind, do_transpose = doTranspose, rc = status)
      _VERIFY(status)
      spec = this%get_spec()
      if (spec%regrid_method /= REGRID_METHOD_NEAREST_STOD) then
         call ESMF_FieldRegrid(src_field, dst_field, &
              & routeHandle=route_handle, &
              & dynamicMask=this%dynamic_mask, &
              & termorderflag=ESMF_TERMORDER_SRCSEQ, &
              & zeroregion=ESMF_REGION_SELECT, &
              & rc=status)
         _VERIFY(status)
      else
         call ESMF_FieldRegrid(src_field, dst_field, &
              & routeHandle=route_handle, &
              & termorderflag=ESMF_TERMORDER_SRCSEQ, &
              & zeroregion=ESMF_REGION_SELECT, &
              & rc=status)
         _VERIFY(status)
      end if
   end subroutine do_regrid
Call graph
do_regrid calls ESMF_FieldRegrid, esmf_fieldget, mapl_assert, get_spec, mapl_verify, select_route_handle
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
select_route_handle calls mapl_assert, get_spec, mapl_verify, create_route_handle, m_at, mapl_return
create_route_handle calls esmf_fieldget, mapl_assert, get_spec, mapl_verify, mapl_return, ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, ESMF_GridGetItem, esmf_fieldcreate, esmf_fielddestroy, insert, mapl_gridhasde
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
m_find calls s_find
mapl_gridhasde calls mapl_verify, mapl_return, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
regrid_scalar_2d_real32 calls do_regrid
regrid_scalar_2d_real64 calls do_regrid
regrid_scalar_3d_real32 calls do_regrid
regrid_scalar_3d_real64 calls do_regrid
regrid_vector_2d_real32 calls do_regrid
regrid_vector_2d_real64 calls do_regrid
regrid_vector_3d_real32 calls do_regrid
regrid_vector_3d_real64 calls do_regrid
transpose_regrid_scalar_2d_real32 calls do_regrid
transpose_regrid_scalar_3d_real32 calls do_regrid
transpose_regrid_vector_2d_real32 calls do_regrid
transpose_regrid_vector_3d_real32 calls do_regrid