DoMasking_ – MAPL
DoMasking_ Subroutine
46 statements
Source File
private subroutine DoMasking_(field, im, jm, lons, lats, undef, sat_name, nymd, nhms, dt, swath, ihalo, jhalo, rc)
Uses
MAPL_NominalOrbitsMod
The routine DoMasking_ …
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: field(im,jm)
integer, intent(in) :: im
integer, intent(in) :: jm
real, intent(in) :: lons(im,jm)
real, intent(in) :: lats(im,jm)
real, intent(in) :: undef
character(len=*), intent(in) :: sat_name
Satellite name
integer, intent(in) :: nymd(2)
Beginning/ending date: YYYYMMDD
integer, intent(in) :: nhms(2)
Beginning/ending time: HHMMSS
integer, intent(in) :: dt
delta t in secs
real, intent(in) :: swath(3)
integer, intent(in) :: ihalo(2)
integer, intent(in) :: jhalo(2)
integer, intent(out), optional :: rc
Error return code = 0 all is well = 3 memory allocation error
Calls
Called by
Source Code
       subroutine DoMasking_ (field, im, jm, lons, lats, undef, &
                              sat_name, nymd, nhms, dt, swath,  &
                              ihalo, jhalo, rc )
       use MAPL_NominalOrbitsMod
       implicit NONE
! !INPUT PARAMETERS:
       integer, intent(in)            :: im, jm
       integer, intent(in)            :: ihalo(2), jhalo(2)
       real, intent(in) :: lons(im,jm)
       real, intent(in) :: lats(im,jm)
       real, intent(in) :: swath(3)
       real, intent(in) :: undef
       character(len=*), intent(in) :: sat_name     !! Satellite name
       integer, intent(in) :: dt      !! delta t in secs
       integer, intent(in) :: nymd(2) !! Beginning/ending date: YYYYMMDD
       integer, intent(in) :: nhms(2) !! Beginning/ending time: HHMMSS
! !OUTPUT PARAMETERS:
       real,    intent(inout) :: field(im,jm)
       integer, intent(out), optional   :: rc    !! Error return code
                                       !! = 0  all is well
                                       !! = 3  memory allocation error
!                               ----
       INTEGER, PARAMETER :: dp=SELECTED_REAL_KIND(15,307)
!      Local workspace
!      ---------------
       integer :: isegs, jsegs, mask(im,jm)
       real(dp)::  V_mean
       real(dp) :: SwathWidth(2) = (/ 0.0, 0.0 /)
       integer nobs
       real(dp), pointer :: tlons(:)   => null()
       real(dp), pointer :: tlats(:)   => null()
       real(dp), pointer :: slons(:,:) => null()
       real(dp), pointer :: slats(:,:) => null()
       SwathWidth(1:2) = swath(1:2) ! type conversion
!      Interpoaltion parameters; swath(3) is the swath resolution, in km
!      -----------------------------------------------------------------
       V_mean = 7.5             ! Mean sat speed in km/s; assumes a 90 minute period
                                ! this should be a function of satellite.
       isegs = nint((swath(1)+swath(2)) / swath(3) ) ! segments across-track
       jsegs =  V_mean * dt / swath(3)               ! segments along-track
!      Simple masking without swath
!      ----------------------------
       if ( swath(1) .eq. 0 .AND. swath(2) .eq. 0 ) then
!         Compute tracks
!         --------------
          call orbits_track(tlons,tlats, sat_name, nymd, nhms, dt, rc)
!         Simple masking
!         --------------
          mask=0
          call orb_mask_lonlat(mask,im,jm,lons,lats,tlons,tlats,size(tlons),jsegs,-180.,180.)
          deallocate(tlons,tlats)
       else
!         Compute tracks
!         --------------
          call orbits_swath(slons,slats, sat_name, nymd, nhms, dt,SwathWidth, rc, wrap=.true.)
!         Swath masking
!         -------------
          nobs = size(slons)/3
          mask = 0
          call orb_swath_mask_lonlat(mask,im,jm,lons,lats,slons,slats,nobs,isegs,jsegs,-180.,180.)
          deallocate(slons,slats)
       end if
!      Add optional halo
!      -----------------
       if ( (sum(ihalo) + sum(jhalo)) > 0) then
          call orb_halo(im,jm,mask,ihalo,jhalo)
       end if
!      Apply mask to field
!      -------------------
       field = 1.0
       where ( mask /= 1 ) field = undef
!      All done
!      --------
     end subroutine DoMasking_
Call graph
domasking_ calls orb_halo, orb_mask_lonlat, orb_swath_mask_lonlat, orbits_swath, orbits_track
orb_halo calls mapl_return
orb_mask_lonlat calls flatten_latlon, ijsearch, orb_edges_1d, pnt_in_rect
orb_swath_mask_lonlat calls flatten_latlon, ijsearch, orb_edges_1d, pnt_in_rect
orbits_swath calls orbits_track, find_sweeppoints, satname2int
orbits_track calls built_vecsize, find_waypointslat, get_time, satname2int
find_sweeppoints calls linspace, get_azimuth, get_reckon
find_waypointslat calls built_vecsize, built_vec, get_latlon
get_time calls ods_julian
mapl_return calls get_error_message, mapl_throw_exception
run_ calls domasking_