done_prefetch – MAPL
done_prefetch Subroutine
14 statements
Source File
private subroutine done_prefetch(this, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine done_prefetch(this, unusable, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      class (ClientThread), pointer :: clientPtr
      clientPtr =>this%current()
      call clientPtr%done_prefetch()
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine done_prefetch
Call graph
done_prefetch calls current, done_prefetch, mapl_return, get_connection, mapl_verify, send
current calls at
mapl_return calls get_error_message, mapl_throw_exception
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
v_at_32 calls v_at_size_kind