done_collective_prefetch – MAPL
done_collective_prefetch Subroutine
16 statements
Source File
private subroutine done_collective_prefetch(this, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine done_collective_prefetch(this, unusable, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      class (ClientThread), pointer :: clientPtr
      clientPtr =>this%current()
      call clientPtr%done_collective_prefetch(_RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine done_collective_prefetch
Call graph
done_collective_prefetch calls current, done_collective_prefetch, mapl_return, mapl_verify, get_connection, isempty_requesthandle, send
current calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
isempty_requesthandle calls mapl_return, m_begin
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_begin calls s_begin
v_at_32 calls v_at_size_kind
mapl_read_bundle calls done_collective_prefetch
run_ calls done_collective_prefetch
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main