done_collective_stage – MAPL
done_collective_stage Subroutine
16 statements
Source File
private subroutine done_collective_stage(this, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine done_collective_stage(this, unusable, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      class (ClientThread), pointer :: clientPtr
      integer :: status
      clientPtr =>this%current()
      call clientPtr%done_collective_stage(_RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine done_collective_stage
Call graph
done_collective_stage calls current, done_collective_stage, mapl_return, mapl_verify, get_connection, isempty_requesthandle, send
current calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
isempty_requesthandle calls mapl_return, m_begin
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_begin calls s_begin
v_at_32 calls v_at_size_kind
mapl_bundlewritencpar calls done_collective_stage
run_model calls done_collective_stage
run calls done_collective_stage
write_to_file calls done_collective_stage
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
main calls write_to_file, run_model
mapl_statevarwritencpar calls mapl_bundlewritencpar
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
mapl_esmfstatewritetofile calls mapl_varwritencpar
regrid_util calls main
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile