done_collective_prefetch – MAPL
done_collective_prefetch Subroutine
15 statements
Source File
private subroutine done_collective_prefetch(this, rc)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine done_collective_prefetch(this, rc)
      class (ClientThread), intent(inout) :: this
      integer, optional, intent(out) :: rc
      class(AbstractSocket),pointer :: connection
      integer :: status
      if (this%isEmpty_RequestHandle()) then
        _RETURN(_SUCCESS)
      endif
      connection=>this%get_connection()
      call connection%send(CollectivePrefetchDoneMessage(),_RC)
      _RETURN(_SUCCESS)
   end subroutine done_collective_prefetch
Call graph
done_collective_prefetch calls get_connection, isempty_requesthandle, mapl_return, mapl_verify, send, done_collective_prefetch
get_connection calls mapl_return, mapl_assert
isempty_requesthandle calls mapl_return, m_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
m_begin calls s_begin
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
s_begin calls s_next
run calls done_collective_prefetch
mapl_read_bundle calls done_collective_prefetch
run_ calls done_collective_prefetch
main calls run, mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main