done – MAPL
done Subroutine
11 statements
Source File
private subroutine done(this, rc)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine done(this, rc)
      class (ClientThread), intent(inout) :: this
      integer, optional, intent(out) :: rc
      class(AbstractSocket),pointer :: connection
      integer :: status
      connection=>this%get_connection()
      call connection%send(DoneMessage(),_RC)
      _RETURN(_SUCCESS)
   end subroutine done
Call graph
done calls get_connection, mapl_return, mapl_verify, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception