DownBit1D – MAPL
DownBit1D Subroutine
18 statements
Source File
private subroutine DownBit1D(x, xr, nbits_to_keep, undef, flops, mpi_comm, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in), target :: x(:)
real, intent(inout), target :: xr(:)
integer, intent(in) :: nbits_to_keep
real, intent(in), optional :: undef
logical, intent(in), optional :: flops
integer, intent(in), optional :: mpi_comm
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine DownBit1D ( x, xr, nbits_to_keep, undef, flops, mpi_comm, rc )
     implicit NONE
!
! !INPUT PARAMETERS:
!
     real,target, intent(in)    ::  x(:)         ! input array
     integer, intent(in) :: nbits_to_keep           ! number of bits per word to retain
     real, OPTIONAL, intent(in) :: undef    ! missing value
     logical, OPTIONAL, intent(in) :: flops ! if true, uses slower float point
                                            !  based algorithm
     integer, optional, intent(in) :: mpi_comm
!
! !OUTPUT PARAMETERS:
!
     real, target, intent(inout)   :: xr(:)   ! precision reduced array; can
     integer, optional, intent(out) :: rc
     real, pointer :: x_tmp(:,:)
     real, pointer :: xr_tmp(:,:)
     type(c_ptr) :: x_ptr, xr_ptr
     x_ptr = c_loc(x(1))
     call c_f_pointer(x_ptr,  x_tmp,[size(x),1])
     xr_ptr = c_loc(xr(1))
     call c_f_pointer(xr_ptr, xr_tmp,[size(x),1])
     call Downbit2d(x_tmp(:,:), xr_tmp(:,:), nbits_to_keep, undef=undef, flops=flops, mpi_comm=mpi_comm, rc=rc)
   end subroutine Downbit1D
Call graph
downbit1d calls downbit2d
downbit2d calls mapl_shavemantissa32, compute_min_max, mapl_verify
compute_min_max calls mapl_verify, mpi_allreduce, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
downbit calls downbit1d
shavebits calls downbit
stagedata calls downbit
bundlepost calls stagedata
run calls shavebits, bundlepost
write_to_file calls bundlepost