DownBit3D – MAPL
DownBit3D Subroutine
14 statements
Source File
private subroutine DownBit3D(x, xr, nbits_to_keep, undef, flops, mpi_comm, rc)
The routine DownBit3D returns a lower precision version of the input array x which retains nbits_to_keep of precision. See routine ESMF_CFIODownBit2D or additional details. This version for rank 3 arrays, calls ESMF_CFIODownBit2D() for each vertical level.
History
06Dec2006 da Silva Initial version.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:,:,:)
input array
real, intent(out) :: xr(:,:,:)
precision reduced array; can share storage with input array if it has same kind
integer, intent(in) :: nbits_to_keep
number of bits per word to retain - no action if nbits_to_keep<1
real, intent(in), optional :: undef
missing value
logical, intent(in), optional :: flops
if true, uses slower float point based algorithm
integer, intent(in), optional :: mpi_comm
integer, intent(out), optional :: rc
error code = 0 - all is well /= 0 - something went wrong
Calls
Called by
Source Code
   subroutine DownBit3D ( x, xr, nbits_to_keep, undef, flops, mpi_comm, rc )
     implicit NONE
!
! !INPUT PARAMETERS:
!
     real, intent(in)    ::  x(:,:,:)       !! input array
     integer, intent(in) :: nbits_to_keep   !! number of bits per word to retain
                                            !! - no action if nbits_to_keep<1
     real, OPTIONAL, intent(in) :: undef    !! missing value
     logical, OPTIONAL, intent(in) :: flops !! if true, uses slower float point
                                            !!  based algorithm
     integer, optional, intent(in) :: mpi_comm
!
! !OUTPUT PARAMETERS:
!
     real, intent(out)   :: xr(:,:,:)       !! precision reduced array; can
                                            !! share storage with input array
                                            !! if it has same kind
     integer, optional, intent(out)  :: rc  !! error code
                                            !!  = 0 - all is well
                                            !! /= 0 - something went wrong
!
!------------------------------------------------------------------------------
   integer :: k
   do k = lbound(x,3), ubound(x,3)
      call DownBit2D ( x(:,:,k), xr(:,:,k), nbits_to_keep, &
                                 undef=undef, flops=flops, mpi_comm=mpi_comm, rc=rc )
   end do
   end subroutine DownBit3D
Call graph
downbit3d calls downbit2d
downbit2d calls mapl_shavemantissa32, compute_min_max, mapl_verify
compute_min_max calls mapl_verify, mpi_allreduce, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
downbit calls downbit3d
shavebits calls downbit
stagedata calls downbit
bundlepost calls stagedata
run calls shavebits, bundlepost
write_to_file calls bundlepost