ECEF2LLA – MAPL
ECEF2LLA Subroutine
16 statements
Source File
private subroutine ECEF2LLA(x, y, z, lat, lon, alt)
alt(k) = abs(z(k))-b
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: x
real(kind=dp), intent(in) :: y
real(kind=dp), intent(in) :: z
real(kind=dp), intent(out) :: lat
real(kind=dp), intent(out) :: lon
real(kind=dp), intent(out) :: alt
Called by
Source Code
SUBROUTINE ECEF2LLA(x, y, z, lat, lon, alt)
!       % ECEF3LLA - convert earth-centered earth-fixed (ECEF)
!       %            cartesian coordinates to latitude, longitude,
!       %            and altitude
!       %
!       % USAGE:
!       % [lat,lon,alt] = ecef2lla(x,y,z)
!       %
!       % lat = geodetic latitude (radians)
!       % lon = longitude (radians)
!       % alt = height above WGS84 ellipsoid (m)
!       % x = ECEF X-coordinate (m)
!       % y = ECEF Y-coordinate (m)
!       % z = ECEF Z-coordinate (m)
!       %
!       % Notes: (1) This function assumes the WGS84 model.
!       %        (2) Latitude is customary geodetic (not geocentric).
!       %        (3) Inputs may be scalars, vectors, or matrices of the same
!       %            size and shape. Outputs will have that same size and shape.
!       %        (4) Tested but no warranty; use at your own risk.
!       %        (5) Michael Kleder, April 2006
       REAL(dp), INTENT(IN)  :: x,y,z
       REAL(dp), INTENT(OUT) :: lat,lon,alt
!      % WGS84 ellipsoid constants:
       REAL(dp)             :: b, ep, p, th, N
       associate(a => MAPL_EARTH_SEMIMAJOR_AXIS, e => MAPL_EARTH_ECCENTRICITY, pi => MAPL_PI_R8)
          b   = sqrt(a**2 * (1-e**2))
          ep  = sqrt((a**2-b**2)/b**2)
          p   = sqrt(x**2+y**2)
          th  = atan2(a*z,b*p)
          lon = atan2(y,x)
          lat = atan2((z+ep**2*b*sin(th)**3),(p-e**2*a*cos(th)**3))
          N   = a/sqrt(1-e**2*sin(lat)**2)
          alt = p/cos(lat)-N
!%        !return lon in range [0,2*pi)
          !lon = mod(lon,2*pi) ! does not the same as matlab
          lon = lon-floor(lon/(2*pi))*(2*pi)
!         % correct for numerical instability in altitude near exact poles:
!         % (after this correction, error is about 2 millimeters, which is about
!         % the same as the numerical precision of the overall function)
          !k= (abs(x)<1.AND.abs(y)<1 )
          !print *, k
          !!alt(k) = abs(z(k))-b
       end associate
END SUBROUTINE ECEF2LLA
Call graph
get_latlon calls ecef2lla
orbits calls ecef2lla
find_delta_t calls get_latlon
find_waypointslat calls get_latlon
redifine_timeint calls get_latlon
orbits_track calls find_waypointslat
domasking_ calls orbits_track
domasking_cs calls orbits_track
orbits_swath calls orbits_track