ECI2ECEF – MAPL
ECI2ECEF Subroutine
23 statements
Source File
private subroutine ECI2ECEF(iSat, fraction2day, ECI_est, ECEF_est)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
real(kind=dp) :: fraction2day
real(kind=dp), intent(in), DIMENSION(:,:) :: ECI_est
real(kind=dp), intent(out), DIMENSION(:,:) :: ECEF_est
Called by
Contents
Source Code
ECI2ECEF
Source Code
SUBROUTINE  ECI2ECEF(iSat,fraction2day,  ECI_est, ECEF_est)
        IMPLICIT NONE
        INTEGER, INTENT(IN)  :: iSat
        REAL(dp), DIMENSION(:,:), INTENT(IN)  :: ECI_est
        REAL(dp), DIMENSION(:,:), INTENT(OUT) :: ECEF_est
        REAL(dp), DIMENSION(3,3) :: RotM        ! rotation matrix from In2ECEF
        INTEGER   :: t1
        REAL(dp)      :: Goft, a1, a2
        REAL(dp)      :: fraction2day
        associate(g0 => MAPL_OMEGA_R8)
           t1 =  Day2year(iSat)
           Goft = g0 + g1p*t1 + g2p(iSat) * fraction2day
           a1 = cos(Goft);
           a2 = sin(Goft);
           RotM = 0.0
           RotM(1,1) = a1
           RotM(1,2) = a2
           RotM(2,1) = -a2
           RotM(2,2) = a1
           RotM(3,3) = 1
           ECEF_est = MATMUL(RotM, ECI_est)
        end associate
END SUBROUTINE ECI2ECEF
Call graph
get_latlon calls eci2ecef
orbits calls eci2ecef
find_delta_t calls get_latlon
redifine_timeint calls get_latlon
find_waypointslat calls get_latlon
orbits_track calls find_waypointslat
orbits_swath calls orbits_track
domasking_ calls orbits_track
domasking_cs calls orbits_track