encode – MAPL
encode Function
15 statements
Source File
private function encode(this, message) result(buffer)
Type Bound
ProtocolParser
Arguments
Type Intent Optional Attributes Name
class(ProtocolParser), intent(in) :: this
class(AbstractMessage), intent(in), target :: message
Return Value integer, allocatable, (:)
Calls
Called by
Source Code
   function encode(this, message) result(buffer)
      integer, allocatable :: buffer(:)
      class (ProtocolParser), intent(in) :: this
      class (AbstractMessage), target, intent(in) :: message
      integer :: length
      length = message%get_length()
      allocate(buffer(1 + length))
      buffer(1) = message%get_type_id()
      call message%serialize(buffer(2:))
      return
      _UNUSED_DUMMY(this)
   end function encode
Call graph
encode calls get_length, get_type_id, serialize
send calls encode
serialize_message_vector calls encode
test_parse_terminate calls encode
create_remote_win calls serialize_message_vector
put_datatofile calls serialize_message_vector
serialize calls serialize_message_vector
test_back_and_forth calls send
test_send_terminate calls send
start calls create_remote_win