ensemble_comm_splitter – MAPL
ensemble_comm_splitter Function
18 statements
Source File
private function ensemble_comm_splitter(communicator, n_members, npes_member, unusable, isolate_nodes, base_name) result(splitter)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: communicator
integer, intent(in) :: n_members
integer, intent(in) :: npes_member
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: isolate_nodes
character(len=*), intent(in), optional :: base_name
Return Value type(SimpleCommSplitter)
Calls
Called by
Source Code
   function ensemble_comm_splitter(communicator, n_members, npes_member, unusable, isolate_nodes, base_name) result(splitter)
      type (SimpleCommSplitter) :: splitter
      integer, intent(in) :: communicator
      integer, intent(in) :: n_members
      integer, intent(in) :: npes_member
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in) :: isolate_nodes
      character(*), optional, intent(in) :: base_name
      integer :: i
      _UNUSED_DUMMY(unusable)
      splitter = SimpleCommSplitter(communicator, base_name=base_name)
      do i = 1, n_members
         call splitter%add_group(npes=npes_member, isolate_nodes=isolate_nodes)
      end do
   end function ensemble_comm_splitter
Call graph
ensemble_comm_splitter calls add_group
add_group_simple calls mapl_assert, mapl_return, mapl_verify, v_push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
simplecommsplitter calls ensemble_comm_splitter