equals – MAPL
equals Function
6 statements
Source File
private function equals(a, b)
Uses
MAPL_GridManagerMod
Arguments
Type Intent Optional Attributes Name
class(RegridderSpec), intent(in) :: a
type(RegridderSpec), intent(in) :: b
Return Value logical
Calls
Contents
Source Code
equals
Source Code
   logical function equals(a, b)
      use MAPL_GridManagerMod, only: get_factory_id
      class (RegridderSpec), intent(in) :: a
      type (RegridderSpec), intent(in) :: b
      equals = &
           & (get_factory_id(a%grid_in) == get_factory_id(b%grid_in)) .and. &
           & (get_factory_id(a%grid_out) == get_factory_id(b%grid_out)) .and. &
           & (a%regrid_method == b%regrid_method) .and. &
           & (a%hints == b%hints)
   end function equals
Call graph
equals calls get_factory_id
get_factory_id calls esmf_attributeget, mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize