equal_c – MAPL
equal_c Function
37 statements
Source File
private function equal_c(a, b)
Type Bound
CoordinateVariable
Arguments
Type Intent Optional Attributes Name
class(CoordinateVariable), intent(in), target :: a
type(CoordinateVariable), intent(in), target :: b
Return Value logical
Calls
Source Code
   logical function equal_c(a, b)
      class (CoordinateVariable), target, intent(in) :: a
      type (CoordinateVariable), target, intent(in) :: b
      equal_c = (a%Variable == b%Variable)
      if( .not. equal_c) return
      if( .not. allocated(a%coordinate_data) .and. .not. allocated(b%coordinate_data) ) then
         return
      endif
      if( allocated(a%coordinate_data) .and. allocated(b%coordinate_data) ) then
         select type (coords_a=>a%coordinate_data)
         type is (integer(INT32))
            select type (coords_b=>b%coordinate_data)
            type is (integer(INT32))
               equal_c = all(coords_a == coords_b)
            end select
         type is (integer(INT64))
            select type (coords_b=>b%coordinate_data)
            type is (integer(INT64))
               equal_c = all(coords_a == coords_b)
            end select
         type is (real(real32))
            select type (coords_b=>b%coordinate_data)
            type is (real(real32))
               equal_c = all(nearlyEqual(coords_a, coords_b))
            end select
         type is (real(real64))
            select type (coords_b=>b%coordinate_data)
            type is (real(real64))
               equal_c = all(nearlyEqual(coords_a, coords_b))
            end select
         class default
            equal_c = .false.
         end select
      else
         ! one if allocated, the other is not
         equal_c = .false.
      end if
   end function equal_c
Call graph
equal_c calls nearlyequal
nearlyequal calls nearlyequal_real32, nearlyequal_real64