equal – MAPL
equal Function
55 statements
Source File
private function equal(a, b)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: a
class(FileMetadata), intent(in), target :: b
Return Value logical
Calls
Source Code
   logical function equal(a, b)
      class (FileMetadata), target, intent(in) :: a
      class (FileMetadata), target, intent(in) :: b
      equal = same_dimensions(a,b)
      if (.not. equal) return
      equal = same_attributes(a,b)
      if (.not. equal) return
      equal = same_variables(a,b)
   contains
      logical function same_dimensions(a, b) result(equal)
         class (FileMetadata), target, intent(in) :: a
         class (FileMetadata), target, intent(in) :: b
         type (StringIntegerMapIterator) :: iter
         integer, pointer :: dim_a, dim_b
         character(len=:), pointer :: dim_name
         equal = a%dimensions%size() == b%dimensions%size()
         if (.not. equal) return
         iter = a%dimensions%begin()
         do while (iter /= a%dimensions%end())
            dim_name => iter%key()
            dim_b => b%dimensions%at(dim_name)
            equal = (associated(dim_b))
            if (.not. equal) return
            dim_a => iter%value()
            equal = (dim_a == dim_b)
            if (.not. equal) return
            call iter%next()
         end do
      end function same_dimensions
      logical function same_attributes(a, b) result(equal)
         class (FileMetadata), target, intent(in) :: a
         class (FileMetadata), target, intent(in) :: b
         equal = (a%global_var == b%global_var)
      end function same_attributes
      logical function same_variables(a, b) result(equal)
         class (FileMetadata), target, intent(in) :: a
         class (FileMetadata), target, intent(in) :: b
         type (StringVariableMapIterator) :: iter
         class (Variable), pointer :: var_a, var_b
         character(len=:), pointer :: var_name
         equal = a%variables%size() == b%variables%size()
         if (.not. equal) return
         iter = a%variables%begin()
         do while (iter /= a%variables%end())
            var_name => iter%key()
            var_b => b%variables%at(var_name)
            equal = (associated(var_b))
            if (.not. equal) return
            var_a => iter%value()
            equal = (var_a == var_b)
            if (.not. equal) return
            call iter%next()
         end do
      end function same_variables
   end function equal
Call graph
equal calls at, begin, key, next, m_at, m_begin, m_key, m_next
m_at calls m_find
m_begin calls s_begin
m_next calls s_next
m_find calls s_find
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
s_find calls at, exists, find_index, s_ordereq