equalSets – MAPL
equalSets Function
17 statements
Source File
private function equalSets(this, other)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
class(set2), intent(in), target :: other
Return Value logical
Calls
Call graph
equalsets calls s_begin, s_next
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at