erase_nonleaf – MAPL
erase_nonleaf Subroutine
41 statements
Source File
private subroutine erase_nonleaf(this, pos, side)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
integer(kind=SIZE_KIND), intent(inout) :: pos
integer, intent(in) :: side
Calls
Called by
Call graph
erase_nonleaf calls at, set, advpos, exists, rebalance, set_child, set_parent_child
advpos calls at, exists, get_child, opposite
rebalance calls at, exists, get_child, opposite, rot, update_height
set_child calls set
set_parent_child calls at, set_child
get_child calls at
rot calls at, set, exists, set_child, set_parent_child, get_child, opposite, update_height
ti_at_32 calls ti_at_size_kind
ti_set_32 calls set
update_height calls at, set, exists
s_erase_multi calls erase_nonleaf
m_erase_one calls erase
s_erase_one calls erase
s_remove calls erase