erase_nonleaf – MAPL
erase_nonleaf Subroutine
41 statements
Source File
private subroutine erase_nonleaf(this, pos, side)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
integer(kind=SIZE_KIND), intent(inout) :: pos
integer, intent(in) :: side
Calls
Called by
Contents
Call graph
erase_nonleaf calls advpos, exists, rebalance, set_child, set_parent_child
advpos calls exists, get_child, opposite
rebalance calls exists, get_child, opposite, rot, update_height
set_parent_child calls set_child
rot calls exists, set_child, set_parent_child, get_child, opposite, update_height
update_height calls exists
s_erase_multi calls erase_nonleaf