error – MAPL
error Subroutine
35 statements
Source File
private subroutine error(this, message, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, unusable, extra, line, file, rc)
Type Bound
Logger
Arguments
Type Intent Optional Attributes Name
class(Logger), intent(inout), target :: this
character(len=*), intent(in) :: message
class(*), intent(in), optional :: arg1
class(*), intent(in), optional :: arg2
class(*), intent(in), optional :: arg3
class(*), intent(in), optional :: arg4
class(*), intent(in), optional :: arg5
class(*), intent(in), optional :: arg6
class(*), intent(in), optional :: arg7
class(*), intent(in), optional :: arg8
class(*), intent(in), optional :: arg9
class(KeywordEnforcer), intent(in), optional :: unusable
type(StringUnlimitedMap), intent(in), optional, target :: extra
integer, intent(in), optional :: line
character(len=*), intent(in), optional :: file
integer, intent(out), optional :: rc
Called by
Source Code
   subroutine error(this, message, ARG_LIST, unusable, extra, line, file, rc)
      ! Log message with the integer severity 'DEBUG'.
      class (Logger), target, intent(inout) :: this
      character(len=*), intent(in) :: message
      include 'recordOptArgs.inc'
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type (StringUnlimitedMap), optional, target, intent(in) :: extra
      integer, optional, intent(in) :: line
      character(*), optional, intent(in) :: file
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(message)
      _UNUSED_DUMMY(arg1)
      _UNUSED_DUMMY(arg2)
      _UNUSED_DUMMY(arg3)
      _UNUSED_DUMMY(arg4)
      _UNUSED_DUMMY(arg5)
      _UNUSED_DUMMY(arg6)
      _UNUSED_DUMMY(arg7)
      _UNUSED_DUMMY(arg8)
      _UNUSED_DUMMY(arg9)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(extra)
      _UNUSED_DUMMY(line)
      _UNUSED_DUMMY(file)
      _RETURN(_SUCCESS)
   end subroutine error
Call graph
checkunused calls error
getbrackettimeonfile calls error
getbrackettimeonsinglefile calls error
initialize_gc calls error
initialize_ calls error
mapl_extdataextractintegers calls error
mapl_varspecaddreffromitem calls error
mapl_varspecaddreffromitemnew calls error
updatebrackettime calls error, getbrackettimeonfile, getbrackettimeonsinglefile
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist, mapl_varspecaddreffromitemnew
mapl_extdataevaluatemask calls mapl_extdataextractintegers
mapl_genericconncheck calls checkunused, mapl_genericconncheck
mapl_varspecaddreffromlist calls mapl_varspecaddreffromitem
run_ calls updatebrackettime, calcderivedfield
calcderivedfield calls mapl_extdataevaluatemask
mapl_genericsetservices calls mapl_genericconncheck, mapl_genericspecenum, mapl_wirecomponent
mapl_genericspecenum calls mapl_varspecaddreftolist, mapl_genericspecenum
mapl_setvarspecforcc calls mapl_varspecaddreftolist
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
mapl_addinternalspec calls mapl_stateaddinternalspec
setservices calls mapl_genericsetservices