ESMF_CFIODestroy – MAPL
ESMF_CFIODestroy Subroutine
35 statements
Source File
public subroutine ESMF_CFIODestroy(cfio, rc)
ESMF_CFIODestroy – destructor for a CFIO object
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine ESMF_CFIODestroy (cfio, rc)
!
! !INPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      ! Error return code:
                                                ! 0   all is well
!
! !INPUT/OUTPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inout) :: cfio       ! CFIO object
!
!------------------------------------------------------------------------------
      integer :: rtcode
      integer :: i
      if ( cfio%isOpen ) call CFIO_Close(cfio%fid, rtcode)
      if ( associated(cfio%varObjs) ) then
         do i = 1, size(cfio%varObjs)
            call ESMF_CFIOVarInfoDestroy (cfio%varObjs(i), rtcode)
         end do
         deallocate(cfio%varObjs, stat=rtcode)
      end if
      if ( associated(cfio%grids) ) then
         if (cfio%isGridSet) then
            do i = 1, size(cfio%grids)
               call ESMF_CFIOGridDestroy (cfio%grids(i), rtcode)
            end do
         end if
         deallocate(cfio%grids, stat=rtcode)
      end if
      if (associated(cfio%attCharCnts)) deallocate(cfio%attCharCnts,         &
         stat=rtcode)
      if (associated(cfio%attRealCnts)) deallocate(cfio%attRealCnts,         &
         stat=rtcode)
      if (associated(cfio%attIntCnts)) deallocate(cfio%attIntCnts,           &
         stat=rtcode)
      if (associated(cfio%attCharNames)) deallocate(cfio%attCharNames,       &
         stat=rtcode)
      if (associated(cfio%attRealNames)) deallocate(cfio%attRealNames,       &
         stat=rtcode)
      if (associated(cfio%attIntNames)) deallocate(cfio%attIntNames,         &
         stat=rtcode)
      if (associated(cfio%attChars)) deallocate(cfio%attChars, stat=rtcode)
      if (associated(cfio%attReals)) deallocate(cfio%attReals, stat=rtcode)
      if (associated(cfio%attInts)) deallocate(cfio%attInts, stat=rtcode)
      if (associated(cfio%iList)) deallocate(cfio%iList, stat=rtcode)
      if (associated(cfio%rList)) deallocate(cfio%rList, stat=rtcode)
      if (associated(cfio%cList)) deallocate(cfio%cList, stat=rtcode)
      rtcode = 0
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIODestroy
Call graph
esmf_cfiodestroy calls cfio_close, esmf_cfiogriddestroy, esmf_cfiovarinfodestroy
cfio_close calls ncclos, err
esmf_cfiovarinfodestroy calls esmf_cfiogriddestroy, cnodedestroy, inodedestroy, rnodedestroy
find calls esmf_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy, find
unfind calls esmf_cfiodestroy
esmf_iodestroy calls mapl_cfiodestroy
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
finalize calls mapl_cfiodestroy
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls find, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread, esmf_iodestroy
utcfio calls test_main