ESMF_CFIOVarInfoCreate – MAPL
ESMF_CFIOVarInfoCreate Function
36 statements
Source File
public function ESMF_CFIOVarInfoCreate(vName, rc)
ESMF_CFIOVarInfoCreate – ESMF_CFIOVarInfo object constructor
Create a CFIO varInfo object and initialize variables.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: vName
variable name
integer, intent(out), optional :: rc
Error return code:
0 all is well
-1 problem in creating Grid
Return Value type(ESMF_CFIOVarInfo)
Calls
Called by
Source Code
      type(ESMF_CFIOVarInfo) function ESMF_CFIOVarInfoCreate (vName, rc)
!
! !INPUT PARAMETERS:
!
      character(len=*), intent(in), OPTIONAL :: vName     !! variable name
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
                                                !! -1  problem in creating Grid
!
!------------------------------------------------------------------------------
      type(ESMF_CFIOVarInfo) :: varObj ! a CFIO grid object
      integer :: rtcode = 0
      _UNUSED_DUMMY(vName)
      varObj%grid = ESMF_CFIOGridCreate(rc=rtcode)
      if (rtcode .ne. 0) then
         print *, "problem in getting ESMF_CFIOGridCreate:lon"
         rtcode = -1
         if ( present(rc) ) rc = rtcode
         return
      end if
      varObj%nVarAttInt = 0
      varObj%nVarAttChar = 0
      varObj%nVarAttReal = 0
      varObj%twoDimVar = .false.
      varObj%timAve = .false.
      varObj%isGridSet = .false.
      varObj%aveMethod = 'c'
      varObj%cellMthd = 'mean'
      varObj%amiss = 1.E15
      varObj%addOffSet = 0
      varObj%scaleFactor = 1
      varObj%validRange = 1.E15
      varObj%packingRange = 1.E15
      varObj%ordering = 'tzyx'
      varObj%vTitle = 'unknown'
      varObj%vUnits = 'unknown'
      varObj%standardName = 'unknown'
!      allocate(varObj%iList, varObj%rList, varObj%cList)
      nullify(varObj%iList)
      nullify(varObj%rList)
      nullify(varObj%cList)
      if ( present(rc) ) rc = 0
      ESMF_CFIOVarInfoCreate = varObj
      end function ESMF_CFIOVarInfoCreate
Call graph
esmf_cfiovarinfocreate calls esmf_cfiogridcreate
esmf_cfiosdffileopen calls esmf_cfiovarinfocreate
mapl_cfiocreatefrombundle calls esmf_cfiovarinfocreate
test calls esmf_cfiovarinfocreate, esmf_cfiofileopen
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_cfiofileopen calls esmf_cfiosdffileopen
esmf_cfiosdfvarread1d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls esmf_cfiosdffileopen
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
find calls esmf_cfiofileopen
mapl_cfioopenwrite calls esmf_cfiofileopen
mapl_cfioreadbundle calls esmf_cfiofileopen
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate