ESMF_CFIODownBit3D_ – MAPL
ESMF_CFIODownBit3D_ Subroutine
13 statements
Source File
private subroutine ESMF_CFIODownBit3D_(x, xr, nbits, undef, flops, rc)
ESMF_CFIODownBit - GRIB-based compression pre-conditioner
This routine returns a lower precision version of the input array x which retains nbits of precision. See routine ESMF\_CFIODownBit2D for additional details. This version for rank 3 arrays, calls ESMF\_CFIODownBit2D() for each vertical level.
History
06Dec2006 da Silva Initial version.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:,:,:)
input array
real(kind=REAL32), intent(out) :: xr(:,:,:)
precision reduced array; can
if it has same kind
integer, intent(in) :: nbits
number of bits per word to retain - no action if nbits<1
real, intent(in), optional :: undef
logical, intent(in), optional :: flops
if true, uses slower float point based algorithm
integer, intent(out) :: rc
error code = 0 - all is well /= 0 - something went wrong
Calls
Called by
Source Code
   subroutine ESMF_CFIODownBit3D_ ( x, xr, nbits, undef, flops, rc )
     implicit NONE
!
! !INPUT PARAMETERS:
!
     real, intent(in)    ::  x(:,:,:)       !! input array
     integer, intent(in) :: nbits           !! number of bits per word to retain
                                            !! - no action if nbits<1
     real, OPTIONAL, intent(in) :: undef    ! missing value
     logical, OPTIONAL, intent(in) :: flops !! if true, uses slower float point
                                            !!  based algorithm
!
! !OUTPUT PARAMETERS:
!
     real(kind=REAL32), intent(out)   :: xr(:,:,:) !! precision reduced array; can
!                                       !! share storage with input array
                                        !! if it has same kind
     integer, intent(out)  :: rc        !! error code
                                        !!  = 0 - all is well
                                        !! /= 0 - something went wrong
!
!------------------------------------------------------------------------------
   integer :: k
   do k = lbound(x,3), ubound(x,3)
      call ESMF_CFIODownBit2D_ ( x(:,:,k), xr(:,:,k), nbits, &
                                 undef=undef, flops=flops, rc=rc )
   end do
   end subroutine ESMF_CFIODownBit3D_
Call graph
esmf_cfiodownbit3d_ calls esmf_cfiodownbit2d_
esmf_cfiodownbit2d_ calls shavemantissa32
esmf_cfiodownbit calls esmf_cfiodownbit3d_
mapl_cfiowritebundlewait calls esmf_cfiodownbit
utdownbit calls esmf_cfiodownbit
mapl_cfiowritebundle calls mapl_cfiowritebundlewait
esmf_iowrite calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle
mapl_cfiowritestate calls mapl_cfiowritebundle