ESMFL_FieldGetPtrToDataR4_4 – MAPL
ESMFL_FieldGetPtrToDataR4_4 Subroutine
18 statements
Source File
private subroutine ESMFL_FieldGetPtrToDataR4_4(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:,:,:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
esmfl_fieldgetptrtodatar4_4 calls esmf_fieldget, mapl_return, mapl_verify, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_gridhasde calls mapl_return, mapl_verify, esmf_gridget, esmf_distgridget, esmf_delayoutget
mapl_throw_exception calls initialize
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar4_4
regridscalar calls esmfl_fieldgetpointertodata
swap_undef_value calls esmfl_fieldgetpointertodata
regridvector calls esmfl_fieldgetpointertodata