ESMF_CFIOGridCreate – MAPL
ESMF_CFIOGridCreate Function
27 statements
Source File
public function ESMF_CFIOGridCreate(gName, rc)
ESMF_CFIOGridCreate – ESMF_Grid object constructor
Create a CFIO grid object and initialize vars
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: gName
grid object name
integer, intent(out), optional :: rc
Error return code:
0 all is well
Return Value type(ESMF_CFIOGrid)
Called by
Source Code
      type(ESMF_CFIOGrid) function ESMF_CFIOGridCreate (gName, rc)
!
! !INPUT PARAMETERS:
!
      character(len=*), intent(in), OPTIONAL :: gName  !! grid object name
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
!------------------------------------------------------------------------------
      type(ESMF_CFIOGrid) :: grid               ! a CFIO grid object
      grid%im = 0
      grid%jm = 0
      grid%km = 0
      grid%tm = 0
      grid%levUnits = 'unknown'
      grid%coordinate = 'unknown'
      grid%standardName = 'unknown'
      grid%formulaTerm = 'unknown'
      grid%ptop = 0
      grid%ptopUnit = 'Pa'
      grid%twoDimLat = .false.
      grid%reduceGrid = .false.
      grid%stnGrid = .false.
      nullify(grid%lon)
      nullify(grid%lat)
      nullify(grid%lev)
      nullify(grid%ak)
      nullify(grid%bk)
      nullify(grid%sigma)
      if ( present(gName) ) grid%gName = gName
      if ( present(rc) ) rc = 0
      ESMF_CFIOGridCreate = grid
      end function ESMF_CFIOGridCreate
Call graph
esmf_cfiovarinfocreate calls esmf_cfiogridcreate
mapl_cfiocreatefrombundle calls esmf_cfiogridcreate, esmf_cfiovarinfocreate
test calls esmf_cfiogridcreate, esmf_cfiovarinfocreate, esmf_cfiofileopen
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_cfiosdffileopen calls esmf_cfiovarinfocreate
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
esmf_cfiofileopen calls esmf_cfiosdffileopen
esmf_cfiosdfvarread1d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls esmf_cfiosdffileopen
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
find calls esmf_cfiofileopen
mapl_cfioopenwrite calls esmf_cfiofileopen
mapl_cfioreadbundle calls esmf_cfiofileopen
utcfio calls test_main