ESMF_CFIOSdfVarReadT3D__ – MAPL
ESMF_CFIOSdfVarReadT3D__ Subroutine
65 statements
Source File
private subroutine ESMF_CFIOSdfVarReadT3D__(cfio, vName, date, curTime, field, rc, cfio2)
ESMF_CFIOSdfVarReadT3D_ – Read a variable from an existing file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
integer, intent(in) :: date
yyyymmdd
integer, intent(in) :: curTime
hhmmss
real, pointer :: field(:,:,:)
array contains data
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -38 error from NF90_VAR_PUT (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID (lat or lon) rc = -42 error from NF90_INQ_DIMID (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
Calls
Called by
Source Code
      subroutine ESMF_CFIOSdfVarReadT3D__(cfio, vName, date, curTime, field, rc, cfio2)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio      !! a CFIO obj
      character(len=*), intent(in) :: vName       !! variable name
      integer, intent(in) :: date                 !! yyyymmdd
      integer, intent(in) :: curTime              !! hhmmss
      type(ESMF_CFIO), intent(inOut), OPTIONAL :: cfio2  !! second CFIO obj
!
! !OUTPUT PARAMETERS:
!
      real, pointer :: field(:,:,:)             !! array contains data
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
                         !!  rc = -2  time is inconsistent with increment
                         !!  rc = -3  number of levels is incompatible with file
                         !!  rc = -4  im is incompatible with file
                         !!  rc = -5  jm is incompatible with file
                         !!  rc = -6  time must fall on a minute boundary
                         !!  rc = -7  error in diffdate
                         !!  rc = -12  error determining default precision
                         !!  rc = -13  error determining variable type
                         !!  rc = -19  unable to identify coordinate variable
                         !!  rc = -38  error from NF90_VAR_PUT (dimension variable)
                         !!  rc = -40  error from NF90_INQ_VARID
                         !!  rc = -41  error from NF90_INQ_DIMID (lat or lon)
                         !!  rc = -42  error from NF90_INQ_DIMID (lev)
                         !!  rc = -43  error from NF90_INQ_VARID (time variable)
                         !!  rc = -44  error from NF90_GET_ATT (time attribute)
                         !!  rc = -46  error from NF90_GET_VAR
                         !!  rc = -48  error from NF90_INQUIRE
                         !!  rc = -52  error from NF90_INQUIRE_VARIABLE
!
!------------------------------------------------------------------------------
      integer rtcode
      integer begDate, begTime, incSecs, timeIndex1, timeIndex2
      integer secs, secs1, secs2, nymd1, nymd2, nhms1, nhms2
      integer i, j, k
      integer im, jm, km
      real    alpha, amiss
      real, pointer ::  field2(:,:,:) => null() ! workspace for interpolation
      rtcode = 0
!     find the right variable obj.
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
      im = cfio%varObjs(i)%grid%im
      jm = cfio%varObjs(i)%grid%jm
      km = cfio%varObjs(i)%grid%km
      if (km .lt. 1) km = 1
      if ( .not. associated(field) ) allocate(field(im,jm,km))
!     Get beginning time & date.  Calculate offset seconds from start.
!     ----------------------------------------------------------------
      call GetBegDateTime ( cfio%fid, begDate, begTime, incSecs, rtcode )
      if (err("GetVar: could not determine begin_date/begin_time",rtcode,-44)&
         .NE. 0) go to 999
      secs = DiffDate (begDate, begTime, date, curTime)
!      if (date .LT. begDate .OR. (begDate .EQ. date .AND.  &
!         curTime .LT. begTime) .or. secs .LT. 0) then
!         rc = -7
!         return
!      endif
!     Determine brackting times
!     -------------------------
      if ( secs >= 0 ) then
         timeIndex1 = secs/incSecs + 1
      else
         timeIndex1 = secs/incSecs
      end if
      timeIndex2 = timeIndex1 + 1
      secs1 = (timeIndex1-1) * incSecs
      secs2 = (timeIndex2-1) * incSecs
      call GetDate ( begDate, begTime, secs1, nymd1, nhms1, rtcode )
      call GetDate ( begDate, begTime, secs2, nymd2, nhms2, rtcode )
!     Read grids at first time with GetVar()
!     --------------------------------------
      call ESMF_CFIOSdfVarRead(cfio, vName, field, date=nymd1, curtime=nhms1,  rc=rtcode)
      if ( rtcode .ne. 0 ) goto 999
      if ( secs1 .eq. secs ) goto 999   ! no interpolation needed
      allocate(field2(im,jm,km))
!     Read grids at second time with GetVar()
!     ---------------------------------------
      call ESMF_CFIOSdfVarRead(cfio, vName, field2, date=nymd2, curtime=nhms2, rc=rtcode)
      if ( rtcode .ne. 0 ) then
         if ( present(cfio2) )     &
            call ESMF_CFIOSdfVarRead(cfio2, vName, field2, &
                                  date=nymd2, curtime=nhms2, rc=rtcode)
         if ( rtcode .ne. 0 ) return
      end if
!     Get missing value
!     -----------------
      amiss = CFIO_GetMissing ( cfio%fid, rtcode )
      if ( rtcode .ne. 0 ) goto 999
!     Do interpolation
!     ----------------
      alpha = real(secs - secs1)/real(secs2 - secs1)
!ams  print *, ' nymd = ', nymd1, nymd2
!ams  print *, ' nhms = ', nhms1, nhms2
!ams  print *, 'alpha = ', alpha
      do k = 1, km
         do j = 1, jm
            do i = 1, im
               if ( abs(field(i,j,k)-amiss) .gt. 0.001 .and.   &
                    abs(field2(i,j,k)-amiss) .gt. 0.001 ) then
                  field(i,j,k) = field(i,j,k)        &
                             + alpha * (field2(i,j,k) - field(i,j,k))
               else
                  field(i,j,k) = amiss
               end if
            end do
         end do
      end do
      rtcode = 0
!     All done
!     --------
999   continue
      if ( associated(field2) ) deallocate(field2)
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOSdfVarReadT3D__
Call graph
esmf_cfiosdfvarreadt3d__ calls esmf_cfiosdfvarread, getdate, cfio_getmissing, diffdate, err, getbegdatetime
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
getdate calls getdateint4, getdateint8
cfio_getmissing calls err, nf90_get_att, nf90_inquire, nf90_inquire_attribute, nf90_inquire_variable
diffdate calls cfio_parseinttime, julday
getbegdatetime calls getdate, err, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_inquire, nf90_inquire_dimension, nf90_inquire_variable, cfio_parseinttime, identifydim, parsetimeunits
esmf_cfiosdfvarread1d_ calls cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, strtoint
esmf_cfiosdfvarread2d_ calls err, cfio_getvar, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, strtoint
esmf_cfiosdfvarread3d_ calls err, cfio_getvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, strtoint
getdateint4 calls getdateint8
getdateint8 calls cfio_parseinttime, julday, caldat
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt3d__, esmf_cfiosdfvarreadt3d_
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__