ESMFL_StateGetPtrToDataR8_3 – MAPL
ESMFL_StateGetPtrToDataR8_3 Subroutine
68 statements
Source File
private subroutine ESMFL_StateGetPtrToDataR8_3(STATE, PTR, NAME, alloc, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: alloc
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
Calls
Called by
Call graph
esmfl_stategetptrtodatar8_3 calls esmf_fieldget, esmf_stateget, mapl_allocatecoupling, mapl_return, mapl_verify
mapl_allocatecoupling calls mapl_allocatecoupling, esmf_fieldget, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_fieldalloccommit
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_fieldalloccommit calls mapl_fieldalloccommit
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar8_3
comparestate calls esmfl_stategetpointertodata
copystate calls esmfl_stategetpointertodata
evaluate_box_mask calls esmfl_stategetpointertodata
evaluate_region_mask calls esmfl_stategetpointertodata
evaluate_zone_mask calls esmfl_stategetpointertodata
fillstate calls esmfl_stategetpointertodata
forceallocation calls esmfl_stategetpointertodata
initialize_ calls esmfl_stategetpointertodata, forceallocation
initialize calls esmfl_stategetpointertodata
mapl_extdataevaluatemask calls esmfl_stategetpointertodata
mapl_readforcingx calls esmfl_stategetpointertodata
run_ calls esmfl_stategetpointertodata, comparestate, copystate, fillstate, set_constant_field, calcderivedfield
run calls esmfl_stategetpointertodata
set_constant_field calls esmfl_stategetpointertodata
calcderivedfield calls mapl_extdataevaluatemask
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
evaluate_derived_field calls evaluate_mask