ESMFL_FieldGetPtrToDataR4_2 – MAPL
ESMFL_FieldGetPtrToDataR4_2 Subroutine
18 statements
Source File
private subroutine ESMFL_FieldGetPtrToDataR4_2(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R4), pointer :: PTR(:,:)
integer, intent(out), optional :: RC
Calls
Called by
Call graph
esmfl_fieldgetptrtodatar4_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar4_2
regridscalar calls esmfl_fieldgetpointertodata
regridvector calls esmfl_fieldgetpointertodata
swap_undef_value calls esmfl_fieldgetpointertodata
bundlepost calls regridscalar, regridvector
interp_accumulate_fields calls regridscalar, regridvector
process_data_from_file calls regridscalar, regridvector, swap_undef_value
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls bundlepost
write_to_file calls bundlepost