ESMF_CFIOVarWrite2D_ – MAPL
ESMF_CFIOVarWrite2D_ Subroutine
39 statements
Source File
private subroutine ESMF_CFIOVarWrite2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
ESMF_CFIOVarWrite2D_ – Write a variable to a output file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
string expression for date and time
logical, intent(in), optional :: doComp
do compression
logical, intent(in), optional :: doChunk
do chunk compression
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -15 data outside of valid range rc = -16 data outside of packing range rc = -17 data outside of pack and valid range rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -45 error from NF90_PUT_VAR rc = -46 error from NF90_GET_VAR rc = -52 error from NF90_INQUIRE_VARIABLE rc = -53 error from NF90_GET_ATT rc = -54 Format is not known
Calls
Called by
Source Code
      subroutine ESMF_CFIOVarWrite2D_(cfio, vName, field, date, curTime, &
                                      kbeg, kount, timeString, doComp,   &
                                      doChunk, rc)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio      !! a CFIO obj
      character(len=*), intent(in) :: vName       !! Variable name
      real, intent(in) :: field(:,:)            !! array contains data
      integer, intent(in), OPTIONAL :: date       !! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime    !! hhmmss
      integer, intent(in), OPTIONAL :: kbeg       !! first level to write
      integer, intent(in), OPTIONAL :: kount      !! number of levels to write
      character(len=*), intent(in), OPTIONAL :: timeString !! string expression for date and time
      logical, intent(in), OPTIONAL :: doComp     !! do compression
      logical, intent(in), OPTIONAL :: doChunk    !! do chunk compression
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
                         !!  rc = -2  time is inconsistent with increment
                         !!  rc = -3  number of levels is incompatible with file
                         !!  rc = -4  im is incompatible with file
                         !!  rc = -5  jm is incompatible with file
                         !!  rc = -6  time must fall on a minute boundary
                         !!  rc = -7  error in diffdate
                         !!  rc = -12  error determining default precision
                         !!  rc = -13  error determining variable type
                         !!  rc = -15  data outside of valid range
                         !!  rc = -16  data outside of packing range
                         !!  rc = -17  data outside of pack and valid range
                         !!  rc = -38  error from NF90_PUT_VAR (dimension variable)
                         !!  rc = -40  error from NF90_INQ_VARID
                         !!  rc = -41  error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon)
                         !!  rc = -42  error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev)
                         !!  rc = -43  error from NF90_INQ_VARID (time variable)
                         !!  rc = -44  error from NF90_GET_ATT (time attribute)
                         !!  rc = -45  error from NF90_PUT_VAR
                         !!  rc = -46  error from NF90_GET_VAR
                         !!  rc = -52  error from NF90_INQUIRE_VARIABLE
                         !!  rc = -53  error from NF90_GET_ATT
                         !!  rc = -54  Format is not known
!
!------------------------------------------------------------------------------
!------------------------------------------------------------------------------
      integer :: rtcode
      integer :: myDate, myCurTime
      character(len=16) :: format
#if defined(HDFEOS)
      logical :: do_comp, do_chunk
#endif
#if defined(HDFEOS)
      do_chunk = .false.
      do_comp = .false.
      if ( present(doComp) ) do_comp = doComp
      if ( present(doChunk) ) do_chunk = doChunk
#endif
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      call ESMF_CFIOGet(cfio, format=format, rc=rtcode)
      if ( rtcode .ne. 0 ) print *, "problem in ESMF_CFIOWrite in calling ESMF_CFIOGet"
      select case (format)
      case ('SDF')
         if (present(kbeg) .and. present(kount)) then
           call ESMF_CFIOSdfVarWrite(cfio, vName, field, date=myDate,  &
                        curTime=myCurTime, kbeg=kbeg, kount=kount,     &
                        rc=rtcode)
         else
           call ESMF_CFIOSdfVarWrite(cfio, vName, field, date=myDate,  &
                        curTime=myCurTime, rc=rtcode)
         end if
         if ( rtcode .ne. 0 ) print *, "problem in ESMF_CFIOVarWrite"
         if (present(rc)) rc = rtcode
         return
#if defined(HDFEOS)
      case ('EOS')
         if (present(kbeg) .and. present(kount)) then
           call ESMF_CFIOEosVarWrite(cfio, vName, field, date=myDate,  &
                        curTime=myCurTime, kbeg=kbeg, kount=kount,     &
                        doComp = do_comp, doChunk = do_chunk,           &
                        rc=rtcode)
         else
           call ESMF_CFIOEosVarWrite(cfio, vName, field, date=myDate,  &
                        doComp = do_comp, doChunk = do_chunk,           &
                        curTime=myCurTime, rc=rtcode)
         end if
         if ( rtcode .ne. 0 ) print *, "problem in ESMF_CFIOEosVarWrite"
         if (present(rc)) rc = rtcode
         return
#endif
      end select
         print *, "CFIO%FORMAT is not known"
         if (present(rc)) rc = -54
         return
#if !defined(HDFEOS)
         associate(q => dochunk); end associate
         associate(q => docomp); end associate
#endif
     end subroutine ESMF_CFIOVarWrite2D_
Call graph
esmf_cfiovarwrite2d_ calls esmf_cfiosdfvarwrite, esmf_cfioget, strtoint
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfioget calls err
esmf_cfiosdfvarwrite1d_ calls strtoint, err, cfio_sputvar, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, writebnds
esmf_cfiosdfvarwrite2d_ calls strtoint, err, cfio_putvar, cfio_sputvar, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, writebnds
esmf_cfiosdfvarwrite3d_ calls strtoint, err, cfio_putvar, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, writebnds
esmf_cfiovarwrite calls esmf_cfiovarwrite2d_
mapl_cfiowritebundlewrite calls esmf_cfiovarwrite
test calls esmf_cfiovarwrite
mapl_cfiowritebundle calls mapl_cfiowritebundlewrite
esmf_iowrite calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle
mapl_cfiowritestate calls mapl_cfiowritebundle