ESMF_time_to_two_integer – MAPL
ESMF_time_to_two_integer Subroutine
16 statements
Source File
public subroutine ESMF_time_to_two_integer(time, itime, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: time
integer, intent(out) :: itime(2)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine ESMF_time_to_two_integer(time, itime, rc)
    type(ESMF_Time), intent(in) ::   time
    integer, intent(out) :: itime(2)
    integer, intent(out), optional :: rc
    integer :: i1, i2
    integer :: yy, mm, dd, h, m, s
    integer :: status
    call ESMF_TimeGet(time, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
    i2=h*10000 + m*100 + s
    i1=yy*10000 + mm*100 + dd
    itime(1)=i1
    itime(2)=i2
    _RETURN(_SUCCESS)
  end subroutine ESMF_time_to_two_integer
Call graph
esmf_time_to_two_integer calls ESMF_TimeGet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_filename_from_template calls esmf_time_to_two_integer
get_filename_from_template_use_index calls esmf_time_to_two_integer
create_grid calls get_filename_from_template_use_index
find_m_files_for_currtime calls get_filename_from_template_use_index
initialize_from_config_with_prefix calls find_m_files_for_currtime