ESMF_CFIOSdfVarRead1D_ – MAPL
ESMF_CFIOSdfVarRead1D_ Subroutine
46 statements
Source File
private subroutine ESMF_CFIOSdfVarRead1D_(cfio, vName, field, date, curTime, xBeg, xCount, timeString, rc)
ESMF_CFIOSdfVarRead1D_ – Read a variable from an existing file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: xBeg
first point for lon
integer, intent(in), optional :: xCount
number of points to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Calls
Called by
Source Code
      subroutine ESMF_CFIOSdfVarRead1D_(cfio, vName, field, date, curTime, &
                                     xBeg, xCount, timestring, rc)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio         !! a CFIO obj
      character(len=*), intent(in) :: vName       !! variable name
      integer, intent(in), OPTIONAL :: date       !! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime    !! hhmmss
      integer, intent(in), OPTIONAL :: xBeg       !! first point for lon
      integer, intent(in), OPTIONAL :: xCount     !! number of points to read
      character(len=*), intent(in), OPTIONAL :: timeString !! string expression for date and time
!
! !OUTPUT PARAMETERS:
!
      real, pointer :: field(:)             !! array contains data
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
!------------------------------------------------------------------------------
      integer :: i, rtcode
      integer :: myXbeg, myXount
      integer :: myDate, myCurTime
      real, pointer :: tmp(:)          ! array contains data
      character(len=MLEN) :: fNameTmp     ! file name
      fNameTmp = ''
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      if (len(trim(cfio%fNameTmplt)) .gt. 1) then
         call strTemplate_(fNameTmp,cfio%fNameTmplt,xid=cfio%expid,nymd=MYdate, &
                           nhms=MYcurTime, stat=rtcode)
         if (trim(fNameTmp) .ne. trim(cfio%fName)) then
            call ESMF_CFIOSdfFileClose(cfio)
            cfio%fName = fNameTmp
!            call ESMF_CFIOSet(cfio, fName=cfio%fName)
            if (len(trim(cfio%expid)) .gt. 0) then
               call ESMF_CFIOSdfFileOpen(cfio, 1, expid=cfio%expid, cyclic=cfio%isCyclic)
            else
               call ESMF_CFIOSdfFileOpen(cfio, 1, cyclic=cfio%isCyclic)
            end if
         end if
      end if
!     make sure user provides the right variable name
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
      myXbeg = 1
      myXount = cfio%varObjs(i)%grid%im
      if (present(xBeg)) myXbeg = xBeg
      if (present(xCount)) myXount = xCount
!     read 1D variable
      allocate(tmp(cfio%varObjs(i)%grid%im), stat=rtcode)
      call CFIO_SGetVar(cfio%fid,vName,MYdate,MYcurTime,               &
               cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,   &
               0,1, cfio%tSteps, tmp, cfio%isCyclic, rtcode )
      do i = 1, myXount
         field(i) = tmp(myXbeg+i-1)
      end do
      deallocate(tmp)
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOSdfVarRead1D_
Call graph
esmf_cfiosdfvarread1d_ calls cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, strtoint
cfio_sgetvar calls nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_inquire, nf90_inquire_dimension, nf90_inquire_variable, diffdate, err, getdatetimevec, identifydim
esmf_cfiosdffileclose calls cfio_close
esmf_cfiosdffileopen calls strtemplate_, nf90_get_att, nf90_get_var, nf90_inq_attname, nf90_inq_varid, nf90_inquire, nf90_inquire_attribute, nf90_inquire_dimension, nf90_inquire_variable, cfio_attinquire, cfio_diminquire, cfio_getattnames, cfio_getcharatt, cfio_getintatt, cfio_getrealatt, cfio_open, err, esmf_cfiovarinfocreate, getbegdatetime, identifydim
strtemplate_ calls die, gx_
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_
esmf_cfiosdfvarreadt2d__ calls esmf_cfiosdfvarread
esmf_cfiosdfvarreadt3d__ calls esmf_cfiosdfvarread
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread
esmf_cfiovarread2d_ calls esmf_cfiosdfvarread
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d__, esmf_cfiosdfvarreadt2d_, esmf_cfiosdfvarreadt3d_
esmf_cfiovarread calls esmf_cfiovarread1d_, esmf_cfiovarread2d_, esmf_cfiovarread3d_
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__
esmf_cfiovarreadt2d__ calls esmf_cfiovarread
esmf_cfiovarreadt3d__ calls esmf_cfiovarread
mapl_cfioreadbundle calls esmf_cfiovarread
test calls esmf_cfiovarread