ESMFL_BundleGetPointerByIndex3 – MAPL
ESMFL_BundleGetPointerByIndex3 Subroutine
21 statements
Source File
private subroutine ESMFL_BundleGetPointerByIndex3(BUNDLE, INDEX, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
integer, intent(in) :: INDEX
real, pointer :: PTR(:,:,:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine ESMFL_BundleGetPointerByIndex3(BUNDLE,INDEX,PTR,RC)
     type(ESMF_FieldBundle), intent(INOUT) :: BUNDLE !ALT: intent(in)
     integer,           intent(IN) :: INDEX
     real, pointer                 :: PTR(:,:,:)
     integer, optional, intent(OUT):: RC
     type(ESMF_FIELD)              :: FIELD
     type(ESMF_FieldStatus_Flag)   :: fieldStatus
     integer                       :: status
! ESMF 5 reorders items, be careful!
! ==================================
     call ESMF_FieldBundleGet (BUNDLE, INDEX, FIELD, RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_FieldGet(field, status=fieldStatus, rc=status)
     _VERIFY(STATUS)
     if (fieldStatus == ESMF_FIELDSTATUS_COMPLETE) then
        call ESMF_FieldGet(field, 0, Ptr, rc=status)
        _VERIFY(STATUS)
     else
        NULLIFY(ptr)
     end if
     _RETURN(ESMF_SUCCESS)
   end subroutine ESMFL_BundleGetPointerByIndex3
Call graph
esmfl_bundlegetpointerbyindex3 calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
esmfl_bundlegetpointertodata calls esmfl_bundlegetpointerbyindex3
mapl_extdatainterpfield calls esmfl_bundlegetpointertodata
run_ calls esmfl_bundlegetpointertodata, mapl_extdatainterpfield