ESMF_CFIOCreate – MAPL
ESMF_CFIOCreate Function
38 statements
Source File
public function ESMF_CFIOCreate(cfioObjName, rc)
ESMF_CFIOCreate – ESMF_CFIO object constructor
Create a CFIO object and initialize vars. The required global metadata title, institution, source, history, references, and comment are set to unknown.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: cfioObjName
integer, intent(out), optional :: rc
Return Value type(ESMF_CFIO)
Called by
Source Code
      type (ESMF_CFIO) function ESMF_CFIOCreate (cfioObjName, rc)
!
! !INPUT PARAMETERS:
!
      character(len=*), intent(in), OPTIONAL :: cfioObjName  ! object name
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      ! Error return code:
                                                ! 0   all is well
!
!------------------------------------------------------------------------------
      type(ESMF_CFIO) :: cfio                   ! a CFIO object
      integer :: rtcode
      if ( present(cfioObjName) ) then
         cfio%cfioObjName = cfioObjName
      else
         cfio%cfioObjName = 'CFIO'
      end if
! Initializing variables
      cfio%nAttChar = 0
      cfio%nAttReal = 0
      cfio%nAttInt = 0
      cfio%fName = 'unknown'
      cfio%title = 'unknown'
      cfio%source = 'unknown'
      cfio%contact = 'unknown'
      cfio%history = 'unknown'
      cfio%convention = 'unknown'
      cfio%institution = 'unknown'
      cfio%references = 'unknown'
      cfio%comment = 'unknown'
      cfio%prec = 0
      cfio%date = -999
      cfio%begTime = 0
      cfio%timeInc = 60000
      cfio%mVars = 1
      cfio%mGrids = 1
      cfio%fNameTmplt = ''
      cfio%isOpen = .false.
      cfio%isCyclic = .false.
      cfio%isGridSet = .false.
      cfio%format = 'SDF'
      cfio%expid = ''
!      allocate(cfio%iList, cfio%rList, cfio%cList)
!      nullify(cfio%iList)
!      nullify(cfio%rList)
!      nullify(cfio%cList)
      rtcode = 0
      if ( present(rc) ) rc = rtcode
      ESMF_CFIOCreate = cfio
      end function ESMF_CFIOCreate
Call graph
find calls esmf_cfiocreate
mapl_cfiocreatefrombundle calls esmf_cfiocreate
mapl_cfioreadbundle calls esmf_cfiocreate, find
test calls esmf_cfiocreate
esmf_iocreate calls mapl_cfiocreatefrombundle
esmf_ioread calls mapl_cfioreadbundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfiocreatefromfile calls find
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundleread calls find
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls find
mapl_cfioreadstate calls mapl_cfioreadbundle