ESMFL_ClockSet – MAPL
ESMFL_ClockSet Subroutine
44 statements
Source File
private subroutine ESMFL_ClockSet(clock, currTime, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock) :: clock
type(ESMF_Time), intent(in) :: currTime
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine ESMFL_ClockSet(clock, currTime, rc)
    ! Args
    type (ESMF_Clock)                :: clock
    type (ESMF_Time),  intent(IN   ) :: currTime
    integer, optional, intent(  OUT) :: rc
    ! ErrLog vars
    integer                                :: status
    ! Local Vars
    type(ESMF_Time)                        :: targetTime
    type(ESMF_Time)                        :: cTime
    type(ESMF_TimeInterval)                :: zero
    type(ESMF_TimeInterval)                :: delt
    type(ESMF_Time)                        :: ringTime
    type(ESMF_TimeInterval)                :: ringInterval
    type(ESMF_Alarm), allocatable          :: AlarmList(:)
    logical                                :: ringing
    integer                                :: I
    integer                                :: nalarms
    targetTime = currTime
    ! get the CurrentTime from the clock
    call ESMF_ClockGet(clock, alarmCount = nalarms, currTime=cTime, rc=status)
    _VERIFY(STATUS)
    delt = targetTime - cTime
    call ESMF_TimeIntervalSet(zero, rc=status)
    _VERIFY(STATUS)
    ! Get the list of current alarms in the clock
    allocate (alarmList(nalarms), stat = status)
    _VERIFY(STATUS)
    call ESMF_ClockGetAlarmList(clock, alarmListFlag=ESMF_ALARMLIST_ALL, &
         alarmList=alarmList, alarmCount = nalarms, rc=status)
    _VERIFY(STATUS)
    ! Loop over all alarms
    DO I = 1, nalarms
       call ESMF_AlarmGet(alarmList(I), ringTime=ringTime, ringInterval=ringInterval, &
            ringing=ringing, rc=status)
       _VERIFY(STATUS)
       ! skip alarms with zero ringing interval
       if (ringInterval == zero) cycle
       _ASSERT(mod(delt,ringInterval) == zero, 'Time-shift should be a multiple of ringing interval.')
       ringTime=ringTime + delt
       call ESMF_AlarmSet(alarmList(I), ringTime=ringTime, ringing=ringing, rc=status)
       _VERIFY(STATUS)
    END DO
    ! Protection in case we reset the clock outside of StopTime
    call ESMF_ClockStopTimeDisable(clock, rc=status)
    _VERIFY(STATUS)
    call ESMF_ClockSet(clock, currTime=targetTime, rc=status)
    _VERIFY(STATUS)
    ! We do not need the protection anymore
    call ESMF_ClockStopTimeEnable(clock, rc=status)
    _VERIFY(STATUS)
    ! clean-up
    deallocate(alarmList)
    _RETURN(ESMF_SUCCESS)
  end subroutine ESMFL_ClockSet
Call graph
esmfl_clockset calls ESMF_AlarmGet, ESMF_AlarmSet, ESMF_ClockGet, ESMF_ClockGetAlarmList, ESMF_ClockSet, ESMF_ClockStopTimeDisable, ESMF_ClockStopTimeEnable, ESMF_TimeIntervalSet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
perpetual_clock calls esmfl_clockset
initialize_gc calls perpetual_clock
step calls perpetual_clock
run_mapl_gridcomp calls step
step_model calls step
model_advance calls step_model
run_gc calls run_mapl_gridcomp