ESMF_CFIOGridDestroy – MAPL
ESMF_CFIOGridDestroy Subroutine
14 statements
Source File
public subroutine ESMF_CFIOGridDestroy(grid, rc)
ESMF_CFIOGridDestroy – destructor for a CFIO grid object
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIOGrid), intent(inout) :: grid
CFIOGrid object
integer, intent(out), optional :: rc
Error return code:
0 all is well
Called by
Source Code
      subroutine ESMF_CFIOGridDestroy (grid, rc)
!
! !INPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
! !INPUT/OUTPUT PARAMETERS:
!
      type(ESMF_CFIOGrid), intent(inout) :: grid !! CFIOGrid object
!
!------------------------------------------------------------------------------
      integer :: rtcode = 0
      if (.not. grid%twoDimLat) then
         if ( associated(grid%lon) ) deallocate(grid%lon, stat=rtcode)
         if ( associated(grid%lat) ) deallocate(grid%lat, stat=rtcode)
      end if
      if ( associated(grid%lev) ) deallocate(grid%lev, stat=rtcode)
      if ( associated(grid%ak) ) deallocate(grid%ak, stat=rtcode)
      if ( associated(grid%bk) ) deallocate(grid%bk, stat=rtcode)
      if ( associated(grid%sigma) ) deallocate(grid%sigma, stat=rtcode)
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOGridDestroy
Call graph
esmf_cfiodestroy calls esmf_cfiogriddestroy, esmf_cfiovarinfodestroy
esmf_cfiovarinfodestroy calls esmf_cfiogriddestroy
find calls esmf_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy, find
unfind calls esmf_cfiodestroy
esmf_iodestroy calls mapl_cfiodestroy
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
finalize calls mapl_cfiodestroy
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls find, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls esmf_iodestroy, esmf_ioread, mapl_cfioread