ESMFL_FCOLLECT_R8 – MAPL
ESMFL_FCOLLECT_R8 Subroutine
56 statements
Source File
private subroutine ESMFL_FCOLLECT_R8(GRID, FULLINPUT, INPUT, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: GRID
real(kind=ESMF_KIND_R8), intent(inout) :: FULLINPUT(:)
real(kind=ESMF_KIND_R8), intent(in) :: INPUT(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
 subroutine ESMFL_FCOLLECT_R8(GRID, FULLINPUT, INPUT, RC )
   type(ESMF_GRID), intent(IN   )     :: GRID
   real(kind= ESMF_KIND_R8), intent(INOUT) :: FULLINPUT(:)
   real(kind= ESMF_KIND_R8), intent(IN   ) :: INPUT(:)
   integer, optional,   intent(  OUT) :: rc
! local vars
   integer          :: status
   type (ESMF_DistGrid)                  :: distGrid
   type(ESMF_DELayout)                   :: LAYOUT
   type (ESMF_VM)                        :: vm
   integer,               allocatable    :: AL(:,:)
   integer,               allocatable    :: AU(:,:)
   integer, pointer, dimension(:)            :: recvcounts, displs
   integer                                       :: nDEs
   integer                                       :: sendcount
   integer                                       :: I, J, de, deId
   integer                                       :: I1, IN
   integer                                       :: gridRank
   call ESMF_GridGet(GRID, dimCount=gridRank, rc=STATUS)
   _VERIFY(STATUS)
   call ESMF_GridGet    (GRID,   distGrid=distGrid, rc=STATUS)
   _VERIFY(STATUS)
   call ESMF_DistGridGet(distGRID, delayout=layout, rc=STATUS)
   _VERIFY(STATUS)
   call ESMF_DELayoutGet(layout, vm=vm, rc=status)
   _VERIFY(STATUS)
   call ESMF_VmGet(vm, localPet=deId, petCount=nDEs, rc=status)
   _VERIFY(STATUS)
   allocate (AL(gridRank,0:nDEs-1),  stat=status)
   _VERIFY(STATUS)
   allocate (AU(gridRank,0:nDEs-1),  stat=status)
   _VERIFY(STATUS)
   call MAPL_DistGridGet(distgrid, &
        minIndex=AL, maxIndex=AU, rc=status)
   _VERIFY(STATUS)
   allocate (recvcounts(nDEs), displs(0:nDEs), stat=status)
   _VERIFY(STATUS)
   displs(0) = 0
   do I = 1,nDEs
      J = I - 1
      de = J
      I1 = AL(1,J)
      IN = AU(1,J)
      recvcounts(I) = (IN - I1 + 1)
      if (de == deId) then
         sendcount = recvcounts(I)
      endif
      displs(I) = displs(J) + recvcounts(I)
   enddo
   _ASSERT(sendcount == size(input), 'inconsistent sendcount')
   _ASSERT(sum(recvcounts) == size(fullinput), 'inconsistent recvcount')
   call MAPL_CommsAllGatherV(layout, input, sendcount, &
                             fullinput, recvcounts, displs, rc=status)
   _VERIFY(STATUS)
   deallocate(recvcounts, displs, AU, AL, stat=status)
   _VERIFY(STATUS)
   _RETURN(ESMF_SUCCESS)
 end subroutine ESMFL_FCOLLECT_R8
Call graph
esmfl_fcollect_r8 calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_assert, mapl_commsallgatherv, mapl_distgridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_commsallgatherv calls mapl_commsallgatherv_i4_1, mapl_commsallgatherv_r4_1, mapl_commsallgatherv_r8_1
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_commsallgatherv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_allgatherv
mapl_commsallgatherv_r4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_allgatherv
mapl_commsallgatherv_r8_1 calls ESMF_DELayoutGet, ESMF_VMGet, mapl_return, mapl_verify, mpi_allgatherv
mapl_throw_exception calls initialize
esmfl_fcollect calls esmfl_fcollect_r8
mapl_locstreamcreatexform calls esmfl_fcollect
mapl_locstreamtransformt2t calls esmfl_fcollect
mapl_locstreamtransform calls mapl_locstreamtransformt2t, mapl_locstreamtransformt2tr4r8, mapl_locstreamtransformt2tr8r4
initialize calls mapl_locstreamcreatexform
mapl_locstreamtransformt2tr4r8 calls mapl_locstreamtransformt2t
mapl_locstreamtransformt2tr8r4 calls mapl_locstreamtransformt2t
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform