ESMFL_FieldGetPtrToDataR8_3 – MAPL
ESMFL_FieldGetPtrToDataR8_3 Subroutine
18 statements
Source File
private subroutine ESMFL_FieldGetPtrToDataR8_3(Field, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
real(kind=ESMF_KIND_R8), pointer :: PTR(:,:,:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
esmfl_fieldgetptrtodatar8_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar8_3
regridscalar calls esmfl_fieldgetpointertodata
regridvector calls esmfl_fieldgetpointertodata
swap_undef_value calls esmfl_fieldgetpointertodata
bundlepost calls regridscalar, regridvector
process_data_from_file calls regridscalar, regridvector, swap_undef_value