ESMF_CFIOVarReadT3D__ – MAPL
ESMF_CFIOVarReadT3D__ Subroutine
90 statements
Source File
private subroutine ESMF_CFIOVarReadT3D__(cfio, vName, date, curTime, field, kbeg, kount, rc, cfio2)
ESMF_CFIOVarReadT3D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
integer, intent(in) :: date
yyyymmdd
integer, intent(in) :: curTime
hhmmss
real, pointer :: field(:,:,:)
array contains data
integer, intent(in), optional :: kbeg
first level to read
integer, intent(in), optional :: kount
number of levels to read
integer, intent(out), optional :: rc
Error return code: 0 all is well rc = -2 time is inconsistent with increment rc = -3 number of levels is incompatible with file rc = -4 im is incompatible with file rc = -5 jm is incompatible with file rc = -6 time must fall on a minute boundary rc = -7 error in diffdate rc = -12 error determining default precision rc = -13 error determining variable type rc = -19 unable to identify coordinate variable rc = -20 unable to find variable rc = -38 error from NF90_PUT_VAR (dimension variable) rc = -40 error from NF90_INQ_VARID rc = -41 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon) rc = -42 error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev) rc = -43 error from NF90_INQ_VARID (time variable) rc = -44 error from NF90_GET_ATT (time attribute) rc = -46 error from NF90_GET_VAR rc = -48 error from NF90_INQUIRE rc = -52 error from NF90_INQUIRE_VARIABLE
type(ESMF_CFIO), intent(inout), optional :: cfio2
second CFIO obj
Calls
Called by
Contents
Source Code
ESMF_CFIOVarReadT3D__
Source Code
      subroutine ESMF_CFIOVarReadT3D__(cfio, vName, date, curTime, field, &
                                       kbeg, kount, rc, cfio2)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio      !! a CFIO obj
      character(len=*), intent(in) :: vName       !! variable name
      integer, intent(in) :: date                 !! yyyymmdd
      integer, intent(in) :: curTime              !! hhmmss
      integer, intent(in), OPTIONAL :: kbeg       !! first level to read
      integer, intent(in), OPTIONAL :: kount      !! number of levels to read
      type(ESMF_CFIO), intent(inOut), OPTIONAL :: cfio2  !! second CFIO obj
!
! !OUTPUT PARAMETERS:
!
      real, pointer :: field(:,:,:)             !! array contains data
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
                         !!  rc = -2  time is inconsistent with increment
                         !!  rc = -3  number of levels is incompatible with file
                         !!  rc = -4  im is incompatible with file
                         !!  rc = -5  jm is incompatible with file
                         !!  rc = -6  time must fall on a minute boundary
                         !!  rc = -7  error in diffdate
                         !!  rc = -12  error determining default precision
                         !!  rc = -13  error determining variable type
                         !!  rc = -19  unable to identify coordinate variable
                         !!  rc = -20  unable to find variable
                         !!  rc = -38  error from NF90_PUT_VAR (dimension variable)
                         !!  rc = -40  error from NF90_INQ_VARID
                         !!  rc = -41  error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon)
                         !!  rc = -42  error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev)
                         !!  rc = -43  error from NF90_INQ_VARID (time variable)
                         !!  rc = -44  error from NF90_GET_ATT (time attribute)
                         !!  rc = -46  error from NF90_GET_VAR
                         !!  rc = -48  error from NF90_INQUIRE
                         !!  rc = -52  error from NF90_INQUIRE_VARIABLE
!
!------------------------------------------------------------------------------
      integer rtcode
      integer begDate, begTime, incSecs, timeIndex1, timeIndex2
      integer secs, secs1, secs2, nymd1, nymd2, nhms1, nhms2
      integer i, j, k
      integer im, jm, km
      integer :: hour, min, sec
      logical ialloc,foundvar
      real    alpha, amiss
      real, pointer ::  field2(:,:,:) => null() ! workspace for interpolation
      rtcode = 0
!     find the right variable obj.
      foundvar=.false.
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) then
            foundvar=.true.
            exit
         endif
      end do
      if (.not.foundvar) then
         rc=-20
         return
      endif
      im = cfio%varObjs(i)%grid%im
      jm = cfio%varObjs(i)%grid%jm
      km = cfio%varObjs(i)%grid%km
      if (km .lt. 1) km = 1
      ialloc=.false.
      if ( .not. associated(field) ) then
         allocate(field(im,jm,km))
         ialloc=.true.
      endif
!     Get beginning time & date.  Calculate offset seconds from start.
!     ----------------------------------------------------------------
      begDate = cfio%date
      begTime = cfio%begTime
      call CFIO_parseIntTime ( cfio%timeInc, hour, min, sec )
      incSecs = sec + 60 * ( min + 60 * hour )
      secs = DiffDate (begDate, begTime, date, curTime)
!     Determine brackting times
!     -------------------------
      if ( secs >= 0 ) then
         timeIndex1 = secs/incSecs + 1
      else
         timeIndex1 = secs/incSecs
      end if
      timeIndex2 = timeIndex1 + 1
      secs1 = (timeIndex1-1) * incSecs
      secs2 = (timeIndex2-1) * incSecs
      call GetDate ( begDate, begTime, secs1, nymd1, nhms1, rtcode )
      call GetDate ( begDate, begTime, secs2, nymd2, nhms2, rtcode )
!     Read grids at first time with GetVar()
!     --------------------------------------
      call ESMF_CFIOVarRead(cfio, vName, field, date=nymd1, curtime=nhms1,  kbeg=kbeg, kount=kount, rc=rtcode)
      if ( rtcode .ne. 0 .and. present(cfio2) ) then
         call ESMF_CFIOVarRead(cfio2, vName, field, date=nymd1, curtime=nhms1, kbeg=kbeg, kount=kount, rc=rtcode)
      end if
      if ( rtcode .ne. 0 ) goto 999
      if ( secs1 .eq. secs ) goto 999   ! no interpolation needed
      allocate(field2(size(field,1),size(field,2),size(field,3)))
!     Read grids at second time with GetVar()
!     ---------------------------------------
      call ESMF_CFIOVarRead(cfio, vName, field2, date=nymd2, curtime=nhms2, kbeg=kbeg, kount=kount, rc=rtcode)
      if ( rtcode .ne. 0 ) then
         if ( present(cfio2) )     &
            call ESMF_CFIOVarRead(cfio2, vName, field2, &
                                  date=nymd2, curtime=nhms2, kbeg=kbeg, kount=kount, rc=rtcode)
         if ( rtcode .ne. 0 ) then
            if(ialloc) deallocate(field)
            deallocate(field2)
            return
         endif
      end if
!     Get missing value
!     -----------------
      amiss = cfio%varObjs(1)%amiss
!     Do interpolation
!     ----------------
      alpha = real(secs - secs1)/real(secs2 - secs1)
      do k = 1, size(field,3)!km
         do j = 1, size(field,2)!jm
            do i = 1, size(field,1)!im
               if ( abs(field(i,j,k)-amiss) .gt. 0.001 .and.   &
                    abs(field2(i,j,k)-amiss) .gt. 0.001 ) then
                  field(i,j,k) = field(i,j,k)        &
                             + alpha * (field2(i,j,k) - field(i,j,k))
               else
                  field(i,j,k) = amiss
               end if
            end do
         end do
      end do
      if ( associated(field2) ) deallocate(field2)
      if ( ialloc ) deallocate(field)
      rtcode = 0
!     All done
!     --------
999   continue
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOVarReadT3D__
Call graph
esmf_cfiovarreadt3d__ calls esmf_cfiovarread, getdate, cfio_parseinttime, diffdate, varobjs
esmf_cfiovarread calls esmf_cfiovarread1d_, esmf_cfiovarread2d_, esmf_cfiovarread3d_
getdate calls getdateint4, getdateint8
diffdate calls cfio_parseinttime, julday
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, strtoint
esmf_cfiovarread2d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
getdateint4 calls getdateint8
getdateint8 calls cfio_parseinttime, julday, caldat
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfioget calls err
esmf_cfiovarinfoget calls attcharcnts, attintcnts, attrealcnts, err
esmf_cfiovarreadt2 calls esmf_cfiovarreadt3d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
esmf_cfiovarreadt calls esmf_cfiovarreadt3d_
mapl_cfioreadbundle calls esmf_cfiovarreadt
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle