ESMF_CFIOVarInfoDestroy – MAPL
ESMF_CFIOVarInfoDestroy Subroutine
22 statements
Source File
public subroutine ESMF_CFIOVarInfoDestroy(varObj, rc)
ESMF_CFIOVarInfoDestroy – destructor for a CFIO varInfo object
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIOVarInfo), intent(inout) :: varObj
CFIOVarInfo object
integer, intent(out), optional :: rc
Error return code:
0 all is well
Calls
Called by
Source Code
      subroutine ESMF_CFIOVarInfoDestroy (varObj, rc)
!
! !INPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
! !INPUT/OUTPUT PARAMETERS:
!
      type(ESMF_CFIOVarInfo), intent(inout) :: varObj !! CFIOVarInfo object
!
!------------------------------------------------------------------------------
      integer :: rtcode = 0
      if ( associated(varObj%attCharCnts) ) deallocate(varObj%attCharCnts, &
                                             stat=rtcode)
      if ( associated(varObj%attRealCnts) ) deallocate(varObj%attRealCnts, &
                                             stat=rtcode)
      if ( associated(varObj%attIntCnts) ) deallocate(varObj%attIntCnts,   &
                                             stat=rtcode)
      if ( associated(varObj%attCharNames) ) deallocate(varObj%attCharNames,&
                                             stat=rtcode)
      if ( associated(varObj%attRealNames) ) deallocate(varObj%attRealNames,&
                                             stat=rtcode)
      if ( associated(varObj%attIntNames) ) deallocate(varObj%attIntNames,  &
                                             stat=rtcode)
      if ( associated(varObj%varAttChars) ) deallocate(varObj%varAttChars,  &
                                             stat=rtcode)
      if ( associated(varObj%varAttReals) ) deallocate(varObj%varAttReals,  &
                                             stat=rtcode)
      if ( associated(varObj%varAttInts) ) deallocate(varObj%varAttInts,    &
                                             stat=rtcode)
      if ( associated(varObj%ChunkSize ) ) deallocate(varObj%ChunkSize,       &
                                             stat=rtcode)
      if (.not. varObj%isGridSet) then
         call ESMF_CFIOGridDestroy(varObj%grid, rc=rtcode)
      end if
      if ( associated(varObj%iList) ) call iNodeDestroy(varObj%iList)
      if ( associated(varObj%rList) ) call rNodeDestroy(varObj%rList)
      if ( associated(varObj%cList) ) call cNodeDestroy(varObj%cList)
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOVarInfoDestroy
Call graph
esmf_cfiovarinfodestroy calls cnodedestroy, esmf_cfiogriddestroy, inodedestroy, rnodedestroy
esmf_cfiodestroy calls esmf_cfiovarinfodestroy
find calls esmf_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy, find
unfind calls esmf_cfiodestroy
esmf_iodestroy calls mapl_cfiodestroy
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
finalize calls mapl_cfiodestroy
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls find, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls esmf_ioread, mapl_cfioread, esmf_iodestroy