ESMF_CFIODownBit2D_ – MAPL
ESMF_CFIODownBit2D_ Subroutine
57 statements
Source File
private subroutine ESMF_CFIODownBit2D_(x, xr, nbits, undef, flops, rc)
ESMF_CFIODownBit - GRIB-based compression pre-conditioner
This routine returns a lower precision version of the input array x which retains nbits of precision. Two algorithms are implemented: 1) a fast one writen in C which downgrades precision by shifting xbits = 24 - nbits bits of the mantissa, and 2) a slower float point based algorithm which is the same algorithm as GRIB with fixed number of bits packing. Notice that as in GRIB the scaling factor is forced to be a power of 2 rather than a generic float. Using this power of 2 binary scaling has the advantage of improving the GZIP compression rates.
This routine returns an array of the same type and kind as the input array, so no data compression has taken place. The goal here is to reduce the entropy in the input array, thereby improving compression rates by the lossless algorithms implemented internally by HDF-4/5 when writing these data to a file. In fact, these GZIP’ed and pre-conditioned files have sizes comparable to the equivalent GRIB file, while being a bonafide self-describing HDF/NetCDF file.
@note Todo : Perhaps implement GRIB decimal scaling (variable number of bits).
History
06Dec2006 da Silva Initial version.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(:,:)
input array
real(kind=REAL32), intent(out) :: xr(:,:)
precision reduced array; can share storage with input array if it has same kind
integer, intent(in) :: nbits
number of bits per word to retain
real, intent(in), optional :: undef
missing value
logical, intent(in), optional :: flops
if true, uses slower float point based algorithm
integer, intent(out) :: rc
error code = 0 - all is well /= 0 - something went wrong
Calls
Called by
Source Code
   subroutine ESMF_CFIODownBit2D_ ( x, xr, nbits, undef, flops, rc )
     implicit NONE
!
! !INPUT PARAMETERS:
!
     real, intent(in)    ::  x(:,:)         !! input array
     integer, intent(in) :: nbits           !! number of bits per word to retain
     real, OPTIONAL, intent(in) :: undef    !! missing value
     logical, OPTIONAL, intent(in) :: flops !! if true, uses slower float point
                                            !!  based algorithm
!
! !OUTPUT PARAMETERS:
!
     real(kind=REAL32), intent(out)   :: xr(:,:)   !! precision reduced array; can
                                        !!  share storage with input array
                                        !!  if it has same kind
     integer, intent(out)  :: rc        !! error code
                                        !!  = 0 - all is well
                                        !! /= 0 - something went wrong
!
!------------------------------------------------------------------------------
    integer   :: E, xbits, has_undef
    real(kind=REAL32)    :: scale, xmin, xmax, tol, undef_
    logical   :: shave_mantissa
    integer, external :: ShaveMantissa32
    rc = 0
!   Defaults for optinal arguments
!   ------------------------------
    if ( present(undef) ) then
         undef_ = undef
         has_undef = 1
    else
         undef_ = 1.0
         undef_ = huge(undef_)   ! why not?
         has_undef = 0
    endif
    if ( present(flops) ) then
         shave_mantissa = .not. flops
    else
         shave_mantissa = .true.
    endif
!   Fast, bit shifting in C
!   -----------------------
    if ( shave_mantissa ) then
       xr = x   ! compiled r8 this will convert to r4.
       xbits = 24 - nbits
       rc = ShaveMantissa32 ( xr, xr, size(x), xbits, has_undef, undef_, size(x) )
       return
!   Slow, flops in FORTRAN (GRIB inspired)
!   --------------------------------------
    else
       if ( nbits < 1 ) then
          xr = x
          rc = 1
          return
       end if
       tol = 0.0001 * undef_
       xmin = minval(x,mask=(abs(undef_-x)>tol))
       xr = x - xmin     ! As in GRIB, force non-negative values
       xmax = maxval(xr,mask=(abs(undef_-x)>tol)) ! max of positive
       if ( xmax <= 0.0 ) then
            xr = x
            rc = 0
            return  ! this means field is constant
       end if
       E = nint(log(xmax)/log(2.)) - nbits ! GRIB binary scale factor
       scale = 2.**E                       ! GRIB requires power of 2
       if ( present(undef) ) then
          where ( abs(x - undef_) > tol )
             xr  = xmin + nint(xr/scale) * scale
          endwhere
       else
          xr  = xmin + nint(xr/scale) * scale
       end if
    end if
   end subroutine ESMF_CFIODownBit2D_
Call graph
esmf_cfiodownbit2d_ calls shavemantissa32
esmf_cfiodownbit calls esmf_cfiodownbit2d_, esmf_cfiodownbit3d_
esmf_cfiodownbit3d_ calls esmf_cfiodownbit2d_
mapl_cfiowritebundlewait calls esmf_cfiodownbit
utdownbit calls esmf_cfiodownbit
mapl_cfiowritebundle calls mapl_cfiowritebundlewait
esmf_iowrite calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle
mapl_cfiowritestate calls mapl_cfiowritebundle