ESMF_CFIOVarRead3D_ – MAPL
ESMF_CFIOVarRead3D_ Subroutine
66 statements
Source File
private subroutine ESMF_CFIOVarRead3D_(cfio, vName, field, date, curTime, kbeg, kount, xBeg, xCount, yBeg, yCount, timeString, rc)
ESMF_CFIOVarRead3D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:,:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
integer, intent(in), optional :: xBeg
first point for lon
integer, intent(in), optional :: xCount
number of points to read
integer, intent(in), optional :: yBeg
first point for lat
integer, intent(in), optional :: yCount
number of points to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Calls
Called by
Contents
Source Code
ESMF_CFIOVarRead3D_
Source Code
      subroutine ESMF_CFIOVarRead3D_(cfio, vName, field, date, curTime, &
                                     kBeg, kount, xBeg, xCount, yBeg,   &
                                     yCount, timeString, rc)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio      !! a CFIO obj
      character(len=*), intent(in) :: vName       !! variable name
      integer, intent(in), OPTIONAL :: date       !! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime    !! hhmmss
      integer, intent(in), OPTIONAL :: kbeg       !! first level to write
      integer, intent(in), OPTIONAL :: kount      !! number of levels to write
      integer, intent(in), OPTIONAL :: xBeg       !! first point for lon
      integer, intent(in), OPTIONAL :: xCount     !! number of points to read
      integer, intent(in), OPTIONAL :: yBeg       !! first point for lat
      integer, intent(in), OPTIONAL :: yCount     !! number of points to read
      character(len=*), intent(in), OPTIONAL :: timeString !! string expression for date and time
!
! !OUTPUT PARAMETERS:
!
      real, pointer :: field(:,:,:)             !! array contains data
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
!------------------------------------------------------------------------------
      integer :: i, rtcode
      integer :: myKbeg, myKount
      integer :: myXbeg, myXount
      integer :: myYbeg, myYount
      integer :: myDate, myCurTime
      integer :: im, jm, km
      integer :: nVars
      type(ESMF_CFIOGrid) :: grid
      type(ESMF_CFIOVarInfo), pointer :: vars(:)
      character(len=MLEN) :: myName
      logical :: twoD
      character(len=MLEN) :: format
      character(len=16) :: myFormat
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      call ESMF_CFIOGet(cfio, nVars=nVars,  rc=rtcode)
      if ( rtcode .ne. 0 ) print *, "problem in GrADS_read in ESMF_CFIOGet"
      !ALT allocate(vars(nVars), stat=rtcode)
      !ALT if ( rtcode .ne. 0 ) print *, "problem in allocate in GrADS_read"
      call ESMF_CFIOGet(cfio, varObjs=vars, format=format, rc=rtcode)
      if ( rtcode .ne. 0 ) print *, "problem in GrADS_read in ESMF_CFIOGet"
      do i = 1, nVars
         call ESMF_CFIOVarInfoGet(vars(i), vName=myName, grid=grid,  &
                                  twoDimVar=twoD, rc=rtcode)
         if ( rtcode .ne. 0 ) print *, "problem in GrADS_read in ESMF_CFIOVarInfoGet"
         call ESMF_CFIOGridGet(grid, im=im, jm=jm, km=km, rc=rtcode)
         if ( rtcode .ne. 0 ) print *, "problem in GrADS_read in ESMF_CFIOGridGet"
         if (km .lt. 1) km = 1
         if ( trim(vName) .eq. trim(myName) ) exit
      end do
!@      call ESMF_CFIOVarInfoDestroy(vars,rtcode)
      deallocate(vars)
      myKbeg = 1
      myKount = km
      if ( present(kbeg) ) myKbeg = kbeg
      if ( present(kount) ) myKount = kount
      if (twoD) myKount = 1
      myXbeg = 1
      myXount = im
      myYbeg = 1
      myYount = jm
      if ( present(xBeg) ) myXbeg=xBeg
      if ( present(yBeg) ) myYbeg=yBeg
      if ( present(xCount) ) myXount = xCount
      if ( present(yCount) ) myYount = yCount
      myFormat = trim(format)
      select case (myFormat)
      case ('SDF')
        call ESMF_CFIOSdfVarRead(cfio, vName, field, date=myDate,            &
                                 curTime=myCurTime, kBeg=myKbeg,             &
                                 kount=myKount, xBeg=myXbeg, xCount=myXount, &
                                 yBeg=myYbeg, yCount=myYount, rc=rtcode)
        if ( rtcode .ne. 0 ) print *, "problem in ESMF_CFIOSdfVarRead"
        if ( present(rc) ) rc= rtcode
        return
      end select
      print *, "Format is not known"
      end subroutine ESMF_CFIOVarRead3D_
Call graph
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, esmf_cfiovarinfoget, strtoint
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfioget calls err
esmf_cfiovarinfoget calls attcharcnts, attintcnts, attrealcnts, err
esmf_cfiosdfvarread1d_ calls strtoint, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiosdfvarread2d_ calls strtoint, err, cfio_getvar, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiosdfvarread3d_ calls strtoint, err, cfio_getvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiovarread calls esmf_cfiovarread3d_
esmf_cfiovarreadt2d__ calls esmf_cfiovarread
esmf_cfiovarreadt3d__ calls esmf_cfiovarread
mapl_cfioreadbundle calls esmf_cfiovarread
test calls esmf_cfiovarread
esmf_cfiovarreadt2 calls esmf_cfiovarreadt2d__, esmf_cfiovarreadt3d__
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
esmf_cfiovarreadt calls esmf_cfiovarreadt2d_, esmf_cfiovarreadt3d_
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread