ESMFL_FailedRC – MAPL
ESMFL_FailedRC Subroutine
7 statements
Source File
private subroutine ESMFL_FailedRC(mype, name)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mype
character(len=*), intent(in) :: name
Calls
Called by
Contents
Source Code
ESMFL_FailedRC
Source Code
   subroutine ESMFL_FailedRC(mype, name)
!-------------------------------------------------------------------------
!
! A local error-exiting routine for ESMFL
!
   integer, intent(in) :: mype
   character(len=*), intent(in) :: name
   _UNUSED_DUMMY(mype)
   write(*,*) ' *** ',trim(name),' failed ***'
   call ESMF_Finalize()
   end subroutine ESMFL_FailedRC
Call graph
esmfl_failedrc calls ESMF_Finalize
bundlediff calls esmfl_failedrc, esmfl_fieldgetdims
bundleregrid calls esmfl_failedrc
esmfl_fieldgetdims calls esmfl_failedrc
statediff calls esmfl_failedrc, bundlediff
stateregrid calls esmfl_failedrc, bundleregrid
esmfl_diff calls bundlediff, statediff
esmfl_regrid calls bundleregrid, stateregrid
bundlestatistics calls bundlediff
statestatistics calls statediff
esmfl_statistics calls bundlestatistics, statestatistics