ESMF_CFIOEosVarWrite2D_ – MAPL
ESMF_CFIOEosVarWrite2D_ Subroutine
56 statements
Source File
private subroutine ESMF_CFIOEosVarWrite2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
logical, intent(in), optional :: doComp
do szip compression
logical, intent(in), optional :: doChunk
do szip compression string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Calls
Called by
Source Code
      subroutine ESMF_CFIOEosVarWrite2D_(cfio, vName, field, date, curTime, kbeg, &
                                      kount, timeString, doComp, doChunk, rc)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(in) :: cfio         !! a CFIO obj
      character(len=*), intent(in) :: vName       !! Variable name
      real, intent(in) :: field(:,:)            !! array contains data
      integer, intent(in), OPTIONAL :: date     !! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime  !! hhmmss
      integer, intent(in), OPTIONAL :: kbeg     !! first level to write
      integer, intent(in), OPTIONAL :: kount    !! number of levels to write
      character(len=*), intent(in), OPTIONAL :: timeString
      logical, intent(in), OPTIONAL :: doComp     !! do szip compression
      logical, intent(in), OPTIONAL :: doChunk    !! do szip compression
                                  !! string expression for date and time
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
!------------------------------------------------------------------------------
      integer :: i, rtcode
      integer :: myKbeg, myKount
      integer :: myDate, myCurTime
      logical :: do_comp, do_chunk
      do_comp = .false.
      do_chunk = .false.
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      if ( present(doComp) ) do_comp = doComp
      if ( present(doChunk) ) do_chunk = doChunk
!
!     make sure user provides the right variable name
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
!     write 2D variable
      if (index(cfio%varObjs(i)%grid%gName,'station') .gt. 0) then
         if ( cfio%varObjs(i)%twoDimVar ) then
!            call CFIO_SPutVar (cfio%fid, vName, myDate, myCurTime,      &
            call EOS_PutVar (cfio%fid, vName, myDate, myCurTime,      &
                     cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                     0, 1, field,  do_comp, do_chunk, rtcode )
            if (err("CFIO_SPutVar failed",rtcode,rtcode) .lt. 0) then
               if ( present(rc) ) rc = rtcode
               return
            end if
         else
            myKbeg = 1
            myKount = cfio%varObjs(i)%grid%km
            if ( present(kbeg) ) myKbeg = kbeg
            if ( present(kount) ) myKount = kount
!            call CFIO_SPutVar (cfio%fid, vName, myDate, myCurTime,          &
            call EOS_PutVar (cfio%fid, vName, myDate, myCurTime,          &
                     cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                     myKbeg, myKount, field,  do_comp, do_chunk, rtcode )
            if (err("CFIO_SPutVar failed",rtcode,rtcode) .lt. 0) then
               if ( present(rc) ) rc = rtcode
               return
            end if
         end if
      else
         call EOS_PutVar (cfio%fid, vName, myDate, myCurTime,              &
                     cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                     0, 1, field,  do_comp, do_chunk, rtcode )
         if (err("EOS_PutVar failed",rtcode,rtcode) .lt. 0) then
            if ( present(rc) ) rc = rtcode
            return
         end if
      end if
      if ( cfio%varObjs(i)%timAve ) then
         call writeBnds(cfio, vName, myDate, myCurTime, rtcode)
      end if
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOEosVarWrite2D_
Call graph
esmf_cfioeosvarwrite2d_ calls eos_putvar, err, strtoint, writebnds
writebnds calls diffdate
diffdate calls cfio_parseinttime, julday
esmf_cfioeosvarwrite calls esmf_cfioeosvarwrite2d_