ESMF_CFIOEosVarWrite3D_ – MAPL
ESMF_CFIOEosVarWrite3D_ Subroutine
48 statements
Source File
private subroutine ESMF_CFIOEosVarWrite3D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, doComp, doChunk, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
character(len=*), intent(in) :: vName
real, intent(in) :: field(:,:,:)
integer, intent(in), optional :: date
integer, intent(in), optional :: curTime
integer, intent(in), optional :: kbeg
integer, intent(in), optional :: kount
character(len=*), intent(in), optional :: timeString
logical, intent(in), optional :: doComp
logical, intent(in), optional :: doChunk
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
ESMF_CFIOEosVarWrite3D_
Source Code
      subroutine ESMF_CFIOEosVarWrite3D_(cfio, vName, field, date, curTime, kbeg, &
                                      kount, timeString, doComp, doChunk, rc)
!
! !ARGUMENTS:
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(in) :: cfio         ! a CFIO obj
      character(len=*), intent(in) :: vName       ! Variable name
      real, intent(in) :: field(:,:,:)            ! array contains data
      integer, intent(in), OPTIONAL :: date       ! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime    ! hhmmss
      integer, intent(in), OPTIONAL :: kbeg       ! first level to write
      integer, intent(in), OPTIONAL :: kount      ! number of levels to write
      character(len=*), intent(in), OPTIONAL :: timeString
      logical, intent(in), OPTIONAL :: doComp     ! do szip compression
      logical, intent(in), OPTIONAL :: doChunk    ! do szip compression
                                  ! string expression for date and time
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      ! Error return code:
                                                ! 0   all is well
                         !  rc = -2  time is inconsistent with increment
                         !  rc = -3  number of levels is incompatible with file
                         !  rc = -4  im is incompatible with file
                         !  rc = -5  jm is incompatible with file
                         !  rc = -6  time must fall on a minute boundary
                         !  rc = -7  error in diffdate
                         !  rc = -12  error determining default precision
                         !  rc = -13  error determining variable type
                         !  rc = -15  data outside of valid range
                         !  rc = -16  data outside of packing range
                         !  rc = -17  data outside of pack and valid range
                         !  rc = -38  error from NF90_PUT_VAR (dimension variable)
                         !  rc = -40  error from NF90_INQ_VARID
                         !  rc = -41  error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lat or lon)
                         !  rc = -42  error from NF90_INQ_DIMID or NF90_INQUIRE_DIMENSION (lev)
                         !  rc = -43  error from NF90_INQ_VARID (time variable)
                         !  rc = -44  error from NF90_GET_ATT (time attribute)
                         !  rc = -45  error from NF90_PUT_VAR
                         !  rc = -46  error from NF90_GET_VAR
                         !  rc = -52  error from NF90_INQUIRE_VARIABLE
                         !  rc = -53  error from NF90_GET_ATT
!
! !DESCRIPTION:
!     Write a variable to file
!EOP
!------------------------------------------------------------------------------
      integer :: i, rtcode
      integer :: myKbeg, myKount
      integer :: myDate, myCurTime
      logical :: do_comp, do_chunk
      do_comp = .false.
      do_chunk = .false.
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      if ( present(doComp) ) do_comp = doComp
      if ( present(doChunk) ) do_chunk = doChunk
!
!     make sure user provides the right variable name
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
!     write 2D variable
      if ( cfio%varObjs(i)%twoDimVar ) then
         call EOS_PutVar (cfio%fid, vName, myDate, myCurTime,             &
                        cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                        0, 1, field, do_comp, do_chunk, rtcode )
         if (err("EOS_PutVar failed",rtcode,rtcode) .lt. 0) then
            if ( present(rc) ) rc = rtcode
            return
         end if
!     write 3D variable
      else
         myKbeg = 1
         myKount = cfio%varObjs(i)%grid%km
         if ( present(kbeg) ) myKbeg = kbeg
         if ( present(kount) ) myKount = kount
         call EOS_PutVar (cfio%fid, vName, myDate, myCurTime,             &
                        cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                        myKbeg, myKount, field,  do_comp, do_chunk, rtcode )
         if (err("EOS_PutVar failed",rtcode,rtcode) .lt. 0) then
            if ( present(rc) ) rc = rtcode
            return
         end if
      end if
      if ( cfio%varObjs(i)%timAve ) then
         call writeBnds(cfio, vName, myDate, myCurTime, rtcode)
      end if
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOEosVarWrite3D_
Call graph
esmf_cfioeosvarwrite3d_ calls strtoint, writebnds, eos_putvar, err
writebnds calls diffdate
diffdate calls cfio_parseinttime, julday
esmf_cfioeosvarwrite calls esmf_cfioeosvarwrite3d_