ESMF_CFIOFileClose – MAPL
ESMF_CFIOFileClose Subroutine
15 statements
Source File
public subroutine ESMF_CFIOFileClose(cfio, rc)
ESMF_CFIOFileClose – close an open CFIO stream
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
integer, intent(out), optional :: rc
Error return code: 0 all is well -54 error from ncclos (file close)
Calls
Called by
Source Code
      subroutine ESMF_CFIOFileClose (cfio, rc)
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc    !! Error return code:
                                              !! 0   all is well
                                              !! -54  error from ncclos (file close)
!
! !INPUT/OUTPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inout) :: cfio       ! CFIO object
!
!------------------------------------------------------------------------------
       integer :: rtcode
       character(len=16) format
      call ESMF_CFIOGet(cfio, format=format, rc=rtcode)
      if (rtcode .ne. 0) print *, "Error in ESMF_CFIOGet in FileClose"
      select case (format)
      case ('SDF')
          call ESMF_CFIOSdfFileClose(cfio,rtcode)
          if (rtcode .ne. 0) print *, "Error in ESMF_CFIOFileClose"
          if ( present(rc) ) rc = rtcode
          return
#if defined(HDFEOS)
      case ('EOS')
          call ESMF_CFIOEosFileClose(cfio,rtcode)
          if (rtcode .ne. 0) print *, "Error in ESMF_CFIOEosFileClose"
          if ( present(rc) ) rc = rtcode
          return
#endif
      end select
      end subroutine ESMF_CFIOFileClose
Call graph
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
esmf_cfioget calls err
esmf_cfiosdffileclose calls cfio_close
cfio_close calls err, ncclos
mapl_cfioclose calls esmf_cfiofileclose
mapl_cfiodestroy calls esmf_cfiofileclose
test calls esmf_cfiofileclose
esmf_iodestroy calls mapl_cfiodestroy
finalize calls mapl_cfiodestroy
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
test_main calls esmf_iodestroy
utcfio calls test_main