ESMFL_StateGetFieldArray – MAPL
ESMFL_StateGetFieldArray Subroutine
24 statements
Source File
public subroutine ESMFL_StateGetFieldArray(state, name, array, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: name
type(ESMF_Array), intent(out) :: array
integer, intent(out), optional :: rc
Calls
Called by
Source Code
 subroutine ESMFL_StateGetFieldArray(state, NAME, ARRAY, RC)
   type(ESMF_State),  intent(IN)  :: state
   type(ESMF_Array),  intent(OUT) :: array
   character(len=*),   intent(IN) :: name
   integer, optional, intent(OUT) :: rc
   integer          :: status
   type(ESMF_Field) :: field
   type(ESMF_StateItem_Flag) :: itemType
   call ESMF_StateGet(state, name, itemType=itemType, rc=status)
   _VERIFY(STATUS)
   if (itemType /= ESMF_STATEITEM_FIELD) then
      if (present(RC)) then
         RC=STATUS
         return
      end if
   else
      call ESMF_StateGet(state, name, field, rc=status)
      _VERIFY(STATUS)
      call ESMF_FieldGet(field, Array=array, rc=status)
      _VERIFY(STATUS)
   end if
   _RETURN(ESMF_SUCCESS)
 end subroutine ESMFL_StateGetFieldArray
Call graph
esmfl_stategetfieldarray calls esmf_fieldget, esmf_stateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_gradsctlwrite calls esmfl_stategetfieldarray
run calls mapl_gradsctlwrite