ESMF_CFIOSdfVarWrite2D_ – MAPL
ESMF_CFIOSdfVarWrite2D_ Subroutine
71 statements
Source File
private subroutine ESMF_CFIOSdfVarWrite2D_(cfio, vName, field, date, curTime, kbeg, kount, timeString, rc)
ESMF_CFIOSdfVarWrite2D_ – Write a variable to a output file.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
Variable name
real, intent(in) :: field(:,:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: kbeg
first level to write
integer, intent(in), optional :: kount
number of levels to write
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Calls
Called by
Source Code
      subroutine ESMF_CFIOSdfVarWrite2D_(cfio, vName, field, date, curTime, &
                                      kbeg, kount, timeString, rc)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio    !! a CFIO obj
      character(len=*), intent(in) :: vName     !! Variable name
      real, intent(in) :: field(:,:)            !! array contains data
      integer, intent(in), OPTIONAL :: date     !! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime  !! hhmmss
      integer, intent(in), OPTIONAL :: kbeg     !! first level to write
      integer, intent(in), OPTIONAL :: kount    !! number of levels to write
      character(len=*), intent(in), OPTIONAL :: timeString !! string expression for date and time
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
!------------------------------------------------------------------------------
      integer :: i, rtcode
      integer :: myKbeg, myKount
      integer :: myDate, myCurTime
      logical :: useFaceDim
      character(len=MLEN) :: fNameTmp     ! file name
      fNameTmp = ''
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      if (len(trim(cfio%fNameTmplt)) .gt. 1) then
         call strTemplate_(fNameTmp,cfio%fNameTmplt,xid=cfio%expid,nymd=myDate, &
                           nhms=myCurTime, stat=rtcode)
         if (trim(fNameTmp) .ne. trim(cfio%fName)) then
            call ESMF_CFIOSdfFileClose(cfio)
            cfio%fName = fNameTmp
            call ESMF_CFIOSet(cfio, fName=cfio%fName)
            call ESMF_CFIOSet(cfio, date=myDate, begTime=myCurTime)
            if (len(trim(cfio%expid)) .gt. 0) then
               call ESMF_CFIOSdfFileCreate(cfio, expid=cfio%expid)
            else
               call ESMF_CFIOSdfFileCreate(cfio)
            end if
         end if
      end if
!
!     make sure user provides the right variable name
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
!     write 2D variable
      if (index(cfio%varObjs(i)%grid%gName,'station') .gt. 0) then
         if ( cfio%varObjs(i)%twoDimVar ) then
            call CFIO_SPutVar (cfio%fid, vName, myDate, myCurTime,      &
                     cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                     0, 1, field, rtcode )
            if (err("CFIO_SPutVar failed",rtcode,rtcode) .lt. 0) then
               if ( present(rc) ) rc = rtcode
               return
            end if
         else
            myKbeg = 1
            myKount = cfio%varObjs(i)%grid%km
            if ( present(kbeg) ) myKbeg = kbeg
            if ( present(kount) ) myKount = kount
            call CFIO_SPutVar (cfio%fid, vName, myDate, myCurTime,          &
                     cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
                     myKbeg, myKount, field, rtcode )
            if (err("CFIO_SPutVar failed",rtcode,rtcode) .lt. 0) then
               if ( present(rc) ) rc = rtcode
               return
            end if
         end if
      else
         if (cfio%formatVersion > 2.0) then
            useFaceDim = .true.
         else
            useFaceDim = .false.
         end if
         call CFIO_PutVar (cfio%fid, vName, myDate, myCurTime,              &
              cfio%varObjs(i)%grid%im, cfio%varObjs(i)%grid%jm,  &
              0, 1, field, useFaceDim, rtcode )
         if (err("CFIO_PutVar failed",rtcode,rtcode) .lt. 0) then
            if ( present(rc) ) rc = rtcode
            return
         end if
      end if
      if ( cfio%varObjs(i)%timAve ) then
         call writeBnds(cfio, vName, myDate, myCurTime, rtcode)
      end if
      if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOSdfVarWrite2D_
Call graph
esmf_cfiosdfvarwrite2d_ calls cfio_putvar, cfio_sputvar, err, esmf_cfiosdffileclose, esmf_cfiosdffilecreate, esmf_cfioset, strtemplate_, strtoint, writebnds
cfio_putvar calls err, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_put_var, cfio_parseinttime, diffdate
cfio_sputvar calls err, nf90_get_att, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_put_var, cfio_parseinttime, diffdate
esmf_cfiosdffileclose calls cfio_close
esmf_cfiosdffilecreate calls err, esmf_cfioset, strtemplate_, cfio_create_, cfio_putcharatt, cfio_putintatt, cfio_putrealatt, esmf_cfioget, getlist
esmf_cfioset calls err, strtoint, addlist
strtemplate_ calls die, gx_
writebnds calls nf90_inq_varid, nf90_put_var, cfio_parseinttime, diffdate
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite2d_
esmf_cfiovarwrite1d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite2d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite3d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite calls esmf_cfiovarwrite1d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite3d_
mapl_cfiowritebundlewrite calls esmf_cfiovarwrite
test calls esmf_cfiovarwrite