ESMFL_BundleGetPointerByIndex2 – MAPL
ESMFL_BundleGetPointerByIndex2 Subroutine
21 statements
Source File
private subroutine ESMFL_BundleGetPointerByIndex2(BUNDLE, INDEX, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
integer, intent(in) :: INDEX
real, pointer :: PTR(:,:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
ESMFL_BundleGetPointerByIndex2
Source Code
   subroutine ESMFL_BundleGetPointerByIndex2(BUNDLE,INDEX,PTR,RC)
     type(ESMF_FieldBundle), intent(INOUT) :: BUNDLE !ALT: intent(in)
     integer,           intent(IN) :: INDEX
     real, pointer                 :: PTR(:,:)
     integer, optional, intent(OUT):: RC
     type(ESMF_FIELD)              :: FIELD
     integer                       :: status
     type(ESMF_FieldStatus_Flag)   :: fieldStatus
! ESMF 5 reorders items, be careful!
! ==================================
     call ESMF_FieldBundleGet (BUNDLE, INDEX, FIELD, RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_FieldGet(field, status=fieldStatus, rc=status)
     _VERIFY(STATUS)
     if (fieldStatus == ESMF_FIELDSTATUS_COMPLETE) then
        call ESMF_FieldGet(field, 0, Ptr, rc=status)
        _VERIFY(STATUS)
     else
        NULLIFY(ptr)
     end if
     _RETURN(ESMF_SUCCESS)
   end subroutine ESMFL_BundleGetPointerByIndex2
Call graph
esmfl_bundlegetpointerbyindex2 calls esmf_fieldbundleget, mapl_verify, esmf_fieldget, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
esmfl_bundlegetpointertodata calls esmfl_bundlegetpointerbyindex2
run_ calls esmfl_bundlegetpointertodata, mapl_extdatainterpfield
mapl_extdatainterpfield calls esmfl_bundlegetpointertodata