ESMF_CFIOSdfFileClose – MAPL
ESMF_CFIOSdfFileClose Subroutine
16 statements
Source File
public subroutine ESMF_CFIOSdfFileClose(cfio, rc)
ESMF_CFIOSdfFileClose – close an open CFIO stream.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
CFIO object
integer, intent(out), optional :: rc
Error return code: 0 all is well -54 error from ncclos (file close)
Calls
Called by
Source Code
      subroutine ESMF_CFIOSdfFileClose (cfio, rc)
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                       !! 0   all is well
                                       !! -54  error from ncclos (file close)
!
! !INPUT/OUTPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inout) :: cfio       !! CFIO object
!
!------------------------------------------------------------------------------
       integer :: rtcode
       if ( cfio%isOpen ) then
          call CFIO_Close(cfio%fid, rtcode)
          if (rtcode .ne. 0) then
             print *, "CFIO_Close failed"
          else
             cfio%isOpen = .false.
          end if
       else
          rtcode = 0
       end if
       if ( present(rc) ) rc = rtcode
      end subroutine ESMF_CFIOSdfFileClose
Call graph
esmf_cfiosdffileclose calls cfio_close
cfio_close calls ncclos, err
esmf_cfiofileclose calls esmf_cfiosdffileclose
esmf_cfiosdfvarread1d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarread2d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarread3d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarwrite1d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarwrite2d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarwrite3d_ calls esmf_cfiosdffileclose
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
mapl_cfioclose calls esmf_cfiofileclose
mapl_cfiodestroy calls esmf_cfiofileclose
test calls esmf_cfiofileclose