ESMFL_BundleCpyField – MAPL
ESMFL_BundleCpyField Subroutine
14 statements
Source File
public subroutine ESMFL_BundleCpyField(BUNDLE, FIELD, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
type(ESMF_Field), intent(inout) :: FIELD
character(len=ESMF_MAXSTR), intent(in), optional :: NAME
integer, intent(out), optional :: RC
Calls
Contents
Source Code
ESMFL_BundleCpyField
Source Code
    subroutine ESMFL_BundleCpyField (BUNDLE, FIELD, NAME, RC)
     type(ESMF_FieldBundle), intent(INOUT) :: BUNDLE
     type(ESMF_FIELD ), intent(INOUT) :: FIELD ! ALT: intent(in)
     character(len=ESMF_MAXSTR), optional, intent(IN) :: NAME
     integer, optional, intent(OUT)   :: RC
     type(ESMF_FIELD )       :: FIELD1
     integer          :: status
     FIELD1 = MAPL_FieldCreate(FIELD, name = name, RC=STATUS )
     _VERIFY(STATUS)
     call MAPL_FieldBundleAdd (BUNDLE, FIELD1, RC=STATUS )
     _VERIFY(STATUS)
     _RETURN(ESMF_SUCCESS)
   end subroutine  ESMFL_BundleCpyField
Call graph
esmfl_bundlecpyfield calls mapl_fieldcreate, mapl_verify, mapl_fieldbundleadd, mapl_return
mapl_fieldcreate calls mapl_fieldcreaterename, mapl_fieldcreatenewgrid, mapl_fieldcreater4
mapl_verify calls mapl_throw_exception
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_return calls mapl_throw_exception, get_error_message
mapl_fieldcreaterename calls mapl_fieldcreaterename, mapl_verify, mapl_return, esmf_fieldget, mapl_assert, esmf_gridget, mapl_fieldcreateempty, esmf_fieldemptycomplete, mapl_fieldcopyattributes
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_verify, mapl_return, esmf_fieldget, esmf_fieldbundleadd, esmf_attributeget, esmf_attributeremove, esmf_attributeset
mapl_fieldcreatenewgrid calls mapl_fieldcreatenewgrid, mapl_verify, mapl_return, esmf_fieldcreate, esmf_localarrayget, esmf_fieldget, mapl_assert, esmf_gridget, mapl_fieldcopyattributes, esmf_attributeset, esmf_arrayget, mapl_gridget
mapl_throw_exception calls initialize
mapl_fieldcreater4 calls mapl_fieldcreater4, mapl_verify, mapl_return, esmf_fieldget, mapl_assert, esmf_gridget, mapl_fieldcreateempty, esmf_fieldemptycomplete, mapl_fieldcopyattributes