ESMF_CFIOVarRead1D_ – MAPL
ESMF_CFIOVarRead1D_ Subroutine
44 statements
Source File
private subroutine ESMF_CFIOVarRead1D_(cfio, vName, field, date, curTime, xBeg, xCount, timeString, rc)
ESMF_CFIOVarRead1D_ – Read a variable from an existing file
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO obj
character(len=*), intent(in) :: vName
variable name
real, pointer :: field(:)
array contains data
integer, intent(in), optional :: date
yyyymmdd
integer, intent(in), optional :: curTime
hhmmss
integer, intent(in), optional :: xBeg
first point for lon
integer, intent(in), optional :: xCount
number of points to read
character(len=*), intent(in), optional :: timeString
string expression for date and time
integer, intent(out), optional :: rc
Error return code: 0 all is well
Calls
Called by
Contents
Source Code
ESMF_CFIOVarRead1D_
Source Code
      subroutine ESMF_CFIOVarRead1D_(cfio, vName, field, date, curTime, &
                                     xBeg, xCount, timeString, rc)
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inOut) :: cfio      !! a CFIO obj
      character(len=*), intent(in) :: vName       !! variable name
      integer, intent(in), OPTIONAL :: date       !! yyyymmdd
      integer, intent(in), OPTIONAL :: curTime    !! hhmmss
      integer, intent(in), OPTIONAL :: xBeg       !! first point for lon
      integer, intent(in), OPTIONAL :: xCount     !! number of points to read
      character(len=*), intent(in), OPTIONAL :: timeString !! string expression for date and time
!
! !OUTPUT PARAMETERS:
!
      real, pointer :: field(:)                 !! array contains data
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
!
!------------------------------------------------------------------------------
      integer :: rtcode
      integer :: myXbeg, myXount
      integer :: myDate, myCurTime
      integer :: im
      integer :: nVars
      type(ESMF_CFIOGrid), pointer :: grid
      type(ESMF_CFIOVarInfo), pointer :: vars(:)
      character(len=MLEN) :: format
      if ( present(date) ) myDate = date
      if ( present(curTime) ) myCurTime = curTime
      if ( present(timeString) ) call strToInt(timeString,myDate,myCurTime)
      allocate(grid, stat=rtcode)
      call ESMF_CFIOGet(cfio, nVars=nVars, grid=grid, rc=rtcode)
      if ( rtcode .ne. 0 ) print *, "problem in GrADS_read in ESMF_CFIOGet"
!ALT      allocate(vars(nVars), stat=rtcode)
!ALT      if (rtcode .ne. 0) print *, "problem in allocate in ESMF_CFIORead"
      call ESMF_CFIOGet(cfio, varObjs=vars, format=format, rc=rtcode)
      if ( rtcode .ne. 0 ) print *, "problem in allocate in ESMF_CFIOGet"
      call ESMF_CFIOGridGet(grid, im=im, rc=rtcode)
      if ( rtcode .ne. 0 ) print *, "problem in calling ESMF_CFIORead"
!@      call ESMF_CFIOVarInfoDestroy(vars,rtcode)
      deallocate(vars)
      myXbeg = 1
      myXount = im
      if ( present(xBeg) ) myXbeg=xBeg
      if ( present(xCount) ) myXount = xCount
      select case (format)
      case ('GRADS')
        print *, "Read 1D GrADS file is not supportted."
      case ('SDF')
        call ESMF_CFIOSdfVarRead(cfio, vName, field, date=myDate,            &
                                 curTime=myCurTime,  xBeg=myXbeg,            &
                                 xCount=myXount, rc=rtcode)
        if ( rtcode .ne. 0 ) print *, "problem in calling ESMF_CFIORead"
        if ( present(rc) ) rc= rtcode
        return
      end select
      print *, "Format is not known"
      end subroutine ESMF_CFIOVarRead1D_
Call graph
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread, esmf_cfioget, esmf_cfiogridget, strtoint
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfioget calls err
esmf_cfiosdfvarread1d_ calls strtoint, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiosdfvarread2d_ calls strtoint, err, cfio_getvar, cfio_sgetvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiosdfvarread3d_ calls strtoint, err, cfio_getvar, esmf_cfiosdffileclose, esmf_cfiosdffileopen, strtemplate_, varobjs
esmf_cfiovarread calls esmf_cfiovarread1d_
esmf_cfiovarreadt2d__ calls esmf_cfiovarread
esmf_cfiovarreadt3d__ calls esmf_cfiovarread
mapl_cfioreadbundle calls esmf_cfiovarread
test calls esmf_cfiovarread
esmf_cfiovarreadt2 calls esmf_cfiovarreadt2d__, esmf_cfiovarreadt3d__
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
esmf_cfiovarreadt calls esmf_cfiovarreadt2d_, esmf_cfiovarreadt3d_
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread