ESMF_CFIOFileCreate – MAPL
ESMF_CFIOFileCreate Subroutine
25 statements
Source File
public subroutine ESMF_CFIOFileCreate(cfio, rc, expid, format)
ESMF_CFIOFileCreate – Create a CFIO output file with meta data
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(inout) :: cfio
a CFIO object
integer, intent(out), optional :: rc
Error return code: 0 all is well -1 Time increment is 0 -2 allocate memory error -3 Num of int/char/real elements and Cnt don’t match -12 error determining default precision -18 incorrect time increment -30 can’t open file -31 error from NF90_DEF_DIM -32 error from NF90_DEF_VAR (dimension variable) -33 error from NF90_PUT_ATT (dimension attribute) -34 error from NF90_DEF_VAR (variable) -35 error from NF90_PUT_ATT (variable attribute) -36 error from NF90_PUT_ATT (global attribute) -37 error from NF90_ENDDEF -38 error from NF90_PUT_VAR (dimension variable) -39 Num of real var elements and Cnt differ -55 error from NF90_REDEF (enter define mode) -56 error from NF90_ENDDEF (exit define mode)
character(len=*), intent(in), optional :: expid
Experiment ID
character(len=*), intent(in), optional :: format
GrADS or SDF
Calls
Called by
Source Code
      subroutine ESMF_CFIOFileCreate (cfio, rc, expid, format)
!
! !ARGUMENTS:
!
! !INPUT PARAMETERS:
!
      type(ESMF_CFIO), intent(inout) :: cfio              !! a CFIO object
      character(len=*), intent(in), OPTIONAL  :: expid    !! Experiment ID
      character(len=*), intent(in), OPTIONAL  :: format   !! GrADS or SDF
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                      !! 0   all is well
                      !! -1 Time increment is 0
                      !! -2  allocate memory error
                      !! -3  Num of int/char/real elements and Cnt don't match
                      !! -12  error determining default precision
                      !! -18 incorrect time increment
                      !! -30 can't open file
                      !! -31 error from NF90_DEF_DIM
                      !! -32 error from NF90_DEF_VAR (dimension variable)
                      !! -33 error from NF90_PUT_ATT (dimension attribute)
                      !! -34 error from NF90_DEF_VAR (variable)
                      !! -35  error from NF90_PUT_ATT (variable attribute)
                      !! -36  error from NF90_PUT_ATT (global attribute)
                      !! -37  error from NF90_ENDDEF
                      !! -38  error from NF90_PUT_VAR (dimension variable)
                      !! -39 Num of real var elements and Cnt differ
                      !! -55  error from NF90_REDEF (enter define mode)
                      !! -56  error from NF90_ENDDEF (exit define mode)
!
!------------------------------------------------------------------------------
      integer :: rtcode
      character (len=16) :: myFormat
      myFormat = 'SDF'
      if (present(format)) then
         if (trim(ESMF_UtilStringUpperCase(format)) .eq. 'GRADS' )  then
             call ESMF_CFIOSet(cfio, format='GRADS')
             myFormat = 'GRADS'
         end if
#if defined(HDFEOS)
         if (ESMF_UtilStringUpperCase(format)) .eq. 'EOS' )  then
             call ESMF_CFIOSet(cfio, format='EOS')
             myFormat = 'EOS'
         end if
#endif
      end if
      select case (myFormat)
      case ('SDF')
         if (present(expid)) then
            call ESMF_CFIOSdfFileCreate (cfio, rtcode, expid)
         else
            call ESMF_CFIOSdfFileCreate (cfio, rtcode)
         end if
         if (present(rc)) rc = rtcode
         return
#if defined(HDFEOS)
      case ('EOS')
         call ESMF_CFIOEOSFileCreate (cfio, rtcode)
         if (present(rc)) rc = rtcode
         return
#endif
      end select
    end subroutine ESMF_CFIOFileCreate
Call graph
esmf_cfiofilecreate calls ESMF_UtilStringUpperCase, esmf_cfiosdffilecreate, esmf_cfioset
esmf_cfiosdffilecreate calls esmf_cfioset, cfio_create_, cfio_putcharatt, cfio_putintatt, cfio_putrealatt, err, esmf_cfioget, getlist, strtemplate_
esmf_cfioset calls addlist, err, strtoint
cfio_create_ calls err, getlist, nf90_create, nf90_def_dim, nf90_def_var, nf90_def_var_chunking, nf90_def_var_deflate, nf90_enddef, nf90_put_att, nf90_put_var, cfio_parseinttime, getmaxlencnt
cfio_putcharatt calls err, nf90_enddef, nf90_put_att, nf90_redef
cfio_putintatt calls err, nf90_enddef, nf90_put_att, nf90_redef
cfio_putrealatt calls err, nf90_enddef, nf90_put_att, nf90_redef
esmf_cfioget calls err
getlist calls getmaxlencnt
strtemplate_ calls die, gx_
gx_ calls die, perr
mapl_cfiocreatewrite calls esmf_cfiofilecreate
test calls esmf_cfiofilecreate
mapl_cfiowritebundle calls mapl_cfiocreatewrite
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
test_main calls esmf_iowrite