ESMFL_BundleGetPointerByName2 – MAPL
ESMFL_BundleGetPointerByName2 Subroutine
21 statements
Source File
private subroutine ESMFL_BundleGetPointerByName2(BUNDLE, NAME, PTR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
character(len=*), intent(in) :: NAME
real, pointer :: PTR(:,:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
ESMFL_BundleGetPointerByName2
Source Code
   subroutine ESMFL_BundleGetPointerByName2(BUNDLE,NAME,PTR,RC)
     type(ESMF_FieldBundle), intent(INOUT) :: BUNDLE !ALT: intent(in)
     character(len=*), intent(IN) :: NAME
     real, pointer                 :: PTR(:,:)
     integer, optional, intent(OUT):: RC
     type(ESMF_FIELD)              :: FIELD
     type(ESMF_FieldStatus_Flag)   :: fieldStatus
     integer                       :: status
     call ESMF_FieldBundleGet (BUNDLE, NAME, FIELD=FIELD, RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_FieldGet(field, status=fieldStatus, rc=status)
     _VERIFY(STATUS)
     if (fieldStatus == ESMF_FIELDSTATUS_COMPLETE) then
        call ESMF_FieldGet(field, 0, Ptr, rc=status)
        _VERIFY(STATUS)
     else
        NULLIFY(ptr)
     end if
     _RETURN(ESMF_SUCCESS)
   end subroutine ESMFL_BundleGetPointerByName2
Call graph
esmfl_bundlegetpointerbyname2 calls esmf_fieldbundleget, mapl_return, esmf_fieldget, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
esmfl_bundlegetpointertodata calls esmfl_bundlegetpointerbyname2
mapl_extdatainterpfield calls esmfl_bundlegetpointertodata
run_ calls esmfl_bundlegetpointertodata, mapl_extdatainterpfield