evaluate_mask – MAPL
evaluate_mask Subroutine
20 statements
Source File
private subroutine evaluate_mask(this, state, field, rc)
Type Bound
StateMask
Arguments
Type Intent Optional Attributes Name
class(StateMask), intent(inout) :: this
type(ESMF_State), intent(inout) :: state
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine evaluate_mask(this,state,field,rc)
      class(StateMask), intent(inout) :: this
      type(ESMF_State), intent(inout) :: state
      type(ESMF_Field), intent(inout) :: field
      integer, optional, intent(out) :: rc
      integer :: status
      select case(this%mask_type)
      case("regionmask")
         call this%evaluate_region_mask(state,field,_RC)
      case("zonemask")
         call this%evaluate_zone_mask(state,field,_RC)
      case("boxmask")
         call this%evaluate_box_mask(state,field,_RC)
      end select
      _RETURN(_SUCCESS)
   end subroutine evaluate_mask
Call graph
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask, mapl_return, mapl_verify
evaluate_box_mask calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_GridGetCoord, esmf_fieldget, esmfl_stategetpointertodata, mapl_assert, mapl_gridget
evaluate_region_mask calls mapl_return, mapl_verify, esmf_fieldget, esmfl_stategetpointertodata, mapl_assert, extdataextractintegers
evaluate_zone_mask calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_GridGetCoord, esmf_fieldget, esmfl_stategetpointertodata, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evaluate_derived_field calls evaluate_mask
statefilter_r4_2d calls evaluate_mask
statefilter_r4_3d calls evaluate_mask
test_region_mask_2d calls evaluate_mask
test_region_mask_3d calls evaluate_mask
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run_ calls evaluate_derived_field
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem