evaluate_time – MAPL
evaluate_time Function
41 statements
Source File
private function evaluate_time(this, currTime, rc) result(dt)
Type Bound
timeVar
Arguments
Type Intent Optional Attributes Name
class(timeVar), intent(in) :: this
type(ESMF_Time), intent(inout) :: currTime
integer, intent(out), optional :: rc
Return Value real(kind=ESMF_KIND_R8)
Calls
Called by
Source Code
   function evaluate_time(this,currTime,rc) result(dt)
      class(timeVar), intent(in) :: this
      type(ESMF_Time), intent(inout) :: currTime
      integer, optional, intent(out) :: rc
      real(kind=ESMF_KIND_R8) :: dt
      integer :: status
      type(ESMF_TimeInterval) :: timeInterval, yearInterval
      integer :: ycurr,yint
      type(ESMF_Time) :: periodic_time
      if (this%climYear > 0) then
         call ESMF_TimeGet(currTime,yy=ycurr,_RC)
         yint=this%climYear-ycurr
         call ESMF_TimeIntervalSet(yearInterval,yy=yint,_RC)
         currTime = currTime+yearInterval
      end if
      periodic_time = this%set_time_for_date(currTime,_RC)
      if (this%have_offset) then
         timeInterval = periodic_time + this%update_offset - this%refTime
      else
         timeInterval = periodic_time - this%refTime
      end if
      select case(trim(this%timeUnits))
      case ('days')
         call ESMF_TimeIntervalGet(timeInterval,d_r8=dt,_RC)
      case ('hours')
         call ESMF_TimeIntervalGet(timeInterval,h_r8=dt,_RC)
      case ('minutes')
         call ESMF_TimeIntervalGet(timeInterval,m_r8=dt,_RC)
      case ('seconds')
         call ESMF_TimeIntervalGet(timeInterval,s_r8=dt,_RC)
      case default
         _FAIL("Unsupported time units specify for interval")
      end select
   end function evaluate_time
Call graph
evaluate_time calls ESMF_TimeGet, ESMF_TimeIntervalGet, ESMF_TimeIntervalSet, mapl_assert, mapl_verify, set_time_for_date
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
set_time_for_date calls ESMF_TimeGet, mapl_verify, ESMF_TimeSet, mapl_unpacktime, mapl_return
mapl_unpacktime calls mapl_unpacktime
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
fillstate calls evaluate_time
run_ calls fillstate