evaluate_token – MAPL
evaluate_token Function
99 statements
Source File
private function evaluate_token(token, year, month, day, hour, minute, second, preserve) result(buffer)
Arguments
Type Intent Optional Attributes Name
character(len=2), intent(in) :: token
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: day
integer, intent(in) :: hour
integer, intent(in) :: minute
integer, intent(in) :: second
logical, intent(in) :: preserve
Return Value character(len=4)
Calls
Called by
Source Code
   function evaluate_token(token,year,month,day,hour,minute,second,preserve) result(buffer)
      character(len=2), intent(in) :: token
      integer, intent(in) :: year,month,day,hour,minute,second
      logical, intent(in) :: preserve
      character(len=4) :: buffer
      character(len=1) :: c1,c2
      type(ESMF_Time)  :: time
      integer(ESMF_KIND_I4) :: doy
      integer :: status, rc
      type(ESMF_Calendar) :: gregorianCalendar
      c1=token(1:1)
      c2=token(2:2)
      select case(c1)
      case("y")
         if (.not.skip_token(year,preserve)) then
            if (c2 == "2" ) then
               write(buffer,'(i2.2)')mod(year,100)
            else if (c2 == "4" ) then
               write(buffer,'(i4.4)')year
            end if
         else
            buffer="%"//token
         end if
      case("m")
         if (.not.skip_token(month,preserve)) then
            if (c2 == "c") then
               buffer = mon_lc(month)
            else if (c2 == "1") then
               if (day < 10) then
                  write(buffer,'(i1)')month
               else
                  write(buffer,'(i2)')month
               end if
            else if (c2 == "2") then
               write(buffer,'(i2.2)')month
            end if
         else
            buffer="%"//token
         end if
      case("d")
         if (.not.skip_token(day,preserve)) then
            if (c2 == "2") then
               write(buffer,'(i2.2)')day
            else if (c1 == "1") then
               if (day < 10) then
                  write(buffer,'(i1)')day
               else
                  write(buffer,'(i2)')day
               end if
            end if
         else
            buffer="%"//token
         end if
      case("D")   ! dayOfYear
         if (.not.skip_token(day,preserve)) then
            if (c2 == "3") then
               gregorianCalendar = ESMF_CalendarCreate(ESMF_CALKIND_GREGORIAN, &
                    name='Gregorian_obs' , rc=rc)
               call ESMF_TimeSet(time, yy=year, mm=month, dd=day, &
                    calendar=gregorianCalendar, _RC)
               call ESMF_TimeGet(time, dayOfYear=doy, _RC)
               call ESMF_CalendarDestroy(gregorianCalendar)
               write(buffer,'(i3.3)')doy
            else
               _FAIL('Day of Year must be %D3')
            end if
         else
            buffer="%"//token
         end if
      case("h")
         if (.not.skip_token(hour,preserve)) then
            if (c2 == "3") then
               write(buffer,'(i3.3)')hour
            else if (c2 == "2") then
               write(buffer,'(i2.2)')hour
            else if (c1 == "1") then
               if (day < 10) then
                  write(buffer,'(i1)')hour
               else
                  write(buffer,'(i2)')hour
               end if
            end if
         else
            buffer="%"//token
         end if
      case("n")
         if (.not.skip_token(minute,preserve)) then
            write(buffer,'(i2.2)')minute
         else
            buffer="%"//token
         end if
      case("S")
         if (.not.skip_token(second,preserve)) then
            write(buffer,'(i2.2)')second
         else
            buffer="%"//token
         end if
      end select
   end function evaluate_token
Call graph
evaluate_token calls ESMF_CalendarCreate, ESMF_CalendarDestroy, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_verify, skip_token
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
fill_grads_template calls evaluate_token
create_primary_field calls fill_grads_template
find_any_file calls fill_grads_template
get_file calls fill_grads_template
get_filename_from_template calls fill_grads_template
get_filename_from_template_use_index calls fill_grads_template
getclimyear calls fill_grads_template
getlevs calls fill_grads_template
mapl_cfioreadbundle calls fill_grads_template
mapl_genericfinalize calls fill_grads_template
mapl_genericinitialize calls fill_grads_template
mapl_getcurrentfile calls fill_grads_template
mapl_read_bundle calls fill_grads_template
run calls fill_grads_template
strtemplate calls fill_grads_template
updatebrackettime calls fill_grads_template