evaluate_region_mask – MAPL
evaluate_region_mask Subroutine
69 statements
Source File
private subroutine evaluate_region_mask(this, state, field, rc)
Type Bound
StateMask
Arguments
Type Intent Optional Attributes Name
class(StateMask), intent(inout) :: this
type(ESMF_State), intent(inout) :: state
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine evaluate_region_mask(this,state,field,rc)
      class(StateMask), intent(inout) :: this
      type(ESMF_State), intent(inout) :: state
      type(ESMF_Field), intent(inout)   :: field
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: k,i
      character(len=:), allocatable :: maskString,maskname,vartomask
      integer, allocatable :: regionNumbers(:), flag(:)
      integer, allocatable :: mask(:,:)
      real, pointer        :: rmask(:,:)
      real, pointer        :: var2d(:,:)
      real, pointer        :: var3d(:,:,:)
      real, pointer        :: out_var2d(:,:)
      real, pointer        :: out_var3d(:,:,:)
      integer              :: rank,ib,ie
      call ESMF_FieldGet(field,rank=rank,_RC)
       ! get mask string
       ib = index(this%mask_arguments,";")
       maskString = this%mask_arguments(ib+1:)
       ! get mask name
       ie = index(this%mask_arguments,";")
       ib = index(this%mask_arguments,",")
       vartomask = this%mask_arguments(:ib-1)
       maskname = this%mask_arguments(ib+1:ie-1)
       call MAPL_GetPointer(state,rmask,maskName,_RC)
       if (rank == 2) then
          call ESMF_FieldGet(field,0,farrayPtr=out_var2d,_RC)
          call MAPL_GetPointer(state,var2d, vartomask, _RC)
       else if (rank == 3) then
          call ESMF_FieldGet(field,0,farrayPtr=out_var3d,_RC)
          call MAPL_GetPointer(state,var3d, vartomask, _RC)
       else
          _FAIL('Rank must be 2 or 3')
       end if
       k=32
       allocate(regionNumbers(k), flag(k), stat=status)
       _VERIFY(STATUS)
       regionNumbers = 0
       call ExtDataExtractIntegers(maskString,k,regionNumbers,rc=status)
       _VERIFY(STATUS)
       flag(:) = 1
       WHERE(regionNumbers(:) == 0) flag(:) = 0
       k = SUM(flag)
       deallocate(flag,stat=status)
       _VERIFY(STATUS)
   !   Set local mask to 1 where gridMask matches each integer (within precision!)
   !   ---------------------------------------------------------------------------
       allocate(mask(size(rmask,1),size(rmask,2)),stat=status)
       _VERIFY(STATUS)
       mask = 0
       DO i=1,k
        WHERE(regionNumbers(i)-0.01 <= rmask .AND. &
              rmask <= regionNumbers(i)+0.01) mask = 1
       END DO
       if (rank == 2) then
          out_var2d = var2d
          where(mask == 0) out_var2d = 0.0
       else if (rank == 3) then
          out_var3d = var3d
          do i=1,size(var3d,3)
             where(mask == 0) out_var3d(:,:,i) = 0.0
          enddo
       end if
       deallocate( mask)
      _RETURN(_SUCCESS)
   end subroutine evaluate_region_mask
Call graph
evaluate_region_mask calls esmf_fieldget, esmfl_stategetpointertodata, mapl_assert, extdataextractintegers, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
extdataextractintegers calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_stategetptrtodatar4_1 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_allocatecoupling calls mapl_allocatecoupling
evaluate_mask calls evaluate_region_mask
evaluate_derived_field calls evaluate_mask
statefilter_r4_2d calls evaluate_mask
statefilter_r4_3d calls evaluate_mask
test_region_mask_2d calls evaluate_mask
test_region_mask_3d calls evaluate_mask
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run_ calls evaluate_derived_field
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem