evaluate_zone_mask – MAPL
evaluate_zone_mask Subroutine
61 statements
Source File
private subroutine evaluate_zone_mask(this, state, field, rc)
Type Bound
StateMask
Arguments
Type Intent Optional Attributes Name
class(StateMask), intent(inout) :: this
type(ESMF_State), intent(inout) :: state
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine evaluate_zone_mask(this,state,field,rc)
      class(StateMask), intent(inout) :: this
      type(ESMF_State), intent(inout) :: state
      type(ESMF_Field), intent(inout) :: field
      integer, optional, intent(out) :: rc
      integer :: status
       integer :: i
       character(len=:), allocatable :: vartomask,clatS,clatN
       real, pointer        :: var2d(:,:)
       real, pointer        :: var3d(:,:,:)
       real, pointer        :: out_var2d(:,:)
       real, pointer        :: out_var3d(:,:,:)
       real(REAL64), pointer :: lats(:,:)
       real(REAL64)         :: limitS, limitN
       type(ESMF_Grid)      :: grid
       integer              :: rank,ib,is
       type(ESMF_CoordSys_Flag) :: coordSys
       call ESMF_FieldGet(field,rank=rank,grid=grid,_RC)
       ib = index(this%mask_arguments,",")
       vartomask = this%mask_arguments(:ib-1)
       is = index(this%mask_arguments,",",back=.true.)
       clatS = this%mask_arguments(ib+1:is-1)
       clatN = this%mask_arguments(is+1:)
       READ(clatS,*,IOSTAT=status) limitS
       _VERIFY(status)
       READ(clatN,*,IOSTAT=status) limitN
       _VERIFY(status)
       call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lats, rc=status)
       _VERIFY(status)
       call ESMF_GridGet(grid,coordsys=coordsys,_RC)
       if (coordsys == ESMF_COORDSYS_SPH_RAD) then
          limitN=limitN*MAPL_PI_R8/180.0d0
          limitS=limitS*MAPL_PI_R8/180.0d0
       end if
       if (rank == 2) then
          call ESMF_FieldGet(field,0,farrayPtr=out_var2d,_RC)
          call MAPL_GetPointer(state,var2d, vartomask, _RC)
       else if (rank == 3) then
          call ESMF_FieldGet(field,0,farrayPtr=out_var3d,_RC)
          call MAPL_GetPointer(state,var3d, vartomask, _RC)
       else
          _FAIL('Rank must be 2 or 3')
       end if
       if (rank == 2) then
          out_var2d = 0.0
          where(limitS <= lats .and. lats <=limitN) out_var2d = var2d
       else if (rank == 3) then
          out_var3d = 0.0
          do i=1,size(var3d,3)
             where(limitS <= lats .and. lats <=limitN) out_var3d(:,:,i) = var3d(:,:,i)
          enddo
       end if
      _RETURN(_SUCCESS)
   end subroutine evaluate_zone_mask
Call graph
evaluate_zone_mask calls ESMF_GridGet, ESMF_GridGetCoord, esmf_fieldget, esmfl_stategetpointertodata, mapl_assert, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_stategetptrtodatar4_1 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls esmf_fieldget, mapl_return, mapl_verify, esmf_stateget, mapl_allocatecoupling
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_allocatecoupling calls mapl_allocatecoupling
evaluate_mask calls evaluate_zone_mask
evaluate_derived_field calls evaluate_mask
statefilter_r4_2d calls evaluate_mask
statefilter_r4_3d calls evaluate_mask
test_region_mask_2d calls evaluate_mask
test_region_mask_3d calls evaluate_mask
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run_ calls evaluate_derived_field
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem