evaluate_box_mask – MAPL
evaluate_box_mask Subroutine
145 statements
Source File
private subroutine evaluate_box_mask(this, state, field, rc)
Type Bound
StateMask
Arguments
Type Intent Optional Attributes Name
class(StateMask), intent(inout) :: this
type(ESMF_State), intent(inout) :: state
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine evaluate_box_mask(this,state,field,rc)
      class(StateMask), intent(inout) :: this
      type(ESMF_State), intent(inout) :: state
      type(ESMF_Field), intent(inout)   :: field
      integer, optional, intent(out) :: rc
      integer :: status
       integer :: i
       character(len=:), allocatable :: vartomask,strtmp
       real, pointer        :: out_var2d(:,:)
       real, pointer        :: out_var3d(:,:,:)
       real, pointer        :: var2d(:,:)
       real, pointer        :: var3d(:,:,:)
       real(REAL64), pointer :: lats(:,:)
       real(REAL64), pointer :: lons(:,:)
       real(REAL64)         :: limitS, limitN, limitE, limitW
       real(REAL64)         :: limitE1, limitW1
       real(REAL64)         :: limitE2, limitW2
       type(ESMF_Grid)      :: grid
       integer              :: rank,is,nargs
       integer              :: counts(3)
       logical              :: isCube, twoBox
       real, allocatable    :: temp2d(:,:)
       character(len=ESMF_MAXSTR) :: args(5)
       type(ESMF_CoordSys_Flag) :: coordSys
       call ESMF_FieldGet(field,rank=rank,grid=grid,_RC)
       call ESMF_GridGet(grid,coordsys=coordsys,_RC)
       strtmp = this%mask_arguments
       do nargs=1,5
          is = index(strtmp,',')
          if (is >0) then
             args(nargs) = strtmp(:is-1)
          else
             args(nargs) = strtmp
          end if
          strtmp = strtmp(is+1:)
       end do
       varToMask=args(1)
       READ(args(2),*,IOSTAT=status) limitS
       _VERIFY(status)
       READ(args(3),*,IOSTAT=status) limitN
       _VERIFY(status)
       READ(args(4),*,IOSTAT=status) limitW
       _VERIFY(status)
       READ(args(5),*,IOSTAT=status) limitE
       _VERIFY(status)
       _ASSERT(limitE > limitW,'LimitE must be greater than limitW')
       _ASSERT(limitE /= limitW,'LimitE cannot equal limitW')
       _ASSERT(limitN /= limitS,'LimitN cannot equal LimitS')
       _ASSERT((limitE-limitW)<=360.0d0,'(LimitE - LimitW) must be less than or equal to 360')
       call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lons, rc=status)
       _VERIFY(status)
       call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lats, rc=status)
       _VERIFY(status)
       ! do some tests if cube goes from 0 to 360, lat-lon -180 to 180
       call MAPL_GridGet(grid, globalCellCountPerDim=COUNTS,rc=status)
       _VERIFY(STATUS)
       if (counts(2)==6*counts(1)) then
          isCube=.true.
       else
          isCube=.false.
       end if
       twoBox = .false.
       if (isCube) then
          if (limitW < 0.0d0 .and. limitE >=0.0d0) then
             ! need two boxes
             twoBox=.true.
             limitW1=0.0d0
             limitE1=limitE
             limitW2=limitW+360.0d0
             limitE2=360.0d0
          else if (limitW <0.0d0 .and. limitE <0.0d0) then
             ! just shift
             limitW1=limitW+360.d0
             limitE1=limitE+360.d0
          else
             ! normal case
             limitW1=limitW
             limitE1=limitE
          end if
       else
          if (limitW  <= 180.0d0 .and. limitE > 180.0d0) then
             ! need two boxes
             twoBox=.true.
             limitW1=limitW
             limitE1=180.0d0
             limitW2=-180.d0
             limitE2=limitE-360.0d0
          else if (limitW > 180.0d0 .and. limitE > 180.0d0) then
             ! just shift
             limitW1=limitW-360.d0
             limitE1=limitE-360.d0
          else
             ! normal case
             limitW1=limitW
             limitE1=limitE
          end if
       end if
       if (coordSys == ESMF_COORDSYS_SPH_RAD) then
          limitE1=limitE1*MAPL_PI_R8/180.0d0
          limitW1=limitW1*MAPL_PI_R8/180.0d0
          if (twoBox) then
             limitE2=limitE2*MAPL_PI_R8/180.0d0
             limitW2=limitW2*MAPL_PI_R8/180.0d0
          end if
          limitN=limitN*MAPL_PI_R8/180.0d0
          limitS=limitS*MAPL_PI_R8/180.0d0
       end if
       if (rank == 2) then
          call ESMF_FieldGet(field,0,farrayPtr=out_var2d,_RC)
          call MAPL_GetPointer(state,var2d, vartomask, _RC)
       else if (rank == 3) then
          call ESMF_FieldGet(field,0,farrayPtr=out_var3d,_RC)
          call MAPL_GetPointer(state,var3d, vartomask, _RC)
       else
          _FAIL('Rank must be 2 or 3')
       end if
       if (rank == 2) then
          out_var2d = 0.0
          where(limitS <= lats .and. lats <=limitN .and. limitW1 <= lons .and. lons <= limitE1 ) out_var2d = var2d
       else if (rank == 3) then
          out_var3d = 0.0
          do i=1,size(var3d,3)
             where(limitS <= lats .and. lats <=limitN .and. limitW1 <= lons .and. lons <= limitE1 ) out_var3d(:,:,i) = var3d(:,:,i)
          enddo
       end if
       if (twoBox) then
          allocate(temp2d(size(var2d,1),size(var2d,2)),stat=status)
          _VERIFY(STATUS)
          if (rank == 2) then
             out_var2d = 0.0
             temp2d = 0.0
             where(limitS <= lats .and. lats <=limitN .and. limitW2 <= lons .and. lons <= limitE2 ) temp2d = var2d
             out_var2d=out_var2d+temp2d
          else if (rank == 3) then
             out_var3d = 0.0
             do i=1,size(var3d,3)
                temp2d = 0.0
                where(limitS <= lats .and. lats <=limitN .and. limitW2 <= lons .and. lons <= limitE2 ) temp2d = var3d(:,:,i)
                out_var3d(:,:,i)=out_var3d(:,:,i)+temp2d
             enddo
          end if
          deallocate(temp2d)
       end if
       _RETURN(_SUCCESS)
  end subroutine evaluate_box_mask
Call graph
evaluate_box_mask calls ESMF_GridGet, ESMF_GridGetCoord, esmf_fieldget, esmfl_stategetpointertodata, mapl_assert, mapl_gridget, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_DistGridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evaluate_mask calls evaluate_box_mask
evaluate_derived_field calls evaluate_mask
statefilter_r4_2d calls evaluate_mask
statefilter_r4_3d calls evaluate_mask
test_region_mask_2d calls evaluate_mask
test_region_mask_3d calls evaluate_mask
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run_ calls evaluate_derived_field
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem