evalf – MAPL
evalf Subroutine
49 statements
Source File
private subroutine evalf(Comp, state, FieldNames, ResField, rc)
Arguments
Type Intent Optional Attributes Name
type(tComp), intent(inout) :: Comp
type(ESMF_State), intent(in) :: state
character(len=ESMF_MAXSTR), intent(in) :: FieldNames(:)
type(ESMF_Field), intent(inout) :: ResField
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
evalf
Source Code
  SUBROUTINE evalf (Comp, State, FieldNames, ResField, rc)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Evaluate bytecode of ith function for the values passed in array Val(:)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    TYPE (tComp),                   INTENT(inout) :: Comp
    TYPE(ESMF_State),               INTENT(in   ) :: state
    CHARACTER(len=ESMF_MAXSTR)    , INTENT(in   ) :: FieldNames(:)
    TYPE(ESMF_Field),               INTENT(inout) :: ResField
    INTEGER, OPTIONAL,              INTENT(out  ) :: rc
    INTEGER                            :: IP,              & ! Instruction pointer
                                          DP,              & ! Data pointer
                                          SP                 ! Stack pointer
    INTEGER                            :: CurrByte,ValNumber
    TYPE(ESMF_Field)                   :: state_field
    character(len=ESMF_MAXSTR), parameter :: Iam="evalf"
    integer :: status
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    DP = 1
    SP = 0
    DO IP=1,Comp%ByteCodeSize
       CurrByte = Comp%ByteCode(IP)
       if (CurrByte == cImmed) then
          SP=SP+1
          call CopyScalarToField(Comp%Stack(SP),Comp%Immed(DP),rc=status)
          _VERIFY(STATUS)
          DP=DP+1
       end if
       if (CurrByte == cNeg) then
          call UnaryFuncField(Comp%Stack(SP),CurrByte,rc=status)
          _VERIFY(STATUS)
       end if
       if (CurrByte >= cAdd .and. CurrByte <= cPow) then
          call ArthFieldToField(Comp%Stack(SP),Comp%Stack(SP-1),CurrByte,rc=status)
          _VERIFY(STATUS)
          SP=SP-1
       end if
       if (CurrByte >= cAbs .and. CurrByte <= cHeav) then
          call UnaryFuncField(Comp%Stack(SP),CurrByte,rc=status)
          _VERIFY(STATUS)
       end if
       if (CurrByte > cHeav) then
          SP=SP+1
          ValNumber = CurrByte-VarBegin+1
          call ESMF_StateGet(state,FieldNames(ValNumber),state_field,rc=status)
          _VERIFY(STATUS)
          call CopyFieldToPtr(state_field,Comp%Stack(SP),rc=status)
          _VERIFY(STATUS)
       end if
    END DO
    call CopyPtrToField(Comp%Stack(1),ResField,rc=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE evalf
Call graph
evalf calls copyscalartofield, mapl_verify, esmf_stateget, arthfieldtofield, unaryfuncfield, copyfieldtoptr, copyptrtofield, mapl_return
copyscalartofield calls mapl_return
mapl_verify calls mapl_throw_exception
arthfieldtofield calls mapl_return
unaryfuncfield calls mapl_return, heav3d, heav2d
copyfieldtoptr calls mapl_verify, mapl_return, esmf_arrayget, esmf_fieldget
copyptrtofield calls mapl_verify, mapl_return, esmf_arrayget, esmf_fieldget
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_stateeval calls evalf
mapl_runexpression calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
calcderivedfield calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
run calls mapl_runexpression
run_ calls fillstate, calcderivedfield