exists – MAPL
exists Function
4 statements
Source File
private function exists(pos)
Arguments
Type Intent Optional Attributes Name
integer(kind=SIZE_KIND), intent(in) :: pos
Return Value logical
Called by
Call graph
advpos calls exists
erase_nonleaf calls exists, advpos, rebalance
find_index calls exists
rebalance calls exists, rot, update_height
rot calls exists, update_height
s_count calls exists, s_find
s_empty calls exists
s_erase_multi calls exists, erase_nonleaf, rebalance
s_find calls exists, find_index
s_insert calls exists, find_index, rebalance
update_height calls exists
m_empty calls s_empty
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
s_next calls advpos
s_prev calls advpos
s_remove calls s_find