exists – MAPL
exists Function
4 statements
Source File
private function exists(pos)
Arguments
Type Intent Optional Attributes Name
integer(kind=SIZE_KIND), intent(in) :: pos
Return Value logical
Called by
Contents
Call graph
advpos calls exists
erase_nonleaf calls exists, advpos, rebalance
find_index calls exists
rebalance calls exists, rot, update_height
rot calls exists, update_height
s_count calls exists
s_empty calls exists
s_erase_multi calls exists, erase_nonleaf, rebalance
s_find calls exists, find_index
s_insert calls exists, find_index, rebalance
update_height calls exists