ExternalGridFactory_from_parameters – MAPL
ExternalGridFactory_from_parameters Function
17 statements
Source File
private function ExternalGridFactory_from_parameters(unusable, grid_name, grid, lm, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
type(ESMF_Grid), intent(in), optional :: grid
integer, intent(in), optional :: lm
integer, intent(out), optional :: rc
Return Value type(ExternalGridFactory)
Calls
Called by
Source Code
   function ExternalGridFactory_from_parameters(unusable, grid_name, grid, lm, rc) result(factory)
      type(ExternalGridFactory) :: factory
      class(KeywordEnforcer), optional, intent(in   ) :: unusable
      character(*),           optional, intent(in   ) :: grid_name
      type(ESMF_Grid),        optional, intent(in   ) :: grid
      integer,                optional, intent(in   ) :: lm
      integer,                optional, intent(  out) :: rc
      if (present(grid_name)) factory%grid_name = grid_name
      if (present(grid)) factory%external_grid = grid
      if (present(grid)) factory%lm = lm
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function ExternalGridFactory_from_parameters
Call graph
externalgridfactory_from_parameters calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
externalgridfactory calls externalgridfactory_from_parameters