extract_ – MAPL
extract_ Subroutine
35 statements
Source File
private subroutine extract_(GC, CLOCK, self, GRID, CF, Time, nymd, nhms, TimeInterval, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_Clock), intent(in) :: CLOCK
type(Orb_State), pointer :: self
type(ESMF_Grid), intent(out) :: GRID
type(ESMF_Config), intent(out) :: CF
type(ESMF_Time), intent(out) :: Time
integer, intent(out) :: nymd
integer, intent(out) :: nhms
type(ESMF_TimeInterval), intent(out) :: TimeInterval
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine extract_ ( GC, CLOCK, self, GRID, CF, time, nymd, nhms, timeinterval, rc)
    type(ESMF_GridComp), intent(INout)  :: GC           ! Grid Comp object
    type(ESMF_Clock), intent(in)        :: CLOCK        ! Clock
    type(Orb_state), pointer           :: self         ! Legacy state
    type(ESMF_Grid),     intent(out)    :: GRID         ! Grid
    type(ESMF_Config),   intent(out)    :: CF           ! Universal Config
    type(ESMF_TIME), intent(out)        :: Time         ! Time
    type(ESMF_TimeInterval), intent(out) :: TimeInterval ! Time Intervale
    integer, intent(out)                :: nymd, nhms   ! date, time
    integer, intent(out), optional      :: rc
!                                      ---
    character(len=ESMF_MAXSTR) :: comp_name
                                 _Iam_('extract_')
    type(Orb_Wrap)               :: wrap
    integer                       :: iyr, imm, idd, ihr, imn, isc
    integer                       :: status
!   Get my name and set-up traceback handle
!   ---------------------------------------
    call ESMF_GridCompGet( GC, NAME=comp_name, _RC )
    Iam = trim(COMP_NAME) // '::extract_'
    rc = 0
!   Get my internal state
!   ---------------------
    call ESMF_UserCompGetInternalState(gc, 'Orb_state', WRAP, STATUS)
    _VERIFY(STATUS)
    self => wrap%ptr
!   Get the configuration
!   ---------------------
    call ESMF_GridCompGet ( GC, config=CF, _RC )
!   Extract time as simple integers from clock
!   ------------------------------------------
    call ESMF_ClockGet(CLOCK,currTIME=TIME,timeStep=TimeInterval,_RC)
    call ESMF_TimeGet(TIME ,yy=iyr, mm=imm, dd=idd, h=ihr, m=imn, s=isc, _RC)
    call MAPL_PackTime(nymd,iyr,imm,idd)
    call MAPL_PackTime(nhms,ihr,imn,isc)
!   Extract the ESMF Grid
!   ---------------------
    call ESMF_GridCompGet ( GC, grid=GRID, _RC)
    _RETURN(ESMF_SUCCESS)
   end subroutine extract_
Call graph
extract_ calls ESMF_ClockGet, ESMF_GridCompGet, ESMF_TimeGet, ESMF_UserCompGetInternalState, mapl_packtime, mapl_return, mapl_verify
mapl_packtime calls mapl_packtime
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_ calls extract_