extract_ISO8601_from_CF_Time_cf_time – MAPL
extract_ISO8601_from_CF_Time_cf_time Subroutine
12 statements
Source File
private subroutine extract_ISO8601_from_CF_Time_cf_time(cft, isostring, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time), intent(in) :: cft
character(len=MAX_CHARACTER_LENGTH), intent(out) :: isostring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine extract_ISO8601_from_CF_Time_cf_time(cft, isostring, rc)
      class(CF_Time), intent(in) :: cft
      character(len=MAX_CHARACTER_LENGTH), intent(out) :: isostring
      integer, optional, intent(out) :: rc
      if(cft % is_valid) then
         isostring = convert_CF_Time_datetime_string_to_ISO8601(cft % base_datetime)
         _RETURN(_SUCCESS)
      end if
      _RETURN(_FAILURE)
   end subroutine extract_ISO8601_from_CF_Time_cf_time
Call graph
extract_iso8601_from_cf_time_cf_time calls convert_cf_time_datetime_string_to_iso8601, mapl_return
convert_cf_time_datetime_string_to_iso8601 calls split, zero_pad
mapl_return calls get_error_message, mapl_throw_exception
split calls split_characters
get_error_message calls at, insert
mapl_throw_exception calls initialize
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time, extract_iso8601_from_cf_time_units
extract_iso8601_from_cf_time_units calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_integer calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_real calls extract_iso8601_from_cf_time
test_extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_real_to_esmf calls convert_netcdf_datetime_to_esmf