extract_CF_Time_unit_units – MAPL
extract_CF_Time_unit_units Subroutine
10 statements
Source File
private subroutine extract_CF_Time_unit_units(units, time_unit, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: units
character(len=MAX_CHARACTER_LENGTH), intent(out) :: time_unit
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine extract_CF_Time_unit_units(units, time_unit, rc)
      character(len=*), intent(in) :: units
      character(len=MAX_CHARACTER_LENGTH), intent(out) :: time_unit
      integer, optional, intent(out) :: rc
      integer :: status
      call extract_CF_Time_unit(CF_Time_Integer(0, units), time_unit, _RC)
      _RETURN(_SUCCESS)
   end subroutine extract_CF_Time_unit_units
Call graph
extract_cf_time_unit_units calls extract_cf_time_unit, mapl_return, mapl_verify
extract_cf_time_unit calls extract_cf_time_unit_units, extract_cf_time_unit_cf_time
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
extract_cf_time_unit_cf_time calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_esmf_time_from_netcdf_datetime_integer calls extract_cf_time_unit
get_esmf_time_from_netcdf_datetime_real calls extract_cf_time_unit
test_extract_cf_time_unit calls extract_cf_time_unit
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf