extract_CF_Time_duration_cf_time_real – MAPL
extract_CF_Time_duration_cf_time_real Subroutine
12 statements
Source File
private subroutine extract_CF_Time_duration_cf_time_real(cft, duration, rc)
Arguments
Type Intent Optional Attributes Name
class(CF_Time_Real), intent(in) :: cft
real(kind=R64), intent(out) :: duration
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine extract_CF_Time_duration_cf_time_real(cft, duration, rc)
      class(CF_Time_Real), intent(in) :: cft
      real(kind=R64), intent(out) :: duration
      integer, optional, intent(out) :: rc
      if(cft % is_valid) then
         duration = cft % duration
         _RETURN(_SUCCESS)
      end if
      _RETURN(_FAILURE)
   end subroutine extract_CF_Time_duration_cf_time_real
Call graph
extract_cf_time_duration_cf_time_real calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
extract_cf_time_duration calls extract_cf_time_duration_cf_time_real