extract_ – MAPL
extract_ Subroutine
22 statements
Source File
private subroutine extract_(GC, self, CF, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_ExtData_State), pointer :: self
type(ESMF_Config), intent(out) :: CF
integer, intent(out), optional :: rc
Calls
Called by
Source Code
 subroutine extract_ ( GC, self, CF, rc)
    type(ESMF_GridComp), intent(INout)  :: GC           ! Grid Comp object
    type(MAPL_ExtData_state), pointer   :: self         ! Legacy state
    type(ESMF_Config),   intent(out)    :: CF           ! Universal Config
    integer, intent(out), optional      :: rc
!                            ---
    character(len=ESMF_MAXSTR) :: comp_name
    character(len=ESMF_MAXSTR) :: Iam
    integer                    :: status
    type(MAPL_ExtData_Wrap)  :: wrap
!   Get my name and set-up traceback handle
!   ---------------------------------------
    Iam = 'extract_'
    call ESMF_GridCompGet( GC, NAME=comp_name, _RC )
    Iam = trim(COMP_NAME) // '::' // trim(Iam)
    If (present(rc))  rc=ESMF_SUCCESS
!   Get my internal state
!   ---------------------
    call ESMF_UserCompGetInternalState(gc, 'MAPL_ExtData_state', WRAP, STATUS)
    _VERIFY(STATUS)
    self => wrap%ptr
!   Get the configuration
!   ---------------------
    call ESMF_GridCompGet ( GC, config=CF, _RC )
    _RETURN(ESMF_SUCCESS)
  end subroutine extract_
Call graph
extract_ calls ESMF_GridCompGet, ESMF_UserCompGetInternalState, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
finalize_ calls extract_
initialize_ calls extract_
run_ calls extract_