extract_ISO8601_from_CF_Time_units – MAPL
extract_ISO8601_from_CF_Time_units Subroutine
10 statements
Source File
private subroutine extract_ISO8601_from_CF_Time_units(units, isostring, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: units
character(len=MAX_CHARACTER_LENGTH), intent(out) :: isostring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine extract_ISO8601_from_CF_Time_units(units, isostring, rc)
      character(len=*), intent(in) :: units
      character(len=MAX_CHARACTER_LENGTH), intent(out) :: isostring
      integer, optional, intent(out) :: rc
      integer :: status
      call extract_ISO8601_from_CF_Time(CF_Time_Integer(0, units), isostring, _RC)
      _RETURN(_SUCCESS)
   end subroutine extract_ISO8601_from_CF_Time_units
Call graph
extract_iso8601_from_cf_time_units calls extract_iso8601_from_cf_time, mapl_return, mapl_verify
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_units, extract_iso8601_from_cf_time_cf_time
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
extract_iso8601_from_cf_time_cf_time calls mapl_return, convert_cf_time_datetime_string_to_iso8601
get_error_message calls at, insert
mapl_throw_exception calls initialize
convert_cf_time_datetime_string_to_iso8601 calls split, zero_pad
get_esmf_time_from_netcdf_datetime_integer calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_real calls extract_iso8601_from_cf_time
test_extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf