fence – MAPL
fence Subroutine
7 statements
Source File
private subroutine fence(this, rc)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Contents
Source Code
fence
Source Code
   subroutine fence(this, rc)
     class(AbstractDataReference),intent(inout) :: this
     integer, optional, intent(out) :: rc
     !print*, "WARNNING: should fence in the sub class"
     _RETURN(_SUCCESS)
     _UNUSED_DUMMY(this)
   end subroutine fence
Call graph
fence calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize