fence – MAPL
fence Subroutine
10 statements
Source File
private subroutine fence(this, rc)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine fence(this, rc)
     class(AbstractDataReference),intent(inout) :: this
     integer, optional, intent(out) :: rc
     !print*, "WARNNING: should fence in the sub class"
     _RETURN(_SUCCESS)
     _UNUSED_DUMMY(this)
   end subroutine fence
Call graph
fence calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
read_and_gather calls fence
read_and_share calls fence
receive_output_data calls fence
handle_done_collective_prefetch calls read_and_gather, read_and_share
start calls receive_output_data