fetch_data – MAPL
fetch_data Subroutine
234 statements
Source File
private subroutine fetch_data(this, offset_address, global_shape, offset_start, rc)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(in), target :: this
type(c_ptr), intent(in) :: offset_address
integer, intent(in) :: global_shape(:)
integer, intent(in), optional :: offset_start(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine fetch_data(this,offset_address,global_shape,offset_start, rc)
      class(AbstractDataReference),target,intent(in)    :: this
      type(c_ptr),intent(in)       :: offset_address
      integer,intent(in)           :: global_shape(:)
      integer,optional,intent(in)  :: offset_start(:)
      integer, optional, intent(out) :: rc
      integer :: s1,e1, s2,e2,s3,e3,s4,e4,s5,e5
      integer(kind=INT32), pointer :: values_int32_0d
      real(kind=REAL32),   pointer :: values_real32_0d
      integer(kind=INT32), pointer :: all_int32_0d
      real(kind=REAL32),   pointer :: all_real32_0d
      integer(kind=INT32), pointer :: values_int32_1d(:)
      real(kind=REAL32),   pointer :: values_real32_1d(:)
      integer(kind=INT32), pointer :: all_int32_1d(:)
      real(kind=REAL32),   pointer :: all_real32_1d(:)
      integer(kind=INT32), pointer :: values_int32_2d(:,:)
      real(kind=REAL32),   pointer :: values_real32_2d(:,:)
      integer(kind=INT32), pointer :: all_int32_2d(:,:)
      real(kind=REAL32),   pointer :: all_real32_2d(:,:)
      integer(kind=INT32), pointer :: values_int32_3d(:,:,:)
      real(kind=REAL32),   pointer :: values_real32_3d(:,:,:)
      integer(kind=INT32), pointer :: all_int32_3d(:,:,:)
      real(kind=REAL32),   pointer :: all_real32_3d(:,:,:)
      integer(kind=INT32), pointer :: values_int32_4d(:,:,:,:)
      real(kind=REAL32),   pointer :: values_real32_4d(:,:,:,:)
      integer(kind=INT32), pointer :: all_int32_4d(:,:,:,:)
      real(kind=REAL32),   pointer :: all_real32_4d(:,:,:,:)
      integer(kind=INT32), pointer :: values_int32_5d(:,:,:,:,:)
      real(kind=REAL32),   pointer :: values_real32_5d(:,:,:,:,:)
      integer(kind=INT32), pointer :: all_int32_5d(:,:,:,:,:)
      real(kind=REAL32),   pointer :: all_real32_5d(:,:,:,:,:)
      integer(kind=INT64), pointer :: values_int64_0d
      real(kind=REAL64),   pointer :: values_real64_0d
      integer(kind=INT64), pointer :: all_int64_0d
      real(kind=REAL64),   pointer :: all_real64_0d
      integer(kind=INT64), pointer :: values_int64_1d(:)
      real(kind=REAL64),   pointer :: values_real64_1d(:)
      integer(kind=INT64), pointer :: all_int64_1d(:)
      real(kind=REAL64),   pointer :: all_real64_1d(:)
      integer(kind=INT64), pointer :: values_int64_2d(:,:)
      real(kind=REAL64),   pointer :: values_real64_2d(:,:)
      integer(kind=INT64), pointer :: all_int64_2d(:,:)
      real(kind=REAL64),   pointer :: all_real64_2d(:,:)
      integer(kind=INT64), pointer :: values_int64_3d(:,:,:)
      real(kind=REAL64),   pointer :: values_real64_3d(:,:,:)
      integer(kind=INT64), pointer :: all_int64_3d(:,:,:)
      real(kind=REAL64),   pointer :: all_real64_3d(:,:,:)
      integer(kind=INT64), pointer :: values_int64_4d(:,:,:,:)
      real(kind=REAL64),   pointer :: values_real64_4d(:,:,:,:)
      integer(kind=INT64), pointer :: all_int64_4d(:,:,:,:)
      real(kind=REAL64),   pointer :: all_real64_4d(:,:,:,:)
      integer(kind=INT64), pointer :: values_int64_5d(:,:,:,:,:)
      real(kind=REAL64),   pointer :: values_real64_5d(:,:,:,:,:)
      integer(kind=INT64), pointer :: all_int64_5d(:,:,:,:,:)
      real(kind=REAL64),   pointer :: all_real64_5d(:,:,:,:,:)
      integer,allocatable :: count(:),start(:)
      integer :: full_rank
      _RETURN_UNLESS(C_ASSOCIATED(this%base_address))
      full_rank = size(global_shape)
      if(size(this%shape) > full_rank) then
        _FAIL("ranks do not agree (probably fixable)")
      endif
      allocate(count(full_rank))
      allocate(start(full_rank))
      ! Pad any extra dimensions with 1's
      count(1:full_rank) = 1
      count(1:size(this%shape)) = this%shape
      start(1:full_rank) = 1
      if(present(offset_start)) then
         start(1:size(offset_start))=offset_start
      endif
      select case (size(global_shape))
         case(0) ! scalar
            select case (this%type_kind)
            case(pFIO_INT32)
               call c_f_pointer(this%base_address,values_int32_0d)
               call c_f_pointer(offset_address, all_int32_0d)
               values_int32_0d=all_int32_0d
            case(pFIO_REAL32)
               call c_f_pointer(this%base_address,values_real32_0d)
               call c_f_pointer(offset_address, all_real32_0d)
               values_real32_0d=all_real32_0d
            case(pFIO_INT64)
               call c_f_pointer(this%base_address,values_int64_0d)
               call c_f_pointer(offset_address, all_int64_0d)
               values_int64_0d=all_int64_0d
            case(pFIO_REAL64)
               call c_f_pointer(this%base_address,values_real64_0d)
               call c_f_pointer(offset_address, all_real64_0d)
               values_real64_0d=all_real64_0d
            case default
               _FAIL("type not supported yet")
            end select
         case(1)
            s1=start(1)
            e1=start(1)+count(1)-1
            select case (this%type_kind)
            case(pFIO_INT32)
               call c_f_pointer(this%base_address,values_int32_1d,count)
               call c_f_pointer(offset_address, all_int32_1d,   global_shape)
               values_int32_1d=all_int32_1d(s1:e1)
            case(pFIO_REAL32)
               call c_f_pointer(this%base_address,values_real32_1d,count)
               call c_f_pointer(offset_address, all_real32_1d,   global_shape)
               values_real32_1d=all_real32_1d(s1:e1)
            case(pFIO_INT64)
               call c_f_pointer(this%base_address,values_int64_1d,count)
               call c_f_pointer(offset_address, all_int64_1d,   global_shape)
               values_int64_1d=all_int64_1d(s1:e1)
            case(pFIO_REAL64)
               call c_f_pointer(this%base_address,values_real64_1d,count)
               call c_f_pointer(offset_address, all_real64_1d,   global_shape)
               values_real64_1d=all_real64_1d(s1:e1)
            case default
               _FAIL("type not supported yet")
            end select
        case(2)
            s1=start(1)
            e1=start(1)+count(1)-1
            s2=start(2)
            e2=start(2)+count(2)-1
            select case (this%type_kind)
            case(pFIO_INT32)
               call c_f_pointer(this%base_address,values_int32_2d,count)
               call c_f_pointer(offset_address, all_int32_2d,   global_shape)
               values_int32_2d=all_int32_2d(s1:e1,s2:e2)
            case(pFIO_REAL32)
               call c_f_pointer(this%base_address,values_real32_2d,count)
               call c_f_pointer(offset_address, all_real32_2d,   global_shape)
               values_real32_2d=all_real32_2d(s1:e1,s2:e2)
            case(pFIO_INT64)
               call c_f_pointer(this%base_address,values_int64_2d,count)
               call c_f_pointer(offset_address, all_int64_2d,   global_shape)
               values_int64_2d=all_int64_2d(s1:e1,s2:e2)
            case(pFIO_REAL64)
               call c_f_pointer(this%base_address,values_real64_2d,count)
               call c_f_pointer(offset_address, all_real64_2d,   global_shape)
               values_real64_2d=all_real64_2d(s1:e1,s2:e2)
            case default
               _FAIL("type not supported yet")
            end select
        case (3)
            s1=start(1)
            e1=start(1)+count(1)-1
            s2=start(2)
            e2=start(2)+count(2)-1
            s3=start(3)
            e3=start(3)+count(3)-1
            select case (this%type_kind)
            case(pFIO_INT32)
               call c_f_pointer(this%base_address,values_int32_3d,count)
               call c_f_pointer(offset_address, all_int32_3d,   global_shape)
               values_int32_3d=all_int32_3d(s1:e1,s2:e2,s3:e3)
            case(pFIO_REAL32)
               call c_f_pointer(this%base_address,values_real32_3d,count)
               call c_f_pointer(offset_address, all_real32_3d,   global_shape)
               values_real32_3d=all_real32_3d(s1:e1,s2:e2,s3:e3)
            case(pFIO_INT64)
               call c_f_pointer(this%base_address,values_int64_3d,count)
               call c_f_pointer(offset_address, all_int64_3d,   global_shape)
               values_int64_3d=all_int64_3d(s1:e1,s2:e2,s3:e3)
            case(pFIO_REAL64)
               call c_f_pointer(this%base_address,values_real64_3d,count)
               call c_f_pointer(offset_address, all_real64_3d,   global_shape)
               values_real64_3d=all_real64_3d(s1:e1,s2:e2,s3:e3)
            case default
               _FAIL("type not supported yet")
            end select
        case (4)
            s1=start(1)
            e1=start(1)+count(1)-1
            s2=start(2)
            e2=start(2)+count(2)-1
            s3=start(3)
            e3=start(3)+count(3)-1
            s4=start(4)
            e4=start(4)+count(4)-1
            select case (this%type_kind)
            case(pFIO_INT32)
               call c_f_pointer(this%base_address,values_int32_4d,count)
               call c_f_pointer(offset_address, all_int32_4d,   global_shape)
               values_int32_4d=all_int32_4d(s1:e1,s2:e2,s3:e3,s4:e4)
            case(pFIO_REAL32)
               call c_f_pointer(this%base_address,values_real32_4d,count)
               call c_f_pointer(offset_address, all_real32_4d,   global_shape)
               values_real32_4d=all_real32_4d(s1:e1,s2:e2,s3:e3,s4:e4)
            case(pFIO_INT64)
               call c_f_pointer(this%base_address,values_int64_4d,count)
               call c_f_pointer(offset_address, all_int64_4d,   global_shape)
               values_int64_4d=all_int64_4d(s1:e1,s2:e2,s3:e3,s4:e4)
            case(pFIO_REAL64)
               call c_f_pointer(this%base_address,values_real64_4d,count)
               call c_f_pointer(offset_address, all_real64_4d,   global_shape)
               values_real64_4d=all_real64_4d(s1:e1,s2:e2,s3:e3,s4:e4)
            case default
               _FAIL("type not supported yet")
            end select
        case (5)
            s1=start(1)
            e1=start(1)+count(1)-1
            s2=start(2)
            e2=start(2)+count(2)-1
            s3=start(3)
            e3=start(3)+count(3)-1
            s4=start(4)
            e4=start(4)+count(4)-1
            s5=start(5)
            e5=start(5)+count(5)-1
            select case (this%type_kind)
            case(pFIO_INT32)
               call c_f_pointer(this%base_address,values_int32_5d,count)
               call c_f_pointer(offset_address, all_int32_5d,   global_shape)
               values_int32_5d=all_int32_5d(s1:e1,s2:e2,s3:e3,s4:e4,s5:e5)
            case(pFIO_REAL32)
               call c_f_pointer(this%base_address,values_real32_5d,count)
               call c_f_pointer(offset_address, all_real32_5d,   global_shape)
               values_real32_5d=all_real32_5d(s1:e1,s2:e2,s3:e3,s4:e4,s5:e5)
            case(pFIO_INT64)
               call c_f_pointer(this%base_address,values_int64_5d,count)
               call c_f_pointer(offset_address, all_int64_5d,   global_shape)
               values_int64_5d=all_int64_5d(s1:e1,s2:e2,s3:e3,s4:e4,s5:e5)
            case(pFIO_REAL64)
               call c_f_pointer(this%base_address,values_real64_5d,count)
               call c_f_pointer(offset_address, all_real64_5d,   global_shape)
               values_real64_5d=all_real64_5d(s1:e1,s2:e2,s3:e3,s4:e4,s5:e5)
            case default
               _FAIL("type not supported yet")
            end select
         case default
            _FAIL("dimension not supported yet")
      end select
   end subroutine fetch_data
Call graph
fetch_data calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_datafrommem calls fetch_data, get_datafrommem