fglob – MAPL
fglob Subroutine
18 statements
Source File
public subroutine fglob(search_name, filename, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: search_name
character(len=*), intent(inout) :: filename
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine fglob(search_name, filename, rc)     ! give the last name
    character(len=*), intent(in) ::  search_name
    character(len=*), intent(INOUT) :: filename
    integer, optional, intent(out)  :: rc
    character(kind=C_CHAR, len=:), allocatable :: c_search_name
    character(kind=C_CHAR, len=512) :: c_filename
    integer :: slen, lenmax
    c_search_name = trim(search_name)//C_NULL_CHAR
    rc = f_call_c_glob(c_search_name, c_filename, slen)
    filename=""
    lenmax = len(filename)
    if (lenmax < slen) then
       if (MAPL_AM_I_ROOT())  write(6,*) 'pathlen vs filename_max_char_len: ', slen, lenmax
       _FAIL ('PATHLEN is greater than filename_max_char_len')
    end if
    if (slen>0) filename(1:slen)=c_filename(1:slen)
    return
  end subroutine fglob
Call graph
fglob calls f_call_c_glob, mapl_am_i_root, mapl_assert
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_filename_from_template_use_index calls fglob
create_grid calls get_filename_from_template_use_index
find_m_files_for_currtime calls get_filename_from_template_use_index
initialize_from_config_with_prefix calls find_m_files_for_currtime