fieldAdd – MAPL
fieldAdd Subroutine
74 statements
Source File
public subroutine fieldAdd(field_out, field_a, field_b, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field_out
type(ESMF_Field), intent(inout) :: field_a
type(ESMF_Field), intent(inout) :: field_b
integer, intent(out), optional :: rc
Calls
Called by
Call graph
fieldadd calls esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
getfieldsundef calls getfieldsundef_r4, getfieldsundef_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fieldshaveundef calls mapl_return, mapl_verify, ESMF_AttributeGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, mapl_return, mapl_verify, fieldgetlocalelementcount
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
getfieldsundef_r4 calls mapl_assert, mapl_return, mapl_verify, ESMF_AttributeGet
getfieldsundef_r8 calls mapl_assert, mapl_return, mapl_verify, ESMF_AttributeGet
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalelementcount calls get_local_element_count
fieldgetlocalsize calls get_local_size
field_binary calls fieldadd
test_fieldaddr4 calls fieldadd
test_fieldaddr4_missing calls fieldadd
test_fieldaddr8 calls fieldadd
evalf calls field_binary
mapl_stateeval calls evalf
calcderivedfield calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval