field_binary – MAPL
field_binary Subroutine
26 statements
Source File
private subroutine field_binary(field1, field2, arthcode, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field1
type(ESMF_Field), intent(inout) :: field2
integer, intent(in) :: arthcode
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
field_binary
Source Code
  subroutine field_binary(field1,field2,arthcode,rc)
     type(ESMF_Field), intent(inout) :: field1
     type(ESMF_Field), intent(inout) :: field2
     integer, intent(in)             :: arthcode
     integer, optional, intent(out)  :: rc
     integer :: status
     select  case(arthcode)
        case(cAdd)
           call FieldAdd(field2,field2,field1,_RC)
        case(cSub)
           call FieldSubtract(field2,field2,field1,_RC)
        case(cMul)
           call FieldMultiply(field2,field2,field1,_RC)
        case(cDiv)
           call FieldDivide(field2,field2,field1,_RC)
        case(cPow)
           call FieldPower(field2,field2,field1,_RC)
     end select
     _RETURN(_SUCCESS)
  end subroutine field_binary
Call graph
field_binary calls fieldadd, fielddivide, fieldmultiply, fieldpower, fieldsubtract, mapl_return, mapl_verify
fieldadd calls mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef
fielddivide calls mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef
fieldmultiply calls mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef
fieldpower calls mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef
fieldsubtract calls mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, mapl_assert, fieldshaveundef
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
getfieldsundef calls getfieldsundef_r4, getfieldsundef_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fieldshaveundef calls mapl_return, mapl_verify, ESMF_AttributeGet
get_error_message calls at
mapl_throw_exception calls initialize
are_conformable_array calls mapl_return, mapl_verify, fieldsareconformable
are_conformable_scalar calls mapl_return, mapl_verify, esmf_fieldget, fieldgetlocalelementcount
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
getfieldsundef_r4 calls mapl_return, mapl_verify, mapl_assert, ESMF_AttributeGet
getfieldsundef_r8 calls mapl_return, mapl_verify, mapl_assert, ESMF_AttributeGet
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
evalf calls field_binary
mapl_stateeval calls evalf
calcderivedfield calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
run calls mapl_runexpression
run_ calls evaluate_derived_field, calcderivedfield, fillstate