field_unary – MAPL
field_unary Subroutine
57 statements
Source File
private subroutine field_unary(field, funcCode, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(in) :: funcCode
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine field_unary(field,funcCode,rc)
     type(ESMF_Field),      intent(inout) :: field
     integer,               intent(in   ) :: funcCode
     integer, optional,     intent(out  ) :: rc
     integer :: status
     select case(funcCode)
        case(cNeg)
           call FieldNegate(field,_RC)
        case(cAbs)
           call FieldAbs(field,field,_RC)
        case(cExp)
           call FieldExp(field,field,_RC)
        case(cLog10)
           call FieldLog10(field,field,_RC)
        case(cLog)
           call FieldLog(field,field,_RC)
        case(cSqrt)
           call FieldSqrt(field,field,_RC)
        case(cSinh)
           call FieldSinh(field,field,_RC)
        case(cCosh)
           call FieldCosh(field,field,_RC)
        case(cTanh)
           call FieldTanh(field,field,_RC)
        case(cSin)
           call FieldSin(field,field,_RC)
        case(cCos)
           call FieldCos(field,field,_RC)
        case(cTan)
           call FieldTan(field,field,_RC)
        case(cAsin)
           call FieldAsin(field,field,_RC)
        case(cAcos)
           call FieldAcos(field,field,_RC)
        case(cAtan)
           call FieldAtan(field,field,_RC)
        case(cHeav)
           _FAIL("heaviside needs implementation")
     end select
     _RETURN(_SUCCESS)
  end subroutine field_unary
Call graph
field_unary calls mapl_assert, fieldabs, fieldacos, fieldasin, fieldatan, fieldcos, fieldcosh, fieldexp, fieldlog, fieldlog10, fieldnegate, fieldsin, fieldsinh, fieldsqrt, fieldtan, fieldtanh, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fieldabs calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldacos calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldasin calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldatan calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldcos calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldcosh calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldexp calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldlog calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldlog10 calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldnegate calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, getfieldsundef, fieldshaveundef
fieldsin calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldsinh calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldsqrt calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldtan calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
fieldtanh calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, assign_fptr, fieldsareconformable, getfieldsundef, fieldshaveundef
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evalf calls field_unary
mapl_stateeval calls evalf
calcderivedfield calls mapl_stateeval
evaluate_box_mask calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
evaluate_region_mask calls mapl_stateeval
evaluate_zone_mask calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
evaluate_mask calls evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
run calls mapl_runexpression
run_ calls fillstate, calcderivedfield, evaluate_derived_field