FieldIsConstantR4 – MAPL
FieldIsConstantR4 Function
21 statements
Source File
private function FieldIsConstantR4(field, constant_val, rc) result(field_is_constant)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
real(kind=ESMF_KIND_R4) :: constant_val
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
function FieldIsConstantR4(field,constant_val,rc) result(field_is_constant)
   logical :: field_is_constant
   type(ESMF_Field), intent(inout) :: field
   real(kind=ESMF_KIND_R4) :: constant_val
   integer, optional, intent(out) :: rc
   integer :: status
   real(ESMF_KIND_R4), pointer :: f_ptr_r4(:)
   type(ESMF_TypeKind_Flag) :: type_kind
   call ESMF_FieldGet(field,typekind=type_kind,_RC)
   field_is_constant = .false.
   if (type_kind == ESMF_TYPEKIND_R4) then
      call assign_fptr(field,f_ptr_r4,_RC)
      field_is_constant = all(f_ptr_r4 == constant_val)
   else
      _FAIL("constant_val is single precision so you can not check if it is all undef for an R8")
   end if
   _RETURN(_SUCCESS)
end function FieldIsConstantR4
Call graph
fieldisconstantr4 calls esmf_fieldget, assign_fptr, mapl_assert, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldisconstant calls fieldisconstantr4
comparestate calls fieldisconstant
run_ calls comparestate