file_has_corners – MAPL
file_has_corners Subroutine
27 statements
Source File
private subroutine file_has_corners(this, rc)
Uses
MAPL_CommsMod
Type Bound
XYGridFactory
Arguments
Type Intent Optional Attributes Name
class(XYGridFactory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Call graph
file_has_corners calls ESMF_VMBroadcast, ESMF_VMGetCurrent, mapl_am_i_root, nf90_inq_varid, nf90_open, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
check_and_fill_consistency calls file_has_corners
initialize_from_config_with_prefix calls check_and_fill_consistency
initialize_from_file_metadata calls check_and_fill_consistency
xygridfactory_from_parameters calls check_and_fill_consistency
xygridfactory calls xygridfactory_from_parameters