fillin_derived – MAPL
fillin_derived Subroutine
34 statements
Source File
public subroutine fillin_derived(this, item_name, derived_item, time, clock, unusable, rc)
Type Bound
ExtDataOldTypesCreator
Arguments
Type Intent Optional Attributes Name
class(ExtDataOldTypesCreator), intent(inout) :: this
character(len=*), intent(in) :: item_name
type(DerivedExport), intent(inout) :: derived_item
type(ESMF_Time), intent(inout) :: time
type(ESMF_Clock), intent(inout) :: clock
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine fillin_derived(this,item_name,derived_item,time,clock,unusable,rc)
      class(ExtDataOldTypesCreator), intent(inout) :: this
      character(len=*), intent(in) :: item_name
      type(DerivedExport), intent(inout) :: derived_item
      type(ESMF_Time), intent(inout) :: time
      type(ESMF_Clock), intent(inout) :: clock
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ExtDataDerived), pointer :: rule
      integer :: status
      type(ExtDataTimeSample), pointer :: time_sample
      type(ExtDataTimeSample), target :: default_time_sample
      _UNUSED_DUMMY(unusable)
      rule => this%derived_map%at(trim(item_name))
      derived_item%name = trim(item_name)
      derived_item%expression = rule%expression
      if (allocated(rule%sample_key)) then
         time_sample => this%sample_map%at(rule%sample_key)
      else
        call default_time_sample%set_defaults()
        time_sample=>default_time_sample
      end if
      call derived_item%update_freq%create_from_parameters(time_sample%refresh_time, &
           time_sample%refresh_frequency, time_sample%refresh_offset, time, clock, _RC)
      derived_item%masking=.false.
      if (index(derived_item%expression,"mask") /= 0 ) then
         derived_item%masking=.true.
         allocate(derived_item%mask_definition)
         derived_item%mask_definition = StateMask(derived_item%expression,_RC)
      end if
      _RETURN(_SUCCESS)
   end subroutine fillin_derived
Call graph
fillin_derived calls create_from_parameters, m_at, mapl_return, mapl_verify, set_defaults
create_from_parameters calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_defaults calls mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls mapl_return, mapl_verify, mapl_assert, ESMF_TimeIntervalSet
string_to_integer_time calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
s_find calls at, exists, find_index, s_ordereq
initialize_ calls fillin_derived