FillRequestBundle – MAPL
FillRequestBundle Subroutine
30 statements
Source File
public subroutine FillRequestBundle(request_list, state, rc)
Arguments
Type Intent Optional Attributes Name
type(requestedServiceItemVector), intent(inout) :: request_list
type(ESMF_State), intent(in) :: state
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine FillRequestBundle(request_list, state, rc)
    type(RequestedServiceItemVector), intent(INOUT) :: request_list
    type(ESMF_State), intent(IN) :: state
    integer, optional, intent(out) :: rc
    integer :: status
    integer :: i, nl
    type(ESMF_Field), allocatable :: fields(:)
    type (RequestedServiceItemVectorIterator) :: iter
    type (RequestedServiceType), pointer :: item
    _ASSERT(request_list%size()>0,'request_list should not be empty')
    iter = request_list%begin()
    ! loop over requested services
    do while (iter /= request_list%end())
       item => iter%get()
       if (allocated(item%var_list)) then
          nl = size(item%var_list)
          allocate(fields(nl), stat=status)
          _VERIFY(status)
          do i=1, nl
             call ESMF_StateGet(state, item%var_list(i), &
                  fields(i), rc=status)
             _VERIFY(status)
          end do
          call ESMF_FieldBundleAdd(item%bundle, fields, rc=status)
          _VERIFY(status)
          deallocate(fields)
       end if
       call iter%next()
    end do
    _RETURN(_SUCCESS)
  end subroutine FillRequestBundle
Call graph
fillrequestbundle calls esmf_fieldbundleadd, esmf_stateget, mapl_assert, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_genericinitialize calls fillrequestbundle
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize