fill_row_integer_stats – MAPL
fill_row_integer_stats Subroutine
21 statements
Source File
private subroutine fill_row_integer_stats(stats, option, row)
Type Bound
AbstractColumn
Arguments
Type Intent Optional Attributes Name
type(DistributedInteger), intent(in) :: stats
character(len=*), intent(in) :: option
class(*), intent(out), allocatable :: row
Called by
Source Code
   subroutine fill_row_integer_stats(stats, option, row)
      type(DistributedInteger), intent(in) :: stats
      character(*), intent(in) :: option
      class(*), allocatable, intent(out) :: row
      select case (option)
      case ('MAX')
         allocate(row, source=stats%max)
      case ('MAX_PE')
         allocate(row, source=stats%max_pe)
      case ('MIN')
         allocate(row, source=stats%min)
      case ('MIN_PE')
         allocate(row, source=stats%min_pe)
      case ('MEAN')
         allocate(row, source=stats%total / stats%num_pes)
      case ('TOTAL')
         allocate(row, source=stats%total)
      case default
         print*,__FILE__,__LINE__,'ERROR: unsupported option '//option
      end select
   end subroutine fill_row_integer_stats
Call graph
get_row_dist calls fill_row
get_row calls get_row_dist