FillState – MAPL
FillState Subroutine
180 statements
Source File
private subroutine FillState(inState, outState, time, grid, synth, cf, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: inState
type(ESMF_State), intent(inout) :: outState
type(ESMF_Time), intent(inout) :: time
type(ESMF_Grid), intent(inout) :: grid
type(SyntheticFieldSupport) :: synth
type(ESMF_Config), intent(inout) :: cf
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine FillState(inState,outState,time,grid,Synth,cf,rc)
      type(ESMF_State), intent(inout) :: inState
      type(ESMF_State), intent(inout) :: outState
      type(ESMF_Time),  intent(Inout) :: time
      type(ESMF_Grid),  intent(inout) :: grid
      type(SyntheticFieldSupport) :: synth
      type(ESMF_Config), intent(inout) :: cf
      integer, optional, intent(out) :: rc
      integer :: status
      real, pointer                       :: Exptr3(:,:,:), Exptr2(:,:), Exptr1(:)
      integer :: itemcount
      character(len=ESMF_MAXSTR), allocatable :: outNameList(:)
      type(ESMF_StateItem_Flag), allocatable :: item_type(:)
      type(ESMF_Field) :: expf,farray(9)
      type(ESMF_State) :: pstate
      character(len=:), pointer :: fexpr
      integer :: i1,in,j1,jn,ldims(3),i,j,seed_size,mypet
      integer, allocatable :: seeds(:)
      type(ESMF_VM) :: vm
      if (.not. synth%on_tiles) then
         call MAPL_GridGet(grid,localcellcountperdim=ldims,_RC)
         call MAPL_Grid_Interior(grid,i1,in,j1,jn)
      end if
      call ESMF_StateGet(outState,itemcount=itemCount,_RC)
      allocate(outNameList(itemCount),stat=status)
      _VERIFY(status)
      allocate(item_type(itemCount),stat=status)
      _VERIFY(status)
      call ESMF_StateGet(outState,itemTypeList=item_type,itemNameList=outNameList,_RC)
      if (synth%on_tiles) then
         call MAPL_GetPointer(inState,exPtr1,'time',_RC)
         exPtr1=synth%tFunc%evaluate_time(Time,_RC)
      else
         call MAPL_GetPointer(inState,exPtr2,'time',_RC)
         exPtr2=synth%tFunc%evaluate_time(Time,_RC)
      end if
      if (.not. synth%on_tiles) then
         call MAPL_GetPointer(inState,exPtr2,'i_index',_RC)
         do j = 1,ldims(2)
            do i=1,ldims(1)
               exPtr2(i,j)=i1+i-1
            enddo
         enddo
         call MAPL_GetPointer(inState,exPtr2,'j_index',_RC)
         do i = 1,ldims(1)
            do j=1,ldims(2)
               exPtr2(i,j)=j1+j-1
            enddo
         enddo
         call MAPL_GetPointer(inState,exPtr3,'numlev',_RC)
         do i=1,size(exPtr3,3)
            exPtr3(:,:,i)=i
         enddo
         call MAPL_GetPointer(inState,exPtr3,'PLE',_RC)
         call Fill_PLE(exPtr3, cf, _RC)
      end if
      if (synth%on_tiles) then
         call MAPL_GetPointer(inState,exPtr1,'doy',_RC)
         exPtr1 = compute_doy(time,_RC)
      else
         call MAPL_GetPointer(inState,exPtr2,'doy',_RC)
         exPtr2 = compute_doy(time,_RC)
      end if
      call random_seed(size=seed_size)
      allocate(seeds(seed_size))
      call ESMF_VMGetCurrent(vm,_RC)
      call ESMF_VMGet(vm,localPet=mypet,_RC)
      seeds = mypet
      call random_seed(put=seeds)
      if (synth%on_tiles) then
         call MAPL_GetPointer(inState,exPtr1,'rand',_RC)
         call random_number(exPtr1)
      else
         call MAPL_GetPointer(inState,exPtr2,'rand',_RC)
         call random_number(exPtr2)
      end if
      call ESMF_StateGet(inState,'time',farray(1),_RC)
      call ESMF_StateGet(inState,'lons',farray(2),_RC)
      call ESMF_StateGet(inState,'lats',farray(3),_RC)
      call ESMF_StateGet(inState,'i_index',farray(4),_RC)
      call ESMF_StateGet(inState,'j_index',farray(5),_RC)
      call ESMF_StateGet(inState,'doy',farray(6),_RC)
      call ESMF_StateGet(inState,'rand',farray(7),_RC)
      call ESMF_StateGet(inState,'numlev',farray(8),_RC)
      call ESMF_StateGet(inState,'PLE',farray(9),_RC)
      pstate = ESMF_StateCreate(_RC)
      call ESMF_StateAdd(pstate,farray,_RC)
      do i=1,itemCount
         if (item_type(i) == ESMF_STATEITEM_FIELD) then
            call ESMF_StateGet(outState,trim(outNameList(i)),expf,_RC)
            fexpr => synth%fillDefs%at(trim(outNameList(i)))
            if (associated(fexpr)) then
               call MAPL_StateEval(pstate,fexpr,expf,_RC)
            end if
         end if
      enddo
      _RETURN(ESMF_SUCCESS)
      contains
      subroutine fill_ple(ple_ptr, cf, rc)
         real, pointer, intent(in) :: ple_ptr(:,:,:)
         type(ESMF_Config), intent(inout) :: cf
         integer, intent(out), optional :: rc
         integer :: status
         type(ESMF_HConfig) :: hconfig, akbk
         character(len=3) :: km_str
         integer :: km, i
         character(len=ESMF_MAXPATHLEN) :: akbk_file, ps_file
         real, allocatable :: ak(:), bk(:), ps(:,:)
         real :: ps_val
         logical :: has_akbk, has_psval
         type(NetCDF4_FileFormatter) :: fs
         call ESMF_ConfigFindLabel(cf,"akbk_file:",isPresent=has_akbk,_RC)
         !call ESMF_ConfigFindLabel(cf,"ps_val:",isPresent=has_psval,_RC)
         call ESMF_ConfigFindLabel(cf,"ps_file:",isPresent=has_psval,_RC)
         if (has_akbk .and. has_psval) then
            call ESMF_ConfigGetAttribute(cf,label="akbk_file:",value=akbk_file,_RC)
            !call ESMF_ConfigGetAttribute(cf,label="ps_val:",value=ps_val,_RC)
            call ESMF_ConfigGetAttribute(cf,label="ps_file:",value=ps_file,_RC)
         else
            _RETURN(_SUCCESS)
         end if
         allocate(ps(size(ple_ptr,1),size(ple_ptr,2)))
         call fs%open(trim(ps_file),pFIO_READ,_RC)
         call fs%get_var("PS",ps, _RC)
         hconfig = ESMF_HConfigCreate(filename=trim(akbk_file), _RC)
         km = size(ple_ptr,3) - 1
         write(km_str,'(i3.3)') km
         akbk = ESMF_HConfigCreateAt(hconfig, keyString='L'//trim(km_str), _RC)
         ak = ESMF_HConfigAsR4Seq(akbk, keyString='ak', _RC)
         bk = ESMF_HConfigAsR4Seq(akbk, keyString='bk', _RC)
         do i=1,km+1
            !ple_ptr(:,:,i-1) = ak(i)+ps_val*bk(i)
            ple_ptr(:,:,i-1) = ak(i)+ps(:,:)*bk(i)
         enddo
         _RETURN(_SUCCESS)
      end subroutine fill_ple
   end subroutine FillState
Call graph
fillstate calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_HConfigCreate, ESMF_VMGet, ESMF_VMGetCurrent, at, esmf_hconfigasr4seq, esmf_hconfigcreateat, esmf_stateadd, esmf_statecreate, esmf_stateget, esmfl_stategetpointertodata, mapl_grid_interior, get_var, compute_doy, evaluate_time, mapl_gridget, mapl_return, mapl_stateeval, mapl_verify
initialize_ calls fillstate
run_ calls fillstate