finalize_global_time_profiler – MAPL
finalize_global_time_profiler Subroutine
5 statements
Source File
public subroutine finalize_global_time_profiler()
Arguments
None
Calls
Called by
Contents
Source Code
finalize_global_time_profiler
Source Code
   subroutine finalize_global_time_profiler()
      type(TimeProfiler), pointer :: time_profiler
      time_profiler => get_global_time_profiler()
      call time_profiler%finalize()
   end subroutine finalize_global_time_profiler
Call graph
finalize_global_time_profiler calls finalize, get_global_time_profiler
finalize calls finalize_global_time_profiler
main calls finalize
run calls finalize, run
test_accumulate_multi calls finalize
test_accumulate_nested calls finalize
test_accumulate_sub calls finalize
test_simple_report_timer calls finalize
test_simple_report_timer_b calls finalize
test_start_one calls finalize
test_stop_wrong_meter calls finalize
time_ave calls finalize
ut_regridding calls finalize
extdata_driver calls run
regrid_util calls main