Finalize_ – MAPL
Finalize_ Subroutine
35 statements
Source File
private subroutine Finalize_(GC, IMPORT, EXPORT, CLOCK, rc)
Finalize_ — Finalize MAPL_ExtData
This is a simple ESMF wrapper.
History
12Dec2009 da Silva Design and first implementation.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
Grid Component
type(ESMF_State), intent(inout) :: IMPORT
Import State
type(ESMF_State), intent(inout) :: EXPORT
Export State
type(ESMF_Clock), intent(inout) :: CLOCK
The clock
integer, intent(out) :: rc
Error return code:
0 - all is well
1 -
Calls
Contents
Source Code
Finalize_
Source Code
   SUBROUTINE Finalize_ ( GC, IMPORT, EXPORT, CLOCK, rc )
! !USES:
  implicit NONE
! !INPUT PARAMETERS:
   type(ESMF_Clock),  intent(inout) :: CLOCK      !! The clock
! !OUTPUT PARAMETERS:
   type(ESMF_GridComp), intent(inout)  :: GC     !! Grid Component
   type(ESMF_State), intent(inout) :: IMPORT     !! Import State
   type(ESMF_State), intent(inout) :: EXPORT     !! Export State
   integer, intent(out) ::  rc                   !! Error return code:
                                                 !!  0 - all is well
                                                 !!  1 -
!
!-------------------------------------------------------------------------
   type(MAPL_ExtData_state), pointer :: self        ! Legacy state
   type(ESMF_Config)                 :: CF          ! Universal Config
   character(len=ESMF_MAXSTR)        :: comp_name
   character(len=ESMF_MAXSTR)        :: Iam
   integer                           :: status
   integer                           :: i
!  Get my name and set-up traceback handle
!  ---------------------------------------
   Iam = 'Finalize_'
   call ESMF_GridCompGet( GC, name=comp_name, _RC )
   Iam = trim(comp_name) // trim(Iam)
!  Finalize MAPL Generic
!  ---------------------
   call MAPL_GenericFinalize ( GC, IMPORT, EXPORT, CLOCK,  _RC )
!  Extract relevant runtime information
!  ------------------------------------
   call extract_ ( GC, self, CF, _RC)
!  Free the memory used for the bracketing arrays
!  -----------------------------------------------------------
   if (self%active) then
      do i = 1, self%primary%nItems
         if (self%primary%item(i)%isConst) cycle
         if (associated(self%primary%item(i)%refresh_time)) then
            deallocate(self%primary%item(i)%refresh_time)
         end if
      end do
!  Free the memory used to hold the primary export items
!  -----------------------------------------------------
      if (associated(self%primary%item)) then
         deallocate(self%primary%item)
      end if
   end if
!  All done
!  --------
   _RETURN(ESMF_SUCCESS)
 end SUBROUTINE Finalize_
Call graph
finalize_ calls ESMF_GridCompGet, extract_, mapl_genericfinalize, mapl_return, mapl_verify
extract_ calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_genericfinalize calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_ClockGet, ESMF_GridCompFinalize, ESMF_TimeGet, ESMF_UtilStringLowerCase, get_internal_state, get_num_children, mapl_getobjectfromgc, mapl_getresource, mapl_timeroff, mapl_timeron, fill_grads_template, get_child_export_state, get_child_gridcomp, get_child_import_state, get_global_time_profiler, mapl_esmfstatewritetofile, mapl_genericstatedestroy, mapl_internalstateretrieve, mapl_profisdisabled
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception