finalize_pflogger – MAPL
finalize_pflogger Subroutine
3 statements
Source File
private subroutine finalize_pflogger()
Arguments
None
Called by
Source Code
   subroutine finalize_pflogger()
      call logging%free()
   end subroutine finalize_pflogger
Call graph
mapl_finalize calls finalize_pflogger
finalize_mpi calls mapl_finalize
main calls mapl_finalize
run calls mapl_finalize, finalize_mpi
time_ave calls mapl_finalize
ut_regridding calls mapl_finalize
comp_testing_driver calls main
extdata_driver calls run
regrid_util calls main
capdriver_main calls run
driver_gethorzijindex calls run