finalize – MAPL
finalize Subroutine
19 statements
Source File
private subroutine finalize(this, rc)
Type Bound
AbstractMeter
Arguments
Type Intent Optional Attributes Name
class(AbstractMeter), intent(in) :: this
integer, intent(out), optional :: rc
Calls
Called by
Call graph
finalize calls mpi_op_free, mpi_type_free, mapl_verify, finalize, finalize_global_time_profiler
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
finalize_global_memory_profiler calls finalize
finalize_global_time_profiler calls finalize
test_accumulate_multi calls finalize
test_accumulate_nested calls finalize
test_accumulate_sub calls finalize
test_simple_report_timer calls finalize
test_simple_report_timer_b calls finalize
test_start_one calls finalize
test_stop_wrong_meter calls finalize
main calls finalize
run calls finalize