finalize – MAPL
finalize Subroutine
15 statements
Source File
private subroutine finalize(this)
Type Bound
FakeHistData0
Arguments
Type Intent Optional Attributes Name
class(FakeHistData0), intent(inout) :: this
Calls
Called by
Source Code
   subroutine finalize(this)
      class (FakeHistData0), intent(inout) :: this
      integer :: ierror
      class(ClientThread), pointer :: icPtr=>null()
      class(ClientThread), pointer :: ocPtr=>null()
      deallocate(this%bundle)
      call Mpi_Barrier(this%comms(1),ierror)
      print*,"iclient sent terminate signal"
      icPtr=>this%ic_vec%at(1)
      call icPtr%terminate()
     ! call this%i_c%terminate()
      call Mpi_Barrier(this%comms(2),ierror)
      ocPtr=>this%oc_vec%at(1)
      call ocPtr%terminate()
      print*,"oclient sent terminate signal"
      !call this%o_c%terminate()
   end subroutine finalize
Call graph
finalize calls mpi_barrier, at, terminate
terminate calls get_connection, mapl_return, mapl_verify, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
main calls finalize