finalize – MAPL
finalize Subroutine
19 statements
Source File
private subroutine finalize(this, rc)
Type Bound
ServerManager
Arguments
Type Intent Optional Attributes Name
class(ServerManager), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine finalize(this,rc)
      class(ServerManager), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      ! reporting here is for client_server in the same process which don't call start()
      ! problem here: all servers should coordinate to report one by one to avoid messy output
      if (associated(this%i_server)) then
         call this%i_server%report_profile(_RC)
         deallocate(this%i_server)
      endif
      if (associated(this%o_server)) then
         call this%o_server%report_profile(_RC)
         deallocate(this%o_server)
      endif
      call this%directory_service%free_directory_resources()
      call this%splitter%free_sub_comm()
      _RETURN(_SUCCESS)
   end subroutine finalize
Call graph
finalize calls free_directory_resources, free_sub_comm, mapl_return, mapl_verify, report_profile
free_directory_resources calls mapl_return, mapl_verify, mpi_barrier, mpi_comm_free, mpi_free_mem, mpi_win_free, free_mpi_resources
free_sub_comm calls mpi_comm_free
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
report_profile calls mapl_return, mapl_verify, generate_report, add_column, reduce
finalize_io_clients_servers calls finalize
main calls finalize
time_ave calls finalize
ut_regridding calls finalize
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls finalize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run
capdriver_main calls run