finalize – MAPL
finalize Subroutine
8 statements
Source File
private subroutine finalize(this)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout), target :: this
Calls
Called by
Source Code
   subroutine finalize(this)
      class(BaseProfiler), target, intent(inout) :: this
      class(AbstractMeter), pointer :: t
      !$omp master
      call this%stack%pop_back()
      t => this%root_node%get_meter()
      call t%stop()
      call t%finalize()
      !$omp end master
   end subroutine finalize
Call graph
finalize calls finalize, get_meter, vector_pop_back, mpi_op_free, mpi_type_free, finalize_global_time_profiler
vector_pop_back calls vector_downsize
finalize_global_memory_profiler calls finalize
finalize_global_time_profiler calls finalize
test_accumulate_multi calls finalize
test_accumulate_nested calls finalize
test_accumulate_sub calls finalize
test_simple_report_timer calls finalize
test_simple_report_timer_b calls finalize
test_start_one calls finalize
test_stop_wrong_meter calls finalize
main calls finalize
run calls finalize
extdata_driver calls run