finalize – MAPL
finalize Module Subroutine
43 statements
Source File
module subroutine finalize(this, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(MaskSampler), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
module subroutine finalize(this,rc)
   class(MaskSampler), intent(inout) :: this
   integer, optional, intent(out)          :: rc
   type(GriddedIOitemVectorIterator) :: iter
   type(GriddedIOitem), pointer :: item
   type(ESMF_Field) :: src_field
   integer :: ic_2d, ic_3d, rank, j
   integer :: status
    if (this%use_pfio) then
       ic_2d=0
       ic_3d=0
       iter = this%items%begin()
       do while (iter /= this%items%end())
          item => iter%get()
          if (item%itemType == ItemTypeScalar) then
             call ESMF_FieldBundleGet(this%bundle,trim(item%xname),field=src_field,_RC)
             call ESMF_FieldGet(src_field,rank=rank,_RC)
             if (rank==2) then
                ic_2d = ic_2d + 1
             else if (rank==3) then
                ic_3d = ic_3d + 1
             end if
          end if
          call iter%next()
       end do
       do j=1, ic_2d
          deallocate ( this%var2d(j)%array_x, _STAT )
       end do
       deallocate ( this%var2d, _STAT )
       do j=1, ic_3d
          deallocate ( this%var3d(j)%array_xz, _STAT )
       end do
       deallocate ( this%var3d, _STAT )
    end if
    _RETURN(_SUCCESS)
  end subroutine finalize
Call graph
finalize calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next, finalize
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize