finalize – MAPL
finalize Subroutine
10 statements
Source File
private subroutine finalize(this)
Type Bound
FakeHistData
Arguments
Type Intent Optional Attributes Name
class(FakeHistData), intent(inout) :: this
Calls
Called by
Source Code
   subroutine finalize(this)
      class (FakeHistData), intent(inout) :: this
      class(ClientThread), pointer :: icPtr=>null()
      class(ClientThread), pointer :: ocPtr=>null()
      deallocate(this%bundle)
      icPtr=>this%ic_vec%at(1)
      call icPtr%terminate()
      ocPtr=>this%oc_vec%at(1)
      call ocPtr%terminate()
   end subroutine finalize
Call graph
finalize calls at, terminate
terminate calls get_connection, mapl_return, mapl_verify, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
main calls finalize