finalize_mpi – MAPL
finalize_mpi Subroutine
16 statements
Source File
private subroutine finalize_mpi(this, unusable, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine finalize_mpi(this, unusable, rc)
      class (MAPL_Cap), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      call MAPL_Finalize(comm=this%comm_world)
      if (.not. this%mpi_already_initialized) then
         call MPI_Finalize(status)
      end if
      _RETURN(_SUCCESS)
   end subroutine finalize_mpi
Call graph
finalize_mpi calls mpi_finalize, mapl_finalize, mapl_return
mapl_finalize calls mapl_return, finalize_profiler, finalize_udunits, finalize_pflogger, mapl_verify, report_global_profiler, stop_global_time_profiler
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception
report_global_profiler calls mapl_return, mapl_verify, mpi_barrier, mpi_comm_rank, mpi_comm_size, generate_report, get_logger, add_column, get_global_time_profiler, info
stop_global_time_profiler calls mapl_return, mapl_verify, get_global_time_profiler
add_column calls get_num_rows_header, get_num_rows_separator, get_width, set_width, v_push_back
run calls finalize_mpi
capdriver_main calls run
driver_gethorzijindex calls run