Finalize – MAPL
Finalize Subroutine
43 statements
Source File
private subroutine Finalize(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(out) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
Finalize
Source Code
  subroutine Finalize ( gc, import, export, clock, rc )
! !ARGUMENTS:
    type(ESMF_GridComp), intent(inout)    :: gc     ! composite gridded component
    type(ESMF_State),       intent(inout) :: import ! import state
    type(ESMF_State),       intent(  out) :: export ! export state
    type(ESMF_Clock),       intent(inout) :: clock  ! the clock
    integer, intent(out), OPTIONAL        :: rc     ! Error code:
                                                     ! = 0 all is well
                                                     ! otherwise, error
    integer                         :: status
    type(HistoryCollection), pointer     :: list(:)
    type(HISTORY_wrap)              :: wrap
    type (HISTORY_STATE), pointer   :: IntState
    integer                         :: nlist, n
    type (MAPL_MetaComp), pointer :: GENSTATE
! Begin...
    call MAPL_GetObjectFromGC ( gc, GENSTATE, _RC)
! Retrieve the pointer to the state
    call ESMF_GridCompGetInternalState(gc, wrap, status)
    IntState => wrap%ptr
    list => IntState%list
    nlist = size(list)
! Close UNITs of GEOSgcm History Data
! -----------------------------------
   do n=1,nlist
      deallocate(list(n)%r4, list(n)%r8, list(n)%r8_to_r4)
      if (list(n)%disabled) cycle
      IF (list(n)%format == 'CFIO') then
         if( MAPL_CFIOIsCreated(list(n)%mcfio) ) then
            CALL MAPL_CFIOdestroy (list(n)%mcfio, _RC)
         end if
      ELSE
         if( list(n)%unit.ne.0 ) call FREE_FILE( list(n)%unit )
      END if
      if(list(n)%monthly) then
         !ALT need some logic if alarm if not ringing
         if (.not. ESMF_AlarmIsRinging ( list(n)%his_alarm )) then
            if (.not. list(n)%partial) then
               call ESMF_CplCompWriteRestart (INTSTATE%CCS(n), &
                    importState=INTSTATE%CIM(n), &
                    exportState=INTSTATE%GIM(n), &
                    clock=CLOCK,           &
                    userRC=STATUS)
               _VERIFY(STATUS)
            end if
         end if
      end if
   enddo
#if 0
   do n=1,nlist
      IF (IntState%average(n)) then
         call MAPL_StateDestroy(IntState%gim(n), _RC)
         call MAPL_StateDestroy(IntState%cim(n), _RC)
      end IF
   enddo
#endif
    call  MAPL_GenericFinalize ( GC, IMPORT, EXPORT, CLOCK, _RC )
    _RETURN(ESMF_SUCCESS)
  end subroutine Finalize
Call graph
finalize calls mapl_getobjectfromgc, mapl_verify, mapl_cfiodestroy, esmf_gridcompgetinternalstate, mapl_cfioiscreated, free_file, esmf_alarmisringing, esmf_cplcompwriterestart, mapl_genericfinalize, mapl_return
mapl_getobjectfromgc calls mapl_internalstateget
mapl_verify calls mapl_throw_exception
mapl_cfiodestroy calls mapl_verify, mapl_return, esmf_cfiodestroy, esmf_cfiofileclose
free_file calls mapl_return, mapl_assert
mapl_genericfinalize calls mapl_getobjectfromgc, mapl_verify, mapl_return, mapl_timeroff, mapl_internalstateretrieve, get_global_time_profiler, esmf_utilstringlowercase, esmf_timeget, mapl_genericstatedestroy, esmf_gridcompfinalize, mapl_getresource, esmf_clockget, mapl_timeron, fill_grads_template, mapl_esmfstatewritetofile, mapl_profisdisabled, esmf_gridcompget
mapl_return calls mapl_throw_exception, get_error_message