finalize_io_clients_servers – MAPL
finalize_io_clients_servers Subroutine
19 statements
Source File
private subroutine finalize_io_clients_servers(this, unusable, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine finalize_io_clients_servers(this, unusable, rc)
     class (MAPL_Cap), target, intent(inout) :: this
     class (KeywordEnforcer), optional, intent(in) :: unusable
     integer, optional, intent(out) :: rc
     type(SplitCommunicator) :: split_comm
     _UNUSED_DUMMY(unusable)
     call this%cap_server%get_splitcomm(split_comm)
     select case(split_comm%get_name())
     case('model')
        call i_Clients%terminate()
        call o_Clients%terminate()
     end select
     call this%cap_server%finalize()
     _RETURN(_SUCCESS)
   end subroutine finalize_io_clients_servers
Call graph
finalize_io_clients_servers calls finalize, get_name, get_splitcomm, mapl_return, terminate
finalize calls mapl_return, free_directory_resources, free_sub_comm, mapl_verify, report_profile
get_splitcomm calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
terminate calls mapl_return, at, terminate, wait_all, mapl_verify, get_connection, send
free_directory_resources calls mapl_return, mapl_verify, mpi_barrier, mpi_comm_free, mpi_free_mem, mpi_win_free, free_mpi_resources
free_sub_comm calls mpi_comm_free
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception
report_profile calls mapl_return, mapl_verify, generate_report, add_column, reduce
wait_all calls clear_requesthandle
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls run_ensemble
capdriver_main calls run