finalize_gc – MAPL
finalize_gc Subroutine
49 statements
Source File
private subroutine finalize_gc(gc, import_state, export_state, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gc
type(ESMF_State) :: import_state
type(ESMF_State) :: export_state
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Contents
Source Code
finalize_gc
Source Code
  subroutine finalize_gc(gc, import_state, export_state, clock, rc)
    type(ESMF_GridComp) :: gc
    type(ESMF_State) :: import_state, export_state
    type(ESMF_Clock) :: clock
    integer, intent(out) :: rc
    integer :: status
    type(MAPL_CapGridComp), pointer :: cap
    type(MAPL_MetaComp), pointer :: maplobj
    class (BaseProfiler), pointer :: t_p
    _UNUSED_DUMMY(import_state)
    _UNUSED_DUMMY(export_state)
    _UNUSED_DUMMY(clock)
    cap => get_CapGridComp_from_gc(gc)
    call MAPL_GetObjectFromGC(gc, maplobj, rc=status)
    _VERIFY(status)
    t_p => get_global_time_profiler()
    call t_p%start('Finalize')
    if (.not. cap%printspec > 0) then
       call ESMF_GridCompFinalize(cap%gcs(cap%root_id), importstate = cap%child_imports(cap%root_id), &
            exportstate=cap%child_exports(cap%root_id), clock = cap%clock, userrc = status)
       _VERIFY(status)
       call ESMF_GridCompFinalize(cap%gcs(cap%history_id), importstate = cap%child_imports(cap%history_id), &
            exportstate = cap%child_exports(cap%history_id), clock = cap%clock_hist, userrc = status)
       _VERIFY(status)
       call ESMF_GridCompFinalize(cap%gcs(cap%extdata_id), importstate = cap%child_imports(cap%extdata_id), &
            exportstate = cap%child_exports(cap%extdata_id), clock = cap%clock, userrc = status)
       _VERIFY(status)
       call CAP_Finalize(CAP%CLOCK_HIST, "cap_restart", rc=STATUS)
       _VERIFY(status)
       call ESMF_ConfigDestroy(cap%cf_ext, rc = status)
       _VERIFY(status)
       call ESMF_ConfigDestroy(cap%cf_hist, rc = status)
       _VERIFY(status)
       call ESMF_ConfigDestroy(cap%cf_root, rc = status)
       _VERIFY(status)
       call ESMF_ConfigDestroy(cap%config, rc = status)
       _VERIFY(status)
       call MAPL_FinalizeShmem(rc = status)
       _VERIFY(STATUS)
       ! Write EGRESS file
       !------------------
       call ESMF_VMBarrier(cap%vm)
       if(allocated(cap%final_file)) then
          if (cap%AmIRoot) then
             close(99)
             open (99,file=cap%final_file,form='formatted')
             close(99)
          end if
       end if
    end if
    call t_p%stop('Finalize')
    _RETURN(ESMF_SUCCESS)
  end subroutine finalize_gc
Call graph
finalize_gc calls ESMF_ConfigDestroy, ESMF_GridCompFinalize, ESMF_VMBarrier, child_exports, child_imports, gcs, mapl_finalizeshmem, mapl_getobjectfromgc, cap_finalize, get_capgridcomp_from_gc, get_global_time_profiler, mapl_return, mapl_verify, start
mapl_finalizeshmem calls mapl_finalizeshmem
mapl_getobjectfromgc calls mapl_internalstateget
cap_finalize calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_TimeGet, mapl_am_i_root, mapl_packdatetime, free_file, getfile
get_capgridcomp_from_gc calls ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception