finalize – MAPL
finalize Subroutine
15 statements
Source File
private subroutine finalize(this, import_state, export_state, clock, phase, unusable, rc)
Type Bound
DecoratorComponent
Arguments
Type Intent Optional Attributes Name
class(DecoratorComponent), intent(inout) :: this
type(ESMF_State), intent(inout) :: import_state
type(ESMF_State), intent(inout) :: export_state
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in) :: phase
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine finalize(this, import_state, export_state, clock, phase, unusable, rc)
      class(DecoratorComponent), intent(inout) :: this
      type(ESMF_State), intent(inout) :: import_state
      type(ESMF_State), intent(inout) :: export_state
      type(ESMF_Clock), intent(inout) :: clock
      character(*), intent(in) :: phase
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      call this%decorated%finalize(import_state, export_state, clock, phase, _RC)
      _RETURN(_SUCCESS)
   end subroutine finalize
Call graph
finalize calls finalize, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize