find_child – MAPL
find_child Function
21 statements
Source File
private function find_child(this, name) result(idx)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(in) :: this
character(len=*), intent(in) :: name
Return Value integer
Calls
Called by
Source Code
   integer function find_child(this, name) result(idx)
      class (MeterNode), intent(in) :: this
      character(*), intent(in) :: name
      integer :: i, ii, n
      class (AbstractMeterNode), pointer :: t
      n = this%children%size()
      do i = 1, n
         ii = 1 + mod(i + this%last_child_accessed - 1, n)
         t => this%children%at(ii)
         select type (t)
         class is (MeterNode)
            if (name == t%name) then
               idx = ii
               return
            end if
         class default
            print*,'insert error handler'
         end select
      end do
      idx = NOT_FOUND
   end function find_child
Call graph
find_child calls at
v_at_32 calls v_at_size_kind
add_child calls find_child
get_child calls find_child
has_child calls find_child
accumulate calls add_child, get_child
test_count_nodes_depth_1 calls add_child
test_depth_2 calls add_child, get_child
test_get_exclusive calls add_child, get_child
test_get_inclusive calls add_child, get_child
test_get_num_nodes calls add_child, get_child
test_get_num_nodes_2 calls add_child, get_child
test_next_one_child calls add_child
test_node_reset calls add_child, get_child
test_percent_inclusive calls add_child, get_child
test_simple calls add_child, get_child