find_index – MAPL
find_index Function
16 statements
Source File
private function find_index(this, value, last) result(idx)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
logical, intent(in) :: last
Return Value integer(kind=SIZE_KIND)
Calls
Called by
Call graph
find_index calls at, exists, s_lessthan, s_ordereq
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
s_find calls find_index
s_insert calls find_index
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_count calls s_find
s_deepcopy calls s_insert
s_remove calls s_find
m_at calls m_find
m_deepcopy calls s_deepcopy
start_back calls m_find, insert
add_attribute_0d calls insert
add_attribute_1d calls insert
equal calls m_at
get_attribute calls m_at
is_attribute_present calls m_at
m_new_map_from_pair_array calls insert
put_datatofile calls insert
start calls start_back
stringattributemap_deserialize calls insert
transfer_metadata calls m_at