find_delta_t – MAPL
find_delta_t Function
43 statements
Source File
private function find_delta_t(iSat, kk, long_limits, longind, t1, time_day)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
integer, intent(in) :: kk
real(kind=dp), intent(in) :: long_limits
real(kind=dp), intent(in), DIMENSION(:) :: longind
real(kind=dp), intent(in), DIMENSION(:) :: t1
real(kind=dp), intent(in) :: time_day
Return Value real(kind=dp)
Calls
Contents
Source Code
find_delta_t
Source Code
REAL(dp) FUNCTION find_delta_t(iSat, kk, long_limits, longind,t1,time_day)
       IMPLICIT NONE
       REAL(dp)    :: ti, ti_day
       INTEGER, INTENT(IN) :: kk
       REAL(dp), INTENT(IN)    :: time_day
       REAL(dp), DIMENSION(:), INTENT(IN)  :: longind
       REAL(dp), INTENT(IN)  :: long_limits
       REAL(dp), DIMENSION(:), INTENT(IN)  :: t1
       INTEGER, INTENT(IN)             :: iSat
       REAL(dp), DIMENSION(:), ALLOCATABLE :: t_tempo
       REAL(dp), DIMENSION(:,:), ALLOCATABLE :: lat_wayptemp, long_wayptemp
       INTEGER             :: flag_add, temp1, temp2, say, ii
       REAL(dp) :: simtimestart_temp, simtimeend_temp
       REAL(dp) :: lat_estwayp, lon_estwayp, dista
       flag_add = 1
       ti = time_day
       do while (flag_add.EQ.1)
          ti = ceiling(ti/2.0); !create new way points
          ti_day = ti/(24*60*60)
          temp1 = longind(kk)
          temp2  = longind(kk)+1
          simtimestart_temp = t1(temp1)
          simtimeend_temp = t1(temp2)
          CALL built_vecsize(simtimestart_temp, simtimeend_temp, &
               ti_day, say)
          ALLOCATE(t_tempo(1:say))
          CALL built_vec(simtimestart_temp,simtimeend_temp,      &
               ti_day, t_tempo)
          ALLOCATE(lat_wayptemp(1:size(t_tempo),1) ,             &
                   long_wayptemp(1:size(t_tempo),1) )
          DO ii=1,size(t_tempo) ! Cal caresponding lat lon
             CALL get_latlon(iSat, t_tempo(ii), lat_estwayp, lon_estwayp)
             lat_wayptemp(ii,1)  = lat_estwayp
             long_wayptemp(ii,1) = lon_estwayp
          END DO
         long_wayptemp = (long_wayptemp-180)
         flag_add = 0
         dista = MAPL_DEG_PER_KM * get_distance( lat_wayptemp(1,1),long_wayptemp(1,1), &
         lat_wayptemp(2,1),long_wayptemp(2,1))
         if  (dista.GT.long_limits) then
             flag_add = 1
         end if
         DEALLOCATE( lat_wayptemp,long_wayptemp )
         DEALLOCATE (t_tempo)
       end do
       find_delta_t = ti
END FUNCTION find_delta_t
Call graph
find_delta_t calls built_vec, built_vecsize, get_distance, get_latlon
get_distance calls deg2rad, rad2deg
get_latlon calls ecef2lla, eci2ecef, get_estimateeci, get_fraction, rad2deg
get_estimateeci calls orbits_track0
orbits_track0 calls orbits_track1, orbits_track2