find_config – MAPL
find_config Function
19 statements
Source File
private function find_config(this, key, rc) result(cf)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
character(len=*), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(ESMF_Config)
Calls
Called by
Source Code
  function find_config (this, key, rc) result(cf)
    class(samplerHQ)  :: this
    character(len=*) , intent(in) :: key
    type(ESMF_Config) :: cf
    integer, intent(out), optional :: rc
    integer :: status
    integer :: i, j
    j=0
    do i=1, this%ngrid
       if ( trim(key) == trim(this%CF_loc(i)%key) ) then
          cf = this%CF_loc(i)%cf
          j=j+1
          exit
       end if
    end do
    _ASSERT( j>0 , trim(key)//' is not found in Hsampler CF_loc(:)')
    _RETURN(_SUCCESS)
  end function find_config
Call graph
find_config calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
create_grid calls find_config
verify_epoch_equals_freq calls find_config
destroy_rh_regen_ogrid calls create_grid
initialize calls create_grid, verify_epoch_equals_freq
run calls destroy_rh_regen_ogrid