find_sweeppoints – MAPL
find_sweeppoints Subroutine
39 statements
Source File
private subroutine find_sweeppoints(iii, latwayp, longwayp, l, r, wrapon, latlonshift)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iii
real(kind=dp), intent(in), DIMENSION(:) :: latwayp
real(kind=dp), intent(in), DIMENSION(:) :: longwayp
real(kind=dp), intent(in) :: l
real(kind=dp), intent(in) :: r
logical, intent(in) :: wrapon
real(kind=dp), intent(inout), DIMENSION(:,:,:) :: latlonshift
Calls
Called by
Contents
Source Code
find_sweeppoints
Source Code
SUBROUTINE find_sweeppoints(iii, latwayp, longwayp, l, r, wrapon, latlonshift)
       IMPLICIT NONE
! !ARGUMENTS:
!
       REAL(dp), DIMENSION(:),     INTENT(IN)   :: latwayp, longwayp
       REAL(dp), INTENT(IN)     :: l, r  ! left right swap space
       INTEGER, INTENT(IN)      :: iii
       REAL(dp), DIMENSION(:,:,:), INTENT(INOUT):: latlonshift
       LOGICAL, intent(in)      :: wrapon       ! if true then wrap to -180 to 180
       REAL(dp), DIMENSION(:), ALLOCATABLE :: myvec, myvec_deg
       REAL(dp), DIMENSION(:), ALLOCATABLE :: latshift1, lonshift1
       REAL(dp)                            :: az, latout1, lonout1
       INTEGER                         :: say, i, count1
!DESCRIPTION:
!      Swap points are the points that gives the satellite instrument view
!      points that is different than the original track. For now calculation
!      is basic. r, and l gives how far sweep points will go vertically from the orbit points.
!
! !SEE ALSO:
!  get_recon, get_azimuth
!
       ALLOCATE(myvec(iii), myvec_deg(iii))
       if (r>l) then
               CALL linspace(l,r,iii,myvec)
       else
               CALL linspace(r,l,iii,myvec)
       end if
       do i=1, size(myvec)
          myvec_deg(i) =  MAPL_KM_PER_DEG * myvec(i)
       end do
      DO say = 1,size(myvec)
          ALLOCATE(latshift1(1:size(longwayp)),lonshift1(1:size(longwayp)))
          count1 = 1
          DO i=1,size(longwayp)-1
           az = get_azimuth(latwayp(i),longwayp(i),latwayp(i+1),longwayp(i+1), wrapon)
           CALL get_reckon(latwayp(i),longwayp(i), az+90.0,      &
                          myvec_deg(say), latout1, lonout1, wrapon)
           latshift1(count1) = latout1
           lonshift1(count1) = lonout1
           count1 = count1 + 1
          END DO
          ! i increased by 1
          CALL get_reckon(latwayp(i),longwayp(i), az+90.0,  &
                  myvec_deg(say), latout1, lonout1, wrapon)
          latshift1(count1) = latout1
          lonshift1(count1) = lonout1
          latlonshift(say,:,1) = latshift1(:)
          latlonshift(say,:,2) = lonshift1(:)
          DEALLOCATE(latshift1, lonshift1)
      END DO
      DEALLOCATE(myvec, myvec_deg)
END SUBROUTINE find_sweeppoints
Call graph
find_sweeppoints calls linspace, get_reckon, get_azimuth
linspace calls linspace1, linspace2
get_reckon calls rad2deg, deg2rad
get_azimuth calls rad2deg, deg2rad
orbits_swath calls find_sweeppoints
domasking_ calls orbits_swath
domasking_cs calls orbits_swath
run_ calls domasking_, domasking_cs