find_waypointslat – MAPL
find_waypointslat Subroutine
52 statements
Source File
private subroutine find_waypointslat(iSat, time_sec, sim_start, sim_end, distlat, t1_l, lat_l, lon_l, ts, las, los, rc)
The subroutine find_waypointslat finds waypoints for the possible max distance on the equator line. If flagauto = 0 then equal deltat data is created. Otherwise optimum number of minimum data is created (nonlinear).
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
integer, intent(in) :: time_sec
real(kind=dp), intent(in) :: sim_start
real(kind=dp), intent(in) :: sim_end
real(kind=dp), intent(in), optional :: distlat
real(kind=dp), intent(inout), DIMENSION(:) :: t1_l
real(kind=dp), intent(inout), DIMENSION(:) :: lat_l
real(kind=dp), intent(inout), DIMENSION(:) :: lon_l
integer, intent(out) :: ts
! INTEGER, INTENT(OUT):: time
integer, intent(out) :: las
! INTEGER, INTENT(OUT):: time
integer, intent(out) :: los
! INTEGER, INTENT(OUT):: time
integer, intent(inout) :: rc
Calls
Called by
Source Code
SUBROUTINE find_waypointslat(iSat, time_sec, sim_start,sim_end, distlat,   &
                               t1_l, lat_l, lon_l, ts, las, los, rc)
      ! sat name - time flag - interval second
      IMPLICIT NONE
! !ARGUMENTS:
!
      INTEGER, INTENT(IN) :: iSat, time_sec
      REAL(dp),    INTENT(IN) :: sim_start, sim_end
      REAL(dp),    OPTIONAL, INTENT(IN) :: distlat
      REAL(dp), DIMENSION(:), INTENT(INOUT):: t1_l, lat_l, lon_l ! data matrices (dm)
      INTEGER, INTENT(OUT)             :: ts, las, los       ! size of dm
!!!      INTEGER, INTENT(OUT):: time
      integer, intent(inout):: rc
      REAL(dp), DIMENSION(:),  ALLOCATABLE :: t1
      REAL(dp), DIMENSION(:,:),ALLOCATABLE :: lat_estwayp, long_estwayp ! temp arrays
      REAL(dp)    :: latest, lonest
      REAL(dp)    :: time_day
      INTEGER :: say, i
      INTEGER :: ierr1, ierr2, ierr3
!
      _UNUSED_DUMMY(distlat)
          IF (time_sec.LE.0.0) THEN
              print*, "Error: time is negative. For now it is not allowed"
              STOP
          ENDIF
          time_day = time_sec/(24.0*60.0*60.0)
          CALL built_vecsize(sim_start, sim_end, time_day, say)
          ALLOCATE (t1(1:say),             stat = ierr1)
          ALLOCATE (lat_estwayp(1:say,1),  stat = ierr2)
          ALLOCATE (long_estwayp(1:say,1), stat = ierr3)
          if ( ierr1 /= 0 .or. ierr2 /= 0 .or.  ierr3 /= 0 ) then
              rc = 3 !
            return
          endif
          CALL built_vec(sim_start, sim_end, time_day, t1)
          DO i=1,size(t1)
             CALL get_latlon(iSat, t1(i), latest, lonest)
             lat_estwayp(i,1)  = latest
             long_estwayp(i,1) = lonest
          END DO ! i
          ! % shift long (-pi)
          long_estwayp = (long_estwayp-180.0);
          ts = size(t1)
          las = size(lat_estwayp,1)
          los = size(long_estwayp,1)
          t1_l(1:ts)  = t1
          lat_l(1:las) = lat_estwayp(:,1)
          lon_l(1:los) = long_estwayp(:,1)
          DEALLOCATE (t1, stat=ierr1)
          DEALLOCATE (lat_estwayp, stat=ierr2)
          DEALLOCATE (long_estwayp, stat=ierr3)
          if ( ierr1 /= 0 .or. ierr2 /= 0 .or.  ierr3 /= 0 ) then
             rc = 3 !
           return
          endif
END SUBROUTINE find_waypointslat
Call graph
find_waypointslat calls built_vec, built_vecsize, get_latlon
get_latlon calls ecef2lla, eci2ecef, get_estimateeci, get_fraction, rad2deg
get_estimateeci calls orbits_track0
orbits_track0 calls orbits_track1, orbits_track2
orbits_track calls find_waypointslat
domasking_ calls orbits_track, orbits_swath
domasking_cs calls orbits_track, orbits_swath
orbits_swath calls orbits_track
run_ calls domasking_, domasking_cs