findnode – MAPL
findnode Function
17 statements
Source File
private function findnode(this, value, last)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
$ target :: value
logical, intent(in) :: last
Return Value type(node), pointer
Calls
Called by
Call graph
findnode calls s_child, s_lessthan, s_ordereq
s_ordereq calls s_lessthan
s_find calls findnode
s_insert calls findnode
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_count calls s_find
s_deepcopy calls s_insert
s_remove calls s_find
m_at calls m_find
m_deepcopy calls s_deepcopy
initialize calls m_at