find_prototype – MAPL
find_prototype Function
27 statements
Source File
private function find_prototype(this, spec, unusable, rc) result(prototype)
Type Bound
NewRegridderManager
Arguments
Type Intent Optional Attributes Name
class(NewRegridderManager), intent(in), target :: this
type(RegridderSpec), intent(in) :: spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(AbstractRegridder), pointer
Calls
Called by
Source Code
   function find_prototype(this, spec, unusable, rc) result(prototype)
      class(AbstractRegridder), pointer :: prototype
      class(NewRegridderManager), target, intent(in) :: this
      type(RegridderSpec), intent(in) :: spec
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: supports
      type(RegridderVectorIterator) :: iter
      _UNUSED_DUMMY(unusable)
      iter = this%prototypes%begin()
      do while (iter /= this%prototypes%end())
         prototype => iter%get()
         supports = prototype%supports(spec,_RC)
         if (supports) then
            _RETURN(_SUCCESS)
         end if
         call iter%next()
      end do
      ! not found
      _RETURN(_FAILURE)
   end function find_prototype
Call graph
find_prototype calls mapl_return, mapl_verify, supports, v_begin, v_iter_get, v_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
supports calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
make_regridder_ calls find_prototype
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
request_data_from_file calls make_regridder
create_from_bundle calls createfilemetadata
initialize calls create_bundle_rh, createfilemetadata
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run calls create_bundle_rh, createfilemetadata