find_index – MAPL
find_index Function
16 statements
Source File
private function find_index(this, value, last) result(idx)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
logical, intent(in) :: last
Return Value integer(kind=SIZE_KIND)
Calls
Called by
Contents
Call graph
find_index calls exists, s_lessthan, s_ordereq
s_ordereq calls s_lessthan
s_find calls find_index
s_insert calls find_index