find_any_file – MAPL
find_any_file Function
38 statements
Source File
private function find_any_file(this, current_time, fail_on_missing, rc) result(filename)
Type Bound
ExtDataAbstractFileHandler
Arguments
Type Intent Optional Attributes Name
class(ExtDataAbstractFileHandler), intent(inout) :: this
type(ESMF_Time), intent(in) :: current_time
logical, intent(in) :: fail_on_missing
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
  function find_any_file(this, current_time, fail_on_missing, rc) result(filename)
     character(len=:), allocatable :: filename
     class(ExtDataAbstractFileHandler), intent(inout) :: this
     type(ESMF_Time), intent(in) :: current_time
     logical, intent(in) :: fail_on_missing
     integer, optional, intent(out) :: rc
     integer :: status, i
     type(ESMF_Time) :: useable_time
     character(len=ESMF_MAXPATHLEN) :: trial_file
     logical :: file_found
     useable_time = current_time
     if (allocated(this%valid_range)) then
        useable_time = this%valid_range(1)
     end if
     call fill_grads_template(trial_file, this%file_template, time=useable_time, _RC)
     inquire(file=trim(trial_file),exist=file_found)
     if (file_found) then
        filename = trial_file
        _RETURN(_SUCCESS)
     end if
     do i=1, MAX_TRIALS
        useable_time = useable_time + this%frequency
        call fill_grads_template(trial_file, this%file_template, time=useable_time, _RC)
        inquire(file=trim(trial_file),exist=file_found)
        if (file_found) exit
     enddo
     if (fail_on_missing) then
        _ASSERT(file_found,"Could not find any file to open to determine metadata after multiple trials")
        filename = trial_file
     else
        filename = 'NONE'
     end if
     _RETURN(_SUCCESS)
   end function find_any_file
Call graph
find_any_file calls mapl_assert, fill_grads_template, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fill_grads_template calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, check_token, evaluate_token
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evaluate_token calls mapl_assert, mapl_verify, ESMF_TimeGet, ESMF_CalendarCreate, ESMF_CalendarDestroy, ESMF_TimeSet, skip_token
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
getlevs calls find_any_file
initialize_ calls getlevs