find – MAPL
find Function
45 statements
Source File
private function find(this, file_name, rc) result(formatter)
Type Bound
ExtDataCollection
Arguments
Type Intent Optional Attributes Name
class(ExtDataCollection), intent(inout), target :: this
character(len=*), intent(in) :: file_name
integer, intent(out), optional :: rc
Return Value type(NetCDF4_FileFormatter), pointer
Calls
Called by
Source Code
  function find(this, file_name, rc) result(formatter)
    type (NetCDF4_FileFormatter), pointer :: formatter
    class (ExtDataCollection), target, intent(inout) :: this
    character(len=*), intent(in) :: file_name
    integer, optional, intent(out) :: rc
    integer, pointer :: file_id
    type (StringIntegerMapIterator) :: iter
    integer :: status
    file_id => this%file_ids%at(file_name)
    if (associated(file_id)) then
       formatter => this%formatters%at(file_id)
    else
       if (this%formatters%size() >= MAX_FORMATTERS) then
          formatter => this%formatters%front()
          call formatter%close(rc=status)
          _VERIFY(status)
          call this%formatters%erase(this%formatters%begin())
          !deallocate(formatter)
          nullify(formatter)
          iter = this%file_ids%begin()
          do while (iter /= this%file_ids%end())
             file_id => iter%value()
             if (file_id == 1) then
                call this%file_ids%erase(iter)
                exit
             end if
             call iter%next()
          end do
          ! Fix the old file_id's accordingly
          iter = this%file_ids%begin()
          do while (iter /= this%file_ids%end())
             file_id => iter%value()
             file_id = file_id -1
             call iter%next()
          end do
       end if
       allocate(formatter)
       call formatter%open(file_name, pFIO_READ, _RC)
       call this%formatters%push_back(formatter)
       deallocate(formatter)
       formatter => this%formatters%back()
       ! size() returns 64-bit integer;  cast to 32 bit for this usage.
       call this%file_ids%insert(file_name, int(this%formatters%size()))
    end if
    _RETURN(_SUCCESS)
  end function find
Call graph
find calls at, insert, next, erase, mapl_return, mapl_verify, v_back, v_begin, v_front, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_erase_one calls erase
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
get_datafromfile calls find
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile
handle_done_collective_prefetch calls read_and_gather, read_and_share