find_bounds – MAPL
find_bounds Function
33 statements
Source File
public function find_bounds(yDim, num_grids) result(bounds)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: yDim
integer, intent(in) :: num_grids
Return Value type(Interval), allocatable, (:)
Called by
Call graph
make_subfields_from_num_grids calls find_bounds, make_subgrids
make_subgrids_from_num_grids calls find_bounds, make_subgrids
make_subfields calls make_subfields_from_num_grids
make_subgrids calls make_subgrids_from_num_grids
create_subobjects calls make_subgrids
make_subfieldbundles_ordinary calls make_subfields
make_substates_from_num_grids calls make_subfields
make_subfieldbundles calls make_subfieldbundles_ordinary
make_substates calls make_substates_from_num_grids
activate_threading calls create_subobjects