flatten_latlon – MAPL
flatten_latlon Subroutine
14 statements
Source File
private subroutine flatten_latlon(lats, lons, lats_1d, lons_1d, im, jm)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: lats(im,jm)
real, intent(in) :: lons(im,jm)
real, intent(inout) :: lats_1d(jm)
real, intent(inout) :: lons_1d(im)
integer, intent(in) :: im
integer, intent(in) :: jm
Called by
Contents
Source Code
flatten_latlon
Source Code
      subroutine flatten_latlon(lats,lons,lats_1d,lons_1d,im,jm)
      implicit none
      integer, intent(in) :: im,jm
      real, intent(in) :: lats(im,jm), lons(im,jm)
      real, intent(inout) :: lats_1d(jm), lons_1d(im)
      integer :: i
      do i =1,im
       lons_1d(i)=lons(i,1)*180./MAPL_PI
      enddo
      do i =1,jm
       lats_1d(i)=lats(1,i)*180./MAPL_PI
      enddo
      return
      end subroutine flatten_latlon
Call graph
orb_mask_lonlat calls flatten_latlon
orb_swath_mask_lonlat calls flatten_latlon
domasking_ calls orb_mask_lonlat, orb_swath_mask_lonlat
run_ calls domasking_