flatten_xy – MAPL
flatten_xy Subroutine
24 statements
Source File
private subroutine flatten_xy(x, y, x_1d, y_1d, im, jm, im_1d, jm_1d, switch)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x(im,jm)
real, intent(in) :: y(im,jm)
real, intent(inout) :: x_1d(im_1d)
real, intent(inout) :: y_1d(jm_1d)
integer, intent(in) :: im
integer, intent(in) :: jm
integer, intent(in) :: im_1d
integer, intent(in) :: jm_1d
logical, intent(in) :: switch
Called by
Source Code
      subroutine flatten_xy(x,y,x_1d,y_1d,im,jm,im_1d,jm_1d,switch)
      implicit none
      integer, intent(in) :: im,jm, im_1d, jm_1d
      real, intent(in) :: x(im,jm), y(im,jm)
      real, intent(inout) :: y_1d(jm_1d), x_1d(im_1d)
      logical, intent(in) :: switch
      integer :: i
      if (.not.switch) then
       do i =1,im_1d
        x_1d(i)=x(i,1)
       enddo
       do i =1,jm_1d
        y_1d(i)=y(1,i)
       enddo
      else if (switch) then
       do i =1,im_1d
        x_1d(i)=x(1,i)
       enddo
       do i =1,jm_1d
        y_1d(i)=y(i,1)
       enddo
      endif
      return
      end subroutine flatten_xy
Call graph
orb_mask_xy calls flatten_xy
orb_swath_mask_xy calls flatten_xy
domasking_cs calls orb_mask_xy, orb_swath_mask_xy
run_ calls domasking_cs