flipCS – MAPL
flipCS Subroutine
30 statements
Source File
private subroutine flipCS(II, JJ, nX, nY, nVal, iFace, iDir)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: II(nVal)
integer, intent(inout) :: JJ(nVal)
integer, intent(in) :: nX
integer, intent(in) :: nY
integer, intent(in) :: nVal
integer, intent(in) :: iFace
integer, intent(in) :: iDir
Called by
Contents
Source Code
flipCS
Source Code
      Subroutine flipCS(II,JJ,nX,nY,nVal,iFace,iDir)
         Integer, Intent(In)     :: nVal
         Integer, Intent(InOut)  :: II(nVal)
         Integer, Intent(InOut)  :: JJ(nVal)
         Integer, Intent(In)     :: nX
         Integer, Intent(In)     :: nY
         Integer, Intent(In)     :: iFace
         Integer, Intent(In)     :: iDir
         Integer                 :: minII, maxII
         Integer                 :: minJJ, maxJJ
         Integer                 :: II0(nVal)
         Integer                 :: JJ0(nVal)
         Integer                 :: I
         Logical                 :: flipII, flipJJ
         _UNUSED_DUMMY(nY)
         ! Copy input
         II0 = II
         JJ0 = JJ
         minJJ = nX*(iFace-1) + 1
         maxJJ = nX*iFace
         minII = 1
         maxII = nX
         flipII = ((iDir.eq.0).or.(iDir.eq.1))
         flipJJ = ((iDir.eq.0).or.(iDir.eq.2))
         Do I=1,nVal
            If ((JJ0(I).ge.minJJ).and.(JJ0(I).le.maxJJ)) Then
               if (flipII) II(I) = minII + (maxII - II0(I))
               if (flipJJ) JJ(I) = minJJ + (maxJJ - JJ0(I))
            End If
         End Do
      End Subroutine flipCS
Call graph
readtilefilenc_file calls flipcs
read_tempest calls readtilefilenc_file
readtilefilenc calls readtilefilenc_file
initialize_subclass calls read_tempest