flip_field – MAPL
flip_field Subroutine
47 statements
Source File
private subroutine flip_field(field, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine flip_field(field,rc)
      type(ESMF_Field), intent(inout) :: field
      integer, intent(out), optional :: rc
      integer :: status,rank
      real(KIND=ESMF_KIND_R4), pointer :: ptr_r4(:,:,:)
      real(KIND=ESMF_KIND_R8), pointer :: ptr_r8(:,:,:)
      real(KIND=ESMF_KIND_R4), allocatable :: alloc_r4(:,:,:)
      real(KIND=ESMF_KIND_R8), allocatable :: alloc_r8(:,:,:)
      type(ESMF_TypeKind_Flag) :: tk
      integer :: vloc,i,lb,ub,ii
      call ESMF_FieldGet(field,rank=rank,typeKind=tk,rc=status)
      _VERIFY(status)
      if (rank/=3) then
         _RETURN(_SUCCESS)
      else
         call ESMF_AttributeGet(field,name="VLOCATION",value=vloc,rc=status)
         _VERIFY(status)
         if (vloc==MAPL_VLocationCenter .or. vloc==MAPL_VLocationEdge) then
            if (tk == ESMF_TYPEKIND_R4) then
               call ESMF_FieldGet(field,farrayPtr=ptr_r4,rc=status)
               _VERIFY(status)
               allocate(alloc_r4,source=ptr_r4)
               lb = lbound(ptr_r4,dim=3)
               ub = ubound(ptr_r4,dim=3)
               ii=0
               do i=lb,ub
                  ptr_r4(:,:,i)=alloc_r4(:,:,ub-ii)
                  ii=ii+1
               enddo
            else if (tk == ESMF_TYPEKIND_R8) then
               call ESMF_FieldGet(field,farrayPtr=ptr_r8,rc=status)
               _VERIFY(status)
               allocate(alloc_r8,source=ptr_r8)
               lb = lbound(ptr_r8,dim=3)
               ub = ubound(ptr_r8,dim=3)
               ii=0
               do i=lb,ub
                  ptr_r8(:,:,i)=alloc_r8(:,:,ub-ii)
                  ii=ii+1
               enddo
            end if
         end if
      end if
      _RETURN(_SUCCESS)
   end subroutine flip_field
Call graph
flip_field calls ESMF_AttributeGet, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_flipped_field calls flip_field
mapl_bundlereadncpar calls flip_field
mapl_varreadncpar calls mapl_bundlereadncpar, mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d, mapl_statevarreadncpar
mapl_statevarwritencpar calls create_flipped_field
mapl_varwritencpar calls mapl_statevarwritencpar
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_statevarreadncpar calls mapl_varreadncpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_staterefresh calls mapl_esmfstatereadfromfile