flip_levels – MAPL
flip_levels Subroutine
16 statements
Source File
private subroutine flip_levels(this, ptrin, ptrout, rc)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout) :: this
real, intent(inout) :: ptrin(:,:,:)
real, intent(inout) :: ptrout(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine flip_levels(this,ptrin,ptrout,rc)
        class(verticaldata), intent(inout) :: this
        real, intent(inout) :: ptrin(:,:,:)
        real, intent(inout) :: ptrout(:,:,:)
        integer, optional, intent(out) :: rc
        integer :: km
        _ASSERT(all(shape(ptrin)==shape(ptrout)),"array must match shape to flip")
        km = size(ptrin,3)
        ptrout(:,:,1:km)=ptrin(:,:,km:1:-1)
        _RETURN(_SUCCESS)
        _UNUSED_DUMMY(this)
     end subroutine flip_levels
Call graph
flip_levels calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
regridscalar calls flip_levels
regridvector calls flip_levels
bundlepost calls regridscalar, regridvector
interp_accumulate_fields calls regridscalar, regridvector
process_data_from_file calls regridscalar, regridvector
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls bundlepost, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls write_to_file
time_ave calls mapl_read_bundle, write_to_file
ut_regridding calls mapl_read_bundle, write_to_file