ForceAllocation – MAPL
ForceAllocation Subroutine
41 statements
Source File
private subroutine ForceAllocation(state, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
ForceAllocation
Source Code
      subroutine ForceAllocation(state,rc)
         type(ESMF_State), intent(inout) :: state
         integer, optional, intent(out) :: rc
         integer :: status
         real, pointer :: ptr3d(:,:,:)
         real, pointer :: ptr2d(:,:)
         integer       :: ii
         integer :: itemcount,dims
         character(len=ESMF_MAXSTR), allocatable :: NameList(:)
         type (ESMF_StateItem_Flag), allocatable :: itemTypeList(:)
         type(ESMF_Field) :: Field
         call ESMF_StateGet(State,itemcount=itemCount,_RC)
         allocate(NameList(itemCount),stat=status)
         _VERIFY(status)
         allocate(itemTypeList(itemCount),stat=status)
         _VERIFY(status)
         call ESMF_StateGet(State,itemNameList=NameList,itemTypeList=itemTypeList,_RC)
         if (itemCount == 0) then
            _RETURN(ESMF_SUCCESS)
         end if
         do ii=1,itemCount
            if (itemTypeList(ii)==ESMF_STATEITEM_FIELD) then
               call ESMF_StateGet(State,trim(nameList(ii)),field,_RC)
               call ESMF_AttributeGet(field,name='DIMS',value=dims,_RC)
               if (dims==MAPL_DimsHorzOnly) then
                  call MAPL_GetPointer(state,ptr2d,trim(nameList(ii)),alloc=.true.,_RC)
               else if (dims==MAPL_DimsHorzVert) then
                  call MAPL_GetPointer(state,ptr3d,trim(nameList(ii)),alloc=.true.,_RC)
               end if
            end if
         enddo
         _RETURN(ESMF_SUCCESS)
      end subroutine ForceAllocation
Call graph
forceallocation calls esmf_stateget, mapl_verify, esmfl_stategetpointertodata, esmf_attributeget, mapl_return
mapl_verify calls mapl_throw_exception
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
esmfl_stategetptrtodatar4_3 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar4_1 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar4_4 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_1 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar4_2 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_2 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_3 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_4 calls esmf_stateget, mapl_verify, mapl_return, mapl_allocatecoupling, esmf_fieldget
mapl_allocatecoupling calls mapl_allocatecoupling
initialize_ calls forceallocation