free_sub_comm – MAPL
free_sub_comm Subroutine
7 statements
Source File
private subroutine free_sub_comm(this)
Type Bound
SimpleCommSplitter
Arguments
Type Intent Optional Attributes Name
class(SimpleCommSplitter), intent(inout) :: this
Calls
Called by
Source Code
   subroutine free_sub_comm(this)
     class ( SimpleCommSplitter), intent(inout) :: this
     integer :: ierror
     if (this%is_split) then
        call MPI_Comm_free(this%sub_comm, ierror)
     endif
  end subroutine free_sub_comm
Call graph
free_sub_comm calls mpi_comm_free
finalize calls free_sub_comm
model_finalize calls free_sub_comm, finalize_io_clients_servers
run_ensemble calls free_sub_comm, finalize_io_clients_servers
start calls free_sub_comm
finalize_io_clients_servers calls finalize
main calls finalize
run calls run_ensemble, finalize_io_clients_servers
time_ave calls finalize
ut_regridding calls finalize
capdriver_main calls run
driver_gethorzijindex calls run
regrid_util calls main
extdata_driver calls run