free_directory_resources – MAPL
free_directory_resources Subroutine
25 statements
Source File
private subroutine free_directory_resources(this, rc)
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine free_directory_resources(this, rc)
      class (DirectoryService), intent(inout) :: this
      integer, optional, intent(out) :: rc
      type (Directory), pointer :: dir
      integer :: ierror
      ! Release resources
      call MPI_Barrier(this%comm, ierror)
      _VERIFY(ierror)
      call this%mutex%free_mpi_resources()
      call MPI_Win_free(this%win_server_directory, ierror)
      _VERIFY(ierror)
      call MPI_Win_free(this%win_client_directory, ierror)
      _VERIFY(ierror)
      if (this%rank == 0) then
         call c_f_pointer(this%server_dir, dir)
         call MPI_Free_mem(dir, ierror)
         _VERIFY(ierror)
         call c_f_pointer(this%client_dir, dir)
         call MPI_Free_mem(dir, ierror)
         _VERIFY(ierror)
      end if
      call Mpi_Comm_free(this%comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
   end subroutine free_directory_resources
Call graph
free_directory_resources calls mpi_barrier, mpi_comm_free, mpi_free_mem, mpi_win_free, free_mpi_resources, mapl_return, mapl_verify
free_mpi_resources calls mpi_comm_free, mpi_free_mem, mpi_win_free, mapl_verify, mpi_type_free
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
finalize calls free_directory_resources
test_connect calls free_directory_resources
test_connect_multi calls free_directory_resources
test_connect_swap_role calls free_directory_resources
test_connect_with_unused_process calls free_directory_resources
test_publish calls free_directory_resources
test_put_directory calls free_directory_resources
test_stress calls free_directory_resources
finalize_io_clients_servers calls finalize
main calls finalize
time_ave calls finalize
ut_regridding calls finalize
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls finalize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run