free_mpi_resources – MAPL
free_mpi_resources Subroutine
16 statements
Source File
private subroutine free_mpi_resources(this)
Type Bound
MpiMutex
Arguments
Type Intent Optional Attributes Name
class(MpiMutex), intent(inout) :: this
Calls
Called by
Source Code
   subroutine free_mpi_resources(this)
      class (MpiMutex), intent(inout) :: this
      logical, pointer :: scratchpad(:)
      integer :: ierror,rc,status
      ! Release resources
      call MPI_Type_free(this%pe_locks_type, ierror)
      _VERIFY(ierror)
      call MPI_Win_free(this%window, ierror)
      _VERIFY(ierror)
      if (this%rank == 0) then
         call c_f_pointer(this%locks_ptr, scratchpad, [this%npes])
         call MPI_Free_mem(scratchpad, ierror)
         _VERIFY(ierror)
      end if
      call Mpi_comm_free(this%comm, ierror)
      _VERIFY(ierror)
   end subroutine free_mpi_resources
Call graph
free_mpi_resources calls mpi_comm_free, mpi_free_mem, mpi_type_free, mpi_win_free, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
free_directory_resources calls free_mpi_resources
finalize calls free_directory_resources
test_connect calls free_directory_resources
test_connect_multi calls free_directory_resources
test_connect_swap_role calls free_directory_resources
test_connect_with_unused_process calls free_directory_resources
test_publish calls free_directory_resources
test_put_directory calls free_directory_resources
test_stress calls free_directory_resources
finalize_io_clients_servers calls finalize
main calls finalize
time_ave calls finalize
ut_regridding calls finalize
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls finalize_io_clients_servers
regrid_util calls main