FREE_FILE – MAPL
FREE_FILE Subroutine
25 statements
Source File
public subroutine FREE_FILE(UNIT, RC)
Arguments
Type Intent Optional Attributes Name
integer :: UNIT
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
FREE_FILE
Source Code
  SUBROUTINE FREE_FILE(UNIT, RC)
    implicit none
    integer         , intent(out), OPTIONAL :: RC
    integer :: UNIT
    if(UNIT < 0) then
      _ASSERT(-UNIT<=LAST_UNIT, 'illegal io unit')
      _ASSERT(MTAKEN(-UNIT), 'illegal io unit')
      MEM_units(-unit)%PREVREC=0
    ELSE
    if (UNIT == STD_OUT_UNIT_NUMBER) return
    if (UNIT /= UNDEF) then
       close(UNIT)
       IF (UNIT.LT.1 .OR. UNIT.GT.LAST_UNIT) THEN
          WRITE (0,*) ' BAD UNIT NUMBER  ZFILCLR  UNIT = ', UNIT
          _RETURN(ESMF_FAILURE)
       ELSE
          TAKEN(UNIT) = .FALSE.
          MTAKEN(UNIT) = .FALSE.
       ENDIF
    end if
    END IF
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE FREE_FILE
Call graph
free_file calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
cap_finalize calls free_file
finalize calls free_file, mapl_genericfinalize
initialize calls free_file, mapl_locstreamcreate
mapl_climupdate calls free_file
mapl_clockinit calls free_file
mapl_esmfstatereadfromfile calls free_file
mapl_esmfstatewritetofile calls free_file
mapl_gradsctlwrite calls free_file
mapl_gridcoordadjustfromfile calls free_file
mapl_locstreamcreatefromfile calls free_file
readrestart calls free_file
run calls free_file, mapl_gradsctlwrite
writerestart calls free_file
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
capture calls mapl_esmfstatewritetofile
finalize_gc calls cap_finalize
initialize_gc calls mapl_clockinit
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore
mapl_genericwrapper calls record_component