gemv_r4 – MAPL
gemv_r4 Subroutine
46 statements
Source File
private subroutine gemv_r4(alpha, A, x, beta, y, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: alpha
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:)
type(ESMF_Field), intent(inout) :: x(:)
real(kind=ESMF_KIND_R4), intent(in) :: beta
type(ESMF_Field), intent(inout) :: y(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
gemv_r4
Source Code
   subroutine gemv_r4(alpha, A, x, beta, y, rc)
      real(kind=ESMF_KIND_R4), intent(in) :: alpha
      real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:)
      type(ESMF_Field), intent(inout) :: x(:)
      real(kind=ESMF_KIND_R4), intent(in) :: beta
      type(ESMF_Field), intent(inout) :: y(:)
      integer, optional, intent(out) :: rc
      logical :: conformable
      integer :: dimcount
      integer, allocatable :: local_element_count(:)
      integer(kind=ESMF_KIND_I8) :: n_gridded, n_ungridded
      integer(kind=ESMF_KIND_I8) :: fp_shape(2)
      real(kind=ESMF_KIND_R4), pointer :: x_ptr(:,:), y_ptr(:,:)
      integer :: ix, jy, kv
      integer :: status
      _ASSERT(size(A,3) == size(x), 'FieldGEMV() - array A not nonformable with x.')
      _ASSERT(size(A,2) == size(y), 'FieldGEMV() - array A not nonformable with y.')
      call verify_typekind(x, ESMF_TYPEKIND_R4)
      call verify_typekind(y, ESMF_TYPEKIND_R4)
      conformable = FieldsAreConformable(x(1), x(2:))
      _ASSERT(conformable, 'FieldGEMV() - fields not conformable.')
      conformable = FieldsAreConformable(x(1), y)
      _ASSERT(conformable, 'FieldGEMV() - fields not conformable.')
      ! Reference dimensions
      local_element_count = FieldGetLocalElementCount(x(1), _RC)
      call ESMF_FieldGet(x(1), dimcount=dimcount, _RC)
      n_gridded = product(local_element_count(1:dimcount))
      n_ungridded = product(local_element_count(dimcount+1:))
      _ASSERT(size(A,1) == n_gridded, 'FieldGEMV() - array A not nonformable with gridded dims.')
      fp_shape = [n_gridded, n_ungridded]
!      y = matmul(A, x)
      do jy = 1, size(y)
         call assign_fptr(y(jy), fp_shape, y_ptr, _RC)
         y_ptr(:,jy) = beta * y_ptr(:,jy)
!         call FieldSCAL(beta, y_ptr(:,jy), _RC)
         do ix = 1, size(x)
            call assign_fptr(x(ix), fp_shape, x_ptr, _RC)
            do kv = 1, n_ungridded
               y_ptr(:,jy) = y_ptr(:,jy) + alpha * A(:,ix,jy) * x_ptr(:,kv)
            end do
         end do
      end do
      _RETURN(_SUCCESS)
   end subroutine gemv_r4
Call graph
gemv_r4 calls esmf_fieldget, assign_fptr, fieldgetlocalelementcount, fieldsareconformable, mapl_assert, verify_typekind, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldgetlocalelementcount calls get_local_element_count
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
verify_typekind calls verify_typekind_array, verify_typekind_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_return, mapl_verify
are_conformable_scalar calls esmf_fieldget, fieldgetlocalelementcount, mapl_return, mapl_verify
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at
get_local_element_count calls esmf_fieldget, mapl_return, mapl_verify, mapl_fieldgetlocalelementcount
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
verify_typekind_array calls verify_typekind, mapl_return, mapl_verify
verify_typekind_scalar calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
fieldgemv calls gemv_r4