generate_file_bounds – MAPL
generate_file_bounds Subroutine
41 statements
Source File
private subroutine generate_file_bounds(this, grid, local_start, global_start, global_count, metaData, rc)
Uses
MAPL_BaseMod
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), allocatable :: local_start(:)
integer, intent(out), allocatable :: global_start(:)
integer, intent(out), allocatable :: global_count(:)
type(FileMetadata), intent(in), optional :: metaData
integer, intent(out), optional :: rc
Calls
Contents
Source Code
generate_file_bounds
Source Code
   subroutine generate_file_bounds(this,grid,local_start,global_start,global_count,metaData,rc)
      use MAPL_BaseMod
      class(CubedSphereGridFactory), intent(inout) :: this
      type(ESMF_Grid),      intent(inout) :: grid
      integer, allocatable, intent(out) :: local_start(:)
      integer, allocatable, intent(out) :: global_start(:)
      integer, allocatable, intent(out) :: global_count(:)
      type(FileMetadata), intent(in), optional :: metaData
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: global_dim(3),i1,j1,in,jn,tile
      character(len=*), parameter :: Iam = MOD_NAME // 'generate_file_bounds'
      logical :: face_format
      integer :: nf
      _UNUSED_DUMMY(this)
      if (present(metadata)) then
         nf = metadata%get_dimension('nf',rc=status)
         if (status == _SUCCESS) then
            face_format = .true.
         else
            face_format = .false.
         end if
      else
         face_format = .true.
      end if
      call MAPL_GridGet(grid,globalCellCountPerDim=global_dim,rc=status)
      _VERIFY(status)
      call MAPL_GridGetInterior(grid,i1,in,j1,jn)
      if (face_format) then
         tile = 1 + (j1-1)/global_dim(1)
         allocate(local_start,source=[i1,j1-(tile-1)*global_dim(1),tile])
         allocate(global_start,source=[1,1,1])
         allocate(global_count,source=[global_dim(1),global_dim(1),6])
      else
         allocate(local_start,source=[i1,j1])
         allocate(global_start,source=[1,1])
         allocate(global_count,source=[global_dim(1),global_dim(2)])
      end if
      _RETURN(_SUCCESS)
   end subroutine generate_file_bounds
Call graph
generate_file_bounds calls mapl_gridget, mapl_verify, mapl_gridgetinterior, mapl_return
mapl_gridget calls mapl_verify, mapl_return, esmf_gridget, esmf_attributeget, mapl_gridhasde
mapl_verify calls mapl_throw_exception
mapl_gridgetinterior calls mapl_gridgetinterior, esmf_gridget, esmf_vmget, mapl_distgridget, esmf_distgridget, esmf_delayoutget
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_gridhasde calls mapl_verify, mapl_return, esmf_gridget, esmf_distgridget, esmf_delayoutget
mapl_distgridget calls mapl_verify, esmf_distgridget