generate_new_decomp – MAPL
generate_new_decomp Function
14 statements
Source File
private function generate_new_decomp(im, nd) result(n)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: im
integer, intent(in) :: nd
Return Value integer
Called by
Contents
Source Code
generate_new_decomp
Source Code
   function generate_new_decomp(im,nd) result(n)
      integer, intent(in) :: im, nd
      integer :: n
      logical :: canNotDecomp
      canNotDecomp = .true.
      n = nd
      do while(canNotDecomp)
         if ( (im/n) < 2) then
            n = n/2
         else
            canNotDecomp = .false.
         end if
      enddo
   end function generate_new_decomp
Call graph
generate_newnxy calls generate_new_decomp
check_and_fill_consistency calls generate_newnxy
initialize_from_config_with_prefix calls check_and_fill_consistency
initialize_from_file_metadata calls check_and_fill_consistency
latlongridfactory_from_parameters calls check_and_fill_consistency
latlongridfactory calls latlongridfactory_from_parameters