generate_file_reference3D – MAPL
generate_file_reference3D Function
27 statements
Source File
private function generate_file_reference3D(this, fpointer, metaData) result(ref)
Uses
iso_c_binding
pFIO
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
real, intent(in), pointer :: fpointer(:,:,:)
type(FileMetadata), intent(in), optional :: metaData
Return Value type(ArrayReference)
Calls
Source Code
   function generate_file_reference3D(this,fpointer,metadata) result(ref)
      use pFIO
      use, intrinsic :: ISO_C_BINDING
      type(ArrayReference) :: ref
      class(CubedSphereGridFactory), intent(inout) :: this
      real, pointer, intent(in) :: fpointer(:,:,:)
      type(FileMetadata), intent(in), optional :: metaData
      type(c_ptr) :: cptr
      real, pointer :: ptr_ref(:,:,:,:,:)
      logical :: face_format
      if (present(metadata)) then
         face_format = metadata%has_dimension('nf')
      else
         face_format = .true.
      end if
      if (face_format) then
         cptr = c_loc(fpointer)
         call C_F_pointer(cptr,ptr_ref,[size(fpointer,1),size(fpointer,2),1,size(fpointer,3),1])
         ref = ArrayReference(ptr_ref)
      else
         ref = ArrayReference(fpointer)
      end if
      _UNUSED_DUMMY(this)
   end function generate_file_reference3D
Call graph
generate_file_reference3d calls has_dimension
has_dimension calls find, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize