generate_file_corner_bounds – MAPL
generate_file_corner_bounds Subroutine
22 statements
Source File
private subroutine generate_file_corner_bounds(this, grid, local_start, global_start, global_count, rc)
Uses
MAPL_BaseMod
Type Bound
TripolarGridFactory
Arguments
Type Intent Optional Attributes Name
class(TripolarGridFactory), intent(inout) :: this
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), allocatable :: local_start(:)
integer, intent(out), allocatable :: global_start(:)
integer, intent(out), allocatable :: global_count(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine generate_file_corner_bounds(this,grid,local_start,global_start,global_count,rc)
      use MAPL_BaseMod
      class (TripolarGridFactory), intent(inout) :: this
      type(ESMF_Grid), intent(inout)      :: grid
      integer, allocatable, intent(out) :: local_start(:)
      integer, allocatable, intent(out) :: global_start(:)
      integer, allocatable, intent(out) :: global_count(:)
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME // 'generate_file_corner_bounds'
      integer :: status
      integer :: global_dim(3), i1,j1,in,jn
      call MAPL_GridGet(grid,globalCellCountPerDim=global_dim,rc=status)
      _VERIFY(status)
      call MAPL_GridGetInterior(grid,i1,in,j1,jn)
      allocate(local_start,source=[i1,j1])
      allocate(global_start,source=[1,1])
      allocate(global_count,source=[global_dim(1)+1,global_dim(2)+1])
      _UNUSED_DUMMY(this)
   end subroutine generate_file_corner_bounds
Call graph
generate_file_corner_bounds calls mapl_gridgetinterior, mapl_gridget, mapl_verify
mapl_gridgetinterior calls mapl_gridgetinterior, mapl_verify, ESMF_AttributeGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_return, ESMF_DELayoutGet, ESMF_VMGet
mapl_gridget calls mapl_verify, ESMF_AttributeGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde, mapl_return
mapl_verify calls mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_verify, mapl_return, mapl_assert, mapl_sort
mapl_gridhasde calls mapl_verify, ESMF_DistGridGet, ESMF_GridGet, mapl_return, ESMF_DELayoutGet
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize