generate_report_profiler – MAPL
generate_report_profiler Function
22 statements
Source File
private function generate_report_profiler(this, p) result(report_lines)
Type Bound
ProfileReporter
Arguments
Type Intent Optional Attributes Name
class(ProfileReporter), intent(in), target :: this
class(BaseProfiler), intent(in), target :: p
Return Value character(len=:), allocatable, (:)
Calls
Called by
Source Code
   function generate_report_profiler(this, p) result(report_lines)
      character(:), allocatable :: report_lines(:)
      class (ProfileReporter), target, intent(in) :: this
      class (BaseProfiler), target, intent(in) :: p
      integer :: width, height
      integer :: i
      character(:), allocatable :: rows(:)
      character(:), allocatable :: header(:)
      class (AbstractMeterNode), pointer :: node
      call this%get_header(header)
      node => p%get_root_node()
      call this%get_rows(node, rows)
      width = this%get_width()
      height = size(header) + size(rows)
      allocate(character(len=width) :: report_lines(height))
      do i = 1, size(header)
         report_lines(i) = header(i)
      end do
      do i = size(header)+1, height
         report_lines(i) = rows(i - size(header))
      end do
   end function generate_report_profiler
Call graph
generate_report_profiler calls get_header, get_root_node, get_rows, get_width
get_header calls get_width, get_header, get_num_rows_header, at, center, get_num_rows_separator, get_separator
get_rows calls get_width, get_num_nodes, get_rows, at
center calls get_width
get_separator calls get_width
v_at_32 calls v_at_size_kind
generate_report calls generate_report
mapl_genericfinalize calls generate_report
report_global_profiler calls generate_report
report_profile calls generate_report
test_simple_report_timer calls generate_report
test_simple_report_timer_b calls generate_report
main calls generate_report, finalize, mapl_finalize
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report, finalize, mapl_finalize
finalize_io_clients_servers calls finalize
finalize_mpi calls mapl_finalize
run calls mapl_finalize
regrid_util calls main
ut_regridding calls finalize, mapl_finalize