generate_report – MAPL
generate_report Subroutine
24 statements
Source File
subroutine generate_report()
Arguments
None
Calls
Called by
Source Code
    subroutine generate_report()
         character(:), allocatable :: report_lines(:)
         integer :: i
         character(1) :: empty(0)
         reporter = ProfileReporter(empty)
         call reporter%add_column(NameColumn(20))
         call reporter%add_column(FormattedTextColumn('Inclusive','(f12.2)', 12, InclusiveColumn('MEAN')))
         call reporter%add_column(FormattedTextColumn('% Incl','(f6.2)', 6, PercentageColumn(InclusiveColumn('MEAN'),'MAX')))
         call reporter%add_column(FormattedTextColumn('Exclusive','(f12.2)', 12, ExclusiveColumn('MEAN')))
         call reporter%add_column(FormattedTextColumn('% Excl','(f6.2)', 6, PercentageColumn(ExclusiveColumn('MEAN'))))
         call reporter%add_column(FormattedTextColumn(' Max Excl)','(f12.2)', 12, ExclusiveColumn('MAX')))
         call reporter%add_column(FormattedTextColumn(' Min Excl)','(f12.2)', 12, ExclusiveColumn('MIN')))
         call reporter%add_column(FormattedTextColumn('Max PE)','(1x,i5.5,1x)', 7, ExclusiveColumn('MAX_PE')))
         call reporter%add_column(FormattedTextColumn('Min PE)','(1x,i5.5,1x)', 7, ExclusiveColumn('MIN_PE')))
        report_lines = reporter%generate_report(t_prof)
         if (mapl_am_I_root()) then
            write(*,'(a)')'Final profile'
            write(*,'(a)')'============='
            do i = 1, size(report_lines)
               write(*,'(a)') report_lines(i)
            end do
            write(*,'(a)') ''
         end if
    end subroutine generate_report
Call graph
generate_report calls mapl_am_i_root, generate_report, add_column
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
add_column calls get_num_rows_header, get_num_rows_separator, get_width, set_width, v_push_back
generate_report_profiler calls get_width, get_header, get_root_node, get_rows
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
v_push_back calls resize, v_grow_to
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
get_header calls get_num_rows_header, get_num_rows_separator, get_width, get_header, at, center, get_separator
get_rows calls get_width, get_num_nodes, get_rows, at
v_grow_to calls v_capacity, v_set_capacity
time_ave calls generate_report