generate_file_corner_bounds – MAPL
generate_file_corner_bounds Subroutine
17 statements
Source File
private subroutine generate_file_corner_bounds(this, grid, local_start, global_start, global_count, rc)
Uses
ESMF
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(inout) :: this
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), allocatable :: local_start(:)
integer, intent(out), allocatable :: global_start(:)
integer, intent(out), allocatable :: global_count(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
generate_file_corner_bounds
Source Code
   subroutine generate_file_corner_bounds(this,grid,local_start,global_start,global_count,rc)
      use esmf
      class (LatLonGridFactory), intent(inout) :: this
      type(ESMF_Grid), intent(inout)      :: grid
      integer, allocatable, intent(out) :: local_start(:)
      integer, allocatable, intent(out) :: global_start(:)
      integer, allocatable, intent(out) :: global_count(:)
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(grid)
      _UNUSED_DUMMY(local_start)
      _UNUSED_DUMMY(global_start)
      _UNUSED_DUMMY(global_count)
      _FAIL('unimplemented')
      _RETURN(_SUCCESS)
   end subroutine generate_file_corner_bounds
Call graph
generate_file_corner_bounds calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize