generic_entry_point – MAPL
generic_entry_point Subroutine
36 statements
Source File
private subroutine generic_entry_point(gridcomp, import, export, clock, rc)
$ phase_name => component%init_phase_map%at(phase) $ if(MAPL_Assert(associated(phase_name),’no such phase’,1,”/home/runner/work/MAPL/MAPL/docs/Ford/../../generic/MaplGenericComponent.F90”,172 ,rc)) return $ phase_name = component%run_phase_map%at(phase) $ if(MAPL_Assert(associated(phase_name),’no such phase’,1,”/home/runner/work/MAPL/MAPL/docs/Ford/../../generic/MaplGenericComponent.F90”,178 ,rc)) return $ phase_name = component%finalize_phase_map%at(phase) $ if(MAPL_Assert(associated(phase_name),’no such phase’,1,”/home/runner/work/MAPL/MAPL/docs/Ford/../../generic/MaplGenericComponent.F90”,184 ,rc)) return
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gridcomp
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
generic_entry_point
Source Code
   subroutine generic_entry_point(gridcomp, import, export, clock, rc)
      type(ESMF_GridComp), intent(inout) :: gridcomp
      type(ESMF_State), intent(inout) :: import
      type(ESMF_State), intent(inout) :: export
      type(ESMF_Clock), intent(inout) :: clock
      integer, optional, intent(out) :: rc
      character(len=ESMF_MAXSTR) :: name
      integer :: phase
      type(ESMF_Method_Flag) :: method
      integer :: status
      class(MaplComponent), pointer :: component
      type :: ComponentWrapper
         class(MaplComponent), pointer :: component
      end type ComponentWrapper
      type(ComponentWrapper) :: wrapper
      character(:), pointer :: phase_name
      call ESMF_UserCompGetInternalState(gridcomp, "MaplComponent", wrapper, status)
      _VERIFY(status)
      component => wrapper%component
      call ESMF_GridCompGet( gridcomp, name=name, currentPhase=phase, currentMethod=method, _RC)
      if (method == ESMF_METHOD_INITIALIZE) then
!!$         phase_name => component%init_phase_map%at(phase)
!!$         _ASSERT(associated(phase_name),'no such phase')
         call component%initialize(import, export, clock, phase_name, _RC)
      else if (method == ESMF_METHOD_RUN) then
!!$         phase_name = component%run_phase_map%at(phase)
!!$         _ASSERT(associated(phase_name),'no such phase')
         call component%run(import, export, clock, phase_name, _RC)
      else if (method == ESMF_METHOD_FINALIZE) then
!!$         phase_name = component%finalize_phase_map%at(phase)
!!$         _ASSERT(associated(phase_name),'no such phase')
         call component%finalize(import, export, clock, phase_name, _RC)
      else
         _FAIL('unknown value for ESMF_METHOD_FLAG')
      end if
      _RETURN(_SUCCESS)
   end subroutine generic_entry_point
Call graph
generic_entry_point calls ESMF_GridCompGet, ESMF_UserCompGetInternalState, mapl_assert, finalize, initialize, mapl_return, mapl_verify, run
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize