generate_newnxy – MAPL
generate_newnxy Subroutine
24 statements
Source File
private subroutine generate_newnxy(this, unusable, rc)
Uses
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(inout), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine generate_newnxy(this,unusable,rc)
      use MAPL_BaseMod, only: MAPL_DecomposeDim
      class (LatLonGridFactory), target, intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: n
      _UNUSED_DUMMY(unusable)
      n = this%im_world/this%nx
      if (n < 2) then
         this%nx = generate_new_decomp(this%im_world,this%nx)
         deallocate(this%ims)
         allocate(this%ims(0:this%nx-1))
         call MAPL_DecomposeDim(this%im_world, this%ims, this%nx)
      end if
      n = this%jm_world/this%ny
      if (n < 2) then
         this%ny = generate_new_decomp(this%jm_world,this%ny)
         deallocate(this%jms)
         allocate(this%jms(0:this%ny-1))
         call MAPL_DecomposeDim(this%jm_world, this%jms, this%ny)
      end if
      _RETURN(_SUCCESS)
   end subroutine generate_newnxy
Call graph
generate_newnxy calls mapl_decomposedim, generate_new_decomp, mapl_return
mapl_decomposedim calls mapl_decomposedim
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
check_and_fill_consistency calls generate_newnxy
initialize_from_config_with_prefix calls check_and_fill_consistency
initialize_from_file_metadata calls check_and_fill_consistency
latlongridfactory_from_parameters calls check_and_fill_consistency
latlongridfactory calls latlongridfactory_from_parameters