get_component – MAPL
get_component Function
5 statements
Source File
private function get_component(this) result(component)
Type Bound
BaseFrameworkComponent
Arguments
Type Intent Optional Attributes Name
class(BaseFrameworkComponent), intent(in), target :: this
Return Value class(AbstractComponent), pointer
Called by
Source Code
   function get_component(this) result(component)
      class(AbstractComponent), pointer :: component
      class(BaseFrameworkComponent), target, intent(in) :: this
      component => this%component
   end function get_component
Call graph
get_logger calls get_component
set_logger calls get_component
stub calls get_component
addchild_preamble calls set_logger
mapl_genericstateset calls set_logger
mapl_getlogger_gc calls get_logger
mapl_getlogger_meta calls get_logger
mapl_getlogger calls mapl_getlogger_gc, mapl_getlogger_meta
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
mapl_genericstatesetfromgc calls mapl_genericstateset
mapl_addchild calls addchildfromdsometa, addchildfrommeta
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta
initialize_ calls mapl_getlogger
initialize_gc calls mapl_getlogger, mapl_set
mapl_capgridcompcreate calls mapl_set
mapl_clockinit calls mapl_getlogger
perpetual_clock calls mapl_getlogger
run_component_driver calls mapl_set
warn_empty calls mapl_getlogger