get_actual_timer_name – MAPL
get_actual_timer_name Function
5 statements
Source File
private function get_actual_timer_name(name) result(actual_name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Return Value character(len=:), allocatable
Called by
Source Code
   function get_actual_timer_name(name) result(actual_name)
      character(:), allocatable :: actual_name
      character(*), intent(in) :: name
      actual_name = trim(name(verify(name, '-'):))
   end function get_actual_timer_name
Call graph
mapl_genericstateclockoff calls get_actual_timer_name
mapl_genericstateclockon calls get_actual_timer_name
mapl_timeroff calls mapl_genericstateclockoff
mapl_timeron calls mapl_genericstateclockon
append_file calls mapl_timeroff, mapl_timeron
create_geosat_grid_find_mask calls mapl_timeroff, mapl_timeron, create_geosat_grid_find_mask
initialize_ calls mapl_timeroff, mapl_timeron, mapl_genericinitialize
initialize calls mapl_timeroff, mapl_timeron, mapl_genericinitialize
mapl_genericfinalize calls mapl_timeroff, mapl_timeron
mapl_genericinitialize calls mapl_timeroff, mapl_timeron
mapl_genericrecord calls mapl_timeroff, mapl_timeron
mapl_genericrefresh calls mapl_timeroff, mapl_timeron, mapl_genericrefresh
mapl_genericrunchildren calls mapl_timeroff, mapl_timeron
mapl_genericstaterestore calls mapl_timeron, mapl_genericstaterestore
mapl_genericwrapper calls mapl_timeroff, mapl_timeron
regrid_append_file calls mapl_timeroff, mapl_timeron, regrid_append_file
run calls mapl_timeroff, mapl_timeron, append_file
run_ calls mapl_timeroff, mapl_timeron
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
refresh_state calls mapl_genericstaterestore