get_test_framework_resource – MAPL
get_test_framework_resource Subroutine
17 statements
Source File
private subroutine get_test_framework_resource(STATE, is_test_framework, is_test_framework_driver, is_grid_capture, restore_export, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
logical, intent(inout) :: is_test_framework
logical, intent(inout) :: is_test_framework_driver
logical, intent(inout) :: is_grid_capture
logical, intent(inout) :: restore_export
integer, intent(out) :: rc
Calls
Called by
Source Code
   subroutine get_test_framework_resource(STATE, is_test_framework, is_test_framework_driver, &
                                          is_grid_capture, restore_export, rc)
     type (MAPL_MetaComp), intent(inout) :: STATE
     logical, intent(inout) :: is_test_framework, is_test_framework_driver
     logical, intent(inout) :: is_grid_capture, restore_export
     integer, intent(out) :: rc
     integer :: status
     call MAPL_GetResource(STATE, is_test_framework, label='TEST_FRAMEWORK:', default=.false., _RC)
     call MAPL_GetResource(STATE, is_test_framework_driver, label='TEST_FRAMEWORK_DRIVER:', default=.false., _RC)
     call MAPL_GetResource(STATE, is_grid_capture, label='GRID_CAPTURE:', default=.false., _RC)
     call MAPL_GetResource(STATE, restore_export, label='RESTORE_EXPORT_STATE:', default=.false., _RC)
     _RETURN(_SUCCESS)
   end subroutine get_test_framework_resource
Call graph
get_test_framework_resource calls mapl_getresource, mapl_return, mapl_verify
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_getresourcefromconfig_array calls mapl_return, mapl_verify, mapl_getresource_config_array
mapl_getresourcefromconfig_scalar calls mapl_return, mapl_verify, mapl_getresource_config_scalar
mapl_getresourcefrommapl_array calls mapl_return, mapl_verify, mapl_getresource_config_array
mapl_getresourcefrommapl_scalar calls mapl_return, mapl_verify, mapl_getresource_config_scalar
mapl_throw_exception calls initialize
mapl_getresource_config_array calls mapl_return, mapl_verify, ESMF_ConfigGetAttribute, array_format, mapl_assert, compare_all, get_actual_label, get_print_settings, make_string_character_array, print_resource, set_do_print
mapl_getresource_config_scalar calls mapl_return, mapl_verify, ESMF_ConfigGetAttribute, mapl_assert, get_actual_label, get_print_settings, make_string_character, print_resource, set_do_print
record_component calls get_test_framework_resource
mapl_genericwrapper calls record_component