get_model_duration – MAPL
get_model_duration Function
8 statements
Source File
private function get_model_duration(this, rc) result(duration)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp) :: this
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
  function get_model_duration(this, rc) result (duration)
    class (MAPL_CapGridComp) :: this
    integer, optional, intent(out) :: rc
    integer :: duration
    duration = this%nsteps * this%heartbeat_dt
    _RETURN(ESMF_SUCCESS)
  end function get_model_duration
Call graph
get_model_duration calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run_model calls get_model_duration
run_member calls run_model
run_ensemble calls run_member
run calls run_ensemble