get_interpolating_variable – MAPL
get_interpolating_variable Subroutine
8 statements
Source File
private subroutine get_interpolating_variable(this, bundle, rc)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout) :: this
type(ESMF_FieldBundle), intent(inout) :: bundle
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine get_interpolating_variable(this,bundle,rc)
        class(verticalData), intent(inout) :: this
        type(ESMF_FieldBundle), intent(inout) :: bundle
        integer, optional, intent(out) :: rc
        integer :: status
        call ESMF_FieldBundleGet(bundle,fieldName=trim(this%vvar),field=this%interp_var,rc=status)
        _VERIFY(status)
     end subroutine get_interpolating_variable
Call graph
get_interpolating_variable calls esmf_fieldbundleget, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
add_metadata_route_handle calls get_interpolating_variable
create_bundle_rh calls get_interpolating_variable
createfilemetadata calls get_interpolating_variable
initialize_ calls get_interpolating_variable
create_from_bundle calls createfilemetadata
initialize calls add_metadata_route_handle, create_bundle_rh, createfilemetadata
run calls create_bundle_rh, createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main