get_file – MAPL
get_file Subroutine
37 statements
Source File
private subroutine get_file(this, filename, input_time, shift, allow_missing_file, ghost_time, rc)
Type Bound
ExtDataSimpleFileHandler
Arguments
Type Intent Optional Attributes Name
class(ExtDataSimpleFileHandler), intent(inout) :: this
character(len=*), intent(out) :: filename
type(ESMF_Time) :: input_time
integer, intent(in) :: shift
logical, intent(in) :: allow_missing_file
type(ESMF_Time), intent(out), optional :: ghost_time
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_file(this,filename,input_time,shift,allow_missing_file,ghost_time,rc)
      class(ExtdataSimpleFileHandler), intent(inout) :: this
      character(len=*), intent(out) :: filename
      type(ESMF_Time) :: input_time
      integer, intent(in) :: shift
      logical, intent(in) :: allow_missing_file
      type(ESMF_Time), intent(out), optional :: ghost_time
      integer, intent(out), optional :: rc
      type(ESMF_Time) :: ftime
      integer :: n,status
      logical :: file_found
      integer(ESMF_KIND_I8) :: interval_seconds
      call ESMF_TimeIntervalGet(this%frequency,s_i8=interval_seconds)
      if (interval_seconds==0) then
         ! time is not representable as absolute time interval (month, year etc...) do this
         ! brute force way. Not good but ESMF leaves no choice
         ftime=this%reff_time
         do while (ftime <= input_time)
            ftime = ftime + this%frequency
         enddo
         ftime=ftime -this%frequency + shift*this%frequency
      else
         n = (input_time-this%reff_time)/this%frequency
         ftime = this%reff_time+(n+shift)*this%frequency
      end if
      call fill_grads_template(filename,this%file_template,time=ftime,_RC)
      inquire(file=trim(filename),exist=file_found)
      if (.not.file_found) then
         if (allow_Missing_file) then
            filename = file_not_found
            if (present(ghost_time)) ghost_time = ftime
         else
            _FAIL("get_file did not file a file using: "//trim(this%file_template))
         end if
      end if
      _RETURN(_SUCCESS)
   end subroutine get_file
Call graph
get_file calls ESMF_TimeIntervalGet, mapl_assert, fill_grads_template, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fill_grads_template calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, check_token, evaluate_token
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evaluate_token calls mapl_assert, mapl_verify, ESMF_TimeGet, ESMF_CalendarCreate, ESMF_CalendarDestroy, ESMF_TimeSet, skip_token
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_file_bracket calls get_file