get_rows – MAPL
get_rows Subroutine
23 statements
Source File
private recursive subroutine get_rows(this, node, rows)
Type Bound
MultiColumn
Arguments
Type Intent Optional Attributes Name
class(MultiColumn), intent(in) :: this
class(AbstractMeterNode), intent(in), target :: node
character(len=:), intent(out), allocatable :: rows(:)
Calls
Called by
Source Code
   recursive subroutine get_rows(this, node, rows)
      class (MultiColumn), intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      character(:), allocatable, intent(out) :: rows(:)
      integer :: i, j
      integer :: w0, w1
      class(TextColumn), pointer :: c
      integer :: total_width, height
      character(:), allocatable :: column(:)
      total_width = this%get_width()
      height = node%get_num_nodes()
      allocate(character(total_width) :: rows(height))
      w0 = 1
      do i = 1, this%columns%size()
         c => this%columns%at(i)
         w1 = w0 + c%get_width() - 1
         call c%get_rows(node, column)
         do j = 1, height
            rows(j)(w0:w1) = column(j)
         end do
         w0 = w1 + 1
      end do
   end subroutine get_rows
Call graph
get_rows calls get_num_nodes, get_rows, at, get_width
v_at_32 calls v_at_size_kind
generate_report_profiler calls get_rows
generate_report calls generate_report
mapl_genericfinalize calls generate_report
report_global_profiler calls generate_report
report_profile calls generate_report
test_simple_report_timer calls generate_report
test_simple_report_timer_b calls generate_report
main calls generate_report
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report