get_eta_r4 – MAPL
get_eta_r4 Subroutine
26 statements
Source File
private subroutine get_eta_r4(this, ptop, pint, ak, bk, unusable, rc)
Type Bound
EtaHybridVerticalCoordinate
Arguments
Type Intent Optional Attributes Name
class(EtaHybridVerticalCoordinate), intent(in) :: this
real(kind=REAL32), intent(out) :: ptop
real(kind=REAL32), intent(out) :: pint
real(kind=REAL32), intent(out) :: ak(:)
real(kind=REAL32), intent(out) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Contents
Source Code
get_eta_r4
Source Code
   subroutine get_eta_r4(this, ptop, pint, ak, bk, unusable,rc)
      class(EtaHybridVerticalCoordinate), intent(in) :: this
      real(kind=REAL32), intent(out) :: ak(:)
      real(kind=REAL32), intent(out) :: bk(:)
      real(kind=REAL32), intent(out) :: ptop ! model top (Pa)
      real(kind=REAL32), intent(out) :: pint ! transition to p (Pa)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      real(kind=REAL64), allocatable :: ak8(:)
      real(kind=REAL64), allocatable :: bk8(:)
      real(kind=REAL64) :: ptop8 ! model top (Pa)
      real(kind=REAL64) :: pint8 ! transition to p (Pa)
      integer :: num_levels
      _UNUSED_DUMMY(unusable)
      num_levels = this%num_levels
      allocate(ak8(num_levels+1))
      allocate(bk8(num_levels+1))
      call this%get_eta(ptop8, pint8, ak8, bk8)
      ak = real(ak8, kind=REAL32)
      bk = real(bk8, kind=REAL32)
      ptop = ptop8
      pint = pint8
      deallocate(ak8,bk8)
     _RETURN(_SUCCESS)
   end subroutine get_eta_r4
Call graph
get_eta_r4 calls get_eta, mapl_return
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
get_eta_onestep_r4 calls get_eta, etahybridverticalcoordinate, mapl_verify
get_eta_onestep_r8 calls get_eta, etahybridverticalcoordinate, mapl_verify
mapl_throw_exception calls initialize
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_cfg, new_etahybridverticalcoordinate_by_file
mapl_verify calls mapl_throw_exception