get_units – MAPL
get_units Function
24 statements
Source File
function get_units(bundle, rc) result(units)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
integer, intent(out), optional :: rc
Return Value character(len=ESMF_MAXSTR), allocatable, (:)
Calls
Called by
Contents
Source Code
get_units
Source Code
   function get_units(bundle,rc) result(units)
      character(len=ESMF_MAXSTR), allocatable :: units(:)
      type(ESMF_FieldBundle), intent(in) :: bundle
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=ESMF_MAXSTR), allocatable :: field_list(:)
      type(ESMF_Field) :: field
      integer :: i,num_fields
      call ESMF_FieldBundleGet(bundle,fieldCount=num_fields,_RC)
      allocate(field_list(num_fields))
      allocate(units(num_fields))
      call ESMF_FieldBundleGet(bundle,fieldNameList=field_list,_RC)
      do i=1,num_fields
         call ESMF_FieldBundleGet(bundle,field_list(i),field=field,_RC)
         call ESMF_AttributeGet(field,name='UNITS',value=units(i),_RC)
      enddo
      if (present(rc)) then
         RC=_SUCCESS
      end if
   end function get_units
Call graph
get_units calls esmf_fieldbundleget, mapl_verify, esmf_attributeget, mapl_abort
mapl_verify calls mapl_throw_exception
mapl_abort calls mpi_abort
mapl_throw_exception calls initialize
time_ave calls get_units