get_child_by_index – MAPL
get_child_by_index Function
8 statements
Source File
private function get_child_by_index(this, i) result(child)
Type Bound
ConcreteComposite
Arguments
Type Intent Optional Attributes Name
class(ConcreteComposite), intent(in), target :: this
integer, intent(in) :: i
Return Value class(AbstractComposite), pointer
Calls
Called by
Source Code
   function get_child_by_index(this, i) result(child)
      class(AbstractComposite), pointer :: child
      class(ConcreteComposite), target, intent(in) :: this
      integer, intent(in) :: i
      character(:), pointer :: child_name
      child_name => this%children_names%of(i)
      child => this%get_child(child_name)
   end function get_child_by_index
Call graph
get_child_by_index calls get_child, of
get_child_by_name calls m_at, get_child
m_at calls m_find
test_get_child calls get_child
activate_threading calls get_child
deactivate_threading calls get_child
get_ith_child calls get_child
stub_child calls get_child