get_var_string_1 – MAPL
get_var_string_1 Subroutine
28 statements
Source File
private subroutine get_var_string_1(this, var_name, values, unusable, group_name, start, count, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(out) :: values(:)
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: group_name
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Call graph
get_var_string_1 calls mapl_assert, nf90_inq_ncid, nf90_inq_varid, mapl_return, pfio_nf90_get_var_string
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
pfio_nf90_get_var_string calls c_f_pfio_get_var_string
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize