get_item_type – MAPL
get_item_type Function
47 statements
Source File
private function get_item_type(this, item_name, unusable, rc) result(item_type)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(inout), target :: this
character(len=*), intent(in) :: item_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function get_item_type(this,item_name,unusable,rc) result(item_type)
      class(ExtDataConfig), target, intent(inout) :: this
      character(len=*), intent(in) :: item_name
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: item_type
      type(ExtDataRule), pointer :: rule
      type(ExtDataDerived), pointer :: derived
      type(ExtDataRuleMapIterator) :: rule_iterator
      character(len=:), pointer :: key
      character(len=:), allocatable :: found_key
      logical :: found_rule
      _UNUSED_DUMMY(unusable)
      item_type=ExtData_not_found
      found_rule = .false.
      rule_iterator = this%rule_map%begin()
      do while(rule_iterator /= this%rule_map%end())
         key => rule_iterator%key()
         if (index(key,trim(item_name))/=0) then
            found_rule = .true.
            found_key = key
            exit
         end if
         call rule_iterator%next()
      enddo
      if (found_rule) then
         rule => this%rule_map%at(found_key)
         if (associated(rule)) then
            if (allocated(rule%vector_component)) then
               if (rule%vector_component=='EW') then
                  item_type=Primary_Type_Vector_comp1
               else if (rule%vector_component=='NS') then
                  item_type=Primary_Type_Vector_comp2
               end if
            else
               item_type=Primary_Type_scalar
            end if
         end if
      end if
      derived => this%derived_map%at(trim(item_name))
      if (associated(derived)) then
         item_type=derived_type
         found_rule = .true.
      end if
      _RETURN(_SUCCESS)
   end function get_item_type
Call graph
get_item_type calls m_at, m_begin, m_key, m_next, mapl_return
m_at calls m_find
m_begin calls s_begin
m_next calls s_next
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
s_find calls at, exists, find_index, s_ordereq
initialize_ calls get_item_type