get_num_cycles – MAPL
get_num_cycles Function
4 statements
Source File
private function get_num_cycles(this) result(num_cycles)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_num_cycles(this) result(num_cycles)
      class(AdvancedMeter), intent(in) :: this
      num_cycles = this%num_cycles
   end function get_num_cycles
Call graph
get_mean_cycle calls get_num_cycles
reduce_mpi calls get_num_cycles
test_accumulate calls get_num_cycles, add_cycle
test_add_cycle calls get_num_cycles, add_cycle
test_get_num_cycles calls get_num_cycles, reduce, add_cycle
test_reset calls get_num_cycles, add_cycle
add_cycle calls get_mean_cycle
get_relative_deviation calls get_mean_cycle
test_get_mean_cycle calls get_mean_cycle, add_cycle
reduce_global calls reduce
stop calls add_cycle
test_get_max calls reduce, add_cycle
test_get_max_cycle calls add_cycle
test_get_min calls reduce, add_cycle
test_get_min_cycle calls add_cycle
test_get_standard_deviation calls add_cycle
test_get_total calls reduce, add_cycle
test_trivial calls reduce, add_cycle