get_regrid_method – MAPL
get_regrid_method Function
4 statements
Source File
private function get_regrid_method(this) result(method)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_regrid_method(this) result(method)
      class (AbstractRegridder), intent(in) :: this
      method = this%spec%regrid_method
   end function get_regrid_method
Call graph
create_bundle_rh calls get_regrid_method
createfilemetadata calls get_regrid_method
create_from_bundle calls createfilemetadata
initialize calls create_bundle_rh, createfilemetadata
run calls create_bundle_rh, createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main