get_pressure_levels_r4 – MAPL
get_pressure_levels_r4 Subroutine
25 statements
Source File
private subroutine get_pressure_levels_r4(this, pressure_levels, unusable, reference_pressure, rc)
Type Bound
EtaHybridVerticalCoordinate
Arguments
Type Intent Optional Attributes Name
class(EtaHybridVerticalCoordinate), intent(in) :: this
real(kind=REAL32), intent(out) :: pressure_levels(:)
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=REAL32), intent(in), optional :: reference_pressure
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_pressure_levels_r4(this, pressure_levels, unusable, reference_pressure, rc)
      class(EtaHybridVerticalCoordinate), intent(in) :: this
      real(kind=REAL32), intent(out) :: pressure_levels(:)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      real(kind=REAL32), optional, intent(in) :: reference_pressure
      integer, optional, intent(out) :: rc
      real(kind=REAL64) :: p0
      integer :: num_levels
      real(kind=REAL64), allocatable :: plevels(:)
      _UNUSED_DUMMY(unusable)
      num_levels = this%num_levels
      _ASSERT(size(pressure_levels) == num_levels, 'incorrect array size for pressure_levels dummy argument')
      if (present(reference_pressure)) then
         p0 = reference_pressure
      else
         p0 = this%ref_pressure
      end if
      allocate(plevels(num_levels))
      call this%get_pressure_levels(plevels, reference_pressure=p0)
      pressure_levels = real(plevels,kind=REAL32)
      deallocate(plevels)
   end subroutine get_pressure_levels_r4
Call graph
get_pressure_levels_r4 calls mapl_assert, get_pressure_levels
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_pressure_levels_r8 calls mapl_assert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_pressures_r4_3d calls get_pressure_levels
get_pressures_r8_3d calls get_pressure_levels