get_communicator – MAPL
get_communicator Function
4 statements
Source File
private function get_communicator(this) result(communicator)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_communicator(this) result(communicator)
      class (AbstractServer), intent(in) :: this
      communicator = this%comm
   end function get_communicator
Call graph
connect_to_client calls get_communicator
publish calls get_communicator
initialize calls connect_to_client, publish
test_connect calls connect_to_client, publish
test_connect_multi calls connect_to_client, publish
test_connect_swap_role calls connect_to_client, publish
test_connect_with_unused_process calls connect_to_client, publish
test_publish calls publish
test_stress calls connect_to_client, publish
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main