get_export_state – MAPL
get_export_state Function
11 statements
Source File
private function get_export_state(this) result(export_state)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(in), target :: this
Return Value type(ESMF_State), pointer
Calls
Called by
Source Code
   function get_export_state(this) result(export_state)
     class(MaplGenericComponent), target, intent(in) :: this
     type(ESMF_State), pointer :: export_state
     integer :: thread
     if (.NOT. this%is_threading_active()) then
        export_state => this%export_state
     else
        thread = get_current_thread()
        export_state => this%subcomponents(thread+1)%export_state
     end if
   end function get_export_state
Call graph
get_export_state calls get_current_thread, is_threading_active
get_child_export_state calls get_export_state
omp_driver calls get_export_state
addchild_preamble calls get_child_export_state
mapl_adjustisneeded calls get_child_export_state, mapl_adjustisneeded
mapl_genericfinalize calls get_child_export_state
mapl_genericinitialize calls get_child_export_state, mapl_adjustisneeded
mapl_genericrecord calls get_child_export_state
mapl_genericrefresh calls get_child_export_state, mapl_genericrefresh
mapl_genericrunchildren calls get_child_export_state
mapl_genericruncouplers calls get_child_export_state
mapl_genericstateget calls get_child_export_state
mapl_genericstaterestore calls get_child_export_state, mapl_genericstaterestore
mapl_genericstatesave calls get_child_export_state, mapl_genericstatesave
mapl_genericwrapper calls omp_driver
run_component_driver calls get_child_export_state
mapl_get calls mapl_genericstateget
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
main calls run_component_driver
mapl_readforcingx calls mapl_genericstateget
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore