get_import_state – MAPL
get_import_state Function
11 statements
Source File
private function get_import_state(this) result(import_state)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(in), target :: this
Return Value type(ESMF_State), pointer
Calls
Called by
Source Code
   function get_import_state(this) result(import_state)
     class(MaplGenericComponent), target, intent(in) :: this
     type(ESMF_State), pointer :: import_state
     integer :: thread
     if (.NOT. this%is_threading_active()) then
        import_state => this%import_state
     else
        thread = get_current_thread()
        import_state => this%subcomponents(thread+1)%import_state
     end if
   end function get_import_state
Call graph
get_import_state calls get_current_thread, is_threading_active
get_child_import_state calls get_import_state
omp_driver calls get_import_state
addchild_preamble calls get_child_import_state
mapl_genericfinalize calls get_child_import_state
mapl_genericinitialize calls get_child_import_state
mapl_genericrecord calls get_child_import_state
mapl_genericrefresh calls get_child_import_state, mapl_genericrefresh
mapl_genericrunchildren calls get_child_import_state
mapl_genericruncouplers calls get_child_import_state
mapl_genericstateget calls get_child_import_state
mapl_genericstaterestore calls get_child_import_state, mapl_genericstaterestore
mapl_genericstatesave calls get_child_import_state, mapl_genericstatesave
mapl_genericwrapper calls omp_driver
mapl_importstateget calls get_child_import_state, mapl_importstateget
run_component_driver calls get_child_import_state
mapl_get calls mapl_genericstateget
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
get_field_from_import calls mapl_importstateget
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
main calls run_component_driver
mapl_readforcingx calls mapl_genericstateget
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore