get_row_dist – MAPL
get_row_dist Subroutine
16 statements
Source File
private subroutine get_row_dist(this, node, row)
Type Bound
StdDevColumn
Arguments
Type Intent Optional Attributes Name
class(StdDevColumn), intent(in), target :: this
class(AbstractMeterNode), intent(in), target :: node
class(*), intent(out), allocatable :: row
Calls
Called by
Source Code
   subroutine get_row_dist(this, node, row)
      class (StdDevColumn), target, intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      class(*), allocatable, intent(out) :: row
      class(AbstractMeter), pointer :: m
      type(DistributedStatistics) :: stats
      type(DistributedReal64) :: std_deviation
      m => node%get_meter()
      select type (m)
      class is (DistributedMeter)
         stats = m%get_statistics()
         std_deviation = stats%sum_square_deviation
         print*,__FILE__,__LINE__,'std deviation not fully implemented'
         call this%fill_row(std_deviation, this%option, row)
      end select
   end subroutine get_row_dist
Call graph
get_row_dist calls get_meter, get_statistics, fill_row
get_row calls get_row_dist