get_local_size – MAPL
get_local_size Function
13 statements
Source File
private function get_local_size(x, rc) result(sz)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
Return Value integer(kind=ESMF_KIND_I8)
Calls
Called by
Contents
Source Code
get_local_size
Source Code
   function get_local_size(x, rc) result(sz)
      integer(kind=ESMF_KIND_I8) :: sz
      type(ESMF_Field), intent(inout) :: x
      integer, optional, intent(out) :: rc
      integer :: status
      integer, allocatable :: element_count(:)
      sz = 0
      element_count = FieldGetLocalElementCount(x, _RC)
      sz = int(product(element_count), kind=ESMF_KIND_I8)
      _RETURN(_SUCCESS)
   end function get_local_size
Call graph
get_local_size calls fieldgetlocalelementcount, mapl_return, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
get_local_element_count calls mapl_return, mapl_verify, esmf_fieldget, mapl_fieldgetlocalelementcount
mapl_throw_exception calls initialize
mapl_fieldgetlocalelementcount calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert
fieldgetlocalsize calls get_local_size
assign_fptr_r4_rank1 calls fieldgetlocalsize
assign_fptr_r8_rank1 calls fieldgetlocalsize
copy calls fieldgetlocalsize
test_fieldgetlocalsize calls fieldgetlocalsize
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r8_rank1
fieldcopy calls copy
copy_broadcast calls copy