get_values – MAPL
get_values Function
12 statements
Source File
private function get_values(this, rc) result(values)
get 1d , need get_shape to get back to original array
Type Bound
UnlimitedEntity
Arguments
Type Intent Optional Attributes Name
class(UnlimitedEntity), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value class(*), pointer, (:)
Calls
Called by
Source Code
   function get_values(this, rc) result(values)
      class (UnlimitedEntity), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      class (*), pointer :: values(:)
      if (allocated(this%values)) then
        values => this%values
      else
        values => null()
      end if
      _RETURN(_SUCCESS)
   end function get_values
Call graph
get_values calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
equal calls get_values
get_attribute_int32 calls get_values
get_attribute_int64 calls get_values
get_attribute_real32 calls get_values
get_attribute_real64 calls get_values
initialize_from_file_metadata calls get_values
mapl_readtilingnc4 calls get_values
put_attributes calls get_values
put_var_attributes calls get_values
test_get_attribute_real_double calls get_values
test_get_attribute_vector calls get_values
write_const_variables calls get_values
write_data calls get_values
def_variables calls put_var_attributes
get_var_attr_int32 calls get_attribute_int32
get_var_attr_int64 calls get_attribute_int64
get_var_attr_real32 calls get_attribute_real32
get_var_attr_real64 calls get_attribute_real64
mapl_locstreamcreatefromfile calls mapl_readtilingnc4
write calls put_attributes, write_const_variables, def_variables
main calls write_data
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
add_variable calls def_variables
get_file_times calls get_var_attr_int32
getlevs calls get_var_attr_real32
var_get_missing_value calls get_var_attr_real32