get_item_index – MAPL
get_item_index Function
36 statements
Source File
private function get_item_index(this, base_name, current_time, rc) result(item_index)
Type Bound
PrimaryExports
Arguments
Type Intent Optional Attributes Name
class(PrimaryExports), intent(in) :: this
character(len=*), intent(in) :: base_name
type(ESMF_Time) :: current_time
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
  function get_item_index(this,base_name,current_time,rc) result(item_index)
     integer :: item_index
     class(primaryExports), intent(in) :: this
     type(ESMF_Time) :: current_time
     character(len=*),intent(in) :: base_name
     integer, optional, intent(out) :: rc
     character(len=:), pointer :: cname
     integer :: i
     integer, pointer :: num_rules,i_start
     logical :: found
     found = .false.
     do i=1,this%import_names%size()
        cname => this%import_names%at(i)
        if (cname == base_name) then
           found = .true.
           i_start => this%export_id_start%at(i)
           num_rules => this%number_of_rules%at(i)
           exit
        end if
     enddo
     _ASSERT(found,"ExtData no item with basename '"//TRIM(base_name)//"' found")
     item_index = -1
     if (num_rules == 1) then
        item_index = i_start
     else if (num_rules > 1) then
        do i=1,num_rules
           if (current_time >= this%item(i_start+i-1)%start_end_time(1) .and. &
               current_time <  this%item(i_start+i-1)%start_end_time(2)) then
              item_index = i_start + i -1
              exit
           endif
        enddo
     end if
     _ASSERT(item_index/=-1,"ExtData did not find item index for basename "//TRIM(base_name))
     _RETURN(_SUCCESS)
  end function get_item_index
Call graph
get_item_index calls at, mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_ calls get_item_index
mapl_extdataverticalinterpolate calls get_item_index
run_ calls get_item_index, mapl_extdataverticalinterpolate