get_connection – MAPL
get_connection Function
9 statements
Source File
private function get_connection(this, rc) result(connection)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value class(AbstractSocket), pointer
Calls
Called by
pFIO_BaseServerMod::BaseServer%get_dmessage w pFIO_BaseThreadMod::BaseThread%get_connection
w
pFIO_ClientThreadMod::ClientThread%add_ext_collection w
w
pFIO_ClientThreadMod::ClientThread%add_hist_collection w
w
pFIO_ClientThreadMod::ClientThread%collective_prefetch_data w
w
pFIO_ClientThreadMod::ClientThread%collective_stage_data w
w
pFIO_ClientThreadMod::ClientThread%done w
w
pFIO_ClientThreadMod::ClientThread%done_collective_prefetch w
w
pFIO_ClientThreadMod::ClientThread%done_collective_stage w
w
pFIO_ClientThreadMod::ClientThread%done_prefetch w
w
pFIO_ClientThreadMod::ClientThread%done_stage w
w
pFIO_ClientThreadMod::ClientThread%modify_metadata w
w
pFIO_ClientThreadMod::ClientThread%prefetch_data w
w
pFIO_ClientThreadMod::ClientThread%replace_metadata w
w
pFIO_ClientThreadMod::ClientThread%shake_hand w
w
pFIO_ClientThreadMod::ClientThread%stage_data w
w
pFIO_ClientThreadMod::ClientThread%stage_nondistributed_data w
w
pFIO_ClientThreadMod::ClientThread%terminate w
w
pFIO_FastClientThreadMod::FastClientThread%collective_stage_data w
w
pFIO_FastClientThreadMod::FastClientThread%stage_data w
w
pFIO_FastClientThreadMod::FastClientThread%stage_nondistributed_data w
w
pFIO_ServerThreadMod::run_done w
w
pFIO_ServerThreadMod::ServerThread%get_DataFromMem w
w
pFIO_ServerThreadMod::ServerThread%handle_AddExtCollection w
w
pFIO_ServerThreadMod::ServerThread%handle_AddHistCollection w
w
pFIO_ServerThreadMod::ServerThread%handle_CollectivePrefetchData w
w
pFIO_ServerThreadMod::ServerThread%handle_CollectiveStageData w
w
pFIO_ServerThreadMod::ServerThread%handle_Done_prefetch w
w
pFIO_ServerThreadMod::ServerThread%handle_HandShake w
w
pFIO_ServerThreadMod::ServerThread%handle_ModifyMetadata w
w
pFIO_ServerThreadMod::ServerThread%handle_PrefetchData w
w
pFIO_ServerThreadMod::ServerThread%handle_ReplaceMetadata w
w
pFIO_ServerThreadMod::ServerThread%handle_StageData w
w
pFIO_ServerThreadMod::ServerThread%run w
w
pFIO_SimpleSocketMod::SimpleSocket%send w
w
test_Client::test_addExtCollection_send_message w
w
test_Client::test_addExtCollection_unique_handle w
w
test_Client::test_prefetch_data w
w
test_Client::test_wait w
w
test_SimpleSocket::test_send_done w
w
test_SimpleSocket::test_send_terminate w
w
Source Code
   function get_connection(this, rc) result(connection)
      class (BaseThread), target, intent(in) :: this
      class (AbstractSocket), pointer :: connection
      integer, optional, intent(out) :: rc
      _ASSERT(allocated(this%connection), "no connection")
      connection => this%connection
      _RETURN(_SUCCESS)
   end function get_connection
Call graph
get_connection calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize