get_child_import_state – MAPL
get_child_import_state Function
8 statements
Source File
private function get_child_import_state(this, i) result(state)
Type Bound
MAPL_MetaComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_MetaComp), intent(in), target :: this
integer, intent(in) :: i
Return Value type(ESMF_State), pointer
Calls
Called by
Source Code
   function get_child_import_state(this, i) result(state)
      type(ESMF_State), pointer :: state
      class(MAPL_MetaComp), target, intent(in) :: this
      integer, intent(in) :: i
      class(MaplGenericComponent), pointer :: child
      child => this%get_ith_child(i)
      state => child%get_import_state()
   end function get_child_import_state
Call graph
get_child_import_state calls get_import_state, get_ith_child
get_import_state calls get_current_thread, is_threading_active
get_ith_child calls get_child
get_child_by_index calls get_component, get_child
get_child_by_name calls get_component, get_child
addchild_preamble calls get_child_import_state
mapl_genericfinalize calls get_child_import_state
mapl_genericinitialize calls get_child_import_state
mapl_genericrecord calls get_child_import_state
mapl_genericrefresh calls get_child_import_state, mapl_genericrefresh
mapl_genericrunchildren calls get_child_import_state
mapl_genericruncouplers calls get_child_import_state
mapl_genericstateget calls get_child_import_state
mapl_genericstaterestore calls get_child_import_state, mapl_genericstaterestore
mapl_genericstatesave calls get_child_import_state, mapl_genericstatesave
mapl_importstateget calls get_child_import_state, mapl_importstateget
run_component_driver calls get_child_import_state
mapl_get calls mapl_genericstateget
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
get_field_from_import calls mapl_importstateget
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
main calls run_component_driver
mapl_readforcingx calls mapl_genericstateget
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore