get_offset – MAPL
get_offset Function
5 statements
Source File
private function get_offset(this) result(offset)
Type Bound
ExtDataPointerUpdate
Arguments
Type Intent Optional Attributes Name
class(ExtDataPointerUpdate), intent(in) :: this
Return Value type(ESMF_TimeInterval)
Called by
Source Code
   function get_offset(this) result(offset)
      type(ESMF_TimeInterval) :: offset
      class(ExtDataPointerUpdate), intent(in) :: this
      offset = this%offset
   end function get_offset
Call graph
test_compare_negative_string_to_negative_heartbeat calls get_offset
test_compare_positive_string_to_positive_heartbeat calls get_offset
test_create_from_parameters_heartbeat_negative calls get_offset
test_create_from_parameters_heartbeat_positive calls get_offset
test_create_from_parameters_heartbeat_positive_explicit calls get_offset
test_create_from_parameters_string_negative calls get_offset
test_create_from_parameters_string_positive calls get_offset