get_obs_time – MAPL
get_obs_time Subroutine
57 statements
Source File
private subroutine get_obs_time(this, grid, obs_time, rc)
Uses
MAPL_BaseMod
Type Bound
SwathGridFactory
Arguments
Type Intent Optional Attributes Name
class(SwathGridFactory), intent(inout) :: this
type(ESMF_Grid), intent(in) :: grid
real(kind=ESMF_KIND_R4), intent(out) :: obs_time(:,:)
integer, intent(out), optional :: rc
Calls
Source Code
    subroutine get_obs_time(this, grid, obs_time,  rc)
      use MAPL_BaseMod, only: MAPL_grid_interior
      class(SwathGridFactory), intent(inout) :: this
      type (ESMF_Grid), intent(in) :: grid
      real(ESMF_KIND_R4), intent(out) :: obs_time(:,:)
      integer, optional, intent(out) :: rc
      integer :: status
      real(kind=ESMF_KIND_R8), pointer :: fptr(:,:)
      real(kind=ESMF_KIND_R8), pointer :: centers(:,:)
      real(kind=ESMF_KIND_R8), allocatable :: lon_true(:,:)
      real(kind=ESMF_KIND_R8), allocatable :: lat_true(:,:)
      real(kind=ESMF_KIND_R8), allocatable :: time_true(:,:)
      real(kind=ESMF_KIND_R8), pointer :: arr_time(:,:)
      integer :: i, j, k
      integer :: Xdim, Ydim, count
      integer :: nx, ny
      integer :: i_1, i_n, j_1, j_n ! regional array bounds
      ! debug
      type(ESMF_VM) :: vm
      integer :: mypet, petcount
      integer :: mpic
      call ESMF_VMGetCurrent(vm,_RC)
      call ESMF_VMGet(vm, mpiCommunicator=mpic, localPet=mypet, petCount=petCount, _RC)
      Xdim=this%im_world
      Ydim=this%jm_world
      count=Xdim*Ydim
      call MAPL_grid_interior(grid, i_1, i_n, j_1, j_n)
      call MAPL_AllocateShared(arr_time,[Xdim,Ydim],transroot=.true.,_RC)
      call MAPL_SyncSharedMemory(_RC)
      if (mapl_am_i_root()) then
         allocate( lon_true(0,0), lat_true(0,0), time_true(0,0) )
         call read_M_files_4_swath (this%filenames(1:this%M_file), nx, ny, &
              this%index_name_lon, this%index_name_lat, &
              var_name_lon=this%var_name_lon, &
              var_name_lat=this%var_name_lat, &
              var_name_time=this%var_name_time, &
              lon=lon_true, lat=lat_true, time=time_true, &
              Tfilter=.true., _RC)
         k=0
         do j=this%epoch_index(3), this%epoch_index(4)
            k=k+1
            arr_time(1:Xdim, k) = time_true(1:Xdim, j)
         enddo
         deallocate( lon_true, lat_true, time_true )
!         write(6,*) 'in root, time'
!         write(6,'(11x,100E12.5)')  arr_time(::5,189)
      end if
      call MAPL_SyncSharedMemory(_RC)
      call MAPL_BcastShared (VM, data=arr_time, N=count, Root=MAPL_ROOT, RootOnly=.false., _RC)
!      write(6,'(2x,a,2x,i5,4x,100E12.5)')  'PET, time', mypet, arr_time(::5,189)
!      call MPI_Barrier(mpic, status)
      !(Xdim, Ydim)
      obs_time = arr_time(i_1:i_n,j_1:j_n)
      if(MAPL_ShmInitialized) then
         call MAPL_DeAllocNodeArray(arr_time,_RC)
      else
         deallocate(arr_time)
      end if
      _RETURN(_SUCCESS)
    end subroutine get_obs_time
Call graph
get_obs_time calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_allocateshared, mapl_am_i_root, mapl_bcastshared, mapl_deallocnodearray, mapl_grid_interior, mapl_syncsharedmemory, mapl_return, mapl_verify, read_m_files_4_swath