get_rows – MAPL
get_rows Subroutine
61 statements
Source File
private subroutine get_rows(this, node, rows)
Uses
MAPL_AbstractMeterNode
Type Bound
MemoryTextColumn
Arguments
Type Intent Optional Attributes Name
class(MemoryTextColumn), intent(in) :: this
class(AbstractMeterNode), intent(in), target :: node
character(len=:), intent(out), allocatable :: rows(:)
Calls
Source Code
   subroutine get_rows(this, node, rows)
      use MAPL_AbstractMeterNode
      class (MemoryTextColumn), intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      character(:), allocatable, intent(out) :: rows(:)
      integer :: n, i
      character(2) :: suffix
      real(kind=REAL64) :: x
      type (UnlimitedVector) :: values
      n = this%get_width()
      values = this%data_column%get_rows(node)
      allocate(character(n) :: rows(values%size()))
      do i = 1, values%size()
         select type (v => values%at(i))
         type is (integer)
            x = real(v, kind=REAL64)
            suffix = get_suffix(x)
            write(rows(i),this%format) convert(x), suffix
         type is (real(kind=REAL64))
            suffix = get_suffix(v)
            write(rows(i),this%format) convert(v), suffix
         end select
      end do
   contains
      function get_suffix(x) result(suffix)
         character(2) :: suffix
         real(kind=REAL64), intent(in) :: x
         integer(kind=INT64) :: ix
         integer(kind=INT64) :: KB = 1024
         ix = ceiling(abs(x))
         if (ix < KB) then
            suffix = ' B'
         elseif (ix < KB**2) then
            suffix = 'KB'
         elseif (ix < KB**3) then
            suffix = 'MB'
         elseif (ix < KB**4) then
            suffix = 'GB'
         else
            suffix = 'TB'
         end if
      end function get_suffix
      function convert(x) result(ix)
         integer(kind=INT64) :: ix
         real(kind=REAL64), intent(in) :: x
         integer(kind=INT64) :: KB = 1024
         ix = ceiling(abs(x))
         if (ix < KB) then
            ix = ix
         elseif (ix < KB**2) then
            ix = ix / KB
         elseif (ix < KB**3) then
            ix = ix / KB**2
         elseif (ix < KB**4) then
            ix = ix / KB**3
         else
            ix = ix / KB**4
         end if
         ix = sign(1.d0, x) * ix
      end function convert
   end subroutine get_rows
Call graph
get_rows calls at, get_rows, get_width