get_factory – MAPL
get_factory Function
19 statements
Source File
private function get_factory(this, grid, unusable, rc) result(factory)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(in), target :: this
type(ESMF_Grid), intent(in) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(AbstractGridFactory), pointer
Calls
Called by
Source Code
   function get_factory(this, grid, unusable, rc) result(factory)
      class (AbstractGridFactory), pointer :: factory
      class (GridManager), target, intent(in) :: this
      type (ESMF_Grid), intent(in) :: grid
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer (kind=ESMF_KIND_I8) :: id
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'get_factory'
      _UNUSED_DUMMY(unusable)
      call ESMF_AttributeGet(grid, factory_id_attribute, id, rc=status)
      _VERIFY(status)
      factory => this%factories%at(id)
      _RETURN(_SUCCESS)
   end function get_factory
Call graph
get_factory calls ESMF_AttributeGet, m_at, mapl_return, mapl_verify, get_factory
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
addgrid calls get_factory
regrid_vector_2d_real32 calls get_factory
regrid_vector_2d_real64 calls get_factory
regrid_vector_3d_real32 calls get_factory
regrid_vector_3d_real64 calls get_factory
transpose_regrid_vector_2d_real32 calls get_factory
transpose_regrid_vector_3d_real32 calls get_factory
createfilemetadata calls get_factory, createvariable
createvariable calls get_factory
esmfl_halo_r4_2d calls get_factory
find_tile_file calls get_factory
get_latlon_from_factory calls get_factory
initialize calls addgrid, createfilemetadata
mapl_create_bundle_from_metdata_id calls get_factory
mapl_esmfstatereadfromfile calls get_factory
request_data_from_file calls get_factory
stage2dlatlon calls get_factory
stagedata calls get_factory
esmfl_halo calls esmfl_halo_r4_2d
bundlepost calls stage2dlatlon, stagedata
create_from_bundle calls createfilemetadata
initialize_subclass calls find_tile_file
mapl_cfiocreatefrombundle calls get_latlon_from_factory
mapl_extdataprefetch calls request_data_from_file
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_read_bundle calls mapl_create_bundle_from_metdata_id, request_data_from_file
mapl_staterefresh calls mapl_esmfstatereadfromfile