get_num_rows_header – MAPL
get_num_rows_header Function
4 statements
Source File
private function get_num_rows_header(this) result(num_rows)
Type Bound
NameColumn
Arguments
Type Intent Optional Attributes Name
class(NameColumn), intent(in) :: this
Return Value integer
Calls
Called by
Source Code
   integer function get_num_rows_header(this) result(num_rows)
      class(NameColumn), intent(in) :: this
      num_rows = 1 + this%get_num_rows_separator()
   end function get_num_rows_header
Call graph
get_num_rows_header calls get_num_rows_separator
get_header calls get_num_rows_header
test_one_timer calls get_header