get_x_subset – MAPL
get_x_subset Module Procedure
31 statements
Source File
module procedure get_x_subset module subroutine get_x_subset(this, interval, x_subset, rc) Interface →
I choose UB = N+1 not N, because my sub. bisect find n: Y(n)<x<=Y(n+1) write(6,’(2x,a,2x,2i10)’) ‘mod vers. get_x_subset, LB,UB=’, x_subset(1:2)
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
type(ESMF_Time), intent(in) :: interval(2)
integer, intent(out) :: x_subset(2)
integer, intent(out), optional :: rc
Calls
Call graph
get_x_subset calls bisect, mapl_return, mapl_verify, time_esmf_2_nc_int
bisect calls bisect_find_lb_r8_i8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
time_esmf_2_nc_int calls mapl_return, mapl_verify, ESMF_TimeIntervalGet, parse_timeunit
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
bisect_find_lb_r8_i8 calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_timeunit_i4 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
parse_timeunit_i8 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert