get_total – MAPL
get_total Function
5 statements
Source File
private function get_total(this) result(val)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(in) :: this
Return Value real(kind=REAL64)
Called by
Source Code
   function get_total(this) result(val)
      real(kind=REAL64) :: val
      class(AdvancedMeter), intent(in) :: this
      val = this%total
   end function get_total
Call graph
get_overhead calls get_total
reduce_mpi calls get_total
start_back calls get_total
test_accumulate calls get_total
test_add_cycle calls get_total
test_reset calls get_total
start calls start_back
reduce_global calls reduce
test_get_max calls reduce
test_get_min calls reduce
test_get_num_cycles calls reduce
test_get_total calls reduce
test_trivial calls reduce