get_internal_state – MAPL
get_internal_state Function
11 statements
Source File
private function get_internal_state(this) result(internal_state)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(in), target :: this
Return Value type(ESMF_State), pointer
Calls
Called by
Source Code
   function get_internal_state(this) result(internal_state)
      class(MaplGenericComponent), target, intent(in) :: this
      type(ESMF_State), pointer :: internal_state
      integer :: thread
      if (.NOT. this%is_threading_active()) then
        internal_state => this%internal_state
     else
        thread = get_current_thread()
        internal_state => this%subcomponents(thread+1)%internal_state
     end if
   end function get_internal_state
Call graph
get_internal_state calls get_current_thread, is_threading_active
capture calls get_internal_state
get_child_internal_state calls get_internal_state
mapl_friendlyget calls get_internal_state
mapl_genericfinalize calls get_internal_state, mapl_genericstatedestroy
mapl_genericinitialize calls get_internal_state
mapl_genericstatedestroy calls get_internal_state
mapl_genericstateget calls get_internal_state
mapl_genericstaterestore calls get_internal_state, mapl_genericstaterestore
mapl_genericstatesave calls get_internal_state, mapl_genericstatesave
mapl_gridcompgetfriendlies0 calls get_internal_state
mapl_staterecord calls get_internal_state
mapl_staterefresh calls get_internal_state
mapl_get calls mapl_genericstateget
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0
mapl_readforcingx calls mapl_genericstateget
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore