get_unit – MAPL
get_unit Subroutine
20 statements
Source File
private subroutine get_unit(iunit)
Arguments
Type Intent Optional Attributes Name
integer :: iunit
Called by
Source Code
subroutine get_unit (iunit)
  implicit none
!
  integer i
  integer ios
  integer iunit
  logical lopen
  iunit = 0
  do i = 1, 99
    if ( i /= 5 .and. i /= 6 ) then
      inquire ( unit = i, opened = lopen, iostat = ios )
      if ( ios == 0 ) then
        if ( .not. lopen ) then
          iunit = i
          return
        end if
      end if
    end if
  end do
  return
end subroutine get_unit
Call graph
mapl_memcommited calls get_unit
mapl_memused calls get_unit
mapl_memutilsfree calls get_unit
mem_dump calls get_unit
mapl_memreport calls mapl_memcommited, mapl_memused
mapl_memutilswritecomm calls mem_dump
run_one_step calls mapl_memcommited
step calls mapl_memcommited, mapl_memused
mapl_memutilswrite calls mapl_memutilswritecomm, mapl_memutilswritevm
mapl_memutilswritevm calls mapl_memutilswritecomm
run_mapl_gridcomp calls step, mapl_memutilswrite
run_multipletimes calls run_one_step
step_model calls step
mapl_genericinitialize calls mapl_memutilswrite
model_advance calls step_model
run_gc calls run_mapl_gridcomp, run_multipletimes
test_main calls mapl_memutilswrite