get_mask_variables – MAPL
get_mask_variables Function
24 statements
Source File
private function get_mask_variables(this, rc) result(variables_in_mask)
Type Bound
ExtDataMask
Arguments
Type Intent Optional Attributes Name
class(ExtDataMask), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Called by
Call graph
get_mask_variables calls mapl_return, parser_variables_in_expression, push_back
mapl_return calls get_error_message, mapl_throw_exception
parser_variables_in_expression calls mapl_return, push_back, mapl_assert, checkundef, getvariables, mathfunctionindex, parseerrmsg, realnum, removespaces, replace
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
checkundef calls lowcase
get_error_message calls at, insert
mapl_throw_exception calls initialize
mathfunctionindex calls lowcase
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_variables_in_expression calls get_mask_variables
get_extra_derived_items calls get_variables_in_expression
initialize_ calls get_extra_derived_items