get_fname_by_face – MAPL
get_fname_by_face Function
17 statements
Source File
public function get_fname_by_face(fname, face) result(name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
integer, intent(in) :: face
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_fname_by_face(fname, face) result(name)
     character(len=:), allocatable :: name
     character(len=*), intent(in) :: fname
     integer, intent(in) :: face
     integer :: i
     i= index(fname,'_checkpoint')
     if (i /= 0) then
        name = fname(1:i-1)//'_face_'//i_to_string(face)//trim(fname(i:))
        return
     end if
     i= index(fname,'_rst')
     if (i /= 0) then
        name = fname(1:i-1)//'_face_'//i_to_string(face)//trim(fname(i:))
        return
     endif
     name = trim(fname)//'_face_'//i_to_string(face)
   end function get_fname_by_face
Call graph
get_fname_by_face calls i_to_string
i_to_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_bundlereadncpar calls get_fname_by_face
mapl_bundlewritencpar calls get_fname_by_face
mapl_esmfstatereadfromfile calls get_fname_by_face, mapl_varreadncpar
mapl_statevarreadncpar calls get_fname_by_face, mapl_varreadncpar
mapl_varreadncpar calls mapl_bundlereadncpar, mapl_statevarreadncpar, mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarwritencpar calls mapl_bundlewritencpar
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
refresh_state calls mapl_genericstaterestore
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile