get_unique_collective_request_id – MAPL
get_unique_collective_request_id Function
7 statements
Source File
private function get_unique_collective_request_id(this) result(request_id)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
Return Value integer
Called by
Source Code
   integer function get_unique_collective_request_id(this) result(request_id)
      class (ClientThread), intent(inout) :: this
      associate (n => this%collective_counter)
        n = COLLECTIVE_MIN_ID + mod(n +1 - COLLECTIVE_MIN_ID, (COLLECTIVE_MAX_ID-COLLECTIVE_MIN_ID+1))
      end associate
      request_id = this%collective_counter
   end function get_unique_collective_request_id
Call graph
collective_prefetch_data calls get_unique_collective_request_id, collective_prefetch_data
collective_stage_data calls get_unique_collective_request_id, collective_stage_data
stage_nondistributed_data calls get_unique_collective_request_id, collective_stage_data
run calls collective_prefetch_data, collective_stage_data, stage_nondistributed_data
bundlepost calls stage_nondistributed_data
mapl_fieldwritencpar calls collective_stage_data
mapl_varwritencpar_r4_2d calls collective_stage_data
mapl_varwritencpar_r4_3d calls collective_stage_data
mapl_varwritencpar_r4_4d calls collective_stage_data
mapl_varwritencpar_r8_2d calls collective_stage_data
mapl_varwritencpar_r8_3d calls collective_stage_data
mapl_varwritencpar_r8_4d calls collective_stage_data
regrid_append_file calls collective_stage_data
request_data_from_file calls collective_prefetch_data
run_model calls collective_stage_data
stage2dlatlon calls collective_stage_data
stagedata calls collective_stage_data
main calls run