get_fraction – MAPL
get_fraction Function
19 statements
Source File
private function get_fraction(t1)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t1
Return Value real(kind=dp)
Called by
Source Code
REAL(dp) FUNCTION get_fraction(t1)
       IMPLICIT NONE
       REAL(dp), INTENT(IN) :: t1
       REAL(dp) :: fraction2day, temp3, temp4
       if (t1.EQ.0.0) then
           fraction2day = 0.0
       else if (t1.lt.1.0 .AND. t1.gt.0) then
           fraction2day = t1
       else
           temp3 = floor(t1)
           temp4 = t1
           if (temp3 == temp4) then
             fraction2day = temp3 ! either is ok
           else
             fraction2day = MOD(temp4,temp3)
           end if
       end if
       get_fraction = fraction2day
END FUNCTION get_fraction
Call graph
get_latlon calls get_fraction
find_delta_t calls get_latlon
find_waypointslat calls get_latlon
redifine_timeint calls get_latlon
orbits_track calls find_waypointslat
domasking_ calls orbits_track
domasking_cs calls orbits_track
orbits_swath calls orbits_track