get_file_basename – MAPL
get_file_basename Function
11 statements
Source File
public pure function get_file_basename(filename) result(basename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   pure function get_file_basename(filename) result(basename)
      ! Function that returns the basename of a string filename
      ! where filename is "basename.extension"
      character(len=*), intent(in) :: filename
      character(len=:), allocatable :: basename
      integer :: dot_index
      dot_index = find_extension_index(trim(filename))
      ! If the filename has no extension, return the filename
      if (dot_index > 0) then
         basename = trim(filename(1:dot_index-1))
      else
         basename = trim(filename)
      end if
   end function get_file_basename
Call graph
get_file_basename calls find_extension_index
adjust_dso_name calls get_file_basename
test_get_file_basename calls get_file_basename
addchildfromdsometa calls adjust_dso_name
mapl_addchild calls addchildfromdsometa, addchildfromdso
addchildfromdso calls addchildfromdsometa
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild