get_day – MAPL
get_day Function
4 statements
Source File
public function get_day(self)
Type Bound
ISO8601Date
Arguments
Type Intent Optional Attributes Name
class(ISO8601Date), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_day(self)
      class(ISO8601Date), intent(in) :: self
      get_day = self%day_
   end function get_day
Call graph
convert_iso8601_to_integer_date calls get_day
get_day_datetime calls get_day
test_construct_iso8601date calls get_day
test_iso8601date_getters calls get_day
convert_iso8601_to_esmf_time calls get_day_datetime
test_construct_iso8601datetime calls get_day_datetime
test_convert_iso8601_to_integer_date calls convert_iso8601_to_integer_date
test_iso8601datetime_getters calls get_day_datetime