get_mean_cycle – MAPL
get_mean_cycle Function
11 statements
Source File
private function get_mean_cycle(this) result(mean_cycle)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(in) :: this
Return Value real(kind=REAL64)
Calls
Called by
Source Code
   function get_mean_cycle(this) result(mean_cycle)
      real(kind=REAL64) :: mean_cycle
      class(AdvancedMeter), intent(in) :: this
      integer :: n
      n = this%get_num_cycles()
      if (n > 0) then
         mean_cycle = this%total / n
      else
         mean_cycle = 0  ! undefined actually
      end if
   end function get_mean_cycle
Call graph
get_mean_cycle calls get_num_cycles
add_cycle calls get_mean_cycle
get_relative_deviation calls get_mean_cycle
test_get_mean_cycle calls get_mean_cycle, add_cycle
stop calls add_cycle
test_accumulate calls add_cycle
test_add_cycle calls add_cycle
test_get_max calls add_cycle
test_get_max_cycle calls add_cycle
test_get_min calls add_cycle
test_get_min_cycle calls add_cycle
test_get_num_cycles calls add_cycle
test_get_standard_deviation calls add_cycle
test_get_total calls add_cycle
test_reset calls add_cycle
test_trivial calls add_cycle