Get_Tdim – MAPL
Get_Tdim Subroutine
47 statements
Source File
private subroutine Get_Tdim(list, clock, tdim)
Uses
MAPL_CommsMod
ESMF
Arguments
Type Intent Optional Attributes Name
type(HistoryCollection), intent(in) :: list
type(ESMF_Clock), intent(in) :: clock
integer, intent(out) :: tdim
Calls
Called by
Contents
Source Code
Get_Tdim
Source Code
  subroutine Get_Tdim (list, clock, tdim)
! !IROUTINE: Get_Tdim -- Returns Time Dimension (Number of Records) in a HISTORY.rc collection file
! !USES:
    use ESMF
    use MAPL_CommsMod, only: MAPL_AM_I_ROOT
    implicit none
! !ARGUMENTS:
    type (HistoryCollection),  intent(IN ) :: list
    type (ESMF_Clock),    intent(IN ) :: clock
    integer,              intent(OUT) :: tdim
! ESMF stuff
!-----------
    type (ESMF_Time)            :: currTime
    type (ESMF_Time)            :: stopTime
    type (ESMF_TimeInterval)    :: tint
! Misc locals
!------------
    real                         :: rfreq
    real                         :: rdelt
    real                         :: rfrac
    integer                      :: nfreq
    integer                      :: ndelt
    integer                      :: STATUS
!  Initialize TDIM=-1 (UNLIMITED)
!--------------------------------
    tdim = -1
    if( list%tm == 0) then  ! Dynamic calculation of time dimension
       if( list%duration == 0 ) then
          ! compute duration from the ESMF clock
          call ESMF_ClockGet(clock, currTime=currTime, stopTime=stopTime, &
               RC=status)
          if (status /= ESMF_SUCCESS) goto 200
          tint = stopTime - currTime
          call ESMF_TimeIntervalGet(tint, s=ndelt, RC=status)
          if (status /= ESMF_SUCCESS) goto 200
          nfreq = MAPL_nsecf( list%frequency )
          rfreq = real(nfreq)
          rdelt = real(ndelt)
          rfrac = rdelt/rfreq - ndelt/nfreq
          if( rfrac.ne.0 ) rfrac = 1.0 - rfrac
          ndelt = ndelt  + rfrac*nfreq
       else
          ndelt = MAPL_nsecf( list%duration )
       endif
       nfreq = MAPL_nsecf( list%frequency )
       if (nfreq /=0) then
          tdim  = ndelt/nfreq
       end if
    else
       tdim = list%tm
    endif  ! End TM=0 Test
! Debug Prints
! ------------
200 continue
    if( MAPL_AM_I_ROOT() ) then
       write(6,100) list%frequency, list%duration, tdim, trim(list%collection)
100    format(1x,'Freq: ',i8.8,'  Dur: ',i8.8,'  TM: ',i4,'  Collection: ',a)
    endif
    return
  end subroutine Get_Tdim
Call graph
get_tdim calls esmf_clockget, esmf_timeintervalget, mapl_am_i_root, mapl_nsecf
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_nsecf calls mapl_nsecf
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout
initialize calls get_tdim