get_shared_communicator – MAPL
get_shared_communicator Function
4 statements
Source File
private function get_shared_communicator(this) result(shared_communicator)
Type Bound
AbstractCommSplitter
Arguments
Type Intent Optional Attributes Name
class(AbstractCommSplitter), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_shared_communicator(this) result(shared_communicator)
      class (AbstractCommSplitter), intent(in) :: this
      shared_communicator = this%shared_communicator
   end function get_shared_communicator
Call graph
assign calls get_shared_communicator
compute_color calls get_shared_communicator, get_node_id, get_node_sizes
get_node_id calls get_shared_communicator
get_node_sizes calls get_shared_communicator
split calls get_shared_communicator, compute_color
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls get_node_sizes, split
new_multigroupserver calls get_node_sizes, split
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator, initialize_io_clients_servers
main calls initialize, create_member_subcommunicator, initialize_ioserver
run_ensemble calls create_member_subcommunicator, initialize_io_clients_servers
time_ave calls initialize
ut_regridding calls initialize
run calls initialize_io_clients_servers, run_ensemble
regrid_util calls main