get_file_times – MAPL
get_file_times Subroutine
35 statements
Source File
subroutine get_file_times(file_metadata, num_times, time_series, time_interval, yymmdd, hhmmss, rc)
Arguments
Type Intent Optional Attributes Name
type(FileMetadataUtils), intent(inout) :: file_metadata
integer, intent(out) :: num_times
type(ESMF_Time), intent(inout), allocatable :: time_series(:)
integer, intent(out) :: time_interval
integer, intent(inout), allocatable :: yymmdd(:)
integer, intent(inout), allocatable :: hhmmss(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
get_file_times
Source Code
   subroutine get_file_times(file_metadata,num_times,time_series,time_interval,yymmdd,hhmmss,rc)
      type(FileMetadataUtils), intent(inout) :: file_metadata
      integer, intent(out) :: num_times
      type(ESMF_Time), allocatable, intent(inout) :: time_series(:)
      integer, intent(inout), allocatable :: yymmdd(:)
      integer, intent(inout), allocatable :: hhmmss(:)
      integer, intent(out) :: time_interval
      integer, intent(out), optional :: rc
      integer :: status
      type(ESMF_TimeInterval) :: esmf_time_interval
      integer :: hour, minute, second, year, month, day, i
      num_times = file_metadata%get_dimension('time',_RC)
      call file_metadata%get_time_info(timeVector=time_series,_RC)
      if (num_times == 1) then
         time_interval = file_metadata%get_var_attr_int32('time','time_increment',_RC)
      else if (num_times > 1) then
         esmf_time_interval = time_series(2)-time_series(1)
         call ESMF_TimeIntervalGet(esmf_time_interval,h=hour,m=minute,s=second,_RC)
         time_interval = hour*10000+minute*100+second
      end if
      allocate(yymmdd(num_times),hhmmss(num_times))
      do i = 1,num_times
         call ESMF_TimeGet(time_series(i),yy=year,mm=month,dd=day,h=hour,m=minute,s=second,_RC)
         yymmdd(i)=year*10000+month*100+day
         hhmmss(i)=hour*10000+minute*100+second
      enddo
      if (present(rc)) then
         rc=_SUCCESS
      end if
   end subroutine get_file_times
Call graph
get_file_times calls ESMF_TimeGet, ESMF_TimeIntervalGet, get_dimension, get_time_info, get_var_attr_int32, mapl_abort, mapl_verify
get_time_info calls ESMF_TimeGet, mapl_verify, ESMF_TimeIntervalSet, ESMF_TimeSet, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, mapl_assert, get_coordinate_info, get_file_name, mapl_return
get_var_attr_int32 calls mapl_verify, get_attribute, get_values, get_variable, mapl_assert, get_file_name, mapl_return
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_coordinate_info calls get_dimension, mapl_verify, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, mapl_assert, get_file_name, mapl_return, get_ith_dimension, var_has_attr
get_file_name calls mapl_return
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
var_has_attr calls mapl_verify, get_variable, mapl_assert, get_file_name, mapl_return, is_attribute_present
time_ave calls get_file_times