get_att_char_netcdf – MAPL
get_att_char_netcdf Subroutine
29 statements
Source File
public subroutine get_att_char_netcdf(filename, varname, att_name, att_value, group_name, rc)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: varname
character(len=*), intent(in) :: att_name
character(len=*), intent(out) :: att_value
character(len=*), intent(out), optional :: group_name
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine get_att_char_netcdf(filename, varname, att_name, att_value, group_name, rc)
    use netcdf
    implicit none
    character(len=*), intent(in) :: filename
    character(len=*), intent(in) :: varname
    character(len=*), intent(in) :: att_name
    character(len=*), intent(out) :: att_value
    character(len=*), optional, intent(out) :: group_name
    integer, optional, intent(out) :: rc
    integer :: status
    integer :: ncid, ncid_grp, ncid_sv
    integer :: varid
    call check_nc_status(nf90_open(trim(fileName), NF90_NOWRITE, ncid), _RC)
    ncid_sv = ncid
    if(present(group_name)) then
       call check_nc_status(nf90_inq_ncid(ncid, group_name, ncid_grp), _RC)
       ! overwrite
       ncid = ncid_grp
    end if
    call check_nc_status(nf90_inq_varid(ncid, varname, varid), _RC)
    call check_nc_status(nf90_get_att(ncid, varid, att_name, att_value), _RC)
    call check_nc_status(nf90_close(ncid_sv), _RC)
    _RETURN(_SUCCESS)
  end subroutine get_att_char_netcdf
Call graph
get_att_char_netcdf calls nf90_close, nf90_get_att, nf90_inq_ncid, nf90_inq_varid, nf90_open, check_nc_status, mapl_return, mapl_verify
check_nc_status calls mapl_return, mapl_assert, nf90_strerror
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception