get_depth – MAPL
get_depth Function
5 statements
Source File
private function get_depth(this) result(depth)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(in) :: this
Return Value integer
Called by
Source Code
   function get_depth(this) result(depth)
      integer :: depth
      class (MeterNode), intent(in) :: this
      depth = this%depth
   end function get_depth
Call graph
add_child calls get_depth
accumulate calls add_child
test_count_nodes_depth_1 calls add_child
test_depth_2 calls add_child
test_get_exclusive calls add_child
test_get_inclusive calls add_child
test_get_num_nodes calls add_child
test_get_num_nodes_2 calls add_child
test_next_one_child calls add_child
test_node_reset calls add_child
test_percent_inclusive calls add_child
test_simple calls add_child