get_factory – MAPL
get_factory Function
13 statements
Source File
public function get_factory(grid, unusable, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid) :: grid
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(AbstractGridFactory), pointer
Calls
Called by
Contents
Source Code
get_factory
Source Code
   function get_factory(this, grid, unusable, rc) result(factory)
      class (AbstractGridFactory), pointer :: factory
      class (GridManager), intent(in) :: this
      type (ESMF_Grid), intent(in) :: grid
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer (kind=ESMF_KIND_I8) :: id
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'get_factory'
      _UNUSED_DUMMY(unusable)
      call ESMF_AttributeGet(grid, factory_id_attribute, id, rc=status)
      _VERIFY(status)
      factory => this%factories%at(id)
      _RETURN(_SUCCESS)
   end function get_factory
Call graph
get_factory calls mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
esmfl_halo_r4_2d calls get_factory
createfilemetadata calls get_factory
mapl_esmfstatereadfromfile calls get_factory
createvariable calls get_factory
mapl_create_bundle_from_metdata_id calls get_factory
request_data_from_file calls get_factory
stage2dlatlon calls get_factory
stagedata calls get_factory
get_latlon_from_factory calls get_factory
find_tile_file calls get_factory
esmfl_halo calls esmfl_halo_r4_2d
mapl_cfiocreatefrombundle calls get_latlon_from_factory
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_locstreamtransformg2t calls esmfl_halo
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
refresh_state calls mapl_genericstaterestore
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t
test_main calls esmf_iocreate
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_locstreamtransform calls mapl_locstreamtransformg2t
mapl_simplebundlewrite2 calls mapl_cfiocreate
regrid_util calls main