get_DataFromMem – MAPL
get_DataFromMem Subroutine
15 statements
Source File
private subroutine get_DataFromMem(this, multi, rc)
Type Bound
BaseServer
Arguments
Type Intent Optional Attributes Name
class(BaseServer), intent(inout), target :: this
logical, intent(in) :: multi
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine get_DataFromMem(this, multi, rc)
     class (BaseServer),target, intent(inout) :: this
     logical, intent(in) :: multi
     integer, optional, intent(out) :: rc
     integer :: i, client_num, status
     class (ServerThread),pointer :: threadPtr
     client_num = this%threads%size()
     do i = 1, client_num
         threadPtr=>this%threads%at(i)
         ! get data from Shmem_reference and send it back to app
         call threadPtr%get_DataFromMem(multi, rc=status)
         _VERIFY(status)
     enddo
     _RETURN(_SUCCESS)
   end subroutine get_DataFromMem
Call graph
get_datafrommem calls at, get_datafrommem, mapl_return, mapl_verify, mapl_assert, erase, distribute_task, fetch_data, get_connection, get_datareference, i_to_string, insert_requesthandle, v_begin, v_iter_get, put
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fetch_data calls mapl_return, mapl_assert
get_connection calls mapl_return, mapl_assert
get_datareference calls at
get_error_message calls at, insert
i_to_string calls mapl_return, mapl_assert
insert_requesthandle calls mapl_return, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_erase_one calls erase