get_exclusive – MAPL
get_exclusive Function
15 statements
Source File
private function get_exclusive(this) result(exclusive)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(in) :: this
Return Value real(kind=REAL64)
Calls
Contents
Source Code
get_exclusive
Source Code
   function get_exclusive(this) result(exclusive)
      real(kind=REAL64) :: exclusive
      class (MeterNode), intent(in) :: this
      type (MeterNodevectorIterator) :: iter
      class (AbstractMeterNode), pointer :: child
      real(kind=REAL64) :: tmp
      ! Subtract time of submeters from time of node meter.
      ! Previously, this used 128-bit precision to avoid negative
      ! exclusive times due to roundoff. But the GNU on M1 and NVHPC do
      ! not allow REAL128. So tmp is now 64-bit and we use a max(tmp,0)
      ! below to try and cap negatives
      tmp = this%get_inclusive()
      iter = this%children%begin()
      do while (iter /= this%children%end())
         child => iter%get()
         tmp = tmp - child%get_inclusive()
         call iter%next()
      end do
      exclusive = max(tmp, 0.0_REAL64)
   end function get_exclusive
Call graph
get_exclusive calls get_inclusive, get, next
next calls begin
begin calls meternodeiterator
meternodeiterator calls new_meternodeiterator