get_gc_id – MAPL
get_gc_id Function
4 statements
Source File
private function get_gc_id(this) result(gc_id)
Type Bound
VarConnPoint
Arguments
Type Intent Optional Attributes Name
class(VarConnPoint), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_gc_id(this) result(gc_id)
      class(VarConnPoint), intent(in) :: this
      gc_id = this%gc_id
   end function get_gc_id
Call graph
checkreq calls get_gc_id
varisconnected_ie calls get_gc_id
varisconnected_name calls get_gc_id
varislisted calls get_gc_id
mapl_genericsetservices calls checkreq, mapl_wirecomponent
mapl_wirecomponent calls varislisted, varisconnected
mapl_terminateimportallbut calls varisconnected
setservices calls mapl_genericsetservices
mapl_terminateimport calls mapl_terminateimportallbut