get_xy_subset – MAPL
get_xy_subset Subroutine
47 statements
Source File
private subroutine get_xy_subset(this, interval, xy_subset, rc)
Uses
mpi
complex version ! (x1, x2] design in bisect if (index1==jlo-1) then je = index1 + 1 else je = index1 end if xy_subset(1, 2) = je if (index2==jlo-1) then je = index2 + 1 else je = index2 end if xy_subset(2, 2) = je
Type Bound
SwathGridFactory
Arguments
Type Intent Optional Attributes Name
class(SwathGridFactory), intent(in) :: this
type(ESMF_Time), intent(in) :: interval(2)
integer, intent(out) :: xy_subset(2,2)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine get_xy_subset(this, interval, xy_subset, rc)
      use MPI
      class(SwathGridFactory), intent(in) :: this
      type(ESMF_Time), intent(in) :: interval(2)
      integer, intent(out) :: xy_subset(2,2)
      integer, optional, intent(out) :: rc
      type(ESMF_VM) :: VM
      integer:: mpic
      integer:: irank, ierror
      integer :: status
      type(ESMF_Time) :: T1, T2
      integer(ESMF_KIND_I8) :: i1, i2
      real(ESMF_KIND_R8) :: iT1, iT2
      integer(ESMF_KIND_I8) :: index1, index2
      integer :: jlo, jhi, je
      call ESMF_VmGetCurrent(VM, _RC)
      call ESMF_VMGet(vm, mpiCommunicator=mpic, _RC)
      call MPI_COMM_RANK(mpic, irank, ierror)
      if (irank==0) then
         ! xtrack
         xy_subset(1:2,1)=this%epoch_index(1:2)
         ! atrack
         T1= interval(1)
         T2= interval(2)
         ! this%t_alongtrack
         !
         call time_esmf_2_nc_int (T1, this%tunit, i1, _RC)
         call time_esmf_2_nc_int (T2, this%tunit, i2, _RC)
         iT1 = i1   ! int to real*8
         iT2 = i2
         if (this%epoch_index(3) > 2) then
            jlo = this%epoch_index(3) - 2
         else
            jlo = this%epoch_index(3)
         end if
         jhi = this%epoch_index(4) + 1
         !
         ! -- it is possible some obs files are missing
         !
         call bisect( this%t_alongtrack, iT1, index1, n_LB=int(jlo, ESMF_KIND_I8), n_UB=int(jhi, ESMF_KIND_I8), rc=rc)
         call bisect( this%t_alongtrack, iT2, index2, n_LB=int(jlo, ESMF_KIND_I8), n_UB=int(jhi, ESMF_KIND_I8), rc=rc)
         !! complex version
         !!      ! (x1, x2]  design in bisect
         !!      if (index1==jlo-1) then
         !!         je = index1 + 1
         !!      else
         !!         je = index1
         !!      end if
         !!      xy_subset(1, 2) = je
         !!      if (index2==jlo-1) then
         !!         je = index2 + 1
         !!      else
         !!         je = index2
         !!      end if
         !!      xy_subset(2, 2) = je
         ! simple version
         xy_subset(1,  2)=index1+1                 ! atrack
         xy_subset(2,  2)=index2
         !
         !- relative
         !
         xy_subset(1,2)= xy_subset(1,2) - this%epoch_index(3) + 1
         xy_subset(2,2)= xy_subset(2,2) - this%epoch_index(3) + 1
      end if
      call MPI_bcast(xy_subset, 4, MPI_INTEGER, 0, mpic, ierror)
      _RETURN(_SUCCESS)
    end subroutine get_xy_subset
Call graph
get_xy_subset calls ESMF_VMGet, ESMF_VMGetCurrent, bisect, mpi_bcast, mpi_comm_rank, mapl_return, mapl_verify, time_esmf_2_nc_int
bisect calls bisect_find_lb_r8_i8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
time_esmf_2_nc_int calls mapl_return, mapl_verify, ESMF_TimeIntervalGet, parse_timeunit
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
bisect_find_lb_r8_i8 calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_timeunit_i4 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
parse_timeunit_i8 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert