get_converter_function – MAPL
get_converter_function Function
17 statements
Source File
private function get_converter_function(from, to) result(conv)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: from
character(len=*), intent(in) :: to
Return Value type(Converter)
Calls
Called by
Source Code
   function get_converter_function(from, to) result(conv)
      type(Converter) :: conv
      character(len=*), intent(in) :: from, to
      type(UDUnit) :: from_unit
      type(UDUnit) :: to_unit
      ! Unit system must be initialized (instantiated).
      if(instance_is_uninitialized()) return
      ! Get units based on strings. Free memory on fail.
      from_unit = UDUnit(from)
      if(from_unit%is_free()) return
      to_unit = UDUnit(to)
      if(to_unit%is_free()) then
         call from_unit%free()
         return
      end if
      conv = Converter(from_unit, to_unit)
      ! Units are no longer needed
      call from_unit%free()
      call to_unit%free()
   end function get_converter_function
Call graph
get_converter_function calls instance_is_uninitialized, is_free
instance_is_uninitialized calls is_free
get_converter calls get_converter_function
test_convert_double calls get_converter
test_convert_doubles calls get_converter
test_convert_float calls get_converter
test_convert_floats calls get_converter
test_get_converter calls get_converter