get_attribute – MAPL
get_attribute Function
10 statements
Source File
private function get_attribute(this, attr_name, rc) result(attr)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value type(Attribute), pointer
Calls
Called by
Source Code
   function get_attribute(this, attr_name, rc) result(attr)
      type (Attribute), pointer :: attr
      class (Variable), target, intent(in) :: this
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      attr => this%attributes%at(attr_name)
      _ASSERT(associated(attr), "no such attribute : " // trim(attr_name))
      _RETURN(_SUCCESS)
   end function get_attribute
Call graph
get_attribute calls mapl_assert, m_at, mapl_return, get_attribute
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
check_flip calls get_attribute
compute_time_for_current calls get_attribute
get_attribute_int32 calls get_attribute
get_attribute_int64 calls get_attribute
get_attribute_real32 calls get_attribute
get_attribute_real64 calls get_attribute
get_attribute_string calls get_attribute
get_coordinate_bounds calls get_attribute
get_coordinate_bounds_name calls get_attribute
get_coordinate_info calls get_attribute
get_file_start_time calls get_attribute
get_start_time calls get_attribute
get_time_info calls get_attribute
get_variable_attribute calls get_attribute
mapl_iogettime calls get_attribute
test_get_attribute_real_double calls get_attribute
test_get_attribute_scalar_int calls get_attribute
test_get_attribute_string calls get_attribute
write_data calls get_attribute