get_variables_in_expression – MAPL
get_variables_in_expression Function
18 statements
Source File
private function get_variables_in_expression(this, rc) result(variables_in_expression)
Type Bound
ExtDataDerived
Arguments
Type Intent Optional Attributes Name
class(ExtDataDerived), intent(inout), target :: this
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Called by
Call graph
get_variables_in_expression calls get_mask_variables, mapl_return, mapl_verify, parser_variables_in_expression
get_mask_variables calls mapl_return, parser_variables_in_expression, push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parser_variables_in_expression calls mapl_return, mapl_assert, checkundef, getvariables, mathfunctionindex, parseerrmsg, realnum, removespaces, replace, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
checkundef calls lowcase
get_error_message calls at, insert
mapl_throw_exception calls initialize
mathfunctionindex calls lowcase
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_extra_derived_items calls get_variables_in_expression
initialize_ calls get_extra_derived_items