get_type – MAPL
get_type Function
4 statements
Source File
private function get_type(this) result(type)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_type(this) result(type)
      class (Variable), intent(in) :: this
      type = this%type
   end function get_type
Call graph
def_variables calls get_type
test_get_type calls get_type
transfer_metadata calls get_type
write_variables calls get_type
add_variable calls def_variables
write calls def_variables
write_formatted calls write_variables
main calls transfer_metadata