get_id – MAPL
get_id Function
6 statements
Source File
private function get_id(this, factory) result(id)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
class(AbstractGridFactory), intent(in) :: factory
Return Value integer(kind=INT64)
Calls
Source Code
   function get_id(this, factory) result(id)
      integer(kind=INT64) :: id
      class (GridManager), intent(inout) :: this
      class (AbstractGridFactory), intent(in) :: factory
      call this%add_factory(factory, id)
   end function get_id
Call graph
get_id calls add_factory
add_factory calls insert, m_begin, m_key, m_next
m_begin calls s_begin
m_next calls s_next
m_insert_pair calls s_insert
s_begin calls s_next
s_next calls advpos