get_source_file – MAPL
get_source_file Function
11 statements
Source File
private function get_source_file(this, rc) result(source_file)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in) :: this
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Call graph
get_source_file calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_from_file_metadata calls get_source_file