get_length – MAPL
get_length Function
6 statements
Source File
private function get_length(this) result(length)
Type Bound
AddHistCollectionMessage
Arguments
Type Intent Optional Attributes Name
class(AddHistCollectionMessage), intent(in) :: this
Return Value integer
Calls
Source Code
   integer function get_length(this) result(length)
      class (AddHistCollectionMessage), intent(in) :: this
      integer,allocatable :: buffer(:) ! no-op
      call this%fmd%serialize(buffer)
      length = size(buffer) + 1 ! 1 is the create_mode
   end function get_length
Call graph
get_length calls serialize
serialize calls serialize_buffer_length, serialize_intrinsic, mapl_return, serialize, stringintegermap_serialize, stringvariablemap_serialize, stringvector_serialize