get_coordinate_data – MAPL
get_coordinate_data Function
8 statements
Source File
private function get_coordinate_data(this, rc) result(coordinate_data)
Type Bound
CoordinateVariable
Arguments
Type Intent Optional Attributes Name
class(CoordinateVariable), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value class(*), pointer, (:)
Calls
Called by
Source Code
   function get_coordinate_data(this, rc) result(coordinate_data)
      class (*), pointer :: coordinate_data(:)
      class (CoordinateVariable), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      coordinate_data => this%coordinate_data
      _RETURN(_SUCCESS)
   end function get_coordinate_data
Call graph
get_coordinate_data calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_coordinate_info calls get_coordinate_data
get_coords calls get_coordinate_data
get_time_info calls get_coordinate_data, get_coordinate_info
initialize_from_file_metadata calls get_coordinate_data
mapl_iochangeres calls get_coordinate_data
test_get_coordinate_data calls get_coordinate_data
test_replace_coordinate_data calls get_coordinate_data
write_coordinate_variables calls get_coordinate_data
detect_metadata calls get_time_info
get_file_levels calls get_coordinate_info
get_file_times calls get_time_info
get_time_on_file calls get_time_info
getclimyear calls get_time_info
getlevs calls get_coordinate_info
initialize_ calls get_coordinate_info
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info
new_verticalcoordinate calls get_coords
run_component_driver calls get_time_info
updatebrackettime calls get_time_info
write calls write_coordinate_variables
time_ave calls get_coordinate_info