get_name – MAPL
get_name Function
5 statements
Source File
private function get_name(this) result(name)
Type Bound
SplitCommunicator
Arguments
Type Intent Optional Attributes Name
class(SplitCommunicator), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_name(this) result(name)
      character(:), allocatable :: name
      class (SplitCommunicator), intent(in) :: this
      name = this%name
   end function get_name
Call graph
create_member_subcommunicator calls get_name
finalize_io_clients_servers calls get_name
initialize calls get_name
new_multicommserver calls get_name
new_multigroupserver calls get_name
run_member calls get_name
run calls get_name, finalize_io_clients_servers, initialize_io_clients_servers, run_ensemble
main calls get_name, initialize_ioserver, initialize
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator, initialize_io_clients_servers
model_finalize calls finalize_io_clients_servers
run_ensemble calls create_member_subcommunicator, finalize_io_clients_servers, run_member, initialize_io_clients_servers
extdata_driver calls run
time_ave calls initialize
ut_regridding calls initialize
regrid_util calls main
capdriver_main calls run
driver_gethorzijindex calls run