get_estimateECI – MAPL
get_estimateECI Subroutine
19 statements
Source File
private subroutine get_estimateECI(iSat, ntime_day, ECI_est)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
real(kind=dp), intent(in) :: ntime_day
real(kind=dp), intent(out), DIMENSION(:,:) :: ECI_est
Calls
Called by
Contents
Source Code
get_estimateECI
Source Code
SUBROUTINE get_estimateECI(iSat, ntime_day, ECI_est)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: iSat
        REAL(dp), INTENT(IN)    :: ntime_day
        REAL(dp), DIMENSION(:,:), INTENT(OUT) :: ECI_est
        REAL(dp), DIMENSION(Num_coef) :: myvec
        REAL(dp), DIMENSION(Num_normcoef) :: normvec
        REAL(dp)                      :: xdata_est, ydata_est, zdata_est
       CALL Orbits_Track0(iSat, myvec, normvec) ! myvec has 9 sat coef
                                                ! normvec has normalization coef
!       % _________________________Estimates_________________________
        xdata_est = sin(myvec(1) * ntime_day + myvec(2)) + myvec(3);
        ydata_est = sin(myvec(4) * ntime_day + myvec(5)) + myvec(6);
        zdata_est = sin(myvec(7) * ntime_day + myvec(8)) + myvec(9);
!       % ________________Mult by Norm fator_________________________
        xdata_est = xdata_est * normvec(1)   ! max(xECI);
        ydata_est = ydata_est * normvec(2) ! max(yECI);
        zdata_est = zdata_est * normvec(3) ! max(zECI);
        ECI_est(1,1) = xdata_est
        ECI_est(2,1) = ydata_est
        ECI_est(3,1) = zdata_est
END SUBROUTINE get_estimateECI
Call graph
get_estimateeci calls orbits_track0
orbits_track0 calls orbits_track1, orbits_track2
orbits_track1 calls satname2int
get_latlon calls get_estimateeci
orbits calls get_estimateeci
find_delta_t calls get_latlon
find_waypointslat calls get_latlon
redifine_timeint calls get_latlon
orbits_track calls find_waypointslat
domasking_ calls orbits_track
domasking_cs calls orbits_track
orbits_swath calls orbits_track