get_quantize_algorithm – MAPL
get_quantize_algorithm Function
5 statements
Source File
private function get_quantize_algorithm(this) result(quantizeAlgorithm)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
Return Value integer
Called by
Source Code
   function get_quantize_algorithm(this) result(quantizeAlgorithm)
      class (Variable), target, intent(In) :: this
      integer :: quantizeAlgorithm
      quantizeAlgorithm=this%quantize_algorithm
   end function get_quantize_algorithm
Call graph
def_variables calls get_quantize_algorithm
add_variable calls def_variables
write calls def_variables