get_esmf_grid_layout – MAPL
get_esmf_grid_layout Subroutine
33 statements
Source File
subroutine get_esmf_grid_layout(grid, nx, ny, ims_out, jms_out, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out) :: nx
integer, intent(out) :: ny
integer, intent(inout), allocatable :: ims_out(:)
integer, intent(inout), allocatable :: jms_out(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
get_esmf_grid_layout
Source Code
   subroutine get_esmf_grid_layout(grid,nx,ny,ims_out,jms_out,rc)
      type(ESMF_Grid), intent(inout) :: grid
      integer, intent(out) :: nx
      integer, intent(out) :: ny
      integer, intent(inout), allocatable :: ims_out(:)
      integer, intent(inout), allocatable :: jms_out(:)
      integer, optional, intent(out) :: rc
      type(ESMF_VM) :: vm
      integer :: status
      type(ESMF_DistGrid) :: dist_grid
      integer, allocatable :: minindex(:,:),maxindex(:,:)
      integer :: dim_count, ndes
      integer, pointer :: ims(:),jms(:)
      call ESMF_VMGetCurrent(vm,_RC)
      call ESMF_VMGet(vm,petCount=ndes,_RC)
      call ESMF_GridGet(grid,distgrid=dist_grid,dimCOunt=dim_count,_RC)
      allocate(minindex(dim_count,ndes),maxindex(dim_count,ndes))
      call MAPL_DistGridGet(dist_grid,minIndex=minindex,maxIndex=maxindex,_RC)
      call MAPL_GetImsJms(minindex(1,:),maxindex(1,:),minindex(2,:),maxindex(2,:),ims,jms,_RC)
      nx = size(ims)
      ny = size(jms)
      allocate(ims_out(nx),jms_out(ny))
      ims_out = ims
      jms_out = jms
      if (present(rc)) then
         rc=_SUCCESS
      endif
   end subroutine get_esmf_grid_layout
Call graph
get_esmf_grid_layout calls esmf_vmgetcurrent, mapl_verify, mapl_abort, esmf_vmget, esmf_gridget, mapl_distgridget, mapl_getimsjms
mapl_verify calls mapl_throw_exception
mapl_abort calls mpi_abort
mapl_distgridget calls mapl_verify, esmf_distgridget
mapl_getimsjms calls mapl_verify, mapl_assert, mapl_return, mapl_sort
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_return calls mapl_throw_exception, get_error_message
mapl_sort calls sort1ls, sort2ss, sort2ld, sort2lr, sort2ls, sort1sr, sort2sr, sort2al, sort2as, sort2sd, sort1ss, sort1lr, sort1ld, sort1sd
latlon_zmean calls get_esmf_grid_layout
latlon_zstar calls latlon_zmean
time_ave calls latlon_zstar