get_cap_parameters_from_gc – MAPL
get_cap_parameters_from_gc Function
11 statements
Source File
public function get_cap_parameters_from_gc(gc, rc) result(cap_params)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
integer, intent(out) :: rc
Return Value type(cap_parameters)
Calls
Called by
Contents
Source Code
get_cap_parameters_from_gc
Source Code
    function get_cap_parameters_from_gc(gc, rc) result(cap_params)
        type(cap_parameters)               :: cap_params
        type(ESMF_GridComp), intent(inout) :: gc
        integer,             intent(  out) :: rc
        type(cap_parameters_wrapper) :: parameters_wrapper
        call ESMF_UserCompGetInternalState(gc, internal_parameters_name, parameters_wrapper, rc)
        VERIFY_NUOPC_(rc)
        cap_params = parameters_wrapper%ptr
        _RETURN(_SUCCESS)
    end function get_cap_parameters_from_gc
Call graph
get_cap_parameters_from_gc calls ESMF_LogFoundError, ESMF_UserCompGetInternalState, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
initialize_p0 calls get_cap_parameters_from_gc