get_length – MAPL
get_length Function
7 statements
Source File
private function get_length(this) result(length)
Type Bound
ReplaceMetadataMessage
Arguments
Type Intent Optional Attributes Name
class(ReplaceMetadataMessage), intent(in) :: this
Return Value integer
Calls
Source Code
   integer function get_length(this) result(length)
      class (ReplaceMetadataMessage), intent(in) :: this
      integer, allocatable :: buffer(:)
      allocate(buffer(0))
      call this%fmd%serialize(buffer)
      length = &
           & serialize_buffer_length(this%collection_id) + &
           & size(buffer)
   end function get_length
Call graph
get_length calls serialize_buffer_length, serialize
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
serialize calls serialize_buffer_length, serialize_intrinsic, mapl_return, serialize, stringintegermap_serialize, stringvariablemap_serialize, stringvector_serialize