get_short_name – MAPL
get_short_name Function
5 statements
Source File
private function get_short_name(this) result(short_name)
Type Bound
VarConnPoint
Arguments
Type Intent Optional Attributes Name
class(VarConnPoint), intent(in) :: this
Return Value character(len=:), allocatable
Called by
Source Code
   function get_short_name(this) result(short_name)
      class(VarConnPoint), intent(in) :: this
      character(:), allocatable :: short_name
      short_name = this%new_connection_point%state_item
   end function get_short_name
Call graph
checkreq calls get_short_name
checkunused calls get_short_name
varisconnected_ie calls get_short_name
varisconnected_name calls get_short_name
varislisted calls get_short_name
mapl_genericconncheck calls checkunused, mapl_genericconncheck
mapl_genericsetservices calls checkreq, mapl_genericconncheck, mapl_wirecomponent
mapl_wirecomponent calls varislisted, varisconnected
mapl_terminateimportallbut calls varisconnected
setservices calls mapl_genericsetservices
mapl_terminateimport calls mapl_terminateimportallbut