get_rows_range – MAPL
get_rows_range Subroutine
26 statements
Source File
private subroutine get_rows_range(this, begin, end, rows)
Type Bound
SimpleTextColumn
Arguments
Type Intent Optional Attributes Name
class(SimpleTextColumn), intent(in), target :: this
class(AbstractMeterNodeIterator), intent(in) :: begin
class(AbstractMeterNodeIterator), intent(in) :: end
character(len=:), intent(inout), allocatable :: rows(:)
Calls
Called by
Contents
Source Code
get_rows_range
Source Code
   subroutine get_rows_range(this, begin, end, rows)
      class (SimpleTextColumn), target, intent(in) :: this
      class (AbstractMeterNodeIterator), intent(in) :: begin
      class (AbstractMeterNodeIterator), intent(in) :: end
      character(:), allocatable, intent(inout) :: rows(:)
      class (AbstractMeterNodeIterator), allocatable :: iter
      integer :: i
      integer :: width
      class (AbstractMeterNode), pointer :: subnode
      ! count_nodes
      iter = begin
      i = 0
      do while (iter /= end)
         i = i + 1
         call iter%next()
      end do
      width = this%get_width()
      allocate(character(width) :: rows(i))
      ! Fill rows
      iter = begin
      i = 0
      do while (iter /= end)
         i = i + 1
         subnode => iter%get()
         rows(i) = this%get_row(subnode)
         call iter%next()
      end do
   end subroutine get_rows_range
Call graph
get_rows_range calls get, get_row, get_width, next
get_rows calls get_rows_range