get_coords – MAPL
get_coords Function
22 statements
Source File
private function get_coords(coord_var, rc) result(coords)
Arguments
Type Intent Optional Attributes Name
class(CoordinateVariable), intent(in) :: coord_var
integer, intent(out), optional :: rc
Return Value real, allocatable, (:)
Calls
Called by
Source Code
    function get_coords(coord_var, rc) result(coords)
       real, allocatable :: coords(:)
       class(CoordinateVariable), intent(in) :: coord_var
       integer, intent(out), optional :: rc
       class(*), pointer :: ptr(:)
       ptr => coord_var%get_coordinate_data()
       _ASSERT(associated(ptr),"coord variable coordinate data not found")
       select type (ptr)
       type is (real(kind=REAL64))
          coords=ptr
       type is (real(kind=REAL32))
          coords=ptr
       type is (integer(kind=INT64))
          coords=ptr
       type is (integer(kind=INT32))
          coords=ptr
       class default
          _FAIL("unsupported coordinate variable type in ")
       end select
       _RETURN(_SUCCESS)
    end function get_coords
Call graph
get_coords calls mapl_assert, get_coordinate_data, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_coordinate_data calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_verticalcoordinate calls get_coords
verticalcoordinate calls new_verticalcoordinate