get_child_idx – MAPL
get_child_idx Function
12 statements
Source File
private function get_child_idx(this, child_name) result(idx)
Type Bound
MAPL_MetaComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_MetaComp), intent(in), target :: this
character(len=*), intent(in) :: child_name
Return Value integer
Calls
Called by
Contents
Source Code
get_child_idx
Source Code
   integer function get_child_idx(this, child_name) result(idx)
      class(MAPL_MetaComp), target, intent(in) :: this
      character(*), intent(in) :: child_name
      integer :: i
      idx = -1
      do i = 1, this%get_num_children()
         if (this%gcnamelist(i) == trim(child_name)) then
            idx = i
            return
         end if
      end do
   end function get_child_idx
Call graph
get_child_idx calls gcnamelist, get_num_children
mapl_stateaddexportspecfrmchldname calls get_child_idx
mapl_stateaddexportspecfrmchld calls mapl_stateaddexportspecfrmchldname
mapl_addexportspec calls mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld
addnewspec calls mapl_addexportspec
setservices calls mapl_addexportspec