get_shape – MAPL
get_shape Function
12 statements
Source File
private function get_shape(this, rc) result(shp)
Simple accessor
Type Bound
UnlimitedEntity
Arguments
Type Intent Optional Attributes Name
class(UnlimitedEntity), intent(in) :: this
integer, intent(out), optional :: rc
Return Value integer, allocatable, (:)
Calls
Called by
Source Code
   function get_shape(this, rc) result(shp)
      class (UnlimitedEntity), intent(in) :: this
      integer, optional, intent(out) :: rc
      integer, allocatable :: shp(:)
      if (.not. allocated(this%shape)) then
         shp = EMPTY
      else
         shp = this%shape
      endif
      _RETURN(_SUCCESS)
   end function get_shape
Call graph
get_shape calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_variable calls get_shape
equal calls get_shape
get_rank calls get_shape
put_attributes calls get_shape
put_var_attributes calls get_shape
test_get_attribute_real_double calls get_shape
test_get_attribute_scalar calls get_shape
test_get_attribute_scalar_int calls get_shape
test_get_attribute_string calls get_shape
test_get_attribute_vector calls get_shape
write_const_variables calls get_shape