get_actual_label – MAPL
get_actual_label Subroutine
28 statements
Source File
private subroutine get_actual_label(config, label, label_is_present, actual_label, unusable, component_name, rc)
If possible, find label or label with prefix. Out: label found (logical) ! version of label found,
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: label
logical, intent(out) :: label_is_present
character(len=:), intent(out), allocatable :: actual_label
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: component_name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_actual_label(config, label, label_is_present, actual_label, unusable, component_name, rc)
      type(ESMF_Config), intent(inout) :: config
      character(len=*), intent(in) :: label
      logical, intent(out) :: label_is_present
      character(len=:), allocatable, intent(out) :: actual_label
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: component_name
      integer, optional, intent(out) :: rc
      character(len=ESMF_MAXSTR), allocatable :: labels_to_try(:)
      integer :: i
      integer :: status
      _UNUSED_DUMMY(unusable)
      label_is_present = .false.
      ! If component_name is present, find label in some form in config. Else search
      ! for exact label
      labels_to_try = get_labels_with_prefix(label, component_name)
      do i = 1, size(labels_to_try)
         actual_label = trim(labels_to_try(i))
         if (len_trim(actual_label) == 0 ) cycle
         call ESMF_ConfigFindLabel(config, label = actual_label, isPresent = label_is_present, _RC)
         if (label_is_present) exit
      end do
      if (.not. label_is_present) actual_label = trim(label)
      _RETURN(_SUCCESS)
   end subroutine get_actual_label
Call graph
get_actual_label calls ESMF_ConfigFindLabel, get_labels_with_prefix, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_getresource_config_array calls get_actual_label
mapl_getresource_config_scalar calls get_actual_label
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
test_mapl_getresource_scalar_character calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int8 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_logical calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real8 calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar