get_length_base – MAPL
get_length_base Function
10 statements
Source File
private function get_length_base(this) result(length)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_length_base(this) result(length)
      class (AbstractDataReference), intent(in) :: this
      integer :: n
      if( allocated(this%shape)) then
         n = size(this%shape)
      else
         n = 0
      endif
      length = size(transfer(this%base_address,[1])) +  &
               1 + 1 + & ! type_kind + rank
               n  ! shape
   end function get_length_base
Call graph
get_length calls get_length_base
serialize calls get_length_base, get_length