get_latitudes – MAPL
get_latitudes Function
11 statements
Source File
private function get_latitudes(this, unusable, rc) result(latitudes)
Uses
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Source Code
   function get_latitudes(this, unusable, rc) result(latitudes)
      use MAPL_BaseMod
      class (LatLonGridFactory), intent(in) :: this
      real(kind=REAL64), allocatable :: latitudes(:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      latitudes = this%lat_centers
      _RETURN(_SUCCESS)
   end function get_latitudes
Call graph
get_latitudes calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
test_cartesian_to_spherical_x calls get_latitudes
test_cartesian_to_spherical_y calls get_latitudes
test_cartesian_to_spherical_z calls get_latitudes
test_spherical_to_cartesian_north_wind calls get_latitudes