get_child – MAPL
get_child Function
12 statements
Source File
private function get_child(this, pos, dir) result(child)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in) :: this
integer(kind=SIZE_KIND), intent(in) :: pos
integer, intent(in) :: dir
Return Value integer(kind=SIZE_KIND)
Called by
Contents
Call graph
advpos calls get_child
rebalance calls get_child, rot
rot calls get_child
erase_nonleaf calls advpos, rebalance
s_erase_multi calls rebalance, erase_nonleaf
s_insert calls rebalance