get_latlon – MAPL
get_latlon Subroutine
14 statements
Source File
private subroutine get_latlon(iSat, t1, lat_estwayp, long_estwayp)
The subroutine get_latlon calls three important functions to calculate lat lon values of a satellite for a given time. Those functions are described in the following subsections.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
real(kind=dp), intent(in) :: t1
real(kind=dp), intent(inout) :: lat_estwayp
real(kind=dp), intent(inout) :: long_estwayp
Calls
Called by
Contents
Call graph
get_latlon calls ecef2lla, eci2ecef, get_estimateeci, get_fraction, rad2deg
get_estimateeci calls orbits_track0
orbits_track0 calls orbits_track1, orbits_track2
orbits_track1 calls satname2int
find_delta_t calls get_latlon
find_waypointslat calls get_latlon
redifine_timeint calls get_latlon
orbits_track calls find_waypointslat
domasking_ calls orbits_track, orbits_swath
domasking_cs calls orbits_track, orbits_swath
orbits_swath calls orbits_track
run_ calls domasking_, domasking_cs