get_pressures_r4_3d – MAPL
get_pressures_r4_3d Subroutine
27 statements
Source File
private subroutine get_pressures_r4_3d(this, pressures, surface_pressure, unusable, rc)
Type Bound
EtaHybridVerticalCoordinate
Arguments
Type Intent Optional Attributes Name
class(EtaHybridVerticalCoordinate), intent(in) :: this
real(kind=REAL32), intent(out) :: pressures(:,:,:)
real(kind=REAL32), intent(in), optional :: surface_pressure(:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine get_pressures_r4_3d(this, pressures, surface_pressure, unusable, rc)
      class(EtaHybridVerticalCoordinate), intent(in) :: this
      real(kind=REAL32), intent(out) :: pressures(:,:,:)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      real(kind=REAL32), optional, intent(in) :: surface_pressure(:,:)
      integer, optional, intent(out) :: rc
      integer :: i, j, k, isize, jsize, ksize
      real(kind=REAL32), allocatable :: levels(:)
      _UNUSED_DUMMY(unusable)
      isize = size(pressures,1)
      jsize = size(pressures,2)
      ksize = size(pressures,3)
      _ASSERT(this%num_levels == ksize, "pressure levels should match")
      allocate(levels(ksize))
      call this%get_pressure_levels(levels(:), reference_pressure = 0._REAL32)
      do k = 1, ksize
        do j = 1, jsize
          do i = 1, isize
             pressures(i,j,k) = surface_pressure(i,j) + levels(k)
          enddo
        enddo
      enddo
      deallocate(levels)
   end subroutine get_pressures_r4_3d
Call graph
get_pressures_r4_3d calls mapl_assert, get_pressure_levels
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_pressure_levels_r4 calls mapl_assert, get_pressure_levels
get_pressure_levels_r8 calls mapl_assert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize