get_row_dist – MAPL
get_row_dist Subroutine
15 statements
Source File
private subroutine get_row_dist(this, node, row)
Type Bound
ExclusiveColumn
Arguments
Type Intent Optional Attributes Name
class(ExclusiveColumn), intent(in), target :: this
class(AbstractMeterNode), intent(in), target :: node
class(*), intent(out), allocatable :: row
Calls
Called by
Contents
Source Code
get_row_dist
Source Code
   subroutine get_row_dist(this, node, row)
      class(*), allocatable, intent(out) :: row
      class (ExclusiveColumn), target, intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      class(AbstractMeter), pointer :: m
      type(DistributedStatistics) :: stats
      type(DistributedReal64) :: exclusive
      m => node%get_meter()
      select type (m)
      class is (DistributedMeter)
         stats = m%get_statistics()
         exclusive = stats%exclusive
         call this%fill_row(exclusive, this%option, row)
      end select
   end subroutine get_row_dist
Call graph
get_row_dist calls fill_row, get_meter, get_statistics
get_row calls get_row_dist