get_basis – MAPL
get_basis Function
64 statements
Source File
private function get_basis(this, basis, unusable, rc) result(basis_vectors)
Uses
MAPL_KeywordEnforcerMod
ESMF
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout), target :: this
character(len=*), intent(in) :: basis
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), pointer, (:,:,:,:)
Calls
Called by
Source Code
   function get_basis(this,basis,unusable,rc) result(basis_vectors)
      use esmf
      use MAPL_KeywordEnforcerMod
      real(REAL64), pointer :: basis_vectors(:,:,:,:)
      character(len=*), intent(in) :: basis
      class (AbstractGridFactory), target, intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam= MOD_NAME // 'get_basis'
      integer :: status
      real(REAL64), pointer :: temp_vect(:,:,:,:)
      real(REAL64), pointer :: Xcoord(:,:) => null()
      real(REAL64), pointer :: Ycoord(:,:) => null()
      _UNUSED_DUMMY(unusable)
      _ASSERT(allocated(this%grid), 'grid not allocated')
      select case (basis)
      case ('north-south')
         if (.not.allocated(this%NS_basis)) then
            call ESMF_GridGetCoord(this%grid,1, &
                 staggerLoc=ESMF_STAGGERLOC_CENTER, &
                 farrayPtr=Xcoord, rc=status)
            _VERIFY(status)
            call ESMF_GridGetCoord(this%grid,2, &
                 staggerLoc=ESMF_STAGGERLOC_CENTER, &
                 farrayPtr=Ycoord, rc=status)
            _VERIFY(status)
            allocate(this%NS_Basis(3,2,size(Xcoord,1),size(Xcoord,2)),stat=status)
            _VERIFY(status)
            basis_vectors => this%NS_Basis
            basis_vectors(1,1,:,:)= -sin(Xcoord)
            basis_vectors(2,1,:,:)=  cos(Xcoord)
            basis_vectors(3,1,:,:)=  0.0
            basis_vectors(1,2,:,:)= -sin(Ycoord)*cos(Xcoord)
            basis_vectors(2,2,:,:)= -sin(Ycoord)*sin(Xcoord)
            basis_vectors(3,2,:,:)=  cos(Ycoord)
         else
            basis_vectors => this%NS_basis
         end if
      case ('grid')
         if (.not.allocated(this%grid_basis)) then
            this%grid_basis = ComputeGridBasis(this%grid,rc=status)
            _VERIFY(status)
            basis_vectors => this%grid_Basis
         else
            basis_vectors => this%grid_basis
         end if
      case('xyz')
         if (.not.allocated(this%XYZ_basis)) then
            if (.not.allocated(this%grid_basis)) then
               this%grid_basis = ComputeGridBasis(this%grid,rc=status)
               _VERIFY(status)
               temp_vect => this%grid_basis
            else
               temp_vect => this%grid_basis
            end if
            this%XYZ_basis = ComputeXYZbasis(temp_vect,rc=status)
            _VERIFY(status)
            basis_vectors => this%XYZ_basis
         else
            basis_vectors => this%XYZ_basis
         end if
      end select
      _RETURN(_SUCCESS)
   end function get_basis
Call graph
get_basis calls ESMF_GridGetCoord, mapl_assert, computegridbasis, computexyzbasis, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
computegridbasis calls ESMF_GridGetCoord, mapl_return, mapl_verify, mapl_gridgetcorners, get_unit_vector, mapl_gridget, mid_pt_sphere
computexyzbasis calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_gridgetcorners calls mapl_gridgetcorners, ESMF_GridGetCoord, mapl_assert, mapl_return, mapl_verify, mapl_gridget, ESMF_AttributeGet, ESMF_GridGet, ESMF_AttributeSet, ESMF_FieldHalo, ESMF_FieldHaloRelease, ESMF_FieldHaloStore, esmf_fieldcreate, esmf_fielddestroy
get_error_message calls at, insert
get_unit_vector calls latlon2xyz
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_throw_exception calls initialize
mid_pt_sphere calls latlon2xyz, xyz2latlon
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_DELayoutGet, ESMF_DistGridGet
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis
regrid_vector_2d_real32 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_2d_real64 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_3d_real32 calls cartesian_to_spherical, spherical_to_cartesian
regrid_vector_3d_real64 calls cartesian_to_spherical, spherical_to_cartesian
test_cartesian_to_spherical_x calls cartesian_to_spherical
test_cartesian_to_spherical_y calls cartesian_to_spherical
test_cartesian_to_spherical_z calls cartesian_to_spherical
test_spherical_to_cartesian_east_wind calls spherical_to_cartesian
test_spherical_to_cartesian_north_wind calls spherical_to_cartesian
transpose_regrid_vector_2d_real32 calls cartesian_to_spherical, spherical_to_cartesian
transpose_regrid_vector_3d_real32 calls cartesian_to_spherical, spherical_to_cartesian