get_attribute_int64 – MAPL
get_attribute_int64 Function
23 statements
Source File
private function get_attribute_int64(this, attr_name, rc) result(attr_int64)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(inout) :: this
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value integer(kind=INT64)
Calls
Called by
Source Code
   function get_attribute_int64(this,attr_name,rc) result(attr_int64)
      integer(INT64) :: attr_int64
      class(Variable), intent(inout) :: this
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      integer(INT64) :: tmp(1)
      integer :: status
      type(Attribute), pointer :: attr
      class(*), pointer :: attr_val(:)
      attr => this%get_attribute(attr_name,_RC)
      _ASSERT(associated(attr),"no attribute named "//attr_name)
      attr_val => attr%get_values()
      select type(attr_val)
      type is(integer(kind=INT64))
         tmp = attr_val
         attr_int64 = tmp(1)
      class default
         _FAIL('unsupported subclass (not int64) for units of attribute named '//attr_name)
      end select
      _RETURN(_SUCCESS)
   end function get_attribute_int64
Call graph
get_attribute_int64 calls mapl_assert, get_attribute, get_values, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_values calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
get_var_attr_int64 calls get_attribute_int64