get_ncfile_dimension – MAPL
get_ncfile_dimension Subroutine
38 statements
Source File
public subroutine get_ncfile_dimension(filename, nlon, nlat, tdim, key_lon, key_lat, key_time, rc)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer, intent(out), optional :: nlon
integer, intent(out), optional :: nlat
integer, intent(out), optional :: tdim
character(len=*), intent(in), optional :: key_lon
character(len=*), intent(in), optional :: key_lat
character(len=*), intent(in), optional :: key_time
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine get_ncfile_dimension(filename, nlon, nlat, tdim, key_lon, key_lat, key_time, rc)
    use netcdf
    implicit none
    character(len=*), intent(in) :: filename
    integer, optional,intent(out) :: nlat, nlon, tdim
    character(len=*), optional, intent(in)  :: key_lon, key_lat, key_time
    integer, optional, intent(out) :: rc
    integer :: ncid , dimid
    integer :: status
    character(len=ESMF_MAXSTR) :: lon_name, lat_name, time_name
    call check_nc_status(nf90_open(trim(fileName), NF90_NOWRITE, ncid), _RC)
    if(present(key_lon)) then
       lon_name=trim(key_lon)
       call check_nc_status(nf90_inq_dimid(ncid, trim(lon_name), dimid), _RC)
       call check_nc_status(nf90_inquire_dimension(ncid, dimid, len=nlon), _RC)
    endif
    if(present(key_lat)) then
       lat_name=trim(key_lat)
       call check_nc_status(nf90_inq_dimid(ncid, trim(lat_name), dimid), _RC)
       call check_nc_status(nf90_inquire_dimension(ncid, dimid, len=nlat), _RC)
    endif
    if(present(key_time)) then
       time_name=trim(key_time)
       call check_nc_status(nf90_inq_dimid(ncid, trim(time_name), dimid), _RC)
       call check_nc_status(nf90_inquire_dimension(ncid, dimid, len=tdim), _RC)
    endif
    call check_nc_status(nf90_close(ncid), _RC)
    _RETURN(_SUCCESS)
  end subroutine get_ncfile_dimension
Call graph
get_ncfile_dimension calls nf90_close, nf90_inq_dimid, nf90_inquire_dimension, nf90_open, check_nc_status, mapl_return, mapl_verify
check_nc_status calls mapl_return, mapl_assert, nf90_strerror
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
create_geosat_grid_find_mask calls get_ncfile_dimension
create_grid calls get_ncfile_dimension
initialize_from_config_with_prefix calls get_ncfile_dimension, read_m_files_4_swath
read_m_files_4_swath calls get_ncfile_dimension
add_horz_coordinates_from_file calls read_m_files_4_swath
get_obs_time calls read_m_files_4_swath
make_new_grid calls add_horz_coordinates_from_file