get_integer_digit – MAPL
get_integer_digit Function
4 statements
Source File
public pure function get_integer_digit(c)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
Return Value integer
Called by
Contents
Source Code
get_integer_digit
Source Code
   pure integer function get_integer_digit(c)
      character, intent(in) :: c
      get_integer_digit = index(DIGIT_CHARACTERS, c) - 1
   end function get_integer_digit
Call graph
get_integer_digit_from_string calls get_integer_digit
test_get_integer_digit calls get_integer_digit
read_whole_number_indexed calls get_integer_digit_from_string
test_get_integer_digit_from_string calls get_integer_digit_from_string
construct_iso8601duration calls read_whole_number_indexed
read_whole_number calls read_whole_number_indexed
test_read_whole_number_indexed calls read_whole_number_indexed
iso8601duration calls construct_iso8601duration
parse_date calls read_whole_number
parse_time calls read_whole_number
parse_timezone_offset calls read_whole_number
test_read_whole_number calls read_whole_number