get_var_real32_3 – MAPL
get_var_real32_3 Subroutine
18 statements
Source File
private subroutine get_var_real32_3(this, var_name, values, unusable, start, count, rc)
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
real(kind=REAL32), intent(out) :: values(:,:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Contents
Call graph
get_var_real32_3 calls nf90_inq_varid, nf90_get_var, mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls get_error_message, mapl_throw_exception