get_latitudes_degrees – MAPL
get_latitudes_degrees Function
11 statements
Source File
private function get_latitudes_degrees(this, unusable, rc) result(latitudes)
Uses
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Source Code
   function get_latitudes_degrees(this, unusable, rc) result(latitudes)
      use MAPL_BaseMod
      class (LatLonGridFactory), intent(in) :: this
      real(kind=REAL64), allocatable :: latitudes(:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      latitudes = this%lat_centers_degrees
      _RETURN(_SUCCESS)
   end function get_latitudes_degrees
Call graph
get_latitudes_degrees calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
append_metadata calls get_latitudes_degrees