get_reckon – MAPL
get_reckon Subroutine
29 statements
Source File
private subroutine get_reckon(phi1, lambda1, az1, rng1, phi, lambda, wrapon)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: phi1
real(kind=dp), intent(in) :: lambda1
real(kind=dp), intent(in) :: az1
real(kind=dp), intent(in) :: rng1
real(kind=dp), intent(inout) :: phi
real(kind=dp), intent(inout) :: lambda
logical, intent(in) :: wrapon
Calls
Called by
Contents
Source Code
get_reckon
Source Code
SUBROUTINE get_reckon(phi1, lambda1, az1, rng1, phi, lambda, wrapon)
       ! phi0 - > lat, lambda0 -> lon
       ! calculates a position (LATOUT, LONOUT) at a given range RNG and azimuth
       ! AZ along a great circle from a starting point defined by LAT and LON.
       ! LAT and LON are in degrees.  The range is in degrees of arc length on a
       ! sphere.  The input azimuth is in degrees, measured clockwise from due
       ! north. Translated from MatLab
       IMPLICIT NONE
       REAL(dp), INTENT(IN) :: phi1, lambda1, az1, rng1
       REAL(dp), INTENT(INOUT) :: phi, lambda
       REAL(dp)                :: phi0, lambda0
       REAL(dp) :: epsilone, az, saz, rng
       LOGICAL, intent(in) :: wrapon       ! if true then wrap to -180 to 180
       epsilone = 10*1.74E-8
       phi0 = deg2rad(phi1)
       lambda0 = deg2rad(lambda1)
       az = deg2rad(az1)
       rng = deg2rad(rng1)
       associate(pi => MAPL_PI_R8)
          if (phi0 >= pi/2-epsilone) az = pi   ! starting at north pole
          if (phi0 <= epsilone-pi/2) az = 0    ! starting at south pole
          ! Calculate coordinates of great circle end point using spherical trig.
          phi = asin(sin(phi0)*cos(rng) + cos(phi0)*sin(rng)*cos(az))
          lambda = lambda0 + atan2( sin(rng)*sin(az),            &
                   cos(phi0)*cos(rng) - sin(phi0)*sin(rng)*cos(az) )
          if (wrapon) then
              if ( lambda>-epsilone .AND. lambda < epsilone) then
                  saz = 0
              else
                  saz = lambda/abs(lambda)
              end if
              lambda = pi*((abs(lambda)/pi) - 2*ceiling(((abs(lambda)/pi)-1)/2)) * saz
          end if
       end associate
       lambda = rad2deg(lambda)
       phi    = rad2deg(phi)
END SUBROUTINE get_reckon
Call graph
get_reckon calls deg2rad, rad2deg
find_sweeppoints calls get_reckon
orbits_swath calls find_sweeppoints
domasking_ calls orbits_swath
domasking_cs calls orbits_swath
run_ calls domasking_, domasking_cs