get_splitcomm – MAPL
get_splitcomm Subroutine
8 statements
Source File
private subroutine get_splitcomm(this, split_comm, rc)
Type Bound
ServerManager
Arguments
Type Intent Optional Attributes Name
class(ServerManager), intent(inout) :: this
type(SplitCommunicator), intent(out) :: split_comm
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_splitcomm(this, split_comm, rc)
      class (ServerManager), intent(inout) :: this
      type(SplitCommunicator), intent(out) :: split_comm
      integer, intent(out), optional :: rc
      split_comm=this%split_comm
      _RETURN(_SUCCESS)
   end subroutine get_splitcomm
Call graph
get_splitcomm calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
finalize_io_clients_servers calls get_splitcomm
run_member calls get_splitcomm
run calls get_splitcomm, finalize_io_clients_servers, run_ensemble
main calls get_splitcomm
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers, run_member
extdata_driver calls run
capdriver_main calls run
driver_gethorzijindex calls run