get_max_cycle – MAPL
get_max_cycle Function
5 statements
Source File
private function get_max_cycle(this) result(max_cycle)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(in) :: this
Return Value real(kind=REAL64)
Called by
Source Code
   function get_max_cycle(this) result(max_cycle)
      real(kind=REAL64) :: max_cycle
      class(AdvancedMeter), intent(in) :: this
      max_cycle = this%max_cycle
   end function get_max_cycle
Call graph
reduce_mpi calls get_max_cycle
test_get_max_cycle calls get_max_cycle
reduce_global calls reduce
test_get_max calls reduce
test_get_min calls reduce
test_get_num_cycles calls reduce
test_get_total calls reduce
test_trivial calls reduce