get_field_from_internal – MAPL
get_field_from_internal Subroutine
15 statements
Source File
private subroutine get_field_from_internal(this, field_name, state_name, field, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
character(len=*), intent(in) :: field_name
character(len=*), intent(in) :: state_name
type(ESMF_Field), intent(inout) :: field
integer, intent(out) :: rc
Calls
Source Code
  subroutine get_field_from_internal(this,field_name,state_name,field,rc)
    class(MAPL_CapGridComp), intent(inout) :: this
    character(len=*), intent(in) :: field_name
    character(len=*), intent(in) :: state_name
    type(ESMF_field), intent(inout) :: field
    integer, intent(out) :: rc
    integer :: status
    type(ESMF_State) :: state
    call MAPL_InternalESMFStateGet(this%gcs(this%root_id),state_name,state,rc=status)
    _VERIFY(status)
    call ESMF_StateGet(state,trim(field_name),field,rc=status)
    _VERIFY(status)
    _RETURN(_SUCCESS)
  end subroutine get_field_from_internal
Call graph
get_field_from_internal calls esmf_stateget, mapl_internalesmfstateget, mapl_return, mapl_verify
mapl_internalesmfstateget calls esmf_stateget, mapl_internalesmfstateget, mapl_return, mapl_verify, mapl_get, get_child_gridcomp, get_num_children, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_get calls mapl_genericstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_error_message calls at, insert
get_num_children calls get_num_children
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_genericstateget calls mapl_return, mapl_verify, get_child_gridcomp, get_num_children, ESMF_GridGet, get_child_export_state, get_child_import_state, get_grid, get_internal_state, mapl_locstreamget, mapl_sunorbitcreated, mapl_sunorbitcreatefromconfig