get_writing_PE – MAPL
get_writing_PE Function
7 statements
Source File
private function get_writing_PE(this, id) result(rank)
Type Bound
MultiCommServer
Arguments
Type Intent Optional Attributes Name
class(MultiCommServer), intent(in) :: this
integer, intent(in) :: id
Return Value integer
Calls
Called by
Contents
Source Code
get_writing_PE
Source Code
   function get_writing_PE(this,id) result (rank)
      class(MultiCommServer),intent(in) :: this
      integer, intent(in) :: id
      integer :: rank, ith
      ith  = mod(id-1,this%nwriter)
      rank = this%back_ranks(ith+1)
   end function get_writing_PE
Call graph
get_writing_pe calls back_ranks
clean_up calls get_writing_pe, put_datatofile
create_remote_win calls get_writing_pe
put_datatofile calls get_writing_pe