get_node_id – MAPL
get_node_id Function
38 statements
Source File
private function get_node_id(this, unusable, rc) result(node_id)
Type Bound
SimpleCommSplitter
Arguments
Type Intent Optional Attributes Name
class(SimpleCommSplitter), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function get_node_id(this, unusable, rc) result(node_id)
      class (SimpleCommSplitter), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: node_comm
      integer :: shared_communicator
      integer :: npes, rank, ierror
      integer :: status
      integer :: rank_on_node
      integer, allocatable :: node_ranks(:)
      integer :: info = MPI_INFO_NULL
      _UNUSED_DUMMY(unusable)
      shared_communicator = this%get_shared_communicator()
      call MPI_Comm_split_type(shared_communicator, MPI_COMM_TYPE_SHARED, 0, info, node_comm, ierror)
      _VERIFY(ierror)
      call MPI_Comm_size(shared_communicator, npes, ierror); _VERIFY(ierror)
      call MPI_Comm_rank(shared_communicator, rank, ierror); _VERIFY(ierror)
      call MPI_Comm_rank(node_comm, rank_on_node, ierror); _VERIFY(ierror)
      allocate(node_ranks(0:npes-1), stat=status);  _VERIFY(status)
      call MPI_Allgather(rank_on_node, 1, MPI_INTEGER, node_ranks, 1, MPI_INTEGER, shared_communicator, ierror)
      _VERIFY(ierror)
      if (rank_on_node == 0) then
         node_id = 1 + count(node_ranks(0:rank-1) == 0)  ! Numbering starts at _1_.
      end if
      ! Share node_id with other processes on same node
      call MPI_Bcast(node_id, 1, MPI_INTEGER, 0, node_comm, ierror)
      _VERIFY(ierror)
      call Mpi_Comm_free(node_comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
   end function get_node_id
Call graph
get_node_id calls mpi_allgather, mpi_bcast, mpi_comm_free, mpi_comm_rank, mpi_comm_size, mpi_comm_split_type, get_shared_communicator, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
compute_color calls get_node_id
split calls compute_color
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls split
new_multigroupserver calls split
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator
main calls initialize, create_member_subcommunicator
run_ensemble calls create_member_subcommunicator
time_ave calls initialize
ut_regridding calls initialize