get_CapGridComp_from_gc – MAPL
get_CapGridComp_from_gc Function
12 statements
Source File
private function get_CapGridComp_from_gc(gc, rc) result(cap)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
integer, intent(out), optional :: rc
Return Value type(MAPL_CapGridComp), pointer
Calls
Called by
Source Code
  function get_CapGridComp_from_gc(gc, rc) result(cap)
    type(ESMF_GridComp), intent(inout) :: gc
    integer, optional, intent(out) :: rc
    type(MAPL_CapGridComp), pointer :: cap
    type(MAPL_CapGridComp_Wrapper) :: cap_wrapper
    integer :: status
    call ESMF_UserCompGetInternalState(gc, internal_cap_name, cap_wrapper, status)
    _VERIFY(status)
    cap => cap_wrapper%ptr
    _RETURN(_SUCCESS)
  end function get_CapGridComp_from_gc
Call graph
get_capgridcomp_from_gc calls ESMF_UserCompGetInternalState, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
finalize_gc calls get_capgridcomp_from_gc
initialize_gc calls get_capgridcomp_from_gc
run_mapl_gridcomp calls get_capgridcomp_from_gc
set_services_gc calls get_capgridcomp_from_gc
run_gc calls run_mapl_gridcomp