get_variables – MAPL
get_variables Function
8 statements
Source File
private function get_variables(this, rc) result(variables)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value type(StringVariableMap), pointer
Calls
Called by
Source Code
   function get_variables(this, rc ) result(variables)
      type (StringVariableMap), pointer :: variables
      class (FileMetadata), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      variables => this%variables
      _RETURN(_SUCCESS)
   end function get_variables
Call graph
get_variables calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
check_flip calls get_variables
def_variables calls get_variables
get_level_name calls get_variables
mapl_create_bundle_from_metdata_id calls get_variables, get_level_name
mapl_iochangeres calls get_variables
mapl_iocountlevels calls get_variables
mapl_iocountnondimvars calls get_variables
mapl_iogetnondimvars calls get_variables
merge calls get_variables
transfer_metadata calls get_variables
write_const_variables calls get_variables
write_coordinate_variables calls get_variables
write_data calls get_variables
add_variable calls def_variables
create_grid calls get_level_name
get_file_levels calls get_level_name
getlevs calls get_level_name
mapl_bundlereadncpar calls check_flip
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
write calls def_variables, write_const_variables, write_coordinate_variables
main calls transfer_metadata, write_data, get_file_levels, mapl_read_bundle
time_ave calls get_level_name, get_file_levels, mapl_read_bundle
mapl_varreadncpar calls mapl_bundlereadncpar
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
initialize_ calls getlevs
process_command_line calls create_grid
ut_regridding calls mapl_read_bundle