get_coordinate_bounds_name – MAPL
get_coordinate_bounds_name Function
23 statements
Source File
private function get_coordinate_bounds_name(metadata, coord_name, rc) result(coord_bounds_name)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: metadata
character(len=*), intent(in) :: coord_name
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Call graph
get_coordinate_bounds_name calls mapl_assert, get_attribute, get_value, get_variable, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_value calls mapl_return
get_variable calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
initialize_from_file_metadata calls get_coordinate_bounds_name