get_cptr_i8 – MAPL
get_cptr_i8 Subroutine
40 statements
Source File
private subroutine get_cptr_i8(x, cptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(c_ptr), intent(out) :: cptr
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
get_cptr_i8
Source Code
   subroutine get_cptr_i8(x, cptr, rc)
      type(ESMF_Field), intent(inout) :: x
      type(c_ptr), intent(out) :: cptr
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: rank
      integer(kind=ESMF_KIND_I8), pointer :: x_1d(:)
      integer(kind=ESMF_KIND_I8), pointer :: x_2d(:,:)
      integer(kind=ESMF_KIND_I8), pointer :: x_3d(:,:,:)
      integer(kind=ESMF_KIND_I8), pointer :: x_4d(:,:,:,:)
      integer(kind=ESMF_KIND_I8), pointer :: x_5d(:,:,:,:,:)
      call ESMF_FieldGet(x, rank=rank, _RC)
      select case (rank)
      case (1)
         call ESMF_FieldGet(x, farrayPtr = x_1d, _RC)
         cptr = c_loc(x_1d)
      case (2)
         call ESMF_FieldGet(x, farrayPtr = x_2d, _RC)
         cptr = c_loc(x_2d)
      case (3)
         call ESMF_FieldGet(x, farrayPtr = x_3d, _RC)
         cptr = c_loc(x_3d)
      case (4)
         call ESMF_FieldGet(x, farrayPtr = x_4d, _RC)
         cptr = c_loc(x_4d)
      case (5)
         call ESMF_FieldGet(x, farrayPtr = x_5d, _RC)
         cptr = c_loc(x_5d)
      case default
         _FAIL('Unsupported rank in FieldGetCptr().')
      end select
      _RETURN(_SUCCESS)
   end subroutine get_cptr_i8
Call graph
get_cptr_i8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_cptr calls get_cptr_i8
fieldgetcptr calls get_cptr
assign_fptr_r4_rank1 calls fieldgetcptr
assign_fptr_r4_rank2 calls fieldgetcptr
assign_fptr_r8_rank1 calls fieldgetcptr
assign_fptr_r8_rank2 calls fieldgetcptr
copy calls fieldgetcptr
copy_broadcast calls fieldgetcptr, copy
test_fieldgetcptr calls fieldgetcptr
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldcopy calls copy
fieldcopybroadcast calls copy_broadcast