get_child_by_index – MAPL
get_child_by_index Function
11 statements
Source File
private function get_child_by_index(this, i) result(child)
Type Bound
CompositeComponent
Arguments
Type Intent Optional Attributes Name
class(CompositeComponent), intent(in) :: this
integer, intent(in) :: i
Return Value class(AbstractFrameworkComponent), pointer
Calls
Called by
Source Code
   function get_child_by_index(this, i) result(child)
      class(AbstractFrameworkComponent), pointer :: child
      class(CompositeComponent), intent(in) :: this
      integer, intent(in) :: i
      class(AbstractComposite), pointer :: child_node
      child_node => this%composite%get_child(i)
      select type (child_node)
      class is (ConcreteComposite)
         child => child_node%get_component()
      end select
   end function get_child_by_index
Call graph
get_child_by_index calls get_component, get_child, of
get_child_by_name calls m_at
m_at calls m_find
activate_threading calls get_child
deactivate_threading calls get_child
get_ith_child calls get_child
stub_child calls get_child
get_child_export_state calls get_ith_child
get_child_gridcomp calls get_ith_child
get_child_import_state calls get_ith_child
get_child_internal_state calls get_ith_child
omp_driver calls activate_threading, deactivate_threading