get_order – MAPL
get_order Function
13 statements
Source File
private function get_order(this, unusable, rc) result(order)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Called by
Source Code
   function get_order(this, unusable, rc ) result(order)
      class (FileMetadata), target, intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (StringVector) :: order
      order = this%order
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function get_order
Call graph
get_order calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
alphabatize_variables calls get_order, alphabatize_variables
create_metadata calls get_order, alphabatize_variables, create_metadata
createfilemetadata calls get_order, alphabatize_variables
def_variables calls get_order
test_serialize calls get_order
add_variable calls def_variables
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata, create_metadata, initialize
run calls createfilemetadata
write calls def_variables
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main