get_step_counter – MAPL
get_step_counter Function
5 statements
Source File
private function get_step_counter(this) result(step_counter)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(in) :: this
Return Value integer
Called by
Source Code
  function get_step_counter(this) result (step_counter)
    class (MAPL_CapGridComp), intent(in) :: this
    integer :: step_counter
    step_counter = this%step_counter
  end function get_step_counter
Call graph
step calls get_step_counter
run_mapl_gridcomp calls step
step_model calls step
model_advance calls step_model
run_gc calls run_mapl_gridcomp