get_timezone_offset – MAPL
get_timezone_offset Function
4 statements
Source File
public function get_timezone_offset(self)
Type Bound
ISO8601Time
Arguments
Type Intent Optional Attributes Name
class(ISO8601Time), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_timezone_offset(self)
      class(ISO8601Time), intent(in) :: self
      get_timezone_offset = self%timezone_offset_
   end function get_timezone_offset
Call graph
get_timezone_offset_datetime calls get_timezone_offset
test_construct_iso8601time calls get_timezone_offset
test_iso8601time_getters calls get_timezone_offset
test_construct_iso8601datetime calls get_timezone_offset_datetime
test_iso8601datetime_getters calls get_timezone_offset_datetime