get_row – MAPL
get_row Function
15 statements
Source File
private function get_row(this, node) result(row)
Type Bound
MaxCycleColumn
Arguments
Type Intent Optional Attributes Name
class(MaxCycleColumn), intent(in) :: this
class(AbstractMeterNode), intent(in), target :: node
Return Value class(*), allocatable
Calls
Contents
Source Code
get_row
Source Code
   function get_row(this, node) result(row)
      class(*), allocatable :: row
      class (MaxCycleColumn), intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      class (AbstractMeter), pointer :: tmr
      tmr => node%get_meter()
      select type (tmr)
      class is (AdvancedMeter)
         if (.not. allocated(this%option)) then
            allocate(row, source=tmr%get_max_cycle())
         else
            call this%get_row_dist(node, row)
         end if
      end select
   end function get_row
Call graph
get_row calls get_max_cycle, get_meter, get_row_dist
get_row_dist calls get_meter, fill_row, get_statistics