get_millisecond – MAPL
get_millisecond Function
4 statements
Source File
public function get_millisecond(self)
Type Bound
ISO8601Time
Arguments
Type Intent Optional Attributes Name
class(ISO8601Time), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_millisecond(self)
      class(ISO8601Time), intent(in) :: self
      get_millisecond = self%millisecond_
   end function get_millisecond
Call graph
get_millisecond_datetime calls get_millisecond
test_construct_iso8601time calls get_millisecond
test_iso8601time_getters calls get_millisecond
test_construct_iso8601datetime calls get_millisecond_datetime
test_iso8601datetime_getters calls get_millisecond_datetime