get_unique_request_id – MAPL
get_unique_request_id Function
7 statements
Source File
private function get_unique_request_id(this) result(request_id)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
Return Value integer
Called by
Source Code
   integer function get_unique_request_id(this) result(request_id)
      class (ClientThread), intent(inout) :: this
      associate (n => this%request_counter)
        n = MIN_ID + mod(n +1 - MIN_ID, (MAX_ID-MIN_ID+1))
      end associate
      request_id = this%request_counter
   end function get_unique_request_id
Call graph
prefetch_data calls get_unique_request_id, prefetch_data
stage_data calls get_unique_request_id, stage_data
run calls prefetch_data
test_prefetch_data calls prefetch_data
test_wait calls prefetch_data
main calls run