get_time_range – MAPL
get_time_range Function
35 statements
Source File
private function get_time_range(this, item_name, rc) result(time_range)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(in), target :: this
character(len=*), intent(in) :: item_name
integer, intent(out), optional :: rc
Return Value type(ESMF_Time), allocatable, (:)
Calls
Called by
Source Code
   function get_time_range(this,item_name,rc) result(time_range)
      type(ESMF_Time), allocatable :: time_range(:)
      class(ExtDataConfig), target, intent(in) :: this
      character(len=*), intent(in) :: item_name
      integer, optional, intent(out) :: rc
      type(ExtDataRuleMapIterator) :: rule_iterator
      character(len=:), pointer :: key
      type(StringVector) :: start_times
      integer :: num_rules
      type(ExtDataRule), pointer :: rule
      integer :: i,status,idx
      type(ESMF_Time) :: very_future_time
      rule_iterator = this%rule_map%begin()
      do while(rule_iterator /= this%rule_map%end())
         key => rule_iterator%key()
         idx = index(key,rule_sep)
         if (idx > 0) then
            if (key(1:idx-1) == trim(item_name)) then
               rule => rule_iterator%value()
               call start_times%push_back(rule%start_time)
            end if
         end if
         call rule_iterator%next()
      enddo
      num_rules = start_times%size()
      allocate(time_range(num_rules+1))
      do i=1,num_rules
          time_range(i) = string_to_esmf_time(start_times%at(i))
      enddo
      call ESMF_TimeSet(very_future_time,yy=2365,mm=1,dd=1,_RC)
      time_range(num_rules+1) = very_future_time
      _RETURN(_SUCCESS)
   end function get_time_range
Call graph
get_time_range calls ESMF_TimeSet, at, m_begin, m_key, m_next, mapl_return, mapl_verify, string_to_esmf_time, push_back
m_begin calls s_begin
m_next calls s_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_to_esmf_time calls ESMF_TimeSet, mapl_return, mapl_verify, string_to_integer_date, string_to_integer_time
get_error_message calls at, insert
mapl_throw_exception calls initialize
s_begin calls s_next
s_next calls advpos
string_to_integer_date calls mapl_return
string_to_integer_time calls mapl_return
advpos calls at, exists, get_child, opposite
initialize_ calls get_time_range