get_eta_onestep_r8 – MAPL
get_eta_onestep_r8 Subroutine
15 statements
Source File
private subroutine get_eta_onestep_r8(filename, ptop, pint, ak, bk, unusable, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
real(kind=REAL64), intent(out) :: ptop
real(kind=REAL64), intent(out) :: pint
real(kind=REAL64), intent(out) :: ak(:)
real(kind=REAL64), intent(out) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
get_eta_onestep_r8
Source Code
   subroutine get_eta_onestep_r8(filename, ptop, pint, ak, bk, unusable, rc)
      character(len=*), intent(in) :: filename
      real(kind=REAL64), intent(out) :: ak(:)
      real(kind=REAL64), intent(out) :: bk(:)
      real(kind=REAL64), intent(out) :: ptop ! model top (Pa)
      real(kind=REAL64), intent(out) :: pint ! transition to p (Pa)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type (EtaHybridVerticalCoordinate) :: vgrid
      _UNUSED_DUMMY(unusable)
      vgrid = EtaHybridVerticalCoordinate(filename)
      call vgrid%get_eta(ptop, pint, ak, bk, _RC )
   end subroutine get_eta_onestep_r8
Call graph
get_eta_onestep_r8 calls etahybridverticalcoordinate, get_eta, mapl_verify
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_cfg, new_etahybridverticalcoordinate_by_file
get_eta calls get_eta_onestep_r8, get_eta_onestep_r4
mapl_verify calls mapl_throw_exception
get_eta_onestep_r4 calls etahybridverticalcoordinate, get_eta, mapl_verify
mapl_throw_exception calls initialize
new_etahybridverticalcoordinate_by_ak_bk calls mapl_assert
new_etahybridverticalcoordinate_by_cfg calls etahybridverticalcoordinate, mapl_verify, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine
new_etahybridverticalcoordinate_by_file calls etahybridverticalcoordinate, mapl_verify, ESMF_ConfigLoadFile
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_eta_r4 calls get_eta