get_extra_derived_items – MAPL
get_extra_derived_items Function
38 statements
Source File
private function get_extra_derived_items(this, primary_items, derived_items, rc) result(needed_vars)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(inout) :: this
type(StringVector), intent(in) :: primary_items
type(StringVector), intent(in) :: derived_items
integer, intent(out), optional :: rc
Return Value type(StringVector)
Calls
Contents
Source Code
get_extra_derived_items
Source Code
   function get_extra_derived_items(this,primary_items,derived_items,rc) result(needed_vars)
      type(StringVector) :: needed_vars
      class(ExtDataConfig), intent(inout) :: this
      type(StringVector), intent(in) :: primary_items
      type(StringVector), intent(in) :: derived_items
      integer, intent(out), optional :: rc
      integer :: status
      type(StringVectorIterator) :: string_iter
      type(ExtDataDerived), pointer :: derived_item
      type(StringVector) :: variables_in_expression
      character(len=:), pointer :: sval,derived_name
      logical :: in_primary,found_rule
      integer :: i
      if (derived_items%size() ==0) then
         _RETURN(_SUCCESS)
      end if
      string_iter = derived_items%begin()
      do while(string_iter /= derived_items%end() )
         derived_name => string_iter%get()
         derived_item => this%derived_map%at(derived_name)
         variables_in_expression = derived_item%get_variables_in_expression(_RC)
         ! now we have a stringvector of the variables involved in the expression
         ! check which of this are already in primary_items list, if any are not
         ! then we need to createa new list of needed variables and the "derived field"
         ! wence to coppy them
         do i=1,variables_in_expression%size()
            sval => variables_in_expression%at(i)
            in_primary = string_in_stringVector(sval,primary_items)
            if (.not.in_primary) then
               found_rule = this%has_rule_for(sval,_RC)
               _ASSERT(found_rule,"no rule for "//trim(sval)//" needed by "//trim(derived_name))
               call needed_vars%push_back(sval//","//derived_name)
            end if
         enddo
         call string_iter%next()
      enddo
      _RETURN(_SUCCESS)
   end function get_extra_derived_items
Call graph
get_extra_derived_items calls at, begin, get, get_variables_in_expression, mapl_assert, next, has_rule_for, mapl_return, mapl_verify, string_in_stringvector, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
has_rule_for calls next, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_in_stringvector calls begin, get, next
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize