get_DataFromMem – MAPL
get_DataFromMem Subroutine
43 statements
Source File
private subroutine get_DataFromMem(this, multi_data_read, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
logical, intent(in) :: multi_data_read
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_DataFromMem( this, multi_data_read, rc)
      class (ServerThread), target, intent(inout) :: this
      logical, intent(in) :: multi_data_read
      integer, optional, intent(out) :: rc
      type (LocalMemReference) :: mem_data_reference
      class(AbstractDataReference),pointer :: dataRefPtr
      integer :: node_rank, innode_rank
      integer(kind=INT64) :: g_offset, offset,msize_word
      type(c_ptr) :: offset_address
      integer,pointer :: i_ptr(:)
      type (MessageVectorIterator) :: iter
      class (AbstractMessage), pointer :: msg
      class(AbstractSocket),pointer :: connection
      integer :: status
      connection=>this%get_connection(status)
      _VERIFY(status)
      iter = this%request_backlog%begin()
      do while (iter /= this%request_backlog%end())
         msg => iter%get()
         select type (q=>msg)
         type is (CollectivePrefetchDataMessage)
            mem_data_reference = LocalMemReference(q%type_kind,q%count)
            offset = this%containing_server%prefetch_offset%at(i_to_string(q%request_id))
           !W.J node: these three lines are necessary for read_and_gather call
           if ( .not. multi_data_read) then
              call this%containing_server%distribute_task(q%request_id,node_rank,innode_rank)
              g_offset = this%containing_server%prefetch_offset%at(i_to_string(-node_rank))
              offset = offset+g_offset
           endif
           msize_word  = this%containing_server%prefetch_offset%at(i_to_string(MSIZE_ID))
           dataRefPtr => this%containing_server%get_dataReference()
           call c_f_pointer(dataRefPtr%base_address,i_ptr,shape=[msize_word])
           offset_address = c_loc(i_ptr(offset+1))
           call mem_data_reference%fetch_data(offset_address,q%global_count,q%start-q%global_start+1)
           call this%insert_RequestHandle(q%request_id, &
              & connection%put(q%request_id, mem_data_reference))
           call this%request_backlog%erase(iter)
         class default
           _FAIL( "Message type should be CollectivePrefetchDataMessage ")
         end select
         iter = this%request_backlog%begin()
      enddo
      _RETURN(_SUCCESS)
   end subroutine get_DataFromMem
Call graph
get_datafrommem calls at, mapl_assert, erase, distribute_task, fetch_data, get_connection, get_datareference, i_to_string, insert_requesthandle, mapl_return, mapl_verify, v_begin, v_iter_get, put, get_datafrommem
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fetch_data calls mapl_assert, mapl_return
get_connection calls mapl_assert, mapl_return
get_datareference calls at
i_to_string calls mapl_assert, mapl_return
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
v_erase_one calls erase
m_insert_pair calls s_insert
v_at_32 calls v_at_size_kind