get_longitudes – MAPL
get_longitudes Function
11 statements
Source File
private function get_longitudes(this, unusable, rc) result(longitudes)
Uses
MAPL_BaseMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Source Code
   function get_longitudes(this, unusable, rc) result(longitudes)
      use MAPL_BaseMod
      class (LatLonGridFactory), intent(in) :: this
      real(kind=REAL64), allocatable :: longitudes(:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      longitudes = this%lon_centers
      _RETURN(_SUCCESS)
   end function get_longitudes
Call graph
get_longitudes calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
test_cartesian_to_spherical_x calls get_longitudes
test_cartesian_to_spherical_y calls get_longitudes
test_cartesian_to_spherical_z calls get_longitudes
test_spherical_to_cartesian_east_wind calls get_longitudes
test_spherical_to_cartesian_north_wind calls get_longitudes