get_num_rows_separator – MAPL
get_num_rows_separator Function
8 statements
Source File
private function get_num_rows_separator(this) result(num_rows)
Type Bound
TextColumn
Arguments
Type Intent Optional Attributes Name
class(TextColumn), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_num_rows_separator(this) result(num_rows)
      class (TextColumn), intent(in) :: this
      if (allocated(this%separator)) then
         num_rows = 1
      else
         num_rows = 0
      end if
   end function get_num_rows_separator
Call graph
add_column calls get_num_rows_separator
get_header calls get_num_rows_separator, get_num_rows_header
get_num_rows_header calls get_num_rows_separator
new_multicolumn calls get_num_rows_separator
multicolumn calls new_multicolumn
generate_report calls add_column
generate_report_profiler calls get_header
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column, generate_report
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize, report_profile
mapl_finalize calls report_global_profiler
start calls report_profile
test_one_timer calls get_header
time_ave calls generate_report