get_current_time – MAPL
get_current_time Function
10 statements
Source File
private function get_current_time(this, rc) result(current_time)
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp) :: this
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Contents
Source Code
get_current_time
Source Code
  function get_current_time(this, rc) result (current_time)
    class (MAPL_CapGridComp) :: this
    type(ESMF_Time) :: current_time
    integer, optional, intent(out) :: rc
    integer :: status
    call ESMF_ClockGet(this%clock,currTime=current_time,rc=status)
    _VERIFY(status)
    _RETURN(ESMF_SUCCESS)
  end function get_current_time
Call graph
get_current_time calls esmf_clockget, mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize