get_num_nodes – MAPL
get_num_nodes Function
12 statements
Source File
private recursive function get_num_nodes(this) result(num_nodes)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(in), target :: this
Return Value integer
Calls
Called by
Source Code
   recursive integer function get_num_nodes(this) result(num_nodes)
      class (MeterNode), target, intent(in) :: this
      type (MeterNodeVectorIterator) :: iter
      class (AbstractMeterNode), pointer :: child
      num_nodes = 1
      iter = this%children%begin()
      do while (iter /= this%children%end())
         child => iter%get()
         num_nodes = num_nodes + child%get_num_nodes()
         call iter%next()
      end do
   end function get_num_nodes
Call graph
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
get_num_meters calls get_num_nodes
test_count_nodes_depth_0 calls get_num_nodes
test_count_nodes_depth_1 calls get_num_nodes
test_get_num_nodes calls get_num_nodes
test_get_num_nodes_2 calls get_num_nodes
test_accumulate_nested calls get_num_meters
test_accumulate_sub calls get_num_meters
test_start_one calls get_num_meters