get_am_i_root – MAPL
get_am_i_root Function
8 statements
Source File
private function get_am_i_root(this, rc) result(amiroot)
Type Bound
ExtData_DriverGridComp
Arguments
Type Intent Optional Attributes Name
class(ExtData_DriverGridComp) :: this
integer, intent(out), optional :: rc
Return Value logical
Calls
Source Code
  function get_am_i_root(this, rc) result (amiroot)
    class (ExtData_DriverGridComp) :: this
    integer, optional, intent(out) :: rc
    logical :: amiroot
    amiroot = this%amiroot
    _RETURN(ESMF_SUCCESS)
  end function get_am_i_root
Call graph
get_am_i_root calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize