get_filename_from_template – MAPL
get_filename_from_template Function
22 statements
Source File
public function get_filename_from_template(time, file_template, rc) result(filename)
Uses
Plain_netCDF_Time
MAPL_StringTemplate
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: time
character(len=*), intent(in) :: file_template
integer, intent(out), optional :: rc
Return Value character(len=ESMF_MAXSTR)
Calls
Source Code
  function get_filename_from_template (time, file_template, rc) result(filename)
    use Plain_netCDF_Time, only : ESMF_time_to_two_integer
    use  MAPL_StringTemplate, only : fill_grads_template
    type(ESMF_Time), intent(in) :: time
    character(len=*), intent(in) :: file_template
    character(len=ESMF_MAXSTR) :: filename
    integer, optional, intent(out) :: rc
    integer :: itime(2)
    integer :: nymd, nhms
    integer :: status
    _FAIL ('DO not use get_filename_from_template')
    call ESMF_time_to_two_integer(time, itime, _RC)
    print*, 'two integer time, itime(:)', itime(1:2)
    nymd = itime(1)
    nhms = itime(2)
    call fill_grads_template ( filename, file_template, &
         experiment_id='', nymd=nymd, nhms=nhms, _RC )
    print*, 'ck: obsFile_T=', trim(filename)
    _RETURN(ESMF_SUCCESS)
  end function get_filename_from_template
Call graph
get_filename_from_template calls mapl_assert, esmf_time_to_two_integer, fill_grads_template, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
esmf_time_to_two_integer calls mapl_return, mapl_verify, ESMF_TimeGet
fill_grads_template calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, check_token, evaluate_token
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evaluate_token calls mapl_assert, mapl_verify, ESMF_TimeGet, ESMF_CalendarCreate, ESMF_CalendarDestroy, ESMF_TimeSet, skip_token
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize