get_fname_by_rank – MAPL
get_fname_by_rank Function
7 statements
Source File
public function get_fname_by_rank(fname, rank) result(name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
integer, intent(in) :: rank
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_fname_by_rank(fname, rank) result(name)
     character(len=:), allocatable :: name
     character(len=*), intent(in) :: fname
     integer, intent(in) :: rank
     integer :: i
     name = trim(fname)//"_"//i_to_string(rank)
   end function get_fname_by_rank
Call graph
get_fname_by_rank calls i_to_string
i_to_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_bundlereadncpar calls get_fname_by_rank
mapl_bundlewritencpar calls get_fname_by_rank, mapl_fieldwritencpar
mapl_esmfstatereadfromfile calls get_fname_by_rank, mapl_varreadncpar
mapl_fieldwritencpar calls get_fname_by_rank, mapl_varwrite
mapl_statevarreadncpar calls get_fname_by_rank, mapl_varreadncpar
mapl_varwritencpar_r4_2d calls get_fname_by_rank
mapl_varwritencpar_r4_3d calls get_fname_by_rank, mapl_varwrite
mapl_varwritencpar_r4_4d calls get_fname_by_rank, mapl_varwrite
mapl_varwritencpar_r8_2d calls get_fname_by_rank
mapl_varwritencpar_r8_3d calls get_fname_by_rank, mapl_varwrite
mapl_varwritencpar_r8_4d calls get_fname_by_rank, mapl_varwrite
mapl_varreadncpar calls mapl_bundlereadncpar, mapl_statevarreadncpar
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_varwrite calls mapl_varwritencpar_r4_2d, mapl_varwritencpar_r4_3d, mapl_varwritencpar_r4_4d, mapl_varwritencpar_r8_2d, mapl_varwritencpar_r8_3d, mapl_varwritencpar_r8_4d
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarwritencpar calls mapl_bundlewritencpar
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore