get_rank – MAPL
get_rank Function
8 statements
Source File
private function get_rank(this, rc) result(rank)
Type Bound
UnlimitedEntity
Arguments
Type Intent Optional Attributes Name
class(UnlimitedEntity), intent(in) :: this
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function get_rank(this, rc) result(rank)
      class (UnlimitedEntity), intent(in) :: this
      integer, optional, intent(out) :: rc
      integer :: rank
      rank = size(this%get_shape())
      _RETURN(_SUCCESS)
   end function get_rank
Call graph
get_rank calls get_shape, mapl_return
get_shape calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_const_value calls get_rank
equal calls get_rank
serialize calls get_rank, serialize
unlimitedentity_deserialize calls get_rank
append_metadata calls add_const_value
append_vertical_metadata calls add_const_value
attribute_deserialize calls unlimitedentity_deserialize
create_file_metada calls add_const_value
run calls add_const_value
stringattributemap_serialize calls serialize
stringunlimitedentitymap_deserialize calls unlimitedentity_deserialize
stringunlimitedentitymap_serialize calls serialize
test_serialize calls serialize, add_const_value, unlimitedentity_deserialize
variable_deserialize calls unlimitedentity_deserialize