get_row – MAPL
get_row Function
10 statements
Source File
private function get_row(this, node) result(row)
Type Bound
ExclusiveColumn
Arguments
Type Intent Optional Attributes Name
class(ExclusiveColumn), intent(in) :: this
class(AbstractMeterNode), intent(in), target :: node
Return Value class(*), allocatable
Calls
Source Code
   function get_row(this, node) result(row)
      class(*), allocatable :: row
      class (ExclusiveColumn), intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      if (.not. allocated(this%option)) then
         allocate(row, source=node%get_exclusive())
      else
         call this%get_row_dist(node, row)
      end if
   end function get_row
Call graph
get_row calls get_exclusive, get_row_dist
get_row_dist calls get_meter, get_statistics, fill_row