get_coordinate_bounds – MAPL
get_coordinate_bounds Function
46 statements
Source File
private function get_coordinate_bounds(metadata, coord_name, rc) result(coord_bounds)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in) :: metadata
character(len=*), intent(in) :: coord_name
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Call graph
get_coordinate_bounds calls mapl_assert, get_var, get_attribute, get_dimension, get_source_file, get_value, get_variable, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_dimension calls mapl_return, at, find
get_source_file calls mapl_assert, mapl_return
get_value calls mapl_return
get_variable calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_var_real64_4 calls mapl_assert, mapl_return, nf90_get_var, nf90_inq_ncid, nf90_inq_varid
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
initialize_from_file_metadata calls get_coordinate_bounds