get_unit_vector – MAPL
get_unit_vector Function
14 statements
Source File
private function get_unit_vector(p1, p2, p3) result(uvect)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: p1(2)
real(kind=REAL64), intent(in) :: p2(2)
real(kind=REAL64), intent(in) :: p3(2)
Return Value real(kind=REAL64), (3)
Calls
Called by
Contents
Source Code
get_unit_vector
Source Code
   function get_unit_vector( p1, p2, p3 ) result(uvect)
      real(REAL64), intent(in):: p1(2), p2(2), p3(2)
      real(REAL64) :: uvect(3)
      real(REAL64) :: xyz1(3), xyz2(3), xyz3(3)
      real(REAL64) :: ap
      xyz1 = latlon2xyz(p1,right_hand=.true.)
      xyz2 = latlon2xyz(p2,right_hand=.true.)
      xyz3 = latlon2xyz(p3,right_hand=.true.)
      uvect = xyz3-xyz1
      ap = dot_product(uvect,xyz2)
      uvect = uvect - ap*xyz2
      ap = dot_product(uvect,uvect)
      uvect=uvect/sqrt(ap)
   end function get_unit_vector
Call graph
get_unit_vector calls latlon2xyz
computegridbasis calls get_unit_vector
get_basis calls computegridbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis