get_dimension – MAPL
get_dimension Function
20 statements
Source File
private function get_dimension(this, dim_name, unusable, rc) result(extent)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: dim_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function get_dimension(this, dim_name, unusable, rc) result(extent)
      class (FileMetadata), target, intent(in) :: this
      character(len=*), intent(in) :: dim_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (StringIntegerMapIterator) :: iter
      iter = this%dimensions%find(dim_name)
      if (iter /= this%dimensions%end()) then
         extent = this%dimensions%at(dim_name)
         _RETURN(_SUCCESS)
      else
         extent = 0
         if (present(rc)) rc=pFIO_DIMENSION_NOT_FOUND
      end if
      _UNUSED_DUMMY(unusable)
   end function get_dimension
Call graph
get_dimension calls at, find, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
compare_grid_file calls get_dimension
create_cubed_sphere_grid calls get_dimension
create_grid calls get_dimension
get_coordinate_bounds calls get_dimension
get_coordinate_info calls get_dimension
get_file_times calls get_dimension
initialize_from_file_metadata calls get_dimension, get_coordinate_bounds
make_factory_from_file calls get_dimension
mapl_create_bundle_from_metdata_id calls get_dimension
mapl_iocountlevels calls get_dimension
mapl_readtilingnc4 calls get_dimension
test_get_dimension calls get_dimension
test_get_dimension_missing calls get_dimension
main calls get_dimension, get_file_times
create_esmf_grids calls create_cubed_sphere_grid
get_file_levels calls get_coordinate_info
get_time_info calls get_coordinate_info
getlevs calls get_coordinate_info
initialize_ calls get_coordinate_info
mapl_bundlereadncpar calls compare_grid_file
mapl_locstreamcreatefromfile calls mapl_readtilingnc4
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
process_command_line calls create_grid
time_ave calls get_coordinate_info, get_file_times