get_file_levels – MAPL
get_file_levels Subroutine
34 statements
Source File
subroutine get_file_levels(filename, vertical_data, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(verticalData), intent(inout) :: vertical_data
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
get_file_levels
Source Code
   subroutine get_file_levels(filename,vertical_data,rc)
      character(len=*), intent(in) :: filename
      type(VerticalData), intent(inout) :: vertical_data
      integer, intent(out), optional :: rc
      integer :: status
      type(NetCDF4_fileFormatter) :: formatter
      type(FileMetadata) :: basic_metadata
      type(FileMetadataUtils) :: metadata
      character(len=:), allocatable :: lev_name
      character(len=ESMF_MAXSTR) :: long_name
      character(len=ESMF_MAXSTR) :: standard_name
      character(len=ESMF_MAXSTR) :: vcoord
      character(len=ESMF_MAXSTR) :: lev_units
      real, allocatable, target :: levs(:)
      real, pointer :: plevs(:)
      call formatter%open(trim(filename),pFIO_Read,_RC)
      basic_metadata=formatter%read(_RC)
      call metadata%create(basic_metadata,trim(filename))
      lev_name = metadata%get_level_name(_RC)
      if (lev_name /= '') then
         call metadata%get_coordinate_info(lev_name,coords=levs,coordUnits=lev_units,long_name=long_name,&
               standard_name=standard_name,coordinate_attr=vcoord,_RC)
         plevs => levs
         vertical_data = VerticalData(levels=plevs,vunit=lev_units,vcoord=vcoord,standard_name=standard_name,long_name=long_name, &
               force_no_regrid=.true.,_RC)
         nullify(plevs)
      end if
      if (present(rc)) then
         rc=_SUCCESS
      end if
   end subroutine get_file_levels
Call graph
get_file_levels calls create, get_coordinate_info, get_level_name, mapl_abort, mapl_verify
get_coordinate_info calls mapl_verify, get_attribute, get_coordinate_data, get_coordinate_variable, get_dimension, get_ith_dimension, get_value, mapl_assert, get_file_name, mapl_return, var_has_attr
get_level_name calls begin, get_coordinate_variable, get_variables, is_attribute_present, key, next, get_variable_attribute, mapl_return
mapl_abort calls mpi_abort
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file_name calls mapl_return
get_variable_attribute calls mapl_verify, get_attribute, get_value, mapl_assert, is_attribute_present, get_file_name, mapl_return, get_variable
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
var_has_attr calls mapl_verify, mapl_assert, is_attribute_present, get_file_name, mapl_return, get_variable
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
time_ave calls get_file_levels