get_root_node – MAPL
get_root_node Function
5 statements
Source File
private function get_root_node(this) result(root_node)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(in), target :: this
Return Value class(AbstractMeterNode), pointer
Called by
Source Code
   function get_root_node(this) result(root_node)
      class(AbstractMeterNode), pointer :: root_node
      class(BaseProfiler), target, intent(in) :: this
      !$omp master
      root_node => this%root_node
      !$omp end master
   end function get_root_node
Call graph
accumulate calls get_root_node
generate_report_profiler calls get_root_node
reduce calls get_root_node
reset calls get_root_node
test_accumulate_nested calls get_root_node, accumulate
test_accumulate_sub calls get_root_node, accumulate
main calls reduce, finalize, generate_report, accumulate, reset
mapl_genericfinalize calls reduce, generate_report
report_profile calls reduce, generate_report
test_accumulate_multi calls accumulate, reset
time_ave calls reduce, finalize, generate_report
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
generate_report calls generate_report
report_global_profiler calls generate_report
start calls report_profile
test_simple_report_timer calls generate_report
test_simple_report_timer_b calls generate_report
regrid_util calls main
finalize_io_clients_servers calls finalize
mapl_finalize calls report_global_profiler
ut_regridding calls finalize