get_local_element_count – MAPL
get_local_element_count Function
14 statements
Source File
private function get_local_element_count(x, rc) result(element_count)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
Return Value integer, allocatable, (:)
Calls
Called by
Source Code
   function get_local_element_count(x, rc) result(element_count)
      type(ESMF_Field), intent(inout) :: x
      integer, optional, intent(out) :: rc
      integer, allocatable :: element_count(:)
      integer :: status
      integer :: rank
      call ESMF_FieldGet(x, rank=rank, _RC)
      allocate(element_count(rank))
      ! ESMF has a big fat bug with multi tile grids and loal element count
      !call ESMF_FieldGet(x, localElementCount=element_count, _RC)
      ! until it is fixed we must kluge :(
      call MAPL_FieldGetLocalElementCount(x, element_count, _RC)
      _RETURN(_SUCCESS)
   end function get_local_element_count
Call graph
get_local_element_count calls esmf_fieldget, mapl_fieldgetlocalelementcount, mapl_return, mapl_verify
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_return, mapl_verify, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
fieldgetlocalelementcount calls get_local_element_count
clone calls get_local_element_count
fieldclone calls clone
are_broadcast_conformable calls fieldgetlocalelementcount
are_conformable_scalar calls fieldgetlocalelementcount
gemv_r4 calls fieldgetlocalelementcount
gemv_r8 calls fieldgetlocalelementcount
get_local_size calls fieldgetlocalelementcount
test_fieldgetlocalelementcount calls fieldgetlocalelementcount
fieldgemv calls gemv_r4, gemv_r8
fieldgetlocalsize calls get_local_size
fieldsarebroadcastconformable calls are_broadcast_conformable
fieldsareconformable calls are_conformable_scalar
compile calls fieldclone
statefilter_r4_2d calls fieldclone
statefilter_r4_3d calls fieldclone
test_fieldclone3d calls fieldclone