get_attributes – MAPL
get_attributes Function
8 statements
Source File
private function get_attributes(this, rc) result(attributes)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value type(StringAttributeMap), pointer
Calls
Called by
Source Code
   function get_attributes(this, rc ) result(attributes)
      type (StringAttributeMap), pointer :: attributes
      class (FileMetadata), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      attributes => this%global_var%get_attributes()
      _RETURN(_SUCCESS)
   end function get_attributes
Call graph
get_attributes calls get_attributes, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
merge calls get_attributes
put_attributes calls get_attributes
test_get_attributes calls get_attributes
transfer_metadata calls get_attributes
write calls put_attributes
main calls transfer_metadata