get_composite – MAPL
get_composite Function
5 statements
Source File
private function get_composite(this) result(composite)
Type Bound
CompositeComponent
Arguments
Type Intent Optional Attributes Name
class(CompositeComponent), intent(in), target :: this
Return Value class(AbstractComposite), pointer
Called by
Source Code
   function get_composite(this) result(composite)
      class(CompositeComponent), target, intent(in) :: this
      class(AbstractComposite), pointer :: composite
      composite => this%composite
   end function get_composite
Call graph
mapl_genericstateset calls get_composite
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
mapl_genericstatesetfromgc calls mapl_genericstateset
initialize_gc calls mapl_set
mapl_capgridcompcreate calls mapl_set
run_component_driver calls mapl_set
initialize_cap_gc calls mapl_capgridcompcreate
main calls run_component_driver