get_child_gridcomp – MAPL
get_child_gridcomp Function
8 statements
Source File
private function get_child_gridcomp(this, i) result(gridcomp)
Type Bound
MAPL_MetaComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_MetaComp), intent(in), target :: this
integer, intent(in) :: i
Return Value type(ESMF_GridComp), pointer
Calls
Called by
comp_testing_driver::run_component_driver w MAPL_GenericMod::MAPL_MetaComp%get_child_gridcomp
w
MAPL_CapGridCompMod::initialize_gc w
w
MAPL_GenericMod::MAPL_AddAttributeToFields_I4 w
w
MAPL_GenericMod::MAPL_AdjustIsNeeded w
w
MAPL_GenericMod::MAPL_ChildAddAttribToImportSpec w
w
MAPL_GenericMod::MAPL_DestroyStateSave w
w
MAPL_GenericMod::MAPL_DisableRecord w
w
MAPL_GenericMod::MAPL_ExchangeGridSet w
w
MAPL_GenericMod::MAPL_FindChild w
w
MAPL_GenericMod::MAPL_GCGet w
w
MAPL_GenericMod::MAPL_GenericConnCheck w
w
MAPL_GenericMod::MAPL_GenericFinalize w
w
MAPL_GenericMod::MAPL_GenericInitialize w
w
MAPL_GenericMod::MAPL_GenericRecord w
w
MAPL_GenericMod::MAPL_GenericRefresh w
w
MAPL_GenericMod::MAPL_GenericRunChildren w
w
MAPL_GenericMod::MAPL_GenericSetServices w
w
MAPL_GenericMod::MAPL_GenericSpecEnum w
w
MAPL_GenericMod::MAPL_GenericStateGet w
w
MAPL_GenericMod::MAPL_GenericStateRestore w
w
MAPL_GenericMod::MAPL_GenericStateSave w
w
MAPL_GenericMod::MAPL_GetAllExchangeGrids w
w
MAPL_GenericMod::MAPL_GetChildLocstream w
w
MAPL_GenericMod::MAPL_GridCompGetFriendlies0 w
w
MAPL_GenericMod::MAPL_ImportStateGet w
w
MAPL_GenericMod::MAPL_InternalESMFStateGet w
w
MAPL_GenericMod::MAPL_SetStateSave w
w
MAPL_GenericMod::MAPL_StateAddExportSpecFrmAll w
w
MAPL_GenericMod::MAPL_StateAddExportSpecFrmChld_All w
w
MAPL_GenericMod::MAPL_StateAddImportSpecFrmChld w
w
MAPL_GenericMod::MAPL_StatePrintSpec w
w
MAPL_GenericMod::MAPL_StatePrintSpecCSV w
w
MAPL_GenericMod::MAPL_TerminateImportAllBut w
w
MAPL_GenericMod::MAPL_WireComponent w
w
Source Code
   function get_child_gridcomp(this, i) result(gridcomp)
      type(ESMF_GridComp), pointer :: gridcomp
      class(MAPL_MetaComp), target, intent(in) :: this
      integer, intent(in) :: i
      class(MaplGenericComponent), pointer :: child
      child => this%get_ith_child(i)
      gridcomp => child%get_gridcomp()
   end function get_child_gridcomp
Call graph
get_child_gridcomp calls get_gridcomp, get_ith_child
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
get_child_by_index calls get_component, get_child
get_child_by_name calls get_component, get_child