get_year – MAPL
get_year Function
4 statements
Source File
public function get_year(self)
Type Bound
ISO8601Date
Arguments
Type Intent Optional Attributes Name
class(ISO8601Date), intent(in) :: self
Return Value integer
Called by
Source Code
   integer function get_year(self)
      class(ISO8601Date), intent(in) :: self
      get_year = self%year_
   end function get_year
Call graph
convert_iso8601_to_integer_date calls get_year
get_year_datetime calls get_year
test_construct_iso8601date calls get_year
test_iso8601date_getters calls get_year
convert_iso8601_to_esmf_time calls get_year_datetime
test_construct_iso8601datetime calls get_year_datetime
test_convert_iso8601_to_integer_date calls convert_iso8601_to_integer_date
test_iso8601datetime_getters calls get_year_datetime