get_dmessage – MAPL
get_dmessage Function
25 statements
Source File
private function get_dmessage(this, rc) result(dmessage)
Type Bound
BaseServer
Arguments
Type Intent Optional Attributes Name
class(BaseServer), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value class(AbstractMessage), pointer
Calls
Call graph
get_dmessage calls mapl_assert, at, get_connection, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind