get_file_bracket – MAPL
get_file_bracket Subroutine
210 statements
Source File
private subroutine get_file_bracket(this, input_time, source_time, bracket, fail_on_missing_file, rc)
Type Bound
ExtDataClimFileHandler
Arguments
Type Intent Optional Attributes Name
class(ExtDataClimFileHandler), intent(inout) :: this
type(ESMF_Time), intent(in) :: input_time
type(ESMF_Time), intent(in) :: source_time(:)
type(ExtDataBracket), intent(inout) :: bracket
logical, intent(in) :: fail_on_missing_file
integer, intent(out), optional :: rc
Calls
Contents
Source Code
get_file_bracket
Source Code
   subroutine get_file_bracket(this, input_time, source_time, bracket, fail_on_missing_file, rc)
      class(ExtdataClimFileHandler), intent(inout) :: this
      type(ESMF_Time), intent(in) :: input_time
      type(ESMF_Time), intent(in) :: source_time(:)
      type(ExtDataBracket), intent(inout) :: bracket
      logical, intent(in) :: fail_on_missing_file
      integer, optional, intent(out) :: rc
      type(ESMF_Time) :: time
      integer :: time_index
      character(len=ESMF_MAXPATHLEN) :: current_file
      integer :: status
      type(ESMF_TimeInterval) :: zero
      type(ESMF_Time) :: target_time, clim_target_time
      integer :: target_year, original_year,clim_shift,valid_years(2)
      integer, allocatable :: source_years(:)
      _ASSERT(fail_on_missing_file,"Failure on missing file not allowed when rule is climatology")
      if (bracket%time_in_bracket(input_time)) then
         _RETURN(_SUCCESS)
      end if
      target_time=input_time
      _ASSERT(size(this%valid_range) == 2, 'Valid time is not defined so can not do any extrapolation or climatology')
      call ESMF_TimeGet(this%valid_range(1),yy=valid_years(1),_RC)
      call ESMF_TimeGet(this%valid_range(2),yy=valid_years(2),_RC)
      if (size(source_time)==2) then
         allocate(source_years(2))
         call ESMF_TimeGet(source_time(1),yy=source_years(1),_RC)
         call ESMF_TimeGet(source_time(2),yy=source_years(2),_RC)
         _ASSERT(source_time(1) >= this%valid_range(1),'source time outside valid range')
         _ASSERT(source_time(1) <=  this%valid_range(2),'source time outside valid range')
         _ASSERT(source_time(2) >=  this%valid_range(1),'source time outside valid range')
         _ASSERT(source_time(2) <= this%valid_range(2),'source time outside valid range')
      end if
      ! shift target year to request source time if specified
      ! is TS1 < TM < TS2, if not then extrapolate beyond that
      call ESMF_TimeGet(target_time,yy=target_year,_RC)
      original_year=target_year
      !if (size(source_years)>0) then
      if (allocated(source_years)) then
         if (input_time < source_time(1)) then
            target_year = source_years(1)
            this%clim_year = target_year
         else if (input_time >= source_time(2)) then
            target_year = source_years(2)
            this%clim_year = target_year
         end if
         call swap_year(target_time,target_year,_RC)
      else
         if (input_time <= this%valid_range(1)) then
            target_year = valid_years(1)
            this%clim_year = target_year
            call swap_year(target_time,target_year,_RC)
         else if (input_time >= this%valid_range(2)) then
            target_year = valid_years(2)
            this%clim_year = target_year
            call swap_year(target_time,target_year,_RC)
         end if
      end if
      clim_target_time = target_time
      ! the target time is contained in the dataset and we are not extrapolating outside of source time selection based on available data
      if (this%clim_year == CLIM_NULL) then
         call ESMF_TimeIntervalSet(zero,_RC)
         if (this%frequency == zero) then
            current_file = this%file_template
            call this%get_time_on_file(current_file,input_time,'L',time_index,time,_RC)
            _ASSERT(time_index/=time_not_found,"Time not found on file")
            call bracket%set_node('L',file=current_file,time_index=time_index,time=time,_RC)
            if (bracket%left_node == bracket%right_node) then
               call bracket%swap_node_fields(rc=status)
               _VERIFY(status)
            else
               bracket%new_file_left=.true.
            end if
            call this%get_time_on_file(current_file,input_time,'R',time_index,time,_RC)
            _ASSERT(time_index/=time_not_found,"Time not found on file")
            call bracket%set_node('R',file=current_file,time_index=time_index,time=time,_RC)
            bracket%new_file_right=.true.
         else
            call this%get_file(current_file,target_time,0,_RC)
            call this%get_time_on_file(current_file,target_time,'L',time_index,time,rc=status)
            if (time_index == time_not_found) then
               call this%get_file(current_file,target_time,-1,_RC)
               call this%get_time_on_file(current_file,target_time,'L',time_index,time,_RC)
               _ASSERT(time_index/=time_not_found,"Time not found on file")
            end if
            call bracket%set_node('L',file=current_file,time_index=time_index,time=time,_RC)
            if (bracket%left_node == bracket%right_node) then
               call bracket%swap_node_fields(rc=status)
               _VERIFY(status)
            else
               bracket%new_file_left=.true.
            end if
            target_time = clim_target_time
            call this%get_file(current_file,target_time,0,_RC)
            call this%get_time_on_file(current_file,target_time,'R',time_index,time,rc=status)
            if (time_index == time_not_found) then
               call this%get_file(current_file,target_time,1,_RC)
               call this%get_time_on_file(current_file,target_time,'R',time_index,time,_RC)
               _ASSERT(time_index/=time_not_found,"Time not found on file")
            end if
            call bracket%set_node('R',file=current_file,time_index=time_index,time=time,_RC)
            bracket%new_file_right=.true.
         end if
      ! the target time has been specified to be a climatology for the year; either we
      ! are outside the dataset or we have requested a source time range and are on
      ! or outside either end
      else
         call ESMF_TimeIntervalSet(zero,_RC)
         if (this%frequency == zero) then
            current_file = this%file_template
            clim_shift=0
            call this%get_time_on_file(current_file,target_time,'L',time_index,time,wrap=clim_shift,_RC)
            _ASSERT(time_index/=time_not_found,"Time not found on file")
            call swap_year(time,original_year+clim_shift,_RC)
            call bracket%set_node('L',file=current_file,time_index=time_index,time=time,_RC)
            if (bracket%left_node == bracket%right_node) then
               call bracket%swap_node_fields(rc=status)
               _VERIFY(status)
            else
               bracket%new_file_left=.true.
            end if
            clim_shift=0
            call this%get_time_on_file(current_file,target_time,'R',time_index,time,wrap=clim_shift,_RC)
            _ASSERT(time_index/=time_not_found,"Time not found on file")
            call swap_year(time,original_year+clim_shift,_RC)
            call bracket%set_node('R',file=current_file,time_index=time_index,time=time,_RC)
            bracket%new_file_right=.true.
         else
            call this%get_file(current_file,target_time,0,_RC)
            call this%get_time_on_file(current_file,target_time,'L',time_index,time,rc=status)
            if (time_index == time_not_found) then
               call this%get_file(current_file,target_time,-1,_RC)
               call this%get_time_on_file(current_file,target_time,'L',time_index,time,_RC)
               _ASSERT(time_index/=time_not_found,"Time not found on file")
               call ESMF_TimeGet(target_time,yy=target_year,_RC)
               if (target_year > this%clim_year) then
                  call swap_year(time,original_year-1,_RC)
               else
                  call swap_year(time,original_year,_RC)
               end if
            else
               call swap_year(time,original_year,_RC)
            end if
            if (bracket%left_node == bracket%right_node) then
               call bracket%swap_node_fields(rc=status)
               _VERIFY(status)
            else
               bracket%new_file_left=.true.
            end if
            call bracket%set_node('L',file=current_file,time_index=time_index,time=time,_RC)
            target_time = clim_target_time
            call this%get_file(current_file,target_time,0,_RC)
            call this%get_time_on_file(current_file,target_time,'R',time_index,time,rc=status)
            if (time_index == time_not_found) then
               call this%get_file(current_file,target_time,1,_RC)
               call this%get_time_on_file(current_file,target_time,'R',time_index,time,_RC)
               _ASSERT(time_index/=time_not_found,"Time not found on file")
               call ESMF_TimeGet(target_time,yy=target_year,_RC)
               if (target_year < this%clim_year) then
                  call swap_year(time,original_year+1,_RC)
               else
                  call swap_year(time,original_year,_RC)
               end if
            else
               call swap_year(time,original_year,_RC)
            end if
            call bracket%set_node('R',file=current_file,time_index=time_index,time=time,_RC)
            bracket%new_file_right=.true.
         end if
      end if
      _RETURN(_SUCCESS)
   end subroutine get_file_bracket
Call graph
get_file_bracket calls ESMF_TimeGet, ESMF_TimeIntervalSet, get_time_on_file, mapl_assert, get_file, mapl_return, mapl_verify, swap_year, set_node, swap_node_fields, time_in_bracket, valid_range
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file calls ESMF_TimeGet, mapl_assert, mapl_return, mapl_verify, swap_year, ESMF_TimeIntervalGet, fill_grads_template
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
swap_year calls ESMF_TimeGet, mapl_return, mapl_verify, ESMF_CalendarIsLeapYear, ESMF_TimeSet
fill_grads_template calls ESMF_TimeGet, mapl_assert, mapl_return, mapl_verify, check_token, evaluate_token
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
evaluate_token calls skip_token