get_xy_mask – MAPL
get_xy_mask Subroutine
52 statements
Source File
private subroutine get_xy_mask(grid, xy_subset, xy_mask, rc)
write(6,*) ‘get_xy_mask: j1,j2=’, j1, j2
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(in) :: xy_subset(2,2)
integer, intent(out) :: xy_mask(:,:)
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine get_xy_mask(grid, xy_subset, xy_mask, rc)
    implicit none
    type(ESMF_Grid), intent(in) :: grid
    integer, intent(in)  :: xy_subset(2,2)
    integer, intent(out) :: xy_mask(:,:)
    integer, optional, intent(out) :: rc
    integer :: status
    integer :: ii1, iin, jj1, jjn  ! local box for localDE
    integer :: is, ie, js, je  ! global box for each time-interval
    integer :: j1p, jnp        ! local y-index for each time-interval
    integer :: dimCount
    integer :: y1, y2
    integer :: j, jj
    integer :: j1, j2
    is=xy_subset(1,1); ie=xy_subset(2,1)
    js=xy_subset(1,2); je=xy_subset(2,2)
    call MAPL_GridGetInterior(grid,ii1,iin,jj1,jjn)
    write(6,*) 'MAPL_GridGetInterior, ii1,iin,jj1,jjn', ii1,iin,jj1,jjn
    y1=jj1; y2=jjn
    if (y1 < js) then
       if (y2 < js) then
          j1=-1
          j2=-1
       elseif (y2 < je) then
          j1=js
          j2=y2
       else
          j1=js
          j2=je
       endif
    elseif (y1 <= je) then
       j1=y1
       if (y2 < je) then
          j2=y2
       else
          j2=je
       endif
    else
       j1=-1
       j2=-1
    endif
!!    write(6,*) 'get_xy_mask: j1,j2=', j1, j2
    xy_mask(:,:) = 0
    if (j1 > 0) then
       do jj = j1, j2
          xy_mask(:, jj) = 1
       enddo
    end if
    if(present(rc)) rc=0
  end subroutine get_xy_mask
Call graph
get_xy_mask calls mapl_gridgetinterior
mapl_gridgetinterior calls mapl_gridgetinterior, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_distgridget
mapl_distgridget calls ESMF_DistGridGet, mapl_verify