get_meter – MAPL
get_meter Function
5 statements
Source File
private function get_meter(this) result(meter)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(in), target :: this
Return Value class(AbstractMeter), pointer
Called by
Source Code
   function get_meter(this) result(meter)
      class (AbstractMeter), pointer :: meter
      class (MeterNode), target, intent(in) :: this
      meter => this%meter
   end function get_meter
Call graph
finalize calls get_meter, finalize_global_time_profiler
test_depth_2 calls get_meter
test_get_exclusive calls get_meter
test_get_inclusive calls get_meter
test_node_reset calls get_meter
test_percent_inclusive calls get_meter
test_simple calls get_meter
finalize_global_memory_profiler calls finalize
finalize_global_time_profiler calls finalize
test_accumulate_multi calls finalize
test_accumulate_nested calls finalize
test_accumulate_sub calls finalize
test_simple_report_timer calls finalize
test_simple_report_timer_b calls finalize
test_start_one calls finalize
test_stop_wrong_meter calls finalize
main calls finalize
run calls finalize