get_DateStamp – MAPL
get_DateStamp Subroutine
56 statements
Source File
private subroutine get_DateStamp(clock, DateStamp, offset, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock) :: clock
character(len=ESMF_MAXSTR), optional :: DateStamp
type(ESMF_TimeInterval), optional :: offset
integer, optional :: rc
Calls
Called by
Contents
Source Code
get_DateStamp
Source Code
  subroutine get_DateStamp (clock, DateStamp, offset, rc)
    type (ESMF_Clock)                   :: clock
    character(len=ESMF_MAXSTR),optional :: DateStamp
    type(ESMF_TimeInterval),   optional :: offset
    integer, optional                   :: rc
    type(ESMF_Time)                   :: currentTime
    type(ESMF_Alarm)                  :: PERPETUAL
    character(len=ESMF_MAXSTR)        :: TimeString
    character(len=ESMF_MAXSTR)        :: clockname
    character                         :: String(ESMF_MAXSTR)
    logical                           :: LPERP
    integer                           :: YY,MM,DD,H,M,S
    integer                           :: noffset
    character(len=4) :: year
    character(len=2) :: month
    character(len=2) :: day
    character(len=2) :: hour
    character(len=2) :: minute
    character(len=2) :: second
    integer                    :: STATUS
    equivalence ( string(01),TimeString )
    equivalence ( string(01),year       )
    equivalence ( string(06),month      )
    equivalence ( string(09),day        )
    equivalence ( string(12),hour       )
    equivalence ( string(15),minute     )
    equivalence ( string(18),second     )
    call ESMF_ClockGet ( clock, name=clockname, currTime=currentTime, _RC)
    if (present(offset)) then
        call ESMF_TimeIntervalGet( OFFSET, S=noffset, _RC )
        if( noffset /= 0 ) then
            LPERP = ( index( trim(clockname),'_PERPETUAL' ).ne.0 )
        if( LPERP ) then
            call ESMF_ClockGetAlarm ( clock, AlarmName='PERPETUAL', alarm=PERPETUAL, _RC )
            if( ESMF_AlarmIsRinging(PERPETUAL) ) then
!
! Month has already been set back to PERPETUAL Month, therefore
! Time-Averaged Files (i.e., non-zero offset) need Month to be advanced for proper offset calculation
! ---------------------------------------------------------------------------------------------------
                call ESMF_TimeGet ( CurrentTime, YY = YY, &
                                                 MM = MM, &
                                                 DD = DD, &
                                                 H  = H , &
                                                 M  = M , &
                                                 S  = S, _RC )
                                                 MM = MM + 1
                call ESMF_TimeSet ( CurrentTime, YY = YY, &
                                                 MM = MM, &
                                                 DD = DD, &
                                                 H  = H , &
                                                 M  = M , &
                                                 S  = S, _RC )
#ifdef DEBUG
      if( MAPL_AM_I_ROOT() ) write(6,"(a,2x,i4.4,'/',i2.2,'/',i2.2,2x,'Time: ',i2.2,':',i2.2,':',i2.2)") "Inside HIST GetDate: ",YY,MM,DD,H,M,S
#endif
            endif
        endif
        endif
        currentTime = currentTime - offset
    end if
    call ESMF_TimeGet (currentTime, timeString=TimeString, _RC)
    if(present(DateStamp)) then
       DateStamp = year//month//day//'_'//hour//minute//second //'z'
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine get_DateStamp
Call graph
get_datestamp calls esmf_clockget, esmf_clockgetalarm, esmf_timeintervalget, mapl_verify, esmf_alarmisringing, esmf_timeget, esmf_timeset, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
run calls get_datestamp