get_pressure_levels_r8 – MAPL
get_pressure_levels_r8 Subroutine
31 statements
Source File
private subroutine get_pressure_levels_r8(this, pressure_levels, unusable, reference_pressure, rc)
Type Bound
EtaHybridVerticalCoordinate
Arguments
Type Intent Optional Attributes Name
class(EtaHybridVerticalCoordinate), intent(in) :: this
real(kind=REAL64), intent(out) :: pressure_levels(:)
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=REAL64), intent(in), optional :: reference_pressure
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_pressure_levels_r8(this, pressure_levels, unusable, reference_pressure, rc)
      class(EtaHybridVerticalCoordinate), intent(in) :: this
      real(kind=REAL64), intent(out) :: pressure_levels(:)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      real(kind=REAL64), optional, intent(in) :: reference_pressure
      integer, optional, intent(out) :: rc
      real(kind=REAL64) :: p0
      integer :: k, num_levels
      _UNUSED_DUMMY(unusable)
      num_levels = this%num_levels
      _ASSERT(size(pressure_levels) == num_levels, 'incorrect array size for pressure_levels dummy argument')
      if (present(reference_pressure)) then
         p0 = reference_pressure
      else
         p0 = this%ref_pressure
      end if
      pressure_levels(1) = this%ak(1) + 0.50d0 * dpref_(1,p0)
      do k = 2, num_levels
         pressure_levels(k) = pressure_levels(k-1) + 0.5d0 * (dpref_(k-1, p0) + dpref_(k,p0))
      end do
      Pressure_levels = pressure_levels/100.0d0
   contains
      real(kind=REAL64) function dpref_ (k,pbot)
         integer k
         real(kind=REAL64) pbot
         dpref_   = ( this%ak(k+1) - this%ak(k) ) + &
                    ( this%bk(k+1) - this%bk(k) ) * pbot
      end function dpref_
   end subroutine get_pressure_levels_r8
Call graph
get_pressure_levels_r8 calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_pressure_levels_r4 calls get_pressure_levels
get_pressures_r4_3d calls get_pressure_levels
get_pressures_r8_3d calls get_pressure_levels