get_typekind – MAPL
get_typekind Subroutine
16 statements
Source File
private subroutine get_typekind(x, expected_tks, actual_tk, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_TypeKind_Flag), intent(in) :: expected_tks(:)
type(ESMF_TypeKind_Flag), intent(out) :: actual_tk
integer, intent(out), optional :: rc
Calls
Contents
Source Code
get_typekind
Source Code
   subroutine get_typekind(x, expected_tks, actual_tk, rc)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_TypeKind_Flag), intent(in) :: expected_tks(:)
      type(ESMF_TypeKind_Flag), intent(out) :: actual_tk
      type(ESMF_TypeKind_Flag) :: found_tk
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      do i = 1, size(expected_tks)
         actual_tk = expected_tks(i)
         call ESMF_FieldGet(x, typekind=found_tk, _RC)
         if(actual_tk == found_tk) return
      end do
      _FAIL('Does not match any expected typekind')
   end subroutine get_typekind
Call graph
get_typekind calls esmf_fieldget, mapl_assert, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at