get_attributes – MAPL
get_attributes Function
5 statements
Source File
private function get_attributes(this) result(attributes)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
Return Value type(StringAttributeMap), pointer
Called by
Source Code
   function get_attributes(this) result(attributes)
      class (Variable), target, intent(in) :: this
      type (StringAttributeMap), pointer :: attributes
      attributes => this%attributes
   end function get_attributes
Call graph
get_attributes calls get_attributes
put_var_attributes calls get_attributes
transfer_metadata calls get_attributes
def_variables calls put_var_attributes
merge calls get_attributes
put_attributes calls get_attributes
test_get_attributes calls get_attributes
main calls transfer_metadata
add_variable calls def_variables
write calls def_variables, put_attributes