get_attribute_string – MAPL
get_attribute_string Function
21 statements
Source File
private function get_attribute_string(this, attr_name, rc) result(attr_string)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_attribute_string(this, attr_name, rc) result(attr_string)
      character(len=:), allocatable :: attr_string
      class (Variable), target, intent(in) :: this
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      integer :: status
      type(Attribute), pointer :: attr
      class(*), pointer :: attr_val
      attr => this%get_attribute(attr_name,_RC)
      _ASSERT(associated(attr),"no such attribute "//attr_name)
      attr_val => attr%get_value()
      select type(attr_val)
      type is(character(*))
         attr_string = attr_val
      class default
         _FAIL('unsupported subclass (not string) of attribute named '//attr_name)
      end select
      _RETURN(_SUCCESS)
   end function get_attribute_string
Call graph
get_attribute_string calls mapl_assert, get_attribute, get_value, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_value calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
get_var_attr_string calls get_attribute_string
mapl_create_bundle_from_metdata_id calls get_var_attr_string
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle