get_ESMF_Time_from_NetCDF_DateTime_real – MAPL
get_ESMF_Time_from_NetCDF_DateTime_real Subroutine
34 statements
Source File
private subroutine get_ESMF_Time_from_NetCDF_DateTime_real(duration, units_string, interval, basetime, unusable, time, time_unit, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: duration
character(len=*), intent(in) :: units_string
type(ESMF_TimeInterval), intent(inout) :: interval
type(ESMF_Time), intent(inout) :: basetime
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Time), intent(inout), optional :: time
character(len=:), intent(out), optional, allocatable :: time_unit
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_ESMF_Time_from_NetCDF_DateTime_real(duration, units_string, &
      interval, basetime, unusable, time, time_unit, rc)
      real(kind=ESMF_KIND_R8), intent(in) :: duration
      character(len=*), intent(in) :: units_string
      type(ESMF_TimeInterval), intent(inout) :: interval
      type(ESMF_Time), intent(inout) :: basetime
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Time), optional, intent(inout) :: time
      character(len=:), allocatable, optional, intent(out) :: time_unit
      integer, optional, intent(out) :: rc
      type(CF_Time_Real) :: cft
      type(datetime_duration) :: dt_duration
      character(len=MAX_CHARACTER_LENGTH) :: isostring
      character(len=MAX_CHARACTER_LENGTH) :: tunit_
      integer :: status
      _UNUSED_DUMMY(unusable)
      _ASSERT((len_trim(adjustl(units_string)) > 0), 'units empty')
      cft = CF_Time_Real(duration, units_string)
      call convert_CF_Time_to_datetime_duration(cft, dt_duration, _RC)
      call set_ESMF_TimeInterval(interval, dt_duration, _RC)
      call extract_ISO8601_from_CF_Time(cft, isostring, _RC)
      call set_ESMF_Time_from_ISO8601(basetime, isostring, _RC)
      if(present(time)) time = basetime + interval
      if(present(time_unit)) then
         call extract_CF_Time_unit(cft, tunit_, _RC)
         time_unit = trim(tunit_)
      end if
      _RETURN(_SUCCESS)
   end subroutine get_ESMF_Time_from_NetCDF_DateTime_real
Call graph
get_esmf_time_from_netcdf_datetime_real calls convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, mapl_assert, set_esmf_timeinterval, mapl_return, mapl_verify, set_esmf_time_from_iso8601
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
extract_cf_time_unit calls extract_cf_time_unit_cf_time, extract_cf_time_unit_units
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time, extract_iso8601_from_cf_time_units
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
set_esmf_timeinterval calls set_esmf_timeinterval_from_datetime_duration
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_esmf_time_from_iso8601 calls mapl_return, mapl_verify, ESMF_TimeSet
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf
compute_time_for_current calls time_esmf_to_real, compute_time_for_current