get_level_name – MAPL
get_level_name Function
36 statements
Source File
public function get_level_name(this, rc) result(lev_name)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout), target :: this
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_level_name(this,rc) result(lev_name)
      class (FileMetadataUtils), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      character(len=:), pointer :: units
      character(len=:), allocatable :: lev_name
      type(CoordinateVariable), pointer :: var
      type (StringVariableMap), pointer :: vars
      type (StringVariableMapIterator) :: var_iter
      character(len=:), pointer :: var_name
      vars => this%get_variables()
      var_iter = vars%begin()
      do while(var_iter /=vars%end())
         var_name => var_iter%key()
         var => this%get_coordinate_variable(trim(var_name))
         if (associated(var)) then
            if (index(var_name,'lev') .ne. 0 .or. index(var_name,'height') .ne. 0) then
               lev_name=var_name
               _RETURN(_SUCCESS)
            else
               if (var%is_attribute_present('units')) then
               units => this%get_variable_attribute(var_name,'units')
                  if (trim(units) .eq. 'hPa' .or. trim(units) .eq. 'sigma_level' .or. &
                      trim(units) .eq. 'mb'  .or. trim(units) .eq. 'millibar') then
                     lev_name=var_name
                     _RETURN(_SUCCESS)
                  end if
               end if
            end if
         end if
         call var_iter%next()
      enddo
      lev_name=''
      _RETURN(_SUCCESS)
   end function get_level_name
Call graph
get_level_name calls get_coordinate_variable, get_variable_attribute, get_variables, is_attribute_present, m_begin, m_key, m_next, mapl_return
get_coordinate_variable calls mapl_return, mapl_assert, m_at
get_variable_attribute calls is_attribute_present, mapl_return, mapl_assert, get_attribute, get_file_name, get_value, get_variable, mapl_verify
get_variables calls mapl_return
is_attribute_present calls mapl_return, m_at
m_begin calls s_begin
m_next calls s_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_return, mapl_assert, m_at
get_error_message calls at, insert
get_file_name calls mapl_return
get_value calls mapl_return
get_variable calls mapl_return, m_at
m_at calls m_find
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception
s_begin calls s_next
s_next calls advpos
create_grid calls get_level_name
get_file_levels calls get_level_name
getlevs calls get_level_name
mapl_create_bundle_from_metdata_id calls get_level_name
time_ave calls get_level_name, get_file_levels, mapl_read_bundle
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
initialize_ calls getlevs, create_primary_field
main calls get_file_levels, mapl_read_bundle, process_command_line
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
process_command_line calls create_grid
run_ calls create_bracketing_fields
regrid_util calls main
ut_regridding calls mapl_read_bundle