get_child – MAPL
get_child Function
12 statements
Source File
private function get_child(this, pos, dir) result(child)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in) :: this
integer(kind=SIZE_KIND), intent(in) :: pos
integer, intent(in) :: dir
Return Value integer(kind=SIZE_KIND)
Calls
Called by
Call graph
get_child calls at
ti_at_32 calls ti_at_size_kind
advpos calls get_child
rebalance calls get_child, rot
rot calls get_child
erase_nonleaf calls advpos, rebalance
s_erase_multi calls rebalance, erase_nonleaf, s_next
s_insert calls rebalance
s_next calls advpos
s_prev calls advpos
equalsets calls s_next, s_begin
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_next calls s_next
m_of calls s_insert
m_previous calls s_prev
m_set calls s_insert
s_begin calls s_next
s_deepcopy calls s_insert, s_next, s_begin
s_erase_one calls s_next, erase
equal calls m_next
m_begin calls s_begin
m_deepcopy calls s_deepcopy
m_erase_one calls erase
put_attributes calls m_next
put_var_attributes calls m_next
s_remove calls erase
stringattributemap_serialize calls m_next
transfer_metadata calls m_next