get_header – MAPL
get_header Subroutine
14 statements
Source File
private subroutine get_header(this, header)
Type Bound
MemoryTextColumn
Arguments
Type Intent Optional Attributes Name
class(MemoryTextColumn), intent(in) :: this
character(len=:), intent(out), allocatable :: header(:)
Calls
Source Code
   subroutine get_header(this, header)
      class (MemoryTextColumn), intent(in) :: this
      character(:), allocatable, intent(out) :: header(:)
      integer :: w, n
      integer :: i
      w = this%get_width()
      n = this%get_num_rows_header()
      allocate(character(w) :: header(n))
      do i = 1, size(this%header)
         header(i)(:) = this%header(i)%string
      end do
      call this%get_separator(header(size(this%header)+1), n - size(this%header))
      call this%center(header)
   end subroutine get_header
Call graph
get_header calls center, get_num_rows_header, get_separator, get_width
center calls get_width
get_num_rows_header calls get_num_rows_separator
get_separator calls get_width