get_callbacks – MAPL
get_callbacks Subroutine
30 statements
Source File
public subroutine get_callbacks(state, callbacks, rc)
Uses
mapl_ESMF_Interfaces
mapl_CallbackMap
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(CallbackMap), intent(out), pointer :: callbacks
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine get_callbacks(state, callbacks, rc)
       use mapl_ESMF_Interfaces
       use mapl_CallbackMap
       type(ESMF_State), intent(inout) :: state
       type(CallbackMap), pointer, intent(out) :: callbacks
       integer, optional, intent(out) :: rc
       integer :: status
       integer(kind=ESMF_KIND_I4), allocatable :: valueList(:)
       logical :: isPresent
       type CallbackMapWrapper
          type(CallbackMap), pointer :: map
       end type
       type(CallbackMapWrapper) :: wrapper
       call ESMF_AttributeGet(state, name='MAPL_CALLBACK_MAP', isPresent=isPresent, _RC)
       if (.not. isPresent) then ! create callback map for this state
          allocate(callbacks)
          wrapper%map => callbacks
          valueList = transfer(wrapper, valueList)
          call ESMF_AttributeSet(state, name='MAPL_CALLBACK_MAP', valueList=valueList, _RC)
       end if
       ! Ugly hack to decode ESMF attribute as a gFTL map
       valueList = transfer(wrapper, valueList)
       call ESMF_AttributeGet(state, name='MAPL_CALLBACK_MAP', valueList=valueList, _RC)
       wrapper = transfer(valueList, wrapper)
       callbacks => wrapper%map
       _RETURN(ESMF_SUCCESS)
    end subroutine get_callbacks
Call graph
get_callbacks calls ESMF_AttributeGet, ESMF_AttributeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
copy_callbacks calls get_callbacks
mapl_methodadd calls get_callbacks
make_substates_from_num_grids calls copy_callbacks, make_substates
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates