get_azimuth – MAPL
get_azimuth Function
32 statements
Source File
private function get_azimuth(lt1, ln1, lt2, ln2, wrapon)
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: lt1
real(kind=dp) :: ln1
real(kind=dp) :: lt2
real(kind=dp) :: ln2
logical, intent(in) :: wrapon
Return Value real(kind=dp)
Calls
Called by
Contents
Source Code
get_azimuth
Source Code
REAL(dp) FUNCTION get_azimuth(lt1, ln1, lt2, ln2, wrapon) ! need to be
       ! Computes great circle distance and azimuth
       ! Lat - lon in degrees
       IMPLICIT NONE
       REAL(dp) :: lat1, lat2, lon1, lon2
       REAL(dp) :: lt1, lt2, ln1, ln2
       REAL(dp) :: az, epsilone, saz
       LOGICAL, intent(in) :: wrapon       ! if true then wrap to -180 to 180
       lat1 = deg2rad(lt1)
       lon1 = deg2rad(ln1)
       lat2 = deg2rad(lt2)
       lon2 = deg2rad(ln2)
       ! Inputs LAT1, LON1, LAT2, LON2 are in units of radians.
        az = atan2(cos(lat2) * sin(lon2-lon1), cos(lat1) * sin(lat2)-  &
             sin(lat1) * cos(lat2) * cos(lon2-lon1))
       ! Azimuths are undefined at the poles, so we choose a convention: zero at
       ! the north pole and pi at the south pole.
       associate(pi => MAPL_PI_R8)
          if (lat1 <= -pi/2.0) az = 0.0
          if (lat2 >=  pi/2.0) az = 0.0
          if (lat2 <=  -pi/2.0) az = pi
          if (lat1 >=   pi/2.0) az = pi
          epsilone = 1.74E-8
          if (wrapon) then
              if ( az>-epsilone .AND. az < epsilone) then
                  saz = 0
              else
                  saz = az/abs(az)
              end if
              az = pi*((abs(az)/pi) - 2*ceiling(((abs(az)/pi)-1)/2)) * saz
          end if
          if ( az < -epsilone) then ! change to 0 to 2pi
              az = az + 2*pi
          end if
       end associate
       !  Reset near-zero points
       if (az<0.0) az=0
       get_azimuth = rad2deg(az)
END FUNCTION get_azimuth
Call graph
get_azimuth calls deg2rad, rad2deg
find_sweeppoints calls get_azimuth
orbits_swath calls find_sweeppoints
domasking_ calls orbits_swath
domasking_cs calls orbits_swath
run_ calls domasking_, domasking_cs