get_parameters – MAPL
get_parameters Subroutine
29 statements
Source File
private subroutine get_parameters(this, bracket_side, unusable, field, file, time, time_index, update, rc)
Type Bound
ExtDataBracket
Arguments
Type Intent Optional Attributes Name
class(ExtDataBracket), intent(inout) :: this
character(len=*), intent(in) :: bracket_side
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Field), intent(out), optional :: field
character(len=*), intent(out), optional :: file
type(ESMF_Time), intent(out), optional :: time
integer, intent(out), optional :: time_index
logical, intent(out), optional :: update
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_parameters(this, bracket_side, unusable, field, file, time, time_index, update, rc)
      class(ExtDataBracket), intent(inout) :: this
      character(len=*), intent(in) :: bracket_side
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Field), optional, intent(out) :: field
      character(len=*), optional, intent(out) :: file
      type(ESMF_Time),  optional, intent(out) :: time
      integer,          optional, intent(out) :: time_index
      logical,          optional, intent(out) :: update
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      if (bracket_side == 'L') then
          if (present(field))  field = this%left_node%field
          if (present(file)) file = trim(this%left_node%file)
          if (present(time)) time = this%left_node%time
          if (present(time_index)) time_index = this%left_node%time_index
          if (present(update)) update = this%new_file_left
      else if (bracket_side == 'R') then
          if (present(field))  field = this%right_node%field
          if (present(file)) file = trim(this%right_node%file)
          if (present(time)) time = this%right_node%time
          if (present(time_index)) time_index = this%right_node%time_index
          if (present(update)) update = this%new_file_right
      else
         _FAIL('invalid bracket side!')
      end if
      _RETURN(_SUCCESS)
   end subroutine get_parameters
Call graph
get_parameters calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
create_bracketing_fields calls get_parameters, createfilelevbracket
createfilelevbracket calls get_parameters
iobundle_add_entry calls get_parameters
mapl_extdatagetbracket calls get_parameters
mapl_extdataflipvertical calls mapl_extdatagetbracket
mapl_extdatapopulatebundle calls mapl_extdatagetbracket
mapl_extdataverticalinterpolate calls mapl_extdatagetbracket, mapl_extdataflipvertical
run_ calls create_bracketing_fields, iobundle_add_entry, mapl_extdatapopulatebundle, mapl_extdataverticalinterpolate