get_length – MAPL
get_length Function
4 statements
Source File
private function get_length(this) result(length)
Type Bound
AbstractCollectiveDataMessage
Arguments
Type Intent Optional Attributes Name
class(AbstractCollectiveDataMessage), intent(in) :: this
Return Value integer
Calls
Source Code
   integer function get_length(this) result(length)
      class (AbstractCollectiveDataMessage), intent(in) :: this
      length = &
           & serialize_buffer_length(this%request_id) + &
           & serialize_buffer_length(this%collection_id) + &
           & serialize_buffer_length(this%file_name) + &
           & serialize_buffer_length(this%var_name) + &
           & serialize_buffer_length(this%type_kind) + &
           & serialize_buffer_length(this%start) + &
           & serialize_buffer_length(this%count) + &
           & serialize_buffer_length(this%global_start) + &
           & serialize_buffer_length(this%global_count)
   end function get_length
Call graph
get_length calls serialize_buffer_length
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert