get_num_meters – MAPL
get_num_meters Function
4 statements
Source File
private function get_num_meters(this) result(num_meters)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(in) :: this
Return Value integer
Calls
Called by
Source Code
   integer function get_num_meters(this) result(num_meters)
      class(BaseProfiler), intent(in) :: this
      !$omp master
      num_meters = this%root_node%get_num_nodes()
      !$omp end master
   end function get_num_meters
Call graph
get_num_meters calls get_num_nodes
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
test_accumulate_nested calls get_num_meters
test_accumulate_sub calls get_num_meters
test_start_one calls get_num_meters