get_var_real32_5 – MAPL
get_var_real32_5 Subroutine
28 statements
Source File
private subroutine get_var_real32_5(this, var_name, values, unusable, group_name, start, count, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
real(kind=REAL32), intent(out) :: values(:,:,:,:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: group_name
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Call graph
get_var_real32_5 calls mapl_assert, nf90_get_var, nf90_inq_ncid, nf90_inq_varid, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize