get_subcommunicator – MAPL
get_subcommunicator Function
4 statements
Source File
private function get_subcommunicator(this) result(subcommunicator)
Type Bound
SplitCommunicator
Arguments
Type Intent Optional Attributes Name
class(SplitCommunicator), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_subcommunicator(this) result(subcommunicator)
      class (SplitCommunicator), intent(in) :: this
      subcommunicator = this%subcommunicator
   end function get_subcommunicator
Call graph
create_member_subcommunicator calls get_subcommunicator
initialize calls get_subcommunicator
new_multicommserver calls get_subcommunicator
new_multigroupserver calls get_subcommunicator
run_member calls get_subcommunicator
run calls get_subcommunicator, initialize_io_clients_servers, run_ensemble
main calls get_subcommunicator, create_member_subcommunicator, initialize_ioserver, initialize
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator, initialize_io_clients_servers
run_ensemble calls create_member_subcommunicator, run_member, initialize_io_clients_servers
extdata_driver calls run
time_ave calls initialize
ut_regridding calls initialize
regrid_util calls main
capdriver_main calls run
driver_gethorzijindex calls run