get_spec – MAPL
get_spec Function
5 statements
Source File
private function get_spec(this) result(spec)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(in) :: this
Return Value type(RegridderSpec)
Called by
Source Code
   function get_spec(this) result(spec)
      type (RegridderSpec) :: spec
      class (AbstractRegridder), intent(in) :: this
      spec = this%spec
   end function get_spec
Call graph
copy_global_to_local calls get_spec
create_route_handle calls get_spec
do_regrid calls get_spec, select_route_handle
find_tile_file calls get_spec
get_spec calls get_spec
identity_regridder calls get_spec
initialize_subclass calls get_spec, copy_global_to_local, find_tile_file, create_route_handle
make_regridder_ calls get_spec, identity_regridder
make_regridder_from_grids calls get_spec, identity_regridder
regrid_scalar_2d_real32 calls get_spec, do_regrid
regrid_scalar_2d_real64 calls get_spec, do_regrid
regrid_scalar_3d_real32 calls get_spec, do_regrid
regrid_scalar_3d_real64 calls get_spec, do_regrid
regrid_vector_2d_real32 calls get_spec, do_regrid
regrid_vector_2d_real64 calls get_spec, do_regrid
regrid_vector_3d_real32 calls get_spec, do_regrid
regrid_vector_3d_real64 calls get_spec, do_regrid
select_route_handle calls get_spec, create_route_handle
transpose_regrid_scalar_2d_real32 calls get_spec, do_regrid
transpose_regrid_scalar_3d_real32 calls get_spec, do_regrid
transpose_regrid_vector_2d_real32 calls get_spec, do_regrid
transpose_regrid_vector_3d_real32 calls get_spec, do_regrid