get_row – MAPL
get_row Function
21 statements
Source File
private function get_row(this, node) result(row)
Type Bound
StdDevColumn
Arguments
Type Intent Optional Attributes Name
class(StdDevColumn), intent(in) :: this
class(AbstractMeterNode), intent(in), target :: node
Return Value class(*), allocatable
Calls
Source Code
   function get_row(this, node) result(row)
      class(*), allocatable :: row
      class (StdDevColumn), intent(in) :: this
      class (AbstractMeterNode), target, intent(in) :: node
      class (AbstractMeter), pointer :: tmr
      if (.not. allocated(this%option)) then
         tmr => node%get_meter()
         select type (tmr)
         class is (AdvancedMeter)
            if (this%relative) then
               allocate(row, source=tmr%get_relative_deviation())
            else
               allocate(row, source=tmr%get_standard_deviation())
            end if
         class default
            print*,'error handling here'
         end select
      else
         call this%get_row_dist(node, row)
      end if
   end function get_row
Call graph
get_row calls get_meter, get_relative_deviation, get_standard_deviation, get_row_dist
get_row_dist calls get_meter, get_statistics, fill_row