get_file_name – MAPL
get_file_name Function
8 statements
Source File
public function get_file_name(this, rc) result(fname)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Source Code
   function get_file_name(this,rc) result(fname)
      class (FileMetadataUtils), intent(inout) :: this
      integer, optional, intent(out) :: rc
      character(len=:), allocatable :: fname
      fname = this%fileName
      _RETURN(_SUCCESS)
   end function get_file_name
Call graph
get_file_name calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_coordinate_info calls get_file_name, var_has_attr
get_time_info calls get_file_name, get_coordinate_info
get_var_attr_int32 calls get_file_name
get_var_attr_int64 calls get_file_name
get_var_attr_real32 calls get_file_name
get_var_attr_real64 calls get_file_name
get_var_attr_string calls get_file_name
get_variable_attribute calls get_file_name
getbrackettimeonfile calls get_file_name
getbrackettimeonsinglefile calls get_file_name
var_get_missing_value calls get_file_name, get_var_attr_real32, var_has_attr
var_has_attr calls get_file_name
var_has_missing_value calls get_file_name
detect_metadata calls get_time_info
get_file_levels calls get_coordinate_info
get_file_times calls get_time_info, get_var_attr_int32
get_level_name calls get_variable_attribute
get_time_on_file calls get_time_info
getclimyear calls get_time_info
getlevs calls get_coordinate_info, get_variable_attribute, get_var_attr_real32, get_var_attr_string, var_has_attr
initialize_ calls get_coordinate_info
mapl_create_bundle_from_metdata_id calls get_var_attr_string
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info
run_component_driver calls get_time_info
swap_undef_value calls var_get_missing_value, var_has_missing_value
updatebrackettime calls get_time_info, getbrackettimeonfile, getbrackettimeonsinglefile
time_ave calls get_coordinate_info, var_get_missing_value