get_print_settings – MAPL
get_print_settings Subroutine
19 statements
Source File
private subroutine get_print_settings(config, default_is_present, do_print, print_nondefault_only, rc)
Set do_print & print_nondefault_only based on config and if default is present Print only (do_print) only if printrc is 0 or 1 Print only nondefault values if printrc == 0 and if default is present
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
logical, intent(in) :: default_is_present
logical, intent(out) :: do_print
logical, intent(out) :: print_nondefault_only
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_print_settings(config, default_is_present, do_print, print_nondefault_only, rc)
      type(ESMF_Config), intent(inout) :: config
      logical, intent(in) :: default_is_present
      logical, intent(out) :: do_print
      logical, intent(out) :: print_nondefault_only
      integer, optional, intent(out) :: rc
      integer, parameter :: PRINT_ALL = 1
      integer, parameter :: PRINT_DIFFERENT = 0
      integer :: printrc
      integer :: status
      if (MAPL_AM_I_Root()) then
         call ESMF_ConfigGetAttribute(config, printrc, label = 'PRINTRC:', default = 0, _RC)
         do_print = (printrc == PRINT_ALL) .or. (printrc == PRINT_DIFFERENT)
         print_nondefault_only = (printrc == PRINT_DIFFERENT) .and. default_is_present
      else
         do_print = .FALSE.
      end if
   end subroutine get_print_settings
Call graph
get_print_settings calls ESMF_ConfigGetAttribute, mapl_am_i_root, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_verify calls mapl_throw_exception
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_getresource_config_array calls get_print_settings
mapl_getresource_config_scalar calls get_print_settings
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
test_mapl_getresource_scalar_character calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int8 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_logical calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real8 calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar