get_cptr – MAPL
get_cptr Subroutine
26 statements
Source File
private subroutine get_cptr(x, cptr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(c_ptr), intent(out) :: cptr
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_cptr(x, cptr, rc)
      type(ESMF_Field), intent(inout) :: x
      type(c_ptr), intent(out) :: cptr
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_TypeKind_Flag) :: tk_x
      call ESMF_FieldGet(x, typekind=tk_x, _RC)
      if (tk_x == ESMF_TYPEKIND_R4) then
         call get_cptr_r4(x, cptr, _RC)
      elseif (tk_x == ESMF_TYPEKIND_R8) then
         call get_cptr_r8(x, cptr, _RC)
      elseif (tk_x == ESMF_TYPEKIND_I4) then
         call get_cptr_i4(x, cptr, _RC)
      elseif (tk_x == ESMF_TYPEKIND_I8) then
         call get_cptr_i8(x, cptr, _RC)
      else
         _FAIL('Unsupported typekind in FieldGetCptr().')
      end if
      _RETURN(_SUCCESS)
   end subroutine get_cptr
Call graph
get_cptr calls esmf_fieldget, mapl_assert, get_cptr_i4, get_cptr_i8, get_cptr_r4, get_cptr_r8, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_cptr_i4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_i8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_r4 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
get_cptr_r8 calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
assign_fptr_r4_rank1 calls fieldgetcptr
assign_fptr_r4_rank2 calls fieldgetcptr
assign_fptr_r8_rank1 calls fieldgetcptr
assign_fptr_r8_rank2 calls fieldgetcptr
copy calls fieldgetcptr
copy_broadcast calls fieldgetcptr, copy
test_fieldgetcptr calls fieldgetcptr
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldcopy calls copy
fieldcopybroadcast calls copy_broadcast