get_ith_dimension – MAPL
get_ith_dimension Function
20 statements
Source File
private function get_ith_dimension(this, i, unusable, rc) result(dimension_name)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
integer, intent(in) :: i
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value character(len=:), pointer
Calls
Called by
Source Code
   function get_ith_dimension(this, i, unusable, rc) result(dimension_name)
      character(len=:), pointer :: dimension_name
      class (Variable), target, intent(in) :: this
      integer, intent(in) :: i
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      if (i <= 0 .or. i > this%dimensions%size()) then
         dimension_name => null()
         _RETURN(pFIO_ILLEGAL_DIMENSION_INDEX)
      else
         dimension_name => this%dimensions%at(i)
         _RETURN(_SUCCESS)
      end if
      _UNUSED_DUMMY(unusable)
   end function get_ith_dimension
Call graph
get_ith_dimension calls at, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_coordinate_info calls get_ith_dimension
test_get_ith_dimension calls get_ith_dimension
get_file_levels calls get_coordinate_info
get_time_info calls get_coordinate_info
getlevs calls get_coordinate_info
initialize_ calls get_coordinate_info, getlevs, getclimyear, create_primary_field
time_ave calls get_coordinate_info, get_file_levels, get_file_times, mapl_read_bundle
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
detect_metadata calls get_time_info
get_file_times calls get_time_info
get_time_on_file calls get_time_info
getclimyear calls get_time_info
main calls get_file_levels, get_file_times, mapl_read_bundle, run_component_driver
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info
run_component_driver calls get_time_info
updatebrackettime calls get_time_info
fillin_primary calls detect_metadata
get_file_bracket calls get_time_on_file
run_ calls mapl_extdatagetfstarttime, updatebrackettime, create_bracketing_fields
regrid_util calls main
ut_regridding calls mapl_read_bundle