get_acc_offset – MAPL
get_acc_offset Function
27 statements
Source File
private function get_acc_offset(current_time, ref_time, rc) result(acc_offset)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: current_time
integer, intent(in) :: ref_time
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Call graph
get_acc_offset calls ESMF_TimeGet, ESMF_TimeIntervalGet, ESMF_TimeSet, mapl_unpacktime, mapl_return, mapl_verify
mapl_unpacktime calls mapl_unpacktime
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize calls get_acc_offset