get_var_from_name_w_group – MAPL
get_var_from_name_w_group Subroutine
52 statements
Source File
public subroutine get_var_from_name_w_group(var_name, var2d, filename, rc)
print, ‘no grp name’ write(6,) ‘ncid, short_name, varid’, ncid, trim(short_name), varid
Arguments
Type Intent Optional Attributes Name
character(len=ESMF_MAXSTR), intent(in) :: var_name
real(kind=ESMF_KIND_R8), intent(inout) :: var2d(:,:)
character(len=ESMF_MAXSTR), intent(in) :: filename
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine get_var_from_name_w_group (var_name, var2d, filename, rc)
    character(len=ESMF_MAXSTR), intent(in) :: var_name, filename
    real(ESMF_KIND_R8), intent(inout) :: var2d(:,:)
    integer, optional, intent(out) :: rc
    integer :: i, j
    character(len=ESMF_MAXSTR) :: grp1, grp2
    character(len=ESMF_MAXSTR) :: short_name
    integer :: ncid, ncid1, ncid2, ncid_final, varid
    logical :: found_group
    integer :: status
    i=index(var_name, '/')
    if (i>0) then
       found_group = .true.
       grp1 = var_name(1:i-1)
       j=index(var_name(i+1:), '/')
       if (j>0) then
          grp2=var_name(i+1:i+j-1)
          short_name=var_name(i+j+1:)
       else
          grp2=''
          short_name=var_name(i+1:)
       endif
       i=i+j
    else
       found_group = .false.
       grp1 = ''
       grp2=''
       short_name=var_name
    endif
    ! ncid
    ! ncid1:  grp1
    ! ncid2:  grp2
    !
    call check_nc_status(nf90_open(filename, NF90_NOWRITE, ncid), _RC)
    ncid_final = ncid
    if ( found_group ) then
       call check_nc_status(nf90_inq_ncid(ncid, grp1, ncid1), _RC)
       ncid_final = ncid1
       if (j>0) then
          call check_nc_status(nf90_inq_ncid(ncid1, grp2, ncid2), _RC)
          ncid_final = ncid2
       endif
    else
!!       print*, 'no grp name'
    endif
    call check_nc_status(nf90_inq_varid(ncid_final, short_name, varid), _RC)
!!    write(6,*) 'ncid, short_name, varid', ncid, trim(short_name), varid
    call check_nc_status(nf90_get_var(ncid_final, varid, var2d), _RC)
    call check_nc_status(nf90_close(ncid), _RC)
    _RETURN(_SUCCESS)
  end subroutine get_var_from_name_w_group
Call graph
get_var_from_name_w_group calls nf90_close, nf90_get_var, nf90_inq_ncid, nf90_inq_varid, nf90_open, check_nc_status, mapl_return, mapl_verify
check_nc_status calls mapl_return, mapl_assert, nf90_strerror
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
read_m_files_4_swath calls get_var_from_name_w_group
add_horz_coordinates_from_file calls read_m_files_4_swath
get_obs_time calls read_m_files_4_swath
initialize_from_config_with_prefix calls read_m_files_4_swath
make_new_grid calls add_horz_coordinates_from_file