get_logger – MAPL
get_logger Function
7 statements
Source File
private function get_logger(this) result(lgr)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(in) :: this
Return Value class(Logger), pointer
Calls
Called by
Source Code
   function get_logger(this) result(lgr)
      class(Logger), pointer :: lgr
      class(MaplGenericComponent), intent(in) :: this
      class(AbstractComponent), pointer :: component
      component => this%get_component()
      lgr => component%get_logger()
   end function get_logger
Call graph
get_logger calls get_logger, get_component
mapl_getlogger_gc calls get_logger
mapl_getlogger_meta calls get_logger
mapl_getlogger calls mapl_getlogger_gc, mapl_getlogger_meta
initialize_gc calls mapl_getlogger, mapl_clockinit, perpetual_clock
initialize_ calls mapl_getlogger
mapl_clockinit calls mapl_getlogger
perpetual_clock calls mapl_getlogger
warn_empty calls mapl_getlogger
mapl_esmfstatereadfromfile calls warn_empty
mapl_esmfstatewritetofile calls warn_empty
step calls perpetual_clock