get_time_on_file – MAPL
get_time_on_file Subroutine
76 statements
Source File
private subroutine get_time_on_file(this, filename, target_time, bracketside, time_index, output_time, unusable, wrap, rc)
Type Bound
ExtDataAbstractFileHandler
Arguments
Type Intent Optional Attributes Name
class(ExtDataAbstractFileHandler), intent(inout) :: this
character(len=*), intent(inout) :: filename
type(ESMF_Time), intent(in) :: target_time
character(len=*), intent(in) :: bracketside
integer, intent(out) :: time_index
type(ESMF_Time), intent(out) :: output_time
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(inout), optional :: wrap
integer, intent(out), optional :: rc
Calls
Contents
Source Code
get_time_on_file
Source Code
   subroutine get_time_on_file(this,filename,target_time,bracketside,time_index,output_time,unusable,wrap,rc)
      class(ExtdataAbstractFileHandler), intent(inout) :: this
      character(len=*), intent(inout) :: filename
      type(ESMF_Time), intent(in) :: target_time
      character(len=*), intent(in) :: bracketside
      integer, intent(Out) :: time_index
      type(ESMF_Time), intent(out) :: output_time
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(inout) :: wrap
      integer, optional, intent(out) :: rc
      integer :: status
      type(FileMetadataUtils), pointer :: file_metadata
      type(ESMF_Time), allocatable :: time_series(:)
      logical :: in_bounds, found_time, wrap_
      integer :: i,num_times
      _UNUSED_DUMMY(unusable)
      if (present(wrap)) then
         wrap_= .true.
      else
         wrap_=.false.
      end if
      time_index=time_not_found
      if (trim(filename) == file_not_found) then
         _RETURN(_SUCCESS)
      end if
      call this%make_metadata(filename,file_metadata,_RC)
      call file_metadata%get_time_info(timeVector=time_series,_RC)
      num_times = size(time_series)
      found_time = .false.
      if (bracketside == 'L') then
         in_bounds = .not.(target_time < time_series(1))
         if (in_bounds) then
            do i=num_times,1,-1
               if (target_time >= time_series(i)) then
                  output_time = time_series(i)
                  time_index = i
                  found_time = .true.
                  exit
               end if
            enddo
         else
            if (wrap_) then
               output_time=time_series(num_times)
               time_index = num_times
               found_time = .true.
               wrap = -1
            end if
         end if
      else if (bracketside == 'R') then
         in_bounds = .not.(target_time >= time_series(num_times))
         if (in_bounds) then
            do i=1,num_times
               if (target_time < time_series(i)) then
                  output_time = time_series(i)
                  time_index = i
                  found_time = .true.
                  exit
               end if
            enddo
         else
            if (wrap_) then
               output_time=time_series(1)
               time_index = 1
               found_time = .true.
               wrap = 1
            end if
         end if
      else
         _FAIL("unknown bracket side")
      end if
      _RETURN(_SUCCESS)
   end subroutine get_time_on_file
Call graph
get_time_on_file calls mapl_assert, get_time_info, make_metadata, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_time_info calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, get_coordinate_info, get_file_name
make_metadata calls mapl_return, at, find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_coordinate_info calls mapl_assert, mapl_return, mapl_verify, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, get_file_name, get_dimension, get_ith_dimension, var_has_attr
get_error_message calls at
get_file_name calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
var_has_attr calls mapl_assert, mapl_return, mapl_verify, get_file_name, get_variable, is_attribute_present