get_DataReference – MAPL
get_DataReference Function
9 statements
Source File
private function get_DataReference(this, ith) result(DataRef)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(in), target :: this
integer, intent(in), optional :: ith
Return Value class(AbstractDataReference), pointer
Calls
Called by
Source Code
   function get_DataReference(this, ith) result(DataRef)
      class (AbstractServer),target, intent(in) :: this
      integer,optional, intent(in) :: ith
      class(AbstractDataReference),pointer :: DataRef
      integer :: i
      i=1
      if(present(ith)) i = ith
      DataRef => this%dataRefPtrs%at(i)
   end function get_DataReference
Call graph
get_datareference calls at
v_at_32 calls v_at_size_kind
get_datafrommem calls get_datareference, get_datafrommem
put_datatofile calls get_datareference
receive_output_data calls get_datareference, receive_output_data
start calls put_datatofile, receive_output_data