get_var_real64_4 – MAPL
get_var_real64_4 Subroutine
28 statements
Source File
private subroutine get_var_real64_4(this, var_name, values, unusable, group_name, start, count, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
real(kind=REAL64), intent(out) :: values(:,:,:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: group_name
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Called by
Call graph
get_var_real64_4 calls mapl_assert, nf90_get_var, nf90_inq_ncid, nf90_inq_varid, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fillstate calls get_var
get_coordinate_bounds calls get_var
get_datafromfile calls get_var
inq_variables calls get_var
mapl_readtilingnc4 calls get_var
mapl_varreadncpar_r4_1d calls get_var
mapl_varreadncpar_r4_2d calls get_var
mapl_varreadncpar_r8_1d calls get_var
mapl_varreadncpar_r8_2d calls get_var
new_verticalcoordinate calls get_var
run_component_driver calls get_var
write_data calls get_var
main calls get_var, run_component_driver, write_data
mapl_varread calls mapl_varreadncpar_r4_1d, mapl_varreadncpar_r4_2d, mapl_varreadncpar_r8_1d, mapl_varreadncpar_r8_2d
verticalcoordinate calls new_verticalcoordinate
handle_done_prefetch calls get_datafromfile
initialize_ calls fillstate
initialize_from_file_metadata calls get_coordinate_bounds
mapl_locstreamcreatefromfile calls mapl_readtilingnc4
read calls inq_variables
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile
run_ calls fillstate