get_var_int64_0 – MAPL
get_var_int64_0 Subroutine
23 statements
Source File
private subroutine get_var_int64_0(this, var_name, values, unusable, group_name, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
integer(kind=INT64), intent(out) :: values
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: group_name
integer, intent(out), optional :: rc
Calls
Contents
Call graph
get_var_int64_0 calls mapl_assert, nf90_get_var, nf90_inq_ncid, nf90_inq_varid, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize