get_grid – MAPL
get_grid Function
11 statements
Source File
public function get_grid(this) result(grid)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(in), target :: this
Return Value type(MaplGrid), pointer
Calls
Called by
Contents
Source Code
get_grid
Source Code
   function get_grid(this) result(grid)
     class(MaplGenericComponent), target, intent(in) :: this
     type(MaplGrid), pointer :: grid
     integer :: thread
     if (.NOT. this%is_threading_active()) then
        grid => this%grid
     else
        thread = get_current_thread()
        grid => this%subcomponents(thread+1)%grid ! subgrids is of type ESMF_Grid because of the return type of make_subgrids
     end if
   end function get_grid
Call graph
get_grid calls get_current_thread, is_threading_active, subcomponents
mapl_genericstateget calls get_grid
mapl_get calls mapl_genericstateget
mapl_readforcingx calls mapl_genericstateget
initialize_gc calls mapl_get
initialize_ calls mapl_get
mapl_donotallocateimport calls mapl_get
mapl_donotallocateinternal calls mapl_get
mapl_internalesmfstateget calls mapl_get, mapl_internalesmfstateget
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run_ calls mapl_get
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
get_field_from_internal calls mapl_internalesmfstateget