get_ith_child – MAPL
get_ith_child Function
11 statements
Source File
private function get_ith_child(this, i) result(child)
Type Bound
MAPL_MetaComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_MetaComp), intent(in), target :: this
integer, intent(in) :: i
Return Value class(MaplGenericComponent), pointer
Calls
Called by
Source Code
   function get_ith_child(this, i) result(child)
      class(MaplGenericComponent), pointer :: child
      class(MAPL_MetaComp), target, intent(in) :: this
      integer, intent(in) :: i
      class(AbstractFrameworkComponent), pointer :: child_node
      child_node => this%get_child(trim(this%GCnamelist(i)))
      select type (child_node)
         class is (MaplGenericComponent)
         child => child_node
      end select
   end function get_ith_child
Call graph
get_ith_child calls get_child
get_child_by_index calls get_component, get_child
get_child_by_name calls get_component, get_child
get_child_export_state calls get_ith_child
get_child_gridcomp calls get_ith_child
get_child_import_state calls get_ith_child
get_child_internal_state calls get_ith_child