get_error_message – MAPL
get_error_message Function
29 statements
Source File
private function get_error_message(error_code) result(description)
Uses
gFTL_IntegerStringMap
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: error_code
Return Value character(len=:), allocatable
Calls
Called by
Source Code
  function get_error_message(error_code) result(description)
     use gFTL_IntegerStringMap
     character(:), allocatable :: description
     integer, intent(in) :: error_code
     type(IntegerStringMap), save :: error_messages
     logical, save :: initialized = .false.
     call initialize_err()
     if (error_messages%count(error_code) > 0) then
        description = error_messages%at(error_code)
     else
        description = error_messages%at(MAPL_UNKNOWN_ERROR)
     end if
  contains
     subroutine initialize_err()
        if (.not. initialized) then
           initialized = .true.
           call error_messages%insert(MAPL_UNKNOWN_ERROR, 'unknown error')
           call error_messages%insert(MAPL_SUCCESS, 'success')
           call error_messages%insert(MAPL_NO_SUCH_PROPERTY, 'no such property')
           call error_messages%insert(MAPL_NO_SUCH_VARIABLE, 'no such variable')
           call error_messages%insert(MAPL_TYPE_MISMATCH,    'passed argument does not match expected type')
           call error_messages%insert(MAPL_UNSUPPORTED_TYPE, 'provided data type is not supported by this subclass')
           call error_messages%insert(MAPL_VALUE_NOT_SUPPORTED, 'provided value is not supported by this subclass')
           call error_messages%insert(MAPL_NO_DEFAULT_VALUE, 'no default value has been provided for this property')
           call error_messages%insert(MAPL_DUPLICATE_KEY, 'map container already has the specified key')
           call error_messages%insert(MAPL_STRING_TOO_SHORT, 'fixed length string is not long enough to contain requested data')
        end if
     end subroutine initialize_err
  end function get_error_message
Call graph
get_error_message calls at, insert
mapl_assert_return_code calls get_error_message
mapl_return calls get_error_message