get_MetaComp_from_gc – MAPL
get_MetaComp_from_gc Function
8 statements
Source File
private function get_MetaComp_from_gc(gc) result(meta_comp)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
Return Value type(MAPL_MetaComp), pointer
Calls
Called by
Contents
Source Code
get_MetaComp_from_gc
Source Code
  function get_MetaComp_from_gc(gc) result(meta_comp)
    type(ESMF_GridComp), intent(inout) :: gc
    type(MAPL_MetaComp), pointer :: meta_comp
    type(MAPL_MetaComp_Wrapper) :: meta_comp_wrapper
    integer :: rc
    call ESMF_UserCompGetInternalState(gc, internal_meta_comp_name, meta_comp_wrapper, rc)
    meta_comp => meta_comp_wrapper%ptr
  end function get_MetaComp_from_gc
Call graph
get_metacomp_from_gc calls esmf_usercompgetinternalstate
finalize_gc calls get_metacomp_from_gc
run_multipletimes calls get_metacomp_from_gc
initialize_gc calls get_metacomp_from_gc
run_gc calls run_multipletimes