get_fake_longitudes – MAPL
get_fake_longitudes Function
56 statements
Source File
private function get_fake_longitudes(this, unusable, rc) result(longitudes)
Uses
MAPL_BaseMod
mpi
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Source Code
   function get_fake_longitudes(this, unusable, rc) result(longitudes)
      use mpi
      use MAPL_BaseMod, only: MAPL_Grid_Interior
      real (kind=REAL64), allocatable :: longitudes(:)
      class (CubedSphereGridFactory), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (ESMF_Grid) :: grid
      real (kind=ESMF_KIND_R8), pointer :: centers(:,:)
      real (kind=REAL64), allocatable :: piece(:)
      integer :: n_loc
      integer, allocatable :: counts(:), displs(:)
      type (ESMF_VM) :: vm
      integer :: ierror
      integer :: npes, p, pet
      integer :: comm_grid
      integer :: i_1, i_n, j_1, j_n
      integer :: j_mid
      integer :: tile
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'get_fake_longitudes()'
      _UNUSED_DUMMY(unusable)
      grid = this%make_grid()
      call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=centers, rc=status)
      _VERIFY(status)
      call ESMF_VMGetCurrent(vm, rc=status)
      _VERIFY(status)
      call ESMF_VMGet(vm, mpiCommunicator=comm_grid, petcount=npes, localpet=pet, rc=status)
      _VERIFY(status)
      call MAPL_grid_interior(grid, i_1, i_n, j_1, j_n)
      j_mid = 1 + this%im_world/2
      tile = 1 + (j_1-1)/this%im_world
      if (tile == 1 .and. (j_1 <= j_mid) .and. (j_mid <= j_n)) then
         allocate(piece(i_1:i_n))
         piece(:) = centers(:,j_mid-(j_1-1))
         n_loc = (i_n - i_1 + 1)
      else
         allocate(piece(1)) ! MPI does not like 0-sized arrays.
         piece(1) = 0
         n_loc = 0
      end if
      allocate(counts(0:npes-1), displs(0:npes-1))
      call MPI_Allgather(n_loc, 1, MPI_INTEGER, counts, 1, MPI_INTEGER, comm_grid, ierror)
      _VERIFY(ierror)
      displs(0) = 0
      do p = 1, npes-1
         displs(p) = displs(p-1) + counts(p-1)
      end do
      allocate(longitudes(this%im_world))
      call MPI_Allgatherv(piece, n_loc, MPI_REAL8, longitudes, counts, displs, MPI_REAL8, comm_grid, ierror)
      _VERIFY(ierror)
      longitudes = longitudes * MAPL_RADIANS_TO_DEGREES
   end function get_fake_longitudes
Call graph
get_fake_longitudes calls ESMF_GridGetCoord, ESMF_VMGet, ESMF_VMGetCurrent, mapl_grid_interior, mpi_allgather, mpi_allgatherv, make_grid, mapl_verify
mapl_grid_interior calls mapl_grid_interior, mapl_verify, mapl_return, ESMF_AttributeGet, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget
make_grid calls mapl_verify, make_new_grid, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
append_metadata calls get_fake_longitudes