get_header – MAPL
get_header Subroutine
43 statements
Source File
private recursive subroutine get_header(this, header)
Type Bound
MultiColumn
Arguments
Type Intent Optional Attributes Name
class(MultiColumn), intent(in) :: this
character(len=:), intent(out), allocatable :: header(:)
Calls
Called by
Source Code
   recursive subroutine get_header(this, header)
      class (MultiColumn), intent(in) :: this
      character(:), allocatable, intent(out) :: header(:)
      integer :: i, column_width, column_height
      integer :: w, w0, w1, h, h0, h1, h2
      integer :: total_width, total_height, shared_height
      class(TextColumn), pointer :: c
      character(:), allocatable :: column_header(:)
      integer :: n_shared
      total_width = this%get_width()
      total_height = this%num_rows_header
      n_shared = size(this%shared_header)
      shared_height = n_shared + this%get_num_rows_separator()
      allocate(character(total_width) :: header(total_height))
      header(1:n_shared) = this%shared_header
      call this%center(header(1:n_shared))
      call this%get_separator(header(n_shared+1), shared_height - n_shared)
      c => this%columns%at(1)
      column_height = c%get_num_rows_header()
      column_width = c%get_width()
      header(shared_height+1:total_height-column_height) = repeat(' ', column_width)
      call c%get_header(column_header)
      do h = 1, column_height
         h0 = total_height - column_height + h
         header(h0) = column_header(h)
      end do
      deallocate(column_header)
      w0 = 1
      do i = 1, this%columns%size()
         c => this%columns%at(i)
         column_height = c%get_num_rows_header()
         w = c%get_width()
         w1 = w0 + w - 1
         h0 = shared_height + 1
         h1 = total_height-column_height+1
         h2 = total_height
         header(h0:h1-1)(w0:w1) = repeat(' ',w)
         call c%get_header(column_header)
         header(h1:h2)(w0:w1) = column_header
         w0 = w1 + 1 ! space
         deallocate(column_header)
      end do
   end subroutine get_header
Call graph
get_header calls get_header, get_num_rows_header, at, center, get_num_rows_separator, get_separator, get_width
center calls get_width
get_separator calls get_width
v_at_32 calls v_at_size_kind
generate_report_profiler calls get_header
generate_report calls generate_report
mapl_genericfinalize calls generate_report
report_global_profiler calls generate_report
report_profile calls generate_report
test_simple_report_timer calls generate_report
test_simple_report_timer_b calls generate_report
main calls generate_report
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report