get_variable_attribute – MAPL
get_variable_attribute Function
32 statements
Source File
public function get_variable_attribute(this, var_name, attr_name, rc) result(units)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value character(len=:), pointer
Calls
Called by
Source Code
   function get_variable_attribute(this,var_name,attr_name,rc) result(units)
      class (FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      character(:), allocatable :: fname
      character(len=:), pointer :: units
      type(Attribute), pointer :: attr => null()
      class(Variable), pointer :: var => null()
      class(*), pointer :: vunits
      logical :: isPresent
      integer :: status
      fname = this%get_file_name(_RC)
      var => this%get_variable(var_name,rc=status)
      _VERIFY(status)
      isPresent = var%is_attribute_present(trim(attr_name))
      if (isPresent) then
         attr => var%get_attribute(trim(attr_name))
         vunits => attr%get_value()
         select type(vunits)
         type is (character(*))
            units => vunits
         class default
            _FAIL('units must be string for '//var_name//' in '//fname)
         end select
      else
         units => null()
      end if
      _RETURN(_SUCCESS)
   end function get_variable_attribute
Call graph
get_variable_attribute calls mapl_assert, get_attribute, get_file_name, get_value, get_variable, is_attribute_present, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, m_at
get_file_name calls mapl_return
get_value calls mapl_return
get_variable calls mapl_return, m_at
is_attribute_present calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
get_level_name calls get_variable_attribute
getlevs calls get_variable_attribute, get_level_name
create_bracketing_fields calls getlevs
create_grid calls get_level_name
create_primary_field calls getlevs
get_file_levels calls get_level_name
initialize_ calls getlevs, create_primary_field
mapl_create_bundle_from_metdata_id calls get_level_name
time_ave calls get_level_name, get_file_levels, mapl_read_bundle
main calls get_file_levels, mapl_read_bundle, process_command_line
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
process_command_line calls create_grid
run_ calls create_bracketing_fields
regrid_util calls main
ut_regridding calls mapl_read_bundle