get_width – MAPL
get_width Function
4 statements
Source File
private function get_width(this) result(column_width)
Type Bound
TextColumn
Arguments
Type Intent Optional Attributes Name
class(TextColumn), intent(in) :: this
Return Value integer
Called by
Source Code
   integer function get_width(this) result(column_width)
      class (TextColumn), intent(in) :: this
      column_width = this%column_width
   end function get_width
Call graph
add_column calls get_width
center calls get_width
generate_report_profiler calls get_width, get_header, get_rows
get_header calls get_width, center, get_separator
get_rows_range calls get_width
get_rows calls get_width, get_rows_range
get_row calls get_width
get_separator calls get_width
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_one_timer calls get_header, get_row
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column