get_eta_r8 – MAPL
get_eta_r8 Subroutine
31 statements
Source File
private subroutine get_eta_r8(this, ptop, pint, ak, bk, unusable, rc)
Type Bound
EtaHybridVerticalCoordinate
Arguments
Type Intent Optional Attributes Name
class(EtaHybridVerticalCoordinate), intent(in) :: this
real(kind=REAL64), intent(out) :: ptop
real(kind=REAL64), intent(out) :: pint
real(kind=REAL64), intent(out) :: ak(:)
real(kind=REAL64), intent(out) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_eta_r8(this, ptop, pint, ak, bk, unusable,rc)
      class(EtaHybridVerticalCoordinate), intent(in) :: this
      real(kind=REAL64), intent(out) :: ak(:)
      real(kind=REAL64), intent(out) :: bk(:)
      real(kind=REAL64), intent(out) :: ptop ! model top (Pa)
      real(kind=REAL64), intent(out) :: pint ! transition to p (Pa)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: num_levels, k, ks
      _UNUSED_DUMMY(unusable)
     _ASSERT(this%num_levels == size(ak) - 1 ,"size vertical grid should be consistent")
     ak = this%ak
     bk = this%bk
     do k = 1, num_levels+1
        if (num_levels == 1) then
           ks = 1
           exit
        endif
        if ( bk(k) > 0.0d0) then
           ks = k -2
           exit
        endif
     enddo
     ptop = this%ak(1)
     pint = this%ak(ks+1)
     _RETURN(_SUCCESS)
   end subroutine get_eta_r8
Call graph
get_eta_r8 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_eta_onestep_r4 calls get_eta
get_eta_onestep_r8 calls get_eta
get_eta_r4 calls get_eta
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8