get_global_options – MAPL
get_global_options Subroutine
23 statements
Source File
private subroutine get_global_options(yaml_file, am_running, use_file_weights, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: yaml_file
logical, intent(out) :: am_running
logical, intent(out) :: use_file_weights
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine get_global_options(yaml_file,am_running,use_file_weights,rc)
     character(len=*), intent(in) :: yaml_file
     logical,intent(out) :: am_running
     logical,intent(out) :: use_file_weights
     integer, intent(out), optional :: rc
     type(ESMF_HConfig), allocatable :: config
     integer :: status
     am_running=.true.
     use_file_weights=.false.
     config = ESMF_HConfigCreate(filename = trim(yaml_file),_RC)
     if (ESMF_HConfigIsDefined(config,keyString="USE_EXTDATA")) then
        am_running  = ESMF_HConfigAsLogical(config,keyString="USE_EXTDATA",_RC)
     end if
     if (ESMF_HConfigIsDefined(config,keyString="file_weights")) then
        use_file_weights  = ESMF_HConfigAsLogical(config,keyString="file_weights",_RC)
     end if
     call ESMF_HConfigDestroy(config)
     _RETURN(_SUCCESS)
  end subroutine get_global_options
Call graph
get_global_options calls ESMF_HConfigCreate, ESMF_HConfigDestroy, esmf_hconfigaslogical, esmf_hconfigisdefined, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_ calls get_global_options