get_cap_from_gc – MAPL
get_cap_from_gc Function
11 statements
Source File
private function get_cap_from_gc(gc, rc) result(cap)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
integer, intent(out) :: rc
Return Value type(MAPL_Cap), pointer
Calls
Called by
Source Code
    function get_cap_from_gc(gc, rc) result(cap)
        type(ESMF_GridComp), intent(inout) :: gc
        integer,             intent(  out) :: rc
        type(MAPL_Cap), pointer :: cap
        type(Cap_Wrapper)       :: wrapped_cap
        call ESMF_UserCompGetInternalState(gc, "MAPL_Cap", wrapped_cap, rc)
        VERIFY_NUOPC_(rc)
        cap => wrapped_cap%ptr
        _RETURN(_SUCCESS)
    end function get_cap_from_gc
Call graph
get_cap_from_gc calls ESMF_LogFoundError, ESMF_UserCompGetInternalState, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
advertise_fields calls get_cap_from_gc
model_advance calls get_cap_from_gc
model_finalize calls get_cap_from_gc
realize_fields calls get_cap_from_gc
set_clock calls get_cap_from_gc