get_vec_from_config – MAPL
get_vec_from_config Function
20 statements
Source File
private function get_vec_from_config(config, key) result(vec)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: key
Return Value type(StringVector)
Calls
Called by
Contents
Source Code
get_vec_from_config
Source Code
  function get_vec_from_config(config, key) result(vec)
    type(ESMF_Config), intent(inout) :: config
    character(len=*), intent(in) :: key
    logical :: present
    integer :: status, rc
    character(len=ESMF_MAXSTR) :: cap_import
    type(StringVector) :: vec
    call ESMF_ConfigFindLabel(config, key//":", isPresent = present, rc = status)
    _VERIFY(status)
    cap_import = ""
    if (present) then
       do while(trim(cap_import) /= "::")
          call ESMF_ConfigNextLine(config, rc = status)
          _VERIFY(status)
          call ESMF_ConfigGetAttribute(config, cap_import, rc = status)
          _VERIFY(status)
          if (trim(cap_import) /= "::") call vec%push_back(trim(cap_import))
       end do
    end if
  end function get_vec_from_config
Call graph
get_vec_from_config calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine, mapl_verify, push_back
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
initialize_extdata calls get_vec_from_config
initialize_gc calls initialize_extdata