get_DataFromFile – MAPL
get_DataFromFile Subroutine
77 statements
Source File
private subroutine get_DataFromFile(this, message, address, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout) :: this
class(AbstractDataMessage), intent(in) :: message
type(c_ptr), intent(in) :: address
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine get_DataFromFile(this,message,address, rc)
      class (ServerThread), intent(inout)    :: this
      class (AbstractDataMessage), intent(in) ::  message
      type (c_ptr), intent(in) :: address
      integer, optional, intent(out) :: rc
      type (NetCDF4_FileFormatter), pointer :: formatter
      integer(kind=INT32), pointer :: values_int32_0d
      integer(kind=INT32), pointer :: values_int32_1d(:)
      real(kind=REAL32), pointer :: values_real32_0d
      real(kind=REAL32), pointer :: values_real32_1d(:)
      integer(kind=INT64), pointer :: values_int64_0d
      integer(kind=INT64), pointer :: values_int64_1d(:)
      real(kind=REAL64), pointer :: values_real64_0d
      real(kind=REAL64), pointer :: values_real64_1d(:)
      type (ExtDataCollection), pointer :: collection
      integer, allocatable :: start(:),count(:)
      integer :: status
      collection => this%ext_collections%at(message%collection_id)
      formatter => collection%find(message%file_name, _RC)
      select type (message)
      type is (PrefetchDataMessage)
        start = message%start
        count = message%count
      type is (CollectivePrefetchDataMessage)
        start = message%global_start
        count = message%global_count
      class default
        _FAIL( "wrong PrefetchDataMessage type")
      end select
!      if (product(count) /= product(file_data_reference%shape)) stop "memory size not match"
      select case (size(count)) ! rank
      case (0)
          select case (message%type_kind)
          case (pFIO_INT32)
              call c_f_pointer(address, values_int32_0d)
              call formatter%get_var(message%var_name, values_int32_0d, _RC)
          case (pFIO_REAL32)
              call c_f_pointer(address, values_real32_0d)
              call formatter%get_var(message%var_name, values_real32_0d, _RC)
          case (pFIO_INT64)
              call c_f_pointer(address, values_int64_0d)
              call formatter%get_var(message%var_name, values_int64_0d, _RC)
          case (pFIO_REAL64)
              call c_f_pointer(address, values_real64_0d)
              call formatter%get_var(message%var_name, values_real64_0d, _RC)
          case default
              _FAIL( "Not supported type")
          end select
      case (1:)
          select case (message%type_kind)
          case (pFIO_INT32)
              call c_f_pointer(address, values_int32_1d, [product(count)])
              call formatter%get_var(message%var_name, values_int32_1d, start=start, count=count, _RC)
          case (pFIO_REAL32)
              call c_f_pointer(address, values_real32_1d, [product(count)])
              call formatter%get_var(message%var_name, values_real32_1d, start=start, count=count, _RC)
          case (pFIO_INT64)
              call c_f_pointer(address, values_int64_1d, [product(count)])
              call formatter%get_var(message%var_name, values_int64_1d, start=start, count=count, _RC)
          case (pFIO_REAL64)
              call c_f_pointer(address, values_real64_1d, [product(count)])
              call formatter%get_var(message%var_name, values_real64_1d, start=start, count=count, _RC)
          case default
              _FAIL( "Not supported type")
          end select
      end select
      _RETURN(_SUCCESS)
   end subroutine get_DataFromFile
Call graph
get_datafromfile calls mapl_assert, at, get_var, find, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
find calls mapl_return, mapl_verify, at, insert, next, erase, v_back, v_begin, v_front, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_var_real64_4 calls mapl_assert, mapl_return, nf90_get_var, nf90_inq_ncid, nf90_inq_varid
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
v_push_back calls resize, v_grow_to
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile
handle_done_collective_prefetch calls read_and_gather, read_and_share