get_child – MAPL
get_child Function
14 statements
Source File
private function get_child(this, name) result(child)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(inout), target :: this
character(len=*), intent(in) :: name
Return Value class(AbstractMeterNode), pointer
Calls
Called by
Source Code
   function get_child(this, name) result(child)
      class (AbstractMeterNode), pointer :: child
      class (MeterNode), target, intent(inout) :: this
      character(*), intent(in) :: name
      integer :: idx
      idx = this%find_child(name)
      if (idx /= NOT_FOUND) then
         child => this%children%at(idx)
         this%last_child_accessed = idx
      else
         child => null()
         this%last_child_accessed = 0
      end if
   end function get_child
Call graph
get_child calls at, find_child
find_child calls at
v_at_32 calls v_at_size_kind
accumulate calls get_child
test_depth_2 calls get_child
test_get_exclusive calls get_child
test_get_inclusive calls get_child
test_get_num_nodes calls get_child
test_get_num_nodes_2 calls get_child
test_node_reset calls get_child
test_percent_inclusive calls get_child
test_simple calls get_child