get_real64 – MAPL
get_real64 Subroutine
16 statements
Source File
private subroutine get_real64(this, coordinate_data, unusable, rc)
Type Bound
CoordinateVariable
Arguments
Type Intent Optional Attributes Name
class(CoordinateVariable), intent(in), target :: this
real(kind=REAL64), intent(out), pointer :: coordinate_data(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Contents
Source Code
get_real64
Source Code
   subroutine get_real64(this, coordinate_data, unusable, rc)
      class (CoordinateVariable), target, intent(in) :: this
      real(kind=REAL64), pointer, intent(out) :: coordinate_data(:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _ASSERT(allocated(this%coordinate_data), "not allocated coordinate data")
      select type (q => this%coordinate_data)
      type is (real(kind=REAL64))
         coordinate_data => q
      class default ! wrong type
         _FAIL( 'wrong type')
      end select
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine get_real64
Call graph
get_real64 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize