get_child_internal_state – MAPL
get_child_internal_state Function
8 statements
Source File
private function get_child_internal_state(this, i) result(state)
Type Bound
MAPL_MetaComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_MetaComp), target :: this
integer, intent(in) :: i
Return Value type(ESMF_State), pointer
Calls
Source Code
   function get_child_internal_state(this, i) result(state)
      type(ESMF_State), pointer :: state
      class(MAPL_MetaComp), target :: this
      integer, intent(in) :: i
      class(MaplGenericComponent), pointer :: child
      child => this%get_ith_child(i)
      state => child%get_internal_state()
   end function get_child_internal_state
Call graph
get_child_internal_state calls get_internal_state, get_ith_child
get_internal_state calls get_current_thread, is_threading_active
get_ith_child calls get_child
get_child_by_index calls get_component, get_child
get_child_by_name calls get_component, get_child