get_min_cycle – MAPL
get_min_cycle Function
5 statements
Source File
private function get_min_cycle(this) result(min_cycle)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(in) :: this
Return Value real(kind=REAL64)
Called by
Source Code
   function get_min_cycle(this) result(min_cycle)
      real(kind=REAL64) :: min_cycle
      class(AdvancedMeter), intent(in) :: this
      min_cycle = this%min_cycle
   end function get_min_cycle
Call graph
reduce_mpi calls get_min_cycle
test_get_min_cycle calls get_min_cycle
reduce_global calls reduce
test_get_max calls reduce
test_get_min calls reduce
test_get_num_cycles calls reduce
test_get_total calls reduce
test_trivial calls reduce