get_v2d_netcdf_R8 – MAPL
get_v2d_netcdf_R8 Subroutine
26 statements
Source File
public subroutine get_v2d_netcdf_R8(filename, name, array, Xdim, Ydim, rc)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: name
real(kind=REAL64), intent(out), dimension(Xdim,Ydim) :: array
integer, intent(in) :: Xdim
integer, intent(in) :: Ydim
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine get_v2d_netcdf_R8(filename, name, array, Xdim, Ydim, rc)
    use netcdf
    implicit none
    character(len=*), intent(in) :: name, filename
    integer, intent(in) :: Xdim, Ydim
    real(REAL64), dimension(Xdim,Ydim), intent(out) :: array
    integer, optional, intent(out) :: rc
    integer :: status
    integer :: ncid, varid
    real    :: scale_factor, add_offset
    integer :: iret
    call check_nc_status(nf90_open(trim(fileName), NF90_NOWRITE, ncid), _RC)
    call check_nc_status(nf90_inq_varid(ncid, name, varid), _RC)
    call check_nc_status(nf90_get_var(ncid, varid, array), _RC)
    iret = nf90_get_att(ncid, varid, 'scale_factor', scale_factor)
    if(iret .eq. 0) array = array * scale_factor
    !
    iret = nf90_get_att(ncid, varid, 'add_offset', add_offset)
    if(iret .eq. 0) array = array + add_offset
    !
    call check_nc_status(nf90_close(ncid), _RC)
    _RETURN(_SUCCESS)
  end subroutine get_v2d_netcdf_R8
Call graph
get_v2d_netcdf_r8 calls nf90_close, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_open, check_nc_status, mapl_return, mapl_verify
check_nc_status calls mapl_return, mapl_assert, nf90_strerror
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_v2d_netcdf calls get_v2d_netcdf_r8