get_CapGridComp_from_gc – MAPL
get_CapGridComp_from_gc Function
8 statements
Source File
private function get_CapGridComp_from_gc(gc) result(cap)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
Return Value type(ExtData_DriverGridComp), pointer
Calls
Called by
Source Code
  function get_CapGridComp_from_gc(gc) result(cap)
    type(ESMF_GridComp), intent(inout) :: gc
    type(ExtData_DriverGridComp), pointer :: cap
    type(ExtData_DriverGridComp_Wrapper) :: cap_wrapper
    integer :: rc
    call ESMF_UserCompGetInternalState(gc, internal_cap_name, cap_wrapper, rc)
    cap => cap_wrapper%ptr
  end function get_CapGridComp_from_gc
Call graph
get_capgridcomp_from_gc calls ESMF_UserCompGetInternalState
finalize_gc calls get_capgridcomp_from_gc
initialize_gc calls get_capgridcomp_from_gc
run_multipletimes calls get_capgridcomp_from_gc
run_gc calls run_multipletimes