get_directory – MAPL
get_directory Function
21 statements
Source File
private function get_directory(this, win) result(dir)
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(in) :: this
integer, intent(in) :: win
Return Value type(Directory)
Calls
Called by
Source Code
   function get_directory(this, win) result(dir)
      type (Directory) :: dir
      class (DirectoryService), intent(in) :: this
      integer, intent(in) :: win
      integer :: sz
      integer(kind=MPI_ADDRESS_KIND) :: disp
      integer :: ierror, rc
      call MPI_Win_lock(MPI_LOCK_EXCLUSIVE, 0, 0, win, ierror)
      _VERIFY(ierror)
      sz = sizeof_directory()
      disp = 0
      call MPI_Get(dir, sz, MPI_BYTE, 0, disp, sz, MPI_BYTE, win, ierror)
      _VERIFY(ierror)
      call MPI_Win_unlock(0, win, ierror)
      _VERIFY(ierror)
      return
      _UNUSED_DUMMY(this)
   end function get_directory
Call graph
get_directory calls mpi_get, mpi_win_lock, mpi_win_unlock, mapl_verify, sizeof_directory
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
connect_to_client calls get_directory
connect_to_server calls get_directory
publish calls get_directory
terminate_servers calls get_directory
test_put_directory calls get_directory
initialize calls connect_to_client, connect_to_server, publish
test_connect calls connect_to_client, connect_to_server, publish
test_connect_multi calls connect_to_client, connect_to_server, publish
test_connect_swap_role calls connect_to_client, connect_to_server, publish
test_connect_with_unused_process calls connect_to_client, connect_to_server, publish
test_publish calls publish
test_stress calls connect_to_client, connect_to_server, publish
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main