GetBracketTimeOnSingleFile – MAPL
GetBracketTimeOnSingleFile Subroutine
242 statements
Source File
private subroutine GetBracketTimeOnSingleFile(fdata, tSeries, cTime, bSide, UniFileClim, interpTime, fileTime, tindex, allowExtrap, climYear, rc)
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: fdata
type(ESMF_Time), intent(in) :: tSeries(:)
type(ESMF_Time), intent(inout) :: cTime
character(len=1), intent(in) :: bSide
logical, intent(in) :: UniFileClim
type(ESMF_Time), intent(inout) :: interpTime
type(ESMF_Time), intent(inout) :: fileTime
integer, intent(inout) :: tindex
logical, intent(in) :: allowExtrap
integer, intent(in) :: climYear
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine GetBracketTimeOnSingleFile(fdata,tSeries,cTime,bSide,UniFileClim,interpTime,fileTime,tindex,allowExtrap,climyear,rc)
        class(FileMetadataUtils),            intent(inout) :: fdata
        type(ESMF_Time),                     intent(in   ) :: tSeries(:)
        type(ESMF_Time),                     intent(inout) :: cTime
        character(len=1),                    intent(in   ) :: bSide
        logical,                             intent(in   ) :: UniFileClim
        type(ESMF_TIME),                     intent(inout) :: interpTime
        type(ESMF_TIME),                     intent(inout) :: fileTime
        integer,                             intent(inout) :: tindex
        logical,                             intent(in   ) :: allowExtrap
        integer,                             intent(in   ) :: climYear
        integer, optional,                   intent(out  ) :: rc
        __Iam__('GetBracketTimeOnSingleFile')
        integer(ESMF_KIND_I4)              :: iyr,imm,idd,ihr,imn,isc
        integer                            :: i
        type(ESMF_Time)                    :: climTime
        logical                            :: found
        logical                            :: LExtrap,RExtrap,LExact,RExact
        logical                            :: LSide, RSide
        integer                            :: yrOffset, yrOffsetNeg, targYear
        integer                            :: iEntry
        type(ESMF_Time), allocatable       :: tSeriesC(:)
        logical                            :: foundYear
        integer                            :: tSteps, curYear, nsteps
        _UNUSED_DUMMY(Iam)
        ! Store the target time which was actually requested
        yrOffset=0
        nsteps = size(tSeries)
        call ESMF_TimeGet(cTime,yy=targYear,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
        if (lgr%isEnabledFor(DEBUG)) then
           call lgr%debug('               GetBracketTimeOnSingleFile called for %a', trim(fdata%get_file_name()))
           call lgr%debug('               GetBracketTimeOnSingleFile: Reading times from fixed (%l1) file %a', UniFileClim, trim(fdata%get_file_name()))
           call ESMF_TimeGet(tSeries(1),yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('                  ==> File start    : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
           call ESMF_TimeGet(tSeries(nsteps),yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('                  ==> File end      : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
           call ESMF_TimeGet(cTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('                  ==> Time requested: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
        end if
        if (uniFileClim) then
           yrOffset = 0
           call ESMF_TimeGet(cTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           iyr = climYear
           if (idd == 29 .and. imm == 2) idd = 28
           call ESMF_TimeSet(climTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           tsteps=0
           foundYear = .false.
           do i=1,nsteps
              call ESMF_TimeGet(tseries(i),yy=iyr,_RC)
              if (iyr==climYear) then
                 if (foundYear .eqv. .false.) then
                    iEntry = i
                    foundYear = .true.
                 end if
                 tsteps=tsteps+1
              end if
           end do
           allocate(tSeriesC(tsteps),__STAT__)
           do i=1,tsteps
              tSeriesC(i)=tSeries(iEntry+i-1)
           enddo
           found = .false.
           if (bSide == "L") then
              if ( (climTime < tSeriesC(1)) ) then
                 fileTime = tSeriesC(tSteps)
                 tindex = tSteps
                 call ESMF_TimeGet(tSeriesC(tSteps),yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call ESMF_TimeGet(cTime,yy=curYear,_RC)
                 iyr = curYear - 1
                 call ESMF_TimeSet(interpTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 found = .true.
              else
                 do i=tSteps,1,-1
                    if (climTime >= tSeriesC(i)) then
                       fileTime = tSeriesC(i)
                       tindex = i
                       if (UniFileClim) then
                          call ESMF_TimeGet(cTime,yy=curYear,_RC)
                          call ESMF_TimeGet(fileTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                          call ESMF_TimeSet(interpTime,yy=curYear,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                       else
                          interpTime = tSeriesC(i)
                       end if
                       found = .true.
                       exit
                    end if
                 end do
              end if
           else if (bSide == "R") then
              if ( (climTime >= tSeriesC(tSteps)) ) then
                 fileTime = tSeriesC(1)
                 tindex = 1
                 call ESMF_TimeGet(tSeriesC(1),yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call ESMF_TimeGet(cTime,yy=curYear,_RC)
                 iyr = curYear + 1
                 call ESMF_TimeSet(interpTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 found = .true.
              else
                 do i=1,tSteps
                    if (climTime < tSeriesC(i)) then
                       fileTime = tSeriesC(i)
                       tindex = i
                       if (UniFileClim) then
                          call ESMF_TimeGet(cTime,yy=curYear,_RC)
                          call ESMF_TimeGet(fileTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                          call ESMF_TimeSet(interpTime,yy=curYear,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                       else
                          interpTime = tSeriesC(i)
                       end if
                       found = .true.
                       exit
                    end if
                 end do
              end if
           end if
        else
           yrOffset = 0
           climTime = cTime
           ! Is the requested time within the range of values offered?
           LSide = (bSide == "L")
           RSide = (.not.LSide)
           LExact  = (cLimTime == tSeries(1))
           RExact  = (cLimTime == tSeries(nsteps))
           LExtrap = (cLimTime <  tSeries(1))
           RExtrap = (cLimTime >  tSeries(nsteps))
           found = .false.
           call lgr%debug('               GetBracketTimeOnSingleFile: Extrapolation flags (0) are %L1 %L1 %L1 %L1 for file %a',LExact,RExact,LExtrap,RExtrap, trim(fdata%get_file_name()))
           if (allowExtrap) then
              If (LExtrap) Then
                 call lgr%debug('               GetBracketTimeOnSingleFile: Requested time is before first available sample in file %a', trim(fdata%get_file_name()))
                 ! Increase the target time until it is within range
                 Do While (LExtrap)
                    yrOffset = yrOffset + 1
                    iYr = targYear + yrOffset
                    call OffsetTimeYear(cTime,yrOffset,cLimTime,rc)
                    If (LSide) Then
                       LExtrap = (cLimTime <  tSeries(1))
                    Else
                       LExtrap = (cLimTime <= tSeries(1))
                       ! When scanning for the right side, if we find that we
                       ! have an exact match to the first entry, then as long
                       ! as there is a second entry, we have the correct offset
                       If (LExtrap.and.(nsteps > 1)) Then
                          LExact  = (cLimTime == tSeries(1))
                          LExtrap = (LExtrap.and.(.not.LExact))
                       End If
                    End If
                 End Do
              Else If (RExtrap.or.(RExact.and.RSide)) Then
                 call lgr%debug('               GetBracketTimeOnSingleFile: Requested time is after or on last available sample in file %a', trim(fdata%get_file_name()))
                 Do While (RExtrap.or.(RExact.and.RSide))
                    yrOffset = yrOffset - 1
                    iYr = targYear + yrOffset
                    call OffsetTimeYear(cTime,yrOffset,cLimTime,rc)
                    If (LSide) Then
                       RExtrap = (cLimTime >  tSeries(nsteps))
                    Else
                       RExtrap = (cLimTime >= tSeries(nsteps))
                       RExact  = (cLimTime == tSeries(nsteps))
                    End If
                 End Do
              End If
              ! Retest for an exact match - note this is only useful if we want bracket L
              LExact  =  (cLimTime == tSeries(1))
              RExact  =  (cLimTime == tSeries(nsteps))
              call lgr%debug('            GetBracketTimeOnSingleFile: Extrapolation flags (2) are %L1 %L1 %L1 %L1 for file %a',LExact,RExact,LExtrap,RExtrap, trim(fdata%get_file_name()))
           End IF
           If (LSide.and.LExact) Then
              found = .true.
              iEntry = 1
           Else If (LSide.and.RExact) Then
              found = .true.
              iEntry = nsteps
           Else
              if (bSide == "L") then
                 do i=nsteps,1,-1
                    if (climTime >= tSeries(i)) then
                       iEntry = i
                       found = .true.
                       exit
                    end if
                 end do
              else if (bSide == "R") then
                 do i=1,nsteps
                    if (climTime < tSeries(i)) then
                       iEntry = i
                       found = .true.
                       exit
                    end if
                 end do
              end if
           end if
           if (found) then
              fileTime = tSeries(iEntry)
              tindex = iEntry
              if (yrOffset == 0) Then
                 interpTime = fileTime
              Else
                 yrOffsetNeg = -1*yrOffset
                 call OffsetTimeYear(fileTime,yrOffsetNeg,interpTime,rc)
              End If
           end if
        end if
        if (found) then
           if (lgr%isEnabledFor(DEBUG)) then
              call ESMF_TimeGet(fileTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
              call lgr%debug('               GetBracketTimeOnSingleFile: Data from time  %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2 set for bracket %a1 of file %a', &
                   & iyr, imm, idd, ihr, imn, isc, bside, trim(fdata%get_file_name()))
              if (yrOffset /= 0) then
                 call ESMF_TimeGet(interpTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call lgr%debug('              ==> Mapped to:  %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
                 call ESMF_TimeGet(interpTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call lgr%debug('              ==> Target to:  %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
              end if
           end if
           _RETURN(ESMF_SUCCESS)
        else
           call lgr%error('Requested sample not found in file %a', trim(fdata%get_file_name()))
           _RETURN(ESMF_FAILURE)
        endif
     end subroutine GetBracketTimeOnSingleFile
Call graph
getbrackettimeonsinglefile calls ESMF_TimeGet, ESMF_TimeSet, debug, error, get_file_name, isenabledfor, mapl_return, mapl_verify, offsettimeyear
get_file_name calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
offsettimeyear calls ESMF_TimeGet, ESMF_TimeSet, mapl_return, mapl_verify
get_error_message calls at, insert
mapl_throw_exception calls initialize
updatebrackettime calls getbrackettimeonsinglefile
run_ calls updatebrackettime