GetBracketTimeOnFile – MAPL
GetBracketTimeOnFile Subroutine
104 statements
Source File
private subroutine GetBracketTimeOnFile(fdata, tSeries, cTime, bSide, UniFileClim, interpTime, fileTime, tindex, yrOffsetInt, rc)
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: fdata
type(ESMF_Time), intent(in) :: tSeries(:)
type(ESMF_Time), intent(inout) :: cTime
character(len=1), intent(in) :: bSide
logical, intent(in) :: UniFileClim
type(ESMF_Time), intent(inout) :: interpTime
type(ESMF_Time), intent(inout) :: fileTime
integer, intent(inout) :: tindex
integer, intent(in), optional :: yrOffsetInt
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
GetBracketTimeOnFile
Source Code
     subroutine GetBracketTimeOnFile(fdata,tSeries,cTime,bSide,UniFileClim,interpTime,fileTime,tindex,yrOffsetInt,rc)
        class(FileMetadataUtils),            intent(inout) :: fdata
        type(ESMF_Time),                     intent(in   ) :: tSeries(:)
        type(ESMF_Time),                     intent(inout) :: cTime
        character(len=1),                    intent(in   ) :: bSide
        logical,                             intent(in   ) :: UniFileClim
        type(ESMF_TIME),                     intent(inout) :: interpTime
        type(ESMF_TIME),                     intent(inout) :: fileTime
        integer,                             intent(inout) :: tindex
        integer, optional,                   intent(in   ) :: yrOffsetInt
        integer, optional,                   intent(out  ) :: rc
        __Iam__('GetBracketTimeOnFile')
        integer(ESMF_KIND_I4)              :: iyr,imm,idd,ihr,imn,isc
        integer                            :: i
        type(ESMF_Time)                    :: climTime
        logical                            :: found, outOfBounds
        integer                            :: yrOffset, yrOffsetNeg
        integer                            :: climSize,tsteps
        _UNUSED_DUMMY(Iam)
        tsteps = size(tSeries)
        ! Assume that the requested time is within range
        If (Present(yrOffsetInt)) Then
           yrOffset = yrOffsetInt
        Else
           yrOffset = 0
        End If
        if (UniFileClim) then
           call lgr%error('GetBracketTimeOnFile: called with UniFileClim true')
           _RETURN(ESMF_FAILURE)
        end if
        call lgr%debug('               GetBracketTimeOnFile: (%a1) called for %a', bside, trim(fdata%get_file_name()))
        if (yrOffset.ne.0) then
           ! If the source year is a leap year but this isn't, modify to day 28
           call OffsetTimeYear(cTime,yrOffset,cLimTime,rc)
        else
           climTime = cTime
        end if
        climSize = 1
        ! Debug output
        if (lgr%isEnabledFor(DEBUG)) then
           call ESMF_TimeGet(cLimTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('              GetBracketTimeOnFile: Year offset of %i3 applied while scanning %a to give target time %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', &
                & yrOffset, trim(fdata%get_file_name()), iyr, imm, idd, ihr, imn, isc)
        end if
        found = .false.
        ! we will have to specially handle a climatology in one file
        ! might be better way but can not think of one
        if (bSide == "L") then
           OutOfBounds = (cLimTime < tSeries(1))
           If (OutOfBounds) Then
              ! This can be an acceptable outcome - no printout
              if(present(RC)) RC = ESMF_FAILURE
              Return
           End If
           do i=tSteps,1,-1
              if (climTime >= tSeries(i)) then
                 fileTime = tSeries(i)
                 tindex = i
                 if (yrOffset .ne. 0) Then
                    yrOffsetNeg = -1*yrOffset
                    Call OffsetTimeYear(fileTime,yrOffsetNeg,interpTime,rc)
                 else
                    interpTime = fileTime
                 end if
                 found = .true.
                 exit
              end if
           end do
        else if (bSide == "R") then
           ! Is the requested time within the range of values offered?
           OutOfBounds = (cLimTime >= tSeries(tSteps))
           If (OutOfBounds) Then
              ! This can be an acceptable outcome - no printout
              if(present(RC)) RC = ESMF_FAILURE
              Return
           End If
           do i=1,tSteps
              if (climTime < tSeries(i)) then
                 fileTime = tSeries(i)
                 tindex = i
                 if (yrOffset .ne. 0) Then
                    yrOffsetNeg = -1*yrOffset
                    Call OffsetTimeYear(fileTime,yrOffsetNeg,interpTime,rc)
                 else
                    interpTime = fileTime
                 end if
                 found = .true.
                 exit
              end if
           end do
        end if
        if (found) then
           if (lgr%isEnabledFor(DEBUG)) then
              call ESMF_TimeGet(fileTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
              call lgr%debug('               GetBracketTimeOnFile: Data from time  %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2 set for bracket %a1 of file %a', &
                   & iyr, imm, idd, ihr, imn, isc, bside, trim(fdata%get_file_name()))
              if (yrOffset /= 0) then
                 call ESMF_TimeGet(interpTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call lgr%debug('        GetBracketTimeOnFile:  ==> Mapped to:  %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2 offset %i0.2', iyr, imm, idd, ihr, imn, isc, yrOffset)
              end if
           end if
           _RETURN(ESMF_SUCCESS)
        else
           call lgr%error('Requested sample not found in file %a ', trim(fdata%get_file_name()))
        _RETURN(ESMF_FAILURE)
     endif
     !end if
  end subroutine GetBracketTimeOnFile
Call graph
getbrackettimeonfile calls ESMF_TimeGet, debug, error, isenabledfor, get_file_name, mapl_return, mapl_verify, offsettimeyear
get_file_name calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
offsettimeyear calls ESMF_TimeGet, mapl_return, mapl_verify, ESMF_TimeSet
get_error_message calls at
mapl_throw_exception calls initialize
updatebrackettime calls getbrackettimeonfile
run_ calls updatebrackettime