GetClimYear – MAPL
GetClimYear Subroutine
55 statements
Source File
private subroutine GetClimYear(item, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
GetClimYear
Source Code
     subroutine GetClimYear(item, rc)
        type(PrimaryExport)      , intent(inout) :: item
        integer, optional        , intent(out  ) :: rc
        integer(ESMF_KIND_I4)      :: iyr
        type(ESMF_TimeInterval)    :: zero
        integer                    :: lasttoken
        character(len=ESMF_MAXPATHLEN) :: file
        character(len=2)           :: token
        integer                    :: nymd, nhms, climYear
        character(len=ESMF_MAXSTR) :: buffer
        logical                    :: inRange
        type(FileMetadataUtils), pointer :: metadata
        integer :: status
        buffer = trim(item%cyclic)
        if (trim(buffer) == 'n') then
           item%cyclic = "n"
           _RETURN(ESMF_SUCCESS)
        else if (trim(buffer) == 'single') then
           _RETURN(ESMF_SUCCESS)
        else if (trim(buffer) == 'y') then
           item%cyclic = "y"
           call ESMF_TimeIntervalSet(zero,_RC)
           if (item%frequency == zero) then
              file = item%file
           else
              lasttoken = index(item%file,'%',back=.true.)
              token = item%file(lasttoken+1:lasttoken+2)
              _ASSERT(token == "m2",'Clim year must be month template "%m2"')
              ! just put a time in so we can evaluate the template to open a file
              nymd = 20000101
              nhms = 0
              call fill_grads_template(file,item%file,nymd=nymd,nhms=nhms,_RC)
           end if
           call MakeMetadata(file,item%pfioCollection_id,metadata,_RC)
           call metadata%get_time_info(startYear=iyr)
           item%climYear=iYr
           _RETURN(ESMF_SUCCESS)
        else
           read(buffer,'(I4)') climYear
           inRange = 0 <= climYear .and. climYear <= 3000
           if (inRange) then
              item%cyclic = "y"
              item%climYear = climYear
              _RETURN(ESMF_SUCCESS)
           else
              _FAIL( 'cyclic keyword was not y, n, or a valid year (0 < year < 3000)')
           end if
        end if
     end subroutine GetClimYear
Call graph
getclimyear calls ESMF_TimeIntervalSet, mapl_assert, fill_grads_template, get_time_info, makemetadata, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
fill_grads_template calls mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, check_token, evaluate_token
get_time_info calls ESMF_TimeIntervalSet, mapl_assert, mapl_return, mapl_verify, ESMF_TimeGet, ESMF_TimeSet, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, get_coordinate_info, get_file_name
makemetadata calls mapl_return, mapl_verify, at, debug, find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
evaluate_token calls skip_token
get_coordinate_info calls mapl_assert, mapl_return, mapl_verify, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, get_file_name, get_dimension, get_ith_dimension, var_has_attr
get_error_message calls at
get_file_name calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
var_has_attr calls mapl_assert, mapl_return, mapl_verify, get_file_name, get_variable, is_attribute_present
initialize_ calls getclimyear