GetDateInt4 – MAPL
GetDateInt4 Subroutine
13 statements
Source File
public subroutine GetDateInt4(yyyymmdd_1, hhmmss_1, offset, yyyymmdd_2, hhmmss_2, rc)
GetDateInt4 — Returns a new date/time from an initial date/time and offset
This subroutine returns a new date and time in yyyymmdd and hhmmss format given and initial date, time, and offset in seconds. The routine converts the input date and time to julian seconds, adds the offset, and converts back to yyyymmdd and hhmmss format. This routine has been tested for Y2K compiance.
History
1998.07.20 Lucchesi Initial version.
2010.05.11 Lucchesi Integer for julian seconds changed to 64-bit. StartDate constant no longer needed.
Arguments
Type Intent Optional Attributes Name
integer :: yyyymmdd_1
Initial date in YYYYYMMDD format
integer :: hhmmss_1
Initial time in HHMMSS format
integer :: offset
Offset to add (in seconds)
integer :: yyyymmdd_2
New date in YYYYMMDD format
integer :: hhmmss_2
New time in HHMMSS format
integer :: rc
Return code. (<0 = error)
Calls
Called by
Source Code
       subroutine GetDateInt4 (yyyymmdd_1,hhmmss_1,offset, &
                          yyyymmdd_2,hhmmss_2,rc)
       implicit none
!
! !INPUT PARAMETERS:
!
       integer yyyymmdd_1               !! Initial date in YYYYYMMDD format
       integer hhmmss_1                 !! Initial time in HHMMSS format
       integer offset                   !! Offset to add (in seconds)
!
! !OUTPUT PARAMETERS:
!
       integer yyyymmdd_2               !! New date in YYYYMMDD format
       integer hhmmss_2                 !! New time in HHMMSS format
       integer rc                       !! Return code. (<0 = error)
!
!-------------------------------------------------------------------------
       integer(Kind=INT64) offsetLong
       offsetLong = INT(offset,Kind=INT64)
       call GetDateInt8(yyyymmdd_1,hhmmss_1,offsetLong,yyyymmdd_2,hhmmss_2,rc)
       return
      end subroutine GetDateInt4
Call graph
getdateint4 calls getdateint8
getdateint8 calls caldat, cfio_parseinttime, julday
getdate calls getdateint4
esmf_cfiosdfvarreadt2d__ calls getdate, getbegdatetime
esmf_cfiosdfvarreadt3d__ calls getdate, getbegdatetime
esmf_cfiovarreadt2d__ calls getdate
esmf_cfiovarreadt3d__ calls getdate
getbegdatetime calls getdate
getdatetimevec calls getdate
gettimesonfile calls getdate, getdatetimevec
gettindex calls getdate, getdatetimevec
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d__, esmf_cfiosdfvarreadt2d_, esmf_cfiosdfvarreadt3d_
esmf_cfiovarreadt2 calls esmf_cfiovarreadt2d__, esmf_cfiovarreadt3d__
cfio_getvar calls getdatetimevec
cfio_sgetvar calls getdatetimevec
esmf_cfiosdffileopen calls getbegdatetime
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__
esmf_cfiovarreadt2d_ calls esmf_cfiovarreadt2d__
esmf_cfiovarreadt3d_ calls esmf_cfiovarreadt3d__
mapl_cfioreadparallel_ calls gettindex
esmf_cfiovarreadt calls esmf_cfiovarreadt2d_, esmf_cfiovarreadt3d_
mapl_cfioreadparallel calls mapl_cfioreadparallel_
esmf_cfiofileopen calls esmf_cfiosdffileopen
esmf_cfiosdfvarread1d_ calls cfio_sgetvar, esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls cfio_getvar, cfio_sgetvar, esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls cfio_getvar, esmf_cfiosdffileopen