GETFILEMEM – MAPL
GETFILEMEM Function
31 statements
Source File
private function GETFILEMEM(Name, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: Name
integer, intent(out), optional :: RC
Return Value integer
Called by
Source Code
  INTEGER FUNCTION GETFILEMEM(name,  RC )
    IMPLICIT NONE
    character(LEN=*), intent(in   )           :: Name
    integer         , intent(  out), OPTIONAL :: RC
    integer :: i
    logical :: found
    found = .false.
    do i = 3, last_unit
       if(name==Mname(i)) then
          found = .true.
          exit
       end if
    end do
    if (.not. found) then
       do i = 3,last_unit
          if(.not.MTAKEN(i)) then
             found = .true.
             exit
          endif
       enddo
    end if
    if (.not. found) then
       if(present(rc)) rc = 1
       return
    endif
    mname(i)   = name
    mtaken(i)  = .true.
    getfilemem = -i
    if(present(rc)) rc = 0
    return
  end function getfilemem
Call graph
getfile calls getfilemem
cap_finalize calls getfile
initialize calls getfile
mapl_climupdate calls getfile
mapl_clockinit calls getfile
mapl_destroystatesave calls getfile, mapl_destroystatesave
mapl_esmfstatereadfromfile calls getfile
mapl_esmfstatewritetofile calls getfile
mapl_genericstaterestore calls getfile, mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_gradsctlwrite calls getfile
mapl_gridcoordadjustfromfile calls getfile
mapl_locstreamcreatefromfile calls getfile
mapl_readforcingx calls getfile
mapl_staterefresh calls getfile, mapl_esmfstatereadfromfile
readrestart calls getfile
run calls getfile, mapl_gradsctlwrite
writerestart calls getfile
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
capture calls mapl_esmfstatewritetofile
destroy_state calls mapl_destroystatesave
finalize_gc calls cap_finalize
initialize_gc calls mapl_clockinit
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericrefresh calls mapl_staterefresh
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterecord calls mapl_esmfstatewritetofile
refresh_state calls mapl_genericstaterestore