GETIDAY – MAPL
GETIDAY Subroutine
28 statements
Source File
private subroutine GETIDAY(IDAY, TIME, ORBIT, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: IDAY
integer, intent(in) :: TIME
type(MAPL_SunOrbit), intent(in) :: ORBIT
integer, intent(out), optional :: RC
Calls
Called by
Source Code
    subroutine GETIDAY(IDAY,TIME,ORBIT,RC)
      integer,              intent(OUT) :: IDAY
      integer,              intent(IN ) :: TIME
      type(MAPL_SunORBIT),  intent(IN ) :: ORBIT
      integer, optional,    intent(OUT) :: RC
      real :: ANOMALY
      select case(TIME)
      case (MAPL_SunAutumnalEquinox)
         ANOMALY = MAPL_PI
      case (MAPL_SunWinterSolstice )
         ANOMALY = (MAPL_PI*3.0)/2.0
      case (MAPL_SunVernalEquinox  )
         ANOMALY = 0.0
      case (MAPL_SunSummerSolstice )
         ANOMALY = MAPL_PI/2.0
      case  default
         _RETURN(ESMF_FAILURE)
      end select
      do IDAY=1,ORBIT%DAYS_PER_CYCLE-1
         if(ORBIT%TH(IDAY)<=ANOMALY .and. ORBIT%TH(IDAY+1)>ANOMALY) then
            _RETURN(ESMF_SUCCESS)
         end if
      end do
      _RETURN(ESMF_FAILURE)
    end subroutine GETIDAY
Call graph
getiday calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
solar_1d calls getiday, mapl_sungetinsolation
solar_2d calls getiday, mapl_sungetinsolation
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
solar_arr_int calls mapl_sungetinsolation