getLocalPET – MAPL
getLocalPET Function
6 statements
Source File
private function getLocalPET(this) result(localPET)
Type Bound
ESMF_TestCase
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestCase), intent(in) :: this
Return Value integer
Calls
Called by
Source Code
   integer function getLocalPET(this) result(localPET)
      class (ESMF_TestCase), intent(in) :: this
      type (ESMF_VM) :: vm
      vm = this%getVM()
      call ESMF_VMGet(vm, localPET=localPET)
   end function getLocalPET
Call graph
getlocalpet calls ESMF_VMGet, getvm
getvm calls ESMF_GridCompGet
setup calls getlocalpet
test_centers calls getlocalpet
test_corners calls getlocalpet
test_shape calls getlocalpet