GetLevs – MAPL
GetLevs Subroutine
155 statements
Source File
private subroutine GetLevs(item, time, state, allowExtrap, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_Time), intent(inout) :: time
type(ESMF_State), intent(in) :: state
logical, intent(in) :: allowExtrap
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
GetLevs
Source Code
     subroutine GetLevs(item, time, state, allowExtrap, rc)
        type(PrimaryExport)      , intent(inout) :: item
        type(ESMF_Time)          , intent(inout) :: time
        type(ESMF_State)         , intent(in   ) :: state
        logical                  , intent(in   ) :: allowExtrap
        integer, optional        , intent(out  ) :: rc
        integer :: status
        integer(ESMF_KIND_I4)      :: iyr,imm,idd,ihr,imn,iss,i,n,refYear
        character(len=ESMF_MAXPATHLEN) :: file
        integer                    :: nymd, nhms, rank
        type(ESMF_Time)            :: fTime
        type(ESMF_Field)           :: field
        real, allocatable          :: levFile(:)
        character(len=ESMF_MAXSTR) :: buff,levunits,tlevunits,temp_name
        logical                    :: found,lFound,intOK
        integer                    :: maxOffset
        character(len=:), allocatable :: levname
        character(len=:), pointer :: positive
        type(FileMetadataUtils), pointer :: metadata
        type(Variable), pointer :: var
        type(ESMF_TimeInterval)    :: zero
        integer :: vect_semi
        positive=>null()
        call ESMF_TimeIntervalSet(zero,_RC)
        vect_semi=index(item%name,";")
        if (vect_semi/=0) then
           temp_name=item%name(:vect_semi-1)
        else
           temp_name=item%name
        end if
        call ESMF_StateGet(state,trim(temp_name),field,_RC)
        call ESMF_FieldGet(field,rank=rank,_RC)
        if (rank==2) then
           item%lm=0
           _RETURN(_SUCCESS)
        end if
        if (item%frequency == zero) then
           file = item%file
           Inquire(file=trim(file),EXIST=found)
        else
           buff = trim(item%refresh_template)
           buff = ESMF_UtilStringLowerCase(buff, _RC)
           if ( index(buff,'t')/=0) then
              if (index(buff,'p') == 0) then
                 ftime = timestamp_(time,buff,_RC)
              else
                 ftime = time
              end if
           else
              ftime = time
           end if
           call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=iss,_RC)
           if (item%cyclic == 'y') then
              iyr = item%climyear
           end if
          call MAPL_PackTime(nymd,iyr,imm,idd)
          call MAPL_PackTime(nhms,ihr,imn,iss)
          call fill_grads_template(file,item%file,nymd=nymd,nhms=nhms,_RC)
          Inquire(file=trim(file),EXIST=found)
        end if
        if (found) then
           call MakeMetadata(file,item%pfioCollection_id,metadata,_RC)
        else
           if (allowExtrap .and. (item%cyclic == 'n') ) then
              ftime = item%reff_time
              n = 0
              maxOffSet = 100
              call ESMF_TimeGet(item%reff_time,yy=refYear)
              lfound = .false.
              intOK = .true.
              do while (intOK .and. (.not.lfound))
                 call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=iss,_RC)
                 call MAPL_PackTime(nymd,iyr,imm,idd)
                 call MAPL_PackTime(nhms,ihr,imn,iss)
                 call fill_grads_template(file,item%file,nymd=nymd,nhms=nhms,_RC)
                 Inquire(file=trim(file),exist=lfound)
                 intOK = (abs(iYr-refYear)<maxOffset)
                 if (.not.lfound) then
                    n = n + 1
                    ftime = ftime + item%frequency
                 else
                    call MakeMetadata(file,item%pfioCollection_id,metadata,_RC)
                 end if
              enddo
              if (.not.lfound) then
                 _FAIL( 'From ' // trim(item%file) // ' could not find file with extrapolation')
              end if
           else
              _FAIL('From ' // trim(item%file) // ' could not find time no extrapolation')
           end if
        end if
        var => null()
        if (item%isVector) then
           var=>metadata%get_variable(trim(item%fcomp1))
           _ASSERT(associated(var),"Variable "//TRIM(item%fcomp1)//" not found in file "//TRIM(item%file))
           var => null()
           var=>metadata%get_variable(trim(item%fcomp2))
           _ASSERT(associated(var),"Variable "//TRIM(item%fcomp2)//" not found in file "//TRIM(item%file))
        else
           var=>metadata%get_variable(trim(item%var))
           _ASSERT(associated(var),"Variable "//TRIM(item%var)//" not found in file "//TRIM(item%file))
        end if
        levName = metadata%get_level_name(rc=status)
        _VERIFY(status)
        if (trim(levName) /='') then
           call metadata%get_coordinate_info(levName,coordSize=item%lm,coordUnits=tLevUnits,coords=levFile,_RC)
           levUnits=MAPL_TrimString(tlevUnits)
           ! check if pressure
           item%levUnit = ESMF_UtilStringLowerCase(levUnits)
           if (trim(item%levUnit) == 'hpa' .or. trim(item%levUnit)=='pa') then
              item%havePressure = .true.
           end if
           if (item%havePressure) then
              if (levFile(1)>levFile(size(levFile))) item%fileVDir="up"
           else
              positive => metadata%get_variable_attribute(levName,'positive',_RC)
              if (associated(positive)) then
                 if (MAPL_TrimString(positive)=='up') item%fileVDir="up"
              end if
           end if
           allocate(item%levs(item%lm),__STAT__)
           item%levs=levFile
           if (trim(item%fileVDir)/=trim(item%importVDir)) then
              do i=1,size(levFile)
                 item%levs(i)=levFile(size(levFile)-i+1)
              enddo
           end if
           if (trim(item%levunit)=='hpa') item%levs=item%levs*100.0
           if (item%isVector) then
              item%units = metadata%get_variable_attribute(trim(item%fcomp1),"units",rc=status)
              _VERIFY(status)
           else
              item%units = metadata%get_variable_attribute(trim(item%var),"units",rc=status)
              _VERIFY(status)
           end if
        else
           item%LM=0
        end if
        _RETURN(ESMF_SUCCESS)
     end subroutine GetLevs
Call graph
getlevs calls fill_grads_template, mapl_assert, mapl_verify, esmf_stateget, makemetadata, esmf_timeintervalset, esmf_fieldget, mapl_return, esmf_utilstringlowercase, timestamp_, esmf_timeget, mapl_packtime, mapl_trimstring
fill_grads_template calls mapl_assert, mapl_verify, mapl_return, esmf_timeget, check_token, evaluate_token
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_verify calls mapl_throw_exception
makemetadata calls mapl_verify, mapl_return
mapl_return calls mapl_throw_exception, get_error_message
timestamp_ calls mapl_assert, mapl_verify, mapl_return, esmf_utilstringlowercase, esmf_timeget, esmf_timeset
mapl_packtime calls mapl_packtime
mapl_trimstring calls mapl_trimstring, mapl_verify, mapl_return
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
evaluate_token calls skip_token
mapl_assert_condition calls mapl_throw_exception
initialize_ calls getlevs