getNumPETsRequested – MAPL
getNumPETsRequested Function
10 statements
Source File
private function getNumPETsRequested(this) result(numPETsRequested)
Type Bound
ESMF_TestCase
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestCase), intent(in) :: this
Return Value integer
Calls
Called by
Source Code
   integer function getNumPETsRequested(this) result(numPETsRequested)
      class (ESMF_TestCase), intent(in) :: this
      select type (p => this%testParameter)
      class is (ESMF_TestParameter)
         numPETsRequested = p%getNumPETsRequested()
      class default
         numPETsRequested = 0
         call throw('Incorrect type of test parameter in ESMF_TestCase::getNumPETsRequested()')
      end select
   end function getNumPETsRequested
Call graph
getnumpetsrequested calls getnumpetsrequested, throw
runbare_inner calls getnumpetsrequested
runbare calls runbare_inner