GetPinFlagFromConfig – MAPL
GetPinFlagFromConfig Function
30 statements
Source File
private function GetPinFlagFromConfig(rcfile, rc) result(pinflag)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: rcfile
integer, intent(out), optional :: rc
Return Value type(ESMF_Pin_Flag)
Calls
Called by
Source Code
   function GetPinFlagFromConfig(rcfile, rc) result(pinflag)
     character(len=*), intent(in) :: rcfile
     integer, optional, intent(out) :: rc
     type(ESMF_PIN_Flag) :: pinflag
     character(len=ESMF_MAXSTR) :: pinflag_str
     integer :: status
     type(ESMF_Config) :: config
     config = ESMF_ConfigCreate(_RC)
     call ESMF_ConfigLoadFile(config,rcfile, _RC)
     call ESMF_ConfigGetAttribute(config, value=pinflag_str, &
          label='ESMF_PINFLAG:', default='SSI_CONTIG', _RC)
     select case (pinflag_str)
     case ('PET')
        pinflag = ESMF_PIN_DE_TO_PET
     case ('VAS')
        pinflag = ESMF_PIN_DE_TO_VAS
     case ('SSI')
        pinflag = ESMF_PIN_DE_TO_SSI
     case ('SSI_CONTIG')
        pinflag = ESMF_PIN_DE_TO_SSI_CONTIG
     case default
        _ASSERT(.false.,'Unsupported PIN flag')
     end select
     call ESMF_ConfigDestroy(config, _RC)
     _RETURN(_SUCCESS)
   end function GetPinFlagFromConfig
Call graph
getpinflagfromconfig calls ESMF_ConfigCreate, ESMF_ConfigDestroy, ESMF_ConfigGetAttribute, ESMF_ConfigLoadFile, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_cap_gc calls getpinflagfromconfig
initialize_p0 calls initialize_cap_gc
run_model calls initialize_cap_gc
run_member calls run_model
run_ensemble calls run_member