GetSharedMemory – MAPL
GetSharedMemory Module Procedure
47 statements
Source File
module procedure GetSharedMemory module subroutine GetSharedMemory(Caddr, Len, rc) Interface →
! Create the segment in root and have other processors ! get the segment id using the common key
! Everyone attaches the memory to their own C pointer
! Check that we have valid shared memory
! Return C address. It will be attached to a Fortran pointer ! with rank overloads
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(out) :: Caddr
integer, intent(in) :: Len
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
getsharedmemory calls mapl_assert, shmat, shmget, mpi_barrier, mapl_return, segs, segsnew, getsharedmemory
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_allocnodearray_1di4 calls getsharedmemory
mapl_allocnodearray_1dl4 calls getsharedmemory
mapl_allocnodearray_1dr4 calls getsharedmemory
mapl_allocnodearray_1dr8 calls getsharedmemory
mapl_allocnodearray_2di4 calls getsharedmemory
mapl_allocnodearray_2dr4 calls getsharedmemory
mapl_allocnodearray_2dr8 calls getsharedmemory
mapl_allocnodearray_3di4 calls getsharedmemory
mapl_allocnodearray_3dr4 calls getsharedmemory
mapl_allocnodearray_3dr8 calls getsharedmemory
mapl_allocnodearray_4di4 calls getsharedmemory
mapl_allocnodearray_4dr4 calls getsharedmemory
mapl_allocnodearray_4dr8 calls getsharedmemory
mapl_allocnodearray_5dr8 calls getsharedmemory
mapl_allocnodearray_6dr8 calls getsharedmemory
mapl_allocnodearray_tiling calls getsharedmemory