GetTimesOnFile – MAPL
GetTimesOnFile Subroutine
32 statements
Source File
private subroutine GetTimesOnFile(cfio, tSeries, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO) :: cfio
type(ESMF_Time) :: tSeries(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
GetTimesOnFile
Source Code
     subroutine GetTimesOnFile(cfio,tSeries,rc)
        type(ESMF_CFIO)                           :: cfio
        type(ESMF_Time)                           :: tSeries(:)
        integer, optional,          intent(out  ) :: rc
        integer :: status
        integer(ESMF_KIND_I4)              :: iyr,imm,idd,ihr,imn,isc
        integer                            :: i
        integer(ESMF_KIND_I8)              :: iCurrInterval
        integer                            :: nhmsB, nymdB
        integer                            :: begDate, begTime
        integer(ESMF_KIND_I8),allocatable  :: tSeriesInt(:)
        allocate(tSeriesInt(cfio%tSteps))
        call getDateTimeVec(cfio%fid,begDate,begTime,tSeriesInt,_RC)
        ! Assume success
        If (present(rc))  rc=ESMF_SUCCESS
        call lgr%debug('               GetTimesOnFile: Reading times')
        call lgr%debug('                  ==> File: %a', trim(cfio%fName))
        call lgr%debug('                  ==> File timing info: %i0.10 %i0.10 %i0.4', begDate, begTime, cfio%tSteps)
        do i=1,cfio%tSteps
           iCurrInterval = tSeriesInt(i)
           call GetDate ( begDate, begTime, iCurrInterval, nymdB, nhmsB, status )
           call MAPL_UnpackTime(nymdB,iyr,imm,idd)
           call MAPL_UnpackTime(nhmsB,ihr,imn,isc)
           if (lgr%isEnabledFor(DEBUG) .and. any(i == [1,cfio%tsteps])) then
              call lgr%debug('                  ==> STD Sample %i~: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', i, iYr, iMm, iDd, iHr, iMn, iSc)
           end if
           call ESMF_TimeSet(tSeries(i), yy=iyr, mm=imm, dd=idd,  h=ihr,  m=imn, s=isc,_RC)
        enddo
        deallocate(tSeriesInt)
        return
     end subroutine GetTimesOnFile
Call graph
gettimesonfile calls ESMF_TimeSet, debug, getdate, mapl_unpacktime, isenabledfor, getdatetimevec, mapl_verify
getdate calls getdateint4, getdateint8
mapl_unpacktime calls mapl_unpacktime
getdatetimevec calls getdate, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_inquire, nf90_inquire_dimension, nf90_inquire_variable, err, identifydim, parsetimeunits
mapl_verify calls mapl_throw_exception
getdateint4 calls getdateint8
getdateint8 calls caldat, cfio_parseinttime, julday
mapl_throw_exception calls initialize