GetTIndex – MAPL
GetTIndex Subroutine
30 statements
Source File
private subroutine GetTIndex(cfio, time, tindex, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO) :: cfio
type(ESMF_Time) :: time
integer :: tindex
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine GetTIndex(cfio,time,tindex,rc)
     type(ESMF_CFIO)                           :: cfio
     type(ESMF_Time)                           :: time
     integer                                   :: tindex
     integer, optional,          intent(out  ) :: rc
     integer(ESMF_KIND_I4)              :: iyr,imm,idd,ihr,imn,isc
     integer                            :: i,status
     integer(ESMF_KIND_I8)              :: iCurrInterval
     integer                            :: nhmsB, nymdB
     integer                            :: begDate, begTime
     integer(ESMF_KIND_I8),allocatable  :: tSeriesInt(:)
     type(ESMF_TIME)                    :: ctime
     tindex=-1
     allocate(tSeriesInt(cfio%tSteps))
     call getDateTimeVec(cfio%fid,begDate,begTime,tSeriesInt,_RC)
     do i=1,cfio%tSteps
        iCurrInterval = tSeriesInt(i)
        call GetDate ( begDate, begTime, iCurrInterval, nymdB, nhmsB, status )
        call MAPL_UnpackTime(nymdB,iyr,imm,idd)
        call MAPL_UnpackTime(nhmsB,ihr,imn,isc)
        call ESMF_TimeSet(ctime, yy=iyr, mm=imm, dd=idd,  h=ihr,  m=imn, s=isc,_RC)
        if (ctime == time) tindex =i
     enddo
     deallocate(tSeriesInt)
     _ASSERT(tindex/=-1, 'tindex should not be -1')
     _RETURN(ESMF_SUCCESS)
  end subroutine GetTIndex
Call graph
gettindex calls ESMF_TimeSet, getdate, mapl_assert, mapl_unpacktime, getdatetimevec, mapl_return, mapl_verify
getdate calls getdateint4, getdateint8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_unpacktime calls mapl_unpacktime
getdatetimevec calls getdate, nf90_get_att, nf90_get_var, nf90_inq_varid, nf90_inquire, nf90_inquire_dimension, nf90_inquire_variable, err, identifydim, parsetimeunits
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
getdateint4 calls getdateint8
getdateint8 calls caldat, cfio_parseinttime, julday
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_cfioreadparallel_ calls gettindex
mapl_cfioreadparallel calls mapl_cfioreadparallel_