getVM – MAPL
getVM Function
6 statements
Source File
private function getVM(this) result(vm)
Type Bound
ESMF_TestCase
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestCase), intent(in) :: this
Return Value type(ESMF_VM)
Calls
Called by
Source Code
   function getVM(this) result(vm)
      class (ESMF_TestCase), intent(in) :: this
      type (ESMF_VM) :: vm
      integer :: rc
      call ESMF_GridCompGet(this%gc, VM=vm, rc=rc)
   end function getVM
Call graph
getvm calls ESMF_GridCompGet
barrier calls getvm
getlocalpet calls getvm
getpetcount calls getvm
test_main calls getvm
test_one calls getvm
setup calls barrier, getlocalpet
test_centers calls getlocalpet
test_corners calls getlocalpet
test_make_arbitrary_decomposition calls getpetcount
test_shape calls getlocalpet