get – MAPL
get Function
26 statements
Source File
private function get(this, request_id, local_reference, rc) result(handle)
Type Bound
MockSocket
Arguments
Type Intent Optional Attributes Name
class(MockSocket), intent(inout), target :: this
integer, intent(in) :: request_id
class(AbstractDataReference), intent(in) :: local_reference
integer, intent(out), optional :: rc
Return Value class(AbstractRequestHandle), allocatable
Calls
Source Code
   function get(this, request_id, local_reference, rc) result(handle)
      class (AbstractRequestHandle), allocatable :: handle
      class (MockSocket), target, intent(inout) :: this
      integer, intent(in) :: request_id
      class (AbstractDataReference), intent(in) :: local_reference
      integer, optional, intent(out) :: rc
      real(kind=REAL32), pointer :: values_0d
      real(kind=REAL32), pointer :: values_1d(:)
      !real(kind=REAL32), pointer :: values_2d(:,:)
      call this%prefix('get()')
      allocate(handle, source=MockHandle(this))
      this%log%counter = this%log%counter + 1
      select case (this%log%counter)
      case (1)
         call c_f_pointer(local_reference%base_address, values_0d)
         values_0d = this%q1
      case (2)
         call c_f_pointer(local_reference%base_address, values_1d, shape=local_reference%shape)
         values_1d = this%q2
      end select
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(request_id)
   end function get
Call graph
get calls mapl_return, prefix
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize