get – MAPL
get Function
12 statements
Source File
private function get(this, request_id, local_reference, rc) result(handle)
Type Bound
SimpleSocket
Arguments
Type Intent Optional Attributes Name
class(SimpleSocket), intent(inout), target :: this
integer, intent(in) :: request_id
class(AbstractDataReference), intent(in) :: local_reference
integer, intent(out), optional :: rc
Return Value class(AbstractRequestHandle), allocatable
Calls
Contents
Source Code
get
Source Code
   function get(this, request_id, local_reference, rc) result(handle)
      class (AbstractRequestHandle), allocatable :: handle
      class (SimpleSocket), target, intent(inout) :: this
      class (AbstractDataReference), intent(in) :: local_reference
      integer, intent(in) :: request_id
      integer, optional, intent(out) :: rc
      allocate(handle, source=SimpleHandle(local_reference))
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(request_id)
   end function get
Call graph
get calls simplehandle, mapl_return
simplehandle calls new_simplehandle
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize