get – MAPL
get Function
21 statements
Source File
private function get(this, request_id, local_reference, rc) result(handle)
Type Bound
MpiSocket
Arguments
Type Intent Optional Attributes Name
class(MpiSocket), intent(inout), target :: this
integer, intent(in) :: request_id
class(AbstractDataReference), intent(in) :: local_reference
integer, intent(out), optional :: rc
Return Value class(AbstractRequestHandle), allocatable
Calls
Contents
Source Code
get
Source Code
   function get(this, request_id, local_reference, rc) result(handle)
      class (AbstractRequestHandle), allocatable :: handle
      class (MpiSocket), target, intent(inout) :: this
      integer, intent(in) :: request_id
      class (AbstractDataReference), intent(in) :: local_reference
      integer, optional, intent(out) :: rc
      integer :: tag
      integer :: ierror
      integer :: request
      integer, pointer :: data(:)
      integer :: n_words
      tag = make_tag(request_id)
      n_words = product(local_reference%shape) * word_size(local_reference%type_kind)
      call c_f_pointer(local_reference%base_address, data, shape=[n_words])
      if (n_words ==0) allocate(data(1))
      call MPI_Irecv(data, n_words, MPI_INTEGER, this%pair_remote_rank, tag, this%pair_comm, request, ierror)
      allocate(handle, source=MpiRequestHandle(local_reference, request))
      if (n_words ==0) deallocate(data)
      _RETURN(_SUCCESS)
   end function get
Call graph
get calls mpirequesthandle, mpi_irecv, make_tag, mapl_return, word_size
mpirequesthandle calls new_mpirequesthandle
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception