GRIDINDEX – MAPL
GRIDINDEX Function
21 statements
Source File
private function GRIDINDEX(Stream, Grid, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStreamType), intent(in) :: Stream
type(ESMF_Grid), intent(in) :: Grid
integer, intent(out), optional :: RC
Return Value integer
Calls
Called by
Source Code
integer function GRIDINDEX(STREAM,GRID,RC)
  type(MAPL_LocStreamType),      intent(IN ) :: Stream
  type(ESMF_Grid),               intent(IN ) :: Grid
  integer, optional,             intent(OUT) :: RC
  integer                    :: STATUS
  integer                    :: N
  character(len=MAPL_TileNameLength) :: NAME
! Find the given grid among the allowed grids
!--------------------------------------------
  call ESMF_GridGet(GRID, NAME=NAME, RC=STATUS)
  _VERIFY(STATUS)
  GridIndex = 0
  do N=1,STREAM%N_GRIDS
     if(STREAM%TILING(N)%NAME==NAME) then
        GridIndex = N
        exit
     end if
  end do
  if (trim(name)=="CATCHMENT_GRID") GridIndex=2
  _ASSERT(GridIndex/=0,'needs informative message')
  _RETURN(ESMF_SUCCESS)
end function GRIDINDEX
Call graph
gridindex calls ESMF_GridGet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_locstreamattachgrid calls gridindex
mapl_locstreamcreatefromfile calls mapl_locstreamattachgrid
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize calls mapl_locstreamcreate
initialize_ calls mapl_locstreamcreate