halo – MAPL
halo Subroutine
119 statements
Source File
private subroutine halo(this, array, unusable, halo_width, rc)
Uses
MAPL_CommsMod
Type Bound
LatLonGridFactory
Arguments
Type Intent Optional Attributes Name
class(LatLonGridFactory), intent(inout) :: this
real(kind=REAL32), intent(inout) :: array(:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: halo_width
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine halo(this, array, unusable, halo_width, rc)
      use MAPL_CommsMod
      class (LatLonGridFactory), intent(inout) :: this
      real(kind=REAL32), intent(inout) :: array(:,:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: halo_width
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: pet_north
      integer :: pet_south
      integer :: pet_east
      integer :: pet_west
      integer :: pet_N_E, pet_N_W, pet_S_E, pet_S_W
      integer :: last_lon, last_lat
      _UNUSED_DUMMY(unusable)
      ! not yet implmented, default is 1
      _UNUSED_DUMMY(halo_width)
      if (.not. this%is_halo_initialized) then
         call this%init_halo(rc=status)
         _VERIFY(status)
      end if
      last_lon = size(array,1)
      last_lat = size(array,2)
      associate (nx => this%nx, ny => this% ny, px => this%px, py => this%py)
        ! Nearest neighbors processor' ids
        pet_north = get_pet(px, py+1, nx, ny)
        pet_south = get_pet(px, py-1, nx, ny)
        pet_east  = get_pet(px+1, py, nx, ny)
        pet_west  = get_pet(px-1, py, nx, ny)
        call fill_north(array, rc=status)
        _VERIFY(status)
        call fill_south(array, rc=status)
        _VERIFY(status)
        call fill_east(array, rc=status)
        _VERIFY(status)
        call fill_west(array, rc=status)
        _VERIFY(status)
        pet_N_E   = get_pet(px+1, py+1, nx, ny)
        pet_N_W   = get_pet(px-1, py+1, nx, ny)
        pet_S_E   = get_pet(px+1, py-1, nx, ny)
        pet_S_W   = get_pet(px-1, py-1, nx, ny)
        !fill north east
        call MAPL_CommsSendRecv(this%layout,              &
              array(2,      2         ), 1,  pet_S_W,  &
              array(last_lon,last_lat ), 1,  pet_N_E,  &
              rc=status)
        _VERIFY(status)
        !fill north west
        call MAPL_CommsSendRecv(this%layout,              &
              array(last_lon-1, 2), 1,  pet_S_E,  &
              array(1,   last_lat), 1,  pet_N_W,  &
              rc=status)
        _VERIFY(status)
        ! north pol corner
        if(this%py== this%ny-1) then
           array(last_lon,last_lat) = array(last_lon-1,last_lat-1)
           array(1,last_lat)        = array(2,last_lat-1)
        endif
        !fill south east
        call MAPL_CommsSendRecv(this%layout,              &
              array(2, last_lat-1), 1,  pet_N_W,  &
              array(last_lon,1),    1,  pet_S_E,  &
              rc=status)
        _VERIFY(status)
        !fill south west
        call MAPL_CommsSendRecv(this%layout,              &
              array(last_lon-1,last_lat-1), 1,  pet_N_E,  &
              array(1,1                  ), 1,  pet_S_W,  &
              rc=status)
        _VERIFY(status)
        ! south pole corner
        if(this%py==0) then
           array(last_lon,1   ) = array(last_lon-1,2 )
           array(1,1   )        = array(2,2 )
        endif
      end associate
      _RETURN(ESMF_SUCCESS)
   contains
      integer function get_pet(px, py, nx, ny) result(pet)
         integer, intent(in) :: px, py  ! rank in x/y directions
         integer, intent(in) :: nx, ny  ! npets in x/y directions
         pet = mod(px+nx,nx) + nx*mod(py+ny,ny)
      end function get_pet
      subroutine fill_north(array, rc)
         real(kind=REAL32), intent(inout) :: array(:,:)
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: len, last
         last = size(array,2)-1
         len = size(array,1)
         call MAPL_CommsSendRecv(this%layout,        &
              array(:,2        ),  len,  pet_south,  &
              array(:,last+1   ),  len,  pet_north,  &
              rc=status)
         _VERIFY(status)
         if(this%py==this%ny-1) then
            array(:,last+1   ) = array(:,last )
         end if
         _RETURN(_SUCCESS)
      end subroutine fill_north
      subroutine fill_south(array, rc)
         real(kind=REAL32), intent(inout) :: array(:,:)
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: len, last
         last = size(array,2)-1
         len = size(array,1)
         call MAPL_CommsSendRecv(this%layout,     &
              array(:,last     ),  len,  pet_north,  &
              array(:,1        ),  len,  pet_south,  &
              rc=status)
         _VERIFY(status)
         if(this%py==0) then
            array(:,1   ) = array(:,2 )
         endif
         _RETURN(_SUCCESS)
      end subroutine fill_south
      subroutine fill_east(array, rc)
         real(kind=REAL32), intent(inout) :: array(:,:)
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: len, last
         last = size(array,1)-1
         len = size(array,2)
         call MAPL_CommsSendRecv(this%layout,      &
              array(2     , : ),  len,  pet_west,  &
              array(last+1, : ),  len,  pet_east,  &
              rc=status)
         _VERIFY(status)
         _RETURN(_SUCCESS)
      end subroutine fill_east
      subroutine fill_west(array, rc)
         real(kind=REAL32), intent(inout) :: array(:,:)
         integer, optional, intent(out) :: rc
         integer :: status
         integer :: len, last
         last = size(array,1)-1
         len = size(array,2)
         call MAPL_CommsSendRecv(this%layout,   &
              array(last  , : ),  len,  pet_east,  &
              array(1     , : ),  len,  pet_west,  &
              rc=status)
         _VERIFY(status)
         _RETURN(_SUCCESS)
      end subroutine fill_west
   end subroutine halo
Call graph
halo calls mapl_commssendrecv, init_halo, mapl_return, mapl_verify
mapl_commssendrecv calls mapl_commssendrecv_i4_0, mapl_commssendrecv_r4_0, mapl_commssendrecv_r4_1, mapl_commssendrecv_r4_2, mapl_commssendrecv_r8_1, mapl_commssendrecv_r8_2
init_halo calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, get_grid
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_grid calls mapl_return
mapl_commssendrecv_i4_0 calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv
mapl_commssendrecv_r4_0 calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv
mapl_commssendrecv_r4_1 calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv
mapl_commssendrecv_r4_2 calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv
mapl_commssendrecv_r8_1 calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv
mapl_commssendrecv_r8_2 calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv
mapl_throw_exception calls initialize