halo – MAPL
halo Subroutine
9 statements
Source File
private subroutine halo(this, array, unusable, halo_width, rc)
Uses
MAPL_CommsMod
Type Bound
SwathGridFactory
Arguments
Type Intent Optional Attributes Name
class(SwathGridFactory), intent(inout) :: this
real(kind=REAL32), intent(inout) :: array(:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: halo_width
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine halo(this, array, unusable, halo_width, rc)
      use MAPL_CommsMod
      class (SwathGridFactory), intent(inout) :: this
      real(kind=REAL32), intent(inout) :: array(:,:)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: halo_width
      integer, optional, intent(out) :: rc
      _FAIL( 'Stop: subroutine halo is not needed for SwathGridFactory')
   end subroutine halo
Call graph
halo calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize