handle_CollectiveStageData – MAPL
handle_CollectiveStageData Subroutine
20 statements
Source File
private subroutine handle_CollectiveStageData(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(CollectiveStageDataMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine handle_CollectiveStageData(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (CollectiveStageDataMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      class(AbstractSocket),pointer :: connection
      type(LocalMemReference), target :: mem_data_reference
      type(DummyMessage) :: handshake_msg
      integer :: status
      class(AbstractRequestHandle), allocatable :: handle
      connection => this%get_connection()
      call connection%send(handshake_msg,_RC)
      call this%request_backlog%push_back(message)
      mem_data_reference = LocalMemReference(message%type_kind,message%count)
      !iRecv
      handle = connection%get(message%request_id, mem_data_reference)
      call this%insert_RequestHandle(message%request_id, handle, _RC)
      _RETURN(_SUCCESS)
   end subroutine handle_CollectiveStageData
Call graph
handle_collectivestagedata calls get, get_connection, insert_requesthandle, mapl_return, mapl_verify, v_push_back, send
get_connection calls mapl_return, mapl_assert
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_resize_32 calls resize