handle_Done_stage – MAPL
handle_Done_stage Subroutine
33 statements
Source File
private recursive subroutine handle_Done_stage(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(StageDoneMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Contents
Source Code
handle_Done_stage
Source Code
   recursive subroutine handle_Done_stage(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (StageDoneMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      type (MessageVectorIterator) :: iter
      class (AbstractMessage), pointer :: msg
      class (AbstractRequestHandle), pointer :: handle
      integer :: status
      _UNUSED_DUMMY(message)
      if ( this%request_backlog%empty()) then
         _RETURN(_SUCCESS)
      endif
      iter = this%request_backlog%begin()
      do while ( iter /= this%request_backlog%end())
         msg => iter%get()
         select type (q=>msg)
         type is (StageDataMessage)
            handle => this%get_RequestHandle(q%request_id)
            call handle%wait()
            call this%put_DataToFile(q,handle%data_reference%base_address,rc=status)
            _VERIFY(status)
            call this%request_backlog%erase(iter)
         class default
            _FAIL( "Wrong message type")
         end select
         iter = this%request_backlog%begin()
     enddo
     call this%clear_RequestHandle()
     call this%clear_hist_collections()
     _RETURN(_SUCCESS)
   end subroutine handle_Done_stage
Call graph
handle_done_stage calls clear_requesthandle, get, get_requesthandle, mapl_assert, clear_hist_collections, mapl_return, mapl_verify, put_datatofile
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
clear_hist_collections calls clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_datatofile calls mapl_assert, mapl_return, mapl_verify, find, put_var
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize