handle_AddExtCollection – MAPL
handle_AddExtCollection Subroutine
34 statements
Source File
private subroutine handle_AddExtCollection(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(AddExtCollectionMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine handle_AddExtCollection(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (AddExtCollectionMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      integer :: n, status
      logical :: found
      type (ExtCollectionVectorIterator) :: iter
      type (ExtDataCollection), pointer :: collection
      type (ExtDataCollection) :: c
      class(AbstractSocket),pointer :: connection
      if (associated(ioserver_profiler)) call ioserver_profiler%start("add_Extcollection")
      iter = this%ext_collections%begin()
      n = 1
      ! Is it a new collection?
      found = .false.
      do while (iter /= this%ext_collections%end())
         collection => iter%get()
         if (message%template == collection%template) then
            found = .true.
            exit
         end if
         n = n + 1
         call iter%next()
      end do
      if (.not. found) then
         c = new_ExtDataCollection(message%template)
         call this%ext_collections%push_back(c)
      end if
      connection=>this%get_connection()
      call connection%send(IdMessage(n),_RC)
      if (associated(ioserver_profiler)) call ioserver_profiler%stop("add_Extcollection")
      _RETURN(_SUCCESS)
   end subroutine handle_AddExtCollection
Call graph
handle_addextcollection calls start, get_connection, mapl_return, mapl_verify, new_extdatacollection, v_begin, v_iter_get, v_iter_next, v_push_back, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
v_grow_to calls v_capacity, v_set_capacity
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_resize_32 calls resize