handle_AddHistCollection – MAPL
handle_AddHistCollection Subroutine
18 statements
Source File
private subroutine handle_AddHistCollection(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(AddHistCollectionMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine handle_AddHistCollection(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (AddHistCollectionMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      integer :: n, status
      type (HistoryCollection) :: hist_collection
      class(AbstractSocket),pointer :: connection
      if (associated(ioserver_profiler)) call ioserver_profiler%start("add_Histcollection")
      n = this%hist_collections%size()+1
      hist_collection = HistoryCollection(message%fmd)
      call this%hist_collections%push_back(hist_collection)
      connection=>this%get_connection()
      call connection%send(IdMessage(n),_RC)
      if (associated(ioserver_profiler)) call ioserver_profiler%stop("add_Histcollection")
      _RETURN(_SUCCESS)
   end subroutine handle_AddHistCollection
Call graph
handle_addhistcollection calls start, get_connection, mapl_return, mapl_verify, v_push_back, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
v_grow_to calls v_capacity, v_set_capacity
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_resize_32 calls resize