handle_AddHistCollection – MAPL
handle_AddHistCollection Subroutine
14 statements
Source File
private subroutine handle_AddHistCollection(this, message, rc)
Type Bound
MessageVisitor
Arguments
Type Intent Optional Attributes Name
class(MessageVisitor), intent(inout), target :: this
type(AddHistCollectionMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine handle_AddHistCollection(this, message, rc)
      class (MessageVisitor), target, intent(inout) :: this
      type (AddHistCollectionMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      _FAIL( "Warning : dummy handle_AddHistCollection should not be called")
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(message)
   end subroutine handle_AddHistCollection
Call graph
handle_addhistcollection calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
handle calls handle_addhistcollection