handle_ModifyMetadata – MAPL
handle_ModifyMetadata Subroutine
16 statements
Source File
private subroutine handle_ModifyMetadata(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(ModifyMetadataMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine handle_ModifyMetadata(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (ModifyMetadataMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      type (HistoryCollection),pointer :: hist_collection
      class(AbstractSocket),pointer :: connection
      type (DummyMessage) :: handshake_msg
      integer :: status
      hist_collection=>this%hist_collections%at(message%collection_id)
      call hist_collection%ModifyMetadata(message%var_map)
      connection=>this%get_connection()
      call connection%send(handshake_msg,_RC)
      _RETURN(_SUCCESS)
   end subroutine handle_ModifyMetadata
Call graph
handle_modifymetadata calls at, get_connection, mapl_return, mapl_verify, modifymetadata, send
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modifymetadata calls mapl_return, mapl_verify, m_begin, m_key, m_next, modify_variable
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
m_begin calls s_begin
m_next calls s_next
mapl_throw_exception calls initialize
modify_variable calls mapl_return, mapl_assert, at, begin, get, next, get_dimensions, m_set
v_at_32 calls v_at_size_kind
m_set calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
s_begin calls s_next
s_next calls advpos