handle_CollectiveStageData – MAPL
handle_CollectiveStageData Subroutine
20 statements
Source File
private subroutine handle_CollectiveStageData(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(CollectiveStageDataMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Contents
Source Code
handle_CollectiveStageData
Source Code
   subroutine handle_CollectiveStageData(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (CollectiveStageDataMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      class(AbstractSocket),pointer :: connection
      type(LocalMemReference), target :: mem_data_reference
      type(DummyMessage) :: handshake_msg
      integer :: status
      class(AbstractRequestHandle), allocatable :: handle
      connection => this%get_connection()
      call connection%send(handshake_msg,_RC)
      call this%request_backlog%push_back(message)
      mem_data_reference = LocalMemReference(message%type_kind,message%count)
      !iRecv
      handle = connection%get(message%request_id, mem_data_reference)
      call this%insert_RequestHandle(message%request_id, handle, _RC)
      _RETURN(_SUCCESS)
   end subroutine handle_CollectiveStageData
Call graph
handle_collectivestagedata calls get, get_connection, insert_requesthandle, mapl_return, mapl_verify, send
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize