handle_Done_collective_stage – MAPL
handle_Done_collective_stage Subroutine
25 statements
Source File
private recursive subroutine handle_Done_collective_stage(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(CollectiveStageDoneMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
  recursive subroutine handle_Done_collective_stage(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (CollectiveStageDoneMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      integer :: status
      this%containing_server%serverthread_done_msgs(this%thread_rank) = .true.
      if ( .not. all(this%containing_server%serverthread_done_msgs)) then
         _RETURN(_SUCCESS)
      endif
      _ASSERT( associated(this%containing_server), "need server")
      call this%containing_server%create_remote_win(_RC)
      call this%containing_server%receive_output_data(_RC)
      call this%containing_server%put_dataToFile(_RC)
      call this%containing_server%clean_up()
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(message)
   end subroutine handle_Done_collective_stage
Call graph
handle_done_collective_stage calls create_remote_win, mapl_assert, clean_up, mapl_return, mapl_verify, put_datatofile, receive_output_data
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
clean_up calls mapl_return, mapl_verify, begin, clear_RequestHandle, erase, start, clear_datareference, set_allbacklogisempty
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_datatofile calls mapl_assert
receive_output_data calls mapl_assert
clear_datareference calls at, erase, v_begin
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
start_self calls mapl_assert, mapl_return, start, get_name