handle_Done_collective_prefetch – MAPL
handle_Done_collective_prefetch Subroutine
32 statements
Source File
private recursive subroutine handle_Done_collective_prefetch(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(CollectivePrefetchDoneMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Contents
Source Code
handle_Done_collective_prefetch
Source Code
   recursive subroutine handle_Done_collective_prefetch(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (CollectivePrefetchDoneMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      class(AbstractDataReference),pointer :: dataRefPtr
      integer :: status
      ! first time handling the "Done" message, simple return
      this%containing_server%serverthread_done_msgs(this%thread_rank) = .true.
      if ( .not. all(this%containing_server%serverthread_done_msgs)) then
         _RETURN(_SUCCESS)
      endif
      if( .not. multi_data_read) then
        ! each node read part of a file, then exchange
         if (associated(ioserver_profiler)) call ioserver_profiler%start("read_gather")
         dataRefPtr=> this%read_and_gather(rc=status)
         _VERIFY(status)
         if (associated(ioserver_profiler)) call ioserver_profiler%stop("read_gather")
      else
         if (associated(ioserver_profiler)) call ioserver_profiler%start("read_share")
         dataRefPtr=> this%read_and_share(rc=status)
         _VERIFY(status)
         if (associated(ioserver_profiler)) call ioserver_profiler%stop("read_share")
      endif
      if (associated(ioserver_profiler)) call ioserver_profiler%start("send_data")
      ! now dataRefPtr on each node has all the data
      call this%containing_server%add_DataReference(dataRefPtr)
      call this%containing_server%get_DataFromMem(multi_data_read, _RC)
      if (associated(ioserver_profiler)) call ioserver_profiler%stop("send_data")
      call this%containing_server%clean_up()
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(message)
   end subroutine handle_Done_collective_prefetch
Call graph
handle_done_collective_prefetch calls mapl_return, mapl_verify, read_and_gather, read_and_share
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
read_and_gather calls mapl_return, mapl_verify, fence, get, mpi_allgatherv, next, get_datafromfile, i_to_string, word_size, stringinteger64map
read_and_share calls mapl_return, mapl_verify, fence, get, next, get_datafromfile, i_to_string, word_size, stringinteger64map
get_datafromfile calls mapl_return, mapl_verify, find, get_var, mapl_assert
get_error_message calls at
i_to_string calls mapl_return, mapl_assert
mapl_throw_exception calls initialize
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code