handle_Terminate – MAPL
handle_Terminate Subroutine
10 statements
Source File
private subroutine handle_Terminate(this, message, rc)
Type Bound
MockServerThread
Arguments
Type Intent Optional Attributes Name
class(MockServerThread), intent(inout) :: this
type(TerminateMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Contents
Source Code
handle_Terminate
Source Code
   subroutine handle_Terminate(this, message, rc)
      class (MockServerThread), intent(inout) :: this
      type (TerminateMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(message)
      call this%prefix('handle_Terminate()')
      call this%set_terminate()
      _RETURN(_SUCCESS)
   end subroutine handle_Terminate
Call graph
handle_terminate calls mapl_return, prefix, set_terminate
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize