handle_Done_prefetch – MAPL
handle_Done_prefetch Subroutine
34 statements
Source File
private recursive subroutine handle_Done_prefetch(this, message, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout), target :: this
type(PrefetchDoneMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Source Code
   recursive subroutine handle_Done_prefetch(this, message, rc)
      class (ServerThread), target, intent(inout) :: this
      type (PrefetchDoneMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      type (LocalMemReference) :: mem_data_reference
      type (MessageVectorIterator) :: iter
      class (AbstractMessage), pointer :: msg
      class(AbstractSocket),pointer :: connection
      integer :: status
      iter = this%request_backlog%begin()
      do while ( iter /= this%request_backlog%end())
         msg => iter%get()
         connection=>this%get_connection(status)
         _VERIFY(status)
         select type (q=>msg)
         type is (PrefetchDataMessage)
             mem_data_reference=LocalMemReference(q%type_kind,q%count)
             call this%get_DataFromFile(q,mem_data_reference%base_address, _RC)
             call this%insert_RequestHandle(q%request_id, &
              & connection%put(q%request_id, mem_data_reference))
             call this%request_backlog%erase(iter)
         class default
            _FAIL( "Wrong message type")
         end select
         iter = this%request_backlog%begin()
       enddo
       call this%clear_RequestHandle()
       _RETURN(_SUCCESS)
       _UNUSED_DUMMY(message)
   end subroutine handle_Done_prefetch
Call graph
handle_done_prefetch calls mapl_assert, erase, clear_requesthandle, get_connection, get_datafromfile, insert_requesthandle, mapl_return, mapl_verify, v_begin, v_iter_get, put
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
clear_requesthandle calls mapl_return, mapl_verify, erase, m_begin
get_connection calls mapl_assert, mapl_return
get_datafromfile calls mapl_assert, mapl_return, mapl_verify, at, get_var, find
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception