handle_Done_prefetch – MAPL
handle_Done_prefetch Subroutine
9 statements
Source File
private subroutine handle_Done_prefetch(this, message, rc)
Type Bound
MockServerThread
Arguments
Type Intent Optional Attributes Name
class(MockServerThread), intent(inout), target :: this
type(PrefetchDoneMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Contents
Source Code
handle_Done_prefetch
Source Code
   subroutine handle_Done_prefetch(this, message, rc)
      class (MockServerThread), target, intent(inout) :: this
      type (PrefetchDoneMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(message)
      call this%prefix('handle_Done_prefetch()')
      _RETURN(_SUCCESS)
   end subroutine handle_Done_prefetch
Call graph
handle_done_prefetch calls mapl_return, prefix
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize