handle – MAPL
handle Subroutine
62 statements
Source File
private recursive subroutine handle(this, message, rc)
Type Bound
MessageVisitor
Arguments
Type Intent Optional Attributes Name
class(MessageVisitor), intent(inout), target :: this
class(AbstractMessage), intent(in), target :: message
integer, intent(out), optional :: rc
Calls
Source Code
   recursive subroutine handle(this, message, rc)
      class (MessageVisitor), target, intent(inout) :: this
      class (AbstractMessage), target, intent(in) :: message
      integer, optional, intent(out) :: rc
      integer :: status
      select type (cmd => message)
      type is (TerminateMessage)
        call this%handle_terminate(cmd, rc=status)
        _VERIFY(status)
      type is (DoneMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (PrefetchDoneMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (CollectivePrefetchDoneMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (StageDoneMessage)
         call this%handle_cmd(cmd,_RC)
      type is (CollectiveStageDoneMessage)
          call this%handle_cmd(cmd,_RC)
      type is (AddExtCollectionMessage)
        call this%handle_AddExtCollection(cmd,rc=status)
        _VERIFY(status)
      type is (AddHistCollectionMessage)
        call this%handle_AddHistCollection(cmd,rc=status)
        _VERIFY(status)
      type is (IdMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (PrefetchDataMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (CollectivePrefetchDataMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (StageDataMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (CollectiveStageDataMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (ModifyMetadataMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (ReplaceMetadataMessage)
        call this%handle_cmd(cmd,rc=status)
        _VERIFY(status)
      type is (HandShakeMessage)
        ! the handShake is from client to server
        call this%handle_cmd(cmd, rc=status)
        _VERIFY(status)
      type is (DummyMessage)
        ! WY notes: self hand_shake: if iserver or oserver is with app"
        ! the dummy is from server to client
        ! if the serverthread sends the dummy directly to clientthread, it will not go through here.
        _VERIFY(0)
      class default
         _FAIL( 'unsupported subclass')
      end select
      _RETURN(_SUCCESS)
   end subroutine handle
Call graph
handle calls mapl_assert, handle_cmd, handle_addextcollection, handle_addhistcollection, handle_terminate, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
handle_addextcollection calls mapl_assert
handle_addhistcollection calls mapl_assert
handle_terminate calls mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
handle_handshake calls mapl_assert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize