has_dimension – MAPL
has_dimension Function
16 statements
Source File
private function has_dimension(this, dim_name, unusable, rc) result(isPresent)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: dim_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function has_dimension(this, dim_name, unusable, rc) result(isPresent)
      class (FileMetadata), target, intent(in) :: this
      character(len=*), intent(in) :: dim_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (StringIntegerMapIterator) :: iter
      logical :: isPresent
      iter = this%dimensions%find(dim_name)
      isPresent = (iter /=this%dimensions%end())
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function has_dimension
Call graph
has_dimension calls find, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
generate_file_bounds calls has_dimension
generate_file_reference3d calls has_dimension
initialize_from_file_metadata calls has_dimension
make_factory_from_file calls has_dimension