has_rule_for – MAPL
has_rule_for Function
24 statements
Source File
private function has_rule_for(This, base_name, rc) result(found_rule)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(inout) :: This
character(len=*), intent(in) :: base_name
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Call graph
has_rule_for calls m_begin, m_key, m_next, mapl_return
m_begin calls s_begin
m_next calls s_next
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_extra_derived_items calls has_rule_for
initialize_ calls get_extra_derived_items