has_attribute – MAPL
has_attribute Function
5 statements
Source File
private function has_attribute(this, attr_name)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(in), target :: this
character(len=*), intent(in) :: attr_name
Return Value logical
Calls
Called by
Source Code
   logical function has_attribute(this, attr_name)
      class (FileMetadata), target, intent(in) :: this
      character(len=*), intent(in) :: attr_name
      has_attribute = this%global_var%is_attribute_present(attr_name)
   end function has_attribute
Call graph
has_attribute calls is_attribute_present
is_attribute_present calls m_at, mapl_return
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize
compare_grid_file calls has_attribute
initialize_from_file_metadata calls has_attribute
make_factory_from_file calls has_attribute
mapl_bundlereadncpar calls compare_grid_file
mapl_varreadncpar calls mapl_bundlereadncpar
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_statevarreadncpar calls mapl_varreadncpar