HistoryTrajectory_from_config – MAPL
HistoryTrajectory_from_config Module Procedure
249 statements
Source File
module procedure HistoryTrajectory_from_config module function HistoryTrajectory_from_config(config, string, clock, GENSTATE, rc) result(traj) Interface →
Uses
BinIOMod
MAPL_scan_pattern_in_file
pflogger
write(6,) ‘nline, col’, nline, col write(6,) ‘line’, i, ‘ncol(i)’, ncol(i) if (mapl_am_i_root()) then do k=1, nobs do j=1, traj%obs(k)%ngeoval write(6, ‘(2x,a,2x,2i10,2x,a)’) & ‘traj%obs(k)%geoval_xname(j), k, j, xname ‘, k, j, trim(traj%obs(k)%geoval_xname(j)) end do end do end if
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: string
type(ESMF_Clock), intent(in) :: clock
type(MAPL_MetaComp), intent(in), optional, pointer :: GENSTATE
integer, intent(out), optional :: rc
Return Value type(HistoryTrajectory)
Calls
Call graph
historytrajectory_from_config calls ESMF_AlarmCreate, ESMF_ClockGet, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigGetDim, ESMF_ConfigGetLen, ESMF_ConfigNextLine, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, hms_2_s, mapl_am_i_root, mapl_assert, get_logger, convert_twostring_2_esmfinterval, debug, extract_unquoted_item, mapl_return, mapl_verify, split_string_by_seperator
hms_2_s calls hms_2_s
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_twostring_2_esmfinterval calls ESMF_TimeIntervalSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
split_string_by_seperator calls split_string_by_space