i_to_string – MAPL
i_to_string Function
11 statements
Source File
public function i_to_string(count, rc) result(str)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: count
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Contents
Source Code
i_to_string
Source Code
   function i_to_string(count, rc) result(str)
      character(len=:), allocatable :: str
      integer, intent(in) :: count
      integer, optional, intent(out) :: rc
      character(len=9)    :: buffer
      _ASSERT( count <= 10**8, "too big to hold")
      write(buffer,'(i0)') count
      str = trim(buffer)
      _RETURN(_SUCCESS)
   end function i_to_string
Call graph
i_to_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
clean_up calls i_to_string, put_datatofile
create_remote_win calls i_to_string
get_datafrommem calls i_to_string
get_fname_by_face calls i_to_string
initialize calls i_to_string
put_datatofile calls i_to_string, put_datatofile
read_and_gather calls i_to_string
read_and_share calls i_to_string
receive_output_data calls i_to_string
run calls i_to_string
to_string calls i_to_string
main calls i_to_string
handle_done_collective_prefetch calls read_and_gather, read_and_share
mapl_bundlereadncpar calls get_fname_by_face
mapl_bundlewritencpar calls get_fname_by_face
mapl_esmfstatereadfromfile calls get_fname_by_face
mapl_statevarreadncpar calls get_fname_by_face
mapl_varreadncpar calls mapl_bundlereadncpar, mapl_statevarreadncpar
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarwritencpar calls mapl_bundlewritencpar