identity_regridder – MAPL
identity_regridder Function
9 statements
Source File
public function identity_regridder() result(regridder)
Uses
ESMF
Arguments
None
Return Value type(IdentityRegridder), pointer
Calls
Called by
Source Code
   function identity_regridder() result(regridder)
      use ESMF
      type (IdentityRegridder), pointer :: regridder
      type (RegridderSpec) :: spec
      regridder => singleton
      ! Due to how MAPL is set up, the default regrid_method is
      ! bilinear. But if an identity regridder is requested, we
      ! want to reflect that in the metadata by updating the spec.
      spec = regridder%get_spec()
      spec%regrid_method = REGRID_METHOD_IDENTITY
      call regridder%set_spec(spec)
    end function identity_regridder
Call graph
identity_regridder calls get_spec, set_spec
make_regridder_ calls identity_regridder
make_regridder_from_grids calls identity_regridder
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
request_data_from_file calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
create_from_bundle calls createfilemetadata
initialize calls create_bundle_rh, createfilemetadata
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run calls create_bundle_rh, createfilemetadata