ijsearch – MAPL
ijsearch Function
47 statements
Source File
private function ijsearch(coords, idim, value, periodic)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: coords(idim)
integer, intent(in) :: idim
real, intent(inout) :: value
logical, intent(in) :: periodic
Return Value integer
Called by
Contents
Call graph
orb_mask_lonlat calls ijsearch
orb_mask_xy calls ijsearch
orb_swath_mask_xy calls ijsearch
orb_swath_mask_lonlat calls ijsearch
domasking_ calls orb_mask_lonlat, orb_swath_mask_lonlat
domasking_cs calls orb_mask_xy, orb_swath_mask_xy
run_ calls domasking_, domasking_cs