info – MAPL
info Subroutine
35 statements
Source File
private subroutine info(this, message, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, unusable, extra, line, file, rc)
Type Bound
Logger
Arguments
Type Intent Optional Attributes Name
class(Logger), intent(inout), target :: this
character(len=*), intent(in) :: message
class(*), intent(in), optional :: arg1
class(*), intent(in), optional :: arg2
class(*), intent(in), optional :: arg3
class(*), intent(in), optional :: arg4
class(*), intent(in), optional :: arg5
class(*), intent(in), optional :: arg6
class(*), intent(in), optional :: arg7
class(*), intent(in), optional :: arg8
class(*), intent(in), optional :: arg9
class(KeywordEnforcer), intent(in), optional :: unusable
type(StringUnlimitedMap), intent(in), optional, target :: extra
integer, intent(in), optional :: line
character(len=*), intent(in), optional :: file
integer, intent(out), optional :: rc
Called by
Source Code
   subroutine info(this, message, ARG_LIST, unusable, extra, line, file, rc)
      class (Logger), target, intent(inout) :: this
      character(len=*), intent(in) :: message
      include 'recordOptArgs.inc'
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type (StringUnlimitedMap), optional, target, intent(in) :: extra
      integer, optional, intent(in) :: line
      character(*), optional, intent(in) :: file
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(message)
      _UNUSED_DUMMY(arg1)
      _UNUSED_DUMMY(arg2)
      _UNUSED_DUMMY(arg3)
      _UNUSED_DUMMY(arg4)
      _UNUSED_DUMMY(arg5)
      _UNUSED_DUMMY(arg6)
      _UNUSED_DUMMY(arg7)
      _UNUSED_DUMMY(arg8)
      _UNUSED_DUMMY(arg9)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(extra)
      _UNUSED_DUMMY(line)
      _UNUSED_DUMMY(file)
      _RETURN(_SUCCESS)
   end subroutine info
Call graph
getnodecomm calls info
getnoderootscomm calls info
initialize_ calls info
initialize_gc calls info, mapl_clockinit
iobundle_add_entry calls info
mapl_clockinit calls info
mapl_extdataextractintegers calls info
mapl_genericfinalize calls info
mapl_varspecprint1csv calls info
mapl_varspecprintone calls info
report_global_profiler calls info
run_model calls info
start_back calls info
updatebrackettime calls info
mapl_varspecprint calls mapl_varspecprintone
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_extdataevaluatemask calls mapl_extdataextractintegers
mapl_finalize calls report_global_profiler
mapl_varspecprintcsv calls mapl_varspecprint1csv
run_ calls updatebrackettime, iobundle_add_entry
run_member calls run_model
start calls start_back