init – MAPL
init Subroutine
36 statements
Source File
private subroutine init(message, request_id, collection_id, file_name, var_name, data_reference, unusable, start, rc)
Type Bound
AbstractDataMessage
Arguments
Type Intent Optional Attributes Name
class(AbstractDataMessage) :: message
integer, intent(in) :: request_id
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init(message,  &
        request_id, collection_id, file_name, var_name, &
        data_reference, unusable, start, rc)
      class (AbstractDataMessage) :: message
      integer, intent(in) :: request_id
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: start(:)
      integer, optional, intent(out) :: rc
      integer :: i,k
      message%request_id = request_id
      message%collection_id = collection_id
      message%file_name = file_name
      message%var_name = var_name
      message%type_kind= data_reference%type_kind
      message%count = data_reference%shape
      if (present(start)) then
         message%start = start
      else
         message%start = [(1,i=1,size(data_reference%shape))]
      end if
      k = size(message%start) - size(message%count)
      if ( k > 0 ) then
         message%count = [message%count,[(1,i=1,k)]]
      endif
      if ( k < 0 ) then
         message%start = [message%start,[(1,i=1,-k)]]
      endif
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine init
Call graph
init calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initcollective calls init
new_prefetchdatamessage calls init
new_stagedatamessage calls init
prefetchdatamessage calls new_prefetchdatamessage
stagedatamessage calls new_stagedatamessage
new_collectiveprefetchdatamessage calls initcollective
new_collectivestagedatamessage calls initcollective
collectiveprefetchdatamessage calls new_collectiveprefetchdatamessage
collectivestagedatamessage calls new_collectivestagedatamessage