Initialize_ – MAPL
Initialize_ Subroutine
108 statements
Source File
private subroutine Initialize_(GC, IMPORT, EXPORT, CLOCK, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: IMPORT
type(ESMF_State), intent(inout) :: EXPORT
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out) :: rc
Calls
Source Code
      SUBROUTINE Initialize_ ( GC, IMPORT, EXPORT, CLOCK, rc )
         implicit NONE
         type(ESMF_Clock),  intent(inout) :: CLOCK     ! The clock
         type(ESMF_GridComp), intent(inout) :: GC      ! Grid Component
         type(ESMF_State), intent(inout) :: IMPORT     ! Import State
         type(ESMF_State), intent(inout) :: EXPORT     ! Export State
         integer, intent(out)            :: rc         ! Error return code:
         type(ESMF_Config)           :: CF          ! Universal Config
         integer                     :: status
         character(len=ESMF_MAXSTR)  :: comp_name
         integer :: nrows, ncolumn,i
         type(ESMF_Grid) :: grid
         type(ESMF_Time) :: currTime
         type(SyntheticFieldSupportWrapper) :: synthWrap
         type(SyntheticFieldSupport), pointer :: synth => null()
         character(len=ESMF_MaxStr) :: key, keyVal
         type(MAPL_MetaComp), pointer :: MAPL
         logical :: isPresent, fill_bundle
         type(ESMF_State) :: internal
         call ESMF_GridCompGet( GC, name=comp_name, config=CF, _RC )
         call MAPL_GetObjectFromGC ( GC, MAPL, _RC )
         call ESMF_UserCompGetInternalState(gc,wrap_name,synthWrap,status)
         _VERIFY(status)
         synth => synthWrap%ptr
         call ESMF_ClockGet(Clock,currTime=currTime,_RC)
         synth%delay = -1.0
         call ESMF_ConfigFindLabel(cf,label='delay:',isPresent=isPresent,_RC)
         if (isPresent) then
            call ESMF_ConfigGetAttribute(cf,label='delay:',value=synth%delay,_RC)
         end if
         fill_bundle=.false.
         call ESMF_ConfigFIndLabel(cf,label='fill_bundle:',isPresent=isPresent,_RC)
         if (isPresent) then
            call ESMF_ConfigGetAttribute(cf,label='fill_bundle:',value=fill_bundle,_RC)
         end if
         call ESMF_ConfigGetDim(cf,nrows,ncolumn,label="FILL_DEF::",rc=status)
         if (status==ESMF_SUCCESS) then
            call ESMF_ConfigFindLabel(cf,label="FILL_DEF::",_RC)
            do i=1,nrows
               call ESMF_ConfigNextLine(cf,_RC)
               call ESMF_ConfigGetAttribute(cf,value=key,_RC)
               call ESMF_ConfigGetAttribute(cf,value=keyVal,_RC)
               call synth%fillDefs%insert(trim(key),trim(keyVal))
            enddo
         end if
         call synth%tFunc%init_time(cf,currTime,_RC)
         call ESMF_ConfigGetAttribute(cf,value=synth%runMode,label="RUN_MODE:",_RC)
         call MAPL_GridCreate(GC, _RC)
         call ESMF_GridCompGet(GC, grid=grid, _RC)
         call set_locstream(_RC)
         call MAPL_GenericInitialize ( GC, IMPORT, EXPORT, clock, _RC)
         call ForceAllocation(Export,_RC)
         if (fill_bundle) then
            call FillBundle(Export,_RC)
         end if
         call MAPL_Get ( MAPL, internal_esmf_state=internal, cf=cf, _RC )
         call FillState(internal,export,currTime,grid,synth,cf,_RC)
         _RETURN(ESMF_SUCCESS)
      contains
            subroutine set_locstream(rc)
            integer, optional, intent(out) :: rc
            integer :: status
            character(len=ESMF_MAXPATHLEN) :: tile_file
            type(ESMF_DistGrid) :: distgrid
            type(ESMF_DELayout) :: layout
            type(MAPL_LocStream) :: exch
            if (synth%on_tiles) then
               call ESMF_ConfigGetAttribute(cf,tile_file,label="tiling_file:",_RC)
               call ESMF_GridGet(grid,distGrid=distgrid,_RC)
               call ESMF_DistGridGet(distgrid,deLayout=layout,_RC)
               call MAPL_LocStreamCreate(exch,layout=layout,filename=tile_file, &
                    name = 'my_tiles', mask = [MAPL_LAND], grid=grid,_RC)
               call MAPL_ExchangeGridSet(gc,exch,_RC)
               call MAPL_GenericMakeXchgNatural(MAPL,_RC)
               call ESMF_GridCompSet(gc,grid=grid,_RC)
            end if
            _RETURN(_SUCCESS)
            end subroutine set_locstream
      END SUBROUTINE Initialize_
Call graph
initialize_ calls ESMF_ClockGet, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigGetDim, ESMF_ConfigNextLine, ESMF_DistGridGet, ESMF_GridCompGet, ESMF_GridCompSet, ESMF_GridGet, ESMF_UserCompGetInternalState, insert, mapl_get, mapl_getobjectfromgc, mapl_locstreamcreate, fillbundle, fillstate, forceallocation, init_time, mapl_exchangegridset, mapl_genericinitialize, mapl_genericmakexchgnatural, mapl_gridcreate, mapl_return, mapl_verify