initialize_base – MAPL
initialize_base Subroutine
19 statements
Source File
private subroutine initialize_base(this, spec, unusable, rc)
Uses
mapl_RegridderSpec
MAPL_KeywordEnforcerMod
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(inout) :: this
type(RegridderSpec), intent(in) :: spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_base(this, spec, unusable, rc)
      use MAPL_KeywordEnforcerMod
      use MAPL_RegridderSpec
      class (AbstractRegridder), intent(inout) :: this
      type (RegridderSpec), intent(in) :: spec
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME//'initialize_base'
      _UNUSED_DUMMY(unusable)
      this%spec = spec
      ! Do the rest in the child type
      call this%initialize(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine initialize_base
Call graph
initialize_base calls initialize, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
initialize_subclass calls mapl_return, mapl_verify, mapl_allocnodearray, mapl_deallocnodearray, mapl_syncsharedmemory, copy_global_to_local, find_tile_file, get_spec, read_geos_binary, read_tempest
mapl_throw_exception calls initialize
make_regridder_from_grids calls initialize
newlatlontolatlonregridder calls initialize
latlontolatlonregridder calls newlatlontolatlonregridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder