initialize_from_esmf_distGrid – MAPL
initialize_from_esmf_distGrid Subroutine
59 statements
Source File
private subroutine initialize_from_esmf_distGrid(this, dist_grid, lon_array, lat_array, unusable, rc)
Uses
MAPL_Constants
MAPL_ConfigMod
Type Bound
SwathGridFactory
Arguments
Type Intent Optional Attributes Name
class(SwathGridFactory), intent(inout) :: this
type(ESMF_DistGrid), intent(in) :: dist_grid
type(ESMF_LocalArray), intent(in) :: lon_array
type(ESMF_LocalArray), intent(in) :: lat_array
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_esmf_distGrid(this, dist_grid, lon_array, lat_array, unusable, rc)
      use MAPL_ConfigMod
      use MAPL_Constants, only: PI => MAPL_PI_R8
      class (SwathGridFactory), intent(inout)  :: this
      type (ESMF_DistGrid), intent(in) :: dist_grid
      type (ESMF_LocalArray), intent(in) :: lon_array
      type (ESMF_LocalArray), intent(in) :: lat_array
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: dim_count, tile_count
      integer, allocatable :: max_index(:,:)
      integer :: status
      character(len=2) :: pole ,dateline
      type (ESMF_Config) :: config
      type (ESMF_VM) :: vm
      integer :: nPet
      real(kind=REAL32), pointer :: lon(:)
      real(kind=REAL32), pointer :: lat(:)
      integer :: nx_guess,nx,ny
      integer :: i
      real, parameter :: tiny = 1.e-4
      _FAIL ('stop: not implemented: subroutine initialize_from_esmf_distGrid')
      _UNUSED_DUMMY(unusable)
      call ESMF_DistGridGet(dist_grid, dimCount=dim_count, tileCount=tile_count)
      allocate(max_index(dim_count, tile_count))
      call ESMF_DistGridGet(dist_grid, maxindexPTile=max_index)
      config = MAPL_ConfigCreate(_RC)
      call MAPL_ConfigSetAttribute(config, max_index(1,1), 'IM_WORLD:', _RC)
      call MAPL_ConfigSetAttribute(config, max_index(2,1), 'JM_WORLD:', _RC)
      call MAPL_ConfigSetAttribute(config, max_index(3,1), 'LM:', _RC)
      lon => null()
      lat => null()
      call ESMF_LocalArrayGet(lon_array, farrayPtr=lon, _RC)
      call ESMF_LocalArrayGet(lat_array, farrayPtr=lat, _RC)
      call ESMF_VMGetCurrent(vm, _RC)
      call ESMF_VMGet(vm, PETcount=nPet, _RC)
      nx_guess = nint(sqrt(real(nPet)))
      do nx = nx_guess,1,-1
         ny=nPet/nx
         if (nx*ny==nPet) then
            call MAPL_ConfigSetAttribute(config, nx, 'NX:')
            call MAPL_ConfigSetAttribute(config, ny, 'NY:')
            exit
         end if
      enddo
      call this%initialize(config, _RC)
   end subroutine initialize_from_esmf_distGrid
Call graph
initialize_from_esmf_distgrid calls ESMF_DistGridGet, ESMF_VMGet, ESMF_VMGetCurrent, esmf_localarrayget, mapl_assert, mapl_configsetattribute, initialize, mapl_configcreate, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configcreate calls ESMF_ConfigCreate, buffer, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_configsetattribute_int32 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_ints32 calls mapl_assert, mapl_configsetattribute, mapl_verify, mapl_return
mapl_configsetattribute_real32 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_real64 calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_configsetattribute_reals32 calls mapl_assert, mapl_configsetattribute, mapl_verify, mapl_return
mapl_configsetattribute_string calls buffer, mapl_return, ESMF_ConfigGetAttribute
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert