initialize_data – MAPL
initialize_data Subroutine
15 statements
Source File
private subroutine initialize_data(model, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
integer, intent(out) :: rc
Calls
Source Code
    subroutine initialize_data(model, rc)
        type(ESMF_GridComp)  :: model
        integer, intent(out) :: rc
        type(ESMF_State) :: import_state, export_state
        type(ESMF_Clock) :: clock
        integer                                 :: num_items
        call ESMF_GridCompGet(model, clock=clock, importState=import_state, &
                exportState=export_state, rc=rc)
        VERIFY_NUOPC_(rc)
        call ESMF_StateGet(export_state, itemcount=num_items, rc=rc)
        VERIFY_NUOPC_(rc)
        ! if (num_items /= 0) then
        !    allocate(item_names(num_items))
        !    call ESMF_StateGet(export_state, itemnamelist = item_names, rc = rc)
        !    if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
        !         line=__LINE__, file=__FILE__)) return
        !    do i = 1, num_items
        !       call ESMF_StateGet(export_state, item_names(i), field, rc = rc)
        !       if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
        !            line=__LINE__, file=__FILE__)) return
        !       call NUOPC_SetAttribute(field, name="Updated", value="true", rc=rc)
        !       if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, &
        !            line=__LINE__, &
        !            file=__FILE__)) &
        !            return  ! bail out
        !    end do
        ! end if
        call NUOPC_CompAttributeSet(model, &
                name="InitializeDataComplete", value="true", rc=rc)
        VERIFY_NUOPC_(rc)
        _RETURN(_SUCCESS)
    end subroutine initialize_data
Call graph
initialize_data calls ESMF_GridCompGet, ESMF_LogFoundError, NUOPC_CompAttributeSet, esmf_stateget, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize