init_ClientManager – MAPL
init_ClientManager Subroutine
17 statements
Source File
private subroutine init_ClientManager(client_comm, unusable, n_i, n_o, fast_oclient, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: client_comm
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: n_i
integer, intent(in), optional :: n_o
logical, intent(in), optional :: fast_oclient
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init_ClientManager(client_comm, unusable, n_i, n_o, fast_oclient, rc)
      integer, intent(in) :: client_comm
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in) :: n_i
      integer, optional, intent(in) :: n_o
      logical, optional, intent(in) :: fast_oclient
      integer, optional, intent(out):: rc
      integer :: status
      i_Clients = ClientManager(client_comm, n_client = n_i, rc=status)
      o_Clients = ClientManager(client_comm, n_client = n_o, fast_oclient = fast_oclient, rc=status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine init_ClientManager
Call graph
init_clientmanager calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
init_io_clientmanager calls init_clientmanager
initialize calls init_io_clientmanager
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main