initialize_mpi – MAPL
initialize_mpi Subroutine
27 statements
Source File
private subroutine initialize_mpi(this, unusable, rc)
$ call MPI_Init_thread(MPI_THREAD_MULTIPLE, provided, ierror) $ if(MAPL_Assert(provided == MPI_THREAD_MULTIPLE, ‘MPI_THREAD_MULTIPLE not supporte by this MPI.’,1,”/home/runner/work/MAPL/MAPL/docs/Ford/../../gridcomps/Cap/MAPL_Cap.F90”,449 ,rc)) return
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
initialize_mpi
Source Code
   subroutine initialize_mpi(this, unusable, rc)
      class (MAPL_Cap), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: ierror
      integer :: provided
      integer :: npes_world
      _UNUSED_DUMMY(unusable)
      call MPI_Initialized(this%mpi_already_initialized, ierror)
      _VERIFY(ierror)
      if (.not. this%mpi_already_initialized) then
!!$         call MPI_Init_thread(MPI_THREAD_MULTIPLE, provided, ierror)
!!$         _ASSERT(provided == MPI_THREAD_MULTIPLE, 'MPI_THREAD_MULTIPLE not supporte by this MPI.')
         call MPI_Init_thread(MPI_THREAD_SINGLE, provided, ierror)
         _VERIFY(ierror)
         _ASSERT(provided == MPI_THREAD_SINGLE, "MPI_THREAD_SINGLE not supported by this MPI.")
      end if
      call MPI_Comm_rank(this%comm_world, this%rank, ierror); _VERIFY(ierror)
      call MPI_Comm_size(this%comm_world, npes_world, ierror); _VERIFY(ierror)
      if ( this%cap_options%npes_model == -1) then
         ! just a feed back to cap_options to maintain integrity
          this%cap_options%npes_model = npes_world
      endif
      _ASSERT(npes_world >= this%cap_options%npes_model, "npes_world is smaller than npes_model")
      this%npes_member = npes_world / this%cap_options%n_members
      _RETURN(_SUCCESS)
   end subroutine initialize_mpi
Call graph
initialize_mpi calls mapl_assert, mpi_comm_rank, mpi_comm_size, mpi_init_thread, mpi_initialized, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_mapl_cap_from_dso calls initialize_mpi
new_mapl_cap_from_set_services calls initialize_mpi
mapl_cap calls new_mapl_cap_from_dso, new_mapl_cap_from_set_services