init – MAPL
init Subroutine
12 statements
Source File
private subroutine init(this, sckt, server, rc)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout) :: this
class(AbstractSocket), intent(in), target :: sckt
class(AbstractServer), intent(in), target :: server
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init(this, sckt, server, rc)
      class (ServerThread), intent(inout) :: this
      class (AbstractSocket), target, intent(in) :: sckt
      class (AbstractServer), target, intent(in) :: server
      integer, optional, intent(out) :: rc
      integer :: status
      call this%set_connection(sckt, _RC)
      this%containing_server => server
      _RETURN(_SUCCESS)
   end subroutine init
Call graph
init calls mapl_return, mapl_verify, set_connection
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_connection calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize
test_handle_addextcollection calls init
test_handle_prefetchdata calls init
test_return_on_terminate calls init
test_return_on_terminate_b calls init