initialize_mpi – MAPL
initialize_mpi Subroutine
20 statements
Source File
public subroutine initialize_mpi(this, unusable, rc)
Type Bound
ExtDataDriver
Arguments
Type Intent Optional Attributes Name
class(ExtDataDriver), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
initialize_mpi
Source Code
   subroutine initialize_mpi(this, unusable, rc)
      class (ExtDataDriver), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: ierror
      integer :: npes_world
      _UNUSED_DUMMY(unusable)
      call MPI_Init(ierror)
      this%comm_world=MPI_COMM_WORLD
      call MPI_Comm_rank(this%comm_world, this%rank, ierror); _VERIFY(ierror)
      call MPI_Comm_size(this%comm_world, npes_world, ierror); _VERIFY(ierror)
      if ( this%cap_options%npes_model == -1) then
         ! just a feed back to cap_options to maintain integrity
          this%cap_options%npes_model = npes_world
      endif
      _ASSERT(npes_world >= this%cap_options%npes_model, "npes_world is smaller than npes_model")
      _RETURN(_SUCCESS)
   end subroutine initialize_mpi
Call graph
initialize_mpi calls mapl_assert, mpi_comm_rank, mpi_comm_size, mpi_init, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
newextdatadriver calls initialize_mpi
extdatadriver calls newextdatadriver
extdata_driver calls extdatadriver