initialize_extdata – MAPL
initialize_extdata Subroutine
89 statements
Source File
private subroutine initialize_extdata(cap, root_gc, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: cap
type(ESMF_GridComp), intent(inout), pointer :: root_gc
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine initialize_extdata(cap , root_gc, rc)
    class(MAPL_CapGridComp), intent(inout) :: cap
    type (ESMF_GridComp), intent(inout), pointer :: root_gc
    integer, optional, intent(out) :: rc
    integer :: item_count, status
    type (ESMF_StateItem_Flag), pointer   :: item_types(:)
    character(len=ESMF_MAXSTR ), pointer  :: item_names(:)
    type(ESMF_Field) :: field
    type(ESMF_FieldBundle) :: bundle
    type(StringVector) :: cap_imports_vec, cap_exports_vec, extdata_imports_vec
    type(StringVectorIterator) :: iter
    integer :: i
    type(ESMF_State) :: state, root_imports, component_state
    character(len=:), allocatable :: component_name, field_name
    ! Prepare EXPORTS for ExtData
    ! ---------------------------
    cap_imports_vec = get_vec_from_config(cap%config, "CAP_IMPORTS", _RC)
    cap_exports_vec = get_vec_from_config(cap%config, "CAP_EXPORTS", _RC)
    extdata_imports_vec = get_vec_from_config(cap%config, "EXTDATA_IMPORTS")
    cap%import_state = ESMF_StateCreate(name = "Cap_Imports", stateintent = ESMF_STATEINTENT_IMPORT)
    cap%export_state = ESMF_StateCreate(name = "Cap_Exports", stateintent = ESMF_STATEINTENT_EXPORT)
    if (cap_exports_vec%size() /= 0) then
       iter = cap_exports_vec%begin()
       do while(iter /= cap_exports_vec%end())
          component_name = iter%get()
          component_name = trim(component_name(index(component_name, ",")+1:))
          field_name = iter%get()
          field_name = trim(field_name(1:index(field_name, ",")-1))
          call MAPL_ExportStateGet([cap%child_exports(cap%root_id)], component_name, &
               component_state, status)
          _VERIFY(status)
          call ESMF_StateGet(component_state, trim(field_name), field, _RC)
          call MAPL_StateAdd(cap%export_state, field, _RC)
          call iter%next()
       end do
    end if
    if (extdata_imports_vec%size() /= 0) then
       iter = extdata_imports_vec%begin()
       do while(iter /= extdata_imports_vec%end())
          component_name = iter%get()
          component_name = trim(component_name(index(component_name, ",")+1:))
          field_name = iter%get()
          field_name = trim(field_name(1:index(field_name, ",")-1))
          call MAPL_ExportStateGet([cap%child_exports(cap%root_id)], component_name, &
               component_state, _RC)
          call ESMF_StateGet(component_state, trim(field_name), field, _RC)
          call MAPL_StateAdd(cap%child_imports(cap%extdata_id), field, _RC)
          call iter%next()
       end do
    end if
    call ESMF_StateGet(cap%child_imports(cap%root_id), itemcount = item_count, _RC)
    allocate(item_names(item_count), _STAT)
    allocate(item_types(item_count), _STAT)
    call ESMF_StateGet(cap%child_imports(cap%root_id), itemnamelist = item_names, &
         itemtypelist = item_types, _RC)
    root_imports = cap%child_imports(cap%root_id)
    do i = 1, item_count
       if (vector_contains_str(cap_imports_vec, item_names(i))) then
          state = cap%import_state
       else
          state = cap%child_exports(cap%extdata_id)
       end if
       if (item_types(i) == ESMF_StateItem_Field) then
          call ESMF_StateGet(root_imports, item_names(i), field, _RC)
          call MAPL_AddAttributeToFields(root_gc,trim(item_names(i)),'RESTART',MAPL_RestartSkip,_RC)
          call MAPL_StateAdd(state, field, _RC)
       else if (item_types(i) == ESMF_StateItem_FieldBundle) then
          call ESMF_StateGet(root_imports, item_names(i), bundle, _RC)
          call MAPL_StateAdd(state, bundle, _RC)
       end if
    end do
    deallocate(item_types)
    deallocate(item_names)
    ! Initialize the ExtData
    !------------------------
    call ESMF_GridCompInitialize (cap%gcs(cap%extdata_id), importState = cap%child_imports(cap%extdata_id), &
         exportState = cap%child_exports(cap%extdata_id), &
         clock = cap%clock, userRc = status)
    _VERIFY(status)
    _RETURN(ESMF_SUCCESS)
  end subroutine initialize_extdata
Call graph
initialize_extdata calls ESMF_GridCompInitialize, begin, esmf_statecreate, esmf_stateget, get, mapl_addattributetofields, mapl_stateadd, next, get_vec_from_config, mapl_exportstateget, mapl_return, mapl_verify, vector_contains_str
mapl_addattributetofields calls mapl_addattributetofields_i4
mapl_stateadd calls mapl_stateaddbundle, mapl_stateaddfield
get_vec_from_config calls mapl_return, mapl_verify, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine, push_back
mapl_exportstateget calls esmf_stateget, mapl_exportstateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vector_contains_str calls begin, get, next
initialize_gc calls initialize_extdata