initCollective – MAPL
initCollective Subroutine
36 statements
Source File
private subroutine initCollective(message, request_id, collection_id, file_name, var_name, data_reference, unusable, start, global_start, global_count, rc)
Type Bound
AbstractCollectiveDataMessage
Arguments
Type Intent Optional Attributes Name
class(AbstractCollectiveDataMessage) :: message
integer, intent(in) :: request_id
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: global_start(:)
integer, intent(in), optional :: global_count(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initCollective( message, &
        & request_id, collection_id, file_name, var_name, &
        & data_reference, unusable, start,global_start,global_count, rc)
      class (AbstractCollectiveDataMessage) :: message
      integer, intent(in) :: request_id
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: start(:)
      integer, optional, intent(in) :: global_start(:)
      integer, optional, intent(in) :: global_count(:)
      integer, optional, intent(out) :: rc
      integer, allocatable :: st(:)
      integer :: i,k, status
      if (present(global_start)) then
         message%global_start = global_start
      else
         message%global_start = [(1,i=1,size(data_reference%shape))]
      end if
      if (present(global_count)) then
         message%global_count = global_count
      else
         message%global_count = data_reference%shape
      end if
      _ASSERT(size(message%global_start) == size(message%global_count),"global count and global start should mactch")
      if(present(start)) then
         k = size(message%global_start) - size(start)
         st = [start,[(1,i=1,k)]]
      else
         st = message%global_start
      endif
      call message%init(request_id,collection_id, &
          file_name,var_name,data_reference,unusable=unusable,start=st, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine initCollective
Call graph
initcollective calls mapl_assert, init, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
init calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_collectiveprefetchdatamessage calls initcollective
new_collectivestagedatamessage calls initcollective
collectiveprefetchdatamessage calls new_collectiveprefetchdatamessage
collectivestagedatamessage calls new_collectivestagedatamessage