init_wrapper – MAPL
init_wrapper Subroutine
13 statements
Source File
public subroutine init_wrapper(wrapper_gc, name, cap_rc_file, root_set_services, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: wrapper_gc
character(len=*), intent(in) :: name
character(len=*), intent(in) :: cap_rc_file
procedure(set_services_interface) :: root_set_services
integer, intent(out) :: rc
Calls
Contents
Source Code
init_wrapper
Source Code
    subroutine init_wrapper(wrapper_gc, name, cap_rc_file, root_set_services, rc)
        type(ESMF_GridComp), intent(inout) :: wrapper_gc
        character(*),        intent(in   ) :: name, cap_rc_file
        procedure(set_services_interface)  :: root_set_services
        integer, intent(out)               :: rc
        type(cap_parameters_wrapper) :: wrapper
        allocate(wrapper%ptr)
        wrapper%ptr = cap_parameters(name, cap_rc_file, root_set_services)
        call ESMF_UserCompSetInternalState(wrapper_gc, internal_parameters_name, wrapper, rc)
        VERIFY_NUOPC_(rc)
        _RETURN(_SUCCESS)
    end subroutine init_wrapper
Call graph
init_wrapper calls ESMF_LogFoundError, ESMF_UserCompSetInternalState, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize