initialize_history – MAPL
initialize_history Subroutine
21 statements
Source File
private subroutine initialize_history(cap, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: cap
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine initialize_history(cap, rc)
    class(MAPL_CapGridComp), intent(inout) :: cap
    integer, optional, intent(out) :: rc
    integer :: status
    type(HISTORY_ExchangeListWrap) :: lswrap
    integer(kind=INT64), pointer   :: LSADDR(:) => null()
    if (present(rc)) rc = ESMF_SUCCESS
    ! All the EXPORTS of the Hierachy are made IMPORTS of History
    !------------------------------------------------------------
    call ESMF_StateAdd(cap%child_imports(cap%history_id), [cap%child_exports(cap%root_id)], rc = status)
    _VERIFY(STATUS)
    allocate(lswrap%ptr, stat = status)
    _VERIFY(STATUS)
    call ESMF_UserCompSetInternalState(cap%gcs(cap%history_id), 'MAPL_LocStreamList', &
         lswrap, STATUS)
    _VERIFY(STATUS)
    call MAPL_GetAllExchangeGrids(CAP%GCS(cap%root_id), LSADDR, RC=STATUS)
    _VERIFY(STATUS)
    lswrap%ptr%LSADDR_PTR => LSADDR
    ! Initialize the History
    !------------------------
    call ESMF_GridCompInitialize (CAP%GCS(cap%history_id), importState=CAP%CHILD_IMPORTS(cap%history_id), &
         exportState=CAP%CHILD_EXPORTS(cap%history_id), clock=CAP%CLOCK_HIST, userRC=STATUS )
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine initialize_history
Call graph
initialize_history calls ESMF_GridCompInitialize, ESMF_UserCompSetInternalState, esmf_stateadd, mapl_getallexchangegrids, mapl_return, mapl_verify
mapl_getallexchangegrids calls mapl_getallexchangegrids, mapl_return, mapl_verify, ESMF_GridCompGet, c_mapl_locstreamretrieveptr, mapl_getobjectfromgc, get_child_gridcomp, get_num_children
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_error_message calls at, insert
get_num_children calls get_num_children
mapl_throw_exception calls initialize
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
initialize_gc calls initialize_history