initialize_from_config_file – MAPL
initialize_from_config_file Subroutine
25 statements
Source File
private subroutine initialize_from_config_file(this, config_file, unusable, prefix, rc)
Uses
MAPL_KeywordEnforcerMod
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout) :: this
character(len=*), intent(in) :: config_file
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: prefix
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_config_file(this, config_file, unusable, prefix, rc)
      use MAPL_KeywordEnforcerMod
      class (AbstractGridFactory), intent(inout)  :: this
      character(len=*), intent(in) :: config_file
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: prefix
      integer, optional, intent(out) :: rc
      type (ESMF_Config) :: config
      character(len=*), parameter :: Iam= MOD_NAME // 'initialize_from_file'
      integer :: status
      _UNUSED_DUMMY(unusable)
      config = ESMF_ConfigCreate(rc=status)
      _VERIFY(status)
      call ESMF_ConfigLoadFile   (config, config_file, rc=STATUS )
      _VERIFY(status)
      call this%initialize(config, prefix=prefix, rc=status)
      _VERIFY(status)
      call ESMF_ConfigDestroy(config, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine initialize_from_config_file
Call graph
initialize_from_config_file calls ESMF_ConfigCreate, ESMF_ConfigDestroy, ESMF_ConfigLoadFile, initialize, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
initialize_from_esmf_distgrid calls mapl_assert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code