init – MAPL
init Subroutine
60 statements
Source File
private subroutine init(this, comm, port_name, profiler_name, with_profiler, rc)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout) :: this
integer, intent(in) :: comm
character(len=*), intent(in) :: port_name
character(len=*), intent(in), optional :: profiler_name
logical, intent(in), optional :: with_profiler
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init(this,comm, port_name, profiler_name, with_profiler, rc)
      class (AbstractServer),intent(inout) :: this
      integer, intent(in) :: comm
      character(*), intent(in) :: port_name
      character(*), optional, intent(in) :: profiler_name
      logical, optional, intent(in) :: with_profiler
      integer, optional, intent(out) :: rc
      integer :: ierror, MyColor
      character(len=:), allocatable :: p_name
      this%comm = comm
      call MPI_Comm_rank(this%comm, this%rank, ierror)
      _VERIFY(ierror)
      call MPI_Comm_size(this%comm, this%npes, ierror)
      _VERIFY(ierror)
      this%num_clients = 0
      this%all_backlog_is_empty = .true.
      this%status = UNALLOCATED
      call MPI_Comm_split_type(this%comm, MPI_COMM_TYPE_SHARED, 0, MPI_INFO_NULL, this%InNode_Comm,ierror)
      _VERIFY(ierror)
      call MPI_Comm_size(this%InNode_Comm, this%InNode_npes,ierror)
      _VERIFY(ierror)
      call MPI_Comm_rank(this%InNode_Comm, this%InNode_Rank,ierror)
      _VERIFY(ierror)
      MyColor = 0
      if (this%InNode_Rank == 0) MyColor = 1
      call MPI_COMM_SPLIT( comm, MyColor, this%rank, this%NodeRoot_Comm, ierror)
      _VERIFY(ierror)
      if (MyColor==0) then
         this%NodeRoot_Comm=MPI_COMM_NULL
      else
         call MPI_COMM_SIZE(this%NodeRoot_Comm, this%Node_Num, ierror)
         _VERIFY(ierror)
         call MPI_COMM_RANK(this%NodeRoot_Comm, this%Node_Rank, ierror)
         _VERIFY(ierror)
      endif
      call Mpi_Bcast(this%Node_Rank, 1, MPI_INTEGER, 0, this%InNode_Comm, ierror)
      _VERIFY(ierror)
      call Mpi_Bcast(this%Node_Num,  1, MPI_INTEGER, 0, this%InNode_Comm, ierror)
      _VERIFY(ierror)
      allocate(This%Node_Ranks(0:this%npes-1))
      call Mpi_AllGather(this%Node_Rank,  1, MPI_INTEGER, &
                         this%Node_Ranks, 1, MPI_INTEGER, comm,ierror)
      _VERIFY(ierror)
      if (present(profiler_name)) then
         p_name = profiler_name
      else
         p_name = port_name
      endif
      if (present(with_profiler)) then
         if (with_profiler) then
            if (.not. associated(ioserver_profiler)) then
               allocate(ioserver_profiler, source = DistributedProfiler(p_name, MpiTimerGauge(), comm))
               call ioserver_profiler%start()
            endif
         endif
      endif
      call MPI_Barrier(comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
   end subroutine init
Call graph
init calls mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
new_mpiserver calls init
new_multicommserver calls init
new_multigroupserver calls init
new_multilayerserver calls init
new_openmpserver calls init
mpiserver calls new_mpiserver
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
multilayerserver calls new_multilayerserver
openmpserver calls new_openmpserver