initialize_pflogger – MAPL
initialize_pflogger Subroutine
60 statements
Source File
private subroutine initialize_pflogger(unusable, comm, logging_config, rc)
Uses
PFL_Formatter
pflogger
mapl_SimulationTime
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
character(len=*), intent(in), optional :: logging_config
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
initialize_pflogger
Source Code
   subroutine initialize_pflogger(unusable,comm,logging_config,rc)
      use pflogger, only: pfl_initialize => initialize
      use pflogger, only: StreamHandler, FileHandler, HandlerVector
      use pflogger, only: MpiLock, MpiFormatter
      use pflogger, only: INFO, WARNING
      use PFL_Formatter, only: get_sim_time
      use mapl_SimulationTime, only: fill_time_dict
      use, intrinsic :: iso_fortran_env, only: OUTPUT_UNIT
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      character(len=*), optional,intent(in) :: logging_config
      integer, optional, intent(out) :: rc
      type (HandlerVector) :: handlers
      type (StreamHandler) :: console
      type (FileHandler) :: file_handler
      integer :: level,rank,status
      character(:), allocatable :: logging_configuration_file
      integer :: comm_world
      type(Logger), pointer :: lgr
      _UNUSED_DUMMY(unusable)
      if (present(logging_config)) then
         logging_configuration_file=logging_config
      else
         logging_configuration_file=''
      end if
      if (present(comm)) then
         comm_world = comm
      else
         comm_world=MPI_COMM_WORLD
      end if
      call pfl_initialize()
      get_sim_time => fill_time_dict
      if (logging_configuration_file /= '') then
         call logging%load_file(logging_configuration_file)
      else
         call MPI_COMM_Rank(comm_world,rank,status)
         console = StreamHandler(OUTPUT_UNIT)
         call console%set_level(INFO)
         call console%set_formatter(MpiFormatter(comm_world, fmt='%(short_name)a10~: %(message)a'))
         call handlers%push_back(console)
         file_handler = FileHandler('warnings_and_errors.log')
         call file_handler%set_level(WARNING)
         call file_handler%set_formatter(MpiFormatter(comm_world, fmt='pe=%(mpi_rank)i5.5~: %(short_name)a~: %(message)a'))
         call file_handler%set_lock(MpiLock(comm_world))
         call handlers%push_back(file_handler)
         if (rank == 0) then
            level = INFO
         else
            level = WARNING
         end if
         call logging%basic_config(level=level, handlers=handlers, rc=status)
         _VERIFY(status)
         if (rank == 0) then
            lgr => logging%get_logger('MAPL')
            call lgr%warning('No configure file specified for logging layer.  Using defaults.')
         end if
      end if
      _RETURN(_SUCCESS)
   end subroutine initialize_pflogger
Call graph
initialize_pflogger calls basic_config, filehandler, get_logger, load_file, mpi_comm_rank, mpiformatter, mpilock, initialize, mapl_return, mapl_verify, push_back, set_formatter, set_level, set_lock, streamhandler, warning
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_initialize calls initialize_pflogger
main calls mapl_initialize
new_mapl_cap_from_dso calls mapl_initialize
new_mapl_cap_from_set_services calls mapl_initialize
newextdatadriver calls mapl_initialize
time_ave calls mapl_initialize
ut_regridding calls mapl_initialize
extdatadriver calls newextdatadriver
mapl_cap calls new_mapl_cap_from_dso, new_mapl_cap_from_set_services
comp_testing_driver calls main
regrid_util calls main
extdata_driver calls extdatadriver