init – MAPL
init Subroutine
74 statements
Source File
private subroutine init(this, options, comms, app_ds, N_iclient_g, N_oclient_g, rc)
Type Bound
FakeHistData0
Arguments
Type Intent Optional Attributes Name
class(FakeHistData0), intent(inout), target :: this
type(CommandLineOptions0), intent(in) :: options
integer, intent(in), dimension(:) :: comms
class(AbstractDirectoryService), intent(inout), target :: app_ds
integer, intent(in) :: N_iclient_g
integer, intent(in) :: N_oclient_g
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init(this, options, comms,app_ds, N_iclient_g, N_oclient_g, rc)
      class (FakeHistData0),target, intent(inout) :: this
      type (CommandLineOptions0), intent(in) :: options
      integer, intent(in), dimension(:) :: comms
      class(AbstractDirectoryService), target,intent(inout) :: app_ds
      integer, intent(in) :: N_iclient_g, N_oclient_g
      integer, optional, intent(out) :: rc
      integer :: ierror,k, i,status
      type (FileMetadata) :: file_metadata
      type (NetCDF4_FileFormatter) :: formatter
      type (NetCDF4_FileFormatter) :: test_formatter
      type (FileMetadata) :: test_metadata
      real, target,allocatable :: testValues(:,:,:,:,:)
      real, pointer :: testPtr(:)
      type (StringIntegerMap) :: dims
      class(ClientThread), pointer :: threadPtr=>null()
      this%ic_vec = ClientThreadVector()
      this%oc_vec = ClientThreadVector()
      do i = 1, N_iclient_g
         allocate(threadPtr, source = ClientThread())
         call app_ds%connect_to_server('iserver',threadPtr, comms(i), rc=status)
         _VERIFY(status)
         !call threadPtr%init_connection(app_ds(i)%dsPtr, comms(i),'i_server')
         call this%ic_vec%push_back(threadPtr)
         nullify(threadPtr)
      enddo
      do i = 1 + N_iclient_g, N_iclient_g + N_oclient_g
         allocate(threadPtr, source = ClientThread())
         call app_ds%connect_to_server('oserver',threadPtr, comms(i), rc=status)
         _VERIFY(status)
         !call threadPtr%init_connection(app_ds(i)%dsPtr, comms(i),'o_server')
         call this%oc_vec%push_back(threadPtr)
         nullify(threadPtr)
      enddo
      !this%i_c = ClientThread()
      !call this%i_c%init_connection(app_ds(1)%dsPtr,comms(1),'i_server')
      !this%o_c = ClientThread()
      !call this%o_c%init_connection(app_ds(2)%dsPtr,comms(2),'o_server')
      this%vars = options%requested_variables
      this%comm = comms(1)
      allocate(this%comms, source = comms)
      call MPI_Comm_rank(this%comms(1),this%rank,ierror)
      call MPI_Comm_size(this%comms(1),this%npes,ierror)
      allocate(this%bundle(this%vars%size()))
      allocate(this%hist_collection_ids(10))
      if ( this%rank == 0) then
         call test_metadata%add_dimension('Xdim',48)
         call test_metadata%add_dimension('Ydim',48)
         call test_metadata%add_dimension('nf',6)
         call test_metadata%add_dimension('lev',72)
         call test_metadata%add_dimension('time',1)
         do k = 1, this%vars%size()
            call test_metadata%add_variable(this%vars%at(k),Variable(type=pFIO_REAL32, dimensions='Xdim,Ydim,nf,lev,time'), rc=status)
            _VERIFY(status)
         enddo
         call test_formatter%create('test_in.nc4', rc=status)
         _VERIFY(status)
         call test_formatter%write(test_metadata, rc=status)
         _VERIFY(status)
         allocate(testValues(48,48,6,72,1))
         do k = 1, this%vars%size()
            do i = 1,6
               testValues(:,:,i,:,:) = 1.0*i*10**k
            enddo
            call c_f_pointer(c_loc(testValues), testPtr,[48*48*72*6*1])
            call test_formatter%put_var(this%vars%at(k),testPtr, start=[1,1,1,1,1], count = [48,48,6,72,1])
         enddo
         call test_formatter%close(rc=status)
      endif
      call Mpi_Barrier(this%comms(1),ierror)
      call formatter%open('test_in.nc4', pFIO_READ)
      file_metadata = formatter%read()
      call formatter%close()
      dims = file_metadata%get_dimensions()
      this%Xdim = dims%at('Xdim')
      this%Ydim = dims%at('Ydim')
      this%nf   = dims%at('nf')
      this%lev  = dims%at('lev')
      this%time = 1
   end subroutine init
Call graph
init calls at, connect_to_server, mpi_barrier, mpi_comm_rank, mpi_comm_size, put_var, add_dimension, add_variable, create, get_dimensions, mapl_verify, v_push_back
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
create calls mapl_verify, nf90_create, mapl_return
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
main calls init