initialize_gc – MAPL
initialize_gc Subroutine
222 statements
Source File
private subroutine initialize_gc(gc, import_state, export_state, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gc
type(ESMF_State) :: import_state
type(ESMF_State) :: export_state
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Source Code
  subroutine initialize_gc(gc, import_state, export_state, clock, rc)
    type(ESMF_GridComp) :: gc
    type(ESMF_State) :: import_state, export_state
    type(ESMF_Clock) :: clock
    integer, intent(out) :: rc
    integer :: comm
    integer                      :: NPES
    logical :: amIRoot_
    character(len=ESMF_MAXSTR)   :: enableTimers
    character(len=ESMF_MAXSTR)   :: enableMemUtils
    integer                      :: MemUtilsMode
    integer :: status
    character(len=ESMF_MAXSTR)   :: ROOT_NAME
    ! Misc locals
    !------------
    character(len=ESMF_MAXSTR)   :: EXPID
    character(len=ESMF_MAXSTR)   :: EXPDSC
    ! Handles to the CAP's Gridded Components GCs
    ! -------------------------------------------
    integer                               :: i, itemcount
    type (ESMF_Field)                     :: field
    type (ESMF_FieldBundle)               :: bundle
    type (ESMF_StateItem_Flag), pointer   :: ITEMTYPES(:)
    character(len=ESMF_MAXSTR ), pointer  :: ITEMNAMES(:)
    integer                      :: RUN_DT
    integer :: nx
    integer :: ny
    integer                      :: HEARTBEAT_DT
    character(len=ESMF_MAXSTR)   :: HIST_CF, ROOT_CF, EXTDATA_CF
    type (MAPL_MetaComp), pointer :: MAPLOBJ
    procedure(), pointer :: root_set_services
    type(ExtData_DriverGridComp), pointer :: cap
    class(BaseProfiler), pointer :: t_p
    logical :: use_extdata2g
    integer :: useShmem
    _UNUSED_DUMMY(import_state)
    _UNUSED_DUMMY(export_state)
    _UNUSED_DUMMY(clock)
    t_p => get_global_time_profiler()
    cap => get_CapGridComp_from_gc(gc)
    maplobj => get_MetaComp_from_gc(gc)
    call ESMF_GridCompGet(gc, vm = cap%vm, rc = status)
    _VERIFY(status)
    call ESMF_VMGet(cap%vm, petcount = NPES, mpiCommunicator = comm, rc = status)
    _VERIFY(status)
    AmIRoot_ = MAPL_Am_I_Root(cap%vm)
    call MAPL_GetNodeInfo(comm = comm, rc = status)
    _VERIFY(STATUS)
    AmIRoot_ = MAPL_Am_I_Root(cap%vm)
    cap%AmIRoot = AmIRoot_
    !  Open the CAP's configuration from CAP.rc
    !------------------------------------------
    cap%config = ESMF_ConfigCreate(rc = status)
    _VERIFY(status)
    call ESMF_ConfigLoadFile(cap%config, cap%configFile, rc = status)
    _VERIFY(status)
    !  CAP's MAPL MetaComp
    !---------------------
    call MAPL_Set(MAPLOBJ,rc = status)
    _VERIFY(STATUS)
    call MAPL_Set(MAPLOBJ, name = cap%name, cf = cap%config, rc = status)
    _VERIFY(status)
    call MAPL_GetResource(MAPLOBJ, useShmem,  label = 'USE_SHMEM:',  default = 0, _RC)
    if (useShmem /= 0) then
       call MAPL_InitializeShmem (_RC)
    end if
    call ESMF_ConfigGetAttribute(cap%config,cap%run_fbf,label="RUN_FBF:",default=.false.)
    call ESMF_ConfigGetAttribute(cap%config,cap%run_hist,label="RUN_HISTORY:",default=.true.)
    call ESMF_ConfigGetAttribute(cap%config,cap%run_extdata,label="RUN_EXTDATA:",default=.true.)
    ! !RESOURCE_ITEM: string :: Name of ROOT's config file
    call MAPL_GetResource(MAPLOBJ, ROOT_CF, "ROOT_CF:", default = "ROOT.rc", rc = status)
    _VERIFY(status)
    ! !RESOURCE_ITEM: string :: Name to assign to the ROOT component
    call MAPL_GetResource(MAPLOBJ, ROOT_NAME, "ROOT_NAME:", default = "ROOT", rc = status)
    _VERIFY(status)
    ! !RESOURCE_ITEM: string :: Name of HISTORY's config file
    call MAPL_GetResource(MAPLOBJ, HIST_CF, "HIST_CF:", default = "HISTORY.rc", rc = status)
    _VERIFY(status)
    ! !RESOURCE_ITEM: string :: Name of ExtData's config file
    call MAPL_GetResource(MAPLOBJ, EXTDATA_CF, "EXTDATA_CF:", default = 'ExtData.rc', rc = status)
    _VERIFY(status)
    ! !RESOURCE_ITEM: string :: Control Timers
    call MAPL_GetResource(MAPLOBJ, enableTimers, "MAPL_ENABLE_TIMERS:", default = 'NO', rc = status)
    _VERIFY(status)
    ! !RESOURCE_ITEM: string :: Control Memory Diagnostic Utility
    call MAPL_GetResource(MAPLOBJ, enableMemUtils, "MAPL_ENABLE_MEMUTILS:", default='NO', rc = status)
    _VERIFY(status)
    call MAPL_GetResource(MAPLOBJ, MemUtilsMode, "MAPL_MEMUTILS_MODE:", default = MAPL_MemUtilsModeBase, rc = status)
    _VERIFY(status)
    !EOR
    enableTimers = ESMF_UtilStringUpperCase(enableTimers, rc = status)
    _VERIFY(status)
    call MAPL_GetResource(maplobj,use_extdata2g,"USE_EXTDATA2G:",default=.false.,_RC)
    if (enableTimers /= 'YES') then
       call MAPL_ProfDisable(rc = status)
       _VERIFY(status)
    end if
    enableMemUtils = ESMF_UtilStringUpperCase(enableMemUtils, rc=STATUS)
    _VERIFY(STATUS)
    if (enableMemUtils /= 'YES') then
       call MAPL_MemUtilsDisable( rc=STATUS )
       _VERIFY(STATUS)
    else
       call MAPL_MemUtilsInit( mode=MemUtilsMode, rc=STATUS )
       _VERIFY(STATUS)
    end if
    ! Handle RUN_DT in ROOT_CF
    !-------------------------
    cap%cf_root = ESMF_ConfigCreate(rc=STATUS )
    _VERIFY(STATUS)
    call ESMF_ConfigLoadFile(cap%cf_root, ROOT_CF, rc=STATUS )
    _VERIFY(STATUS)
    call ESMF_ConfigGetAttribute(cap%config, value=HEARTBEAT_DT, Label="HEARTBEAT_DT:", default=900, rc=status)
    call ESMF_ConfigGetAttribute(cap%cf_root, value=run_dt, Label="RUN_DT:", default=heartbeat_dt, rc=status)
    call MAPL_ConfigSetAttribute(cap%cf_root, value=run_dt, Label="RUN_DT:", rc=status)
    _VERIFY(STATUS)
    ! Add EXPID and EXPDSC from HISTORY.rc to AGCM.rc
    !------------------------------------------------
    if (cap%run_hist) then
       cap%cf_hist = ESMF_ConfigCreate(rc=STATUS )
       _VERIFY(STATUS)
       call ESMF_ConfigLoadFile(cap%cf_hist, HIST_CF, rc=STATUS )
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_hist, value=HIST_CF, Label="HIST_CF:", rc=status)
       _VERIFY(STATUS)
       call ESMF_ConfigGetAttribute(cap%cf_hist, value=EXPID,  Label="EXPID:",  default='', rc=status)
       call ESMF_ConfigGetAttribute(cap%cf_hist, value=EXPDSC, Label="EXPDSC:", default='', rc=status)
       call MAPL_ConfigSetAttribute(cap%cf_root, value=EXPID,  Label="EXPID:",  rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_root, value=EXPDSC, Label="EXPDSC:", rc=status)
       _VERIFY(STATUS)
       call ESMF_ConfigGetAttribute(cap%cf_root, value = NX, Label="NX:", rc=status)
       _VERIFY(STATUS)
       call ESMF_ConfigGetAttribute(cap%cf_root, value = NY, Label="NY:", rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_hist, value=NX,  Label="NX:",  rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_hist, value=NY,  Label="NY:",  rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_hist, value=run_dt, Label="RUN_DT:", rc=status)
       _VERIFY(STATUS)
    end if
    if (cap%run_extdata) then
       ! Add NX and NY from AGCM.rc to ExtData.rc as well as name of ExtData rc file
       cap%cf_ext = ESMF_ConfigCreate(rc=STATUS )
       _VERIFY(STATUS)
       call ESMF_ConfigLoadFile(cap%cf_ext, EXTDATA_CF, rc=STATUS )
       _VERIFY(STATUS)
       call ESMF_ConfigGetAttribute(cap%cf_root, value = NX, Label="NX:", rc=status)
       _VERIFY(STATUS)
       call ESMF_ConfigGetAttribute(cap%cf_root, value = NY, Label="NY:", rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_ext, value=NX,  Label="NX:",  rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_ext, value=NY,  Label="NY:",  rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_ext, value=run_dt, Label="RUN_DT:", rc=status)
       _VERIFY(STATUS)
       call MAPL_ConfigSetAttribute(cap%cf_ext, value=EXTDATA_CF,  Label="CF_EXTDATA:",  rc=status)
       _VERIFY(STATUS)
    end if
    !  Create Root child
    !-------------------
    call MAPL_Set(MAPLOBJ, CF=CAP%CF_ROOT, RC=STATUS)
    _VERIFY(STATUS)
    call MAPL_ClockInit(cap%config, cap%clock, cap%nsteps, rc = status)
    _VERIFY(status)
    root_set_services => cap%root_set_services
    cap%root_id = MAPL_AddChild(MAPLOBJ, name = root_name, SS = root_set_services, rc = status)
    _VERIFY(status)
    if (cap%run_hist) then
       call MAPL_Set(MAPLOBJ, CF=CAP%CF_HIST, RC=STATUS)
       _VERIFY(STATUS)
       cap%history_id = MAPL_AddChild( MAPLOBJ, name = 'HIST', SS = HIST_SetServices, rc = status)
       _VERIFY(status)
    end if
    if (cap%run_extdata) then
       call MAPL_Set(MAPLOBJ, CF=CAP%CF_EXT, RC=STATUS)
       _VERIFY(STATUS)
       if (use_extdata2g) then
#if defined(BUILD_WITH_EXTDATA2G)
          cap%extdata_id = MAPL_AddChild (MAPLOBJ, name = 'EXTDATA', SS = ExtData2G_SetServices, _RC)
#else
          _FAIL('ExtData2G requested but not built')
#endif
       else
          cap%extdata_id = MAPL_AddChild (MAPLOBJ, name = 'EXTDATA', SS = ExtData1G_SetServices, _RC)
       end if
    end if
    !  Query MAPL for the the children's for GCS, IMPORTS, EXPORTS
    !-------------------------------------------------------------
    call MAPL_Get(MAPLOBJ, childrens_gridcomps = cap%gcs, &
         childrens_import_states = cap%imports, childrens_export_states = cap%exports, rc = status)
    _VERIFY(status)
    !  Initialize the Computational Hierarchy
    !----------------------------------------
    call ESMF_GridCompInitialize(cap%gcs(cap%root_id), importState = cap%imports(cap%root_id), &
         exportState = cap%exports(cap%root_id), clock = cap%clock, userRC = status)
    _VERIFY(status)
    if (cap%run_hist) then
       ! All the EXPORTS of the Hierachy are made IMPORTS of History
       !------------------------------------------------------------
       call ESMF_StateAdd(cap%imports(cap%history_id), [cap%exports(cap%root_id)], rc = status)
       _VERIFY(STATUS)
       ! Initialize the History
       !------------------------
       call ESMF_GridCompInitialize (CAP%GCS(cap%history_id), importState=CAP%IMPORTS(cap%history_id), &
            exportState=CAP%EXPORTS(cap%history_id), clock=CAP%CLOCK, userRC=STATUS )
       _VERIFY(STATUS)
    end if
    if (cap%run_extdata) then
       ! Prepare EXPORTS for ExtData
       ! ---------------------------
       call ESMF_StateGet(cap%imports(cap%root_id), itemcount = itemcount, rc = status)
       _VERIFY(status)
       allocate(itemnames(itemcount), stat = status)
       _VERIFY(status)
       allocate(itemtypes(itemcount), stat = status)
       _VERIFY(status)
       call ESMF_StateGet(cap%imports(cap%root_id), itemnamelist = itemnames, &
            itemtypelist = itemtypes, rc = status)
       _VERIFY(status)
       do i = 1, itemcount
          if (ItemTypes(i) == ESMF_StateItem_Field) then
             call ESMF_StateGet(cap%imports(cap%root_id), itemnames(i), field, rc = status)
             _VERIFY(status)
             call MAPL_StateAdd(cap%exports(cap%extdata_id), field, rc = status)
             _VERIFY(status)
          else if (ItemTypes(i) == ESMF_StateItem_FieldBundle) then
             call ESMF_StateGet(cap%imports(cap%root_id), itemnames(i), bundle, rc = status)
             _VERIFY(status)
             call MAPL_StateAdd(cap%exports(cap%extdata_id), bundle, rc = status)
             _VERIFY(status)
          end if
       END DO
       deallocate(itemtypes)
       deallocate(itemnames)
       ! Initialize the ExtData
       !------------------------
       call ESMF_GridCompInitialize (cap%gcs(cap%extdata_id), importState = cap%imports(cap%extdata_id), &
            exportState = cap%exports(cap%extdata_id), &
            clock = cap%clock, userRc = status)
       _VERIFY(status)
    end if
    call cap%parseTimes(rc=status)
    _VERIFY(status)
    if (allocated(cap%times) .and. cap%run_fbf ) then
       _FAIL("can not run forwards and backwards with specific times")
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine initialize_gc
Call graph
initialize_gc calls ESMF_ConfigCreate, ESMF_ConfigGetAttribute, ESMF_ConfigLoadFile, ESMF_GridCompGet, ESMF_GridCompInitialize, ESMF_UtilStringUpperCase, ESMF_VMGet, esmf_stateadd, esmf_stateget, mapl_addchild, mapl_am_i_root, mapl_assert, mapl_configsetattribute, mapl_get, mapl_getnodeinfo, mapl_getresource, mapl_initializeshmem, mapl_set, mapl_stateadd, get_capgridcomp_from_gc, get_global_time_profiler, get_metacomp_from_gc, mapl_clockinit, mapl_memutilsdisable, mapl_memutilsinit, mapl_profdisable, mapl_return, mapl_verify, parsetimes