initialize_p0 – MAPL
initialize_p0 Subroutine
54 statements
Source File
private subroutine initialize_p0(model, import_state, export_state, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
type(ESMF_State) :: import_state
type(ESMF_State) :: export_state
type(ESMF_Clock) :: clock
integer, intent(out) :: rc
Calls
Contents
Source Code
initialize_p0
Source Code
    subroutine initialize_p0(model, import_state, export_state, clock, rc)
        type(ESMF_GridComp)  :: model
        type(ESMF_State)     :: import_state, export_state
        type(ESMF_Clock)     :: clock
        integer, intent(out) :: rc
        type(MAPL_Cap), pointer :: cap
        type(Cap_Wrapper)       :: wrapped_cap
        type(cap_parameters)    :: cap_params
        type(ESMF_VM) :: vm
        integer       :: my_rank, npes, mpi_comm, dup_comm, status, subcommunicator
        type(MAPL_CapOptions) :: cap_options
        logical, save         :: first = .true.
        _UNUSED_DUMMY(import_state)
        _UNUSED_DUMMY(export_state)
        _UNUSED_DUMMY(clock)
        call NUOPC_CompFilterPhaseMap(model, ESMF_METHOD_INITIALIZE, &
                acceptStringList=(/"IPDv05p"/), rc=rc)
        VERIFY_NUOPC_(rc)
        call ESMF_GridCompGet(model, vm=vm, rc=status)
        _VERIFY(status)
        call ESMF_VMGet(vm, localPet=my_rank, petCount=npes, &
                mpiCommunicator=mpi_comm, rc=status)
        _VERIFY(status)
        !call MPI_Comm_dup(mpi_comm, dup_comm, status)
        !_VERIFY(status)
        dup_comm = mpi_comm
        cap_params = get_cap_parameters_from_gc(model, status)
        _VERIFY(status)
        cap_options = MAPL_CapOptions(cap_rc_file=cap_params%cap_rc_file, rc=status)
        _VERIFY(status)
        cap_options%use_comm_world = .false.
        cap_options%comm = dup_comm
        ! cap_options%logging_config = "logging.yaml"
        cap_options%logging_config = ''
        call MPI_Comm_size(dup_comm, cap_options%npes_model, status)
        _VERIFY(status)
        allocate(cap)
        cap = MAPL_Cap(cap_params%name, cap_params%set_services,  &
                cap_options=cap_options, rc=status)
        _VERIFY(status)
        wrapped_cap%ptr => cap
        call ESMF_UserCompSetInternalState(model, "MAPL_Cap", &
                wrapped_cap, status)
        _VERIFY(status)
        call cap%initialize_mpi(rc = status)
        _VERIFY(status)
        subcommunicator = cap%create_member_subcommunicator(cap%get_comm_world(), rc=status)
        _VERIFY(status)
        if (first) then
            call cap%initialize_io_clients_servers(subcommunicator, rc=status)
            _VERIFY(status)
            first = .false.
        end if
        call cap%initialize_cap_gc()
        call cap%cap_gc%set_services(rc=status)
        _VERIFY(status)
        call cap%cap_gc%initialize(rc=status)
        _VERIFY(status)
        _RETURN(_SUCCESS)
    end subroutine initialize_p0
Call graph
initialize_p0 calls ESMF_GridCompGet, ESMF_LogFoundError, ESMF_UserCompSetInternalState, ESMF_VMGet, NUOPC_CompFilterPhaseMap, create_member_subcommunicator, get_comm_world, initialize_cap_gc, initialize_io_clients_servers, initialize_mpi, mpi_comm_size, get_cap_parameters_from_gc, mapl_return, mapl_verify
get_cap_parameters_from_gc calls ESMF_LogFoundError, mapl_return, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize