initialize_mpi – MAPL
initialize_mpi Subroutine
36 statements
Source File
private subroutine initialize_mpi(this, unusable, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_mpi(this, unusable, rc)
      class (MAPL_Cap), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: ierror, status
      integer :: provided
      integer :: npes_world
      _UNUSED_DUMMY(unusable)
      call MPI_Initialized(this%mpi_already_initialized, ierror)
      _VERIFY(ierror)
      if (.not. this%mpi_already_initialized) then
         call ESMF_InitializePreMPI(_RC)
         call MPI_Init_thread(MPI_THREAD_MULTIPLE, provided, ierror)
         _VERIFY(ierror)
         _ASSERT(provided == MPI_THREAD_MULTIPLE, 'MPI_THREAD_MULTIPLE not supported by this MPI.')
      else
         ! If we are here, then MPI has already been initialized by the user
         ! and we are just using it. But we need to make sure that the user
         ! has initialized MPI with the correct threading level.
         call MPI_Query_thread(provided, ierror)
         _VERIFY(ierror)
      end if
      _ASSERT(provided == MPI_THREAD_MULTIPLE, 'MPI_THREAD_MULTIPLE not supported by this MPI.')
      call MPI_Comm_rank(this%comm_world, this%rank, status)
      _VERIFY(status)
      call MPI_Comm_size(this%comm_world, npes_world, status)
      _VERIFY(status)
      if ( this%cap_options%npes_model == -1) then
         ! just a feed back to cap_options to maintain integrity
          this%cap_options%npes_model = npes_world
      endif
      _ASSERT(npes_world >= this%cap_options%npes_model, "npes_world is smaller than npes_model")
      this%npes_member = npes_world / this%cap_options%n_members
      _RETURN(_SUCCESS)
   end subroutine initialize_mpi
Call graph
initialize_mpi calls ESMF_InitializePreMPI, mapl_assert, mpi_comm_rank, mpi_comm_size, mpi_init_thread, mpi_initialized, mpi_query_thread, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_p0 calls initialize_mpi
new_mapl_cap_from_dso calls initialize_mpi
new_mapl_cap_from_set_services calls initialize_mpi
mapl_cap calls new_mapl_cap_from_dso, new_mapl_cap_from_set_services