initialize – MAPL
initialize Module Procedure
89 statements
Source File
module procedure initialize module subroutine initialize(this, items, bundle, timeInfo, vdata, recycle_track, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
type(GriddedIOitemVector), intent(inout), target :: items
type(ESMF_FieldBundle), intent(inout) :: bundle
type(timeData), intent(inout) :: timeInfo
type(verticalData), intent(inout), optional :: vdata
logical, intent(inout), optional :: recycle_track
integer, intent(out), optional :: rc
Calls
Call graph
initialize calls ESMF_ClockGet, esmf_fieldbundleget, create_grid, create_metadata_variable, create_new_bundle, get_obsfile_tbracket_from_epoch, mapl_am_i_root, mapl_assert, reset_times_to_current_day, add_attribute, add_dimension, add_variable, append_vertical_metadata, get_interpolating_variable, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next