initialize_from_config – MAPL
initialize_from_config Subroutine
17 statements
Source File
private subroutine initialize_from_config(this, config, unusable, rc)
Uses
MAPL_KeywordEnforcerMod
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout) :: this
type(ESMF_Config), intent(inout) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_config(this, config, unusable, rc)
      use MAPL_KeywordEnforcerMod
      class (AbstractGridFactory), intent(inout)  :: this
      type (ESMF_Config), intent(inout) :: config
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'initialize_from_config'
      _UNUSED_DUMMY(unusable)
      call this%initialize(config, prefix='', rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine initialize_from_config
Call graph
initialize_from_config calls initialize, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
initialize_from_esmf_distgrid calls mapl_assert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code