initialize_prototypes – MAPL
initialize_prototypes Subroutine
36 statements
Source File
private subroutine initialize_prototypes(this, unusable, rc)
Uses
MAPL_ExternalGridFactoryMod
MAPL_XYGridFactoryMod
MAPL_LlcGridFactoryMod
MAPL_TripolarGridFactoryMod
MAPL_CubedSphereGridFactoryMod
MAPL_SwathGridFactoryMod
MAPL_LatLonGridFactoryMod
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_prototypes(this, unusable, rc)
      use MAPL_LatLonGridFactoryMod, only: LatLonGridFactory
      use MAPL_CubedSphereGridFactoryMod, only: CubedSphereGridFactory
      use MAPL_TripolarGridFactoryMod, only: TripolarGridFactory
      use MAPL_LlcGridFactoryMod, only: LlcGridFactory
      use MAPL_ExternalGridFactoryMod, only: ExternalGridFactory
      use MAPL_XYGridFactoryMod, only: XYGridFactory
      use MAPL_SwathGridFactoryMod, only : SwathGridFactory
      class (GridManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (LatLonGridFactory) :: latlon_factory
      type (CubedSphereGridFactory) :: cubed_factory
      type (TripolarGridFactory) :: tripolar_factory
      type (LlcGridFactory) :: llc_factory
      type (ExternalGridFactory) :: external_factory
      type (XYGridFactory) :: xy_factory
      type (SwathGridFactory) :: swath_factory
      ! This is a local variable to prevent the subroutine from running
      ! initialiazation twice. Calling functions have their own local variables
      ! to prevent calling this subroutine twice, but the initialization status
      ! is not shared. This guarantees it. It's a trade-off between efficiency
      ! with a shared state variable with avoiding a shared state vartiable.
      logical, save :: initialized = .false.
      ! intialized check prevents adding same items twice
      if (.not. initialized) then
         call this%prototypes%insert('LatLon', latlon_factory)
         call this%prototypes%insert('Cubed-Sphere', cubed_factory)
         call this%prototypes%insert('Tripolar',  tripolar_factory)
         call this%prototypes%insert('llc',  llc_factory)
         call this%prototypes%insert('External', external_factory)
         call this%prototypes%insert('XY', xy_factory)
         call this%prototypes%insert('Swath', swath_factory)
         initialized = .true.
      end if
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine initialize_prototypes
Call graph
initialize_prototypes calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_insert_pair calls s_insert
mapl_throw_exception calls initialize
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
is_valid_prototype calls initialize_prototypes
make_clone calls initialize_prototypes
make_factory_from_config calls make_clone
make_factory_from_distgrid calls make_clone
make_factory_from_file calls make_clone
set_grid calls is_valid_prototype
find calls make_factory
make_grid_from_config calls make_factory
make_grid_from_distgrid calls make_factory
mapl_esmfstatereadfromfile calls make_factory
time_ave calls make_factory