initialize – MAPL
initialize Subroutine
49 statements
Source File
private subroutine initialize(this)
Type Bound
ProtocolParser
Arguments
Type Intent Optional Attributes Name
class(ProtocolParser), intent(inout) :: this
Calls
Called by
Source Code
   subroutine initialize(this)
      class (ProtocolParser), intent(inout) :: this
      type (TerminateMessage) :: terminate
      type (DoneMessage)                   :: done
      type (PrefetchDoneMessage)           :: pdone
      type (CollectivePrefetchDoneMessage) :: cpdone
      type (StageDoneMessage)              :: sdone
      type (CollectiveStageDoneMessage)    :: csdone
      type (AddExtCollectionMessage)  :: addExtCollection
      type (AddHistCollectionMessage) :: addHistCollection
      type (IdMessage):: IDid
      type (PrefetchDataMessage)    :: PrefetchData
      type (StageDataMessage) :: StageData
      type (CollectivePrefetchDataMessage) :: CollectivePrefetchData
      type (CollectiveStageDataMessage)    :: CollectiveStageData
      type (ModifyMetadataMessage) :: ModifyMetadata
      type (ReplaceMetadataMessage) :: ReplaceMetadata
      type (HandShakeMessage) :: handshake
      type (DummyMessage) :: dummy
      type (ForwardDataMessage) :: ForwardData
      if (this%initialized) return
      call add_prototype(terminate)
      call add_prototype(done)
      call add_prototype(pdone)
      call add_prototype(cpdone)
      call add_prototype(sdone)
      call add_prototype(csdone)
      call add_prototype(addExtCollection)
      addHistCollection = AddHistCollectionMessage(FileMetadata())
      call add_prototype(addHistCollection)
      call add_prototype(IDId)
      call add_prototype(PrefetchData)
      call add_prototype(CollectivePrefetchData)
      call add_prototype(StageData)
      call add_prototype(CollectiveStageData)
      ModifyMetaData = ModifyMetadataMessage(collection_id=-1)
      call add_prototype(ModifyMetadata)
      ReplaceMetaData = ReplaceMetadataMessage(-1, FileMetadata())
      call add_prototype(ReplaceMetadata)
      call add_prototype(handshake)
      call add_prototype(dummy)
      call add_prototype(ForwardData)
      this%initialized = .true.
   contains
      subroutine add_prototype(message)
         class (AbstractMessage), intent(in) :: message
         call this%prototypes%insert(message%get_type_id(), message)
      end subroutine add_prototype
   end subroutine initialize
Call graph
initialize calls get_type_id, insert
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
new_protocolparser calls initialize
protocolparser calls new_protocolparser