init_halo – MAPL
init_halo Subroutine
31 statements
Source File
private subroutine init_halo(this, unusable, rc)
Type Bound
TripolarGridFactory
Arguments
Type Intent Optional Attributes Name
class(TripolarGridFactory), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine init_halo(this, unusable, rc)
      class (TripolarGridFactory), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (ESMF_Grid) :: grid
      type (ESMF_DistGrid) :: dist_grid
      integer :: dim_count
      integer :: pet
      integer :: ndes
      type (ESMF_VM) :: vm
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'init_halo'
      _UNUSED_DUMMY(unusable)
      grid = this%make_grid(rc=status)
      _VERIFY(status)
      call ESMF_GridGet(grid,   distGrid=dist_grid, dimCount=dim_count, rc=status)
      _VERIFY(status)
      call ESMF_DistGridGet(dist_grid, delayout=this%layout, rc=status)
      _VERIFY(status)
      call ESMF_DELayoutGet (this%layout, vm=vm, rc=status)
      _VERIFY(status)
      call ESMF_VmGet(vm, localPet=pet, petCount=ndes, rc=status)
      _VERIFY(status)
      this%px = mod(pet, this%nx)
      this%py = pet / this%nx
      _RETURN(_SUCCESS)
   end subroutine init_halo
Call graph
init_halo calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, make_grid, mapl_return, mapl_verify
make_grid calls mapl_return, mapl_verify, make_new_grid
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_from_config_with_prefix calls init_halo