initialize_from_config_with_prefix – MAPL
initialize_from_config_with_prefix Subroutine
313 statements
Source File
private subroutine initialize_from_config_with_prefix(this, config, prefix, unusable, rc)
Uses
mpi
disable using currTime as obsfile_start_time if (trim(STR1)==’‘) then this%obsfile_start_time = currTime call ESMF_TimeGet(currTime, timestring=STR1, rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/base/MAPL_SwathGridFactory.F90”,505 ,rc)) return if (mapl_am_I_root()) then write(6,105) ‘obs_file_begin missing, default = currTime :’, trim(STR1) endif else call ESMF_TimeSet(this%obsfile_start_time, timestring=STR1, rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/base/MAPL_SwathGridFactory.F90”,510 ,rc)) return if (mapl_am_I_root()) then write(6,105) ‘obs_file_begin provided: ‘, trim(STR1) end if end if
write(6,’(a)’) ‘this%t_alongtrack(::50)=’ write(6,’(5f20.2)’) this%t_alongtrack(::50)
Type Bound
SwathGridFactory
Arguments
Type Intent Optional Attributes Name
class(SwathGridFactory), intent(inout) :: this
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: prefix
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_config_with_prefix(this, config, prefix, unusable, rc)
      use MPI
      implicit none
      class (SwathGridFactory), intent(inout) :: this
      type (ESMF_Config), intent(inout) :: config
      character(len=*), intent(in) :: prefix
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_VM) :: VM
      integer:: mpic
      integer:: irank, ierror
      integer :: nlon, nlat, tdim
      integer :: Xdim, Ydim, ntime
      integer :: nx, ny
      character(len=ESMF_MAXSTR) :: key_lon, key_lat, key_time
      character(len=ESMF_MAXSTR) :: tunit, grp1, grp2
      character(len=ESMF_MAXSTR) :: filename, STR1, tmp
      character(len=ESMF_MAXSTR) :: symd, shms
      real(ESMF_KIND_R8), allocatable :: scanTime(:,:)
      real(ESMF_KIND_R8), allocatable :: lon_true(:,:)
      real(ESMF_KIND_R8), allocatable :: lat_true(:,:)
      integer :: yy, mm, dd, h, m, s, sec, second
      integer :: i, j, L
      integer :: ncid, ncid2, varid
      integer :: fid_s, fid_e
      integer :: M_file
      type(ESMF_Time) :: currTime
      integer (ESMF_KIND_I8) :: j0, j1, jt, jt1, jt2
      real(ESMF_KIND_R8) :: jx0, jx1
      real(ESMF_KIND_R8) :: x0, x1
      integer :: khi, klo, k, nstart, nend, max_iter
      type(Logger), pointer :: lgr
      logical :: ispresent
      type(ESMF_TimeInterval) :: Toff, obs_time_span
      _UNUSED_DUMMY(unusable)
      lgr => logging%get_logger('HISTORY.sampler')
      call ESMF_VmGetCurrent(VM, _RC)
      !   input :  config
      !   output:  this%epoch_index,  nx, ny
      !
      !   Read in specs, crop epoch_index based on scanTime
      !__ s1. read in file spec.
      !
      call ESMF_ConfigGetAttribute(config, tmp, label=prefix//'GRIDNAME:', default=MAPL_GRID_NAME_DEFAULT)
      this%grid_name = trim(tmp)
      call ESMF_ConfigGetAttribute(config, this%nx,  label=prefix//'NX:', default=MAPL_UNDEFINED_INTEGER)
      call ESMF_ConfigGetAttribute(config, this%ny,  label=prefix//'NY:', default=MAPL_UNDEFINED_INTEGER)
      call ESMF_ConfigGetAttribute(config, this%lm,  label=prefix//'LM:', default=MAPL_UNDEFINED_INTEGER)
      call ESMF_ConfigGetAttribute(config, this%input_template, label=prefix//'GRID_FILE:', default='unknown.txt', _RC)
      call ESMF_ConfigGetAttribute(config, this%epoch, label=prefix//'Epoch:', default=300, _RC)
      call ESMF_ConfigGetAttribute(config, tmp,      label=prefix//'Epoch_init:', default='2006', _RC)
      write(6,'(2x,a,100i10)') 'nail 2, nx,ny,im,jm,lm',&
           this%nx,this%ny,this%im_world,this%jm_world,this%lm
      call lgr%debug(' %a  %a', 'CurrTime =', trim(tmp))
      if ( index(tmp, 'T') /= 0 .OR. index(tmp, '-') /= 0 ) then
         call ESMF_TimeSet(currTime, timeString=tmp, _RC)
      else
         read(tmp,'(i4,5i2)') yy,mm,dd,h,m,s
         call ESMF_Timeset(currTime, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
      endif
      second = hms_2_s(this%Epoch)
      call ESMF_TimeIntervalSet(this%epoch_frequency, s=second, _RC)
      call ESMF_ConfigGetAttribute(config, value=STR1, default="", &
           label= prefix// 'obs_file_begin:', _RC)
      _ASSERT (trim(STR1)/='', 'obs_file_begin missing, critical for data with 5 min interval!')
      call ESMF_TimeSet(this%obsfile_start_time, timestring=STR1, _RC)
      !!disable using currTime as obsfile_start_time
      !!if (trim(STR1)=='') then
      !!   this%obsfile_start_time = currTime
      !!   call ESMF_TimeGet(currTime, timestring=STR1, _RC)
      !!   if (mapl_am_I_root()) then
      !!      write(6,105) 'obs_file_begin missing, default = currTime :', trim(STR1)
      !!   endif
      !!else
      !!   call ESMF_TimeSet(this%obsfile_start_time, timestring=STR1, _RC)
      !!   if (mapl_am_I_root()) then
      !!      write(6,105) 'obs_file_begin provided: ', trim(STR1)
      !!   end if
      !!end if
      if (mapl_am_I_root()) then
         write(6,105) 'obs_file_begin provided: ', trim(STR1)
      end if
      call ESMF_ConfigGetAttribute(config, value=STR1, default="", &
           label=prefix // 'obs_file_end:', _RC)
      if (trim(STR1)=='') then
         call ESMF_TimeIntervalSet(obs_time_span, d=100, _RC)
         this%obsfile_end_time = this%obsfile_start_time + obs_time_span
         call ESMF_TimeGet(this%obsfile_end_time, timestring=STR1, _RC)
         if (mapl_am_I_root()) then
            write(6,105) 'obs_file_end   missing, default = begin+100D:', trim(STR1)
         endif
      else
         call ESMF_TimeSet(this%obsfile_end_time, timestring=STR1, _RC)
         if (mapl_am_I_root()) then
            write(6,105) 'obs_file_end provided:', trim(STR1)
         end if
      end if
      call ESMF_ConfigGetAttribute(config, value=STR1, default="", &
           label= prefix// 'obs_file_interval:', _RC)
      _ASSERT(STR1/='', 'fatal error: obs_file_interval not provided in RC file')
      if (mapl_am_I_root()) write(6,105) 'obs_file_interval:', trim(STR1)
      if (mapl_am_I_root()) write(6,106) 'Epoch (second)   :', second
      i= index( trim(STR1), ' ' )
      if (i>0) then
         symd=STR1(1:i-1)
         shms=STR1(i+1:)
      else
         symd=''
         shms=trim(STR1)
      endif
      call convert_twostring_2_esmfinterval (symd, shms,  this%obsfile_interval, _RC)
      call ESMF_ConfigGetAttribute(config, value=this%index_name_lon, default="", &
           label=prefix // 'index_name_lon:', _RC)
      call ESMF_ConfigGetAttribute(config, value=this%index_name_lat, default="", &
                 label=prefix // 'index_name_lat:', _RC)
      call ESMF_ConfigGetAttribute(config, this%var_name_lon, &
           label=prefix // 'var_name_lon:', default="", _RC)
      call ESMF_ConfigGetAttribute(config, this%var_name_lat, &
           label=prefix // 'var_name_lat:', default="", _RC)
      call ESMF_ConfigGetAttribute(config, this%var_name_time, default="", &
           label=prefix//'var_name_time:',  _RC)
      call ESMF_ConfigGetAttribute(config, this%tunit, default="", &
           label=prefix//'tunit:',  _RC)
      call lgr%debug(' %a  %a', 'input_template =', trim(this%input_template))
      !__ s2. find obsFile even if missing on disk and get array: this%t_alongtrack(:)
      !
      call ESMF_VMGet(vm, mpiCommunicator=mpic, _RC)
      call MPI_COMM_RANK(mpic, irank, ierror)
      if (irank==0) &
           write(6,'(10(2x,a20,2x,a40,/))') &
           'index_name_lon:', trim(this%index_name_lon), &
           'index_name_lat:', trim(this%index_name_lat), &
           'var_name_lon:',   trim(this%var_name_lon), &
           'var_name_lat:',   trim(this%var_name_lat), &
           'var_name_time:',  trim(this%var_name_time), &
           'tunit:',          trim(this%tunit)
      if (irank==0) then
         call ESMF_TimeIntervalSet(Toff, h=0, m=0, s=0, _RC)
         call Find_M_files_for_currTime (currTime, &
              this%obsfile_start_time, this%obsfile_end_time, this%obsfile_interval, &
              this%epoch_frequency,  this%input_template, M_file, this%filenames, &
              T_offset_in_file_content = Toff,  _RC)
         this%M_file = M_file
         write(6,'(10(2x,a20,2x,i40))') &
              'M_file:', M_file
         do i=1, M_file
            write(6,'(10(2x,a14,i4,a2,2x,a))') &
                 'filenames(', i, '):', trim(this%filenames(i))
         end do
         !------------------------------------------------------------
         !  QC for obs files:
         !
         !  1.  redefine nstart to skip un-defined time value
         !  2.  Scan_Start_Time =  -9999, -9999, -9999,
         !      ::  eliminate this row of data
         !------------------------------------------------------------
         allocate(lon_true(0,0), lat_true(0,0), scanTime(0,0))
         call read_M_files_4_swath (this%filenames(1:M_file), nx, ny, &
              this%index_name_lon, this%index_name_lat, &
              var_name_lon=this%var_name_lon, &
              var_name_lat=this%var_name_lat, &
              var_name_time=this%var_name_time, &
              lon=lon_true, lat=lat_true, time=scanTime, &
              Tfilter=.true., _RC)
         nlon=nx
         nlat=ny
         allocate(this%t_alongtrack(nlat))
         do j=1, nlat
            this%t_alongtrack(j) = scanTime(1,j)
         end do
         !!write(6,'(a)')  'this%t_alongtrack(::50)='
         !!write(6,'(5f20.2)')  this%t_alongtrack(::50)
         nstart = 1
         !
         ! If the t_alongtrack contains undefined values, use this code
         !
         x0 = this%t_alongtrack(1)
         x1 = 1.d16
         if (x0 > x1) then
            !
            ! bisect backward finding the first index arr[n] < x1
            klo=1
            khi=nlat
            max_iter = int( log( real(nlat) ) / log(2.d0) ) + 2
            do i=1, max_iter
               k = (klo+khi)/2
               if ( this%t_alongtrack(k) < x1 ) then
                  khi=k
               else
                  nstart = khi
                  exit
               endif
            enddo
            call lgr%debug('%a %i4', 'nstart', nstart)
            call lgr%debug('%a %i4', 'this%t_alongtrack(nstart)',  this%t_alongtrack(nstart))
         endif
         this%cell_across_swath = nlon
         this%cell_along_swath = nlat
         deallocate(scanTime)
         ! P2.
         ! determine im_world from Epoch
         ! -----------------------------
         ! t_axis = t_alongtrack = t_a
         ! convert currTime to j0
         ! use Epoch to find j1
         ! search j0, j1 in t_a
         call time_esmf_2_nc_int (currTime, this%tunit, j0, _RC)
         sec = hms_2_s (this%Epoch)
         j1= j0 + sec
         jx0= j0
         jx1= j1
         this%epoch_index(1)= 1
         this%epoch_index(2)= this%cell_across_swath
         nend = this%cell_along_swath
         call bisect( this%t_alongtrack, jx0, jt1, n_LB=int(nstart, ESMF_KIND_I8), n_UB=int(nend, ESMF_KIND_I8), rc=rc)
         call bisect( this%t_alongtrack, jx1, jt2, n_LB=int(nstart, ESMF_KIND_I8), n_UB=int(nend, ESMF_KIND_I8), rc=rc)
         call lgr%debug ('%a %i20 %i20', 'nstart, nend', nstart, nend)
         call lgr%debug ('%a %f20.1 %f20.1', 'j0[currT]    j1[T+Epoch]  w.r.t. timeunit ', jx0, jx1)
         call lgr%debug ('%a %f20.1 %f20.1', 'x0[times(1)] xn[times(N)] w.r.t. timeunit ', &
              this%t_alongtrack(1), this%t_alongtrack(nend))
         call lgr%debug ('%a %i20 %i20', 'jt1, jt2 [final intercepted position]', jt1, jt2)
         if (jt1==jt2) then
            _FAIL('Epoch Time is too small, empty swath grid is generated, increase Epoch')
         endif
         jt1 = jt1 + 1               ! (x1,x2]  design
         this%epoch_index(3)= jt1
         this%epoch_index(4)= jt2
         _ASSERT( jt1 < jt2, 'Swath grid fail : epoch_index(3) > epoch_index(4)')
         Xdim = this%cell_across_swath
         Ydim = this%epoch_index(4) - this%epoch_index(3) + 1
         call lgr%debug ('%a %i4 %i4', 'bisect for j0:  rc, jt', rc, jt1)
         call lgr%debug ('%a %i4 %i4', 'bisect for j1:  rc, jt', rc, jt2)
         call lgr%debug ('%a %i4 %i4', 'Xdim, Ydim', Xdim, Ydim)
         call lgr%debug ('%a %i4 %i4 %i4 %i4', 'this%epoch_index(4)', &
              this%epoch_index(1), this%epoch_index(2), &
              this%epoch_index(3), this%epoch_index(4))
         this%im_world = Xdim
         this%jm_world = Ydim
      end if
      call MPI_bcast(this%M_file, 1, MPI_INTEGER, 0, mpic, ierror)
      do i=1, this%M_file
         call MPI_bcast(this%filenames(i), ESMF_MAXSTR, MPI_CHARACTER, 0, mpic, ierror)
      end do
      call MPI_bcast(this%epoch_index, 4, MPI_INTEGER8, 0, mpic, ierror)
      call MPI_bcast(this%im_world, 1, MPI_INTEGER, 0, mpic, ierror)
      call MPI_bcast(this%jm_world, 1, MPI_INTEGER, 0, mpic, ierror)
      call MPI_bcast(this%cell_across_swath, 1, MPI_INTEGER, 0, mpic, ierror)
      call MPI_bcast(this%cell_along_swath, 1, MPI_INTEGER, 0, mpic, ierror)
      ! donot need to bcast this%along_track (root only)
      call ESMF_ConfigGetAttribute(config, tmp, label=prefix//'IMS_FILE:', rc=status)
      if ( status == _SUCCESS ) then
         call get_ims_from_file(this%ims, trim(tmp),this%nx, _RC)
      else
         call get_multi_integer(this%ims, 'IMS:', _RC)
      endif
      call ESMF_ConfigGetAttribute(config, tmp, label=prefix//'JMS_FILE:', rc=status)
      if ( status == _SUCCESS ) then
         call get_ims_from_file(this%jms, trim(tmp),this%ny, _RC)
      else
         call get_multi_integer(this%jms, 'JMS:', _RC)
      endif
      ! ims is set at here
      call this%check_and_fill_consistency(_RC)
      _RETURN(_SUCCESS)
105      format (1x,a,2x,a)
106      format (1x,a,2x,10i8)
   contains
      subroutine get_multi_integer(values, label, rc)
         integer, allocatable, intent(out) :: values(:)
         character(len=*) :: label
         integer, optional, intent(out) :: rc
         integer :: i
         integer :: n
         integer :: tmp
         integer :: status
         logical :: isPresent
         call ESMF_ConfigFindLabel(config, label=prefix//label, isPresent=isPresent, _RC)
         if (.not. isPresent) then
            _RETURN(_SUCCESS)
         end if
         ! First pass:  count values
         n = 0
         do
            call ESMF_ConfigGetAttribute(config, tmp, rc=status)
            if (status /= _SUCCESS) then
               exit
            else
               n = n + 1
            end if
         end do
         ! Second pass: allocate and fill
         allocate(values(n), stat=status) ! no point in checking status
         _VERIFY(status)
         call ESMF_ConfigFindLabel(config, label=prefix//label,_RC)
         do i = 1, n
            call ESMF_ConfigGetAttribute(config, values(i), _RC)
            write(6,*) 'values(i)=', values(i)
         end do
         _RETURN(_SUCCESS)
      end subroutine get_multi_integer
      subroutine get_ims_from_file(values, file_name, n, rc)
         integer, allocatable, intent(out) :: values(:)
         character(len=*), intent(in) :: file_name
         integer, intent(in) :: n
         integer, optional, intent(out) :: rc
         logical :: FileExists
         integer :: i, total, unit
         integer :: status
         inquire(FILE = trim(file_name), EXIST=FileExists)
         allocate(values(n), stat=status) ! no point in checking status
         _VERIFY(status)
         _ASSERT(FileExists, "File <"//trim(file_name)//"> not found")
         if (MAPL_AM_I_Root(VM)) then
            open(newunit=UNIT, file=trim(file_name), form="formatted", iostat=status )
            _VERIFY(STATUS)
            read(UNIT,*) total
            _ASSERT(total == n, trim(file_name) // " n is different from total")
            do i = 1,total
                read(UNIT,*) values(i)
            enddo
            close(UNIT)
         endif
         call MAPL_CommsBcast(VM, values, n=N, ROOT=MAPL_Root, _RC)
         _RETURN(_SUCCESS)
      end subroutine get_ims_from_file
      subroutine get_range(range, label, rc)
         type(RealMinMax), intent(out) :: range
         character(len=*) :: label
         integer, optional, intent(out) :: rc
         integer :: i
         integer :: n
         integer :: status
         logical :: isPresent
         call ESMF_ConfigFindLabel(config, label=prefix//label,isPresent=isPresent,_RC)
         if (.not. isPresent) then
            _RETURN(_SUCCESS)
         end if
         ! Must be 2 values: min and max
         call ESMF_ConfigGetAttribute(config, range%min, _RC)
         call ESMF_ConfigGetAttribute(config, range%max, _RC)
         _RETURN(_SUCCESS)
      end subroutine get_range
   end subroutine initialize_from_config_with_prefix
Call graph
initialize_from_config_with_prefix calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_TimeGet, ESMF_TimeIntervalSet, ESMF_TimeSet, ESMF_VMGet, ESMF_VMGetCurrent, bisect, hms_2_s, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_bcast, mpi_comm_rank, get_logger, check_and_fill_consistency, convert_twostring_2_esmfinterval, debug, find_m_files_for_currtime, mapl_return, mapl_verify, read_m_files_4_swath, time_esmf_2_nc_int