initialize – MAPL
initialize Module Subroutine
86 statements
Source File
module subroutine initialize(this, duration, frequency, items, bundle, timeInfo, vdata, global_attributes, reinitialize, rc) Interface →
if (mapl_am_i_root()) write(6,*) ‘mask smod init: item%xname:’, trim(item%xname)
Arguments
Type Intent Optional Attributes Name
class(MaskSampler), intent(inout) :: this
integer, intent(in) :: duration
integer, intent(in) :: frequency
type(GriddedIOitemVector), intent(inout), optional :: items
type(ESMF_FieldBundle), intent(inout), optional :: bundle
type(timeData), intent(inout), optional :: timeInfo
type(verticalData), intent(inout), optional :: vdata
type(StringStringMap), intent(in), optional, target :: global_attributes
logical, intent(in), optional :: reinitialize
integer, intent(out), optional :: rc
Calls
Called by
Source Code
module subroutine initialize(this,duration,frequency,items,bundle,timeInfo,vdata,global_attributes,reinitialize,rc)
   class(MaskSampler), intent(inout) :: this
   integer, intent(in) :: duration
   integer, intent(in) :: frequency
   type(GriddedIOitemVector), optional, intent(inout) :: items
   type(ESMF_FieldBundle), optional, intent(inout)   :: bundle
   type(TimeData), optional, intent(inout)           :: timeInfo
   type(VerticalData), optional, intent(inout)       :: vdata
   type(StringStringMap), target, intent(in), optional :: global_attributes
   logical, optional, intent(in)           :: reinitialize
   integer, optional, intent(out)          :: rc
   integer :: status
   type(ESMF_Grid) :: grid
   type(variable) :: v
   type(GriddedIOitemVectorIterator) :: iter
   type(GriddedIOitem), pointer :: item
   type(ESMF_Time)            :: currTime
   integer :: n1, n2, k, j
   integer :: ic_2d, ic_3d, rank
   type(ESMF_Field) :: src_field
   if (.not. present(reinitialize)) then
      if(present(bundle))   this%bundle=bundle
      if(present(items))    this%items=items
      if(present(timeInfo)) this%timeinfo=timeInfo
      if(present(vdata)) then
         this%vdata=vdata
      else
         this%vdata=VerticalData(_RC)
      end if
   end if
   _ASSERT(present(global_attributes), 'PFIO needs global_attributes')
!   this%do_vertical_regrid = (this%vdata%regrid_type /= VERTICAL_METHOD_NONE)
!   if (this%vdata%regrid_type == VERTICAL_METHOD_ETA2LEV) call this%vdata%get_interpolating_variable(this%bundle,_RC)
   this%obs_written = 0
   call this%create_Geosat_grid_find_mask(_RC)
   call this%create_metadata(global_attributes,_RC)
   n1 = MAPL_nsecf( duration )
   n2 = MAPL_nsecf( frequency )
   _ASSERT (n2>0, "list%frequency ==0, fail!")
   this%tmax =  n1/n2
   if (this%use_pfio) then
      ic_2d=0
      ic_3d=0
      iter = this%items%begin()
      do while (iter /= this%items%end())
         item => iter%get()
         if (item%itemType == ItemTypeScalar) then
            !! if (mapl_am_i_root()) write(6,*) 'mask smod init: item%xname:', trim(item%xname)
            call ESMF_FieldBundleGet(this%bundle,trim(item%xname),field=src_field,_RC)
            call ESMF_FieldGet(src_field,rank=rank,_RC)
            if (rank==2) then
               ic_2d = ic_2d + 1
            else if (rank==3) then
               ic_3d = ic_3d + 1
            end if
         end if
         call iter%next()
      end do
      allocate ( this%var2d(ic_2d), _STAT )
      allocate ( this%var3d(ic_3d), _STAT )
      do j=1, ic_2d
         if (mapl_am_i_root()) then
            allocate ( this%var2d(j)%array_x(this%npt_mask_tot), _STAT )
         else
            allocate ( this%var2d(j)%array_x(0), _STAT )
         end if
      end do
      do j=1, ic_3d
         if (mapl_am_i_root()) then
            allocate ( this%var3d(j)%array_xz(this%npt_mask_tot, this%vdata%lm), _STAT )
         else
            allocate ( this%var3d(j)%array_xz(0,0), _STAT )
         end if
      end do
   end if
   _RETURN(_SUCCESS)
end subroutine initialize
Call graph
initialize calls esmf_fieldbundleget, esmf_fieldget, create_geosat_grid_find_mask, create_metadata, mapl_am_i_root, mapl_assert, mapl_nsecf, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next, initialize
create_geosat_grid_find_mask calls create_geosat_grid_find_mask
create_metadata calls create_metadata
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_nsecf calls mapl_nsecf
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception