initialize_array_R4 – MAPL
initialize_array_R4 Subroutine
9 statements
Source File
public subroutine initialize_array_R4(x, xmin, xrange)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(inout) :: x(:,:)
real(kind=ESMF_KIND_R4), intent(in) :: xmin
real(kind=ESMF_KIND_R4), intent(in) :: xrange
Calls
Called by
Source Code
   subroutine initialize_array_R4(x, xmin, xrange)
      real(ESMF_KIND_R4), intent(inout) :: x(:,:)
      real(ESMF_KIND_R4), intent(in) :: xmin
      real(ESMF_KIND_R4), intent(in) :: xrange
      integer :: rc
      _ASSERT(xrange > 0, 'Range for random numbers must be positive.')
      call random_number(x)
      x = xrange * x + xmin
   end subroutine initialize_array_R4
Call graph
initialize_array_r4 calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_array calls initialize_array_r4
test_fieldconvertprec_r4r8 calls initialize_array