initialize_from_file_metadata – MAPL
initialize_from_file_metadata Subroutine
87 statements
Source File
private subroutine initialize_from_file_metadata(this, file_metadata, unusable, force_file_coordinates, rc)
Uses
MAPL_KeywordEnforcerMod
MAPL_BaseMod
Type Bound
SwathGridFactory
Arguments
Type Intent Optional Attributes Name
class(SwathGridFactory), intent(inout) :: this
type(FileMetadata), intent(in), target :: file_metadata
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: force_file_coordinates
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine initialize_from_file_metadata(this, file_metadata, unusable, force_file_coordinates, rc)
      use MAPL_KeywordEnforcerMod
      use MAPL_BaseMod, only: MAPL_DecomposeDim
      class (SwathGridFactory), intent(inout)  :: this
      type (FileMetadata), target, intent(in) :: file_metadata
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in) :: force_file_coordinates
      integer, optional, intent(out) :: rc
      integer :: status
      class (CoordinateVariable), pointer :: v
      class (*), pointer :: ptr(:)
      character(:), allocatable :: lon_name
      character(:), allocatable :: lat_name
      character(:), allocatable :: lev_name
      integer :: i
      logical :: hasLon, hasLat, hasLongitude, hasLatitude, hasLev,hasLevel,regLat,regLon
      real(kind=REAL64) :: del12,delij
      integer :: i_min, i_max
      real(kind=REAL64) :: d_lat, d_lat_temp, extrap_lat
      logical :: is_valid, use_file_coords, compute_lons, compute_lats
      _UNUSED_DUMMY(unusable)
      if (present(force_file_coordinates)) then
         use_file_coords = force_file_Coordinates
      else
         use_file_coords = .false.
      end if
      ! Cannot assume that lats and lons are evenly spaced
      associate (im => this%im_world, jm => this%jm_world, lm => this%lm)
         lon_name = 'lon'
         hasLon = file_metadata%has_dimension(lon_name)
         if (hasLon) then
            im = file_metadata%get_dimension(lon_name, _RC)
         else
            lon_name = 'longitude'
            hasLongitude = file_metadata%has_dimension(lon_name)
            if (hasLongitude) then
               im = file_metadata%get_dimension(lon_name, _RC)
            else
               _FAIL('no longitude coordinate')
            end if
         end if
         lat_name = 'lat'
         hasLat = file_metadata%has_dimension(lat_name)
         if (hasLat) then
            jm = file_metadata%get_dimension(lat_name, _RC)
         else
            lat_name = 'latitude'
            hasLatitude = file_metadata%has_dimension(lat_name)
            if (hasLatitude) then
               jm = file_metadata%get_dimension(lat_name, _RC)
            else
               _FAIL('no latitude coordinate')
            end if
         end if
         hasLev=.false.
         hasLevel=.false.
         lev_name = 'lev'
         hasLev = file_metadata%has_dimension(lev_name)
         if (hasLev) then
            lm = file_metadata%get_dimension(lev_name,_RC)
         else
            lev_name = 'levels'
            hasLevel = file_metadata%has_dimension(lev_name)
            if (hasLevel) then
               lm = file_metadata%get_dimension(lev_name,_RC)
            end if
         end if
    end associate
    call this%make_arbitrary_decomposition(this%nx, this%ny, _RC)
    ! Determine IMS and JMS with constraint for ESMF that each DE has at least an extent
    ! of 2.  Required for ESMF_FieldRegrid().
    allocate(this%ims(0:this%nx-1))
    allocate(this%jms(0:this%ny-1))
    call MAPL_DecomposeDim(this%im_world, this%ims, this%nx, min_DE_extent=2)
    call MAPL_DecomposeDim(this%jm_world, this%jms, this%ny, min_DE_extent=2)
    call this%check_and_fill_consistency(_RC)
    _RETURN(_SUCCESS)
   end subroutine initialize_from_file_metadata
Call graph
initialize_from_file_metadata calls mapl_assert, mapl_decomposedim, check_and_fill_consistency, get_dimension, has_dimension, make_arbitrary_decomposition, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_decomposedim calls mapl_decomposedim
check_and_fill_consistency calls mapl_return, mapl_verify, check_decomposition, generate_newnxy
get_dimension calls mapl_return, at, find
has_dimension calls mapl_return, find
make_arbitrary_decomposition calls mapl_return, mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
check_decomposition calls mapl_return
generate_newnxy calls mapl_decomposedim, mapl_return, generate_new_decomp
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize