initialize_cap_gc – MAPL
initialize_cap_gc Subroutine
24 statements
Source File
private subroutine initialize_cap_gc(this, unusable, n_run_phases, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: n_run_phases
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_cap_gc(this, unusable, n_run_phases, rc)
     class(MAPL_Cap), target, intent(inout) :: this
     class (KeywordEnforcer), optional, intent(in) :: unusable
     integer, optional, intent(in) :: n_run_phases
     integer, optional, intent(out) :: rc
     integer :: status
     type(ESMF_PIN_Flag) :: pinflag
     _UNUSED_DUMMY(unusable)
     pinflag = GetPinFlagFromConfig(this%cap_options%cap_rc_file, _RC)
     call MAPL_PinFlagSet(pinflag)
     if (this%non_dso) then
        call MAPL_CapGridCompCreate(this%cap_gc, this%get_cap_rc_file(), &
           this%name, this%get_egress_file(), n_run_phases=n_run_phases, root_set_services = this%set_services,rc=status)
     else
        _ASSERT(this%cap_options%root_dso /= 'none',"No set services specified, must pass a dso")
        call MAPL_CapGridCompCreate(this%cap_gc, this%get_cap_rc_file(), &
           this%name, this%get_egress_file(), n_run_phases=n_run_phases, root_dso = this%cap_options%root_dso,rc=status)
     end if
     _VERIFY(status)
     _RETURN(_SUCCESS)
   end subroutine initialize_cap_gc
Call graph
initialize_cap_gc calls mapl_assert, get_cap_rc_file, get_egress_file, getpinflagfromconfig, mapl_capgridcompcreate, mapl_pinflagset, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
getpinflagfromconfig calls mapl_assert, mapl_return, mapl_verify, ESMF_ConfigCreate, ESMF_ConfigDestroy, ESMF_ConfigGetAttribute, ESMF_ConfigLoadFile
mapl_capgridcompcreate calls mapl_assert, mapl_return, mapl_verify, ESMF_ConfigCreate, ESMF_ConfigLoadFile, ESMF_GridCompCreate, ESMF_UserCompSetInternalState, mapl_set, mapl_internalstatecreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_UserCompSetInternalState, ESMF_GridCompGet, get_component, initialize, set_composite
mapl_throw_exception calls initialize
initialize_p0 calls initialize_cap_gc
run_model calls initialize_cap_gc
run_member calls run_model
run_ensemble calls run_member
run calls run_ensemble