initialize_subclass – MAPL
initialize_subclass Subroutine
71 statements
Source File
private subroutine initialize_subclass(this, unusable, rc)
Uses
MAPL_BaseMod
MAPL_KeywordEnforcerMod
Type Bound
TilingRegridder
Arguments
Type Intent Optional Attributes Name
class(TilingRegridder), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_subclass(this, unusable, rc)
      use MAPL_KeywordEnforcerMod
      use MAPL_BaseMod, only: MAPL_GridGet
      class (TilingRegridder), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = 'initialize_subclass'
      type (TileFile) :: tile_file
      character(len=:), allocatable :: file_name ! tile file
      logical :: swap
      integer :: idx_tiling_in
      integer :: idx_tiling_out
      type (RegridderSpec) :: spec
      _UNUSED_DUMMY(unusable)
      call this%find_tile_file(file_name, swap, rc=status)
      _VERIFY(status)
      select case (this%file_type)
      case (GEOS_BINARY)
         tile_file = read_geos_binary(file_name, rc=status)
         _VERIFY(status)
      case (TEMPEST)
         tile_file = read_tempest(file_name, rc=status)
         _VERIFY(status)
      end select
      if (swap) then
         idx_tiling_in = 2
         idx_tiling_out = 1
      else
         idx_tiling_in = 1
         idx_tiling_out = 2
      end if
      ! Copy tile_file into global_x_tiles
      if(MAPL_ShmInitialized) then
         call MAPL_AllocNodeArray( this%global_x_tiles,(/tile_file%n_tiles/),rc=status)
         _VERIFY(STATUS)
      else
         allocate(this%global_x_tiles(tile_file%n_tiles),stat=status)
         _VERIFY(STATUS)
      end if
      if (.not. MAPL_ShmInitialized  .or. MAPL_AmNodeRoot) then
         associate (tiles => this%global_x_tiles)
           tiles(:)%idx_i_in = tile_file%grid_tiles(idx_tiling_in)%i_indices(:)
           tiles(:)%idx_j_in = tile_file%grid_tiles(idx_tiling_in)%j_indices(:)
           tiles(:)%idx_i_out = tile_file%grid_tiles(idx_tiling_out)%i_indices(:)
           tiles(:)%idx_j_out = tile_file%grid_tiles(idx_tiling_out)%j_indices(:)
           tiles(:)%weight = tile_file%grid_tiles(idx_tiling_out)%weights(:)
         end associate
      end if
      call MAPL_SyncSharedMemory(rc=status)
      _VERIFY(status)
      ! Copy local subset of global_x_tiles into local_x_tiles
      call this%copy_global_to_local()
      associate (tile => tile_file%grid_tiles(idx_tiling_out))
        this%out_shape = [tile%im, tile%jm]
      end associate
      spec = this%get_spec()
      if (iand(spec%hints, REGRID_HINT_LOCAL) /= 0) then
         _DEALOCS(this%global_x_tiles)
      end if
      _RETURN(_SUCCESS)
   end subroutine initialize_subclass
Call graph
initialize_subclass calls mapl_allocnodearray, mapl_deallocnodearray, mapl_syncsharedmemory, copy_global_to_local, find_tile_file, get_spec, mapl_return, mapl_verify, read_geos_binary, read_tempest
initialize_base calls initialize
make_regridder_from_grids calls initialize
newlatlontolatlonregridder calls initialize
latlontolatlonregridder calls newlatlontolatlonregridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder