init – MAPL
init Subroutine
19 statements
Source File
private subroutine init(this)
Uses
MAPL_VotingRegridderMod
MAPL_ConservativeRegridderMod
mapl_HorizontalFluxRegridder
MAPL_FractionalRegridderMod
MAPL_LatLonToLatLonRegridderMod
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout) :: this
Calls
Called by
Source Code
   subroutine init(this)
     use MAPL_LatLonToLatLonRegridderMod
     use MAPL_ConservativeRegridderMod
     use MAPL_VotingRegridderMod
     use MAPL_FractionalRegridderMod
     use MAPL_HorizontalFluxRegridder
     class (RegridderManager), intent(inout) :: this
     type (ConservativeRegridder) :: regridder1
     type (LatLonToLatLonRegridder) :: regridder2
     type (VotingRegridder) :: regridder3
     type (FractionalRegridder) :: regridder4
     type (HorizontalFluxRegridder) :: regridder5
     call this%add_prototype('LatLon', 'LatLon', REGRID_METHOD_CONSERVE, regridder1)
     call this%add_prototype('LatLon', 'LatLon', REGRID_METHOD_BILINEAR, regridder2)
     call this%add_prototype('LatLon', 'LatLon', REGRID_METHOD_VOTE, regridder3)
     call this%add_prototype('LatLon', 'LatLon', REGRID_METHOD_FRACTION, regridder4)
     call this%add_prototype('Cubed-Sphere', 'Cubed_Sphere', &
          REGRID_METHOD_CONSERVE_HFLUX, regridder5)
     this%initialized = .true.
   end subroutine init
Call graph
init calls add_prototype
add_prototype_by_grid_types calls add_prototype
make_regridder_from_grids calls init
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder