initialize_io_clients_servers – MAPL
initialize_io_clients_servers Subroutine
15 statements
Source File
private subroutine initialize_io_clients_servers(this, comm, unusable, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout), target :: this
integer, intent(in) :: comm
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine initialize_io_clients_servers(this, comm, unusable, rc)
     class (MAPL_Cap), target, intent(inout) :: this
     integer, intent(in) :: comm
     class (KeywordEnforcer), optional, intent(in) :: unusable
     integer, optional, intent(out) :: rc
     integer :: status
     _UNUSED_DUMMY(unusable)
     call this%cap_server%initialize(comm, &
         application_size=this%cap_options%npes_model, &
         nodes_input_server=this%cap_options%nodes_input_server, &
         nodes_output_server=this%cap_options%nodes_output_server, &
         npes_input_server=this%cap_options%npes_input_server, &
         npes_output_server=this%cap_options%npes_output_server, &
         oserver_type=this%cap_options%oserver_type, &
         npes_backend_pernode=this%cap_options%npes_backend_pernode, &
         isolate_nodes = this%cap_options%isolate_nodes, &
         fast_oclient  = this%cap_options%fast_oclient, &
         with_profiler = this%cap_options%with_io_profiler, &
         rc=status)
     _VERIFY(status)
     _RETURN(_SUCCESS)
   end subroutine initialize_io_clients_servers
Call graph
initialize_io_clients_servers calls initialize, mapl_return, mapl_verify
initialize calls mapl_return, mapl_verify, init_io_clientmanager, mapl_assert, mpi_barrier, mpi_comm_rank, mpi_comm_size, add_group, connect_to_client, connect_to_server, current, get_name, get_subcommunicator, i_to_string, next_, publish, set_current, set_server_size, split, start
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls run_ensemble