initialize_global_time_profiler – MAPL
initialize_global_time_profiler Subroutine
21 statements
Source File
public subroutine initialize_global_time_profiler(unusable, name, comm)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: name
integer, intent(in), optional :: comm
Calls
Called by
Contents
Source Code
initialize_global_time_profiler
Source Code
   subroutine initialize_global_time_profiler(unusable, name, comm)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(*), optional, intent(in) :: name
      integer, optional, intent(in) :: comm
      type(TimeProfiler), pointer :: time_profiler
      character(:), allocatable :: name_
      integer :: world_comm
      if (present(name)) then
         name_ = name
      else
         name_ = 'All'
      end if
      if (present(comm)) then
         world_comm = comm
      else
         world_comm = MPI_COMM_WORLD
      end if
      time_profiler => get_global_time_profiler()
      time_profiler = TimeProfiler(name_, comm_world = world_comm)
      _UNUSED_DUMMY(unusable)
   end subroutine initialize_global_time_profiler
Call graph
initialize_global_time_profiler calls get_global_time_profiler
initialize calls initialize_global_time_profiler
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
mapl_genericstateset calls initialize
mapl_internalstatecreate calls initialize
run calls initialize, run
time_ave calls initialize
ut_regridding calls initialize
mapl_set calls mapl_genericstateset
addchild_preamble calls mapl_internalstatecreate
mapl_capgridcompcreate calls mapl_internalstatecreate
mapl_genericstatesetfromgc calls mapl_genericstateset
mapl_internalstateretrieve calls mapl_internalstatecreate
run_component_driver calls mapl_internalstatecreate
extdata_driver calls run
regrid_util calls main