initialize – MAPL
initialize Subroutine
79 statements
Source File
private subroutine initialize(this, items, bundle, timeInfo, unusable, vdata, recycle_track, rc)
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
type(GriddedIOitemVector), intent(inout), target :: items
type(ESMF_FieldBundle), intent(inout) :: bundle
type(timeData), intent(inout) :: timeInfo
class(KeywordEnforcer), intent(in), optional :: unusable
type(verticalData), intent(inout), optional :: vdata
logical, intent(inout), optional :: recycle_track
integer, intent(out), optional :: rc
Calls
Contents
Source Code
initialize
Source Code
      subroutine initialize(this,items,bundle,timeInfo,unusable,vdata,recycle_track,rc)
         class(HistoryTrajectory), intent(inout) :: this
         type(GriddedIOitemVector), target, intent(inout) :: items
         type(ESMF_FieldBundle), intent(inout) :: bundle
         type(TimeData), intent(inout) :: timeInfo
         class (KeywordEnforcer), optional, intent(in) :: unusable
         type(VerticalData), optional, intent(inout) :: vdata
         logical, optional, intent(inout) :: recycle_track
         integer, optional, intent(out) :: rc
         integer :: status,nobs
         type(ESMF_Grid) :: grid
         type(ESMF_Clock) :: clock
         type(variable) :: v
         type(GriddedIOitemVectorIterator) :: iter
         type(GriddedIOitem), pointer :: item
         _UNUSED_DUMMY(unusable)
         this%bundle=bundle
         this%items=items
         if (present(vdata)) then
            this%vdata=vdata
         else
            this%vdata=VerticalData(_RC)
         end if
         call this%vdata%append_vertical_metadata(this%metadata,this%bundle,_RC)
         this%do_vertical_regrid = (this%vdata%regrid_type /= VERTICAL_METHOD_NONE)
         if (this%vdata%regrid_type == VERTICAL_METHOD_ETA2LEV) call this%vdata%get_interpolating_variable(this%bundle,_RC)
         call timeInfo%add_time_to_metadata(this%metadata,_RC)
         this%time_info = timeInfo
         nobs = size(this%times)
         v = variable(type=PFIO_REAL64,dimensions="time")
         call v%add_attribute('units','degrees_east')
         call v%add_attribute('long_name','longitude')
         call this%metadata%add_variable(trim('longitude'),v)
         v = variable(type=PFIO_REAL64,dimensions="time")
         call v%add_attribute('units','degrees_east')
         call v%add_attribute('long_name','latitude')
         call this%metadata%add_variable(trim('latitude'),v)
         iter = this%items%begin()
         do while (iter /= this%items%end())
            item => iter%get()
            if (item%itemType == ItemTypeScalar) then
               call this%create_variable(item%xname,_RC)
            else if (item%itemType == ItemTypeVector) then
               call this%create_variable(item%xname,_RC)
               call this%create_variable(item%yname,_RC)
            end if
            call iter%next()
         enddo
         call ESMF_FieldBundleGet(this%bundle,grid=grid,_RC)
         !this%dist_locstream = this%locstream_factory%create_locstream(grid=grid,_RC)
         this%number_written = 0
         this%previous_index = lbound(this%times,1)-1
         call timeInfo%get(clock=clock,_RC)
         call ESMF_ClockGet(clock,currTime=this%previous_time,_RC)
         this%regridder = LocStreamRegridder(grid,this%root_locstream,_RC)
         call this%create_output_bundle(_RC)
         this%file_name = ''
         this%recycle_track=.false.
         if (present(recycle_track)) then
            this%recycle_track=recycle_track
         end if
         if (this%recycle_track) then
            call this%reset_times_to_current_day(_RC)
         end if
         _RETURN(_SUCCESS)
      end subroutine initialize
Call graph
initialize calls mapl_verify, esmf_clockget, esmf_fieldbundleget, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize