Initialize – MAPL
Initialize Subroutine
212 statements
Source File
private subroutine Initialize(CC, SRC, DST, CLOCK, RC)
Initialize method for generic couplers.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CplComp) :: CC
type(ESMF_State) :: SRC
type(ESMF_State) :: DST
type(ESMF_Clock) :: CLOCK
integer, intent(out) :: RC
Calls
Contents
Source Code
Initialize
Source Code
  subroutine Initialize(CC, SRC, DST, CLOCK, RC)
! !ARGUMENTS:
    type (ESMF_CplComp)      :: CC
    type (ESMF_State)        :: SRC
    type (ESMF_State)        :: DST
    type (ESMF_Clock)        :: CLOCK
    integer, intent(  OUT)   :: RC
!EOPI
! ErrLog Variables
    character(len=ESMF_MAXSTR)    :: IAm
    character(len=ESMF_MAXSTR)    :: COMP_NAME
    integer                       :: STATUS
! Locals
    character (len=ESMF_MAXSTR)           :: NAME
    type (MAPL_GenericCplState), pointer  :: STATE
    type (MAPL_GenericCplWrap )           :: WRAP
    type (ESMF_TimeInterval   )           :: TCPL
    type (ESMF_TimeInterval   )           :: TCLR
    type (ESMF_TimeInterval   )           :: TS
    type (ESMF_TimeInterval   )           :: TOFF ! offset for alarms
    type (ESMF_Time           )           :: TM0
    type (ESMF_Time           )           :: currTime ! current time of the clock
    type (ESMF_Time           )           :: rTime
    type (ESMF_Calendar       )           :: cal
    integer                               :: J, L1, LN
    integer                               :: NCPLS
    integer                               :: DIMS
    real, pointer                         :: PTR1 (:    )
    real, pointer                         :: PTR2 (:,:  )
    real, pointer                         :: PTR3 (:,:,:)
    real, pointer                         :: PTR4 (:,:,:,:)
    real, pointer                         :: PTR10(:    )
    real, pointer                         :: PTR20(:,:  )
    real, pointer                         :: PTR30(:,:,:)
    real, pointer                         :: PTR40(:,:,:,:)
    integer                               :: OFFSET
    integer, pointer                      :: ungrd(:)
    logical                               :: has_ungrd
    type(ESMF_Field)                      :: field
    integer                               :: cplfunc
    logical                               :: isPresent
    integer                               :: globalOffset
    integer                               :: specOffset
    logical                               :: clockYetToAdvance
    integer                               :: timeStep ! in seconds
! Begin...
    _UNUSED_DUMMY(SRC)
    _UNUSED_DUMMY(DST)
    _UNUSED_DUMMY(CLOCK)
! Get the target components name and set-up traceback handle.
! -----------------------------------------------------------
    Iam = "MAPL_GenericCplCompInitialize"
    call ESMF_CplCompGet( CC, NAME=COMP_NAME, RC=STATUS )
    _VERIFY(STATUS)
    Iam = trim(COMP_NAME) // Iam
! Retrieve the pointer to the internal state. It comes in a wrapper.
! ------------------------------------------------------------------
    call ESMF_CplCompGetInternalState ( CC, WRAP, STATUS )
    _VERIFY(STATUS)
    STATE  =>  WRAP%INTERNAL_STATE
! The number of couplings for this pair
!--------------------------------------
    NCPLS = size(STATE%DST_SPEC)
    _ASSERT(NCPLS == size(STATE%SRC_SPEC),'needs informative message')
! Allocate arrays of ESMF arrays for accumulators
!-------------------------------------------------
    allocate(STATE%ACCUMULATORS(NCPLS), STAT=STATUS)
    _VERIFY(STATUS)
    allocate(STATE%ARRAY_COUNT (NCPLS), STAT=STATUS)
    _VERIFY(STATUS)
    allocate(STATE%ACCUM_RANK (NCPLS), STAT=STATUS)
    _VERIFY(STATUS)
    allocate(STATE%couplerType(NCPLS), STAT=STATUS)
    _VERIFY(STATUS)
! Allocate internal state objects
! -------------------------------
    allocate (STATE%CLEAR_INTERVAL (NCPLS), stat=status)
    _VERIFY(STATUS)
    allocate (STATE%COUPLE_INTERVAL(NCPLS), stat=status)
    _VERIFY(STATUS)
    allocate (STATE%TIME_TO_CLEAR  (NCPLS), stat=status)
    _VERIFY(STATUS)
    allocate (STATE%TIME_TO_COUPLE (NCPLS), stat=status)
    _VERIFY(STATUS)
    allocate(STATE%ACCUM_COUNT     (NCPLS), stat=status)
    _VERIFY(STATUS)
! Get clock info
!---------------
    call ESMF_ClockGet(CLOCK, calendar=cal, currTime=currTime, timeStep=TS, rc=STATUS)
    _VERIFY(STATUS)
    TM0 = currTime
    call ESMF_AttributeGet(CC, name='ClockYetToAdvance', &
         isPresent=isPresent, _RC)
    if (isPresent) then
       call ESMF_AttributeGet(CC, name='ClockYetToAdvance', &
            value=clockYetToAdvance, _RC)
    else
       clockYetToAdvance = .false.
    endif
    globalOffset = 0
    if (clockYetToAdvance) then
       call ESMF_TimeIntervalGet(TS, S=timeStep, _RC)
       globalOffset = -timeStep
    end if
! Initialize the counters to 0. This may do some unnecessary
!   accumulations immediately after initialize
!-----------------------------------------------------------
    STATE%ACCUM_COUNT = 0
    DO J = 1, NCPLS
! Get info from the DST spec
!---------------------------
       call MAPL_VarSpecGet(STATE%DST_SPEC(J),        &
            ACCMLT_INTERVAL = STATE%CLEAR_INTERVAL(J), &
            COUPLE_INTERVAL = STATE%COUPLE_INTERVAL(J), &
            OFFSET          = specOffset, &
            SHORT_NAME      = NAME, &
                                            RC = STATUS )
       _VERIFY(STATUS)
! Initalize COUPLE ALARM from destination properties
!---------------------------------------------------
       OFFSET = specOffset + globalOffset
       call ESMF_TimeIntervalSet(TCPL, S=STATE%COUPLE_INTERVAL(J), &
            calendar=cal, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_TimeIntervalSet(TOFF, S=OFFSET, &
            calendar=cal, RC=STATUS)
       _VERIFY(STATUS)
       rTime = TM0 + TOFF
       do while (rTime < currTime)
          rTime = rTime + TCPL
       end do
       if (associated(STATE%TIME2CPL_ALARM)) then
          STATE%TIME_TO_COUPLE(J) = STATE%TIME2CPL_ALARM
          STATE%TIME_TO_CLEAR(J) = STATE%TIME2CPL_ALARM
       else
          STATE%TIME_TO_COUPLE(J) = ESMF_AlarmCreate(NAME='TIME2COUPLE_' // trim(COMP_NAME) &
               // '_' // trim(NAME),   &
               clock        = CLOCK,   &
               ringInterval = TCPL,    &
               ringTime     = rTime,   &
               sticky       = .false., &
               rc=STATUS   )
          _VERIFY(STATUS)
          if(rTime == currTime) then
             call ESMF_AlarmRingerOn(STATE%TIME_TO_COUPLE(J), rc=status); _VERIFY(STATUS)
          end if
! initalize CLEAR ALARM from destination properties
!--------------------------------------------------
          call ESMF_TimeIntervalSet(TCLR, S=STATE%CLEAR_INTERVAL(J), &
               calendar=cal, RC=STATUS)
          _VERIFY(STATUS)
          if (TCLR < TS) TCLR = TS
          !rTime = TM0 + TOFF - TCLR
          rTime = TM0 + TOFF
          !do while (rTime < currTime)
             !rTime = rTime + TCPL
          !end do
          STATE%TIME_TO_CLEAR(J) = ESMF_AlarmCreate(NAME='TIME2CLEAR_' // trim(COMP_NAME) &
               // '_' // trim(NAME),   &
               clock        = CLOCK,   &
               ringInterval = TCLR,    &
               ringTime     = rTime,   &
               sticky       = .false., &
               rc=STATUS   )
          _VERIFY(STATUS)
          if(rTime == currTime) then
             call ESMF_AlarmRingerOn(STATE%TIME_TO_CLEAR(J), rc=status); _VERIFY(STATUS)
          end if
       end if
! Get info from the SRC spec
!---------------------------
       call MAPL_VarSpecGet(STATE%SRC_SPEC(J),      &
                            DIMS       = DIMS,      &
                            SHORT_NAME = NAME,      &
                            UNGRIDDED_DIMS=UNGRD,   &
                                           RC=STATUS)
       _VERIFY(STATUS)
! We currently make these d1mension assumptions
!----------------------------------------------
       if(DIMS==MAPL_DIMSHORZVERT) then
          DIMS=3
       elseif(DIMS==MAPL_DIMSHORZONLY .or. DIMS==MAPL_DIMSTILETILE) then
          DIMS=2
       elseif(DIMS==MAPL_DIMSVERTONLY .or. DIMS==MAPL_DIMSTILEONLY) then
          DIMS=1
       else
          _RETURN(ESMF_FAILURE)
       end if
       has_ungrd = associated(UNGRD)
       if (has_ungrd) then
          DIMS = DIMS + size(UNGRD)
       end if
       _ASSERT(DIMS < 5,'needs informative message') ! ALT: due to laziness we are supporting only 4 dims
       STATE%ACCUM_RANK(J) = DIMS
       call ESMF_StateGet(src, NAME, field, rc=status)
       _VERIFY(STATUS)
       call ESMF_AttributeGet(field, NAME="CPLFUNC", isPresent=isPresent, RC=STATUS)
       _VERIFY(STATUS)
       if (isPresent) then
          call ESMF_AttributeGet(field, NAME="CPLFUNC", VALUE=cplfunc, RC=STATUS)
          _VERIFY(STATUS)
       else
          cplfunc = MAPL_CplAverage
       end if
       state%couplerType(J) = cplfunc
! Create Accumulators for 3 dimensions
!-------------------------------------
       select case(DIMS)
       case(4)
! Get SRC pointer, making sure it is allocated.
          call MAPL_GetPointer(SRC, PTR4, NAME, ALLOC=.TRUE., RC=STATUS)
          _VERIFY(STATUS)
! Allocate space for accumulator
          L1 = LBOUND(PTR4,3)
          LN = UBOUND(PTR4,3)
          allocate(PTR40(size(PTR4,1),size(PTR4,2),L1:LN,size(PTR4,4)), STAT=STATUS)
          _VERIFY(STATUS)
          if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
             PTR40 = MAPL_UNDEF
          else
! Set accumulator values to zero
             PTR40 = 0.0
          endif
! Put pointer in accumulator
          STATE%ACCUMULATORS(J)=ESMF_LocalArrayCreate( PTR40, RC=STATUS)
          _VERIFY(STATUS)
       case(3)
! Get SRC pointer, making sure it is allocated.
          call MAPL_GetPointer(SRC, PTR3, NAME, ALLOC=.TRUE., RC=STATUS)
          _VERIFY(STATUS)
! Allocate space for accumulator
          L1 = LBOUND(PTR3,3)
          LN = UBOUND(PTR3,3)
          allocate(PTR30(size(PTR3,1),size(PTR3,2),L1:LN), STAT=STATUS)
          _VERIFY(STATUS)
          if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
             PTR30 = MAPL_UNDEF
          else
! Set accumulator values to zero
             PTR30 = 0.0
          endif
! Put pointer in accumulator
          STATE%ACCUMULATORS(J)=ESMF_LocalArrayCreate( PTR30, RC=STATUS)
          _VERIFY(STATUS)
       case(2)
          call MAPL_GetPointer(SRC, PTR2, NAME, ALLOC=.TRUE., RC=STATUS)
          _VERIFY(STATUS)
          allocate(PTR20(size(PTR2,1),size(PTR2,2)), STAT=STATUS)
          _VERIFY(STATUS)
          if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
             PTR20 = MAPL_UNDEF
          else
             PTR20 = 0.0
          end if
          STATE%ACCUMULATORS(J)=ESMF_LocalArrayCreate( PTR20, RC=STATUS)
          _VERIFY(STATUS)
       case(1)
          call MAPL_GetPointer(SRC, PTR1, NAME, ALLOC=.TRUE., RC=STATUS)
          _VERIFY(STATUS)
          allocate(PTR10(size(PTR1)), STAT=STATUS)
          _VERIFY(STATUS)
          if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
             PTR10 = MAPL_UNDEF
          else
             PTR10 = 0.0
          end if
          STATE%ACCUMULATORS(J)=ESMF_LocalArrayCreate( PTR10, RC=STATUS)
          _VERIFY(STATUS)
       case default
          _RETURN(ESMF_FAILURE)
       end select
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine Initialize
Call graph
initialize calls ESMF_AlarmCreate, ESMF_AlarmRingerOn, ESMF_AttributeGet, ESMF_ClockGet, ESMF_CplCompGet, ESMF_CplCompGetInternalState, ESMF_TimeIntervalGet, ESMF_TimeIntervalSet, accum_count, accum_rank, accumulators, array_count, clear_interval, couple_interval, couplertype, dst_spec, esmf_localarraycreate, esmf_stateget, esmfl_stategetpointertodata, mapl_assert, mapl_varspecget, mapl_return, mapl_verify, src_spec, time_to_clear, time_to_couple