initialize_cf_time – MAPL
initialize_cf_time Subroutine
13 statements
Source File
private subroutine initialize_cf_time(cft, units)
Arguments
Type Intent Optional Attributes Name
class(CF_Time), intent(inout) :: cft
character(len=*), intent(in) :: units
Calls
Called by
Source Code
   subroutine initialize_cf_time(cft, units)
      class(CF_Time), intent(inout) :: cft
      character(len=*), intent(in) :: units
      character(len=MAX_CHARACTER_LENGTH) :: token, remainder
      cft % is_valid = .FALSE.
      remainder = units
      if(len_trim(remainder) == 0) return
      call split(trim(remainder), token, remainder, CF_DELIM)
      cft % time_unit = token
      call split(trim(remainder), token, remainder, CF_DELIM)
      cft % base_datetime = remainder
      cft % is_valid = .TRUE.
   end subroutine initialize_cf_time
Call graph
initialize_cf_time calls split
split calls split_characters
construct_cf_time_integer calls initialize_cf_time
construct_cf_time_real calls initialize_cf_time
cf_time_integer calls construct_cf_time_integer
cf_time_real calls construct_cf_time_real