inject_external_grid – MAPL
inject_external_grid Subroutine
34 statements
Source File
private subroutine inject_external_grid(this, unusable, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
inject_external_grid
Source Code
  subroutine inject_external_grid(this, unusable, rc)
     class(MAPL_CapGridComp),          intent(inout) :: this
     class(KeywordEnforcer), optional, intent(in   ) :: unusable
     integer,                optional, intent(  out) :: rc
     type(ESMF_GridMatch_Flag) :: grid_match
     type(ESMF_Grid)           :: cap_grid,            root_grid
     logical                   :: cap_grid_is_present, root_grid_is_present
     integer                   :: status
     _UNUSED_DUMMY(unusable)
     call ESMF_GridCompGet(this%gc, gridIsPresent=cap_grid_is_present, _RC)
     if (cap_grid_is_present) then
        call ESMF_GridCompGet(this%gc, grid=cap_grid, _RC)
        call ESMF_GridValidate(cap_grid, _RC)
        call ESMF_GridCompGet(this%gcs(this%root_id), gridIsPresent=root_grid_is_present, _RC)
        if (root_grid_is_present) then
           call ESMF_GridCompGet(this%gcs(this%root_id), grid=root_grid, _RC)
           call ESMF_GridValidate(root_grid, _RC)
           grid_match = ESMF_GridMatch(cap_grid, root_grid, _RC)
           _ASSERT(grid_match == ESMF_GRIDMATCH_EXACT, "Attempting to override root grid with non-matching external grid")
        else
            call ESMF_GridCompSet(this%gcs(this%root_id), grid=cap_grid, _RC)
        end if
     end if
     _RETURN(_SUCCESS)
  end subroutine inject_external_grid
Call graph
inject_external_grid calls ESMF_GridCompGet, ESMF_GridCompSet, ESMF_GridMatch, ESMF_GridValidate, gcs, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_gc calls inject_external_grid