iNodeDestroy – MAPL
iNodeDestroy Subroutine
18 statements
Source File
public subroutine iNodeDestroy(List)
Arguments
Type Intent Optional Attributes Name
type(iNode), pointer :: List
Called by
Contents
Source Code
iNodeDestroy
Source Code
   subroutine iNodeDestroy(List)
     type(iNode), pointer :: List, p, q
     if (.not. associated(List)) return
     q => List
     p => List%next
     do while ( associated(p) )
        if (associated(q)) then
           if (associated(q%intData)) deallocate(q%intData)
           deallocate(q)
        end if
        q => p
        p => p%next
     end do
     if (associated(q)) then
        if (associated(q%intData)) deallocate(q%intData)
        deallocate(q)
     end if
   end subroutine iNodeDestroy
Call graph
esmf_cfiovarinfodestroy calls inodedestroy
esmf_cfiodestroy calls esmf_cfiovarinfodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy
unfind calls esmf_cfiodestroy
find calls esmf_cfiodestroy
finalize calls mapl_cfiodestroy
esmf_iodestroy calls mapl_cfiodestroy
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle