inq_var_string_length – MAPL
inq_var_string_length Subroutine
14 statements
Source File
private subroutine inq_var_string_length(this, var_name, length, unusable, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
character(len=*), intent(in) :: var_name
integer, intent(out) :: length
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine inq_var_string_length(this, var_name, length, unusable, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      character(*),                  intent(in)    :: var_name
      integer,                       intent(out)   :: length
      class (KeywordEnforcer), optional, intent(in):: unusable
      integer, optional, intent(out) :: rc
      integer :: varid, status
      status = nf90_inq_varid(this%ncid, name=var_name, varid=varid)
      _VERIFY(status)
      status = pfio_nf90_get_var_string_len(this%ncid, varid, length)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine inq_var_string_length
Call graph
inq_var_string_length calls nf90_inq_varid, mapl_return, mapl_verify, pfio_nf90_get_var_string_len
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
pfio_nf90_get_var_string_len calls c_f_pfio_get_var_string_len, nf90_inquire_dimension, nf90_inquire_variable
get_error_message calls at, insert
mapl_throw_exception calls initialize
main calls inq_var_string_length