INQFILEMEM – MAPL
INQFILEMEM Function
15 statements
Source File
private function INQFILEMEM(Name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: Name
Return Value logical
Called by
Source Code
  LOGICAL FUNCTION INQFILEMEM(name)
    IMPLICIT NONE
    character(LEN=*), intent(in   )           :: Name
    integer :: i
    logical :: found
    found = .false.
    do i = 3, last_unit
       if(name==Mname(i)) then
          found = .true.
          exit
       end if
    end do
    InqFileMem = found
    return
  end FUNCTION INQFILEMEM
Call graph
mapl_memfileinquire calls inqfilemem
mapl_esmfstatereadfromfile calls mapl_memfileinquire
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore