insert_RequestHandle – MAPL
insert_RequestHandle Subroutine
9 statements
Source File
private subroutine insert_RequestHandle(this, request_id, handle, rc)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(inout), target :: this
integer, intent(in) :: request_id
class(AbstractRequestHandle), intent(in) :: handle
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine insert_RequestHandle(this,request_id, handle, rc)
      class (BaseThread), target, intent(inout) :: this
      integer, intent(in) :: request_id
      class(AbstractRequestHandle), intent(in):: handle
      integer, optional, intent(out) :: rc
      call this%open_requests%insert(request_id, handle)
      _RETURN(_SUCCESS)
   end subroutine insert_RequestHandle
Call graph
insert_requesthandle calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_insert_pair calls s_insert
mapl_throw_exception calls initialize
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
collective_prefetch_data calls insert_requesthandle, collective_prefetch_data
collective_stage_data calls insert_requesthandle, collective_stage_data
get_datafrommem calls insert_requesthandle, get_datafrommem
handle_collectivestagedata calls insert_requesthandle
handle_done_prefetch calls insert_requesthandle
handle_stagedata calls insert_requesthandle
prefetch_data calls insert_requesthandle, prefetch_data
stage_data calls insert_requesthandle, stage_data
stage_nondistributed_data calls insert_requesthandle, collective_stage_data
run calls collective_prefetch_data, collective_stage_data, stage_nondistributed_data, prefetch_data
test_prefetch_data calls prefetch_data
test_wait calls prefetch_data