interpolate_to_time – MAPL
interpolate_to_time Subroutine
62 statements
Source File
private subroutine interpolate_to_time(this, field, time, rc)
Type Bound
ExtDataBracket
Arguments
Type Intent Optional Attributes Name
class(ExtDataBracket), intent(inout) :: this
type(ESMF_Field), intent(inout) :: field
type(ESMF_Time), intent(in) :: time
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine interpolate_to_time(this,field,time,rc)
      class(ExtDataBracket), intent(inout) :: this
      type(ESMF_Field), intent(inout) :: field
      type(ESMF_Time), intent(in) :: time
      integer, optional, intent(out) :: rc
      type(ESMF_TimeInterval)    :: tinv1, tinv2
      real                       :: alpha
      real, pointer              :: var1d(:)     => null()
      real, pointer              :: var1d_left(:)   => null()
      real, pointer              :: var1d_right(:)   => null()
      integer :: status
      logical :: right_node_set, left_node_set
      character(len=ESMF_MAXPATHLEN) :: left_file, right_file
      right_node_set = this%right_node%check_if_initialized(_RC)
      left_node_set = this%left_node%check_if_initialized(_RC)
      call this%right_node%get(file=right_file)
      call this%left_node%get(file=left_file)
      right_node_set = right_file /= file_not_found
      left_node_set = left_file /= file_not_found
      alpha = 0.0
      if ( (.not.this%disable_interpolation) .and. (.not.this%intermittent_disable) .and. right_node_set .and. left_node_set) then
         tinv1 = time - this%left_node%time
         tinv2 = this%right_node%time - this%left_node%time
         alpha = tinv1/tinv2
      end if
      call assign_fptr(field,var1d,_RC)
      if (right_node_set) then
         call assign_fptr(this%right_node%field,var1d_right,_RC)
      end if
      if (left_node_set) then
         call assign_fptr(this%left_node%field,var1d_left,_RC)
      end if
      if ( left_node_set .and. (time == this%left_node%time .or. this%disable_interpolation)) then
         var1d = var1d_left
      else if (right_node_set .and. (time == this%right_node%time)) then
         var1d = var1d_right
      else if ( (left_node_set .and. right_node_set) .and. (.not.this%exact) ) then
         where( (var1d_left /= mapl_undef) .and. (var1d_right /= mapl_undef))
            var1d = var1d_left + alpha*(var1d_right-var1d_left)
         elsewhere
            var1d = mapl_undef
         endwhere
      else
         var1d = mapl_undef
      end if
      if (this%scale_factor == 0.0 .and. this%offset /= 0.0) then
         where(var1d /= MAPL_UNDEF) var1d=var1d+this%offset
      end if
      if (this%scale_factor /= 0.0 .and. this%offset == 0.0) then
         where(var1d /= MAPL_UNDEF) var1d=var1d*this%scale_factor
      end if
      if (this%scale_factor /= 0.0 .and. this%offset /= 0.0) then
         where(var1d /= MAPL_UNDEF) var1d=var1d*this%scale_factor+this%offset
      end if
      _RETURN(_SUCCESS)
   end subroutine interpolate_to_time
Call graph
interpolate_to_time calls assign_fptr, check_if_initialized, get, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
check_if_initialized calls mapl_return, mapl_verify, ESMF_FieldIsCreated
get calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
mapl_extdatainterpfield calls interpolate_to_time
run_ calls mapl_extdatainterpfield