interpVal – MAPL
interpVal Function
10 statements
Source File
private function interpVal(var1, var2, ple, plev1, plev2, KAP) result(val)
Main vertical interpolation formula:
In this particular case, we have:
Arguments
Type Intent Optional Attributes Name
real :: var1
variable (pressure level) value at level k
real :: var2
variable (pressure level) value at level k-1
real :: ple
model pressure at current level
real :: plev1
pressure value at level k
real :: plev2
pressure value at level k-1
real :: KAP
coefficient KAPPA
Return Value real
Returned value
Called by
Contents
Source Code
interpVal
Source Code
      FUNCTION interpVal (var1, var2, ple, plev1, plev2, KAP) result(val)
!
      real :: var1      !! variable (pressure level) value at level k
      real :: var2      !! variable (pressure level) value at level k-1
      real :: ple       !! model pressure at current level
      real :: plev1     !! pressure value at level k
      real :: plev2     !! pressure value at level k-1
      real :: KAP       !! coefficient KAPPA
      real :: val       !! Returned value
!
!------------------------------------------------------------------------------
      val = ( var1*(ple**KAP - plev2**KAP) - &
              var2*(ple**KAP - plev1**KAP) ) / (plev1**KAP - plev2**KAP)
      END FUNCTION interpVal
Call graph
vertinterpolation_presskappa calls interpval
mapl_extdataverticalinterpolate calls vertinterpolation_presskappa
run_ calls mapl_extdataverticalinterpolate