interp_accumulate_fields – MAPL
interp_accumulate_fields Subroutine
188 statements
Source File
private subroutine interp_accumulate_fields(this, xy_subset, rc)
write(6,) ‘MAPL_GridGetInterior, ii1,iin,jj1,jjn’, ii1,iin,jj1,jjn print, ‘js,je ‘, js, je
write(6,) ‘ck bundlepost_acc’ write(6,) ‘j1(localDe)’, j1(0:localDeCount-1) write(6,*) ‘j2(localDe)’, j2(0:localDeCount-1)
              write(6,*) 'j, jj', j, jj
              write(6,*) 'j, jj', j, jj
Type Bound
sampler
Arguments
Type Intent Optional Attributes Name
class(sampler) :: this
integer, intent(in) :: xy_subset(2,2)
integer, intent(in) :: xy_mask(:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine interp_accumulate_fields (this,xy_subset,rc)
    implicit none
    class (sampler) :: this
    integer, intent(in) :: xy_subset(2,2)
    !!integer, intent(in) :: xy_mask(:,:)
    integer, optional, intent(out) :: rc
    integer :: status
    type(ESMF_Field) :: outField, outField2
    type(ESMF_Field) :: new_outField
    type(ESMF_Grid)  :: grid
    type(GriddedIOitemVectorIterator) :: iter
    type(GriddedIOitem), pointer :: item
    type(ESMF_Array) :: array1, array2
    integer :: is,ie,js,je
    integer :: rank
    real(KIND=ESMF_KIND_R4), pointer :: pt2d(:,:), pt2d_(:,:)
    real(KIND=ESMF_KIND_R4), pointer :: pt3d(:,:,:), pt3d_(:,:,:)
    integer :: localDe, localDECount
    integer, dimension(:), allocatable :: LB, UB, exclusiveCount
    integer, dimension(:), allocatable :: compLB, compUB, compCount
    integer :: dimCount
    integer :: y1, y2
    integer :: j, jj
    integer :: ii1, iin, jj1, jjn
    integer, dimension(:), allocatable :: j1, j2
    is=xy_subset(1,1); ie=xy_subset(2,1)
    js=xy_subset(1,2); je=xy_subset(2,2)
    if (js > je) then
       ! no valid points are found on swath grid for this time step
       _RETURN(ESMF_SUCCESS)
    end if
    if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
       call this%vdata%setup_eta_to_pressure(regrid_handle=this%regrid_handle,output_grid=this%output_grid,rc=status)
       _VERIFY(status)
    end if
    call ESMF_FieldBundleGet(this%output_bundle, grid=grid, _RC)
    call ESMF_GridGet(grid, localDECount=localDECount, dimCount=dimCount, _RC)
    allocate ( LB(dimCount), UB(dimCount), exclusiveCount(dimCount) ,_STAT)
    allocate ( compLB(dimCount), compUB(dimCount), compCount(dimCount) ,_STAT)
    allocate ( j1(0:localDEcount-1) ,_STAT)  ! start
    allocate ( j2(0:localDEcount-1) ,_STAT)  ! end
    _ASSERT ( localDEcount == 1, 'failed, due to localDEcount > 1')
    call MAPL_GridGetInterior(grid,ii1,iin,jj1,jjn)
!!    write(6,*) 'MAPL_GridGetInterior, ii1,iin,jj1,jjn', ii1,iin,jj1,jjn
!!    print*, 'js,je ', js, je
    LB(1)=ii1; LB(2)=jj1
    UB(1)=iin; UB(2)=jjn
    do localDe=0, localDEcount-1
       !
       ! is/ie, js/je,  [LB, UB]
       !
       !
       y1=jj1; y2=jjn
       if (y1 < js) then
          if (y2 < js) then
             j1(localDe)=-1
             j2(localDe)=-1
          elseif (y2 < je) then
             j1(localDe)=js
             j2(localDe)=y2
          else
             j1(localDe)=js
             j2(localDe)=je
          endif
       elseif (y1 <= je) then
          j1(localDe)=y1
          if (y2 < je) then
             j2(localDe)=y2
          else
             j2(localDe)=je
          endif
       else
          j1(localDe)=-1
          j2(localDe)=-1
       endif
    enddo
!!    write(6,*) 'ck bundlepost_acc'
!!    write(6,*) 'j1(localDe)', j1(0:localDeCount-1)
!!    write(6,*) 'j2(localDe)', j2(0:localDeCount-1)
    iter = this%items%begin()
    do while (iter /= this%items%end())
       item => iter%get()
       if (item%itemType == ItemTypeScalar) then
          call this%RegridScalar(item%xname,_RC)
          call ESMF_FieldBundleGet(this%output_bundle,item%xname,field=outField, _RC)
          if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
             call this%vdata%correct_topo(outField,_RC)
          end if
       elseif (item%itemType == ItemTypeVector) then
          call this%RegridVector(item%xname,item%yname,_RC)
          call ESMF_FieldBundleGet(this%output_bundle,item%xname,field=outField, _RC)
          if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
             call this%vdata%correct_topo(outField,_RC)
          end if
          call ESMF_FieldBundleGet(this%output_bundle,item%yname,field=outField2, _RC)
          if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
             call this%vdata%correct_topo(outField2,_RC)
          end if
       end if
       ! -- mask the time interval
       !    store the time interval fields into new bundle
       !    xname
       call ESMF_FieldGet(outField, Array=array1, _RC)
       call ESMF_FieldBundleGet(this%acc_bundle,item%xname,field=new_outField,_RC)
       call ESMF_FieldGet(new_outField, Array=array2, _RC)
       call ESMF_ArrayGet(array1, rank=rank, _RC)
       if (rank==2) then
          call ESMF_ArrayGet(array1, farrayptr=pt2d, _RC)
          call ESMF_ArrayGet(array2, farrayptr=pt2d_, _RC)
          localDe=0
          if (j1(localDe)>0) then
             do j= j1(localDe), j2(localDe)
                jj= j-jj1+1     ! j_local
                !!                      write(6,*) 'j, jj', j, jj
                pt2d_(:,jj) = pt2d(:,jj)
             enddo
          endif
       elseif (rank==3) then
          call ESMF_ArrayGet(array1, farrayptr=pt3d, _RC)
          call ESMF_ArrayGet(array2, farrayptr=pt3d_, _RC)
          do localDe=0, localDEcount-1
             if (j1(localDe)>0) then
                do j= j1(localDe), j2(localDe)
                   jj= j-jj1+1
                   pt3d_(:,jj,:) = pt3d(:,jj,:)
                enddo
             endif
          enddo
       else
          _FAIL('failed interp_accumulate_fields')
       endif
       ! __ additional step for yname if vector
       if (item%itemType == ItemTypeScalar) then
          ! already done
       elseif (item%itemType == ItemTypeVector) then
          !
          ! add yname
          !
          call ESMF_FieldGet(outField2, Array=array1, _RC)
          call ESMF_FieldBundleGet(this%acc_bundle,item%yname,field=new_outField,_RC)
          call ESMF_FieldGet(new_outField, Array=array2, _RC)
          call ESMF_ArrayGet(array1, rank=rank, _RC)
          if (rank==2) then
             call ESMF_ArrayGet(array1, farrayptr=pt2d, _RC)
             call ESMF_ArrayGet(array2, farrayptr=pt2d_, _RC)
             localDe=0
                if (j1(localDe)>0) then
                   do j= j1(localDe), j2(localDe)
                      jj= j-jj1+1     ! j_local
!!                      write(6,*) 'j, jj', j, jj
                      pt2d_(:,jj) = pt2d(:,jj)
                   enddo
                endif
          elseif (rank==3) then
             call ESMF_ArrayGet(array1, farrayptr=pt3d, _RC)
             call ESMF_ArrayGet(array2, farrayptr=pt3d_, _RC)
             do localDe=0, localDEcount-1
                if (j1(localDe)>0) then
                   do j= j1(localDe), j2(localDe)
                      jj= j-jj1+1
                      pt3d_(:,jj,:) = pt3d(:,jj,:)
                   enddo
                endif
             enddo
          else
             _FAIL('failed interp_accumulate_fields')
          endif
       end if
       call iter%next()
    enddo
    _RETURN(ESMF_SUCCESS)
  end subroutine interp_accumulate_fields
Call graph
interp_accumulate_fields calls ESMF_GridGet, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_assert, mapl_gridgetinterior, correct_topo, mapl_return, mapl_verify, regridscalar, regridvector, setup_eta_to_pressure, v_begin, v_iter_get, v_iter_next
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridgetinterior calls mapl_gridgetinterior
correct_topo calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
regridscalar calls esmf_fieldbundleget, esmf_fieldget, mapl_assert, mapl_return, mapl_verify, esmfl_fieldgetpointertodata, regrid, flip_levels, mapl_gridhasde, regrid_eta_to_pressure, regrid_select_level
regridvector calls esmf_fieldbundleget, esmf_fieldget, mapl_return, mapl_verify, esmfl_fieldgetpointertodata, regrid, flip_levels, mapl_gridhasde, regrid_eta_to_pressure, regrid_select_level
setup_eta_to_pressure calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, regrid, mapl_gridget
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls regrid_accumulate_on_xysubset