intrinsic_to_string – MAPL
intrinsic_to_string Function
24 statements
Source File
private function intrinsic_to_string(val, str_format, rc) result(formatted_str)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: val
character(len=*), intent(in) :: str_format
integer, intent(out), optional :: rc
Return Value character(len=256)
Calls
Called by
Contents
Source Code
intrinsic_to_string
Source Code
   function intrinsic_to_string(val, str_format, rc) result(formatted_str)
      class(*), intent(in) :: val
      character(len=*), intent(in) :: str_format
      character(len=256) :: formatted_str
      integer, optional, intent(out) :: rc
      select type(val)
      type is(integer(int32))
         write(formatted_str, str_format) val
      type is(integer(int64))
         write(formatted_str, str_format) val
      type is(real(real32))
         write(formatted_str, str_format) val
      type is(real(real64))
         write(formatted_str, str_format) val
      type is(logical)
         write(formatted_str, str_format) val
      type is(character(len=*))
         formatted_str = trim(val)
         class default
         _FAIL( "Unsupported type in intrinsic_to_string")
      end select
      _RETURN(_SUCCESS)
   end function intrinsic_to_string
Call graph
intrinsic_to_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
print_resource calls intrinsic_to_string
mapl_getresource_config_scalar calls print_resource
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_scalar