invert_Keplers_Newton – MAPL
invert_Keplers_Newton Subroutine
29 statements
Source File
private subroutine invert_Keplers_Newton(MA, ECC, EA, dE, nits, tol, max_its)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: MA
real, intent(in) :: ECC
real, intent(out) :: EA
real, intent(out) :: dE
integer, intent(out) :: nits
real, intent(in), optional :: tol
integer, intent(in), optional :: max_its
Called by
Contents
Call graph
mapl_sungetdaylightduration calls invert_keplers_newton
mapl_sungetlocalsolarhourangle calls invert_keplers_newton
solar_1d calls invert_keplers_newton, mapl_sungetinsolation
solar_2d calls invert_keplers_newton, mapl_sungetinsolation
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
solar_arr_int calls mapl_sungetinsolation