is_attribute_present – MAPL
is_attribute_present Function
11 statements
Source File
private function is_attribute_present(this, attr_name, rc) result(isPresent)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in), target :: this
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function is_attribute_present(this, attr_name, rc) result(isPresent)
      type (Attribute), pointer :: attr
      class (Variable), target, intent(in) :: this
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      logical :: isPresent
      attr => this%attributes%at(attr_name)
      isPresent = associated(attr)
      _RETURN(_SUCCESS)
   end function is_attribute_present
Call graph
is_attribute_present calls m_at, mapl_return
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
check_flip calls is_attribute_present
coordinate_has_bounds calls is_attribute_present
get_level_name calls is_attribute_present, get_variable_attribute
get_variable_attribute calls is_attribute_present
has_attribute calls is_attribute_present
var_has_attr calls is_attribute_present
var_has_missing_value calls is_attribute_present
compare_grid_file calls has_attribute
create_grid calls get_level_name
get_coordinate_info calls var_has_attr
get_file_levels calls get_level_name, get_coordinate_info
getlevs calls get_level_name, get_variable_attribute, get_coordinate_info
initialize_from_file_metadata calls has_attribute, coordinate_has_bounds
make_factory_from_file calls has_attribute
mapl_bundlereadncpar calls check_flip, compare_grid_file
mapl_create_bundle_from_metdata_id calls get_level_name
swap_undef_value calls var_has_missing_value, var_get_missing_value
var_get_missing_value calls var_has_attr
time_ave calls get_level_name, get_coordinate_info, get_file_levels, var_get_missing_value
mapl_varreadncpar calls mapl_bundlereadncpar
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
get_time_info calls get_coordinate_info
initialize_ calls get_coordinate_info, getlevs
main calls get_file_levels
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
process_command_line calls create_grid
process_data_from_file calls swap_undef_value