is_between – MAPL
is_between Function
6 statements
Source File
public pure function is_between(lower, upper, n)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lower
integer, intent(in) :: upper
integer, intent(in) :: n
Return Value logical
Called by
Contents
Source Code
is_between
Source Code
   pure logical function is_between(lower, upper, n)
      integer, intent(in) :: lower
      integer, intent(in) :: upper
      integer, intent(in) :: n
      is_between = n > lower .and. n < upper
   end function is_between
Call graph
is_valid_year calls is_between
is_valid_month calls is_between
is_valid_minute calls is_between
is_valid_date calls is_between, is_valid_year, is_valid_month
is_valid_hour calls is_between
is_valid_second calls is_between
is_valid_millisecond calls is_between
test_is_between calls is_between
test_is_valid_year calls is_valid_year
test_is_valid_minute calls is_valid_minute
test_is_valid_month calls is_valid_month
parse_date calls is_valid_date
is_valid_time calls is_valid_minute, is_valid_hour, is_valid_second, is_valid_millisecond
test_is_valid_date calls is_valid_date
test_is_valid_hour calls is_valid_hour
test_is_valid_second calls is_valid_second
test_is_valid_millisecond calls is_valid_millisecond
construct_iso8601date calls parse_date
test_is_valid_time calls is_valid_time
parse_time calls is_valid_time
test_parse_date calls parse_date
iso8601date calls construct_iso8601date
construct_iso8601time calls parse_time
test_parse_time calls parse_time