is_digit – MAPL
is_digit Function
4 statements
Source File
public pure elemental function is_digit(c)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: c
Return Value logical
Called by
Contents
Source Code
is_digit
Source Code
   elemental pure logical function is_digit(c)
      character, intent(in) :: c
      is_digit = scan(c, DIGIT_CHARACTERS) > 0
   end function is_digit
Call graph
construct_iso8601duration calls is_digit
test_is_digit calls is_digit
iso8601duration calls construct_iso8601duration
convert_iso8601_to_esmf_timeinterval calls iso8601duration