is_digit – MAPL
is_digit Function
4 statements
Source File
public pure elemental function is_digit(c)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
Return Value logical
Called by
Contents
Source Code
is_digit
Source Code
   elemental pure logical function is_digit(c)
      character, intent(in) :: c
      is_digit = scan(c, DIGIT_CHARACTERS) > 0
   end function is_digit
Call graph
is_valid_datestring calls is_digit
test_is_digit calls is_digit
undelimit_all calls is_digit
convert_to_iso8601datetime calls undelimit_all
test_undelimit_all calls undelimit_all
test_convert_to_iso8601datetime calls convert_to_iso8601datetime