is_empty – MAPL
is_empty Function
20 statements
Source File
private function is_empty(this, rc) result(yes)
Type Bound
UnlimitedEntity
Arguments
Type Intent Optional Attributes Name
class(UnlimitedEntity), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function is_empty(this, rc) result(yes)
      class (UnlimitedEntity), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      logical :: yes
      class (*), pointer :: value
      ! not initialized
      yes = .not. allocated(this%shape)
      if (yes) then
        _RETURN(_SUCCESS)
      endif
      ! initialized with UnlimitedEnity('')
      value => this%get_value()
      if (associated(value)) then
         select type (q=>value)
         type is (character(len=*))
             yes = (q == '')
         end select
      end if
      _RETURN(_SUCCESS)
   end function is_empty
Call graph
is_empty calls get_value, mapl_return
get_value calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_variable calls is_empty
test_is_empty calls is_empty
test_serialize calls is_empty
write_const_variables calls is_empty