is_free – MAPL
is_free Function
4 statements
Source File
private function is_free(this)
Type Bound
CptrWrapper
Arguments
Type Intent Optional Attributes Name
class(CptrWrapper), intent(in) :: this
Return Value logical
Called by
Source Code
   logical function is_free(this)
      class(CptrWrapper), intent(in) :: this
      is_free = .not. c_associated(this%cptr_)
   end function is_free
Call graph
construct_converter calls is_free
finalize calls is_free
free calls is_free
free_cv_converter calls is_free
free_ut_system calls is_free
free_ut_unit calls is_free
get_converter calls is_free, get_converter_function
get_converter_function calls is_free, instance_is_uninitialized
initialize_system calls is_free
initialize calls is_free, finalize, initialize_system, instance_is_uninitialized
instance_is_uninitialized calls is_free
safe_are_convertible calls is_free
test_construct_converter calls is_free
test_construct_system_no_path calls is_free
test_construct_unit calls is_free
test_cptr_wrapper calls is_free
test_get_converter calls is_free, get_converter
converter calls construct_converter
construct_unit calls instance_is_uninitialized
detect_cf_vertical_coord_var calls safe_are_convertible
new_verticalcoordinate calls safe_are_convertible, detect_cf_vertical_coord_var
test_convert_double calls get_converter
test_convert_doubles calls get_converter
test_convert_float calls get_converter
test_convert_floats calls get_converter
udunit calls construct_unit
verticalcoordinate calls new_verticalcoordinate