is_field_undef – MAPL
is_field_undef Function
35 statements
Source File
public function is_field_undef(field, rc) result(field_is_undef)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Contents
Call graph
is_field_undef calls esmf_fieldget, mapl_verify, mapl_assert, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
comparestate calls is_field_undef
run_ calls comparestate