is_initialized – MAPL
is_initialized Function
4 statements
Source File
private function is_initialized(this)
Type Bound
NewRegridderManager
Arguments
Type Intent Optional Attributes Name
class(NewRegridderManager), intent(in) :: this
Return Value logical
Called by
Source Code
   logical function is_initialized(this)
      class(NewRegridderManager), intent(in) :: this
      is_initialized = this%initialized
   end function is_initialized
Call graph
initialize calls is_initialized, create_bundle_rh, createfilemetadata
make_regridder_ calls is_initialized, initialize
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
request_data_from_file calls make_regridder
create_from_bundle calls createfilemetadata
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run calls create_bundle_rh, createfilemetadata