is_leap_year – MAPL
is_leap_year Function
4 statements
Source File
public pure function is_leap_year(y)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
Return Value logical
Called by
Contents
Source Code
is_leap_year
Source Code
   pure logical function is_leap_year(y)
      integer, intent(in) :: y
      ! Leap years are years divisible by 400 or (years divisible by 4 and not divisible by 100)
      is_leap_year = (400 .divides. y) .or. ((4 .divides. y) .and. .not. (100 .divides. y))
   end function is_leap_year
Call graph
get_month_ends calls is_leap_year
test_is_leap_year calls is_leap_year
get_month_end calls get_month_ends
test_get_month_ends calls get_month_ends
is_valid_date calls get_month_end
test_get_month_end calls get_month_end
parse_date calls is_valid_date
test_is_valid_date calls is_valid_date