is_ringing – MAPL
is_ringing Function
21 statements
Source File
private function is_ringing(this, current_time, rc) result(ringing)
Type Bound
SimpleAlarm
Arguments
Type Intent Optional Attributes Name
class(SimpleAlarm), intent(inout) :: this
type(ESMF_Time), intent(inout) :: current_time
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function is_ringing(this,current_time,rc) result(ringing)
      class(SimpleAlarm), intent(inout) :: this
      type(ESMF_Time), intent(inout) :: current_time
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: ringing
      integer(ESMF_KIND_I8) :: ring_interval_i8, elapsed_interval_i8
      type(ESMF_TimeInterval) :: elapsed_interval
      elapsed_interval = current_time - this%reference_time
      call ESMF_TimeIntervalGet(elapsed_interval,s_i8=elapsed_interval_i8,rc=status)
      _VERIFY(status)
      call ESMF_TimeIntervalGet(this%ring_interval,s_i8=ring_interval_i8,rc=status)
      _VERIFY(status)
      if (mod(elapsed_interval_i8,ring_interval_i8) == 0) then
         ringing=.true.
      else
         ringing=.false.
      end if
      _RETURN(_SUCCESS)
   end function is_ringing
Call graph
is_ringing calls ESMF_TimeIntervalGet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
checkupdate calls is_ringing
run_ calls checkupdate