is_time_unit – MAPL
is_time_unit Function
10 statements
Source File
public function is_time_unit(tunit)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: tunit
Return Value logical
Calls
Called by
Contents
Source Code
is_time_unit
Source Code
   function is_time_unit(tunit)
      character(len=*), intent(in) :: tunit
      logical :: is_time_unit
      integer :: i
      is_time_unit = .TRUE.
      do i = 1, size(TIME_UNITS)
         if(lr_trim(tunit) == lr_trim(TIME_UNITS(i))) return
      end do
      is_time_unit = .FALSE.
   end function is_time_unit
Call graph
is_time_unit calls lr_trim
convert_netcdf_datetime_to_esmf calls is_time_unit
test_is_time_unit calls is_time_unit
test_convert_netcdf_datetime_to_esmf calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf, time_real_to_esmf