is_threading_active – MAPL
is_threading_active Function
5 statements
Source File
private function is_threading_active(this) result(threading_active)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(in) :: this
Return Value logical
Called by
Source Code
   function is_threading_active(this) result(threading_active)
     class(MaplGenericComponent), intent(in) :: this
     logical :: threading_active
     threading_active = this%threading_active
   end function is_threading_active
Call graph
get_export_state calls is_threading_active
get_grid calls is_threading_active
get_gridcomp calls is_threading_active
get_import_state calls is_threading_active
get_internal_state calls is_threading_active
omp_driver calls is_threading_active, get_export_state, get_gridcomp, get_import_state
capture calls get_internal_state
get_child_export_state calls get_export_state
get_child_gridcomp calls get_gridcomp
get_child_import_state calls get_import_state
get_child_internal_state calls get_internal_state
mapl_friendlyget calls get_internal_state
mapl_genericfinalize calls get_internal_state
mapl_genericinitialize calls get_internal_state
mapl_genericstatedestroy calls get_internal_state
mapl_genericstateget calls get_grid, get_internal_state
mapl_genericstaterestore calls get_internal_state
mapl_genericstatesave calls get_internal_state
mapl_genericwrapper calls omp_driver
mapl_gridcompgetfriendlies0 calls get_internal_state
mapl_staterecord calls get_internal_state
mapl_staterefresh calls get_internal_state