is_valid_year – MAPL
is_valid_year Function
4 statements
Source File
public pure function is_valid_year(y)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
Return Value logical
Called by
Contents
Source Code
is_valid_year
Source Code
   pure logical function is_valid_year(y)
      integer, intent(in) :: y
      is_valid_year = y .in. [0, 9999]
   end function is_valid_year
Call graph
is_valid_date calls is_valid_year
test_is_valid_year calls is_valid_year
construct_date_fields_default calls is_valid_date
test_is_valid_date calls is_valid_date, date_fields
date_fields calls construct_date_fields_default
parse_date calls date_fields
test_are_valid_date_fields calls date_fields
test_construct_date_fields_null calls date_fields
test_get_day_field calls date_fields
test_get_month_field calls date_fields
test_get_year_field calls date_fields