is_valid_year – MAPL
is_valid_year Function
6 statements
Source File
public pure function is_valid_year(y)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_year
Source Code
   pure logical function is_valid_year(y)
      integer, intent(in) :: y
! Strict ISO8601 compliance does not allow years before 1583
#ifdef STRICT_ISO8601
      integer, parameter :: LB_YEAR = 1582
#else
      integer, parameter :: LB_YEAR = -1
#endif
      integer, parameter :: UB_YEAR = 10000
      is_valid_year = is_between(LB_YEAR, UB_YEAR, y)
   end function is_valid_year
Call graph
is_valid_year calls is_between
is_valid_date calls is_valid_year
test_is_valid_year calls is_valid_year
parse_date calls is_valid_date
test_is_valid_date calls is_valid_date
construct_iso8601date calls parse_date
test_parse_date calls parse_date
iso8601date calls construct_iso8601date