is_valid_dso_extension – MAPL
is_valid_dso_extension Function
4 statements
Source File
public pure function is_valid_dso_extension(extension)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: extension
Return Value logical
Called by
Contents
Source Code
is_valid_dso_extension
Source Code
   pure logical function is_valid_dso_extension(extension)
      character(len=*), intent(in) :: extension
      is_valid_dso_extension = (extension == '' .or. extension == SYSTEM_DSO_EXTENSION)
   end function is_valid_dso_extension
Call graph
is_valid_dso_name calls is_valid_dso_extension
test_is_valid_dso_extension calls is_valid_dso_extension
addchildfromdsometa calls is_valid_dso_name
mapl_addchild calls addchildfromdsometa, addchildfromdso
addchildfromdso calls addchildfromdsometa
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild