is_valid_dso_name – MAPL
is_valid_dso_name Function
4 statements
Source File
public pure function is_valid_dso_name(name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_dso_name
Source Code
   pure logical function is_valid_dso_name(name)
      character(*), intent(in) :: name
      is_valid_dso_name = is_valid_dso_extension(get_file_extension(name))
   end function is_valid_dso_name
Call graph
is_valid_dso_name calls get_file_extension, is_valid_dso_extension
get_file_extension calls find_extension_index
addchildfromdsometa calls is_valid_dso_name
mapl_addchild calls addchildfromdsometa, addchildfromdso, addchildfromdso_old
addchildfromdso calls addchildfromdsometa
addchildfromdso_old calls addchildfromdso
initialize_gc calls mapl_addchild
run_component_driver calls mapl_addchild
main calls run_component_driver