is_valid_date – MAPL
is_valid_date Function
5 statements
Source File
public pure function is_valid_date(date)
Arguments
Type Intent Optional Attributes Name
type(date_fields), intent(in) :: date
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_date
Source Code
   pure logical function is_valid_date(date)
      type(date_fields), intent(in) :: date
      integer, parameter :: LB_DAY = 0
      is_valid_date = is_valid_year(date%year_) .and. &
         is_valid_month(date%month_) .and. &
         is_between(LB_DAY, get_month_end(date%year_, date%month_)+1, date%day_)
   end function is_valid_date
Call graph
is_valid_date calls get_month_end, is_between, is_valid_month, is_valid_year
get_month_end calls get_month_ends
is_valid_month calls is_between
is_valid_year calls is_between
get_month_ends calls is_leap_year
parse_date calls is_valid_date
test_is_valid_date calls is_valid_date
construct_iso8601date calls parse_date
test_parse_date calls parse_date
iso8601date calls construct_iso8601date
construct_iso8601datetime calls iso8601date
convert_iso8601_to_integer_date calls iso8601date
test_construct_iso8601date calls iso8601date
test_iso8601datetime_getters calls iso8601date