is_valid_prototype – MAPL
is_valid_prototype Function
21 statements
Source File
private function is_valid_prototype(this, prototype_name, unusable, rc)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: prototype_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function is_valid_prototype(this, prototype_name, unusable, rc)
      class (GridManager), intent(inout) :: this
      character(len=*), intent(in) :: prototype_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      logical, save :: initialized = .false.
      _UNUSED_DUMMY(unusable)
      ! This is a local variable to prevent the function from running
      ! initialiazation twice. It avoids a shared state variable for
      ! initialization status.
      initialized = .false.
      ! Do not initialize prototypes more than once.
      if (.not. initialized) then
         call initialize_prototypes(this, _RC)
         initialized = .true.
      end if
      is_valid_prototype = .not. this%prototypes%find(prototype_name) == this%prototypes%end()
      _RETURN(_SUCCESS)
   end function is_valid_prototype
Call graph
is_valid_prototype calls initialize_prototypes, m_find, mapl_return, mapl_verify
initialize_prototypes calls mapl_return, insert
m_find calls s_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
m_insert_pair calls s_insert
s_ordereq calls s_lessthan
set_grid calls is_valid_prototype