is_valid_millisecond – MAPL
is_valid_millisecond Function
6 statements
Source File
public pure function is_valid_millisecond(millisecond)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: millisecond
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_millisecond
Source Code
   pure logical function is_valid_millisecond(millisecond)
      integer, intent(in) :: millisecond
      integer, parameter :: LB_MILLISECOND = -1
      integer, parameter :: UB_MILLISECOND = 1000
      is_valid_millisecond = is_between(LB_MILLISECOND, UB_MILLISECOND, millisecond)
   end function is_valid_millisecond
Call graph
is_valid_millisecond calls is_between
is_valid_time calls is_valid_millisecond
test_is_valid_millisecond calls is_valid_millisecond
parse_time calls is_valid_time
test_is_valid_time calls is_valid_time
construct_iso8601time calls parse_time
test_parse_time calls parse_time
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time