is_var_present – MAPL
is_var_present Function
10 statements
Source File
public function is_var_present(this, var_name, rc) result(isPresent)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
integer, intent(out), optional :: rc
Return Value logical
Calls
Source Code
   function is_var_present(this,var_name,rc) result(isPresent)
      class (FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      integer, optional, intent(out) :: rc
      logical :: isPresent
      class(Variable), pointer :: var
      _UNUSED_DUMMY(rc)
      var => this%get_variable(var_name)
      isPresent = associated(var)
   end function is_var_present
Call graph
is_var_present calls get_variable
get_variable calls m_at, mapl_return
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize