is_valid_month – MAPL
is_valid_month Function
6 statements
Source File
public pure function is_valid_month(m)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: m
Return Value logical
Calls
Called by
Contents
Source Code
is_valid_month
Source Code
   pure logical function is_valid_month(m)
      integer, intent(in) :: m
      integer, parameter :: LB_MONTH = 0
      integer, parameter :: UB_MONTH = 13
      is_valid_month = is_between(LB_MONTH, UB_MONTH, m)
   end function is_valid_month
Call graph
is_valid_month calls is_between
is_valid_date calls is_valid_month
test_is_valid_month calls is_valid_month
parse_date calls is_valid_date
test_is_valid_date calls is_valid_date
construct_iso8601date calls parse_date
test_parse_date calls parse_date
iso8601date calls construct_iso8601date