is_whole_number – MAPL
is_whole_number Function
4 statements
Source File
public pure function is_whole_number(n)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Return Value logical
Called by
Contents
Source Code
is_whole_number
Source Code
   pure logical function is_whole_number(n)
      integer, intent(in) :: n
      is_whole_number = .not. (n < 0)
   end function is_whole_number
Call graph
parse_timezone_offset calls is_whole_number, read_whole_number
parse_time calls is_whole_number, parse_timezone_offset, read_whole_number, time_fields
read_whole_number_indexed calls is_whole_number
test_is_whole_number calls is_whole_number
construct_time_fields_string calls parse_time
read_whole_number calls read_whole_number_indexed
test_parse_timezone_offset calls parse_timezone_offset
test_parse_time calls parse_time
test_read_whole_number_indexed calls read_whole_number_indexed
time_fields calls construct_time_fields_string
parse_date calls read_whole_number
test_read_whole_number calls read_whole_number
construct_date_fields_string calls parse_date
test_are_valid_time_fields calls time_fields
test_construct_time_fields_null calls time_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_is_valid_time calls time_fields
test_parse_date calls parse_date