isEmpty_RequestHandle – MAPL
isEmpty_RequestHandle Function
10 statements
Source File
private function isEmpty_RequestHandle(this, rc) result(empty)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(in), target :: this
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function isEmpty_RequestHandle(this, rc) result(empty)
      class (BaseThread), target, intent(in) :: this
      integer, optional, intent(out) :: rc
      logical :: empty
      type (IntegerRequestMapIterator) :: iter
      iter  = this%open_requests%begin()
      empty = (iter == this%open_requests%end())
      _RETURN(_SUCCESS)
   end function isEmpty_RequestHandle
Call graph
isempty_requesthandle calls m_begin, mapl_return
m_begin calls s_begin
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
s_begin calls s_next
s_next calls advpos
done_collective_prefetch calls isempty_requesthandle, done_collective_prefetch
done_collective_stage calls isempty_requesthandle, done_collective_stage
done_prefetch calls isempty_requesthandle, done_prefetch
done_stage calls isempty_requesthandle, done_stage
run calls done_collective_prefetch, done_collective_stage, done_prefetch
mapl_bundlewritencpar calls done_collective_stage
mapl_read_bundle calls done_collective_prefetch
run_model calls done_collective_stage
run_ calls done_collective_prefetch
write_to_file calls done_collective_stage
main calls run, mapl_read_bundle, write_to_file, run_model
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
write_bundle_single_time calls write_to_file
time_ave calls mapl_read_bundle, write_to_file
ut_regridding calls mapl_read_bundle, write_to_file