isEnabledFor – MAPL
isEnabledFor Function
5 statements
Source File
private function isEnabledFor(this, level)
Type Bound
Logger
Arguments
Type Intent Optional Attributes Name
class(Logger), intent(in) :: this
integer, intent(in) :: level
Return Value logical
Called by
Source Code
   logical function isEnabledFor(this, level)
      class (Logger), intent(in) :: this
      integer, intent(in) :: level
      isEnabledFor = .false.
   end function isEnabledFor
Call graph
createtimeinterval calls isenabledfor
getbrackettimeonfile calls isenabledfor
getbrackettimeonsinglefile calls isenabledfor
gettimesonfile calls isenabledfor
mapl_extdatainterpfield calls isenabledfor
updatebrackettime calls isenabledfor, getbrackettimeonfile, getbrackettimeonsinglefile
initialize_ calls createtimeinterval
run_ calls mapl_extdatainterpfield, updatebrackettime