julday – MAPL
julday Function
23 statements
Source File
public function julday(mm, id, iyyy)
Arguments
Type Intent Optional Attributes Name
integer :: mm
integer :: id
integer :: iyyy
Return Value integer
Called by
Source Code
      INTEGER FUNCTION julday(mm,id,iyyy)
      INTEGER id,iyyy,mm,IGREG
      PARAMETER (IGREG=15+31*(10+12*1582))
      INTEGER ja,jm,jy
      jy=iyyy
      if (jy.eq.0) then
        print *, 'julday: there is no year zero'
        return
      endif
      if (jy.lt.0) jy=jy+1
      if (mm.gt.2) then
        jm=mm+1
      else
        jy=jy-1
        jm=mm+13
      endif
      julday=int(365.25*jy)+int(30.6001*jm)+id+1720995
      if (id+31*(mm+12*iyyy).ge.IGREG) then
        ja=int(0.01*jy)
        julday=julday+2-ja+int(0.25*ja)
      endif
      return
      END function julday
Call graph
diffdate calls julday
getdateint8 calls julday
getdate calls getdateint8
cfio_getvar calls diffdate
cfio_putvar calls diffdate
cfio_sgetvar calls diffdate
cfio_sputvar calls diffdate
esmf_cfiosdfvarreadt2d__ calls diffdate
esmf_cfiosdfvarreadt3d__ calls diffdate
esmf_cfiovarreadt2d__ calls diffdate
esmf_cfiovarreadt3d__ calls diffdate
getdateint4 calls getdateint8
writebnds calls diffdate