latlon_zstar – MAPL
latlon_zstar Subroutine
32 statements
Source File
subroutine latlon_zstar(q, qp, undef, grid, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: q(:,:)
real, intent(out) :: qp(:,:)
real, intent(in) :: undef
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
latlon_zstar
Source Code
   subroutine latlon_zstar (q,qp,undef,grid,rc)
      real, intent(inout) :: q(:,:)
      real, intent(out) :: qp(:,:)
      real, intent(in) :: undef
      type (ESMF_Grid), intent(inout) :: grid
      integer, optional, intent(out) :: rc
      integer :: local_dims(3)
      integer im,jm,i,j,status
      real, allocatable :: qz(:)
      call MAPL_GridGet(grid,localCellCountPerDim=local_dims,_RC)
      im = local_dims(1)
      jm = local_dims(2)
      allocate(qz(jm))
      call latlon_zmean ( q,qz,undef,grid )
      do j=1,jm
         if( qz(j).eq. undef ) then
            qp(:,j) = undef
         else
            do i=1,im
               if( defined( q(i,j),undef) ) then
                  qp(i,j) = q(i,j) - qz(j)
               else
                  qp(i,j) = undef
               endif
            enddo
         endif
      enddo
      if (present(rc)) then
         rc=_SUCCESS
      endif
   end subroutine latlon_zstar
Call graph
latlon_zstar calls defined, latlon_zmean, mapl_abort, mapl_gridget, mapl_verify
latlon_zmean calls mapl_abort, mapl_gridget, mapl_verify, ESMF_VMGet, ESMF_VMGetCurrent, mapl_grid_interior, mpi_recv, mpi_send, get_esmf_grid_layout
mapl_abort calls mpi_abort
mapl_gridget calls mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde, mapl_return
mapl_verify calls mapl_throw_exception
mapl_grid_interior calls mapl_grid_interior, ESMF_GridGet, ESMF_DELayoutGet, ESMF_DistGridGet, mapl_distgridget
get_esmf_grid_layout calls mapl_abort, mapl_verify, ESMF_GridGet, ESMF_VMGet, ESMF_VMGetCurrent, mapl_distgridget, mapl_getimsjms
mapl_gridhasde calls mapl_verify, ESMF_GridGet, mapl_return, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_verify, mapl_return, mapl_assert, mapl_sort
time_ave calls latlon_zstar