LatLonGridFactory_from_parameters – MAPL
LatLonGridFactory_from_parameters Function
50 statements
Source File
private function LatLonGridFactory_from_parameters(unusable, grid_name, im_world, jm_world, lm, nx, ny, ims, jms, pole, dateline, lon_range, lat_range, force_decomposition, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(in), optional :: ims(:)
integer, intent(in), optional :: jms(:)
character(len=2), intent(in), optional :: pole
character(len=2), intent(in), optional :: dateline
type(RealMinMax), intent(in), optional :: lon_range
type(RealMinMax), intent(in), optional :: lat_range
logical, intent(in), optional :: force_decomposition
integer, intent(out), optional :: rc
Return Value type(LatLonGridFactory)
Calls
Called by
Contents
Source Code
LatLonGridFactory_from_parameters
Source Code
   function LatLonGridFactory_from_parameters(unusable, grid_name, &
        & im_world, jm_world, lm, nx, ny, ims, jms, &
        & pole, dateline, lon_range, lat_range, force_decomposition, rc) result(factory)
      type (LatLonGridFactory) :: factory
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: grid_name
      ! grid details:
      integer, optional, intent(in) :: im_world
      integer, optional, intent(in) :: jm_world
      integer, optional, intent(in) :: lm
      character(len=2), optional, intent(in) :: pole
      character(len=2), optional, intent(in) :: dateline
      type (RealMinMax), optional, intent(in) :: lon_range
      type (RealMinMax), optional, intent(in) :: lat_range
      ! decomposition:
      integer, optional, intent(in) :: nx
      integer, optional, intent(in) :: ny
      integer, optional, intent(in) :: ims(:)
      integer, optional, intent(in) :: jms(:)
      logical, optional, intent(in) :: force_decomposition
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      factory%is_regular = .true.
      call set_with_default(factory%grid_name, grid_name, MAPL_GRID_NAME_DEFAULT)
      call set_with_default(factory%nx, nx, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%ny, ny, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%im_world, im_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%jm_world, jm_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%lm, lm, MAPL_UNDEFINED_INTEGER)
      ! default is unallocated
      if (present(ims)) factory%ims = ims
      if (present(jms)) factory%jms = jms
      call set_with_default(factory%pole, pole, MAPL_UNDEFINED_CHAR)
      call set_with_default(factory%dateline, dateline, MAPL_UNDEFINED_CHAR)
      call set_with_default(factory%lon_range, lon_range, RealMinMax(MAPL_UNDEFINED_REAL,MAPL_UNDEFINED_REAL))
      call set_with_default(factory%lat_range, lat_range, RealMinMax(MAPL_UNDEFINED_REAL,MAPL_UNDEFINED_REAL))
      call set_with_default(factory%force_decomposition, force_decomposition, .false.)
      call factory%check_and_fill_consistency(rc=status)
      _VERIFY(status)
      ! Compute the centers and corners
      factory%lon_centers = factory%compute_lon_centers(factory%dateline, rc=status)
      _VERIFY(status)
      factory%lat_centers = factory%compute_lat_centers(factory%pole, rc=status)
      _VERIFY(status)
      factory%lon_centers_degrees = factory%compute_lon_centers(factory%dateline, &
            convert_to_radians = .false.,  rc=status)
      _VERIFY(status)
      factory%lat_centers_degrees = factory%compute_lat_centers(factory%pole, &
            convert_to_radians = .false.,  rc=status)
      _VERIFY(status)
      factory%lon_corners = factory%compute_lon_corners(factory%dateline, rc=status)
      _VERIFY(status)
      factory%lat_corners = factory%compute_lat_corners(factory%pole, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function LatLonGridFactory_from_parameters
Call graph
latlongridfactory_from_parameters calls set_with_default, check_and_fill_consistency, compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners, mapl_return, mapl_verify
set_with_default calls set_with_default_character, set_with_default_integer, set_with_default_logical, set_with_default_range, set_with_default_real
check_and_fill_consistency calls mapl_return, mapl_verify, mapl_assert, check_decomposition, generate_newnxy
compute_lat_centers calls mapl_return, mapl_assert, mapl_range
compute_lat_corners calls mapl_return, mapl_assert, mapl_range
compute_lon_centers calls mapl_return, mapl_verify, mapl_range
compute_lon_corners calls mapl_return, mapl_verify, mapl_range
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_range calls mapl_range_real32, mapl_range_real64
check_decomposition calls mapl_return
generate_newnxy calls mapl_return, ims, mapl_decomposedim, jms, generate_new_decomp
get_error_message calls at
mapl_throw_exception calls initialize
mapl_decomposedim calls mapl_decomposedim
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_range_real32 calls mapl_return, mapl_assert
mapl_range_real64 calls mapl_return, mapl_assert
latlongridfactory calls latlongridfactory_from_parameters