latlon2xyz – MAPL
latlon2xyz Function
18 statements
Source File
private function latlon2xyz(sph_coord, right_hand) result(xyz_coord)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in), dimension(2) :: sph_coord
logical, intent(in), optional :: right_hand
Return Value real(kind=REAL64), dimension(3)
Called by
Contents
Call graph
get_unit_vector calls latlon2xyz
mid_pt_sphere calls latlon2xyz
computegridbasis calls get_unit_vector, mid_pt_sphere
get_basis calls computegridbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis