lines_intersect – MAPL
lines_intersect Function
20 statements
Source File
private function lines_intersect(b0, b1, a0, a1) result(intersect)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: b0(3)
real(kind=real64), intent(in) :: b1(3)
real(kind=real64), intent(in) :: a0(3)
real(kind=real64), intent(in) :: a1(3)
Return Value logical
Calls
Called by
Contents
Source Code
lines_intersect
Source Code
 function lines_intersect(b0,b1,a0,a1)  result(intersect)
    real(real64), intent(in) :: b0(3),b1(3),a0(3),a1(3)
    logical :: intersect
    real(real64) :: p(3),q(3),t(3)
    real(real64) :: s1,s2,s3,s4
    logical :: signs(4)
    intersect=.false.
    q=cross_prod(b0,b1)
    p=cross_prod(a0,a1)
    t=normal_vect(cross_prod(p,q))
    s1=dot_product(cross_prod(a0,p),t)
    s2=dot_product(cross_prod(a1,p),t)
    s3=dot_product(cross_prod(b0,q),t)
    s4=dot_product(cross_prod(b1,q),t)
    signs(1) = -s1 <0.d0
    signs(2) = s2 <0.d0
    signs(3) = -s3 < 0.d0
    signs(4) = s4 < 0.d0
    intersect = ((count(signs)==0) .or. (count(signs)==4))
 end function lines_intersect
Call graph
lines_intersect calls cross_prod, normal_vect
point_in_polygon calls lines_intersect
get_points_in_spherical_domain calls point_in_polygon
mapl_gethorzijindex calls get_points_in_spherical_domain, mapl_gethorzijindex