linspace2 – MAPL
linspace2 Subroutine
13 statements
Source File
private subroutine linspace2(d1, d2, n, y)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: d1
real(kind=dp), intent(in) :: d2
integer, intent(in) :: n
real(kind=dp), intent(inout), DIMENSION(:) :: y
Called by
Source Code
SUBROUTINE linspace2(d1,d2,n,y)
        IMPLICIT   NONE
        REAL(dp), INTENT(IN)   :: d1, d2
        INTEGER, INTENT(IN)   :: n
        INTEGER            :: n2, i
        REAL(dp), DIMENSION(:), INTENT(INOUT) :: y
        n2 = n
        DO i = 0, n2-2
          y(i+1) = i
        END DO
        y(1:n2-1) = (d1+y(1:n2-1)*(d2-d1)/(n-1))   ! d2);
        y(n2) = d2
END SUBROUTINE linspace2
Call graph
linspace calls linspace2
find_sweeppoints calls linspace
orbits_swath calls find_sweeppoints
domasking_ calls orbits_swath
domasking_cs calls orbits_swath