LocStreamFactory_from_arrays – MAPL
LocStreamFactory_from_arrays Function
16 statements
Source File
private function LocStreamFactory_from_arrays(lons, lats, unusable, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: lons(:)
real(kind=REAL64), intent(in) :: lats(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(LocStreamFactory)
Calls
Called by
Contents
Source Code
LocStreamFactory_from_arrays
Source Code
      function LocStreamFactory_from_arrays(lons,lats,unusable,rc) result(factory)
         type(LocStreamFactory) :: factory
         real(kind=REAL64), intent(in) :: lons(:)
         real(kind=REAL64), intent(in) :: lats(:)
         class (KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         integer :: status
         _UNUSED_DUMMY(unusable)
         _ASSERT(size(lons)==size(lats),"Lats and Lons for locstream must be same size")
         allocate(factory%lons,source=lons,stat=status)
         _VERIFY(status)
         allocate(factory%lats,source=lats,stat=status)
         _VERIFY(status)
         _RETURN(_SUCCESS)
      end function LocStreamFactory_from_arrays
Call graph
locstreamfactory_from_arrays calls mapl_assert, mapl_verify, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
locstreamfactory calls locstreamfactory_from_arrays