LowCase – MAPL
LowCase Subroutine
13 statements
Source File
public subroutine LowCase(str1, str2)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str1
character(len=*), intent(out) :: str2
Called by
Source Code
  SUBROUTINE LowCase (str1, str2)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Transform upper case letters in str1 into lower case letters, result is str2
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    CHARACTER (LEN=*),  INTENT(in) :: str1
    CHARACTER (LEN=*), INTENT(out) :: str2
    INTEGER                        :: j,k
    CHARACTER (LEN=*),   PARAMETER :: lc = 'abcdefghijklmnopqrstuvwxyz'
    CHARACTER (LEN=*),   PARAMETER :: uc = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    str2 = str1
    DO j=1,LEN_TRIM(str1)
       k = INDEX(uc,str1(j:j))
       IF (k > 0) str2(j:j) = lc(k:k)
    END DO
  END SUBROUTINE LowCase
Call graph
checkundef calls lowcase
mathfunctionindex calls lowcase
checksyntax calls checkundef, mathfunctionindex
compilesubstr calls mathfunctionindex, compilesubstr, mathitemindex
mathitemindex calls checkundef
parser_variables_in_expression calls checkundef, mathfunctionindex
compile calls compilesubstr
get_mask_variables calls parser_variables_in_expression
get_variables_in_expression calls parser_variables_in_expression, get_mask_variables
initialize_ calls checksyntax
mapl_setexpression calls checksyntax
mapl_stateeval calls checksyntax, parsef
parsef calls checksyntax, compile
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
get_extra_derived_items calls get_variables_in_expression
initialize calls mapl_setexpression
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval