lr_trim – MAPL
lr_trim Function
5 statements
Source File
public function lr_trim(string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value character(len=:), allocatable
Called by
Contents
Source Code
lr_trim
Source Code
   function lr_trim(string)
      character(len=*), intent(in) :: string
      character(len=:), allocatable :: lr_trim
      lr_trim = trim(adjustl(string))
   end function lr_trim
Call graph
convert_netcdf_datetime_to_esmf calls lr_trim, get_shift_sign, is_time_unit, make_esmf_timeinterval
get_shift_sign calls lr_trim
is_time_unit calls lr_trim
make_esmf_timeinterval calls lr_trim
make_netcdf_datetime_int_time calls lr_trim
test_lr_trim calls lr_trim
convert_esmf_to_netcdf_datetime calls make_netcdf_datetime_int_time
test_convert_netcdf_datetime_to_esmf calls convert_netcdf_datetime_to_esmf
test_get_shift_sign calls get_shift_sign
test_is_time_unit calls is_time_unit
test_make_esmf_timeinterval calls make_esmf_timeinterval
test_make_netcdf_datetime_int_time calls make_netcdf_datetime_int_time
time_real_to_esmf calls convert_netcdf_datetime_to_esmf, time_real_to_esmf
test_convert_esmf_to_netcdf_datetime calls convert_esmf_to_netcdf_datetime