m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
StringVariableMap
Arguments
Type Intent Optional Attributes Name
class(StringVariableMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value class(Variable), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
def_variables calls m_at
equal calls m_at
get_coordinate_variable calls m_at
get_variable calls m_at
has_variable calls m_at
is_coordinate_variable calls m_at
set_order calls m_at