m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
StringNetCDF4_FileFormatterMap
Arguments
Type Intent Optional Attributes Name
class(StringNetCDF4_FileFormatterMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(NetCDF4_FileFormatter), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
clear calls m_at
clear_hist_collections calls clear
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections
start calls clean_up, put_datatofile, start_back