m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
ExtDataRuleMap
Arguments
Type Intent Optional Attributes Name
class(ExtDataRuleMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(ExtDataRule), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
add_new_rule calls m_at
fillin_primary calls m_at
get_item_type calls m_at
initialize_ calls fillin_primary, get_item_type
new_extdataconfig_from_yaml calls add_new_rule, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml
extdataoldtypescreator calls new_extdataoldtypescreator