m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
IntegerMessageMap
Arguments
Type Intent Optional Attributes Name
class(IntegerMessageMap), intent(in), target :: this
integer, intent(in) :: key
Return Value class(AbstractMessage), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
decode calls m_at
make_message calls m_at
deserialize_message_vector calls decode
receive calls decode
test_parse_terminate calls decode
create_remote_win calls deserialize_message_vector
deserialize calls deserialize_message_vector
test_back_and_forth calls receive
test_send_terminate calls receive
main calls deserialize_message_vector
start calls create_remote_win
start_back calls deserialize