m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
Integer64GridFactoryMap
Arguments
Type Intent Optional Attributes Name
class(Integer64GridFactoryMap), intent(in), target :: this
integer(kind=INT64), intent(in) :: key
Return Value class(AbstractGridFactory), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
get_factory calls m_at, get_factory
make_grid_from_factory calls m_at
addgrid calls get_factory
regrid_vector_2d_real32 calls get_factory
regrid_vector_2d_real64 calls get_factory
regrid_vector_3d_real32 calls get_factory
regrid_vector_3d_real64 calls get_factory
transpose_regrid_vector_2d_real32 calls get_factory
transpose_regrid_vector_3d_real32 calls get_factory
createfilemetadata calls get_factory, createvariable
createvariable calls get_factory
esmfl_halo_r4_2d calls get_factory
find_tile_file calls get_factory
get_latlon_from_factory calls get_factory
initialize calls addgrid, createfilemetadata
mapl_create_bundle_from_metdata_id calls get_factory
mapl_esmfstatereadfromfile calls get_factory
request_data_from_file calls get_factory
stage2dlatlon calls get_factory
stagedata calls get_factory
esmfl_halo calls esmfl_halo_r4_2d
bundlepost calls stage2dlatlon, stagedata
create_from_bundle calls createfilemetadata
initialize_subclass calls find_tile_file
mapl_cfiocreatefrombundle calls get_latlon_from_factory
mapl_extdataprefetch calls request_data_from_file
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_read_bundle calls mapl_create_bundle_from_metdata_id, request_data_from_file
mapl_staterefresh calls mapl_esmfstatereadfromfile