m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
StringAttributeMap
Arguments
Type Intent Optional Attributes Name
class(StringAttributeMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(Attribute), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
equal calls m_at
get_attribute calls m_at, get_attribute
is_attribute_present calls m_at
transfer_metadata calls m_at
check_flip calls get_attribute, is_attribute_present
compute_time_for_current calls get_attribute
coordinate_has_bounds calls is_attribute_present
get_attribute_int32 calls get_attribute
get_attribute_int64 calls get_attribute
get_attribute_real32 calls get_attribute
get_attribute_real64 calls get_attribute
get_attribute_string calls get_attribute
get_coordinate_bounds calls get_attribute
get_coordinate_bounds_name calls get_attribute
get_coordinate_info calls get_attribute
get_file_start_time calls get_attribute
get_level_name calls is_attribute_present
get_start_time calls get_attribute
get_time_info calls get_attribute
get_variable_attribute calls get_attribute, is_attribute_present
has_attribute calls is_attribute_present
mapl_iogettime calls get_attribute
test_get_attribute_real_double calls get_attribute
test_get_attribute_scalar_int calls get_attribute
test_get_attribute_string calls get_attribute
var_has_attr calls is_attribute_present
var_has_missing_value calls is_attribute_present
write_data calls get_attribute
main calls transfer_metadata