m_at – MAPL
m_at Function
13 statements
Source File
private function m_at(this, key) result(res)
Type Bound
StringGridFactoryMap
Arguments
Type Intent Optional Attributes Name
class(StringGridFactoryMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value class(AbstractGridFactory), pointer
Calls
Called by
Call graph
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
make_clone calls m_at
test_retrieve_exists calls m_at
test_retrieve_multi calls m_at
make_factory_from_config calls make_clone
make_factory_from_distgrid calls make_clone
make_factory_from_file calls make_clone
find calls make_factory
make_grid_from_config calls make_factory
make_grid_from_distgrid calls make_factory
mapl_esmfstatereadfromfile calls make_factory
time_ave calls make_factory