m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
StringUnlimitedEntityMap
Arguments
Type Intent Optional Attributes Name
class(StringUnlimitedEntityMap), intent(in), target :: this
Return Value type(StringUnlimitedEntityMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
stringunlimitedentitymap_serialize calls m_begin