m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
ExtDataRuleMap
Arguments
Type Intent Optional Attributes Name
class(ExtDataRuleMap), intent(in), target :: this
Return Value type(ExtDataRuleMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
count_rules_for_item calls m_begin
get_item_type calls m_begin
get_time_range calls m_begin
has_rule_for calls m_begin
get_extra_derived_items calls has_rule_for
initialize_ calls count_rules_for_item, get_item_type, get_time_range, get_extra_derived_items