m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(in), target :: this
Return Value type(IntegerRequestMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
clear_requesthandle calls m_begin, clear_requesthandle
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait_all calls clear_requesthandle
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls wait_all
terminate calls wait_all
wait calls wait_all
finalize_io_clients_servers calls terminate
post_wait calls post_wait_all
start calls clean_up
main calls run, terminate