m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(in), target :: this
Return Value type(IntegerRequestMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
clear_requesthandle calls m_begin, clear_requesthandle
isempty_requesthandle calls m_begin
done_collective_prefetch calls isempty_requesthandle, done_collective_prefetch
done_collective_stage calls isempty_requesthandle, done_collective_stage
done_prefetch calls isempty_requesthandle, done_prefetch
done_stage calls isempty_requesthandle, done_stage
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait_all calls clear_requesthandle
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls done_collective_prefetch, done_collective_stage, wait_all, done_prefetch
terminate calls wait_all
wait calls wait_all