m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
StringAttributeMap
Arguments
Type Intent Optional Attributes Name
class(StringAttributeMap), intent(in), target :: this
Return Value type(StringAttributeMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
equal calls m_begin
put_attributes calls m_begin
put_var_attributes calls m_begin
stringattributemap_serialize calls m_begin
transfer_metadata calls m_begin
def_variables calls put_var_attributes
put_datatofile calls stringattributemap_serialize
serialize calls stringattributemap_serialize, serialize, stringvariablemap_serialize
write calls put_attributes, def_variables
main calls transfer_metadata
add_variable calls def_variables
stringvariablemap_serialize calls serialize
test_serialize calls serialize
get_length calls serialize
historycollectionvector_serialize calls serialize
receive_output_data calls serialize
stringvariablemap_get_length calls stringvariablemap_serialize