m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
StringGridMap
Arguments
Type Intent Optional Attributes Name
class(StringGridMap), intent(in), target :: this
Return Value type(StringGridMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
destroy_rh_regen_ogrid calls m_begin
initialize calls m_begin
run calls destroy_rh_regen_ogrid