m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
StringVariableMap
Arguments
Type Intent Optional Attributes Name
class(StringVariableMap), intent(in), target :: this
Return Value type(StringVariableMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
check_flip calls m_begin
equal calls m_begin
get_level_name calls m_begin
getlevs calls m_begin, get_level_name
mapl_create_bundle_from_metdata_id calls m_begin, get_level_name
mapl_iochangeres calls m_begin
mapl_iocountlevels calls m_begin
mapl_iocountnondimvars calls m_begin
mapl_iogetnondimvars calls m_begin
modifymetadata calls m_begin
stringvariablemap_serialize calls m_begin
transfer_metadata calls m_begin
write_const_variables calls m_begin
write_coordinate_variables calls m_begin
write_data calls m_begin
write_variables calls m_begin
create_grid calls get_level_name
get_file_levels calls get_level_name
handle_modifymetadata calls modifymetadata
initialize_ calls getlevs
mapl_bundlereadncpar calls check_flip
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
serialize calls stringvariablemap_serialize
stringvariablemap_get_length calls stringvariablemap_serialize
write calls write_const_variables, write_coordinate_variables
write_formatted calls write_variables
main calls transfer_metadata, write_data
time_ave calls get_level_name