m_begin – MAPL
m_begin Function
6 statements
Source File
private function m_begin(this) result(iter)
Type Bound
StringNetCDF4_FileFormatterMap
Arguments
Type Intent Optional Attributes Name
class(StringNetCDF4_FileFormatterMap), intent(in), target :: this
Return Value type(StringNetCDF4_FileFormatterMapIterator)
Calls
Called by
Call graph
m_begin calls s_begin
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
clear calls m_begin
main calls m_begin
clear_hist_collections calls clear
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections
start calls start_back, clean_up, put_datatofile