m_deepCopy – MAPL
m_deepCopy Subroutine
5 statements
Source File
private subroutine m_deepCopy(this, original)
Type Bound
StringNetCDF4_FileFormatterMap
Arguments
Type Intent Optional Attributes Name
class(StringNetCDF4_FileFormatterMap), intent(out) :: this
class(StringNetCDF4_FileFormatterMap), intent(in) :: original
Calls
Call graph
m_deepcopy calls s_deepcopy
s_deepcopy calls s_begin, s_insert, s_next
s_begin calls s_next
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
s_next calls advpos
advpos calls exists, at, get_child, opposite
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to