m_erase_one – MAPL
m_erase_one Subroutine
5 statements
Source File
private subroutine m_erase_one(this, iter)
Type Bound
StringNetCDF4_FileFormatterMap
Arguments
Type Intent Optional Attributes Name
class(StringNetCDF4_FileFormatterMap), intent(inout) :: this
type(StringNetCDF4_FileFormatterMapIterator), intent(inout) :: iter
Calls
Called by
Call graph
m_erase_one calls erase
s_erase_multi calls at, set, erase_nonleaf, exists, rebalance, s_next, set_parent_child
s_erase_one calls erase, s_next
erase_nonleaf calls at, set, exists, rebalance, set_parent_child, advpos, set_child
rebalance calls at, exists, get_child, opposite, rot, update_height
s_next calls advpos
set_parent_child calls at, set_child
clear calls erase
main calls erase
clear_hist_collections calls clear
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections