m_erase_one – MAPL
m_erase_one Subroutine
5 statements
Source File
private subroutine m_erase_one(this, iter)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(inout) :: this
type(IntegerRequestMapIterator), intent(inout) :: iter
Calls
Called by
Call graph
m_erase_one calls erase
s_erase_multi calls at, set, erase_nonleaf, exists, rebalance, s_next, set_parent_child
s_erase_one calls erase, s_next
erase_nonleaf calls at, set, exists, rebalance, set_parent_child, advpos, set_child
rebalance calls at, exists, get_child, opposite, rot, update_height
s_next calls advpos
set_parent_child calls at, set_child
clear_requesthandle calls erase, clear_requesthandle
erase_requesthandle calls erase
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait calls erase_requesthandle, wait_all
wait_all calls clear_requesthandle
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls wait_all
terminate calls wait_all