m_erase_one – MAPL
m_erase_one Subroutine
5 statements
Source File
private subroutine m_erase_one(this, iter)
Type Bound
RegridderSpecRouteHandleMap
Arguments
Type Intent Optional Attributes Name
class(RegridderSpecRouteHandleMap), intent(inout) :: this
type(RegridderSpecRouteHandleMapIterator), intent(inout) :: iter
Calls
Called by
Call graph
m_erase_one calls erase
s_erase_multi calls at, set, erase_nonleaf, exists, rebalance, s_next, set_parent_child
s_erase_one calls erase, s_next
erase_nonleaf calls at, set, exists, rebalance, set_parent_child, advpos, set_child
rebalance calls at, exists, get_child, opposite, rot, update_height
s_next calls advpos
set_parent_child calls at, set_child
destroy_route_handle calls erase
destroy calls destroy_route_handle