m_find – MAPL
m_find Function
9 statements
Source File
private function m_find(this, key) result(iter)
Type Bound
ExtDataFileStreamMap
Arguments
Type Intent Optional Attributes Name
class(ExtDataFileStreamMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(ExtDataFileStreamMapIterator)
Calls
Called by
Call graph
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
m_at calls m_find
new_extdataconfig_from_yaml calls m_at, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml
initialize_ calls new_extdataoldtypescreator