m_find – MAPL
m_find Function
9 statements
Source File
private function m_find(this, key) result(iter)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(in), target :: this
integer, intent(in) :: key
Return Value type(IntegerRequestMapIterator)
Calls
Called by
Call graph
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
erase_requesthandle calls m_find
get_requesthandle calls m_find
m_at calls m_find
handle_done_stage calls get_requesthandle
put calls get_requesthandle
receive_output_data calls get_requesthandle, receive_output_data
wait calls erase_requesthandle, get_requesthandle
start calls receive_output_data