m_find – MAPL
m_find Function
9 statements
Source File
private function m_find(this, key) result(iter)
Type Bound
StringCompositeMap
Arguments
Type Intent Optional Attributes Name
class(StringCompositeMap), intent(in), target :: this
character(len=*), intent(in) :: key
Return Value type(StringCompositeMapIterator)
Calls
Called by
Call graph
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
m_at calls m_find
add_child calls m_at, add_child
get_child_by_name calls m_at, get_child
test_get_child calls add_child, get_child
add_child_component calls add_child
addchild_preamble calls add_child
get_child_by_index calls get_child