m_find – MAPL
m_find Function
9 statements
Source File
private function m_find(this, key) result(iter)
Type Bound
Integer64GridFactoryMap
Arguments
Type Intent Optional Attributes Name
class(Integer64GridFactoryMap), intent(in), target :: this
integer(kind=INT64), intent(in) :: key
Return Value type(Integer64GridFactoryMapIterator)
Calls
Called by
Call graph
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
destroy_grid calls m_find, m_at
m_at calls m_find
get_factory calls m_at, get_factory
make_grid_from_factory calls m_at
addgrid calls get_factory
destroy_rh_regen_ogrid calls destroy
fill_time_in_bundle calls get_factory
regrid_accumulate_on_xysubset calls get_factory
regrid_vector_2d_real32 calls get_factory
regrid_vector_2d_real64 calls get_factory
regrid_vector_3d_real32 calls get_factory
regrid_vector_3d_real64 calls get_factory
transpose_regrid_vector_2d_real32 calls get_factory
transpose_regrid_vector_3d_real32 calls get_factory
create_bundle_rh calls get_factory
createfilemetadata calls get_factory
createquantizationinfo calls get_factory
createvariable calls get_factory
esmfl_halo_r4_2d calls get_factory
find_tile_file calls get_factory
get_latlon_from_factory calls get_factory
initialize calls addgrid
mapl_create_bundle_from_metdata_id calls get_factory
mapl_esmfstatereadfromfile calls get_factory
request_data_from_file calls get_factory
run calls destroy_rh_regen_ogrid, fill_time_in_bundle, regrid_accumulate_on_xysubset
stage2dlatlon calls get_factory
stagedata calls get_factory