m_get – MAPL
m_get Function
17 statements
Source File
private function m_get(this, key, value) result(res)
Type Bound
RegridderTypeSpecRegridderMap
Arguments
Type Intent Optional Attributes Name
class(RegridderTypeSpecRegridderMap), intent(in), target :: this
type(RegridderTypeSpec) :: key
class(AbstractRegridder), intent(out), pointer :: value
Return Value logical
Calls
Call graph
m_get calls s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind