m_get – MAPL
m_get Function
13 statements
Source File
private function m_get(this, key, value) result(res)
Type Bound
StringRouteHandleMap
Arguments
Type Intent Optional Attributes Name
class(StringRouteHandleMap), intent(in), target :: this
character(len=*) :: key
type(ESMF_RouteHandle), intent(out), pointer :: value
Return Value logical
Calls
Call graph
m_get calls s_find
s_find calls findnode, s_ordereq
findnode calls s_ordereq, s_child, s_lessthan
s_ordereq calls s_lessthan