m_insert_pair – MAPL
m_insert_pair Subroutine
5 statements
Source File
private subroutine m_insert_pair(this, p)
Type Bound
IntegerRequestMap
Arguments
Type Intent Optional Attributes Name
class(IntegerRequestMap), intent(inout) :: this
type(pair), intent(in) :: p
Calls
Called by
Call graph
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to
get_child calls at
rot calls exists, at, get_child, opposite, update_height, set, set_child, set_parent_child
tt_at_32 calls tt_at_size_kind
tt_grow_to calls tt_capacity, tt_set_capacity
tt_set_32 calls set
update_height calls exists, at, set
insert_requesthandle calls insert
m_new_map_from_pair_array calls insert
integerrequestmap calls m_new_map_from_pair_array
collective_prefetch_data calls insert_requesthandle, collective_prefetch_data
collective_stage_data calls insert_requesthandle, collective_stage_data
get_datafrommem calls insert_requesthandle, get_datafrommem
handle_collectivestagedata calls insert_requesthandle
handle_done_prefetch calls insert_requesthandle
handle_stagedata calls insert_requesthandle
prefetch_data calls insert_requesthandle, prefetch_data
stage_data calls insert_requesthandle, stage_data
stage_nondistributed_data calls insert_requesthandle, collective_stage_data
run calls prefetch_data, collective_prefetch_data, collective_stage_data, stage_nondistributed_data
test_prefetch_data calls prefetch_data
test_wait calls prefetch_data