m_insert_pair – MAPL
m_insert_pair Subroutine
5 statements
Source File
private subroutine m_insert_pair(this, p)
Type Bound
StringGridFactoryMap
Arguments
Type Intent Optional Attributes Name
class(StringGridFactoryMap), intent(inout) :: this
type(pair), intent(in) :: p
Calls
Called by
Call graph
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to
get_child calls at
rot calls exists, at, get_child, opposite, update_height, set, set_child, set_parent_child
tt_at_32 calls tt_at_size_kind
tt_grow_to calls tt_capacity, tt_set_capacity
tt_set_32 calls set
update_height calls exists, at, set
add_prototype calls insert
initialize_prototypes calls insert
m_new_map_from_pair_array calls insert
test_retrieve_exists calls insert
test_retrieve_multi calls insert
stringgridfactorymap calls m_new_map_from_pair_array
is_valid_prototype calls initialize_prototypes
make_clone calls initialize_prototypes
test_add_prototype calls add_prototype
test_grid_type calls add_prototype
test_make_grid_multi calls add_prototype
test_make_grid_prototype calls add_prototype
make_factory_from_config calls make_clone
make_factory_from_distgrid calls make_clone
make_factory_from_file calls make_clone
set_grid calls is_valid_prototype