m_insert_pair – MAPL
m_insert_pair Subroutine
5 statements
Source File
private subroutine m_insert_pair(this, p)
Type Bound
StringAttributeMap
Arguments
Type Intent Optional Attributes Name
class(StringAttributeMap), intent(inout) :: this
type(pair), intent(in) :: p
Calls
Called by
Call graph
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to
get_child calls at
rot calls exists, at, get_child, opposite, update_height, set, set_child, set_parent_child
tt_at_32 calls tt_at_size_kind
tt_grow_to calls tt_capacity, tt_set_capacity
tt_set_32 calls set
update_height calls exists, at, set
add_attribute_0d calls insert
add_attribute_1d calls insert
m_new_map_from_pair_array calls insert
put_datatofile calls insert
start_back calls insert
stringattributemap_deserialize calls insert
stringattributemap calls m_new_map_from_pair_array
start calls start_back
variable_deserialize calls stringattributemap_deserialize
main calls stringattributemap_deserialize