m_key – MAPL
m_key Function
7 statements
Source File
private function m_key(this) result(res)
Type Bound
StringVariableMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringVariableMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Called by
Call graph
check_flip calls m_key
equal calls m_key
get_level_name calls m_key
getlevs calls m_key, get_level_name
mapl_create_bundle_from_metdata_id calls m_key, get_level_name
mapl_iochangeres calls m_key
mapl_iocountlevels calls m_key
mapl_iocountnondimvars calls m_key
mapl_iogetnondimvars calls m_key
modifymetadata calls m_key
stringvariablemap_serialize calls m_key
transfer_metadata calls m_key
write_const_variables calls m_key
write_coordinate_variables calls m_key
write_data calls m_key
write_variables calls m_key
create_grid calls get_level_name
get_file_levels calls get_level_name
handle_modifymetadata calls modifymetadata
initialize_ calls getlevs
mapl_bundlereadncpar calls check_flip
mapl_read_bundle calls mapl_create_bundle_from_metdata_id
serialize calls stringvariablemap_serialize
stringvariablemap_get_length calls stringvariablemap_serialize
write calls write_const_variables, write_coordinate_variables
write_formatted calls write_variables
main calls transfer_metadata, write_data
time_ave calls get_level_name