m_key – MAPL
m_key Function
7 statements
Source File
private function m_key(this) result(res)
Type Bound
StringNetCDF4_FileFormatterMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringNetCDF4_FileFormatterMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Called by
Call graph
clear calls m_key
clear_hist_collections calls clear
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections
start calls clean_up, put_datatofile, start_back