m_key – MAPL
m_key Function
7 statements
Source File
private function m_key(this) result(res)
Type Bound
StringAttributeMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringAttributeMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Called by
Call graph
equal calls m_key
put_attributes calls m_key
put_var_attributes calls m_key
stringattributemap_serialize calls m_key
transfer_metadata calls m_key
def_variables calls put_var_attributes
put_datatofile calls stringattributemap_serialize
serialize calls stringattributemap_serialize, serialize, stringvariablemap_serialize
write calls put_attributes, def_variables
main calls transfer_metadata
add_variable calls def_variables
stringvariablemap_serialize calls serialize
test_serialize calls serialize
get_length calls serialize
historycollectionvector_serialize calls serialize
receive_output_data calls serialize
stringvariablemap_get_length calls stringvariablemap_serialize