m_key – MAPL
m_key Function
7 statements
Source File
private function m_key(this) result(res)
Type Bound
ExtDataRuleMapIterator
Arguments
Type Intent Optional Attributes Name
class(ExtDataRuleMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Called by
Call graph
count_rules_for_item calls m_key
get_item_type calls m_key
get_time_range calls m_key
has_rule_for calls m_key
get_extra_derived_items calls has_rule_for
initialize_ calls count_rules_for_item, get_item_type, get_time_range, get_extra_derived_items