m_next – MAPL
m_next Subroutine
4 statements
Source File
private subroutine m_next(this)
Type Bound
StringUnlimitedEntityMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringUnlimitedEntityMapIterator), intent(inout) :: this
Calls
Called by
Call graph
m_next calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
stringunlimitedentitymap_serialize calls m_next