m_next – MAPL
m_next Subroutine
4 statements
Source File
private subroutine m_next(this)
Type Bound
StringAttributeMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringAttributeMapIterator), intent(inout) :: this
Calls
Called by
Call graph
m_next calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equal calls m_next
put_attributes calls m_next
put_var_attributes calls m_next
stringattributemap_serialize calls m_next
transfer_metadata calls m_next
def_variables calls put_var_attributes
put_datatofile calls stringattributemap_serialize
serialize calls stringattributemap_serialize, serialize, stringvariablemap_serialize
write calls put_attributes, def_variables
main calls transfer_metadata
add_variable calls def_variables
stringvariablemap_serialize calls serialize
test_serialize calls serialize
get_length calls serialize
historycollectionvector_serialize calls serialize
receive_output_data calls serialize
stringvariablemap_get_length calls stringvariablemap_serialize