m_next – MAPL
m_next Subroutine
4 statements
Source File
private subroutine m_next(this)
Type Bound
IntegerMessageMapIterator
Arguments
Type Intent Optional Attributes Name
class(IntegerMessageMapIterator), intent(inout) :: this
Calls
Called by
Call graph
m_next calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
start_back calls m_next
start calls start_back