m_next – MAPL
m_next Subroutine
4 statements
Source File
private subroutine m_next(this)
Type Bound
Integer64GridFactoryMapIterator
Arguments
Type Intent Optional Attributes Name
class(Integer64GridFactoryMapIterator), intent(inout) :: this
Calls
Called by
Call graph
m_next calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
add_factory calls m_next
get_id calls add_factory
make_grid_from_factory calls add_factory