m_new_map_from_pair_array – MAPL
m_new_map_from_pair_array Function
8 statements
Source File
private function m_new_map_from_pair_array(pairs) result(m)
Arguments
Type Intent Optional Attributes Name
type(pair), intent(in) :: pairs(:)
Return Value type(StringNetCDF4_FileFormatterMap)
Calls
Called by
Call graph
m_new_map_from_pair_array calls insert
m_insert_pair calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
stringnetcdf4_fileformattermap calls m_new_map_from_pair_array