m_next – MAPL
m_next Subroutine
4 statements
Source File
private subroutine m_next(this)
Type Bound
StringVariableMapIterator
Arguments
Type Intent Optional Attributes Name
class(StringVariableMapIterator), intent(inout) :: this
Calls
Called by
Call graph
m_next calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
check_flip calls m_next
equal calls m_next
get_level_name calls m_next
getlevs calls m_next, get_level_name
mapl_iochangeres calls m_next
mapl_iocountlevels calls m_next
mapl_iocountnondimvars calls m_next
mapl_iogetnondimvars calls m_next
modifymetadata calls m_next
stringvariablemap_serialize calls m_next
transfer_metadata calls m_next
write_const_variables calls m_next
write_coordinate_variables calls m_next
write_data calls m_next
write_variables calls m_next
create_grid calls get_level_name
get_file_levels calls get_level_name
handle_modifymetadata calls modifymetadata
initialize_ calls getlevs
mapl_bundlereadncpar calls check_flip
mapl_create_bundle_from_metdata_id calls get_level_name
serialize calls stringvariablemap_serialize
stringvariablemap_get_length calls stringvariablemap_serialize
write calls write_const_variables, write_coordinate_variables
write_formatted calls write_variables
main calls transfer_metadata, write_data
time_ave calls get_level_name