m_next – MAPL
m_next Subroutine
4 statements
Source File
private subroutine m_next(this)
Type Bound
ExtDataRuleMapIterator
Arguments
Type Intent Optional Attributes Name
class(ExtDataRuleMapIterator), intent(inout) :: this
Calls
Called by
Call graph
m_next calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
count_rules_for_item calls m_next
get_item_type calls m_next
get_time_range calls m_next
has_rule_for calls m_next
get_extra_derived_items calls has_rule_for
initialize_ calls count_rules_for_item, get_item_type, get_time_range, get_extra_derived_items