m_previous – MAPL
m_previous Subroutine
4 statements
Source File
private subroutine m_previous(this)
Type Bound
RegridderTypeSpecRegridderMapIterator
Arguments
Type Intent Optional Attributes Name
class(RegridderTypeSpecRegridderMapIterator), intent(inout) :: this
Calls
Call graph
m_previous calls s_prev
s_prev calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at