m_set – MAPL
m_set Subroutine
10 statements
Source File
private subroutine m_set(this, key, value)
Type Bound
StringVariableMap
Arguments
Type Intent Optional Attributes Name
class(StringVariableMap), intent(inout) :: this
character(len=*), intent(in) :: key
class(Variable), intent(in) :: value
Calls
Called by
Call graph
m_set calls s_insert
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to
get_child calls at
rot calls exists, at, get_child, opposite, update_height, set, set_child, set_parent_child
tt_at_32 calls tt_at_size_kind
tt_grow_to calls tt_capacity, tt_set_capacity
tt_set_32 calls set
update_height calls exists, at, set
modify_variable calls m_set
create_file_handle calls modify_variable, create_file_handle
modifymetadata calls modify_variable
modifytime calls modify_variable
test_equal_diff_variables calls modify_variable
handle_modifymetadata calls modifymetadata
run calls modifytime
start_new_file calls modifytime
main calls start_new_file
time_ave calls start_new_file