make_directory_window – MAPL
make_directory_window Function
20 statements
Source File
private function make_directory_window(comm, addr) result(win)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
type(c_ptr), intent(out) :: addr
Return Value integer
Calls
Called by
Source Code
   integer function make_directory_window(comm, addr) result(win)
      integer, intent(in) :: comm
      type (c_ptr), intent(out) :: addr
      type (Directory), pointer :: dir
      type (Directory), target  :: dirnull
      integer(kind=MPI_ADDRESS_KIND) :: sz
#if !defined (SUPPORT_FOR_MPI_ALLOC_MEM_CPTR)
      integer(kind=MPI_ADDRESS_KIND) :: baseaddr
#endif
      integer :: ierror, rank
      call MPI_Comm_Rank(comm, rank, ierror)
      if (rank == 0)  then
         sz = sizeof_directory()
#if defined(SUPPORT_FOR_MPI_ALLOC_MEM_CPTR)
         call MPI_Alloc_mem(sz, MPI_INFO_NULL, addr, ierror)
#else
         call MPI_Alloc_mem(sz, MPI_INFO_NULL, baseaddr, ierror)
         addr = transfer(baseaddr, addr)
#endif
         call c_f_pointer(addr, dir)
      else
         sz  = 0
         dir =>dirnull
      endif
      call MPI_Win_create(dir, sz, 1, MPI_INFO_NULL, comm, win, ierror)
   end function make_directory_window
Call graph
make_directory_window calls mpi_alloc_mem, mpi_comm_rank, mpi_win_create, sizeof_directory
new_directoryservice calls make_directory_window
directoryservice calls new_directoryservice