make_BW_Benchmark – MAPL
make_BW_Benchmark Function
19 statements
Source File
public function make_BW_Benchmark(spec, comm, rc) result(benchmark)
Arguments
Type Intent Optional Attributes Name
type(ComboSpec), intent(in) :: spec
integer, intent(in) :: comm
integer, intent(out), optional :: rc
Return Value type(BW_Benchmark)
Calls
Called by
Contents
Source Code
make_BW_Benchmark
Source Code
   function make_BW_Benchmark(spec, comm, rc) result(benchmark)
      type(BW_Benchmark) :: benchmark
      type(ComboSpec), intent(in) :: spec
      integer, intent(in) :: comm
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: rank
      associate (packet_size => int(spec%nx,kind=INT64)**2 * 6* spec%n_levs/spec%n_writers)
        allocate(benchmark%buffer(packet_size), _STAT)
        call random_number(benchmark%buffer)
      end associate
      call MPI_Comm_rank(comm, rank, _IERROR)
      benchmark%filename = make_filename(base='scratch.', rank=rank, width=5, _RC)
      _RETURN(_SUCCESS)
   end function make_BW_Benchmark
Call graph
make_bw_benchmark calls buffer, mpi_comm_rank, make_filename, mapl_return, mapl_verify
make_filename calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
run calls make_bw_benchmark
time calls run
main calls run