make_NetCDF_DateTime_int_time – MAPL
make_NetCDF_DateTime_int_time Subroutine
31 statements
Source File
public subroutine make_NetCDF_DateTime_int_time(interval, t0, tunit, int_time, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TimeInterval), intent(inout) :: interval
type(ESMF_Time), intent(inout) :: t0
character(len=*), intent(in) :: tunit
integer, intent(out) :: int_time
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
make_NetCDF_DateTime_int_time
Source Code
   subroutine make_NetCDF_DateTime_int_time(interval, t0, tunit, int_time, unusable, rc)
      type(ESMF_TimeInterval), intent(inout) :: interval
      type(ESMF_Time), intent(inout) :: t0
      character(len=*), intent(in) :: tunit
      integer, intent(out) :: int_time
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      ! get int_time
      select case(lr_trim(tunit))
         case('years')
            call ESMF_TimeIntervalGet(interval, t0, yy=int_time, _RC)
         case('months')
            call ESMF_TimeIntervalGet(interval, t0, mm=int_time, _RC)
         case('hours')
            call ESMF_TimeIntervalGet(interval, t0, h=int_time, _RC)
         case('minutes')
            call ESMF_TimeIntervalGet(interval, t0, m=int_time, _RC)
         case('seconds')
            call ESMF_TimeIntervalGet(interval, t0, s=int_time, _RC)
         case default
            _FAIL('Unrecognized unit')
      end select
      _RETURN(_SUCCESS)
   end subroutine make_NetCDF_DateTime_int_time
Call graph
make_netcdf_datetime_int_time calls ESMF_TimeIntervalGet, mapl_assert, lr_trim, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_esmf_to_netcdf_datetime calls make_netcdf_datetime_int_time
test_make_netcdf_datetime_int_time calls make_netcdf_datetime_int_time
test_convert_esmf_to_netcdf_datetime calls convert_esmf_to_netcdf_datetime