make_tile_file_name – MAPL
make_tile_file_name Function
17 statements
Source File
private function make_tile_file_name(grid_name_1, grid_name_2, suffix, unusable, rc) result(name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: grid_name_1
character(len=*), intent(in) :: grid_name_2
character(len=*), intent(in) :: suffix
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Called by
Source Code
   function make_tile_file_name(grid_name_1, grid_name_2, suffix, unusable, rc) result(name)
      character(len=:), allocatable :: name
      character(len=*), intent(in) :: grid_name_1
      character(len=*), intent(in) :: grid_name_2
      character(len=*), intent(in) :: suffix
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(rc)
      name = grid_name_1 // '_' // grid_name_2 // suffix
   end function make_tile_file_name
Call graph
find_tile_file calls make_tile_file_name
initialize_subclass calls find_tile_file
initialize_base calls initialize
make_regridder_from_grids calls initialize
newlatlontolatlonregridder calls initialize