make_GathervKernel – MAPL
make_GathervKernel Function
17 statements
Source File
public function make_GathervKernel(spec, comm, rc) result(kernel)
Arguments
Type Intent Optional Attributes Name
type(GathervSpec), intent(in) :: spec
integer, intent(in) :: comm
integer, intent(out), optional :: rc
Return Value type(GathervKernel)
Calls
Called by
Source Code
   function make_GathervKernel(spec, comm, rc) result(kernel)
      type(GathervKernel) :: kernel
      type(GathervSpec), intent(in) :: spec
      integer, intent(in) :: comm
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: npes
      integer :: n
      call MPI_Comm_size(MPI_COMM_WORLD, npes, _IERROR)
      n = int(spec%nx,kind=INT64)**2 * 6 * spec%n_levs / npes
      kernel = GathervKernel(n, comm)
      call kernel%init(_RC)
      _RETURN(_SUCCESS)
   end function make_GathervKernel
Call graph
make_gathervkernel calls mpi_comm_size, init, mapl_return, mapl_verify
init calls mpi_comm_size, mapl_return, mapl_verify, mapl_assert, mpi_comm_rank
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
run calls make_gathervkernel
main calls run