make_subgrids_from_bounds – MAPL
make_subgrids_from_bounds Function
105 statements
Source File
private function make_subgrids_from_bounds(primary_grid, bounds, unusable, rc) result(subgrids)
Uses
MAPL_BaseMod
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: primary_grid
type(Interval), intent(in) :: bounds(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid), allocatable, (:)
Calls
Called by
Source Code
    function make_subgrids_from_bounds(primary_grid, bounds, unusable, rc) result(subgrids)
        use MAPL_BaseMod, only : MAPL_GridGetCorners
        type(ESMF_Grid), allocatable :: subgrids(:)
        type(ESMF_Grid), intent(inout) :: primary_grid ! inout to use MAPL_GridGetCorners
        type(Interval), intent(in) :: bounds(:)
        class(KeywordEnforcer), optional, intent(in) :: unusable
        integer, optional, intent(out) :: rc
        integer :: local_count(3), global_count(3)
        integer :: status
        integer :: petMap(1,1,1)
        integer :: myPet, section, i, j, k, count, size_
        type(ESMF_VM) :: vm
        real(kind=ESMF_KIND_R8), pointer :: new_lats(:,:), new_lons(:,:)
        real(kind=ESMF_KIND_R8), pointer :: lats(:,:), lons(:,:)
        real(kind=ESMF_KIND_R8), pointer :: new_corner_lats(:,:), new_corner_lons(:,:)
        real(kind=ESMF_KIND_R8), allocatable :: corner_lats(:,:), corner_lons(:,:)
        real(kind=ESMF_KIND_R8), allocatable :: lats1d(:), lons1d(:)
        character(len=ESMF_MAXSTR) :: name
        logical :: isPresent
        call ESMF_GridGet(primary_grid, name=name, _RC)
         !print*, 'Printing bounds for ', trim(name)
        !do i = 1, size(bounds)
        !   print*, trim(name), ',', i, ':', 'Bounds min:', bounds(i)%min, 'Bounds max:', bounds(i)%max
        !end do
        allocate(subgrids(size(bounds)))
        call MAPL_GridGet(primary_grid,localcellcountPerDim=local_count, globalCellCountPerDim=global_count, _RC)
        call ESMF_VMGetCurrent(vm, _RC)
        call ESMF_VMGet(vm, localPET=myPET, _RC)
        petMap(1,1,1) = myPet
        do i = 1, size(bounds)
           section = bounds(i)%max - bounds(i)%min + 1
           ! make each grid
           subgrids(i) = ESMF_GridCreateNoPeriDim( &
                countsPerDEDim1 = [local_count(1)], &
                countsPerDEDim2 = [section], &
                indexFlag=ESMF_INDEX_DELOCAL, &
                coordDep1=[1,2], &
                coordDep2=[1,2], &
                coordSys=ESMF_COORDSYS_SPH_RAD, &
                petMap = petMap, &
                name = name, &
                _RC)
           call ESMF_GridAddCoord(grid=subgrids(i), staggerloc=ESMF_STAGGERLOC_CENTER, _RC)
           call ESMF_AttributeCopy(primary_grid, subgrids(i), attcopy=ESMF_ATTCOPY_VALUE, _RC)
           ! delete corner lon/lat atttributes in the subgrid
           call ESMF_AttributeGet(subgrids(i), name='GridCornerLons:', isPresent=isPresent, _RC)
           if (isPresent) then
              call ESMF_AttributeRemove(subgrids(i), name='GridCornerLons:')
           end if
           call ESMF_AttributeGet(subgrids(i), name='GridCornerLats:', isPresent=isPresent, _RC)
           if (isPresent) then
              call ESMF_AttributeRemove(subgrids(i), name='GridCornerLats:')
           end if
        end do
        ! get lons/lats from original grid
        call ESMF_GridGetCoord(grid=primary_grid, coordDim=1, localDE=0, &
             staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lons, _RC)
        call ESMF_GridGetCoord(grid=primary_grid, coordDim=2, localDE=0, &
             staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lats, _RC)
        ! get corner lons/lats from original grid
        allocate(corner_lons(local_count(1)+1,local_count(2)+1))
        allocate(corner_lats(local_count(1)+1,local_count(2)+1))
        call MAPL_GridGetCorners(primary_grid, corner_lons, corner_lats, _RC)
        do i = 1, size(bounds)
           call ESMF_GridGetCoord(grid=subgrids(i), coordDim=1, localDE=0, &
                staggerloc=ESMF_STAGGERLOC_CENTER, &
                farrayPtr=new_lons, _RC)
           new_lons = subset_array(lons, bounds(i))
           call ESMF_GridGetCoord(grid=subgrids(i), coordDim=2, localDE=0, &
                staggerloc=ESMF_STAGGERLOC_CENTER, &
                farrayPtr=new_lats, _RC)
           new_lats = subset_array(lats, bounds(i))
           allocate(new_corner_lons(size(new_lons,1)+1,size(new_lons,2)+1))
           allocate(new_corner_lats(size(new_lats,1)+1,size(new_lats,2)+1))
           new_corner_lons = corner_lons(:,bounds(i)%min:bounds(i)%max+1)
           new_corner_lats = corner_lats(:,bounds(i)%min:bounds(i)%max+1)
           ! translate the 2d arrays into 1D arrays, lines 2462 to 2468 in base/Base/Base_implementation.F90
           size_ = size(new_corner_lons, 1) * size(new_corner_lons, 2)
           allocate(lons1d(size_))
           allocate(lats1d(size_))
           count = 0
           do k=1,size(new_corner_lons,2)
              do j=1,size(new_corner_lons,1)
                 count=count+1
                 lons1d(count)=new_corner_lons(j,k)
                 lats1d(count)=new_corner_lats(j,k)
              end do
           end do
           ! add the these arrays as attributes in the subgrids
           call ESMF_AttributeSet(subgrids(i), name='GridCornerLons:', &
                itemCount = count, valueList=lons1d, _RC)
           call ESMF_AttributeSet(subgrids(i), name='GridCornerLats:', &
                itemCount = count, valueList=lats1d, _RC)
           block
              integer :: global_grid_info(11)
              integer :: i1,i2,j1,j2
              call MAPL_Grid_Interior(primary_grid,i1,i2,j1,j2)
              global_grid_info(1:3) = global_count
              !global_grid_info(4:6) = local_count
              global_grid_info(4) = size(new_lons,1)
              global_grid_info(5) = size(new_lons,2)
              global_grid_info(6) = local_count(3)
              global_grid_info(7) = i1
              global_grid_info(8) = i2
              global_grid_info(9) = j1 + bounds(i)%min - 1
              global_grid_info(10) = j1 + bounds(i)%max - 1
              global_grid_info(11) = bounds(i)%min
              call ESMF_AttributeSet(subgrids(i), name="GLOBAL_GRID_INFO",  &
                   itemCount=11, valueList=global_grid_info, _RC)
           end block
            deallocate(lons1d, lats1d)
            deallocate(new_corner_lons, new_corner_lats)
        end do
        _RETURN(ESMF_SUCCESS)
        _UNUSED_DUMMY(unusable)
    end function make_subgrids_from_bounds
Call graph
make_subgrids_from_bounds calls ESMF_AttributeCopy, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, ESMF_GridAddCoord, ESMF_GridCreateNoPeriDim, ESMF_GridGet, ESMF_GridGetCoord, ESMF_VMGet, ESMF_VMGetCurrent, global_grid_info, mapl_grid_interior, mapl_gridgetcorners, mapl_gridget, mapl_return, mapl_verify, subset_array
mapl_grid_interior calls mapl_grid_interior
mapl_gridgetcorners calls mapl_gridgetcorners
mapl_gridget calls ESMF_AttributeGet, ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
make_subgrids calls make_subgrids_from_bounds, make_subgrids_from_num_grids
create_subobjects calls make_subgrids
make_subfields_from_num_grids calls make_subgrids
make_subgrids_from_num_grids calls make_subgrids
make_subfields calls make_subfields_from_num_grids
activate_threading calls create_subobjects
make_subfieldbundles_ordinary calls make_subfields
make_substates_from_num_grids calls make_subfields
omp_driver calls activate_threading