make_ESMF_TimeInterval – MAPL
make_ESMF_TimeInterval Subroutine
31 statements
Source File
public subroutine make_ESMF_TimeInterval(span, tunit, t0, interval, unusable, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: span
character(len=*), intent(in) :: tunit
type(ESMF_Time), intent(inout) :: t0
type(ESMF_TimeInterval), intent(inout) :: interval
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
make_ESMF_TimeInterval
Source Code
   subroutine make_ESMF_TimeInterval(span, tunit, t0, interval, unusable, rc)
      integer, intent(in) :: span
      character(len=*), intent(in) :: tunit
      type(ESMF_Time), intent(inout) :: t0
      type(ESMF_TimeInterval), intent(inout) :: interval
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      select case(lr_trim(tunit))
         case('years')
            call ESMF_TimeIntervalSet(interval, startTime=t0, yy=span, _RC)
         case('months')
            call ESMF_TimeIntervalSet(interval, startTime=t0, mm=span, _RC)
         case('hours')
            call ESMF_TimeIntervalSet(interval, startTime=t0, h=span, _RC)
         case('minutes')
            call ESMF_TimeIntervalSet(interval, startTime=t0, m=span, _RC)
         case('seconds')
            call ESMF_TimeIntervalSet(interval, startTime=t0, s=span, _RC)
         case default
            _FAIL('Unrecognized unit')
      end select
      _RETURN(_SUCCESS)
   end subroutine make_ESMF_TimeInterval
Call graph
make_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_assert, lr_trim, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_netcdf_datetime_to_esmf calls make_esmf_timeinterval
test_make_esmf_timeinterval calls make_esmf_timeinterval
test_convert_netcdf_datetime_to_esmf calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf, time_real_to_esmf