make_mpi_type_distributed_data – MAPL
make_mpi_type_distributed_data Subroutine
19 statements
Source File
private subroutine make_mpi_type_distributed_data(this, d, new_type, ierror)
Type Bound
DistributedMeter
Arguments
Type Intent Optional Attributes Name
class(DistributedMeter), intent(in) :: this
type(DistributedStatistics), intent(in) :: d
integer, intent(out) :: new_type
integer, intent(out) :: ierror
Calls
Source Code
   subroutine make_mpi_type_distributed_data(this, d, new_type, ierror)
      class (DistributedMeter), intent(in) :: this
      type (DistributedStatistics), intent(in) :: d ! used only for generic resolution
      integer, intent(out) :: new_type
      integer, intent(out) :: ierror
      integer(kind=MPI_ADDRESS_KIND) :: displacements(2)
      integer(kind=MPI_ADDRESS_KIND) :: lb, sz, sz2
      integer :: rc, status
      _UNUSED_DUMMY(d)
      call this%make_mpi_type(this%statistics%total, type_dist_real64, ierror)
      call this%make_mpi_type(this%statistics%num_cycles, type_dist_integer, ierror)
      call MPI_Type_get_extent_x(type_dist_real64, lb, sz, ierror)
      _VERIFY(ierror)
      displacements = [0_MPI_ADDRESS_KIND, 6*sz]
      call MPI_Type_create_struct(2, [6,1], displacements, [type_dist_real64, type_dist_integer], new_type, ierror)
      _VERIFY(ierror)
      call MPI_Type_get_extent_x(new_type, lb, sz2, ierror)
      _VERIFY(ierror)
   end subroutine make_mpi_type_distributed_data
Call graph
make_mpi_type_distributed_data calls mpi_type_create_struct, mpi_type_get_extent_x, make_mpi_type, mapl_verify
mapl_verify calls mapl_throw_exception
make_mpi_type_distributed_integer calls mpi_type_create_struct, mapl_verify
mapl_throw_exception calls initialize