make_clone – MAPL
make_clone Function
29 statements
Source File
private function make_clone(this, grid_type, unusable, rc) result(factory)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: grid_type
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(AbstractGridFactory), allocatable
Calls
Called by
Source Code
   function make_clone(this, grid_type, unusable, rc) result(factory)
      class (AbstractGridFactory), allocatable :: factory
      class (GridManager), intent(inout) :: this
      character(len=*), intent(in) :: grid_type
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class (AbstractGridFactory), pointer :: prototype
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_clone'
      ! This is a local variable to prevent the function from running
      ! initialiazation twice.
      logical, save :: initialized = .false.
      _UNUSED_DUMMY(unusable)
      ! Do not initialize prototypes more than once.
      if (.not. initialized) then
           call initialize_prototypes(this, _RC)
           initialized = .true.
      end if
      prototype => this%prototypes%at(grid_type)
      if (associated(prototype)) then
         allocate(factory, source=prototype%clone(), stat=status)
         _VERIFY(status)
      else
         _FAIL('prototype not found')
      end if
      _RETURN(_SUCCESS)
   end function make_clone
Call graph
make_clone calls mapl_assert, clone, initialize_prototypes, m_at, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
initialize_prototypes calls mapl_return, insert
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_insert_pair calls s_insert
s_find calls at, exists, find_index, s_ordereq
make_factory_from_config calls make_clone
make_factory_from_distgrid calls make_clone
make_factory_from_file calls make_clone
find calls make_factory
make_grid_from_config calls make_factory
make_grid_from_distgrid calls make_factory
mapl_esmfstatereadfromfile calls make_factory
time_ave calls make_factory
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
make_metadata calls find
makemetadata calls find
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundle calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadparallel_ calls find
mapl_create_bundle_from_metdata_id calls find
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_read_bundle calls find
mapl_staterefresh calls mapl_esmfstatereadfromfile
request_data_from_file calls find