make_NetCDF_DateTime_units_string – MAPL
make_NetCDF_DateTime_units_string Subroutine
16 statements
Source File
public subroutine make_NetCDF_DateTime_units_string(t0, tunit, units_string, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: t0
character(len=*), intent(in) :: tunit
character(len=:), intent(out), allocatable :: units_string
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
make_NetCDF_DateTime_units_string
Source Code
   subroutine make_NetCDF_DateTime_units_string(t0, tunit, units_string, unusable, rc)
      type(ESMF_Time), intent(inout) :: t0
      character(len=*), intent(in) :: tunit
      character(len=:), allocatable, intent(out) :: units_string
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: preposition = 'since'
      character(len=:), allocatable :: datetime_string
      integer :: status
      _UNUSED_DUMMY(unusable)
      ! make units_string
      call convert_ESMF_Time_to_NetCDF_DateTimeString(t0, datetime_string, _RC)
      units_string = tunit //SPACE// preposition //SPACE// datetime_string
      _RETURN(_SUCCESS)
   end subroutine make_NetCDF_DateTime_units_string
Call graph
make_netcdf_datetime_units_string calls convert_esmf_time_to_netcdf_datetimestring, mapl_return, mapl_verify
convert_esmf_time_to_netcdf_datetimestring calls mapl_return, mapl_verify, ESMF_TimeGet, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
convert_esmf_to_netcdf_datetime calls make_netcdf_datetime_units_string
test_make_netcdf_datetime_units_string calls make_netcdf_datetime_units_string
test_convert_esmf_to_netcdf_datetime calls convert_esmf_to_netcdf_datetime