make_regridder – MAPL
make_regridder Function
77 statements
Source File
private function make_regridder(esmfgrid, method, lons, lats, im, jm, lm, runparallel, LocalTiles, rc) result(regridder)
Uses
MAPL_AbstractRegridderMod
MAPL_RegridderManagerMod
MAPL_GridManagerMod
MAPL_AbstractGridFactoryMod
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: esmfgrid
integer, intent(in) :: method
real, intent(in) :: lons(:)
real, intent(in) :: lats(:)
integer, intent(in) :: im
integer, intent(in) :: jm
integer, intent(in) :: lm
logical, intent(in) :: runparallel
logical, intent(in), optional :: LocalTiles
integer, intent(out), optional :: rc
Return Value class(AbstractRegridder), pointer
Calls
Called by
Contents
Source Code
make_regridder
Source Code
  function make_regridder(esmfgrid, method, lons, lats, im,jm,lm, runparallel, LocalTiles, rc) result(regridder)
    use MAPL_AbstractGridFactoryMod
    use MAPL_AbstractRegridderMod
    use MAPL_GridManagerMod
    use MAPL_RegridderManagerMod
    class (AbstractRegridder), pointer :: regridder
    type (ESMF_Grid), intent(in) :: esmfgrid
    integer, intent(in) :: method
    real, intent(in) :: lons(:) ! degrees
    real, intent(in) :: lats(:) ! degrees
    integer, intent(in) :: im, jm, lm
    logical, intent(in) :: runparallel
    logical, optional, intent(in) :: LocalTiles
    integer, optional, intent(out) :: rc
    integer :: status
    type (ESMF_Grid) :: grid
    type (ESMF_DistGrid) :: dist_grid
    type (ESMF_LocalArray) :: lon_array, lat_array
    integer, allocatable :: krank(:)
    type (ESMF_DELayout) :: layout
    real, pointer :: lons_radians(:)
    real, pointer :: lats_radians(:)
    integer :: numNodes, k
    integer :: regrid_hints
    if (present(LocalTiles)) then
       if (localtiles) then
           regrid_hints=REGRID_HINT_LOCAL
       else
           regrid_hints=0
       end if
    else
       regrid_hints=REGRID_HINT_LOCAL
    end if
    if (LM > 0) then
      allocate(krank(LM),stat=status)
    else
      allocate(krank(1) ,stat=status)
    end if
    _VERIFY(status)
    if (runParallel .and. (LM > 0) ) then
      numNodes = size(MAPL_NodeRankList)
      call MAPL_RoundRobinPEList(krank,numNodes,rc=status)
      _VERIFY(STATUS)
    else
      krank = 0
    end if
    allocate(lons_radians(size(lons)))
    allocate(lats_radians(size(lats)))
    lons_radians = MAPL_DEGREES_TO_RADIANS_R8 * lons
    lats_radians = MAPL_DEGREES_TO_RADIANS_R8 * lats
    lon_array = ESMF_LocalArrayCreate(lons_radians, rc=status)
    _VERIFY(status)
    lat_array = ESMF_LocalArrayCreate(lats_radians, rc=status)
    _VERIFY(status)
    layout = ESMF_DELayoutCreate(petMap=krank, rc=status)
    _VERIFY(status)
    dist_grid = ESMF_DistGridCreate([1,1,1],[IM,JM,LM], &
         & deBlockList=reshape([([[1,1,k],[IM,JM,k]],k=1,LM)],[3,2,LM]), &
         & deLayout = layout, rc=status)
    _VERIFY(status)
    grid = grid_manager%make_grid('LatLon', dist_grid, lon_array, lat_array, rc=status)
    _VERIFY(status)
    call ESMF_DistGridDestroy(dist_grid, rc=status)
    _VERIFY(status)
    deallocate(lons_radians, lats_radians)
    call ESMF_LocalArrayDestroy(lon_array)
    _VERIFY(status)
    call ESMF_LocalArrayDestroy(lat_array)
    _VERIFY(status)
    if (method == REGRID_METHOD_CONSERVE .or. method == REGRID_METHOD_VOTE .or. &
        method == REGRID_METHOD_FRACTION) then
       regridder => regridder_manager%make_regridder(grid, ESMFGRID, &
            & method, hints=regrid_hints, rc=status)
       _VERIFY(status)
    else
       regridder => regridder_manager%make_regridder(grid, ESMFGRID, &
            & method, hints=regrid_hints, rc=status)
       _VERIFY(status)
    end if
    _RETURN(ESMF_SUCCESS)
  end function make_regridder
Call graph
make_regridder calls make_regridder, ESMF_DELayoutCreate, ESMF_DistGridCreate, ESMF_DistGridDestroy, esmf_localarraycreate, esmf_localarraydestroy, make_grid, mapl_return, mapl_roundrobinpelist, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_roundrobinpelist calls mapl_return, mapl_verify, mapl_getnewrank
mapl_verify calls mapl_throw_exception
mapl_getnewrank calls mapl_getnewrank, mapl_return, mapl_noderanklist
get_error_message calls at
mapl_throw_exception calls initialize
mapl_cfiocreatefrombundle calls make_regridder
mapl_cfiocreatefromfile calls make_regridder
mapl_cfioreadbundle calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls mapl_cfiocreatefromfile
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls mapl_cfioread, esmf_ioread, esmf_iocreate
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main