make_new_grid – MAPL
make_new_grid Function
29 statements
Source File
private function make_new_grid(this, unusable, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
class(ExternalGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Contents
Source Code
make_new_grid
Source Code
   function make_new_grid(this, unusable, rc) result(grid)
      type(ESMF_Grid) :: grid
      class(ExternalGridFactory),       intent(in   ) :: this
      class(KeywordEnforcer), optional, intent(in   ) :: unusable
      integer,                optional, intent(  out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME // 'make_grid'
      logical                     :: is_present
      integer                     :: status, lm
      _UNUSED_DUMMY(unusable)
      if (allocated(this%external_grid)) then
         grid = this%external_grid
      else
         _FAIL('grid not allocated')
      end if
      if (allocated(this%lm)) then
         call ESMF_AttributeGet(grid, name='GRID_LM', isPresent=is_present, rc=status)
         _VERIFY(status)
         if (is_present) then
            call ESMF_AttributeGet(grid, name='GRID_LM', value=lm, rc=status)
            _VERIFY(status)
            _ASSERT(lm == this%lm,'inconsistent levels')
         else
            call ESMF_AttributeSet(grid, name='GRID_LM', value=this%lm, rc=status)
            _VERIFY(status)
         end if
      end if
      _RETURN(_SUCCESS)
   end function make_new_grid
Call graph
make_new_grid calls mapl_assert, mapl_verify, esmf_attributeget, esmf_attributeset, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize