make_grid – MAPL
make_grid Function
32 statements
Source File
private function make_grid(this, unusable, force_new_grid, rc) result(grid)
Uses
MAPL_KeywordEnforcerMod
ESMF
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
class(AbstractGridFactory), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: force_new_grid
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
   function make_grid(this, unusable, force_new_grid, rc) result(grid)
      use esmf
      use MAPL_KeywordEnforcerMod
      type (ESMF_Grid) :: grid
      class (AbstractGridFactory), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in)  :: force_new_grid
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_grid'
      logical :: new_grid
      _UNUSED_DUMMY(unusable)
      new_grid = .false.
      if (present(force_new_grid)) new_grid = force_new_grid
      if (new_grid) then
         grid = this%make_new_grid(_RC)
      else
         if (allocated(this%grid)) then
            grid = this%grid
         else
            this%grid = this%make_new_grid(_RC)
            grid = this%grid
         end if
      end if
      _RETURN(_SUCCESS)
   end function make_grid
Call graph
make_grid calls make_new_grid, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_fake_latitudes calls make_grid
get_fake_longitudes calls make_grid
init_halo calls make_grid
make_grid_from_factory calls make_grid
mapl_extdatagridchangelev calls make_grid
setup calls make_grid
test_cartesian_to_spherical_x calls make_grid
test_cartesian_to_spherical_y calls make_grid
test_cartesian_to_spherical_z calls make_grid
test_spherical_to_cartesian_east_wind calls make_grid
test_spherical_to_cartesian_north_wind calls make_grid
append_metadata calls get_fake_latitudes, get_fake_longitudes
create_bracketing_fields calls mapl_extdatagridchangelev
initialize_from_config_with_prefix calls init_halo
run_ calls create_bracketing_fields