make_new_grid – MAPL
make_new_grid Function
13 statements
Source File
private function make_new_grid(this, unusable, rc) result(grid)
Type Bound
CubedSphereGridFactory
Arguments
Type Intent Optional Attributes Name
class(CubedSphereGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Contents
Source Code
make_new_grid
Source Code
   function make_new_grid(this, unusable, rc) result(grid)
      type (ESMF_Grid) :: grid
      class (CubedSphereGridFactory), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'make_grid'
      _UNUSED_DUMMY(unusable)
      grid = this%create_basic_grid(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function make_new_grid
Call graph
make_new_grid calls create_basic_grid, mapl_return, mapl_verify
create_basic_grid calls mapl_return, mapl_verify, ESMF_AttributeSet, ESMF_GridAddCoord, ESMF_GridCreateCubedSphere, ESMF_GridCreateNoPeriDim, ESMF_GridGetCoord, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception