make_GathervSpec – MAPL
make_GathervSpec Function
29 statements
Source File
public function make_GathervSpec(rc) result(spec)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Return Value type(GathervSpec)
Calls
Called by
Contents
Source Code
make_GathervSpec
Source Code
   function make_GathervSpec(rc) result(spec)
      type(GathervSpec) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      type(ArgParser) :: parser
      type(StringUnlimitedMap) :: options
      class(*), pointer :: option
      parser = ArgParser()
      call add_cli_options(parser)
      options = parser%parse_args()
      option => options%at('nx')
      _ASSERT(associated(option), 'nx not found')
      call cast(option, spec%nx, _RC)
      option => options%at('n_levs')
      _ASSERT(associated(option), 'n_levs not found')
      call cast(option, spec%n_levs, _RC)
      option => options%at('n_writers')
      _ASSERT(associated(option), 'n_writers not found')
      call cast(option, spec%n_writers, _RC)
      option => options%at('n_tries')
      _ASSERT(associated(option), 'n_tries not found')
      call cast(option, spec%n_tries, _RC)
      _RETURN(_SUCCESS)
   end function make_GathervSpec
Call graph
make_gathervspec calls argparser, at, cast, mapl_assert, parse_args, add_cli_options, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_cli_options calls add_argument
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
main calls make_gathervspec