make_filename – MAPL
make_filename Function
17 statements
Source File
private function make_filename(base, rank, width, rc) result(filename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: base
integer, intent(in) :: rank
integer, intent(in) :: width
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Contents
Source Code
make_filename
Source Code
   function make_filename(base, rank, width, rc) result(filename)
      character(:), allocatable :: filename
      character(*), intent(in) :: base
      integer, intent(in) :: rank
      integer, intent(in) :: width
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=width) :: suffix
      character(30) :: fmt
      write(fmt,'("(i",i0,".",i0,")")', iostat=status) width, width
      _VERIFY(status)
      write(suffix,trim(fmt), iostat=status) rank
      _VERIFY(status)
      filename = base // suffix
      _RETURN(_SUCCESS)
   end function make_filename
Call graph
make_filename calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
make_bw_benchmark calls make_filename
run calls make_bw_benchmark
time calls run
main calls run