make_cfio – MAPL
make_cfio Subroutine
7 statements
Source File
public subroutine make_cfio(this, rc)
Type Bound
ExtData_IoBundle
Arguments
Type Intent Optional Attributes Name
class(ExtData_IoBundle), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine make_cfio(this, rc)
    class (ExtData_IoBundle), intent(inout) :: this
    integer, optional, intent(out) :: rc
     this%cfio = MAPL_GriddedIO(output_bundle=this%pbundle,regrid_method=this%regrid_method, &
                        read_collection_id=this%server_coll_id, &
                        metadata_collection_id = this%metadata_coll_id, fraction = this%fraction, &
                        items=this%items)
     _RETURN(ESMF_SUCCESS)
   end subroutine make_cfio
Call graph
make_cfio calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_extdatacreatecfio calls make_cfio
run_ calls mapl_extdatacreatecfio