make_string_character – MAPL
make_string_character Function
8 statements
Source File
private function make_string_character(value_, slen) result(string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: value_
integer, intent(in) :: slen
Return Value character(len=slen)
Called by
Contents
Source Code
make_string_character
Source Code
   function make_string_character(value_, slen) result(string)
      character(len=*), intent(in) :: value_
      integer, intent(in) :: slen
      character(len=slen) :: string
      integer :: last
      last = min(slen, len(value_))
      string = value_(1:last)
   end function make_string_character
Call graph
mapl_getresource_config_scalar calls make_string_character
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_character calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int8 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_logical calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real8 calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_scalar
arrdescrsetncpar calls mapl_getresource
capture calls mapl_getresource
get_test_framework_resource calls mapl_getresource
initialize_gc calls mapl_getresource
mapl_clockinit calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource
mapl_esmfstatewritetofile calls mapl_getresource
mapl_genericfinalize calls mapl_getresource
mapl_genericinitialize calls mapl_getresource
mapl_genericrecord calls mapl_getresource
mapl_genericrefresh calls mapl_getresource
mapl_genericstaterestore calls mapl_getresource
mapl_genericstatesave calls mapl_getresource
mapl_genericwrapper calls mapl_getresource
mapl_staterecord calls mapl_getresource
mapl_staterefresh calls mapl_getresource