make_message – MAPL
make_message Function
8 statements
Source File
private function make_message(this, type_id) result(message)
Type Bound
ProtocolParser
Arguments
Type Intent Optional Attributes Name
class(ProtocolParser), intent(in) :: this
integer, intent(in) :: type_id
Return Value class(AbstractMessage), allocatable
Calls
Source Code
   function make_message(this, type_id) result(message)
      class (AbstractMessage), allocatable :: message
      class (ProtocolParser), intent(in) :: this
      integer, intent(in) :: type_id
      class (AbstractMessage), pointer :: prototype
      prototype => this%prototypes%at(type_id)
      allocate(message, source=prototype)
   end function make_message
Call graph
make_message calls m_at
m_at calls m_find
m_find calls s_find
s_find calls at, exists, find_index, s_ordereq