make_regridder_from_grids – MAPL
make_regridder_from_grids Function
87 statements
Source File
private function make_regridder_from_grids(this, grid_in, grid_out, regrid_method, unusable, hints, rc) result(regridder)
Type Bound
RegridderManager
Arguments
Type Intent Optional Attributes Name
class(RegridderManager), intent(inout) :: this
type(ESMF_Grid), intent(in) :: grid_in
type(ESMF_Grid), intent(in) :: grid_out
integer, intent(in) :: regrid_method
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: hints
integer, intent(out), optional :: rc
Return Value class(AbstractRegridder), pointer
Calls
Called by
Source Code
   function make_regridder_from_grids(this, grid_in, grid_out, regrid_method, unusable, hints, rc) result(regridder)
      class (AbstractRegridder), pointer :: regridder
      class (RegridderManager), intent(inout) :: this
      type (ESMF_Grid), intent(in) :: grid_in
      type (ESMF_Grid), intent(in) :: grid_out
      integer, intent(in) :: regrid_method
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: hints
      integer, optional,  intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_regridder_from_grids'
      type (RegridderSpec) :: spec
      integer (kind=ESMF_KIND_I8) :: id_in, id_out
      character(len=:), allocatable :: grid_type_in, grid_type_out
      type (RegridderTypeSpec) :: type_spec
      class (AbstractRegridder), pointer :: prototype
      !---------------
      ! Note:
      ! We need to add LatLon prototype somewhere, and MAPL does not have
      ! a natural initialization.  Other grids can be added during
      ! setServices or initialize of the component that defines the grid.
      !---------------
      _UNUSED_DUMMY(unusable)
      if (.not. this%initialized) then
        call this%init()
      end if
      ! Special case if two grids are the same
      id_in = get_factory_id(grid_in,rc=status)
      _VERIFY(status)
      id_out = get_factory_id(grid_out,rc=status)
      _VERIFY(status)
      if (id_in==id_out) then
         regridder => identity_regridder()
         _RETURN(_SUCCESS)
      end if
      ! If manager already has suitable regridder, use it.
      spec = RegridderSpec(grid_in, grid_out, regrid_method, hints=hints)
      regridder => find(this%regridders, spec)
      if (associated(regridder)) then
         _RETURN(_SUCCESS)
      end if
      ! Else, if we have a prototype, clone it and configure
      grid_type_in = get_grid_type(grid_in, rc=status)
      _VERIFY(status)
      grid_type_out = get_grid_type(grid_out, rc=status)
      _VERIFY(status)
      type_spec = RegridderTypeSpec(grid_type_in, grid_type_out, regrid_method)
      prototype => this%prototypes%at(type_spec)
      if (associated(prototype)) then
        call this%regridders%push_back(prototype%clone())
        regridder => this%regridders%back()
        call regridder%initialize(spec, rc=status)
        _VERIFY(status)
        _RETURN(_SUCCESS)
      end if
      print*,__FILE__,__LINE__,'I cannot create this regridder. types are <',&
           & grid_type_in,',',grid_type_out,'>'
      ! Do not know how to make this type of regridder
      _RETURN(_FAILURE)
   contains
      function find(vector, spec) result(match)
         class (AbstractRegridder), pointer :: match
         type (RegridderVector), intent(in) :: vector
         type (RegridderSpec), intent(in) :: spec
         type (RegridderVectorIterator) :: iter
         iter = vector%begin()
         do while (iter /= vector%end())
            match => iter%get()
            if (match%get_spec() == spec) return
           call iter%next()
        end do
        match => null()
      end function find
      function get_grid_type(grid, unusable, rc) result(grid_type)
         character(len=:), allocatable :: grid_type
         type (ESMF_Grid), intent(in) :: grid
         class (KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         integer :: status
         character(len=ESMF_MAXSTR) :: buffer
         call ESMF_AttributeGet(grid, 'GridType', buffer, rc=status)
         _VERIFY(status)
         grid_type = trim(buffer)
         _RETURN(_SUCCESS)
         _UNUSED_DUMMY(unusable)
      end function get_grid_type
   end function make_regridder_from_grids
Call graph
make_regridder_from_grids calls ESMF_AttributeGet, initialize, clone, get_factory_id, get_spec, identity_regridder, init, m_at, mapl_return, mapl_verify, v_back, v_begin, v_iter_get, v_iter_next, v_push_back
get_factory_id calls ESMF_AttributeGet, mapl_return, mapl_verify
identity_regridder calls get_spec, set_spec
init calls add_prototype
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls mapl_cfiocreatefromfile
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate