make_arbitrary_decomposition – MAPL
make_arbitrary_decomposition Subroutine
30 statements
Source File
private subroutine make_arbitrary_decomposition(nx, ny, unusable, reduceFactor, rc)
Uses
MAPL_KeywordEnforcerMod
ESMF
Type Bound
AbstractGridFactory
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: nx
integer, intent(out) :: ny
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: reduceFactor
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine make_arbitrary_decomposition(nx, ny, unusable, reduceFactor, rc)
      use ESMF
      use MAPL_KeywordEnforcerMod
      integer, intent(out) :: nx
      integer, intent(out) :: ny
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: reduceFactor
      integer, optional, intent(out) :: rc
      type (ESMF_VM) :: vm
      integer :: pet_count
      character(len=*), parameter :: Iam= MOD_NAME // 'make_arbitrary_decomposition()'
      integer :: status
      _UNUSED_DUMMY(unusable)
      call ESMF_VMGetCurrent(vm, rc=status)
      _VERIFY(status)
      call ESMF_VMGet(vm, petCount=pet_count, rc=status)
      _VERIFY(status)
      if (present(reduceFactor)) pet_count=pet_count/reduceFactor
      ! count down from sqrt(n)
      ! Note: inal iteration (nx=1) is guaranteed to succeed.
      do nx = floor(sqrt(real(2*pet_count))), 1, -1
         if (mod(pet_count, nx) == 0) then ! found a decomposition
            ny = pet_count / nx
            exit
         end if
      end do
      _RETURN(_SUCCESS)
   end subroutine make_arbitrary_decomposition
Call graph
make_arbitrary_decomposition calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_from_file_metadata calls make_arbitrary_decomposition
test_make_arbitrary_decomposition calls make_arbitrary_decomposition