make_mpi_type_distributed_integer – MAPL
make_mpi_type_distributed_integer Subroutine
17 statements
Source File
private subroutine make_mpi_type_distributed_integer(this, int, new_type, ierror)
Type Bound
DistributedMeter
Arguments
Type Intent Optional Attributes Name
class(DistributedMeter), intent(in) :: this
type(DistributedInteger), intent(in) :: int
integer, intent(out) :: new_type
integer, intent(out) :: ierror
Calls
Called by
Source Code
   subroutine make_mpi_type_distributed_integer(this, int, new_type, ierror)
      class (DistributedMeter), intent(in) :: this
      type (DistributedInteger), intent(in) :: int ! used only for generic resolution
      integer, intent(out) :: new_type
      integer, intent(out) :: ierror
      integer(kind=MPI_ADDRESS_KIND) :: displacements(1)
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(int)
      displacements = [0_MPI_ADDRESS_KIND]
      call MPI_Type_create_struct(1, [6], displacements, [MPI_INTEGER], new_type, ierror)
   end subroutine make_mpi_type_distributed_integer
Call graph
make_mpi_type_distributed_integer calls mpi_type_create_struct
initialize calls make_mpi_type
make_mpi_type_distributed_data calls make_mpi_type
new_distributedmeter calls initialize
distributedmeter calls new_distributedmeter