make_grid_from_distGrid – MAPL
make_grid_from_distGrid Function
26 statements
Source File
private function make_grid_from_distGrid(this, grid_type, dist_grid, lon_array, lat_array, unusable, rc) result(grid)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: grid_type
type(ESMF_DistGrid), intent(in) :: dist_grid
type(ESMF_LocalArray), intent(in) :: lon_array
type(ESMF_LocalArray), intent(in) :: lat_array
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
   function make_grid_from_distGrid(this, grid_type, dist_grid, lon_array, lat_array, unusable, rc) result(grid)
      use ESMF
      type (ESMF_Grid) :: grid
      class (GridManager), intent(inout) :: this
      character(len=*), intent(in) :: grid_type
      type (ESMF_DistGrid), intent(in) :: dist_grid
      type (ESMF_LocalArray), intent(in) :: lon_array
      type (ESMF_LocalArray), intent(in) :: lat_array
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional,  intent(out) :: rc
      class (AbstractGridFactory), allocatable :: factory
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_grid_from_distGrid'
      _UNUSED_DUMMY(unusable)
      allocate(factory, source=this%make_factory(grid_type, dist_grid, lon_array, lat_array, rc=status))
      _VERIFY(status)
      grid = this%make_grid(factory, rc=status)
      _VERIFY(status)
      ! TLC: Using 'GridType' instead of 'GRID_TYPE' for legacy reasons.
      call ESMF_AttributeSet(grid, 'GridType', grid_type, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function make_grid_from_distGrid
Call graph
make_grid_from_distgrid calls ESMF_AttributeSet, make_factory, make_grid, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_factory_from_distgrid calls mapl_return, mapl_verify, initialize, make_clone
mapl_throw_exception calls initialize
make_clone calls mapl_return, mapl_verify, mapl_assert, clone, initialize_prototypes, m_at
addgrid calls make_grid
create_grid calls make_grid
create_output_grid calls make_grid
find calls make_grid
initialize calls make_grid
make_grid_from_config calls make_grid
make_regridder calls make_grid
mapl_extdatagridchangelev calls make_grid
mapl_gridcreate calls make_grid
run_component_driver calls make_grid
set_grid calls make_grid
test_grid_type calls make_grid
test_make_grid_multi calls make_grid
test_make_grid_no_prototype calls make_grid
test_make_grid_prototype calls make_grid
time_ave calls make_grid
ut_regridding calls make_grid