make_substates_from_num_grids – MAPL
make_substates_from_num_grids Function
71 statements
Source File
private recursive function make_substates_from_num_grids(state, num_subgrids, unusable, rc) result(substates)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
integer, intent(in) :: num_subgrids
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_State), allocatable, (:)
Calls
Called by
Contents
Source Code
make_substates_from_num_grids
Source Code
    recursive function make_substates_from_num_grids(state, num_subgrids, unusable, rc) result(substates)
      type(ESMF_State), allocatable :: substates(:)
      type(ESMF_State), intent(inout) :: state
      integer, intent(in) :: num_subgrids
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=ESMF_MAXSTR) :: name
      integer :: count, status, i, j
      character(len=ESMF_MAXSTR), allocatable :: item_names(:)
      type(ESMF_StateItem_Flag), allocatable :: item_types(:)
      type(ESMF_Field), allocatable :: subfields(:)
      type(ESMF_FieldBundle), allocatable :: sub_bundles(:)
      type(ESMF_State), allocatable :: sub_nested_states(:)
      type(ESMF_Field) :: field
      type(ESMF_FieldBundle) :: bundle
      type(ESMF_State) :: nested_state
      type (ESMF_FieldStatus_Flag) :: fieldStatus
      allocate(substates(num_subgrids))
      ! get information about state contents in order they were added
      call ESMF_StateGet(state, itemCount=count, name=name, _RC)
      allocate(item_names(count))
      allocate(item_types(count))
      call ESMF_StateGet(state, itemOrderFlag=ESMF_ITEMORDER_ADDORDER, itemNameList=item_names, &
           itemTypeList=item_types,  _RC)
      do i = 1, num_subgrids
         substates(i) = ESMF_StateCreate(name=name, _RC)
         call ESMF_AttributeCopy(state, substates(i), attcopy=ESMF_ATTCOPY_VALUE, _RC)
      end do
      do i = 1, count
         if (item_types(i) == ESMF_STATEITEM_FIELD) then
            call ESMF_StateGet(state, item_names(i), field, _RC)
            call ESMF_FieldGet(field, status=fieldStatus, _RC)
            if (fieldStatus /= ESMF_FIELDSTATUS_COMPLETE) then
               subfields = spread(field, dim=1, ncopies=num_subgrids)
            else
               subfields = make_subfields(field, num_subgrids, _RC)
            end if
            ! add subfields to appropriate substate
            do j = 1, size(subfields)
               call ESMF_StateAdd(substates(j), subfields(j:j), _RC)
            end do
         else if (item_types(i) == ESMF_STATEITEM_FIELDBUNDLE) then
            call ESMF_StateGet(state, item_names(i), bundle, _RC)
            sub_bundles = make_subFieldBundles(bundle, num_subgrids, _RC)
            ! add sub_bundles to appropriate substate
            do j = 1, size(sub_bundles)
                call ESMF_StateAdd(substates(j), sub_bundles(j:j), _RC)
            end do
         else if (item_types(i) == ESMF_STATEITEM_STATE) then
            call ESMF_StateGet(state, item_names(i), nested_state, _RC)
            sub_nested_states = make_substates(nested_state, num_subgrids, _RC)
            ! add the nested substates to appropriate larger substate
            do j = 1, size(sub_nested_states)
               call ESMF_StateAdd(substates(j), sub_nested_states(j:j), _RC)
            end do
         end if
      end do
      call copy_callbacks(state, substates, _RC)
      _RETURN(0)
    end function make_substates_from_num_grids
Call graph
make_substates_from_num_grids calls esmf_stateget, esmf_statecreate, mapl_verify, esmf_fieldget, esmf_attributecopy, make_subfields, esmf_stateadd, make_subfieldbundles, make_substates, copy_callbacks, mapl_return
mapl_verify calls mapl_throw_exception
make_subfields calls make_subfields_from_num_grids
make_subfieldbundles calls make_subfieldbundles_ordinary
make_substates calls make_substates_from_num_grids
copy_callbacks calls mapl_verify, mapl_return, get_callbacks, mapl_assert, esmf_methodadd
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_callbacks calls mapl_verify, mapl_return, esmf_attributeget, esmf_attributeset
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_subfields_from_num_grids calls mapl_verify, esmf_fieldget, esmf_attributecopy, mapl_return, make_subgrids, mapl_gridget, find_bounds, esmf_fieldcreate
make_subfieldbundles_ordinary calls mapl_verify, esmf_attributecopy, make_subfields, mapl_return, esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_fieldbundleadd
create_subobjects calls make_substates