make_factory_from_file – MAPL
make_factory_from_file Function
102 statements
Source File
private function make_factory_from_file(this, file_name, unused, force_file_coordinates, rc) result(factory)
Uses
pFIO
$ elseif (…) then ! something that is true for tripolar? $ factory = this%make_clone(‘tripolar’)
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: file_name
class(KeywordEnforcer), intent(in), optional :: unused
logical, intent(in), optional :: force_file_coordinates
integer, intent(out), optional :: rc
Return Value class(AbstractGridFactory), allocatable
Calls
Source Code
   function make_factory_from_file(this, file_name, unused, force_file_coordinates, rc) result(factory)
      use pFIO
      class (AbstractGridFactory), allocatable :: factory
      class (GridManager), intent(inout) :: this
      character(*), intent(in) :: file_name
      class (KeywordEnforcer), optional, intent(in) :: unused
      logical, optional, intent(in) :: force_file_coordinates
      integer, optional, intent(out) :: rc
      type (FileMetadata) :: file_metadata
      type (NetCDF4_FileFormatter) :: file_formatter
      integer :: im, jm
      character(len=*), parameter :: Iam= MOD_NAME // 'make_factory_from_file()'
      integer :: status
      class (Attribute), pointer :: attr
      class(*), pointer :: attr_value
      character(len=:), pointer :: grid_type
      type (ESMF_VM) :: vm
      integer :: pet
      logical :: hasXdim      = .FALSE.
      logical :: hasLon       = .FALSE.
      logical :: hasLongitude = .FALSE.
      logical :: hasLat       = .FALSE.
      logical :: hasLatitude  = .FALSE.
      logical :: SplitCubedSphere  = .FALSE.
      _UNUSED_DUMMY(unused)
      call ESMF_VMGetCurrent(vm, rc=status)
      _VERIFY(status)
      call ESMF_VMGet(vm, localPet=pet, rc=status)
      _VERIFY(status)
      call file_formatter%open(file_name, PFIO_READ, rc=status)
      _VERIFY(status)
      file_metadata = file_formatter%read(rc=status)
      _VERIFY(status)
      call file_formatter%close(rc=status)
      _VERIFY(status)
      SplitCubedSphere = file_metadata%has_attribute("Split_Cubed_Sphere")
      im = 0
      hasXdim = file_metadata%has_dimension('Xdim')
      if (hasXdim) then
         im = file_metadata%get_dimension('Xdim',rc=status)
         _VERIFY(status)
      end if
      hasLon = file_metadata%has_dimension('lon')
      if (hasLon) then
         im = file_metadata%get_dimension('lon', rc=status)
         _VERIFY(status)
      else
         hasLongitude = file_metadata%has_dimension('longitude')
         if (hasLongitude) then
             im = file_metadata%get_dimension('longitude', rc=status)
             _VERIFY(status)
         end if
      end if
      if (file_metadata%has_attribute('grid_type')) then
         attr => file_metadata%get_attribute('grid_type')
         attr_value => attr%get_value()
         select type (attr_value)
         type is (character(*))
            grid_type => attr_value
         class default
            _FAIL("grid_type attribute must be stringwrap")
         end select
         allocate(factory,source=this%make_clone(grid_type))
      else if (hasXdim) then
         im = file_metadata%get_dimension('Xdim',rc=status)
         if (status == _SUCCESS) then
            jm = file_metadata%get_dimension('Ydim',rc=status)
            _VERIFY(status)
            if (jm == 6*im .or. SplitCubedSphere) then
               allocate(factory, source=this%make_clone('Cubed-Sphere'))
            else
               if (file_metadata%has_dimension('nf')) then
                  allocate(factory, source=this%make_clone('Cubed-Sphere'))
               end if
            end if
         end if
      else if (hasLon .or. hasLongitude) then
         hasLat = file_metadata%has_dimension('lat')
         if (hasLat) then
            jm = file_metadata%get_dimension('lat', rc=status)
            _VERIFY(status)
         else
            hasLatitude = file_metadata%has_dimension('latitude')
            if (hasLatitude) then
               jm = file_metadata%get_dimension('latitude', rc=status)
               _VERIFY(status)
            end if
         end if
         if (jm == 6*im .or. SplitCubedSphere) then ! old-format cubed-sphere
            allocate(factory, source=this%make_clone('Cubed-Sphere'))
!!$        elseif (...) then ! something that is true for tripolar?
!!$           factory = this%make_clone('tripolar')
         else
            allocate(factory, source=this%make_clone('LatLon'))
        end if
     end if
     call factory%initialize(file_metadata, force_file_coordinates=force_file_coordinates, rc=status)
     _VERIFY(status)
     _RETURN(_SUCCESS)
   end function make_factory_from_file
Call graph
make_factory_from_file calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_assert, initialize, get_attribute, get_dimension, get_value, has_attribute, has_dimension, make_clone, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_attribute calls mapl_assert, mapl_return, get_attribute, m_at
get_dimension calls mapl_return, at, find
get_value calls mapl_return
has_attribute calls is_attribute_present
has_dimension calls mapl_return, find
make_clone calls mapl_assert, mapl_return, mapl_verify, clone, initialize_prototypes, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
initialize_from_esmf_distgrid calls mapl_assert
initialize_prototypes calls mapl_return, insert
is_attribute_present calls mapl_return, m_at
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize