make_new_grid – MAPL
make_new_grid Function
25 statements
Source File
private function make_new_grid(this, unusable, rc) result(grid)
Type Bound
XYGridFactory
Arguments
Type Intent Optional Attributes Name
class(XYGridFactory), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Source Code
   function make_new_grid(this, unusable, rc) result(grid)
      type (ESMF_Grid) :: grid
      class (XYGridFactory), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'make_geos_grid'
      _UNUSED_DUMMY(unusable)
      grid = this%create_basic_grid(_RC)
      if ( index(trim(adjustl(this%grid_name)), 'ABI') == 0 ) then
         call this%add_horz_coordinates_from_file(grid, _RC)
      else
         call this%add_horz_coordinates_from_ABIfile(grid, _RC)
      end if
      call this%add_mask(grid,_RC)
      _RETURN(_SUCCESS)
   end function make_new_grid
Call graph
make_new_grid calls add_horz_coordinates_from_abifile, add_horz_coordinates_from_file, add_mask, create_basic_grid, mapl_return, mapl_verify
add_horz_coordinates_from_abifile calls mapl_return, mapl_verify, ESMF_GridGetCoord, ESMF_VMGetCurrent, mapl_allocateshared, mapl_am_i_root, mapl_bcastshared, mapl_deallocnodearray, mapl_grid_interior, mapl_syncsharedmemory, abi_xy_2_lonlat, get_att_real_netcdf, get_v1d_netcdf_r8_complete
add_horz_coordinates_from_file calls mapl_return, mapl_verify, ESMF_GridGetCoord, mapl_allocateshared, mapl_deallocnodearray, mapl_grid_interior, mapl_syncsharedmemory, nf90_close, nf90_get_var, nf90_inq_varid, nf90_open, mapl_gridget
add_mask calls mapl_return, mapl_verify, ESMF_AttributeSet, ESMF_GridAddItem, ESMF_GridGetCoord, ESMF_GridGetItem, ESMF_VMAllFullReduce, ESMF_VMGetCurrent
create_basic_grid calls mapl_return, mapl_verify, ESMF_AttributeSet, ESMF_GridAddCoord, ESMF_GridCreateNoPeriDim
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception