make_factory_from_config – MAPL
make_factory_from_config Function
22 statements
Source File
private function make_factory_from_config(this, grid_type, config, unusable, prefix, rc) result(factory)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: grid_type
type(ESMF_Config), intent(inout) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: prefix
integer, intent(out), optional :: rc
Return Value class(AbstractGridFactory), allocatable
Calls
Source Code
   function make_factory_from_config(this, grid_type, config, unusable, prefix, rc) result(factory)
      use ESMF
      class (AbstractGridFactory), allocatable :: factory
      class (GridManager), intent(inout) :: this
      character(len=*), intent(in) :: grid_type
      type (ESMF_Config), intent(inout) :: config
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: prefix
      integer, optional,  intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_factory_from_config'
      _UNUSED_DUMMY(unusable)
      allocate(factory, source=this%make_clone(trim(grid_type), rc=status))
      _VERIFY(status)
      call factory%initialize(config, prefix=prefix, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function make_factory_from_config
Call graph
make_factory_from_config calls initialize, make_clone, mapl_return, mapl_verify
make_clone calls mapl_return, mapl_verify, mapl_assert, clone, initialize_prototypes, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
initialize_from_esmf_distgrid calls mapl_assert
initialize_prototypes calls mapl_return, insert
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception