make_factory_from_distGrid – MAPL
make_factory_from_distGrid Function
23 statements
Source File
private function make_factory_from_distGrid(this, grid_type, dist_grid, lon_array, lat_array, unusable, rc) result(factory)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout) :: this
character(len=*), intent(in) :: grid_type
type(ESMF_DistGrid), intent(in) :: dist_grid
type(ESMF_LocalArray), intent(in) :: lon_array
type(ESMF_LocalArray), intent(in) :: lat_array
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value class(AbstractGridFactory), allocatable
Calls
Called by
Source Code
   function make_factory_from_distGrid(this, grid_type, dist_grid, lon_array, lat_array, unusable, rc) result(factory)
      use ESMF
      class (AbstractGridFactory), allocatable :: factory
      class (GridManager), intent(inout) :: this
      character(len=*), intent(in) :: grid_type
      type (ESMF_DistGrid), intent(in) :: dist_grid
      type (ESMF_LocalArray), intent(in) :: lon_array
      type (ESMF_LocalArray), intent(in) :: lat_array
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional,  intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_factory_from_distGrid'
      _UNUSED_DUMMY(unusable)
      allocate(factory, source=this%make_clone(trim(grid_type), rc=status))
      _VERIFY(status)
      call factory%initialize(dist_grid, lon_array, lat_array, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function make_factory_from_distGrid
Call graph
make_factory_from_distgrid calls initialize, make_clone, mapl_return, mapl_verify
make_clone calls mapl_return, mapl_verify, mapl_assert, clone, initialize_prototypes, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
initialize_from_esmf_distgrid calls mapl_assert
initialize_prototypes calls mapl_return, insert
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
find calls make_factory
make_grid_from_config calls make_factory
make_grid_from_distgrid calls make_factory
mapl_esmfstatereadfromfile calls make_factory
time_ave calls make_factory
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
make_metadata calls find
makemetadata calls find
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundle calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadparallel_ calls find
mapl_create_bundle_from_metdata_id calls find
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_read_bundle calls find
mapl_staterefresh calls mapl_esmfstatereadfromfile
request_data_from_file calls find