make_grid_from_factory – MAPL
make_grid_from_factory Function
24 statements
Source File
private function make_grid_from_factory(this, factory, unusable, rc) result(grid)
Uses
ESMF
Type Bound
GridManager
Arguments
Type Intent Optional Attributes Name
class(GridManager), intent(inout), target :: this
class(AbstractGridFactory), intent(in) :: factory
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Source Code
   function make_grid_from_factory(this, factory, unusable, rc) result(grid)
      use ESMF
      type (ESMF_Grid) :: grid
      class (GridManager), target, intent(inout) :: this
      class (AbstractGridFactory), intent(in) :: factory
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional,  intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam= MOD_NAME // 'make_grid'
      integer(kind=INT64) :: factory_id
      class (AbstractGridFactory), pointer :: f
      _UNUSED_DUMMY(unusable)
      call this%add_factory(factory, factory_id)
      f => this%factories%at(factory_id)
      grid = f%make_grid(rc=status)
      _VERIFY(status)
      ! TODO: this should only be done if the grid is new, rather than cached, in which case
      ! the attribute is already set.
      call ESMF_AttributeSet(grid, factory_id_attribute, factory_id, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function make_grid_from_factory
Call graph
make_grid_from_factory calls ESMF_AttributeSet, add_factory, m_at, make_grid, mapl_return, mapl_verify
add_factory calls insert, m_begin, m_key, m_next
m_at calls m_find
make_grid calls mapl_return, mapl_verify, make_new_grid
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_begin calls s_begin
m_find calls s_find
m_next calls s_next
mapl_throw_exception calls initialize
m_insert_pair calls s_insert
s_begin calls s_next
s_find calls at, exists, find_index, s_ordereq
s_next calls advpos