map_iter_of – MAPL
map_iter_of Function
5 statements
Source File
private function map_iter_of(this) result(p)
Type Bound
CallbackMapIterator
Arguments
Type Intent Optional Attributes Name
class(CallbackMapIterator), intent(in), target :: this
Return Value type(CallbackPair), pointer
Calls
Called by
Call graph
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
map_find_if calls map_iter_of
map_find_if_not calls map_iter_of
map_iter_first calls map_iter_of
map_iter_second calls map_iter_of
find_if_not calls map_find_if_not
find_if calls map_find_if
copy_callbacks calls map_iter_first
make_substates_from_num_grids calls copy_callbacks
make_substates calls make_substates_from_num_grids