map_s_has_child – MAPL
map_s_has_child Function
6 statements
Source File
private function map_s_has_child(this, side) result(has_child)
Type Bound
map_s_Node
Arguments
Type Intent Optional Attributes Name
class(map_s_Node), intent(in) :: this
integer, intent(in) :: side
Return Value logical
Called by
Call graph
map_s_erase_range calls map_s_has_child, map_s_rebalance, map_s_erase_nonleaf
map_s_rebalance calls map_s_has_child
map_s_verify calls map_s_has_child
map_s_erase_nonleaf calls map_s_rebalance
map_s_insert_single calls map_s_rebalance
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_erase_value calls erase
map_s_merge calls erase