map_s_find_if_not – MAPL
map_s_find_if_not Function
18 statements
Source File
private function map_s_find_if_not(first, last, q) result(it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: first
type(map_SetIterator), intent(in) :: last
private function q(item)
Arguments
Type Intent Optional Attributes Name
type(CallbackPair), intent(in) :: item
Return Value logical
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_find_if_not calls map_s_iter_next, map_s_iter_of
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
find_if_not calls map_s_find_if_not