map_new_map_empty – MAPL
map_new_map_empty Function
4 statements
Source File
private function map_new_map_empty() result(m)
Arguments
None
Return Value type(CallbackMap)
Calls
Called by
Contents
None
Call graph
map_new_map_empty calls map_set
map_set calls map_s_new_set_empty, map_s_new_set_initializer_list, map_s_new_set_copy
callbackmap calls map_new_map_empty, map_new_map_initializer_list
map_new_map_initializer_list calls callbackmap