map_iter_first – MAPL
map_iter_first Function
11 statements
Source File
private function map_iter_first(this) result(first)
Type Bound
CallbackMapIterator
Arguments
Type Intent Optional Attributes Name
class(CallbackMapIterator), intent(in), target :: this
Return Value character(len=:), pointer
Calls
Called by
Call graph
map_iter_first calls map_iter_of
map_iter_of calls map_s_iter_of
map_s_iter_of calls map_s_get_value
copy_callbacks calls map_iter_first
make_substates_from_num_grids calls copy_callbacks, make_substates
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates