map_iter_next – MAPL
map_iter_next Subroutine
4 statements
Source File
private recursive subroutine map_iter_next(this)
Type Bound
CallbackMapIterator
Arguments
Type Intent Optional Attributes Name
class(CallbackMapIterator), intent(inout) :: this
Calls
Called by
Call graph
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
copy_callbacks calls map_iter_next
map_find_if calls map_iter_next
map_find_if_not calls map_iter_next
map_iter_advance_default calls map_iter_next
map_iter_advance_size_kind calls map_iter_next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
advance calls map_iter_advance_default, map_iter_advance_size_kind
find_if_not calls map_find_if_not
find_if calls map_find_if
next calls map_iter_next_n_default, map_iter_next_n_size_kind, map_iter_next_1, map_s_iter_next_1
make_substates_from_num_grids calls copy_callbacks, make_substates
make_substates calls make_substates_from_num_grids
map_iter_next_1 calls next
map_s_ftn_end calls next
map_s_iter_next_1 calls next
create_subobjects calls make_substates
map_ftn_end calls map_s_ftn_end
map_s_iter_ftn_end calls map_s_ftn_end