map_s_merge – MAPL
map_s_merge Subroutine
14 statements
Source File
private recursive subroutine map_s_merge(this, source)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout) :: this
type(map_Set), intent(inout), target :: source
Calls
Call graph
map_s_merge calls erase, insert, map_s_begin, map_s_iter_next, map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
map_s_erase_iter calls erase, map_s_iter_next
map_s_erase_range calls map_s_iter_next, map_s_deallocate_child, map_s_erase_nonleaf, map_s_get_parent, map_s_has_child, map_s_rebalance, map_s_which_child
map_s_erase_value calls erase, map_s_find
map_s_insert_initializer_list calls insert
map_s_erase_nonleaf calls map_s_advpos, map_s_get_child, map_s_rebalance, map_s_which_side_am_i, set_parent
map_s_find calls map_s_get_value, map_s_find_node, map_s_order_eq
map_s_rebalance calls map_s_get_child, map_s_has_child, get_height, map_s_rot, map_s_update_height
map_s_which_child calls map_s_get_child