map_s_iter_prev_n_size_kind – MAPL
map_s_iter_prev_n_size_kind Function
11 statements
Source File
private function map_s_iter_prev_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(map_SetIterator)
Calls
Called by
Contents
Call graph
map_s_iter_prev_n_size_kind calls prev
prev calls map_iter_prev_1, map_iter_prev_n_default, map_iter_prev_n_size_kind, map_s_iter_prev_n_size_kind
map_iter_prev_1 calls prev
map_iter_prev_n_default calls prev
map_iter_prev_n_size_kind calls prev