map_s_insert_single – MAPL
map_s_insert_single Subroutine
53 statements
Source File
private recursive subroutine map_s_insert_single(this, value, unused, is_new, iter)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout), target :: this
type(CallbackPair), intent(in) :: value
type(KeywordEnforcer), optional :: unused
logical, intent(out), optional :: is_new
type(map_SetIterator), intent(out), optional :: iter
Calls
Call graph
map_s_insert_single calls map_key_less_than, map_s_find_node, map_s_get_value, map_s_order_eq, map_s_rebalance, map_s_set_child, map_s_set_parent, map_s_set_value, to_node
map_s_find_node calls map_s_get_value, map_s_order_eq, to_node, map_s_get_child, map_s_lessthan
map_s_order_eq calls map_s_lessthan
map_s_rebalance calls get_height, map_s_get_child, map_s_has_child, map_s_rot, map_s_update_height
map_s_lessthan calls map_key_less_than
map_s_rot calls map_s_set_parent, map_s_get_child, map_s_update_height, map_s_which_side_am_i
map_s_update_height calls get_height
map_s_which_side_am_i calls map_s_get_parent, map_s_which_child