map_iter_advance_size_kind – MAPL
map_iter_advance_size_kind Subroutine
9 statements
Source File
private subroutine map_iter_advance_size_kind(it, n)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(inout) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Calls
Called by
Call graph
map_iter_advance_size_kind calls map_iter_next
map_iter_next calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
advance calls map_iter_advance_size_kind