map_s_iter_next_1 – MAPL
map_s_iter_next_1 Function
6 statements
Source File
private function map_s_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_iter_next_1 calls next
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind, map_s_iter_next_1
map_iter_next_1 calls next
map_iter_next_n_default calls map_iter_next
map_iter_next_n_size_kind calls map_iter_next
map_iter_next calls map_s_iter_next