map_iter_next_n_size_kind – MAPL
map_iter_next_n_size_kind Function
11 statements
Source File
private function map_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(CallbackMapIterator)
Calls
Called by
Contents
Call graph
map_iter_next_n_size_kind calls next
next calls map_iter_next_n_size_kind, map_iter_next_1, map_iter_next_n_default
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_find_if calls next
map_find_if_not calls next
map_iter_advance_default calls next
map_iter_advance_size_kind calls next
map_s_begin calls next
map_s_deep_copy calls next
map_s_equal calls next
map_s_erase_iter calls next
map_s_erase_range calls next
map_s_find_if calls next
map_s_find_if_not calls next
map_s_ftn_end calls next
map_s_insert_range calls next
map_s_iter_advance_default calls next
map_s_iter_advance_size_kind calls next
map_s_iter_next_1 calls next
map_s_iter_next_n_default calls next
map_s_iter_next_n_size_kind calls next
map_s_less_than calls next
map_s_lower_bound calls next
map_s_merge calls next
map_s_upper_bound calls next
map_s_verify calls next