map_s_iter_next_n_size_kind – MAPL
map_s_iter_next_n_size_kind Function
11 statements
Source File
private function map_s_iter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(map_SetIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_iter_next_n_size_kind calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
next calls map_s_iter_next_n_size_kind