map_s_count – MAPL
map_s_count Function
12 statements
Source File
private function map_s_count(this, value) result(count)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(in), target :: this
type(CallbackPair), intent(in) :: value
Return Value integer(kind=GFTL_SIZE_KIND)
Calls
Call graph
map_s_count calls map_s_find
map_s_find calls map_s_find_node, map_s_get_value, map_s_order_eq
map_s_find_node calls map_s_get_value, map_s_order_eq, map_s_get_child, map_s_lessthan, to_node
map_s_order_eq calls map_s_lessthan
map_s_lessthan calls map_key_less_than