map_s_set_parent – MAPL
map_s_set_parent Subroutine
5 statements
Source File
private subroutine map_s_set_parent(this, parent)
Type Bound
map_s_Node
Arguments
Type Intent Optional Attributes Name
class(map_s_Node), intent(inout) :: this
type(map_s_Node), intent(in), pointer :: parent
Called by
Call graph
map_s_insert_single calls map_s_set_parent, map_s_rebalance
map_s_rot calls map_s_set_parent
map_s_rebalance calls map_s_rot
map_s_erase_nonleaf calls map_s_rebalance
map_s_erase_range calls map_s_rebalance, map_s_erase_nonleaf