map_iter_advance_default – MAPL
map_iter_advance_default Subroutine
9 statements
Source File
private subroutine map_iter_advance_default(it, n)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(inout) :: it
integer, intent(in) :: n
Calls
Called by
Contents
Call graph
map_iter_advance_default calls next
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_iter_next_n_size_kind calls next
advance calls map_iter_advance_default