map_s_insert_range – MAPL
map_s_insert_range Subroutine
11 statements
Source File
private recursive subroutine map_s_insert_range(this, first, last)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout) :: this
type(map_SetIterator), intent(in) :: first
type(map_SetIterator), intent(in) :: last
Calls
Call graph
map_s_insert_range calls insert, map_s_iter_next, map_s_iter_of
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
map_s_insert_initializer_list calls insert