map_s_erase_range – MAPL
map_s_erase_range Function
30 statements
Source File
private function map_s_erase_range(this, first, last) result(next_iter)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(inout) :: this
type(map_SetIterator), intent(in) :: first
type(map_SetIterator), intent(in) :: last
Return Value type(map_SetIterator)
Calls
Called by
Call graph
map_s_erase_range calls map_s_deallocate_child, map_s_erase_nonleaf, map_s_get_parent, map_s_has_child, map_s_iter_next, map_s_rebalance, map_s_which_child
map_s_erase_nonleaf calls map_s_rebalance, map_s_advpos, map_s_get_child, map_s_which_side_am_i, set_parent
map_s_iter_next calls map_s_advpos
map_s_rebalance calls map_s_has_child, get_height, map_s_get_child, map_s_rot, map_s_update_height
map_s_which_child calls map_s_get_child
map_s_advpos calls map_s_get_child, to_node
map_s_rot calls map_s_get_child, map_s_update_height, map_s_which_side_am_i, map_s_set_parent
map_s_update_height calls get_height
map_s_which_side_am_i calls map_s_get_parent, map_s_which_child
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_erase_value calls erase
map_s_merge calls erase
map_erase_key calls erase