map_iter_prev_n_size_kind – MAPL
map_iter_prev_n_size_kind Function
11 statements
Source File
private function map_iter_prev_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(CallbackMapIterator)
Calls
Called by
Call graph
map_iter_prev_n_size_kind calls map_iter_prev
map_iter_prev calls map_s_iter_prev
map_s_iter_prev calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
prev calls map_iter_prev_n_size_kind, map_iter_prev_1, map_s_iter_prev_1
map_iter_prev_1 calls prev
map_s_iter_prev_1 calls prev