map_begin – MAPL
map_begin Function
6 statements
Source File
private function map_begin(this) result(iter)
Type Bound
CallbackMap
Arguments
Type Intent Optional Attributes Name
class(CallbackMap), intent(in), target :: this
Return Value type(CallbackMapIterator)
Calls
Called by
Call graph
map_begin calls map_s_begin
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_advpos calls map_s_get_child, to_node
copy_callbacks calls map_begin
map_iter_begin calls map_begin
begin calls map_iter_begin
make_substates_from_num_grids calls copy_callbacks, make_substates
make_substates calls make_substates_from_num_grids
create_subobjects calls make_substates