map_iter_begin – MAPL
map_iter_begin Function
6 statements
Source File
private function map_iter_begin(cont) result(begin)
Arguments
Type Intent Optional Attributes Name
type(CallbackMap), intent(in), target :: cont
Return Value type(CallbackMapIterator)
Calls
Called by
Call graph
map_iter_begin calls map_begin
map_begin calls map_s_begin
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
begin calls map_iter_begin