map_iter_prev_1 – MAPL
map_iter_prev_1 Function
6 statements
Source File
private function map_iter_prev_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
Return Value type(CallbackMapIterator)
Calls
Called by
Call graph
map_iter_prev_1 calls prev
prev calls map_iter_prev_1, map_iter_prev_n_default, map_iter_prev_n_size_kind, map_s_iter_prev_1
map_iter_prev_n_default calls map_iter_prev
map_iter_prev_n_size_kind calls map_iter_prev
map_iter_prev calls map_s_iter_prev
map_s_iter_prev_1 calls prev