map_s_iter_ftn_begin – MAPL
map_s_iter_ftn_begin Function
6 statements
Source File
private function map_s_iter_ftn_begin(cont) result(begin)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in), target :: cont
Return Value type(map_SetIterator)
Calls
Called by
Contents
Call graph
map_s_iter_ftn_begin calls ftn_begin
ftn_begin calls map_iter_ftn_begin, map_s_iter_ftn_begin
map_iter_ftn_begin calls ftn_begin