map_new_map_initializer_list – MAPL
map_new_map_initializer_list Function
9 statements
Source File
private function map_new_map_initializer_list(il) result(m)
Arguments
Type Intent Optional Attributes Name
type(CallbackPair), intent(in) :: il(:)
Return Value type(CallbackMap)
Calls
Called by
Contents
Call graph
map_new_map_initializer_list calls insert, callbackmap
callbackmap calls map_new_map_initializer_list, map_new_map_copy, map_new_map_empty
map_new_map_empty calls map_set
map_set calls map_s_new_set_copy, map_s_new_set_empty, map_s_new_set_initializer_list