map_s_new_set_initializer_list – MAPL
map_s_new_set_initializer_list Function
9 statements
Source File
private function map_s_new_set_initializer_list(il) result(s)
Arguments
Type Intent Optional Attributes Name
type(CallbackPair), intent(in), dimension(:) :: il
Return Value type(map_Set)
Calls
Called by
Contents
Call graph
map_s_new_set_initializer_list calls insert
map_set calls map_s_new_set_initializer_list
map_new_map_empty calls map_set
callbackmap calls map_new_map_empty
map_new_map_initializer_list calls callbackmap