map_s_deep_copy – MAPL
map_s_deep_copy Subroutine
25 statements
Source File
private recursive subroutine map_s_deep_copy(this, other)
Type Bound
map_Set
Arguments
Type Intent Optional Attributes Name
class(map_Set), intent(out), target :: this
class(map_Set), intent(in), target :: other
Calls
Called by
Call graph
map_s_deep_copy calls insert, map_s_begin, map_s_iter_next, map_s_iter_of
map_s_begin calls map_s_iter_next
map_s_iter_next calls map_s_advpos
map_s_iter_of calls map_s_get_value
map_s_advpos calls map_s_get_child, to_node
map_s_insert_initializer_list calls insert
map_deep_copy calls map_s_deep_copy