map_iter_prev_n_default – MAPL
map_iter_prev_n_default Function
11 statements
Source File
private function map_iter_prev_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(CallbackMapIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(CallbackMapIterator)
Calls
Called by
Contents
Call graph
map_iter_prev_n_default calls prev
prev calls map_iter_prev_n_default, map_iter_prev_1, map_iter_prev_n_size_kind, map_s_iter_prev_1, map_s_iter_prev_n_default, map_s_iter_prev_n_size_kind
map_iter_prev_1 calls prev
map_iter_prev_n_size_kind calls prev
map_s_iter_prev_1 calls prev
map_s_iter_prev_n_default calls prev
map_s_iter_prev_n_size_kind calls prev