map_s_equal – MAPL
map_s_equal Function
20 statements
Source File
private function map_s_equal(a, b) result(equal)
Arguments
Type Intent Optional Attributes Name
type(map_Set), intent(in), target :: a
type(map_Set), intent(in), target :: b
Return Value logical
Calls
Called by
Contents
Call graph
map_s_equal calls begin, next, of, map_s_order_eq
begin calls map_iter_begin
next calls map_iter_next_1, map_iter_next_n_default, map_iter_next_n_size_kind
map_s_order_eq calls map_s_lessthan
map_iter_next_1 calls next
map_iter_next_n_default calls next
map_iter_next_n_size_kind calls next
map_s_lessthan calls map_key_less_than
operator(==) calls map_s_equal