map_s_which_child – MAPL
map_s_which_child Function
19 statements
Source File
private function map_s_which_child(this, child) result(side)
Type Bound
map_s_Node
Arguments
Type Intent Optional Attributes Name
class(map_s_Node), intent(in) :: this
type(map_s_Node), intent(in), target :: child
Return Value integer
Calls
Called by
Call graph
map_s_which_child calls map_s_get_child
map_s_erase_range calls map_s_which_child, map_s_erase_nonleaf, map_s_rebalance
map_s_which_side_am_i calls map_s_which_child
map_s_erase_nonleaf calls map_s_which_side_am_i, map_s_rebalance
map_s_rot calls map_s_which_side_am_i
map_erase_iter calls erase
map_erase_range calls erase
map_s_erase_iter calls erase
map_s_erase_value calls erase
map_s_merge calls erase
map_s_rebalance calls map_s_rot
map_s_insert_single calls map_s_rebalance