map_insert_pair – MAPL
map_insert_pair Subroutine
8 statements
Source File
private recursive subroutine map_insert_pair(this, p)
Type Bound
CallbackMap
Arguments
Type Intent Optional Attributes Name
class(CallbackMap), intent(inout) :: this
type(CallbackPair), intent(in) :: p
Calls
Called by
Call graph
map_insert_pair calls insert
map_s_insert_initializer_list calls insert
map_new_map_initializer_list calls insert
mapl_methodadd calls insert
callbackmap calls map_new_map_initializer_list