map_s_get_child – MAPL
map_s_get_child Function
24 statements
Source File
private function map_s_get_child(this, side) result(child)
Type Bound
map_s_Node
Arguments
Type Intent Optional Attributes Name
class(map_s_Node), intent(in), target :: this
integer, intent(in) :: side
Return Value type(map_s_Node), pointer
Called by
Call graph
map_s_advpos calls map_s_get_child
map_s_erase_nonleaf calls map_s_get_child, map_s_advpos, map_s_rebalance
map_s_find_node calls map_s_get_child
map_s_rebalance calls map_s_get_child, map_s_rot
map_s_rot calls map_s_get_child
map_s_verify calls map_s_get_child
map_s_which_child calls map_s_get_child
map_s_erase_range calls map_s_erase_nonleaf, map_s_rebalance, map_s_which_child
map_s_find calls map_s_find_node
map_s_insert_single calls map_s_find_node, map_s_rebalance
map_s_iter_next calls map_s_advpos
map_s_iter_prev calls map_s_advpos
map_s_lower_bound calls map_s_find_node
map_s_upper_bound calls map_s_find_node
map_s_which_side_am_i calls map_s_which_child