MAPL_CapGridCompCreate – MAPL
MAPL_CapGridCompCreate Subroutine
47 statements
Source File
public subroutine MAPL_CapGridCompCreate(cap, cap_rc, name, final_file, unusable, n_run_phases, root_set_services, root_dso, rc)
Uses
MAPL_StubComponent
Arguments
Type Intent Optional Attributes Name
type(MAPL_CapGridComp), intent(out), target :: cap
character(len=*), intent(in) :: cap_rc
character(len=*), intent(in) :: name
character(len=*), intent(in), optional :: final_file
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: n_run_phases
procedure, optional :: root_set_services
character(len=*), intent(in), optional :: root_dso
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_CapGridCompCreate
Source Code
   subroutine MAPL_CapGridCompCreate(cap, cap_rc, name, final_file, unusable, n_run_phases, root_set_services, root_dso,  rc)
      use mapl_StubComponent
    type(MAPL_CapGridComp), intent(out), target :: cap
    character(*), intent(in) :: cap_rc, name
    character(len=*), optional, intent(in) :: final_file
    class(KeywordEnforcer), optional, intent(in) :: unusable
    procedure(), optional :: root_set_services
    character(len=*), optional, intent(in) :: root_dso
    integer, optional, intent(in)  :: n_run_phases
    integer, optional, intent(out) :: rc
    type(MAPL_CapGridComp_Wrapper) :: cap_wrapper
    type(MAPL_MetaComp), pointer :: meta => null()
    integer :: status
    character(*), parameter :: cap_name = "CAP"
    type(StubComponent) :: stub_component
    _UNUSED_DUMMY(unusable)
    cap%cap_rc_file = cap_rc
    if (present(root_set_services)) cap%root_set_services => root_set_services
    if (present(root_dso)) cap%root_dso = root_dso
    if (present(root_dso) .and. present(root_set_services)) then
       _FAIL("can only specify a setservice pointer or a dso to use")
    end if
    if (present(final_file)) then
       allocate(cap%final_file, source=final_file)
    end if
    cap%n_run_phases = 1
    if (present(n_run_phases)) cap%n_run_phases = n_run_phases
    cap%config = ESMF_ConfigCreate(_RC)
    call ESMF_ConfigLoadFile(cap%config, cap%cap_rc_file,_RC)
    allocate(cap%name, source=name)
    cap%gc = ESMF_GridCompCreate(name=cap_name, config=cap%config, _RC)
    meta => null()
    call MAPL_InternalStateCreate(cap%gc, meta, _RC)
    call MAPL_Set(meta, CF=cap%config, _RC)
    call MAPL_Set(meta, name=cap_name, component=stub_component, _RC)
    cap_wrapper%ptr => cap
    call ESMF_UserCompSetInternalState(cap%gc, internal_cap_name, cap_wrapper, status)
    _VERIFY(status)
    _RETURN(_SUCCESS)
  end subroutine MAPL_CapGridCompCreate
Call graph
mapl_capgridcompcreate calls ESMF_ConfigCreate, ESMF_ConfigLoadFile, ESMF_GridCompCreate, ESMF_UserCompSetInternalState, mapl_assert, mapl_set, mapl_internalstatecreate, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
mapl_internalstatecreate calls ESMF_UserCompSetInternalState, mapl_return, mapl_verify, ESMF_GridCompGet, get_component, initialize, set_composite
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
initialize calls initialize_global_time_profiler
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_genericstateset calls ESMF_ConfigCreate, ESMF_ConfigLoadFile, mapl_return, mapl_verify, initialize, set_composite, get_composite, get_logger, set_component, set_logger
mapl_genericstatesetfromgc calls mapl_return, mapl_verify, mapl_genericstateset, mapl_internalstateget
mapl_throw_exception calls initialize
initialize_global_time_profiler calls get_global_time_profiler
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
initialize_cap_gc calls mapl_capgridcompcreate
run_model calls initialize_cap_gc
run_member calls run_model
run_ensemble calls run_member