MAPL_VerifyFriendlyInState – MAPL
MAPL_VerifyFriendlyInState Function
16 statements
Source File
private function MAPL_VerifyFriendlyInState(STATE, NAME, FRIEND2COMP, RC) result(FRIENDLY)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: STATE
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: FRIEND2COMP
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Contents
Source Code
MAPL_VerifyFriendlyInState
Source Code
   function MAPL_VerifyFriendlyInState(STATE,NAME,FRIEND2COMP,RC) result(FRIENDLY)
      type (ESMF_State),          intent(IN)    :: STATE
      character(len=*),           intent(IN)    :: NAME
      character(len=*),           intent(IN)    :: FRIEND2COMP
      integer  , optional,        intent(OUT)   :: RC
      logical                                   :: FRIENDLY
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_VerifyFriendlyState"
      integer                               :: status
      type (ESMF_field)                     :: FIELD
      call ESMF_StateGet(STATE,NAME,FIELD,RC=status)
      _VERIFY(status)
      FRIENDLY=MAPL_VerifyFriendly(FIELD,FRIEND2COMP,RC=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end function MAPL_VerifyFriendlyInState
Call graph
mapl_verifyfriendlyinstate calls esmf_stateget, mapl_verifyfriendly, mapl_return, mapl_verify
mapl_verifyfriendly calls mapl_verifyfriendlyinstate, mapl_verifyfriendlyinfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_verifyfriendlyinfield calls mapl_return, mapl_verify, ESMF_AttributeGet