MAPL_FieldBundleGetByIndex – MAPL
MAPL_FieldBundleGetByIndex Module Subroutine
24 statements
Source File
module subroutine MAPL_FieldBundleGetByIndex(Bundle, fieldIndex, Field, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
integer, intent(in) :: fieldIndex
type(ESMF_Field), intent(inout) :: Field
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_FieldBundleGetByIndex
Source Code
  module subroutine MAPL_FieldBundleGetByIndex(Bundle, fieldIndex, Field, RC)
    type(ESMF_FieldBundle),  intent(INout) :: Bundle
    integer,           intent(in   ) :: fieldIndex
    type(ESMF_Field),  intent(INout   ) :: Field
    integer, optional, intent(  out) :: rc
    ! ErrLog vars
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_FieldBundleGetByIndex"
    integer                               :: STATUS
    ! Local var
    character(len=ESMF_MAXSTR), parameter   :: attrName = MAPL_BundleItemOrderList
    character(len=ESMF_MAXSTR)              :: name
    character(len=ESMF_MAXSTR), allocatable :: currList(:)
    integer                                 :: natt
    ! check for attribute
    call ESMF_AttributeGet(Bundle, NAME=attrName, itemcount=natt, RC=STATUS)
    _VERIFY(STATUS)
    allocate(currList(natt), stat=status)
    _VERIFY(STATUS)
    ! get the current list
    call ESMF_AttributeGet(Bundle, NAME=attrName, VALUELIST=currList, rc=status)
    _VERIFY(STATUS)
    name = currList(fieldIndex)
    call ESMF_FieldBundleGet(Bundle, fieldName = name, field=field, rc=status)
    _VERIFY(STATUS)
    deallocate(currList)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldBundleGetByIndex
Call graph
mapl_fieldbundlegetbyindex calls esmf_attributeget, mapl_verify, esmf_fieldbundleget, mapl_return, mapl_fieldbundlegetbyindex
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_fieldbundleget calls mapl_fieldbundlegetbyindex
mapl_bundleread calls mapl_fieldbundleget
mapl_bundlewrite calls mapl_fieldbundleget
mapl_simplebundlecreatefrombundle calls mapl_fieldbundleget
mapl_gridcompgetfriendlies0 calls mapl_fieldbundleget
mapl_statevarread calls mapl_bundleread
mapl_statevarwrite calls mapl_bundlewrite
mapl_simplebundlecreatefromstate calls mapl_simplebundlecreatefrombundle
mapl_varread calls mapl_bundleread
mapl_varwrite calls mapl_bundlewrite
mapl_simplebundlecreate calls mapl_simplebundlecreatefrombundle
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0