MAPL_Range_REAL64 – MAPL
MAPL_Range_REAL64 Function
25 statements
Source File
private function MAPL_Range_REAL64(x0, x1, n, conversion_factor, rc) result(range)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: x0
real(kind=REAL64), intent(in) :: x1
integer, intent(in) :: n
real(kind=REAL64), intent(in), optional :: conversion_factor
integer, intent(out), optional :: rc
Return Value real(kind=REAL64), allocatable, (:)
Calls
Called by
Source Code
  function MAPL_Range_REAL64(x0, x1, n, conversion_factor,rc) result(range)
     real(kind=REAL64), allocatable :: range(:)
     real(kind=REAL64), intent(in) :: x0
     real(kind=REAL64), intent(in) :: x1
     integer, intent(in) :: n
     real(kind=REAL64), optional, intent(in) :: conversion_factor
     integer, optional, intent(out) :: rc
     integer :: i
     real(kind=REAL64) :: delta
     _ASSERT(((n /= 1) .or. (x0 == x1)),'needs informative message')
     allocate(range(n))
     range(1) = x0
     range(n) = x1
     if (n > 1) then
        delta = (x1 - x0)/(n-1)
        do i = 2, n-1
           range(i) = x0 + (i-1)*delta
        end do
     end if
     if (present(conversion_factor)) then
        range = range * conversion_factor
     end if
     _RETURN(_SUCCESS)
  end function MAPL_Range_REAL64
Call graph
mapl_range_real64 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_range calls mapl_range_real64
compute_lat_centers calls mapl_range
compute_lat_corners calls mapl_range
compute_lon_centers calls mapl_range
compute_lon_corners calls mapl_range
create_lat_lon_grid calls mapl_range
mapl_bundlewritencpar calls mapl_range
mapl_cfiocreatefrombundle calls mapl_range
mapl_iochangeres calls mapl_range
mapl_latlongridcreate calls mapl_range, mapl_latlongridcreate
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
create_esmf_grids calls create_lat_lon_grid
initialize_from_config_with_prefix calls compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners
initialize_from_file_metadata calls compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners
latlongridfactory_from_parameters calls compute_lat_centers, compute_lat_corners, compute_lon_centers, compute_lon_corners
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_statevarwritencpar calls mapl_bundlewritencpar
latlongridfactory calls latlongridfactory_from_parameters
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate
main calls create_esmf_grids