MAPL_StateSetTimeStamp – MAPL
MAPL_StateSetTimeStamp Subroutine
18 statements
Source File
private subroutine MAPL_StateSetTimeStamp(STATE, NAME, TIME, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
type(ESMF_Time), intent(inout) :: TIME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_StateSetTimeStamp(STATE,NAME,TIME,RC)
      type (MAPL_MetaComp),     intent(INOUT)   :: STATE
      character(len=*),         intent(IN   )   :: NAME
      type (ESMF_Time),         intent(INout)   :: TIME
      integer, optional,        intent(  OUT)   :: RC
      ! ErrLog Variables
      integer                           :: status
      ! Locals
      integer                           :: HOUR
      integer                           :: DATE
      integer                           :: IYR, IMM, IDD, IHR, IMN, ISC
      call ESMF_TimeGet(TIME ,YY=IYR, MM=IMM, DD=IDD, H=IHR, M=IMN, S=ISC, rc=status)
      _VERIFY(status)
      call MAPL_PackTime(DATE,IYR,IMM,IDD)
      call MAPL_PackTime(HOUR,IHR,IMN,ISC)
      call MAPL_StateSetSpecAttrib(STATE,NAME,forcing=.true., &
           refresh_interval=DATE, &
           averaging_interval=HOUR, rc=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateSetTimeStamp
Call graph
mapl_statesettimestamp calls ESMF_TimeGet, mapl_packtime, mapl_return, mapl_statesetspecattrib, mapl_verify
mapl_packtime calls mapl_packtime
mapl_return calls get_error_message, mapl_throw_exception
mapl_statesetspecattrib calls mapl_return, mapl_verify, mapl_varspecgetindex, mapl_varspecset, of
mapl_verify calls mapl_throw_exception
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecset calls mapl_varspecsetnew
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecsetnew calls mapl_return
mapl_readforcingx calls mapl_statesettimestamp
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2