MAPL_VarSpecAddRefFromItem – MAPL
MAPL_VarSpecAddRefFromItem Subroutine
53 statements
Source File
private subroutine MAPL_VarSpecAddRefFromItem(SPEC, ITEM, ALLOW_DUPLICATES, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM
logical, intent(in), optional :: ALLOW_DUPLICATES
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_VarSpecAddRefFromItem(SPEC, ITEM, ALLOW_DUPLICATES, RC)
      type (MAPL_VarSpec ), pointer         :: SPEC(:)
      type (MAPL_VarSpec ), intent(IN )     :: ITEM
      logical, optional   , intent(IN)      :: ALLOW_DUPLICATES
      integer, optional   , intent(OUT)     :: RC
      integer                               :: STATUS
      type (MAPL_VarSpec ), pointer         :: TMP(:) => null()
      integer                               :: I
      logical                               :: usableALLOW_DUPLICATES
      class(Logger), pointer :: lgr
      if(present(ALLOW_DUPLICATES)) then
         usableALLOW_DUPLICATES=ALLOW_DUPLICATES
      else
         usableALLOW_DUPLICATES=.FALSE.
      endif
      if(.not.associated(ITEM%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      if(associated(SPEC)) then
         if (.not. usableALLOW_DUPLICATES) then
            I = MAPL_VarSpecGetIndex(SPEC, ITEM, RC=STATUS)
            _VERIFY(STATUS)
            if(I /= -1) then
               if (SPEC(I) == ITEM) THEN
                  if(present(RC)) then
                     RC=MAPL_DuplicateEntry
                  end if
                  return
               else
                  lgr => logging%get_logger('MAPL.GENERIC')
                  call lgr%error("Duplicate SHORT_NAME %a with different attributes.", trim(ITEM%SPECPtr%short_name))
                  call MAPL_VarSpecPrint(ITEM)
                  call MAPL_VarSpecPrint(SPEC(I))
                  _RETURN(ESMF_FAILURE)
               end if
            endif
         end if
      else
         allocate(SPEC(0),stat=STATUS)
         _VERIFY(STATUS)
      endif
      I = size(SPEC)
      allocate(TMP(I+1),stat=STATUS)
      _VERIFY(STATUS)
      TMP(1:I) = SPEC
      deallocate(SPEC)
      TMP(I+1)%SPECPtr => ITEM%SPECPtr
      SPEC => TMP
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecAddRefFromItem
Call graph
mapl_varspecaddreffromitem calls mapl_varspecgetindex, mapl_varspecprint, get_logger, error, mapl_return, mapl_verify
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecprintmany calls mapl_varspecprint, mapl_return, mapl_verify
mapl_varspecprintone calls mapl_return, info
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_varspecaddreffromlist calls mapl_varspecaddreffromitem
mapl_genericspecenum calls mapl_varspecaddreftolist, mapl_genericspecenum
mapl_setvarspecforcc calls mapl_varspecaddreftolist
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_genericsetservices calls mapl_genericspecenum, mapl_wirecomponent
addnewspec calls mapl_addexportspec, mapl_addimportspec
setservices calls mapl_genericsetservices, mapl_addinternalspec, mapl_addexportspec