MAPL_StateGetVarSpecs – MAPL
MAPL_StateGetVarSpecs Subroutine
18 statements
Source File
private subroutine MAPL_StateGetVarSpecs(STATE, IMPORT, EXPORT, INTERNAL, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(in) :: STATE
type(MAPL_VarSpec), optional, pointer :: IMPORT(:)
type(MAPL_VarSpec), optional, pointer :: EXPORT(:)
type(MAPL_VarSpec), optional, pointer :: INTERNAL(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_StateGetVarSpecs(STATE,IMPORT,EXPORT,INTERNAL,RC)
      ! !ARGUMENTS:
      type(MAPL_MetaComp),       intent(IN)  :: STATE
      type(MAPL_VarSpec ), pointer, optional :: IMPORT(:)
      type(MAPL_VarSpec ), pointer, optional :: EXPORT(:)
      type(MAPL_VarSpec ), pointer, optional :: INTERNAL(:)
      integer,             optional, intent(OUT) :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      ! Begin
      ! Get the specs for the 3 ESMF states
      ! -----------------------------------
      if(present(IMPORT)) then
         IMPORT => STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      endif
      if(present(EXPORT)) then
         EXPORT => STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      endif
      if(present(INTERNAL)) then
         INTERNAL => STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateGetVarSpecs
Call graph
mapl_stategetvarspecs calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_genericsetservices calls mapl_stategetvarspecs, mapl_gridcompgetvarspecs, mapl_wirecomponent
mapl_gridcompgetvarspecs calls mapl_stategetvarspecs
mapl_childaddattribtoimportspec calls mapl_gridcompgetvarspecs
mapl_setvarspecforcc calls mapl_gridcompgetvarspecs
mapl_stateaddexportspecfrmall calls mapl_gridcompgetvarspecs
mapl_stateaddexportspecfrmchld_all calls mapl_gridcompgetvarspecs
mapl_stateaddimportspecfrmchld calls mapl_gridcompgetvarspecs
mapl_wirecomponent calls mapl_gridcompgetvarspecs
setservices calls mapl_genericsetservices, mapl_addexportspec
mapl_addexportspec calls mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld_all
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
addnewspec calls mapl_addexportspec, mapl_addimportspec