MAPL_ProcessServiceConnections – MAPL
MAPL_ProcessServiceConnections Subroutine
34 statements
Source File
private subroutine MAPL_ProcessServiceConnections(META, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), pointer :: META
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_ProcessServiceConnections
Source Code
   subroutine MAPL_ProcessServiceConnections(META, RC)
      !ARGUMENTS:
      type (MAPL_MetaComp), pointer :: META
      integer, optional,           intent(  OUT) :: RC     ! Error code:
      integer :: status
      type (MAPL_Connectivity), pointer     :: conn
      type (ServiceConnectionItemVectorIterator) :: iter
      type (ServiceConnectionType), pointer :: item
      type(ESMF_FieldBundle) :: PBUNDLE, RBUNDLE
      type(ESMF_Field) :: FIELD
      integer :: K, NF
      character(len=ESMF_MAXSTR) :: service, provider, requester
      conn => meta%connectList
      iter = conn%ServiceConnectionItems%begin()
      ! loop over service connections
      do while (iter /= conn%ServiceConnectionItems%end())
         item => iter%get()
         ! retrieve connection info
         call ServiceConnectionGet(item, &
              service=service, provider=provider, requester=requester, &
              rc=status)
         _VERIFY(status)
         ! get the PBUNDLE and RBUNDLE
         call MAPL_ServiceGetBundle(META, provider=provider, &
              service=service, bundle=pbundle, RC=status)
         _VERIFY(status)
         call MAPL_ServiceGetBundle(META, requester=requester, &
              service=service, bundle=rbundle, RC=status)
         _VERIFY(status)
         call ESMF_FieldBundleGet(RBUNDLE, FieldCount=NF, RC=status)
         _VERIFY(status)
         ! loop over entries in RBUNDLE
         DO K = 1, NF
            call ESMF_FieldBundleGet(RBUNDLE, K, FIELD, RC=status)
            _VERIFY(status)
            ! add each of the fields to PBUNDLE, duplicates are allowed
            call MAPL_FieldBundleAdd(PBUNDLE, FIELD, multiflag=.true., RC=status)
            _VERIFY(status)
         END DO
         call iter%next()
      END DO
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ProcessServiceConnections
Call graph
mapl_processserviceconnections calls serviceconnectionget, mapl_verify, mapl_fieldbundleadd, mapl_servicegetbundle, esmf_fieldbundleget, mapl_return
serviceconnectionget calls mapl_return
mapl_verify calls mapl_throw_exception
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_servicegetbundle calls mapl_verify, mapl_return, mapl_assert, mapl_findchild, providedserviceget, requestedserviceget
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_findchild calls mapl_verify, mapl_return, mapl_findchild, mapl_internalstateretrieve
providedserviceget calls mapl_return, mapl_assert
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_verify, mapl_return, esmf_attributeget, esmf_attributeremove, esmf_fieldbundleadd, esmf_fieldget, esmf_attributeset
requestedserviceget calls mapl_return, mapl_assert
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_assert_condition calls mapl_throw_exception