MAPL_DoNotAllocateVar – MAPL
MAPL_DoNotAllocateVar Subroutine
23 statements
Source File
private subroutine MAPL_DoNotAllocateVar(SPEC, NAME, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_DoNotAllocateVar
Source Code
   subroutine MAPL_DoNotAllocateVar(SPEC, NAME, notFoundOK, RC)
      type (MAPL_VarSpec),  pointer       :: SPEC(:)
      character(len=*),     intent(IN   ) :: NAME
      logical, optional,    intent(IN   ) :: notFoundOK
      integer, optional,    intent(  OUT) :: RC         ! Return code
      integer                       :: status
      integer                       :: I
      logical                       :: notFoundOK_
      notFoundOK_ = .false.
      if (present(notFoundOK)) then
         notFoundOK_ = notFoundOK
      end if
      I = MAPL_VarSpecGetIndex(Spec, NAME)
      if (I<=0 .and. notFoundOK_) then
         _RETURN(ESMF_SUCCESS)
      end if
      _ASSERT(I>0,'needs informative message') ! make sure NAME is in the SPEC
      call MAPL_VarSpecSet(SPEC(I), doNotAllocate = .true., RC=status )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_DoNotAllocateVar
Call graph
mapl_donotallocatevar calls mapl_varspecgetindex, mapl_assert, mapl_varspecset, mapl_verify, mapl_return
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_varspecset calls mapl_varspecsetnew
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_varspecgetindexbyname calls mapl_return
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_varspecsetnew calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_donotallocateimport calls mapl_donotallocatevar
mapl_donotallocateinternal calls mapl_donotallocatevar