MAPL_CFIODestroy – MAPL
MAPL_CFIODestroy Subroutine
33 statements
Source File
public subroutine MAPL_CFIODestroy(MCFIO, RC)
The subroutine MAPL_CFIODestroy destroys a MAPL CFIO object. It closes any file associated with it and deallocates memory.
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CFIODestroy
Source Code
  subroutine MAPL_CFIODestroy( MCFIO, RC )
!
  type(MAPL_CFIO),             intent(INOUT) :: MCFIO
  integer, optional,           intent(  OUT) :: RC
!
  integer :: status
  if(associated(MCFIO%Krank     )) deallocate(MCFIO%Krank     )
  if(associated(MCFIO%reqs      )) deallocate(MCFIO%reqs      )
  if(associated(MCFIO%varname   )) deallocate(MCFIO%varname   )
  if(associated(MCFIO%vardims   )) deallocate(MCFIO%vardims   )
  if(associated(MCFIO%Levs      )) deallocate(MCFIO%Levs      )
  if(associated(MCFIO%vartype   )) deallocate(MCFIO%vartype   )
  if(associated(MCFIO%needvar   )) deallocate(MCFIO%needvar   )
  if(associated(MCFIO%pairList  )) deallocate(MCFIO%pairList  )
  if(associated(MCFIO%buffer    )) deallocate(MCFIO%buffer  )
  if(associated(MCFIO%varid     )) deallocate(MCFIO%varid  )
  nullify(MCFIO%Krank     )
  nullify(MCFIO%reqs      )
  nullify(MCFIO%varname   )
  nullify(MCFIO%vardims   )
  nullify(MCFIO%Levs      )
  nullify(MCFIO%varid     )
  nullify(MCFIO%buffer    )
  if (MCFIO%Root > 0) then
     if (MCFIO%myPE == mCFIO%RootRank) then
        call ESMF_CFIOFileClose(MCFIO%CFIO,rc=status)
        _VERIFY(STATUS)
     end if
  end if
  call ESMF_CFIODestroy(MCFIO%CFIO,rc=status)
  _VERIFY(STATUS)
  MCFIO%created = .false.
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIODestroy
Call graph
mapl_cfiodestroy calls esmf_cfiodestroy, esmf_cfiofileclose, mapl_return, mapl_verify
esmf_cfiodestroy calls grids, cfio_close, esmf_cfiogriddestroy, esmf_cfiovarinfodestroy, varobjs
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
cfio_close calls ncclos, err
esmf_cfioget calls err
esmf_cfiosdffileclose calls cfio_close
esmf_cfiovarinfodestroy calls esmf_cfiogriddestroy, cnodedestroy, inodedestroy, rnodedestroy
get_error_message calls at
mapl_throw_exception calls initialize
esmf_iodestroy calls mapl_cfiodestroy
finalize calls mapl_cfiodestroy
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
test_main calls esmf_iodestroy
utcfio calls test_main