MAPL_GetRootGC – MAPL
MAPL_GetRootGC Subroutine
17 statements
Source File
private recursive subroutine MAPL_GetRootGC(GC, rootGC, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_GridComp), intent(out) :: rootGC
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_GetRootGC
Source Code
   recursive subroutine MAPL_GetRootGC(GC, rootGC, RC)
      type(ESMF_GridComp),    intent(INout) :: GC
      type(ESMF_GridComp),    intent(  OUT) :: rootGC
      integer, optional,      intent(OUT)   :: rc
      integer                               :: status
      type (MAPL_MetaComp),     pointer     :: meta
      call MAPL_GetObjectFromGC(GC, meta, _RC)
      if (.not. associated(meta%parentGC)) then
         rootGC = GC
      else
         call MAPL_GetRootGC(meta%parentGC, rootGC, _RC)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GetRootGC
Call graph
mapl_getrootgc calls mapl_getrootgc, mapl_getobjectfromgc, mapl_return, mapl_verify
mapl_getobjectfromgc calls mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_genericsetservices calls mapl_getrootgc
setservices calls mapl_genericsetservices