MAPL_GetAllExchangeGrids – MAPL
MAPL_GetAllExchangeGrids Subroutine
52 statements
Source File
public recursive subroutine MAPL_GetAllExchangeGrids(GC, LSADDR, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer(kind=INT64), pointer :: LSADDR(:)
integer, intent(out) :: RC
Calls
Called by
Source Code
   recursive subroutine MAPL_GetAllExchangeGrids ( GC, LSADDR, RC )
      type(ESMF_GridComp),  intent(INOUT) :: GC         ! Gridded component
      integer(kind=INT64),            pointer       :: LSADDR(:)
      integer,              intent(  OUT) :: RC         ! Return code
      integer :: status
      type (MAPL_MetaComp),              pointer  :: MAPLOBJ
      type (MAPL_LocStream)                       :: LocStream
      character(len=ESMF_MAXSTR)   :: CNAME
      integer(kind=INT64)                    :: ADDR
      integer                      :: I
      integer                      :: N
      integer(kind=INT64), pointer           :: TMP(:)
      logical                      :: found
      type(ESMF_GridComp), pointer :: gridcomp
      ! Retrieve the pointer to the internal state
      ! --------------------------------------------
      call MAPL_GetObjectFromGC ( GC, MAPLOBJ, RC=status)
      _VERIFY(status)
      LocStream = MAPLOBJ%LocStream
      call c_MAPL_LocStreamRetrievePtr(LocStream, ADDR)
      call ESMF_GridCompGet(GC, NAME = cname, rc=status)
      _VERIFY(status)
      if (ADDR /= 0) then
         N = 0
         if (associated(LSADDR)) then
            N = SIZE(LSADDR)
         end if
         found = .false.
         do I = 1, N
            if (addr == LSADDR(I)) then
               found = .true.
               exit
            end if
         end do
         if (.not. found) then
            allocate(tmp(N+1), stat=status)
            _VERIFY(status)
            if (N > 0) then
               tmp(1:N) = LSADDR
               deallocate(LSADDR)
            end if
            N = N + 1
            tmp(N) = addr
            LSADDR => TMP
         end if
      end if
      do I = 1, MAPLOBJ%get_num_children()
         gridcomp => MAPLOBJ%GET_CHILD_GRIDCOMP(I)
         call MAPL_GetAllExchangeGrids(gridcomp, LSADDR, RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GetAllExchangeGrids
Call graph
mapl_getallexchangegrids calls mapl_getallexchangegrids, ESMF_GridCompGet, c_mapl_locstreamretrieveptr, mapl_getobjectfromgc, get_child_gridcomp, get_num_children, mapl_return, mapl_verify
mapl_getobjectfromgc calls mapl_internalstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
initialize_history calls mapl_getallexchangegrids
initialize_gc calls initialize_history