MAPL_InternalESMFStateGet – MAPL
MAPL_InternalESMFStateGet Subroutine
44 statements
Source File
public recursive subroutine MAPL_InternalESMFStateGet(GC, name, result, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: name
type(ESMF_State), intent(out) :: result
integer, intent(out) :: rc
Calls
Called by
Source Code
   recursive subroutine MAPL_InternalESMFStateGet ( GC, name, result, rc )
      type(ESMF_GridComp), intent(INout)  :: GC
      character(len=*),  intent(IN   ) :: name
      type (ESMF_State), intent(  OUT) :: result
      integer,           intent(  OUT) :: rc
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_InternalESMFStateGet"
      integer                               :: status
      integer                               :: I
      logical                               :: have_ens
      character(len=ESMF_MAXSTR)            :: sname
      type (MAPL_MetaComp),pointer          :: STATE
      type(ESMF_State)                      :: internal
      type(ESMF_GridComp), pointer :: gridcomp
      have_ens = index(name,":") /= 0
      call MAPL_InternalStateGet ( GC, STATE, RC=status)
      _VERIFY(status)
      call MAPL_Get(STATE,INTERNAL_ESMF_STATE=internal,rc=status)
      _VERIFY(status)
      call ESMF_StateGet(internal, name=sname, rc=status)
      _VERIFY(status)
      if (have_ens) then
         if (sname == trim(name) // '_INTERNAL') then
            result = internal
            _RETURN(ESMF_SUCCESS)
         end if
      else
         if (sname(index(sname,":")+1:) == trim(name) // '_INTERNAL') then
            result = internal
            _RETURN(ESMF_SUCCESS)
         end if
      end if
      do I = 1, STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(I)
         call MAPL_InternalESMFStateGet(gridcomp, name, result, RC=status)
         if (status == ESMF_SUCCESS) then
            _RETURN(ESMF_SUCCESS)
         end if
      end do
      rc = ESMF_FAILURE
      return
   end subroutine MAPL_InternalESMFStateGet
Call graph
mapl_internalesmfstateget calls mapl_internalesmfstateget, esmf_stateget, mapl_get, get_child_gridcomp, get_num_children, mapl_internalstateget, mapl_return, mapl_verify
mapl_get calls mapl_genericstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_genericstateget calls get_child_gridcomp, get_num_children, mapl_return, mapl_verify, ESMF_GridGet, get_child_export_state, get_child_import_state, get_grid, get_internal_state, mapl_locstreamget, mapl_sunorbitcreated, mapl_sunorbitcreatefromconfig
mapl_throw_exception calls initialize
get_field_from_internal calls mapl_internalesmfstateget