MAPL_CommsAllReduceSum_I4_1 – MAPL
MAPL_CommsAllReduceSum_I4_1 Subroutine
16 statements
Source File
private subroutine MAPL_CommsAllReduceSum_I4_1(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf(:)
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf(:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Calls
Called by
Call graph
mapl_commsallreducesum_i4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_commsallreducesum calls mapl_commsallreducesum_i4_1
mapl_areamean_2d_r8 calls mapl_commsallreducesum
mapl_areamean calls mapl_areamean_2d_r8
mapl_areamean_2d_r8_bitrep calls mapl_areamean