MAPL_nsecf – MAPL
MAPL_nsecf Module Function
4 statements
Source File
module function MAPL_nsecf(nhms) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nhms
Return Value integer
Called by
Contents
Source Code
MAPL_nsecf
Source Code
  integer module function MAPL_nsecf(nhms)
    integer, intent(in) :: nhms
    MAPL_nsecf = nhms/10000*3600 + mod(nhms,10000)/100*60 + mod(nhms,100)
  end function MAPL_nsecf
Call graph
mapl_nsecf calls mapl_nsecf
get_tdim calls mapl_nsecf
mapl_gradsctlwrite calls mapl_nsecf
initialize calls mapl_nsecf, get_tdim
mapl_nsecf2 calls mapl_nsecf, mapl_nsecf2
mapl_tick calls mapl_nsecf, mapl_tick
run calls mapl_gradsctlwrite