MAPL_ChildAddAttribToImportSpec – MAPL
MAPL_ChildAddAttribToImportSpec Subroutine
26 statements
Source File
public subroutine MAPL_ChildAddAttribToImportSpec(STATE, CHILD_ID, REFRESH_INTERVAL, AVERAGING_INTERVAL, OFFSET, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
integer, intent(in) :: CHILD_ID
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
integer, intent(in), optional :: OFFSET
integer, intent(out), optional :: RC
Calls
Source Code
   subroutine MAPL_ChildAddAttribToImportSpec ( STATE, CHILD_ID, &
        REFRESH_INTERVAL, AVERAGING_INTERVAL, OFFSET, RC )
      !ARGUMENTS:
      type (MAPL_MetaComp)            , intent(INOUT)   :: STATE
      integer                         , intent(IN)      :: CHILD_ID
      integer            , optional   , intent(IN)      :: REFRESH_INTERVAL
      integer            , optional   , intent(IN)      :: AVERAGING_INTERVAL
      integer            , optional   , intent(IN)      :: OFFSET
      integer            , optional   , intent(OUT)     :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_ChildAddAttribToImportSpec"
      integer                               :: status
      type (MAPL_VarSpec),      pointer     :: SPECS(:)
      integer                               :: I
      type(ESMF_GridComp), pointer :: gridcomp
      if (.not. STATE%get_num_children() > 0) then
         _RETURN(ESMF_FAILURE)
      end if
      gridcomp => STATE%GET_CHILD_GRIDCOMP(CHILD_ID)
      call MAPL_GridCompGetVarSpecs(gridcomp, IMPORT=SPECS, RC=status)
      _VERIFY(status)
      do I = 1, size(SPECS)
         call MAPL_VarSpecSet(SPECS(I),                  &
              ACCMLT_INTERVAL= AVERAGING_INTERVAL,       &
              COUPLE_INTERVAL= REFRESH_INTERVAL,         &
              OFFSET         = OFFSET,                   &
              RC=status  )
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ChildAddAttribToImportSpec
Call graph
mapl_childaddattribtoimportspec calls mapl_varspecset, get_child_gridcomp, get_num_children, mapl_gridcompgetvarspecs, mapl_return, mapl_verify
mapl_varspecset calls mapl_varspecsetnew
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_gridcompgetvarspecs calls mapl_return, mapl_verify, ESMF_GridCompGet, mapl_internalstateretrieve, mapl_stategetvarspecs
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_stategetvarspecs calls mapl_return
mapl_throw_exception calls initialize
mapl_varspecsetnew calls mapl_return
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState