MAPL_Comm_Dup – MAPL
MAPL_Comm_Dup Subroutine
13 statements
Source File
private subroutine MAPL_Comm_Dup(comm, newcomm, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(out) :: newcomm
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_Comm_Dup(comm, newcomm, rc)
    integer, intent(in) :: comm
    integer, intent(out) :: newcomm
    integer, optional, intent(out) :: rc
    integer :: status
    newcomm = MPI_COMM_NULL
    if(comm /= MPI_COMM_NULL) then
       call MPI_Comm_Dup(comm, newcomm,status)
       _VERIFY(status)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_Comm_Dup
Call graph
mapl_comm_dup calls mpi_comm_dup, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
arrdescrcreatereadercomm calls mapl_comm_dup
arrdescrcreatewritercomm calls mapl_comm_dup
arrdescrinit calls mapl_comm_dup
arrdescrset calls mapl_comm_dup
arrdescrsetncpar calls arrdescrcreatereadercomm, arrdescrcreatewritercomm, arrdescrset
mapl_bundlewritencpar calls arrdescrset
mapl_esmfstatereadfromfile calls arrdescrcreatereadercomm, arrdescrset, arrdescrsetncpar
mapl_esmfstatewritetofile calls arrdescrcreatewritercomm, arrdescrset, arrdescrsetncpar
mapl_readforcingx calls arrdescrset
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_varwritencpar calls mapl_bundlewritencpar
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarwritencpar calls mapl_bundlewritencpar