MAPL_RunExpression – MAPL
MAPL_RunExpression Subroutine
22 statements
Source File
private subroutine MAPL_RunExpression(state, fields, tmpfields, rewrite, nfield, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: fields(:,:)
character(len=*), intent(in) :: tmpfields(:)
logical, intent(inout) :: rewrite(:)
integer, intent(in) :: nfield
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_RunExpression
Source Code
  subroutine MAPL_RunExpression(state,fields,tmpfields,rewrite,nfield,rc)
  type (ESMF_State),  intent(in)    :: state
  character(len=*), intent(in):: fields(:,:),tmpfields(:)
  logical, intent(inout) :: rewrite(:)
  integer, intent(in):: nfield
  integer, optional, intent(out) :: rc
! Local variables:
  character(len=ESMF_MAXSTR)     :: fname,fexpr
  integer:: m,STATUS
  type(ESMF_Field) :: field
  do m=1,nfield
     if (rewrite(m)) then
        fname = trim(fields(3,m))
        call MAPL_StateGet(state,fname,field,_RC)
        fexpr = tmpfields(m)
        call MAPL_StateEval(state,fexpr,field,_RC)
     end if
  enddo
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_RunExpression
Call graph
mapl_runexpression calls mapl_stateget, mapl_verify, mapl_stateeval, mapl_return
mapl_stateget calls mapl_verify, mapl_return, esmf_stateget, mapl_assert, esmf_fieldbundleget
mapl_verify calls mapl_throw_exception
mapl_stateeval calls mapl_verify, esmf_stateget, mapl_assert, checkifconformal, checksyntax, parsef, evalf, bytecode_dealloc
mapl_return calls mapl_throw_exception, get_error_message
run calls mapl_runexpression