MAPL_DestroyStateSave – MAPL
MAPL_DestroyStateSave Subroutine
28 statements
Source File
public recursive subroutine MAPL_DestroyStateSave(GC, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine MAPL_DestroyStateSave(gc,rc)
      type(ESMF_GridComp), intent(inout) :: GC
      integer, optional,   intent(out) :: rc
      type(MAPL_MetaComp), pointer :: state
      integer :: unit, i, status
      type (ESMF_GridComp), pointer :: gridcomp
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      do I=1,STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(I)
         call MAPL_DestroyStateSave (gridcomp, RC=status )
         _VERIFY(status)
      enddo
      if (allocated(STATE%initial_state%imp_fname)) then
         UNIT = GETFILE(STATE%initial_state%IMP_FNAME, RC=status)
         _VERIFY(status)
         call MAPL_DestroyFile(unit = UNIT, rc=status)
         _VERIFY(status)
         deallocate(STATE%initial_state%imp_fname)
      end if
      if (allocated(state%initial_state%int_fname)) then
         UNIT = GETFILE(STATE%initial_state%INT_FNAME, RC=status)
         _VERIFY(status)
         call MAPL_DestroyFile(unit = UNIT, rc=status)
         _VERIFY(status)
         deallocate(state%initial_state%int_fname)
      end if
   end subroutine MAPL_DestroyStateSave
Call graph
mapl_destroystatesave calls mapl_destroystatesave, get_child_gridcomp, get_num_children, getfile, mapl_destroyfile, mapl_internalstateretrieve, mapl_verify
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
getfile calls mapl_verify, mapl_am_i_root, getfilemem, mapl_open, mapl_return
mapl_destroyfile calls dealloc_
mapl_internalstateretrieve calls mapl_verify, mapl_internalstatecreate, mapl_internalstateget, mapl_return
mapl_verify calls mapl_throw_exception
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
dealloc_ calls mapl_return, mapl_assert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_internalstatecreate calls mapl_verify, mapl_return, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_verify, mapl_return, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_open calls mapl_verify, mapl_am_i_root, mapl_return
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
destroy_state calls mapl_destroystatesave