MAPL_AreaMean_2d_r8_bitrep – MAPL
MAPL_AreaMean_2d_r8_bitrep Subroutine
64 statements
Source File
private subroutine MAPL_AreaMean_2d_r8_bitrep(qave, q, area, grid, bitreproducible, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out) :: qave
real, intent(in) :: q(:,:)
real, intent(in) :: area(:,:)
type(ESMF_Grid), intent(inout) :: grid
logical, intent(in) :: bitreproducible
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_AreaMean_2d_r8_bitrep
Source Code
  subroutine MAPL_AreaMean_2d_r8_bitrep ( qave, q, area, grid, bitreproducible, rc )
    implicit none
    ! Arguments
    real(kind=REAL64), intent(  OUT) :: qave
    real,              intent(IN   ) :: q(:,:)
    real,              intent(IN   ) :: area(:,:)
    type(ESMF_Grid),   intent(INout) :: grid
    logical,           intent(IN   ) :: bitreproducible
    integer, optional, intent(  OUT) :: rc
    ! Log err vars
    integer :: status
    character(len=ESMF_MAXSTR), parameter :: Iam='MAPL_AreaMeanBR'
    ! Local vars
    real(kind=REAL64)  :: qdum(2)
    integer :: im,jm
    integer :: DIMS(3)
    integer :: i,j
    logical :: amIRoot
    real, allocatable :: qglobal(:,:)
    real, allocatable :: aglobal(:,:)
    type(ESMF_VM) :: vm
    if (.not. bitreproducible) then
       call MAPL_AreaMean(qave, q, area, grid, rc=status )
       _RETURN(STATUS)
    end if
    ! get VM (should get from the grid, but this is quicker)
    call ESMF_VmGetCurrent(vm, rc=status)
    _VERIFY(STATUS)
    amIRoot = MAPL_AM_I_Root(vm)
    if (amIRoot) then
       call MAPL_GridGet(GRID, globalCellCountPerDim=DIMS, RC=STATUS)
       im = DIMS(1) ! global grid dim
       jm = DIMS(2) ! global grid dim
    else
       im = 0 ! dummy sizes
       jm = 0 ! dummy sizes
    end if
    allocate(qglobal(im,jm), stat=status)
    _VERIFY(STATUS)
    allocate(aglobal(im,jm), stat=status)
    _VERIFY(STATUS)
    call ArrayGather(local_array=area, global_array=aglobal, grid=grid, rc=status)
    _VERIFY(STATUS)
    call ArrayGather(local_array=q,    global_array=qglobal, grid=grid, rc=status)
    _VERIFY(STATUS)
    qdum = 0.0d+0
    ! do calculation on root
    if (amIRoot) then
       do j=1,jm
          do i=1,im
             if (qglobal(i,j) == MAPL_Undef) cycle ! exclude any undefs
             qdum(1) = qdum(1) + qglobal(i,j)*aglobal(i,j)
             qdum(2) = qdum(2) + aglobal(i,j)
          enddo
       end do
       if (qdum(2) /= 0.0d+0) then
          qave = qdum(1) / qdum(2)
          !ALT: convert the the result to single precision
          !     This technically is not needed here, but is is done to be in sync
          !     with the parallel method below
          !     qave = real(qave, kind=4)
       else
          qave = MAPL_Undef
       end if
    end if
    deallocate(aglobal)
    deallocate(qglobal)
    call MAPL_CommsBcast(vm, DATA=qave, N=1, Root=MAPL_Root, RC=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_AreaMean_2d_r8_bitrep
Call graph
mapl_areamean_2d_r8_bitrep calls ESMF_VMGetCurrent, arraygather, mapl_am_i_root, mapl_areamean, mapl_commsbcast, mapl_gridget, mapl_return, mapl_verify
mapl_areamean calls mapl_areamean_2d_r8_bitrep