MAPL_GenericStateSet – MAPL
MAPL_GenericStateSet Subroutine
70 statements
Source File
private subroutine MAPL_GenericStateSet(STATE, ORBIT, LM, RUNALARM, CHILDINIT, LOCSTREAM, EXCHANGEGRID, CLOCK, NAME, CF, ConfigFile, component, RC)
Uses
mapl_AbstractComposite
mapl_ConcreteComposite
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
type(MAPL_SunOrbit), intent(in), optional :: ORBIT
integer, intent(in), optional :: LM
type(ESMF_Alarm), intent(in), optional :: RUNALARM
logical, intent(in), optional :: CHILDINIT
type(MAPL_LocStream), intent(in), optional :: LOCSTREAM
type(MAPL_LocStream), intent(in), optional :: EXCHANGEGRID
type(ESMF_Clock), intent(in), optional :: CLOCK
character(len=*), intent(in), optional :: NAME
type(ESMF_Config), intent(in), optional :: CF
character(len=*), intent(in), optional :: ConfigFile
class(AbstractComponent), intent(in), optional :: component
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GenericStateSet
Source Code
   subroutine MAPL_GenericStateSet (STATE, ORBIT, LM, RUNALARM, CHILDINIT, &
        LOCSTREAM, EXCHANGEGRID, CLOCK, NAME,  &
        CF, ConfigFile, component, RC)
      use mapl_AbstractComposite
      use mapl_ConcreteComposite
      !ARGUMENTS:
      type (MAPL_MetaComp),            intent(INOUT) :: STATE
      type (ESMF_Alarm),     optional, intent(IN   ) :: RUNALARM
      type (MAPL_SunOrbit),  optional, intent(IN   ) :: ORBIT
      integer,               optional, intent(IN   ) :: LM
      logical,               optional, intent(IN   ) :: CHILDINIT
      type (MAPL_LocStream), optional, intent(IN   ) :: LOCSTREAM
      type (MAPL_LocStream), optional, intent(IN   ) :: EXCHANGEGRID
      type (ESMF_Clock)    , optional, intent(IN   ) :: CLOCK
      type (ESMF_Config)   , optional, intent(IN   ) :: CF
      character(len=*)     , optional, intent(IN   ) :: NAME
      character(len=*)     , optional, intent(IN   ) :: ConfigFile
      class(AbstractComponent), optional, intent(in) :: component
      integer,               optional, intent(  OUT) :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm = "MAPL_GenericStateSet"
      integer :: status
      class(AbstractComposite), pointer :: composite
      type(ConcreteComposite), pointer :: t_composite
      ! Fixup uninitialized METAs
      ! Fixup uninitialized META objs.
      composite => STATE%get_composite()
      if (.not. associated(composite)) then
         allocate(t_composite)
         call t_composite%initialize(STATE)
         composite => t_composite
         call STATE%set_composite(composite)
      end if
      if(present(LM)) then
         STATE%GRID%LM=LM
      endif
      if(present(ORBIT)) then
         STATE%ORBIT=ORBIT
      endif
      if(present(RUNALARM)) then
         STATE%ALARM(0)=RUNALARM
      endif
      if(present(CHILDINIT)) then
         STATE%CHILDINIT=CHILDINIT
      endif
      if(present(LOCSTREAM)) then
         STATE%LOCSTREAM=LOCSTREAM
      endif
      if(present(EXCHANGEGRID)) then
         STATE%EXCHANGEGRID=EXCHANGEGRID
      endif
      if(present(CLOCK)) then
         STATE%CLOCK=CLOCK
      endif
      if(present(NAME)) then
         STATE%COMPNAME=NAME
         if (.not. allocated(state%full_name)) then
            state%full_name = trim(name)
         end if
      endif
      if(present(Cf)) then
         STATE%CF=CF
      endif
      if(present(ConfigFile)) then
         State%CF = ESMF_ConfigCreate(_RC)
         call ESMF_ConfigLoadFile(State%CF,ConfigFile,_RC)
      endif
      if (present(component)) then
         call state%set_component(component)
         call state%set_logger(logging%get_logger(state%full_name))
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericStateSet
Call graph
mapl_genericstateset calls ESMF_ConfigCreate, ESMF_ConfigLoadFile, get_composite, get_logger, initialize, mapl_return, mapl_verify, set_component, set_composite, set_logger
initialize calls initialize_global_time_profiler
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
initialize_global_time_profiler calls get_global_time_profiler
mapl_throw_exception calls initialize
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
mapl_genericstatesetfromgc calls mapl_genericstateset
initialize_gc calls mapl_set
mapl_capgridcompcreate calls mapl_set
run_component_driver calls mapl_set
initialize_cap_gc calls mapl_capgridcompcreate
main calls run_component_driver
run_model calls initialize_cap_gc
comp_testing_driver calls main