MAPL_IsStateEmpty – MAPL
MAPL_IsStateEmpty Function
13 statements
Source File
private function MAPL_IsStateEmpty(state, rc) result(empty)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   function MAPL_IsStateEmpty(state, rc) result(empty)
      type(ESMF_State), intent(in) :: state
      integer, optional, intent(out) :: rc
      logical                        :: empty
      integer :: itemcount
      integer :: status
      empty = .true.
      call ESMF_StateGet(state,itemcount=itemcount,rc=status)
      _VERIFY(status)
      if (itemcount /= 0) empty = .false.
      _RETURN(ESMF_SUCCESS)
   end function MAPL_IsStateEmpty
Call graph
mapl_isstateempty calls esmf_stateget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_esmfstatereadfromfile calls mapl_isstateempty
mapl_esmfstatewritetofile calls mapl_isstateempty
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore
mapl_genericwrapper calls record_component