MAPL_ExtDataVerticalInterpolate – MAPL
MAPL_ExtDataVerticalInterpolate Subroutine
105 statements
Source File
private subroutine MAPL_ExtDataVerticalInterpolate(MAPLExtState, item, import, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_ExtData_State), intent(inout) :: MAPLExtState
type(PrimaryExport), intent(inout) :: item
type(ESMF_State), intent(in) :: import
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataVerticalInterpolate(MAPLExtState,item,import,rc)
     type(MAPL_ExtData_State), intent(inout) :: MAPLExtState
     type(PrimaryExport), intent(inout)     :: item
     type(ESMF_State), intent(in)           :: import
     integer, optional,   intent(out  )     :: rc
     integer :: status
     type(ESMF_Field) :: src_field, dst_field, src_ps, dst_ple, q_field
     character(len=:), allocatable :: src_ps_name, src_q_name
     integer :: fieldRank
     real, pointer :: dst_ptr3d(:,:,:), src_ptr3d(:,:,:), src_ps_ptr(:,:), dst_ple_ptr(:,:,:)
     real, pointer :: src_q(:,:,:), dst_q(:,:,:)
     real, allocatable :: src_ple_ptr(:,:,:)
     real :: molecular_weight
     character(len=:), allocatable :: units_in, units_out
     integer :: constituent_type
     if (item%vcoord%vertical_type == NO_COORD &
        .or. (.not.item%delivered_item)) then
        _RETURN(_SUCCESS)
     end if
     if (item%allow_vertical_regrid .and. (item%vcoord%vertical_type == model_pressure)) then
        call extdata_lgr%info('ExtData vertical conservative regridding of '//trim(item%name))
        call ESMF_StateGet(import, "PLE", dst_ple, _RC)
        call ESMF_FieldGet(dst_ple,farrayPtr=dst_ple_ptr,_RC)
        src_ps_name = item%vcoord%surf_name//"_"//trim(item%vcomp1)
        call ESMF_StateGet(MAPLExtState%ExtDataState, src_ps_name, src_ps, _RC)
        call ESMF_FieldGet(src_ps, farrayPtr=src_ps_ptr, _RC)
        src_ple_ptr = item%vcoord%compute_ple(src_ps_ptr, _RC)
        call ESMF_StateGet(MAPLExtState%ExtDataState,trim(item%vcomp1),dst_field,_RC)
        call ESMF_FieldGet(dst_field,rank=fieldRank,_RC)
        _ASSERT(fieldRank==3, "Trying to regrid non 3D field")
        call ESMF_FieldGet(dst_field,farrayPtr=dst_ptr3d,_RC)
        call ESMF_FieldBundleGet(item%t_interp_bundle, trim(item%vcomp1), field=src_field, _RC)
        call ESMF_FieldGet(src_field,farrayPtr=src_ptr3d,_RC)
        units_in = get_field_units(src_field, _RC)
        units_out = get_field_units(dst_field, _RC)
        _ASSERT(units_in == units_out, "Going to vertical regrid and units of source and destination do not match")
        units_in = strip_per_second(units_in)
        if (units_in == mol_per_mol) constituent_type = volume_mixing
        if (units_in == kg_per_kg) constituent_type = mass_mixing
        if (units_in == emission_units) constituent_type = emission
        select case (constituent_type)
        case(mass_mixing)
           call vremap_conserve_mass_mixing(src_ple_ptr,src_ptr3d,dst_ple_ptr,dst_ptr3d)
        case(emission)
           call vremap_conserve_emission(src_ple_ptr,src_ptr3d,dst_ple_ptr,dst_ptr3d)
        case (volume_mixing)
           call ESMF_AttributeGet(src_field,name='molecular_weight',value=molecular_weight, _RC)
           call ESMF_StateGet(import, 'Q', q_field, _RC)
           call ESMF_FieldGet(q_field,0, farrayPtr=dst_q, _RC)
           src_q_name = item%aux_q//"_"//trim(item%vcomp1)
           call ESMF_StateGet(MAPLExtState%ExtDataState, src_q_name, q_field, _RC)
           call ESMF_FieldGet(q_field,0, farrayPtr=src_q, _RC)
           call vremap_conserve_vol_mixing(src_ple_ptr, src_q, molecular_weight, src_ptr3d, dst_ple_ptr, dst_q, dst_ptr3d, _RC)
        case default
           _FAIL(trim(units_in)//" not supported for vertical regridding")
        end select
     else if (item%vcoord%vertical_type == simple_coord .and. item%do_fill) then
        call extdata_lgr%info('ExtData filling destination with available layers of source for '//trim(item%name))
        call ESMF_FieldBundleGet(item%t_interp_bundle, trim(item%vcomp1), field=src_field, _RC)
        call ESMF_StateGet(MAPLExtState%ExtDataState,trim(item%vcomp1),dst_field,_RC)
        call MAPL_ExtDataFillField(item, dst_field, src_field, _RC)
     end if
     _RETURN(ESMF_SUCCESS)
    contains
    function get_field_units(field, rc) result(field_units)
       character(len=:), allocatable :: field_units
       type(ESMF_Field), intent(in) :: field
       integer, optional, intent(out) :: rc
       integer :: status
       character(len=ESMF_MAXSTR) :: temp_char
       call ESMF_AttributeGet(field,name='UNITS',value=temp_char, _RC)
       field_units = temp_char
    end function get_field_units
    function strip_per_second(input_units) result(output_units)
       character(len=:), allocatable :: output_units
       character(len=*), intent(in) :: input_units
       integer :: idx
       idx = index(input_units, per_second)
       output_units = input_units
       if (idx > 0) output_units = input_units(1:idx-1)
    end function
  end subroutine MAPL_ExtDataVerticalInterpolate
Call graph
mapl_extdataverticalinterpolate calls ESMF_AttributeGet, esmf_fieldbundleget, esmf_fieldget, esmf_stateget, mapl_assert, compute_ple, info, mapl_extdatafillfield, mapl_return, mapl_verify, vremap_conserve_emission, vremap_conserve_mass_mixing, vremap_conserve_vol_mixing
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
compute_ple calls mapl_return
mapl_extdatafillfield calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vremap_conserve_emission calls gmap
vremap_conserve_mass_mixing calls gmap
vremap_conserve_vol_mixing calls mapl_return, gmap
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run_ calls mapl_extdataverticalinterpolate