MAPL_CopyFriendlinessInState – MAPL
MAPL_CopyFriendlinessInState Subroutine
19 statements
Source File
private subroutine MAPL_CopyFriendlinessInState(STATEOUT, nameOUT, STATEIN, nameIN, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATEOUT
character(len=*), intent(in) :: nameOUT
type(ESMF_State), intent(in) :: STATEIN
character(len=*), intent(in) :: nameIN
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_CopyFriendlinessInState
Source Code
   subroutine MAPL_CopyFriendlinessInState(STATEOUT, NAMEOUT,STATEIN,NAMEIN,RC)
      type(ESMF_STATE),      intent(INOUT) :: STATEOUT
      character(len=*),      intent(IN   ) :: nameOUT
      type(ESMF_STATE),      intent(IN   ) :: STATEIN
      character(len=*),      intent(IN   ) :: nameIN
      integer,    optional,  intent(  OUT) :: rc
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_CopyFriendlinessInState"
      integer                               :: status
      type(ESMF_FIELD)                      :: FIELDIN
      type(ESMF_FIELD)                      :: FIELDOUT
      call ESMF_StateGet(STATEIN ,NAMEIN ,FIELDIN ,RC=status)
      _VERIFY(status)
      call ESMF_StateGet(STATEOUT,NAMEOUT,FIELDOUT,RC=status)
      _VERIFY(status)
      call  MAPL_CopyFriendlinessInField(FIELDOUT,FIELDIN,RC=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_CopyFriendlinessInState
Call graph
mapl_copyfriendlinessinstate calls esmf_stateget, mapl_copyfriendlinessinfield, mapl_return, mapl_verify
mapl_copyfriendlinessinfield calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_AttributeSet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_copyfriendliness calls mapl_copyfriendlinessinstate