MAPL_SetFieldTimeFromState – MAPL
MAPL_SetFieldTimeFromState Module Subroutine
15 statements
Source File
module subroutine MAPL_SetFieldTimeFromState(STATE, Fieldname, TIME, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
character(len=*), intent(in) :: Fieldname
type(ESMF_Time), intent(inout) :: TIME
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_SetFieldTimeFromState
Source Code
  module subroutine  MAPL_SetFieldTimeFromState ( STATE, Fieldname, TIME, RC )
    type(ESMF_STATE),        intent(INOUT) :: STATE
    character(len=*),        intent(IN   ) :: Fieldname
    type(ESMF_Time),         intent(INOUT) :: TIME !ALT: IN
    integer, optional,       intent(  OUT) :: RC
    character(len=ESMF_MAXSTR),parameter   :: IAm=" MAPL_SetFieldTimeFromState"
    integer                                :: STATUS
    type(ESMF_FIELD)                       :: FIELD
    call ESMF_StateGet (STATE, FIELDNAME, FIELD, RC=STATUS)
    _VERIFY(STATUS)
    call MAPL_FieldSetTime  (FIELD, TIME,             RC=STATUS)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine  MAPL_SetFieldTimeFromState
Call graph
mapl_setfieldtimefromstate calls esmf_stateget, mapl_return, mapl_verify, mapl_fieldsettime, mapl_setfieldtimefromstate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldsettime calls mapl_setfieldtimefromstate, mapl_setfieldtimefromfield
mapl_throw_exception calls initialize
mapl_setfieldtimefromfield calls mapl_setfieldtimefromfield, mapl_return, mapl_verify, esmf_timeget, esmf_attributeset
mapl_climupdate calls mapl_fieldsettime