MAPL_StateVarReadNCPar – MAPL
MAPL_StateVarReadNCPar Subroutine
262 statements
Source File
private subroutine MAPL_StateVarReadNCPar(filename, STATE, ARRDES, bootstrapable, NAME, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
type(ESMF_State), intent(inout) :: STATE
type(ArrDescr), intent(inout) :: ARRDES
logical, intent(in) :: bootstrapable
character(len=*), intent(in), optional :: NAME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_StateVarReadNCPar(filename, STATE, arrdes, bootstrapable, NAME, RC)
    character(len=*)            , intent(IN   ) :: filename
    type (ESMF_State)           , intent(INOUT) :: STATE
    type(ArrDescr)              , intent(INOUT) :: ARRDES
    logical                     , intent(IN   ) :: bootstrapable
    character(len=*),   optional, intent(IN   ) :: NAME
    integer,            optional, intent(  OUT) :: RC
! Local vars
    type (ESMF_FieldBundle)              :: bundle
    type (ESMF_Field)                    :: field
    integer                              :: status
    integer                              :: I, K
    integer                              :: J, ITEMCOUNT
    type (ESMF_StateItem_Flag), pointer  :: ITEMTYPES(:)
    character(len=ESMF_MAXSTR ), pointer :: ITEMNAMES(:)
    logical, pointer                     :: DOIT(:)
    integer                            :: ind
    logical                            :: skipReading
    integer                            :: RST
    character(len=ESMF_MAXSTR)         :: FieldName, BundleName
    type (ESMF_Field)                  :: new_field
    type (ESMF_FieldBundle)            :: bundle_read
    integer                            :: nBundle
    logical                            :: tile
    integer                            :: nVarFile, ncid
    character(len=ESMF_MAXSTR), pointer :: VarNamesFile(:) => null()
    type(ESMF_VM)                      :: VM
    logical                            :: foundInFile
    integer                            :: dna
    logical                            :: bootstrapable_
    logical                            :: isPresent
    logical                            :: is_test_framework, restore_export
    character(len=:), allocatable      :: fname_by_face
    ! get a list of variables in the file so we can skip if the
    ! variable in the state is not in the file and it is bootstrapable
    ! will just let root do this since everybody will need it
    ! and avoid complications with doing later on when only readers_comm has opened file
    call ESMF_VMGetCurrent(VM,rc=status)
    _VERIFY(STATUS)
    if (MAPL_AM_I_Root()) then
       if(arrdes%read_restart_by_face) then
          fname_by_face = get_fname_by_face(filename, 1)
          status = NF90_OPEN(trim(fname_by_face),NF90_NOWRITE, ncid) ! just pick one
          _VERIFY(STATUS)
       else
          status = NF90_OPEN(trim(filename),NF90_NOWRITE, ncid)
          _VERIFY(STATUS)
       endif
       status = NF90_INQUIRE(ncid, nVariables=nVarFile)
       _VERIFY(STATUS)
    end if
    call MAPL_CommsBcast(vm, nVarFile, n=1, ROOT=MAPL_Root, rc=status)
    _VERIFY(STATUS)
    allocate(VarNamesFile(nVarFile),stat=status)
    _VERIFY(STATUS)
    if (MAPL_AM_I_Root()) then
       do i=1,nVarFile
          status = NF90_INQUIRE_VARIABLE(ncid, i, VarNamesFile(i))
          _VERIFY(STATUS)
       end do
       status = NF90_CLOSE(ncid)
       _VERIFY(STATUS)
    end if
    do i=1,nVarFile
       call MAPL_CommsBcast(vm, VarNamesFile(i), N=ESMF_MAXSTR, ROOT=MAPL_Root, rc=status)
       _VERIFY(STATUS)
    end do
    call ESMF_StateGet(STATE,ITEMCOUNT=ITEMCOUNT,RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(ITEMCOUNT>0, 'itemcount should be > 0')
    allocate(ITEMNAMES(ITEMCOUNT),STAT=STATUS)
    _VERIFY(STATUS)
    allocate(ITEMTYPES(ITEMCOUNT),STAT=STATUS)
    _VERIFY(STATUS)
    allocate(     DOIT(ITEMCOUNT),STAT=STATUS)
    _VERIFY(STATUS)
    call ESMF_StateGet(STATE,ITEMNAMELIST=ITEMNAMES,&
                       ITEMTYPELIST=ITEMTYPES,RC=STATUS)
    _VERIFY(STATUS)
    if(present(NAME)) then
       DOIT = ITEMNAMES==NAME
       _ASSERT(count(DOIT)/=0, 'count(DOIT) should not be 0')
    else
       DOIT = .true.
    endif
    bundle_read = ESMF_FieldBundleCreate(rc=STATUS)
    _VERIFY(STATUS)
    call ESMF_FieldBundleSet(bundle_read,grid=arrdes%grid,rc=STATUS)
    _VERIFY(STATUS)
    do I = 1, ITEMCOUNT
       if (DOIT(I)) then
          if (ITEMTYPES(I) == ESMF_StateItem_FieldBundle) then
             call ESMF_StateGet(state, itemnames(i), bundle, rc=status)
             _VERIFY(STATUS)
             skipReading = .false.
             call ESMF_AttributeGet(bundle, name='RESTART', isPresent=isPresent, rc=status)
             _VERIFY(STATUS)
             if (isPresent) then
                call ESMF_AttributeGet(bundle, name='RESTART', value=RST, rc=status)
                _VERIFY(STATUS)
             else
                RST = MAPL_RestartOptional
             end if
             skipReading = (RST == MAPL_RestartSkip .or.   &
                            RST == MAPL_RestartSkipInitial)
             call ESMF_AttributeGet(state, name='MAPL_TestFramework', isPresent=isPresent, _RC)
             if (isPresent) then
                call ESMF_AttributeGet(state, name='MAPL_TestFramework', value=is_test_framework, _RC)
                if (is_test_framework) skipReading = .false.
             end if
             if (skipReading) cycle
             bootstrapable_ = bootstrapable .and. (RST == MAPL_RestartOptional)
             call ESMF_FieldBundleGet(bundle, fieldCount=nBundle, rc=STATUS)
             _VERIFY(STATUS)
             call ESMF_FieldBundleGet(bundle, name=BundleName, rc=status)
             _VERIFY(STATUS)
             DO J = 1,nBundle
               call ESMF_FieldBundleGet(bundle, fieldIndex=J, field=field, rc=status)
               _VERIFY(STATUS)
               call ESMF_FieldGet(field,name=FieldName,rc=status)
               _VERIFY(STATUS)
               skipReading = .false.
               call ESMF_AttributeGet(field, name='RESTART', isPresent=isPresent, rc=status)
               _VERIFY(STATUS)
               if (isPresent) then
                  call ESMF_AttributeGet(field, name='RESTART', value=RST, rc=status)
                  _VERIFY(STATUS)
               else
                  RST = MAPL_RestartOptional
               end if
               skipReading = (RST == MAPL_RestartSkip)
               call ESMF_AttributeGet(state, name='MAPL_TestFramework', isPresent=isPresent, _RC)
               if (isPresent) then
                  call ESMF_AttributeGet(state, name='MAPL_TestFramework', value=is_test_framework, _RC)
                  if (is_test_framework) skipReading = .false.
               end if
               if (skipReading) cycle
               ind= index(FieldName, '::')
               if (ind> 0) then
                 FieldName = trim(FieldName(ind+2:))
               end if
               ! Tack on BundleName to distiguish duplicate FieldNames in different Bundles (PCHEM for instance)
               FieldName = trim(BundleName) //'_'// trim(FieldName)
               ! now check if the fieldname is in the list of available fields
               ! -------------------------------------------------------------
               foundInFile = .false.
               do k=1,nVarFile
                  if (trim(FieldName) == trim(VarNamesFile(k))) then
                     FoundInFile = .true.
                     exit
                  end if
               end do
               if (foundInFile) then
                  new_field = MAPL_FieldCreate(Field,FieldName,rc=status)
                  _VERIFY(STATUS)
                  call MAPL_FieldBundleAdd(bundle_read,new_field,rc=status)
                  _VERIFY(STATUS)
               else
                  if (bootStrapable_ .and. (RST == MAPL_RestartOptional)) then
                     call WRITE_PARALLEL("  Bootstrapping Variable: "//trim(FieldName)//" in "//trim(filename))
                     call ESMF_AttributeSet ( field, name='RESTART', &
                             value=MAPL_RestartBootstrap, rc=status)
                  else
                     restore_export = .false.
                     call ESMF_AttributeGet(state, name='MAPL_RestoreExport', isPresent=isPresent, _RC)
                     if (isPresent) then
                        call ESMF_AttributeGet(state, name='MAPL_RestoreExport', value=restore_export, _RC)
                     end if
                     if (restore_export) then
                        if (mapl_am_i_root()) print*, trim(fieldName), " not found in ", trim(filename), ". Skipping reading..."
                     else
                        _FAIL( "  Could not find field "//trim(FieldName)//" in "//trim(filename))
                     end if
                  end if
               end if
             ENDDO
          else if (ITEMTYPES(I) == ESMF_StateItem_Field) then
             call ESMF_StateGet(state, itemnames(i), field, rc=status)
             _VERIFY(STATUS)
             FieldName = trim(itemnames(i))
               ind= index(FieldName, '::')
               if (ind> 0) then
                 FieldName = trim(FieldName(ind+2:))
               end if
             skipReading = .false.
             call ESMF_AttributeGet(field, name='RESTART', isPresent=isPresent, rc=status)
             _VERIFY(STATUS)
             if (isPresent) then
                call ESMF_AttributeGet(field, name='RESTART', value=RST, rc=status)
                _VERIFY(STATUS)
             else
                RST = MAPL_RestartOptional
             end if
             skipReading = (RST == MAPL_RestartSkip)
             call ESMF_AttributeGet(state, name='MAPL_TestFramework', isPresent=isPresent, _RC)
             if (isPresent) then
                call ESMF_AttributeGet(state, name='MAPL_TestFramework', value=is_test_framework, _RC)
                if (is_test_framework) skipReading = .false.
             end if
             if (skipReading) cycle
             call ESMF_AttributeGet(field, name='doNotAllocate', isPresent=isPresent, rc=status)
             _VERIFY(STATUS)
             if (isPresent) then
                call ESMF_AttributeGet(field, name='doNotAllocate', value=DNA, rc=status)
                _VERIFY(STATUS)
                skipReading = (DNA /= 0)
             end if
             call ESMF_AttributeGet(state, name='MAPL_TestFramework', isPresent=isPresent, _RC)
             if (isPresent) then
                call ESMF_AttributeGet(state, name='MAPL_TestFramework', value=is_test_framework, _RC)
                if (is_test_framework) skipReading = .false.
             end if
             if (skipReading) cycle
             ! now check if the field is in the list of available fields
             ! ---------------------------------------------------------
             foundInFile = .false.
             do k=1,nVarFile
                if (trim(Fieldname) == trim(VarNamesFile(k))) then
                   FoundInFile = .true.
                   exit
                end if
             end do
             if (foundInFile) then
                call MAPL_FieldBundleAdd(bundle_read,field,rc=status)
                _VERIFY(STATUS)
             else
                if (bootStrapable .and. (RST == MAPL_RestartOptional)) then
                    call WRITE_PARALLEL("  Bootstrapping Variable: "//trim(FieldName)//" in "//trim(filename))
                    call ESMF_AttributeSet ( field, name='RESTART', &
                            value=MAPL_RestartBootstrap, rc=status)
                else
                   restore_export = .false.
                   call ESMF_AttributeGet(state, name='MAPL_RestoreExport', isPresent=isPresent, _RC)
                   if (isPresent) then
                      call ESMF_AttributeGet(state, name='MAPL_RestoreExport', value=restore_export, _RC)
                   end if
                   if (restore_export) then
                      if (mapl_am_i_root()) print*, trim(fieldName), " not found in ", trim(filename), ". Skipping reading..."
                   else
                      _FAIL( "  Could not find field "//trim(FieldName)//" in "//trim(filename))
                   end if
                end if
             end if
          end if
       end if
    end do
    tile = arrdes%tile
    call ESMF_AttributeGet(state, name='MAPL_RestoreExport', isPresent=isPresent, _RC)
    if (isPresent) then
       call ESMF_AttributeGet(state, name='MAPL_RestoreExport', value=restore_export, _RC)
       call ESMF_AttributeSet(bundle_read, name="MAPL_RestoreExport", value=restore_export, _RC)
    end if
    call MAPL_VarReadNCPar(Bundle_Read, arrdes, filename, rc=status)
    _VERIFY(STATUS)
    deallocate(ITEMNAMES)
    deallocate(ITEMTYPES)
    deallocate(     DOIT)
    deallocate(VarNamesFile)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_StateVarReadNCPar
Call graph
mapl_statevarreadncpar calls ESMF_AttributeGet, ESMF_AttributeSet, ESMF_VMGetCurrent, esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_am_i_root, mapl_assert, mapl_commsbcast, mapl_fieldbundleadd, mapl_fieldcreate, mapl_varreadncpar, write_parallel, nf90_close, nf90_inquire, nf90_inquire_variable, nf90_open, get_fname_by_face, mapl_return, mapl_verify
mapl_varreadncpar calls mapl_statevarreadncpar, mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d
mapl_arrayreadncpar_1d calls mapl_varreadncpar
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore