MAPL_AllocateCoupling – MAPL
MAPL_AllocateCoupling Module Subroutine
64 statements
Source File
module subroutine MAPL_AllocateCoupling(field, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  module subroutine MAPL_AllocateCoupling(field, rc)
    type(ESMF_Field),  intent(INOUT) :: field
    integer, optional, intent(  OUT) :: rc
    integer                                 :: status
    character(len=ESMF_MAXSTR), parameter   :: IAm='MAPL_AllocateCouplingFromField'
    type(ESMF_FieldStatus_Flag)             :: fieldStatus
    integer          :: dims
    integer          :: location
    integer          :: knd
    integer, pointer :: ungrd(:)
    integer          :: hw
    integer          :: ungrd_cnt
    logical          :: has_ungrd
    logical          :: defaultProvided
    real             :: default_value
    call ESMF_FieldGet(field, status=fieldStatus, rc=status)
    _VERIFY(STATUS)
    if (fieldStatus /= ESMF_FIELDSTATUS_COMPLETE) then
       !ALT: if the attributeGet calls fail, this would very likely indicate
       !     that the field was NOT created by MAPL (or something terrible happened)
       !     For now we just abort
       call ESMF_AttributeGet(FIELD, NAME='DIMS', VALUE=DIMS, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_AttributeGet(FIELD, NAME='VLOCATION', VALUE=LOCATION, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_AttributeGet(FIELD, NAME='HALOWIDTH', VALUE=HW, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_AttributeGet(FIELD, NAME='PRECISION', VALUE=KND, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_AttributeGet(FIELD, NAME='DEFAULT_PROVIDED', value=defaultProvided, RC=STATUS)
       _VERIFY(STATUS)
       if(defaultProvided) then
          call ESMF_AttributeGet(FIELD, NAME='DEFAULT_VALUE', value=default_value, RC=STATUS)
          _VERIFY(STATUS)
       end if
       call ESMF_AttributeGet(FIELD, NAME='UNGRIDDED_DIMS', isPresent=has_ungrd, RC=STATUS)
       _VERIFY(STATUS)
       if (has_ungrd) then
          call ESMF_AttributeGet(FIELD, NAME='UNGRIDDED_DIMS', itemcount=UNGRD_CNT, RC=STATUS)
          _VERIFY(STATUS)
          allocate(ungrd(UNGRD_CNT), stat=status)
          _VERIFY(STATUS)
          call ESMF_AttributeGet(FIELD, NAME='UNGRIDDED_DIMS', valueList=UNGRD, RC=STATUS)
          _VERIFY(STATUS)
          if (defaultProvided) then
             call MAPL_FieldAllocCommit(field, dims=dims, location=location, typekind=knd, &
                  hw=hw, ungrid=ungrd, default_value=default_value, rc=status)
             _VERIFY(STATUS)
          else
             call MAPL_FieldAllocCommit(field, dims=dims, location=location, typekind=knd, &
                  hw=hw, ungrid=ungrd, rc=status)
             _VERIFY(STATUS)
          end if
       else
          if (defaultProvided) then
             call MAPL_FieldAllocCommit(field, dims=dims, location=location, typekind=knd, &
                  hw=hw, default_value=default_value, rc=status)
             _VERIFY(STATUS)
          else
             call MAPL_FieldAllocCommit(field, dims=dims, location=location, typekind=knd, &
                  hw=hw, rc=status)
             _VERIFY(STATUS)
          end if
       end if
       if (has_ungrd) then
          deallocate(ungrd)
       end if
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_AllocateCoupling
Call graph
mapl_allocatecoupling calls ESMF_AttributeGet, esmf_fieldget, mapl_fieldalloccommit, mapl_return, mapl_verify, mapl_allocatecoupling
mapl_fieldalloccommit calls mapl_fieldalloccommit, esmf_fieldget, mapl_return, mapl_verify, ESMF_GridGet, esmf_fieldemptycomplete, mapl_assert, mapl_attributeset, mapl_gridget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_attributeset calls mapl_bundleattseti4, mapl_fieldattseti4, mapl_stateattseti4
mapl_gridget calls ESMF_AttributeGet, mapl_return, mapl_verify, ESMF_GridGet, mapl_gridhasde
esmfl_stategetfield calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_1 calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls mapl_allocatecoupling
initialize calls mapl_allocatecoupling
mapl_bundlereadncpar calls mapl_allocatecoupling
mapl_statecreatefromspecnew calls mapl_allocatecoupling
realize_fields calls mapl_allocatecoupling
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_varreadncpar calls mapl_bundlereadncpar
mapl_genericinitialize calls mapl_statecreatefromspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
stateregrid calls esmfl_stategetfield