MAPL_ExtDataVerticalInterpolate – MAPL
MAPL_ExtDataVerticalInterpolate Subroutine
74 statements
Source File
private subroutine MAPL_ExtDataVerticalInterpolate(ExtState, item, filec, current_time, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_ExtData_State), intent(inout) :: ExtState
type(PrimaryExport), intent(inout) :: item
integer, intent(in) :: filec
type(ESMF_Time), intent(in) :: current_time
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataVerticalInterpolate(ExtState,item,filec,current_time,rc)
     type(MAPL_ExtData_State), intent(inout) :: ExtState
     type(PrimaryExport), intent(inout)     :: item
     integer,             intent(in   )     :: filec
     type(ESMF_Time),     intent(in   )     :: current_time
     integer, optional,   intent(out  )     :: rc
     integer :: status
     integer :: id_ps
     type(ESMF_Field) :: field, newfield,psF
     if (item%do_VertInterp) then
        if (trim(item%importVDir)/=trim(item%fileVDir)) then
           call MAPL_ExtDataFlipVertical(item,filec,rc=status)
           _VERIFY(status)
        end if
        if (item%vartype == MAPL_fieldItem) then
           call MAPL_ExtDataGetBracket(item,filec,newField,getRL=.true.,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,Field,rc=status)
           _VERIFY(STATUS)
           id_ps = ExtState%primary%get_item_index("PS",current_time,_RC)
           call MAPL_ExtDataGetBracket(ExtState%primary%item(id_ps),filec,field=psF,rc=status)
           _VERIFY(STATUS)
           call vertInterpolation_pressKappa(field,newfield,psF,item%levs,MAPL_UNDEF,rc=status)
           _VERIFY(STATUS)
        else if (item%vartype == MAPL_VectorField) then
           id_ps = ExtState%primary%get_item_index("PS",current_time,_RC)
           call MAPL_ExtDataGetBracket(ExtState%primary%item(id_ps),filec,field=psF,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,newField,getRL=.true.,vcomp=1,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,Field,vcomp=1,rc=status)
           _VERIFY(STATUS)
           call vertInterpolation_pressKappa(field,newfield,psF,item%levs,MAPL_UNDEF,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,newField,getRL=.true.,vcomp=2,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,Field,vcomp=2,rc=status)
           _VERIFY(STATUS)
           call vertInterpolation_pressKappa(field,newfield,psF,item%levs,MAPL_UNDEF,rc=status)
           _VERIFY(STATUS)
        end if
     else if (item%do_Fill) then
        if (item%vartype == MAPL_fieldItem) then
           call MAPL_ExtDataGetBracket(item,filec,newField,getRL=.true.,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,Field,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataFillField(item,field,newfield,rc=status)
           _VERIFY(STATUS)
        else if (item%vartype == MAPL_VectorField) then
           call MAPL_ExtDataGetBracket(item,filec,newField,getRL=.true.,vcomp=1,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,Field,vcomp=1,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataFillField(item,field,newfield,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,newField,getRL=.true.,vcomp=2,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataGetBracket(item,filec,Field,vcomp=2,rc=status)
           _VERIFY(STATUS)
           call MAPL_ExtDataFillField(item,field,newfield,rc=status)
           _VERIFY(STATUS)
        end if
     else
        if (trim(item%importVDir)/=trim(item%fileVDir)) then
           call MAPL_ExtDataFlipVertical(item,filec,rc=status)
           _VERIFY(status)
        end if
     end if
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataVerticalInterpolate
Call graph
mapl_extdataverticalinterpolate calls get_item_index, mapl_extdatafillfield, mapl_extdataflipvertical, mapl_extdatagetbracket, mapl_return, mapl_verify, vertinterpolation_presskappa
get_item_index calls mapl_return, at, mapl_assert
mapl_extdatafillfield calls mapl_return, mapl_verify, esmf_fieldget
mapl_extdataflipvertical calls mapl_extdatagetbracket, mapl_return, mapl_verify, esmf_fieldget
mapl_extdatagetbracket calls mapl_return, mapl_verify, get_parameters
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
vertinterpolation_presskappa calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_UtilStringLowerCase, esmf_fieldget, mapl_assert, interpval, mapl_gridget, searchverticallocations
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
get_parameters calls mapl_return, mapl_assert
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_DELayoutGet, ESMF_DistGridGet
run_ calls mapl_extdataverticalinterpolate