MAPL_StateAddExportSpecFrmAll – MAPL
MAPL_StateAddExportSpecFrmAll Subroutine
56 statements
Source File
private subroutine MAPL_StateAddExportSpecFrmAll(STATE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateAddExportSpecFrmAll
Source Code
   subroutine MAPL_StateAddExportSpecFrmAll ( STATE, RC )
      !ARGUMENTS:
      type (MAPL_MetaComp)            , intent(INOUT)   :: STATE
      integer            , optional   , intent(OUT)     :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddExportSpecFrmAll"
      integer                               :: status
      type (MAPL_VarSpec),      pointer     :: SPECS(:)
      type (MAPL_VarSpec),      pointer     :: MYSPEC(:) => null()
      integer                               :: I
      integer                               :: N
      character(len=ESMF_MAXSTR)            :: NAME
      character(len=ESMF_MAXSTR)            :: GCNAME
      character (len=ESMF_MAXSTR)           :: LONG_NAME
      character (len=ESMF_MAXSTR)           :: UNITS
      integer                               :: FIELD_TYPE
      integer                               :: STAGGERING
      integer                               :: ROTATION
      integer                               :: DIMS
      integer                               :: VLOCATION
      integer                               :: NUM_SUBTILES
      integer                               :: ACCMLT_INTERVAL
      integer                               :: COUPLE_INTERVAL
      integer                               :: STAT
      type(ESMF_Field), pointer             :: FIELD
      type(ESMF_GridComp), pointer :: gridcomp
      if (.not. STATE%get_num_children() > 0) then
         _RETURN(ESMF_FAILURE)
      end if
      do N = 1, STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(N)
         call MAPL_GridCompGetVarSpecs(gridcomp, EXPORT=SPECS, RC=status)
         _VERIFY(status)
         call ESMF_GridCompGet( STATE%GET_CHILD_GRIDCOMP(N), name=GCNAME, RC=status )
         _VERIFY(status)
         do I = 1, size(SPECS)
            call MAPL_VarSpecGet(SPECS(I), SHORT_NAME=NAME,  &
                 LONG_NAME  = LONG_NAME,                                  &
                 UNITS      = UNITS,                                      &
                 FIELD_TYPE = FIELD_TYPE,                                 &
                 STAGGERING = STAGGERING,                                 &
                 ROTATION = ROTATION,                                     &
                 DIMS       = DIMS,                                       &
                 VLOCATION  = VLOCATION,                                  &
                 NUM_SUBTILES=NUM_SUBTILES,                               &
                 STAT       = STAT,                                       &
                 ACCMLT_INTERVAL= ACCMLT_INTERVAL,                     &
                 COUPLE_INTERVAL= COUPLE_INTERVAL,                       &
                 RC=status  )
            _VERIFY(status)
            call MAPL_VarSpecGet(SPECS(I), FIELDPTR = FIELD, RC=status  )
            _VERIFY(status)
            call MAPL_VarSpecCreateInList(MYSPEC,                         &
                 SHORT_NAME=trim(NAME)//'_from_' // trim(GCNAME),         &
                 LONG_NAME  = LONG_NAME,                                  &
                 UNITS      = UNITS,                                      &
                 FIELD_TYPE = FIELD_TYPE,                                 &
                 STAGGERING = STAGGERING,                                 &
                 ROTATION = ROTATION,                                     &
                 DIMS       = DIMS,                                       &
                 VLOCATION  = VLOCATION,                                  &
                 NUM_SUBTILES=NUM_SUBTILES,                               &
                 STAT       = STAT,                                       &
                 ACCMLT_INTERVAL= ACCMLT_INTERVAL,                     &
                 COUPLE_INTERVAL= COUPLE_INTERVAL,                       &
                 RC=status  )
            _VERIFY(status)
            call MAPL_VarSpecSet(MYSPEC(1), FIELDPTR = FIELD, RC=status  )
            _VERIFY(status)
            call MAPL_VarSpecAddRefToList(STATE%COMPONENT_SPEC%EXPORT, MYSPEC(1), RC=status)
            if (status /= MAPL_DuplicateEntry) then
               _VERIFY(status)
            else
               _RETURN(ESMF_FAILURE) ! ALT this needs to be revisited
            endif
            NULLIFY(MYSPEC)
            !ALT specDestroy ?; otherwise we have small mem leak
            !ALT    call MAPL_AddConnectivity ???
         end do
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddExportSpecFrmAll
Call graph
mapl_stateaddexportspecfrmall calls mapl_return, mapl_gridcompgetvarspecs, mapl_verify, esmf_gridcompget, mapl_varspecget, mapl_varspeccreateinlist, mapl_varspecset, mapl_varspecaddreftolist
mapl_return calls get_error_message, mapl_throw_exception
mapl_gridcompgetvarspecs calls mapl_return, mapl_verify, esmf_gridcompget, mapl_internalstateretrieve, mapl_stategetvarspecs
mapl_verify calls mapl_throw_exception
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetstateptr, mapl_varspecgetfieldptr, mapl_varspecgetbundleptr, mapl_varspecgetnew
mapl_varspeccreateinlist calls mapl_return, mapl_verify, mapl_assert, mapl_varspecgetindex
mapl_varspecset calls mapl_varspecsetnew
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_varspecsetnew calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecaddreffromitem calls mapl_return, mapl_verify, mapl_varspecgetindex, mapl_varspecprint
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_stategetvarspecs calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_throw_exception calls initialize
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecaddreffromlist calls mapl_return, mapl_verify, mapl_varspecaddreffromitem
mapl_addexportspec calls mapl_stateaddexportspecfrmall
setservices calls mapl_addexportspec, setservices
addnewspec calls mapl_addexportspec