MAPL_VRFYt – MAPL
MAPL_VRFYt Function
8 statements
Source File
private function MAPL_VRFYt(A, text, iam, line, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A
character(len=*), intent(in) :: text
character(len=*), intent(in) :: iam
integer, intent(in) :: line
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Source Code
   logical function MAPL_VRFYt(A,text,iam,line,rc)
      integer,           intent(IN ) :: A
      character(len=*),  intent(IN ) :: iam,text
      integer,           intent(IN ) :: line
      integer, optional, intent(OUT) :: RC
        MAPL_VRFYt =  MAPL_VRFY(A,iam,line,rc)
        !$omp critical (MAPL_ErrorHandling10)
        if(MAPL_VRFYt) print *, text
        !$omp end critical (MAPL_ErrorHandling10)
   end function MAPL_VRFYT
Call graph
mapl_vrfyt calls mapl_vrfy
mapl_vrfy calls mapl_vrfyt, mapl_vrfy