MAPL_DoNotConnect – MAPL
MAPL_DoNotConnect Subroutine
15 statements
Source File
private subroutine MAPL_DoNotConnect(GC, SHORT_NAME, CHILD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: CHILD
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_DoNotConnect ( GC, SHORT_NAME, CHILD, RC )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*)             , intent(IN   ) :: SHORT_NAME
      integer,                        intent(IN   ) :: CHILD
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_DoNotConnect"
      integer                               :: status
      type (MAPL_Connectivity), pointer     :: conn
      call MAPL_ConnectivityGet(gc, connectivityPtr=conn, RC=status)
      _VERIFY(status)
      call CONN%DONOTCONN%append(SHORT_NAME, TO_IMPORT=CHILD, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_DoNotConnect
Call graph
mapl_donotconnect calls append, mapl_connectivityget, mapl_return, mapl_verify
append calls mapl_return, resize, vector_back
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
vector_resize_size_kind calls reserve
mapl_terminateimport calls mapl_donotconnect, mapl_donotconnectanyimport, mapl_donotconnectmany, mapl_terminateimportallbut, mapl_terminateimportall
mapl_donotconnectanyimport calls mapl_donotconnect
mapl_donotconnectmany calls mapl_donotconnect
mapl_terminateimportallbut calls mapl_donotconnect
mapl_terminateimportall calls mapl_terminateimport