MAPL_GenericSpecEnum – MAPL
MAPL_GenericSpecEnum Subroutine
52 statements
Source File
private recursive subroutine MAPL_GenericSpecEnum(GC, specs, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(StateSpecification), intent(inout) :: specs
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_GenericSpecEnum
Source Code
   recursive subroutine MAPL_GenericSpecEnum(GC, SPECS, RC)
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INout)  :: GC
      type(StateSpecification), intent(inout) :: specs
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: STATE
      type (MAPL_VarSpec),               pointer  :: IMPORT_SPEC(:)
      type (MAPL_VarSpec),               pointer  :: EXPORT_SPEC(:)
      integer                                     :: I, K
      integer                                     :: LBL
      type(ESMF_GridComp), pointer :: gridcomp
      !EOP
      ! Get my name and set-up traceback handle
      !----------------------------------------
      call ESMF_GridCompGet( GC, NAME=comp_name, _RC)
      ! Retrieve the pointer to the internal state
      !--------------------------------------------
      call MAPL_InternalStateGet ( GC, STATE, _RC)
      IMPORT_SPEC => STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      EXPORT_SPEC => STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      ! Add all import specs to the list and label by place on list.
      !-------------------------------------------------------------
      if (associated(IMPORT_SPEC)) then
         do I = 1, size(IMPORT_SPEC)
            call MAPL_VarSpecAddRefToList(SPECS, IMPORT_SPEC(I), &
                 ALLOW_DUPLICATES=.true., RC=status)
            if (status /= MAPL_DuplicateEntry) then
               _VERIFY(status)
            end if
            LBL = SPECS%var_specs%size()
            call MAPL_VarSpecSet(SPECS%old_var_specs(LBL), LABEL=LBL, _RC)
         end do
      end if
      ! Add all export specs to the list
      !  and label in a funny way.
      !---------------------------------
      if (associated(EXPORT_SPEC)) then
         do I = 1, size(EXPORT_SPEC)
            call MAPL_VarSpecAddRefToList(SPECS, EXPORT_SPEC(I), &
                 ALLOW_DUPLICATES=.true., RC=status)
            if (status /= MAPL_DuplicateEntry) then
               _VERIFY(status)
            end if
            K = specs%var_specs%size()
            call MAPL_VarSpecGet(SPECS%old_var_specs(K), LABEL=LBL, _RC)
            if (LBL == 0) then
               call MAPL_VarSpecSet(SPECS%old_var_specs(K), LABEL=K, _RC)
            end if
         end do
      end if
      ! Do the same for the children
      !-----------------------------
      do I = 1, STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(I)
         call MAPL_GenericSpecEnum(gridcomp, SPECS, _RC)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericSpecEnum
Call graph
mapl_genericspecenum calls mapl_genericspecenum, ESMF_GridCompGet, get_num_children, mapl_varspecaddreftolist, mapl_varspecget, mapl_varspecset, old_var_specs, get_child_gridcomp, mapl_internalstateget, mapl_return, mapl_verify
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_varspecset calls mapl_varspecsetnew
get_child_gridcomp calls get_gridcomp, get_ith_child
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
get_ith_child calls gcnamelist, get_child
mapl_throw_exception calls initialize
mapl_varspecaddreffromitem calls mapl_return, mapl_verify, error, get_logger, mapl_varspecgetindex, mapl_varspecprint
mapl_varspecaddreffromlist calls mapl_return, mapl_verify, mapl_varspecaddreffromitem
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecsetnew calls mapl_return