MAPL_VarSpecPrintOne – MAPL
MAPL_VarSpecPrintOne Subroutine
14 statements
Source File
private subroutine MAPL_VarSpecPrintOne(SPEC, RC)
$ call lgr%info(‘DIMS = %i0’,SPEC%SPECPtr%DIMS) $ call lgr%info(‘LOCATION = %dims = %i0’,SPEC%SPECPtr%location)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecPrintOne
Source Code
   subroutine MAPL_VarSpecPrintOne(SPEC, RC )
      type (MAPL_VarSpec ),             intent(IN )     :: SPEC
      integer            , optional   , intent(OUT)     :: RC
      class(Logger), pointer :: lgr
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      call lgr%info('NAME = %a~:%a~:%i3.3', &
           trim(spec%specptr%short_name), trim(spec%specptr%long_name), spec%specptr%label)
      call lgr%info('ACCUMT = %i0',SPEC%SPECPtr%ACCMLT_INTERVAL)
      call lgr%info('COUPLE = %i0',SPEC%SPECPtr%COUPLE_INTERVAL)
!!$    call lgr%info('DIMS   = %i0',SPEC%SPECPtr%DIMS)
!!$    call lgr%info('LOCATION = %dims   = %i0',SPEC%SPECPtr%location)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecPrintOne
Call graph
mapl_varspecprintone calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecprint calls mapl_varspecprintone, mapl_varspecprintmany
mapl_varspecprintmany calls mapl_varspecprint
mapl_stateprintspec calls mapl_varspecprint, mapl_stateprintspec
mapl_setvarspecforcc calls mapl_varspecprint, mapl_varspecaddreftolist
mapl_varspecaddreffromitem calls mapl_varspecprint
mapl_varspecaddreffromitemnew calls mapl_varspecprint
mapl_varspecaddreffromlist calls mapl_varspecaddreffromitem
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew, mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist
mapl_genericspecenum calls mapl_varspecaddreftolist