MAPL_Backspace – MAPL
MAPL_Backspace Subroutine
21 statements
Source File
public subroutine MAPL_Backspace(UNIT, LAYOUT, COUNT, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_DELayout), intent(in) :: LAYOUT
integer, intent(in), optional :: COUNT
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_Backspace(UNIT, LAYOUT, COUNT, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_DELayout)        , intent(IN   ) :: LAYOUT
    integer,           optional , intent(IN   ) :: COUNT
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer                               :: STATUS
    integer                               :: N, NN
    if (MAPL_AM_I_ROOT(LAYOUT)) then
       if(present(COUNT)) then
          NN=COUNT
       else
          NN=1
       endif
       do N=1,NN
          backspace(unit=UNIT, IOSTAT=status)
          _VERIFY(STATUS)
       end do
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_Backspace
Call graph
mapl_backspace calls mapl_am_i_root, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_fieldread calls mapl_backspace, mapl_varread
mapl_readforcingx calls mapl_backspace, mapl_varread
mapl_varread calls mapl_fieldread, mapl_bundleread, mapl_statevarread, mapl_varread_r4_2d, mapl_varread_r4_3d, mapl_varread_r4_4d, mapl_varread_r8_2d, mapl_varread_r8_3d, mapl_varread_r8_4d
mapl_bundleread calls mapl_fieldread
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_statevarread calls mapl_fieldread, mapl_bundleread
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
readrestart calls mapl_varread
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_staterefresh calls mapl_esmfstatereadfromfile