MAPL_CommsBcast_STRING_0 – MAPL
MAPL_CommsBcast_STRING_0 Subroutine
15 statements
Source File
private subroutine MAPL_CommsBcast_STRING_0(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
character(len=*), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CommsBcast_STRING_0
Source Code
  subroutine MAPL_CommsBcast_STRING_0( layout, data, N, ROOT, RC)
    type (ESMF_DELayout)                         :: layout
    character(len=*),   intent(INOUT)            :: data
    integer,            intent(in   )            :: N
    integer,            intent(in   )            :: ROOT
    integer         ,   intent(  out),  optional :: RC
    integer                               :: status
    type(ESMF_VM)                         :: vm
    call ESMF_DELayoutGet(layout, vm=vm, rc=status)
    _VERIFY(STATUS)
    call MAPL_CommsBcast(vm, data=data, N=N, Root=Root, RC=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE MAPL_CommsBcast_STRING_0
Call graph
mapl_commsbcast_string_0 calls esmf_delayoutget, mapl_commsbcast, mapl_return, mapl_verify
mapl_commsbcast calls mapl_commsbcast_string_0, mapl_commsbcast_i4_0, mapl_commsbcastvm_r8_0, mapl_commsbcast_r8_0, mapl_commsbcast_r8_2, mapl_commsbcast_r8_1, mapl_commsbcast_i4_2, mapl_commsbcast_r4_2, mapl_commsbcastvm_r4_1, mapl_commsbcastvm_r8_1, mapl_commsbcast_r4_0, mapl_commsbcast_i4_1, mapl_commsbcastvm_r4_0, mapl_commsbcast_l4_0, mapl_commsbcast_r4_1, mapl_commsbcastvm_i4_2, mapl_commsbcastvm_r4_2, mapl_commsbcastvm_i4_0, mapl_commsbcastvm_i4_1, mapl_commsbcastvm_l4_0, mapl_commsbcastvm_string_0, mapl_commsbcastvm_r8_2
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_commsbcast_i4_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r8_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r8_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r8_2 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r8_1 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_i4_2 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r4_2 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_throw_exception calls initialize
mapl_commsbcastvm_r4_1 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r8_1 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r4_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_i4_1 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r4_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_l4_0 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcast_r4_1 calls esmf_delayoutget, mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_i4_2 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_r4_2 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_i4_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_i4_1 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_l4_0 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
mapl_commsbcastvm_string_0 calls mapl_return, mapl_verify, mpi_bcast, mapl_assert, esmf_vmget
mapl_commsbcastvm_r8_2 calls mapl_return, mapl_verify, mpi_bcast, esmf_vmget
read_parallel_r4_2 calls mapl_commsbcast
read_parallel_r8_2 calls mapl_commsbcast
read_parallel_r8_0 calls mapl_commsbcast
mapl_bcastshared_1dr4 calls mapl_commsbcast
mapl_locstreamcreatefromfile calls mapl_commsbcast
mapl_varwrite_r8_1d calls mapl_commsbcast
read_parallel_i4_1 calls mapl_commsbcast
read_parallel_r4_0 calls mapl_commsbcast
read_parallel_r4_1 calls mapl_commsbcast
read_parallel_r8_1 calls mapl_commsbcast
mapl_areamean_2d_r8_bitrep calls mapl_commsbcast
read_parallel_string_0 calls mapl_commsbcast
mapl_fieldread calls mapl_commsbcast
mapl_getlatloncoord_real32 calls mapl_commsbcast
mapl_bcastshared_2dr4 calls mapl_commsbcast
mapl_esmfstatereadfromfile calls mapl_commsbcast
mapl_varwrite_r4_1d calls mapl_commsbcast
mapl_getlatloncoord_real64 calls mapl_commsbcast
initialize calls mapl_commsbcast
read_parallel_i4_0 calls mapl_commsbcast
read_parallel_i4_2 calls mapl_commsbcast
mapl_varread_r8_1d calls mapl_commsbcast
mapl_sungetsolarconstantfromnrlfile calls mapl_commsbcast
mapl_varread_r4_1d calls mapl_commsbcast
mapl_cfiocreatefrombundle calls mapl_commsbcast
readrestart calls mapl_commsbcast