MAPL_Interp_Fac – MAPL
MAPL_Interp_Fac Module Subroutine
13 statements
Source File
module subroutine MAPL_Interp_Fac(TIME0, TIME1, TIME2, FAC1, FAC2, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: TIME0
type(ESMF_Time), intent(in) :: TIME1
type(ESMF_Time), intent(in) :: TIME2
real, intent(out) :: FAC1
real, intent(out), optional :: FAC2
integer, intent(out), optional :: RC
Called by
Contents
Source Code
MAPL_Interp_Fac
Source Code
  module subroutine MAPL_Interp_Fac (TIME0, TIME1, TIME2, FAC1, FAC2, RC)
    !------------------------------------------------------------
    !  PURPOSE:
    !  ========
    !
    !    Compute interpolation factors, fac, to be used
    !    in the calculation of the instantaneous boundary
    !    conditions, ie:
    !
    !     q(i,j) = fac1*q1(i,j) + (1.-fac1)*q2(i,j)
    !
    !    where:
    !     q(i,j)  => Boundary Data valid    at time0
    !     q1(i,j) => Boundary Data centered at time1
    !     q2(i,j) => Boundary Data centered at time2
    !  INPUT:
    !  ======
    !    time0    : Time of current timestep
    !    time1    : Time of boundary data 1
    !    time2    : Time of boundary data 2
    !  OUTPUT:
    !  =======
    !     fac1    : Interpolation factor for Boundary Data 1
    !
    ! ------------------------------------------------------------
    !               GODDARD LABORATORY FOR ATMOSPHERES
    ! ------------------------------------------------------------
    type(ESMF_Time),   intent(in ) :: TIME0, TIME1, TIME2
    real,              intent(out) :: FAC1
    real,    optional, intent(out) :: FAC2
    integer, optional, intent(out) :: RC
    type(ESMF_TimeInterval)        :: TimeDif1
    type(ESMF_TimeInterval)        :: TimeDif
    TimeDif1 = TIME2-TIME0
    TimeDif  = TIME2-TIME1
    FAC1 = TimeDif1/TimeDif
    if(present(FAC2)) FAC2 = 1.-FAC1
    if(present(RC  )) RC   = ESMF_SUCCESS
  end subroutine MAPL_Interp_Fac
Call graph
mapl_interp_fac calls mapl_interp_fac
mapl_climinterpfac calls mapl_interp_fac, mapl_climinterpfac
mapl_readforcingx calls mapl_interp_fac
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_sungetsolarconstantfromnetcdffile calls mapl_climinterpfac
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2