MAPL_ExtDataExtractIntegers – MAPL
MAPL_ExtDataExtractIntegers Subroutine
80 statements
Source File
private subroutine MAPL_ExtDataExtractIntegers(string, iSize, iValues, delimiter, verbose, rc)
The routine MAPL_ExtDataExtractIntegers extracts integers from a character-delimited string, for example, “-1,45,256,7,10”. In the context of Chem_Util, this is provided for determining the numerically indexed regions over which an emission might be applied.
In multiple passes, the string is parsed for the delimiter, and the characters up to, but not including the delimiter are taken as consecutive digits of an integer. A negative sign (“-“) is allowed. After the first pass, each integer and its trailing delimiter are lopped of the head of the (local copy of the) string, and the process is started over.
The default delimiter is a comma (“,”).
“Unfilled” iValues are zero.
Return codes: - 1 Zero-length string. - 2 iSize needs to be increased.
Bug
-The routine works under the following assumptions: - A non-zero return code does not stop execution. - Allowed numerals are: 0,1,2,3,4,5,6,7,8,9. - A delimiter must be separated from another delimiter by at least one numeral. - The delimiter cannot be a numeral or a negative sign. - The character following a negative sign must be an allowed numeral. - The first character must be an allowed numeral or a negative sign. - The last character must be an allowed numeral. - The blank character (” “) cannot serve as a delimiter.
Examples of strings that will work:
  "1"
  "-1"
  "-1,2004,-3"
  "1+-2+3"
  "-1A100A5"
Examples of strings that will not work:
  "1,--2,3"
  "1,,2,3"
  "1,A,3"
  "1,-,2"
  "1,2,3,4,"
  "+1"
  "1 3 6"
History
Taken from chem utilities.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Character-delimited string of integers
integer, intent(in) :: iSize
integer, intent(inout) :: iValues(iSize)
Space allocated for extracted integers
character(len=*), optional :: delimiter
1-character delimiter
logical, intent(in), optional :: verbose
Let me know iValues as they are found. DEBUG directive turns on the message even if verbose is not present or if verbose = .FALSE.
integer, intent(out), optional :: rc
Return code
Calls
Called by
Contents
Source Code
MAPL_ExtDataExtractIntegers
Source Code
  SUBROUTINE MAPL_ExtDataExtractIntegers(string,iSize,iValues,delimiter,verbose,rc)
! !USES:
  IMPLICIT NONE
! !INPUT/OUTPUT PARAMETERS:
  CHARACTER(LEN=*), INTENT(IN)   :: string     !! Character-delimited string of integers
  INTEGER, INTENT(IN)            :: iSize
  INTEGER, INTENT(INOUT)         :: iValues(iSize) !! Space allocated for extracted integers
  CHARACTER(LEN=*), OPTIONAL     :: delimiter      !! 1-character delimiter
  LOGICAL, OPTIONAL, INTENT(IN)  :: verbose    !! Let me know iValues as they are found.
                                      !! DEBUG directive turns on the message even
                                      !! if verbose is not present or if
                                      !! verbose = .FALSE.
  INTEGER, OPTIONAL, INTENT(OUT) :: rc            !! Return code
!
 CHARACTER(LEN=*), PARAMETER :: Iam = 'Chem_UtilExtractIntegers'
 INTEGER :: base,count,i,iDash,last,lenStr
 INTEGER :: multiplier,pos,posDelim,sign
 CHARACTER(LEN=255) :: str
 CHARACTER(LEN=1) :: char,delimChar
 LOGICAL :: Done
 LOGICAL :: tellMe
! Initializations
! ---------------
 If (present(rc))  rc=0
 count = 1
 Done = .FALSE.
 iValues(:) = 0
 base = ICHAR("0")
 iDash = ICHAR("-")
! Determine verbosity, letting the DEBUG
! directive override local specification
! --------------------------------------
  tellMe = .FALSE.
  IF(PRESENT(verbose)) THEN
   IF(verbose) tellMe = .TRUE.
 END IF
#ifdef DEBUG
  tellMe = .TRUE.
#endif
! Check for zero-length string
! ----------------------------
 lenStr = LEN_TRIM(string)
 IF(lenStr == 0) THEN
    if (present(rc))  rc=1
    call lgr%error('Found zero length string at line %i0',__LINE__)
  RETURN
 END IF
! Default delimiter is a comma
! ----------------------------
 delimChar = ","
 IF(PRESENT(delimiter)) delimChar(1:1) = delimiter(1:1)
! Work on a local copy
! --------------------
 str = TRIM(string)
! One pass for each delimited integer
! -----------------------------------
 Parse: DO
  lenStr = LEN_TRIM(str)
! Parse the string for the delimiter
! ----------------------------------
  posDelim = INDEX(TRIM(str),TRIM(delimChar))
  if(tellMe) then
     call lgr%info('%a~: Input string is >%a<',trim(Iam), trim(string))
  end if
! If the delimiter does not exist,
! one integer remains to be extracted.
! ------------------------------------
  IF(posDelim == 0) THEN
   Done = .TRUE.
   last = lenStr
  ELSE
   last = posDelim-1
  END IF
  multiplier = 10**last
! Examine the characters of this integer
! --------------------------------------
  Extract: DO pos=1,last
   char = str(pos:pos)
   i = ICHAR(char)
! Account for a leading "-"
! -------------------------
   IF(pos == 1) THEN
    IF(i == iDash) THEN
     sign = -1
    ELSE
     sign = 1
    END IF
   END IF
! "Power" of 10 for this character
! --------------------------------
   multiplier = multiplier/10
   IF(pos == 1 .AND. sign == -1) CYCLE Extract
! Integer comes from remaining characters
! ---------------------------------------
   i = (i-base)*multiplier
   iValues(count) = iValues(count)+i
   IF(pos == last) THEN
    iValues(count) = iValues(count)*sign
    if(tellMe) then
       call lgr%info('%a~:Integer number %i0 is %i0', trim(iAm), count, iValues(count))
    end if
   END IF
  END DO Extract
  IF(Done) EXIT
! Lop off the leading integer and try again
! -----------------------------------------
  str(1:lenStr-posDelim) = str(posDelim+1:lenStr)
  str(lenStr-posDelim+1:255) = " "
  count = count+1
! Check size
! ----------
  IF(count > iSize) THEN
     if (present(rc))  rc=2
     call lgr%error('%a~: - iValues does not have enough elements.')
  END IF
 END DO Parse
 _RETURN(ESMF_SUCCESS)
 END SUBROUTINE MAPL_ExtDataExtractIntegers
Call graph
mapl_extdataextractintegers calls error, info, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_extdataevaluatemask calls mapl_extdataextractintegers
calcderivedfield calls mapl_extdataevaluatemask
run_ calls calcderivedfield