MAPL_CFIOCreateFromBundle – MAPL
MAPL_CFIOCreateFromBundle Subroutine
828 statements
Source File
private subroutine MAPL_CFIOCreateFromBundle(MCFIO, NAME, CLOCK, BUNDLE, OFFSET, OUTPUT_GRID, CHUNKSIZE, FREQUENCY, LEVELS, DESCR, XYOFFSET, VCOORD, VUNIT, VSCALE, source, institution, comment, contact, format, EXPID, DEFLATE, GC, Order, NumCores, Nbits, TM, Conservative, vectorList, itemOrder, RC)
The subroutine MAPL_CFIOCreateFromBundle creates a MAPL_CFIO object from a Bundle. The MAPL_CFIO objects is opaque and its properties can only be set by this method at creation. Currently, its properties cannot be queried. The object is used only as a handle in write operations. It is not needed for reading.
Its non-optional arguments associate a NAME, an ESMF BUNDLE, and a CLOCK with the object. An ESMF TimeInterval OFFSET is an optional argument that sets an offset between the time on the clock when eriting and the time stamp used for the data (defaults to no offset).
The format optional argument determines whether the write will use the linked self-describing format (SDF) library (HDF or netcdf) or write GrADS readable flat files. Currently only the SDF library option is supported.
The remaining (optional) arguments are especialized and used primarily to support MAPL_History, or to provide documentation in the form of character strings that will be placed in corresponding attributes in the SDF file.
HIstory
19Apr2007 Todling
Added ability to write out ak/bk
Added experiment ID as optional argument
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(out) :: MCFIO
character(len=*), intent(in) :: NAME
type(ESMF_Clock), intent(inout) :: CLOCK
type(ESMF_FIELDBUNDLE), intent(inout) :: BUNDLE
type(ESMF_TimeInterval), intent(inout), optional :: OFFSET
type(ESMF_Grid), optional, pointer :: OUTPUT_GRID
integer, optional, pointer :: CHUNKSIZE(:)
integer, intent(in), optional :: FREQUENCY
real, optional, pointer :: LEVELS(:)
character(len=*), intent(in), optional :: DESCR
integer, intent(in), optional :: XYOFFSET
character(len=*), intent(in), optional :: VCOORD
character(len=*), intent(in), optional :: VUNIT
real, intent(in), optional :: VSCALE
character(len=*), intent(in), optional :: source
character(len=*), intent(in), optional :: institution
character(len=*), intent(in), optional :: comment
character(len=*), intent(in), optional :: contact
character(len=*), intent(in), optional :: format
character(len=*), intent(in), optional :: EXPID
integer, intent(in), optional :: DEFLATE
type(ESMF_GridComp), intent(in), optional :: GC
integer, intent(in), optional :: Order
integer, intent(in), optional :: NumCores
integer, intent(in), optional :: Nbits
integer, intent(in), optional :: TM
integer, intent(in), optional :: Conservative
character(len=*), optional, pointer :: vectorList(:,:)
type(ESMF_ItemOrder_Flag), intent(in), optional :: itemOrder
integer, intent(out), optional :: RC
Calls
MAPL_CFIOCreateFromBundle w ArrayGather
w
w ESMF_AlarmIsRinging
w
w ESMF_AttributeGet
w
w ESMF_CFIOCreate
w
w ESMF_CFIOGridCreate
w
w ESMF_CFIOGridSet
w
w ESMF_CFIOSet
w
w ESMF_CFIOVarInfoCreate
w
w ESMF_CFIOVarInfoSet
w
w ESMF_ClockGet
w
w ESMF_ClockGetAlarm
w
w ESMF_DELayoutGet
w
w ESMF_DistGridGet
w
w esmf_fieldbundleget
w
w esmf_fieldget
w
w ESMF_GridGet
w
w ESMF_GridGetCoord
w
w ESMF_TimeGet
w
w ESMF_TimeIntervalGet
w
w ESMF_TimeIntervalSet
w
w ESMF_TimeSet
w
w ESMF_VMGet
w
w get_latlon_from_factory
w
w MAPL_AllocateShared
w
w MAPL_Am_I_Root
w
w MAPL_Assert
w
w MAPL_CommsBcast
w
w MAPL_CoresPerNodeGet
w
w MAPL_GenGridName
w
w MAPL_GeosNameNew
w
w MAPL_GridGet
w
w MAPL_Range
w
w MAPL_Return
w
w MAPL_RoundRobinPEList
w
w MAPL_SyncSharedMemory
w
w MAPL_Verify
w
w RegridderManager%make_regridder
w
Called by
Source Code
  subroutine MAPL_CFIOCreateFromBundle ( MCFIO, NAME, CLOCK, BUNDLE, OFFSET,      &
                                         OUTPUT_GRID, CHUNKSIZE, FREQUENCY, LEVELS, DESCR,    &
                                         XYOFFSET, VCOORD, VUNIT, VSCALE,         &
                                         SOURCE, INSTITUTION, COMMENT, CONTACT,   &
                                         FORMAT, EXPID, DEFLATE, GC,  ORDER, &
                                         NumCores, nbits, TM, Conservative,  &
                                         VectorList, itemOrder, RC )
! !ARGUMENTS:
!
    type(MAPL_CFIO),             intent(OUT) :: MCFIO
    character(LEN=*),            intent(IN)  :: NAME
    type(ESMF_FIELDBUNDLE),      intent(INout)  :: BUNDLE
    type(ESMF_CLOCK),            intent(INout):: CLOCK
    type(ESMF_TIMEINTERVAL), &
         optional,   intent(INout):: OFFSET
    type (ESMF_Grid), optional, pointer :: OUTPUT_GRID
    integer,         optional,   pointer     :: CHUNKSIZE(:)
    integer,         optional,   intent(IN)  :: FREQUENCY
    real,            optional,   pointer     :: LEVELS(:)
    character(LEN=*),optional,   intent(IN)  :: DESCR
    integer,         optional,   intent(IN)  :: XYOFFSET
    real,            optional,   intent(IN)  :: VSCALE
    integer,         optional,   intent(IN)  :: DEFLATE
    character(len=*),optional,   intent(IN)  :: VUNIT
    character(len=*),optional,   intent(IN)  :: VCOORD
    character(len=*),optional,   intent(IN)  :: source
    character(len=*),optional,   intent(IN)  :: institution
    character(len=*),optional,   intent(IN)  :: comment
    character(len=*),optional,   intent(IN)  :: contact
    character(len=*),optional,   intent(IN)  :: format
    character(len=*),optional,   intent(IN)  :: EXPID
    integer,         optional,   intent(IN)  :: Conservative
    type(ESMF_GridComp),optional,intent(IN)  :: GC
    integer,         optional,   intent(IN)  :: Order
    integer,         optional,   intent(IN)  :: Nbits
    integer,         optional,   intent(IN)  :: NumCores
    integer,         optional,   intent(IN)  :: TM
    character(len=*),optional,   pointer     :: vectorList(:,:)
    type(ESMF_ItemOrder_Flag),   optional,   intent(IN)  :: itemOrder
    integer,         optional,   intent(OUT) :: RC
! Locals
!-------
    integer                    :: STATUS
    type(ESMF_FIELD)    :: FIELD
    type(ESMF_GRID)     :: ESMFGRID
    type(ESMF_DELayout) :: LAYOUT
    type(ESMF_DistGrid) :: DISTGRID
    type(ESMF_TIME)     :: TIME
    type(ESMF_ALARM)    :: PERPETUAL
    type(ESMF_VM)       :: VM
    type(ESMF_CFIOVarInfo), pointer :: vars(:)
    type(ESMF_CFIOGrid),    pointer :: cfiogrid
    real, pointer  :: lats(:,:)
    real, pointer  :: lons(:,:)
    real, pointer  :: lats1d(:)
    real, pointer  :: lons1d(:)
    real, pointer  :: Local(:,:)
    real, pointer  :: lev (:  )
    real, pointer  :: ak  (:  )
    real, pointer  :: bk  (:  )
    real, pointer  :: ulevels(:  )
    real           :: range(2)
    real(KIND=REAL64), pointer  :: R8D2(:,:)
    integer        :: L, WriteInterval, counts(5), dims(3)
    integer        :: NumVars
    integer        :: IM,JM,LM
    integer        :: gridRank
    integer        :: fieldRank
    integer        :: Comm, nPEs
    integer        :: hours, mins, secs, timeInc
    integer        :: I, J, LT, K, IMO, JMO, LMG, IML, JML
    integer        :: IMBEG, IMEND, JMBEG, JMEND
    integer        :: Field_Type
    integer        :: Df
    integer        :: Num2DVars, Num3dVars
    integer        :: YY,MM,DD,H,M,S
    integer        :: noffset
    integer, allocatable :: Location(:)
    integer        :: CNT
    logical        :: Have2D, Have3D, HAVE_center, HAVE_edge, HAVE_ungrd
    logical        :: LPERP
    character(len=ESMF_MAXSTR)  :: Vunits
    character(len=ESMF_MAXSTR)  :: LongName
    character(len=ESMF_MAXSTR)  :: Units
    character(len=ESMF_MAXSTR)  :: StartTime
    character(len=esmf_maxstr)  :: Usource
    character(len=esmf_maxstr)  :: Uinstitution
    character(len=esmf_maxstr)  :: Ucomment
    character(len=esmf_maxstr)  :: Ucontact
    character(len=esmf_maxstr)  :: Utitle
    character(len=esmf_maxstr)  :: GridTypeAttribute
    character(len=ESMF_MAXSTR)  :: ClockName
    character(len=ESMF_MAXSTR)  :: Gridname
    character(len=ESMF_MAXSTR)  :: GridnameIn
    character(len=ESMF_MAXSTR)  :: GridnameOut
    character(len=2)            :: date
    character(len=2)            :: pole
    integer                     :: nn
    logical                     :: isGridRectilinear
    real, pointer               :: ptr3d(:,:,:)
    integer, allocatable        :: vsize(:)
    logical, allocatable        :: HasUngrid(:)
    character(len=ESMF_MAXSTR), pointer :: ungridded_units(:) => null()
    character(len=ESMF_MAXSTR), pointer :: ungridded_names(:) => null()
    character(len=ESMF_MAXSTR)  :: ungridded_unit, ungridded_name
    integer                     :: ungrdsize
    real, allocatable           :: ungridded_coord(:)
    real, allocatable           :: ungridded_coords(:,:)
    logical                     :: unGrdNameCheck, unGrdUnitCheck, unGrdCoordCheck
    logical                     :: found
    integer                     :: vectorListSize
    logical                     :: prevStored
    logical                     :: foundEmpty
    real(KIND=REAL64), pointer       :: LONS2D(:) => NULL()
    real(KIND=REAL64), pointer       :: LATS2D(:) => NULL()
    character(len=ESMF_MAXSTR), allocatable :: names(:)
    type(ESMF_ItemOrder_Flag) :: itemOrder_
    logical                     :: isPresent
! Begin
!------
    MCFIO%NAME   = NAME
    MCFIO%CLOCK  = CLOCK
    MCFIO%BUNDLE = BUNDLE
! Number of variables in the bundle
!----------------------------------
    call ESMF_FieldBundleGet (BUNDLE, FieldCount=NumVars,    RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(NumVars>0, 'numVars must be > 0')
! Process optionals
!------------------
    if(present(NBITS)) then
       MCFIO%Nbits = NBITS
    else
       MCFIO%nBits = 1000
    end if
    if(present(deflate)) then
       df = deflate
    else
       df = 0
    endif
    if(present(Order)) then
       print*,'WARNING:   CFIO parameter "order" is no longer used.'
       print*,'           The new regrid facility uses ESMF parameters to'
       print*,'           specify the type of regridding to perform.'
       _FAIL( 'Order must be present')
       MCFIO%Order = Order
    else
       MCFIO%Order = -1
    endif
    if(present(source)) then
       Usource = source
    else
       Usource = "unknown"
    endif
    if(present(institution)) then
       Uinstitution = institution
    else
       Uinstitution = "unknown"
    endif
    if(present(comment)) then
       Ucomment = comment
    else
       Ucomment = "unknown"
    endif
    if(present(contact)) then
       Ucontact = contact
    else
       Ucontact = "unknown"
    endif
    if(present(format)) then
       MCFIO%format = format
    else
       MCFIO%format = "SDF"
    endif
    if(present(expid)) then
       MCFIO%expid = expid
    else
       MCFIO%expid = "No_ExpId"
    endif
    if(present(descr )) then
       Utitle  = descr
    else
       Utitle  = "unknown"
    endif
    if(present(LEVELS)) then
       ulevels => LEVELS
    else
       nullify(ulevels)
    endif
    if(present(GC)) then
       MCFIO%GC   = GC
    else
!ALT       MCFIO%GC   = ESMF_GridCompCreate("NULL")
    endif
    if(present(VUNIT)) then
       vunits = trim(vunit)
    else
       vunits = ""
    endif
    if (present(vectorList)) then
       if (associated(vectorList)) then
          mcfio%vectorList => vectorList
       else
          mcfio%vectorList => null()
       end if
    else
       mcfio%vectorList => null()
    end if
! Get CommBndl, the communicator that is spanned by fields in the bundle
!-----------------------------------------------------------------------
    call ESMF_FieldBundleGet(BUNDLE, 1, FIELD,               RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_FieldGet       (FIELD, grid=ESMFGRID,          RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_GridGet        (ESMFGRID, dimCount=gridRank,   rc=STATUS)
    _VERIFY(STATUS)
    call ESMF_GridGet        (ESMFGRID, NAME=Gridname, rc=status )
    _VERIFY(STATUS)
    call ESMF_GridGet        (ESMFGRID, distgrid=DISTGRID,   RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_DistGridGet    (DISTGRID, delayout=LAYOUT,     RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_DELayoutGet    (LAYOUT,   vm=VM,               RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_VMGet          (VM, mpiCommunicator=Comm,      RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_VMGet          (VM, localpet=mCFIO%MYPE,       RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_VMGet          (VM, petcount=NPES,             RC=STATUS)
    _VERIFY(STATUS)
! Save the ESMFGrid in the object
!--------------------------------
    mCFIO%comm = comm
    mCFIO%Grid = ESMFGRID
! Set the partition size to size of VM. Can be overridden later to call to MAPL_CFIOSet
! -------------------------------------------------------------------------------------
    if(present(NumCores)) then
       mcfio%Numcores = NumCores
    else
       mcfio%Numcores = MAPL_CoresPerNodeGet(comm,rc=status)
       _VERIFY(STATUS)
    end if
    mCFIO%partsize = size(MAPL_NodeRankList)
    MCFIO%regridConservative = .false.
    if (present(Conservative)) then
       if (Conservative /= 0) then
          MCFIO%regridConservative = .true.
       end if
    end if
! Vertical interpolation info
!----------------------------
    if(present(Vcoord)) then
       MCFIO%VVAR = adjustl(vcoord)
       MCFIO%Func = MCFIO%Vvar(1:3)
       if    (MCFIO%Func=='log') then
          MCFIO%Vvar = adjustl(MCFIO%Vvar(index(MCFIO%Vvar,'(')+1:index(MCFIO%Vvar,')')-1))
       elseif(MCFIO%Func=='pow') then
          read( MCFIO%Vvar(index(MCFIO%Vvar,',')+1:index(MCFIO%Vvar,')')-1) , *) mCFIO%pow
          MCFIO%Vvar = adjustl(MCFIO%Vvar(index(MCFIO%Vvar,'(')+1:index(MCFIO%Vvar,',')-1))
       endif
    else
       MCFIO%VVAR = ""
       MCFIO%Func = ""
    end if
    if(present(vscale)) then
       MCFIO%Vscale = Vscale
    else
       MCFIO%Vscale = 1.0
    endif
! Determine the rank and vertical Location (Mid or Edge) of Fields within Bundle.
!   Note: If User-Defined ULEVELS is not present, ALL levels are written.
!   In this case, vertical Location must be consistent for ALL variables.
! ---------------------------------------------------------------------------------------
    allocate(MCFIO%VarDims(NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(MCFIO%VarName(NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(location     (NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(vsize        (NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(hasUngrid    (NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(MCFIO%VarType(NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(MCFIO%needVar(NumVars), stat=STATUS)
    _VERIFY(STATUS)
    allocate(ungridded_names(NumVars), stat=STATUS)
    _VERIFY(STATUS)
    ungridded_names=""
    allocate(ungridded_units(NumVars), stat=STATUS)
    _VERIFY(STATUS)
    ungridded_units=""
    allocate(names(NumVars),stat=status)
    _VERIFY(status)
    if (present(itemOrder)) then
       itemOrder_ = itemOrder
    else
       itemOrder_ = ESMF_ITEMORDER_ABC
    end if
    call ESMF_FieldBundleGet(bundle,itemorderflag=itemOrder_,fieldNameList=Names,rc=status)
    _VERIFY(status)
    VARIABLES_1: DO I = 1, NumVars
       call ESMF_FieldBundleGet(BUNDLE, names(i), field=FIELD,              RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_FieldGet      (FIELD, NAME= mCFIO%VarName(I), RC=STATUS)
       _VERIFY(STATUS)
       vsize(i) = 1
       hasUngrid(I) = .false.
       if(mCFIO%VarName(I)==MCFIO%Vvar) then
          MCFIO%VarDims(I) = -1
          LOCATION(i)      = MAPL_VLocationNone
       else
          call ESMF_FieldGet(FIELD, dimCount=fieldRank, RC=STATUS)
          _VERIFY(STATUS)
          _ASSERT(fieldRank <= 3, 'fieldRank > 3')
          MCFIO%VarDims(I) = fieldRank
          call ESMF_AttributeGet(FIELD, NAME="VLOCATION", isPresent=isPresent, RC=STATUS)
          _VERIFY(STATUS)
          if ( isPresent ) then
             call ESMF_AttributeGet(FIELD, NAME="VLOCATION", VALUE=LOCATION(I), RC=STATUS)
             _VERIFY(STATUS)
          else
             LOCATION(I) = MAPL_VLocationNone
          end if
          if (fieldRank == 3) then
             call ESMF_FieldGet(field, farrayPtr=ptr3d, rc=status)
             _VERIFY(STATUS)
             vsize(i) = size(ptr3d,3)
          end if
          if (fieldRank >= 3 .and. location(I) == MAPL_VLocationNone) then
             hasUngrid(I) = .true.
             call ESMF_AttributeGet(field,NAME="UNGRIDDED_UNIT",value=ungridded_unit,rc=status)
             _VERIFY(STATUS)
             call ESMF_AttributeGet(field,NAME="UNGRIDDED_NAME",value=ungridded_name,rc=status)
             _VERIFY(STATUS)
             ungridded_names(i) = ungridded_name
             ungridded_units(i) = ungridded_unit
             call ESMF_AttributeGet(field,NAME="UNGRIDDED_COORDS",isPresent=isPresent,rc=status)
             _VERIFY(STATUS)
             if (isPresent) then
                call ESMF_AttributeGet(field,NAME="UNGRIDDED_COORDS",itemcount=ungrdsize,rc=status)
                _VERIFY(STATUS)
             else
                ungrdsize=0
             end if
             if (ungrdsize/=0) then
                _ASSERT(vsize(i)==ungrdsize,'inconsistent ungrdsize')
                if (.not.allocated(ungridded_coord)) allocate(ungridded_coord(ungrdsize),stat=status)
                if (.not.allocated(ungridded_coords)) allocate(ungridded_coords(NumVars,ungrdsize),stat=status)
                _VERIFY(STATUS)
                call ESMF_AttributeGet(field,NAME="UNGRIDDED_COORDS",valuelist=ungridded_coord,rc=status)
                _VERIFY(STATUS)
                ungridded_coords(i,:) = ungridded_coord
             end if
          end if
       endif
    end do VARIABLES_1
    ! now put a check in that we aren't trying to do something like have two different
    ! ungridded units if we have any ungridded dimensions, compare ungridded info for
    ! each variable to the last values retrieved, if any differ then obviously user
    ! is trying to put 2 different ungridded variables in a collection that have
    ! different attributes
    if (any(hasUngrid)) then
       do i=1,NumVars
          if (hasUngrid(i)) then
             unGrdUnitCheck = ungridded_units(i) /= ungridded_unit
             unGrdNameCheck = ungridded_names(i) /= ungridded_name
             if ( allocated(ungridded_coords) .and. allocated(ungridded_coords) ) then
                unGrdCoordCheck = any(ungridded_coords(i,:) /= ungridded_coord)
             else
                unGrdCoordCheck = .false.
             end if
             if ( unGrdUnitCheck .or. unGrdNameCheck .or. unGrdCoordCheck) then
                _FAIL( 'Ungridded attributes for variables in collection do not match')
             end if
          end if
       end do
    end if
!ALT: next segment is here only for initial testing
! we need a better logic how to prepare needVar list
! possibilities are: add staggering, vector pair to spec
! special key words in collection, etc.
    mCFIO%needVar = 0
    vectorListSize = 0
    if (associated(mCFIO%vectorList)) then
       vectorListSize = size(mCFIO%vectorList,2)
    end if
    VARLOOP: DO I = 1, NumVars
       DO k = 1, vectorListSize
          if (mCFIO%varName(I) == mCFIO%vectorList(1,k)) then
             ! this is first component of a vector (i.e. U)
             ! find the index of the V component
             found = .false.
             DO J = 1, NumVars
                if (trim(mCFIO%varName(J)) == mCFIO%vectorList(2,k)) then
                   found = .true.
                   exit
                end if
             end DO
             _ASSERT(found, 'search failed')
             mCFIO%needVar(I) = J ! I am first component of the vector
          else if(mCFIO%varName(I) == mCFIO%vectorList(2,k)) then
             ! find the index of the U component
             ! store it as negative number by convension suggested by Max
             found = .false.
             DO J = 1, NumVars
                if (trim(mCFIO%varName(J)) == mCFIO%vectorList(1,k)) then
                   found = .true.
                   exit
                end if
             end DO
             _ASSERT(found, 'search failed')
             mCFIO%needVar(I) = -J ! I am second component of the vector
          end if
       end DO
    end DO VARLOOP
! Sizes of global grid in the bundle. Sizes in the SDF may be different.
!----------------------------------------------------------------------
    call MAPL_GridGet( MCFIO%GRID, globalCellCountPerDim=COUNTS,  &
                       localCellCountPerDim=DIMS,     RC=STATUS)
    _VERIFY(STATUS)
    IML = DIMS(1)
    JML = DIMS(2)
    IM = COUNTS(1)
    JM = COUNTS(2)
    LMG = COUNTS(3)
    HAVE_center = any(LOCATION==MAPL_VLocationCenter)
    HAVE_edge   = any(LOCATION==MAPL_VLocationEdge  )
    HAVE_ungrd  = any(hasUngrid)
    if     ( associated(ULEVELS)  ) then
       LM = size(ULEVELS)
       HAVE_edge = .false.
       if (HAVE_ungrd) then
          _FAIL( 'ERROR: Specifying LEVELS is not allowed for UNGRIDDED vars')
       end if
    else
!      Check on proper levels
!      -----------------------
       if(HAVE_center .and.  HAVE_edge) then
          DO I = 1, NumVars
             IF (LOCATION(I)==MAPL_VLocationEdge) print*, mCFIO%VarName(I)
          ENDDO
          _FAIL( 'ERROR: Mixed Vlocation in CFIO not allowed unless LEVELS is specified')
       endif
       if( all(MCFIO%VarDims==2)) then
          LM = 1
       else if (HAVE_ungrd) then
          if (HAVE_center .or. HAVE_edge) then
             _FAIL( 'ERROR: Mixed 3d and UNGRIDDED in CFIO not allowed')
          end if
          if (minval(vsize) /= maxval(vsize)) then
             _FAIL( 'ERROR: Outputting variables with different ungridded sizes in one collection')
          end if
          LM = maxval(vsize)
       else
          LM = COUNTS(3)
          if (HAVE_edge) LM = LM+1
       endif
    end if
    mCFIO%LM   = LM
! Allocate request arrays for non-blocking gathers of bundle variables
!  Each 2D variable and each level of each 3D variable needs a request
!---------------------------------------------------------------------
    Num2DVars = count(MCFIO%VarDims==2)
    Num3DVars = count(MCFIO%VarDims==3)
    Have2D    = Num2DVars > 0
    Have3D    = Num3DVars > 0
    _ASSERT(HAVE2D .or. HAVE3D, 'must be 2D or 3D')
    LT        = Num2DVars + Num3DVars*LM
    allocate( MCFIO%reqs (LT),stat=STATUS)
    _VERIFY(STATUS)
    allocate( MCFIO%Krank(LT),stat=STATUS)
    _VERIFY(STATUS)
    mcfio%krank=0
    allocate(MCFIO%pairList(LT), stat=STATUS)
    _VERIFY(STATUS)
    if (allocated(MAPL_NodeRankList)) then
       call MAPL_RoundRobinPEList(mcfio%krank,size(MAPL_NodeRankList),rc=status)
       _VERIFY(status)
    end if
    MCFIO%pairList = 0
! Horizontal dimensions of output fields
!---------------------------------------
    if (present(OUTPUT_GRID)) then
       if (associated(OUTPUT_GRID)) then
          mcfio%output_grid = OUTPUT_GRID
       else
          mcfio%output_grid = mCFIO%grid
       end if
       call MAPL_GridGet(mcfio%output_grid, globalCellCountPerDim=dims, rc=status)
       _VERIFY(status)
       IMO = dims(1)
       JMO = dims(2)
    else
       mcfio%output_grid = mCFIO%grid
       IMO = IM
       JMO = JM
    end if
    MCFIO%IM = IMO
    MCFIO%JM = JMO
!ALT: this is first attempt to guess if the grid is rectilinear
!     i.e. if we need could use 1d LAT/LONs
!     we take clues from the gridname
    Gridname = adjustl(Gridname)
    nn   = len_trim(Gridname)
    pole = Gridname(1:2)
    date = Gridname(nn-1:nn)
!ALT: if change of horizontal resolution is requested, we
!     assume uniform output grid
    if (IM /= IMO .or. JM /= JMO) isGridRectilinear=.true.
    isGridRectilinear = .true. ! default: 1d LAT/LONs
        ! special cases requiring 2d LAT/LONs
    if (JMO == 6*IMO) isGridRectilinear = .false.
    if (pole == 'CM') isGridRectilinear = .false.
    if (date == 'TM') isGridRectilinear = .false.
!ALT: if change of horizontal resolution is requested, we
!     assume uniform output grid
    if (IM /= IMO .or. JM /= JMO) then
       isGridRectilinear=.true.
       mCFIO%newFormat = .false.
    end if
    if (isGridRectilinear) then
       allocate(LONS1D(IMO), STAT=status)
       _VERIFY(status)
       allocate(LATS1D(JMO), STAT=status)
       _VERIFY(status)
    else
       allocate(LONS1D(0), LATS1D(0), STAT=status)
       _VERIFY(status)
       ! the above 2 lines need to be replaced with:
       ! table search + set logical prevStored
       prevStored = .false.
       do i = 1, maxStoredCoords
          if (.not.storedCoords(i)%created) cycle
          if ( storedCoords(i)%IM == IMO .and. &
               storedCoords(i)%JM == JMO ) then
             prevStored = .true.
             LONS2D => storedCoords(i)%LONS2D
             LATS2D => storedCoords(i)%LATS2D
!             call Write_Parallel("DEBUG:Using stored LAT/LONs")
             exit
          end if
       end do
       if (.not.prevStored) then
          call MAPL_AllocateShared(LONS2D, (/IMO*JMO/), &
               TransRoot=.true., RC=STATUS)
          _VERIFY(STATUS)
          call MAPL_AllocateShared(LATS2D, (/IMO*JMO/), &
               TransRoot=.true., RC=STATUS)
          _VERIFY(STATUS)
          foundEmpty = .false.
!          call Write_Parallel("DEBUG:Storing LAT/LONs")
          do i = 1, maxStoredCoords
             if (storedCoords(i)%created) cycle
             storedCoords(i)%created = .true.
             storedCoords(i)%LONS2D => LONS2D
             storedCoords(i)%LATS2D => LATS2D
             storedCoords(i)%IM = IMO
             storedCoords(i)%JM = JMO
             foundEmpty = .true.
             exit
          end do
          if (.not.foundEmpty) then
             _FAIL( 'ERROR: Need bigger table with storedCoords')
          end if
       end if
    endif
! Process horizontal resolution change
!-------------------------------------
    IMBEG = 1
    IMEND = IMO
    JMBEG = 1
    JMEND = JMO
    TRANSFORM: if (IM /= IMO .or. JM /= JMO) then
       if (present(output_grid)) then
            call get_latlon_from_factory(output_grid, lons1d, lats1d, rc=status)
            _VERIFY(status)
       else
          if(present(xyoffset)) then
             select case(xyoffset)
             case(0) ! PC, DC
                lons1d = MAPL_Range(-180.,180.-(360./IMO), IMO)
                lats1d = MAPL_Range(-90., +90., JMO)
             case(1) ! PC, DE
                lons1d = MAPL_Range(-180.+(180./IMO), 180.-(180./IMO), IMO)
                lats1d = MAPL_Range(-90., +90., JMO)
             case(2) ! PE, DC
                lons1d = MAPL_Range(-180.,180.-(360./IMO), IMO)
                lats1d = MAPL_Range(-90.+(90./JMO), +90.-(90./JMO), JMO)
             case(3) ! PE, DE
                lons1d = MAPL_Range(-180.+(180./IMO), 180.-(180./IMO), IMO)
                lats1d = MAPL_Range(-90.+(90./JMO), +90.-(90./JMO), JMO)
             case default
                _FAIL('needs informative message')
             end select
             mcfio%xyoffset = xyoffset
          else
             mcfio%xyoffset = 0
             lons1d = MAPL_Range(-180.,180.-(360./IMO), IMO, conversion_factor=MAPL_DEGREES_TO_RADIANS_R8)
             lats1d = MAPL_Range(-90., +90., JMO, conversion_factor=MAPL_DEGREES_TO_RADIANS_R8)
          endif
       endif
       call ESMF_AttributeGet(ESMFGRID, name="GridType", isPresent=isPresent, rc=STATUS)
       _VERIFY(STATUS)
       if (isPresent) then
          call ESMF_AttributeGet(ESMFGRID, name="GridType", value=GridTypeAttribute, rc=STATUS)
          _VERIFY(STATUS)
       else
          GridTypeAttribute = 'UNKNOWN'
       endif
! If order of transform was not specified, do binning for coarser,
!   and bilinear for finer.
!------------------------------------------------------------------
       if     (mCFIO%order<0) then
          if (IMO <  IM .or. JMO < JM) then
             mCFIO%order=0
          else
             mCFIO%order=1
          end if
       end if
    else ! TRANSFORM
! Arrays of lats and lons from esmfgrid
!--------------------------------------
       !ALT we need to execute all of this only if
       ! the grid is rectilinear or not in the table
       if (isGridRectilinear .or. .not. prevStored) then
    !if (JMO /= 6*IMO) then
       allocate(LONS (IM ,JM ),STAT=STATUS)
       _VERIFY(STATUS)
       allocate(LATS (IM ,JM ),STAT=STATUS)
       _VERIFY(STATUS)
       allocate(LOCAL(IML,JML),STAT=STATUS)
       _VERIFY(STATUS)
       call ESMF_GridGetCoord(esmfgrid, localDE=0, coordDim=1, &
            staggerloc=ESMF_STAGGERLOC_CENTER, &
            farrayPtr=R8D2, rc=status)
       _VERIFY(STATUS)
       LOCAL = R8D2*(180._REAL64/MAPL_PI_R8)
       call ArrayGather(LOCAL, LONS, ESMFGRID, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_GridGetCoord(esmfgrid, localDE=0, coordDim=2, &
            staggerloc=ESMF_STAGGERLOC_CENTER, &
            farrayPtr=R8D2, rc=status)
       _VERIFY(STATUS)
       LOCAL = R8D2*(180._REAL64/MAPL_PI_R8)
       call ArrayGather(LOCAL, LATS, ESMFGRID, RC=STATUS)
       _VERIFY(STATUS)
       call MAPL_CommsBcast (layout, lons, size(lons), 0, rc=status)
       _VERIFY(STATUS)
       call MAPL_CommsBcast (layout, lats, size(lats), 0, rc=status)
       _VERIFY(STATUS)
       if (isGridRectilinear) then
          LONS1D = LONS(:,1)
          LATS1D = LATS(1,:)
       else
          if (MAPL_AmNodeRoot .or. (.not. MAPL_ShmInitialized)) then
             k = 0
             do j = 1, jm
                do i = 1, im
                   k = k+1
                   LONS2D(k) = LONS(i,j)
                   LATS2D(k) = LATS(i,j)
                end do
             end do
          end if
          call MAPL_SyncSharedMemory(rc=STATUS)
          _VERIFY(STATUS)
       endif
       DEALLOCATE(LOCAL)
       DEALLOCATE(LONS)
       DEALLOCATE(LATS)
     end if
     !end if ! Cubed-Sphere ouput
    endif TRANSFORM
    if (present(output_grid)) then
       if (MCFIO%regridConservative) then
          call MAPL_GenGridName(imo, jmo, xyoffset=mcfio%xyoffset, gridname=gridnameOut, geos_style=.false.)
          gridnameIn = gridname
          call MAPL_GeosNameNew(gridnameIn)
          mCFIO%regridder => regridder_manager%make_regridder(mCFIO%grid, mCFIO%output_grid, &
               & REGRID_METHOD_CONSERVE, rc=status)
          _VERIFY(status)
       else
          mCFIO%regridder => regridder_manager%make_regridder(mCFIO%grid, mCFIO%output_grid, &
               & REGRID_METHOD_BILINEAR, rc=status)
          _VERIFY(status)
       end if
    end if
! Create the CFIO grid and populate it
!-------------------------------------
    allocate(CFIOGRID)
    CFIOGRID = ESMF_CFIOGridCreate(gName=trim(NAME)//"Grid", RC=STATUS)
    _VERIFY(STATUS)
! Horizontal grid info
!---------------------
    if (isGridRectilinear) then
       call ESMF_CFIOGridSet(CFIOGRID, LON=LONS1D(IMBEG:IMEND), LAT=LATS1D(JMBEG:JMEND),  TM=TM,  RC=STATUS)
       _VERIFY(STATUS)
    else
       !ALT: new approach
       ! create 2DR8 shared memory coordinate arrays
       ! actually, check if the object is in a table, if YES, use it
       ! else  create one and put it in the table
       ! fill them on node root
       ! pass them down
       call ESMF_CFIOGridSet(CFIOGRID, twoDimLat=.true., IM=IMO, JM=JMO, TM=TM,  &
            LON2=LONS2D, LAT2=LATS2D,  RC=STATUS)
       _VERIFY(STATUS)
    end if
    deallocate(LONS1D)
    deallocate(LATS1D)
! Vertical grid info
!--------------------
    mCFIO%Vinterp = .false.
    mCFIO%Vinterp = MCFIO%Vvar/=""
    VERTGRID: if(HAVE3D) THEN
       allocate(LEV(LM), stat=status)
       _VERIFY(STATUS)
       if (associated(ULEVELS)) then
          if (mCFIO%Vinterp .or. (size(ulevels) < LMG)) then
             LEV = ULEVELS
          else
             LEV = (/(L, L=1,size(ulevels))/)
          end if
       else if (HAVE_edge) then
          LEV = (/(L, L=0,LM-1)/)
       else if (HAVE_ungrd) then
          if (allocated(ungridded_coord)) then
             lev = ungridded_coord
          else
             lev = (/(L, L=1,LM)/)
          end if
       else
          LEV = (/(L, L=1,LM)/)
       end if
       allocate(mCFIO%levs(size(lev)),mcfio%unmodifiedLevs(size(lev)), stat=status)
       _VERIFY(STATUS)
       mCFIO%levs = lev
       mCFIO%unmodifiedLevs = lev
       if (HAVE_ungrd) then
          call ESMF_CFIOGridSet(cfiogrid, levUnit=ungridded_unit, RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_CFIOGridSet(cfiogrid, standardName =ungridded_name, RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_CFIOGridSet(cfiogrid, coordinate ='N/A', RC=STATUS)
          _VERIFY(STATUS)
          mCFIO%levs = -mCFIO%levs
       else if(mCFIO%Vinterp) then
          if    (mCFIO%Func=='log') then
             mCFIO%levs = log(lev* MCFIO%vscale)
          elseif(mCFIO%Func=='pow') then
             mCFIO%levs = (lev* MCFIO%vscale)**mCFIO%pow
          else
             mCFIO%levs = lev* MCFIO%vscale
          end if
          mCFIO%unmodifiedLevs=mCFIO%unmodifiedLevs*MCFIO%vscale
          if( trim(vunits).eq."" ) then
             call ESMF_AttributeGet(FIELD, NAME="UNITS", VALUE=units,         RC=STATUS)
             _VERIFY(STATUS)
             call ESMF_CFIOGridSet(cfiogrid, levUnit=trim(units),             RC=STATUS)
             _VERIFY(STATUS)
          else
             call ESMF_CFIOGridSet(cfiogrid, levUnit=trim(vunits),            RC=STATUS)
             _VERIFY(STATUS)
          endif
          call ESMF_CFIOGridSet(cfiogrid, standardName =trim(MCFIO%Vvar)//'_level', RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_CFIOGridSet(cfiogrid, coordinate   =trim(MCFIO%Vvar),           RC=STATUS)
          _VERIFY(STATUS)
       else
          if (present(vunit) .and. trim(vunits) .ne. "") then
             call ESMF_CFIOGridSet(cfiogrid, levUnit      =trim(vunits),         RC=STATUS)
             _VERIFY(STATUS)
          else
             call ESMF_CFIOGridSet(cfiogrid, levUnit      ='layer',              RC=STATUS)
             _VERIFY(STATUS)
          end if
          call ESMF_CFIOGridSet(cfiogrid, standardName ='model_layers',       RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_CFIOGridSet(cfiogrid, coordinate   ='eta',                RC=STATUS)
          _VERIFY(STATUS)
       end if
       if (associated(ulevels)) then
          call ESMF_CFIOGridSet(cfiogrid, lev=ulevels,  RC=STATUS)
          _VERIFY(STATUS)
       else
          call ESMF_CFIOGridSet(cfiogrid, lev=abs(lev),  RC=STATUS)
          _VERIFY(STATUS)
       end if
       deallocate(LEV)
    else
       call ESMF_CFIOGridSet(cfiogrid, levUnit      ='none',         RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_CFIOGridSet(cfiogrid, standardName ='2d_fields',    RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_CFIOGridSet(cfiogrid, coordinate   ='N/A',          RC=STATUS)
       _VERIFY(STATUS)
    end if VERTGRID
! Create variable objects
!------------------------
    allocate(vars(Num2DVars+Num3dVars), stat=status)
    _VERIFY(STATUS)
! Disable range checking
!-----------------------
    RANGE(2) =  MAPL_UNDEF
    RANGE(1) = -MAPL_UNDEF
    K = 0
    mCFIO%vartype = MAPL_ScalarField
    VARIABLES_2: do L=1,NumVars
       if(mCFIO%VarDims(L)<1) cycle
       K = K + 1
       call ESMF_FieldBundleGet(BUNDLE, mCFIO%varName(L), field=FIELD,                       RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_AttributeGet  (FIELD, NAME="LONG_NAME",isPresent=isPresent, RC=STATUS)
       _VERIFY(STATUS)
       if ( isPresent ) then
          call ESMF_AttributeGet  (FIELD, NAME="LONG_NAME",VALUE=LongName, RC=STATUS)
          _VERIFY(STATUS)
       else
          LongName = mCFIO%VarName(L)
       endif
       call ESMF_AttributeGet  (FIELD, NAME="UNITS"    ,isPresent=isPresent, RC=STATUS)
       _VERIFY(STATUS)
       if ( isPresent ) then
          call ESMF_AttributeGet  (FIELD, NAME="UNITS"    ,VALUE=Units, RC=STATUS)
          _VERIFY(STATUS)
       else
          Units = 'unknown'
       end if
       call ESMF_AttributeGet  (FIELD, NAME="FIELD_TYPE",isPresent=isPresent, RC=STATUS)
       _VERIFY(STATUS)
       if ( isPresent ) then
          call ESMF_AttributeGet  (FIELD, NAME="FIELD_TYPE",VALUE=Field_Type, RC=STATUS)
          _VERIFY(STATUS)
       else
          Field_Type = MAPL_ScalarField
       end if
       mCFIO%vartype(L) = Field_Type
       VARS(K) = ESMF_CFIOVarInfoCreate(vName=trim(mCFIO%VarName(L)),   RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_CFIOVarInfoSet(VARS(K),           &
            vName        = mCFIO%VarName(L),       &
            vTitle       = LongName,               &
            grid         = cfioGRID,               &
            amiss        = MAPL_Undef,             &
            scaleFactor  = 1.,                     &
            addOffSet    = 0.,                     &
            standardName = LongName,               &
            twoDimVar    = MCFIO%VarDims(L)==2,    &
            validRange   = RANGE,                  &
            vUnits       = UNITS,                  &
                                         RC=STATUS )
       _VERIFY(STATUS)
       if (present(CHUNKSIZE)) then
          if (associated(CHUNKSIZE)) then
             call ESMF_CFIOVarInfoSet(VARS(K), &
                  ChunkSize = ChunkSize,       &
                         rc = status           )
          end if
       end if
    end do VARIABLES_2
! Get time info from the clock. Note the optional offset
!-------------------------------------------------------
    call ESMF_ClockGet(CLOCK, name=clockname, CurrTime =TIME, RC=STATUS)
    _VERIFY(STATUS)
    if(present(OFFSET)) then
        call ESMF_TimeIntervalGet( OFFSET, S=noffset, rc=status )
        _VERIFY(STATUS)
        if( noffset /= 0 ) then
            LPERP = ( index( trim(clockname),'_PERPETUAL' ).ne.0 )
        if( LPERP ) then
            call ESMF_ClockGetAlarm ( clock, alarmname='PERPETUAL', alarm=PERPETUAL, rc=status )
            _VERIFY(STATUS)
            if( ESMF_AlarmIsRinging(PERPETUAL) ) then
                call ESMF_TimeGet ( Time, YY = YY, &
                                          MM = MM, &
                                          DD = DD, &
                                          H  = H , &
                                          M  = M , &
                                          S  = S, rc=status )
                                          MM = MM + 1
                call ESMF_TimeSet ( Time, YY = YY, &
                                          MM = MM, &
                                          DD = DD, &
                                          H  = H , &
                                          M  = M , &
                                          S  = S, rc=status )
                if( MAPL_AM_I_ROOT() ) write(6,"(a,2x,i4.4,'/',i2.2,'/',i2.2,2x,'Time: ',i2.2,':',i2.2,':',i2.2)") &
                     & "Inside Create: ",YY,MM,DD,H,M,S
            endif
        endif
        endif
       TIME = TIME  - OFFSET
       MCFIO%OFFSET = OFFSET
    else
      call ESMF_TimeIntervalSet( MCFIO%OFFSET, S=0, rc=status )
      _VERIFY(STATUS)
    endif
    call ESMF_TimeGet (TIME,  timeString=StartTime, RC=STATUS)
    _VERIFY(STATUS)
! Create CFIO object
!-------------------
    MCFIO%cfio =  ESMF_CFIOCreate(cfioObjName=trim(Name))
! Set Internal MetaCode Writing interval. Default of 6 hours. If set to 0
!  it is reset to 6 hours.Currently CFIO and GFIO expect timeIncrement to be
!  in HHMMSS format, this imposes severe limitations to the frequency of the output:
!  no writes should be done less frequently than once every 4 days (99 hours)
! ------------------------------------------------------------------------------
    if (present(FREQUENCY)) then
       !_ASSERT(FREQUENCY <= 4*86400,'bad frequency')
       if (frequency == 0 ) then
          writeInterval = 21600
       else
          writeInterval = FREQUENCY
       endif
    else
       writeInterval = 21600
    end if
    hours         = writeInterval/3600
    writeInterval = writeInterval-3600*hours
             mins = writeInterval/60
             secs = writeInterval-60*mins
    timeinc = 10000*hours + 100*mins + secs
! Set global attributes
!----------------------
    call ESMF_CFIOSet(MCFIO%CFIO,                                 &
         varObjs     = VARS,                                      &
         grid        = cfioGRID,                                  &
         format      = MCFIO%Format,                              &
         expid       = MCFIO%ExpId,                               &
         TimeString  = trim(StartTime),                           &
         timeInc     = timeInc,                                   &
         title       = trim(Utitle),                              &
         source      = Usource,                                   &
         history     = 'File written by MAPL_CFIO',               &
         institution = Uinstitution,                              &
         convention  = "COARDS",                                  &
         contact     = Ucontact,                                  &
         references  = "http://gmao.gsfc.nasa.gov",               &
         comment     = Ucomment,                                  &
         prec        = 0,                                         &
         deflate     = df,                                        &
         RC=STATUS )
    _VERIFY(STATUS)
! Create AK/BKs
! -------------
    if(HAVE3D) then
       call ESMF_AttributeGet(ESMFGRID, NAME='ak', isPresent=isPresent, RC=STATUS)
       _VERIFY(STATUS)
       if (isPresent) then
          call ESMF_AttributeGet(ESMFGRID, NAME='ak', itemcount=CNT, RC=STATUS)
          _VERIFY(STATUS)
       else
          CNT=0
       endif
       if (CNT>0) then
          allocate ( ak(CNT), bk(CNT), stat=status )
          _VERIFY(STATUS)
          call ESMF_AttributeGet(ESMFGRID, name='ak', valueList=ak, rc=STATUS)
          _VERIFY(STATUS)
          call ESMF_CFIOSet(MCFIO%cfio, attRealName='ak', attReal=ak )
          call ESMF_AttributeGet(ESMFGRID, name='bk', valuelist=bk, rc=STATUS)
          _VERIFY(STATUS)
          call ESMF_CFIOSet(MCFIO%cfio, attRealName='bk', attReal=bk )
          deallocate ( ak, bk )
       end if
    endif
! All Done
!---------
    MCFIO%CREATED = .true.
    deallocate(hasUngrid)
    deallocate(vsize)
    deallocate(location)
!@    call ESMF_CFIOVarInfoDestroy(vars, _RC)
    deallocate(vars)
!ALT we should do this:    call ESMF_CFIOGridDestroy(cfiogrid)
    deallocate(cfiogrid)
    deallocate(ungridded_names)
    deallocate(ungridded_units)
    if (allocated(ungridded_coord)) then
       deallocate(ungridded_coord)
    end if
    if (allocated(ungridded_coords)) then
       deallocate(ungridded_coords)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOCreateFromBundle
Call graph
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls esmf_iocreate
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main