MAPL_GeosNameNew – MAPL
MAPL_GeosNameNew Module Subroutine
27 statements
Source File
module subroutine MAPL_GeosNameNew(name) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*) :: name
Called by
Contents
Source Code
MAPL_GeosNameNew
Source Code
  module subroutine MAPL_GeosNameNew(name)
    character(len=*) :: name
    integer :: im, jm
    integer :: nn
    character(len=MAPL_TileNameLength) :: gridname
    character(len=2) :: dateline, pole
    character(len=8) :: imsz
    character(len=8) :: jmsz
    ! Parse name for grid info
    !-------------------------
    Gridname = AdjustL(name)
    nn   = len_trim(Gridname)
    imsz = Gridname(3:index(Gridname,'x')-1)
    jmsz = Gridname(index(Gridname,'x')+1:nn-3)
    pole = Gridname(1:2)
    dateline = Gridname(nn-1:nn)
    read(IMSZ,*) IM
    read(JMSZ,*) JM
    if (jm /= 6*im) then
       ! Lat-Lon
       write(name,'(a,i4.4,a,a,i4.4)') dateline,im,'x',pole,jm
    else
       ! Cubed-sphere
       pole='6C'
       if (dateline=='CF') then
          write(name,'(a,i4.4,a,a)') dateline,im,'x',pole
       else
          name='UNKNOWN_ERROR'
       end if
    end if
  end subroutine MAPL_GeosNameNew
Call graph
mapl_geosnamenew calls mapl_geosnamenew
mapl_cfiocreatefrombundle calls mapl_geosnamenew
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_simplebundlewrite1 calls mapl_cfiocreate
test_main calls esmf_iocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate