MAPL_GetCorrectedPhase – MAPL
MAPL_GetCorrectedPhase Module Function
11 statements
Source File
module function MAPL_GetCorrectedPhase(gc, rc) result(phase) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
  module function MAPL_GetCorrectedPhase(gc,rc) result(phase)
     type(ESMF_GridComp), intent(inout) :: gc
     integer, optional, intent(out) :: rc
     integer :: phase
     integer :: status
     call ESMF_GridCompGet(gc,currentPhase=phase,_RC)
     if (phase>10) phase=phase-10
     _RETURN(_SUCCESS)
  end function MAPL_GetCorrectedPhase
Call graph
mapl_getcorrectedphase calls ESMF_GridCompGet, mapl_return, mapl_verify, mapl_getcorrectedphase
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize