MAPL_SunGetSolarConstantByTime – MAPL
MAPL_SunGetSolarConstantByTime Subroutine
14 statements
Source File
private subroutine MAPL_SunGetSolarConstantByTime(Time, SC, HK, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: Time
real, intent(out) :: SC
real, intent(out), optional :: HK(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_SunGetSolarConstantByTime
Source Code
    subroutine MAPL_SunGetSolarConstantByTime(Time,SC,HK,rc)
      type (ESMF_Time),  intent(INOUT) :: Time
      real,              intent(OUT)   :: SC
      real,   optional,  intent(OUT)   :: HK(:)
      integer, optional, intent(OUT)   :: rc
      integer    :: YY, DOY
      integer    :: STATUS
      call ESMF_TimeGet (TIME, YY=YY, DayOfYear=DOY, RC=STATUS)
      _VERIFY(STATUS)
      call MAPL_SunGetSolarConstantByYearDoY(YY,DOY,SC,HK, RC=STATUS)
      _VERIFY(STATUS)
      _RETURN(ESMF_SUCCESS)
    end subroutine MAPL_SunGetSolarConstantByTime
Call graph
mapl_sungetsolarconstantbytime calls ESMF_TimeGet, mapl_return, mapl_sungetsolarconstantbyyeardoy, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_sungetsolarconstantbyyeardoy calls mapl_return, mapl_assert
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_sungetsolarconstant calls mapl_sungetsolarconstantbytime