MAPL_Fail – MAPL
MAPL_Fail Subroutine
28 statements
Source File
private subroutine MAPL_Fail(filename, line, message)
Uses
mpi
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
integer, intent(in) :: line
character(len=*), intent(in), optional :: message
Calls
Source Code
   subroutine MAPL_Fail(filename, line, message)
      use MPI
      use, intrinsic :: iso_fortran_env, only: ERROR_UNIT
      character(*), intent(in) :: filename
      integer, intent(in) :: line
      character(*), optional, intent(in) :: message
      integer, parameter :: FIELD_WIDTH=40
      character(FIELD_WIDTH) :: use_name
      character(3) :: prefix
      character(:), allocatable :: base_name
      integer :: rank, ierror
      logical :: is_mpi_initialized
      call MPI_Initialized(is_mpi_initialized,ierror)
      base_name = get_base_name(filename)
      if (len(base_name) > FIELD_WIDTH) then
         prefix = '...'
         use_name = base_name(2:)
      else
         prefix = '   '
         use_name = base_name
      end if
      ! Could use ADVANCE='no', but this may increase the chance
      ! that the output lines are not interrupted by messages from
      ! other PEs
      if (is_mpi_initialized) then
         call MPI_Comm_rank(MPI_COMM_WORLD, rank, ierror)
         !$omp critical (MAPL_Throw1)
         write(ERROR_UNIT,'(a,i5.5,1x,a,i5.5,1x,a3,a40,1x,a)') &
              & 'pe=', rank, 'FAIL at line=', line, prefix, use_name, &
              & '<'//adjustl(trim(message))//'>'
         !$omp end critical (MAPL_Throw1)
      else
         !$omp critical (MAPL_Throw1)
         write(ERROR_UNIT,'(a,i5.5,1x,a3,a40,1x,a)') &
              & 'FAIL at line=', line, prefix, use_name, &
              & '<'//adjustl(trim(message))//'>'
         !$omp end critical (MAPL_Throw1)
      end if
   end subroutine MAPL_Fail
Call graph
mapl_fail calls mpi_comm_rank, mpi_initialized, get_base_name