MAPL_FieldF90Deallocate – MAPL
MAPL_FieldF90Deallocate Module Subroutine
31 statements
Source File
module subroutine MAPL_FieldF90Deallocate(field, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_FieldF90Deallocate
Source Code
  module subroutine MAPL_FieldF90Deallocate(field, rc)
    type(ESMF_Field),  intent(INOUT) :: field
    integer, optional, intent(  OUT) :: rc
    integer                                 :: status
    character(len=ESMF_MAXSTR), parameter   :: IAm='MAPL_FieldF90Deallocate'
    type(ESMF_Array)                        :: array
    type(ESMF_FieldStatus_Flag)             :: fieldStatus
    type (ESMF_LocalArray), target          :: larrayList(1)
    type (ESMF_LocalArray), pointer         :: larray
    integer                                 :: localDeCount
    integer                                 :: rank
    type(ESMF_TypeKind_Flag)                :: tk
    call ESMF_FieldGet(field, status=fieldStatus, rc=status)
    _VERIFY(STATUS)
    if (fieldStatus == ESMF_FIELDSTATUS_COMPLETE) then
       call ESMF_FieldGet(field, Array=array, rc=status)
       _VERIFY(STATUS)
       call ESMF_ArrayGet(array, localDeCount=localDeCount, rc=status)
       _VERIFY(STATUS)
       _ASSERT(localDeCount == 1, 'currently MAPL supports only 1 local array')
       call ESMF_ArrayGet(array, localarrayList=larrayList, rc=status)
       _VERIFY(STATUS)
       larray => lArrayList(1) ! alias
       call ESMF_LocalArrayGet(larray, rank=rank, typekind=tk, &
            rc=status)
       _VERIFY(STATUS)
       call ESMF_LocalArrayF90Deallocate(larray, typekind=tk, rank=rank, rc=status)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldF90Deallocate
Call graph
mapl_fieldf90deallocate calls esmf_arrayget, esmf_fieldget, esmf_localarrayf90deallocate, esmf_localarrayget, mapl_assert, mapl_return, mapl_verify, mapl_fieldf90deallocate
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize