MAPL_CommsSend_I4_1 – MAPL
MAPL_CommsSend_I4_1 Subroutine
20 statements
Source File
private subroutine MAPL_CommsSend_I4_1(layout, data, COUNT, DEST, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: DEST
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commssend_i4_1 calls esmf_delayoutget, mapl_return, esmf_vmget, mapl_verify, mpi_send
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_commssend calls mapl_commssend_i4_1