MAPL_ExtDataReadPrefetch – MAPL
MAPL_ExtDataReadPrefetch Subroutine
20 statements
Source File
private subroutine MAPL_ExtDataReadPrefetch(IOBundles, rc)
Arguments
Type Intent Optional Attributes Name
type(IoBundleNGVector), intent(inout), target :: IOBundles
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataReadPrefetch(IOBundles,rc)
     type(IOBundleNGVector), target, intent(inout) :: IOBundles
     integer, optional,      intent(out  ) :: rc
     integer :: nfiles, n
     type (ExtDataNG_IOBundle), pointer :: io_bundle
     integer :: status
     nfiles = IOBundles%size()
     do n=1, nfiles
        io_bundle => IOBundles%at(n)
        if (io_bundle%on_tiles) then
           call io_bundle%tile_io%process_data_from_file(_RC)
        else
           call io_bundle%grid_io%process_data_from_file(_RC)
        end if
     enddo
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataReadPrefetch
Call graph
mapl_extdatareadprefetch calls at, mapl_return, mapl_verify, process_data_from_file
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
process_data_from_file calls mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldget, arrayscatter, mapl_assert, mapl_tilemaskget
run_ calls mapl_extdatareadprefetch