MAPL_AddConnectivityRename – MAPL
MAPL_AddConnectivityRename Subroutine
17 statements
Source File
private subroutine MAPL_AddConnectivityRename(GC, SRC_NAME, SRC_ID, DST_NAME, DST_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SRC_NAME
integer, intent(in) :: SRC_ID
character(len=*), intent(in) :: DST_NAME
integer, intent(in) :: DST_ID
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_AddConnectivityRename ( GC, SRC_NAME, SRC_ID, &
        DST_NAME, DST_ID, RC  )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*),              intent(IN   ) :: SRC_NAME !FROM_NAME==SHORT_NAME
      character (len=*),              intent(IN   ) :: DST_NAME !TO_NAME
      integer,                        intent(IN   ) :: SRC_ID !FROM_EXPORT
      integer,                        intent(IN   ) :: DST_ID !TO_IMPORT
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_AddConnectivityRename"
      integer                               :: status
      type (MAPL_Connectivity), pointer     :: conn
      call MAPL_ConnectivityGet(gc, connectivityPtr=conn, RC=status)
      _VERIFY(status)
      call CONN%CONNECT%append(SHORT_NAME=SRC_NAME, TO_NAME=DST_NAME,        &
           FROM_EXPORT=SRC_ID, TO_IMPORT=DST_ID, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_AddConnectivityRename
Call graph
mapl_addconnectivityrename calls append, mapl_connectivityget, mapl_return, mapl_verify
append calls mapl_return, resize, vector_back
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
vector_resize_size_kind calls reserve
mapl_addconnectivity calls mapl_addconnectivityrename, mapl_addconnectivitymany, mapl_addconnectivityrenamemany
mapl_addconnectivitymany calls mapl_addconnectivityrename
mapl_addconnectivityrenamemany calls mapl_addconnectivity