MAPL_LocStreamAdjustNsubtiles – MAPL
MAPL_LocStreamAdjustNsubtiles Subroutine
14 statements
Source File
public subroutine MAPL_LocStreamAdjustNsubtiles(LocStream, NSUBTILES, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(inout) :: LocStream
integer, intent(in) :: NSUBTILES
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_LocStreamAdjustNsubtiles
Source Code
  subroutine MAPL_LocStreamAdjustNsubtiles(LocStream, NSUBTILES, RC)
    type(MAPL_LocStream),  intent(INOUT) :: LocStream
    integer,               intent(IN   ) :: NSUBTILES
    integer, optional,     intent(  OUT) :: RC
! Local variables
    integer                    :: STATUS
    type(MAPL_LocStreamType), pointer :: STREAM
! Alias to the pointer
!---------------------
    STREAM => LocStream%Ptr
!======================================================
! Check if the location stream is already attached
!-------------------------------------------------
    if (stream%current_tiling > 0) then
       call ESMF_AttributeSet(stream%tilegrid, name='GRID_EXTRADIM', &
            value=NSUBTILES, rc=status)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_LocStreamAdjustNsubtiles
Call graph
mapl_locstreamadjustnsubtiles calls esmf_attributeset, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_genericinitialize calls mapl_locstreamadjustnsubtiles
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
my_initialize calls mapl_genericinitialize