MAPL_SetPointer3DR4 – MAPL
MAPL_SetPointer3DR4 Module Subroutine
50 statements
Source File
module subroutine MAPL_SetPointer3DR4(state, ptr, name, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
real, pointer :: ptr(:,:,:)
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_SetPointer3DR4
Source Code
  module subroutine MAPL_SetPointer3DR4(state, ptr, name, rc)
    type(ESMF_State),               intent(INOUT) :: state
    real,                           pointer       :: ptr(:,:,:)
    character(len=*),               intent(IN   ) :: name
    integer,              optional, intent(  OUT) :: rc
    integer                               :: status
    character(len=ESMF_MAXSTR), parameter :: IAm='MAPL_SetPointer3DR4'
    type(ESMF_Field)                      :: field
    type(ESMF_FieldBundle)                :: bundle
    type(ESMF_Grid)                       :: GRID
    integer                               :: COUNTS(ESMF_MAXDIM)
    integer                               :: gridRank
    integer                               :: I
    integer                               :: loc
    integer, allocatable                  :: gridToFieldMap(:)
    type(ESMF_FieldStatus_Flag)             :: fieldStatus
    _ASSERT(associated(ptr), 'unassociated pointer')
    ! Get Field from state
    loc = index(name,';;')
    if(loc/=0) then
       call ESMF_StateGet(state, name(:loc-1), Bundle, rc=status)
       _VERIFY(STATUS)
       call ESMF_StateGet(state, name(loc+2:), Field, rc=status)
       _VERIFY(STATUS)
    else
       call ESMF_StateGet(state, name, Field, rc=status)
       _VERIFY(STATUS)
    end if
    call ESMF_FieldGet(field, status=fieldStatus, rc=status)
    _VERIFY(STATUS)
    _ASSERT(fieldStatus /= ESMF_FIELDSTATUS_COMPLETE, 'fieldStatus == ESMF_FIELDSTATUS_COMPLETE')
    call ESMF_FieldGet(field, grid=GRID, RC=STATUS)
    _VERIFY(STATUS)
    call MAPL_GridGet(GRID, localCellCountPerDim=COUNTS, RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(size(ptr,1) == COUNTS(1), 'shape mismatch dim=1')
    _ASSERT(size(ptr,2) == COUNTS(2), 'shape mismatch dim=2')
    call ESMF_GridGet(GRID, dimCount=gridRank, rc=status)
    _VERIFY(STATUS)
    ! MAPL restriction (actually only the first 2 dims are distributted)
    _ASSERT(gridRank <= 3, 'gridRank > 3 not supported')
    allocate(gridToFieldMap(gridRank), stat=status)
    _VERIFY(STATUS)
    do I = 1, gridRank
       gridToFieldMap(I) = I
    end do
    call ESMF_FieldEmptyComplete(FIELD, farrayPtr=ptr, &
         datacopyFlag = ESMF_DATACOPY_REFERENCE,       &
         gridToFieldMap=gridToFieldMap,                &
         rc = status)
    _VERIFY(STATUS)
    ! Clean up
    deallocate(gridToFieldMap)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_SetPointer3DR4
Call graph
mapl_setpointer3dr4 calls mapl_assert, esmf_stateget, esmf_fieldget, mapl_verify, mapl_gridget, esmf_gridget, esmf_fieldemptycomplete, mapl_return, mapl_setpointer3dr4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_gridget calls mapl_verify, esmf_gridget, mapl_return, esmf_attributeget, mapl_gridhasde
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_gridhasde calls mapl_verify, esmf_gridget, mapl_return, esmf_distgridget, esmf_delayoutget
mapl_setpointer calls mapl_setpointer3dr4