MAPL_LinkCreate – MAPL
MAPL_LinkCreate Subroutine
35 statements
Source File
private subroutine MAPL_LinkCreate(LINK, GC_FROM, STATETYPE_FROM, SPECINDEX_FROM, GC_TO, STATETYPE_TO, SPECINDEX_TO, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_Link), pointer :: LINK(:)
type(ESMF_GridComp), intent(in) :: GC_FROM
integer, intent(in) :: STATETYPE_FROM
integer, intent(in) :: SPECINDEX_FROM
type(ESMF_GridComp), intent(in) :: GC_TO
integer, intent(in) :: STATETYPE_TO
integer, intent(in) :: SPECINDEX_TO
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_LinkCreate(LINK,              &
        GC_FROM, STATETYPE_FROM, SPECINDEX_FROM, &
        GC_TO,   STATETYPE_TO,   SPECINDEX_TO,   &
        RC )
      type (MAPL_Link),              pointer     :: LINK(:)
      type(ESMF_GridComp),        intent(IN   )  :: GC_FROM
      integer,                    intent(IN   )  :: STATETYPE_FROM
      integer,                    intent(IN   )  :: SPECINDEX_FROM
      type(ESMF_GridComp),        intent(IN   )  :: GC_TO
      integer,                    intent(IN   )  :: STATETYPE_TO
      integer,                    intent(IN   )  :: SPECINDEX_TO
      integer,          optional, intent(  OUT)  :: RC     ! Error code:
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_LinkCreate"
      integer                               :: status
      integer                               :: I
      type (MAPL_Link ), pointer         :: TMP(:)
      type (MAPL_LinkType) :: FROM
      type (MAPL_LinkType) :: TO
      if(.not. associated(LINK)) then
         allocate(LINK(0),stat=status)
         _VERIFY(status)
      else
         !ALT: check for duplicates ???
      endif
      I = size(LINK)
      allocate(TMP(I+1),stat=status)
      _VERIFY(status)
      TMP(1:I) = LINK
      deallocate(LINK, stat=status)
      _VERIFY(status)
      allocate(TMP(I+1)%Ptr,stat=status)
      _VERIFY(status)
      FROM = MAPL_LinkType(GC_FROM, STATETYPE_FROM, SPECINDEX_FROM)
      TO   = MAPL_LinkType(GC_TO,   STATETYPE_TO,   SPECINDEX_TO  )
      TMP(I+1)%Ptr = MAPL_LinkForm(FROM, TO)
      LINK => TMP
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_LinkCreate
Call graph
mapl_linkcreate calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_reconnect calls mapl_linkcreate
mapl_wirecomponent calls mapl_reconnect
mapl_genericsetservices calls mapl_wirecomponent
setservices calls mapl_genericsetservices