MAPL_ArrayReadNCpar_1d – MAPL
MAPL_ArrayReadNCpar_1d Subroutine
31 statements
Source File
private subroutine MAPL_ArrayReadNCpar_1d(varn, filename, farrayPtr, arrDes, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: varn
character(len=*), intent(in) :: filename
real, pointer :: farrayPtr(:)
type(ArrDescr), intent(inout) :: arrDes
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ArrayReadNCpar_1d(varn,filename,farrayPtr,arrDes,rc)
  character(len=*),      intent(IN   )  :: varn
  character(len=*),      intent(IN   )  :: filename
  real, pointer                         :: farrayPtr(:)
  type(arrDescr),        intent(INOUT)  :: arrDes
  integer, optional,     intent(OUT  )  :: rc
  character(len=*), parameter           :: Iam="MAPL_ArrayReadNCpar_1d"
  integer                               :: status
  type(ESMF_Field)                      :: field
  type(ESMF_FieldBundle)                :: bundle
  FIELD = ESMF_FieldCreate(grid=arrDes%grid, datacopyflag=ESMF_DATACOPY_VALUE, &
         farrayPtr=farrayPtr, name=trim(varn), RC=STATUS)
  _VERIFY(STATUS)
  if (arrDes%tile) then
     call ESMF_AttributeSet(field,name='DIMS',value=MAPL_DimsTileOnly,rc=status)
     _VERIFY(STATUS)
  endif
  BUNDLE =  ESMF_FieldBundleCreate ( name=Iam, rc=STATUS )
  _VERIFY(STATUS)
  call ESMF_FieldBundleSet ( bundle, grid=arrDes%grid, rc=STATUS )
  _VERIFY(STATUS)
  call MAPL_FieldBundleAdd(BUNDLE, FIELD, rc=STATUS)
  _VERIFY(STATUS)
  call MAPL_VarReadNCPar(Bundle, arrdes, filename, rc=status)
  _VERIFY(STATUS)
  call ESMF_FieldBundleDestroy(bundle,rc=status)
  _VERIFY(STATUS)
  call ESMF_FieldDestroy(field,rc=status)
  _VERIFY(STATUS)
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ArrayReadNCpar_1d
Call graph
mapl_arrayreadncpar_1d calls ESMF_AttributeSet, esmf_fieldbundlecreate, esmf_fieldbundledestroy, esmf_fieldbundleset, esmf_fieldcreate, esmf_fielddestroy, mapl_fieldbundleadd, mapl_varreadncpar, mapl_return, mapl_verify
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_varreadncpar calls mapl_arrayreadncpar_1d, mapl_arrayreadncpar_2d, mapl_arrayreadncpar_3d, mapl_bundlereadncpar, mapl_statevarreadncpar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_arrayreadncpar_2d calls mapl_varreadncpar
mapl_arrayreadncpar_3d calls mapl_varreadncpar
mapl_esmfstatereadfromfile calls mapl_varreadncpar
mapl_statevarreadncpar calls mapl_varreadncpar
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_staterefresh calls mapl_esmfstatereadfromfile
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore