MAPL_LocStreamTransformT2T – MAPL
MAPL_LocStreamTransformT2T Subroutine
60 statements
Source File
private subroutine MAPL_LocStreamTransformT2T(OUTPUT, XFORM, INPUT, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: OUTPUT(:)
type(MAPL_LocStreamXform), intent(in) :: XFORM
real, intent(in) :: INPUT(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
subroutine MAPL_LocStreamTransformT2T (OUTPUT, XFORM, INPUT, RC)
  !ARGUMENTS:
  real,                      intent(OUT) :: OUTPUT(:)
  type(MAPL_LocStreamXform), intent(IN ) :: XFORM
  real,                      intent(IN ) :: INPUT(:)
  integer, optional,         intent(OUT) :: RC
  !EOPI
! Local variables
  integer                     :: STATUS
  integer                     :: N, offset
  integer                     :: me
  real,   allocatable         :: FULLINPUT(:)
#if defined(TWO_SIDED_COMM)
  integer, allocatable        :: request(:)
  integer                     :: msg_tag
  integer                     :: count
  integer                     :: NumReceivers
  integer                     :: mpstatus(MPI_STATUS_SIZE)
#elif defined(ONE_SIDED_COMM)
  logical                     :: use_lock
  use_lock = .false.
#endif
  _ASSERT(associated(Xform%PTR),'needs informative message')
  do N = 1,Xform%PTR%LastLocal
     OUTPUT(Xform%PTR%IndexOut(N)) = INPUT(Xform%PTR%IndexIn(N))
  end do
  if(.not.Xform%PTR%Local) then
     if (Xform%PTR%do_not_use_fcollect) then
     me = Xform%PTR%myId
#if defined(TWO_SIDED_COMM)
     msg_tag = me
     count = size(input)
     NumReceivers = size(Xform%PTR%receivers)
     allocate(request(NumReceivers), stat=status)
     _VERIFY(status)
     do n=1, NumReceivers
        call MPI_ISend(input, count, MPI_REAL, &
                       Xform%PTR%receivers(n), msg_tag, &
                       Xform%PTR%Comm, request(n), status)
        _VERIFY(status)
     end do
#elif defined(ONE_SIDED_COMM)
     if (use_lock) then
        call MPI_WIN_LOCK(MPI_LOCK_EXCLUSIVE, me, 0, Xform%PTR%window, status)
        _VERIFY(STATUS)
     end if
     Xform%Ptr%Buff = input
     if (use_lock) then
        call MPI_WIN_UNLOCK(me, Xform%PTR%window, status)
        _VERIFY(STATUS)
        call mpi_Barrier(Xform%PTR%Comm,STATUS)
        _VERIFY(STATUS)
     end if
#endif
     allocate(FULLINPUT(Xform%Ptr%InputLen),STAT=STATUS)
     _VERIFY(STATUS)
#if defined(ONE_SIDED_COMM)
     if (.not. use_lock) then
        call mpi_win_fence(0, Xform%PTR%window, status)
        _VERIFY(STATUS)
     endif
#endif
     offset = 1
     if (associated(Xform%PTR%senders)) then
        do n=1,size(Xform%PTR%senders)
#if defined(TWO_SIDED_COMM)
! ALT: the senders' id is also used as a mpi_tag
           msg_tag = Xform%PTR%senders(N)
           call MPI_RECV(FULLINPUT(offset), Xform%PTR%len(N), MPI_REAL, &
                         Xform%PTR%senders(N), msg_tag, &
                         Xform%Ptr%Comm, mpstatus, status)
           _VERIFY(STATUS)
#elif defined(ONE_SIDED_COMM)
           if (use_lock) then
              call MPI_WIN_LOCK(MPI_LOCK_SHARED, Xform%PTR%senders(N), &
                   0, Xform%PTR%window, status)
              _VERIFY(STATUS)
           end if
           call MPI_GET(FULLINPUT(offset),       Xform%PTR%len(N), MPI_REAL, &
                        Xform%PTR%senders(N), 0, Xform%PTR%len(N), MPI_REAL, &
                        Xform%PTR%window,                               STATUS)
           _VERIFY(STATUS)
           if (use_lock) then
              call MPI_WIN_UNLOCK(Xform%PTR%senders(N), Xform%PTR%window, status)
              _VERIFY(STATUS)
           end if
#endif
           offset = offset + Xform%PTR%len(N)
        enddo
     endif
#if defined(TWO_SIDED_COMM)
     do n=1, NumReceivers
        call MPI_Wait(request(n),MPI_STATUS_IGNORE,status)
        _VERIFY(STATUS)
     end do
     if (allocated(request)) deallocate(request)
#elif defined(ONE_SIDED_COMM)
     if (.not. use_lock) then
        call mpi_win_fence(0, Xform%PTR%window, status)
        _VERIFY(STATUS)
     endif
#endif
     else
     allocate(FULLINPUT(Xform%Ptr%InputStream%Ptr%NT_GLOBAL),STAT=STATUS)
     _VERIFY(STATUS)
     call ESMFL_FCOLLECT(Xform%Ptr%InputStream%Ptr%TILEGRID, FULLINPUT, INPUT, RC=STATUS)
     _VERIFY(STATUS)
     endif
     do N = Xform%PTR%LastLocal+1,Xform%PTR%Count
        OUTPUT(Xform%PTR%IndexOut(N)) = FULLINPUT(Xform%PTR%IndexIn(N))
     end do
     deallocate(FULLINPUT)
  end if
  _RETURN(ESMF_SUCCESS)
end subroutine MAPL_LocStreamTransformT2T
Call graph
mapl_locstreamtransformt2t calls esmfl_fcollect, mapl_assert, mpi_isend, mpi_recv, mpi_wait, mapl_return, mapl_verify
esmfl_fcollect calls esmfl_fcollect_i4, esmfl_fcollect_r4, esmfl_fcollect_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_fcollect_i4 calls mapl_assert, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_commsallgatherv, mapl_distgridget
esmfl_fcollect_r4 calls mapl_assert, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_commsallgatherv, mapl_distgridget
esmfl_fcollect_r8 calls mapl_assert, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_commsallgatherv, mapl_distgridget
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_commsallgatherv calls mapl_commsallgatherv_i4_1, mapl_commsallgatherv_r4_1, mapl_commsallgatherv_r8_1
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_locstreamtransform calls mapl_locstreamtransformt2t, mapl_locstreamtransformt2tr4r8, mapl_locstreamtransformt2tr8r4
mapl_locstreamtransformt2tr4r8 calls mapl_locstreamtransformt2t
mapl_locstreamtransformt2tr8r4 calls mapl_locstreamtransformt2t
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run calls regridtransform, regridtransformt2g, regridtransformt2g2g
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2