MAPL_SetStateSave – MAPL
MAPL_SetStateSave Subroutine
16 statements
Source File
public recursive subroutine MAPL_SetStateSave(state, filetype, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: state
integer, intent(in) :: filetype
integer, intent(out), optional :: rc
Calls
Source Code
   recursive subroutine MAPL_SetStateSave(state,filetype,rc)
      type(MAPL_MetaComp), intent(inout) :: state
      integer,             intent(in ) :: filetype
      integer, optional,   intent(out) :: rc
      type(MAPL_MetaComp), pointer :: CMAPL => null()
      integer :: k, status
      type(ESMF_GridComp), pointer :: gridcomp
      do k=1,state%get_num_children()
         gridcomp => state%GET_CHILD_GRIDCOMP(K)
         call MAPL_GetObjectFromGC ( gridcomp, CMAPL, RC=status)
         _VERIFY(status)
         call MAPL_SetStateSave(CMAPL,filetype,RC=status)
         _VERIFY(status)
      enddo
      state%initial_state%filetype = filetype
   end subroutine MAPL_SetStateSave
Call graph
mapl_setstatesave calls mapl_setstatesave, mapl_getobjectfromgc, get_child_gridcomp, get_num_children, mapl_verify
mapl_getobjectfromgc calls mapl_internalstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_verify calls mapl_throw_exception
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_internalstateget calls mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState, mapl_return
mapl_throw_exception calls initialize
mapl_return calls mapl_throw_exception, get_error_message