MAPL_ArrayIScatter_R4_2 – MAPL
MAPL_ArrayIScatter_R4_2 Subroutine
54 statements
Source File
private subroutine MAPL_ArrayIScatter_R4_2(global_array, request, hw, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: global_array(:,:)
type(MAPL_CommRequest), intent(inout) :: request
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ArrayIScatter_R4_2(global_array, request, hw, rc)
    real,                    intent(IN   ) :: global_array (:,:)
    type (MAPL_CommRequest), intent(INOUT) :: request
    integer, optional,       intent(   IN) :: hw
    integer, optional,       intent(  OUT) :: rc
! Local variables
    integer                    :: status
    integer                    :: i1,in,j1,jn
    integer                    :: n, count, hw_, j
    real, allocatable          :: global_array_(:,:)
    if (present(hw)) then
       hw_ = hw
    else
       hw_ = 0
    end if
! Post sends from all processors except root
!-------------------------------------------
    if(request%amRoot) then
       !if have halo, make local copy and halo global
       if (hw_ > 0) then
          allocate(Global_Array_(1-hw_:request%im_world+hw_,1-hw_:request%jm_world+hw_))
          Global_Array_(1:request%im_world,1:request%jm_world) = Global_Array
          do j=1,hw_
             ! x-direction
             Global_Array_(1-j,:) = Global_Array_(request%im_world-j+1,:)
             Global_Array_(request%im_world+j,:) = Global_Array_(j,:)
             ! y-direction
             Global_Array_(:,1-j) = MAPL_UNDEF
             Global_Array_(:,request%jm_world+j) = MAPL_UNDEF
          enddo
       endif
       allocate(request%Buff(0:request%nDEs-1))
       PEs: do n=0,request%nDEs-1
          count = request%IM(n)*request%JM(n)
          i1 = request%i1(n)
          in = request%in(n)
          j1 = request%j1(n)
          jn = request%jn(n)
          if(n == request%mype) then
             if (hw_ > 0) then
                 request%DstArray = Global_Array_(i1:in,j1:jn)
             else
                 request%DstArray = Global_Array(i1:in,j1:jn)
             end if
          else
             allocate(request%Buff(n)%A(request%im(n), request%jm(n)))
             if (hw_ > 0) then
                  request%Buff(n)%A = Global_Array_(i1:in,j1:jn)
             else
                  request%Buff(n)%A = Global_Array(i1:in,j1:jn)
             end if
             call MPI_ISend(request%Buff(n)%A, count, MPI_REAL, &
                  n, request%tag, request%comm, request%send(n),  status)
             _VERIFY(STATUS)
          end if
       end do PEs
       if (hw_ > 0) deallocate(Global_Array_)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ArrayIScatter_R4_2
Call graph
mapl_arrayiscatter_r4_2 calls mpi_isend, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_arrayiscatter calls mapl_arrayiscatter_r4_2
mapl_cfioreadbundleread calls mapl_arrayiscatter
mapl_collectivescatter3d calls mapl_arrayiscatter
mapl_cfioreadbundle calls mapl_collectivescatter3d
mapl_cfioreadparallel_ calls mapl_cfioreadbundleread
regrid_scalar_3d_real32 calls mapl_collectivescatter3d
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle