MAPL_StatePrintSpec – MAPL
MAPL_StatePrintSpec Subroutine
48 statements
Source File
private recursive subroutine MAPL_StatePrintSpec(GC, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_StatePrintSpec
Source Code
   recursive subroutine MAPL_StatePrintSpec(GC, RC)
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)            :: IAm='MAPL_StatePrintSpec'
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: MAPLOBJ
      type (MAPL_VarSpec),               pointer  :: IMPORT_SPEC(:)
      type (MAPL_VarSpec),               pointer  :: EXPORT_SPEC(:)
      integer                                     :: I
      type(ESMF_GridComp), pointer :: gridcomp
      !EOP
      ! Get my name and set-up traceback handle
      ! ---------------------------------------
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      ! Retrieve the pointer to the internal state
      ! --------------------------------------------
      call MAPL_InternalStateRetrieve ( GC, MAPLOBJ, RC=status )
      _VERIFY(status)
      IMPORT_SPEC => MAPLOBJ%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      EXPORT_SPEC => MAPLOBJ%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      if (associated(IMPORT_SPEC)) then
         call WRITE_PARALLEL("==========================")
         call WRITE_PARALLEL("IMPORT spec for " // trim(comp_name))
         call WRITE_PARALLEL("==========================")
         if (associated(IMPORT_SPEC)) then
            do I = 1, size(IMPORT_SPEC)
               call MAPL_VarSpecPrint(IMPORT_SPEC(I), RC=status)
               _VERIFY(status)
            end do
         end if
      end if
      if (associated(EXPORT_SPEC)) then
         call WRITE_PARALLEL("==========================")
         call WRITE_PARALLEL("EXPORT spec for " // trim(comp_name))
         call WRITE_PARALLEL("==========================")
         if (associated(EXPORT_SPEC)) then
            do I = 1, size(EXPORT_SPEC)
               call MAPL_VarSpecPrint(EXPORT_SPEC(I), RC=status)
               _VERIFY(status)
            end do
         end if
      end if
      do I = 1, MAPLOBJ%get_num_children()
         gridcomp => MAPLOBJ%GET_CHILD_GRIDCOMP(I)
         call MAPL_StatePrintSpec(gridcomp, RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StatePrintSpec
Call graph
mapl_stateprintspec calls mapl_stateprintspec, esmf_gridcompget, mapl_internalstateretrieve, mapl_verify, mapl_varspecprint, write_parallel, mapl_return
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_verify calls mapl_throw_exception
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
write_parallel calls write_parallel_r8_1, write_parallel_i4_0, write_parallel_r4_1, write_parallel_i4_1, write_parallel_r8_0, write_parallel_r4_0, write_parallel_string_0
mapl_return calls mapl_throw_exception, get_error_message
write_parallel_r8_1 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, alloc_, mpi_file_write
mapl_internalstateget calls esmf_gridcompget, mapl_verify, mapl_return, esmf_usercompgetinternalstate
mapl_internalstatecreate calls esmf_gridcompget, mapl_verify, mapl_return, esmf_usercompsetinternalstate
mapl_varspecprintmany calls mapl_verify, mapl_varspecprint, mapl_return
mapl_throw_exception calls initialize
mapl_varspecprintone calls mapl_return
write_parallel_i4_0 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_
write_parallel_r4_1 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, alloc_, mpi_file_write
write_parallel_i4_1 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, alloc_, mpi_file_write
write_parallel_r8_0 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_
write_parallel_r4_0 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_
write_parallel_string_0 calls mapl_verify, mapl_return, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write