MAPL_AllocNodeArray_4DI4 – MAPL
MAPL_AllocNodeArray_4DI4 Module Procedure
16 statements
Source File
module procedure MAPL_AllocNodeArray_4DI4 module subroutine MAPL_AllocNodeArray_4DI4(Ptr, Shp, lbd, rc) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), pointer :: Ptr(:,:,:,:)
integer, intent(in) :: Shp(4)
integer, intent(in), optional :: lbd(4)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_allocnodearray_4di4 calls getsharedmemory, mapl_assert, mapl_return, mapl_verify, mapl_allocnodearray_4di4
getsharedmemory calls getsharedmemory, mapl_assert, mapl_return, shmat, shmget, mpi_barrier, segs, segsnew
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_allocnodearray calls mapl_allocnodearray_4di4
initialize_subclass calls mapl_allocnodearray
mapl_allocateshared_1di4 calls mapl_allocnodearray
mapl_allocateshared_1dl4 calls mapl_allocnodearray
mapl_allocateshared_1dr4 calls mapl_allocnodearray
mapl_allocateshared_1dr8 calls mapl_allocnodearray
mapl_allocateshared_2dr4 calls mapl_allocnodearray
mapl_allocateshared_2dr8 calls mapl_allocnodearray
mapl_cfioreadbundle calls mapl_allocnodearray
mapl_cfiowritebundlepost calls mapl_allocnodearray
mapl_tilemaskget calls mapl_allocnodearray
mapl_varread_r4_1d calls mapl_allocnodearray
mapl_varread_r4_2d calls mapl_allocnodearray