MAPL_CommsRecv_I4_1 – MAPL
MAPL_CommsRecv_I4_1 Subroutine
21 statements
Source File
private subroutine MAPL_CommsRecv_I4_1(layout, data, COUNT, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: COUNT
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commsrecv_i4_1 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_recv, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_commsrecv calls mapl_commsrecv_i4_1