MAPL_LocStreamTransformT2G – MAPL
MAPL_LocStreamTransformT2G Subroutine
123 statements
Source File
private subroutine MAPL_LocStreamTransformT2G(LocStream, OUTPUT, INPUT, MASK, SAMPLE, TRANSPOSE, variance, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
real, intent(inout) :: OUTPUT(:,:)
real, intent(inout) :: INPUT(:)
logical, intent(in), optional :: MASK(:)
logical, intent(in), optional :: SAMPLE
logical, intent(in), optional :: TRANSPOSE
logical, intent(in), optional :: variance
integer, intent(out), optional :: RC
Calls
Called by
Source Code
subroutine MAPL_LocStreamTransformT2G (LocStream, OUTPUT, INPUT, MASK, SAMPLE, TRANSPOSE, variance, RC)
  !ARGUMENTS:
  type(MAPL_LocStream),      intent(IN ) :: LocStream
  real,                      intent(INOUT) :: OUTPUT(:,:)
  real,                      intent(INOUT) :: INPUT(:)
  logical, optional,         intent(IN ) :: MASK(:)
  logical, optional,         intent(IN ) :: SAMPLE
  logical, optional,         intent(IN ) :: TRANSPOSE
  logical, optional,         intent(IN ) :: variance
  integer, optional,         intent(OUT) :: RC
  !EOPI
! Local variables
  integer                    :: STATUS
  real,         allocatable  :: FF(:,:),tmpOut(:,:)
  integer                    :: II, JJ, N, I1, IN, J1, JN
  logical,      allocatable  :: usableMASK(:)
  logical                    :: uSAMPLE
  logical                    :: usableTRANSPOSE
  logical                    :: computeVariance
! Make sure Location stream has been created...
!----------------------------------------------
  _ASSERT(associated(LocStream%Ptr),'needs informative message')
! and a grid attached...
!-----------------------
  _ASSERT(LocStream%Ptr%Current_Tiling > 0,'needs informative message')
! that's the size of the output array
!------------------------------------
  call MAPL_GRID_INTERIOR  (LocStream%Ptr%GRID, I1,IN,J1,JN)
  _ASSERT(IN-I1+1==size(OUTPUT,1),'needs informative message')
  _ASSERT(JN-J1+1==size(OUTPUT,2),'needs informative message')
! Allocate space for mask and cumulative weight at each grid point
!------------------------------------------------------------
  allocate(FF(size(OUTPUT,1),size(OUTPUT,2)), stat=STATUS)
  _VERIFY(STATUS)
  FF = 0.0
  allocate(usableMASK(size(INPUT)), STAT=STATUS)
  _VERIFY(STATUS)
! Make usable mask from optional argument
!----------------------------------------
  if (present(MASK)) then
     usableMASK = MASK
  else
     usableMASK = .TRUE.
  end if
  if (present(SAMPLE)) then
     uSAMPLE = SAMPLE
  else
     uSAMPLE = .false.
  end if
  if (present(variance)) then
     computeVariance=variance
  else
     computeVariance=.false.
  end if
  if(present(TRANSPOSE)) then
     usableTRANSPOSE = TRANSPOSE
  else
     usableTRANSPOSE = .false.
  end if
  if (computeVariance .and. usableTranspose) then
     _FAIL("Can not compute variance and transpose in LocStream!")
  end if
  if (computeVariance .and. uSample) then
     _FAIL("Can not compute variance and sample in LocStream!")
  end if
! Compute weighted average over masked locations
!-----------------------------------------------
  if (usableTRANSPOSE) then
      INPUT  = 0.0
  else
      OUTPUT = 0.0
      if(uSample) then
         OUTPUT = MAPL_Undef
      end if
  endif
  do N = 1, size(INPUT)
     if(usableMASK(N) .and. INPUT(N)/=MAPL_UNDEF) then
        II = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I
        JJ = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J
        if(uSample) then
           if( LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W > FF(II,JJ)) then
              OUTPUT(II,JJ) = INPUT(N)
              FF    (II,JJ) = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W
           end if
        else
          if(usableTRANSPOSE) then
               INPUT(N) = INPUT(N) + LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W * OUTPUT(II,JJ)
          else
               OUTPUT(II,JJ) = OUTPUT(II,JJ) + LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W * INPUT(N)
!jk
               FF    (II,JJ) = FF    (II,JJ) + LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W
          endif
        endif
     end if
  end do
  if (usableTRANSPOSE) then
      OUTPUT=0.
  endif
  if(.not.uSample) then
     if (usableTRANSPOSE) then
     else
         where(FF>0)
!jk
            OUTPUT = OUTPUT / FF
         end where
     endif
  endif
  if (usableTRANSPOSE) then
  else
     where(FF<=0)
!jk
        OUTPUT = MAPL_Undef
     end where
  endif
  if (computeVariance) then
     allocate(tmpOut(size(OUTPUT,1),size(OUTPUT,2)), stat=STATUS)
     _VERIFY(STATUS)
     tmpOut=Output
     outPut=0.0
     ff=0.0
     do N = 1, size(INPUT)
        if(usableMASK(N) .and. INPUT(N)/=MAPL_UNDEF) then
           II = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I
           JJ = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J
           OUTPUT(II,JJ) = OUTPUT(II,JJ) + LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W * (INPUT(N)-tmpOut(II,JJ))**2
           FF    (II,JJ) = FF    (II,JJ) + LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W
        end if
     end do
     where (FF>0)
         output=output/ff
     end where
     where (ff<=0)
         output=mapl_undef
     end where
     deallocate(tmpOut)
  end if
  deallocate(usableMASK)
  deallocate(FF)
  _RETURN(ESMF_SUCCESS)
end subroutine MAPL_LocStreamTransformT2G
Call graph
mapl_locstreamtransformt2g calls mapl_assert, mapl_grid_interior, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_grid_interior calls mapl_grid_interior, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_locstreamtransform calls mapl_locstreamtransformt2g, mapl_locstreamtransformfield
mapl_locstreamtransformfield calls mapl_locstreamtransformt2g
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run calls regridtransform, regridtransformt2g, regridtransformt2g2g
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2