MAPL_GetCurrentFile – MAPL
MAPL_GetCurrentFile Subroutine
18 statements
Source File
public subroutine MAPL_GetCurrentFile(filetmpl, time, filename, rc, EXPID)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filetmpl
type(ESMF_Time), intent(inout) :: time
character(len=*), intent(out) :: filename
integer, intent(out), optional :: rc
character(len=*), intent(in), optional :: EXPID
Calls
Source Code
  subroutine MAPL_GetCurrentFile(FileTmpl, Time, Filename, RC, EXPID)
    character(len=*),    intent(IN   ) :: filetmpl
    type(ESMF_Time),     intent(INout) :: time
    character(len=*),    intent(  out) :: filename
    integer, optional,   intent(  out) :: rc
    character(len=*), optional, intent(  in) :: EXPID
    integer :: status
    character(len=ESMF_MAXSTR)          :: DATE
    integer                             :: nymd
    integer                             :: nhms
    call ESMF_TimeGet(Time, timeString=DATE, RC=STATUS)
    _VERIFY(STATUS)
    call strToInt(DATE, nymd, nhms)
    call fill_grads_template ( Filename, FileTmpl,&
                           experiment_id=EXPID, nymd=nymd, nhms=nhms, rc=status )
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_GetCurrentFile
Call graph
mapl_getcurrentfile calls ESMF_TimeGet, fill_grads_template, mapl_return, mapl_verify, strtoint
fill_grads_template calls ESMF_TimeGet, mapl_return, mapl_verify, mapl_assert, check_token, evaluate_token
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
evaluate_token calls ESMF_TimeGet, mapl_verify, mapl_assert, ESMF_CalendarCreate, ESMF_CalendarDestroy, ESMF_TimeSet, skip_token
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception