MAPL_SimpleBundleCreateFromState – MAPL
MAPL_SimpleBundleCreateFromState Function
38 statements
Source File
private function MAPL_SimpleBundleCreateFromState(State, rc, Levs, LevUnits, ptop, delp, only_vars, strict, name) result(self)
Given an ESMF Staete, creates a corresponding Simple Bundle. The specificatiopn of a vertical grid is optional but useful in many cases. The 1-D Levs will default to the layer number, and units of “1”. Input parameters (ptop,delp) can be used to record the corresponding Lagrangian Control Volume Grid. When delp is not specified, variables DELP or delp are used if present inside the bundle.
IMPORTANT: It is assumed that the ESMF State has a single grid.
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout), target :: State
ESMF State
integer, intent(out), optional :: rc
real(kind=ESMF_KIND_R4), intent(in), optional :: Levs(:)
Vertical coordinates Constant levels
character(len=*), intent(in), optional :: LevUnits
Level units
real(kind=ESMF_KIND_R4), intent(in), optional :: ptop
top pressure (Pa) Lagrangian Control Volume Info
real(kind=ESMF_KIND_R4), intent(in), optional, pointer :: delp(:,:,:)
layer thickness (Pa)
character(len=*), intent(in), optional :: only_vars
comma separated field names
logical, intent(in), optional :: strict
force name maching, ignored if only_vars is not present
character(len=*), intent(in), optional :: name
name
Return Value type(MAPL_SimpleBundle)
Simple Bundle
Calls
Called by
Source Code
  Function MAPL_SimpleBundleCreateFromState ( State, rc,      &
                                              Levs, LevUnits, &
                                              ptop, delp,     &
                                              only_vars,      &
                                              strict,         &
                                              name) result (self)
    type(MAPL_SimpleBundle)                        :: self          !! Simple Bundle
    type(ESMF_State), target, intent(inout)        :: State         !! ESMF State
    integer, OPTIONAL,              intent(out)    :: rc
    real(ESMF_KIND_R4), OPTIONAL,   intent(in)     :: Levs(:)       !! Vertical coordinates
                                                                    !! Constant levels
    character(len=*), OPTIONAL,     intent(in)     :: LevUnits      !! Level units
    real(ESMF_KIND_R4), OPTIONAL,   intent(in)     :: ptop          !! top pressure (Pa)
                                                                    !! Lagrangian Control Volume Info
    real(ESMF_KIND_R4), OPTIONAL, pointer, &
                                    intent(in)     :: delp(:,:,:)   !! layer thickness (Pa)
    character(len=*), OPTIONAL,     intent(in)     :: only_vars     !! comma separated field names
    logical, OPTIONAL,              intent(in)     :: strict        !! force name maching, ignored if only_vars is not present
    character(len=*), OPTIONAL,     intent(in)     :: name          !! name
    character(len=ESMF_MAXSTR) :: stateName
    character(len=ESMF_MAXSTR) :: bundleName
    character(len=ESMF_MAXSTR) :: message
    type (ESMF_FieldBundle)    :: Bundle
    integer :: status
    call ESMF_StateGet(State, name=stateName, _RC)
    if (present(name)) then
       if (len_trim(name) > ESMF_MAXSTR) then
          message = 'string "'//trim(name)//'" is too long to be used '// &
                    'as a Simple Bundle name'
          __raise__(MAPL_RC_ERROR, message)
       end if
       bundleName = trim(name)
    else
       bundleName = stateName
    end if
    Bundle = ESMF_FieldBundleCreate(name=bundleName, _RC)
    call ESMFL_BundleAddState ( Bundle, State, _RC)
    self = MAPL_SimpleBundleCreateFromBundle ( Bundle, Levs=Levs, LevUnits=LevUnits, &
                                               ptop=ptop, delp=delp, only_vars=only_vars, &
                                               strict=strict, name=name, _RC )
    _RETURN(_SUCCESS)
  end Function MAPL_SimpleBundleCreateFromState
Call graph
mapl_simplebundlecreatefromstate calls esmf_fieldbundlecreate, esmf_stateget, esmfl_bundleaddstate, mapl_return, mapl_simplebundlecreatefrombundle, mapl_verify
esmfl_bundleaddstate calls bundleaddstate_
mapl_return calls get_error_message, mapl_throw_exception
mapl_simplebundlecreatefrombundle calls mapl_return, mapl_verify, ESMF_GridGetCoord, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_assert, mapl_fieldbundleget, mapl_gridget
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleget calls mapl_fieldbundlegetbyindex
bundleaddstate_ calls esmf_stateget, mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldget, mapl_assert, bundleaddstate_, ESMF_AttributeGet, esmf_fieldbundleset, mapl_fieldbundleadd
get_error_message calls at, insert
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_throw_exception calls initialize
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_fieldbundlegetbyindex calls mapl_fieldbundlegetbyindex
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_GridGet, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_simplebundlecreate calls mapl_simplebundlecreatefromstate
mapl_simplebundleread calls mapl_simplebundlecreate