MAPL_BcastShared_2DR8 – MAPL
MAPL_BcastShared_2DR8 Subroutine
26 statements
Source File
private subroutine MAPL_BcastShared_2DR8(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
real(kind=REAL64), intent(inout), pointer :: Data(:,:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_BcastShared_2DR8(VM, Data, N, Root, RootOnly, rc)
    type(ESMF_VM) :: VM
    real(kind=REAL64),  pointer,  intent(INOUT) :: Data(:,:)
    integer,           intent(IN   ) :: N
    integer, optional, intent(IN   ) :: Root
    logical,           intent(IN   ) :: RootOnly
    integer, optional, intent(  OUT) :: rc
    integer :: status
    if(.not.MAPL_ShmInitialized) then
       if (RootOnly) then
          _RETURN(ESMF_SUCCESS)
       end if
       call MAPL_CommsBcast(vm, DATA=Data, N=N, ROOT=Root, _RC)
    else
       call MAPL_SyncSharedMemory(_RC)
       call MAPL_BroadcastToNodes(Data, N=N, ROOT=Root, _RC)
       call MAPL_SyncSharedMemory(_RC)
    endif
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_BcastShared_2DR8
Call graph
mapl_bcastshared_2dr8 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
mapl_bcastshared calls mapl_bcastshared_2dr8
add_horz_coordinates_from_abifile calls mapl_bcastshared
add_horz_coordinates_from_file calls mapl_bcastshared
get_obs_time calls mapl_bcastshared
mapl_cfioreadbundle calls mapl_bcastshared
mapl_cfiowritebundlepost calls mapl_bcastshared
mapl_locstreamcreatefromfile calls mapl_bcastshared
read_geos_binary calls mapl_bcastshared
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize_subclass calls read_geos_binary
make_new_grid calls add_horz_coordinates_from_abifile, add_horz_coordinates_from_file
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost