MAPL_VarSpecGetData – MAPL
MAPL_VarSpecGetData Subroutine
38 statements
Source File
private subroutine MAPL_VarSpecGetData(SPEC, PTR1, PTR2, PTR3, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC
real, optional, pointer :: PTR1(:)
real, optional, pointer :: PTR2(:,:)
real, optional, pointer :: PTR3(:,:,:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecGetData
Source Code
   subroutine MAPL_VarSpecGetData(SPEC, PTR1, PTR2, PTR3, RC)
      type (MAPL_VarSpec )            , intent(INout):: SPEC
      real,    optional, pointer                     :: PTR1(:)
      real,    optional, pointer                     :: PTR2(:,:)
      real,    optional, pointer                     :: PTR3(:,:,:)
      integer, optional               , intent(OUT)  :: RC
      integer :: STATUS
      type(ESMF_Array) :: ARRAY
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      call ESMF_FieldGet(SPEC%SPECPtr%FIELD,Array=ARRAY,rc=STATUS)
      _VERIFY(STATUS)
      if (present(PTR1)) then
         call ESMF_ArrayGet(ARRAY, localDE=0, farrayptr=PTR1, RC=STATUS)
         _VERIFY(STATUS)
         _ASSERT(.not.present(PTR2),'needs informative message')
         _ASSERT(.not.present(PTR3),'needs informative message')
         _RETURN(ESMF_SUCCESS)
      endif
      if (present(PTR2)) then
         call ESMF_ArrayGet(ARRAY, localDE=0, farrayptr=PTR2, RC=STATUS)
         _VERIFY(STATUS)
         _ASSERT(.not.present(PTR3),'needs informative message')
         _RETURN(ESMF_SUCCESS)
      endif
      if (present(PTR3)) then
         call ESMF_ArrayGet(ARRAY, localDE=0, farrayptr=PTR3, RC=STATUS)
         _VERIFY(STATUS)
         _RETURN(ESMF_SUCCESS)
      endif
      _RETURN(ESMF_FAILURE)
   end subroutine MAPL_VarSpecGetData
Call graph
mapl_varspecgetdata calls esmf_arrayget, esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecgetdatabyname calls mapl_varspecgetdata