MAPL_InternalStateGet – MAPL
MAPL_InternalStateGet Subroutine
23 statements
Source File
private subroutine MAPL_InternalStateGet(GC, MAPLOBJ, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_MetaComp), pointer :: MAPLOBJ
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_InternalStateGet
Source Code
   subroutine MAPL_InternalStateGet ( GC, MAPLOBJ, RC)
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INout) :: GC ! Gridded component
      type (MAPL_MetaComp),                 pointer :: MAPLOBJ
      integer,              optional, intent(  OUT) :: RC ! Return code
      ! !DESCRIPTION:
      ! This is the recommended way of getting the opaque MAPL Generic
      ! state object from the gridded component (GC). It can be called at any time
      ! {\em after} {\tt MAPL\_GenericSetServices} has been called on GC.
      ! Note that you get a pointer to the object.
      !EOPI
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)        :: IAm
      character(len=ESMF_MAXSTR)        :: comp_name
      integer                           :: status
      ! Local variables
      ! ---------------
      type (MAPL_GenericWrap )          :: WRAP
#if defined(ABSOFT) || defined(sysIRIX64)
      type(MAPL_MetaComp      ), target :: DUMMY
#endif
      !=============================================================================
      ! Begin...
      ! Get the target components name and set-up traceback handle.
      ! -----------------------------------------------------------
      Iam = "MAPL_InternalStateGet"
      call ESMF_GridCompGet( GC, name=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
#if defined(ABSOFT) || defined(sysIRIX64)
      WRAP%MAPLOBJ => DUMMY
#endif
      call ESMF_UserCompGetInternalState(GC, "MAPL_GenericInternalState", WRAP, status)
      IF (status /= ESMF_SUCCESS) then
         if (present(RC)) then
            RC = ESMF_FAILURE
         end if
         return
      END IF
      MAPLOBJ => WRAP%MAPLOBJ
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_InternalStateGet
Call graph
mapl_internalstateget calls esmf_gridcompget, mapl_return, esmf_usercompgetinternalstate, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_gcget calls mapl_internalstateget
mapl_exchangegridset calls mapl_internalstateget
mapl_getobjectfromgc calls mapl_internalstateget
mapl_genericspecenum calls mapl_internalstateget
mapl_internalstateretrieve calls mapl_internalstateget
mapl_genericinitialize calls mapl_internalstateget
mapl_genericstatesetfromgc calls mapl_internalstateget
mapl_adjustisneeded calls mapl_internalstateget
mapl_importstateget calls mapl_internalstateget
mapl_internalesmfstateget calls mapl_internalstateget
mapl_gridcreate calls mapl_internalstateget
mapl_genericrunchildren calls mapl_internalstateget
mapl_exchangegridget calls mapl_internalstateget
mapl_getchildlocstream calls mapl_internalstateget
mapl_genericwrapper calls mapl_internalstateget
mapl_gridcompgetfriendlies0 calls mapl_internalstateget