MAPL_CommsGatherV_R4_1 – MAPL
MAPL_CommsGatherV_R4_1 Subroutine
22 statements
Source File
private subroutine MAPL_CommsGatherV_R4_1(layout, sendbuf, sendcnt, recvbuf, recvcnts, displs, root, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
real(kind=ESMF_KIND_R4), intent(out) :: recvbuf(:)
integer, intent(in) :: recvcnts(:)
integer, intent(in) :: displs(:)
integer, intent(in) :: root
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commsgatherv_r4_1 calls esmf_delayoutget, mapl_verify, esmf_vmget, mpi_gatherv, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_commsgatherv calls mapl_commsgatherv_r4_1
arraygather_i4_1 calls mapl_commsgatherv
arraygather_r4_1 calls mapl_commsgatherv
arraygather_r8_2 calls mapl_commsgatherv
arraygather_r4_2 calls mapl_commsgatherv
arraygather_r8_1 calls mapl_commsgatherv
mapl_tilemaskget calls mapl_commsgatherv
arraygather calls arraygather_i4_1, arraygather_r4_1, arraygather_r8_2, arraygather_r4_2, arraygather_r8_1
mapl_statevarread calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget