MAPL_Alloc_R_2D – MAPL
MAPL_Alloc_R_2D Subroutine
54 statements
Source File
private subroutine MAPL_Alloc_R_2D(A, IM, JM, RC)
Arguments
Type Intent Optional Attributes Name
real, pointer :: A(:,:)
integer, intent(in) :: IM
integer, intent(in) :: JM
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_Alloc_R_2D
Source Code
    subroutine MAPL_Alloc_R_2D(A,IM, JM, RC)
      integer,           intent(IN ) :: IM, JM
      integer, optional, intent(OUT) :: RC
      real,  pointer                 :: A(:,:)
      integer :: gap, len, i, j
      integer :: status
      interface loadr2d
         function loadr2d(P1,I1,I2) result(P2)
           real          :: P1
           real, pointer :: P2(:,:)
           integer, intent(IN) :: I1, I2
         end function loadr2d
      end interface
      if(.not.associated(heap%buffer)) then
         call MAPL_HeapSet(HeapSize=DefaultSize,RC=status)
         _VERIFY(STATUS)
      end if
      len = im*jm
! Look for space between or after used segments
!----------------------------------------------
      do i=1,NumSegments-1
         if(heap%HP_start(i)<0) exit  ! found the last segment
         if(i==1              ) cycle ! first segment is taken
         ! Beginning at the second segment, check if there is room
         ! between the previous and current segments
         gap = heap%HP_start(i)-heap%HP_end(i-1)-1
         if(gap >= len) exit
      end do
      if(I>=NumSegments) then
         print *, 'MAPL_Alloc: Out of Segments. Need: ', I
         _FAIL('needs informative message')
      end if
! If we are filling a gap, move trailing segments down
!-----------------------------------------------------
      if(heap%HP_start(i)>0) then
         j = NumSegments-2
         do while (j >= i)
            heap%HP_start(j+1) = heap%HP_start(j)
            heap%HP_end  (j+1) = heap%HP_end  (j)
            j = j-1
         end do
      end if
! Record the start and end of the segment
!----------------------------------------
      if(i == 1) then
         heap%HP_start(i) = 1
      else
         heap%HP_start(i) = heap%HP_end(i-1) + 1
      end if
      heap%HP_end(i) =  heap%HP_start(i) + (len-1)
! Pass that space back in the pointer
!------------------------------------
      if(heap%HP_end(i) > size(heap%buffer)) then
         print *, 'MAPL_Alloc: Out of Space. Need: ', len, &
                  ' Have: ',  size(heap%buffer)-heap%HP_start(i)+1
         do i=1,NumSegments
            print *,  i, heap%HP_start(i),  heap%HP_end(i)
         end do
         _FAIL('needs informative message')
      end if
      heap%ptrs(i)%a => heap%buffer(heap%HP_start(i):heap%HP_end(i))
      a => loadr2d(heap%buffer(heap%HP_start(i)),im,jm)
      _RETURN(_SUCCESS)
    end subroutine MAPL_Alloc_R_2D
Call graph
mapl_alloc_r_2d calls mapl_heapset, mapl_return, mapl_verify, mapl_assert
mapl_heapset calls mapl_return, mapl_verify, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_alloc calls mapl_alloc_r_2d