MAPL_TerminateImportAllBut – MAPL
MAPL_TerminateImportAllBut Subroutine
44 statements
Source File
private subroutine MAPL_TerminateImportAllBut(GC, SHORT_NAMES, CHILD_IDS, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAMES(:)
integer, intent(in) :: CHILD_IDS(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_TerminateImportAllBut
Source Code
   subroutine MAPL_TerminateImportAllBut ( GC, SHORT_NAMES, CHILD_IDS, RC )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character(len=*),               intent(IN   ) :: SHORT_NAMES(:)
      integer,                        intent(IN   ) :: CHILD_IDS(:)
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_TerminateImportAllBut"
      integer                               :: status
      type(MAPL_MetaComp), pointer          :: META
      type(MAPL_MetaComp), pointer          :: META_CHILD
      character(len=ESMF_MAXSTR)            :: SHORT_NAME
      integer                               :: I,J
      logical                               :: SKIP
      character(len=ESMF_MAXSTR), allocatable :: SNAMES(:)
      type (MAPL_Connectivity), pointer     :: conn
      type (VarConn), pointer          :: CONNECT
      logical :: isConnected
      type(ESMF_GridComp), pointer :: gridcomp
      _ASSERT(size(SHORT_NAMES)==size(CHILD_IDS),'needs informative message')
      call MAPL_GetObjectFromGC(GC, META, RC=status)
      _VERIFY(status)
      allocate(SNAMES(size(SHORT_NAMES)))
      do I=1, size(SHORT_NAMES(:))
         SNAMES(I) = trim(SHORT_NAMES(I))
      enddo
      call MAPL_ConnectivityGet(gc, connectivityPtr=conn, RC=status)
      CONNECT => CONN%CONNECT
      do I=1, META%get_num_children()
         gridcomp => META%GET_CHILD_GRIDCOMP(I)
         call MAPL_GetObjectFromGC(gridcomp, META_CHILD, RC=status)
         _VERIFY(status)
         do J=1 ,size(META_CHILD%component_spec%import%old_var_specs)
            call MAPL_VarSpecGet(META_CHILD%component_spec%import%old_var_specs(J),SHORT_NAME=SHORT_NAME,RC=status)
            isConnected = connect%varIsConnected(short_name,I,rc=status)
            SKIP = ANY(SNAMES==TRIM(SHORT_NAME)) .and. (ANY(CHILD_IDS==I))
            if ((.not.isConnected) .and. (.not.skip)) then
               call MAPL_DoNotConnect(GC, SHORT_NAME, I, RC=status)
               _VERIFY(status)
            end if
         enddo
      end do
      deallocate(SNAMES)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_TerminateImportAllBut
Call graph
mapl_terminateimportallbut calls get_num_children, mapl_assert, mapl_getobjectfromgc, mapl_varspecget, get_child_gridcomp, mapl_connectivityget, mapl_donotconnect, mapl_return, mapl_verify, varisconnected
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_getobjectfromgc calls mapl_internalstateget
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
get_child_gridcomp calls get_gridcomp, get_ith_child
mapl_connectivityget calls mapl_getobjectfromgc, mapl_return, mapl_verify
mapl_donotconnect calls mapl_connectivityget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
get_ith_child calls gcnamelist, get_child
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_terminateimport calls mapl_terminateimportallbut, mapl_terminateimportall
mapl_terminateimportall calls mapl_terminateimport