MAPL_ArrayIGather_R4_2 – MAPL
MAPL_ArrayIGather_R4_2 Subroutine
22 statements
Source File
private subroutine MAPL_ArrayIGather_R4_2(local_array, request, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: local_array(:,:)
type(MAPL_CommRequest), intent(inout) :: request
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ArrayIGather_R4_2
Source Code
  subroutine MAPL_ArrayIGather_R4_2(local_array, request, rc)
    real,                    intent(IN   ) :: local_array (:,:)
    type (MAPL_CommRequest), intent(INOUT) :: request
    integer, optional,       intent(  OUT) :: rc
! Local variables
    integer                    :: status
    integer  :: i1, in, j1, jn
    allocate(request%local_array(size(LOCAL_ARRAY,1),size(LOCAL_ARRAY,2)), stat=STATUS)
    _VERIFY(STATUS)
! In senders, copy input to contiguous buffer for safety
!-------------------------------------------------------
    request%local_array = local_array
    if(request%amRoot) then
       i1 = request%i1(request%mype)
       in = request%in(request%mype)
       j1 = request%j1(request%mype)
       jn = request%jn(request%mype)
       request%DstArray(i1:in,j1:jn) = local_array
    else
       call MPI_ISend(request%Local_Array, size(Local_Array), MPI_REAL, &
            request%root, request%tag, request%comm, request%send(0), status)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ArrayIGather_R4_2
Call graph
mapl_arrayigather_r4_2 calls mpi_isend, mapl_return, mapl_verify, send
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_arrayigather calls mapl_arrayigather_r4_2
mapl_cfiowritebundlepost calls mapl_arrayigather
mapl_collectivegather3d calls mapl_arrayigather
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
regrid_scalar_3d_real32 calls mapl_collectivegather3d
esmf_iowrite calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle
mapl_cfiowritestate calls mapl_cfiowritebundle