MAPL_GRID_INTERIOR – MAPL
MAPL_GRID_INTERIOR Module Subroutine
63 statements
Source File
module subroutine MAPL_GRID_INTERIOR(grid, I1, IN, J1, JN) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(out) :: I1
integer, intent(out) :: IN
integer, intent(out) :: J1
integer, intent(out) :: JN
Calls
Called by
Source Code
  module subroutine MAPL_GRID_INTERIOR(GRID,I1,IN,J1,JN)
    type (ESMF_Grid), intent(IN) :: grid
    integer, intent(OUT)         :: I1, IN, J1, JN
    ! local vars
    integer                               :: status
    !    character(len=ESMF_MAXSTR)            :: IAm='MAPL_Grid_Interior'
    type (ESMF_DistGrid)                  :: distGrid
    type(ESMF_DELayout)                   :: LAYOUT
    integer,               allocatable    :: AL(:,:)
    integer,               allocatable    :: AU(:,:)
    integer                               :: nDEs,localDECount
    integer                               :: deId
    integer                               :: gridRank
    integer,               allocatable    :: localDeToDeMap(:)
    integer :: rc
    logical :: isPresent
    integer, allocatable  :: global_grid_info(:)
    integer :: itemCount
    i1=-1
    j1=-1
    in=-1
    jn=-1
    call ESMF_AttributeGet(grid, name="GLOBAL_GRID_INFO", isPresent=isPresent, _RC)
    if (isPresent) then
      call ESMF_AttributeGet(grid, name="GLOBAL_GRID_INFO", itemCount=itemCount, _RC)
      allocate(global_grid_info(itemCount), _STAT)
      call ESMF_AttributeGet(grid, name="GLOBAL_GRID_INFO", valueList=global_grid_info, _RC)
      I1 = global_grid_info(7)
      IN = global_grid_info(8)
      j1 = global_grid_info(9)
      JN = global_grid_info(10)
      deallocate(global_grid_info, _STAT)
      _RETURN(_SUCCESS)
    end if
    call ESMF_GridGet    (GRID, dimCount=gridRank, distGrid=distGrid, _RC)
    call ESMF_DistGridGet(distGRID, delayout=layout, _RC)
    call ESMF_DELayoutGet(layout, deCount = nDEs, localDeCount=localDeCount,_RC)
    if (localDeCount > 0) then
       allocate(localDeToDeMap(localDeCount),_STAT)
       call ESMF_DELayoutGet(layout, localDEtoDeMap=localDeToDeMap,_RC)
       deId=localDeToDeMap(1)
       allocate (AL(gridRank,0:nDEs-1),  _STAT)
       allocate (AU(gridRank,0:nDEs-1),  _STAT)
       call MAPl_DistGridGet(distgrid, &
            minIndex=AL, maxIndex=AU, _RC)
       I1 = AL(1, deId)
       IN = AU(1, deId)
       !    _ASSERT(gridRank > 1, 'tilegrid is 1d (without RC this only for info')
       J1 = AL(2, deId)
       JN = AU(2, deId)
       deallocate(AU, AL, localDeToDeMap)
    end if
  end subroutine MAPL_GRID_INTERIOR
Call graph
mapl_grid_interior calls ESMF_AttributeGet, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_return, mapl_verify, mapl_grid_interior
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_horz_coordinates calls mapl_grid_interior
add_horz_coordinates_from_abifile calls mapl_grid_interior
add_horz_coordinates_from_file calls mapl_grid_interior
copy_global_to_local calls mapl_grid_interior
fillstate calls mapl_grid_interior
get_fake_latitudes calls mapl_grid_interior
get_fake_longitudes calls mapl_grid_interior
get_obs_time calls mapl_grid_interior
latlon_zmean calls mapl_grid_interior
make_subgrids_from_bounds calls mapl_grid_interior
mapl_cfioreadbundle calls mapl_grid_interior
mapl_gethorzijindex calls mapl_grid_interior
mapl_gridcoordadjustfromfile calls mapl_grid_interior
mapl_latlongridcreate calls mapl_grid_interior
mapl_locstreamattachgrid calls mapl_grid_interior
mapl_locstreamcreatefromfile calls mapl_grid_interior
mapl_locstreamtransformg2t calls mapl_grid_interior
mapl_locstreamtransformt2g calls mapl_grid_interior
mapl_varwritencpar_r4_2d calls mapl_grid_interior
mapl_varwritencpar_r4_3d calls mapl_grid_interior
mapl_varwritencpar_r4_4d calls mapl_grid_interior
mapl_varwritencpar_r8_2d calls mapl_grid_interior
mapl_varwritencpar_r8_3d calls mapl_grid_interior
mapl_varwritencpar_r8_4d calls mapl_grid_interior