MAPL_DoNotDeferExport – MAPL
MAPL_DoNotDeferExport Subroutine
24 statements
Source File
public subroutine MAPL_DoNotDeferExport(GC, NAMES, RC)
For each entry in NAMES marks the export spec to not be deferred during MAPL_GenericInitialize.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: NAMES(:)
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_DoNotDeferExport
Source Code
   subroutine MAPL_DoNotDeferExport(GC, NAMES, RC)
      ! !ARGUMENTS:
      type (ESMF_GridComp)            , intent(INOUT)   :: GC
      character (len=*)               , intent(IN)      :: NAMES(:)
      integer            , optional   , intent(OUT)     :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_DoNotDeferExport"
      integer                               :: status
      integer                               :: I, J, N, K
      type (MAPL_MetaComp), pointer         :: STATE
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      if (associated(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS)) then
         N = size(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS)
         K = size(NAMES)
         DO I=1,K
            J = MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS,NAMES(I))
            _ASSERT(J > 0, 'J is equal or less than 0')
            _ASSERT(J <= N, 'J is greater than N')
            call MAPL_VarSpecSet(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS(J),                         &
                 alwaysAllocate = .true.,                                     &
                 RC=status  )
            _VERIFY(status)
         END DO
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_DoNotDeferExport
Call graph
mapl_donotdeferexport calls mapl_assert, mapl_varspecgetindex, mapl_varspecset, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecset calls mapl_varspecsetnew
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecsetnew calls mapl_return
initialize calls initialize_global_time_profiler