MAPL_SunOrbitCreated – MAPL
MAPL_SunOrbitCreated Function
9 statements
Source File
public function MAPL_SunOrbitCreated(ORBIT, RC)
The function MAPL_SunOrbitCreated returns .true. if the given orbit object has been initilized.
Arguments
Type Intent Optional Attributes Name
type(MAPL_SunOrbit), intent(in) :: ORBIT
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Source Code
       logical function  MAPL_SunOrbitCreated(ORBIT, RC)
! !ARGUMENTS:
       type(MAPL_SunOrbit),    intent(IN ) :: ORBIT
       integer, optional,      intent(OUT) :: RC
       character(len=ESMF_MAXSTR), parameter :: IAm = "SunOrbitCreated"
       MAPL_SunOrbitCreated = ORBIT%CREATED
       _RETURN(ESMF_SUCCESS)
       return
     end function MAPL_SunOrbitCreated
Call graph
mapl_sunorbitcreated calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_genericstateget calls mapl_sunorbitcreated
mapl_sungetdaylightduration calls mapl_sunorbitcreated
mapl_sungetdaylightdurationmax calls mapl_sunorbitcreated
mapl_sungetlocalsolarhourangle calls mapl_sunorbitcreated
mapl_sunorbitquery calls mapl_sunorbitcreated
solar_1d calls mapl_sunorbitcreated, mapl_sungetinsolation
solar_2d calls mapl_sunorbitcreated, mapl_sungetinsolation
mapl_get calls mapl_genericstateget
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
mapl_readforcingx calls mapl_genericstateget
initialize_gc calls mapl_get
initialize_ calls mapl_get
mapl_donotallocateimport calls mapl_get
mapl_donotallocateinternal calls mapl_get
mapl_internalesmfstateget calls mapl_get, mapl_internalesmfstateget
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run_ calls mapl_get
solar_arr_int calls mapl_sungetinsolation
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
get_field_from_internal calls mapl_internalesmfstateget