MAPL_CplCompSetAlarm – MAPL
MAPL_CplCompSetAlarm Subroutine
23 statements
Source File
public subroutine MAPL_CplCompSetAlarm(CC, ALARM, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CplComp), intent(inout) :: CC
type(ESMF_Alarm), intent(in), target :: ALARM
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CplCompSetAlarm
Source Code
  subroutine MAPL_CplCompSetAlarm ( CC, ALARM, RC )
    type (ESMF_CplComp  ),           intent(INOUT) :: CC
    type (ESMF_Alarm), target,       intent(IN   ) :: ALARM
    integer, optional,               intent(  OUT) :: RC
! ErrLog Variables
    character(len=ESMF_MAXSTR)    :: IAm
    character(len=ESMF_MAXSTR)    :: COMP_NAME
    integer                       :: STATUS
! Locals
    type (MAPL_GenericCplState), pointer :: STATE
    type (MAPL_GenericCplWrap )          :: WRAP
! Begin...
! Get this instance's name and set-up traceback handle.
! -----------------------------------------------------
    call ESMF_CplCompGet( CC, name=COMP_NAME, RC=STATUS )
    _VERIFY(STATUS)
    Iam = trim(COMP_NAME) // "MAPL_CplCompSetAlarm"
! Retrieve the pointer to the internal state. It comes in a wrapper.
! ------------------------------------------------------------------
    call ESMF_CplCompGetInternalState ( CC, WRAP, STATUS )
    _VERIFY(STATUS)
    STATE  =>  WRAP%INTERNAL_STATE
    if (.not.associated(STATE%TIME2CPL_ALARM)) then
       STATE%TIME2CPL_ALARM => ALARM
    else
       _FAIL( "Alarm is already associated! Cannot set it again!")
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CplCompSetAlarm
Call graph
mapl_cplcompsetalarm calls ESMF_CplCompGet, ESMF_CplCompGetInternalState, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize calls mapl_cplcompsetalarm