MAPL_VarSpecPrint1CSV – MAPL
MAPL_VarSpecPrint1CSV Subroutine
23 statements
Source File
private subroutine MAPL_VarSpecPrint1CSV(spec, compName, RC)
Uses
pflogger
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: spec
character(len=*), intent(in) :: compName
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecPrint1CSV
Source Code
   subroutine MAPL_VarSpecPrint1CSV(spec, compName, rc )
      use pFlogger
      type (MAPL_VarSpec ),             intent(in )     :: spec
      character(len=*),                 intent(in )     :: compName
      integer            , optional   , intent(out)     :: RC
      class(Logger), pointer :: lgr
      character(len=:), allocatable :: item_type
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      if (iand(spec%specptr%stat,MAPL_BundleItem) /= 0) then
         item_type = "esmf_bundle"
      else if (iand(spec%specptr%stat,MAPL_StateItem) /=0) then
         item_type = "esmf_state"
      else
         item_type = "esmf_field"
      end if
      lgr => logging%get_logger('MAPL.GENERIC')
      call lgr%info('%a~, %a~, %a~, %a~, %i3~, %a~ ', &
           trim(compName), trim(spec%specptr%short_name), trim(spec%specptr%long_name), &
           trim(spec%specptr%units),spec%specptr%dims,item_type)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecPrint1CSV
Call graph
mapl_varspecprint1csv calls get_logger, info, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecprintcsv calls mapl_varspecprint1csv
mapl_stateprintspeccsv calls mapl_varspecprintcsv, mapl_stateprintspeccsv
initialize_gc calls mapl_stateprintspeccsv