MAPL_InitializeShmem – MAPL
MAPL_InitializeShmem Module Procedure
11 statements
Source File
module procedure MAPL_InitializeShmem module subroutine MAPL_InitializeShmem(rc) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_initializeshmem calls mapl_assert, mapl_return, segs, mapl_initializeshmem
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_gc calls mapl_initializeshmem