MAPL_DataAddCollection – MAPL
MAPL_DataAddCollection Function
27 statements
Source File
public function MAPL_DataAddCollection(template, use_file_coords) result(id)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: template
logical, intent(in), optional :: use_file_coords
Return Value integer
Calls
Called by
Source Code
  function MAPL_DataAddCollection(template,use_file_coords) result(id)
     character(len=*), intent(in) :: template
     logical, optional, intent(in) :: use_file_coords
      integer :: n
      logical :: found
      type (MAPLCollectionVectorIterator) :: iter
      type (MAPLDataCollection), pointer :: collection
      type (MAPLDataCollection) :: c
      integer :: id
      iter = Datacollections%begin()
      n = 1
      ! Is it a new collection?
      found = .false.
      do while (iter /= Datacollections%end())
         collection => iter%get()
         if (template == collection%template) then
            found = .true.
            exit
         end if
         n = n + 1
         call iter%next()
      end do
      if (.not. found) then
         c = MAPLDataCollection(template,use_file_coords=use_file_coords)
         call Datacollections%push_back(c)
      end if
      id = n
   end function MAPL_DataAddCollection
Call graph
mapl_dataaddcollection calls v_begin, v_iter_get, v_iter_next, v_push_back
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
initialize_ calls mapl_dataaddcollection
mapl_read_bundle calls mapl_dataaddcollection
new_extdatafilestream calls mapl_dataaddcollection
run_ calls mapl_dataaddcollection
extdatafilestream calls new_extdatafilestream
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main