MAPL_PackDateTime – MAPL
MAPL_PackDateTime Module Subroutine
6 statements
Source File
module subroutine MAPL_PackDateTime(date_time, yy, mm, dd, h, m, s) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: date_time(:)
integer, intent(in) :: yy
integer, intent(in) :: mm
integer, intent(in) :: dd
integer, intent(in) :: h
integer, intent(in) :: m
integer, intent(in) :: s
Called by
Source Code
  module subroutine MAPL_PackDateTime(date_time, yy, mm, dd, h, m, s)
    integer, intent(in) :: yy, mm, dd, h, m, s
    integer, intent(out) :: date_time(:)
    date_time(1) = (10000 * yy) + (100 * mm) + dd
    date_time(2) = (10000 * h) + (100 * m) + s
  end subroutine MAPL_PackDateTime
Call graph
mapl_packdatetime calls mapl_packdatetime
cap_finalize calls mapl_packdatetime
mapl_readforcingx calls mapl_packdatetime
finalize_gc calls cap_finalize
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2