MAPL_GetResource_config_array – MAPL
MAPL_GetResource_config_array Subroutine
306 statements
Source File
public subroutine MAPL_GetResource_config_array(config, val, label, value_is_set, unusable, default, component_name, iunit, rc)
Find value of array variable in config
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
class(*), intent(inout) :: val(:)
character(len=*), intent(in) :: label
logical, intent(out) :: value_is_set
class(KeywordEnforcer), intent(in), optional :: unusable
class(*), intent(in), optional :: default(:)
character(len=*), intent(in), optional :: component_name
character(len=*), intent(inout), optional :: iunit
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_GetResource_config_array
Source Code
   subroutine MAPL_GetResource_config_array(config, val, label, value_is_set, unusable, default, component_name, iunit, rc)
      type(ESMF_Config), intent(inout) :: config
      class(*), intent(inout) :: val(:)
      character(len=*), intent(in) :: label
      logical, intent(out) :: value_is_set
      class(KeywordEnforcer), optional, intent(in) :: unusable
      class(*), optional, intent(in) :: default(:)
      character(len=*), optional, intent(in) :: component_name
      character(len=*), optional, intent(inout) :: iunit
      integer, optional, intent(out) :: rc
      ! We assume we will never have more than 99 values, hence len=2
      character(len=:), allocatable :: actual_label
      character(len=:), allocatable :: type_format
      character(len=:), allocatable :: type_string
      character(len=MAX_LINE_LENGTH) :: formatted_value
      logical :: default_is_present
      logical :: label_is_present
      logical :: print_nondefault_only
      logical :: do_print
      logical :: value_is_default
      integer :: count
      integer :: io_stat
      integer :: status
      _UNUSED_DUMMY(unusable)
#if defined(TYPE_)
#undef TYPE_
#endif
#if defined(TYPENUM)
#undef TYPENUM
#endif
#if defined(IS_ARRAY)
#undef IS_ARRAY
#endif
#define IS_ARRAY
#if defined(VALUE_)
#undef VALUE_
#endif
#define VALUE_ val
#if defined(MAX_CHAR_LEN)
#undef MAX_CHAR_LEN
#endif
      default_is_present = present(default)
      ! these need to be initialized explicitly
      value_is_set = .FALSE.
      label_is_present = .FALSE.
      print_nondefault_only = .FALSE.
      do_print = .FALSE.
      value_is_default = .FALSE.
      if (default_is_present) then
         _ASSERT(same_type_as(val, default), "Value and default must have same type")
      end if
      call get_actual_label(config, label, label_is_present, actual_label, component_name = component_name, _RC)
      ! label or default must be present
      if (.not. label_is_present .and. .not. default_is_present) then
         value_is_set = .FALSE.
         return
      end if
      ! only print if root
      call get_print_settings(config, default_is_present, do_print, print_nondefault_only, _RC)
      count = size(val)
      select type(val)
      type is (TYPE_INTEGER4)
#define TYPE_ TYPE_INTEGER4
#define TYPENUM TYPENUM_INTEGER4
#include "MAPL_Resource_SetValue.h"
#include "MAPL_Resource_MakeString.h"
#undef TYPE_
#undef TYPENUM
      type is (TYPE_INTEGER8)
#define TYPE_ TYPE_INTEGER8
#define TYPENUM TYPENUM_INTEGER8
#include "MAPL_Resource_SetValue.h"
#include "MAPL_Resource_MakeString.h"
#undef TYPE_
#undef TYPENUM
      type is (TYPE_REAL4)
#define TYPE_ TYPE_REAL4
#define TYPENUM TYPENUM_REAL4
#include "MAPL_Resource_SetValue.h"
#include "MAPL_Resource_MakeString.h"
#undef TYPE_
#undef TYPENUM
      type is (TYPE_REAL8)
#define TYPE_ TYPE_REAL8
#define TYPENUM TYPENUM_REAL8
#include "MAPL_Resource_SetValue.h"
#include "MAPL_Resource_MakeString.h"
#undef TYPE_
#undef TYPENUM
      type is (TYPE_LOGICAL)
#define TYPE_ TYPE_LOGICAL
#define TYPENUM TYPENUM_LOGICAL
#include "MAPL_Resource_SetValue.h"
#include "MAPL_Resource_MakeString.h"
#undef TYPE_
#undef TYPENUM
      type is (TYPE_CHARACTER)
#define TYPE_ TYPE_CHARACTER
#define TYPENUM TYPENUM_CHARACTER
#include "MAPL_Resource_SetValue.h"
#include "MAPL_Resource_MakeString.h"
#undef TYPE_
#undef TYPENUM
      class default
         _FAIL( "Unsupported type")
      end select
      if(do_print) then
         call print_resource(type_string, actual_label, formatted_value, value_is_default, iunit=iunit, _RC)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GetResource_config_array
Call graph
mapl_getresource_config_array calls ESMF_ConfigGetAttribute, array_format, mapl_assert, compare_all, get_actual_label, get_print_settings, make_string_character_array, mapl_return, mapl_verify, print_resource, set_do_print
array_format calls array_format_simple, array_format_string
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_actual_label calls mapl_return, mapl_verify, ESMF_ConfigFindLabel, get_labels_with_prefix
get_print_settings calls ESMF_ConfigGetAttribute, mapl_verify, mapl_am_i_root
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
print_resource calls mapl_return
set_do_print calls vector_contains_str, push_back
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_contains_str calls begin, next, of
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefrommapl_array
arrdescrsetncpar calls mapl_getresource
capture calls mapl_getresource
get_test_framework_resource calls mapl_getresource
initialize_gc calls mapl_getresource
mapl_clockinit calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource
mapl_esmfstatewritetofile calls mapl_getresource
mapl_genericfinalize calls mapl_getresource
mapl_genericinitialize calls mapl_getresource
mapl_genericrecord calls mapl_getresource
mapl_genericrefresh calls mapl_getresource
mapl_genericstaterestore calls mapl_getresource
mapl_genericstatesave calls mapl_getresource
mapl_genericwrapper calls mapl_getresource
mapl_staterecord calls mapl_getresource
mapl_staterefresh calls mapl_getresource