MAPL_SimpleBundleWrite2 – MAPL
MAPL_SimpleBundleWrite2 Subroutine
23 statements
Source File
private subroutine MAPL_SimpleBundleWrite2(self, filename, time, verbose, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_SimpleBundle) :: self
character(len=*), intent(in) :: filename
type(ESMF_Time), intent(in) :: time
logical, intent(in), optional :: verbose
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_SimpleBundleWrite2
Source Code
  subroutine MAPL_SimpleBundleWrite2 ( self, filename, time, verbose, rc )
!
    type(MAPL_SimpleBundle)                 :: self
    character(len=*),           intent(in) :: filename
    type(ESMF_Time),            intent(in)  :: time
    logical, OPTIONAL,          intent(in)  :: verbose
    integer, OPTIONAL,          intent(out) :: rc
!  !DESCRIPTION:
!
!   Writes a MAPL SimpleBundle to file fiven an ESMF Time object. The file opened,
!   written to, and closed. A fake timestep of 30 minutes is assumed.
!
!EOP
!                                ---
    type(ESMF_TimeInterval)    :: TimeStep
    type(ESMF_Clock)           :: Clock
    type(MAPL_CFIO)            :: cfio
    integer                    :: status
    call ESMF_TimeIntervalSet( TimeStep, h=0, m=30, s=0, _RC )
    CLOCK = ESMF_ClockCreate ( name="Clock", timeStep=TimeStep, startTime=Time, _RC )
    call MAPL_CFIOCreate ( cfio, filename, clock, self%Bundle, _RC)
    call MAPL_CFIOWrite  ( cfio, Clock, self%Bundle, verbose=verbose, _RC)
    call MAPL_CFIODestroy ( cfio, _RC )
    _RETURN(_SUCCESS)
  end subroutine MAPL_SimpleBundleWrite2
Call graph
mapl_simplebundlewrite2 calls esmf_timeintervalset, mapl_verify, mapl_cfiocreate, esmf_clockcreate, mapl_cfiowrite, mapl_cfiodestroy, mapl_return
mapl_verify calls mapl_throw_exception
mapl_cfiocreate calls mapl_cfiocreatefromstate, mapl_cfiocreatefrombundle
mapl_cfiowrite calls mapl_cfiowritestate, mapl_cfiowritebundle
mapl_cfiodestroy calls mapl_verify, mapl_return, esmf_cfiofileclose, esmf_cfiodestroy
mapl_return calls mapl_throw_exception, get_error_message
mapl_simplebundlewrite calls mapl_simplebundlewrite2