MAPL_DistGridGet – MAPL
MAPL_DistGridGet Subroutine
72 statements
Source File
public subroutine MAPL_DistGridGet(distGrid, MinIndex, MaxIndex, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DistGrid), intent(inout) :: distGrid
integer, intent(inout) :: MinIndex(:,:)
integer, intent(inout) :: MaxIndex(:,:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_DistGridGet
Source Code
  subroutine MAPL_DistGridGet(distGrid,minIndex,maxIndex,rc)
     type(ESMF_DistGrid), intent(inout) :: distGrid
     integer,             intent(inout) :: MinIndex(:,:)
     integer,             intent(inout) :: MaxIndex(:,:)
     integer, optional,   intent(out  ) :: rc
     integer :: status
     character(len=ESMF_MAXSTR) :: Iam
     integer :: i,tileSize,tileCount,tile,deCount
     logical :: ESMFCubeSphere
     integer, allocatable  :: elementCountPTile(:)
     integer, allocatable :: deToTileMap(:)
     integer, allocatable :: oldMinIndex(:,:),oldMaxIndex(:,:)
     Iam = "MAPL_DistGridGet"
     ESMFCubeSphere = .false.
     call ESMF_DistGridGet(distGrid,tileCount=tileCount,_RC)
     if (tileCount==6) ESMFCubeSphere = .true.
     if (ESMFCubeSphere) then
        allocate(elementCountPTile(tileCount),__STAT__)
        call ESMF_DistGridGet(distGrid,elementCountPTile=elementCountPTile,_RC)
        ! All tile should have same number of elements
        tileSize = elementCountPTile(1)
        tileSize = SQRT(real(tileSize))
        deallocate(elementCountPTile)
        deCount = size(minIndex,2)
        allocate(deToTileMap(deCount),__STAT__)
        allocate(oldMinIndex(2,deCount),oldMaxIndex(2,deCount),__STAT__)
        call ESMF_DistGridGet(distGrid,MaxIndexPDe=oldMaxIndex,MinIndexPDe=oldMinIndex, &
                              deToTileMap=deToTileMap,_RC)
        do i=1,deCount
           tile = deToTileMap(i)
           select case (tile)
              case (1)
                 minIndex(:,i)=oldMinIndex(:,i)
                 maxIndex(:,i)=oldMaxIndex(:,i)
              case (2)
                 minIndex(1,i)=oldMinIndex(1,i) -  tileSize
                 minIndex(2,i)=oldMinIndex(2,i) +  tileSize
                 maxIndex(1,i)=oldMaxIndex(1,i) -  tileSize
                 maxIndex(2,i)=oldMaxIndex(2,i) +  tileSize
              case (3)
                 minIndex(1,i)=oldMinIndex(1,i) -  tileSize
                 minIndex(2,i)=oldMinIndex(2,i) +  tileSize
                 maxIndex(1,i)=oldMaxIndex(1,i) -  tileSize
                 maxIndex(2,i)=oldMaxIndex(2,i) +  tileSize
              case (4)
                 minIndex(1,i)=oldMinIndex(1,i) -2*tileSize
                 minIndex(2,i)=oldMinIndex(2,i) +2*tileSize
                 maxIndex(1,i)=oldMaxIndex(1,i) -2*tileSize
                 maxIndex(2,i)=oldMaxIndex(2,i) +2*tileSize
              case (5)
                 minIndex(1,i)=oldMinIndex(1,i) -2*tileSize
                 minIndex(2,i)=oldMinIndex(2,i) +2*tileSize
                 maxIndex(1,i)=oldMaxIndex(1,i) -2*tileSize
                 maxIndex(2,i)=oldMaxIndex(2,i) +2*tileSize
              case (6)
                 minIndex(1,i)=oldMinIndex(1,i) -3*tileSize
                 minIndex(2,i)=oldMinIndex(2,i) +3*tileSize
                 maxIndex(1,i)=oldMaxIndex(1,i) -3*tileSize
                 maxIndex(2,i)=oldMaxIndex(2,i) +3*tileSize
           end select
        enddo
        deallocate(deToTileMap)
        deallocate(oldMaxIndex,oldMinIndex)
     else
        call ESMF_DistGridGet(distGrid,minIndexPDe=minIndex,maxIndexPDe=maxIndex,_RC)
     end if
 end subroutine MAPL_DistGridGet
Call graph
mapl_distgridget calls esmf_distgridget, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
arrayscatter_r8_2 calls mapl_distgridget
arraygather_r8_2 calls mapl_distgridget
create_cubed_sphere_grid calls mapl_distgridget
set calls mapl_distgridget
arraygather_r8_1 calls mapl_distgridget
arrayscatter_r4_2 calls mapl_distgridget
arrayscatter_r4_1 calls mapl_distgridget
esmfl_halo_r4_2d calls mapl_distgridget
get_esmf_grid_layout calls mapl_distgridget
arrayscatter_r8_1 calls mapl_distgridget
arraygather_i4_1 calls mapl_distgridget
mapl_gridgetinterior calls mapl_distgridget
arrayscattershmr4d1 calls mapl_distgridget
arraygather_r4_2 calls mapl_distgridget
mapl_createrequest calls mapl_distgridget
mapl_genericinitialize calls mapl_distgridget
arraygather_r4_1 calls mapl_distgridget
mapl_tilemaskget calls mapl_distgridget
esmfl_fcollect_i4 calls mapl_distgridget
esmfl_fcollect_r8 calls mapl_distgridget
mapl_grid_interior calls mapl_distgridget
mapl_gridgetsection calls mapl_distgridget
esmfl_fcollect_r4 calls mapl_distgridget