MAPL_GetResourceFromConfig_array – MAPL
MAPL_GetResourceFromConfig_array Subroutine
23 statements
Source File
private subroutine MAPL_GetResourceFromConfig_array(config, vals, label, unusable, default, value_is_set, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
class(*), intent(inout) :: vals(:)
character(len=*), intent(in) :: label
class(KeywordEnforcer), intent(in), optional :: unusable
class(*), intent(in), optional :: default(:)
logical, intent(out), optional :: value_is_set
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_GetResourceFromConfig_array
Source Code
   subroutine MAPL_GetResourceFromConfig_array(config, vals, label, unusable, default, value_is_set, rc)
      type(ESMF_Config), intent(inout) :: config
      character(len=*), intent(in) :: label
      class(*), intent(inout) :: vals(:)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      class(*), optional, intent(in) :: default(:)
      logical, optional, intent(out) :: value_is_set
      integer, optional, intent(out) :: rc
      integer :: status
      logical :: value_set
      _UNUSED_DUMMY(unusable)
      call MAPL_GetResource_config_array(config, vals, label, value_set, &
         default = default, rc=status)
      ! FIXME: assertion that value_set (TRUE) or return a non-negative rc value.
      ! Instead, optional argument value_is_set should to the value of value_set,
      ! an intent(out) argument to MAPL_GetResource_config_array..
      ! That differentiates a failed attempt to set value when there is no default
      ! and label is not found. However, some existing code catches the non-zero
      ! rc value to indicate failure to set the value and handles the failure
      ! by an alternative action. That code needs to use the value_is_set argument
      ! to determine failure. Once that code is fixed, the assertion should be
      ! removed.
      if(present(value_is_set)) then
         value_is_set = value_set
      end if
      if(.not. value_set) then
         if (present(rc)) rc = ESMF_FAILURE
         return
      end if
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GetResourceFromConfig_array
Call graph
mapl_getresourcefromconfig_array calls mapl_getresource_config_array, mapl_return, mapl_verify
mapl_getresource_config_array calls mapl_return, mapl_verify, ESMF_ConfigGetAttribute, array_format, mapl_assert, compare_all, get_actual_label, get_print_settings, make_string_character_array, print_resource, set_do_print
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
array_format calls array_format_simple, array_format_string
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_actual_label calls mapl_return, mapl_verify, ESMF_ConfigFindLabel, get_labels_with_prefix
get_error_message calls at
get_print_settings calls mapl_verify, ESMF_ConfigGetAttribute, mapl_am_i_root
mapl_throw_exception calls initialize
print_resource calls mapl_return
set_do_print calls vector_contains_str, push_back
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
vector_contains_str calls begin, next, of
mapl_getresource calls mapl_getresourcefromconfig_array
arrdescrsetncpar calls mapl_getresource
capture calls mapl_getresource, mapl_esmfstatewritetofile
get_test_framework_resource calls mapl_getresource
initialize_gc calls mapl_getresource, mapl_clockinit
mapl_clockinit calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource, arrdescrsetncpar
mapl_esmfstatewritetofile calls mapl_getresource, arrdescrsetncpar
mapl_genericfinalize calls mapl_getresource, mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_getresource
mapl_genericrecord calls mapl_getresource, mapl_staterecord
mapl_genericrefresh calls mapl_getresource, mapl_genericrefresh, mapl_staterefresh
mapl_genericstaterestore calls mapl_getresource, mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_getresource, mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_genericwrapper calls mapl_getresource, record_component
mapl_staterecord calls mapl_getresource, mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_getresource, mapl_esmfstatereadfromfile
mapl_checkpointstate calls mapl_esmfstatewritetofile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
record_component calls capture, get_test_framework_resource
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore