MAPL_VarSpecDestroy1 – MAPL
MAPL_VarSpecDestroy1 Subroutine
13 statements
Source File
private subroutine MAPL_VarSpecDestroy1(SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecDestroy1
Source Code
   subroutine MAPL_VarSpecDestroy1(SPEC, RC )
      type (MAPL_VarSpec ),             pointer      :: SPEC(:)
      integer            , optional   , intent(OUT)  :: RC
      integer :: i
      if (associated(SPEC)) then
         do I=1,size(SPEC)
            call MAPL_VarSpecDestroy0(spec(i))
         end do
         deallocate(SPEC)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecDestroy1
Call graph
mapl_varspecdestroy1 calls mapl_return, mapl_varspecdestroy0
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspecdestroy0 calls mapl_return
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecdestroy calls mapl_varspecdestroy1
mapl_genericstatedestroy calls mapl_varspecdestroy
mapl_genericfinalize calls mapl_genericstatedestroy
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize