MAPL_GridGetSection – MAPL
MAPL_GridGetSection Function
60 statements
Source File
private function MAPL_GridGetSection(GRID, SectionMap, GridName, RC) result(SECTION)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: GRID
integer, intent(in) :: SectionMap(:)
character(len=*), intent(in), optional :: GridName
integer, intent(out), optional :: RC
Return Value type(ESMF_Grid)
Calls
Contents
Source Code
MAPL_GridGetSection
Source Code
   function  MAPL_GridGetSection(Grid, SectionMap, GridName, RC) result(SECTION)
      type(ESMF_Grid),   intent(IN   ) :: GRID
      integer,           intent(IN   ) :: SectionMap(:)
      character (Len=*), optional, intent(IN   ) :: GridName
      integer, optional, intent(  OUT) :: RC
      type(ESMF_Grid) :: SECTION
      integer                          :: ndes
      integer                          :: dimcount
      integer                          :: nx, ny
      integer, allocatable             :: minindex(:,:)
      integer, allocatable             :: maxindex(:,:)
      integer, pointer                 :: ims(:) => null()
      integer, pointer                 :: jms(:) => null()
      real(ESMF_KIND_R8), pointer      :: centerX(:,:)
      real(ESMF_KIND_R8), pointer      :: centerY(:,:)
      real(ESMF_KIND_R8), pointer      :: coordX(:,:)
      real(ESMF_KIND_R8), pointer      :: coordY(:,:)
      type(ESMF_DistGrid)              :: distgrid
      type(ESMF_VM)                    :: vm
      character(len=ESMF_MAXSTR)       :: name
      integer              :: status
      call ESMF_GridGet(GRID, Name=Name, DistGrid=distgrid, dimCount=dimCount, RC=status)
      _VERIFY(status)
      if (present(GridName)) then
         name = GridName
      else
         name = name // "horz_section"
      end if
      _ASSERT(dimcount == size(SectionMap),'needs informative message')
      call ESMF_VmGetCurrent(VM, rc=status)
      _VERIFY(status)
      call ESMF_VmGet(VM, petCount=ndes, rc=status)
      _VERIFY(status)
      allocate(minindex(dimCount,ndes), maxindex(dimCount,ndes), stat=status)
      _VERIFY(status)
      ! Processors in each direction
      !-----------------------------
      call MAPL_DistGridGet(distgrid, &
           minIndex=minindex, &
           maxIndex=maxindex, rc=status)
      _VERIFY(status)
      call MAPL_GetImsJms(Imins=minindex(1,:),Imaxs=maxindex(1,:),&
           Jmins=minindex(2,:),Jmaxs=maxindex(2,:),Ims=ims,Jms=jms,rc=status)
      _VERIFY(status)
      deallocate(maxindex, minindex)
      NX = size(ims)
      NY = size(jms)
      ! Retrieve the coordinates so we can put them in the newly create SECTION
      call ESMF_GridGetCoord(GRID, coordDim=1, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=centerX, rc=status)
      _VERIFY(status)
      call ESMF_GridGetCoord(GRID, coordDim=2, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=centerY, rc=status)
      _VERIFY(status)
      SECTION = ESMF_GridCreate(          &
           name=name,                     &
           countsPerDEDim1=ims,           &
           countsPerDEDim2=jms,           &
                                !       indexFlag = ESMF_INDEX_GLOBAL, &
           coordDep1 = (/1,2/),           &
           coordDep2 = (/1,2/),           &
           gridEdgeLWidth = (/0,0/),      &
           gridEdgeUWidth = (/0,0/),      &
           rc=status)
      _VERIFY(status)
      ! Allocate coords at default stagger location
      call ESMF_GridAddCoord(SECTION, rc=status)
      _VERIFY(status)
      call ESMF_GridGetCoord(SECTION, coordDim=1, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=coordX, rc=status)
      _VERIFY(status)
      call ESMF_GridGetCoord(SECTION, coordDim=2, localDE=0, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=coordY, rc=status)
      _VERIFY(status)
      coordX = centerX
      coordY = centerY
      deallocate(jms, ims)
      _RETURN(ESMF_SUCCESS)
   end function MAPL_GridGetSection
Call graph
mapl_gridgetsection calls esmf_gridaddcoord, mapl_return, mapl_verify, esmf_vmgetcurrent, esmf_vmget, esmf_gridget, mapl_assert, mapl_distgridget, mapl_getimsjms, esmf_gridgetcoord, esmf_gridcreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_distgridget calls mapl_verify, esmf_distgridget
mapl_getimsjms calls mapl_return, mapl_verify, mapl_assert, mapl_sort