MAPL_ExtDataInterpField – MAPL
MAPL_ExtDataInterpField Subroutine
173 statements
Source File
private subroutine MAPL_ExtDataInterpField(item, time, field, vector_comp, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_Time), intent(in) :: time
type(ESMF_Field), intent(inout) :: field
integer, intent(in), optional :: vector_comp
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ExtDataInterpField
Source Code
  subroutine MAPL_ExtDataInterpField(item,time,field,vector_comp,rc)
     type(PrimaryExport), intent(inout) :: item
     type(ESMF_Time),     intent(in   ) :: time
     type(ESMF_Field),    intent(inout) :: field
     integer, optional,   intent(in   ) :: vector_comp
     integer, optional,   intent(out  ) :: rc
     character(len=ESMF_MAXSTR) :: Iam
     integer                    :: status
     type(ESMF_TimeInterval)    :: tinv1, tinv2
     real                       :: alpha
     real, pointer              :: var2d(:,:)   => null()
     real, pointer              :: var3d(:,:,:) => null()
     real, pointer              :: var2d_prev(:,:)   => null()
     real, pointer              :: var2d_next(:,:)   => null()
     real, pointer              :: var3d_prev(:,:,:) => null()
     real, pointer              :: var3d_next(:,:,:) => null()
     integer                    :: fieldRank,i,j,k
     character(len=ESMF_MAXSTR) :: name
     integer :: yr,mm,dd,hr,mn,sc,nhms1,nymd1,nhms2,nymd2
     Iam = "MAPL_ExtDataInterpField"
     alpha = 0.0
     if (item%doInterpolate) then
        tinv1 = time - item%interp_time1
        tinv2 = item%interp_time2 - item%interp_time1
        alpha = tinv1/tinv2
     end if
     call ESMF_FieldGet(FIELD, dimCount=fieldRank,name=name,_RC)
     if (lgr%isEnabledFor(DEBUG)) then
        call ESMF_TimeGet(item%interp_time1,yy=yr,mm=mm,dd=dd,h=hr,m=mn,s=sc,_RC)
        call MAPL_PackTime(nhms1,hr,mn,sc)
        call MAPL_PackTime(nymd1,yr,mm,dd)
        if (item%doInterpolate) then
           if (alpha .gt. 0.0) then
              call ESMF_TimeGet(item%interp_time2,yy=yr,mm=mm,dd=dd,h=hr,m=mn,s=sc,_RC)
              call MAPL_PackTime(nhms2,hr,mn,sc)
              call MAPL_PackTime(nymd2,yr,mm,dd)
           else
              nhms2=0
              nymd2=0
           end if
        else
           nhms2=0
           nymd2=0
        end if
        if (lgr%isEnabledFor(DEBUG) .and. .not. item%doInterpolate) then
           call lgr%debug('   MAPL_ExtDataInterpField: Uninterpolated field %a set to sample L %i0.8 %i0.6', trim(item%name),  nymd1, nhms1)
        else if (time == item%interp_time1) then
           call lgr%debug('   MAPL_ExtDataInterpField: Interpolated field %a set to sample L %i0.8 %i0.6', trim(item%name),  nymd1, nhms1)
        else if (time == item%interp_time2) then
           call lgr%debug('   MAPL_ExtDataInterpField: Interpolated field %a set to sample R %i0.8 %i0.6', trim(item%name),  nymd2, nhms2)
        else
           call lgr%debug('   MAPL_ExtDataInterpField: Interpolated field %a between %i0.8 %i0.6 and %i0.8 %i0.6 (%f10.6 fraction)', trim(item%name), nymd1, nhms1, nymd2, nhms2, alpha)
        end if
     end if
     call ESMF_FieldGet(FIELD, dimCount=fieldRank,name=name, _RC)
     if (fieldRank == 2) then
        if (item%vartype == MAPL_FieldItem) then
           call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var2d_prev, _RC)
           call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var2d_next, _RC)
        else if (item%vartype == MAPL_BundleItem) then
           call ESMFL_BundleGetPointerToData(item%binterp1,name,var2d_prev,_RC)
           call ESMFL_BundleGetPointerToData(item%binterp2,name,var2d_next,_RC)
        else if (item%vartype == MAPL_ExtDataVectorItem) then
           _ASSERT(present(vector_comp),'Vector comp must be present when performing vector interpolation')
           if (vector_comp == 1) then
              call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var2d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var2d_next, _RC)
           else if (vector_comp == 2) then
              call ESMF_FieldGet(item%modelGridFields%v2_finterp1, localDE=0, farrayPtr=var2d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v2_finterp2, localDE=0, farrayPtr=var2d_next, _RC)
          end if
        end if
        call ESMF_FieldGet(field, localDE=0, farrayPtr=var2d, _RC)
        ! only interpolate if we have to
        if (time == item%interp_time1 .or. item%doInterpolate .eqv. .false.) then
           var2d = var2d_prev
        else if (time == item%interp_time2) then
           var2d = var2d_next
        else
           do j=1,size(var2d,2)
              do i=1,size(var2d,1)
                 if (var2d_next(i,j) /= MAPL_UNDEF .and. var2d_prev(i,j) /= MAPL_UNDEF) then
                     var2d(i,j) = var2d_prev(i,j) + alpha*(var2d_next(i,j)-var2d_prev(i,j))
                 else
                     var2d(i,j) = MAPL_UNDEF
                 end if
              enddo
           enddo
        end if
        do j=1,size(var2d,2)
           do i=1,size(var2d,1)
              if (var2d(i,j) /= MAPL_UNDEF) then
                 if (item%do_scale .and. (.not.item%do_offset)) var2d(i,j) = item%scale*var2d(i,j)
                 if ((.not.item%do_scale) .and. item%do_offset) var2d(i,j) = var2d(i,j)+item%offset
                 if (item%do_scale .and. item%do_offset) var2d(i,j) = item%offset + (item%scale * var2d(i,j))
              else
                  var2d(i,j) = MAPL_UNDEF
              end if
           enddo
        enddo
      else if (fieldRank == 3) then
        if (item%vartype == MAPL_FieldItem) then
           call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var3d_prev, _RC)
           call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var3d_next, _RC)
        else if (item%vartype == MAPL_BundleItem) then
           call ESMFL_BundleGetPointerToData(item%binterp1,name,var3d_prev,_RC)
           call ESMFL_BundleGetPointerToData(item%binterp2,name,var3d_next,_RC)
        else if (item%vartype == MAPL_ExtDataVectorItem) then
           _ASSERT(present(vector_comp),'Vector comp must be present when performing vector interpolation')
           if (vector_comp == 1) then
              call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var3d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var3d_next, _RC)
           else if (vector_comp == 2) then
              call ESMF_FieldGet(item%modelGridFields%v2_finterp1, localDE=0, farrayPtr=var3d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v2_finterp2, localDE=0, farrayPtr=var3d_next, _RC)
           end if
        end if
        call ESMF_FieldGet(field, localDE=0, farrayPtr=var3d, _RC)
        ! only interpolate if we have to
        if (time == item%interp_time1 .or. item%doInterpolate .eqv. .false.) then
           var3d = var3d_prev
        else if (time == item%interp_time2) then
           var3d = var3d_next
        else
           do k=lbound(var3d,3),ubound(var3d,3)
              do j=1,size(var3d,2)
                 do i=1,size(var3d,1)
                    if (var3d_next(i,j,k) /= MAPL_UNDEF .and. var3d_prev(i,j,k) /= MAPL_UNDEF) then
                        var3d(i,j,k) = var3d_prev(i,j,k) + alpha*(var3d_next(i,j,k)-var3d_prev(i,j,k))
                    else
                        var3d(i,j,k) = MAPL_UNDEF
                    end if
                 enddo
              enddo
            enddo
        end if
        do k=lbound(var3d,3),ubound(var3d,3)
           do j=1,size(var3d,2)
              do i=1,size(var3d,1)
                 if (var3d(i,j,k) /= MAPL_UNDEF) then
                    if (item%do_scale .and. (.not.item%do_offset)) var3d(i,j,k) = item%scale*var3d(i,j,k)
                    if ((.not.item%do_scale) .and. item%do_offset) var3d(i,j,k) = var3d(i,j,k)+item%offset
                    if (item%do_scale .and. item%do_offset) var3d(i,j,k) = item%offset + (item%scale * var3d(i,j,k))
                 else
                     var3d(i,j,k) = MAPL_UNDEF
                 end if
              enddo
           enddo
        enddo
     endif
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataInterpField
Call graph
mapl_extdatainterpfield calls ESMF_TimeGet, debug, esmf_fieldget, esmfl_bundlegetpointertodata, mapl_assert, mapl_packtime, isenabledfor, mapl_return, mapl_verify
esmfl_bundlegetpointertodata calls esmfl_bundlegetpointerbyindex2, esmfl_bundlegetpointerbyindex3, esmfl_bundlegetpointerbyname2, esmfl_bundlegetpointerbyname3
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_packtime calls mapl_packtime
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_bundlegetpointerbyindex2 calls esmf_fieldget, mapl_return, mapl_verify, esmf_fieldbundleget
esmfl_bundlegetpointerbyindex3 calls esmf_fieldget, mapl_return, mapl_verify, esmf_fieldbundleget
esmfl_bundlegetpointerbyname2 calls esmf_fieldget, mapl_return, mapl_verify, esmf_fieldbundleget
esmfl_bundlegetpointerbyname3 calls esmf_fieldget, mapl_return, mapl_verify, esmf_fieldbundleget
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run_ calls mapl_extdatainterpfield