MAPL_tick – MAPL
MAPL_tick Module Subroutine
24 statements
Source File
module subroutine MAPL_tick(nymd, nhms, ndt) Interface →
Arguments
Type Intent Optional Attributes Name
integer :: nymd
integer :: nhms
integer :: ndt
Calls
Called by
Contents
Source Code
MAPL_tick
Source Code
  module subroutine MAPL_tick (nymd,nhms,ndt)
    integer nymd,nhms,ndt,nsec
    IF(NDT.NE.0) THEN
       NSEC = MAPL_NSECF(NHMS) + NDT
       IF (NSEC.GT.86400)  THEN
          DO WHILE (NSEC.GT.86400)
             NSEC = NSEC - 86400
             NYMD = MAPL_INCYMD (NYMD,1)
          ENDDO
       ENDIF
       IF (NSEC.EQ.86400)  THEN
          NSEC = 0
          NYMD = MAPL_INCYMD (NYMD,1)
       ENDIF
       IF (NSEC.LT.00000)  THEN
          DO WHILE (NSEC.LT.0)
             NSEC = 86400 + NSEC
             NYMD = MAPL_INCYMD (NYMD,-1)
          ENDDO
       ENDIF
       NHMS = MAPL_NHMSF (NSEC)
    ENDIF
    RETURN
  end subroutine MAPL_tick
Call graph
mapl_tick calls mapl_incymd, mapl_nhmsf, mapl_nsecf, mapl_tick
mapl_incymd calls mapl_incymd, mapl_leap
mapl_nhmsf calls mapl_nhmsf
mapl_nsecf calls mapl_nsecf
mapl_leap calls mapl_leap