MAPL_ConnectivityGet – MAPL
MAPL_ConnectivityGet Subroutine
12 statements
Source File
private subroutine MAPL_ConnectivityGet(gc, connectivityPtr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(MAPL_Connectivity), pointer :: connectivityPtr
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_ConnectivityGet(gc, connectivityPtr, RC)
      type(ESMF_GridComp), intent(inout) :: gc
      integer, optional, intent(out) :: rc
      type (MAPL_Connectivity), pointer :: connectivityPtr
      type (MAPL_MetaComp), pointer :: meta
      integer                       :: status
      call MAPL_GetObjectFromGC(gc, meta, rc=status)
      _VERIFY(status)
      connectivityPtr => meta%connectList
      _RETURN(_SUCCESS)
   end subroutine MAPL_ConnectivityGet
Call graph
mapl_connectivityget calls mapl_getobjectfromgc, mapl_return, mapl_verify
mapl_getobjectfromgc calls mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_addconnectivitye2e calls mapl_connectivityget
mapl_addconnectivityrename calls mapl_connectivityget
mapl_connectservice calls mapl_connectivityget
mapl_donotconnect calls mapl_connectivityget
mapl_terminateimportallbut calls mapl_connectivityget, mapl_donotconnect
mapl_wirecomponent calls mapl_connectivityget
mapl_addconnectivity calls mapl_addconnectivityrename, mapl_addconnectivitymany, mapl_addconnectivityrenamemany
mapl_terminateimport calls mapl_donotconnect, mapl_terminateimportallbut, mapl_donotconnectanyimport, mapl_donotconnectmany, mapl_terminateimportall
mapl_addconnectivitymany calls mapl_addconnectivityrename
mapl_donotconnectanyimport calls mapl_donotconnect
mapl_donotconnectmany calls mapl_donotconnect
mapl_genericsetservices calls mapl_wirecomponent
mapl_stateaddexportspecfrmchldname calls mapl_addconnectivitye2e
mapl_addconnectivityrenamemany calls mapl_addconnectivity
mapl_stateaddexportspecfrmchld calls mapl_stateaddexportspecfrmchldname
mapl_terminateimportall calls mapl_terminateimport
setservices calls mapl_genericsetservices
mapl_addexportspec calls mapl_stateaddexportspecfrmchld
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld