MAPL_VarReadNCpar_R4_3d – MAPL
MAPL_VarReadNCpar_R4_3d Subroutine
15 statements
Source File
private subroutine MAPL_VarReadNCpar_R4_3d(formatter, name, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R4), intent(inout) :: A(:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarReadNCpar_R4_3d
Source Code
  subroutine MAPL_VarReadNCpar_R4_3d(formatter, name, A, ARRDES, RC)
    type (Netcdf4_Fileformatter)          , intent(IN   ) :: formatter
    character(len=*)            , intent(IN   ) :: name
    real(kind=ESMF_KIND_R4)     , intent(INOUT) :: A(:,:,:)
    type(ArrDescr), optional    , intent(INOUT) :: ARRDES
    integer,           optional , intent(  OUT) :: RC
    integer                               :: status
    integer :: l
    do l=1,size(a,3)
       call MAPL_VarRead(formatter,name,A(:,:,l), arrdes=arrdes, lev=l, rc=status)
       _VERIFY(status)
    enddo
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarReadNCpar_R4_3d
Call graph
mapl_varreadncpar_r4_3d calls mapl_varread, mapl_return, mapl_verify
mapl_varread calls mapl_varreadncpar_r4_3d, mapl_varreadncpar_r4_1d, mapl_varreadncpar_r4_2d, mapl_varreadncpar_r8_1d, mapl_varreadncpar_r8_2d, mapl_varreadncpar_r8_3d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varreadncpar_r4_1d calls mapl_return, mapl_verify, get_var, mapl_am_i_root, mapl_assert, mapl_commsbcast, mapl_sort, mpi_comm_create, mpi_comm_free, mpi_comm_group, mpi_comm_rank, mpi_comm_size, mpi_group_free, mpi_group_incl, mpi_group_translate_ranks, mpi_scatterv, nf90_strerror
mapl_varreadncpar_r4_2d calls mapl_return, mapl_verify, get_var, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_strerror
mapl_varreadncpar_r8_1d calls mapl_return, mapl_verify, get_var, mapl_am_i_root, mapl_assert, mapl_commsbcast, mapl_sort, mpi_comm_create, mpi_comm_free, mpi_comm_group, mpi_comm_rank, mpi_comm_size, mpi_group_free, mpi_group_incl, mpi_group_translate_ranks, mpi_scatterv, nf90_strerror
mapl_varreadncpar_r8_2d calls mapl_return, mapl_verify, get_var, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_strerror
mapl_varreadncpar_r8_3d calls mapl_varread, mapl_return, mapl_verify
mapl_fieldreadncpar calls mapl_varread
mapl_bundlereadncpar calls mapl_fieldreadncpar
mapl_varreadncpar calls mapl_bundlereadncpar