MAPL_RoundRobinPEList – MAPL
MAPL_RoundRobinPEList Subroutine
60 statements
Source File
public subroutine MAPL_RoundRobinPEList(List, nNodes, Root, UseFirstRank, FirstRank, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: List(:)
integer, intent(in) :: nNodes
integer, intent(in), optional :: Root
logical, intent(in), optional :: UseFirstRank
integer, intent(out), optional :: FirstRank
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_RoundRobinPEList
Source Code
  subroutine MAPL_RoundRobinPEList(List,nNodes,Root,UseFirstRank,FirstRank,RC)
    integer,           intent(  OUT) :: List(:)
    integer,           intent(IN   ) :: nNodes
    integer, optional, intent(IN   ) :: Root
    logical, optional, intent(IN   ) :: UseFirstRank
    integer, optional, intent(out  ) :: FirstRank
    integer, optional, intent(  OUT) :: RC
    integer                    :: status
    integer, allocatable :: filled(:),nPerNode(:)
    integer :: i,n,nlist,locRoot
    logical :: gotFirstRank,lUseFirstRank
    if (present(Root)) then
       locRoot = Root
    else
       locRoot = 1
    endif
    if (present(UseFirstRank)) then
       lUseFirstRank=UseFirstRank
    else
       lUseFirstRank=.true.
    end if
    gotFirstRank = .false.
    if (present(UseFirstRank)) then
       lUseFirstRank=UseFirstRank
    else
       lUseFirstRank=.true.
    end if
    allocate(filled(nNodes),nPerNode(nNodes),stat=status)
    _VERIFY(STATUS)
    do i=1,nNodes
       nPerNode(i) = size(MAPL_NodeRankList(locRoot+i-1)%rank)
       if (lUseFirstRank) then
          filled(i)=0
       else
          filled(i)=MAPL_GetNewRank(locRoot+i-1,rc=status)-1
          _VERIFY(status)
       end if
    enddo
    nlist = size(list)
    n=0
    do
       do i=1,nNodes
          if (filled(i) < size(MAPL_NodeRankList(locRoot+i-1)%rank)) then
             filled(i) = filled(i) + 1
             n=n+1
             list(n) = MAPL_NodeRankList(locRoot+i-1)%rank(filled(i))
             if (.not.gotFirstRank .and. present(FirstRank)) then
                gotFirstRank=.true.
                FirstRank = list(n)
             end if
          end if
          if (n == nlist) exit
       enddo
       if (n == nlist) exit
       if (All(filled == nPerNode)) filled = 0
    enddo
    deallocate(filled,nPerNode)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_RoundRobinPEList
Call graph
mapl_roundrobinpelist calls mapl_getnewrank, mapl_return, mapl_verify
mapl_getnewrank calls mapl_getnewrank, mapl_return, mapl_noderanklist
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
make_regridder calls mapl_roundrobinpelist, make_regridder
mapl_cfiocreatefrombundle calls mapl_roundrobinpelist, make_regridder
mapl_cfioreadbundle calls mapl_roundrobinpelist, make_regridder, mapl_collectivescatter3d
mapl_cfioreadbundleread calls mapl_roundrobinpelist
mapl_cfiosetkrank calls mapl_roundrobinpelist
mapl_collectivegather3d calls mapl_roundrobinpelist
mapl_collectivescatter3d calls mapl_roundrobinpelist
esmf_iocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls mapl_cfioreadbundleread, mapl_cfiocreatefromfile
mapl_cfioreadstate calls mapl_cfioreadbundle
regrid_scalar_3d_real32 calls mapl_collectivegather3d, mapl_collectivescatter3d
mapl_cfioreadparallel calls mapl_cfioreadparallel_
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
mapl_simplebundlewrite1 calls mapl_cfiocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
test_main calls mapl_cfioread, esmf_iocreate, esmf_ioread