MAPL_GridGet – MAPL
MAPL_GridGet Subroutine
69 statements
Source File
public subroutine MAPL_GridGet(GRID, globalCellCountPerDim, localCellCountPerDim, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: GRID
integer, intent(inout), optional :: globalCellCountPerDim(:)
integer, intent(inout), optional :: localCellCountPerDim(:)
integer, intent(out), optional :: RC
Calls
Called by
Base_Implementation::MAPL_BundleCreate w mapl_MaplGrid::MAPL_GridGet
w
Base_Implementation::MAPL_FieldAllocCommit w
w
Base_Implementation::MAPL_FieldCreateNewgrid w
w
Base_Implementation::MAPL_GetGlobalHorzIJIndex w
w
Base_Implementation::MAPL_GetHorzIJIndex w
w
Base_Implementation::MAPL_GridGetCorners w
w
Base_Implementation::MAPL_SetPointer2DR4 w
w
Base_Implementation::MAPL_SetPointer3DR4 w
w
BinIOMod::MAPL_VarRead_R4_1d w
w
BinIOMod::MAPL_VarRead_R4_2d w
w
BinIOMod::MAPL_VarRead_R8_1d w
w
BinIOMod::MAPL_VarRead_R8_2d w
w
BinIOMod::MAPL_VarWrite_I4_1d w
w
BinIOMod::MAPL_VarWrite_R4_1d w
w
BinIOMod::MAPL_VarWrite_R4_2d w
w
BinIOMod::MAPL_VarWrite_R8_1d w
w
BinIOMod::MAPL_VarWrite_R8_2d w
w
ESMFL_MOD::BundleRegrid1 w
w
ESMFL_MOD::ESMFL_field_is_undefined w
w
ESMFL_MOD::ESMFL_FieldGetDims w
w
ESMFL_MOD::ESMFL_GridCoordGet w
w
ESMFL_MOD::ESMFL_HALO_R4_2D w
w
ESMFL_MOD::MAPL_AreaMean_2d_r8_bitrep w
w
ExtDataUtRoot_GridCompMod::FillState w
w
FileIOSharedMod::MAPL_TileMaskGet w
w
linearVerticalInterpolation_mod::vertInterpolation_pressKappa w
w
MAPL_AbstractGridFactoryMod::ComputeGridBasis w
w
MAPL_CFIOMod::GridGetLatLons_ w
w
MAPL_CFIOMod::MAPL_CFIOCreateFromBundle w
w
MAPL_CFIOMod::MAPL_CFIOCreateFromFile w
w
MAPL_CFIOMod::MAPL_CFIOReadBundle w
w
MAPL_CFIOMod::MAPL_CFIOReadBundleRead w
w
MAPL_CFIOMod::MAPL_CFIOWriteBundlePost w
w
MAPL_CFIOMod::MAPL_CFIOWriteBundleWait w
w
MAPL_CFIOMod::MAPL_CFIOWriteBundleWrite w
w
MAPL_CommsMod::MAPL_CollectiveGather3D w
w
MAPL_CubedSphereGridFactoryMod::CubedSphereGridFactory%generate_file_bounds w
w
MAPL_CubedSphereGridFactoryMod::CubedSphereGridFactory%generate_file_corner_bounds w
w
MAPL_ESMFFieldBundleRead::MAPL_create_bundle_from_metdata_id w
w
MAPL_ExtDataGridComp2G::MAPL_ExtDataGridChangeLev w
w
MAPL_ExtDataGridCompMod::MAPL_ExtDataEvaluateMask w
w
MAPL_ExtDataGridCompMod::MAPL_ExtDataGridChangeLev w
w
MAPL_ExtDataMask::ExtDataMask%evaluate_box_mask w
w
MAPL_GenericMod::ArrDescrSetNCPar w
w
MAPL_GenericMod::MAPL_ESMFStateReadFromFile w
w
MAPL_GenericMod::MAPL_ESMFStateWriteToFile w
w
MAPL_GenericMod::MAPL_GenericInitialize w
w
MAPL_GenericMod::MAPL_GridCoordAdjustFromFile w
w
MAPL_GenericMod::MAPL_ReadForcingX w
w
MAPL_GetLatLonCoordMod::MAPL_GetLatLonCoord_REAL32 w
w
MAPL_GetLatLonCoordMod::MAPL_GetLatLonCoord_REAL64 w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%check_chunking w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%request_data_from_file w
w
MAPL_GriddedIOMod::MAPL_GriddedIO%set_default_chunking w
w
MAPL_HistoryGridCompMod::Initialize w
w
MAPL_HistoryGridCompMod::MAPL_GradsCtlWrite w
w
MAPL_HistoryGridCompMod::RegridTransformT2G2G w
w
mapl_HorizontalFluxRegridder::HorizontalFluxRegridder%initialize_subclass w
w
mapl_HorizontalFluxRegridder::HorizontalFluxRegridder%supports w
w
MAPL_LatLonGridFactoryMod::LatLonGridFactory%generate_file_bounds w
w
MAPL_LatLonToLatLonRegridderMod::LatLonToLatLonRegridder%initialize_subclass w
w
MAPL_LatLonToLatLonRegridderMod::LatLonToLatLonRegridder%regrid_scalar_3d_real32 w
w
MAPL_LocStreamMod::MAPL_GridCoordAdjust w
w
MAPL_LocStreamMod::MAPL_LocStreamAttachGrid w
w
mapl_MaplGrid::GridCoordGet w
w
mapl_MaplGrid::MaplGrid%set w
w
MAPL_OpenMP_Support::make_subfields_from_num_grids w
w
MAPL_OpenMP_Support::make_subgrids_from_bounds w
w
MAPL_OpenMP_Support::make_subgrids_from_num_grids w
w
MAPL_OrbGridCompMod::Run_ w
w
MAPL_SimpleBundleMod::MAPL_SimpleBundleCreateEmpty w
w
MAPL_SimpleBundleMod::MAPL_SimpleBundleCreateFromBundle w
w
MAPL_TileIOMod::MAPL_TileIO%request_data_from_file w
w
MAPL_TripolarGridFactoryMod::TripolarGridFactory%add_horz_coordinates_from_file w
w
MAPL_TripolarGridFactoryMod::TripolarGridFactory%generate_file_bounds w
w
MAPL_TripolarGridFactoryMod::TripolarGridFactory%generate_file_corner_bounds w
w
MAPL_VerticalDataMod::verticalData%setup_eta_to_pressure w
w
MAPL_XYGridFactoryMod::XYGridFactory%add_horz_coordinates_from_file w
w
MAPL_XYGridFactoryMod::XYGridFactory%generate_file_bounds w
w
MAPL_XYGridFactoryMod::XYGridFactory%generate_file_corner_bounds w
w
NCIOMod::compare_grid_file w
w
NCIOMod::MAPL_VarWriteNCpar_R4_2d w
w
NCIOMod::MAPL_VarWriteNCpar_R4_3d w
w
NCIOMod::MAPL_VarWriteNCpar_R4_4d w
w
NCIOMod::MAPL_VarWriteNCpar_R8_2d w
w
NCIOMod::MAPL_VarWriteNCpar_R8_3d w
w
NCIOMod::MAPL_VarWriteNCpar_R8_4d w
w
regrid_util_support_mod::regrid_support%has_level w
w
time_ave w
w
time_ave::has_level w
w
time_ave::latlon_zmean w
w
time_ave::latlon_zstar w
w
utCFIO::test_main w
w
Source Code
  subroutine MAPL_GridGet(GRID, globalCellCountPerDim, localCellCountPerDim, RC)
      type (ESMF_Grid), intent(IN) :: GRID
      integer, optional, intent(INout) :: globalCellCountPerDim(:)
      integer, optional, intent(INout) :: localCellCountPerDim(:)
      integer, optional, intent(  OUT) :: RC
! local vars
      integer :: status
      integer :: mincounts(ESMF_MAXDIM)
      integer :: maxcounts(ESMF_MAXDIM)
      integer :: gridRank
      integer :: UNGRID
      integer :: sz, tileCount
      logical :: plocal, pglobal, lxtradim
      logical :: isPresent,hasDE
      pglobal = present(globalCellCountPerDim)
      plocal  = present(localCellCountPerDim)
      if (pglobal .or. plocal) then
         call ESMF_GridGet(grid, dimCount=gridRank, _RC)
!ALT kludge
         lxtradim = .false.
         if (gridRank == 1) then
            call ESMF_AttributeGet(grid, name='GRID_EXTRADIM', isPresent=isPresent, _RC)
            if (isPresent) then
               call ESMF_AttributeGet(grid, name='GRID_EXTRADIM', value=UNGRID, _RC)
               lxtradim = .true.
            end if
         else if (gridRank == 2) then
            call ESMF_AttributeGet(grid, name='GRID_LM', isPresent=isPresent, _RC)
            if (isPresent) then
               call ESMF_AttributeGet(grid, name='GRID_LM', value=UNGRID, _RC)
               lxtradim = .true.
            end if
         end if
      end if
      if (pglobal) then
         globalCellCountPerDim = 1
         call ESMF_GridGet(grid, tileCount=tileCount,_RC)
         call ESMF_GridGet(grid, tile=1, staggerLoc=ESMF_STAGGERLOC_CENTER, &
              minIndex=mincounts, &
              maxIndex=maxcounts, &
              _RC      )
         sz = min(gridRank, ESMF_MAXDIM, size(globalCellCountPerDim))
         globalCellCountPerDim(1:sz) = maxcounts(1:sz)-mincounts(1:sz)+1
         ! kludge for new cube sphere from ESMF
         if (tileCount == 6) then
            if (globalCellCountPerDim(1) /= 1) then ! kludge-on-the-kludge for Single-Column case
               globalCellCountPerDim(2)=globalCellCountPerDim(2)*6
            end if
         end if
         if (lxtradim ) then
            globalCellCountPerDim(gridRank+1) = UNGRID
         end if
      end if
      if (plocal) then
         localCellCountPerDim = 1
         HasDE = MAPL_GridHasDE(grid,_RC)
         if (HasDE) then
            call ESMF_GridGet(GRID, localDE=0, &
                 staggerloc=ESMF_STAGGERLOC_CENTER, &
                 exclusiveCount=localCellCountPerDim, _RC)
         end if
         if (lxtradim ) then
            localCellCountPerDim(gridRank+1) = UNGRID
         end if
      end if
      _RETURN(ESMF_SUCCESS)
    end subroutine MAPL_GridGet
Call graph
mapl_gridget calls ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde, mapl_return, mapl_verify
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize