MAPL_UnpackTime – MAPL
MAPL_UnpackTime Module Subroutine
9 statements
Source File
module subroutine MAPL_UnpackTime(TIME, IYY, IMM, IDD) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: TIME
integer, intent(out) :: IYY
integer, intent(out) :: IMM
integer, intent(out) :: IDD
Called by
Contents
Source Code
MAPL_UnpackTime
Source Code
  module subroutine MAPL_UnpackTime(TIME,IYY,IMM,IDD)
    integer, intent (IN ) :: TIME
    integer, intent (OUT) :: IYY
    integer, intent (OUT) :: IMM
    integer, intent (OUT) :: IDD
    IYY = TIME/10000
    IMM = mod(TIME/100,100)
    IDD = mod(TIME,100)
  end subroutine MAPL_UnpackTime
Call graph
mapl_unpacktime calls mapl_unpacktime
get_acc_offset calls mapl_unpacktime
gettimesonfile calls mapl_unpacktime
gettindex calls mapl_unpacktime
initialize_ calls mapl_unpacktime
mapl_stategettimestamp calls mapl_unpacktime
set_time_for_date calls mapl_unpacktime
evaluate_time calls set_time_for_date
initialize calls get_acc_offset
mapl_cfioreadparallel_ calls gettindex
mapl_readforcingx calls mapl_stategettimestamp
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx