MAPL_GenericStateDestroy – MAPL
MAPL_GenericStateDestroy Subroutine
35 statements
Source File
private subroutine MAPL_GenericStateDestroy(STATE, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), pointer :: STATE
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GenericStateDestroy (STATE,RC)
      type (MAPL_MetaComp), pointer              :: STATE
      integer, optional,           intent(  OUT) :: rc     ! Error code:
      character(len=ESMF_MAXSTR), parameter :: IAm = "MAPL_GenericStateDestroy"
      logical :: isCreated
      integer :: status
      type(ESMF_State), pointer :: internal_state
      if(associated(STATE)) then
         call MAPL_SunOrbitDestroy    (STATE%ORBIT         ,RC=status)
         _VERIFY(status)
         internal_state => state%get_internal_state()
         isCreated = ESMF_StateIsCreated(internal_state, RC=status)
         _VERIFY(status)
         if (isCreated) then
            call ESMF_StateDestroy       (internal_state, _RC)
         end if
         isCreated = ESMF_StateIsCreated(STATE%FORCING, RC=status)
         _VERIFY(status)
         if (isCreated) then
            call ESMF_StateDestroy       (STATE%FORCING      ,RC=status)
            _VERIFY(status)
         end if
         !       call MAPL_VarSpecDestroy     (STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS   ,RC=status)
         !       _VERIFY(status)
         !       call MAPL_VarSpecDestroy     (STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS   ,RC=status)
         !       _VERIFY(status)
         !       call MAPL_VarSpecDestroy     (STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS ,RC=status)
         !       _VERIFY(status)
         call MAPL_VarSpecDestroy     (STATE%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS   ,RC=status)
         _VERIFY(status)
         if(associated(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS)  ) deallocate(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS)
         if(associated(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS)) deallocate(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS)
         if(allocated(STATE%GCNameList   )) deallocate(STATE%GCNameList   )
         if(associated(STATE%CCS          )) deallocate(STATE%CCS          )
         if(associated(STATE%CIM          )) deallocate(STATE%CIM          )
         if(associated(STATE%CEX          )) deallocate(STATE%CEX          )
         !ALT: still to do: clean LINK, LOCSTREAM, EXCHANGEGRID, RECORD
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericStateDestroy
Call graph
mapl_genericstatedestroy calls esmf_statedestroy, esmf_stateiscreated, mapl_varspecdestroy, get_internal_state, mapl_return, mapl_sunorbitdestroy, mapl_verify
mapl_varspecdestroy calls mapl_varspecdestroy0, mapl_varspecdestroy1
get_internal_state calls get_current_thread, is_threading_active
mapl_return calls get_error_message, mapl_throw_exception
mapl_sunorbitdestroy calls mapl_return
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecdestroy0 calls mapl_return
mapl_varspecdestroy1 calls mapl_return, mapl_varspecdestroy0
mapl_genericfinalize calls mapl_genericstatedestroy
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize