MAPL_FinalizeShmem – MAPL
MAPL_FinalizeShmem Module Procedure
45 statements
Source File
module procedure MAPL_FinalizeShmem module subroutine MAPL_FinalizeShmem(rc) Interface →
! Everyone detaches address from shared segment
! Make sure everyone has finished detaching
! The root processor destroys the segment
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_finalizeshmem calls mapl_assert, shmctl, shmdt, mapl_noderanklist, mpi_barrier, mpi_comm_free, mapl_return, segs, mapl_finalizeshmem
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
finalize_gc calls mapl_finalizeshmem