MAPL_VarSpecReconnect – MAPL
MAPL_VarSpecReconnect Subroutine
50 statements
Source File
public subroutine MAPL_VarSpecReconnect(SPEC, ITEM, RC)
ITEM%SPECptr => SPEC(I)%SPECPtr
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(inout) :: ITEM
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_VarSpecReconnect
Source Code
   subroutine MAPL_VarSpecReconnect(SPEC,ITEM,RC)
      type (MAPL_VarSpec ), pointer         :: SPEC(:)
      type (MAPL_VarSpec ), intent(INOUT)   :: ITEM
      integer, optional   , intent(OUT)     :: RC
      integer                               :: STATUS
      type(ESMF_Field), pointer             :: FIELD
      type(ESMF_FieldBundle), pointer       :: BUNDLE
      type(ESMF_State), pointer       :: STATE
      integer I
      if(.not.associated(ITEM%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      if(.not.associated(SPEC)) then
         _RETURN(ESMF_FAILURE)
      endif
      I=MAPL_VarSpecGetIndex(SPEC, ITEM, RC=STATUS)
      _VERIFY(STATUS)
      if (I == -1) then
         _RETURN(ESMF_FAILURE)
      endif
      if (associated(ITEM%SPECptr%FIELD)) then
         deallocate(ITEM%SPECptr%FIELD, STAT=STATUS)
         _VERIFY(STATUS)
      end if
      call MAPL_VarSpecGet(SPEC(I), FIELDPTR=FIELD, RC=STATUS)
      _VERIFY(STATUS)
      call MAPL_VarSpecSet(ITEM, FIELDPTR=FIELD, RC=STATUS)
      _VERIFY(STATUS)
      if (associated(ITEM%SPECptr%BUNDLE)) then
         deallocate(ITEM%SPECptr%BUNDLE, STAT=STATUS)
         _VERIFY(STATUS)
      end if
      call MAPL_VarSpecGet(SPEC(I), BUNDLEPTR=BUNDLE, RC=STATUS)
      _VERIFY(STATUS)
      call MAPL_VarSpecSet(ITEM, BUNDLEPTR=BUNDLE, RC=STATUS)
      _VERIFY(STATUS)
      if (associated(ITEM%SPECptr%STATE)) then
         deallocate(ITEM%SPECptr%STATE, STAT=STATUS)
         _VERIFY(STATUS)
      end if
      call MAPL_VarSpecGet(SPEC(I), STATEPTR=STATE, RC=STATUS)
      _VERIFY(STATUS)
      call MAPL_VarSpecSet(ITEM, STATEPTR=STATE, RC=STATUS)
      _VERIFY(STATUS)
      !      deallocate(ITEM%SPECptr, stat=status)
      !      _VERIFY(STATUS)
      !!      ITEM%SPECptr => SPEC(I)%SPECPtr
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecReconnect
Call graph
mapl_varspecreconnect calls mapl_return, mapl_varspecgetindex, mapl_verify, mapl_varspecset, mapl_varspecget
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_verify calls mapl_throw_exception
mapl_varspecset calls mapl_varspecsetnew
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetfieldptr, mapl_varspecgetstateptr, mapl_varspecgetnew, mapl_varspecgetbundleptr
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_throw_exception calls initialize
mapl_varspecsetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetbundleptr calls mapl_return