MAPL_CommsBcastVM_STRING_0 – MAPL
MAPL_CommsBcastVM_STRING_0 Subroutine
27 statements
Source File
private subroutine MAPL_CommsBcastVM_STRING_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
character(len=*), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CommsBcastVM_STRING_0
Source Code
  subroutine MAPL_CommsBcastVM_STRING_0( vm, data, N, ROOT,RC)
    type (ESMF_VM)                               :: vm
    character(len=*),   intent(INOUT)            :: data
    integer,            intent(in   )            :: N
    integer,            intent(in   )            :: ROOT
    integer         ,   intent(  out),  optional :: RC
    character(len=N)                      :: tmpString
    integer                               :: slen
    integer                               :: status
    integer                               :: comm
    integer                               :: deId
    call ESMF_VMGet(vm, mpiCommunicator=COMM, localPet=deId, rc=status)
    _VERIFY(STATUS)
    tmpString = data
    if (deId == Root) then
       slen = len_trim(tmpString)
    end if
    call MPI_Bcast(slen, 1, MPI_INTEGER, ROOT, COMM, status)
    _VERIFY(STATUS)
    _ASSERT(slen <= N, 'exceeded string length')
    call MPI_Bcast(tmpString, slen, MPI_BYTE, ROOT, COMM, STATUS)
    _VERIFY(STATUS)
    data = ""
    data = tmpString(1:slen)
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE MAPL_CommsBcastVM_STRING_0
Call graph
mapl_commsbcastvm_string_0 calls ESMF_VMGet, mapl_assert, mpi_bcast, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_commsbcast calls mapl_commsbcastvm_string_0