MAPL_CFIOWriteState – MAPL
MAPL_CFIOWriteState Subroutine
21 statements
Source File
private subroutine MAPL_CFIOWriteState(MCFIO, CLOCK, STATE, VERBOSE, NBITS, RC)
ALT else ALT tBUNDLE = MCFIO%BUNDLE ALT end if
ALT if(present(STATE)) then ALT endif
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
type(ESMF_Clock), intent(inout) :: CLOCK
type(ESMF_State), intent(inout) :: STATE
logical, intent(in), optional :: VERBOSE
integer, intent(in), optional :: NBITS
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CFIOWriteState
Source Code
  subroutine MAPL_CFIOWriteState ( MCFIO, CLOCK, State, &
                                   VERBOSE, NBITS, RC   )
!
! !ARGUMENTS:
!
    type(MAPL_CFIO),             intent(INOUT) :: MCFIO
    type(ESMF_State),            intent(INout) :: STATE
    type(ESMF_CLOCK),            intent(INOUT) :: CLOCK
    integer, optional,           intent(  OUT) :: RC
    logical, optional,           intent(  IN)  :: VERBOSE
    integer, optional,           intent(  IN)  :: NBITS
!
#ifdef ___PROTEX___
    !DESCRIPTION:
     Serializes an ESMF state into a Bundle and writes it to a file.
     Only the MAPL\_CFIO object is a required argument as pointers to
     the actual data to be written is recorded in it during creation.
     {\tt CLOCK, BUNDLE} can be used to override the choice
     made at creation, but this is of dubious value, particularly
     for {\tt BUNDLE} since it must be excatly conformant with the
     creation {\tt BUNDLE}. {\tt NBITS} if the number of bits of
     the mantissa to retain. This is used to write files with degraded
     precision, which can then be compressed with standard utilities.
     The default is no degradation of precision.
     {\bf A note about compression.} NetCDF-4, HDF-4 and HDF-5 all
     support transparent internal GZIP compression of the data being
     written. However, very little is gained by compressing float
     point fields from earth system models. Compression yields can
     be greatly increased by setting to zero bits in the mantissa of float
     numbers. On average 50\% compression can be achieved, while
     preserving a meaningful accuracy in the fields. Unlike
     classical CF compression by means of {\tt scale\_factor} and
     {\tt add\_offset} attributes, internal GZIP compression
     requires no special handling by the users of the data. In fact,
     they do not even need to know that the data is compressed! At this
     point, MAPL\_CFIO does not activate this GZIP compression
     feature in the files being written, but the resulting precision
     degredaded files can be compressed offline with the HDF-4
     {\tt hrepack} utility.
#endif
!EOP
    character(len=*), parameter  :: Iam="MAPL_CFIOWriteState"
    integer                      :: STATUS
! Locals
    type(ESMF_FieldBundle) :: tBUNDLE
! Get the appropriate bundle
!---------------------------
!!ALT    if(present(STATE)) then
       tBUNDLE = ESMF_FieldBundleCreate ( name=Iam, rc=STATUS )
       _VERIFY(STATUS)
       call ESMFL_BundleAddState ( tBUNDLE, STATE, rc=STATUS, VALIDATE=.true. )
       _VERIFY(STATUS)
!!ALT    else
!!ALT       tBUNDLE = MCFIO%BUNDLE
!!ALT    end if
!   Write the Bundle
!   ----------------
    call MAPL_CFIOWriteBundle ( MCFIO, CLOCK=CLOCK, BUNDLE=tBUNDLE, &
                                VERBOSE=VERBOSE, NBITS=NBITS, RC=STATUS   )
    _VERIFY(STATUS)
!!ALT    if(present(STATE)) then
       call ESMF_FieldBundleDestroy ( tBUNDLE, rc=STATUS )
       _VERIFY(STATUS)
!!ALT    endif
!   All done
!   --------
    _RETURN(ESMF_SUCCESS)
 end subroutine MAPL_CFIOWriteState
Call graph
mapl_cfiowritestate calls esmf_fieldbundlecreate, mapl_cfiowritebundle, esmfl_bundleaddstate, mapl_verify, esmf_fieldbundledestroy, mapl_return
mapl_cfiowritebundle calls mapl_verify, mapl_return, mapl_assert, mapl_cfioset, mapl_cfiowritebundlepost, mapl_cfiowritebundlewait, mapl_cfiocreatewrite, mapl_cfiowritebundlewrite
esmfl_bundleaddstate calls bundleaddstate_
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
esmf_iowrite calls mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritestate
test_main calls esmf_iowrite
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
utcfio calls test_main
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2