MAPL_GenericConnCheck – MAPL
MAPL_GenericConnCheck Subroutine
40 statements
Source File
private recursive subroutine MAPL_GenericConnCheck(GC, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_GenericConnCheck
Source Code
   recursive subroutine MAPL_GenericConnCheck(GC, RC)
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)            :: IAm
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: STATE
      integer                                     :: I
      logical                                     :: err
      type (MAPL_Connectivity), pointer           :: conn
      type(ESMF_GridComp), pointer :: gridcomp
      !EOP
      ! Get my name and set-up traceback handle
      ! ---------------------------------------
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // 'MAPL_GenericConnCheck'
      ! Retrieve the pointer to the internal state
      ! --------------------------------------------
      call MAPL_InternalStateRetrieve ( GC, STATE, RC=status )
      _VERIFY(status)
      conn => state%connectList
      err = .false.
      if (.not. conn%connect%checkUnused()) then
         err = .true.
         CALL WRITE_PARALLEL("CONNECT ERRORS FOUND in " // trim(comp_name))
      end if
      if (.not. CONN%DONOTCONN%checkUnused()) then
         err = .true.
         CALL WRITE_PARALLEL("DO_NOT_CONNECT ERRORS FOUND in " // trim(comp_name))
      end if
      do I = 1, STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(I)
         call MAPL_GenericConnCheck(gridcomp, RC=status)
         if (status /= ESMF_SUCCESS) then
            err = .true.
         end if
      end do
      if (err) then
         _RETURN(ESMF_FAILURE)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericConnCheck
Call graph
mapl_genericconncheck calls mapl_genericconncheck, esmf_gridcompget, mapl_internalstateretrieve, mapl_return, mapl_verify, write_parallel
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
write_parallel calls write_parallel_i4_0, write_parallel_r4_1, write_parallel_i4_1, write_parallel_r8_0, write_parallel_r4_0, write_parallel_r8_1, write_parallel_string_0
mapl_internalstateget calls esmf_gridcompget, mapl_return, mapl_verify, esmf_usercompgetinternalstate
mapl_internalstatecreate calls esmf_gridcompget, mapl_return, mapl_verify, esmf_usercompsetinternalstate
write_parallel_i4_0 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert, dealloc_
mapl_throw_exception calls initialize
write_parallel_r4_1 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert, alloc_
write_parallel_i4_1 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert, alloc_
write_parallel_r8_0 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert, dealloc_
write_parallel_r4_0 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert, dealloc_
write_parallel_r8_1 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert, alloc_
write_parallel_string_0 calls mapl_return, mapl_verify, mpi_file_seek, mapl_am_i_root, mpi_file_write, mapl_assert
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
dealloc_ calls mapl_return, mapl_assert
alloc_ calls mapl_return, mapl_verify, mapl_assert, dealloc_