MAPL_StateAlarmAdd – MAPL
MAPL_StateAlarmAdd Subroutine
11 statements
Source File
public subroutine MAPL_StateAlarmAdd(STATE, ALARM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
type(ESMF_Alarm), intent(in) :: ALARM
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_StateAlarmAdd
Source Code
   subroutine MAPL_StateAlarmAdd(STATE,ALARM,RC)
      type (MAPL_MetaComp),        intent(INOUT) :: STATE
      type (ESMF_Alarm),           intent(IN   ) :: ALARM
      integer, optional,           intent(  OUT) :: RC     ! Error code
      character(len=ESMF_MAXSTR), parameter :: IAm = "MAPL_StateAlarmAdd"
      STATE%ALARMLAST = STATE%ALARMLAST + 1
      _ASSERT(STATE%ALARMLAST <= LAST_ALARM,'needs informative message')
      STATE%ALARM(STATE%ALARMLAST) = ALARM
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAlarmAdd
Call graph
mapl_statealarmadd calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message