MAPL_BundleRead – MAPL
MAPL_BundleRead Subroutine
51 statements
Source File
private subroutine MAPL_BundleRead(UNIT, BUNDLE, ARRDES, BOOTSTRAPABLE, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
type(ArrDescr), intent(inout), optional :: ARRDES
logical, intent(in), optional :: BOOTSTRAPABLE
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_BundleRead(UNIT,BUNDLE, ARRDES, BOOTSTRAPABLE, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_FieldBundle)     , intent(INOUT) :: BUNDLE
    type(ArrDescr),    optional , intent(INOUT) :: ARRDES
    logical,           optional , intent(IN   ) :: BOOTSTRAPABLE
    integer,           optional , intent(  OUT) :: RC
    integer                            :: status
    integer                            :: J, N, fieldCount
    type (ESMF_Field)                  :: field
    character(len=ESMF_MAXSTR),allocatable  :: nameList(:)
    character(len=ESMF_MAXSTR)              :: BundleName
    integer                            :: RST
    logical                            :: ignoreEOF
    logical                            :: skipReading
    logical                            :: bootstrapable_
    logical                            :: isPresent
    call ESMF_FieldBundleGet(bundle, fieldCount=N, name=BundleName, rc=STATUS)
    _VERIFY(STATUS)
    allocate(namelist(N), stat=status)
    _VERIFY(STATUS)
    call ESMF_FieldBundleGet(bundle, fieldNameList=nameList, fieldCount=FieldCount,  rc=STATUS)
    _VERIFY(STATUS)
    _ASSERT(N==fieldCount, 'inconsistent fieldCount')
    if (present(bootstrapable)) then
       bootstrapable_ = bootstrapable
    else
       bootstrapable_ = .false.
    end if
    do J = 1, N
       call MAPL_FieldBundleGet(bundle, fieldIndex=J, field=field, rc=status)
       _VERIFY(STATUS)
       call ESMF_AttributeGet(field, name='RESTART', isPresent=isPresent, rc=status)
       _VERIFY(STATUS)
       if (isPresent) then
          call ESMF_AttributeGet(field, name='RESTART', value=RST, rc=status)
          _VERIFY(STATUS)
       else
          RST = MAPL_RestartOptional
       end if
       skipReading = (RST == MAPL_RestartSkip)
       if (skipReading) cycle
       ignoreEOF=.false.
       if (bootstrapable_ .and. (RST == MAPL_RestartOptional)) then
          ignoreEOF = .true.
       end if
       call MAPL_FieldRead(unit, field, arrdes=ARRDES,  ignoreEOF=ignoreEOF, rc=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_BundleRead
Call graph
mapl_bundleread calls ESMF_AttributeGet, esmf_fieldbundleget, mapl_assert, mapl_fieldbundleget, mapl_fieldread, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldbundleget calls mapl_fieldbundlegetbyindex
mapl_fieldread calls ESMF_AttributeGet, mapl_assert, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, esmf_arrayget, esmf_fieldget, mapl_am_i_root, mapl_commsbcast, mapl_deallocnodearray, mapl_syncsharedmemory, mapl_varread, read_parallel, mapl_backspace, mapl_tilemaskget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_varread calls mapl_bundleread, mapl_statevarread, mapl_fieldread, mapl_varread_r4_2d, mapl_varread_r4_3d, mapl_varread_r4_4d, mapl_varread_r8_2d, mapl_varread_r8_3d, mapl_varread_r8_4d
mapl_statevarread calls mapl_bundleread, mapl_fieldread
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_readforcingx calls mapl_varread
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
readrestart calls mapl_varread
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore