MAPL_FieldBundleDestroy – MAPL
MAPL_FieldBundleDestroy Module Subroutine
24 statements
Source File
module subroutine MAPL_FieldBundleDestroy(Bundle, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  module subroutine MAPL_FieldBundleDestroy(Bundle,RC)
    type(ESMF_FieldBundle),    intent(INOUT) :: Bundle
    integer, optional,         intent(OUT  ) :: RC
    integer                               :: I
    integer                               :: FieldCount
    type(ESMF_Field)                      :: Field
    logical                               :: isCreated
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_FieldBundleDestroy"
    integer                               :: STATUS
    isCreated = ESMF_FieldBundleIsCreated(bundle,_RC)
    if(isCreated) then
       call ESMF_FieldBundleGet(BUNDLE, FieldCount=FIELDCOUNT, _RC)
       do I = 1, FIELDCOUNT
          call ESMF_FieldBundleGet(BUNDLE, I, FIELD, _RC)
          call MAPL_FieldDestroy(FIELD, _RC)
       end do
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldBundleDestroy
Call graph
mapl_fieldbundledestroy calls esmf_fieldbundleget, esmf_fieldbundleiscreated, mapl_fielddestroy, mapl_return, mapl_verify, mapl_fieldbundledestroy
mapl_fielddestroy calls destroy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
destroy calls mapl_return, mapl_verify, esmf_fielddestroy, esmf_fieldget, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
createfilemetadata calls mapl_fieldbundledestroy
mapl_simplebundledestroy calls mapl_fieldbundledestroy
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle