MAPL_FriendlyGet – MAPL
MAPL_FriendlyGet Subroutine
32 statements
Source File
public subroutine MAPL_FriendlyGet(GC, NAME, FIELD, REQUESTER, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: NAME
type(ESMF_Field), intent(out) :: FIELD
character(len=*), intent(in), optional :: REQUESTER
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_FriendlyGet
Source Code
   subroutine MAPL_FriendlyGet ( GC, NAME, FIELD, REQUESTER, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      character(len=*),              intent(IN   )  :: NAME
      character(len=*),    optional, intent(IN   )  :: REQUESTER !ALT (set to optional TEMPORARY)
      type(ESMF_Field),              intent(  OUT)  :: FIELD
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      integer                               :: status
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: STATE
      logical                                     :: FRIENDLY
      integer                                     :: N, STAT
      ! Retrieve the pointer to the internal state of Root.
      ! ----------------------------------------------------
      call MAPL_InternalStateRetrieve ( GC, STATE, RC=status )
      _VERIFY(status)
      N =  MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS, NAME, RC=status)
      if(N /= -1) then
         _VERIFY(status)
      else
         _RETURN(ESMF_FAILURE)
      endif
      call MAPL_VarSpecGet(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS(N), STAT=STAT, RC=status)
      _VERIFY(status)
      _ASSERT(iand(STAT, MAPL_FriendlyVariable) /= 0,'needs informative message')
      call ESMF_StateGet(STATE%get_internal_state(), NAME, FIELD, RC=status)
      _VERIFY(status)
      if (present(REQUESTER)) then
         call ESMF_AttributeGet  (FIELD, NAME="FriendlyTo"//trim(REQUESTER),VALUE=FRIENDLY, RC=status)
         _VERIFY(status)
         _ASSERT(FRIENDLY,'needs informative message')
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_FriendlyGet
Call graph
mapl_friendlyget calls ESMF_AttributeGet, esmf_stateget, get_internal_state, mapl_assert, mapl_varspecget, mapl_varspecgetindex, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
initialize calls initialize_global_time_profiler