MAPL_GetGlobalHorzIJIndex – MAPL
MAPL_GetGlobalHorzIJIndex Module Subroutine
134 statements
Source File
module subroutine MAPL_GetGlobalHorzIJIndex(npts, II, JJ, lon, lat, lonR8, latR8, Grid, rc) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npts
integer, intent(inout) :: II(npts)
integer, intent(inout) :: JJ(npts)
real, intent(in), optional :: lon(npts)
real, intent(in), optional :: lat(npts)
real(kind=ESMF_KIND_R8), intent(in), optional :: lonR8(npts)
real(kind=ESMF_KIND_R8), intent(in), optional :: latR8(npts)
type(ESMF_Grid), intent(inout), optional :: Grid
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  module subroutine MAPL_GetGlobalHorzIJIndex(npts,II,JJ,lon,lat,lonR8,latR8,Grid, rc)
    implicit none
    !ARGUMENTS:
    integer,                      intent(in   ) :: npts ! number of points in lat and lon arrays
    integer,                      intent(inout) :: II(npts) ! array of the first index for each lat and lon
    integer,                      intent(inout) :: JJ(npts) ! array of the second index for each lat and lon
    real, optional,               intent(in   ) :: lon(npts) ! array of longitudes in radians
    real, optional,               intent(in   ) :: lat(npts) ! array of latitudes in radians
    real(ESMF_KIND_R8), optional, intent(in   ) :: lonR8(npts) ! array of longitudes in radians
    real(ESMF_KIND_R8), optional, intent(in   ) :: latR8(npts) ! array of latitudes in radians
    type(ESMF_Grid),    optional, intent(inout) :: Grid ! ESMF grid
    integer,            optional, intent(out  ) :: rc  ! return code
    integer :: status
    integer :: dims(3), IM_WORLD, JM_WORLD
    real(ESMF_KIND_R8), allocatable, dimension (:,:) :: xyz
    real(ESMF_KIND_R8), allocatable, dimension (:)   :: x,y,z
    real(ESMF_KIND_R8), allocatable :: max_abs(:)
    real(ESMF_KIND_R8)              :: dalpha, shift0
    real(ESMF_KIND_R8), allocatable :: lons(:), lats(:)
    ! sqrt(2.0d0), distance from center to the mid of an edge for a 2x2x2 cube
    real(ESMF_KIND_R8), parameter :: sqr2 = 1.41421356237310d0
    ! asin(1.d0/sqrt(3.d0)),  angle between the two lines(center to the mid and center to the end of an edge)
    real(ESMF_KIND_R8), parameter :: alpha= 0.615479708670387d0
    ! MAPL_PI_R8/18, Japan Fuji mountain shift
    real(ESMF_KIND_R8), parameter :: shift= 0.174532925199433d0
    logical :: good_grid, stretched
    ! Return if no local points
    _RETURN_IF(npts == 0)
    if ( .not. present(grid)) then
      _FAIL("need a cubed-sphere grid")
    endif
    call MAPL_GridGet(grid, globalCellCountPerDim=dims,_RC)
    IM_World = dims(1)
    JM_World = dims(2)
    _ASSERT( IM_WORLD*6 == JM_WORLD, "It only works for cubed-sphere grid")
    allocate(lons(npts),lats(npts))
    call MAPL_Reverse_Schmidt(Grid, stretched, npts, lon=lon, lat=lat, lonR8=lonR8, latR8=latR8, lonRe=lons, latRe=lats, _RC)
    dalpha = 2.0d0*alpha/IM_WORLD
    ! make sure the grid can be used in this subroutine
    good_grid = grid_is_ok(grid)
    if ( .not. good_grid ) then
       _FAIL( "MAPL_GetGlobalHorzIJIndex cannot handle this grid")
    endif
    ! shift the grid away from Japan Fuji Mt.
    shift0 = shift
    if (stretched) shift0 = 0
    lons = lons + shift0
    ! get xyz from sphere surface
    allocate(xyz(3, npts), max_abs(npts))
    xyz(1,:) = cos(lats)*cos(lons)
    xyz(2,:) = cos(lats)*sin(lons)
    xyz(3,:) = sin(lats)
    ! project onto 2x2x2 cube
    max_abs = maxval(abs(xyz), dim=1)
    xyz(1,:) = xyz(1,:)/max_abs
    xyz(2,:) = xyz(2,:)/max_abs
    xyz(3,:) = xyz(3,:)/max_abs
    x = xyz(1,:)
    y = xyz(2,:)
    z = xyz(3,:)
    II = -1
    JJ = -1
    ! The edge points are assigned in the order of face 1,2,3,4,5,6
    call calculate(x,y,z,II,JJ)
    _RETURN(_SUCCESS)
contains
    elemental subroutine calculate(x, y, z, i, j)
       real(ESMF_KIND_R8), intent(in) :: x
       real(ESMF_KIND_R8), intent(in) :: y
       real(ESMF_KIND_R8), intent(in) :: z
       integer, intent(out) :: i, j
       real :: tolerance
       tolerance = epsilon(1.0d0)
       ! face = 1
       if   ( abs(x-1.0d0) <= tolerance) then
         call angle_to_index(y, z, i, j)
       ! face = 2
       elseif (abs(y-1.0d0) <= tolerance) then
         call angle_to_index(-x,  z, i, j)
         J = J + IM_WORLD
       ! face = 3
       elseif (abs(z-1.0d0) <= tolerance) then
         call angle_to_index(-x, -y, i, j)
         J = J + IM_WORLD*2
       ! face = 4
       elseif (abs(x+1.0d0) <= tolerance) then
         call angle_to_index(-z, -y, i, j)
         J = J + IM_WORLD*3
       ! face = 5
       elseif (abs(y+1.0d0) <= tolerance) then
         call angle_to_index(-z,  x, i, j)
         J = J + IM_WORLD*4
       ! face = 6
       elseif (abs(z+1.0d0) <= tolerance) then
         call angle_to_index( y,  x, i, j)
         J = J + IM_WORLD*5
       endif
       if (I == 0 ) I = 1
       if (I == IM_WORLD+1 ) I = IM_WORLD
    end subroutine calculate
    elemental subroutine angle_to_index(xval, yval, i, j)
       real(ESMF_KIND_R8), intent(in) :: xval
       real(ESMF_KIND_R8), intent(in) :: yval
       integer, intent(out) :: i, j
       I = ceiling((atan(xval/sqr2) + alpha)/dalpha)
       J = ceiling((atan(yval/sqr2) + alpha)/dalpha)
       if (j == 0 ) J = 1
       if (j == IM_WORLD+1) j = IM_WORLD
    end subroutine angle_to_index
    function grid_is_ok(grid) result(OK)
       type(ESMF_Grid), intent(inout) :: grid
       logical :: OK
       integer :: I1, I2, J1, J2, j
       real(ESMF_KIND_R8), pointer :: corner_lons(:,:), corner_lats(:,:)
       real(ESMF_KIND_R8), allocatable :: lonRe(:), latRe(:)
       real(ESMF_KIND_R8), allocatable :: accurate_lat(:), accurate_lon(:)
       real(ESMF_KIND_R8) :: stretch_factor, target_lon, target_lat, shift0
       real :: tolerance
       tolerance = epsilon(1.0)
       call MAPL_GridGetInterior(grid,I1,I2,J1,J2)
       OK = .true.
       ! check the edge of face 1 along longitude
       call ESMF_GridGetCoord(grid,localDE=0,coordDim=1,staggerloc=ESMF_STAGGERLOC_CORNER, &
            farrayPtr=corner_lons, rc=status)
       call ESMF_GridGetCoord(grid,localDE=0,coordDim=2,staggerloc=ESMF_STAGGERLOC_CORNER, &
            farrayPtr=corner_lats, rc=status)
       if ( I1 == 1 .and. J1 == 1 ) then
          allocate(lonRe(j2-j1+1),      latRe(j2-j1+1))
          call MAPL_Reverse_Schmidt(grid, stretched, J2-J1+1, lonR8=corner_lons(1,:), &
                                   latR8=corner_lats(1,:), lonRe=lonRe, latRe=latRe, _RC)
          allocate(accurate_lon(j2-j1+1), accurate_lat(j2-j1+1))
          shift0 = shift
          if (stretched) shift0 = 0
          accurate_lon = 1.750d0*MAPL_PI_R8 - shift0
          accurate_lat = [(-alpha + (j-1)*dalpha, j = j1, j2)]
          if (any(abs(accurate_lon - lonRe) > 2.0* tolerance) .or. any(abs(accurate_lat - latRe) > 2.0*tolerance)) then
             print*, "Error: It could be "
             print*, "  1) grid may not have pi/18 Japan mountain shift"
             print*, "  2) grid is NOT gnomonic_ed;"
             print*, "  3) lats lons from MAPL_GridGetCorners are NOT accurate (single precision from ESMF)"
             print*, "  4) strtech grid rotates north pole"
             OK = .false.
             return
          endif
        endif
    end function
  end subroutine MAPL_GetGlobalHorzIJIndex
Call graph
mapl_getglobalhorzijindex calls ESMF_GridGetCoord, mapl_assert, mapl_gridgetinterior, mapl_reverse_schmidt, mapl_gridget, mapl_return, mapl_verify, mapl_getglobalhorzijindex
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridgetinterior calls mapl_gridgetinterior, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, ESMF_DELayoutGet, ESMF_VMGet
mapl_reverse_schmidt calls mapl_reverse_schmidt, mapl_assert, mapl_return, mapl_verify, ESMF_AttributeGet
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_GridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
mapl_gethorzijindex calls mapl_getglobalhorzijindex, mapl_gethorzijindex
create_geosat_grid_find_mask calls mapl_gethorzijindex