MAPL_set_throw_method – MAPL
MAPL_set_throw_method Subroutine
5 statements
Source File
public subroutine MAPL_set_throw_method(method)
Arguments
Type Intent Optional Attributes Name
procedure(throw) :: method
Calls
Called by
Contents
Source Code
MAPL_set_throw_method
Source Code
   subroutine MAPL_set_throw_method(method)
      procedure (throw) :: method
      if (.not. initialized) call initialize()
      throw_method => method
   end subroutine MAPL_set_throw_method
Call graph
mapl_set_throw_method calls initialize
init_tests calls mapl_set_throw_method
initialize calls mapl_set_throw_method