MAPL_GetClimMonths – MAPL
MAPL_GetClimMonths Subroutine
26 statements
Source File
private subroutine MAPL_GetClimMonths(CURRENT_TIME, BEFORE, AFTER, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: CURRENT_TIME
type(ESMF_Time), intent(out) :: BEFORE
type(ESMF_Time), intent(out) :: AFTER
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GetClimMonths
Source Code
    subroutine MAPL_GetClimMonths ( CURRENT_TIME, BEFORE, AFTER, RC )
        type(ESMF_Time), intent(inout) :: CURRENT_TIME !ALT: intent(in)
        type(ESMF_Time), intent(out) :: BEFORE, AFTER
        integer,optional,intent(out) :: RC
        integer :: STATUS
        integer                 :: MonthCurr
        type(ESMF_Time        ) :: midMonth
        type(ESMF_TimeInterval) :: oneMonth
        call ESMF_TimeIntervalSet(oneMonth, MM = 1, RC=STATUS )
        _VERIFY(STATUS)
        call ESMF_TimeGet(CURRENT_TIME, midMonth=midMonth, mm=MonthCurr, RC=STATUS )
        _VERIFY(STATUS)
        if( CURRENT_TIME < midMonth ) then
           AFTER    = midMonth
           midMonth = midMonth - oneMonth
           call ESMF_TimeGet (midMonth, midMonth=BEFORE, rc=STATUS )
           _VERIFY(STATUS)
        else
           BEFORE   = midMonth
           midMonth = midMonth + oneMonth
           call ESMF_TimeGet (midMonth, midMonth=AFTER , rc=STATUS )
           _VERIFY(STATUS)
        endif
        _RETURN(ESMF_SUCCESS)
    end subroutine MAPL_GetClimMonths
Call graph
mapl_getclimmonths calls ESMF_TimeGet, ESMF_TimeIntervalSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_climupdate calls mapl_getclimmonths