MAPL_ReadForcing1 – MAPL
MAPL_ReadForcing1 Subroutine
14 statements
Source File
private subroutine MAPL_ReadForcing1(STATE, NAME, DATAFILE, CURRENTTIME, FORCING, INIT_ONLY, ON_TILES, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: DATAFILE
type(ESMF_Time), intent(inout) :: CURRENTTIME
real, intent(out) :: FORCING(:)
logical, intent(in), optional :: INIT_ONLY
logical, intent(in), optional :: ON_TILES
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_ReadForcing1
Source Code
   subroutine MAPL_ReadForcing1(STATE,NAME,DATAFILE,CURRENTTIME,    &
        FORCING,INIT_ONLY,ON_TILES,RC )
      !ARGUMENTS:
      type (MAPL_MetaComp),     intent(INOUT)   :: STATE
      character(len=*),         intent(IN   )   :: NAME
      character(len=*),         intent(IN   )   :: DATAFILE
      type (ESMF_Time),         intent(INout)   :: CURRENTTIME
      real,                     intent(  OUT)   :: FORCING(:)
      logical, optional,        intent(IN   )   :: INIT_ONLY
      logical, optional,        intent(IN   )   :: ON_TILES
      integer, optional,        intent(  OUT)   :: RC
      !EOPI
      integer                           :: status
      call MAPL_ReadForcingX(STATE,NAME,DATAFILE,CURRENTTIME,      &
           FORCING1=FORCING,INIT_ONLY=INIT_ONLY, &
           ON_TILES=ON_TILES,                    &
           RC=status )
      _RETURN(status)
   end subroutine MAPL_ReadForcing1
Call graph
mapl_readforcing1 calls mapl_readforcingx, mapl_return
mapl_readforcingx calls mapl_return, mapl_interp_fac, mapl_stategettimestamp, mapl_verify, mapl_backspace, mapl_assert, esmf_stateget, esmf_timeget, mapl_varspeccreateinlistnew, mapl_statecreatefromvarspecnew, mapl_getnumsubtiles, read_parallel, mapl_am_i_root, getfile, mapl_stategetspecattrib, mapl_locstreamget, mapl_varspecgetindex, esmfl_stategetpointertodata, esmf_timeset, mapl_genericstateget
mapl_return calls mapl_throw_exception, get_error_message
mapl_readforcing calls mapl_readforcing1