MAPL_ConfigSetAttribute_reals32 – MAPL
MAPL_ConfigSetAttribute_reals32 Subroutine
25 statements
Source File
private subroutine MAPL_ConfigSetAttribute_reals32(config, value, label, rc)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
real(kind=REAL32), intent(in) :: value(:)
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ConfigSetAttribute_reals32
Source Code
   subroutine MAPL_ConfigSetAttribute_reals32( config, value, label, rc )
     use, intrinsic :: iso_fortran_env, only: REAL32
! !ARGUMENTS:
     type(ESMF_Config), intent(inout)             :: config
     real(kind=REAL32), intent(in)                :: value(:)
     character(len=*), intent(in), optional       :: label
     integer, intent(out), optional               :: rc
! BOPI -------------------------------------------------------------------
!
! !IROUTINE: MAPL_ConfigSetAttribute - Set an array of 4-byte real numbers
     ! This uses existing overload of MAPL_ConfogSetAttribute for vector of
     ! character strings. This limits the number of reals to about 92
!
! !INTERFACE:
      ! Private name; call using MAPL_ConfigSetAttribute()
     ! The next variable, IWSZ, is used for sizing a buffer for internal write
     ! The value varies between different compilers
     ! 15 is big enough for Intel
     ! 16 is good for NAG and Portland Group
     ! 18 is needed for gfortran
     ! Hopefully 32 is large enough to fit-all.
#define IWSZ 32
     integer,   parameter :: LSZ = max (1024,ESMF_MAXPATHLEN)  ! Maximum line size
     character(len=LSZ) :: buffer
     character(len=IWSZ) :: tmpStr, newVal
     integer :: count, i, j
     integer :: status
     count = size(value)
     buffer = '' ! initialize to
     do i = 1, count
        j = len_trim(buffer)
        write(tmpStr, *) value(i) ! ALT: check if enough space to write
        newVal = adjustl(tmpStr)
        _ASSERT(j + len_trim(newVal) <= LSZ,'not enough space to write')
        write(buffer(j+1:), *) trim(newVal)
     end do
     call MAPL_ConfigSetAttribute(config, value=buffer, label=label, _RC)
     _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ConfigSetAttribute_reals32
Call graph
mapl_configsetattribute_reals32 calls mapl_assert, mapl_return, mapl_configsetattribute, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_configsetattribute calls mapl_configsetattribute_reals32, mapl_configsetattribute_real32, mapl_configsetattribute_int32, mapl_configsetattribute_real64, mapl_configsetattribute_ints32, mapl_configsetattribute_string
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_configsetattribute_real32 calls mapl_return, esmf_configgetattribute
mapl_configsetattribute_int32 calls mapl_return, esmf_configgetattribute
mapl_configsetattribute_real64 calls mapl_return, esmf_configgetattribute
mapl_configsetattribute_ints32 calls mapl_assert, mapl_return, mapl_configsetattribute, mapl_verify
mapl_configsetattribute_string calls mapl_return, esmf_configgetattribute
create_cf calls mapl_configsetattribute
create_output_grid calls mapl_configsetattribute
initialize_from_esmf_distgrid calls mapl_configsetattribute
initialize calls mapl_configsetattribute
initialize_gc calls mapl_configsetattribute
addgrid calls mapl_configsetattribute
mapl_extdatagridchangelev calls mapl_configsetattribute
mapl_gridcreate calls mapl_configsetattribute
test_setattribute_string calls mapl_configsetattribute
create_grid calls create_cf
initialize_ calls mapl_gridcreate, createfilelevbracket
time_ave calls create_output_grid
createfilelevbracket calls mapl_extdatagridchangelev
my_initialize calls mapl_gridcreate
ut_regridding calls create_cf
create_bracketing_fields calls createfilelevbracket