MAPL_StateAddImportSpecFrmChld – MAPL
MAPL_StateAddImportSpecFrmChld Subroutine
33 statements
Source File
private subroutine MAPL_StateAddImportSpecFrmChld(STATE, SHORT_NAME, CHILD_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: CHILD_ID
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateAddImportSpecFrmChld
Source Code
   subroutine MAPL_StateAddImportSpecFrmChld ( STATE, SHORT_NAME, CHILD_ID, RC )
      !ARGUMENTS:
      type (MAPL_MetaComp)            , intent(INOUT)   :: STATE
      character (len=*)               , intent(IN)      :: SHORT_NAME
      integer                         , intent(IN)      :: CHILD_ID
      integer            , optional   , intent(OUT)     :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddImportSpecFrmChld"
      integer                               :: status
      type (MAPL_VarSpec),      pointer     :: SPECS(:)
      integer                               :: I
      type(ESMF_GridComp), pointer :: gridcomp
      if (.not. STATE%get_num_children() > 0) then
         _RETURN(ESMF_FAILURE)
      end if
      gridcomp => STATE%GET_CHILD_GRIDCOMP(CHILD_ID)
      call MAPL_GridCompGetVarSpecs(gridcomp, IMPORT=SPECS, RC=status)
      _VERIFY(status)
      I=MAPL_VarSpecGetIndex(SPECS, SHORT_NAME, RC=status)
      if (I == -1) then
         _RETURN(ESMF_FAILURE)
      endif
      _VERIFY(status)
      call MAPL_VarSpecAddRefToList(STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS, SPECS(I), RC=status)
      if (status /= MAPL_DuplicateEntry) then
         _VERIFY(status)
      else
         _RETURN(ESMF_FAILURE) ! ALT this needs to be revisited
      endif
      !ALT: is reconnect needed
      !    call MAPL_AddConnectivity ( STATE, SHORT_NAME=SHORT_NAME, &
      !       FROM_IMPORT=CHILD_ID, TO_IMPORT=MAPL_Self, RC=status  )
      !    _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddImportSpecFrmChld
Call graph
mapl_stateaddimportspecfrmchld calls mapl_return, mapl_gridcompgetvarspecs, mapl_varspecgetindex, mapl_verify, mapl_varspecaddreftolist
mapl_return calls get_error_message, mapl_throw_exception
mapl_gridcompgetvarspecs calls mapl_return, mapl_verify, mapl_internalstateretrieve, esmf_gridcompget, mapl_stategetvarspecs
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_verify calls mapl_throw_exception
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_stategetvarspecs calls mapl_return
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecaddreffromitem calls mapl_return, mapl_varspecgetindex, mapl_verify, mapl_varspecprint
mapl_varspecaddreffromlist calls mapl_return, mapl_verify, mapl_varspecaddreffromitem
mapl_internalstateget calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
mapl_internalstatecreate calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompsetinternalstate
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
setservices calls mapl_addimportspec, setservices
addnewspec calls mapl_addimportspec