MAPL_VarWrite_R4_3d – MAPL
MAPL_VarWrite_R4_3d Subroutine
15 statements
Source File
private subroutine MAPL_VarWrite_R4_3d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R4), intent(in) :: A(:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_VarWrite_R4_3d(UNIT, GRID, A, ARRDES, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_Grid)            , intent(INout) :: GRID
    real(kind=ESMF_KIND_R4)     , intent(IN   ) :: A(:,:,:)
    type(ArrDescr),     optional, intent(INOUT) :: ARRDES
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer                               :: status
    integer :: L
    do L = 1, size(A,3)
       call MAPL_VarWrite(UNIT, GRID, A(:,:,L), ARRDES=ARRDES, rc=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarWrite_R4_3d
Call graph
mapl_varwrite_r4_3d calls mapl_varwrite, mapl_return, mapl_verify
mapl_varwrite calls mapl_varwrite_r4_3d, mapl_bundlewrite, mapl_fieldwrite, mapl_statevarwrite, mapl_varwrite_i4_1d, mapl_varwrite_r4_1d, mapl_varwrite_r4_2d, mapl_varwrite_r4_4d, mapl_varwrite_r8_1d, mapl_varwrite_r8_2d, mapl_varwrite_r8_3d, mapl_varwrite_r8_4d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_esmfstatewritetofile calls mapl_varwrite
mapl_fieldwrite calls mapl_varwrite
mapl_varwrite_r4_2d calls mapl_varwrite
mapl_varwrite_r4_4d calls mapl_varwrite
mapl_varwrite_r8_2d calls mapl_varwrite
mapl_varwrite_r8_3d calls mapl_varwrite
mapl_varwrite_r8_4d calls mapl_varwrite
run calls mapl_varwrite
writerestart calls mapl_varwrite
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_bundlewrite calls mapl_fieldwrite
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_statevarwrite calls mapl_fieldwrite, mapl_bundlewrite
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave