MAPL_AreaMean_2d_r8 – MAPL
MAPL_AreaMean_2d_r8 Subroutine
37 statements
Source File
private subroutine MAPL_AreaMean_2d_r8(qave, q, area, grid, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(out) :: qave
real, intent(in) :: q(:,:)
real, intent(in) :: area(:,:)
type(ESMF_Grid), intent(inout) :: grid
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_AreaMean_2d_r8
Source Code
  subroutine MAPL_AreaMean_2d_r8 ( qave, q, area, grid, rc )
    implicit none
    ! Arguments
    real(kind=REAL64), intent(  OUT) :: qave
    real,              intent(IN   ) :: q(:,:)
    real,              intent(IN   ) :: area(:,:)
    type(ESMF_Grid),   intent(INout) :: grid
    integer, optional, intent(  OUT) :: rc
    ! Log err vars
    integer :: status
    character(len=ESMF_MAXSTR), parameter :: Iam='MAPL_AreaMean'
    ! Local vars
    real(kind=REAL64)  :: qdum(2)
    real(kind=REAL64)  :: qdumloc(2)
    integer :: im,jm
    integer :: i,j
    type(ESMF_VM) :: vm
    _UNUSED_DUMMY(grid)
    ! get VM (should get from the grid, but this is quicker)
    call ESMF_VmGetCurrent(vm, rc=status)
    _VERIFY(STATUS)
    im = size(area,1) ! local grid dim
    jm = size(area,2) ! local grid dim
    ! do calculation on every PE
    ! compute local sum
    qdumloc = 0.0d+0
    do j=1,jm
       do i=1,im
          if (q(i,j) == MAPL_Undef) cycle ! exclude any undefs
          qdumloc(1) = qdumloc(1) + q(i,j)*area(i,j)
          qdumloc(2) = qdumloc(2) + area(i,j)
       enddo
    end do
    call MAPL_CommsAllReduceSum(vm, sendbuf=qdumloc, recvbuf=qdum, &
         cnt=2, RC=status)
    _VERIFY(STATUS)
    if (qdum(2) /= 0.0d+0) then
       qave = qdum(1) / qdum(2)
       !ALT: convert the the result to single precision to get rid of
       !     numerical non-associativity in floating point numbers
       !     qave = real(qave, kind=4)
    else
       qave = MAPL_Undef
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_AreaMean_2d_r8
Call graph
mapl_areamean_2d_r8 calls esmf_vmgetcurrent, mapl_verify, mapl_commsallreducesum, mapl_return
mapl_verify calls mapl_throw_exception
mapl_commsallreducesum calls mapl_commsallreducesum_r8_0, mapl_commsallreducesum_i4_1, mapl_commsallreducesum_r4_1, mapl_commsallreducesum_i4_0, mapl_commsallreducesum_r4_0, mapl_commsallreducesum_r8_1, mapl_commsallreducesum_i4_2, mapl_commsallreducesum_r4_2, mapl_commsallreducesum_r8_2
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_commsallreducesum_r8_0 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_i4_1 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_r4_1 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_i4_0 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_r4_0 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_r8_1 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_i4_2 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_r4_2 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_commsallreducesum_r8_2 calls mapl_verify, mapl_return, esmf_vmget, mpi_allreduce
mapl_areamean calls mapl_areamean_2d_r8, mapl_areamean_2d_r8_bitrep
mapl_areamean_2d_r8_bitrep calls mapl_areamean