MAPL_SetPointer2DR4 – MAPL
MAPL_SetPointer2DR4 Module Subroutine
51 statements
Source File
module subroutine MAPL_SetPointer2DR4(state, ptr, name, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
real, pointer :: ptr(:,:)
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_SetPointer2DR4
Source Code
  module subroutine MAPL_SetPointer2DR4(state, ptr, name, rc)
    type(ESMF_State),               intent(INOUT) :: state
    real,                           pointer       :: ptr(:,:)
    character(len=*),               intent(IN   ) :: name
    integer,              optional, intent(  OUT) :: rc
    integer                               :: status
    character(len=ESMF_MAXSTR), parameter :: IAm='MAPL_SetPointer2DR4'
    type(ESMF_Field)                      :: field
    type(ESMF_FieldBundle)                :: bundle
    type(ESMF_Grid)                       :: GRID
    integer                               :: COUNTS(ESMF_MAXDIM)
    integer                               :: gridRank
    integer                               :: I
    integer                               :: loc
    integer, allocatable                  :: gridToFieldMap(:)
    type(ESMF_FieldStatus_Flag)           :: fieldStatus
    _ASSERT(associated(ptr), 'unassociated pointer')
    ! Get Field from state
    loc = index(name,';;')
    if(loc/=0) then
       call ESMF_StateGet(state, name(:loc-1), Bundle, rc=status)
       _VERIFY(STATUS)
       call ESMF_StateGet(state, name(loc+2:), Field, rc=status)
       _VERIFY(STATUS)
    else
       call ESMF_StateGet(state, name, Field, rc=status)
       _VERIFY(STATUS)
    end if
    call ESMF_FieldGet(field, status=fieldStatus, rc=status)
    _VERIFY(STATUS)
    _ASSERT(fieldStatus /= ESMF_FIELDSTATUS_COMPLETE, 'fieldStatus == ESMF_FIELDSTATUS_COMPLETE')
    call ESMF_FieldGet(field, grid=GRID, RC=STATUS)
    _VERIFY(STATUS)
    call MAPL_GridGet(GRID, localCellCountPerDim=COUNTS, RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(size(ptr,1) == COUNTS(1), 'shape mismatch dim=1')
    _ASSERT(size(ptr,2) == COUNTS(2), 'shape mismatch dim=2')
    call ESMF_GridGet(GRID, dimCount=gridRank, rc=status)
    _VERIFY(STATUS)
    ! MAPL restriction (actually only the first 2 dims are distributted)
    _ASSERT(gridRank <= 3, 'gridRank > 3 not supported')
    allocate(gridToFieldMap(gridRank), stat=status)
    _VERIFY(STATUS)
    do I = 1, gridRank
       gridToFieldMap(I) = I
    end do
    ! this is 2d case
    if (gridRank == 3) gridToFieldMap(3) = 0
    call ESMF_FieldEmptyComplete(FIELD, farrayPtr=ptr, &
         datacopyFlag = ESMF_DATACOPY_REFERENCE,       &
         gridToFieldMap=gridToFieldMap,                &
         rc = status)
    _VERIFY(STATUS)
    ! Clean up
    deallocate(gridToFieldMap)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_SetPointer2DR4
Call graph
mapl_setpointer2dr4 calls ESMF_GridGet, esmf_fieldemptycomplete, esmf_fieldget, esmf_stateget, mapl_assert, mapl_gridget, mapl_return, mapl_verify, mapl_setpointer2dr4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
mapl_setpointer calls mapl_setpointer2dr4