MAPL_FieldCreateRename – MAPL
MAPL_FieldCreateRename Module Function
111 statements
Source File
module function MAPL_FieldCreateRename(FIELD, NAME, DoCopy, RC) result(F) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: DoCopy
integer, intent(out), optional :: RC
Return Value type(ESMF_Field)
Calls
Called by
Source Code
  module function MAPL_FieldCreateRename(FIELD, NAME, DoCopy, RC) RESULT(F)
    type (ESMF_Field), intent(INOUT) :: FIELD !ALT: IN
    character(len=*),  intent(IN   ) :: NAME
    logical, optional, intent(IN   ) :: DoCopy
    integer, optional, intent(  OUT) :: RC
    type (ESMF_Field)                :: F
    !   we are creating new field so that we can change the name of the field;
    !   the important thing is that the data (ESMF_Array) and the grid (ESMF_Grid)
    !   are the SAME as the one in the original Field, if DoCopy flag is present
    !   and set to true we create a new array and copy the data, not just reference it
    type(ESMF_Grid)         :: grid
    character(len=ESMF_MAXSTR)       :: fieldName
    integer, allocatable    :: gridToFieldMap(:)
    integer                 :: gridRank
    integer                 :: fieldRank
    integer                 :: status
    integer                 :: unGridDims
    character(len=ESMF_MAXSTR), parameter :: Iam='MAPL_FieldCreateRename'
    logical                 :: hasUngridDims
    integer                 :: notGridded
    logical                 :: DoCopy_
    type(ESMF_DataCopy_Flag):: datacopy
    real, pointer           :: var_1d(:)
    real, pointer           :: var_2d(:,:)
    real, pointer           :: var_3d(:,:,:)
    real, pointer           :: var_4d(:,:,:,:)
    real(kind=REAL64), pointer           :: vr8_1d(:)
    real(kind=REAL64), pointer           :: vr8_2d(:,:)
    real(kind=REAL64), pointer           :: vr8_3d(:,:,:)
    real(kind=REAL64), pointer           :: vr8_4d(:,:,:,:)
    type(ESMF_TypeKind_Flag)  :: tk
    DoCopy_ = .false.
    if (present(DoCopy) ) then
       DoCopy_ = DoCopy
    end if
    call ESMF_FieldGet(FIELD, grid=GRID, dimCount=fieldRank, &
         name=fieldName, RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_GridGet(GRID, dimCount=gridRank, rc=status)
    _VERIFY(STATUS)
    allocate(gridToFieldMap(gridRank), stat=status)
    _VERIFY(STATUS)
    call ESMF_FieldGet(FIELD, gridToFieldMap=gridToFieldMap, typekind=tk, RC=STATUS)
    _VERIFY(STATUS)
    hasUngridDims = .false.
    notGridded = count(gridToFieldMap==0)
    unGridDims = fieldRank - gridRank + notGridded
    if (unGridDims > 0) then
       hasUngridDims = .true.
    endif
    if (doCopy_) then
       datacopy = ESMF_DATACOPY_VALUE
    else
       datacopy = ESMF_DATACOPY_REFERENCE
    end if
    f = MAPL_FieldCreateEmpty(name=NAME, grid=grid, rc=status)
    _VERIFY(STATUS)
    if (tk == ESMF_TypeKind_R4) then
       select case (fieldRank)
       case (1)
          call ESMF_FieldGet(field, farrayPtr=var_1d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VAR_1D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case (2)
          call ESMF_FieldGet(field, farrayPtr=var_2d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VAR_2D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case (3)
          call ESMF_FieldGet(field, farrayPtr=var_3d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VAR_3D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case (4)
          call ESMF_FieldGet(field, farrayPtr=var_4d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VAR_4D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case default
          _FAIL( 'only upto 4D are supported')
       end select
    else if (tk == ESMF_TypeKind_R8) then
       select case (fieldRank)
       case (1)
          call ESMF_FieldGet(field, farrayPtr=vr8_1d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VR8_1D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case (2)
          call ESMF_FieldGet(field, farrayPtr=vr8_2d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VR8_2D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case (3)
          call ESMF_FieldGet(field, farrayPtr=vr8_3d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VR8_3D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case (4)
          call ESMF_FieldGet(field, farrayPtr=vr8_4d, rc=status)
          _VERIFY(STATUS)
          call ESMF_FieldEmptyComplete(F, farrayPtr=VR8_4D,    &
               gridToFieldMap=gridToFieldMap,                      &
               datacopyFlag = datacopy,             &
               rc = status)
          _VERIFY(STATUS)
       case default
          _FAIL( 'only 2D and 3D are supported')
       end select
    else
       _FAIL( 'unsupported typekind')
    endif
    deallocate(gridToFieldMap)
    call MAPL_FieldCopyAttributes(FIELD_IN=field, FIELD_OUT=f, RC=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end function MAPL_FieldCreateRename
Call graph
mapl_fieldcreaterename calls ESMF_GridGet, esmf_fieldemptycomplete, esmf_fieldget, mapl_assert, mapl_fieldcopyattributes, mapl_fieldcreateempty, mapl_return, mapl_verify, mapl_fieldcreaterename
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldcopyattributes calls mapl_fieldcopyattributes, mapl_return, mapl_verify, ESMF_AttributeCopy
mapl_fieldcreateempty calls mapl_fieldcreateempty, mapl_return, mapl_verify, esmf_fieldemptycreate, esmf_fieldemptyset
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_fieldcreate calls mapl_fieldcreaterename
addvariable_to_acc_bundle calls mapl_fieldcreate
addvariable_to_output_bundle calls mapl_fieldcreate
create_bracketing_fields calls mapl_fieldcreate, createfilelevbracket
createfilelevbracket calls mapl_fieldcreate
createvariable calls mapl_fieldcreate
esmfl_bundlecpyfield calls mapl_fieldcreate
esmfl_stategetfield calls mapl_fieldcreate
initialize calls mapl_fieldcreate
initialize_ calls mapl_fieldcreate, createfilelevbracket
mapl_gridcompgetfriendlies0 calls mapl_fieldcreate
mapl_statecreatefromspecnew calls mapl_fieldcreate
mapl_statevarreadncpar calls mapl_fieldcreate
mapl_statevarwritencpar calls mapl_fieldcreate
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0
mapl_varreadncpar calls mapl_statevarreadncpar
mapl_varwritencpar calls mapl_statevarwritencpar
create_bundle_rh calls addvariable_to_acc_bundle, createvariable
createfilemetadata calls createvariable
mapl_genericinitialize calls mapl_statecreatefromspecnew
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
run_ calls create_bracketing_fields
stateregrid calls esmfl_stategetfield