MAPL_HashIncrement – MAPL
MAPL_HashIncrement Function
15 statements
Source File
public function MAPL_HashIncrement(Hash, i, j, k)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Hash
integer, intent(in) :: i
integer, intent(in), optional :: j
integer, intent(in), optional :: k
Return Value integer
Calls
Called by
Contents
Source Code
MAPL_HashIncrement
Source Code
integer function MAPL_HashIncrement(Hash,i,j,k)
  integer,           intent(IN) :: Hash
  integer,           intent(IN) :: i
  integer, optional, intent(IN) :: j
  integer, optional, intent(IN) :: k
  integer :: INCREMENTHASH, rc
  if    (present(k)) then
     _ASSERT(present(j),'needs informative message')
     MAPL_HashIncrement = INCREMENTHASH(HASH,I,J,K)
  elseif(present(j)) then
     MAPL_HashIncrement = INCREMENTHASH(HASH,I,J,INT_MAX)
  else
     MAPL_HashIncrement = INCREMENTHASH(HASH,I,INT_MAX,INT_MAX)
  endif
end function MAPL_HashIncrement
Call graph
mapl_hashincrement calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_locstreamcreatexform calls mapl_hashincrement
initialize calls mapl_locstreamcreatexform