MAPL_StateAddInternalSpec – MAPL
MAPL_StateAddInternalSpec Subroutine
79 statements
Source File
private subroutine MAPL_StateAddInternalSpec(GC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, DATATYPE, NUM_SUBTILES, REFRESH_INTERVAL, AVERAGING_INTERVAL, DEFAULT, RESTART, HALOWIDTH, PRECISION, FRIENDLYTO, ADD2EXPORT, ATTR_RNAMES, ATTR_INAMES, ATTR_RVALUES, ATTR_IVALUES, UNGRIDDED_DIMS, FIELD_TYPE, STAGGERING, ROTATION, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: LONG_NAME
character(len=*), intent(in), optional :: UNITS
integer, intent(in), optional :: DIMS
integer, intent(in), optional :: VLOCATION
integer, intent(in), optional :: DATATYPE
integer, intent(in), optional :: NUM_SUBTILES
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
real, intent(in), optional :: DEFAULT
integer, intent(in), optional :: RESTART
character(len=*), intent(in), optional :: HALOWIDTH
integer, intent(in), optional :: PRECISION
character(len=*), intent(in), optional :: FRIENDLYTO
logical, intent(in), optional :: ADD2EXPORT
character(len=*), intent(in), optional :: ATTR_RNAMES(:)
character(len=*), intent(in), optional :: ATTR_INAMES(:)
real, intent(in), optional :: ATTR_RVALUES(:)
integer, intent(in), optional :: ATTR_IVALUES(:)
integer, intent(in), optional :: UNGRIDDED_DIMS(:)
integer, intent(in), optional :: FIELD_TYPE
integer, intent(in), optional :: STAGGERING
integer, intent(in), optional :: ROTATION
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateAddInternalSpec
Source Code
   subroutine MAPL_StateAddInternalSpec(GC,                 &
        SHORT_NAME,         &
        LONG_NAME,          &
        UNITS,              &
        DIMS,               &
        VLOCATION,          &
        DATATYPE,           &
        NUM_SUBTILES,       &
        REFRESH_INTERVAL,   &
        AVERAGING_INTERVAL, &
        DEFAULT,            &
        RESTART,            &
        HALOWIDTH,          &
        PRECISION,          &
        FRIENDLYTO,         &
        ADD2EXPORT,         &
        ATTR_RNAMES,        &
        ATTR_INAMES,        &
        ATTR_RVALUES,       &
        ATTR_IVALUES,       &
        UNGRIDDED_DIMS,     &
        FIELD_TYPE,         &
        STAGGERING,         &
        ROTATION,           &
        RC)
      ! !ARGUMENTS:
      type (ESMF_GridComp)            , intent(INOUT)   :: GC
      character (len=*)               , intent(IN)      :: SHORT_NAME
      character (len=*)  , optional   , intent(IN)      :: LONG_NAME
      character (len=*)  , optional   , intent(IN)      :: UNITS
      integer            , optional   , intent(IN)      :: DIMS
      integer            , optional   , intent(IN)      :: DATATYPE
      integer            , optional   , intent(IN)      :: VLOCATION
      integer            , optional   , intent(IN)      :: NUM_SUBTILES
      integer            , optional   , intent(IN)      :: REFRESH_INTERVAL
      integer            , optional   , intent(IN)      :: AVERAGING_INTERVAL
      integer            , optional   , intent(IN)      :: PRECISION
      real               , optional   , intent(IN)      :: DEFAULT
      integer            , optional   , intent(IN)      :: RESTART
      character (len=*)  , optional   , intent(IN)      :: HALOWIDTH
      character (len=*)  , optional   , intent(IN)      :: FRIENDLYTO
      logical            , optional   , intent(IN)      :: ADD2EXPORT
      character (len=*)  , optional   , intent(IN)      :: ATTR_INAMES(:)
      character (len=*)  , optional   , intent(IN)      :: ATTR_RNAMES(:)
      integer            , optional   , intent(IN)      :: ATTR_IVALUES(:)
      real               , optional   , intent(IN)      :: ATTR_RVALUES(:)
      integer            , optional   , intent(IN)      :: UNGRIDDED_DIMS(:)
      integer            , optional   , intent(IN)      :: FIELD_TYPE
      integer            , optional   , intent(IN)      :: STAGGERING
      integer            , optional   , intent(IN)      :: ROTATION
      integer            , optional   , intent(OUT)     :: RC
      ! !DESCRIPTION:
      !  Sets the specifications for an item in the {\tt INTERNAL} state.
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddInternalSpec"
      integer                               :: status
      integer                               :: usable_RS
      integer                               :: usable_HW
      integer                               :: I
      type (MAPL_MetaComp), pointer         :: STATE
      type (MAPL_VarSpec),  pointer         :: SPEC
      integer                               :: default_dt
      integer                               :: interval
      real                                  :: dt
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      if (present(Restart)) then
         usable_RS  = Restart
      else
         usable_RS = MAPL_RestartOptional
      endif
      if (present(HALOWIDTH)) then
         read(HALOWIDTH,'(I1)') usable_HW
      else
         usable_HW = 0
      endif
      call MAPL_VarSpecCreateInListNew(STATE%COMPONENT_SPEC%INTERNAL,                       &
           LONG_NAME  = LONG_NAME,                                               &
           UNITS      = UNITS,                                                   &
           SHORT_NAME = SHORT_NAME,                                              &
           DIMS       = DIMS,                                                    &
           STAT       = DATATYPE,                                                &
           NUM_SUBTILES=NUM_SUBTILES,                                            &
           ACCMLT_INTERVAL= AVERAGING_INTERVAL,                                  &
           COUPLE_INTERVAL= REFRESH_INTERVAL,                                    &
           VLOCATION  = VLOCATION,                                               &
           DEFAULT    = DEFAULT, FRIENDLYTO = FRIENDLYTO,                        &
           HALOWIDTH  = usable_HW, PRECISION=PRECISION,                          &
           RESTART    = usable_RS,                                               &
           ATTR_RNAMES=ATTR_RNAMES, ATTR_INAMES=ATTR_INAMES,                     &
           ATTR_RVALUES=ATTR_RVALUES, ATTR_IVALUES=ATTR_IVALUES,                 &
           UNGRIDDED_DIMS=UNGRIDDED_DIMS,                                        &
           FIELD_TYPE = FIELD_TYPE,                                              &
           STAGGERING = STAGGERING,                                              &
           ROTATION   = ROTATION,                                                &
           RC=status  )
      _VERIFY(status)
      !ALT: the next section is added here upon the request of Arlindo:
      !     if FRIENDLYTO is set, we automatically
      !     add the spec/field to the export
      if (present(FRIENDLYTO) .or. present(ADD2EXPORT)) then
         I=MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS, SHORT_NAME, RC=status)
         if (I == -1) then
            _RETURN(ESMF_FAILURE)
         endif
         _VERIFY(status)
         call ESMF_ConfigGetAttribute( STATE%CF, dt,  Label="RUN_DT:", RC=status)
         _VERIFY(status)
         default_dt = nint(dt)
         SPEC => STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS(I)
         call MAPL_VarSpecGet(SPEC, ACCMLT_INTERVAL=interval, RC=status)
         _VERIFY(status)
         if (interval == 0) then ! this was not supplied
            call MAPL_VarSpecSet(SPEC, ACCMLT_INTERVAL=default_dt, RC=status)
            _VERIFY(status)
         endif
         call MAPL_VarSpecGet(SPEC, COUPLE_INTERVAL=interval, RC=status)
         _VERIFY(status)
         if (interval == 0) then ! this was not supplied
            call MAPL_VarSpecSet(SPEC, COUPLE_INTERVAL=default_dt, RC=status)
            _VERIFY(status)
         endif
         call MAPL_VarSpecAddRefToList(STATE%COMPONENT_SPEC%EXPORT, SPEC, RC=status)
         _VERIFY(status)
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddInternalSpec
Call graph
mapl_stateaddinternalspec calls mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify, mapl_varspecgetindex, esmf_configgetattribute, mapl_varspecget, mapl_varspecset, mapl_varspecaddreftolist
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstateget, mapl_internalstatecreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspeccreateinlistnew calls mapl_return, mapl_verify, mapl_assert
mapl_verify calls mapl_throw_exception
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetfieldptr, mapl_varspecgetstateptr, mapl_varspecgetnew, mapl_varspecgetbundleptr
mapl_varspecset calls mapl_varspecsetnew
mapl_varspecaddreftolist calls mapl_varspecaddreffromlist, mapl_varspecaddreffromitem
mapl_varspecaddreffromlist calls mapl_return, mapl_verify, mapl_varspecaddreffromitem
mapl_varspecsetnew calls mapl_return
mapl_internalstateget calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_internalstatecreate calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompsetinternalstate
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecaddreffromitem calls mapl_return, mapl_verify, mapl_varspecgetindex, mapl_varspecprint
mapl_varspecgetbundleptr calls mapl_return
mapl_addinternalspec calls mapl_stateaddinternalspec
setservices calls mapl_addinternalspec