MAPL_Assert_condition – MAPL
MAPL_Assert_condition Function
13 statements
Source File
private function MAPL_Assert_condition(condition, message, return_code, filename, line, rc) result(fail)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: condition
character(len=*), intent(in) :: message
integer, intent(in) :: return_code
character(len=*), intent(in) :: filename
integer, intent(in) :: line
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Contents
Source Code
MAPL_Assert_condition
Source Code
   logical function MAPL_Assert_condition(condition, message, return_code, filename, line, rc) result(fail)
      logical, intent(in) :: condition
      character(*), intent(in) :: message
      integer, intent(in) :: return_code
      character(*), intent(in) :: filename
      integer, intent(in) :: line
      integer, optional, intent(out) :: rc ! Not present in MAIN
      fail = .not. condition
      if (fail) then
         !$omp critical (MAPL_ErrorHandling1)
         call MAPL_throw_exception(filename, line, message=message)
         !$omp end critical (MAPL_ErrorHandling1)
         if (present(rc)) rc = return_code
      end if
   end function MAPL_Assert_Condition
Call graph
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition