MAPL_AddConnectivityMany – MAPL
MAPL_AddConnectivityMany Subroutine
16 statements
Source File
private subroutine MAPL_AddConnectivityMany(GC, SHORT_NAME, SRC_ID, DST_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME(:)
integer, intent(in) :: SRC_ID
integer, intent(in) :: DST_ID
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_AddConnectivityMany
Source Code
   subroutine MAPL_AddConnectivityMany ( GC, SHORT_NAME, SRC_ID, DST_ID, RC  )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*)             , intent(IN   ) :: SHORT_NAME(:)
      integer,                        intent(IN   ) :: SRC_ID
      integer,                        intent(IN   ) :: DST_ID
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_AddConnectivityMany"
      integer                               :: status
      integer                               :: I
      DO I = 1, size(SHORT_NAME)
         !ALT attention: DST_NAME needs to be revisited once we remove the old style interface to
         !               MAPL_AddConnectivity
         call MAPL_AddConnectivityRENAME ( GC, SRC_NAME=SHORT_NAME(I), DST_NAME=SHORT_NAME(I), &
              SRC_ID=SRC_ID, DST_ID=DST_ID, RC=status  )
         _VERIFY(status)
      END DO
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_AddConnectivityMany
Call graph
mapl_addconnectivitymany calls mapl_addconnectivityrename, mapl_return, mapl_verify
mapl_addconnectivityrename calls mapl_return, mapl_verify, mapl_connectivityget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_throw_exception calls initialize
mapl_getobjectfromgc calls mapl_internalstateget
mapl_addconnectivity calls mapl_addconnectivitymany, mapl_addconnectivityrenamemany
mapl_addconnectivityrenamemany calls mapl_addconnectivity
setservices calls mapl_addconnectivity, setservices