MAPL_ExtDataGridChangeLev – MAPL
MAPL_ExtDataGridChangeLev Function
80 statements
Source File
private function MAPL_ExtDataGridChangeLev(Grid, CF, lm, rc) result(newGrid)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: Grid
type(ESMF_Config), intent(inout) :: CF
integer, intent(in) :: lm
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Source Code
  function MAPL_ExtDataGridChangeLev(Grid,CF,lm,rc) result(NewGrid)
     type(ESMF_Grid), intent(inout) :: Grid
     type(ESMF_Config), intent(inout) :: CF
     integer,         intent(in)    :: lm
     integer, optional, intent(out) :: rc
     integer :: status
     character(len=ESMF_MAXSTR) :: Iam
     character(len=ESMF_MAXSTR) :: gname, comp_name
     integer :: counts(3)
     integer :: NX,NY
     type(ESMF_Grid)           :: newGrid
     type(ESMF_Config)         :: cflocal
     real :: temp_real
     logical :: isPresent
     IAM = "MAPL_ExtDataGridChangeLev"
     call MAPL_GridGet(grid,globalCellCountPerDim=counts,_RC)
     call ESMF_GridGet(grid,name=gName,_RC)
     call ESMF_ConfigGetAttribute(CF, value = NX, Label="NX:", _RC)
     call ESMF_ConfigGetAttribute(CF, value = NY, Label="NY:", _RC)
     comp_name = "ExtData"
     cflocal = MAPL_ConfigCreate(rc=status)
     _VERIFY(status)
     call MAPL_ConfigSetAttribute(cflocal,value=NX, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"NX:",rc=status)
     _VERIFY(status)
     call MAPL_ConfigSetAttribute(cflocal,value=lm, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"LM:",rc=status)
     _VERIFY(status)
     if (counts(2) == 6*counts(1)) then
        call MAPL_ConfigSetAttribute(cflocal,value="Cubed-Sphere", label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"GRID_TYPE:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=6, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"NF:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=counts(1), label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"IM_WORLD:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=ny/6, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"NY:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=trim(gname), label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"GRIDNAME:",rc=status)
        _VERIFY(status)
        call ESMF_AttributeGet(grid, name='STRETCH_FACTOR', isPresent=isPresent, rc=status)
        _VERIFY(status)
        if (isPresent) then
           call ESMF_AttributeGet(grid, name='STRETCH_FACTOR', value=temp_real, rc=status)
           _VERIFY(status)
           call MAPL_ConfigSetAttribute(cflocal,value=temp_real, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"STRETCH_FACTOR:",rc=status)
           _VERIFY(status)
        endif
        call ESMF_AttributeGet(grid, name='TARGET_LON', isPresent=isPresent, rc=status)
        _VERIFY(status)
        if (isPresent) then
           call ESMF_AttributeGet(grid, name='TARGET_LON', value=temp_real, rc=status)
           _VERIFY(status)
           call MAPL_ConfigSetAttribute(cflocal,value=temp_real*MAPL_RADIANS_TO_DEGREES, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"TARGET_LON:",rc=status)
           _VERIFY(status)
        endif
        call ESMF_AttributeGet(grid, name='TARGET_LAT', isPresent=isPresent, rc=status)
        _VERIFY(status)
        if (isPresent) then
           call ESMF_AttributeGet(grid, name='TARGET_LAT', value=temp_real, rc=status)
           _VERIFY(status)
           call MAPL_ConfigSetAttribute(cflocal,value=temp_real*MAPL_RADIANS_TO_DEGREES, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"TARGET_LAT:",rc=status)
           _VERIFY(status)
        endif
     else
        call MAPL_ConfigSetAttribute(cflocal,value=counts(1), label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"IM_WORLD:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=counts(2), label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"JM_WORLD:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=ny, label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"NY:",rc=status)
        _VERIFY(status)
        call MAPL_ConfigSetAttribute(cflocal,value=trim(gname), label=trim(COMP_Name)//MAPL_CF_COMPONENT_SEPARATOR//"GRIDNAME:",rc=status)
        _VERIFY(status)
     end if
     newgrid = grid_manager%make_grid(cflocal, prefix=trim(COMP_Name)//".", rc=status)
     _VERIFY(status)
     _RETURN(ESMF_SUCCESS)
  end function MAPL_ExtDataGridChangeLev
Call graph
mapl_extdatagridchangelev calls ESMF_AttributeGet, ESMF_ConfigGetAttribute, ESMF_GridGet, mapl_configsetattribute, make_grid, mapl_configcreate, mapl_gridget, mapl_return, mapl_verify
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configcreate calls mapl_return, ESMF_ConfigCreate, buffer
mapl_gridget calls ESMF_AttributeGet, ESMF_GridGet, mapl_return, mapl_verify, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
make_grid_from_distgrid calls make_grid, mapl_return, mapl_verify, ESMF_AttributeSet, make_factory
mapl_configsetattribute_int32 calls ESMF_ConfigGetAttribute, mapl_return, buffer
mapl_configsetattribute_ints32 calls mapl_configsetattribute, mapl_return, mapl_verify, mapl_assert
mapl_configsetattribute_real32 calls ESMF_ConfigGetAttribute, mapl_return, buffer
mapl_configsetattribute_real64 calls ESMF_ConfigGetAttribute, mapl_return, buffer
mapl_configsetattribute_reals32 calls mapl_configsetattribute, mapl_return, mapl_verify, mapl_assert
mapl_configsetattribute_string calls ESMF_ConfigGetAttribute, mapl_return, buffer
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
createfilelevbracket calls mapl_extdatagridchangelev
initialize_ calls createfilelevbracket