MAPL_MemUtilsInit – MAPL
MAPL_MemUtilsInit Subroutine
20 statements
Source File
public subroutine MAPL_MemUtilsInit(mode, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: mode
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_MemUtilsInit
Source Code
    subroutine MAPL_MemUtilsInit(mode,RC)
      integer, optional, intent(IN )   :: mode
      integer, optional, intent(OUT)   :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_MemUtilsInit"
!initialize memutils module
!currently sets default cache characteristics
!(will provide overrides later)
!also sets pe to my_pe on t3e
#ifdef _CRAYT3E
!all sizes in bytes
      l1_cache_line_size = 32
      l1_cache_size = 8192
      l1_associativity = 1
      l2_cache_line_size = 64
      l2_cache_size = 98304
      l2_associativity = 3
#else
!defaults
      l1_cache_line_size = 1
      l1_cache_size = 1
      l1_associativity = 1
      l2_cache_line_size = 1
      l2_cache_size = 1
      l2_associativity = 1
#endif
#ifdef _CRAYT3E
      pe = SHMEM_MY_PE()
#endif
      memutils_initialized = .TRUE.
      gmax_save = 0.0
      if (present(mode)) then
         MAPL_MemUtilsMode=mode
      else
         MAPL_memUtilsMode=MAPL_MemUtilsModeBase
      endif
      _RETURN(ESMF_SUCCESS)
    end subroutine MAPL_MemUtilsInit
Call graph
mapl_memutilsinit calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
initialize_gc calls mapl_memutilsinit
test_main calls mapl_memutilsinit
utcfio calls test_main