MAPL_VarRead_R8_4d – MAPL
MAPL_VarRead_R8_4d Subroutine
15 statements
Source File
private subroutine MAPL_VarRead_R8_4d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(out) :: A(:,:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_VarRead_R8_4d(UNIT, GRID, A, arrdes, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_Grid)            , intent(INout) :: GRID
    real(kind=ESMF_KIND_R8)     , intent(  OUT) :: A(:,:,:,:)
    type(ArrDescr),     optional, intent(INOUT) :: ARRDES
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer                               :: status
    integer :: L
    do L = 1, size(A,4)
       call MAPL_VarRead(UNIT, GRID, A(:,:,:,L), ARRDES=arrdes, rc=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarRead_R8_4d
Call graph
mapl_varread_r8_4d calls mapl_varread, mapl_return, mapl_verify
mapl_varread calls mapl_varread_r8_4d, mapl_bundleread, mapl_fieldread, mapl_statevarread, mapl_varread_r4_1d, mapl_varread_r4_2d, mapl_varread_r4_3d, mapl_varread_r4_4d, mapl_varread_r8_1d, mapl_varread_r8_2d, mapl_varread_r8_3d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_fieldread calls mapl_varread
mapl_readforcingx calls mapl_varread
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
readrestart calls mapl_varread
mapl_bundleread calls mapl_fieldread
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_statevarread calls mapl_fieldread, mapl_bundleread
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh
refresh_state calls mapl_genericstaterestore