MAPL_StateAddExportSpecFrmChld – MAPL
MAPL_StateAddExportSpecFrmChld Subroutine
16 statements
Source File
private subroutine MAPL_StateAddExportSpecFrmChld(GC, SHORT_NAME, CHILD_ID, RC, TO_NAME)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: CHILD_ID
integer, intent(out), optional :: RC
character(len=*), intent(in), optional :: TO_NAME
Calls
Called by
Source Code
   subroutine MAPL_StateAddExportSpecFrmChld ( GC, SHORT_NAME, CHILD_ID, RC, TO_NAME )
      !ARGUMENTS:
      type(ESMF_GridComp),              intent(INOUT)   :: GC
      character (len=*)               , intent(IN)      :: SHORT_NAME ! NAME in CHILD
      integer                         , intent(IN)      :: CHILD_ID
      integer            , optional   , intent(OUT)     :: RC
      character (len=*),      optional, intent(IN)      :: TO_NAME ! NAME to appear is EXPORT;
      ! default is SHORT_NAME
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddExportSpecFrmChld"
      integer                               :: status
      type(MAPL_MetaComp), pointer :: maplobj
      call MAPL_InternalStateRetrieve(gc, maplobj, _RC)
      call MAPL_StateAddExportSpecFrmChldName(gc, short_name, maplobj%gcnamelist(child_id), TO_NAME=TO_NAME, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddExportSpecFrmChld
Call graph
mapl_stateaddexportspecfrmchld calls mapl_internalstateretrieve, mapl_return, mapl_stateaddexportspecfrmchldname, mapl_verify
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_stateaddexportspecfrmchldname calls mapl_internalstateretrieve, mapl_return, mapl_verify, get_child_idx, mapl_addconnectivitye2e
mapl_verify calls mapl_throw_exception
get_child_idx calls get_num_children
get_error_message calls at, insert
mapl_addconnectivitye2e calls mapl_return, mapl_verify, append, mapl_connectivityget
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
append calls mapl_return, resize, vector_back
get_num_children calls get_num_children
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_addexportspec calls mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld
addnewspec calls mapl_addexportspec
setservices calls mapl_addexportspec, addstate
addstate calls addnewspec