MAPL_GridCompGetFriendlies2 – MAPL
MAPL_GridCompGetFriendlies2 Subroutine
16 statements
Source File
private subroutine MAPL_GridCompGetFriendlies2(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC(:)
character(len=*), intent(in) :: TO
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GridCompGetFriendlies2
Source Code
   subroutine MAPL_GridCompGetFriendlies2 ( GC, TO, BUNDLE, AddGCPrefix, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC(:)
      character(len=*),              intent(IN   )  :: TO
      type(ESMF_FieldBundle  ),      intent(INOUT)  :: BUNDLE
      logical, optional,             intent(IN   )  :: AddGCPrefix
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      integer                               :: status, I
      character(len=ESMF_MAXSTR)            :: TO_(1)
      TO_(1) = TO
      do I=1,size(GC)
         call MAPL_GridCompGetFriendlies0(GC(I), TO_, BUNDLE, AddGCPrefix, RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GridCompGetFriendlies2
Call graph
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0, mapl_return, mapl_verify
mapl_gridcompgetfriendlies0 calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridCompGet, esmf_fieldbundleget, esmf_fieldget, esmf_stateget, gcnamelist, get_internal_state, mapl_fieldbundleget, mapl_fieldcreate, mapl_gridcompgetfriendlies, write_parallel, am_i_friendly_, am_i_friendly__, get_child_gridcomp, mapl_internalstateget, putfieldinbundle__
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies3
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0