MAPL_Am_I_Rank_Vm – MAPL
MAPL_Am_I_Rank_Vm Function
13 statements
Source File
private function MAPL_Am_I_Rank_Vm(VM, rank) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
integer, optional :: rank
Return Value logical
Calls
Called by
Contents
Source Code
MAPL_Am_I_Rank_Vm
Source Code
  function MAPL_Am_I_Rank_Vm(VM, rank) result(R)
    type (ESMF_VM)    :: VM
    integer, optional :: rank
    logical           :: R
    integer        :: deId
    integer        :: status
    integer        :: rank_
    rank_ = MAPL_Root
    if (present(rank)) rank_ = rank
    call ESMF_VMGet(VM, localPet=deId, rc=status)
    R = .false.
    if (deId == rank_) R = .true.
  end function MAPL_Am_I_Rank_Vm
Call graph
mapl_am_i_rank_vm calls ESMF_VMGet
mapl_am_i_rank calls mapl_am_i_rank_vm, mapl_am_i_rank_layout, mapl_am_i_rank_only
mapl_am_i_rank_layout calls mapl_am_i_rank
mapl_am_i_rank_only calls mapl_am_i_rank
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm