MAPL_GenericWrapper – MAPL
MAPL_GenericWrapper Subroutine
107 statements
Source File
private recursive subroutine MAPL_GenericWrapper(GC, IMPORT, EXPORT, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: GC
type(ESMF_State) :: IMPORT
type(ESMF_State) :: EXPORT
type(ESMF_Clock) :: CLOCK
integer, intent(out) :: RC
Calls
Contents
Source Code
MAPL_GenericWrapper
Source Code
   recursive subroutine MAPL_GenericWrapper ( GC, IMPORT, EXPORT, CLOCK, RC)
      !ARGUMENTS:
      type(ESMF_GridComp)  :: GC     ! Gridded component
      type(ESMF_State)     :: IMPORT ! Import state
      type(ESMF_State)     :: EXPORT ! Export state
      type(ESMF_Clock)     :: CLOCK  ! The clock
      integer, intent(OUT) :: RC     ! Error code
      !EOPI
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)    :: IAm
      character(len=ESMF_MAXSTR)    :: comp_name
      integer                       :: status
      integer                       :: userRC
      ! Local derived type aliases
      type (MAPL_MetaComp),pointer :: STATE
      integer                          :: PHASE
      integer                          :: PHASE_
      integer                          :: I
      type(ESMF_Method_Flag)           :: method
      type(ESMF_VM) :: VM
      class(BaseProfiler), pointer :: t_p
      character(1) :: char_phase
      character(len=12), pointer :: timers(:) => NULL()
      ! the next declaration assumes all 5 methods have the same signature
      ! we just picked one of them
      procedure(ESMF_GridCompRun), pointer :: func_ptr => NULL()
      character(len=12), target :: timers_run(1) = &
           [character(len=12):: 'GenRunMine']
      character(len=:), allocatable :: sbrtn
      character(:), allocatable :: stage_description
      class(Logger), pointer :: lgr
      logical :: use_threads
      !=============================================================================
      ! Begin...
      _UNUSED_DUMMY(IMPORT)
      _UNUSED_DUMMY(EXPORT)
      ! Get the target components name and set-up traceback handle.
      ! -----------------------------------------------------------
      Iam = "MAPL_GenericWrapper"
      call ESMF_GridCompGet( GC, NAME=comp_name, currentPhase=PHASE, &
           currentMethod=method, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      lgr => logging%get_logger('MAPL.GENERIC')
      call ESMF_VmGetCurrent(VM)
      ! Retrieve the pointer to the internal state. It comes in a wrapper.
      ! ------------------------------------------------------------------
      call MAPL_InternalStateGet ( GC, STATE, RC=status)
      _VERIFY(status)
      ! TIMERS on
      t_p => get_global_time_profiler()
      call t_p%start(trim(state%compname),_RC)
      phase_ = MAPL_MAX_PHASES+phase ! this is the "actual" phase, i.e. the one user registered
      MethodBlock: if (method == ESMF_METHOD_RUN) then
         func_ptr => ESMF_GridCompRun
         timers => timers_run
         sbrtn = 'Run'
         if (phase > 1) then
            write(char_phase,'(i1)')phase
            sbrtn = 'Run'//char_phase
         end if
      else if (method == ESMF_METHOD_INITIALIZE) then
         func_ptr => ESMF_GridCompInitialize
         !ALT: enable this when fully implemented (for now NULLIFY)
         NULLIFY(timers)
         sbrtn = 'Initialize'
      else if (method == ESMF_METHOD_FINALIZE) then
         func_ptr => ESMF_GridCompFinalize
         !ALT: enable this when fully implemented (for now NULLIFY)
         NULLIFY(timers)
         sbrtn = 'Finalize'
      else if (method == ESMF_METHOD_READRESTART) then
         func_ptr => ESMF_GridCompReadRestart
         !ALT: enable this when fully implemented (for now NULLIFY)
         NULLIFY(timers)
         sbrtn = 'ReadRestart'
      else if (method == ESMF_METHOD_WRITERESTART) then
         func_ptr => ESMF_GridCompWriteRestart
         !ALT: enable this when fully implemented (for now NULLIFY)
         NULLIFY(timers)
         sbrtn = 'WriteRestart'
      endif MethodBlock
      stage_description = sbrtn//' stage of the gridded component <'//trim(COMP_NAME)//'>'
      ! TIMERS on
      if (method /= ESMF_METHOD_READRESTART .and. method /= ESMF_METHOD_WRITERESTART) then
         call state%t_profiler%start(_RC)
         call state%t_profiler%start(trim(sbrtn),_RC)
      end if
      if (associated(timers)) then
         do i = 1, size(timers)
            call MAPL_TimerOn (STATE,timers(i))
         end do
      end if
      ! Method itself
      ! ----------
      call lgr%debug('Started %a', stage_description)
      use_threads  = STATE%get_use_threads() ! determine if GC uses OpenMP threading
      if (use_threads .and. method == ESMF_METHOD_RUN)  then
         call omp_driver(GC, import, export, clock, _RC)  ! compnent threaded with OpenMP
      else
         call func_ptr (GC, &
              importState=IMPORT, &
              exportState=EXPORT, &
              clock=CLOCK, PHASE=PHASE_, &
              userRC=userRC, _RC )
         _VERIFY(userRC)
         _ASSERT(userRC==ESMF_SUCCESS .and. STATUS==ESMF_SUCCESS,'Error during '//stage_description//' for <'//trim(COMP_NAME)//'>')
      end if
      call lgr%debug('Finished %a', stage_description)
      ! TIMERS off
      if (associated(timers)) then
         do i = size(timers),1,-1
            call MAPL_TimerOff (STATE,timers(i),_RC)
         end do
      end if
      if (method /= ESMF_METHOD_FINALIZE) then
         if (method /= ESMF_METHOD_WRITERESTART .and. &
              method /= ESMF_METHOD_READRESTART) then
            call state%t_profiler%stop(trim(sbrtn),_RC)
            call state%t_profiler%stop(_RC)
         end if
         call t_p%stop(trim(state%compname),_RC)
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericWrapper
Call graph
mapl_genericwrapper calls esmf_gridcompget, mapl_internalstateget, mapl_verify, esmf_vmgetcurrent, get_global_time_profiler, mapl_timeron, omp_driver, mapl_assert, mapl_timeroff, mapl_return
mapl_internalstateget calls esmf_gridcompget, mapl_verify, mapl_return, esmf_usercompgetinternalstate
mapl_verify calls mapl_throw_exception
mapl_timeron calls mapl_genericstateclockon
omp_driver calls esmf_gridcompget, mapl_verify, mapl_assert, mapl_getobjectfromgc, get_num_threads, esmf_gridcomprun, get_current_thread, mapl_rtrn
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_timeroff calls mapl_genericstateclockoff
mapl_return calls mapl_throw_exception, get_error_message
mapl_genericstateclockoff calls mapl_verify, mapl_return, get_actual_timer_name
mapl_getobjectfromgc calls mapl_internalstateget
mapl_genericstateclockon calls mapl_verify, mapl_return, get_actual_timer_name
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message