MAPL_VarSpecPrintMany – MAPL
MAPL_VarSpecPrintMany Subroutine
12 statements
Source File
private subroutine MAPL_VarSpecPrintMany(SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecPrintMany
Source Code
   subroutine MAPL_VarSpecPrintMany(SPEC, RC )
      type (MAPL_VarSpec ),             intent(IN )     :: SPEC(:)
      integer            , optional   , intent(OUT)     :: RC
      integer                               :: STATUS
      integer                               :: I
      !    if(.not.associated(SPEC)) then
      !       _RETURN(ESMF_FAILURE)
      !    endif
      DO I = 1, size(SPEC)
         call MAPL_VarSpecPrint(Spec(I), RC=status)
         _VERIFY(STATUS)
      END DO
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecPrintMany
Call graph
mapl_varspecprintmany calls mapl_varspecprint, mapl_return, mapl_verify
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecprintone calls mapl_return, info
mapl_setvarspecforcc calls mapl_varspecprint, mapl_varspecaddreftolist
mapl_stateprintspec calls mapl_varspecprint, mapl_stateprintspec
mapl_varspecaddreffromitem calls mapl_varspecprint
mapl_varspecaddreffromitemnew calls mapl_varspecprint
mapl_varspecaddreftolist calls mapl_varspecaddreffromitem, mapl_varspecaddreffromlist, mapl_varspecaddreffromitemnew
mapl_varspecaddreffromlist calls mapl_varspecaddreffromitem
mapl_genericspecenum calls mapl_varspecaddreftolist
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist