MAPL_PinFlagGet – MAPL
MAPL_PinFlagGet Function
4 statements
Source File
public function MAPL_PinFlagGet() result(pinflag)
Arguments
None
Return Value type(ESMF_Pin_Flag)
Called by
Source Code
  function MAPL_PinFlagGet() result(pinflag)
    type(ESMF_PIN_FLAG) :: pinflag
    pinflag = pinflag_global
  end function MAPL_PinFlagGet
Call graph
mapl_fieldalloccommit calls mapl_pinflagget, mapl_fieldalloccommit
initialize_ calls mapl_fieldalloccommit
mapl_allocatecoupling calls mapl_fieldalloccommit, mapl_allocatecoupling
mapl_statecreatefromspecnew calls mapl_fieldalloccommit
mapl_genericinitialize calls mapl_statecreatefromspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew