MAPL_GridGetInterior – MAPL
MAPL_GridGetInterior Module Subroutine
58 statements
Source File
module subroutine MAPL_GridGetInterior(grid, I1, IN, J1, JN) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(out) :: I1
integer, intent(out) :: IN
integer, intent(out) :: J1
integer, intent(out) :: JN
Calls
Called by
Source Code
  module subroutine MAPL_GridGetInterior(GRID,I1,IN,J1,JN)
    type (ESMF_Grid), intent(IN) :: grid
    integer, intent(OUT)         :: I1, IN, J1, JN
    ! local vars
    integer                               :: status
    !    character(len=ESMF_MAXSTR)            :: IAm='MAPL_GridGetInterior'
    type (ESMF_DistGrid)                  :: distGrid
    type(ESMF_DELayout)                   :: LAYOUT
    type (ESMF_VM)                        :: vm
    integer,               allocatable    :: AL(:,:)
    integer,               allocatable    :: AU(:,:)
    integer                               :: nDEs
    integer                               :: deId
    integer                               :: gridRank
    integer                               :: rc
    logical                               :: isPresent
    integer, allocatable                  :: global_grid_info(:)
    integer                               :: itemCount
    i1=-1
    j1=-1
    in=-1
    jn=-1
    call ESMF_AttributeGet(grid, name="GLOBAL_GRID_INFO", isPresent=isPresent, _RC)
    if (isPresent) then
      call ESMF_AttributeGet(grid, name="GLOBAL_GRID_INFO", itemCount=itemCount, _RC)
      allocate(global_grid_info(itemCount), _STAT)
      call ESMF_AttributeGet(grid, name="GLOBAL_GRID_INFO", valueList=global_grid_info, _RC)
      I1 = global_grid_info(7)
      IN = global_grid_info(8)
      j1 = global_grid_info(9)
      JN = global_grid_info(10)
      deallocate(global_grid_info, _STAT)
      _RETURN(_SUCCESS)
    end if
    call ESMF_GridGet    (GRID, dimCount=gridRank, distGrid=distGrid, _RC)
    call ESMF_DistGridGet(distGRID, delayout=layout, _RC)
    call ESMF_DELayoutGet(layout, vm=vm, _RC)
    call ESMF_VmGet(vm, localPet=deId, petCount=nDEs, _RC)
    allocate (AL(gridRank,0:nDEs-1),  _STAT)
    allocate (AU(gridRank,0:nDEs-1),  _STAT)
    call MAPL_DistGridGet(distgrid, &
         minIndex=AL, maxIndex=AU, _RC)
    I1 = AL(1, deId)
    IN = AU(1, deId)
    !    _ASSERT(gridRank > 1, 'tilegrid is 1d (without RC this only for info')
    J1 = AL(2, deId)
    JN = AU(2, deId)
    deallocate(AU, AL)
  end subroutine MAPL_GridGetInterior
Call graph
mapl_gridgetinterior calls ESMF_AttributeGet, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_distgridget, mapl_return, mapl_verify, mapl_gridgetinterior
mapl_distgridget calls ESMF_DistGridGet, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
generate_file_bounds calls mapl_gridgetinterior
generate_file_corner_bounds calls mapl_gridgetinterior
get_xy_mask calls mapl_gridgetinterior
interp_accumulate_fields calls mapl_gridgetinterior
mapl_getglobalhorzijindex calls mapl_gridgetinterior, mapl_getglobalhorzijindex
regrid_accumulate_on_xysubset calls interp_accumulate_fields
mapl_gethorzijindex calls mapl_getglobalhorzijindex
run calls regrid_accumulate_on_xysubset