MAPL_ExtDataCreateCFIO – MAPL
MAPL_ExtDataCreateCFIO Subroutine
16 statements
Source File
private subroutine MAPL_ExtDataCreateCFIO(IOBundles, rc)
Arguments
Type Intent Optional Attributes Name
type(IoBundleNGVector), intent(inout), target :: IOBundles
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ExtDataCreateCFIO
Source Code
  subroutine MAPL_ExtDataCreateCFIO(IOBundles, rc)
    type(IOBundleNGVector), target, intent(inout) :: IOBundles
    integer, optional,      intent(out  ) :: rc
     type (IOBundleNGVectorIterator) :: bundle_iter
     type (ExtDataNG_IOBundle), pointer :: io_bundle
     integer :: status
     bundle_iter = IOBundles%begin()
     do while (bundle_iter /= IOBundles%end())
        io_bundle => bundle_iter%get()
        call io_bundle%make_io(_RC)
        call bundle_iter%next()
     enddo
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataCreateCFIO
Call graph
mapl_extdatacreatecfio calls begin, get, next, make_io, mapl_return, mapl_verify
make_io calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
run_ calls mapl_extdatacreatecfio