MAPL_UnpackDateTime – MAPL
MAPL_UnpackDateTime Module Subroutine
10 statements
Source File
module subroutine MAPL_UnpackDateTime(date_time, yy, mm, dd, h, m, s) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: date_time(:)
integer, intent(out) :: yy
integer, intent(out) :: mm
integer, intent(out) :: dd
integer, intent(out) :: h
integer, intent(out) :: m
integer, intent(out) :: s
Called by
Source Code
  module subroutine MAPL_UnpackDateTime(date_time, yy, mm, dd, h, m, s)
    integer, intent(in) :: date_time(:)
    integer, intent(out) :: yy, mm, dd, h, m, s
    yy =     date_time(1) / 10000
    mm = mod(date_time(1), 10000) / 100
    dd = mod(date_time(1), 100)
    h  =     date_time(2) / 10000
    m  = mod(date_time(2), 10000) / 100
    s  = mod(date_time(2), 100)
  end subroutine MAPL_UnpackDateTime
Call graph
mapl_unpackdatetime calls mapl_unpackdatetime
mapl_clockinit calls mapl_unpackdatetime
mapl_readforcingx calls mapl_unpackdatetime
parsetimes calls mapl_unpackdatetime
initialize_gc calls mapl_clockinit, parsetimes
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2