MAPL_AddConnectivityRenameMany – MAPL
MAPL_AddConnectivityRenameMany Subroutine
17 statements
Source File
private subroutine MAPL_AddConnectivityRenameMany(GC, SRC_NAME, SRC_ID, DST_NAME, DST_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SRC_NAME(:)
integer, intent(in) :: SRC_ID
character(len=*), intent(in) :: DST_NAME(:)
integer, intent(in) :: DST_ID
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_AddConnectivityRenameMany
Source Code
   subroutine MAPL_AddConnectivityRenameMany ( GC, SRC_NAME, SRC_ID, &
        DST_NAME, DST_ID, RC  )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*),              intent(IN   ) :: SRC_NAME(:)
      character (len=*),              intent(IN   ) :: DST_NAME(:)
      integer,                        intent(IN   ) :: SRC_ID !FROM_EXPORT
      integer,                        intent(IN   ) :: DST_ID !TO_IMPORT
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_AddConnectivityRename"
      integer                               :: status
      integer                               :: I
      DO I = 1, size(SRC_NAME)
         call MAPL_AddConnectivity ( GC, SRC_NAME=SRC_NAME(I), DST_NAME=DST_NAME(I), &
              SRC_ID=SRC_ID, DST_ID=DST_ID, RC=status  )
         _VERIFY(status)
      END DO
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_AddConnectivityRenameMany
Call graph
mapl_addconnectivityrenamemany calls mapl_addconnectivity, mapl_verify, mapl_return
mapl_addconnectivity calls mapl_addconnectivityrenamemany, mapl_addconnectivityrename, mapl_addconnectivitymany
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_addconnectivityrename calls mapl_verify, mapl_return, mapl_connectivityget
mapl_addconnectivitymany calls mapl_verify, mapl_return, mapl_addconnectivityrename
mapl_throw_exception calls initialize
mapl_connectivityget calls mapl_verify, mapl_return, mapl_getobjectfromgc
setservices calls mapl_addconnectivity, setservices