MAPL_TileMaskGet – MAPL
MAPL_TileMaskGet Subroutine
103 statements
Source File
public subroutine MAPL_TileMaskGet(GRID, mask, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: GRID
integer, pointer :: mask(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_TileMaskGet
Source Code
  subroutine MAPL_TileMaskGet(grid, mask, rc)
    type (ESMF_Grid),             intent(INout) :: GRID
    integer, pointer                            :: mask(:)
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer                               :: STATUS
    integer, pointer                      :: tileIndex(:)
    integer                               :: gcount(2), lcount(2)
    integer                               :: gsize, lsize
    integer                               :: gridRank
    integer                               :: n
    type (ESMF_DistGrid)                  :: distGrid
    integer,               allocatable    :: AL(:,:)
    integer,               allocatable    :: AU(:,:)
    integer, allocatable, dimension(:)    :: recvcounts, displs
    integer                               :: de, deId
    integer                               :: nDEs
    integer                               :: sendcount
    integer                               :: I
    integer                               :: I1, IN
    integer, allocatable                  :: var(:)
    type (ESMF_DELayout)                  :: layout
    type(ESMF_VM) :: vm
    logical :: amIRoot
    call ESMF_GridGet(grid, dimCount=gridRank, distGrid=distGrid, rc=status)
    _VERIFY(STATUS)
    _ASSERT(gridRank == 1, 'gridRank must be 1')
    call MAPL_GridGet(grid, globalCellCountPerDim=gcount, &
         localCellCountPerDim=lcount, RC=STATUS)
    _VERIFY(STATUS)
    gsize = gcount(1)
    lsize = lcount(1)
    call ESMF_DistGridGet(distgrid, localDe=0, elementCount=n, rc=status)
    _ASSERT(lsize == n, ' inconsistent lsize')
    allocate(tileIndex(lsize), stat=status)
    _VERIFY(STATUS)
    call ESMF_DistGridGet(distgrid, localDe=0, seqIndexList=tileIndex, rc=status)
    _VERIFY(STATUS)
    call ESMF_DistGridGet(distGRID, delayout=layout, rc=STATUS)
    _VERIFY(STATUS)
    call ESMF_DELayoutGet(layout, vm=vm, rc=status)
    _VERIFY(STATUS)
    call ESMF_VmGet(vm, localPet=deId, petCount=nDEs, rc=status)
    _VERIFY(STATUS)
    amIRoot = MAPL_AM_I_Root(vm)
    call ESMF_VmBarrier(vm, rc=status)
    _VERIFY(STATUS)
    if (.not. MAPL_ShmInitialized) then
       allocate(mask(gsize), stat=status)
       _VERIFY(STATUS)
    else
       call MAPL_AllocNodeArray(mask,(/gsize/),rc=STATUS)
       _VERIFY(STATUS)
    end if
    allocate (AL(gridRank,0:nDEs-1),  stat=status)
    _VERIFY(STATUS)
    allocate (AU(gridRank,0:nDEs-1),  stat=status)
    _VERIFY(STATUS)
    call MAPL_DistGridGet(distgrid, &
         minIndex=AL, maxIndex=AU, rc=status)
    _VERIFY(STATUS)
    allocate (recvcounts(0:nDEs-1), displs(0:nDEs), stat=status)
    _VERIFY(STATUS)
    if (.not. MAPL_ShmInitialized .or. amIRoot) then
       allocate(VAR(0:gsize-1), stat=status)
       _VERIFY(STATUS)
    else
       allocate(VAR(0), stat=status)
       _VERIFY(STATUS)
    end if
    displs(0) = 0
    do I = 0,nDEs-1
       de = I
       I1 = AL(1,I)
       IN = AU(1,I)
       recvcounts(I) = (IN - I1 + 1)
       if (de == deId) then
          sendcount = recvcounts(I)      ! Count I will send
       endif
       displs(I+1) = displs(I) + recvcounts(I)
    enddo
#ifdef NEW
    _FAIL( 'unsupported code block') !ALT this section is questionable
    do I = 0,nDEs-1
       de = I
       I1 = AL(1,I)
       IN = AU(1,I)
       var(I1:IN) = -9999
       if (de == deId) then
          var(I1:IN) = tileindex
       endif
       do II=I1,IN
          mmax=var(II)
          call MAPL_CommsAllReduceMax(vm, mmax, var(II), 1, rc=status)
          _VERIFY(STATUS)
       enddo
    end do
#else
    if (MAPL_ShmInitialized) then
       call MAPL_CommsGatherV(layout, tileindex, sendcount, &
                              var, recvcounts, displs, MAPL_Root, status)
       _VERIFY(STATUS)
    else
       call MAPL_CommsAllGatherV(layout, tileindex, sendcount, &
                                 var, recvcounts, displs, status)
       _VERIFY(STATUS)
    endif
#endif
    if (.not. MAPL_ShmInitialized .or. amIRoot) then
       do I = 0,nDEs-1
          mask(displs(I)+1:displs(I+1)) = I
       end do
       call MAPL_SORT(var,MASK)
    end if
! clean up
    deallocate(var)
    deallocate (recvcounts, displs)
    deallocate (AU)
    deallocate (AL)
    deallocate(tileIndex)
! mask is deallocated in the caller routine
       call MAPL_BroadcastToNodes(MASK, N=gsize, ROOT=MAPL_Root, rc=status)
       _VERIFY(STATUS)
    call MAPL_SyncSharedMemory(rc=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_TileMaskGet
Call graph
mapl_tilemaskget calls esmf_vmget, mapl_commsgatherv, esmf_vmbarrier, mapl_broadcasttonodes, mapl_sort, mapl_commsallgatherv, mapl_syncsharedmemory, mapl_return, esmf_gridget, mapl_verify, esmf_distgridget, mapl_assert, mapl_gridget, mapl_am_i_root, mapl_allocnodearray, mapl_distgridget, esmf_delayoutget
mapl_fieldread calls mapl_tilemaskget, mapl_varread
mapl_statevarread calls mapl_tilemaskget, mapl_fieldread, mapl_bundleread
mapl_fieldwrite calls mapl_tilemaskget, mapl_varwrite
mapl_statevarwrite calls mapl_tilemaskget, mapl_fieldwrite, mapl_bundlewrite
readrestart calls mapl_tilemaskget, mapl_varread
writerestart calls mapl_tilemaskget, mapl_varwrite
mapl_bundleread calls mapl_fieldread
mapl_bundlewrite calls mapl_fieldwrite
mapl_varread calls mapl_fieldread, mapl_statevarread, mapl_bundleread
mapl_varwrite calls mapl_fieldwrite, mapl_statevarwrite, mapl_bundlewrite
mapl_varwrite_r8_4d calls mapl_varwrite
mapl_varwrite_r8_3d calls mapl_varwrite
mapl_varwrite_r8_2d calls mapl_varwrite
mapl_esmfstatewritetofile calls mapl_varwrite
mapl_varwrite_r4_4d calls mapl_varwrite
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_varwrite_r4_2d calls mapl_varwrite
mapl_varwrite_r4_3d calls mapl_varwrite
run calls mapl_varwrite