MAPL_Am_I_Root_Layout – MAPL
MAPL_Am_I_Root_Layout Function
5 statements
Source File
private function MAPL_Am_I_Root_Layout(layout) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
Return Value logical
Calls
Called by
Contents
Source Code
MAPL_Am_I_Root_Layout
Source Code
  function MAPL_Am_I_Root_Layout(layout) result(R)
    type (ESMF_DELayout) :: layout
    logical              :: R
    R = MAPL_Am_I_Rank(layout)
  end function MAPL_Am_I_Root_Layout
Call graph
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_am_i_rank_layout calls mapl_am_i_rank, ESMF_DELayoutGet
mapl_am_i_rank_only calls mapl_am_i_rank, ESMF_VMGetCurrent
mapl_am_i_rank_vm calls ESMF_VMGet
mapl_am_i_root calls mapl_am_i_root_layout