MAPL_Am_I_Rank_Layout – MAPL
MAPL_Am_I_Rank_Layout Function
13 statements
Source File
private function MAPL_Am_I_Rank_Layout(layout, rank) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer, optional :: rank
Return Value logical
Calls
Called by
Source Code
  function MAPL_Am_I_Rank_Layout(layout, rank) result(R)
    type (ESMF_DELayout) :: layout
    integer, optional    :: rank
    logical              :: R
    integer       :: status
    type (ESMF_VM) :: vm
    call ESMF_DELayoutGet(layout, vm=vm, rc=status)
    if (present(rank)) then
        R = MAPL_Am_I_Rank(vm, rank)
    else
        R = MAPL_Am_I_Rank(vm)
    end if
  end function MAPL_Am_I_Rank_Layout
Call graph
mapl_am_i_rank_layout calls ESMF_DELayoutGet, mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_am_i_rank_only calls mapl_am_i_rank, ESMF_VMGetCurrent
mapl_am_i_rank_vm calls ESMF_VMGet
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm