MAPL_VarSpecGetIndexOfItem – MAPL
MAPL_VarSpecGetIndexOfItem Function
23 statements
Source File
private function MAPL_VarSpecGetIndexOfItem(SPEC, ITEM, RC) result(INDEX)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM
integer, intent(out), optional :: RC
Return Value integer
Calls
Called by
Contents
Source Code
MAPL_VarSpecGetIndexOfItem
Source Code
   function MAPL_VarSpecGetIndexOfItem(SPEC, ITEM, RC) result (INDEX)
      type (MAPL_VarSpec )            , intent(in)   :: SPEC(:)
      type (MAPL_VarSpec )            , intent(in)   :: ITEM
      integer, optional               , intent(OUT)  :: RC
      integer                                        :: INDEX
      integer :: I
      do I = 1, size(SPEC)
         if(.not.associated(SPEC(I)%SPECPtr)) then
            _RETURN(ESMF_FAILURE)
         endif
         if (trim(SPEC(I)%SPECPtr%SHORT_NAME) == trim(ITEM%SPECPtr%SHORT_NAME)) then
            if (SPEC(I) == ITEM) then
               INDEX = I
               _RETURN(ESMF_SUCCESS)
            end if
         endif
      enddo
      INDEX = -1 ! not found
      _RETURN(ESMF_SUCCESS)
   end function MAPL_VarSpecGetIndexOfItem
Call graph
mapl_varspecgetindexofitem calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecgetindex calls mapl_varspecgetindexofitem
mapl_donotallocatevar calls mapl_varspecgetindex
mapl_donotdeferexport calls mapl_varspecgetindex
mapl_readforcingx calls mapl_varspecgetindex
mapl_wirecomponent calls mapl_varspecgetindex
mapl_varspeccreateinlist calls mapl_varspecgetindex
mapl_setvarspecforcc calls mapl_varspecgetindex
mapl_stategetspecattrib calls mapl_varspecgetindex
mapl_varspecaddreffromitemnew calls mapl_varspecgetindex
mapl_stateaddimportspecfrmchld calls mapl_varspecgetindex
mapl_statecreatefromspecnew calls mapl_varspecgetindex
mapl_varspecaddreffromitem calls mapl_varspecgetindex
mapl_stateaddinternalspec calls mapl_varspecgetindex
checkreq calls mapl_varspecgetindex
mapl_varspecreconnect calls mapl_varspecgetindex
mapl_statesetspecattrib calls mapl_varspecgetindex
mapl_friendlyget calls mapl_varspecgetindex
test_add_spec_grows_container calls mapl_varspecgetindex