MAPL_ExtDataPopulateBundle – MAPL
MAPL_ExtDataPopulateBundle Subroutine
46 statements
Source File
private subroutine MAPL_ExtDataPopulateBundle(item, filec, pbundle, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
integer, intent(in) :: filec
type(ESMF_FieldBundle), intent(inout) :: pbundle
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ExtDataPopulateBundle
Source Code
  subroutine MAPL_ExtDataPopulateBundle(item,filec,pbundle,rc)
      type(PrimaryExport), intent(inout)      :: item
      integer,                  intent(in)    :: filec
      type(ESMF_FieldBundle), intent(inout)   :: pbundle
      integer, optional, intent(out)          :: rc
      integer :: status
      type(ESMF_Field) :: Field,field1,field2
      type(ESMF_Grid)  :: grid
      if (item%isVector) then
         if (item%do_Fill .or. item%do_VertInterp) then
            call MAPL_ExtDataGetBracket(item,filec,field=Field1,vcomp=1,getRL=.true.,_RC)
            call MAPL_ExtDataGetBracket(item,filec,field=Field2,vcomp=2,getRL=.true.,_RC)
         else
            call MAPL_ExtDataGetBracket(item,filec,field=Field1,vcomp=1,_RC)
            call MAPL_ExtDataGetBracket(item,filec,field=Field2,vcomp=2,_RC)
         end if
         call ESMF_FieldGet(Field1,grid=grid,rc=status)
         _VERIFY(STATUS)
         call ESMF_FieldBundleSet(pbundle,grid=grid,rc=status)
         _VERIFY(STATUS)
         call MAPL_FieldBundleAdd(pbundle,Field1,rc=status)
         _VERIFY(STATUS)
         call MAPL_FieldBundleAdd(pbundle,Field2,rc=status)
         _VERIFY(STATUS)
         !block
            !character(len=ESMF_MAXSTR) :: vectorlist(2)
            !vectorlist(1) = item%fcomp1
            !vectorlist(2) = item%fcomp2
            !call ESMF_AttributeSet(pbundle,name="VectorList:", itemCount=2, &
                 !valuelist = vectorlist, rc=status)
            !_VERIFY(STATUS)
         !end block
      else
         if (item%do_Fill .or. item%do_VertInterp) then
            call MAPL_ExtDataGetBracket(item,filec,field=Field,getRL=.true.,_RC)
         else
            call MAPL_ExtDataGetBracket(item,filec,field=Field,_RC)
         end if
         call ESMF_FieldGet(Field,grid=grid,rc=status)
         _VERIFY(STATUS)
         call ESMF_FieldBundleSet(pbundle,grid=grid,rc=status)
         _VERIFY(STATUS)
         call MAPL_FieldBundleAdd(pbundle,Field,rc=status)
         _VERIFY(STATUS)
      end if
      _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataPopulateBundle
Call graph
mapl_extdatapopulatebundle calls mapl_extdatagetbracket, mapl_fieldbundleadd, mapl_verify, esmf_fieldget, esmf_fieldbundleset, mapl_return
mapl_extdatagetbracket calls mapl_return
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_verify calls mapl_throw_exception
mapl_return calls get_error_message, mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_verify, esmf_fieldget, mapl_return, esmf_fieldbundleadd, esmf_attributeget, esmf_attributeremove, esmf_attributeset
mapl_throw_exception calls initialize
run_ calls mapl_extdatapopulatebundle