MAPL_CommsAllReduceMin_I4_0 – MAPL
MAPL_CommsAllReduceMin_I4_0 Subroutine
16 statements
Source File
private subroutine MAPL_CommsAllReduceMin_I4_0(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer(kind=ESMF_KIND_I4), intent(in) :: sendbuf
integer(kind=ESMF_KIND_I4), intent(inout) :: recvbuf
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Calls
Called by
Call graph
mapl_commsallreducemin_i4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_commsallreducemin calls mapl_commsallreducemin_i4_0