MAPL_GetNumSubtiles – MAPL
MAPL_GetNumSubtiles Function
34 statements
Source File
private function MAPL_GetNumSubtiles(STATE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
integer, intent(out), optional :: RC
Return Value integer
Calls
Called by
Contents
Source Code
MAPL_GetNumSubtiles
Source Code
   integer function MAPL_GetNumSubtiles(STATE, RC)
      type (MAPL_MetaComp),       intent(INOUT)    :: STATE
      integer  , optional,        intent(  OUT)    :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_GetNumSubtiles"
      integer                               :: status
      integer                               :: I
      integer                               :: DIMS
      integer                               :: NUM_SUBTILES
      MAPL_GetNumSubtiles = 1
      if (associated(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS)) then
         DO I = 1, size(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS)
            call MAPL_VarSpecGet(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS(I), DIMS = DIMS,       &
                 NUM_SUBTILES=NUM_SUBTILES,                 &
                 RC=status  )
            _VERIFY(status)
            if (DIMS == MAPL_DimsTileTile) then
               MAPL_GetNumSubtiles = NUM_SUBTILES
               _RETURN(ESMF_SUCCESS)
            end if
         END DO
      end if
      if (associated(STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS)) then
         DO I = 1, size(STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS)
            call MAPL_VarSpecGet(STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS(I), DIMS = DIMS,       &
                 NUM_SUBTILES=NUM_SUBTILES,                 &
                 RC=status  )
            _VERIFY(status)
            if (DIMS == MAPL_DimsTileTile) then
               MAPL_GetNumSubtiles = NUM_SUBTILES
               _RETURN(ESMF_SUCCESS)
            end if
         END DO
      end if
      _RETURN(ESMF_SUCCESS)
   end function MAPL_GetNumSubtiles
Call graph
mapl_getnumsubtiles calls mapl_varspecget, mapl_return, mapl_verify
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetfieldptr, mapl_varspecgetstateptr, mapl_varspecgetnew, mapl_varspecgetbundleptr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_varspecgetregular calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_throw_exception calls initialize
mapl_genericinitialize calls mapl_getnumsubtiles
mapl_readforcingx calls mapl_getnumsubtiles
mapl_readforcing1 calls mapl_readforcingx
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
my_initialize calls mapl_genericinitialize
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2