MAPL_incymd – MAPL
MAPL_incymd Module Function
29 statements
Source File
module function MAPL_incymd(nymd, m) Interface →
Arguments
Type Intent Optional Attributes Name
integer :: nymd
integer :: m
Return Value integer
Calls
Called by
Source Code
  integer module function MAPL_incymd (NYMD,M)
    integer nymd,ny,nm,nd,m
    INTEGER NDPM(12)
    DATA    NDPM /31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31/
    NY = NYMD / 10000
    NM = MOD(NYMD,10000) / 100
    ND = MOD(NYMD,100) + M
    IF (ND.EQ.0) THEN
       NM = NM - 1
       IF (NM.EQ.0) THEN
          NM = 12
          NY = NY - 1
       ENDIF
       ND = NDPM(NM)
       IF (NM.EQ.2 .AND. MAPL_LEAP(NY))  ND = 29
    ENDIF
    IF (ND.EQ.29 .AND. NM.EQ.2 .AND. MAPL_LEAP(NY))  GO TO 20
    IF (ND.GT.NDPM(NM)) THEN
       ND = 1
       NM = NM + 1
       IF (NM.GT.12) THEN
          NM = 1
          NY = NY + 1
       ENDIF
    ENDIF
20  CONTINUE
    MAPL_INCYMD = NY*10000 + NM*100 + ND
    RETURN
  end function MAPL_incymd
Call graph
mapl_incymd calls mapl_leap, mapl_incymd
mapl_leap calls mapl_leap
mapl_tick calls mapl_incymd, mapl_tick