MAPL_HashDump – MAPL
MAPL_HashDump Function
20 statements
Source File
public function MAPL_HashDump(Hash, i, j)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Hash
integer, intent(out) :: i(:)
integer, intent(out), optional :: j(:)
Return Value integer
Calls
Contents
Source Code
MAPL_HashDump
Source Code
integer function MAPL_HashDump(Hash,i,j)
  integer, intent(IN ) :: Hash
  integer, intent(OUT) :: i(:)
  integer, optional, intent(OUT) :: j(:)
  integer, allocatable :: jj(:)
  integer :: rc
  MAPL_HashDump = MAPL_HashSize(HASH)
  if(size(i) < MAPL_HashSize(HASH)) then
     MAPL_HashDump = -1
     return
  end if
  if(present(j)) then
     _ASSERT(size(i) == size(j),'needs informative message')
     call DUMPHASH(HASH,I,J)
  else
     allocate(jj(size(i)))
     call DUMPHASH(HASH,I,JJ)
     deallocate(JJ)
  end if
end function MAPL_HashDump
Call graph
mapl_hashdump calls dumphash, mapl_assert, mapl_hashsize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize