MAPL_CFIOWriteBundle – MAPL
MAPL_CFIOWriteBundle Subroutine
38 statements
Source File
private subroutine MAPL_CFIOWriteBundle(MCFIO, CLOCK, BUNDLE, VERBOSE, NBITS, created, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
type(ESMF_Clock), intent(inout), optional :: CLOCK
type(ESMF_FIELDBUNDLE), intent(inout), optional :: BUNDLE
logical, intent(in), optional :: VERBOSE
integer, intent(in), optional :: NBITS
logical, intent(in), optional :: created
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CFIOWriteBundle
Source Code
  subroutine MAPL_CFIOWriteBundle( MCFIO, CLOCK, Bundle, &
                                   VERBOSE, NBITS, created, RC    )
!
! !ARGUMENTS:
!
    type(MAPL_CFIO  ),                 intent(INOUT) :: MCFIO
    type(ESMF_CLOCK),       optional,  intent(INOUT) :: CLOCK
    type(ESMF_FIELDBUNDLE), optional,  intent(INout) :: BUNDLE
    logical,                optional,  intent(IN   ) :: VERBOSE
    integer,                optional,  intent(IN   ) :: NBITS
    logical,                optional,  intent(IN   ) :: created
    integer,                optional,  intent(  OUT) :: RC
!
#ifdef ___PROTEX___
 !DESCRIPTION:
       Writes an ESMF Bundle to a File. Only the MAPL\_CFIO object is
       a required argument as pointers to the actual data to be
       written is recorded in it during creation.
       {\tt CLOCK, BUNDLE} can be used to override the choice
       made at creation, but this is of dubious value, particularly
       for {\tt BUNDLE} since it must be excatly conformant with the
       creation {\tt BUNDLE}. {\tt NBITS} if the number of bits of
       the mantissa to retain. This is used to write files with degraded
       precision, which can then be compressed with standard utilities.
       The default is no degradation of precision.
       {\bf A note about compression.} NetCDF-4, HDF-4 and HDF-5 all
       support transparent internal GZIP compression of the data being
       written. However, very little is gained by compressing float
       point fields from earth system models. Compression yields can
       be greatly increased by setting to zero bits in the mantissa of float
       numbers. On average 50\% compression can be achieved, while
       preserving a meaningful accuracy in the fields. Unlike
       classical CF compression by means of {\tt scale\_factor} and
       {\tt add\_offset} attributes, internal GZIP compression
       requires no special handling by the users of the data. In fact,
       they do not even need to know that the data is compressed! At this
       point, MAPL\_CFIO does not activate this GZIP compression
       feature in the files being written, but the resulting precision
       degredaded files can be compressed offline with the HDF-4
       {\tt hrepack} utility.
#endif
!EOP
    integer                    :: status
    logical                    :: isCreated
    _UNUSED_DUMMY(VERBOSE)
    _ASSERT(present(CLOCK), 'CLOCK argument must be present')
    _ASSERT(present(BUNDLE), 'BUNDLE argument must be present')
! for backward compatibility
!---------------------------
    if(present(NBITS)) then
       mCFIO%Nbits = Nbits
    end if
! DSK fName is set in History during runtime, but the G5 tutorial does not, so we must set it here
    if (IACHAR(MCFIO%fName(1:1)) == 0) then
       call MAPL_CFIOSet( MCFIO, fName=MCFIO%Name, RC=status )
       _VERIFY(STATUS)
    endif
    if (present(created)) then
       isCreated=created
    else
       isCreated=.false.
    end if
    if (.not.isCreated) then
       call MAPL_CFIOCreateWrite    ( MCFIO,         RC=status)
       _VERIFY(STATUS)
    end if
    call MAPL_CFIOWriteBundlePost( MCFIO,         RC=status)
    _VERIFY(STATUS)
    call MAPL_CFIOWriteBundleWait( MCFIO, CLOCK,  RC=status)
    _VERIFY(STATUS)
    call MAPL_CFIOWriteBundleWrite( MCFIO, CLOCK, RC=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOWriteBundle
Call graph
mapl_cfiowritebundle calls mapl_assert, mapl_cfioset, mapl_cfiowritebundlepost, mapl_verify, mapl_cfiocreatewrite, mapl_cfiowritebundlewait, mapl_cfiowritebundlewrite, mapl_return
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_simplebundlewrite1 calls mapl_cfiowrite
test_main calls esmf_iowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main