MAPL_StateAttSetI4 – MAPL
MAPL_StateAttSetI4 Module Subroutine
49 statements
Source File
recursive module subroutine MAPL_StateAttSetI4(STATE, NAME, VALUE, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
integer, intent(in) :: VALUE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateAttSetI4
Source Code
  recursive module subroutine MAPL_StateAttSetI4(STATE, NAME, VALUE, RC)
    type(ESMF_State),                 intent(INOUT) :: STATE
    character(len=*),                 intent(IN   ) :: NAME
    integer,                          intent(IN   ) :: VALUE
    integer, optional,                intent(  OUT) :: RC
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAttSet"
    integer                               :: STATUS
    type(ESMF_State)                      :: nestedSTATE
    type(ESMF_Field)                      :: FIELD
    type(ESMF_FieldBundle)                :: BUNDLE
    type (ESMF_StateItem_Flag), pointer   :: ITEMTYPES(:)
    character(len=ESMF_MAXSTR ), pointer  :: ITEMNAMES(:)
    integer                               :: ITEMCOUNT
    integer                               :: I
    call ESMF_AttributeSet(STATE, NAME, VALUE, RC=status)
    _VERIFY(STATUS)
    call ESMF_StateGet(STATE,ITEMCOUNT=ITEMCOUNT,RC=STATUS)
    _VERIFY(STATUS)
    IF (ITEMCOUNT>0) then
       allocate(ITEMNAMES(ITEMCOUNT),STAT=STATUS)
       _VERIFY(STATUS)
       allocate(ITEMTYPES(ITEMCOUNT),STAT=STATUS)
       _VERIFY(STATUS)
       call ESMF_StateGet(STATE, ITEMNAMELIST=ITEMNAMES, &
            ITEMTYPELIST=ITEMTYPES, RC=STATUS)
       _VERIFY(STATUS)
       do I = 1, ITEMCOUNT
          if(itemtypes(I)==ESMF_StateItem_State) then
             call ESMF_StateGet(STATE, itemNames(I), nestedState, RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_AttributeSet(nestedState, NAME, VALUE, RC=status)
             _VERIFY(STATUS)
          else if(itemtypes(I)==ESMF_StateItem_FieldBundle) then
             call ESMF_StateGet(STATE, itemNames(I), BUNDLE, RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_AttributeSet(BUNDLE, NAME, VALUE, RC=status)
             _VERIFY(STATUS)
          else if(itemtypes(I)==ESMF_StateItem_Field) then
             call ESMF_StateGet(STATE, itemNames(I), FIELD, RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_AttributeSet(FIELD, NAME, VALUE, RC=status)
             _VERIFY(STATUS)
          end if
       end do
       deallocate(ITEMNAMES)
       deallocate(ITEMTYPES)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_StateAttSetI4
Call graph
mapl_stateattseti4 calls ESMF_AttributeSet, esmf_stateget, mapl_attributeset, mapl_return, mapl_verify, mapl_stateattseti4
mapl_attributeset calls mapl_bundleattseti4, mapl_fieldattseti4, mapl_stateattseti4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_bundleattseti4 calls mapl_bundleattseti4, ESMF_AttributeSet, mapl_return, mapl_verify, esmf_fieldbundleget
mapl_fieldattseti4 calls mapl_fieldattseti4, ESMF_AttributeSet, mapl_return, mapl_verify, esmf_fieldget
get_error_message calls at
mapl_throw_exception calls initialize
mapl_esmfstatereadfromfile calls mapl_attributeset
mapl_fieldalloccommit calls mapl_attributeset, mapl_fieldalloccommit
mapl_statecreatefromspecnew calls mapl_attributeset
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
mapl_staterefresh calls mapl_esmfstatereadfromfile