MAPL_DoNotConnectMany – MAPL
MAPL_DoNotConnectMany Subroutine
15 statements
Source File
private subroutine MAPL_DoNotConnectMany(GC, SHORT_NAME, CHILD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME(:)
integer, intent(in) :: CHILD
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_DoNotConnectMany ( GC, SHORT_NAME, CHILD, RC )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*)             , intent(IN   ) :: SHORT_NAME(:)
      integer,                        intent(IN   ) :: CHILD
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_DoNotConnectMany"
      integer                               :: status
      integer                               :: I
      DO I = 1, size(SHORT_NAME)
         call MAPL_DoNotConnect(GC, SHORT_NAME(I), CHILD, RC=status)
         _VERIFY(status)
      END DO
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_DoNotConnectMany
Call graph
mapl_donotconnectmany calls mapl_donotconnect, mapl_return, mapl_verify
mapl_donotconnect calls mapl_return, mapl_verify, append, mapl_connectivityget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
append calls mapl_return, resize, vector_back
get_error_message calls at, insert
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_throw_exception calls initialize
mapl_getobjectfromgc calls mapl_internalstateget
mapl_terminateimport calls mapl_donotconnectmany, mapl_terminateimportall
mapl_terminateimportall calls mapl_terminateimport