MAPL_BundleAttSetI4 – MAPL
MAPL_BundleAttSetI4 Module Subroutine
23 statements
Source File
module subroutine MAPL_BundleAttSetI4(BUNDLE, NAME, VALUE, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
character(len=*), intent(in) :: NAME
integer, intent(in) :: VALUE
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  module subroutine MAPL_BundleAttSetI4(BUNDLE, NAME, VALUE, RC)
    type(ESMF_FieldBundle),           intent(INOUT) :: BUNDLE
    character(len=*),                 intent(IN   ) :: NAME
    integer,                          intent(IN   ) :: VALUE
    integer, optional,                intent(  OUT) :: RC
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_BundleAttSet"
    integer                               :: STATUS
    type(ESMF_Field)                      :: FIELD
    integer                               :: FIELDCOUNT
    integer                               :: I
    call ESMF_AttributeSet(BUNDLE, NAME, VALUE, RC=status)
    _VERIFY(STATUS)
    call ESMF_FieldBundleGet(BUNDLE, FieldCount=FIELDCOUNT, RC=STATUS)
    _VERIFY(STATUS)
    do I = 1, FIELDCOUNT
       call ESMF_FieldBundleGet(BUNDLE, I, FIELD, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_AttributeSet(FIELD, NAME, VALUE, RC=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_BundleAttSetI4
Call graph
mapl_bundleattseti4 calls ESMF_AttributeSet, esmf_fieldbundleget, mapl_return, mapl_verify, mapl_bundleattseti4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_attributeset calls mapl_bundleattseti4
mapl_esmfstatereadfromfile calls mapl_attributeset
mapl_fieldalloccommit calls mapl_attributeset, mapl_fieldalloccommit
mapl_stateattseti4 calls mapl_attributeset, mapl_stateattseti4
mapl_statecreatefromspecnew calls mapl_attributeset
mapl_genericinitialize calls mapl_esmfstatereadfromfile, mapl_statecreatefromspecnew
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
mapl_staterefresh calls mapl_esmfstatereadfromfile