MAPL_StateAddExportSpecFrmChldName – MAPL
MAPL_StateAddExportSpecFrmChldName Subroutine
18 statements
Source File
private subroutine MAPL_StateAddExportSpecFrmChldName(GC, short_name, child_name, rc, TO_NAME)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: short_name
character(len=*), intent(in) :: child_name
integer, intent(out), optional :: rc
character(len=*), intent(in), optional :: TO_NAME
Calls
Called by
Source Code
   subroutine MAPL_StateAddExportSpecFrmChldName ( GC, short_name, child_name, rc, TO_NAME )
      !ARGUMENTS:
      type(ESMF_GridComp),              intent(INOUT)   :: GC
      character (len=*)               , intent(IN)      :: short_name
      character(*), intent(in) :: child_name
      integer            , optional   , intent(OUT)     :: rc
      character (len=*),      optional, intent(IN)      :: TO_NAME ! NAME to appear is EXPORT;
      ! default is SHORT_NAME
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddExportSpecFrmChld"
      integer  :: child_id
      integer  :: status
      type(MAPL_MetaComp), pointer :: maplobj
      call MAPL_InternalStateRetrieve(gc, maplobj, _RC)
      child_id = maplobj%get_child_idx(child_name)
      call MAPL_AddConnectivityE2E ( GC, SHORT_NAME, &
           TO_NAME = TO_NAME, &
           SRC_ID = CHILD_ID, &
           TO_EXPORT = MAPL_Self, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddExportSpecFrmChldName
Call graph
mapl_stateaddexportspecfrmchldname calls get_child_idx, mapl_addconnectivitye2e, mapl_internalstateretrieve, mapl_return, mapl_verify
get_child_idx calls get_num_children
mapl_addconnectivitye2e calls mapl_return, mapl_verify, append, mapl_connectivityget
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
append calls mapl_return, resize, vector_back
get_error_message calls at, insert
get_num_children calls get_num_children
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_getobjectfromgc calls mapl_internalstateget
mapl_stateaddexportspecfrmchld calls mapl_stateaddexportspecfrmchldname
mapl_addexportspec calls mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld
addnewspec calls mapl_addexportspec
setservices calls mapl_addexportspec
addstate calls addnewspec