MAPL_LocStreamCreateFromStream – MAPL
MAPL_LocStreamCreateFromStream Subroutine
74 statements
Source File
private subroutine MAPL_LocStreamCreateFromStream(LocStreamOut, LocStreamIn, NAME, MASK, RC)
Creates a location stream as a subset of another according to mask.
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(out) :: LocStreamOut
type(MAPL_LocStream), intent(in) :: LocStreamIn
character(len=*), intent(in) :: NAME
integer, intent(in), optional :: MASK(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_LocStreamCreateFromStream
Source Code
  subroutine MAPL_LocStreamCreateFromStream(LocStreamOut, LocStreamIn, NAME, MASK, RC)
! !ARGUMENTS:
    type(MAPL_LocStream),                 intent(  OUT) :: LocStreamOut
    type(MAPL_LocStream),                 intent(IN   ) :: LocStreamIn
    character(len=*),                     intent(IN   ) :: NAME
    integer,                    optional, intent(IN   ) :: MASK(:)
    integer,                    optional, intent(  OUT) :: RC
! Local variables
    integer                    :: STATUS
    integer                           :: N, I, K, NT
    type(MAPL_LocStreamType), pointer :: STREAMOUT
    type(MAPL_LocStreamType), pointer :: STREAMIN
    integer                           :: NT_LOCAL(1)
    logical, pointer                  :: MSK(:)
    type(ESMF_VM)                     :: VM
! Begin
!------
    _ASSERT(     associated(LocStreamIn %Ptr),'needs informative message')
! Allocate the Location Stream
!-----------------------------
    LocStreamOut%Ptr => null()
    allocate(LocStreamOut%Ptr, STAT=STATUS)
    _VERIFY(STATUS)
    STREAMOUT => LocStreamOut%Ptr
    STREAMIN  => LocStreamIn %Ptr
! Make sure that the input stream is attached
!--------------------------------------------
    _ASSERT(STREAMIN%CURRENT_TILING > 0,'needs informative message')
! New stream has the same identifier as old
!------------------------------------------
    STREAMOUT%NAME       = NAME
    STREAMOUT%ROOTNAME   = STREAMIN%ROOTNAME
    STREAMOUT%N_GRIDS    = STREAMIN%N_GRIDS
    STREAMOUT%CURRENT_TILING = STREAMIN%CURRENT_TILING
    STREAMOUT%GRID = STREAMIN%GRID
    STREAMOUT%isTileAreaValid = STREAMIN%isTileAreaValid
! Allocate the allowed tilings and copy the names and sizes of the grids
!-----------------------------------------------------------------------
    allocate(STREAMOUT%TILING(STREAMOUT%N_GRIDS), STAT=STATUS)
    _VERIFY(STATUS)
    STREAMOUT%Tiling     = STREAMIN%Tiling
! Local number of tiles in input stream
!--------------------------------------
    NT = STREAMIN%NT_LOCAL
! Allocate msk for which tiles to include in the stream being created.
!--------------------------------------------------------------------
    allocate(MSK(NT), STAT=STATUS)
    _VERIFY(STATUS)
! We include any tile whose type matches any element of the mask
!---------------------------------------------------------------
    if(present(MASK)) then
       do N=1,NT
          MSK(N) = any(STREAMIN%Local_GeoLocation(N)%T==MASK)
       end do
    else
       MSK = .true.
    end if
! The number of tiles in the new stream
!--------------------------------------
    STREAMOUT%NT_LOCAL = count(MSK)
    NT_LOCAL(1) = STREAMOUT%NT_LOCAL
    call ESMF_VMGetCurrent(vm, rc=status)
    _VERIFY(STATUS)
    call ESMF_VMAllFullReduce(vm, sendData=nt_local, recvData=STREAMOUT%NT_GLOBAL, &
         count=1, reduceflag=ESMF_REDUCE_SUM, rc=STATUS)
    _VERIFY(STATUS)
! Allocate space for local versions of stream parameters
!--------------------------------------------------------
    allocate(STREAMOUT%LOCAL_ID         (STREAMOUT%NT_LOCAL), STAT=STATUS)
    _VERIFY(STATUS)
    allocate(STREAMOUT%LOCAL_GEOLOCATION(STREAMOUT%NT_LOCAL), STAT=STATUS)
    _VERIFY(STATUS)
    allocate(STREAMOUT%LOCAL_INDEXLOCATION(STREAMOUT%NT_LOCAL), STAT=STATUS)
    _VERIFY(STATUS)
    allocate(STREAMOUT%D(-1:1,-1:1,STREAMOUT%NT_LOCAL), STAT=STATUS)
    _VERIFY(STATUS)
! Fill local stream parameters subject to mask
!----------------------------------------------
    K = 0
    do I=1, NT
       if(MSK(I)) then
          K = K + 1
          STREAMOUT%LOCAL_ID         (K)   = STREAMIN%LOCAL_ID         (I)
          STREAMOUT%LOCAL_GeoLocation(K)%T = STREAMIN%LOCAL_GeoLocation(I)%T
          STREAMOUT%LOCAL_GeoLocation(K)%A = STREAMIN%LOCAL_GeoLocation(I)%A
          STREAMOUT%LOCAL_GeoLocation(K)%X = STREAMIN%LOCAL_GeoLocation(I)%X
          STREAMOUT%LOCAL_GeoLocation(K)%Y = STREAMIN%LOCAL_GeoLocation(I)%Y
          STREAMOUT%LOCAL_IndexLocation(K)%I = STREAMIN%LOCAL_IndexLocation(I)%I
          STREAMOUT%LOCAL_IndexLocation(K)%J = STREAMIN%LOCAL_IndexLocation(I)%J
          STREAMOUT%LOCAL_IndexLocation(K)%W = STREAMIN%LOCAL_IndexLocation(I)%W
          STREAMOUT%D(:,:,K) = STREAMIN%D(:,:,I)
       end if
    end do
    deallocate(MSK)
! Create a tile grid
!-------------------
    call MAPL_LocStreamCreateTileGrid(LocStreamOut, STREAMIN%GRID, RC=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_LocStreamCreateFromStream
Call graph
mapl_locstreamcreatefromstream calls ESMF_VMAllFullReduce, ESMF_VMGetCurrent, d, mapl_assert, local_geolocation, local_id, local_indexlocation, mapl_locstreamcreatetilegrid, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_locstreamcreatetilegrid calls mapl_assert, mapl_return, mapl_verify, ESMF_AttributeSet, ESMF_DistGridCreate, ESMF_GridCommit, ESMF_GridEmptyCreate, ESMF_GridGet, ESMF_GridSet, c_mapl_locstreamretrieveptr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_locstreamcreate calls mapl_locstreamcreatefromstream
initialize calls mapl_locstreamcreate