MAPL_StatePrintSpecCSV – MAPL
MAPL_StatePrintSpecCSV Subroutine
82 statements
Source File
public recursive subroutine MAPL_StatePrintSpecCSV(GC, printSpec, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(in) :: printSpec
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StatePrintSpecCSV
Source Code
   recursive subroutine MAPL_StatePrintSpecCSV(GC, printSpec, RC)
      !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      integer,                       intent(IN   )  :: printSpec
      integer,             optional, intent(  OUT)  :: RC
      !EOPI
      !=============================================================================
      !
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)            :: IAm='MAPL_StatePrintSpecCSV'
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: MAPLOBJ
      type (MAPL_VarSpec),               pointer  :: IMPORT_SPEC(:)
      type (MAPL_VarSpec),               pointer  :: EXPORT_SPEC(:)
      type (MAPL_VarSpec),               pointer  :: INTERNAL_SPEC(:)
      integer                                     :: I
      type(ESMF_GridComp), pointer :: gridcomp
      !EOP
      ! Get my name and set-up traceback handle
      ! ---------------------------------------
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      ! Retrieve the pointer to the internal state
      ! --------------------------------------------
      call MAPL_InternalStateRetrieve ( GC, MAPLOBJ, RC=status )
      _VERIFY(status)
      IMPORT_SPEC => MAPLOBJ%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      EXPORT_SPEC => MAPLOBJ%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      INTERNAL_SPEC => MAPLOBJ%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS
      if (printSpec == 1) then
         if (associated(IMPORT_SPEC)) then
            call WRITE_PARALLEL("#IMPORT spec for " // trim(comp_name))
            call WRITE_PARALLEL("#COMPONENT, SHORT_NAME, LONG_NAME, UNIT, DIMS, CONTAINER_TYPE")
            if (associated(IMPORT_SPEC)) then
               call MAPL_VarSpecPrintCSV(IMPORT_SPEC, comp_name, RC=status)
               _VERIFY(status)
            end if
         end if
         if (associated(EXPORT_SPEC)) then
            call WRITE_PARALLEL("#EXPORT spec for " // trim(comp_name))
            call WRITE_PARALLEL("#COMPONENT, SHORT_NAME, LONG_NAME, UNIT, DIMS, CONTAINER_TYPE")
            if (associated(EXPORT_SPEC)) then
               call MAPL_VarSpecPrintCSV(EXPORT_SPEC, comp_name, RC=status)
               _VERIFY(status)
            end if
         end if
         if (associated(INTERNAL_SPEC)) then
            call WRITE_PARALLEL("#INTERNAL spec for " // trim(comp_name))
            call WRITE_PARALLEL("#COMPONENT, SHORT_NAME, LONG_NAME, UNIT, DIMS, CONTAINER_TYPE")
            if (associated(INTERNAL_SPEC)) then
               call MAPL_VarSpecPrintCSV(INTERNAL_SPEC, comp_name, RC=status)
               _VERIFY(status)
            end if
         end if
      else if (printSpec == 2) then
         if (associated(IMPORT_SPEC)) then
            call WRITE_PARALLEL("#IMPORT spec for " // trim(comp_name))
            call WRITE_PARALLEL("#COMPONENT, SHORT_NAME, LONG_NAME, UNIT, DIMS, CONTAINER_TYPE")
            if (associated(IMPORT_SPEC)) then
               call MAPL_VarSpecPrintCSV(IMPORT_SPEC, comp_name, RC=status)
               _VERIFY(status)
            end if
         end if
      else if (printSpec == 3) then
         if (associated(EXPORT_SPEC)) then
            call WRITE_PARALLEL("#EXPORT spec for " // trim(comp_name))
            call WRITE_PARALLEL("#COMPONENT, SHORT_NAME, LONG_NAME, UNIT, DIMS, CONTAINER_TYPE")
            if (associated(EXPORT_SPEC)) then
               call MAPL_VarSpecPrintCSV(EXPORT_SPEC, comp_name, RC=status)
               _VERIFY(status)
            end if
         end if
      else if (printSpec == 4) then
         if (associated(INTERNAL_SPEC)) then
            call WRITE_PARALLEL("#INTERNAL spec for " // trim(comp_name))
            call WRITE_PARALLEL("#COMPONENT, SHORT_NAME, LONG_NAME, UNIT, DIMS, CONTAINER_TYPE")
            if (associated(INTERNAL_SPEC)) then
               call MAPL_VarSpecPrintCSV(INTERNAL_SPEC, comp_name, RC=status)
               _VERIFY(status)
            end if
         end if
      end if
      do I = 1, MAPLOBJ%get_num_children()
         gridcomp => MAPLOBJ%GET_CHILD_GRIDCOMP(I)
         call MAPL_StatePrintSpecCSV(gridcomp, printSpec, RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StatePrintSpecCSV
Call graph
mapl_stateprintspeccsv calls mapl_stateprintspeccsv, esmf_gridcompget, mapl_verify, mapl_internalstateretrieve, write_parallel, mapl_varspecprintcsv, mapl_return
mapl_verify calls mapl_throw_exception
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
write_parallel calls write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r8_0, write_parallel_r4_1, write_parallel_r8_1, write_parallel_string_0
mapl_varspecprintcsv calls mapl_verify, mapl_return, mapl_varspecprint1csv
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_internalstateget calls esmf_gridcompget, mapl_verify, mapl_return, esmf_usercompgetinternalstate
write_parallel_i4_0 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert, dealloc_
mapl_internalstatecreate calls esmf_gridcompget, mapl_verify, mapl_return, esmf_usercompsetinternalstate
write_parallel_i4_1 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert, alloc_
write_parallel_r4_0 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert, dealloc_
write_parallel_r8_0 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert, dealloc_
write_parallel_r4_1 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert, alloc_
write_parallel_r8_1 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert, alloc_
write_parallel_string_0 calls mapl_verify, mapl_return, mpi_file_write, mapl_am_i_root, mpi_file_seek, mapl_assert
mapl_varspecprint1csv calls mapl_return
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
dealloc_ calls mapl_return, mapl_assert
alloc_ calls mapl_verify, mapl_return, mapl_assert, dealloc_
initialize_gc calls mapl_stateprintspeccsv