MAPL_VarSpecGetRegular – MAPL
MAPL_VarSpecGetRegular Subroutine
146 statements
Source File
private subroutine MAPL_VarSpecGetRegular(SPEC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, FIELD, BUNDLE, STATE, NUM_SUBTILES, STAT, ACCMLT_INTERVAL, COUPLE_INTERVAL, OFFSET, LABEL, DEFAULT, defaultProvided, FRIENDLYTO, RESTART, HALOWIDTH, PRECISION, ATTR_RNAMES, ATTR_INAMES, ATTR_RVALUES, ATTR_IVALUES, UNGRIDDED_DIMS, UNGRIDDED_UNIT, UNGRIDDED_NAME, UNGRIDDED_COORDS, FIELD_TYPE, STAGGERING, ROTATION, GRID, doNotAllocate, alwaysAllocate, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
character(len=*), intent(out), optional :: SHORT_NAME
character(len=*), intent(out), optional :: LONG_NAME
character(len=*), intent(out), optional :: UNITS
integer, intent(out), optional :: DIMS
integer, intent(out), optional :: VLOCATION
type(ESMF_Field), intent(out), optional :: FIELD
type(ESMF_FieldBundle), intent(out), optional :: BUNDLE
type(ESMF_State), intent(out), optional :: STATE
integer, intent(out), optional :: NUM_SUBTILES
integer, intent(out), optional :: STAT
integer, intent(out), optional :: ACCMLT_INTERVAL
integer, intent(out), optional :: COUPLE_INTERVAL
integer, intent(out), optional :: OFFSET
integer, intent(out), optional :: LABEL
real, intent(out), optional :: DEFAULT
logical, intent(out), optional :: defaultProvided
character(len=*), intent(out), optional :: FRIENDLYTO
integer, intent(out), optional :: RESTART
integer, intent(out), optional :: HALOWIDTH
integer, intent(out), optional :: PRECISION
character(len=ESMF_MAXSTR), optional, pointer :: ATTR_RNAMES(:)
character(len=ESMF_MAXSTR), optional, pointer :: ATTR_INAMES(:)
real, optional, pointer :: ATTR_RVALUES(:)
integer, optional, pointer :: ATTR_IVALUES(:)
integer, optional, pointer :: UNGRIDDED_DIMS(:)
character(len=*), intent(out), optional :: UNGRIDDED_UNIT
character(len=*), intent(out), optional :: UNGRIDDED_NAME
real, optional, pointer :: UNGRIDDED_COORDS(:)
integer, optional :: FIELD_TYPE
integer, optional :: STAGGERING
integer, optional :: ROTATION
type(ESMF_Grid), intent(out), optional :: GRID
logical, intent(out), optional :: doNotAllocate
logical, intent(out), optional :: alwaysAllocate
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecGetRegular
Source Code
   subroutine MAPL_VarSpecGetRegular(SPEC, SHORT_NAME, LONG_NAME, UNITS,       &
        Dims, VLocation, FIELD, BUNDLE, STATE, &
        NUM_SUBTILES,      &
        STAT, ACCMLT_INTERVAL, COUPLE_INTERVAL,   &
        OFFSET, LABEL, DEFAULT, defaultProvided,  &
        FRIENDLYTO,                               &
        RESTART,                                  &
        HALOWIDTH,                                &
        PRECISION,                                &
        ATTR_RNAMES, ATTR_INAMES,                 &
        ATTR_RVALUES, ATTR_IVALUES,               &
        UNGRIDDED_DIMS,                           &
        UNGRIDDED_UNIT,                          &
        UNGRIDDED_NAME,                          &
        UNGRIDDED_COORDS,                         &
        FIELD_TYPE,                               &
        STAGGERING,                               &
        ROTATION,                                 &
        GRID,                                     &
        doNotAllocate,                            &
        alwaysAllocate,                           &
        RC )
      type (MAPL_VarSpec ),             intent(IN )     :: SPEC
      character(len=*)   , optional   , intent(OUT)     :: SHORT_NAME
      character(len=*)   , optional   , intent(OUT)     :: LONG_NAME
      character(len=*)   , optional   , intent(OUT)     :: UNITS
      integer            , optional   , intent(OUT)     :: DIMS
      integer            , optional   , intent(OUT)     :: VLOCATION
      integer            , optional   , intent(OUT)     :: NUM_SUBTILES
      integer            , optional   , intent(OUT)     :: ACCMLT_INTERVAL
      integer            , optional   , intent(OUT)     :: COUPLE_INTERVAL
      integer            , optional   , intent(OUT)     :: OFFSET
      integer            , optional   , intent(OUT)     :: STAT
      integer            , optional   , intent(OUT)     :: LABEL
      real               , optional   , intent(OUT)     :: DEFAULT
      logical            , optional   , intent(OUT)     :: defaultProvided
      type(ESMF_Field)   , optional   , intent(OUT)     :: FIELD
      type(ESMF_FieldBundle)  , optional   , intent(OUT)     :: BUNDLE
      type(ESMF_State)   , optional   , intent(OUT)     :: STATE
      character(len=*)   , optional   , intent(OUT)     :: FRIENDLYTO
      integer            , optional   , intent(OUT)     :: HALOWIDTH
      integer            , optional   , intent(OUT)     :: PRECISION
      integer            , optional   , intent(OUT)     :: RESTART
      character(len=ESMF_MAXSTR), optional, pointer     :: ATTR_INAMES(:)
      character(len=ESMF_MAXSTR), optional, pointer     :: ATTR_RNAMES(:)
      integer,                    optional, pointer     :: ATTR_IVALUES(:)
      real,                       optional, pointer     :: ATTR_RVALUES(:)
      integer,                    optional, pointer     :: UNGRIDDED_DIMS(:)
      character(len=*)   , optional   , intent(OUT)     :: UNGRIDDED_UNIT
      character(len=*)   , optional   , intent(OUT)     :: UNGRIDDED_NAME
      real,                       optional, pointer     :: UNGRIDDED_COORDS(:)
      integer,                    optional              :: FIELD_TYPE
      integer,                    optional              :: STAGGERING
      integer,                    optional              :: ROTATION
      type(ESMF_Grid)    , optional   , intent(OUT)     :: GRID
      logical            , optional   , intent(OUT)     :: doNotAllocate
      logical            , optional   , intent(OUT)     :: alwaysAllocate
      integer            , optional   , intent(OUT)     :: RC
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      if(present(STAT)) then
         STAT = SPEC%SPECPtr%STAT
      endif
      if(present(SHORT_NAME)) then
         SHORT_NAME = SPEC%SPECPtr%SHORT_NAME
      endif
      if(present(LONG_NAME)) then
         LONG_NAME = SPEC%SPECPtr%LONG_NAME
      endif
      if(present(UNITS)) then
         UNITS = SPEC%SPECPtr%UNITS
      endif
      if(present(FRIENDLYTO)) then
         FRIENDLYTO = SPEC%SPECPtr%FRIENDLYTO
      endif
      if(present(DIMS)) then
         DIMS = SPEC%SPECPtr%DIMS
      endif
      if(present(VLOCATION)) then
         VLOCATION = SPEC%SPECPtr%LOCATION
      endif
      if(present(NUM_SUBTILES)) then
         NUM_SUBTILES = SPEC%SPECPtr%NUM_SUBTILES
      endif
      if(present(ACCMLT_INTERVAL)) then
         ACCMLT_INTERVAL = SPEC%SPECPtr%ACCMLT_INTERVAL
      endif
      if(present(COUPLE_INTERVAL)) then
         COUPLE_INTERVAL = SPEC%SPECPtr%COUPLE_INTERVAL
      endif
      if(present(OFFSET)) then
         OFFSET = SPEC%SPECPtr%OFFSET
      endif
      if(present(LABEL)) then
         LABEL = SPEC%SPECPtr%LABEL
      endif
      if(present(DEFAULT)) then
         DEFAULT = SPEC%SPECPtr%DEFAULT
      endif
      if(present(defaultProvided)) then
         defaultProvided= SPEC%SPECPtr%defaultProvided
      endif
      if(present(FIELD)) then
         FIELD = SPEC%SPECPtr%FIELD
      endif
      if(present(BUNDLE)) then
         BUNDLE = SPEC%SPECPtr%BUNDLE
      endif
      if(present(STATE)) then
         STATE = SPEC%SPECPtr%STATE
      endif
      if(present(HALOWIDTH)) then
         HALOWIDTH = SPEC%SPECPtr%HALOWIDTH
      endif
      if(present(PRECISION)) then
         PRECISION = SPEC%SPECPtr%PRECISION
      endif
      if(present(RESTART)) then
         RESTART = SPEC%SPECPtr%RESTART
      endif
      if(present(ATTR_INAMES)) then
         ATTR_INAMES => SPEC%SPECPtr%ATTR_INAMES
      endif
      if(present(ATTR_RNAMES)) then
         ATTR_RNAMES => SPEC%SPECPtr%ATTR_RNAMES
      endif
      if(present(ATTR_IVALUES)) then
         ATTR_IVALUES => SPEC%SPECPtr%ATTR_IVALUES
      endif
      if(present(ATTR_RVALUES)) then
         ATTR_RVALUES => SPEC%SPECPtr%ATTR_RVALUES
      endif
      if(present(UNGRIDDED_DIMS)) then
         UNGRIDDED_DIMS => SPEC%SPECPtr%UNGRIDDED_DIMS
      endif
      if(present(UNGRIDDED_UNIT)) then
         UNGRIDDED_UNIT = SPEC%SPECPtr%UNGRIDDED_UNIT
      endif
      if(present(UNGRIDDED_NAME)) then
         UNGRIDDED_NAME = SPEC%SPECPtr%UNGRIDDED_NAME
      endif
      if(present(UNGRIDDED_COORDS)) then
         UNGRIDDED_COORDS => SPEC%SPECPtr%UNGRIDDED_COORDS
      endif
      if(present(FIELD_TYPE)) then
         FIELD_TYPE = SPEC%SPECPtr%FIELD_TYPE
      endif
      if(present(STAGGERING)) then
         STAGGERING = SPEC%SPECPtr%STAGGERING
      endif
      if(present(ROTATION)) then
         ROTATION = SPEC%SPECPtr%ROTATION
      endif
      if(present(GRID)) then
         GRID = SPEC%SPECPtr%GRID
      endif
      if(present(doNotAllocate)) then
         doNotAllocate = SPEC%SPECPtr%doNotAllocate
      endif
      if(present(alwaysAllocate)) then
         alwaysAllocate = SPEC%SPECPtr%alwaysAllocate
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecGetRegular
Call graph
mapl_varspecgetregular calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecget calls mapl_varspecgetregular
mapl_wirecomponent calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_cplcompsetvarspecs calls mapl_varspecget
mapl_setvarspecforcc calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_stategetspecattrib calls mapl_varspecget
mapl_stateaddexportspecfrmall calls mapl_varspecget
readrestart calls mapl_varspecget
writerestart calls mapl_varspecget
mapl_terminateimportallbut calls mapl_varspecget
mapl_friendlyget calls mapl_varspecget
test_simple_constructor calls mapl_varspecget
mapl_getnumsubtiles calls mapl_varspecget
mapl_genericspecenum calls mapl_varspecget, mapl_genericspecenum
mapl_stateaddexportspecfrmchld_all calls mapl_varspecget
initialize calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_stateaddinternalspec calls mapl_varspecget
mapl_statecreatefromspecnew calls mapl_varspecget
mapl_labelget calls mapl_varspecget
mapl_varspecreconnect calls mapl_varspecget
mapl_statecreatefromvarspecnew calls mapl_varspecget, mapl_statecreatefromspecnew
mapl_bundleinit calls mapl_varspecget
mapl_readforcingx calls mapl_stategetspecattrib, mapl_getnumsubtiles, mapl_statecreatefromvarspecnew
mapl_addexportspec calls mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld_all
mapl_terminateimport calls mapl_terminateimportallbut
mapl_stategettimestamp calls mapl_stategetspecattrib
mapl_genericinitialize calls mapl_getnumsubtiles
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_statecreatefromspec calls mapl_statecreatefromspecnew