MAPL_ReadForcingX – MAPL
MAPL_ReadForcingX Subroutine
409 statements
Source File
private subroutine MAPL_ReadForcingX(MPL, NAME, DATAFILE, CURRTIME, FORCING1, FORCING2, INIT_ONLY, ON_TILES, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: MPL
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: DATAFILE
type(ESMF_Time), intent(inout) :: CURRTIME
real, intent(out), optional :: FORCING1(:)
real, intent(out), optional :: FORCING2(:,:)
logical, intent(in), optional :: INIT_ONLY
logical, intent(in), optional :: ON_TILES
integer, intent(out), optional :: RC
Calls
MAPL_ReadForcingX w ArrDescrSet
w
w esmf_stateget
w
w ESMF_TimeGet
w
w ESMF_TimeSet
w
w ESMFL_StateGetPointerToData
w
w FREE_FILE
w
w GETFILE
w
w MAPL_Am_I_Root
w
w MAPL_Assert
w
w MAPL_Backspace
w
w MAPL_CommsBcast
w
w MAPL_GenericStateGet
w
w MAPL_GetNumSubtiles
w
w MAPL_GetResource
w
w MAPL_GridGet
w
w MAPL_Interp_Fac
w
w MAPL_LocStreamGet
w
w MAPL_LocStreamTransform
w
w MAPL_PackDateTime
w
w MAPL_Return
w
w MAPL_Skip
w
w MAPL_StateCreateFromVarSpecNew
w
w MAPL_StateGetSpecAttrib
w
w MAPL_StateGetTimeStamp
w
w MAPL_StateSetTimeStamp
w
w MAPL_UnpackDateTime
w
w MAPL_VarRead
w
w MAPL_VarSpecCreateInListNew
w
w MAPL_VarSpecGetIndex
w
w MAPL_Verify
w
w mpi_barrier
w
w mpi_bcast
w
w mpi_comm_rank
w
w mpi_file_close
w
w mpi_file_open
w
w READ_PARALLEL
w
w WRITE_PARALLEL
w
Called by
Source Code
   subroutine MAPL_ReadForcingX(MPL,NAME,DATAFILE,CURRTIME,  &
        FORCING1,FORCING2,INIT_ONLY,ON_TILES,RC )
      type (MAPL_MetaComp),     intent(INOUT)   :: MPL
      character(len=*),         intent(IN   )   :: NAME
      character(len=*),         intent(IN   )   :: DATAFILE
      type (ESMF_Time),         intent(INout)   :: CURRTIME
      real, optional,           intent(  OUT)   :: FORCING1(:)
      real, optional,           intent(  OUT)   :: FORCING2(:,:)
      logical, optional,        intent(IN   )   :: INIT_ONLY
      logical, optional,        intent(IN   )   :: ON_TILES
      integer, optional,        intent(  OUT)   :: RC
      ! ErrLog Variables
      integer                           :: status
      ! Locals
      type (MAPL_LocStream)             :: LOCSTREAM
      type (ESMF_Time)                  :: DATE1
      type (ESMF_Time)                  :: DATEN
      type (ESMF_Calendar)              :: CAL
      type (ESMF_DELayout)              :: LAYOUT
      type (ESMF_Time)                  :: MIDT1
      type (ESMF_Time)                  :: MIDT2
      type (ESMF_Time)                  :: CURRENTTIME
      type (ESMF_Grid)                  :: GRID
      type (ESMF_Field)                 :: FIELD
      real                              :: FAC
      real, pointer                     :: PRE1(:  ), NEX1(:  )
      real, pointer                     :: PRE2(:,:), NEX2(:,:)
      real, pointer                     :: LONS(:,:), VAR2(:,:)
      type(ESMF_TimeInterval)           :: TIMEDIFF
      integer, parameter                :: FILE_HEADER_SIZE=14
      real                              :: REAL_HEADER(FILE_HEADER_SIZE)
      integer                           :: HEADER(FILE_HEADER_SIZE)
      integer                           :: UNIT
      integer                           :: DATE_PREV, YEAR
      logical                           :: USE_INIT_ONLY
      logical                           :: USE_ON_TILES
      logical                           :: TRANSFORM
      logical                           :: ONED
      logical                           :: CLIMATOLOGY
      integer                           :: YY, MM, DD
      integer                           :: H, M, S
      integer                           :: NSUBTILES
      integer                           :: L1, L2
      type(ESMF_Grid)                   :: TILEGRID
      integer                           :: datetime(2)
      logical                           :: FileExists
      logical                           :: AM_I_Root_
      character(len=ESMF_MAXSTR)        :: FNAME
      type (ESMF_StateItem_Flag)        :: itemType
      ! Process arguments
      !------------------
      if(present(INIT_ONLY)) then
         USE_INIT_ONLY = INIT_ONLY
      else
         USE_INIT_ONLY = .false.
      end if
      if(present(ON_TILES)) then
         USE_ON_TILES = ON_TILES
      else
         USE_ON_TILES = .false.
      end if
      if    (present(FORCING1)) then
         ONED = .TRUE.
      elseif(present(FORCING2)) then
         ONED = .FALSE.
      else
         _FAIL('needs informative message')
      end if
      ! Get parameters from generic state.
      !-----------------------------------
      call MAPL_GenericStateGet(MPL,             &
           LOCSTREAM=LOCSTREAM,                    &
           LONS=LONS,                              &
           LAYOUT=LAYOUT,                          &
           RC=status )
      _VERIFY(status)
      ! Get the calendar from the current time
      !---------------------------------------
      call ESMF_TimeGet(CurrTime, calendar=cal, rc=status)
      _VERIFY(status)
      ! Scratch space for reading data files
      !-------------------------------------
      TRANSFORM = ONED .and. .not.USE_ON_TILES
      if(TRANSFORM) then
         allocate(VAR2(size(LONS,1),size(LONS,2)),STAT=status)
         _VERIFY(status)
      end if
      ! Get the grid form generic state
      !-------------------------------------------------------
      GRID=MPL%GRID%ESMFGRID
      ! Check if FRCSTATE already has previous and next vars. If not, create them
      !---------------------------------------------------------------------------
      call ESMF_StateGet(MPL%FORCING, trim(NAME)//'_PREV', itemType=itemType, RC=status)
      _VERIFY(status)
      if (itemType == ESMF_STATEITEM_FIELD) then
         call ESMF_StateGet(MPL%FORCING, trim(NAME)//'_PREV', FIELD, RC=status)
         _VERIFY(status)
      else
         if(ONED) then
            NSUBTILES = MAPL_GetNumSubtiles(MPL, RC=status)
            _VERIFY(status)
            call MAPL_LocStreamGet(MPL%LocStream, TILEGRID=TILEGRID, RC=status)
            _VERIFY(status)
            ! create a spec
            call MAPL_VarSpecCreateInListNew(MPL%COMPONENT_SPEC%FORCING,                   &
                 SHORT_NAME = trim(NAME) // '_PREV',                       &
                 LONG_NAME  = 'previous value of ' // trim(NAME),          &
                 NUM_SUBTILES=NSUBTILES,                                   &
                 DIMS       = MAPL_DimsTileOnly,                           &
                 VLOCATION  = MAPL_VLocationNone,                          &
                 COUPLE_INTERVAL = -1,                                     & ! time not set
                 RC=status  )
            _VERIFY(status)
            call MAPL_VarSpecCreateInListNew(MPL%COMPONENT_SPEC%FORCING,                   &
                 SHORT_NAME = trim(NAME) // '_NEXT',                       &
                 LONG_NAME  = 'next value of ' // trim(NAME),              &
                 NUM_SUBTILES=NSUBTILES,                                   &
                 DIMS       = MAPL_DimsTileOnly,                           &
                 VLOCATION  = MAPL_VLocationNone,                          &
                 COUPLE_INTERVAL = -1,                                     & ! time not set
                 RC=status  )
            _VERIFY(status)
            L1 = MAPL_VarSpecGetIndex(MPL%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS,trim(NAME)//'_PREV')
            L2 = MAPL_VarSpecGetIndex(MPL%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS,trim(NAME)//'_NEXT')
            _ASSERT(L2==L1+1,'needs informative message')
            ! create field and put it in FRCSTATE
            call MAPL_StateCreateFromVarSpecNew(MPL%FORCING,MPL%COMPONENT_SPEC%FORCING, &
                 GRID,TILEGRID=TILEGRID,range=[L1,L2],RC=status)
            _VERIFY(status)
         else
            call MAPL_VarSpecCreateInListNew(MPL%COMPONENT_SPEC%FORCING,                   &
                 SHORT_NAME = trim(NAME) // '_PREV',                       &
                 LONG_NAME  = 'previous value of ' // trim(NAME),          &
                 DIMS       = MAPL_DimsHorzOnly,                           &
                 VLOCATION  = MAPL_VLocationNone,                          &
                 COUPLE_INTERVAL = -1,                                     & ! time not set
                 RC=status  )
            _VERIFY(status)
            call MAPL_VarSpecCreateInListNew(MPL%COMPONENT_SPEC%FORCING,                   &
                 SHORT_NAME = trim(NAME) // '_NEXT',                       &
                 LONG_NAME  = 'next value of ' // trim(NAME),              &
                 DIMS       = MAPL_DimsHorzOnly,                           &
                 VLOCATION  = MAPL_VLocationNone,                          &
                 COUPLE_INTERVAL = -1,                                     & ! time not set
                 RC=status  )
            _VERIFY(status)
            L1 = MAPL_VarSpecGetIndex(MPL%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS,trim(NAME)//'_PREV')
            L2 = MAPL_VarSpecGetIndex(MPL%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS,trim(NAME)//'_NEXT')
            _ASSERT(L2==L1+1,'needs informative message')
            ! create field and put it in FRCSTATE
            call MAPL_StateCreateFromVarSpecNew(MPL%FORCING,MPL%COMPONENT_SPEC%FORCING, &
                 GRID, range=[L1,L2],RC=status)
            _VERIFY(status)
         end if
      end if
      ! Get pointers to the endpoints in the forcing state
      !----------------------------------------------------
      if(ONED) then
         call GET_POINTER(MPL%FORCING, PRE1, trim(NAME)//'_PREV', RC=status)
         _VERIFY(status)
         call GET_POINTER(MPL%FORCING, NEX1, trim(NAME)//'_NEXT', RC=status)
         _VERIFY(status)
      else
         call GET_POINTER(MPL%FORCING, PRE2, trim(NAME)//'_PREV', RC=status)
         _VERIFY(status)
         call GET_POINTER(MPL%FORCING, NEX2, trim(NAME)//'_NEXT', RC=status)
         _VERIFY(status)
      end if
      ! Set time endpoints. These are 0000-01-01:000000 if uninitialized
      !----------------------------------------------------
      call MAPL_StateGetTimeStamp(MPL,trim(NAME)//'_NEXT',MIDT2, RC=status )
      _VERIFY(status)
      call MAPL_StateGetTimeStamp(MPL,trim(NAME)//'_PREV',MIDT1, RC=status )
      _VERIFY(status)
      ! Check if the input file is a climatology
      !-----------------------------------------
      call MAPL_StateGetSpecAttrib(MPL,trim(NAME)//'_PREV',forcing=.true., &
           REFRESH_INTERVAL=DATE_PREV, rc=status)
      _VERIFY(status)
      if ( DATE_PREV < 0 ) then
         UNIT=GETFILE(DATAFILE,form='unformatted', rc=status)
         _VERIFY(status)
         call READ_PARALLEL(LAYOUT, REAL_HEADER, unit=UNIT, rc=status)
         _VERIFY(status)
         HEADER = nint(REAL_HEADER)
         call MAPL_BACKSPACE(UNIT,LAYOUT,RC=status)
         _VERIFY(status)
         CLIMATOLOGY = HEADER(1)<3
      else
         call ESMF_TimeGet(MIDT1, YY=YEAR, rc=status)
         _VERIFY(status)
         CLIMATOLOGY = YEAR < 3
      end if
      ! Make a local copy of the current time
      !--------------------------------------
      !ALT clock are shallow objects!    CurrentTime = CurrTime
      call ESMF_TimeGet(CurrTime, &
           YY=YY, MM=MM, DD=DD, &
           H=H, M=M, S=S, rc=status)
      _VERIFY(status)
      if(CLIMATOLOGY) then
         YY = 1
         !ALT: In Climatology mode we should not have leap year
         !     so if the date is Feb.29, move it to Feb.28
         if (MM==2 .and. DD==29) DD=28
      end if
      call ESMF_TimeSet(CurrentTime, &
           YY=YY, MM=MM, DD=DD, &
           H=H, M=M, S=S, rc=status)
      _VERIFY(status)
      AM_I_Root_ = MAPL_AM_I_Root(layout)
      ! Make sure current time is between the current endpoints;
      !  if not, refresh endpoints. This also works initially.
      !-------------------------------------------------------
      if (CurrentTime < MIDT1 .or. CurrentTime > MIDT2) then
         call UPDATE_ENDPOINTS
         _VERIFY(status)
      endif
      ! Interpolate ocean and ice temp and ice fraction
      !   and update the forcing state on the tile grid.
      !--------------------------------------------------
      if(USE_INIT_ONLY) then
         FAC=1.0
      else
         call MAPL_Interp_Fac (CurrentTime,MIDT1,MIDT2,FAC,RC=status )
         _VERIFY(status)
      end if
      _ASSERT(FAC >= 0.0,'needs informative message')
      _ASSERT(FAC <= 1.0,'needs informative message')
      !  Update the friendly skin values
      !---------------------------------
      if(ONED) then
         FORCING1 = MAPL_UNDEF
         where(PRE1/=MAPL_UNDEF .and. NEX1/=MAPL_UNDEF)
            FORCING1 = FAC * PRE1  +  (1.0-FAC) * NEX1
         end where
         where(PRE1==MAPL_UNDEF .and. NEX1/=MAPL_UNDEF)
            FORCING1 = NEX1
         end where
         where(PRE1/=MAPL_UNDEF .and. NEX1==MAPL_UNDEF)
            FORCING1 = PRE1
         end where
      else
         FORCING2 = MAPL_UNDEF
         where(PRE2/=MAPL_UNDEF .and. NEX2/=MAPL_UNDEF)
            FORCING2 = FAC * PRE2  +  (1.0-FAC) * NEX2
         end where
         where(PRE2==MAPL_UNDEF .and. NEX2/=MAPL_UNDEF)
            FORCING2 = NEX2
         end where
         where(PRE2/=MAPL_UNDEF .and. NEX2==MAPL_UNDEF)
            FORCING2 = PRE2
         end where
      end if
      if(TRANSFORM) deallocate(VAR2)
      !  All done
      !-----------
      _RETURN(ESMF_SUCCESS)
   contains
      subroutine UPDATE_ENDPOINTS
         logical :: DataAlreadyRead
         ! Get the previous date
         !----------------------
         call MAPL_StateGetSpecAttrib(MPL,trim(NAME)//'_PREV',forcing=.true., &
              REFRESH_INTERVAL=DATE_PREV, rc=status)
         _VERIFY(status)
         DataAlreadyRead = .not. (DATE_PREV < 0)
         ! In forecast mode (init_only=.true.) we ready only once!
         !-------------------------------------------------------
         if (use_init_only) then
            if (DataAlreadyRead) return
            ! check if a bcs_restart file exists
            ! if YES, use its content to overwrite current clock
            if (AM_I_Root_) then
               call MAPL_GetResource( MPL, FNAME, 'BCS_RESTART:', &
                    default='bcs_restart', rc = status )
               _VERIFY(status)
               inquire(FILE = FNAME, EXIST=FileExists)
               if (FileExists) then
                  UNIT = GETFILE ( FNAME, form="formatted", rc=status )
                  _VERIFY(status)
                  read(UNIT,'(i8.8,1x,i6.6)',iostat=status) datetime
                  _VERIFY(status)
                  call FREE_FILE(UNIT)
               else
                  call MAPL_PackDateTime(DATETIME, YY, MM, DD, H, M, S)
                  !write bcs checkpoint
                  UNIT = GETFILE ( FNAME, form="formatted", rc=status )
                  _VERIFY(status)
                  write(UNIT,'(i8.8,1x,i6.6)',iostat=status) datetime
                  _VERIFY(status)
                  call FREE_FILE(UNIT)
               end if
            end if
            call MAPL_CommsBcast(layout, datetime, n=2, ROOT=MAPL_Root, rc=status)
            _VERIFY(status)
            CALL MAPL_UnpackDateTime(DATETIME, YY, MM, DD, H, M, S)
            call ESMF_TimeSet(CurrentTime, &
                 YY=YY, MM=MM, DD=DD, &
                 H=H, M=M, S=S, rc=status)
            _VERIFY(status)
         end if
         ! Get forcing fortran unit
         !-------------------------
         UNIT=GETFILE(DATAFILE,form='unformatted',all_pes=.true.)
         ! Check to see if forcing state buffers have been initialized
         !-------------------------------------------------------------
         if ( DATE_PREV < 0 .or. CLIMATOLOGY .or. CurrentTime < MIDT1 .or. CurrentTime > MIDT2 ) then
            ! If not, initialize them, by looping until correct times are found
            !-----------------------------------------------------------------
            if(AM_I_ROOT_) then
               rewind(UNIT, iostat=status)
               _VERIFY(status)
               do
                  read(UNIT, iostat=status) REAL_HEADER
                  _VERIFY(status)
                  HEADER = nint(REAL_HEADER)
                  call ESMF_TimeSet(DATEN, &
                       YY=HEADER(7), MM=HEADER(8), DD=HEADER(9), &
                       H=HEADER(10), M=HEADER(11), S=HEADER(12), &
                       calendar=cal, rc=status)
                  _VERIFY(status)
                  ! If the current time is beyond the item's final time, skip it.
                  !--------------------------------------------------------------
                  if (DATEN < CurrentTime) then
                     read(UNIT, iostat=status)
                     _VERIFY(status)
                     cycle
                  else
                     backspace (UNIT, iostat=status)
                     _VERIFY(status)
                     exit
                  end if
               end do
            end if
            ! We have found an interval that contains Current. Now get its initial time
            !--------------------------------------------------------------------------
            call READ_PARALLEL(Layout, REAL_HEADER, unit=UNIT, rc=status)
            _VERIFY(status)
            HEADER = nint(REAL_HEADER)
            call ESMF_TimeSet(DATEN, &
                 YY=HEADER(7), MM=HEADER(8), DD=HEADER(9), &
                 H=HEADER(10), M=HEADER(11), S=HEADER(12), &
                 calendar=cal, rc=status)
            _VERIFY(status)
            call ESMF_TimeSet(DATE1, &
                 YY=HEADER(1), MM=HEADER(2), DD=HEADER(3), &
                 H =HEADER(4), M =HEADER(5), S =HEADER(6), &
                 calendar=cal, rc=status)
            _VERIFY(status)
            ! compute its central time
            !-------------------------
            TimeDiff=DATEN-DATE1
            MIDT2=DATE1 + TimeDiff/2.0D0
            if(MIDT2<=CurrentTime .or. use_init_only) then ! The item we found is PREV
               MIDT1 = MIDT2
               call WRITE_PARALLEL("Previous time for"//trim(NAME)//"s is:", RC=status)
               _VERIFY(status)
               call WRITE_PARALLEL(HEADER(1:12), RC=status)
               _VERIFY(status)
               ! Read PREV
               !----------
               call READIT('_PREV')
               call MAPL_StateSetTimeStamp(MPL,trim(NAME)//'_PREV',MIDT1, RC=status )
               _VERIFY(status)
               if (use_init_only) then
                  if(ONED) then
                     NEX1   = PRE1
                  else
                     NEX2   = PRE2
                  end if
                  return
               end if
               ! Read the header for NEXT
               !-------------------------
               call READ_PARALLEL(Layout, REAL_HEADER, unit=UNIT, rc=status)
               _VERIFY(status)
               HEADER = nint(REAL_HEADER)
               ! Get NEXT's initial and final times
               !-----------------------------------
               call ESMF_TimeSet(DATEN, &
                    YY=HEADER(7), MM=HEADER(8), DD=HEADER(9), &
                    H=HEADER(10), M=HEADER(11), S=HEADER(12), &
                    calendar=cal, rc=status)
               _VERIFY(status)
               call ESMF_TimeSet(DATE1, &
                    YY=HEADER(1), MM=HEADER(2), DD=HEADER(3), &
                    H =HEADER(4), M =HEADER(5), S =HEADER(6), &
                    calendar=cal, rc=status)
               _VERIFY(status)
               ! compute its central time
               !-------------------------
               TimeDiff=DATEN-DATE1
               MIDT2=DATE1 + TimeDiff/2.0D0
               ! and read NEXT
               !--------------
               call READIT('_NEXT')
               _VERIFY(status)
               call MAPL_StateSetTimeStamp(MPL,trim(NAME)//'_NEXT',MIDT2, RC=status )
               _VERIFY(status)
            else
               ! Read NEXT
               !----------
               call READIT('_NEXT')
               _VERIFY(status)
               call MAPL_StateSetTimeStamp(MPL,trim(NAME)//'_NEXT',MIDT2, RC=status )
               _VERIFY(status)
               ! Back up to get PREV
               !--------------------
               call MAPL_Backspace(UNIT, LAYOUT, COUNT=4, RC=status); _VERIFY(status)
               ! Read the header of PREV item
               !-----------------------------
               call READ_PARALLEL(Layout, REAL_HEADER, unit=UNIT, rc=status)
               _VERIFY(status)
               HEADER = nint(REAL_HEADER)
               ! Get the item's initial and final times
               !---------------------------------------
               call ESMF_TimeSet(DATEN, &
                    YY=HEADER(7), MM=HEADER(8), DD=HEADER(9), &
                    H=HEADER(10), M=HEADER(11), S=HEADER(12), &
                    calendar=cal, rc=status)
               _VERIFY(status)
               call ESMF_TimeSet(DATE1, &
                    YY=HEADER(1), MM=HEADER(2), DD=HEADER(3), &
                    H =HEADER(4), M =HEADER(5), S =HEADER(6), &
                    calendar=cal, rc=status)
               _VERIFY(status)
               ! compute its central time
               !-------------------------
               TimeDiff=DATEN-DATE1
               MIDT1=DATE1 + TimeDiff/2.0D0
               ! Read PREV
               !----------
               call READIT('_PREV')
               _VERIFY(status)
               call MAPL_StateSetTimeStamp(MPL,trim(NAME)//'_PREV',MIDT1, RC=status )
               _VERIFY(status)
               ! Skip over NEXT to be positioned for subsequent reads
               !-----------------------------------------------------
               call MAPL_Skip(UNIT, LAYOUT, COUNT=2, RC=status ); _VERIFY(status)
            end if
         elseif(.not.use_init_only) then ! Just need to update NEXT,  PREV is old NEXT
            if(ONED) then
               PRE1   = NEX1
            else
               PRE2   = NEX2
            end if
            MIDT1  = MIDT2
            ! Move time stamp from NEXT to PREV
            !------------------------------------------
            call MAPL_StateGetTimeStamp(MPL,trim(NAME)//'_NEXT',MIDT2, RC=status )
            _VERIFY(status)
            call MAPL_StateSetTimeStamp(MPL,trim(NAME)//'_PREV',MIDT2, RC=status )
            _VERIFY(status)
            ! Read the header of next item
            !-----------------------------
            call READ_PARALLEL(Layout, REAL_HEADER, unit=UNIT, rc=status)
            _VERIFY(status)
            HEADER = nint(REAL_HEADER)
            ! Get the item's initial and final time
            !--------------------------------------
            call ESMF_TimeSet(DATE1, &
                 YY=HEADER(1), MM=HEADER(2), DD=HEADER(3), &
                 H =HEADER(4), M =HEADER(5), S =HEADER(6), &
                 calendar=cal, rc=status)
            _VERIFY(status)
            call ESMF_TimeSet(DATEN, &
                 YY=HEADER(7), MM=HEADER(8), DD=HEADER(9), &
                 H =HEADER(10),M =HEADER(11),S =HEADER(12),&
                 calendar=cal, rc=status)
            _VERIFY(status)
            TimeDiff=DATEN-DATE1
            MIDT2=DATE1 + TimeDiff/2.0D0
            ! Verify that it is the next item
            !--------------------------------
            _ASSERT(MIDT2 >= CurrentTime,'needs informative message')
            ! Read NEXT
            !----------
            call READIT('_NEXT')
            _VERIFY(status)
            call MAPL_StateSetTimeStamp(MPL,trim(NAME)//'_NEXT',MIDT2, RC=status )
            _VERIFY(status)
         endif
      end subroutine UPDATE_ENDPOINTS
      subroutine READIT(WHICH)
         character(len=5), intent(IN) :: WHICH
         real, pointer :: VAR1(:)
         integer       :: PRF
         integer       :: MUNIT
         integer       :: io_rank
         integer(kind=MPI_OFFSET_KIND)         :: offset
         logical       :: AmReader
         type(ArrDescr):: ArrDes
         integer(kind=MPI_OFFSET_KIND)         :: _FTELL
#ifndef __GFORTRAN__
         external      :: _FTELL
#endif
         type(ESMF_Grid) :: TILEGRID
         integer       :: COUNTS(2)
         call MAPL_GetResource( MPL, PRF, 'PARALLEL_READFORCING:', default=0, rc = status )
         _VERIFY(status)
         MUNIT = 0 ! to avoid un-init problems
         AmReader = .false.
         if (PRF /= 0) then
            AmReader = mpl%grid%readers_comm /= MPI_COMM_NULL
            if (use_ON_TILES) then
               call MAPL_LocStreamGet(LocStream, TILEGRID=TILEGRID, RC=status)
               _VERIFY(status)
               call MAPL_GridGet(TILEGRID, globalCellCountPerDim=COUNTS, RC=status)
               _VERIFY(status)
               call ArrDescrSet(arrdes,                     &
                    readers_comm  = mpl%grid%readers_comm,  &
                    ioscattercomm = mpl%grid%comm,          &
                    i1 = mpl%grid%i1, in = mpl%grid%in,     &
                    j1 = mpl%grid%j1, jn = mpl%grid%jn,     &
                    im_world = COUNTS(1),                   &
                    jm_world = COUNTS(2)                  )
            else
               call ArrDescrSet(arrdes,                     &
                    readers_comm  = mpl%grid%readers_comm,  &
                    ioscattercomm = mpl%grid%ioscattercomm, &
                    i1 = mpl%grid%i1, in = mpl%grid%in,     &
                    j1 = mpl%grid%j1, jn = mpl%grid%jn,     &
                    im_world = mpl%grid%im_world,           &
                    jm_world = mpl%grid%jm_world)
            endif
            arrdes%Ycomm = mpl%grid%Ycomm
            if (AmReader) then
               call MPI_COMM_RANK(mpl%grid%readers_comm, io_rank, status)
               _VERIFY(status)
               if (io_rank == 0) then
                  print *,'Using parallel IO for reading file: ',trim(DATAFILE)
#ifdef __NAG_COMPILER_RELEASE
                  _FAIL('NAG does not provide ftell. Convert to stream I/O')
#else
                  offset = _FTELL(UNIT)+4
#endif
                  ! MAT: Here we help protect against use of the 32-bit
                  !      ftell from the macro at top. If we read a file
                  !      > 2 gb, ftell returns a negative number, so
                  !      offset will be less than 4.
                  _ASSERT(offset >= 4,'needs informative message')
               end if
               !ALT: disclaimer
               ! This code assumes the reader with i0_rank == 0 is also Root in the Components VM
               ! This is the only processor that actually could check the offset in the file
               call MPI_Bcast(offset, 1, MPI_INTEGER8, 0, mpl%grid%readers_comm, status)
               _VERIFY(status)
               call ArrDescrSet(arrdes, offset)
               call MPI_Barrier(mpl%grid%readers_comm, status)
               _VERIFY(status)
               call MPI_FILE_OPEN(mpl%grid%readers_comm, DATAFILE, MPI_MODE_RDONLY, &
                    MPI_INFO_NULL, MUNIT, status)
               _VERIFY(status)
               call MPI_Barrier(mpl%grid%readers_comm, status)
               _VERIFY(status)
            end if
         end if
         if(TRANSFORM) then
            if (PRF /= 0) then
               _FAIL('needs informative message') ! for now
            else
               ! ALT this LOOKS WRONG. MAPL_VarRead needs a mask for tiles!
               call MAPL_VarRead(UNIT, GRID, VAR2, RC=status )
               _VERIFY(status)
            end if
            call GET_POINTER(MPL%FORCING, VAR1, trim(NAME)//WHICH, RC=status)
            _VERIFY(status)
            call MAPL_LocStreamTransform(LOCSTREAM, VAR1, VAR2, interp=.true.,RC=status )
            _VERIFY(status)
         else
            if (PRF /= 0) then
               call MAPL_VarRead(UNIT=MUNIT, STATE=MPL%FORCING, NAME=trim(NAME)//WHICH, &
                    arrdes=arrdes, RC=status)
               _VERIFY(status)
            else
               call MAPL_VarRead(UNIT, MPL%FORCING, trim(NAME)//WHICH, RC=status)
               _VERIFY(status)
            end if
         end if
         if (AmReader) then
            ! we need to advance the file pointer properly (to the end of the current record) on root
            ! by using a blank Fortran read
            if (io_rank == 0) then
               read(UNIT, iostat=status)
               _VERIFY(status)
            end if
            call MPI_Barrier(mpl%grid%readers_comm, status)
            _VERIFY(status)
            call MPI_FILE_CLOSE(MUNIT, status)
            _VERIFY(status)
            call MPI_Barrier(mpl%grid%readers_comm, status)
            _VERIFY(status)
         endif
      end subroutine READIT
   end subroutine MAPL_READFORCINGX
Call graph
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2