MAPL_GetImsJms – MAPL
MAPL_GetImsJms Subroutine
51 statements
Source File
public subroutine MAPL_GetImsJms(Imins, Imaxs, Jmins, Jmaxs, Ims, Jms, rc)
Uses
MAPL_SortMod
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: Imins
integer, intent(in), dimension(:) :: Imaxs
integer, intent(in), dimension(:) :: Jmins
integer, intent(in), dimension(:) :: Jmaxs
integer, pointer :: Ims(:)
integer, pointer :: Jms(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_GetImsJms(Imins,Imaxs,Jmins,Jmaxs,Ims,Jms,rc)
!  Given lists of the min and max Is and Js in each processor
!  in a rectangular layout, it computes the number of elements
!  in each of the I columns and the number in each of the j
!  rows of the layout. Pointers Ims and Jms are allocated with the i and j
!  sizes of the layout (nx and ny) and filled with the IMs and JMs.
!  The four input lists must be in the same order, but the order
!  is arbitrary. Nx and Ny can be obtained from the sizes of
!  Ims and Jms, respectively
    use MAPL_SortMod
    integer, dimension(:), intent(IN   ) :: Imins,Imaxs,Jmins,Jmaxs
    integer, pointer                     :: Ims(:),Jms(:)
    integer, optional,   intent(out) :: rc
    integer              :: nx, ny, nx0, ny0, nde, k
    integer, allocatable :: Im0(:), Jm0(:)
    integer              :: minI,minJ ! in case the starting index is zero
    integer              :: status
    _ASSERT(.not.associated(Ims), 'Ims is associated and should not be.')
    _ASSERT(.not.associated(Jms), 'Jms is associated and should not be.')
!   The original minI and minJ are assumed to be 1
!   The index of EASE grid  is starting from 0
    minI = minval(Imins,DIM=1)
    minJ = minval(Jmins,DIM=1)
    nx = count(Jmins==minJ)
    ny = count(Imins==minI)
    allocate(Ims(nx),Jms(ny), __STAT__)
    allocate(Im0(nx),Jm0(ny), __STAT__)
    nde = size(Imins)
    nx0 = 1
    ny0 = 1
    do k=1,nde
       if(Imins(k)==minI) then
          Jms(ny0) = Jmaxs(k)-Jmins(k) + 1
          Jm0(ny0) = Jmins(k)
          if(ny0==ny) then
             exit
          else
             ny0 = ny0 + 1
          end if
       end if
    end do
    do k=1,nde
       if(Jmins(k)==minJ) then
          Ims(nx0) = Imaxs(k)-Imins(k) + 1
          Im0(nx0) = Imins(k)
          if(nx0==nx) then
             exit
          else
             nx0 = nx0 + 1
          end if
       end if
    end do
    call MAPL_Sort(Im0,Ims)
    call MAPL_Sort(Jm0,Jms)
    deallocate(Im0,Jm0,__STAT__)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_GetImsJms
Call graph
mapl_getimsjms calls mapl_assert, mapl_sort, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_sort calls sort1ld, sort1lr, sort1ls, sort1sd, sort1sr, sort1ss, sort2al, sort2as, sort2ld, sort2lr, sort2ls, sort2sd, sort2sr, sort2ss
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
sort1ld calls qsortl
sort1lr calls qsortl
sort1ls calls qsortl
sort1sd calls qsorts
sort1sr calls qsorts
sort1ss calls qsorts
sort2al calls mapl_assert, qsortl
sort2as calls mapl_assert, qsorts
sort2ld calls mapl_assert, qsortl
sort2lr calls mapl_assert, qsortl
sort2ls calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort2sr calls mapl_assert, qsorts
sort2ss calls mapl_assert, qsorts
esmfl_halo_r4_2d calls mapl_getimsjms
get_esmf_grid_layout calls mapl_getimsjms
mapl_genericinitialize calls mapl_getimsjms
mapl_gridgetsection calls mapl_getimsjms
set calls mapl_getimsjms
esmfl_halo calls esmfl_halo_r4_2d
create_subobjects calls set
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize, mapl_gridcreate
latlon_zmean calls get_esmf_grid_layout
mapl_gridcreate calls set
activate_threading calls create_subobjects
latlon_zstar calls latlon_zmean
mapl_locstreamtransformg2t calls esmfl_halo
mapl_locstreamtransform calls mapl_locstreamtransformg2t
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t
omp_driver calls activate_threading
time_ave calls latlon_zstar