MAPL_AddMethod – MAPL
MAPL_AddMethod Function
26 statements
Source File
private function MAPL_AddMethod(PHASE, rc)
Arguments
Type Intent Optional Attributes Name
integer, pointer :: PHASE(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function MAPL_AddMethod(PHASE, RC)
      integer, pointer               :: PHASE(:)
      integer, optional, intent(out) :: rc
      integer :: I
      integer, pointer :: tmp(:)
      integer :: status
      character(len=ESMF_MAXSTR), parameter :: Iam="MAPL_AddMethod"
      MAPL_AddMethod = MAPL_FirstPhase
      if (.not.associated(PHASE)) then
         ! this is the method to be added
         I = 1
         allocate(PHASE(I), stat=status)
         _VERIFY(status)
         PHASE(I) = MAPL_AddMethod
      else
         I = size(PHASE) + 1
         allocate(TMP(I), stat=status)
         _VERIFY(status)
         TMP(1:I-1) = PHASE
         TMP(I) = TMP(I-1)+1
         deallocate(PHASE)
         PHASE => TMP
      end if
      MAPL_AddMethod = PHASE(I)
      _RETURN(ESMF_SUCCESS)
   end function MAPL_AddMethod
Call graph
mapl_addmethod calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_gridcompsetentrypoint calls mapl_addmethod
mapl_genericsetservices calls mapl_gridcompsetentrypoint
setservices calls mapl_gridcompsetentrypoint, mapl_genericsetservices