MAPL_GridCompGetVarSpecs – MAPL
MAPL_GridCompGetVarSpecs Subroutine
20 statements
Source File
private subroutine MAPL_GridCompGetVarSpecs(GC, IMPORT, EXPORT, INTERNAL, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_VarSpec), optional, pointer :: IMPORT(:)
type(MAPL_VarSpec), optional, pointer :: EXPORT(:)
type(MAPL_VarSpec), optional, pointer :: INTERNAL(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_GridCompGetVarSpecs(GC,IMPORT,EXPORT,INTERNAL,RC)
      ! !ARGUMENTS:
      type(ESMF_GridComp),    intent(INOUT)  :: GC
      type(MAPL_VarSpec ), pointer, optional :: IMPORT(:)
      type(MAPL_VarSpec ), pointer, optional :: EXPORT(:)
      type(MAPL_VarSpec ), pointer, optional :: INTERNAL(:)
      integer,             optional, intent(OUT) :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)            :: IAm='MAPL_GridCompGetVarSpec'
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      type (MAPL_MetaComp ), pointer        :: STATE
      ! Begin
      ! Get my name and set-up traceback handle
      ! ---------------------------------------
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      ! Get the private state
      ! ---------------------
      call MAPL_InternalStateRetrieve ( GC, STATE, RC=status )
      _VERIFY(status)
      ! Get the specs for the 3 ESMF states
      ! -----------------------------------
      call MAPL_StateGetVarSpecs(STATE,IMPORT,EXPORT,INTERNAL,RC=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GridCompGetVarSpecs
Call graph
mapl_gridcompgetvarspecs calls ESMF_GridCompGet, mapl_internalstateretrieve, mapl_return, mapl_stategetvarspecs, mapl_verify
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_stategetvarspecs calls mapl_return
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_internalstatecreate calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_childaddattribtoimportspec calls mapl_gridcompgetvarspecs
mapl_genericsetservices calls mapl_gridcompgetvarspecs, mapl_wirecomponent
mapl_setvarspecforcc calls mapl_gridcompgetvarspecs
mapl_stateaddexportspecfrmall calls mapl_gridcompgetvarspecs
mapl_stateaddexportspecfrmchld_all calls mapl_gridcompgetvarspecs
mapl_stateaddimportspecfrmchld calls mapl_gridcompgetvarspecs
mapl_wirecomponent calls mapl_gridcompgetvarspecs
mapl_addexportspec calls mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld_all
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
setservices calls mapl_genericsetservices, mapl_addexportspec
addnewspec calls mapl_addexportspec, mapl_addimportspec
addstate calls addnewspec