MAPL_AllocateShared_2DR8 – MAPL
MAPL_AllocateShared_2DR8 Module Procedure
16 statements
Source File
module procedure MAPL_AllocateShared_2DR8 module subroutine MAPL_AllocateShared_2DR8(Ptr, Shp, lbd, TransRoot, rc) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), pointer :: Ptr(:,:)
integer, intent(in) :: Shp(2)
integer, intent(in), optional :: lbd(2)
logical, intent(in) :: TransRoot
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_allocateshared_2dr8 calls mapl_allocnodearray, mapl_verify, mapl_return, mapl_allocateshared_2dr8
mapl_allocnodearray calls mapl_allocnodearray_2dr4, mapl_allocnodearray_3dr4, mapl_allocnodearray_4dr4, mapl_allocnodearray_6dr8, mapl_allocnodearray_3dr8, mapl_allocnodearray_1dl4, mapl_allocnodearray_4dr8, mapl_allocnodearray_5dr8, mapl_allocnodearray_3di4, mapl_allocnodearray_1di4, mapl_allocnodearray_4di4, mapl_allocnodearray_2di4, mapl_allocnodearray_1dr4, mapl_allocnodearray_1dr8, mapl_allocnodearray_2dr8
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_allocateshared calls mapl_allocateshared_2dr8
add_horz_coordinates_from_file calls mapl_allocateshared
mapl_locstreamcreatefromfile calls mapl_allocateshared
mapl_cfiocreatefrombundle calls mapl_allocateshared
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle