MAPL_Reconnect – MAPL
MAPL_Reconnect Subroutine
19 statements
Source File
private recursive subroutine MAPL_Reconnect(STATE, GC_FROM, STATETYPE_FROM, SPECINDEX_FROM, GC_TO, STATETYPE_TO, SPECINDEX_TO, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp) :: STATE
type(ESMF_GridComp), intent(in) :: GC_FROM
integer, intent(in) :: STATETYPE_FROM
integer, intent(in) :: SPECINDEX_FROM
type(ESMF_GridComp), intent(in) :: GC_TO
integer, intent(in) :: STATETYPE_TO
integer, intent(in) :: SPECINDEX_TO
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   recursive subroutine MAPL_Reconnect(STATE,              &
        GC_FROM, STATETYPE_FROM, SPECINDEX_FROM, &
        GC_TO,   STATETYPE_TO,   SPECINDEX_TO,   &
        RC )
      type (MAPL_MetaComp)                       :: STATE
      type(ESMF_GridComp),        intent(IN   )  :: GC_FROM
      integer,                    intent(IN   )  :: STATETYPE_FROM
      integer,                    intent(IN   )  :: SPECINDEX_FROM
      type(ESMF_GridComp),        intent(IN   )  :: GC_TO
      integer,                    intent(IN   )  :: STATETYPE_TO
      integer,                    intent(IN   )  :: SPECINDEX_TO
      integer,          optional, intent(  OUT)  :: RC     ! Error code:
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_Reconnect"
      integer                               :: status
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),          pointer  :: PSTATE
      ! Retrieve the pointer to the internal state of Root.
      ! ----------------------------------------------------
      call MAPL_InternalStateRetrieve ( STATE%RootGC, PSTATE, RC=status )
      _VERIFY(status)
      call MAPL_LinkCreate(PSTATE%LINK,              &
           GC_FROM, STATETYPE_FROM, SPECINDEX_FROM, &
           GC_TO,   STATETYPE_TO,   SPECINDEX_TO,   &
           RC=status )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_Reconnect
Call graph
mapl_reconnect calls mapl_internalstateretrieve, mapl_linkcreate, mapl_return, mapl_verify
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_linkcreate calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_wirecomponent calls mapl_reconnect
mapl_genericsetservices calls mapl_wirecomponent
setservices calls mapl_genericsetservices