MAPL_GridCoordAdjustFromFile – MAPL
MAPL_GridCoordAdjustFromFile Subroutine
47 statements
Source File
private subroutine MAPL_GridCoordAdjustFromFile(Grid, GRIDSPECFILE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: Grid
character(len=*), intent(in) :: GRIDSPECFILE
integer, intent(out), optional :: RC
Calls
Source Code
   subroutine MAPL_GridCoordAdjustFromFile(GRID, GRIDSPECFILE, RC)
      type(ESMF_Grid),               intent(INout ) :: Grid
      character(len=*),              intent(IN    ) :: GRIDSPECFILE
      integer, optional,             intent(   OUT) :: RC
      ! local vars
      !------------
      integer                    :: status
      integer :: UNIT
      integer :: IM, JM
      integer :: IMSTART, JMSTART
      integer :: IM_WORLD, JM_WORLD
      integer :: DUMMYI, DUMMYJ
      integer :: COUNTS(3), DIMS(3)
      type(ESMF_DELayout) :: LAYOUT
      type(ESMF_DistGrid) :: DISTGRID
      real(ESMF_KIND_R8), allocatable :: x(:,:), y(:,:)
      real(ESMF_KIND_R8), pointer :: gridx(:,:), gridy(:,:)
      ! get IM, JM and IM_WORLD, JM_WORLD
      call MAPL_GridGet(GRID, localCellCountPerDim=COUNTS, globalCellCountPerDim=DIMS, RC=status)
      _VERIFY(status)
      IM = COUNTS(1)
      JM = COUNTS(2)
      IM_WORLD = DIMS(1)
      JM_WORLD = DIMS(2)
      ! get global index of the lower left corner
      !------------------------------------------
      call MAPL_GRID_INTERIOR(GRID,IMSTART,DUMMYI,JMSTART,DUMMYJ)
      call ESMF_GridGetCoord(grid, localDE=0, coordDim=1, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=gridx, rc=status)
      _VERIFY(status)
      call ESMF_GridGetCoord(grid, localDE=0, coordDim=2, &
           staggerloc=ESMF_STAGGERLOC_CENTER, &
           farrayPtr=gridy, rc=status)
      _VERIFY(status)
      allocate(x(IM_WORLD, JM_WORLD), stat=status)
      _VERIFY(status)
      allocate(y(IM_WORLD, JM_WORLD), stat=status)
      _VERIFY(status)
      call ESMF_GridGet    (GRID,   distGrid=distGrid, rc=status)
      _VERIFY(status)
      call ESMF_DistGridGet(distGRID, delayout=layout, rc=status)
      _VERIFY(status)
      UNIT = GETFILE(GRIDSPECFILE, form="formatted", rc=status)
      call READ_PARALLEL(LAYOUT, X, unit=UNIT)
      call READ_PARALLEL(LAYOUT, Y, unit=UNIT)
      call FREE_FILE(UNIT)
      ! Make sure the longitudes are between -180 and 180 degrees
      !ALT disable this for AR5    X = mod(X + 72180._REAL64,360._REAL64) - 180._REAL64 ! -180<= lon0 <180
      ! Convert to radians
      X = X * (MAPL_PI_R8)/180._REAL64
      Y = Y * (MAPL_PI_R8)/180._REAL64
      ! Modify grid coordinates
      !------------------------
      GRIDX = X(IMSTART:IMSTART+IM-1,JMSTART:JMSTART+JM-1)
      GRIDY = Y(IMSTART:IMSTART+IM-1,JMSTART:JMSTART+JM-1)
      ! Clean-up
      !---------
      deallocate(y)
      deallocate(x)
      ! All done
      !---------
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GridCoordAdjustFromFile
Call graph
mapl_gridcoordadjustfromfile calls ESMF_DistGridGet, ESMF_GridGet, ESMF_GridGetCoord, mapl_grid_interior, read_parallel, free_file, getfile, mapl_gridget, mapl_return, mapl_verify
mapl_grid_interior calls mapl_grid_interior
read_parallel calls read_parallel_i4_0, read_parallel_i4_1, read_parallel_i4_2, read_parallel_r4_0, read_parallel_r4_1, read_parallel_r4_2, read_parallel_r8_0, read_parallel_r8_1, read_parallel_r8_2, read_parallel_string_0
free_file calls mapl_return, mapl_assert
getfile calls mapl_return, mapl_verify, mapl_am_i_root, getfilemem, mapl_open
mapl_gridget calls ESMF_DistGridGet, ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception