MAPL_ProfDisable – MAPL
MAPL_ProfDisable Subroutine
7 statements
Source File
public subroutine MAPL_ProfDisable(RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: RC
Calls
Called by
Source Code
    subroutine MAPL_ProfDisable(RC)
      integer, optional, intent(OUT)   :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_ProfDisable"
      !$omp master
      DISABLED = .true.
      !$omp end master
      _RETURN(ESMF_SUCCESS)
    end subroutine MAPL_ProfDisable
Call graph
mapl_profdisable calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_gc calls mapl_profdisable