MAPL_FieldSplit – MAPL
MAPL_FieldSplit Module Subroutine
219 statements
Source File
module subroutine MAPL_FieldSplit(field, fields, aliasName, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(in) :: field
type(ESMF_Field), intent(out), pointer :: fields(:)
character(len=*), intent(in), optional :: aliasName
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_FieldSplit
Source Code
  module subroutine MAPL_FieldSplit(field, fields, aliasName, rc)
    type(ESMF_Field),          intent(IN   ) :: field
    type(ESMF_Field), pointer, intent(  out) :: fields(:)
    character(len=*), optional, intent(in  ) :: aliasName
    integer, optional,         intent(  out) :: rc
    ! local vars
    integer :: status
    integer :: k, n
    integer :: k1,k2,kk
    integer :: gridRank
    logical                    :: has_ungrd
    integer                    :: ungrd_cnt
    integer                    :: fieldRank
    integer, allocatable       :: gridToFieldMap(:)
    integer, allocatable       :: ungrd(:)
    real, pointer              :: ptr4d(:,:,:,:) => null()
    real, pointer              :: ptr3d(:,:,:) => null()
    real, pointer              :: ptr2d(:,:) => null()
    type(ESMF_Field)           :: f, fld
    type(ESMF_Grid)            :: grid
    type(ESMF_TypeKind_Flag)   :: tk
    character(len=ESMF_MAXSTR) :: name
    character(len=ESMF_MAXSTR) :: splitName
    character(len=ESMF_MAXSTR), allocatable :: splitNameArray(:)
    character(len=ESMF_MAXSTR) :: longName
    ! get ptr
    ! loop over 3-d or 4-d dim
    ! create 2d or 3d field
    ! put in state/bundle
    ! end-of-loop
    call ESMF_FieldGet(field, name=name, grid=grid, typekind=tk, rc=status)
    _VERIFY(STATUS)
    call ESMF_GridGet(GRID, dimCount=gridRank, rc=status)
    _VERIFY(STATUS)
    allocate(gridToFieldMap(gridRank), stat=status)
    _VERIFY(STATUS)
    call ESMF_FieldGet(field, gridToFieldMap=gridToFieldMap, rc=status)
    _VERIFY(STATUS)
    if (tk == ESMF_TYPEKIND_R4) then
       call ESMF_FieldGet(FIELD, dimCount=fieldRank, rc=status)
       _VERIFY(STATUS)
       if (fieldRank == 4) then
          !ALT: assumes 1 DE per PET
          call ESMF_FieldGet(Field,0,ptr4D,rc=status)
          _VERIFY(STATUS)
          n = size(ptr4d,4)
          allocate(fields(n), stat=status)
          _VERIFY(STATUS)
          n = 0
          k1=lbound(ptr4d,4)
          k2=ubound(ptr4d,4)
          kk = k2-k1+1
          call genAlias(name, kk, splitNameArray, aliasName=aliasName,rc=status)
          _VERIFY(STATUS)
          do k=k1,k2
             n = n+1
             ptr3d => ptr4d(:,:,:,k)
             ! create a new field
             splitName = splitNameArray(n)
             f = MAPL_FieldCreateEmpty(name=splitName, grid=grid, rc=status)
             _VERIFY(STATUS)
             call ESMF_FieldEmptyComplete(F, farrayPtr=ptr3D,    &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  gridToFieldMap=gridToFieldMap,                      &
                  rc = status)
             _VERIFY(STATUS)
             ! copy attributes and adjust as necessary
             fld = field ! shallow copy to get around intent(in/out)
             call MAPL_FieldCopyAttributes(FIELD_IN=fld, FIELD_OUT=f, RC=status)
             _VERIFY(STATUS)
             ! adjust ungridded dims attribute (if any)
             call ESMF_AttributeGet(FIELD, NAME='UNGRIDDED_DIMS', isPresent=has_ungrd, RC=STATUS)
             _VERIFY(STATUS)
             if (has_ungrd) then
                call ESMF_AttributeGet(F, NAME='UNGRIDDED_DIMS', itemcount=UNGRD_CNT, RC=STATUS)
                _VERIFY(STATUS)
                allocate(ungrd(UNGRD_CNT), stat=status)
                _VERIFY(STATUS)
                call ESMF_AttributeGet(F, NAME='UNGRIDDED_DIMS', valueList=UNGRD, RC=STATUS)
                _VERIFY(STATUS)
                call ESMF_AttributeRemove(F, NAME='UNGRIDDED_DIMS', RC=STATUS)
                _VERIFY(STATUS)
                if (ungrd_cnt > 1) then
                   ungrd_cnt = ungrd_cnt - 1
                   call ESMF_AttributeSet(F, NAME='UNGRIDDED_DIMS', &
                        valueList=UNGRD(1:ungrd_cnt), RC=STATUS)
                   _VERIFY(STATUS)
                else
                   has_ungrd = .false.
                end if
                deallocate(ungrd)
             end if
             fields(n) = f
          end do
       else if (fieldRank == 3) then
          !ALT: assumes 1 DE per PET
          call ESMF_FieldGet(Field,0,ptr3D,rc=status)
          _VERIFY(STATUS)
          n = size(ptr3d,3)
          allocate(fields(n), stat=status)
          _VERIFY(STATUS)
          n = 0
          k1=lbound(ptr3d,3)
          k2=ubound(ptr3d,3)
          kk = k2-k1+1
          call genAlias(name, kk, splitNameArray, aliasName=aliasName,rc=status)
          _VERIFY(STATUS)
          do k=k1,k2
             n = n+1
             ptr2d => ptr3d(:,:,k)
             ! create a new field
             splitName = splitNameArray(n)
             f = MAPL_FieldCreateEmpty(name=splitName, grid=grid, rc=status)
             _VERIFY(STATUS)
             call ESMF_FieldEmptyComplete(F, farrayPtr=ptr2D,    &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  gridToFieldMap=gridToFieldMap,                      &
                  rc = status)
             _VERIFY(STATUS)
             ! copy attributes and adjust as necessary
             fld = field ! shallow copy to get around intent(in/out)
             call MAPL_FieldCopyAttributes(FIELD_IN=fld, FIELD_OUT=f, RC=status)
             _VERIFY(STATUS)
             ! adjust ungridded dims attribute (if any)
             call ESMF_AttributeGet(FIELD, NAME='UNGRIDDED_DIMS', isPresent=has_ungrd, RC=STATUS)
             _VERIFY(STATUS)
             if (has_ungrd) then
                call ESMF_AttributeGet(F, NAME='UNGRIDDED_DIMS', itemcount=UNGRD_CNT, RC=STATUS)
                _VERIFY(STATUS)
                allocate(ungrd(UNGRD_CNT), stat=status)
                _VERIFY(STATUS)
                call ESMF_AttributeGet(F, NAME='UNGRIDDED_DIMS', valueList=UNGRD, RC=STATUS)
                _VERIFY(STATUS)
                call ESMF_AttributeRemove(F, NAME='UNGRIDDED_DIMS', RC=STATUS)
                _VERIFY(STATUS)
                if (ungrd_cnt > 1) then
                   ungrd_cnt = ungrd_cnt - 1
                   call ESMF_AttributeSet(F, NAME='UNGRIDDED_DIMS', &
                        valueList=UNGRD(1:ungrd_cnt), RC=STATUS)
                   _VERIFY(STATUS)
                else
                   has_ungrd = .false.
                end if
                deallocate(ungrd)
             end if
             fields(n) = f
          end do
       end if
    else if (tk == ESMF_TYPEKIND_R8) then
       _FAIL( "R8 overload not implemented yet")
    end if
    deallocate(gridToFieldMap)
    deallocate(splitNameArray)
    ! fields SHOULD be deallocated by the caller!!!
!ALT: check if we need to expand "%d" in the long name
!    Note that at this point the original, and each of the split fields
!    have the same long name. We check the original.
    call ESMF_AttributeGet(FIELD, NAME='LONG_NAME', VALUE=longName, _RC)
    if (index(longName, "%d") /= 0) then
       call expandBinNumber(fields, _RC)
    end if
    _RETURN(ESMF_SUCCESS)
  contains
    subroutine expandBinNumber(fields, rc)
      type(ESMF_Field) :: fields(:)
      integer, optional :: rc
      integer :: i, tlen, i1, i2
      character(len=ESMF_MAXSTR) :: longName
      character(len=3) :: tmp
      character(len=ESMF_MAXSTR) :: newLongName
      do i = 1, size(fields)
         call ESMF_AttributeGet(fields(i), NAME='LONG_NAME', VALUE=longName, _RC)
         i1 = index(longName, "%d")
         _ASSERT(i1>0, "Nothing to expand")
         i2 = i1 + 2 ! size of "%d"
         tlen = len_trim(longName)
         _ASSERT(tlen + 1 <= len(longName),'LONG_NAME would exceed MAX length after expansion')
         write(tmp,'(i3.3)') i
         newLongName = longName(1:i1-1)//tmp//trim(longName(i2:tlen))
         ! remove old attribute
         call ESMF_AttributeRemove(fields(i), NAME='LONG_NAME', _RC)
         ! save the new one
         call ESMF_AttributeSet(fields(i), NAME='LONG_NAME', VALUE=newLongName, _RC)
      end do
    _RETURN(ESMF_SUCCESS)
    end subroutine expandBinNumber
    subroutine genAlias(name, n, splitNameArray, aliasName, rc)
      integer :: n
      character(len=*) :: name
      character(len=*), allocatable :: splitNameArray(:)
      character(len=*), optional :: aliasName
      integer, optional :: rc
      integer :: i, k
      integer :: k1, k2, kk, count
      integer :: nn
      character(len=ESMF_MAXSTR), allocatable :: tmp(:)
      character(len=ESMF_MAXSTR) :: aliasName_
      if (present(aliasName)) then
         aliasName_ = aliasName
      else
         aliasName_ = name
      end if
      allocate(splitNameArray(n), stat=status)
      _VERIFY(status)
      ! parse the aliasName
      ! count the separators (";") in aliasName
      count = 0
      k1 = 1
      kk = len_trim(aliasName_)
      do k=1,kk
         if (aliasName_(k:k) == ";") then
            count = count+1
         end if
      end do
      nn = count+1
      allocate(tmp(nn), __STAT__)
      count = 0
      do k=1,kk
         if (aliasName_(k:k) == ";") then
            count = count+1
            k2=k-1
            if (count > n) exit ! use atmost n of the aliases
            tmp(count) = aliasName_(k1:k2)
            k1 = k+1
         end if
      end do
      count = count+1
      k2 = kk
      tmp(count) = aliasName_(k1:k2)
      do i=1,min(nn,n)
         splitNameArray(i) = tmp(i)
      end do
      deallocate(tmp)
      ! if the user did no supply enough separated alias field names,
      ! append 00i to the original field name
      if (n==1) nn=0
      do i=nn+1,n
         write(splitNameArray(i),'(A,I3.3)') trim(name), i
      end do
      _RETURN(ESMF_SUCCESS)
    end subroutine GenAlias
  end subroutine MAPL_FieldSplit
Call graph
mapl_fieldsplit calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, mapl_fieldcreateempty, esmf_fieldemptycomplete, esmf_gridget, mapl_fieldcopyattributes, esmf_attributeget, esmf_attributeremove, esmf_attributeset, mapl_fieldsplit
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldcreateempty calls mapl_fieldcreateempty, mapl_return, mapl_verify, esmf_fieldemptycreate, esmf_fieldemptyset
mapl_fieldcopyattributes calls mapl_fieldcopyattributes, mapl_return, mapl_verify, esmf_attributecopy
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize calls mapl_fieldsplit
putfieldinbundle__ calls mapl_fieldsplit
mapl_gridcompgetfriendlies0 calls putfieldinbundle__
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0