MAPL_AddConnectivityE2E – MAPL
MAPL_AddConnectivityE2E Subroutine
17 statements
Source File
private subroutine MAPL_AddConnectivityE2E(GC, SHORT_NAME, SRC_ID, TO_EXPORT, TO_NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: SRC_ID
integer, intent(in) :: TO_EXPORT
character(len=*), intent(in), optional :: TO_NAME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_AddConnectivityE2E ( GC, SHORT_NAME, &
        SRC_ID, TO_EXPORT, TO_NAME, RC )
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*),              intent(IN   ) :: SHORT_NAME
      character (len=*),      optional, intent(IN)  :: TO_NAME !name in TO_EXPORT
      integer,                        intent(IN   ) :: SRC_ID !FROM_EXPORT
      integer,                        intent(IN   ) :: TO_EXPORT
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_AddConnectivityE2E"
      integer                               :: status
      type (MAPL_Connectivity), pointer     :: conn
      call MAPL_ConnectivityGet(gc, connectivityPtr=conn, _RC)
      call conn%connect%append(SHORT_NAME, TO_NAME=TO_NAME, &
           FROM_EXPORT=SRC_ID, TO_IMPORT=TO_EXPORT, _RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_AddConnectivityE2E
Call graph
mapl_addconnectivitye2e calls append, mapl_connectivityget, mapl_return, mapl_verify
append calls mapl_return, resize, vector_back
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
vector_resize_size_kind calls reserve
mapl_stateaddexportspecfrmchldname calls mapl_addconnectivitye2e
mapl_stateaddexportspecfrmchld calls mapl_stateaddexportspecfrmchldname
mapl_addexportspec calls mapl_stateaddexportspecfrmchld, mapl_stateaddexportspecfrmchld_all
mapl_stateaddexportspecfrmchld_all calls mapl_stateaddexportspecfrmchld
addnewspec calls mapl_addexportspec
setservices calls mapl_addexportspec