MAPL_FindChild – MAPL
MAPL_FindChild Subroutine
35 statements
Source File
private recursive subroutine MAPL_FindChild(META, name, result, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: META
character(len=*), intent(in) :: name
type(MAPL_MetaComp), intent(inout), pointer :: result
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   recursive subroutine MAPL_FindChild(meta, name, result, rc)
      type (MAPL_MetaComp),        intent(INOUT) :: META
      character(len=*),            intent(IN   ) :: name
      type (MAPL_MetaComp), pointer, intent(INOUT) :: result
      integer, optional,           intent(  OUT) :: RC     ! Error code:
      integer :: status
      integer :: i
      integer :: nc
      type (MAPL_MetaComp), pointer :: cmeta => null()
      type(ESMF_GridComp), pointer :: childgridcomp
      nc = meta%get_num_children()
      if(nc > 0) then
         do I=1, nc
            childgridcomp => meta%get_child_gridcomp(i)
            call MAPL_InternalStateRetrieve(childgridcomp, cmeta, RC=status)
            _VERIFY(status)
            if (cmeta%compname == name) then ! found it!
               result => cmeta
               _RETURN(ESMF_SUCCESS)
            end if
            call MAPL_FindChild(cmeta, name, result, rc=status)
            if (associated(result)) then ! somebody found it, terminate the search
               _RETURN(ESMF_SUCCESS)
            end if
         end do
      else
         result => null()
         _RETURN(ESMF_SUCCESS)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_FindChild
Call graph
mapl_findchild calls mapl_findchild, get_child_gridcomp, get_num_children, mapl_internalstateretrieve, mapl_return, mapl_verify
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_servicegetbundle calls mapl_findchild
mapl_processserviceconnections calls mapl_servicegetbundle
mapl_genericinitialize calls mapl_processserviceconnections
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize