MAPL_SunGetSolarConstantFromNRLFile – MAPL
MAPL_SunGetSolarConstantFromNRLFile Subroutine
215 statements
Source File
private subroutine MAPL_SunGetSolarConstantFromNRLFile(CLOCK, filename_in, SC, MG, SB, PersistSolar, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in) :: filename_in
real, intent(out) :: SC
real, intent(out) :: MG
real, intent(out) :: SB
logical, intent(in), optional :: PersistSolar
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_SunGetSolarConstantFromNRLFile
Source Code
   subroutine MAPL_SunGetSolarConstantFromNRLFile(CLOCK,filename_in,SC,MG,SB,PersistSolar,rc)
! !DESCRIPTION:
!
!  Acquire the TSI, Mg, and SB from file
!
! !BUGS:
!
!  Band values for RRTMG not implemented
!
!EOP
! ---------------------------------------------------------------------------------
      implicit none
      type(ESMF_Clock), intent(in)       :: CLOCK
      character(len=*), intent(in)       :: filename_in
      real, intent(out)                  :: SC
      real, intent(out)                  :: MG
      real, intent(out)                  :: SB
      logical, optional, intent(in)      :: PersistSolar
      integer, optional, intent(out)     :: rc
      type(ESMF_VM)              :: VM
      type(ESMF_Time)            :: noonCurrentDay, prevNoon, nextNoon
      type(ESMF_TimeInterval)    :: intToNextNoon, oneDayInterval
      type(ESMF_Time)            :: currentTime, origTime
      type(ESMF_Time)            :: timeBasedOnCycle24
      type(ESMF_Time)            :: startCycle24, startCycle25
      type(ESMF_TimeInterval)    :: timeSinceStartOfCycle25
      integer :: currentYear, currentMon, currentDay, currentDOY
      integer :: prevDOY, nextDOY, prevNoonYear, nextNoonYear
      integer :: originalYear, originalMon, originalDay, origDOY
      real(ESMF_KIND_R8)         :: days_r8
      integer                    :: INDX1, INDX2, i
      integer                    :: STATUS, UNIT
      real                       :: FAC
      character(len=ESMF_MAXPATHLEN) :: FILENAME
      logical :: found
      logical :: amIRoot
      integer :: deId, NPES
      logical :: outOfTable
      logical :: PersistSolar_
      integer, parameter :: YEAR_NOT_FOUND = -99
      character(len=256) :: line
      character(len=1), parameter :: commentChar = "#"
      integer :: stat
      logical, save :: TableCreated = .FALSE.
      integer, save, allocatable, dimension(:) :: yearTable, doyTable
      real,    save, allocatable, dimension(:) :: tsi, mgindex, sbindex
      integer, save :: numlines
      class(Logger), pointer :: lgr
      lgr => logging%get_logger('MAPL.SUN')
      if (present(PersistSolar)) then
         PersistSolar_ = PersistSolar
      else
         PersistSolar_ = .TRUE.
      end if
      call ESMF_VMGetCurrent(vm, rc=status)
      call ESMF_VmGet(VM, localPet=deId, petCount=npes, rc=status)
      _VERIFY(STATUS)
      amIRoot = (deId == 0)
      CREATE_TABLE: if (.not. TableCreated) then
         ! First we open the file on root to get the
         ! number of lines so we can allocate our tables
         ! ---------------------------------------------
         if (amIRoot) then
            ! Open the file
            ! -------------
            filename = trim(filename_in)
            open(newunit=unit, file=filename, form="formatted", status="old", iostat=status)
            _ASSERT(status==0,'Could not find NRL data file '// trim(filename ))
            ! Determine length of file
            ! ------------------------
            call lgr%debug("Scanning the Solar Table to determine number of data points")
            numlines = num_lines_in_file(UNIT)
            call lgr%debug("Solar Table Data Points: %i0", numlines)
         end if
         ! Broadcast the number of lines
         ! -----------------------------
         call MAPL_CommsBcast(vm, DATA=numlines, N=1, ROOT=0, _RC)
         ! Allocate our arrays on all processes
         ! ------------------------------------
         allocate(yearTable(numlines), source=0,   _STAT)
         allocate(doyTable(numlines),  source=0,   _STAT)
         allocate(tsi(numlines),       source=0.0, _STAT)
         allocate(mgindex(numlines),   source=0.0, _STAT)
         allocate(sbindex(numlines),   source=0.0, _STAT)
         ! Back to root to read in the values
         ! ----------------------------------
         if (amIRoot) then
            call lgr%debug("Reading the Solar Table")
            i = 1
            do
               read(unit,'(A)',iostat=stat) line
               if (is_iostat_end(stat)) exit
               ! Skip lines starting with #-comments
               if (index (line, commentChar) /= 0) cycle
               read(line,*) yearTable(i), doyTable(i), tsi(i), mgindex(i), sbindex(i)
               i = i + 1
            end do
            ! Belt and suspenders check that all data was read
            _ASSERT(size(yearTable) == numlines,"Inconsistency in NRL number of lines")
            close(unit, _IOSTAT)
         end if
         ! Broadcast the tables
         ! --------------------
         call MAPL_CommsBcast(vm, DATA=yearTable, N=numlines, ROOT=0, _RC)
         call MAPL_CommsBcast(vm, DATA=doyTable,  N=numlines, ROOT=0, _RC)
         call MAPL_CommsBcast(vm, DATA=tsi,       N=numlines, ROOT=0, _RC)
         call MAPL_CommsBcast(vm, DATA=mgindex,   N=numlines, ROOT=0, _RC)
         call MAPL_CommsBcast(vm, DATA=sbindex,   N=numlines, ROOT=0, _RC)
         TableCreated = .TRUE.
      end if CREATE_TABLE
      ! Now we need to find the two bracketing days
      ! -------------------------------------------
      ! Get current time
      ! ----------------
      call ESMF_ClockGet(CLOCK, CURRTIME=currentTime, _RC)
      call ESMF_TimeGet( currentTime, YY = currentYear,   &
                                      MM = currentMon,    &
                                      DD = currentDay,    &
                               dayOfYear = currentDOY, _RC)
      ! Test if current time is outside our file
      ! ----------------------------------------
      outOfTable = .FALSE.
      ! First is current year higher than last in file...
      if ( currentYear > yearTable(numlines) ) then
         outOfTable = .TRUE.
      ! ...or if a partial year, are we near the end
      else if ( currentYear == yearTable(numlines) .and. currentDOY >= doyTable(numlines)) then
         outOfTable = .TRUE.
      end if
      ! If we are out of the table...
      ! -----------------------------
      OUT_OF_TABLE: if ( outOfTable ) then
         PERSIST_SOLAR: if ( PersistSolar_ ) then
            ! If we are outOfTable and we have the PersistSolar
            ! option we just use the last value in the table...
            ! -------------------------------------------------
            SC =     tsi(numlines)
            MG = mgindex(numlines)
            SB = sbindex(numlines)
            call lgr%debug('Off the end of table, persisting last values')
            call lgr%debug('  tsi at end of table: %F8.3', tsi(numlines))
            call lgr%debug('  mgindex at end of table: %F8.6', mgindex(numlines))
            call lgr%debug('  sbindex at end of table: %F9.4', sbindex(numlines))
            _RETURN(ESMF_SUCCESS)
         else
            ! If we are out of the table and not persisting, we must
            ! recenter our day to be based on the last complete Solar Cycle
            ! -------------------------------------------------------------
            ! Create an ESMF_Time at start of Cycle 24
            ! ----------------------------------------
            call ESMF_TimeSet( startCycle24, YY = 2008,  &
                                             MM = 12,    &
                                             DD = 1,     &
                                              H = 12,    &
                                              M = 00,    &
                                              S = 00, _RC)
            ! Create an ESMF_Time at start of Cycle 25
            ! ----------------------------------------
            call ESMF_TimeSet( startCycle25, YY = 2019,  &
                                             MM = 12,    &
                                             DD = 1,     &
                                              H = 12,    &
                                              M = 00,    &
                                              S = 00, _RC)
            ! Create TimeInterval based on interval
            ! from start of latest Cycle 25
            ! -------------------------------------
            timeSinceStartOfCycle25 = currentTime - startCycle25
            ! Make a new time based on that
            ! interval past start of Cycle 24
            ! -------------------------------
            timeBasedOnCycle24 = startCycle24 + timeSinceStartOfCycle25
            ! Store our original time just in case
            ! ------------------------------------
            origTime     = currentTime
            originalYear = currentYear
            originalMon  = currentMon
            originalDay  = currentDay
            origDOY      = currentDOY
            ! Make our "current" time the one calculated above
            ! ------------------------------------------------
            currentTime = timeBasedOnCycle24
            ! Get new currentYear, currentMon, currentDay
            ! -------------------------------------------
            call ESMF_TimeGet( currentTime, YY = currentYear,   &
                                            MM = currentMon,    &
                                            DD = currentDay,    &
                                     dayOfYear = currentDOY, _RC)
            call lgr%debug('Off the end of table, moving into last complete cycle')
            call lgr%debug('  Original Year-Mon-Day to Find: %i0.4~-%i0.2~-%i0.2', originalYear,originalMon,originalDay)
            call lgr%debug('  Original Day of Year: %i0', origDOY)
            call lgr%debug('  New Year-Mon-Day to Find: %i0.4~-%i0.2~-%i0.2', currentYear,currentMon,currentDay)
            call lgr%debug('  New Day of Year: %i0', currentDOY)
         end if PERSIST_SOLAR
      end if OUT_OF_TABLE
      ! Create an ESMF_Time on noon of current day
      ! ------------------------------------------
      call ESMF_TimeSet( noonCurrentDay, YY = currentYear, &
                                         MM = currentMon,  &
                                         DD = currentDay,  &
                                          H = 12,          &
                                          M = 00,          &
                                          S = 00,       _RC)
      ! Figure out bracketing days for interpolation
      ! NOTE: nextNoon is mainly for debugging purposes
      ! -----------------------------------------------
      call ESMF_TimeIntervalSet(oneDayInterval, D=1, _RC)
      if (currentTime <= noonCurrentDay) then
         prevNoon = noonCurrentDay - oneDayInterval
         nextNoon = noonCurrentDay
      else
         prevNoon = noonCurrentDay
         nextNoon = noonCurrentDay + oneDayInterval
      end if
      ! Get the DOYs
      ! ------------
      call ESMF_TimeGet( prevNoon, YY = prevNoonYear, dayOfYear = prevDOY, _RC)
      call ESMF_TimeGet( nextNoon, YY = nextNoonYear, dayOfYear = nextDOY, _RC)
      ! Our interpolation factor is based of when we are compared to the next noon
      ! --------------------------------------------------------------------------
      intToNextNoon = nextNoon-currentTime
      ! The FAC for interpolating is just the real version
      ! of the size of the timeinterval to the next noon
      ! --------------------------------------------------
      call ESMF_TimeIntervalGet(intToNextNoon, d_r8=days_r8, _RC)
      FAC = real(days_r8)
      ! Use our find_file_index function to get the index for previous noon
      ! -------------------------------------------------------------------
      INDX1 = find_file_index(numlines, yearTable, prevNoonYear, prevDOY)
      INDX2 = INDX1 + 1
      ! Linear Interpolation to the given day-of-month
      ! ----------------------------------------------
      SC =     tsi(INDX1)*FAC +     tsi(INDX2)*(1.0-FAC)
      MG = mgindex(INDX1)*FAC + mgindex(INDX2)*(1.0-FAC)
      SB = sbindex(INDX1)*FAC + sbindex(INDX2)*(1.0-FAC)
      call lgr%debug('  First DOY to Find:     %i3', prevDOY)
      call lgr%debug('    file_index for date: %i6', INDX1)
      call lgr%debug('    yearTable(date):     %i4', yearTable(INDX1))
      call lgr%debug('    doyTable(date):      %i3', doyTable(INDX1))
      call lgr%debug('    tsi(date):           %f8.3', tsi(INDX1))
      call lgr%debug('    mgindex(date):       %f8.6', mgindex(INDX1))
      call lgr%debug('    sbindex(date):       %f9.4', sbindex(INDX1))
      call lgr%debug('  Second DOY to Find:    %i3', nextDOY)
      call lgr%debug('    file_index for date: %i6', INDX2)
      call lgr%debug('    yearTable(date):     %i4', yearTable(INDX2))
      call lgr%debug('    doyTable(date):      %i3', doyTable(INDX2))
      call lgr%debug('    tsi(date):           %f8.3', tsi(INDX2))
      call lgr%debug('    mgindex(date):       %f8.6', mgindex(INDX2))
      call lgr%debug('    sbindex(date):       %f9.4', sbindex(INDX2))
      call lgr%debug('  Interpolation Factor:  %f8.6', FAC)
      _RETURN(ESMF_SUCCESS)
      contains
         integer function num_lines_in_file(unit) result(count)
            implicit none
            integer, intent(in) :: unit
            character(len=256) :: line
            integer :: stat
            character(len=1), parameter :: commentChar = "#"
            count = 0
            do
               read(unit,'(A)',iostat=stat) line
               if (is_iostat_end(stat)) exit
               ! Skip lines starting with #-comments
               if (index (line, commentChar) /= 0) cycle
               count = count + 1
            end do
            rewind(unit)
         end function num_lines_in_file
         integer function find_file_index(numlines, year, year_to_find, doy_to_find)
            implicit none
            integer, intent(in) :: numlines
            integer, intent(in), dimension(numlines) :: year
            integer, intent(in) :: year_to_find, doy_to_find
            integer :: i, yr_index
            ! Find the index for the year
            ! ---------------------------
            yr_index = YEAR_NOT_FOUND
            do i = 1, numlines
               if (year(i) == year_to_find) then
                  yr_index = i
                  exit
               end if
            end do
            if (yr_index == YEAR_NOT_FOUND) then
               find_file_index = YEAR_NOT_FOUND
            else
               find_file_index = yr_index + doy_to_find - 1
            end if
         end function find_file_index
   end subroutine MAPL_SunGetSolarConstantFromNRLFile
Call graph
mapl_sungetsolarconstantfromnrlfile calls esmf_timeintervalget, esmf_vmgetcurrent, esmf_vmget, mapl_verify, mapl_commsbcast, mapl_assert, esmf_clockget, esmf_timeget, mapl_return, esmf_timeset, esmf_timeintervalset
mapl_sungetsolarconstant calls mapl_sungetsolarconstantfromnrlfile