MAPL_SimpleBundleWrite1 – MAPL
MAPL_SimpleBundleWrite1 Subroutine
17 statements
Source File
private subroutine MAPL_SimpleBundleWrite1(self, filename, Clock, verbose, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_SimpleBundle) :: self
character(len=*), intent(in) :: filename
type(ESMF_Clock), intent(inout) :: Clock
logical, intent(in), optional :: verbose
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_SimpleBundleWrite1
Source Code
  subroutine MAPL_SimpleBundleWrite1 ( self, filename, clock, verbose, rc )
! !ARGUMENTS:
    type(MAPL_SimpleBundle)                 :: self
    character(len=*),           intent(in) :: filename
    type(ESMF_Clock),           intent(inout) :: Clock
    logical, OPTIONAL,          intent(in)  :: verbose
    integer, OPTIONAL,          intent(out) :: rc
!  !DESCRIPTION:
!
!  Writes a MAPL SimpleBundle to file fiven an ESMF Clock object. The file opened,
!  written to, and closed.
!EOP
!                                ---
    type(MAPL_CFIO)            :: cfio
    integer                    :: status
    call MAPL_CFIOCreate ( cfio, filename, clock, self%Bundle, _RC)
    call MAPL_CFIOWrite  ( cfio, Clock, self%Bundle, verbose=verbose, _RC)
    call MAPL_CFIODestroy ( cfio, _RC )
    _RETURN(_SUCCESS)
  end subroutine MAPL_SimpleBundleWrite1
Call graph
mapl_simplebundlewrite1 calls mapl_cfiocreate, mapl_verify, mapl_cfiodestroy, mapl_cfiowrite, mapl_return
mapl_cfiocreate calls mapl_cfiocreatefrombundle, mapl_cfiocreatefromstate
mapl_verify calls mapl_throw_exception
mapl_cfiodestroy calls mapl_verify, mapl_return, esmf_cfiofileclose, esmf_cfiodestroy
mapl_cfiowrite calls mapl_cfiowritestate, mapl_cfiowritebundle
mapl_return calls mapl_throw_exception, get_error_message
mapl_simplebundlewrite calls mapl_simplebundlewrite1