MAPL_VarSpecPrintCSV – MAPL
MAPL_VarSpecPrintCSV Subroutine
13 statements
Source File
public subroutine MAPL_VarSpecPrintCSV(spec, compName, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: spec(:)
character(len=*), intent(in) :: compName
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecPrintCSV
Source Code
   subroutine MAPL_VarSpecPrintCSV(SPEC, compName, RC )
      type (MAPL_VarSpec ),             intent(in )     :: spec(:)
      character(len=*),                 intent(in )     :: compName
      integer            , optional   , intent(out)     :: RC
      integer                               :: status
      integer                               :: i
      do I = 1, size(spec)
         call MAPL_VarSpecPrint1CSV(Spec(I), compName, RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecPrintCSV
Call graph
mapl_varspecprintcsv calls mapl_return, mapl_varspecprint1csv, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspecprint1csv calls mapl_return, get_logger, info
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_stateprintspeccsv calls mapl_varspecprintcsv, mapl_stateprintspeccsv
initialize_gc calls mapl_stateprintspeccsv