MAPL_CommsSendRecv_R4_2 – MAPL
MAPL_CommsSendRecv_R4_2 Subroutine
24 statements
Source File
private subroutine MAPL_CommsSendRecv_R4_2(layout, sendbuf, sendcount, DEST, recvbuf, recvcount, SOURCE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
real(kind=ESMF_KIND_R4), intent(inout) :: sendbuf(:,:)
integer, intent(in) :: sendcount
integer, intent(in) :: DEST
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: recvcount
integer, intent(in) :: SOURCE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commssendrecv_r4_2 calls ESMF_DELayoutGet, ESMF_VMGet, mpi_sendrecv, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_commssendrecv calls mapl_commssendrecv_r4_2
esmfl_halo_r4_2d calls mapl_commssendrecv
halo calls mapl_commssendrecv
esmfl_halo calls esmfl_halo_r4_2d
mapl_locstreamtransformg2t calls esmfl_halo