MAPL_StateRefresh – MAPL
MAPL_StateRefresh Subroutine
46 statements
Source File
private subroutine MAPL_StateRefresh(GC, IMPORT, EXPORT, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: IMPORT
type(ESMF_State), intent(inout) :: EXPORT
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateRefresh
Source Code
   subroutine MAPL_StateRefresh( GC, IMPORT, EXPORT, CLOCK, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp), intent(inout) :: GC     ! composite gridded component
      type(ESMF_State),    intent(inout) :: IMPORT ! import state
      type(ESMF_State),    intent(inout) :: EXPORT ! export state
      type(ESMF_Clock),    intent(inout) :: CLOCK  ! the clock
      integer, optional,   intent(  out) :: RC     ! Error code:
      ! = 0 all is well
      ! otherwise, error
      !EOPI
      ! LOCAL VARIABLES
      character(len=ESMF_MAXSTR)                  :: IAm
      character(len=ESMF_MAXSTR)                  :: comp_name
      integer                                     :: status
      type (MAPL_MetaComp), pointer               :: STATE
      integer                                     :: hdr
      integer                                     :: unit
      type(ESMF_State), pointer :: internal_state
      !=============================================================================
      _UNUSED_DUMMY(EXPORT)
      !  Begin...
      Iam = "MAPL_StateRefresh"
      call ESMF_GridCompGet(GC, name=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // Iam
      ! Retrieve the pointer to the state
      !----------------------------------
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      if (.not.associated(STATE%RECORD)) then
         _RETURN(ESMF_SUCCESS)
      end if
      if (STATE%RECORD%IMP_LEN > 0) then
         call MAPL_ESMFStateReadFromFile(IMPORT, CLOCK, &
              STATE%RECORD%IMP_FNAME, &
              STATE, .FALSE., RC=status)
         _VERIFY(status)
         UNIT = GETFILE(STATE%RECORD%IMP_FNAME, RC=status)
         _VERIFY(status)
         call MAPL_DestroyFile(unit = UNIT, rc=status)
         _VERIFY(status)
      end if
      if (STATE%RECORD%INT_LEN > 0) then
         call MAPL_GetResource( STATE   , hdr,         &
              default=0, &
              LABEL="INTERNAL_HEADER:", &
              RC=status)
         _VERIFY(status)
         internal_state => state%get_internal_state()
         call MAPL_ESMFStateReadFromFile(internal_state, CLOCK, &
              STATE%RECORD%INT_FNAME, &
              STATE, hdr/=0, RC=status)
         _VERIFY(status)
         UNIT = GETFILE(STATE%RECORD%INT_FNAME, RC=status)
         _VERIFY(status)
         call MAPL_DestroyFile(unit = UNIT, rc=status)
         _VERIFY(status)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateRefresh
Call graph
mapl_staterefresh calls ESMF_GridCompGet, get_internal_state, mapl_getresource, getfile, mapl_destroyfile, mapl_esmfstatereadfromfile, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh