MAPL_VarWriteNCpar_R8_4d – MAPL
MAPL_VarWriteNCpar_R8_4d Subroutine
33 statements
Source File
private subroutine MAPL_VarWriteNCpar_R8_4d(formatter, name, A, ARRDES, oClients, RC)
Arguments
Type Intent Optional Attributes Name
type(NetCDF4_FileFormatter), intent(in) :: formatter
character(len=*), intent(in) :: name
real(kind=ESMF_KIND_R8), intent(in) :: A(:,:,:,:)
type(ArrDescr), intent(inout) :: ARRDES
type(ClientManager), intent(inout), optional :: oClients
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarWriteNCpar_R8_4d
Source Code
  subroutine MAPL_VarWriteNCpar_R8_4d(formatter, name, A, ARRDES, oClients, RC)
    type(Netcdf4_Fileformatter) , intent(IN   ) :: formatter
    character(len=*)            , intent(IN   ) :: name
    real(kind=ESMF_KIND_R8)     , intent(IN   ) :: A(:,:,:,:)
    type(ArrDescr)              , intent(INOUT) :: ARRDES
    type (ClientManager), optional, intent(inout)  :: oClients
    integer,           optional , intent(  OUT) :: RC
    integer                               :: status
    integer :: K, L
    integer ::  i1, j1, in, jn,  global_dim(3)
    type(ArrayReference)     :: ref
    if (arrdes%write_restart_by_oserver) then
       _ASSERT(present(oClients), "output server is needed")
       call MAPL_GridGet(arrdes%grid,globalCellCountPerDim=global_dim,rc=status)
       _VERIFY(status)
       call MAPL_Grid_interior(arrdes%grid,i1,in,j1,jn)
       _ASSERT( i1 == arrdes%I1(arrdes%NX0), "interior starting i not match")
       _ASSERT( j1 == arrdes%j1(arrdes%NY0), "interior starting j not match")
       ref = ArrayReference(A)
       _ASSERT( size(a,1) == in-i1+1, "size not match")
       _ASSERT( size(a,2) == jn-j1+1, "size not match")
       call oClients%collective_stage_data(arrdes%collection_id,trim(arrdes%filename),trim(name), &
                   ref,start=[i1,j1,1,1], &
                   global_start=[1,1,1,1], global_count=[global_dim(1),global_dim(2),size(a,3),size(a,4)])
    else
       do K = 1,size(A,4)
          do L = 1,size(A,3)
             call MAPL_VarWrite(formatter, name, A(:,:,L,K), arrdes=arrdes, &
                  & oClients=oClients, lev=l, offset2=k, rc=status)
             _VERIFY(status)
          end do
       end do
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarWriteNCpar_R8_4d
Call graph
mapl_varwritencpar_r8_4d calls collective_stage_data, mapl_assert, mapl_grid_interior, mapl_varwrite, mapl_gridget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_grid_interior calls mapl_grid_interior
mapl_varwrite calls mapl_varwritencpar_r8_4d, mapl_varwritencpar_r4_1d, mapl_varwritencpar_r4_2d, mapl_varwritencpar_r4_3d, mapl_varwritencpar_r4_4d, mapl_varwritencpar_r8_1d, mapl_varwritencpar_r8_2d, mapl_varwritencpar_r8_3d
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldwritencpar calls mapl_varwrite
mapl_varwritencpar_r4_3d calls mapl_varwrite
mapl_varwritencpar_r4_4d calls mapl_varwrite
mapl_varwritencpar_r8_3d calls mapl_varwrite
mapl_bundlewritencpar calls mapl_fieldwritencpar
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar