MAPL_BalanceGet – MAPL
MAPL_BalanceGet Subroutine
14 statements
Source File
public subroutine MAPL_BalanceGet(Handle, BalLen, BufLen, Passes, Comm, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: Handle
integer, intent(out), optional :: BalLen
integer, intent(out), optional :: BufLen
integer, intent(out), optional :: Passes
integer, intent(out), optional :: Comm
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine MAPL_BalanceGet(Handle, BalLen, BufLen, Passes, Comm, rc)
    integer,           intent(IN ) :: Handle
    integer, optional, intent(OUT) :: BalLen, BufLen, Passes, Comm
    integer, optional, intent(OUT) :: rc
    _ASSERT(Handle>=0, 'Handle is less than 0')
    _ASSERT(Handle<=MAX_NUM_STRATEGIES,'Handle is greater than MAX_NUM_STATEGIES')
    _ASSERT(associated(THE_STRATEGIES(Handle)%NOP),'needs informative message')
    if(present(BalLen)) &
         BalLen = THE_STRATEGIES(Handle)%BALANCED_LENGTH
    if(present(BufLen)) &
         BufLen = THE_STRATEGIES(Handle)%BUFFER_LENGTH
    if(present(Passes)) &
         Passes = THE_STRATEGIES(Handle)%PASSES
    if(present(Comm  )) &
         Comm   = THE_STRATEGIES(Handle)%COMM
    _RETURN(LDB_SUCCESS)
  end subroutine MAPL_BalanceGet
Call graph
mapl_balanceget calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize