MAPL_CommsAllGather_I4_1 – MAPL
MAPL_CommsAllGather_I4_1 Subroutine
17 statements
Source File
private subroutine MAPL_CommsAllGather_I4_1(vm, sendbuf, sendcnt, recvbuf, recvcnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
integer, intent(in) :: sendbuf(:)
integer, intent(in) :: sendcnt
integer, intent(inout) :: recvbuf(:)
integer, intent(in) :: recvcnt
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commsallgather_i4_1 calls ESMF_VMGet, mpi_allgather, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_commsallgather calls mapl_commsallgather_i4_1
mapl_locstreamcreatexform calls mapl_commsallgather
initialize calls mapl_locstreamcreatexform