MAPL_MemReport – MAPL
MAPL_MemReport Subroutine
23 statements
Source File
public subroutine MAPL_MemReport(comm, file_name, line, decorator, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
character(len=*), intent(in) :: file_name
integer, intent(in) :: line
character(len=*), intent(in), optional :: decorator
integer, intent(out), optional :: rc
Calls
Call graph
mapl_memreport calls mpi_barrier, mpi_comm_rank, mapl_memcommited, mapl_memused, mapl_verify
mapl_memcommited calls mapl_rtrn, get_unit, mapl_return
mapl_memused calls mapl_rtrn, get_unit, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert