MAPL_BcastShared_1DR4 – MAPL
MAPL_BcastShared_1DR4 Subroutine
27 statements
Source File
private subroutine MAPL_BcastShared_1DR4(VM, Data, N, Root, RootOnly, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: VM
real, intent(inout), pointer :: Data(:)
integer, intent(in) :: N
integer, intent(in), optional :: Root
logical, intent(in) :: RootOnly
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_BcastShared_1DR4(VM, Data, N, Root, RootOnly, rc)
    type(ESMF_VM) :: VM
    real,    pointer,  intent(INOUT) :: Data(:)
    integer,           intent(IN   ) :: N
    integer, optional, intent(IN   ) :: Root
    logical,           intent(IN   ) :: RootOnly
    integer, optional, intent(  OUT) :: rc
    integer :: status
    if(.not.MAPL_ShmInitialized) then
       if (RootOnly) then
          _RETURN(ESMF_SUCCESS)
       end if
       call MAPL_CommsBcast(vm, DATA=Data, N=N, ROOT=Root, RC=status)
       _RETURN(STATUS)
    else
       call MAPL_SyncSharedMemory(RC=STATUS)
       _VERIFY(STATUS)
       call MAPL_BroadcastToNodes(Data, N=N, ROOT=Root, rc=status)
       _VERIFY(STATUS)
       call MAPL_SyncSharedMemory(RC=STATUS)
       _VERIFY(STATUS)
    endif
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_BcastShared_1DR4
Call graph
mapl_bcastshared_1dr4 calls mapl_broadcasttonodes, mapl_commsbcast, mapl_syncsharedmemory, mapl_return, mapl_verify
mapl_bcastshared calls mapl_bcastshared_1dr4
mapl_cfioreadbundle calls mapl_bcastshared
mapl_cfiowritebundlepost calls mapl_bcastshared
mapl_locstreamcreatefromfile calls mapl_bcastshared
read_geos_binary calls mapl_bcastshared
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize_subclass calls read_geos_binary
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
esmf_iowrite calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle
initialize_ calls mapl_cfioread, mapl_locstreamcreate
initialize calls mapl_locstreamcreate
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread