MAPL_DeAllocNodeArray_1DR8 – MAPL
MAPL_DeAllocNodeArray_1DR8 Module Procedure
13 statements
Source File
module procedure MAPL_DeAllocNodeArray_1DR8 module subroutine MAPL_DeAllocNodeArray_1DR8(Ptr, rc) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), pointer :: Ptr(:)
integer, intent(out), optional :: rc
Calls
Call graph
mapl_deallocnodearray_1dr8 calls releasesharedmemory, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize