MAPL_ServiceRequestGet – MAPL
MAPL_ServiceRequestGet Subroutine
12 statements
Source File
private subroutine MAPL_ServiceRequestGet(GC, requested_services, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(requestedServiceItemVector), pointer :: requested_services
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_ServiceRequestGet
Source Code
   subroutine MAPL_ServiceRequestGet(GC, requested_services, RC)
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      type(RequestedServiceItemVector), pointer :: requested_services
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      integer :: status
      type (MAPL_MetaComp), pointer     :: MAPLOBJ
      !get MAPL
      call MAPL_InternalStateRetrieve ( GC, MAPLOBJ, RC=status )
      _VERIFY(status)
      requested_services => maplobj%requested_services
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ServiceRequestGet
Call graph
mapl_servicerequestget calls mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
initialize calls initialize_global_time_profiler