MAPL_VarSpecSetBundlePtr – MAPL
MAPL_VarSpecSetBundlePtr Subroutine
12 statements
Source File
private subroutine MAPL_VarSpecSetBundlePtr(SPEC, BUNDLEPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC
type(ESMF_FieldBundle), pointer :: BUNDLEPTR
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecSetBundlePtr
Source Code
   subroutine MAPL_VarSpecSetBundlePtr(SPEC, BUNDLEPTR, RC )
      type (MAPL_VarSpec ),             intent(INOUT)   :: SPEC
      type(ESMF_FieldBundle)  ,         pointer         :: BUNDLEPTR
      integer            , optional   , intent(  OUT)   :: RC
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      SPEC%SPECPtr%BUNDLE => BUNDLEPTR
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecSetBundlePtr
Call graph
mapl_varspecsetbundleptr calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecset calls mapl_varspecsetbundleptr