MAPL_SunOrbitDestroy – MAPL
MAPL_SunOrbitDestroy Subroutine
13 statements
Source File
public subroutine MAPL_SunOrbitDestroy(ORBIT, RC)
The routine MAPL_SunOrbitDestroy Destroys a GEOS_SunOrbit object, deallocating the space used to save the ephemeris.
Arguments
Type Intent Optional Attributes Name
type(MAPL_SunOrbit), intent(inout) :: ORBIT
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_SunOrbitDestroy
Source Code
    subroutine MAPL_SunOrbitDestroy(ORBIT, RC)
! !ARGUMENTS:
       type(MAPL_SunOrbit),    intent(INOUT) :: ORBIT
       integer, optional,      intent(  OUT) :: RC
       character(len=ESMF_MAXSTR), parameter :: IAm = "SunOrbitDestroy"
       if(associated(ORBIT%TH)) deallocate(ORBIT%TH)
       if(associated(ORBIT%ZC)) deallocate(ORBIT%ZC)
       if(associated(ORBIT%ZS)) deallocate(ORBIT%ZS)
       if(associated(ORBIT%PP)) deallocate(ORBIT%PP)
       if(associated(ORBIT%ET)) deallocate(ORBIT%ET)
       ORBIT%CREATED = .FALSE.
       _RETURN(ESMF_SUCCESS)
     end subroutine MAPL_SunOrbitDestroy
Call graph
mapl_sunorbitdestroy calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_genericstatedestroy calls mapl_sunorbitdestroy
mapl_genericfinalize calls mapl_genericstatedestroy
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize