MAPL_FieldCreateNewgrid – MAPL
MAPL_FieldCreateNewgrid Module Function
104 statements
Source File
module function MAPL_FieldCreateNewgrid(FIELD, GRID, lm, newName, RC) result(F) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
type(ESMF_Grid), intent(inout) :: GRID
integer, intent(in), optional :: lm
character(len=*), intent(in), optional :: newName
integer, intent(out), optional :: RC
Return Value type(ESMF_Field)
Calls
Called by
Source Code
  module function MAPL_FieldCreateNewgrid(FIELD, GRID, LM, NEWNAME, RC) RESULT(F)
    type (ESMF_Field), intent(INOUT) :: FIELD !ALT: intent(IN)
    type (ESMF_Grid),  intent(INout) :: GRID
    integer, optional, intent(IN   ) :: lm
    character(len=*), optional, intent(IN) :: newName
    integer, optional, intent(  OUT) :: RC
    type (ESMF_Field)                :: F
    !   we are creating new field so that we can change the grid of the field
    !   (and allocate array accordingly);
    !ALT: This function is currently used only in History for regridding on an output grid
    !ALT halowidth assumed 0
    !      type(ESMF_FieldDataMap) :: datamap
    type (ESMF_Grid)        :: fGRID
    type(ESMF_Array)        :: array
    type (ESMF_LocalArray), target          :: larrayList(1)
    type (ESMF_LocalArray), pointer         :: larray
    integer                                 :: localDeCount
    integer                 :: rank
    integer                 :: newRank
    integer                 :: COUNTS(3)
    !real, pointer           :: VAR_2D(:,:), VAR_3D(:,:,:), VAR_4D(:,:,:,:)
    character(len=ESMF_MAXSTR) :: NAME
    integer                 :: status
    integer                 :: DIMS
    integer                 :: I
    integer, allocatable    :: gridToFieldMap(:)
    integer                 :: gridRank
    integer                 :: fgridRank
    integer                 :: griddedDims
    integer                 :: ungriddedDims
    integer                 :: lb, ub
    integer                 :: lbnds(ESMF_MAXDIM), ubnds(ESMF_MAXDIM)
    character(len=ESMF_MAXSTR) :: newName_
    character(len=ESMF_MAXSTR), parameter :: Iam='MAPL_FieldCreateNewgrid'
    call ESMF_FieldGet(FIELD, grid=fgrid, RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_GridGet(fGRID, dimCount=fgridRank, rc=status)
    _VERIFY(STATUS)
    allocate(gridToFieldMap(fgridRank), stat=status)
    _VERIFY(STATUS)
    call ESMF_FieldGet(FIELD, Array=Array, name=name, &
         gridToFieldMap=gridToFieldMap, RC=STATUS)
    _VERIFY(STATUS)
    griddedDims = fgridRank - count(gridToFieldMap == 0)
    call ESMF_GridGet(GRID, dimCount=gridRank, rc=status)
    _VERIFY(STATUS)
    call ESMF_ArrayGet(array, rank=rank, rc=status)
    _VERIFY(STATUS)
    ungriddedDims = rank - griddedDims
    call MAPL_GridGet(GRID, localCellCountPerDim=COUNTS, RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_ArrayGet(array, localDeCount=localDeCount, rc=status)
    _VERIFY(STATUS)
    _ASSERT(localDeCount == 1, 'MAPL supports only 1 local array')
    call ESMF_ArrayGet(array, localarrayList=larrayList, rc=status)
    _VERIFY(STATUS)
    larray => lArrayList(1) ! alias
    call ESMF_LocalArrayGet(larray, totalLBound=lbnds, totalUBound=ubnds, rc=status)
    _VERIFY(STATUS)
    newRank = rank
    if (griddedDims == 1 .and. gridRank > 1) then
       deallocate(gridToFieldMap)
       allocate(gridToFieldMap(gridRank), stat=status)
       _VERIFY(STATUS)
       gridToFieldMap = 0
       do I = 1, 2
          gridToFieldMap(I) = I
       end do
       newRank = rank + 1
    end if
    if (present(newName)) then
       newName_=newName
    else
       newName_=name
    end if
    if (newRank == 2) then
       F = ESMF_FieldCreate(GRID, typekind=ESMF_TYPEKIND_R4, &
            indexflag=ESMF_INDEX_DELOCAL, &
            name=newName_, gridToFieldMap=gridToFieldMap, RC=STATUS )
       _VERIFY(STATUS)
       DIMS = MAPL_DimsHorzOnly
    else if (newRank == 3) then
       if (present(lm)) then
          lb=1
          ub=lm
       else
          lb = lbnds(griddedDims+1)
          ub = ubnds(griddedDims+1)
       end if
       F = ESMF_FieldCreate(GRID, typekind=ESMF_TYPEKIND_R4, &
            indexflag=ESMF_INDEX_DELOCAL, &
            name=newName_, gridToFieldMap=gridToFieldMap, &
            ungriddedLBound=[lb],ungriddedUBound=[ub],RC=STATUS )
       if (ungriddedDims > 0) then
          DIMS = MAPL_DimsHorzOnly
       else
          DIMS = MAPL_DimsHorzVert
       end if
    else if (newRank == 4) then
       F = ESMF_FieldCreate(GRID, typekind=ESMF_TYPEKIND_R4, &
            indexflag=ESMF_INDEX_DELOCAL, &
            name=newName_, gridToFieldMap=gridToFieldMap, &
            ungriddedLBound=[lbnds(griddedDims+1),lbnds(griddedDims+2)], &
            ungriddedUBound=[ubnds(griddedDims+1),ubnds(griddedDims+2)],RC=STATUS )
       if (ungriddedDims > 0) then
          DIMS = MAPL_DimsHorzOnly
       else
          DIMS = MAPL_DimsHorzVert
       end if
    else
       _FAIL( 'rank > 4 not supported')
    end if
    deallocate(gridToFieldMap)
    call MAPL_FieldCopyAttributes(FIELD_IN=field, FIELD_OUT=f, RC=status)
    _VERIFY(STATUS)
    ! we are saving DIMS attribute in case the FIELD did not contain one
    ! otherwise we will overwrite it
    call ESMF_AttributeSet(F, NAME='DIMS', VALUE=DIMS, RC=STATUS)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end function MAPL_FieldCreateNewgrid
Call graph
mapl_fieldcreatenewgrid calls ESMF_AttributeSet, ESMF_GridGet, esmf_arrayget, esmf_fieldcreate, esmf_fieldget, esmf_localarrayget, mapl_assert, mapl_fieldcopyattributes, mapl_gridget, mapl_return, mapl_verify, mapl_fieldcreatenewgrid
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_fieldcopyattributes calls mapl_fieldcopyattributes, mapl_return, mapl_verify, ESMF_AttributeCopy
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
mapl_fieldcreate calls mapl_fieldcreatenewgrid
addvariable_to_acc_bundle calls mapl_fieldcreate
addvariable_to_output_bundle calls mapl_fieldcreate
create_bracketing_fields calls mapl_fieldcreate, createfilelevbracket
createfilelevbracket calls mapl_fieldcreate
createvariable calls mapl_fieldcreate
esmfl_bundlecpyfield calls mapl_fieldcreate
esmfl_stategetfield calls mapl_fieldcreate
initialize_ calls mapl_fieldcreate, createfilelevbracket
initialize calls mapl_fieldcreate
mapl_gridcompgetfriendlies0 calls mapl_fieldcreate
mapl_statecreatefromspecnew calls mapl_fieldcreate
mapl_statevarreadncpar calls mapl_fieldcreate
mapl_statevarwritencpar calls mapl_fieldcreate
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies0
mapl_varreadncpar calls mapl_statevarreadncpar
mapl_varwritencpar calls mapl_statevarwritencpar
create_bundle_rh calls addvariable_to_acc_bundle, createvariable
createfilemetadata calls createvariable
mapl_genericinitialize calls mapl_statecreatefromspecnew
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
run_ calls create_bracketing_fields
stateregrid calls esmfl_stategetfield