MAPL_TimeStringGet – MAPL
MAPL_TimeStringGet Module Subroutine
18 statements
Source File
module subroutine MAPL_TimeStringGet(TIMESTRING, YY, MM, DD, H, M, S) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: TIMESTRING
integer, intent(out), optional :: YY
integer, intent(out), optional :: MM
integer, intent(out), optional :: DD
integer, intent(out), optional :: H
integer, intent(out), optional :: M
integer, intent(out), optional :: S
Called by
Source Code
  module subroutine MAPL_TimeStringGet(TIMESTRING,YY,MM,DD,H,M,S)
    character(len=*),  intent (IN ) :: TIMESTRING
    integer, optional, intent (OUT) :: YY
    integer, optional, intent (OUT) :: MM
    integer, optional, intent (OUT) :: DD
    integer, optional, intent (OUT) :: H
    integer, optional, intent (OUT) :: M
    integer, optional, intent (OUT) :: S
    integer :: IYY, IMM, IDD, IHH, IMN, ISS
    read(TIMESTRING,'(I4,1X,I2,1X,I2,1X,I2,1X,I2,1X,I2)') IYY,IMM,IDD,IHH,IMN,ISS
    !ALT: SGI compiler does not like this format  read(TIMESTRING,'(I4,"-",I2,"-",I2,"T",I2,":",I2,":",I2)') IYY,IMM,IDD,IHH,IMN,ISS
    if(present(YY)) YY = IYY
    if(present(MM)) MM = IMM
    if(present(DD)) DD = IDD
    if(present(H )) H  = IHH
    if(present(M )) M  = IMN
    if(present(S )) S  = ISS
    return
  end subroutine MAPL_TimeStringGet
Call graph
mapl_timestringget calls mapl_timestringget
mapl_getfieldtimefromfield calls mapl_timestringget, mapl_getfieldtimefromfield
mapl_fieldgettime calls mapl_getfieldtimefromfield