MAPL_CFIOClose – MAPL
MAPL_CFIOClose Subroutine
17 statements
Source File
public subroutine MAPL_CFIOClose(MCFIO, filename, RC)
The subroutine MAPL_CFIOClose only closes the file in MAPL CFIO Object (not a full destroy).
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
character(len=*), intent(in), optional :: filename
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_CFIOClose
Source Code
  subroutine MAPL_CFIOClose( MCFIO, filename, RC )
!
  type(MAPL_CFIO),             intent(INOUT) :: MCFIO
  character(len=*), optional,  intent(IN   ) :: filename
  integer, optional,           intent(  OUT) :: RC
!
  integer :: status
  if (MCFIO%myPE == mCFIO%RootRank) then
     call ESMF_CFIOFileClose(MCFIO%CFIO,rc=status)
     _VERIFY(STATUS)
     if (present(filename)) then
        close(99)
        open (99,file=trim(filename)//".done",form='formatted')
        close(99)
     end if
  end if
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOClose
Call graph
mapl_cfioclose calls esmf_cfiofileclose, mapl_return, mapl_verify
esmf_cfiofileclose calls esmf_cfioget, esmf_cfiosdffileclose
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmf_cfioget calls err
esmf_cfiosdffileclose calls cfio_close
get_error_message calls at
mapl_throw_exception calls initialize
cfio_close calls err, ncclos