MAPL_LocStreamIsAssociated – MAPL
MAPL_LocStreamIsAssociated Function
7 statements
Source File
public function MAPL_LocStreamIsAssociated(LocStream, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Contents
Source Code
MAPL_LocStreamIsAssociated
Source Code
  logical function MAPL_LocStreamIsAssociated(LocStream, RC)
    type(MAPL_LocStream),                 intent(IN   ) :: LocStream
    integer, optional,                    intent(  OUT) :: RC
    MAPL_LocStreamIsAssociated = associated(LocStream%Ptr)
    _RETURN(ESMF_SUCCESS)
  end function MAPL_LocStreamIsAssociated
Call graph
mapl_locstreamisassociated calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_esmfstatereadfromfile calls mapl_locstreamisassociated
mapl_esmfstatewritetofile calls mapl_locstreamisassociated
mapl_genericinitialize calls mapl_locstreamisassociated
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore
mapl_genericwrapper calls record_component