MAPL_CFIOSetVectorPairs – MAPL
MAPL_CFIOSetVectorPairs Subroutine
56 statements
Source File
private subroutine MAPL_CFIOSetVectorPairs(MCFIO, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(out) :: rc
Calls
Called by
Contents
Source Code
MAPL_CFIOSetVectorPairs
Source Code
  subroutine MAPL_CFIOSetVectorPairs(MCFIO,rc)
    type(MAPL_CFIO), intent(inout) :: MCFIO
    integer,         intent(out  ) :: rc
    integer, allocatable       :: varStart(:)
    integer                    :: l,lm,nn,nv,sgn,k,np
    integer                    :: status
    ! adjust if we have vector pairs
    allocate(varStart(size(MCFIO%VarDims)),stat=status)
    _VERIFY(status)
    nn=0
    STARTVAR: do L=1, size(MCFIO%VarDims)
       if(mCFIO%VarDims(L)==2) then ! Rank == 2
          LM = 1
       elseif(MCFIO%VarDims(L)==3) then ! Rank == 3
          LM = MCFIO%LM
       else
          LM = 0
       endif
       if (L /= 0) then
          varStart(L) = nn + 1
          nn = nn + LM
       end if
    end do STARTVAR
    nn=0
    VECTPAIR: do L=1, size(MCFIO%VarDims)
       if(mCFIO%VarDims(L)==2) then ! Rank == 2
          LM = 1
       elseif(MCFIO%VarDims(L)==3) then ! Rank == 3
          LM = MCFIO%LM
       else
          LM = 0
       endif
       nv = mCFIO%needVar(L)
       if (nv > 0) then
          sgn=1
       else
          sgn = -1
       end if
       do K=1,LM
          nn = nn + 1
          if (nv /= 0) then
             MCFIO%pairList(nn) = sgn*(varStart(abs(nv)) - 1 + k)
          else
             MCFIO%pairList(nn) = 0
          end if
       enddo
    end do VECTPAIR
    deallocate(varStart)
    !Modify KRANK to make sure that for any pair,
    !all of its components are handled by the SAME processor
    do L=1,size(MCFIO%Krank)
       np = MCFIO%pairList(L)
       if (np > 0) then
          ! I am "U"; overwrite location of "V"
          mCFIO%Krank(abs(np)) = mCFIO%Krank(L)
       end if
    enddo
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOSetVectorPairs
Call graph
mapl_cfiosetvectorpairs calls mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_cfiowritebundlepost calls mapl_cfiosetvectorpairs
mapl_cfioreadbundleread calls mapl_cfiosetvectorpairs
mapl_cfiowritebundle calls mapl_cfiowritebundlepost
mapl_cfioreadparallel_ calls mapl_cfioreadbundleread
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
test_main calls esmf_iowrite
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite