MAPL_BundleInit – MAPL
MAPL_BundleInit Subroutine
38 statements
Source File
private subroutine MAPL_BundleInit(GC, STATE, BUNDLENAME, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(in) :: STATE
character(len=*), intent(in) :: BUNDLENAME
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_BundleInit
Source Code
   subroutine MAPL_BundleInit(GC,STATE,BUNDLENAME,RC)
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      type(ESMF_State),              intent(IN   )  :: STATE
      character (len=*),             intent(IN   )  :: BUNDLENAME
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)            :: IAm='MAPL_BundleInit'
      integer                               :: status
      character(len=ESMF_MAXSTR)            :: comp_name
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: MAPLOBJ
      type (ESMF_FieldBundle)                          :: BUNDLE
      type (ESMF_Field)                           :: FIELD
      type (MAPL_VarSpec),               pointer  :: INTERNAL_SPEC(:)
      integer                                     :: I
      integer                                     :: STAT
      !EOP
      ! Get my name and set-up traceback handle
      ! ---------------------------------------
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      ! Retrieve the pointer to the internal state
      ! --------------------------------------------
      call MAPL_InternalStateRetrieve(GC, MAPLOBJ, RC=status)
      _VERIFY(status)
      call ESMF_StateGet(STATE, BUNDLENAME, BUNDLE, RC=status)
      _VERIFY(status)
      INTERNAL_SPEC => MAPLOBJ%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS
      if (.not. associated(INTERNAL_SPEC)) then
         _RETURN(ESMF_FAILURE)
      end if
      do I = 1, size(INTERNAL_SPEC)
         call MAPL_VarSpecGet(INTERNAL_SPEC(I), FIELD=FIELD, STAT=STAT, RC=status)
         _VERIFY(status)
         if (ior(STAT, MAPL_FriendlyVariable) /= 0) then
            cycle
         end if
         !ALT: alternatevly, we could get the field from the INTERNAL_ESMF_STATE
         call MAPL_FieldBundleAdd(bundle, field, rc=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_BundleInit
Call graph
mapl_bundleinit calls ESMF_GridCompGet, esmf_stateget, mapl_fieldbundleadd, mapl_varspecget, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldbundleadd, esmf_fieldget
get_error_message calls at
mapl_internalstatecreate calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
initialize calls initialize_global_time_profiler