MAPL_FieldCreateEmpty – MAPL
MAPL_FieldCreateEmpty Module Function
14 statements
Source File
module function MAPL_FieldCreateEmpty(NAME, GRID, RC) result(FIELD) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: NAME
type(ESMF_Grid), intent(inout) :: GRID
integer, intent(out), optional :: RC
Return Value type(ESMF_Field)
Calls
Called by
Source Code
  module function MAPL_FieldCreateEmpty(NAME, GRID, RC) RESULT(FIELD)
    character(len=*),  intent(IN   ) :: NAME
    type (ESMF_Grid),  intent(INout) :: GRID
    integer, optional, intent(  OUT) :: RC
    type (ESMF_Field)                :: FIELD
    character(len=ESMF_MAXSTR),parameter   :: IAm=" MAPL_FieldCreateEmpty"
    integer                                :: STATUS
    FIELD = ESMF_FieldEmptyCreate(name=name, rc=status)
    _VERIFY(STATUS)
    call ESMF_FieldEmptySet(FIELD, &
         grid=GRID, &
         staggerloc = ESMF_STAGGERLOC_CENTER,        &
         rc = status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end function MAPL_FieldCreateEmpty
Call graph
mapl_fieldcreateempty calls esmf_fieldemptycreate, esmf_fieldemptyset, mapl_return, mapl_verify, mapl_fieldcreateempty
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_ calls mapl_fieldcreateempty, mapl_genericinitialize
mapl_fieldcreater4 calls mapl_fieldcreateempty, mapl_fieldcreater4
mapl_fieldcreaterename calls mapl_fieldcreateempty, mapl_fieldcreaterename
mapl_fieldsplit calls mapl_fieldcreateempty, mapl_fieldsplit
mapl_statecreatefromspecnew calls mapl_fieldcreateempty
mapl_genericinitialize calls mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
mapl_fieldcreate calls mapl_fieldcreater4, mapl_fieldcreaterename
initialize calls mapl_fieldsplit, mapl_genericinitialize, mapl_statecreatefromspec
mapl_readforcingx calls mapl_statecreatefromvarspecnew
putfieldinbundle__ calls mapl_fieldsplit