MAPL_DeAllocNodeArray_Tiling – MAPL
MAPL_DeAllocNodeArray_Tiling Subroutine
16 statements
Source File
private subroutine MAPL_DeAllocNodeArray_Tiling(Ptr, rc)
Arguments
Type Intent Optional Attributes Name
type(XTile), pointer :: Ptr(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_DeAllocNodeArray_Tiling
Source Code
    subroutine MAPL_DeAllocNodeArray_Tiling(Ptr,rc)
      type(XTile),  pointer              :: Ptr(:)
      integer, optional, intent(OUT) :: rc
      type(c_ptr) :: Caddr
      integer     :: status
      character(len=*), parameter :: Iam = 'MAPL_DeAllocNodeArray_Tiling'
      if(.not.MAPL_ShmInitialized) then
         _RETURN(MAPL_NoShm)
      endif
      Caddr = C_Loc(Ptr(lbound(Ptr,1)))
      call ReleaseSharedMemory(Caddr,rc=STATUS)
      _VERIFY(status)
      _RETURN(_SUCCESS)
    end subroutine MAPL_DeAllocNodeArray_Tiling
Call graph
mapl_deallocnodearray_tiling calls releasesharedmemory, mapl_return, mapl_verify
releasesharedmemory calls releasesharedmemory, mapl_return, mapl_assert, shmctl, shmdt, mpi_barrier, segs
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_deallocnodearray calls mapl_deallocnodearray_tiling