MAPL_GetLogger_gc – MAPL
MAPL_GetLogger_gc Subroutine
12 statements
Source File
private subroutine MAPL_GetLogger_gc(gc, lgr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
class(Logger), pointer :: lgr
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_GetLogger_gc(gc, lgr, rc)
      type(ESMF_GridComp), intent(inout) :: gc
      class(Logger), pointer :: lgr
      integer, optional, intent(out) :: rc
      type (MAPL_MetaComp), pointer :: meta
      integer :: status
      call MAPL_GetObjectFromGC(gc, meta, rc=status)
      _VERIFY(status)
      lgr => meta%get_logger()
      _RETURN(_SUCCESS)
   end subroutine MAPL_GetLogger_gc
Call graph
mapl_getlogger_gc calls mapl_getobjectfromgc, get_logger, mapl_return, mapl_verify
mapl_getobjectfromgc calls mapl_internalstateget
get_logger calls get_logger, get_component
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_getlogger calls mapl_getlogger_gc
initialize_gc calls mapl_getlogger, mapl_clockinit, perpetual_clock
initialize_ calls mapl_getlogger
mapl_clockinit calls mapl_getlogger
perpetual_clock calls mapl_getlogger
warn_empty calls mapl_getlogger
mapl_esmfstatereadfromfile calls warn_empty
mapl_esmfstatewritetofile calls warn_empty
step calls perpetual_clock
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
run_mapl_gridcomp calls step
step_model calls step