MAPL_CollectiveGather3D – MAPL
MAPL_CollectiveGather3D Subroutine
61 statements
Source File
public subroutine MAPL_CollectiveGather3D(Grid, LocArray, GlobArray, CoresPerNode, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: Grid
real, intent(in) :: LocArray(:,:,:)
real, pointer :: GlobArray(:,:,:)
integer, intent(in), optional :: CoresPerNode
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_CollectiveGather3D
Source Code
  subroutine MAPL_CollectiveGather3D(Grid, LocArray, GlobArray, &
                                     CoresPerNode, rc)
    type (ESMF_Grid),        intent(INout) :: Grid
    real,                    intent(IN   ) :: LocArray(:,:,:)
    real, pointer                          :: GlobArray(:,:,:)
    integer, optional,       intent(In   ) :: CoresPerNode
    integer, optional,       intent(  OUT) :: rc
! Locals
!-------
    integer                       :: status
    type (MAPL_CommRequest)       :: reqs(size(LocArray,3))
    integer                       :: root(size(LocArray,3))
    integer                       :: NumCores, Nnodes
    integer                       :: nn
    integer                       :: LM, L, nc, npes, mype, dims(5)
    type(ESMF_VM)                 :: VM
    integer                       :: comm
! Begin
!------
    _ASSERT(.not.associated(GlobArray), 'GlobalArray already associated')
    call ESMF_VMGetCurrent(VM,         RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_VMGet(VM, petcount=npes, localpet=MYPE, mpiCommunicator=comm, RC=STATUS)
    _VERIFY(STATUS)
    if(present(CoresPerNode)) then
       NumCores = CoresPerNode
    else
       NumCores = MAPL_CoresPerNodeGet(comm,rc=status)
       _VERIFY(STATUS)
    end if
    LM     = size(LocArray,3)
    nNodes = size(MAPL_NodeRankList)
    call MAPL_RoundRobinPEList(Root, nNodes, RC=STATUS)
    _VERIFY(STATUS)
    if(any(root==mype)) then
       call MAPL_GridGet ( grid, globalCellCountPerDim=DIMS, RC=STATUS)
       _VERIFY(STATUS)
       nc = count(Root==mype)
       allocate(GlobArray(dims(1),dims(2),nc),stat=STATUS)
       _VERIFY(STATUS)
    else
       allocate(GlobArray(1,1,1)             ,stat=STATUS)
       _VERIFY(STATUS)
    endif
    nn = 0
    do L=1,LM
       if(root(L) == mype) then
          nn = nn + 1
          call MAPL_CreateRequest(GRID, Root(L), reqs(L), tag=L,    &
                               RequestType=MAPL_IsGather,           &
                               DstArray=GlobArray(:,:,nn),          &
                               PrePost=.true.,             RC=STATUS)
          _VERIFY(STATUS)
       else
          call MAPL_CreateRequest(GRID, Root(L), reqs(L), tag=L,    &
                               RequestType=MAPL_IsGather,           &
                               DstArray=GlobArray(:,:,1),           &
                               PrePost=.true.,             RC=STATUS)
          _VERIFY(STATUS)
       end if
    enddo  ! Do not fuse with next
    do L=1,LM
       call MAPL_ArrayIGather (LocArray(:,:,L), reqs(L),  RC=STATUS)
       _VERIFY(STATUS)
    enddo  ! Do not fuse with next
    do L=1,LM
       call MAPL_CollectiveWait(reqs(L), rc=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CollectiveGather3D
Call graph
mapl_collectivegather3d calls mapl_return, mapl_assert, mapl_corespernodeget, esmf_vmgetcurrent, esmf_vmget, mapl_verify, mapl_roundrobinpelist, mapl_gridget, mapl_createrequest, mapl_arrayigather, mapl_collectivewait
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_corespernodeget calls mapl_corespernodeget, mapl_return, mapl_verify, mapl_getnodeinfo
mapl_verify calls mapl_throw_exception
mapl_roundrobinpelist calls mapl_return, mapl_verify, mapl_getnewrank
mapl_gridget calls mapl_return, mapl_verify, esmf_gridget, esmf_attributeget, mapl_gridhasde
mapl_createrequest calls mapl_return, mapl_assert, esmf_vmgetcurrent, esmf_vmget, mapl_verify, mpi_irecv, esmf_gridget, mapl_distgridget
mapl_arrayigather calls mapl_arrayigather_r4_2
mapl_collectivewait calls mapl_return, mapl_verify, mpi_wait, mpi_recv
mapl_arrayigather_r4_2 calls mapl_return, mapl_verify, mpi_isend
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_getnewrank calls mapl_getnewrank
mapl_gridhasde calls mapl_return, mapl_verify, esmf_gridget, esmf_distgridget, esmf_delayoutget
mapl_distgridget calls mapl_verify, esmf_distgridget
regrid_scalar_3d_real32 calls mapl_collectivegather3d