MAPL_PackTime – MAPL
MAPL_PackTime Module Subroutine
7 statements
Source File
module subroutine MAPL_PackTime(TIME, IYY, IMM, IDD) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: TIME
integer, intent(in) :: IYY
integer, intent(in) :: IMM
integer, intent(in) :: IDD
Called by
Source Code
  module subroutine MAPL_PackTime(TIME,IYY,IMM,IDD)
    integer, intent (OUT) :: TIME
    integer, intent (IN ) :: IYY
    integer, intent (IN ) :: IMM
    integer, intent (IN ) :: IDD
    TIME=IYY*10000+IMM*100+IDD
  end subroutine MAPL_PackTime
Call graph
mapl_packtime calls mapl_packtime
extract_ calls mapl_packtime
getlevs calls mapl_packtime
mapl_extdatainterpfield calls mapl_packtime
mapl_statesettimestamp calls mapl_packtime
run_ calls mapl_packtime, extract_, mapl_extdatainterpfield, updatebrackettime
updatebrackettime calls mapl_packtime
initialize_ calls getlevs
mapl_readforcingx calls mapl_statesettimestamp
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx