MAPL_LocStreamTransformG2T – MAPL
MAPL_LocStreamTransformG2T Subroutine
114 statements
Source File
private subroutine MAPL_LocStreamTransformG2T(LocStream, OUTPUT, INPUT, MASK, GRID_ID, GLOBAL, ISMINE, INTERP, TRANSPOSE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
real, intent(inout) :: OUTPUT(:)
real, intent(inout) :: INPUT(:,:)
logical, intent(in), optional :: MASK(:)
integer, intent(in), optional :: GRID_ID
logical, intent(in), optional :: GLOBAL
logical, intent(in), optional :: ISMINE(:)
logical, intent(in), optional :: INTERP
logical, intent(in), optional :: TRANSPOSE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_LocStreamTransformG2T
Source Code
subroutine MAPL_LocStreamTransformG2T (LocStream, OUTPUT, INPUT,      &
                                        MASK, GRID_ID, GLOBAL, ISMINE, &
                                        INTERP, TRANSPOSE, RC )
  !ARGUMENTS:
  type(MAPL_LocStream),      intent(IN ) :: LocStream
  real,                      intent(INOUT) :: OUTPUT(:)
  real,                      intent(INOUT) :: INPUT(:,:)
  logical, optional,         intent(IN ) :: MASK(:), ISMINE(:), INTERP
  logical, optional,         intent(IN ) :: GLOBAL
  integer, optional,         intent(IN ) :: GRID_ID
  logical, optional,         intent(IN ) :: TRANSPOSE
  integer, optional,         intent(OUT) :: RC
  !EOPI
! Local variables
  integer                    :: STATUS
  integer                    :: N, I1, IN, J1, JN, I, J, IM, JM
  logical,      allocatable  :: usableMASK(:)
  logical                    :: usableATTACHED
  logical                    :: usableGLOBAL
  logical                    :: usableINTERP
  logical                    :: usableTRANSPOSE
  real, pointer              :: ghostedINPUT(:,:)
  real                       :: D(-1:1,-1:1)
  real                       :: val, wt
  integer, parameter :: HALOWIDTH = 1
  _UNUSED_DUMMY(ISMINE)
  IM = size(INPUT,1)
  JM = size(INPUT,2)
  if(present(INTERP)) then
     usableINTERP = INTERP
  else
     usableINTERP = .false.
  end if
  if(present(GRID_ID)) then
     usableATTACHED = .false.
  else
     usableATTACHED = .true.
  end if
  if(present(GLOBAL)) then
     usableGLOBAL = GLOBAL
  else
     usableGLOBAL = .false.
  end if
  if(present(TRANSPOSE)) then
     usableTRANSPOSE = TRANSPOSE
  else
     usableTRANSPOSE = .false.
  end if
! Make sure Location stream has been created...
!----------------------------------------------
  _ASSERT(associated(LocStream%Ptr),'needs informative message')
! and a grid attached...
!-----------------------
  if (usableATTACHED) then
     _ASSERT(LocStream%Ptr%Current_Tiling > 0,'needs informative message')
! that's the size of the output array
!------------------------------------
     call MAPL_GRID_INTERIOR  (LocStream%Ptr%GRID, I1,IN,J1,JN)
     _ASSERT(IN-I1+1==IM,'needs informative message')
     _ASSERT(JN-J1+1==JM,'needs informative message')
  else
     _ASSERT(GRID_ID <= LocStream%Ptr%N_GRIDS,'needs informative message')
  endif
! Make usable mask from optional argument
!----------------------------------------
  allocate(usableMASK(size(OUTPUT)), STAT=STATUS)
  _VERIFY(STATUS)
  if (present(MASK)) then
     usableMASK = MASK
  else
     usableMASK = .TRUE.
  end if
  if(usableINTERP) then
     allocate(ghostedINPUT(1-HALOWIDTH:IM+HALOWIDTH,1-HALOWIDTH:JM+HALOWIDTH),STAT=STATUS)
     _VERIFY(STATUS)
     ghostedINPUT = MAPL_UNDEF ! ALT: this initializion should not be necessary
                               ! but ifort is not happy in SendRecv
     ghostedINPUT(1:IM,1:JM) = INPUT
     call ESMFL_HALO(LocStream%Ptr%GRID, ghostedINPUT, rc=status)
  end if
! Fill output subject to mask
!----------------------------
  if (usableTRANSPOSE) then
      INPUT =0.
  endif
  if (usableGLOBAL) then
     PRINT *, 'IN G2T GLOBAL NO LONGER VALID ARGUMENT'
     _FAIL('needs informative message')
  else
     do N = 1, size(OUTPUT)
        if(usableMASK(N)) then
           if(usableINTERP) then
              OUTPUT(N) = 0.0
              WT        = 0.0
              D         = LOCSTREAM%Ptr%D(:,:,N)
              do J=-1,1
                 do I=-1,1
                    val = GHOSTEDINPUT(LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I+I, &
                                       LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J+J  )
                    if(VAL /= MAPL_Undef) then
                       OUTPUT(N) = OUTPUT(N) + ( VAL * D(I,J) )
                       wt = wt + D(I,J)
                    endif
                 end do
              end do
              if(WT/=0.0) then
                 OUTPUT(N) = OUTPUT(N)/WT
              else
                 OUTPUT(N) = MAPL_Undef
              end if
           else
              if (usableTRANSPOSE) then
                  INPUT(LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I, &
                        LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J  ) = &
                  INPUT(LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I, &
                        LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J  ) + OUTPUT(N)
              else
                  OUTPUT(N) = INPUT(LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I, &
                                LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J  )
              endif
           end if
        end if
     end do
     if (usableTRANSPOSE) then
         OUTPUT=0.
     endif
  endif
  if(usableINTERP) then
     deallocate(ghostedINPUT,STAT=STATUS)
     _VERIFY(STATUS)
  end if
  deallocate(usableMASK)
  _RETURN(ESMF_SUCCESS)
end subroutine MAPL_LocStreamTransformG2T
Call graph
mapl_locstreamtransformg2t calls mapl_assert, mapl_verify, esmfl_halo, mapl_grid_interior, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
esmfl_halo calls esmfl_halo_r4_2d
mapl_grid_interior calls mapl_grid_interior, esmf_gridget, esmf_distgridget, mapl_distgridget, esmf_delayoutget
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
esmfl_halo_r4_2d calls mapl_assert, mapl_verify, mapl_return, esmf_gridget, esmf_distgridget, mapl_distgridget, esmf_delayoutget, esmf_vmget, mapl_getimsjms, mapl_gridget, get_factory, mapl_commssendrecv
mapl_distgridget calls mapl_verify, esmf_distgridget
mapl_getimsjms calls mapl_assert, mapl_verify, mapl_return, mapl_sort
mapl_gridget calls mapl_verify, mapl_return, esmf_gridget, esmf_attributeget, mapl_gridhasde
get_factory calls mapl_verify, mapl_return
mapl_commssendrecv calls mapl_commssendrecv_r4_1, mapl_commssendrecv_i4_0, mapl_commssendrecv_r4_2, mapl_commssendrecv_r8_1, mapl_commssendrecv_r4_0, mapl_commssendrecv_r8_2
mapl_locstreamtransformfield calls mapl_locstreamtransformg2t
mapl_locstreamtransform calls mapl_locstreamtransformg2t, mapl_locstreamtransformfield
regridtransform calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
run calls regridtransform, regridtransformt2g2g, regridtransformt2g