MAPL_ExchangeGridGet – MAPL
MAPL_ExchangeGridGet Subroutine
18 statements
Source File
public subroutine MAPL_ExchangeGridGet(GC, EXCH, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_LocStream), intent(inout) :: EXCH
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_ExchangeGridGet
Source Code
   subroutine MAPL_ExchangeGridGet ( GC, EXCH, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp), intent(INout) :: GC     ! Gridded component
      type(MAPL_LocStream),intent(INOUT) :: EXCH   ! Exchange grid
      integer, optional,   intent(  OUT) :: RC     ! Error code:
      !EOPI
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)    :: IAm
      character(len=ESMF_MAXSTR)    :: comp_name
      integer                       :: status
      ! Local derived type aliases
      type (MAPL_MetaComp),pointer     :: STATE
      Iam = "MAPL_ExchangeGridGet"
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      ! Retrieve the pointer to the internal state.
      ! -------------------------------------------
      call MAPL_InternalStateGet ( GC, STATE, RC=status)
      _VERIFY(status)
      EXCH = STATE%EXCHANGEGRID
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ExchangeGridGet
Call graph
mapl_exchangegridget calls ESMF_GridCompGet, mapl_internalstateget, mapl_return, mapl_verify
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize