MAPL_StateEval – MAPL
MAPL_StateEval Subroutine
39 statements
Source File
public subroutine MAPL_StateEval(state, expression, field, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: state
character(len=*), intent(in) :: expression
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_StateEval(state,expression,field,rc)
    type(ESMF_State),        intent(in   ) :: state
    character(len=*),        intent(in   ) :: expression
    type(ESMF_Field),        intent(inout) :: field
    integer, optional,       intent(out  ) :: rc
    character(len=ESMF_MAXSTR), allocatable :: fieldNames(:)
    integer                              :: varCount
    type(ESMF_Field)                     :: state_field
    integer                              :: i
    type(tComp)                          :: pcode
    logical, allocatable                 :: needed(:)
    logical                              :: isConformal
    integer :: status
    call ESMF_StateGet(state,ITEMCOUNT=varCount,_RC)
    allocate(fieldnames(varCount),needed(varCount))
    call ESMF_StateGet(state,itemnamelist=fieldNames,_RC)
    ! confirm that each needed field is conformal
    call CheckSyntax(expression,fieldNames,needed,_RC)
    do i=1,varCount
       if (needed(i)) then
          call ESMF_StateGet(state,fieldNames(i),field=state_field,_RC)
          isConformal = FieldsAreBroadcastConformable(state_field,field,_RC)
          if (.not.isConformal) then
             _FAIL('needs informative message')
          end if
       end if
    end do
    call parsef (pcode, expression, fieldNames, field, _RC)
    call evalf(pcode,state,fieldNames,field,_RC)
    call bytecode_dealloc(pcode,_RC)
    deallocate(fieldNames,needed)
    end subroutine MAPL_StateEval
Call graph
mapl_stateeval calls esmf_stateget, fieldsarebroadcastconformable, mapl_assert, bytecode_dealloc, checksyntax, evalf, mapl_verify, parsef
fieldsarebroadcastconformable calls are_broadcast_conformable
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
bytecode_dealloc calls mapl_verify, mapl_fielddestroy, mapl_return
checksyntax calls mapl_assert, checkundef, mapl_return, mathfunctionindex, parseerrmsg, realnum, removespaces, replace, variableindex
evalf calls esmf_stateget, mapl_verify, fieldcopybroadcast, fieldset, field_binary, field_unary, fieldnegate, mapl_return
mapl_verify calls mapl_throw_exception
parsef calls checksyntax, mapl_verify, compile, mapl_return, removespaces, replace
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
initialize_ calls fillstate
run_ calls calcderivedfield, evaluate_derived_field, fillstate
run calls mapl_runexpression
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem