MAPL_Am_I_Rank_Only – MAPL
MAPL_Am_I_Rank_Only Function
12 statements
Source File
private function MAPL_Am_I_Rank_Only(rank) result(R)
Arguments
Type Intent Optional Attributes Name
integer, optional :: rank
Return Value logical
Calls
Called by
Contents
Call graph
mapl_am_i_rank_only calls esmf_vmgetcurrent, mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout
mapl_am_i_rank_vm calls esmf_vmget
mapl_am_i_rank_layout calls mapl_am_i_rank, esmf_delayoutget
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root calls mapl_am_i_root_vm, mapl_am_i_root_layout