MAPL_StateAddImportSpec_ – MAPL
MAPL_StateAddImportSpec_ Subroutine
56 statements
Source File
private subroutine MAPL_StateAddImportSpec_(GC, SHORT_NAME, LONG_NAME, UNITS, DIMS, VLOCATION, DATATYPE, NUM_SUBTILES, REFRESH_INTERVAL, AVERAGING_INTERVAL, HALOWIDTH, PRECISION, DEFAULT, RESTART, UNGRIDDED_DIMS, FIELD_TYPE, STAGGERING, ROTATION, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SHORT_NAME
character(len=*), intent(in), optional :: LONG_NAME
character(len=*), intent(in), optional :: UNITS
integer, intent(in), optional :: DIMS
integer, intent(in), optional :: VLOCATION
integer, intent(in), optional :: DATATYPE
integer, intent(in), optional :: NUM_SUBTILES
integer, intent(in), optional :: REFRESH_INTERVAL
integer, intent(in), optional :: AVERAGING_INTERVAL
integer, intent(in), optional :: HALOWIDTH
integer, intent(in), optional :: PRECISION
real, intent(in), optional :: DEFAULT
integer, intent(in), optional :: RESTART
integer, intent(in), optional :: UNGRIDDED_DIMS(:)
integer, intent(in), optional :: FIELD_TYPE
integer, intent(in), optional :: STAGGERING
integer, intent(in), optional :: ROTATION
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_StateAddImportSpec_(GC, SHORT_NAME, LONG_NAME,               &
        UNITS,  Dims, VLocation,                 &
        DATATYPE,NUM_SUBTILES, REFRESH_INTERVAL, &
        AVERAGING_INTERVAL, HALOWIDTH, PRECISION, DEFAULT,  &
        RESTART, UNGRIDDED_DIMS, FIELD_TYPE,     &
        STAGGERING, ROTATION, RC)
      !ARGUMENTS:
      type (ESMF_GridComp)            , intent(INOUT)   :: GC
      character (len=*)               , intent(IN)      :: SHORT_NAME
      character (len=*)  , optional   , intent(IN)      :: LONG_NAME
      character (len=*)  , optional   , intent(IN)      :: UNITS
      integer            , optional   , intent(IN)      :: DIMS
      integer            , optional   , intent(IN)      :: DATATYPE
      integer            , optional   , intent(IN)      :: NUM_SUBTILES
      integer            , optional   , intent(IN)      :: VLOCATION
      integer            , optional   , intent(IN)      :: REFRESH_INTERVAL
      integer            , optional   , intent(IN)      :: AVERAGING_INTERVAL
      integer            , optional   , intent(IN)      :: HALOWIDTH
      integer            , optional   , intent(IN)      :: PRECISION
      real               , optional   , intent(IN)      :: DEFAULT
      integer            , optional   , intent(IN)      :: RESTART
      integer            , optional   , intent(IN)      :: UNGRIDDED_DIMS(:)
      integer            , optional   , intent(IN)      :: FIELD_TYPE
      integer            , optional   , intent(IN)      :: STAGGERING
      integer            , optional   , intent(IN)      :: ROTATION
      integer            , optional   , intent(OUT)     :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddImportSpec"
      integer                               :: status
      integer                               :: usable_AI
      integer                               :: usable_RI
      integer                               :: usable_RS
      real                                  :: dt
      type (ESMF_Config)                    :: CF
      type (MAPL_MetaComp), pointer         :: STATE
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      CF = STATE%CF
      !  Get the clock increment interval
      call ESMF_ConfigGetAttribute( CF, dt,  Label="RUN_DT:", RC=status)
      _VERIFY(status)
      if (present(REFRESH_INTERVAL)) then
         usable_RI = REFRESH_INTERVAL
      else
         usable_RI = nint(dt)
      endif
      if (present(AVERAGING_INTERVAL)) then
         usable_AI = AVERAGING_INTERVAL
      else
         usable_AI = nint(dt)
      endif
      if (present(Restart)) then
         usable_RS  = Restart
      else
         usable_RS = MAPL_RestartOptional
      endif
      if (present(DIMS)) then
         _ASSERT(DIMS /= MAPL_DimsNone,'needs informative message')
      end if
      call MAPL_VarSpecCreateInListNew(STATE%COMPONENT_SPEC%IMPORT,               &
           LONG_NAME  = LONG_NAME,                                               &
           UNITS      = UNITS,                                                   &
           SHORT_NAME = SHORT_NAME,                                              &
           DIMS       = DIMS,                                                    &
           STAT       = DATATYPE,                                                &
           NUM_SUBTILES=NUM_SUBTILES,                                            &
           ACCMLT_INTERVAL= usable_AI,                                           &
           COUPLE_INTERVAL= usable_RI,                                           &
           VLOCATION  = VLOCATION,                                               &
           HALOWIDTH  = HALOWIDTH,                                               &
           PRECISION  = PRECISION,                                               &
           RESTART    = usable_RS,                                               &
           DEFAULT    = DEFAULT,                                                 &
           UNGRIDDED_DIMS = UNGRIDDED_DIMS,                                      &
           FIELD_TYPE = FIELD_TYPE,                                              &
           STAGGERING = STAGGERING,                                              &
           ROTATION = ROTATION,                                                  &
           RC=status  )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddImportSpec_
Call graph
mapl_stateaddimportspec_ calls ESMF_ConfigGetAttribute, mapl_assert, mapl_internalstateretrieve, mapl_return, mapl_varspeccreateinlistnew, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspeccreateinlistnew calls mapl_assert, mapl_return, mapl_verify, update_legacy, vector_push_back
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
update_legacy calls of
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
mapl_addimportspec calls mapl_stateaddimportspec_
addnewspec calls mapl_addimportspec
addstate calls addnewspec
setservices calls addstate