MAPL_MemUtilsWriteComm – MAPL
MAPL_MemUtilsWriteComm Subroutine
90 statements
Source File
private subroutine MAPL_MemUtilsWriteComm(text, Comm, always, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: text
integer, optional :: Comm
logical, intent(in), optional :: always
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_MemUtilsWriteComm
Source Code
  subroutine MAPL_MemUtilsWriteComm( text, comm, always, RC )
    character(len=*), intent(in) :: text
    integer, optional  :: Comm
    logical, intent(in), optional :: always
    integer, optional, intent(OUT  ) :: RC
    real :: mhwm, mrss, memused, swapused
    real :: mmin, mmax, mavg, mstd
    real :: gmin, gmax, gavg, gstd
    real :: lhwm, ghwm
    real :: lmem, gmem, lswap, gswap
    real :: commitlimit, committed_as
    real :: lcommitlimit, lcommitted_as
    real :: gcommitlimit, gcommitted_as
    integer :: npes
!memuse is an external function: works on SGI
!use #ifdef to generate equivalent on other platforms.
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_MemUtilsWriteComm"
    integer :: status
    character(len=ESMF_MAXSTR) :: outString
    integer :: comm_
    if (present(comm)) then
       comm_=comm
    else
       comm_=MPI_COMM_WORLD
    end if
    if( PRESENT(always) )then
        if( .NOT.always ) then
            _RETURN(ESMF_SUCCESS)
        endif
    else
        if( DISABLED ) then
            _RETURN(ESMF_SUCCESS)
        endif
    end if
#if defined(__sgi) || defined(__aix) || defined(__SX)
    m = memuse()*1e-3
#else
    call mem_dump(mhwm, mrss, memused, swapused, commitlimit, committed_as)
#endif
    call MPI_Comm_Size(comm_,npes,status)
    if (MAPL_MemUtilsMode == MAPL_MemUtilsModeFull) then
       lhwm = mhwm; call MPI_AllReduce(lhwm,ghwm,1,MPI_REAL,MPI_MAX,comm_,status)
       _VERIFY(STATUS)
       mmin = mrss; call MPI_AllReduce(mmin,gmin,1,MPI_REAL,MPI_MIN,comm_,status)
       _VERIFY(STATUS)
       mmax = mrss; call MPI_AllReduce(mmax,gmax,1,MPI_REAL,MPI_MAX,comm_,status)
       _VERIFY(STATUS)
       mavg = mrss; call MPI_AllReduce(mavg,gavg,1,MPI_REAL,MPI_SUM,comm_,status)
       _VERIFY(STATUS)
       gavg = gavg/npes
       mstd = (mrss-gavg)**2; call MPI_AllReduce(mstd,gstd,1,MPI_REAL,MPI_SUM,comm_,status)
       gstd = sqrt( gstd/npes )
       gmax_save = gmax
       lcommitlimit  = commitlimit;  call MPI_AllReduce(lcommitlimit,gcommitlimit,1,MPI_REAL,MPI_MAX,comm_,status)
       _VERIFY(STATUS)
       lcommitted_as = committed_as; call MPI_AllReduce(lcommitted_as,gcommitted_as,1,MPI_REAL,MPI_MAX,comm_,status)
       _VERIFY(STATUS)
    end if
    if (MAPL_MemUtilsMode == MAPL_MemUtilsModeFull .or. MAPL_MemUtilsMode == MAPL_MemUtilsModeBase) then
       lmem  = memused;  call MPI_AllReduce(lmem,gmem,1,MPI_REAL,MPI_MAX,comm_,status)
       _VERIFY(STATUS)
       lswap = swapused; call MPI_AllReduce(lswap,gswap,1,MPI_REAL,MPI_MAX,comm_,status)
       _VERIFY(STATUS)
    end if
    if (MAPL_MemUtilsMode == MAPL_MemUtilsModeBase) then
       write(outString,'(a64,2es11.3)') &
            'Mem/Swap Used (MB) at '//trim(text)//'=', gmem, gswap
       call WRITE_PARALLEL(trim(outString),format='(a132)')
    end if
    if (MAPL_MemUtilsMode == MAPL_MemUtilsModeFull) then
       write(outString,'(a64,5es11.3)') &
            'Memuse(MB) at '//trim(text)//'=', ghwm, gmax, gmin, gavg, gmax-gmax_save
       gmax_save = gmax
       call WRITE_PARALLEL(trim(outString),format='(a132)')
       write(outString,'(a64,2es11.3)') &
            'Mem/Swap Used (MB) at '//trim(text)//'=', gmem, gswap
       call WRITE_PARALLEL(trim(outString),format='(a132)')
       write(outString,'(a64,2es11.3)') &
            'CommitLimit/Committed_AS (MB) at '//trim(text)//'=', gcommitlimit, gcommitted_as
       call WRITE_PARALLEL(trim(outString),format='(a132)')
    end if
    if (MAPL_MemUtilsMode == MAPL_MemUtilsModeNode) then
       if (MAPL_AmNodeRoot) then
          write(*,'(a64,i3,a2,es11.3)')'Memory use at '//trim(text)//' on node ',MAPL_MyNodeNum,': ',memused
       end if
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_MemUtilsWriteComm
Call graph
mapl_memutilswritecomm calls write_parallel, mpi_allreduce, mpi_comm_size, mapl_return, mapl_verify, mem_dump
write_parallel calls write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r4_1, write_parallel_r8_0, write_parallel_r8_1, write_parallel_string_0
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mem_dump calls mapl_return, mapl_verify, get_unit
get_error_message calls at
mapl_throw_exception calls initialize
write_parallel_i4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_i4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_r4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_r4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_r8_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_r8_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_string_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
alloc_ calls mapl_return, mapl_verify, mapl_assert, dealloc_
dealloc_ calls mapl_return, mapl_assert
mapl_memutilswrite calls mapl_memutilswritecomm, mapl_memutilswritevm
mapl_memutilswritevm calls mapl_memutilswritecomm
mapl_genericinitialize calls mapl_memutilswrite
run_mapl_gridcomp calls mapl_memutilswrite
test_main calls mapl_memutilswrite
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
run_gc calls run_mapl_gridcomp
utcfio calls test_main