MAPL_LabelGet – MAPL
MAPL_LabelGet Function
22 statements
Source File
private function MAPL_LabelGet(LINK, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LinkType) :: LINK
integer, intent(out), optional :: RC
Return Value integer
Calls
Called by
Source Code
   integer function MAPL_LabelGet(LINK, RC)
      type (MAPL_LinkType)                       :: LINK
      integer,          optional, intent(  OUT)  :: RC     ! Error code:
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_GetLabel"
      integer                               :: status
      ! Local variables
      ! ---------------
      type (MAPL_MetaComp),              pointer  :: STATE
      type (MAPL_VarSpec),               pointer  :: SPEC(:)
      ! Retrieve the pointer to the internal state of Root.
      ! ----------------------------------------------------
      call MAPL_InternalStateRetrieve ( LINK%GC, STATE, RC=status )
      _VERIFY(status)
      ! Local aliases to the state
      ! ---------------------------------------------------
      if (LINK%StateType == MAPL_Import) then
         SPEC => STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      else if (LINK%StateType == MAPL_Export) then
         SPEC => STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      else
         _RETURN(ESMF_FAILURE)
      end if
      call MAPL_VarSpecGet(SPEC(LINK%SpecId), LABEL = MAPL_LabelGet, RC = status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end function MAPL_LabelGet
Call graph
mapl_labelget calls mapl_varspecget, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_genericsetservices calls mapl_labelget
setservices calls mapl_genericsetservices