MAPL_FieldAllocCommit – MAPL
MAPL_FieldAllocCommit Module Subroutine
301 statements
Source File
module subroutine MAPL_FieldAllocCommit(field, dims, location, typekind, hw, ungrid, default_value, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(in) :: dims
integer, intent(in) :: location
integer, intent(in) :: typekind
integer, intent(in) :: hw
integer, intent(in), optional :: ungrid(:)
real, intent(in), optional :: default_value
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  module subroutine MAPL_FieldAllocCommit(field, dims, location, typekind, &
       hw, ungrid, default_value, rc)
    type(ESMF_Field),               intent(INOUT) :: field
    integer,                        intent(IN   ) :: dims
    integer,                        intent(IN   ) :: location
    integer,                        intent(IN   ) :: typekind
    integer,                        intent(IN   ) :: hw !halowidth
    integer,              optional, intent(IN   ) :: ungrid(:)
    real,                 optional, intent(IN   ) :: default_value
    integer,              optional, intent(  OUT) :: rc
    integer                               :: status
    character(len=ESMF_MAXSTR), parameter :: IAm='MAPL_FieldAllocCommit'
    real(kind=ESMF_KIND_R4), pointer      :: VAR_1D(:), VAR_2D(:,:), VAR_3D(:,:,:), VAR_4D(:,:,:,:)
    real(kind=ESMF_KIND_R8), pointer      :: VR8_1D(:), VR8_2D(:,:), VR8_3D(:,:,:), VR8_4D(:,:,:,:)
    type(ESMF_Grid)                       :: GRID
    integer                               :: COUNTS(ESMF_MAXDIM)
    integer                               :: SZUNGRD
    integer                               :: RANK
    integer                               :: gridRank
    integer                               :: I
    real                                  :: init_value
    integer, allocatable                  :: gridToFieldMap(:)
    integer, allocatable                  :: haloWidth(:)
    integer                               :: griddedDims
    integer                               :: lb1, lb2, lb3
    integer                               :: ub1, ub2, ub3
! SSI
    type(ESMF_Pin_Flag) :: pinflag
    type(ESMF_VM)       :: vm
    logical             :: ssiSharedMemoryEnabled
! SSI
    call ESMF_FieldGet(field, grid=GRID, _RC)
    call MAPL_GridGet(GRID, localCellCountPerDim=COUNTS, _RC)
    call ESMF_GridGet(GRID, dimCount=gridRank, _RC)
    _ASSERT(gridRank <= 3,' MAPL restriction - only 2 and 3d are supported')
    allocate(gridToFieldMap(gridRank), _STAT)
    gridToFieldMap = 0
    do I = 1, gridRank
       gridToFieldMap(I) = I
    end do
    ! ALT: the next allocation should have been griddedDims,
    !      but this compilcates the code unnecessery
    allocate(haloWidth(gridRank), _STAT)
    haloWidth = (/HW,HW,0/)
    if(present(default_value)) then
       init_value = default_value
    else
       init_value = 0.0
    end if
    szungrd = 0
    if (present(UNGRID)) then
       szungrd = size(UNGRID)
    end if
! SSI
    call ESMF_VMGetCurrent(vm, _RC)
    call ESMF_VMGet(vm, ssiSharedMemoryEnabledFlag=ssiSharedMemoryEnabled, _RC)
    ! call pinflag getter
    pinflag = MAPL_PinFlagGet()
    if (any(pinflag == [ESMF_PIN_DE_TO_SSI,ESMF_PIN_DE_TO_SSI_CONTIG])) then
       _ASSERT(ssiSharedMemoryEnabled, 'SSI shared memory is NOT supported')
    end if
! SSI
    Dimensionality: select case(DIMS)
       ! Horizontal and vertical
       ! -----------------------
    case(MAPL_DimsNone)
       rank = szungrd
       !ALT: This is special case - array does not map any gridded dims
       gridToFieldMap= 0
       if (typekind == ESMF_KIND_R4) then
          select case (rank)
          case (1)
             allocate(VAR_1D(UNGRID(1)), _STAT)
             VAR_1D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VAR_1D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  gridToFieldMap=gridToFieldMap,                      &
                  ungriddedLBound=[1],&
                  ungriddedUBound=[ungrid(1)], &
                  _RC)
          case default
             _FAIL( 'unsupported rank > 1')
          end select
       else
          select case (rank)
          case (1)
             allocate(VR8_1D(UNGRID(1)), _STAT)
             VR8_1D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VR8_1D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  gridToFieldMap=gridToFieldMap,                      &
                  ungriddedLBound=[1],&
                  ungriddedUBound=[ungrid(1)], &
                  _RC)
          case default
             _FAIL( 'unsupported rank > 1')
          end select
       endif
       ! Vertical only
       ! -------------
    case(MAPL_DimsVertOnly)
       !ALT: This is special case - array does not map any gridded dims
       gridToFieldMap = 0
       rank=1
       lb1 = 1
       ub1 = COUNTS(3)
       select case(LOCATION)
       case(MAPL_VLocationEdge  )
          lb1 = 0
       case(MAPL_VLocationCenter)
          lb1 = 1
       case default
          _RETURN(ESMF_FAILURE)
       end select
       if (typekind == ESMF_KIND_R4) then
          allocate(VAR_1D(lb1:ub1), _STAT)
          VAR_1D = INIT_VALUE
          call ESMF_FieldEmptyComplete(FIELD, farray=var_1d,  &
               indexflag=ESMF_INDEX_DELOCAL, &
               datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
               gridToFieldMap=gridToFieldMap,                           &
               ungriddedLBound=[lb1],&
               ungriddedUBound=[ub1], &
               _RC)
       else
          allocate(VR8_1D(lb1:ub1), _STAT)
          VR8_1D = INIT_VALUE
          call ESMF_FieldEmptyComplete(FIELD, farray=vr8_1d,  &
               indexflag=ESMF_INDEX_DELOCAL, &
               datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
               gridToFieldMap=gridToFieldMap,                           &
               ungriddedLBound=[lb1],&
               ungriddedUBound=[ub1], &
               _RC)
       end if
       ! Horizontal only
       ! ---------------
    case(MAPL_DimsHorzOnly)
       rank = 2 + szungrd
       _ASSERT(rank <= 4, 'unsupported rank > 4 (UNGRD not fully implemented)')
       if (gridRank == 3 .and. rank == 2) gridToFieldMap(3)=0
       griddedDims = gridRank - count(gridToFieldMap == 0)
       lb1 = 1-HW
       ub1 = COUNTS(1)+HW
       lb2 = 1-HW
       ub2 = COUNTS(2)+HW
       if (typekind == ESMF_KIND_R4) then
          RankCase2d: select case (rank)
          case (2)
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  pinflag=pinflag, _RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VAR_2D, _RC)
             VAR_2D = INIT_VALUE
          case (3)
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  ungriddedLBound=(/1/), ungriddedUBound=(/UNGRID(1)/),  &
                  pinflag=pinflag,_RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VAR_3D, _RC)
             VAR_3D = INIT_VALUE
          case (4)
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  ungriddedLBound=(/1,1/), ungriddedUBound=(/UNGRID(1),UNGRID(2)/), &
                pinflag=pinflag, _RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VAR_4D, _RC)
             VAR_4D = INIT_VALUE
          case default
             _FAIL('only up to 4D are supported')
          end select RankCase2d
       else
          select case (rank)
          case (2)
          call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R8, &
               gridToFieldMap=gridToFieldMap,                   &
               totalLWidth=haloWidth(1:griddedDims),            &
               totalUWidth=haloWidth(1:griddedDims),            &
                pinflag=pinflag, _RC)
          call ESMF_FieldGet(FIELD, farrayPtr=VR8_2D, _RC)
          VR8_2D = INIT_VALUE
          case (3)
          call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R8, &
               gridToFieldMap=gridToFieldMap,                   &
               totalLWidth=haloWidth(1:griddedDims),            &
               totalUWidth=haloWidth(1:griddedDims),            &
               ungriddedLBound=(/1/), ungriddedUBound=(/UNGRID(1)/),  &
               pinflag=pinflag, _RC)
          call ESMF_FieldGet(FIELD, farrayPtr=VR8_3D, _RC)
          VR8_3D = INIT_VALUE
          case (4)
          call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R8, &
               gridToFieldMap=gridToFieldMap,              &
               totalLWidth=haloWidth(1:griddedDims),     &
               totalUWidth=haloWidth(1:griddedDims),     &
               ungriddedLBound=(/1,1/), ungriddedUBound=(/UNGRID(1),UNGRID(2)/), &
               pinflag=pinflag, _RC)
          call ESMF_FieldGet(FIELD, farrayPtr=VR8_4D, _RC)
          VR8_4D = INIT_VALUE
          case default
             _FAIL('only up to 4D are supported')
          end select
       end if
       ! Horz + Vert
       ! -----------
    case(MAPL_DimsHorzVert)
       lb1 = 1-HW
       ub1 = COUNTS(1)+HW
       lb2 = 1-HW
       ub2 = COUNTS(2)+HW
       ub3 = COUNTS(3)
       griddedDims = gridRank - count(gridToFieldMap == 0)
       if (gridRank == 3) gridToFieldMap(3)=0
       rank = 3 + szungrd
       select case(LOCATION)
       case(MAPL_VLocationCenter)
          lb3 = 1
       case(MAPL_VLocationEdge  )
          lb3 = 0
       case default
          _RETURN(ESMF_FAILURE)
       end select
       RankCase3d: select case(rank)
       case (3)
          if (typekind == ESMF_KIND_R4) then
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  ungriddedLBound=(/lb3/), ungriddedUBound=(/ub3/),  &
                  pinflag=pinflag, _RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VAR_3D, _RC)
             VAR_3D = INIT_VALUE
          else
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R8, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  ungriddedLBound=(/lb3/), ungriddedUBound=(/ub3/),  &
                  pinflag=pinflag, _RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VR8_3D, _RC)
             VR8_3D = INIT_VALUE
          endif
       case (4)
          if (typekind == ESMF_KIND_R4) then
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  ungriddedLBound=(/lb3,1/), ungriddedUBound=(/ub3,ungrid(1)/),  &
                   pinflag=pinflag, _RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VAR_4D, _RC)
             VAR_4D = INIT_VALUE
          else
             call ESMF_FieldEmptyComplete(FIELD, typekind=ESMF_TYPEKIND_R8, &
                  gridToFieldMap=gridToFieldMap,              &
                  totalLWidth=haloWidth(1:griddedDims),     &
                  totalUWidth=haloWidth(1:griddedDims),     &
                  ungriddedLBound=(/lb3,1/), ungriddedUBound=(/ub3,ungrid(1)/),  &
                   pinflag=pinflag, _RC)
             call ESMF_FieldGet(FIELD, farrayPtr=VR8_4D, _RC)
             VR8_4D = INIT_VALUE
          endif
       case default
          _RETURN(ESMF_FAILURE)
       end select RankCase3d
       ! Tiles
       ! -----
    case(MAPL_DimsTileOnly)
       rank = 1 + szungrd
       _ASSERT(gridRank == 1, 'gridRank /= 1')
       if (typekind == ESMF_KIND_R4) then
          select case (rank)
          case (1)
             allocate(VAR_1D(COUNTS(1)), _STAT)
             VAR_1D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VAR_1D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,         &
                  _RC)
          case (2)
             allocate(VAR_2D(COUNTS(1),UNGRID(1)), _STAT)
             VAR_2D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VAR_2D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  gridToFieldMap=gridToFieldMap,                      &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  _RC)
          case (3)
             allocate(VAR_3D(COUNTS(1), UNGRID(1), UNGRID(2)), _STAT)
             VAR_3D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VAR_3D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  gridToFieldMap=gridToFieldMap,                      &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  _RC)
          case default
             _FAIL( 'only 2D and 3D are supported')
          end select
       else
          select case (rank)
          case (1)
             allocate(VR8_1D(COUNTS(1)), _STAT)
             VR8_1D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VR8_1D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,         &
                  _RC)
          case (2)
             allocate(VR8_2D(COUNTS(1),UNGRID(1)), _STAT)
             VR8_2D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VR8_2D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  gridToFieldMap=gridToFieldMap,                      &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  _RC)
          case (3)
             allocate(VR8_3D(COUNTS(1), UNGRID(1), UNGRID(2)), _STAT)
             VR8_3D = INIT_VALUE
             call ESMF_FieldEmptyComplete(FIELD, farray=VR8_3D,    &
                  indexflag=ESMF_INDEX_DELOCAL, &
                  gridToFieldMap=gridToFieldMap,                      &
                  datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                  _RC)
          case default
             _FAIL( 'only 2D and 3D are supported')
          end select
       endif
    case(MAPL_DimsTileTile)
       rank=2
       _ASSERT(gridRank == 1, 'gridRank /= 1')
       if (typekind == ESMF_KIND_R4) then
          allocate(VAR_2D(COUNTS(1), COUNTS(2)), _STAT)
          VAR_2D = INIT_VALUE
          call ESMF_FieldEmptyComplete(FIELD, farray=VAR_2D,    &
               indexflag=ESMF_INDEX_DELOCAL, &
               datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                                !                  ungriddedLBound = (/1/),                      &
                                !                  ungriddedUBound = (/counts(2)/),              &
               _RC)
       else
          allocate(VR8_2D(COUNTS(1), COUNTS(2)), _STAT)
          VR8_2D = INIT_VALUE
          call ESMF_FieldEmptyComplete(FIELD, farray=VR8_2D,    &
               indexflag=ESMF_INDEX_DELOCAL, &
               datacopyFlag = ESMF_DATACOPY_REFERENCE,             &
                                !                  ungriddedLBound = (/1/),                      &
                                !                  ungriddedUBound = (/counts(2)/),              &
               _RC)
       endif
       ! Invalid dimensionality
       ! ----------------------
    case default
       _RETURN(ESMF_FAILURE)
    end select Dimensionality
    if (present(default_value)) then
       call MAPL_AttributeSet(field, NAME="MAPL_InitStatus", &
            VALUE=MAPL_InitialDefault, _RC)
    end if
    ! Clean up
    deallocate(haloWidth)
    deallocate(gridToFieldMap)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldAllocCommit
Call graph
mapl_fieldalloccommit calls ESMF_GridGet, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldemptycomplete, esmf_fieldget, mapl_assert, mapl_attributeset, mapl_gridget, mapl_pinflagget, mapl_return, mapl_verify, mapl_fieldalloccommit
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_attributeset calls mapl_bundleattseti4, mapl_fieldattseti4, mapl_stateattseti4
mapl_gridget calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_DistGridGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_bundleattseti4 calls mapl_bundleattseti4
mapl_fieldattseti4 calls mapl_fieldattseti4
mapl_stateattseti4 calls mapl_stateattseti4
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_distgridget calls mapl_verify, ESMF_DistGridGet
mapl_getimsjms calls mapl_assert, mapl_return, mapl_verify, mapl_sort
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DistGridGet, ESMF_DELayoutGet
mapl_throw_exception calls initialize
initialize_ calls mapl_fieldalloccommit, mapl_genericinitialize
mapl_allocatecoupling calls mapl_fieldalloccommit, mapl_allocatecoupling
mapl_statecreatefromspecnew calls mapl_fieldalloccommit, mapl_allocatecoupling
mapl_genericinitialize calls mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew
esmfl_stategetfield calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_1 calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls mapl_allocatecoupling
forceallocation calls mapl_allocatecoupling
initialize calls mapl_allocatecoupling, mapl_genericinitialize, mapl_statecreatefromspec
mapl_bundlereadncpar calls mapl_allocatecoupling
mapl_readforcingx calls mapl_statecreatefromvarspecnew
realize_fields calls mapl_allocatecoupling