MAPL_CommsAllReduceSum_R4_2 – MAPL
MAPL_CommsAllReduceSum_R4_2 Subroutine
16 statements
Source File
private subroutine MAPL_CommsAllReduceSum_R4_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R4), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R4), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commsallreducesum_r4_2 calls esmf_vmget, mapl_verify, mpi_allreduce, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_commsallreducesum calls mapl_commsallreducesum_r4_2
mapl_areamean_2d_r8 calls mapl_commsallreducesum
mapl_areamean calls mapl_areamean_2d_r8
mapl_areamean_2d_r8_bitrep calls mapl_areamean