MAPL_Finalize – MAPL
MAPL_Finalize Subroutine
19 statements
Source File
public subroutine MAPL_Finalize(unusable, comm, rc)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_Finalize(unusable,comm,rc)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      integer, optional, intent(out) :: rc
      integer :: comm_world,status
      _UNUSED_DUMMY(unusable)
      if (present(comm)) then
         comm_world = comm
      else
         comm_world=MPI_COMM_WORLD
      end if
      call stop_global_time_profiler(rc=status)
      _VERIFY(status)
      call report_global_profiler(comm=comm_world)
      call finalize_profiler()
      call finalize_pflogger()
      _RETURN(_SUCCESS)
   end subroutine MAPL_Finalize
Call graph
mapl_finalize calls finalize_profiler, finalize_pflogger, mapl_return, mapl_verify, report_global_profiler, stop_global_time_profiler
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
report_global_profiler calls mapl_return, mapl_verify, mpi_barrier, mpi_comm_rank, mpi_comm_size, generate_report, get_logger, add_column, get_global_time_profiler, info
stop_global_time_profiler calls mapl_return, mapl_verify, get_global_time_profiler
add_column calls get_num_rows_header, get_num_rows_separator, get_width, set_width, v_push_back
get_error_message calls at, insert
mapl_throw_exception calls initialize
generate_report_profiler calls get_width, get_header, get_root_node, get_rows
v_push_back calls resize, v_grow_to
finalize_mpi calls mapl_finalize
main calls mapl_finalize
run calls mapl_finalize, finalize_mpi
time_ave calls mapl_finalize
ut_regridding calls mapl_finalize
comp_testing_driver calls main
extdata_driver calls run
regrid_util calls main
capdriver_main calls run