MAPL_VarSpecSetFieldPtr – MAPL
MAPL_VarSpecSetFieldPtr Subroutine
12 statements
Source File
private subroutine MAPL_VarSpecSetFieldPtr(SPEC, FIELDPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC
type(ESMF_Field), pointer :: FIELDPTR
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_VarSpecSetFieldPtr(SPEC, FIELDPTR, RC )
      type (MAPL_VarSpec ),             intent(INOUT)   :: SPEC
      type(ESMF_Field)   ,              pointer         :: FIELDPTR
      integer            , optional   , intent(  OUT)   :: RC
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      SPEC%SPECPtr%FIELD => FIELDPTR
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecSetFieldPtr
Call graph
mapl_varspecsetfieldptr calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecset calls mapl_varspecsetfieldptr