MAPL_AllocNodeArray_1DR4 – MAPL
MAPL_AllocNodeArray_1DR4 Module Procedure
16 statements
Source File
module procedure MAPL_AllocNodeArray_1DR4 module subroutine MAPL_AllocNodeArray_1DR4(Ptr, Shp, lbd, rc) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(inout), pointer :: Ptr(:)
integer, intent(in) :: Shp(1)
integer, intent(in), optional :: lbd(1)
integer, intent(out), optional :: rc
Calls
Call graph
mapl_allocnodearray_1dr4 calls getsharedmemory, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize