MAPL_GenericStateGet – MAPL
MAPL_GenericStateGet Subroutine
222 statements
Source File
private subroutine MAPL_GenericStateGet(STATE, IM, JM, LM, VERTDIM, NX, NY, NX0, NY0, LAYOUT, GCNames, LONS, LATS, grid, ORBIT, RUNALARM, IMPORTspec, EXPORTspec, INTERNALspec, INTERNAL_ESMF_STATE, TILETYPES, TILEKIND, TILELATS, TILELONS, TILEAREA, LOCSTREAM, EXCHANGEGRID, CLOCK, NumInitPhases, NumRunPhases, GCS, CCS, GIM, GEX, CF, HEARTBEAT, childrens_names, childrens_gridcomps, childrens_import_states, childrens_export_states, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout), target :: STATE
integer, intent(out), optional :: IM
integer, intent(out), optional :: JM
integer, intent(out), optional :: LM
integer, intent(out), optional :: VERTDIM
integer, intent(out), optional :: NX
integer, intent(out), optional :: NY
integer, intent(out), optional :: NX0
integer, intent(out), optional :: NY0
type(ESMF_DELayout), intent(out), optional :: LAYOUT
character(len=ESMF_MAXSTR), optional, pointer :: GCNames(:)
real, optional, pointer :: LONS(:,:)
real, optional, pointer :: LATS(:,:)
type(ESMF_Grid), optional :: grid
type(MAPL_SunOrbit), intent(out), optional :: ORBIT
type(ESMF_Alarm), intent(out), optional :: RUNALARM
type(MAPL_VarSpec), optional, pointer :: IMPORTspec(:)
type(MAPL_VarSpec), optional, pointer :: EXPORTspec(:)
type(MAPL_VarSpec), optional, pointer :: INTERNALspec(:)
type(ESMF_State), intent(out), optional :: INTERNAL_ESMF_STATE
integer, optional, pointer :: TILETYPES(:)
integer, optional, pointer :: TILEKIND(:)
real, optional, pointer :: TILELATS(:)
real, optional, pointer :: TILELONS(:)
real, optional, pointer :: TILEAREA(:)
type(MAPL_LocStream), intent(out), optional :: LOCSTREAM
type(MAPL_LocStream), intent(out), optional :: EXCHANGEGRID
type(ESMF_Clock), intent(out), optional :: CLOCK
integer, intent(out), optional :: NumInitPhases
integer, intent(out), optional :: NumRunPhases
type(ESMF_GridComp), optional, pointer :: GCS(:)
type(ESMF_CplComp), optional, pointer :: CCS(:,:)
type(ESMF_State), optional, pointer :: GIM(:)
type(ESMF_State), optional, pointer :: GEX(:)
type(ESMF_Config), intent(out), optional :: CF
real, intent(out), optional :: HEARTBEAT
character(len=ESMF_MAXSTR), optional, allocatable :: childrens_names(:)
type(ESMF_GridComp), optional, allocatable :: childrens_gridcomps(:)
type(ESMF_State), optional, allocatable :: childrens_import_states(:)
type(ESMF_State), optional, allocatable :: childrens_export_states(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GenericStateGet
Source Code
   subroutine MAPL_GenericStateGet (STATE, IM, JM, LM, VERTDIM,                &
        NX, NY, NX0, NY0, LAYOUT,                  &
        GCNames,                                   &
        LONS, LATS, grid, ORBIT, RUNALARM,               &
        IMPORTspec, EXPORTspec, INTERNALspec,      &
        INTERNAL_ESMF_STATE,                       &
        TILETYPES, TILEKIND,                       &
        TILELATS,TILELONS,TILEAREA,LOCSTREAM,      &
        EXCHANGEGRID,                              &
        CLOCK,                                     &
        NumInitPhases,                             &
        NumRunPhases,                              &
        GCS, CCS, GIM, GEX, CF, HEARTBEAT,         &
        childrens_names, childrens_gridcomps,      &
        childrens_import_states, childrens_export_states, &
        RC )
      !ARGUMENTS:
      type (MAPL_MetaComp), target,   intent(INOUT) :: STATE
      type (ESMF_Alarm),    optional, intent(  OUT) :: RUNALARM
      type (MAPL_SunOrbit), optional, intent(  OUT) :: ORBIT
      integer,              optional, intent(  OUT) :: IM, JM, LM
      integer,              optional, intent(  OUT) :: VERTDIM
      integer,              optional, intent(  OUT) :: NX, NY, NX0, NY0
      type (ESMF_DELayout), optional, intent(  OUT) :: LAYOUT
      real, pointer,        optional                :: LONS(:,:)
      real, pointer,        optional                :: LATS(:,:)
      type(ESMF_Grid),      optional                :: grid
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      type (MAPL_VarSpec),  optional, pointer       :: IMPORTspec(:)
      type (MAPL_VarSpec),  optional, pointer       :: EXPORTspec(:)
      type (MAPL_VarSpec),  optional, pointer       :: INTERNALspec(:)
      type (ESMF_State),    optional, intent(  OUT) :: INTERNAL_ESMF_STATE
      integer,              optional, pointer       :: TILETYPES(:)
      integer,              optional, pointer       :: TILEKIND(:)
      real, pointer,        optional                :: TILELONS(:)
      real, pointer,        optional                :: TILELATS(:)
      real, pointer,        optional                :: TILEAREA(:)
      type (MAPL_LocStream),optional, intent(  OUT) :: LOCSTREAM
      type (MAPL_LocStream),optional, intent(  OUT) :: EXCHANGEGRID
      type (ESMF_CLOCK)    ,optional, intent(  OUT) :: CLOCK
      type (ESMF_CplComp),  optional, pointer       :: CCS(:,:)
      ! Next four are deprecated (now have memory leak)
      character(len=ESMF_MAXSTR), optional, pointer :: GCNames(:)
      type (ESMF_GridComp),       optional, pointer :: GCS(:)
      type (ESMF_State),          optional, pointer :: GIM(:)
      type (ESMF_State),          optional, pointer :: GEX(:)
      character(len=ESMF_MAXSTR), optional, allocatable :: childrens_names(:)
      type (ESMF_GridComp),       optional, allocatable :: childrens_gridcomps(:)
      type (ESMF_State),          optional, allocatable :: childrens_import_states(:)
      type (ESMF_State),          optional, allocatable :: childrens_export_states(:)
      real                 ,optional, intent(  OUT) :: HEARTBEAT
      integer,              optional, intent(  OUT) :: NumInitPhases
      integer,              optional, intent(  OUT) :: NumRunPhases
      type (ESMF_Config),   optional, intent(  OUT) :: CF
      ! !DESCRIPTION:
      ! This is the way of querying the opaque {\em MAPL\_Generic}
      ! state object. The arguments are:
      !  \begin{description}
      !   \item[STATE]
      !    The MAPL object to be queried.
      !   \item[IM]
      !      Size of the first horizontal dimension (X) of local arrays.
      !   \item[JM]
      !      Size of the second horizontal dimension (Y) of local arrays.
      !   \item[LM]
      !      Size of the vertical dimension.
      !   \item[VERTDIM]
      !      Position of the vertical dimension of 2 or higher dimensional arrays.
      !   \item[NX]
      !      Size of the DE array dimension aligned with the first horizontal dimension of arrays
      !   \item[NY]
      !      Size of the DE array dimension aligned with the second horizontal dimension of arrays
      !   \item[NX0, NY0]
      !      Coordinates of current DE.
      !   \item[LONS]
      !      X coordinates of array locations. Currently longitude in radians.
      !   \item[LATS]
      !      Y coordinates of array locations. Currently latitude in radians.
      !   \item[INTERNAL\_ESMF\_STATE]
      !      The gridded component's INTERNAL state.
      !   \item[GCNames]
      !      Names of the children.
      !   \item[GCS]
      !      The child gridded components.
      !   \item[GIM]
      !      The childrens' IMPORT states.
      !   \item[GEX]
      !      The childrens' EXPORT states.
      !   \item[CCS]
      !      Array of child-to-child couplers.
      !   \end{description}
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm = "MAPL_GenericStateGet"
      integer                               :: status
      logical                               :: FIX_SUN
      character(len=ESMF_MAXSTR)            :: gname
      type(MaplGrid), pointer :: temp_grid
      if(present(IM)) then
         IM=STATE%GRID%IM
      endif
      if(present(JM)) then
         temp_grid => state%get_grid()
         JM=temp_GRID%JM
      endif
      if(present(LM)) then
         LM=STATE%GRID%LM
      endif
      if(present(VERTDIM)) then
         VERTDIM=STATE%GRID%VERTDIM
      endif
      if(present(NX)) then
         NX=STATE%GRID%NX
      endif
      if(present(NY)) then
         NY=STATE%GRID%NY
      endif
      if(present(NX0)) then
         NX0=STATE%GRID%NX0
      endif
      if(present(NY0)) then
         NY0=STATE%GRID%NY0
      endif
      if(present(LAYOUT)) then
         LAYOUT=STATE%GRID%LAYOUT
      endif
      if(present(CF)) then
         CF=STATE%CF
      endif
      if(present(ORBIT)) then
         if(.not.MAPL_SunOrbitCreated(STATE%ORBIT)) then
            call ESMF_GridGet(STATE%GRID%ESMFGRID,name=gname,_RC)
            FIX_SUN = (index(gname,"DP")>0)
            ! create the orbit object
            STATE%ORBIT = MAPL_SunOrbitCreateFromConfig (STATE%CF, STATE%CLOCK, FIX_SUN, _RC)
         end if
         ORBIT=STATE%ORBIT
      end if
      if(present(RUNALARM)) then
         RUNALARM=STATE%ALARM(0)
      endif
      if(present(LONS    )) then
         temp_grid => STATE%get_grid()
         LONS   => temp_grid%LONS
      endif
      if(present(LATS    )) then
         temp_grid => STATE%get_grid()
         LATS   => temp_grid%LATS
      endif
      if(present(grid)) then
         temp_grid => STATE%get_grid()
         grid = temp_grid%ESMFGrid
      endif
      if(present(IMPORTspec)) then
         IMPORTspec =>STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS
      endif
      if(present(EXPORTspec)) then
         EXPORTspec =>STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS
      endif
      if(present(INTERNALspec)) then
         INTERNALspec =>STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS
      endif
      if(present(INTERNAL_ESMF_STATE)) then
         INTERNAL_ESMF_STATE = STATE%get_internal_state()
      endif
      if(present(TILETYPES)) then
         call MAPL_LocStreamGet(STATE%LocStream, TILETYPE=TILETYPES, RC=status)
         _VERIFY(status)
      end if
      if(present(TILEKIND)) then
         call MAPL_LocStreamGet(STATE%LocStream, TILEKIND=TILEKIND, RC=status)
         _VERIFY(status)
      end if
      if(present(TILELONS)) then
         call MAPL_LocStreamGet(STATE%LocStream, TILELONS=TILELONS, RC=status)
         _VERIFY(status)
      end if
      if(present(TILELATS)) then
         call MAPL_LocStreamGet(STATE%LocStream, TILELATS=TILELATS, RC=status)
         _VERIFY(status)
      end if
      if(present(TILEAREA)) then
         call MAPL_LocStreamGet(STATE%LocStream, TILEAREA=TILEAREA, RC=status)
         _VERIFY(status)
      end if
      if(present(LOCSTREAM)) then
         LOCSTREAM = STATE%LOCSTREAM
      endif
      if(present(EXCHANGEGRID)) then
         EXCHANGEGRID = STATE%EXCHANGEGRID
      endif
      if(present(CLOCK)) then
         CLOCK = STATE%CLOCK
      endif
      if(present(CCS)) then
         CCS => STATE%CCS
      endif
      if(present(GCNames )) then
         if (.not. allocated(STATE%GCNamelist)) allocate(STATE%GCNamelist(0))
         GCNames => STATE%GCNameList
      endif
      if(present(childrens_names )) then
         if (.not. allocated(STATE%GCNamelist)) allocate(STATE%GCNamelist(0))
         childrens_names = STATE%GCNameList
      endif
      if(present(GCS)) then
         block
           integer i, nc
           nc = STATE%get_num_children()
           allocate(GCS(nc))
           do i = 1, nc
              GCS(i) = STATE%get_child_gridcomp(i)
           end do
         end block
      endif
      if(present(childrens_gridcomps)) then
         block
           integer i, nc
           nc = STATE%get_num_children()
           allocate(childrens_gridcomps(nc))
           do i = 1, nc
              childrens_gridcomps(i) = STATE%get_child_gridcomp(i)
           end do
         end block
      endif
      if(present(GIM)) then
         block
           integer i, nc
           nc = STATE%get_num_children()
           allocate(GIM(nc))
           do i = 1, nc
              GIM(i) = state%get_child_import_state(i)
           end do
         end block
      endif
      if(present(childrens_import_states)) then
         block
           integer i, nc
           nc = STATE%get_num_children()
           allocate(childrens_import_states(nc))
           do i = 1, nc
              childrens_import_states(i) = state%get_child_import_state(i)
           end do
         end block
      endif
      if(present(GEX)) then
         block
           integer i, nc
           nc = STATE%get_num_children()
           allocate(GEX(nc))
           do i = 1, nc
              GEX(i) = state%get_child_export_state(i)
           end do
         end block
      endif
      if(present(childrens_export_states)) then
         block
           integer i, nc
           nc = STATE%get_num_children()
           allocate(childrens_export_states(nc))
           do i = 1, nc
              childrens_export_states(i) = state%get_child_export_state(i)
           end do
         end block
      endif
      if(present(HEARTBEAT)) then
         HEARTBEAT = STATE%HEARTBEAT
      endif
      if(present(NumInitPhases)) then
         NumInitPhases = SIZE(STATE%PHASE_INIT)
      endif
      if(present(NumRunPhases)) then
         NumRunPhases = SIZE(STATE%PHASE_RUN)
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericStateGet
Call graph
mapl_genericstateget calls mapl_sunorbitcreated, mapl_verify, esmf_gridget, mapl_locstreamget, mapl_sunorbitcreatefromconfig, mapl_return
mapl_sunorbitcreated calls mapl_return
mapl_verify calls mapl_throw_exception
mapl_locstreamget calls mapl_return, mapl_assert
mapl_sunorbitcreatefromconfig calls mapl_verify, mapl_return, mapl_sunorbitcreate, esmf_configgetattribute
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_sunorbitcreate calls mapl_verify, mapl_return, calcmafromea, esmf_timeset, calceafromta, esmf_timeintervalget, esmf_timeintervalset, rect_pmpi
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_readforcingx calls mapl_genericstateget
mapl_get calls mapl_genericstateget
mapl_readforcing1 calls mapl_readforcingx
run_ calls mapl_get
mapl_internalesmfstateget calls mapl_get, mapl_internalesmfstateget
mapl_readforcing2 calls mapl_readforcingx
initialize_gc calls mapl_get
initialize_ calls mapl_get
mapl_donotallocateimport calls mapl_get
mapl_donotallocateinternal calls mapl_get
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
get_field_from_internal calls mapl_internalesmfstateget