MAPL_StateGetSpecAttrib – MAPL
MAPL_StateGetSpecAttrib Subroutine
36 statements
Source File
private subroutine MAPL_StateGetSpecAttrib(STATE, NAME, INTERNAL, IMPORT, EXPORT, FORCING, REFRESH_INTERVAL, AVERAGING_INTERVAL, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(in) :: STATE
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: INTERNAL
logical, intent(in), optional :: IMPORT
logical, intent(in), optional :: EXPORT
logical, intent(in), optional :: FORCING
integer, intent(out), optional :: REFRESH_INTERVAL
integer, intent(out), optional :: AVERAGING_INTERVAL
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateGetSpecAttrib
Source Code
   subroutine MAPL_StateGetSpecAttrib(STATE, NAME,    &
        INTERNAL, IMPORT, EXPORT, FORCING,            &
        REFRESH_INTERVAL, AVERAGING_INTERVAL, RC      )
      type (MAPL_MetaComp)            , intent(IN)      :: STATE
      character (len=*)               , intent(IN )     :: NAME
      integer            , optional   , intent(OUT)     :: REFRESH_INTERVAL
      integer            , optional   , intent(OUT)     :: AVERAGING_INTERVAL
      logical            , optional   , intent(IN )     :: INTERNAL, EXPORT, IMPORT, FORCING
      integer            , optional   , intent(OUT)     :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateGetSpecAttrib"
      integer                               :: status
      type (MAPL_VarSpec ), pointer         :: SPEC=>null()
      if(present(INTERNAL))then
         if(INTERNAL) then
            SPEC=>STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS(MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%INTERNAL%OLD_VAR_SPECS,NAME))
         endif
      endif
      if(present(IMPORT))then
         if(IMPORT) then
            SPEC=>STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS(MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%IMPORT%OLD_VAR_SPECS,NAME))
         endif
      endif
      if(present(EXPORT))then
         if(EXPORT) then
            SPEC=>STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS(MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%EXPORT%OLD_VAR_SPECS,NAME))
         endif
      endif
      if(present(FORCING))then
         if(FORCING) then
            SPEC=>STATE%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS(MAPL_VarSpecGetIndex(STATE%COMPONENT_SPEC%FORCING%OLD_VAR_SPECS,NAME))
         endif
      endif
      _ASSERT(associated(SPEC),'needs informative message')
      call MAPL_VarSpecGet(SPEC,            &
           ACCMLT_INTERVAL=AVERAGING_INTERVAL, &
           COUPLE_INTERVAL=REFRESH_INTERVAL,   &
           RC=status  )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateGetSpecAttrib
Call graph
mapl_stategetspecattrib calls mapl_varspecgetindex, mapl_assert, mapl_verify, mapl_varspecget, mapl_return
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_verify calls mapl_throw_exception
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetstateptr, mapl_varspecgetfieldptr, mapl_varspecgetbundleptr, mapl_varspecgetnew
mapl_return calls mapl_throw_exception, get_error_message
mapl_varspecgetindexbyname calls mapl_return
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_varspecgetindexofitem calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_stategettimestamp calls mapl_stategetspecattrib
mapl_readforcingx calls mapl_stategetspecattrib, mapl_stategettimestamp
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2