MAPL_Am_I_Root_Vm – MAPL
MAPL_Am_I_Root_Vm Function
9 statements
Source File
private function MAPL_Am_I_Root_Vm(VM) result(R)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), optional :: VM
Return Value logical
Calls
Called by
Contents
Source Code
MAPL_Am_I_Root_Vm
Source Code
  function MAPL_Am_I_Root_Vm(VM) result(R)
    type (ESMF_VM), optional :: VM
    logical                  :: R
    if (present(VM)) then
       R = MAPL_Am_I_Rank(VM)
    else
       R = MAPL_Am_I_Rank()
    end if
  end function MAPL_Am_I_Root_Vm
Call graph
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout
mapl_am_i_rank_only calls mapl_am_i_rank, esmf_vmgetcurrent
mapl_am_i_rank_vm calls esmf_vmget
mapl_am_i_rank_layout calls mapl_am_i_rank, esmf_delayoutget
mapl_am_i_root calls mapl_am_i_root_vm