MAPL_FieldCopy – MAPL
MAPL_FieldCopy Module Subroutine
54 statements
Source File
module subroutine MAPL_FieldCopy(FROM, TO, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FROM
type(ESMF_Field), intent(inout) :: TO
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_FieldCopy
Source Code
  module subroutine MAPL_FieldCopy(from, to, RC)
    type (ESMF_Field), intent(INOUT) :: FROM !ALT: IN
    type (ESMF_Field), intent(INOUT) :: TO !ALT: OUT
    integer, optional, intent(  OUT) :: RC
    !   we are creating new field so that we can change the name of the field;
    !   the important thing is that the data (ESMF_Array) and the grid (ESMF_Grid)
    !   are the SAME as the one in the original Field, if DoCopy flag is present
    !   and set to true we create a new array and copy the data, not just reference it
    integer                 :: fieldRank
    integer                 :: status
    character(len=ESMF_MAXSTR), parameter :: Iam='MAPL_FieldCopy'
    real, pointer           :: var_1d(:)
    real, pointer           :: var_2d(:,:)
    real, pointer           :: var_3d(:,:,:)
    real(kind=REAL64), pointer :: vr8_1d(:)
    real(kind=REAL64), pointer :: vr8_2d(:,:)
    real(kind=REAL64), pointer :: vr8_3d(:,:,:)
    type(ESMF_TypeKind_Flag)  :: tk
    call ESMF_FieldGet(from, dimCount=fieldRank, &
         typekind=tk, RC=STATUS)
    _VERIFY(STATUS)
    _ASSERT(tk == ESMF_TypeKind_R8, 'inconsistent typekind (should be ESMF_TypeKind_R8)')
    select case (fieldRank)
    case (1)
       call ESMF_FieldGet(from, farrayPtr=vr8_1d, rc=status)
       _VERIFY(STATUS)
       call ESMF_FieldGet(to, dimCount=fieldRank, typekind=tk, RC=STATUS)
       _VERIFY(STATUS)
       _ASSERT(tk == ESMF_TypeKind_R4, 'inconsistent typekind (should be ESMF_TypeKind_R4)')
       _ASSERT(fieldRank==1, 'inconsistent fieldrank (should be 1)')
       call ESMF_FieldGet(to, farrayPtr=var_1d, rc=status)
       _VERIFY(STATUS)
       var_1d = vr8_1d
    case (2)
       call ESMF_FieldGet(from, farrayPtr=vr8_2d, rc=status)
       _VERIFY(STATUS)
       call ESMF_FieldGet(to, dimCount=fieldRank, typekind=tk, RC=STATUS)
       _VERIFY(STATUS)
       _ASSERT(tk == ESMF_TypeKind_R4, 'inconsistent typekind (should be ESMF_TypeKind_R4)')
       _ASSERT(fieldRank==2, 'inconsistent fieldRank (should be 2)')
       call ESMF_FieldGet(to, farrayPtr=var_2d, rc=status)
       _VERIFY(STATUS)
       var_2d = vr8_2d
    case (3)
       call ESMF_FieldGet(from, farrayPtr=vr8_3d, rc=status)
       _VERIFY(STATUS)
       call ESMF_FieldGet(to, dimCount=fieldRank, typekind=tk, RC=STATUS)
       _VERIFY(STATUS)
       _ASSERT(tk == ESMF_TypeKind_R4, 'inconsistent typekind (should be ESMF_TypeKind_R4)')
       _ASSERT(fieldRank==3,'inconsistent fieldRank (should be 3)')
       call ESMF_FieldGet(to, farrayPtr=var_3d, rc=status)
       _VERIFY(STATUS)
       var_3d = vr8_3d
    case default
       _FAIL( 'unsupported fieldRank (> 3)')
    end select
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldCopy
Call graph
mapl_fieldcopy calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, mapl_fieldcopy
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run calls mapl_fieldcopy