MAPL_TerminateImportAll – MAPL
MAPL_TerminateImportAll Subroutine
18 statements
Source File
private subroutine MAPL_TerminateImportAll(GC, ALL, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
logical, intent(in) :: ALL
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_TerminateImportAll
Source Code
   subroutine MAPL_TerminateImportAll ( GC, ALL, RC )
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      logical,                        intent(IN   ) :: ALL
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_TerminateImportAll"
      integer                               :: status
      type(MAPL_MetaComp), pointer          :: META
      integer                               :: I
      _UNUSED_DUMMY(ALL)
      call MAPL_GetObjectFromGC(GC, META, RC=status)
      _VERIFY(status)
      do I=1, META%get_num_children()
         call MAPL_TerminateImport ( GC, CHILD=I, RC=status )
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_TerminateImportAll
Call graph
mapl_terminateimportall calls get_num_children, mapl_getobjectfromgc, mapl_terminateimport, mapl_return, mapl_verify
mapl_getobjectfromgc calls mapl_internalstateget
mapl_terminateimport calls mapl_terminateimportall, mapl_donotconnect, mapl_donotconnectanyimport, mapl_donotconnectmany, mapl_terminateimportallbut
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_donotconnect calls mapl_return, mapl_verify, mapl_connectivityget
mapl_donotconnectanyimport calls mapl_return, mapl_verify, mapl_donotconnect
mapl_donotconnectmany calls mapl_return, mapl_verify, mapl_donotconnect
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_terminateimportallbut calls get_num_children, mapl_getobjectfromgc, mapl_return, mapl_verify, mapl_donotconnect, mapl_assert, mapl_varspecget, get_child_gridcomp, mapl_connectivityget, varisconnected
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
get_child_gridcomp calls get_gridcomp, get_ith_child
mapl_connectivityget calls mapl_getobjectfromgc, mapl_return, mapl_verify