MAPL_AllocNodeArray_3DR8 – MAPL
MAPL_AllocNodeArray_3DR8 Module Procedure
16 statements
Source File
module procedure MAPL_AllocNodeArray_3DR8 module subroutine MAPL_AllocNodeArray_3DR8(Ptr, Shp, lbd, rc) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), pointer :: Ptr(:,:,:)
integer, intent(in) :: Shp(3)
integer, intent(in), optional :: lbd(3)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_allocnodearray_3dr8 calls mapl_return, getsharedmemory, mapl_verify, mapl_assert, mapl_allocnodearray_3dr8
mapl_return calls get_error_message, mapl_throw_exception
getsharedmemory calls getsharedmemory, mapl_return, mapl_assert, mpi_barrier, shmget, segs, segsnew, shmat
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_allocnodearray calls mapl_allocnodearray_3dr8
mapl_cfioreadbundle calls mapl_allocnodearray
mapl_cfiowritebundlepost calls mapl_allocnodearray
mapl_allocateshared_1dl4 calls mapl_allocnodearray
mapl_allocateshared_1di4 calls mapl_allocnodearray
mapl_tilemaskget calls mapl_allocnodearray
mapl_allocateshared_1dr4 calls mapl_allocnodearray
mapl_allocateshared_1dr8 calls mapl_allocnodearray
mapl_allocateshared_2dr4 calls mapl_allocnodearray
mapl_allocateshared_2dr8 calls mapl_allocnodearray
mapl_varread_r4_1d calls mapl_allocnodearray
mapl_varread_r4_2d calls mapl_allocnodearray
initialize_subclass calls mapl_allocnodearray