MAPL_LocStreamFracArea – MAPL
MAPL_LocStreamFracArea Subroutine
19 statements
Source File
public subroutine MAPL_LocStreamFracArea(LocStream, TYPE, AREA, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
integer, intent(in) :: TYPE
real, intent(out) :: AREA(:,:)
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_LocStreamFracArea
Source Code
subroutine MAPL_LocStreamFracArea (LocStream, TYPE, AREA, RC)
  type(MAPL_LocStream),      intent(IN ) :: LocStream
  integer,                   intent(IN ) :: TYPE
  real,                      intent(OUT) :: AREA(:,:)
  integer, optional,         intent(OUT) :: RC
! Local variables
  integer                    :: II, JJ, N
! Make sure Location stream has been created...
!----------------------------------------------
  _ASSERT(associated(LocStream%Ptr),'needs informative message')
! and a grid attached...
!-----------------------
  _ASSERT(LocStream%Ptr%Current_Tiling > 0,'needs informative message')
! Compute area over masked locations
!-----------------------------------------------
  AREA   = 0.0
  do N = 1, size(LOCSTREAM%Ptr%LOCAL_INDEXLOCATION)
     if(LOCSTREAM%Ptr%LOCAL_GEOLOCATION(N)%T == TYPE) then
        II = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%I
        JJ = LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%J
        AREA  (II,JJ) = AREA  (II,JJ) + LOCSTREAM%Ptr%LOCAL_INDEXLOCATION(N)%W
     end if
  end do
  _RETURN(ESMF_SUCCESS)
end subroutine MAPL_LocStreamFracArea
Call graph
mapl_locstreamfracarea calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize