MAPL_VarSpecAddRefFromList – MAPL
MAPL_VarSpecAddRefFromList Subroutine
15 statements
Source File
private subroutine MAPL_VarSpecAddRefFromList(SPEC, ITEM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_VarSpecAddRefFromList(SPEC,ITEM,RC)
      type (MAPL_VarSpec ), pointer         :: SPEC(:)
      type (MAPL_VarSpec ), intent(IN )     :: ITEM(:)
      integer, optional   , intent(OUT)     :: RC
      integer                               :: STATUS
      integer I
      do I=1,size(ITEM)
         call MAPL_VarSpecAddRefFromItem(SPEC,ITEM(I),RC=STATUS)
         IF (STATUS /= MAPL_DuplicateEntry) then
            _VERIFY(STATUS)
         END IF
      enddo
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecAddRefFromList
Call graph
mapl_varspecaddreffromlist calls mapl_return, mapl_varspecaddreffromitem, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspecaddreffromitem calls mapl_return, mapl_verify, mapl_varspecgetindex, mapl_varspecprint, get_logger, error
mapl_verify calls mapl_throw_exception
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecprintmany calls mapl_return, mapl_verify, mapl_varspecprint
mapl_varspecprintone calls mapl_return, info
mapl_varspecaddreftolist calls mapl_varspecaddreffromlist
mapl_genericspecenum calls mapl_varspecaddreftolist, mapl_genericspecenum
mapl_setvarspecforcc calls mapl_varspecaddreftolist
mapl_stateaddexportspecfrmall calls mapl_varspecaddreftolist
mapl_stateaddimportspecfrmchld calls mapl_varspecaddreftolist
mapl_stateaddinternalspec calls mapl_varspecaddreftolist
mapl_wirecomponent calls mapl_varspecaddreftolist
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addimportspec calls mapl_stateaddimportspecfrmchld
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_genericsetservices calls mapl_genericspecenum, mapl_wirecomponent
addnewspec calls mapl_addexportspec, mapl_addimportspec
setservices calls mapl_genericsetservices, mapl_addexportspec, mapl_addinternalspec