MAPL_GenericStateClockAdd – MAPL
MAPL_GenericStateClockAdd Subroutine
15 statements
Source File
private subroutine MAPL_GenericStateClockAdd(GC, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_GenericStateClockAdd(GC, NAME, RC)
      !ARGUMENTS:
      type (ESMF_GridComp),        intent(INOUT) :: GC
      character(len=*),            intent(IN   ) :: NAME
      integer, optional,           intent(  OUT) :: RC     ! Error code:
      !EOPI
      _RETURN(ESMF_SUCCESS)
      _UNUSED_DUMMY(GC)
      _UNUSED_DUMMY(NAME)
   end subroutine MAPL_GenericStateClockAdd
Call graph
mapl_genericstateclockadd calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_timeradd calls mapl_genericstateclockadd
mapl_genericsetservices calls mapl_genericstateclockadd
setservices calls mapl_genericsetservices, mapl_timeradd