MAPL_CFIOReadParallel_ – MAPL
MAPL_CFIOReadParallel_ Subroutine
126 statements
Source File
private subroutine MAPL_CFIOReadParallel_(bundlelist, filelist, time, blocksize, regridMethod, gsiMode, timelist, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout), pointer :: bundlelist(:)
character(len=*), intent(in) :: filelist(:)
type(ESMF_Time), intent(inout) :: time
integer, intent(in), optional :: blocksize
integer, intent(in), optional :: regridMethod
logical, intent(in), optional :: gsiMode
type(ESMF_Time), intent(in), optional :: timelist(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_CFIOReadParallel_
Source Code
  subroutine MAPL_CFIOReadParallel_(bundlelist,filelist,time,blocksize,RegridMethod,gsiMode,timelist,rc)
     type(ESMF_FieldBundle), pointer, intent(inout) :: bundlelist(:)
     character(len=*), intent(in) :: filelist(:)
     type(ESMF_Time), intent(inout) ::time
     type(ESMF_Time), optional, intent(in) ::timelist(:)
     integer, optional, intent(in) :: blocksize
     integer, optional, intent(in) :: regridMethod
     logical, optional, intent(in) :: gsiMode
     integer, optional, intent(out) :: rc
     integer                    :: status
     type(MAPL_CFIO), pointer :: cfio(:)
     type(IntegerVector) :: tindex
     integer :: blocksize_
     type(IntegerVector) :: regridMethod_
     integer, allocatable :: slices(:), psize(:), root(:),gslices(:)
     logical, allocatable :: reading(:)
     integer :: n,nn,n1,n2, nnodes, nfiles, hw,tdx,myregridmethod,nPet,maxSlices,scount
     character(len=ESMF_MAXPATHLEN) :: fname
     type(IntegerVectorIterator) :: time_iter
     type(IntegerVectorIterator) :: regrid_iter
     integer :: collection_id
     type(ESMF_CFIO), pointer :: pcfio
     type(CFIOCollection), pointer :: collection => null()
     type(ESMF_VM) :: vm
     allocate(cfio(size(filelist)),stat=status)
     _VERIFY(status)
     do n=1,size(filelist)
        cfio(n)%collection_id = MAPL_CFIOAddCollection(filelist(n))
        cfio(n)%fname = filelist(n)
        collection => collections%at(cfio(n)%collection_id)
        pcfio => collection%find(cfio(n)%fname, _RC)
        if (present(timelist)) then
          call getTIndex(pcfio,timelist(n),nn,rc=status)
        else
          call getTIndex(pcfio,time,nn,rc=status)
        endif
        _VERIFY(status)
        call tindex%push_back(nn)
     enddo
     if (present(blocksize)) then
        blocksize_=blocksize
     else
        blocksize_=1
     end if
     if (present(regridMethod)) then
        call regridMethod_%resize(size(filelist))
        do n=1,size(filelist)
           call regridMethod_%set(n,RegridMethod)
        enddo
     else
        call regridMethod_%resize(size(filelist))
        do n=1,size(filelist)
           call regridMethod_%set(n,REGRID_METHOD_BILINEAR)
        enddo
     end if
     call ESMF_VMGetCurrent(vm,rc=status)
     _VERIFY(status)
     call ESMF_VMGet(vm,petCount=nPet,rc=status)
     _VERIFY(status)
     nfiles = size(bundlelist)
     blocksize_ = min(nfiles,blocksize_)
     allocate(slices(blocksize_),psize(blocksize_),root(blocksize_),reading(blocksize_),gslices(nfiles),stat=status)
     _VERIFY(STATUS)
     reading=.false.
     hw=0
     if (present(gsiMode)) then
        cfio(:)%gsiMode=gsiMode
        if (gsiMode) hw=1
     end if
     nnodes = size(MAPL_NodeRankList)
     n1=1
     time_iter = tindex%begin()
     regrid_iter = RegridMethod_%begin()
     do n=1,nfiles
        fname = cfio(n)%fname
        myregridmethod = regrid_iter%get()
        collection_id = cfio(n)%collection_id
        call MAPL_CFIOCreateFromFile(cfio(n),bundlelist(n),regridmethod=myRegridMethod,hw=hw,rc=status)
        _VERIFY(status)
        if (mapl_am_i_root()) write(*,'(A,A)')'Parallel read file: ',trim(fname)
        call regrid_iter%next()
        gslices(n)=size(cfio(n)%krank)
     enddo
     maxSlices = maxval(gslices)
     maxSlices = max(maxSlices,nPet)
     do while(n1 <=nfiles)
        nn=0
        scount=0
        do n=n1,nfiles
           nn=nn+1
           slices(nn) = size(cfio(n)%krank)
           scount=scount+slices(nn)
           reading(nn)=.true.
           if (nn == blocksize_) exit
           if (scount > maxSlices) then
              reading(nn)=.false.
              nn=nn-1
              exit
           end if
        enddo
        n2=n1+nn-1
        call MAPL_CFIOPartition(slices,blocksize_,nNodes,reading,psize,root)
        nn=0
        do n=n1,n2
           nn=nn+1
           tdx = time_iter%get()
           call MAPL_CFIOSet(cfio(n),root=root(nn),psize=psize(nn),rc=status)
           _VERIFY(status)
           call MAPL_CFIOReadBundleRead(cfio(n),tdx,hw=hw,rc=status)
           _VERIFY(status)
           call time_iter%next()
        enddo
        do n=n1,n2
           call MAPL_CFIOReadBundleWait(cfio(n),rc=status)
           _VERIFY(status)
        enddo
        n1=n2+1
     enddo
     deallocate(slices,psize,root,reading,gslices,stat=status)
     _VERIFY(STATUS)
     deallocate(cfio,stat=status)
     _VERIFY(STATUS)
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOReadParallel_
Call graph
mapl_cfioreadparallel_ calls ESMF_VMGet, ESMF_VMGetCurrent, at, begin, find, get, mapl_am_i_root, next, gettindex, mapl_cfioaddcollection, mapl_cfiocreatefromfile, mapl_cfiopartition, mapl_cfioreadbundleread, mapl_cfioreadbundlewait, mapl_cfioset, mapl_return, mapl_verify, push_back, resize, set
mapl_cfioreadparallel calls mapl_cfioreadparallel_