MAPL_VarSpecAddFromItem – MAPL
MAPL_VarSpecAddFromItem Subroutine
14 statements
Source File
private subroutine MAPL_VarSpecAddFromItem(SPEC, ITEM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecAddFromItem
Source Code
   subroutine MAPL_VarSpecAddFromItem(SPEC,ITEM,RC)
      type (MAPL_VarSpec ), pointer         :: SPEC(:)
      type (MAPL_VarSpec ), intent(IN )     :: ITEM
      integer, optional   , intent(OUT)     :: RC
      integer                               :: STATUS
      if(.not.associated(ITEM%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      call MAPL_VarSpecCreateInList(SPEC,                                             &
           SHORT_NAME      = ITEM%SPECPTR%SHORT_NAME,        &
           LONG_NAME       = ITEM%SPECPTR%LONG_NAME,         &
           UNITS           = ITEM%SPECPTR%UNITS,             &
           DIMS            = ITEM%SPECPTR%Dims,              &
           VLOCATION       = ITEM%SPECPTR%Location,          &
           STAT            = ITEM%SPECPTR%STAT,              &
           ACCMLT_INTERVAL = ITEM%SPECPTR%ACCMLT_INTERVAL,   &
           COUPLE_INTERVAL = ITEM%SPECPTR%COUPLE_INTERVAL,   &
           DEFAULT         = ITEM%SPECPTR%DEFAULT,           &
           FIELD           = ITEM%SPECPTR%FIELD,             &
           BUNDLE          = ITEM%SPECPTR%BUNDLE,            &
           STATE           = ITEM%SPECPTR%STATE,            &
           HALOWIDTH       = ITEM%SPECPTR%HALOWIDTH,         &
           RESTART         = ITEM%SPECPTR%RESTART,           &
           PRECISION       = ITEM%SPECPTR%PRECISION,         &
           ATTR_INAMES     = ITEM%SPECPTR%ATTR_INAMES,       &
           ATTR_RNAMES     = ITEM%SPECPTR%ATTR_RNAMES,       &
           ATTR_IVALUES    = ITEM%SPECPTR%ATTR_IVALUES,      &
           ATTR_RVALUES    = ITEM%SPECPTR%ATTR_RVALUES,      &
           UNGRIDDED_DIMS  = ITEM%SPECPTR%UNGRIDDED_DIMS,    &
           FIELD_TYPE      = ITEM%SPECPTR%FIELD_TYPE,        &
           STAGGERING      = ITEM%SPECPTR%STAGGERING,        &
           ROTATION        = ITEM%SPECPTR%ROTATION,          &
           GRID            = ITEM%SPECPTR%GRID,              &
           RC=STATUS  )
      _VERIFY(STATUS)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecAddFromItem
Call graph
mapl_varspecaddfromitem calls mapl_return, mapl_varspeccreateinlist, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspeccreateinlist calls mapl_return, mapl_verify, mapl_assert, mapl_varspecgetindex
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecaddtolist calls mapl_varspecaddfromitem, mapl_varspecaddfromlist
mapl_varspecaddfromlist calls mapl_varspecaddfromitem