MAPL_StateGetTimeStamp – MAPL
MAPL_StateGetTimeStamp Subroutine
27 statements
Source File
private subroutine MAPL_StateGetTimeStamp(STATE, NAME, TIME, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
type(ESMF_Time), intent(out) :: TIME
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateGetTimeStamp
Source Code
   subroutine MAPL_StateGetTimeStamp(STATE,NAME,TIME,RC)
      type (MAPL_MetaComp),     intent(INOUT)   :: STATE
      character(len=*),         intent(IN   )   :: NAME
      type (ESMF_Time),         intent(  OUT)   :: TIME
      integer, optional,        intent(  OUT)   :: RC
      ! ErrLog Variables
      integer                           :: status
      ! Locals
      integer                           :: HOUR
      integer                           :: DATE
      integer                           :: IYR, IMM, IDD, IHR, IMN, ISC
      call MAPL_StateGetSpecAttrib(STATE,NAME,forcing=.true., &
           refresh_interval=DATE, averaging_interval=HOUR, RC=status )
      _VERIFY(status)
      if (DATE <= 0) then
         IYR=0; IMM = 1; IDD = 1
         IHR=0; IMN = 0; ISC = 0
      else
         call MAPL_UNPACKTIME(DATE,IYR,IMM,IDD)
         call MAPL_UNPACKTIME(HOUR,IHR,IMN,ISC)
      endif
      call ESMF_TimeSet(TIME, YY=IYR, MM=IMM, DD=IDD, H=IHR, M=IMN, S=ISC, RC=status )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateGetTimeStamp
Call graph
mapl_stategettimestamp calls mapl_stategetspecattrib, mapl_verify, mapl_unpacktime, esmf_timeset, mapl_return
mapl_stategetspecattrib calls mapl_verify, mapl_return, mapl_varspecgetindex, mapl_assert, mapl_varspecget
mapl_verify calls mapl_throw_exception
mapl_unpacktime calls mapl_unpacktime
mapl_return calls mapl_throw_exception, get_error_message
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_throw_exception calls initialize
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetstateptr, mapl_varspecgetfieldptr, mapl_varspecgetbundleptr, mapl_varspecgetnew
mapl_varspecgetindexbyname calls mapl_return
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_varspecgetindexofitem calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_readforcingx calls mapl_stategettimestamp
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2