MAPL_CFIOCreateFromState – MAPL
MAPL_CFIOCreateFromState Subroutine
45 statements
Source File
private subroutine MAPL_CFIOCreateFromState(MCFIO, NAME, CLOCK, STATE, OFFSET, OUTPUT_GRID, CHUNKSIZE, FREQUENCY, LEVELS, DESCR, BUNDLE, XYOFFSET, VCOORD, VUNIT, VSCALE, source, institution, comment, contact, format, EXPID, DEFLATE, GC, Order, NumCores, Nbits, TM, CONSERVATIVE, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(out) :: MCFIO
character(len=*), intent(in) :: NAME
type(ESMF_Clock), intent(inout) :: CLOCK
type(ESMF_State), intent(inout) :: STATE
type(ESMF_TimeInterval), intent(inout), optional :: OFFSET
type(ESMF_Grid), optional, pointer :: OUTPUT_GRID
integer, optional, pointer :: CHUNKSIZE(:)
integer, intent(in), optional :: FREQUENCY
real, optional, pointer :: LEVELS(:)
character(len=*), intent(in), optional :: DESCR
type(ESMF_FieldBundle), optional, pointer :: BUNDLE
integer, intent(in), optional :: XYOFFSET
character(len=*), intent(in), optional :: VCOORD
character(len=*), intent(in), optional :: VUNIT
real, intent(in), optional :: VSCALE
character(len=*), intent(in), optional :: source
character(len=*), intent(in), optional :: institution
character(len=*), intent(in), optional :: comment
character(len=*), intent(in), optional :: contact
character(len=*), intent(in), optional :: format
character(len=*), intent(in), optional :: EXPID
integer, intent(in), optional :: DEFLATE
type(ESMF_GridComp), intent(in), optional :: GC
integer, intent(in), optional :: Order
integer, intent(in), optional :: NumCores
integer, intent(in), optional :: Nbits
integer, intent(in), optional :: TM
integer, intent(in), optional :: CONSERVATIVE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CFIOCreateFromState
Source Code
  subroutine MAPL_CFIOCreateFromState ( MCFIO, NAME, CLOCK, STATE, OFFSET,  &
                                        OUTPUT_GRID, CHUNKSIZE, FREQUENCY, &
                                        LEVELS, DESCR, BUNDLE, &
                                        XYOFFSET, VCOORD, VUNIT, VSCALE,   &
                                        SOURCE, INSTITUTION, COMMENT, CONTACT, &
                                        FORMAT, EXPID, DEFLATE, GC,  ORDER, &
                                        NumCores, nbits, TM, Conservative,  RC )
!
! !ARGUMENTS:
!
    type(MAPL_CFIO),             intent(OUT) :: MCFIO
    character(LEN=*),            intent(IN)  :: NAME
    type(ESMF_State),            intent(INout)  :: STATE
    type(ESMF_Clock),            intent(INOUT)  :: CLOCK
    type(ESMF_FieldBundle), optional,  pointer    :: BUNDLE
    type(ESMF_TimeInterval), &
                     optional,   intent(INOUT):: OFFSET
    type (ESMF_Grid),optional,   pointer     :: OUTPUT_GRID
    integer,         optional,   pointer     :: CHUNKSIZE(:)
    integer,         optional,   intent(IN)  :: FREQUENCY
    real,            optional,   pointer     :: LEVELS(:)
    character(LEN=*),optional,   intent(IN)  :: DESCR
    real,            optional,   intent(IN)  :: VSCALE
    character(len=*),optional,   intent(IN)  :: VUNIT
    character(len=*),optional,   intent(IN)  :: VCOORD
    integer,         optional,   intent(IN)  :: XYOFFSET
    character(len=*),optional,   intent(IN)  :: source
    character(len=*),optional,   intent(IN)  :: institution
    character(len=*),optional,   intent(IN)  :: comment
    character(len=*),optional,   intent(IN)  :: contact
    character(len=*),optional,   intent(IN)  :: format
    character(len=*),optional,   intent(IN)  :: EXPID
    integer,         optional,   intent(IN)  :: DEFLATE
    type(ESMF_GridComp),optional,intent(IN)  :: GC
    integer,         optional,   intent(IN)  :: Order
    integer,         optional,   intent(IN)  :: Nbits
    integer,         optional,   intent(IN)  :: NumCores
    integer,         optional,   intent(IN)  :: TM
    integer,         optional,   intent(IN)  :: CONSERVATIVE
    integer, optional,           intent(OUT) :: RC
!
#ifdef ___PROTEX___
    !DESCRIPTION:
     Creates a MAPL\_CFIO object from a State. States are written by
     ``serializing'' all Fields in them, whether they are directly in
     the State or are contained within a hierarchy of embedded Bundles
     and States, into a single Bundle.
     The Method optionally returns a pointer to the serialized ESMF
     Bundle, but this is not needed for MAPL\_Write
     operations. Otherwise arguments are the same as for
     CreateFromBundle.
   Its non-optional arguments associate a {\tt NAME}, an ESMF {\tt
   BUNDLE}, and a {\tt CLOCK} with the object. An ESMF TimeInterval
   {\tt OFFSET} is an optional argument that sets an offset between the
   time on the clock when eriting and the time stamp used for the data
   (defaults to no offset).
   The {\tt format} optional argument determines whether the write
   will use the linked self-describing format (SDF) library (HDF or
   netcdf) or write GrADS readable flat files. Currently only the SDF
   library option is supported.
   The remaining (optional) arguments are especialized and used
   primarily to support MAPL\_History, or to provide documentation in
   the form of character strings that will be placed in corresponding
   attributes in the SDF file.
  !REVISION HISTORY:
   12Jun2007 Todling  Added EXPID as opt argument
#endif
!EOP
    character(len=ESMF_MAXSTR)     :: Iam="MAPL_CFIOCreateFromState"
    integer                        :: STATUS
! Locals
    type(ESMF_FieldBundle), target :: tBUNDLE
!   Create an empty bundle
!   ----------------------
    tBUNDLE = ESMF_FieldBundleCreate ( name=Iam, rc=STATUS )
    _VERIFY(STATUS)
!   Serialize the state
!   -------------------
    call ESMFL_BundleAddState ( tBUNDLE, STATE, rc=STATUS, VALIDATE=.true. )
    _VERIFY(STATUS)
!   Create the mapl_CFIO object
!   ----------------------
    call MAPL_CFIOCreateFromBundle ( MCFIO, NAME, CLOCK, tBUNDLE,        &
                                     OFFSET = OFFSET,                    &
                                     OUTPUT_GRID=OUTPUT_GRID,            &
                                     CHUNKSIZE=CHUNKSIZE,                &
                                     FREQUENCY=FREQUENCY,                &
                                     LEVELS=LEVELS,                      &
                                     DESCR=DESCR,                        &
                                     XYOFFSET= XYOFFSET,                 &
                                     VCOORD  = VCOORD,                   &
                                     VUNIT   = VUNIT,                    &
                                     VSCALE  = VSCALE,                   &
                                     SOURCE  = SOURCE,                   &
                                     INSTITUTION = INSTITUTION,          &
                                     COMMENT = COMMENT,                  &
                                     CONTACT = CONTACT,                  &
                                     FORMAT  = FORMAT,                   &
                                     EXPID   = EXPID,                    &
                                     DEFLATE = DEFLATE,                  &
                                     GC      = GC,                       &
                                     ORDER   = ORDER,                    &
                                     NumCores= NUMCORES,                 &
                                     nbits   = NBITS,                    &
                                     TM      = TM,                       &
                                     CONSERVATIVE=CONSERVATIVE,          &
                                                               RC=STATUS )
    _VERIFY(STATUS)
    if ( present(BUNDLE) ) then
         BUNDLE => tBUNDLE
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOCreateFromState
Call graph
mapl_cfiocreatefromstate calls esmf_fieldbundlecreate, mapl_verify, mapl_cfiocreatefrombundle, esmfl_bundleaddstate, mapl_return
mapl_cfiocreate calls mapl_cfiocreatefromstate
esmf_iocreate calls mapl_cfiocreatefromstate
mapl_simplebundlewrite1 calls mapl_cfiocreate
test_main calls esmf_iocreate
mapl_simplebundlewrite2 calls mapl_cfiocreate
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main