MAPL_GridCompGetFriendlies1 – MAPL
MAPL_GridCompGetFriendlies1 Subroutine
10 statements
Source File
private subroutine MAPL_GridCompGetFriendlies1(GC, TO, BUNDLE, AddGCPrefix, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: TO
type(ESMF_FieldBundle), intent(inout) :: BUNDLE
logical, intent(in), optional :: AddGCPrefix
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GridCompGetFriendlies1
Source Code
   subroutine MAPL_GridCompGetFriendlies1 ( GC, TO, BUNDLE, AddGCPrefix, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp),           intent(INOUT)  :: GC
      character(len=*),              intent(IN   )  :: TO
      type(ESMF_FieldBundle  ),      intent(INOUT)  :: BUNDLE
      logical, optional,             intent(IN   )  :: AddGCPrefix
      integer,             optional, intent(  OUT)  :: RC
      !=============================================================================
      !
      ! ErrLog Variables
      !    character(len=ESMF_MAXSTR)            :: IAm='MAPL_GridCompGetFriendlies1'
      character(len=ESMF_MAXSTR)            :: TO_(1)
      TO_(1) = TO
      call MAPL_GridCompGetFriendlies0 ( GC, TO_, BUNDLE, AddGCPrefix, RC )
   end subroutine MAPL_GridCompGetFriendlies1
Call graph
mapl_gridcompgetfriendlies1 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies0 calls ESMF_AttributeGet, ESMF_GridCompGet, esmf_fieldbundleget, esmf_fieldget, esmf_stateget, gcnamelist, get_internal_state, mapl_fieldbundleget, mapl_fieldcreate, mapl_gridcompgetfriendlies, write_parallel, am_i_friendly_, am_i_friendly__, get_child_gridcomp, mapl_internalstateget, mapl_return, mapl_verify, putfieldinbundle__
mapl_gridcompgetfriendlies calls mapl_gridcompgetfriendlies1, mapl_gridcompgetfriendlies0, mapl_gridcompgetfriendlies2, mapl_gridcompgetfriendlies3
mapl_gridcompgetfriendlies2 calls mapl_gridcompgetfriendlies0
mapl_gridcompgetfriendlies3 calls mapl_gridcompgetfriendlies0