MAPL_StateCreateFromVarSpecNew – MAPL
MAPL_StateCreateFromVarSpecNew Subroutine
83 statements
Source File
private subroutine MAPL_StateCreateFromVarSpecNew(STATE, SPEC, GRID, TILEGRID, DEFER, range, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
type(StateSpecification), intent(inout) :: SPEC
type(ESMF_Grid), intent(inout) :: GRID
type(ESMF_Grid), intent(inout), optional :: TILEGRID
logical, intent(in), optional :: DEFER
integer, intent(in), optional :: range(2)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateCreateFromVarSpecNew
Source Code
   subroutine MAPL_StateCreateFromVarSpecNew(STATE,SPEC,GRID,TILEGRID,DEFER,range,RC)
      type(ESMF_State),                 intent(INOUT) :: STATE
      type(StateSpecification),               intent(INOUT) :: SPEC
      type(ESMF_Grid),                  intent(INout) :: GRID
      logical, optional,                intent(IN   ) :: DEFER
      type(ESMF_Grid), optional,        intent(INout) :: TILEGRID
      integer, optional, intent(in) :: range(2)
      integer, optional,                intent(  OUT) :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateCreateFromVarSpec"
      integer                               :: status
      integer               :: L
      integer               :: DIMS
      integer               :: STAT
      integer               :: LOCATION
      type(ESMF_Grid)       :: GRD
      integer :: range_(2)
      type(MAPL_VarSpec), pointer :: varspec
      logical :: is_created
      type(ESMF_Field) :: SPEC_FIELD
      if (present(range)) then
         range_ = range
      else
         range_(1) = 1
         range_(2) = spec%var_specs%size()
      end if
      do L = range_(1), range_(2)
         call MAPL_VarSpecGet(SPEC%var_specs%of(L), DIMS=DIMS, VLOCATION=LOCATION, STAT=STAT, RC=status )
         _VERIFY(status)
         !ALT we should also check if we have a valid grid in the spec so we do not overwrite it
         if (IAND(STAT, MAPL_BundleItem) /= 0 .or. &
              IAND(STAT, MAPL_StateItem) /= 0) then
            GRD = GRID
         else
            ! choose the grid
            call MAPL_VarSpecGet(SPEC%var_specs%of(L), FIELD=SPEC_FIELD, _RC)
            is_created = ESMF_FieldIsCreated(SPEC_FIELD, _RC)
            if (is_created) then
               call ESMF_FieldGet(SPEC_FIELD, GRID=GRD, _RC)
            else
               Dimensionality: select case(DIMS)
               case(MAPL_DimsHorzVert)
                  select case(LOCATION)
                  case(MAPL_VLocationCenter)
                     GRD = GRID
                  case(MAPL_VLocationEdge  )
                     GRD = GRID
                  case default
                     _RETURN(ESMF_FAILURE)
                  end select
               case(MAPL_DimsHorzOnly)
                  GRD = GRID
               case(MAPL_DimsVertOnly)
                  GRD = GRID
               case(MAPL_DimsNone)
                  GRD = GRID
               case(MAPL_DimsTileOnly)
                  if (.not. present(TILEGRID)) then
                     _RETURN(ESMF_FAILURE)
                  endif
                  GRD = TILEGRID
               case(MAPL_DimsTileTile)
                  if (.not. present(TILEGRID)) then
                     _RETURN(ESMF_FAILURE)
                  endif
                  GRD = TILEGRID
               case default
                  _RETURN(ESMF_FAILURE)
               end select Dimensionality
            end if ! if created
         end if ! if ISTAT
         varspec => SPEC%var_specs%of(L)
         call MAPL_VarSpecSet(varspec, GRID=GRD, RC=status )
         _VERIFY(status)
      end do
      call MAPL_StateCreateFromSpecNew(STATE, SPEC, DEFER, range=range, RC=status  )
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateCreateFromVarSpecNew
Call graph
mapl_statecreatefromvarspecnew calls mapl_varspecget, esmf_fieldiscreated, mapl_return, esmf_fieldget, mapl_verify, mapl_varspecset, mapl_statecreatefromspecnew
mapl_varspecget calls mapl_varspecgetfieldptr, mapl_varspecgetstateptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetbundleptr
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
mapl_varspecset calls mapl_varspecsetnew
mapl_statecreatefromspecnew calls mapl_varspecget, esmf_fieldiscreated, mapl_return, esmf_fieldget, mapl_verify, mapl_varspecset, mapl_fieldcreateempty, esmf_stateadd, esmf_fieldbundleiscreated, esmf_stateiscreated, esmf_attributeset, mapl_stateadd, esmf_attributeget, esmf_fieldbundlecreate, mapl_attributeset, esmf_fieldbundleset, write_parallel, mapl_varspecgetindex, esmf_statecreate, mapl_allocatecoupling, mapl_fieldalloccommit, mapl_fieldcreate
mapl_readforcingx calls mapl_statecreatefromvarspecnew
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2