MAPL_CFIOOpenWrite – MAPL
MAPL_CFIOOpenWrite Subroutine
11 statements
Source File
public subroutine MAPL_CFIOOpenWrite(MCFIO, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_CFIOOpenWrite
Source Code
  subroutine MAPL_CFIOOpenWrite ( MCFIO, RC )
    type(MAPL_CFIO),           intent(INOUT) :: MCFIO
    integer,         optional, intent(  OUT) :: RC
    integer                        :: STATUS
! Open the file for writing only at the root process
!---------------------------------------------------
    AMROOT: if (mCFIO%MYPE==mCFIO%RootRank) then
       call ESMF_CFIOFileOpen(MCFIO%CFIO, fmode=0, RC=STATUS)
       _VERIFY(STATUS)
!      print *, ' Opened CFIO File: ', trim(mCFIO%fName)
    end if AMROOT
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOOpenWrite
Call graph
mapl_cfioopenwrite calls esmf_cfiofileopen, mapl_verify, mapl_return
esmf_cfiofileopen calls esmf_cfioset, esmf_cfioget, esmf_cfiosdffileopen
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
esmf_cfioset calls strtoint, addlist, err
esmf_cfioget calls err
esmf_cfiosdffileopen calls nf90_inquire_attribute, cfio_getattnames, cfio_getintatt, strtemplate_, cfio_diminquire, esmf_cfiovarinfocreate, nf90_inquire_variable, nf90_inq_varid, cfio_getrealatt, nf90_get_att, cfio_attinquire, nf90_inquire, getbegdatetime, nf90_inq_attname, nf90_get_var, err, cfio_open, nf90_inquire_dimension, identifydim, cfio_getcharatt
mapl_throw_exception calls initialize