MAPL_SyncSharedMemory – MAPL
MAPL_SyncSharedMemory Module Procedure
11 statements
Source File
module procedure MAPL_SyncSharedMemory module subroutine MAPL_SyncSharedMemory(rc) Interface →
! Make sure everyone on a node syncs
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_syncsharedmemory calls mapl_return, mpi_barrier, mapl_assert, mapl_syncsharedmemory
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_cfioreadbundle calls mapl_syncsharedmemory
writerestart calls mapl_syncsharedmemory, mapl_tilemaskget
mapl_statevarwrite calls mapl_syncsharedmemory, mapl_tilemaskget, mapl_fieldwrite
mapl_locstreamcreatefromfile calls mapl_syncsharedmemory
mapl_tilemaskget calls mapl_syncsharedmemory
mapl_bcastshared_1dr4 calls mapl_syncsharedmemory
mapl_fieldwrite calls mapl_syncsharedmemory, mapl_tilemaskget
mapl_bcastshared_2dr4 calls mapl_syncsharedmemory
mapl_fieldread calls mapl_syncsharedmemory, mapl_tilemaskget
mapl_statevarread calls mapl_syncsharedmemory, mapl_tilemaskget, mapl_fieldread
arrayscattershmr4d1 calls mapl_syncsharedmemory
mapl_cfiocreatefrombundle calls mapl_syncsharedmemory
initialize_subclass calls mapl_syncsharedmemory
add_horz_coordinates_from_file calls mapl_syncsharedmemory
readrestart calls mapl_syncsharedmemory, mapl_tilemaskget
arrayscattershm calls arrayscattershmr4d1
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_varwrite calls mapl_statevarwrite, mapl_fieldwrite
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
mapl_bcastshared calls mapl_bcastshared_1dr4, mapl_bcastshared_2dr4
mapl_bundlewrite calls mapl_fieldwrite
mapl_bundleread calls mapl_fieldread
mapl_varread calls mapl_fieldread, mapl_statevarread
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
esmf_iocreate calls mapl_cfiocreatefrombundle