MAPL_CollectiveScatter3D – MAPL
MAPL_CollectiveScatter3D Subroutine
54 statements
Source File
public subroutine MAPL_CollectiveScatter3D(Grid, GlobArray, LocArray, hw, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: Grid
real, intent(in) :: GlobArray(:,:,:)
real, intent(inout), target :: LocArray(:,:,:)
integer, intent(in), optional :: hw
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_CollectiveScatter3D
Source Code
  subroutine MAPL_CollectiveScatter3D(Grid, GlobArray, LocArray, hw, rc)
    type (ESMF_Grid),        intent(IN   ) :: Grid
    real, target,            intent(INOUT) :: LocArray(:,:,:)
    real,                    intent(IN   ) :: GlobArray(:,:,:)
    integer, optional,       intent(IN   ) :: hw
    integer, optional,       intent(  OUT) :: rc
! Locals
!-------
    integer                       :: status
    type (MAPL_CommRequest)       :: reqs(size(LocArray,3))
    integer                       :: root(size(LocArray,3))
    integer                       :: nNodes
    integer                       :: LM, L, nc, npes, mype
    integer                       :: nn
    type(ESMF_VM)                 :: VM
    logical                       :: HaveGlobal
    integer                       :: comm
    integer                       :: hw_
! Begin
!------
    call ESMF_VMGetCurrent(VM,         RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_VMGet(VM, petcount=npes, localpet=MYPE, mpiCommunicator=comm, RC=STATUS)
    _VERIFY(STATUS)
    if(present(hw)) then
       hw_ = hw
    else
       hw_ = 0
    endif
    nNodes = size(MAPL_NodeRankList)
    call MAPL_RoundRobinPEList(Root, nNodes, RC=STATUS)
    _VERIFY(STATUS)
    LM = size(LocArray,3)
    NC = count(Root==mype)
    HaveGlobal = NC>0
    do L=1,LM
       call MAPL_CreateRequest(GRID, Root(L), reqs(L), tag=L,       &
                               RequestType=MAPL_IsScatter,          &
                               DstArray=LocArray(:,:,L),            &
                               PrePost=.true., hw=hw_, RC=STATUS)
       _VERIFY(STATUS)
    enddo
    if(HaveGlobal) then
       _ASSERT(size(GlobArray,3)==NC, 'inconsisntent rank')
       nn = 0
       do L=1,LM
          if(Root(L)==mype) then
             nn = nn + 1
             call MAPL_ArrayIScatter (GlobArray(:,:,nn), reqs(L), hw=hw_, RC=STATUS)
             _VERIFY(STATUS)
             if(nn==NC) exit
          endif
       enddo
    end if
    do L=1,LM
       call MAPL_CollectiveWait(reqs(L), rc=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CollectiveScatter3D
Call graph
mapl_collectivescatter3d calls esmf_vmgetcurrent, mapl_verify, esmf_vmget, mapl_createrequest, mapl_roundrobinpelist, mapl_assert, mapl_arrayiscatter, mapl_collectivewait, mapl_return
mapl_verify calls mapl_throw_exception
mapl_createrequest calls esmf_vmgetcurrent, mapl_verify, esmf_vmget, mapl_assert, mapl_return, mpi_irecv, mapl_distgridget, esmf_gridget
mapl_roundrobinpelist calls mapl_verify, mapl_return, mapl_getnewrank
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_arrayiscatter calls mapl_arrayiscatter_r4_2
mapl_collectivewait calls mapl_verify, mapl_return, mpi_wait, mpi_recv
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_getnewrank calls mapl_getnewrank, mapl_return, mapl_noderanklist
mapl_distgridget calls mapl_verify, esmf_distgridget
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_arrayiscatter_r4_2 calls mapl_verify, mapl_return, mpi_isend
mapl_cfioreadbundle calls mapl_collectivescatter3d
regrid_scalar_3d_real32 calls mapl_collectivescatter3d
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadstate, mapl_cfioreadfield, mapl_cfioreadarray3d, mapl_cfioreadarray2d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadstate, mapl_cfioreadfield, mapl_cfioreadarray3d, mapl_cfioreadarray2d
mapl_cfioreadarray3d calls mapl_cfioreadfield
test_main calls esmf_ioread, mapl_cfioread
mapl_simplebundleread calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
initialize_ calls mapl_cfioread
utcfio calls test_main