MAPL_DestroyFile – MAPL
MAPL_DestroyFile Subroutine
20 statements
Source File
public subroutine MAPL_DestroyFile(unit, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_DestroyFile
Source Code
  subroutine MAPL_DestroyFile(unit,  RC )
    IMPLICIT NONE
    integer         , intent(in   )           :: unit
    integer         , intent(  out), OPTIONAL :: RC
    integer :: i,k
!ALT: Currently, this is NOP except for RAM files
    if (unit < 0) then
       ! this is RAM "file", do it!
       i = -unit
       if (associated(mem_units(i)%records)) then
          do k=1,size(mem_units(i)%records)
             call dealloc_(mem_units(i)%records(k))
          end do
          deallocate(mem_units(i)%records)
          nullify(mem_units(i)%records)
       end if
       mtaken(i)  = .false.
       mname(i) = ''
    end if
    if(present(rc)) rc = 0
    return
  end subroutine MAPL_DestroyFile
Call graph
mapl_destroyfile calls dealloc_
dealloc_ calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_destroystatesave calls mapl_destroyfile, mapl_destroystatesave
mapl_staterefresh calls mapl_destroyfile
destroy_state calls mapl_destroystatesave
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh