MAPL_GridHasDE – MAPL
MAPL_GridHasDE Function
18 statements
Source File
public function MAPL_GridHasDE(grid, rc) result(hasDE)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(in) :: grid
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
  function MAPL_GridHasDE(grid,rc) result(hasDE)
     type(ESMF_Grid), intent(in) :: grid
     integer, intent(out), optional :: rc
     integer :: status
     type(ESMF_DistGrid) :: distGrid
     type(ESMF_DeLayout) :: layout
     integer :: localDECount
     logical :: hasDE
     call ESMF_GridGet    (GRID, distGrid=distGrid, _RC)
     call ESMF_DistGridGet(distGRID, delayout=layout, _RC)
     call ESMF_DELayoutGet(layout, localDeCount=localDeCount,_RC)
     hasDe = (localDECount /=0)
     _RETURN(_SUCCESS)
  end function MAPL_GridHasDE
Call graph
mapl_gridhasde calls ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
correct_topo calls mapl_gridhasde
create_route_handle calls mapl_gridhasde
esmfl_fieldgetptrtodatar4_1 calls mapl_gridhasde
esmfl_fieldgetptrtodatar4_2 calls mapl_gridhasde
esmfl_fieldgetptrtodatar4_3 calls mapl_gridhasde
esmfl_fieldgetptrtodatar4_4 calls mapl_gridhasde
esmfl_fieldgetptrtodatar8_1 calls mapl_gridhasde
esmfl_fieldgetptrtodatar8_2 calls mapl_gridhasde
esmfl_fieldgetptrtodatar8_3 calls mapl_gridhasde
esmfl_fieldgetptrtodatar8_4 calls mapl_gridhasde
mapl_gridget calls mapl_gridhasde
regrid_scalar_2d_real32 calls mapl_gridhasde
regrid_scalar_2d_real64 calls mapl_gridhasde
regrid_scalar_3d_real32 calls mapl_gridhasde
regrid_scalar_3d_real64 calls mapl_gridhasde
regrid_vector_2d_real32 calls mapl_gridhasde
regrid_vector_2d_real64 calls mapl_gridhasde
regrid_vector_3d_real32 calls mapl_gridhasde
regrid_vector_3d_real64 calls mapl_gridhasde
regridscalar calls mapl_gridhasde
regridvector calls mapl_gridhasde
request_data_from_file calls mapl_gridhasde
stagedata calls mapl_gridhasde
swap_undef_value calls mapl_gridhasde
transpose_regrid_scalar_2d_real32 calls mapl_gridhasde
transpose_regrid_scalar_3d_real32 calls mapl_gridhasde
transpose_regrid_vector_2d_real32 calls mapl_gridhasde
transpose_regrid_vector_3d_real32 calls mapl_gridhasde