MAPL_VarSpecDestroy0 – MAPL
MAPL_VarSpecDestroy0 Subroutine
9 statements
Source File
private subroutine MAPL_VarSpecDestroy0(SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecDestroy0
Source Code
   subroutine MAPL_VarSpecDestroy0(SPEC, RC )
      type (MAPL_VarSpec ),             intent(INOUT)   :: SPEC
      integer            , optional   , intent(OUT)     :: RC
      if(associated(SPEC%SPECPtr)) then
         deallocate(SPEC%SPECPtr)
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecDestroy0
Call graph
mapl_varspecdestroy0 calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecdestroy calls mapl_varspecdestroy0, mapl_varspecdestroy1
mapl_varspecdestroy1 calls mapl_varspecdestroy0
mapl_genericstatedestroy calls mapl_varspecdestroy
mapl_genericfinalize calls mapl_genericstatedestroy
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize