MAPL_CommsAllReduceMax_R8_2 – MAPL
MAPL_CommsAllReduceMax_R8_2 Subroutine
16 statements
Source File
private subroutine MAPL_CommsAllReduceMax_R8_2(vm, sendbuf, recvbuf, cnt, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM), intent(in) :: vm
real(kind=ESMF_KIND_R8), intent(in) :: sendbuf(:,:)
real(kind=ESMF_KIND_R8), intent(inout) :: recvbuf(:,:)
integer, intent(in) :: cnt
integer, intent(out), optional :: RC
Calls
Called by
Call graph
mapl_commsallreducemax_r8_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_commsallreducemax calls mapl_commsallreducemax_r8_2
pmaxmin2d_r4 calls mapl_commsallreducemax
writerestart calls mapl_commsallreducemax
mapl_maxmin calls pmaxmin2d_r4, pmaxmin1d_r4, pmaxmin2d_r8, pmaxmin3d_r4
pmaxmin1d_r4 calls pmaxmin2d_r4
pmaxmin2d_r8 calls pmaxmin2d_r4
pmaxmin3d_r4 calls pmaxmin2d_r4
mapl_simplebundleprint calls mapl_maxmin
pmaxmin1d_r8 calls pmaxmin1d_r4
pmaxmin3d_r8 calls pmaxmin3d_r4