MAPL_GetResource_array – MAPL
MAPL_GetResource_array Subroutine
17 statements
Source File
private subroutine MAPL_GetResource_array(state, vals, label, default, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: state
class(*), intent(inout) :: vals(:)
character(len=*), intent(in) :: label
class(*), intent(in), optional :: default(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_GetResource_array
Source Code
   subroutine MAPL_GetResource_array(state, vals, label, default, rc)
      type(MAPL_MetaComp), intent(inout) :: state
      character(len=*), intent(in) :: label
      class(*), intent(inout) :: vals(:)
      class(*), optional, intent(in) :: default(:)
      integer, optional, intent(out) :: rc
      logical :: value_is_set
      integer :: status
      call MAPL_GetResource_config_array(state%cf, vals, label, value_is_set, &
         default = default, component_name = state%compname, rc = status)
      if(.not. value_is_set) then
         if (present(rc)) rc = ESMF_FAILURE
         return
      end if
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end subroutine MAPL_GetResource_array
Call graph
mapl_getresource_array calls mapl_getresource_config_array, mapl_return, mapl_verify
mapl_getresource_config_array calls mapl_return, mapl_verify, mapl_assert, get_actual_label, esmf_configgetattribute
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_actual_label calls mapl_return, mapl_verify, get_labels_with_prefix, esmf_configfindlabel
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_getresource calls mapl_getresource_array
mapl_genericstaterestore calls mapl_getresource
my_run calls mapl_getresource
mapl_esmfstatewritetofile calls mapl_getresource
mapl_genericrecord calls mapl_getresource
setservices calls mapl_getresource
mapl_genericfinalize calls mapl_getresource
mapl_genericstatesave calls mapl_getresource
mapl_staterefresh calls mapl_getresource
initialize_gc calls mapl_getresource
mapl_genericinitialize calls mapl_getresource
mapl_esmfstatereadfromfile calls mapl_getresource
mapl_genericrefresh calls mapl_getresource
arrdescrsetncpar calls mapl_getresource
mapl_staterecord calls mapl_getresource
mapl_clockinit calls mapl_getresource