MAPL_VarSpecGetStatePtr – MAPL
MAPL_VarSpecGetStatePtr Subroutine
12 statements
Source File
private subroutine MAPL_VarSpecGetStatePtr(SPEC, STATEPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
type(ESMF_State), pointer :: STATEPTR
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecGetStatePtr
Source Code
   subroutine MAPL_VarSpecGetStatePtr(SPEC, StatePTR, RC )
      type (MAPL_VarSpec ),             intent(IN )     :: SPEC
      type(ESMF_State)  ,               pointer         :: STATEPTR
      integer            , optional   , intent(OUT)     :: RC
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      STATEPTR => SPEC%SPECPtr%STATE
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecGetStatePtr
Call graph
mapl_varspecgetstateptr calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecget calls mapl_varspecgetstateptr
mapl_statecreatefromspecnew calls mapl_varspecget
mapl_wirecomponent calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_labelget calls mapl_varspecget
writerestart calls mapl_varspecget
mapl_bundleinit calls mapl_varspecget
mapl_terminateimportallbut calls mapl_varspecget
mapl_statecreatefromvarspecnew calls mapl_varspecget, mapl_statecreatefromspecnew
mapl_cplcompsetvarspecs calls mapl_varspecget
initialize calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_getnumsubtiles calls mapl_varspecget
readrestart calls mapl_varspecget
mapl_friendlyget calls mapl_varspecget
mapl_stateaddinternalspec calls mapl_varspecget
mapl_stategetspecattrib calls mapl_varspecget
mapl_varspecreconnect calls mapl_varspecget
mapl_setvarspecforcc calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_genericspecenum calls mapl_varspecget, mapl_genericspecenum
mapl_stateaddexportspecfrmchld_all calls mapl_varspecget
mapl_stateaddexportspecfrmall calls mapl_varspecget
test_simple_constructor calls mapl_varspecget
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_readforcingx calls mapl_statecreatefromvarspecnew, mapl_getnumsubtiles, mapl_stategetspecattrib
mapl_terminateimport calls mapl_terminateimportallbut
mapl_genericinitialize calls mapl_getnumsubtiles
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_stategettimestamp calls mapl_stategetspecattrib
mapl_addexportspec calls mapl_stateaddexportspecfrmchld_all, mapl_stateaddexportspecfrmall