MAPL_CFIOSetKrank – MAPL
MAPL_CFIOSetKrank Subroutine
9 statements
Source File
public subroutine MAPL_CFIOSetKrank(MCFIO, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_CFIOSetKrank
Source Code
  subroutine MAPL_CFIOSetKrank( MCFIO, RC )
  type(MAPL_CFIO),             intent(INOUT) :: MCFIO
  integer, optional,           intent(  OUT) :: RC
  integer :: status
  call MAPL_RoundRobinPEList(MCFIO%Krank,MCFIO%PartSize,root=MCFIO%ROOT,firstRank=MCFIO%RootRank,rc=status)
  _VERIFY(STATUS)
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOSetKrank
Call graph
mapl_cfiosetkrank calls mapl_return, mapl_roundrobinpelist, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_roundrobinpelist calls mapl_return, mapl_verify, mapl_getnewrank
mapl_verify calls mapl_throw_exception
mapl_getnewrank calls mapl_getnewrank, mapl_return, mapl_noderanklist
get_error_message calls at
mapl_throw_exception calls initialize