MAPL_InternalStateRetrieve – MAPL
MAPL_InternalStateRetrieve Subroutine
13 statements
Source File
public subroutine MAPL_InternalStateRetrieve(GC, MAPLOBJ, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_MetaComp), pointer :: MAPLOBJ
integer, intent(out), optional :: RC
Calls
Called by
comp_testing_driver::run_component_driver w MAPL_GenericMod::MAPL_InternalStateRetrieve
w
MAPL_CapGridCompMod::initialize_gc w
w
MAPL_GenericMod::AddChildFromDSO w
w
MAPL_GenericMod::AddChildFromGC w
w
MAPL_GenericMod::MAPL_AdvertiseService w
w
MAPL_GenericMod::MAPL_BundleInit w
w
MAPL_GenericMod::MAPL_DestroyStateSave w
w
MAPL_GenericMod::MAPL_DoNotDeferExport w
w
MAPL_GenericMod::MAPL_FindChild w
w
MAPL_GenericMod::MAPL_FriendlyGet w
w
MAPL_GenericMod::MAPL_GenericConnCheck w
w
MAPL_GenericMod::MAPL_GenericFinalize w
w
MAPL_GenericMod::MAPL_GenericRecord w
w
MAPL_GenericMod::MAPL_GenericRefresh w
w
MAPL_GenericMod::MAPL_GenericSetServices w
w
MAPL_GenericMod::MAPL_GenericStateRestore w
w
MAPL_GenericMod::MAPL_GenericStateSave w
w
MAPL_GenericMod::MAPL_GridCompGetVarSpecs w
w
MAPL_GenericMod::MAPL_GridCompSetEntryPoint w
w
MAPL_GenericMod::MAPL_LabelGet w
w
MAPL_GenericMod::MAPL_ProvidedServiceGet w
w
MAPL_GenericMod::MAPL_Reconnect w
w
MAPL_GenericMod::MAPL_RequestService w
w
MAPL_GenericMod::MAPL_ServiceRequestGet w
w
MAPL_GenericMod::MAPL_StateAddExportSpec_ w
w
MAPL_GenericMod::MAPL_StateAddExportSpecFrmChld w
w
MAPL_GenericMod::MAPL_StateAddExportSpecFrmChld_All w
w
MAPL_GenericMod::MAPL_StateAddExportSpecFrmChldName w
w
MAPL_GenericMod::MAPL_StateAddImportSpec_ w
w
MAPL_GenericMod::MAPL_StateAddInternalSpec w
w
MAPL_GenericMod::MAPL_StatePrintSpec w
w
MAPL_GenericMod::MAPL_StatePrintSpecCSV w
w
MAPL_GenericMod::MAPL_StateRecord w
w
MAPL_GenericMod::MAPL_StateRefresh w
w
MAPL_GenericMod::MAPL_WireComponent w
w
MAPL_HistoryGridCompMod::RecordRestart w
w
Contents
Source Code
MAPL_InternalStateRetrieve
Source Code
   subroutine MAPL_InternalStateRetrieve(GC, MAPLOBJ, RC)
      ! !ARGUMENTS:
      !
      type(ESMF_GridComp),                  intent(INOUT) :: GC ! Gridded component
      type (MAPL_MetaComp),                       pointer :: MAPLOBJ
      integer,                    optional, intent(  OUT) :: RC ! Return code
      !EOPI
      ! ErrLog Variables
      integer                           :: status
      ! Local variables
      ! ---------------
      call MAPL_InternalStateGet( GC, MAPLOBJ, RC=status)
      if (status /= ESMF_SUCCESS) then
         call MAPL_InternalStateCreate( GC, MAPLOBJ, RC=status)
         _VERIFY(status)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_InternalStateRetrieve
Call graph
mapl_internalstateretrieve calls mapl_internalstatecreate, mapl_internalstateget, mapl_return, mapl_verify
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
initialize calls initialize_global_time_profiler
mapl_throw_exception calls initialize
initialize_global_time_profiler calls get_global_time_profiler