MAPL_LocStreamTransformField – MAPL
MAPL_LocStreamTransformField Subroutine
66 statements
Source File
private subroutine MAPL_LocStreamTransformField(LocStream, OUTPUT, INPUT, MASK, GRID_ID, GLOBAL, ISMINE, INTERP, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStream), intent(in) :: LocStream
type(ESMF_Field), intent(out) :: OUTPUT
type(ESMF_Field), intent(inout) :: INPUT
integer, intent(in), optional :: MASK(:)
integer, intent(in), optional :: GRID_ID
logical, intent(in), optional :: GLOBAL
logical, intent(in), optional :: ISMINE(:)
logical, intent(in), optional :: INTERP
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_LocStreamTransformField (LocStream, OUTPUT, INPUT, MASK, &
                                           GRID_ID, GLOBAL, ISMINE, INTERP, RC )
    !ARGUMENTS:
    type(ESMF_Field),          intent(OUT) :: OUTPUT
    type(ESMF_Field),          intent(INout) :: INPUT
    type(MAPL_LocStream),      intent(IN ) :: LocStream
    integer, optional,         intent(IN ) :: MASK(:)
    logical, optional,         intent(IN ) :: ISMINE(:), INTERP
    logical, optional,         intent(IN ) :: GLOBAL
    integer, optional,         intent(IN ) :: GRID_ID
    integer, optional,         intent(OUT) :: RC
    !EOPI
! Local variables
  integer                    :: STATUS
  integer                    :: N, NT
  integer                    :: OutRank
  integer                    :: InRank
  type(ESMF_GRID)            :: INGRID
  type(ESMF_GRID)            :: OUTGRID
  type(ESMF_ARRAY)           :: INARRAY
  type(ESMF_ARRAY)           :: OUTARRAY
  real, pointer              :: TILEVAR(:)
  real, pointer              :: GRIDVAR(:,:)
  logical, pointer           :: MSK(:)
! Begin
  NT = LocStream%Ptr%NT_LOCAL
  allocate(MSK(NT),STAT=STATUS)
  _VERIFY(STATUS)
  if(present(MASK)) then
     do N = 1, NT
        MSK(N) = any(LocSTREAM%Ptr%LOCAL_GEOLOCATION(N)%T==MASK)
     end do
  else
     MSK = .true.
  end if
  call ESMF_FieldGet     (OUTPUT,   GRID=OUTGRID, RC=STATUS)
  _VERIFY(STATUS)
  call ESMF_FieldGet(OUTPUT, Array=OUTARRAY,     RC=STATUS)
  _VERIFY(STATUS)
  call ESMF_ArrayGet     (OUTARRAY, RANK=OUTRANK, RC=STATUS)
  _VERIFY(STATUS)
  call ESMF_FieldGet     (INPUT,    GRID=INGRID,  RC=STATUS)
  _VERIFY(STATUS)
  call ESMF_FieldGet(INPUT, Array=INARRAY,      RC=STATUS)
  _VERIFY(STATUS)
  call ESMF_ArrayGet     (INARRAY,  RANK=INRANK,  RC=STATUS)
  _VERIFY(STATUS)
  if    ( INRANK==1 .and. OUTRANK==2) then ! T2G
     call ESMF_ArrayGet(OUTARRAY, localDE=0, farrayptr=GRIDVAR, RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_ArrayGet( INARRAY, localDE=0, farrayptr=TILEVAR, RC=STATUS)
     _VERIFY(STATUS)
     _ASSERT(size(TILEVAR)==NT,'needs informative message')
     call MAPL_LocStreamTransformT2G (LOCSTREAM, GRIDVAR, TILEVAR, MASK=MSK, RC=STATUS)
     _VERIFY(STATUS)
   elseif( OUTRANK==1 .and. INRANK==2) then ! G2T
     call ESMF_ArrayGet(OUTARRAY, localDE=0, farrayptr=TILEVAR, RC=STATUS)
     _VERIFY(STATUS)
     call ESMF_ArrayGet( INARRAY, localDE=0, farrayptr=GRIDVAR, RC=STATUS)
     _VERIFY(STATUS)
     _ASSERT(size(TILEVAR)==NT,'needs informative message')
     call MAPL_LocStreamTransformG2T(LOCSTREAM, TILEVAR, GRIDVAR, MSK, &
          GRID_ID, GLOBAL, ISMINE, INTERP, RC=STATUS)
     _VERIFY(STATUS)
  else
     _RETURN(ESMF_FAILURE)
  end if
  deallocate(MSK)
  _RETURN(ESMF_SUCCESS)
end subroutine MAPL_LocStreamTransformField
Call graph
mapl_locstreamtransformfield calls esmf_arrayget, esmf_fieldget, mapl_assert, mapl_locstreamtransformg2t, mapl_locstreamtransformt2g, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_locstreamtransformg2t calls mapl_assert, mapl_return, mapl_verify, esmfl_halo, mapl_grid_interior
mapl_locstreamtransformt2g calls mapl_assert, mapl_return, mapl_verify, mapl_grid_interior
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_halo calls esmfl_halo_r4_2d
mapl_grid_interior calls mapl_grid_interior, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, mapl_distgridget
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
esmfl_halo_r4_2d calls mapl_assert, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, halo, mapl_commssendrecv, get_factory, mapl_distgridget, mapl_getimsjms, mapl_gridget
mapl_locstreamtransform calls mapl_locstreamtransformfield
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run calls regridtransform, regridtransformt2g, regridtransformt2g2g
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2