MAPL_Assert_return_code – MAPL
MAPL_Assert_return_code Function
14 statements
Source File
private function MAPL_Assert_return_code(condition, return_code, filename, line, rc) result(fail)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: condition
integer, intent(in) :: return_code
character(len=*), intent(in) :: filename
integer, intent(in) :: line
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function MAPL_Assert_return_code(condition, return_code, filename, line, rc) result(fail)
      logical, intent(in) :: condition
      integer, intent(in) :: return_code
      character(*), intent(in) :: filename
      integer, intent(in) :: line
      integer, optional, intent(out) :: rc ! Not present in MAIN
      character(:), allocatable :: message
      fail = .not. condition
      if (fail) then
         message = get_error_message(return_code)
         !$omp critical (MAPL_ErrorHandling2)
         call MAPL_throw_exception(filename, line, message=message)
         !$omp end critical (MAPL_ErrorHandling2)
         if (present(rc)) rc = return_code
      end if
   end function MAPL_Assert_return_code
Call graph
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_return_code