MAPL_AdjustIsNeeded – MAPL
MAPL_AdjustIsNeeded Subroutine
41 statements
Source File
private recursive subroutine MAPL_AdjustIsNeeded(GC, EXPORT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: EXPORT
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   recursive subroutine MAPL_AdjustIsNeeded ( GC, EXPORT, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp), intent(INOUT) :: GC     ! Gridded component
      type(ESMF_State),    intent(INOUT) :: EXPORT ! Export state
      integer, optional,   intent(  OUT) :: RC     ! Error code:
      !EOPI
      ! ErrLog Variables
      character(len=ESMF_MAXSTR)    :: IAm
      character(len=ESMF_MAXSTR)    :: comp_name
      integer                       :: status
      ! Local derived type aliases
      type (MAPL_MetaComp),pointer     :: STATE
      integer                          :: I
      integer                          :: ITEMCOUNT
      type (ESMF_StateItem_Flag), pointer :: ITEMTYPES(:)
      character(len=ESMF_MAXSTR ), pointer  :: ITEMNAMES(:)
      type(ESMF_GridComp), pointer :: gridcomp
      type(ESMF_State), pointer :: child_export_state
      Iam = "MAPL_AdjustIsNeeded"
      call ESMF_GridCompGet( GC, NAME=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // trim(Iam)
      ! Retrieve the pointer to the internal state.
      ! -------------------------------------------
      call MAPL_InternalStateGet ( GC, STATE, RC=status)
      _VERIFY(status)
      call ESMF_StateGet(EXPORT,ITEMCOUNT=ITEMCOUNT,RC=status)
      _VERIFY(status)
      IF (ITEMCOUNT>0) then
         allocate(ITEMNAMES(ITEMCOUNT),STAT=status)
         _VERIFY(status)
         allocate(ITEMTYPES(ITEMCOUNT),STAT=status)
         _VERIFY(status)
         call ESMF_StateGet(EXPORT,ITEMNAMELIST=ITEMNAMES,ITEMTYPELIST=ITEMTYPES,RC=status)
         _VERIFY(status)
         deallocate(ITEMNAMES)
         deallocate(ITEMTYPES)
      end IF
      do I = 1, STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(I)
         child_export_state => state%get_child_export_state(i)
         call MAPL_AdjustIsNeeded(gridcomp, child_export_state, RC=status)
         _VERIFY(status)
      end do
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_AdjustIsNeeded
Call graph
mapl_adjustisneeded calls mapl_adjustisneeded, ESMF_GridCompGet, esmf_stateget, get_child_export_state, get_child_gridcomp, get_num_children, mapl_internalstateget, mapl_return, mapl_verify
get_child_export_state calls get_export_state, get_ith_child
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_export_state calls get_current_thread, is_threading_active
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_throw_exception calls initialize
mapl_genericinitialize calls mapl_adjustisneeded
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize