MAPL_ExtDataEvaluateMask – MAPL
MAPL_ExtDataEvaluateMask Subroutine
242 statements
Source File
private subroutine MAPL_ExtDataEvaluateMask(state, exportName, exportExpr, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
character(len=*), intent(in) :: exportName
character(len=*), intent(in) :: exportExpr
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ExtDataEvaluateMask
Source Code
  subroutine MAPL_ExtDataEvaluateMask(state,exportName,exportExpr,rc)
    type(ESMF_STATE),           intent(inout) :: state
    character(len=*),           intent(in)    :: exportName
    character(len=*),           intent(in)    :: exportExpr
    integer, optional,          intent(out)   :: rc
    integer :: status
    integer :: k,i
    character(len=ESMF_MAXSTR) :: maskString,maskname,vartomask,functionname,clatS,clatN
    character(len=ESMF_MAXSTR) :: strtmp
    integer, allocatable :: regionNumbers(:), flag(:)
    integer, allocatable :: mask(:,:)
    real, pointer        :: rmask(:,:)    => null()
    real, pointer        :: rvar2d(:,:)   => null()
    real, pointer        :: rvar3d(:,:,:) => null()
    real, pointer        :: var2d(:,:)    => null()
    real, pointer        :: var3d(:,:,:)  => null()
    real(REAL64), pointer :: lats(:,:)     => null()
    real(REAL64), pointer :: lons(:,:)     => null()
    real(REAL64)         :: limitS, limitN, limitE, limitW
    real(REAL64)         :: limitE1, limitW1
    real(REAL64)         :: limitE2, limitW2
    type(ESMF_Field)     :: field
    type(ESMF_Grid)      :: grid
    integer              :: rank,ib,ie,is,i1,nargs
    integer              :: counts(3)
    logical              :: isCube, twoBox
    real, allocatable    :: temp2d(:,:)
    character(len=ESMF_MAXSTR) :: args(5)
    call ESMF_StateGet(state,exportName,field,_RC)
    call ESMF_FieldGet(field,rank=rank,grid=grid,_RC)
    i1 = index(exportExpr,"(")
    _ASSERT(i1 > 0,'Expected "(" in expression: ' // trim(exportExpr))
    functionname = adjustl(exportExpr(:i1-1))
    functionname = ESMF_UtilStringLowerCase(functionname, _RC)
    if (trim(functionname) == "regionmask") then
       ! get mask string
       ib = index(exportExpr,";")
       ie = index(exportExpr,")")
       maskString = trim(exportExpr(ib+1:ie-1))
       ! get mask name
       ie = index(exportExpr,";")
       is = index(exportExpr,"(")
       ib = index(exportExpr,",")
       vartomask = trim(exportExpr(is+1:ib-1))
       maskname = trim(exportExpr(ib+1:ie-1))
       call MAPL_GetPointer(state,rmask,maskName,_RC)
       if (rank == 2) then
          call MAPL_GetPointer(state,rvar2d,vartomask,_RC)
          call MAPL_GetPointer(state,var2d,exportName,_RC)
       else if (rank == 3) then
          call MAPL_GetPointer(state,rvar3d,vartomask,_RC)
          call MAPL_GetPointer(state,var3d,exportName,_RC)
       else
          _FAIL('Rank must be 2 or 3')
       end if
       k=32
       allocate(regionNumbers(k), flag(k), stat=status)
       _VERIFY(STATUS)
       regionNumbers = 0
       call MAPL_ExtDataExtractIntegers(maskString,k,regionNumbers,rc=status)
       _VERIFY(STATUS)
       flag(:) = 1
       WHERE(regionNumbers(:) == 0) flag(:) = 0
       k = SUM(flag)
       deallocate(flag,stat=status)
       _VERIFY(STATUS)
   !   Set local mask to 1 where gridMask matches each integer (within precision!)
   !   ---------------------------------------------------------------------------
       allocate(mask(size(rmask,1),size(rmask,2)),stat=status)
       _VERIFY(STATUS)
       mask = 0
       DO i=1,k
        WHERE(regionNumbers(i)-0.01 <= rmask .AND. &
              rmask <= regionNumbers(i)+0.01) mask = 1
       END DO
       if (rank == 2) then
          var2d = rvar2d
          where(mask == 0) var2d = 0.0
       else if (rank == 3) then
          var3d = rvar3d
          do i=1,size(var3d,3)
             where(mask == 0) var3d(:,:,i) = 0.0
          enddo
       end if
       deallocate( mask)
    elseif(trim(functionname) == "zonemask") then
       ib = index(exportExpr,"(")
       ie = index(exportExpr,",")
       vartomask = trim(exportExpr(ib+1:ie-1))
       ib = index(exportExpr,",")
       is = index(exportExpr,",",back=.true.)
       ie = index(exportExpr,")")
       clatS = trim(exportExpr(ib+1:is-1))
       clatN = trim(exportExpr(is+1:ie-1))
       READ(clatS,*,IOSTAT=status) limitS
       _VERIFY(status)
       READ(clatN,*,IOSTAT=status) limitN
       _VERIFY(status)
       call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lats, rc=status)
       _VERIFY(status)
       limitN=limitN*MAPL_PI_R8/180.0d0
       limitS=limitS*MAPL_PI_R8/180.0d0
       if (rank == 2) then
          call MAPL_GetPointer(state,rvar2d,vartomask,_RC)
          call MAPL_GetPointer(state,var2d,exportName,_RC)
       else if (rank == 3) then
          call MAPL_GetPointer(state,rvar3d,vartomask,_RC)
          call MAPL_GetPointer(state,var3d,exportName,_RC)
       else
          _FAIL('Rank must be 2 or 3')
       end if
       if (rank == 2) then
          var2d = 0.0
          where(limitS <= lats .and. lats <=limitN) var2d = rvar2d
       else if (rank == 3) then
          var3d = 0.0
          do i=1,size(var3d,3)
             where(limitS <= lats .and. lats <=limitN) var3d(:,:,i) = rvar3d(:,:,i)
          enddo
       end if
    elseif(trim(functionname) == "boxmask") then
       is=index(exportExpr,'(')
       ie=index(exportExpr,')')
       strtmp = exportExpr(is+1:ie-1)
       do nargs=1,5
          is = index(strtmp,',')
          if (is >0) then
             args(nargs) = strtmp(:is-1)
          else
             args(nargs) = strtmp
          end if
          strtmp = strtmp(is+1:)
       end do
       varToMask=args(1)
       READ(args(2),*,IOSTAT=status) limitS
       _VERIFY(status)
       READ(args(3),*,IOSTAT=status) limitN
       _VERIFY(status)
       READ(args(4),*,IOSTAT=status) limitW
       _VERIFY(status)
       READ(args(5),*,IOSTAT=status) limitE
       _VERIFY(status)
       _ASSERT(limitE > limitW,'LimitE must be greater than limitW')
       _ASSERT(limitE /= limitW,'LimitE cannot equal limitW')
       _ASSERT(limitN /= limitS,'LimitN cannot equal LimitS')
       _ASSERT((limitE-limitW)<=360.0d0,'(LimitE - LimitW) must be less than or equal to 360')
       call ESMF_GridGetCoord(grid, coordDim=1, localDE=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lons, rc=status)
       _VERIFY(status)
       call ESMF_GridGetCoord(grid, coordDim=2, localDE=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, farrayPtr=lats, rc=status)
       _VERIFY(status)
       ! do some tests if cube goes from 0 to 360, lat-lon -180 to 180
       call MAPL_GridGet(grid, globalCellCountPerDim=COUNTS,rc=status)
       _VERIFY(STATUS)
       if (counts(2)==6*counts(1)) then
          isCube=.true.
       else
          isCube=.false.
       end if
       twoBox = .false.
       if (isCube) then
          if (limitW < 0.0d0 .and. limitE >=0.0d0) then
             ! need two boxes
             twoBox=.true.
             limitW1=0.0d0
             limitE1=limitE
             limitW2=limitW+360.0d0
             limitE2=360.0d0
          else if (limitW <0.0d0 .and. limitE <0.0d0) then
             ! just shift
             limitW1=limitW+360.d0
             limitE1=limitE+360.d0
          else
             ! normal case
             limitW1=limitW
             limitE1=limitE
          end if
       else
          if (limitW  <= 180.0d0 .and. limitE > 180.0d0) then
             ! need two boxes
             twoBox=.true.
             limitW1=limitW
             limitE1=180.0d0
             limitW2=-180.d0
             limitE2=limitE-360.0d0
          else if (limitW > 180.0d0 .and. limitE > 180.0d0) then
             ! just shift
             limitW1=limitW-360.d0
             limitE1=limitE-360.d0
          else
             ! normal case
             limitW1=limitW
             limitE1=limitE
          end if
       end if
       limitE1=limitE1*MAPL_PI_R8/180.0d0
       limitW1=limitW1*MAPL_PI_R8/180.0d0
       limitE2=limitE2*MAPL_PI_R8/180.0d0
       limitW2=limitW2*MAPL_PI_R8/180.0d0
       limitN=limitN*MAPL_PI_R8/180.0d0
       limitS=limitS*MAPL_PI_R8/180.0d0
       if (rank == 2) then
          call MAPL_GetPointer(state,rvar2d,vartomask,_RC)
          call MAPL_GetPointer(state,var2d,exportName,_RC)
       else if (rank == 3) then
          call MAPL_GetPointer(state,rvar3d,vartomask,_RC)
          call MAPL_GetPointer(state,var3d,exportName,_RC)
       else
          _FAIL('Rank must be 2 or 3')
       end if
       if (rank == 2) then
          var2d = 0.0
          where(limitS <= lats .and. lats <=limitN .and. limitW1 <= lons .and. lons <= limitE1 ) var2d = rvar2d
       else if (rank == 3) then
          var3d = 0.0
          do i=1,size(var3d,3)
             where(limitS <= lats .and. lats <=limitN .and. limitW1 <= lons .and. lons <= limitE1 ) var3d(:,:,i) = rvar3d(:,:,i)
          enddo
       end if
       if (twoBox) then
          allocate(temp2d(size(var2d,1),size(var2d,2)),stat=status)
          _VERIFY(STATUS)
          if (rank == 2) then
             temp2d = 0.0
             where(limitS <= lats .and. lats <=limitN .and. limitW2 <= lons .and. lons <= limitE2 ) temp2d = rvar2d
             var2d=var2d+temp2d
          else if (rank == 3) then
             do i=1,size(var3d,3)
                temp2d = 0.0
                where(limitS <= lats .and. lats <=limitN .and. limitW2 <= lons .and. lons <= limitE2 ) temp2d = rvar3d(:,:,i)
                var3d(:,:,i)=var3d(:,:,i)+temp2d
             enddo
          end if
          deallocate(temp2d)
       end if
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataEvaluateMask
Call graph
mapl_extdataevaluatemask calls esmf_stateget, esmf_utilstringlowercase, mapl_verify, esmf_fieldget, mapl_assert, esmfl_stategetpointertodata, mapl_extdataextractintegers, esmf_gridgetcoord, mapl_gridget, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_extdataextractintegers calls mapl_return
mapl_gridget calls mapl_verify, mapl_return, esmf_gridget, esmf_attributeget, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
esmfl_stategetptrtodatar4_1 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
esmfl_stategetptrtodatar8_1 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls esmf_stateget, mapl_verify, esmf_fieldget, mapl_return, mapl_allocatecoupling
mapl_gridhasde calls mapl_verify, mapl_return, esmf_gridget, esmf_delayoutget, esmf_distgridget
mapl_allocatecoupling calls mapl_allocatecoupling
calcderivedfield calls mapl_extdataevaluatemask
run_ calls calcderivedfield