MAPL_ClimInterpFac – MAPL
MAPL_ClimInterpFac Module Subroutine
38 statements
Source File
module subroutine MAPL_ClimInterpFac(CLOCK, I1, I2, FAC, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: CLOCK
integer, intent(out) :: I1
integer, intent(out) :: I2
real, intent(out) :: FAC
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_ClimInterpFac
Source Code
  module subroutine MAPL_ClimInterpFac (CLOCK,I1,I2,FAC, RC)
    !------------------------------------------------------------
    type(ESMF_CLOCK),  intent(in ) :: CLOCK
    integer,           intent(OUT) :: I1, I2
    real,              intent(out) :: FAC
    integer, optional, intent(out) :: RC
    integer                                 :: STATUS
    character(len=ESMF_MAXSTR), parameter   :: IAm='MAPL_ClimInterpFac'
    type (ESMF_Time)                  :: CurrTime
    type (ESMF_Time)                  :: midMonth
    type (ESMF_Time)                  :: BEFORE, AFTER
    type (ESMF_TimeInterval)          :: oneMonth
    type (ESMF_Calendar)              :: cal
    call ESMF_ClockGet       ( CLOCK,    CurrTime=CurrTime, calendar=cal, rc=STATUS )
    _VERIFY(STATUS)
    call ESMF_TimeGet        ( CurrTime, midMonth=midMonth,               rc=STATUS )
    _VERIFY(STATUS)
    call ESMF_TimeIntervalSet( oneMonth, MM = 1, calendar=cal,            rc=status )
    _VERIFY(STATUS)
    if( CURRTIME < midMonth ) then
       AFTER    = midMonth
       midMonth = midMonth - oneMonth
       call ESMF_TimeGet (midMonth, midMonth=BEFORE, rc=STATUS )
       _VERIFY(STATUS)
    else
       BEFORE   = midMonth
       midMonth = midMonth + oneMonth
       call ESMF_TimeGet (midMonth, midMonth=AFTER , rc=STATUS )
       _VERIFY(STATUS)
    endif
    call MAPL_Interp_Fac( CURRTIME, BEFORE, AFTER, FAC, RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_TimeGet (BEFORE, MM=I1, rc=STATUS )
    _VERIFY(STATUS)
    call ESMF_TimeGet (AFTER , MM=I2, rc=STATUS )
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ClimInterpFac
Call graph
mapl_climinterpfac calls esmf_clockget, mapl_verify, esmf_timeintervalset, esmf_timeget, mapl_interp_fac, mapl_return, mapl_climinterpfac
mapl_verify calls mapl_throw_exception
mapl_interp_fac calls mapl_interp_fac
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_sungetsolarconstantfromnetcdffile calls mapl_climinterpfac
mapl_sungetsolarconstant calls mapl_sungetsolarconstantfromnetcdffile