MAPL_MemUtilsWriteVM – MAPL
MAPL_MemUtilsWriteVM Subroutine
28 statements
Source File
private subroutine MAPL_MemUtilsWriteVM(vm, text, always, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
character(len=*), intent(in) :: text
logical, intent(in), optional :: always
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_MemUtilsWriteVM
Source Code
  subroutine MAPL_MemUtilsWriteVM( vm, text, always, RC )
    type(ESMF_VM) :: vm
    character(len=*), intent(in) :: text
    logical, intent(in), optional :: always
    integer, optional, intent(OUT  ) :: RC
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_MemUtilsWriteVM"
    integer :: status
    integer :: comm
    call ESMF_VMGet(vm,mpicommunicator=comm,rc=status)
    _VERIFY(status)
    if( PRESENT(always) )then
        if( .NOT.always ) then
            _RETURN(ESMF_SUCCESS)
        endif
        call MAPL_MemUtilsWriteComm(text,comm=comm,always=always,rc=status)
        _VERIFY(STATUS)
    else
        if( DISABLED ) then
            _RETURN(ESMF_SUCCESS)
        endif
        call MAPL_MemUtilsWriteComm(text,comm=comm,rc=status)
        _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_MemUtilsWriteVM
Call graph
mapl_memutilswritevm calls ESMF_VMGet, mapl_memutilswritecomm, mapl_return, mapl_verify
mapl_memutilswritecomm calls mapl_return, mapl_verify, write_parallel, mpi_allreduce, mpi_comm_size, mem_dump
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
write_parallel calls write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r4_1, write_parallel_r8_0, write_parallel_r8_1, write_parallel_string_0
get_error_message calls at
mapl_throw_exception calls initialize
mem_dump calls mapl_return, mapl_verify, get_unit
write_parallel_i4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_i4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_r4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_r4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_r8_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, dealloc_, records
write_parallel_r8_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write, alloc_, records
write_parallel_string_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mpi_file_seek, mpi_file_write
mapl_memutilswrite calls mapl_memutilswritevm
mapl_genericinitialize calls mapl_memutilswrite
run_mapl_gridcomp calls mapl_memutilswrite
test_main calls mapl_memutilswrite
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
run_gc calls run_mapl_gridcomp
utcfio calls test_main