MAPL_TrimString – MAPL
MAPL_TrimString Module Function
17 statements
Source File
module function MAPL_TrimString(istring, rc) result(ostring) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: istring
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Contents
Source Code
MAPL_TrimString
Source Code
  module function MAPL_TrimString(istring,rc) result(ostring)
    character(len=*), intent(in) :: istring
    integer, optional, intent(out) :: rc
    character(len=:), allocatable :: ostring
    integer :: strlen
    integer :: status
    strlen = len_trim(istring)
    if (istring(strlen:strlen)==char(0)) then
       allocate(ostring,source=istring(1:strlen-1),stat=status)
       _VERIFY(status)
    else
       allocate(ostring,source=istring(1:strlen),stat=status)
       _VERIFY(status)
    end if
    _RETURN(_SUCCESS)
  end function MAPL_TrimString
Call graph
mapl_trimstring calls mapl_return, mapl_verify, mapl_trimstring
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
getlevs calls mapl_trimstring
create_bracketing_fields calls getlevs
create_primary_field calls getlevs
initialize_ calls getlevs, create_primary_field
run_ calls create_bracketing_fields