MAPL_VarWrite_I4_1d – MAPL
MAPL_VarWrite_I4_1d Subroutine
49 statements
Source File
private subroutine MAPL_VarWrite_I4_1d(UNIT, GRID, A, MASK, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
integer(kind=ESMF_KIND_I4), intent(in) :: A(:)
integer, intent(in), optional :: MASK(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_VarWrite_I4_1d(UNIT, GRID, A, MASK, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_Grid)            , intent(INout) :: GRID
    integer(kind=ESMF_KIND_I4)  , intent(IN   ) :: A(:)
    integer,           optional , intent(IN   ) :: MASK(:)
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer(kind=ESMF_KIND_I4),  allocatable :: VAR(:)
    integer                               :: IM_WORLD
    integer                               :: status
    integer                               :: DIMS(ESMF_MAXGRIDDIM)
    type (ESMF_DELayout)                  :: layout
    type (ESMF_DistGrid)                  :: distGrid
    if(unit < 0) then
      munit => MEM_units(-unit)
      munit%prevrec = munit%prevrec + 1
      if(.not.associated(munit%Records)) then
         allocate(munit%Records(16),stat=status)
         _VERIFY(STATUS)
      elseif(size(munit%Records)< munit%prevrec) then
         allocate(REC(munit%prevrec*2),stat=status)
         _VERIFY(STATUS)
         REC(:munit%prevrec-1) = munit%Records
         deallocate(munit%Records)
         munit%Records => REC
      endif
      call alloc_(munit%Records(munit%prevrec),i4_1,size(A),rc=status)
      _VERIFY(STATUS)
      munit%Records(munit%prevrec)%I4_1  = A
    else
    call MAPL_GridGet(GRID, globalCellCountPerDim=DIMS, RC=STATUS)
    _VERIFY(STATUS)
    IM_WORLD = DIMS(1)
    allocate(VAR(IM_WORLD), stat=status)
    _VERIFY(STATUS)
    call ESMF_GridGet(grid, distGrid=distGrid, rc=STATUS)
    _VERIFY(STATUS)
    call ESMF_DistGridGet(distGrid, delayout=layout, rc=STATUS)
    _VERIFY(STATUS)
    call ArrayGather(A, VAR, grid, mask=mask, rc=status)
    _VERIFY(STATUS)
    if (MAPL_am_i_root(layout)) then
       write (UNIT, IOSTAT=status) VAR
       _VERIFY(STATUS)
    end if
    deallocate(VAR)
    endif
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarWrite_I4_1d
Call graph
mapl_varwrite_i4_1d calls ESMF_DistGridGet, ESMF_GridGet, arraygather, mapl_am_i_root, alloc_, mapl_gridget, mapl_return, mapl_verify
arraygather calls arraygather_i4_1, arraygather_r4_1, arraygather_r4_2, arraygather_r8_1, arraygather_r8_2, arraygatherrcvcnt_i4_1, arraygatherrcvcnt_r4_1
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
alloc_ calls mapl_return, mapl_verify, mapl_assert, dealloc_
mapl_gridget calls ESMF_DistGridGet, ESMF_GridGet, mapl_return, mapl_verify, ESMF_AttributeGet, mapl_distgridget, mapl_getimsjms, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_varwrite calls mapl_varwrite_i4_1d, mapl_fieldwrite, mapl_varwrite_r4_2d, mapl_varwrite_r4_3d, mapl_varwrite_r4_4d, mapl_varwrite_r8_2d, mapl_varwrite_r8_3d, mapl_varwrite_r8_4d, mapl_bundlewrite, mapl_statevarwrite
mapl_esmfstatewritetofile calls mapl_varwrite
mapl_fieldwrite calls mapl_varwrite
mapl_varwrite_r4_2d calls mapl_varwrite
mapl_varwrite_r4_3d calls mapl_varwrite
mapl_varwrite_r4_4d calls mapl_varwrite
mapl_varwrite_r8_2d calls mapl_varwrite
mapl_varwrite_r8_3d calls mapl_varwrite
mapl_varwrite_r8_4d calls mapl_varwrite
run calls mapl_varwrite
writerestart calls mapl_varwrite
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_bundlewrite calls mapl_fieldwrite
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_statevarwrite calls mapl_fieldwrite, mapl_bundlewrite
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave