MAPL_DoNotAllocateImport – MAPL
MAPL_DoNotAllocateImport Subroutine
19 statements
Source File
public subroutine MAPL_DoNotAllocateImport(GC, NAME, notFoundOK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: NAME
logical, intent(in), optional :: notFoundOK
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_DoNotAllocateImport
Source Code
   subroutine MAPL_DoNotAllocateImport(GC, NAME, notFoundOK, RC)
      type(ESMF_GridComp),  intent(INOUT) :: GC         ! Gridded component
      character(len=*),     intent(IN   ) :: NAME
      logical, optional,    intent(IN   ) :: notFoundOK
      integer, optional,    intent(  OUT) :: RC         ! Return code
      integer                       :: status
      type (MAPL_MetaComp), pointer :: MAPLOBJ
      type (MAPL_VarSpec),  pointer :: SPEC(:) => null()
      call MAPL_GetObjectFromGC(GC, MAPLOBJ, RC=status)
      _VERIFY(status)
      call MAPL_Get (MAPLOBJ, ImportSpec=spec, RC=status )
      _VERIFY(status)
      if (associated(spec)) then
         call MAPL_DoNotAllocateVar(SPEC, NAME, notFoundOK, RC=status)
         _VERIFY(status)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_DoNotAllocateImport
Call graph
mapl_donotallocateimport calls mapl_getobjectfromgc, mapl_get, mapl_donotallocatevar, mapl_verify, mapl_return
mapl_getobjectfromgc calls mapl_internalstateget
mapl_get calls mapl_genericstateget
mapl_donotallocatevar calls mapl_verify, mapl_return, mapl_assert, mapl_varspecset, mapl_varspecgetindex
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_genericstateget calls mapl_verify, mapl_return, mapl_sunorbitcreated, esmf_gridget, mapl_locstreamget, mapl_sunorbitcreatefromconfig
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecset calls mapl_varspecsetnew
mapl_varspecgetindex calls mapl_varspecgetindexofitem, mapl_varspecgetindexbyname
mapl_throw_exception calls initialize
mapl_varspecgetindexofitem calls mapl_return
mapl_sunorbitcreated calls mapl_return
mapl_locstreamget calls mapl_return, mapl_assert
mapl_sunorbitcreatefromconfig calls mapl_verify, mapl_return, esmf_configgetattribute, mapl_sunorbitcreate
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_varspecsetnew calls mapl_return
mapl_varspecgetindexbyname calls mapl_return