MAPL_DeAllocNodeArray_4DI4 – MAPL
MAPL_DeAllocNodeArray_4DI4 Module Procedure
13 statements
Source File
module procedure MAPL_DeAllocNodeArray_4DI4 module subroutine MAPL_DeAllocNodeArray_4DI4(Ptr, rc) Interface →
Arguments
Type Intent Optional Attributes Name
integer, pointer :: Ptr(:,:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_deallocnodearray_4di4 calls releasesharedmemory, mapl_return, mapl_verify, mapl_deallocnodearray_4di4
releasesharedmemory calls releasesharedmemory, mapl_return, mapl_assert, shmctl, shmdt, mpi_barrier, segs
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_deallocnodearray calls mapl_deallocnodearray_4di4
add_horz_coordinates_from_file calls mapl_deallocnodearray
initialize_subclass calls mapl_deallocnodearray
mapl_bundlereadncpar calls mapl_deallocnodearray
mapl_bundlewritencpar calls mapl_deallocnodearray
mapl_cfioreadbundle calls mapl_deallocnodearray
mapl_cfiowritebundlepost calls mapl_deallocnodearray
mapl_fieldread calls mapl_deallocnodearray
mapl_fieldreadncpar calls mapl_deallocnodearray
mapl_fieldwrite calls mapl_deallocnodearray
mapl_fieldwritencpar calls mapl_deallocnodearray
mapl_locstreamcreatefromfile calls mapl_deallocnodearray
mapl_statevarread calls mapl_deallocnodearray
mapl_statevarwrite calls mapl_deallocnodearray
mapl_varread_r4_1d calls mapl_deallocnodearray
mapl_varread_r4_2d calls mapl_deallocnodearray
readrestart calls mapl_deallocnodearray
writerestart calls mapl_deallocnodearray