MAPL_ESMFStateWriteToFile – MAPL
MAPL_ESMFStateWriteToFile Subroutine
186 statements
Source File
private subroutine MAPL_ESMFStateWriteToFile(STATE, CLOCK, FILENAME, FILETYPE, MPL, HDR, write_with_oserver, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: STATE
type(ESMF_Clock), intent(in) :: CLOCK
character(len=*), intent(in) :: FILENAME
character(len=*), intent(inout) :: FILETYPE
type(MAPL_MetaComp), intent(inout) :: MPL
logical, intent(in) :: HDR
logical, intent(in), optional :: write_with_oserver
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_ESMFStateWriteToFile(STATE,CLOCK,FILENAME,FILETYPE,MPL,HDR, write_with_oserver,RC)
      type(ESMF_State),                 intent(INOUT) :: STATE
      type(ESMF_Clock),                 intent(IN   ) :: CLOCK
      character(len=*),                 intent(IN   ) :: FILENAME
      character(LEN=*),                 intent(INout) :: FILETYPE
      type(MAPL_MetaComp),              intent(INOUT) :: MPL
      logical,                          intent(IN   ) :: HDR
      logical, optional,                intent(in   ) :: write_with_oserver
      integer, optional,                intent(  OUT) :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_ESMFStateWriteToFile"
      integer                               :: status
      integer                               :: UNIT
      integer                               :: YYYY, MM, DD, H, M, S
      type(ESMF_Time)                       :: currentTime
      !    integer                               :: IM_WORLD
      !    integer                               :: JM_WORLD
      !    integer                               :: MONTH, DAY, HOUR, MINUTE
      !    integer                               :: YEAR, SECOND
      !    type (ESMF_Time)                      :: CURRENTTIME
      integer                               :: HEADER(6), DimCount
      logical                               :: AmWriter
      type(ArrDescr)                        :: ArrDes
      integer(kind=MPI_OFFSET_KIND)         :: offset
      integer                               :: info
      type(ESMF_Grid)                       :: TILEGRID
      integer                               :: COUNTS(2)
      integer                               :: io_nodes, io_rank
      integer                               :: attr
      character(len=MPI_MAX_INFO_VAL )      :: romio_cb_write
      logical                               :: nwrgt1
      !real(kind=ESMF_KIND_R8) :: itime_beg, itime_end
      !real(kind=ESMF_KIND_R8),save ::  total_time = 0.0d0
      !logical                               :: amIRoot
      !type (ESMF_VM)                        :: vm
      logical :: empty, local_write_with_oserver
      local_write_with_oserver=.false.
      if (present(write_with_oserver)) local_write_with_oserver = write_with_oserver
      ! Check if state is empty. If "yes", simply return
      empty = MAPL_IsStateEmpty(state, _RC)
      if (empty) then
         call warn_empty('Checkpoint '//trim(filename), MPL, _RC)
         _RETURN(ESMF_SUCCESS)
      end if
      ! Open file
      !----------
      !I/O
      if (index(filename,'*') /= 0) then
         !ALT: this is a special, MAPL_Write2RAM type
         filetype = 'binary'
      end if
      if (mpl%grid%num_writers == 1 .and. filetype == 'pbinary') then
         !ALT: this is a special case, we will treat the same as BINARY
         filetype = 'binary'
      end if
      ! do we have more than 1 reader or writer
      nwrgt1 = (mpl%grid%num_writers > 1)
      if (filetype == 'binary' .or. filetype == 'BINARY') then
         UNIT = GETFILE(FILENAME, form="unformatted", all_pes=.true., rc=status)
         _VERIFY(status)
      elseif(filetype=="formatted".or.filetype=="FORMATTED") then
         UNIT = GETFILE(FILENAME, form="formatted", rc=status)
         _VERIFY(status)
      elseif(filetype=='pbinary') then
         call ESMF_GridGet(MPL%GRID%ESMFGRID, dimCount=dimCount, RC=status)
         _VERIFY(status)
         AmWriter = mpl%grid%writers_comm/=MPI_COMM_NULL
         call ESMF_AttributeGet(STATE, NAME = "MAPL_GridTypeBits", VALUE=ATTR, RC=status)
         _VERIFY(status)
         TILE: if(IAND(ATTR, MAPL_AttrTile) /= 0) then
            _ASSERT(IAND(ATTR, MAPL_AttrGrid) == 0,'needs informative message') ! no hybrid allowed
            _ASSERT(MAPL_LocStreamIsAssociated(MPL%LOCSTREAM,RC=status),'needs informative message')
            call MAPL_LocStreamGet(mpl%LocStream, TILEGRID=TILEGRID, RC=status)
            _VERIFY(status)
            call MAPL_GridGet(TILEGRID, globalCellCountPerDim=COUNTS, RC=status)
            _VERIFY(status)
            call ArrDescrSet(arrdes,                   &
                 writers_comm = mpl%grid%writers_comm,&
                 iogathercomm = mpl%grid%comm )
            if(AmWriter) then
               call MPI_COMM_SIZE(mpl%grid%writers_comm, io_nodes, status)
               _VERIFY(status)
               call MPI_COMM_RANK(mpl%grid%writers_comm, io_rank, status)
               _VERIFY(status)
            endif
            call ArrDescrSet(arrdes,                   &
                 i1 = mpl%grid%i1, in = mpl%grid%in,   &
                 j1 = mpl%grid%j1, jn = mpl%grid%jn,   &
                 im_world = COUNTS(1),                 &
                 jm_world = COUNTS(2)                  )
         else
            AmWriter = mpl%grid%writers_comm/=MPI_COMM_NULL
            if (AmWriter) then
               call MPI_COMM_SIZE(mpl%grid%writers_comm, io_nodes, status)
               _VERIFY(status)
               call MPI_COMM_RANK(mpl%grid%writers_comm, io_rank, status)
               _VERIFY(status)
            endif
            call ArrDescrSet(arrdes, offset, &
                 writers_comm = mpl%grid%writers_comm,  &
                 iogathercomm = mpl%grid%iogathercomm,  &
                 i1 = mpl%grid%i1, in = mpl%grid%in,    &
                 j1 = mpl%grid%j1, jn = mpl%grid%jn,    &
                 im_world = mpl%grid%im_world,          &
                 jm_world = mpl%grid%jm_world)
         end if TILE
!@       call MPI_Barrier(mpl%grid%comm, status)
!@       _VERIFY(status)
         arrdes%offset = 0
         if (AmWriter) then
            call MPI_Info_create(info, status)
            _VERIFY(status)
            ! disable works best on GPFS but remains TBD for Lustre
            call MAPL_GetResource(MPL, romio_cb_write, Label="ROMIO_CB_WRITE:", default="disable", RC=status)
            _VERIFY(status)
            call MPI_Info_set(info, "romio_cb_write", trim(romio_cb_write), status)
            _VERIFY(status)
            if (io_rank == 0) then
               print *,'Using parallel IO for writing file: ',trim(FILENAME)
               ! make sure file exists
               call MPI_FILE_OPEN(MPI_COMM_SELF, FILENAME, MPI_MODE_WRONLY+MPI_MODE_CREATE, &
                    info, UNIT, status)
               _VERIFY(status)
               call MPI_FILE_CLOSE(UNIT, status)
               _VERIFY(status)
            end if
            call MPI_Barrier(mpl%grid%writers_comm, status)
            _VERIFY(status)
            call MPI_FILE_OPEN(mpl%grid%writers_comm, FILENAME, MPI_MODE_WRONLY, &
                 info, UNIT, status)
            _VERIFY(status)
            !$$            call MPI_Barrier(mpl%grid%writers_comm, status)
            !$$            _VERIFY(status)
         else
            UNIT=0
         endif
      else if (filetype=='pnc4') then
#ifndef H5_HAVE_PARALLEL
         if (nwrgt1) then
            print*,trim(Iam),': num_readers and number_writers must be 1 with pnc4 unless HDF5 was built with -enable-parallel'
            _FAIL('needs informative message')
         end if
#endif
         AmWriter = mpl%grid%writers_comm/=MPI_COMM_NULL
         call ESMF_AttributeGet(STATE, NAME = "MAPL_GridTypeBits", VALUE=ATTR, RC=status)
         _VERIFY(status)
         PNC4_TILE: if(IAND(ATTR, MAPL_AttrTile) /= 0) then
            _ASSERT(IAND(ATTR, MAPL_AttrGrid) == 0,'needs informative message') ! no hybrid allowed
            call ArrDescrSetNCPar(arrdes,MPL,tile=.TRUE.,num_writers=mpl%grid%num_writers,RC=status)
            _VERIFY(status)
         else
            call ArrDescrSetNCPar(arrdes,MPL,num_writers=mpl%grid%num_writers,RC=status)
            _VERIFY(status)
         end if PNC4_TILE
         arrdes%filename = trim(FILENAME)
         if (AmWriter) then
            call MPI_COMM_RANK(mpl%grid%writers_comm, io_rank, status)
            _VERIFY(status)
            if (io_rank == 0) then
               print *,'Using parallel NetCDF to write file: ',trim(FILENAME)
            end if
         endif
      else
         UNIT=0
      end if
      ! Write data
      !-----------
      if (HDR .and. filetype/='pnc4') then
         call ESMF_ClockGet (clock, currTime=currentTime, rc=status)
         _VERIFY(status)
         call ESMF_TimeGet(CurrentTime, &
              YY=YYYY, MM=MM, DD=DD, &
              H=H, M=M, S=S, rc=status)
         _VERIFY(status)
         HEADER(1) = YYYY
         HEADER(2) = MM
         HEADER(3) = DD
         HEADER(4) = H
         HEADER(5) = M
         HEADER(6) = S
         if(filetype=='pbinary' ) then
            arrdes%offset=0
            call Write_Parallel(HEADER, UNIT, ARRDES=ARRDES, RC=status)
            _VERIFY(status)
         else
            call Write_Parallel(HEADER, UNIT, RC=status)
            _VERIFY(status)
         endif
         HEADER(1) = MPL%GRID%IM_WORLD
         HEADER(2) = MPL%GRID%JM_WORLD
         HEADER(3) = MPL%GRID%LM
         HEADER(4) = 0
         HEADER(5) = 0
         if(filetype=='pbinary' ) then
            call Write_Parallel(HEADER(1:5), UNIT, ARRDES=ARRDES, RC=status)
            _VERIFY(status)
         else
            call Write_Parallel(HEADER(1:5), UNIT, RC=status)
            _VERIFY(status)
         endif
      end if
      if(filetype=='pbinary' ) then
         arrdes%ycomm = mpl%grid%Ycomm
         call MAPL_VarWrite(UNIT=UNIT, STATE=STATE, arrdes=arrdes, rc=status)
         _VERIFY(status)
         if (AmWriter) then
            !$$          call MPI_Barrier(mpl%grid%writers_comm, status)
            !$$          _VERIFY(status)
            call MPI_FILE_CLOSE(UNIT, status)
            _VERIFY(status)
            call MPI_Info_free(info, status)
            _VERIFY(status)
         endif
!@       call MPI_Barrier(mpl%grid%comm, status)
!@       _VERIFY(status)
      elseif(filetype=='pnc4') then
         !call MPI_Barrier(mpl%grid%comm, status)
         !_VERIFY(status)
         !itime_beg = MPI_Wtime()
         !_VERIFY(status)
         if (local_write_with_oserver) then
            call MAPL_VarWriteNCPar(filename,STATE,ArrDes,CLOCK, oClients=o_clients, _RC)
         else
            call MAPL_VarWriteNCPar(filename,STATE,ArrDes,CLOCK, _RC)
         end if
         !call MPI_Barrier(mpl%grid%comm, status)
         !_VERIFY(status)
         !itime_end = MPI_Wtime()
         !total_time = total_time + itime_end - itime_beg
         !_VERIFY(status)
         !call MPI_COMM_RANK(mpl%grid%comm, io_rank, status)
         !   _VERIFY(status)
         !if (io_rank == 0) then
         !   print *,'Time using writing filename: '//trim(filename), '  ', itime_end - itime_beg
         !   print *,'Total time writing checkpoint: ', total_time
         !end if
      elseif(UNIT/=0) then
         call MAPL_VarWrite(UNIT=UNIT, STATE=STATE, rc=status)
         _VERIFY(status)
         call FREE_FILE(UNIT)
      else
         status = -1  ! not yet
         _VERIFY(status)
      endif
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ESMFStateWriteToFile
Call graph
mapl_esmfstatewritetofile calls ESMF_AttributeGet, ESMF_ClockGet, ESMF_GridGet, ESMF_TimeGet, mapl_assert, mapl_getresource, mapl_varwritencpar, mapl_varwrite, write_parallel, mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_file_close, mpi_file_open, mpi_info_create, mpi_info_free, mpi_info_set, arrdescrset, arrdescrsetncpar, free_file, getfile, mapl_gridget, mapl_isstateempty, mapl_locstreamget, mapl_locstreamisassociated, mapl_return, mapl_verify, warn_empty
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize
mapl_genericrecord calls mapl_staterecord
record_component calls capture
record_state calls mapl_genericstatesave
mapl_genericwrapper calls record_component