MAPL_FieldDestroy – MAPL
MAPL_FieldDestroy Module Subroutine
49 statements
Source File
module subroutine MAPL_FieldDestroy(Field, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: Field
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_FieldDestroy
Source Code
  module subroutine MAPL_FieldDestroy(Field,RC)
    type(ESMF_Field),          intent(INOUT) :: Field
    integer, optional,         intent(OUT  ) :: RC
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_FieldDestroy"
    integer                               :: STATUS
    real(kind=ESMF_KIND_R4), pointer      :: VAR_1D(:), VAR_2D(:,:), VAR_3D(:,:,:)
    real(kind=ESMF_KIND_R8), pointer      :: VR8_1D(:), VR8_2D(:,:), VR8_3D(:,:,:)
    integer                      :: rank
    type(ESMF_TypeKind_Flag)     :: tk
    call ESMF_FieldGet(Field,typekind=tk,dimCount=rank,rc=status)
    _VERIFY(STATUS)
    if (tk == ESMF_TYPEKIND_R4 .and. rank == 1) then
       call ESMF_FieldGet(Field,0,VAR_1d,rc=status)
       _VERIFY(STATUS)
       deallocate(Var_1d,stat=status)
       _VERIFY(STATUS)
    else if (tk == ESMF_TYPEKIND_R8 .and. rank == 1) then
       call ESMF_FieldGet(Field,0,VR8_1d,rc=status)
       _VERIFY(STATUS)
       deallocate(VR8_1d,stat=status)
       _VERIFY(STATUS)
    else if (tk == ESMF_TYPEKIND_R4 .and. rank == 2) then
       call ESMF_FieldGet(Field,0,VAR_2d,rc=status)
       _VERIFY(STATUS)
       deallocate(Var_2d,stat=status)
       _VERIFY(STATUS)
    else if (tk == ESMF_TYPEKIND_R8 .and. rank == 2) then
       call ESMF_FieldGet(Field,0,VR8_2d,rc=status)
       _VERIFY(STATUS)
       deallocate(VR8_2d,stat=status)
       _VERIFY(STATUS)
    else if (tk == ESMF_TYPEKIND_R4 .and. rank == 3) then
       call ESMF_FieldGet(Field,0,VAR_3D,rc=status)
       _VERIFY(STATUS)
       deallocate(Var_3d,stat=status)
       _VERIFY(STATUS)
    else if (tk == ESMF_TYPEKIND_R8 .and. rank == 3) then
       call ESMF_FieldGet(Field,0,VR8_3D,rc=status)
       _VERIFY(STATUS)
       deallocate(VR8_3d,stat=status)
       _VERIFY(STATUS)
    else
       _FAIL( 'unsupported typekind+rank')
    end if
    call ESMF_FieldDestroy(Field,rc=status)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldDestroy
Call graph
mapl_fielddestroy calls esmf_fieldget, mapl_verify, esmf_fielddestroy, mapl_assert, mapl_return, mapl_fielddestroy
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_fieldbundledestroy calls mapl_fielddestroy, mapl_fieldbundledestroy
mapl_simplebundledestroy calls mapl_fieldbundledestroy