MAPL_CplCompSetVarSpecs – MAPL
MAPL_CplCompSetVarSpecs Subroutine
33 statements
Source File
public subroutine MAPL_CplCompSetVarSpecs(CC, SRC_SPEC, DST_SPEC, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CplComp), intent(inout) :: CC
type(MAPL_VarSpec), intent(in), target :: SRC_SPEC(:)
type(MAPL_VarSpec), intent(in), target :: DST_SPEC(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_CplCompSetVarSpecs ( CC, SRC_SPEC, DST_SPEC, RC )
    type (ESMF_CplComp  ),           intent(INOUT) :: CC
    type (MAPL_VarSpec  ), target,   intent(IN   ) :: SRC_SPEC(:)
    type (MAPL_VarSpec  ), target,   intent(IN   ) :: DST_SPEC(:)
    integer, optional,               intent(  OUT) :: RC
! ErrLog Variables
    character(len=ESMF_MAXSTR)    :: IAm
    character(len=ESMF_MAXSTR)    :: COMP_NAME
    integer                       :: STATUS
! Locals
    type (MAPL_GenericCplState), pointer :: STATE
    type (MAPL_GenericCplWrap )          :: WRAP
    character(len=ESMF_MAXSTR)           :: SRC_NAME
    character(len=ESMF_MAXSTR)           :: DST_NAME
    integer                              :: I
! Begin...
! Get this instance's name and set-up traceback handle.
! -----------------------------------------------------
    call ESMF_CplCompGet( CC, name=COMP_NAME, RC=STATUS )
    _VERIFY(STATUS)
    Iam = trim(COMP_NAME) // "MAPL_CplCompSetVarSpecs"
! Retrieve the pointer to the internal state. It comes in a wrapper.
! ------------------------------------------------------------------
    call ESMF_CplCompGetInternalState ( CC, WRAP, STATUS )
    _VERIFY(STATUS)
    STATE  =>  WRAP%INTERNAL_STATE
! Make sure the specs match
!--------------------------
    _ASSERT(size(SRC_SPEC)==size(DST_SPEC),'needs informative message')
    do I=1,size(SRC_SPEC)
       call MAPL_VarSpecGet(SRC_SPEC(I),SHORT_NAME=SRC_NAME,RC=STATUS)
       _VERIFY(STATUS)
       call MAPL_VarSpecGet(DST_SPEC(I),SHORT_NAME=DST_NAME,RC=STATUS)
       _VERIFY(STATUS)
!ALT       _ASSERT(SRC_NAME==DST_NAME,'needs informative message')
    end do
! Put miscellaneous info in the internal state
!---------------------------------------------
    STATE%SRC_SPEC => SRC_SPEC
    STATE%DST_SPEC => DST_SPEC
    STATE%ACTIVE = .true.
    STATE%NAME   = COMP_NAME
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CplCompSetVarSpecs
Call graph
mapl_cplcompsetvarspecs calls ESMF_CplCompGet, ESMF_CplCompGetInternalState, mapl_assert, mapl_varspecget, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetregular calls mapl_return
mapl_varspecgetstateptr calls mapl_return
initialize calls mapl_cplcompsetvarspecs
mapl_setvarspecforcc calls mapl_cplcompsetvarspecs
mapl_wirecomponent calls mapl_cplcompsetvarspecs
mapl_genericsetservices calls mapl_wirecomponent
setservices calls mapl_genericsetservices