MAPL_ReadTilingASCII – MAPL
MAPL_ReadTilingASCII Subroutine
45 statements
Source File
public subroutine MAPL_ReadTilingASCII(LAYOUT, FileName, GridName, NT, IM, JM, n_Grids, N_PfafCat, AVR, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout), intent(in) :: LAYOUT
character(len=*), intent(in) :: FileName
character(len=*), intent(out) :: GridName(:)
integer, intent(out) :: NT
integer, intent(out) :: IM(:)
integer, intent(out) :: JM(:)
integer, intent(out) :: n_Grids
integer, intent(out) :: N_PfafCat
real, intent(out), pointer :: AVR(:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine MAPL_ReadTilingASCII(layout, FileName, GridName, NT, im, jm, n_Grids, N_PfafCat, AVR,rc)
      type(ESMF_DELayout), intent(IN)  :: LAYOUT
      character(*),        intent(IN)  :: FileName
      character(*),        intent(out) :: GridName(:)
      integer,             intent(out) :: NT
      integer,             intent(out) :: IM(:), JM(:)
      integer,             intent(out) :: n_Grids
      integer,             intent(out) :: N_PfafCat
      real,  pointer,      intent(out) :: AVR(:,:)      ! used by GEOSgcm
      integer, optional,   intent(out) :: rc
      integer :: unit, status, hdr(2), N
      real, pointer :: AVR_Transpose(:,:)
      UNIT = GETFILE(FILENAME, form='FORMATTED', RC=status)
      _VERIFY(STATUS)
! Total number of tiles in exchange grid
!---------------------------------------
      call READ_PARALLEL(layout, hdr, UNIT=UNIT, rc=status)
       _VERIFY(STATUS)
       NT        = hdr(1)
       N_PfafCat = hdr(2)
      call READ_PARALLEL(layout, N_GRIDS, unit=UNIT, rc=status)
      _VERIFY(STATUS)
      do N = 1, N_GRIDS
         call READ_PARALLEL(layout, GridName(N), unit=UNIT, rc=status)
         _VERIFY(STATUS)
         call READ_PARALLEL(layout, IM(N), unit=UNIT, rc=status)
         _VERIFY(STATUS)
         call READ_PARALLEL(layout, JM(N), unit=UNIT, rc=status)
         _VERIFY(STATUS)
      enddo
      if(index(GridNAME(1),'EASE') /=0 ) then
          allocate(AVR(NT,9), STAT=STATUS) ! 9 columns for EASE grid
          _VERIFY(STATUS)
          allocate(AVR_transpose(9,NT))
      else
         allocate(AVR(NT,NumGlobalVars+NumLocalVars*N_GRIDS), STAT=STATUS)
         _VERIFY(STATUS)
         allocate(AVR_transpose(NumGlobalVars+NumLocalVars*N_GRIDS,NT), STAT=STATUS)
         _VERIFY(STATUS)
      endif
      call READ_PARALLEL(layout, AVR_transpose(:,:), unit=UNIT, rc=status)
      AVR = transpose(AVR_transpose)
      deallocate(AVR_transpose)
      call FREE_FILE(UNIT)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ReadTilingASCII
Call graph
mapl_readtilingascii calls read_parallel, free_file, getfile, mapl_return, mapl_verify
read_parallel calls read_parallel_i4_0, read_parallel_i4_1, read_parallel_i4_2, read_parallel_r4_0, read_parallel_r4_1, read_parallel_r4_2, read_parallel_r8_0, read_parallel_r8_1, read_parallel_r8_2, read_parallel_string_0
free_file calls mapl_return, mapl_assert
getfile calls mapl_return, mapl_verify, mapl_am_i_root, getfilemem, mapl_open
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_open calls mapl_return, mapl_verify, mapl_am_i_root
mapl_throw_exception calls initialize
read_parallel_i4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_i4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_i4_2 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_r4_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_r4_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_r4_2 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_r8_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_r8_1 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_r8_2 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
read_parallel_string_0 calls mapl_return, mapl_verify, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek
mapl_locstreamcreatefromfile calls mapl_readtilingascii
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
initialize_ calls mapl_locstreamcreate
initialize calls mapl_locstreamcreate