MAPL_DeAllocNodeArray_4DR4 – MAPL
MAPL_DeAllocNodeArray_4DR4 Module Procedure
13 statements
Source File
module procedure MAPL_DeAllocNodeArray_4DR4 module subroutine MAPL_DeAllocNodeArray_4DR4(Ptr, rc) Interface →
Arguments
Type Intent Optional Attributes Name
real, pointer :: Ptr(:,:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
mapl_deallocnodearray_4dr4 calls mapl_return, mapl_verify, releasesharedmemory, mapl_deallocnodearray_4dr4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
releasesharedmemory calls releasesharedmemory, mapl_return, shmdt, mapl_assert, shmctl, segs, mpi_barrier
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_deallocnodearray calls mapl_deallocnodearray_4dr4
writerestart calls mapl_deallocnodearray
mapl_statevarwrite calls mapl_deallocnodearray, mapl_fieldwrite
mapl_locstreamcreatefromfile calls mapl_deallocnodearray
mapl_statevarread calls mapl_deallocnodearray, mapl_fieldread
mapl_fieldwrite calls mapl_deallocnodearray
mapl_fieldread calls mapl_deallocnodearray
mapl_varread_r4_1d calls mapl_deallocnodearray
mapl_varread_r4_2d calls mapl_deallocnodearray
mapl_cfioreadbundle calls mapl_deallocnodearray
mapl_cfiowritebundlepost calls mapl_deallocnodearray
initialize_subclass calls mapl_deallocnodearray
add_horz_coordinates_from_file calls mapl_deallocnodearray
readrestart calls mapl_deallocnodearray
mapl_varwrite calls mapl_statevarwrite, mapl_fieldwrite
mapl_bundleread calls mapl_fieldread
mapl_varread calls mapl_statevarread, mapl_fieldread, mapl_varread_r4_1d, mapl_varread_r4_2d
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
mapl_bundlewrite calls mapl_fieldwrite
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
mapl_cfiowritebundle calls mapl_cfiowritebundlepost