MAPL_AddAttributeToFields_I4 – MAPL
MAPL_AddAttributeToFields_I4 Subroutine
41 statements
Source File
private recursive subroutine MAPL_AddAttributeToFields_I4(gc, field_name, att_name, att_val, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout), pointer :: gc
character(len=*), intent(in) :: field_name
character(len=*), intent(in) :: att_name
integer(kind=int32), intent(in) :: att_val
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine MAPL_AddAttributeToFields_I4(gc,field_name,att_name,att_val,rc)
      type(ESMF_GridComp), pointer, intent(inout) :: gc
      character(len=*), intent(in) :: field_name
      character(len=*), intent(in) :: att_name
      integer(int32), intent(in) :: att_val
      integer, optional, intent(out) :: rc
      integer :: nc,i,status
      type(MAPL_MetaComp), pointer :: state
      type(ESMF_GridComp), pointer :: child_gc
      type(ESMF_Field) :: field
      type(ESMF_StateItem_Flag) :: item_type
      type(ESMF_TypeKind_Flag) :: item_kind
      integer :: item_count
      logical :: is_present
      call MAPL_GetObjectFromGC(gc,state,_RC)
      call ESMF_StateGet(state%import_state,field_name,item_type,_RC)
      if (item_type == ESMF_STATEITEM_FIELD) then
         call ESMF_StateGet(state%import_state,field_name,field,_RC)
         call ESMF_AttributeGet(field,name=att_name,isPresent=is_Present,_RC)
         if (is_present) then
            call ESMF_AttributeGet(field,name=att_name,typekind=item_kind,itemCount=item_count,_RC)
            _ASSERT(item_kind == ESMF_TYPEKIND_I4,"attribute "//att_name//" in "//field_name//" is not I4")
            _ASSERT(item_count==1,"attribute "//att_name//" in "//field_name//" is not a scalar")
         end if
         call ESMF_AttributeSet(field,name=att_name,value=att_val,_RC)
      end if
      nc = state%get_num_children()
      do i=1,nc
         child_gc => state%get_child_gridcomp(i)
         call MAPL_AddAttributeToFields_I4(child_gc,field_name,att_name,att_val,_RC)
      enddo
      _RETURN(_SUCCESS)
   end subroutine MAPL_AddAttributeToFields_I4
Call graph
mapl_addattributetofields_i4 calls mapl_addattributetofields_i4, ESMF_AttributeGet, ESMF_AttributeSet, esmf_stateget, mapl_assert, mapl_getobjectfromgc, get_child_gridcomp, get_num_children, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_getobjectfromgc calls mapl_internalstateget
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
mapl_addattributetofields calls mapl_addattributetofields_i4
initialize_extdata calls mapl_addattributetofields
initialize_gc calls initialize_extdata