MAPL_VarSpecAddFromList – MAPL
MAPL_VarSpecAddFromList Subroutine
13 statements
Source File
private subroutine MAPL_VarSpecAddFromList(SPEC, ITEM, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), pointer :: SPEC(:)
type(MAPL_VarSpec), intent(in) :: ITEM(:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecAddFromList
Source Code
   subroutine MAPL_VarSpecAddFromList(SPEC,ITEM,RC)
      type (MAPL_VarSpec ), pointer         :: SPEC(:)
      type (MAPL_VarSpec ), intent(IN )     :: ITEM(:)
      integer, optional   , intent(OUT)     :: RC
      integer                               :: STATUS
      integer I
      do I=1,size(ITEM)
         call MAPL_VarSpecAddFromItem(SPEC,ITEM(I),RC=STATUS)
         _VERIFY(STATUS)
      enddo
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecAddFromList
Call graph
mapl_varspecaddfromlist calls mapl_return, mapl_varspecaddfromitem, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspecaddfromitem calls mapl_return, mapl_verify, mapl_varspeccreateinlist
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspeccreateinlist calls mapl_return, mapl_verify, mapl_assert, mapl_varspecgetindex
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecaddtolist calls mapl_varspecaddfromlist