MAPL_SimpleBundleRead – MAPL
MAPL_SimpleBundleRead Function
29 statements
Source File
public function MAPL_SimpleBundleRead(filename, bundle_name, Grid, Time, verbose, only_vars, expid, voting, unusable, rc) result(self)
Uses
MAPL_KeywordEnforcerMod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
character(len=*), intent(in) :: bundle_name
type(ESMF_Grid), intent(in) :: Grid
type(ESMF_Time), intent(inout) :: Time
logical, intent(in), optional :: verbose
character(len=*), intent(in), optional :: only_vars
character(len=*), intent(in), optional :: expid
logical, intent(in), optional :: voting
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(MAPL_SimpleBundle)
Calls
Contents
Source Code
MAPL_SimpleBundleRead
Source Code
  Function MAPL_SimpleBundleRead (filename, bundle_name, grid, time, verbose, &
                                  only_vars, expid, voting, unusable, rc ) result (self)
         use mapl_KeywordEnforcerMod
! !ARGUMENTS:
    type(MAPL_SimpleBundle)                    :: self ! Simple Bundle
    character(len=*),            intent(in)    :: filename
    character(len=*),            intent(in)    :: bundle_name
    type(ESMF_Time),             intent(inout) :: Time
    type(ESMF_Grid),             intent(in)    :: Grid
    logical, OPTIONAL,           intent(in)    :: verbose
    character(len=*), optional,  intent(IN)    :: only_vars
    character(len=*), optional,  intent(IN)    :: expid
    class(KeywordEnforcer), optional, intent(in) :: unusable
    logical,          optional,  intent(in)    :: voting
    integer, OPTIONAL,           intent(out)   :: rc
!  !DESCRIPTION:
!
!   Given an ESMF Config object and a filename, reads the corresponding file into
!    a MAPL SimpleBundle.
!
!EOP
!-----------------------------------------------------------------------------
    integer :: status
    type(ESMF_FieldBundle),  pointer :: Bundle
    allocate(Bundle, stat=STATUS)
    _VERIFY(STATUS)
    Bundle = ESMF_FieldBundleCreate ( name=bundle_name, _RC )
    call ESMF_FieldBundleSet ( bundle, grid=Grid, _RC )
    call MAPL_CFIORead  ( filename, Time, Bundle, verbose=verbose, &
                          ONLY_VARS=only_vars, expid=expid, voting=voting, _RC )
    self = MAPL_SimpleBundleCreate ( Bundle, _RC )
    self%bundleAlloc = .true.
    _RETURN(_SUCCESS)
  end function MAPL_SimpleBundleRead
Call graph
mapl_simplebundleread calls mapl_verify, mapl_simplebundlecreate, esmf_fieldbundlecreate, mapl_cfioread, esmf_fieldbundleset, mapl_return
mapl_verify calls mapl_throw_exception
mapl_simplebundlecreate calls mapl_simplebundlecreateempty, mapl_simplebundlecreatefrombundle, mapl_simplebundlecreatefromstate
mapl_cfioread calls mapl_cfioreadstate, mapl_cfioreadbundle, mapl_cfioreadarray3d, mapl_cfioreadfield, mapl_cfioreadarray2d
mapl_return calls mapl_throw_exception, get_error_message