MAPL_ConfigCreate – MAPL
MAPL_ConfigCreate Function
21 statements
Source File
public function MAPL_ConfigCreate(unusable, rc) result(config)
Uses
MAPL_KeywordEnforcerMod
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Config)
Calls
Called by
Source Code
   function MAPL_ConfigCreate(unusable, rc) result(config)
      use MAPL_KeywordEnforcerMod
      type (ESMF_Config) :: config
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character, parameter :: EOB = achar(00)   !! end of buffer mark (null)
#if defined(__NAG_COMPILER_BUILD) && defined(__DARWIN)
      character, parameter :: EOL = achar(12)   !! end of line mark (cr)
#else
      character, parameter :: EOL = achar(10)   !! end of line mark (newline)
#endif
      character, parameter :: NUL = achar(00)   !! what it says
      config = ESMF_ConfigCreate(rc=rc)
      config%cptr%buffer(1:1) = EOL
      config%cptr%buffer(2:2) = EOB
      config%cptr%nbuf = 2
      config%cptr%next_line = 1
      config%cptr%value_begin = 1
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function MAPL_ConfigCreate
Call graph
mapl_configcreate calls ESMF_ConfigCreate, buffer, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
addgrid calls mapl_configcreate
create_cf calls mapl_configcreate
create_output_grid calls mapl_configcreate
initialize_from_esmf_distgrid calls mapl_configcreate
mapl_extdatagridchangelev calls mapl_configcreate
test_setattribute_string calls mapl_configcreate
create_grid calls create_cf
createfilelevbracket calls mapl_extdatagridchangelev
initialize calls addgrid
time_ave calls create_output_grid
ut_regridding calls create_cf
create_bracketing_fields calls createfilelevbracket
initialize_ calls createfilelevbracket
process_command_line calls create_grid
main calls process_command_line
run_ calls create_bracketing_fields