MAPL_ProvidedServiceGet – MAPL
MAPL_ProvidedServiceGet Subroutine
12 statements
Source File
private subroutine MAPL_ProvidedServiceGet(GC, provided_services, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(providedServiceItemVector), pointer :: provided_services
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_ProvidedServiceGet
Source Code
   subroutine MAPL_ProvidedServiceGet(gc, provided_services, rc)
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      type(ProvidedServiceItemVector), pointer :: provided_services
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      integer :: status
      type (MAPL_MetaComp), pointer     :: MAPLOBJ
      !get MAPL
      call MAPL_InternalStateRetrieve ( GC, MAPLOBJ, RC=status )
      _VERIFY(status)
      provided_services => maplobj%provided_services
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ProvidedServiceGet
Call graph
mapl_providedserviceget calls mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
initialize calls initialize_global_time_profiler