MAPL_IsFieldAllocated – MAPL
MAPL_IsFieldAllocated Function
64 statements
Source File
private function MAPL_IsFieldAllocated(FIELD, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
integer, intent(out), optional :: RC
Return Value logical
Calls
Contents
Source Code
MAPL_IsFieldAllocated
Source Code
   logical function MAPL_IsFieldAllocated(FIELD, RC)
      ! !ARGUMENTS:
      type(ESMF_Field),    intent(INout) :: FIELD  ! Field
      integer, optional,   intent(  OUT) :: RC     ! Error code:
      ! !DESCRIPTION:  Shortcut for checking that field is allocated
      !EOPI
      ! ErrLog Variables
      character(len=ESMF_MAXSTR), parameter :: IAm='MAPL_IsFieldAllocated'
      integer                               :: status
      real(kind=REAL32), dimension(:)        , pointer :: r4d1
      real(kind=REAL32), dimension(:,:)      , pointer :: r4d2
      real(kind=REAL32), dimension(:,:,:)    , pointer :: r4d3
      real(kind=REAL32), dimension(:,:,:,:)  , pointer :: r4d4
      type(ESMF_Array)                        :: array
      type(ESMF_TypeKind_Flag)                :: tk
      integer                                 :: rank
      type(ESMF_FieldStatus_Flag)             :: fieldStatus
      call ESMF_FieldGet(field, status=fieldStatus, rc=status)
      _VERIFY(status)
      if(fieldStatus /= ESMF_FIELDstatus_COMPLETE) then
         MAPL_IsFieldAllocated = .false.
      else
         call ESMF_FieldGet (FIELD, Array=ARRAY, RC=status)
         _VERIFY(status)
         MAPL_IsFieldAllocated = .true.
         call ESMF_ArrayGet(array, typekind=tk, rank=rank, rc=status)
         if (tk .eq. ESMF_TYPEKIND_R4) then
            if (rank .eq. 1) then
               call ESMF_ArrayGet(array, localDE=0, farrayptr=r4d1, rc=status)
               _VERIFY(status)
               if (.not. associated(r4d1)) then
                  MAPL_IsFieldAllocated = .false.
                  _RETURN(ESMF_SUCCESS)
               endif
            else if (rank .eq. 2) then
               call ESMF_ArrayGet(array, localDE=0, farrayptr=r4d2, rc=status)
               _VERIFY(status)
               if (.not. associated(r4d2)) then
                  MAPL_IsFieldAllocated = .false.
                  _RETURN(ESMF_SUCCESS)
               endif
            else if (rank .eq. 3) then
               call ESMF_ArrayGet(array, localDE=0, farrayptr=r4d3, rc=status)
               _VERIFY(status)
               if (.not. associated(r4d3)) then
                  MAPL_IsFieldAllocated = .false.
                  _RETURN(ESMF_SUCCESS)
               endif
            else if (rank .eq. 4) then
               call ESMF_ArrayGet(array, localDE=0, farrayptr=r4d4, rc=status)
               _VERIFY(status)
               if (.not. associated(r4d4)) then
                  MAPL_IsFieldAllocated = .false.
                  _RETURN(ESMF_SUCCESS)
               endif
            else
               _RETURN(ESMF_FAILURE)
            end if
         end if
      end if
      _RETURN(ESMF_SUCCESS)
   end function MAPL_IsFieldAllocated
Call graph
mapl_isfieldallocated calls esmf_fieldget, mapl_verify, esmf_arrayget, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize