MAPL_LatLonGridCreate – MAPL
MAPL_LatLonGridCreate Module Function
164 statements
Source File
module function MAPL_LatLonGridCreate(Name, VM, Config, ConfigFile, Nx, Ny, IM_World, BegLon, DelLon, JM_World, BegLat, DelLat, LM_World, rc) result(Grid) Interface →
Uses
MAPL_Constants
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: Name
type(ESMF_VM), intent(in), optional, target :: VM
type(ESMF_Config), intent(in), optional, target :: Config
character(len=*), intent(in), optional :: ConfigFile
integer, intent(in), optional :: Nx
integer, intent(in), optional :: Ny
integer, intent(in), optional :: IM_World
real, intent(in), optional :: BegLon
real, intent(in), optional :: DelLon
integer, intent(in), optional :: JM_World
real, intent(in), optional :: BegLat
real, intent(in), optional :: DelLat
integer, intent(in), optional :: LM_World
integer, intent(out), optional :: rc
Return Value type(ESMF_Grid)
Calls
Called by
Contents
Source Code
MAPL_LatLonGridCreate
Source Code
  module function MAPL_LatLonGridCreate (Name, vm,                 &
       Config, ConfigFile,       &
       Nx, Ny,                   &
       IM_World, BegLon, DelLon, &
       JM_World, BegLat, DelLat, &
       LM_World,                 &
       rc)                       &
       result(Grid)
    ! !INPUT PARAMETERS:
    character(len=*),            intent(in)  :: Name
    type (ESMF_VM),    OPTIONAL, target,     &
         intent(in)  :: VM
    !   There are 3 possibilities to provide the coordinate information:
    ! 1) Thru Config object:
    type(ESMF_Config), OPTIONAL, target,     &
         intent(in)  :: Config
    ! 2) Thru a resource file:
    character(len=*),  OPTIONAL, intent(in)  :: ConfigFile
    ! 3) Thru argument list:
    integer,           OPTIONAL, intent(in)  :: Nx, Ny          ! Layout
    integer,           OPTIONAL, intent(in)  :: IM_World        ! Zonal
    real,              OPTIONAL, intent(in)  :: BegLon, DelLon  ! in degrees
    integer,           OPTIONAL, intent(in)  :: JM_World        ! Meridional
    real,              OPTIONAL, intent(in)  :: BegLat, DelLat  ! in degrees
    integer,           OPTIONAL, intent(in)  :: LM_World        ! Vertical
    ! !OUTPUT PARAMETERS:
    type (ESMF_Grid)                         :: Grid  ! Distributed grid
    integer,           OPTIONAL, intent(out) :: rc    ! return code
#ifdef ___PROTEX___
    !DESCRIPTION:
    This routine creates a distributed ESMF grid where the horizontal
    coordinates are regular longitudes and latitudes. The grid is
    created on the user specified {\bf VM}, or on the current VM if the user
    does not specify one. The layout and the coordinate information can
    be provided with a {\tt ESMF\_Config attribute}, a resource file name
    or specified through the argument list.
    \subsubsection*{Using resource files}
    The {\bf resource file} {\tt ConfigFile} has a syntax similar to a GrADS
    control file.  Here is an example defining a typical GEOS-5 1x1.25
    grid with 72 layers:
    %
    \begin{verbatim}
    GDEF: LatLon
    IDEF: 32
    JDEF: 16
    LDEF:  1
    XDEF: 288 LINEAR -180. 1.25
    YDEF: 181 LINEAR -90. 1.
    ZDEF:  72 LINEAR 1 1
    \end{verbatim}
    %
    More generally,
    \begin{verbatim}
    GDEF: LatLon
    IDEF: Nx
    JDEF: Ny
    LDEF: Nz
    XDEF: IM_World XCoordType BegLon, DelLon
    YDEF: JM_World YCoordType BegLat, DelLat
    ZDEF: LM_World ZCoordType 1        1
    \end{verbatim}
    The attribute {\bf GDEF} must always be {\tt LatLon} for  Lat/Lon grids.
    The remaining parameters are:
    \bd
    \item[Nx] is the number of processors used to decompose the X dimension
    \item[Ny] is the number of processors used to decompose the Y dimension
    \item[Nz] is the number of processors used to decompose the Z dimension;
    must be 1 for now.
    \item[IM\_World] is the number of longitudinal grid points; if {\tt IM\_World=0} then the
    grid has no zonal dimension.
    \item[XCoordType] must be set to LINEAR
    \item[BegLon] is the longitude (in degrees) of the {\em center} of the first
    gridbox
    \item[DelLon] is the constant mesh size (in degrees); if {\tt DelLon<1} then a
    global grid is assumed.
    %
    \item[JM\_World] is the number of meridional grid points if {\tt JM\_World=0} then
    the grid has no meridional dimension.
    \item[YCoordType] must be set to LINEAR
    \item[BegLat] is the latitude (in degrees) of the {\em center} of the first
    gridbox
    \item[DelLat] is the constant mesh size (in degrees); if {\tt DelLat<1} then a
    global grid is assumed.
    %
    \item[LM\_World] is the number of vertical grid points;     if {\tt LM\_World=0} then the
    grid has no vertical dimension.
    \ed
    As of this writing, only the size of the vertical grid ({\tt LM\_World})
    needs to be specified.
    \subsubsection*{Passing an ESMF Config}
    The {\bf ESMF\_Config} object {\tt Config}, when specified, must
    contain the same information as the resource file above.
    subsubsection*{Providing parameters explicitly through the argument list}
    Alternatively, one can specify coordinate information in the argument
    list; their units and meaning is as in the resource file above. In
    this case you must specify at least {\tt Nx, Ny, IM\_World, JM\_World,} and
    {\tt LM\_World}. The other parameters have default values
    \bd
    \item[BegLon] defaults to -180. (the date line)
    \item[DelLon] defaults to -1. (meaning a global grid)
    \item[BegLat] defaults to -90. (the south pole)
    \item[DelLat] deaults to -1. (meaning a global grid)
    \ed
    \subsubsection*{Restrictions}
    The current implementation imposes the following
    restrictions:
    \begin{enumerate}
    \item Only uniform longitude/latitude grids are supported (no Gaussian grids).
    \item Only 2D Lon-Lat or 3D Lon-Lat-Lev grids are currently supported
    (no Lat-Lev or Lon-Lev grids supprted yet).
    \item No vertical decomposition yet ({\tt Nz=1}).
    \end{enumerate}
    \subsubsection*{Future enhancements}
    The {\tt IDEF/JDEF/LDEF} records in the resource file should be
    extended as to allow specification of a more general distribution.
    For consistency with the {\tt XDEF/YDEF/ZDEF} records a similar
    syntax could be adopted. For example,
    %
    \begin{verbatim}
    IDEF 4   LEVELS  22 50 50 22
    XDEF 144 LINEAR -180 2.5
    \end{verbatim}
    would indicate that longitudes would be decomposed in 4 PETs,
    with the first PET having 22 grid points, the second 50 gridpoints,
    and so on.
#endif
    !
    !EOP
    !                                 ------
    !   Internal version of the input arguments
    !   ---------------------------------------
    type(ESMF_Config), pointer :: Config_
    integer           :: IM_World_
    real(kind=REAL64) :: BegLon_
    real(kind=REAL64) :: DelLon_
    integer           :: JM_World_
    real(kind=REAL64) :: BegLat_
    real(kind=REAL64) :: DelLat_
    integer           :: LM_World_
    integer           :: Nx_, Ny_, Nz_
    integer, allocatable            :: IMs(:), JMs(:), LMs(:)
    real(ESMF_KIND_R8)              :: minCoord(3)
    real(ESMF_KIND_R8)              :: deltaX, deltaY
    type (ESMF_VM), pointer         :: VM_
    integer                         :: I, J, I1, IN, J1, JN
    real(ESMF_KIND_R8), pointer     :: centerX(:,:)
    real(ESMF_KIND_R8), pointer     :: centerY(:,:)
    real(ESMF_KIND_R8), allocatable :: cornerX(:)
    real(ESMF_KIND_R8), allocatable :: cornerY(:)
    real                            :: FirstOut(2)
    real                            :: LastOut(2)
    integer                         :: STATUS
    !                                ------
    !  Defaults
    !  --------
    BegLon_ = -180.0  ! centered at date line
    DelLon_ =   -1.0  ! means global grid
    BegLat_ =  -90.0  ! centered at south pole
    DelLat_ =   -1.0  ! means global grid
    Nz_     =  1      ! place holder for now
    !  Either user specified VM or current one
    !  ---------------------------------------
    if ( present(vm) ) then
       vm_ => vm
    else
       allocate(vm_, stat=STATUS)
       _VERIFY(STATUS)
       call ESMF_VMGetCurrent(vm_, rc=STATUS)
       _VERIFY(STATUS)
    end if
    ! Grid info via resources
    ! -----------------------
    if ( present(Config) .or. present(ConfigFile) ) then
       !    Either use supplied Config or load resource file
       !    ------------------------------------------------
       if ( present(ConfigFile) ) then
          allocate(Config_,stat=STATUS)
          _VERIFY(STATUS)
          Config_ = ESMF_ConfigCreate (rc=STATUS )
          _VERIFY(STATUS)
          call ESMF_ConfigLoadFile (Config_, ConfigFile, rc=STATUS )
          _VERIFY(STATUS)
       else if ( present(Config) ) then
          Config_ => Config
       else
          STATUS = 100
          _VERIFY(STATUS)
       end if
       !    Get relevant parameters from Config
       !    -----------------------------------
       call parseConfig_()                            ! internal routine
       !  Grid info thru argument list
       !  ----------------------------
    else if ( present(IM_World) .AND. &
         present(JM_World) .AND. &
         present(LM_World) .AND. &
         present(Nx)       .AND. &
         present(Ny)             ) then
       IM_World_ = IM_World
       JM_World_ = JM_World
       LM_World_ = LM_World
       Nx_ = Nx
       Ny_ = Ny
       if ( present(BegLon) ) BegLon_ = BegLon
       if ( present(DelLon) ) DelLon_ = DelLon
       if ( present(BegLat) ) BegLat_ = BegLat
       if ( present(DelLat) ) DelLat_ = DelLat
       continue  ! all is well
       !  Something is missing
       !  --------------------
    else
       STATUS = 300
       _VERIFY(STATUS)
    end if
    !  Global grids
    !  ------------
    if ( IM_World_ < 1 .OR. JM_World_ < 1 ) then
       STATUS = 400
       _VERIFY(STATUS)
    end if
    if ( DelLon_ < 0.0 ) then  ! convention for global grids
       if ( IM_World_ == 1 ) then
          DelLon_ = 0.0
       else
          DelLon_ = 360.d0 / IM_World_
       end if
    end if
    if ( DelLat_ < 0.0 ) then  ! convention for global grids
       if ( JM_World_ == 1 ) then
          DelLat_ = 0.0
       else
          DelLat_ = 180.d0 / ( JM_World_ - 1)
       end if
    end if
    !  Give the IMs, JMs and LMs the MAPL default distribution
    !  -------------------------------------------------------
    allocate( IMs(0:Nx_-1), JMs(0:Ny_-1), LMs(0:Nz_-1), stat=STATUS)
    _VERIFY(STATUS)
    call MAPL_DecomposeDim ( IM_World_, IMs, Nx_ )
    call MAPL_DecomposeDim ( JM_World_, JMs, Ny_ )
    call MAPL_DecomposeDim ( LM_World_, LMs, Nz_ )
    !  ------------------------------------------------------------
    !  TO DO: implement IMs/JMs/LMs as part of the IDEF/JDEF record
    !         our thru command line
    !  ------------------------------------------------------------
    !  3D Lat-Lon-Lev Grid
    !  -------------------
    if ( LM_World_>0 .AND. IM_World_>0 .AND. JM_World_>0 ) then
       !ALT creat actually 2-d grid the SAME way MAPL_GridCreate
#if 0
       Grid = ESMF_GridCreateShapeTile (     &
            name=Name,                     &
            countsPerDEDim1=IMs,           &
            countsPerDEDim2=JMs,           &
            countsPerDEDim3=LMs,           &
            coordDep1 = (/1,2/),           &
            coordDep2 = (/1,2/),           &
            coordDep3 = (/3/),             &
            gridEdgeLWidth = (/0,0,0/),    &
            gridEdgeUWidth = (/0,0,0/),    &
            rc=STATUS)
       _VERIFY(STATUS)
#else
       Grid = ESMF_GridCreate(             &
            name=Name,                     &
            countsPerDEDim1=IMs,           &
            countsPerDEDim2=JMs,           &
            indexFlag = ESMF_INDEX_DELOCAL,&
            gridEdgeLWidth = (/0,0/),      &
            gridEdgeUWidth = (/0,0/),      &
            coordDep1 = (/1,2/),           &
            coordDep2 = (/1,2/),           &
            rc=status)
       _VERIFY(STATUS)
       call ESMF_AttributeSet(grid, name='GRID_LM', value=LM_World, rc=status)
       _VERIFY(STATUS)
#endif
       !  2D Lat-Lon Grid
       !  ---------------
    else if ( LM_World_==0 .AND. IM_World_>0 .AND. JM_World>0 ) then
       Grid = ESMF_GridCreate(             &
            name=Name,                     &
            countsPerDEDim1=IMs,           &
            countsPerDEDim2=JMs,           &
            coordDep1 = (/1,2/),           &
            coordDep2 = (/1,2/),           &
            gridEdgeLWidth = (/0,0/),      &
            gridEdgeUWidth = (/0,0/),      &
            rc=STATUS)
       _VERIFY(STATUS)
       !  Other possibilities not implemented yet
       !  ---------------------------------------
    else
       STATUS = 300
       _VERIFY(STATUS)
    endif
    !  -------------------------------------------------------------------
    !  NOTE: In the remaining part of this routine it is assumed that the
    !        1st and 2nd axes correspond to lat/lon; revise this for other
    !        arrangements (say, YZ grids)
    !  -------------------------------------------------------------------
    !  Allocate coords at default stagger location
    !  -------------------------------------------
    call ESMF_GridAddCoord(Grid, rc=status)
    _VERIFY(STATUS)
    !  Compute the coordinates (the corner/center is for backward compatibility)
    !  -------------------------------------------------------------------------
    deltaX      = MAPL_DEGREES_TO_RADIANS_R8 * DelLon_
    deltaY      = MAPL_DEGREES_TO_RADIANS_R8 * DelLat_
    minCoord(1) = MAPL_DEGREES_TO_RADIANS_R8 * BegLon_ - deltaX/2
    minCoord(2) = MAPL_DEGREES_TO_RADIANS_R8 * BegLat_ - deltaY/2
    allocate(cornerX(IM_World_+1),cornerY(JM_World_+1), stat=STATUS)
    _VERIFY(STATUS)
    cornerX(1) = minCoord(1)
    do i = 1,IM_World_
       cornerX(i+1) = cornerX(1) + deltaX * i
    enddo
    cornerY(1) = minCoord(2)
    do j = 1,JM_World_
       cornerY(j+1) = cornerY(1) + deltaY * j
    enddo
    !  Retrieve the coordinates so we can set them
    !  -------------------------------------------
    call ESMF_GridGetCoord (Grid, coordDim=1, localDE=0, &
         staggerloc=ESMF_STAGGERLOC_CENTER, &
         farrayPtr=centerX, rc=status)
    _VERIFY(STATUS)
    call ESMF_GridGetCoord (Grid, coordDim=2, localDE=0, &
         staggerloc=ESMF_STAGGERLOC_CENTER, &
         farrayPtr=centerY, rc=status)
    _VERIFY(STATUS)
    FirstOut(1)=BegLon_
    FirstOut(2)=-90.
    LastOut(1)=360.+BegLon_ - 360./im_world_
    LastOut(2)=90.
    block
      use MAPL_Constants, only: MAPL_DEGREES_TO_RADIANS_R8
      real(kind=REAL64), allocatable :: lons(:)
      real(kind=REAL64), allocatable :: lats(:)
      lons = MAPL_Range(FirstOut(1), LastOut(1), im_world_, &
           & conversion_factor=MAPL_DEGREES_TO_RADIANS_R8)
      lats = MAPL_Range(FirstOut(2), LastOut(2), JM_WORLD, &
           & conversion_factor=MAPL_DEGREES_TO_RADIANS_R8)
      call MAPL_GRID_INTERIOR(grid, i1, in, j1, jn)
      do i = 1,size(centerX,1)
         centerX(I,:) = lons(i1+i-1)
      end do
      do j = 1,size(centerY,2)
         centerY(:,J) = lats(j1+j-1)
      enddo
    end block
    !  Make sure we've got it right
    !  ----------------------------
    call ESMF_GridValidate(Grid,rc=status)
    _VERIFY(STATUS)
    !  Clean up
    !  --------
    deallocate(cornerY,cornerX)
    deallocate(IMs,JMs,LMs)
    if ( present(ConfigFile) ) deallocate(Config_)
    if ( .not. present(vm) )   deallocate(vm_)
    !  All Done
    !  --------
    _RETURN(STATUS)
  Contains
    subroutine parseConfig_()
      !
      !    Internal routine to parse the ESMF_Config.
      !
      STATUS = 200     ! not implemented yet
      _VERIFY(STATUS)
    end subroutine parseConfig_
  end function MAPL_LatLonGridCreate
Call graph
mapl_latlongridcreate calls mapl_return, mapl_verify, esmf_vmgetcurrent, mapl_decomposedim, esmf_configloadfile, esmf_configcreate, esmf_gridcreate, esmf_attributeset, esmf_gridaddcoord, esmf_gridgetcoord, lons, lats, mapl_range, mapl_grid_interior, esmf_gridvalidate, mapl_latlongridcreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_decomposedim calls mapl_decomposedim
mapl_range calls mapl_range_real32, mapl_range_real64
mapl_grid_interior calls mapl_grid_interior, esmf_gridget, esmf_distgridget, mapl_distgridget, esmf_delayoutget
mapl_range_real32 calls mapl_return, mapl_assert
mapl_range_real64 calls mapl_return, mapl_assert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_distgridget calls mapl_verify, esmf_distgridget