MAPL_DateStampGet – MAPL
MAPL_DateStampGet Subroutine
31 statements
Source File
public subroutine MAPL_DateStampGet(clock, DateStamp, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock) :: clock
character(len=*) :: DateStamp
integer, optional :: rc
Calls
Called by
Contents
Source Code
MAPL_DateStampGet
Source Code
   subroutine MAPL_DateStampGet (clock, DateStamp, rc)
      type (ESMF_Clock)                 :: clock
      character(len=*)        :: DateStamp
      integer, optional                 :: rc
      type(ESMF_Time)                   :: currentTime
      character(len=ESMF_MAXSTR)        :: TimeString
      character                         :: String(ESMF_MAXSTR)
      character(len=ESMF_MAXSTR)                  :: IAm
      integer                                     :: status
      character*4 year
      character*2 month
      character*2 day
      character*2 hour
      character*2 minute
      character*2 second
      equivalence ( string(01),TimeString )
      equivalence ( string(01),year       )
      equivalence ( string(06),month      )
      equivalence ( string(09),day        )
      equivalence ( string(12),hour       )
      equivalence ( string(15),minute     )
      equivalence ( string(18),second     )
      Iam = "MAPL_DateStampGet"
      call ESMF_ClockGet (clock, currTime=currentTime, rc=status)
      _VERIFY(status)
      call ESMF_TimeGet  (currentTime, timeString=TimeString, rc=status)
      _VERIFY(status)
      DateStamp = year // month // day // '_' // hour // minute // 'z'
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_DateStampGet
Call graph
mapl_datestampget calls esmf_clockget, mapl_verify, esmf_timeget, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
recordrestart calls mapl_datestampget
mapl_genericrecord calls mapl_datestampget
mapl_genericrefresh calls mapl_datestampget, mapl_genericrefresh
mapl_genericstatesave calls mapl_datestampget, mapl_genericstatesave
record_state calls mapl_genericstatesave