MAPL_SimpleBundlePrint – MAPL
MAPL_SimpleBundlePrint Subroutine
56 statements
Source File
public subroutine MAPL_SimpleBundlePrint(self)
Arguments
Type Intent Optional Attributes Name
type(MAPL_SimpleBundle) :: self
Calls
Contents
Source Code
MAPL_SimpleBundlePrint
Source Code
  subroutine MAPL_SimpleBundlePrint ( self )
! !ARGUMENTS:
    type(MAPL_SimpleBundle) :: self
!  !DESCRIPTION: Prints the global max/min for each variable in the
!                Simple Bundle.
!
!EOP
!-----------------------------------------------------------------------------
    integer :: i
    if ( MAPL_AM_I_ROOT() ) then
       print *
       print *, 'Simple Bundle: ', trim(self%name)
    end if
!   1-D
!   ---
    do i = 1, self%n1d
       if ( self%r1(i)%myKind == ESMF_KIND_R4 ) then
          if ( associated(self%r1(i)%qr4) ) then
             call MAPL_MaxMin(trim(self%r1(i)%name), self%r1(i)%qr4)
          else
             if (MAPL_AM_I_ROOT()) write(*,*) trim(self%r1(i)%name)//' ------    ------'
          endif
       else if ( self%r1(i)%myKind == ESMF_KIND_R8 ) then
          if ( associated(self%r1(i)%qr8) ) then
             call MAPL_MaxMin(trim(self%r1(i)%name), self%r1(i)%qr8)
          else
             if (MAPL_AM_I_ROOT()) write(*,*) trim(self%r1(i)%name)//' ------    ------'
          endif
       end if
    end do
!   2-D
!   ---
    do i = 1, self%n2d
       if ( self%r2(i)%myKind == ESMF_KIND_R4 ) then
          if ( associated(self%r2(i)%qr4) ) then
             call MAPL_MaxMin(trim(self%r2(i)%name), self%r2(i)%qr4)
          else
             if (MAPL_AM_I_ROOT()) write(*,*) trim(self%r2(i)%name)//' ------    ------'
          endif
       else if ( self%r2(i)%myKind == ESMF_KIND_R8 ) then
          if ( associated(self%r2(i)%qr8) ) then
             call MAPL_MaxMin(trim(self%r2(i)%name), self%r2(i)%qr8)
          else
             if (MAPL_AM_I_ROOT()) write(*,*) trim(self%r2(i)%name)//' ------    ------'
          endif
       end if
    end do
!   3-D
!   ---
    do i = 1, self%n3d
       if ( self%r3(i)%myKind == ESMF_KIND_R4 ) then
          if ( associated(self%r3(i)%qr4) ) then
             call MAPL_MaxMin(trim(self%r3(i)%name), self%r3(i)%qr4)
          else
             if (MAPL_AM_I_ROOT()) write(*,*) trim(self%r3(i)%name)//' ------    ------'
          endif
       else if ( self%r3(i)%myKind == ESMF_KIND_R8 ) then
          if ( associated(self%r3(i)%qr8) ) then
             call MAPL_MaxMin(trim(self%r3(i)%name), self%r3(i)%qr8)
          else
             if (MAPL_AM_I_ROOT()) write(*,*) trim(self%r3(i)%name)//' ------    ------'
          endif
       end if
    end do
    if ( MAPL_AM_I_ROOT() ) then
       print *
    end if
end subroutine MAPL_SimpleBundlePrint
Call graph
mapl_simplebundleprint calls mapl_am_i_root, mapl_maxmin
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_maxmin calls pmaxmin2d_r4, pmaxmin1d_r4, pmaxmin3d_r4, pmaxmin2d_r8, pmaxmin3d_r8, pmaxmin1d_r8
mapl_am_i_root_layout calls mapl_am_i_rank
pmaxmin2d_r4 calls mapl_am_i_root, mapl_commsallreducemax, esmf_vmgetcurrent
mapl_am_i_root_vm calls mapl_am_i_rank
pmaxmin1d_r4 calls pmaxmin2d_r4
pmaxmin3d_r4 calls pmaxmin2d_r4
pmaxmin2d_r8 calls pmaxmin2d_r4
pmaxmin3d_r8 calls pmaxmin3d_r4
pmaxmin1d_r8 calls pmaxmin1d_r4
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout
mapl_commsallreducemax calls mapl_commsallreducemax_r4_2, mapl_commsallreducemax_i4_0, mapl_commsallreducemax_r4_1, mapl_commsallreducemax_r4_0, mapl_commsallreducemax_r8_0, mapl_commsallreducemax_i4_1, mapl_commsallreducemax_r8_1, mapl_commsallreducemax_i4_2, mapl_commsallreducemax_r8_2