MAPL_AdvertiseService – MAPL
MAPL_AdvertiseService Subroutine
13 statements
Source File
public subroutine MAPL_AdvertiseService(GC, SERVICE, BUNDLE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SERVICE
character(len=*), intent(in) :: BUNDLE
integer, intent(out), optional :: RC
Calls
Source Code
   subroutine MAPL_AdvertiseService(GC, SERVICE, BUNDLE, RC)
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*),              intent(IN   ) :: SERVICE
      character (len=*),              intent(IN   ) :: BUNDLE
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      integer :: status
      type (MAPL_MetaComp), pointer     :: MAPLOBJ
      !get MAPL
      call MAPL_InternalStateRetrieve ( GC, MAPLOBJ, RC=status )
      _VERIFY(status)
      call maplobj%provided_services%push_back( &
           ProvidedServiceType( &
           SERVICE=SERVICE, &
           BUNDLE=BUNDLE))
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_AdvertiseService
Call graph
mapl_advertiseservice calls mapl_internalstateretrieve, mapl_return, mapl_verify, v_push_back
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize