MAPL_CFIOAddCollection – MAPL
MAPL_CFIOAddCollection Function
26 statements
Source File
public function MAPL_CFIOAddCollection(template) result(id)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: template
Return Value integer
Calls
Called by
Source Code
  function MAPL_CFIOAddCollection(template) result(id)
     character(len=*), intent(in) :: template
      integer :: n
      logical :: found
      type (CFIOCollectionVectorIterator) :: iter
      type (CFIOCollection), pointer :: collection
      type (CFIOCollection) :: c
      integer :: id
      iter = collections%begin()
      n = 1
      ! Is it a new collection?
      found = .false.
      do while (iter /= collections%end())
         collection => iter%get()
         if (template == collection%template) then
            found = .true.
            exit
         end if
         n = n + 1
         call iter%next()
      end do
      if (.not. found) then
         c = new_CFIOCollection(template)
         call collections%push_back(c)
      end if
      id = n
   end function MAPL_CFIOAddCollection
Call graph
mapl_cfioaddcollection calls new_cfiocollection, v_begin, v_iter_get, v_iter_next, v_push_back
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
mapl_cfioreadparallel_ calls mapl_cfioaddcollection
mapl_cfioreadparallel calls mapl_cfioreadparallel_