MAPL_GenericStateClockOn – MAPL
MAPL_GenericStateClockOn Subroutine
14 statements
Source File
private subroutine MAPL_GenericStateClockOn(STATE, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_GenericStateClockOn(STATE,NAME,RC)
      !ARGUMENTS:
      type (MAPL_MetaComp),        intent(INOUT) :: STATE
      character(len=*),            intent(IN   ) :: NAME
      integer, optional,           intent(  OUT) :: RC     ! Error code:
      !EOPI
      integer :: status
      if (trim(name) == 'TOTAL') then
         _RETURN(ESMF_SUCCESS)
      end if
      call state%t_profiler%start(get_actual_timer_name(name),_RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericStateClockOn
Call graph
mapl_genericstateclockon calls start, get_actual_timer_name, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_timeron calls mapl_genericstateclockon
append_file calls mapl_timeron
create_geosat_grid_find_mask calls mapl_timeron, create_geosat_grid_find_mask
initialize_ calls mapl_timeron, mapl_genericinitialize
initialize calls mapl_timeron, mapl_genericinitialize, create_geosat_grid_find_mask
mapl_genericfinalize calls mapl_timeron
mapl_genericinitialize calls mapl_timeron
mapl_genericrecord calls mapl_timeron
mapl_genericrefresh calls mapl_timeron, mapl_genericrefresh
mapl_genericrunchildren calls mapl_timeron
mapl_genericstaterestore calls mapl_timeron, mapl_genericstaterestore
mapl_genericwrapper calls mapl_timeron
regrid_append_file calls mapl_timeron, regrid_append_file
run_ calls mapl_timeron
run calls mapl_timeron, append_file, regrid_append_file
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
refresh_state calls mapl_genericstaterestore