MAPL_VarSpecAddRefFromItemNew – MAPL
MAPL_VarSpecAddRefFromItemNew Subroutine
44 statements
Source File
private subroutine MAPL_VarSpecAddRefFromItemNew(SPEC, ITEM, ALLOW_DUPLICATES, RC)
Arguments
Type Intent Optional Attributes Name
type(StateSpecification) :: SPEC
type(MAPL_VarSpec), intent(in) :: ITEM
logical, intent(in), optional :: ALLOW_DUPLICATES
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_VarSpecAddRefFromItemNew(SPEC, ITEM, ALLOW_DUPLICATES, RC)
    type (StateSpecification)        :: SPEC
    type (MAPL_VarSpec ), intent(IN )     :: ITEM
    logical, optional   , intent(IN)      :: ALLOW_DUPLICATES
    integer, optional   , intent(OUT)     :: RC
    integer                               :: STATUS
    integer                               :: I
    logical                               :: usableALLOW_DUPLICATES
    class(Logger), pointer :: lgr
    if(present(ALLOW_DUPLICATES)) then
       usableALLOW_DUPLICATES=ALLOW_DUPLICATES
    else
       usableALLOW_DUPLICATES=.FALSE.
    endif
    if(.not.associated(ITEM%SPECPtr)) then
       _RETURN(ESMF_FAILURE)
    endif
    if (spec%var_specs%size() > 0) then
       if (.not. usableALLOW_DUPLICATES) then
          I = MAPL_VarSpecGetIndex(SPEC%old_var_specs, ITEM, RC=STATUS)
          _VERIFY(STATUS)
          if(I /= -1) then
             if (SPEC%old_var_specs(I) == ITEM) THEN
                if(present(RC)) then
                   RC=MAPL_DuplicateEntry
                end if
                return
             else
                lgr => logging%get_logger('MAPL.GENERIC')
                call lgr%error("Duplicate SHORT_NAME %a with different attributes.", trim(ITEM%SPECPtr%short_name))
                call MAPL_VarSpecPrint(ITEM)
                call MAPL_VarSpecPrint(SPEC%old_var_specs(I))
                _RETURN(ESMF_FAILURE)
             end if
          endif
       end if
    end if
      call spec%var_specs%push_back(item)
      call spec%update_legacy()
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecAddRefFromItemNew
Call graph
mapl_varspecaddreffromitemnew calls mapl_varspecgetindex, mapl_varspecprint, get_logger, error, mapl_return, mapl_verify, update_legacy, vector_push_back
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_varspecprint calls mapl_varspecprintmany, mapl_varspecprintone
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
update_legacy calls of
vector_push_back calls resize, vector_grow_to
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecgetindexbyname calls mapl_return
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecprintmany calls mapl_varspecprint, mapl_return, mapl_verify
mapl_varspecprintone calls mapl_return, info
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew