MAPL_VarSpecSetNew – MAPL
MAPL_VarSpecSetNew Subroutine
123 statements
Source File
private subroutine MAPL_VarSpecSetNew(spec, short_name, long_name, units, dims, vlocation, field, bundle, state, stat, accmlt_interval, couple_interval, offset, label, friendlyto, field_type, staggering, rotation, grid, donotallocate, alwaysallocate, positive, rc)
Type Bound
MAPL_VarSpecType
Arguments
Type Intent Optional Attributes Name
class(MAPL_VarSpecType), intent(inout) :: spec
character(len=*), intent(in), optional :: short_name
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: units
integer, intent(in), optional :: dims
integer, intent(in), optional :: vlocation
type(ESMF_Field), intent(in), optional :: field
type(ESMF_fieldbundle), intent(in), optional :: bundle
type(ESMF_State), intent(in), optional :: state
integer, intent(in), optional :: stat
integer, intent(in), optional :: accmlt_interval
integer, intent(in), optional :: couple_interval
integer, intent(in), optional :: offset
integer, intent(in), optional :: label
character(len=*), intent(in), optional :: friendlyto
integer, intent(in), optional :: field_type
integer, intent(in), optional :: staggering
integer, intent(in), optional :: rotation
type(ESMF_Grid), intent(in), optional :: grid
logical, intent(in), optional :: donotallocate
logical, intent(in), optional :: alwaysallocate
character(len=positive_length), intent(in), optional :: positive
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_VarSpecSetNew(spec, short_name, long_name, units,       &
                             dims, vlocation, field, bundle, state,    &
                             stat, accmlt_interval, couple_interval,   &
                             offset, label,                            &
                             friendlyto,                               &
                             field_type,                               &
                             staggering,                               &
                             rotation,                                 &
                             grid,                                     &
                             donotallocate,                            &
                             alwaysallocate,                            &
                             positive,                                 &
                                                                    rc )
    class(mapl_varspectype),             intent(inout)   :: spec
    character(len=*)   , optional   , intent(in)      :: short_name
    character(len=*)   , optional   , intent(in)      :: long_name
    character(len=*)   , optional   , intent(in)      :: units
    integer            , optional   , intent(in)      :: dims
    integer            , optional   , intent(in)      :: vlocation
    integer            , optional   , intent(in)      :: accmlt_interval
    integer            , optional   , intent(in)      :: couple_interval
    integer            , optional   , intent(in)      :: offset
    integer            , optional   , intent(in)      :: stat
    integer            , optional   , intent(in)      :: label
    type(ESMF_field)   , optional   , intent(in)      :: field
    type(ESMF_fieldbundle)  , optional   , intent(in) :: bundle
    type(ESMF_state)   , optional   , intent(in)      :: state
    character(len=*)   , optional   , intent(in)      :: friendlyto
    integer            , optional   , intent(in)      :: field_type
    integer            , optional   , intent(in)      :: staggering
    integer            , optional   , intent(in)      :: rotation
    type(ESMF_grid)    , optional   , intent(in)      :: grid
    logical            , optional   , intent(in)      :: donotallocate
    logical            , optional   , intent(in)      :: alwaysallocate
    character(len=positive_length), optional, intent(in) :: positive
    integer            , optional   , intent(out)     :: rc
      if(present(short_name)) then
        spec%short_name = short_name
      endif
      if(present(long_name)) then
        spec%long_name = long_name
      endif
      if(present(units)) then
        spec%units = units
      endif
      if(present(friendlyto)) then
        spec%friendlyto = friendlyto
      endif
      if(present(stat)) then
       spec%stat=stat
      endif
      if(present(dims)) then
       spec%dims=dims
      endif
      if(present(vlocation)) then
       spec%location=vlocation
      endif
      if(present(accmlt_interval)) then
       spec%accmlt_interval=accmlt_interval
      endif
      if(present(couple_interval)) then
       spec%couple_interval=couple_interval
      endif
      if(present(offset)) then
       spec%offset=offset
      endif
      if(present(label)) then
       spec%label=label
      endif
      if(present(field)) then
       spec%field = field
      endif
      if(present(bundle)) then
       spec%bundle = bundle
      endif
      if(present(state)) then
       spec%state = state
      endif
      if(present(grid)) then
         spec%grid = grid
      endif
      if(present(field_type)) then
         spec%field_type = field_type
      endif
      if(present(staggering)) then
         spec%staggering = staggering
      endif
      if(present(rotation)) then
         spec%rotation = rotation
      endif
      if(present(donotallocate)) then
         spec%donotallocate = donotallocate
      endif
      if(present(alwaysallocate)) then
         spec%alwaysallocate = alwaysallocate
      endif
      if(present(positive)) then
         spec%positive = positive
      endif
      associate( &
           horz_spec => create_horz_stagger_spec(spec), &
           vert_spec => create_vert_stagger_spec(spec), &
           ungr_spec => create_ungridded_dim_specs(spec), &
           tk_spec => create_tk_spec(spec))
        associate( dims_spec => DimsSpec(horz_spec, vert_spec, ungr_spec, spec%halowidth))
          spec%field_spec = FieldSpec(spec%long_name, dims_spec, tk_spec)
        end associate
      end associate
      _RETURN(ESMF_SUCCESS)
   contains
      function create_horz_stagger_spec(this) result(horz_spec)
         type(HorizontalStaggerLoc) :: horz_spec
         type(MAPL_VarSpecType), intent(in) :: this
      end function create_horz_stagger_spec
      function create_vert_stagger_spec(this) result(vert_spec)
         type(VerticalStaggerLoc) :: vert_spec
         type(MAPL_VarSpecType), intent(in) :: this
      end function create_vert_stagger_spec
      function create_ungridded_dim_specs(this) result(ungr_spec)
         type(UngriddedDimSpec), allocatable :: ungr_spec(:)
         type(MAPL_VarSpecType), intent(in) :: this
      end function create_ungridded_dim_specs
      function create_tk_spec(this) result(tk_spec)
         use esmf, only: ESMF_KIND_R4, ESMF_KIND_R8
         use esmf, only: ESMF_TYPEKIND_R4, ESMF_TYPEKIND_R8
         use esmf, only: ESMF_TYPEKIND_FLAG
         type(ESMF_TypeKind_Flag) :: tk_spec
         type(MAPL_VarSpecType), intent(in) :: this
         select case (this%precision)
         case (ESMF_KIND_R4)
            tk_spec = ESMF_TYPEKIND_R4
         case (ESMF_KIND_R8)
            tk_spec = ESMF_TYPEKIND_R8
         case default
            error stop
         end select
      end function create_tk_spec
   end subroutine MAPL_VarSpecSetNew
Call graph
mapl_varspecsetnew calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_varspecset calls mapl_varspecsetnew
mapl_childaddattribtoimportspec calls mapl_varspecset
mapl_donotallocatevar calls mapl_varspecset
mapl_donotdeferexport calls mapl_varspecset
mapl_genericsetservices calls mapl_varspecset, mapl_genericspecenum, mapl_wirecomponent
mapl_genericspecenum calls mapl_varspecset, mapl_genericspecenum
mapl_stateaddexportspecfrmall calls mapl_varspecset
mapl_stateaddinternalspec calls mapl_varspecset
mapl_statecreatefromspecnew calls mapl_varspecset
mapl_statecreatefromvarspecnew calls mapl_varspecset, mapl_statecreatefromspecnew
mapl_statesetspecattrib calls mapl_varspecset
mapl_varspecreconnect calls mapl_varspecset
mapl_wirecomponent calls mapl_varspecset
mapl_addexportspec calls mapl_stateaddexportspecfrmall
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_donotallocateimport calls mapl_donotallocatevar
mapl_donotallocateinternal calls mapl_donotallocatevar
mapl_genericinitialize calls mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_readforcingx calls mapl_statecreatefromvarspecnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statesettimestamp calls mapl_statesetspecattrib
setservices calls mapl_genericsetservices