MAPL_LocStreamXformIsAssociated – MAPL
MAPL_LocStreamXformIsAssociated Function
7 statements
Source File
public function MAPL_LocStreamXformIsAssociated(Xform, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_LocStreamXform), intent(in) :: Xform
integer, intent(out), optional :: RC
Return Value logical
Calls
Source Code
  logical function MAPL_LocStreamXformIsAssociated(Xform, RC)
    type(MAPL_LocStreamXform),            intent(IN   ) :: Xform
    integer, optional,                    intent(  OUT) :: RC
    MAPL_LocStreamXformIsAssociated = associated(Xform%Ptr)
    _RETURN(ESMF_SUCCESS)
  end function MAPL_LocStreamXformIsAssociated
Call graph
mapl_locstreamxformisassociated calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize