MAPL_StateAddBundle – MAPL
MAPL_StateAddBundle Module Subroutine
47 statements
Source File
module subroutine MAPL_StateAddBundle(State, Bundle, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: State
type(ESMF_FieldBundle), intent(in) :: Bundle
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_StateAddBundle
Source Code
  module subroutine MAPL_StateAddBundle(State, Bundle, RC)
    type(ESMF_State),  intent(inout) :: State
    type(ESMF_FieldBundle),  intent(in   ) :: Bundle
    integer, optional, intent(  out) :: rc
    ! ErrLog vars
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddBundles"
    integer                               :: STATUS
    ! Local var
    character(len=ESMF_MAXSTR), parameter   :: attrName = MAPL_StateItemOrderList
    character(len=ESMF_MAXSTR)              :: name
    character(len=ESMF_MAXSTR), allocatable :: currList(:)
    character(len=ESMF_MAXSTR), allocatable :: thisList(:)
    integer                                 :: natt
    integer                                 :: na
    type(ESMF_FieldBundle)                  :: Bundles(1)
    logical                                 :: haveAttr
    bundles(1) = bundle
    call ESMF_StateAdd(state, Bundles, RC=status)
    _VERIFY(STATUS)
    ! check for attribute
    call ESMF_AttributeGet(state, NAME=attrName, isPresent=haveAttr, RC=STATUS)
    _VERIFY(STATUS)
    if (haveAttr) then
       call ESMF_AttributeGet(state, NAME=attrName, itemcount=natt, RC=STATUS)
       _VERIFY(STATUS)
    else
       natt = 0
    end if
    allocate(currList(natt), stat=status)
    _VERIFY(STATUS)
    if (natt > 0) then
       ! get the current list
       call ESMF_AttributeGet(state, NAME=attrName, VALUELIST=currList, rc=status)
       _VERIFY(STATUS)
       !ALT delete/destroy this attribute to prevent memory leaks
       call ESMF_AttributeRemove(state, NAME=attrName, rc=status)
       _VERIFY(STATUS)
    end if
    na = natt+1
    allocate(thisList(na), stat=status)
    _VERIFY(STATUS)
    thisList(1:natt) = currList
    call ESMF_FieldBundleGet(bundle, name=name, rc=status)
    _VERIFY(STATUS)
    thisList(na) = name
    call ESMF_AttributeSet(state, NAME=attrName, itemcount=na, VALUELIST=thisList, rc=status)
    _VERIFY(STATUS)
    deallocate(thisList)
    deallocate(currList)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_StateAddBundle
Call graph
mapl_stateaddbundle calls esmf_stateadd, mapl_verify, esmf_attributeget, esmf_attributeremove, esmf_fieldbundleget, esmf_attributeset, mapl_return, mapl_stateaddbundle
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_stateadd calls mapl_stateaddbundle
initialize calls mapl_stateadd
initialize_extdata calls mapl_stateadd
create_holding_field calls mapl_stateadd
initialize_ calls mapl_stateadd, create_holding_field, create_primary_field
mapl_statecreatefromspecnew calls mapl_stateadd
create_primary_field calls mapl_stateadd
initialize_gc calls mapl_stateadd
bundle2state calls mapl_stateadd
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
esmfl_bundle2state calls bundle2state
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew