MAPL_GetHorzIJIndex – MAPL
MAPL_GetHorzIJIndex Module Subroutine
156 statements
Source File
module subroutine MAPL_GetHorzIJIndex(npts, II, JJ, lon, lat, lonR8, latR8, Grid, rc) Interface →
MAPL_GetHorzIJIndex – Get indexes on destributed ESMF grid for an arbitary lat and lon
For a set of longitudes and latitudes in radians this routine will return the indexes for the domain Depending on how it is invoked these will be the local domain or the global indices. If the Lat/Lon pair is not in the domain -1 is returned. The routine works for both the gmao cube and lat/lon grids. Currently the lat/lon grid is asumed to go from -180 to 180
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npts
number of points in lat and lon arrays
integer, intent(inout) :: II(npts)
array of the first index for each lat and lon
integer, intent(inout) :: JJ(npts)
array of the second index for each lat and lon
real, intent(in), optional :: lon(npts)
array of longitudes in radians
real, intent(in), optional :: lat(npts)
array of latitudes in radians
real(kind=ESMF_KIND_R8), intent(in), optional :: lonR8(npts)
array of longitudes in radians
real(kind=ESMF_KIND_R8), intent(in), optional :: latR8(npts)
array of latitudes in radians
type(ESMF_Grid), intent(inout), optional :: Grid
ESMF grid
integer, intent(out), optional :: rc
return code
Calls
Called by
Source Code
  module subroutine MAPL_GetHorzIJIndex(npts,II,JJ,lon,lat,lonR8,latR8,Grid, rc)
    implicit none
    !ARGUMENTS:
    integer,                      intent(in   ) :: npts        !! number of points in lat and lon arrays
    integer,                      intent(inout) :: II(npts)    !! array of the first index for each lat and lon
    integer,                      intent(inout) :: JJ(npts)    !! array of the second index for each lat and lon
    real, optional,               intent(in   ) :: lon(npts)   !! array of longitudes in radians
    real, optional,               intent(in   ) :: lat(npts)   !! array of latitudes in radians
    real(ESMF_KIND_R8), optional, intent(in   ) :: lonR8(npts) !! array of longitudes in radians
    real(ESMF_KIND_R8), optional, intent(in   ) :: latR8(npts) !! array of latitudes in radians
    type(ESMF_Grid),    optional, intent(inout) :: Grid        !! ESMF grid
    integer,            optional, intent(out  ) :: rc          !! return code
    integer                    :: status
    integer                         :: IM_World, JM_World, dims(3)
    integer                         :: IM, JM, counts(3)
    real(ESMF_KIND_R8), pointer     :: lons(:,:)
    real(ESMF_KIND_R8), pointer     :: lats(:,:)
    real(ESMF_KIND_R8), allocatable :: elons(:)
    real(ESMF_KIND_R8), allocatable :: elats(:)
    integer :: i,iiloc,jjloc
    real(ESMF_KIND_R4) :: lonloc,latloc
    logical                 :: localSearch
    real(ESMF_KIND_R8), allocatable :: target_lons(:),target_lats(:)
    real(ESMF_KIND_R8), allocatable :: corner_lons(:,:),corner_lats(:,:),center_lats(:,:),center_lons(:,:)
    type(ESMF_CoordSys_Flag) :: coordSys
    character(len=ESMF_MAXSTR) :: grid_type
    ! if the grid is present then we can just get the prestored edges and the dimensions of the grid
    ! this also means we are running on a distributed grid
    ! if grid not present then the we just be running outside of ESMF and the user must
    ! pass in the the dimensions of the grid and we must compute them
    ! and assume search on the global domain
    if (present(Grid)) then
       call MAPL_GridGet(grid, localCellCountPerDim=counts,globalCellCountPerDim=dims,_RC)
       IM_World = dims(1)
       JM_World = dims(2)
       IM = counts(1)
       JM = counts(2)
       localSearch = .true.
    else
       localSearch = .false.
    end if
    allocate(target_lons(npts),target_lats(npts))
    if (present(lon) .and. present(lat)) then
       target_lons = lon
       target_lats = lat
    else if (present(lonR8) .and. present(latR8)) then
       target_lons = lonR8
       target_lats = latR8
    end if
    _ASSERT(localSearch,"Global Search for IJ not implemented")
!AOO change tusing GridType atribute    if (im_world*6==jm_world) then
    call ESMF_AttributeGet(grid, name='GridType', value=grid_type, _RC)
    if(trim(grid_type) == "Cubed-Sphere") then
       call ESMF_GridGetCoord(grid,coordDim=1, localDe=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, fArrayPtr = lons, _RC)
       call ESMF_GridGetCoord(grid,coordDim=2, localDe=0, &
            staggerloc=ESMF_STAGGERLOC_CENTER, fArrayPtr = lats, _RC)
       call ESMF_GridGet(grid,coordSys=coordSys,_RC)
       allocate(corner_lons(im+1,jm+1))
       allocate(corner_lats(im+1,jm+1))
       allocate(center_lons(im,jm),center_lats(im,jm))
       if (coordSys==ESMF_COORDSYS_SPH_DEG) then
          center_lons=lons*MAPL_DEGREES_TO_RADIANS_R8
          center_lats=lats*MAPL_DEGREES_TO_RADIANS_R8
       else if (coordSys==ESMF_COORDSYS_SPH_RAD) then
          center_lons=lons
          center_lats=lats
       else if (coordSys==ESMF_COORDSYS_CART) then
          _FAIL('Unsupported coordinate system:  ESMF_COORDSYS_CART')
       end if
       call MAPL_GridGetCorners(Grid,corner_lons,corner_lats,_RC)
       ii=-1
       jj=-1
       call get_points_in_spherical_domain(center_lons,center_lats,corner_lons,corner_lats,target_lons,target_lats,ii,jj,_RC)
       deallocate(corner_lons,corner_lats, center_lons,center_lats)
    else
       if (localSearch) then
          call ESMF_GridGetCoord(grid,coordDim=1, localDe=0, &
               staggerloc=ESMF_STAGGERLOC_CORNER, fArrayPtr = lons, _RC)
          call ESMF_GridGetCoord(grid,coordDim=2, localDe=0, &
               staggerloc=ESMF_STAGGERLOC_CORNER, fArrayPtr = lats, _RC)
       else
          _FAIL('if not isCubed, localSearch must be .true.')
       end if
       allocate(elons(im+1),_STAT)
       allocate(elats(jm+1),_STAT)
       call ESMF_GridGet(grid,coordSys=coordSys,_RC)
       elons = lons(:,1)
       elats = lats(1,:)
       if (coordSys==ESMF_COORDSYS_SPH_DEG) then
          elons=elons*MAPL_DEGREES_TO_RADIANS_R8
          elats=elats*MAPL_DEGREES_TO_RADIANS_R8
       else if (coordSys==ESMF_COORDSYS_CART) then
          _FAIL('Unsupported coordinate system:  ESMF_COORDSYS_CART')
       end if
       ! lat-lon grid goes from -180 to 180 shift if we must
       ! BMA this -180 to 180 might change at some point
       do i=1,npts
          lonloc = target_lons(i)
          latloc = target_lats(i)
          if (lonloc > MAPL_PI) lonloc = lonloc - 2.0*MAPL_PI
          IIloc = ijsearch(elons,im+1,lonloc,.false.)
          JJloc = ijsearch(elats,jm+1,latloc,.false.)
          II(i) = IIloc
          JJ(i) = JJloc
       end do
       deallocate(elons,elats)
    end if
    _RETURN(ESMF_SUCCESS)
  contains
    integer function ijsearch(coords,idim,valueIn,periodic) ! fast bisection version
      implicit NONE
      integer, intent(in) :: idim
      real(ESMF_KIND_R8), intent(in) :: coords(:)
      real, intent(inout) :: valueIn
      logical, intent(in)  :: periodic
      integer i, i1, i2, k
      real :: value
      value = valueIn
      if ( periodic ) then
         if ( value>coords(idim) ) value = value - 360.
      endif
      ijsearch = -1
      i1 = 1
      i2 = idim
      if (coords(idim) > coords(1)) then
         do k = 1, idim  ! it should never take take long
            i = (i1 + i2) / 2
            if ( (value .ge. coords(i)) ) then
               if (value .lt. coords(i+1) ) then
                  ijsearch = i
                  exit
               else
                  i1 = i
               end if
            else
               i2 = i
            endif
         end do
      else
         do k = 1, idim  ! it should never take take long
            i = (i1 + i2) / 2
            if ( (value .lt. coords(i)) ) then
               if (value .ge. coords(i+1) ) then
                  ijsearch = i
                  exit
               else
                  i1 = i
               end if
            else
               i2 = i
            endif
         end do
      endif
    end function ijsearch
  end subroutine MAPL_GetHorzIJIndex
Call graph
mapl_gethorzijindex calls ESMF_AttributeGet, ESMF_GridGet, ESMF_GridGetCoord, mapl_assert, mapl_gridgetcorners, get_points_in_spherical_domain, mapl_gridget, mapl_return, mapl_verify, mapl_gethorzijindex
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridgetcorners calls mapl_gridgetcorners, ESMF_AttributeGet, ESMF_GridGet, ESMF_GridGetCoord, mapl_assert, mapl_gridget, mapl_return, mapl_verify, ESMF_AttributeSet, ESMF_FieldHalo, ESMF_FieldHaloRelease, ESMF_FieldHaloStore, esmf_fieldcreate, esmf_fielddestroy
get_points_in_spherical_domain calls mapl_assert, mapl_return, point_in_polygon
mapl_gridget calls ESMF_AttributeGet, ESMF_GridGet, mapl_return, mapl_verify, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
point_in_polygon calls convert_to_cart, lines_intersect
lines_intersect calls cross_prod, normal_vect