MAPL_VarSpecGetFieldPtr – MAPL
MAPL_VarSpecGetFieldPtr Subroutine
12 statements
Source File
private subroutine MAPL_VarSpecGetFieldPtr(SPEC, FIELDPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(in) :: SPEC
type(ESMF_Field), pointer :: FIELDPTR
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecGetFieldPtr
Source Code
   subroutine MAPL_VarSpecGetFieldPtr(SPEC, FIELDPTR, RC )
      type (MAPL_VarSpec ),             intent(IN )     :: SPEC
      type(ESMF_Field)   ,              pointer         :: FIELDPTR
      integer            , optional   , intent(OUT)     :: RC
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      FIELDPTR => SPEC%SPECPtr%FIELD
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecGetFieldPtr
Call graph
mapl_varspecgetfieldptr calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecget calls mapl_varspecgetfieldptr
initialize calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_bundleinit calls mapl_varspecget
mapl_cplcompsetvarspecs calls mapl_varspecget
mapl_friendlyget calls mapl_varspecget
mapl_genericspecenum calls mapl_varspecget, mapl_genericspecenum
mapl_getnumsubtiles calls mapl_varspecget
mapl_labelget calls mapl_varspecget
mapl_setvarspecforcc calls mapl_varspecget, mapl_cplcompsetvarspecs
mapl_stateaddexportspecfrmall calls mapl_varspecget
mapl_stateaddexportspecfrmchld_all calls mapl_varspecget
mapl_stateaddinternalspec calls mapl_varspecget
mapl_statecreatefromspecnew calls mapl_varspecget
mapl_statecreatefromvarspecnew calls mapl_varspecget, mapl_statecreatefromspecnew
mapl_stategetspecattrib calls mapl_varspecget
mapl_terminateimportallbut calls mapl_varspecget
mapl_varspecreconnect calls mapl_varspecget
mapl_wirecomponent calls mapl_varspecget, mapl_cplcompsetvarspecs
readrestart calls mapl_varspecget
test_simple_constructor calls mapl_varspecget
writerestart calls mapl_varspecget
mapl_addexportspec calls mapl_stateaddexportspecfrmall, mapl_stateaddexportspecfrmchld_all
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_terminateimport calls mapl_terminateimportallbut
mapl_genericinitialize calls mapl_getnumsubtiles
mapl_readforcingx calls mapl_getnumsubtiles, mapl_statecreatefromvarspecnew, mapl_stategetspecattrib
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_stategettimestamp calls mapl_stategetspecattrib