MAPL_GenericStateSetFromGC – MAPL
MAPL_GenericStateSetFromGC Subroutine
20 statements
Source File
private subroutine MAPL_GenericStateSetFromGC(GC, ORBIT, LM, RUNALARM, CHILDINIT, LOCSTREAM, EXCHANGEGRID, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_SunOrbit), intent(in), optional :: ORBIT
integer, intent(in), optional :: LM
type(ESMF_Alarm), intent(in), optional :: RUNALARM
logical, intent(in), optional :: CHILDINIT
type(MAPL_LocStream), intent(in), optional :: LOCSTREAM
type(MAPL_LocStream), intent(in), optional :: EXCHANGEGRID
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GenericStateSetFromGC
Source Code
   subroutine MAPL_GenericStateSetFromGC (GC, ORBIT, LM, RUNALARM, CHILDINIT, &
        LOCSTREAM, EXCHANGEGRID, CLOCK, RC)
      !ARGUMENTS:
      type (ESMF_GridComp),            intent(INout) :: GC
      type (ESMF_Alarm),     optional, intent(IN   ) :: RUNALARM
      type (MAPL_SunOrbit),  optional, intent(IN   ) :: ORBIT
      integer,               optional, intent(IN   ) :: LM
      logical,               optional, intent(IN   ) :: CHILDINIT
      type (MAPL_LocStream), optional, intent(IN   ) :: LOCSTREAM
      type (MAPL_LocStream), optional, intent(IN   ) :: EXCHANGEGRID
      type (ESMF_Clock)    , optional, intent(IN   ) :: CLOCK
      integer,               optional, intent(  OUT) :: RC
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm = "MAPL_GenericStateSetFromGC"
      integer :: status
      type (MAPL_MetaComp), pointer         :: STATE
      call MAPL_InternalStateGet ( GC, STATE, RC=status )
      _VERIFY(status)
      call MAPL_GenericStateSet (STATE, ORBIT, LM, RUNALARM, CHILDINIT, &
           LOCSTREAM, EXCHANGEGRID, CLOCK, RC=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericStateSetFromGC
Call graph
mapl_genericstatesetfromgc calls mapl_genericstateset, mapl_internalstateget, mapl_return, mapl_verify
mapl_genericstateset calls mapl_return, mapl_verify, ESMF_ConfigCreate, ESMF_ConfigLoadFile, get_composite, get_logger, initialize, set_component, set_composite, set_logger
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
initialize calls initialize_global_time_profiler
mapl_throw_exception calls initialize
initialize_global_time_profiler calls get_global_time_profiler
mapl_set calls mapl_genericstatesetfromgc
initialize_gc calls mapl_set
mapl_capgridcompcreate calls mapl_set
run_component_driver calls mapl_set
initialize_cap_gc calls mapl_capgridcompcreate
main calls run_component_driver
run_model calls initialize_cap_gc
comp_testing_driver calls main