MAPL_FieldGetLocalElementCount – MAPL
MAPL_FieldGetLocalElementCount Subroutine
56 statements
Source File
private subroutine MAPL_FieldGetLocalElementCount(field, local_count, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: field
integer, intent(out), allocatable :: local_count(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_FieldGetLocalElementCount(field,local_count,rc)
     type(ESMF_Field), intent(inout) :: field
     integer, allocatable, intent(out) :: local_count(:)
     integer, optional, intent(out) :: rc
     integer :: status, rank
     type(ESMF_TypeKind_Flag) :: tk
     real(kind=ESMF_KIND_R4), pointer :: r4_1d(:),r4_2d(:,:),r4_3d(:,:,:),r4_4d(:,:,:,:)
     real(kind=ESMF_KIND_R8), pointer :: r8_1d(:),r8_2d(:,:),r8_3d(:,:,:),r8_4d(:,:,:,:)
     call ESMF_FieldGet(field,rank=rank,typekind=tk,_RC)
     if (tk == ESMF_TypeKind_R4) then
        if (rank==1) then
           call ESMF_FieldGet(field,0,farrayptr=r4_1d,_RC)
           local_count = shape(r4_1d)
        else if (rank ==2) then
           call ESMF_FieldGet(field,0,farrayptr=r4_2d,_RC)
           local_count = shape(r4_2d)
        else if (rank ==3) then
           call ESMF_FieldGet(field,0,farrayptr=r4_3d,_RC)
           local_count = shape(r4_3d)
        else if (rank ==4) then
           call ESMF_FieldGet(field,0,farrayptr=r4_4d,_RC)
           local_count = shape(r4_4d)
        else
           _FAIL("Unsupported rank")
        end if
     else if (tk == ESMF_TypeKind_R8) then
        if (rank==1) then
           call ESMF_FieldGet(field,0,farrayptr=r8_1d,_RC)
           local_count = shape(r8_1d)
        else if (rank ==2) then
           call ESMF_FieldGet(field,0,farrayptr=r8_2d,_RC)
           local_count = shape(r8_2d)
        else if (rank ==3) then
           call ESMF_FieldGet(field,0,farrayptr=r8_3d,_RC)
           local_count = shape(r8_3d)
        else if (rank ==4) then
           call ESMF_FieldGet(field,0,farrayptr=r8_4d,_RC)
           local_count = shape(r8_4d)
        else
           _FAIL("Unsupported rank")
        end if
     else
        _FAIL("Unsupported type")
     end if
     _RETURN(_SUCCESS)
  end subroutine MAPL_FieldGetLocalElementCount
Call graph
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
copy_broadcast calls mapl_fieldgetlocalelementcount
get_local_element_count calls mapl_fieldgetlocalelementcount
fieldcopybroadcast calls copy_broadcast
fieldgetlocalelementcount calls get_local_element_count
clone calls get_local_element_count
fieldclone calls clone
are_broadcast_conformable calls fieldgetlocalelementcount
are_conformable_scalar calls fieldgetlocalelementcount
evalf calls fieldcopybroadcast
gemv_r4 calls fieldgetlocalelementcount
gemv_r8 calls fieldgetlocalelementcount
get_local_size calls fieldgetlocalelementcount
test_fieldgetlocalelementcount calls fieldgetlocalelementcount
fieldgemv calls gemv_r4, gemv_r8
fieldgetlocalsize calls get_local_size
fieldsarebroadcastconformable calls are_broadcast_conformable
fieldsareconformable calls are_conformable_scalar
compile calls fieldclone
mapl_stateeval calls evalf
statefilter_r4_2d calls fieldclone
statefilter_r4_3d calls fieldclone
test_fieldclone3d calls fieldclone