MAPL_CommsBcast_I4_1 – MAPL
MAPL_CommsBcast_I4_1 Subroutine
19 statements
Source File
private subroutine MAPL_CommsBcast_I4_1(layout, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
integer(kind=ESMF_KIND_I4), intent(inout) :: data(:)
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
Calls
Called by
Contents
Call graph
mapl_commsbcast_i4_1 calls esmf_delayoutget, mapl_return, esmf_vmget, mapl_verify, mpi_bcast
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_commsbcast calls mapl_commsbcast_i4_1
read_parallel_r4_2 calls mapl_commsbcast
read_parallel_r8_2 calls mapl_commsbcast
read_parallel_r8_0 calls mapl_commsbcast
mapl_bcastshared_1dr4 calls mapl_commsbcast
mapl_locstreamcreatefromfile calls mapl_commsbcast
mapl_commsbcast_string_0 calls mapl_commsbcast
mapl_varwrite_r8_1d calls mapl_commsbcast
read_parallel_i4_1 calls mapl_commsbcast
read_parallel_r4_0 calls mapl_commsbcast
read_parallel_r4_1 calls mapl_commsbcast
read_parallel_r8_1 calls mapl_commsbcast
mapl_areamean_2d_r8_bitrep calls mapl_commsbcast
read_parallel_string_0 calls mapl_commsbcast
mapl_fieldread calls mapl_commsbcast
mapl_getlatloncoord_real32 calls mapl_commsbcast
mapl_bcastshared_2dr4 calls mapl_commsbcast
initialize calls mapl_commsbcast
mapl_esmfstatereadfromfile calls mapl_commsbcast
mapl_getlatloncoord_real64 calls mapl_commsbcast
mapl_varwrite_r4_1d calls mapl_commsbcast
read_parallel_i4_0 calls mapl_commsbcast
read_parallel_i4_2 calls mapl_commsbcast
mapl_varread_r8_1d calls mapl_commsbcast
mapl_sungetsolarconstantfromnrlfile calls mapl_commsbcast
mapl_varread_r4_1d calls mapl_commsbcast
mapl_cfiocreatefrombundle calls mapl_commsbcast
readrestart calls mapl_commsbcast