MAPL_StateAddExportSpecFrmChld_All – MAPL
MAPL_StateAddExportSpecFrmChld_All Subroutine
26 statements
Source File
private subroutine MAPL_StateAddExportSpecFrmChld_All(GC, CHILD_ID, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(in) :: CHILD_ID
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateAddExportSpecFrmChld_All
Source Code
   subroutine MAPL_StateAddExportSpecFrmChld_All ( GC, CHILD_ID, RC)
      !ARGUMENTS:
      type(ESMF_GridComp),              intent(INOUT)   :: GC
      integer                         , intent(IN)      :: CHILD_ID
      integer            , optional   , intent(OUT)     :: RC
      !EOPI
      character (len=ESMF_MAXSTR)  :: SHORT_NAME ! NAME in CHILD
      character (len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddExportSpecFrmChld"
      integer                               :: status
      type (MAPL_VarSpec),      pointer     :: SPECS(:)
      integer :: I
      type(ESMF_GridComp), pointer :: gridcomp
      type(MAPL_MetaComp), pointer :: maplobj
      call MAPL_InternalStateRetrieve(gc, maplobj, _RC)
      gridcomp => maplobj%GET_CHILD_GRIDCOMP(child_id)
      call MAPL_GridCompGetVarSpecs(gridcomp, EXPORT=SPECS, _RC)
       _VERIFY(status)
      do I = 1, size(SPECS)
         call MAPL_VarSpecGet(SPECS(I), SHORT_NAME=short_name, _RC)
         call MAPL_StateAddExportSpecFrmChld(gc, short_name, child_id, _RC)
      enddo
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateAddExportSpecFrmChld_all
Call graph
mapl_stateaddexportspecfrmchld_all calls mapl_internalstateretrieve, mapl_verify, mapl_varspecget, mapl_stateaddexportspecfrmchld, mapl_gridcompgetvarspecs, mapl_return
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_verify calls mapl_throw_exception
mapl_varspecget calls mapl_varspecgetstateptr, mapl_varspecgetregular, mapl_varspecgetfieldptr, mapl_varspecgetbundleptr, mapl_varspecgetnew
mapl_stateaddexportspecfrmchld calls mapl_internalstateretrieve, mapl_verify, mapl_return, mapl_stateaddexportspecfrmchldname
mapl_gridcompgetvarspecs calls mapl_internalstateretrieve, mapl_verify, mapl_return, esmf_gridcompget, mapl_stategetvarspecs
mapl_return calls mapl_throw_exception, get_error_message
mapl_internalstateget calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_varspecgetstateptr calls mapl_return
mapl_throw_exception calls initialize
mapl_internalstatecreate calls mapl_verify, mapl_return, esmf_gridcompget, esmf_usercompsetinternalstate
mapl_varspecgetregular calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_stateaddexportspecfrmchldname calls mapl_internalstateretrieve, mapl_verify, mapl_return, mapl_addconnectivitye2e
mapl_stategetvarspecs calls mapl_return
mapl_addconnectivitye2e calls mapl_verify, mapl_return, mapl_connectivityget
mapl_addexportspec calls mapl_stateaddexportspecfrmchld_all
setservices calls mapl_addexportspec, setservices
addnewspec calls mapl_addexportspec