MAPL_ConnectService – MAPL
MAPL_ConnectService Subroutine
15 statements
Source File
public subroutine MAPL_ConnectService(GC, PROVIDER, REQUESTER, SERVICE, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: PROVIDER
character(len=*), intent(in) :: REQUESTER
character(len=*), intent(in) :: SERVICE
integer, intent(out), optional :: RC
Calls
Source Code
   subroutine MAPL_ConnectService( GC, PROVIDER, REQUESTER, SERVICE, RC)
      !ARGUMENTS:
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*),              intent(IN   ) :: PROVIDER
      character (len=*),              intent(IN   ) :: REQUESTER
      character (len=*),              intent(IN   ) :: SERVICE
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_ServiceAddConnection"
      integer                               :: status
      type (MAPL_Connectivity), pointer     :: conn
      call MAPL_ConnectivityGet(gc, connectivityPtr=conn, RC=status)
      _VERIFY(status)
      call conn%ServiceConnectionItems%push_back( &
           ServiceConnectionType( &
           provider_name=provider, &
           requester_name=requester, &
           service_name=service))
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ConnectService
Call graph
mapl_connectservice calls mapl_connectivityget, mapl_return, mapl_verify, v_push_back
mapl_connectivityget calls mapl_return, mapl_verify, mapl_getobjectfromgc
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
mapl_getobjectfromgc calls mapl_internalstateget
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
v_resize_32 calls resize