MAPL_OPEN – MAPL
MAPL_OPEN Subroutine
26 statements
Source File
private subroutine MAPL_OPEN(UNIT, FILE, FORM, BLOCKSIZE, NUMBUFFERS, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
character(len=*), intent(in) :: FILE
character(len=*), intent(in), optional :: FORM
integer, intent(in), optional :: BLOCKSIZE
integer, intent(in), optional :: NUMBUFFERS
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_OPEN(UNIT,FILE,FORM,BLOCKSIZE, NUMBUFFERS, RC)
    implicit none
    integer         , optional, intent(out) :: RC
    integer         ,           intent(in) :: UNIT
    character(LEN=*),           intent(in) :: FILE
    character(LEN=*), optional, intent(in) :: FORM
    integer,          optional, intent(in) :: BLOCKSIZE, NUMBUFFERS
    integer          :: status
    character(LEN=ESMF_MAXSTR) :: usableFORM
    if(MAPL_AM_I_ROOT()) then
       if(.not.present(BLOCKSIZE) .and. .not.present(NUMBUFFERS)) then
          print *, "NOT using buffer I/O for file: ", trim(file)
       else
          print *, "Using buffer I/O for file: ", trim(file)
       endif
    endif
    if (present(FORM)) then
       usableFORM = FORM
    else
       usableFORM = "unformatted"
    end if
    open(UNIT,FILE=FILE,FORM=usableFORM,IOSTAT=STATUS)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_OPEN
Call graph
mapl_open calls mapl_am_i_root, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
getfile calls mapl_open
cap_finalize calls getfile
initialize calls getfile
mapl_climupdate calls getfile
mapl_clockinit calls getfile
mapl_destroystatesave calls getfile, mapl_destroystatesave
mapl_esmfstatereadfromfile calls getfile
mapl_esmfstatewritetofile calls getfile
mapl_genericstaterestore calls getfile, mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_gradsctlwrite calls getfile
mapl_gridcoordadjustfromfile calls getfile
mapl_locstreamcreatefromfile calls getfile
mapl_readforcingx calls getfile
mapl_staterefresh calls getfile, mapl_esmfstatereadfromfile
readrestart calls getfile
run calls getfile, mapl_gradsctlwrite
writerestart calls getfile
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
capture calls mapl_esmfstatewritetofile
destroy_state calls mapl_destroystatesave
finalize_gc calls cap_finalize
initialize_gc calls mapl_clockinit
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericrefresh calls mapl_staterefresh
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterecord calls mapl_esmfstatewritetofile
refresh_state calls mapl_genericstaterestore