MAPL_SimpleBundleDestroy – MAPL
MAPL_SimpleBundleDestroy Subroutine
20 statements
Source File
public subroutine MAPL_SimpleBundleDestroy(self, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_SimpleBundle) :: self
integer, intent(out), optional :: rc
Calls
Contents
Source Code
MAPL_SimpleBundleDestroy
Source Code
  subroutine MAPL_SimpleBundleDestroy (self, rc )
! !ARGUMENTS:
    type(MAPL_SimpleBundle)                    :: self ! Simple Bundle
    integer, OPTIONAL,           intent(out)   :: rc
!  !DESCRIPTION:
!
!   Destructor for the MAPL Simple Bundle.  It is assumed that the bundle has been created from
!   an ESMF Field Bundle.
!EOP
!-----------------------------------------------------------------------------
    integer :: status
    deallocate(self%coords%Lons, self%coords%Lats, self%coords%Levs, __STAT__)
!    deallocate(self%r1, self%r2, self%r3, __STAT__)
    if(associated(self%r1)) deallocate(self%r1)
    if(associated(self%r2)) deallocate(self%r2)
    if(associated(self%r3)) deallocate(self%r3)
    if (associated(self%bundle)) then
       call MAPL_FieldBundleDestroy(self%bundle, _RC)
    end if
    if (self%bundleAlloc) then
       deallocate(self%bundle, __STAT__)
    end if
    _RETURN(_SUCCESS)
  end subroutine MAPL_SimpleBundleDestroy
Call graph
mapl_simplebundledestroy calls mapl_verify, mapl_fieldbundledestroy, mapl_return
mapl_verify calls mapl_throw_exception
mapl_fieldbundledestroy calls mapl_fieldbundledestroy, mapl_verify, mapl_return, esmf_fieldbundleiscreated, mapl_fielddestroy, esmf_fieldbundleget
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_fielddestroy calls mapl_fielddestroy