MAPL_GetFieldTimeFromField – MAPL
MAPL_GetFieldTimeFromField Module Subroutine
25 statements
Source File
module subroutine MAPL_GetFieldTimeFromField(FIELD, TIME, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: FIELD
type(ESMF_Time), intent(out) :: TIME
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GetFieldTimeFromField
Source Code
  module subroutine MAPL_GetFieldTimeFromField ( FIELD, TIME, RC )
    type(ESMF_Field),        intent(INOUT) :: FIELD ! ALT: IN
    type(ESMF_Time),         intent(  OUT) :: TIME
    integer, optional,       intent(  OUT) :: RC
    character(len=ESMF_MAXSTR),parameter   :: IAm=" MAPL_GetFieldTimeFromField"
    integer                                :: STATUS
    integer                                :: YEAR, MONTH, DAY
    integer                                :: HOUR, MINUTE, SCND
    character(len=ESMF_MAXSTR)             :: TIMESTAMP
    logical                                :: isPresent
    call ESMF_AttributeGet(FIELD, NAME="TimeStamp", isPresent=isPresent, RC=STATUS)
    _VERIFY(STATUS)
    if(.not. isPresent) then
       call ESMF_TimeSet          (TIME,      YY=0,                RC=STATUS)
    else
       call ESMF_AttributeGet(FIELD, NAME="TimeStamp", VALUE=TIMESTAMP, RC=STATUS)
       _VERIFY(STATUS)
       call MAPL_TimeStringGet    (TIMESTAMP, YY=YEAR, MM=MONTH,  DD=DAY,   &
            H =HOUR, M =MINUTE, S =SCND   )
       _VERIFY(STATUS)
       call ESMF_TimeSet          (TIME,      YY=YEAR, MM=MONTH,  DD=DAY,   &
            H =HOUR, M =MINUTE, S =SCND,  &
            RC=STATUS)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_GetFieldTimeFromField
Call graph
mapl_getfieldtimefromfield calls ESMF_AttributeGet, ESMF_TimeSet, mapl_timestringget, mapl_return, mapl_verify, mapl_getfieldtimefromfield
mapl_timestringget calls mapl_timestringget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_fieldgettime calls mapl_getfieldtimefromfield
mapl_climupdate calls mapl_fieldgettime
mapl_getfieldtimefromstate calls mapl_fieldgettime, mapl_getfieldtimefromstate