MAPL_GetLatLonCoord_REAL32 – MAPL
MAPL_GetLatLonCoord_REAL32 Subroutine
43 statements
Source File
private subroutine MAPL_GetLatLonCoord_REAL32(grid, dim, x, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
integer, intent(in) :: dim
real(kind=REAL32), intent(out) :: x(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_GetLatLonCoord_REAL32
Source Code
   subroutine MAPL_GetLatLonCoord_REAL32(grid,dim,x,rc)
      real(kind=REAL32), intent(out)  :: x(:)
      type(ESMF_Grid), intent(inout) :: grid
      integer,           intent(in) :: dim
      integer, optional, intent(out) :: rc
      real(kind=REAL64), pointer :: x_2d(:,:) => null()
      real(kind=REAL32), allocatable :: xg(:,:),xl(:,:)
      integer :: counts(3),mypet
      type(ESMF_DistGrid) :: distgrid
      type(ESMF_DeLayout) :: layout
      type(ESMF_VM) :: vm
      integer :: status
      call ESMF_GridGetCoord (grid, coordDim=dim, localDE=0, &
               staggerloc=ESMF_STAGGERLOC_CENTER, &
               farrayPtr=x_2d, rc=status)
      _VERIFY(status)
      call MAPL_GridGet(grid,globalCellCountPerDim=counts,rc=status)
      _VERIFY(status)
      allocate(xg(counts(1),counts(2)),stat=status)
      _VERIFY(status)
      allocate(xl(size(x_2d,1),size(x_2d,2)),stat=status)
      _VERIFY(status)
      xl=x_2d
      call ArrayGather(xl,xg,grid,rc=status)
      _VERIFY(status)
      deallocate(xl)
      call ESMF_GridGet(GRID, DistGrid=distgrid, rc=status)
      _VERIFY(STATUS)
      call ESMF_DistGridGet(distgrid, DELayout=layout, rc=status)
      _VERIFY(STATUS)
      call ESMF_DELayoutGet(layout,vm=vm,rc=status)
      _VERIFY(status)
      call ESMF_VMGet(vm,localPet=myPet,rc=status)
      _VERIFY(status)
      if (dim==1) then
         if(myPet==0) x = xg(:,1)
      else if (dim==2) then
         if (myPet==0) x = xg(1,:)
      else
         _FAIL('unsupported rank > 2')
      end if
      call MAPL_CommsBcast(layout,x,size(x), 0, rc=status)
      _VERIFY(status)
      deallocate(xg)
   end subroutine MAPL_GetLatLonCoord_Real32
Call graph
mapl_getlatloncoord_real32 calls esmf_gridgetcoord, mapl_verify, esmf_gridget, mapl_gridget, arraygather, esmf_distgridget, esmf_delayoutget, esmf_vmget, mapl_assert, mapl_commsbcast
mapl_getlatloncoord calls mapl_getlatloncoord_real32
gridgetlatlons_ calls mapl_getlatloncoord
initialize_subclass calls mapl_getlatloncoord
mapl_cfioreadbundle calls gridgetlatlons_
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfioreadfield calls mapl_cfioreadbundle
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle