MAPL_MemUtilsDisable – MAPL
MAPL_MemUtilsDisable Subroutine
7 statements
Source File
public subroutine MAPL_MemUtilsDisable(RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: RC
Calls
Called by
Source Code
    subroutine MAPL_MemUtilsDisable(RC)
      integer, optional, intent(OUT)   :: RC
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_MemUtilsDisable"
      DISABLED = .true.
      _RETURN(ESMF_SUCCESS)
    end subroutine MAPL_MemUtilsDisable
Call graph
mapl_memutilsdisable calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_gc calls mapl_memutilsdisable