MAPL_GenericStateClockOff – MAPL
MAPL_GenericStateClockOff Subroutine
15 statements
Source File
private subroutine MAPL_GenericStateClockOff(STATE, NAME, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine MAPL_GenericStateClockOff(STATE,NAME,RC)
      !ARGUMENTS:
      type (MAPL_MetaComp),        intent(INOUT) :: STATE
      character(len=*),            intent(IN   ) :: NAME
      integer, optional,           intent(  OUT) :: RC     ! Error code:
      !EOPI
      character(len=ESMF_MAXSTR), parameter :: IAm = "MAPL_GenericStateClockOff"
      integer :: status
      if (trim(name) == 'TOTAL') then
         _RETURN(ESMF_SUCCESS)
      end if
      call state%t_profiler%stop(get_actual_timer_name(name),_RC)
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericStateClockOff
Call graph
mapl_genericstateclockoff calls get_actual_timer_name, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_timeroff calls mapl_genericstateclockoff
append_file calls mapl_timeroff
create_geosat_grid_find_mask calls mapl_timeroff, create_geosat_grid_find_mask
initialize_ calls mapl_timeroff, mapl_genericinitialize
initialize calls mapl_timeroff, mapl_genericinitialize, create_geosat_grid_find_mask
mapl_genericfinalize calls mapl_timeroff
mapl_genericinitialize calls mapl_timeroff
mapl_genericrecord calls mapl_timeroff
mapl_genericrefresh calls mapl_timeroff, mapl_genericrefresh
mapl_genericrunchildren calls mapl_timeroff
mapl_genericwrapper calls mapl_timeroff
regrid_append_file calls mapl_timeroff, regrid_append_file
run calls mapl_timeroff, append_file, regrid_append_file
run_ calls mapl_timeroff
finalize calls mapl_genericfinalize
finalize_ calls mapl_genericfinalize