MAPL_VarSpecSetStatePtr – MAPL
MAPL_VarSpecSetStatePtr Subroutine
12 statements
Source File
private subroutine MAPL_VarSpecSetStatePtr(SPEC, STATEPTR, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC
type(ESMF_State), pointer :: STATEPTR
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarSpecSetStatePtr
Source Code
   subroutine MAPL_VarSpecSetStatePtr(SPEC, STATEPTR, RC )
      type (MAPL_VarSpec ),             intent(INOUT)   :: SPEC
      type(ESMF_State)  ,               pointer         :: STATEPTR
      integer            , optional   , intent(  OUT)   :: RC
      if(.not.associated(SPEC%SPECPtr)) then
         _RETURN(ESMF_FAILURE)
      endif
      SPEC%SPECPtr%STATE => STATEPTR
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_VarSpecSetStatePtr
Call graph
mapl_varspecsetstateptr calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_varspecset calls mapl_varspecsetstateptr