MAPL_GetFieldTimeFromState – MAPL
MAPL_GetFieldTimeFromState Module Subroutine
15 statements
Source File
module subroutine MAPL_GetFieldTimeFromState(STATE, Fieldname, TIME, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(in) :: STATE
character(len=*), intent(in) :: Fieldname
type(ESMF_Time), intent(out) :: TIME
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_GetFieldTimeFromState
Source Code
  module subroutine  MAPL_GetFieldTimeFromState ( STATE, Fieldname, TIME, RC )
    type(ESMF_STATE),        intent(IN   ) :: STATE
    character(len=*),        intent(IN   ) :: Fieldname
    type(ESMF_Time),         intent(  OUT) :: TIME
    integer, optional,       intent(  OUT) :: RC
    character(len=ESMF_MAXSTR),parameter   :: IAm=" MAPL_GetFieldTimeFromState"
    integer                                :: STATUS
    type(ESMF_FIELD)                       :: FIELD
    call ESMF_StateGet (STATE, FIELDNAME, FIELD, RC=STATUS )
    _VERIFY(STATUS)
    call MAPL_FieldGetTime  (FIELD, TIME,             RC=STATUS)
    _VERIFY(STATUS)
    _RETURN(ESMF_SUCCESS)
  end subroutine  MAPL_GetFieldTimeFromState
Call graph
mapl_getfieldtimefromstate calls esmf_stateget, mapl_fieldgettime, mapl_return, mapl_verify, mapl_getfieldtimefromstate
mapl_fieldgettime calls mapl_getfieldtimefromfield, mapl_getfieldtimefromstate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_getfieldtimefromfield calls mapl_getfieldtimefromfield, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_TimeSet, mapl_timestringget
get_error_message calls at
mapl_throw_exception calls initialize
mapl_climupdate calls mapl_fieldgettime