MAPL_ConfigSetAttribute_int32 – MAPL
MAPL_ConfigSetAttribute_int32 Subroutine
89 statements
Source File
private subroutine MAPL_ConfigSetAttribute_int32(config, value, label, rc)
Uses
iso_fortran_env
Set a 4-byte integer value in the config object.
The arguments are: - config: Already created ESMF_Config object. - value: Integer value to set. - label: Identifying attribute label. - rc: Return code; equals ESMF_SUCCESS if there are no errors.
Private name: call using ESMF_ConfigSetAttribute()`.
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: config
integer(kind=INT32), intent(in) :: value
character(len=*), intent(in), optional :: label
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ConfigSetAttribute_int32
Source Code
      subroutine MAPL_ConfigSetAttribute_int32( config, value, label, rc )
         use, intrinsic :: iso_fortran_env, only: INT32
!
      type(ESMF_Config), intent(inout)             :: config
      integer(kind=INT32), intent(in)            :: value
      character(len=*), intent(in), optional       :: label
      integer, intent(out), optional               :: rc
!
!$$      character(len=ESMF_MAXSTR) :: Iam = 'MAPL_ConfigSetAttribute_int32'
      character(len=ESMF_MAXSTR) :: logmsg
      character(len=LSZ) :: curVal, newVal
      integer :: iret, i, j, k, m, nchar, ninsert, ndelete, lenThisLine
      ! Initialize return code; assume routine not implemented
      iret = ESMF_RC_NOT_IMPL
      if (present(rc)) rc = ESMF_RC_NOT_IMPL
      !check variables
!ALT      ESMF_INIT_CHECK_DEEP(ESMF_ConfigGetInit,config,rc)
      ! Set config buffer at desired attribute
      if ( present (label) ) then
         call ESMF_ConfigGetAttribute( config, value=curVal, label=label, rc = iret )
      else
         call ESMF_ConfigGetAttribute( config, value=curVal, rc = iret )
      endif
      if ( iret .ne. ESMF_SUCCESS ) then
        if ( iret .eq. ESMF_RC_NOT_FOUND ) then
          ! set config buffer at end for appending
          i = config%cptr%nbuf
        else
          if ( present( rc ) ) then
            rc = iret
          endif
          return
        endif
      else ! attribute found
        ! set config buffer for overwriting/inserting
        i = config%cptr%value_begin
        curVal = BLK // trim(curVal) // BLK // EOL ! like config%cptr%this_line
      endif
      ! for appending, create new attribute string with label and value
      if ( i .eq. config%cptr%nbuf .and. present(label) ) then
        write(newVal, *) label, value
        newVal = trim(adjustl(newVal)) // EOL
        j = i + len_trim(newVal)
        ! check to ensure len of newVal doesn't exceed LSZ
        if ( (j-i) .gt. LSZ) then
           write(logmsg, *) ", attribute label, value & EOL are ", j-i, &
               " characters long, only ", LSZ, " characters allowed per line"
           _RETURN(ESMF_RC_LONG_STR)
        endif
        ! check if enough space left in config buffer
        if (j .ge. NBUF_MAX) then   ! room for EOB if necessary
           write(logmsg, *) ", attribute label & value require ", j-i+1, &
               " characters (including EOL & EOB), only ", NBUF_MAX-i, &
               " characters left in config buffer"
           _RETURN(ESMF_RC_LONG_STR)
        endif
      endif
      ! overwrite, with possible insertion or deletion of extra characters
      if (i .eq. config%cptr%value_begin) then
         write(newVal, *) value
         newVal = BLK // trim(adjustl(newVal)) // EOL
         j = i + len_trim(newVal) - 1
         !  check if we need more space to insert new characters;
         !  shift buffer down (linked-list redesign would be better!)
         nchar = j-i+1
         lenThisLine = len_trim(curVal) - 1
         if ( nchar .gt. lenThisLine) then
            ! check to ensure length of extended line doesn't exceed LSZ
            do m = i, 1, -1
              if (config%cptr%buffer(m:m) .eq. EOL) then
                exit
              endif
            enddo
            if (j-m+1 .gt. LSZ) then
               write(logmsg, *) ", attribute label, value & EOL are ", j-m+1, &
                  " characters long, only ", LSZ, " characters allowed per line"
               _RETURN(ESMF_RC_LONG_STR)
            endif
            ! check if enough space left in config buffer to extend line
            if (j+1 .ge. NBUF_MAX) then   ! room for EOB if necessary
               write(logmsg, *) ", attribute label & value require ", j-m+1, &
                   " characters (including EOL & EOB), only ", NBUF_MAX-i, &
                   " characters left in config buffer"
               _RETURN(ESMF_RC_LONG_STR)
            endif
            ninsert = nchar - lenThisLine
            do k = config%cptr%nbuf, j, -1
               config%cptr%buffer(k+ninsert:k+ninsert) = config%cptr%buffer(k:k)
            enddo
            config%cptr%nbuf = config%cptr%nbuf + ninsert
         ! or if we need less space and remove characters;
         ! shift buffer up
         elseif ( nchar .lt. lenThisLine ) then
           ndelete = lenThisLine - nchar
            do k = j+1, config%cptr%nbuf
               config%cptr%buffer(k-ndelete:k-ndelete) = config%cptr%buffer(k:k)
            enddo
            config%cptr%nbuf = config%cptr%nbuf - ndelete
         endif
      endif
      ! write new attribute value into config
      config%cptr%buffer(i:j) = newVal(1:len_trim(newVal))
      ! if appended, reset EOB marker and nbuf
      if (i .eq. config%cptr%nbuf) then
!@@        j = j + 1
!@@        config%cptr%buffer(j:j) = EOB
        config%cptr%nbuf = j
      endif
      if( present( rc )) then
        if ( iret .eq. ESMF_RC_NOT_FOUND ) iret = ESMF_SUCCESS
        rc = iret
      endif
      return
   end subroutine MAPL_ConfigSetAttribute_int32
Call graph
mapl_configsetattribute_int32 calls ESMF_ConfigGetAttribute, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_reals32
addgrid calls mapl_configsetattribute
create_cf calls mapl_configsetattribute
create_output_grid calls mapl_configsetattribute
initialize calls mapl_configsetattribute
initialize_from_esmf_distgrid calls mapl_configsetattribute
initialize_gc calls mapl_configsetattribute
mapl_configsetattribute_ints32 calls mapl_configsetattribute
mapl_configsetattribute_reals32 calls mapl_configsetattribute
mapl_extdatagridchangelev calls mapl_configsetattribute
mapl_gridcreate calls mapl_configsetattribute
test_setattribute_string calls mapl_configsetattribute
create_grid calls create_cf
createfilelevbracket calls mapl_extdatagridchangelev
initialize_ calls mapl_gridcreate, createfilelevbracket
time_ave calls create_output_grid
ut_regridding calls create_cf
create_bracketing_fields calls createfilelevbracket
process_command_line calls create_grid