MAPL_CFIOSet – MAPL
MAPL_CFIOSet Subroutine
41 statements
Source File
public subroutine MAPL_CFIOSet(MCFIO, Root, Psize, fName, Krank, IOWorker, globalComm, newFormat, collectionID, fraction, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(in), optional :: Root
integer, intent(in), optional :: Psize
character(len=*), intent(in), optional :: fName
integer, intent(in), optional :: Krank(:)
integer, intent(in), optional :: IOWorker
integer, intent(in), optional :: globalComm
logical, intent(in), optional :: newFormat
integer, intent(in), optional :: collectionID
integer, intent(in), optional :: fraction
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CFIOSet
Source Code
  subroutine MAPL_CFIOSet( MCFIO, Root, Psize, fName, Krank, IOWorker, globalComm, newFormat, collectionID, fraction, RC )
!
! !ARGUMENTS:
!
  type(MAPL_CFIO),             intent(INOUT) :: MCFIO
  integer, optional,           intent(IN   ) :: Root, Psize
  character*(*), optional,     intent(IN   ) :: fName
  integer, optional,           intent(IN   ) :: Krank(:)
  integer, optional,           intent(IN   ) :: IOWorker
  integer, optional,           intent(IN   ) :: globalComm
  logical, optional,           intent(IN   ) :: newFormat
  integer, optional,           intent(IN   ) :: collectionID
  integer, optional,           intent(IN   ) :: fraction
  integer, optional,           intent(  OUT) :: RC
! !DESCRIPTION:
!
!    Not a full destroy; only closes the file.
!EOP
  if(present(Root)) then
     mCFIO%Root = Root
  endif
  if(present(Psize)) then
     mCFIO%Partsize = Psize
  endif
  if(present(fName)) then
     mCFIO%fName = fName
  endif
  if(present(Krank)) then
    mCFIO%Krank = Krank
  endif
  if(present(IOWorker)) then
    mCFIO%AsyncWorkRank = IOWorker
  end if
  if(present(globalComm)) then
    mCFIO%globalComm = globalComm
  end if
  if(present(newFormat)) then
     mCFIO%newFormat = newFormat
  end if
  if(present(collectionID)) then
     mCFIO%collection_ID = collectionID
  end if
  if(present(fraction)) then
     mCFIO%fraction = fraction
  end if
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOSet
Call graph
mapl_cfioset calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_cfiowritebundle calls mapl_cfioset
mapl_cfioreadparallel_ calls mapl_cfioset
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
test_main calls esmf_iowrite
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
utcfio calls test_main
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2