MAPL_BundleCreate – MAPL
MAPL_BundleCreate Module Function
119 statements
Source File
module function MAPL_BundleCreate(name, grid, fieldNames, is2D, isEdge, long_names, units, rc) result(B) Interface →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
type(ESMF_Grid), intent(inout) :: grid
character(len=*), intent(in) :: fieldNames(:)
logical, intent(in), optional :: is2D(:)
logical, intent(in), optional :: isEdge(:)
character(len=*), intent(in), optional :: long_names(:)
character(len=*), intent(in), optional :: units(:)
integer, intent(out), optional :: rc
Return Value type(ESMF_FieldBundle)
Calls
Called by
Contents
Source Code
MAPL_BundleCreate
Source Code
  module function MAPL_BundleCreate(name,grid,fieldNames,is2D,isEdge,long_names,units,rc) result(B)
    character(len=*),           intent(in   ) :: name
    type(ESMF_Grid),            intent(inout) :: grid
    character(len=*),           intent(in   ) :: fieldNames(:)
    logical, optional,          intent(in   ) :: is2D(:)
    logical, optional,          intent(in   ) :: isEdge(:)
    character(len=*), optional, intent(in   ) :: long_names(:)
    character(len=*), optional, intent(in   ) :: units(:)
    integer, optional, intent(out  ) :: rc
    type(ESMF_FieldBundle) :: B
    character(len=ESMF_MAXSTR), parameter :: IAm='MAPL_BundleCreate'
    integer :: status
    integer :: i
    logical, allocatable :: localIs2D(:)
    logical, allocatable :: localIsEdge(:)
    real, pointer :: PTR2(:,:) => null()
    real, pointer :: PTR3(:,:,:) => null()
    integer :: counts(5)
    integer :: dims(3)
    integer, allocatable :: gridToFieldMap(:)
    integer :: gridRank
    type(ESMF_Field) :: field
    allocate(localIs2D(size(fieldNames)),stat=status)
    _VERIFY(STATUS)
    if (present(is2D)) then
       _ASSERT(size(fieldNames) == size(is2D),'inconsistent size of is2D array')
       localIs2D = is2D
    else
       localIs2D = .false.
    end if
    allocate(localIsEdge(size(fieldNames)),stat=status)
    _VERIFY(STATUS)
    if (present(isEdge)) then
       _ASSERT(size(fieldNames) == size(isEdge), 'inconsistent size of isEdge array')
       localIsEdge = isEdge
    else
       localIsEdge = .false.
    end if
    if (present(long_names)) then
       _ASSERT(size(fieldNames) == size(long_names), 'inconsistent size of long_names array')
    end if
    if (present(units)) then
       _ASSERT(size(fieldNames) == size(units), 'inconsistent size of units array')
    end if
    B = ESMF_FieldBundleCreate ( name=name, rc=STATUS )
    _VERIFY(STATUS)
    call ESMF_FieldBundleSet ( B, grid=GRID, rc=STATUS )
    _VERIFY(STATUS)
    call MAPL_GridGet(GRID, globalCellCountPerDim=COUNTS, &
         localCellCountPerDim=DIMS, RC=STATUS)
    _VERIFY(STATUS)
    do i=1,size(fieldnames)
       if (localIs2D(i)) then
          allocate(PTR2(DIMS(1),DIMS(2)),stat=STATUS)
          _VERIFY(STATUS)
          PTR2  = 0.0
          call ESMF_GridGet(GRID, dimCount=gridRank, rc=status)
          _VERIFY(STATUS)
          allocate(gridToFieldMap(gridRank), stat=status)
          _VERIFY(STATUS)
          if(gridRank == 2) then
             gridToFieldMap(1) = 1
             gridToFieldMap(2) = 2
          else if (gridRank == 3) then
             gridToFieldMap(1) = 1
             gridToFieldMap(2) = 2
             gridToFieldMap(3) = 0
          else
             _RETURN(ESMF_FAILURE)
          end if
          FIELD = ESMF_FieldCreate(grid=GRID, &
               datacopyFlag = ESMF_DATACOPY_REFERENCE,   &
               farrayPtr=PTR2, gridToFieldMap=gridToFieldMap, &
               name=fieldNames(i), RC=STATUS)
          _VERIFY(STATUS)
          deallocate(gridToFieldMap)
          call ESMF_AttributeSet(FIELD, NAME='DIMS', VALUE=MAPL_DimsHorzOnly, RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_AttributeSet(FIELD, NAME='VLOCATION', VALUE=MAPL_VLocationNone, RC=STATUS)
          _VERIFY(STATUS)
       else
          if (localIsEdge(i)) then
             allocate(PTR3(Dims(1),Dims(2),0:counts(3)),stat=status)
             _VERIFY(STATUS)
          else
             allocate(PTR3(Dims(1),Dims(2),counts(3)),stat=status)
             _VERIFY(STATUS)
          end if
          PTR3 = 0.0
          FIELD = ESMF_FieldCreate(grid=GRID, &
               datacopyFlag = ESMF_DATACOPY_REFERENCE,   &
               farrayPtr=PTR3, name=fieldNames(i), RC=STATUS)
          call ESMF_AttributeSet(FIELD, NAME='DIMS', VALUE=MAPL_DimsHorzVert, RC=STATUS)
          _VERIFY(STATUS)
          if (localIsEdge(i)) then
             call ESMF_AttributeSet(FIELD, NAME='VLOCATION', VALUE=MAPL_VLocationEdge, RC=STATUS)
             _VERIFY(STATUS)
          else
             call ESMF_AttributeSet(FIELD, NAME='VLOCATION', VALUE=MAPL_VLocationCenter, RC=STATUS)
             _VERIFY(STATUS)
          end if
       end if
       if (present(long_names)) then
          call ESMF_AttributeSet(FIELD, NAME='LONG_NAME', VALUE=long_names(i), RC=STATUS)
          _VERIFY(STATUS)
       else
          call ESMF_AttributeSet(FIELD, NAME='LONG_NAME', VALUE="UNKNOWN", RC=STATUS)
          _VERIFY(STATUS)
       end if
       if (present(units)) then
          call ESMF_AttributeSet(FIELD, NAME='LONG_NAME', VALUE=units(i), RC=STATUS)
          _VERIFY(STATUS)
       else
          call ESMF_AttributeSet(FIELD, NAME='LONG_NAME', VALUE="UNKNOWN", RC=STATUS)
          _VERIFY(STATUS)
       end if
       call MAPL_FieldBundleAdd(B, FIELD, RC=STATUS)
       _VERIFY(STATUS)
    enddo
    deallocate(localIs2D)
    deallocate(localIsEdge)
    _RETURN(ESMF_SUCCESS)
  end function MAPL_BundleCreate
Call graph
mapl_bundlecreate calls mapl_verify, esmf_fieldbundleset, esmf_fieldbundlecreate, mapl_assert, mapl_gridget, esmf_gridget, mapl_return, esmf_fieldcreate, esmf_attributeset, mapl_fieldbundleadd, mapl_bundlecreate
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls mapl_verify, esmf_gridget, mapl_return, mapl_gridhasde, esmf_attributeget
mapl_return calls mapl_throw_exception, get_error_message
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_throw_exception calls initialize
mapl_gridhasde calls mapl_verify, esmf_gridget, mapl_return, esmf_delayoutget, esmf_distgridget
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_fieldbundleaddfield calls mapl_fieldbundleaddfield, mapl_verify, mapl_return, esmf_attributeset, esmf_attributeget, esmf_fieldbundleadd, esmf_fieldget, esmf_attributeremove