MAPL_AllocNodeArray_Tiling – MAPL
MAPL_AllocNodeArray_Tiling Subroutine
22 statements
Source File
private subroutine MAPL_AllocNodeArray_Tiling(Ptr, shp, rc)
Arguments
Type Intent Optional Attributes Name
type(XTile), intent(inout), pointer :: Ptr(:)
integer, intent(in) :: shp(1)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_AllocNodeArray_Tiling
Source Code
   subroutine MAPL_AllocNodeArray_Tiling(Ptr,shp,rc)
      type(XTile), pointer, intent(inout) :: Ptr(:)
      integer,              intent(in)    :: shp(1)
      integer, optional,    intent(  out) :: rc
      integer                             :: status
      character(len=*), parameter :: Iam = 'MAPL_AllocNodeArray_Tiling'
      type(c_ptr) :: Caddr
      integer     :: len,memsize,intsize
      type(XTile) :: xdummy
      if(.not.MAPL_ShmInitialized) then
         _RETURN(MAPL_NoShm)
      endif
      ! Xtile type has 4 32-bit integers, and 1 real 4
      memsize=storage_size(xdummy)
      intsize=storage_size(1)
      len=shp(1)*(memsize/intsize)
      call GetSharedMemory(Caddr, len, rc=STATUS)
      _VERIFY(STATUS)
      call c_f_pointer(Caddr, Ptr, Shp) ! C ptr to Fortran ptr
      _RETURN(0)
   end subroutine MAPL_AllocNodeArray_Tiling
Call graph
mapl_allocnodearray_tiling calls getsharedmemory, mapl_return, mapl_verify
getsharedmemory calls getsharedmemory, mapl_return, mapl_assert, shmat, shmget, mpi_barrier, segs, segsnew
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_allocnodearray calls mapl_allocnodearray_tiling