MAPL_StateRecord – MAPL
MAPL_StateRecord Subroutine
48 statements
Source File
private subroutine MAPL_StateRecord(GC, IMPORT, EXPORT, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: IMPORT
type(ESMF_State), intent(inout) :: EXPORT
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_StateRecord
Source Code
   subroutine MAPL_StateRecord( GC, IMPORT, EXPORT, CLOCK, RC )
      ! !ARGUMENTS:
      type(ESMF_GridComp), intent(inout) :: GC     ! composite gridded component
      type(ESMF_State),    intent(inout) :: IMPORT ! import state
      type(ESMF_State),    intent(inout) :: EXPORT ! export state
      type(ESMF_Clock),    intent(inout) :: CLOCK  ! the clock
      integer, optional,   intent(  out) :: RC     ! Error code:
      ! = 0 all is well
      ! otherwise, error
      !EOPI
      ! LOCAL VARIABLES
      character(len=ESMF_MAXSTR)                  :: IAm
      character(len=ESMF_MAXSTR)                  :: comp_name
      integer                                     :: status
      type (MAPL_MetaComp), pointer               :: STATE
      integer                                     :: hdr
      character(len=ESMF_MAXSTR)                  :: FILETYPE
      type(ESMF_State), pointer :: internal_state
      !=============================================================================
      !  Begin...
      _UNUSED_DUMMY(EXPORT)
      Iam = "MAPL_StateRecord"
      call ESMF_GridCompGet(GC, name=comp_name, RC=status )
      _VERIFY(status)
      Iam = trim(comp_name) // Iam
      ! Retrieve the pointer to the state
      !----------------------------------
      call MAPL_InternalStateRetrieve(GC, STATE, RC=status)
      _VERIFY(status)
      if (.not.associated(STATE%RECORD)) then
         _RETURN(ESMF_SUCCESS)
      end if
      if (STATE%RECORD%IMP_LEN > 0) then
         call    MAPL_GetResource( STATE, FILETYPE, LABEL="IMPORT_CHECKPOINT_TYPE:",                  RC=status )
         if ( status/=ESMF_SUCCESS  .or.  FILETYPE == "default" ) then
            call MAPL_GetResource( STATE, FILETYPE, LABEL="DEFAULT_CHECKPOINT_TYPE:", default='pnc4', RC=status )
            _VERIFY(status)
         end if
         call MAPL_ESMFStateWriteToFile(IMPORT, CLOCK, &
              STATE%RECORD%IMP_FNAME, &
              FILETYPE, STATE, .FALSE., oClients = o_Clients, &
              RC=status)
         _VERIFY(status)
      end if
      if (STATE%RECORD%INT_LEN > 0) then
         call    MAPL_GetResource( STATE, hdr,      LABEL="INTERNAL_HEADER:",         default=0,      RC=status )
         _VERIFY(status)
         call    MAPL_GetResource( STATE, FILETYPE, LABEL="INTERNAL_CHECKPOINT_TYPE:",                RC=status )
         if ( status/=ESMF_SUCCESS  .or.  FILETYPE == "default" ) then
            call MAPL_GetResource( STATE, FILETYPE, LABEL="DEFAULT_CHECKPOINT_TYPE:", default='pnc4', RC=status )
            _VERIFY(status)
         end if
         internal_state => STATE%get_internal_state()
         call MAPL_ESMFStateWriteToFile(internal_state, CLOCK, &
              STATE%RECORD%INT_FNAME, &
              FILETYPE, STATE, hdr/=0, oClients = o_Clients, &
              RC=status)
         _VERIFY(status)
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_StateRecord
Call graph
mapl_staterecord calls ESMF_GridCompGet, get_internal_state, mapl_getresource, mapl_esmfstatewritetofile, mapl_internalstateretrieve, mapl_return, mapl_verify
mapl_genericrecord calls mapl_staterecord