MAPL_Skip – MAPL
MAPL_Skip Subroutine
27 statements
Source File
public subroutine MAPL_Skip(UNIT, LAYOUT, COUNT, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_DELayout), intent(in) :: LAYOUT
integer, intent(in), optional :: COUNT
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine MAPL_Skip(UNIT, LAYOUT, COUNT, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_DELayout)        , intent(IN   ) :: LAYOUT
    integer,           optional , intent(IN   ) :: COUNT
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer                               :: STATUS
    integer                               :: N, NN
    if(present(COUNT)) then
       NN=COUNT
    else
       NN=1
    endif
    if (unit < 0) then
       munit => MEM_units(-unit)
       munit%prevrec = munit%prevrec + NN
       _RETURN(ESMF_SUCCESS)
    endif
    if (MAPL_AM_I_ROOT(LAYOUT)) then
       do N=1,NN
          read (unit=UNIT, IOSTAT=status)
          _VERIFY(STATUS)
       end do
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_Skip
Call graph
mapl_skip calls mapl_am_i_root, mapl_return, mapl_verify
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_climupdate calls mapl_skip
mapl_esmfstatereadfromfile calls mapl_skip
mapl_readforcingx calls mapl_skip
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_staterefresh calls mapl_esmfstatereadfromfile
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
refresh_state calls mapl_genericstaterestore