MAPL_ServiceGetBundle – MAPL
MAPL_ServiceGetBundle Subroutine
35 statements
Source File
private subroutine MAPL_ServiceGetBundle(meta, service, bundle, provider, requester, rc)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: meta
character(len=*), intent(in) :: service
type(ESMF_FieldBundle), intent(out) :: bundle
character(len=*), intent(in), optional :: provider
character(len=*), intent(in), optional :: requester
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_ServiceGetBundle
Source Code
   subroutine MAPL_ServiceGetBundle(meta, service, bundle, provider, &
        requester, rc)
      type (MAPL_MetaComp),        intent(INOUT) :: meta
      character(len=*),            intent(IN   ) :: service
      type(ESMF_FieldBundle),      intent(  OUT) :: bundle
      character(len=*), optional,  intent(IN   ) :: provider
      character(len=*), optional,  intent(IN   ) :: requester
      integer, optional,           intent(  OUT) :: rc     ! Error code:
      integer :: status
      logical :: do_provider, do_requester
      character(len=ESMF_MAXSTR) :: cname
      type (MAPL_MetaComp), pointer :: cmeta => null()
      ! find the GC for component who's name matches P/S
      do_provider = .false.
      do_requester = .false.
      if (present(provider)) then
         do_provider = .true.
         cname = provider
      end if
      if (present(requester)) then
         do_requester = .true.
         cname = requester
      end if
      _ASSERT(do_provider .neqv. do_requester, 'Only one of the arguments PROVIDER or REQUESTER must be provided')
      call MAPL_FindChild(META, name=cname, result=cmeta, rc=status)
      _VERIFY(status)
      _ASSERT(associated(cmeta), 'No child found')
      ! find the appropriate object (P, or R) matching SERVICE
      if (do_requester) then
         call RequestedServiceGet(cmeta%requested_services, service, bundle, rc=status)
         _VERIFY(status)
      else ! must be provider
         call ProvidedServiceGet(cmeta%provided_services, service, bundle, rc=status)
         _VERIFY(status)
      end if
      ! return the saved bundle
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_ServiceGetBundle
Call graph
mapl_servicegetbundle calls mapl_assert, mapl_findchild, mapl_return, mapl_verify, providedserviceget, requestedserviceget
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_findchild calls mapl_findchild, mapl_return, mapl_verify, get_num_children, get_child_gridcomp, mapl_internalstateretrieve
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
providedserviceget calls mapl_assert, mapl_return, begin, get, next
requestedserviceget calls mapl_assert, mapl_return, begin, get
get_child_gridcomp calls get_gridcomp, get_ith_child
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_throw_exception calls initialize
get_ith_child calls gcnamelist, get_child
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_processserviceconnections calls mapl_servicegetbundle