MAPL_ExtDataReadPrefetch – MAPL
MAPL_ExtDataReadPrefetch Subroutine
15 statements
Source File
private subroutine MAPL_ExtDataReadPrefetch(IOBundles, rc)
Arguments
Type Intent Optional Attributes Name
type(IoBundleVector), intent(inout), target :: IOBundles
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataReadPrefetch(IOBundles,rc)
     type(IOBundleVector), target, intent(inout) :: IOBundles
     integer, optional,      intent(out  ) :: rc
     integer :: nfiles, n
     type (ExtData_IoBundle), pointer :: io_bundle
     integer :: status
     nfiles = IOBundles%size()
     do n=1, nfiles
        io_bundle => IOBundles%at(n)
        call io_bundle%cfio%process_data_from_file(rc=status)
        _VERIFY(status)
     enddo
     _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataReadPrefetch
Call graph
mapl_extdatareadprefetch calls at, mapl_return, mapl_verify, process_data_from_file
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
process_data_from_file calls mapl_return, mapl_verify, esmf_fieldbundledestroy, esmf_fieldbundleget, esmf_fielddestroy, regridscalar, regridvector, swap_undef_value, v_begin, v_iter_get, v_iter_next
get_error_message calls at, insert
mapl_throw_exception calls initialize
regridscalar calls mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, regrid, flip_levels, mapl_gridhasde, regrid_eta_to_pressure, regrid_select_level
regridvector calls mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldget, esmfl_fieldgetpointertodata, regrid, flip_levels, mapl_gridhasde, regrid_eta_to_pressure, regrid_select_level
swap_undef_value calls mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, mapl_gridhasde, var_get_missing_value, var_has_missing_value
v_at_32 calls v_at_size_kind
run_ calls mapl_extdatareadprefetch