MAPL_StateAddField – MAPL
MAPL_StateAddField Module Subroutine
47 statements
Source File
module subroutine MAPL_StateAddField(State, Field, rc) Interface →
!ALT Example to add one field at the time (not used anymore) ! call ESMF_StateAdd(STATE, FIELD, proxyflag=.false., & ! addflag=.true., replaceflag=.false., RC=STATUS)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: State
type(ESMF_Field), intent(in) :: Field
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
MAPL_StateAddField
Source Code
  module subroutine MAPL_StateAddField(State, Field, RC)
    type(ESMF_State),  intent(inout) :: State
    type(ESMF_Field),  intent(in   ) :: Field
    integer, optional, intent(  out) :: rc
    ! ErrLog vars
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_StateAddField"
    integer                               :: STATUS
    ! Local var
    character(len=ESMF_MAXSTR), parameter   :: attrName = MAPL_StateItemOrderList
    character(len=ESMF_MAXSTR)              :: name
    character(len=ESMF_MAXSTR), allocatable :: currList(:)
    character(len=ESMF_MAXSTR), allocatable :: thisList(:)
    integer                                 :: natt
    integer                                 :: na
    type(ESMF_Field)                        :: Fields(1)
    logical                                 :: haveAttr
    fields(1) = field
    call ESMF_StateAdd(state, fields, RC=status)
    _VERIFY(STATUS)
    !=================
!!!ALT Example to add one field at the time (not used anymore)
!!!      call ESMF_StateAdd(STATE, FIELD, proxyflag=.false., &
!!!           addflag=.true., replaceflag=.false., RC=STATUS)
    !=================
    ! check for attribute
    call ESMF_AttributeGet(state, NAME=attrName, isPresent=haveAttr, RC=STATUS)
    _VERIFY(STATUS)
    if (haveAttr) then
       call ESMF_AttributeGet(state, NAME=attrName, itemcount=natt, RC=STATUS)
       _VERIFY(STATUS)
    else
       natt = 0
    end if
    allocate(currList(natt), stat=status)
    _VERIFY(STATUS)
    if (natt > 0) then
       ! get the current list
       call ESMF_AttributeGet(state, NAME=attrName, VALUELIST=currList, rc=status)
       _VERIFY(STATUS)
       !ALT delete/destroy this attribute to prevent memory leaks
       call ESMF_AttributeRemove(state, NAME=attrName, rc=status)
       _VERIFY(STATUS)
    end if
    na = natt+1
    allocate(thisList(na), stat=status)
    _VERIFY(STATUS)
    thisList(1:natt) = currList
    call ESMF_FieldGet(field, name=name, rc=status)
    _VERIFY(STATUS)
    thisList(na) = name
    call ESMF_AttributeSet(state, NAME=attrName, itemcount=na, VALUELIST=thisList, rc=status)
    _VERIFY(STATUS)
    deallocate(thisList)
    deallocate(currList)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_StateAddField
Call graph
mapl_stateaddfield calls ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldget, esmf_stateadd, mapl_return, mapl_verify, mapl_stateaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_stateadd calls mapl_stateaddfield
bundle2state calls mapl_stateadd
create_holding_field calls mapl_stateadd
create_primary_field calls mapl_stateadd
initialize calls mapl_stateadd
initialize_ calls mapl_stateadd, create_holding_field, create_primary_field
initialize_extdata calls mapl_stateadd
initialize_gc calls mapl_stateadd, initialize_extdata
mapl_statecreatefromspecnew calls mapl_stateadd
esmfl_bundle2state calls bundle2state
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statecreatefromvarspecnew calls mapl_statecreatefromspecnew