MAPL_LocStreamTransformT2TR8R4 – MAPL
MAPL_LocStreamTransformT2TR8R4 Subroutine
17 statements
Source File
private subroutine MAPL_LocStreamTransformT2TR8R4(OUTPUT, XFORM, INPUT, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: OUTPUT(:)
type(MAPL_LocStreamXform), intent(in) :: XFORM
real(kind=ESMF_KIND_R8), intent(in) :: INPUT(:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
subroutine MAPL_LocStreamTransformT2TR8R4 (OUTPUT, XFORM, INPUT, RC)
  !ARGUMENTS:
  real,                      intent(OUT) :: OUTPUT(:)
  type(MAPL_LocStreamXform), intent(IN ) :: XFORM
  real(kind=ESMF_KIND_R8),   intent(IN ) :: INPUT(:)
  integer, optional,         intent(OUT) :: RC
  !EOPI
! Local variables
  integer                     :: STATUS
#ifdef OLD_RUN
  integer                     :: N
  real(kind=ESMF_KIND_R8),  allocatable  :: FULLINPUT(:)
  _ASSERT(associated(Xform%PTR),'needs informative message')
  do N = 1,Xform%PTR%LastLocal
     OUTPUT(Xform%PTR%IndexOut(N)) = real(INPUT(Xform%PTR%IndexIn(N)))
  end do
  if(.not.Xform%PTR%Local) then
     allocate(FULLINPUT(Xform%Ptr%InputStream%Ptr%NT_GLOBAL),STAT=STATUS)
     _VERIFY(STATUS)
     call ESMFL_FCOLLECT(Xform%Ptr%InputStream%Ptr%TILEGRID, FULLINPUT, INPUT, RC=STATUS)
     _VERIFY(STATUS)
     do N = Xform%PTR%LastLocal+1,Xform%PTR%Count
        OUTPUT(Xform%PTR%IndexOut(N)) = FULLINPUT(Xform%PTR%IndexIn(N))
     end do
     deallocate(FULLINPUT)
  end if
#else
  real,   allocatable         :: INPUTR4(:)
  integer                     :: INPUTSIZE
  INPUTSIZE = size(INPUT)
  allocate(INPUTR4(INPUTSIZE),STAT=STATUS)
  _VERIFY(STATUS)
  INPUTR4 = INPUT
  call MAPL_LocStreamTransformT2T( OUTPUT, XFORM, INPUTR4, RC )
  deallocate(INPUTR4)
#endif
  _RETURN(ESMF_SUCCESS)
end subroutine MAPL_LocStreamTransformT2TR8R4
Call graph
mapl_locstreamtransformt2tr8r4 calls mapl_locstreamtransformt2t, mapl_return, mapl_verify
mapl_locstreamtransformt2t calls mapl_return, mapl_verify, esmfl_fcollect, mapl_assert, mpi_isend, mpi_recv, mpi_wait
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_fcollect calls esmfl_fcollect_i4, esmfl_fcollect_r4, esmfl_fcollect_r8
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
esmfl_fcollect_i4 calls mapl_return, mapl_verify, mapl_assert, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_commsallgatherv, mapl_distgridget
esmfl_fcollect_r4 calls mapl_return, mapl_verify, mapl_assert, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_commsallgatherv, mapl_distgridget
esmfl_fcollect_r8 calls mapl_return, mapl_verify, mapl_assert, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet, ESMF_VMGet, mapl_commsallgatherv, mapl_distgridget
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_locstreamtransform calls mapl_locstreamtransformt2tr8r4
mapl_readforcingx calls mapl_locstreamtransform
regridtransform calls mapl_locstreamtransform
regridtransformt2g calls mapl_locstreamtransform
regridtransformt2g2g calls mapl_locstreamtransform
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
run calls regridtransform, regridtransformt2g, regridtransformt2g2g
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2