MAPL_CFIOCreatewrite – MAPL
MAPL_CFIOCreatewrite Subroutine
56 statements
Source File
public subroutine MAPL_CFIOCreatewrite(MCFIO, nsteps, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_CFIO), intent(inout) :: MCFIO
integer, intent(in), optional :: nsteps
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_CFIOCreatewrite
Source Code
  subroutine MAPL_CFIOCreatewrite ( MCFIO, nsteps, RC )
    type(MAPL_CFIO),           intent(INOUT) :: MCFIO
    integer,         optional, intent(   IN) :: nsteps
    integer,         optional, intent(  OUT) :: RC
    type(ESMF_Time)                :: CurrTime
    type(ESMF_Alarm)               :: PERPETUAL
    character(len=ESMF_MAXSTR)     :: StartTime
    character(len=ESMF_MAXSTR)     :: ClockName
    logical                        :: LPERP
    integer                        :: YY,MM,DD,H,M,S
    integer                        :: noffset
    integer                        :: STATUS
    if(present(nsteps)) then
       call ESMF_CFIOSet(MCFIO%CFIO, nsteps=nsteps, RC=STATUS)
       _VERIFY(STATUS)
    else
       call ESMF_CFIOSet(MCFIO%CFIO, nsteps=1, RC=STATUS)
       _VERIFY(STATUS)
    endif
! Get time info from the clock. Note the optional offset
!-------------------------------------------------------
    call ESMF_ClockGet(mCFIO%CLOCK, name=clockname, CurrTime=CurrTime, RC=STATUS)
    _VERIFY(STATUS)
        call ESMF_TimeIntervalGet( mCFIO%OFFSET, S=noffset, rc=status )
        _VERIFY(STATUS)
        if( noffset /= 0 ) then
            LPERP = ( index( trim(clockname),'_PERPETUAL' ).ne.0 )
        if( LPERP ) then
            call ESMF_ClockGetAlarm ( mCFIO%CLOCK, alarmName='PERPETUAL', alarm=PERPETUAL, rc=status )
            _VERIFY(STATUS)
            if( ESMF_AlarmIsRinging(PERPETUAL) ) then
                call ESMF_TimeGet ( CurrTime, YY = YY, &
                                              MM = MM, &
                                              DD = DD, &
                                              H  = H , &
                                              M  = M , &
                                              S  = S, rc=status )
                                              MM = MM + 1
                call ESMF_TimeSet ( CurrTime, YY = YY, &
                                              MM = MM, &
                                              DD = DD, &
                                              H  = H , &
                                              M  = M , &
                                              S  = S, rc=status )
            endif
        endif
        endif
    CurrTime = CurrTime - mCFIO%OFFSET
    call ESMF_TimeGet (CurrTime,  timeString=StartTime, RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_CFIOSet(MCFIO%CFIO, TimeString=trim(StartTime), RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_CFIOSet(MCFIO%CFIO, fName=trim(mCFIO%fName),     RC=STATUS)
    _VERIFY(STATUS)
    if (MCFIO%JM == 6 * MCFIO%IM) then
       if (MCFIO%newFormat) then
          call ESMF_CFIOSet(MCFIO%CFIO, formatVersion=2.90, RC=STATUS)
          _VERIFY(STATUS)
          MCFIO%useFaceDim = .true.
       end if
    end if
! Create FILE from the root of the partition working on this bundle.
!------------------------------------------------------------------
    AMROOT: if (mCFIO%MYPE==mCFIO%RootRank) then
       call ESMF_CFIOFileCreate(MCFIO%CFIO, format=MCFIO%format, &
                                expid=MCFIO%EXPID,      RC=STATUS)
       _VERIFY(STATUS)
!      print *, ' Created CFIO File: ', trim(mCFIO%fName)
    end if AMROOT
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CFIOCreateWrite
Call graph
mapl_cfiocreatewrite calls esmf_cfioset, esmf_clockget, esmf_clockgetalarm, mapl_verify, esmf_timeintervalget, esmf_alarmisringing, esmf_timeget, esmf_timeset, esmf_cfiofilecreate, mapl_return
esmf_cfioset calls strtoint, err, addlist
mapl_verify calls mapl_throw_exception
esmf_cfiofilecreate calls esmf_cfioset, esmf_utilstringuppercase, esmf_cfiosdffilecreate
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
esmf_cfiosdffilecreate calls esmf_cfioset, err, cfio_putcharatt, cfio_create_, esmf_cfioget, strtemplate_, getlist, cfio_putintatt, cfio_putrealatt
mapl_cfiowritebundle calls mapl_cfiocreatewrite
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_simplebundlewrite1 calls mapl_cfiowrite
test_main calls esmf_iowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
mapl_simplebundlewrite calls mapl_simplebundlewrite1, mapl_simplebundlewrite2
utcfio calls test_main