MAPL_CommFree – MAPL
MAPL_CommFree Subroutine
12 statements
Source File
private subroutine MAPL_CommFree(comm, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: comm
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_CommFree(comm, rc)
    integer, intent(inout) :: comm
    integer, optional, intent(out) :: rc
    integer :: status
    if(comm /= MPI_COMM_NULL) then
       call MPI_Comm_Free(comm, status)
       _VERIFY(status)
       comm = MPI_COMM_NULL
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_CommFree
Call graph
mapl_commfree calls mpi_comm_free, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
arrdescrcommfree calls mapl_commfree
mapl_esmfstatereadfromfile calls arrdescrcommfree
mapl_esmfstatewritetofile calls arrdescrcommfree
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore