MAPL_ReadForcing2 – MAPL
MAPL_ReadForcing2 Subroutine
13 statements
Source File
private subroutine MAPL_ReadForcing2(STATE, NAME, DATAFILE, CURRENTTIME, FORCING, INIT_ONLY, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
character(len=*), intent(in) :: NAME
character(len=*), intent(in) :: DATAFILE
type(ESMF_Time), intent(inout) :: CURRENTTIME
real, intent(out) :: FORCING(:,:)
logical, intent(in), optional :: INIT_ONLY
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_ReadForcing2
Source Code
   subroutine MAPL_ReadForcing2(STATE,NAME,DATAFILE,CURRENTTIME,    &
        FORCING,INIT_ONLY,RC )
      !ARGUMENTS:
      type (MAPL_MetaComp),     intent(INOUT)   :: STATE
      character(len=*),         intent(IN   )   :: NAME
      character(len=*),         intent(IN   )   :: DATAFILE
      type (ESMF_Time),         intent(INout)   :: CURRENTTIME
      real,                     intent(  OUT)   :: FORCING(:,:)
      logical, optional,        intent(IN   )   :: INIT_ONLY
      integer, optional,        intent(  OUT)   :: RC
      !EOPI
      integer                           :: status
      call MAPL_ReadForcingX(STATE,NAME,DATAFILE,CURRENTTIME,      &
           FORCING2=FORCING,INIT_ONLY=INIT_ONLY, &
           ON_TILES=.FALSE.,                     &
           RC=status )
      _RETURN(status)
   end subroutine MAPL_ReadForcing2
Call graph
mapl_readforcing2 calls mapl_readforcingx, mapl_return
mapl_readforcingx calls mapl_return, ESMF_TimeGet, ESMF_TimeSet, esmf_stateget, esmfl_stategetpointertodata, mapl_am_i_root, mapl_assert, mapl_interp_fac, mapl_varspecgetindex, read_parallel, getfile, mapl_backspace, mapl_genericstateget, mapl_getnumsubtiles, mapl_locstreamget, mapl_statecreatefromvarspecnew, mapl_stategetspecattrib, mapl_stategettimestamp, mapl_varspeccreateinlistnew, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_readforcing calls mapl_readforcing2