MAPL_GridGetCorners – MAPL
MAPL_GridGetCorners Module Subroutine
105 statements
Source File
module subroutine MAPL_GridGetCorners(GRID, gridCornerLons, gridCornerLats, RC) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(inout) :: gridCornerLons(:,:)
real(kind=ESMF_KIND_R8), intent(inout) :: gridCornerLats(:,:)
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  module subroutine MAPL_GridGetCorners(grid,gridCornerLons, gridCornerLats, RC)
    type (ESMF_Grid), intent(INOUT) :: GRID
    real(ESMF_KIND_R8), intent(INOUT) :: gridCornerLons(:,:)
    real(ESMF_KIND_R8), intent(INOUT) :: gridCornerLats(:,:)
    integer, optional, intent(  OUT) :: RC
    integer :: status
    type(ESMF_RouteHandle) :: rh
    type(ESMF_Field) :: field
    integer :: counts(3),lsz
    real(ESMF_KIND_R8), pointer :: ptr(:,:)
    real(ESMF_KIND_R8), pointer :: corner(:,:)
    integer :: im,jm,imc,jmc,idx,i,j
    logical :: hasLons,hasLats
    real(ESMF_KIND_R8), allocatable :: r8ptr(:),lons1d(:),lats1d(:)
    type(ESMF_CoordSys_Flag) :: coordSys
    call MAPL_GridGet(grid,localCellCountPerDim=counts,rc=status)
    _VERIFY(status)
    im=counts(1)
    jm=counts(2)
    ! check if we have corners
    call ESMF_AttributeGet(grid,  NAME='GridCornerLons:', &
         isPresent=hasLons, RC=STATUS)
    _VERIFY(status)
    call ESMF_AttributeGet(grid,  NAME='GridCornerLats:', &
         isPresent=hasLats, RC=STATUS)
    _VERIFY(status)
    if (hasLons .and. hasLats) then
       call ESMF_AttributeGet(grid,  NAME='GridCornerLons:', &
            itemcount=lsz, RC=STATUS)
       _VERIFY(STATUS)
       _ASSERT(size(gridCornerLons,1)*size(gridCornerLons,2)==lsz,"stored corner sizes to not match grid")
       call ESMF_AttributeGet(grid,  NAME='GridCornerLats:', &
            itemcount=lsz, RC=STATUS)
       _VERIFY(STATUS)
       _ASSERT(size(gridCornerLats,1)*size(gridCornerLats,2)==lsz,"stored corner sizes to not match grid")
       allocate(r8ptr(lsz),stat=status)
       _VERIFY(status)
       call ESMF_AttributeGet(grid,  NAME='GridCornerLons:', &
            VALUELIST=r8ptr, RC=STATUS)
       _VERIFY(STATUS)
       idx = 0
       do j = 1, size(gridCornerLons,2)
          do i = 1, size(gridCornerLons,1)
             idx = idx+1
             gridCornerLons(i,j) = r8ptr(idx)
          end do
       end do
       call ESMF_AttributeGet(grid,  NAME='GridCornerLats:', &
            VALUELIST=r8ptr, RC=STATUS)
       _VERIFY(STATUS)
       idx = 0
       do j = 1, size(gridCornerLons,2)
          do i = 1, size(gridCornerLons,1)
             idx = idx+1
             gridCornerLats(i,j) = r8ptr(idx)
          end do
       end do
       deallocate(r8ptr)
    else
       call ESMF_GridGetCoord(grid,localDE=0,coordDim=1,staggerloc=ESMF_STAGGERLOC_CORNER, &
            farrayPtr=corner, rc=status)
       imc=size(corner,1)
       jmc=size(corner,2)
       allocate(ptr(0:imc+1,0:jmc+1),source=0.0d0,stat=status)
       _VERIFY(status)
       field = ESMF_FieldCreate(grid,ptr,staggerLoc=ESMF_STAGGERLOC_CORNER,totalLWidth=[1,1],totalUWidth=[1,1],rc=status)
       _VERIFY(status)
       call ESMF_FieldHaloStore(field,rh,rc=status)
       _VERIFY(status)
       ptr(1:imc,1:jmc)=corner
       call ESMF_FieldHalo(field,rh,rc=status)
       _VERIFY(status)
       gridCornerLons=ptr(1:im+1,1:jm+1)
       call ESMF_GridGetCoord(grid,localDE=0,coordDim=2,staggerloc=ESMF_STAGGERLOC_CORNER, &
            farrayPtr=corner, rc=status)
       _VERIFY(status)
       ptr(1:imc,1:jmc)=corner
       call ESMF_FieldHalo(field,rh,rc=status)
       _VERIFY(status)
       gridCornerLats=ptr(1:im+1,1:jm+1)
       deallocate(ptr)
       call ESMF_FieldDestroy(field,rc=status)
       _VERIFY(status)
       call ESMF_FieldHaloRelease(rh,rc=status)
       _VERIFY(status)
       call ESMF_GridGet(grid,coordSys=coordSys,rc=status)
       _VERIFY(status)
       if (coordSys==ESMF_COORDSYS_SPH_DEG) then
          gridCornerLons=gridCornerLons*MAPL_DEGREES_TO_RADIANS_R8
          gridCornerLats=gridCornerLats*MAPL_DEGREES_TO_RADIANS_R8
       else if (coordSys==ESMF_COORDSYS_CART) then
          _FAIL('Unsupported coordinate system:  ESMF_COORDSYS_CART')
       end if
       allocate(lons1d(size(gridCornerLons,1)*size(gridCornerLons,2)),stat=status)
       _VERIFY(status)
       allocate(lats1d(size(gridCornerLons,1)*size(gridCornerLons,2)),stat=status)
       _VERIFY(status)
       idx = 0
       do j=1,size(gridCornerLons,2)
          do i=1,size(gridCornerLons,1)
             idx=idx+1
             lons1d(idx)=gridCornerLons(i,j)
             lats1d(idx)=gridCornerLats(i,j)
          enddo
       enddo
       call ESMF_AttributeSet(grid, name='GridCornerLons:', &
            itemCount = idx, valueList=lons1d, rc=status)
       _VERIFY(STATUS)
       call ESMF_AttributeSet(grid, name='GridCornerLats:', &
            itemCount = idx, valueList=lats1d, rc=status)
       _VERIFY(STATUS)
       deallocate(lons1d,lats1d)
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_GridGetCorners
Call graph
mapl_gridgetcorners calls ESMF_AttributeGet, ESMF_AttributeSet, ESMF_FieldHalo, ESMF_FieldHaloRelease, ESMF_FieldHaloStore, ESMF_GridGet, ESMF_GridGetCoord, esmf_fieldcreate, esmf_fielddestroy, mapl_assert, mapl_gridget, mapl_return, mapl_verify, mapl_gridgetcorners
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridget calls ESMF_AttributeGet, ESMF_GridGet, mapl_return, mapl_verify, mapl_gridhasde
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls ESMF_GridGet, mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet
mapl_throw_exception calls initialize
computegridbasis calls mapl_gridgetcorners
initialize_ calls mapl_gridgetcorners
make_subgrids_from_bounds calls mapl_gridgetcorners
mapl_getglobalhorzijindex calls mapl_gridgetcorners, mapl_getglobalhorzijindex
mapl_gethorzijindex calls mapl_gridgetcorners, mapl_gethorzijindex
make_subgrids calls make_subgrids_from_bounds
get_basis calls computegridbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
create_subobjects calls make_subgrids
make_subfields_from_num_grids calls make_subgrids
make_subgrids_from_num_grids calls make_subgrids
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis