MAPL_FieldBundleAddField – MAPL
MAPL_FieldBundleAddField Module Subroutine
48 statements
Source File
module subroutine MAPL_FieldBundleAddField(Bundle, Field, multiflag, rc) Interface →
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: Bundle
type(ESMF_Field), intent(in) :: Field
logical, intent(in), optional :: multiflag
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  module subroutine MAPL_FieldBundleAddField(Bundle, Field, multiflag, RC)
    type(ESMF_FieldBundle),  intent(inout) :: Bundle
    type(ESMF_Field),  intent(in   ) :: Field
    logical, optional, intent(in   ) :: multiflag
    integer, optional, intent(  out) :: rc
    ! ErrLog vars
    character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_FieldBundleAddField"
    integer                               :: STATUS
    ! Local var
    character(len=ESMF_MAXSTR), parameter   :: attrName = MAPL_BundleItemOrderList
    character(len=ESMF_MAXSTR)              :: name
    character(len=ESMF_MAXSTR), allocatable :: currList(:)
    character(len=ESMF_MAXSTR), allocatable :: thisList(:)
    integer                                 :: natt
    integer                                 :: na
    type(ESMF_Field)                        :: Fields(1)
    logical                                 :: haveAttr
    fields(1) = field
    call ESMF_FieldBundleAdd(Bundle, fields, multiflag=multiflag, RC=status)
    _VERIFY(STATUS)
    ! check for attribute
    call ESMF_AttributeGet(Bundle, NAME=attrName, isPresent=haveAttr, RC=STATUS)
    _VERIFY(STATUS)
    if (haveAttr) then
       call ESMF_AttributeGet(Bundle, NAME=attrName, itemcount=natt, RC=STATUS)
       _VERIFY(STATUS)
    else
       natt = 0
    end if
    allocate(currList(natt), stat=status)
    _VERIFY(STATUS)
    if (natt > 0) then
       ! get the current list
       call ESMF_AttributeGet(Bundle, NAME=attrName, VALUELIST=currList, rc=status)
       _VERIFY(STATUS)
       !ALT delete/destroy this attribute to prevent memory leaks
       call ESMF_AttributeRemove(bundle, NAME=attrName, rc=status)
       _VERIFY(STATUS)
    end if
    na = natt+1
    allocate(thisList(na), stat=status)
    _VERIFY(STATUS)
    thisList(1:natt) = currList
    call ESMF_FieldGet(field, name=name, rc=status)
    _VERIFY(STATUS)
    thisList(na) = name
    call ESMF_AttributeSet(bundle, NAME=attrName, itemcount=na, VALUELIST=thisList, rc=status)
    _VERIFY(STATUS)
    deallocate(thisList)
    deallocate(currList)
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_FieldBundleAddField
Call graph
mapl_fieldbundleaddfield calls ESMF_AttributeGet, ESMF_AttributeRemove, ESMF_AttributeSet, esmf_fieldbundleadd, esmf_fieldget, mapl_return, mapl_verify, mapl_fieldbundleaddfield
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
add2bundle calls mapl_fieldbundleadd
add_new_field_to_bundle calls mapl_fieldbundleadd
bundleaddstate_ calls mapl_fieldbundleadd
bundles2bundle calls mapl_fieldbundleadd
copy_bundle_to_bundle calls mapl_fieldbundleadd
create_new_bundle calls mapl_fieldbundleadd
createvariable calls mapl_fieldbundleadd
esmfl_bundlecpyfield calls mapl_fieldbundleadd
esmfl_stategetfield calls mapl_fieldbundleadd
initialize calls mapl_fieldbundleadd
initialize_ calls mapl_fieldbundleadd
mapl_arrayreadncpar_1d calls mapl_fieldbundleadd
mapl_arrayreadncpar_2d calls mapl_fieldbundleadd
mapl_arrayreadncpar_3d calls mapl_fieldbundleadd
mapl_bundlecreate calls mapl_fieldbundleadd
mapl_bundleinit calls mapl_fieldbundleadd
mapl_cfiocreatefromfile calls mapl_fieldbundleadd
mapl_cfioreadbundle calls mapl_fieldbundleadd
mapl_cfioreadfield calls mapl_fieldbundleadd
mapl_create_bundle_from_metdata_id calls mapl_fieldbundleadd
mapl_extdatapopulatebundle calls mapl_fieldbundleadd
mapl_processserviceconnections calls mapl_fieldbundleadd
mapl_statevarreadncpar calls mapl_fieldbundleadd
mapl_statevarwritencpar calls mapl_fieldbundleadd
putfieldinbundle__ calls mapl_fieldbundleadd
state2bundle calls mapl_fieldbundleadd
time_ave calls mapl_fieldbundleadd
ut_regridding calls mapl_fieldbundleadd