MAPL_GenericRunCouplers – MAPL
MAPL_GenericRunCouplers Subroutine
23 statements
Source File
public subroutine MAPL_GenericRunCouplers(STATE, CHILD, CLOCK, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_MetaComp), intent(inout) :: STATE
integer, intent(in) :: CHILD
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out), optional :: RC
Calls
Source Code
   subroutine MAPL_GenericRunCouplers( STATE, CHILD, CLOCK, RC )
      !ARGUMENTS:
      type (MAPL_MetaComp),    intent(INOUT) :: STATE
      integer,                 intent(IN   ) :: CHILD  ! Child Id
      type(ESMF_Clock),        intent(INOUT) :: CLOCK  ! The clock
      integer, optional,       intent(  OUT) :: RC     ! Error code
      !EOPI
      ! ErrLog Variables
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_GenericRunCouplers"
      integer                               :: status
      integer                               :: userRC
      integer                               :: J
      type(ESMF_State), pointer :: child_import_state
      type(ESMF_State), pointer :: child_export_state
      do J=1,STATE%get_num_children()
         if(STATE%CCcreated(CHILD,J)) then
            child_export_state => STATE%get_child_export_state(child)
            child_import_state => STATE%get_child_import_state(j)
            call ESMF_CplCompRun (STATE%CCS(CHILD,J), &
                 importState=child_export_state, &
                 exportState=child_import_state, &
                 clock=CLOCK, userRC=userRC, _RC )
            _VERIFY(userRC)
         endif
      enddo
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_GenericRunCouplers
Call graph
mapl_genericruncouplers calls ESMF_CplCompRun, get_child_export_state, get_child_import_state, get_num_children, mapl_return, mapl_verify
get_child_export_state calls get_export_state, get_ith_child
get_child_import_state calls get_import_state, get_ith_child
get_num_children calls get_num_children
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_export_state calls get_current_thread, is_threading_active
get_import_state calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_throw_exception calls initialize