MAPL_DeAlloc_R_2D – MAPL
MAPL_DeAlloc_R_2D Subroutine
38 statements
Source File
private subroutine MAPL_DeAlloc_R_2D(A, RC)
Arguments
Type Intent Optional Attributes Name
real, pointer :: A(:,:)
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_DeAlloc_R_2D
Source Code
    subroutine MAPL_DeAlloc_R_2D(A, RC)
      real, pointer                  :: A(:,:)
      integer, optional, intent(OUT) :: RC
      interface ival2
         integer(kind=INT64) function ival2(Ptr)
            use, intrinsic :: iso_fortran_env, only: INT64
           real, pointer :: Ptr(:,:)
         end function ival2
      end interface
      interface ival1
         integer(kind=INT64) function ival1(Ptr)
            use, intrinsic :: iso_fortran_env, only: INT64
           real, pointer :: Ptr(:)
         end function ival1
      end interface
      integer :: i
! Look for the pointer in the list of allocated segments
!-------------------------------------------------------
      i = 1
      do while ( ival2(a) /= ival1(heap%ptrs(i)%a) )
         i = i+1
         if(i==NumSegments) then
            print *, 'MAPL_DeAlloc: Bad Pointer'
            _FAIL('needs informative message')
         end if
      end do
! I is the segment to be freed. If it is not the last one,
! move up all segments below it.
!---------------------------------------------------------
      do while (heap%HP_start(i+1) /= -1)
         heap%HP_start(i) = heap%HP_start(i+1)
         heap%HP_end  (i) = heap%HP_end  (i+1)
         i = i+1
         if(i==NumSegments-1) then
            print *, 'MAPL_DeAlloc: Something wrong. Missed bottom mark'
            _FAIL('needs informative message')
         end if
      end do
! Mark bottom segment as free
!----------------------------
      heap%HP_start(I) = -1
      heap%HP_end  (I) = -1
      _RETURN(_SUCCESS)
    end subroutine MAPL_DeAlloc_R_2D
Call graph
mapl_dealloc_r_2d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_dealloc calls mapl_dealloc_r_2d