MAPL_CommsBcastVm_I4_0 – MAPL
MAPL_CommsBcastVm_I4_0 Subroutine
16 statements
Source File
private subroutine MAPL_CommsBcastVm_I4_0(vm, data, N, ROOT, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_VM) :: vm
integer(kind=ESMF_KIND_I4), intent(inout) :: data
integer, intent(in) :: N
integer, intent(in) :: ROOT
integer, intent(out), optional :: RC
Calls
Called by
Call graph
mapl_commsbcastvm_i4_0 calls ESMF_VMGet, mpi_bcast, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_commsbcast calls mapl_commsbcastvm_i4_0