MAPL_ExtDataGetBracket – MAPL
MAPL_ExtDataGetBracket Subroutine
103 statements
Source File
private subroutine MAPL_ExtDataGetBracket(item, bside, field, bundle, getRL, vcomp, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
integer, intent(in) :: bside
type(ESMF_Field), intent(inout), optional :: field
type(ESMF_FieldBundle), intent(inout), optional :: bundle
logical, intent(in), optional :: getRL
integer, intent(in), optional :: vcomp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataGetBracket(item,Bside,field,bundle,getRL,vcomp,rc)
     type(PrimaryExport),              intent(inout) :: item
     integer,                          intent(in   ) :: bside
     type(ESMF_Field),       optional, intent(inout) :: field
     type(ESMF_FieldBundle), optional, intent(inout) :: bundle
     logical,                optional, intent(in   ) :: getRL
     integer,                optional, intent(in   ) :: vcomp
     integer,                optional, intent(out  ) :: rc
     integer :: status
     logical :: getRL_
     if (present(getRL)) then
        getRL_=getRL
     else
        getRL_=.false.
     end if
     if (present(vcomp)) then
        if (present(field)) then
           if (Bside == MAPL_ExtDataLeft .and. vcomp == 1) then
              if (getRL_) then
                 call item%modelGridFields%auxiliary1%get_parameters('L',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              else
                 call item%modelGridFields%comp1%get_parameters('L',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              end if
           else if (Bside == MAPL_ExtDataLeft .and. vcomp == 2) then
              if (getRL_) then
                 call item%modelGridFields%auxiliary2%get_parameters('L',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              else
                 call item%modelGridFields%comp2%get_parameters('L',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              end if
           else if (Bside == MAPL_ExtDataRight .and. vcomp == 1) then
              if (getRL_) then
                 call item%modelGridFields%auxiliary1%get_parameters('R',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              else
                 call item%modelGridFields%comp1%get_parameters('R',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              end if
           else if (Bside == MAPL_ExtDataRight .and. vcomp == 2) then
              if (getRL_) then
                 call item%modelGridFields%auxiliary2%get_parameters('R',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              else
                 call item%modelGridFields%comp2%get_parameters('R',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              end if
           end if
        else if (present(bundle)) then
           _RETURN(ESMF_FAILURE)
        end if
     else
        if (present(field)) then
           if (Bside == MAPL_ExtDataLeft) then
              if (getRL_) then
                 call item%modelGridFields%auxiliary1%get_parameters('L',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              else
                 call item%modelGridFields%comp1%get_parameters('L',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              end if
           else if (Bside == MAPL_ExtDataRight) then
              if (getRL_) then
                 call item%modelGridFields%auxiliary1%get_parameters('R',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              else
                 call item%modelGridFields%comp1%get_parameters('R',field=field,_RC)
                 _RETURN(ESMF_SUCCESS)
              end if
           end if
        else if (present(bundle)) then
           !if (Bside == MAPL_ExtDataLeft) then
              !bundle = item%binterp1
              !_RETURN(ESMF_SUCCESS)
           !else if (Bside == MAPL_ExtDataRight) then
              !bundle = item%binterp2
              !_RETURN(ESMF_SUCCESS)
           !end if
        end if
     end if
     _RETURN(ESMF_FAILURE)
  end subroutine MAPL_ExtDataGetBracket
Call graph
mapl_extdatagetbracket calls get_parameters, mapl_return, mapl_verify
get_parameters calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_extdataflipvertical calls mapl_extdatagetbracket
mapl_extdatapopulatebundle calls mapl_extdatagetbracket
mapl_extdataverticalinterpolate calls mapl_extdatagetbracket, mapl_extdataflipvertical
run_ calls mapl_extdatapopulatebundle, mapl_extdataverticalinterpolate