MAPL_VarSpecGetDataByName – MAPL
MAPL_VarSpecGetDataByName Subroutine
24 statements
Source File
private subroutine MAPL_VarSpecGetDataByName(SPEC, NAME, PTR1, PTR2, PTR3, RC)
Arguments
Type Intent Optional Attributes Name
type(MAPL_VarSpec), intent(inout) :: SPEC(:)
character(len=*), intent(in) :: NAME
real, optional, pointer :: PTR1(:)
real, optional, pointer :: PTR2(:,:)
real, optional, pointer :: PTR3(:,:,:)
integer, intent(out), optional :: RC
Calls
Contents
Source Code
MAPL_VarSpecGetDataByName
Source Code
   subroutine MAPL_VarSpecGetDataByName(SPEC, NAME, PTR1, PTR2, PTR3, RC)
      type (MAPL_VarSpec )            , intent(INout):: SPEC(:)
      character (len=*)               , intent(IN)   :: NAME
      real,    optional, pointer                     :: PTR1(:)
      real,    optional, pointer                     :: PTR2(:,:)
      real,    optional, pointer                     :: PTR3(:,:,:)
      integer, optional               , intent(OUT)  :: RC
      integer :: STATUS
      integer :: I
      do I = 1, size(SPEC)
         if(.not.associated(SPEC(I)%SPECPtr)) then
            _RETURN(ESMF_FAILURE)
         endif
         if (trim(SPEC(I)%SPECPtr%SHORT_NAME) == trim(NAME)) then
            call MAPL_VarSpecGetData(SPEC(I),PTR1,PTR2,PTR3,RC=STATUS)
            _VERIFY(STATUS)
            _RETURN(ESMF_SUCCESS)
         endif
      enddo
      _RETURN(ESMF_FAILURE)
   end subroutine MAPL_VarSpecGetDataByName
Call graph
mapl_varspecgetdatabyname calls mapl_return, mapl_varspecgetdata, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_varspecgetdata calls mapl_return, mapl_verify, esmf_arrayget, esmf_fieldget, mapl_assert
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception