MAPL_ExtDataGetFStartTime – MAPL
MAPL_ExtDataGetFStartTime Function
18 statements
Source File
private function MAPL_ExtDataGetFStartTime(item, fname, rc) result(stime)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(in) :: item
character(len=*), intent(in) :: fname
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Called by
Contents
Source Code
MAPL_ExtDataGetFStartTime
Source Code
  function MAPL_ExtDataGetFStartTime(item,fname, rc) result(stime)
     type(PrimaryExport), intent(in) :: item
     character(len=*), intent(in   ) :: fname
     integer, optional, intent(out  ) :: rc
     type(ESMF_Time) :: stime
     integer                               :: status
     integer :: iyr,imm,idd,ihr,imn,isc
     type(FileMetadataUtils), pointer :: metadata => null()
     call MakeMetadata(fname,item%pfiocollection_id,metadata,_RC)
     call Metadata%get_time_info(startyear=iyr,startmonth=imm,startday=idd,starthour=ihr,startmin=imn,startsec=isc,rc=status)
     _VERIFY(status)
     call ESMF_TimeSet(sTime, yy=iyr, mm=imm, dd=idd,  h=ihr,  m=imn, s=isc, _RC)
     nullify(metadata)
     _RETURN(ESMF_SUCCESS)
  end function MAPL_ExtDataGetFStartTime
Call graph
mapl_extdatagetfstarttime calls ESMF_TimeSet, get_time_info, makemetadata, mapl_return, mapl_verify
get_time_info calls ESMF_TimeSet, mapl_return, mapl_verify, ESMF_TimeGet, ESMF_TimeIntervalSet, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, mapl_assert, get_coordinate_info, get_file_name
makemetadata calls mapl_return, mapl_verify, at, debug, find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_coordinate_info calls mapl_return, mapl_verify, get_attribute, get_coordinate_data, get_coordinate_variable, get_value, mapl_assert, get_file_name, get_dimension, get_ith_dimension, var_has_attr
get_error_message calls at
get_file_name calls mapl_return
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
var_has_attr calls mapl_return, mapl_verify, mapl_assert, get_file_name, get_variable, is_attribute_present
run_ calls mapl_extdatagetfstarttime