MAPL_GetChildLocstream – MAPL
MAPL_GetChildLocstream Subroutine
41 statements
Source File
public recursive subroutine MAPL_GetChildLocstream(GC, result, name, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(MAPL_LocStream), intent(out) :: result
character(len=*), intent(in) :: name
integer, intent(out) :: rc
Calls
Source Code
   recursive subroutine MAPL_GetChildLocstream(GC, result, name, rc)
      type(ESMF_GridComp),   intent(INout) :: GC
      type (MAPL_LocStream), intent(  OUT) :: result
      character(len=*),      intent(IN   ) :: name
      integer,               intent(  OUT) :: rc
      character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_GetChildLocstream"
      integer                               :: status
      integer                               :: I
      logical                               :: have_ens
      character(len=ESMF_MAXSTR)            :: comp_name
      type (MAPL_MetaComp),pointer          :: STATE
      type(ESMF_GridComp), pointer :: gridcomp
      call ESMF_GridCompGet(GC, name=comp_name, rc=status)
      _VERIFY(status)
      call MAPL_InternalStateGet ( GC, STATE, RC=status)
      _VERIFY(status)
      have_ens = index(name,":") /= 0
      if (have_ens) then ! the name contains ensemble #
         if (name == comp_name) then
            result = state%locstream
            _RETURN(status)
         end if
      else
         if (name == comp_name(index(comp_name,":")+1:)) then
            result = state%locstream
            _RETURN(status)
         end if
      end if
      do I = 1, STATE%get_num_children()
         gridcomp => STATE%GET_CHILD_GRIDCOMP(I)
         call MAPL_GetChildLocstream(gridcomp, result, name, rc=status)
         if (status == ESMF_SUCCESS) then
            _RETURN(ESMF_SUCCESS)
         end if
      end do
      rc = ESMF_FAILURE
      return
   end subroutine MAPL_GetChildLocstream
Call graph
mapl_getchildlocstream calls mapl_getchildlocstream, ESMF_GridCompGet, get_child_gridcomp, get_num_children, mapl_internalstateget, mapl_return, mapl_verify
get_child_gridcomp calls get_gridcomp, get_ith_child
get_num_children calls get_num_children
mapl_internalstateget calls ESMF_GridCompGet, mapl_return, mapl_verify, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_gridcomp calls get_current_thread, is_threading_active
get_ith_child calls get_child
mapl_throw_exception calls initialize