MAPL_CFIOReadBundle – MAPL
MAPL_CFIOReadBundle Subroutine
695 statements
Source File
private subroutine MAPL_CFIOReadBundle(FILETMPL, TIME, BUNDLE, NOREAD, RC, VERBOSE, FORCE_REGRID, ONLY_VARS, ONLY_LEVS, TIME_IS_CYCLIC, TIME_INTERP, conservative, voting, ignoreCase, doParallel, GSImode, getFrac, EXPID, collection_id)
The subroutine MAPL_CFIOReadBundle` reads an ESMF Bundle from a file on a given time. The file is open, read from, and closed on exit. The arguments are:
FILETMPL A GrADS-style file name template. In its simplest form is the full path name for the file to be read. However, it can contain the following tokens which will be expanded from the current time in {\em TIME}:
%y4 4 digits for year
%m2 2 digits for month, to expand to 01, 02, .., 12
%m3 3 digits for month, to expand to jan, feb, mar, …, dec
%d2 2 digits for day
%h2 2 digits for hour
%n2 2 digits for minutes Example: if FILETMPL = 'forecast.%y4-%m2-%d2_%h2z.nc4', and the clock says it is 18Z on 05 February 2007, the template will expand in the following file name: 'forecast.2007-02-05_18Z.nc4'
TIME The ESMF time to read from the file
BUNDLE An ESMF Bundle to read the data in. When the Bundle is empty one field is added for each variable present in the input file, and the necessary memory allocated according to the ESMF grid present in the Bundle.
[NOREAD] If .TRUE., no data is actually read into the Bundle. This is useful to define a Bundle with the same variables as presented in the file, which in turn can be used to created a MAPL_CFIO object for writing.
[RC] Error return code; set to ESMF_SUCCESS if all is well.
[VERBOSE] If .TRUE., prints progress messages to STDOUT; useful for debugging.
[FORCE_REGRID] Obsolete; kept for backward compatibility but has no effect.
[TIME_IS_CYCLIC] If .TRUE. it says that the input file is periodic in time. Useful for reading climatological files. For example, if the input file has 12 monthly means from January to December of 2001, setting this option to .TRUE. allows one to read this data for any other year. See note below regarding issues with reading monthly mean data.
[TIME_INTERP] If .TRUE., the input file does not have to coincide with the actual times on file. In such cases, the data for the bracketing times are read and the data is properly interpolated in time. The input time, though, need to be within the range of times present on file (unless TIME_IS_CYCLIC is specified).
[ONLY_VARS] A list of comma separated vafriables to be read from the file. By default, all variables are read from the file. This option allows one to read a subset of vafriables. Example: ONLY_VARS='u,v,ps'.
A note about storing monthly climatological data. As per the CF conventions, month is not a well defined unit of time, as the time step is not constant throughout the year. When storing 12 months of climatological data one way around it is to use an average number of hours: use 732 or 730 hours depending on whether the year recorded in the file is a leap-year or not.
Design Issues
The input argument TIME should be replaced with CLOCK for consistency with the rest of the API. One should also provide an interface involving the MAPL CFIO object.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: FILETMPL
type(ESMF_Time), intent(inout) :: TIME
type(ESMF_FIELDBUNDLE), intent(inout) :: BUNDLE
logical, intent(in), optional :: NOREAD
integer, intent(out), optional :: RC
logical, intent(in), optional :: VERBOSE
logical, intent(in), optional :: FORCE_REGRID
character(len=*), intent(in), optional :: ONLY_VARS
real, intent(in), optional :: ONLY_LEVS(:)
logical, intent(in), optional :: TIME_IS_CYCLIC
logical, intent(in), optional :: TIME_INTERP
logical, intent(in), optional :: conservative
logical, intent(in), optional :: voting
logical, intent(in), optional :: ignoreCase
logical, intent(in), optional :: doParallel
logical, intent(in), optional :: GSImode
integer, intent(in), optional :: getFrac
character(len=*), intent(in), optional :: EXPID
integer, intent(in), optional :: collection_id
Calls
MAPL_CFIOMod::MAPL_CFIOReadBundle w ESMF::ESMF_AttributeSet
w
w ESMF::ESMF_GridGet
w
w ESMF::ESMF_TimeGet
w
w ESMF::ESMF_UtilStringUpperCase
w
w ESMF::ESMF_VMGet
w
w ESMF::ESMF_VMGetCurrent
w
w esmf_arrayget
w
w ESMF_CFIOCollectionMod::CFIOCollection%find
w
w ESMF_CFIOCollectionVectorMod::CFIOCollectionVector%at
w
w ESMF_CFIOFileMod::ESMF_CFIOCreate
w
w ESMF_CFIOFileMod::ESMF_CFIODestroy
w
w ESMF_CFIOFileMod::ESMF_CFIOGet
w
w ESMF_CFIOFileMod::ESMF_CFIOSet
w
w ESMF_CFIOGridMod::ESMF_CFIOGridGet
w
w ESMF_CFIOMod::ESMF_CFIOFileOpen
w
w ESMF_CFIOMod::ESMF_CFIOVarRead
w
w ESMF_CFIOMod::ESMF_CFIOVarReadT
w
w ESMF_CFIOUtilMod::strToInt
w
w ESMF_CFIOVarInfoMod::ESMF_CFIOVarInfoGet
w
w esmf_fieldbundleget
w
w esmf_fieldcreate
w
w esmf_fieldget
w
w MAPL_AbstractRegridderMod::AbstractRegridder%regrid
w
w MAPL_AbstractRegridderMod::AbstractRegridder%set_undef_value
w
w MAPL_Base::MAPL_FieldBundleAdd
w
w MAPL_Base::MAPL_GRID_INTERIOR
w
w MAPL_CFIOMod::GridGetLatLons_
w
w MAPL_CFIOMod::make_regridder
w
w MAPL_CommsMod::ArrayScatter
w
w MAPL_CommsMod::MAPL_Am_I_Root
w
w MAPL_CommsMod::MAPL_BcastShared
w
w MAPL_CommsMod::MAPL_CollectiveScatter3D
w
w MAPL_CommsMod::MAPL_RoundRobinPEList
w
w MAPL_ErrorHandlingMod::MAPL_Assert
w
w MAPL_ErrorHandlingMod::MAPL_Return
w
w MAPL_ErrorHandlingMod::MAPL_Verify
w
w mapl_MaplGrid::MAPL_GridGet
w
w MAPL_Shmem::MAPL_AllocNodeArray
w
w MAPL_Shmem::MAPL_CoresPerNodeGet
w
w MAPL_Shmem::MAPL_DeAllocNodeArray
w
w MAPL_Shmem::MAPL_ShmemAmOnFirstNode
w
w MAPL_Shmem::MAPL_SyncSharedMemory
w
w MAPL_StringTemplate::fill_grads_template
w
Called by
Source Code
  subroutine MAPL_CFIOReadBundle ( FILETMPL, TIME, BUNDLE, NOREAD, RC, &
                                   VERBOSE, FORCE_REGRID, ONLY_VARS, ONLY_LEVS, &
                                   TIME_IS_CYCLIC, TIME_INTERP, conservative, &
                                   voting, ignoreCase, doParallel, GSImode, getFrac, EXPID, collection_id )
!
    character(len=*),            intent(IN   ) :: FILETMPL
    type(ESMF_TIME),             intent(INout) :: TIME
    type(ESMF_FIELDBUNDLE),           intent(INOUT) :: BUNDLE
    logical, optional,           intent(IN   ) :: NOREAD
    integer, optional,           intent(  OUT) :: RC
    logical, optional,           intent(IN)    :: VERBOSE
    logical, optional,           intent(IN)    :: FORCE_REGRID
    logical, optional,           intent(IN)    :: TIME_IS_CYCLIC
    logical, optional,           intent(IN)    :: TIME_INTERP
    logical, optional,           intent(IN)    :: conservative
    logical, optional,           intent(IN)    :: voting
    logical, optional,           intent(IN)    :: doParallel
    character(len=*), optional,  intent(IN)    :: ONLY_VARS
    real,    optional,           intent(IN)    :: ONLY_LEVS(:)
    character(len=*), optional,  intent(IN)    :: EXPID
    logical, optional,           intent(IN)    :: ignoreCase
    logical, optional,           intent(IN)    :: GSImode
    integer, optional,           intent(IN)    :: getFrac
    integer, optional,           intent(IN)    :: collection_id
!
!--------------------------------------------------------------------------------
    character(len=*), parameter  :: Iam="MAPL_CFIOReadBundle"
    integer                      :: STATUS
! Locals
    type(ESMF_CFIO), pointer     :: CFIO
    type(ESMF_CFIOGrid), pointer :: CFIOGRID
    type(ESMF_GRID)              :: ESMFGRID
    type(ESMF_FIELD)             :: FIELD
    type(ESMF_ARRAY)             :: ARRAY
    type(ESMF_VM)                :: VM
    type(ESMF_CFIOVarInfo), pointer :: VARS(:)
    integer                      :: IM,  JM,  LM, ISTAR, JSTAR
    integer                      :: IM0, JM0
    integer                      :: L1, L, K
    integer                      :: NumVars, nVars
    integer                      :: counts(5)
    integer                      :: dims(3)
    integer                      :: arrayRank
    logical                      :: IamRoot, twoD
    logical                      :: amOnFirstNode
    real, pointer                ::  PTR2      (:,:),  PTR3      (:,:,:)
    real, pointer                :: GPTR2bundle(:,:), GPTR3bundle(:,:,:)
    real, pointer                :: GPTR2file  (:,:), GPTR3file  (:,:,:)
    character(len=ESMF_MAXSTR)   :: DATE
    character(len=ESMF_MAXSTR)   :: BundleVARNAME
    character(len=ESMF_MAXSTR)   :: CFIOVARNAME
    character(len=ESMF_MAXSTR)   :: LONG_NAME
    character(len=ESMF_MAXSTR)   :: UNITS
    real, pointer :: LONSfile(:),   LATSfile(:)
    real, pointer :: LONSbundle(:) => NULL()
    real, pointer :: LATSbundle(:) => NULL()
    !(stassi,14feb2012)--character(len=ESMF_MAXSTR) :: FILENAME
    !character(len=256) :: FILENAME
    character(len=1024) :: FILENAME
    integer :: nymd, nhms
    logical :: timeInterp=.false., VERB = .false., change_resolution, do_xshift, single_point, fcubed
    integer, allocatable    :: gridToFieldMap(:)
    integer                 :: gridRank
    integer                 :: comm
    logical                 :: found
    character(len=ESMF_MAXSTR) :: gridname
    logical :: RegridCnv
    logical :: Voting_, ldoFrac
    logical :: runParallel
    logical :: ignoreCase_
    integer, pointer        :: Krank(:) => null()
    logical                 :: myGlobal
    integer                 :: nn, CoresPerNode, myPet, nPet, numNodes
    logical :: selectedLevels
    real, pointer :: levsfile(:) => null()
    integer :: LM_FILE
    integer :: LL,klev
    integer, allocatable :: LEVIDX(:)
    type(ESMF_CFIOGrid)  :: varsGrid
    real, parameter      :: eps = 1.0e-4 ! tolerance to find "selected" levels
    logical :: kreverse
    integer :: i1w,inw,j1w,jnw
    logical :: gsiMode_
    integer :: hw
    integer :: halowidth(3)
    class (AbstractRegridder), pointer :: regridder
    integer :: method
    type(CFIOCollection), pointer :: collection => null()
    logical :: time_is_cyclic_
    logical :: cfioIsCreated
!                              ---
    _UNUSED_DUMMY(FORCE_REGRID)
    if ( present(VERBOSE) )     VERB = VERBOSE
    if ( present(TIME_INTERP) ) timeInterp = TIME_INTERP
    if (present(time_is_cyclic)) then
       time_is_cyclic_ = time_is_cyclic
    else
       time_is_cyclic_ = .false.
    end if
    if (present(conservative) ) then
       RegridCnv = conservative
    else
       RegridCnv = .false.
    end if
    if ( present(Voting) ) then
         Voting_ = Voting
    else
         Voting_ = .false.
    endif
    if ( present(getFrac) ) then
         ldoFrac = .true.
    else
         ldoFrac = .false.
    endif
    if ( present(ignoreCase) ) then
         ignoreCase_ = ignoreCase
    else
         ignoreCase_ = .false.
    end if
    if ( present(doParallel) ) then
       runParallel = doParallel
    else
       runParallel = .true.
    end if
    if (present(ONLY_LEVS)) then
       selectedLevels = .true.
    else
       selectedLevels = .false.
    end if
    if (present(GSImode)) then
       GSImode_=GSImode
    else
       GSImode_=.false.
    end if
    if (gsiMode_) then
       hw = 1
    else
       hw = 0
    end if
    haloWidth = (/HW,HW,0/)
    ! by default kreverse is false
    kreverse = .false.
! Transform ESMF time to string for use in CFIO
!----------------------------------------------
    call ESMF_TimeGet(TIME, timeString=DATE, RC=STATUS)
    _VERIFY(STATUS)
    call strToInt(DATE, nymd, nhms)
    call fill_grads_template ( filename, filetmpl, &
                           experiment_id=EXPID, nymd=nymd, nhms=nhms, rc=status )
    _VERIFY(STATUS)
    !call WRITE_PARALLEL("CFIO: Reading " // trim(filename))
    if (mapl_am_i_root()) write(*,*)"CFIO: Reading ",trim(filename)," at ",nymd," ",nhms
    cfioIsCreated = .false.
    if (present(collection_id)) then
       collection => collections%at(collection_id)
       cfio => collection%find(filename, _RC)
    else
       allocate(CFIO)
       cfio=ESMF_CFIOCreate(RC=status)
       _VERIFY(status)
       cfioIsCreated = .true.
       call ESMF_CFIOSet(CFIO, fName=trim(fileName), RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_CFIOFileOpen  (CFIO, FMODE=1, cyclic=TIME_IS_CYCLIC_, RC=STATUS)
       _VERIFY(STATUS)
    end if
! Get info from the bundle
!-------------------------
    call ESMF_VMGetCurrent(VM, RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_FieldBundleGet     (Bundle, FieldCount=NUMVARS, RC=STATUS)
    _VERIFY(STATUS)
    IamRoot = MAPL_AM_I_ROOT(VM)
    call ESMF_VMGet(VM, mpiCommunicator=comm, localPet=myPET, PETcount=nPet, rc=status)
    _VERIFY(STATUS)
    amOnFirstNode = MAPL_ShmemAmOnFirstNode(comm=comm, RC=status)
    _VERIFY(STATUS)
    CoresPerNode = MAPL_CoresPerNodeGet(comm,rc=status)
    _VERIFY(STATUS)
    ! Get lat/lons of input bundle
    ! ----------------------------
    call ESMF_FieldBundleGet     (Bundle,   Grid=ESMFGRID, RC=STATUS)
    _VERIFY(STATUS)
    call GridGetLatLons_ ( ESMFGRID, LONSbundle, LATSbundle, rc=status )
    _VERIFY(STATUS)
! Get info from the CFIO object
!------------------------------
    call ESMF_CFIOGet       (CFIO,     grid=CFIOGRID,                     RC=STATUS)
    _VERIFY(STATUS)
    call ESMF_CFIOGridGet   (CFIOGRID, IM=IM, JM=JM, KM=LM,               RC=STATUS)
    _VERIFY(STATUS)
    if(selectedLevels) then
       LM_FILE = LM
       LM = size(ONLY_LEVS)
       _ASSERT(LM <= LM_FILE, 'LM > LM_FILE')
    end if
    call ESMF_CFIOGridGet    (CFIOGRID, LON=LONSFILE, LAT=LATSFILE, RC=STATUS)
    _VERIFY(STATUS)
    deallocate(CFIOGRID)
    call ESMF_CFIOGet (CFIO,varObjs=VARS, nVars=nVars, RC=STATUS)
    _VERIFY(STATUS)
! If the bundle is empty, read entire varlist from file
!------------------------------------------------------
    if(NUMVARS==0) then
       call MAPL_GridGet(ESMFGRID, globalCellCountPerDim=COUNTS, &
            localCellCountPerDim=DIMS, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_GridGet(ESMFGRID, name=gridname, rc=rc)
       _VERIFY(STATUS)
       ! Assert compatibility of file and bundle
       !----------------------------------------
       _ASSERT( LM==0 .or. counts(3) == 0 .or. LM==counts(3) .or. LM==(counts(3)+1), 'file and bundle are incompatible')
       ! Get lat/lons of input bundle
       ! ----------------------------
       NUMVARS = nVars
       L1 = 0
       do L=1,NUMVARS
          call ESMF_CFIOVarInfoGet(VARS(L),vname=CFIOVARNAME, vtitle=LONG_NAME, vunits=UNITS, twoDimVar=twoD, &
               & grid=varsGrid, RC=STATUS)
          _VERIFY(STATUS)
          if ( present(ONLY_VARS) ) then
               if ( index(','//trim(ONLY_VARS)  //',', &
                          ','//trim(CFIOVARNAME)//',') < 1 ) cycle
          endif
          if (trim(CFIOVARNAME)=="lons" .or. trim(CFIOVARNAME)=="lats") cycle
          L1 = L1 + 1
          BundleVarName = CFIOVARNAME
          if(twoD) then
            allocate(PTR2(1-HW:DIMS(1)+HW,1-HW:DIMS(2)+HW),stat=STATUS)
            _VERIFY(STATUS)
            PTR2  = 0.0
            call ESMF_GridGet(ESMFGRID, dimCount=gridRank, rc=status)
            _VERIFY(STATUS)
            allocate(gridToFieldMap(gridRank), stat=status)
            _VERIFY(STATUS)
            if(gridRank == 2) then
               gridToFieldMap(1) = 1
               gridToFieldMap(2) = 2
            else if (gridRank == 3) then
               gridToFieldMap(1) = 1
               gridToFieldMap(2) = 2
               gridToFieldMap(3) = 0
            else
               _RETURN(ESMF_FAILURE)
            end if
            FIELD = ESMF_FieldCreate(grid=ESMFGRID, &
                            datacopyFlag = ESMF_DATACOPY_REFERENCE,   &
                            farrayPtr=PTR2, gridToFieldMap=gridToFieldMap, &
                            name=BundleVARNAME, &
                            totalLWidth=haloWidth(1:2),     &
                            totalUWidth=haloWidth(1:2),     &
                            rc = status)
            _VERIFY(STATUS)
            deallocate(gridToFieldMap)
!ALT: for now we add only HorzOnly (no tiles)
            call ESMF_AttributeSet(FIELD, NAME='LONG_NAME', VALUE=LONG_NAME, RC=STATUS)
            _VERIFY(STATUS)
            call ESMF_AttributeSet(FIELD, NAME='UNITS', VALUE=UNITS, RC=STATUS)
            _VERIFY(STATUS)
            call ESMF_AttributeSet(FIELD, NAME='DIMS', VALUE=MAPL_DimsHorzOnly, RC=STATUS)
            _VERIFY(STATUS)
            call ESMF_AttributeSet(FIELD, NAME='VLOCATION', &
                                        VALUE=MAPL_VLocationNone, RC=STATUS)
            _VERIFY(STATUS)
          else
            ! 3-d case
             call ESMF_CFIOGridGet (varsGrid, lev=levsfile, rc=status)
             _VERIFY(STATUS)
             if (levsfile(1) > levsfile(lm)) kreverse = .true.
             if (selectedLevels) then
                if (.not. allocated(levidx)) then
                   allocate(levidx(LM), stat=status)
                   _VERIFY(STATUS)
                   ! build level index
                   DO K = 1, LM
                      found = .false.
                      DO LL = 1, LM_FILE
                         if (abs(LEVSFILE(LL) - ONLY_LEVS(K)) < eps) then
                            LEVIDX(K) = LL
                            found = .true.
                            exit
                         end if
                      END DO
                      _ASSERT(found, 'search failed')
                   END DO
                end if
             end if
            deallocate(levsfile)
            nullify(levsfile)
            if (lm == counts(3)) then
               allocate(PTR3(1-HW:DIMS(1)+HW,1-HW:DIMS(2)+HW,LM),stat=STATUS)
               _VERIFY(STATUS)
            else if (lm == (counts(3)+1)) then
               allocate(PTR3(1-HW:DIMS(1)+HW,1-HW:DIMS(2)+HW,0:LM-1),stat=STATUS)
               _VERIFY(STATUS)
            endif
            PTR3  = 0.0
            FIELD = ESMF_FieldCreate(grid=ESMFGRID, &
                            datacopyFlag = ESMF_DATACOPY_REFERENCE,   &
                            farrayPtr=PTR3, name=BundleVARNAME,       &
                            totalLWidth=haloWidth(1:2),     &
                            totalUWidth=haloWidth(1:2),     &
                            rc = status)
            _VERIFY(STATUS)
!ALT: for now we add only HorzVert (no tiles)
            call ESMF_AttributeSet(FIELD, NAME='LONG_NAME', VALUE=LONG_NAME, RC=STATUS)
            _VERIFY(STATUS)
            call ESMF_AttributeSet(FIELD, NAME='UNITS', VALUE=UNITS, RC=STATUS)
            _VERIFY(STATUS)
            call ESMF_AttributeSet(FIELD, NAME='DIMS', VALUE=MAPL_DimsHorzVert, RC=STATUS)
            _VERIFY(STATUS)
            if (lm == counts(3)) then
               call ESMF_AttributeSet(FIELD, NAME='VLOCATION', &
                                           VALUE=MAPL_VLocationCenter, RC=STATUS)
            else if (lm == (counts(3)+1)) then
               call ESMF_AttributeSet(FIELD, NAME='VLOCATION', &
                                           VALUE=MAPL_VLocationEdge, RC=STATUS)
            end if
            _VERIFY(STATUS)
          end if
          call MAPL_FieldBundleAdd(BUNDLE, FIELD, RC=STATUS)
          _VERIFY(STATUS)
       end do
       NUMVARS = L1  ! could be less than on file if user chooses to
    else
       do L=1,NumVars
          call ESMF_FieldBundleGet (BUNDLE, L, FIELD,                     RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_FieldGet(FIELD,NAME=BundleVarName, RC=STATUS)
          _VERIFY(STATUS)
          call MAPL_GridGet(ESMFGRID, globalCellCountPerDim=COUNTS, RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_GridGet(ESMFGRID, name=gridname, rc=rc)
          _VERIFY(STATUS)
          ! Assert compatibility of file and bundle
          !----------------------------------------
          _ASSERT( LM==0 .or. counts(3) == 0 .or. LM==counts(3) .or. lm == (counts(3)+1), 'incompatible file and bundle')
          found = .false.
          do K=1,size(VARS)
             call ESMF_CFIOVarInfoGet(VARS(K),vname=CFIOVARNAME,          RC=STATUS)
             _VERIFY(STATUS)
             if (ignoreCase_) then
                BUNDLEVARNAME = ESMF_UtilStringUpperCase(BUNDLEVARNAME,RC=status)
                _VERIFY(STATUS)
                CFIOVARNAME   = ESMF_UtilStringUpperCase(CFIOVARNAME,RC=status)
                _VERIFY(STATUS)
             end if
             if(trim(BUNDLEVARNAME)==trim(CFIOVARNAME)) then
               found = .true.
               exit
             end if
          end do
          _ASSERT(found, 'search failed')
          call ESMF_CFIOVarInfoGet(VARS(K), twoDimVar=twoD, grid=varsGrid, RC=STATUS)
          _VERIFY(STATUS)
          if (.not. twoD) then
             call ESMF_CFIOGridGet (varsGrid, lev=levsfile, rc=status)
             _VERIFY(STATUS)
             if (levsfile(1) > levsfile(lm)) kreverse = .true.
          end if
          if (selectedLevels) then
             if (.not. twoD) then
                ! 3-d case
                if (.not. allocated(levidx)) then
                   allocate(levidx(LM), stat=status)
                   _VERIFY(STATUS)
                   ! build level index
                   DO K = 1, LM
                      found = .false.
                      DO LL = 1, LM_FILE
                         if (abs(LEVSFILE(LL) - ONLY_LEVS(K)) < eps) then
                            LEVIDX(K) = LL
                            found = .true.
                            exit
                         end if
                      END DO
                      _ASSERT(found, 'search failed')
                   END DO
                end if
             end if
          end if
          if (associated(levsfile)) then
             deallocate(levsfile)
             nullify(levsfile)
          end if
       end do
    end if
    if(present(NOREAD)) then
       if(NOREAD) goto 10
    end if
!   Do we have to run a transform?
!   ------------------------------
    IM0 = counts(1)
    JM0 = counts(2)
    if (IM /= IM0 .or. JM /= JM0)  then
        change_resolution = .true.
    else
        change_resolution = .false.
    end if
! 180 Degree Shifting and Cubed Sphere
! ------------------------------------
!
!   In the earlier revisions of this subroutine there was an implicit assumption
!   of the input data being on the lat-lon grid. Since there were two
!   possibilities: Longitudinal origin at dateline, or at the Greewitch meridian,
!   the code used to perform Longitudinal shifting, if needed, so that the
!   output is "properly" oriented at dateline center.
!
!   Out current strategy is to correct the input (from the file), if needed.
!   We first check if the input is on the Cubed-Sphere grid.
!   In this case no shifting is done. Otherwise we still assume that the
!   input is on a lat-lon grid and if shifting is needed,
!   it will be done prior to the optional MAPL_HorzTransformRun regridding.
    if ( JM == 6*IM )  then
        fcubed = .true.
    else
        fcubed = .false.
    end if
    do_xshift = .FALSE. ! Initialize: do not shift
    if ( IM0==1 .AND. JM0==1 ) then
       single_point = .TRUE.       ! running SCM with single point grid
       change_resolution = .FALSE. ! does not make sense in SCM mode
    else
       single_point = .FALSE. ! Normal case, not SCM
       ! never shift if cubed
       if (.not.fcubed) do_xshift = abs(LONSfile(1)+180._REAL64) .GT. abs(LONSfile(2)-LONSfile(1))
    end if
    if (change_resolution .and. RegridCnv) then
       runParallel = .false. ! override input, conservative regridding now done distributed
       if (Voting_) then
         method = REGRID_METHOD_VOTE
       elseif (ldofrac) then
         method = REGRID_METHOD_FRACTION
       else
         method = REGRID_METHOD_CONSERVE
       end if
       regridder => make_regridder(ESMFGRID, method, LONSfile, LATSfile, IM, JM, counts(3), runparallel, localTiles=.true., rc=status)
       _VERIFY(status)
    else if ( change_resolution .and. (.not.RegridCnv)) then
       method = REGRID_METHOD_BILINEAR
       regridder => make_regridder(ESMFGRID, method, LONSfile, LATSfile, IM, JM, counts(3), runparallel, rc=status)
       _VERIFY(status)
    end if
    call MAPL_SyncSharedMemory(rc=status)
    _VERIFY(STATUS)
! Allocate space for global arrays. If non-conservative perform
! parallel transform distributed across levels
! If conservative do not parallelize over levels this is done
! distributed already so this parallel strategy will not work
!------------------------------------------------------------
    if (RegridCnv .and. change_resolution) then
       call MAPL_GRID_INTERIOR(ESMFGRID,I1w,INw,J1w,JNw)
       if(MAPL_ShmInitialized) then
          call MAPL_AllocNodeArray(Gptr2file,(/im,jm/),rc=STATUS)
          _VERIFY(STATUS)
          call MAPL_AllocNodeArray(Gptr3file,(/im,jm,1/),rc=STATUS)
          _VERIFY(STATUS)
       else
          allocate(Gptr2file(im,jm),stat=status)
          _VERIFY(STATUS)
          allocate(Gptr3file(im,jm,1),stat=status)
          _VERIFY(STATUS)
       endif
       Allocate(Gptr2bundle(inw-i1w+1,jnw-j1w+1),stat=STATUS)
       _VERIFY(STATUS)
       allocate(Gptr3bundle(0,0,0), stat=STATUS)
       _VERIFY(STATUS)
       if (LM > 0) then
          allocate(krank(LM),stat=status)
       else
          allocate(krank(1) ,stat=status)
       end if
       krank = 0
    else
       IM0 = counts(1)
       JM0 = counts(2)
       CoresPerNode = MAPL_CoresPerNodeGet(comm,rc=status)
       _VERIFY(STATUS)
       if (LM > 0) then
          allocate(krank(LM),stat=status)
       else
          allocate(krank(1) ,stat=status)
       end if
       _VERIFY(STATUS)
       if (runParallel .and. (LM > 0) ) then
          numNodes = size(MAPL_NodeRankList)
          call MAPL_RoundRobinPEList(krank,numNodes,rc=status)
          _VERIFY(STATUS)
       else
          krank = 0
       end if
       nn=count(krank==myPet)
       if (nn > 0) then
          allocate(Gptr2bundle(IM0,JM0   ), stat=STATUS)
          _VERIFY(STATUS)
          allocate(Gptr3bundle(IM0,JM0,nn), stat=STATUS)
          _VERIFY(STATUS)
          allocate(Gptr2file  (IM ,JM    ), stat=STATUS)
          _VERIFY(STATUS)
          allocate(Gptr3file  (IM ,JM , 1), stat=STATUS)
          _VERIFY(STATUS)
       else
          allocate(Gptr2bundle(0,0   ), stat=STATUS)
          _VERIFY(STATUS)
          allocate(Gptr3bundle(0,0,0), stat=STATUS)
          _VERIFY(STATUS)
          allocate(Gptr2file  (0,0    ), stat=STATUS)
          _VERIFY(STATUS)
          allocate(Gptr3file  (0,0,0), stat=STATUS)
          _VERIFY(STATUS)
       end if
    end if
!   Special handling for single column case
!   Pick out index into file grid for lats and lons of scm grid -
!   Assume that scm grid counts lon from -180 to 180 and lat from -90 to 90
    if(single_point) then
      if(LONSfile(1).lt.0.) then        !  assume lons on file go from -180 to 180
       ISTAR = 1 + (LONSbundle(1)+180.)/( 360./ IM )
      else                              !  lons on file go from 0 to 360
       if(LONSbundle(1).lt.0.) then
       ISTAR = 1 + (LONSbundle(1)+360.)/( 360./IM )
       else
       ISTAR = 1 + LONSbundle(1)/( 360./IM )
       endif
      endif
!  assume lats on file go from -90 to 90
       JSTAR = 1 + (LATSbundle(1)+90.)/( 180. / (JM-1) )
    endif
! Read each variable
!-------------------
    do L=1,NumVars
       call ESMF_FieldBundleGet (BUNDLE, L, FIELD,                       RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_FieldGet       (FIELD, NAME=BundleVarName, array=ARRAY, RC=STATUS)
       _VERIFY(STATUS)
       if (ignoreCase_) call getVarNameIgnoreCase(BundleVarName,vars,RC=status)
       call ESMF_FieldGet(FIELD,   Grid=ESMFGRID, RC=STATUS)
       _VERIFY(STATUS)
       call ESMF_ArrayGet       (array, rank=arrayRank,                  RC=STATUS)
       _VERIFY(STATUS)
       if ( VERB .and. IamRoot ) &
            print *, Iam // ': Reading '//trim(BundleVARNAME)// &
                            ' at ' // trim(date)
       select case (arrayRank)
       case (2)
          call ESMF_ArrayGet(Array, localDE=0, farrayPtr=PTR2, RC=STATUS)
          _VERIFY(STATUS)
          ! read the data on root
          if (IamRoot) then
             if ( timeInterp ) then
                call ESMF_CFIOVarReadT(CFIO, trim(BundleVARNAME), GPTR2file, &
                                       timeString=DATE, RC=STATUS)
                if (ldofrac) GPTR2file=GPTR2file-getfrac
             else
                call ESMF_CFIOVarRead (CFIO, trim(BundleVARNAME), GPTR2file, &
                                       timeString=DATE, RC=STATUS)
                if (ldofrac) GPTR2file=GPTR2file-getfrac
             endif
             _VERIFY(STATUS)
             if ( do_xshift ) then
                 if ( VERB ) print *, Iam // &
                      ': shifting input longitudes by 180 degrees'
                 call shift180Lon2D_ ( Gptr2file, im, jm )
             end if
          end if
          ! transform and scatter
          if (change_resolution) then
              if (RegridCnv) then
                 call MAPL_SyncSharedMemory(rc=status)
                 _VERIFY(STATUS)
                 call MAPL_BcastShared(VM, Data=Gptr2file, N=im*jm, Root=0, RootOnly=.false., rc=status)
                 _VERIFY(STATUS)
                 call MAPL_SyncSharedMemory(rc=STATUS)
                 _VERIFY(STATUS)
                 call regridder%regrid(Gptr2file, Gptr2bundle, rc=status)
                 _VERIFY(status)
                 call MAPL_SyncSharedMemory(rc=status)
                 _VERIFY(STATUS)
                 ptr2 = Gptr2bundle
                 call MAPL_SyncSharedMemory(rc=STATUS)
                 _VERIFY(STATUS)
              else
                 if (IamRoot) then
                    call regridder%set_undef_value(MAPL_undef)
                    call regridder%regrid(Gptr2file, Gptr2bundle, rc=status)
                    _VERIFY(status)
                    if (GSImode_) call shift180Lon2D_ ( Gptr2bundle, im0, jm0 )
                 end if
                 call ArrayScatter(PTR2, GPTR2bundle, ESMFGRID, hw=hw, RC=STATUS)
                 _VERIFY(STATUS)
              end if
          else if ( single_point ) then
             Gptr2bundle(1,1) = Gptr2file(ISTAR,JSTAR)
             ptr2(1,1) = GPTR2bundle(1,1) ! single point SCM case
          else
             if (IamRoot) Gptr2bundle = Gptr2file
             call ArrayScatter(PTR2, GPTR2bundle, ESMFGRID, hw=hw, RC=STATUS)
             _VERIFY(STATUS)
          end if ! change resolution
       case(3)
          nn = 0
          call ESMF_FieldGet(Field, localDE=0, farrayPtr=PTR3, RC=STATUS)
          _VERIFY(STATUS)
          nn=0
          do k = 1, LM
             MyGlobal = Krank(k) == myPet
             call MAPL_SyncSharedMemory(rc=status)
             _VERIFY(STATUS)
             if (MyGlobal) then
                nn=nn+1
                if (selectedLevels) then
                   _ASSERT(allocated(levidx), 'levidx not allocated')
                   klev = levidx(k)
                else
                   klev = k
                end if
                if (kreverse) klev = lm - k + 1
                if ( timeInterp ) then
                   call ESMF_CFIOVarReadT(CFIO, trim(BundleVARNAME), GPTR3file, &
                        kbeg=klev, kount=1, timeString=DATE, RC=STATUS)
                        if (ldofrac) GPTR3file=GPTR3file-getfrac
                else
                   call ESMF_CFIOVarRead (CFIO, trim(BundleVARNAME), GPTR3file, &
                        kbeg=klev, kount=1, timeString=DATE, RC=STATUS)
                        if (ldofrac) GPTR3file=GPTR3file-getfrac
                end if
                _VERIFY(STATUS)
                GPTR2file = GPTR3file(:,:,1)
                if ( do_xshift ) then
                   call shift180Lon2D_ ( Gptr2file, im, jm )
                end if
             end if
             if (change_resolution) then
                if (RegridCnv) then
                   call MAPL_SyncSharedMemory(rc=status)
                   _VERIFY(STATUS)
                   call MAPL_BcastShared(VM, Data=Gptr2file, N=im*jm, Root=0, RootOnly=.false., rc=status)
                   _VERIFY(STATUS)
                   call MAPL_SyncSharedMemory(rc=STATUS)
                   _VERIFY(STATUS)
                   call regridder%regrid(Gptr2file, Gptr2bundle, rc=status)
                   _VERIFY(status)
                   call MAPL_SyncSharedMemory(rc=status)
                   _VERIFY(STATUS)
                   L1 = LBOUND(PTR3,3)-1
                   ptr3(:,:,K+L1) = Gptr2bundle
                   call MAPL_SyncSharedMemory(rc=STATUS)
                   _VERIFY(STATUS)
                 else
                    if (MyGlobal) then
                       call regridder%set_undef_value(MAPL_undef)
                       call regridder%regrid(Gptr2file, Gptr2bundle, rc=status)
                       _VERIFY(status)
                       if (GSImode_) call shift180Lon2D_ ( Gptr2bundle, im0, jm0 )
                       Gptr3bundle(:,:,nn)=Gptr2bundle
                    end if
                end if
             else if ( single_point ) then
                  Gptr3bundle(:,:,nn) = Gptr2file(ISTAR,JSTAR)
             else
                if (MyGlobal) Gptr3bundle(:,:,nn)=Gptr2file
             end if
          end do
          if (single_point) then
             ptr3(1,1,:) = Gptr3bundle(1,1,:)
          else
             if ( (.not.RegridCnv) .and. runParallel) then
                call MAPL_CollectiveScatter3D(esmfgrid,Gptr3bundle(:,:,:nn),ptr3,hw=hw,rc=status)
                _VERIFY(STATUS)
             else if ( (.not.RegridCnv) .and. (.not.RunParallel) ) then
                do K=1,LM
                   L1 = LBOUND(PTR3,3)-1
                   call ArrayScatter(PTR3(:,:,K+L1), Gptr3bundle(:,:,K), ESMFGRID, hw=hw, RC=STATUS)
                   _VERIFY(STATUS)
                end do
             end if
             if (GSImode_) call SwapV_(PTR3)
          end if
       end select
    end do
    deallocate(krank)
    deallocate(GPtr2bundle)
    deallocate(GPtr3bundle)
    if (RegridCnv .and. change_resolution) then
       ! make sure everyone is done before potentially releasing shared memory
       call MAPL_SyncSharedMemory(rc=status)
       _VERIFY(STATUS)
       DEALOC_(GPtr2file  )
       DEALOC_(GPtr3file  )
    else
       deallocate(Gptr2file)
       deallocate(Gptr3file)
    end if
10  continue
! always do this cleanup
    deallocate(LONSfile,LATSfile)
    deallocate(LONSbundle,LATSbundle)
!@    call ESMF_CFIOVarInfoDestroy(vars, _RC)
    deallocate(VARS)
    if (selectedLevels) then
       if (allocated(levidx)) then
          deallocate(levidx)
       end if
    end if
    if (cfioIsCreated) then
       call ESMF_CFIODestroy(CFIO, rc=status)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
CONTAINS
    subroutine shift180Lon2D_ ( c, im, jm )
    integer, intent(in) :: im, jm
    real, intent(inout) :: c(im,jm)
    real :: cj(im)
    integer :: m(4), n(4), imh, j
    imh = nint(im/2.)
    m = [ 1,      imh, 1+imh,    im  ]
    n = [ 1,   im-imh, 1+im-imh, im  ]
    do j = 1, jm
       cj(n(1):n(2)) = c(m(3):m(4),j)
       cj(n(3):n(4)) = c(m(1):m(2),j)
       c(:,j) = cj
    end do
    return
    end subroutine shift180Lon2D_
    subroutine SwapV_(fld)
    implicit none
    real,intent(inout) ::  fld(:,:,:)
    real,allocatable   :: work(:,:,:)
    integer im, jm, km
    im   = size(fld,1)
    jm   = size(fld,2)
    km   = size(fld,3)
    allocate (work(im,jm,km))
    work = fld
    fld(:,:,km:1:-1) = work(:,:,1:km:+1)
    deallocate (work)
    end subroutine SwapV_
    subroutine getVarNameIgnoreCase(vname,vars,rc)
    character(len=*), intent(inout)  :: vname
    type(ESMF_CFIOVarInfo), pointer, intent(in) :: vars(:)
    integer, optional, intent(out)  :: rc
    integer :: status
    integer j
    character(len=ESMF_MAXSTR) :: cfiovarname,tname,tcfioname
    tname = vname
    tname = ESMF_UtilStringUpperCase(tname,rc=STATUS)
    _VERIFY(STATUS)
    do j=1,size(vars)
        call ESMF_CFIOVarInfoGet(vars(j),vname=cfiovarname,RC=STATUS)
        _VERIFY(STATUS)
        tcfioname = cfiovarname
        tcfioname = ESMF_UtilStringUpperCase(tcfioname,rc=STATUS)
        _VERIFY(STATUS)
        if (trim(tname) == trim(tcfioname)) then
           vname = cfiovarname
           exit
        end if
    enddo
    _RETURN(ESMF_SUCCESS)
    end subroutine getVarNameIgnoreCase
  end subroutine MAPL_CFIOReadBundle
Call graph
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread
utcfio calls test_main