MAPL_VarWrite_R8_4d – MAPL
MAPL_VarWrite_R8_4d Subroutine
15 statements
Source File
private subroutine MAPL_VarWrite_R8_4d(UNIT, GRID, A, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: UNIT
type(ESMF_Grid), intent(inout) :: GRID
real(kind=ESMF_KIND_R8), intent(in) :: A(:,:,:,:)
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_VarWrite_R8_4d
Source Code
  subroutine MAPL_VarWrite_R8_4d(UNIT, GRID, A, ARRDES, RC)
    integer                     , intent(IN   ) :: UNIT
    type (ESMF_Grid)            , intent(INout) :: GRID
    real(kind=ESMF_KIND_R8)     , intent(IN   ) :: A(:,:,:,:)
    type(ArrDescr),     optional, intent(INOUT) :: ARRDES
    integer,           optional , intent(  OUT) :: RC
! Local variables
    integer                               :: status
    integer :: L
    do L = 1, size(A,4)
       call MAPL_VarWrite(UNIT, GRID, A(:,:,:,L), ARRDES=ARRDES, rc=status)
       _VERIFY(STATUS)
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_VarWrite_R8_4d
Call graph
mapl_varwrite_r8_4d calls mapl_varwrite, mapl_return, mapl_verify
mapl_varwrite calls mapl_varwrite_r8_4d, mapl_varwrite_r8_3d, mapl_statevarwrite, mapl_varwrite_i4_1d, mapl_varwrite_r4_1d, mapl_fieldwrite, mapl_bundlewrite, mapl_varwrite_r4_2d, mapl_varwrite_r4_3d, mapl_varwrite_r4_4d, mapl_varwrite_r8_1d, mapl_varwrite_r8_2d
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
mapl_fieldwrite calls mapl_varwrite
mapl_varwrite_r4_2d calls mapl_varwrite
mapl_varwrite_r4_3d calls mapl_varwrite
mapl_varwrite_r4_4d calls mapl_varwrite
mapl_varwrite_r8_2d calls mapl_varwrite
mapl_varwrite_r8_3d calls mapl_varwrite
mapl_esmfstatewritetofile calls mapl_varwrite
run calls mapl_varwrite
writerestart calls mapl_varwrite
mapl_bundlewrite calls mapl_fieldwrite
mapl_statevarwrite calls mapl_fieldwrite, mapl_bundlewrite
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_checkpointstate calls mapl_esmfstatewritetofile
mapl_genericrecord calls mapl_staterecord
record_state calls mapl_genericstatesave
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize