MAPL_RequestService – MAPL
MAPL_RequestService Subroutine
16 statements
Source File
public subroutine MAPL_RequestService(GC, SERVICE, VARS, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
character(len=*), intent(in) :: SERVICE
character(len=*), intent(in) :: VARS(:)
integer, intent(out), optional :: RC
Calls
Source Code
   subroutine MAPL_RequestService(GC, SERVICE, VARS, RC)
      type(ESMF_GridComp),            intent(INOUT) :: GC ! Gridded component
      character (len=*),              intent(IN   ) :: SERVICE
      character (len=*),              intent(IN   ) :: VARS(:)
      integer,              optional, intent(  OUT) :: RC     ! Error code:
      integer :: status
      type (MAPL_MetaComp), pointer     :: MAPLOBJ
      type (ESMF_FieldBundle) :: bundle
      !get MAPL
      call MAPL_InternalStateRetrieve ( GC, MAPLOBJ, _RC )
      bundle = ESMF_FieldBundleCreate(NAME=SERVICE, _RC)
      call maplobj%requested_services%push_back( &
           RequestedServiceType( &
           service_name=service, &
           var_list = vars, &
           bundle = bundle ))
      _RETURN(ESMF_SUCCESS)
   end subroutine MAPL_RequestService
Call graph
mapl_requestservice calls esmf_fieldbundlecreate, mapl_internalstateretrieve, mapl_return, mapl_verify, v_push_back
mapl_internalstateretrieve calls mapl_return, mapl_verify, mapl_internalstatecreate, mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_internalstatecreate calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompSetInternalState, get_component, initialize, set_composite
mapl_internalstateget calls mapl_return, mapl_verify, ESMF_GridCompGet, ESMF_UserCompGetInternalState
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize