MAPL_ExtDataFlipVertical – MAPL
MAPL_ExtDataFlipVertical Subroutine
53 statements
Source File
private subroutine MAPL_ExtDataFlipVertical(item, filec, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
integer, intent(in) :: filec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataFlipVertical(item,filec,rc)
      type(PrimaryExport), intent(inout)      :: item
      integer,                  intent(in)    :: filec
      integer, optional, intent(out)          :: rc
      integer :: status
      type(ESMF_Field) :: Field,field1,field2
      real, pointer    :: ptr(:,:,:)
      real, allocatable :: ptemp(:,:,:)
      integer :: ls, le
      if (item%isVector) then
         if (item%do_Fill .or. item%do_VertInterp) then
            call MAPL_ExtDataGetBracket(item,filec,field=Field1,vcomp=1,getRL=.true.,_RC)
            call MAPL_ExtDataGetBracket(item,filec,field=Field2,vcomp=2,getRL=.true.,_RC)
         else
            call MAPL_ExtDataGetBracket(item,filec,field=Field1,vcomp=1,_RC)
            call MAPL_ExtDataGetBracket(item,filec,field=Field2,vcomp=2,_RC)
         end if
         call ESMF_FieldGet(Field1,0,farrayPtr=ptr,rc=status)
         _VERIFY(STATUS)
         allocate(ptemp,source=ptr,stat=status)
         _VERIFY(status)
         ls = lbound(ptr,3)
         le = ubound(ptr,3)
         ptr(:,:,le:ls:-1) = ptemp(:,:,ls:le:+1)
         call ESMF_FieldGet(Field2,0,farrayPtr=ptr,rc=status)
         _VERIFY(STATUS)
         ptemp=ptr
         ptr(:,:,le:ls:-1) = ptemp(:,:,ls:le:+1)
         deallocate(ptemp)
      else
         if (item%do_Fill .or. item%do_VertInterp) then
            call MAPL_ExtDataGetBracket(item,filec,field=Field,getRL=.true.,_RC)
         else
            call MAPL_ExtDataGetBracket(item,filec,field=Field,_RC)
         end if
         call ESMF_FieldGet(Field,0,farrayPtr=ptr,rc=status)
         _VERIFY(STATUS)
         allocate(ptemp,source=ptr,stat=status)
         _VERIFY(status)
         ls = lbound(ptr,3)
         le = ubound(ptr,3)
         ptr(:,:,le:ls:-1) = ptemp(:,:,ls:le:+1)
         deallocate(ptemp)
      end if
      _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataFlipVertical
Call graph
mapl_extdataflipvertical calls esmf_fieldget, mapl_extdatagetbracket, mapl_return, mapl_verify
mapl_extdatagetbracket calls mapl_return, mapl_verify, get_parameters
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_parameters calls mapl_return, mapl_assert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_extdataverticalinterpolate calls mapl_extdataflipvertical
run_ calls mapl_extdataverticalinterpolate