MAPL_ExtDataFillField – MAPL
MAPL_ExtDataFillField Subroutine
40 statements
Source File
private subroutine MAPL_ExtDataFillField(item, FieldF, FieldR, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_Field), intent(inout) :: FieldF
type(ESMF_Field), intent(inout) :: FieldR
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine MAPL_ExtDataFillField(item,FieldF,FieldR,rc)
  type(PrimaryExport), intent(inout) :: item
  type(ESMF_Field), intent(inout) :: FieldF
  type(ESMF_Field), intent(inout) :: FieldR
  integer, optional, intent(out)  :: rc
  integer :: status
  real, pointer :: ptrF(:,:,:),ptrR(:,:,:)
  integer :: lm_in,lm_out,i
  call ESMF_FieldGet(FieldF,0,farrayPtr=ptrF,_RC)
  call ESMF_FieldGet(FieldR,0,farrayPtr=ptrR,_RC)
  ptrF = 0.0
  lm_in= size(ptrR,3)
  lm_out = size(ptrF,3)
  _ASSERT(lm_out > lm_in, "trying to fillin but destination has less levels than source")
  if (trim(item%importVDir)=="down") then
     if (trim(item%vcoord%positive)=="down") then
        do i=1,lm_in
           ptrF(:,:,lm_out-lm_in+i)=ptrR(:,:,i)
        enddo
     else if (trim(item%vcoord%positive)=="up") then
        do i=1,lm_in
           ptrF(:,:,lm_out-i+1)=ptrR(:,:,i)
        enddo
     end if
  else if (trim(item%importVDir)=="up") then
     if (trim(item%vcoord%positive)=="down") then
        do i=1,lm_in
           ptrF(:,:,lm_in-i+1)=ptrR(:,:,i)
        enddo
     else if (trim(item%vcoord%positive)=="up") then
        do i=1,lm_in
           ptrF(:,:,i)=ptrR(:,:,i)
        enddo
     end if
  end if
  _RETURN(ESMF_SUCCESS)
  end subroutine MAPL_ExtDataFillField
Call graph
mapl_extdatafillfield calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_extdataverticalinterpolate calls mapl_extdatafillfield
run_ calls mapl_extdataverticalinterpolate