MAPL_HeapSet – MAPL
MAPL_HeapSet Subroutine
13 statements
Source File
public subroutine MAPL_HeapSet(HeapSize, RC)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: HeapSize
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
MAPL_HeapSet
Source Code
    subroutine MAPL_HeapSet(HeapSize, RC)
      integer, optional, intent(IN   ) :: HeapSize
      integer, optional, intent(OUT  ) :: RC
      integer :: status
      _ASSERT(.not.associated(HEAP%BUFFER),'needs informative message')
      if(present(HeapSize)) then
         _ASSERT(HeapSize > 0,'needs informative message')
         allocate(HEAP%BUFFER(1:HeapSize), STAT=STATUS)
         _VERIFY(STATUS)
      end if
      _RETURN(_SUCCESS)
    end subroutine MAPL_HeapSet
Call graph
mapl_heapset calls mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_alloc_r_2d calls mapl_heapset
mapl_alloc calls mapl_alloc_r_2d