matchbgn – MAPL
matchbgn Function
11 statements
Source File
public function matchbgn(string, substring)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: substring
Return Value logical
Called by
Source Code
  function matchbgn ( string, substring )
    ! only begin with
    ! string:  main-str
    ! substring:  sub-str
    IMPLICIT NONE
    CHARACTER (LEN=*), INTENT(IN) :: string, substring
    LOGICAL                       :: matchbgn
    if (index(string, substring).eq.1) then
       matchbgn = .TRUE.
    else
       matchbgn = .FALSE.
    endif
    return
  end function matchbgn
Call graph
scan_begin calls matchbgn
scan_count_match_bgn calls matchbgn
regen_rcx_for_obs_platform calls scan_begin, scan_count_match_bgn
initialize calls regen_rcx_for_obs_platform