mem_dump – MAPL
mem_dump Subroutine
73 statements
Source File
private subroutine mem_dump(memhwm, memrss, memused, swapused, commitlimit, committed_as, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: memhwm
real, intent(out) :: memrss
real, intent(out) :: memused
real, intent(out) :: swapused
real, intent(out) :: commitlimit
real, intent(out) :: committed_as
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
mem_dump
Source Code
subroutine mem_dump (memhwm, memrss, memused, swapused, commitlimit, committed_as, RC)
real, intent(out) :: memhwm, memrss, memused, swapused, commitlimit, committed_as
integer, optional, intent(OUT) :: RC
! This routine returns the memory usage on Linux systems.
! It does this by querying a system file (file_name below).
character(len=32) :: proc_self = '/proc/self/status'
character(len=32) :: meminfo   = '/proc/meminfo'
character(len=32) :: string
integer(kind=INT64) :: memtot, memfree, swaptot, swapfree
integer :: mem_unit
real    :: multiplier
character(len=ESMF_MAXSTR), parameter :: IAm="MAPL_MemUtils:mem_dump"
integer :: status
  memhwm = 0.0
  memrss = 0.0
  multiplier = 1.0
  call get_unit(mem_unit)
  open(UNIT=mem_unit,FILE=proc_self,FORM='formatted',IOSTAT=STATUS)
  _VERIFY(STATUS)
  do; read (mem_unit,'(a)', end=10) string
    if ( INDEX ( string, 'VmHWM:' ) == 1 ) then  ! High Water Mark
      read (string(7:LEN_TRIM(string)-2),*) memhwm
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      memhwm = memhwm * multiplier
    endif
    if ( INDEX ( string, 'VmRSS:' ) == 1 ) then  ! Resident Memory
      read (string(7:LEN_TRIM(string)-2),*) memrss
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      memrss = memrss * multiplier
    endif
  enddo
10 close(mem_unit)
  call get_unit(mem_unit)
  open(UNIT=mem_unit,FILE=meminfo,FORM='formatted',IOSTAT=STATUS)
  _VERIFY(STATUS)
  do; read (mem_unit,'(a)', end=20) string
    if ( INDEX ( string, 'MemTotal:' ) == 1 ) then  ! High Water Mark
      read (string(10:LEN_TRIM(string)-2),*) memtot
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      memtot = memtot * multiplier
    endif
    if ( INDEX ( string, 'MemFree:' ) == 1 ) then  ! High Water Mark
      read (string(9:LEN_TRIM(string)-2),*) memfree
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      memfree = memfree * multiplier
    endif
    if ( INDEX ( string, 'SwapTotal:' ) == 1 ) then  ! Resident Memory
      read (string(11:LEN_TRIM(string)-2),*) swaptot
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      swaptot = swaptot * multiplier
    endif
    if ( INDEX ( string, 'SwapFree:' ) == 1 ) then  ! Resident Memory
      read (string(10:LEN_TRIM(string)-2),*) swapfree
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      swapfree = swapfree * multiplier
    endif
    if ( INDEX ( string, 'CommitLimit:' ) == 1 ) then  ! Resident Memory
      read (string(13:LEN_TRIM(string)-2),*) commitlimit
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      commitlimit = commitlimit * multiplier
    endif
    if ( INDEX ( string, 'Committed_AS:' ) == 1 ) then  ! Resident Memory
      read (string(14:LEN_TRIM(string)-2),*) committed_as
      if (TRIM(string(LEN_TRIM(string)-1:)) == "kB" ) &
        multiplier = 1.0/1024. ! Convert from kB to MB
      committed_as = committed_as * multiplier
    endif
  enddo
20 close(mem_unit)
   memused = memtot-memfree
   swapused = swaptot-swapfree
   _RETURN(ESMF_SUCCESS)
end subroutine mem_dump
Call graph
mem_dump calls get_unit, mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_memutilswritecomm calls mem_dump
mapl_memutilswritevm calls mapl_memutilswritecomm
mapl_memutilswrite calls mapl_memutilswritecomm, mapl_memutilswritevm
test_main calls mapl_memutilswrite
run_mapl_gridcomp calls mapl_memutilswrite
mapl_genericinitialize calls mapl_memutilswrite
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
utcfio calls test_main
run_gc calls run_mapl_gridcomp
my_initialize calls mapl_genericinitialize