merge – MAPL
merge Subroutine
41 statements
Source File
private subroutine merge(this, meta, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
class(FileMetadata), intent(in), target :: meta
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine merge(this, meta,rc)
      class (FileMetadata), target, intent(inout) :: this
      class (FileMetadata), target, intent(in) :: meta
      integer, optional, intent(out) :: rc
      type (StringIntegerMap), pointer :: dims
      type (StringVariableMap), pointer :: vars
      type (StringAttributeMap), pointer :: atts
      type (StringIntegerMapIterator) :: dim_iter
      type (StringVariableMapIterator):: var_iter
      type (StringAttributeMapIterator) :: att_iter
      type (Variable), pointer  :: var
      type (Attribute), pointer :: att
      character(len=:), pointer :: name
      integer :: extent
      ! merge dims
      dims => meta%get_dimensions()
      dim_iter = dims%begin()
      do while (dim_iter /= dims%end())
        name => dim_iter%key()
        extent = dim_iter%value()
        call this%add_dimension(name, extent)
        call dim_iter%next()
      end do
      ! merge attribute
      atts => meta%get_attributes()
      att_iter = atts%begin()
      do while (att_iter /= atts%end())
        name => att_iter%key()
        att => att_iter%value()
        call this%add_attribute(name, att)
        call att_iter%next()
      enddo
      ! merge variables
      vars => meta%get_variables()
      var_iter = vars%begin()
      do while (var_iter /= vars%end())
        name => var_iter%key()
        var  => var_iter%value()
        call this%add_variable(name, var)
        call var_iter%next()
      end do
      _RETURN(_SUCCESS)
   end subroutine merge
Call graph
merge calls begin, key, next, add_attribute, add_dimension, add_variable, get_attributes, get_dimensions, get_variables, mapl_return
add_dimension calls mapl_return, insert
add_variable calls begin, next, mapl_return, at, get, mapl_assert, insert, get_const_value, get_dimensions, get_shape, is_empty, push_back
get_attributes calls mapl_return, get_attributes
get_variables calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_0d calls mapl_return, add_attribute
add_attribute_1d calls mapl_return, add_attribute
get_error_message calls at, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_throw_exception calls initialize