mid_pt_sphere – MAPL
mid_pt_sphere Function
11 statements
Source File
private function mid_pt_sphere(p1, p2) result(pm)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: p1(2)
real(kind=REAL64), intent(in) :: p2(2)
Return Value real(kind=REAL64), (2)
Calls
Called by
Contents
Source Code
mid_pt_sphere
Source Code
   function mid_pt_sphere(p1, p2) result(pm)
      real(REAL64) , intent(IN)  :: p1(2), p2(2)
      real(REAL64) :: pm(2)
      real(REAL64) :: e1(3), e2(3), e3(3),dd
      e1 = latlon2xyz(p1,right_Hand=.true.)
      e2 = latlon2xyz(p2,right_Hand=.true.)
      e3 = e1+e2
      dd = sqrt(dot_product(e3,e3))
      e3 = e3 / dd
      pm = xyz2latlon(e3)
   end function mid_pt_sphere
Call graph
mid_pt_sphere calls latlon2xyz, xyz2latlon
computegridbasis calls mid_pt_sphere
get_basis calls computegridbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis