mk_field_common – MAPL
mk_field_common Function
22 statements
Source File
public function mk_field_common(tk, regDecomp, minIndex, maxIndex, indexflag, name, ungriddedLBound, ungriddedUBound, rc) result(field)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TypeKind_Flag), intent(in) :: tk
integer, intent(in), dimension(:) :: regDecomp
integer, intent(in), dimension(:) :: minIndex
integer, intent(in), dimension(:) :: maxIndex
type(ESMF_Index_Flag), intent(in) :: indexflag
character(len=*), intent(in) :: name
integer, intent(in), optional :: ungriddedLBound(:)
integer, intent(in), optional :: ungriddedUBound(:)
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Called by
Source Code
   function mk_field_common(tk, regDecomp, minIndex, maxIndex, indexflag, name, ungriddedLBound, ungriddedUBound, rc) result(field)
      type(ESMF_TypeKind_Flag), intent(in) :: tk
      integer, dimension(:), intent(in) :: regDecomp
      integer, dimension(:), intent(in) :: minIndex
      integer, dimension(:), intent(in) :: maxIndex
      type(ESMF_Index_Flag), intent(in) :: indexflag
      character(len=*), intent(in) :: name
      integer, optional, intent(in) :: ungriddedLBound(:)
      integer, optional, intent(in) :: ungriddedUBound(:)
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: GRID_SUFFIX = '_grid'
      character(len=*), parameter :: FIELD_SUFFIX = '_field'
      type(ESMF_Field) :: field
      type(ESMF_Grid) :: grid
      integer :: status
      grid = mk_grid(regDecomp=regDecomp, minIndex=minIndex, maxIndex=maxIndex, indexflag = indexflag, grid_name = name // GRID_SUFFIX, _RC)
      field = ESMF_FieldCreate(grid, typekind = tk, name = name // FIELD_SUFFIX, ungriddedLBound = ungriddedLBound, ungriddedUBound = ungriddedUBound, _RC)
      _RETURN(_SUCCESS)
   end function mk_field_common
Call graph
mk_field_common calls esmf_fieldcreate, mapl_return, mapl_verify, mk_grid
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mk_grid calls mapl_return, mapl_verify, ESMF_GridCreateNoPeriDim
get_error_message calls at, insert
mapl_throw_exception calls initialize
mk_field_r4_2d calls mk_field_common
mk_field_r4_ungrid calls mk_field_common
mk_field_r8_2d calls mk_field_common
mk_field calls mk_field_r4_2d, mk_field_r8_2d
set_up_data calls mk_field_r4_ungrid, mk_field
test_fieldconvertprec_r4r8 calls mk_field