mk_field_r4_ungrid – MAPL
mk_field_r4_ungrid Function
16 statements
Source File
public function mk_field_r4_ungrid(regDecomp, minIndex, maxIndex, indexflag, name, ungriddedLBound, ungriddedUBound, rc) result(field)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: regDecomp
integer, intent(in), dimension(:) :: minIndex
integer, intent(in), dimension(:) :: maxIndex
type(ESMF_Index_Flag), intent(in) :: indexflag
character(len=*), intent(in) :: name
integer, intent(in), optional :: ungriddedLBound(:)
integer, intent(in), optional :: ungriddedUBound(:)
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Called by
Contents
Source Code
mk_field_r4_ungrid
Source Code
   function mk_field_r4_ungrid(regDecomp, minIndex, maxIndex, indexflag, name, ungriddedLBound, ungriddedUBound, rc) result(field)
      integer, dimension(:), intent(in) :: regDecomp
      integer, dimension(:), intent(in) :: minIndex
      integer, dimension(:), intent(in) :: maxIndex
      type(ESMF_Index_Flag), intent(in) :: indexflag
      character(len=*), intent(in) :: name
      integer, optional, intent(in) :: ungriddedLBound(:)
      integer, optional, intent(in) :: ungriddedUBound(:)
      integer, optional, intent(out) :: rc
      type(ESMF_Field) :: field
      integer :: status
      field = mk_field_common(tk = ESMF_TYPEKIND_R4, regDecomp=regDecomp, minIndex=minIndex, maxIndex=maxIndex, indexflag = indexflag, name = name, ungriddedLBound=ungriddedLBound, ungriddedUBound=ungriddedUBound, _RC)
      _RETURN(_SUCCESS)
   end function mk_field_r4_ungrid
Call graph
mk_field_r4_ungrid calls mapl_return, mapl_verify, mk_field_common
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mk_field_common calls mapl_return, mapl_verify, esmf_fieldcreate, mk_grid
get_error_message calls at
mapl_throw_exception calls initialize
mk_grid calls mapl_return, mapl_verify, ESMF_GridCreateNoPeriDim
set_up_data calls mk_field_r4_ungrid