mk_r4field – MAPL
mk_r4field Function
11 statements
Source File
public function mk_r4field(r4array, field_name, rc) result(r4field)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: r4array(:,:)
character(len=*), intent(in) :: field_name
integer, intent(out), optional :: rc
Return Value type(ESMF_Field)
Calls
Called by
Source Code
   function mk_r4field(r4array, field_name, rc) result(r4field)
      type(ESMF_Field) :: r4field
      real(kind=ESMF_KIND_R4), intent(in) :: r4array(:,:)
      character(len=*), intent(in) :: field_name
      integer, optional, intent(out) :: rc
      integer :: status
      r4field = mk_field(r4array, name = field_name, _RC)
      _RETURN(_SUCCESS)
   end function mk_r4field
Call graph
mk_r4field calls mk_field, mapl_return, mapl_verify
mk_field calls mk_field_r4_2d, mk_field_r8_2d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mk_field_r4_2d calls mapl_return, mapl_verify, esmf_fieldget, mk_field_common
mk_field_r8_2d calls mapl_return, mapl_verify, esmf_fieldget, mk_field_common
mk_field_common calls mapl_return, mapl_verify, esmf_fieldcreate, mk_grid
test_fieldaddr4 calls mk_r4field