model_finalize – MAPL
model_finalize Subroutine
17 statements
Source File
private subroutine model_finalize(model, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
integer, intent(out) :: rc
Calls
Source Code
    subroutine model_finalize(model, rc)
        type(ESMF_GridComp)  :: model
        integer, intent(out) :: rc
        type(MAPL_Cap),     pointer :: cap
        class(BaseProfiler), pointer :: t_p
        cap => get_cap_from_gc(model, rc)
        _VERIFY(rc)
        call cap%cap_gc%finalize(rc=rc)
        _VERIFY(rc)
        call cap%finalize_io_clients_servers(rc=rc)
        _VERIFY(rc)
        t_p => get_global_time_profiler()
        call t_p%stop()
        call cap%splitter%free_sub_comm()
        _RETURN(_SUCCESS)
    end subroutine model_finalize
Call graph
model_finalize calls finalize_io_clients_servers, finalize, free_sub_comm, get_cap_from_gc, get_global_time_profiler, mapl_return, mapl_verify
finalize_io_clients_servers calls mapl_return, finalize, get_name, get_splitcomm, terminate
finalize calls mapl_return, mapl_verify, ESMF_GridCompFinalize, free_sub_comm, free_directory_resources, report_profile
free_sub_comm calls mpi_comm_free
get_cap_from_gc calls mapl_return, ESMF_LogFoundError, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_splitcomm calls mapl_return
mapl_throw_exception calls initialize
terminate calls mapl_return, mapl_verify, at, terminate, wait_all