model_advance – MAPL
model_advance Subroutine
11 statements
Source File
private subroutine model_advance(model, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
integer, intent(out) :: rc
Calls
Source Code
    subroutine model_advance(model, rc)
        type(ESMF_GridComp)  :: model
        integer, intent(out) :: rc
        type(MAPL_Cap), pointer :: cap
        cap => get_cap_from_gc(model, rc)
        VERIFY_NUOPC_(rc)
        call cap%step_model(rc=rc)
        _VERIFY(rc)
        _RETURN(_SUCCESS)
    end subroutine model_advance
Call graph
model_advance calls ESMF_LogFoundError, get_cap_from_gc, mapl_return, mapl_verify, step_model
get_cap_from_gc calls ESMF_LogFoundError, mapl_return, ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
step_model calls mapl_return, mapl_verify, step
get_error_message calls at, insert
mapl_throw_exception calls initialize
step calls mapl_return, mapl_verify, ESMF_ClockAdvance, ESMF_ClockGet, ESMF_GridCompGet, ESMF_GridCompRun, ESMF_GridCompWriteRestart, ESMF_TimeGet, ESMF_VMBarrier, mapl_am_i_root, mpi_wtime, get_step_counter, mapl_memcommited, mapl_memused, perpetual_clock