modify_metadata – MAPL
modify_metadata Subroutine
21 statements
Source File
private subroutine modify_metadata(this, collection_id, unusable, var_map, rc)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(in) :: collection_id
class(KeywordEnforcer), intent(out), optional :: unusable
type(StringVariableMap), intent(in), optional :: var_map
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine modify_metadata(this, collection_id, unusable,var_map, rc)
      class (ClientThread), intent(inout) :: this
      integer, intent(in) :: collection_id
      class (KeywordEnforcer), optional, intent(out) :: unusable
      type (StringVariableMap), optional,intent(in) :: var_map
      integer, optional, intent(out) :: rc
      class (AbstractMessage), pointer :: handshake_msg
      class(AbstractSocket),pointer :: connection
      integer :: status
      connection=>this%get_connection()
      call connection%send(ModifyMetadataMessage( &
           collection_id, &
           var_map=var_map),_RC)
      handshake_msg => connection%receive()
      deallocate(handshake_msg)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine modify_metadata
Call graph
modify_metadata calls get_connection, mapl_return, mapl_verify, receive, send, modify_metadata
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
modify_metadata_all calls modify_metadata
run calls modify_metadata, modifytime
mapl_bundlewritencpar calls modify_metadata
modifytime calls modify_metadata, modifytime
run_model calls modify_metadata
main calls run, run_model, start_new_file
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
start_new_file calls modifytime
mapl_esmfstatewritetofile calls mapl_varwritencpar
time_ave calls start_new_file