modify_variable – MAPL
modify_variable Subroutine
26 statements
Source File
private subroutine modify_variable(this, var_name, var, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: var_name
class(Variable), intent(in), target :: var
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine modify_variable(this, var_name, var, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: var_name
      class (Variable), target, intent(in) :: var
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type (StringVector), pointer :: dims
      type (StringVectorIterator) :: iter
      integer, pointer :: dim_this
      character(len=:), pointer :: dim_name
      ! ensure all of var's dimensions are defined
      dims => var%get_dimensions()
      iter = dims%begin()
      do while (iter /= dims%end())
         dim_name => iter%get()
         dim_this => this%dimensions%at(dim_name)
         _ASSERT( associated(dim_this), "FileMetadata:: modify_variable() - undefined dimension " // dim_name )
         call iter%next()
      end do
      call this%variables%set(var_name, var)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine modify_variable
Call graph
modify_variable calls at, begin, get, mapl_assert, next, get_dimensions, m_set, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_set calls s_insert
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
create_file_handle calls modify_variable, create_file_handle
modifymetadata calls modify_variable
modifytime calls modify_variable
test_equal_diff_variables calls modify_variable
handle_modifymetadata calls modifymetadata
run calls modifytime
start_new_file calls modifytime
main calls start_new_file
time_ave calls start_new_file
regrid_util calls main