modify_dimension – MAPL
modify_dimension Subroutine
14 statements
Source File
private subroutine modify_dimension(this, dim_name, extent, unusable, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout), target :: this
character(len=*), intent(in) :: dim_name
integer, intent(in) :: extent
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine modify_dimension(this, dim_name, extent, unusable, rc)
      class (FileMetadata), target, intent(inout) :: this
      character(len=*), intent(in) :: dim_name
      integer, intent(in) :: extent
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      call this%dimensions%set(dim_name, extent)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine modify_dimension
Call graph
modify_dimension calls mapl_return, set
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_file_handle calls modify_dimension
mapl_iochangeres calls modify_dimension