modifyTimeIncrement – MAPL
modifyTimeIncrement Subroutine
14 statements
Source File
private subroutine modifyTimeIncrement(this, frequency, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
integer, intent(in) :: frequency
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine modifyTimeIncrement(this, frequency, rc)
        class(MAPL_GriddedIO), intent(inout) :: this
        integer, intent(in) :: frequency
        integer, optional, intent(out) :: rc
        integer :: status
        if (this%timeInfo%is_initialized) then
           call this%timeInfo%setFrequency(frequency, rc=status)
           _VERIFY(status)
        else
           _FAIL("Time was not initialized for the GriddedIO class instance")
        end if
        _RETURN(ESMF_SUCCESS)
      end subroutine modifyTimeIncrement
Call graph
modifytimeincrement calls mapl_assert, mapl_return, mapl_verify, setfrequency
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
setfrequency calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
run calls modifytimeincrement