modify_metadata_all – MAPL
modify_metadata_all Subroutine
20 statements
Source File
private subroutine modify_metadata_all(this, collection_id, unusable, var_map, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
integer, intent(in) :: collection_id
class(KeywordEnforcer), intent(out), optional :: unusable
type(StringVariableMap), intent(in), optional :: var_map
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine modify_metadata_all(this, collection_id, unusable,var_map,rc)
      class (ClientManager), intent(inout) :: this
      integer, intent(in) :: collection_id
      class (KeywordEnforcer), optional, intent(out) :: unusable
      type (StringVariableMap), optional,intent(in) :: var_map
      integer, optional, intent(out) :: rc
      class (ClientThread), pointer :: clientPtr
      integer :: i, status
      do i = 1, this%clients%size()
         ClientPtr => this%clients%at(i)
         call clientPtr%modify_metadata(collection_id, var_map = var_map, rc=status)
         _VERIFY(status)
      enddo
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine modify_metadata_all
Call graph
modify_metadata_all calls at, mapl_return, mapl_verify, modify_metadata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
modify_metadata calls mapl_return, mapl_verify, get_connection, receive, send
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code