my_initialize – MAPL
my_initialize Subroutine
12 statements
Source File
private subroutine my_initialize(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
my_initialize
Source Code
  subroutine my_initialize(gc, import, export, clock, rc)
     type(ESMF_GridComp), intent(inout) :: gc
     type(ESMF_State), intent(inout) :: import
     type(ESMF_State), intent(inout) :: export
     type(ESMF_Clock), intent(inout) :: clock
     integer, intent(out), optional :: rc
     integer :: status
     call MAPL_GenericInitialize(gc, import, export, clock, _RC)
     _RETURN(_SUCCESS)
  end subroutine my_initialize
Call graph
my_initialize calls mapl_genericinitialize, mapl_return, mapl_verify
mapl_genericinitialize calls mapl_return, mapl_verify, esmf_stateadd, mapl_memutilswrite, mapl_adjustisneeded, esmfl_gridcoordget, esmf_utilstringlowercase, esmf_gridcompget, esmf_vmgetcurrent, mapl_internalstateget, esmf_gridget, mapl_gridget, esmf_attributeget, mapl_timeron, mapl_getnumsubtiles, mapl_locstreamget, mapl_getimsjms, mapl_locstreamadjustnsubtiles, mapl_getresource, esmf_vmget, esmf_gridcompset, esmf_distgridget, mapl_distgridget, mapl_assert, esmf_statecreate, esmf_attributeset, mapl_timeroff, mapl_locstreamisassociated
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception