my_initialize – MAPL
my_initialize Subroutine
12 statements
Source File
private subroutine my_initialize(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
my_initialize
Source Code
  subroutine my_initialize(gc, import, export, clock, rc)
     type(ESMF_GridComp), intent(inout) :: gc
     type(ESMF_State), intent(inout) :: import
     type(ESMF_State), intent(inout) :: export
     type(ESMF_Clock), intent(inout) :: clock
     integer, intent(out), optional :: rc
     integer :: status
     call MAPL_GenericInitialize(gc, import, export, clock, _RC)
     _RETURN(_SUCCESS)
  end subroutine my_initialize
Call graph
my_initialize calls mapl_genericinitialize, mapl_verify, mapl_return
mapl_genericinitialize calls mapl_verify, mapl_return, esmf_statecreate, mapl_timeroff, esmf_attributeset, mapl_locstreamisassociated, esmf_utilstringlowercase, mapl_getimsjms, mapl_assert, esmf_gridcompget, mapl_internalstateget, esmf_vmgetcurrent, esmf_gridcompset, mapl_locstreamget, esmfl_gridcoordget, mapl_distgridget, mapl_getnumsubtiles, esmf_vmget, esmf_gridget, mapl_getresource, mapl_adjustisneeded, esmf_stateadd, esmf_distgridget, mapl_gridget, esmf_attributeget, mapl_locstreamadjustnsubtiles, mapl_memutilswrite, mapl_timeron
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message