my_run – MAPL
my_run Subroutine
14 statements
Source File
private subroutine my_run(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
my_run
Source Code
  subroutine my_run(gc, import, export, clock, rc)
     type(ESMF_GridComp), intent(inout) :: gc
     type(ESMF_State), intent(inout) :: import
     type(ESMF_State), intent(inout) :: export
     type(ESMF_Clock), intent(inout) :: clock
     integer, intent(out), optional :: rc
     real, pointer :: ptr_2d(:,:)
     integer :: status
     call MAPL_GetPointer(import,ptr_2d,'field1',_RC)
     write(*,*)"BBB import 1 maxval: ",maxval(ptr_2d)
     _RETURN(_SUCCESS)
  end subroutine my_run
Call graph
my_run calls esmfl_stategetpointertodata, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_stategetptrtodatar4_1 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
mapl_throw_exception calls initialize
mapl_allocatecoupling calls mapl_allocatecoupling