my_run – MAPL
my_run Subroutine
22 statements
Source File
private subroutine my_run(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
my_run
Source Code
  subroutine my_run(gc, import, export, clock, rc)
     type(ESMF_GridComp), intent(inout) :: gc
     type(ESMF_State), intent(inout) :: import
     type(ESMF_State), intent(inout) :: export
     type(ESMF_Clock), intent(inout) :: clock
     integer, intent(out), optional :: rc
     real, pointer :: ptr_2d(:,:)
     type(ESMF_Time) :: current_time, start_time
     type(ESMF_TimeInterval) :: time_interval
     real(ESMF_KIND_R8) :: relative_time
     integer :: status
     call MAPL_GetPointer(export,ptr_2d,'field1',_RC)
     call ESMF_ClockGet(clock,currTime=current_time,startTime=start_time,_RC)
     time_interval = current_time - start_time
     call ESMF_TimeIntervalGet(time_interval,h_r8=relative_time,_RC)
     if (associated(ptr_2d)) ptr_2d = relative_time
     _RETURN(_SUCCESS)
  end subroutine my_run
Call graph
my_run calls esmfl_stategetpointertodata, mapl_verify, esmf_clockget, esmf_timeintervalget, mapl_return
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
esmfl_stategetptrtodatar4_1 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar4_3 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_1 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar4_2 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar4_4 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_2 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_3 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
esmfl_stategetptrtodatar8_4 calls mapl_verify, mapl_return, esmf_stateget, mapl_allocatecoupling, esmf_fieldget
mapl_throw_exception calls initialize
mapl_allocatecoupling calls mapl_allocatecoupling