my_run – MAPL
my_run Subroutine
23 statements
Source File
private subroutine my_run(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
my_run
Source Code
  subroutine my_run(gc, import, export, clock, rc)
     type(ESMF_GridComp), intent(inout) :: gc
     type(ESMF_State), intent(inout) :: import
     type(ESMF_State), intent(inout) :: export
     type(ESMF_Clock), intent(inout) :: clock
     integer, intent(out), optional :: rc
     real, pointer :: ptr_2d(:,:), ptr_3d(:,:,:)
     type (MAPL_MetaComp),      pointer  :: MAPL
     real :: my_constant
     integer :: status
     call MAPL_GetObjectFromGC ( GC, MAPL, _RC)
     call MAPL_GetResource(MAPL, my_constant, Label="my_value:", default=17.0,_RC)
     call MAPL_GetPointer(export,ptr_2d,'output1',_RC)
     if (associated(ptr_2d)) ptr_2d = my_constant
     call MAPL_GetPointer(export,ptr_3d,'output2',_RC)
     if (associated(ptr_3d)) ptr_3d = my_constant
     _RETURN(_SUCCESS)
  end subroutine my_run
Call graph
my_run calls mapl_getobjectfromgc, mapl_return, mapl_getresource, mapl_verify, esmfl_stategetpointertodata
mapl_getobjectfromgc calls mapl_internalstateget
mapl_return calls get_error_message, mapl_throw_exception
mapl_getresource calls mapl_getresource_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_scalar
mapl_verify calls mapl_throw_exception
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_4
esmfl_stategetptrtodatar8_3 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
mapl_internalstateget calls mapl_return, mapl_verify, esmf_gridcompget, esmf_usercompgetinternalstate
mapl_getresource_array calls mapl_return, mapl_verify, mapl_getresource_config_array
mapl_throw_exception calls initialize
mapl_getresourcefromconfig_scalar calls mapl_return, mapl_verify, mapl_getresource_config_scalar
mapl_getresourcefrommapl_scalar calls mapl_return, mapl_verify, mapl_getresource_config_scalar
esmfl_stategetptrtodatar4_1 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar4_4 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls mapl_return, mapl_verify, esmf_stateget, esmf_fieldget, mapl_allocatecoupling