my_run – MAPL
my_run Subroutine
22 statements
Source File
private subroutine my_run(gc, import, export, clock, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: gc
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: rc
Calls
Contents
Source Code
my_run
Source Code
  subroutine my_run(gc, import, export, clock, rc)
     type(ESMF_GridComp), intent(inout) :: gc
     type(ESMF_State), intent(inout) :: import
     type(ESMF_State), intent(inout) :: export
     type(ESMF_Clock), intent(inout) :: clock
     integer, intent(out), optional :: rc
     type(MAPL_MetaComp), pointer :: MAPL
     real, pointer :: ptr_2d(:,:)
     real :: my_constant
     integer :: status
     call MAPL_GetObjectFromGC ( GC, MAPL, _RC)
     call MAPL_GetResource(MAPL, my_constant, Label="my_value:", default=17.0,_RC)
     call MAPL_GetPointer(export,ptr_2d,'output1',_RC)
     if (associated(ptr_2d)) ptr_2d = my_constant
     call MAPL_GenericRunChildren(gc, import, export, clock, _RC)
     _RETURN(_SUCCESS)
  end subroutine my_run
Call graph
my_run calls mapl_getobjectfromgc, mapl_verify, mapl_getresource, mapl_genericrunchildren, esmfl_stategetpointertodata, mapl_return
mapl_getobjectfromgc calls mapl_internalstateget
mapl_verify calls mapl_throw_exception
mapl_getresource calls mapl_getresource_array, mapl_getresourcefrommapl_scalar, mapl_getresourcefromconfig_scalar
mapl_genericrunchildren calls mapl_getobjectfromgc, mapl_verify, mapl_return, mapl_internalstateget, esmf_gridcompget, mapl_timeron, esmf_gridcomprun, mapl_timeroff, esmf_cplcomprun
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar8_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_4
mapl_return calls mapl_throw_exception, get_error_message