nearlyEqual_real32 – MAPL
nearlyEqual_real32 Function
8 statements
Source File
private elemental function nearlyEqual_real32(r1, r2) result(yes)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: r1
real(kind=REAL32), intent(in) :: r2
Return Value logical
Called by
Contents
Call graph
nearlyequal calls nearlyequal_real32
equal_c calls nearlyequal
test_3d calls nearlyequal
test_2d calls nearlyequal
equal calls nearlyequal
test_1d calls nearlyequal
test_4d calls nearlyequal
test_scalar calls nearlyequal