new_MemoryProfiler – MAPL
new_MemoryProfiler Function
8 statements
Source File
private function new_MemoryProfiler(name, comm_world) result(prof)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(in), optional :: comm_world
Return Value type(MemoryProfiler), target
Calls
Called by
Source Code
   function new_MemoryProfiler(name, comm_world) result(prof)
      type(MemoryProfiler), target :: prof
      character(*), intent(in) :: name
      integer, optional, intent(in) :: comm_world
      call prof%set_comm_world(comm_world = comm_world)
      call prof%set_node(MeterNode(name, prof%make_meter()))
      call prof%start()
   end function new_MemoryProfiler
Call graph
new_memoryprofiler calls start, make_meter, set_comm_world, set_node
start_self calls mapl_assert, start, get_name, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
memoryprofiler calls new_memoryprofiler