new_EtaHybridVerticalCoordinate_by_cfg – MAPL
new_EtaHybridVerticalCoordinate_by_cfg Function
31 statements
Source File
private function new_EtaHybridVerticalCoordinate_by_cfg(config, unusable, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(inout), optional :: rc
Return Value type(EtaHybridVerticalCoordinate)
Calls
Called by
Contents
Source Code
new_EtaHybridVerticalCoordinate_by_cfg
Source Code
   function new_EtaHybridVerticalCoordinate_by_cfg(config, unusable, rc) result(grid)
      type (EtaHybridVerticalCoordinate) :: grid
      type (ESMF_Config) :: config
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(inout) :: rc
      real(kind=REAL64), allocatable :: ak(:)
      real(kind=REAL64), allocatable :: bk(:)
      integer :: status
      integer :: k, num_levels
      real(kind=REAL64) :: ref_pressure
      character(len=32) :: data_label
      _UNUSED_DUMMY(unusable)
      call ESMF_ConfigGetAttribute(config, num_levels,label='NUM_LEVELS:', _RC )
      call ESMF_ConfigGetAttribute(config, ref_pressure,label='REF_PRESSURE:', &
                                   default = DEFAULT_REFERENCE_PRESSURE, _RC )
      data_label = "ak-bk:"
      allocate(ak(num_levels+1), bk(num_levels+1))
      call ESMF_ConfigFindLabel(config, trim(data_label), _RC )
      ! get ak and bk
      do k = 1, num_levels+1
         call ESMF_ConfigNextLine(config, &
            _RC )
         call ESMF_ConfigGetAttribute(config, ak(k), &
            _RC )
         call ESMF_ConfigGetAttribute(config, bk(k), &
            _RC )
      enddo
      grid = EtaHybridVerticalCoordinate(ak, bk, ref_pressure=ref_pressure)
      deallocate(ak, bk)
   end function new_EtaHybridVerticalCoordinate_by_cfg
Call graph
new_etahybridverticalcoordinate_by_cfg calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine, etahybridverticalcoordinate, mapl_verify
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_cfg, new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_file
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
new_etahybridverticalcoordinate_by_ak_bk calls mapl_assert
new_etahybridverticalcoordinate_by_file calls etahybridverticalcoordinate, mapl_verify, ESMF_ConfigLoadFile
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_eta_onestep_r4 calls etahybridverticalcoordinate, get_eta
get_eta_onestep_r8 calls etahybridverticalcoordinate, get_eta
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8
get_eta_r4 calls get_eta