new_CollectivePrefetchDataMessage – MAPL
new_CollectivePrefetchDataMessage Function
13 statements
Source File
private function new_CollectivePrefetchDataMessage(request_id, collection_id, file_name, var_name, data_reference, unusable, start, global_start, global_count) result(message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: request_id
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: global_start(:)
integer, intent(in), optional :: global_count(:)
Return Value type(CollectivePrefetchDataMessage)
Calls
Called by
Source Code
   function new_CollectivePrefetchDataMessage( &
        & request_id, collection_id, file_name, var_name, &
        & data_reference, unusable, start,global_start,global_count) result(message)
      type (CollectivePrefetchDataMessage) :: message
      integer, intent(in) :: request_id
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: start(:)
      integer, optional, intent(in) :: global_start(:)
      integer, optional, intent(in) :: global_count(:)
      call message%initCollective(request_id,collection_id, &
          file_name,var_name,data_reference,unusable=unusable, &
          start=start,global_start = global_start,global_count=global_count)
   end function new_CollectivePrefetchDataMessage
Call graph
new_collectiveprefetchdatamessage calls initcollective
initcollective calls mapl_assert, init, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
init calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
collectiveprefetchdatamessage calls new_collectiveprefetchdatamessage