new_LocalMemReference – MAPL
new_LocalMemReference Function
13 statements
Source File
private function new_LocalMemReference(type_kind, shp, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer, intent(in) :: shp(:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
Calls
Called by
Contents
Source Code
new_LocalMemReference
Source Code
   function new_LocalMemReference(type_kind, shp, rc) result(reference)
      type (LocalMemReference) :: reference
      integer, intent(in) :: type_kind
      integer, intent(in) :: shp(:)
      integer, optional, intent(out) :: rc
      integer :: status
      reference%shape = shp
      reference%type_kind = type_kind
      call reference%allocate(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function new_LocalMemReference
Call graph
new_localmemreference calls mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
localmemreference calls new_localmemreference, new_localmemreference_1d, new_localmemreference_3d, new_localmemreference_5d, new_localmemreference_2d, new_localmemreference_4d, new_localmemreference_0d
new_localmemreference_1d calls localmemreference
new_localmemreference_3d calls localmemreference
new_localmemreference_5d calls localmemreference
new_localmemreference_2d calls localmemreference
new_localmemreference_4d calls localmemreference
new_localmemreference_0d calls localmemreference