new_RDMAReference – MAPL
new_RDMAReference Function
17 statements
Source File
private function new_RDMAReference(type_kind, msize_word, comm, rank, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer(kind=INT64), intent(in) :: msize_word
integer, intent(in) :: comm
integer, intent(in) :: rank
integer, intent(out), optional :: rc
Return Value type(RDMAReference)
Calls
Called by
Contents
Source Code
new_RDMAReference
Source Code
   function new_RDMAReference(type_kind,msize_word,comm, rank, rc) result(reference)
      type (RDMAReference) :: reference
      integer, intent(in) :: type_kind
      integer(kind=INT64), intent(in) :: msize_word
      integer, intent(in) :: comm
      integer, intent(in) :: rank
      integer, optional, intent(out) :: rc
      integer :: status
      reference%msize_word = msize_word
      reference%type_kind  = type_kind
      call Mpi_comm_dup(Comm,reference%comm,status)
      reference%mem_rank = rank
      call reference%allocate(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function new_RDMAReference
Call graph
new_rdmareference calls mpi_comm_dup, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
rdmareference calls new_rdmareference