new_MultiColumn – MAPL
new_MultiColumn Function
15 statements
Source File
private function new_MultiColumn(header, separator) result(column)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: header(:)
character(len=1), intent(in), optional :: separator
Return Value type(MultiColumn)
Calls
Called by
Source Code
   function new_MultiColumn(header, separator) result(column)
      character(*), intent(in) :: header(:)
      type(MultiColumn) :: column
      character(1), optional, intent(in) :: separator
      integer :: i, w, n
      w = len(header)
      n = size(header)
      allocate(character(w) :: column%shared_header(n))
      do i = 1, n
         column%shared_header(i) = header(i)
      end do
      if (present(separator)) call column%set_separator(separator)
      column%num_rows_header = column%get_num_rows_separator()
      call column%set_width(0)
   end function new_MultiColumn
Call graph
new_multicolumn calls get_num_rows_separator, set_separator, set_width
multicolumn calls new_multicolumn