new_VarspecDescriptionFromConfig – MAPL
new_VarspecDescriptionFromConfig Function
66 statements
Source File
private function new_VarspecDescriptionFromConfig(cf, nwords, rc) result(VarspecDescr)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Config), intent(inout) :: cf
integer, intent(in) :: nwords
integer, intent(out), optional :: rc
Return Value type(VarspecDescription)
Calls
Called by
Source Code
   function new_VarspecDescriptionFromConfig(cf,nwords,rc) result(VarspecDescr)
      type(VarspecDescription) :: VarspecDescr
      type(ESMF_Config), intent(inout) :: cf
      integer, intent(in) :: nwords
      logical :: lcomp
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = 'new_VarspecDescriptionFromConfig'
      integer :: status
      type(StringVector) :: svec
      integer :: i
      character(ESMF_MAXSTR) :: tmpstring
      do i=1,nwords
         call ESMF_ConfigGetAttribute(cf,tmpstring,rc=status)
         _VERIFY(status)
         if (trim(tmpstring)==',') cycle
         call svec%push_back(trim(tmpstring))
      enddo
      lcomp = (svec%size()==5 .or. svec%size()==7)
      _ASSERT(lcomp)
      VarspecDescr%short_name = svec%at(1)
      VarspecDescr%long_name = svec%at(2)
      VarspecDescr%units = svec%at(3)
      tmpstring = svec%at(4)
      if (trim(tmpstring) == 'xy') then
         VarspecDescr%dims = MAPL_DimsHorzOnly
      else if (trim(tmpstring) == 'xyz') then
         VarspecDescr%dims = MAPL_DimsHorzVert
      else if (trim(tmpstring) == 'tileonly') then
         VarspecDescr%dims = MAPL_DimsTileOnly
      end if
      tmpstring = svec%at(5)
      if (trim(tmpstring) == 'none') then
         VarspecDescr%location = MAPL_VLocationNone
      else if (trim(tmpstring) == 'c') then
         VarspecDescr%location = MAPL_VLocationCenter
      else if (trim(tmpstring) == 'e') then
         VarspecDescr%location = MAPL_VLocationEdge
      end if
      if (svec%size() == 7) then
         tmpstring = svec%at(6)
         if (trim(tmpstring)== 'agrid') then
            VarspecDescr%staggering = MAPL_AGrid
         else if (trim(tmpstring)== 'cgrid') then
            VarspecDescr%staggering = MAPL_CGrid
         else if (trim(tmpstring)== 'dgrid') then
            VarspecDescr%staggering = MAPL_DGrid
         end if
         tmpstring = svec%at(7)
         if (trim(tmpstring)== 'grid_aligned') then
            VarspecDescr%rotation = MAPL_RotateCube
         else if (trim(tmpstring)== 'latlon_aligned') then
            VarspecDescr%rotation = MAPL_RotateLL
         end if
      else
         VarspecDescr%staggering = MAPL_AGrid
         VarspecDescr%rotation = MAPL_AGrid
      end if
   end function new_VarspecDescriptionFromConfig
Call graph
new_varspecdescriptionfromconfig calls ESMF_ConfigGetAttribute, at, push_back
varspecdescription calls new_varspecdescriptionfromconfig