new_MeterNodeIterator – MAPL
new_MeterNodeIterator Function
6 statements
Source File
private function new_MeterNodeIterator(meter_node) result(iterator)
Arguments
Type Intent Optional Attributes Name
type(MeterNode), intent(in), target :: meter_node
Return Value type(MeterNodeIterator)
Called by
Contents
Source Code
new_MeterNodeIterator
Source Code
   function new_MeterNodeIterator(meter_node) result(iterator)
      type (MeterNode), target, intent(in) :: meter_node
      type (MeterNodeIterator) :: iterator
      iterator%reference => meter_node
      iterator%current => meter_node
   end function new_MeterNodeIterator
Call graph
meternodeiterator calls new_meternodeiterator
begin calls meternodeiterator
end calls meternodeiterator
accumulate calls begin, accumulate, next
next calls begin
get_exclusive calls next
get_num_nodes calls next
reset calls next