new_MAPL_GriddedIO – MAPL
new_MAPL_GriddedIO Function
24 statements
Source File
private function new_MAPL_GriddedIO(metadata, input_bundle, output_bundle, write_collection_id, read_collection_id, metadata_collection_id, regrid_method, fraction, items, rc) result(GriddedIO)
Arguments
Type Intent Optional Attributes Name
type(FileMetadata), intent(in), optional :: metadata
type(ESMF_FieldBundle), intent(in), optional :: input_bundle
type(ESMF_FieldBundle), intent(in), optional :: output_bundle
integer, intent(in), optional :: write_collection_id
integer, intent(in), optional :: read_collection_id
integer, intent(in), optional :: metadata_collection_id
integer, intent(in), optional :: regrid_method
integer, intent(in), optional :: fraction
type(GriddedIOitemVector), intent(in), optional :: items
integer, intent(out), optional :: rc
Return Value type(MAPL_GriddedIO)
Calls
Called by
Contents
Source Code
new_MAPL_GriddedIO
Source Code
     function new_MAPL_GriddedIO(metadata,input_bundle,output_bundle,write_collection_id,read_collection_id, &
             metadata_collection_id,regrid_method,fraction,items,rc) result(GriddedIO)
        type(MAPL_GriddedIO) :: GriddedIO
        type(Filemetadata), intent(in), optional :: metadata
        type(ESMF_FieldBundle), intent(in), optional :: input_bundle
        type(ESMF_FieldBundle), intent(in), optional :: output_bundle
        integer, intent(in), optional :: write_collection_id
        integer, intent(in), optional :: read_collection_id
        integer, intent(in), optional :: metadata_collection_id
        integer, intent(in), optional :: regrid_method
        integer, intent(in), optional :: fraction
        type(GriddedIOitemVector), intent(in), optional :: items
        integer, intent(out), optional :: rc
        if (present(metadata)) GriddedIO%metadata=metadata
        if (present(input_bundle)) GriddedIO%input_bundle=input_bundle
        if (present(output_bundle)) GriddedIO%output_bundle=output_bundle
        if (present(regrid_method)) GriddedIO%regrid_method=regrid_method
        if (present(write_collection_id)) GriddedIO%write_collection_id=write_collection_id
        if (present(read_collection_id)) GriddedIO%read_collection_id=read_collection_id
        if (present(metadata_collection_id)) GriddedIO%metadata_collection_id=metadata_collection_id
        if (present(items)) GriddedIO%items=items
        if (present(fraction)) GriddedIO%fraction=fraction
        _RETURN(ESMF_SUCCESS)
     end function new_MAPL_GriddedIO
Call graph
new_mapl_griddedio calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_griddedio calls new_mapl_griddedio