new_Variable – MAPL
new_Variable Function
66 statements
Source File
private function new_Variable(unusable, type, dimensions, chunksizes, const_value, deflation, quantize_algorithm, quantize_level, zstandard_level, rc) result(var)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: type
character(len=*), intent(in), optional :: dimensions
integer, intent(in), optional :: chunksizes(:)
type(UnlimitedEntity), intent(in), optional :: const_value
integer, intent(in), optional :: deflation
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(in), optional :: zstandard_level
integer, intent(out), optional :: rc
Return Value type(Variable)
Calls
Called by
Source Code
   function new_Variable(unusable, type, dimensions, chunksizes,const_value, deflation, quantize_algorithm, quantize_level, zstandard_level, rc) result(var)
      type (Variable) :: var
      integer, optional, intent(in) :: type
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: dimensions
      integer, optional, intent(in) :: chunksizes(:)
      type (UnlimitedEntity), optional, intent(in) :: const_value
      integer, optional, intent(in) :: deflation
      integer, optional, intent(in) :: quantize_algorithm
      integer, optional, intent(in) :: quantize_level
      integer, optional, intent(in) :: zstandard_level
      integer, optional, intent(out) :: rc
      integer:: empty(0)
      var%type = -1
      var%deflation = 0
      var%quantize_algorithm = 0
      var%quantize_level = 0
      var%zstandard_level = 0
      var%chunksizes = empty
      var%dimensions = StringVector()
      var%attributes = StringAttributeMap()
      var%const_value = UnlimitedEntity()
      if (present(type)) then
         var%type = type
      endif
      if (present(dimensions)) then
         call parse_dimensions()
      end if
      if (present(chunksizes)) then
         var%chunksizes = chunksizes
      end if
      if (present(const_value)) then
         var%const_value = const_value
      endif
      if (present(deflation)) then
         var%deflation = deflation
      endif
      if (present(quantize_algorithm)) then
         var%quantize_algorithm = quantize_algorithm
      endif
      if (present(quantize_level)) then
         var%quantize_level = quantize_level
      endif
      if (present(zstandard_level)) then
         var%zstandard_level = zstandard_level
      endif
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   contains
      subroutine parse_dimensions()
         character(len=:), allocatable :: dim_string
         integer :: idx
         dim_string = dimensions // pFIO_DIMENSION_SEPARATOR
         do
            idx = index(dim_string, pFIO_DIMENSION_SEPARATOR)
            if (idx == 0) exit
            if (idx == 1) exit
            call var%dimensions%push_back(dim_string(1:idx-1))
            dim_string = dim_string(idx+1:) ! do not forget to skip separator !
         end do
      end subroutine parse_dimensions
   end function new_Variable
Call graph
new_variable calls mapl_return, push_back, stringvector
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
variable calls new_variable