new_MpiMutex – MAPL
new_MpiMutex Function
47 statements
Source File
private function new_MpiMutex(comm) result(lock)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
Return Value type(MpiMutex)
Calls
Called by
Source Code
   function new_MpiMutex(comm) result(lock)
      type (MpiMutex) :: lock
      integer, intent(in) :: comm
      integer :: ierror,rc,status
      integer(kind=MPI_ADDRESS_KIND) :: sz
#if !defined (SUPPORT_FOR_MPI_ALLOC_MEM_CPTR)
      integer(kind=MPI_ADDRESS_KIND) :: baseaddr
#endif
      call MPI_Comm_dup(comm, lock%comm, ierror)
      _VERIFY(ierror)
      call MPI_Comm_rank(lock%comm, lock%rank, ierror)
      _VERIFY(ierror)
      call MPI_Comm_size(lock%comm, lock%npes, ierror)
      _VERIFY(ierror)
      ! This type is used to copy the status of locks on other PE's
      ! into a table that can be examined on the local process.
      block
        integer :: blklens(2)
        integer :: displs(2)
        blklens = [lock%rank, lock%npes - lock%rank - 1]
        displs = [0, lock%rank + 1]
        call MPI_Type_indexed(2, blklens, displs, MPI_LOGICAL, lock%pe_locks_type, ierror);
        _VERIFY(ierror)
        call MPI_Type_commit(lock%pe_locks_type, ierror)
        _VERIFY(ierror)
      end block
      ! Create windows
      if (lock%rank == 0) then
         block
           logical, pointer :: scratchpad(:)
           integer :: sizeof_logical
           call MPI_Type_extent(MPI_LOGICAL, sizeof_logical, ierror)
           _VERIFY(ierror)
           sz = lock%npes * sizeof_logical
#if defined(SUPPORT_FOR_MPI_ALLOC_MEM_CPTR)
           call MPI_Alloc_mem(sz, MPI_INFO_NULL, lock%locks_ptr, ierror)
           _VERIFY(ierror)
#else
           call MPI_Alloc_mem(sz, MPI_INFO_NULL, baseaddr, ierror)
           _VERIFY(ierror)
           lock%locks_ptr = transfer(baseaddr, lock%locks_ptr)
#endif
           call c_f_pointer(lock%locks_ptr, scratchpad, [lock%npes])
           scratchpad = .false.
           call MPI_Win_create(scratchpad, sz, sizeof_logical, &
                & MPI_INFO_NULL, lock%comm, lock%window, ierror)
           _VERIFY(ierror)
         end block
      else ! local window memory is size 0, but have to pass something
         block
           logical :: buffer(1)
           sz = 0
           call MPI_Win_create(buffer, sz, 1, MPI_INFO_NULL, lock%comm, lock%window, ierror)
           _VERIFY(ierror)
         end block
      end if
      allocate(lock%local_data(lock%npes-1))
   end function new_MpiMutex
Call graph
new_mpimutex calls blklens, buffer, displs, mpi_alloc_mem, mpi_comm_dup, mpi_comm_rank, mpi_comm_size, mpi_type_commit, mpi_type_extent, mpi_type_indexed, mpi_win_create, mapl_verify, scratchpad
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
mpimutex calls new_mpimutex