new_FastClientThread – MAPL
new_FastClientThread Function
5 statements
Source File
private function new_FastClientThread(sckt) result(c)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), optional :: sckt
Return Value type(FastClientThread), target
Calls
Called by
Source Code
   function new_FastClientThread(sckt) result(c)
      class(AbstractSocket),optional,intent(in) :: sckt
      type (FastClientThread),target :: c
      if (present(sckt)) call c%set_connection(sckt)
   end function new_FastClientThread
Call graph
new_fastclientthread calls set_connection
set_connection calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
fastclientthread calls new_fastclientthread