new_EtaHybridVerticalCoordinate_by_file – MAPL
new_EtaHybridVerticalCoordinate_by_file Function
12 statements
Source File
private function new_EtaHybridVerticalCoordinate_by_file(filename, unusable, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(inout), optional :: rc
Return Value type(EtaHybridVerticalCoordinate)
Calls
Called by
Contents
Source Code
new_EtaHybridVerticalCoordinate_by_file
Source Code
   function new_EtaHybridVerticalCoordinate_by_file(filename, unusable, rc) result(grid)
      type (EtaHybridVerticalCoordinate) :: grid
      character(len=*), intent(in) :: filename
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(inout) :: rc
      type (ESMF_Config) :: config
      integer :: status
      _UNUSED_DUMMY(unusable)
      call ESMF_ConfigLoadFile (config, filename, _RC)
      grid = EtaHybridVerticalCoordinate(config)
   end function new_EtaHybridVerticalCoordinate_by_file
Call graph
new_etahybridverticalcoordinate_by_file calls ESMF_ConfigLoadFile, etahybridverticalcoordinate, mapl_verify
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_file, new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_cfg
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
new_etahybridverticalcoordinate_by_ak_bk calls mapl_assert
new_etahybridverticalcoordinate_by_cfg calls etahybridverticalcoordinate, mapl_verify, ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigNextLine
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_eta_onestep_r4 calls etahybridverticalcoordinate, get_eta
get_eta_onestep_r8 calls etahybridverticalcoordinate, get_eta
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8
get_eta_r4 calls get_eta