new_CapOptions_from_flap_back_comp – MAPL
new_CapOptions_from_flap_back_comp Function
22 statements
Source File
private function new_CapOptions_from_flap_back_comp(unusable, description, authors, extra, rc) result(flapcap)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: description
character(len=*), intent(in) :: authors
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_FlapCLI)
Calls
Called by
Contents
Source Code
new_CapOptions_from_flap_back_comp
Source Code
   function new_CapOptions_from_flap_back_comp(unusable, description, authors, extra, rc) result (flapcap)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type (MAPL_FlapCLI) :: flapcap
      character(*), intent(in) :: description
      character(*), intent(in) :: authors
      procedure(I_extraoptions), optional :: extra
      integer, optional, intent(out) :: rc
      integer :: status
      call flapcap%cli_options%init( &
        description = trim(description), &
        authors     = trim(authors))
      call flapcap%add_command_line_options(flapcap%cli_options, rc=status)
      _VERIFY(status)
      if (present(extra)) then
         call extra(flapcap%cli_options, _RC)
      end if
      call flapcap%cli_options%parse(error=status); _VERIFY(status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function new_CapOptions_from_flap_back_comp
Call graph
new_capoptions_from_flap_back_comp calls add_command_line_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, mapl_verify, add
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_flapcli calls new_capoptions_from_flap_back_comp