new_LocstreamRegridder – MAPL
new_LocstreamRegridder Function
41 statements
Source File
private function new_LocstreamRegridder(grid, locstream, unusable, regrid_method, rc) result(regridder)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Grid), intent(inout) :: grid
type(ESMF_LocStream), intent(inout) :: locstream
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_RegridMethod_Flag), intent(in), optional :: regrid_method
integer, intent(out), optional :: rc
Return Value type(LocstreamRegridder)
Calls
Called by
Source Code
   function new_LocstreamRegridder(grid,locstream,unusable,regrid_method,rc) result(regridder)
      type(LocstreamRegridder) :: regridder
      type(ESMF_Grid), intent(inout) :: grid
      type(ESMF_Locstream), intent(inout) :: locstream
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_RegridMethod_Flag), optional, intent(in) :: regrid_method
      integer, optional, intent(out) :: rc
      type(ESMF_RegridMethod_Flag) :: local_regrid_method
      type(ESMF_Field) :: src_field, dst_field
      real, pointer :: pt2d(:,:), pt1d(:)
      integer :: status
      _UNUSED_DUMMY(unusable)
      if (present(regrid_method)) then
         local_regrid_method = regrid_method
      else
         local_regrid_method = ESMF_REGRIDMETHOD_NEAREST_STOD
      end if
      src_field = ESMF_FieldCreate(grid,typekind=ESMF_TYPEKIND_R4,gridToFieldMap=[1,2],rc=status)
      _VERIFY(status)
      dst_field = ESMF_FieldCreate(locstream,typekind=ESMF_TYPEKIND_R4,gridToFieldMap=[1],rc=status)
      _VERIFY(status)
      call ESMF_FieldGet(src_field, localDE=0, farrayPtr=pt2d, _RC)
      call ESMF_FieldGet(dst_field, localDE=0, farrayPtr=pt1d, _RC)
      pt2d = 0.0
      pt1d = 0.0
      call ESMF_FieldRegridStore(srcField=src_field,dstField=dst_field, &
           routeHandle=regridder%route_handle,regridmethod=local_regrid_method,rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(src_field,noGarbage=.true.,rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(dst_field,noGarbage=.true.,rc=status)
      _VERIFY(status)
      regridder%grid=grid
      regridder%locstream=locstream
      _RETURN(_SUCCESS)
   end function new_LocstreamRegridder
Call graph
new_locstreamregridder calls ESMF_FieldRegridStore, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
locstreamregridder calls new_locstreamregridder