new_CoordinateVariable – MAPL
new_CoordinateVariable Function
10 statements
Source File
private function new_CoordinateVariable(var, coordinate_data, rc) result(coordinate_variable)
Arguments
Type Intent Optional Attributes Name
type(Variable), intent(in) :: var
class(*), intent(in) :: coordinate_data(:)
integer, intent(out), optional :: rc
Return Value type(CoordinateVariable)
Calls
Called by
Contents
Source Code
new_CoordinateVariable
Source Code
   function new_CoordinateVariable(var, coordinate_data, rc) result(coordinate_variable)
      type (CoordinateVariable) :: coordinate_variable
      type (Variable), intent(in) :: var
      class(*), intent(in) :: coordinate_data(:)
      integer, optional, intent(out) :: rc
      coordinate_variable%Variable = var
      call coordinate_variable%set_coordinate_data(coordinate_data)
      _RETURN(_SUCCESS)
   end function new_CoordinateVariable
Call graph
new_coordinatevariable calls mapl_return, set_coordinate_data
mapl_return calls get_error_message, mapl_throw_exception
set_coordinate_data calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
coordinatevariable calls new_coordinatevariable