new_ModifyMetadataMessage – MAPL
new_ModifyMetadataMessage Function
15 statements
Source File
private function new_ModifyMetadataMessage(collection_id, unusable, var_map, rc) result(message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: collection_id
class(KeywordEnforcer), intent(in), optional :: unusable
type(StringVariableMap), intent(in), optional :: var_map
integer, intent(out), optional :: rc
Return Value type(ModifyMetadataMessage)
Calls
Called by
Source Code
   function new_ModifyMetadataMessage(collection_id, unusable, var_map, rc) result (message)
      type (ModifyMetadataMessage) :: message
      integer, intent(in) :: collection_id
      class (KeywordEnforcer), optional,  intent(in) :: unusable
      type (StringVariableMap), optional, intent(in) :: var_map
      integer, optional, intent(out) :: rc
      message%collection_id = collection_id
      if (present(var_map)) message%var_map = var_map
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function new_ModifyMetadataMessage
Call graph
new_modifymetadatamessage calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
modifymetadatamessage calls new_modifymetadatamessage