new_PrefetchDataMessage – MAPL
new_PrefetchDataMessage Function
11 statements
Source File
private function new_PrefetchDataMessage(request_id, collection_id, file_name, var_name, data_reference, unusable, start) result(message)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: request_id
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
Return Value type(PrefetchDataMessage)
Calls
Called by
Source Code
   function new_PrefetchDataMessage( &
        & request_id, collection_id, file_name, var_name, &
        & data_reference, unusable, start) result(message)
      type (PrefetchDataMessage) :: message
      integer, intent(in) :: request_id
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: start(:)
      call message%init( &
        & request_id, collection_id, file_name, var_name, &
        & data_reference, unusable=unusable, start=start)
   end function new_PrefetchDataMessage
Call graph
new_prefetchdatamessage calls init
init calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
prefetchdatamessage calls new_prefetchdatamessage