new_LocalMemReference_1d – MAPL
new_LocalMemReference_1d Function
52 statements
Source File
private function new_LocalMemReference_1d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:)
integer, intent(out), optional :: rc
Return Value type(LocalMemReference)
Calls
Called by
Contents
Source Code
new_LocalMemReference_1d
Source Code
   function new_LocalMemReference_1d(array, rc) result(reference)
      type (LocalMemReference) :: reference
      class(*), target, intent(in) :: array(:)
      integer, optional, intent(out) :: rc
      integer (kind=INT32), pointer :: int32Ptr(:)
      integer (kind=INT64), pointer :: int64Ptr(:)
      real (kind=REAL32)  , pointer :: real32Ptr(:)
      real (kind=REAL64)  , pointer :: real64Ptr(:)
      integer :: status
      select type (array)
      type is (integer(kind=INT32))
         reference = LocalMemReference( pFIO_INT32, shape(array), rc=status)
         _VERIFY(status)
         if (.not. c_associated(reference%base_address)) then
            _RETURN(_SUCCESS)
         endif
         call c_f_pointer(reference%base_address, int32Ptr, shape=shape(array))
         int32Ptr = array
      type is (integer(kind=INT64))
         reference = LocalMemReference( pFIO_INT64, shape(array), rc=status)
         _VERIFY(status)
         if (.not. c_associated(reference%base_address)) then
            _RETURN(_SUCCESS)
         endif
         call c_f_pointer(reference%base_address, int64Ptr, shape=shape(array))
         int64Ptr = array
      type is (real(kind=REAL32))
         reference = LocalMemReference( pFIO_REAL32, shape(array), rc=status)
         _VERIFY(status)
         if (.not. c_associated(reference%base_address)) then
            _RETURN(_SUCCESS)
         endif
         call c_f_pointer(reference%base_address, real32Ptr, shape=shape(array))
         real32Ptr = array
      type is (real(kind=REAL64))
         reference = LocalMemReference( pFIO_REAL64, shape(array), rc=status)
         _VERIFY(status)
         if (.not. c_associated(reference%base_address)) then
            _RETURN(_SUCCESS)
         endif
         call c_f_pointer(reference%base_address, real64Ptr, shape=shape(array))
         real64Ptr = array
      class default
         _FAIL( "LocalMemRef does not support this type")
      end select
      _RETURN(_SUCCESS)
   end function new_LocalMemReference_1d
Call graph
new_localmemreference_1d calls localmemreference, mapl_assert, mapl_return, mapl_verify
localmemreference calls new_localmemreference_1d, new_localmemreference, new_localmemreference_0d, new_localmemreference_2d, new_localmemreference_3d, new_localmemreference_4d, new_localmemreference_5d
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_localmemreference calls mapl_return, mapl_verify
new_localmemreference_0d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_2d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_3d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_4d calls localmemreference, mapl_assert, mapl_return, mapl_verify
new_localmemreference_5d calls localmemreference, mapl_assert, mapl_return, mapl_verify