new_FileMetadata – MAPL
new_FileMetadata Function
17 statements
Source File
private function new_FileMetadata(unusable, dimensions, global, variables, order) result(fmd)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
type(StringIntegerMap), intent(in), optional :: dimensions
type(Variable), intent(in), optional :: global
type(StringVariableMap), intent(in), optional :: variables
type(StringVector), intent(in), optional :: order
Return Value type(FileMetadata)
Calls
Called by
Contents
Call graph
new_filemetadata calls stringintegermap, stringvector
filemetadata calls new_filemetadata
filemetadata_deserialize calls filemetadata
deserialize calls filemetadata_deserialize
historycollectionvector_deserialize calls filemetadata_deserialize
test_serialize calls filemetadata_deserialize
create_remote_win calls historycollectionvector_deserialize