new_time_data – MAPL
new_time_data Function
27 statements
Source File
private function new_time_data(clock, ntime, frequency, offset, funits, integer_time, rc) result(tData)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(inout) :: clock
integer, intent(in) :: ntime
integer, intent(in) :: frequency
type(ESMF_TimeInterval) :: offset
character(len=*), intent(in), optional :: funits
logical, intent(in), optional :: integer_time
integer, intent(out), optional :: rc
Return Value type(timeData)
Calls
Called by
Contents
Source Code
new_time_data
Source Code
  function new_time_data(clock,ntime,frequency,offset,funits,integer_time,rc) result(tData)
    type(timeData) :: tData
    type(ESMF_Clock),intent(inout) :: clock
    integer, intent(in) :: ntime
    integer, intent(in) :: frequency
    type(ESMF_TimeInterval) :: offset
    character(len=*), optional, intent(in) :: funits
    logical, optional, intent(in) :: integer_time
    integer, optional, intent(Out) :: rc
    tData%is_initialized = .true.
    tdata%clock=clock
    tdata%ntime=ntime
    tdata%frequency=frequency
    tdata%offset=offset
    if(present(funits)) then
       tdata%funits=funits
    else
       tdata%funits="minutes"
    end if
    if(present(integer_time)) then
      tdata%integer_time = integer_time
    else
      tdata%integer_time = .false.
    end if
    _RETURN(ESMF_SUCCESS)
  end function new_time_data
Call graph
new_time_data calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
timedata calls new_time_data