new_UngriddedDimSpec_extent – MAPL
new_UngriddedDimSpec_extent Function
5 statements
Source File
private pure function new_UngriddedDimSpec_extent(extent) result(spec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: extent
Return Value type(UngriddedDimSpec)
Calls
Called by
Contents
Source Code
new_UngriddedDimSpec_extent
Source Code
   pure function new_UngriddedDimSpec_extent(extent) result(spec)
      integer, intent(in) :: extent
      type(UngriddedDimSpec) :: spec
      spec = UngriddedDimSpec(UNKNOWN_DIM_NAME, UNKNOWN_DIM_UNITS, default_coords(extent))
   end function new_UngriddedDimSpec_extent
Call graph
new_ungriddeddimspec_extent calls ungriddeddimspec, default_coords
ungriddeddimspec calls new_ungriddeddimspec_extent, new_ungriddeddimspec_name_and_coords, new_ungriddeddimspec_name_units_and_coords
new_ungriddeddimspec_name_and_coords calls ungriddeddimspec