new_CFIOCollection – MAPL
new_CFIOCollection Function
5 statements
Source File
public function new_CFIOCollection(template) result(collection)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: template
Return Value type(CFIOCollection)
Called by
Contents
Source Code
new_CFIOCollection
Source Code
  function new_CFIOCollection(template) result(collection)
    type (CFIOCollection) :: collection
    character(len=*), intent(in) :: template
    collection%template = template
  end function new_CFIOCollection
Call graph
cfiocollection calls new_cfiocollection
mapl_cfioaddcollection calls new_cfiocollection
mapl_cfioreadparallel_ calls mapl_cfioaddcollection
mapl_cfioreadparallel calls mapl_cfioreadparallel_