new_CommGroupDescription – MAPL
new_CommGroupDescription Function
27 statements
Source File
private function new_CommGroupDescription(npes, nnodes, isolate_nodes, name, unusable, npes_per_node, rc) result(CommGroup)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npes
integer, intent(in) :: nnodes
logical, intent(in) :: isolate_nodes
character(len=*), intent(in) :: name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: npes_per_node
integer, intent(out), optional :: rc
Return Value type(CommGroupDescription)
Calls
Called by
Contents
Source Code
new_CommGroupDescription
Source Code
   function new_CommGroupDescription( npes, nnodes, isolate_nodes, name, unusable, npes_per_node, rc) result(CommGroup)
      type(CommGroupDescription) :: CommGroup
      integer, intent(in) :: npes
      integer, intent(in) :: nnodes
      logical, intent(in) :: isolate_nodes
      character(*), intent(in) :: name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in)  :: npes_per_node
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      _ASSERT(npes*nnodes == 0, "npes and nnodes are exclusive")
      if (nnodes > 0) then
         _ASSERT( isolate_nodes, " nnodes should be isolated")
      endif
      CommGroup%npes   = npes
      CommGroup%nnodes = nnodes
      CommGroup%isolate_nodes = isolate_nodes
      CommGroup%name = name
      CommGroup%npes_per_node = 0
      if ( present(npes_per_node)) then
         CommGroup%npes_per_node = npes_per_node
         CommGroup%npes   = 0
         CommGroup%nnodes = 0
      endif
      _RETURN(_SUCCESS)
   end function new_CommGroupDescription
Call graph
new_commgroupdescription calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
commgroupdescription calls new_commgroupdescription