new_samplerHQ – MAPL
new_samplerHQ Function
40 statements
Source File
private function new_samplerHQ(clock, config, key, rc) result(hq)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(in) :: clock
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: key
integer, intent(out), optional :: rc
Return Value type(samplerHQ)
Calls
Called by
Source Code
  function new_samplerHQ(clock, config, key, rc) result(hq)
    implicit none
    type(samplerHQ) :: hq
    type(ESMF_Clock),  intent(in) :: clock
    type(ESMF_Config), intent(inout) :: config
    character(len=*), intent(in) :: key
    integer, optional, intent(out) :: rc
    character(len=ESMF_MAXSTR) :: time_string
    integer :: status
    integer :: time_integer
    type(ESMF_Time)            :: RingTime_epoch
    type(ESMF_Time)            :: startTime
    type(ESMF_Time)         :: currTime
    type(ESMF_TimeInterval) :: timeStep
    type(ESMF_TimeInterval)  :: Frequency_epoch
    integer :: sec, second
    integer :: n1
    type(ESMF_Config) :: cf
    hq%clock= clock
    hq%config_grid_save= config
    hq%arr(1:2) = -2.d0
    call ESMF_ClockGet ( clock, CurrTime=currTime, _RC )
    call ESMF_ClockGet ( clock, timestep=timestep, _RC )
    call ESMF_ClockGet ( clock, startTime=startTime, _RC )
    call ESMF_ConfigGetAttribute(config, value=time_integer, label=trim(key)//'.Epoch:', default=0, _RC)
    _ASSERT(time_integer /= 0, 'Epoch value in config wrong')
    second = hms_2_s (time_integer)
    call ESMF_TimeIntervalSet(frequency_epoch, s=second, _RC)
    hq%frequency_epoch = frequency_epoch
    hq%RingTime  = currTime
    hq%alarm = ESMF_AlarmCreate( clock=clock, RingInterval=Frequency_epoch, &
         RingTime=hq%RingTime, sticky=.false., _RC )
    _RETURN(_SUCCESS)
  end function new_samplerHQ
Call graph
new_samplerhq calls ESMF_AlarmCreate, ESMF_ClockGet, ESMF_ConfigGetAttribute, ESMF_TimeIntervalSet, hms_2_s, mapl_assert, mapl_return, mapl_verify
hms_2_s calls hms_2_s
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
samplerhq calls new_samplerhq