new_DirectoryService – MAPL
new_DirectoryService Function
28 statements
Source File
private function new_DirectoryService(comm, unusable, rc) result(ds)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(DirectoryService)
Calls
Called by
Source Code
   function new_DirectoryService(comm, unusable, rc) result(ds)
      type (DirectoryService) :: ds
      integer, intent(in) :: comm
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: ierror
      type (Directory) :: empty_dir
      call MPI_Comm_dup(comm, ds%comm, ierror)
      _VERIFY(ierror)
      call MPI_Comm_rank(ds%comm, ds%rank, ierror)
      _VERIFY(ierror)
      ! Create windows that will be used for coordination
      ! 1. lock - control modification of other windows
      ds%mutex = MpiMutex(ds%comm)
      ds%win_server_directory = make_directory_window(ds%comm, ds%server_dir)
      ds%win_client_directory = make_directory_window(ds%comm, ds%client_dir)
      if(ds%rank == 0) then
         call ds%put_directory(empty_dir, ds%win_client_directory)
         call ds%put_directory(empty_dir, ds%win_server_directory)
      end if
      ds%parser = ProtocolParser()
      ! Need to be sure that the directories have been initialized before
      ! proceeding
      call MPI_Barrier(comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function new_DirectoryService
Call graph
new_directoryservice calls mpi_barrier, mpi_comm_dup, mpi_comm_rank, make_directory_window, mapl_return, mapl_verify, put_directory
make_directory_window calls mpi_comm_rank, mapl_verify, mpi_alloc_mem, mpi_win_create, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_directory calls mapl_verify, mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
get_error_message calls at, insert
mapl_throw_exception calls initialize
directoryservice calls new_directoryservice