new_UnlimitedEntity_0d – MAPL
new_UnlimitedEntity_0d Function
17 statements
Source File
private function new_UnlimitedEntity_0d(value, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: value
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
Calls
Called by
Contents
Source Code
new_UnlimitedEntity_0d
Source Code
   function new_UnlimitedEntity_0d(value, rc) result(attr)
      type (UnlimitedEntity) :: attr
      class (*), intent(in) :: value
      integer, optional, intent(out) :: rc
      type(StringWrap) :: w
      attr%shape = EMPTY
      select type (value)
      type is (character(len=*)) ! workaround for gfortran-6.2 and ifort-17.0.1
        w = StringWrap('')
        w%value = value
        allocate(attr%value,source=w)
      class default
        allocate(attr%value, source=value)
      end select
      _RETURN(_SUCCESS)
   end function new_UnlimitedEntity_0d
Call graph
new_unlimitedentity_0d calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
unlimitedentity calls new_unlimitedentity_0d, new_unlimitedentity_2d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_5d
new_unlimitedentity_2d calls unlimitedentity
new_unlimitedentity_3d calls unlimitedentity
new_unlimitedentity_4d calls unlimitedentity
new_unlimitedentity_5d calls unlimitedentity
unlimitedentity_deserialize calls unlimitedentity
attribute_deserialize calls unlimitedentity_deserialize
stringunlimitedentitymap_deserialize calls unlimitedentity_deserialize
test_serialize calls unlimitedentity_deserialize, attribute_deserialize
stringattributemap_deserialize calls attribute_deserialize