new_UnlimitedEntity_1d – MAPL
new_UnlimitedEntity_1d Function
14 statements
Source File
private function new_UnlimitedEntity_1d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
Calls
Called by
Contents
Source Code
new_UnlimitedEntity_1d
Source Code
   function new_UnlimitedEntity_1d(values, rc) result(attr)
      type (UnlimitedEntity) :: attr
      class (*), intent(in) :: values(:)
      integer, optional, intent(out) :: rc
      select type (values)
      type is (character(len=*))
        _FAIL( 'unsupported unless shape is [1]')
      class default
         allocate(attr%values, source=values)
         attr%shape = shape(values)
      end select
      _RETURN(_SUCCESS)
   end function new_UnlimitedEntity_1d
Call graph
new_unlimitedentity_1d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
unlimitedentity calls new_unlimitedentity_1d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_5d, new_unlimitedentity_2d
new_unlimitedentity_3d calls unlimitedentity
unlimitedentity_deserialize calls unlimitedentity
new_unlimitedentity_4d calls unlimitedentity
new_unlimitedentity_5d calls unlimitedentity
new_unlimitedentity_2d calls unlimitedentity
stringunlimitedentitymap_deserialize calls unlimitedentity_deserialize
attribute_deserialize calls unlimitedentity_deserialize
test_serialize calls unlimitedentity_deserialize, attribute_deserialize
stringattributemap_deserialize calls attribute_deserialize