new_MpiServer – MAPL
new_MpiServer Function
15 statements
Source File
private function new_MpiServer(comm, port_name, profiler_name, with_profiler, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
character(len=*), intent(in) :: port_name
character(len=*), intent(in), optional :: profiler_name
logical, intent(in), optional :: with_profiler
integer, intent(out), optional :: rc
Return Value type(MpiServer)
Calls
Called by
Source Code
   function new_MpiServer(comm, port_name, profiler_name, with_profiler, rc) result(s)
      type (MpiServer) :: s
      integer, intent(in) :: comm
      character(*), intent(in) :: port_name
      character(*), optional, intent(in) :: profiler_name
      logical, optional, intent(in) :: with_profiler
      integer, optional, intent(out) :: rc
      integer :: status
      call s%init(comm, port_name, profiler_name=profiler_name, with_profiler = with_profiler, _RC)
      s%port_name = trim(port_name)
      s%threads = ServerThreadVector()
      _RETURN(_SUCCESS)
   end function new_MpiServer
Call graph
new_mpiserver calls init, mapl_return, mapl_verify
init calls mapl_return, mapl_verify, mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
mpiserver calls new_mpiserver