new_StationSampler_readfile – MAPL
new_StationSampler_readfile Function
205 statements
Source File
private function new_StationSampler_readfile(bundle, filename, nskip_line, GENSTATE, rc) result(sampler)
Uses
pflogger
write(6,) ‘i=’, i write(6,) ‘line=’, trim(line)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(in) :: bundle
character(len=*), intent(in) :: filename
integer, intent(in), optional :: nskip_line
type(MAPL_MetaComp), intent(in), optional, pointer :: GENSTATE
integer, intent(out), optional :: rc
Return Value type(StationSampler)
Calls
Called by
Source Code
  function new_StationSampler_readfile (bundle, filename, nskip_line, GENSTATE, rc) result(sampler)
    use pflogger, only             :  Logger, logging
    implicit none
    type(StationSampler)           :: sampler
    type(ESMF_FieldBundle), intent(in) :: bundle
    character(len=*), intent(in)   :: filename
    integer, optional, intent(in)  :: nskip_line
    type(MAPL_MetaComp), pointer, intent(in), optional  :: GENSTATE
    integer, optional, intent(out) :: rc
    type(ESMF_VM) :: vm
    integer :: mypet, petcount, mpic
    type(ESMF_grid) :: grid
    integer, allocatable :: sendcount(:), displs(:)
    integer :: recvcount
    integer :: is, ie, ierr
    integer :: M, N, ip
    integer :: arr(1)
    integer :: nx, nx2, nx_sum
    real(REAL64), allocatable :: lons_chunk(:)
    real(REAL64), allocatable :: lats_chunk(:)
    integer :: unit, ios, nstation, status
    integer :: i, j, k, ncount
    logical :: con1, con2
    character (len=1)     :: CH1
    character (len=5)     :: seq
    character (len=100)   :: line, line2
    integer               :: nskip
    type(Logger), pointer :: lgr
    !__ 1. read from station_id_file: static
    !      plain text format:
    !      ["name,lat,lon,elev"] or ["id,name,lat,lon,elev"]
    !      ["name_short lat lon elev name_full"]
    !
    lgr => logging%get_logger('HISTORY.sampler')
    if ( MAPL_AM_I_ROOT() ) then
       open(newunit=unit, file=trim(filename), form='formatted', &
            access='sequential', status='old', _IOSTAT)
       ios=0
       nstation=0
       nskip=0
       if (present(nskip_line)) then
          nskip=nskip_line
       end if
       if (nskip>0) then
          do i=1, nskip
             read(unit, *)
          end do
       end if
       read(unit, '(a100)', IOSTAT=ios) line
       call count_substring(line, ',', ncount, _RC)
       con1= (ncount>=2 .AND. ncount<=4).OR.(ncount==0)
       _ASSERT(con1, 'string sequence in Aeronet file not supported')
       if (ncount==0) then
          seq='AFFFA'
       elseif (ncount==2) then
          seq='AFF'
       elseif (ncount==3) then
          seq='AFFF'
       elseif (ncount==4) then
          CH1=line(1:1)
          con1= (CH1>='a'.AND.CH1<='z').OR.(CH1>='A'.AND.CH1<='Z')
          con2= CH1>='0'.AND.CH1<='9'
          if (con1) then
             seq='AIFFF'
          else
             if (con2) then
                seq='IAFFF'
             else
                _ASSERT(.false., 'string sequence in Aeronet file not supported')
             end if
          end if
       end if
       rewind(unit)
       if (nskip>0) then
          do i=1, nskip
             read(unit, *)
          end do
       end if
       ios=0
       do while (ios==0)
          read(unit, '(a100)', IOSTAT=ios) line
          if (ios==0) nstation=nstation+1
       end do
       sampler%nstation=nstation
       allocate(sampler%station_id(nstation), _STAT)
       allocate(sampler%station_name(nstation), _STAT)
       allocate(sampler%station_fullname(nstation), _STAT)
       allocate(sampler%lons(nstation), _STAT)
       allocate(sampler%lats(nstation), _STAT)
       allocate(sampler%elevs(nstation), _STAT)
       rewind(unit)
       if (nskip>0) then
          do i=1, nskip
             read(unit, *)
          end do
       end if
       do i=1, nstation
          if(seq=='IAFFF') then
             read(unit, *) &
                  sampler%station_id(i), &
                  sampler%station_name(i), &
                  sampler%lons(i), &
                  sampler%lats(i)
          elseif(seq=='AIFFF') then
             read(unit, *) &
                  sampler%station_name(i), &
                  sampler%station_id(i), &
                  sampler%lons(i), &
                  sampler%lats(i)
          elseif(trim(seq)=='AFF' .OR. trim(seq)=='AFFF') then
             !!write(6,*) 'i=', i
             line=''
             read(unit, '(a100)')  line
             !!write(6,*) 'line=', trim(line)
             call CSV_read_line_with_CH_I_R(line, &
                  sampler%station_name(i), &
                  sampler%lons(i), &
                  sampler%lats(i), _RC)
             sampler%station_id(i)=i
          elseif(trim(seq)=='AFFFA') then
          ! NOAA GHCNd
          ! Ex: 'CHM00054511  39.9330  116.2830   55.0    BEIJING   GSN     54511'
             read(unit, *) &
                  sampler%station_name(i), &
                  sampler%lats(i), &
                  sampler%lons(i)
             sampler%station_id(i)=i
             backspace(unit)
             read(unit, '(a100)', IOSTAT=ios) line
             j=index(line, '.', BACK=.true.)
             line2=line(j+1:)
             k=len(line2)
             line=''
             do j=1, k
                CH1=line2(j:j)
                con1= (CH1>='a'.AND.CH1<='z').OR.(CH1>='A'.AND.CH1<='Z')
                if (con1) exit
             enddo
             read(line2(j:k), '(a100)') line
             line2=trim(line)
             k=len(line2)
             line=''
             do j=1, k
                CH1=line2(j:j)
                con1= (CH1>='0' .AND. CH1<='9')
                if (con1) exit
             enddo
             if (j>k) j=k
             sampler%station_fullname(i) = trim(line2(1:j-1))
          end if
       end do
       close(unit)
       write(6,*)  'nstation=', nstation
       write(6,*)  'sampler%station_name(1:2) : ', &
            trim(sampler%station_name(1)), trim(sampler%station_name(2))
       write(6,*)  'sampler%lons(1:2) : ',&
            sampler%lons(1:2)
       write(6,*)  'sampler%lats(1:2) : ',&
            sampler%lats(1:2)
    else
       nstation=0
       sampler%nstation = 0
       allocate(sampler%station_id(nstation), _STAT)
       allocate(sampler%station_name(nstation), _STAT)
       allocate(sampler%station_fullname(nstation), _STAT)
       allocate(sampler%lons(nstation), _STAT)
       allocate(sampler%lats(nstation), _STAT)
       allocate(sampler%elevs(nstation), _STAT)
    end if
    sampler%index_name_x = 'station_index'
    if (present(GENSTATE)) sampler%GENSTATE => GENSTATE
    !__ 2. create LocStreamFactory, then LS_rt including route_handle
    !
    !      grid_A:  LS_rt    : on root
    !      grid_B:  LS_chunk : uniform on cores
    !      grid_C:  LS_ds    : bg=CS
    !
    call ESMF_VMGetCurrent(vm,_RC)
    call ESMF_VMGet(vm, mpiCommunicator=mpic, petCount=petCount, localPet=mypet, _RC)
    call MAPL_CommsBcast(vm, DATA=sampler%nstation, N=1, ROOT=MAPL_Root, _RC)
    nx_sum = sampler%nstation
    ip = mypet    ! 0 to M-1
    N = nx_sum
    M = petCount
    recvcount = int(ip+1, INT64) * int(N, INT64) / int(M, INT64) - &
         int(ip  , INT64) * int(N, INT64) / int(M, INT64)
    call lgr%debug('%a %i12 %i12', 'ip, recvcount', ip, recvcount)
    allocate ( sendcount (petCount) )
    allocate ( displs    (petCount) )
    do ip=0, M-1
       sendcount(ip+1) = int(ip+1, INT64) * int(N, INT64) / int(M, INT64) - &
            int(ip  , INT64) * int(N, INT64) / int(M, INT64)
    end do
    displs(1)=0
    do i = 2, petCount
       displs(i) = displs(i-1) + sendcount(i-1)
    end do
    allocate ( lons_chunk (recvcount) )
    allocate ( lats_chunk (recvcount) )
    arr(1) = recvcount
    call ESMF_VMAllFullReduce(vm, sendData=arr, recvData=nx2, &
         count=1, reduceflag=ESMF_REDUCE_SUM, rc=rc)
    _ASSERT( nx2 == nx_sum, 'Erorr in recvcount' )
    call MPI_Scatterv( sampler%lons, sendcount, &
         displs, MPI_REAL8,  lons_chunk, &
         recvcount, MPI_REAL8, 0, mpic, ierr)
    call MPI_Scatterv( sampler%lats, sendcount, &
         displs, MPI_REAL8,  lats_chunk, &
         recvcount, MPI_REAL8, 0, mpic, ierr)
    ! -- root
    sampler%LSF   = LocStreamFactory(sampler%lons, sampler%lats, _RC)
    sampler%LS_rt = sampler%LSF%create_locstream(_RC)
    ! -- chunk
    sampler%LSF = LocStreamFactory(lons_chunk,lats_chunk,_RC)
    sampler%LS_chunk = sampler%LSF%create_locstream_on_proc(_RC)
    ! -- distributed
    call ESMF_FieldBundleGet(bundle,grid=grid,_RC)
    sampler%LS_ds = sampler%LSF%create_locstream_on_proc(grid=grid,_RC)
    ! init ofile
    sampler%ofile=''
    sampler%obs_written=0
    sampler%level_by_level = .false.
    _RETURN(_SUCCESS)
  end function new_StationSampler_readfile
Call graph
new_stationsampler_readfile calls ESMF_VMAllFullReduce, ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_scatterv, get_logger, count_substring, create_locstream, create_locstream_on_proc, csv_read_line_with_ch_i_r, debug, mapl_return, mapl_verify
stationsampler calls new_stationsampler_readfile