new_ExtDataRule – MAPL
new_ExtDataRule Function
81 statements
Source File
private function new_ExtDataRule(config, sample_map, key, unusable, multi_rule, rc) result(rule)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: config
type(ExtDataTimeSampleMap) :: sample_map
character(len=*), intent(in) :: key
class(KeywordEnforcer), intent(in), optional :: unusable
logical, intent(in), optional :: multi_rule
integer, intent(out), optional :: rc
Return Value type(ExtDataRule)
Calls
Called by
Source Code
   function new_ExtDataRule(config,sample_map,key,unusable,multi_rule,rc) result(rule)
      type(ESMF_HConfig), intent(in) :: config
      character(len=*), intent(in) :: key
      type(ExtDataTimeSampleMap) :: sample_map
      class(KeywordEnforcer), optional, intent(in) :: unusable
      logical, optional, intent(in) :: multi_rule
      integer, optional, intent(out) :: rc
      type(ExtDataRule) :: rule
      logical :: collection_present, variable_present
      integer :: status
      type(ESMF_HConfig) ::config1
      character(len=:), allocatable :: tempc
      type(ExtDataTimeSample) :: ts
      logical :: usable_multi_rule
      _UNUSED_DUMMY(unusable)
      if (present(multi_rule)) then
         usable_multi_rule = multi_rule
      else
         usable_multi_rule = .false.
      end if
      if (allocated(tempc)) deallocate(tempc)
      collection_present = ESMF_HConfigIsDefined(config,keyString="collection")
      _ASSERT(collection_present,"no collection present in ExtData export")
      rule%collection = ESMF_HConfigAsString(config,keyString="collection",_RC)
      if (allocated(tempc)) deallocate(tempc)
      variable_present = ESMF_HConfigIsDefined(config,keyString="variable")
      if (index(rule%collection,"/dev/null")==0) then
         _ASSERT(variable_present,"no variable present in ExtData export")
      end if
      if (variable_present) then
         tempc = ESMF_HConfigAsString(config,keyString="variable",_RC)
         rule%file_var=tempc
      else
         rule%file_var='null'
      end if
      if (ESMF_HConfigIsDefined(config,keyString="sample")) then
         config1 = ESMF_HConfigCreateAt(config,keyString="sample",_RC)
         if (ESMF_HConfigIsMap(config1)) then
            ts = ExtDataTimeSample(config1,_RC)
            call sample_map%insert(trim(key)//"_sample",ts)
            rule%sample_key=trim(key)//"_sample"
         else
            rule%sample_key=ESMF_HConfigAsString(config1,_RC)
         end if
      else
         rule%sample_key = ""
      end if
      if (allocated(rule%linear_trans)) deallocate(rule%linear_trans)
      if (ESMF_HConfigIsDefined(config,keyString="linear_transformation")) then
         allocate(rule%linear_trans(2))
         rule%linear_trans = ESMF_HConfigAsR4Seq(config,keyString="linear_transformation",_RC)
      else
         allocate(rule%linear_trans,source=[0.0,0.0])
      end if
      if (allocated(tempc)) deallocate(tempc)
      if (ESMF_HConfigIsDefined(config,keyString="regrid")) then
         tempc = ESMF_HConfigAsString(config,keyString="regrid",_RC)
         rule%regrid_method=tempc
      else
         rule%regrid_method="BILINEAR"
      end if
      if (ESMF_HConfigIsDefined(config,keyString="starting")) then
         tempc = ESMF_HConfigAsString(config,keyString="starting",_RC)
         rule%start_time = tempc
      end if
      if (ESMF_HConfigIsDefined(config,keyString="fail_on_missing_file")) then
         rule%fail_on_missing_file = ESMF_HConfigAsLogical(config,keyString="fail_on_missing_file",_RC)
      end if
      rule%multi_rule=usable_multi_rule
      _RETURN(_SUCCESS)
   end function new_ExtDataRule
Call graph
new_extdatarule calls esmf_hconfigaslogical, esmf_hconfigasr4seq, esmf_hconfigasstring, esmf_hconfigcreateat, esmf_hconfigisdefined, esmf_hconfigismap, mapl_assert, insert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
extdatarule calls new_extdatarule