new_ExtDataOldTypesCreator – MAPL
new_ExtDataOldTypesCreator Subroutine
13 statements
Source File
public subroutine new_ExtDataOldTypesCreator(ExtDataObj, config_file, current_time, unusable, rc)
Arguments
Type Intent Optional Attributes Name
type(ExtDataOldTypesCreator), intent(out), target :: ExtDataObj
character(len=*), intent(in) :: config_file
type(ESMF_Time), intent(in) :: current_time
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine new_ExtDataOldTypesCreator(extdataobj, config_file,current_time,unusable,rc )
         type(ExtDataOldTypesCreator), target, intent(out) :: ExtDataObj
         character(len=*), intent(in) :: config_file
         type(ESMF_Time), intent(in) :: current_time
         class(KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         integer :: status
         call ExtDataObj%ExtDataConfig%new_ExtDataConfig_from_yaml(config_file,current_time,_RC)
         _RETURN(_SUCCESS)
         _UNUSED_DUMMY(unusable)
      end subroutine new_ExtDataOldTypesCreator
Call graph
new_extdataoldtypescreator calls mapl_return, mapl_verify, new_extdataconfig_from_yaml
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
new_extdataconfig_from_yaml calls mapl_return, mapl_verify, new_extdataconfig_from_yaml, ESMF_HConfigAsStringMapKey, ESMF_HConfigCreate, ESMF_HConfigCreateAtMapVal, ESMF_HConfigDestroy, ESMF_HConfigIterLoop, esmf_hconfigasi4, esmf_hconfigasstringseq, esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, mapl_assert, insert, add_new_rule, m_at, sort_rules_by_start
initialize_ calls new_extdataoldtypescreator