new_OpenMPServer – MAPL
new_OpenMPServer Function
8 statements
Source File
private function new_OpenMPServer(comm, directory_service) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
class(AbstractDirectoryService), intent(inout), target :: directory_service
Return Value type(OpenMPServer)
Calls
Called by
Source Code
   function new_OpenMPServer(comm,directory_service) result(s)
      type (OpenMPServer) :: s
      integer, intent(in) :: comm
      class(AbstractDirectoryService), target, intent(inout) :: directory_service
      call s%init(comm)
      s%directory_service => directory_service
      call s%directory_service%publish(PortInfo('i_server'), s%comm)
   end function new_OpenMPServer
Call graph
new_openmpserver calls init, publish
init calls mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
openmpserver calls new_openmpserver