new_MultiLayerServer – MAPL
new_MultiLayerServer Function
19 statements
Source File
private function new_MultiLayerServer(comm, port_name, nwriters, pfio_writer, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
character(len=*), intent(in) :: port_name
integer, intent(in) :: nwriters
character(len=*), intent(in) :: pfio_writer
integer, intent(out), optional :: rc
Return Value type(MultiLayerServer)
Calls
Called by
Source Code
   function new_MultiLayerServer(comm, port_name, nwriters, pfio_writer, rc) result(s)
      type (MultiLayerServer) :: s
      integer, intent(in) :: comm
      character(*), intent(in) :: port_name
      integer, intent(in) :: nwriters
      character(*), intent(in) :: pfio_writer
      integer, optional, intent(out) :: rc
      integer :: ierror
      call s%init(comm, port_name)
      s%Inter_Comm = MPI_COMM_NULL
      s%nwriters = nwriters
      _ASSERT(s%nwriters > 1 ,' nwriters should be >=2. pfio_writer.x has captain-soldier structure')
      call MPI_Comm_spawn( pfio_writer , MPI_ARGV_NULL, s%nwriters, MPI_INFO_NULL, 0, &
                   s%comm, s%Inter_Comm, MPI_ERRCODES_IGNORE, ierror)
      _VERIFY(ierror)
      s%port_name = trim(port_name)
      s%threads = ServerThreadVector()
      _RETURN(_SUCCESS)
   end function new_MultiLayerServer
Call graph
new_multilayerserver calls mapl_assert, mpi_comm_spawn, init, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
init calls mapl_return, mapl_verify, mpi_allgather, mpi_barrier, mpi_bcast, mpi_comm_rank, mpi_comm_size, mpi_comm_split, mpi_comm_split_type, start
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
start_self calls mapl_assert, mapl_return, start, get_name
multilayerserver calls new_multilayerserver