new_UngriddedDimSpec_name_and_coords – MAPL
new_UngriddedDimSpec_name_and_coords Function
6 statements
Source File
private pure function new_UngriddedDimSpec_name_and_coords(name, coordinates) result(spec)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: name
real, intent(in) :: coordinates(:)
Return Value type(UngriddedDimSpec)
Calls
Called by
Contents
Source Code
new_UngriddedDimSpec_name_and_coords
Source Code
   pure function new_UngriddedDimSpec_name_and_coords(name, coordinates) result(spec)
      type(UngriddedDimSpec) :: spec
      character(*), intent(in) :: name
      real, intent(in) :: coordinates(:)
      spec = UngriddedDimSpec(name, UNKNOWN_DIM_UNITS, coordinates)
   end function new_UngriddedDimSpec_name_and_coords
Call graph
new_ungriddeddimspec_name_and_coords calls ungriddeddimspec
ungriddeddimspec calls new_ungriddeddimspec_name_and_coords, new_ungriddeddimspec_extent, new_ungriddeddimspec_name_units_and_coords
new_ungriddeddimspec_extent calls ungriddeddimspec, default_coords