new_DistributedMeter – MAPL
new_DistributedMeter Function
10 statements
Source File
private function new_DistributedMeter(gauge) result(distributed_meter)
Arguments
Type Intent Optional Attributes Name
class(AbstractGauge), intent(in) :: gauge
Return Value type(DistributedMeter)
Calls
Called by
Source Code
   function new_DistributedMeter(gauge) result(distributed_meter)
      type(DistributedMeter) :: distributed_meter
      class(AbstractGauge), intent(in) :: gauge
      integer :: ierror
      if (.not. dist_initialized) then
         call initialize(ierror)
         dist_initialized = .true.
      end if
      distributed_meter%AdvancedMeter = AdvancedMeter(gauge)
   end function new_DistributedMeter
Call graph
new_distributedmeter calls initialize
initialize calls mpi_op_create, mpi_type_commit, make_mpi_type, mapl_verify
mapl_verify calls mapl_throw_exception
make_mpi_type_distributed_integer calls mapl_verify, mpi_type_create_struct
mapl_throw_exception calls initialize
distributedmeter calls new_distributedmeter