new_ExtDataDerived – MAPL
new_ExtDataDerived Function
29 statements
Source File
private function new_ExtDataDerived(config, unusable, rc) result(rule)
Arguments
Type Intent Optional Attributes Name
type(ESMF_HConfig), intent(in) :: config
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ExtDataDerived)
Calls
Called by
Contents
Source Code
new_ExtDataDerived
Source Code
   function new_ExtDataDerived(config,unusable,rc) result(rule)
      type(ESMF_HConfig), intent(in) :: config
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ExtDataDerived) :: rule
      logical :: is_present
      integer :: status
      character(len=:), allocatable :: tempc
      _UNUSED_DUMMY(unusable)
      if (allocated(tempc)) deallocate(tempc)
      is_present = ESMF_HConfigIsDefined(config,keyString="function",_RC)
      _ASSERT(is_present,"no expression found in derived entry")
      if (is_present) then
         tempc = ESMF_HConfigAsString(config,keyString="function",_RC)
         rule%expression=tempc
      end if
      if (allocated(tempc)) deallocate(tempc)
      is_present = ESMF_HConfigIsDefined(config,keyString="sample",_RC)
      if (is_present) then
         tempc = ESMF_HConfigAsString(config,keyString="sample",_RC)
         rule%sample_key=tempc
      end if
      _RETURN(_SUCCESS)
   end function new_ExtDataDerived
Call graph
new_extdataderived calls esmf_hconfigasstring, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
extdataderived calls new_extdataderived