new_ProtocolParser – MAPL
new_ProtocolParser Function
4 statements
Source File
private function new_ProtocolParser() result(parser)
Arguments
None
Return Value type(ProtocolParser)
Calls
Called by
Source Code
   function new_ProtocolParser() result(parser)
      type (ProtocolParser) :: parser
      call parser%initialize()
   end function new_ProtocolParser
Call graph
new_protocolparser calls initialize
initialize calls get_type_id, insert
m_insert_pair calls s_insert
protocolparser calls new_protocolparser