new_MpiSocket – MAPL
new_MpiSocket Function
35 statements
Source File
private function new_MpiSocket(comm, remote_rank, parser, rc) result(s)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: comm
integer, intent(in) :: remote_rank
type(ProtocolParser), intent(in), target :: parser
integer, intent(out), optional :: rc
Return Value type(MpiSocket)
Calls
Called by
Source Code
   function new_MpiSocket(comm, remote_rank, parser, rc) result(s)
      type (MpiSocket) :: s
      integer, intent(in) :: comm
      integer, intent(in) :: remote_rank
      type (ProtocolParser), target, intent(in) :: parser
      integer, optional, intent(out) :: rc
      integer :: ierror
      integer :: local_rank
      integer :: pair_group
      integer :: world_group
      integer :: ranks(2)
      s%parser => parser
      s%world_comm = comm
      s%world_remote_rank = remote_rank
      call MPI_Comm_rank(comm, local_rank, ierror)
      _VERIFY(ierror)
      s%world_local_rank = local_rank
      call MPI_Comm_group(comm, world_group, ierror)
      _VERIFY(ierror)
      ! Enforce consistent ordering in new communicator/group
      if (local_rank < remote_rank) then
         ranks = [local_rank, remote_rank]
         s%pair_local_rank = 0
         s%pair_remote_rank = 1
      else
         ranks = [remote_rank, local_rank]
         s%pair_local_rank = 1
         s%pair_remote_rank = 0
      end if
      call MPI_Group_incl(world_group, 2, ranks, pair_group, ierror)
      _VERIFY(ierror)
      call MPI_Comm_create_group(comm, pair_group, PAIR_TAG, s%pair_comm, ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
   end function new_MpiSocket
Call graph
new_mpisocket calls mpi_comm_create_group, mpi_comm_group, mpi_comm_rank, mpi_group_incl, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mpisocket calls new_mpisocket