new_UnlimitedEntity_empty – MAPL
new_UnlimitedEntity_empty Function
4 statements
Source File
private function new_UnlimitedEntity_empty() result(attr)
Arguments
None
Return Value type(UnlimitedEntity)
Called by
Contents
Source Code
new_UnlimitedEntity_empty
Source Code
   function new_UnlimitedEntity_empty() result(attr)
      type (UnlimitedEntity) :: attr
      attr%valid = .true.
   end function new_UnlimitedEntity_empty
Call graph
unlimitedentity calls new_unlimitedentity_empty, new_unlimitedentity_2d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_5d
new_unlimitedentity_2d calls unlimitedentity
new_unlimitedentity_3d calls unlimitedentity
new_unlimitedentity_4d calls unlimitedentity
new_unlimitedentity_5d calls unlimitedentity
unlimitedentity_deserialize calls unlimitedentity
attribute_deserialize calls unlimitedentity_deserialize
stringunlimitedentitymap_deserialize calls unlimitedentity_deserialize
test_serialize calls unlimitedentity_deserialize, attribute_deserialize
stringattributemap_deserialize calls attribute_deserialize