new_DimsSpec_w_halo – MAPL
new_DimsSpec_w_halo Function
11 statements
Source File
private pure function new_DimsSpec_w_halo(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs, halo_width) result(spec)
Arguments
Type Intent Optional Attributes Name
type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
type(VerticalStaggerLoc), intent(in) :: vert_stagger_loc
type(UngriddedDimSpec), intent(in) :: ungridded_dim_specs(:)
integer, intent(in) :: halo_width
Return Value type(DimsSpec)
Called by
Contents
Source Code
new_DimsSpec_w_halo
Source Code
   pure function new_DimsSpec_w_halo(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs, halo_width) result(spec)
      type(DimsSpec) :: spec
      type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
      type(VerticalStaggerLoc) , intent(in) :: vert_stagger_loc
      type(UngriddedDimSpec), intent(in) :: ungridded_dim_specs(:)
      integer, intent(in) :: halo_width
      spec%horz_stagger_loc = horz_stagger_loc
      spec%vert_stagger_loc = vert_stagger_loc
      spec%ungridded_dim_specs = ungridded_dim_specs
      spec%halo_width = halo_width
   end function new_DimsSpec_w_halo
Call graph
dimsspec calls new_dimsspec_w_halo, new_dimsspec_w_ungridded, new_dimsspec_simple
new_dimsspec_w_ungridded calls dimsspec
new_dimsspec_simple calls dimsspec