new_CapOptions_from_fargparse_back_comp – MAPL
new_CapOptions_from_fargparse_back_comp Function
18 statements
Source File
private function new_CapOptions_from_fargparse_back_comp(unusable, extra, rc) result(fargparsecap)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_FargparseCLI)
Calls
Called by
Contents
Source Code
new_CapOptions_from_fargparse_back_comp
Source Code
   function new_CapOptions_from_fargparse_back_comp(unusable, extra, rc) result (fargparsecap)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type (MAPL_FargparseCLI) :: fargparsecap
      procedure(I_extraoptions), optional :: extra
      integer, optional, intent(out) :: rc
      integer :: status
      fargparsecap%parser = ArgParser()
      call fargparsecap%add_command_line_options(fargparsecap%parser, _RC)
      if (present(extra)) then
         call extra(fargparsecap%parser, _RC)
      end if
      fargparsecap%options = fargparsecap%parser%parse_args()
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function new_CapOptions_from_fargparse_back_comp
Call graph
new_capoptions_from_fargparse_back_comp calls argparser, add_command_line_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, add_argument, push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_fargparsecli calls new_capoptions_from_fargparse_back_comp