new_CapOptions_from_fargparse – MAPL
new_CapOptions_from_fargparse Function
23 statements
Source File
private function new_CapOptions_from_fargparse(unusable, dummy, extra, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: dummy
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
Calls
Called by
Contents
Source Code
new_CapOptions_from_fargparse
Source Code
   function new_CapOptions_from_fargparse(unusable, dummy, extra, rc) result (cap_options)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type (MAPL_CapOptions) :: cap_options
      character(*), intent(in) :: dummy !Needed for backward compatibility. Remove after 3.0
      procedure(I_extraoptions), optional :: extra
      integer, optional, intent(out) :: rc
      integer :: status
      type(MAPL_FargparseCLI) :: fargparse_cli
      fargparse_cli%parser = ArgParser()
      call fargparse_cli%add_command_line_options(fargparse_cli%parser, _RC)
      if (present(extra)) then
         call extra(fargparse_cli%parser, _RC)
      end if
      fargparse_cli%options = fargparse_cli%parser%parse_args()
      call fargparse_cli%fill_cap_options(cap_options, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(dummy)
   end function new_CapOptions_from_fargparse
Call graph
new_capoptions_from_fargparse calls argparser, add_command_line_options, fill_cap_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, add_argument, push_back
fill_cap_options calls mapl_return, mapl_verify, cast, mapl_assert, of
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_fargparsecli calls new_capoptions_from_fargparse