new_ServerThread – MAPL
new_ServerThread Function
12 statements
Source File
private function new_ServerThread(sckt, server, rc) result(s)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), target :: sckt
class(AbstractServer), intent(in), optional, target :: server
integer, intent(out), optional :: rc
Return Value type(ServerThread)
Calls
Called by
Source Code
   function new_ServerThread(sckt, server, rc) result(s)
      class (AbstractSocket), target, intent(in) :: sckt
      class (AbstractServer), target,optional, intent(in) :: server
      integer, optional, intent(out) :: rc
      type (ServerThread) :: s
      integer :: status
      call s%set_connection(sckt, _RC)
      if(present(server)) s%containing_server => server
      _RETURN(_SUCCESS)
   end function new_ServerThread
Call graph
new_serverthread calls mapl_return, mapl_verify, set_connection
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_connection calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize
serverthread calls new_serverthread