new_ClientThread – MAPL
new_ClientThread Function
5 statements
Source File
private function new_ClientThread(sckt) result(c)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), optional :: sckt
Return Value type(ClientThread), target
Calls
Called by
Source Code
   function new_ClientThread(sckt) result(c)
      type (ClientThread),target :: c
      class(AbstractSocket),optional,intent(in) :: sckt
      if(present(sckt)) call c%set_connection(sckt)
   end function new_ClientThread
Call graph
new_clientthread calls set_connection
set_connection calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
clientthread calls new_clientthread