new_DimsSpec_w_ungridded – MAPL
new_DimsSpec_w_ungridded Function
7 statements
Source File
private pure function new_DimsSpec_w_ungridded(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs) result(spec)
Arguments
Type Intent Optional Attributes Name
type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
type(VerticalStaggerLoc), intent(in) :: vert_stagger_loc
type(UngriddedDimSpec), intent(in) :: ungridded_dim_specs(:)
Return Value type(DimsSpec)
Calls
Called by
Contents
Source Code
new_DimsSpec_w_ungridded
Source Code
   pure function new_DimsSpec_w_ungridded(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs) result(spec)
      type(DimsSpec) :: spec
      type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
      type(VerticalStaggerLoc) , intent(in) :: vert_stagger_loc
      type(UngriddedDimSpec), intent(in) :: ungridded_dim_specs(:)
      spec = DimsSpec(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs, halo_width=0)
   end function new_DimsSpec_w_ungridded
Call graph
new_dimsspec_w_ungridded calls dimsspec
dimsspec calls new_dimsspec_w_ungridded, new_dimsspec_simple, new_dimsspec_w_halo
new_dimsspec_simple calls dimsspec