new_verticalCoordinate – MAPL
new_verticalCoordinate Function
125 statements
Source File
private function new_verticalCoordinate(metadata, var_name, rc) result(vertical_coord)
Arguments
Type Intent Optional Attributes Name
type(FileMetadataUtils), intent(in) :: metadata
character(len=*), intent(in) :: var_name
integer, intent(out), optional :: rc
Return Value type(VerticalCoordinate)
Calls
Called by
Source Code
   function new_verticalCoordinate(metadata, var_name, rc) result(vertical_coord)
      type(VerticalCoordinate) :: vertical_coord
      type(FileMetaDataUtils), intent(in) :: metadata
      character(len=*), intent(in) :: var_name
      integer, optional, intent(out) :: rc
      integer :: status, i
      type(StringVector), pointer :: dimensions
      type(StringVectorIterator) :: iter
      type(Variable), pointer :: var, dim_var, ps_var
      class(CoordinateVariable), pointer :: coord_var
      character(len=:), pointer :: dim_name
      logical :: is_vertical_coord_var, has_pressure_units, has_height_units
      character(len=:), allocatable :: lev_name, temp_units, formula_terms, standard_name, bounds_var, ak_name, bk_name, ps_name, source_file
      type(NETCDF4_FileFormatter) :: file_formatter
      real, allocatable :: temp_ak(:,:), temp_bk(:,:)
      vertical_coord%num_levels = 0 ! initialze
      var => metadata%get_variable(var_name, _RC)
      dimensions => var%get_dimensions()
      lev_name = ''
      iter = dimensions%begin()
      dimensions => var%get_dimensions()
      do while(iter /= dimensions%end())
         dim_name => iter%get()
         if (metadata%has_variable(dim_name)) then
            dim_var => metadata%get_variable(dim_name)
            is_vertical_coord_var = detect_cf_vertical_coord_var(dim_var, _RC)
            if (is_vertical_coord_var) then
               lev_name = dim_name
               exit
            end if
         end if
         call iter%next()
      end do
      ! if not blank, we found something that "looks" like a vertical coordinate according to cf, now lets fill it out
      if (lev_name /= '') then
         coord_var => metadata%get_coordinate_variable(lev_name, _RC)
         vertical_coord%levels = get_coords(coord_var,_RC)
         vertical_coord%num_levels = size(vertical_coord%levels)
         if (coord_var%is_attribute_present("positive")) vertical_coord%positive = coord_var%get_attribute_string("positive")
         if (coord_var%is_attribute_present("units"))  temp_units = coord_var%get_attribute_string("units")
         ! now test if this is a "fixed" pressure level, if has units of pressure, then CF says is pressure dimensional coordinate
         has_pressure_units = safe_are_convertible(temp_units, 'hPa', _RC)
         if (has_pressure_units) then
            vertical_coord%level_units = temp_units
            vertical_coord%vertical_type = fixed_pressure
            if (vertical_coord%levels(1) > vertical_coord%levels(2)) vertical_coord%positive = "up" !bmaa
            _RETURN(_SUCCESS)
         end if
         ! now test if this is a "fixed" height level, if has height units, then dimensioanl coordinate, but must have positive
         has_height_units = safe_are_convertible(temp_units, 'm', _RC)
         if (has_height_units) then
            _ASSERT(allocated(vertical_coord%positive),"non pressure veritcal dimensional coordinates must have positive attribute")
            vertical_coord%level_units = temp_units
            vertical_coord%vertical_type = fixed_height
            _RETURN(_SUCCESS)
         end if
         ! now test if this is a model pressure, the positive says is vertical and formula_terms says, this is a parametric quantity
         if (coord_var%is_attribute_present("positive") .and. coord_var%is_attribute_present("formula_terms")) then
            standard_name = coord_var%get_attribute_string("standard_name")
            formula_terms = coord_var%get_attribute_string("formula_terms")
            if (standard_name == "atmosphere_hybrid_sigma_pressure_coordinate") then
               ! do we have bounds, if so this is centers
               source_file = metadata%get_source_file()
               if (coord_var%is_attribute_present('bounds')) then
                  bounds_var = coord_var%get_attribute_string("bounds")
                  var => metadata%get_variable(bounds_var, _RC)
                  formula_terms = var%get_attribute_string("formula_terms")
                  call parse_formula_terms(formula_terms, ps_name, ak_name, bk_name, _RC)
                  vertical_coord%surf_name = ps_name
                  ps_var => metadata%get_variable(ps_name)
                  vertical_coord%surf_units = ps_var%get_attribute_string("units")
                  vertical_coord%stagger = vertical_stagger_center
                  allocate(temp_ak(2,vertical_coord%num_levels))
                  allocate(temp_bk(2,vertical_coord%num_levels))
                  allocate(vertical_coord%ak(vertical_coord%num_levels+1))
                  allocate(vertical_coord%bk(vertical_coord%num_levels+1))
                  call file_formatter%open(source_file, PFIO_READ, _RC)
                  call file_formatter%get_var(ak_name, temp_ak, _RC)
                  call file_formatter%get_var(bk_name, temp_bk, _RC)
                  do i=2,vertical_coord%num_levels+1
                     vertical_coord%ak(i-1) = temp_ak(1,i-1)
                     vertical_coord%ak(i) = temp_ak(2,i-1)
                     vertical_coord%bk(i-1) = temp_bk(1,i-1)
                     vertical_coord%bk(i) = temp_bk(2,i-1)
                  enddo
               else
               ! do we not have bounds, if so this is edge
                  vertical_coord%num_levels = vertical_coord%num_levels - 1
                  call parse_formula_terms(formula_terms, ps_name, ak_name, bk_name, _RC)
                  vertical_coord%surf_name = ps_name
                  ps_var => metadata%get_variable(ps_name)
                  vertical_coord%surf_units = ps_var%get_attribute_string("units")
                  vertical_coord%stagger = vertical_stagger_edge
                  allocate(vertical_coord%ak(vertical_coord%num_levels+1))
                  allocate(vertical_coord%bk(vertical_coord%num_levels+1))
                  call file_formatter%open(source_file, PFIO_READ, _RC)
                  call file_formatter%get_var(ak_name, vertical_coord%ak, _RC)
                  call file_formatter%get_var(bk_name, vertical_coord%bk, _RC)
               end if
            else
               _FAIL("unsupported hybrid vertical coordinate")
            end if
            _ASSERT(allocated(vertical_coord%surf_name), "PS was not found in the file")
            vertical_coord%vertical_type = model_pressure
            _RETURN(_SUCCESS)
         end if
         ! if this is none of those, then a simple coordinate
         vertical_coord%vertical_type = simple_coord
      else
         vertical_coord%vertical_type = no_coord
      end if
      _RETURN(_SUCCESS)
    end function new_VerticalCoordinate
Call graph
new_verticalcoordinate calls begin, get, mapl_assert, next, get_var, detect_cf_vertical_coord_var, get_attribute_string, get_coordinate_variable, get_coords, get_dimensions, get_source_file, get_variable, has_variable, is_attribute_present, mapl_return, mapl_verify, parse_formula_terms, safe_are_convertible
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
detect_cf_vertical_coord_var calls get_attribute_string, is_attribute_present, mapl_return, mapl_verify, safe_are_convertible
get_attribute_string calls mapl_assert, mapl_return, mapl_verify, get_attribute, get_value
get_coordinate_variable calls mapl_assert, mapl_return, m_at
get_coords calls mapl_assert, mapl_return, get_coordinate_data
get_source_file calls mapl_assert, mapl_return
get_variable calls mapl_return, m_at
has_variable calls mapl_return, m_at
is_attribute_present calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
parse_formula_terms calls mapl_return, find_term
safe_are_convertible calls mapl_return, mapl_verify, is_free, udunits_are_convertible
verticalcoordinate calls new_verticalcoordinate