new_EtaHybridVerticalCoordinate_by_ak_bk – MAPL
new_EtaHybridVerticalCoordinate_by_ak_bk Function
19 statements
Source File
private function new_EtaHybridVerticalCoordinate_by_ak_bk(ak, bk, unusable, ref_pressure, rc) result(grid)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: ak(:)
real(kind=REAL64), intent(in) :: bk(:)
class(KeywordEnforcer), intent(in), optional :: unusable
real(kind=REAL64), intent(in), optional :: ref_pressure
integer, intent(inout), optional :: rc
Return Value type(EtaHybridVerticalCoordinate)
Calls
Called by
Contents
Source Code
new_EtaHybridVerticalCoordinate_by_ak_bk
Source Code
   function new_EtaHybridVerticalCoordinate_by_ak_bk(ak, bk, unusable, ref_pressure, rc) result(grid)
      type (EtaHybridVerticalCoordinate) :: grid
      real(kind=REAL64), intent(in) :: ak(:)
      real(kind=REAL64), intent(in) :: bk(:)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      real(kind=REAL64),optional, intent(in) :: ref_pressure
      integer, optional, intent(inout) :: rc
      _UNUSED_DUMMY(unusable)
      _ASSERT(size(ak) >= 2, 'size of ak should be >=2')
      _ASSERT(size(ak) == size(bk), ' size of ak should be the same as that of bk')
      grid%ak = ak
      grid%bk = bk
      grid%num_levels = size(ak) - 1
      if (present(ref_pressure)) then
         grid%ref_pressure = ref_pressure
      else
         grid%ref_pressure = DEFAULT_REFERENCE_PRESSURE
      end if
   end function new_EtaHybridVerticalCoordinate_by_ak_bk
Call graph
new_etahybridverticalcoordinate_by_ak_bk calls mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
etahybridverticalcoordinate calls new_etahybridverticalcoordinate_by_ak_bk, new_etahybridverticalcoordinate_by_cfg, new_etahybridverticalcoordinate_by_file
get_eta_onestep_r4 calls etahybridverticalcoordinate, get_eta
get_eta_onestep_r8 calls etahybridverticalcoordinate, get_eta
new_etahybridverticalcoordinate_by_cfg calls etahybridverticalcoordinate
new_etahybridverticalcoordinate_by_file calls etahybridverticalcoordinate
get_eta calls get_eta_onestep_r4, get_eta_onestep_r8
get_eta_r4 calls get_eta