new_MeterNode – MAPL
new_MeterNode Function
14 statements
Source File
private function new_MeterNode(name, meter, depth) result(tree)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
class(AbstractMeter), intent(in) :: meter
integer, intent(in), optional :: depth
Return Value type(MeterNode)
Called by
Contents
Source Code
new_MeterNode
Source Code
   function new_MeterNode(name, meter, depth) result(tree)
      type (MeterNode) :: tree
      character(*), intent(in) :: name
      class(AbstractMeter), intent(in) :: meter
      integer, optional, intent(in) :: depth
      tree%name = name
      tree%meter = meter
      if (present(depth)) then
         tree%depth = depth
      else
         tree%depth = 0
      end if
      tree%last_child_accessed = 0
   end function new_MeterNode
Call graph
meternode calls new_meternode
add_child calls meternode
accumulate calls add_child, accumulate