new_ExtDataNG_IOBundle – MAPL
new_ExtDataNG_IOBundle Function
28 statements
Source File
public function new_ExtDataNG_IOBundle(bracket_side, entry_index, file_name, time_index, regrid_method, fraction, template, metadata_coll_id, server_coll_id, items, on_tiles, rc) result(io_bundle)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: bracket_side
integer, intent(in) :: entry_index
character(len=*), intent(in) :: file_name
integer, intent(in) :: time_index
integer, intent(in) :: regrid_method
integer, intent(in) :: fraction
character(len=*), intent(in) :: template
integer, intent(in) :: metadata_coll_id
integer, intent(in) :: server_coll_id
type(GriddedIOitemVector) :: items
logical, intent(in) :: on_tiles
integer, intent(out), optional :: rc
Return Value type(ExtDataNG_IOBundle)
Calls
Called by
Contents
Source Code
new_ExtDataNG_IOBundle
Source Code
  function new_ExtDataNG_IOBundle(bracket_side, entry_index, file_name, time_index, regrid_method, fraction, template, metadata_coll_id,server_coll_id,items, on_tiles, rc) result(io_bundle)
    type (ExtDataNG_IOBundle) :: io_bundle
    integer, intent(in) :: bracket_side
    integer, intent(in) :: entry_index
    character(len=*), intent(in) :: file_name
    integer, intent(in) :: time_index
    integer, intent(in) :: regrid_method
    integer, intent(in) :: fraction
    character(len=*), intent(in) :: template
    integer, intent(in) :: metadata_coll_id
    integer, intent(in) :: server_coll_id
    type(GriddedIOItemVector) :: items
    logical, intent(in) :: on_tiles
    integer, optional, intent(out) :: rc
    io_bundle%bracket_side = bracket_side
    io_bundle%entry_index = entry_index
    io_bundle%file_name = file_name
    io_bundle%time_index = time_index
    io_bundle%regrid_method = regrid_method
    io_bundle%fraction = fraction
    io_bundle%template = trim(template)
    io_bundle%metadata_coll_id=metadata_coll_id
    io_bundle%server_coll_id=server_coll_id
    io_bundle%items=items
    io_bundle%on_tiles = on_tiles
    _RETURN(ESMF_SUCCESS)
  end function new_ExtDataNG_IOBundle
Call graph
new_extdatang_iobundle calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
extdatang_iobundle calls new_extdatang_iobundle
iobundle_add_entry calls extdatang_iobundle
run_ calls iobundle_add_entry