new_UnlimitedEntity_5d – MAPL
new_UnlimitedEntity_5d Function
25 statements
Source File
private function new_UnlimitedEntity_5d(values, rc) result(attr)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: values(:,:,:,:,:)
integer, intent(out), optional :: rc
Return Value type(UnlimitedEntity)
Calls
Called by
Contents
Source Code
new_UnlimitedEntity_5d
Source Code
   function new_UnlimitedEntity_5d(values, rc) result(attr)
      type (UnlimitedEntity) :: attr
      class (*), intent(in) :: values(:,:,:,:,:)
      integer, optional, intent(out) :: rc
      class (*), allocatable :: values1d(:)
      select type (values)
      type is (integer(INT32))
         allocate(values1d, source = reshape(values, [product(shape(values))]))
      type is (integer(INT64))
         allocate(values1d, source = reshape(values, [product(shape(values))]))
      type is (real(real32))
         allocate(values1d, source = reshape(values, [product(shape(values))]))
      type is (real(real64))
         allocate(values1d, source = reshape(values, [product(shape(values))]))
      type is (logical)
         allocate(values1d, source = reshape(values, [product(shape(values))]))
      class default
        _FAIL( 'not support type')
      end select
      attr = UnlimitedEntity(values1d)
      attr%shape = shape(values)
      deallocate(values1d)
      _RETURN(_SUCCESS)
   end function new_UnlimitedEntity_5d
Call graph
new_unlimitedentity_5d calls mapl_assert, unlimitedentity, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
unlimitedentity calls new_unlimitedentity_5d, new_unlimitedentity_0d, new_unlimitedentity_1d, new_unlimitedentity_2d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_empty
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_unlimitedentity_0d calls mapl_return
new_unlimitedentity_1d calls mapl_assert, mapl_return
new_unlimitedentity_2d calls mapl_assert, unlimitedentity, mapl_return
new_unlimitedentity_3d calls mapl_assert, unlimitedentity, mapl_return
new_unlimitedentity_4d calls mapl_assert, unlimitedentity, mapl_return
unlimitedentity_deserialize calls unlimitedentity
attribute_deserialize calls unlimitedentity_deserialize
stringunlimitedentitymap_deserialize calls unlimitedentity_deserialize
test_serialize calls unlimitedentity_deserialize, attribute_deserialize
stringattributemap_deserialize calls attribute_deserialize