new_simple_alarm – MAPL
new_simple_alarm Function
10 statements
Source File
private function new_simple_alarm(reference_time, ring_interval, rc) result(new_alarm)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: reference_time
type(ESMF_TimeInterval), intent(in) :: ring_interval
integer, intent(out), optional :: rc
Return Value type(SimpleAlarm)
Calls
Called by
Source Code
   function new_simple_alarm(reference_time,ring_interval,rc) result(new_alarm)
      type(ESMF_Time), intent(in) :: reference_time
      type(ESMF_TimeInterval), intent(in) :: ring_interval
      integer, optional, intent(out) :: rc
      type(SimpleAlarm) :: new_alarm
      new_alarm%reference_time = reference_time
      new_alarm%ring_interval = ring_interval
      _RETURN(_SUCCESS)
   end function new_simple_alarm
Call graph
new_simple_alarm calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
simplealarm calls new_simple_alarm