new_ClientManager – MAPL
new_ClientManager Function
34 statements
Source File
private function new_ClientManager(client_comm, unusable, n_client, fast_oclient, rc) result(c_manager)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: client_comm
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: n_client
logical, intent(in), optional :: fast_oclient
integer, intent(out), optional :: rc
Return Value type(ClientManager)
Calls
Called by
Source Code
   function new_ClientManager(client_comm, unusable, n_client, fast_oclient, rc) result (c_manager)
      integer, intent(in) :: client_comm
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in) :: n_client
      logical, optional, intent(in) :: fast_oclient
      integer, optional, intent(out) :: rc
      type (ClientManager) :: c_manager
      class (ClientThread), pointer :: clientPtr
      integer :: i, n
      logical :: fast_
      n = 1
      if (present(n_client)) n = n_client
      fast_ = .false.
      if (present(fast_oclient)) fast_ = fast_oclient
      c_manager%clients = ClientThreadVector()
      do i = 1, n
        if (fast_) then
           allocate(clientPtr, source = FastClientThread())
        else
           allocate(clientPtr, source = ClientThread())
        endif
        call c_manager%clients%push_back(clientPtr)
        clientPtr=>null()
      enddo
      c_manager%client_comm = client_comm
      call MPI_Comm_rank(client_comm, c_manager%rank, rc)
      _VERIFY(rc)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function new_ClientManager
Call graph
new_clientmanager calls mpi_comm_rank, mapl_return, mapl_verify, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_push_back calls resize, v_grow_to
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
clientmanager calls new_clientmanager