new_ShmemReference – MAPL
new_ShmemReference Function
15 statements
Source File
private function new_ShmemReference(type_kind, msize_word, InNode_Comm, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer(kind=INT64), intent(in) :: msize_word
integer, intent(in) :: InNode_Comm
integer, intent(out), optional :: rc
Return Value type(ShmemReference)
Calls
Called by
Contents
Source Code
new_ShmemReference
Source Code
   function new_ShmemReference(type_kind,msize_word,InNode_Comm, rc) result(reference)
      type (ShmemReference) :: reference
      integer, intent(in) :: type_kind
      integer(kind=INT64), intent(in) :: msize_word
      integer, intent(in) :: InNode_Comm
      integer, optional, intent(out) :: rc
      integer :: status
      reference%msize_word = msize_word
      reference%type_kind  = type_kind
      call Mpi_comm_dup(InNode_Comm,reference%InNode_Comm,status)
      call reference%allocate(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function new_ShmemReference
Call graph
new_shmemreference calls mpi_comm_dup, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
shmemreference calls new_shmemreference