new_ArrayReference_0d – MAPL
new_ArrayReference_0d Function
21 statements
Source File
private function new_ArrayReference_0d(scalar, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: scalar
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
Calls
Called by
Contents
Source Code
new_ArrayReference_0d
Source Code
   function new_ArrayReference_0d(scalar, rc) result(reference)
      type (ArrayReference) :: reference
      class(*), target, intent(in) :: scalar
      integer, optional, intent(out) :: rc
      select type (scalar)
      type is (real(kind=REAL32))
         reference%base_address = c_loc(scalar)
      type is (real(kind=REAL64))
         reference%base_address = c_loc(scalar)
      type is (integer(kind=INT32))
         reference%base_address = c_loc(scalar)
      type is (integer(kind=INT64))
         reference%base_address = c_loc(scalar)
      class default
         _FAIL( "ArrayRef does not support this type")
      end select
      reference%shape = shape(scalar)
      reference%type_kind = type_kind(scalar)
      _RETURN(_SUCCESS)
   end function new_ArrayReference_0d
Call graph
new_arrayreference_0d calls mapl_assert, mapl_return, type_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
type_kind calls mapl_assert, mapl_return
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
arrayreference calls new_arrayreference_0d