new_DimsSpec_simple – MAPL
new_DimsSpec_simple Function
7 statements
Source File
private pure function new_DimsSpec_simple(horz_stagger_loc, vert_stagger_loc) result(spec)
Arguments
Type Intent Optional Attributes Name
type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
type(VerticalStaggerLoc), intent(in) :: vert_stagger_loc
Return Value type(DimsSpec)
Calls
Called by
Contents
Source Code
new_DimsSpec_simple
Source Code
   pure function new_DimsSpec_simple(horz_stagger_loc, vert_stagger_loc) result(spec)
      type(DimsSpec) :: spec
      type(HorizontalStaggerLoc), intent(in) :: horz_stagger_loc
      type(VerticalStaggerLoc) , intent(in) :: vert_stagger_loc
      type(UngriddedDimSpec) :: no_ungridded(0)
      spec = DimsSpec(horz_stagger_loc, vert_stagger_loc, ungridded_dim_specs=no_ungridded, halo_width=0)
   end function new_DimsSpec_simple
Call graph
new_dimsspec_simple calls dimsspec
dimsspec calls new_dimsspec_simple, new_dimsspec_w_halo, new_dimsspec_w_ungridded
new_dimsspec_w_ungridded calls dimsspec