new_ArrayReference_1d – MAPL
new_ArrayReference_1d Function
27 statements
Source File
private function new_ArrayReference_1d(array, rc) result(reference)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in), target :: array(:)
integer, intent(out), optional :: rc
Return Value type(ArrayReference)
Calls
Called by
Contents
Source Code
new_ArrayReference_1d
Source Code
   function new_ArrayReference_1d(array, rc) result(reference)
      type (ArrayReference) :: reference
      class(*), target, intent(in) :: array(:)
      integer, optional, intent(out) :: rc
      logical :: has_address
      has_address = (size(array) /= 0)
      reference%base_address=C_NULL_PTR
      select type (array)
      type is (real(kind=REAL32))
         if (has_address)   reference%base_address = c_loc(array)
         reference%type_kind = pFIO_REAL32
      type is (real(kind=REAL64))
         if (has_address)   reference%base_address = c_loc(array)
         reference%type_kind = pFIO_REAL64
      type is (integer(kind=INT32))
         if (has_address)   reference%base_address = c_loc(array)
         reference%type_kind = pFIO_INT32
      type is (integer(kind=INT64))
         if (has_address)   reference%base_address = c_loc(array)
         reference%type_kind = pFIO_INT64
      class default
         _FAIL( "ArrayRef does not support this type")
      end select
      reference%shape = shape(array)
      _RETURN(_SUCCESS)
   end function new_ArrayReference_1d
Call graph
new_arrayreference_1d calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
arrayreference calls new_arrayreference_1d