new_CapOptions_from_flap – MAPL
new_CapOptions_from_flap Function
25 statements
Source File
private function new_CapOptions_from_flap(unusable, description, authors, dummy, extra, rc) result(cap_options)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: description
character(len=*), intent(in) :: authors
character(len=*), intent(in) :: dummy
procedure(I_extraoptions), optional :: extra
integer, intent(out), optional :: rc
Return Value type(MAPL_CapOptions)
Calls
Called by
Contents
Source Code
new_CapOptions_from_flap
Source Code
   function new_CapOptions_from_flap(unusable, description, authors, dummy, extra, rc) result (cap_options)
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type (MAPL_CapOptions) :: cap_options
      character(*), intent(in) :: description
      character(*), intent(in) :: authors
      character(*), intent(in) :: dummy !Needed for backward compatibility. Remove after 3.0
      procedure(I_extraoptions), optional :: extra
      integer, optional, intent(out) :: rc
      integer :: status
      type(MAPL_FlapCLI) :: flap_cli
      call flap_cli%cli_options%init( &
        description = trim(description), &
        authors     = trim(authors))
      call flap_cli%add_command_line_options(flap_cli%cli_options, rc=status)
      _VERIFY(status)
      if (present(extra)) then
         call extra(flap_cli%cli_options, _RC)
      end if
      call flap_cli%cli_options%parse(error=status); _VERIFY(status)
      call flap_cli%fill_cap_options(cap_options, rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function new_CapOptions_from_flap
Call graph
new_capoptions_from_flap calls add_command_line_options, fill_cap_options, mapl_return, mapl_verify
add_command_line_options calls mapl_return, mapl_verify, add
fill_cap_options calls mapl_return, mapl_verify, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_flapcli calls new_capoptions_from_flap