new_ExtDataConfig_from_yaml – MAPL
new_ExtDataConfig_from_yaml Subroutine
131 statements
Source File
private recursive subroutine new_ExtDataConfig_from_yaml(ext_config, config_file, current_time, unusable, rc)
Type Bound
ExtDataConfig
Arguments
Type Intent Optional Attributes Name
class(ExtDataConfig), intent(inout), target :: ext_config
character(len=*), intent(in) :: config_file
type(ESMF_Time), intent(in) :: current_time
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Contents
Source Code
new_ExtDataConfig_from_yaml
Source Code
   recursive subroutine new_ExtDataConfig_from_yaml(ext_config,config_file,current_time,unusable,rc)
      class(ExtDataConfig), intent(inout), target :: ext_config
      character(len=*), intent(in) :: config_file
      type(ESMF_Time), intent(in) :: current_time
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ESMF_HConfig) :: input_config
      type(ESMF_HConfig) :: temp_configs
      type(ESMF_HConfigIter) :: hconfigIter,hconfigIterBegin,hconfigIterEnd
      character(len=:), allocatable :: hconfig_key
      type(ESMF_HConfig) :: single_sample,single_collection,single_export,rule_map,hconfig_val
      character(len=:), allocatable :: new_key
      type(ExtDataFileStream) :: ds
      type(ExtDataDerived) :: derived
      type(ExtDataTimeSample) :: ts
      integer :: status
      type(ExtDataFileStream), pointer :: temp_ds
      type(ExtDataDerived), pointer :: temp_derived
      integer :: i,num_rules
      integer, allocatable :: sorted_rules(:)
      character(len=1) :: i_char
      logical :: file_found
      logical :: is_right_type
      character(len=:), allocatable :: sub_configs(:)
      _UNUSED_DUMMY(unusable)
      inquire(file=trim(config_file),exist=file_found)
      _ASSERT(file_found,"could not find: "//trim(config_file))
      input_config = ESMF_HConfigCreate(filename=trim(config_file),_RC)
      if (ESMF_HConfigIsDefined(input_config,keyString="subconfigs")) then
         is_right_type = ESMF_HConfigIsSequence(input_config,keyString='subconfigs',_RC)
         _ASSERT(is_right_type,"subconfig list is not a sequence")
         sub_configs = ESMF_HConfigAsStringSeq(input_config,ESMF_MAXPATHLEN,keyString='subconfigs',_RC)
         do i=1,size(sub_configs)
            call new_ExtDataConfig_from_yaml(ext_config,sub_configs(i),current_time,_RC)
         enddo
      end if
      if (ESMF_HConfigIsDefined(input_config,keyString="Samplings")) then
         temp_configs = ESMF_HConfigCreateAt(input_config,keyString="Samplings",_RC)
         hconfigIter = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterBegin = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterEnd = ESMF_HConfigIterEnd(temp_configs)
         do while (ESMF_HConfigIterLoop(hconfigIter,hconfigIterBegin,hconfigIterEnd))
            hconfig_key = ESMF_HConfigAsStringMapKey(hconfigIter,_RC)
            single_sample = ESMF_HConfigCreateAtMapVal(hconfigIter,_RC)
            ts = ExtDataTimeSample(single_sample,_RC)
            call ext_config%sample_map%insert(trim(hconfig_key),ts)
         enddo
      end if
      if (ESMF_HConfigIsDefined(input_config,keyString="Collections")) then
         temp_configs = ESMF_HConfigCreateAt(input_config,keyString="Collections",_RC)
         hconfigIter = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterBegin = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterEnd = ESMF_HConfigIterEnd(temp_configs)
         do while (ESMF_HConfigIterLoop(hconfigIter,hconfigIterBegin,hconfigIterEnd))
            hconfig_key = ESMF_HConfigAsStringMapKey(hconfigIter,_RC)
            temp_ds => ext_config%file_stream_map%at(hconfig_key)
            _ASSERT(.not.associated(temp_ds),"defined duplicate named collection")
            single_collection = ESMF_HConfigCreateAtMapVal(hconfigIter,_RC)
            ds = ExtDataFileStream(single_collection,current_time,_RC)
            call ext_config%file_stream_map%insert(trim(hconfig_key),ds)
         enddo
      end if
      if (ESMF_HConfigIsDefined(input_config,keyString="Exports")) then
         temp_configs = ESMF_HConfigCreateAt(input_config,keyString="Exports",_RC)
         hconfigIter = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterBegin = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterEnd = ESMF_HConfigIterEnd(temp_configs)
         do while (ESMF_HConfigIterLoop(hconfigIter,hconfigIterBegin,hconfigIterEnd))
            hconfig_key = ESMF_HConfigAsStringMapKey(hconfigIter,_RC)
            hconfig_val = ESMF_HConfigCreateAtMapVal(hconfigIter,_RC)
            if (ESMF_HConfigIsMap(hconfig_val)) then
               call ext_config%add_new_rule(hconfig_key,hconfig_val,_RC)
            else if (ESMF_HConfigIsSequence(hconfig_val)) then
               sorted_rules = sort_rules_by_start(hconfig_val,_RC)
               num_rules = ESMF_HConfigGetSize(hconfig_val,_RC)
               do i=1,num_rules
                  rule_map = ESMF_HConfigCreateAt(hconfig_val,index=sorted_rules(i),_RC)
                  write(i_char,'(I1)')i
                  new_key = hconfig_key//rule_sep//i_char
                  call ext_config%add_new_rule(new_key,rule_map,multi_rule=.true.,_RC)
               enddo
            else
               _FAIL("Unsupported type")
            end if
         enddo
      end if
      if (ESMF_HConfigIsDefined(input_config,keyString="Derived")) then
         temp_configs = ESMF_HConfigCreateAt(input_config,keyString="Derived",_RC)
         hconfigIter = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterBegin = ESMF_HConfigIterBegin(temp_configs)
         hconfigIterEnd = ESMF_HConfigIterEnd(temp_configs)
         do while (ESMF_HConfigIterLoop(hconfigIter,hconfigIterBegin,hconfigIterEnd))
            hconfig_key = ESMF_HConfigAsStringMapKey(hconfigIter,_RC)
            single_export = ESMF_HConfigCreateAtMapVal(hconfigIter,_RC)
            derived = ExtDataDerived(single_export,_RC)
            temp_derived => ext_config%derived_map%at(trim(hconfig_key))
             _ASSERT(.not.associated(temp_derived),"duplicated derived entry key")
            call ext_config%derived_map%insert(trim(hconfig_key),derived)
         end do
      end if
      if (ESMF_HConfigIsDefined(input_config,keyString="debug") )then
         ext_config%debug =  ESMF_HConfigAsI4(input_config,keyString="debug",_RC)
      end if
      _RETURN(_SUCCESS)
   end subroutine new_ExtDataConfig_from_yaml
Call graph
new_extdataconfig_from_yaml calls new_extdataconfig_from_yaml, ESMF_HConfigCreate, esmf_hconfigasi4, esmf_hconfigasstringmapkey, esmf_hconfigasstringseq, esmf_hconfigcreateat, esmf_hconfigcreateatmapval, esmf_hconfiggetsize, esmf_hconfigisdefined, esmf_hconfigismap, esmf_hconfigissequence, esmf_hconfigiterbegin, esmf_hconfigiterend, esmf_hconfigiterloop, mapl_assert, add_new_rule, mapl_return, mapl_verify, sort_rules_by_start
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_new_rule calls mapl_assert, mapl_return, mapl_verify, set_defaults, split_vector
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
sort_rules_by_start calls esmf_hconfigcreateat, esmf_hconfiggetsize, esmf_hconfigisdefined, mapl_assert, mapl_return, mapl_verify, esmf_hconfigasstring, string_to_esmf_time
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
string_to_esmf_time calls mapl_return, mapl_verify, ESMF_TimeSet, string_to_integer_date, string_to_integer_time
string_to_integer_date calls mapl_return
string_to_integer_time calls mapl_return