new_MockClientThread – MAPL
new_MockClientThread Function
5 statements
Source File
private function new_MockClientThread(sckt) result(c)
Arguments
Type Intent Optional Attributes Name
class(AbstractSocket), intent(in), optional :: sckt
Return Value type(MockClientThread), target
Calls
Called by
Source Code
   function new_MockClientThread(sckt) result(c)
      type (MockClientThread),target :: c
      class(AbstractSocket),optional,intent(in) :: sckt
      if(present(sckt)) call c%set_connection(sckt)
   end function new_MockClientThread
Call graph
new_mockclientthread calls set_connection
set_connection calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mockclientthread calls new_mockclientthread