newVerticalData – MAPL
newVerticalData Function
85 statements
Source File
private function newVerticalData(levels, vcoord, vscale, vunit, positive, long_name, standard_name, force_no_regrid, rc) result(vData)
Arguments
Type Intent Optional Attributes Name
real, intent(in), optional, pointer :: levels(:)
character(len=*), intent(in), optional :: vcoord
real, intent(in), optional :: vscale
character(len=*), intent(in), optional :: vunit
character(len=*), intent(in), optional :: positive
character(len=*), intent(in), optional :: long_name
character(len=*), intent(in), optional :: standard_name
logical, intent(in), optional :: force_no_regrid
integer, intent(out), optional :: rc
Return Value type(verticalData)
Calls
Called by
Contents
Source Code
newVerticalData
Source Code
     function newVerticalData(levels,vcoord,vscale,vunit,positive,long_name,standard_name,force_no_regrid,rc) result(vdata)
        type(VerticalData) :: vData
        real, pointer, intent(in), optional :: levels(:)
        real, intent(in), optional :: vscale
        character(len=*), optional, intent(in) :: vcoord
        character(len=*), optional, intent(in) :: vunit
        character(len=*), optional, intent(in) :: positive
        character(len=*), optional, intent(in) :: long_name
        character(len=*), optional, intent(in) :: standard_name
        logical, optional, intent(in) :: force_no_regrid
        integer, optional, intent(Out) :: rc
        logical :: local_force_no_regrid
        if (present(positive)) then
           _ASSERT(trim(positive)=='up'.or.trim(positive)=='down',trim(positive)//" not allowed for positive argument")
           vdata%positive=trim(positive)
        else
           vdata%positive='down'
        end if
        if (present(long_name)) then
           vdata%long_name = long_name
        else
           vdata%long_name = 'vertical level'
        end if
        if (present(standard_name)) then
           vdata%standard_name = standard_name
        else
           vdata%standard_name = 'model_layers'
        end if
        if (present(vcoord)) then
           vdata%vcoord = vcoord
        else
           vdata%vcoord = 'eta'
        endif
        if (present(vunit)) then
           vdata%vunit=vunit
         else
           vdata%vunit="layer"
        end if
        if (present(force_no_regrid)) then
           local_force_no_regrid = force_no_regrid
        else
           local_force_no_regrid = .false.
        end if
        if (.not.present(levels)) then
           if (trim(vdata%positive)=='down') then
              vdata%regrid_type = VERTICAL_METHOD_NONE
           else
              vdata%regrid_type = VERTICAL_METHOD_FLIP
           end if
        else
           allocate(vData%levs,source=levels)
           if (local_force_no_regrid) then
              if (trim(vdata%positive)=='down') then
                 vdata%regrid_type = VERTICAL_METHOD_NONE
              else
                 vdata%regrid_type = VERTICAL_METHOD_FLIP
              end if
              _RETURN(_SUCCESS)
           end if
           allocate(vData%scaled_levels,source=levels)
           if (present(vscale)) then
              vdata%vscale=vscale
              vData%scaled_levels = vData%scaled_levels*vdata%vscale
           end if
           if (present(vcoord)) then
              allocate(vData%interp_levels(size(vData%levs)))
              vdata%regrid_type = VERTICAL_METHOD_ETA2LEV
              vdata%VVAR = adjustl(vcoord)
              vdata%Func = vdata%Vvar(1:3)
              if    (vdata%Func=='log') then
                 vdata%Vvar = adjustl(vdata%Vvar(index(vdata%Vvar,'(')+1:index(vdata%Vvar,')')-1))
                 vdata%interp_levels = log(vdata%scaled_levels)
              elseif(vdata%Func=='pow') then
                 read( vdata%Vvar(index(vdata%Vvar,',')+1:index(vdata%Vvar,')')-1) , *) vdata%pow
                 vdata%Vvar = adjustl(vdata%Vvar(index(vdata%Vvar,'(')+1:index(vdata%Vvar,',')-1))
                 vdata%interp_levels =  (vdata%levs*vdata%scaled_levels)**vdata%pow
              else
                 vdata%interp_levels = vdata%scaled_levels
              endif
           else
              vdata%regrid_type = VERTICAL_METHOD_SELECT
           end if
        end if
     end function newVerticalData
Call graph
newverticaldata calls mapl_assert, interp_levels, mapl_return, vvar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
verticaldata calls newverticaldata