next – MAPL
next Subroutine
29 statements
Source File
private recursive subroutine next(this)
Type Bound
MeterNodeIterator
Arguments
Type Intent Optional Attributes Name
class(MeterNodeIterator), intent(inout) :: this
Calls
Called by
Contents
Source Code
next
Source Code
   recursive subroutine next(this)
      class (MeterNodeIterator), intent(inout) :: this
      class (AbstractMeterNode), pointer :: current_child
      if (.not. associated(this%current)) return ! done
      if (.not. allocated(this%iterator_over_children)) then
         this%iterator_over_children = this%reference%children%begin()
         if (this%iterator_over_children /= this%reference%children%end()) then
            current_child => this%iterator_over_children%get()
            this%iterator_of_current_child = current_child%begin()
            this%current => this%iterator_of_current_child%get()
         else
            this%current => null()
         end if
      else
         call this%iterator_of_current_child%next()
         this%current => this%iterator_of_current_child%get()
         if (.not. associated(this%current)) then ! go to next child
            deallocate(this%iterator_of_current_child)
            call this%iterator_over_children%next()
            if (this%iterator_over_children == this%reference%children%end()) then ! done
               deallocate(this%iterator_over_children)
            else
               current_child => this%iterator_over_children%get()
               this%iterator_of_current_child = current_child%begin() ! always at least one node
               this%current => this%iterator_of_current_child%get()
            end if
         end if
      end if
   end subroutine next
Call graph
next calls begin
begin calls meternodeiterator
meternodeiterator calls new_meternodeiterator
accumulate calls next, accumulate, reset
get_exclusive calls next
get_num_nodes calls next, get_num_nodes
reset calls next, reset