nf_strerror – MAPL
nf_strerror Function
4 statements
Source File
function nf_strerror() result(status)
Arguments
None
Return Value character(len=80)
Called by
Contents
Source Code
nf_strerror
Source Code
function nf_strerror() result(status)
  character*80 :: status
  status=''
end function nf_strerror
Call graph
cfio_getvar calls nf_strerror
esmf_cfiosdfvarread3d_ calls cfio_getvar
esmf_cfiosdfvarread2d_ calls cfio_getvar
esmf_cfiosdfvarread calls esmf_cfiosdfvarread3d_, esmf_cfiosdfvarread2d_
esmf_cfiovarread3d_ calls esmf_cfiosdfvarread
esmf_cfiosdfvarreadt2d__ calls esmf_cfiosdfvarread
esmf_cfiovarread2d_ calls esmf_cfiosdfvarread
esmf_cfiosdfvarreadt3d__ calls esmf_cfiosdfvarread
esmf_cfiovarread1d_ calls esmf_cfiosdfvarread