normal_vect – MAPL
normal_vect Function
5 statements
Source File
private function normal_vect(vin) result(vout)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: vin(3)
Return Value real(kind=real64), (3)
Called by
Contents
Source Code
normal_vect
Source Code
 function normal_vect(vin) result(vout)
    real(real64), intent(in) :: vin(3)
    real(real64) :: vout(3)
    vout=vin/sqrt(vin(1)*vin(1)+vin(2)*vin(2)+vin(3)*vin(3))
 end function normal_vect
Call graph
lines_intersect calls normal_vect
point_in_polygon calls lines_intersect
get_points_in_spherical_domain calls point_in_polygon
mapl_gethorzijindex calls get_points_in_spherical_domain