OffsetTimeYear – MAPL
OffsetTimeYear Subroutine
35 statements
Source File
private subroutine OffsetTimeYear(inTime, yrOffset, outTime, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: inTime
integer :: yrOffset
type(ESMF_Time), intent(out) :: outTime
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
OffsetTimeYear
Source Code
     subroutine OffsetTimeYear(inTime,yrOffset,outTime,rc)
        type(ESMF_Time),            intent(in   ) :: inTime
        integer                                   :: yrOffset
        type(ESMF_Time),            intent(out  ) :: outTime
        integer, optional,          intent(out  ) :: rc
        __Iam__('OffsetTimeYear')
        integer(ESMF_KIND_I4)              :: iyr,imm,idd,ihr,imn,isc
        logical                            :: srcLeap, targLeap
        _UNUSED_DUMMY(Iam)
        call ESMF_TimeGet(inTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
        ! If the source year is a leap year but the new one isn't, modify to day 28
        iYr = iYr + yrOffset
        targLeap = ((imm.eq.2).and.(idd.eq.29))
        if (targLeap) then
           if (iyr.lt.1582) then
              srcLeap = .False.
           else if (modulo(iYr,4).ne.0) then
              srcLeap = .False.
           else if (modulo(iYr,100).ne.0) then
              srcLeap = .True.
           else if (modulo(iYr,400).ne.0) then
              srcLeap = .False.
           else
              srcLeap = .True.
           end if
        else
           srcLeap = .True.
        end if
        if (targLeap.and.(.not.srcLeap)) idd=28
        call ESMF_TimeSet(outTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
        _RETURN(ESMF_SUCCESS)
     end subroutine OffsetTimeYear
Call graph
offsettimeyear calls ESMF_TimeGet, ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
getbrackettimeonfile calls offsettimeyear
getbrackettimeonsinglefile calls offsettimeyear
updatebrackettime calls offsettimeyear, getbrackettimeonfile, getbrackettimeonsinglefile
run_ calls updatebrackettime