omp_driver – MAPL
omp_driver Subroutine
57 statements
Source File
private subroutine omp_driver(GC, import, export, clock, RC)
Uses
MAPL_OpenMP_Support
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: import
type(ESMF_State), intent(inout) :: export
type(ESMF_Clock), intent(inout) :: clock
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine omp_driver(GC, import, export, clock, RC)
      use MAPL_OpenMP_Support, only : get_current_thread,  get_num_threads
      type (ESMF_GridComp), intent(inout) :: GC     ! Gridded component
      type (ESMF_State),    intent(inout) :: import ! Import state
      type (ESMF_State),    intent(inout) :: export ! Export state
      type (ESMF_Clock),    intent(inout) :: clock  ! The clock
      integer, optional,    intent(  out) :: RC     ! Error code:
      type (MAPL_MetaComp), pointer :: MAPL
      integer :: thread
      type(ESMF_State) :: subimport
      type(ESMF_State) :: subexport
      integer :: status
      integer, allocatable :: statuses(:), user_statuses(:)
      integer :: num_threads
      character(len=ESMF_MAXSTR) :: Iam = "Run1"
      type(ESMF_GridComp) :: thread_gc
      integer :: userRC
      character(len=ESMF_MAXSTR) :: comp_name
      integer :: phase
      call ESMF_GridCompGet (GC, NAME=comp_name, currentPhase=phase, _RC)
      call MAPL_GetObjectFromGC (GC, MAPL, _RC)
      if(MAPL%is_threading_active()) then
         call ESMF_GridCompRun (GC, &
              importState=import, &
              exportState=export, &
              clock=CLOCK, PHASE=phase, &
              userRC=userRC, _RC )
         _VERIFY(userRC)
      else
         !call start_global_time_profiler('activate_threads')
         num_threads = get_num_threads()
         call MAPL%activate_threading(num_threads, _RC)
         !call stop_global_time_profiler('activate_threads')
         !call start_global_time_profiler('parallel')
         allocate(statuses(num_threads), __STAT__)
         allocate(user_statuses(num_threads), __STAT__)
         statuses=0
         user_statuses=0
         !$omp parallel default(none), &
         !$omp& private(thread, subimport, subexport, thread_gc), &
         !$omp& shared(gc, statuses, user_statuses, clock, PHASE, MAPL)
         thread = get_current_thread()
         subimport = MAPL%get_import_state()
         subexport = MAPL%get_export_state()
         thread_gc = MAPL%get_gridcomp()
         call ESMF_GridCompRun (thread_gc, &
              importState=subimport, &
              exportState=subexport, &
              clock=CLOCK, PHASE=phase, &
              userRC=user_statuses(thread+1), rc=statuses(thread+1) )
         !$omp end parallel
         !call stop_global_time_profiler('parallel')
         if (any(user_statuses /= ESMF_SUCCESS)) then
            _FAIL('some thread failed for user_statuses')
         end if
         if (any(statuses /= ESMF_SUCCESS)) then
            _FAIL('some thread failed')
         end if
         deallocate(statuses, __STAT__)
         deallocate(user_statuses, __STAT__)
         !call start_global_time_profiler('deactivate_threads')
         call MAPL%deactivate_threading(_RC)
         !call stop_global_time_profiler('deactivate_threads')
      end if
      !call stop_global_time_profiler('run1()')
      RETURN_(ESMF_SUCCESS)
   end subroutine omp_driver
Call graph
omp_driver calls ESMF_GridCompGet, ESMF_GridCompRun, mapl_assert, mapl_getobjectfromgc, mapl_rtrn, activate_threading, deactivate_threading, get_current_thread, get_export_state, get_gridcomp, get_import_state, get_num_threads, is_threading_active, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_getobjectfromgc calls mapl_internalstateget
activate_threading calls mapl_assert, mapl_verify, activate_threading, get_child, create_subobjects, get_num_children, mapl_return
deactivate_threading calls mapl_assert, deactivate_threading, get_child, get_num_children, mapl_return
get_export_state calls get_current_thread, is_threading_active
get_gridcomp calls get_current_thread, is_threading_active
get_import_state calls get_current_thread, is_threading_active
mapl_verify calls mapl_throw_exception
mapl_genericwrapper calls omp_driver