open – MAPL
open Subroutine
41 statements
Source File
private subroutine open(this, file, mode, unusable, comm, info, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
character(len=*), intent(in) :: file
integer, intent(in) :: mode
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: comm
integer, intent(in), optional :: info
integer, intent(out), optional :: rc
Calls
Contents
Source Code
open
Source Code
   subroutine open(this, file, mode, unusable, comm, info, rc)
      class (NetCDF4_FileFormatter), intent(inout) :: this
      character(len=*), intent(in) :: file
      integer, intent(in) :: mode
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(in) :: comm
      integer, optional, intent(in) :: info
      integer, optional, intent(out) :: rc
      integer :: omode
      integer :: status
      select case (mode)
      case (pFIO_READ)
         omode = NF90_NOWRITE
      case (pFIO_WRITE)
         omode = NF90_WRITE
      case default
         _FAIL("read or write mode")
      end select
      if (present(comm)) then
         this%comm = comm
         this%parallel=.true.
      end if
      if (present(info)) then
         this%info = info
      else
         this%info = MPI_INFO_NULL
      end if
      !$omp critical
      if (this%parallel) then
         status = nf90_open(file, IOR(omode, NF90_MPIIO), comm=this%comm, info=this%info, ncid=this%ncid)
      else
         status = nf90_open(file, IOR(omode, NF90_SHARE), this%ncid)
      end if
      if (status /= nf90_noerr) then
         write(error_unit, fmt='("nf90_open: returned error code (", I0,") opening ", A, " [", A,"]")') &
               status,trim(file),trim(nf90_strerror(status))
      end if
      !$omp end critical
      _VERIFY(status)
      this%origin_file = file
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine open
Call graph
open calls mapl_assert, nf90_open, nf90_strerror, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize