OperatorIndex – MAPL
OperatorIndex Function
12 statements
Source File
private function OperatorIndex(c) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: c
Return Value integer
Called by
Source Code
  FUNCTION OperatorIndex (c) RESULT (n)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Return operator index
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    CHARACTER (LEN=1), INTENT(in) :: c
    INTEGER                       :: n,j
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    n = 0
    DO j=cAdd,cPow
       IF (c == Ops(j)) THEN
          n = j
          EXIT
       END IF
    END DO
  END FUNCTION OperatorIndex
Call graph
compilesubstr calls operatorindex, compilesubstr
compile calls compilesubstr
parsef calls compile
mapl_stateeval calls parsef