opposite – MAPL
opposite Function
4 statements
Source File
private function opposite(dir)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dir
Return Value integer
Called by
Contents
Call graph
advpos calls opposite
rebalance calls opposite, rot
rot calls opposite
erase_nonleaf calls advpos, rebalance
s_erase_multi calls rebalance, erase_nonleaf
s_insert calls rebalance