orb_halo – MAPL
orb_halo Subroutine
29 statements
Source File
private subroutine orb_halo(im, jm, mask, ihalo, jhalo, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: im
integer, intent(in) :: jm
integer, intent(inout) :: mask(im,jm)
integer, intent(in) :: ihalo(2)
integer, intent(in) :: jhalo(2)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
orb_halo
Source Code
      subroutine orb_halo(im,jm,mask,ihalo,jhalo,rc)
         integer,           intent(in   ) :: im
         integer,           intent(in   ) :: jm
         integer,           intent(inout) :: mask(im,jm)
         integer,           intent(in   ) :: ihalo(2)
         integer,           intent(in   ) :: jhalo(2)
         integer, optional, intent(out  ) :: rc
         character(len=ESMF_MAXSTR) :: Iam
         integer :: i, j, is, js
         integer :: tmask(im,jm)
         Iam = "orb_halo"
         tmask = 0
         do i = 1, im
            do j = 1, jm
               if (mask(i,j) == 1) then
                  do is = i-ihalo(1),i+ihalo(2)
                     if (is >= 1 .and. is <= im) then
                        do js = j-jhalo(1),j+jhalo(2)
                           if (js >= 1 .and. js <=jm) tmask(is,js) = 1
                        end do ! js loop
                     end if ! is in range
                  end do ! is loop
               end if ! (i,j) has mask = 1
            end do ! j loop
         end do ! i loop
         mask = tmask
         _RETURN(ESMF_SUCCESS)
      end subroutine orb_halo
Call graph
orb_halo calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
domasking_ calls orb_halo
domasking_cs calls orb_halo
run_ calls domasking_, domasking_cs