orb_mask_xy – MAPL
orb_mask_xy Subroutine
84 statements
Source File
private subroutine orb_mask_xy(mask, im, jm, x, y, tlons, tlats, nobs, jsegs, lb, ub, face, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: mask(im,jm)
integer, intent(in) :: im
integer, intent(in) :: jm
real, intent(in) :: x(im+1,jm+1)
real, intent(in) :: y(im+1,jm+1)
real(kind=dp) :: tlons(nobs)
real(kind=dp) :: tlats(nobs)
integer, intent(in) :: nobs
integer, intent(in) :: jsegs
real, intent(in) :: lb
real, intent(in) :: ub
integer, intent(in) :: face
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
orb_mask_xy
Source Code
      subroutine orb_mask_xy(mask,im,jm,x,y,tlons,tlats,nobs,jsegs,lb,ub,face,rc)
      implicit NONE
      INTEGER, PARAMETER :: dp=SELECTED_REAL_KIND(15,307)
      integer, intent(in) :: im, jm, nobs, jsegs
      real, intent(in) :: x(im+1,jm+1)
      real, intent(in) :: y(im+1,jm+1)
      real, intent(in) :: lb,ub
      integer, intent(in) :: face
      integer, optional, intent(out) :: rc
      real, pointer  :: ex(:), ey(:)
      real(dp) :: tlons(nobs), tlats(nobs)
      real(dp) :: beta
      integer, intent(out) :: mask(im,jm)
      real :: x_loc, y_loc
      integer i, j, m, n, nfail, inbox, imp1, jmp1, face_pnt
      integer im_1d, jm_1d, itmp
      logical switch
      real :: wcorner_x(4),wcorner_y(4) ! corners of world for this proc
      real :: lat,lon
!          _Iam_('orb_mask_xy')
      if (present(rc)) then
         rc = ESMF_SUCCESS
      end if
      switch = .false.
      if ( abs(x(1,1)-x(2,1)) < abs(x(1,1)-x(1,2)) ) switch = .true.
      if (.not.switch) then
        allocate(ex(im+1),ey(jm+1))
        im_1d = im+1
        jm_1d = jm+1
        imp1 = im+1
        jmp1 = jm+1
      endif
      if (switch) then
       allocate(ex(jm+1),ey(im+1))
       im_1d = jm+1
       jm_1d = im+1
       imp1 = im+1
       jmp1 = jm+1
      end if
      call flatten_xy(x,y,ex,ey,imp1,jmp1,im_1d,jm_1d,switch)
      nfail = 0
!     loop over each point
!     first define corners of the world
      wcorner_x(1)=minval(ex)
      wcorner_x(4)=minval(ex)
      wcorner_x(2)=maxval(ex)
      wcorner_x(3)=maxval(ex)
      wcorner_y(1)=minval(ey)
      wcorner_y(4)=maxval(ey)
      wcorner_y(2)=minval(ey)
      wcorner_y(3)=maxval(ey)
      do n = 2, nobs
        do m = 1, jsegs ! interpolate track along orbit for better resoluation between points
         beta = (m - 1.0 ) / ( jsegs - 1.0 )
         if ( abs(tlons(n)-tlons(n-1))<180. ) then
          lon = (1.0-beta) * tlons(n-1) + beta * tlons(n)
         else if ( tlons(n) > tlons(n-1) ) then
          lon = (1.0-beta) * tlons(n-1) + beta * (tlons(n)-360.)
         else
          lon = (1.0-beta) * (tlons(n-1)-360.) + beta * tlons(n)
         end if
         if (lon < lb) lon=lon+360.
         if (lon > ub) lon=lon-360.
         lat = (1.0-beta) * tlats(n-1) + beta * tlats(n)
!        check if lat and lon is in the piece of world on this processor
         lat = lat * MAPL_PI/180.0
         lon = lon * MAPL_PI/180.0
         call check_face_pnt(LON,LAT,face_pnt)
         if (face_pnt == face) then
          call cube_xy_point(x_loc,y_loc,LAT,LON,face_pnt)
          inbox = pnt_in_rect(x_loc,y_loc,wcorner_x,wcorner_y)
          ! if we found the point in the box
          if (inbox == 1) then
           i = ijsearch(ex,im_1d,x_loc,.false.)
           j = ijsearch(ey,jm_1d,y_loc,.false.)
           ! fill in mask for i,j
             if (switch) then
                itmp = i
                i = j
                j = itmp
             endif
             if ( i>0 .and. j>0 .and. i<=im .and. j<=jm) then
               mask(i,j)=1
             end if
          endif
         endif
       enddo
      enddo
      deallocate(ex,ey)
      end subroutine orb_mask_xy
Call graph
orb_mask_xy calls flatten_xy, pnt_in_rect, ijsearch, check_face_pnt, cube_xy_point
domasking_cs calls orb_mask_xy
run_ calls domasking_cs