orb_edges_1d – MAPL
orb_edges_1d Subroutine
10 statements
Source File
private subroutine orb_edges_1d(ecoords, coords, idim)
Arguments
Type Intent Optional Attributes Name
real, intent(out) :: ecoords(idim+1)
real, intent(in) :: coords(idim)
integer, intent(in) :: idim
Called by
Contents
Source Code
orb_edges_1d
Source Code
      subroutine orb_edges_1d(ecoords,coords,idim)
      implicit NONE
      integer, intent(in) :: idim
      real, intent(in)  :: coords(idim)
      real, intent(out) :: ecoords(idim+1)
      ecoords(1)  = coords(1) - 0.5 * ( coords(2) - coords(1) )
      ecoords(2:idim) = 0.5 * ( coords(1:idim-1)+coords(2:idim) )
      ecoords(idim+1) = coords(idim) + 0.5 * (coords(idim) - coords(idim-1))
      return
      end subroutine orb_edges_1d
Call graph
orb_mask_lonlat calls orb_edges_1d
orb_swath_mask_lonlat calls orb_edges_1d
domasking_ calls orb_mask_lonlat, orb_swath_mask_lonlat
run_ calls domasking_