orb_swath_mask_lonlat – MAPL
orb_swath_mask_lonlat Subroutine
126 statements
Source File
private subroutine orb_swath_mask_lonlat(mask, im, jm, lons, lats, slons, slats, nobs, isegs, jsegs, lb, ub)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: mask(im,jm)
integer, intent(in) :: im
integer, intent(in) :: jm
real, intent(in) :: lons(im,jm)
real, intent(in) :: lats(im,jm)
real(kind=dp) :: slons(3,nobs)
real(kind=dp) :: slats(3,nobs)
integer, intent(in) :: nobs
integer, intent(in) :: isegs
integer, intent(in) :: jsegs
real, intent(in) :: lb
real, intent(in) :: ub
Calls
Called by
Contents
Source Code
orb_swath_mask_lonlat
Source Code
      subroutine orb_swath_mask_lonlat(mask,im,jm,lons,lats,slons,slats,nobs,isegs,jsegs,lb,ub)
      implicit NONE
      INTEGER, PARAMETER :: dp=SELECTED_REAL_KIND(15,307)
      integer, intent(in) :: im, jm, nobs, isegs, jsegs
      real, intent(in) :: lons(im,jm)
      real, intent(in) :: lats(im,jm)
      real, intent(in) :: lb,ub
      real :: lons_1d(im),lats_1d(jm)
      real :: elons(im+1), elats(jm+1)
      real(dp) :: slons(3,nobs), slats(3,nobs)
      real(dp) :: alpha, beta, lon1, lon2, lat1, lat2
      integer, intent(out) :: mask(im,jm)
      integer i, j, k, m, n, nfail, imp1, jmp1, inbox
      real :: wcorner_lat(4),wcorner_lon(4)
      real :: lat,lon
      real :: sdnom1,sdnom2,eplonl1,eplonl2,eplonr1,eplonr2
      real :: eplatl1,eplatl2,eplatr1,eplatr2
      real :: sp1,sp2
      real :: sdnom,eplon1,eplon2,eplat1,eplat2
      real :: latf
!     Build edge coords
!     -----------------
      call flatten_latlon(lats,lons,lats_1d,lons_1d,im,jm)
      call orb_edges_1d(elons,lons_1d,im)
      call orb_edges_1d(elats,lats_1d,jm)
      imp1=im+1
      jmp1=jm+1
      nfail = 0
!     first define corners of the world
      wcorner_lat(1)=elats(1)
      wcorner_lat(4)=elats(jmp1)
      wcorner_lat(2)=elats(1)
      wcorner_lat(3)=elats(jmp1)
      wcorner_lon(1)=elons(1)
      wcorner_lon(4)=elons(1)
      wcorner_lon(2)=elons(imp1)
      wcorner_lon(3)=elons(imp1)
      do k = 1, isegs   ! cros-track
         alpha = (k - 1.0 ) / ( isegs - 1.0 )
         do n = 2, nobs
            if (abs(slons(1,n-1)-slons(3,n-1)) < 180.) then
             lon1 = (1.0-alpha) * slons(1,n-1) + alpha * slons(3,n-1)
             eplonl1 = slons(1,n-1)
             eplonr1 = slons(3,n-1)
            else if (slons(1,n-1) > slons(3,n-1)) then
             lon1 = (1.0-alpha) * slons(1,n-1) + alpha * (slons(3,n-1)+360.)
             eplonl1 = slons(1,n-1)
             eplonr1 = slons(3,n-1)+360.
            else
             lon1 = (1.0-alpha) * (slons(1,n-1)+360.) + alpha * slons(3,n-1)
             eplonl1 = slons(1,n-1)+360.
             eplonr1 = slons(3,n-1)
            endif
            if (abs(slons(1,n)-slons(3,n)) < 180.) then
             lon2 = (1.0-alpha) * slons(1,n) + alpha * slons(3,n)
             eplonl2 = slons(1,n)
             eplonr2 = slons(3,n)
            else if (slons(1,n) > slons(3,n)) then
             lon2 = (1.0-alpha) * slons(1,n) + alpha * (slons(3,n)+360.)
             eplonl2 = slons(1,n)
             eplonr2 = slons(3,n)+360.
            else
             lon2 = (1.0-alpha) * (slons(1,n)+360.) + alpha * slons(3,n)
             eplonl2 = slons(1,n)+360.
             eplonr2 = slons(3,n)
            endif
            ! interpolate along great circle unless endpoints of interpolation have same lon
            associate(d2r => MAPL_DEGREES_TO_RADIANS_R8, r2d => MAPL_RADIANS_TO_DEGREES)
             eplatl1 = slats(1,n-1)
             eplatr1 = slats(3,n-1)
             eplatl2 = slats(1,n)
             eplatr2 = slats(3,n)
             sdnom1 = sin((eplonl1-eplonr1)*d2r)
             sdnom2 = sin((eplonl2-eplonr2)*d2r)
             if (abs(sdnom1) /= 0.) then
              sp1 = sin((lon1-eplonr1)*d2r)/sdnom1
              sp2 = sin((lon1-eplonl1)*d2r)/sdnom1
              lat1 = atan(tan(eplatl1*d2r)*sp1 - tan(eplatr1*d2r)*sp2)
              lat1 = lat1*r2d
             else
              lat1 = (1.0-alpha) * slats(1,n-1) + alpha * slats(3,n-1)
             endif
             if (abs(sdnom2) /= 0.) then
              sp1 = sin((lon2-eplonr2)*d2r)/sdnom2
              sp2 = sin((lon2-eplonl2)*d2r)/sdnom2
              lat2 = atan(tan(eplatl2*d2r)*sp1 - tan(eplatr2*d2r)*sp2)
              lat2 = lat2*r2d
             else
              lat2 = (1.0-alpha) * slats(1,n) + alpha * slats(3,n)
             endif
             do m = 1, jsegs ! along track refinement
                beta = (m - 1.0 ) / ( jsegs - 1.0 )
                if (abs(lon2-lon1) < 180.) then
                 lon = (1.0-beta) * lon1 + beta * lon2
                 eplon1=lon1
                 eplon2=lon2
                else if (lon2 > lon1) then
                 lon = (1.0-beta) * (lon1+360.) + beta * lon2
                 eplon1=lon1+360.
                 eplon2=lon2
                else
                 lon = (1.0-beta) * lon1 + beta * (lon2+360.)
                 eplon1=lon1
                 eplon2=lon2+360.
                endif
                eplat1=lat1
                eplat2=lat2
                sdnom=sin((eplon1-eplon2)*d2r)
                if (abs(sdnom) /= 0. ) then
                 sp1=sin((lon-eplon2)*d2r)/sdnom
                 sp2=sin((lon-eplon1)*d2r)/sdnom
                 latf = atan(tan(eplat1*d2r)*sp1-tan(eplat2*d2r)*sp2)
                 latf = latf*r2d
                 lat = latf
                else
                 lat = (1.0-beta) * lat1 + beta * lat2
                endif
                if (lon < lb) lon=lon+360.
                if (lon > ub) lon=lon-360.
                inbox = pnt_in_rect(lat,lon,wcorner_lat,wcorner_lon)
                if (inbox == 1) then
                 i = ijsearch(elons,im+1,lon,.false.)
                 j = ijsearch(elats,jm+1,lat,.false.)
                 if ( i>0 .and. i<=im .and. j>0 .and. j<=jm ) mask(i,j) = 1
                end if
             end do ! msegs
            end associate
         end do    ! nobs
      end do       ! ksegs
      end subroutine orb_swath_mask_lonlat
Call graph
orb_swath_mask_lonlat calls flatten_latlon, ijsearch, orb_edges_1d, pnt_in_rect
domasking_ calls orb_swath_mask_lonlat
run_ calls domasking_