orb_swath_mask_xy – MAPL
orb_swath_mask_xy Subroutine
155 statements
Source File
private subroutine orb_swath_mask_xy(mask, im, jm, x, y, slons, slats, nobs, isegs, jsegs, lb, ub, face)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: mask(im,jm)
integer, intent(in) :: im
integer, intent(in) :: jm
real, intent(in) :: x(im+1,jm+1)
real, intent(in) :: y(im+1,jm+1)
real(kind=dp) :: slons(3,nobs)
real(kind=dp) :: slats(3,nobs)
integer, intent(in) :: nobs
integer, intent(in) :: isegs
integer, intent(in) :: jsegs
real, intent(in) :: lb
real, intent(in) :: ub
integer, intent(in) :: face
Calls
Called by
Contents
Source Code
orb_swath_mask_xy
Source Code
      subroutine orb_swath_mask_xy(mask,im,jm,x,y,slons,slats,nobs,isegs,jsegs,lb,ub,face)
      implicit NONE
      INTEGER, PARAMETER :: dp=SELECTED_REAL_KIND(15,307)
      integer, intent(in) :: im, jm, nobs, isegs, jsegs
      real, intent(in) :: x(im+1,jm+1)
      real, intent(in) :: y(im+1,jm+1)
      real, intent(in) :: lb,ub
      integer, intent(in) :: face
      real, pointer :: ex(:), ey(:)
      real(dp) :: slons(3,nobs), slats(3,nobs)
      real(dp) :: alpha, beta, lon1, lon2, lat1, lat2
      integer, intent(out) :: mask(im,jm)
      real :: x_loc, y_loc
      integer :: i, j, k, m, n, imp1, jmp1, inbox, itmp
      integer :: im_1d, jm_1d
      real :: wcorner_x(4),wcorner_y(4)
      real :: lat,lon
      real :: sdnom1,sdnom2,eplonl1,eplonl2,eplonr1,eplonr2
      real :: eplatl1,eplatl2,eplatr1,eplatr2
      real :: sp1,sp2
      real :: sdnom,eplon1,eplon2,eplat1,eplat2
      real :: latf
      integer :: face_pnt
      logical :: switch
!     find indices have constant values of coordinate
      switch = .false.
      if ( abs(x(1,1)-x(2,1)) < abs(x(1,1)-x(1,2)) ) switch = .true.
      if (.not.switch) then
         allocate(ex(im+1),ey(jm+1))
         im_1d = im+1
         jm_1d = jm+1
         imp1=im+1
         jmp1=jm+1
      endif
      if (switch) then
         allocate(ex(jm+1),ey(im+1))
         im_1d = jm+1
         jm_1d = im+1
         imp1=im+1
         jmp1=jm+1
      end if
      call flatten_xy(x,y,ex,ey,imp1,jmp1,im_1d,jm_1d,switch)
!     first define corners of the world
      wcorner_x(1)=minval(ex)
      wcorner_x(4)=minval(ex)
      wcorner_x(2)=maxval(ex)
      wcorner_x(3)=maxval(ex)
      wcorner_y(1)=minval(ey)
      wcorner_y(4)=maxval(ey)
      wcorner_y(2)=minval(ey)
      wcorner_y(3)=maxval(ey)
      do k = 1, isegs   ! cros-track
         alpha = (k - 1.0 ) / ( isegs - 1.0 )
         do n = 2, nobs
            if (abs(slons(1,n-1)-slons(3,n-1)) < 180.) then
             lon1 = (1.0-alpha) * slons(1,n-1) + alpha * slons(3,n-1)
             eplonl1 = slons(1,n-1)
             eplonr1 = slons(3,n-1)
            else if (slons(1,n-1) > slons(3,n-1)) then
             lon1 = (1.0-alpha) * slons(1,n-1) + alpha * (slons(3,n-1)+360.)
             eplonl1 = slons(1,n-1)
             eplonr1 = slons(3,n-1)+360.
            else
             lon1 = (1.0-alpha) * (slons(1,n-1)+360.) + alpha * slons(3,n-1)
             eplonl1 = slons(1,n-1)+360.
             eplonr1 = slons(3,n-1)
            endif
            if (abs(slons(1,n)-slons(3,n)) < 180.) then
             lon2 = (1.0-alpha) * slons(1,n) + alpha * slons(3,n)
             eplonl2 = slons(1,n)
             eplonr2 = slons(3,n)
            else if (slons(1,n) > slons(3,n)) then
             lon2 = (1.0-alpha) * slons(1,n) + alpha * (slons(3,n)+360.)
             eplonl2 = slons(1,n)
             eplonr2 = slons(3,n)+360.
            else
             lon2 = (1.0-alpha) * (slons(1,n)+360.) + alpha * slons(3,n)
             eplonl2 = slons(1,n)+360.
             eplonr2 = slons(3,n)
            endif
            ! interpolate along great circle unless endpoints of interpolation have same lon
            associate(d2r => MAPL_DEGREES_TO_RADIANS_R8, r2d => MAPL_RADIANS_TO_DEGREES)
             eplatl1 = slats(1,n-1)
             eplatr1 = slats(3,n-1)
             eplatl2 = slats(1,n)
             eplatr2 = slats(3,n)
             sdnom1 = sin((eplonl1-eplonr1)*d2r)
             sdnom2 = sin((eplonl2-eplonr2)*d2r)
             if (abs(sdnom1) /= 0.) then
              sp1 = sin((lon1-eplonr1)*d2r)/sdnom1
              sp2 = sin((lon1-eplonl1)*d2r)/sdnom1
              lat1 = atan(tan(eplatl1*d2r)*sp1 - tan(eplatr1*d2r)*sp2)
              lat1 = lat1*r2d
             else
              lat1 = (1.0-alpha) * slats(1,n-1) + alpha * slats(3,n-1)
             endif
             if (abs(sdnom2) /= 0.) then
              sp1 = sin((lon2-eplonr2)*d2r)/sdnom2
              sp2 = sin((lon2-eplonl2)*d2r)/sdnom2
              lat2 = atan(tan(eplatl2*d2r)*sp1 - tan(eplatr2*d2r)*sp2)
              lat2 = lat2*r2d
             else
              lat2 = (1.0-alpha) * slats(1,n) + alpha * slats(3,n)
             endif
             do m = 1, jsegs ! along track refinement
                beta = (m - 1.0 ) / ( jsegs - 1.0 )
                if (abs(lon2-lon1) < 180.) then
                 lon = (1.0-beta) * lon1 + beta * lon2
                 eplon1=lon1
                 eplon2=lon2
                else if (lon2 > lon1) then
                 lon = (1.0-beta) * (lon1+360.) + beta * lon2
                 eplon1=lon1+360.
                 eplon2=lon2
                else
                 lon = (1.0-beta) * lon1 + beta * (lon2+360.)
                 eplon1=lon1
                 eplon2=lon2+360.
                endif
                eplat1=lat1
                eplat2=lat2
                sdnom=sin((eplon1-eplon2)*d2r)
                if (abs(sdnom) /= 0. ) then
                 sp1=sin((lon-eplon2)*d2r)/sdnom
                 sp2=sin((lon-eplon1)*d2r)/sdnom
                 latf = atan(tan(eplat1*d2r)*sp1-tan(eplat2*d2r)*sp2)
                 latf = latf*r2d
                 lat = latf
                else
                 lat = (1.0-beta) * lat1 + beta * lat2
                endif
                if (lon < lb) lon=lon+360.
                if (lon > ub) lon=lon-360.
                lat = lat * MAPL_PI/180.0
                lon = lon * MAPL_PI/180.0
                call check_face_pnt(LON,LAT,face_pnt)
                if (face_pnt == face) then
                 call cube_xy_point(x_loc,y_loc,LAT,LON,face)
                 inbox = pnt_in_rect(x_loc,y_loc,wcorner_x,wcorner_y)
                 if (inbox == 1) then
                  i = ijsearch(ex,im_1d,x_loc,.false.)
                  j = ijsearch(ey,jm_1d,y_loc,.false.)
                  if (switch) then
                     itmp = i
                     i = j
                     j = itmp
                  endif
                  if ( i>0 .and. j>0 .and. i<=im .and. j<=jm) then
                    mask(i,j)=1
                  end if
                 end if
                endif
             end do ! msegs
            end associate
         end do    ! nobs
      end do       ! ksegs
      deallocate(ex,ey)
      end subroutine orb_swath_mask_xy
Call graph
orb_swath_mask_xy calls flatten_xy, cube_xy_point, ijsearch, check_face_pnt, pnt_in_rect
domasking_cs calls orb_swath_mask_xy
run_ calls domasking_cs