Orbits_Track2 – MAPL
Orbits_Track2 Subroutine
13 statements
Source File
private subroutine Orbits_Track2(iSat, Satcoef_vec, Normcoef_vec)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iSat
real(kind=dp), intent(out), dimension(1:Num_coef) :: Satcoef_vec
real(kind=dp), intent(out), dimension(1:Num_normcoef) :: Normcoef_vec
Called by
Contents
Source Code
Orbits_Track2
Source Code
SUBROUTINE Orbits_Track2(iSat, Satcoef_vec, Normcoef_vec)
    ! See interface
    IMPLICIT NONE
      integer, intent(in) :: iSat ! this is the sat number ex: Aqua=1
      real(dp), intent(out), dimension(1:Num_coef) :: Satcoef_vec
      real(dp), intent(out), dimension(1:Num_normcoef) :: Normcoef_vec
      integer                               :: start_ind, end_ind
      integer                               :: Normcoef_ind
!     ...................................
      ! Num_sat, Num_coef needs to be defined at the begining of the module
      ! Num_coef is 9 for each sat...
      ! Also Norm factor coef. need to be retrived.
      ! Here locations of these vectors are calculated
!     ...................................
        start_ind = (iSat - 1) * Num_coef + 1 !CALL calc_ind
        end_ind  = start_ind +  (Num_coef-1)
        Satcoef_vec(1:9) = Coefs(start_ind:end_ind) ! x,y,z
!       % ________________Mult by Norm fator_________________________
        !Normcoef_ind = (iSat-1)*Num_sat+1
        Normcoef_ind = iSat*Num_normcoef-(Num_normcoef-1)
!         print*, Normcoef_ind
!         print*, start_ind, end_ind
        Normcoef_vec = (/Norm_factor(Normcoef_ind),       &
                         Norm_factor(Normcoef_ind+1),     &
                         Norm_factor(Normcoef_ind+2)/)
END SUBROUTINE Orbits_Track2
Call graph
orbits_track0 calls orbits_track2
get_estimateeci calls orbits_track0
get_latlon calls get_estimateeci
orbits calls get_estimateeci
find_delta_t calls get_latlon
find_waypointslat calls get_latlon
redifine_timeint calls get_latlon