orbits – MAPL
orbits Subroutine
13 statements
Source File
private subroutine orbits(lat, lon, iSat, nymd, nhms)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: lat
real(kind=dp), intent(out) :: lon
integer, intent(in) :: iSat
integer, intent(in) :: nymd
integer, intent(in) :: nhms
Calls
Contents
Source Code
orbits
Source Code
SUBROUTINE orbits(lat, lon, iSat, nymd, nhms) ! for now time has to be after
       IMPLICIT  NONE
       INTEGER, INTENT(IN)   :: iSat
       INTEGER, INTENT(IN)   :: nymd, nhms
       REAL(dp), INTENT(OUT)     :: lat,lon
       REAL(dp), DIMENSION(3,1)  :: ECI_est, ECEF_est
       REAL(dp)                  :: alt
       REAL(dp)      :: fraction2day, ntime_day
       CALL get_time(iSat, nymd, nhms, fraction2day, ntime_day)
       CALL get_estimateECI(iSat, ntime_day, ECI_est)
       CALL ECI2ECEF(iSat,fraction2day, ECI_est, ECEF_est)
       CALL ECEF2LLA(ECEF_est(1,1), ECEF_est(2,1),   &
                     ECEF_est(3,1), lat, lon, alt)
END SUBROUTINE orbits
Call graph
orbits calls get_time, eci2ecef, ecef2lla, get_estimateeci
get_time calls ods_julian
get_estimateeci calls orbits_track0
orbits_track0 calls orbits_track1, orbits_track2
orbits_track1 calls satname2int