parsef – MAPL
parsef Subroutine
19 statements
Source File
private subroutine parsef(Comp, FuncStr, Var, Field, rc)
Arguments
Type Intent Optional Attributes Name
type(tComp), intent(inout) :: Comp
character(len=*), intent(in) :: FuncStr
character(len=*), intent(in), DIMENSION(:) :: Var
type(ESMF_Field), intent(inout) :: Field
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  SUBROUTINE parsef (Comp, FuncStr, Var, field, rc)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Parse ith function string FuncStr and compile it into bytecode
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    TYPE (tComp)                   , INTENT(inout) :: Comp              ! Bytecode
    CHARACTER (LEN=*),               INTENT(in   ) :: FuncStr   ! Function string
    CHARACTER (LEN=*), DIMENSION(:), INTENT(in   ) :: Var       ! Array with variable names
    TYPE(ESMF_Field)               , INTENT(inout) :: Field     ! resultant field, use to get rank, etc . . .
    INTEGER, OPTIONAL              , INTENT(out  ) :: rc
    CHARACTER(len=LEN(FuncStr))           :: Func
    integer :: status
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    CALL CheckSyntax (FuncStr,Var,_RC)
    Func = FuncStr                                           ! Local copy of function string
    CALL Replace ('**','^ ',Func)                            ! Exponent into 1-Char. format
    CALL RemoveSpaces (Func)                                 ! Condense function string
    CALL Compile (comp,Func,Var,field,_RC)             ! Compile into bytecode
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE parsef
Call graph
parsef calls checksyntax, compile, mapl_return, mapl_verify, removespaces, replace
checksyntax calls mapl_return, removespaces, replace, mapl_assert, checkundef, mathfunctionindex, parseerrmsg, realnum, variableindex
compile calls mapl_return, mapl_verify, ESMF_AttributeSet, fieldclone, compilesubstr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
fieldclone calls clone
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
checkundef calls lowcase
compilesubstr calls compilesubstr, mathfunctionindex, addcompiledbyte, completelyenclosed, isbinaryop, mathitemindex, operatorindex
get_error_message calls at, insert
mapl_throw_exception calls initialize
mathfunctionindex calls lowcase
mapl_stateeval calls parsef
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
initialize_ calls fillstate
run_ calls evaluate_derived_field, calcderivedfield, fillstate
run calls mapl_runexpression
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem