parse_heartbeat_timestring – MAPL
parse_heartbeat_timestring Subroutine
14 statements
Source File
private subroutine parse_heartbeat_timestring(timestring, is_heartbeat, multiplier, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: timestring
logical, intent(out) :: is_heartbeat
integer, intent(out) :: multiplier
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine parse_heartbeat_timestring(timestring, is_heartbeat, multiplier, rc)
      character(len=*), intent(in) :: timestring
      logical, intent(out) :: is_heartbeat
      integer, intent(out) :: multiplier
      character(len=:), allocatable :: found_string
      character(len=:), allocatable :: upper
      integer, optional, intent(out) :: rc
      integer :: status
      multiplier = 1
      upper = ESMF_UtilStringUpperCase(timestring, _RC)
      call split_on(upper, HEARTBEAT_STRING, found_string=found_string)
      is_heartbeat = len(found_string) > 0
      ! For now, multiplier is simply set to 1. In the future, as needed, the before_string
      ! and after_string arguments of split_on can be used to parse for a multiplier.
   end subroutine parse_heartbeat_timestring
Call graph
parse_heartbeat_timestring calls ESMF_UtilStringUpperCase, mapl_verify, split_on
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
create_from_parameters calls parse_heartbeat_timestring
fillin_derived calls create_from_parameters
fillin_primary calls create_from_parameters
test_compare_negative_string_to_negative_heartbeat calls create_from_parameters
test_compare_positive_string_to_positive_heartbeat calls create_from_parameters
test_create_from_parameters_heartbeat_negative calls create_from_parameters
test_create_from_parameters_heartbeat_negative_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive_explicit calls create_from_parameters
test_create_from_parameters_heartbeat_positive_negative calls create_from_parameters
test_create_from_parameters_string_negative calls create_from_parameters
test_create_from_parameters_string_positive calls create_from_parameters
test_get_adjusted_time calls create_from_parameters
initialize_ calls fillin_derived, fillin_primary