ParseTimeUnits – MAPL
ParseTimeUnits Subroutine
73 statements
Source File
public subroutine ParseTimeUnits(TimeUnits, year, month, day, hour, min, sec, rc)
ParseTimeUnits – Parse the COARDS time units string
This subroutine takes as input the COARDS metadata time units string and parses out the date included in the string. This date typically represents the first time in a COARDS HDF files.
History
2000.10.18 Lucchesi Initial coding.
2001.08.13 Lucchesi Modified to better parse time:units string (needed for lats4d support)
Arguments
Type Intent Optional Attributes Name
character(len=MAXCHR) :: TimeUnits
Units metadata string from the Time coord var
integer :: year
4-digit year
integer :: month
month
integer :: day
day
integer :: hour
hour
integer :: min
minute
integer :: sec
second
integer :: rc
return code 0 = no error -1 = problem parsing string
Called by
Contents
Source Code
ParseTimeUnits
Source Code
      subroutine ParseTimeUnits ( TimeUnits, year, month, day, hour, min, sec, rc )
!
! !USES:
!
      implicit none
!
! !INPUT PARAMETERS:
!
      character(len=MAXCHR) TimeUnits      !! Units metadata string from the Time coord var
!
! !OUTPUT PARAMETERS:
!
      integer        year               !! 4-digit year
      integer        month              !! month
      integer        day                !! day
      integer        hour               !! hour
      integer        min                !! minute
      integer        sec                !! second
      integer        rc                 !! return code
                                        !!  0 = no error
                                        !! -1 = problem parsing string
!
!-------------------------------------------------------------------------
      ! Local variables
      integer ypos(2), mpos(2), dpos(2), hpos(2), spos(2)
      integer strlen
      integer firstdash, lastdash
      integer firstcolon, lastcolon
      integer lastspace
      strlen = LEN_TRIM (TimeUnits)
      firstdash = index(TimeUnits, '-')
      lastdash  = index(TimeUnits, '-', BACK=.TRUE.)
      if (firstdash .LE. 0 .OR. lastdash .LE. 0) then
        rc = -1
        return
      endif
      ypos(2) = firstdash - 1
      mpos(1) = firstdash + 1
      ypos(1) = ypos(2) - 4
      mpos(2) = lastdash - 1
      dpos(1) = lastdash + 1
      dpos(2) = dpos(1) + 2
      read ( TimeUnits(ypos(1):ypos(2)), * ) year
      read ( TimeUnits(mpos(1):mpos(2)), * ) month
      read ( TimeUnits(dpos(1):dpos(2)), * ) day
      firstcolon = index(TimeUnits, ':')
      if (firstcolon .LE. 0) then
        ! If no colons, check for hour.
        ! Logic below assumes a null character or something else is after the hour
        ! if we do not find a null character add one so that it correctly parses time
        if (TimeUnits(strlen:strlen) /= char(0)) then
           TimeUnits = trim(TimeUnits)//char(0)
           strlen=len_trim(TimeUnits)
        endif
        lastspace = index(TRIM(TimeUnits), ' ', BACK=.TRUE.)
        if ((strlen-lastspace).eq.2 .or. (strlen-lastspace).eq.3) then
          hpos(1) = lastspace+1
          hpos(2) = strlen-1
          read (TimeUnits(hpos(1):hpos(2)), * ) hour
          min  = 0
          sec  = 0
        else
          print *, 'ParseTimeUnits: Assuming a starting time of 00z'
          hour = 0
          min  = 0
          sec  = 0
        endif
      else
        hpos(1) = firstcolon - 2
        hpos(2) = firstcolon - 1
        lastcolon =  index(TimeUnits, ':', BACK=.TRUE.)
        if ( lastcolon .EQ. firstcolon ) then
          mpos(1) = firstcolon + 1
          mpos(2) = firstcolon + 2
          read (TimeUnits(hpos(1):hpos(2)), * ) hour
          read (TimeUnits(mpos(1):mpos(2)), * ) min
          sec = 0
        else
          mpos(1) = firstcolon + 1
          mpos(2) = lastcolon - 1
          spos(1) = lastcolon + 1
          spos(2) = lastcolon + 2
          read (TimeUnits(hpos(1):hpos(2)), * ) hour
          read (TimeUnits(mpos(1):mpos(2)), * ) min
          read (TimeUnits(spos(1):spos(2)), * ) sec
        endif
      endif
      rc = 0
      return
      end subroutine ParseTimeUnits
Call graph
getbegdatetime calls parsetimeunits
getdatetimevec calls parsetimeunits
cfio_getvar calls getdatetimevec
cfio_sgetvar calls getdatetimevec
esmf_cfiosdffileopen calls getbegdatetime
esmf_cfiosdfvarreadt2d__ calls getbegdatetime
esmf_cfiosdfvarreadt3d__ calls getbegdatetime
gettimesonfile calls getdatetimevec
gettindex calls getdatetimevec
esmf_cfiosdfvarreadt calls esmf_cfiosdfvarreadt2d__, esmf_cfiosdfvarreadt3d__, esmf_cfiosdfvarreadt2d_, esmf_cfiosdfvarreadt3d_
esmf_cfiofileopen calls esmf_cfiosdffileopen
esmf_cfiosdfvarread1d_ calls cfio_sgetvar, esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls cfio_getvar, cfio_sgetvar, esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls cfio_getvar, esmf_cfiosdffileopen
esmf_cfiosdfvarreadt2d_ calls esmf_cfiosdfvarreadt2d__
esmf_cfiosdfvarreadt3d_ calls esmf_cfiosdfvarreadt3d__
mapl_cfioreadparallel_ calls gettindex
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
mapl_cfioreadparallel calls mapl_cfioreadparallel_
find calls esmf_cfiofileopen
mapl_cfioopenwrite calls esmf_cfiofileopen
mapl_cfioreadbundle calls esmf_cfiofileopen
test calls esmf_cfiofileopen