parse_formula_terms – MAPL
parse_formula_terms Subroutine
12 statements
Source File
private subroutine parse_formula_terms(formula_terms, ps, ak, bk, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: formula_terms
character(len=:), intent(out), allocatable :: ps
character(len=:), intent(out), allocatable :: ak
character(len=:), intent(out), allocatable :: bk
integer, intent(out), optional :: rc
Calls
Called by
Source Code
    subroutine parse_formula_terms(formula_terms, ps, ak, bk, rc)
       character(len=*), intent(in) :: formula_terms
       character(len=:), allocatable, intent(out) :: ps
       character(len=:), allocatable, intent(out) :: ak
       character(len=:), allocatable, intent(out) :: bk
       integer, intent(out), optional :: rc
       ps = find_term(formula_terms, "ps:")
       ak = find_term(formula_terms, "ap:")
       bk = find_term(formula_terms, "b:")
       _RETURN(_SUCCESS)
    end subroutine parse_formula_terms
Call graph
parse_formula_terms calls find_term, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
new_verticalcoordinate calls parse_formula_terms
verticalcoordinate calls new_verticalcoordinate