parse_timeunit_i4 – MAPL
parse_timeunit_i4 Subroutine
32 statements
Source File
public subroutine parse_timeunit_i4(tunit, n, t0, dt, rc)
Uses
ESMF
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: tunit
integer, intent(in) :: n
type(ESMF_Time), intent(out) :: t0
type(ESMF_TimeInterval), intent(out) :: dt
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine parse_timeunit_i4(tunit, n, t0, dt, rc)
    use ESMF
    implicit none
    character(len=*), intent(in) :: tunit
    integer, intent(in) :: n
    type(ESMF_Time), intent(out) :: t0
    type(ESMF_TimeInterval), intent(out) :: dt
    integer, optional, intent(out) :: rc
    integer :: status
    integer :: i
    character(len=ESMF_MAXSTR) :: s1, s2, s_time, s_unit
    character(len=1) :: c1
    integer :: y,m,d,hour,min,sec
    integer :: isec
    type(ESMF_Calendar) :: gregorianCalendar
    i=index(trim(tunit), 'since')
    s_time=trim(tunit(i+5:))
    s_unit=trim(tunit(1:i-1))
    read(s_time,*) s1, s2
    read(s1, '(i4,a1,i2,a1,i2)') y, c1, m, c1, d
    read(s2, '(i2,a1,i2,a1,i2)') hour, c1, min, c1, sec
    _ASSERT(trim(s_unit) == 'seconds', "s_unit /= 'seconds' is not handled")
    isec=n
    gregorianCalendar = ESMF_CalendarCreate(ESMF_CALKIND_GREGORIAN, name='Gregorian_obs', _RC)
    call ESMF_timeSet(t0, yy=y,mm=m,dd=m,h=hour,m=min,s=sec,&
         calendar=gregorianCalendar, _RC)
    call ESMF_timeintervalSet(dt, d=0, h=0, m=0, s=isec, _RC)
   _RETURN(_SUCCESS)
  end subroutine parse_timeunit_i4
Call graph
parse_timeunit_i4 calls ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_timeunit calls parse_timeunit_i4
time_esmf_2_nc_int calls parse_timeunit
time_nc_int_2_esmf calls parse_timeunit
convert_time_esmf2nc calls time_esmf_2_nc_int
convert_time_nc2esmf calls time_nc_int_2_esmf
create_grid calls time_esmf_2_nc_int
get_x_subset calls time_esmf_2_nc_int