parse_timezone_offset – MAPL
parse_timezone_offset Function
23 statements
Source File
public pure function parse_timezone_offset(offset, field_width) result(tzo)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: offset
integer, intent(in) :: field_width
Return Value integer
Calls
Called by
Contents
Source Code
parse_timezone_offset
Source Code
   pure function parse_timezone_offset(offset, field_width) result(tzo)
      character(len=*), intent(in) :: offset
      integer, intent(in) :: field_width
      integer :: offset_length
      integer :: tzo
      integer :: minutes
      integer :: hours
      offset_length = len_trim(offset)
      if(offset_length == field_width) then
         ! Offset with hours only
         hours = read_whole_number(offset)
         tzo = hours*MINUTES_PER_HOUR
      elseif (offset_length == 2*field_width) then
         ! Offset with hours and minutes
         hours = read_whole_number(offset(1:field_width))
         minutes = read_whole_number(offset(field_width+1:len(offset)))
         if(is_whole_number(hours) .and. is_whole_number(minutes)) then
            tzo = hours*MINUTES_PER_HOUR + minutes
         else
            tzo = INVALID
         end if
      else
         tzo = INVALID
      end if
   end function parse_timezone_offset
Call graph
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string
get_integer_digit_from_string calls get_integer_digit
parse_time calls parse_timezone_offset
test_parse_timezone_offset calls parse_timezone_offset
construct_iso8601time calls parse_time
test_parse_time calls parse_time
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time
construct_iso8601datetime calls iso8601time
convert_iso8601_to_integer_time calls iso8601time
test_iso8601datetime_getters calls iso8601time