parseTimes – MAPL
parseTimes Subroutine
24 statements
Source File
private subroutine parseTimes(this, rc)
Type Bound
ExtData_DriverGridComp
Arguments
Type Intent Optional Attributes Name
class(ExtData_DriverGridComp), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
parseTimes
Source Code
  subroutine parseTimes(this, rc)
    class(ExtData_DriverGridComp), intent(inout) :: this
    integer, intent(out), optional :: rc
    integer :: comp_YY, comp_MM, comp_DD, comp_H, comp_M, comp_S,columnCount,lineCount,i,ctime(2)
    integer :: status
    call ESMF_ConfigGetDim(this%config,lineCount,columnCount,label='RUN_TIMES::',rc=status)
    if (status==ESMF_SUCCESS) then
       allocate(this%times(lineCount))
       call ESMF_ConfigFindLabel(this%config,label='RUN_TIMES::',rc=status)
       _VERIFY(status)
       do i=1,lineCount
          call ESMF_ConfigNextLine(this%config,rc=status)
          _VERIFY(status)
          call ESMF_ConfigGetAttribute(this%config,ctime,rc=status)
          _VERIFY(status)
          call MAPL_UnpackDateTime(ctime,comp_YY,comp_MM,COMP_DD,COMP_H,COMP_M,COMP_S)
          call ESMF_TimeSet(this%times(i),yy=comp_yy,mm=comp_mm,dd=comp_dd,h=comp_h,m=comp_m,s=comp_s,rc=status)
          _VERIFY(status)
       enddo
    else
       _RETURN(ESMF_SUCCESS)
    end if
  end subroutine parseTimes
Call graph
parsetimes calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, ESMF_ConfigGetDim, ESMF_ConfigNextLine, ESMF_TimeSet, mapl_unpackdatetime, mapl_return, mapl_verify, times
mapl_unpackdatetime calls mapl_unpackdatetime
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
initialize_gc calls parsetimes