parse_date – MAPL
parse_date Function
19 statements
Source File
public pure function parse_date(datestring) result(fields)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: datestring
Return Value type(date_fields)
Calls
Called by
Contents
Source Code
parse_date
Source Code
   pure function parse_date(datestring) result(fields)
      character(len=*), intent(in) :: datestring
      type(date_fields) :: fields
      integer, parameter :: LENGTH = 8
      character, parameter :: DELIMITER = '-'
      integer, parameter :: YEAR_POSITION = 1
      integer, parameter :: MONTH_POSITION = 5
      integer, parameter :: DAY_POSITION = 7
      character(len=LENGTH) :: undelimited
      ! Eliminate delimiters so that there is one parsing block
      undelimited=undelimit(datestring, DELIMITER)
      if(len(undelimited) == LENGTH) then
         fields%year_ = read_whole_number(undelimited(YEAR_POSITION:MONTH_POSITION-1))
         fields%month_ = read_whole_number(undelimited(MONTH_POSITION:DAY_POSITION-1))
         fields%day_ = read_whole_number(undelimited(DAY_POSITION:LENGTH))
         fields%is_valid_ = is_valid_date(fields)
      else
         fields%is_valid_ = .FALSE.
      end if
   end function parse_date
Call graph
parse_date calls undelimit, read_whole_number, is_valid_date
read_whole_number calls read_whole_number_indexed
is_valid_date calls get_month_end, is_valid_year, is_between, is_valid_month
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
get_month_end calls get_month_ends
is_valid_year calls is_between
is_valid_month calls is_between
get_integer_digit_from_string calls get_integer_digit
get_month_ends calls is_leap_year
construct_iso8601date calls parse_date
test_parse_date calls parse_date
iso8601date calls construct_iso8601date
convert_iso8601_to_integer_date calls iso8601date
test_construct_iso8601date calls iso8601date
test_iso8601datetime_getters calls iso8601date
construct_iso8601datetime calls iso8601date
test_convert_iso8601_to_integer_date calls convert_iso8601_to_integer_date
iso8601datetime calls construct_iso8601datetime
test_construct_iso8601datetime calls construct_iso8601datetime