ParseErrMsg – MAPL
ParseErrMsg Subroutine
19 statements
Source File
private subroutine ParseErrMsg(j, FuncStr, ipos, Msg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
character(len=*), intent(in) :: FuncStr
integer, intent(inout), DIMENSION(:) :: ipos
character(len=*), intent(in), optional :: Msg
Called by
Source Code
  SUBROUTINE ParseErrMsg (j, FuncStr, ipos, Msg)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Print error message and terminate program
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    INTEGER,                     INTENT(in) :: j
    CHARACTER (LEN=*),           INTENT(in) :: FuncStr       ! Original function string
    INTEGER, DIMENSION(:),       INTENT(inout) :: ipos
    CHARACTER (LEN=*), OPTIONAL, INTENT(in) :: Msg
    INTEGER                                 :: k
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IF (PRESENT(Msg)) THEN
       WRITE(*,*) '*** Error in syntax of function string: '//Msg
    ELSE
       WRITE(*,*) '*** Error in syntax of function string:'
    ENDIF
    WRITE(*,*)
    WRITE(*,'(A)') ' '//FuncStr
    DO k=1,ipos(j)
       WRITE(*,'(A)',ADVANCE='NO') ' '                       ! Advance to the jth position
    END DO
    WRITE(*,'(A)') '?'
  END SUBROUTINE ParseErrMsg
Call graph
checksyntax calls parseerrmsg
parser_variables_in_expression calls parseerrmsg
get_mask_variables calls parser_variables_in_expression
get_variables_in_expression calls parser_variables_in_expression, get_mask_variables
initialize_ calls checksyntax, fillstate, get_extra_derived_items
mapl_setexpression calls checksyntax
mapl_stateeval calls checksyntax, parsef
parsef calls checksyntax
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
get_extra_derived_items calls get_variables_in_expression
initialize calls mapl_setexpression
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run calls mapl_runexpression
run_ calls fillstate, evaluate_derived_field, calcderivedfield