perr – MAPL
perr Subroutine
6 statements
Source File
private subroutine perr(name, msg, i)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: name
character(len=*) :: msg
integer :: i
Called by
Source Code
subroutine perr (name, msg, i)
character(len=*) :: name, msg
integer :: i
print *, trim(name)//':'//trim(msg), i
return
end subroutine perr
Call graph
gx_ calls perr
strtemplate_ calls gx_
esmf_cfiostrtemplate calls strtemplate_
esmf_cfiosdffilecreate calls strtemplate_
esmf_cfiosdffileopen calls strtemplate_
esmf_cfiosdfvarread1d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarwrite1d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite2d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite3d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfiofilecreate calls esmf_cfiosdffilecreate
esmf_cfiofileopen calls esmf_cfiosdffileopen