pfio_get_att_string – MAPL
pfio_get_att_string Function
20 statements
Source File
public function pfio_get_att_string(ncid, varid, name, string) result(status)
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in) :: ncid
integer(kind=C_INT), intent(in) :: varid
character(len=*), intent(in) :: name
character(len=:), intent(out), allocatable :: string
Return Value integer
Calls
Called by
Contents
Source Code
pfio_get_att_string
Source Code
   function pfio_get_att_string(ncid, varid, name, string) result(status)
      integer :: status
      integer(kind=C_INT), intent(in) :: ncid
      integer(kind=C_INT), intent(in) :: varid
      character(*), intent(in) :: name
      character(:), allocatable, intent(out) :: string
      integer :: name_len
      integer(kind=C_INT),target :: attlen
      character(kind=C_CHAR, len=:), target, allocatable :: c_name
      character(len=512) :: tmp_str
      ! C requires null termination
      name_len = len_trim(name)
      allocate(character(kind=C_CHAR,len=name_len+1) :: c_name)
      c_name(1:name_len) = name(1:name_len)
      c_name(name_len+1:name_len+1) = C_NULL_CHAR
      tmp_str = ''
      ! This c-call would fill tmp_str with the global attribute
      status = c_f_pfio_get_att_string(ncid, varid, c_name, tmp_str, attlen)
      allocate(character(len=attlen) :: string)
      string = trim(tmp_str)
      deallocate(c_name)
   end function pfio_get_att_string
Call graph
pfio_get_att_string calls c_f_pfio_get_att_string
get_attribute_from_group calls pfio_get_att_string
inq_attributes calls pfio_get_att_string
create_grid calls get_attribute_from_group, create_grid
read calls inq_attributes
initialize calls create_grid
reinitialize calls create_grid