pmaxmin2d_r8 – MAPL
pmaxmin2d_r8 Subroutine
16 statements
Source File
private subroutine pmaxmin2d_r8(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R8), intent(in) :: a(:,:)
real(kind=ESMF_KIND_R8), intent(out), optional :: pmin
real(kind=ESMF_KIND_R8), intent(out), optional :: pmax
real(kind=ESMF_KIND_R8), intent(in), optional :: fac
Calls
Called by
Contents
Source Code
pmaxmin2d_r8
Source Code
  subroutine pmaxmin2d_r8 ( qname, a, pmin, pmax, fac )
      implicit none
      character*(*),                intent(in)  :: qname        ! label to print
      real(ESMF_KIND_R8),           intent(in)  :: a(:,:)     ! input array
      real(ESMF_KIND_R8), optional, intent(in)  :: fac          ! multiplication factor
      real(ESMF_KIND_R8), optional, intent(out) :: pmax, pmin   ! min/max value
!                         ---
      real(ESMF_KIND_R4) :: pmin_r4, pmax_r4, fac_r4
      if ( present(fac) ) then
         fac_r4 = fac
      else
         fac_r4 = 1.0
      end if
      call pmaxmin2d_r4 ( qname, real(a,kind=ESMF_KIND_R4), pmin_r4, pmax_r4, fac_r4 )
      if ( present(pmin) ) pmin = pmin_r4
      if ( present(pmax) ) pmax = pmax_r4
   end subroutine pmaxmin2d_r8
Call graph
pmaxmin2d_r8 calls pmaxmin2d_r4
pmaxmin2d_r4 calls esmf_vmgetcurrent, mapl_commsallreducemax, mapl_am_i_root
mapl_commsallreducemax calls mapl_commsallreducemax_i4_0, mapl_commsallreducemax_r4_0, mapl_commsallreducemax_r4_1, mapl_commsallreducemax_i4_1, mapl_commsallreducemax_r8_0, mapl_commsallreducemax_r8_1, mapl_commsallreducemax_i4_2, mapl_commsallreducemax_r4_2, mapl_commsallreducemax_r8_2
mapl_am_i_root calls mapl_am_i_root_vm, mapl_am_i_root_layout
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_commsallreducemax_i4_0 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r4_0 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r4_1 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_i4_1 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r8_0 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r8_1 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_i4_2 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r4_2 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r8_2 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_maxmin calls pmaxmin2d_r8
mapl_simplebundleprint calls mapl_maxmin