pmaxmin3d_r4 – MAPL
pmaxmin3d_r4 Subroutine
11 statements
Source File
private subroutine pmaxmin3d_r4(qname, a, pmin, pmax, fac)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R4), intent(in) :: a(:,:,:)
real(kind=ESMF_KIND_R4), intent(out), optional :: pmin
real(kind=ESMF_KIND_R4), intent(out), optional :: pmax
real(kind=ESMF_KIND_R4), intent(in), optional :: fac
Calls
Called by
Source Code
  subroutine pmaxmin3d_r4 ( qname, a, pmin, pmax, fac )
      implicit none
      character(len=*),             intent(in)  :: qname        ! label to print
      real(ESMF_KIND_R4),           intent(in)  :: a(:,:,:)     ! input array
      real(ESMF_KIND_R4), optional, intent(in)  :: fac          ! multiplication factor
      real(ESMF_KIND_R4), optional, intent(out) :: pmax, pmin   ! min/max value
!                         ---
      integer im, jt
      im = size(a,1) * size(a,2)
      jt = size(a,3)
      call pmaxmin2d_r4 ( qname, reshape(a,(/ im, jt /)), pmin, pmax, fac )
    end subroutine pmaxmin3d_r4
Call graph
pmaxmin3d_r4 calls pmaxmin2d_r4
pmaxmin2d_r4 calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_am_i_root, mapl_commsallreducemax, mpi_reduce
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_commsallreducemax calls mapl_commsallreducemax_i4_0, mapl_commsallreducemax_i4_1, mapl_commsallreducemax_i4_2, mapl_commsallreducemax_r4_0, mapl_commsallreducemax_r4_1, mapl_commsallreducemax_r4_2, mapl_commsallreducemax_r8_0, mapl_commsallreducemax_r8_1, mapl_commsallreducemax_r8_2
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_commsallreducemax_i4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_i4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_i4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r4_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r4_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r4_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r8_0 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r8_1 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_commsallreducemax_r8_2 calls ESMF_VMGet, mpi_allreduce, mapl_return, mapl_verify
mapl_maxmin calls pmaxmin3d_r4, pmaxmin3d_r8
pmaxmin3d_r8 calls pmaxmin3d_r4
mapl_simplebundleprint calls mapl_maxmin