pmaxmin2d_r4 – MAPL
pmaxmin2d_r4 Subroutine
58 statements
Source File
private subroutine pmaxmin2d_r4(qname, a, pmin_, pmax_, fac_)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: qname
real(kind=ESMF_KIND_R4), intent(in) :: a(:,:)
real(kind=ESMF_KIND_R4), intent(out), optional :: pmin_
real(kind=ESMF_KIND_R4), intent(out), optional :: pmax_
real(kind=ESMF_KIND_R4), intent(in), optional :: fac_
Calls
Called by
Contents
Source Code
pmaxmin2d_r4
Source Code
    subroutine pmaxmin2d_r4 ( qname, a, pmin_, pmax_, fac_ )
      implicit none
      character*(*),                intent(in)  :: qname        ! label to print
      real(ESMF_KIND_R4),           intent(in)  :: a(:,:)       ! input array
      real(ESMF_KIND_R4), optional, intent(in)  :: fac_         ! multiplication factor
      real(ESMF_KIND_R4), optional, intent(out) :: pmax_, pmin_ ! min/max value
!                                           ---
      real(ESMF_KIND_R4) :: pmax, pmin, fac
      integer :: im, jt
      integer :: i, j, two=2
      real, allocatable :: qmin(:), qmax(:)
      real pm1(2)
      real pm_res(2)
      type(ESMF_VM) :: vm
      character(len=16) :: name
      integer :: status
      im = size(a,1)
      jt = size(a,2)
      allocate(qmin(jt),qmax(jt))
      if ( present(fac_) ) then
         fac = fac_
      else
         fac = 1.0
      end if
      call ESMF_VmGetCurrent(vm=vm, rc=status)
      do j=1,jt
         pmax = a(1,j)
         pmin = a(1,j)
         do i=2,im
            pmax = max(pmax, a(i,j))
            pmin = min(pmin, a(i,j))
         enddo
         qmax(j) = pmax
         qmin(j) = pmin
      enddo
!
! Now find max/min of amax/amin
!
      pmax = qmax(1)
      pmin = qmin(1)
      do j=2,jt
         pmax = max(pmax, qmax(j))
         pmin = min(pmin, qmin(j))
      enddo
      pm1(1) = pmax
      pm1(2) = -pmin
      call MAPL_CommsAllReduceMax(vm, sendbuf=pm1, recvbuf=pm_res, cnt=two, RC=status)
      pmax=pm_res(1)
      pmin=-pm_res(2)
      if ( present(pmax_) ) pmax_ = pmax
      if ( present(pmin_) ) pmin_ = pmin
      deallocate(qmax,qmin)
      if ( fac /= 0.0 ) then  ! trick to prevent printing
         if ( MAPL_am_I_root() ) then
            name = '            '
            name(1:len(qname)) = qname
            write(*,*) name, ' max = ', pmax*fac, ' min = ', pmin*fac
            return
         end if
      end if
      return
    end subroutine pmaxmin2d_r4
Call graph
pmaxmin2d_r4 calls esmf_vmgetcurrent, mapl_commsallreducemax, mapl_am_i_root
mapl_commsallreducemax calls mapl_commsallreducemax_i4_0, mapl_commsallreducemax_r4_0, mapl_commsallreducemax_r4_1, mapl_commsallreducemax_i4_1, mapl_commsallreducemax_r8_0, mapl_commsallreducemax_r8_1, mapl_commsallreducemax_i4_2, mapl_commsallreducemax_r4_2, mapl_commsallreducemax_r8_2
mapl_am_i_root calls mapl_am_i_root_vm, mapl_am_i_root_layout
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_commsallreducemax_i4_0 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r4_0 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r4_1 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_i4_1 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r8_0 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r8_1 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_i4_2 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r4_2 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_commsallreducemax_r8_2 calls mapl_return, mpi_allreduce, mapl_verify, esmf_vmget
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_rank calls mapl_am_i_rank_only, mapl_am_i_rank_vm, mapl_am_i_rank_layout
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
pmaxmin1d_r4 calls pmaxmin2d_r4
pmaxmin2d_r8 calls pmaxmin2d_r4
pmaxmin3d_r4 calls pmaxmin2d_r4
mapl_maxmin calls pmaxmin2d_r4, pmaxmin1d_r4, pmaxmin2d_r8, pmaxmin3d_r4, pmaxmin1d_r8, pmaxmin3d_r8
pmaxmin1d_r8 calls pmaxmin1d_r4
pmaxmin3d_r8 calls pmaxmin3d_r4
mapl_simplebundleprint calls mapl_maxmin