pnt_in_rect – MAPL
pnt_in_rect Function
40 statements
Source File
private function pnt_in_rect(x0, y0, x, y)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x0
real, intent(in) :: y0
real, intent(in), dimension(4) :: x
real, intent(in), dimension(4) :: y
Return Value integer
Called by
Contents
Source Code
pnt_in_rect
Source Code
      integer function pnt_in_rect(x0,y0,x,y)
      implicit none
      real, intent(in) :: x0,y0
      real, intent(in), dimension(4) :: x,y
      ! local variable
      integer :: i, j, i1,i2, nintersect
      real :: s,t,x1,y1, denom, tol
      real, dimension(2) :: p0,p1,q0,q1,w,v,u
      tol=0.
      !  for now set x1,y1
      x1=x0+0.2
      y1=y0+0.2
      q0(1)=x0
      q0(2)=y0
      q1(1)=x1
      q1(2)=y1
      nintersect = 0
      ! loop over four sides
      do i = 1, 4
       i1 = i
       i2 = i+1-(4*(i/4))
       ! define edge
       p0(1)=x(i1)
       p0(2)=y(i1)
       p1(1)=x(i2)
       p1(2)=y(i2)
       ! define vectors w,v,u
       do j=1,2
        w(j)=p0(j)-q0(j)
        v(j)=q1(j)-q0(j)
        u(j)=p1(j)-p0(j)
       enddo
       denom = v(1)*u(2)-v(2)*u(1)
       ! if the ray and edge are parallel they probably don't cross, should really
       ! check if they are on top of each other but probably won't happen
       if (abs(denom).gt.tol) then
        s = (v(2)*w(1)-v(1)*w(2))/denom
        t = -(u(1)*w(2)-u(2)*w(1))/denom
        ! now test if ray intersects segment t > 0 and 0 < s < 1
        if (0. <= s .and. s <= 1. .and. t >= 0.) nintersect = nintersect + 1
        ! in future put in test if t = 0, i.e. the point is on one of the edges
       endif
      enddo
      if (mod(nintersect,2) == 1) then
!      if (nintersect == 1) then
       pnt_in_rect = 1
      else
       pnt_in_rect = 0
      endif
      end function pnt_in_rect
Call graph
orb_mask_lonlat calls pnt_in_rect
orb_mask_xy calls pnt_in_rect
orb_swath_mask_xy calls pnt_in_rect
orb_swath_mask_lonlat calls pnt_in_rect
domasking_ calls orb_mask_lonlat, orb_swath_mask_lonlat
domasking_cs calls orb_mask_xy, orb_swath_mask_xy
run_ calls domasking_, domasking_cs