point_in_polygon – MAPL
point_in_polygon Function
21 statements
Source File
private function point_in_polygon(p0, pinside, a1, a2, a3, a4) result(in_poly)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: p0(2)
real(kind=real64), intent(in) :: pinside(2)
real(kind=real64), intent(in) :: a1(2)
real(kind=real64), intent(in) :: a2(2)
real(kind=real64), intent(in) :: a3(2)
real(kind=real64), intent(in) :: a4(2)
Return Value logical
Calls
Called by
Source Code
 function point_in_polygon(p0,pinside,a1,a2,a3,a4) result(in_poly)
    real(real64), intent(in) :: p0(2),pinside(2),a1(2),a2(2),a3(2),a4(2)
    logical :: in_poly
    real(real64) :: p1c(3),p2c(3),a1c(3),a2c(3),a3c(3),a4c(3)
    logical :: intersect(4)
    p1c=convert_to_cart(p0)
    p2c=convert_to_cart(pinside)
    a1c=convert_to_cart(a1)
    a2c=convert_to_cart(a2)
    a3c=convert_to_cart(a3)
    a4c=convert_to_cart(a4)
    intersect(1) = lines_intersect(p1c,p2c,a1c,a2c)
    intersect(2) = lines_intersect(p1c,p2c,a2c,a3c)
    intersect(3) = lines_intersect(p1c,p2c,a3c,a4c)
    intersect(4) = lines_intersect(p1c,p2c,a4c,a1c)
    if (mod(count(intersect),2)==0) then
       in_poly=.true.
    else
       in_poly=.false.
    end if
 end function point_in_polygon
Call graph
point_in_polygon calls convert_to_cart, lines_intersect
lines_intersect calls cross_prod, normal_vect
get_points_in_spherical_domain calls point_in_polygon
mapl_gethorzijindex calls get_points_in_spherical_domain, mapl_gethorzijindex