post_wait – MAPL
post_wait Subroutine
16 statements
Source File
private subroutine post_wait(this, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout), target :: this
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine post_wait(this, unusable, rc)
      class (ClientManager), target, intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      class (ClientThread), pointer :: clientPtr
      clientPtr =>this%current()
      call clientPtr%post_wait_all(_RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine post_wait
Call graph
post_wait calls current, mapl_return, mapl_verify, post_wait_all
current calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
post_wait_all calls mapl_return, mapl_verify, wait_all
get_error_message calls at, insert
mapl_throw_exception calls initialize
wait_all calls mapl_return, mapl_verify, clear_requesthandle
clear_requesthandle calls mapl_return, mapl_verify, erase, m_begin
v_at_32 calls v_at_size_kind
mapl_bundlewritencpar calls post_wait
run calls post_wait
run_model calls post_wait
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
main calls run_model
mapl_esmfstatewritetofile calls mapl_varwritencpar
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile