print_resource – MAPL
print_resource Subroutine
47 statements
Source File
private subroutine print_resource(type_string, label, formatted_value, value_is_default, unusable, iunit, rc)
Print the resource value
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: type_string
character(len=*), intent(in) :: label
character(len=*), intent(in) :: formatted_value
logical, intent(in) :: value_is_default
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(out), optional :: iunit
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine print_resource(type_string, label, formatted_value, value_is_default, unusable, iunit, rc)
      character(len=*), intent(in) :: type_string
      character(len=*), intent(in) :: label
      character(len=*), intent(in) :: formatted_value
      logical, intent(in) :: value_is_default
      class(KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(out) :: iunit
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: DEFAULT_ = ", (default value)"
      character(len=*), parameter :: NONDEFAULT_ = EMPTY_STRING
      character(len=*), parameter :: TRUNCATE = '... [VALUE_TRUNCATED]'
      integer, parameter :: LENGTH_TRUNCATE = len(TRUNCATE)
      character(len=:), allocatable :: output_format
      character(len=:), allocatable :: trailer
      character(len=:), allocatable :: value_out
      character(len=ESMF_MAXSTR) :: output_string
      character(len=MAX_LINE_LENGTH) :: final_output
      integer :: max_length_value_out
      _UNUSED_DUMMY(unusable)
      if(value_is_default) then
         trailer = DEFAULT_
      else
         trailer =  NONDEFAULT_
      end if
      ! maximum line length before adding the label and trailer
      max_length_value_out = MAX_LINE_LENGTH - len_trim(label) - len(trailer)
      value_out = trim(formatted_value)
      if(len(value_out) == 0) then
      ! if something went wrong, the formatted_value will be empty, so provide alternative value_out
         value_out = "[Empty formatted value]"
      else if(len(value_out) > max_length_value_out) then
         ! if value_out is too long (such that the output string will be longer than maxium line length, truncate
         value_out = value_out(1:(max_length_value_out - LENGTH_TRUNCATE)) // TRUNCATE
      end if
      ! Make output_string including label but without the trailer
      output_string = " " // type_string // "Resource Parameter: " // trim(label) // value_out
      ! Add the trailer now
      output_string = trim(output_string) // trailer
      ! Output a string no longer than maximum line length
      final_output = output_string(1:len(final_output))
      output_format = '(a)'
      if(present(iunit)) then
         iunit = EMPTY_STRING
         iunit = final_output(1:min(len(iunit), MAX_LINE_LENGTH))
      else
         write(*, fmt='(a)') trim(final_output)
      end if
      _RETURN(_SUCCESS)
   end subroutine print_resource
Call graph
print_resource calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_getresource_config_array calls print_resource
mapl_getresource_config_scalar calls print_resource
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
test_mapl_getresource_scalar_character calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int8 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_logical calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real8 calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar