print_stack – MAPL
print_stack Subroutine
18 statements
Source File
private subroutine print_stack(s)
Arguments
Type Intent Optional Attributes Name
type(MeterNodeStack), intent(in) :: s
Calls
Source Code
   subroutine print_stack(s)
      type(MeterNodeStack), intent(in) :: s
      type(MeterNodeStackIterator) :: iter
      type(MeterNodePtr), pointer :: node_ptr
      !$omp master
      print*
      print*,'Stack Size: ', s%size()
      print*,'---------------'
      associate(b => s%begin(), e => s%end())
        iter = b
        do while (iter /= e)
           node_ptr => iter%of()
           print*,node_ptr%ptr%get_name()
           call iter%next()
        end do
      end associate
      print*,'---------------'
      print*
      !$omp end master
   end subroutine print_stack
Call graph
print_stack calls get_name, of, vector_begin, vector_iter_next