process_data_from_file – MAPL
process_data_from_file Subroutine
44 statements
Source File
private subroutine process_data_from_file(this, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Contents
Source Code
process_data_from_file
Source Code
  subroutine process_data_from_file(this,rc)
     class(mapl_GriddedIO), intent(inout) :: this
     integer, intent(out), optional :: rc
     integer :: status
     integer :: i,numVars
     character(len=ESMF_MAXSTR), allocatable :: names(:)
     type(ESMF_Field) :: field
     type(GriddedIOitem), pointer :: item
     type(GriddedIOitemVectorIterator) :: iter
     call ESMF_FieldBundleGet(this%output_bundle,fieldCount=numVars,rc=status)
     _VERIFY(status)
     allocate(names(numVars),stat=status)
     _VERIFY(status)
     call ESMF_FieldBundleGet(this%output_bundle,fieldNameList=names,rc=status)
     _VERIFY(status)
     iter = this%items%begin()
     do while(iter /= this%items%end())
        item => iter%get()
        if (item%itemType == ItemTypeScalar) then
           call this%swap_undef_value(trim(item%xname),_RC)
           call this%regridScalar(trim(item%xname),rc=status)
           _VERIFY(status)
        else if (item%itemType == ItemTypeVector) then
           call this%swap_undef_value(trim(item%xname),_RC)
           call this%swap_undef_value(trim(item%yname),_RC)
           call this%regridVector(trim(item%xname),trim(item%yname),rc=status)
           _VERIFY(status)
        end if
        call iter%next()
     enddo
     do i=1,numVars
        call ESMF_FieldBundleGet(this%input_bundle,trim(names(i)),field=field,rc=status)
        _VERIFY(status)
        call ESMF_FieldDestroy(field,noGarbage=.true., rc=status)
        _VERIFY(status)
     enddo
     call ESMF_FieldBundleDestroy(this%input_bundle,noGarbage=.true.,rc=status)
     _VERIFY(status)
     _RETURN(_SUCCESS)
  end subroutine process_data_from_file
Call graph
process_data_from_file calls esmf_fieldbundledestroy, esmf_fieldbundleget, esmf_fielddestroy, get, next, mapl_return, mapl_verify, regridscalar, regridvector, swap_undef_value
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
regridscalar calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, mapl_gridhasde
regridvector calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_gridhasde
swap_undef_value calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, mapl_gridhasde
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar4_1, esmfl_fieldgetptrtodatar4_2, esmfl_fieldgetptrtodatar4_3, esmfl_fieldgetptrtodatar4_4, esmfl_fieldgetptrtodatar8_1, esmfl_fieldgetptrtodatar8_2, esmfl_fieldgetptrtodatar8_3, esmfl_fieldgetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_throw_exception calls initialize
esmfl_fieldgetptrtodatar4_1 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar4_2 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar4_3 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar4_4 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar8_1 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar8_2 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar8_3 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
esmfl_fieldgetptrtodatar8_4 calls mapl_return, mapl_verify, esmf_fieldget, mapl_gridhasde
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception