process_data_from_file – MAPL
process_data_from_file Subroutine
44 statements
Source File
private subroutine process_data_from_file(this, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine process_data_from_file(this,rc)
     class(mapl_GriddedIO), intent(inout) :: this
     integer, intent(out), optional :: rc
     integer :: status
     integer :: i,numVars
     character(len=ESMF_MAXSTR), allocatable :: names(:)
     type(ESMF_Field) :: field
     type(GriddedIOitem), pointer :: item
     type(GriddedIOitemVectorIterator) :: iter
     call ESMF_FieldBundleGet(this%output_bundle,fieldCount=numVars,rc=status)
     _VERIFY(status)
     allocate(names(numVars),stat=status)
     _VERIFY(status)
     call ESMF_FieldBundleGet(this%output_bundle,fieldNameList=names,rc=status)
     _VERIFY(status)
     iter = this%items%begin()
     do while(iter /= this%items%end())
        item => iter%get()
        if (item%itemType == ItemTypeScalar) then
           call this%swap_undef_value(trim(item%xname),_RC)
           call this%regridScalar(trim(item%xname),rc=status)
           _VERIFY(status)
        else if (item%itemType == ItemTypeVector) then
           call this%swap_undef_value(trim(item%xname),_RC)
           call this%swap_undef_value(trim(item%yname),_RC)
           call this%regridVector(trim(item%xname),trim(item%yname),rc=status)
           _VERIFY(status)
        end if
        call iter%next()
     enddo
     do i=1,numVars
        call ESMF_FieldBundleGet(this%input_bundle,trim(names(i)),field=field,rc=status)
        _VERIFY(status)
        call ESMF_FieldDestroy(field,noGarbage=.true., rc=status)
        _VERIFY(status)
     enddo
     call ESMF_FieldBundleDestroy(this%input_bundle,noGarbage=.true.,rc=status)
     _VERIFY(status)
     _RETURN(_SUCCESS)
  end subroutine process_data_from_file
Call graph
process_data_from_file calls esmf_fieldbundledestroy, esmf_fieldbundleget, esmf_fielddestroy, mapl_return, mapl_verify, regridscalar, regridvector, swap_undef_value, v_begin, v_iter_get, v_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
regridscalar calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, regrid, flip_levels, mapl_gridhasde, regrid_eta_to_pressure, regrid_select_level
regridvector calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, regrid, flip_levels, mapl_gridhasde, regrid_eta_to_pressure, regrid_select_level
swap_undef_value calls esmf_fieldbundleget, mapl_return, mapl_verify, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, mapl_gridhasde, var_get_missing_value, var_has_missing_value
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
main calls mapl_read_bundle
run_ calls mapl_extdatareadprefetch
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main