ProvidedServiceSet – MAPL
ProvidedServiceSet Subroutine
18 statements
Source File
public subroutine ProvidedServiceSet(provider_list, state, rc)
Arguments
Type Intent Optional Attributes Name
type(providedServiceItemVector), intent(in) :: provider_list
type(ESMF_State), intent(in) :: state
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine ProvidedServiceSet(provider_list, state, rc)
    type(ProvidedServiceItemVector), intent(IN) :: provider_list
    type(ESMF_State), intent(IN) :: state
    integer, optional, intent(out) :: rc
    integer :: status
    type (ProvidedServiceItemVectorIterator) :: iter
    type (ProvidedServiceType), pointer :: item
    _ASSERT(provider_list%size()>0,'provider_list should not be empty')
    iter = provider_list%begin()
    ! loop over provided services
    do while (iter /= provider_list%end())
       item => iter%get()
       call ESMF_StateGet(state, item%bundle_name, &
            item%bundle, rc=status)
       _VERIFY(status)
       call iter%next()
    end do
    _RETURN(_SUCCESS)
  end subroutine ProvidedServiceSet
Call graph
providedserviceset calls esmf_stateget, mapl_assert, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_genericinitialize calls providedserviceset
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize