ProvidedServiceGet – MAPL
ProvidedServiceGet Subroutine
24 statements
Source File
public subroutine ProvidedServiceGet(provider_list, advertised_service, bundle, rc)
Arguments
Type Intent Optional Attributes Name
type(providedServiceItemVector), intent(in) :: provider_list
character(len=*), intent(in) :: advertised_service
type(ESMF_FieldBundle), intent(out) :: bundle
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine ProvidedServiceGet(provider_list, advertised_service, bundle, rc)
    type(ProvidedServiceItemVector), intent(IN) :: provider_list
    character(len=*), intent(IN) :: advertised_service
    type(ESMF_FieldBundle), intent(OUT) :: bundle
    integer, optional, intent(out) :: rc
    logical :: found
    type (ProvidedServiceItemVectorIterator) :: iter
    type (ProvidedServiceType), pointer :: item
    _ASSERT(provider_list%size()>0,'provider_list should not be empty')
    found = .false.
    iter = provider_list%begin()
    ! loop over provided services
    do while (iter /= provider_list%end())
       item => iter%get()
       if(item%service_name == advertised_service) then
          found = .true.
          bundle = item%bundle
          exit
       end if
    end do
    _ASSERT(found, 'No match found for service')
    call iter%next()
    _RETURN(_SUCCESS)
  end subroutine ProvidedServiceGet
Call graph
providedserviceget calls mapl_assert, mapl_return, v_begin, v_iter_get, v_iter_next
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_servicegetbundle calls providedserviceget
mapl_processserviceconnections calls mapl_servicegetbundle
mapl_genericinitialize calls mapl_processserviceconnections
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize