publish – MAPL
publish Subroutine
49 statements
Source File
private subroutine publish(this, port, server, rc)
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(inout), target :: this
type(PortInfo), intent(in), target :: port
class(BaseServer), intent(in) :: server
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine publish(this, port, server, rc)
      class (DirectoryService), target,intent(inout) :: this
      type(PortInfo),target, intent(in) :: port
      class (BaseServer), intent(in) :: server
      integer, optional, intent(out) :: rc
      character(len=MAX_LEN_PORT_NAME) :: port_name
      integer :: ierror
      integer :: rank_in_server
      integer :: n
      type (Directory) :: dir
      type (DirectoryEntry) :: dir_entry
      logical :: found
      integer :: server_comm
      character(len=*), parameter :: Iam = __FILE__
      ! Update local ports
      this%n_local_ports = this%n_local_ports + 1
      this%local_ports(this%n_local_ports) = port
      server_comm = MPI_COMM_NULL
      server_comm = server%get_communicator()
      if (server_comm == MPI_COMM_NULL) then
         _RETURN(_SUCCESS)
      endif
      call MPI_Comm_rank(server_comm, rank_in_server, ierror)
      _VERIFY(ierror)
      port_name = port%port_name
      if (rank_in_server == 0) then
         call this%mutex%acquire()
        ! Get - modify - put
         dir = this%get_directory(this%win_server_directory)
         ! Verify that server has not already published.
         found = .false.
         do n = 1, dir%num_entries
            if (port_name == dir%entries(n)%port_name) then
               if (dir%entries(n)%partner_root_rank >= 0) then
                  found = .true.
               end if
               exit
            end if
         end do
         _ASSERT(.not. found, 'not found port_name')
         n = dir%num_entries + 1
         dir%num_entries = n
         dir_entry%port_name = port_name
         dir_entry%partner_root_rank = this%rank
         dir%entries(n) = dir_entry
         call this%put_directory(dir, this%win_server_directory)
         call this%mutex%release()
      end if
      _RETURN(_SUCCESS)
   end subroutine publish
Call graph
publish calls mapl_assert, mpi_comm_rank, acquire, get_communicator, get_directory, mapl_return, mapl_verify, put_directory, release
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
acquire calls mapl_verify, mpi_get, mpi_put, mpi_recv, mpi_win_lock, mpi_win_unlock
get_directory calls mapl_verify, mpi_get, mpi_win_lock, mpi_win_unlock, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
put_directory calls mapl_verify, mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
release calls mapl_verify, mpi_get, mpi_put, mpi_send, mpi_win_lock, mpi_win_unlock
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize calls publish
test_connect calls publish
test_connect_multi calls publish
test_connect_swap_role calls publish
test_connect_with_unused_process calls publish
test_publish calls publish
test_stress calls publish
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run