put_var_real32_3 – MAPL
put_var_real32_3 Subroutine
21 statements
Source File
private subroutine put_var_real32_3(this, var_name, values, unusable, start, count, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
real(kind=REAL32), intent(in) :: values(:,:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Call graph
put_var_real32_3 calls nf90_inq_varid, nf90_put_var, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize