put_var_real64_4 – MAPL
put_var_real64_4 Subroutine
21 statements
Source File
private subroutine put_var_real64_4(this, var_name, values, unusable, start, count, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
real(kind=REAL64), intent(in) :: values(:,:,:,:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Called by
Call graph
put_var_real64_4 calls nf90_inq_varid, nf90_put_var, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
append_file calls put_var
create_file_handle calls put_var, create_file_handle
init calls put_var
mapl_varwritencpar_r4_1d calls put_var
mapl_varwritencpar_r4_2d calls put_var
mapl_varwritencpar_r8_1d calls put_var
mapl_varwritencpar_r8_2d calls put_var
put_datatofile calls put_var, put_datatofile
regrid_append_file calls put_var, regrid_append_file
run calls put_var, append_file
setup calls put_var
write_const_variables calls put_var
write_coordinate_variables calls put_var
write_data calls put_var
main calls put_var, run, init, write_data
mapl_varwrite calls mapl_varwritencpar_r4_1d, mapl_varwritencpar_r4_2d, mapl_varwritencpar_r8_1d, mapl_varwritencpar_r8_2d
clean_up calls put_datatofile
handle_done_stage calls put_datatofile
start_back calls put_datatofile
write calls write_const_variables, write_coordinate_variables