put_var_real32_0 – MAPL
put_var_real32_0 Subroutine
16 statements
Source File
private subroutine put_var_real32_0(this, var_name, values, unusable, rc)
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
real(kind=REAL32), intent(in) :: values
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Contents
Call graph
put_var_real32_0 calls nf90_inq_varid, mapl_return, mapl_verify, nf90_put_var
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize