put_var_string_1 – MAPL
put_var_string_1 Subroutine
21 statements
Source File
private subroutine put_var_string_1(this, var_name, values, unusable, start, count, rc)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(in) :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: values(:)
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(in), optional :: count(:)
integer, intent(out), optional :: rc
Calls
Call graph
put_var_string_1 calls nf90_inq_varid, mapl_return, mapl_verify, pfio_nf90_put_var_string
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
pfio_nf90_put_var_string calls c_f_pfio_put_var_string
get_error_message calls at, insert
mapl_throw_exception calls initialize