put_directory – MAPL
put_directory Subroutine
18 statements
Source File
private subroutine put_directory(this, dir, win)
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(in) :: this
type(Directory), intent(in) :: dir
integer, intent(in) :: win
Calls
Called by
Source Code
   subroutine put_directory(this, dir, win)
      class (DirectoryService), intent(in) :: this
      type (Directory), intent(in) :: dir
      integer, intent(in) :: win
      integer :: sz
      integer(kind=MPI_ADDRESS_KIND) :: disp
      integer :: ierror
      call MPI_Win_lock(MPI_LOCK_EXCLUSIVE, 0, 0, win, ierror)
      sz = sizeof_directory()
      disp = 0
      call MPI_put(dir, sz, MPI_BYTE, 0, disp, sz, MPI_BYTE, win, ierror)
      call MPI_Win_unlock(0, win, ierror)
      return
      _UNUSED_DUMMY(this)
   end subroutine put_directory
Call graph
put_directory calls mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
connect_to_client calls put_directory
connect_to_server calls put_directory
new_directoryservice calls put_directory
publish calls put_directory
test_put_directory calls put_directory
directoryservice calls new_directoryservice
initialize calls connect_to_client, connect_to_server, publish
test_connect calls connect_to_client, connect_to_server, publish
test_connect_multi calls connect_to_client, connect_to_server, publish
test_connect_swap_role calls connect_to_client, connect_to_server, publish
test_connect_with_unused_process calls connect_to_client, connect_to_server, publish
test_publish calls publish
test_stress calls connect_to_client, connect_to_server, publish
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver
time_ave calls initialize
ut_regridding calls initialize
initialize_p0 calls initialize_io_clients_servers
run_ensemble calls initialize_io_clients_servers
run calls initialize_io_clients_servers
regrid_util calls main