put – MAPL
put Function
24 statements
Source File
private function put(this, request_id, local_reference, rc) result(handle)
Type Bound
MpiSocket
Arguments
Type Intent Optional Attributes Name
class(MpiSocket), intent(inout) :: this
integer, intent(in) :: request_id
class(AbstractDataReference), intent(in) :: local_reference
integer, intent(out), optional :: rc
Return Value class(AbstractRequestHandle), allocatable
Calls
Contents
Source Code
put
Source Code
   function put(this, request_id, local_reference, rc) result(handle)
      class (AbstractRequestHandle), allocatable :: handle
      class (MpiSocket), intent(inout) :: this
      integer, intent(in) :: request_id
      class (AbstractDatareference), intent(in) :: local_reference
      integer, optional, intent(out) :: rc
      integer :: request
      integer :: ierror
      integer :: tag
      integer, pointer :: data(:)
      integer :: n_words
      integer(kind=INT64) :: big_n
      tag = make_tag(request_id)
      big_n   = product(int(local_reference%shape, INT64)) * word_size(local_reference%type_kind)
      _ASSERT( big_n < huge(0), "Increase the number of processors to decrease the local size of data to be sent")
      n_words = big_n
      call c_f_pointer(local_reference%base_address, data, shape=[n_words])
      if (n_words ==0) allocate(data(1))
      call MPI_Isend(data, n_words, MPI_INTEGER, this%pair_remote_rank, tag, this%pair_comm, request, ierror)
      allocate(handle, source=MpiRequestHandle(local_reference, request))
      if (n_words ==0) deallocate(data)
      _RETURN(_SUCCESS)
   end function put
Call graph
put calls mapl_assert, mpirequesthandle, mpi_isend, make_tag, mapl_return, word_size
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mpirequesthandle calls new_mpirequesthandle
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_assert, mapl_return
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize