QSAT0 – MAPL
QSAT0 Function
220 statements
Source File
private recursive function QSAT0(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: TL
real(kind=REAL32), intent(in), optional :: PL
real(kind=REAL32), intent(out), optional :: DQ
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL32)
Calls
Called by
Source Code
  recursive function QSAT0(TL,PL,DQ,OverIce) result(QS)
    real(kind=REAL32),              intent(IN) :: TL
    real(kind=REAL32), optional,    intent(IN) :: PL
    real(kind=REAL32), optional,    intent(OUT):: DQ
    logical,optional,    intent(IN) :: OverIce
    real(kind=REAL32)                          :: QS
    real(kind=REAL32)    :: TI,W
    real(kind=REAL32)    :: DD, TT, EF
    real(kind=REAL32)    :: DDQ
    integer   :: IT
    logical   :: OverLqu
    OverLqu = .true.
    if(present(OverIce)) OverLqu=.not.OverIce
    if(OverLqu) then
#include "qsatlqu.H"
    else
#include "qsatice.H"
    end if
    return
  end function QSAT0
Call graph
qsat0 calls qsat0, mapl_eqsatset
mapl_eqsatset calls qsatd0
qsatd0 calls mapl_eqsatset, qsatd0
mapl_eqsat calls qsat0, qsat1, qsat2, qsat3
qsat1 calls qsat0
qsat2 calls qsat0
qsat3 calls qsat0
tstqsat calls mapl_eqsat