QSAT3 – MAPL
QSAT3 Function
227 statements
Source File
private function QSAT3(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: TL(:,:,:)
real(kind=REAL32), intent(in), optional :: PL(:,:,:)
real(kind=REAL32), intent(out), optional :: DQ(:,:,:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL32), (SIZE(TL,1),SIZE(TL,2),SIZE(TL,3))
Calls
Called by
Source Code
   function QSAT3(TL,PL,DQ, OverIce) result(QS)
    real(kind=REAL32),              intent(IN) :: TL(:,:,:)
    real(kind=REAL32), optional,    intent(IN) :: PL(:,:,:)
    real(kind=REAL32), optional,    intent(OUT):: DQ(:,:,:)
    logical,optional,    intent(IN) :: OverIce
    real(kind=REAL32)    :: QS(SIZE(TL,1),SIZE(TL,2),SIZE(TL,3))
    integer   :: I, J, K
    real(kind=REAL32)    :: TI,W
    real(kind=REAL32)    :: DDQ
    real(kind=REAL32)    :: DD, TT, EF
    integer   :: IT
    logical   :: OverLqu
    OverLqu = .true.
    if(present(OverIce)) OverLqu=.not.OverIce
    do K=1,size(TL,3)
       do J=1,size(TL,2)
          do I=1,size(TL,1)
             if(OverLqu) then
#include "qsatlqu.H"
             else
#include "qsatice.H"
             end if
          end do
       end do
    end do
    return
  end function QSAT3
Call graph
qsat3 calls mapl_eqsatset, qsat0
mapl_eqsatset calls qsatd0
qsat0 calls mapl_eqsatset, qsat0
qsatd0 calls mapl_eqsatset, qsatd0
mapl_eqsat calls qsat3
tstqsat calls mapl_eqsat