QSATD0 – MAPL
QSATD0 Function
220 statements
Source File
private recursive function QSATD0(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: TL
real(kind=REAL64), intent(in), optional :: PL
real(kind=REAL64), intent(out), optional :: DQ
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL64)
Calls
Called by
Source Code
  recursive function QSATD0(TL,PL,DQ,OverIce) result(QS)
    real(kind=REAL64),              intent(IN) :: TL
    real(kind=REAL64), optional,    intent(IN) :: PL
    real(kind=REAL64), optional,    intent(OUT):: DQ
    logical,optional,    intent(IN) :: OverIce
    real(kind=REAL64)                          :: QS
    real(kind=REAL64)    :: TI,W
    real(kind=REAL64)    :: DD, TT, EF
    real(kind=REAL64)    :: DDQ
    integer   :: IT
    logical   :: OverLqu
    OverLqu = .true.
    if(present(OverIce)) OverLqu=.not.OverIce
    if(OverLqu) then
#include "qsatlqu.H"
    else
#include "qsatice.H"
    end if
    return
  end function QSATD0
Call graph
qsatd0 calls qsatd0, mapl_eqsatset
mapl_eqsatset calls qsatd0
mapl_eqsat calls qsatd0, qsatd1, qsatd2, qsatd3, qsat0, qsat1, qsat2, qsat3
qsatd1 calls qsatd0, mapl_eqsatset
qsatd2 calls qsatd0, mapl_eqsatset
qsatd3 calls qsatd0, mapl_eqsatset
qsat0 calls mapl_eqsatset, qsat0
qsat1 calls mapl_eqsatset, qsat0
qsat2 calls mapl_eqsatset, qsat0
qsat3 calls mapl_eqsatset, qsat0
tstqsat calls mapl_eqsat, mapl_eqsatset