QSATD3 – MAPL
QSATD3 Function
227 statements
Source File
private function QSATD3(TL, PL, DQ, OverIce) result(QS)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: TL(:,:,:)
real(kind=REAL64), intent(in), optional :: PL(:,:,:)
real(kind=REAL64), intent(out), optional :: DQ(:,:,:)
logical, intent(in), optional :: OverIce
Return Value real(kind=REAL64), (SIZE(TL,1),SIZE(TL,2),SIZE(TL,3))
Calls
Called by
Contents
Source Code
QSATD3
Source Code
   function QSATD3(TL,PL,DQ, OverIce) result(QS)
    real(kind=REAL64),              intent(IN) :: TL(:,:,:)
    real(kind=REAL64), optional,    intent(IN) :: PL(:,:,:)
    real(kind=REAL64), optional,    intent(OUT):: DQ(:,:,:)
    logical,optional,    intent(IN) :: OverIce
    real(kind=REAL64)    :: QS(SIZE(TL,1),SIZE(TL,2),SIZE(TL,3))
    integer   :: I, J, K
    real(kind=REAL64)    :: TI,W
    real(kind=REAL64)    :: DDQ
    real(kind=REAL64)    :: DD, TT, EF
    integer   :: IT
    logical   :: OverLqu
    OverLqu = .true.
    if(present(OverIce)) OverLqu=.not.OverIce
    do K=1,size(TL,3)
       do J=1,size(TL,2)
          do I=1,size(TL,1)
             if(OverLqu) then
#include "qsatlqu.H"
             else
#include "qsatice.H"
             end if
          end do
       end do
    end do
    return
  end function QSATD3
Call graph
qsatd3 calls mapl_eqsatset, qsatd0
qsatd0 calls mapl_eqsatset, qsatd0
mapl_eqsat calls qsatd3
tstqsat calls mapl_eqsat