rad2deg – MAPL
rad2deg Function
5 statements
Source File
private function rad2deg(rad)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: rad
Return Value real(kind=dp)
Called by
Contents
Source Code
rad2deg
Source Code
REAL(dp) FUNCTION rad2deg(rad)
       IMPLICIT NONE
       REAL(dp), INTENT(IN) :: rad
       rad2deg = MAPL_RADIANS_TO_DEGREES * rad
END FUNCTION rad2deg
Call graph
get_latlon calls rad2deg
get_azimuth calls rad2deg
get_distance calls rad2deg
get_reckon calls rad2deg
find_delta_t calls get_latlon, get_distance
redifine_timeint calls get_latlon
find_sweeppoints calls get_azimuth, get_reckon
find_waypointslat calls get_latlon
orbits_swath calls find_sweeppoints, orbits_track
orbits_track calls find_waypointslat
domasking_ calls orbits_swath, orbits_track
domasking_cs calls orbits_swath, orbits_track