READ_PARALLEL_STRING_0 – MAPL
READ_PARALLEL_STRING_0 Subroutine
71 statements
Source File
private subroutine READ_PARALLEL_STRING_0(layout, data, UNIT, FORMAT, ARRDES, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_DELayout) :: layout
character(len=*), intent(out) :: data
integer, intent(in), optional :: UNIT
character(len=*), intent(in), optional :: FORMAT
type(ArrDescr), intent(inout), optional :: ARRDES
integer, intent(out), optional :: RC
Calls
Called by
Call graph
read_parallel_string_0 calls mapl_am_i_root, mapl_assert, mapl_commsbcast, mpi_file_read, mpi_file_seek, mapl_return, mapl_verify
read_parallel calls read_parallel_string_0
mapl_fieldread calls read_parallel, mapl_varread
mapl_gridcoordadjustfromfile calls read_parallel
mapl_locstreamcreatefromfile calls read_parallel
mapl_readforcingx calls read_parallel, mapl_varread
mapl_locstreamcreate calls mapl_locstreamcreatefromfile
mapl_varread calls mapl_fieldread, mapl_bundleread, mapl_statevarread
mapl_bundleread calls mapl_fieldread
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_statevarread calls mapl_fieldread, mapl_bundleread
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
initialize calls mapl_locstreamcreate
initialize_ calls mapl_locstreamcreate
mapl_climupdate calls mapl_varread
mapl_esmfstatereadfromfile calls mapl_varread
mapl_varread_r4_2d calls mapl_varread
mapl_varread_r4_3d calls mapl_varread
mapl_varread_r4_4d calls mapl_varread
mapl_varread_r8_2d calls mapl_varread
mapl_varread_r8_3d calls mapl_varread
mapl_varread_r8_4d calls mapl_varread
readrestart calls mapl_varread