read_metadata – MAPL
read_metadata Subroutine
9 statements
Source File
public subroutine read_metadata(this)
Type Bound
RegridSupport
Arguments
Type Intent Optional Attributes Name
class(RegridSupport), intent(inout) :: this
Calls
Called by
Source Code
   subroutine read_metadata(this)
      class (RegridSupport), intent(inout) :: this
      associate (formatter => this%formatter_cubed_sphere )
         call formatter%open(this%in_file, mode=pFIO_READ)
         this%cfio_cubed_sphere = formatter%read()
         this%nt = formatter%inq_dim('time')
         call formatter%close()
      end associate
    end subroutine read_metadata
Call graph
read_metadata calls inq_dim
inq_dim calls nf90_inq_dimid, nf90_inquire_dimension, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
main calls read_metadata