read_xml – MAPL
read_xml Subroutine
13 statements
Source File
public subroutine read_xml(path, utsystem, status)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: path
type(c_ptr), intent(out) :: utsystem
integer(kind=ut_status), intent(out) :: status
Calls
Called by
Source Code
   subroutine read_xml(path, utsystem, status)
      character(len=*), optional, intent(in) :: path
      type(c_ptr), intent(out) :: utsystem
      integer(ut_status), intent(out) :: status
      character(kind=c_char, len=:), target, allocatable :: cchar_path
      if(present(path)) then
         cchar_path = cstring(path)
         utsystem = ut_read_xml_cptr(c_loc(cchar_path))
      else
         utsystem = ut_read_xml_cptr(c_null_ptr)
      end if
      status = ut_get_status()
   end subroutine read_xml
Call graph
read_xml calls ut_get_status, ut_read_xml_cptr, cstring
construct_system calls read_xml
test_read_xml_nopath calls read_xml
udsystem calls construct_system