read_variable – MAPL
read_variable Subroutine
94 statements
Source File
public subroutine read_variable(this, var_name, local_var)
Type Bound
test_support
Arguments
Type Intent Optional Attributes Name
class(test_support), intent(inout) :: this
character(len=*), intent(in) :: var_name
real, intent(in) :: local_var(:,:,:)
Calls
Called by
Call graph
read_variable calls mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_scatterv, nf90_get_var, nf90_inq_varid
read_file calls read_variable
checkpoint_tester calls read_file