readTileFileNC – MAPL
readTileFileNC Subroutine
24 statements
Source File
public subroutine readTileFileNC(TFDir, gridIn, gridOut, RC)
The routine readTileFileNC reads a Tempest NetCDF tile file and stores the relevant data in module variables for later use.
History
09 Jan 2016 - S. D. Eastham - Initial version
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: TFDir
character(len=*), intent(in) :: gridIn
character(len=*), intent(in) :: gridOut
integer, optional :: RC
Calls
Contents
Source Code
readTileFileNC
Source Code
      subroutine readTileFileNC(TFDir,gridIn,gridOut,RC)
!
! !USES:
!
!      Use Precision_Mod, Only: f4
!
! !INPUT PARAMETERS:
!
      Character(Len=*), Intent(In)         :: TFDir
      Character(Len=*), Intent(In)         :: gridIn
      Character(Len=*), Intent(In)         :: gridOut
      Integer, Optional                    :: RC
!
! !OUTPUT PARAMETERS:
!
      !Real(kind=sp), Intent(Out) :: TestOut
!
!-----------------------------------------------------------------------
!
! !LOCAL VARIABLES:
!
      Character(Len=255)        :: fName
      Logical                   :: Found
      Integer                   :: status
      !=================================================================
      ! readTileFileNC starts here!
      !=================================================================
      ! Assemble the full tile file name
      Write(fName,'(a,a,a,a)') Trim(gridIn),'_',Trim(gridOut),'.nc'
      fName = Trim(TFDir) // '/' // Trim(fName)
      Inquire(File=fName,Exist=Found)
      If (.not.Found) Then
         ! Try the reverse name
         Write(fName,'(a,a,a,a)') Trim(gridOut),'_',Trim(gridIn),'.nc'
         fName = Trim(TFDir) // '/' // Trim(fName)
         Inquire(File=fName,Exist=Found)
         If (.not.Found) Then
            Write(6,'(a,a)') ' --- Could not find NetCDF tile file ',Trim(fName)
            RC = -1
            Return
         End If
      End If
      call readTileFileNC_file(fName, rc=status)
      if (present(rc)) rc = status
      end subroutine readTileFileNC
Call graph
readtilefilenc calls readtilefilenc_file
readtilefilenc_file calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, assert, flipcs, swapcs, transposecs
assert calls nf90_close, cleanup
cleanup calls nf90_close