read – MAPL
read Function
17 statements
Source File
private function read(this, unusable, rc) result(cf)
Type Bound
NetCDF4_FileFormatter
Arguments
Type Intent Optional Attributes Name
class(NetCDF4_FileFormatter), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(FileMetadata), target
Calls
Contents
Source Code
read
Source Code
   function read(this, unusable, rc) result(cf)
      type (FileMetadata), target :: cf
      class (NetCDF4_FileFormatter), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      call this%inq_dimensions(cf, rc=status)
      _VERIFY(status)
      call this%inq_variables(cf, rc=status)
      _VERIFY(status)
      call this%inq_attributes(cf, NF90_GLOBAL, rc=status)
      _VERIFY(status)
      if (allocated(this%origin_file)) call cf%set_source_file(this%origin_file)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end function read
Call graph
read calls inq_attributes, inq_dimensions, inq_variables, mapl_return, mapl_verify, set_source_file
inq_attributes calls mapl_return, mapl_verify, add_attribute, nf90_get_att, nf90_inq_attname, nf90_inquire, nf90_inquire_attribute, pfio_get_att_string
inq_dimensions calls mapl_return, mapl_verify, get_dimensions, insert, nf90_inquire, nf90_inquire_dimension
inq_variables calls mapl_return, mapl_verify, get_var, nf90_inq_dimid, nf90_inquire, nf90_inquire_dimension, nf90_inquire_variable, add_variable, get_fio_type, inq_var_attributes, is_coordinate_dimension
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
add_variable calls mapl_return, mapl_verify, nf90_enddef, nf90_redef, def_variables
get_error_message calls at
inq_var_attributes calls mapl_return, mapl_verify, add_attribute, nf90_get_att, nf90_inq_attname, nf90_inquire_attribute, nf90_inquire_variable
is_coordinate_dimension calls nf90_inq_dimid
mapl_throw_exception calls initialize
pfio_get_att_string calls c_f_pfio_get_att_string