read_tempest – MAPL
read_tempest Function
22 statements
Source File
private function read_tempest(file_name, unusable, rc) result(tile_file)
Uses
Regrid_Functions_Mod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(TileFile)
Calls
Called by
Source Code
    function read_tempest(file_name, unusable, rc) result(tile_file)
      use Regrid_Functions_Mod
      type (TileFile) :: tile_file
      character(len=*), intent(in) :: file_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = 'read_tempest'
      call readTileFileNC_file(file_name)
      tile_file%grid_tiles(1)%i_indices = II_in
      tile_file%grid_tiles(1)%j_indices = JJ_in
      tile_file%grid_tiles(1)%i_indices = II_out
      tile_file%grid_tiles(1)%j_indices = JJ_out
      tile_file%grid_tiles(1)%weights = W
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(rc)
   end function read_tempest
Call graph
read_tempest calls readtilefilenc_file
readtilefilenc_file calls nf90_close, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, assert, flipcs, swapcs, transposecs
assert calls nf90_close, cleanup
cleanup calls nf90_close
initialize_subclass calls read_tempest
initialize_base calls initialize
make_regridder_from_grids calls initialize
newlatlontolatlonregridder calls initialize
latlontolatlonregridder calls newlatlontolatlonregridder