read_whole_number – MAPL
read_whole_number Function
4 statements
Source File
public pure function read_whole_number(string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value integer
Calls
Called by
Contents
Source Code
read_whole_number
Source Code
   pure integer function read_whole_number(string)
      character(len=*), intent(in) :: string
      read_whole_number = read_whole_number_indexed(string, 1, len(string))
   end function read_whole_number
Call graph
read_whole_number calls read_whole_number_indexed
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
get_integer_digit_from_string calls get_integer_digit
parse_date calls read_whole_number, date_fields
parse_timezone_offset calls read_whole_number
parse_time calls read_whole_number, parse_timezone_offset, time_fields
test_read_whole_number calls read_whole_number
construct_date_fields_string calls parse_date
construct_time_fields_string calls parse_time
test_parse_date calls parse_date
test_parse_timezone_offset calls parse_timezone_offset
test_parse_time calls parse_time
date_fields calls construct_date_fields_string
time_fields calls construct_time_fields_string
test_are_valid_date_fields calls date_fields
test_are_valid_time_fields calls time_fields
test_construct_date_fields_null calls date_fields
test_construct_time_fields_null calls time_fields
test_get_day_field calls date_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_month_field calls date_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields
test_is_valid_time calls time_fields