read_whole_number_indexed – MAPL
read_whole_number_indexed Function
25 statements
Source File
public pure function read_whole_number_indexed(string, istart, istop)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
integer, intent(in) :: istart
integer, intent(in) :: istop
Return Value integer
Calls
Called by
Contents
Source Code
read_whole_number_indexed
Source Code
   pure integer function read_whole_number_indexed(string, istart, istop)
      character(len=*), intent(in) :: string
      integer, intent(in) :: istart
      integer, intent(in) :: istop
      integer, parameter :: BASE=10
      integer :: n
      integer :: i
      integer :: place_value
      integer :: digit_value
      read_whole_number_indexed = INVALID
      ! Check indices
      if((istart < 1) .or. (istart > istop) .or. (istop > len(string))) return
      ! Convert characters from string, last to first, to integers,
      ! multiplies by place value, and adds
      place_value = 1
      n = 0
      do i= istop, istart, -1
         digit_value = get_integer_digit_from_string(string, i)
         if(is_whole_number(digit_value)) then
            n = n + digit_value * place_value
            place_value = place_value * BASE
         else
            n = INVALID
            exit
         end if
      end do
      read_whole_number_indexed = n
   end function read_whole_number_indexed
Call graph
read_whole_number_indexed calls get_integer_digit_from_string, is_whole_number
get_integer_digit_from_string calls get_integer_digit
construct_iso8601duration calls read_whole_number_indexed
read_whole_number calls read_whole_number_indexed
test_read_whole_number_indexed calls read_whole_number_indexed
iso8601duration calls construct_iso8601duration
parse_date calls read_whole_number
parse_time calls read_whole_number, parse_timezone_offset
parse_timezone_offset calls read_whole_number
test_read_whole_number calls read_whole_number
construct_iso8601date calls parse_date
construct_iso8601time calls parse_time
convert_iso8601_to_esmf_timeinterval calls iso8601duration
test_parse_date calls parse_date
test_parse_time calls parse_time
test_parse_timezone_offset calls parse_timezone_offset
iso8601date calls construct_iso8601date
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time