read_geos_binary – MAPL
read_geos_binary Function
130 statements
Source File
private function read_geos_binary(file_name, unusable, rc) result(tile_file)
Uses
MAPL_CommsMod
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(TileFile)
Calls
Called by
Contents
Source Code
read_geos_binary
Source Code
    function read_geos_binary(file_name, unusable, rc) result(tile_file)
      use MAPL_CommsMod
      type (TileFile) :: tile_file
      character(len=*), intent(in) :: file_name
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: n_tiles
      integer :: n_grids
      integer :: idx_grid
      integer :: unit
      integer :: status
      character(len=*), parameter :: Iam = 'read_geos_binary'
      integer :: npes, deId
      logical :: am_i_root
      type (ESMF_VM) :: vm
      _UNUSED_DUMMY(unusable)
      call ESMF_VMGetCurrent(vm, rc=status)
      _VERIFY(status)
      call ESMF_VmGet(VM, localPet=deId, petCount=npes, rc=status)
      _VERIFY(status)
      am_i_root = (deId == 0)
      if (am_i_root) then
         open(file=file_name, newunit=unit, form='unformatted', iostat=status)
         _VERIFY(status)
      end if
      call read_integer(n_tiles)
      _VERIFY(status)
      tile_file%n_tiles = n_tiles
      call read_integer(n_grids)
      _VERIFY(status)
      _ASSERT(n_grids == 2, 'illegal value for n_grids (must be 2)')
      do idx_grid = 1, n_grids
         call read_tiling_metadata(tile_file%grid_tiles(idx_grid)) ! in
         _VERIFY(status)
      end do
      ! Skip records that are not used here
      if (am_i_root) then
         read(unit) ! skip type
         read(unit) ! skip X
         read(unit) ! skip Y
      end if
      do idx_grid = 1, n_grids ! always 2
         call read_tiling_data(tile_file%n_tiles, tile_file%grid_tiles(idx_grid))
         _VERIFY(status)
      end do
      if (am_i_root) then
         close(unit)
      end if
      _RETURN(_SUCCESS)
   contains
      subroutine read_integer(item)
         integer, intent(out) :: item
         if (am_i_root) then
            read(unit) item
         end if
         call MAPL_CommsBcast(vm, data=item, N=1, root=0, rc=status)
      end subroutine read_integer
      subroutine read_tiling_metadata(tiling, unusable, rc)
         type (GridTiling), intent(out) :: tiling
         class (KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         character(len=MAPL_TileNameLength) :: buffer
         integer :: length
         character(len=*), parameter :: Iam = 'read_tiling_metadata'
         integer :: status
         if (am_i_root) then
            read(unit) buffer
            read(unit) tiling%im
            read(unit) tiling%jm
            length = len(tiling%grid_name)
         end if
         call MAPL_CommsBcast(vm, data=length, N=1, ROOT=0, RC=status)
         _VERIFY(status)
         call MAPL_CommsBcast(vm, data=buffer, N=length, ROOT=0, RC=status)
         _VERIFY(status)
         tiling%grid_name = buffer(1:length)
         call MAPL_CommsBcast(vm, data=tiling%im, N=1, ROOT=0, RC=status)
         _VERIFY(status)
         call MAPL_CommsBcast(vm, data=tiling%jm, N=1, ROOT=0, RC=status)
         _VERIFY(status)
         _RETURN(_SUCCESS)
      end subroutine read_tiling_metadata
      subroutine read_tiling_data(n_tiles, tiling, unusable, rc)
         use MAPL_ShmemMod, only: MAPL_AllocateShared, MAPL_DeallocNodeArray
         use MAPL_CommsMod, only: MAPL_BcastShared
         integer, intent(in) :: n_tiles
         type (GridTiling), intent(inout) :: tiling
         class (KeywordEnforcer), optional, intent(in) :: unusable
         integer, optional, intent(out) :: rc
         real(kind=REAL32), pointer :: buffer(:)
         integer :: length
         character(len=*), parameter :: Iam = 'read_tiling_data'
         integer :: status
         logical :: transroot
         logical :: rootonly_ = .false.
!!$         if (RootOnly_) then
!!$            TransRoot = amIRoot
!!$         else
            TransRoot = .true.
!!$         end if
         call MAPL_AllocateShared(buffer, [n_tiles], TransRoot=TransRoot, rc=status)
         _VERIFY(status)
         if (am_i_root) read(unit) buffer
         call MAPL_BcastShared(vm, data=buffer, N=n_tiles, ROOT=0, RootOnly=RootOnly_, rc=status)
         _VERIFY(status)
         allocate(tiling%i_indices(n_tiles))
         tiling%i_indices = nint(buffer)
         if (am_i_root) read(unit) buffer
         call MAPL_BcastShared(vm, data=buffer, N=n_tiles, ROOT=0, RootOnly=RootOnly_, rc=status)
         _VERIFY(status)
         allocate(tiling%j_indices(n_tiles))
         tiling%j_indices = nint(buffer)
         if (am_i_root) read(unit) buffer
         call MAPL_BcastShared(vm, data=buffer, N=n_tiles, ROOT=0, RootOnly=RootOnly_, rc=status)
         _VERIFY(status)
         allocate(tiling%weights(n_tiles))
         tiling%weights = buffer
         call MAPL_SyncSharedMemory(rc=status)
         _VERIFY(status)
         if (associated(buffer)) then
            _DEALOCS(buffer)
         end if
         _RETURN(_SUCCESS)
      end subroutine read_tiling_data
    end function read_geos_binary
Call graph
read_geos_binary calls ESMF_VMGet, ESMF_VMGetCurrent, grid_tiles, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize_subclass calls read_geos_binary