receive – MAPL
receive Function
16 statements
Source File
private function receive(this, rc) result(message)
Type Bound
MpiSocket
Arguments
Type Intent Optional Attributes Name
class(MpiSocket), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value class(AbstractMessage), pointer
Calls
Called by
Source Code
   function receive(this, rc) result(message)
      class (AbstractMessage), pointer :: message
      class (MpiSocket), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer, allocatable :: buffer(:)
      integer :: ierror
      integer :: status(MPI_STATUS_SIZE)
      integer :: count
      call MPI_Probe(this%pair_remote_rank, MESSAGE_TAG, this%pair_comm, status, ierror)
      call MPI_Get_count(status, MPI_INTEGER, count, ierror)
      allocate(buffer(count))
      call MPI_Recv(buffer, count, MPI_INTEGER, this%pair_remote_rank, MESSAGE_TAG, this%pair_comm, &
           & status, ierror)
      allocate(message, source=this%parser%decode(buffer))
      _RETURN(_SUCCESS)
   end function receive
Call graph
receive calls mpi_get_count, mpi_probe, mpi_recv, decode, mapl_return
decode calls deserialize, m_at
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_throw_exception calls initialize
m_find calls s_find
test_back_and_forth calls receive
test_send_terminate calls receive