receive – MAPL
receive Function
27 statements
Source File
private function receive(this, rc) result(message)
Type Bound
MockSocket
Arguments
Type Intent Optional Attributes Name
class(MockSocket), intent(inout) :: this
integer, intent(out), optional :: rc
Return Value class(AbstractMessage), pointer
Calls
Source Code
   function receive(this, rc) result(message)
      class (AbstractMessage), pointer :: message
      class (MockSocket), intent(inout) :: this
      integer, optional, intent(out) :: rc
      type (MessageVectorIterator) :: iter
      if (this%messages%size() > 0) then
         allocate(message, source= this%messages%front())
         iter = this%messages%begin()
         call this%messages%erase(iter)
         select type (message)
         type is (TerminateMessage)
            call this%prefix('receive<Terminate>')
         type is (DoneMessage)
            call this%prefix('receive<Done>')
         type is (PrefetchDoneMessage)
            call this%prefix('receive<Done_prefetch>')
         type is (AddExtCollectionMessage)
            call this%prefix("receive<AddExtCollection('"//message%template//"')>")
         type is (PrefetchDataMessage)
            call this%prefix("receive<PrefetchData('"//message%var_name//"')>")
         end select
      else
         message => null()
      end if
      _RETURN(_SUCCESS)
   end function receive
Call graph
receive calls erase, mapl_return, prefix, v_begin, v_front
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_erase_one calls erase