receive_output_data – MAPL
receive_output_data Subroutine
22 statements
Source File
private subroutine receive_output_data(this, rc)
Type Bound
MultiCommServer
Arguments
Type Intent Optional Attributes Name
class(MultiCommServer), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine receive_output_data(this, rc)
     class (MultiCommServer),target, intent(inout) :: this
     integer, optional, intent(out) :: rc
     integer :: i, client_num, status
     class (ServerThread),pointer :: threadPtr
     class (AbstractDataReference), pointer :: dataRefPtr
     client_num = this%threads%size()
     if (this%front_comm /= MPI_COMM_NULL) then
       do i = 1, client_num
         threadPtr=>this%threads%at(i)
         call threadPtr%receive_output_data(rc=status)
         _VERIFY(status)
       enddo
     endif
     do i = 1, this%dataRefPtrs%size()
        dataRefPtr => this%get_dataReference(i)
        call dataRefPtr%fence(rc=status)
         _VERIFY(status)
     enddo
     _RETURN(_SUCCESS)
   end subroutine receive_output_data
Call graph
receive_output_data calls at, fence, get_datareference, mapl_return, mapl_verify, receive_output_data, mapl_assert, mpi_put, mpi_type_commit, mpi_type_create_subarray, get_requesthandle, i_to_string, v_begin, v_iter_get, v_iter_next, word_size, push_back
fence calls mapl_return
get_datareference calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
get_requesthandle calls mapl_return, mapl_assert, m_find
i_to_string calls mapl_return, mapl_assert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
word_size calls mapl_return, mapl_assert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
start calls receive_output_data