record_state – MAPL
record_state Subroutine
22 statements
Source File
private subroutine record_state(this, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
integer, intent(out) :: rc
Calls
Contents
Source Code
record_state
Source Code
  subroutine record_state(this, rc)
    class(MAPL_CapGridComp), intent(inout) :: this
    integer, intent(out) :: rc
    integer :: status
    type(MAPL_MetaComp), pointer :: maplobj
    integer :: nalarms,i
    call MAPL_GetObjectFromGC(this%gcs(this%root_id),maplobj,rc=status)
    _VERIFY(status)
    call MAPL_GenericStateSave(this%gcs(this%root_id),this%child_imports(this%root_id), &
           this%child_exports(this%root_id),this%clock,rc=status)
    call ESMF_ClockGet(this%clock,alarmCount=nalarms,rc=status)
    _VERIFY(status)
    allocate(this%alarm_list(nalarms),this%ringingState(nalarms),this%alarmRingTime(nalarms),stat=status)
    _VERIFY(status)
    call ESMF_ClockGetAlarmList(this%clock, alarmListFlag=ESMF_ALARMLIST_ALL, &
         alarmList=this%alarm_list, rc=status)
    _VERIFY(status)
    do i = 1, nalarms
       call ESMF_AlarmGet(this%alarm_list(I), ringTime=this%alarmRingTime(I), ringing=this%ringingState(I), rc=status)
       VERIFY_(STATUS)
    end do
    _RETURN(_SUCCESS)
  end subroutine record_state
Call graph
record_state calls ESMF_AlarmGet, ESMF_ClockGet, ESMF_ClockGetAlarmList, alarm_list, alarmringtime, child_exports, child_imports, gcs, mapl_getobjectfromgc, mapl_vrfy, mapl_genericstatesave, mapl_return, mapl_verify, ringingstate
mapl_getobjectfromgc calls mapl_internalstateget
mapl_genericstatesave calls mapl_genericstatesave, mapl_return, mapl_verify, ESMF_UtilStringLowerCase, get_internal_state, get_num_children, mapl_assert, mapl_getresource, get_child_export_state, get_child_gridcomp, get_child_import_state, mapl_datestampget, mapl_esmfstatewritetofile, mapl_internalstateretrieve
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception