RECT_PMPI – MAPL
RECT_PMPI Function
4 statements
Source File
private function RECT_PMPI(X)
Arguments
Type Intent Optional Attributes Name
real :: X
Return Value real
Called by
Contents
Call graph
mapl_sungetlocalsolarhourangle calls rect_pmpi
mapl_sunorbitcreate calls rect_pmpi
solar_1d calls rect_pmpi, mapl_sungetinsolation
solar_2d calls rect_pmpi, mapl_sungetinsolation
mapl_sungetinsolation calls solar_1d, solar_2d, solar_arr_int
mapl_sunorbitcreatefromconfig calls mapl_sunorbitcreate
mapl_genericstateget calls mapl_sunorbitcreatefromconfig
solar_arr_int calls mapl_sungetinsolation
mapl_get calls mapl_genericstateget
mapl_readforcingx calls mapl_genericstateget