redifine_timeint – MAPL
redifine_timeint Subroutine
56 statements
Source File
private subroutine redifine_timeint(kk, longind, ti, iSat, lat_new, lon_new, t1_new, carylat, carylon, caryt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: kk
real(kind=dp), intent(inout), DIMENSION(:) :: longind
integer, intent(in) :: ti
integer :: iSat
real(kind=dp), intent(inout), DIMENSION(:) :: lat_new
real(kind=dp), intent(inout), DIMENSION(:) :: lon_new
real(kind=dp), intent(inout), DIMENSION(:) :: t1_new
integer, intent(inout) :: carylat
integer, intent(inout) :: carylon
integer, intent(inout) :: caryt
Calls
Contents
Source Code
redifine_timeint
Source Code
SUBROUTINE redifine_timeint(kk, longind, ti, iSat,      &
                 lat_new, lon_new, t1_new, carylat, carylon, caryt)
       IMPLICIT NONE
       REAL(dp), DIMENSION(:), INTENT(INOUT) :: lat_new, lon_new, t1_new
       INTEGER, INTENT(INOUT) :: carylat, carylon, caryt
       REAL(dp), DIMENSION(:), INTENT(INOUT) :: longind
       INTEGER, INTENT(IN)               :: kk
       INTEGER, INTENT(IN)               :: ti
       REAL(dp), DIMENSION(:), ALLOCATABLE   :: t1
       REAL(dp), DIMENSION(:), ALLOCATABLE   :: t1_f, lat_final, lon_final
       REAL(dp), DIMENSION(:,:), ALLOCATABLE :: latestwp, longestwp
       REAL(dp), DIMENSION(:), ALLOCATABLE  :: t_tempo
       REAL(dp), DIMENSION(:,:), ALLOCATABLE:: lat_wayptemp, long_wayptemp
       INTEGER             :: temp1, temp2, temp4, iSat, say, ii, temp_size
       REAL(dp) :: simtimestart_temp, simtimeend_temp, ti_day
       REAL(dp) :: lat_estwayp, lon_estwayp
       ALLOCATE(latestwp(1:carylat,1), longestwp(1:carylon,1), t1(1:caryt))
       latestwp(:,1)   =  lat_new(1:carylat)
       longestwp(:,1)  =  lon_new(1:carylon)
       t1(:)           =  t1_new(1:caryt)
       ti_day = REAL(ti)/(24.0*60.0*60.0)
       temp1 = longind(kk)
       temp2  = longind(kk)+1
       if (temp2 <= size(latestwp,1) ) then
           simtimestart_temp = t1(temp1)
           simtimeend_temp = t1(temp2)
           CALL built_vecsize(simtimestart_temp, simtimeend_temp, &
                              ti_day, say)
           ALLOCATE(t_tempo(1:say))
           CALL built_vec(simtimestart_temp,simtimeend_temp,      &
                              ti_day, t_tempo)
           ALLOCATE(lat_wayptemp(1:size(t_tempo),1) ,             &
                              long_wayptemp(1:size(t_tempo),1) )
           do ii=1,size(t_tempo) ! Calculate carresponding lat lon points
             CALL get_latlon(iSat, t_tempo(ii), lat_estwayp, lon_estwayp)
              lat_wayptemp(ii,1)  = lat_estwayp
                long_wayptemp(ii,1) = lon_estwayp
                  end do
           long_wayptemp = (long_wayptemp-180)
           temp_size = size(t1)+size(t_tempo)-2
           ALLOCATE(t1_f(1:temp_size))
           ALLOCATE(lat_final(1:temp_size))
           ALLOCATE(lon_final(1:temp_size))
           CALL add_newdata(t1, temp1, t_tempo, t1_f)
           CALL add_newdata(latestwp(:,1), temp1, lat_wayptemp(:,1), lat_final)
           CALL add_newdata(longestwp(:,1), temp1, long_wayptemp(:,1), lon_final)
           temp4 = size(lat_wayptemp,1)-2;
           longind(kk+1:size(longind)) = longind(kk+1:size(longind)) + temp4;
           carylat =  size(lat_final)
           carylon =  size(lon_final)
           caryt   =  size(t1_f)
           lat_new(1:carylat) =  lat_final
           lon_new(1:carylon) =  lon_final
           t1_new(1:caryt)    =  t1_f
           DEALLOCATE(t1_f, lat_final, lon_final )
           DEALLOCATE(lat_wayptemp,long_wayptemp)
           DEALLOCATE (t_tempo)
       end if
      DEALLOCATE(latestwp, longestwp, t1)
END SUBROUTINE redifine_timeint
Call graph
redifine_timeint calls built_vecsize, built_vec, add_newdata, get_latlon
get_latlon calls get_estimateeci, get_fraction, ecef2lla, rad2deg, eci2ecef
get_estimateeci calls orbits_track0
orbits_track0 calls orbits_track1, orbits_track2