reduce – MAPL
reduce Subroutine
19 statements
Source File
private subroutine reduce(this)
Type Bound
DistributedProfiler
Arguments
Type Intent Optional Attributes Name
class(DistributedProfiler), intent(inout), target :: this
Calls
Called by
Source Code
   subroutine reduce(this)
      class(DistributedProfiler), target, intent(inout) :: this
      class(AbstractMeterNodeIterator), target, allocatable :: iter
      class(AbstractMeterNode), pointer :: root, node
      class(AbstractMeter), pointer :: m
      root => this%get_root_node()
      iter = root%begin()
      do while (iter /= root%end())
         node => iter%get()
         m => iter%get_meter()
         select type (m)
         class is (DistributedMeter)
            call m%reduce(this%comm, node%get_exclusive())
         class default
            print*,'error - wrong type (other)'
         end select
         call iter%next()
      end do
   end subroutine reduce
Call graph
reduce calls begin, get, get_exclusive, get_meter, next, get_root_node, reduce
main calls reduce, finalize
mapl_genericfinalize calls reduce
report_profile calls reduce
time_ave calls reduce, finalize
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
start calls report_profile
regrid_util calls main
finalize_io_clients_servers calls finalize
ut_regridding calls finalize
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls finalize_io_clients_servers