reduce_global – MAPL
reduce_global Subroutine
5 statements
Source File
private subroutine reduce_global(this, exclusive)
Arguments
Type Intent Optional Attributes Name
class(DistributedMeter), intent(inout) :: this
real(kind=REAL64), intent(in) :: exclusive
Calls
Source Code
   subroutine reduce_global(this, exclusive)
      class(DistributedMeter), intent(inout) :: this
      real(kind=REAL64), intent(in) :: exclusive
      call this%reduce(MPI_COMM_WORLD, exclusive)
   end subroutine reduce_global
Call graph
reduce_global calls reduce
reduce_mpi calls mpi_comm_rank, mpi_reduce, get_max_cycle, get_min_cycle, get_num_cycles, get_sum_square_deviation, get_total, mapl_verify
mapl_verify calls mapl_throw_exception