reduce_mpi – MAPL
reduce_mpi Subroutine
20 statements
Source File
private subroutine reduce_mpi(this, comm, exclusive)
Type Bound
DistributedMeter
Arguments
Type Intent Optional Attributes Name
class(DistributedMeter), intent(inout) :: this
integer, intent(in) :: comm
real(kind=REAL64), intent(in) :: exclusive
Calls
Called by
Source Code
   subroutine reduce_mpi(this, comm, exclusive)
      class(DistributedMeter), intent(inout) :: this
      integer, intent(in) :: comm
      real(kind=REAL64), intent(in) :: exclusive
      integer :: ierror
      integer :: rank
      type(DistributedStatistics) :: tmp
      integer :: rc, status
      call MPI_Comm_rank(comm, rank, ierror)
      _VERIFY(ierror)
      this%statistics%total = DistributedReal64(this%get_total(), rank)
      this%statistics%exclusive = DistributedReal64(exclusive, rank)
      this%statistics%min_cycle = DistributedReal64(this%get_min_cycle(), rank)
      this%statistics%max_cycle = DistributedReal64(this%get_max_cycle(), rank)
      this%statistics%sum_square_deviation = DistributedReal64(this%get_sum_square_deviation(), rank)
      this%statistics%num_cycles = DistributedInteger(this%get_num_cycles(), rank)
      tmp = this%statistics
      call MPI_Reduce(tmp, this%statistics, 1, type_dist_struct, dist_reduce_op, 0, comm, ierror)
      _VERIFY(ierror)
   end subroutine reduce_mpi
Call graph
reduce_mpi calls mpi_comm_rank, mpi_reduce, get_max_cycle, get_min_cycle, get_num_cycles, get_sum_square_deviation, get_total, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
reduce_global calls reduce
test_get_max calls reduce
test_get_min calls reduce
test_get_num_cycles calls reduce
test_get_total calls reduce
test_trivial calls reduce