refresh_state – MAPL
refresh_state Subroutine
14 statements
Source File
private subroutine refresh_state(this, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
integer, intent(out) :: rc
Calls
Contents
Source Code
refresh_state
Source Code
  subroutine refresh_state(this, rc)
    class(MAPL_CapGridComp), intent(inout) :: this
    integer, intent(out) :: rc
    integer :: status
    integer :: i
    call MAPL_GenericStateRestore(this%gcs(this%root_id),this%child_imports(this%root_id), &
             this%child_exports(this%root_id),this%clock,rc=status)
    _VERIFY(status)
    DO I = 1, size(this%alarm_list)
       call ESMF_AlarmSet(this%alarm_list(I), ringTime=this%alarmRingTime(I), ringing=this%ringingState(I), rc=status)
       _VERIFY(STATUS)
    END DO
    _RETURN(_SUCCESS)
  end subroutine refresh_state
Call graph
refresh_state calls ESMF_AlarmSet, alarm_list, alarmringtime, child_exports, child_imports, gcs, mapl_genericstaterestore, mapl_return, mapl_verify, ringingstate
mapl_genericstaterestore calls mapl_genericstaterestore, mapl_return, mapl_verify, ESMF_GridCompGet, get_internal_state, get_num_children, mapl_getresource, mapl_timeron, get_child_export_state, get_child_gridcomp, get_child_import_state, getfile, mapl_esmfstatereadfromfile, mapl_internalstateretrieve
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception