regrid_3d_real32 – MAPL
regrid_3d_real32 Subroutine
28 statements
Source File
private subroutine regrid_3d_real32(this, q_in, q_out, rc)
Type Bound
LocstreamRegridder
Arguments
Type Intent Optional Attributes Name
class(LocstreamRegridder), intent(inout) :: this
real(kind=REAL32), intent(in) :: q_in(:,:,:)
real(kind=REAL32), intent(out) :: q_out(:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine regrid_3d_real32(this,q_in,q_out, rc)
      class(LocstreamRegridder), intent(inout) :: this
      real(kind=REAL32), intent(in) :: q_in(:,:,:)
      real(kind=REAL32), intent(out) :: q_out(:,:)
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: lm
      type(ESMF_Field) :: dst_field,src_field
      real(kind=REAL32), pointer :: p_src(:,:,:),p_dst(:,:)
      _ASSERT(size(q_in,3)==size(q_out,2),"Input and output arrays size inconsistent in 3D locstream regridder")
      lm = size(q_in,3)
      dst_field=ESMF_FieldCreate(this%locstream,typekind=ESMF_TYPEKIND_R4, &
           gridToFieldMap=[2],ungriddedLBound=[1],ungriddedUBound=[lm],rc=status)
      _VERIFY(status)
      src_field=ESMF_FieldCreate(this%grid,typekind=ESMF_TYPEKIND_R4, &
           gridToFieldMap=[2,3],ungriddedLBound=[1],ungriddedUBound=[lm],rc=status)
      _VERIFY(status)
      call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
      _VERIFY(status)
      call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
      _VERIFY(status)
      p_src= reshape(q_in,shape(p_src), order = [2,3,1])
      call ESMF_FieldRegrid(src_field,dst_field,this%route_handle,rc=status)
      _VERIFY(status)
      q_out=reshape(p_dst, shape(q_out), order=[2,1])
      call ESMF_FieldDestroy(dst_field,noGarbage=.true.,rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(src_field,noGarbage=.true.,rc=status)
      _VERIFY(status)
   end subroutine regrid_3d_real32
Call graph
regrid_3d_real32 calls ESMF_FieldRegrid, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_assert, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
append_file calls regrid
regrid_accumulate_on_xsubset calls regrid
run calls append_file