RegridScalar – MAPL
RegridScalar Subroutine
105 statements
Source File
private subroutine RegridScalar(this, itemName, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
character(len=*), intent(in) :: itemName
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine RegridScalar(this,itemName,rc)
        class (MAPL_GriddedIO), intent(inout) :: this
        character(len=*), intent(in) :: itemName
        integer, optional, intent(out) :: rc
        integer :: status
        type(ESMF_Field) :: field,outField
        integer :: fieldRank
        real, pointer :: ptr3d(:,:,:),outptr3d(:,:,:)
        real, pointer :: ptr2d(:,:), outptr2d(:,:)
        real, allocatable, target :: ptr3d_inter(:,:,:)
        type(ESMF_Grid) :: gridIn,gridOut
        logical :: hasDE_in, hasDE_out
        ptr3d => null()
        call ESMF_FieldBundleGet(this%output_bundle,itemName,field=outField,rc=status)
        _VERIFY(status)
        call ESMF_FieldBundleGet(this%input_bundle,grid=gridIn,rc=status)
        _VERIFY(status)
        call ESMF_FieldBundleGet(this%output_bundle,grid=gridOut,rc=status)
        _VERIFY(status)
        hasDE_in = MAPL_GridHasDE(gridIn,rc=status)
        _VERIFY(status)
        hasDE_out = MAPL_GridHasDE(gridOut,rc=status)
        _VERIFY(status)
        if (this%doVertRegrid) then
           call ESMF_FieldBundleGet(this%input_bundle,itemName,field=field,rc=status)
           _VERIFY(status)
           call ESMF_FieldGet(Field,rank=fieldRank,rc=status)
           _VERIFY(status)
           if (fieldRank==3) then
              if (hasDE_in) then
                 call ESMF_FieldGet(field,farrayPtr=ptr3d,rc=status)
                 _VERIFY(status)
              else
                 allocate(ptr3d(0,0,0))
              end if
              allocate(ptr3d_inter(size(ptr3d,1),size(ptr3d,2),this%vdata%lm),stat=status)
              _VERIFY(status)
              if (this%vdata%regrid_type==VERTICAL_METHOD_SELECT) then
                 call this%vdata%regrid_select_level(ptr3d,ptr3d_inter,rc=status)
                 _VERIFY(status)
              else if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
                 call this%vdata%regrid_eta_to_pressure(ptr3d,ptr3d_inter,rc=status)
                 _VERIFY(status)
              else if (this%vdata%regrid_type==VERTICAL_METHOD_FLIP) then
                 call this%vdata%flip_levels(ptr3d,ptr3d_inter,rc=status)
                 _VERIFY(status)
              end if
              ptr3d => ptr3d_inter
           end if
        else
           if (associated(ptr3d)) nullify(ptr3d)
        end if
        call ESMF_FieldBundleGet(this%input_bundle,itemName,field=field,rc=status)
        _VERIFY(status)
        call ESMF_FieldGet(field,rank=fieldRank,rc=status)
        _VERIFY(status)
        if (fieldRank==2) then
           if (hasDE_in) then
              call MAPL_FieldGetPointer(field,ptr2d,rc=status)
              _VERIFY(status)
           else
              allocate(ptr2d(0,0))
           end if
           if (hasDE_out) then
              call MAPL_FieldGetPointer(OutField,outptr2d,rc=status)
              _VERIFY(status)
           else
              allocate(outptr2d(0,0))
           end if
           if (gridIn==gridOut) then
              outPtr2d=ptr2d
           else
              if (this%regrid_method==REGRID_METHOD_FRACTION) ptr2d=ptr2d-this%fraction
              call this%regrid_handle%regrid(ptr2d,outPtr2d,rc=status)
              _VERIFY(status)
           end if
        else if (fieldRank==3) then
           if (.not.associated(ptr3d)) then
              if (hasDE_in) then
                 call ESMF_FieldGet(field,farrayPtr=ptr3d,rc=status)
                 _VERIFY(status)
              else
                 allocate(ptr3d(0,0,0))
              end if
           end if
           if (hasDE_out) then
              call MAPL_FieldGetPointer(OutField,outptr3d,rc=status)
              _VERIFY(status)
           else
              allocate(outptr3d(0,0,0))
           end if
           if (gridIn==gridOut) then
              outPtr3d=Ptr3d
           else
              if (this%regrid_method==REGRID_METHOD_FRACTION) ptr3d=ptr3d-this%fraction
              call this%regrid_handle%regrid(ptr3d,outPtr3d,rc=status)
              _VERIFY(status)
           end if
        else
           _FAIL('rank not supported')
        end if
        if (allocated(ptr3d_inter)) deallocate(ptr3d_inter)
        _RETURN(_SUCCESS)
     end subroutine RegridScalar
Call graph
regridscalar calls esmf_fieldbundleget, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, regrid, flip_levels, mapl_gridhasde, mapl_return, mapl_verify, regrid_eta_to_pressure, regrid_select_level
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar4_1, esmfl_fieldgetptrtodatar4_2, esmfl_fieldgetptrtodatar4_3, esmfl_fieldgetptrtodatar4_4, esmfl_fieldgetptrtodatar8_1, esmfl_fieldgetptrtodatar8_2, esmfl_fieldgetptrtodatar8_3, esmfl_fieldgetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
flip_levels calls mapl_assert, mapl_return
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
regrid_eta_to_pressure calls mapl_return
regrid_select_level calls mapl_return
esmfl_fieldgetptrtodatar4_1 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_4 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_1 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_4 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
regrid_vector_3d_real64 calls mapl_assert, mapl_return
bundlepost calls regridscalar
process_data_from_file calls regridscalar
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
run calls bundlepost
write_to_file calls bundlepost
main calls mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls write_to_file
time_ave calls mapl_read_bundle, write_to_file
ut_regridding calls mapl_read_bundle, write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main