regrid_scalar_2d_real32 – MAPL
regrid_scalar_2d_real32 Subroutine
23 statements
Source File
private subroutine regrid_scalar_2d_real32(this, q_in, q_out, rc)
Type Bound
TilingRegridder
Arguments
Type Intent Optional Attributes Name
class(TilingRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: q_in(:,:)
real(kind=REAL32), intent(out) :: q_out(:,:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_scalar_2d_real32(this, q_in, q_out, rc)
      class (TilingRegridder), intent(in) :: this
      real(kind=REAL32), intent(in) :: q_in(:,:)
      real(kind=REAL32), intent(out) :: q_out(:,:)
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = 'regrid_2d_real32'
      real (kind=REAL32), allocatable :: fraction(:,:)
      type (RegridderSpec) :: spec
      _ASSERT(.not. this%has_undef_value(), 'undefined value')
      call this%init_regrid(q_out)
      allocate(fraction, source = q_out)
      fraction = 0
      spec = this%get_spec()
      if (all(shape(q_out) == this%out_shape)) then
         call this%loop_over_tiles(this%global_x_tiles, q_in, q_out, fraction)
      else
         _ASSERT(iand(spec%hints, REGRID_HINT_LOCAL) /= 0, 'bad hint')
         call this%loop_over_tiles(this%local_x_tiles, q_in, q_out, fraction)
      end if
      call this%final_regrid(q_out, fraction)
      _RETURN(_SUCCESS)
   end subroutine regrid_scalar_2d_real32
Call graph
regrid_scalar_2d_real32 calls mapl_assert, final_regrid, get_spec, has_undef_value, init_regrid, loop_over_tiles, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
loop_over_tiles calls add_contribution
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize