regrid_scalar_2d_real32 – MAPL
regrid_scalar_2d_real32 Subroutine
19 statements
Source File
private subroutine regrid_scalar_2d_real32(this, q_in, q_out, rc)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: q_in(:,:)
real(kind=REAL32), intent(out) :: q_out(:,:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_scalar_2d_real32(this, q_in, q_out, rc)
      class (AbstractRegridder), intent(in) :: this
      real(kind=REAL32), intent(in) :: q_in(:,:)
      real(kind=REAL32), intent(out) :: q_out(:,:)
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME//'regrid_scalar_2d_real32'
      _FAIL( 'unimplemented - must override in subclass')
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(q_in)
      q_out = 0
      _RETURN(_FAILURE)
   end subroutine regrid_scalar_2d_real32
Call graph
regrid_scalar_2d_real32 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize