regrid_accumulate_append_file – MAPL
regrid_accumulate_append_file Module Procedure
118 statements
Source File
module procedure regrid_accumulate_append_file module subroutine regrid_accumulate_append_file(this, current_time, rc) Interface →
write(6,’(2x,a,2x,i5,3x,10f8.1)’) ‘pet, p_dst_3d(j)’, mypet, p_dst_3d(::10)
Arguments
Type Intent Optional Attributes Name
class(MaskSamplerGeosat), intent(inout) :: this
type(ESMF_Time), intent(inout) :: current_time
integer, intent(out), optional :: rc
Calls
Call graph
regrid_accumulate_append_file calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, esmf_fieldget, compute_time_for_current, mapl_am_i_root, mapl_assert, mpi_barrier, mpi_gatherv, put_var, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
put_var_real64_4 calls mapl_return, mapl_verify, nf90_inq_varid, nf90_put_var
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm