regrid_vector_3d_real64 – MAPL
regrid_vector_3d_real64 Subroutine
26 statements
Source File
private subroutine regrid_vector_3d_real64(this, u_in, v_in, u_out, v_out, rc)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(in) :: this
real(kind=REAL64), intent(in) :: u_in(:,:,:)
real(kind=REAL64), intent(in) :: v_in(:,:,:)
real(kind=REAL64), intent(out) :: u_out(:,:,:)
real(kind=REAL64), intent(out) :: v_out(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine regrid_vector_3d_real64(this, u_in, v_in, u_out, v_out, rc)
      class (AbstractRegridder), intent(in) :: this
      real(kind=REAL64), intent(in) :: u_in(:,:,:)
      real(kind=REAL64), intent(in) :: v_in(:,:,:)
      real(kind=REAL64), intent(out) :: u_out(:,:,:)
      real(kind=REAL64), intent(out) :: v_out(:,:,:)
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME//'regrid_vector_3d_real64'
      _FAIL( 'unimplemented - must override in subclass')
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(u_in)
      _UNUSED_DUMMY(v_in)
      u_out = 0
      v_out = 0
      _RETURN(_FAILURE)
   end subroutine regrid_vector_3d_real64
Call graph
regrid_vector_3d_real64 calls mapl_assert, mapl_return, regrid
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_cfioreadbundle calls regrid
mapl_cfioreadbundleread calls regrid
mapl_cfiowritebundlepost calls regrid
mapl_cfiowritebundlewait calls regrid
regrid_esmf_fields_scalar calls regrid
regrid_esmf_fields_vector calls regrid
regrid_scalar_3d_real32 calls regrid
regrid_vector_3d_real32 calls regrid
regridscalar calls regrid
regridvector calls regrid
setup_eta_to_pressure calls regrid
transpose_regrid_esmf_fields_scalar calls regrid
transpose_regrid_esmf_fields_vector calls regrid
transpose_regrid_scalar_2d_real32 calls regrid
transpose_regrid_scalar_2d_real64 calls regrid
transpose_regrid_scalar_3d_real32 calls regrid
transpose_regrid_scalar_3d_real64 calls regrid
transpose_regrid_vector_2d_real32 calls regrid
transpose_regrid_vector_2d_real64 calls regrid
transpose_regrid_vector_3d_real32 calls regrid
transpose_regrid_vector_3d_real64 calls regrid