regrid_accumulate_on_xsubset – MAPL
regrid_accumulate_on_xsubset Module Procedure
97 statements
Source File
module procedure regrid_accumulate_on_xsubset module subroutine regrid_accumulate_on_xsubset(this, rc) Interface →
write(6,’(2x,a,4i10)’) ‘in regrid_accumulate is, ie=’, is, ie
arr(1)=1 if (.NOT. (is > 0 .AND. is <= ie)) arr(1)=0 call ESMF_VMGetGlobal(vm,rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/gridcomps/History/MAPL_HistoryTrajectoryMod_smod.F90”,1044 ,rc)) return call ESMF_VMGet(vm, localPet=mypet, petCount=petCount, rc=status);if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/gridcomps/History/MAPL_HistoryTrajectoryMod_smod.F90”,1045 ,rc)) return call ESMF_VMAllFullReduce(vm, sendData=arr, recvData=nx_sum, & count=1, reduceflag=ESMF_REDUCE_SUM, rc=rc) if (nx_sum == 0) then write(6, ‘(2x,a,2x,3i10)’) ‘invalid points, mypet, is, ie =’, mypet, is, ie ! no valid points to regrid call MAPL_Return(ESMF_SUCCESS,”/home/runner/work/MAPL/MAPL/gridcomps/History/MAPL_HistoryTrajectoryMod_smod.F90”,1051 ,rc); return else write(6, ‘(2x,a,2x,3i10)’) ’ valid points, mypet, is, ie =’, mypet, is, ie end if
print*, ‘size(src,dst,acc)’, size(p_src_2d), size(p_dst_2d), size(p_acc_2d) if (is>0) write(6,’(a)’) ‘regrid_accu: p_dst_2d’ if (is>0) write(6,’(10f7.1)’) p_dst_2d
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Call graph
regrid_accumulate_on_xsubset calls ESMF_ClockGet, esmf_fieldbundleget, esmf_fieldget, get_x_subset, mapl_assert, regrid, mapl_return, mapl_verify, regrid_eta_to_pressure, setup_eta_to_pressure, v_begin, v_iter_get, v_iter_next
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
regrid_eta_to_pressure calls mapl_return
setup_eta_to_pressure calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify, regrid, mapl_gridget
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridget calls mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_GridGet, mapl_gridhasde
mapl_throw_exception calls initialize
regrid_3d_real32 calls esmf_fieldget, mapl_assert, mapl_verify, ESMF_FieldRegrid, esmf_fieldcreate, esmf_fielddestroy