regrid_2d_real32 – MAPL
regrid_2d_real32 Subroutine
25 statements
Source File
private subroutine regrid_2d_real32(this, q_in, q_out, rc)
Type Bound
LocstreamRegridder
Arguments
Type Intent Optional Attributes Name
class(LocstreamRegridder), intent(inout) :: this
real(kind=REAL32), intent(in) :: q_in(:,:)
real(kind=REAL32), intent(out) :: q_out(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_2d_real32(this,q_in,q_out, rc)
      class(LocstreamRegridder), intent(inout) :: this
      real(kind=REAL32), intent(in) :: q_in(:,:)
      real(kind=REAL32), intent(out) :: q_out(:)
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_Field) :: dst_field,src_field
      real(kind=REAL32), pointer :: p_src(:,:),p_dst(:)
      dst_field=ESMF_FieldCreate(this%locstream,typekind=ESMF_TYPEKIND_R4, &
           gridToFieldMap=[1],rc=status)
      _VERIFY(status)
      src_field=ESMF_FieldCreate(this%grid,typekind=ESMF_TYPEKIND_R4, &
           gridToFieldMap=[1,2],rc=status)
      _VERIFY(status)
      call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
      _VERIFY(status)
      call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
      _VERIFY(status)
      p_src=q_in
      call ESMF_FieldRegrid(src_field,dst_field,this%route_handle,rc=status)
      _VERIFY(status)
      q_out=p_dst
      call ESMF_FieldDestroy(dst_field,noGarbage=.true.,rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(src_field,noGarbage=.true.,rc=status)
      _VERIFY(status)
   end subroutine regrid_2d_real32
Call graph
regrid_2d_real32 calls ESMF_FieldRegrid, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize