regrid_select_level – MAPL
regrid_select_level Subroutine
12 statements
Source File
private subroutine regrid_select_level(this, ptrIn, ptrOut, rc)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout) :: this
real, intent(inout) :: ptrIn(:,:,:)
real, intent(inout) :: ptrOut(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine regrid_select_level(this,ptrIn,PtrOut,rc)
        class(verticalData), intent(inout) :: this
        real, intent(inout) :: ptrIn(:,:,:)
        real, intent(inout) :: ptrOut(:,:,:)
        integer, optional, intent(out) :: rc
        integer :: i
        do i=1,size(this%levs)
           ptrOut(:,:,i)=ptrIn(:,:,nint(this%levs(i)))
        enddo
        _RETURN(ESMF_SUCCESS)
     end subroutine regrid_select_level
Call graph
regrid_select_level calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
regridscalar calls regrid_select_level
regridvector calls regrid_select_level
bundlepost calls regridscalar, regridvector
interp_accumulate_fields calls regridscalar, regridvector
process_data_from_file calls regridscalar, regridvector
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls bundlepost, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls write_to_file
time_ave calls mapl_read_bundle, write_to_file
ut_regridding calls mapl_read_bundle, write_to_file