regrid_eta_to_pressure – MAPL
regrid_eta_to_pressure Subroutine
43 statements
Source File
private subroutine regrid_eta_to_pressure(this, ptrin, ptrout, rc)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout), target :: this
real, intent(inout) :: ptrin(:,:,:)
real, intent(inout) :: ptrout(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine regrid_eta_to_pressure(this,ptrin,ptrout,rc)
        class(verticaldata), target, intent(inout) :: this
        real, intent(inout) :: ptrin(:,:,:)
        real, intent(inout) :: ptrout(:,:,:)
        integer, optional, intent(out) :: rc
        real :: weight
        integer :: status
        integer :: i,j,k,lev,levo, D1,D2, km
        integer, pointer :: ks_(:,:,:)
        real, pointer    :: weights_(:,:,:)
        km = size(ptrin,3)
        if (km == this%nedge -1) then
           ks_ => this%ks
           weights_ => this%weight
        else
           ks_ => this%ks_e
           weights_ => this%weight_e
        endif
        D1   = size(ks_,1)
        D2   = size(ks_,2)
        levo = size(ptrout,3)
        ptrout = MAPL_UNDEF
        do lev = 1, levo
          do j = 1, D2
            do i = 1, D1
               k = ks_(i,j,lev)
               if (k == -1) cycle
               !if (k == km) then
               !   ptrout(i,j,lev) = ptrin(i,j,k)
               !   cycle
               !endif
               weight = weights_(i,j,lev)
               if (ptrin(i,j,k)   == MAPL_UNDEF) then
                  ptrout(i,j,lev) = ptrin(i,j,k+1)
                  cycle
               endif
               if (ptrin(i,j,k+1) == MAPL_UNDEF) then
                  ptrout(i,j,lev) = ptrin(i,j,k)
                  cycle
               endif
               ptrout(i,j,lev) = ptrin(i,j,k)*weight + ptrin(i,j,k+1)*(1.0-weight)
            enddo
          enddo
        enddo
        _RETURN(_SUCCESS)
     end subroutine regrid_eta_to_pressure
Call graph
regrid_eta_to_pressure calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
regrid_accumulate_on_xsubset calls regrid_eta_to_pressure
regridscalar calls regrid_eta_to_pressure
regridvector calls regrid_eta_to_pressure
bundlepost calls regridscalar, regridvector
interp_accumulate_fields calls regridscalar, regridvector
process_data_from_file calls regridscalar, regridvector
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls bundlepost, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls write_to_file
time_ave calls mapl_read_bundle, write_to_file
ut_regridding calls mapl_read_bundle, write_to_file