regrid_vector_3d_real64 – MAPL
regrid_vector_3d_real64 Subroutine
90 statements
Source File
private subroutine regrid_vector_3d_real64(this, u_in, v_in, u_out, v_out, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
real(kind=real64), intent(in) :: u_in(:,:,:)
real(kind=real64), intent(in) :: v_in(:,:,:)
real(kind=real64), intent(out) :: u_out(:,:,:)
real(kind=real64), intent(out) :: v_out(:,:,:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
regrid_vector_3d_real64
Source Code
   subroutine regrid_vector_3d_real64(this, u_in, v_in, u_out, v_out, rc)
     class (EsmfRegridder), intent(in) :: this
     real(real64), intent(in) :: u_in(:,:,:)
     real(real64), intent(in) :: v_in(:,:,:)
     real(real64), intent(out) :: u_out(:,:,:)
     real(real64), intent(out) :: v_out(:,:,:)
     integer, optional, intent(out) :: rc
     character(*), parameter :: Iam = 'MAPL_EsmfRegridder::regrid_vector_3d_real64()'
     integer :: status
     type (RegridderSpec) :: spec
     class (AbstractGridFactory), pointer :: factory
     real(real64), pointer :: p_src(:,:,:,:), p_dst(:,:,:,:)
     type (ESMF_Field) :: src_field, dst_field
     character(len=ESMF_MAXSTR) :: grid_axis_in, grid_axis_out
     integer :: km,kin,kout
     integer :: im_src, jm_src
     integer :: im_dst, jm_dst
     logical :: hasDE
     type(ESMF_VM) :: vm
     call ESMF_VMGetCurrent(vm,rc=status)
     _VERIFY(status)
     spec = this%get_spec()
     km = size(u_in,3)
     _ASSERT(km == size(v_in,3),'inconsistent array shape')
      if (size(u_out) /= 0) then
         _ASSERT(km == size(u_out,3),'inconsistent array shape')
         _ASSERT(km == size(v_out,3),'inconsistent array shape')
      end if
     im_src = size(u_in,1)
     jm_src = size(u_in,2)
     _ASSERT(im_src == size(v_in,1),'inconsistent array shape')
     _ASSERT(jm_src == size(v_in,2),'inconsistent array shape')
     im_dst = size(u_out,1)
     jm_dst = size(u_out,2)
     _ASSERT(im_dst == size(v_out,1),'inconsistent array shape')
     _ASSERT(jm_dst == size(v_out,2),'inconsistent array shape')
     grid_axis_in = 'north-south'
     grid_axis_out = 'north-south'
     factory => grid_manager%get_factory(spec%grid_in,rc=status)
     _VERIFY(status)
     hasDE = MAPL_GridHasDE(spec%grid_in,rc=status)
     _VERIFY(status)
     if (hasDE) then
        km = size(u_in,3)
     else
        km = 0
     end if
     call ESMF_VMAllReduce(vm,sendData=km,recvData=kin,reduceFlag=ESMF_REDUCE_MAX,rc=status)
     _VERIFY(status)
     src_field = ESMF_FieldCreate(spec%grid_in, typekind = ESMF_TYPEKIND_R8, &
          & gridToFieldMap=[3,4],ungriddedLBound=[1,1],ungriddedUBound=[3,kin],rc=status)
     _VERIFY(status)
     if (hasDE) then
        call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
        _VERIFY(status)
        call factory%spherical_to_cartesian(u_in, v_in, p_src, grid_axis_in, rc=status)
        _VERIFY(status)
     end if
     hasDE = MAPL_GridHasDE(spec%grid_out,rc=status)
     _VERIFY(status)
     hasDE = MAPL_GridHasDE(spec%grid_out,rc=status)
     _VERIFY(status)
     if (hasDE) then
        km = size(u_out,3)
     else
        km = 0
     end if
     call ESMF_VMAllReduce(vm,sendData=km,recvData=kout,reduceFlag=ESMF_REDUCE_MAX,rc=status)
     _VERIFY(status)
     dst_field = ESMF_FieldCreate(spec%grid_out, typekind = ESMF_TYPEKIND_R8, &
          & gridToFieldMap=[3,4],ungriddedLBound=[1,1],ungriddedUBound=[3,kout],rc=status)
     _VERIFY(status)
     if (hasDE) then
        call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
        _VERIFY(status)
        p_dst = 0
     end if
     call this%do_regrid(src_field, dst_field, rc=status)
     _VERIFY(status)
     factory => grid_manager%get_factory(spec%grid_out,rc=status)
     _VERIFY(status)
     if (hasDE) then
        call factory%cartesian_to_spherical(p_dst, u_out, v_out, grid_axis_out,rc=status)
        _VERIFY(status)
     end if
     call ESMF_FieldDestroy(src_field, noGarbage=.true., rc=status)
     _VERIFY(status)
     call ESMF_FieldDestroy(dst_field, noGarbage=.true., rc=status)
     _VERIFY(status)
     _RETURN(ESMF_SUCCESS)
   end subroutine regrid_vector_3d_real64
Call graph
regrid_vector_3d_real64 calls ESMF_VMAllReduce, ESMF_VMGetCurrent, cartesian_to_spherical, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_assert, do_regrid, get_factory, mapl_gridhasde, mapl_return, mapl_verify, spherical_to_cartesian
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
do_regrid calls esmf_fieldget, get_spec, mapl_assert, mapl_verify, ESMF_FieldRegrid, select_route_handle
get_factory calls get_factory, mapl_return, mapl_verify
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
select_route_handle calls get_spec, mapl_assert, mapl_return, mapl_verify, at, create_route_handle
create_route_handle calls esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_assert, mapl_gridhasde, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, insert