regrid_vector_2d_real32 – MAPL
regrid_vector_2d_real32 Subroutine
25 statements
Source File
private subroutine regrid_vector_2d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
Uses
iso_fortran_env
MAPL_CommsMod
MAPL_BaseMod
Type Bound
IdentityRegridder
Arguments
Type Intent Optional Attributes Name
class(IdentityRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: u_in(:,:)
real(kind=REAL32), intent(in) :: v_in(:,:)
real(kind=REAL32), intent(out) :: u_out(:,:)
real(kind=REAL32), intent(out) :: v_out(:,:)
logical, intent(in), optional :: rotate
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_vector_2d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
      use MAPL_CommsMod
      use MAPL_BaseMod
      use, intrinsic :: iso_fortran_env, only: REAL32
      class (IdentityRegridder), intent(in) :: this
      real(kind=REAL32), intent(in) :: u_in(:,:)
      real(kind=REAL32), intent(in) :: v_in(:,:)
      real(kind=REAL32), intent(out) :: u_out(:,:)
      real(kind=REAL32), intent(out) :: v_out(:,:)
      logical, optional, intent(in) :: rotate
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME//'regrid_vector_3d_real32'
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(rotate)
      u_out = u_in
      v_out = v_in
     _RETURN(_SUCCESS)
   end subroutine regrid_vector_2d_real32
Call graph
regrid_vector_2d_real32 calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize