regrid_scalar_3d_real64 – MAPL
regrid_scalar_3d_real64 Subroutine
11 statements
Source File
private subroutine regrid_scalar_3d_real64(this, q_in, q_out, rc)
Type Bound
TransposeRegridder
Arguments
Type Intent Optional Attributes Name
class(TransposeRegridder), intent(in) :: this
real(kind=REAL64), intent(in) :: q_in(:,:,:)
real(kind=REAL64), intent(out) :: q_out(:,:,:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
regrid_scalar_3d_real64
Source Code
   subroutine regrid_scalar_3d_real64(this, q_in, q_out, rc)
      class (TransposeRegridder), intent(in) :: this
      real(kind=REAL64), intent(in) :: q_in(:,:,:)
      real(kind=REAL64), intent(out) :: q_out(:,:,:)
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME//'regrid_scalar_3d_real64'
      integer :: status
      call this%reference%transpose_regrid(q_in, q_out, rc=status)
      _RETURN(status)
   end subroutine regrid_scalar_3d_real64
Call graph
regrid_scalar_3d_real64 calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize