regrid_accumulate_on_xysubset – MAPL
regrid_accumulate_on_xysubset Subroutine
25 statements
Source File
private subroutine regrid_accumulate_on_xysubset(this, sp, rc)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
class(sampler), intent(inout) :: sp
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine regrid_accumulate_on_xysubset (this, sp, rc)
    class(samplerHQ) :: this
    class(sampler), intent(inout)  :: sp
    integer, intent(out), optional :: rc
    integer :: status
    class(AbstractGridFactory), pointer :: factory
    type(ESMF_Time)            :: timeset(2)
    type(ESMF_Time)            :: current_time
    type(ESMF_TimeInterval)    :: dur
    integer                    :: xy_subset(2,2)
    ! __ s1.  get xy_subset
    call ESMF_ClockGet(this%clock,currTime=current_time,_RC)
    call ESMF_ClockGet(this%clock,timeStep=dur, _RC )
    timeset(1) = current_time - dur
    timeset(2) = current_time
    factory => grid_manager%get_factory(sp%output_grid,_RC)
    call factory%get_xy_subset( timeset, xy_subset, _RC)
    ! __ s2.  interpolate then save data using xy_mask
    call sp%interp_accumulate_fields (xy_subset, _RC)
    _RETURN(ESMF_SUCCESS)
  end subroutine regrid_accumulate_on_xysubset
Call graph
regrid_accumulate_on_xysubset calls ESMF_ClockGet, get_factory, get_xy_subset, interp_accumulate_fields, mapl_return, mapl_verify
get_factory calls mapl_return, mapl_verify, ESMF_AttributeGet, m_at
get_xy_subset calls mapl_return
interp_accumulate_fields calls mapl_return, mapl_verify, ESMF_GridGet, esmf_arrayget, esmf_fieldbundleget, esmf_fieldget, mapl_assert, mapl_gridgetinterior, correct_topo, regridscalar, regridvector, setup_eta_to_pressure, v_begin, v_iter_get, v_iter_next
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls regrid_accumulate_on_xysubset