regrid_vector_3d_real32 – MAPL
regrid_vector_3d_real32 Subroutine
25 statements
Source File
private subroutine regrid_vector_3d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
Type Bound
HorizontalFluxRegridder
Arguments
Type Intent Optional Attributes Name
class(HorizontalFluxRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: u_in(:,:,:)
real(kind=REAL32), intent(in) :: v_in(:,:,:)
real(kind=REAL32), intent(out) :: u_out(:,:,:)
real(kind=REAL32), intent(out) :: v_out(:,:,:)
logical, intent(in), optional :: rotate
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_vector_3d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
      class (HorizontalFluxRegridder), intent(in) :: this
      real(kind=REAL32), intent(in) :: u_in(:,:,:)
      real(kind=REAL32), intent(in) :: v_in(:,:,:)
      real(kind=REAL32), intent(out) :: u_out(:,:,:)
      real(kind=REAL32), intent(out) :: v_out(:,:,:)
      logical, optional, intent(in) :: rotate
      integer, optional, intent(out) :: rc
      integer :: k, status
      _UNUSED_DUMMY(rotate)
      _ASSERT(size(u_in,3) == size(u_out,3), 'mismatch in number of levels')
      _ASSERT(size(v_in,3) == size(v_out,3), 'mismatch in number of levels')
      _ASSERT(size(u_in,3) == size(v_in,3), 'mismatch in number of levels')
      associate (LM => size(u_in,3))
        do k = 1, LM
           call this%regrid(u_in(:,:,k),v_in(:,:,k), u_out(:,:,k), v_out(:,:,k), rotate, rc=status)
           _VERIFY(status)
        end do
      end associate
      _RETURN(ESMF_SUCCESS)
   end subroutine regrid_vector_3d_real32
Call graph
regrid_vector_3d_real32 calls mapl_assert, regrid, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
regrid_vector_3d_real64 calls mapl_assert, mapl_return