regrid_append_file – MAPL
regrid_append_file Module Subroutine
170 statements
Source File
module subroutine regrid_append_file(this, current_time, filename, oClients, rc) Interface →
write(6,’(2x,a,2x,i5,3x,10f8.1)’) ‘pet, p_dst_3d(j)’, mypet, p_dst_3d(::10) this%var3d(ic_3d)%array_xz(1:this%npt_mask_tot, 1:nz) = 99.0
Arguments
Type Intent Optional Attributes Name
class(MaskSampler), intent(inout) :: this
type(ESMF_Time), intent(inout) :: current_time
character(len=*), intent(in) :: filename
type(ClientManager), intent(inout), optional, target :: oClients
integer, intent(out), optional :: rc
Calls
Called by
Source Code
 module subroutine regrid_append_file(this,current_time,filename,oClients,rc)
    implicit none
    class(MaskSampler), intent(inout) :: this
    type(ESMF_Time), intent(inout)          :: current_time
    character(len=*), intent(in) :: filename
    type (ClientManager), target, optional, intent(inout) :: oClients
    integer, optional, intent(out)          :: rc
    !
    integer :: status
    integer :: fieldCount
    integer :: ub(1), lb(1)
    type(ESMF_Field) :: src_field,dst_field
    real(kind=REAL32), pointer :: p_src_3d(:,:,:),p_src_2d(:,:)
    real(kind=REAL32), allocatable :: p_dst_3d(:),p_dst_2d(:)
    real(kind=REAL32), allocatable :: p_dst_3d_full(:),p_dst_2d_full(:)
    real(kind=REAL32), allocatable :: arr(:,:)
    character(len=ESMF_MAXSTR), allocatable ::  fieldNameList(:)
    character(len=ESMF_MAXSTR) :: xname
    real(kind=ESMF_KIND_R8), allocatable :: rtimes(:)
    real(kind=REAL32), allocatable :: rtime(:)
    integer :: i, j, k, rank
    integer :: nx, nz
    integer :: ix, iy, m
    integer :: mypet, petcount, nsend
    integer :: iroot, ierr
    integer :: mpic
    integer :: ic_2d, ic_3d
    integer, allocatable :: recvcounts_3d(:)
    integer, allocatable :: displs_3d(:)
    type(GriddedIOitemVectorIterator) :: iter
    type(GriddedIOitem), pointer :: item
    type(ESMF_VM) :: vm
    type(ArrayReference) :: ref
    this%obs_written=this%obs_written+1
    ! -- fixed for all fields
    call ESMF_VMGetCurrent(vm,_RC)
    call ESMF_VMGet(vm, mpiCommunicator=mpic, petcount=petcount, localpet=mypet, _RC)
    iroot=0
    nx = this%npt_mask
    nz = this%vdata%lm
    allocate(p_dst_2d (nx), _STAT)
    allocate(p_dst_3d (nx * nz), _STAT)
    if (mapl_am_i_root()) then
       allocate ( p_dst_2d_full (this%npt_mask_tot), _STAT )
       allocate ( p_dst_3d_full (this%npt_mask_tot * nz), _STAT )
    else
       allocate ( p_dst_2d_full (0), _STAT )
       allocate ( p_dst_3d_full (0), _STAT )
    end if
    allocate( recvcounts_3d(petcount), displs_3d(petcount), _STAT )
    recvcounts_3d(:) = nz * this%recvcounts(:)
    displs_3d(:)     = nz * this%displs(:)
    !__ 1. put_var: time variable
    !
    allocate( rtimes(1), _STAT )
    rtimes(1) = this%compute_time_for_current(current_time,_RC) ! rtimes: seconds since opening file
    if (mapl_am_i_root()) then
      allocate( rtime(1), _STAT )
      rtime(1) = rtimes(1)
   else
      allocate( rtime(0), _STAT )
   endif
   if (this%use_pfio) then
       this%rtime = rtimes(1)*1.0
       ref = ArrayReference(rtime)
       call oClients%collective_stage_data(this%write_collection_id,trim(filename),'time', &
            ref,start=[1], global_start=[1], global_count=[1])
       call this%stage2DLatLon(trim(filename),oClients=oClients,_RC)
    else
       if (mapl_am_i_root()) then
          call this%formatter%put_var('time',rtimes(1:1),&
               start=[this%obs_written],count=[1],_RC)
          call this%formatter%put_var('longitude',this%lons_deg,_RC)
          call this%formatter%put_var('latitude',this%lats_deg,_RC)
       end if
    end if
    !__ 2. put_var: ungridded_dim from src to dst [use index_mask]
    !
    !   Currently mask only pickup values
    !   It does not support vertical regridding
    !
    !if (this%vdata%regrid_type==VERTICAL_METHOD_ETA2LEV) then
    !   call this%vdata%setup_eta_to_pressure(_RC)
    !endif
    iter = this%items%begin()
    ic_2d = 0
    ic_3d = 0
    do while (iter /= this%items%end())
       item => iter%get()
       if (item%itemType == ItemTypeScalar) then
          call ESMF_FieldBundleGet(this%bundle,trim(item%xname),field=src_field,_RC)
          call ESMF_FieldGet(src_field,rank=rank,_RC)
          if (rank==2) then
             call ESMF_FieldGet(src_field,farrayptr=p_src_2d,_RC)
             do j=1, nx
                ix = this%index_mask(1,j)
                iy = this%index_mask(2,j)
                p_dst_2d(j) = p_src_2d(ix, iy)
             end do
             nsend = nx
             call MPI_gatherv ( p_dst_2d, nsend, MPI_REAL, &
                  p_dst_2d_full, this%recvcounts, this%displs, MPI_REAL,&
                  iroot, mpic, status )
             _VERIFY(status)
             call MAPL_TimerOn(this%GENSTATE,"put2D")
             if (this%use_pfio) then
                ic_2d = ic_2d + 1
                if (mapl_am_i_root()) then
                   this%var2d(ic_2d)%array_x(1:this%npt_mask_tot) = p_dst_2d_full(1:this%npt_mask_tot)
                endif
                ref = ArrayReference(this%var2d(ic_2d)%array_x)
                call oClients%collective_stage_data(this%write_collection_id,trim(filename), item%xname, &
                     ref,start=[1], global_start=[1], global_count=[this%npt_mask_tot])
             else
                if (mapl_am_i_root()) then
                   call this%formatter%put_var(item%xname,p_dst_2d_full,&
                        start=[1,this%obs_written],count=[this%npt_mask_tot,1],_RC)
                end if
             end if
             call MAPL_TimerOff(this%GENSTATE,"put2D")
          else if (rank==3) then
             call ESMF_FieldGet(src_field,farrayptr=p_src_3d,_RC)
             call ESMF_FieldGet(src_field,ungriddedLBound=lb,ungriddedUBound=ub,_RC)
             _ASSERT (this%vdata%lm == (ub(1)-lb(1)+1), 'vertical level is different from CS grid')
             m=0
             do j=1, nx
                ix = this%index_mask(1,j)
                iy = this%index_mask(2,j)
                do k= lb(1), ub(1)
                   m = m + 1
                   p_dst_3d(m) = p_src_3d(ix, iy, k)
                end do
             end do
             !! write(6,'(2x,a,2x,i5,3x,10f8.1)') 'pet, p_dst_3d(j)', mypet, p_dst_3d(::10)
             nsend = nx * nz
             call MPI_gatherv ( p_dst_3d, nsend, MPI_REAL, &
                  p_dst_3d_full, recvcounts_3d, displs_3d, MPI_REAL,&
                  iroot, mpic, status )
             _VERIFY(status)
             call MAPL_TimerOn(this%GENSTATE,"put3D")
             if (this%use_pfio) then
                ic_3d = ic_3d + 1
                if (mapl_am_i_root()) then
                   this%var3d(ic_3d)%array_xz(1:this%npt_mask_tot, 1:nz) = &
                        reshape(p_dst_3d_full,[this%npt_mask_tot, nz],order=[2,1])
!!                   this%var3d(ic_3d)%array_xz(1:this%npt_mask_tot, 1:nz) = 99.0
                endif
                ref = ArrayReference(this%var3d(ic_3d)%array_xz)
                call oClients%collective_stage_data(this%write_collection_id,trim(filename), item%xname, &
                     ref,start=[1,1], global_start=[1,1], global_count=[this%npt_mask_tot, nz])
                     ! 2d: ref,start=[1], global_start=[1], global_count=[this%npt_mask_tot])
             else
                if (mapl_am_i_root()) then
                   allocate(arr(nz, this%npt_mask_tot), _STAT)
                   arr=reshape(p_dst_3d_full,[nz,this%npt_mask_tot],order=[1,2])
                   call this%formatter%put_var(item%xname,arr,&
                        start=[1,1,this%obs_written],count=[nz,this%npt_mask_tot,1],_RC)
                   !note:     lev,location,time
                   deallocate(arr, _STAT)
                end if
             end if
             call MAPL_TimerOff(this%GENSTATE,"put3D")
          else
             _FAIL('grid2LS regridder: rank > 3 not implemented')
          end if
       end if
       call iter%next()
    end do
    _RETURN(_SUCCESS)
  end subroutine regrid_append_file
Call graph
regrid_append_file calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundleget, esmf_fieldget, compute_time_for_current, mapl_am_i_root, mapl_assert, mapl_timeroff, mapl_timeron, stage2dlatlon, mpi_gatherv, put_var, collective_stage_data, mapl_return, mapl_verify, v_begin, v_iter_get, v_iter_next, regrid_append_file
compute_time_for_current calls compute_time_for_current
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_timeroff calls mapl_genericstateclockoff
mapl_timeron calls mapl_genericstateclockon
stage2dlatlon calls stage2dlatlon
collective_stage_data calls mapl_return, mapl_verify, collective_stage_data, current
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls regrid_append_file