regrid_vector_2d_real32 – MAPL
regrid_vector_2d_real32 Subroutine
19 statements
Source File
private subroutine regrid_vector_2d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
Uses
iso_fortran_env
Type Bound
TransposeRegridder
Arguments
Type Intent Optional Attributes Name
class(TransposeRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: u_in(:,:)
real(kind=REAL32), intent(in) :: v_in(:,:)
real(kind=REAL32), intent(out) :: u_out(:,:)
real(kind=REAL32), intent(out) :: v_out(:,:)
logical, intent(in), optional :: rotate
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_vector_2d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
      use, intrinsic :: iso_fortran_env, only: REAL32
      class (TransposeRegridder), intent(in) :: this
      real(kind=REAL32), intent(in) :: u_in(:,:)
      real(kind=REAL32), intent(in) :: v_in(:,:)
      real(kind=REAL32), intent(out) :: u_out(:,:)
      real(kind=REAL32), intent(out) :: v_out(:,:)
      logical, optional, intent(in) :: rotate
      integer, optional, intent(out) :: rc
      character(len=*), parameter :: Iam = MOD_NAME//'regrid_vector_2d_real32'
      integer :: status
      _UNUSED_DUMMY(rotate)
      call this%reference%transpose_regrid(u_in, v_in, u_out, v_out, rc=status)
      _RETURN(status)
   end subroutine regrid_vector_2d_real32
Call graph
regrid_vector_2d_real32 calls transpose_regrid, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
transpose_regrid_vector_3d_real64 calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code