regrid_vector_2d_real64 – MAPL
regrid_vector_2d_real64 Subroutine
49 statements
Source File
private subroutine regrid_vector_2d_real64(this, u_in, v_in, u_out, v_out, rotate, rc)
Type Bound
HorizontalFluxRegridder
Arguments
Type Intent Optional Attributes Name
class(HorizontalFluxRegridder), intent(in) :: this
real(kind=REAL64), intent(in) :: u_in(:,:)
real(kind=REAL64), intent(in) :: v_in(:,:)
real(kind=REAL64), intent(out) :: u_out(:,:)
real(kind=REAL64), intent(out) :: v_out(:,:)
logical, intent(in), optional :: rotate
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine regrid_vector_2d_real64(this, u_in, v_in, u_out, v_out, rotate, rc)
      class (HorizontalFluxRegridder), intent(in) :: this
      real(REAL64), intent(in) :: u_in(:,:)
      real(REAL64), intent(in) :: v_in(:,:)
      real(REAL64), intent(out) :: u_out(:,:)
      real(REAL64), intent(out) :: v_out(:,:)
      logical, optional, intent(in) :: rotate
      integer, optional, intent(out) :: rc
      integer :: i, j, ii, jj
      real(REAL64) :: m_x, m_y
      _UNUSED_DUMMY(rotate)
      _ASSERT(size(u_in,1) == this%IM_in, 'mismatch in IM for input')
      _ASSERT(size(v_in,1) == this%IM_in, 'mismatch in IM for input')
      _ASSERT(size(u_in,2) == this%JM_in, 'mismatch in JM for input')
      _ASSERT(size(v_in,2) == this%JM_in, 'mismatch in JM for input')
      _ASSERT(size(u_out,1) == this%IM_out, 'mismatch in IM for output')
      _ASSERT(size(v_out,1) == this%IM_out, 'mismatch in IM for output')
      _ASSERT(size(u_out,2) == this%JM_out, 'mismatch in JM for output')
      _ASSERT(size(v_out,2) == this%JM_out, 'mismatch in JM for output')
      associate (N => this%resolution_ratio)
        associate (IM => size(u_out,1), JM => size(u_out,2))
          ! aggregate y-fluxes
          do j = 1, JM
             jj = 1 + (j-1)*N
             do i  = 1, IM
                m_y = 0
                do ii = 1 + (i-1)*N, i*N
                   m_y = m_y + v_in(ii,jj)
                end do
                v_out(i,j) = m_y
             end do
          end do
          ! aggregate x-fluxes
          do i = 1, IM
             ii = 1 + (i-1)*N
             do j  = 1, JM
                m_x = 0
                do jj = 1 + (j-1)*N, j*N
                   m_x = m_x + u_in(ii,jj)
                end do
                u_out(i,j) = m_x
             end do
          end do
        end associate
      end associate
      _RETURN(ESMF_SUCCESS)
   end subroutine regrid_vector_2d_real64
Call graph
regrid_vector_2d_real64 calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize