reinitialize – MAPL
reinitialize Module Procedure
78 statements
Source File
module procedure reinitialize module subroutine reinitialize(this, rc) Interface →
Arguments
Type Intent Optional Attributes Name
class(HistoryTrajectory), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
reinitialize calls ESMF_ClockGet, add_attribute, create_variable, esmf_fieldbundleget, get, create_grid, create_new_bundle, get_obsfile_tbracket_from_epoch, mapl_am_i_root, mapl_assert, next, obs, mapl_return, mapl_verify, reinitialize
create_grid calls create_grid
create_new_bundle calls create_new_bundle
get_obsfile_tbracket_from_epoch calls get_obsfile_tbracket_from_epoch
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
destroy_rh_regen_ls calls reinitialize, destroy_rh_regen_ls