release – MAPL
release Subroutine
30 statements
Source File
private subroutine release(this)
Type Bound
MpiMutex
Arguments
Type Intent Optional Attributes Name
class(MpiMutex), intent(inout) :: this
Calls
Contents
Source Code
release
Source Code
   subroutine release(this)
      class (MpiMutex), intent(inout) :: this
      integer :: ierror
      call MPI_Win_lock(MPI_LOCK_EXCLUSIVE, 0, 0, this%window, ierror)
      call MPI_Get(this%local_data, this%npes-1, MPI_LOGICAL, 0, &
           & 0_MPI_ADDRESS_KIND, 1, this%pe_locks_type, this%window, ierror)
      call MPI_Put(.false., 1, MPI_LOGICAL, 0, int(this%rank,kind=MPI_ADDRESS_KIND), &
           & 1, MPI_LOGICAL, this%window, ierror)
      call MPI_Win_unlock(0, this%window, ierror)
      ! who needs the lock next (if anyone)?
      block
        integer :: p, next_rank, buffer
        p = this%rank
        next_rank = -1
        do p = this%rank+1, this%npes-1
           if (this%local_data(p)) then
              next_rank = p
              exit
           end if
        end do
        if (next_rank == -1) then
           do p = 1, this%rank
              if (this%local_data(p)) then
                 next_rank = p-1
                 exit
              end if
           end do
        end if
        if (next_rank /= -1) then
           call MPI_Send(buffer, 0, MPI_LOGICAL, next_rank, &
                & LOCK_TAG, this%comm, ierror)
        end if
      end block
   end subroutine release
Call graph
release calls local_data, mpi_get, mpi_put, mpi_send, mpi_win_lock, mpi_win_unlock