ReleaseSharedMemory – MAPL
ReleaseSharedMemory Module Procedure
22 statements
Source File
module procedure ReleaseSharedMemory module subroutine ReleaseSharedMemory(Caddr, rc) Interface →
! Everyone exits if it is not there
! The root processor destroys the segment
! Everyone detaches address from shared segment
! Make sure everyone has finished detaching
! The root processor destroys the segment
! Free the position in the segment list
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(inout) :: Caddr
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
releasesharedmemory calls segs, shmdt, mapl_assert, shmctl, mpi_barrier, mapl_return, releasesharedmemory
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_deallocnodearray_4dr4 calls releasesharedmemory
mapl_deallocnodearray_5dr8 calls releasesharedmemory
mapl_deallocnodearray_6dr8 calls releasesharedmemory
mapl_deallocnodearray_4di4 calls releasesharedmemory
mapl_deallocnodearray_tiling calls releasesharedmemory
mapl_deallocnodearray_1di4 calls releasesharedmemory
mapl_deallocnodearray_1dl4 calls releasesharedmemory
mapl_deallocnodearray_2di4 calls releasesharedmemory
mapl_deallocnodearray_3di4 calls releasesharedmemory
mapl_deallocnodearray_1dr4 calls releasesharedmemory
mapl_deallocnodearray_2dr4 calls releasesharedmemory
mapl_deallocnodearray_3dr4 calls releasesharedmemory
mapl_deallocnodearray_1dr8 calls releasesharedmemory
mapl_deallocnodearray_2dr8 calls releasesharedmemory
mapl_deallocnodearray_3dr8 calls releasesharedmemory
mapl_deallocnodearray_4dr8 calls releasesharedmemory