remove_attribute – MAPL
remove_attribute Subroutine
11 statements
Source File
private subroutine remove_attribute(this, attr_name, rc)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(inout), target :: this
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Calls
Called by
Call graph
remove_attribute calls erase, m_find, mapl_return, remove_attribute
m_find calls s_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_erase_one calls erase
mapl_throw_exception calls initialize
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan