remove_zero_pad – MAPL
remove_zero_pad Function
16 statements
Source File
private function remove_zero_pad(isostring) result(unpadded)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: isostring
Return Value character(len=len)
Calls
Called by
Source Code
   function remove_zero_pad(isostring) result(unpadded)
      character(len=*), intent(in) :: isostring
      character(len=len(isostring)) :: unpadded
      character(len=:), allocatable :: part(:)
      character(len=len(isostring)) :: fraction_part
      integer :: i
      part = get_ISO8601_substrings(isostring)
      fraction_part = get_ISO8601_fractional_seconds(isostring)
      unpadded = trim(part(1))
      do i = 2, size(part)
         part(i) = strip_zero(part(i))
         unpadded = trim(unpadded) // trim(part(i))
      end do
      fraction_part = strip_zero(fraction_part, back = .TRUE.)
      if(len_trim(fraction_part) > 0) unpadded = trim(unpadded) // DECIMAL_POINT // trim(fraction_part)
   end function remove_zero_pad
Call graph
remove_zero_pad calls get_iso8601_fractional_seconds, get_iso8601_substrings, strip_zero
strip_zero calls is_zero
convert_iso8601_to_cf_time_base_datetime calls remove_zero_pad