RemoveSpaces – MAPL
RemoveSpaces Subroutine
17 statements
Source File
private subroutine RemoveSpaces(str, ipos)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: str
integer, intent(inout), optional :: ipos(:)
Called by
Source Code
  SUBROUTINE RemoveSpaces (str, ipos)
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    ! Remove Spaces from string, remember positions of characters in old string
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    IMPLICIT NONE
    CHARACTER (LEN=*), INTENT(inout) :: str
    INTEGER, OPTIONAL, INTENT(inout) :: ipos(:)
    INTEGER                          :: k,lstr
    !----- -------- --------- --------- --------- --------- --------- --------- -------
    lstr = LEN_TRIM(str)
    if (present(ipos)) ipos = (/ (k,k=1,lstr) /)
    k = 1
    DO WHILE (str(k:lstr) /= ' ')
       IF (str(k:k) == ' ') THEN
          str(k:lstr)  = str(k+1:lstr)//' '                  ! Move 1 character to left
          if (present(ipos)) ipos(k:lstr) = (/ ipos(k+1:lstr), 0 /)  ! Move 1 element to left
          k = k-1
       END IF
       k = k+1
    END DO
  END SUBROUTINE RemoveSpaces
Call graph
checksyntax calls removespaces
parsef calls removespaces, checksyntax
parser_variables_in_expression calls removespaces
get_mask_variables calls parser_variables_in_expression
get_variables_in_expression calls parser_variables_in_expression, get_mask_variables
initialize_ calls checksyntax, fillstate, get_extra_derived_items
mapl_setexpression calls checksyntax
mapl_stateeval calls checksyntax, parsef
calcderivedfield calls mapl_stateeval
evaluate_derived_field calls mapl_stateeval
fillstate calls mapl_stateeval
get_extra_derived_items calls get_variables_in_expression
initialize calls mapl_setexpression
mapl_runexpression calls mapl_stateeval
statefilter_r4_2d calls mapl_stateeval
statefilter_r4_3d calls mapl_stateeval
test_arithmetic_2d calls mapl_stateeval
test_arithmetic_3d calls mapl_stateeval
test_arithmetic_mixed calls mapl_stateeval
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
run calls mapl_runexpression
run_ calls calcderivedfield, fillstate, evaluate_derived_field