replace_metadata_all – MAPL
replace_metadata_all Subroutine
15 statements
Source File
private subroutine replace_metadata_all(this, collection_id, fmd, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
integer, intent(in) :: collection_id
type(FileMetadata), intent(in) :: fmd
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine replace_metadata_all(this, collection_id, fmd, rc)
      class (ClientManager), intent(inout) :: this
      integer, intent(in) :: collection_id
      type (FileMetadata), intent(in) :: fmd
      integer, optional, intent(out) :: rc
      class (ClientThread), pointer :: clientPtr
      integer :: i, status
      do i = 1, this%clients%size()
         ClientPtr => this%clients%at(i)
         call clientPtr%replace_metadata(collection_id, fmd, rc=status)
         _VERIFY(status)
      enddo
      _RETURN(_SUCCESS)
   end subroutine replace_metadata_all
Call graph
replace_metadata_all calls at, mapl_return, mapl_verify, replace_metadata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
replace_metadata calls mapl_return, mapl_verify, get_connection, receive, send
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code