replace_coordinate_data – MAPL
replace_coordinate_data Subroutine
9 statements
Source File
private subroutine replace_coordinate_data(this, coordinate_data, rc)
Type Bound
CoordinateVariable
Arguments
Type Intent Optional Attributes Name
class(CoordinateVariable), intent(inout) :: this
class(*), intent(in) :: coordinate_data(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine replace_coordinate_data(this, coordinate_data,rc)
      class (CoordinateVariable), intent(inout) :: this
      class (*), intent(in) :: coordinate_data(:)
      integer, optional, intent(out) :: rc
      if( allocated(this%coordinate_data)) deallocate(this%coordinate_data)
      allocate(this%coordinate_data, source=coordinate_data)
      _RETURN(_SUCCESS)
   end subroutine replace_coordinate_data
Call graph
replace_coordinate_data calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_iochangeres calls replace_coordinate_data
test_replace_coordinate_data calls replace_coordinate_data
test_serialize calls replace_coordinate_data