replace_metadata – MAPL
replace_metadata Subroutine
16 statements
Source File
private subroutine replace_metadata(this, collection_id, fmd, rc)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(in) :: collection_id
type(FileMetadata), intent(in) :: fmd
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine replace_metadata(this, collection_id, fmd, rc)
      class (ClientThread), intent(inout) :: this
      integer, intent(in) :: collection_id
      type (FileMetadata),intent(in) :: fmd
      integer, optional, intent(out) :: rc
      class (AbstractMessage), pointer :: handshake_msg
      class(AbstractSocket),pointer :: connection
      integer :: status
      connection=>this%get_connection()
      call connection%send(ReplaceMetadataMessage(collection_id,fmd),_RC)
      handshake_msg => connection%receive()
      deallocate(handshake_msg)
      _RETURN(_SUCCESS)
   end subroutine replace_metadata
Call graph
replace_metadata calls get_connection, mapl_return, mapl_verify, receive, send, replace_metadata
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
replace_metadata_all calls replace_metadata