report_profile – MAPL
report_profile Subroutine
37 statements
Source File
private subroutine report_profile(this, RC)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout) :: this
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine report_profile(this, rc )
      class (AbstractServer), intent(inout) :: this
      integer, optional,   intent(  out) :: RC     ! Error code:
      character(:), allocatable :: report_lines(:)
      type (ProfileReporter) :: reporter
      character(1) :: empty(0)
      integer :: i, status
      if ( .not. associated(ioserver_profiler)) then
         _RETURN(_SUCCESS)
      endif
      call ioserver_profiler%stop(_RC)
      call ioserver_profiler%reduce()
      reporter = ProfileReporter(empty)
      call reporter%add_column(NameColumn(20))
      call reporter%add_column(FormattedTextColumn('Inclusive','(f10.2)', 10, InclusiveColumn('MEAN')))
      call reporter%add_column(FormattedTextColumn('% Incl','(f6.2)', 6, PercentageColumn(InclusiveColumn('MEAN'),'MAX')))
      call reporter%add_column(FormattedTextColumn('Exclusive','(f10.2)', 10, ExclusiveColumn('MEAN')))
      call reporter%add_column(FormattedTextColumn('% Excl','(f6.2)', 6, PercentageColumn(ExclusiveColumn('MEAN'))))
      call reporter%add_column(FormattedTextColumn(' Max Excl)','(f10.2)', 10, ExclusiveColumn('MAX')))
      call reporter%add_column(FormattedTextColumn(' Min Excl)','(f10.2)', 10, ExclusiveColumn('MIN')))
      call reporter%add_column(FormattedTextColumn('Max PE)','(1x,i4.4,1x)', 6, ExclusiveColumn('MAX_PE')))
      call reporter%add_column(FormattedTextColumn('Min PE)','(1x,i4.4,1x)', 6, ExclusiveColumn('MIN_PE')))
      report_lines = reporter%generate_report(ioserver_profiler)
      if (this%rank == 0) then
         write(*,'(a)')'Final io_server profile'
         write(*,'(a)')'============='
         do i = 1, size(report_lines)
            write(*,'(a)') report_lines(i)
         end do
         write(*,'(a)') ''
      end if
      deallocate(ioserver_profiler)
      _RETURN(_SUCCESS)
   end subroutine report_profile
Call graph
report_profile calls generate_report, add_column, mapl_return, mapl_verify, reduce
add_column calls get_num_rows_header, get_num_rows_separator, get_width, set_width, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
reduce calls begin, get, get_exclusive, get_meter, next, get_root_node, reduce
generate_report_profiler calls get_root_node, get_width, get_header, get_rows
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_push_back calls resize, v_grow_to
finalize calls report_profile
start calls report_profile
finalize_io_clients_servers calls finalize
main calls finalize
time_ave calls finalize
ut_regridding calls finalize
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls finalize_io_clients_servers, run_ensemble
regrid_util calls main
extdata_driver calls run