RequestedServiceGet – MAPL
RequestedServiceGet Subroutine
23 statements
Source File
public subroutine RequestedServiceGet(request_list, service, bundle, rc)
Arguments
Type Intent Optional Attributes Name
type(requestedServiceItemVector), intent(in) :: request_list
character(len=*), intent(in) :: service
type(ESMF_FieldBundle), intent(out) :: bundle
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine RequestedServiceGet(request_list, service, bundle, rc)
    type(RequestedServiceItemVector), intent(IN) :: request_list
    character(len=*), intent(IN) :: service
    type(ESMF_FieldBundle), intent(OUT) :: bundle
    integer, optional, intent(out) :: rc
    logical :: found
    type (RequestedServiceItemVectorIterator) :: iter
    type (RequestedServiceType), pointer :: item
    _ASSERT(request_list%size()>0,'request_list should not be empty')
    found = .false.
    iter = request_list%begin()
    ! loop over requested services
    do while (iter /= request_list%end())
       item => iter%get()
       if(item%service_name == service) then
          found = .true.
          bundle = item%bundle
          exit
       end if
    END DO
    _ASSERT(found, 'No match found for service')
    _RETURN(_SUCCESS)
  end subroutine RequestedServiceGet
Call graph
requestedserviceget calls mapl_assert, mapl_return, v_begin, v_iter_get
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
mapl_servicegetbundle calls requestedserviceget
mapl_processserviceconnections calls mapl_servicegetbundle
mapl_genericinitialize calls mapl_processserviceconnections
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize