reset – MAPL
reset Subroutine
14 statements
Source File
private recursive subroutine reset(this)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout), target :: this
Calls
Called by
Source Code
   recursive subroutine reset(this)
      class(BaseProfiler), target, intent(inout) :: this
      class(AbstractMeterNodeIterator), allocatable :: iter
      class(AbstractMeterNode), pointer :: node
      class(AbstractMeter), pointer :: t
      !$omp master
      node => this%get_root_node()
      iter = node%begin()
      do while (iter /= node%end())
         t => iter%get_meter()
         call t%reset()
         call iter%next()
      end do
      call this%start()
      !$omp end master
   end subroutine reset
Call graph
reset calls begin, get_meter, next, start, get_root_node, reset
start_self calls start, mapl_assert, get_name, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
test_accumulate_multi calls reset
main calls reset