reset – MAPL
reset Subroutine
9 statements
Source File
private subroutine reset(this)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(inout) :: this
Called by
Source Code
   subroutine reset(this)
      class(AdvancedMeter), intent(inout) :: this
      this%total = 0
      this%active = .false.
      this%num_cycles = 0
      this%min_cycle = huge(1._REAL64)
      this%max_cycle = 0._REAL64
      this%sum_square_deviation = 0._REAL64
   end subroutine reset
Call graph
start_back calls reset
test_accumulate calls reset
test_get_max_cycle calls reset
test_get_mean_cycle calls reset
test_get_min_cycle calls reset
test_get_standard_deviation calls reset
test_reset calls reset
start calls start_back