reset – MAPL
reset Subroutine
14 statements
Source File
private recursive subroutine reset(this)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout), target :: this
Calls
Contents
Source Code
reset
Source Code
   recursive subroutine reset(this)
      class(BaseProfiler), target, intent(inout) :: this
      class(AbstractMeterNodeIterator), allocatable :: iter
      class(AbstractMeterNode), pointer :: node
      class(AbstractMeter), pointer :: t
      !$omp master
      node => this%get_root_node()
      iter = node%begin()
      do while (iter /= node%end())
         t => iter%get_meter()
         call t%reset()
         call iter%next()
      end do
      call this%start()
      !$omp end master
   end subroutine reset
Call graph
reset calls reset, begin, next, get_meter, get_root_node, start
begin calls vector_iter_begin