reset – MAPL
reset Subroutine
12 statements
Source File
private recursive subroutine reset(this)
Type Bound
MeterNode
Arguments
Type Intent Optional Attributes Name
class(MeterNode), intent(inout), target :: this
Calls
Called by
Contents
Source Code
reset
Source Code
   recursive subroutine reset(this)
      class (MeterNode), target, intent(inout) :: this
      type (MeterNodeVectorIterator) :: iter
      class (AbstractMeterNode), pointer :: child
      call this%meter%reset
      iter = this%children%begin()
      do while (iter /= this%children%end())
         child => iter%get()
         call child%reset()
         call iter%next()
      end do
   end subroutine reset
Call graph
reset calls reset, get, next
next calls begin
begin calls meternodeiterator
meternodeiterator calls new_meternodeiterator
accumulate calls reset, accumulate