rewind_model – MAPL
rewind_model Subroutine
10 statements
Source File
private subroutine rewind_model(this, time, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
type(ESMF_Time), intent(inout) :: time
integer, intent(out) :: rc
Calls
Source Code
   subroutine rewind_model(this, time, rc)
     class(MAPL_Cap), intent(inout) :: this
     type(ESMF_Time), intent(inout) :: time
     integer, intent(out) :: rc
     integer :: status
     call this%cap_gc%rewind_clock(time,rc = status); _VERIFY(status)
     _RETURN(_SUCCESS)
   end subroutine rewind_model
Call graph
rewind_model calls mapl_return, mapl_verify, rewind_clock
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
rewind_clock calls mapl_return, mapl_verify, ESMF_ClockAdvance, ESMF_ClockGet, ESMF_ClockSet
get_error_message calls at, insert
mapl_throw_exception calls initialize