rNodeDestroy – MAPL
rNodeDestroy Subroutine
18 statements
Source File
public subroutine rNodeDestroy(List)
Arguments
Type Intent Optional Attributes Name
type(rNode), pointer :: List
Called by
Contents
Source Code
rNodeDestroy
Source Code
   subroutine rNodeDestroy(List)
     type(rNode), pointer :: List, p, q
     if (.not. associated(List)) return
     q => List
     p => List%next
     do while ( associated(p) )
        if (associated(q)) then
           if (associated(q%realData)) deallocate(q%realData)
           deallocate(q)
        end if
        q => p
        p => p%next
     end do
     if (associated(q)) then
        if (associated(q%realData)) deallocate(q%realData)
        deallocate(q)
     end if
   end subroutine rNodeDestroy
Call graph
esmf_cfiovarinfodestroy calls rnodedestroy
esmf_cfiodestroy calls esmf_cfiovarinfodestroy
find calls esmf_cfiodestroy
mapl_cfiodestroy calls esmf_cfiodestroy
mapl_cfioreadbundle calls esmf_cfiodestroy
unfind calls esmf_cfiodestroy
esmf_iodestroy calls mapl_cfiodestroy
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
finalize calls mapl_cfiodestroy
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_simplebundlewrite1 calls mapl_cfiodestroy
mapl_simplebundlewrite2 calls mapl_cfiodestroy