Run – MAPL
Run Subroutine
488 statements
Source File
private subroutine Run(CC, SRC, DST, CLOCK, RC)
Run method for the generic coupler.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CplComp) :: CC
type(ESMF_State) :: SRC
type(ESMF_State) :: DST
type(ESMF_Clock) :: CLOCK
integer, intent(out) :: RC
Calls
Source Code
  subroutine Run(CC, SRC, DST, CLOCK, RC)
! !ARGUMENTS:
    type (ESMF_CplComp)      :: CC
    type (ESMF_State)        :: SRC
    type (ESMF_State)        :: DST
    type (ESMF_Clock)        :: CLOCK
    integer, intent(  OUT)   :: RC
!EOPI
! ErrLog Variables
    character(len=ESMF_MAXSTR)    :: IAm
    character(len=ESMF_MAXSTR)    :: COMP_NAME
    integer                       :: STATUS
! Locals
    type (MAPL_GenericCplState), pointer  :: STATE
    type (MAPL_GenericCplWrap )           :: WRAP
! Begin...
    _UNUSED_DUMMY(CLOCK)
! Get the target components name and set-up traceback handle.
! -----------------------------------------------------------
    Iam = "MAPL_GenericCplCompRun"
    call ESMF_CplCompGet( CC, NAME=COMP_NAME, RC=STATUS )
    _VERIFY(STATUS)
    Iam = trim(COMP_NAME) // Iam
! Retrieve the pointer to the internal state. It comes in a wrapper.
! ------------------------------------------------------------------
    call ESMF_CplCompGetInternalState ( CC, WRAP, STATUS )
    _VERIFY(STATUS)
    STATE     =>  WRAP%INTERNAL_STATE
! If the state is inactive, src and dst are the same
! --------------------------------------------------
    if(STATE%ACTIVE) then
! Make sure SRC and DST descriptors exist
!----------------------------------------
       _ASSERT(associated(STATE%SRC_SPEC),'needs informative message')
       _ASSERT(associated(STATE%DST_SPEC),'needs informative message')
! Update accumulators on SRC grid.
!---------------------------------
       call  ACCUMULATE(SRC, STATE, RC=STATUS)
       _VERIFY(STATUS)
! Periodically transfer accumulators to DST arrays
!-------------------------------------------------
       call  COUPLE    (DST, STATE, RC=STATUS)
       _VERIFY(STATUS)
! Zero accumulators when next averaging interval starts
!------------------------------------------------------
       call ZERO_CLEAR_COUNT(STATE, RC=STATUS)
       _VERIFY(STATUS)
    end if
    _RETURN(ESMF_SUCCESS)
  contains
  subroutine ACCUMULATE(SRC, STATE, RC)
    type (ESMF_State)           :: SRC
    type (MAPL_GenericCplState) :: STATE
    integer, optional           :: RC
! local vars
    integer                               :: J
    integer                               :: I1, I2, I3, I4
    integer                               :: couplerType
    character (len=ESMF_MAXSTR)           :: NAME
    integer                               :: DIMS
    real, pointer                         :: PTR1 (:)
    real, pointer                         :: PTR2 (:,:)
    real, pointer                         :: PTR3 (:,:,:)
    real, pointer                         :: PTR4 (:,:,:,:)
    real, pointer                         :: PTR10(:)
    real, pointer                         :: PTR20(:,:)
    real, pointer                         :: PTR30(:,:,:)
    real, pointer                         :: PTR40(:,:,:,:)
    integer, pointer                      :: PTR1c(:)     => NULL()
    integer, pointer                      :: PTR2c(:,:)   => NULL()
    integer, pointer                      :: PTR3c(:,:,:) => NULL()
    integer, pointer                      :: PTR4c(:,:,:,:) => NULL()
    character(*), parameter       :: IAm="ACCUMULATE"
    integer                       :: STATUS
    do J = 1, size(STATE%SRC_SPEC)
       couplerType = state%couplerType(J)
! Accumulate only if we are in the couplings averaging interval
!--------------------------------------------------------------
       if(STATE%ACCUM_COUNT(J) < 0) cycle
! Get info from the SRC spec
!---------------------------
       call MAPL_VarSpecGet(STATE%SRC_SPEC(J), SHORT_NAME=NAME, RC=STATUS)
       _VERIFY(STATUS)
       DIMS = STATE%ACCUM_RANK(J)
! Process the 3 dimensions
!-------------------------
       select case(DIMS)
       case(4)
          call MAPL_GetPointer  (SRC, PTR4, NAME,            RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR40,RC=STATUS)
          _VERIFY(STATUS)
          PTR4c => STATE%ARRAY_COUNT(J)%PTR4C
          if(.not.associated(PTR4C)) then
             if(  any( PTR4==MAPL_UNDEF ) ) then
                allocate(PTR4C(size(PTR4,1), size(PTR4,2), size(PTR4,3), size(PTR4,4)),STAT=STATUS)
                _VERIFY(STATUS)
                PTR4C = STATE%ACCUM_COUNT(J)
!               put it back into array
                STATE%ARRAY_COUNT(J)%PTR4C => PTR4c
                _VERIFY(STATUS)
             end if
          end if
          if (couplerType == MAPL_CplAverage .or. couplerType == MAPL_CplAccumulate) then
             if(associated(PTR3C)) then
                where (PTR4 /= MAPL_Undef)
                   PTR40 = PTR40 + PTR4
                   PTR4c = PTR4c + 1
                end where
             else
                PTR40 = PTR40 + PTR4
             end if
          else
             DO I1=1,size(PTR4,1)
                DO I2=1,size(PTR4,2)
                   DO I3=1,size(PTR4,3)
                      DO I4=1,size(PTR4,4)
                         if (PTR40(I1,I2,I3,I4)== MAPL_Undef) then
                            PTR40(I1,I2,I3,I4) = PTR4(I1,I2,I3,I4)
                         else
                            if (couplerType == MAPL_CplMax) then
                               PTR40(I1,I2,I3,I4) = max(PTR40(I1,I2,I3,I4),PTR4(I1,I2,I3,I4))
                            else if (couplerType == MAPL_CplMin) then
                               PTR40(I1,I2,I3,I4) = min(PTR40(I1,I2,I3,I4),PTR4(I1,I2,I3,I4))
                            end if
                         end if
                      end DO
                   end DO
                end DO
             end DO
          end if
       case(3)
          call MAPL_GetPointer  (SRC, PTR3, NAME,            RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR30,RC=STATUS)
          _VERIFY(STATUS)
          PTR3c => STATE%ARRAY_COUNT(J)%PTR3C
          if(.not.associated(PTR3C)) then
             if(  any( PTR3==MAPL_UNDEF ) ) then
                allocate(PTR3C(size(PTR3,1), size(PTR3,2), size(PTR3,3)),STAT=STATUS)
                _VERIFY(STATUS)
                PTR3C = STATE%ACCUM_COUNT(J)
!               put it back into array
                STATE%ARRAY_COUNT(J)%PTR3C => PTR3c
                _VERIFY(STATUS)
             end if
          end if
          if (couplerType == MAPL_CplAverage .or. couplerType == MAPL_CplAccumulate) then
             if(associated(PTR3C)) then
                where (PTR3 /= MAPL_Undef)
                   PTR30 = PTR30 + PTR3
                   PTR3c = PTR3c + 1
                end where
             else
                PTR30 = PTR30 + PTR3
             end if
          else
             DO I1=1,size(PTR3,1)
                DO I2=1,size(PTR3,2)
                   DO I3=1,size(PTR3,3)
                      if (PTR30(I1,I2,I3)== MAPL_Undef) then
                         PTR30(I1,I2,I3) = PTR3(I1,I2,I3)
                      else
                         if (couplerType == MAPL_CplMax) then
                            PTR30(I1,I2,I3) = max(PTR30(I1,I2,I3),PTR3(I1,I2,I3))
                         else if (couplerType == MAPL_CplMin) then
                            PTR30(I1,I2,I3) = min(PTR30(I1,I2,I3),PTR3(I1,I2,I3))
                         end if
                      end if
                   end DO
                end DO
             end DO
          end if
       case(2)
          call MAPL_GetPointer  (SRC, PTR2, NAME,            RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR20,RC=STATUS)
          _VERIFY(STATUS)
          PTR2c => STATE%ARRAY_COUNT(J)%PTR2C
          if(.not.associated(PTR2C)) then
             if(  any( PTR2==MAPL_UNDEF ) ) then
                allocate(PTR2C(size(PTR2,1), size(PTR2,2)), STAT=STATUS)
                _VERIFY(STATUS)
                PTR2C = STATE%ACCUM_COUNT(J)
!               put it back into array
                STATE%ARRAY_COUNT(J)%PTR2C => PTR2c
                _VERIFY(STATUS)
             end if
          end if
          if (couplerType == MAPL_CplAverage .or. couplerType == MAPL_CplAccumulate) then
             if(associated(PTR2C)) then
                where (PTR2 /= MAPL_Undef)
                   PTR20 = PTR20 + PTR2
                   PTR2c = PTR2c + 1
                end where
             else
                PTR20 = PTR20 + PTR2
             end if
          else
             DO I1=1,size(PTR2,1)
                DO I2=1,size(PTR2,2)
                   if (PTR20(I1,I2)== MAPL_Undef) then
                      PTR20(I1,I2) = PTR2(I1,I2)
                   else
                      if (couplerType == MAPL_CplMax) then
                         PTR20(I1,I2) = max(PTR20(I1,I2),PTR2(I1,I2))
                      else if (couplerType == MAPL_CplMin) then
                         PTR20(I1,I2) = min(PTR20(I1,I2),PTR2(I1,I2))
                      end if
                   end if
                end DO
             end DO
          endif
       case(1)
          call MAPL_GetPointer  (SRC, PTR1, NAME,            RC=STATUS)
          _VERIFY(STATUS)
          call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR10,RC=STATUS)
          _VERIFY(STATUS)
          PTR1c => STATE%ARRAY_COUNT(J)%PTR1C
          if(.not.associated(PTR1C)) then
             if(  any( PTR1==MAPL_UNDEF ) ) then
                allocate(PTR1C(size(PTR1,1)), STAT=STATUS)
                _VERIFY(STATUS)
                PTR1C = STATE%ACCUM_COUNT(J)
!               put it back into array
                STATE%ARRAY_COUNT(J)%PTR1C => PTR1c
                _VERIFY(STATUS)
             end if
          end if
          if (couplerType == MAPL_CplAverage .or. couplerType == MAPL_CplAccumulate) then
             if(associated(PTR1C)) then
                where (PTR1 /= MAPL_Undef)
                   PTR10 = PTR10 + PTR1
                   PTR1c = PTR1c + 1
                end where
             else
                PTR10 = PTR10 + PTR1
             end if
          else
             DO I1=1,size(PTR1,1)
                if (PTR10(I1)== MAPL_Undef) then
                   PTR10(I1) = PTR1(I1)
                else
                   if (couplerType == MAPL_CplMax) then
                      PTR10(I1) = max(PTR10(I1),PTR1(I1))
                   else if (couplerType == MAPL_CplMin) then
                      PTR10(I1) = min(PTR10(I1),PTR1(I1))
                   end if
                end if
             end DO
          endif
       case default
          _RETURN(ESMF_FAILURE)
       end select
       if(couplerType == MAPL_CplMax .or. couplerType == MAPL_CplMin) then
        STATE%ACCUM_COUNT(J) = 1
       else
        STATE%ACCUM_COUNT(J) = STATE%ACCUM_COUNT(J) + 1
       endif
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine ACCUMULATE
  subroutine ZERO_CLEAR_COUNT(STATE, RC)
    type (MAPL_GenericCplState) :: STATE
    integer, optional           :: RC
! local vars
    integer                               :: J
    integer                               :: DIMS
    logical                               :: RINGING
    real, pointer                         :: PTR10(:)
    real, pointer                         :: PTR20(:,:)
    real, pointer                         :: PTR30(:,:,:)
    real, pointer                         :: PTR40(:,:,:,:)
    character(*), parameter       :: IAm="ZERO_CLEAR_COUNT"
    integer                       :: STATUS
    do J = 1, size(STATE%SRC_SPEC)
       RINGING = ESMF_AlarmIsRinging(STATE%TIME_TO_CLEAR(J), RC=STATUS)
       _VERIFY(STATUS)
       if (RINGING) then
          if(.not.associated(STATE%TIME2CPL_ALARM)) then
             call ESMF_AlarmRingerOff(STATE%TIME_TO_CLEAR(J), RC=STATUS)
             _VERIFY(STATUS)
          end if
          DIMS = STATE%ACCUM_RANK(J)
! Process the 4 dimension possibilities
!--------------------------------------
          select case(DIMS)
          case(4)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR40,RC=STATUS)
             _VERIFY(STATUS)
             if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
                PTR40 = MAPL_UNDEF
             else
                PTR40 = 0.0
             endif
             if (associated(STATE%ARRAY_COUNT(J)%PTR4C)) STATE%ARRAY_COUNT(J)%PTR4C = 0
          case(3)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR30,RC=STATUS)
             _VERIFY(STATUS)
             if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
                PTR30 = MAPL_UNDEF
             else
                PTR30 = 0.0
             endif
             if (associated(STATE%ARRAY_COUNT(J)%PTR3C)) STATE%ARRAY_COUNT(J)%PTR3C = 0
          case(2)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR20,RC=STATUS)
             _VERIFY(STATUS)
             if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
                PTR20 = MAPL_UNDEF
             else
                PTR20 = 0.0
             endif
             if (associated(STATE%ARRAY_COUNT(J)%PTR2C)) STATE%ARRAY_COUNT(J)%PTR2C = 0
          case(1)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR10,RC=STATUS)
             _VERIFY(STATUS)
             if (STATE%couplerType(J) /= MAPL_CplAverage .and. STATE%couplerType(J) /= MAPL_CplAccumulate) then
                PTR10 = MAPL_UNDEF
             else
                PTR10 = 0.0
             endif
             if (associated(STATE%ARRAY_COUNT(J)%PTR1C)) STATE%ARRAY_COUNT(J)%PTR1C = 0
          case default
             _RETURN(ESMF_FAILURE)
          end select
          STATE%ACCUM_COUNT(J) = 0
          if (associated(STATE%ARRAY_COUNT(J)%PTR1C)) then
             deallocate(STATE%ARRAY_COUNT(J)%PTR1C)
             nullify(STATE%ARRAY_COUNT(J)%PTR1C)
          end if
          if (associated(STATE%ARRAY_COUNT(J)%PTR2C)) then
             deallocate(STATE%ARRAY_COUNT(J)%PTR2C)
             nullify(STATE%ARRAY_COUNT(J)%PTR2C)
          end if
          if (associated(STATE%ARRAY_COUNT(J)%PTR3C)) then
             deallocate(STATE%ARRAY_COUNT(J)%PTR3C)
             nullify(STATE%ARRAY_COUNT(J)%PTR3C)
          end if
          if (associated(STATE%ARRAY_COUNT(J)%PTR4C)) then
             deallocate(STATE%ARRAY_COUNT(J)%PTR4C)
             nullify(STATE%ARRAY_COUNT(J)%PTR4C)
          end if
       end if
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine ZERO_CLEAR_COUNT
  subroutine COUPLE(SRC, STATE, RC)
    type (ESMF_State)           :: SRC
    type (MAPL_GenericCplState) :: STATE
    integer, optional           :: RC
! local vars
    integer                               :: J
    character (len=ESMF_MAXSTR)           :: NAME
    integer                               :: DIMS
    real, pointer                         :: PTR1 (:)
    real, pointer                         :: PTR2 (:,:)
    real, pointer                         :: PTR3 (:,:,:)
    real, pointer                         :: PTR4 (:,:,:,:)
    real, pointer                         :: PTR10(:)
    real, pointer                         :: PTR20(:,:)
    real, pointer                         :: PTR30(:,:,:)
    real, pointer                         :: PTR40(:,:,:,:)
    integer, pointer                      :: PTR1c(:)
    integer, pointer                      :: PTR2c(:,:)
    integer, pointer                      :: PTR3c(:,:,:)
    integer, pointer                      :: PTR4c(:,:,:,:)
    logical                               :: RINGING
    integer                               :: couplerType
    character(*), parameter       :: IAm="COUPLE"
    integer                       :: STATUS
    do J = 1, size(STATE%SRC_SPEC)
       couplerType = state%couplerType(J)
       RINGING = ESMF_AlarmIsRinging(STATE%TIME_TO_COUPLE(J), RC=STATUS)
       _VERIFY(STATUS)
       if (RINGING) then
          if(.not.associated(STATE%TIME2CPL_ALARM)) then
             call ESMF_AlarmRingerOff(STATE%TIME_TO_COUPLE(J), RC=STATUS)
             _VERIFY(STATUS)
          end if
          call MAPL_VarSpecGet(STATE%DST_SPEC(J), SHORT_NAME=NAME, RC=STATUS)
          _VERIFY(STATUS)
          DIMS = STATE%ACCUM_RANK(J)
! Process the four dimension possibilities
!------------------------------------------
          select case(DIMS)
          case(4)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR40,RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_GetPointer  (DST, PTR4, NAME,            RC=STATUS)
             _VERIFY(STATUS)
             PTR4c => STATE%ARRAY_COUNT(J)%PTR4C
             if(associated(PTR4C)) then
                if (couplerType /= MAPL_CplAccumulate) then
                   where (PTR4C /= 0)
                      PTR40 = PTR40 / PTR4C
                   elsewhere
                      PTR40 = MAPL_Undef
                   end where
                else
                   where (PTR4C /= 0)
                      PTR40 = PTR40
                   elsewhere
                      PTR40 = MAPL_Undef
                   end where
                end if
             elseif(STATE%ACCUM_COUNT(J)>0) then
                if (couplerType /= MAPL_CplAccumulate) then
                   PTR40 = PTR40 / STATE%ACCUM_COUNT(J)
                else
                   PTR40 = PTR40
                end if
             else
                PTR40 = MAPL_Undef
             end if
! Regrid stubbed
             PTR4 = PTR40
          case(3)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR30,RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_GetPointer  (DST, PTR3, NAME,            RC=STATUS)
             _VERIFY(STATUS)
             PTR3c => STATE%ARRAY_COUNT(J)%PTR3C
             if(associated(PTR3C)) then
                if (couplerType /= MAPL_CplAccumulate) then
                   where (PTR3C /= 0)
                      PTR30 = PTR30 / PTR3C
                   elsewhere
                      PTR30 = MAPL_Undef
                   end where
                else
                   where (PTR3C /= 0)
                      PTR30 = PTR30
                   elsewhere
                      PTR30 = MAPL_Undef
                   end where
                end if
             elseif(STATE%ACCUM_COUNT(J)>0) then
                if (couplerType /= MAPL_CplAccumulate) then
                   PTR30 = PTR30 / STATE%ACCUM_COUNT(J)
                else
                   PTR30 = PTR30
                end if
             else
                PTR30 = MAPL_Undef
             end if
! Regrid stubbed
             PTR3 = PTR30
          case(2)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR20,RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_GetPointer  (DST, PTR2, NAME,            RC=STATUS)
             _VERIFY(STATUS)
             PTR2c => STATE%ARRAY_COUNT(J)%PTR2C
             if(associated(PTR2C)) then
                if (couplerType /= MAPL_CplAccumulate) then
                   where (PTR2C /= 0)
                      PTR20 = PTR20 / PTR2C
                   elsewhere
                      PTR20 = MAPL_Undef
                   end where
                else
                   where (PTR2C /= 0)
                      PTR20 = PTR20
                   elsewhere
                      PTR20 = MAPL_Undef
                   end where
                end if
             elseif(STATE%ACCUM_COUNT(J)>0) then
                if (couplerType /= MAPL_CplAccumulate) then
                   PTR20 = PTR20 / STATE%ACCUM_COUNT(J)
                else
                   PTR20 = PTR20
                end if
             else
                PTR20 = MAPL_Undef
             end if
! Regrid stubbed
             PTR2 = PTR20
          case(1)
             call ESMF_LocalArrayGet(STATE%ACCUMULATORS(J),farrayPtr=PTR10,RC=STATUS)
             _VERIFY(STATUS)
             call MAPL_GetPointer  (DST, PTR1, NAME,            RC=STATUS)
             _VERIFY(STATUS)
             PTR1c => STATE%ARRAY_COUNT(J)%PTR1C
             if(associated(PTR1C)) then
                if (couplerType /= MAPL_CplAccumulate) then
                   where (PTR1C /= 0)
                      PTR10 = PTR10 / PTR1C
                   elsewhere
                      PTR10 = MAPL_Undef
                   end where
                else
                   where (PTR1C /= 0)
                      PTR10 = PTR10
                   elsewhere
                      PTR10 = MAPL_Undef
                   end where
                end if
             elseif(STATE%ACCUM_COUNT(J)>0) then
                if (couplerType /= MAPL_CplAccumulate) then
                   PTR10 = PTR10 / STATE%ACCUM_COUNT(J)
                else
                   PTR10 = PTR10
                end if
             else
                PTR10 = MAPL_Undef
             end if
! Regrid stubbed
             PTR1 = PTR10
          case default
             _RETURN(ESMF_FAILURE)
          end select
          !STATE%ACCUM_COUNT(J) = -1
       end if
    end do
    _RETURN(ESMF_SUCCESS)
  end subroutine COUPLE
 end subroutine Run
Call graph
run calls ESMF_AlarmIsRinging, ESMF_AlarmRingerOff, ESMF_CplCompGet, ESMF_CplCompGetInternalState, esmf_localarrayget, esmfl_stategetpointertodata, mapl_assert, mapl_varspecget, mapl_return, mapl_verify
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecget calls mapl_varspecgetbundleptr, mapl_varspecgetfieldptr, mapl_varspecgetnew, mapl_varspecgetregular, mapl_varspecgetstateptr
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception