run_MAPL_GridComp – MAPL
run_MAPL_GridComp Subroutine
43 statements
Source File
private subroutine run_MAPL_GridComp(gc, phase, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gc
integer, intent(in), optional :: phase
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
run_MAPL_GridComp
Source Code
  subroutine run_MAPL_GridComp(gc, phase, rc)
    type (ESMF_Gridcomp) :: gc
    integer, optional, intent(in)  :: phase
    integer, optional, intent(out) :: rc
    integer :: n, status, phase_
    logical :: done
    type(MAPL_CapGridComp), pointer :: cap
    type (MAPL_MetaComp), pointer :: MAPLOBJ
    procedure(), pointer :: root_set_services
    cap => get_CapGridComp_from_gc(gc)
    call MAPL_GetObjectFromGC(gc, maplobj, rc=status)
    _VERIFY(status)
    phase_ = 1
    if (present(phase)) phase_ = phase
    if (.not. cap%printspec > 0) then
       ! Time Loop starts by checking for Segment Ending Time
       !-----------------------------------------------------
       if (cap%compute_throughput) then
          call ESMF_VMBarrier(cap%vm,rc=status)
          _VERIFY(status)
          cap%starts%loop_start_timer = MPI_WTime(status)
          cap%started_loop_timer = .true.
       end if
       call cap%set_step_counter(0)
       TIME_LOOP: do n = 1, cap%nsteps
          call cap%increment_step_counter()
          call MAPL_MemUtilsWrite(cap%vm, 'MAPL_Cap:TimeLoop', rc = status)
          _VERIFY(status)
          if (.not.cap%lperp) then
             done = ESMF_ClockIsStopTime(cap%clock_hist, rc = status)
             _VERIFY(status)
             if (done) exit
          endif
          call cap%step(phase=phase_, rc=status)
          _VERIFY(status)
          ! Reset loop average timer to get a better
          ! estimate of true run time left by ignoring
          ! initialization costs in the averageing.
          !-------------------------------------------
          if (n == 1 .and. cap%compute_throughput) then
             call ESMF_VMBarrier(cap%vm,rc=status)
             _VERIFY(status)
             cap%starts%loop_start_timer = MPI_WTime(status)
          endif
       enddo TIME_LOOP ! end of time loop
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine run_MAPL_GridComp
Call graph
run_mapl_gridcomp calls get_capgridcomp_from_gc, mapl_verify, mapl_getobjectfromgc, esmf_vmbarrier, mpi_wtime, mapl_memutilswrite, esmf_clockisstoptime, mapl_return
get_capgridcomp_from_gc calls esmf_usercompgetinternalstate
mapl_verify calls mapl_throw_exception
mapl_getobjectfromgc calls mapl_internalstateget
mapl_memutilswrite calls mapl_memutilswritevm, mapl_memutilswritecomm
mapl_return calls mapl_throw_exception, get_error_message
mapl_internalstateget calls mapl_verify, mapl_return, esmf_usercompgetinternalstate, esmf_gridcompget
mapl_memutilswritevm calls mapl_verify, mapl_return, mapl_memutilswritecomm, esmf_vmget
mapl_throw_exception calls initialize
mapl_memutilswritecomm calls mapl_verify, mapl_return, mem_dump, mpi_comm_size, mpi_allreduce, write_parallel
mem_dump calls mapl_verify, mapl_return, get_unit
write_parallel calls write_parallel_i4_1, write_parallel_r4_0, write_parallel_i4_0, write_parallel_r8_0, write_parallel_r4_1, write_parallel_r8_1, write_parallel_string_0
run_gc calls run_mapl_gridcomp