run_model – MAPL
run_model Subroutine
75 statements
Source File
private subroutine run_model(this, comm, unusable, rc)
Uses
pflogger
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
integer, intent(in) :: comm
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run_model(this, comm, unusable, rc)
      use pFlogger, only: logging, Logger
      class (MAPL_Cap), intent(inout) :: this
      integer, intent(in) :: comm
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) ::rc
      integer(kind=INT64) :: start_tick, stop_tick, tick_rate
      integer :: rank, ierror
      integer :: status
      class(Logger), pointer :: lgr
      logical :: file_exists
      type (ESMF_VM) :: vm
      character(len=:), allocatable :: esmfComm
      _UNUSED_DUMMY(unusable)
      call start_timer()
      ! Look for a file called "ESMF.rc" but we want to do this on root and then
      ! broadcast the result to the other ranks
      call MPI_COMM_RANK(comm, rank, ierror)
      if (rank == 0) then
         inquire(file='ESMF.rc', exist=file_exists)
      end if
      call MPI_BCAST(file_exists, 1, MPI_LOGICAL, 0, comm, ierror)
      ! If the file exists, we pass it into ESMF_Initialize, else, we
      ! use the one from the command line arguments
      if (file_exists) then
         call ESMF_Initialize (configFileName='ESMF.rc', mpiCommunicator=comm, vm=vm, _RC)
      else
         call ESMF_Initialize (logKindFlag=this%cap_options%esmf_logging_mode, mpiCommunicator=comm, vm=vm, _RC)
      end if
      ! We check to see if ESMF_COMM was built as mpiuni which is not allowed for MAPL
      call ESMF_VmGet(vm, esmfComm = esmfComm, _RC)
      _ASSERT( esmfComm /= 'mpiuni', 'ESMF_COMM=mpiuni is not allowed for MAPL')
      ! Note per ESMF this is a temporary routine as eventually MOAB will
      ! be the only mesh generator. But until then, this allows us to
      ! test it
      call ESMF_MeshSetMOAB(this%cap_options%with_esmf_moab, rc=status)
      _VERIFY(status)
      lgr => logging%get_logger('MAPL')
      call lgr%info("Running with MOAB library for ESMF Mesh: %l1", this%cap_options%with_esmf_moab)
      call this%initialize_cap_gc(rc=status)
      _VERIFY(status)
      call this%cap_gc%set_services(rc = status)
      _VERIFY(status)
      call this%cap_gc%initialize(rc=status)
      _VERIFY(status)
      call this%cap_gc%run(rc=status)
      _VERIFY(status)
      call this%cap_gc%finalize(rc=status)
      _VERIFY(status)
      call ESMF_Finalize(endflag=ESMF_END_KEEPMPI, rc=status)
      _VERIFY(status)
      call stop_timer()
      call report_throughput()
      _RETURN(_SUCCESS)
   contains
      subroutine start_timer()
         call system_clock(start_tick, count_rate=tick_rate)
      end subroutine start_timer
      subroutine stop_timer()
         call system_clock(stop_tick)
      end subroutine stop_timer
      subroutine report_throughput(rc)
         integer, optional, intent(out) :: rc
         integer :: rank, ierror
         real(kind=REAL64) :: model_duration, wall_time, model_days_per_day
         call MPI_Comm_rank(this%comm_world, rank, ierror)
         _VERIFY(ierror)
         if (rank == 0) then
            model_duration = this%cap_gc%get_model_duration()
            wall_time = (stop_tick - start_tick) / real(tick_rate, kind=REAL64)
            model_days_per_day = model_duration / wall_time
            lgr => logging%get_logger('MAPL.profiler')
            call lgr%info("Model Throughput: %f12.3 days per day", model_days_per_day)
         end if
      end subroutine report_throughput
   end subroutine run_model
Call graph
run_model calls ESMF_Finalize, ESMF_Initialize, ESMF_MeshSetMOAB, ESMF_VMGet, mapl_assert, mpi_bcast, mpi_comm_rank, get_logger, finalize, get_model_duration, info, initialize_cap_gc, initialize, mapl_return, mapl_verify, run, set_services
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
finalize calls mapl_return, mapl_verify, ESMF_GridCompFinalize
get_model_duration calls mapl_return
initialize_cap_gc calls mapl_assert, mapl_return, mapl_verify, get_cap_rc_file, get_egress_file, mapl_capgridcompcreate
initialize calls mapl_return, mapl_verify, ESMF_GridCompInitialize
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls mapl_return, mapl_verify, ESMF_GridCompRun, run_ensemble
set_services calls mapl_return, mapl_verify, esmf_gridcompsetservices
run_member calls run_model
run_ensemble calls run_member