run_one_step – MAPL
run_one_step Subroutine
28 statements
Source File
private subroutine run_one_step(this, rc)
Type Bound
ExtData_DriverGridComp
Arguments
Type Intent Optional Attributes Name
class(ExtData_DriverGridComp), intent(inout) :: this
integer, intent(out) :: rc
Calls
Called by
Contents
Source Code
run_one_step
Source Code
  subroutine run_one_step(this, rc)
    class(ExtData_DriverGridComp), intent(inout) :: this
    integer, intent(out) :: rc
    integer :: AGCM_YY, AGCM_MM, AGCM_DD, AGCM_H, AGCM_M, AGCM_S
    integer :: status
    type(ESMF_Time) :: currTime
    real            :: mem_total, mem_commit, mem_percent
    call ESMF_ClockGet(this%clock, CurrTime = currTime, rc = status)
    _VERIFY(status)
    call ESMF_TimeGet(CurrTime, YY = AGCM_YY, &
         MM = AGCM_MM, &
         DD = AGCM_DD, &
         H  = AGCM_H , &
         M  = AGCM_M , &
         S  = AGCM_S, rc=status)
    _VERIFY(status)
    call ESMF_GridCompGet(this%gc, vm = this%vm)
    ! Run the ExtData Component
    ! --------------------------
    if (this%run_extdata) then
       call ESMF_GridCompRun(this%gcs(this%extdata_id), importState = this%imports(this%extdata_id), &
            exportState = this%exports(this%extdata_id), &
            clock = this%clock, userrc = status)
       _VERIFY(status)
    end if
    ! Run the Gridded Component
    ! --------------------------
    call ESMF_GridCompRun(this%gcs(this%root_id), importstate = this%imports(this%root_id), &
         exportstate = this%exports(this%root_id), &
         clock = this%clock, userrc = status)
    _VERIFY(status)
    ! Call History Run for Output
    ! ---------------------------
    if (this%run_hist) then
       call ESMF_GridCompRun(this%gcs(this%history_id), importstate=this%imports(this%history_id), &
            exportstate = this%exports(this%history_id), &
            clock = this%clock, userrc = status)
       _VERIFY(status)
    end if
    call MAPL_MemCommited ( mem_total, mem_commit, mem_percent, RC=STATUS )
    if (this%AmIRoot) write(6,1000) AGCM_YY,AGCM_MM,AGCM_DD,AGCM_H,AGCM_M,AGCM_S,mem_percent
1000 format(1x,'TestDriver Date: ',i4.4,'/',i2.2,'/',i2.2,2x,'Time: ',i2.2,':',i2.2,':',i2.2,2x,f5.1,'%Memory Committed')
    _RETURN(ESMF_SUCCESS)
  end subroutine run_one_step
Call graph
run_one_step calls ESMF_ClockGet, ESMF_GridCompGet, ESMF_GridCompRun, ESMF_TimeGet, exports, gcs, imports, mapl_memcommited, mapl_return, mapl_verify
mapl_memcommited calls mapl_return, mapl_rtrn, get_unit
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
run_multipletimes calls run_one_step
run_gc calls run_multipletimes