run_member – MAPL
run_member Subroutine
15 statements
Source File
private subroutine run_member(this, rc)
Uses
MAPL_CFIOMod
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
run_member
Source Code
   subroutine run_member(this, rc)
      use MAPL_CFIOMod
      class (MAPL_Cap), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      type(SplitCommunicator) :: split_comm
      call this%cap_server%get_splitcomm(split_comm)
      select case(split_comm%get_name())
      case('model')
         call this%run_model(comm=split_comm%get_subcommunicator(), rc=status); _VERIFY(status)
      end select
     _RETURN(_SUCCESS)
   end subroutine run_member
Call graph
run_member calls get_name, get_subcommunicator, mapl_return, mapl_verify, run_model
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_model calls mapl_return, mapl_verify, ESMF_Finalize, ESMF_Initialize, ESMF_MeshSetMOAB, get_logger, info, mpi_bcast, mpi_comm_rank, initialize_cap_gc
get_error_message calls at
initialize_cap_gc calls mapl_return, mapl_verify, mapl_assert, get_cap_rc_file, get_egress_file, mapl_capgridcompcreate
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_capgridcompcreate calls mapl_return, mapl_verify, mapl_assert, ESMF_ConfigCreate, ESMF_ConfigLoadFile, ESMF_GridCompCreate, ESMF_UserCompSetInternalState, mapl_set, mapl_internalstatecreate
run_ensemble calls run_member
run calls run_ensemble