run_child – MAPL
run_child Subroutine
14 statements
Source File
private subroutine run_child(this, name, clock, phase, unusable, rc)
Type Bound
DecoratorComponent
Arguments
Type Intent Optional Attributes Name
class(DecoratorComponent), intent(inout) :: this
character(len=*), intent(in) :: name
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in) :: phase
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine run_child(this, name, clock, phase, unusable, rc)
      class(DecoratorComponent), intent(inout) :: this
      character(*), intent(in) :: name
      type(ESMF_Clock), intent(inout) :: clock
      character(*), intent(in) :: phase
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      call this%decorated%run_child(name, clock, phase, _RC)
      _RETURN(_SUCCESS)
   end subroutine run_child
Call graph
run_child calls mapl_return, mapl_verify, run_child
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize