run_gc – MAPL
run_gc Subroutine
21 statements
Source File
private subroutine run_gc(GC, import, export, clock, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: GC
type(ESMF_State) :: import
type(ESMF_State) :: export
type(ESMF_Clock) :: clock
integer, intent(out) :: RC
Calls
Contents
Source Code
run_gc
Source Code
  subroutine run_gc(gc, import, export, clock, rc)
    !ARGUMENTS:
    type(ESMF_GridComp) :: GC     ! Gridded component
    type(ESMF_State) :: import ! Import state
    type(ESMF_State) :: export ! Export state
    type(ESMF_Clock) :: clock  ! The clock
    integer, intent(out) :: RC     ! Error code:
    integer :: status, phase
    class (BaseProfiler), pointer :: t_p
    _UNUSED_DUMMY(import)
    _UNUSED_DUMMY(export)
    _UNUSED_DUMMY(clock)
    t_p => get_global_time_profiler()
    call t_p%start('Run')
    call ESMF_GridCompGet( gc, currentPhase=phase, RC=status )
    VERIFY_(status)
    call run_MAPL_GridComp(gc, phase=phase, rc=status)
    _VERIFY(status)
    call t_p%stop('Run')
    _RETURN(ESMF_SUCCESS)
  end subroutine run_gc
Call graph
run_gc calls get_global_time_profiler, mapl_verify, esmf_gridcompget, run_mapl_gridcomp, mapl_vrfy, mapl_return
mapl_verify calls mapl_throw_exception
run_mapl_gridcomp calls mapl_verify, mapl_return, mapl_getobjectfromgc, esmf_vmbarrier, mpi_wtime, get_capgridcomp_from_gc, mapl_memutilswrite, esmf_clockisstoptime
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_getobjectfromgc calls mapl_internalstateget
get_capgridcomp_from_gc calls esmf_usercompgetinternalstate
mapl_memutilswrite calls mapl_memutilswritevm, mapl_memutilswritecomm
mapl_internalstateget calls mapl_verify, esmf_gridcompget, mapl_return, esmf_usercompgetinternalstate
mapl_memutilswritevm calls mapl_verify, mapl_return, mapl_memutilswritecomm, esmf_vmget
mapl_memutilswritecomm calls mapl_verify, mapl_return, mem_dump, write_parallel, mpi_comm_size, mpi_allreduce