run_ensemble – MAPL
run_ensemble Subroutine
20 statements
Source File
private subroutine run_ensemble(this, unusable, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
run_ensemble
Source Code
   subroutine run_ensemble(this, unusable, rc)
      class (MAPL_Cap), target, intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: subcommunicator
      _UNUSED_DUMMY(unusable)
      subcommunicator = this%create_member_subcommunicator(this%comm_world, rc=status); _VERIFY(status)
      if (subcommunicator /= MPI_COMM_NULL) then
         call this%initialize_io_clients_servers(subcommunicator, rc = status); _VERIFY(status)
         call this%run_member(rc=status); _VERIFY(status)
         call this%finalize_io_clients_servers()
         call this%splitter%free_sub_comm()
      end if
      _RETURN(_SUCCESS)
   end subroutine run_ensemble
Call graph
run_ensemble calls create_member_subcommunicator, finalize_io_clients_servers, initialize_io_clients_servers, mapl_return, mapl_verify, run_member
create_member_subcommunicator calls mapl_return, mapl_verify, get_name, get_subcommunicator, c_chdir
finalize_io_clients_servers calls mapl_return, get_name, terminate
initialize_io_clients_servers calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_member calls mapl_return, mapl_verify, get_name, get_subcommunicator, run_model
get_error_message calls at
mapl_throw_exception calls initialize
run_model calls mapl_return, mapl_verify, ESMF_Finalize, ESMF_Initialize, ESMF_MeshSetMOAB, get_logger, info, mpi_bcast, mpi_comm_rank, initialize_cap_gc
initialize_cap_gc calls mapl_return, mapl_verify, mapl_assert, get_cap_rc_file, get_egress_file, mapl_capgridcompcreate
run calls run_ensemble