Run_ – MAPL
Run_ Subroutine
169 statements
Source File
private subroutine Run_(GC, IMPORT, EXPORT, CLOCK, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
type(ESMF_State), intent(inout) :: IMPORT
type(ESMF_State), intent(inout) :: EXPORT
type(ESMF_Clock), intent(inout) :: CLOCK
integer, intent(out) :: rc
Calls
Contents
Source Code
Run_
Source Code
   SUBROUTINE Run_ ( GC, IMPORT, EXPORT, CLOCK, rc )
! !USES:
  implicit NONE
! !INPUT PARAMETERS:
   type(ESMF_Clock),  intent(inout) :: CLOCK     ! The clock
! !OUTPUT PARAMETERS:
   type(ESMF_GridComp), intent(inout)  :: GC     ! Grid Component
   type(ESMF_State), intent(inout) :: IMPORT     ! Import State
   type(ESMF_State), intent(inout) :: EXPORT     ! Export State
   integer, intent(out) ::  rc                   ! Error return code:
                                                 !  0 - all is well
                                                 !  1 -
! !DESCRIPTION: This is a simple ESMF wrapper.
!
! !REVISION HISTORY:
!
!  12Dec2009  da Silva  Design and first implementation.
!
!EOP
!-------------------------------------------------------------------------
   type(MAPL_ExtData_state), pointer :: self        ! Legacy state
   type(ESMF_Config)                 :: CF          ! Universal Config
   character(len=ESMF_MAXSTR)        :: comp_name
   integer                           :: status
   type(PrimaryExport), pointer      :: item
   type(DerivedExport), pointer      :: derivedItem
   integer                           :: i
   type(ESMF_Time)                   :: use_time, current_time
   type(MAPL_MetaComp), pointer      :: MAPLSTATE
   logical                           :: doUpdate_
   character(len=ESMF_MAXPATHLEN)    :: file_processed
   logical, allocatable              :: do_pointer_update(:)
   type(ESMF_Time), allocatable      :: useTime(:)
   integer                           :: bracket_side
   integer                           :: entry_num
   type(IOBundleNGVector), target     :: IOBundles
   type(IOBundleNGVectorIterator) :: bundle_iter
   type(ExtDataNG_IOBundle), pointer :: io_bundle
   character(len=:), pointer :: current_base_name
   integer :: idx,nitems
   type(ESMF_Config) :: cf_master
   type(ESMF_Time) :: adjusted_time
   _UNUSED_DUMMY(IMPORT)
   _UNUSED_DUMMY(EXPORT)
!  Get my name and set-up traceback handle
!  ---------------------------------------
   call ESMF_GridCompGet( GC, name=comp_name, config=CF_master, _RC )
!  Extract relevant runtime information
!  ------------------------------------
   call extract_ ( GC, self, CF, _RC )
   if (.not. self%active) then
      _RETURN(ESMF_SUCCESS)
   end if
   call MAPL_GetObjectFromGC ( gc, MAPLSTATE, RC=STATUS)
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"TOTAL")
   call MAPL_TimerOn(MAPLSTATE,"Run")
   call ESMF_ClockGet(CLOCK, currTIME=current_time, _RC)
!  Fill in the internal state with data from the files
!  ---------------------------------------------------
   allocate(do_pointer_update(self%primary%nitems),stat=status)
   _VERIFY(STATUS)
   do_pointer_update = .false.
   allocate(useTime(self%primary%nitems),stat=status)
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"-Read_Loop")
   call extdata_lgr%debug('ExtData Rune_(): Start')
   call extdata_lgr%debug('ExtData Run_(): READ_LOOP: Start')
   READ_LOOP: do i=1,self%primary%import_names%size()
      current_base_name => self%primary%import_names%at(i)
      idx = self%primary%get_item_index(current_base_name,current_time,_RC)
      item => self%primary%item(idx)
      if (.not.item%initialized) then
         item%pfioCollection_id = MAPL_DataAddCollection(item%file_template)
         if (item%isConst) then
            call set_constant_field(item,self%extDataState,_RC)
            cycle
         end if
         item%initialized=.true.
      end if
      nitems = self%primary%import_names%size()
      !call extdata_lgr%debug('ExtData Run_(): READ_LOOP: variable %i0 of %i0~: %a', i, nitems, trim(current_base_name))
      !call extdata_lgr%debug('   ==> file: %a', trim(item%file_template))
      !call extdata_lgr%debug('   ==> isConst:: %l1', item%isConst)
      if (item%isConst) then
         call extdata_lgr%debug('   ==> Break loop since isConst is true')
         cycle
      endif
      call MAPL_TimerOn(MAPLSTATE,"--CheckUpd")
      call item%update_freq%check_update(do_pointer_update(i),use_time,current_time,.not.hasRun,_RC)
      adjusted_time = item%update_freq%get_adjusted_time(current_time)
      call MAPL_TimerOff(MAPLSTATE,"--CheckUpd")
      !call extdata_lgr%info('Going to update %a with file template: %a ',current_base_name, item%file_template)
      call item%modelGridFields%comp1%reset()
      call item%filestream%get_file_bracket(use_time,item%source_time, item%modelGridFields%comp1,item%fail_on_missing_file, _RC)
      if (item%vartype == MAPL_VectorField) then
         call item%filestream%get_file_bracket(use_time,item%source_time, item%modelGridFields%comp2, item%fail_on_missing_file,_RC)
      end if
      call create_bracketing_fields(item,self%ExtDataState,cf_master, _RC)
      call IOBundle_Add_Entry(IOBundles,item,idx)
      useTime(i)=use_time
   end do READ_LOOP
   call extdata_lgr%debug('ExtData Run_: READ_LOOP: Done')
   bundle_iter = IOBundles%begin()
   do while (bundle_iter /= IoBundles%end())
      io_bundle => bundle_iter%get()
      bracket_side = io_bundle%bracket_side
      entry_num = io_bundle%entry_index
      file_Processed = io_bundle%file_name
      item => self%primary%item(entry_num)
      io_bundle%pbundle = ESMF_FieldBundleCreate(rc=status)
      _VERIFY(STATUS)
      call MAPL_ExtDataPopulateBundle(item,bracket_side,io_bundle%pbundle,rc=status)
      _VERIFY(status)
      call bundle_iter%next()
   enddo
   call MAPL_TimerOn(MAPLSTATE,"--PRead")
   call MAPL_TimerOn(MAPLSTATE,"---CreateCFIO")
   call MAPL_ExtDataCreateCFIO(IOBundles, rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"---CreateCFIO")
   call MAPL_TimerOn(MAPLSTATE,"---prefetch")
   call MAPL_ExtDataPrefetch(IOBundles, rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"---prefetch")
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"---IclientDone")
   call i_Clients%done_collective_prefetch()
   call i_Clients%wait()
   call MAPL_TimerOff(MAPLSTATE,"---IclientDone")
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"---read-prefetch")
   call MAPL_ExtDataReadPrefetch(IOBundles,rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"---read-prefetch")
   call MAPL_TimerOff(MAPLSTATE,"--PRead")
   bundle_iter = IOBundles%begin()
   do while (bundle_iter /= IOBundles%end())
      io_bundle => bundle_iter%get()
      bracket_side = io_bundle%bracket_side
      entry_num = io_bundle%entry_index
      item => self%primary%item(entry_num)
      call MAPL_ExtDataVerticalInterpolate(self,item,bracket_side,current_time,rc=status)
      _VERIFY(status)
      call bundle_iter%next()
   enddo
   call MAPL_ExtDataDestroyCFIO(IOBundles,rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"-Read_Loop")
   call MAPL_TimerOn(MAPLSTATE,"-Interpolate")
   call extdata_lgr%debug('ExtData Run_: INTERP_LOOP: Start')
   INTERP_LOOP: do i=1,self%primary%import_names%size()
      current_base_name => self%primary%import_names%at(i)
      idx = self%primary%get_item_index(current_base_name,current_time,_RC)
      item => self%primary%item(idx)
      if (do_pointer_update(i)) then
         call extdata_lgr%debug('ExtData Run_: INTERP_LOOP: interpolating between bracket times, variable: %a, file: %a', &
              & trim(current_base_name), trim(item%file_template))
         call MAPL_ExtDataInterpField(item,self%ExtDataState,useTime(i),_RC)
      endif
      nullify(item)
   end do INTERP_LOOP
   call extdata_lgr%debug('ExtData Run_: INTERP_LOOP: Done')
   call MAPL_TimerOff(MAPLSTATE,"-Interpolate")
   ! now take care of derived fields
   do i=1,self%derived%nItems
      derivedItem => self%derived%item(i)
      call derivedItem%update_freq%check_update(doUpdate_,use_time,current_time,.not.hasRun,_RC)
      if (doUpdate_) then
         call derivedItem%evaluate_derived_field(self%ExtDataState,_RC)
      end if
   end do
   call extdata_lgr%debug('ExtData Run_: End')
!  All done
!  --------
   deallocate(useTime)
   if (hasRun .eqv. .false.) hasRun = .true.
   call MAPL_TimerOff(MAPLSTATE,"Run")
   call MAPL_TimerOff(MAPLSTATE,"TOTAL")
   _RETURN(ESMF_SUCCESS)
   END SUBROUTINE Run_
Call graph
run_ calls mapl_extdatainterpfield, iobundle_add_entry, mapl_extdatadestroycfio, esmf_gridcompget, mapl_extdatareadprefetch, mapl_extdatapopulatebundle, mapl_verify, extract_, mapl_dataaddcollection, set_constant_field, mapl_extdatacreatecfio, mapl_extdataverticalinterpolate, mapl_timeroff, mapl_extdataprefetch, mapl_return, esmf_fieldbundlecreate, mapl_getobjectfromgc, create_bracketing_fields, mapl_timeron, esmf_clockget