run_MultipleTimes – MAPL
run_MultipleTimes Subroutine
48 statements
Source File
private subroutine run_MultipleTimes(gc, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gc
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
run_MultipleTimes
Source Code
  subroutine run_MultipleTimes(gc, rc)
    type (ESMF_Gridcomp) :: gc
    integer, optional, intent(out) :: rc
    integer :: n, status
    type(ExtData_DriverGridComp), pointer :: cap
    type (MAPL_MetaComp), pointer :: MAPLOBJ
    procedure(), pointer :: root_set_services
    cap => get_CapGridComp_from_gc(gc)
    MAPLOBJ => get_MetaComp_from_gc(gc)
    if (allocated(cap%times)) then
       do n=1,size(cap%times)
          call cap%AdvanceClockToTime(cap%times(n),rc=status)
          _VERIFY(status)
          call cap%run_one_step(status)
          _VERIFY(status)
       enddo
    else if (cap%run_fbf) then
       do n=1,cap%nsteps
          call ESMF_ClockAdvance(cap%clock,rc=status)
          _VERIFY(status)
          call cap%run_one_step(status)
          _VERIFY(status)
       enddo
       if (mapl_am_i_root()) write(*,*)"Rewinding Clock"
       call ESMF_ClockSet(cap%clock,direction=ESMF_DIRECTION_REVERSE,_RC)
       do n=1,cap%nsteps
          call ESMF_ClockAdvance(cap%clock,rc=status)
       enddo
       call ESMF_ClockSet(cap%clock,direction=ESMF_DIRECTION_FORWARD,_RC)
       do n=1,cap%nsteps
          call ESMF_ClockAdvance(cap%clock,rc=status)
          _VERIFY(status)
          call cap%run_one_step(status)
          _VERIFY(status)
       enddo
    else
       do n=1,cap%nsteps
          call ESMF_ClockAdvance(cap%clock,rc=status)
          _VERIFY(status)
          call cap%run_one_step(status)
          _VERIFY(status)
       enddo
    endif
    _RETURN(ESMF_SUCCESS)
  end subroutine run_MultipleTimes
Call graph
run_multipletimes calls ESMF_ClockAdvance, ESMF_ClockSet, mapl_am_i_root, advanceclocktotime, get_capgridcomp_from_gc, get_metacomp_from_gc, mapl_return, mapl_verify, run_one_step, times
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
advanceclocktotime calls ESMF_ClockAdvance, mapl_return, mapl_verify, ESMF_ClockGet
get_capgridcomp_from_gc calls ESMF_UserCompGetInternalState
get_metacomp_from_gc calls ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_one_step calls mapl_return, mapl_verify, ESMF_ClockGet, ESMF_GridCompGet, ESMF_GridCompRun, ESMF_TimeGet, exports, gcs, imports, mapl_memcommited
get_error_message calls at
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_memcommited calls mapl_return, mapl_rtrn, get_unit
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
run_gc calls run_multipletimes