Run_ – MAPL
Run_ Subroutine
280 statements
Source File
private subroutine Run_(GC, IMPORT, EXPORT, CLOCK, rc)
Run_ — Runs MAPL_ExtData
This is a simple ESMF wrapper.
History
12Dec2009 da Silva Design and first implementation.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
Grid Component
type(ESMF_State), intent(inout) :: IMPORT
Import State
type(ESMF_State), intent(inout) :: EXPORT
Export State
type(ESMF_Clock), intent(inout) :: CLOCK
The clock
integer, intent(out) :: rc
Error return code: 0 - all is well 1 -
Calls
Source Code
   SUBROUTINE Run_ ( GC, IMPORT, EXPORT, CLOCK, rc )
! !USES:
  implicit NONE
! !INPUT PARAMETERS:
   type(ESMF_Clock),  intent(inout) :: CLOCK     !! The clock
! !OUTPUT PARAMETERS:
   type(ESMF_GridComp), intent(inout)  :: GC     !! Grid Component
   type(ESMF_State), intent(inout) :: IMPORT     !! Import State
   type(ESMF_State), intent(inout) :: EXPORT     !! Export State
   integer, intent(out) ::  rc                   !! Error return code:
                                                 !!  0 - all is well
                                                 !!  1 -
!
!-------------------------------------------------------------------------
   type(MAPL_ExtData_state), pointer :: self        ! Legacy state
   type(ESMF_Field)                  :: field ! Field
   type(ESMF_FieldBundle)            :: bundle
   type(ESMF_Config)                 :: CF          ! Universal Config
   character(len=ESMF_MAXSTR)        :: comp_name
   character(len=ESMF_MAXSTR)        :: Iam
   integer                           :: status
   type(PrimaryExport), pointer      :: item
   type(DerivedExport), pointer      :: derivedItem
   integer                           :: i, j
   type(ESMF_Time)                   :: time, time0
   type(MAPL_MetaComp), pointer      :: MAPLSTATE
   logical                           :: doUpdate_
   integer                           :: fieldCount
   character(len=ESMF_MAXSTR), ALLOCATABLE  :: NAMES (:)
   character(len=ESMF_MAXPATHLEN)    :: file_processed, file_processed1, file_processed2
   logical                           :: NotSingle
   logical                           :: updateL, updateR, swap
   logical, allocatable              :: doUpdate(:)
   type(ESMF_Time), allocatable      :: useTime(:)
   integer                           :: bracket_side
   integer                           :: entry_num
   type(IOBundleVector), target     :: IOBundles
   type(IOBundleVectorIterator) :: bundle_iter
   type(ExtData_IOBundle), pointer :: io_bundle
   _UNUSED_DUMMY(IMPORT)
   _UNUSED_DUMMY(EXPORT)
!  Declare pointers to IMPORT/EXPORT/INTERNAL states
!  -------------------------------------------------
!  #include "MAPL_ExtData_DeclarePointer___.h"
!  Get my name and set-up traceback handle
!  ---------------------------------------
   Iam = 'Run_'
   call ESMF_GridCompGet( GC, name=comp_name, _RC )
   Iam = trim(comp_name) // '::' // trim(Iam)
!  Call Run for every Child
!  -------------------------
!ALT   call MAPL_GenericRunChildren (GC, IMPORT, EXPORT, CLOCK,  _RC)
!  Extract relevant runtime information
!  ------------------------------------
   call extract_ ( GC, self, CF, _RC )
   if (.not. self%active) then
      _RETURN(ESMF_SUCCESS)
   end if
   call MAPL_GetObjectFromGC ( gc, MAPLSTATE, RC=STATUS)
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"Run")
   call ESMF_ClockGet(CLOCK, currTIME=time0, _RC)
!  Fill in the internal state with data from the files
!  ---------------------------------------------------
   allocate(doUpdate(self%primary%nitems),stat=status)
   _VERIFY(STATUS)
   doUpdate = .false.
   allocate(useTime(self%primary%nitems),stat=status)
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"-Read_Loop")
   call lgr%debug('ExtData Rune_(): Start')
   call lgr%debug('ExtData Run_(): READ_LOOP: Start')
   READ_LOOP: do i = 1, self%primary%nItems
      item => self%primary%item(self%primaryOrder(i))
      call lgr%debug('ExtData Run_(): READ_LOOP: variable %i0 of %i0~: %a', i, self%primary%nItems, trim(item%var))
      call lgr%debug('   ==> file: %a', trim(item%file))
      call lgr%debug('   ==> cyclic: %a', trim(item%cyclic))
      call lgr%debug('   ==> isConst:: %l1', item%isConst)
      if (item%isConst) then
         call lgr%debug('   ==> Break loop since isConst is true')
         cycle
      endif
      NotSingle = .true.
      if (trim(item%cyclic) == 'single') NotSingle = .false.
      call MAPL_TimerOn(MAPLSTATE,"--CheckUpd")
      call CheckUpdate(doUpdate_,time,time0,hasRun,primaryItem=item,_RC)
      doUpdate(i) = doUpdate_
      call MAPL_TimerOff(MAPLSTATE,"--CheckUpd")
      DO_UPDATE: if (doUpdate_) then
         call lgr%debug('   ExtData Run_: DO_UPDATE: Start. doUpdate_ is true.')
         HAS_RUN: if ( hasRun .eqv. .false.) then
            call lgr%debug('   ExtData Run_: Has_Run: Start. hasRun is false. Update time.')
            call MAPL_TimerOn(MAPLSTATE,"--Bracket")
            if (NotSingle) then
               ! update left time
               call lgr%debug('   ExtData Run_: HAS_RUN: NotSingle is true. Update left time (bracket L)')
               call UpdateBracketTime(item,time,"L",item%interp_time1, &
                    item%time1,file_processed1,self%allowExtrap,rc=status)
               _VERIFY(status)
               call IOBundle_Add_Entry(IOBundles,item,self%primaryOrder(i),file_processed1,MAPL_ExtDataLeft,item%tindex1,_RC)
               ! update right time
               call lgr%debug('      ExtData Run_: HAS_RUN: NotSingle is true. Update right time (bracket R)')
               call UpdateBracketTime(item,time,"R",item%interp_time2, &
                    item%time2,file_processed2,self%allowExtrap,rc=status)
               _VERIFY(STATUS)
               call IOBundle_Add_Entry(IOBundles,item,self%primaryOrder(i),file_processed2,MAPL_ExtDataRight,item%tindex2,_RC)
            else
               call lgr%debug('      ExtData Run_: HAS_RUN: NotSingle is false. Just get time on file.')
               ! just get time on the file
               item%time1 = MAPL_ExtDataGetFStartTime(item,trim(item%file),_RC)
               item%interp_time1 = item%time1
               file_processed1 = item%file
               call IOBundle_Add_Entry(IOBundles,item,self%primaryOrder(i),file_processed1,MAPL_ExtDataLeft,1,_RC)
            end if
            call MAPL_TimerOff(MAPLSTATE,"--Bracket")
            call lgr%debug('      ExtData Run_: HAS_RUN: End')
         endif HAS_RUN
         ! now update bracketing times if neccessary
         NOT_SINGLE: if (NotSingle) then
            call lgr%debug('      ExtData Run_: NOT_SINGLE: Start. Update bracketing times?')
            if (time >= item%interp_time2) then
               ! normal flow assume clock is moving forward
               updateR = .true.
               updateL = .false.
               swap    = .true.
            else if (time < item%interp_time1) then
               ! the can only happen if clock was rewound like in replay update both
               updateR = .true.
               updateL = .true.
               swap    = .false.
            else
               updateR = .false.
               updateL = .false.
               swap    = .false.
            end if
            call lgr%debug('         ==> updateR: %L1', updateR)
            call lgr%debug('         ==> updateL: %L1', updateL)
            call lgr%debug('         ==> swap: %L1', swap)
            call MAPL_TimerOn(MAPLSTATE,'--Swap')
            DO_SWAP: if (swap) then
               call lgr%debug('            DO_SWAP: Swapping prev and next')
               call swapBracketInformation(item,_RC)
            end if DO_SWAP
            call MAPL_TimerOff(MAPLSTATE,'--Swap')
            UPDATE_R: if (updateR) then
               call lgr%debug('         UPDATE_R: updating right bracket')
               call MAPL_TimerOn(MAPLSTATE,'--Bracket')
               call UpdateBracketTime(item,time,"R",item%interp_time2, &
                    item%time2,file_processed,self%allowExtrap,rc=status)
               _VERIFY(STATUS)
               call IOBundle_Add_Entry(IOBundles,item,self%primaryOrder(i),file_processed,MAPL_ExtDataRight,item%tindex2,_RC)
               call MAPL_TimerOff(MAPLSTATE,'--Bracket')
            end if UPDATE_R
            UPDATE_L: if (updateL) then
               call lgr%debug('         UPDATE_L: updating left bracket')
               call MAPL_TimerOn(MAPLSTATE,'--Bracket')
               call UpdateBracketTime(item,time,"L",item%interp_time1, &
                    item%time1,file_processed,self%allowExtrap,rc=status)
               _VERIFY(STATUS)
               call IOBundle_Add_Entry(IOBundles,item,self%primaryOrder(i),file_processed,MAPL_ExtDataLeft,item%tindex1,_RC)
               call MAPL_TimerOff(MAPLSTATE,'--Bracket')
            end if UPDATE_L
            call lgr%debug('      ExtData Run_: NOT_SINGLE: End')
         endif NOT_SINGLE
         useTime(i) = time
         call lgr%debug('   ExtData Run_: DO_UPDATE: End')
      end if DO_UPDATE
      if (PrimaryExportIsConstant_(item) .and. associated(item%refresh_time)) then
         deallocate(item%refresh_time)
         item%refresh_time => null()
      end if
   end do READ_LOOP
   call lgr%debug('ExtData Run_: READ_LOOP: Done')
   if (IOBundles%size() == 0) then
      deallocate(doUpdate)
      deallocate(useTime)
      if (hasRun .eqv. .false.) hasRun = .true.
      call MAPL_TimerOff(MAPLSTATE,"-Read_Loop")
      call MAPL_TimerOff(MAPLSTATE,"Run")
      _RETURN(ESMF_SUCCESS)
   endif
   bundle_iter = IOBundles%begin()
   do while (bundle_iter /= IoBundles%end())
      io_bundle => bundle_iter%get()
      bracket_side = io_bundle%bracket_side
      entry_num = io_bundle%entry_index
      file_Processed = io_bundle%file_name
      item => self%primary%item(entry_num)
      io_bundle%pbundle = ESMF_FieldBundleCreate(rc=status)
      _VERIFY(STATUS)
      call MAPL_ExtDataPopulateBundle(item,bracket_side,io_bundle%pbundle,rc=status)
      _VERIFY(status)
      call bundle_iter%next()
   enddo
   call MAPL_TimerOn(MAPLSTATE,"--PRead")
   call MAPL_TimerOn(MAPLSTATE,"---CreateCFIO")
   call MAPL_ExtDataCreateCFIO(IOBundles, rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"---CreateCFIO")
   call MAPL_TimerOn(MAPLSTATE,"---prefetch")
   call MAPL_ExtDataPrefetch(IOBundles, rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"---prefetch")
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"---IclientDone")
   call i_Clients%done_collective_prefetch()
   call i_Clients%wait()
   call MAPL_TimerOff(MAPLSTATE,"---IclientDone")
   _VERIFY(STATUS)
   call MAPL_TimerOn(MAPLSTATE,"---read-prefetch")
   call MAPL_ExtDataReadPrefetch(IOBundles,rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"---read-prefetch")
   call MAPL_TimerOff(MAPLSTATE,"--PRead")
   bundle_iter = IOBundles%begin()
   do while (bundle_iter /= IOBundles%end())
      io_bundle => bundle_iter%get()
      bracket_side = io_bundle%bracket_side
      entry_num = io_bundle%entry_index
      item => self%primary%item(entry_num)
      call MAPL_ExtDataVerticalInterpolate(self,item,bracket_side,rc=status)
      _VERIFY(status)
      call bundle_iter%next()
   enddo
   call MAPL_ExtDataDestroyCFIO(IOBundles,rc=status)
   _VERIFY(status)
   call MAPL_TimerOff(MAPLSTATE,"-Read_Loop")
   call MAPL_TimerOn(MAPLSTATE,"-Interpolate")
   call lgr%debug('ExtData Run_: INTERP_LOOP: Start')
   INTERP_LOOP: do i = 1, self%primary%nItems
      item => self%primary%item(self%primaryOrder(i))
      if (doUpdate(i)) then
         call lgr%debug('ExtData Run_: INTERP_LOOP: interpolating between bracket times, variable: %a, file: %a', &
              & trim(item%var), trim(item%file))
         ! finally interpolate between bracketing times
         if (item%vartype == MAPL_FieldItem) then
               call ESMF_StateGet(self%ExtDataState, item%name, field, _RC)
               call MAPL_ExtDataInterpField(item,useTime(i),field,_RC)
         else if (item%vartype == MAPL_BundleItem) then
               call ESMF_StateGet(self%ExtDataState, item%name, bundle, _RC)
               call ESMF_FieldBundleGet(bundle, fieldCount = fieldCount, _RC)
               allocate(names(fieldCount),__STAT__)
               call ESMF_FieldBundleGet(bundle, fieldNameList = Names, _RC)
               do j = 1,fieldCount
                  call ESMF_FieldBundleGet(bundle,names(j), field=field, _RC)
                  call MAPL_ExtDataInterpField(item,useTime(i),field,_RC)
               enddo
               deallocate(names)
         else if (item%vartype == MAPL_ExtDataVectorItem) then
               call ESMF_StateGet(self%ExtDataState, item%vcomp1, field, _RC)
               call MAPL_ExtDataInterpField(item,useTime(i),field,vector_comp=1,_RC)
               call ESMF_StateGet(self%ExtDataState, item%vcomp2, field, _RC)
               call MAPL_ExtDataInterpField(item,useTime(i),field,vector_comp=2,_RC)
         end if
      endif
      nullify(item)
   end do INTERP_LOOP
   call lgr%debug('ExtData Run_: INTERP_LOOP: Done')
   call MAPL_TimerOff(MAPLSTATE,"-Interpolate")
   ! now take care of derived fields
   do i=1,self%derived%nItems
      derivedItem => self%derived%item(i)
      call CheckUpdate(doUpdate_,time,time0,hasRun,derivedItem=deriveditem,_RC)
      if (doUpdate_) then
         call CalcDerivedField(self%ExtDataState,derivedItem%name,derivedItem%expression, &
              derivedItem%masking,_RC)
      end if
      if (DerivedExportIsConstant_(derivedItem) .and. associated(derivedItem%refresh_time)) then
          deallocate(self%derived%item(i)%refresh_time)
          self%derived%item(i)%refresh_time => null()
      end if
   end do
   call lgr%debug('ExtData Run_: End')
!  All done
!  --------
   deallocate(doUpdate)
   deallocate(useTime)
   if (hasRun .eqv. .false.) hasRun = .true.
   call MAPL_TimerOff(MAPLSTATE,"Run")
   _RETURN(ESMF_SUCCESS)
   END SUBROUTINE Run_
Call graph
run_ calls ESMF_ClockGet, ESMF_GridCompGet, esmf_fieldbundlecreate, esmf_fieldbundleget, esmf_stateget, mapl_getobjectfromgc, mapl_timeroff, mapl_timeron, calcderivedfield, checkupdate, debug, derivedexportisconstant_, done_collective_prefetch, extract_, iobundle_add_entry, mapl_extdatacreatecfio, mapl_extdatadestroycfio, mapl_extdatagetfstarttime, mapl_extdatainterpfield, mapl_extdatapopulatebundle, mapl_extdataprefetch, mapl_extdatareadprefetch, mapl_extdataverticalinterpolate, mapl_return, mapl_verify, primaryexportisconstant_, swapbracketinformation, updatebrackettime, v_begin, v_iter_get, v_iter_next