runBare – MAPL
runBare Subroutine
37 statements
Source File
private recursive subroutine runBare(this)
Type Bound
ESMF_TestCase
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestCase), intent(inout) :: this
Calls
Source Code
   recursive subroutine runBare(this)
      class (ESMF_TestCase), intent(inout) :: this
      logical :: discard
      type (ESMF_GridComp), target :: gc
      integer :: rc, userRc
      integer :: pet
      ! Gridded component
      gc = ESMF_GridCompCreate(petList=[(pet,pet=0,this%getNumPETsRequested()-1)], rc=rc)
      if (rc /= ESMF_SUCCESS) call throw('Insufficient PETs for request')
      this%gc => gc
      this%val = 4
      call this%setInternalState(gc,rc=rc)
      if (rc /= ESMF_SUCCESS) call throw('Insufficient PETs for request')
      ! create subcommunicator
      this%context = this%parentContext%makeSubcontext(this%getNumPETsRequested())
      if (.not. anyExceptions(this%parentContext)) then
         if (this%context%isActive()) then
            call ESMF_GridCompInitialize(gc, userRc=userRc, rc=rc)
            if (userRc /= ESMF_SUCCESS) call throw('ESMF_TestCase::initialize() failed.')
            if (rc /= ESMF_SUCCESS) call throw('Failure in ESMF_GridCompInitialize()')
            if (.not. anyExceptions(this%context)) then
               call ESMF_GridCompRun(gc, userRc=userRc, rc=rc)
               if (userRc /= ESMF_SUCCESS) call throw('ESMF_TestCase::run() failed.')
               if (rc /= ESMF_SUCCESS) call throw('Failure in ESMF_GridCompRun()')
               call ESMF_GridCompFinalize(gc, userRc=userRc, rc=rc)
               if (userRc /= ESMF_SUCCESS) call throw('ESMF_TestCase::finalize() failed.')
               if (rc /= ESMF_SUCCESS) call throw('Failure in ESMF_GridCompFinalize()')
            end if
         end if
      else
         ! only report context failure on root PE
         if (.not. this%parentContext%isRootProcess()) then
            discard = catch()
            if (.false.) print*,shape(discard)
         end if
      end if
      call gatherExceptions(this%parentContext)
      call this%clearInternalState(gc, rc=rc)
      if (rc /= ESMF_SUCCESS) call throw('Failure in ESMF_GridCompFinalize()')
   end subroutine runBare
Call graph
runbare calls ESMF_GridCompCreate, ESMF_GridCompFinalize, ESMF_GridCompInitialize, ESMF_GridCompRun, anyexceptions, catch, gatherexceptions, isactive, isrootprocess, makesubcontext, clearinternalstate, getnumpetsrequested, setinternalstate, throw
clearinternalstate calls ESMF_GridCompDestroy
getnumpetsrequested calls throw, getnumpetsrequested
setinternalstate calls ESMF_GridCompSetInternalState, esmf_gridcompsetservices