run – MAPL
run Subroutine
24 statements
Source File
subroutine run(rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine run(rc)
         integer, intent(out), optional :: rc
         integer :: status
         character(len=:), allocatable :: input_file
         call MPI_Init(status)
         _VERIFY(status)
         ! Read and parse the command line, and set parameters
         ! If you have extra options you make a procedure as seen below and add arguments
         ! there and pass in here
         cli = MAPL_FargparseCLI(extra=extra_options)
         ! This does the casting of arguments into cap_options for CAP
         cap_options = MAPL_CapOptions(cli, _RC)
         write(*,*) "done with MAPL_FargparseCLI"
         write(*,*) "  cap_options%with_esmf_moab = ", cap_options%with_esmf_moab
         write(*,*) "  cap_options%npes_input_server = ", cap_options%npes_input_server
         write(*,*) "  cap_options%nodes_input_server = ", cap_options%nodes_input_server
         write(*,*) "  cap_options%npes_output_server = ", cap_options%npes_output_server
         write(*,*) "  cap_options%nodes_output_server = ", cap_options%nodes_output_server
         write(*,*) "  cap_options%egress_file = ", cap_options%egress_file
         ! For our extra options we have to explicitly cast them
         call cast(cli%options%at('file'), input_file, _RC)
         write(*,*) ""
         write(*,*) "Extra arguments"
         write(*,*) "  input file = ", input_file
         _RETURN(_SUCCESS)
      end subroutine run
Call graph
run calls at, cast, mapl_fargparsecli, mpi_init, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
main calls run