run – MAPL
run Subroutine
14 statements
Source File
private subroutine run(this, rc)
Type Bound
BW_Benchmark
Arguments
Type Intent Optional Attributes Name
class(BW_Benchmark), intent(in) :: this
integer, intent(out), optional :: rc
Calls
Contents
Source Code
run
Source Code
   subroutine run(this, rc)
      class(BW_Benchmark), intent(in) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: unit
      unit = open_file(this%filename, _RC)
      call write_file(this%buffer, unit, _RC)
      call delete_file(this%filename, _RC)
      _RETURN(_SUCCESS)
   end subroutine run
Call graph
run calls delete_file, mapl_return, mapl_verify, open_file, write_file
delete_file calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
open_file calls mapl_return, mapl_verify
write_file calls mapl_return, mapl_verify
get_error_message calls at
mapl_throw_exception calls initialize