run – MAPL
run Subroutine
160 statements
Source File
private subroutine run(this, step)
Type Bound
FakeHistData
Arguments
Type Intent Optional Attributes Name
class(FakeHistData), intent(inout), target :: this
integer, intent(in) :: step
Calls
Called by
Source Code
   subroutine run(this, step)
      class (FakeHistData), target, intent(inout) :: this
      integer, intent(in) :: step
      type(ArrayReference) :: ref
      type(FileMetadata) :: fmd
      Type(Variable) :: T, v, const_v
      integer :: i_var,i
      integer :: collection_id, file_md_id
      integer,allocatable :: prefetch_ids(:)
      integer,allocatable :: stage_ids(:,:)
      integer,allocatable :: nondistributed_ids(:,:)
      integer :: nx, nf, width, k, ith, jth, Xdim0, Xdim1, Ydim0, Ydim1
      integer :: ierr, status
      real(kind=REAL64) :: t0, t1
      type (StringVariableMap) :: var_map
      real(kind=REAL64), allocatable :: lons(:,:,:),lats(:,:,:)
      class(ClientThread), pointer :: icPtr=>null()
      class(ClientThread), pointer :: ocPtr=>null()
      i = mod(this%npes, 6)
      if(i /=0 ) then; print*, " make sure the number of reading cores  is multiple of 6"; stop 1;endif
      nx = nint(sqrt(this%npes/6.))
      if( nx*nx*6 /= this%npes ) then; print*, " make sure 6*M^2 cores to read"; stop 1; endif
      width = this%Xdim/nx
      nf  = this%rank/(nx*nx) + 1    ! nf th face
      k   = this%rank - (nf-1)*nx*nx ! rank within the face
      ith = k/nx
      jth = mod(k,nx)
      Xdim0 = 1 + ith*width
      Xdim1 = (ith+1)*width
      Ydim0 = 1 + jth*width
      Ydim1 = (jth+1)*width
      select case (step)
      case (1) ! read the file
         icPtr => this%ic_vec%at(1)
         collection_id = icPtr%add_ext_collection('collection-i')
         allocate(prefetch_ids(this%vars%size()))
         call MPI_barrier(this%comm,ierr)
         t0 = MPI_wtime()
         do i_var = 1, this%vars%size()
            allocate(this%bundle(i_var)%x(Xdim0:Xdim1,Ydim0:Ydim1,nf:nf,this%lev,1))
            ref = ArrayReference(this%bundle(i_var)%x)
            prefetch_ids(i_var) = &
                 & icPtr%collective_prefetch_data(collection_id,this%file_1, this%vars%at(i_var), ref,&
                 !& this%i_c%collective_prefetch_data(collection_id, this%file_1, this%vars%at(i_var), ref,&
                 & start=[Xdim0,Ydim0,nf,1,1], &
                 & global_start=[1,1,1,1,1],global_count=[this%Xdim,this%Ydim,this%nf, this%lev,1])
         end do
         call icPtr%done_collective_prefetch()
         call MPI_barrier(this%comm,ierr)
         t1 = MPI_wtime()
         if( this%rank == 0) then
            print*, "seconds issuing prefech: ", t1-t0
            print*
         endif
         call MPI_barrier(this%comm,ierr)
         t0 = MPI_wtime()
         do i_var = 1, this%vars%size()
            call icPtr%wait(prefetch_ids(i_var))
         end do
         call MPI_barrier(this%comm,ierr)
         t1 = MPI_wtime()
         if( this%rank == 0) then
            print*, "seconds fetching the data: ",t1-t0
         endif
      case (2) ! history out
         allocate(stage_ids(this%vars%size(),this%num_collection))
         fmd = FileMetadata()
         call fmd%add_dimension('Xdim',this%Xdim)
         call fmd%add_dimension('Ydim',this%Ydim)
         call fmd%add_dimension('lev',this%lev)
         call fmd%add_dimension('nf',this%nf)
         call fmd%add_dimension('time',1)
         call fmd%add_dimension('ncontact', 4, rc=status)
         call fmd%add_dimension('orientationStrLen', 5, rc=status)
          v = Variable(type=PFIO_REAL32, dimensions='Xdim')
          call v%add_attribute('long_name', 'Fake Longitude for GrADS Compatibility')
          call v%add_attribute('units', 'degrees_east')
          call fmd%add_variable('Xdim', v)
          const_v = Variable(type=PFIO_REAL64, dimensions='Xdim,Ydim,nf')
          call const_v%add_attribute('long_name', 'longitude with 6 faces')
          call const_v%add_attribute('units', 'degrees_east')
          allocate(lats(this%Xdim,this%Ydim, this%nf))
          lats = 1.0_real64
          call const_v%add_const_value(UnlimitedEntity(lats))
          call fmd%add_variable('lats', const_v)
          v = Variable(type=PFIO_REAL64, dimensions='Xdim,Ydim,nf')
          call const_v%add_attribute('long_name', 'longitude with 6 faces')
          call const_v%add_attribute('units', 'degrees_east')
          call fmd%add_variable('lons', v)
           v = Variable(type=PFIO_REAL64, dimensions='Ydim')
          call v%add_attribute('long_name', 'Fake Latitude for GrADS Compatibility')
          call v%add_attribute('units', 'degrees_north')
          call fmd%add_variable('Ydim', v)
           v = Variable(type=PFIO_REAL32, dimensions='time')
          call v%add_attribute('long_name', 'time sine')
          call v%add_attribute('units', 'time since 0000000')
          call fmd%add_variable('time', v)
           T = Variable(type=pFIO_REAL32, dimensions='Xdim,Ydim,nf,lev,time')
          do i_var = 1, this%vars%size()
             call fmd%add_variable( this%vars%at(i_var),T)
             if (.not. allocated(this%bundle(i_var)%x)) allocate(this%bundle(i_var)%x(Xdim0:Xdim1,Ydim0:Ydim1,nf:nf,this%lev,1))
         enddo
         ocPtr=> this%oc_vec%at(1)
         do i = 1, this%num_collection
            this%hist_collection_ids(i) = ocPtr%add_hist_collection(fmd)
         enddo
         ! create file and put changes into var_map
         v = Variable(type=PFIO_REAL32, dimensions='time')
         call v%add_attribute('long_name', 'time sine')
         call v%add_attribute('units', 'time since 1111111')
         call var_map%insert('time',v)
         do i = 1, this%num_collection
            file_md_id = this%hist_collection_ids(i)
            call ocPtr%modify_metadata(file_md_id, var_map = var_map)
         end do
         ! send non-distributed-data
         allocate(nondistributed_ids(1,this%num_collection))
         allocate(lons(this%Xdim,this%Ydim, this%nf))
         lons = 10.0_real64
         do i = 1, this%num_collection
            file_md_id = this%hist_collection_ids(i)
            ref = ArrayReference(lons)
            nondistributed_ids(1,i) = ocPtr%stage_nondistributed_data(file_md_id, 'test_out'//i_to_string(i)//'.nc4', 'lons', ref)
         end do
         t0 = MPI_wtime()
         do i = 1, this%num_collection
            file_md_id = this%hist_collection_ids(i)
            do i_var = 1, this%vars%size()
               this%bundle(i_var)%x = 1.0*i*i*i_var*i_var
               ref = ArrayReference(this%bundle(i_var)%x)
               stage_ids(i_var,i) = &
                 & ocPtr%collective_stage_data(file_md_id, 'test_out'//i_to_string(i)//'.nc4', this%vars%at(i_var), ref,&
                 & start=[Xdim0,Ydim0,nf,1, 1], &
                 & global_start=[1,1,1,1,1],global_count=[this%Xdim,this%Ydim, this%nf, this%lev,1])
            enddo
         end do
         call ocPtr%done_collective_stage()
         call MPI_barrier(this%comm,ierr)
         t1 = MPI_wtime()
         if( this%rank == 0) then
            print*, "seconds issuing staging data: ", t1-t0
         endif
         call MPI_barrier(this%comm,ierr)
         t0 = MPI_wtime()
         do i = 1, this%num_collection
           call ocPtr%wait(nondistributed_ids(1,i))
         end do
         do i = 1, this%num_collection
            do i_var = 1, this%vars%size()
               call ocPtr%wait(stage_ids(i_var,i))
            enddo
         end do
         call MPI_barrier(this%comm,ierr)
         t1 = MPI_wtime()
         if( this%rank == 0) then
            print*, "seconds offloading data ", t1-t0
         endif
         deallocate(stage_ids)
         do i_var = 1, this%vars%size()
            if (allocated(this%bundle(i_var)%x)) deallocate(this%bundle(i_var)%x)
         enddo
      end select
   end subroutine run
Call graph
run calls mpi_barrier, mpi_wtime, add_attribute, at, insert, add_const_value, add_dimension, add_ext_collection, add_hist_collection, add_variable, collective_prefetch_data, collective_stage_data, done_collective_prefetch, done_collective_stage, i_to_string, modify_metadata, stage_nondistributed_data
main calls run