run – MAPL
run Subroutine
16 statements
Source File
private subroutine run(this, unusable, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine run(this, unusable, rc)
      class (MAPL_Cap), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
!
      _UNUSED_DUMMY(unusable)
      call this%run_ensemble(rc=status); _VERIFY(status)
      call this%finalize_mpi(rc=status); _VERIFY(status)
      _RETURN(_SUCCESS)
    end subroutine run
Call graph
run calls finalize_mpi, mapl_return, mapl_verify, run_ensemble
finalize_mpi calls mapl_return, mpi_finalize, mapl_finalize
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run_ensemble calls mapl_return, mapl_verify, create_member_subcommunicator, finalize_io_clients_servers, free_sub_comm, initialize_io_clients_servers, run_member
create_member_subcommunicator calls mapl_return, mapl_verify, c_chdir, get_name, get_subcommunicator, split
finalize_io_clients_servers calls mapl_return, finalize, get_name, get_splitcomm, terminate
free_sub_comm calls mpi_comm_free
get_error_message calls at, insert
initialize_io_clients_servers calls mapl_return, mapl_verify, initialize
mapl_finalize calls mapl_return, mapl_verify, finalize_profiler, finalize_pflogger, report_global_profiler, stop_global_time_profiler
mapl_throw_exception calls initialize
run_member calls mapl_return, mapl_verify, get_name, get_splitcomm, get_subcommunicator, run_model