run – MAPL
run Subroutine
50 statements
Source File
private subroutine run(this, step)
Type Bound
FakeExtData
Arguments
Type Intent Optional Attributes Name
class(FakeExtData), intent(inout), target :: this
integer, intent(in) :: step
Calls
Called by
Source Code
   subroutine run(this, step)
      class (FakeExtData), target, intent(inout) :: this
      integer, intent(in) :: step
      type (ArrayReference) :: ref
      integer :: i_var,i
      integer :: lat0, lat1
      integer :: collection_id
      character(len=5) :: tmp
      integer(kind=INT64) :: c1,c2
      integer :: num_request
      integer,allocatable :: request_ids(:,:)
      lat0 = 1 + (this%rank*this%nlat)/this%npes
      lat1 = (this%rank+1)*this%nlat/this%npes
      ! Establish the collection
      ! In a real use case the collection name would be the ExtData template.
      ! But the actual name does not matter - it is just used to identify
      ! a group of files that have identical metadata (except for time)
      !num_request = 1000
      num_request = 3
      call system_clock(c1)
      do i = 1,num_request
         tmp= ''
         write(tmp,'(I5.5)') i
         collection_id = this%c%add_ext_collection('collection-name'//tmp)
         !print*,"collection_id: ",collection_id
      enddo
      call system_clock(c2)
      !print*," step  1 : add_ext_collection"
      allocate(request_ids(this%vars%size(),num_request))
      select case (step)
      case (1) ! read 1st file; prefetch 2nd
        ! call system_clock(c1)
         do i_var = 1, this%vars%size()
            allocate(this%bundle(i_var)%x(this%nlon,lat0:lat1,1,1))
            this%bundle(i_var)%x = -1
            ref = ArrayReference(this%bundle(i_var)%x)
            !this%bundle(i_var)%request_id = &
                 !& this%c%request_subset_data_reference(collection_id, this%file_1, this%vars%at(i_var), ref, start=[1,lat0,20,1])
            do i =1, num_request
            request_ids(i_var,i) = &
                 & this%c%collective_prefetch_data(collection_id, this%file_1, this%vars%at(i_var), ref,&
                 & start=[1,lat0,20,1], &
                 & global_start=[1,1,20,1],global_count=[this%nlon,this%nlat,1,1])
            enddo
         end do
         !call system_clock(c2)
        ! print*," step 1 send collective message"
         call this%c%done_collective_prefetch()
         !print*," step 1 first done"
         do i_var = 1, this%vars%size()
            do i = 1, num_request
              call this%c%wait(request_ids(i_var,i))
            enddo
         end do
         do i_var = 1, this%vars%size()
            this%bundle(i_var)%x = -1
            ref = ArrayReference(this%bundle(i_var)%x)
            this%bundle(i_var)%request_id = &
                 !& this%c%request_subset_data_reference(collection_id, this%file_2, this%vars%at(i_var), ref, start=[1,lat0,20,1])
                 & this%c%collective_prefetch_data(collection_id, this%file_1, this%vars%at(i_var), ref,&
                 & start=[1,lat0,20,1], &
                 & global_start=[1,1,20,1],global_count=[this%nlon,this%nlat,1,1])
         end do
         call this%c%done_collective_prefetch()
      case (2) ! wait for 2nd file to complete
         do i_var = 1, this%vars%size()
            call this%c%wait(this%bundle(i_var)%request_id)
         end do
      end select
   end subroutine run
Call graph
run calls at, add_ext_collection, collective_prefetch_data, done_collective_prefetch
add_ext_collection calls mapl_assert, get_connection, mapl_return, mapl_verify, receive, send
collective_prefetch_data calls get, get_connection, get_unique_collective_request_id, insert_requesthandle, mapl_return, mapl_verify, receive, send
done_collective_prefetch calls get_connection, mapl_return, mapl_verify, send
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_assert, mapl_return
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
main calls run