run – MAPL
run Subroutine
63 statements
Source File
subroutine run(spec, rc)
Arguments
Type Intent Optional Attributes Name
type(ComboSpec), intent(in) :: spec
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run(spec, rc)
      type(ComboSpec), intent(in) :: spec
      integer, optional, intent(out) :: rc
      integer :: status
      real :: tot_time
      real :: tot_time_write
      real :: tot_time_gather
      real :: avg_time
      real :: avg_time_write
      real :: avg_time_gather
      type(GathervKernel) :: kernel
      type(BW_Benchmark) :: benchmark
      integer :: writer_comm
      integer :: gather_comm
      integer :: i
      real :: ta, tb
      integer :: color, rank, npes
      call MPI_Comm_rank(MPI_COMM_WORLD, rank, _IERROR)
      call MPI_Comm_size(MPI_COMM_WORLD, npes, _IERROR)
      color = (rank*spec%n_writers) / npes
      call MPI_Comm_split(MPI_COMM_WORLD, color, 0, gather_comm, _IERROR)
      call MPI_Comm_rank(gather_comm, rank, _IERROR)
      call MPI_Comm_split(MPI_COMM_WORLD, rank, 0, writer_comm, _IERROR)
      if (rank /= 0) then
         writer_comm = MPI_COMM_NULL
      end if
      kernel = make_GathervKernel(spec, gather_comm, _RC)
      if (rank == 0) then
         benchmark = make_BW_Benchmark(spec, writer_comm, _RC)
      end if
      call write_header(MPI_COMM_WORLD, _RC)
      tot_time = 0
      tot_time_gather = 0
      tot_time_write = 0
      associate (n => spec%n_tries)
        do i = 1, n
           ta = time(kernel, gather_comm, _RC)
           if (writer_comm /= MPI_COMM_NULL) then
              tb = time(benchmark, writer_comm, _RC)
           end if
           tot_time_gather = tot_time_gather + ta
           tot_time_write = tot_time_write + tb
           tot_time = tot_time + ta + tb
        end do
        avg_time = tot_time / n
        avg_time_gather = tot_time_gather / n
        avg_time_write = tot_time_write / n
      end associate
      call report(spec, avg_time, avg_time_gather, avg_time_write, MPI_COMM_WORLD, _RC)
      _RETURN(_SUCCESS)
   end subroutine run
Call graph
run calls mpi_comm_rank, mpi_comm_size, mpi_comm_split, make_bw_benchmark, make_gathervkernel, mapl_return, mapl_verify, report, write_header
make_bw_benchmark calls mpi_comm_rank, mapl_return, mapl_verify, make_filename
make_gathervkernel calls mpi_comm_size, mapl_return, mapl_verify, init
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
report calls mpi_comm_rank, mpi_comm_size, mapl_return, mapl_verify
write_header calls mpi_comm_rank, mapl_return, mapl_verify
get_error_message calls at, insert
init calls mpi_comm_rank, mpi_comm_size, mapl_return, mapl_verify, mapl_assert
make_filename calls mapl_return, mapl_verify
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
main calls run