run – MAPL
run Subroutine
80 statements
Source File
private subroutine run(this, step, rc)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
Type Bound
FakeHistData0
Arguments
Type Intent Optional Attributes Name
class(FakeHistData0), intent(inout), target :: this
integer, intent(in) :: step
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine run(this, step, rc)
      class (FakeHistData0), target, intent(inout) :: this
      integer, intent(in) :: step
      integer, optional, intent(out) :: rc
      type(ArrayReference) :: ref
      type(FileMetadata) :: fmd
      Type(Variable) :: T
      integer :: i_var,i,md_id
      integer :: collection_id, file_md_id, collection_num
      integer,allocatable :: prefetch_ids(:)
      integer,allocatable :: stage_ids(:,:)
      integer :: nx, nf, width, k, ith, jth, Xdim0, Xdim1, Ydim0, Ydim1
      integer :: status
      class(ClientThread), pointer :: icPtr=>null()
      class(ClientThread), pointer :: ocPtr=>null()
      i = mod(this%npes, 6)
      if(i /=0 ) then; print*, " make sure the number of reading cores  is multiple of 6"; stop 1;endif
      nx = nint(sqrt(this%npes/6.))
      if( nx*nx*6 /= this%npes ) then; print*, " make sure 6*M^2 cores to read"; stop 1; endif
      width = this%Xdim/nx
      nf  = this%rank/(nx*nx) + 1    ! nf th face
      k   = this%rank - (nf-1)*nx*nx ! rank within the face
      ith = k/nx
      jth = mod(k,nx)
      Xdim0 = 1 + ith*width
      Xdim1 = (ith+1)*width
      Ydim0 = 1 + jth*width
      Ydim1 = (jth+1)*width
      ! Establish the collection
      ! In a real use case the collection name would be the ExtData template.
      ! But the actual name does not matter - it is just used to identify
      ! a group of files that have identical metadata (except for time)
      !num_request = 1000
      ! get the input first
      icPtr => this%ic_vec%at(1)
      collection_id = icPtr%add_ext_collection('collection-i')
      !collection_id = this%i_c%add_ext_collection('collection-i')
      allocate(prefetch_ids(this%vars%size()))
      select case (step)
      case (1) ! read the file
         call system_clock(c0)
         do i_var = 1, this%vars%size()
            allocate(this%bundle(i_var)%x(Xdim0:Xdim1,Ydim0:Ydim1,nf:nf,this%lev,1))
            ref = ArrayReference(this%bundle(i_var)%x)
            prefetch_ids(i_var) = &
                 & icPtr%collective_prefetch_data(collection_id,'test_in.nc4', this%vars%at(i_var), ref,&
                 & start=[Xdim0,Ydim0,nf,1,1], &
                 & global_start=[1,1,1,1,1],global_count=[this%Xdim,this%Ydim,this%nf, this%lev,1], rc=status)
            _VERIFY(status)
         end do
         call icPtr%done_collective_prefetch()
         call icPtr%wait_all()
         !do i_var = 1, this%vars%size()
         !   call icPtr%wait(prefetch_ids(i_var))
         !end do
      case (2) ! history out
         call system_clock(c1)
         call fmd%add_dimension('Xdim',this%Xdim)
         call fmd%add_dimension('Ydim',this%Ydim)
         call fmd%add_dimension('lev',this%lev)
         call fmd%add_dimension('nf',this%nf)
         call fmd%add_dimension('time',1)
         T = Variable(type=pFIO_REAL32, dimensions='Xdim,Ydim,nf,lev,time')
         do i_var = 1, this%vars%size()
            call fmd%add_variable( this%vars%at(i_var),T, rc=status)
            _VERIFY(status)
         enddo
         ocPtr=> this%oc_vec%at(1)
         this%hist_collection_ids(1) = ocPtr%add_hist_collection(fmd)
         this%hist_collection_ids(2) = ocPtr%add_hist_collection(fmd)
         !this%hist_collection_ids(1) = this%o_c%add_hist_collection(fmd)
         collection_num = 2
         allocate(stage_ids(this%vars%size(),collection_num))
         do md_id = 1, collection_num
            ! writing
            file_md_id = this%hist_collection_ids(md_id)
            do i_var = 1, this%vars%size()
               ref = ArrayReference(this%bundle(i_var)%x)
               stage_ids(i_var,md_id) = &
                 & ocPtr%collective_stage_data(file_md_id, 'test_out'//i_to_string(md_id)//'.nc4', this%vars%at(i_var), ref,&
                 & start=[Xdim0,Ydim0,nf,1, 1], &
                 & global_start=[1,1,1,1,1],global_count=[this%Xdim,this%Ydim, this%nf, this%lev,1], rc=status)
               _VERIFY(status)
            end do
         enddo
         call ocPtr%done_collective_stage()
         call ocPtr%wait_all()
         !call this%o_c%done()
         !do md_id = 1, collection_num
         !   do i_var = 1, this%vars%size()
         !      call ocPtr%wait(stage_ids(i_var,md_id))
         !   enddo
         !end do
         call system_clock(c2)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
      end select
      _RETURN(_SUCCESS)
   end subroutine run
Call graph
run calls at, add_dimension, add_ext_collection, add_hist_collection, add_variable, collective_prefetch_data, collective_stage_data, done_collective_prefetch, done_collective_stage, i_to_string, mapl_return, mapl_verify, wait_all
main calls run