run – MAPL
run Subroutine
34 statements
Source File
private subroutine run(this, step)
Type Bound
FakeExtData
Arguments
Type Intent Optional Attributes Name
class(FakeExtData), intent(inout), target :: this
integer, intent(in) :: step
Calls
Called by
Source Code
   subroutine run(this, step)
      class (FakeExtData), target, intent(inout) :: this
      integer, intent(in) :: step
      type (ArrayReference) :: ref
      integer :: i_var
      !integer :: i
      integer :: lat0, lat1
      integer :: collection_id
      !character(len=4) :: tmp
      lat0 = 1 + (this%rank*this%nlat)/this%npes
      lat1 = (this%rank+1)*this%nlat/this%npes
      ! Establish the collection
      ! In a real use case the collection name would be the ExtData template.
      ! But the actual name does not matter - it is just used to identify
      ! a group of files that have identical metadata (except for time)
      !do i = 1,9999
      !   tmp= ''
      !   write(tmp,'(I4.4)') i
      !collection_id = this%c%add_ext_collection('collection-name'//tmp)
      !enddo
      collection_id = this%c%add_ext_collection('collection-name')
      select case (step)
      case (1) ! read 1st file; prefetch 2nd
         do i_var = 1, this%vars%size()
            allocate(this%bundle(i_var)%x(this%nlon,lat0:lat1,1,1))
            this%bundle(i_var)%x = -1
            ref = ArrayReference(this%bundle(i_var)%x)
            this%bundle(i_var)%request_id = &
                 & this%c%prefetch_data(collection_id, this%file_1, this%vars%at(i_var), ref, start=[1,lat0,20,1])
         end do
         call this%c%done_prefetch()
         do i_var = 1, this%vars%size()
            call this%c%wait(this%bundle(i_var)%request_id)
         end do
         do i_var = 1, this%vars%size()
            this%bundle(i_var)%x = -1
            ref = ArrayReference(this%bundle(i_var)%x)
            this%bundle(i_var)%request_id = &
                 & this%c%prefetch_data(collection_id, this%file_2, this%vars%at(i_var), ref, start=[1,lat0,20,1])
         end do
         call this%c%done_prefetch()
      case (2) ! wait for 2nd file to complete
         do i_var = 1, this%vars%size()
            call this%c%wait(this%bundle(i_var)%request_id)
         end do
      end select
   end subroutine run
Call graph
run calls at, add_ext_collection, done_prefetch, prefetch_data
add_ext_collection calls mapl_assert, get_connection, mapl_return, mapl_verify, receive, send
done_prefetch calls get_connection, isempty_requesthandle, mapl_return, mapl_verify, send
prefetch_data calls get, get_connection, get_unique_request_id, insert_requesthandle, mapl_return, mapl_verify, receive, send
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_assert, mapl_return
insert_requesthandle calls mapl_return, insert
isempty_requesthandle calls mapl_return, m_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_begin calls s_begin
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
main calls run