s_begin – MAPL
s_begin Function
6 statements
Source File
private function s_begin(this) result(begin)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
Return Value type(s_iterator)
Calls
Called by
Call graph
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equalsets calls s_begin
m_begin calls s_begin
s_deepcopy calls s_begin
count_rules_for_item calls m_begin
get_item_type calls m_begin
get_time_range calls m_begin
has_rule_for calls m_begin
m_deepcopy calls s_deepcopy
get_extra_derived_items calls has_rule_for
initialize_ calls count_rules_for_item, get_item_type, get_time_range, get_extra_derived_items