s_begin – MAPL
s_begin Function
6 statements
Source File
private function s_begin(this) result(begin)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
Return Value type(s_iterator)
Calls
Called by
Call graph
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equalsets calls s_begin
m_begin calls s_begin
s_deepcopy calls s_begin
equal calls m_begin
m_deepcopy calls s_deepcopy
put_attributes calls m_begin
put_var_attributes calls m_begin
stringattributemap_serialize calls m_begin
transfer_metadata calls m_begin
def_variables calls put_var_attributes
put_datatofile calls stringattributemap_serialize
serialize calls stringattributemap_serialize, serialize
write calls put_attributes, def_variables
main calls transfer_metadata
add_variable calls def_variables
stringvariablemap_serialize calls serialize
test_serialize calls serialize