s_begin – MAPL
s_begin Function
6 statements
Source File
private function s_begin(this) result(begin)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
Return Value type(s_iterator)
Calls
Called by
Call graph
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equalsets calls s_begin
m_begin calls s_begin
s_deepcopy calls s_begin
clear_requesthandle calls m_begin, clear_requesthandle
isempty_requesthandle calls m_begin
m_deepcopy calls s_deepcopy
done_collective_prefetch calls isempty_requesthandle, done_collective_prefetch
done_collective_stage calls isempty_requesthandle, done_collective_stage
done_prefetch calls isempty_requesthandle, done_prefetch
done_stage calls isempty_requesthandle, done_stage
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait_all calls clear_requesthandle
clean_up calls clear_requesthandle
post_wait_all calls wait_all
run calls done_collective_prefetch, done_collective_stage, done_prefetch, wait_all
terminate calls wait_all
wait calls wait_all