s_begin – MAPL
s_begin Function
6 statements
Source File
private function s_begin(this) result(begin)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
Return Value type(s_iterator)
Calls
Called by
Call graph
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equalsets calls s_begin
m_begin calls s_begin
s_deepcopy calls s_begin
destroy_rh_regen_ogrid calls m_begin
initialize calls m_begin
m_deepcopy calls s_deepcopy
run calls destroy_rh_regen_ogrid