s_begin – MAPL
s_begin Function
6 statements
Source File
private function s_begin(this) result(begin)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
Return Value type(s_iterator)
Calls
Called by
Call graph
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equalsets calls s_begin
m_begin calls s_begin
s_deepcopy calls s_begin
clear calls m_begin
m_deepcopy calls s_deepcopy
main calls m_begin
clear_hist_collections calls clear
clean_up calls clear_hist_collections
handle_done_stage calls clear_hist_collections
put_datatofile calls clear_hist_collections
start_back calls clear_hist_collections