s_begin – MAPL
s_begin Function
6 statements
Source File
private function s_begin(this) result(begin)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
Return Value type(s_iterator)
Calls
Called by
Call graph
s_begin calls s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
equalsets calls s_begin
m_begin calls s_begin
s_deepcopy calls s_begin
check_flip calls m_begin
equal calls m_begin
get_level_name calls m_begin
m_deepcopy calls s_deepcopy
mapl_create_bundle_from_metdata_id calls m_begin
mapl_iochangeres calls m_begin
mapl_iocountlevels calls m_begin
mapl_iocountnondimvars calls m_begin
mapl_iogetnondimvars calls m_begin
modifymetadata calls m_begin
stringvariablemap_serialize calls m_begin
transfer_metadata calls m_begin
write_const_variables calls m_begin
write_coordinate_variables calls m_begin
write_data calls m_begin
write_variables calls m_begin