s_child – MAPL
s_child Function
7 statements
Source File
private function s_child(this, idx) result(child)
Type Bound
node
Arguments
Type Intent Optional Attributes Name
class(node), intent(in), target :: this
integer :: idx
Return Value type(node), pointer
Called by
Call graph
advpos calls s_child
erasenonleaf calls s_child, advpos, rebalance
findnode calls s_child
rebalance calls s_child, rot
rot calls s_child
s_erase_multi calls erasenonleaf, rebalance, s_next
s_find calls findnode
s_insert calls findnode, rebalance
s_next calls advpos
s_prev calls advpos
equalsets calls s_next, s_begin
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_next calls s_next
m_of calls s_insert
m_previous calls s_prev
m_set calls s_insert
s_begin calls s_next
s_count calls s_find
s_deepcopy calls s_insert, s_next, s_begin
s_erase_one calls s_next, erase
s_remove calls s_find, erase
m_at calls m_find
m_begin calls s_begin
m_deepcopy calls s_deepcopy
m_erase_one calls erase