s_clear – MAPL
s_clear Subroutine
10 statements
Source File
private subroutine s_clear(this)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
Calls
Called by
Call graph
s_clear calls tt_clear
tt_clear calls tt_downsize
m_clear calls s_clear