s_count – MAPL
s_count Function
12 statements
Source File
private function s_count(this, value) result(count)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
Return Value integer(kind=SIZE_KIND)
Calls
Call graph
s_count calls exists, s_find
s_find calls exists, at, find_index, s_ordereq
find_index calls exists, at, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind