s_deepCopy – MAPL
s_deepCopy Subroutine
13 statements
Source File
private subroutine s_deepCopy(this, other)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(out), target :: this
class(set2), intent(in), target :: other
Calls
Called by
Call graph
s_deepcopy calls s_begin, s_insert, s_next
s_begin calls s_next
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
s_next calls advpos
advpos calls exists, at, get_child, opposite
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to
get_child calls at
rot calls exists, at, get_child, opposite, update_height, set, set_child, set_parent_child
tt_at_32 calls tt_at_size_kind
tt_grow_to calls tt_capacity, tt_set_capacity
tt_set_32 calls set
update_height calls exists, at, set
m_deepcopy calls s_deepcopy