s_deepCopy – MAPL
s_deepCopy Subroutine
13 statements
Source File
private subroutine s_deepCopy(this, other)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(out), target :: this
class(set2), intent(in), target :: other
Calls
Called by
Call graph
s_deepcopy calls s_begin, s_insert, s_next
s_begin calls s_next
s_insert calls findnode, rebalance, s_lessthan, s_ordereq, s_setchild
s_next calls advpos
advpos calls s_child
findnode calls s_lessthan, s_ordereq, s_child
rebalance calls rot, s_child, s_updateheight
s_ordereq calls s_lessthan
rot calls s_setchild, s_child, s_updateheight, s_whichchild
m_deepcopy calls s_deepcopy