s_erase_one – MAPL
s_erase_one Subroutine
8 statements
Source File
private subroutine s_erase_one(this, iter)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(s_iterator), intent(inout) :: iter
Calls
Called by
Call graph
s_erase_one calls erase, s_next
s_next calls advpos
advpos calls at, exists, get_child, opposite
s_erase_multi calls s_next, at, set, erase_nonleaf, exists, rebalance, set_parent_child
erase_nonleaf calls advpos, at, set, exists, rebalance, set_parent_child, set_child
get_child calls at
rebalance calls at, exists, get_child, opposite, rot, update_height
set_parent_child calls at, set_child
m_erase_one calls erase
s_remove calls erase
clear_requesthandle calls erase
erase_requesthandle calls erase