s_erase_multi – MAPL
s_erase_multi Subroutine
31 statements
Source File
private subroutine s_erase_multi(this, first, last)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(s_iterator), intent(inout) :: first
type(s_iterator), intent(in) :: last
Calls
Contents
Call graph
s_erase_multi calls next, erase_nonleaf, exists, rebalance, set_parent_child
erase_nonleaf calls exists, rebalance, set_parent_child, advpos, set_child
rebalance calls exists, get_child, opposite, rot, update_height
set_parent_child calls set_child
advpos calls exists, get_child, opposite
rot calls exists, set_parent_child, get_child, opposite, set_child, update_height
update_height calls exists