s_erase_multi – MAPL
s_erase_multi Subroutine
31 statements
Source File
private subroutine s_erase_multi(this, first, last)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(s_iterator), intent(inout) :: first
type(s_iterator), intent(in) :: last
Calls
Called by
Call graph
s_erase_multi calls at, set, erase_nonleaf, exists, rebalance, s_next, set_parent_child
erase_nonleaf calls at, set, exists, rebalance, set_parent_child, advpos, set_child
rebalance calls at, exists, get_child, opposite, rot, update_height
s_next calls advpos
set_parent_child calls at, set_child
advpos calls at, exists, get_child, opposite
get_child calls at
rot calls at, set, exists, set_parent_child, get_child, opposite, set_child, update_height
set_child calls set
ti_at_32 calls ti_at_size_kind
ti_set_32 calls set
update_height calls at, set, exists
m_erase_one calls erase
s_erase_one calls erase
s_remove calls erase
clear_requesthandle calls erase
erase_requesthandle calls erase