s_erase_one – MAPL
s_erase_one Subroutine
8 statements
Source File
private subroutine s_erase_one(this, iter)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(s_iterator), intent(inout) :: iter
Calls
Called by
Call graph
s_erase_one calls erase, s_next
s_next calls advpos
advpos calls s_child
s_erase_multi calls s_next, erasenonleaf, rebalance, s_setchild, s_whichchild
erasenonleaf calls advpos, rebalance, s_child, s_setchild, s_whichchild
rebalance calls s_child, rot, s_updateheight
m_erase_one calls erase
s_remove calls erase