s_find – MAPL
s_find Function
14 statements
Source File
private function s_find(this, value) result(find)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
Return Value type(s_iterator)
Calls
Contents
Call graph
s_find calls exists, find_index, s_ordereq
find_index calls exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan