s_find – MAPL
s_find Function
14 statements
Source File
private function s_find(this, value) result(find)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
Return Value type(s_iterator)
Calls
Called by
Call graph
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
m_find calls s_find
m_get calls s_find
s_count calls s_find
s_remove calls s_find
is_valid_prototype calls m_find
m_at calls m_find
make_clone calls m_at
set_grid calls is_valid_prototype
test_retrieve_exists calls m_at
test_retrieve_multi calls m_at
make_factory_from_config calls make_clone
make_factory_from_distgrid calls make_clone
make_factory_from_file calls make_clone