s_find – MAPL
s_find Function
14 statements
Source File
private function s_find(this, value) result(find)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
Return Value type(s_iterator)
Calls
Called by
Call graph
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
m_find calls s_find
m_get calls s_find
s_count calls s_find
s_remove calls s_find
destroy_grid calls m_find, m_at
m_at calls m_find
get_factory calls m_at, get_factory
make_grid_from_factory calls m_at
addgrid calls get_factory
destroy_rh_regen_ogrid calls destroy
fill_time_in_bundle calls get_factory
regrid_accumulate_on_xysubset calls get_factory
regrid_vector_2d_real32 calls get_factory
regrid_vector_2d_real64 calls get_factory
regrid_vector_3d_real32 calls get_factory
regrid_vector_3d_real64 calls get_factory
transpose_regrid_vector_2d_real32 calls get_factory
transpose_regrid_vector_3d_real32 calls get_factory