s_find – MAPL
s_find Function
14 statements
Source File
private function s_find(this, value) result(find)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(in), target :: this
type(pair), intent(in) :: value
Return Value type(s_iterator)
Calls
Called by
Call graph
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan
tt_at_32 calls tt_at_size_kind
m_find calls s_find
m_get calls s_find
s_count calls s_find
s_remove calls s_find
erase_requesthandle calls m_find
get_requesthandle calls m_find
m_at calls m_find
handle_done_stage calls get_requesthandle
put calls get_requesthandle
receive_output_data calls get_requesthandle, receive_output_data
wait calls erase_requesthandle, get_requesthandle