s_insert – MAPL
s_insert Subroutine
79 statements
Source File
private subroutine s_insert(this, value, unused, isNew, ref)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(StringCompositePair), intent(in) :: value
type(Unusable), optional :: unused
logical, intent(out), optional :: isNew
integer(kind=SIZE_KIND), intent(out), optional :: ref
Calls
Contents
Call graph
s_insert calls exists, find_index, rebalance, s_lessthan, s_ordereq
find_index calls exists, s_lessthan, s_ordereq
rebalance calls exists, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
rot calls exists, get_child, opposite, update_height, set_child, set_parent_child
update_height calls exists
set_parent_child calls set_child