s_insert – MAPL
s_insert Subroutine
79 statements
Source File
private subroutine s_insert(this, value, unused, isNew, ref)
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(pair), intent(in) :: value
type(Unusable), optional :: unused
logical, intent(out), optional :: isNew
integer(kind=SIZE_KIND), intent(out), optional :: ref
Calls
Contents
Call graph
s_insert calls exists, s_ordereq, s_lessthan
s_ordereq calls s_lessthan