s_insert – MAPL
s_insert Subroutine
44 statements
Source File
private subroutine s_insert(this, value, unused, isNew, ref)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(pair), intent(in) :: value
type(Unusable), optional :: unused
logical, intent(out), optional :: isNew
type(node), intent(out), optional, pointer :: ref
Calls
Called by
Call graph
s_insert calls findnode, rebalance, s_lessthan, s_ordereq, s_setchild
findnode calls s_lessthan, s_ordereq, s_child
rebalance calls rot, s_child, s_updateheight
s_ordereq calls s_lessthan
rot calls s_setchild, s_child, s_updateheight, s_whichchild
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
m_deepcopy calls s_deepcopy
regrid calls insert
write_data calls regrid