s_insert – MAPL
s_insert Subroutine
79 statements
Source File
private subroutine s_insert(this, value, unused, isNew, ref)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
type(pair), intent(in) :: value
type(Unusable), optional :: unused
logical, intent(out), optional :: isNew
integer(kind=SIZE_KIND), intent(out), optional :: ref
Calls
Called by
Call graph
s_insert calls at, set, exists, find_index, rebalance, s_lessthan, s_ordereq, tt_push_back
find_index calls at, exists, s_lessthan, s_ordereq
rebalance calls exists, at, get_child, opposite, rot, update_height
s_ordereq calls s_lessthan
tt_push_back calls resize, tt_grow_to
get_child calls at
rot calls exists, at, get_child, opposite, update_height, set, set_child, set_parent_child
tt_at_32 calls tt_at_size_kind
tt_grow_to calls tt_capacity, tt_set_capacity
tt_set_32 calls set
update_height calls exists, at, set
set_child calls set
set_parent_child calls at, set_child
ti_at_32 calls ti_at_size_kind
tt_resize_32 calls resize
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
m_deepcopy calls s_deepcopy
modify_variable calls m_set
add_variable calls insert
create_file_handle calls modify_variable
m_new_map_from_pair_array calls insert
mapl_bundlewritencpar calls insert
modifymetadata calls modify_variable
modifytime calls insert, modify_variable
run_model calls insert
run calls insert
stringvariablemap_deserialize calls insert
test_equal_diff_variables calls modify_variable