s_next – MAPL
s_next Subroutine
4 statements
Source File
private subroutine s_next(this)
Type Bound
s_iterator
Arguments
Type Intent Optional Attributes Name
class(s_iterator), intent(inout) :: this
Calls
Called by
Call graph
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
equalsets calls s_next, s_begin
m_next calls s_next
s_begin calls s_next
s_deepcopy calls s_next, s_begin
s_erase_multi calls s_next
s_erase_one calls s_next, erase
m_begin calls s_begin
m_deepcopy calls s_deepcopy
clear_requesthandle calls m_begin, clear_requesthandle
isempty_requesthandle calls m_begin
m_erase_one calls erase
s_remove calls erase
done_collective_prefetch calls isempty_requesthandle
done_collective_stage calls isempty_requesthandle
done_prefetch calls isempty_requesthandle
done_stage calls isempty_requesthandle
handle_done_prefetch calls clear_requesthandle
handle_done_stage calls clear_requesthandle
wait_all calls clear_requesthandle