s_next – MAPL
s_next Subroutine
4 statements
Source File
private subroutine s_next(this)
Type Bound
s_iterator
Arguments
Type Intent Optional Attributes Name
class(s_iterator), intent(inout) :: this
Calls
Called by
Call graph
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
equalsets calls s_next, s_begin
m_next calls s_next
s_begin calls s_next
s_deepcopy calls s_next, s_begin
s_erase_multi calls s_next
s_erase_one calls s_next, erase
equal calls m_next, m_begin
m_begin calls s_begin
m_deepcopy calls s_deepcopy
put_attributes calls m_next, m_begin
put_var_attributes calls m_next, m_begin
stringattributemap_serialize calls m_next, m_begin
transfer_metadata calls m_next, m_begin
def_variables calls put_var_attributes
m_erase_one calls erase
put_datatofile calls stringattributemap_serialize
s_remove calls erase
serialize calls stringattributemap_serialize, serialize
write calls put_attributes, def_variables
main calls transfer_metadata
add_variable calls def_variables
stringvariablemap_serialize calls serialize
test_serialize calls serialize