s_next – MAPL
s_next Subroutine
4 statements
Source File
private subroutine s_next(this)
Type Bound
s_iterator
Arguments
Type Intent Optional Attributes Name
class(s_iterator), intent(inout) :: this
Calls
Called by
Call graph
s_next calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
equalsets calls s_next, s_begin
m_next calls s_next
s_begin calls s_next
s_deepcopy calls s_next, s_begin
s_erase_multi calls s_next
s_erase_one calls s_next, erase
count_rules_for_item calls m_next, m_begin
get_item_type calls m_next, m_begin
get_time_range calls m_next, m_begin
has_rule_for calls m_next, m_begin
m_begin calls s_begin
m_deepcopy calls s_deepcopy
get_extra_derived_items calls has_rule_for
initialize_ calls count_rules_for_item, get_item_type, get_time_range, get_extra_derived_items
m_erase_one calls erase
s_remove calls erase