s_orderEq – MAPL
s_orderEq Function
5 statements
Source File
private function s_orderEq(x, y) result(equal)
Arguments
Type Intent Optional Attributes Name
type(pair), intent(in) :: x
type(pair), intent(in) :: y
Return Value logical
Calls
Called by
Call graph
s_ordereq calls s_lessthan
find_index calls s_ordereq
s_find calls s_ordereq, find_index
s_insert calls s_ordereq, find_index
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_count calls s_find
s_deepcopy calls s_insert
s_remove calls s_find
is_valid_prototype calls m_find
m_at calls m_find
m_deepcopy calls s_deepcopy
add_prototype calls insert
initialize_prototypes calls insert
m_new_map_from_pair_array calls insert
make_clone calls m_at
set_grid calls is_valid_prototype
test_retrieve_exists calls insert, m_at
test_retrieve_multi calls insert, m_at