s_orderEq – MAPL
s_orderEq Function
5 statements
Source File
private function s_orderEq(x, y) result(equal)
Arguments
Type Intent Optional Attributes Name
type(pair), intent(in) :: x
type(pair), intent(in) :: y
Return Value logical
Calls
Called by
Call graph
s_ordereq calls s_lessthan
find_index calls s_ordereq
s_find calls s_ordereq, find_index
s_insert calls s_ordereq, find_index
m_find calls s_find
m_get calls s_find
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_count calls s_find
s_deepcopy calls s_insert
s_remove calls s_find
destroy_rh_regen_ogrid calls m_set, m_at
initialize calls m_set, insert
m_at calls m_find
m_deepcopy calls s_deepcopy
addgrid calls insert, m_at
m_new_map_from_pair_array calls insert
mapl_gradsctlwrite calls m_at
run calls destroy_rh_regen_ogrid, m_at