s_orderEq – MAPL
s_orderEq Function
5 statements
Source File
private function s_orderEq(x, y) result(equal)
Arguments
Type Intent Optional Attributes Name
type(StringCompositePair), intent(in) :: x
type(StringCompositePair), intent(in) :: y
Return Value logical
Calls
Called by
Contents
Call graph
s_ordereq calls s_lessthan
find_index calls s_ordereq
s_find calls s_ordereq, find_index
s_insert calls s_ordereq, find_index