s_prev – MAPL
s_prev Subroutine
4 statements
Source File
private subroutine s_prev(this)
Type Bound
s_iterator
Arguments
Type Intent Optional Attributes Name
class(s_iterator), intent(inout) :: this
Calls
Called by
Call graph
s_prev calls advpos
advpos calls at, exists, get_child, opposite
get_child calls at
ti_at_32 calls ti_at_size_kind
m_previous calls s_prev