s_remove – MAPL
s_remove Subroutine
8 statements
Source File
private subroutine s_remove(this, value)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout), target :: this
type(pair), intent(in) :: value
Calls
Call graph
s_remove calls erase, s_find
s_find calls findnode, s_ordereq
findnode calls s_ordereq, s_child, s_lessthan
s_erase_multi calls erasenonleaf, rebalance, s_next, s_setchild, s_whichchild
s_erase_one calls erase, s_next
s_ordereq calls s_lessthan
erasenonleaf calls rebalance, s_child, s_setchild, s_whichchild, advpos
rebalance calls s_child, rot, s_updateheight
s_next calls advpos