s_remove – MAPL
s_remove Subroutine
7 statements
Source File
private subroutine s_remove(this, value)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout), target :: this
type(StringCompositePair), intent(in) :: value
Calls
Call graph
s_remove calls erase, s_find
s_find calls at, exists, find_index, s_ordereq
find_index calls at, exists, s_ordereq, s_lessthan
s_erase_multi calls exists, at, set, erase_nonleaf, rebalance, s_next, set_parent_child
s_erase_one calls erase, s_next
s_ordereq calls s_lessthan
erase_nonleaf calls exists, at, set, rebalance, set_parent_child, advpos, set_child
rebalance calls exists, at, get_child, opposite, rot, update_height
s_next calls advpos
set_parent_child calls at, set_child
tt_at_32 calls tt_at_size_kind