s_setchild – MAPL
s_setchild Subroutine
8 statements
Source File
private subroutine s_setchild(this, idx, child)
Type Bound
node
Arguments
Type Intent Optional Attributes Name
class(node), intent(inout) :: this
integer, intent(in) :: idx
type(node), intent(in), pointer :: child
Called by
Call graph
erasenonleaf calls s_setchild, rebalance
rot calls s_setchild
s_erase_multi calls s_setchild, erasenonleaf, rebalance
s_insert calls s_setchild, rebalance
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
rebalance calls rot
s_deepcopy calls s_insert
m_deepcopy calls s_deepcopy
m_erase_one calls erase
s_erase_one calls erase
s_remove calls erase
regrid calls insert