s_updateheight – MAPL
s_updateheight Subroutine
10 statements
Source File
private subroutine s_updateheight(this)
Type Bound
node
Arguments
Type Intent Optional Attributes Name
class(node), intent(inout), target :: this
Called by
Call graph
rebalance calls s_updateheight, rot
rot calls s_updateheight
erasenonleaf calls rebalance
s_erase_multi calls rebalance, erasenonleaf
s_insert calls rebalance
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
m_deepcopy calls s_deepcopy
m_erase_one calls erase
s_erase_one calls erase
s_remove calls erase