s_whichchild – MAPL
s_whichchild Function
6 statements
Source File
private function s_whichchild(this, child) result(whichchild)
Type Bound
node
Arguments
Type Intent Optional Attributes Name
class(node), intent(in) :: this
type(node), intent(in), target :: child
Return Value integer
Called by
Call graph
erasenonleaf calls s_whichchild, rebalance
rot calls s_whichchild
s_erase_multi calls s_whichchild, erasenonleaf, rebalance
rebalance calls rot
m_erase_one calls erase
s_erase_one calls erase
s_insert calls rebalance
s_remove calls erase
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert