satname2int – MAPL
satname2int Subroutine
21 statements
Source File
private subroutine satname2int(name, satnum, rc)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(out) :: satnum
integer, intent(out) :: rc
Called by
Contents
Source Code
satname2int
Source Code
Subroutine satname2int(name, satnum, rc)
       IMPLICIT NONE
       character(len=*), intent(in) :: name ! Satellite name
       integer, intent(out) :: satnum       ! Satellite number
       integer, intent(out) :: rc
       rc = 0
       if ((name.EQ."AQUA").or.(name.EQ."aqua").or.(name.EQ."Aqua")) then
           satnum = 1
       elseif ((name.EQ." calipso").or.(name.EQ."CALIPSO").or.(name.EQ."Calipso")) then
           satnum = 2
       elseif ((name.EQ." cloudsat").or.(name.EQ."CLOUDSAT").or.(name.EQ."CloudSat")) then
           satnum = 3
       elseif ((name.EQ." aura").or.(name.EQ."AURA").or.(name.EQ."Aura")) then
           satnum = 4
       elseif ((name.EQ." terra").or.(name.EQ."TERRA").or.(name.EQ."Terra")) then
           satnum = 5
       else
          rc =99
          return
       endif
end Subroutine satname2int
Call graph
orbits_swath calls satname2int, orbits_track
orbits_track calls satname2int
orbits_track1 calls satname2int
orbits_track0 calls orbits_track1
domasking_ calls orbits_swath, orbits_track
domasking_cs calls orbits_swath, orbits_track
get_estimateeci calls orbits_track0
run_ calls domasking_, domasking_cs
get_latlon calls get_estimateeci
orbits calls get_estimateeci