scale_field_ – MAPL
scale_field_ Subroutine
28 statements
Source File
private subroutine scale_field_(offset, scale_factor, field, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: offset
real, intent(in) :: scale_factor
type(ESMF_Field), intent(inout) :: field
integer, intent(inout), optional :: rc
Calls
Source Code
  subroutine scale_field_(offset, scale_factor, field, rc)
     real, intent(in)                  :: scale_factor
     real, intent(in)                  :: offset
     type (ESMF_Field), intent(inout)  :: field
     integer, optional, intent (inout) :: rc
        integer       :: fieldRank
        real, pointer :: xy(:,:)    => null()
        real, pointer :: xyz(:,:,:) => null()
        integer :: status
        call ESMF_FieldGet(field, dimCount=fieldRank, _RC)
        _ASSERT(fieldRank == 2 .or. fieldRank == 3,'Field rank must be 2 or 3')
        if (fieldRank == 2) then
           call ESMF_FieldGet(field, farrayPtr=xy, _RC)
           if (associated(xy)) then
              xy = offset + scale_factor*xy
           end if
        else if (fieldRank == 3) then
           call ESMF_FieldGet(field, farrayPtr=xyz, _RC)
           if (associated(xyz)) then
              xyz = offset + scale_factor*xyz
           end if
        end if
        _RETURN(_SUCCESS)
     end subroutine scale_field_
Call graph
scale_field_ calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize