scale_r4 – MAPL
scale_r4 Subroutine
12 statements
Source File
private subroutine scale_r4(a, x, rc)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R4), intent(in) :: a
type(ESMF_Field), intent(inout) :: x
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
scale_r4
Source Code
   subroutine scale_r4(a, x, rc)
      real(kind=ESMF_KIND_R4), intent(in) :: a
      type(ESMF_Field), intent(inout) :: x
      integer, optional, intent(out) :: rc
      real(kind=ESMF_KIND_R4), pointer :: x_ptr(:)
      integer :: status
      call assign_fptr(x, x_ptr, _RC)
      x_ptr = a * x_ptr
      _RETURN(_SUCCESS)
   end subroutine scale_r4
Call graph
scale_r4 calls assign_fptr, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldscal calls scale_r4
test_fieldscal_r4 calls fieldscal
test_fieldscal_r8 calls fieldscal