searchVerticalLocations – MAPL
searchVerticalLocations Subroutine
42 statements
Source File
private subroutine searchVerticalLocations(pl_mod, plevs, kbeg, kend, im, jm, lmmod, lmpres)
For each horizontal grid point, the subroutine searchVerticalLocations searches the last pressure level that is below lowest model levels and the first pressure level that is above the last model level. This allows to speed up the calculations while doing interpolations.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: pl_mod(im,jm,lmmod)
3D mid pressure on model levels
real, intent(in) :: plevs(lmpres)
pressure levels
integer, intent(out) :: kbeg(im,jm)
starting location
integer, intent(out) :: kend(im,jm)
ending location
integer, intent(in) :: im
number of longitude grid points
integer, intent(in) :: jm
number of latitude grid points
integer, intent(in) :: lmmod
number of model vertical levels
integer, intent(in) :: lmpres
number of pressure vertical levels
Called by
Source Code
      subroutine searchVerticalLocations(pl_mod, plevs, kbeg, kend, &
                                    im, jm, lmmod, lmpres)
!
      integer, intent(IN)  :: im                  !! number of longitude grid points
      integer, intent(IN)  :: jm                  !! number of latitude  grid points
      integer, intent(IN)  :: lmmod               !! number of model vertical levels
      integer, intent(IN)  :: lmpres              !! number of pressure vertical levels
      real,    intent(IN)  :: pl_mod(im,jm,lmmod) !! 3D mid pressure on model levels
      real,    intent(IN)  :: plevs(lmpres)       !! pressure levels
      integer, intent(OUT) :: kbeg(im,jm)         !! starting location
      integer, intent(OUT) :: kend(im,jm)         !! ending location
!
      integer :: i, j, L, k
!
!------------------------------------------------------------------------------
      !-----------------------------------------------------------------------
      ! Find the starting location.
      ! The kbeg in each column is the index of model level data which has the
      ! smaller pressure (highest level) that is trapped by pressure levels.
      !-----------------------------------------------------------------------
      kbeg(:,:) = 1
      DO j = 1, jm
         DO i = 1, im
            model_pressure_beg : DO L = 2, lmmod
               !pressure_search_beg : DO k = lmpres, 2, -1
               pressure_search_beg : DO k = 2, lmpres
                  IF ( (pl_mod(i,j,L) .LE. plevs(k  )) .AND. &
                       (pl_mod(i,j,L) .GT. plevs(k-1))) THEN
                     kbeg(i,j) = L
                     EXIT model_pressure_beg
                  ELSE IF (pl_mod(i,j,L) .LT. plevs(k-1)) THEN
                     EXIT pressure_search_beg
                  END IF
               ENDDO pressure_search_beg
            ENDDO model_pressure_beg
         ENDDO
      ENDDO
      !------------------------------------------------------------------------
      ! Find the ending location.
      ! The kend in each column is the index of model level data which has the
      ! largest pressure (lowest level) that is trapped by pressure levels.
      !------------------------------------------------------------------------
      kend(:,:) = lmmod
      DO j = 1, jm
         DO i = 1, im
            model_pressure_end : DO L = lmmod, 2, -1
               !pressure_search_end : DO k = 2, lmpres
               pressure_search_end : DO k = lmpres, 2, -1
                  IF ( (pl_mod(i,j,L) .LE. plevs(k  )) .AND. &
                       (pl_mod(i,j,L) .GT. plevs(k-1))) THEN
                     kend(i,j) = L
                     EXIT model_pressure_end
                  !ELSE IF (pl_mod(i,j,L) .LT. plevs(k-1)) THEN
                  ELSE IF (pl_mod(i,j,L) .GT. plevs(k)) THEN
                     EXIT pressure_search_end
                  END IF
               ENDDO pressure_search_end
            ENDDO model_pressure_end
         ENDDO
      ENDDO
      return
      end subroutine searchVerticalLocations
Call graph
vertinterpolation_presskappa calls searchverticallocations
mapl_extdataverticalinterpolate calls vertinterpolation_presskappa
run_ calls mapl_extdataverticalinterpolate