select_route_handle – MAPL
select_route_handle Function
37 statements
Source File
private function select_route_handle(this, kind, do_transpose, rc) result(route_handle)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
type(ESMF_TypeKind_Flag), intent(in) :: kind
logical, intent(in), optional :: do_transpose
integer, intent(out), optional :: rc
Return Value type(ESMF_RouteHandle)
Calls
Called by
Source Code
   function select_route_handle(this, kind, do_transpose, rc) result(route_handle)
     type(ESMF_RouteHandle) :: route_handle
     class (EsmfRegridder), intent(in) :: this
     type(ESMF_TypeKind_Flag), intent(in) :: kind
     logical, optional, intent(in) :: do_transpose
     integer, optional, intent(out) :: rc
     character(*), parameter :: Iam = "select_route_handle"
     type(RegridderSpecRouteHandleMap), pointer :: route_handles, transpose_route_handles
     type (RegridderSpec) :: spec
     integer :: status
     logical :: transpose
     spec = this%get_spec()
     if (kind == ESMF_TYPEKIND_R4) then
        route_handles => route_handles_r4
        transpose_route_handles => transpose_route_handles_r4
     else if(kind == ESMF_TYPEKIND_R8) then
        route_handles => route_handles_r8
        transpose_route_handles => transpose_route_handles_r8
     else
        _FAIL('unsuported typekind (must be R4 or R8)')
     end if
     ! Create route-handle if none exist
     if (route_handles%count(spec) == 0) then
        call this%create_route_handle(kind, rc = status)
        _VERIFY(status)
     end if
     ! select proper route-handle
     transpose = .false.
     if (present(do_transpose)) then
        transpose = do_transpose
     end if
     if (.not. transpose) then
        route_handle = route_handles%at(spec)
     else
        route_handle = transpose_route_handles%at(spec)
     end if
     _RETURN(_SUCCESS)
   end function select_route_handle
Call graph
select_route_handle calls mapl_assert, create_route_handle, get_spec, m_at, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
create_route_handle calls mapl_assert, get_spec, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, ESMF_GridGetItem, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, insert, mapl_gridhasde
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_throw_exception calls initialize
do_regrid calls select_route_handle
regrid_scalar_2d_real32 calls do_regrid
regrid_scalar_2d_real64 calls do_regrid
regrid_scalar_3d_real32 calls do_regrid
regrid_scalar_3d_real64 calls do_regrid
regrid_vector_2d_real32 calls do_regrid
regrid_vector_2d_real64 calls do_regrid
regrid_vector_3d_real32 calls do_regrid
regrid_vector_3d_real64 calls do_regrid
transpose_regrid_scalar_2d_real32 calls do_regrid
transpose_regrid_scalar_3d_real32 calls do_regrid
transpose_regrid_vector_2d_real32 calls do_regrid
transpose_regrid_vector_3d_real32 calls do_regrid