send – MAPL
send Subroutine
12 statements
Source File
private subroutine send(this, message, rc)
Type Bound
MpiSocket
Arguments
Type Intent Optional Attributes Name
class(MpiSocket), intent(inout), target :: this
class(AbstractMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine send(this, message, rc)
      class (MpiSocket), target, intent(inout) :: this
      class (AbstractMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      integer, allocatable :: buffer(:)
      integer :: ierror
      buffer = this%parser%encode(message)
      call MPI_Send(buffer, size(buffer), MPI_INTEGER, this%pair_remote_rank, MESSAGE_TAG, this%pair_comm, &
           & ierror)
      _VERIFY(ierror)
      _RETURN(_SUCCESS)
   end subroutine send
Call graph
send calls mpi_send, encode, mapl_return, mapl_verify
encode calls get_length, get_type_id, serialize
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
test_back_and_forth calls send
test_send_terminate calls send