send – MAPL
send Subroutine
19 statements
Source File
private recursive subroutine send(this, message, rc)
Type Bound
SimpleSocket
Arguments
Type Intent Optional Attributes Name
class(SimpleSocket), intent(inout), target :: this
class(AbstractMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   recursive subroutine send(this, message, rc)
      class (SimpleSocket), target, intent(inout) :: this
      class (AbstractMessage), intent(in) :: message
      class (AbstractSocket),pointer :: connection
      integer, optional, intent(out) :: rc
      integer :: status
      connection => this%visitor%get_connection()
      select type (connection)
      type is (SimpleSocket)
         if (allocated(connection%msg)) deallocate(connection%msg)
         allocate(connection%msg , source = message)
         call connection%msg%dispatch(this%visitor, _RC)
      class default
         _FAIL("Simple should connect Simple")
      end select
      _RETURN(_SUCCESS)
     ! call message%dispatch(this%visitor,_RC)
   end subroutine send
Call graph
send calls dispatch, mapl_assert, get_connection, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_connection calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
test_send_done calls send
test_send_terminate calls send