send – MAPL
send Subroutine
23 statements
Source File
private subroutine send(this, message, rc)
Type Bound
MockSocket
Arguments
Type Intent Optional Attributes Name
class(MockSocket), intent(inout), target :: this
class(AbstractMessage), intent(in) :: message
integer, intent(out), optional :: rc
Calls
Contents
Source Code
send
Source Code
   subroutine send(this, message, rc)
      class (MockSocket), target, intent(inout) :: this
      class (AbstractMessage), intent(in) :: message
      integer, optional, intent(out) :: rc
      character(len=100) :: buffer
      select type (message)
      type is (IdMessage)
         write(buffer,'("(",i3.3,")")') message%id
         call this%prefix('send<Id'//trim(buffer)//'>')
      type is (AddExtCollectionMessage)
         call this%prefix("send<AddExtCollection('" // message%template // "')>")
         this%collection_counter = this%collection_counter + 1
         call this%messages%push_back(IdMessage(this%collection_counter))
      type is (PrefetchDataMessage)
         call this%prefix("send<PrefetchData('"//message%var_name//"')>")
      type is (DummyMessage)
         call this%prefix("send<Dummy>")
      class default
         call this%prefix('send<unknown>')
      end select
      _RETURN(_SUCCESS)
   end subroutine send
Call graph
send calls mapl_return, prefix
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize