serialize_buffer_length_int64_0d – MAPL
serialize_buffer_length_int64_0d Function
11 statements
Source File
private function serialize_buffer_length_int64_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function serialize_buffer_length_int64_0d(scalar, rc) result(length)
      integer(kind=INT64), intent(in) :: scalar
      integer, optional, intent(out) :: rc
      length = 2
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(scalar)
   end function serialize_buffer_length_int64_0d
Call graph
serialize_buffer_length_int64_0d calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
serialize_buffer_length calls serialize_buffer_length_int64_0d