serialize – MAPL
serialize Subroutine
12 statements
Source File
private subroutine serialize(this, buffer, rc)
Arguments
Type Intent Optional Attributes Name
class(ModifyMetadataMessage), intent(in) :: this
integer, intent(inout) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
serialize
Source Code
   subroutine serialize(this, buffer, rc)
      class (ModifyMetadataMessage), intent(in) :: this
      integer, intent(inout) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer, allocatable ::  map_buf(:)
      integer :: status
      call StringVariableMap_serialize(this%var_map, map_buf, rc=status)
      _VERIFY(status)
      buffer = [ &
           & serialize_intrinsic(this%collection_id), &
           & map_buf]
      _RETURN(_SUCCESS)
   end subroutine serialize
Call graph
serialize calls stringvariablemap_serialize, mapl_return, mapl_verify, serialize_intrinsic
stringvariablemap_serialize calls mapl_return, mapl_verify, serialize_intrinsic, serialize_buffer_length
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
serialize_intrinsic calls serialize_real32_1d, serialize_logical_0d, serialize_logical_1d, serialize_string, serialize_int32_0d, serialize_int64_0d, serialize_int64_1d, serialize_int32_1d, serialize_real32_0d, serialize_real64_0d, serialize_real64_1d
serialize_real32_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_buffer_length calls serialize_buffer_length_real64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_logical_1d, serialize_buffer_length_string, serialize_buffer_length_int64_1d, serialize_buffer_length_int32_0d, serialize_buffer_length_int64_0d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d
serialize_logical_1d calls mapl_return, word_size
serialize_string calls mapl_return
mapl_throw_exception calls initialize
serialize_int32_0d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_int32_1d calls mapl_return
serialize_real32_0d calls mapl_return
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size