serialize – MAPL
serialize Subroutine
29 statements
Source File
private subroutine serialize(this, buffer, rc)
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(in) :: this
integer, intent(inout), allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Call graph
serialize calls stringvector_serialize, stringattributemap_serialize, mapl_verify, serialize_buffer_length, serialize_intrinsic, mapl_return
stringvector_serialize calls serialize_buffer_length, serialize_intrinsic
stringattributemap_serialize calls serialize_buffer_length, serialize_intrinsic, mapl_return
mapl_verify calls mapl_throw_exception
serialize_buffer_length calls serialize_buffer_length_int32_1d, serialize_buffer_length_int32_0d, serialize_buffer_length_real32_0d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_string, serialize_buffer_length_int64_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_real32_1d
serialize_intrinsic calls serialize_logical_1d, serialize_int32_0d, serialize_int64_1d, serialize_string, serialize_int64_0d, serialize_logical_0d, serialize_int32_1d, serialize_real32_0d, serialize_real64_1d, serialize_real32_1d, serialize_real64_0d
mapl_return calls mapl_throw_exception, get_error_message