serialize_buffer_length_logical_0d – MAPL
serialize_buffer_length_logical_0d Function
8 statements
Source File
private function serialize_buffer_length_logical_0d(scalar, rc) result(length)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
serialize_buffer_length_logical_0d
Source Code
   integer function serialize_buffer_length_logical_0d(scalar, rc) result(length)
      logical, intent(in) :: scalar
      integer, optional, intent(out) :: rc
      length = word_size(pFIO_LOGICAL)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(scalar)
   end function serialize_buffer_length_logical_0d
Call graph
serialize_buffer_length_logical_0d calls word_size, mapl_return
word_size calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
serialize_buffer_length calls serialize_buffer_length_logical_0d