serialize_buffer_length_string – MAPL
serialize_buffer_length_string Function
9 statements
Source File
private function serialize_buffer_length_string(str, rc) result(length)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function serialize_buffer_length_string(str, rc) result(length)
      character(len=*),  intent(in) :: str
      integer, optional, intent(out) :: rc
      integer :: n
      n = len(str)
      ! two words in header
      length = 1 + 1 + (1 + (n-1)/CHARS_PER_INT32)
      _RETURN(_SUCCESS)
   end function serialize_buffer_length_string
Call graph
serialize_buffer_length_string calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
serialize_buffer_length calls serialize_buffer_length_string