serialize_base – MAPL
serialize_base Subroutine
20 statements
Source File
private subroutine serialize_base(this, buffer, rc)
Type Bound
AbstractDataReference
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReference), intent(in) :: this
integer, allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine serialize_base(this, buffer, rc)
      class (AbstractDataReference), intent(in) :: this
      integer, allocatable :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: n, rank
      if(allocated(buffer)) deallocate(buffer)
      allocate(buffer(this%get_length()))
      n = size(transfer(this%base_address,[1]))
      if( allocated(this%shape)) then
         rank = size(this%shape)
      else
         rank = 0
      endif
      buffer(1:n)  = transfer(this%base_address, [1])
      buffer(n+1)  = this%type_kind
      buffer(n+2)  = rank
      if (rank > 0) buffer(n+3:) = this%shape
      _RETURN(_SUCCESS)
   end subroutine serialize_base
Call graph
serialize_base calls get_length, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
serialize calls serialize_base
test_serialize calls serialize