serialize_logical_1d – MAPL
serialize_logical_1d Function
15 statements
Source File
private function serialize_logical_1d(array, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
Calls
Called by
Source Code
   function serialize_logical_1d(array, rc) result(buffer)
      integer(kind=INT32), allocatable :: buffer(:)
      logical, intent(in) :: array(:)
      integer, optional, intent(out) :: rc
      integer, allocatable :: itmp(:)
      integer(kind=INT32) :: n
      n = size(array)*word_size(pFIO_LOGICAL)
      allocate(itmp(n), source = 0)
      where(array)
         itmp = 1
      endwhere
      buffer = [n+1, itmp]
      _RETURN(_SUCCESS)
   end function serialize_logical_1d
Call graph
serialize_logical_1d calls mapl_return, word_size
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
serialize_intrinsic calls serialize_logical_1d
serialize calls serialize_intrinsic
stringattributemap_serialize calls serialize_intrinsic
stringintegermap_serialize calls serialize_intrinsic
stringunlimitedentitymap_serialize calls serialize_intrinsic
stringvariablemap_serialize calls serialize_intrinsic
stringvector_serialize calls serialize_intrinsic
test_serialize_int64_array calls serialize_intrinsic
test_serialize_int64_scalar calls serialize_intrinsic
test_serialize_int_array calls serialize_intrinsic
test_serialize_int_scalar calls serialize_intrinsic
test_serialize_logical_array calls serialize_intrinsic
test_serialize_logical_scalar calls serialize_intrinsic
test_serialize_real_array calls serialize_intrinsic
test_serialize_real_scalar calls serialize_intrinsic
test_serialize_string calls serialize_intrinsic