serialize – MAPL
serialize Subroutine
12 statements
Source File
private subroutine serialize(this, buffer, rc)
Type Bound
ReplaceMetadataMessage
Arguments
Type Intent Optional Attributes Name
class(ReplaceMetadataMessage), intent(in) :: this
integer, intent(inout) :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
serialize
Source Code
   subroutine serialize(this, buffer, rc)
      class (ReplaceMetadataMessage), intent(in) :: this
      integer, intent(inout) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer, allocatable ::  fmd_buf(:)
      integer :: status
      call this%fmd%serialize(fmd_buf, rc=status)
      _VERIFY(status)
      buffer = [ &
           & serialize_intrinsic(this%collection_id), &
           & fmd_buf]
      _RETURN(_SUCCESS)
   end subroutine serialize
Call graph
serialize calls serialize_intrinsic, mapl_return, mapl_verify
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return
word_size calls mapl_return, mapl_assert