serialize – MAPL
serialize Subroutine
22 statements
Source File
private subroutine serialize(this, buffer, rc)
Arguments
Type Intent Optional Attributes Name
class(ForwardDataAndMessage), intent(in) :: this
integer, intent(inout), allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
serialize
Source Code
   subroutine serialize(this, buffer, rc)
      class (ForwardDataAndMessage), intent(in) :: this
      integer, allocatable, intent(inout) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: i,k
      integer, allocatable :: buff_tmp(:)
      if (allocated(buffer)) deallocate(buffer)
      k = 0
      if (allocated(this%idata)) k = size(this%idata)
      call serialize_message_vector(this%msg_vec, buff_tmp)
      if ( k > 0 ) then
         i = k + 1
         buffer =[buff_tmp, i, this%idata]
      else
         buffer = buff_tmp
      endif
      if ( size(buffer, kind=8) > huge(0)) then
        _FAIL("need to increase oserver's number of front cores (nfront)")
      endif
      _RETURN(_SUCCESS)
   end subroutine serialize
Call graph
serialize calls serialize_message_vector, mapl_return, mapl_assert
serialize_message_vector calls mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_assert_return_code calls get_error_message, mapl_throw_exception