serialize_message_vector – MAPL
serialize_message_vector Subroutine
22 statements
Source File
public subroutine serialize_message_vector(msgVec, buffer, rc)
Arguments
Type Intent Optional Attributes Name
type(MessageVector), intent(in) :: msgVec
integer, intent(inout), allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Call graph
serialize_message_vector calls mapl_assert, at, encode
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
encode calls get_length, get_type_id, serialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
v_at_32 calls v_at_size_kind
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_remote_win calls serialize_message_vector
put_datatofile calls serialize_message_vector
serialize calls serialize_message_vector
start calls create_remote_win