serialize_int32_0d – MAPL
serialize_int32_0d Function
10 statements
Source File
private function serialize_int32_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
Calls
Called by
Contents
Source Code
serialize_int32_0d
Source Code
   function serialize_int32_0d(scalar, rc) result(buffer)
      integer(kind=INT32), allocatable :: buffer(:)
      integer(kind=INT32), intent(in) :: scalar
      integer, optional, intent(out) :: rc
      integer(kind=INT32) :: n
      n = 1
      buffer = [scalar]
      _RETURN(_SUCCESS)
   end function serialize_int32_0d
Call graph
serialize_int32_0d calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
serialize_intrinsic calls serialize_int32_0d
stringunlimitedentitymap_serialize calls serialize_intrinsic
serialize calls serialize_intrinsic, stringintegermap_serialize, stringvector_serialize, stringvariablemap_serialize, stringattributemap_serialize
stringintegermap_serialize calls serialize_intrinsic
stringvector_serialize calls serialize_intrinsic
stringvariablemap_serialize calls serialize_intrinsic
stringattributemap_serialize calls serialize_intrinsic
stringvariablemap_get_length calls stringvariablemap_serialize
get_length calls stringvariablemap_get_length