serialize – MAPL
serialize Subroutine
64 statements
Source File
private subroutine serialize(this, buffer, rc)
Arguments
Type Intent Optional Attributes Name
class(UnlimitedEntity), intent(in), target :: this
integer, intent(inout), allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
serialize
Source Code
   subroutine serialize( this, buffer, rc)
      class (UnlimitedEntity),target, intent(in) :: this
      integer, allocatable,intent(inout) :: buffer(:)
      integer, optional, intent(out) :: rc
      integer :: type_kind
      integer :: length, rank
      if(allocated(buffer)) deallocate(buffer)
      buffer = EMPTY
      rank = this%get_rank()
      select case (rank)
      case (0)
         if ( .not. allocated(this%value)) then
            type_kind = pFIO_UNSUPPORTED_TYPE
            buffer = [serialize_intrinsic(EMPTY), &
                      serialize_intrinsic(type_kind)]
         else
         ! check type
         select type (value => this%value)
         type is (integer(INT32))
            type_kind = pFIO_INT32
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(value)]
         type is (integer(INT64))
            type_kind = pFIO_INT64
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(value)]
         type is (real(real32))
            type_kind = pFIO_REAL32
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(value)]
         type is (real(real64))
            type_kind = pFIO_REAL64
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(value)]
         type is (logical)
            type_kind = pFIO_LOGICAL
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(value)]
         type is (StringWrap)
            type_kind = pFIO_STRING
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(value%value)]
         class default
            _FAIL(" type is not supported")
         end select
         endif
      case (1:)
         ! check type
         select type (values=>this%values)
         type is (integer(INT32))
            type_kind = pFIO_INT32
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(values)]
         type is (integer(INT64))
            type_kind = pFIO_INT64
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(values)]
         type is (real(REAL32))
            type_kind = pFIO_REAL32
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(values)]
         type is (real(REAL64))
            type_kind = pFIO_REAL64
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(values)]
         type is (logical)
            type_kind = pFIO_LOGICAL
            buffer = [serialize_intrinsic(this%shape), &
                      serialize_intrinsic(type_kind),  &
                      serialize_intrinsic(values)]
        ! type is (character(len=*))
        !    type_kind = pFIO_STRING
        !    buffer = [serialize_intrinsic(this%shape), &
        !              serialize_intrinsic(type_kind),  &
        !              serialize_intrinsic(values)]
         class default
            _FAIL(" type is not supported")
         end select
      end select
      length =  serialize_buffer_length(length) + size(buffer)
      buffer = [serialize_intrinsic(length),buffer]
      _RETURN(_SUCCESS)
   end subroutine serialize
Call graph
serialize calls serialize_intrinsic, mapl_return, mapl_assert, serialize_buffer_length
serialize_intrinsic calls serialize_logical_1d, serialize_string, serialize_int64_1d, serialize_int32_0d, serialize_int64_0d, serialize_real32_1d, serialize_real64_0d, serialize_logical_0d, serialize_int32_1d, serialize_real32_0d, serialize_real64_1d
mapl_return calls mapl_throw_exception, get_error_message
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
serialize_buffer_length calls serialize_buffer_length_real32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_real64_1d, serialize_buffer_length_int32_0d, serialize_buffer_length_logical_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_1d, serialize_buffer_length_string, serialize_buffer_length_int64_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d