serialize_buffer_length_real32_1d – MAPL
serialize_buffer_length_real32_1d Function
7 statements
Source File
private function serialize_buffer_length_real32_1d(array, rc) result(length)
Arguments
Type Intent Optional Attributes Name
real(kind=REAL32), intent(in) :: array(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
serialize_buffer_length_real32_1d
Source Code
   integer function serialize_buffer_length_real32_1d(array, rc) result(length)
      real(kind=REAL32), intent(in) :: array(:)
      integer, optional, intent(out) :: rc
      length = 1 + size(array)*word_size(pFIO_REAL32)
      _RETURN(_SUCCESS)
   end function serialize_buffer_length_real32_1d
Call graph
serialize_buffer_length_real32_1d calls mapl_return, word_size
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
serialize_buffer_length calls serialize_buffer_length_real32_1d