serialize_logical_0d – MAPL
serialize_logical_0d Function
9 statements
Source File
private function serialize_logical_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
Calls
Called by
Contents
Source Code
serialize_logical_0d
Source Code
   function serialize_logical_0d(scalar, rc) result(buffer)
      integer(kind=INT32), allocatable :: buffer(:)
      logical, intent(in) :: scalar
      integer, optional, intent(out) :: rc
      allocate(buffer(1), source = 0)
      if(scalar) buffer(1) = 1
      _RETURN(_SUCCESS)
   end function serialize_logical_0d
Call graph
serialize_logical_0d calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
serialize_intrinsic calls serialize_logical_0d
serialize calls serialize_intrinsic, stringvector_serialize, stringattributemap_serialize, stringvariablemap_serialize, stringintegermap_serialize
stringintegermap_serialize calls serialize_intrinsic
stringvariablemap_serialize calls serialize_intrinsic
stringvector_serialize calls serialize_intrinsic
stringattributemap_serialize calls serialize_intrinsic
stringunlimitedentitymap_serialize calls serialize_intrinsic
stringvariablemap_get_length calls stringvariablemap_serialize
get_length calls stringvariablemap_get_length