serialize – MAPL
serialize Subroutine
20 statements
Source File
private subroutine serialize(this, buffer, rc)
Type Bound
RDMAReference
Arguments
Type Intent Optional Attributes Name
class(RDMAReference), intent(in) :: this
integer, allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine serialize(this, buffer, rc)
      class (RDMAReference), intent(in) :: this
      integer, allocatable :: buffer(:)
      integer, optional, intent(out) :: rc
      integer, allocatable :: tmp_buff(:)
      integer :: n, status
      if(allocated(buffer)) deallocate(buffer)
      allocate(buffer(this%get_length()))
      call this%serialize_base(tmp_buff, status)
      _VERIFY(status)
      n = this%get_length_base()
      buffer(1:n)  = tmp_buff(:)
      buffer(n+1)  = this%win
      buffer(n+2)  = this%comm
      buffer(n+3)  = this%mem_rank
      buffer(n+4:n+4) = serialize_intrinsic(this%RDMA_allocated)
      buffer(n+5:) = transfer(this%msize_word, [1])
      _RETURN(_SUCCESS)
   end subroutine serialize
Call graph
serialize calls serialize_intrinsic, get_length_base, get_length, mapl_return, mapl_verify, serialize_base
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
get_length calls get_length_base
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
serialize_base calls mapl_return, get_length
get_error_message calls at, insert
mapl_throw_exception calls initialize
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return
word_size calls mapl_return, mapl_assert