serialize_int64_0d – MAPL
serialize_int64_0d Function
8 statements
Source File
private function serialize_int64_0d(scalar, rc) result(buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(in) :: scalar
integer, intent(out), optional :: rc
Return Value integer(kind=INT32), allocatable, (:)
Calls
Called by
Contents
Source Code
serialize_int64_0d
Source Code
   function serialize_int64_0d(scalar, rc) result(buffer)
      integer(kind=INT32), allocatable :: buffer(:)
      integer(kind=INT64), intent(in) :: scalar
      integer, optional, intent(out) :: rc
      buffer = [transfer(scalar,[1])]
      _RETURN(_SUCCESS)
   end function serialize_int64_0d
Call graph
serialize_int64_0d calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
serialize_intrinsic calls serialize_int64_0d
serialize calls serialize_intrinsic, stringvariablemap_serialize, stringattributemap_serialize, stringvector_serialize, stringintegermap_serialize
stringattributemap_serialize calls serialize_intrinsic
stringintegermap_serialize calls serialize_intrinsic
stringunlimitedentitymap_serialize calls serialize_intrinsic
stringvariablemap_serialize calls serialize_intrinsic
stringvector_serialize calls serialize_intrinsic
stringvariablemap_get_length calls stringvariablemap_serialize
get_length calls stringvariablemap_get_length