ServiceConnectionGet – MAPL
ServiceConnectionGet Subroutine
18 statements
Source File
public subroutine ServiceConnectionGet(ITEM, SERVICE, PROVIDER, REQUESTER, RC)
Arguments
Type Intent Optional Attributes Name
type(ServiceConnectionType), intent(in) :: ITEM
character(len=*), intent(out), optional :: SERVICE
character(len=*), intent(out), optional :: PROVIDER
character(len=*), intent(out), optional :: REQUESTER
integer, intent(out), optional :: RC
Calls
Called by
Source Code
  subroutine ServiceConnectionGet(item, &
            Service, Provider, Requester, RC)
    type (ServiceConnectionType), intent(IN)  :: ITEM
    character (len=*), optional, intent(  OUT) :: SERVICE
    character (len=*), optional, intent(  OUT) :: PROVIDER
    character (len=*), optional, intent(  OUT) :: REQUESTER
    integer,           optional, intent(  OUT) :: RC     ! Error code:
    if (present(Service)) then
       Service = item%Service_name
    end if
    if (present(Provider)) then
       Provider = item%Provider_name
    end if
    if (present(requester)) then
       requester = item%requester_name
    end if
    _RETURN(ESMF_SUCCESS)
  end subroutine ServiceConnectionGet
Call graph
serviceconnectionget calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_processserviceconnections calls serviceconnectionget
mapl_genericinitialize calls mapl_processserviceconnections
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize