set_parent_child – MAPL
set_parent_child Subroutine
11 statements
Source File
private subroutine set_parent_child(this, parent, pos, other)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: parent
integer(kind=SIZE_KIND), intent(in) :: pos
integer(kind=SIZE_KIND), intent(in) :: other
Calls
Called by
Call graph
set_parent_child calls at, set_child
set_child calls set
ti_at_32 calls ti_at_size_kind
ti_set_32 calls set
erase_nonleaf calls set_parent_child, rebalance
rot calls set_parent_child
s_erase_multi calls set_parent_child, erase_nonleaf, rebalance
rebalance calls rot
m_erase_one calls erase
s_erase_one calls erase
s_insert calls rebalance
s_remove calls erase
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert