set_separator – MAPL
set_separator Subroutine
5 statements
Source File
private subroutine set_separator(this, separator)
Type Bound
TextColumn
Arguments
Type Intent Optional Attributes Name
class(TextColumn), intent(inout) :: this
character(len=1), intent(in) :: separator
Called by
Source Code
   subroutine set_separator(this, separator)
      class(TextColumn), intent(inout) :: this
      character(1), intent(in) :: separator
      this%separator = separator
   end subroutine set_separator
Call graph
new_formattedtextcolumn_array_header calls set_separator
new_memorytextcolumn calls set_separator
new_multicolumn calls set_separator
new_namecolumn calls set_separator
formattedtextcolumn calls new_formattedtextcolumn_array_header
memorytextcolumn calls new_memorytextcolumn
multicolumn calls new_multicolumn
namecolumn calls new_namecolumn