set_with_default_bounds – MAPL
set_with_default_bounds Subroutine
10 statements
Source File
private elemental subroutine set_with_default_bounds(to, from, default)
Arguments
Type Intent Optional Attributes Name
type(RealMinMax), intent(out) :: to
type(RealMinMax), intent(in), optional :: from
type(RealMinMax), intent(in) :: default
Called by
Contents
Source Code
set_with_default_bounds
Source Code
   elemental subroutine set_with_default_bounds(to, from, default)
      type (RealMinMax), intent(out) :: to
      type (RealMinMax), optional, intent(in) :: from
      type (RealMinMax), intent(in) :: default
      if (present(from)) then
         to = from
      else
         to = default
      end if
   end subroutine set_with_default_bounds
Call graph
set_with_default calls set_with_default_bounds
cubedspheregridfactory_from_parameters calls set_with_default
cubedspheregridfactory calls cubedspheregridfactory_from_parameters