set_ESMF_TimeInterval_from_datetime_duration – MAPL
set_ESMF_TimeInterval_from_datetime_duration Subroutine
41 statements
Source File
public subroutine set_ESMF_TimeInterval_from_datetime_duration(interval, duration, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_TimeInterval), intent(inout) :: interval
class(datetime_duration), intent(in) :: duration
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_ESMF_TimeInterval_from_datetime_duration(interval, duration, rc)
      type(ESMF_TimeInterval), intent(inout) :: interval
      class(datetime_duration), intent(in) :: duration
      integer, optional, intent(out) :: rc
      integer :: status
      ! Get duration(s) from datetime_duration
      ! Set ESMF_TimeInterval
      if(duration % year_is_set()) then
         call ESMF_TimeIntervalSet(interval, yy = duration % year, _RC)
      end if
      if(duration % month_is_set()) then
         call ESMF_TimeIntervalSet(interval, yy = duration % month, _RC)
      end if
      if(duration % day_is_set()) then
         call ESMF_TimeIntervalSet(interval, yy = duration % day, _RC)
      end if
      if(duration % hour_is_real()) then
         call ESMF_TimeIntervalSet(interval, h_r8 = duration % hour_real, _RC)
      else if(duration % hour_is_set()) then
         call ESMF_TimeIntervalSet(interval, h = duration % hour, _RC)
      end if
      if(duration % minute_is_real()) then
         call ESMF_TimeIntervalSet(interval, m_r8 = duration % minute_real, _RC)
      else if(duration % minute_is_set()) then
         call ESMF_TimeIntervalSet(interval, m = duration % minute, _RC)
      end if
      if(duration % second_is_real()) then
         call ESMF_TimeIntervalSet(interval, s_r8 = duration % second_real, _RC)
      else if(duration % second_is_set()) then
         call ESMF_TimeIntervalSet(interval, s = duration % second, _RC)
      end if
      _RETURN(_SUCCESS)
   end subroutine set_ESMF_TimeInterval_from_datetime_duration
Call graph
set_esmf_timeinterval_from_datetime_duration calls ESMF_TimeIntervalSet, day_is_set, hour_is_real, hour_is_set, minute_is_real, minute_is_set, month_is_set, mapl_return, mapl_verify, second_is_real, second_is_set, year_is_set
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
set_esmf_timeinterval calls set_esmf_timeinterval_from_datetime_duration
get_esmf_time_from_netcdf_datetime_integer calls set_esmf_timeinterval
get_esmf_time_from_netcdf_datetime_real calls set_esmf_timeinterval
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_real_to_esmf calls convert_netcdf_datetime_to_esmf