set_undef_value – MAPL
set_undef_value Subroutine
6 statements
Source File
private subroutine set_undef_value(this, undef_value)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(inout) :: this
real :: undef_value
Called by
Source Code
   subroutine set_undef_value(this, undef_value)
      class (AbstractRegridder), intent(inout) :: this
      real :: undef_value
      this%undef_value = undef_value
      this%has_undef_value_ = .true.
   end subroutine set_undef_value
Call graph
mapl_cfioreadbundle calls set_undef_value
mapl_cfioreadbundleread calls set_undef_value
mapl_cfiowritebundlewait calls set_undef_value
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate, mapl_cfioreadarray2d, mapl_cfioreadarray3d
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadparallel_ calls mapl_cfioreadbundleread
mapl_cfioreadstate calls mapl_cfioreadbundle
mapl_cfiowritebundle calls mapl_cfiowritebundlewait
esmf_iowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfiowrite calls mapl_cfiowritebundle, mapl_cfiowritestate
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_cfiowritestate calls mapl_cfiowritebundle
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread, esmf_iowrite
mapl_simplebundlewrite1 calls mapl_cfiowrite
mapl_simplebundlewrite2 calls mapl_cfiowrite
utcfio calls test_main