set_status – MAPL
set_status Subroutine
5 statements
Source File
private subroutine set_status(this, status)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout) :: this
integer, intent(in) :: status
Called by
Source Code
   subroutine set_status(this,status)
      class(AbstractServer),intent(inout) :: this
      integer,intent(in) :: status
      !$omp critical (counter_status)
      this%status = status
      !$omp flush (this)
      !$omp end critical (counter_status)
   end subroutine  set_status
Call graph
add_datareference calls set_status
new_multicommserver calls set_status
new_multigroupserver calls set_status
update_status calls set_status
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
create_remote_win calls add_datareference
handle_done_collective_prefetch calls add_datareference
handle_done calls update_status
start calls create_remote_win