set_child – MAPL
set_child Subroutine
14 statements
Source File
private subroutine set_child(this, pos, dir, child)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: pos
integer, intent(in) :: dir
integer(kind=SIZE_KIND), intent(in) :: child
Calls
Called by
Call graph
set_child calls set
ti_set_32 calls set
erase_nonleaf calls set_child, set_parent_child, rebalance
rot calls set_child, set_parent_child
set_parent_child calls set_child
rebalance calls rot
s_erase_multi calls erase_nonleaf, set_parent_child, rebalance
s_insert calls rebalance
m_erase_one calls erase
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
s_erase_one calls erase
s_remove calls erase