set_comm_world – MAPL
set_comm_world Subroutine
10 statements
Source File
private subroutine set_comm_world(this, comm_world)
Uses
mpi
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout) :: this
integer, intent(in), optional :: comm_world
Called by
Source Code
   subroutine set_comm_world(this, comm_world)
      use MPI
      class(BaseProfiler), intent(inout) :: this
      integer, optional, intent(in) :: comm_world
      !$omp master
      if(present(comm_world)) then
        this%comm_world = comm_world
      else
        this%comm_world =  MPI_COMM_WORLD
      endif
      !$omp end master
   end subroutine set_comm_world
Call graph
new_distributedprofiler calls set_comm_world
new_memoryprofiler calls set_comm_world
new_timeprofiler calls set_comm_world
distributedprofiler calls new_distributedprofiler
memoryprofiler calls new_memoryprofiler
timeprofiler calls new_timeprofiler