set_source_file – MAPL
set_source_file Subroutine
8 statements
Source File
private subroutine set_source_file(this, source_file, rc)
Type Bound
FileMetadata
Arguments
Type Intent Optional Attributes Name
class(FileMetadata), intent(inout) :: this
character(len=*), intent(in) :: source_file
integer, intent(out), optional :: rc
Calls
Called by
Call graph
set_source_file calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
read calls set_source_file