set_services_gc – MAPL
set_services_gc Subroutine
17 statements
Source File
private subroutine set_services_gc(gc, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: gc
integer, intent(out) :: rc
Calls
Contents
Source Code
set_services_gc
Source Code
  subroutine set_services_gc(gc, rc)
    type (ESMF_GridComp) :: gc
    integer, intent(out) :: rc
    integer :: status, phase
    type(MAPL_CapGridComp), pointer :: cap
    cap => get_CapGridComp_from_gc(gc)
    call ESMF_GridCompSetEntryPoint(gc, ESMF_METHOD_INITIALIZE, userRoutine = initialize_gc, rc = status)
    _VERIFY(status)
    do phase = 1, cap%n_run_phases
       call ESMF_GridCompSetEntryPoint(gc, ESMF_METHOD_RUN, userRoutine = run_gc, rc = status)
       _VERIFY(status)
    enddo
    call ESMF_GridCompSetEntryPoint(gc, ESMF_METHOD_FINALIZE, userRoutine = finalize_gc, rc = status)
    _VERIFY(status)
    _RETURN(ESMF_SUCCESS)
  end subroutine set_services_gc
Call graph
set_services_gc calls ESMF_GridCompSetEntryPoint, get_capgridcomp_from_gc, mapl_return, mapl_verify
get_capgridcomp_from_gc calls ESMF_UserCompGetInternalState
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize