set_logger – MAPL
set_logger Subroutine
7 statements
Source File
private subroutine set_logger(this, lgr)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout) :: this
class(Logger), target :: lgr
Calls
Called by
Source Code
   subroutine set_logger(this, lgr)
      class(MaplGenericComponent), intent(inout) :: this
      class(Logger), target :: lgr
      class(AbstractComponent), pointer :: component
      component => this%get_component()
      call component%set_logger(lgr)
   end subroutine set_logger
Call graph
set_logger calls get_component, set_logger
addchild_preamble calls set_logger
mapl_genericstateset calls set_logger
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
mapl_genericstatesetfromgc calls mapl_genericstateset
mapl_addchild calls addchildfromdsometa, addchildfrommeta, addchildfromdso, addchildfromgc
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta
initialize_gc calls mapl_set, mapl_addchild
mapl_capgridcompcreate calls mapl_set
run_component_driver calls mapl_set, mapl_addchild
addchildfromdso_old calls addchildfromdso
initialize_cap_gc calls mapl_capgridcompcreate
main calls run_component_driver