set_clock – MAPL
set_clock Subroutine
19 statements
Source File
private subroutine set_clock(model, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp) :: model
integer, intent(out) :: rc
Calls
Source Code
    subroutine set_clock(model, rc)
        type(ESMF_GridComp)  :: model
        integer, intent(out) :: rc
        type(ESMF_Clock)        :: model_clock
        type(MAPL_Cap), pointer :: cap
        type(ESMF_TimeInterval) :: time_step
        integer                 :: heartbeat_dt
        cap => get_cap_from_gc(model, rc)
        VERIFY_NUOPC_(rc)
        heartbeat_dt = cap%cap_gc%get_heartbeat_dt()
        call NUOPC_ModelGet(model, modelClock=model_clock, rc=rc)
        VERIFY_NUOPC_(rc)
        call ESMF_TimeIntervalSet(time_step, s=heartbeat_dt, rc=rc)
        VERIFY_NUOPC_(rc)
        call ESMF_ClockSet(model_clock, timeStep=time_step)
        VERIFY_NUOPC_(rc)
        _RETURN(_SUCCESS)
    end subroutine set_clock
Call graph
set_clock calls ESMF_ClockSet, ESMF_LogFoundError, ESMF_TimeIntervalSet, NUOPC_ModelGet, get_cap_from_gc, get_heartbeat_dt, mapl_return
get_cap_from_gc calls ESMF_LogFoundError, mapl_return, ESMF_UserCompGetInternalState
get_heartbeat_dt calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize