set_rank – MAPL
set_rank Subroutine
5 statements
Source File
private subroutine set_rank(this, rank)
Type Bound
ServerThread
Arguments
Type Intent Optional Attributes Name
class(ServerThread), intent(inout) :: this
integer, intent(in) :: rank
Called by
Source Code
   subroutine set_rank(this,rank)
      class (ServerThread), intent(inout) :: this
      integer, intent(in) :: rank
      this%thread_rank  = rank
   end subroutine set_rank
Call graph
add_connection calls set_rank
test_handle_addextcollection calls set_rank
test_handle_prefetchdata calls set_rank
test_return_on_terminate calls set_rank
test_return_on_terminate_b calls set_rank
connect_to_client calls add_connection
connect_to_server calls add_connection
new_multicommserver calls add_connection
new_multigroupserver calls add_connection
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize calls connect_to_client, connect_to_server
test_connect calls connect_to_client, connect_to_server
test_connect_multi calls connect_to_client, connect_to_server
test_connect_swap_role calls connect_to_client, connect_to_server
test_connect_with_unused_process calls connect_to_client, connect_to_server
test_stress calls connect_to_client, connect_to_server
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize
time_ave calls initialize
ut_regridding calls initialize