set_shared_communicator – MAPL
set_shared_communicator Subroutine
5 statements
Source File
private subroutine set_shared_communicator(this, shared_communicator)
Type Bound
AbstractCommSplitter
Arguments
Type Intent Optional Attributes Name
class(AbstractCommSplitter), intent(inout) :: this
integer, intent(in) :: shared_communicator
Called by
Source Code
   subroutine set_shared_communicator(this, shared_communicator)
      class (AbstractCommSplitter), intent(inout) :: this
      integer, intent(in) :: shared_communicator
      this%shared_communicator = shared_communicator
   end subroutine set_shared_communicator
Call graph
assign calls set_shared_communicator
new_simplecommsplitter calls set_shared_communicator
simplecommsplitter calls new_simplecommsplitter