set_spec – MAPL
set_spec Subroutine
5 statements
Source File
private subroutine set_spec(this, spec)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
class(AbstractRegridder), intent(inout) :: this
type(RegridderSpec), intent(in) :: spec
Called by
Source Code
   subroutine set_spec(this, spec)
      class(AbstractRegridder), intent(inout) :: this
      type(RegridderSpec), intent(in) :: spec
      this%spec = spec
   end subroutine set_spec
Call graph
identity_regridder calls set_spec
make_regridder_ calls identity_regridder
make_regridder_from_grids calls identity_regridder
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
request_data_from_file calls make_regridder