set_param – MAPL
set_param Subroutine
28 statements
Source File
private subroutine set_param(this, deflation, quantize_algorithm, quantize_level, chunking, nbits_to_keep, regrid_method, itemOrder, write_collection_id, regrid_hints, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
integer, intent(in), optional :: deflation
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(in), optional :: chunking(:)
integer, intent(in), optional :: nbits_to_keep
integer, intent(in), optional :: regrid_method
logical, intent(in), optional :: itemOrder
integer, intent(in), optional :: write_collection_id
integer, intent(in), optional :: regrid_hints
integer, intent(out), optional :: rc
Calls
Called by
Source Code
     subroutine set_param(this,deflation,quantize_algorithm,quantize_level,chunking,nbits_to_keep,regrid_method,itemOrder,write_collection_id,regrid_hints,rc)
        class (MAPL_GriddedIO), intent(inout) :: this
        integer, optional, intent(in) :: deflation
        integer, optional, intent(in) :: quantize_algorithm
        integer, optional, intent(in) :: quantize_level
        integer, optional, intent(in) :: chunking(:)
        integer, optional, intent(in) :: nbits_to_keep
        integer, optional, intent(in) :: regrid_method
        logical, optional, intent(in) :: itemOrder
        integer, optional, intent(in) :: write_collection_id
        integer, optional, intent(in) :: regrid_hints
        integer, optional, intent(out) :: rc
        integer :: status
        if (present(regrid_method)) this%regrid_method=regrid_method
        if (present(nbits_to_keep)) this%nbits_to_keep=nbits_to_keep
        if (present(deflation)) this%deflateLevel = deflation
        if (present(quantize_algorithm)) this%quantizeAlgorithm = quantize_algorithm
        if (present(quantize_level)) this%quantizeLevel = quantize_level
        if (present(chunking)) then
           allocate(this%chunking,source=chunking,stat=status)
           _VERIFY(status)
        end if
        if (present(itemOrder)) this%itemOrderAlphabetical = itemOrder
        if (present(write_collection_id)) this%write_collection_id=write_collection_id
        if (present(regrid_hints)) this%regrid_hints = regrid_hints
        _RETURN(ESMF_SUCCESS)
     end subroutine set_param
Call graph
set_param calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_from_bundle calls set_param
mapl_extdataprefetch calls set_param
mapl_read_bundle calls set_param
run calls set_param
main calls create_from_bundle, mapl_read_bundle
run_ calls mapl_extdataprefetch
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle, mapl_read_bundle
ut_regridding calls create_from_bundle, mapl_read_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main