set_width – MAPL
set_width Subroutine
5 statements
Source File
private subroutine set_width(this, column_width)
Type Bound
TextColumn
Arguments
Type Intent Optional Attributes Name
class(TextColumn), intent(inout) :: this
integer, intent(in) :: column_width
Called by
Source Code
   subroutine set_width(this, column_width)
      class (TextColumn), intent(inout) :: this
      integer, intent(in) :: column_width
      this%column_width = column_width
   end subroutine set_width
Call graph
add_column calls set_width
new_formattedtextcolumn_array_header calls set_width
new_memorytextcolumn calls set_width
new_multicolumn calls set_width
new_namecolumn calls set_width
new_separatorcolumn calls set_width
formattedtextcolumn calls new_formattedtextcolumn_array_header
memorytextcolumn calls new_memorytextcolumn
multicolumn calls new_multicolumn
namecolumn calls new_namecolumn
separatorcolumn calls new_separatorcolumn
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column, generate_report
finalize_ calls mapl_genericfinalize
finalize calls report_profile, mapl_genericfinalize
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report