set_deflation – MAPL
set_deflation Subroutine
5 statements
Source File
private subroutine set_deflation(this, deflate_level)
Type Bound
Variable
Arguments
Type Intent Optional Attributes Name
class(Variable), intent(inout), target :: this
integer, intent(in) :: deflate_level
Called by
Call graph
createfilemetadata calls set_deflation
create_from_bundle calls createfilemetadata
initialize calls createfilemetadata
run calls createfilemetadata
main calls create_from_bundle
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle
ut_regridding calls create_from_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main