set_constant_field – MAPL
set_constant_field Subroutine
52 statements
Source File
private subroutine set_constant_field(item, extDataState, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_State), intent(inout) :: extDataState
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
set_constant_field
Source Code
  subroutine set_constant_field(item,ExtDataState,rc)
     type(PrimaryExport), intent(inout) :: item
     type(ESMF_State), intent(inout) :: extDataState
     integer, intent(out), optional :: rc
     integer :: status,fieldRank
     real(kind=REAL32), pointer :: ptr2d(:,:),ptr3d(:,:,:)
     type(ESMF_Field) :: field
     if (item%vartype == MAPL_FieldItem) then
        call ESMF_StateGet(ExtDataState,trim(item%name),field,_RC)
        call ESMF_FieldGet(field,dimCount=fieldRank,_RC)
        if (fieldRank == 2) then
           call MAPL_GetPointer(ExtDataState, ptr2d, trim(item%name),_RC)
           ptr2d = item%const
        else if (fieldRank == 3) then
           call MAPL_GetPointer(ExtDataState, ptr3d, trim(item%name), _RC)
           ptr3d = item%const
         endif
     else if (item%vartype == MAPL_VectorField) then
        call ESMF_StateGet(ExtDataState,trim(item%vcomp1),field,_RC)
        call ESMF_FieldGet(field,dimCount=fieldRank,_RC)
         if (fieldRank == 2) then
               call MAPL_GetPointer(ExtDataState, ptr2d, trim(item%vcomp1),_RC)
               ptr2d = item%const
         else if (fieldRank == 3) then
               call MAPL_GetPointer(ExtDataState, ptr3d, trim(item%vcomp1), _RC)
               ptr3d = item%const
         endif
         call ESMF_StateGet(ExtDataState,trim(item%vcomp2),field,_RC)
         call ESMF_FieldGet(field,dimCount=fieldRank,_RC)
         if (fieldRank == 2) then
               call MAPL_GetPointer(ExtDataState, ptr2d, trim(item%vcomp2),_RC)
               ptr2d = item%const
         else if (fieldRank == 3) then
               call MAPL_GetPointer(ExtDataState, ptr3d, trim(item%vcomp2), _RC)
               ptr3d = item%const
         endif
      end if
     _RETURN(_SUCCESS)
  end subroutine set_constant_field
Call graph
set_constant_field calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, esmfl_stategetpointertodata
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_stategetpointertodata calls esmfl_stategetptrtodatar4_1, esmfl_stategetptrtodatar8_1, esmfl_stategetptrtodatar4_2, esmfl_stategetptrtodatar4_4, esmfl_stategetptrtodatar4_3, esmfl_stategetptrtodatar8_2, esmfl_stategetptrtodatar8_3, esmfl_stategetptrtodatar8_4
esmfl_stategetptrtodatar4_1 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_1 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_2 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
mapl_throw_exception calls initialize
esmfl_stategetptrtodatar4_4 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar4_3 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_2 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_3 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
esmfl_stategetptrtodatar8_4 calls esmf_stateget, mapl_return, esmf_fieldget, mapl_verify, mapl_allocatecoupling
mapl_allocatecoupling calls mapl_allocatecoupling
run_ calls set_constant_field