set_component – MAPL
set_component Subroutine
6 statements
Source File
private subroutine set_component(this, component)
Type Bound
BaseFrameworkComponent
Arguments
Type Intent Optional Attributes Name
class(BaseFrameworkComponent), intent(inout), target :: this
class(AbstractComponent), intent(in) :: component
Calls
Called by
Source Code
   subroutine set_component(this, component)
      class(BaseFrameworkComponent), target, intent(inout) :: this
      class(AbstractComponent), intent(in) :: component
      this%component = component
      call this%component%set_framework(this)
   end subroutine set_component
Call graph
set_component calls set_framework
addchild_preamble calls set_component
mapl_genericstateset calls set_component
mapl_set calls mapl_genericstateset, mapl_genericstatesetfromgc
addchildfromdsometa calls addchild_preamble
addchildfrommeta calls addchild_preamble
mapl_genericstatesetfromgc calls mapl_genericstateset
mapl_addchild calls addchildfromdsometa, addchildfrommeta, addchildfromdso, addchildfromgc
addchildfromdso calls addchildfromdsometa
addchildfromgc calls addchildfrommeta
initialize_gc calls mapl_set, mapl_addchild
mapl_capgridcompcreate calls mapl_set
run_component_driver calls mapl_set, mapl_addchild
addchildfromdso_old calls addchildfromdso
initialize_cap_gc calls mapl_capgridcompcreate
main calls run_component_driver