set_current – MAPL
set_current Subroutine
13 statements
Source File
private subroutine set_current(this, ith, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
integer, intent(in), optional :: ith
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_current(this, ith, rc)
      class (ClientManager), intent(inout) :: this
      integer, optional, intent(in) :: ith
      integer, optional, intent(out) :: rc
      integer :: ith_
      ith_ = 1
      if (present(ith)) ith_ = ith
      _ASSERT( ith_>=1, 'needs at least one client number')
      _ASSERT( ith_<=this%size(), "exceeding the clients number")
      this%current_client = ith_
      _RETURN(_SUCCESS)
   end subroutine set_current
Call graph
set_current calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize calls set_current
set_optimal_server calls set_current
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize, initialize_ioserver, run_model
mapl_bundlewritencpar calls set_optimal_server
run calls set_optimal_server, initialize_io_clients_servers, run_ensemble
run_model calls set_optimal_server
time_ave calls initialize
ut_regridding calls initialize
mapl_varwritencpar calls mapl_bundlewritencpar, mapl_statevarwritencpar
initialize_p0 calls initialize_io_clients_servers
mapl_statevarwritencpar calls mapl_bundlewritencpar
run_ensemble calls initialize_io_clients_servers
regrid_util calls main
mapl_esmfstatewritetofile calls mapl_varwritencpar
extdata_driver calls run