set_param – MAPL
set_param Module Subroutine
25 statements
Source File
module subroutine set_param(this, deflation, quantize_algorithm, quantize_level, chunking, nbits_to_keep, regrid_method, itemOrder, write_collection_id, regrid_hints, oClients, rc) Interface →
add later on if (present(regrid_method)) this%regrid_method=regrid_method if (present(nbits_to_keep)) this%nbits_to_keep=nbits_to_keep if (present(deflation)) this%deflateLevel = deflation if (present(quantize_algorithm)) this%quantizeAlgorithm = quantize_algorithm if (present(quantize_level)) this%quantizeLevel = quantize_level if (present(chunking)) then allocate(this%chunking,source=chunking,stat=status) if(MAPL_Verify(status,”/home/runner/work/MAPL/MAPL/gridcomps/History/Sampler/MAPL_MaskMod_smod.F90”,232 ,rc)) return end if if (present(regrid_hints)) this%regrid_hints = regrid_hints
Arguments
Type Intent Optional Attributes Name
class(MaskSampler), intent(inout) :: this
integer, intent(in), optional :: deflation
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(in), optional :: chunking(:)
integer, intent(in), optional :: nbits_to_keep
integer, intent(in), optional :: regrid_method
logical, intent(in), optional :: itemOrder
integer, intent(in), optional :: write_collection_id
integer, intent(in), optional :: regrid_hints
type(ClientManager), intent(in), optional :: oClients
integer, intent(out), optional :: rc
Calls
Called by
Source Code
module subroutine set_param(this,deflation,quantize_algorithm,quantize_level,chunking,&
     nbits_to_keep,regrid_method,itemOrder,write_collection_id,regrid_hints,oClients,rc)
  class (MaskSampler), intent(inout) :: this
  integer, optional, intent(in) :: deflation
  integer, optional, intent(in) :: quantize_algorithm
  integer, optional, intent(in) :: quantize_level
  integer, optional, intent(in) :: chunking(:)
  integer, optional, intent(in) :: nbits_to_keep
  integer, optional, intent(in) :: regrid_method
  logical, optional, intent(in) :: itemOrder
  integer, optional, intent(in) :: write_collection_id
  integer, optional, intent(in) :: regrid_hints
  type (ClientManager), optional, intent(in) :: oClients
  integer, optional, intent(out) :: rc
  integer :: status
  if (present(write_collection_id)) this%write_collection_id=write_collection_id
  if (present(itemOrder)) this%itemOrderAlphabetical = itemOrder
  if (present(oClients)) then
     this%use_pfio = .true.
     if (mapl_am_i_root()) then
        write(6, '(2x,a)') 'Mask sampler: use_pfio = .true.;  output to oserver'
     end if
  end if
!!  add later on
!!        if (present(regrid_method)) this%regrid_method=regrid_method
!!        if (present(nbits_to_keep)) this%nbits_to_keep=nbits_to_keep
!!        if (present(deflation)) this%deflateLevel = deflation
!!        if (present(quantize_algorithm)) this%quantizeAlgorithm = quantize_algorithm
!!        if (present(quantize_level)) this%quantizeLevel = quantize_level
!!        if (present(chunking)) then
!!           allocate(this%chunking,source=chunking,stat=status)
!!           _VERIFY(status)
!!        end if
!!        if (present(regrid_hints)) this%regrid_hints = regrid_hints
  _RETURN(ESMF_SUCCESS)
end subroutine set_param
Call graph
set_param calls mapl_am_i_root, mapl_return, set_param
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm