set_ESMF_Time_from_ISO8601 – MAPL
set_ESMF_Time_from_ISO8601 Subroutine
10 statements
Source File
public subroutine set_ESMF_Time_from_ISO8601(time, isostring, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: time
character(len=*), intent(in) :: isostring
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_ESMF_Time_from_ISO8601(time, isostring, rc)
       type(ESMF_Time), intent(inout) :: time
       character(len=*), intent(in) :: isostring
       integer, optional, intent(out) :: rc
       integer :: status
       call ESMF_TimeSet(time, isostring, _RC)
       _RETURN(_SUCCESS)
   end subroutine set_ESMF_Time_from_ISO8601
Call graph
set_esmf_time_from_iso8601 calls ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_esmf_time_from_netcdf_datetime_integer calls set_esmf_time_from_iso8601
get_esmf_time_from_netcdf_datetime_real calls set_esmf_time_from_iso8601
test_esmf_time_from_iso8601 calls set_esmf_time_from_iso8601
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
get_esmf_time_from_netcdf_datetime calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
test_convert_netcdf_datetime_to_esmf_integer calls get_esmf_time_from_netcdf_datetime
test_convert_netcdf_datetime_to_esmf_real calls get_esmf_time_from_netcdf_datetime
time_esmf_to_real calls convert_netcdf_datetime_to_esmf
time_real_to_esmf calls convert_netcdf_datetime_to_esmf
compute_time_for_current calls time_esmf_to_real