set_composite – MAPL
set_composite Subroutine
8 statements
Source File
private subroutine set_composite(this, composite)
Type Bound
CompositeComponent
Arguments
Type Intent Optional Attributes Name
class(CompositeComponent), intent(inout) :: this
class(AbstractComposite), intent(in), target :: composite
Called by
Source Code
   subroutine set_composite(this, composite)
      class(CompositeComponent), intent(inout) :: this
      class(AbstractComposite), target, intent(in) :: composite
      select type (composite)
      type is (ConcreteComposite)
         this%composite => composite
      end select
   end subroutine set_composite
Call graph
mapl_genericstateset calls set_composite
mapl_internalstatecreate calls set_composite
mapl_set calls mapl_genericstateset
addchild_preamble calls mapl_internalstatecreate
mapl_capgridcompcreate calls mapl_internalstatecreate
mapl_genericstatesetfromgc calls mapl_genericstateset
mapl_internalstateretrieve calls mapl_internalstatecreate
run_component_driver calls mapl_internalstatecreate