set_parameters – MAPL
set_parameters Subroutine
23 statements
Source File
private subroutine set_parameters(this, unusable, linear_trans, disable_interpolation, left_field, right_field, intermittent_disable, exact, rc)
Type Bound
ExtDataBracket
Arguments
Type Intent Optional Attributes Name
class(ExtDataBracket), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
real, intent(in), optional :: linear_trans(2)
logical, intent(in), optional :: disable_interpolation
type(ESMF_Field), intent(in), optional :: left_field
type(ESMF_Field), intent(in), optional :: right_field
logical, intent(in), optional :: intermittent_disable
logical, intent(in), optional :: exact
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_parameters(this, unusable, linear_trans, disable_interpolation, left_field, right_field, intermittent_disable, exact, rc)
      class(ExtDataBracket), intent(inout) :: this
      class(KeywordEnforcer), optional, intent(in) :: unusable
      real, optional, intent(in) :: linear_trans(2)
      logical, optional, intent(in) :: disable_interpolation
      type(ESMF_Field), optional, intent(in) :: left_field
      type(ESMF_Field), optional, intent(in) :: right_field
      logical, optional, intent(in) :: intermittent_disable
      logical, optional, intent(in) :: exact
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      if (present(linear_trans)) then
         this%offset=linear_trans(1)
         this%scale_factor=linear_trans(2)
      end if
      if (present(disable_interpolation)) this%disable_interpolation = disable_interpolation
      if (present(left_field)) this%left_node%field=left_field
      if (present(right_field)) this%right_node%field=right_field
      if (present(intermittent_disable)) this%intermittent_disable = intermittent_disable
      if (present(exact)) this%exact = exact
      _RETURN(_SUCCESS)
   end subroutine set_parameters
Call graph
set_parameters calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_bracketing_fields calls set_parameters, createfilelevbracket
createfilelevbracket calls set_parameters
fillin_primary calls set_parameters
get_file_bracket calls set_parameters
initialize_ calls fillin_primary
run_ calls create_bracketing_fields