set_defaults – MAPL
set_defaults Subroutine
11 statements
Source File
private subroutine set_defaults(this, unusable, rc)
Type Bound
ExtDataRule
Arguments
Type Intent Optional Attributes Name
class(ExtDataRule), intent(inout), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_defaults(this,unusable,rc)
      class(ExtDataRule), intent(inout), target :: this
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      this%collection=''
      this%file_var='missing_variable'
      this%regrid_method='BILINEAR'
      _RETURN(_SUCCESS)
   end subroutine set_defaults
Call graph
set_defaults calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
add_new_rule calls set_defaults
new_extdataconfig_from_yaml calls add_new_rule, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml
extdataoldtypescreator calls new_extdataoldtypescreator