set_time_for_date – MAPL
set_time_for_date Function
28 statements
Source File
private function set_time_for_date(this, input_time, rc) result(returned_time)
Type Bound
timeVar
Arguments
Type Intent Optional Attributes Name
class(timeVar), intent(in) :: this
type(ESMF_Time), intent(inout) :: input_time
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Called by
Call graph
set_time_for_date calls ESMF_TimeGet, ESMF_TimeSet, mapl_unpacktime, mapl_return, mapl_verify
mapl_unpacktime calls mapl_unpacktime
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
evaluate_time calls set_time_for_date
fillstate calls evaluate_time
run_ calls fillstate