set_coordinate_data – MAPL
set_coordinate_data Subroutine
9 statements
Source File
private subroutine set_coordinate_data(this, coordinate_data, rc)
Type Bound
CoordinateVariable
Arguments
Type Intent Optional Attributes Name
class(CoordinateVariable), intent(inout) :: this
class(*), intent(in) :: coordinate_data(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_coordinate_data(this, coordinate_data, rc)
      class (CoordinateVariable), intent(inout) :: this
      class (*), intent(in) :: coordinate_data(:)
      integer, optional, intent(out) :: rc
      _ASSERT(.not. allocated(this%coordinate_data), "use replace_coordinate_data")
      allocate(this%coordinate_data, source=coordinate_data)
      _RETURN(_SUCCESS)
   end subroutine set_coordinate_data
Call graph
set_coordinate_data calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_coordinatevariable calls set_coordinate_data
coordinatevariable calls new_coordinatevariable