set_node – MAPL
set_node Subroutine
29 statements
Source File
private subroutine set_node(this, bracketside, unusable, field, file, time, time_index, was_set, rc)
Type Bound
ExtDataBracket
Arguments
Type Intent Optional Attributes Name
class(ExtDataBracket), intent(inout) :: this
character(len=*), intent(in) :: bracketside
class(KeywordEnforcer), intent(in), optional :: unusable
type(ESMF_Field), intent(in), optional :: field
character(len=*), intent(in), optional :: file
type(ESMF_Time), intent(in), optional :: time
integer, intent(in), optional :: time_index
logical, intent(in), optional :: was_set
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_node(this, bracketside, unusable, field, file, time, time_index, was_set, rc)
      class(ExtDataBracket), intent(inout) :: this
      character(len=*), intent(in) :: bracketside
      class(KeywordEnforcer), optional, intent(in) :: unusable
      type(ESMF_Field), optional, intent(in) :: field
      character(len=*), optional, intent(in) :: file
      integer, optional, intent(in) :: time_index
      type(ESMF_Time), optional, intent(in) :: time
      logical, optional, intent(in) :: was_set
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(unusable)
      if (bracketside=='L') then
         if (present(field)) this%left_node%field=field
         if (present(time)) this%left_node%time=time
         if (present(time_index)) this%left_node%time_index=time_index
         if (present(file)) this%left_node%file=file
         if (present(was_set)) this%left_node%was_set=was_set
      else if (bracketside=='R') then
         if (present(field)) this%right_node%field=field
         if (present(time)) this%right_node%time=time
         if (present(time_index)) this%right_node%time_index=time_index
         if (present(file)) this%right_node%file=file
         if (present(was_set)) this%right_node%was_set=was_set
      else
         _FAIL('wrong bracket side')
      end if
      _RETURN(_SUCCESS)
   end subroutine set_node
Call graph
set_node calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_file_bracket calls set_node