set_AllBacklogIsEmpty – MAPL
set_AllBacklogIsEmpty Subroutine
5 statements
Source File
private subroutine set_AllBacklogIsEmpty(this, status)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout) :: this
logical :: status
Called by
Source Code
   subroutine set_AllBacklogIsEmpty(this,status)
      class(AbstractServer),intent(inout) :: this
      logical :: status
      !$omp critical (backlog_status)
      this%all_backlog_is_empty = status
      !$omp flush (this)
      !$omp end critical (backlog_status)
   end subroutine set_AllBacklogIsEmpty
Call graph
clean_up calls set_allbacklogisempty
handle_done calls set_allbacklogisempty, update_status
update_status calls set_allbacklogisempty
handle_done_collective_prefetch calls clean_up
handle_done_collective_stage calls clean_up
start calls clean_up