set_do_print – MAPL
set_do_print Subroutine
15 statements
Source File
private subroutine set_do_print(label, do_print)
Check if resource has already been printed (vector contains label) or should be printed
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: label
logical, intent(inout) :: do_print
Calls
Called by
Source Code
   subroutine set_do_print(label, do_print)
      character(*), intent(in) :: label
      logical, intent(inout) :: do_print
      type(StringVector), pointer, save :: already_printed_labels => null()
      if (do_print) then
         if (.not. associated(already_printed_labels)) then
            allocate(already_printed_labels)
         end if
         ! Do not print label more than once
         if (.not. vector_contains_str(already_printed_labels, trim(label))) then
            call already_printed_labels%push_back(trim(label))
         else
            do_print = .FALSE.
         end if
      end if
   end subroutine set_do_print
Call graph
set_do_print calls vector_contains_str, push_back
vector_contains_str calls begin, next, of
mapl_getresource_config_array calls set_do_print
mapl_getresource_config_scalar calls set_do_print
mapl_getresourcefromconfig_array calls mapl_getresource_config_array
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_array calls mapl_getresource_config_array
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
test_mapl_getresource_array_character calls mapl_getresource_config_array
test_mapl_getresource_array_int4 calls mapl_getresource_config_array
test_mapl_getresource_array_int8 calls mapl_getresource_config_array
test_mapl_getresource_array_logical calls mapl_getresource_config_array
test_mapl_getresource_array_real4 calls mapl_getresource_config_array
test_mapl_getresource_array_real8 calls mapl_getresource_config_array
test_mapl_getresource_scalar_character calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_int8 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_logical calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real4 calls mapl_getresource_config_scalar
test_mapl_getresource_scalar_real8 calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_array, mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_array, mapl_getresourcefrommapl_scalar