set_connection – MAPL
set_connection Subroutine
9 statements
Source File
private subroutine set_connection(this, connection, rc)
Type Bound
BaseThread
Arguments
Type Intent Optional Attributes Name
class(BaseThread), intent(inout), target :: this
class(AbstractSocket), intent(in) :: connection
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine set_connection(this, connection, rc)
      class(BaseThread),target,intent(inout) :: this
      class (AbstractSocket), intent(in) :: connection
      integer, optional, intent(out) :: rc
      if(allocated(this%connection)) deallocate(this%connection)
      allocate(this%connection, source=connection)
      _RETURN(_SUCCESS)
   end subroutine set_connection
Call graph
set_connection calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
connect_to_server calls set_connection
init calls set_connection
new_clientthread calls set_connection
new_fastclientthread calls set_connection
new_mockclientthread calls set_connection
new_mockserverthread calls set_connection
new_serverthread calls set_connection
test_addextcollection_send_message calls set_connection
test_addextcollection_unique_handle calls set_connection
test_prefetch_data calls set_connection
test_send_done calls set_connection
test_send_terminate calls set_connection
test_wait calls set_connection
clientthread calls new_clientthread
fastclientthread calls new_fastclientthread
mockclientthread calls new_mockclientthread
mockserverthread calls new_mockserverthread
serverthread calls new_serverthread
initialize calls connect_to_server
test_connect calls connect_to_server
test_connect_multi calls connect_to_server
test_connect_swap_role calls connect_to_server
test_connect_with_unused_process calls connect_to_server
test_handle_addextcollection calls init
test_handle_prefetchdata calls init
test_return_on_terminate calls init
test_return_on_terminate_b calls init
test_stress calls connect_to_server