setFrequency – MAPL
setFrequency Subroutine
8 statements
Source File
private subroutine setFrequency(this, frequency, rc)
Type Bound
timeData
Arguments
Type Intent Optional Attributes Name
class(timeData), intent(inout) :: this
integer, intent(in) :: frequency
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine setFrequency(this,frequency,rc)
     class(TimeData), intent(inout) :: this
     integer, intent(in) :: frequency
     integer, optional, intent(out) :: rc
     this%frequency = frequency
     _RETURN(_SUCCESS)
   end subroutine setFrequency
Call graph
setfrequency calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
modifytimeincrement calls setfrequency
run calls modifytimeincrement