SetRefreshAlarms – MAPL
SetRefreshAlarms Subroutine
41 statements
Source File
private subroutine SetRefreshAlarms(Clock, primaryItem, derivedItem, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Clock), intent(inout) :: Clock
type(PrimaryExport), intent(inout), optional :: primaryItem
type(DerivedExport), intent(inout), optional :: derivedItem
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine SetRefreshAlarms(clock,primaryItem,derivedItem,rc)
     type(ESMF_Clock),              intent(inout) :: Clock
     type(PrimaryExport), optional, intent(inout) :: primaryItem
     type(DerivedExport), optional, intent(inout) :: derivedItem
     integer,             optional, intent(out  ) :: rc
     integer                    :: pindex,cindex,iyy,imm,idd,ihh,imn,isc
     character(len=ESMF_MAXSTR) :: refresh_template,ctInt
     character(len=ESMF_MAXSTR) :: Iam
     type(ESMF_TimeInterval)    :: tInterval
     type(ESMF_Time)            :: current_time
     integer                    :: status
     Iam = "SetRefreshAlarms"
     if (present(primaryItem)) then
        refresh_template = primaryItem%refresh_template
     else if (present(derivedItem)) then
        refresh_template = derivedItem%refresh_template
     end if
     pindex = index(refresh_template,'P')
     if (pindex > 0) then
        call ESMF_ClockGet(Clock,currTime=current_time,rc=status)
        _VERIFY(status)
        ! now get time interval. Put 0000-00-00 in front if not there so parsetimeunits doesn't complain
        ctInt = refresh_template(pindex+1:)
        cindex = index(ctInt,'T')
        if (cindex == 0) ctInt = '0000-00-00T'//trim(ctInt)
        call MAPL_NCIOParseTimeUnits(ctInt,iyy,imm,idd,ihh,imn,isc,status)
        _VERIFY(STATUS)
        call ESMF_TimeIntervalSet(tInterval,yy=iyy,mm=imm,d=idd,h=ihh,m=imn,s=isc,rc=status)
        _VERIFY(STATUS)
        if (present(primaryItem)) then
           primaryItem%update_alarm = simpleAlarm(current_time,tInterval,rc=status)
           _VERIFY(status)
           primaryItem%alarmIsEnabled = .true.
        else if (present(derivedItem)) then
           DerivedItem%update_alarm = simpleAlarm(current_time,tInterval,rc=status)
           _VERIFY(status)
           derivedItem%alarmIsEnabled = .true.
        end if
     end if
     _RETURN(ESMF_SUCCESS)
  end subroutine SetRefreshAlarms
Call graph
setrefreshalarms calls ESMF_ClockGet, ESMF_TimeIntervalSet, mapl_ncioparsetimeunits, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
initialize_ calls setrefreshalarms