SetServices – MAPL
SetServices Subroutine
28 statements
Source File
public subroutine SetServices(GC, RC)
SetServices — Sets IRF services for the MAPL_ExtData
Sets Initialize, Run and Finalize services.
History
12Dec2009 da Silva Design and first implementation.
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
gridded component
integer, optional :: RC
return code
Calls
Source Code
   SUBROUTINE SetServices ( GC, RC )
    type(ESMF_GridComp), intent(INOUT) :: GC  !! gridded component
    integer, optional                  :: RC  !! return code
!
!-------------------------------------------------------------------------
!   Local derived type aliases
!   --------------------------
    type (MAPL_ExtData_State), pointer  :: self   ! internal, that is
    type (MAPL_ExtData_wrap)            :: wrap
    character(len=ESMF_MAXSTR)          :: comp_name
    character(len=ESMF_MAXSTR)          :: Iam
    integer                             :: status
!                              ------------
!   Get my name and set-up traceback handle
!   ---------------------------------------
    Iam = 'SetServices'
    call ESMF_GridCompGet( GC, name=comp_name, _RC )
    Iam = trim(comp_name) // '::' // trim(Iam)
!   Wrap internal state for storing in GC; rename legacyState
!   -------------------------------------
    allocate ( self, stat=STATUS )
    _VERIFY(STATUS)
    wrap%ptr => self
!                       ------------------------
!                       ESMF Functional Services
!                       ------------------------
!   Set the Initialize, Run, Finalize entry points
!   ----------------------------------------------
    call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_INITIALIZE,  Initialize_, _RC )
    call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_RUN,   Run_,        _RC )
    call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_FINALIZE, Finalize_,   _RC )
!   Store internal state in GC
!   --------------------------
    call ESMF_UserCompSetInternalState ( GC, 'MAPL_ExtData_state', wrap, STATUS )
    _VERIFY(STATUS)
!   Generic Set Services
!   --------------------
    call MAPL_GenericSetServices ( GC, _RC )
!   All done
!   --------
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE SetServices
Call graph
setservices calls ESMF_GridCompGet, ESMF_UserCompSetInternalState, mapl_genericsetservices, mapl_gridcompsetentrypoint, mapl_return, mapl_verify
mapl_genericsetservices calls mapl_gridcompsetentrypoint, mapl_return, mapl_verify, mapl_assert, mapl_varspecget, mapl_varspecset, start, checkreq, get_child_gridcomp, get_num_children, mapl_genericconncheck, mapl_genericspecenum, mapl_genericstateclockadd, mapl_getrootgc, mapl_gridcompgetvarspecs, mapl_internalstateretrieve, mapl_labelget, mapl_stategetvarspecs, mapl_wirecomponent
mapl_gridcompsetentrypoint calls mapl_return, mapl_verify, ESMF_GridCompSetEntryPoint, mapl_addmethod, mapl_internalstateretrieve, vector_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception