SetServices – MAPL
SetServices Subroutine
37 statements
Source File
public subroutine SetServices(GC, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, intent(out) :: RC
Calls
Contents
Source Code
SetServices
Source Code
      subroutine SetServices ( GC, RC )
! !ARGUMENTS:
         type(ESMF_GridComp), intent(INOUT) :: GC  ! gridded component
         integer,             intent(  OUT) :: RC  ! return code
         integer                                 :: STATUS
         character(len=ESMF_MAXSTR)              :: COMP_NAME
         type(ESMF_Config)          :: cf
         type(SyntheticFieldSupportWrapper) :: synthWrap
         type(SyntheticFieldSupport), pointer :: synth
         call ESMF_GridCompGet( GC, NAME=COMP_NAME, CONFIG=CF, _RC )
         call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_INITIALIZE,  Initialize_, _RC)
         call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_RUN,   Run_, _RC)
         allocate(synth)
         synthWrap%ptr => synth
         call ESMF_UserCompSetInternalState(gc,wrap_name,synthWrap,_RC)
         call AddState(GC,CF,"IMPORT",_RC)
         call AddState(GC,CF,"EXPORT",_RC)
         call MAPL_AddInternalSpec(GC,&
               short_name='time', &
               long_name='na' , &
               units = 'na', &
               dims = MAPL_DimsHorzOnly, &
               vlocation = MAPL_VLocationCenter, _RC)
         call MAPL_AddInternalSpec(GC,&
               short_name='lats', &
               long_name='na' , &
               units = 'na', &
               dims = MAPL_DimsHorzOnly, &
               vlocation = MAPL_VLocationCenter, _RC)
         call MAPL_AddInternalSpec(GC,&
               short_name='lons', &
               long_name='na' , &
               units = 'na', &
               dims = MAPL_DimsHorzOnly, &
               vlocation = MAPL_VLocationCenter, _RC)
         call MAPL_AddInternalSpec(GC,&
               short_name='i_index', &
               long_name='na' , &
               units = 'na', &
               dims = MAPL_DimsHorzOnly, &
               vlocation = MAPL_VLocationCenter, _RC)
         call MAPL_AddInternalSpec(GC,&
               short_name='j_index', &
               long_name='na' , &
               units = 'na', &
               dims = MAPL_DimsHorzOnly, &
               vlocation = MAPL_VLocationCenter, _RC)
         call MAPL_GenericSetServices ( GC, _RC)
         _RETURN(ESMF_SUCCESS)
      end subroutine SetServices
Call graph
setservices calls esmf_gridcompget, mapl_verify, esmf_usercompsetinternalstate, addstate, mapl_gridcompsetentrypoint, mapl_addinternalspec, mapl_genericsetservices, mapl_return
mapl_verify calls mapl_throw_exception
addstate calls mapl_verify, esmf_configfindlabel, esmf_confignextline, esmf_configgetdim
mapl_gridcompsetentrypoint calls mapl_verify, mapl_return, mapl_internalstateretrieve, mapl_addmethod, esmf_gridcompsetentrypoint
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_genericsetservices calls mapl_verify, mapl_return, mapl_internalstateretrieve, mapl_getrootgc
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_addmethod calls mapl_verify, mapl_return
mapl_stateaddinternalspec calls mapl_verify, mapl_return, mapl_internalstateretrieve, mapl_varspeccreateinlistnew, mapl_varspecgetindex, esmf_configgetattribute, mapl_varspecget, mapl_varspecset, mapl_varspecaddreftolist
mapl_getrootgc calls mapl_verify, mapl_return, mapl_getrootgc, mapl_getobjectfromgc