SetServices – MAPL
SetServices Subroutine
65 statements
Source File
public subroutine SetServices(GC, RC)
Arguments
Type Intent Optional Attributes Name
type(ESMF_GridComp), intent(inout) :: GC
integer, optional :: RC
Calls
Contents
Source Code
SetServices
Source Code
   SUBROUTINE SetServices ( GC, RC )
! !ARGUMENTS:
    type(ESMF_GridComp), intent(INOUT) :: GC  ! gridded component
    integer, optional                  :: RC  ! return code
! !DESCRIPTION: Sets Initialize, Run and Finalize services.
!
! !REVISION HISTORY:
!
!  12Dec2009  da Silva  Design and first implementation.
!
!EOP
!-------------------------------------------------------------------------
!   Local derived type aliases
!   --------------------------
    type (MAPL_ExtData_State), pointer  :: self   ! internal, that is
    type (MAPL_ExtData_wrap)            :: wrap
    character(len=ESMF_MAXSTR)          :: comp_name
    integer                             :: status
!                              ------------
!   Get my name and set-up traceback handle
!   ---------------------------------------
    call ESMF_GridCompGet( GC, name=comp_name, _RC )
!   Wrap internal state for storing in GC; rename legacyState
!   -------------------------------------
    allocate ( self, stat=STATUS )
    _VERIFY(STATUS)
    wrap%ptr => self
!                       ------------------------
!                       ESMF Functional Services
!                       ------------------------
!   Set the Initialize, Run, Finalize entry points
!   ----------------------------------------------
    call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_INITIALIZE,  Initialize_, _RC )
    call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_RUN,   Run_,        _RC )
    call MAPL_GridCompSetEntryPoint ( GC, ESMF_METHOD_FINALIZE, Finalize_,   _RC )
!   Store internal state in GC
!   --------------------------
    call ESMF_UserCompSetInternalState ( GC, 'MAPL_ExtData_state', wrap, STATUS )
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="Initialize", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="Run", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="-Read_Loop", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--CheckUpd", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--Read", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--GridCreate", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--IclientWait", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--PRead", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="---CreateCFIO", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="---prefetch", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="----add-collection", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="----make-reference", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="----RegridStore", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="----request", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="---IclientDone", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="----RegridApply", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="---read-prefetch", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--Swap", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="--Bracket", rc=status)
    _VERIFY(STATUS)
    call MAPL_TimerAdd(gc,name="-Interpolate", rc=status)
    _VERIFY(STATUS)
!   Generic Set Services
!   --------------------
    call MAPL_GenericSetServices ( GC, _RC )
!   All done
!   --------
    _RETURN(ESMF_SUCCESS)
  END SUBROUTINE SetServices
Call graph
setservices calls esmf_gridcompget, mapl_verify, esmf_usercompsetinternalstate, mapl_gridcompsetentrypoint, mapl_timeradd, mapl_genericsetservices, mapl_return
mapl_verify calls mapl_throw_exception
mapl_gridcompsetentrypoint calls mapl_verify, mapl_return, mapl_internalstateretrieve, esmf_gridcompsetentrypoint, mapl_addmethod
mapl_timeradd calls mapl_genericstateclockadd
mapl_genericsetservices calls mapl_verify, mapl_return, mapl_internalstateretrieve, mapl_getrootgc
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_internalstateretrieve calls mapl_verify, mapl_return, mapl_internalstateget, mapl_internalstatecreate
mapl_genericstateclockadd calls mapl_return
mapl_addmethod calls mapl_verify, mapl_return
mapl_getrootgc calls mapl_verify, mapl_return, mapl_getrootgc, mapl_getobjectfromgc
mapl_internalstateget calls esmf_gridcompget, mapl_verify, mapl_return, esmf_usercompgetinternalstate
mapl_internalstatecreate calls esmf_gridcompget, mapl_verify, esmf_usercompsetinternalstate, mapl_return
mapl_getobjectfromgc calls mapl_internalstateget