shake_hand – MAPL
shake_hand Subroutine
14 statements
Source File
private subroutine shake_hand(this, rc)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine shake_hand(this, rc)
      class (ClientThread), intent(inout) :: this
      integer, optional, intent(out) :: rc
      class(AbstractSocket),pointer :: connection
      class (AbstractMessage), pointer :: handshake_msg
      integer :: status
      connection=>this%get_connection()
      call connection%send(HandShakeMessage(),_RC)
      handshake_msg => connection%receive()
      deallocate(handshake_msg)
      _RETURN(_SUCCESS)
   end subroutine shake_hand
Call graph
shake_hand calls get_connection, mapl_return, mapl_verify, receive, send, shake_hand
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception