shake_hand – MAPL
shake_hand Subroutine
16 statements
Source File
private subroutine shake_hand(this, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine shake_hand(this, unusable, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      class (ClientThread), pointer :: clientPtr
      clientPtr =>this%current()
      call clientPtr%shake_hand(_RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine shake_hand
Call graph
shake_hand calls current, mapl_return, mapl_verify, shake_hand, get_connection, receive, send
current calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
v_at_32 calls v_at_size_kind