shavebits – MAPL
shavebits Subroutine
40 statements
Source File
private subroutine shavebits(state, list, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(HistoryCollection), intent(in) :: list
integer, intent(out), optional :: rc
Calls
Called by
Call graph
shavebits calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldget, esmf_stateget, downbit, mapl_assert, mapl_return, mapl_verify
downbit calls downbit1d, downbit2d, downbit3d
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
downbit1d calls downbit2d
downbit2d calls mapl_verify, mapl_shavemantissa32, compute_min_max
downbit3d calls downbit2d
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
compute_min_max calls mapl_return, mapl_verify, mpi_allreduce
run calls shavebits