sizeof_directory – MAPL
sizeof_directory Function
10 statements
Source File
private function sizeof_directory() result(sz)
Arguments
None
Return Value integer
Called by
Source Code
   function sizeof_directory() result(sz)
      integer :: sz
      integer :: sizeof_char, sizeof_integer, sizeof_DirectoryEntry
      integer :: one_integer
      character :: one_char
      sizeof_integer = c_sizeof(one_integer)
      sizeof_char    = c_sizeof(one_char)
      sizeof_DirectoryEntry = MAX_LEN_PORT_NAME*sizeof_char + 1*sizeof_integer
      sz = sizeof_integer + MAX_NUM_PORTS*sizeof_DirectoryEntry
   end function sizeof_directory
Call graph
get_directory calls sizeof_directory
make_directory_window calls sizeof_directory
put_directory calls sizeof_directory
connect_to_client calls get_directory, put_directory
connect_to_server calls get_directory, put_directory
new_directoryservice calls make_directory_window, put_directory
publish calls get_directory, put_directory
terminate_servers calls get_directory
test_put_directory calls get_directory, put_directory
directoryservice calls new_directoryservice
initialize calls connect_to_client, connect_to_server, publish
test_connect calls connect_to_client, connect_to_server, publish
test_connect_multi calls connect_to_client, connect_to_server, publish
test_connect_swap_role calls connect_to_client, connect_to_server, publish
test_connect_with_unused_process calls connect_to_client, connect_to_server, publish
test_publish calls publish
test_stress calls connect_to_client, connect_to_server, publish
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize
time_ave calls initialize
ut_regridding calls initialize