skip_token – MAPL
skip_token Function
7 statements
Source File
private function skip_token(val, preserve) result(skip)
Arguments
Type Intent Optional Attributes Name
integer :: val
logical :: preserve
Return Value logical
Called by
Source Code
   function skip_token(val,preserve) result(skip)
      integer :: val
      logical :: preserve
      logical :: skip
      skip = .false.
      if (val==uninit_time .and. preserve) skip = .true.
   end function skip_token
Call graph
evaluate_token calls skip_token
fill_grads_template calls evaluate_token
create_primary_field calls fill_grads_template
find_any_file calls fill_grads_template
get_file calls fill_grads_template
get_filename_from_template calls fill_grads_template
get_filename_from_template_use_index calls fill_grads_template
getclimyear calls fill_grads_template
getlevs calls fill_grads_template
mapl_cfioreadbundle calls fill_grads_template
mapl_genericfinalize calls fill_grads_template
mapl_genericinitialize calls fill_grads_template
mapl_getcurrentfile calls fill_grads_template
mapl_read_bundle calls fill_grads_template
run calls fill_grads_template
strtemplate calls fill_grads_template
updatebrackettime calls fill_grads_template