skip_var – MAPL
skip_var Function
11 statements
Source File
private function skip_var(this, field, rc) result(skip)
Type Bound
verticalData
Arguments
Type Intent Optional Attributes Name
class(verticalData), intent(inout) :: this
type(ESMF_Field), intent(inout) :: field
integer, intent(out), optional :: rc
Return Value logical
Calls
Source Code
     function skip_var(this,field,rc) result(skip)
        logical :: skip
        class(verticalData), intent(inout) :: this
        type(ESMF_Field), intent(inout) :: field
        integer, optional, intent(out) :: rc
        integer :: status
        character(len=ESMF_MAXSTR) :: name
        call ESMF_FieldGet(field,name=name,rc=status)
        _VERIFY(status)
        skip = trim(name)==trim(this%vvar)
     end function skip_var
Call graph
skip_var calls esmf_fieldget, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize