SOLAR_1D – MAPL
SOLAR_1D Subroutine
261 statements
Source File
private recursive subroutine SOLAR_1D(LONS, LATS, ORBIT, ZTH, SLR, INTV, CLOCK, TIME, currTime, DIST, ZTHB, ZTHD, ZTH1, ZTHN, ZTHP, STEPSIZE, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: LONS(:)
real, intent(in) :: LATS(:)
type(MAPL_SunOrbit), intent(in) :: ORBIT
real, intent(out) :: ZTH(:)
real, intent(out) :: SLR(:)
type(ESMF_TimeInterval), intent(inout), optional :: INTV
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(in), optional :: TIME
type(ESMF_Time), intent(in), optional :: currTime
real, intent(out), optional :: DIST
real, intent(out), optional :: ZTHB(:)
real, intent(out), optional :: ZTHD(:)
real, intent(out), optional :: ZTH1(:)
real, intent(out), optional :: ZTHN(:)
real, intent(out), optional :: ZTHP(:)
real, intent(in), optional :: STEPSIZE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
SOLAR_1D
Source Code
      recursive subroutine SOLAR_1D(LONS, LATS, ORBIT,ZTH,SLR,INTV,CLOCK, &
                                    TIME,currTime,DIST,ZTHB,ZTHD,ZTH1,ZTHN,ZTHP,&
                                    STEPSIZE,RC)
#include "sun.H"
      end subroutine SOLAR_1D
Call graph
solar_1d calls invert_keplers_newton, esmf_clockdestroy, esmf_timeintervalget, mapl_sunorbitcreated, esmf_timeget, float, rect_pmpi, mapl_sungetinsolation, calcradfromta, mapl_return, getiday, esmf_clockadvance, mapl_assert, mapl_verify, esmf_clockget, write_parallel, calctafromea, esmf_clockcreate
mapl_sunorbitcreated calls mapl_return
mapl_sungetinsolation calls solar_1d, solar_arr_int, solar_2d
mapl_return calls mapl_throw_exception, get_error_message
getiday calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_verify calls mapl_throw_exception
write_parallel calls write_parallel_r4_1, write_parallel_r8_1, write_parallel_i4_0, write_parallel_i4_1, write_parallel_r4_0, write_parallel_r8_0, write_parallel_string_0
solar_2d calls mapl_sungetinsolation
solar_arr_int calls mapl_sungetinsolation