SOLAR_2D – MAPL
SOLAR_2D Subroutine
261 statements
Source File
private recursive subroutine SOLAR_2D(LONS, LATS, ORBIT, ZTH, SLR, INTV, CLOCK, TIME, currTime, DIST, ZTHB, ZTHD, ZTH1, ZTHN, ZTHP, STEPSIZE, RC)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: LONS(:,:)
real, intent(in) :: LATS(:,:)
type(MAPL_SunOrbit), intent(in) :: ORBIT
real, intent(out) :: ZTH(:,:)
real, intent(out) :: SLR(:,:)
type(ESMF_TimeInterval), intent(inout), optional :: INTV
type(ESMF_Clock), intent(in), optional :: CLOCK
integer, intent(in), optional :: TIME
type(ESMF_Time), intent(in), optional :: currTime
real, intent(out), optional :: DIST
real, intent(out), optional :: ZTHB(:,:)
real, intent(out), optional :: ZTHD(:,:)
real, intent(out), optional :: ZTH1(:,:)
real, intent(out), optional :: ZTHN(:,:)
real, intent(out), optional :: ZTHP(:,:)
real, intent(in), optional :: STEPSIZE
integer, intent(out), optional :: RC
Calls
Called by
Contents
Source Code
SOLAR_2D
Source Code
      recursive subroutine SOLAR_2D(LONS, LATS, ORBIT,ZTH,SLR,INTV,CLOCK, &
                                    TIME,currTime,DIST,ZTHB,ZTHD,ZTH1,ZTHN,ZTHP,&
                                    STEPSIZE,RC)
#include "sun.H"
      end subroutine SOLAR_2D
Call graph
solar_2d calls esmf_timeintervalget, calctafromea, invert_keplers_newton, mapl_return, esmf_clockadvance, getiday, calcradfromta, esmf_clockdestroy, mapl_assert, esmf_clockget, mapl_sunorbitcreated, mapl_verify, write_parallel, rect_pmpi, esmf_clockcreate, float, mapl_sungetinsolation, esmf_timeget
mapl_return calls get_error_message, mapl_throw_exception
getiday calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_sunorbitcreated calls mapl_return
mapl_verify calls mapl_throw_exception
write_parallel calls write_parallel_i4_0, write_parallel_r4_1, write_parallel_i4_1, write_parallel_r8_0, write_parallel_r4_0, write_parallel_r8_1, write_parallel_string_0
mapl_sungetinsolation calls solar_2d, solar_arr_int, solar_1d
solar_1d calls mapl_sungetinsolation
solar_arr_int calls mapl_sungetinsolation