SORT1SR – MAPL
SORT1SR Subroutine
5 statements
Source File
private subroutine SORT1SR(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: A(:)
real(kind=REAL32), intent(inout) :: B(:)
Calls
Called by
Contents
Source Code
SORT1SR
Source Code
subroutine SORT1SR(A,B)
  integer(kind=INT32),           intent(INOUT) :: A(:)
  real   (kind=REAL32),           intent(INOUT) :: B(:)
  call QSORTS(A,B,size(A),1)
end subroutine SORT1SR
Call graph
sort1sr calls qsorts
mapl_sort calls sort1sr
foo calls mapl_sort
mapl_varread_r4_1d calls mapl_sort
mapl_tilemaskget calls mapl_sort
getnodecomm calls mapl_sort, getnodecomm
mapl_varread_r8_1d calls mapl_sort
arrdescrinit calls mapl_sort
mapl_getimsjms calls mapl_sort
mapl_cfiopartition calls mapl_sort
test_mapl_sort calls mapl_sort
set_optimal_server calls mapl_sort
split_server_pools calls mapl_sort
get_esmf_grid_layout calls mapl_getimsjms
mapl_cfioreadparallel_ calls mapl_cfiopartition
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r8_1d
mapl_statevarread calls mapl_tilemaskget
mapl_fieldwrite calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
writerestart calls mapl_tilemaskget
esmfl_halo_r4_2d calls mapl_getimsjms
set calls mapl_getimsjms
mapl_genericinitialize calls mapl_getimsjms
mapl_gridgetsection calls mapl_getimsjms