SORT1LR – MAPL
SORT1LR Subroutine
5 statements
Source File
private subroutine SORT1LR(A, B)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
real(kind=REAL32), intent(inout) :: B(:)
Calls
Called by
Source Code
subroutine SORT1LR(A,B)
  integer(kind=INT64),           intent(INOUT) :: A(:)
  real   (kind=REAL32),           intent(INOUT) :: B(:)
  call QSORTL(A,B,size(A),1)
end subroutine SORT1LR
Call graph
sort1lr calls qsortl
mapl_sort calls sort1lr
arrdescrinit calls mapl_sort
foo calls mapl_sort
getnodecomm calls mapl_sort
mapl_balancecreate calls mapl_sort
mapl_cfiopartition calls mapl_sort
mapl_getimsjms calls mapl_sort
mapl_tilemaskget calls mapl_sort
mapl_varread_r4_1d calls mapl_sort
mapl_varread_r8_1d calls mapl_sort
mapl_varreadncpar_r4_1d calls mapl_sort
mapl_varreadncpar_r8_1d calls mapl_sort
set_optimal_server calls mapl_sort
sort_four_arrays_by_time calls mapl_sort
sort_three_arrays_by_time calls mapl_sort
split_server_pools calls mapl_sort
test_mapl_sort calls mapl_sort