sort_four_arrays_by_time – MAPL
sort_four_arrays_by_time Subroutine
38 statements
Source File
public subroutine sort_four_arrays_by_time(U, V, T, ID, rc)
Uses
MAPL_SortMod
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8) :: U(:)
real(kind=ESMF_KIND_R8) :: V(:)
real(kind=ESMF_KIND_R8) :: T(:)
integer :: ID(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine sort_four_arrays_by_time(U,V,T,ID,rc)
    use MAPL_SortMod
    real(ESMF_KIND_R8) :: U(:), V(:), T(:)
    integer :: ID(:)
    integer, optional, intent(out) :: rc
    integer :: i, len
    integer, allocatable :: IA(:)
    integer(ESMF_KIND_I8), allocatable :: IX(:)
    real(ESMF_KIND_R8), allocatable :: X(:)
    integer, allocatable :: NX(:)
    _ASSERT(size(U)==size(V), 'U,V different dimension')
    _ASSERT(size(U)==size(T), 'U,T different dimension')
    len = size (T)
    allocate (IA(len), IX(len), X(len), NX(len))
    do i=1, len
       IX(i)=T(i)
       IA(i)=i
    enddo
    call MAPL_Sort(IX,IA)
    X = U
    do i=1, len
       U(i) = X(IA(i))
    enddo
    X = V
    do i=1, len
       V(i) = X(IA(i))
    enddo
    X = T
    do i=1, len
       T(i) = X(IA(i))
    enddo
    NX = ID
    do i=1, len
       ID(i) = NX(IA(i))
    enddo
    _RETURN(_SUCCESS)
  end subroutine sort_four_arrays_by_time
Call graph
sort_four_arrays_by_time calls mapl_assert, mapl_sort, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_sort calls sort1ld, sort1lr, sort1ls, sort1sd, sort1sr, sort1ss, sort2al, sort2as, sort2ld, sort2lr, sort2ls, sort2sd, sort2sr, sort2ss
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
sort1ld calls qsortl
sort1lr calls qsortl
sort1ls calls qsortl
sort1sd calls qsorts
sort1sr calls qsorts
sort1ss calls qsorts
sort2al calls mapl_assert, qsortl
sort2as calls mapl_assert, qsorts
sort2ld calls mapl_assert, qsortl
sort2lr calls mapl_assert, qsortl
sort2ls calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort2sr calls mapl_assert, qsorts
sort2ss calls mapl_assert, qsorts
sort_multi_arrays_by_time calls sort_four_arrays_by_time
create_grid calls sort_four_arrays_by_time