SORT2AS – MAPL
SORT2AS Subroutine
17 statements
Source File
private subroutine SORT2AS(B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
Calls
Called by
Contents
Source Code
SORT2AS
Source Code
subroutine SORT2AS(B,DIM)
  integer(kind=INT32),   intent(INOUT) :: B(:,:)
  integer, optional, intent(IN   ) :: DIM
  integer :: uDIM, rc
  if(present(DIM)) then
     uDIM = DIM
  else
     uDIM = 2
  end if
  _ASSERT(uDIM>0, 'uDim needs to be greater than 0')
  _ASSERT(uDIM<3, 'uDim needs to be less than 3')
  if(uDIM==1) then
     call QSORTS(B(:,1),B(:,2:),size(B,1),-(size(B,2)-1))
  else
     call QSORTS(B(1,:),B(2:,:),size(B,2), (size(B,1)-1))
  end if
end subroutine SORT2AS
Call graph
sort2as calls mapl_assert, qsorts
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_sort calls sort2as
split_server_pools calls mapl_sort
mapl_tilemaskget calls mapl_sort
foo calls mapl_sort
mapl_varread_r4_1d calls mapl_sort
getnodecomm calls mapl_sort, getnodecomm
mapl_getimsjms calls mapl_sort
mapl_varread_r8_1d calls mapl_sort
mapl_cfiopartition calls mapl_sort
arrdescrinit calls mapl_sort
test_mapl_sort calls mapl_sort
set_optimal_server calls mapl_sort
set calls mapl_getimsjms
mapl_gridgetsection calls mapl_getimsjms
mapl_fieldwrite calls mapl_tilemaskget
mapl_statevarwrite calls mapl_tilemaskget
mapl_statevarread calls mapl_tilemaskget
readrestart calls mapl_tilemaskget
mapl_fieldread calls mapl_tilemaskget
writerestart calls mapl_tilemaskget
mapl_varread calls mapl_varread_r4_1d, mapl_varread_r8_1d
mapl_genericinitialize calls mapl_getimsjms
esmfl_halo_r4_2d calls mapl_getimsjms
get_esmf_grid_layout calls mapl_getimsjms
mapl_cfioreadparallel_ calls mapl_cfiopartition