SORT2LS – MAPL
SORT2LS Subroutine
19 statements
Source File
private subroutine SORT2LS(A, B, DIM)
Arguments
Type Intent Optional Attributes Name
integer(kind=INT64), intent(inout) :: A(:)
integer(kind=INT32), intent(inout) :: B(:,:)
integer, intent(in), optional :: DIM
Calls
Called by
Source Code
subroutine SORT2LS(A,B,DIM)
  integer(kind=INT64),   intent(INOUT) :: A(:)
  integer(kind=INT32),   intent(INOUT) :: B(:,:)
  integer, optional, intent(IN   ) :: DIM
  integer :: uDIM, rc
  if(present(DIM)) then
     uDIM = DIM
  else
     uDIM = 2
  end if
  _ASSERT(uDIM>0, 'uDim needs to be greater than 0')
  _ASSERT(uDIM<3, 'uDim needs to be less than 3')
  _ASSERT(size(A)==size(B,uDIM),'needs informative message')
  if(uDIM==1) then
     call QSORTL(A,B,size(A),-size(B,2))
  else
     call QSORTL(A,B,size(A), size(B,1))
  end if
end subroutine SORT2LS
Call graph
sort2ls calls mapl_assert, qsortl
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_sort calls sort2ls
arrdescrinit calls mapl_sort
foo calls mapl_sort
getnodecomm calls mapl_sort
mapl_balancecreate calls mapl_sort
mapl_cfiopartition calls mapl_sort
mapl_getimsjms calls mapl_sort
mapl_tilemaskget calls mapl_sort
mapl_varread_r4_1d calls mapl_sort
mapl_varread_r8_1d calls mapl_sort
mapl_varreadncpar_r4_1d calls mapl_sort
mapl_varreadncpar_r8_1d calls mapl_sort
set_optimal_server calls mapl_sort
sort_four_arrays_by_time calls mapl_sort
sort_three_arrays_by_time calls mapl_sort
split_server_pools calls mapl_sort
test_mapl_sort calls mapl_sort