sort_index – MAPL
sort_index Subroutine
18 statements
Source File
public subroutine sort_index(X, IA, rc)
Uses
MAPL_SortMod
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in) :: X(:)
integer, intent(out) :: IA(:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine sort_index (X, IA, rc)
    use MAPL_SortMod
    real(ESMF_KIND_R8), intent(in) :: X(:)
    integer, intent(out) :: IA(:)            ! index
    integer, optional, intent(out) :: rc
    integer :: i, len
    integer(ESMF_KIND_I8), allocatable :: IX(:)
    _ASSERT (size(X)==size(IA), 'X and IA (its index) differ in dimension')
    len = size (X)
    allocate (IX(len))
    do i=1, len
       IX(i)=X(i)
       IA(i)=i
    enddo
    call MAPL_Sort(IX,IA)
    _RETURN(_SUCCESS)
  end subroutine sort_index
Call graph
sort_index calls mapl_assert, mapl_sort, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_sort calls sort1ld, sort1lr, sort1ls, sort1sd, sort1sr, sort1ss, sort2al, sort2as, sort2ld, sort2lr, sort2ls, sort2sd, sort2sr, sort2ss
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
sort1ld calls qsortl
sort1lr calls qsortl
sort1ls calls qsortl
sort1sd calls qsorts
sort1sr calls qsorts
sort1ss calls qsorts
sort2al calls mapl_assert, qsortl
sort2as calls mapl_assert, qsorts
sort2ld calls mapl_assert, qsortl
sort2lr calls mapl_assert, qsortl
sort2ls calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort2sr calls mapl_assert, qsorts
sort2ss calls mapl_assert, qsorts
create_grid calls sort_index