split_on – MAPL
split_on Subroutine
17 statements
Source File
private subroutine split_on(string, substring, found_string, before_string, after_string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in) :: substring
character(len=:), intent(out), allocatable :: found_string
character(len=:), intent(out), optional, allocatable :: before_string
character(len=:), intent(out), optional, allocatable :: after_string
Called by
Source Code
   subroutine split_on(string, substring, found_string, before_string, after_string)
      character(len=*), intent(in) :: string, substring
      character(len=:), allocatable, intent(out) :: found_string
      character(len=:), optional, allocatable, intent(out) :: before_string, after_string
      integer :: i
      i = index(string, substring)
      found_string = ''
      if(i > 0) found_string = string(i:i+len(substring)-1)
      if(present(before_string)) then
         before_string = ''
         if(i > 1) before_string = string(:i-1)
      end if
      if(present(after_string)) then
         after_string = ''
         if(i + len(substring) <= len(string)) after_string = string(i+len(substring):)
      end if
   end subroutine split_on
Call graph
parse_heartbeat_timestring calls split_on
create_from_parameters calls parse_heartbeat_timestring
fillin_derived calls create_from_parameters
fillin_primary calls create_from_parameters
test_compare_negative_string_to_negative_heartbeat calls create_from_parameters
test_compare_positive_string_to_positive_heartbeat calls create_from_parameters
test_create_from_parameters_heartbeat_negative calls create_from_parameters
test_create_from_parameters_heartbeat_negative_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive_explicit calls create_from_parameters
test_create_from_parameters_heartbeat_positive_negative calls create_from_parameters
test_create_from_parameters_string_negative calls create_from_parameters
test_create_from_parameters_string_positive calls create_from_parameters
test_get_adjusted_time calls create_from_parameters
initialize_ calls fillin_derived, fillin_primary