split_server_pools – MAPL
split_server_pools Subroutine
60 statements
Source File
private subroutine split_server_pools(this, unusable, n_server_split, n_hist_split, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: n_server_split
integer, intent(in), optional :: n_hist_split
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine split_server_pools(this, unusable, n_server_split, n_hist_split, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer),  optional, intent(in) :: unusable
      integer, optional, intent(in) :: n_server_split
      integer, optional, intent(in) :: n_hist_split
      integer, optional, intent(out) :: rc
      integer :: i, nsplit, tsize
      integer, allocatable :: server_sizes(:), tmp_position(:)
      integer :: pos
      tsize = this%server_sizes%size()
      if (tsize == 1) then
         if (this%rank == 0) print*, " oserver is not split"
        _RETURN(_SUCCESS)
      endif
      nsplit = 0
      if (present(n_server_split)) nsplit = n_server_split
      allocate(server_sizes(tsize))
      allocate(tmp_position(tsize))
      do i=1,tsize
         server_sizes(i) = this%server_sizes%at(i)
         tmp_position(i) = i
      enddo
      call MAPL_Sort(server_sizes, tmp_position)
      ! if nsplit is out of scope, pick the mid point
      if (nsplit < server_sizes(1) .or. nsplit > server_sizes(tsize)) then
         pos = tsize/2
      else
         pos = 0
         do i = 1, tsize
            if ( nsplit < server_sizes(i) ) then
               pos = i-1
               exit
            endif
         enddo
         if (pos == 0) pos = tsize/2
      endif
      this%large_total = 0
      this%small_total = 0
      do i = 1, pos
         call this%small_server_pool%push_back(tmp_position(i))
         this%small_total = this%small_total + this%server_sizes%at(tmp_position(i))
      enddo
      do i = pos + 1, tsize
         call this%large_server_pool%push_back(tmp_position(i))
         this%large_total = this%large_total + this%server_sizes%at(tmp_position(i))
      enddo
      this%writeCutoff = 0
      if (present(n_hist_split)) this%writeCutoff = n_hist_split
      if (this%rank == 0) then
         print*, "Oservers are split: ", server_sizes
         print*, "Small pool oserver npes: ", server_sizes(1:pos)
         print*, "Large pool oserver npes: ", server_sizes(pos+1:tsize)
      endif
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine split_server_pools
Call graph
split_server_pools calls at, mapl_sort, mapl_return, push_back
mapl_sort calls sort1ld, sort1lr, sort1ls, sort1sd, sort1sr, sort1ss, sort2al, sort2as, sort2ld, sort2lr, sort2ls, sort2sd, sort2sr, sort2ss
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
sort1ld calls qsortl
sort1lr calls qsortl
sort1ls calls qsortl
sort1sd calls qsorts
sort1sr calls qsorts
sort1ss calls qsorts
sort2al calls mapl_assert, qsortl
sort2as calls mapl_assert, qsorts
sort2ld calls mapl_assert, qsortl
sort2lr calls mapl_assert, qsortl
sort2ls calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort2sr calls mapl_assert, qsorts
sort2ss calls mapl_assert, qsorts
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
initialize calls split_server_pools
main calls split_server_pools