split_string – MAPL
split_string Function
18 statements
Source File
public function split_string(input_string, separator) result(output_string_vec)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_string
character(len=1), intent(in) :: separator
Return Value type(StringVector)
Calls
Called by
Source Code
    function split_string(input_string,separator) result(output_string_vec)
       character(len=*), intent(in) :: input_string
       character(len=1), intent(in) :: separator
       type(StringVector)  :: output_string_vec
       character(len=:), allocatable :: tstring
       integer :: i
       tstring = input_string
       i = 1
       do while(i /=0)
          i = index(tstring,separator)
          if (i > 0) then
             call output_string_vec%push_back(tstring(1:i-1))
             tstring = tstring(i+1:)
          else
             call output_string_vec%push_back(trim(tstring))
          end if
       enddo
    end function split_string
Call graph
split_string calls push_back
process_command_line calls split_string
main calls process_command_line
regrid_util calls main