split_vector – MAPL
split_vector Subroutine
27 statements
Source File
private subroutine split_vector(this, original_key, ucomp, vcomp, unusable, rc)
Type Bound
ExtDataRule
Arguments
Type Intent Optional Attributes Name
class(ExtDataRule), intent(in) :: this
character(len=*), intent(in) :: original_key
type(ExtDataRule), intent(inout) :: ucomp
type(ExtDataRule), intent(inout) :: vcomp
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine split_vector(this,original_key,ucomp,vcomp,unusable,rc)
      class(ExtDataRule), intent(in) :: this
      character(len=*), intent(in) :: original_key
      type(ExtDataRule), intent(inout) :: ucomp,vcomp
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: semi_pos
      character(len=:),allocatable :: uname,vname
      _UNUSED_DUMMY(unusable)
      semi_pos = index(this%file_var,";")
      _ASSERT(semi_pos > 0,"vector rule does not have 2 variables in the file_var")
      uname = this%file_var(1:semi_pos-1)
      vname = this%file_var(semi_pos+1:len_trim(this%file_var))
      ucomp = this
      vcomp = this
      semi_pos = index(original_key,";")
      ucomp%vector_partner = original_key(semi_pos+1:len_trim(original_key))
      vcomp%vector_partner = original_key(1:semi_pos-1)
      ucomp%file_var = uname
      vcomp%file_var = vname
      ucomp%vector_file_partner = vname
      vcomp%vector_file_partner = uname
      ucomp%vector_component = "EW"
      vcomp%vector_component = "NS"
      _RETURN(_SUCCESS)
   end subroutine split_vector
Call graph
split_vector calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
add_new_rule calls split_vector
new_extdataconfig_from_yaml calls add_new_rule, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml
extdataoldtypescreator calls new_extdataoldtypescreator