split – MAPL
split Function
30 statements
Source File
private function split(this, unusable, rc) result(split_communicator)
Type Bound
SimpleCommSplitter
Arguments
Type Intent Optional Attributes Name
class(SimpleCommSplitter), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(SplitCommunicator)
Calls
Called by
Source Code
   function split(this, unusable, rc) result(split_communicator)
      type (SplitCommunicator) :: split_communicator
      class (SimpleCommSplitter), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: color
      integer :: subcommunicator
      integer :: ierror
      integer :: status
      type (CommGroupDescription), pointer :: group_description => null()
      character(:), allocatable :: name
      _UNUSED_DUMMY(unusable)
      color = this%compute_color(rc=status)
      _VERIFY(status)
      call MPI_Comm_split(this%get_shared_communicator(), color, 0, subcommunicator, ierror)
      _VERIFY(ierror)
      if (subcommunicator == MPI_COMM_NULL) then
         _ASSERT(color == MPI_UNDEFINED, "color should not be defined")
         name = NULL_SUBCOMMUNICATOR_NAME
      else
         group_description => this%group_descriptions%at(color)
         name = group_description%name
      end if
      split_communicator = SplitCommunicator(subcommunicator, color, name)
      _RETURN(_SUCCESS)
   end function split
Call graph
split calls mapl_assert, mpi_comm_split, at, compute_color, get_shared_communicator, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
compute_color calls at, get_shared_communicator, mapl_return, mapl_verify, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, comm_group_range, get_node_id, get_node_sizes
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
comm_group_range calls mapl_assert, mapl_return
get_error_message calls at, insert
get_node_id calls get_shared_communicator, mapl_return, mapl_verify, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, mpi_allgather, mpi_bcast, mpi_comm_size
get_node_sizes calls get_shared_communicator, mapl_return, mapl_verify, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, mpi_allgather, mpi_comm_size
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls split
new_multigroupserver calls split
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
initialize_p0 calls create_member_subcommunicator, initialize_io_clients_servers
main calls initialize, create_member_subcommunicator, initialize_ioserver
run_ensemble calls create_member_subcommunicator, initialize_io_clients_servers
time_ave calls initialize
ut_regridding calls initialize
run calls run_ensemble, initialize_io_clients_servers
regrid_util calls main
capdriver_main calls run
driver_gethorzijindex calls run
extdata_driver calls run