split_characters – MAPL
split_characters Subroutine
18 statements
Source File
private subroutine split_characters(characters, token, remainder, delimiters)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: characters
character(len=MAX_CHARACTER_LENGTH), intent(out) :: token
character(len=MAX_CHARACTER_LENGTH), intent(out) :: remainder
character(len=*), intent(in), optional :: delimiters
Called by
Source Code
   subroutine split_characters(characters, token, remainder, delimiters)
      character(len=*), intent(in) :: characters
      character(len=MAX_CHARACTER_LENGTH), intent(out) :: token
      character(len=MAX_CHARACTER_LENGTH), intent(out) :: remainder
      character(len=*), optional, intent(in) :: delimiters
      character(len=:), allocatable :: delims
      integer :: i
      delims = ' '
      if(present(delimiters)) delims = delimiters
      i = scan(characters, delims)
      if(i > 0) then
         token = characters(:(i-1))
         remainder = characters((i+1):)
      else
         token = characters
         remainder = EMPTY_STRING
      endif
   end subroutine split_characters
Call graph
split calls split_characters
convert_cf_time_datetime_string_to_iso8601 calls split
initialize_cf_time calls split
construct_cf_time_integer calls initialize_cf_time
construct_cf_time_real calls initialize_cf_time
extract_iso8601_from_cf_time_cf_time calls convert_cf_time_datetime_string_to_iso8601
cf_time_integer calls construct_cf_time_integer
cf_time_real calls construct_cf_time_real
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time