split – MAPL
split Function
27 statements
Source File
private function split(this, unusable, rc) result(split_communicator)
Type Bound
SimpleCommSplitter
Arguments
Type Intent Optional Attributes Name
class(SimpleCommSplitter), intent(in) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(SplitCommunicator)
Calls
Contents
Source Code
split
Source Code
   function split(this, unusable, rc) result(split_communicator)
      type (SplitCommunicator) :: split_communicator
      class (SimpleCommSplitter), intent(in) :: this
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: color
      integer :: subcommunicator
      integer :: ierror
      integer :: status
      type (CommGroupDescription), pointer :: group_description => null()
      character(:), allocatable :: name
      _UNUSED_DUMMY(unusable)
      color = this%compute_color(rc=status)
      _VERIFY(status)
      call MPI_Comm_split(this%get_shared_communicator(), color, 0, subcommunicator, ierror)
      _VERIFY(ierror)
      if (subcommunicator == MPI_COMM_NULL) then
         _ASSERT(color == MPI_UNDEFINED, "color should not be defined")
         name = NULL_SUBCOMMUNICATOR_NAME
      else
         group_description => this%group_descriptions%at(color)
         name = group_description%name
      end if
      split_communicator = SplitCommunicator(subcommunicator, color, name)
      _RETURN(_SUCCESS)
   end function split
Call graph
split calls get_shared_communicator, mapl_assert, mpi_comm_split, compute_color, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
compute_color calls get_shared_communicator, mapl_return, mapl_verify, comm_group_range, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, get_node_id, get_node_sizes
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
get_node_id calls get_shared_communicator, mapl_return, mapl_verify, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, mpi_allgather, mpi_bcast, mpi_comm_size
get_node_sizes calls get_shared_communicator, mapl_return, mapl_verify, mpi_comm_free, mpi_comm_rank, mpi_comm_split_type, mpi_allgather, mpi_comm_size
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize