spread_scalar – MAPL
spread_scalar Function
16 statements
Source File
private function spread_scalar(source, ncopies, rc) result(vector)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: source
integer, intent(in) :: ncopies
integer, intent(out), optional :: rc
Return Value type(ESMF_Field), allocatable, (:)
Calls
Called by
Source Code
   function spread_scalar(source, ncopies, rc) result(vector)
      type(ESMF_Field), intent(inout) :: source
      integer, intent(in) :: ncopies
      integer, optional, intent(out) :: rc
      type(ESMF_Field), allocatable :: vector(:)
      integer :: i
      integer :: status
      _ASSERT(ncopies > 0, 'ncopies must be positive')
      allocate(vector(ncopies))
      do i=1, ncopies
         call FieldCOPY(source, vector(i), _RC)
      end do
      _RETURN(_SUCCESS)
   end function spread_scalar
Call graph
spread_scalar calls fieldcopy, mapl_assert, mapl_return, mapl_verify
fieldcopy calls copy
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
copy calls mapl_assert, mapl_return, mapl_verify, esmf_fieldget, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldsareconformable calls are_conformable_array, are_conformable_scalar
fieldspread calls spread_scalar