stage_data – MAPL
stage_data Function
33 statements
Source File
private function stage_data(this, collection_id, file_name, var_name, data_reference, unusable, start, rc) result(request_id)
Type Bound
FastClientThread
Arguments
Type Intent Optional Attributes Name
class(FastClientThread), intent(inout) :: this
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(in), optional :: start(:)
integer, intent(out), optional :: rc
Return Value integer
Calls
Source Code
   function stage_data(this, collection_id, file_name, var_name, data_reference, &
        & unusable, start, rc) result(request_id)
      class (FastClientThread), intent(inout) :: this
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(in)  :: start(:)
      integer, optional, intent(out) :: rc
      integer :: request_id, status
      class (AbstractMessage), pointer :: handshake_msg
      class(AbstractSocket),pointer :: connection
      type (LocalMemReference) :: mem_data_reference
      request_id = this%get_unique_request_id()
      connection=>this%get_connection()
      call connection%send(StageDataMessage( &
           request_id, &
           collection_id, &
           file_name, &
           var_name, &
           data_reference,unusable=unusable,start=start),_RC)
      handshake_msg => connection%receive()
      deallocate(handshake_msg)
      associate (id => request_id)
         select type (data_reference)
         type is (LocalMemReference)
            !if localmem is already allocated, no need extra copy. For example, write_restart_by_oserver
            call this%insert_RequestHandle(id, connection%put(id, data_reference))
         class default
            mem_data_reference = LocalMemReference(data_reference%type_kind, data_reference%shape)
            ! copy data out so the client can move on after done message is send
            call data_reference%copy_data_to(mem_data_reference, rc=status)
            _VERIFY(status)
            ! put calls iSend
            call this%insert_RequestHandle(id, connection%put(id, mem_data_reference))
         end select
      end associate
      _RETURN(_SUCCESS)
   end function stage_data
Call graph
stage_data calls copy_data_to, get_connection, get_unique_request_id, insert_requesthandle, mapl_return, mapl_verify, put, receive, send
copy_data_to calls mapl_return, mapl_assert, word_size
get_connection calls mapl_return, mapl_assert
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
word_size calls mapl_return, mapl_assert
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception