stage_nondistributed_data – MAPL
stage_nondistributed_data Subroutine
24 statements
Source File
private subroutine stage_nondistributed_data(this, collection_id, file_name, var_name, data_reference, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
integer, intent(in) :: collection_id
character(len=*), intent(in) :: file_name
character(len=*), intent(in) :: var_name
class(AbstractDataReference), intent(in) :: data_reference
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine stage_nondistributed_data(this, collection_id, file_name, var_name, data_reference, unusable, rc)
      class (ClientManager), intent(inout) :: this
      integer, intent(in) :: collection_id
      character(len=*), intent(in) :: file_name
      character(len=*), intent(in) :: var_name
      class (AbstractDataReference), intent(in) :: data_reference
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      class (clientThread), pointer :: clientPtr
      integer :: request_id, status
      clientPtr => this%current()
      request_id = clientPtr%collective_stage_data(collection_id, file_name, var_name, data_reference, _RC)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(request_id)
   end subroutine stage_nondistributed_data
Call graph
stage_nondistributed_data calls collective_stage_data, current, mapl_return, mapl_verify
collective_stage_data calls mapl_return, mapl_verify, get_connection, get_unique_collective_request_id, insert_requesthandle, put, receive, send
current calls at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
insert_requesthandle calls mapl_return, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
v_at_32 calls v_at_size_kind
bundlepost calls stage_nondistributed_data
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main