start – MAPL
start Subroutine
24 statements
Source File
private subroutine start(this)
Type Bound
OpenMPServer
Arguments
Type Intent Optional Attributes Name
class(OpenMPServer), intent(inout), target :: this
Calls
Source Code
   subroutine start(this)
      class (OpenMPServer),target, intent(inout) :: this
      class (AbstractSocket), pointer :: sckt
      type (AbstractSocketVector) :: sockets
      class (ServerThread),pointer :: threadPtr
      integer :: i,thread_size
      this%terminate = .false.
      sockets = AbstractSocketVector()
      !$omp parallel shared(this,sockets)
      !$omp single
      call this%directory_service%connect_to_client(PortInfo('i_server'),this%comm,sockets,this%terminate)
      this%num_clients=this%num_clients+sockets%size()
      thread_size = sockets%size()
      do i =1,thread_size
         sckt => sockets%at(i)
         !$omp task private(threadPtr),firstprivate(sckt),shared(this)
         allocate(threadPtr,source = ServerThread(sckt,this))
         do while (.true.)
            call threadPtr%run()
            if(threadPtr%do_terminate()) then
               deallocate(threadPtr)
               exit
            endif
         enddo
         !$omp end task
       enddo
      !$omp taskwait
      !$omp end single
      !$omp end parallel
      print*, "terminated successfully"
   end subroutine start
Call graph
start calls connect_to_client, at, do_terminate, run
run calls start, dispatch, get_connection, mapl_return, mapl_verify, receive
dispatch calls mapl_return, mapl_verify, handle
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name