start – MAPL
start Subroutine
29 statements
Source File
private subroutine start(this, rc)
Type Bound
MultiLayerServer
Arguments
Type Intent Optional Attributes Name
class(MultiLayerServer), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine start(this, rc)
      class (MultiLayerServer), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      class (ServerThread), pointer :: thread_ptr => null()
      integer :: i, client_size, status
      logical, allocatable :: mask(:)
      client_size = this%threads%size()
      allocate(this%serverthread_done_msgs(client_size))
      this%serverthread_done_msgs(:) = .false.
      allocate(mask(client_size))
      mask = .false.
      ! loop untill terminate
      do while (.true.)
         do i = 1,client_size
            if ( mask(i)) cycle
            thread_ptr=>this%threads%at(i)
            !handle the message
            call thread_ptr%run(_RC)
            !delete the thread object if it terminates
            if(thread_ptr%do_terminate()) then
               mask(i) = .true.
            endif
         enddo
         if (all(mask)) exit
      enddo
      call this%threads%clear()
      call this%terminate_writers()
      deallocate(mask)
      _RETURN(_SUCCESS)
   end subroutine start
Call graph
start calls at, do_terminate, mapl_return, mapl_verify, run, terminate_writers, v_clear
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls mapl_return, mapl_verify, start, dispatch, get_connection, receive
terminate_writers calls mpi_recv, mpi_send
v_clear calls v_downsize
dispatch calls mapl_return, mapl_verify, handle
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
start_self calls mapl_return, mapl_assert, start, get_name