start_self – MAPL
start_self Subroutine
17 statements
Source File
private subroutine start_self(this, unusable, rc)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout), target :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine start_self(this, unusable, rc)
      class(BaseProfiler), target, intent(inout) :: this
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      logical :: empty_stack
      empty_stack = .true.
      !$omp master
      if (this%stack%size()/= 0) this%status = INCORRECTLY_NESTED_METERS
      empty_stack = this%stack%size()== 0
      if(empty_stack) call this%start(this%root_node)
      !$omp end master
      _ASSERT_RC(empty_stack,"Timer "//this%root_node%get_name()// " is not a fresh self start",INCORRECTLY_NESTED_METERS)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine start_self
Call graph
start_self calls mapl_assert, start, get_name, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize