start_global_memory_profiler – MAPL
start_global_memory_profiler Subroutine
6 statements
Source File
public subroutine start_global_memory_profiler(name)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
Calls
Source Code
   subroutine start_global_memory_profiler(name)
      character(*), intent(in) :: name
      type(MemoryProfiler), pointer :: memory_profiler
      memory_profiler => get_global_memory_profiler()
      call memory_profiler%start(name)
   end subroutine start_global_memory_profiler
Call graph
start_global_memory_profiler calls start, get_global_memory_profiler
start_self calls mapl_assert, start, get_name, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception