start_global_time_profiler – MAPL
start_global_time_profiler Subroutine
12 statements
Source File
public subroutine start_global_time_profiler(unusable, rc)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine start_global_time_profiler(unusable, rc)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(TimeProfiler), pointer :: time_profiler
      integer :: status
      time_profiler => get_global_time_profiler()
      call time_profiler%start(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine start_global_time_profiler
Call graph
start_global_time_profiler calls start, get_global_time_profiler, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_initialize calls start_global_time_profiler
main calls mapl_initialize
new_mapl_cap_from_dso calls mapl_initialize
new_mapl_cap_from_set_services calls mapl_initialize
newextdatadriver calls mapl_initialize
time_ave calls mapl_initialize
ut_regridding calls mapl_initialize
extdatadriver calls newextdatadriver
mapl_cap calls new_mapl_cap_from_dso, new_mapl_cap_from_set_services
comp_testing_driver calls main
regrid_util calls main