start_name – MAPL
start_name Subroutine
25 statements
Source File
private subroutine start_name(this, name, rc)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout), target :: this
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine start_name(this, name, rc)
      class(BaseProfiler), target, intent(inout) :: this
      character(*), intent(in) :: name
      integer, optional, intent(out) :: rc
      class(AbstractMeter), allocatable :: m
      type(MeterNodePtr), pointer :: node_ptr
      class(AbstractMeterNode), pointer :: node
      logical :: stack_is_not_empty
      stack_is_not_empty = .true.
      !$omp master
      if (this%stack%empty()) this%status = INCORRECTLY_NESTED_METERS
      stack_is_not_empty = .not. this%stack%empty()
      if(stack_is_not_empty) then
         node_ptr => this%stack%back()
         node => node_ptr%ptr
         if (.not. node%has_child(name)) then
            m = this%make_meter()
            call node%add_child(name, m) !this%make_meter())
         end if
         node => node%get_child(name)
      end if
      !$omp end master
      _ASSERT_RC(stack_is_not_empty, "Timer <"//name// "> should not start when empty.",INCORRECTLY_NESTED_METERS)
      call this%start(node)
      _RETURN(_SUCCESS)
   end subroutine start_name
Call graph
start_name calls add_child, get_child, has_child, mapl_assert, make_meter, start, mapl_return, vector_back, vector_empty
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
start_self calls mapl_assert, start, mapl_return, get_name