start_node – MAPL
start_node Subroutine
12 statements
Source File
private subroutine start_node(this, node)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout) :: this
class(AbstractMeterNode), intent(inout), target :: node
Calls
Source Code
   subroutine start_node(this, node)
      class(BaseProfiler), intent(inout) :: this
      class(AbstractMeterNode), target, intent(inout) :: node
      class(AbstractMeter), pointer :: t
      type(MeterNodePtr), pointer :: node_ptr
      !$omp master
      allocate(node_ptr)
      node_ptr%ptr => node
      call this%stack%push_back(node_ptr)
      deallocate(node_ptr)
      t => node%get_meter()
      call t%start()
      !$omp end master
   end subroutine start_node
Call graph
start_node calls get_meter, vector_push_back, start
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve