start – MAPL
start Subroutine
69 statements
Source File
private subroutine start(this, rc)
Type Bound
MultiCommServer
Arguments
Type Intent Optional Attributes Name
class(MultiCommServer), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine start(this, rc)
      class (MultiCommServer), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      if ( this%front_comm /= MPI_COMM_NULL) then
         call start_front(_RC)
      endif
      if ( this%back_comm /= MPI_COMM_NULL) then
         call start_back(_RC)
      endif
      call this%splitter%free_sub_comm()
      _RETURN(_SUCCESS)
   contains
      subroutine start_back(rc)
         integer, optional, intent(out) :: rc
         integer :: ierr
         integer :: my_rank, cmd, status
         call MPI_Comm_rank(this%server_comm, my_rank, ierr)
         allocate(this%serverthread_done_msgs(1))
         this%serverthread_done_msgs(:) = .false.
         do while (.true.)
            call MPI_Bcast(cmd, 1, MPI_INTEGER, 0, this%server_comm, ierr)
            if (cmd == -1) exit
            call this%create_remote_win(_RC)
            call this%receive_output_data(_RC)
            call this%put_dataToFile(_RC)
            call this%clean_up(_RC)
         enddo
         _RETURN(_SUCCESS)
      end subroutine start_back
      subroutine start_front(rc)
         integer, optional, intent(out) :: rc
         class (ServerThread), pointer :: thread_ptr => null()
         integer :: i,client_size,ierr
         logical, allocatable :: mask(:)
         integer :: terminate = -1
         integer :: status
         client_size = this%threads%size()
         allocate(this%serverthread_done_msgs(client_size))
         this%serverthread_done_msgs(:) = .false.
         allocate(mask(client_size))
         mask = .false.
         ! loop untill terminate
         do while (.true.)
            do i = 1,client_size
               if ( mask(i)) cycle
               thread_ptr=>this%threads%at(i)
               !handle the message
               call thread_ptr%run(_RC)
               !delete the thread object if it terminates
               if(thread_ptr%do_terminate()) then
                  mask(i) = .true.
               endif
            enddo
            if (all(mask)) exit
         enddo
         call this%threads%clear()
         call MPI_Bcast(terminate, 1, MPI_INTEGER, 0, this%server_comm, ierr)
         deallocate(mask)
         _RETURN(_SUCCESS)
      end subroutine start_front
   end subroutine start
Call graph
start calls mpi_bcast, mpi_comm_rank, at, clean_up, create_remote_win, do_terminate, free_sub_comm, mapl_return, mapl_verify, put_datatofile, receive_output_data, run, v_clear