start_back – MAPL
start_back Subroutine
328 statements
Source File
private subroutine start_back(this, rc)
Type Bound
MultiGroupServer
Arguments
Type Intent Optional Attributes Name
class(MultiGroupServer), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
start_back
Source Code
   subroutine start_back(this, rc)
     class (MultiGroupServer),target, intent(inout) :: this
     integer, optional, intent(out) :: rc
     integer, parameter :: stag = 6782
     integer :: status
     type (StringSet) :: FilesBeingWritten
     allocate(this%serverthread_done_msgs(1))
     this%serverthread_done_msgs(:) = .false.
     if ( this%I_am_back_root ) then
        call start_back_captain(_RC)
     else
        call start_back_writers(_RC)
     endif
     _RETURN(_SUCCESS)
   contains
     subroutine start_back_captain(rc)
       integer, optional, intent(out) :: rc
       integer :: collection_id
       integer :: nwriter_per_node
       integer, allocatable :: idleRank(:,:)   ! idle processors
       integer, allocatable :: num_idlePEs(:) ! how many idle processors in each node of backend server
       integer :: local_rank, node_rank, nth_writer
       integer :: terminate, ierr
       integer :: MPI_STAT(MPI_STATUS_SIZE)
       character(len=FNAME_LEN)         :: FileName
       nwriter_per_node = this%nwriter/this%Node_Num
       allocate(num_idlePEs(0:this%Node_Num-1))
       allocate(idleRank(0:this%Node_Num-1, 0:nwriter_per_node-1), source=-1)
        ! all local ranks are idle at the beginning
       do local_rank = 1, this%nwriter-1
          node_rank = this%node_ranks(local_rank)
          nth_writer = mod(local_rank, nwriter_per_node)
          idleRank(node_rank, nth_writer) = local_rank
       enddo
       num_idlePEs = count(idleRank /=-1, dim = 2)
       do while (.true.)
         ! 1) captain node of back_comm is waiting command from front_comm
         call MPI_recv( collection_id, 1, MPI_INTEGER, &
              this%front_ranks(1), this%back_ranks(1), this%server_comm, &
              MPI_STAT, ierr)
         if (collection_id == -1) exit
         call MPI_recv( FileName, FNAME_LEN , MPI_CHARACTER, &
              this%front_ranks(1), this%back_ranks(1), this%server_comm, &
              MPI_STAT, ierr)
         ! 2) get an idle processor and notify front root
         call dispatch_work(collection_id, idleRank, num_idlePEs, FileName, rc=status)
         _VERIFY(status)
       enddo ! while .true.
       ! terminate writers ( or soldiers) first
       call terminate_back_writers(idleRank, rc=status)
       _VERIFY(status)
       ! at the end , send done message to root of oserver
       ! this serves the syncronization with oserver
       terminate = -1
       call MPI_send(terminate, 1, MPI_INTEGER, 0, 0, this%server_comm, ierr)
       deallocate(num_idlePEs, idleRank)
       _RETURN(_SUCCESS)
     end subroutine start_back_captain
     subroutine dispatch_work(collection_id, idleRank, num_idlePEs, FileName, rc)
       integer, intent(in) :: collection_id
       integer, intent(inout) :: idleRank(0:,0:)
       integer, intent(inout) :: num_idlePEs(0:)
       character(*), intent(in) :: FileName
       integer, optional, intent(out) :: rc
       integer :: MPI_STAT(MPI_STATUS_SIZE)
       integer :: local_rank, idle_writer, nth_writer, node_rank
       integer :: i, ierr, nwriter_per_node
       logical :: flag
       character(len=FNAME_LEN) :: FileDone
       type (StringSetIterator) :: iter
       logical :: found
       ! 2.1)  try to retrieve idle writers
       !       keep looping (waiting) until there are idle processors
       nwriter_per_node = size(idleRank,2)
       found = .false.
       do while (.not. found)
          ! non block probe writers
          do local_rank = 1, this%nwriter-1
             flag = .false.
             call MPI_Iprobe( local_rank, stag, this%back_comm, flag, MPI_STAT, ierr)
             if (flag) then
               call MPI_recv(idle_writer, 1, MPI_INTEGER, &
                             local_rank, stag, this%back_comm, &
                             MPI_STAT, ierr)
               _ASSERT(local_rank == idle_writer, "local_rank and idle_writer should match")
               node_rank = this%node_ranks(local_rank)
               num_idlePEs(node_rank) = num_idlePEs(node_rank) + 1
               nth_writer = mod(local_rank, nwriter_per_node)
               idleRank(node_rank, nth_writer) = local_rank
               call MPI_recv(FileDone, FNAME_LEN, MPI_CHARACTER, &
                             local_rank, stag+1, this%back_comm, &
                             MPI_STAT, ierr)
               iter = FilesBeingWritten%find(FileDone)
               _ASSERT( iter /= FilesBeingWritten%end(), "FileDone should be in the set")
               iter = FilesBeingWritten%erase(iter)
             endif
          enddo
          ! if there is no idle processor, get back to probe
          if (all(num_idlePEs == 0)) cycle
          ! if this file is still being written, get back to probe
          iter = FilesBeingWritten%find(FileName)
          if (iter /= FilesBeingWritten%end()) cycle
          ! get the node with the most idle processors
          node_rank = maxloc(num_idlePEs, dim=1) - 1
          do i = 0, nwriter_per_node -1
            if (idleRank(node_rank,i) /= -1) then
               idle_writer = idleRank(node_rank,i)
               idleRank(node_rank,i) = -1 ! set to -1 when it becomes busy
               num_idlePEs(node_rank) = num_idlePEs(node_rank)-1
               exit
            end if
          enddo
          _ASSERT(1<= idle_writer .and. idle_writer <= this%nwriter-1, "wrong local rank of writer")
          call FilesBeingWritten%insert(FileName)
          found = .true. ! exit the loop after get one idle processor and the file is done
       enddo ! while,  get one idle writer
       ! 2.2) tell front comm which idel_worker is ready
       call MPI_send(idle_writer, 1, MPI_INTEGER, this%front_ranks(1), &
                     this%front_ranks(1), this%server_comm, ierr)
       ! 2.3) forward the collection_id to the idle_writer
       call MPI_send(collection_id, 1, MPI_INTEGER, idle_writer, idle_writer,this%back_comm, ierr)
       _RETURN(_SUCCESS)
     end subroutine dispatch_work
     subroutine terminate_back_writers(idleRank, rc)
       integer, intent(in) :: idleRank(0:,0:)
       integer, optional, intent(out) :: rc
       integer :: MPI_STAT(MPI_STATUS_SIZE)
       integer :: node_rank, local_rank, nth_writer
       integer :: ierr, no_job, nwriter_per_node, idle_writer
       character(len=FNAME_LEN) :: FileDone
       no_job = -1
       nwriter_per_node = size(idleRank, 2)
       do local_rank = 1, this%nwriter -1
          node_rank = this%node_ranks(local_rank)
          nth_writer = mod(local_rank, nwriter_per_node)
          if (idleRank(node_rank, nth_writer) >=1) then
             ! send no_job directly to terminate
             call MPI_send(no_job, 1, MPI_INTEGER, local_rank, local_rank, this%back_comm, ierr)
          else
             ! For busy worker, wait to receive idle_writer and the send no_job
             call MPI_recv( idle_writer, 1, MPI_INTEGER, &
                            local_rank, stag, this%back_comm, &
                            MPI_STAT, ierr)
             call MPI_recv( FileDone, FNAME_LEN, MPI_CHARACTER, &
                            local_rank, stag+1, this%back_comm, &
                            MPI_STAT, ierr)
             _ASSERT(local_rank == idle_writer, "local_rank and idle_writer should match")
             call MPI_send(no_job, 1, MPI_INTEGER, local_rank, local_rank, this%back_comm, ierr)
          endif
       enddo
       _RETURN(_SUCCESS)
     end subroutine terminate_back_writers
     subroutine start_back_writers(rc)
       integer, optional, intent(out) :: rc
       integer :: collection_id
       integer :: i, j
       integer :: msg_size, back_local_rank, status
       integer :: MPI_STAT(MPI_STATUS_SIZE), ierr
       class (AbstractMessage), pointer :: msg
       class(ServerThread), pointer :: thread_ptr
       integer, allocatable :: buffer_fmd(:)
       integer, pointer :: g_1d(:), l_1d(:), g_2d(:,:), l_2d(:,:), g_3d(:,:,:), l_3d(:,:,:)
       integer, pointer :: g_4d(:,:,:,:), l_4d(:,:,:,:), g_5d(:,:,:,:,:), l_5d(:,:,:,:,:)
       integer :: d_rank, request_id
       integer(kind=INT64) :: msize_word, s0, e0, s1, e1, s2, e2, s3, e3, s4, e4, s5, e5
       type (StringAttributeMap) :: vars_map
       type (StringAttributeMapIterator) :: var_iter
       type (IntegerMessageMap) :: msg_map
       type (IntegerMessageMapIterator) :: msg_iter
       class (*), pointer :: x_ptr(:)
       integer , allocatable :: buffer_v(:)
       type (Attribute), pointer :: attr_ptr
       type (Attribute) :: attr_tmp
       type (c_ptr) :: address
       type (ForwardDataAndMessage), target :: f_d_m
       type (FileMetaData) :: fmd
       type(AdvancedMeter) :: file_timer
       real(kind=REAL64) :: time
       character(len=:), allocatable :: filename
       character(len=FNAME_LEN) :: FileDone
       real(kind=REAL64) :: file_size, speed
       class(Logger), pointer :: lgr
       back_local_rank = this%rank
       thread_ptr => this%threads%at(1)
       file_timer = AdvancedMeter(MpiTimerGauge())
       do while (.true.)
         ! 1) get collection id from captain
         call MPI_recv( collection_id, 1, MPI_INTEGER, &
               0, back_local_rank, this%back_comm, &
               MPI_STAT, ierr)
         if (collection_id == -1 ) exit ! exit when get terminate signal
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! sync with create_remote_win from front_com
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         do i = 1, this%nfront
            ! receive extra metadata from front root
            if (i == 1) then
               call MPI_recv( msg_size, 1, MPI_INTEGER,    &
                    this%front_ranks(i), this%back_ranks(back_local_rank+1), this%server_comm, &
                    MPI_STAT, ierr)
               allocate(buffer_fmd(msg_size))
               call MPI_recv( buffer_fmd(1), msg_size, MPI_INTEGER, &
                   this%front_ranks(i), this%back_ranks(back_local_rank+1), this%server_comm, &
                   MPI_STAT, ierr)
            endif
            call MPI_recv( msg_size, 1, MPI_INTEGER,    &
                   this%front_ranks(i), this%back_ranks(back_local_rank+1), this%server_comm, &
                   MPI_STAT, ierr)
            if (allocated(this%buffers(i)%buffer)) deallocate (this%buffers(i)%buffer)
              allocate(this%buffers(i)%buffer(msg_size))
              call MPI_Irecv( this%buffers(i)%buffer(1), msg_size, MPI_INTEGER, &
                   this%front_ranks(i), this%back_ranks(back_local_rank+1), this%server_comm, this%buffers(i)%request, &
                   ierr)
         enddo ! nfront
         ! re-org data
         vars_map = StringAttributeMap()
         msg_map  = IntegerMessageMap()
         file_size = 0.
         do i = 1, this%nfront
            s0 = 1
            f_d_m = ForwardDataAndMessage()
            call MPI_Wait(this%buffers(i)%request, MPI_STAT, ierr)
            call f_d_m%deserialize(this%buffers(i)%buffer)
            deallocate(this%buffers(i)%buffer)
            if (size(f_d_m%idata) ==0) cycle
            file_size = file_size + size(f_d_m%idata)
            do j = 1, f_d_m%msg_vec%size()
               msg => f_d_m%msg_vec%at(j)
               select type (q=>msg)
               type is (CollectiveStageDataMessage)
                  var_iter = vars_map%find(i_to_string(q%request_id))
                  if (var_iter == vars_map%end()) then
                     msize_word = word_size(q%type_kind)*product(int(q%global_count, INT64))
                     allocate(buffer_v(msize_word), source = -1)
                     attr_tmp = Attribute(buffer_v)
                     deallocate(buffer_v)
                     call vars_map%insert(i_to_string(q%request_id),attr_tmp)
                     call attr_tmp%destroy()
                     var_iter = vars_map%find(i_to_string(q%request_id))
                     call msg_map%insert(q%request_id, q)
                  endif
                  attr_ptr => var_iter%value()
                  x_ptr => attr_ptr%get_values()
                  select type (ptr=>x_ptr)
                  type is (integer(INT32))
                     address = c_loc(ptr(1))
                  end select
                  d_rank = size(q%global_count)
                  ! first dimension increases
                  q%global_count(1) = word_size(q%type_kind)*q%global_count(1)
                  q%count(1) = word_size(q%type_kind)*q%count(1)
                  q%start(1) = word_size(q%type_kind)*(q%start(1)-1)+1
                  select case (d_rank)
                  case (0)
                     _FAIL( "scalar ?? ")
                  case (1)
                     call c_f_pointer(address, g_1d, shape=q%global_count)
                     msize_word = product(q%count)
                     e0 = s0 + msize_word - 1
                     l_1d(1:q%count(1))=> f_d_m%idata(s0:e0)
                     s1 = q%start(1)
                     e1 = s1 + q%count(1) - 1
                     g_1d(s1:e1) = l_1d(:)
                     s0 = e0 + 1
                  case (2)
                     call c_f_pointer(address, g_2d, shape=q%global_count)
                     msize_word = product(q%count)
                     e0 = s0 + msize_word - 1
                     l_2d(1:q%count(1),1:q%count(2))=> f_d_m%idata(s0:e0)
                     s1 = q%start(1)
                     e1 = s1 + q%count(1) - 1
                     s2 = q%start(2)
                     e2 = s2 + q%count(2) - 1
                     g_2d(s1:e1,s2:e2) = l_2d(:,:)
                     s0 = e0 + 1
                  case (3)
                     call c_f_pointer(address, g_3d, shape=q%global_count)
                     msize_word = product(q%count)
                     e0 = s0 + msize_word - 1
                     l_3d(1:q%count(1),1:q%count(2),1:q%count(3))=> f_d_m%idata(s0:e0)
                     s1 = q%start(1)
                     e1 = s1 + q%count(1) - 1
                     s2 = q%start(2)
                     e2 = s2 + q%count(2) - 1
                     s3 = q%start(3)
                     e3 = s3 + q%count(3) - 1
                     g_3d(s1:e1,s2:e2,s3:e3) = l_3d(:,:,:)
                     s0 = e0 + 1
                  case (4)
                     call c_f_pointer(address, g_4d, shape=q%global_count)
                     msize_word = product(q%count)
                     e0 = s0 + msize_word - 1
                     l_4d(1:q%count(1),1:q%count(2),1:q%count(3),1:q%count(4))=> f_d_m%idata(s0:e0)
                     s1 = q%start(1)
                     e1 = s1 + q%count(1) - 1
                     s2 = q%start(2)
                     e2 = s2 + q%count(2) - 1
                     s3 = q%start(3)
                     e3 = s3 + q%count(3) - 1
                     s4 = q%start(4)
                     e4 = s4 + q%count(4) - 1
                     g_4d(s1:e1,s2:e2,s3:e3,s4:e4) = l_4d(:,:,:,:)
                     s0 = e0 + 1
                  case (5)
                     call c_f_pointer(address, g_5d, shape=q%global_count)
                     msize_word = product(q%count)
                     e0 = s0 + msize_word - 1
                     l_5d(1:q%count(1),1:q%count(2),1:q%count(3),1:q%count(4), 1:q%count(5))=> f_d_m%idata(s0:e0)
                     s1 = q%start(1)
                     e1 = s1 + q%count(1) - 1
                     s2 = q%start(2)
                     e2 = s2 + q%count(2) - 1
                     s3 = q%start(3)
                     e3 = s3 + q%count(3) - 1
                     s4 = q%start(4)
                     e4 = s4 + q%count(4) - 1
                     s5 = q%start(5)
                     e5 = s5 + q%count(5) - 1
                     g_5d(s1:e1,s2:e2,s3:e3,s4:e4,s5:e5) = l_5d(:,:,:,:,:)
                     s0 = e0 + 1
                  end select
                  ! return to its orignal value
                  q%global_count(1) = q%global_count(1)/word_size(q%type_kind)
                  q%count(1) = q%count(1)/word_size(q%type_kind)
                  q%start(1) = (q%start(1)-1)/word_size(q%type_kind)+1
               end select
             end do ! message vec size
             if(allocated(f_d_m%idata))deallocate(f_d_m%idata)
         enddo ! nfront
         call FileMetadata_deserialize(buffer_fmd, fmd)
         call thread_ptr%hist_collections%push_back(HistoryCollection(fmd))
         msg_iter = msg_map%begin()
         do while (msg_iter /= msg_map%end())
            request_id = msg_iter%key()
            msg =>msg_iter%value()
            var_iter = vars_map%find(i_to_string(request_id))
            attr_ptr =>var_iter%value()
            x_ptr => attr_ptr%get_values()
            select type (ptr=>x_ptr)
            type is (integer(INT32))
                 address = c_loc(ptr(1))
            end select
            select type (q=>msg)
            class is (AbstractDataMessage)
               filename =q%file_name
               call file_timer%start()
               call thread_ptr%put_dataToFile(q, address, _RC)
               call file_timer%stop()
            end select
            call msg_iter%next()
         enddo
         call thread_ptr%clear_hist_collections()
         call thread_ptr%hist_collections%clear()
         time = file_timer%get_total()
         file_size = file_size*4./1024./1024. ! 4-byte integer, unit is converted to MB
         speed = file_size/time
         lgr => logging%get_logger('MAPL.pfio')
         call lgr%info(" Writing time: %f9.3 s, speed: %f9.3 MB/s, size: %f9.3 MB, at server node: %i0~:%i0~, file: %a", time, speed, file_size, this%node_rank, this%innode_rank, filename)
         call file_timer%reset()
         deallocate (buffer_fmd)
         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         ! telling captain it is idle by sending its own rank
         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         call MPI_send(back_local_rank, 1, MPI_INTEGER, 0, stag, this%back_comm , ierr)
         FileDone = Filename
         call MPI_send(FileDone, FNAME_LEN, MPI_CHARACTER, 0, stag+1, this%back_comm , ierr)
       enddo
       _RETURN(_SUCCESS)
     end subroutine start_back_writers
   end subroutine start_back
Call graph
start_back calls mapl_return, mapl_verify, serverthread_done_msgs
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
start calls start_back
clean_up calls start
receive_output_data calls start