StateStatistics – MAPL
StateStatistics Subroutine
10 statements
Source File
private subroutine StateStatistics(srcSTA, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: srcSTA
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
StateStatistics
Source Code
   subroutine StateStatistics(srcSTA, rc)
     implicit NONE
     type(ESMF_State), intent(inout)  :: srcSTA
     integer, optional, intent(out)   :: rc     ! return code
     integer :: status
     call StateDiff(srcSTA, rc=status)
     _VERIFY(status)
     _RETURN(ESMF_SUCCESS)
   end subroutine StateStatistics
Call graph
statestatistics calls statediff, mapl_return, mapl_verify
statediff calls mapl_return, esmf_vmgetcurrent, esmf_stateget, esmf_vmget, mapl_am_i_root, esmfl_failedrc, state2bundle, bundlediff
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
esmfl_failedrc calls esmf_finalize
state2bundle calls mapl_return, mapl_verify, esmf_vmgetcurrent, esmf_stateget, esmf_vmget, mapl_am_i_root, mapl_fieldbundleadd, esmf_fieldget, esmf_fieldbundlecreate, esmf_fieldbundleset, check_list_
bundlediff calls mapl_return, esmf_vmgetcurrent, esmf_vmget, mapl_am_i_root, esmfl_failedrc, arraygather, esmf_vmbarrier, esmf_utilstringint2string, esmf_fieldget, esmf_fieldbundleget, esmfl_fieldgetdims
mapl_throw_exception calls initialize
esmfl_statistics calls statestatistics