StateFilter_R4_3D – MAPL
StateFilter_R4_3D Subroutine
62 statements
Source File
private subroutine StateFilter_R4_3D(state, config, itemName, array, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: state
type(ESMF_Config), intent(inout) :: config
character(len=*), intent(in) :: itemName
real(kind=REAL32), intent(out), allocatable :: array(:,:,:)
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine StateFilter_R4_3D(state, config, itemName, array, rc)
      type(ESMF_State), intent(inout) :: state
      type(ESMF_Config), intent(inout) :: config
      character(len=*), intent(in) :: itemName
      real(REAL32), allocatable, intent(out) :: array(:,:,:)
      integer, optional, intent(out) :: rc
      integer :: status, rank
      character(len=ESMF_MAXSTR) :: filter_expression, field_name
      character(len=:), allocatable :: processed_expression
      type(ESMF_Field) :: new_field, old_field
      logical :: name_Present, default_Present
      real(REAL32), pointer :: ptr3d_new(:,:,:), ptr3d_old(:,:,:)
      type(ESMF_TYPEKIND_FLAG) :: tk
      type(StateMask) :: mask
      call ESMF_StateGet(state, itemName, old_field, _RC)
      call ESMF_FieldGet(old_field, typeKind=tk, rank=rank, _RC)
      _ASSERT(tk==ESMF_TYPEKIND_R4,"wrong typekind when call MAPL_StateFilter")
      _ASSERT(rank==3,"wrong rank when call MAPL_StateFilter")
      call ESMF_FieldGet(old_field, 0, farrayPtr=ptr3d_old, _RC)
      allocate(array( lbound(ptr3d_old,1):ubound(ptr3d_old,1) , lbound(ptr3d_old,2):ubound(ptr3d_old,2), lbound(ptr3d_old,3):ubound(ptr3d_old,3) ),  _STAT)
      array = ptr3d_old
      call ESMF_ConfigFindLabel(config, "FILTER"//separator//trim(itemName)//":", isPresent=name_Present, _RC)
      if (name_Present) then
         call ESMF_ConfigGetAttribute(config, filter_expression, label="FILTER"//separator//trim(itemName)//":", _RC)
      else
         call ESMF_ConfigFindLabel(config, "FILTER"//separator//var_placeholder//":", isPresent=default_Present, _RC)
         _RETURN_UNLESS(default_present)
         call ESMF_ConfigGetAttribute(config, filter_expression, label="FILTER"//separator//var_placeholder//":", _RC)
      end if
      call FieldClone(old_field, new_field, _RC)
      call ESMF_FieldGet(old_field, name=field_name, _RC)
      call ESMF_FieldGet(new_field, 0, farrayPtr=ptr3d_new, _RC)
      ptr3d_new = ptr3d_old
      processed_expression = substitute_name(filter_expression, field_name)
      if (index(processed_expression,"mask") > 0) then
         mask = StateMask(processed_expression)
         call mask%evaluate_mask(state, new_field, _RC)
      else
         call MAPL_StateEval(state, processed_expression, new_field, _RC)
      end if
      array = ptr3d_new
      call ESMF_FieldDestroy(new_field, noGarbage=.true., _RC)
      _RETURN(_SUCCESS)
   end subroutine StateFilter_R4_3d
Call graph
statefilter_r4_3d calls ESMF_ConfigFindLabel, ESMF_ConfigGetAttribute, esmf_fielddestroy, esmf_fieldget, esmf_stateget, fieldclone, mapl_assert, evaluate_mask, mapl_return, mapl_stateeval, mapl_verify, substitute_name
fieldclone calls clone
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
evaluate_mask calls mapl_return, mapl_verify, evaluate_box_mask, evaluate_region_mask, evaluate_zone_mask
mapl_return calls get_error_message, mapl_throw_exception
mapl_stateeval calls esmf_stateget, mapl_assert, mapl_verify, fieldsarebroadcastconformable, bytecode_dealloc, checksyntax, evalf, parsef
mapl_verify calls mapl_throw_exception
substitute_name calls mapl_assert, mapl_return
statefilteritem calls statefilter_r4_3d
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem