StateDiff – MAPL
StateDiff Subroutine
52 statements
Source File
private subroutine StateDiff(srcSTA, dstSTA, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: srcSTA
type(ESMF_State), intent(inout), optional :: dstSTA
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
StateDiff
Source Code
   subroutine StateDiff (srcSTA, dstSTA, rc)
!
! !USES:
!
  implicit NONE
! !ARGUMENTS:
   type(ESMF_State), intent(inout)  :: srcSTA
   type(ESMF_State),optional, intent(inout)  :: dstSTA
   integer, optional, intent(out)   :: rc     ! return code
! !DESCRIPTION:
!     Regrid a state
!
!EOP
! !REVISION HISTORY:
!
!  19Apr2006  Cruz  Initial code.
!
!-------------------------------------------------------------------------
! locals
   type(ESMF_VM)              :: vm
   type(ESMF_FieldBundle)          :: srcBUN
   type(ESMF_FieldBundle)          :: dstBUN
   integer :: status, mype, i, itemcount
   character (len=ESMF_MAXSTR), pointer  :: itemnamelist(:)
   type(ESMF_StateItem_Flag)  , pointer  :: itemtypelist(:)
   character(len=ESMF_MAXSTR), parameter :: IAm = 'StateDiff'
! start
   call ESMF_VMGetCurrent(vm)
   call ESMF_VMGet(vm, localPet=mype, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
! Get information from state
!---------------------------
! query the states for item number and types. If item type is other
! than a field then return(1)
   call ESMF_StateGet(srcSTA, itemcount=itemcount, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   if(itemcount==0) then
      !call ESMFL_FailedRC(mype,Iam//': ESMF_state is empty')
      if (MAPL_AM_I_Root()) print*, "WARNING: "//Iam//': ESMF_state is empty'
      _RETURN(_SUCCESS)
   end if
   allocate(itemnamelist(itemcount), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   allocate(itemtypelist(itemcount), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   call ESMF_StateGet(srcSTA, itemnamelist=itemnamelist, &
                      itemtypelist=itemtypelist, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   do i=1,itemcount
      if(itemtypelist(i)/=ESMF_STATEITEM_FIELD) then
        !call ESMFL_FailedRC(mype,Iam//': State item is not a field.')
        if (MAPL_AM_I_Root()) print*, "WARNING: "//Iam//':  State item is not a field'
      end if
   end do
! populate source bundle with fields from source state
! ----------------------------------------------------
   call State2Bundle (srcSTA, srcBun)
   if(present(dstSTA)) then
      call ESMF_StateGet(dstSTA, itemnamelist=itemnamelist, &
                      itemtypelist=itemtypelist, rc=status)
      if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
      do i=1,itemcount
         if(itemtypelist(i)/=ESMF_STATEITEM_FIELD) then
          ! call ESMFL_FailedRC(mype,Iam//': State item is not a field.')
            if (MAPL_AM_I_Root()) print*, "WARNING: "//Iam//':  State item is not a field'
         end if
      end do
      call State2Bundle (dstSTA, dstBun)
   ! now call BundleDiff
      call BundleDiff (srcBUN, dstBUN, rc=status)
      if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
    else
      call BundleDiff (srcBUN, rc=status)
      if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
    endif
   _RETURN(ESMF_SUCCESS)
   end subroutine StateDiff
Call graph
statediff calls esmf_vmgetcurrent, esmf_stateget, esmf_vmget, mapl_am_i_root, esmfl_failedrc, mapl_return, state2bundle, bundlediff
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
esmfl_failedrc calls esmf_finalize
mapl_return calls mapl_throw_exception, get_error_message
state2bundle calls esmf_vmgetcurrent, esmf_stateget, esmf_vmget, mapl_am_i_root, mapl_return, mapl_fieldbundleadd, mapl_verify, esmf_fieldget, esmf_fieldbundlecreate, esmf_fieldbundleset, check_list_
bundlediff calls esmf_vmgetcurrent, esmf_vmget, mapl_am_i_root, esmfl_failedrc, mapl_return, arraygather, esmf_vmbarrier, esmfl_fieldgetdims, esmf_utilstringint2string, esmf_fieldget, esmf_fieldbundleget
statestatistics calls statediff
esmfl_diff calls statediff
esmfl_statistics calls statestatistics