StateRegrid – MAPL
StateRegrid Subroutine
105 statements
Source File
private subroutine StateRegrid(srcSTA, dstSTA, rc)
The subroutine StateRegrid regrids a state.
History
19Apr2006 Cruz Initial code.
Arguments
Type Intent Optional Attributes Name
type(ESMF_State), intent(inout) :: srcSTA
type(ESMF_State), intent(inout) :: dstSTA
integer, intent(out), optional :: rc
return code
Calls
Called by
Contents
Source Code
StateRegrid
Source Code
   subroutine StateRegrid (srcSTA, dstSTA, rc)
!
  implicit NONE
! !ARGUMENTS:
   type(ESMF_State), intent(inout)  :: srcSTA
   type(ESMF_State), intent(inout)  :: dstSTA
   integer, optional, intent(out)   :: rc      !! return code
!
!-------------------------------------------------------------------------
! locals
   type(ESMF_VM)              :: vm
   type(ESMF_Field)           :: FLD
   type(ESMF_Grid)            :: GRID
   type(ESMF_FieldBundle)          :: srcBUN
   type(ESMF_FieldBundle)          :: dstBUN
   integer :: status, mype, npe, i, itemcount, srcFCount,dstFCount
   character (len=ESMF_MAXSTR), pointer  :: itemnamelist(:)
   character (len=ESMF_MAXSTR), allocatable  :: dstNames(:)
   character (len=ESMF_MAXSTR), allocatable  :: srcNames(:)
   type(ESMF_StateItem_Flag)  , pointer  :: itemtypelist(:)
   character(len=ESMF_MAXSTR)            :: name
   character(len=ESMF_MAXSTR), parameter :: IAm = 'StateRegrid'
! start
   call ESMF_VMGetCurrent(vm)
   call ESMF_VMGet(vm, localPet=mype, petCount=npe, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
! Get information from src state
!-------------------------------
! query the states for item number and types. If item type is other
! than a field then return(1)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   call ESMF_StateGet(srcSTA, itemcount=itemcount, rc=status)
   if(itemcount==0) then
      call ESMFL_FailedRC(mype,Iam//': ESMF_state is empty')
   end if
   allocate(itemnamelist(itemcount), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   allocate(itemtypelist(itemcount), stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   call ESMF_StateGet(srcSTA, itemnamelist=itemnamelist, &
                      itemtypelist=itemtypelist, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   srcFCount=0
   do i=1,itemcount
      if(itemtypelist(i)==ESMF_STATEITEM_FIELD) then
        srcFCount=srcFCount+1
        !call ESMFL_FailedRC(mype,trim(Iam)//': State item '//trim(itemNameList(i))//' is not a field.')
      end if
   end do
   allocate(srcNames(srcFCount))
   srcFCount=0
   do i=1,itemcount
      if(itemtypelist(i)==ESMF_STATEITEM_FIELD) then
        srcFCount=srcFCount+1
        srcNames(srcFCount)=trim(itemNameList(i))
      end if
   end do
! get grid from first field in state, and create bundle
   if(verbose .and. mype==MAPL_Root) print *, ' Get grid from ',trim(srcNames(1))
   call ESMF_StateGet(srcSTA, trim(srcNames(1)), FLD, &
                      rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_StateGetField failed')
   call ESMF_StateGet(srcSTA, name=name, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_StateGet failed')
   name = name//'to bundle'
   call ESMF_FieldGet (FLD, grid=GRID, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_FieldGet failed')
   ! create bundle with input grid
   srcBUN = ESMF_FieldBundleCreate ( name=name, rc=status )
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' src ESMF_FieldBundleCreate failed' )
   call ESMF_FieldBundleSet(srcBUN, grid, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' src ESMF_FieldBundleSet failed' )
! populate source bundle
   call ESMFL_StateGetField(srcSTA, srcNames , srcBUN, RC=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' SRC ESMFL_StateGetField failed')
! Get information from dst state
!-------------------------------
   call ESMF_StateGet(dstSTA, itemcount=itemcount, rc=status)
   _VERIFY(status)
   deallocate(itemNameList)
   deallocate(itemTypeList)
   allocate(itemNameList(itemCount))
   allocate(itemTypeList(itemCount))
   call ESMF_StateGet(dstSTA, itemnamelist=itemnamelist, &
                      itemtypelist=itemtypelist, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   dstFCount=0
   do i=1,itemcount
      if(itemtypelist(i)==ESMF_STATEITEM_FIELD) then
        dstFCount=dstFCount+1
      end if
   end do
   allocate(dstNames(dstFCount))
   dstFCount=0
   do i=1,itemcount
      if(itemtypelist(i)==ESMF_STATEITEM_FIELD) then
        dstFCount=dstFCount+1
        dstNames(dstFCount)=trim(itemNameList(i))
      end if
   end do
   _ASSERT(dstFCount==srcFCount,"source and destination bundle sizes do not match")
! get grid from first field in state, and create bundle
   if(verbose .and. mype==MAPL_Root) print *, ' Get grid from ',trim(dstNames(1))
   call ESMF_StateGet(dstSTA, trim(dstNames(1)), FLD, &
                      rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_StateGetField failed')
   call ESMF_StateGet(dstSTA, name=name, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_StateGet failed')
   name = name//'to bundle'
   call ESMF_FieldGet (FLD, grid=GRID, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_FieldGet failed')
   ! create bundle with input grid
   dstBUN = ESMF_FieldBundleCreate ( name=name, rc=status )
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' ESMF_FieldBundleCreate failed' )
   call ESMF_FieldBundleSet(dstBUN, grid, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' src ESMF_FieldBundleSet failed' )
! populate destination bundle
   call ESMFL_StateGetField(dstSTA, dstNames, dstBUN, RC=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam//' DST ESMFL_StateGetField failed')
! now call BundleRegrid
   call BundleRegrid (srcBUN, dstBUN, rc=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
! clean up
   deallocate(itemnamelist, stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   deallocate(itemtypelist, stat=status)
   if (status /= ESMF_SUCCESS) call ESMFL_FailedRC(mype,Iam)
   _RETURN(ESMF_SUCCESS)
   end subroutine StateRegrid
Call graph
stateregrid calls ESMF_VMGet, ESMF_VMGetCurrent, esmf_fieldbundlecreate, esmf_fieldbundleset, esmf_fieldget, esmf_stateget, mapl_assert, bundleregrid, esmfl_failedrc, esmfl_stategetfield, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
bundleregrid calls ESMF_VMGet, ESMF_VMGetCurrent, esmfl_failedrc, mapl_return
esmfl_failedrc calls ESMF_Finalize
esmfl_stategetfield calls esmf_stateget, mapl_assert, mapl_return, mapl_verify, esmf_fieldbundleget, esmf_fieldemptycreate, mapl_allocatecoupling, mapl_fieldbundleadd, mapl_fieldcreate
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_allocatecoupling calls mapl_allocatecoupling
mapl_fieldbundleadd calls mapl_fieldbundleaddfield
mapl_fieldcreate calls mapl_fieldcreatenewgrid, mapl_fieldcreater4, mapl_fieldcreaterename
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
esmfl_regrid calls stateregrid