step_model – MAPL
step_model Subroutine
9 statements
Source File
private subroutine step_model(this, rc)
Type Bound
MAPL_Cap
Arguments
Type Intent Optional Attributes Name
class(MAPL_Cap), intent(inout) :: this
integer, intent(out) :: rc
Calls
Called by
Source Code
   subroutine step_model(this, rc)
     class(MAPL_Cap), intent(inout) :: this
     integer, intent(out) :: rc
     integer :: status
     call this%cap_gc%step(rc = status); _VERIFY(status)
     _RETURN(_SUCCESS)
   end subroutine step_model
Call graph
step_model calls mapl_return, mapl_verify, step
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
step calls mapl_return, mapl_verify, ESMF_ClockAdvance, ESMF_ClockGet, ESMF_GridCompGet, ESMF_GridCompRun, ESMF_GridCompWriteRestart, ESMF_TimeGet, ESMF_VMBarrier, mapl_am_i_root, mpi_wtime, get_step_counter, mapl_memcommited, mapl_memused, perpetual_clock
model_advance calls step_model