step – MAPL
step Subroutine
116 statements
Source File
private subroutine step(this, unusable, phase, rc)
Type Bound
MAPL_CapGridComp
Arguments
Type Intent Optional Attributes Name
class(MAPL_CapGridComp), intent(inout) :: this
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(in), optional :: phase
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine step(this, unusable, phase, rc)
    class(MAPL_CapGridComp), intent(inout) :: this
    class(KeywordEnforcer), optional, intent(in   ) :: unusable
    integer, optional, intent(in) :: phase
    integer, optional, intent(out) :: rc
    integer :: status, phase_
    real(kind=REAL64) :: END_RUN_TIMER, END_TIMER
    _UNUSED_DUMMY(unusable)
    phase_ = 1
    if (present(phase)) phase_ = phase
    call ESMF_GridCompGet(this%gc, vm = this%vm)
    ! Run the ExtData Component
    ! --------------------------
    if (phase_ == 1) then
      call first_phase(rc=status)
      _VERIFY(status)
    endif ! phase_ == 1
    ! Run the Gridded Component
    ! --------------------------
    call ESMF_GridCompRun(this%gcs(this%root_id), importstate = this%child_imports(this%root_id), &
         exportstate = this%child_exports(this%root_id), &
         clock = this%clock, phase=phase_, userrc = status)
    _VERIFY(status)
    ! Advance the Clock and run History and Record
    ! ---------------------------------------------------
    if (phase_ == this%n_run_phases) then
       call last_phase(rc=status)
       _VERIFY(STATUS)
    endif !phase_ == last
    _RETURN(ESMF_SUCCESS)
  contains
     subroutine first_phase(rc)
        integer, optional, intent(out) :: rc
        integer :: status
        if (this%compute_throughput) then
           if (.not.this%started_loop_timer) then
              this%starts%loop_start_timer = MPI_WTime()
              this%started_loop_timer=.true.
           end if
           this%starts%start_timer = MPI_Wtime()
        end if
        call ESMF_GridCompRun(this%gcs(this%extdata_id), importState = this%child_imports(this%extdata_id), &
             exportState = this%child_exports(this%extdata_id), &
             clock = this%clock, userrc = status)
         _VERIFY(status)
        ! Call Record for intermediate checkpoint (if desired)
        ! ------------------------------------------------------
        call ESMF_GridCompWriteRestart(this%gcs(this%root_id), importstate = this%child_imports(this%root_id), &
             exportstate = this%child_exports(this%root_id), &
             clock = this%clock_hist, userrc = status)
        _VERIFY(status)
        call ESMF_GridCompWriteRestart(this%gcs(this%history_id), importstate = this%child_imports(this%history_id), &
             exportstate = this%child_exports(this%history_id), &
             clock = this%clock_hist, userrc = status)
        _VERIFY(status)
        if (this%compute_throughput) then
           call ESMF_VMBarrier(this%vm,rc=status)
           _VERIFY(status)
           this%starts%start_run_timer = MPI_WTime()
        end if
        _RETURN(_SUCCESS)
     end subroutine
     subroutine last_phase(rc)
        integer, optional, intent(out) :: rc
        integer :: status
        if (this%compute_throughput) then
           call ESMF_VMBarrier(this%vm,rc=status)
           _VERIFY(status)
           end_run_timer = MPI_WTime()
        end if
        call ESMF_ClockAdvance(this%clock, rc = status)
        _VERIFY(STATUS)
        call ESMF_ClockAdvance(this%clock_hist, rc = status)
        _VERIFY(STATUS)
        ! Update Perpetual Clock
        ! ----------------------
        if (this%lperp) then
           call Perpetual_Clock(this, status)
           _VERIFY(status)
        end if
        call ESMF_GridCompRun(this%gcs(this%history_id), importstate=this%child_imports(this%history_id), &
             exportstate = this%child_exports(this%history_id), &
             clock = this%clock_hist, userrc = status)
        _VERIFY(status)
        ! Estimate throughput times
        ! ---------------------------
        if (this%compute_throughput) then
           call print_throughput(rc=status)
           _VERIFY(STATUS)
        end if
        _RETURN(_SUCCESS)
     end subroutine
     subroutine print_throughput(rc)
        integer, optional, intent(out) :: rc
        integer :: status, n
        real(kind=REAL64) ::  TIME_REMAINING
        real(kind=REAL64) ::  LOOP_THROUGHPUT
        real(kind=REAL64) ::  INST_THROUGHPUT
        real(kind=REAL64) ::  RUN_THROUGHPUT
        real              :: mem_total, mem_commit, mem_committed_percent
        real              :: mem_used, mem_used_percent
        type(ESMF_Time)   :: currTime
        type(ESMF_TimeInterval) :: delt
        integer                 :: AGCM_YY, AGCM_MM, AGCM_DD, AGCM_H, AGCM_M, AGCM_S
        integer                 :: HRS_R, MIN_R, SEC_R
        call ESMF_ClockGet(this%clock, CurrTime = currTime, rc = status)
        _VERIFY(status)
        call ESMF_TimeGet(CurrTime, YY = AGCM_YY, &
            MM = AGCM_MM, &
            DD = AGCM_DD, &
            H  = AGCM_H , &
            M  = AGCM_M , &
            S  = AGCM_S, rc=status)
        _VERIFY(status)
        delt=currTime-this%cap_restart_time
        ! Call system clock to estimate throughput simulated Days/Day
        call ESMF_VMBarrier( this%vm, RC=STATUS )
        _VERIFY(STATUS)
        END_TIMER = MPI_Wtime()
        n=this%get_step_counter()
        !GridCompRun Timer [Inst]
        RUN_THROUGHPUT  = REAL(  this%HEARTBEAT_DT,kind=REAL64)/(END_RUN_TIMER-this%starts%start_run_timer)
        ! Time loop throughput [Inst]
        INST_THROUGHPUT = REAL(  this%HEARTBEAT_DT,kind=REAL64)/(END_TIMER-this%starts%start_timer)
        ! Time loop throughput [Avg]
        LOOP_THROUGHPUT = REAL(n*this%HEARTBEAT_DT,kind=REAL64)/(END_TIMER-this%starts%loop_start_timer)
        ! Estimate time remaining (seconds)
        TIME_REMAINING = REAL((this%nsteps-n)*this%HEARTBEAT_DT,kind=REAL64)/LOOP_THROUGHPUT
        HRS_R = FLOOR(TIME_REMAINING/3600.0)
        MIN_R = FLOOR(TIME_REMAINING/60.0  -   60.0*HRS_R)
        SEC_R = FLOOR(TIME_REMAINING       - 3600.0*HRS_R - 60.0*MIN_R)
        ! Reset Inst timer
        this%starts%start_timer = END_TIMER
        ! Get percent of used memory
        call MAPL_MemUsed ( mem_total, mem_used, mem_used_percent, RC=STATUS )
        _VERIFY(STATUS)
        ! Get percent of committed memory
        call MAPL_MemCommited ( mem_total, mem_commit, mem_committed_percent, RC=STATUS )
        _VERIFY(STATUS)
        if( mapl_am_I_Root(this%vm) ) write(6,1000) AGCM_YY,AGCM_MM,AGCM_DD,AGCM_H,AGCM_M,AGCM_S,&
                                      LOOP_THROUGHPUT,INST_THROUGHPUT,RUN_THROUGHPUT,HRS_R,MIN_R,SEC_R,&
                                      mem_committed_percent,mem_used_percent
    1000 format(1x,'AGCM Date: ',i4.4,'/',i2.2,'/',i2.2,2x,'Time: ',i2.2,':',i2.2,':',i2.2, &
                2x,'Throughput(days/day)[Avg Tot Run]: ',f12.1,1x,f12.1,1x,f12.1,2x,'TimeRemaining(Est) ',i3.3,':',i2.2,':',i2.2,2x, &
                f5.1,'% : ',f5.1,'% Mem Comm:Used')
        _RETURN(_SUCCESS)
     end subroutine
  end subroutine step
Call graph
step calls ESMF_ClockAdvance, ESMF_ClockGet, ESMF_GridCompGet, ESMF_GridCompRun, ESMF_GridCompWriteRestart, ESMF_TimeGet, ESMF_VMBarrier, mapl_am_i_root, mpi_wtime, get_step_counter, mapl_memcommited, mapl_memused, mapl_return, mapl_verify, perpetual_clock
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_memcommited calls mapl_return, mapl_rtrn, get_unit
mapl_memused calls mapl_return, mapl_rtrn, get_unit
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
perpetual_clock calls ESMF_ClockGet, ESMF_TimeGet, mapl_return, mapl_verify, ESMF_AlarmRingerOff, ESMF_AlarmRingerOn, ESMF_ClockGetAlarm, ESMF_TimeSet, mapl_getlogger, debug, esmfl_clockset
run_mapl_gridcomp calls step
step_model calls step
model_advance calls step_model
run_gc calls run_mapl_gridcomp