stop_global_time_profiler – MAPL
stop_global_time_profiler Subroutine
12 statements
Source File
public subroutine stop_global_time_profiler(unusable, rc)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
stop_global_time_profiler
Source Code
   subroutine stop_global_time_profiler(unusable, rc)
      class (KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(TimeProfiler), pointer :: time_profiler
      integer :: status
      time_profiler => get_global_time_profiler()
      call time_profiler%stop(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine stop_global_time_profiler
Call graph
stop_global_time_profiler calls get_global_time_profiler, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
mapl_finalize calls stop_global_time_profiler
finalize_mpi calls mapl_finalize
main calls mapl_finalize
run calls mapl_finalize, run, finalize_mpi
time_ave calls mapl_finalize
ut_regridding calls mapl_finalize
comp_testing_driver calls main
extdata_driver calls run
regrid_util calls main