stop_name – MAPL
stop_name Subroutine
17 statements
Source File
private subroutine stop_name(this, name, rc)
Type Bound
BaseProfiler
Arguments
Type Intent Optional Attributes Name
class(BaseProfiler), intent(inout) :: this
character(len=*), intent(in) :: name
integer, intent(out), optional :: rc
Calls
Contents
Source Code
stop_name
Source Code
   subroutine stop_name(this, name, rc)
      class(BaseProfiler), intent(inout) :: this
      character(*), intent(in) :: name
      integer, optional, intent(out) :: rc
      type(MeterNodePtr), pointer :: node_ptr
      class(AbstractMeterNode), pointer :: node
      logical :: name_is_node_name
      name_is_node_name = .true.
      !$omp master
      node_ptr => this%stack%back()
      node => node_ptr%ptr
      if (name /= node%get_name()) this%status = INCORRECTLY_NESTED_METERS
      name_is_node_name = name == node%get_name()
      if(name_is_node_name) call this%stop(node)
      !$omp end master
      _ASSERT_RC(name_is_node_name,"Timer <"//name// "> does not match start timer <"//node%get_name()//">",INCORRECTLY_NESTED_METERS)
      _RETURN(_SUCCESS)
   end subroutine stop_name
Call graph
stop_name calls mapl_assert, get_name, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize