stop – MAPL
stop Subroutine
11 statements
Source File
private subroutine stop(this)
Type Bound
AdvancedMeter
Arguments
Type Intent Optional Attributes Name
class(AdvancedMeter), intent(inout) :: this
Calls
Source Code
   subroutine stop(this)
      class(AdvancedMeter), intent(inout) :: this
      real(kind=REAL64) :: increment
      !$omp master
      if (.not. this%active) then
         this%status = MAPL_METER_STOP_INACTIVE
      else
         this%active = .false.
         increment = this%gauge%get_measurement() - this%start_value
         call this%add_cycle(increment)
      end if
      !$omp end master
   end subroutine stop
Call graph
stop calls get_measurement, add_cycle
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles