StringVector_serialize – MAPL
StringVector_serialize Subroutine
17 statements
Source File
public subroutine StringVector_serialize(strVec, buffer)
Arguments
Type Intent Optional Attributes Name
type(StringVector), intent(in) :: strVec
integer, intent(inout), allocatable :: buffer(:)
Calls
Called by
Source Code
   subroutine StringVector_serialize(strVec,buffer)
       type (StringVector) ,intent(in):: strVec
       integer, allocatable,intent(inout) :: buffer(:)
       type (StringVectorIterator) :: iter
       character(len=:),pointer :: str
       integer :: length
       if (allocated(buffer)) deallocate(buffer)
       allocate(buffer(0))
       iter = strVec%begin()
       do while (iter /= strVec%end())
          str => iter%get()
          buffer=[buffer,serialize_intrinsic(str)]
          call iter%next()
       enddo
       length = serialize_buffer_length(length) + size(buffer)
       buffer = [serialize_intrinsic(length),buffer]
    end subroutine StringVector_serialize
Call graph
stringvector_serialize calls begin, get, serialize_buffer_length, serialize_intrinsic, next
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return
serialize calls stringvector_serialize, serialize, stringvariablemap_serialize
get_length calls serialize, stringvariablemap_get_length
historycollectionvector_serialize calls serialize
receive_output_data calls serialize
stringvariablemap_serialize calls serialize
test_serialize calls serialize
create_remote_win calls historycollectionvector_serialize
stringvariablemap_get_length calls stringvariablemap_serialize
start calls create_remote_win