StringVariableMap_serialize – MAPL
StringVariableMap_serialize Subroutine
27 statements
Source File
public subroutine StringVariableMap_serialize(map, buffer, rc)
Arguments
Type Intent Optional Attributes Name
type(StringVariableMap), intent(in) :: map
integer, intent(inout), allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
StringVariableMap_serialize
Source Code
    subroutine StringVariableMap_serialize(map, buffer, rc)
       type (StringVariableMap) ,intent(in):: map
       integer, allocatable,intent(inout) :: buffer(:)
       integer, optional, intent(out) :: rc
       type (StringVariableMapIterator) :: iter
       character(len=:),pointer :: key
       class(Variable),pointer :: var_ptr
       integer :: length, status
       integer, allocatable :: tmp_buffer(:)
       if (allocated(buffer)) deallocate(buffer)
       allocate(buffer(0))
       iter = map%begin()
       do while (iter /= map%end())
          key => iter%key()
          buffer=[buffer,serialize_intrinsic(key)]
          var_ptr => iter%value()
          call var_ptr%serialize(tmp_buffer, status)
          _VERIFY(status)
          buffer = [buffer, tmp_buffer]
          deallocate(tmp_buffer)
          call iter%next()
       enddo
       length = serialize_buffer_length(length)+size(buffer)
       buffer = [serialize_intrinsic(length),buffer]
       _RETURN(_SUCCESS)
    end subroutine StringVariableMap_serialize
Call graph
stringvariablemap_serialize calls serialize_intrinsic, mapl_return, mapl_verify, serialize_buffer_length
serialize_intrinsic calls serialize_logical_1d, serialize_string, serialize_int64_1d, serialize_int32_0d, serialize_int64_0d, serialize_real32_1d, serialize_real64_0d, serialize_logical_0d, serialize_int32_1d, serialize_real32_0d, serialize_real64_1d
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
serialize_buffer_length calls serialize_buffer_length_real32_0d, serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_real64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_string, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d
serialize_buffer_length_real32_0d calls mapl_return, word_size
mapl_throw_exception calls initialize
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_string calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_int32_0d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_int64_0d calls mapl_return
serialize_logical_0d calls mapl_return
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_int32_1d calls mapl_return
serialize_real32_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
word_size calls mapl_return, mapl_assert
stringvariablemap_get_length calls stringvariablemap_serialize
serialize calls stringvariablemap_serialize
get_length calls stringvariablemap_get_length