string_to_esmf_timeinterval – MAPL
string_to_esmf_timeinterval Function
71 statements
Source File
public function string_to_esmf_timeinterval(time_interval_string, unusable, rc) result(time_interval)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: time_interval_string
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_TimeInterval)
Calls
Called by
Source Code
   function string_to_esmf_timeinterval(time_interval_string,unusable,rc) result(time_interval)
      character(len=*), intent(in) :: time_interval_string
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ESMF_TimeInterval) :: time_interval
      integer :: status
      integer :: strlen,ppos,cpos,lpos,tpos
      integer year,month,day,hour,min,sec
      character(len=:), allocatable :: date_string,time_string
      _UNUSED_DUMMY(unusable)
      year=0
      month=0
      day=0
      hour=0
      min=0
      sec=0
      strlen = len_trim(time_interval_string)
      tpos = index(time_interval_string,'T')
      ppos = index(time_interval_string,'P')
      _ASSERT(time_interval_string(1:1) == 'P','Not valid time duration')
      if (tpos /= 0) then
         if (tpos /= ppos+1) then
            date_string = time_interval_string(ppos+1:tpos-1)
         end if
         time_string = time_interval_string(tpos+1:strlen)
      else
         date_string = time_interval_string(ppos+1:strlen)
      end if
      if (allocated(date_string)) then
         strlen = len_trim(date_string)
         lpos = 0
         cpos = index(date_string,'Y')
         if (cpos /= 0) then
            read(date_string(lpos+1:cpos-1),*)year
            lpos = cpos
         end if
         cpos = index(date_string,'M')
         if (cpos /= 0) then
            read(date_string(lpos+1:cpos-1),*)month
            lpos = cpos
         end if
         cpos = index(date_string,'D')
         if (cpos /= 0) then
            read(date_string(lpos+1:cpos-1),*)day
            lpos = cpos
         end if
      end if
      if (allocated(time_string)) then
         strlen = len_trim(time_string)
         lpos = 0
         cpos = index(time_string,'H')
         if (cpos /= 0) then
            read(time_string(lpos+1:cpos-1),*)hour
            lpos = cpos
         end if
         cpos = index(time_string,'M')
         if (cpos /= 0) then
            read(time_string(lpos+1:cpos-1),*)min
            lpos = cpos
         end if
         cpos = index(time_string,'S')
         if (cpos /= 0) then
            read(time_string(lpos+1:cpos-1),*)sec
            lpos = cpos
         end if
      end if
      call ESMF_TimeIntervalSet(time_interval,yy=year,mm=month,d=day,h=hour,m=min,s=sec,_RC)
      _RETURN(_SUCCESS)
   end function string_to_esmf_timeinterval
Call graph
string_to_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
create_from_parameters calls string_to_esmf_timeinterval
new_extdatafilestream calls string_to_esmf_timeinterval
extdatafilestream calls new_extdatafilestream
fillin_derived calls create_from_parameters
fillin_primary calls create_from_parameters
test_compare_negative_string_to_negative_heartbeat calls create_from_parameters
test_compare_positive_string_to_positive_heartbeat calls create_from_parameters
test_create_from_parameters_heartbeat_negative calls create_from_parameters
test_create_from_parameters_heartbeat_negative_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive_explicit calls create_from_parameters
test_create_from_parameters_heartbeat_positive_negative calls create_from_parameters
test_create_from_parameters_string_negative calls create_from_parameters
test_create_from_parameters_string_positive calls create_from_parameters
test_get_adjusted_time calls create_from_parameters
initialize_ calls fillin_derived, fillin_primary