string_to_esmf_time – MAPL
string_to_esmf_time Function
40 statements
Source File
public function string_to_esmf_time(input_string, unusable, rc) result(time)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_string
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value type(ESMF_Time)
Calls
Called by
Source Code
   function string_to_esmf_time(input_string,unusable,rc) result(time)
      character(len=*), intent(in) :: input_string
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      type(ESMF_Time) :: time
      integer :: status
      integer :: tpos
      integer year,month,day,hour,min,sec
      integer :: int_time, int_date
      character(len=:), allocatable :: date_string,time_string
      logical :: have_time
      _UNUSED_DUMMY(unusable)
      tpos = index(input_string,'T')
      if (tpos<=0) then
         have_time = .false.
      else
         have_time = .true.
      end if
      if (have_time) then
         time_string = input_string(tpos+1:)
         date_string = input_string(:tpos-1)
         int_time = string_to_integer_time(time_string,_RC)
      else
         date_string = trim(input_string)
         int_time = 0
      end if
      int_date = string_to_integer_date(date_string,_RC)
      year=int_date/10000
      month=mod(int_date/100,100)
      day=mod(int_date,100)
      hour=int_time/10000
      min=mod(int_time/100,100)
      sec=mod(int_time,100)
      call ESMF_TimeSet(time,yy=year,mm=month,dd=day,h=hour,m=min,s=sec,_RC)
      _RETURN(_SUCCESS)
   end function string_to_esmf_time
Call graph
string_to_esmf_time calls ESMF_TimeSet, mapl_return, mapl_verify, string_to_integer_date, string_to_integer_time
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
string_to_integer_date calls mapl_return
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_throw_exception calls initialize
get_time_range calls string_to_esmf_time
new_extdatafilestream calls string_to_esmf_time
new_extdatatimesample calls string_to_esmf_time
sort_rules_by_start calls string_to_esmf_time
extdatafilestream calls new_extdatafilestream
extdatatimesample calls new_extdatatimesample
initialize_ calls get_time_range, new_extdataoldtypescreator
new_extdataconfig_from_yaml calls sort_rules_by_start, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml