string_to_integer_time – MAPL
string_to_integer_time Function
50 statements
Source File
public function string_to_integer_time(time_string, unusable, rc) result(time)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: time_string
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function string_to_integer_time(time_string,unusable,rc) result(time)
      character(len=*), intent(in) :: time_string
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: time
      integer mpos(2), hpos(2), spos(2)
      integer strlen
      integer firstcolon, lastcolon
      integer lastspace
      integer hour,min,sec
      _UNUSED_DUMMY(unusable)
      strlen = LEN_TRIM (time_string)
      firstcolon = index(time_string, ':')
      if (firstcolon .LE. 0) then
        ! If no colons, check for hour.
        ! Logic below assumes a null character or something else is after the hour
        ! if we do not find a null character add one so that it correctly parses time
        !if (time_string(strlen:strlen) /= char(0)) then
           !time_string = trim(time_string)//char(0)
           !strlen=len_trim(time_string)
        !endif
        lastspace = index(TRIM(time_string), ' ', BACK=.TRUE.)
        if ((strlen-lastspace).eq.2 .or. (strlen-lastspace).eq.3) then
          hpos(1) = lastspace+1
          hpos(2) = strlen-1
          read (time_string(hpos(1):hpos(2)), * ) hour
          min  = 0
          sec  = 0
        else
          hour = 0
          min  = 0
          sec  = 0
        endif
      else
        hpos(1) = firstcolon - 2
        hpos(2) = firstcolon - 1
        lastcolon =  index(time_string, ':', BACK=.TRUE.)
        if ( lastcolon .EQ. firstcolon ) then
          mpos(1) = firstcolon + 1
          mpos(2) = firstcolon + 2
          read (time_string(hpos(1):hpos(2)), * ) hour
          read (time_string(mpos(1):mpos(2)), * ) min
          sec = 0
        else
          mpos(1) = firstcolon + 1
          mpos(2) = lastcolon - 1
          spos(1) = lastcolon + 1
          spos(2) = lastcolon + 2
          read (time_string(hpos(1):hpos(2)), * ) hour
          read (time_string(mpos(1):mpos(2)), * ) min
          read (time_string(spos(1):spos(2)), * ) sec
        endif
      endif
      time = hour*10000+min*100+sec
      _RETURN(_SUCCESS)
   end function string_to_integer_time
Call graph
string_to_integer_time calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
create_from_parameters calls string_to_integer_time
string_to_esmf_time calls string_to_integer_time
test_string_to_integer_time_delimiters calls string_to_integer_time
fillin_derived calls create_from_parameters
fillin_primary calls create_from_parameters
get_time_range calls string_to_esmf_time
new_extdatafilestream calls string_to_esmf_time
new_extdatatimesample calls string_to_esmf_time
sort_rules_by_start calls string_to_esmf_time
test_compare_negative_string_to_negative_heartbeat calls create_from_parameters
test_compare_positive_string_to_positive_heartbeat calls create_from_parameters
test_create_from_parameters_heartbeat_negative calls create_from_parameters
test_create_from_parameters_heartbeat_negative_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive calls create_from_parameters
test_create_from_parameters_heartbeat_positive_explicit calls create_from_parameters
test_create_from_parameters_heartbeat_positive_negative calls create_from_parameters
test_create_from_parameters_string_negative calls create_from_parameters
test_create_from_parameters_string_positive calls create_from_parameters
test_get_adjusted_time calls create_from_parameters
extdatafilestream calls new_extdatafilestream
extdatatimesample calls new_extdatatimesample
initialize_ calls fillin_derived, fillin_primary, get_time_range
new_extdataconfig_from_yaml calls sort_rules_by_start, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml