StringIntegerMap_deserialize – MAPL
StringIntegerMap_deserialize Subroutine
26 statements
Source File
public subroutine StringIntegerMap_deserialize(buffer, map, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(StringIntegerMap), intent(inout) :: map
integer, intent(out), optional :: rc
Calls
Contents
Source Code
StringIntegerMap_deserialize
Source Code
    subroutine StringIntegerMap_deserialize(buffer, map, rc)
       integer, intent(in) :: buffer(:)
       type (StringIntegerMap), intent(inout) :: map
       integer, optional, intent(out) :: rc
       character(len=:),allocatable :: key
       integer :: value,length,n,n0,n1,n2
       n = 1
       call deserialize_intrinsic(buffer(n:),length)
       n0 = serialize_buffer_length(length)
       n = n + n0
       length = length - n0
       map = StringIntegerMap()
       do while (length > 0)
          call deserialize_intrinsic(buffer(n:),key)
          n1 = serialize_buffer_length(key)
          n = n + n1
          call deserialize_intrinsic(buffer(n:),value)
          n2 = serialize_buffer_length(value)
          n = n + n2
          length = length - n1 - n2
          call map%insert(key,value)
          deallocate(key)
       enddo
       _RETURN(_SUCCESS)
    end subroutine StringIntegerMap_deserialize
Call graph
stringintegermap_deserialize calls deserialize_intrinsic, serialize_buffer_length, stringintegermap, mapl_return
deserialize_intrinsic calls deserialize_string, deserialize_int32_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_int64_1d, deserialize_int32_0d, deserialize_int64_0d, deserialize_real64_0d, deserialize_real64_1d
serialize_buffer_length calls serialize_buffer_length_real32_1d, serialize_buffer_length_logical_1d, serialize_buffer_length_int64_1d, serialize_buffer_length_int32_0d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_int64_0d, serialize_buffer_length_string, serialize_buffer_length_int32_1d, serialize_buffer_length_logical_0d
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_int32_0d calls mapl_return
deserialize_string calls mapl_return, mapl_assert
deserialize_int32_1d calls mapl_return, mapl_assert
deserialize_real32_0d calls mapl_return, mapl_assert
deserialize_real32_1d calls mapl_return, mapl_assert
deserialize_logical_0d calls mapl_return, mapl_assert
deserialize_logical_1d calls mapl_return, mapl_assert
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_int64_0d calls mapl_return
deserialize_int64_1d calls mapl_return, mapl_assert
deserialize_int32_0d calls mapl_return, mapl_assert
deserialize_int64_0d calls mapl_return, mapl_assert
deserialize_real64_0d calls mapl_return, mapl_assert
deserialize_real64_1d calls mapl_return, mapl_assert
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_logical_0d calls mapl_return, word_size