string_to_integer_date – MAPL
string_to_integer_date Function
30 statements
Source File
public function string_to_integer_date(time_string, unusable, rc) result(date)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: time_string
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   function string_to_integer_date(time_string,unusable,rc) result(date)
      character(len=*), intent(in) :: time_string
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: date
      integer ypos(2), mpos(2), dpos(2)
      integer strlen
      integer firstdash, lastdash
      integer year,month,day
      _UNUSED_DUMMY(unusable)
      strlen = LEN_TRIM (time_string)
      firstdash = index(time_string, '-')
      lastdash  = index(time_string, '-', BACK=.TRUE.)
      if (firstdash .LE. 0 .OR. lastdash .LE. 0) then
        _RETURN(_FAILURE)
      endif
      ypos(2) = firstdash - 1
      mpos(1) = firstdash + 1
      ypos(1) = ypos(2) - 3
      mpos(2) = lastdash - 1
      dpos(1) = lastdash + 1
      dpos(2) = dpos(1) + 1
      read ( time_string(ypos(1):ypos(2)), * ) year
      read ( time_string(mpos(1):mpos(2)), * ) month
      read ( time_string(dpos(1):dpos(2)), * ) day
      date = year*10000+month*100+day
      _RETURN(_SUCCESS)
   end function string_to_integer_date
Call graph
string_to_integer_date calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
string_to_esmf_time calls string_to_integer_date
test_string_to_integer_date_delimiters calls string_to_integer_date
get_time_range calls string_to_esmf_time
new_extdatafilestream calls string_to_esmf_time
new_extdatatimesample calls string_to_esmf_time
sort_rules_by_start calls string_to_esmf_time
extdatafilestream calls new_extdatafilestream
extdatatimesample calls new_extdatatimesample
initialize_ calls get_time_range
new_extdataconfig_from_yaml calls sort_rules_by_start, new_extdataconfig_from_yaml
new_extdataoldtypescreator calls new_extdataconfig_from_yaml