StringVariableMap_get_length – MAPL
StringVariableMap_get_length Function
6 statements
Source File
public function StringVariableMap_get_length(this) result(length)
Arguments
Type Intent Optional Attributes Name
type(StringVariableMap), intent(in) :: this
Return Value integer
Calls
Called by
Contents
Source Code
StringVariableMap_get_length
Source Code
    integer function StringVariableMap_get_length(this) result(length)
      type (StringVariableMap), intent(in) :: this
      integer, allocatable :: buffer(:)
      call StringVariableMap_serialize(this, buffer)
      length = size(buffer)
    end function StringVariableMap_get_length
Call graph
stringvariablemap_get_length calls stringvariablemap_serialize
stringvariablemap_serialize calls serialize_intrinsic, mapl_verify, serialize_buffer_length, mapl_return
serialize_intrinsic calls serialize_logical_0d, serialize_int32_1d, serialize_int64_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_logical_1d, serialize_int64_0d, serialize_string, serialize_int32_0d
mapl_verify calls mapl_throw_exception
serialize_buffer_length calls serialize_buffer_length_logical_1d, serialize_buffer_length_int64_1d, serialize_buffer_length_int32_0d, serialize_buffer_length_real64_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_int64_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_string, serialize_buffer_length_logical_0d
mapl_return calls mapl_throw_exception, get_error_message
serialize_logical_0d calls mapl_return
mapl_throw_exception calls initialize
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_int64_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_int64_0d calls mapl_return
serialize_string calls mapl_return
serialize_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_logical_0d calls mapl_return, word_size
get_length calls stringvariablemap_get_length