StringVector_deserialize – MAPL
StringVector_deserialize Subroutine
23 statements
Source File
public subroutine StringVector_deserialize(buffer, strVec, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(StringVector), intent(inout) :: strVec
integer, intent(out), optional :: rc
Calls
Contents
Source Code
StringVector_deserialize
Source Code
    subroutine StringVector_deserialize(buffer, strVec, rc)
       integer, intent(in) :: buffer(:)
       type (StringVector), intent(inout) :: strVec
       integer, optional, intent(out) :: rc
       character(len=:),allocatable :: str
       integer :: length,n,n1,n0
       n = 1
       call deserialize_intrinsic(buffer(n:),length)
       n0 =  serialize_buffer_length(length)
       n = n + n0
       length = length - n0
       strVec = StringVector()
       do while (length > 0)
          call deserialize_intrinsic(buffer(n:),str)
          call strVec%push_back(str)
          n1 = serialize_buffer_length(str)
          n = n + n1
          length = length - n1
          deallocate(str)
       enddo
       _RETURN(_SUCCESS)
   end subroutine StringVector_deserialize
Call graph
stringvector_deserialize calls deserialize_intrinsic, stringvector, mapl_return, serialize_buffer_length
deserialize_intrinsic calls deserialize_int64_0d, deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_1d, deserialize_real64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_string, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d
mapl_return calls mapl_throw_exception, get_error_message
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_string, serialize_buffer_length_real32_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_int64_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real64_0d
mapl_throw_exception calls initialize
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
deserialize_int64_0d calls mapl_return, mapl_assert
deserialize_int32_0d calls mapl_return, mapl_assert
deserialize_int32_1d calls mapl_return, mapl_assert
deserialize_int64_1d calls mapl_return, mapl_assert
deserialize_real64_1d calls mapl_return, mapl_assert
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
deserialize_logical_0d calls mapl_return, mapl_assert
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_logical_1d calls mapl_return, word_size
deserialize_logical_1d calls mapl_return, mapl_assert
deserialize_string calls mapl_return, mapl_assert
deserialize_real32_0d calls mapl_return, mapl_assert
deserialize_real32_1d calls mapl_return, mapl_assert
deserialize_real64_0d calls mapl_return, mapl_assert
serialize_buffer_length_real64_0d calls mapl_return, word_size