StringAttributeMap_serialize – MAPL
StringAttributeMap_serialize Subroutine
26 statements
Source File
public subroutine StringAttributeMap_serialize(map, buffer, rc)
Arguments
Type Intent Optional Attributes Name
type(StringAttributeMap), intent(in) :: map
integer, intent(inout), allocatable :: buffer(:)
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
StringAttributeMap_serialize
Source Code
    subroutine StringAttributeMap_serialize(map,buffer, rc)
       type (StringAttributeMap) ,intent(in):: map
       integer, allocatable,intent(inout) :: buffer(:)
       integer, optional, intent(out) :: rc
       type (StringAttributeMapIterator) :: iter
       character(len=:),pointer :: key
       type(Attribute),pointer :: attr_ptr
       integer :: length
       integer, allocatable :: tmp_buffer(:)
       if (allocated(buffer)) deallocate(buffer)
       allocate(buffer(0))
       iter = map%begin()
       do while (iter /= map%end())
          key => iter%key()
          buffer=[buffer,serialize_intrinsic(key)]
          attr_ptr => iter%value()
          call attr_ptr%serialize(tmp_buffer)
          buffer = [buffer, tmp_buffer]
          deallocate(tmp_buffer)
          call iter%next()
       enddo
       length = serialize_buffer_length(length)+size(buffer)
       buffer = [serialize_intrinsic(length),buffer]
       _RETURN(_SUCCESS)
    end subroutine StringAttributeMap_serialize
Call graph
stringattributemap_serialize calls serialize_intrinsic, mapl_return, serialize_buffer_length
serialize_intrinsic calls serialize_logical_1d, serialize_string, serialize_int64_1d, serialize_int32_0d, serialize_int64_0d, serialize_real32_1d, serialize_real64_0d, serialize_logical_0d, serialize_int32_1d, serialize_real32_0d, serialize_real64_1d
mapl_return calls mapl_throw_exception, get_error_message
serialize_buffer_length calls serialize_buffer_length_real32_0d, serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_real64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_string, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d
serialize_buffer_length_real32_0d calls mapl_return, word_size
mapl_throw_exception calls initialize
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_string calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_int32_0d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_int64_0d calls mapl_return
serialize_logical_0d calls mapl_return
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_int32_1d calls mapl_return
serialize_real32_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
word_size calls mapl_return, mapl_assert
serialize calls stringattributemap_serialize