StringUnlimitedEntityMap_deserialize – MAPL
StringUnlimitedEntityMap_deserialize Subroutine
27 statements
Source File
public subroutine StringUnlimitedEntityMap_deserialize(buffer, map, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: buffer(:)
type(StringUnlimitedEntityMap), intent(inout) :: map
integer, intent(out), optional :: rc
Calls
Contents
Source Code
StringUnlimitedEntityMap_deserialize
Source Code
    subroutine StringUnlimitedEntityMap_deserialize(buffer, map, rc)
       integer, intent(in) :: buffer(:)
       type (StringUnlimitedEntityMap), intent(inout) :: map
       integer, optional, intent(out) :: rc
       character(len=:),allocatable :: key
       integer :: length,n,n0,n1,n2
       type (UnlimitedEntity) :: attr
       n = 1
       call deserialize_intrinsic(buffer(n:),length)
       n0 = serialize_buffer_length(length)
       n = n + n0
       length = length - n0
       map = StringUnlimitedEntityMap()
       do while (length > 0)
          call deserialize_intrinsic(buffer(n:),key)
          n1 = serialize_buffer_length(key)
          n = n + n1
          call deserialize_intrinsic(buffer(n:),n2)
          call UnlimitedEntity_deserialize(buffer(n:), attr)
          n = n + n2
          length = length - n1 - n2
          call map%insert(key,attr)
          deallocate(key)
       enddo
       _RETURN(_SUCCESS)
    end subroutine StringUnlimitedEntityMap_deserialize
Call graph
stringunlimitedentitymap_deserialize calls insert, deserialize_intrinsic, serialize_buffer_length, mapl_return, unlimitedentity_deserialize
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
mapl_return calls get_error_message, mapl_throw_exception
unlimitedentity_deserialize calls mapl_return, unlimitedentity, mapl_verify