strTemplate_ – MAPL
strTemplate_ Subroutine
24 statements
Source File
public subroutine strTemplate_(str, tmpl, class, xid, nymd, nhms, stat)
strTemplate_ - expanding a format template to a string
History
03Jun99 - Jing Guo guo@dao.gsfc.nasa.gov - initial prototype/prolog/code
08Jan01 - da Silva: moved uppercase() to outside select() to avoid coredump on Linux/PGI.
! uc_class=uppercase(tmpl_class)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out) :: str
character(len=*), intent(in) :: tmpl
character(len=*), intent(in), optional :: class
character(len=*), intent(in), optional :: xid
integer, intent(in), optional :: nymd
integer, intent(in), optional :: nhms
integer, intent(out), optional :: stat
Calls
Called by
Source Code
    subroutine strTemplate_(str,tmpl,class,xid,nymd,nhms,stat)
      implicit none
      character(len=*),intent(out) :: str ! the output
      character(len=*),intent(in ) :: tmpl ! a "format"
      character(len=*),intent(in ),optional :: class
      ! choose a UNIX or a GrADS(defulat) type format
      character(len=*),intent(in ),optional :: xid
      ! a string substituting a "%s".  Trailing
      ! spaces will be ignored
      integer,intent(in ),optional :: nymd
      ! yyyymmdd, substituting "%y4", "%y2", "%m1",
      ! "%m2", "%mc", "%Mc', and "%MC"
      integer,intent(in ),optional :: nhms
      ! hhmmss, substituting "%h1", "%h2", "%h3",
      ! and "%n2"
      integer,intent(out),optional :: stat
      ! error code
  character(len=*),parameter :: myname_=myname//'::strTemplate_'
  character(len=16) :: tmpl_class,uc_class
  tmpl_class="GX"
  if(present(class)) tmpl_class=class
!!!  uc_class=uppercase(tmpl_class)
  uc_class=trim(tmpl_class) ! removed this dependency on mpeu
  select case(uc_class)
  case("GX","GRADS")
    call GX_(str,tmpl,xid,nymd,nhms,stat)
  !case("UX","UNIX") ! yet to be implemented
  !  call UX_(str,tmpl,xid,nymd,nhms,stat)
  case default
    write(stderr,'(4a)') myname_,': unknown class, "',trim(tmpl_class),'"'
    if(.not.present(stat)) call die(myname_)
    stat=-1
    return
  end select
end subroutine strTemplate_
Call graph
strtemplate_ calls die, gx_
gx_ calls die, perr
esmf_cfiostrtemplate calls strtemplate_
esmf_cfiosdffilecreate calls strtemplate_
esmf_cfiosdffileopen calls strtemplate_
esmf_cfiosdfvarread1d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarread2d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarread3d_ calls strtemplate_, esmf_cfiosdffileopen
esmf_cfiosdfvarwrite1d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite2d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarwrite3d_ calls strtemplate_, esmf_cfiosdffilecreate
esmf_cfiosdfvarread calls esmf_cfiosdfvarread1d_, esmf_cfiosdfvarread2d_, esmf_cfiosdfvarread3d_
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfiofilecreate calls esmf_cfiosdffilecreate
esmf_cfiofileopen calls esmf_cfiosdffileopen