stub – MAPL
stub Subroutine
15 statements
Source File
private subroutine stub(this, clock, phase, unusable, rc)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout) :: this
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in) :: phase
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine stub(this, clock, phase, unusable, rc)
      class(MaplGenericComponent), intent(inout) :: this
      type(ESMF_Clock), intent(inout) :: clock
      character(*), intent(in) :: phase
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      class(AbstractComponent), pointer :: user_component
      _UNUSED_DUMMY(unusable)
      user_component => this%get_component()
      call user_component%run(this%import_state, this%export_state, clock, phase, _RC)
      _RETURN(_SUCCESS)
   end subroutine stub
Call graph
stub calls get_component, mapl_return, mapl_verify, run
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize