stub_child – MAPL
stub_child Subroutine
16 statements
Source File
private subroutine stub_child(this, name, clock, phase, unusable, rc)
Type Bound
MaplGenericComponent
Arguments
Type Intent Optional Attributes Name
class(MaplGenericComponent), intent(inout) :: this
character(len=*), intent(in) :: name
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in) :: phase
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine stub_child(this, name, clock, phase, unusable, rc)
      class(MaplGenericComponent), intent(inout) :: this
      character(*), intent(in) :: name
      type(ESMF_Clock), intent(inout) :: clock
      character(*), intent(in) :: phase
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      class(AbstractFrameworkComponent), pointer :: child
      integer :: status
      _UNUSED_DUMMY(unusable)
      child => this%get_child(name)
      call child%run(clock, phase, _RC)
      _RETURN(_SUCCESS)
   end subroutine stub_child
Call graph
stub_child calls get_child, mapl_return, mapl_verify, run
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_child_by_index calls get_component, get_child
get_child_by_name calls get_component, get_child
get_error_message calls at, insert
mapl_throw_exception calls initialize