substitute_name – MAPL
substitute_name Function
15 statements
Source File
private function substitute_name(filter_expression, field_name, rc) result(processed_expression)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filter_expression
character(len=*), intent(in) :: field_name
integer, intent(out), optional :: rc
Return Value character(len=:), allocatable
Calls
Called by
Call graph
substitute_name calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
statefilter_r4_2d calls substitute_name
statefilter_r4_3d calls substitute_name
statefilteritem calls statefilter_r4_2d, statefilter_r4_3d
test_filter_arithmetic_2d calls statefilteritem
test_filter_arithmetic_3d calls statefilteritem
test_filter_default_2d calls statefilteritem
test_filter_identity_2d calls statefilteritem
test_filter_identity_3d calls statefilteritem
test_filter_region_mask_2d calls statefilteritem