subset_array – MAPL
subset_array Function
7 statements
Source File
public function subset_array(input_array, bounds) result(output_array)
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(in), pointer :: input_array(:,:)
type(Interval), intent(in) :: bounds
Return Value real(kind=ESMF_KIND_R8), pointer, (:,:)
Called by
Contents
Call graph
make_subgrids_from_bounds calls subset_array
make_subgrids calls make_subgrids_from_bounds, make_subgrids_from_num_grids
create_subobjects calls make_subgrids
make_subfields_from_num_grids calls make_subgrids
make_subgrids_from_num_grids calls make_subgrids
make_subfields calls make_subfields_from_num_grids
activate_threading calls create_subobjects