supports – MAPL
supports Function
17 statements
Source File
private function supports(spec, unusable, rc)
Type Bound
AbstractRegridder
Arguments
Type Intent Optional Attributes Name
type(RegridderSpec), intent(in) :: spec
class(KeywordEnforcer), intent(in), optional :: unusable
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function supports(spec, unusable, rc)
      type(RegridderSpec), intent(in) :: spec
      class(KeywordEnforcer), optional, intent(in) :: unusable
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(spec)
      _UNUSED_DUMMY(unusable)
      supports = .false.
      _FAIL('unimplemented')
      _RETURN(_SUCCESS)
   end function supports
Call graph
supports calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
find_prototype calls supports
make_regridder_ calls find_prototype
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
request_data_from_file calls make_regridder