swapCS – MAPL
swapCS Subroutine
29 statements
Source File
private subroutine swapCS(II, JJ, nX, nY, nVal)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: II(nVal)
integer, intent(inout) :: JJ(nVal)
integer, intent(in) :: nX
integer, intent(in) :: nY
integer, intent(in) :: nVal
Called by
Source Code
      Subroutine swapCS(II,JJ,nX,nY,nVal)
         Integer, Intent(In)     :: nVal
         Integer, Intent(InOut)  :: II(nVal)
         Integer, Intent(InOut)  :: JJ(nVal)
         Integer, Intent(In)     :: nX
         Integer, Intent(In)     :: nY
         Integer                 :: iFace
         Integer                 :: xFace
         Integer                 :: minJJ, maxJJ, minJJOut
         Integer                 :: JJ0(nVal)
         Integer                 :: I
         Integer, Parameter      :: faceMap(6) = (/4,5,1,2,6,3/)
         _UNUSED_DUMMY(nY)
         ! Copy input
         JJ0 = JJ
         Do iFace = 1,6
            ! Re-order faces from Tempest to GMAO convention
            xFace = faceMap(iFace)
            minJJ    = nX*(iFace-1) + 1
            minJJOut = nX*(xFace-1) + 1
            maxJJ    = nX*iFace
            Do I=1,nVal
               If ((JJ0(I).ge.minJJ).and.(JJ0(I).le.maxJJ)) Then
                  JJ(I) = minJJOut + JJ0(I) - minJJ
               End If
            End Do
         End Do
      End Subroutine swapCS
Call graph
readtilefilenc_file calls swapcs
read_tempest calls readtilefilenc_file
readtilefilenc calls readtilefilenc_file
initialize_subclass calls read_tempest