swap_year – MAPL
swap_year Subroutine
20 statements
Source File
private subroutine swap_year(time, year, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(inout) :: time
integer, intent(in) :: year
integer, intent(out), optional :: rc
Calls
Called by
Contents
Call graph
swap_year calls ESMF_CalendarIsLeapYear, ESMF_TimeGet, ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
get_file_bracket calls swap_year, get_file
get_file calls swap_year