swap_node_fields – MAPL
swap_node_fields Subroutine
20 statements
Source File
private subroutine swap_node_fields(this, rc)
Type Bound
ExtDataBracket
Arguments
Type Intent Optional Attributes Name
class(ExtDataBracket), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine swap_node_fields(this,rc)
      class(ExtDataBracket), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      real, pointer :: left_ptr(:), right_ptr(:)
      logical :: left_created, right_created
      left_created  = ESMF_FieldIsCreated(this%left_node%field,_RC)
      right_created = ESMF_FieldIsCreated(this%right_node%field,_RC)
      if (left_created .and. right_created) then
         call assign_fptr(this%left_node%field,left_ptr,_RC)
         call assign_fptr(this%right_node%field,right_ptr,_RC)
         left_ptr = right_ptr
      end if
      _RETURN(_SUCCESS)
   end subroutine swap_node_fields
Call graph
swap_node_fields calls ESMF_FieldIsCreated, assign_fptr, mapl_return, mapl_verify
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
assign_fptr_r4_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r4_rank2 calls mapl_return, mapl_verify, fieldgetcptr
assign_fptr_r8_rank1 calls mapl_return, mapl_verify, fieldgetcptr, fieldgetlocalsize
assign_fptr_r8_rank2 calls mapl_return, mapl_verify, fieldgetcptr
get_error_message calls at, insert
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
get_file_bracket calls swap_node_fields