swap_undef_value – MAPL
swap_undef_value Subroutine
56 statements
Source File
private subroutine swap_undef_value(this, fname, rc)
Type Bound
MAPL_GriddedIO
Arguments
Type Intent Optional Attributes Name
class(MAPL_GriddedIO), intent(inout) :: this
character(len=*), intent(in) :: fname
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
swap_undef_value
Source Code
  subroutine swap_undef_value(this,fname,rc)
     class (MAPL_GriddedIO), intent(inout) :: this
     character(len=*), intent(in) :: fname
     integer, optional, intent(out) :: rc
     integer :: status
     type(ESMF_Field) :: field
     integer :: fieldRank
     real, pointer :: ptr3d(:,:,:)
     real, pointer :: ptr2d(:,:)
     type(ESMF_Grid) :: gridIn
     logical :: hasDE_in
     real(REAL32) :: fill_value
     if ( .not. this%current_file_metadata%var_has_missing_value(fname) ) then
        _RETURN(_SUCCESS)
     endif
     fill_value = this%current_file_metadata%var_get_missing_value(fname,_RC)
     call ESMF_FieldBundleGet(this%input_bundle,fname,field=field,_RC)
     call ESMF_FieldBundleGet(this%input_bundle,grid=gridIn,_RC)
     call ESMF_FieldGet(field,rank=fieldRank,_RC)
     hasDE_in = MAPL_GridHasDE(gridIn,_RC)
     if (fieldRank==2) then
        if (hasDE_in) then
           call MAPL_FieldGetPointer(field,ptr2d,_RC)
        else
           allocate(ptr2d(0,0))
        end if
        if (isnan(fill_value)) then
           where(isnan(ptr2d)) ptr2d=MAPL_UNDEF
        else
           where(ptr2d==fill_value) ptr2d=MAPL_UNDEF
        endif
     else if (fieldRank==3) then
        if (hasDE_in) then
           call ESMF_FieldGet(field,farrayPtr=ptr3d,_RC)
        else
           allocate(ptr3d(0,0,0))
        end if
        if (isnan(fill_value)) then
           where(isnan(ptr3d)) ptr3d=MAPL_UNDEF
        else
           where(ptr3d==fill_value) ptr3d=MAPL_UNDEF
        endif
     else
        _FAIL('rank not supported')
     end if
     _RETURN(_SUCCESS)
  end subroutine swap_undef_value
Call graph
swap_undef_value calls esmf_fieldbundleget, esmf_fieldget, esmfl_fieldgetpointertodata, mapl_assert, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetpointertodata calls esmfl_fieldgetptrtodatar4_1, esmfl_fieldgetptrtodatar4_2, esmfl_fieldgetptrtodatar4_3, esmfl_fieldgetptrtodatar4_4, esmfl_fieldgetptrtodatar8_1, esmfl_fieldgetptrtodatar8_2, esmfl_fieldgetptrtodatar8_3, esmfl_fieldgetptrtodatar8_4
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
esmfl_fieldgetptrtodatar4_1 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar4_4 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_1 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_2 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_3 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
esmfl_fieldgetptrtodatar8_4 calls esmf_fieldget, mapl_gridhasde, mapl_return, mapl_verify
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
process_data_from_file calls swap_undef_value