swapBracketInformation – MAPL
swapBracketInformation Subroutine
85 statements
Source File
private subroutine swapBracketInformation(item, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
swapBracketInformation
Source Code
     subroutine swapBracketInformation(item,rc)
        type(PrimaryExport), intent(inout) :: item
        integer, optional, intent(out) :: rc
        integer :: status
        integer :: j, fieldRank, fieldCount
        type(ESMF_Field) :: field1, field2
        real, pointer :: var2d_prev(:,:)
        real, pointer :: var3d_prev(:,:,:)
        real, pointer :: var2d_next(:,:)
        real, pointer :: var3d_next(:,:,:)
        character(len=ESMF_MAXSTR), ALLOCATABLE  :: NAMES (:)
        item%interp_time1 = item%interp_time2
        if (item%vartype == MAPL_FieldItem) then
           call ESMF_FieldGet(item%modelGridFields%v1_finterp1, dimCount=fieldRank,_RC)
           if (fieldRank == 2) then
              call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var2d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var2d_next, _RC)
              var2d_prev=var2d_next
           else if (fieldRank == 3) then
              call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var3d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var3d_next, _RC)
              var3d_prev=var3d_next
           endif
        else if (item%vartype == MAPL_BundleItem) then
           call ESMF_FieldBundleGet(item%binterp2, fieldCount = fieldCount, _RC)
           allocate(names(fieldCount),__STAT__)
           call ESMF_FieldBundleGet(item%binterp2, fieldNameList = Names, _RC)
           do j = 1,fieldCount
              call ESMF_FieldBundleGet(item%binterp1, names(j), field=field1, _RC)
              call ESMF_FieldBundleGet(item%binterp2, names(j), field=field2, _RC)
              call ESMF_FieldGet(field1, dimCount=fieldRank, _RC)
              if (fieldRank == 2) then
                 call ESMF_FieldGet(field1, localDE=0, farrayPtr=var2d_prev, _RC)
                 call ESMF_FieldGet(field2, localDE=0, farrayPtr=var2d_next, _RC)
                 var2d_prev=var2d_next
              else if (fieldRank == 3) then
                 call ESMF_FieldGet(field1, localDE=0, farrayPtr=var3d_prev, _RC)
                 call ESMF_FieldGet(field2, localDE=0, farrayPtr=var3d_next, _RC)
                 var3d_prev=var3d_next
              endif
           enddo
           deallocate(names)
        else if (item%vartype == MAPL_ExtDataVectorItem) then
           call ESMF_FieldGet(item%modelGridFields%v1_finterp1, dimCount=fieldRank, _RC)
           if (fieldRank == 2) then
              call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var2d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var2d_next, _RC)
              var2d_prev=var2d_next
              call ESMF_FieldGet(item%modelGridFields%v2_finterp1, localDE=0, farrayPtr=var2d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v2_finterp2, localDE=0, farrayPtr=var2d_next, _RC)
              var2d_prev=var2d_next
           else if (fieldRank == 3) then
              call ESMF_FieldGet(item%modelGridFields%v1_finterp1, localDE=0, farrayPtr=var3d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v1_finterp2, localDE=0, farrayPtr=var3d_next, _RC)
              var3d_prev=var3d_next
              call ESMF_FieldGet(item%modelGridFields%v2_finterp1, localDE=0, farrayPtr=var3d_prev, _RC)
              call ESMF_FieldGet(item%modelGridFields%v2_finterp2, localDE=0, farrayPtr=var3d_next, _RC)
              var3d_prev=var3d_next
           endif
        end if
     end subroutine swapBracketInformation
Call graph
swapbracketinformation calls esmf_fieldget, mapl_verify, esmf_fieldbundleget
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
run_ calls swapbracketinformation