SwathGridFactory_from_parameters – MAPL
SwathGridFactory_from_parameters Function
30 statements
Source File
private function SwathGridFactory_from_parameters(unusable, grid_name, im_world, jm_world, lm, nx, ny, ims, jms, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(in), optional :: ims(:)
integer, intent(in), optional :: jms(:)
integer, intent(out), optional :: rc
Return Value type(SwathGridFactory)
Calls
Called by
Source Code
   function SwathGridFactory_from_parameters(unusable, grid_name, &
        & im_world, jm_world, lm, nx, ny, ims, jms, rc) result(factory)
      type (SwathGridFactory) :: factory
      class (KeywordEnforcer), optional, intent(in) :: unusable
      character(len=*), optional, intent(in) :: grid_name
      ! grid details:
      integer, optional, intent(in) :: im_world
      integer, optional, intent(in) :: jm_world
      integer, optional, intent(in) :: lm
      ! decomposition:
      integer, optional, intent(in) :: nx
      integer, optional, intent(in) :: ny
      integer, optional, intent(in) :: ims(:)
      integer, optional, intent(in) :: jms(:)
      integer, optional, intent(out) :: rc
      integer :: status
      _UNUSED_DUMMY(unusable)
      call set_with_default(factory%grid_name, grid_name, MAPL_GRID_NAME_DEFAULT)
      call set_with_default(factory%nx, nx, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%ny, ny, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%im_world, im_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%jm_world, jm_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%lm, lm, MAPL_UNDEFINED_INTEGER)
      ! default is unallocated
      if (present(ims)) factory%ims = ims
      if (present(jms)) factory%jms = jms
      call factory%check_and_fill_consistency(_RC)
      _RETURN(_SUCCESS)
   end function SwathGridFactory_from_parameters
Call graph
swathgridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_bounds, set_with_default_character, set_with_default_integer, set_with_default_real64, set_with_default_real
check_and_fill_consistency calls mapl_return, mapl_verify, check_decomposition, generate_newnxy
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
check_decomposition calls mapl_return
generate_newnxy calls mapl_return, mapl_assert, mapl_decomposedim
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_decomposedim calls mapl_decomposedim
swathgridfactory calls swathgridfactory_from_parameters