terminate_servers – MAPL
terminate_servers Subroutine
22 statements
Source File
private subroutine terminate_servers(this, client_comm, rc)
Type Bound
DirectoryService
Arguments
Type Intent Optional Attributes Name
class(DirectoryService), intent(inout) :: this
integer, intent(in) :: client_comm
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine terminate_servers(this, client_comm, rc)
      class (DirectoryService), intent(inout) :: this
      integer ,intent(in) :: client_comm
      integer, optional, intent(out) :: rc
      type (Directory) :: dir
      integer :: ierror, rank_in_client,i
      call MPI_Comm_rank(client_comm, rank_in_client, ierror)
      _VERIFY(ierror)
      call MPI_BARRIER(client_comm,ierror)
      _VERIFY(ierror)
      if (rank_in_client ==0) then
         write(6,*)"client0 terminates servers"; flush(6)
         dir = this%get_directory(this%win_server_directory)
         do i = 1, dir%num_entries
            call MPI_Send(TERMINATE, 1, MPI_INTEGER, dir%entries(i)%partner_root_rank, DISCOVERY_TAG, &
                & this%comm, ierror)
            _VERIFY(ierror)
         enddo
      endif
      _RETURN(_SUCCESS)
   end subroutine terminate_servers
Call graph
terminate_servers calls mpi_barrier, mpi_comm_rank, mpi_send, get_directory, mapl_return, mapl_verify
get_directory calls mapl_verify, mpi_get, mpi_win_lock, mpi_win_unlock, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize