terminate – MAPL
terminate Subroutine
20 statements
Source File
private subroutine terminate(this, unusable, rc)
Type Bound
ClientManager
Arguments
Type Intent Optional Attributes Name
class(ClientManager), intent(inout) :: this
class(KeywordEnforcer), intent(out), optional :: unusable
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine terminate(this, unusable, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc
      integer :: status
      class (ClientThread), pointer :: clientPtr
      integer :: i
      do i = 1, this%size()
         clientPtr =>this%clients%at(i)
         call clientPtr%wait_all(_RC)
         call clientPtr%terminate()
      enddo
      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine terminate
Call graph
terminate calls at, mapl_return, mapl_verify, terminate, wait_all, get_connection, send
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
wait_all calls mapl_return, mapl_verify, clear_requesthandle
clear_requesthandle calls mapl_return, mapl_verify, erase, m_begin
get_connection calls mapl_return, mapl_assert
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
m_begin calls s_begin
finalize_io_clients_servers calls terminate
main calls terminate
model_finalize calls finalize_io_clients_servers
run calls finalize_io_clients_servers, run_ensemble
run_ensemble calls finalize_io_clients_servers
extdata_driver calls run
capdriver_main calls run