terminate_writers – MAPL
terminate_writers Subroutine
12 statements
Source File
private subroutine terminate_writers(this)
Type Bound
MultiLayerServer
Arguments
Type Intent Optional Attributes Name
class(MultiLayerServer), intent(inout) :: this
Calls
Called by
Source Code
   subroutine terminate_writers(this)
      class (MultiLayerServer), intent(inout) :: this
      integer :: terminate = -1
      integer :: ierr, status, rc
      integer :: MPI_STAT(MPI_STATUS_SIZE)
      ! The root rank sends termination signal to the root of the spawned children which would
      ! send terminate back for synchronization
      ! if no syncrohization, the writer may be still writing while the main testing node is comparing
      if( this%rank == 0 .and. this%nwriters > 1 ) then
        call MPI_send(terminate, 1, MPI_INTEGER, 0, pFIO_s_tag, this%Inter_Comm, ierr)
        _VERIFY(ierr)
        call MPI_recv(terminate, 1, MPI_INTEGER, 0, pFIO_s_tag, this%Inter_Comm, MPI_STAT, ierr)
        _VERIFY(ierr)
      endif
   end subroutine terminate_writers
Call graph
terminate_writers calls mpi_recv, mpi_send, mapl_verify
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
start calls terminate_writers