terminate – MAPL
terminate Subroutine
11 statements
Source File
private subroutine terminate(this, rc)
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine terminate(this, rc)
      class (ClientThread), intent(inout) :: this
      integer, optional, intent(out) :: rc
      class(AbstractSocket),pointer :: connection
      integer :: status
      connection=>this%get_connection()
      call connection%send(TerminateMessage(),_RC)
      _RETURN(_SUCCESS)
   end subroutine terminate
Call graph
terminate calls get_connection, mapl_return, mapl_verify, send, terminate
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
finalize calls terminate
finalize_io_clients_servers calls terminate
main calls finalize, terminate
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run calls finalize_io_clients_servers, run_ensemble
extdata_driver calls run