terminate_backend_server – MAPL
terminate_backend_server Subroutine
22 statements
Source File
private subroutine terminate_backend_server(this, rc)
Type Bound
MultiGroupServer
Arguments
Type Intent Optional Attributes Name
class(MultiGroupServer), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Contents
Source Code
terminate_backend_server
Source Code
   subroutine terminate_backend_server(this, rc)
      class (MultiGroupServer), intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: terminate
      integer :: ierr, i
      integer :: MPI_STAT(MPI_STATUS_SIZE)
      terminate = -1
      ! starting from 2, no backend root
      do i = 2, this%nwriter
        if (allocated(this%buffers(i)%buffer)) then
           call MPI_Wait(this%buffers(i)%request, MPI_STAT, ierr)
           _VERIFY(ierr)
        endif
      enddo
      ! The front root rank sends termination signal to the back root
      ! The back root send terminate back for synchronization
      if (this%I_am_front_root) then
         call MPI_send(terminate, 1, MPI_INTEGER, this%back_ranks(1), &
              this%back_ranks(1),  this%server_comm, ierr)
         _VERIFY(ierr)
         call MPI_recv(terminate, 1, MPI_INTEGER, this%back_ranks(1), &
              this%front_ranks(1), this%server_comm, MPI_STAT, ierr)
         _VERIFY(ierr)
      endif
      _RETURN(_SUCCESS)
   end subroutine terminate_backend_server
Call graph
terminate_backend_server calls back_ranks, buffers, front_ranks, mpi_recv, mpi_send, mpi_wait, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize