test_add_prototype – MAPL
test_add_prototype Subroutine
4 statements
Source File
public subroutine test_add_prototype()
Arguments
None
Calls
Source Code
   subroutine test_add_prototype()
      type (GridManager) :: grid_manager
      call grid_manager%add_prototype('mock', MockGridFactory('foo'))
   end subroutine test_add_prototype
Call graph
test_add_prototype calls add_prototype
add_prototype calls insert
m_insert_pair calls s_insert