test_serialize_buffer_length_logical_0d – MAPL
test_serialize_buffer_length_logical_0d Subroutine
4 statements
Source File
public subroutine test_serialize_buffer_length_logical_0d()
Arguments
None
Calls
Contents
Source Code
test_serialize_buffer_length_logical_0d
Source Code
   subroutine test_serialize_buffer_length_logical_0d()
      @assertEqual(1, serialize_buffer_length(.true.))
      @assertEqual(1, serialize_buffer_length(.false.))
   end subroutine test_serialize_buffer_length_logical_0d
Call graph
test_serialize_buffer_length_logical_0d calls assertequal, serialize_buffer_length
serialize_buffer_length calls serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_int32_1d, serialize_buffer_length_string, serialize_buffer_length_int32_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d
serialize_buffer_length_logical_0d calls word_size, mapl_return
serialize_buffer_length_logical_1d calls word_size, mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int64_1d calls word_size, mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_real32_0d calls word_size, mapl_return
serialize_buffer_length_real32_1d calls word_size, mapl_return
serialize_buffer_length_real64_0d calls word_size, mapl_return
serialize_buffer_length_real64_1d calls word_size, mapl_return
word_size calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception