test_get_adjusted_time – MAPL
test_get_adjusted_time Subroutine
20 statements
Source File
public subroutine test_get_adjusted_time()
Arguments
None
Calls
Source Code
   subroutine test_get_adjusted_time
      type(ExtDataPointerUpdate) :: ex
      integer :: status, rc
      character(len=STRLEN) :: offset_string
      type(ESMF_TimeInterval) :: offset
      integer :: ios
      integer, parameter :: OFFSET_IN_SECONDS = 300
      integer :: expected(NF), actual(NF)
      write(offset_string, fmt='("PT", I03, "S")', iostat=ios) OFFSET_IN_SECONDS
      _VERIFY(ios)
      call ESMF_TimeIntervalSet(offset, s=OFFSET_IN_SECONDS, _RC)
      call get_int_time(default_time+offset, expected, _RC)
      call ex%create_from_parameters(UPDATE_TIMESTRING, UPDATE_FREQ_STRING, offset_string, default_time, clock, _RC)
      call get_int_time(ex%get_adjusted_time(default_time), actual, _RC)
      @assertEqual(expected, actual, 'Adjusted time does match expected time.')
   end subroutine test_get_adjusted_time
Call graph
test_get_adjusted_time calls ESMF_TimeIntervalSet, assertequal, create_from_parameters, get_adjusted_time, get_int_time, mapl_verify
create_from_parameters calls mapl_verify, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_return, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
get_adjusted_time calls mapl_return
get_int_time calls mapl_verify, ESMF_TimeGet, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_verify, mapl_assert, mapl_return
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message