test_get_dimension_missing – MAPL
test_get_dimension_missing Subroutine
7 statements
Source File
public subroutine test_get_dimension_missing()
Arguments
None
Calls
Source Code
   subroutine test_get_dimension_missing()
      type (FileMetadata) :: cf
      integer :: extent
      integer :: status
      !W.Y notes: If missing, crash
      extent = cf%get_dimension('x',rc=status)
      @assertEqual(status, pFIO_DIMENSION_NOT_FOUND)
      !extent = cf%get_dimension('x') ! without rc
      !@assertExceptionRaised('FileMetadata::get_dimension() - no such dimension <x>.')
      !@assertEqual(pFIO_DIMENSION_NOT_FOUND, status)
   end subroutine test_get_dimension_missing
Call graph
test_get_dimension_missing calls assertequal, get_dimension
get_dimension calls at, find, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize