test_convert_NetCDF_DateTimeString_to_ESMF_Time – MAPL
test_convert_NetCDF_DateTimeString_to_ESMF_Time Subroutine
16 statements
Source File
public subroutine test_convert_NetCDF_DateTimeString_to_ESMF_Time()
Arguments
None
Calls
Contents
Source Code
test_convert_NetCDF_DateTimeString_to_ESMF_Time
Source Code
   subroutine test_convert_NetCDF_DateTimeString_to_ESMF_Time()
      character(len=19), parameter:: netcdf_string='2023-01-31 14:04:37'
      type(ESMF_Time) :: etime
      integer :: yy, mm, dd, h, m, s
      integer :: status, rc
      call convert_NetCDF_DateTimeString_to_ESMF_Time(netcdf_string, etime, _RC)
      call ESMF_TimeGet(etime, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
      @assertEqual(2023, yy, 'Incorrect year')
      @assertEqual(01, mm, 'Incorrect month')
      @assertEqual(31, dd, 'Incorrect day')
      @assertEqual(14, h, 'Incorrect hour')
      @assertEqual(04, m, 'Incorrect minute')
      @assertEqual(37, s, 'Incorrect second')
   end subroutine test_convert_NetCDF_DateTimeString_to_ESMF_Time
Call graph
test_convert_netcdf_datetimestring_to_esmf_time calls ESMF_TimeGet, assertequal, convert_netcdf_datetimestring_to_esmf_time, mapl_verify
convert_netcdf_datetimestring_to_esmf_time calls mapl_verify, ESMF_CalendarSetDefault, ESMF_TimeSet, mapl_assert, convert_to_integer, is_valid_netcdf_datetime_string, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message