test_FieldSCAL_R8 – MAPL
test_FieldSCAL_R8 Subroutine
16 statements
Source File
public subroutine test_FieldSCAL_R8()
Arguments
None
Calls
Source Code
   subroutine test_FieldSCAL_R8()
      real(kind=ESMF_KIND_R8), parameter :: a = 2.0
      type(ESMF_Field) :: x
      real(kind=ESMF_KIND_R8), dimension(:,:), allocatable :: x_array
      real(kind=ESMF_KIND_R8), dimension(:,:), pointer :: x_ptr
      integer :: status, rc
      x = XR8
      call ESMF_FieldGet(x, farrayPtr = x_ptr, _RC)
      x_array = x_ptr
      call FieldSCAL(a, x, _RC)
      call ESMF_FieldGet(x, farrayPtr = x_ptr, _RC)
      @assertEqual(x_ptr, a*x_array)
   end subroutine test_FieldSCAL_R8
Call graph
test_fieldscal_r8 calls assertequal, esmf_fieldget, fieldscal, mapl_verify
fieldscal calls scale_r4, scale_r8
mapl_verify calls mapl_throw_exception
mapl_throw_exception calls initialize
scale_r4 calls mapl_verify, assign_fptr, mapl_return
scale_r8 calls mapl_verify, assign_fptr, mapl_return
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
mapl_return calls mapl_throw_exception, get_error_message