test_make_ESMF_TimeInterval – MAPL
test_make_ESMF_TimeInterval Subroutine
16 statements
Source File
public subroutine test_make_ESMF_TimeInterval()
Arguments
None
Calls
Contents
Source Code
test_make_ESMF_TimeInterval
Source Code
   subroutine test_make_ESMF_TimeInterval()
      character(len=*), parameter :: tunit = 'seconds'
      character(len=*), parameter :: iso_string = '2013-08-26T12:34:56'
      integer, parameter :: span = 1800
      type(ESMF_TimeInterval) :: expected_interval
      type(ESMF_Time) :: t0
      type(ESMF_TimeInterval) :: interval
      integer :: rc, status
      call ESMF_TimeSet(t0, iso_string, _RC)
      call ESMF_TimeIntervalSet(expected_interval, startTime=t0, s=span, _RC)
      call make_ESMF_TimeInterval(span, tunit, t0, interval, _RC)
      @assertTrue(expected_interval == interval, 'ESMF_TimeInterval variables do not match.')
   end subroutine test_make_ESMF_TimeInterval
Call graph
test_make_esmf_timeinterval calls ESMF_TimeIntervalSet, ESMF_TimeSet, asserttrue, make_esmf_timeinterval, mapl_verify
make_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_verify, mapl_assert, lr_trim, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message