test_get_inclusive – MAPL
test_get_inclusive Subroutine
14 statements
Source File
public subroutine test_get_inclusive()
Arguments
None
Calls
Source Code
   subroutine test_get_inclusive()
      type (MeterNode), target:: node
      class (AbstractMeter), pointer :: root_meter
      class (AbstractMeter), pointer :: submeter
      class (AbstractMeterNode), pointer :: child
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('sub1', AdvancedMeter(MpiTimerGauge()))
      root_meter => node%get_meter()
      child => node%get_child('sub1')
      submeter => child%get_meter()
      call submeter%add_cycle(1.0_REAL64)
      call root_meter%add_cycle(3.0_REAL64)
      @assertEqual(3.0, node%get_inclusive())
   end subroutine test_get_inclusive
Call graph
test_get_inclusive calls add_cycle, assertequal, add_child, get_child, get_inclusive, get_meter
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_inclusive calls get_total
find_child calls at
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity