test_create_from_parameters_heartbeat_negative_positive – MAPL
test_create_from_parameters_heartbeat_negative_positive Subroutine
13 statements
Source File
public subroutine test_create_from_parameters_heartbeat_negative_positive()
Arguments
None
Calls
Source Code
   subroutine test_create_from_parameters_heartbeat_negative_positive()
      type(ExtDataPointerUpdate) :: ex
      integer :: status, rc
      character(len=*), parameter :: OFFSET_STRING = '-+' // HEARTBEAT_STRING
      type(ESMF_TimeInterval) :: offset, interval
      integer :: expected, actual
      offset = timestep
      call ESMF_TimeIntervalGet(offset, s=expected, _RC)
      call ex%create_from_parameters(UPDATE_TIMESTRING, UPDATE_FREQ_STRING, OFFSET_STRING, default_time, clock, rc=status)
      @assertExceptionRaised('"+" and "-" cannot both be present in update_offset string.')
      @assertFalse(status == 0, 'An exception should have been thrown.')
   end subroutine test_create_from_parameters_heartbeat_negative_positive
Call graph
test_create_from_parameters_heartbeat_negative_positive calls ESMF_TimeIntervalGet, assertexceptionraised, assertfalse, create_from_parameters, mapl_verify
create_from_parameters calls mapl_verify, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_return, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls mapl_verify, mapl_assert, mapl_return, ESMF_TimeIntervalSet
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message