test_reset – MAPL
test_reset Subroutine
10 statements
Source File
public subroutine test_reset()
Arguments
None
Calls
Source Code
   subroutine test_reset()
      type (AdvancedMeter) :: t
      t = AdvancedMeter(MpiTimerGauge())
      call t%start()
      call t%add_cycle(increment=1._REAL64)
      call t%reset()
      @assertEqual(0, t%get_num_cycles())
      @assertFalse(t%is_active())
      @assertEqual(0, t%get_total())
   end subroutine test_reset
Call graph
test_reset calls assertequal, assertfalse, add_cycle, get_num_cycles, get_total, is_active, reset, start
add_cycle calls get_mean_cycle
start calls get_measurement
get_mean_cycle calls get_num_cycles