test_next_one_child – MAPL
test_next_one_child Subroutine
17 statements
Source File
public subroutine test_next_one_child()
Arguments
None
Calls
Source Code
   subroutine test_next_one_child()
      type (MeterNode) :: node
      class (AbstractMeterNodeIterator), allocatable :: iter_1
      class (AbstractMeterNodeIterator), allocatable :: iter_2
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      allocate(iter_1, source=node%begin())
      allocate(iter_2, source=node%begin())
      call node%add_child('a', AdvancedMeter(MpiTimerGauge()))
      call iter_1%next()
      call iter_2%next()
      @assertTrue(iter_1 == iter_2)
      @assertFalse(iter_1 /= iter_2)
      call iter_1%next()
      call iter_2%next()
      @assertTrue(iter_1 == iter_2)
      @assertFalse(iter_1 /= iter_2)
   end subroutine test_next_one_child
Call graph
test_next_one_child calls assertfalse, asserttrue, next, add_child, begin
add_child calls find_child, get_depth, v_push_back
find_child calls at
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity