test_make_arbitrary_decomposition – MAPL
test_make_arbitrary_decomposition Subroutine
9 statements
Source File
public subroutine test_make_arbitrary_decomposition(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_make_arbitrary_decomposition(this)
      class (ESMF_TestMethod), intent(inout) :: this
      type (LatLonGridFactory) :: factory
      integer :: nx, ny
      call factory%make_arbitrary_decomposition(nx, ny)
      @assertTrue(nx > 0)
      @assertTrue(ny > 0)
      @assertEqual(this%getPetCount(), nx*ny)
   end subroutine test_make_arbitrary_decomposition
Call graph
test_make_arbitrary_decomposition calls assertequal, asserttrue, getpetcount, make_arbitrary_decomposition
getpetcount calls ESMF_VMGet, getvm
make_arbitrary_decomposition calls ESMF_VMGet, ESMF_VMGetCurrent, mapl_return, mapl_verify
getvm calls ESMF_GridCompGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize