test_set_attribute_integer – MAPL
test_set_attribute_integer Subroutine
11 statements
Source File
public subroutine test_set_attribute_integer()
Arguments
None
Calls
Source Code
   subroutine test_set_attribute_integer
      type (ESMF_Config) :: config
      integer :: status
      integer :: nx
      config = MAPL_ConfigCreate()
      call MAPL_ConfigSetAttribute(config, value=12, label='NX:', rc=status)
      @assert_that(status, is(0))
      call ESMF_ConfigGetAttribute(config, value=nx, label='NX:', rc=status)
      @assert_that(status, is(0))
      @assert_that(nx, is(12))
   end subroutine test_set_attribute_integer
Call graph
test_set_attribute_integer calls ESMF_ConfigGetAttribute, assert_that, mapl_configsetattribute, mapl_configcreate
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configcreate calls ESMF_ConfigCreate, buffer, mapl_return
mapl_configsetattribute_int32 calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_configsetattribute_ints32 calls mapl_configsetattribute, mapl_return, mapl_assert, mapl_verify
mapl_configsetattribute_real32 calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_configsetattribute_real64 calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_configsetattribute_reals32 calls mapl_configsetattribute, mapl_return, mapl_assert, mapl_verify
mapl_configsetattribute_string calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception