test_convert_double – MAPL
test_convert_double Subroutine
17 statements
Source File
public subroutine test_convert_double()
Arguments
None
Calls
Source Code
   subroutine test_convert_double()
      real(c_double), parameter :: FROM = 1.0
      real(c_double), parameter :: EXPECTED = 1000.0
      real(c_double) :: actual
      type(Converter) :: conv
      integer(ut_status) :: status
      character(len=*), parameter :: FROM_STRING = KM
      character(len=*), parameter :: TO_STRING = M
      call initialize_udunits_system(rc=status)
      @assertEqual(UT_SUCCESS, status, 'Failed to initialize')
      call get_converter(conv, FROM_STRING, TO_STRING, rc=status)
      @assertEqual(UT_SUCCESS, status, 'Failed to get converter')
      actual = conv%convert(FROM)
      @assertEqual(actual, EXPECTED, 'Actual does not equal expected.')
      call conv%free()
      call finalize_udunits_system()
   end subroutine test_convert_double
Call graph
test_convert_double calls assertequal, finalize_udunits_system, initialize_udunits_system, convert, get_converter
get_converter calls get_converter_function, is_free
convert_double_5d calls cv_convert_doubles, get_cptr
get_converter_function calls is_free, instance_is_uninitialized
instance_is_uninitialized calls is_free