test_FieldConvertPrec_R4R8 – MAPL
test_FieldConvertPrec_R4R8 Subroutine
21 statements
Source File
public subroutine test_FieldConvertPrec_R4R8()
Arguments
None
Calls
Source Code
   subroutine test_FieldConvertPrec_R4R8()
      integer, parameter :: NROWS = 4
      integer, parameter :: NCOLS = NROWS
      type(ESMF_Field) :: r4_field, r8_field
      real(kind=ESMF_KIND_R4) :: r4_data(NROWS,NCOLS)
      real(kind=ESMF_KIND_R8) :: r8_data(NROWS,NCOLS)
      real(kind=ESMF_KIND_R8) :: r8_converted(NROWS,NCOLS)
      real(kind=ESMF_KIND_R8), pointer :: r8_pointer(:,:)
      integer :: rc, status
      call initialize_array(r4_data, 0.0, 1.0)
      r8_data = 0.0
      r8_converted = r4_data
      r4_field = mk_field(r4_data, regDecomp = REG_DECOMP_DEFAULT, minIndex = [1, 1], &
         maxIndex = [NROWS, NCOLS], indexflag = INDEX_FLAG_DEFAULT, &
         name = 'XR4', _RC)
      r8_field = mk_field(r8_data, regDecomp = REG_DECOMP_DEFAULT, minIndex = [1, 1], &
         maxIndex = [NROWS, NCOLS], indexflag = INDEX_FLAG_DEFAULT, &
         name = 'YR8', _RC)
      call FieldConvertPrec(r4_field, r8_field, _RC)
      call ESMF_FieldGet(r8_field, farrayPtr = r8_pointer, _RC)
!      @assertEqual(r8_converted, r8_pointer) !wdb fixme temporarily disabled
   end subroutine test_FieldConvertPrec_R4R8
Call graph
test_fieldconvertprec_r4r8 calls esmf_fieldget, fieldconvertprec, initialize_array, mk_field, mapl_verify
fieldconvertprec calls convert_prec
initialize_array calls initialize_array_r4, initialize_array_r8
mk_field calls mk_field_r4_2d, mk_field_r8_2d
mapl_verify calls mapl_throw_exception
convert_prec calls esmf_fieldget, mapl_verify, fieldcopy, mapl_assert, convert_prec_r4_to_r8, convert_prec_r8_to_r4, is_valid_typekind, mapl_return
initialize_array_r4 calls mapl_assert
initialize_array_r8 calls mapl_assert
mapl_throw_exception calls initialize
mk_field_r4_2d calls esmf_fieldget, mapl_verify, mapl_return, mk_field_common
mk_field_r8_2d calls esmf_fieldget, mapl_verify, mapl_return, mk_field_common
fieldcopy calls copy
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_prec_r4_to_r8 calls mapl_verify, mapl_return, assign_fptr
convert_prec_r8_to_r4 calls mapl_verify, mapl_return, assign_fptr
mapl_return calls mapl_throw_exception, get_error_message
mk_field_common calls mapl_verify, mapl_return, esmf_fieldcreate, mk_grid