test_accumulate_sub – MAPL
test_accumulate_sub Subroutine
13 statements
Source File
public subroutine test_accumulate_sub()
Arguments
None
Calls
Source Code
   subroutine test_accumulate_sub()
      type(TimeProfiler), target :: main, lap
      class(AbstractMeterNode), pointer :: main_node
      main = TimeProfiler('main')
      call main%start()
      lap = TimeProfiler('lap')
      call lap%start()
      call lap%finalize()
      call main%accumulate(lap)
      ! should now have 'lap' as a subtimer of 'main'
      @assertEqual(2, main%get_num_meters())
      main_node => main%get_root_node()
      @assertTrue(main_node%has_child('lap'))
   end subroutine test_accumulate_sub
Call graph
test_accumulate_sub calls assertequal, asserttrue, has_child, start, accumulate, finalize, get_num_meters, get_root_node
accumulate calls get_root_node, accumulate, vector_back
finalize calls finalize, get_meter, vector_pop_back, mpi_op_free, mpi_type_free, mapl_verify
get_num_meters calls get_num_nodes
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
start_self calls mapl_assert, start, get_name, mapl_return
vector_pop_back calls vector_downsize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception