test_var_dims_defined – MAPL
test_var_dims_defined Subroutine
11 statements
Source File
public subroutine test_var_dims_defined()
Arguments
None
Calls
Source Code
   subroutine test_var_dims_defined()
      type (FileMetadata) :: cf
      type (Variable) :: v
      integer :: status
      cf = FileMetaData()
      call cf%add_dimension('x', 10)
      call cf%add_dimension('y', 20)
      v = Variable(type=pFIO_REAL64, dimensions='x,y')
      call cf%add_variable('mass', v, rc=status)
      !@assertExceptionRaised("FileMetadata::add_variable() - undefined dimension 'z'.")
      @assertEqual(0, status)
   end subroutine test_var_dims_defined
Call graph
test_var_dims_defined calls assertequal, add_dimension, add_variable
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize