test_time – MAPL
test_time Subroutine
19 statements
Source File
public subroutine test_time()
Arguments
None
Calls
Source Code
   subroutine test_time()
      integer :: time
      time = 000000
      @assert_that(is_valid_time(time), is(true()))
      time = 235959
      @assert_that(is_valid_time(time), is(true()))
      time = 240000
      @assert_that(is_valid_time(time), is(true()))
      time = -000001
      @assert_that(is_valid_time(time), is(false()))
      time = 240001
      @assert_that(is_valid_time(time), is(false()))
      time = 006000
      @assert_that(is_valid_time(time), is(false()))
      time = 000060
      @assert_that(is_valid_time(time), is(false()))
      time = 234567
      @assert_that(is_valid_time(time), is(false()))
   end subroutine test_time
Call graph
test_time calls assert_that, false, is_valid_time, true