test_string_to_integer_time_delimiters – MAPL
test_string_to_integer_time_delimiters Subroutine
8 statements
Source File
public subroutine test_string_to_integer_time_delimiters()
Arguments
None
Calls
Source Code
    subroutine test_string_to_integer_time_delimiters()
        character(len=*), parameter :: time_string = '21:00:00'
        integer :: expected_time = -1
        integer :: actual_time = -2
        expected_time = 21*HOUR_FACTOR + 0*MINUTE_FACTOR + 0*SECOND_FACTOR
        actual_time = string_to_integer_time(time_string)
        @assertEqual(expected_time, actual_time)
    end subroutine test_string_to_integer_time_delimiters
Call graph
test_string_to_integer_time_delimiters calls assertequal, string_to_integer_time
string_to_integer_time calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize