test_convert_ISO8601_to_integer_time – MAPL
test_convert_ISO8601_to_integer_time Subroutine
11 statements
Source File
public subroutine test_convert_ISO8601_to_integer_time()
Arguments
None
Calls
Contents
Source Code
test_convert_ISO8601_to_integer_time
Source Code
   subroutine test_convert_ISO8601_to_integer_time()
      character(len=8) :: time_string
      integer :: actual
      integer :: expected
      integer :: status
      time_string = 'T174107Z'
      expected = 174107
      actual = convert_ISO8601_to_integer_time(time_string, rc=status)
      @assertEqual(SUCCESS, status)
      @assertEqual(expected, actual)
   end subroutine test_convert_ISO8601_to_integer_time
Call graph
test_convert_iso8601_to_integer_time calls assertequal, convert_iso8601_to_integer_time
convert_iso8601_to_integer_time calls iso8601time, get_hour, get_minute, get_second, mapl_return, mapl_verify
iso8601time calls construct_iso8601time
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
construct_iso8601time calls mapl_return, mapl_assert, parse_time
get_error_message calls at
mapl_throw_exception calls initialize