test_serialize_logical_array – MAPL
test_serialize_logical_array Subroutine
18 statements
Source File
public subroutine test_serialize_logical_array()
Arguments
None
Calls
Source Code
   subroutine test_serialize_logical_array()
      call check([.true.]); if (anyExceptions()) return
      call check([.false.]); if (anyExceptions()) return
      call check([.true.,.false.]); if (anyExceptions()) return
   contains
      subroutine check(expected)
         logical, intent(in) :: expected(:)
         logical, allocatable :: found(:)
         integer :: i
         call deserialize_intrinsic(serialize_intrinsic(expected),found)
         do i = 1,size(expected)
            @assertEqual(expected(i), found(i))
         enddo
      end subroutine check
   end subroutine test_serialize_logical_array
Call graph
test_serialize_logical_array calls anyexceptions, assertequal, deserialize_intrinsic, serialize_intrinsic
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
deserialize_int32_0d calls mapl_assert, mapl_return
deserialize_int32_1d calls mapl_assert, mapl_return
deserialize_int64_0d calls mapl_assert, mapl_return
deserialize_int64_1d calls mapl_assert, mapl_return
deserialize_logical_0d calls mapl_assert, mapl_return
deserialize_logical_1d calls mapl_assert, mapl_return
deserialize_real32_0d calls mapl_assert, mapl_return
deserialize_real32_1d calls mapl_assert, mapl_return
deserialize_real64_0d calls mapl_assert, mapl_return
deserialize_real64_1d calls mapl_assert, mapl_return
deserialize_string calls mapl_assert, mapl_return
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return