test_make_NetCDF_DateTime_units_string – MAPL
test_make_NetCDF_DateTime_units_string Subroutine
12 statements
Source File
public subroutine test_make_NetCDF_DateTime_units_string()
Arguments
None
Calls
Contents
Source Code
test_make_NetCDF_DateTime_units_string
Source Code
   subroutine test_make_NetCDF_DateTime_units_string()
      type(ESMF_Time) :: t0
      character(len=*), parameter :: tunit = 'seconds'
      character(len=*), parameter :: expected = tunit // ' since 2012-08-26 08:36:37'
      character(len=:), allocatable :: actual
      integer :: status, rc
      call ESMF_TimeSet(t0, yy=2012, mm=08, dd=26, h=08, m=36, s=37, _RC)
      call make_NetCDF_DateTime_units_string(t0, tunit, actual, _RC)
      @assertEqual(expected, actual, 'Strings don''t match: ' // expected // '/=' // actual)
   end subroutine test_make_NetCDF_DateTime_units_string
Call graph
test_make_netcdf_datetime_units_string calls ESMF_TimeSet, assertequal, make_netcdf_datetime_units_string, mapl_verify
make_netcdf_datetime_units_string calls mapl_verify, convert_esmf_time_to_netcdf_datetimestring, mapl_return
mapl_verify calls mapl_throw_exception
convert_esmf_time_to_netcdf_datetimestring calls mapl_verify, mapl_return, ESMF_TimeGet, mapl_assert
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at