test_node_reset – MAPL
test_node_reset Subroutine
24 statements
Source File
public subroutine test_node_reset()
Arguments
None
Calls
Source Code
   subroutine test_node_reset()
      type (MeterNode) :: node
      class (AbstractMeter), pointer :: root_meter
      class (AbstractMeter), pointer :: submeter
      class (AbstractMeterNode), pointer :: child, grandchild
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('A', AdvancedMeter(MpiTimerGauge()))
      root_meter => node%get_meter()
      child => node%get_child('A')
      submeter => child%get_meter()
      call submeter%add_cycle(10.0_REAL64)
      call child%add_child('A1', AdvancedMeter(MpiTimerGauge()))
      call child%add_child('A2', AdvancedMeter(MpiTimerGauge()))
      grandchild => child%get_child('A1')
      submeter => grandchild%get_meter()
      call submeter%add_cycle(2.0_REAL64)
      grandchild => child%get_child('A2')
      submeter => grandchild%get_meter()
      call submeter%add_cycle(3.0_REAL64)
      call node%reset()
      @assertEqual(0, node%get_inclusive())
      @assertEqual(0, child%get_inclusive())
      @assertEqual(0, grandchild%get_inclusive())
   end subroutine test_node_reset
Call graph
test_node_reset calls add_cycle, assertequal, add_child, get_child, get_inclusive, get_meter, reset
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_inclusive calls get_total
reset calls v_begin, v_iter_get, v_iter_next, reset
find_child calls at
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity