test_cartesian_to_spherical_Y – MAPL
test_cartesian_to_spherical_Y Subroutine
32 statements
Source File
public subroutine test_cartesian_to_spherical_Y(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_cartesian_to_spherical_Y(this)
      class (ESMF_TestMethod), intent(inout) :: this
      type (LatLonGridFactory) :: factory
      real, allocatable :: u(:,:)
      real, allocatable :: v(:,:)
      real, allocatable :: xyz(:,:,:,:)
      real, allocatable :: longitudes(:)
      real, allocatable :: latitudes(:)
      integer, parameter :: IM=12, JM=6
      type (ESMF_Grid) :: grid
      integer :: status
      _UNUSED_DUMMY(this)
      factory = LatLonGridFactory(im_world=IM, jm_world=JM, lm=1, nx=1, ny=1, pole='PE', dateline='GC')
      grid = factory%make_grid()
      allocate(u(IM,JM))
      allocate(v(IM,JM))
      allocate(xyz(3,1,IM,JM))
      XYZ(1,1,:,:) = 0
      XYZ(2,1,:,:) = 1
      XYZ(3,1,:,:) = 0
      call factory%cartesian_to_spherical(xyz, u, v, basis='north-south',rc=status)
      @assertEqual(0,status)
      ! Note: longitudes return as REAL64.
      longitudes = real(factory%get_longitudes())
      latitudes = real(factory%get_latitudes())
      do j = 1, JM
         @assertEqual(+cos(longitudes), u(:,j), 10*epsilon(1.))
         @assertEqual(-sin(longitudes)*sin(latitudes(j)), v(:,j), 10*epsilon(1.))
      end do
   end subroutine test_cartesian_to_spherical_Y
Call graph
test_cartesian_to_spherical_y calls assertequal, cartesian_to_spherical, get_latitudes, get_longitudes, make_grid
get_latitudes calls mapl_return
get_longitudes calls mapl_return
make_grid calls make_new_grid, mapl_return, mapl_verify
cartesian_to_spherical_3d_real64 calls mapl_return, mapl_verify, mapl_assert, get_basis
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_basis calls mapl_return, mapl_verify, mapl_assert, ESMF_GridGetCoord, computegridbasis, computexyzbasis
get_error_message calls at, insert
mapl_throw_exception calls initialize