test_ISO8601Time_getters – MAPL
test_ISO8601Time_getters Subroutine
18 statements
Source File
public subroutine test_ISO8601Time_getters()
Arguments
None
Calls
Contents
Source Code
test_ISO8601Time_getters
Source Code
   subroutine test_ISO8601Time_getters()
      type(ISO8601Time) :: time
      integer, parameter :: HOUR = 14
      integer, parameter :: MINUTE = 41
      integer, parameter :: SECOND = 37
      integer, parameter :: MILLISECOND = 357
      integer, parameter :: TZ_OFFSET = 0
      time%hour_ = HOUR
      time%minute_ = MINUTE
      time%second_ = SECOND
      time%millisecond_ = MILLISECOND
      time%timezone_offset_ = TZ_OFFSET
      @assertEqual(HOUR, time%get_hour())
      @assertEqual(MINUTE, time%get_minute())
      @assertEqual(SECOND, time%get_second())
      @assertEqual(MILLISECOND, time%get_millisecond())
      @assertEqual(TZ_OFFSET, time%get_timezone_offset())
   end subroutine test_ISO8601Time_getters
Call graph
test_iso8601time_getters calls assertequal, get_hour, get_millisecond, get_minute, get_second, get_timezone_offset