test_get_exclusive – MAPL
test_get_exclusive Subroutine
14 statements
Source File
public subroutine test_get_exclusive()
Arguments
None
Calls
Source Code
   subroutine test_get_exclusive()
      type (MeterNode), target:: node
      class (AbstractMeter), pointer :: root_meter
      class (AbstractMeter), pointer :: submeter
      class (AbstractMeterNode), pointer :: child
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('sub1', AdvancedMeter(MpiTimerGauge()))
      root_meter => node%get_meter()
      child => node%get_child('sub1')
      submeter => child%get_meter()
      call submeter%add_cycle(1.0_REAL64)
      call root_meter%add_cycle(3.0_REAL64)
      @assertEqual(2.0, node%get_exclusive())
   end subroutine test_get_exclusive
Call graph
test_get_exclusive calls add_cycle, assertequal, add_child, get_child, get_exclusive, get_meter
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_exclusive calls get_inclusive, v_begin, v_iter_get, v_iter_next
find_child calls at
get_inclusive calls get_total
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity