test_get_num_nodes – MAPL
test_get_num_nodes Subroutine
14 statements
Source File
public subroutine test_get_num_nodes()
Arguments
None
Calls
Source Code
   subroutine test_get_num_nodes()
      type (MeterNode) :: node
      class (AbstractMeterNode), pointer :: child
      @assertEqual(1, node%get_num_nodes())
      call node%add_child('a', AdvancedMeter(MpiTimerGauge()))
      @assertEqual(2, node%get_num_nodes())
      call node%add_child('b', AdvancedMeter(MpiTimerGauge()))
      @assertEqual(3, node%get_num_nodes())
      child => node%get_child('a')
      call child%add_child('cat', AdvancedMeter(MpiTimerGauge()))
      call child%add_child('dog', AdvancedMeter(MpiTimerGauge()))
      call child%add_child('fish', AdvancedMeter(MpiTimerGauge()))
      @assertEqual(6, node%get_num_nodes())
   end subroutine test_get_num_nodes
Call graph
test_get_num_nodes calls assertequal, add_child, get_child, get_num_nodes
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
find_child calls at
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity