test_FieldsAreConformableR4 – MAPL
test_FieldsAreConformableR4 Subroutine
12 statements
Source File
public subroutine test_FieldsAreConformableR4(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldsAreConformableR4(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x, y
      integer :: status, rc
      logical :: are_conformable
      x = XR4
      y = YR4
      are_conformable = .FALSE.
      are_conformable = FieldsAreConformable(x, y, _RC)
      @assertTrue(are_conformable)
   end subroutine test_FieldsAreConformableR4
Call graph
test_fieldsareconformabler4 calls asserttrue, fieldsareconformable, mapl_verify
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_verify calls mapl_throw_exception
are_conformable_array calls fieldsareconformable, mapl_verify, mapl_return
are_conformable_scalar calls mapl_verify, esmf_fieldget, fieldgetlocalelementcount, mapl_return
mapl_throw_exception calls initialize
fieldgetlocalelementcount calls get_local_element_count
mapl_return calls mapl_throw_exception, get_error_message