test_is_valid_hour – MAPL
test_is_valid_hour Subroutine
10 statements
Source File
public subroutine test_is_valid_hour()
Arguments
None
Calls
Source Code
   subroutine test_is_valid_hour()
      integer, parameter :: IMIN = 0
      integer, parameter :: IMAX = 23
      integer :: i
      do i= IMIN, IMAX
         @assertTrue(is_valid_hour(i))
      end do
      @assertFalse(is_valid_hour(IMAX+1))
      @assertFalse(is_valid_hour(IMIN-1))
   end subroutine test_is_valid_hour
Call graph
test_is_valid_hour calls assertfalse, asserttrue, is_valid_hour
is_valid_hour calls is_between