test_get_child – MAPL
test_get_child Subroutine
24 statements
Source File
public subroutine test_get_child()
Arguments
None
Calls
Source Code
   subroutine test_get_child()
      type(ConcreteComposite) :: child
      type(ConcreteComposite), target :: parent
      type(NamedComponent) :: P, A
      class(AbstractComposite), pointer :: ptr
      P%name = 'p'
      A%name = 'A'
      parent = ConcreteComposite(P)
      child = ConcreteComposite(A)
      ptr => parent%add_child('A', child)
      ptr => parent%get_child('A')
      @assert_that(associated(ptr), is(true()))
      select type (ptr)
      type is (ConcreteComposite)
         select type (q => ptr%get_component())
         type is (NamedComponent)
            @assert_that(q%name, is('A'))
         class default
            @assert_that('incorrect type', .true., is(false()))
         end select
      class default
         @assert_that('incorrect type', .true., is(false()))
      end select
   end subroutine test_get_child
Call graph
test_get_child calls assert_that, false, get_component, get_child, add_child, true
add_child calls insert, m_at, push_back
get_child_by_index calls get_child, of
get_child_by_name calls m_at
m_at calls m_find
m_find calls s_find
m_insert_pair calls s_insert