test_get_standard_deviation – MAPL
test_get_standard_deviation Subroutine
16 statements
Source File
public subroutine test_get_standard_deviation()
Arguments
None
Calls
Source Code
   subroutine test_get_standard_deviation()
      type (AdvancedMeter) :: t
      t = AdvancedMeter(MpiTimerGauge())
      call t%add_cycle(increment=1._REAL64)
      call t%add_cycle(increment=3._REAL64)
      @assertEqual(1., t%get_standard_deviation())
      call t%reset()
      call t%add_cycle(increment=1._REAL64)
      call t%add_cycle(increment=3._REAL64)
      @assertEqual(1., t%get_standard_deviation())
      call t%reset()
      call t%add_cycle(increment=7._REAL64 - 2)
      call t%add_cycle(increment=7._REAL64 - 1)
      call t%add_cycle(increment=7._REAL64 + 3)
      @assertEqual(sqrt(14._REAL64/3), t%get_standard_deviation())
   end subroutine test_get_standard_deviation
Call graph
test_get_standard_deviation calls assertequal, add_cycle, get_standard_deviation, reset
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles