test_FieldCOPY_R8R4 – MAPL
test_FieldCOPY_R8R4 Subroutine
20 statements
Source File
public subroutine test_FieldCOPY_R8R4(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldCOPY_R8R4(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x
      type(ESMF_Field) :: y
      real(kind=ESMF_KIND_R8), dimension(:,:), pointer :: x_ptr
      real(kind=ESMF_KIND_R4), dimension(:,:), pointer :: y_ptr
      integer :: status, rc
      x = XR8
      y = YR4
      call ESMF_FieldGet(x, farrayPtr = x_ptr, _RC)
      x_ptr = 4.d0
      call FieldCOPY(x, y, _RC)
      call ESMF_FieldGet(x, farrayPtr = x_ptr, _RC)
      call ESMF_FieldGet(y, farrayPtr = y_ptr, _RC)
      @assertTrue(all(are_almost_equal(x_ptr, y_ptr)), 'Values differ above threshold.')
   end subroutine test_FieldCOPY_R8R4
Call graph
test_fieldcopy_r8r4 calls asserttrue, esmf_fieldget, fieldcopy, are_almost_equal, mapl_verify
fieldcopy calls copy
mapl_verify calls mapl_throw_exception
copy calls esmf_fieldget, mapl_verify, fieldgetcptr, fieldgetlocalsize, fieldsareconformable, mapl_assert, copy_r4_r4, copy_r4_r8, copy_r8_r4, copy_r8_r8, mapl_return
mapl_throw_exception calls initialize
fieldgetcptr calls get_cptr
fieldgetlocalsize calls get_local_size
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message