test_construct_ISO8601Time – MAPL
test_construct_ISO8601Time Subroutine
25 statements
Source File
public subroutine test_construct_ISO8601Time()
Arguments
None
Calls
Contents
Source Code
test_construct_ISO8601Time
Source Code
   subroutine test_construct_ISO8601Time()
      type(ISO8601Time) :: isotime
      integer :: hour = 17
      integer :: minute = 49
      integer :: second = 07
      integer :: millisecond = 357
      integer :: timezone_offset = 0
      character(len=*), parameter :: delimited = 'T17:49:07.357Z'
      character(len=*), parameter :: undelimited = 'T174907.357Z'
      integer :: status
      isotime = construct_ISO8601Time(delimited, rc = status)
      @assertEqual(SUCCESS, status)
      @assertEqual(hour, isotime%get_hour())
      @assertEqual(minute, isotime%get_minute())
      @assertEqual(second, isotime%get_second())
      @assertEqual(millisecond, isotime%get_millisecond())
      @assertEqual(timezone_offset, isotime%get_timezone_offset())
      isotime = construct_ISO8601Time(undelimited, rc = status)
      @assertEqual(SUCCESS, status)
      @assertEqual(hour, isotime%get_hour())
      @assertEqual(minute, isotime%get_minute())
      @assertEqual(second, isotime%get_second())
      @assertEqual(millisecond, isotime%get_millisecond())
      @assertEqual(timezone_offset, isotime%get_timezone_offset())
   end subroutine test_construct_ISO8601Time
Call graph
test_construct_iso8601time calls assertequal, construct_iso8601time, get_hour, get_millisecond, get_minute, get_second, get_timezone_offset
construct_iso8601time calls mapl_assert, mapl_return, parse_time
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
parse_time calls time_fields, is_valid_time, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
time_fields calls construct_time_fields
get_error_message calls at
is_valid_time calls is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed