test_get_dimension – MAPL
test_get_dimension Subroutine
7 statements
Source File
public subroutine test_get_dimension()
Arguments
None
Calls
Source Code
   subroutine test_get_dimension()
      type (FileMetadata) :: cf
      call cf%add_dimension('x', 10)
      call cf%add_dimension('y', 11)
      @assertEqual(10, cf%get_dimension('x'))
      @assertEqual(11, cf%get_dimension('y'))
   end subroutine test_get_dimension
Call graph
test_get_dimension calls assertequal, add_dimension, get_dimension
add_dimension calls insert, mapl_return
get_dimension calls at, find, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize