test_convert_NetCDF_DateTime_to_ESMF – MAPL
test_convert_NetCDF_DateTime_to_ESMF Subroutine
26 statements
Source File
public subroutine test_convert_NetCDF_DateTime_to_ESMF()
Arguments
None
Calls
Contents
Source Code
test_convert_NetCDF_DateTime_to_ESMF
Source Code
   subroutine test_convert_NetCDF_DateTime_to_ESMF()
      character(len=*), parameter :: expected_tunit = 'seconds'
      integer, parameter :: int_time = 1800
      character(len=*), parameter :: units_string = expected_tunit // ' since 2012-08-26 12:36:37'
      character(len=*), parameter :: t0_iso_string = '2012-08-26T12:36:37'
      character(len=*), parameter :: t1_iso_string = '2012-08-26T13:06:37'
      type(ESMF_TimeInterval) :: expected_interval
      type(ESMF_Time) :: expected_time0
      type(ESMF_Time) :: expected_time1
      type(ESMF_TimeInterval) :: interval
      type(ESMF_Time) :: time0
      type(ESMF_Time) :: time1
      character(len=:), allocatable :: tunit
      integer :: rc, status
      call ESMF_TimeSet(expected_time0, timeString=t0_iso_string, _RC)
      call ESMF_TimeSet(expected_time1, timeString=t1_iso_string, _RC)
      call ESMF_TimeIntervalSet(expected_interval, startTime=expected_time0, s=int_time, _RC)
      call convert_NetCDF_DateTime_to_ESMF(int_time, units_string, interval, time0, time1=time1, tunit=tunit, _RC)
      @assertTrue(expected_time0 == time0, 'Mismatch for time0')
      @assertTrue(expected_time1 == time1, 'Mismatch for time1')
      @assertTrue(expected_interval == interval, 'Mismatch for interval')
   end subroutine test_convert_NetCDF_DateTime_to_ESMF
Call graph
test_convert_netcdf_datetime_to_esmf calls ESMF_TimeIntervalSet, ESMF_TimeSet, asserttrue, convert_netcdf_datetime_to_esmf, mapl_verify
convert_netcdf_datetime_to_esmf calls mapl_verify, mapl_assert, convert_netcdf_datetimestring_to_esmf_time, get_shift_sign, is_time_unit, lr_trim, make_esmf_timeinterval, mapl_return, split
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_netcdf_datetimestring_to_esmf_time calls ESMF_TimeSet, mapl_verify, mapl_assert, mapl_return, ESMF_CalendarSetDefault, convert_to_integer, is_valid_netcdf_datetime_string
get_shift_sign calls lr_trim
is_time_unit calls lr_trim
make_esmf_timeinterval calls ESMF_TimeIntervalSet, mapl_verify, mapl_assert, lr_trim, mapl_return
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message