test_FieldGetLocalSize – MAPL
test_FieldGetLocalSize Subroutine
20 statements
Source File
public subroutine test_FieldGetLocalSize(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldGetLocalSize(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x
      integer :: status, rc
      integer :: rank
      integer :: expected_size
      integer :: actual_size
      integer, allocatable :: element_count(:)
      x = XR4
      call ESMF_FieldGet(x, rank=rank, _RC)
      allocate(element_count(rank))
      call ESMF_FieldGet(x, localElementCount=element_count, _RC)
      expected_size = sum(element_count)
      actual_size=FieldGetLocalSize(x, _RC)
      @assertEqual(actual_size, expected_size)
      if(allocated(element_count)) deallocate(element_count)
   end subroutine test_FieldGetLocalSize
Call graph
test_fieldgetlocalsize calls assertequal, esmf_fieldget, fieldgetlocalsize, mapl_verify
fieldgetlocalsize calls get_local_size
mapl_verify calls mapl_throw_exception
get_local_size calls mapl_verify, fieldgetlocalelementcount, mapl_return
mapl_throw_exception calls initialize
fieldgetlocalelementcount calls get_local_element_count
mapl_return calls mapl_throw_exception, get_error_message