test_serialize – MAPL
test_serialize Subroutine
64 statements
Source File
public subroutine test_serialize()
Arguments
None
Calls
Contents
Source Code
test_serialize
Source Code
   subroutine test_serialize()
      type (UnlimitedEntity) :: a,b
      integer,allocatable :: buffer(:)
      real, dimension(2*3*4*5) :: array
      real, dimension(2*3,4*5) :: a2d
      real, dimension(2*3,4,5) :: a3d
      real, dimension(2,3,4,5) :: a4d
      integer :: i
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(b%is_empty())
      deallocate(buffer)
      a = UnlimitedEntity('')
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(b%is_empty())
      deallocate(buffer)
      do i = 1, 2*3*4*5
         array(i) = i*1.0
      enddo
      a = UnlimitedEntity(10)
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = UnlimitedEntity([10,20,30])
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = UnlimitedEntity([.true.,.false.])
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = UnlimitedEntity('abcd')
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a = UnlimitedEntity('abcdefgh')
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a2d = reshape(array,(/2*3,4*5/))
      a = UnlimitedEntity(a2d)
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a3d = reshape(array,(/2*3,4,5/))
      a = UnlimitedEntity(a3d)
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
      a4d = reshape(array,(/2,3,4,5/))
      a = UnlimitedEntity(a4d)
      call a%serialize(buffer)
      call UnlimitedEntity_deserialize(buffer,b)
      @assertTrue(a==b)
      deallocate(buffer)
   end subroutine test_serialize
Call graph
test_serialize calls asserttrue, is_empty, unlimitedentity_deserialize, serialize
unlimitedentity_deserialize calls unlimitedentity, mapl_return, mapl_verify
unlimitedentity calls new_unlimitedentity_0d, new_unlimitedentity_1d, new_unlimitedentity_2d, new_unlimitedentity_3d, new_unlimitedentity_4d, new_unlimitedentity_5d, new_unlimitedentity_empty
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_throw_exception calls initialize
new_unlimitedentity_0d calls mapl_return
new_unlimitedentity_1d calls mapl_return, mapl_assert
new_unlimitedentity_2d calls unlimitedentity, mapl_return, mapl_assert
new_unlimitedentity_3d calls unlimitedentity, mapl_return, mapl_assert
new_unlimitedentity_4d calls unlimitedentity, mapl_return, mapl_assert
new_unlimitedentity_5d calls unlimitedentity, mapl_return, mapl_assert