test_MAPL_decomposeDim_even – MAPL
test_MAPL_decomposeDim_even Subroutine
10 statements
Source File
public subroutine test_MAPL_decomposeDim_even()
Arguments
None
Calls
Contents
Source Code
test_MAPL_decomposeDim_even
Source Code
   subroutine test_MAPL_decomposeDim_even()
      integer :: NDEs
      integer :: dim_world
      integer, allocatable :: dim(:)
      NDEs = 4
      allocate(dim(0:NDEs-1))
      dim_world = 12
      call MAPL_DecomposeDim(dim_world, dim, NDEs)
      @assertEqual(12/4, dim)
   end subroutine test_MAPL_decomposeDim_even
Call graph
test_mapl_decomposedim_even calls assertequal, mapl_decomposedim
mapl_decomposedim calls mapl_decomposedim