test_serialize_real_array – MAPL
test_serialize_real_array Subroutine
17 statements
Source File
public subroutine test_serialize_real_array()
Arguments
None
Calls
Source Code
   subroutine test_serialize_real_array()
      call check([1.0]); if (anyExceptions()) return
      call check([2.0]); if (anyExceptions()) return
      call check([1.0,2.0]); if (anyExceptions()) return
      call check([1.0,2.0,3.0]); if (anyExceptions()) return
   contains
      subroutine check(expected)
         real, intent(in) :: expected(:)
         real, allocatable :: found(:)
         call deserialize_intrinsic(serialize_intrinsic(expected),found)
         @assertEqual(expected, found)
      end subroutine check
   end subroutine test_serialize_real_array
Call graph
test_serialize_real_array calls anyexceptions, assertequal, deserialize_intrinsic, serialize_intrinsic
deserialize_intrinsic calls deserialize_int32_0d, deserialize_int32_1d, deserialize_int64_0d, deserialize_int64_1d, deserialize_logical_0d, deserialize_logical_1d, deserialize_real32_0d, deserialize_real32_1d, deserialize_real64_0d, deserialize_real64_1d, deserialize_string
serialize_intrinsic calls serialize_int32_0d, serialize_int32_1d, serialize_int64_0d, serialize_int64_1d, serialize_logical_0d, serialize_logical_1d, serialize_real32_0d, serialize_real32_1d, serialize_real64_0d, serialize_real64_1d, serialize_string
deserialize_int32_0d calls mapl_assert, mapl_return
deserialize_int32_1d calls mapl_assert, mapl_return
deserialize_int64_0d calls mapl_assert, mapl_return
deserialize_int64_1d calls mapl_assert, mapl_return
deserialize_logical_0d calls mapl_assert, mapl_return
deserialize_logical_1d calls mapl_assert, mapl_return
deserialize_real32_0d calls mapl_assert, mapl_return
deserialize_real32_1d calls mapl_assert, mapl_return
deserialize_real64_0d calls mapl_assert, mapl_return
deserialize_real64_1d calls mapl_assert, mapl_return
deserialize_string calls mapl_assert, mapl_return
serialize_int32_0d calls mapl_return
serialize_int32_1d calls mapl_return
serialize_int64_0d calls mapl_return
serialize_int64_1d calls mapl_return, word_size
serialize_logical_0d calls mapl_return
serialize_logical_1d calls mapl_return, word_size
serialize_real32_0d calls mapl_return
serialize_real32_1d calls mapl_return, word_size
serialize_real64_0d calls mapl_return
serialize_real64_1d calls mapl_return, word_size
serialize_string calls mapl_return