test_wait – MAPL
test_wait Subroutine
44 statements
Source File
public subroutine test_wait()
Arguments
None
Calls
Source Code
   subroutine test_wait()
      type (MockClientThread), target :: c
      class (AbstractSocket), pointer :: connection
      integer :: collection_id
      integer :: request_id1
      integer :: request_id2
      real(kind=REAL32), target :: q1
      real(kind=REAL32), target :: q2(3)
      real(kind=REAL32) :: q1_expected = 3.14
      real(kind=REAL32) :: q2_expected(3) = [1,2,3]
      character(len=:), allocatable :: expected_log
      type (MockSocketLog), target :: log
      type(MockSocket), target :: ms
      ms = MockSocket(log)
      call c%set_connection(ms)
      connection => c%get_connection()
      select type (connection)
      type is (MockSocket)
         call connection%add_message(IdMessage(1))
         call connection%add_message(IdMessage(1)) ! note value not used
         call connection%add_message(IdMessage(2))
         connection%q1 = q1_expected
         connection%q2 = q2_expected
      end select
      collection_id = c%add_ext_collection(template='foo')
      request_id1 = c%prefetch_data(collection_id, 'foo', 'q1', ArrayReference(q1))
      request_id2 = c%prefetch_data(collection_id, 'foo', 'q2', ArrayReference(q2))
      call c%wait(request_id1)
      call c%wait(request_id2)
      @assertTrue (request_id1 /= request_id2)
      expected_log = "send<AddExtCollection('foo')>"
      expected_log = expected_log // " :: send<PrefetchData('q1')>"
      expected_log = expected_log // " :: get()"
      expected_log = expected_log // " :: send<PrefetchData('q2')>"
      expected_log = expected_log // " :: get()"
      !write(str,'(i0)') request_id1
      !expected_log = expected_log // " :: send<Wait("//trim(str)//")>"
      !write(str,'(i0)') request_id2
      expected_log = expected_log // " :: wait()"
      !expected_log = expected_log // " :: send<Wait("//trim(str)//")>"
      expected_log = expected_log // " :: wait()"
      select type (connection)
      type is (MockSocket)
         @assertEqual(expected_log, log%log)
      end select
      @assertEqual(q1_expected, q1)
      @assertEqual(q2_expected, q2)
   end subroutine test_wait
Call graph
test_wait calls add_message, assertequal, asserttrue, add_ext_collection, get_connection, prefetch_data, set_connection
add_ext_collection calls get_connection, mapl_assert, mapl_return, mapl_verify, receive, send
get_connection calls mapl_assert, mapl_return
prefetch_data calls get_connection, get, get_unique_request_id, insert_requesthandle, mapl_return, mapl_verify, receive, send
set_connection calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize