test_compare_negative_string_to_negative_heartbeat – MAPL
test_compare_negative_string_to_negative_heartbeat Subroutine
21 statements
Source File
public subroutine test_compare_negative_string_to_negative_heartbeat()
Arguments
None
Calls
Source Code
   subroutine test_compare_negative_string_to_negative_heartbeat()
      type(ExtDataPointerUpdate) :: ex_str, ex_hb
      integer :: status, rc
      type(ESMF_TimeInterval) :: intv_str, intv_hb
      integer :: expected, actual
      character(len=STRLEN) :: offset_string
      call make_offset_string(TIME_STEP_IN_SECONDS, offset_string, _RC)
      offset_string = '-' // offset_string
      call ex_str%create_from_parameters(UPDATE_TIMESTRING, UPDATE_FREQ_STRING, offset_string, default_time, clock, _RC)
      intv_str = ex_str%get_offset()
      call ESMF_TimeIntervalGet(intv_str, s=expected, _RC)
      call ex_hb%create_from_parameters(UPDATE_TIMESTRING, UPDATE_FREQ_STRING, '-' // HEARTBEAT_STRING, default_time, clock, _RC)
      intv_hb = ex_hb%get_offset()
      call ESMF_TimeIntervalGet(intv_hb, s=actual, _RC)
      @assertEqual(expected, actual, ERR_MSG)
   end subroutine test_compare_negative_string_to_negative_heartbeat
Call graph
test_compare_negative_string_to_negative_heartbeat calls ESMF_TimeIntervalGet, assertequal, create_from_parameters, get_offset, make_offset_string, mapl_verify
create_from_parameters calls mapl_verify, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_return, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
make_offset_string calls mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls mapl_verify, mapl_assert, mapl_return, ESMF_TimeIntervalSet
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message