test_simple_constructor – MAPL
test_simple_constructor Subroutine
13 statements
Source File
public subroutine test_simple_constructor()
Arguments
None
Calls
Contents
Source Code
test_simple_constructor
Source Code
   subroutine test_simple_constructor()
      integer :: status
      type (MAPL_VarSpec), pointer :: specs(:) => null()
      character(:), allocatable :: units
      character(ESMF_MAXSTR) :: found_short_name, found_units
      units='barn'
      call MAPL_VarSpecCreateInList(specs, &
           short_name='fred', &
           units = units, &
           rc=status)
      @assertEqual(0, status)
      @assertEqual(1, size(specs))
      call MAPL_VarSpecGet(specs(1), short_name=found_short_name, units=found_units)
      @assertEqual('fred', trim(found_short_name))
      @assertEqual(units, found_units)
   end subroutine test_simple_constructor
Call graph
test_simple_constructor calls mapl_varspeccreateinlist, assertequal, mapl_varspecget
mapl_varspeccreateinlist calls mapl_varspecgetindex, mapl_return, mapl_verify, mapl_assert
mapl_varspecget calls mapl_varspecgetregular, mapl_varspecgetfieldptr, mapl_varspecgetstateptr, mapl_varspecgetnew, mapl_varspecgetbundleptr
mapl_varspecgetindex calls mapl_varspecgetindexbyname, mapl_varspecgetindexofitem
mapl_return calls mapl_throw_exception, get_error_message
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_varspecgetregular calls mapl_return
mapl_varspecgetfieldptr calls mapl_return
mapl_varspecgetstateptr calls mapl_return
mapl_varspecgetnew calls mapl_return
mapl_varspecgetbundleptr calls mapl_return
mapl_varspecgetindexbyname calls mapl_return
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
mapl_varspecgetindexofitem calls mapl_return
mapl_assert_return_code calls mapl_throw_exception, get_error_message