test_send_terminate – MAPL
test_send_terminate Subroutine
17 statements
Source File
public subroutine test_send_terminate()
Arguments
None
Calls
Source Code
   subroutine test_send_terminate()
      type (SimpleSocket) :: client_connection
      type (MockServerThread), target :: s
      type (SimpleSocket),target :: server_connection
      class(BaseThread), pointer :: visitor
      class(AbstractSocket), pointer :: connection
      class(AbstractMessage), pointer :: msg
      server_connection = SimpleSocket()
      call s%set_connection(server_connection)
      call client_connection%set_visitor(s)
      call client_connection%send(TerminateMessage())
      @assertEqual('handle_Terminate()', s%log)
      visitor =>client_connection%visitor
      connection=>visitor%get_connection()
      msg => connection%receive()
      @assertEqual(TERMINATE_ID,msg%get_type_id())
   end subroutine test_send_terminate
Call graph
test_send_terminate calls assertequal, get_type_id, get_connection, send, set_connection, set_visitor, receive
get_connection calls mapl_assert, mapl_return
send calls get_connection, dispatch, mapl_assert, mapl_return, mapl_verify
set_connection calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize