test_get_month_end – MAPL
test_get_month_end Subroutine
9 statements
Source File
public subroutine test_get_month_end()
Arguments
None
Calls
Source Code
   subroutine test_get_month_end()
      integer, parameter :: year = 2022
      integer, parameter :: leap_year = 2020
      integer :: i
      do i = 1, 12
         @assertEqual(ENDS(i), get_month_end(year, i))
         @assertEqual(ENDS_LEAP(i), get_month_end(leap_year, i))
      end do
   end subroutine test_get_month_end
Call graph
test_get_month_end calls assertequal, get_month_end
get_month_end calls get_month_ends
get_month_ends calls is_leap_year