test_convert_ESMF_Time_to_NetCDF_DateTimeString – MAPL
test_convert_ESMF_Time_to_NetCDF_DateTimeString Subroutine
17 statements
Source File
public subroutine test_convert_ESMF_Time_to_NetCDF_DateTimeString()
Arguments
None
Calls
Contents
Source Code
test_convert_ESMF_Time_to_NetCDF_DateTimeString
Source Code
   subroutine test_convert_ESMF_Time_to_NetCDF_DateTimeString()
      type(ESMF_Time) :: esmf_datetime
      character(len=*), parameter :: expected = '2022-08-26 07:30:37'
      integer, parameter :: yy = 2022
      integer, parameter :: mm = 08
      integer, parameter :: dd  = 26
      integer, parameter :: h  = 07
      integer, parameter :: m  = 30
      integer, parameter :: s  = 37
      character(len=:), allocatable :: actual
      integer :: status, rc
      call ESMF_TimeSet(esmf_datetime, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
      call convert_ESMF_Time_to_NetCDF_DateTimeString(esmf_datetime, actual, _RC)
      @assertEqual(expected, actual, 'Strings don''t match: ' // expected  // '/=' // actual)
   end subroutine test_convert_ESMF_Time_to_NetCDF_DateTimeString
Call graph
test_convert_esmf_time_to_netcdf_datetimestring calls ESMF_TimeSet, assertequal, convert_esmf_time_to_netcdf_datetimestring, mapl_verify
convert_esmf_time_to_netcdf_datetimestring calls mapl_verify, ESMF_TimeGet, mapl_assert, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message