test_arithmetic_mixed – MAPL
test_arithmetic_mixed Subroutine
25 statements
Source File
public subroutine test_arithmetic_mixed(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_arithmetic_mixed(this)
      class(ESMF_TestMethod), intent(inout) :: this
      integer :: status, rc
      real(ESMF_KIND_R4), pointer :: ptr3d(:,:,:), extra_ptr(:,:)
      real(ESMF_KIND_R4), allocatable :: expected_array(:,:,:)
      real(ESMF_KIND_R4) :: rval
      character(len=:), allocatable :: expr
      call ESMF_FieldGet(extra_2d, 0, farrayPtr=extra_ptr, _RC)
      call ESMF_FieldGet(field_3d, 0, farrayPtr=ptr3d, _RC)
      expr = "field_3d*extra_2d"
      rval = 5.0
      ptr3d = rval
      rval = 3.0
      extra_ptr = rval
      allocate(expected_array(3,3,2),_STAT)
      expected_array = 15.0
      call  MAPL_StateEval(state, expr, field_3d, _RC)
      @assertEqual(expected_array, ptr3d)
      _RETURN(_SUCCESS)
   end subroutine test_arithmetic_mixed
Call graph
test_arithmetic_mixed calls assertequal, esmf_fieldget, mapl_return, mapl_stateeval, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_stateeval calls mapl_verify, esmf_stateget, fieldsarebroadcastconformable, mapl_assert, bytecode_dealloc, checksyntax, evalf, parsef
mapl_verify calls mapl_throw_exception