test_get_num_cycles – MAPL
test_get_num_cycles Subroutine
23 statements
Source File
public subroutine test_get_num_cycles(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_get_num_cycles(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DistributedMeter) :: distributed
      type (DistributedInteger) :: distributed_num_cycles
      distributed = DistributedMeter(MpiTimerGauge())
      select case (this%getProcessRank())
      case (0)
         call distributed%add_cycle(1.0_REAL64)
         call distributed%add_cycle(3.0_REAL64)
      case (1)
         call distributed%add_cycle(2.0_REAL64)
      end select
      call distributed%reduce(this%getMpiCommunicator(), 0._REAL64)
      distributed_num_cycles = distributed%get_stats_num_cycles()
      if (this%getProcessRank() == 0) then
         ! Some of these are meaningless/pointless
         @assertEqual(3, distributed_num_cycles%total)
         @assertEqual(1, distributed_num_cycles%min)
         @assertEqual(2, distributed_num_cycles%max)
         @assertEqual(1, distributed_num_cycles%min_pe)
         @assertEqual(0, distributed_num_cycles%max_pe)
         @assertEqual(2, distributed_num_cycles%num_pes)
      end if
   end subroutine test_get_num_cycles
Call graph
test_get_num_cycles calls assertequal, getmpicommunicator, getprocessrank, reduce, add_cycle, get_stats_num_cycles
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles
reduce_mpi calls mpi_comm_rank, mpi_reduce, get_max_cycle, get_min_cycle, get_num_cycles, get_sum_square_deviation, get_total, mapl_verify
mapl_verify calls mapl_throw_exception