test_get_attribute_string – MAPL
test_get_attribute_string Subroutine
18 statements
Source File
public subroutine test_get_attribute_string()
Arguments
None
Calls
Source Code
   subroutine test_get_attribute_string()
      type (Variable) :: var
      type (Attribute), pointer :: attr
      class (*), pointer :: value
      !integer :: EMPTY(0)
      var = Variable(type=pFIO_INT32, dimensions='x')
      call var%add_attribute('pet_name', 'kitty')
      attr => var%get_attribute('pet_name')
      @assertEqual(empty, attr%get_shape())
      value => attr%get_value()
      select type (value)
      type is (character(len=*))
         @assertEqual('kitty', value)
      type is (StringWrap)
         @assertEqual('kitty', value%value)
      class default
         @assertTrue(1==2)
      end select
   end subroutine test_get_attribute_string
Call graph
test_get_attribute_string calls assertequal, asserttrue, add_attribute, get_attribute, get_shape, get_value
get_attribute calls mapl_assert, m_at, mapl_return
get_shape calls mapl_return
get_value calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize