test_is_valid_netcdf_datetime_string – MAPL
test_is_valid_netcdf_datetime_string Subroutine
13 statements
Source File
public subroutine test_is_valid_netcdf_datetime_string()
Arguments
None
Calls
Contents
Source Code
test_is_valid_netcdf_datetime_string
Source Code
   subroutine test_is_valid_netcdf_datetime_string()
      character(len=:), allocatable :: string
!      string = ''
!      @assertTrue(is_valid_netcdf_datetime_string(string), string // ' is not a valid NetCDF datetime string.')
      string = '1970-01-01 23:59:59'
      @assertTrue(is_valid_netcdf_datetime_string(string), string // ' is not a valid NetCDF datetime string.')
      string = '1970-01-01  23:59:59'
      @assertFalse(is_valid_netcdf_datetime_string(string), string // ' is not a valid NetCDF datetime string.')
      string = '1970:01-01 23:59:59'
      @assertFalse(is_valid_netcdf_datetime_string(string), string // ' is not a valid NetCDF datetime string.')
      string = '1970-01-01 23-59:59'
      @assertFalse(is_valid_netcdf_datetime_string(string), string // ' is not a valid NetCDF datetime string.')
      string = '1970-01-01T23:59:59'
      @assertFalse(is_valid_netcdf_datetime_string(string), string // ' is not a valid NetCDF datetime string.')
   end subroutine test_is_valid_netcdf_datetime_string
Call graph
test_is_valid_netcdf_datetime_string calls assertfalse, asserttrue, is_valid_netcdf_datetime_string