test_datetime – MAPL
test_datetime Subroutine
9 statements
Source File
public subroutine test_datetime()
Arguments
None
Calls
Contents
Source Code
test_datetime
Source Code
   subroutine test_datetime()
      integer :: datetime(2)
      ! Simple test
      datetime = [20000101,120000]
      @assert_that(is_valid_datetime(datetime), is(true()))
      ! Bad date
      datetime = [20001301,120000]
      @assert_that(is_valid_datetime(datetime), is(false()))
      ! Bad time
      datetime = [20000101,250000]
      @assert_that(is_valid_datetime(datetime), is(false()))
   end subroutine test_datetime
Call graph
test_datetime calls assert_that, is_valid_datetime, false, true
is_valid_datetime calls is_valid_date, is_valid_time