test_handle_AddExtCollection – MAPL
test_handle_AddExtCollection Subroutine
25 statements
Source File
public subroutine test_handle_AddExtCollection()
Arguments
None
Calls
Source Code
   subroutine test_handle_AddExtCollection()
      type (ServerThread) :: s
      character(len=:), allocatable :: expected
      type (MockSocketLog), target :: log
      type (MockSocket) :: client_socket
      type (MockServer) :: mock_server
      integer :: i
      client_socket = MockSocket(log)
      call client_socket%add_message(AddExtCollectionMessage('foo'))
      call client_socket%add_message(AddExtCollectionMessage('bar'))
      call client_socket%add_message(TerminateMessage())
      mock_server = MockServer()
      call s%init(client_socket, mock_server)
      call s%set_rank(1)
      do i = 1,3
        call s%run()
      enddo
      expected = ""
      expected = expected // "receive<AddExtCollection('foo')>"
      expected = expected // " :: send<Id(001)>"
      expected = expected // " :: receive<AddExtCollection('bar')>"
      expected = expected // " :: send<Id(002)>"
      expected = expected // " :: receive<Terminate>"
      @assertEqual(expected, log%log)
   end subroutine test_handle_AddExtCollection
Call graph
test_handle_addextcollection calls assertequal, add_message, init, run, set_rank
add_message calls v_push_back
init calls mapl_return, mapl_verify, set_connection
run calls start, dispatch, get_connection, mapl_return, mapl_verify, receive
dispatch calls mapl_return, mapl_verify, handle
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_connection calls mapl_return
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
v_grow_to calls v_capacity, v_set_capacity