test_mapl_sort – MAPL
test_mapl_sort Subroutine
22 statements
Source File
public subroutine test_mapl_sort()
Arguments
None
Calls
Contents
Source Code
test_mapl_sort
Source Code
   subroutine test_mapl_sort
      implicit none
      integer(kind=INT64) :: a(5), c(5)
      integer(kind=INT32) :: a4(5)
      integer(kind=INT32) ::  b1(5,3), b2(3,5)
      integer(kind=INT32) ::  d1(5,3)
      integer :: i, j
      a = [5,3,8,6,-7]
      do j=1,3
         b1(:,j) = a
         b2(j,:) = a
      enddo
      a4 = a
      C=A
      d1=b1
      call MAPL_SORT(C,d1,dim=1)
      do j=1,3
         do i = 2, size(d1,dim=1)
            @assertTrue(d1(i-1,j) <= d1(i,j))
         end do
      end do
   end subroutine test_mapl_sort
Call graph
test_mapl_sort calls mapl_sort, asserttrue
mapl_sort calls sort2ss, sort2ld, sort2lr, sort2ls, sort2sr, sort2as, sort1ss, sort2al, sort2sd, sort1lr, sort1sd, sort1ls, sort1sr, sort1ld
sort2ss calls mapl_assert, qsorts
sort2ld calls mapl_assert, qsortl
sort2lr calls mapl_assert, qsortl
sort2ls calls mapl_assert, qsortl
sort2sr calls mapl_assert, qsorts
sort2as calls mapl_assert, qsorts
sort1ss calls qsorts
sort2al calls mapl_assert, qsortl
sort2sd calls mapl_assert, qsorts
sort1lr calls qsortl
sort1sd calls qsorts
sort1ls calls qsortl
sort1sr calls qsorts
sort1ld calls qsortl
mapl_assert calls mapl_assert_condition, mapl_assert_return_code