test_FieldsAreSameTypeKind – MAPL
test_FieldsAreSameTypeKind Subroutine
27 statements
Source File
public subroutine test_FieldsAreSameTypeKind(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldsAreSameTypeKind(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x, y
      integer :: status, rc
      logical :: are_same_typekind
      x = XR4
      y = YR4
      are_same_typekind = .FALSE.
      are_same_typekind = FieldsAreSameTypeKind(x, y, _RC)
      @assertTrue(are_same_typekind)
      x = XR8
      y = YR8
      are_same_typekind = .FALSE.
      are_same_typekind = FieldsAreSameTypeKind(x, y, _RC)
      @assertTrue(are_same_typekind)
      y = YR4
      are_same_typekind = .TRUE.
      are_same_typekind = FieldsAreSameTypeKind(x, y, _RC)
      @assertFalse(are_same_typekind)
      are_same_typekind = .TRUE.
      are_same_typekind = FieldsAreSameTypeKind(y, x, _RC)
      @assertFalse(are_same_typekind)
   end subroutine test_FieldsAreSameTypeKind
Call graph
test_fieldsaresametypekind calls assertfalse, asserttrue, fieldsaresametypekind, mapl_verify
fieldsaresametypekind calls are_same_type_kind
mapl_verify calls mapl_throw_exception
are_same_type_kind calls mapl_verify, esmf_fieldget, mapl_return
mapl_throw_exception calls initialize
mapl_return calls mapl_throw_exception, get_error_message