test_stop_wrong_meter – MAPL
test_stop_wrong_meter Subroutine
12 statements
Source File
public subroutine test_stop_wrong_meter()
Arguments
None
Calls
Source Code
   subroutine test_stop_wrong_meter()
      type (TimeProfiler), target :: prof
      integer :: status
      prof = TimeProfiler('top')
      call prof%start()
      call prof%start('timer_1')
      call prof%start('timer_2')
      @assertEqual(0, prof%get_status())
      call prof%stop('timer_1', rc=status) ! not the current timer
!C$      @assertEqual(INCORRECTLY_NESTED_METERS, prof%get_status())
      @assertExceptionRaised('Timer <timer_1> does not match start timer <timer_2>')
      call prof%finalize()
   end subroutine test_stop_wrong_meter
Call graph
test_stop_wrong_meter calls assertequal, assertexceptionraised, start, finalize, get_status
finalize calls finalize, get_meter, vector_pop_back, mpi_op_free, mpi_type_free, mapl_verify
start_self calls mapl_assert, start, get_name, mapl_return
vector_pop_back calls vector_downsize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception