test_serialize_buffer_length_real_1d – MAPL
test_serialize_buffer_length_real_1d Subroutine
6 statements
Source File
public subroutine test_serialize_buffer_length_real_1d()
Arguments
None
Calls
Contents
Source Code
test_serialize_buffer_length_real_1d
Source Code
   subroutine test_serialize_buffer_length_real_1d()
      real :: empty(0)
      @assertEqual(1, serialize_buffer_length(empty))
      @assertEqual(2, serialize_buffer_length([1.0]))
      @assertEqual(5, serialize_buffer_length([1.0,2.0,3.0,4.0]))
   end subroutine test_serialize_buffer_length_real_1d
Call graph
test_serialize_buffer_length_real_1d calls assertequal, serialize_buffer_length
serialize_buffer_length calls serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_string, serialize_buffer_length_int64_1d, serialize_buffer_length_int32_1d, serialize_buffer_length_int32_0d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d
serialize_buffer_length_logical_0d calls word_size, mapl_return
serialize_buffer_length_logical_1d calls word_size, mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_string calls mapl_return
serialize_buffer_length_int64_1d calls word_size, mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_real32_0d calls word_size, mapl_return
serialize_buffer_length_real32_1d calls word_size, mapl_return
serialize_buffer_length_real64_0d calls word_size, mapl_return
serialize_buffer_length_real64_1d calls word_size, mapl_return
word_size calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception