test_are_not_convertible – MAPL
test_are_not_convertible Subroutine
20 statements
Source File
public subroutine test_are_not_convertible()
Arguments
None
Calls
Source Code
   subroutine test_are_not_convertible()
      type(UDUnit) :: unit1
      type(UDUnit) :: unit2
      integer(ut_status) :: status
      logical :: convertible
      call initialize_udunits_system(rc=status)
      @assertEqual(UT_SUCCESS, status, 'Failed to initialize')
      unit1 = UDUnit(KM)
      unit2 = UDUnit(S)
      convertible = are_convertible(unit1, unit2, rc=status)
      @assertFalse(convertible, 'Units are not convertible.')
      if(.not. convertible) then
         @assertFalse(status == UT_BAD_ARG, 'One of the units is null.')
         @assertFalse(status == UT_NOT_SAME_SYSTEM, 'Units belong to different systems.')
         @assertTrue(status == UT_SUCCESS, 'Units are not convertible.')
      end if
      call unit1%free()
      call unit2%free()
      call finalize_udunits_system()
   end subroutine test_are_not_convertible
Call graph
test_are_not_convertible calls assertequal, assertfalse, asserttrue, finalize_udunits_system, initialize_udunits_system, are_convertible
are_convertible calls are_convertible_str, are_convertible_udunit
are_convertible_str calls are_convertible_udunit
are_convertible_udunit calls ut_are_convertible, ut_get_status, get_cptr, success