test_is_empty – MAPL
test_is_empty Subroutine
18 statements
Source File
public subroutine test_is_empty()
Arguments
None
Calls
Source Code
   subroutine test_is_empty()
      type (UnlimitedEntity) :: a
      logical :: is
      ! not initialized
      is = a%is_empty()
      @assertTrue(is)
      ! empty string
      a = UnlimitedEntity('')
      is = a%is_empty()
      @assertTrue(is)
      a = UnlimitedEntity('no')
      is = a%is_empty()
      @assertFalse(is)
      a = UnlimitedEntity(0)
      is = a%is_empty()
      @assertFalse(is)
      a = UnlimitedEntity([0])
      is = a%is_empty()
      @assertFalse(is)
   end subroutine test_is_empty
Call graph
test_is_empty calls assertfalse, asserttrue, is_empty
is_empty calls get_value, mapl_return
get_value calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize