test_get_attribute_real_double – MAPL
test_get_attribute_real_double Subroutine
16 statements
Source File
public subroutine test_get_attribute_real_double()
Arguments
None
Calls
Source Code
   subroutine test_get_attribute_real_double()
      type (Variable) :: var
      type (Attribute), pointer :: attr
      class (*), pointer :: values(:)
      var = Variable(type=pFIO_INT32, dimensions='x')
      call var%add_attribute('pet_size', [15._REAL64,24._REAL64])
      attr => var%get_attribute('pet_size')
      @assertEqual([2], attr%get_shape())
      values => attr%get_values()
      select type (values)
      type is (real(REAL64))
         @assertEqual([15,24], values)
      class default
         @assertTrue(1==2)
      end select
   end subroutine test_get_attribute_real_double
Call graph
test_get_attribute_real_double calls assertequal, asserttrue, add_attribute, get_attribute, get_shape, get_values
get_attribute calls mapl_assert, m_at, mapl_return
get_shape calls mapl_return
get_values calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize