test_parse_terminate – MAPL
test_parse_terminate Subroutine
10 statements
Source File
public subroutine test_parse_terminate()
Arguments
None
Calls
Source Code
   subroutine test_parse_terminate()
      type (ProtocolParser) :: parser
      type (TerminateMessage) :: expected_message
      integer, allocatable :: buffer(:)
      class (AbstractMessage), allocatable :: found_message
      parser = ProtocolParser()
      buffer = parser%encode(expected_message)
      allocate(found_message, source=parser%decode(buffer))
      @assertTrue(same_type_as(expected_message, found_message))
   end subroutine test_parse_terminate
Call graph
test_parse_terminate calls asserttrue, decode, encode
decode calls deserialize, m_at
encode calls get_length, get_type_id, serialize
m_at calls m_find
m_find calls s_find