test_merge_meta – MAPL
test_merge_meta Subroutine
22 statements
Source File
public subroutine test_merge_meta()
Arguments
None
Calls
Source Code
   subroutine test_merge_meta()
      type (FileMetadata) :: cf1, cf2,cf3
      type (Variable) :: v1, v2, v3
      call cf1%add_dimension('x', 10)
      call cf1%add_dimension('y', 20)
      call cf1%add_dimension('z', 30)
      v1 = Variable(type=pFIO_INT32, dimensions='x')
      call v3%add_attribute('flag', .true.)
      call cf1%add_variable('v1', v1)
      call cf2%merge(cf1)
      @assertTrue(cf2 == cf1)
      ! merge again, should be the same
      call cf2%merge(cf1)
      @assertTrue(cf2 == cf1)
      call cf3%add_dimension('x', 10)
      call cf3%add_dimension('a', 3)
      v3 = Variable(type=pFIO_REAL64, dimensions='x,a')
      call cf3%add_variable('v3', v3)
      call cf2%merge(cf3)
      call cf1%add_dimension('a',3)
      call cf1%add_variable('v3', v3)
      @assertTrue(cf2 == cf1)
   end subroutine test_merge_meta
Call graph
test_merge_meta calls asserttrue, add_attribute, add_dimension, add_variable
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
get_value calls mapl_return
m_insert_pair calls s_insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize