test_create_from_parameters_string_negative – MAPL
test_create_from_parameters_string_negative Subroutine
18 statements
Source File
public subroutine test_create_from_parameters_string_negative()
Arguments
None
Calls
Source Code
   subroutine test_create_from_parameters_string_negative()
      type(ExtDataPointerUpdate) :: ex
      integer :: status, rc
      character(len=STRLEN) :: offset_string
      integer, parameter :: OFFSET_IN_SECONDS = 300
      integer :: expected, actual
      type(ESMF_TimeInterval) :: interval
      call make_offset_string(OFFSET_IN_SECONDS, offset_string, _RC)
      offset_string = '-' // offset_string
      expected = -OFFSET_IN_SECONDS
      call ex%create_from_parameters(UPDATE_TIMESTRING, UPDATE_FREQ_STRING, offset_string, default_time, clock, _RC)
      interval = ex%get_offset()
      call ESMF_TimeIntervalGet(interval, s=actual, _RC)
      @assertEqual(expected, actual, ERR_MSG)
   end subroutine test_create_from_parameters_string_negative
Call graph
test_create_from_parameters_string_negative calls ESMF_TimeIntervalGet, assertequal, create_from_parameters, get_offset, make_offset_string, mapl_verify
create_from_parameters calls mapl_verify, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_return, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
make_offset_string calls mapl_verify, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls mapl_verify, mapl_assert, mapl_return, ESMF_TimeIntervalSet
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message