test_parse_date – MAPL
test_parse_date Subroutine
13 statements
Source File
public subroutine test_parse_date()
Arguments
None
Calls
Contents
Source Code
test_parse_date
Source Code
   subroutine test_parse_date()
      type(date_fields) :: date
      date = parse_date('2022-07-07')
      @assertTrue(date%is_valid_)
      @assertEqual(2022, date%year_)
      @assertEqual(7, date%month_)
      @assertEqual(7, date%day_)
      date = parse_date('20220707')
      @assertTrue(date%is_valid_)
      @assertEqual(2022, date%year_)
      @assertEqual(7, date%month_)
      @assertEqual(7, date%day_)
   end subroutine test_parse_date
Call graph
test_parse_date calls parse_date, assertequal, asserttrue
parse_date calls undelimit, is_valid_date, read_whole_number
is_valid_date calls is_valid_year, is_valid_month, get_month_end, is_between
read_whole_number calls read_whole_number_indexed
is_valid_year calls is_between
is_valid_month calls is_between
get_month_end calls get_month_ends
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string