test_addExtCollection_send_message – MAPL
test_addExtCollection_send_message Subroutine
13 statements
Source File
public subroutine test_addExtCollection_send_message()
Arguments
None
Calls
Source Code
   subroutine test_addExtCollection_send_message()
      type (MockClientThread) :: c
      class (AbstractSocket), pointer :: connection
      integer :: handle_foo
      type (MockSocketLog), target :: log
      call c%set_connection(MockSocket(log))
      connection => c%get_connection()
      handle_foo = c%add_ext_collection(template='foo')
      select type (connection)
      type is (MockSocket)
         @assertEqual("send<AddExtCollection('foo')>", log%log)
      end select
   end subroutine test_addExtCollection_send_message
Call graph
test_addextcollection_send_message calls assertequal, add_ext_collection, get_connection, set_connection
add_ext_collection calls get_connection, mapl_assert, mapl_return, mapl_verify, receive, send
get_connection calls mapl_assert, mapl_return
set_connection calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize