test_convert_ISO8601_to_integer_date – MAPL
test_convert_ISO8601_to_integer_date Subroutine
11 statements
Source File
public subroutine test_convert_ISO8601_to_integer_date()
Arguments
None
Calls
Contents
Source Code
test_convert_ISO8601_to_integer_date
Source Code
   subroutine test_convert_ISO8601_to_integer_date()
      character(len=8) :: date_string
      integer :: actual
      integer :: expected
      integer :: status
      date_string = '20220813'
      expected = 20220813
      actual = convert_ISO8601_to_integer_date(date_string, rc=status)
      @assertEqual(SUCCESS, status)
      @assertEqual(expected, actual)
   end subroutine test_convert_ISO8601_to_integer_date
Call graph
test_convert_iso8601_to_integer_date calls assertequal, convert_iso8601_to_integer_date
convert_iso8601_to_integer_date calls iso8601date, get_day, get_month, get_year, mapl_return, mapl_verify
iso8601date calls construct_iso8601date
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
construct_iso8601date calls mapl_assert, parse_date
get_error_message calls at
mapl_throw_exception calls initialize