test_simple – MAPL
test_simple Subroutine
30 statements
Source File
public subroutine test_simple()
Arguments
None
Calls
Source Code
   subroutine test_simple()
      type(MeterNode), target :: node
      class(AbstractMeterNode), pointer :: subnode
      class(AbstractMeter), pointer :: t
      type(ExclusiveColumn) :: c
      type(UnlimitedVector) :: v
      integer :: i
      integer :: expected(3)
      class(*), allocatable :: q
      node = MeterNode('top', AdvancedMeter(MpiTimerGauge()))
      t => node%get_meter()
      call t%add_cycle(10.0d0)
      call node%add_child('a', AdvancedMeter(MpiTimerGauge()))
      subnode => node%get_child('a')
      t => subnode%get_meter()
      call t%add_cycle(1.0d0)
      call node%add_child('b', AdvancedMeter(MpiTimerGauge()))
      subnode => node%get_child('b')
      t => subnode%get_meter()
      call t%add_cycle(2.0d0)
      v = c%get_rows(node)
      expected = [7,1,2]
      do i = 1, 3
         q = v%at(i)
         select type (q)
         type is (integer)
            @assertEqual(expected(i), q)
         end select
      end do
   end subroutine test_simple
Call graph
test_simple calls add_cycle, assertequal, at, add_child, get_child, get_meter, get_rows
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_rows calls begin, get, get_row, next, push_back
find_child calls at
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity