test_start_one – MAPL
test_start_one Subroutine
9 statements
Source File
public subroutine test_start_one()
Arguments
None
Calls
Source Code
   subroutine test_start_one()
      type (TimeProfiler), target :: prof
      prof = TimeProfiler('top')
      call Prof%start()
      call prof%start('timer_1')
      call prof%stop('timer_1')
      call prof%finalize()
      @assertEqual(2, prof%get_num_meters())
   end subroutine test_start_one
Call graph
test_start_one calls assertequal, start, finalize, get_num_meters
finalize calls finalize, get_meter, vector_pop_back, mpi_op_free, mpi_type_free, mapl_verify
get_num_meters calls get_num_nodes
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
start_self calls mapl_assert, start, get_name, mapl_return
vector_pop_back calls vector_downsize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception