test_accumulate_multi – MAPL
test_accumulate_multi Subroutine
16 statements
Source File
public subroutine test_accumulate_multi()
Arguments
None
Calls
Source Code
   subroutine test_accumulate_multi()
      type(TimeProfiler), target :: main, lap
      main = TimeProfiler('main')
      call main%start()
      lap = TimeProfiler('lap')
      call lap%start()
      call lap%start('A')
      call lap%stop('A')
      call lap%finalize()
      call main%accumulate(lap)
      call lap%reset()
      call lap%start('A')
      call lap%stop('A')
      call lap%finalize()
      call main%accumulate(lap)
   end subroutine test_accumulate_multi
Call graph
test_accumulate_multi calls start, accumulate, finalize, reset
accumulate calls accumulate, get_root_node, vector_back
finalize calls finalize, get_meter, vector_pop_back, mpi_op_free, mpi_type_free, mapl_verify
reset calls begin, get_meter, next, start, get_root_node, reset
start_self calls start, mapl_assert, get_name, mapl_return
vector_pop_back calls vector_downsize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception