test_add_spec_grows_container – MAPL
test_add_spec_grows_container Subroutine
17 statements
Source File
public subroutine test_add_spec_grows_container()
Arguments
None
Calls
Contents
Source Code
test_add_spec_grows_container
Source Code
   subroutine test_add_spec_grows_container()
      integer :: status
      type (MAPL_VarSpec), pointer :: specs(:) => null()
      character(:), allocatable :: units
      integer :: idx
      units='barn'
      call MAPL_VarSpecCreateInList(specs, &
           short_name='fred', &
           units = units, &
           rc=status)
      units='barn'
      call MAPL_VarSpecCreateInList(specs, &
           short_name='barney', &
           units = units, &
           rc=status)
      @assertEqual(2, size(specs))
      idx = MAPL_VarSpecGetIndex(specs, name='fred', rc=status)
      @assertEqual(0, status)
      @assertEqual(1, idx)
      idx = MAPL_VarSpecGetIndex(specs, name='barney', rc=status)
      @assertEqual(0, status)
      @assertEqual(2, idx)
   end subroutine test_add_spec_grows_container
Call graph
test_add_spec_grows_container calls mapl_varspeccreateinlist, mapl_varspecgetindex, assertequal
mapl_varspeccreateinlist calls mapl_varspecgetindex, mapl_verify, mapl_assert, mapl_return
mapl_varspecgetindex calls mapl_varspecgetindexofitem, mapl_varspecgetindexbyname
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_return_code, mapl_assert_condition
mapl_varspecgetindexofitem calls mapl_return
mapl_varspecgetindexbyname calls mapl_return
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
mapl_assert_return_code calls mapl_throw_exception, get_error_message
mapl_assert_condition calls mapl_throw_exception