test_get_timezone_offset_field – MAPL
test_get_timezone_offset_field Subroutine
7 statements
Source File
public subroutine test_get_timezone_offset_field()
Arguments
None
Calls
Contents
Source Code
test_get_timezone_offset_field
Source Code
   subroutine test_get_timezone_offset_field
      type(time_fields) :: tf
      integer :: h = 13, m = 43, s = 37, ms = 100, tzo = 0
      tf = time_fields(h, m, s, ms, tzo)
      @assertTrue(tf % is_valid(), 'Failed to initialize tf')
      @assertEqual(tzo, tf % timezone_offset())
   end subroutine test_get_timezone_offset_field
Call graph
test_get_timezone_offset_field calls assertequal, asserttrue, time_fields
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit