test_parse_time – MAPL
test_parse_time Subroutine
17 statements
Source File
public subroutine test_parse_time()
Arguments
None
Calls
Contents
Source Code
test_parse_time
Source Code
   subroutine test_parse_time()
      type(time_fields) :: time
      time = parse_time('T17:41:07.513Z')
      @assertTrue(time%is_valid_)
      @assertEqual(17, time%hour_)
      @assertEqual(41, time%minute_)
      @assertEqual(7, time%second_)
      @assertEqual(513, time%millisecond_)
      @assertEqual(0, time%timezone_offset_)
      time = parse_time('T174107.513Z')
      @assertTrue(time%is_valid_)
      @assertEqual(17, time%hour_)
      @assertEqual(41, time%minute_)
      @assertEqual(7, time%second_)
      @assertEqual(513, time%millisecond_)
      @assertEqual(0, time%timezone_offset_)
!      time = parse_time('T174107.513+0000')
!      @assertTrue(time%is_valid_)
!      @assertEqual(17, time%hour_)
!      @assertEqual(41, time%minute_)
!      @assertEqual(7, time%second_)
!      @assertEqual(513, time%millisecond_)
!      @assertEqual(0, time%timezone_offset_)
!      time = parse_time('T174107.513-0500')
!      @assertTrue(time%is_valid_)
!      @assertEqual(17, time%hour_)
!      @assertEqual(41, time%minute_)
!      @assertEqual(7, time%second_)
!      @assertEqual(513, time%millisecond_)
!      @assertEqual(-300, time%timezone_offset_)
   end subroutine test_parse_time
Call graph
test_parse_time calls assertequal, asserttrue, parse_time
parse_time calls time_fields, is_valid_time, is_whole_number, parse_timezone_offset, read_whole_number, undelimit
time_fields calls construct_time_fields
is_valid_time calls is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset
parse_timezone_offset calls is_whole_number, read_whole_number
read_whole_number calls read_whole_number_indexed
is_valid_hour calls is_between
is_valid_millisecond calls is_between
is_valid_minute calls is_between
is_valid_second calls is_between
read_whole_number_indexed calls is_whole_number, get_integer_digit_from_string