test_trivial – MAPL
test_trivial Subroutine
15 statements
Source File
public subroutine test_trivial(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_trivial(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DistributedMeter) :: distributed
      type (DistributedReal64) :: distributed_total
      distributed = DistributedMeter(MpiTimerGauge())
      call distributed%add_cycle(1.0_REAL64)
      call distributed%reduce(this%getMpiCommunicator(), 0._REAL64)
      distributed_total = distributed%get_stats_total()
      @assertEqual(1.0, distributed_total%total)
      @assertEqual(1.0, distributed_total%min)
      @assertEqual(1.0, distributed_total%max)
      @assertEqual(0, distributed_total%min_pe)
      @assertEqual(0, distributed_total%max_pe)
      @assertEqual(1, distributed_total%num_pes)
   end subroutine test_trivial
Call graph
test_trivial calls assertequal, getmpicommunicator, reduce, add_cycle, get_stats_total
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles
reduce_mpi calls mpi_comm_rank, mpi_reduce, get_max_cycle, get_min_cycle, get_num_cycles, get_sum_square_deviation, get_total, mapl_verify
mapl_verify calls mapl_throw_exception