test_is_active – MAPL
test_is_active Subroutine
9 statements
Source File
public subroutine test_is_active()
Arguments
None
Calls
Source Code
   subroutine test_is_active()
      type (AdvancedMeter) :: t
      t = AdvancedMeter(MpiTimerGauge())
      ! Initial state is
      @assertFalse(t%is_active())
      call t%start()
      @assertTrue(t%is_active())
      call t%stop()
      @assertFalse(t%is_active())
   end subroutine test_is_active
Call graph
test_is_active calls assertfalse, asserttrue, is_active, start
start calls get_measurement