test_extract_CF_Time_unit – MAPL
test_extract_CF_Time_unit Subroutine
17 statements
Source File
public subroutine test_extract_CF_Time_unit()
Arguments
None
Calls
Source Code
   subroutine test_extract_CF_Time_unit()
      type(CF_Time_Integer) :: cfti
      integer :: duration = 0
      character(len=*), parameter :: time_unit = 'seconds'
      character(len=*), parameter :: base_datetime = '1999-12-31 23:29:59'
      character(len=*), parameter :: units = time_unit // ' since ' // base_datetime
      character(len=MAX_CHARACTER_LENGTH) :: actual
      integer :: status
      call extract_CF_Time_unit(units, actual, rc = status)
      @assertEqual(SUCCESS, status, 'Failed to extract time unit from units')
      @assertEqual(time_unit, actual, 'Actual time unit does not match expected time unit.')
      cfti = CF_Time_Integer(duration, units)
      @assertTrue(cfti % is_valid, 'Invalid CF_Time_Integer')
      call extract_CF_Time_unit(cfti, actual, rc = status)
      @assertEqual(SUCCESS, status, 'Failed to extract time unit from CF_Time')
      @assertEqual(time_unit, actual, 'Actual time unit does not match expected time unit.')
   end subroutine test_extract_CF_Time_unit
Call graph
test_extract_cf_time_unit calls assertequal, asserttrue, extract_cf_time_unit
extract_cf_time_unit calls extract_cf_time_unit_cf_time, extract_cf_time_unit_units
extract_cf_time_unit_cf_time calls mapl_return
extract_cf_time_unit_units calls extract_cf_time_unit, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception