test_publish – MAPL
test_publish Subroutine
11 statements
Source File
public subroutine test_publish(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_publish(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DirectoryService) :: ds
      integer :: comm
      type (MockServer) :: mock_server
      comm = this%getMpiCommunicator()
      ds = DirectoryService(comm)
      mock_server = MockServer(comm)
      call ds%publish(PortInfo('service', mock_server), mock_server)
      call ds%free_directory_resources()
   end subroutine test_publish
Call graph
test_publish calls getmpicommunicator, free_directory_resources, publish
free_directory_resources calls mpi_barrier, mpi_comm_free, mpi_free_mem, mpi_win_free, free_mpi_resources, mapl_return
publish calls mapl_assert, mpi_comm_rank, acquire, get_communicator, get_directory, mapl_return, put_directory, release
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
acquire calls mpi_get, mpi_put, mpi_recv, mpi_win_lock, mpi_win_unlock
free_mpi_resources calls mpi_comm_free, mpi_free_mem, mpi_win_free, mpi_type_free
get_directory calls mpi_get, mpi_win_lock, mpi_win_unlock, sizeof_directory
mapl_return calls get_error_message, mapl_throw_exception
put_directory calls mpi_put, mpi_win_lock, mpi_win_unlock, sizeof_directory
release calls mpi_get, mpi_put, mpi_send, mpi_win_lock, mpi_win_unlock
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize