test_get_attributes – MAPL
test_get_attributes Subroutine
8 statements
Source File
public subroutine test_get_attributes()
Arguments
None
Calls
Source Code
   subroutine test_get_attributes()
      type (FileMetadata), target :: cf
      type (StringAttributeMap), pointer :: attributes
      call cf%add_attribute('x', 10)
      call cf%add_attribute('y', 11)
      attributes => cf%get_attributes()
      @assertEqual(2, attributes%size())
   end subroutine test_get_attributes
Call graph
test_get_attributes calls assertequal, add_attribute, get_attributes
get_attributes calls get_attributes, mapl_return
add_attribute_0d calls mapl_return, add_attribute
add_attribute_1d calls mapl_return, add_attribute
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize