test_get_attribute_scalar_int – MAPL
test_get_attribute_scalar_int Subroutine
16 statements
Source File
public subroutine test_get_attribute_scalar_int()
Arguments
None
Calls
Source Code
   subroutine test_get_attribute_scalar_int()
      type (Variable) :: var
      type (Attribute), pointer :: attr
      class (*), pointer :: value
      var = Variable(type=pFIO_INT32, dimensions='x')
      call var%add_attribute('pet_age', 15)
      attr => var%get_attribute('pet_age')
      @assertEqual(EMPTY, attr%get_shape())
      value => attr%get_value()
      select type (value)
      type is (integer(INT32))
         @assertEqual(15, value)
      class default
         @assertTrue(1==2)
      end select
   end subroutine test_get_attribute_scalar_int
Call graph
test_get_attribute_scalar_int calls assertequal, asserttrue, add_attribute, get_attribute, get_shape, get_value
get_attribute calls mapl_assert, m_at, mapl_return
get_shape calls mapl_return
get_value calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
m_at calls m_find
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
m_find calls s_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize