test_prefetch_data – MAPL
test_prefetch_data Subroutine
25 statements
Source File
public subroutine test_prefetch_data()
Arguments
None
Calls
Source Code
   subroutine test_prefetch_data()
      type (MockClientThread) :: c
      class (AbstractSocket), pointer :: connection
      integer :: collection_id
      integer :: request_id
      real(kind=REAL32), target :: q
      character(len=:), allocatable :: expected_log
      type (MockSocketLog), target :: log
      call c%set_connection(MockSocket(log))
      connection => c%get_connection()
      select type (connection)
      type is (MockSocket)
         call connection%add_message(IdMessage(1))
         call connection%add_message(IdMessage(2))
         connection%q1 = q
      end select
      collection_id = c%add_ext_collection(template='foo')
      request_id = c%prefetch_data(collection_id, 'foo', 'q', ArrayReference(q))
      expected_log = "send<AddExtCollection('foo')>"
      expected_log = expected_log // " :: send<PrefetchData('q')> :: get()"
      select type (connection)
      type is (MockSocket)
         @assertEqual(expected_log, log%log)
      end select
   end subroutine test_prefetch_data
Call graph
test_prefetch_data calls add_message, assertequal, add_ext_collection, get_connection, prefetch_data, set_connection
add_ext_collection calls get_connection, mapl_assert, mapl_return, mapl_verify, receive, send
get_connection calls mapl_assert, mapl_return
prefetch_data calls get_connection, get, get_unique_request_id, insert_requesthandle, mapl_return, mapl_verify, receive, send
set_connection calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
insert_requesthandle calls mapl_return, insert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize