test_equal_diff_attributes – MAPL
test_equal_diff_attributes Subroutine
18 statements
Source File
public subroutine test_equal_diff_attributes()
Arguments
None
Calls
Source Code
   subroutine test_equal_diff_attributes()
      type (Variable)  :: v1, v2
      type (UnlimitedEntity) :: const
      ! no init equal?
      @assertTrue(v1 == v2)
      const = UnlimitedEntity([0,1])
      v1 = Variable(type=pFIO_INT32, dimensions='x', const_value = const)
      v2 = v1
      call v1%add_attribute('attr1', 1)
      @assertFalse(v1 == v2)
      ! guard against missing extra items in v2
      @assertFalse(v2 == v1)
      call v1%add_attribute('attr2', 2.)
      call v2%add_attribute('attr2', 2.)
      call v2%add_attribute('attr1', 1)
      @assertTrue(v1 == v2)
      call v1%add_attribute('attr3', 'cat')
      call v2%add_attribute('attr3', 'dog')
      @assertFalse(v1 == v2)
   end subroutine test_equal_diff_attributes
Call graph
test_equal_diff_attributes calls assertfalse, asserttrue, add_attribute
add_attribute_1d calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception