test_complex – MAPL
test_complex Subroutine
17 statements
Source File
public subroutine test_complex()
Arguments
None
Calls
Source Code
   subroutine test_complex()
      type (DirPath) :: path
      character(len=:), allocatable :: full_name
      integer :: status
      call path%append('dir1')
      call path%append('dir1/dir3')
      call path%append('dir2')
      full_name = path%find('exist.dat', rc=status)
      @assertEqual(0, status)
      @assertEqual('dir1/exist.dat', full_name)
      full_name = path%find('exist2.dat', rc=status)
      @assertEqual(0, status)
      @assertEqual('dir2/exist2.dat', full_name)
      full_name = path%find('exist3.dat', rc=status)
      @assertEqual(0, status)
      @assertEqual('dir1/dir3/exist3.dat', full_name)
   end subroutine test_complex
Call graph
test_complex calls assertequal, append, find
append calls push_back
find calls begin, get, next