test_set_ESMF_TimeInterval_integer – MAPL
test_set_ESMF_TimeInterval_integer Subroutine
9 statements
Source File
public subroutine test_set_ESMF_TimeInterval_integer()
Arguments
None
Calls
Source Code
   subroutine test_set_ESMF_TimeInterval_integer()
      integer :: duration = 1800, actual
      type(datetime_duration) :: dt_dur
      character(len=*), parameter :: units = 'seconds since 1999-12-31 23:29:59'
      type(ESMF_TimeInterval) :: interval
      integer :: status
      call convert_CF_Time_to_datetime_duration(duration, units, dt_dur, rc = status)
      @assertEqual(_SUCCESS, status, 'Conversion unsuccessful')
   end subroutine test_set_ESMF_TimeInterval_integer
Call graph
test_set_esmf_timeinterval_integer calls assertequal, convert_cf_time_to_datetime_duration
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
convert_cf_time_to_datetime_duration_integer calls get_time_unit, mapl_assert, mapl_return, set_value
convert_cf_time_to_datetime_duration_integer_duration calls convert_cf_time_to_datetime_duration, mapl_return, mapl_verify
convert_cf_time_to_datetime_duration_real calls get_time_unit, mapl_assert, mapl_return, set_value
convert_cf_time_to_datetime_duration_real_duration calls convert_cf_time_to_datetime_duration, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception