test_count_nodes_depth_1 – MAPL
test_count_nodes_depth_1 Subroutine
16 statements
Source File
public subroutine test_count_nodes_depth_1()
Arguments
None
Calls
Source Code
   subroutine test_count_nodes_depth_1()
      type (MeterNode), target :: node
      class (AbstractMeterNodeIterator), allocatable :: iter
      integer :: count
      node = MeterNode('all', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('a', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('b', AdvancedMeter(MpiTimerGauge()))
      call node%add_child('c', AdvancedMeter(MpiTimerGauge()))
      count = 0
      allocate(iter, source=node%begin())
      do while (iter /= node%end())
         count = count + 1
         call iter%next()
      end do
      @assertEqual(node%get_num_nodes(), count)
   end subroutine test_count_nodes_depth_1
Call graph
test_count_nodes_depth_1 calls assertequal, next, add_child, begin, get_num_nodes
add_child calls find_child, get_depth, v_push_back
get_num_nodes calls get_num_nodes, v_begin, v_iter_get, v_iter_next
find_child calls at
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity