test_put_directory – MAPL
test_put_directory Subroutine
18 statements
Source File
public subroutine test_put_directory(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_put_directory(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DirectoryService) :: ds
      integer :: comm
      integer :: win
      type (Directory) :: dir, dir2
      comm = this%getMpiCommunicator()
      ds = DirectoryService(comm)
      dir%num_entries = 1
      dir%entries(1) = DirectoryEntry('foo', 1)
      win = ds%get_win('server_directory')
      call ds%put_directory(dir, win)
      dir2 = ds%get_directory(win)
      @assertEqual(dir%num_entries, dir2%num_entries)
      @assertEqual(dir%entries(1)%port_name, dir%entries(1)%port_name)
      @assertEqual(dir%entries(1)%partner_root_rank, dir%entries(1)%partner_root_rank)
      call ds%free_directory_resources()
   end subroutine test_put_directory
Call graph
test_put_directory calls assertequal, getmpicommunicator, free_directory_resources, get_directory, get_win, put_directory
free_directory_resources calls mpi_barrier, mpi_comm_free, mpi_free_mem, mpi_win_free, free_mpi_resources, mapl_return, mapl_verify
get_directory calls mpi_get, mpi_win_lock, mpi_win_unlock, mapl_verify, sizeof_directory
put_directory calls mpi_put, mpi_win_lock, mpi_win_unlock, mapl_verify, sizeof_directory
free_mpi_resources calls mpi_comm_free, mpi_free_mem, mpi_win_free, mapl_verify, mpi_type_free
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize