test_is_valid_time – MAPL
test_is_valid_time Subroutine
8 statements
Source File
public subroutine test_is_valid_time()
Arguments
None
Calls
Contents
Source Code
test_is_valid_time
Source Code
   subroutine test_is_valid_time()
      type(time_fields) :: valid_time
      type(time_fields) :: invalid_time
      valid_time = time_fields(9, 41, 33, 456, 0)
      invalid_time = time_fields(24, 41, 33, 456, 0)
      @assertTrue(is_valid_time(valid_time))
      @assertFalse(is_valid_time(invalid_time))
   end subroutine test_is_valid_time
Call graph
test_is_valid_time calls assertfalse, asserttrue, time_fields, is_valid_time
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit