test_FieldAXPY_R8 – MAPL
test_FieldAXPY_R8 Subroutine
25 statements
Source File
public subroutine test_FieldAXPY_R8(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldAXPY_R8(this)
       class(MpiTestMethod), intent(inout) :: this
     real(kind=ESMF_KIND_R8), parameter :: a = 2.0
      type(ESMF_Field) :: x
      type(ESMF_Field) :: y
      real(kind=ESMF_KIND_R8), dimension(:,:), allocatable :: x_array
      real(kind=ESMF_KIND_R8), dimension(:,:), pointer :: x_ptr
      real(kind=ESMF_KIND_R8), dimension(:,:), allocatable :: y_array
      real(kind=ESMF_KIND_R8), dimension(:,:), pointer :: y_ptr
      integer :: status, rc
      x = XR8
      y = YR8
      call ESMF_FieldGet(x, farrayPtr = x_ptr, _RC)
      x_array = x_ptr
      call ESMF_FieldGet(y, farrayPtr = y_ptr, _RC)
      y_array = y_ptr
      call FieldAXPY(a, x, y, _RC)
      call ESMF_FieldGet(x, farrayPtr = x_ptr, _RC)
      call ESMF_FieldGet(y, farrayPtr = y_ptr, _RC)
   end subroutine test_FieldAXPY_R8
Call graph
test_fieldaxpy_r8 calls esmf_fieldget, fieldaxpy, mapl_verify
fieldaxpy calls axpy_r4, axpy_r8
mapl_verify calls mapl_throw_exception
axpy_r4 calls mapl_verify, assign_fptr, fieldsareconformable, mapl_assert, verify_typekind, mapl_return
axpy_r8 calls mapl_verify, assign_fptr, fieldsareconformable, mapl_assert, verify_typekind, mapl_return
mapl_throw_exception calls initialize
assign_fptr calls assign_fptr_r4_rank1, assign_fptr_r4_rank2, assign_fptr_r8_rank1, assign_fptr_r8_rank2
fieldsareconformable calls are_conformable_array, are_conformable_scalar
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
verify_typekind calls verify_typekind_array, verify_typekind_scalar
mapl_return calls mapl_throw_exception, get_error_message