test_handle_PrefetchData – MAPL
test_handle_PrefetchData Subroutine
47 statements
Source File
public subroutine test_handle_PrefetchData()
Arguments
None
Calls
Source Code
   subroutine test_handle_PrefetchData()
      type (ServerThread) :: s
      character(len=:), allocatable :: expected
      type (ArrayReference) :: reference_a, reference_u, reference_v
      type (MockSocketLog), target :: log
      type (MockSocket) :: client_socket
      real(kind=REAL32), target :: a, u(NX,NY), v(NX,NY)
      type (MockServer) :: mock_server
      integer :: i
      reference_a = ArrayReference(a)
      reference_u = ArrayReference(u)
      reference_v = ArrayReference(v)
      client_socket = MockSocket(log)
      call client_socket%add_message(AddExtCollectionMessage('foo'))
      call client_socket%add_message(PrefetchDataMessage(1, 1, 'fake_data.nc4', 'a', reference_a))
      call client_socket%add_message(PrefetchDataMessage(2, 1, 'fake_data.nc4', 'u', reference_u, start=[1,1]))
      call client_socket%add_message(PrefetchDataMessage(3, 1, 'fake_data.nc4', 'v', reference_v, start=[1,1]))
      call client_socket%add_message(PrefetchDoneMessage())
      call client_socket%add_message(TerminateMessage())
      mock_server = MockServer()
      call s%init(client_socket, mock_server)
      call s%set_rank(1)
      do i = 1,6
         call s%run()
      enddo
      expected = ""
      expected = expected // "receive<AddExtCollection('foo')>"
      expected = expected // " :: send<Id(001)>"
      expected = expected // " :: receive<PrefetchData('a')>"
      expected = expected // " :: send<Dummy>"
      expected = expected // " :: receive<PrefetchData('u')>"
      expected = expected // " :: send<Dummy>"
      expected = expected // " :: receive<PrefetchData('v')>"
      expected = expected // " :: send<Dummy>"
      expected = expected // " :: receive<Done_prefetch>"
      expected = expected // " :: put()"
      expected = expected // " :: put()"
      expected = expected // " :: put()"
      expected = expected // " :: wait()"
      expected = expected // " :: wait()"
      expected = expected // " :: wait()"
      expected = expected // " :: receive<Terminate>"
      @assertEqual(expected, log%log)
      @assertEqual(A_EXPECTED, log%values_a)
      @assertEqual(U_EXPECTED, log%values_u)
      @assertEqual(V_EXPECTED, log%values_v)
   end subroutine test_handle_PrefetchData
Call graph
test_handle_prefetchdata calls assertequal, add_message, init, run, set_rank
add_message calls v_push_back
init calls mapl_return, mapl_verify, set_connection
run calls start, dispatch, get_connection, mapl_return, mapl_verify, receive
dispatch calls mapl_return, mapl_verify, handle
get_connection calls mapl_return, mapl_assert
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
set_connection calls mapl_return
v_push_back calls resize, v_grow_to
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
start_self calls mapl_return, mapl_assert, start, get_name
v_grow_to calls v_capacity, v_set_capacity