test_convert_ESMF_to_NetCDF_DateTime – MAPL
test_convert_ESMF_to_NetCDF_DateTime Subroutine
28 statements
Source File
public subroutine test_convert_ESMF_to_NetCDF_DateTime()
Arguments
None
Calls
Contents
Source Code
test_convert_ESMF_to_NetCDF_DateTime
Source Code
   subroutine test_convert_ESMF_to_NetCDF_DateTime()
      character(len=*), parameter :: tunit = 'seconds'
      character(len=*), parameter :: t0_iso_string = '2013-08-26T12:34:56'
      type(ESMF_Time) :: t0
      character(len=*), parameter :: t1_iso_string = '2013-08-26T13:04:56'
      type(ESMF_Time) :: t1
      type(ESMF_TimeInterval) :: interval
      integer, parameter :: span = 1800
      character(len=*), parameter :: expected_units_string = tunit // ' since 2013-08-26 12:34:56'
      integer, parameter :: expected_int_time = span
      integer :: int_time
      character(len=:), allocatable :: units_string
      integer :: rc, status
      call ESMF_TimeSet(t0, t0_iso_string, _RC)
      call ESMF_TimeSet(t1, t1_iso_string, _RC)
      call ESMF_TimeIntervalSet(interval, startTime=t0, s=span, _RC)
      call convert_ESMF_to_NetCDF_DateTime(tunit, t0, int_time, units_string, t1=t1, _RC)
      @assertEqual(expected_int_time, int_time, 'Using t1, expected_int_time /= int_time')
      @assertEqual(expected_units_string, units_string, 'Using t1, expected_units_strin g/= units_string')
      call convert_ESMF_to_NetCDF_DateTime(tunit, t0, int_time, units_string, interval=interval, _RC)
      @assertEqual(expected_int_time, int_time, 'Using interval, expected_int_time /= int_time')
      @assertEqual(expected_units_string, units_string, 'Using interval, expected_units_strin g/= units_string')
   end subroutine test_convert_ESMF_to_NetCDF_DateTime
Call graph
test_convert_esmf_to_netcdf_datetime calls ESMF_TimeIntervalSet, ESMF_TimeSet, assertequal, convert_esmf_to_netcdf_datetime, mapl_verify
convert_esmf_to_netcdf_datetime calls mapl_verify, mapl_assert, make_netcdf_datetime_int_time, make_netcdf_datetime_units_string, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
make_netcdf_datetime_int_time calls mapl_verify, mapl_assert, mapl_return, ESMF_TimeIntervalGet, lr_trim
make_netcdf_datetime_units_string calls mapl_verify, mapl_return, convert_esmf_time_to_netcdf_datetimestring
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
convert_esmf_time_to_netcdf_datetimestring calls mapl_verify, mapl_assert, mapl_return, ESMF_TimeGet
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message