test_get_ith_dimension – MAPL
test_get_ith_dimension Subroutine
8 statements
Source File
public subroutine test_get_ith_dimension()
Arguments
None
Calls
Source Code
   subroutine test_get_ith_dimension()
      type (Variable) :: var
      var = Variable(type=pFIO_INT32, dimensions='x')
      @assertEqual('x', var%get_ith_dimension(1))
      var = Variable(type=pFIO_INT32, dimensions='x,yz,qqq')
      @assertEqual('yz', var%get_ith_dimension(2))
      @assertEqual('qqq', var%get_ith_dimension(3))
   end subroutine test_get_ith_dimension
Call graph
test_get_ith_dimension calls assertequal, get_ith_dimension
get_ith_dimension calls at, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize