test_get_min – MAPL
test_get_min Subroutine
23 statements
Source File
public subroutine test_get_min(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_get_min(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DistributedMeter) :: distributed
      type (DistributedReal64) :: distributed_min_cycle
      distributed = DistributedMeter(MpiTimerGauge())
      select case (this%getProcessRank())
      case (0)
         call distributed%add_cycle(1.0_REAL64)
         call distributed%add_cycle(3.0_REAL64)
      case (1)
         call distributed%add_cycle(2.0_REAL64)
      end select
      call distributed%reduce(this%getMpiCommunicator(), 0._REAL64)
      distributed_min_cycle = distributed%get_stats_min_cycle()
      if (this%getProcessRank() == 0) then
         ! Some of these are meaningless/pointless
         @assertEqual(3.0, distributed_min_cycle%total)
         @assertEqual(1.0, distributed_min_cycle%min)
         @assertEqual(2.0, distributed_min_cycle%max)
         @assertEqual(0, distributed_min_cycle%min_pe)
         @assertEqual(1, distributed_min_cycle%max_pe)
         @assertEqual(2, distributed_min_cycle%num_pes)
      end if
   end subroutine test_get_min
Call graph
test_get_min calls assertequal, getmpicommunicator, getprocessrank, reduce, add_cycle, get_stats_min_cycle
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles
reduce_mpi calls mpi_comm_rank, mpi_reduce, get_max_cycle, get_min_cycle, get_num_cycles, get_sum_square_deviation, get_total, mapl_verify
mapl_verify calls mapl_throw_exception