test_percent_inclusive – MAPL
test_percent_inclusive Subroutine
28 statements
Source File
public subroutine test_percent_inclusive()
Uses
iso_fortran_env
Arguments
None
Calls
Source Code
   subroutine test_percent_inclusive()
      use, intrinsic :: iso_fortran_env, only: REAL64
      type (PercentageColumn) :: c
      type (MeterNode), target :: node
      class (AbstractMeterNode), pointer :: child
      class (AbstractMeter), pointer :: t
      type(UnlimitedVector) :: v
      integer :: i
      integer :: expected(2)
      class(*), allocatable :: q
      node = MeterNode('foo', AdvancedMeter(MpiTimerGauge()))
      t => node%get_meter()
      call t%add_cycle(10.0_REAL64)
      call node%add_child('a', AdvancedMeter(MpiTimerGauge()))
      child => node%get_child('a')
      t => child%get_meter()
      call t%add_cycle(5.0_REAL64)
      c = PercentageColumn(InclusiveColumn(),'MAX')
      v = c%get_rows(node)
      expected = [100.,50.]
      do i = 1, 2
         q = v%at(i)
         select type (q)
         type is (real(kind=REAL64))
            @assertEqual(expected(i), q)
         end select
      end do
   end subroutine test_percent_inclusive
Call graph
test_percent_inclusive calls add_cycle, assertequal, at, add_child, get_child, get_meter, get_rows
add_child calls find_child, get_depth, v_push_back
get_child calls at, find_child
get_rows calls at, get_rows, push_back
find_child calls at
v_push_back calls resize, v_grow_to
v_at_32 calls v_at_size_kind
v_grow_to calls v_capacity, v_set_capacity