test_get_converter – MAPL
test_get_converter Subroutine
14 statements
Source File
public subroutine test_get_converter()
Arguments
None
Calls
Source Code
   subroutine test_get_converter()
      type(Converter) :: conv
      type(c_ptr) :: cptr
      integer(ut_status) :: status
      call initialize_udunits_system(rc=status)
      @assertEqual(UT_SUCCESS, status, 'Failed to initialize')
      call get_converter(conv, KM, M, rc=status)
      @assertEqual(UT_SUCCESS, status, 'Failed to get converter')
      @assertFalse(conv%is_free(), 'cv_converter is not set')
      cptr = conv%get_cptr()
      @assertTrue(c_associated(cptr), 'c_ptr is not associated')
      call conv%free()
      call finalize_udunits_system()
  end subroutine test_get_converter
Call graph
test_get_converter calls assertequal, assertfalse, asserttrue, finalize_udunits_system, initialize_udunits_system, get_converter, get_cptr, is_free
get_converter calls is_free, get_converter_function
get_converter_function calls is_free, instance_is_uninitialized
instance_is_uninitialized calls is_free