test_construct_ISO8601DateTime – MAPL
test_construct_ISO8601DateTime Subroutine
34 statements
Source File
public subroutine test_construct_ISO8601DateTime()
Arguments
None
Calls
Source Code
   subroutine test_construct_ISO8601DateTime()
      type(ISO8601DateTime) :: isodatetime
      integer :: year = 2022
      integer :: month = 07
      integer :: day = 07
      integer :: hour = 17
      integer :: minute = 41
      integer :: second = 07
      integer :: millisecond = 513
      integer :: timezone_offset = 0
      character(len=*), parameter :: delimited = '2022-07-07T17:41:07.513Z'
      character(len=*), parameter :: undelimited = '20220707T174107.513Z'
      integer :: status
      isodatetime = construct_ISO8601DateTime(delimited, rc = status)
      @assertEqual(SUCCESS, status)
      @assertEqual(year, isodatetime%get_year())
      @assertEqual(month, isodatetime%get_month())
      @assertEqual(day, isodatetime%get_day())
      @assertEqual(hour, isodatetime%get_hour())
      @assertEqual(minute, isodatetime%get_minute())
      @assertEqual(second, isodatetime%get_second())
      @assertEqual(millisecond, isodatetime%get_millisecond())
      @assertEqual(timezone_offset, isodatetime%get_timezone_offset())
      isodatetime = construct_ISO8601DateTime(undelimited, rc = status)
      @assertEqual(SUCCESS, status)
      @assertEqual(year, isodatetime%get_year())
      @assertEqual(month, isodatetime%get_month())
      @assertEqual(day, isodatetime%get_day())
      @assertEqual(hour, isodatetime%get_hour())
      @assertEqual(minute, isodatetime%get_minute())
      @assertEqual(second, isodatetime%get_second())
      @assertEqual(millisecond, isodatetime%get_millisecond())
      @assertEqual(timezone_offset, isodatetime%get_timezone_offset())
   end subroutine test_construct_ISO8601DateTime
Call graph
test_construct_iso8601datetime calls assertequal, construct_iso8601datetime, get_day_datetime, get_hour_datetime, get_millisecond_datetime, get_minute_datetime, get_month_datetime, get_second_datetime, get_timezone_offset_datetime, get_year_datetime
construct_iso8601datetime calls mapl_assert, mapl_return, mapl_verify
get_day_datetime calls get_day
get_hour_datetime calls get_hour
get_millisecond_datetime calls get_millisecond
get_minute_datetime calls get_minute
get_month_datetime calls get_month
get_second_datetime calls get_second
get_timezone_offset_datetime calls get_timezone_offset
get_year_datetime calls get_year
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize