Test_MAPL_GetResource_array_logical – MAPL
Test_MAPL_GetResource_array_logical Subroutine
20 statements
Source File
public subroutine Test_MAPL_GetResource_array_logical()
Arguments
None
Calls
Source Code
   subroutine Test_MAPL_GetResource_array_logical()
      type(ESMF_Config) :: config
      integer :: status
      logical :: expected(4), actual(4), match
      character(len=*), parameter :: LABEL = 'label'
      character(len=*), parameter :: VAL = '.T. .F. .F. .T.'
      logical :: value_is_set
      character(len=MAX_LINE_LENGTH) :: output_string
      expected = [.TRUE., .FALSE., .FALSE., .TRUE.]
      config = ESMF_ConfigCreate(rc = status)
      @assertEqual(0, status, 'Failed to create ESMF_Config')
      call ESMF_ConfigSetAttribute(config, PRINT_ALL, label = 'PRINTRC:', rc = status)
      @assertEqual(0, status, 'Failed to set PRINTRC')
      call ESMF_ConfigSetAttribute(config, VAL, label = LABEL, rc = status)
      @assertEqual(0, status, 'Failed to set attribute')
      call MAPL_GetResource_config_array(config, actual, label = LABEL, value_is_set = value_is_set, iunit=output_string, rc = status)
      @assertEqual(0, status, 'Failed to get resource')
      match = all(expected .eqv. actual)
      @assertTrue(match, 'actual does not match expected.')
   end subroutine Test_MAPL_GetResource_array_logical
Call graph
test_mapl_getresource_array_logical calls ESMF_ConfigCreate, ESMF_ConfigSetAttribute, assertequal, asserttrue, mapl_getresource_config_array
mapl_getresource_config_array calls ESMF_ConfigGetAttribute, array_format, mapl_assert, compare_all, get_actual_label, get_print_settings, make_string_character_array, mapl_return, mapl_verify, print_resource, set_do_print
array_format calls array_format_simple, array_format_string
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_actual_label calls mapl_return, mapl_verify, ESMF_ConfigFindLabel, get_labels_with_prefix
get_print_settings calls ESMF_ConfigGetAttribute, mapl_verify, mapl_am_i_root
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
print_resource calls mapl_return
set_do_print calls vector_contains_str, push_back