test_create_from_parameters_heartbeat_negative – MAPL
test_create_from_parameters_heartbeat_negative Subroutine
16 statements
Source File
public subroutine test_create_from_parameters_heartbeat_negative()
Arguments
None
Calls
Source Code
   subroutine test_create_from_parameters_heartbeat_negative()
      type(ExtDataPointerUpdate) :: ex
      integer :: status, rc
      character(len=*), parameter :: OFFSET_STRING = '-' // HEARTBEAT_STRING
      type(ESMF_TimeInterval) :: offset, interval
      integer :: expected, actual
      offset = -timestep
      call ESMF_TimeIntervalGet(offset, s=expected, _RC)
      call ex%create_from_parameters(UPDATE_TIMESTRING, UPDATE_FREQ_STRING, OFFSET_STRING, default_time, clock, _RC)
      interval = ex%get_offset()
      call ESMF_TimeIntervalGet(interval, s=actual, _RC)
      @assertEqual(expected, actual, ERR_MSG)
   end subroutine test_create_from_parameters_heartbeat_negative
Call graph
test_create_from_parameters_heartbeat_negative calls ESMF_TimeIntervalGet, assertequal, create_from_parameters, get_offset, mapl_verify
create_from_parameters calls mapl_verify, ESMF_ClockGet, ESMF_TimeGet, ESMF_TimeSet, mapl_assert, mapl_return, parse_heartbeat_timestring, string_to_esmf_timeinterval, string_to_integer_time
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
parse_heartbeat_timestring calls mapl_verify, ESMF_UtilStringUpperCase, split_on
string_to_esmf_timeinterval calls mapl_verify, mapl_assert, mapl_return, ESMF_TimeIntervalSet
string_to_integer_time calls mapl_return
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message