test_serialize_1d – MAPL
test_serialize_1d Subroutine
16 statements
Source File
public subroutine test_serialize_1d()
Arguments
None
Calls
Source Code
   subroutine test_serialize_1d()
      type (PrefetchDataMessage) :: msg_in, msg_out
      type (ArrayReference) :: ref
      integer, target :: n(3)
      integer, allocatable :: buffer(:)
      ref = ArrayReference(n)
      msg_in = PrefetchDataMessage(1, 3, 'foo', 'bar', ref, start=[2])
      allocate(buffer(msg_in%get_length()))
      call msg_in%serialize(buffer)
      call msg_out%deserialize(buffer)
      @assertEqual(1, msg_out%request_id)
      @assertEqual(3, msg_out%collection_id)
      @assertEqual('foo', msg_out%file_name)
      @assertEqual('bar', msg_out%var_name)
      @assertEqual([2], msg_out%start)
   end subroutine test_serialize_1d
Call graph
test_serialize_1d calls assertequal, deserialize, get_length, serialize
deserialize calls deserialize_intrinsic, serialize_buffer_length, mapl_return
get_length calls serialize_buffer_length
serialize calls serialize_intrinsic, mapl_return