test_ISO8601DateTime_getters – MAPL
test_ISO8601DateTime_getters Subroutine
31 statements
Source File
public subroutine test_ISO8601DateTime_getters()
Arguments
None
Calls
Contents
Source Code
test_ISO8601DateTime_getters
Source Code
   subroutine test_ISO8601DateTime_getters()
      character(len=*), parameter :: isodate = '20220707'
      character(len=*), parameter :: isotime = 'T174107.513Z'
      integer, parameter :: YEAR = 2022
      integer, parameter :: MONTH = 07
      integer, parameter :: DAY = 07
      integer, parameter :: HOUR = 17
      integer, parameter :: MINUTE = 41
      integer, parameter :: SECOND = 07
      integer, parameter :: MILLISECOND = 513
      integer, parameter :: TIMEZONE_OFFSET = 0
      type(ISO8601DateTime) :: datetime
      type(ISO8601Date) :: date
      type(ISO8601Time) :: time
      integer :: status
      integer :: rc
      date = ISO8601Date(isodate, _RC)
      datetime%date_ = date
      time = ISO8601Time(isotime, _RC)
      datetime%time_ = time
      @assertEqual(YEAR, datetime%get_year())
      @assertEqual(MONTH, datetime%get_month())
      @assertEqual(DAY, datetime%get_day())
      @assertEqual(HOUR, datetime%get_hour())
      @assertEqual(MINUTE, datetime%get_minute())
      @assertEqual(SECOND, datetime%get_second())
      @assertEqual(MILLISECOND, datetime%get_millisecond())
      @assertEqual(TIMEZONE_OFFSET, datetime%get_timezone_offset())
   end subroutine test_ISO8601DateTime_getters
Call graph
test_iso8601datetime_getters calls assertequal, iso8601date, iso8601time, get_day, get_hour, get_millisecond, get_minute, get_month, get_second, get_timezone_offset, get_year, mapl_verify
iso8601date calls construct_iso8601date
iso8601time calls construct_iso8601time
mapl_verify calls mapl_throw_exception
construct_iso8601date calls mapl_assert, parse_date
construct_iso8601time calls mapl_assert, mapl_return, parse_time
mapl_throw_exception calls initialize
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
parse_date calls is_valid_date, read_whole_number, undelimit
parse_time calls time_fields, is_valid_time, is_whole_number, parse_timezone_offset, read_whole_number, undelimit