test_get_mean_cycle – MAPL
test_get_mean_cycle Subroutine
11 statements
Source File
public subroutine test_get_mean_cycle()
Arguments
None
Calls
Source Code
   subroutine test_get_mean_cycle()
      type (AdvancedMeter) :: t
      t = AdvancedMeter(MpiTimerGauge())
      call t%add_cycle(increment=1._REAL64)
      call t%add_cycle(increment=3._REAL64)
      @assertEqual(2., t%get_mean_cycle())
      call t%reset()
      call t%add_cycle(increment=3._REAL64)
      call t%add_cycle(increment=5._REAL64)
      @assertEqual(4., t%get_mean_cycle())
   end subroutine test_get_mean_cycle
Call graph
test_get_mean_cycle calls assertequal, add_cycle, get_mean_cycle, reset
add_cycle calls get_mean_cycle
get_mean_cycle calls get_num_cycles