test_write_read_simple_attribute – MAPL
test_write_read_simple_attribute Subroutine
21 statements
Source File
public subroutine test_write_read_simple_attribute()
Arguments
None
Calls
Source Code
   subroutine test_write_read_simple_attribute()
      type (NetCDF4_FileFormatter) :: formatter
      type (FileMetadata) :: cf_expected
      type (FileMetadata) :: cf_found
      integer :: status
      call cf_expected%add_dimension('x',1)
      call cf_expected%add_dimension('y',2)
      call cf_expected%add_attribute('attr', [1,2])
      call formatter%create('test.nc', rc=status)
      @assertEqual(NF90_NOERR, status)
      call formatter%write(cf_expected, rc=status)
      @assertEqual(0, NF90_NOERR)
      call formatter%close(rc=status)
      @assertEqual(0, NF90_NOERR)
      call formatter%open('test.nc', mode=NF90_NOWRITE, rc=status)
      @assertEqual(0, NF90_NOERR)
      cf_found = formatter%read(rc=status)
      call formatter%close(rc=status)
      @assertEqual(0, NF90_NOERR)
      @assertTrue(cf_expected == cf_found)
   end subroutine test_write_read_simple_attribute
Call graph
test_write_read_simple_attribute calls assertequal, asserttrue, add_attribute, add_dimension, create
add_dimension calls insert, mapl_return
create calls nf90_create, mapl_return, mapl_verify
add_attribute_0d calls mapl_return, add_attribute
add_attribute_1d calls mapl_return, add_attribute
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls insert, at
mapl_throw_exception calls initialize