test_SetAttribute_string – MAPL
test_SetAttribute_string Subroutine
8 statements
Source File
public subroutine test_SetAttribute_string()
Arguments
None
Calls
Source Code
   subroutine test_SetAttribute_string
      type (ESMF_Config) :: config
      integer :: status
      character(len=ESMF_MAXSTR) :: str
      config = MAPL_ConfigCreate()
      call MAPL_ConfigSetAttribute(config, 'LatLon', 'GRID_TYPE:', rc=status)
      call ESMF_ConfigGetAttribute(config, value=str, label='GRID_TYPE:', rc=status)
   end subroutine test_SetAttribute_string
Call graph
test_setattribute_string calls ESMF_ConfigGetAttribute, mapl_configsetattribute, mapl_configcreate
mapl_configsetattribute calls mapl_configsetattribute_int32, mapl_configsetattribute_ints32, mapl_configsetattribute_real32, mapl_configsetattribute_real64, mapl_configsetattribute_reals32, mapl_configsetattribute_string
mapl_configcreate calls ESMF_ConfigCreate, buffer, mapl_return
mapl_configsetattribute_int32 calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_configsetattribute_ints32 calls mapl_configsetattribute, mapl_return, mapl_assert, mapl_verify
mapl_configsetattribute_real32 calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_configsetattribute_real64 calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_configsetattribute_reals32 calls mapl_configsetattribute, mapl_return, mapl_assert, mapl_verify
mapl_configsetattribute_string calls ESMF_ConfigGetAttribute, buffer, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_verify calls mapl_throw_exception