test_make_NetCDF_DateTime_int_time – MAPL
test_make_NetCDF_DateTime_int_time Subroutine
16 statements
Source File
public subroutine test_make_NetCDF_DateTime_int_time()
Arguments
None
Calls
Contents
Source Code
test_make_NetCDF_DateTime_int_time
Source Code
   subroutine test_make_NetCDF_DateTime_int_time()
      character(len=*), parameter :: tunit = 'seconds'
      character(len=*), parameter :: iso_string = '2013-08-26T12:34:56'
      type(ESMF_TimeInterval) :: interval
      type(ESMF_Time) :: t0
      integer, parameter :: expected_int_time = 1800
      integer :: int_time
      integer :: status, rc
      call ESMF_TimeSet(t0, iso_string, _RC)
      call ESMF_TimeIntervalSet(interval, startTime=t0, s=expected_int_time, _RC)
      call make_NetCDF_DateTime_int_time(interval, t0, tunit, int_time, _RC)
      @assertEqual(expected_int_time, int_time, 'int_time does not match.')
   end subroutine test_make_NetCDF_DateTime_int_time
Call graph
test_make_netcdf_datetime_int_time calls ESMF_TimeIntervalSet, ESMF_TimeSet, assertequal, make_netcdf_datetime_int_time, mapl_verify
make_netcdf_datetime_int_time calls mapl_verify, ESMF_TimeIntervalGet, mapl_assert, lr_trim, mapl_return
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls mapl_throw_exception, get_error_message