test_get_dimensions – MAPL
test_get_dimensions Subroutine
8 statements
Source File
public subroutine test_get_dimensions()
Arguments
None
Calls
Source Code
   subroutine test_get_dimensions()
      type (FileMetadata), target :: cf
      type (StringIntegerMap), pointer :: dimensions
      call cf%add_dimension('x', 10)
      call cf%add_dimension('y', 11)
      dimensions => cf%get_dimensions()
      @assertEqual(2, dimensions%size())
   end subroutine test_get_dimensions
Call graph
test_get_dimensions calls assertequal, add_dimension, get_dimensions
add_dimension calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls insert, at
mapl_throw_exception calls initialize