test_connect_multi – MAPL
test_connect_multi Subroutine
29 statements
Source File
public subroutine test_connect_multi(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Contents
Source Code
test_connect_multi
Source Code
   subroutine test_connect_multi(this)
      class (MpiTestMethod), intent(inout) :: this
      type (DirectoryService) :: ds
      integer :: comm
      integer :: ierror
      integer :: color, key
      type (MockServer) :: mock_server
      type (MockClient) :: mock_client
      ds = DirectoryService(this%getMpiCommunicator())
      color = this%getProcessRank()/3
      key = 0
      call MPI_Comm_split(this%getMpiCommunicator(), color, key, comm, ierror)
      @assertEqual(0, ierror)
      select case (color)
      case (1) ! server
         mock_server = MockServer(comm)
         call ds%publish(PortInfo('input', mock_server), mock_server)
         select case (this%getProcessRank())
         case (3) ! have one
            call ds%connect_to_client('input', mock_server)
         case (4)
            call ds%connect_to_client('input', mock_server)
         end select
      case (0) ! client
         mock_client = MockClient()
         call ds%connect_to_server('input', mock_client, comm)
      end select
      call ds%free_directory_resources()
   end subroutine test_connect_multi
Call graph
test_connect_multi calls assertequal, connect_to_client, connect_to_server, free_directory_resources, getmpicommunicator, getprocessrank, mpi_comm_split, publish