test_are_valid_time_fields – MAPL
test_are_valid_time_fields Subroutine
7 statements
Source File
public subroutine test_are_valid_time_fields()
Arguments
None
Calls
Contents
Source Code
test_are_valid_time_fields
Source Code
   subroutine test_are_valid_time_fields
      type(time_fields) :: tf
      tf = time_fields(13, 43, 37, 100, 0)
      @assertTrue(tf % is_valid(), 'tf should be valid.')
      tf = time_fields(13, 63, 37, 100, 0)
      @assertFalse(tf % is_valid(), 'tf should not be valid.')
   end subroutine test_are_valid_time_fields
Call graph
test_are_valid_time_fields calls assertfalse, asserttrue, time_fields
time_fields calls construct_time_fields_default, construct_time_fields_null, construct_time_fields_string
construct_time_fields_default calls is_valid_time
construct_time_fields_string calls parse_time
is_valid_time calls hour, millisecond, minute, is_valid_hour, is_valid_millisecond, is_valid_minute, is_valid_second, is_valid_timezone_offset, timezone_offset
parse_time calls time_fields, is_whole_number, parse_timezone_offset, read_whole_number, undelimit