test_serialize_buffer_length_int64_1d – MAPL
test_serialize_buffer_length_int64_1d Subroutine
12 statements
Source File
public subroutine test_serialize_buffer_length_int64_1d()
Arguments
None
Calls
Source Code
   subroutine test_serialize_buffer_length_int64_1d()
      integer(kind=INT64) :: empty(0)
      integer(kind=INT64) :: i,j,k,l,m
      m = 10
      i = m**14; j = i+1; k = i+2; l = i+3
      @assertEqual(1, serialize_buffer_length(empty))
      @assertEqual(3, serialize_buffer_length([i]))
      @assertEqual(9, serialize_buffer_length([i,j,k,l]))
   end subroutine test_serialize_buffer_length_int64_1d
Call graph
test_serialize_buffer_length_int64_1d calls assertequal, serialize_buffer_length
serialize_buffer_length calls serialize_buffer_length_int32_0d, serialize_buffer_length_int32_1d, serialize_buffer_length_int64_0d, serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d, serialize_buffer_length_string
serialize_buffer_length_int32_0d calls mapl_return
serialize_buffer_length_int32_1d calls mapl_return
serialize_buffer_length_int64_0d calls mapl_return
serialize_buffer_length_int64_1d calls mapl_return, word_size
serialize_buffer_length_logical_0d calls mapl_return, word_size
serialize_buffer_length_logical_1d calls mapl_return, word_size
serialize_buffer_length_real32_0d calls mapl_return, word_size
serialize_buffer_length_real32_1d calls mapl_return, word_size
serialize_buffer_length_real64_0d calls mapl_return, word_size
serialize_buffer_length_real64_1d calls mapl_return, word_size
serialize_buffer_length_string calls mapl_return
mapl_return calls get_error_message, mapl_throw_exception
word_size calls mapl_return, mapl_assert