test_FieldGetLocalElementCount – MAPL
test_FieldGetLocalElementCount Subroutine
17 statements
Source File
public subroutine test_FieldGetLocalElementCount(this)
Arguments
Type Intent Optional Attributes Name
class(MpiTestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_FieldGetLocalElementCount(this)
      class(MpiTestMethod), intent(inout) :: this
      type(ESMF_Field) :: x
      integer :: rank
      integer, allocatable :: expected_count(:)
      integer, allocatable :: actual_count(:)
      integer :: status, rc
      x = XR4
      call ESMF_FieldGet(x, rank=rank, _RC)
      allocate(expected_count(rank))
      call ESMF_FieldGet(x, localElementCount=expected_count, _RC)
      actual_count = FieldGetLocalElementCount(x, _RC)
      @assertEqual(actual_count, expected_count)
   end subroutine test_FieldGetLocalElementCount
Call graph
test_fieldgetlocalelementcount calls assertequal, esmf_fieldget, fieldgetlocalelementcount, mapl_verify
fieldgetlocalelementcount calls get_local_element_count
mapl_verify calls mapl_throw_exception
get_local_element_count calls esmf_fieldget, mapl_verify, mapl_fieldgetlocalelementcount, mapl_return
mapl_throw_exception calls initialize
mapl_fieldgetlocalelementcount calls esmf_fieldget, mapl_verify, mapl_return, mapl_assert
mapl_return calls mapl_throw_exception, get_error_message