test_spherical_to_cartesian_east_wind – MAPL
test_spherical_to_cartesian_east_wind Subroutine
30 statements
Source File
public subroutine test_spherical_to_cartesian_east_wind(this)
Arguments
Type Intent Optional Attributes Name
class(ESMF_TestMethod), intent(inout) :: this
Calls
Source Code
   subroutine test_spherical_to_cartesian_east_wind(this)
      class (ESMF_TestMethod), intent(inout) :: this
      type (LatLonGridFactory) :: factory
      real, allocatable :: east_wind_u(:,:)
      real, allocatable :: east_wind_v(:,:)
      real, allocatable :: xyz(:,:,:,:)
      real, allocatable :: longitudes(:)
      integer, parameter :: IM=12, JM=6
      type (ESMF_Grid) :: grid
      integer :: status
      _UNUSED_DUMMY(this)
      factory = LatLonGridFactory(im_world=IM, jm_world=JM, lm=1, nx=1, ny=1, pole='PE', dateline='GC')
      grid = factory%make_grid()
      allocate(east_wind_u(IM,JM))
      allocate(east_wind_v(IM,JM))
      allocate(xyz(3,1,IM,JM))
      east_wind_u = 1
      east_wind_v = 0
      call factory%spherical_to_cartesian(east_wind_u, east_wind_v, xyz, basis='north-south',rc=status)
      @assertEqual(0, status)
      ! z component is 0
      @assertEqual(0, xyz(3,1,:,:))
      ! Note: longitudes return as REAL64.
      longitudes = real(factory%get_longitudes())
      do j = 1, JM
         @assertEqual(-sin(longitudes), xyz(1,1,:,j), 10*epsilon(1.))
         @assertEqual(+cos(longitudes), xyz(2,1,:,j), 10*epsilon(1.))
      end do
   end subroutine test_spherical_to_cartesian_east_wind
Call graph
test_spherical_to_cartesian_east_wind calls assertequal, spherical_to_cartesian, get_longitudes, make_grid
get_longitudes calls mapl_return
make_grid calls make_new_grid, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
spherical_to_cartesian_3d_real64 calls mapl_return, mapl_verify, mapl_assert, get_basis
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_basis calls mapl_return, mapl_verify, mapl_assert, ESMF_GridGetCoord, computegridbasis, computexyzbasis
get_error_message calls at, insert
mapl_throw_exception calls initialize