test_is_valid_date – MAPL
test_is_valid_date Subroutine
8 statements
Source File
public subroutine test_is_valid_date()
Arguments
None
Calls
Contents
Source Code
test_is_valid_date
Source Code
   subroutine test_is_valid_date()
      type(date_fields) :: valid_date
      type(date_fields) :: invalid_date
      valid_date = date_fields(2022, 7, 7)
      invalid_date = date_fields(2022, 6, 31)
      @assertTrue(is_valid_date(valid_date))
      @assertFalse(is_valid_date(invalid_date))
   end subroutine test_is_valid_date
Call graph
test_is_valid_date calls assertfalse, asserttrue, date_fields, is_valid_date
date_fields calls construct_date_fields_default, construct_date_fields_null, construct_date_fields_string
is_valid_date calls day, month, is_valid_day, is_valid_month, is_valid_year, year
construct_date_fields_default calls is_valid_date
construct_date_fields_string calls parse_date
is_valid_day calls get_month_end
get_month_end calls get_month_ends
parse_date calls date_fields, read_whole_number, undelimit