test_addExtCollection_unique_handle – MAPL
test_addExtCollection_unique_handle Subroutine
17 statements
Source File
public subroutine test_addExtCollection_unique_handle()
Arguments
None
Calls
Source Code
   subroutine test_addExtCollection_unique_handle()
      type (MockClientThread) :: c
      class (AbstractSocket), pointer :: connection
      integer :: handle_foo
      integer :: handle_bar
      type (MockSocketLog), target :: log
      call c%set_connection(MockSocket(log))
      connection => c%get_connection()
      select type (connection)
      type is (MockSocket)
         call connection%add_message(IdMessage(1))
         call connection%add_message(IdMessage(2))
      end select
      handle_foo = c%add_ext_collection(template='foo')
      handle_bar = c%add_ext_collection(template='bar')
      @assertFalse(handle_foo == handle_bar)
   end subroutine test_addExtCollection_unique_handle
Call graph
test_addextcollection_unique_handle calls add_message, assertfalse, add_ext_collection, get_connection, set_connection
add_ext_collection calls get_connection, mapl_assert, mapl_return, mapl_verify, receive, send
get_connection calls mapl_assert, mapl_return
set_connection calls mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize