test_construct_ISO8601Date – MAPL
test_construct_ISO8601Date Subroutine
19 statements
Source File
public subroutine test_construct_ISO8601Date()
Arguments
None
Calls
Contents
Source Code
test_construct_ISO8601Date
Source Code
   subroutine test_construct_ISO8601Date()
      type(ISO8601Date) :: isodate
      integer :: year = 2022
      integer :: month = 07
      integer :: day = 07
      character(len=*), parameter :: delimited = '2022-07-07'
      character(len=*), parameter :: undelimited = '20220707'
      integer :: status
      isodate = ISO8601Date(delimited, rc = status)
      @assertEqual(SUCCESS, status)
      @assertEqual(year, isodate%get_year())
      @assertEqual(month, isodate%get_month())
      @assertEqual(day, isodate%get_day())
      isodate = ISO8601Date(undelimited, rc = status)
      @assertEqual(SUCCESS, status)
      @assertEqual(year, isodate%get_year())
      @assertEqual(month, isodate%get_month())
      @assertEqual(day, isodate%get_day())
   end subroutine test_construct_ISO8601Date
Call graph
test_construct_iso8601date calls iso8601date, assertequal
iso8601date calls construct_iso8601date
construct_iso8601date calls parse_date, mapl_assert
parse_date calls undelimit, is_valid_date, read_whole_number
mapl_assert calls mapl_assert_condition, mapl_assert_return_code