test_equal_dims – MAPL
test_equal_dims Subroutine
15 statements
Source File
public subroutine test_equal_dims()
Arguments
None
Calls
Source Code
   subroutine test_equal_dims()
      type (FileMetadata) :: cf1
      type (FileMetadata) :: cf2
      @assertTrue(cf1 == cf2)
      @assertFalse(cf1 /= cf2)
      call cf1%add_dimension('x', 10)
      call cf1%add_dimension('t', pFIO_UNLIMITED)
      call cf2%add_dimension('t', pFIO_UNLIMITED)
      call cf2%add_dimension('x', 10)
      @assertTrue(cf1 == cf2)
      @assertFalse(cf1 /= cf2)
      call cf1%add_dimension('z', 5)
      @assertFalse(cf1 == cf2)
      @assertFalse(cf2 == cf1)
   end subroutine test_equal_dims
Call graph
test_equal_dims calls assertfalse, asserttrue, add_dimension
add_dimension calls insert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls insert, at
mapl_throw_exception calls initialize