Test_MAPL_GetResource_scalar_character – MAPL
Test_MAPL_GetResource_scalar_character Subroutine
21 statements
Source File
public subroutine Test_MAPL_GetResource_scalar_character()
Arguments
None
Calls
Source Code
   subroutine Test_MAPL_GetResource_scalar_character()
      type(ESMF_Config) :: config
      integer :: status
      character(ESMF_MAXSTR) :: expected, actual
      character(len=*), parameter :: LABEL = 'label'
      character(len=*), parameter :: VAL = 'value'
      character(len=MAX_LINE_LENGTH) :: output_string
      logical :: value_is_set
      config = ESMF_ConfigCreate(rc = status)
      @assertEqual(0, status, 'Failed to create ESMF_Config')
      call ESMF_ConfigSetAttribute(config, PRINT_ALL, label = 'PRINTRC:', rc = status)
      @assertEqual(0, status, 'Failed to set PRINTRC')
      call ESMF_ConfigSetAttribute(config, VAL, label = LABEL, rc = status)
      @assertEqual(0, status, 'Failed to set attribute')
      expected = VAL
      call MAPL_GetResource_config_scalar(config, actual, label = LABEL, value_is_set = value_is_set, iunit = output_string, rc = status)
      @assertEqual(0, status, 'Failed to get resource')
      @assertEqual(expected, actual, 'actual does not match expected.')
      @assertTrue(len_trim(output_string) > len(VAL), 'output_string should be longer than VAL')
      @assertTrue(len_trim(output_string) <= MAX_LINE_LENGTH, 'output_string is too long.')
   end subroutine Test_MAPL_GetResource_scalar_character
Call graph
test_mapl_getresource_scalar_character calls ESMF_ConfigCreate, ESMF_ConfigSetAttribute, assertequal, asserttrue, mapl_getresource_config_scalar
mapl_getresource_config_scalar calls ESMF_ConfigGetAttribute, mapl_assert, get_actual_label, get_print_settings, make_string_character, mapl_return, mapl_verify, print_resource, set_do_print
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_actual_label calls mapl_return, mapl_verify, ESMF_ConfigFindLabel, get_labels_with_prefix
get_print_settings calls ESMF_ConfigGetAttribute, mapl_verify, mapl_am_i_root
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
print_resource calls mapl_return
set_do_print calls vector_contains_str, push_back
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
vector_contains_str calls begin, next, of