test_add_variable – MAPL
test_add_variable Subroutine
31 statements
Source File
public subroutine test_add_variable()
Arguments
None
Calls
Source Code
   subroutine test_add_variable()
      type (NetCDF4_FileFormatter) :: formatter
      type (FileMetadata) :: cf_expected
      type (FileMetadata) :: cf_found
      type (Variable) :: v,v1
      integer :: status
      call cf_expected%add_dimension('x',1)
      call cf_expected%add_dimension('y',2)
      v = Variable(type=pFIO_INT32, dimensions='x,y')
      call v%add_attribute('attr', [1.,2.,3.])
      call cf_expected%add_variable('var', v)
      call formatter%create('test.nc', rc=status)
      @assertEqual(NF90_NOERR, status)
      call formatter%write(cf_expected, rc=status)
      @assertEqual(0, NF90_NOERR)
      call formatter%close(rc=status)
      @assertEqual(0, NF90_NOERR)
      call formatter%open('test.nc', mode=NF90_WRITE, rc=status)
      @assertEqual(NF90_NOERR, status)
      v1 = Variable(type=pFIO_INT32, dimensions='x,y')
      call cf_expected%add_variable('new_var', v1)
      call formatter%add_variable(cf_expected,'new_var', rc=status)
      call formatter%close(rc=status)
      @assertEqual(0, NF90_NOERR)
      call formatter%open('test.nc', mode=NF90_NOWRITE, rc=status)
      @assertEqual(0, NF90_NOERR)
      cf_found = formatter%read(rc=status)
      call formatter%close(rc=status)
      @assertEqual(0, NF90_NOERR)
      @assertTrue(cf_expected == cf_found)
   end subroutine test_add_variable
Call graph
test_add_variable calls assertequal, asserttrue, add_attribute, add_dimension, add_variable, create
add_dimension calls insert, mapl_return
add_variable calls at, begin, get, mapl_assert, next, insert, get_const_value, get_dimensions, get_shape, is_empty, mapl_return, push_back
create calls nf90_create, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
add_attribute_1d calls mapl_return, insert
get_shape calls mapl_return
is_empty calls mapl_return, get_value
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception