ti_at_32 – MAPL
ti_at_32 Function
9 statements
Source File
private function ti_at_32(this, i, unused, rc) result(res)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value integer(kind=SIZE_KIND), pointer
Calls
Called by
Call graph
ti_at_32 calls ti_at_size_kind
advpos calls at, get_child
erase_nonleaf calls at, advpos, rebalance, set_parent_child
get_child calls at
rebalance calls at, get_child, rot, update_height
rot calls at, get_child, set_parent_child, update_height
s_dump calls at
s_erase_multi calls at, erase_nonleaf, rebalance, set_parent_child, s_next
set_parent_child calls at
update_height calls at
s_insert calls rebalance
s_next calls advpos
s_prev calls advpos
equalsets calls s_next
m_erase_one calls erase
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_next calls s_next
m_of calls s_insert
m_previous calls s_prev
m_set calls s_insert
s_begin calls s_next
s_deepcopy calls s_insert, s_next
s_erase_one calls erase, s_next
s_remove calls erase