ti_capacity – MAPL
ti_capacity Function
9 statements
Source File
private pure function ti_capacity(this) result(capacity)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
ti_grow_to calls ti_capacity
ti_reserve_size_kind calls ti_capacity
ti_shrink_to_fit calls ti_capacity
ti_insert_size_kind calls ti_grow_to, ti_push_back
ti_push_back calls ti_grow_to