ti_insert_size_kind – MAPL
ti_insert_size_kind Subroutine
24 statements
Source File
private subroutine ti_insert_size_kind(this, index, value, unused, rc)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: index
integer(kind=SIZE_KIND), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Call graph
ti_insert_size_kind calls resize, ti_grow_to, ti_push_back
ti_grow_to calls ti_capacity, ti_set_capacity
ti_push_back calls resize, ti_grow_to
ti_resize_32 calls resize