ti_push_back – MAPL
ti_push_back Subroutine
10 statements
Source File
private subroutine ti_push_back(this, value, unused, rc)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
ti_push_back calls resize, ti_grow_to
ti_grow_to calls ti_capacity, ti_set_capacity
ti_resize_32 calls resize
ti_insert_size_kind calls ti_push_back