ti_resize_32 – MAPL
ti_resize_32 Subroutine
9 statements
Source File
private subroutine ti_resize_32(this, newsize, value, unused, rc)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(inout) :: this
integer, intent(in) :: newsize
integer(kind=SIZE_KIND), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
ti_resize_32 calls resize
ti_insert_size_kind calls resize, ti_push_back
ti_push_back calls resize