ti_reserve_32 – MAPL
ti_reserve_32 Subroutine
6 statements
Source File
private subroutine ti_reserve_32(this, capacity)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(inout) :: this
integer, intent(in) :: capacity
Calls
Called by
Call graph
ti_reserve_32 calls reserve
ti_copyfromarray calls reserve
ti_resize_size calls reserve