ti_set_capacity – MAPL
ti_set_capacity Subroutine
21 statements
Source File
private subroutine ti_set_capacity(this, capacity)
Type Bound
iVector
Arguments
Type Intent Optional Attributes Name
class(iVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Called by
Call graph
ti_grow_to calls ti_set_capacity
ti_reserve_size_kind calls ti_set_capacity
ti_shrink_to_fit calls ti_set_capacity
ti_insert_size_kind calls ti_grow_to, ti_push_back
ti_push_back calls ti_grow_to