time_ESMF_to_real – MAPL
time_ESMF_to_real Subroutine
39 statements
Source File
public subroutine time_ESMF_to_real(times_R8_1d, times_esmf_1d, datetime_units, rc)
Uses
MAPL_NetCDF
Arguments
Type Intent Optional Attributes Name
real(kind=ESMF_KIND_R8), intent(inout) :: times_R8_1d(:)
type(ESMF_Time), intent(in) :: times_esmf_1d(:)
character(len=*), intent(in) :: datetime_units
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine time_ESMF_to_real (times_R8_1d, times_esmf_1d, datetime_units, rc)
    use  MAPL_NetCDF, only : convert_NetCDF_DateTime_to_ESMF
    type(ESMF_Time), intent(in) :: times_esmf_1d(:)
    real(kind=ESMF_KIND_R8), intent(inout) :: times_R8_1d(:)
    character(len=*), intent(in) :: datetime_units
    integer, optional, intent(out) :: rc
    type(ESMF_TimeInterval) :: interval, t_interval
    type(ESMF_Time) :: time0
    type(ESMF_Time) :: time1
    character(len=:), allocatable :: tunit
    integer :: i, len
    integer :: int_time
    integer :: status
    len = size (times_esmf_1d)
    int_time = 0
    call convert_NetCDF_DateTime_to_ESMF(int_time, datetime_units, interval, &
         time0, time=time1, time_unit=tunit, _RC)
    do i=1, len
       t_interval = times_esmf_1d(i) - time0
       select case(trim(tunit))
       case ('days')
          call ESMF_TimeIntervalGet(t_interval,d_r8=times_R8_1d(i),_RC)
       case ('hours')
          call ESMF_TimeIntervalGet(t_interval,h_r8=times_R8_1d(i),_RC)
       case ('minutes')
          call ESMF_TimeIntervalGet(t_interval,m_r8=times_R8_1d(i),_RC)
       case ('seconds')
          call ESMF_TimeIntervalGet(t_interval,s_r8=times_R8_1d(i),_RC)
       case default
          _FAIL('illegal value for tunit: '//trim(tunit))
       end select
    enddo
    _RETURN(_SUCCESS)
  end subroutine time_ESMF_to_real
Call graph
time_esmf_to_real calls ESMF_TimeIntervalGet, convert_netcdf_datetime_to_esmf, mapl_assert, mapl_return, mapl_verify
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_esmf_time_from_netcdf_datetime_integer calls mapl_assert, mapl_return, mapl_verify, convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, set_esmf_timeinterval, set_esmf_time_from_iso8601
get_esmf_time_from_netcdf_datetime_real calls mapl_assert, mapl_return, mapl_verify, convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, set_esmf_timeinterval, set_esmf_time_from_iso8601
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
extract_cf_time_unit calls extract_cf_time_unit_cf_time, extract_cf_time_unit_units
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time, extract_iso8601_from_cf_time_units
set_esmf_timeinterval calls set_esmf_timeinterval_from_datetime_duration
set_esmf_time_from_iso8601 calls mapl_return, mapl_verify, ESMF_TimeSet
compute_time_for_current calls time_esmf_to_real