time_nc_int_2_esmf – MAPL
time_nc_int_2_esmf Subroutine
20 statements
Source File
public subroutine time_nc_int_2_esmf(time, tunit, n, rc)
Uses
ESMF
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(out) :: time
character(len=*), intent(in) :: tunit
integer, intent(in) :: n
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine time_nc_int_2_esmf(time, tunit, n, rc)
    use ESMF
    implicit none
    type(ESMF_TIME), intent(out) :: time
    integer, intent(in) :: n
    character(len=*), intent(in) :: tunit
    integer, intent(out), optional :: rc
    integer :: status
    type(ESMF_Time) :: time0
    type(ESMF_TimeInterval) :: dt
    integer :: iyy,imm,idd,ih,im,is
    call parse_timeunit(tunit, n, time0, dt, _RC)
    time = time0 + dt
    ! check
    ! -----
    call ESMF_timeGet(time, yy=iyy, mm=imm, dd=idd, h=ih, m=im, s=is, _RC)
    write(6, *) 'obs_start: iyy,imm,idd,ih,im,is', iyy,imm,idd,ih,im,is
    _RETURN(_SUCCESS)
  end subroutine time_nc_int_2_esmf
Call graph
time_nc_int_2_esmf calls ESMF_TimeGet, parse_timeunit, mapl_return, mapl_verify
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_timeunit_i4 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
parse_timeunit_i8 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_time_nc2esmf calls time_nc_int_2_esmf