time – MAPL
time Function
19 statements
Source File
function time(benchmark, comm, rc)
Arguments
Type Intent Optional Attributes Name
type(BW_Benchmark), intent(in) :: benchmark
integer, intent(in) :: comm
integer, intent(out), optional :: rc
Return Value real
Calls
Contents
Source Code
time
Source Code
   real function time(benchmark, comm, rc)
      type(BW_Benchmark), intent(in) :: benchmark
      integer, intent(in) :: comm
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: rank
      integer(kind=INT64) :: c0, c1, count_rate
      call MPI_Barrier(comm, _IERROR)
      call system_clock(c0)
      call benchmark%run(_RC)
      call MPI_Barrier(comm, _IERROR)
      call system_clock(c1, count_rate=count_rate)
      time = real(c1-c0)/count_rate
      _RETURN(_SUCCESS)
   end function time
Call graph
time calls mpi_barrier, mapl_return, mapl_verify, run
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls mapl_return, mapl_verify, mpi_comm_rank, mpi_comm_size, mpi_comm_split, make_bw_benchmark, report, write_header
get_error_message calls at
make_bw_benchmark calls mapl_return, mapl_verify, mpi_comm_rank, buffer, make_filename
mapl_throw_exception calls initialize
report calls mapl_return, mapl_verify, mpi_comm_rank, mpi_comm_size
write_header calls mapl_return, mapl_verify, mpi_comm_rank
make_filename calls mapl_return, mapl_verify