time – MAPL
time Function
18 statements
Source File
function time(kernel, comm, rc)
Arguments
Type Intent Optional Attributes Name
type(GathervKernel), intent(in) :: kernel
integer, intent(in) :: comm
integer, intent(out), optional :: rc
Return Value real
Calls
Contents
Source Code
time
Source Code
   real function time(kernel, comm, rc)
      type(GathervKernel), intent(in) :: kernel
      integer, intent(in) :: comm
      integer, optional, intent(out) :: rc
      integer :: status
      real :: t0, t1
      call MPI_Barrier(comm, _IERROR)
      t0 = MPI_Wtime()
      call kernel%run(_RC)
      call MPI_Barrier(comm, _IERROR)
      t1 = MPI_Wtime()
      time = t1 - t0
      _RETURN(_SUCCESS)
   end function time
Call graph
time calls mpi_barrier, mpi_wtime, mapl_return, mapl_verify, run
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
run calls mapl_return, mapl_verify, mpi_comm_rank, mpi_comm_size, mpi_comm_split, make_gathervkernel, report, write_header
get_error_message calls at
make_gathervkernel calls mapl_return, mapl_verify, mpi_comm_size, init
mapl_throw_exception calls initialize
report calls mapl_return, mapl_verify, mpi_comm_rank, mpi_comm_size
write_header calls mapl_return, mapl_verify, mpi_comm_rank