time_real_to_ESMF – MAPL
time_real_to_ESMF Subroutine
23 statements
Source File
public subroutine time_real_to_ESMF(times_R8_1d, times_esmf_1d, datetime_units, rc)
Uses
MAPL_NetCDF
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(in) :: times_R8_1d(:)
type(ESMF_Time), intent(inout) :: times_esmf_1d(:)
character(len=*), intent(in) :: datetime_units
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine time_real_to_ESMF (times_R8_1d, times_esmf_1d, datetime_units, rc)
    use  MAPL_NetCDF, only : convert_NetCDF_DateTime_to_ESMF
    real(kind=REAL64), intent(in) :: times_R8_1d(:)
    type(ESMF_Time), intent(inout) :: times_esmf_1d(:)
    character(len=*), intent(in) :: datetime_units
    integer, optional, intent(out) :: rc
    type(ESMF_TimeInterval) :: interval
    type(ESMF_Time) :: time0
    type(ESMF_Time) :: time1
    character(len=:), allocatable :: tunit
    integer :: i, len
    integer :: int_time
    integer :: status
    len = size (times_R8_1d)
    do i=1, len
       int_time = times_R8_1d(i)
       call convert_NetCDF_DateTime_to_ESMF(int_time, datetime_units, interval, &
            time0, time=time1, time_unit=tunit, _RC)
       times_esmf_1d(i) = time1
    enddo
    _RETURN(_SUCCESS)
  end subroutine time_real_to_ESMF
Call graph
time_real_to_esmf calls convert_netcdf_datetime_to_esmf, mapl_return, mapl_verify
convert_netcdf_datetime_to_esmf calls get_esmf_time_from_netcdf_datetime_integer, get_esmf_time_from_netcdf_datetime_real
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
get_esmf_time_from_netcdf_datetime_integer calls mapl_return, mapl_verify, convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, mapl_assert, set_esmf_timeinterval, set_esmf_time_from_iso8601
get_esmf_time_from_netcdf_datetime_real calls mapl_return, mapl_verify, convert_cf_time_to_datetime_duration, extract_cf_time_unit, extract_iso8601_from_cf_time, mapl_assert, set_esmf_timeinterval, set_esmf_time_from_iso8601
mapl_throw_exception calls initialize
convert_cf_time_to_datetime_duration calls convert_cf_time_to_datetime_duration_integer, convert_cf_time_to_datetime_duration_integer_duration, convert_cf_time_to_datetime_duration_real, convert_cf_time_to_datetime_duration_real_duration
extract_cf_time_unit calls extract_cf_time_unit_cf_time, extract_cf_time_unit_units
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time, extract_iso8601_from_cf_time_units
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
set_esmf_timeinterval calls set_esmf_timeinterval_from_datetime_duration
set_esmf_time_from_iso8601 calls mapl_return, mapl_verify, ESMF_TimeSet