time_esmf_2_nc_int – MAPL
time_esmf_2_nc_int Subroutine
20 statements
Source File
public subroutine time_esmf_2_nc_int(time, tunit, n, rc)
Uses
ESMF
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(in) :: time
character(len=*), intent(in) :: tunit
integer(kind=ESMF_KIND_I8), intent(out) :: n
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine time_esmf_2_nc_int(time, tunit, n, rc)
    use ESMF
    implicit none
    type(ESMF_TIME), intent(in) :: time
    integer(ESMF_KIND_I8), intent(out) :: n
    character(len=*), intent(in) :: tunit
    integer, intent(out), optional :: rc
    integer :: status
    type(ESMF_Time) :: time0
    type(ESMF_TimeInterval) :: dt
    character(len=ESMF_MAXSTR) :: STR1
    n=0
    call parse_timeunit(tunit, n, time0, dt, _RC)
    dt = time - time0
!    ! test
!    write(6, '(2x,a,2x,a)') 'tunit=', trim(tunit)
!    call ESMF_TimeGet(time, timestring=STR1, _RC)
!    write(6, '(2x,a,2x,a)') 'time=', trim(STR1)
!    call ESMF_TimeGet(time0, timestring=STR1, _RC)
!    write(6, '(2x,a,2x,a)') 'time0=', trim(STR1)
    ! assume unit is second
    !
    call ESMF_TimeIntervalGet(dt, s_i8=n, _RC)
    _RETURN(_SUCCESS)
  end subroutine time_esmf_2_nc_int
Call graph
time_esmf_2_nc_int calls ESMF_TimeIntervalGet, parse_timeunit, mapl_return, mapl_verify
parse_timeunit calls parse_timeunit_i4, parse_timeunit_i8
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
parse_timeunit_i4 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
parse_timeunit_i8 calls mapl_return, mapl_verify, ESMF_CalendarCreate, ESMF_TimeIntervalSet, ESMF_TimeSet, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
convert_time_esmf2nc calls time_esmf_2_nc_int
create_grid calls time_esmf_2_nc_int
get_x_subset calls time_esmf_2_nc_int
get_xy_subset calls time_esmf_2_nc_int
initialize_from_config_with_prefix calls time_esmf_2_nc_int