to_string – MAPL
to_string Function
7 statements
Source File
private function to_string(this) result(string)
Type Bound
MpiSocket
Arguments
Type Intent Optional Attributes Name
class(MpiSocket), intent(in) :: this
Return Value character(len=:), allocatable
Calls
Contents
Source Code
to_string
Source Code
   function to_string(this) result(string)
      class (MpiSocket), intent(in) :: this
      character(len=:), allocatable :: string
      string = 'MpiSocket::info' // new_line('a')
      string = string // '... world local rank:  ' // i_to_string(this%world_local_rank) // new_line('a')
      string = string // '... world remote rank: ' // i_to_string(this%world_remote_rank) // new_line('a')
   end function to_string
Call graph
to_string calls i_to_string
i_to_string calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize