transpose_regrid_scalar_3d_real32 – MAPL
transpose_regrid_scalar_3d_real32 Subroutine
64 statements
Source File
private subroutine transpose_regrid_scalar_3d_real32(this, q_in, q_out, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
real, intent(in) :: q_in(:,:,:)
real, intent(out) :: q_out(:,:,:)
integer, intent(out), optional :: rc
Calls
Contents
Source Code
transpose_regrid_scalar_3d_real32
Source Code
   subroutine transpose_regrid_scalar_3d_real32(this, q_in, q_out, rc)
      class (EsmfRegridder), intent(in) :: this
      real, intent(in) :: q_in(:,:,:)
      real, intent(out) :: q_out(:,:,:)
      integer, optional, intent(out) :: rc
      character(*), parameter :: Iam = 'MAPL_EsmfRegridder::transpose_regrid_scalar_3d_real32()'
      integer :: status
      type (RegridderSpec) :: spec
      real, pointer :: p_src(:,:,:), p_dst(:,:,:)
      type (ESMF_Field) :: src_field, dst_field
      integer :: km,kin,kout
      logical :: hasDE
      type(ESMF_VM) :: vm
      call ESMF_VMGetCurrent(vm,rc=status)
      _VERIFY(status)
      spec = this%get_spec()
      km = size(q_in,3)
      _ASSERT(km == size(q_out,3),'inconsistent array shape')
      HasDE = MAPL_GridHasDE(spec%grid_out,rc=status)
      _VERIFY(status)
      if (hasDE) then
         km = size(q_in,3)
      else
         km = 0
      end if
      call ESMF_VMAllReduce(vm,sendData=km,recvData=kin,reduceFlag=ESMF_REDUCE_MAX,rc=status)
      _VERIFY(status)
      if (hasDE) then
          _ASSERT(kin == size(q_in,3),'inconsistent array shape')
      end if
      src_field = ESMF_FieldCreate(spec%grid_out, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=[2,3],ungriddedLBound=[1],ungriddedUBound=[kin],&
                  rc=status)
      if (HasDE) then
         call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
         _VERIFY(status)
         p_src = reshape(q_in,shape(p_src), order=[2,3,1])
      end if
      HasDE = MAPL_GridHasDE(spec%grid_in,rc=status)
      _VERIFY(status)
      if (hasDE) then
         km = size(q_out,3)
      else
         km = 0
      end if
      call ESMF_VMAllReduce(vm,sendData=km,recvData=kout,reduceFlag=ESMF_REDUCE_MAX,rc=status)
      _VERIFY(status)
      if (hasDE) then
          _ASSERT(kout == size(q_out,3),'inconsistent array shape')
      end if
      dst_field = ESMF_FieldCreate(spec%grid_in, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=[2,3],ungriddedLBound=[1],ungriddedUBound=[kout],&
                  rc=status)
      if (HasDE) then
         call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
         _VERIFY(status)
         p_dst = 0
      end if
      call this%do_regrid(src_field, dst_field, doTranspose=.true., rc=status)
      _VERIFY(status)
      if (HasDE) q_out = reshape(p_dst, shape(q_out), order=[3,1,2])
      call ESMF_FieldDestroy(src_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(dst_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine transpose_regrid_scalar_3d_real32
Call graph
transpose_regrid_scalar_3d_real32 calls ESMF_VMAllReduce, ESMF_VMGetCurrent, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_assert, do_regrid, mapl_gridhasde, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
do_regrid calls esmf_fieldget, get_spec, mapl_assert, mapl_verify, ESMF_FieldRegrid, select_route_handle
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
select_route_handle calls get_spec, mapl_assert, mapl_return, mapl_verify, at, create_route_handle
create_route_handle calls esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_assert, mapl_gridhasde, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, insert