transpose_regrid_scalar_2d_real32 – MAPL
transpose_regrid_scalar_2d_real32 Subroutine
38 statements
Source File
private subroutine transpose_regrid_scalar_2d_real32(this, q_in, q_out, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
real(kind=REAL32), intent(in) :: q_in(:,:)
real(kind=REAL32), intent(out) :: q_out(:,:)
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine transpose_regrid_scalar_2d_real32(this, q_in, q_out, rc)
      class (EsmfRegridder), intent(in) :: this
      real(kind=REAL32), intent(in) :: q_in(:,:)
      real(kind=REAL32), intent(out) :: q_out(:,:)
      integer, optional, intent(out) :: rc
      character(*), parameter :: Iam = 'MAPL_EsmfRegridder::transpose_regrid_scalar_2d_real32()'
      integer :: status
      type (RegridderSpec) :: spec
      real, pointer :: p_src(:,:), p_dst(:,:)
      type (ESMF_Field) :: src_field, dst_field
      logical :: HasDE
      spec = this%get_spec()
      src_field = ESMF_FieldCreate(spec%grid_out, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=[1,2],&
                  rc=status)
      HasDE = MAPL_GridHasDE(spec%grid_out,rc=status)
      _VERIFY(status)
      if (HasDE) then
         call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
         _VERIFY(status)
         p_src = q_in
      end if
      dst_field = ESMF_FieldCreate(spec%grid_in, typekind=ESMF_TYPEKIND_R4, &
                  gridToFieldMap=[1,2],&
                  rc=status)
      HasDE = MAPL_GridHasDE(spec%grid_in,rc=status)
      _VERIFY(status)
      if (HasDE) then
         call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
         _VERIFY(status)
         p_dst = MAPL_UNDEF
      end if
      call this%do_regrid(src_field, dst_field, doTranspose=.true., rc=status)
      _VERIFY(status)
      if (hasDE) q_out = p_dst
      call ESMF_FieldDestroy(src_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(dst_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine transpose_regrid_scalar_2d_real32
Call graph
transpose_regrid_scalar_2d_real32 calls esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, do_regrid, get_spec, mapl_gridhasde, mapl_return, mapl_verify
do_regrid calls esmf_fieldget, get_spec, mapl_verify, ESMF_FieldRegrid, mapl_assert, select_route_handle
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
mapl_throw_exception calls initialize
select_route_handle calls get_spec, mapl_return, mapl_verify, mapl_assert, create_route_handle, m_at
create_route_handle calls esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_gridhasde, mapl_return, mapl_verify, mapl_assert, ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, ESMF_GridGetItem, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception