transpose_regrid_vector_2d_real32 – MAPL
transpose_regrid_vector_2d_real32 Subroutine
71 statements
Source File
private subroutine transpose_regrid_vector_2d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
Type Bound
EsmfRegridder
Arguments
Type Intent Optional Attributes Name
class(EsmfRegridder), intent(in) :: this
real, intent(in) :: u_in(:,:)
real, intent(in) :: v_in(:,:)
real, intent(out) :: u_out(:,:)
real, intent(out) :: v_out(:,:)
logical, intent(in), optional :: rotate
integer, intent(out), optional :: rc
Calls
Contents
Source Code
transpose_regrid_vector_2d_real32
Source Code
   subroutine transpose_regrid_vector_2d_real32(this, u_in, v_in, u_out, v_out, rotate, rc)
      class (EsmfRegridder), intent(in) :: this
      real, intent(in) :: u_in(:,:)
      real, intent(in) :: v_in(:,:)
      real, intent(out) :: u_out(:,:)
      real, intent(out) :: v_out(:,:)
      logical, optional, intent(in) :: rotate
      integer, optional, intent(out) :: rc
      character(*), parameter :: Iam = 'MAPL_EsmfRegridder::transpose_regrid_vector_2d_real32()'
      integer :: status
      type (RegridderSpec) :: spec
      class (AbstractGridFactory), pointer :: factory
      real, pointer :: p_src(:,:,:,:), p_dst(:,:,:,:)
      type (ESMF_Field) :: src_field, dst_field
      character(len=ESMF_MAXSTR) :: grid_axis_in, grid_axis_out
      integer :: im_src, jm_src
      integer :: im_dst, jm_dst
      logical :: HasDE
      spec = this%get_spec()
      im_src = size(u_in,1)
      jm_src = size(u_in,2)
      _ASSERT(im_src == size(v_in,1),'inconsistent array shape')
      _ASSERT(jm_src == size(v_in,2),'inconsistent array shape')
      im_dst = size(u_out,1)
      jm_dst = size(u_out,2)
      _ASSERT(im_dst == size(v_out,1),'inconsistent array shape')
      _ASSERT(jm_dst == size(v_out,2),'inconsistent array shape')
      grid_axis_in = 'north-south'
      grid_axis_out = 'north-south'
      if (present(rotate)) then
         if (rotate) then
            grid_axis_in = 'grid'
            grid_axis_out = 'xyz'
         end if
      end if
      factory => grid_manager%get_factory(spec%grid_out,rc=status)
      _VERIFY(status)
      hasDE = MAPL_GridHasDE(spec%grid_out,rc=status)
      _VERIFY(status)
      src_field = ESMF_FieldCreate(spec%grid_out, typekind = ESMF_TYPEKIND_R4, &
           & gridToFieldMap=[3,4],ungriddedLBound=[1,1],ungriddedUBound=[3,1],rc=status)
      _VERIFY(status)
      if (hasDE) then
         call ESMF_FieldGet(src_field,localDE=0,farrayPtr=p_src,rc=status)
         _VERIFY(status)
         call factory%spherical_to_cartesian(u_in, v_in, p_src, grid_axis_in, rc=status)
         _VERIFY(status)
      end if
      hasDE = MAPL_GridHasDE(spec%grid_in,rc=status)
      _VERIFY(status)
      dst_field = ESMF_FieldCreate(spec%grid_in, typekind = ESMF_TYPEKIND_R4, &
           & gridToFieldMap=[3,4],ungriddedLBound=[1,1],ungriddedUBound=[3,1],rc=status)
      _VERIFY(status)
      if (hasDE) then
         call ESMF_FieldGet(dst_field,localDE=0,farrayPtr=p_dst,rc=status)
         _VERIFY(status)
         p_dst = 0
      end if
      call this%do_regrid(src_field, dst_field, doTranspose=.true., rc=status)
      _VERIFY(status)
      factory => grid_manager%get_factory(spec%grid_in,rc=status)
      _VERIFY(status)
      if (hasDE) then
         call factory%cartesian_to_spherical(p_dst, u_out, v_out, grid_axis_out, rc=status)
         _VERIFY(status)
      end if
      call ESMF_FieldDestroy(src_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      call ESMF_FieldDestroy(dst_field, noGarbage=.true., rc=status)
      _VERIFY(status)
      _RETURN(ESMF_SUCCESS)
   end subroutine transpose_regrid_vector_2d_real32
Call graph
transpose_regrid_vector_2d_real32 calls cartesian_to_spherical, esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_assert, do_regrid, get_factory, mapl_gridhasde, mapl_return, mapl_verify, spherical_to_cartesian
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
do_regrid calls esmf_fieldget, get_spec, mapl_assert, mapl_verify, ESMF_FieldRegrid, select_route_handle
get_factory calls get_factory, mapl_return, mapl_verify
mapl_gridhasde calls mapl_return, mapl_verify, ESMF_DELayoutGet, ESMF_DistGridGet, ESMF_GridGet
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
select_route_handle calls get_spec, mapl_assert, mapl_return, mapl_verify, at, create_route_handle
create_route_handle calls esmf_fieldcreate, esmf_fielddestroy, esmf_fieldget, get_spec, mapl_assert, mapl_gridhasde, mapl_return, mapl_verify, ESMF_AttributeGet, ESMF_FieldRegridStore, ESMF_FieldSMMStore, insert