transposeCS – MAPL
transposeCS Subroutine
26 statements
Source File
private subroutine transposeCS(II, JJ, nX, nY, nVal, iFace)
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: II(nVal)
integer, intent(inout) :: JJ(nVal)
integer, intent(in) :: nX
integer, intent(in) :: nY
integer, intent(in) :: nVal
integer, intent(in) :: iFace
Called by
Source Code
      Subroutine transposeCS(II,JJ,nX,nY,nVal,iFace)
         Integer, Intent(In)     :: nVal
         Integer, Intent(InOut)  :: II(nVal)
         Integer, Intent(InOut)  :: JJ(nVal)
         Integer, Intent(In)     :: nX
         Integer, Intent(In)     :: nY
         Integer, Intent(In)     :: iFace
         Integer                 :: minJJ, maxJJ
         Integer                 :: II0(nVal)
         Integer                 :: JJ0(nVal)
         Integer                 :: I
         _UNUSED_DUMMY(nY)
         ! Copy input
         II0 = II
         JJ0 = JJ
         minJJ = nX*(iFace-1) + 1
         maxJJ = nX*iFace
         Do I=1,nVal
            If ((JJ0(I).ge.minJJ).and.(JJ0(I).le.maxJJ)) Then
               II(I) = JJ0(I) - minJJ + 1
               JJ(I) = II0(I) + minJJ - 1
            End If
         End Do
      End Subroutine transposeCS
Call graph
readtilefilenc_file calls transposecs
read_tempest calls readtilefilenc_file
readtilefilenc calls readtilefilenc_file
initialize_subclass calls read_tempest