tt_capacity – MAPL
tt_capacity Function
9 statements
Source File
private pure function tt_capacity(this) result(capacity)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
tt_grow_to calls tt_capacity
tt_reserve_size_kind calls tt_capacity
tt_shrink_to_fit calls tt_capacity
tt_insert_size_kind calls tt_grow_to, tt_push_back
tt_push_back calls tt_grow_to
s_insert calls tt_push_back
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert