tt_downsize – MAPL
tt_downsize Subroutine
14 statements
Source File
private subroutine tt_downsize(this, newsize)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: newsize
Called by
Call graph
tt_clear calls tt_downsize
tt_pop_back calls tt_downsize
s_clear calls tt_clear
m_clear calls s_clear