tt_insert_size_kind – MAPL
tt_insert_size_kind Subroutine
28 statements
Source File
private subroutine tt_insert_size_kind(this, index, value, unused, rc)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: index
type(pair), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Call graph
tt_insert_size_kind calls resize, tt_grow_to, tt_push_back
tt_grow_to calls tt_capacity, tt_set_capacity
tt_push_back calls resize, tt_grow_to
tt_resize_32 calls resize