tt_push_back – MAPL
tt_push_back Subroutine
10 statements
Source File
private subroutine tt_push_back(this, value, unused, rc)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(inout) :: this
type(pair), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
tt_push_back calls resize, tt_grow_to
tt_grow_to calls tt_capacity, tt_set_capacity
tt_resize_32 calls resize
s_insert calls tt_push_back
tt_insert_size_kind calls tt_push_back
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
m_deepcopy calls s_deepcopy
add_attribute_0d calls insert
add_attribute_1d calls insert
m_new_map_from_pair_array calls insert
put_datatofile calls insert
start_back calls insert
stringattributemap_deserialize calls insert