tt_reserve_32 – MAPL
tt_reserve_32 Subroutine
6 statements
Source File
private subroutine tt_reserve_32(this, capacity)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(inout) :: this
integer, intent(in) :: capacity
Calls
Called by
Call graph
tt_reserve_32 calls reserve
tt_copyfromarray calls reserve
tt_resize_size calls reserve