tt_resize_32 – MAPL
tt_resize_32 Subroutine
9 statements
Source File
private subroutine tt_resize_32(this, newsize, value, unused, rc)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(inout) :: this
integer, intent(in) :: newsize
type(pair), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
tt_resize_32 calls resize
tt_insert_size_kind calls resize, tt_push_back
tt_push_back calls resize
s_insert calls tt_push_back
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert