tt_set_capacity – MAPL
tt_set_capacity Subroutine
22 statements
Source File
private subroutine tt_set_capacity(this, capacity)
Type Bound
tVector
Arguments
Type Intent Optional Attributes Name
class(tVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Called by
Call graph
tt_grow_to calls tt_set_capacity
tt_reserve_size_kind calls tt_set_capacity
tt_shrink_to_fit calls tt_set_capacity
tt_insert_size_kind calls tt_grow_to, tt_push_back
tt_push_back calls tt_grow_to
s_insert calls tt_push_back
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert