two_integer_to_ESMF_time – MAPL
two_integer_to_ESMF_time Subroutine
20 statements
Source File
public subroutine two_integer_to_ESMF_time(time, itime, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Time), intent(out) :: time
integer, intent(in) :: itime(2)
integer, intent(out), optional :: rc
Calls
Source Code
  subroutine two_integer_to_ESMF_time(time, itime, rc)
    type(ESMF_Time), intent(out) ::   time
    integer, intent(in) :: itime(2)
    integer, intent(out), optional :: rc
    integer :: i1, i2
    integer :: yy, mm, dd, h, m, s
    integer :: status
    i1= itime(1)
    yy= i1/10000
    mm= mod(i1, 10000)/100
    dd= mod(i1, 100)
    i2= itime(2)
    h= i2/10000
    m= mod(i2, 10000)/100
    s= mod(i2, 100)
    call ESMF_TimeSet(time, yy=yy, mm=mm, dd=dd, h=h, m=m, s=s, _RC)
    _RETURN(_SUCCESS)
  end subroutine two_integer_to_ESMF_time
Call graph
two_integer_to_esmf_time calls ESMF_TimeSet, mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize