type_kind – MAPL
type_kind Function
18 statements
Source File
private function type_kind(element, rc)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: element
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Source Code
   integer function type_kind(element, rc)
      class(*), intent(in) :: element
      integer, optional, intent(out) :: rc
      select type (element)
      type is (integer(kind=INT32))
         type_kind = pFIO_INT32
      type is (integer(kind=INT64))
         type_kind = pFIO_INT64
      type is (real(kind=REAL32))
         type_kind = pFIO_REAL32
      type is (real(kind=REAL64))
         type_kind = pFIO_REAL64
      class default
         _FAIL('kind error')
      end select
      _RETURN(_SUCCESS)
   end function type_kind
Call graph
type_kind calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
new_arrayreference_0d calls type_kind
arrayreference calls new_arrayreference_0d