undelimit – MAPL
undelimit Function
14 statements
Source File
public pure function undelimit(string, delimiter) result(undelimited)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=1), intent(in) :: delimiter
Return Value character(len=len)
Called by
Contents
Source Code
undelimit
Source Code
   pure function undelimit(string, delimiter) result(undelimited)
      character(len=*), intent(in) :: string
      character, intent(in) :: delimiter
      character(len=len(string)) :: undelimited
      integer :: i
      integer :: j
      undelimited = ''
      j = 0
      do i=1,len(string)
        if(string(i:i) == delimiter) cycle
        j = j + 1
        undelimited(j:j) = string(i:i)
      end do
   end function undelimit
Call graph
parse_date calls undelimit
parse_time calls undelimit
test_undelimit calls undelimit
construct_iso8601date calls parse_date
construct_iso8601time calls parse_time
test_parse_date calls parse_date
test_parse_time calls parse_time
iso8601date calls construct_iso8601date
iso8601time calls construct_iso8601time
test_construct_iso8601time calls construct_iso8601time
construct_iso8601datetime calls iso8601date, iso8601time
convert_iso8601_to_integer_date calls iso8601date
convert_iso8601_to_integer_time calls iso8601time
test_construct_iso8601date calls iso8601date
test_iso8601datetime_getters calls iso8601date, iso8601time