undelimit_all – MAPL
undelimit_all Function
19 statements
Source File
public pure function undelimit_all(string) result(undelimited)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value character(len=len_trim)
Calls
Called by
Contents
Source Code
undelimit_all
Source Code
   pure function undelimit_all(string) result(undelimited)
      character(len=*), intent(in) :: string
      character(len=len_trim(string)) :: undelimited
      character(len=len_trim(string)) :: ljustified
      character :: ch
      integer :: trimmed_len
      integer :: i, pos
      ljustified = adjustl(string)
      trimmed_len = len_trim(ljustified)
      undelimited = ''
      pos = 0
      do i= 1, trimmed_len
         ch = ljustified(i:i)
         if(is_digit(ch)) then
            pos = pos + 1
            undelimited(pos:pos) = ch
         end if
      end do
   end function undelimit_all
Call graph
undelimit_all calls is_digit
convert_to_iso8601datetime calls undelimit_all
test_undelimit_all calls undelimit_all
test_convert_to_iso8601datetime calls convert_to_iso8601datetime