undelimit – MAPL
undelimit Function
16 statements
Source File
public pure function undelimit(string, delimiter) result(undelimited)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=1), intent(in) :: delimiter
Return Value character(len=len)
Called by
Contents
Source Code
undelimit
Source Code
   pure function undelimit(string, delimiter) result(undelimited)
      character(len=*), intent(in) :: string
      character,  intent(in) :: delimiter
      character(len=len(string)) :: undelimited
      integer :: i
      integer :: j
      undelimited = string
      if(len_trim(delimiter) <= 0) return
      undelimited = ''
      j = 0
      do i=1,len(string)
        if(string(i:i) == delimiter) cycle
        j = j + 1
        undelimited(j:j) = string(i:i)
      end do
   end function undelimit
Call graph
parse_date calls undelimit, date_fields
parse_time calls undelimit, time_fields
test_undelimit calls undelimit
construct_date_fields_string calls parse_date
construct_time_fields_string calls parse_time
test_parse_date calls parse_date
test_parse_time calls parse_time
date_fields calls construct_date_fields_string
time_fields calls construct_time_fields_string
test_are_valid_date_fields calls date_fields
test_are_valid_time_fields calls time_fields
test_construct_date_fields_null calls date_fields
test_construct_time_fields_null calls time_fields
test_get_day_field calls date_fields
test_get_hour_field calls time_fields
test_get_millisecond_field calls time_fields
test_get_minute_field calls time_fields
test_get_month_field calls date_fields
test_get_second_field calls time_fields
test_get_timezone_offset_field calls time_fields
test_get_year_field calls date_fields
test_is_valid_date calls date_fields
test_is_valid_time calls time_fields