unfind – MAPL
unfind Subroutine
6 statements
Source File
private subroutine unfind(this)
Type Bound
CFIOCollection
Arguments
Type Intent Optional Attributes Name
class(CFIOCollection), intent(inout) :: this
Calls
Contents
Source Code
unfind
Source Code
  subroutine unfind(this)
    class (CFIOCollection), intent(inout) :: this
    call ESMF_CFIODestroy(this%formatter)
    deallocate(this%formatter)
    nullify(this%formatter)
  end subroutine unfind
Call graph
unfind calls esmf_cfiodestroy
esmf_cfiodestroy calls grids, cfio_close, esmf_cfiogriddestroy, esmf_cfiovarinfodestroy, varobjs
cfio_close calls ncclos, err
esmf_cfiovarinfodestroy calls esmf_cfiogriddestroy, cnodedestroy, inodedestroy, rnodedestroy