UpdateBracketTime – MAPL
UpdateBracketTime Subroutine
395 statements
Source File
private subroutine UpdateBracketTime(item, cTime, bSide, interpTime, fileTime, file_processed, allowExtrap, rc)
Arguments
Type Intent Optional Attributes Name
type(PrimaryExport), intent(inout) :: item
type(ESMF_Time), intent(inout) :: cTime
character(len=1), intent(in) :: bSide
type(ESMF_Time), intent(inout) :: interpTime
type(ESMF_Time), intent(inout) :: fileTime
character(len=*), intent(inout) :: file_processed
logical, intent(in) :: allowExtrap
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
UpdateBracketTime
Source Code
     subroutine UpdateBracketTime(item,cTime,bSide,interpTime,fileTime,file_processed,allowExtrap,rc)
        type(PrimaryExport),                 intent(inout) :: item
        type(ESMF_Time),                     intent(inout) :: cTime
        character(len=1),                    intent(in   ) :: bSide
        type(ESMF_TIME),                     intent(inout) :: interpTime
        type(ESMF_TIME),                     intent(inout) :: fileTime
        character(len=*),                    intent(inout) :: file_processed
        logical,                             intent(in   ) :: allowExtrap
        integer, optional,                   intent(out  ) :: rc
        integer :: status
        type(ESMF_Time)                            :: newTime
        integer                                    :: curDate,curTime,n,tindex
        integer(ESMF_KIND_I4)                      :: iyr, imm, idd, ihr, imn, isc, oldYear
        integer(ESMF_KIND_I4)                      :: fyr, fmm, fdd, fhr, fmn, fsc
        type(ESMF_TimeInterval)                    :: zero
        type(ESMF_Time)                            :: fTime
        logical                                    :: UniFileClim
        type(ESMF_Time)                            :: readTime
        ! Allow for extrapolation.. up to a limit
        integer                                    :: yrOffset,yrOffsetStamp
        integer(ESMF_KIND_I4)                      :: cYearOff, refYear
        character(len=ESMF_MAXSTR)                 :: buff
        integer, parameter                         :: maxOffset=10000
        logical                                    :: found, newFile
        logical                                    :: LExtrap, RExtrap, LExact, RExact
        logical                                    :: LSide, RSide, intOK, bracketScan
        type(ESMF_Time), allocatable               :: xTSeries(:)
        type(FileMetaDataUtils), pointer           :: fdata
        call lgr%info('Updating %a1 bracket for %a',bside, trim(item%name))
        call ESMF_TimeIntervalSet(zero,_RC)
        ! Default
        fTime = cTime
        bracketScan = .False.
        ! Is there only one file for this dataset?
        if (item%frequency == zero) then
           call lgr%debug('            UpdateBracketTime: Scanning fixed file %a for side %a1', trim(item%file), bSide)
           UniFileClim = .false.
           ! if the file is constant, i.e. no tokens in in the template
           ! but it was marked as cyclic we must have a year long climatology
           ! on one file, set UniFileClim to true
           if (trim(item%cyclic)=='y') UniFileClim = .true.
           file_processed = item%file
           call MakeMetadata(file_processed,item%pfioCollection_id,fdata,_RC)
           ! Retrieve the time series
           call fdata%get_time_info(timeVector=xTSeries,rc=status)
           if (status /= ESMF_SUCCESS) then
              call lgr%error('Time vector retrieval failed on fixed file %a',trim(item%file))
              _RETURN(ESMF_FAILURE)
           end if
           call GetBracketTimeOnSingleFile(fdata,xTSeries,cTime,bSide,UniFileClim,interpTime,fileTime,tindex,allowExtrap,item%climYear,rc=status)
           if (status /= ESMF_SUCCESS) then
              call lgr%error('Bracket timing request failed on fixed file %a for side %a', trim(item%file), bSide)
              _RETURN(ESMF_FAILURE)
           end if
        else
           if (lgr%isEnabledFor(DEBUG)) then
              call lgr%debug('            UpdateBracketTime: Scanning template %a for side %a1',trim(item%file), bSide)
              call ESMF_TimeGet(ctime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,rc=status)
              call lgr%debug('       UpdateBracketTime: Target time   : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
              call ESMF_TimeGet(item%reff_time,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,rc=status)
              call lgr%debug('       UpdateBracketTime: Reference time: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
           endif
           UniFileClim = .false.
           found = .false.
           ! Start by assuming the file we want exists
           if (trim(item%cyclic)=='y') then
              ! if climatology compute year offset
              call ESMF_TimeGet(cTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
              yrOffset = item%climYear - iyr
              call OffsetTimeYear(cTime,yrOffset,fTime,rc)
           else
              yrOffset = 0
              if (item%reff_time > cTime) then
                 _FAIL('Reference time for file ' // trim(item%file) // ' is too late')
              end if
              ! This approach causes a problem if cTime and item%reff_time are too far
              ! apart - do it the hard way instead...
              ftime = item%reff_time
              n = 0
              ! SDE DEBUG: This caused problems in the past but the
              ! alternative is far too slow... need to keep an eye
              ! on this but the Max(0,...) should help.
              n = max(0,floor((cTime-item%reff_time)/item%frequency))
              if (n>0) fTime = fTime + (n*item%frequency)
              do while (.not.found)
                 ! SDE: This needs to be ">"
                 found = ((ftime + item%frequency) > ctime)
                 if (.not.found) then
                    n = n + 1
                    ftime = fTime+item%frequency
                 end if
              end do
              if (lgr%isEnabledFor(DEBUG)) then
                 call lgr%debug('            UpdateBracketTime: untemplating %a',trim(item%file))
                 call ESMF_TimeGet(cTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,rc=status)
                 call lgr%debug('     ==> Target time    : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, iMm, iDd, ihr, iMn, iSc)
                 call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,rc=status)
                 call lgr%debug('     ==> Target time    : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, iMm, iDd, ihr, iMn, iSc)
                 call ESMF_TimeIntervalGet(item%frequency,yy=iyr,mm=imm,d=idd,h=ihr,m=imn,s=isc,rc=status)
                 call lgr%debug('     ===> item%%frequency: Reference time: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, iMm, iDd, ihr, iMn, iSc)
                 call lgr%debug('     ===> # iterations until found %i5', n)
              endif
           end if
           readTime = cTime
           call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call MAPL_PackTime(curDate,iyr,imm,idd)
           call MAPL_PackTime(curTime,ihr,imn,isc)
           call fill_grads_template(file_processed,item%file,nymd=curDate,nhms=curTime,_RC)
           Inquire(FILE=trim(file_processed),EXIST=found)
           if (found) then
              call lgr%debug(' Target file for %a found and is %a', trim(item%file), trim(file_processed))
              !yrOffset = 0
           Else if (allowExtrap) then
              if (lgr%isEnabledFor(DEBUG)) then
                 call lgr%debug('            UpdateBracketTime: Target file not found: %a', trim(item%file))
                 call lgr%debug('            ==> Propagating forwards in file from reference time')
                 call ESMF_TimeGet(item%reff_time,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call lgr%debug('            ==> Reference time: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
              end if
              ! Go back to the reference time, and propagate forwards until we find
              ! the first valid file
              ftime = item%reff_time
              call ESMF_TimeGet(item%reff_time,yy=refYear,_RC)
              if (refYear.lt.1850) then
                 call lgr%info('            UpdateBracketTime: Reference year too early (%i0.4~). Aborting search for data from %a', refYear, trim(item%file))
                 _RETURN(ESMF_FAILURE)
              End If
              intOK = .True.
              found = .false.
              ! yrOffset currently tracking how far we are from the reference year
              n = 0
              yrOffset = 0
              ftime = item%reff_time
              Do While (intOK.and.(.not.found))
                 call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call MAPL_PackTime(curDate,iyr,imm,idd)
                 call MAPL_PackTime(curTime,ihr,imn,isc)
                 call fill_grads_template(file_processed,item%file,nymd=curDate,nhms=curTime,_RC)
                 Inquire(FILE=trim(file_processed),EXIST=found)
                 yrOffset = iYr-refYear
                 intOK = (abs(yrOffset)<maxOffset)
                 if (.not.found) then
                    n = n + 1
                    ftime = ftime + item%frequency
                 end if
              End Do
              if (.not.found) then
                 call lgr%error('UpdateBracketTime: Could not find data within maximum offset range from %a ',trim(item%file))
                 call lgr%error('            ==> Test year: %i0 and reference year: %i0 ', iYr, refYear)
                 call ESMF_TimeGet(item%reff_time,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call lgr%error('            ==> Reference time: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
                 call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call lgr%error('            ==> Last check    : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', iyr, imm, idd, ihr, imn, isc)
                 _RETURN(ESMF_FAILURE)
              End If
              call MakeMetadata(file_processed,item%pfioCollection_id,fdata,_RC)
              ! Retrieve the time series
              if (allocated(xTseries)) deallocate(xTseries)
              call fdata%get_time_info(timeVector=xTseries,_RC)
              ! Is this before or after our target time?
              LSide   = (bSide == "L")
              RSide   = (.not.LSide)
              LExact  = (cTime == xTSeries(1))
              LExtrap = (cTime <  xTSeries(1))
              RExact  = (cTime == xTSeries(size(xTSeries)))
              RExtrap = (cTime >  xTSeries(size(XTSeries)))
              found = .false.
              If (LExtrap.or.(LExact.and.RSide)) Then
                 call lgr%debug('            UpdateBracketTime: Extrapolating BACKWARD for bracket %a1 for file %a', bSide, trim(item%file))
                 ! We have data from future years
                 ! Advance the target time until we can have what we want
                 call ESMF_TimeGet(cTime,yy=cYearOff,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 iYr = refYear + yrOffset
                 ! Convert year offset to the future value
                 yrOffset = iYr - cYearOff
                 ! Determine the template time
                 call OffsetTimeYear(cTime,yrOffset,newTime,_RC)
                 ftime = item%reff_time
                 n = 0
                 do while (.not.found)
                    found = ((ftime + item%frequency) > newtime)
                    if (.not.found) then
                       n = n + 1
                       ftime = fTime+item%frequency
                    end if
                 end do
                 ! untemplate file
                 call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 ! Build file name
                 call MAPL_PackTime(curDate,iyr,imm,idd)
                 call MAPL_PackTime(curTime,ihr,imn,isc)
                 call fill_grads_template(file_processed,item%file,nymd=curDate,nhms=curTime,_RC)
                 call lgr%debug('            UpdateBracketTime: Testing for file %a for target time %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', &
                      & trim(file_processed), iyr, iMm, iDd, iHr, iMn, iSc)
                 Inquire(FILE=trim(file_processed),EXIST=found)
                 if (.not.found) then
                    call lgr%error('Failed to project data from %a for side %a', trim(item%file), bside)
                    _RETURN(ESMF_FAILURE)
                 End If
              ElseIf (RExtrap.or.(RExact.and.RSide)) Then
                 call lgr%debug('            UpdateBracketTime: Extrapolating FORWARD for bracket %a1 for file %a', bSide, trim(item%file))
                 ! We have data from past years
                 ! Rewind the target time until we can have what we want
                 call ESMF_TimeGet(cTime,yy=refYear,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 yrOffset = 0
                 fTime = cTime
                 ! yrOffset: Number of years added from current time to get file time
                 Do While ((.not.found).and.(abs(yrOffset).lt.maxOffset))
                    yrOffset = yrOffset - 1
                    call OffsetTimeYear(cTime,yrOffset,newTime,_RC)
                    ! Error check - if the new time is before the first file time,
                    ! all is lost
                    If (newTime.lt.xTSeries(1)) exit
                    do while (ftime > newTime)
                       fTime = fTime - item%frequency
                       n = n - 1
                    end do
                    ! untemplate file
                    call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                    call MAPL_PackTime(curDate,iyr,imm,idd)
                    call MAPL_PackTime(curTime,ihr,imn,isc)
                    call fill_grads_template(file_processed,item%file,nymd=curDate,nhms=curTime,_RC)
                    Inquire(FILE=trim(file_processed),EXIST=found)
                 End Do
                 if (.not.found) then
                    call lgr%error('Could not determine upper bounds on %a for side %a', trim(item%file), bSide)
                    _RETURN(ESMF_FAILURE)
                 End If
              Else
                 call lgr%error('Could not find appropriate file from file template %a for side %a', trim(item%file), bSide)
                 _RETURN(ESMF_FAILURE)
              End If
           End If
           ! Should now have the "correct" time
           call lgr%debug('            UpdateBracketTime: Making metadata for %a', trim(file_processed))
           call MakeMetadata(file_processed,item%pfioCOllection_id,fdata,_RC)
           ! Retrieve the time series
           if (allocated(xTseries)) deallocate(xTseries)
           call fdata%get_time_info(timeVector=xTSeries,_RC)
           ! We now have a time which, when passed to the FILE TEMPLATE, returns a valid file
           ! However, if the file template does not include a year token, then the file in
           ! question could actually be for a different year. We therefore feed the file time
           ! into the refresh template and see if the result has the same year. If it doesn't,
           ! then we can assume that the year is actually fixed, and the times in the file will
           ! correspond to the year in the refresh template. In this case, an additional year
           ! offset must be applied.
           yrOffsetStamp = 0
           buff = trim(item%refresh_template)
           buff = ESMF_UtilStringLowerCase(buff, _RC)
           If (buff /= "0" .and. index(buff,"p")==0) Then
              newTime = timestamp_(fTime,item%refresh_template,_RC)
              if (newTime .ne. fTime) Then
                 call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                 call ESMF_TimeGet(newTime,yy=fyr,mm=fmm,dd=fdd,h=fhr,m=fmn,s=fsc,_RC)
                 yrOffsetStamp = fYr - iYr
              End If
           End If
           ! try to get bracketing time on file using current time
           call GetBracketTimeOnFile(fdata,xTSeries,readTime,bSide,UniFileClim,interpTime,fileTime,tindex,yrOffsetInt=yrOffset+yrOffsetStamp,rc=status)
           found = (status==ESMF_SUCCESS)
           call lgr%debug('            UpdateBracketTime: Found status of %a~: %l1', trim(file_processed), found)
           ! if we didn't find the bracketing time look forwards or backwards depending on
           ! whether it is the right or left time
           if (.not.found) then
              call lgr%debug('            UpdateBracketTime: Scanning for bracket %a1 of %a~. RSide: %l1', bSide, trim(file_processed), (bSide=="R"))
              bracketScan = .True.
              newTime = fTime
              if (bSide == "R") then
                 found=.false.
                 newFile=allowExtrap
                 status = ESMF_SUCCESS
                 call lgr%debug('            UpdateBracketTime: Sanity check on file %a with flags: %i5 %2L1', &
                      & trim(file_processed), status, wrapArray([status==ESMF_SUCCESS, found]))
                 do while ((status==ESMF_SUCCESS).and.(.not.found))
                    ! check next time
                    newTime = fTime + item%frequency
                    if (trim(item%cyclic)=='y') then
                       call ESMF_TimeGet(fTime,yy=OldYear)
                       call ESMF_TimeGet(newTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                       if (oldyear/=iyr) then
                          call ESMF_TimeSet(newTime,yy=oldyear,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                          yrOffset = yrOffset - 1
                          call lgr%info('            UpdateBracketTime: IN clim after %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2',Oldyear,iMm,iDd,iHr,Imn,iSc)
                       end if
                    end if
                    ! untemplate file
                    call ESMF_TimeGet(newTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                    call MAPL_PackTime(curDate,iyr,imm,idd)
                    call MAPL_PackTime(curTime,ihr,imn,isc)
                    call fill_grads_template(file_processed,item%file,nymd=curDate,nhms=curTime,_RC)
                    call lgr%debug('            UpdateBracketTime: Testing for file %a for target time %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', trim(file_processed), iYr, iMm, iDd, iHr, iMn, iSc)
                    Inquire(FILE=trim(file_processed),EXIST=found)
                    If (found) Then
                       fTime = newTime
                    Else If (newFile) Then
                       ! We went RIGHT - cycle round by SUBTRACTING a year
                       yrOffset = yrOffset - 1
                       newFile = .False. ! Only one attempt
                       call OffsetTimeYear(fTime,-1,newTime,rc)
                       fTime = newTime
                    Else
                       status = ESMF_FAILURE
                    End If
                 End Do
                 if (status /= ESMF_SUCCESS) then
                    call lgr%error('ExtData could not find appropriate file from file template %a for side %a1', trim(item%file), bSide)
                    _RETURN(ESMF_FAILURE)
                 end if
              else if (bSide == "L") then
                 found=.false.
                 newFile=allowExtrap
                 status = ESMF_SUCCESS
                 do while ((status==ESMF_SUCCESS).and.(.not.found))
                    ! check next time
                    newTime = fTime - item%frequency
                    if (trim(item%cyclic)=='y') then
                       call ESMF_TimeGet(fTime,yy=OldYear)
                       call ESMF_TimeGet(newTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                       if (oldyear/=iyr) then
                          call ESMF_TimeSet(newTime,yy=oldyear,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                          yrOffset = yrOffset + 1
                       end if
                    end if
                    ! untemplate file
                    call ESMF_TimeGet(newTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                    call MAPL_PackTime(curDate,iyr,imm,idd)
                    call MAPL_PackTime(curTime,ihr,imn,isc)
                    call fill_grads_template(file_processed,item%file,nymd=curDate,nhms=curTime,_RC)
                    Inquire(FILE=trim(file_processed),EXIST=found)
                    If (found) Then
                       fTime = newTime
                    Else If (newFile) Then
                       ! We went LEFT - cycle round by ADDING a year
                       yrOffset = yrOffset + 1
                       newFile = .False. ! Only one attempt
                       call OffsetTimeYear(fTime,+1,newTime,rc)
                       fTime = newTime
                    Else
                       status = ESMF_FAILURE
                    End If
                 End Do
                 if (status /= ESMF_SUCCESS) then
                    call lgr%error('ExtData could not find appropriate file from file template %a for side %a1', trim(item%file), bSide)
                    _RETURN(ESMF_FAILURE)
                 end if
              end if
              ! fTime is now ALWAYS the time which was applied to the file template to get the current file
              call MakeMetadata(file_processed,item%pfioCollection_id,fdata,rc=status)
              if (allocated(xTSeries)) deallocate(xTSeries)
              call fdata%get_time_info(timeVector=xTSeries,_RC)
              !If (Mapl_Am_I_Root()) Write (*,'(a,a,x,a)') ' SUPERDEBUG: File/template: ',Trim(file_processed),Trim(item%refresh_template)
              ! The file template may be "hiding" a year offset from us
              yrOffsetStamp = 0
              buff = trim(item%refresh_template)
              buff = ESMF_UtilStringLowerCase(buff, _RC)
              If (buff /= "0" .and. index(buff,"p")==0 ) Then
                 newTime = timestamp_(fTime,item%refresh_template,_RC)
                 if (lgr%isEnabledFor(DEBUG)) then
                    call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                    call ESMF_TimeGet(newTime,yy=fyr,mm=fmm,dd=fdd,h=fhr,m=fmn,s=fsc,_RC)
                    call lgr%debug('            UpdateBracketTime: Template %a applied: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2 ', &
                         & trim(item%refresh_template), iyr, imm, idd, ihr, imn, isc)
                    call lgr%debug('                                                 -> %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2 on file %a', &
                         fyr, fmm, fdd, fhr, fmn, fsc, trim(file_processed))
                 End If
                 if (newTime .ne. fTime) Then
                    call ESMF_TimeGet(fTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
                    call ESMF_TimeGet(newTime,yy=fyr,mm=fmm,dd=fdd,h=fhr,m=fmn,s=fsc,_RC)
                    yrOffsetStamp = fYr - iYr
                    call lgr%debug('            UpdateBracketTime: Year offset modified from %i4 to %i4 to satisfy refresh template for %a', yrOffset, yrOffset+yrOffsetStamp, trim(file_processed))
                 End If
              End If
              ! try to get bracketing time on file using new time
              call GetBracketTimeOnFile(fdata,xTSeries,readTime,bSide,UniFileClim,interpTime,fileTime,tindex,yrOffsetInt=yrOffset+yrOffsetStamp,rc=status)
              found = (status == ESMF_SUCCESS)
              if (.not.found) then
                 call lgr%error('ExtData could not find bracketing data from file template %a for side %a1', trim(item%file), bSide)
                 _RETURN(ESMF_FAILURE)
              end if
           end if
        end if
        if (lgr%isEnabledFor(DEBUG)) then
           call lgr%debug('            UpdateBracketTime: Updated bracket %a1 for %a', bside, trim(file_processed))
           call ESMF_TimeGet(cTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('            ==> (%a1) Time Requested: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', bside, iYr, iMm, iDd, iHr, iMn, iSc)
           call ESMF_TimeGet(fileTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('            ==> (%a1) Record time   : %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', bside, iYr, iMm, iDd, iHr, iMn, iSc)
           call ESMF_TimeGet(interpTime,yy=iyr,mm=imm,dd=idd,h=ihr,m=imn,s=isc,_RC)
           call lgr%debug('            ==> (%a1) Effective time: %i0.4~-%i0.2~-%i0.2 %i0.2~:%i0.2~:%i0.2', bside, iYr, iMm, iDd, iHr, iMn, iSc)
        End If
        ! If we made it this far, then I guess we are OK?
        if (bside =='R') then
           item%tindex2=tindex
        else if (bside =='L') then
           item%tindex1=tindex
        end if
        call lgr%info(' ... file processed: %a', trim(file_processed))
        _RETURN(ESMF_SUCCESS)
     end subroutine UpdateBracketTime
Call graph
updatebrackettime calls mapl_packtime, offsettimeyear, getbrackettimeonfile, esmf_utilstringlowercase, esmf_timeset, timestamp_, esmf_timeintervalset, wraparray, mapl_return, mapl_verify, getbrackettimeonsinglefile, makemetadata, esmf_timeget, fill_grads_template, mapl_assert, esmf_timeintervalget
mapl_packtime calls mapl_packtime
offsettimeyear calls esmf_timeset, mapl_return, mapl_verify, esmf_timeget
getbrackettimeonfile calls offsettimeyear, mapl_return, mapl_verify, esmf_timeget
timestamp_ calls esmf_utilstringlowercase, esmf_timeset, mapl_return, mapl_verify, esmf_timeget, mapl_assert
wraparray calls wrap4d, wrap5d, wrap1d, wrap3d, wrap2d
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
getbrackettimeonsinglefile calls offsettimeyear, esmf_timeset, mapl_return, mapl_verify, esmf_timeget
makemetadata calls mapl_return, mapl_verify
fill_grads_template calls mapl_return, mapl_verify, esmf_timeget, mapl_assert, check_token, evaluate_token
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_assert_condition calls mapl_throw_exception
mapl_throw_exception calls initialize
evaluate_token calls skip_token
mapl_assert_return_code calls get_error_message, mapl_throw_exception
run_ calls updatebrackettime