update_status – MAPL
update_status Subroutine
30 statements
Source File
private subroutine update_status(this, rc)
Type Bound
AbstractServer
Arguments
Type Intent Optional Attributes Name
class(AbstractServer), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine update_status(this, rc)
      class(AbstractServer),intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer :: status
      type(StringInteger64MapIterator) :: iter
      !$omp critical (counter_status)
      this%status = this%status -1
      status = this%status
      !$omp flush (this)
      !$omp end critical (counter_status)
      if (status /= 0) then
        _RETURN(_SUCCESS)
      endif
      ! status ==0, means the last server thread in the backlog
      call this%clear_DataReference()
      call this%clear_RequestHandle(_RC)
      call this%set_status(UNALLOCATED)
      call this%set_AllBacklogIsEmpty(.true.)
      iter = this%prefetch_offset%begin()
      do while (iter /= this%prefetch_offset%end())
         call this%prefetch_offset%erase(iter)
         iter = this%prefetch_offset%begin()
      enddo
      iter = this%stage_offset%begin()
      do while (iter /= this%stage_offset%end())
         call this%stage_offset%erase(iter)
         iter = this%stage_offset%begin()
      enddo
      this%serverthread_done_msgs(:) = .false.
      _RETURN(_SUCCESS)
   end subroutine update_status
Call graph
update_status calls begin, clear_RequestHandle, erase, clear_datareference, mapl_return, mapl_verify, set_allbacklogisempty, set_status
clear_datareference calls at, erase, v_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
v_at_32 calls v_at_size_kind
v_erase_one calls erase
handle_done calls update_status