update_vector – MAPL
update_vector Subroutine
9 statements
Source File
private subroutine update_vector(this)
Type Bound
StateSpecification
Arguments
Type Intent Optional Attributes Name
class(StateSpecification), intent(inout), target :: this
Calls
Called by
Source Code
   subroutine update_vector(this)
      class(StateSpecification), target, intent(inout) :: this
      integer :: i, n
      call this%var_specs%clear()
      n = size(this%old_var_specs)
      do i = 1, n
         call this%var_specs%push_back(this%old_var_specs(i))
      end do
   end subroutine update_vector
Call graph
update_vector calls vector_clear, vector_push_back
vector_clear calls vector_downsize
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
mapl_statecreatefromspec calls update_vector
initialize calls mapl_statecreatefromspec