update_legacy – MAPL
update_legacy Subroutine
15 statements
Source File
private subroutine update_legacy(this)
Type Bound
StateSpecification
Arguments
Type Intent Optional Attributes Name
class(StateSpecification), intent(inout), target :: this
Calls
Called by
Source Code
   subroutine update_legacy(this)
      class(StateSpecification), target, intent(inout) :: this
      integer :: i, n
      if (associated(this%old_var_specs)) then
         do i = 1, size(this%old_var_specs)
            nullify(this%old_var_specs(i)%specPtr)
         end do
         deallocate(this%old_var_specs)
      endif
      n = this%var_specs%size()
      allocate(this%old_var_specs(n))
      do i = 1, n
         this%old_var_specs(i) = this%var_specs%of(i)
      end do
   end subroutine update_legacy
Call graph
update_legacy calls of
mapl_varspecaddreffromitemnew calls update_legacy
mapl_varspeccreateinlistnew calls update_legacy
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew
mapl_readforcingx calls mapl_varspeccreateinlistnew
mapl_stateaddexportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddimportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddinternalspec calls mapl_varspeccreateinlistnew
mapl_addexportspec calls mapl_stateaddexportspec_
mapl_addimportspec calls mapl_stateaddimportspec_
mapl_addinternalspec calls mapl_stateaddinternalspec
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
addnewspec calls mapl_addexportspec, mapl_addimportspec
setservices calls mapl_addexportspec, mapl_addinternalspec