update_height – MAPL
update_height Subroutine
17 statements
Source File
private subroutine update_height(this, pos)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: pos
Calls
Called by
Contents
Call graph
update_height calls exists
rebalance calls update_height, rot
rot calls update_height
erase_nonleaf calls rebalance
s_erase_multi calls rebalance, erase_nonleaf
s_insert calls rebalance