update_height – MAPL
update_height Subroutine
17 statements
Source File
private subroutine update_height(this, pos)
Type Bound
set2
Arguments
Type Intent Optional Attributes Name
class(set2), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: pos
Calls
Called by
Call graph
update_height calls at, set, exists
ti_at_32 calls ti_at_size_kind
ti_set_32 calls set
rebalance calls update_height, rot
rot calls update_height
erase_nonleaf calls rebalance
s_erase_multi calls rebalance, erase_nonleaf
s_insert calls rebalance
m_insert_key_value calls s_insert
m_insert_pair calls s_insert
m_of calls s_insert
m_set calls s_insert
s_deepcopy calls s_insert
destroy_rh_regen_ogrid calls m_set
initialize calls m_set
m_deepcopy calls s_deepcopy
m_erase_one calls erase
s_erase_one calls erase
s_remove calls erase