v_at_32 – MAPL
v_at_32 Function
9 statements
Source File
private function v_at_32(this, i, unused, rc) result(res)
Type Bound
MeterNodeVector
Arguments
Type Intent Optional Attributes Name
class(MeterNodeVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value class(AbstractMeterNode), pointer
Calls
Called by
Call graph
v_at_32 calls v_at_size_kind
find_child calls at
get_child calls at, find_child
accumulate calls get_child, add_child
add_child calls find_child
has_child calls find_child
test_depth_2 calls get_child, add_child
test_get_exclusive calls get_child, add_child
test_get_inclusive calls get_child, add_child
test_get_num_nodes calls get_child, add_child
test_get_num_nodes_2 calls get_child, add_child
test_node_reset calls get_child, add_child
test_percent_inclusive calls get_child, add_child
test_simple calls get_child, add_child
test_count_nodes_depth_1 calls add_child
test_next_one_child calls add_child