v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
MAPLCollectionVector
Arguments
Type Intent Optional Attributes Name
class(MAPLCollectionVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(MAPLDataCollection), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
create_bracketing_fields calls at
create_primary_field calls at
detect_metadata calls at
make_metadata calls at
makemetadata calls at
mapl_create_bundle_from_metdata_id calls at
mapl_read_bundle calls at, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls at
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls create_primary_field, makemetadata
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle