v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
CommGroupDescriptionVector
Arguments
Type Intent Optional Attributes Name
class(CommGroupDescriptionVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(CommGroupDescription), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
compute_color calls at
split calls at, compute_color
create_member_subcommunicator calls split
initialize calls split
new_multicommserver calls split
new_multigroupserver calls split