v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
CFIOCollectionVector
Arguments
Type Intent Optional Attributes Name
class(CFIOCollectionVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(CFIOCollection), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
mapl_cfiocreatefromfile calls at
mapl_cfioreadbundle calls at
mapl_cfioreadbundleread calls at
mapl_cfioreadparallel_ calls at, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle