v_at_32 – MAPL
v_at_32 Function
9 statements
Source File
private function v_at_32(this, i, unused, rc) result(res)
Type Bound
CFIOCollectionVector
Arguments
Type Intent Optional Attributes Name
class(CFIOCollectionVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(CFIOCollection), pointer
Calls
Called by
Call graph
v_at_32 calls v_at_size_kind
mapl_cfiocreatefromfile calls at
mapl_cfioreadbundle calls at
mapl_cfioreadbundleread calls at
mapl_cfioreadparallel_ calls at, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
esmf_ioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioread calls mapl_cfioreadbundle, mapl_cfioreadfield, mapl_cfioreadstate
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle
initialize_ calls mapl_cfioread
mapl_cfioreadarray2d calls mapl_cfioreadfield
mapl_cfioreadarray3d calls mapl_cfioreadfield
mapl_simplebundleread calls mapl_cfioread
test_main calls mapl_cfioread, esmf_ioread