v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
MessageVector
Arguments
Type Intent Optional Attributes Name
class(MessageVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value class(AbstractMessage), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
serialize_message_vector calls at
main calls at
create_remote_win calls serialize_message_vector
put_datatofile calls serialize_message_vector
serialize calls serialize_message_vector