v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
ClientThreadVector
Arguments
Type Intent Optional Attributes Name
class(ClientThreadVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value class(ClientThread), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
add_ext_collection calls at
add_hist_collection calls at
current calls at
finalize calls at
modify_metadata_all calls at
replace_metadata_all calls at
run calls at
terminate calls at