v_at_32 – MAPL
v_at_32 Function
9 statements
Source File
private function v_at_32(this, i, unused, rc) result(res)
Type Bound
AbstractDataReferenceVector
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReferenceVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value class(AbstractDataReference), pointer
Calls
Called by
Call graph
v_at_32 calls v_at_size_kind
clear_datareference calls at
get_datareference calls at
clean_up calls clear_datareference
get_datafrommem calls get_datareference, get_datafrommem
put_datatofile calls get_datareference
receive_output_data calls get_datareference, receive_output_data
update_status calls clear_datareference
handle_done calls update_status
handle_done_collective_prefetch calls clean_up
handle_done_collective_stage calls clean_up
start calls clean_up, put_datatofile, receive_output_data