v_at_32 – MAPL
v_at_32 Function
9 statements
Source File
private function v_at_32(this, i, unused, rc) result(res)
Type Bound
HistoryCollectionVector
Arguments
Type Intent Optional Attributes Name
class(HistoryCollectionVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(HistoryCollection), pointer
Calls
Called by
Call graph
v_at_32 calls v_at_size_kind
clear_hist_collections calls at
get_hist_collection calls at
handle_modifymetadata calls at
handle_replacemetadata calls at
historycollectionvector_serialize calls at
put_datatofile calls at, clear_hist_collections, get_hist_collection, put_datatofile
clean_up calls clear_hist_collections, put_datatofile
create_remote_win calls historycollectionvector_serialize
handle_done_stage calls clear_hist_collections, put_datatofile
start_back calls clear_hist_collections, put_datatofile
start calls clean_up, create_remote_win, put_datatofile, start_back