v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
ServerThreadVector
Arguments
Type Intent Optional Attributes Name
class(ServerThreadVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value class(ServerThread), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
clean_up calls at, clear_requesthandle
clear_requesthandle calls at
connect_to_server calls at
create_remote_win calls at
get_datafrommem calls at
get_dmessage calls at
put_datatofile calls at
receive_output_data calls at
set_collective_request calls at
start_back calls at
start calls at, start_back, clean_up, create_remote_win, put_datatofile, receive_output_data
initialize calls connect_to_server
test_connect calls connect_to_server
test_connect_multi calls connect_to_server
test_connect_swap_role calls connect_to_server
test_connect_with_unused_process calls connect_to_server
test_stress calls connect_to_server