v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
AbstractDataReferenceVector
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReferenceVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value class(AbstractDataReference), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
clear_datareference calls at
get_datareference calls at
clean_up calls clear_datareference
get_datafrommem calls get_datareference
put_datatofile calls get_datareference
receive_output_data calls get_datareference
update_status calls clear_datareference