v_at_size_kind – MAPL
v_at_size_kind Function
14 statements
Source File
private function v_at_size_kind(this, i, unused, rc) result(res)
Type Bound
IoBundleNGVector
Arguments
Type Intent Optional Attributes Name
class(IoBundleNGVector), intent(in), target :: this
integer(kind=SIZE_KIND), intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(ExtDataNG_IOBundle), pointer
Called by
Call graph
v_at_32 calls v_at_size_kind
mapl_extdataprefetch calls at
mapl_extdatareadprefetch calls at
run_ calls mapl_extdataprefetch, mapl_extdatareadprefetch