v_at_32 – MAPL
v_at_32 Function
9 statements
Source File
private function v_at_32(this, i, unused, rc) result(res)
Type Bound
ExtCollectionVector
Arguments
Type Intent Optional Attributes Name
class(ExtCollectionVector), intent(in), target :: this
integer, intent(in) :: i
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Return Value type(ExtDataCollection), pointer
Calls
Called by
Call graph
v_at_32 calls v_at_size_kind
get_datafromfile calls at
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile
handle_done_collective_prefetch calls read_and_gather, read_and_share