v_back – MAPL
v_back Function
6 statements
Source File
private function v_back(this) result(res)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(in), target :: this
Return Value type(FileMetadataUtils), pointer
Called by
Call graph
find calls v_back
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
getlevs calls find, makemetadata
make_metadata calls find
makemetadata calls find
mapl_create_bundle_from_metdata_id calls find
mapl_read_bundle calls find, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
initialize_ calls create_primary_field, getlevs, fillin_primary, makemetadata, getclimyear
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields, mapl_extdatagetfstarttime, mapl_extdataprefetch, updatebrackettime
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
get_file_bracket calls get_time_on_file
regrid_util calls main