v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
FormatterPtrVector
Arguments
Type Intent Optional Attributes Name
class(FormatterPtrVector), intent(in), target :: this
Return Value type(FormatterPtrVectorIterator)
Called by
Call graph
find calls v_begin
get_datafromfile calls find
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile
handle_done_collective_prefetch calls read_and_gather, read_and_share