v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
ESMFTimeVector
Arguments
Type Intent Optional Attributes Name
class(ESMFTimeVector), intent(in), target :: this
Return Value type(ESMFTimeVectorIterator)
Called by
Call graph
compute_time_vector calls v_begin
bundlepost calls compute_time_vector
run calls bundlepost
write_to_file calls bundlepost
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file