v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
GriddedIOitemVector
Arguments
Type Intent Optional Attributes Name
class(GriddedIOitemVector), intent(in), target :: this
Return Value type(GriddedIOitemVectorIterator)
Called by
Call graph
add_metadata_route_handle calls v_begin
append_file calls v_begin
bundlepost calls v_begin
create_bundle_rh calls v_begin
create_new_bundle calls v_begin
createfilemetadata calls v_begin
finalize calls v_begin, finalize
initialize calls v_begin, add_metadata_route_handle, create_bundle_rh, createfilemetadata
initialize_ calls v_begin
interp_accumulate_fields calls v_begin
process_data_from_file calls v_begin
regrid_accumulate_on_xsubset calls v_begin
regrid_append_file calls v_begin, regrid_append_file
create_from_bundle calls createfilemetadata
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls append_file, bundlepost, create_bundle_rh, createfilemetadata, regrid_append_file, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls create_from_bundle, mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls create_from_bundle, write_to_file
time_ave calls create_from_bundle, mapl_read_bundle, write_to_file
ut_regridding calls create_from_bundle, mapl_read_bundle, write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main