v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(in), target :: this
Return Value type(FileMetadataUtilsVectorIterator)
Called by
Call graph
find calls v_begin
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
make_metadata calls find
makemetadata calls find
mapl_create_bundle_from_metdata_id calls find
mapl_read_bundle calls find, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls makemetadata, getclimyear, getlevs, create_primary_field, fillin_primary
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields, mapl_extdatagetfstarttime, mapl_extdataprefetch, updatebrackettime
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
get_file_bracket calls get_time_on_file
regrid_util calls main