v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
providedServiceItemVector
Arguments
Type Intent Optional Attributes Name
class(providedServiceItemVector), intent(in), target :: this
Return Value type(providedServiceItemVectorIterator)
Called by
Call graph
providedserviceget calls v_begin
providedserviceset calls v_begin
mapl_genericinitialize calls providedserviceset, mapl_processserviceconnections
mapl_servicegetbundle calls providedserviceget
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_processserviceconnections calls mapl_servicegetbundle