v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
MeterNodeVector
Arguments
Type Intent Optional Attributes Name
class(MeterNodeVector), intent(in), target :: this
Return Value type(MeterNodeVectorIterator)
Called by
Call graph
get_exclusive calls v_begin
get_num_nodes calls v_begin
next calls v_begin
reset calls v_begin
get_num_meters calls get_num_nodes
test_count_nodes_depth_0 calls get_num_nodes
test_count_nodes_depth_1 calls get_num_nodes
test_get_exclusive calls get_exclusive
test_get_num_nodes calls get_num_nodes
test_get_num_nodes_2 calls get_num_nodes
test_node_reset calls reset
test_accumulate_nested calls get_num_meters
test_accumulate_sub calls get_num_meters
test_start_one calls get_num_meters