v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
RegridderVector
Arguments
Type Intent Optional Attributes Name
class(RegridderVector), intent(in), target :: this
Return Value type(RegridderVectorIterator)
Called by
Call graph
delete_regridder calls v_begin
find_prototype calls v_begin
make_regridder_ calls v_begin, find_prototype
make_regridder_from_grids calls v_begin
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
request_data_from_file calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
create_from_bundle calls createfilemetadata
initialize calls create_bundle_rh, createfilemetadata
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run calls create_bundle_rh, createfilemetadata