v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
MessageVector
Arguments
Type Intent Optional Attributes Name
class(MessageVector), intent(in), target :: this
Return Value type(MessageVectorIterator)
Called by
Call graph
clear_backlog calls v_begin
create_remote_win calls v_begin
get_datafrommem calls v_begin, get_datafrommem
handle_done calls v_begin
handle_done_prefetch calls v_begin
handle_done_stage calls v_begin
put_datatofile calls v_begin, clear_backlog
read_and_gather calls v_begin
read_and_share calls v_begin
receive_output_data calls v_begin, receive_output_data
receive calls v_begin
clean_up calls clear_backlog
handle_done_collective_prefetch calls read_and_gather, read_and_share
start calls create_remote_win, clean_up, put_datatofile, receive_output_data