v_begin – MAPL
v_begin Function
10 statements
Source File
private function v_begin(this) result(iter)
Type Bound
serviceConnectionItemVector
Arguments
Type Intent Optional Attributes Name
class(serviceConnectionItemVector), intent(in), target :: this
Return Value type(serviceConnectionItemVectorIterator)
Called by
Call graph
mapl_processserviceconnections calls v_begin
mapl_genericinitialize calls mapl_processserviceconnections
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize