v_capacity – MAPL
v_capacity Function
9 statements
Source File
private pure function v_capacity(this) result(capacity)
Type Bound
HistoryCollectionVector
Arguments
Type Intent Optional Attributes Name
class(HistoryCollectionVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
v_grow_to calls v_capacity
v_reserve_size_kind calls v_capacity
v_shrink_to_fit calls v_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
handle_addhistcollection calls v_push_back
historycollectionvector_deserialize calls v_push_back
start_back calls v_push_back
create_remote_win calls historycollectionvector_deserialize
start calls start_back