v_capacity – MAPL
v_capacity Function
9 statements
Source File
private pure function v_capacity(this) result(capacity)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
v_grow_to calls v_capacity
v_reserve_size_kind calls v_capacity
v_shrink_to_fit calls v_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
add_column calls v_push_back
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column