v_capacity – MAPL
v_capacity Function
9 statements
Source File
private pure function v_capacity(this) result(capacity)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
v_grow_to calls v_capacity
v_reserve_size_kind calls v_capacity
v_shrink_to_fit calls v_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
find calls v_push_back
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
make_metadata calls find
makemetadata calls find
mapl_create_bundle_from_metdata_id calls find
mapl_read_bundle calls find
request_data_from_file calls find