v_capacity – MAPL
v_capacity Function
9 statements
Source File
private pure function v_capacity(this) result(capacity)
Type Bound
VarspecDescriptionVector
Arguments
Type Intent Optional Attributes Name
class(VarspecDescriptionVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
v_grow_to calls v_capacity
v_reserve_size_kind calls v_capacity
v_shrink_to_fit calls v_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
addstate calls v_push_back
setservices calls addstate