v_capacity – MAPL
v_capacity Function
9 statements
Source File
private pure function v_capacity(this) result(capacity)
Type Bound
MeterNodeVector
Arguments
Type Intent Optional Attributes Name
class(MeterNodeVector), intent(in) :: this
Return Value integer(kind=SIZE_KIND)
Called by
Call graph
v_grow_to calls v_capacity
v_reserve_size_kind calls v_capacity
v_shrink_to_fit calls v_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
add_child calls v_push_back
accumulate calls add_child
test_count_nodes_depth_1 calls add_child
test_depth_2 calls add_child
test_get_exclusive calls add_child
test_get_inclusive calls add_child
test_get_num_nodes calls add_child
test_get_num_nodes_2 calls add_child
test_next_one_child calls add_child
test_node_reset calls add_child
test_percent_inclusive calls add_child
test_simple calls add_child