v_clear – MAPL
v_clear Subroutine
5 statements
Source File
private subroutine v_clear(this)
Type Bound
ESMFTimeVector
Arguments
Type Intent Optional Attributes Name
class(ESMFTimeVector), intent(inout) :: this
Calls
Called by
Call graph
v_clear calls v_downsize
define_time_variable calls v_clear
add_time_to_metadata calls define_time_variable
create_file_handle calls define_time_variable, create_file_handle
modifytime calls define_time_variable
add_metadata calls add_time_to_metadata, add_metadata
add_metadata_route_handle calls add_time_to_metadata
createfilemetadata calls add_time_to_metadata
run calls modifytime, createfilemetadata
start_new_file calls modifytime
create_from_bundle calls createfilemetadata
initialize calls add_metadata_route_handle, createfilemetadata
main calls start_new_file
time_ave calls start_new_file