v_downsize – MAPL
v_downsize Subroutine
11 statements
Source File
private subroutine v_downsize(this, newsize)
Type Bound
IoBundleNGVector
Arguments
Type Intent Optional Attributes Name
class(IoBundleNGVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: newsize
Called by
Call graph
v_clear calls v_downsize
v_pop_back calls v_downsize
mapl_extdatadestroycfio calls v_clear
run_ calls mapl_extdatadestroycfio