v_erase_one – MAPL
v_erase_one Subroutine
6 statements
Source File
private subroutine v_erase_one(this, position)
Type Bound
FormatterPtrVector
Arguments
Type Intent Optional Attributes Name
class(FormatterPtrVector), intent(inout), target :: this
type(FormatterPtrVectorIterator), intent(in) :: position
Calls
Called by
Call graph
v_erase_one calls erase
find calls erase
get_datafromfile calls find
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile