v_erase_one – MAPL
v_erase_one Subroutine
6 statements
Source File
private subroutine v_erase_one(this, position)
Type Bound
ESMF_CFIOPtrVector
Arguments
Type Intent Optional Attributes Name
class(ESMF_CFIOPtrVector), intent(inout), target :: this
type(ESMF_CFIOPtrVectorIterator), intent(in) :: position
Calls
Called by
Call graph
v_erase_one calls erase
find calls erase
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundle calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadparallel_ calls find, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle