v_erase_range – MAPL
v_erase_range Subroutine
14 statements
Source File
private subroutine v_erase_range(this, first, last)
Type Bound
FormatterPtrVector
Arguments
Type Intent Optional Attributes Name
class(FormatterPtrVector), intent(inout), target :: this
type(FormatterPtrVectorIterator), intent(in) :: first
type(FormatterPtrVectorIterator), intent(in) :: last
Called by
Call graph
find calls erase
v_erase_one calls erase
get_datafromfile calls find
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile