v_erase_one – MAPL
v_erase_one Subroutine
6 statements
Source File
private subroutine v_erase_one(this, position)
Type Bound
AbstractDataReferenceVector
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReferenceVector), intent(inout), target :: this
type(AbstractDataReferenceVectorIterator), intent(in) :: position
Calls
Called by
Call graph
v_erase_one calls erase
clear_datareference calls erase
clean_up calls clear_datareference
update_status calls clear_datareference
handle_done_collective_prefetch calls clean_up
handle_done_collective_stage calls clean_up
handle_done calls update_status
start calls clean_up