v_erase_range – MAPL
v_erase_range Subroutine
14 statements
Source File
private subroutine v_erase_range(this, first, last)
Type Bound
AbstractDataReferenceVector
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReferenceVector), intent(inout), target :: this
type(AbstractDataReferenceVectorIterator), intent(in) :: first
type(AbstractDataReferenceVectorIterator), intent(in) :: last
Called by
Call graph
clear_datareference calls erase
v_erase_one calls erase
clean_up calls clear_datareference
update_status calls clear_datareference
handle_done calls update_status
handle_done_collective_prefetch calls clean_up
handle_done_collective_stage calls clean_up
start calls clean_up