v_erase_range – MAPL
v_erase_range Subroutine
14 statements
Source File
private subroutine v_erase_range(this, first, last)
Type Bound
ESMF_CFIOPtrVector
Arguments
Type Intent Optional Attributes Name
class(ESMF_CFIOPtrVector), intent(inout), target :: this
type(ESMF_CFIOPtrVectorIterator), intent(in) :: first
type(ESMF_CFIOPtrVectorIterator), intent(in) :: last
Called by
Call graph
find calls erase
v_erase_one calls erase
mapl_cfiocreatefromfile calls find
mapl_cfioreadbundle calls find
mapl_cfioreadbundleread calls find
mapl_cfioreadparallel_ calls find, mapl_cfiocreatefromfile, mapl_cfioreadbundleread
esmf_ioread calls mapl_cfioreadbundle
mapl_cfioread calls mapl_cfioreadbundle
mapl_cfioreadparallel calls mapl_cfioreadparallel_
mapl_cfioreadfield calls mapl_cfioreadbundle
mapl_cfioreadstate calls mapl_cfioreadbundle