v_erase_range – MAPL
v_erase_range Subroutine
15 statements
Source File
private subroutine v_erase_range(this, first, last)
Type Bound
MessageVector
Arguments
Type Intent Optional Attributes Name
class(MessageVector), intent(inout), target :: this
type(MessageVectorIterator), intent(in) :: first
type(MessageVectorIterator), intent(in) :: last
Called by
Call graph
clear_backlog calls erase
destroy calls erase
get_datafrommem calls erase, get_datafrommem
handle_done_prefetch calls erase
handle_done_stage calls erase
receive calls erase
v_erase_one calls erase
clean_up calls clear_backlog
put_datatofile calls clear_backlog
receive_output_data calls destroy
start calls clean_up, put_datatofile