v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
ServerThreadVector
Arguments
Type Intent Optional Attributes Name
class(ServerThreadVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
add_connection calls v_push_back
connect_to_client calls add_connection
connect_to_server calls add_connection
new_multicommserver calls add_connection
new_multigroupserver calls add_connection
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize calls connect_to_client, connect_to_server
test_connect calls connect_to_client, connect_to_server
test_connect_multi calls connect_to_client, connect_to_server
test_connect_swap_role calls connect_to_client, connect_to_server
test_connect_with_unused_process calls connect_to_client, connect_to_server
test_stress calls connect_to_client, connect_to_server