v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
MAPLCollectionVector
Arguments
Type Intent Optional Attributes Name
class(MAPLCollectionVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
mapl_dataaddcollection calls v_push_back
initialize_ calls mapl_dataaddcollection
mapl_read_bundle calls mapl_dataaddcollection
new_extdatafilestream calls mapl_dataaddcollection
run_ calls mapl_dataaddcollection
extdatafilestream calls new_extdatafilestream
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle