v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
HistoryCollectionVector
Arguments
Type Intent Optional Attributes Name
class(HistoryCollectionVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
handle_addhistcollection calls v_push_back
historycollectionvector_deserialize calls v_push_back
start_back calls v_push_back
create_remote_win calls historycollectionvector_deserialize
start calls start_back, create_remote_win