v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
add_column calls v_push_back
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column, generate_report
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize, report_profile
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report