v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
find calls v_push_back
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
getlevs calls find, makemetadata
make_metadata calls find
makemetadata calls find
mapl_create_bundle_from_metdata_id calls find
mapl_read_bundle calls find, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
initialize_ calls makemetadata, create_primary_field, getlevs
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle