v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
GriddedIOitemVector
Arguments
Type Intent Optional Attributes Name
class(GriddedIOitemVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
create_from_bundle calls v_push_back
initialize calls v_push_back
iobundle_add_entry calls v_push_back
mapl_read_bundle calls v_push_back
run calls v_push_back
main calls create_from_bundle, mapl_read_bundle
run_ calls iobundle_add_entry
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle, mapl_read_bundle
ut_regridding calls create_from_bundle, mapl_read_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main