v_grow_to – MAPL
v_grow_to Subroutine
8 statements
Source File
private subroutine v_grow_to(this, capacity)
Type Bound
FormatterPtrVector
Arguments
Type Intent Optional Attributes Name
class(FormatterPtrVector), intent(inout) :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
v_grow_to calls v_capacity, v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
find calls v_push_back
get_datafromfile calls find
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile