v_insert_size_kind – MAPL
v_insert_size_kind Subroutine
24 statements
Source File
private subroutine v_insert_size_kind(this, index, value, unused, rc)
Type Bound
AbstractDataReferenceVector
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReferenceVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: index
class(AbstractDataReference), intent(in), target :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Call graph
v_insert_size_kind calls resize, v_grow_to, v_push_back
v_grow_to calls v_capacity, v_set_capacity
v_push_back calls resize, v_grow_to
v_resize_32 calls resize