v_iter_get – MAPL
v_iter_get Function
5 statements
Source File
private function v_iter_get(this) result(item)
Type Bound
IoBundleVectorIterator
Arguments
Type Intent Optional Attributes Name
class(IoBundleVectorIterator), intent(in) :: this
Return Value type(ExtData_IoBundle), pointer
Called by
Call graph
mapl_extdatacreatecfio calls v_iter_get
mapl_extdatadestroycfio calls v_iter_get
run_ calls v_iter_get, mapl_extdatacreatecfio, mapl_extdatadestroycfio