v_iter_get – MAPL
v_iter_get Function
5 statements
Source File
private function v_iter_get(this) result(item)
Type Bound
GriddedIOitemVectorIterator
Arguments
Type Intent Optional Attributes Name
class(GriddedIOitemVectorIterator), intent(in) :: this
Return Value type(GriddedIOitem), pointer
Called by
Call graph
add_metadata_route_handle calls v_iter_get
append_file calls v_iter_get
bundlepost calls v_iter_get
create_bundle_rh calls v_iter_get
create_new_bundle calls v_iter_get
createfilemetadata calls v_iter_get
finalize calls v_iter_get, finalize
initialize calls v_iter_get, add_metadata_route_handle, create_bundle_rh, createfilemetadata
initialize_ calls v_iter_get
interp_accumulate_fields calls v_iter_get
process_data_from_file calls v_iter_get
regrid_accumulate_on_xsubset calls v_iter_get
regrid_append_file calls v_iter_get, regrid_append_file
create_from_bundle calls createfilemetadata
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls append_file, bundlepost, create_bundle_rh, createfilemetadata, regrid_append_file, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls create_from_bundle, mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls create_from_bundle, write_to_file
time_ave calls create_from_bundle, mapl_read_bundle, write_to_file
ut_regridding calls create_from_bundle, mapl_read_bundle, write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main