v_iter_next – MAPL
v_iter_next Subroutine
4 statements
Source File
private subroutine v_iter_next(this)
Type Bound
requestedServiceItemVectorIterator
Arguments
Type Intent Optional Attributes Name
class(requestedServiceItemVectorIterator), intent(inout) :: this
Called by
Call graph
fillrequestbundle calls v_iter_next
mapl_genericinitialize calls fillrequestbundle
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize