v_iter_get – MAPL
v_iter_get Function
5 statements
Source File
private function v_iter_get(this) result(item)
Type Bound
serviceConnectionItemVectorIterator
Arguments
Type Intent Optional Attributes Name
class(serviceConnectionItemVectorIterator), intent(in) :: this
Return Value type(ServiceConnectionType), pointer
Called by
Call graph
mapl_processserviceconnections calls v_iter_get
mapl_genericinitialize calls mapl_processserviceconnections
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize