v_iter_get – MAPL
v_iter_get Function
5 statements
Source File
private function v_iter_get(this) result(item)
Type Bound
MAPLCollectionVectorIterator
Arguments
Type Intent Optional Attributes Name
class(MAPLCollectionVectorIterator), intent(in) :: this
Return Value type(MAPLDataCollection), pointer
Called by
Call graph
mapl_dataaddcollection calls v_iter_get
initialize_ calls mapl_dataaddcollection
mapl_read_bundle calls mapl_dataaddcollection
new_extdatafilestream calls mapl_dataaddcollection
run_ calls mapl_dataaddcollection
extdatafilestream calls new_extdatafilestream
main calls mapl_read_bundle
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
regrid_util calls main