v_iter_next – MAPL
v_iter_next Subroutine
4 statements
Source File
private subroutine v_iter_next(this)
Type Bound
providedServiceItemVectorIterator
Arguments
Type Intent Optional Attributes Name
class(providedServiceItemVectorIterator), intent(inout) :: this
Called by
Call graph
providedserviceget calls v_iter_next
providedserviceset calls v_iter_next
mapl_genericinitialize calls providedserviceset, mapl_processserviceconnections
mapl_servicegetbundle calls providedserviceget
initialize calls mapl_genericinitialize
initialize_ calls mapl_genericinitialize
mapl_processserviceconnections calls mapl_servicegetbundle