v_iter_get – MAPL
v_iter_get Function
5 statements
Source File
private function v_iter_get(this) result(item)
Type Bound
MessageVectorIterator
Arguments
Type Intent Optional Attributes Name
class(MessageVectorIterator), intent(in) :: this
Return Value class(AbstractMessage), pointer
Called by
Call graph
clean_up calls v_iter_get
create_remote_win calls v_iter_get
get_datafrommem calls v_iter_get, get_datafrommem
handle_done_prefetch calls v_iter_get
handle_done_stage calls v_iter_get
handle_done calls v_iter_get
put_datatofile calls v_iter_get
read_and_gather calls v_iter_get
read_and_share calls v_iter_get
receive_output_data calls v_iter_get, receive_output_data
handle_done_collective_prefetch calls read_and_gather, read_and_share
start calls clean_up, create_remote_win, receive_output_data