v_iter_next – MAPL
v_iter_next Subroutine
4 statements
Source File
private subroutine v_iter_next(this)
Type Bound
MessageVectorIterator
Arguments
Type Intent Optional Attributes Name
class(MessageVectorIterator), intent(inout) :: this
Called by
Call graph
clean_up calls v_iter_next
create_remote_win calls v_iter_next
put_datatofile calls v_iter_next
read_and_gather calls v_iter_next
read_and_share calls v_iter_next
receive_output_data calls v_iter_next, receive_output_data
handle_done_collective_prefetch calls read_and_gather, read_and_share
start calls clean_up, create_remote_win, receive_output_data