v_iter_next – MAPL
v_iter_next Subroutine
4 statements
Source File
private subroutine v_iter_next(this)
Type Bound
GriddedIOitemVectorIterator
Arguments
Type Intent Optional Attributes Name
class(GriddedIOitemVectorIterator), intent(inout) :: this
Called by
Call graph
add_metadata_route_handle calls v_iter_next
append_file calls v_iter_next
bundlepost calls v_iter_next
create_bundle_rh calls v_iter_next
create_new_bundle calls v_iter_next
createfilemetadata calls v_iter_next
finalize calls v_iter_next, finalize
initialize calls v_iter_next, add_metadata_route_handle, create_bundle_rh, createfilemetadata
initialize_ calls v_iter_next
interp_accumulate_fields calls v_iter_next
process_data_from_file calls v_iter_next
regrid_accumulate_on_xsubset calls v_iter_next
regrid_append_file calls v_iter_next, regrid_append_file
create_from_bundle calls createfilemetadata
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
regrid_accumulate_on_xysubset calls interp_accumulate_fields
run calls append_file, bundlepost, create_bundle_rh, createfilemetadata, regrid_append_file, regrid_accumulate_on_xysubset
write_to_file calls bundlepost
main calls create_from_bundle, mapl_read_bundle, write_to_file
run_ calls mapl_extdatareadprefetch
write_bundle_single_time calls create_from_bundle, write_to_file
time_ave calls create_from_bundle, mapl_read_bundle, write_to_file
ut_regridding calls create_from_bundle, mapl_read_bundle, write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main