v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
RegridderVector
Arguments
Type Intent Optional Attributes Name
class(RegridderVector), intent(inout) :: this
class(AbstractRegridder), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
add_prototype calls v_push_back
make_regridder_ calls v_push_back, initialize
make_regridder_from_grids calls v_push_back
v_insert_size_kind calls v_push_back
initialize calls add_prototype, create_bundle_rh, createfilemetadata
create_bundle_rh calls make_regridder
createfilemetadata calls make_regridder
make_regridder calls make_regridder
mapl_cfiocreatefrombundle calls make_regridder
request_data_from_file calls make_regridder
esmf_iocreate calls mapl_cfiocreatefrombundle
mapl_cfiocreate calls mapl_cfiocreatefrombundle
create_from_bundle calls createfilemetadata
mapl_cfiocreatefromfile calls make_regridder
mapl_cfiocreatefromstate calls mapl_cfiocreatefrombundle
mapl_cfioreadbundle calls make_regridder
mapl_extdataprefetch calls request_data_from_file
mapl_read_bundle calls request_data_from_file
run calls create_bundle_rh, createfilemetadata