v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
ServerThreadVector
Arguments
Type Intent Optional Attributes Name
class(ServerThreadVector), intent(inout) :: this
class(ServerThread), intent(in), target :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
add_connection calls v_push_back
v_insert_size_kind calls v_push_back
connect_to_client calls add_connection
connect_to_server calls add_connection
new_multicommserver calls add_connection
new_multigroupserver calls add_connection
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
initialize calls connect_to_client, connect_to_server
test_connect calls connect_to_client, connect_to_server
test_connect_multi calls connect_to_client, connect_to_server
test_connect_swap_role calls connect_to_client, connect_to_server
test_connect_with_unused_process calls connect_to_client, connect_to_server
test_stress calls connect_to_client, connect_to_server
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize
time_ave calls initialize
ut_regridding calls initialize