v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
GriddedIOitemVector
Arguments
Type Intent Optional Attributes Name
class(GriddedIOitemVector), intent(inout) :: this
type(GriddedIOitem), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
create_from_bundle calls v_push_back
initialize calls v_push_back
iobundle_add_entry calls v_push_back
mapl_read_bundle calls v_push_back
run calls v_push_back
v_insert_size_kind calls v_push_back
main calls create_from_bundle, mapl_read_bundle
run_ calls iobundle_add_entry
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle, mapl_read_bundle
ut_regridding calls create_from_bundle, mapl_read_bundle
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main