v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
ClientThreadVector
Arguments
Type Intent Optional Attributes Name
class(ClientThreadVector), intent(inout) :: this
class(ClientThread), intent(in), target :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
init calls v_push_back
new_clientmanager calls v_push_back
v_insert_size_kind calls v_push_back
clientmanager calls new_clientmanager
main calls init