v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(inout) :: this
class(TextColumn), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
add_column calls v_push_back
v_insert_size_kind calls v_push_back
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column, generate_report, finalize, mapl_finalize
finalize calls mapl_genericfinalize, report_profile
finalize_ calls mapl_genericfinalize
mapl_finalize calls report_global_profiler
start calls report_profile
time_ave calls generate_report, finalize, mapl_finalize
finalize_io_clients_servers calls finalize
finalize_mpi calls mapl_finalize
run calls mapl_finalize
regrid_util calls main
ut_regridding calls finalize, mapl_finalize