v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
VarspecDescriptionVector
Arguments
Type Intent Optional Attributes Name
class(VarspecDescriptionVector), intent(inout) :: this
type(VarspecDescription), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
addstate calls v_push_back
v_insert_size_kind calls v_push_back
setservices calls addstate