v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
MessageVector
Arguments
Type Intent Optional Attributes Name
class(MessageVector), intent(inout) :: this
class(AbstractMessage), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
add_data_message calls v_push_back
add_message calls v_push_back
deserialize_message_vector calls v_push_back
handle_collectiveprefetchdata calls v_push_back
handle_collectivestagedata calls v_push_back
handle_prefetchdata calls v_push_back
handle_stagedata calls v_push_back
put_datatofile calls v_push_back
send calls v_push_back
v_insert_size_kind calls v_push_back
create_remote_win calls deserialize_message_vector
deserialize calls deserialize_message_vector
receive_output_data calls add_data_message
test_handle_addextcollection calls add_message
test_handle_prefetchdata calls add_message
test_return_on_terminate calls add_message
test_return_on_terminate_b calls add_message
main calls deserialize_message_vector
start calls create_remote_win, start_back
start_back calls deserialize