v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(inout) :: this
type(FileMetadataUtils), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
find calls v_push_back
v_insert_size_kind calls v_push_back
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
make_metadata calls find
makemetadata calls find
mapl_create_bundle_from_metdata_id calls find
mapl_read_bundle calls find, mapl_create_bundle_from_metdata_id, request_data_from_file
request_data_from_file calls find
fillin_primary calls detect_metadata
get_time_on_file calls make_metadata
getclimyear calls makemetadata
getlevs calls makemetadata
initialize_ calls create_primary_field, fillin_primary, makemetadata, getclimyear, getlevs
main calls mapl_read_bundle
mapl_extdatagetfstarttime calls makemetadata
mapl_extdataprefetch calls request_data_from_file
run_ calls create_bracketing_fields, mapl_extdatagetfstarttime, mapl_extdataprefetch, updatebrackettime
updatebrackettime calls makemetadata
time_ave calls mapl_read_bundle
ut_regridding calls mapl_read_bundle
get_file_bracket calls get_time_on_file
regrid_util calls main