v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
CommGroupDescriptionVector
Arguments
Type Intent Optional Attributes Name
class(CommGroupDescriptionVector), intent(inout) :: this
type(CommGroupDescription), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
add_group_simple calls v_push_back
v_insert_size_kind calls v_push_back
ensemble_comm_splitter calls add_group
initialize calls add_group
new_multicommserver calls add_group
new_multigroupserver calls add_group
multicommserver calls new_multicommserver
multigroupserver calls new_multigroupserver
simplecommsplitter calls ensemble_comm_splitter
initialize_io_clients_servers calls initialize
initialize_ioserver calls initialize
main calls initialize
time_ave calls initialize
ut_regridding calls initialize