v_push_back – MAPL
v_push_back Subroutine
10 statements
Source File
private subroutine v_push_back(this, value, unused, rc)
Type Bound
FormatterPtrVector
Arguments
Type Intent Optional Attributes Name
class(FormatterPtrVector), intent(inout) :: this
type(NetCDF4_FileFormatter), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_push_back calls resize, v_grow_to
v_grow_to calls v_capacity, v_set_capacity
v_resize_32 calls resize
find calls v_push_back
v_insert_size_kind calls v_push_back
get_datafromfile calls find
handle_done_prefetch calls get_datafromfile
read_and_gather calls get_datafromfile
read_and_share calls get_datafromfile
handle_done_collective_prefetch calls read_and_gather, read_and_share