v_reserve_32 – MAPL
v_reserve_32 Subroutine
6 statements
Source File
private subroutine v_reserve_32(this, capacity)
Type Bound
ExtCollectionVector
Arguments
Type Intent Optional Attributes Name
class(ExtCollectionVector), intent(inout) :: this
integer, intent(in) :: capacity
Calls
Called by
Call graph
v_reserve_32 calls reserve
v_copyfromarray calls reserve
v_resize_size calls reserve