v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
MeterNodeVector
Arguments
Type Intent Optional Attributes Name
class(MeterNodeVector), intent(inout) :: this
integer, intent(in) :: newsize
class(AbstractMeterNode), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
add_child calls v_push_back
accumulate calls add_child
test_count_nodes_depth_1 calls add_child
test_depth_2 calls add_child
test_get_exclusive calls add_child
test_get_inclusive calls add_child
test_get_num_nodes calls add_child
test_get_num_nodes_2 calls add_child
test_next_one_child calls add_child
test_node_reset calls add_child
test_percent_inclusive calls add_child
test_simple calls add_child