v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
FileMetadataUtilsVector
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtilsVector), intent(inout) :: this
integer, intent(in) :: newsize
type(FileMetadataUtils), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
find calls v_push_back
create_bracketing_fields calls find
create_primary_field calls find
detect_metadata calls find
make_metadata calls find
makemetadata calls find
mapl_create_bundle_from_metdata_id calls find
mapl_read_bundle calls find
request_data_from_file calls find