v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
ClientThreadVector
Arguments
Type Intent Optional Attributes Name
class(ClientThreadVector), intent(inout) :: this
integer, intent(in) :: newsize
class(ClientThread), intent(in), optional, target :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
init calls v_push_back
new_clientmanager calls v_push_back
clientmanager calls new_clientmanager
main calls init