v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
AbstractDataReferenceVector
Arguments
Type Intent Optional Attributes Name
class(AbstractDataReferenceVector), intent(inout) :: this
integer, intent(in) :: newsize
class(AbstractDataReference), intent(in), optional, target :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
add_datareference calls v_push_back
put_datatofile calls v_push_back
create_remote_win calls add_datareference
handle_done_collective_prefetch calls add_datareference
start calls put_datatofile