v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
HistoryCollectionVector
Arguments
Type Intent Optional Attributes Name
class(HistoryCollectionVector), intent(inout) :: this
integer, intent(in) :: newsize
type(HistoryCollection), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
handle_addhistcollection calls v_push_back
historycollectionvector_deserialize calls v_push_back
start_back calls v_push_back
create_remote_win calls historycollectionvector_deserialize
start calls start_back