v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
GriddedIOitemVector
Arguments
Type Intent Optional Attributes Name
class(GriddedIOitemVector), intent(inout) :: this
integer, intent(in) :: newsize
type(GriddedIOitem), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
create_from_bundle calls v_push_back
initialize calls v_push_back
iobundle_add_entry calls v_push_back
mapl_read_bundle calls v_push_back
run calls v_push_back
main calls create_from_bundle, mapl_read_bundle
run_ calls iobundle_add_entry
write_bundle_single_time calls create_from_bundle
time_ave calls create_from_bundle, mapl_read_bundle
ut_regridding calls create_from_bundle, mapl_read_bundle