v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
RegridderVector
Arguments
Type Intent Optional Attributes Name
class(RegridderVector), intent(inout) :: this
integer, intent(in) :: newsize
class(AbstractRegridder), intent(in), optional :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
add_prototype calls v_push_back
make_regridder_ calls v_push_back
make_regridder_from_grids calls v_push_back
initialize calls add_prototype