v_resize_32 – MAPL
v_resize_32 Subroutine
9 statements
Source File
private subroutine v_resize_32(this, newsize, value, unused, rc)
Type Bound
ServerThreadVector
Arguments
Type Intent Optional Attributes Name
class(ServerThreadVector), intent(inout) :: this
integer, intent(in) :: newsize
class(ServerThread), intent(in), optional, target :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
v_resize_32 calls resize
v_insert_size_kind calls resize, v_push_back
v_push_back calls resize
add_connection calls v_push_back
connect_to_client calls add_connection
connect_to_server calls add_connection
new_multicommserver calls add_connection
new_multigroupserver calls add_connection