v_set_capacity – MAPL
v_set_capacity Subroutine
21 statements
Source File
private subroutine v_set_capacity(this, capacity)
Type Bound
HistoryCollectionVector
Arguments
Type Intent Optional Attributes Name
class(HistoryCollectionVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Called by
Call graph
v_grow_to calls v_set_capacity
v_reserve_size_kind calls v_set_capacity
v_shrink_to_fit calls v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
handle_addhistcollection calls v_push_back
historycollectionvector_deserialize calls v_push_back
start_back calls v_push_back
create_remote_win calls historycollectionvector_deserialize
start calls start_back