v_set_capacity – MAPL
v_set_capacity Subroutine
21 statements
Source File
private subroutine v_set_capacity(this, capacity)
Type Bound
TextColumnVector
Arguments
Type Intent Optional Attributes Name
class(TextColumnVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Called by
Call graph
v_grow_to calls v_set_capacity
v_reserve_size_kind calls v_set_capacity
v_shrink_to_fit calls v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
add_column calls v_push_back
generate_report calls add_column
mapl_genericfinalize calls add_column
report_global_profiler calls add_column
report_profile calls add_column
test_simple_report_timer calls add_column
test_simple_report_timer_b calls add_column
main calls add_column