v_set_capacity – MAPL
v_set_capacity Subroutine
21 statements
Source File
private subroutine v_set_capacity(this, capacity)
Type Bound
ServerThreadVector
Arguments
Type Intent Optional Attributes Name
class(ServerThreadVector), intent(inout), target :: this
integer(kind=SIZE_KIND), intent(in) :: capacity
Called by
Call graph
v_grow_to calls v_set_capacity
v_reserve_size_kind calls v_set_capacity
v_shrink_to_fit calls v_set_capacity
v_insert_size_kind calls v_grow_to, v_push_back
v_push_back calls v_grow_to
add_connection calls v_push_back
connect_to_client calls add_connection
connect_to_server calls add_connection
new_multicommserver calls add_connection
new_multigroupserver calls add_connection