var_get_missing_value – MAPL
var_get_missing_value Function
20 statements
Source File
public function var_get_missing_value(this, var_name, rc) result(missing_value)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
integer, intent(out), optional :: rc
Return Value real(kind=REAL32)
Calls
Called by
Source Code
   function var_get_missing_value(this,var_name,rc) result(missing_value)
      real(REAL32) :: missing_value
      class(FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: fname
      type(Variable), pointer :: var
      fname = this%get_file_name(_RC)
      var => this%get_variable(var_name,_RC)
      _ASSERT(associated(var),"no variable named "//var_name//" in "//fname)
      ! check _FillValue, we could do more, not sure what to do here like also check for missing_value ...
      if (this%var_has_attr(var_name,"_FillValue")) then
         missing_value = this%get_var_attr_real32(var_name,"_FillValue",_RC)
      end if
      _RETURN(_SUCCESS)
   end function var_get_missing_value
Call graph
var_get_missing_value calls mapl_assert, get_file_name, get_var_attr_real32, get_variable, mapl_return, mapl_verify, var_has_attr
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file_name calls mapl_return
get_var_attr_real32 calls mapl_assert, get_file_name, get_variable, mapl_return, mapl_verify, get_attribute_real32
get_variable calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
var_has_attr calls mapl_assert, get_file_name, get_variable, mapl_return, mapl_verify, is_attribute_present
get_attribute_real32 calls mapl_assert, mapl_return, mapl_verify, get_attribute, get_values
get_error_message calls at, insert
is_attribute_present calls mapl_return, m_at
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
get_attribute calls mapl_assert, mapl_return, m_at
get_values calls mapl_return
m_find calls s_find
swap_undef_value calls var_get_missing_value
time_ave calls var_get_missing_value, mapl_read_bundle
process_data_from_file calls swap_undef_value
mapl_extdatareadprefetch calls process_data_from_file
mapl_read_bundle calls process_data_from_file
main calls mapl_read_bundle
run_ calls mapl_extdatareadprefetch
ut_regridding calls mapl_read_bundle