var_has_attr – MAPL
var_has_attr Function
17 statements
Source File
public function var_has_attr(this, var_name, attr_name, rc)
Type Bound
FileMetadataUtils
Arguments
Type Intent Optional Attributes Name
class(FileMetadataUtils), intent(inout) :: this
character(len=*), intent(in) :: var_name
character(len=*), intent(in) :: attr_name
integer, intent(out), optional :: rc
Return Value logical
Calls
Called by
Source Code
   logical function var_has_attr(this,var_name,attr_name,rc)
      class(FileMetadataUtils), intent(inout) :: this
      character(len=*), intent(in) :: var_name
      character(len=*), intent(in) :: attr_name
      integer, optional, intent(out) :: rc
      integer :: status
      character(:), allocatable :: fname
      type(Variable), pointer :: var
      fname = this%get_file_name(_RC)
      var => this%get_variable(var_name,_RC)
      _ASSERT(associated(var),"no variable named "//var_name//" in "//fname)
      var_has_attr = var%is_attribute_present(attr_name)
      _RETURN(_SUCCESS)
   end function var_has_attr
Call graph
var_has_attr calls mapl_assert, get_file_name, get_variable, is_attribute_present, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_file_name calls mapl_return
get_variable calls mapl_return, m_at
is_attribute_present calls mapl_return, m_at
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_at calls m_find
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
m_find calls s_find
get_coordinate_info calls var_has_attr
getlevs calls var_has_attr, get_coordinate_info
var_get_missing_value calls var_has_attr
get_file_levels calls get_coordinate_info
get_time_info calls get_coordinate_info
initialize_ calls getlevs, get_coordinate_info, getclimyear
swap_undef_value calls var_get_missing_value
time_ave calls get_coordinate_info, var_get_missing_value, get_file_levels, get_file_times, mapl_read_bundle
detect_metadata calls get_time_info
get_file_times calls get_time_info
get_time_on_file calls get_time_info
getclimyear calls get_time_info
main calls get_file_levels, get_file_times, mapl_read_bundle, run_component_driver
mapl_extdatagetfstarttime calls get_time_info
mapl_read_bundle calls get_time_info, process_data_from_file
process_data_from_file calls swap_undef_value
run_component_driver calls get_time_info
updatebrackettime calls get_time_info
fillin_primary calls detect_metadata
get_file_bracket calls get_time_on_file
mapl_extdatareadprefetch calls process_data_from_file
run_ calls mapl_extdatagetfstarttime, updatebrackettime
regrid_util calls main
ut_regridding calls mapl_read_bundle