varIsConnected_name – MAPL
varIsConnected_name Function
30 statements
Source File
private function varIsConnected_name(this, IMPORT_NAME, import, RC)
Type Bound
VarConn
Arguments
Type Intent Optional Attributes Name
class(VarConn), intent(inout), target :: this
character(len=*), intent(in) :: IMPORT_NAME
integer, intent(in) :: import
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Source Code
   logical function varIsConnected_name(this, IMPORT_NAME, import, RC)
      class(VarConn), target, intent(inout):: this
      character (len=*),           intent(IN   ) :: IMPORT_NAME
      integer,                     intent(in   ) :: import
      integer,           optional, intent(  OUT) :: RC     ! Error code:
      integer                               :: I
      integer                               :: TI
      type(VarConnType), pointer :: conn
      character(len=ESMF_MAXSTR) :: name
      varIsConnected_name = .false.
      associate (conn_v => this%conn_v)
        ! try to find a match with "TO"
        do I = 1, conn_v%size()
           conn => conn_v%of(i)
           name = conn%to%get_short_name()
           if (name /= IMPORT_NAME) then
              cycle
           end if
           TI = conn%to%get_gc_id()
           if (TI /= import) then
              cycle
           end if
           varIsConnected_name = .true.
           _RETURN(ESMF_SUCCESS)
        end do
      end associate
      varIsConnected_name = .false.
      _RETURN(ESMF_SUCCESS)
   end function VarIsConnected_Name
Call graph
varisconnected_name calls of, get_gc_id, get_short_name, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_terminateimportallbut calls varisconnected
mapl_wirecomponent calls varisconnected
mapl_terminateimport calls mapl_terminateimportallbut
mapl_genericsetservices calls mapl_wirecomponent
mapl_terminateimportall calls mapl_terminateimport
setservices calls mapl_genericsetservices