varIsConnected_IE – MAPL
varIsConnected_IE Function
40 statements
Source File
private function varIsConnected_IE(this, IMPORT_NAME, EXPORT_NAME, IMPORT, EXPORT, RC)
Type Bound
VarConn
Arguments
Type Intent Optional Attributes Name
class(VarConn), intent(inout), target :: this
character(len=*), intent(in) :: IMPORT_NAME
character(len=*), intent(out), optional :: EXPORT_NAME
integer, intent(in) :: IMPORT
integer, intent(in) :: EXPORT
integer, intent(out), optional :: RC
Return Value logical
Calls
Source Code
   logical function varIsConnected_IE(this, IMPORT_NAME, EXPORT_NAME, &
        import, EXPORT, RC)
      class(VarConn), target, intent(inout) :: this
      character (len=*),           intent(IN   ) :: IMPORT_NAME
      character (len=*), optional, intent(  OUT) :: EXPORT_NAME
      integer,                     intent(IN   ) :: IMPORT
      integer,                     intent(IN   ) :: EXPORT
      integer,           optional, intent(  OUT) :: RC     ! Error code:
      integer                               :: I
      integer                               :: TI, FE
      type(VarConnType), pointer :: conn
      character(len=ESMF_MAXSTR) :: name
      varIsConnected_IE = .false.
      ! try to find a match with "TO"
      associate (conn_v => this%conn_v)
        do I = 1, conn_v%size()
           conn => conn_v%of(i)
           name = conn%TO%get_short_name()
           if (name /= IMPORT_NAME) then
              cycle
           end if
           TI = conn%to%get_gc_id()
           FE = conn%from%get_gc_id()
           if (TI /= import) then
              cycle
           end if
           if (FE /= EXPORT) then
              cycle
           end if
           varIsConnected_IE = .true.
           conn%used = .true.
           if (present(EXPORT_NAME)) then
              EXPORT_NAME = conn%FROM%get_short_name()
           end if
           _RETURN(ESMF_SUCCESS)
        end do
      end associate
      varIsConnected_IE = .false.
      _RETURN(ESMF_SUCCESS)
   end function VarIsConnected_IE
Call graph
varisconnected_ie calls of, get_gc_id, get_short_name, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize