varIsListed – MAPL
varIsListed Function
29 statements
Source File
private function varIsListed(this, SHORT_NAME, IMPORT, RC)
Type Bound
VarConn
Arguments
Type Intent Optional Attributes Name
class(VarConn), intent(inout), target :: this
character(len=*), intent(in) :: SHORT_NAME
integer, intent(in) :: IMPORT
integer, intent(out), optional :: RC
Return Value logical
Calls
Called by
Source Code
   logical function varIsListed(this, SHORT_NAME, import, RC)
      class(VarConn ), target, intent(inout):: this
      character (len=*),               intent(IN) :: SHORT_NAME
      integer,                         intent(IN) :: IMPORT
      integer,              optional, intent(OUT) :: RC     ! Error code:
      type(VarConnType), pointer :: conn
      integer                               :: I
      integer                               :: TI
      character(len=ESMF_MAXSTR) :: name
      associate (conn_v => this%conn_v)
        do I = 1, conn_v%size()
           conn => conn_v%of(i)
           name = conn%FROM%get_short_name()
           if (name /= SHORT_NAME) then
              cycle
           end if
           TI = conn%to%get_gc_id()
           ! check for a match
           if(TI == import)  then
              varIsListed = .true.
              conn%used = .true.
              _RETURN(ESMF_SUCCESS)
           end if
        end do
      end associate
      varIsListed = .false.
      _RETURN(ESMF_SUCCESS)
   end function VarIsListed
Call graph
varislisted calls of, get_gc_id, get_short_name, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_wirecomponent calls varislisted
mapl_genericsetservices calls mapl_wirecomponent
setservices calls mapl_genericsetservices