vector_riter_next_1 – MAPL
vector_riter_next_1 Function
6 statements
Source File
private function vector_riter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
Return Value type(VectorRIterator)
Calls
Called by
Contents
Call graph
vector_riter_next_1 calls next
next calls vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind, vector_iter_next_1
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add
vector_find_if_not calls next
vector_find_if calls next
vector_iter_next_1 calls next
vector_reverse_find_if_not calls next
vector_reverse_find_if calls next
find_if_not calls vector_find_if_not, vector_reverse_find_if_not
find_if calls vector_find_if, vector_reverse_find_if