vector_downsize – MAPL
vector_downsize Subroutine
11 statements
Source File
private recursive subroutine vector_downsize(this, newsize)
Type Bound
MeterNodeStack
Arguments
Type Intent Optional Attributes Name
class(MeterNodeStack), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: newsize
Called by
Call graph
vector_clear calls vector_downsize
vector_pop_back calls vector_downsize
finalize calls vector_pop_back, finalize_global_time_profiler
stop_node calls vector_pop_back
finalize_global_memory_profiler calls finalize
finalize_global_time_profiler calls finalize
test_accumulate_multi calls finalize
test_accumulate_nested calls finalize
test_accumulate_sub calls finalize
test_simple_report_timer calls finalize
test_simple_report_timer_b calls finalize
test_start_one calls finalize
test_stop_wrong_meter calls finalize
main calls finalize