vector_new_vector_fill_default – MAPL
vector_new_vector_fill_default Function
7 statements
Source File
private function vector_new_vector_fill_default(n, value) result(v)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
type(MeterNodePtr), intent(in), optional :: value
Return Value type(MeterNodeStack)
Calls
Called by
Call graph
vector_new_vector_fill_default calls resize
vector_resize_size_kind calls reserve
meternodestack calls vector_new_vector_fill_default