vector_riter_advance_default – MAPL
vector_riter_advance_default Subroutine
6 statements
Source File
private subroutine vector_riter_advance_default(it, n)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(inout) :: it
integer, intent(in) :: n
Calls
Called by
Call graph
vector_riter_advance_default calls add
vector_riter_add_n_size_kind calls sub
advance calls vector_riter_advance_default