vector_riter_prev_n_size_kind – MAPL
vector_riter_prev_n_size_kind Function
8 statements
Source File
private function vector_riter_prev_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VectorRIterator)
Calls
Called by
Call graph
vector_riter_prev_n_size_kind calls sub
vector_riter_sub_n_size_kind calls add
prev calls vector_riter_prev_n_size_kind, vector_riter_prev_1, vector_iter_prev_1
vector_iter_prev_1 calls prev
vector_riter_prev_1 calls prev