vector_of_size_kind – MAPL
vector_of_size_kind Function
7 statements
Source File
private function vector_of_size_kind(this, i) result(res)
Type Bound
VarSpecVector
Arguments
Type Intent Optional Attributes Name
class(VarSpecVector), intent(in), target :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: i
Return Value type(MAPL_VarSpec), pointer
Called by
Call graph
mapl_statecreatefromspecnew calls of
mapl_statecreatefromvarspecnew calls of, mapl_statecreatefromspecnew
mapl_statesetspecattrib calls of
to_varspecptr calls of
update_legacy calls of
mapl_genericinitialize calls mapl_statecreatefromspecnew, mapl_statecreatefromvarspecnew
mapl_readforcingx calls mapl_statecreatefromvarspecnew, mapl_statesettimestamp, mapl_varspeccreateinlistnew
mapl_statecreatefromspec calls mapl_statecreatefromspecnew
mapl_statesettimestamp calls mapl_statesetspecattrib
mapl_varspecaddreffromitemnew calls update_legacy
mapl_varspeccreateinlistnew calls update_legacy
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize, mapl_statecreatefromspec
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_stateaddexportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddimportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddinternalspec calls mapl_varspeccreateinlistnew