vector_begin – MAPL
vector_begin Function
10 statements
Source File
private function vector_begin(this) result(iter)
Type Bound
MeterNodeStack
Arguments
Type Intent Optional Attributes Name
class(MeterNodeStack), intent(in), target :: this
Return Value type(MeterNodeStackIterator)
Called by
Call graph
copy_profiler calls vector_begin
print_stack calls vector_begin
vector_iter_begin calls vector_begin
vector_iter_ftn_begin calls vector_begin
vector_rend calls vector_begin
begin calls vector_iter_begin
ftn_begin calls vector_iter_ftn_begin
copy calls copy_profiler