vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
VarSpecVector
Arguments
Type Intent Optional Attributes Name
class(VarSpecVector), intent(inout) :: this
type(MAPL_VarSpec), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
mapl_varspecaddreffromitemnew calls vector_push_back
mapl_varspeccreateinlistnew calls vector_push_back
update_vector calls vector_push_back
vector_new_vector_range calls vector_push_back
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew
varspecvector calls vector_new_vector_range
mapl_readforcingx calls mapl_varspeccreateinlistnew
mapl_stateaddexportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddimportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddinternalspec calls mapl_varspeccreateinlistnew
mapl_statecreatefromspec calls update_vector
mapl_addexportspec calls mapl_stateaddexportspec_
mapl_addimportspec calls mapl_stateaddimportspec_
mapl_addinternalspec calls mapl_stateaddinternalspec
initialize calls mapl_statecreatefromspec
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx
mapl_readforcing calls mapl_readforcing1, mapl_readforcing2
addnewspec calls mapl_addexportspec, mapl_addimportspec
setservices calls mapl_addexportspec, mapl_addinternalspec