vector_riter_sub_n_size_kind – MAPL
vector_riter_sub_n_size_kind Subroutine
6 statements
Source File
private subroutine vector_riter_sub_n_size_kind(this, n)
Type Bound
VectorRIterator
Arguments
Type Intent Optional Attributes Name
class(VectorRIterator), intent(inout) :: this
integer(kind=selected_int_kind(18)), intent(in) :: n
Calls
Called by
Call graph
vector_riter_sub_n_size_kind calls add
vector_riter_prev_n_default calls sub
vector_riter_prev_n_size_kind calls sub
prev calls vector_riter_prev_n_default, vector_riter_prev_n_size_kind
vector_iter_prev_1 calls prev
vector_riter_prev_1 calls prev