vector_capacity – MAPL
vector_capacity Function
10 statements
Source File
private pure function vector_capacity(this) result(capacity)
Type Bound
VarSpecVector
Arguments
Type Intent Optional Attributes Name
class(VarSpecVector), intent(in) :: this
Return Value integer(kind=GFTL_SIZE_KIND)
Called by
Call graph
vector_grow_to calls vector_capacity
vector_reserve_size_kind calls vector_capacity
vector_shrink_to_fit calls vector_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
mapl_varspecaddreffromitemnew calls vector_push_back
mapl_varspeccreateinlistnew calls vector_push_back
update_vector calls vector_push_back
vector_copy_from_array calls reserve
vector_new_vector_range calls vector_push_back
vector_reserve_default calls reserve
vector_resize_size_kind calls reserve
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew
varspecvector calls vector_new_vector_range
mapl_readforcingx calls mapl_varspeccreateinlistnew
mapl_stateaddexportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddimportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddinternalspec calls mapl_varspeccreateinlistnew
mapl_statecreatefromspec calls update_vector
vector_insert_count_default calls insert
vector_insert_one calls insert