vector_reserve_default – MAPL
vector_reserve_default Subroutine
17 statements
Source File
private subroutine vector_reserve_default(this, capacity, unused, rc)
Type Bound
PrimaryExportVector
Arguments
Type Intent Optional Attributes Name
class(PrimaryExportVector), intent(inout) :: this
integer, intent(in) :: capacity
class(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Call graph
vector_reserve_default calls reserve, vector_max_size
vector_reserve_size_kind calls vector_max_size, vector_capacity, vector_set_capacity