vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
VarSpecVector
Arguments
Type Intent Optional Attributes Name
class(VarSpecVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
mapl_varspecaddreffromitemnew calls vector_push_back
mapl_varspeccreateinlistnew calls vector_push_back
update_vector calls vector_push_back
vector_new_vector_range calls vector_push_back
mapl_varspecaddreftolist calls mapl_varspecaddreffromitemnew
varspecvector calls vector_new_vector_range
mapl_readforcingx calls mapl_varspeccreateinlistnew
mapl_stateaddexportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddimportspec_ calls mapl_varspeccreateinlistnew
mapl_stateaddinternalspec calls mapl_varspeccreateinlistnew
mapl_statecreatefromspec calls update_vector
vector_insert_count_default calls insert
vector_insert_one calls insert
mapl_addexportspec calls mapl_stateaddexportspec_
mapl_addimportspec calls mapl_stateaddimportspec_
mapl_addinternalspec calls mapl_stateaddinternalspec
initialize calls mapl_statecreatefromspec
mapl_readforcing1 calls mapl_readforcingx
mapl_readforcing2 calls mapl_readforcingx