vector_insert_one – MAPL
vector_insert_one Function
7 statements
Source File
private recursive function vector_insert_one(this, pos, value) result(iter)
Type Bound
entryPointVector
Arguments
Type Intent Optional Attributes Name
class(entryPointVector), intent(inout), target :: this
type(entryPointVectorIterator), intent(in) :: pos
type(runEntryPoint), intent(in) :: value
Return Value type(entryPointVectorIterator)
Calls
Call graph
vector_insert_one calls insert
vector_insert_list calls vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity