vector_insert_one – MAPL
vector_insert_one Function
7 statements
Source File
private recursive function vector_insert_one(this, pos, value) result(iter)
Type Bound
VarSpecVector
Arguments
Type Intent Optional Attributes Name
class(VarSpecVector), intent(inout), target :: this
type(VarSpecVectorIterator), intent(in) :: pos
type(MAPL_VarSpec), intent(in) :: value
Return Value type(VarSpecVectorIterator)
Calls
Call graph
vector_insert_one calls insert
vector_insert_list calls vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity