vector_iter_next_1 – MAPL
vector_iter_next_1 Function
6 statements
Source File
private function vector_iter_next_1(it) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VarConnVectorIterator), intent(in) :: it
Return Value type(VarConnVectorIterator)
Calls
Called by
Contents
Call graph
vector_iter_next_1 calls next
next calls vector_riter_next_1, vector_riter_next_n_default, vector_riter_next_n_size_kind, vector_iter_next_1
vector_riter_next_1 calls next
vector_riter_next_n_default calls add
vector_riter_next_n_size_kind calls add