vector_riter_next_n_size_kind – MAPL
vector_riter_next_n_size_kind Function
8 statements
Source File
private function vector_riter_next_n_size_kind(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Return Value type(VectorRIterator)
Calls
Called by
Contents
Call graph
vector_riter_next_n_size_kind calls add
next calls vector_riter_next_n_size_kind, vector_riter_next_1, vector_iter_next_1
vector_find_if_not calls next
vector_find_if calls next
vector_iter_next_1 calls next
vector_reverse_find_if_not calls next
vector_reverse_find_if calls next
vector_riter_next_1 calls next
find_if_not calls vector_find_if_not, vector_reverse_find_if_not
find_if calls vector_find_if, vector_reverse_find_if