vector_push_back – MAPL
vector_push_back Subroutine
10 statements
Source File
private recursive subroutine vector_push_back(this, value, unused, rc)
Type Bound
entryPointVector
Arguments
Type Intent Optional Attributes Name
class(entryPointVector), intent(inout) :: this
type(runEntryPoint), intent(in) :: value
type(KeywordEnforcer), intent(in), optional :: unused
integer, intent(out), optional :: rc
Calls
Called by
Call graph
vector_push_back calls resize, vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity
vector_resize_size_kind calls reserve
mapl_gridcompsetentrypoint calls vector_push_back
vector_new_vector_range calls vector_push_back
entrypointvector calls vector_new_vector_range
mapl_genericsetservices calls mapl_gridcompsetentrypoint
setservices calls mapl_gridcompsetentrypoint, mapl_genericsetservices