vector_riter_next_n_default – MAPL
vector_riter_next_n_default Function
8 statements
Source File
private function vector_riter_next_n_default(it, n) result(new_it)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(in) :: it
integer, intent(in) :: n
Return Value type(VectorRIterator)
Calls
Called by
Call graph
vector_riter_next_n_default calls add
vector_riter_add_n_size_kind calls sub
next calls vector_riter_next_n_default, vector_riter_next_1, vector_iter_next_1
vector_iter_next_1 calls next
vector_riter_next_1 calls next