vector_riter_advance_size_kind – MAPL
vector_riter_advance_size_kind Subroutine
6 statements
Source File
private subroutine vector_riter_advance_size_kind(it, n)
Arguments
Type Intent Optional Attributes Name
type(VectorRIterator), intent(inout) :: it
integer(kind=selected_int_kind(18)), intent(in) :: n
Calls
Called by
Call graph
vector_riter_advance_size_kind calls add
vector_riter_add_n_size_kind calls sub
advance calls vector_riter_advance_size_kind