vector_insert_one – MAPL
vector_insert_one Function
7 statements
Source File
private recursive function vector_insert_one(this, pos, value) result(iter)
Type Bound
VarConnVector
Arguments
Type Intent Optional Attributes Name
class(VarConnVector), intent(inout), target :: this
type(VarConnVectorIterator), intent(in) :: pos
type(VarConnType), intent(in) :: value
Return Value type(VarConnVectorIterator)
Calls
Call graph
vector_insert_one calls insert
vector_insert_list calls vector_grow_to
vector_grow_to calls vector_capacity, vector_set_capacity