vector_max_size – MAPL
vector_max_size Function
6 statements
Source File
private pure function vector_max_size() result(res)
Type Bound
DerivedExportVector
Arguments
None
Return Value integer(kind=GFTL_SIZE_KIND)
Called by
Call graph
vector_reserve_default calls vector_max_size, reserve
vector_reserve_size_kind calls vector_max_size
vector_copy_from_array calls reserve
vector_resize_size_kind calls reserve