vector_back – MAPL
vector_back Function
6 statements
Source File
private function vector_back(this) result(res)
Type Bound
VarConnVector
Arguments
Type Intent Optional Attributes Name
class(VarConnVector), intent(in), target :: this
Return Value type(VarConnType), pointer
Called by
Call graph
append calls vector_back
mapl_addconnectivitye2e calls append
mapl_addconnectivityrename calls append
mapl_donotconnect calls append
mapl_addconnectivity calls mapl_addconnectivityrename, mapl_addconnectivitymany
mapl_terminateimport calls mapl_donotconnect, mapl_donotconnectanyimport, mapl_donotconnectmany, mapl_terminateimportallbut
mapl_addconnectivitymany calls mapl_addconnectivityrename
mapl_donotconnectanyimport calls mapl_donotconnect
mapl_donotconnectmany calls mapl_donotconnect
mapl_stateaddexportspecfrmchldname calls mapl_addconnectivitye2e
mapl_terminateimportallbut calls mapl_donotconnect
mapl_addconnectivityrenamemany calls mapl_addconnectivity
mapl_stateaddexportspecfrmchld calls mapl_stateaddexportspecfrmchldname
mapl_terminateimportall calls mapl_terminateimport