vector_riter_of_offset_default – MAPL
vector_riter_of_offset_default Function
6 statements
Source File
private function vector_riter_of_offset_default(this, i) result(ptr)
Type Bound
VectorRIterator
Arguments
Type Intent Optional Attributes Name
class(VectorRIterator), intent(in) :: this
integer, intent(in) :: i
Return Value type(runEntryPoint), pointer
Calls
Called by
Call graph
vector_riter_of_offset_default calls of
vector_reverse_find_if_not calls of
vector_reverse_find_if calls of
find_if_not calls vector_reverse_find_if_not
find_if calls vector_reverse_find_if