vector_contains_str – MAPL
vector_contains_str Function
14 statements
Source File
private function vector_contains_str(vector, string)
Arguments
Type Intent Optional Attributes Name
type(StringVector), intent(in) :: vector
character(len=*), intent(in) :: string
Return Value logical
Called by
Contents
Source Code
vector_contains_str
Source Code
   logical function vector_contains_str(vector, string)
      type(StringVector), intent(in) :: vector
      character(len=*), intent(in) :: string
      type(StringVectorIterator) :: iter
      iter = vector%begin()
      vector_contains_str = .false.
      do while (iter /= vector%end())
         if (trim(string) == iter%of()) then
            vector_contains_str = .true.
            return
         end if
         call iter%next()
      end do
   end function vector_contains_str
Call graph
print_resource calls vector_contains_str
mapl_getresource_config_scalar calls print_resource
mapl_getresourcefromconfig_scalar calls mapl_getresource_config_scalar
mapl_getresourcefrommapl_scalar calls mapl_getresource_config_scalar
mapl_getresource calls mapl_getresourcefromconfig_scalar, mapl_getresourcefrommapl_scalar