vector_new_vector_copy – MAPL
vector_new_vector_copy Function
10 statements
Source File
private function vector_new_vector_copy(x) result(v)
Arguments
Type Intent Optional Attributes Name
type(VarSpecVector) :: x
Return Value type(VarSpecVector)
Calls
Called by
Call graph
vector_new_vector_copy calls resize
vector_resize_size_kind calls reserve
varspecvector calls vector_new_vector_copy