vector_empty – MAPL
vector_empty Function
4 statements
Source File
private pure function vector_empty(this) result(empty)
Type Bound
MeterNodeStack
Arguments
Type Intent Optional Attributes Name
class(MeterNodeStack), intent(in) :: this
Return Value logical
Called by
Call graph
copy_profiler calls vector_empty
start_name calls vector_empty
copy calls copy_profiler