vector_grow_to – MAPL
vector_grow_to Subroutine
8 statements
Source File
private subroutine vector_grow_to(this, capacity)
Type Bound
entryPointVector
Arguments
Type Intent Optional Attributes Name
class(entryPointVector), intent(inout) :: this
integer(kind=GFTL_SIZE_KIND), intent(in) :: capacity
Calls
Called by
Call graph
vector_grow_to calls vector_capacity, vector_set_capacity
vector_insert_count_size_kind calls vector_grow_to
vector_insert_list calls vector_grow_to
vector_insert_range calls vector_grow_to
vector_push_back calls vector_grow_to
mapl_gridcompsetentrypoint calls vector_push_back
vector_new_vector_range calls vector_push_back
entrypointvector calls vector_new_vector_range
mapl_genericsetservices calls mapl_gridcompsetentrypoint
setservices calls mapl_gridcompsetentrypoint, mapl_genericsetservices
vector_insert_count_default calls insert
vector_insert_one calls insert