verify_typekind_scalar – MAPL
verify_typekind_scalar Subroutine
12 statements
Source File
private subroutine verify_typekind_scalar(x, expected_tk, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x
type(ESMF_TypeKind_Flag), intent(in) :: expected_tk
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
verify_typekind_scalar
Source Code
    subroutine verify_typekind_scalar(x, expected_tk, rc)
      type(ESMF_Field), intent(inout) :: x
      type(ESMF_TypeKind_Flag), intent(in) :: expected_tk
      integer, optional, intent(out) :: rc
      integer :: status
      type(ESMF_TypeKind_Flag) :: found_tk
      call ESMF_FieldGet(x, typekind=found_tk, _RC)
      _ASSERT((found_tk == expected_tk), 'Found incorrect typekind.')
      _RETURN(_SUCCESS)
   end subroutine verify_typekind_scalar
Call graph
verify_typekind_scalar calls esmf_fieldget, mapl_assert, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
verify_typekind calls verify_typekind_scalar, verify_typekind_array
axpy_r4 calls verify_typekind
axpy_r8 calls verify_typekind
gemv_r4 calls verify_typekind
gemv_r8 calls verify_typekind
verify_typekind_array calls verify_typekind
fieldaxpy calls axpy_r4, axpy_r8
fieldgemv calls gemv_r4, gemv_r8
test_fieldaxpy_r4 calls fieldaxpy
test_fieldaxpy_r8 calls fieldaxpy