verify_epoch_equals_freq – MAPL
verify_epoch_equals_freq Subroutine
31 statements
Source File
private subroutine verify_epoch_equals_freq(this, frequency_from_list, swath_grid_label, rc)
Type Bound
samplerHQ
Arguments
Type Intent Optional Attributes Name
class(samplerHQ) :: this
integer, intent(in) :: frequency_from_list
character(len=*), intent(in) :: swath_grid_label
integer, intent(out), optional :: rc
Calls
Called by
Source Code
  subroutine verify_epoch_equals_freq (this, frequency_from_list, swath_grid_label, rc)
    class(samplerHQ)  :: this
    integer, intent(in) :: frequency_from_list
    character(len=*) , intent(in) :: swath_grid_label
    integer, intent(out), optional :: rc
    type(ESMF_Config) :: config_grid
    integer :: hq_epoch_sec
    integer :: freq_sec
    integer :: local_swath_epoch_sec
    integer :: time_integer
    logical :: con
    integer :: status
    type(Logger), pointer          :: lgr
    call ESMF_TimeIntervalGet(this%Frequency_epoch, s=hq_epoch_sec, _RC)
    freq_sec = MAPL_nsecf( frequency_from_list )
    config_grid = this%find_config( swath_grid_label )
    call ESMF_ConfigGetAttribute(config_grid, value=time_integer, &
         label=trim(swath_grid_label)//'.Epoch:', default=0, _RC)
    local_swath_epoch_sec = MAPL_nsecf( time_integer )
    lgr => logging%get_logger('HISTORY.sampler')
    con = (hq_epoch_sec == local_swath_epoch_sec) .AND. (hq_epoch_sec == freq_sec)
    if (.not. con) then
       call lgr%debug('%a %i', 'hq_epoch_sec', hq_epoch_sec)
       call lgr%debug('%a %i', 'local_swath_epoch_sec', local_swath_epoch_sec)
       call lgr%debug('%a %i', 'freq_sec', freq_sec)
    end if
    _ASSERT(con, 'Error in '//trim(swath_grid_label)//' related swath and list in History.rc: Epoch in all swath grids must be equal, and equal to list%freq')
    _RETURN(_SUCCESS)
  end subroutine verify_epoch_equals_freq
Call graph
verify_epoch_equals_freq calls ESMF_ConfigGetAttribute, ESMF_TimeIntervalGet, mapl_assert, mapl_nsecf, get_logger, debug, find_config, mapl_return, mapl_verify
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_nsecf calls mapl_nsecf
find_config calls mapl_assert, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
initialize calls verify_epoch_equals_freq