verify_typekind_array – MAPL
verify_typekind_array Subroutine
13 statements
Source File
private subroutine verify_typekind_array(x, expected_tk, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_Field), intent(inout) :: x(:)
type(ESMF_TypeKind_Flag), intent(in) :: expected_tk
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine verify_typekind_array(x, expected_tk, rc)
      type(ESMF_Field), intent(inout) :: x(:)
      type(ESMF_TypeKind_Flag), intent(in) :: expected_tk
      integer, optional, intent(out) :: rc
      integer :: status
      integer :: i
      do i = 1, size(x)
         call verify_typekind(x(i), expected_tk, _RC)
      end do
      _RETURN(_SUCCESS)
   end subroutine verify_typekind_array
Call graph
verify_typekind_array calls verify_typekind, mapl_return, mapl_verify
verify_typekind calls verify_typekind_array, verify_typekind_scalar
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
verify_typekind_scalar calls mapl_return, mapl_verify, esmf_fieldget, mapl_assert
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
axpy_r4 calls verify_typekind
axpy_r8 calls verify_typekind
gemv_r4 calls verify_typekind
gemv_r8 calls verify_typekind
fieldaxpy calls axpy_r4, axpy_r8
fieldgemv calls gemv_r4, gemv_r8
test_fieldaxpy_r4 calls fieldaxpy
test_fieldaxpy_r8 calls fieldaxpy