wait_all – MAPL
wait_all Subroutine
10 statements
Source File
private subroutine wait_all(this, rc)
Uses
pFIO_AbstractRequestHandleMod
Type Bound
ClientThread
Arguments
Type Intent Optional Attributes Name
class(ClientThread), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine wait_all(this, rc)
      use pFIO_AbstractRequestHandleMod
      class (ClientThread), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      integer:: status
      call this%clear_RequestHandle(_RC)
      !call this%shake_hand()
      _RETURN(_SUCCESS)
   end subroutine wait_all
Call graph
wait_all calls clear_requesthandle, mapl_return, mapl_verify
clear_requesthandle calls mapl_return, mapl_verify, erase, m_begin
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
m_begin calls s_begin
mapl_throw_exception calls initialize
m_erase_one calls erase
s_begin calls s_next
post_wait_all calls wait_all
run calls wait_all, finalize_io_clients_servers, post_wait, run_ensemble
terminate calls wait_all
wait calls wait_all
finalize_io_clients_servers calls terminate
post_wait calls post_wait_all
main calls run, terminate, run_model
mapl_bundlewritencpar calls post_wait
model_finalize calls finalize_io_clients_servers
run_ensemble calls finalize_io_clients_servers
run_model calls post_wait
mapl_varwritencpar calls mapl_bundlewritencpar
mapl_statevarwritencpar calls mapl_bundlewritencpar
extdata_driver calls run