wait – MAPL
wait Subroutine
13 statements
Source File
private subroutine wait(this, request_id, rc)
Uses
pFIO_AbstractRequestHandleMod
Type Bound
MockClientThread
Arguments
Type Intent Optional Attributes Name
class(MockClientThread), intent(inout), target :: this
integer, intent(in) :: request_id
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine wait(this, request_id, rc)
      use pFIO_AbstractRequestHandleMod
      class (MockClientThread), target, intent(inout) :: this
      integer, intent(in) :: request_id
      integer, optional, intent(out) :: rc
      class(AbstractRequestHandle), pointer :: handle
      this%counter = this%counter + 1
      handle => this%get_RequestHandle(request_id)
      call handle%wait()
      call this%erase_RequestHandle(request_id)
      _RETURN(_SUCCESS)
   end subroutine wait
Call graph
wait calls erase_requesthandle, get_requesthandle, mapl_return
erase_requesthandle calls mapl_return, erase, m_find
get_requesthandle calls mapl_return, mapl_assert, m_find
mapl_return calls get_error_message, mapl_throw_exception
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
get_error_message calls at, insert
m_find calls s_find
mapl_throw_exception calls initialize
m_erase_one calls erase
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
s_find calls at, exists, find_index, s_ordereq