wait – MAPL
wait Subroutine
10 statements
Source File
private subroutine wait(this, rc)
Type Bound
MockHandle
Arguments
Type Intent Optional Attributes Name
class(MockHandle), intent(inout), target :: this
integer, intent(out), optional :: rc
Calls
Source Code
   subroutine wait(this, rc)
      class (MockHandle), target, intent(inout) :: this
      integer, optional, intent(out) :: rc
      select type(q => this%owner)
      type is (MockSocket)
         call q%prefix('wait()')
      end select
      _RETURN(_SUCCESS)
   end subroutine wait
Call graph
wait calls prefix, mapl_return
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize