warning – MAPL
warning Subroutine
35 statements
Source File
private subroutine warning(this, message, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, unusable, extra, line, file, rc)
Type Bound
Logger
Arguments
Type Intent Optional Attributes Name
class(Logger), intent(inout), target :: this
character(len=*), intent(in) :: message
class(*), intent(in), optional :: arg1
class(*), intent(in), optional :: arg2
class(*), intent(in), optional :: arg3
class(*), intent(in), optional :: arg4
class(*), intent(in), optional :: arg5
class(*), intent(in), optional :: arg6
class(*), intent(in), optional :: arg7
class(*), intent(in), optional :: arg8
class(*), intent(in), optional :: arg9
class(KeywordEnforcer), intent(in), optional :: unusable
type(StringUnlimitedMap), intent(in), optional, target :: extra
integer, intent(in), optional :: line
character(len=*), intent(in), optional :: file
integer, intent(out), optional :: rc
Called by
Source Code
   subroutine warning(this, message, ARG_LIST, unusable, extra, line, file, rc)
      class (Logger), target, intent(inout) :: this
      character(len=*), intent(in) :: message
      include 'recordOptArgs.inc'
      class (KeywordEnforcer), optional, intent(in) :: unusable
      type (StringUnlimitedMap), optional, target, intent(in) :: extra
      integer, optional, intent(in) :: line
      character(*), optional, intent(in) :: file
      integer, optional, intent(out) :: rc
      _UNUSED_DUMMY(this)
      _UNUSED_DUMMY(message)
      _UNUSED_DUMMY(arg1)
      _UNUSED_DUMMY(arg2)
      _UNUSED_DUMMY(arg3)
      _UNUSED_DUMMY(arg4)
      _UNUSED_DUMMY(arg5)
      _UNUSED_DUMMY(arg6)
      _UNUSED_DUMMY(arg7)
      _UNUSED_DUMMY(arg8)
      _UNUSED_DUMMY(arg9)
      _UNUSED_DUMMY(unusable)
      _UNUSED_DUMMY(extra)
      _UNUSED_DUMMY(line)
      _UNUSED_DUMMY(file)
      _RETURN(_SUCCESS)
   end subroutine warning
Call graph
addchildfromdsometa calls warning
initialize_gc calls warning, mapl_addchild
initialize_pflogger calls warning
warn_empty calls warning
mapl_addchild calls addchildfromdsometa, addchildfromdso
addchildfromdso calls addchildfromdsometa
mapl_esmfstatereadfromfile calls warn_empty
mapl_esmfstatewritetofile calls warn_empty
mapl_initialize calls initialize_pflogger
mapl_checkpointstate calls mapl_esmfstatewritetofile
addchildfromdso_old calls addchildfromdso
capture calls mapl_esmfstatewritetofile
main calls mapl_initialize
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile
mapl_genericstatesave calls mapl_esmfstatewritetofile
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
new_mapl_cap_from_dso calls mapl_initialize
new_mapl_cap_from_set_services calls mapl_initialize
newextdatadriver calls mapl_initialize
run_component_driver calls mapl_addchild
time_ave calls mapl_initialize
ut_regridding calls mapl_initialize