warn_empty – MAPL
warn_empty Subroutine
14 statements
Source File
private subroutine warn_empty(string, MPL, RC)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
type(MAPL_MetaComp), intent(inout) :: MPL
integer, intent(out), optional :: RC
Calls
Called by
Source Code
   subroutine warn_empty(string, MPL, rc)
      character (len=*), intent(in) :: string
      type(MAPL_MetaComp),              intent(INOUT) :: MPL
      integer, optional,                intent(  OUT) :: RC
      class(Logger), pointer :: lgr
      integer :: status
      if (MAPL_Am_I_Root()) then
         call MAPL_GetLogger(mpl, lgr, _RC)
         call lgr%warning(string //&
              ' requested, but state is empty. Ignored...')
      end if
      _RETURN(ESMF_SUCCESS)
   end subroutine warn_empty
Call graph
warn_empty calls mapl_am_i_root, mapl_getlogger, mapl_return, mapl_verify, warning
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
mapl_getlogger calls mapl_getlogger_gc, mapl_getlogger_meta
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_am_i_root_layout calls mapl_am_i_rank
mapl_am_i_root_vm calls mapl_am_i_rank
mapl_getlogger_gc calls mapl_return, mapl_verify, mapl_getobjectfromgc, get_logger
mapl_getlogger_meta calls mapl_return, get_logger
mapl_throw_exception calls initialize
mapl_am_i_rank calls mapl_am_i_rank_layout, mapl_am_i_rank_only, mapl_am_i_rank_vm
mapl_getobjectfromgc calls mapl_internalstateget
get_logger calls get_logger, get_component
mapl_esmfstatereadfromfile calls warn_empty
mapl_esmfstatewritetofile calls warn_empty
mapl_checkpointstate calls mapl_esmfstatewritetofile
capture calls mapl_esmfstatewritetofile
mapl_genericfinalize calls mapl_esmfstatewritetofile
mapl_genericinitialize calls mapl_esmfstatereadfromfile
mapl_genericstaterestore calls mapl_esmfstatereadfromfile, mapl_genericstaterestore
mapl_genericstatesave calls mapl_esmfstatewritetofile, mapl_genericstatesave
mapl_staterecord calls mapl_esmfstatewritetofile
mapl_staterefresh calls mapl_esmfstatereadfromfile
finalize_ calls mapl_genericfinalize
finalize calls mapl_genericfinalize
initialize_ calls mapl_genericinitialize
initialize calls mapl_genericinitialize
mapl_genericrecord calls mapl_staterecord
mapl_genericrefresh calls mapl_staterefresh, mapl_genericrefresh
record_component calls capture
record_state calls mapl_genericstatesave
refresh_state calls mapl_genericstaterestore
mapl_genericwrapper calls record_component