word_size – MAPL
word_size Function
24 statements
Source File
public function word_size(type_kind, rc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: type_kind
integer, intent(out), optional :: rc
Return Value integer
Calls
Called by
Contents
Source Code
word_size
Source Code
   integer function word_size(type_kind,rc)
      integer, intent(in) :: type_kind
      integer, optional, intent(out) :: rc
      integer(kind=INT32) :: i32
      integer(kind=INT64) :: i64
      real (kind=REAL32) :: r32
      real (kind=REAL64) :: r64
      select case(type_kind)
      case (pFIO_INT32)
         word_size = 1
      case (pFIO_REAL32)
         word_size = c_sizeof(r32)/c_sizeof(i32)
      case (pFIO_LOGICAL)
         word_size = 1
      case (pFIO_REAL64)
         word_size = c_sizeof(r64)/c_sizeof(i32)
      case (pFIO_INT64)
         word_size = c_sizeof(i64)/c_sizeof(i32)
      case default
         _FAIL( "unsupported type kind")
      end select
      _RETURN(_SUCCESS)
   end function word_size
Call graph
word_size calls mapl_assert, mapl_return
mapl_assert calls mapl_assert_condition, mapl_assert_return_code
mapl_return calls get_error_message, mapl_throw_exception
get_error_message calls at
mapl_assert_condition calls mapl_throw_exception
mapl_assert_return_code calls get_error_message, mapl_throw_exception
mapl_throw_exception calls initialize
allocate calls word_size
copy_data_to calls word_size
create_remote_win calls word_size
get calls word_size
put calls word_size
read_and_gather calls word_size
read_and_share calls word_size
receive_output_data calls word_size
serialize_buffer_length_int64_1d calls word_size
serialize_buffer_length_logical_0d calls word_size
serialize_buffer_length_logical_1d calls word_size
serialize_buffer_length_real32_0d calls word_size
serialize_buffer_length_real32_1d calls word_size
serialize_buffer_length_real64_0d calls word_size
serialize_buffer_length_real64_1d calls word_size
serialize_int64_1d calls word_size
serialize_logical_1d calls word_size
serialize_real32_1d calls word_size
serialize_real64_1d calls word_size
serialize_buffer_length calls serialize_buffer_length_int64_1d, serialize_buffer_length_logical_0d, serialize_buffer_length_logical_1d, serialize_buffer_length_real32_0d, serialize_buffer_length_real32_1d, serialize_buffer_length_real64_0d, serialize_buffer_length_real64_1d
serialize_intrinsic calls serialize_int64_1d, serialize_logical_1d, serialize_real32_1d, serialize_real64_1d
handle_done_collective_prefetch calls read_and_gather, read_and_share