wrap2d – MAPL
wrap2d Function
9 statements
Source File
private function wrap2d(array) result(wrapper)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: array(:,:)
Return Value type(WrapArray2d)
Called by
Source Code
   function wrap2d(array) result(wrapper)
      type (WrapArray2d) :: wrapper
      class (*), intent(in) :: array(:,:)
      wrapper%placeholder = 0
      _UNUSED_DUMMY(array)
   end function wrap2d
Call graph
wraparray calls wrap2d
set calls wraparray
updatebrackettime calls wraparray
create_subobjects calls set
mapl_gridcreate calls set
run_ calls updatebrackettime
activate_threading calls create_subobjects
initialize_ calls mapl_gridcreate