write_file – MAPL
write_file Subroutine
12 statements
Source File
private subroutine write_file(buffer, unit, rc)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: buffer(:)
integer :: unit
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine write_file(buffer, unit, rc)
      real, intent(in) :: buffer(:)
      integer :: unit
      integer, optional, intent(out) :: rc
      integer :: status
      write(unit, iostat=status) buffer(:)
      _VERIFY(status)
      ! Without the close, maybe the writing is not done?
      close(unit, _IOSTAT)
      _RETURN(_SUCCESS)
   end subroutine write_file
Call graph
write_file calls mapl_return, mapl_verify
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
get_error_message calls at, insert
mapl_throw_exception calls initialize
run calls write_file