write_dims – MAPL
write_dims Subroutine
27 statements
Source File
private subroutine write_dims(dimensions, unit, iotype, v_list, iostat, iomsg)
Arguments
Type Intent Optional Attributes Name
type(StringIntegerMap), intent(in), target :: dimensions
integer, intent(in) :: unit
character(len=*), intent(in) :: iotype
integer, intent(in) :: v_list(:)
integer, intent(out) :: iostat
character(len=*), intent(inout) :: iomsg
Calls
Called by
Source Code
   subroutine write_dims(dimensions, unit, iotype, v_list, iostat, iomsg)
      type(StringIntegerMap), target, intent(in) :: dimensions
      integer, intent(in) :: unit
      character(*), intent(in) :: iotype
      integer, intent(in) :: v_list(:)
      integer, intent(out) :: iostat
      character(*), intent(inout) :: iomsg
      type(StringIntegerMapIterator) :: iter
      iostat = 0
      write(unit,'(a,/)')'dimensions:'
      associate (e => dimensions%end())
        iter = dimensions%begin()
        do while (iter /= e)
           write(unit, '(T8,a,1x,a,1x,i0,/)', iostat=iostat, iomsg=iomsg) iter%key(), "=" , iter%value()
           if (iostat /= 0) return
           call iter%next()
        end do
      end associate
      _UNUSED_DUMMY(iotype)
      _UNUSED_DUMMY(v_list)
   end subroutine write_dims
Call graph
write_dims calls begin, key, next
write_formatted calls write_dims