write_metadata – MAPL
write_metadata Subroutine
16 statements
Source File
public subroutine write_metadata(this, rc)
Type Bound
RegridSupport
Arguments
Type Intent Optional Attributes Name
class(RegridSupport), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
   subroutine write_metadata(this, rc)
      class (RegridSupport), intent(inout) :: this
      integer, optional, intent(out) :: rc
      type (ESMF_VM) :: vm_global
      integer :: status
!$$      if (local_pet == 0) then
         call this%formatter_lat_lon%create_par(this%out_file, comm=MPI_COMM_WORLD, rc=status)
         _VERIFY(status)
         call this%formatter_lat_lon%write(this%cfio_lat_lon, rc=status)
         _VERIFY(status)
         call this%formatter_lat_lon%close(rc=status)
         _VERIFY(status)
!$$       end if
      call ESMF_VMGetGlobal(vm_global, rc=status)
      _VERIFY(status)
      call ESMF_VMBarrier(vm_global, rc=status)
      _VERIFY(status)
   end subroutine write_metadata
Call graph
write_metadata calls ESMF_VMBarrier, ESMF_VMGetGlobal, create_par, mapl_verify
create_par calls mapl_verify, nf90_create, mapl_return
mapl_verify calls mapl_throw_exception
mapl_return calls mapl_throw_exception, get_error_message
mapl_throw_exception calls initialize
get_error_message calls at, insert
main calls write_metadata