write_bundle_single_time – MAPL
write_bundle_single_time Subroutine
19 statements
Source File
private subroutine write_bundle_single_time(bundle, clock, output_file, nbits_to_keep, deflate, quantize_algorithm, quantize_level, zstandard_level, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_FieldBundle), intent(inout) :: bundle
type(ESMF_Clock), intent(inout) :: clock
character(len=*), intent(in) :: output_file
integer, intent(in), optional :: nbits_to_keep
integer, intent(in), optional :: deflate
integer, intent(in), optional :: quantize_algorithm
integer, intent(in), optional :: quantize_level
integer, intent(in), optional :: zstandard_level
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine write_bundle_single_time(bundle,clock,output_file,nbits_to_keep,deflate,quantize_algorithm,quantize_level,zstandard_level,rc)
         type(ESMF_FieldBundle), intent(inout) :: bundle
         type(ESMF_Clock), intent(inout) :: clock
         character(len=*), intent(in) :: output_file
         integer, optional, intent(in)  :: nbits_to_keep
         integer, optional, intent(in)  :: deflate
         integer, optional, intent(in)  :: quantize_algorithm
         integer, optional, intent(in)  :: quantize_level
         integer, optional, intent(in)  :: zstandard_level
         integer, optional, intent(out) :: rc
         integer :: status
         type(FieldBundleWriter) :: newWriter
         call newWriter%create_from_bundle(bundle,clock,output_file=output_File,n_steps=1,time_interval=0,nbits_to_keep=nbits_to_keep,deflate=deflate,quantize_algorithm=quantize_algorithm,quantize_level=quantize_level,zstandard_level=zstandard_level,rc=status)
         _VERIFY(status)
         call newWriter%write_to_file(rc=status)
         _VERIFY(status)
         _RETURN(_SUCCESS)
      end subroutine write_bundle_single_time
Call graph
write_bundle_single_time calls create_from_bundle, mapl_return, mapl_verify, write_to_file
create_from_bundle calls mapl_return, mapl_verify, ESMF_TimeIntervalSet, esmf_fieldbundleget, add_hist_collection, createfilemetadata, set_param, v_push_back
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
write_to_file calls mapl_return, mapl_verify, bundlepost, done_collective_stage
mapl_write_bundle calls write_bundle_single_time