write_to_file – MAPL
write_to_file Subroutine
12 statements
Source File
private subroutine write_to_file(this, rc)
Type Bound
FieldBundleWriter
Arguments
Type Intent Optional Attributes Name
class(FieldBundleWriter), intent(inout) :: this
integer, intent(out), optional :: rc
Calls
Called by
Source Code
      subroutine write_to_file(this,rc)
         class(FieldBundleWriter), intent(inout) :: this
         integer, optional, intent(out) :: rc
         integer :: status
         call this%cfio%bundlepost(this%file_name,oClients=o_clients,rc=status)
         _VERIFY(status)
         call o_Clients%done_collective_stage(_RC)
         call o_Clients%wait()
         _RETURN(_SUCCESS)
      end subroutine write_to_file
Call graph
write_to_file calls bundlepost, done_collective_stage, mapl_return, mapl_verify
bundlepost calls mapl_return, mapl_verify, esmf_fieldbundleget, am_i_initialized, compute_time_vector, correct_topo, regridscalar, regridvector, setup_eta_to_pressure, stage2dlatlon, stage_nondistributed_data, stagedata, v_begin, v_iter_get, v_iter_next
done_collective_stage calls mapl_return, mapl_verify, current, done_collective_stage
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
main calls write_to_file
write_bundle_single_time calls write_to_file
time_ave calls write_to_file
ut_regridding calls write_to_file
mapl_write_bundle calls write_bundle_single_time
regrid_util calls main