writeBnds – MAPL
writeBnds Subroutine
51 statements
Source File
private subroutine writeBnds(cfio, vName, date, curTime, rc)
writeBnds – write time bounds
Write time bounds for time averaging variable.
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
character(len=*), intent(in) :: vName
integer, intent(in) :: date
integer, intent(in) :: curTime
integer, intent(out), optional :: rc
Error return code: 0 all is well 1 …
Calls
Called by
Contents
Source Code
writeBnds
Source Code
      subroutine writeBnds(cfio, vName, date, curTime, rc)
!
! !INPUT PARAMETERS:
!
      type (ESMF_CFIO), intent(in) :: cfio
      character(len=*), intent(in) :: vName
      integer, intent(in) :: date
      integer, intent(in) :: curTime
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      !! Error return code:
                                                !! 0   all is well
                                                !! 1   ...
!
!------------------------------------------------------------------------------
      integer :: vid, corner(4), edges(4)
      integer :: hour, minute, sec, incSecs, timeIndex
      integer :: seconds, timeinc, curSecs
      real(kind=REAL32) :: bndsdata(2)
      integer :: i, rtcode=0
!     make sure user provides the right variable name
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
      if ( cfio%varObjs(i)%timAve ) then
         seconds = DiffDate (cfio%date, cfio%begTime, date, curTime)
         timeinc = cfio%timeInc
!ams          write (strBuf,203) timeinc
!ams 203      format (I6)
!ams          read (strBuf,204) hour, minute, sec
!ams 204      format (3I2)
         call CFIO_parseIntTime ( timeinc, hour, minute, sec )
         incSecs = hour*3600 + minute*60 + sec
!ams         write (strBuf,203) curTime
!ams         read (strBuf,204) hour, minute, sec
         call CFIO_parseIntTime ( curTime, hour, minute, sec )
         curSecs = hour*3600 + minute*60 + sec
         timeIndex = seconds/incSecs + 1
         corner(1) = 1
         corner(2) = timeIndex
         edges(1) = 2
         edges(2) = 1
         bndsdata(1) = (-incSecs + curSecs)/60.
         bndsdata(2) = curSecs/60.
         if ( cfio%varObjs(i)%aveMethod .eq. 'c' ) then
            bndsdata(1) = (-incSecs/2. + curSecs)/60.
            bndsdata(2) = (incSecs/2. + curSecs)/60.
         end if
         if ( cfio%varObjs(i)%aveMethod .eq. 'd' ) then
            bndsdata(1) = curSecs/60.
            bndsdata(2) = (incSecs + curSecs)/60.
         end if
         rtcode = NF90_INQ_VARID (cfio%fid, 'time_bnds', vid)
         if ( rtcode .ne. 0 ) then
            print *, "NF90_INQ_VARID failed in NF90_INQ_VARID for time_bnds"
            if ( present(rc) ) rc = rtcode
            return
         end if
         rtcode = NF90_PUT_VAR(cfio%fid,vid,bndsdata,corner,edges)
         if ( rtcode .ne. 0 ) then
            print *, "NF90_PUT_VAR failed in NF90_PUT_VAR for time_bnds"
            if ( present(rc) ) rc = rtcode
            return
         end if
      end if
      if ( present(rc) ) rc = rtcode
      end subroutine writeBnds
Call graph
writebnds calls nf90_inq_varid, nf90_put_var, cfio_parseinttime, diffdate, varobjs
diffdate calls cfio_parseinttime, julday
esmf_cfiosdfvarwrite1d_ calls writebnds
esmf_cfiosdfvarwrite2d_ calls writebnds
esmf_cfiosdfvarwrite3d_ calls writebnds
esmf_cfiosdfvarwrite calls esmf_cfiosdfvarwrite1d_, esmf_cfiosdfvarwrite2d_, esmf_cfiosdfvarwrite3d_
esmf_cfiovarwrite1d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite2d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite3d_ calls esmf_cfiosdfvarwrite
esmf_cfiovarwrite calls esmf_cfiovarwrite1d_, esmf_cfiovarwrite2d_, esmf_cfiovarwrite3d_