writeBnds – MAPL
writeBnds Subroutine
57 statements
Source File
private subroutine writeBnds(cfio, vName, date, curTime, rc)
Arguments
Type Intent Optional Attributes Name
type(ESMF_CFIO), intent(in) :: cfio
character(len=*), intent(in) :: vName
integer, intent(in) :: date
integer, intent(in) :: curTime
integer, intent(out), optional :: rc
Calls
Called by
Contents
Source Code
writeBnds
Source Code
      subroutine writeBnds(cfio, vName, date, curTime, rc)
!
! !ARGUMENTS:
!
! !INPUT PARAMETERS:
!
      type (ESMF_CFIO), intent(in) :: cfio
      character(len=*), intent(in) :: vName
      integer, intent(in) :: date
      integer, intent(in) :: curTime
!
! !OUTPUT PARAMETERS:
!
      integer, intent(out), OPTIONAL :: rc      ! Error return code:
                                                ! 0   all is well
                                                ! 1   ...
!
!
! !DESCRIPTION:
!     write time bounds for time averaging variable
!EOP
!------------------------------------------------------------------------------
      integer :: sds_index, sfwdata, sfselect, sfn2index
      integer :: sfsnatt, sfendacc
      integer :: sds_id, corner(4), edges(4), stride(4)
      integer :: hour, min, sec, incSecs, timeIndex
      integer :: seconds, timeinc, curSecs
      real*4 :: bndsdata(2)
      character*8 :: strBuf
      integer :: i, rtcode=0
!     make sure user provides the right variable name
      do i = 1, cfio%mVars
         if ( trim(vName) .eq. trim(cfio%varObjs(i)%vName) ) exit
      end do
      if ( cfio%varObjs(i)%timAve ) then
         seconds = DiffDate (cfio%date, cfio%begTime, date, curTime)
         timeinc = cfio%timeInc
         write (strBuf,203) timeinc
203      format (I6)
         read (strBuf,204) hour, min, sec
204      format (3I2)
         incSecs = hour*3600 + min*60 + sec
         write (strBuf,203) curTime
         read (strBuf,204) hour, min, sec
         curSecs = hour*3600 + min*60 + sec
         timeIndex = seconds/incSecs + 1
         corner(1) = 0
         corner(2) = timeIndex-1
         stride(1) = 1
         stride(2) = 1
         edges(1) = 2
         edges(2) = 1
         bndsdata(1) = (-incSecs + curSecs)/60.
         bndsdata(2) = curSecs/60.
         if ( cfio%varObjs(i)%aveMethod .eq. 'c' ) then
            bndsdata(1) = (-incSecs/2. + curSecs)/60.
            bndsdata(2) = (incSecs/2. + curSecs)/60.
         end if
         if ( cfio%varObjs(i)%aveMethod .eq. 'd' ) then
            bndsdata(1) = curSecs/60.
            bndsdata(2) = (incSecs + curSecs)/60.
         end if
         sds_index = sfn2index(cfio%sd_id, 'time_bnds')
         sds_id = sfselect(cfio%sd_id, sds_index)
         rtcode = sfwdata (sds_id, corner, stride, edges, bndsdata)
         if ( rtcode .ne. 0 ) then
            print *, "sfwdata failed in time_bnds"
            if ( present(rc) ) rc = rtcode
            return
         end if
         rtcode = sfendacc(sds_id)
      end if
      if ( present(rc) ) rc = rtcode
      end subroutine writeBnds
Call graph
writebnds calls diffdate
diffdate calls cfio_parseinttime, julday
esmf_cfioeosvarwrite1d_ calls writebnds
esmf_cfioeosvarwrite2d_ calls writebnds
esmf_cfioeosvarwrite3d_ calls writebnds
esmf_cfioeosvarwrite calls esmf_cfioeosvarwrite1d_, esmf_cfioeosvarwrite2d_, esmf_cfioeosvarwrite3d_