XYGridFactory_from_parameters – MAPL
XYGridFactory_from_parameters Function
26 statements
Source File
private function XYGridFactory_from_parameters(unusable, grid_file_name, grid_name, im_world, jm_world, lm, nx, ny, rc) result(factory)
Arguments
Type Intent Optional Attributes Name
class(KeywordEnforcer), intent(in), optional :: unusable
character(len=*), intent(in) :: grid_file_name
character(len=*), intent(in), optional :: grid_name
integer, intent(in), optional :: im_world
integer, intent(in), optional :: jm_world
integer, intent(in), optional :: lm
integer, intent(in), optional :: nx
integer, intent(in), optional :: ny
integer, intent(out), optional :: rc
Return Value type(XYGridFactory)
Calls
Called by
Source Code
   function XYGridFactory_from_parameters(unusable, grid_file_name, grid_name, &
        & im_world,jm_world,lm,nx, ny, rc) result(factory)
      type (XYGridFactory) :: factory
      class (KeywordEnforcer), optional, intent(in) :: unusable
      ! grid details:
      character(len=*), intent(in) :: grid_file_name ! required
      character(len=*), optional, intent(in) :: grid_name
      integer, optional, intent(in) :: im_world
      integer, optional, intent(in) :: jm_world
      integer, optional, intent(in) :: lm
      ! decomposition:
      integer, optional, intent(in) :: nx
      integer, optional, intent(in) :: ny
      integer, optional, intent(out) :: rc
      integer :: status
      character(len=*), parameter :: Iam = MOD_NAME // 'XYGridFactory_from_parameters'
      if (present(unusable)) print*,shape(unusable)
      call set_with_default(factory%grid_name, grid_name, MAPL_GRID_NAME_DEFAULT)
      call set_with_default(factory%grid_file_name, grid_file_name, MAPL_GRID_FILE_NAME_DEFAULT)
      call set_with_default(factory%ny, nx, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%nx, ny, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%im_world, im_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%jm_world, jm_world, MAPL_UNDEFINED_INTEGER)
      call set_with_default(factory%lm, lm, MAPL_UNDEFINED_INTEGER)
      call factory%check_and_fill_consistency(rc=status)
      _VERIFY(status)
      _RETURN(_SUCCESS)
   end function XYGridFactory_from_parameters
Call graph
xygridfactory_from_parameters calls set_with_default, check_and_fill_consistency, mapl_return, mapl_verify
set_with_default calls set_with_default_character, set_with_default_integer
check_and_fill_consistency calls mapl_return, mapl_verify, file_has_corners
mapl_return calls get_error_message, mapl_throw_exception
mapl_verify calls mapl_throw_exception
file_has_corners calls mapl_return, mapl_verify, ESMF_VMBroadcast, ESMF_VMGetCurrent, mapl_am_i_root, nf90_inq_varid, nf90_open
get_error_message calls at, insert
mapl_throw_exception calls initialize
mapl_am_i_root calls mapl_am_i_root_layout, mapl_am_i_root_vm
xygridfactory calls xygridfactory_from_parameters