xyz2latlon – MAPL
xyz2latlon Function
23 statements
Source File
private function xyz2latlon(xyz_coord) result(sph_coord)
Uses
MAPL_Constants
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout) :: xyz_coord(3)
Return Value real(kind=REAL64), (2)
Called by
Contents
Source Code
xyz2latlon
Source Code
   function xyz2latlon(xyz_coord) result(sph_coord)
      use MAPL_Constants, only: PI => MAPL_PI_R8
      real(REAL64), intent(inout):: xyz_coord(3)
      real(REAL64) :: sph_coord(2)
      real(REAL64), parameter:: esl=1.e-10
      real(REAL64):: p(3)
      real(REAL64):: dist, lat, lon
      integer k
      p = xyz_coord
      dist =sqrt( dot_product(p,p))
      do k=1,3
         p(k) = p(k) / dist
      enddo
      if ( (abs(p(1))+abs(p(2)))  < esl ) then
           lon = 0.
      else
           lon = atan2( p(2), p(1) )   ! range [-pi,pi]
      endif
      if ( lon < 0.) lon = 2.*pi + lon
      lat = asin(p(3))
      sph_coord(1) = lon
      sph_coord(2) = lat
   end function xyz2latlon
Call graph
mid_pt_sphere calls xyz2latlon
computegridbasis calls mid_pt_sphere
get_basis calls computegridbasis
cartesian_to_spherical_2d_real32 calls get_basis
cartesian_to_spherical_2d_real64 calls get_basis
cartesian_to_spherical_3d_real32 calls get_basis
cartesian_to_spherical_3d_real64 calls get_basis
spherical_to_cartesian_2d_real32 calls get_basis
spherical_to_cartesian_2d_real64 calls get_basis
spherical_to_cartesian_3d_real32 calls get_basis
spherical_to_cartesian_3d_real64 calls get_basis