zero_pad – MAPL
zero_pad Function
12 statements
Source File
private function zero_pad(number_string, width) result(padded)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: number_string
integer, intent(in) :: width
Return Value character(len=MAX_CHARACTER_LENGTH)
Called by
Source Code
   function zero_pad(number_string, width) result(padded)
      character(len=*), intent(in) :: number_string
      integer, intent(in) :: width
      character(len=MAX_CHARACTER_LENGTH) :: padded
      integer :: num_zeros
      num_zeros = width - len_trim(number_string)
      if(num_zeros > 0) then
         padded = repeat('0', num_zeros) // number_string
      else
         padded = number_string
      end if
   end function zero_pad
Call graph
convert_cf_time_datetime_string_to_iso8601 calls zero_pad
extract_iso8601_from_cf_time_cf_time calls convert_cf_time_datetime_string_to_iso8601
extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time_cf_time
extract_iso8601_from_cf_time_units calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_integer calls extract_iso8601_from_cf_time
get_esmf_time_from_netcdf_datetime_real calls extract_iso8601_from_cf_time
test_extract_iso8601_from_cf_time calls extract_iso8601_from_cf_time