include (CheckFortranSource)

CHECK_FORTRAN_SOURCE_COMPILE (
  ${CMAKE_CURRENT_LIST_DIR}/support_for_assumed_type.F90
  SUPPORT_FOR_ASSUMED_TYPE
)

CHECK_FORTRAN_SOURCE_COMPILE (
  ${CMAKE_CURRENT_LIST_DIR}/support_for_c_loc_assumed_size.F90
  SUPPORT_FOR_C_LOC_ASSUMED_SIZE
)

CHECK_FORTRAN_SOURCE_COMPILE (
  ${CMAKE_CURRENT_LIST_DIR}/support_for_mpi_alloc_mem_cptr.F90
  SUPPORT_FOR_MPI_ALLOC_MEM_CPTR
  MPI
)

CHECK_FORTRAN_SOURCE_COMPILE (
  ${CMAKE_CURRENT_LIST_DIR}/support_for_mpi_ierror_keyword.F90
  SUPPORT_FOR_MPI_IERROR_KEYWORD
  MPI
)




