#!/bin/bash -f

# Script to run the MAPL_GetHorzIJIndex
# Takes three arguments 
# arg 1: MAPL source path
# arg 2: MAPL build path i.e. that contains 'install' subdirectory
# arg 3: run directory path

if [[ $# -ne 3 ]]; then
  echo 'num args should be 3: MAPL_src_dir, build_dir, run_dir; exiting ...'
  exit
fi

export SRC_DIR=$1
export BUILD_DIR=$2
export RUN_DIR=$3
export INSTALL_DIR=$BUILD_DIR'/install/bin'

if [ ! -d $RUN_DIR  ]; then
   mkdir ${RUN_DIR}
   cd $RUN_DIR
else
   cd $RUN_DIR
   rm -rf *
fi

for f in $(find "${SRC_DIR}"/Tests/GetHorzIJIndex -name "*.data")
do
   cp $f .
done

for f in $(find "${SRC_DIR}"/Tests/GetHorzIJIndex -name "*.rc")
do
   cp $f .
done

export ROOT_RC=`grep '^\s*ROOT_CF:' CAP.rc | cut -d: -f2`
export NX=`grep '^\s*NX:' ${ROOT_RC}  | cut -d: -f2`
export NY=`grep '^\s*NY:' ${ROOT_RC}  | cut -d: -f2`

export NPES=`expr ${NY} \* ${NX}`

source ${INSTALL_DIR}/g5_modules.sh

# Default run - use_threads: .FALSE.
export OMP_NUM_THREADS=1
mpirun -np ${NPES} ${INSTALL_DIR}/driver_MAPL_GetHorzIJIndex.x >  run_log 2>&1

# Threaded run - use_threads: .TRUE.
sed -i 's/FALSE/TRUE/g' GetHorzIJIndex.rc

# 1 thread
export OMP_NUM_THREADS=1
mpirun -np ${NPES} ${INSTALL_DIR}/driver_MAPL_GetHorzIJIndex.x >>  run_log 2>&1

# 4 threads
export OMP_NUM_THREADS=4
mpirun -np ${NPES} ${INSTALL_DIR}/driver_MAPL_GetHorzIJIndex.x >>  run_log 2>&1
