name: Build and Publish on Release

on:
  release:
    types: [published]

jobs:
  build-gnu-image:
    name: Build GNU Docker image
    uses: geos-esm/mapl/.github/workflows/build-and-publish-container-workflow.yml@main
    with:
      maplversion: ${{ github.event.release.tag_name }}
      osversion: ubuntu20
      imagename: geos-env-mkl
      baselibversion: v7.5.0
      mpiname: openmpi
      mpiversion: 4.1.4
      compilername: gcc
      compilerversion: 12.1.0
    secrets: inherit

  build-intel-image:
    name: Build Intel Docker image
    uses: geos-esm/mapl/.github/workflows/build-and-publish-container-workflow.yml@main
    with:
      maplversion: ${{ github.event.release.tag_name }}
      osversion: ubuntu20
      imagename: geos-env
      baselibversion: v7.5.0
      mpiname: intelmpi
      mpiversion: 2021.6.0
      compilername: intel
      compilerversion: 2022.1.0
    secrets: inherit
