# Based on examples from the stale action site:
# https://github.com/actions/stale

name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 60
          stale-issue-message: >
            This issue has been automatically marked as stale because it
            has not had activity in the last 60 days. If there are no
            updates within 7 days, it will be closed.  You can add the
            ":hourglass: Long Term" label to prevent the stale action
            from closing this issue.
          days-before-issue-close: 7
          close-issue-message: >
            This issue was closed because it has been stalled for 7 days with no activity.
            You can reopen this issue if you are still working on it.
          stale-issue-label: ':snowflake: Stale'
          exempt-issue-labels: ':hourglass: Long Term,:exclamation: High Priority'

          days-before-pr-stale: 60
          stale-pr-message: >
            This PR has been automatically marked as stale because it
            has not had activity in the last 60 days. If there are no
            updates within 7 days, it will be closed.  You can add the
            ":hourglass: Long Term" label to prevent the stale action
            from closing this issue.
          days-before-pr-close: 30
          close-pr-message: >
            This PR was closed because it has been stalled for 30 days with no activity.
            You can reopen this PR if you are still working on it.
          stale-pr-label: ':snowflake: Stale'
          exempt-pr-labels: ':hourglass: Long Term,:exclamation: High Priority'

          labels-to-remove-when-unstale: ':snowflake: Stale'
          remove-stale-when-updated: true


