name: mapl3docs

on:
  push:
    branches:
      - release/MAPL-v3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy-mapl3-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: blob:none

      - name: Build and Deploy Dev Docs
        uses: ./.github/actions/deploy-ford-docs
        with:
          # Due to a bug in ford, for now we do *not* want to use
          # the full path to the ford input file. Rather, the
          # action will cd into docs/Ford and then run ford
          # relative path to the ford input file.
          ford-input: mapl3docs-with-remote-esmf.md
          doc-folder: docs/Ford/mapl3-doc
          target-folder: mapl3-doc
          deploy-token: ${{ secrets.DOCS_DEPLOY_PAT }}

  ##############################################################################
  # build-and-deploy-mapl3-dev-docs:                                           #
  #   runs-on: ubuntu-latest                                                   #
  #   steps:                                                                   #
  #     - name: Checkout                                                       #
  #       uses: actions/checkout@v4                                            #
  #       with:                                                                #
  #         fetch-depth: 0                                                     #
  #         filter: blob:none                                                  #
  #                                                                            #
  #     - name: Build and Deploy Dev Docs                                      #
  #       uses: ./.github/actions/deploy-ford-docs                             #
  #       with:                                                                #
  #         # Due to a bug in ford, for now we do *not* want to use            #
  #         # the full path to the ford input file. Rather, the                #
  #         # action will cd into docs/Ford and then run ford                  #
  #         # relative path to the ford input file.                            #
  #         ford-input: mapl3docs-with-remote-esmf.public_private_protected.md #
  #         doc-folder: docs/Ford/mapl3-dev-doc                                #
  #         target-folder: mapl3-dev-doc                                       #
  #         deploy-token: ${{ secrets.DOCS_DEPLOY_PAT }}                       #
  ##############################################################################
