name: spack-ci-gcc

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        ref: develop      # Spack version (examples: develop, releases/v0.21)
        color: true       # Force color output (SPACK_COLOR=always)
        path: spack       # Where to clone Spack
        buildcache: false # Do not use the spack buildcache

    - name: Create Spack environment
      run: |
        spack env create spack-env
        spack env activate spack-env

    - name: Find compilers
      run: |
        spack compiler find

    - name: Set default compiler and target
      run: |
        spack config add 'packages:all:compiler:[gcc@13.2.0]'
        spack config add 'packages:all:require:target=x86_64_v3'

    - name: Login
      run: |
        spack -e spack-env mirror add mapl-buildcache oci://ghcr.io/mathomp4/mapl-buildcache
        spack -e spack-env mirror set --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" mapl-buildcache
        spack -e spack-env mirror list
        spack -e spack-env buildcache list

    #- name: Concretize
      #run: |
        #spack -e spack-env concretize

    #- name: Install
      #run: |
        #spack -e spack-env install --add --no-check-signature \
           #esmf gftl gftl-shared fargparse pflogger pfunit yafyaml ecbuild udunits

    #- name: Build with Cmake
      #shell: spack-bash {0}
      #run: |
        #FC=gfortran-13 CC=gcc-13 CXX=g++-13
        #spack -e spack-env load \
           #esmf gftl gftl-shared fargparse pflogger pfunit yafyaml ecbuild udunits
        #cmake -B build -S . -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=Debug -DUSE_F2PY=OFF
        #cmake --build build -j 4
        #cmake --install build

