name: Spack CI GCC Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Do not run if the only files changed cannot affect the build
    paths-ignore:
      - "**.md"
      - "**.pro"
      - "**.sh"
      - "**.perl"
      - ".github/CODEOWNERS"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  spack_builds:
    strategy:
      matrix:
        include:
          - name: "stable"
            use-esmf-develop: false
            run-tests: true
          - name: "develop"
            use-esmf-develop: true
            run-tests: true
    uses: GEOS-ESM/CI-workflows/.github/workflows/spack_gcc_build.yml@project/geosgcm
    name: Spack Build with ESMF (${{ matrix.name }})
    secrets:
      BUILDCACHE_USERNAME: ${{ secrets.BUILDCACHE_USERNAME }}
      BUILDCACHE_TOKEN: ${{ secrets.BUILDCACHE_TOKEN }}
    with:
      use-esmf-develop: ${{ matrix.use-esmf-develop }}
      run-tests: ${{ matrix.run-tests }}
      run-mepo-develop: false
      patch-esmf: true
